### ISSUE TITLE
Disable auto hide controls

### ISSUE THREAD

**Issue by several27** [videojs/video.js#1001]
Is there any option to disable auto hide control bar? Or if not, where I should change source code to add this functionality?

**Comment by djmakwana** [comment]
Any idea how to do this in latest 5.10.4 version? Can I do it without modifying origin video-js.css ? Thanks.

**Comment by vegamedia** [comment]
https://stackoverflow.com/questions/17524198/how-to-hide-video-js-player

`var videoid =document.getElementsByClassName("vjs-control-bar");
videoid[0].style.setProperty("display", "none", "important");`

**Comment by mizmaar3** [comment]
Not working on 5.20.x :(

**Comment by y4my4my4m** [comment]
@mizmaar3 

I found this somewhere else online, I think it may work: `data-setup='{ "inactivityTimeout": 0 }'`

**Comment by gkatsev** [comment]
the `inactivityTimeout` option set to `0` is the currently supported way to do so, as @y4my4my4m mentioned.

**Comment by mizmaar3** [comment]
Ok will try

**Comment by toby11** [comment]
I have tried inactivityTimeout in 7.3.0 and it does not seem to do anything, any other way to stop the controls from hiding?

**Comment by bizos** [comment]
I've the same issue too.

**Comment by Paderman** [comment]
`inactivityTimeout: 0` works fine, but how can this disabled for _Fullscreen_?

**Comment by lifedup** [comment]
> data-setup='{ "inactivityTimeout": 0 }'

You can set the `controlBar` options to show/hide whatever you want.  The typescript types are the easiest way to see what options are available. 

`controlBar: {
      audioTrackButton: false,
      captionsButton: false,
      chaptersButton: false,
      currentTimeDisplay: false,
      customControlSpacer: false,
      descriptionsButton: false,
      durationDisplay: false,
      fullscreenToggle: false,
      liveDisplay: false,
      pictureInPictureToggle: false,
      playToggle: true,
      playbackRateMenuButton: false,
      progressControl: { seekBar: true },
      remainingTimeDisplay: false,
      seekToLive: false,
      subsCapsButton: false,
      subtitlesButton: false,
      timeDivider: false,
      volumePanel: {
        inline: true,
        volumeBar: {
          vertical: false,
          liveDisplay: false,
        },
      },
    },`
