### ISSUE TITLE
Switch to standard minified file naming conventions

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1013]
For 5.0 we should use `video.js` and `video.min.js` instead of `video.dev.js` and `video.js`. The original reason for using the minified version as the main lib is all the variable mangling that closure compiler does to get the size so small. If you built something with private but available functions using the unminified version, it would break on you when you switched to the minified version. 

We should find a better way to communicate that issue and stick with the standard naming. And also we may do less var mangling in 5.0.

### To finish
- [x] Feature implemented  
- [x] Docs/guides updated  
- [x] Examples updated (including JSbins, fiddles, etc.)

**Comment by dconnolly** [comment]
Grabbing this. :facepunch:

**Comment by heff** [comment]
There's probably some [guides and examples](https://github.com/videojs/video.js/tree/master/docs) that need to be updated to use video.min.js instead of video.js.

**Comment by heff** [comment]
Closed by #2087!
