### ISSUE TITLE
Is it required to use absolute path for video-js.swf?

### ISSUE THREAD

**Issue by smohadjer** [videojs/video.js#1027]
The video-js setup guide uses an absolute path to refer to video-js.swf and not a relative path like those used for css and js files. See below:

```
<link href="//example.com/path/to/video-js.css" rel="stylesheet">
<script src="//example.com/path/to/video.js"></script>
<script>
  videojs.options.flash.swf = "http://example.com/path/to/video-js.swf"
</script>
```

Is this required? If so, why? If not, please update documentation so that swf also uses a relative path.

**Comment by oleynikd** [comment]
How do I set `videojs.options.flash.swf` in video.js v5 when I use it with browserify (commonjs)?
Thanks.

**Comment by gkatsev** [comment]
@oleynikd after you require videojs, you should be able to set it then.
