### ISSUE TITLE
Does videojs support capturing a snapshot?

### ISSUE THREAD

**Issue by dingyaguang117** [videojs/video.js#1036]
such as  saving data to clipboard

**Comment by prasadKodeInCloud** [comment]
Its not possible with video.js player when trying to save an image using canvas. Error: "Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)". 

Video is not identified as "HTMLVideoElement". This is a basic use case and glad if you can mention a workaround.

**Comment by BrandonOCasey** [comment]
`player.tech(true).el()` or `player.$('video')` should both work, with the first one being more explicit but depending upon the use of the `HTML` tech (which is the default).

**Comment by talalz94** [comment]
> `player.tech(true).el()` or `player.$('video')` should both work, with the first one being more explicit but depending upon the use of the `HTML` tech (which is the default).

Is this compatible with iOS devices?
