### ISSUE TITLE
Integrate vtt.js for webvtt captions parsing

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1044]
Related: #460 

I wanted to formalize this and open the door for anyone interested in giving this a shot. 

@RickEyre is doing some great work on [mozilla/vtt.js](https://github.com/mozilla/vtt.js), and it'd be great if we could take advantage of that. He's building it so it can be used inside Firefox for vtt parsing and display, and hopes that it can be valuable in other browser contexts as well.

I've done some investigation and [pushed some changes](https://github.com/mozilla/vtt.js/pull/185) to help with IE8 compatibility, but some extra investigation may be needed to determine if we can use vtt.js.

The concerns have mainly been size and compatibility. We need it to be IE8 compatible, and ideally wouldn't add significant weight to the player, e.g. less than 20k minified (not gzipped) would be preferred.

It's been a little while since I looked at it but there was a sizable stringencoding library that seemed like it might not be needed browser-side. There's also a "strongRTLChars" array used for determining right-to-left text, that adds a lot of size and seems like it could be compressed.

Rick may have some additional insight as to where those things are at since we last talked.

Chime in if you're interested in taking this on.

**Comment by gkatsev** [comment]
Fixed via 4e5c28cc561487ff29394d19dce3a420675e4f9d
