### ISSUE TITLE
Player Reset

### ISSUE THREAD

**Issue by mmcc** [videojs/video.js#1050]
Currently with version 4 there's no way to reset a player to the initialized state. In version 3 you could simply do the following things and the player would appear as it does immediately post initialization:
- show the big play button
- hide the controls
- show the poster image

However, version 4...breaks all of these things. Rather than get back to the functionality of version 3, there should be a new method, `Player#reset`, that allows a player to be reset to the original state without calling `dispose()` and instantiating a new one.

**Comment by crs1138** [comment]
Is there any progress on this after 3 years? How can I reset the player after the playlist ended?

**Comment by benjaminpreiss** [comment]
I am also quite curious how to solve this?

**Comment by benjaminpreiss** [comment]
Ah, I think it is partly solved in this issue: [https://github.com/videojs/video.js/issues/2661#issuecomment-150600956](https://github.com/videojs/video.js/issues/2661#issuecomment-150600956)
