### ISSUE TITLE
Support native text tracks when available

### ISSUE THREAD

**Issue by natas123** [videojs/video.js#1054]
UPDATED 2014-10-27 with new direction

Supporting captions through TextTracks and WebVTT was originally built into Video.js before any of the browsers supported it. When Chrome began supporting text tracks we started seeing double captions, and the easiest solution was to strip the tracks from the video element and continue relying on the custom captions. Today, most modern browsers support text tracks natively, including iOS Safari where we can't display custom captions in fullscreen mode. A better approach now would be to rely on native text track support to a greater degree.

After doing some research with @mmcc, I think we should do a 180 and rely fully on native text tracks **when available**. There's a few potential complications with doing this:
- The custom controls will often overlap the native captions. We can mitigate this to some degree by making the captions area higher by default (like Chrome), or using the `-webkit-media-text-track-display` selector that affects the shadow dom of the captions.
- Providing a captions styling interface for end-users relies on browser support of the the `::cue` pseudo selector. Chrome supports it but it doesn't appear Firefox does.

We'll need to continue to rely on our custom captions anywhere Flash is used (IE8 and currently HLS also), and possibly in IE9 & 10 depending on how good their support is. I'm assuming IE11 has decent support but haven't checked yet.

There's two main pieces to captions support, **TextTracks** and the **CaptionsDisplay**. **TextTracks** will parse the WebVTT file contents and create "cues" with a startTime and an endTime. If the media's currentTime is between the startTime and endTime, the cue is considered "active". TextTracks can be used for captions, subtitles, chapters, descriptions, and also metadata tracks which could represent anything (e.g. timeline thumbnail images).

The **CaptionsDisplay** displays the text of any currently active cues for captions tracks. The logic to display captions can get pretty complex when it comes to specific caption positioning, vertical text languages, and mulitple tracks showing at once that can't overlap. (Our current implementation only support very simple text)

To move in this direction, we need to:

1. Build the text track API support at the tech level. This includes `addTextTrack` and `textTracks`.
2. Switch the player API to pass through the API calls instead of relying on its own implementation, and also to pass through the initial track information to the tech.
3. Update the MediaTechController to load the track shim in cases where text tracks aren't supported natively.

One situation to consider is ads that use the same video element. Whether the tracks get cleared with a new source or not, there's going to be some extra work to support that.

--------------------------------------------------
Original Title: multiple subtitles
Original Description:
...We need and advanced web player to be integrated in our product. We need the player to be able to include multiple subtitle tracks so the user can show/hide subtitles and toggle between the diferent tracks, and we need it to work on desktop and mobile devices. In the current version, it seems subtitles does not work in Android and iOS...

**Comment by gkatsev** [comment]
Fixed via 4e5c28cc561487ff29394d19dce3a420675e4f9d
