### ISSUE TITLE
Controls failing with some RTMP streams

### ISSUE THREAD

**Issue by ghost** [videojs/video.js#1071]
Some RTMP streams return json data that fails to parse. The video is streaming properly until i.e. pause button is pressed, which stops the playback and breaks the player, so that it can't restart (a page refresh is needed).

Debug consoles of various browsers throw errors like:

> FF: "SyntaxError: missing : after property id"
> Chrome: "Uncaught SyntaxError: Unexpected token -"
> IE: "Expected ':' char"

Here's a test case: http://jsfiddle.net/s8hC3/

Same issue is extensively covered here: http://www.longtailvideo.com/support/forums/jw-player/servers-and-streaming/19772/javascript-error-missing-after-property-id/

**Comment by wangxd8** [comment]
I want to know how you did it, because I have the same problem
