### ISSUE TITLE
Video Error,[object Object] in IE11

### ISSUE THREAD

**Issue by vgf62** [videojs/video.js#1097]
I have a weird issue with IE11. After some testing this is what I've found:
- this page contains 11 video files and works fine: 
  http://www.vuototecnica.net/video-js/demo.html
- this page contains one more video and doesn't work well in IE11: http://www.vuototecnica.net/video-js/demo2.html

IE Console reports a Video Error,[object Object] and you can't run the 11th video (see the loading spinner). More video files, more errors and loading spinners.
With Firefox, Chrome and Safari the page works perfectly.
Standard HTML5 video page with 20 video files works fine too: http://www.vuototecnica.net/video-js/demo3.html

**Comment by AsishDas** [comment]
Did anyone found the exact cause of this problem? and way to solve it apart from setting up new windows 7 installation?

**Comment by Bokis** [comment]
I also have the same problem on Browserstack Win7 IE10-11. It's working well on IE9. 
I have also heard from visitors of my page that they have this problem. I can't see a solution for this?

![win7_ie_11 0](https://cloud.githubusercontent.com/assets/569024/7856191/6fca80fa-0527-11e5-98cf-3739f153b438.jpg)
![win7_ie_10 0](https://cloud.githubusercontent.com/assets/569024/7856192/6fcd3688-0527-11e5-8bee-2d86e0ab968e.jpg)

**Comment by mmcc** [comment]
@Bokis Can you reproduce on a real VM? Browserstack fails pretty hard at video / Flash in general, so it's really not a good way to test.
