### ISSUE TITLE
css:transform and scrubber

### ISSUE THREAD

**Issue by commonpike** [videojs/video.js#1102]
See a JSBin of the issue here http://jsbin.com/qovayule/1

If transform:scale is applied to the video or any of its parent elements, the scrubber (or in fact any slider elements) don't correctly respond to mouse interaction. In the above jsbin, clicking halfway the scrubbers tracker positions the playhead at the end.

Its not an easy issue and its not limited to videojs. The problem is that getBoundingClientRect returns .. well ... values that don't correspond to the mouse events pageX and pageY. jQueryUI has the same problems, ao.

As an intermediate solution for users that run into this problem, I would suggest to just hide the sliders with css.  If anyone knows how to disable mouse interaction on the progress bar, so we can show it non-interactive, please let us know.

**Comment by makker** [comment]
@heff I also have a same issue as @commonpike. We also have a 'transform: scale(n, n)' style in one of the video elements parents. And this causes the MouseTimeDisplay component, and the slider heads in SeekBar and VolumeBar to position incorrectly in relation to mouse pointer position.  

I have found a way to fix this and working on implementing it to videojs. The thing is that when mouse is over the SeekBar it's position is calculated continuously. And my fix loops through video element parents and gets and multiplies their scale values from the computed styles. I feel this may affect performance and should probably be enabled with a setting. 

In our case, scale is changed (to one of the video's parent elements) when window is resized. So the scale doesn't need to be calculated every time, but only after window size changes. And then it could be saved to a variable. In some other cases it only needs to be calculated once and in some other cases continuously. 

So my suggestion is that there is a new option added to videojs, options.html5.calculateTransformScale with option values 'never' (default value) | 'init' | 'once' | 'windowresize' | 'always' ). Is this ok. Is the option place and name OK? How about the option values?

My fix without options can be found here:
https://github.com/makker/video.js/commit/b90ef1a0f518ae80aec4b6dc3cf4afa7871391f8
https://github.com/makker/video.js/tree/fix-css-transform-issue-1102

**Comment by makker** [comment]
Improved my code so that it now saves the calculated scale on first time it's needed and updates it every time after window is resized.
