### ISSUE TITLE
Skip to a certain timecode?

### ISSUE THREAD

**Issue by seabasss** [videojs/video.js#1109]
Hi!

Is it possible to start the movie from a certain timecode when hitting the play button in video js?

Thanks!

**Comment by Histonic** [comment]
Hello,
I need to start the play of a video from a certain timecode, but from a link in the page. So far I had this short code I used with a standard html <video> element and that used to work :

<script type="text/javascript">
		var lecteur;
		function timecode(secondes) {
		    lecteur = document.getElementById("mavideo");
		    lecteur.currentTime = (secondes);
		    lecteur.play();
		}
	</script>
and the link :
<a href=#mavideo onclick="timecode(60)">play from 1 min</a>

I just copyed it after using video.js and... it doesn't work.
Can anyone help me please ?

**Comment by matiaszumbo** [comment]
Hi, it's possible to read the timecode from video?
