### ISSUE TITLE
Autoplay does not work in Chrome

### ISSUE THREAD

**Issue by eurojojo** [videojs/video.js#113]
I use video-js 3.0, for sake of the loop. In 2010 I developed moving photos. See www.photion.info . Since then I had troubles to get the loop working. It works fine now in Firefox, Internet Explorer and on my Android phone. However, in Chrome the clips do not autostart. Tried everything, read every blog. Looks like it is a problem in video-js, since others have got it running in Chrome without video-js.

**Comment by sachin-weboniselab** [comment]
Still, I am facing autoplay issue with Video.js 5.16.0. Can you please suggest any solution.
