### ISSUE TITLE
Automated acceptance (integration) testing?

### ISSUE THREAD

**Issue by floehopper** [videojs/video.js#1148]
Is anyone aware of any video.js _acceptance_ tests (as opposed to unit tests) running anywhere?

Would there be any merit in setting up acceptance tests (using something like Selenium [1]) which loaded a page including a video.js player, clicking play and waiting for a player event to check whether the video is playing?

I see that SauceLabs offer _free_ automated testing with selenium for open-source projects [2] and they offer an impressive array of platforms [3].

It feels like this could be a nice way to automatically build a matrix of supported browsers/OSes/devices.

[1] http://docs.seleniumhq.org/
[2] https://saucelabs.com/opensauce
[3] https://saucelabs.com/platforms

**Comment by gkatsev** [comment]
Given that we currently test Video.js in browsers using Karma and Browserstack, we're pretty close to this. It's probably good to write some true Integration tests but I'm not sure it gives us a huge benefit compared to where we were in 2014.
Therefor I'm going to close this for now and any test additions would still be greatly welcome!
