### ISSUE TITLE
IE paused status set to true when skipping the video forward

### ISSUE THREAD

**Issue by dseijts** [videojs/video.js#1168]
In IE, when I skip forward (not backwards) the paused() function returns true, but the video keeps playing.

The behavior that paused() returns true while skipping and returns false right after seems to be on all browsers, but on IE paused() returns true right after that again.

I've tested it on Windows 8, IE 10 and 9, 8 and below are making use of the flash fallback and don't seem to be bothered with it.

**Comment by gkatsev** [comment]
One thing that we should probably do is that on browsers that support playbackRate, we can set the playbackRate to zero while seeking instead of pausing it. Though, that won't fix the older IEs.
I'm inclined to just call it a browser bug.

**Comment by heff** [comment]
Fwiw, the other day I noticed that the native controls of one of the major browsers was throwing play/pause events when scrubbing the same way video.js does. Or maybe it was youtube, or both. Either way, I'm more comfortable with that behavior now. And if IE can't support it, it's definitely an IE bug.

**Comment by gkatsev** [comment]
Given that Video.js 7 no longer supports these browsers and we haven't really heard more on this subject, I'm closing this issue.
