### ISSUE TITLE
flash player: lots of js errors if player is hidden

### ISSUE THREAD

**Issue by mkoryak** [videojs/video.js#117]
to reproduce:

create html as in the quickstart but use an mp4 file on firefox, because it is not supported in html5
cause the player to fall back to flash via **V**("player_id")
press play, the movie plays. 
hide the player div via firebug

actual:

firebug console will show errors, one per second:
 (VideoJ...
video.js (line 21)
this.el.vjs_getProperty is not a function
[Break On This Error]  
...){try{this.el.currentTime=seconds}catch(e){_V_.log(e,"Video isn't ready. (VideoJ...

expected:

no errors in console

**Comment by aaesis** [comment]
hi guys, can you help me with my bug?


i am using decast running in videojs 5.

The thing is when I remove the video dynamically. i got an error:

"Uncaught TypeError: this.el_.vjs_getProperty is not a function"
"Player api is not ready yet or working"

my code is 

when rendering the player at first load:
`dacast(dacast_video_url, 'video', {player: 'vjs5'});
 that.dacast_player = dacast.players[dacast_video_url];`

when triggering the button close:
`that.dacast_player.dispose()`


please help help me

**Comment by mmcc** [comment]
I don't know what dacast is, but this question feels better suited for them. Sorry!
