### ISSUE TITLE
Fullscreen not working when playing within iframe

### ISSUE THREAD

**Issue by rainboxx** [videojs/video.js#119]
Having a video within an iframe.  Chrome does nothing when clicking on fullscreen, Firefox goes "full iframe".  Both are the latest public versions.  I guess Chrome is refusing to go fullscreen.

Maybe it would be a solution to load the flash when going fullscreen when that video is played within an iframe (eg. through a setup key).  What dou you think?

Best,
  Matthias

**Comment by enbplas11** [comment]
Good,

I can do fullscreen on a iframe without using the tag allowfullscreen inside the iframe.

What I need is this:

<Iframe src = "http://cdn.clappr.io"> </ Iframe>

I'm using the version clappr-0.2.58

I need your help

**Comment by enbplas11** [comment]
I can do fullscreen on a iframe without using the tag allowfullscreen inside the iframe.

What I need is this:

`<Iframe src = "http://cdn.clappr.io"> </ Iframe>`

I'm using the version clappr-0.2.58

I need your help

**Comment by gkatsev** [comment]
@enbplas11 you cannot do fullscreen inside an iframe without the iframe includeing the `allowfullscreen` attribute.
