### ISSUE TITLE
video overlapping bottom control-bar on chrome when within css transform:scale

### ISSUE THREAD

**Issue by commonpike** [videojs/video.js#1192]
When video-js is playing within a css transform:scale, under certain conditions (having to do with the amount of scale, i guess), the video will overlap the control-bar. as the user gets active, the control-bar may flash up shortly, but immediately disappear behind the video again (you can see its actually behind the video if you hide the video element). z-index seems irrelevant.

If you think you see this behaviour, try to remove the css bottom:0 from the scrollbar, and turn it into top:0. you will see it behaving normally, when you're active, on top of the video. increase top:0 slowly, until at a certain point somewhere halfway the video you can see it fall apart; first, the background disappears, then, still increasing the top, the buttons, and finally the scrubber. freaky.

Now add 

``` css
.video-js .vjs-control-bar {
    -webkit-transform: translateZ(0);
}
```

to your css, et voila, behaves normal. even freakier.

*-pike

**Comment by vmarkovtsev** [comment]
@commonpike Thanks so much for this `translateZ` hack. I was about getting mad.
I get this problem with the recent Chrome. It is not related to videojs.

**Comment by murray971** [comment]
same for me i have a fixed size window in electron and when ever i get above a certain size controls go behind.  this fixes it.

**Comment by Bahir** [comment]
I confirm that this bug is still on using latest videojs (7.18.1).
At MacOS Chrome it shows controls ok. At Windows the same version of Chrome control are out.
Solved by adding transform: translateZ(0) to controls
