### ISSUE TITLE
Test builds

### ISSUE THREAD

**Issue by ange007** [videojs/video.js#1201]
Why not posted test build `(dist)` of a player after commit?
I think it would be more convenient than to collect self.
Or it is difficult?

**Comment by ange007** [comment]
What concerning this question?

**Comment by heff** [comment]
The plan is to move to including dist/ in master, probably starting with v5.0.

**Comment by ange007** [comment]
It is a pity that and there are no test assemblies, and there is no opportunity to test fresh functions without need to download a repository and build a player hemself.

**Comment by heff** [comment]
@ange007 there are. We don't build them in master or stable but we do as tags, that get pushed to npm and added as releases.

https://github.com/videojs/video.js/releases
https://github.com/videojs/video.js/tree/v5.0.0-31

**Comment by ange007** [comment]
And so as it is made, and I thought that anything of that kind isn't present.
Then I apologize.

**Comment by heff** [comment]
No problem. Let us know how it works for you.

On Saturday, June 6, 2015, Vladimir B. <notifications@github.com> wrote:

> And so as it is made, and I thought that anything of that kind isn't
> present.
> Then I apologize.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/1201#issuecomment-109585657>.
>


-- 
Sent from mobile
