### ISSUE TITLE
Change the classname vjs-control to vjs-button

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1204]
Originally 'control' was going to be the parent class of buttons and all other controls, but in practice only buttons use vjs-control. It would be a lot cleaner if we just vjs-button for button elements.

This would break existing skins so should wait for a major release. Though it's possible we could duplicate classes to help in the transition.

**Comment by heff** [comment]
We discussed this a little on Friday, and the conclusion was that we need to switch to use the `<button>` element first, then decide what makes sense here classname wise. I think we should still have a `vis-button` class, and then decide if the `vjs-control` class is still necessary. It would be nice if the CSS class names matched the class inheritance.

**Comment by dmlap** [comment]
Decided to add vjs-button instead of removing vjs-control

**Comment by forbesjo** [comment]
Working on this.

**Comment by heff** [comment]
Closed by #2084!
