### ISSUE TITLE
Crashing IE8

### ISSUE THREAD

**Issue by dchichizola** [videojs/video.js#1213]
What happened? 
Opening any site with the latest version of videojs in it crashes IE8 immediately or after hover the viewport. I tried to open my test site: http://mygoldenticket.leadinglabels.com.au/test/index_video2.html and it crashed. I tried with your site www.videojs.com and it also crashed IE8.

What should have happened? 
It should just work as usual.

Video.js version (e.g. v4.3.0)
4.5.1
Video.js plugins used (e.g. videojs-youtube)
video-js 
no plugins

Browsers + platforms where this is happening (e.g. Windows XP IE8)
Windows XP - IE8
Browsers + platforms where this is NOT happening (e.g. Mac Chrome 30)
Windows 7 - IE9+, Chrome, Firefox, Safari and iOS X+ Firefox, Chrome, Safari.
Reduced test case or online example (link)
Check my link from the first question.
Thanks
Regards,
Dante

**Comment by heff** [comment]
Do we know the current status off this issue? @mmcc, could the `@media \0screen` piece be affecting the video.js site in IE8 too?

**Comment by mmcc** [comment]
I somewhat doubt it since the IE8 crash is only for the site itself, but not just a page with the player on it. To be terribly honest, I'm just holding off on debugging this until I see whether or not it's happening on the new design, then dealing with it there.

**Comment by mmcc** [comment]
For what it's worth, it appears that videojs.com no longer crashes IE8. There are some layout issues, but at least this one's closed.

**Comment by davewallace** [comment]
Hey guys, I just whipped open the videojs.com home page in IE8 WinXP with Flash Player 11.8, no dice. It doesn't crash like the original issue, but rather no player turns up at all (save the big play button). This was on a real test machine, screenshot below:

![videojs com_ie8](https://cloud.githubusercontent.com/assets/1988022/7974189/d1885002-0ab2-11e5-9c32-af39d964b8a9.PNG)

Also, virtualised testing on Win7 IE8 with Flash Player 17.0 via browserstack.com gives the same result.

**Comment by mmcc** [comment]
Thanks for checking @davewallace. I saw the same thing, but I think it's just because of how we did the responsive sizing for IE8. I feel pretty confident that this can be opened on the [website repo](http://github.com/videojs/videojs.com), but we're entirely re-writing the website, so hopefully this is a moot point in a few weeks.

**Comment by davewallace** [comment]
Ahh, no problems then, sorry I jumped ahead a bit too soon!
