### ISSUE TITLE
Expose utility functions

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1232]
I'm opening this issue to discuss the idea of exposing more utility functions, e.g. vjs.on() and vjs.obj.each(). If we decide to expose more, we'll use this issue to discuss the right way to do that.

### Background
To date we've avoided exposing too many top-level utility functions because we're not trying to build and support a general use case utility library like jquery or underscore/lodash. Limiting the utility functions to just the capabilities we need in the internal video.js codebase helps keep them small, focused, and performant.

We've also never discouraged anyone from using jquery alongside video.js or even building plugins/components that require it. So "you can use jquery" has been one of the excuses for not exposing the internal utilities.

Many of these internal utility functions are already available when extending video.js components, e.g. Button.prototype.on(), but just not available to be used just on their own, e.g. vjs.on(any_element, 'event', fn).

The addition of plugins have encouraged a lot of new and interesting development on top of video.js specifically, and raises the question of whether or not it's still best to keep these functions private and require plugins to either use a lib like jquery/underscore or duplicate the same functionality manually when needed.

### Discuss
- Do the old reasons for keeping utility functions private still stand up? 
- Are there any other positives/negatives to either side that aren't mentioned here?

### UPDATE 2015-03-16
We're now in development of v5.0 and have removed Closure Compiler's aggressive variable mangling, as well as started to add ES6 modules + Browserify. So all properties of `videojs` will be publicly available (not mangled) but we have new options for creating internal utility modules that don't get exposed. The conversation is still essentially the same but the implementation will look different.

**Comment by heff** [comment]
@videojs/core-committers we need to revisit this one now that we're in 5.0 development, and it applies to PR #1909.

Last comments in IRC were from @gkatsev and @dmlap about putting everything on the root object, `videojs.something`. Reason being it would force us to keep the API small and well defined.

When @mmcc and I were previously discussing we liked grouping functions under `videojs.util`. Partly to make it clear that videojs is not a utility library like lodash or jquery. @mmcc may be able to add other details.

With 5.0 we're making a big push improving the plugin authoring experience, so I want to make sure we're taking that into consideration with what we're doing here. For example do we add extra functions because of convenience even if they're not specifically used inside core? @dmlap and @gkatsev might actually be the best to speak to that. Would there be any utilities that would come in handy as a plugin author? Or what if you always had a reference to lodash and could expect those functions to always be there for plugins?

Finally, we get a lot of extra language features with the ES6 transition, so I'd like to have a better understanding of where our current utils overlap with ES6, and also the two with lodash. Bascially we need to come up with a final set and where the functions will be coming from.

**Comment by gkatsev** [comment]
Whatever we do expose, if it is also used internally, it shouldn't be available.

**Comment by heff** [comment]
@gkatsev your comment isn't very clear. Can you expand on that?

**Comment by gkatsev** [comment]
Updated my comment. Forgot a negation.

**Comment by carpasse** [comment]
I really like the idea of exposing the methods you mentioned.

vjs.on
vjs.off
vjs.one
vjs.trigger
vjs.createEl
vjs.obj.create
vjs.obj.each
vjs.obj.merge
vjs.obj.deepMerge
vjs.obj.isPlain
vjs.obj.isArray
vjs.bind
vjs.addClass
vjs.removeClass
vjs.get

Nowadays  more and more projects are not relying on jquery or lodash (specially if they use a framework like angular or react) so to have this methods available from videojs will be mostly helpful.

**Comment by thijstriemstra** [comment]
My plugins use the vjs.formatTime method to manipulate display/remaining/duration time. Since it's not exposed in a public API I'm currently copying it into each plugin codebase which is not ideal at all. Is it possible to export this method? Also see #1922

**Comment by brianpkelley** [comment]
While I can't comment on specific methods or variables, the suite of plugins I've created rely on the end user using the dev build.  At work I'm using a custom build process to package all of the plugins and minimizing (without mangling) video.js.  So I'm all for exposing more.

I feel creating plugins for a video player library should be framework agnostic.  Why develop plugins that require frameworks that include duplicated functionality?  I'm not advocating turning video.js into a utility framework, but why restrict your plugin developers?

**Comment by dmlap** [comment]
We decided that utility methods should be directly on the videojs object.
```
videojs.on(...);
```

**Comment by heff** [comment]
Pieces of this have been merged in with #2182 and #2139. I'm going to shift the requirement to export every utility function to 5.1 so we can get 5.0 released.

**Comment by dmlap** [comment]
I agree exporting new utilities can wait for 5.1 but we've dropped quite a few of the old utilities in the transition to 5.x (#2321 and #2322, for instance). It doesn't seem like the right move to break backward compatibility for one minor release to me.

**Comment by heff** [comment]
I'm fine with moving this back to 5.0 since we're waiting for the BC player testing and migration before officially releasing 5.0.

**Comment by gkatsev** [comment]
Going to close this since with the 5.2.0 release we're exporting a bunch of utilities including some DOM ones. Moving forward, we can decide on a case by case basis whether we need to export more but I think this is largely solved.
