### ISSUE TITLE
Play button does not hide on autostart and Chrome 35.0.1916.114 m sometimes

### ISSUE THREAD

**Issue by mdempfle** [videojs/video.js#1237]
What happened? (actual results)
- When using autoplay the big play button does not hide sometimes when using 

What should have happened? (expected results)
- Play button should disapear and othe controls available

Video.js version (e.g. v4.3.0)
- version 4.6.1

Video.js plugins used (e.g. videojs-youtube)
- demo that comes with the download

Browsers + platforms where this is happening (e.g. Windows XP IE8)
- win 7 - Chrome 35.0.1916.114
  Browsers + platforms where this is NOT happening (e.g. Mac Chrome 30)
- win 7 - Firefox 29.0.1

Reduced test case or online example (link)
http://www.tinywebgallery.com/test/video-js/demo2.html
This is the demo from the download with added autoplay.
Press the reload button of the browser sometimes cause that the play button does not disaper anymore. Making a hard reload (Developer tools open clicking "Hard reload") causes to fix this most of the time.
Using the Javascript api to start the player with 
https://github.com/videojs/video.js/blob/stable/docs/guides/api.md
does not make a difference. It is even worse:
http://www.tinywebgallery.com/test/video-js/demo3.html
here the play button never disapears.

Best, Michael

**Comment by aproni34f** [comment]
I can still replicate this issue with videojs 7 even in Chrome. Note that I am opening video in fancybox. The only difference is that when I use absolute video url, then the player button remains, while if I use relative url, then it works an intended:

absolute url (play button remain visible): https://interactivepixel.net/tst/2/videojs.html

relative url (works as intended): https://interactivepixel.net/tst/2/videojs_2.html

You can look at the source code. I tried add timeout in fancybox open to init video js with delay but no change. Note however it only happen sin fancybox. If I try adding video to body, then it doesnt happen.

**Comment by gkatsev** [comment]
Not sure exactly what the difference is, but it seems like it's fancybox autoplaying manually and Video.js isn't picking it up. In `vidoejs.html` even if I remove `autoplay` param from the video element, it still autoplays.

**Comment by aproni34f** [comment]
Yes, fancybox does autoplay, but if I turn off autoplay in fancybox and try to play with videojs, the same weird issue with absolute/ relative url (absolute url doesnt want to autoplay)

https://interactivepixel.net/tst/2/videojs3.html
