### ISSUE TITLE
Autoplay in Chrome stopped working.

### ISSUE THREAD

**Issue by cdeutsch** [videojs/video.js#1240]
I have an app that's over a year old and I can't get Chrome to autoplay anymore using video.js 

Fiddle:
http://jsfiddle.net/cdeutsch/cjyB3/

I'm guessing something in Chrome changed.

I just confirmed that fiddle works in Chrome 34.0.1847.116 on windows (which amazingly I had open and not updated)

Does not work in 35.0.1916.114 on OSX

**Comment by kwolniak** [comment]
I have Chrome 49 OSX, and autoplay don't work in Chrome for me, but it works in Firefox.
What can I do?

**Comment by jeicd** [comment]
Same problem, autoplay doesn't work on Chrome 49 Windows 8.1.

**Comment by kjkta** [comment]
I'm having the same problem with the latest versions of vjs and chrome.

Having to resort to this at the moment:
```window.onload = function() {
  document.querySelector('#hero-vid video').play()
}```

**Comment by ChristianGiupponi** [comment]
Same problem for me

**Comment by ngocketit** [comment]
Same problem here but it was with mobile Chrome: 
`Mozilla/5.0 (Linux; Android 5.0.2; AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36`

Removing `preload` doesn't work for me.

**Comment by mikhoul** [comment]
Same here...

**Comment by UralZima** [comment]
+1, even if I add player.play() right after creating video object, it doesn't work in latest chrome, only firefox

**Comment by UralZima** [comment]
Only this works for me:
setTimeout(function() { player.play(); }, 1000);

**Comment by acevski48** [comment]
you should try using video on local server insted of external link. Auto play workd for me from lokal server.

**Comment by sergibondarenko** [comment]
On Android, you can autoplay if you put `muted` option
```
<video autoplay muted>
  <source src="video.webm" type="video/webm" />
  <source src="video.mp4" type="video/mp4" />
</video>
```
https://developers.google.com/web/updates/2016/07/autoplay
