### ISSUE TITLE
Bug after hibernation

### ISSUE THREAD

**Issue by ghost** [videojs/video.js#1254]
OS: OSX 10.9.3
Connection: 10mbps
Version: Popcorn-Time Mac 0.3.1

Hi,
As a follow up of this thread
https://github.com/popcorn-official/popcorn-app/issues/701

There's a problem with videojs and hibernation on OSX.
After OSX goes to sleep, video doesn't resume, depending on the versions it is either a forever spinning symbol (0.3) or a dead end cross symbol (0.3.1) forcing to restart the application.
Thanks

![2](https://cloud.githubusercontent.com/assets/164418/3122383/b1028688-e766-11e3-87e5-bb0f4753d86b.jpg)
![1](https://cloud.githubusercontent.com/assets/164418/3122382/abe7e350-e766-11e3-87c3-eb956e54176e.jpg)

**Comment by gkatsev** [comment]
Hm... yeah, not sure whether there's really anything we can do.

**Comment by gkatsev** [comment]
I'm closing this as a browser bug.
