### ISSUE TITLE
[IE8] Null Tech on Load

### ISSUE THREAD

**Issue by tomjohnson916** [videojs/video.js#1266]
In IE8, if you load a player with a null, non-conforming, or stalled source; the player will break and become non-responsive prior to triggering the appropriate error. The root of the issue is due to the tech not instantiating.

https://github.com/videojs/video.js/blob/master/src/js/player.js#L590

**Comment by mmcc** [comment]
Is this still an issue?

**Comment by mmcc** [comment]
@gkatsev ping? Have we seen this in 5.0?

**Comment by gkatsev** [comment]
No clue. Also, unfortunately, we lost what the link above referenced.

**Comment by mmcc** [comment]
Ok. Closing this and if we see it again we can reopen.
