### ISSUE TITLE
Flash Fallback doesn't support src attribute

### ISSUE THREAD

**Issue by cbeckr** [videojs/video.js#1274]
Flash fallback silently fails when the video source is provided in the `src` attribute of the `<video>` rather than as a `<source>` element.
This is the default output of the Rails [`video_tag`](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-video_tag) helper if only one source is provided.

Sample: http://jsfiddle.net/Anyt8/2/
- When referencing an .mp4 source in this manner, Firefox 29.0.1 / Mac will attempt playback (first clip).
- When forcing Flash fallback via `techOrder: ["flash"]`, the Play button shows but does not react (second clip).
- Only when adding a `<source>` element, the fallback works as expected (third clip).

**Comment by gkatsev** [comment]
We're no longer supporting Flash since it is now EOLed. We have a PR to getting the src attribute working that needs to get fixed up, though.
