### ISSUE TITLE
Loading indicator moves beyond

### ISSUE THREAD

**Issue by doublex** [videojs/video.js#1288]
Clicking "pause" after starting the video, the loading indicator moves and moves and moves.
Screenshot:
http://doppelbauer.name/LoadingIndicator.png
Firefox 30, Ubuntu 14.04
Works fine in Chrome.

**Comment by mmcc** [comment]
Closing this because I think it's a non-issue in 5.0. Ping this thread if that's not the case and we'll reopen.
