### ISSUE TITLE
Android Chrome fullscreen video controls draw wrong if orientation changed after entering fullscreen

### ISSUE THREAD

**Issue by rbolyard** [videojs/video.js#1307]
Repro: Navigate to videojs.com. Begin playing the video. Enter fullscreen in portrait orientation. Rotate the phone to landscape.

Behavior: The controls end up in the middle of the screen and only as wide as they were in portrait mode. The interaction with the controls (seeking, pause, etc) still take place at the bottom of the screen (where the control actually should be).

Expected: The controls should update graphically to show at the bottom of the screen.

Note: There are similar issues if you enter fullscreen in landscape and then rotate the phone into portrait.

Tested in Chrome 35.0.1916.141 on 2 devices:
Moto X (Android 4.4.2)
Galaxy S4 (Android 4.4.2)

**Comment by meleyal** [comment]
In Chrome / Android / LG Nexus 5 the fullscreen option seems broken, in portrait you just see a black screen, in landscape you see a bit of the video but it doesn't fit to the screen (using the video.js homepage, for example).

**Comment by gkatsev** [comment]
This is a really old issue and I believe we no longer experience this, or we no longer support the platforms that really had it the worst.
