### ISSUE TITLE
Have videojs choose another source/tech combination when one fails

### ISSUE THREAD

**Issue by ange007** [videojs/video.js#1316]
Any news concerning https://github.com/videojs/video.js/issues/995?
As a whole some things changed, but not absolutely: http://jsfiddle.net/uLG8H/9/

Still strangeness in this example:
*if to click on the first link, and then on the second: the first video won't work, but the second will play.
*if to press at once the second video - it won't play.

_P.S. And why not to make an "techOrder" rechoice in case of failure previous?_

**Comment by gkatsev** [comment]
I believe the output we want from this issue is the ability for videojs to choose another source/tech combination if the current one failed.
I'm going to update the title with this.

**Comment by gkatsev** [comment]
I think tech selection is in a much better place in the newest versions of Video.js. Having Video.js choose another source when one failed is definitely a thing we want to work on. I'm working on writing up a roadmap for Video.js and retry on error is definitely going to be on there.
In the mean time, I'm closing this issue.
