### ISSUE TITLE
`waiting` event not firing

### ISSUE THREAD

**Issue by shshaw** [videojs/video.js#1318]
Based on our discussion in #1225, I thought it'd be best to start a new issue since it's not directly related.

I'm currently testing locally in Chrome 35 and using [speedlimit](http://mschrag.github.io/) to simulate a slow connection.

I tried myVideo.on("waiting", ...) but the event never fired, but other events are firing correctly. On the [JSBin example](http://jsbin.com/zubig/1/edit), I do see the `waiting` being fired. 

I moved the same code from localhost to a server, and I still am not getting the `waiting` event to fire.

Let me see if I can simplify/reduce the code and replicate it to be able to provide an example.

Edit: I can get it to fire occasionally, but it is not firing whenever the video is actually buffering.

**Comment by norlin** [comment]
Is there any progress with that bug?

**Comment by gkatsev** [comment]
Anyone had a chance to look at this with videojs 5?
I think that ultimately, it's up the browser (we have some control of it in the swf, I guess) on how and when to fire these events. `waiting` is fired when it's played back through all the data available and no longer has any more data to play. `progress` events fire when it's downloading more data. Browsers may or may not fire those reliably.
Though, I would wonder whether the browsers are more reliable now than they were back then.
To reliably know that the video has stopped playing back, you probably would want to listen to `timeupdate` and `propgress` events and set a timer each time (we do that in the [videojs-errors](https://github.com/brightcove/videojs-errors/blob/master/src/plugin.js#L116-L124) to throw an error if nothing has been playing in 45 seconds).

I dont think there's much we can do in videojs. Closing this issue but if you have questions or comments, please add them.
