### ISSUE TITLE
Only works once when dynamically loading the player

### ISSUE THREAD

**Issue by walterdavis** [videojs/video.js#1319]
If you have multiple videos on a page loading into a single player, or if you try to load the same video more than once, it will only work on the first try. Example here:

http://scripty.walterdavisstudio.com/flash/

Important for testing: you need to use a browser that does not play back MP4 video, so the Flash fallback is engaged for playback. Firefox latest on Mac OS X works for this. 

Click the yellow area to load the video. It loads and auto-plays just fine. Click the yellow area again to reload the video. It fails to engage the Flash fallback, and shows the Firefox "no supported formats" error. Reload the page, and you get another crack at it. 

On the second time that the callback is called, I see the following error in Firebug:

```
VIDEOJS: Video.js: currentTime unavailable on Flash playback technology element.
TypeError: this.b.vjs_getProperty is not a function
....version()[0]};u.i.ub=function(a){if(!a.type)return"";a=a.type.replace(/;.*/,"")…
```

I am using the CDN version of the script, so presumably the latest version.

**Comment by KiruthikaKumar** [comment]
I am able to play the video for the first time using the following code using videoJS v4.10.2. I referred this code from a github link https://github.com/videojs/video.js/issues/1021

videojs("video1").ready(function () {
            var videoPlayer = videojs('video1');
            var played = false;
            videoPlayer.one('play', function () {
                if (!played) {
                    played = true;
                }
            });
  });

And if I try playing the same video after navigating to different view I am getting '  });' error in console and the video is not playing. I have also tried dispose method but it didt work. Can anyone please suggest some alternative solution to fix this issue?
