### ISSUE TITLE
NuGet Support

### ISSUE THREAD

**Issue by DaveMiscampbell** [videojs/video.js#1323]
As someone who works in Visual Studio a lot, a NuGet package for VideoJS would be invaluable.

I have created one which can be previewed here https://www.nuget.org/packages/VideoJs/4.6.3.

I would be really happy to add anyone else who is interested as an owner of the package or add the nupkg to the repository so it can be updated as part of the build process?

Let me know what you guys think!

**Comment by robertpmansion** [comment]
Hi There, 

Please update the package to the latest version. thanks :)
