### ISSUE TITLE
IE11: Fullscreen inside iframe, video will seek to end when clicking on trackbar (seeking forward)

### ISSUE THREAD

**Issue by leray** [videojs/video.js#1333]
IE11: Fullscreen inside iframe, video will seek to end when clicking on trackbar (seeking forward)

How to reproduce:
1. Put a video inside an iframe ( http://storage.eu.ee/testground/videojs/ )
2. Play video and enter fullscreen
3. trying to seek forward

FF, Chrome will change the current position
IE11 will seek to the end and stop the video

![s1](https://cloud.githubusercontent.com/assets/3197275/3507186/74d65732-067b-11e4-9f3e-24be8d59df4f.png)

**Comment by mzgol** [comment]
IE11 is not developed anymore and the bug is fixed in Edge. It seems checking `"msFullscreenElement" in document` should be enough to catch the "rogue" browser.

**Comment by darcnite3000** [comment]
I'd like to add that i think there is a related issue in here that the volume control doesn't work in this situation either. (fullscreen from iframe)

**Comment by forbesjo** [comment]
I can’t reproduce the issue on 11.0.9600.18762, perhaps this has been surprisingly fixed? Anyone else still seeing this?

**Comment by banyan** [comment]
I see this problem on 11.0.9600.17280. I can't see on 11.0.9600.18860 anymore.

**Comment by gkatsev** [comment]
Given that this is a browser bug and it's fixed in a newer build of IE11, I'm going to close this issue.
