### ISSUE TITLE
Media loading issues from Cloudfront

### ISSUE THREAD

**Issue by zenmatt** [videojs/video.js#1338]
I've been using videojs successfully for audio and video files loading via S3. In an effort to speed up loading, I enabled Cloudfrount for the buckets. Since that time, I've had several issues with audio/video partially loading and ultimately stalling. Additionally, skipping to a different time in the video works very well once or twice before ultimately failing and requiring a reload. I recognize this could be a Cloudfront issue, though I haven't identified what that might be (download/network tests are fine). 

I have preload set to auto and noticed the media downloads an initial burst very quickly on load, but stalls shortly thereafter and am wondering if there is a setting I should consider changing. Any advice is welcomed, thank you.

**Comment by cedricve** [comment]
@zenmatt @mmcc  I've been trying to do the same (but directly from AWS S3). Can you help me with this?
https://github.com/videojs/video.js/issues/3903
