### ISSUE TITLE
Allow for webkit-playsinline

### ISSUE THREAD

**Issue by dcharbonnier** [videojs/video.js#1367]
There is currently no way to use videojs to play a video inline on iOS devices .

**webkit-playsinline**
Indicates that a video element should play inline instead of full-screen. Enabled only in a UIWebView with the allowsInlineMediaPlayback property set to YES.
Related Tags : video
Availability : Available in iOS 4.0 and later.

https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-SW30

Related to #896, #314 copy attributes but don't provide an option.

**Comment by rapsody** [comment]
Has this been added to the latest release  v4.12.13?  I have added playsinline': true, to my videoJs setup and its not detecting it.

**Comment by DieterPagel** [comment]
Does anyone perhaps have a working code example for me on how to play video inline on iOS? We have read extensively in the forums and tried all suggestions but we just can't seem to get it to work
