### ISSUE TITLE
Android vs. .htaccess

### ISSUE THREAD

**Issue by lost-carrier** [videojs/video.js#1383]
I have a very basic page playing video fine in different browsers (Chrome, Firefox, Safari, ...) and also on various devices (iPhone, iPad, Android 4.x). As a very simple protection mechanism I wanted to use a .htaccess. The index page and media file are protected within the same relam. If you use "save password" this works fine on all browsers and devices ... except(!) Android, which then claims it cannot load the video or did not understand the codec (the later one is obviously not the case since it works without that password). I'm not entirely sure who to blame, but hoping for some hints here...

Code is...

```
<div class='video'>
    <video id="video" class="video-js vjs-default-skin"
        controls preload="auto" width="1280" height="720"
        data-setup='{"customControlsOnMobile": true}'
        poster="media/Chile_2013_v4.jpg">
        <source src="media/Chile_2013_v4.m4v" type='video/mp4' />
        <source src="media/Chile_2013_v4.ogv" type='video/ogg' />
        <source src="media/Chile_2013_v4.webm" type='video/webm' />
    </video>
</div>
```

Tried with multiple V4 Androids, but primarily using Sony Z1 w/ V4.4.2.

Thanks in advance...

**Comment by haykz7777** [comment]
This is Android related issue. Try Chrome Beta browser on Android KitKat or Lollipop
