### ISSUE TITLE
Couple suggestions for better fallback behavior (HLS vs MP4)

### ISSUE THREAD

**Issue by rafaelrruiz** [videojs/video.js#1384]
I have HLS and MP4 versions of my streams.  I'd like to show HLS when its supported and fallback to MP4 when its not.  (See below for a fuller description of what I think is a pretty common scenario.)  I think there are two changes needed in video.js that would make this possible.

1. The first is to distinguish between HLS content and regular MP4 content by adding "application/x-mpegURL" to the supported MIME types for the Flash tech.  MIME-type is the fundamental way we check whether a tech supports a source so it seems logical that we should add this MIME type to the vjs.Flash.formats set.

2. The second is changing the way selectSource works to prioritize source over tech.  In the spirit of following the <video> approach, we should try to play the first source with any tech we have handy first, before trying the second source.  That seems to be the intent of the design for <video>.  This is a simple code change but of course I recognize it would be a change to existing behavior so maybe we add a new Option with two values - one for the existing behavior and one for the "try all techs per source" approach.  (I'm horrible with names but maybe the option could be called sourceSelection with values of 'prioritizeTech' and 'prioritizeSource' and prioritizeTech would be the default (as its the behavior of video.js today) ?)

What do you all think?

Scenario:  I have an HLS version of a video with multiple bitrates (cause that often provides a better user experience on a variety of devices and networks) but I also have a vanilla version in MP4 format for devices/platforms that simply can't display HLS. 

For example, on Mac Safari or iOS browsers, I'd like to display HLS without the use of Flash (using the built-in <video> tag).  On PC browsers I'd like HLS to be displayed using Flash, if its available.  And finally on PC browsers that don't have Flash enabled or mobile devices that don't have reliable HLS support, I'd like to fallback to the MP4 version of the video.

To accomplish this (with the changes above) I could use a techOrder of [ 'html5', 'flash' ] cause the native implementation is always preferable if it will play my content.  And a sources array like this:

                    sources = [                       
                        { src: content.url, type: "application/x-mpegurl" },
                        { src: content.httpUrl, type: "video/mp4" },                        
                    ];

With the changes I describe above, each tech would be checked to see if the first source will play.  If none suffice, then the techs are checked for the next source.  On systems with native support for HLS or no-native support but Flash enabled, HLS will be chosen.  On systems with neither HLS or Flash support, the MP4 is chosen.  AND, on old browsers that might not have MP4 support built in, I still have the final choice option of Flash playing the MP4.

**Comment by heff** [comment]
I'm going to close this issue because:
- We've exported selectSource so you can override the tech/source priority
- We've released the [source-handlers](https://github.com/videojs/video.js/pull/1560) interface and started migrating the adaptive formats to it

The root of this issue was that we didn't have support for HLS in HTML5, and we're getting close to having a solution.

HLS was always awkward as a "tech" because it didn't fit the concept of a tech, like Flash, HTML5, and YouTube. With the source handler API, there will be an HLS-Flash and HLS-Html5 source handler, and they will use the existing Flash and HTML5 techs instead of extending them to create a new tech.

Feel free to continue the discussion or ask questions here.

**Comment by gkatsev** [comment]
https://github.com/videojs/video.js/pull/2847 implements an option `sourceOrder` which would loop through each source and then for each source each tech.
The default stays the same.
It'll be released as videojs 5.3 which will be a `@next` on npm.
