### ISSUE TITLE
<track> with kind="metadata" throws error

### ISSUE THREAD

**Issue by Dador** [videojs/video.js#1388]
Hi.

HTML:
```html
<video id="somevideo" class="video-js" controls preload="auto" width="300" height="300" poster="/poster.jpg" data-setup="{}">
<source src="/video.mp4" type="video/mp4">
<track src="/metadata.txt" kind="metadata" />
</video>
```

Error:
> Uncaught TypeError: undefined is not a function
> video.dev.js:6915

File: [src/js/tracks.js on line 52](https://github.com/videojs/video.js/blob/bb50466733ab7de22e2e0463f622db91222d54b1/src/js/tracks.js#L53)

As I tested just adding check that `new window['videojs'][Kind + 'Track']` is exists wouldn't help. Track just disappear.

**Comment by mmcc** [comment]
I think #1044 took care of this, I no longer see the error thrown.
