### ISSUE TITLE
Unloading a tech fires events that try to get its currentTime after el_ has been set to null

### ISSUE THREAD

**Issue by rafaelrruiz** [videojs/video.js#1389]
In unloadTech (see below) we call dispose on the tech then try to clean some things up.  As part of manualTimeUpdatesOff or manualProgressOff, we try to trigger an event that uses currentTime. This causes "Uncaught TypeError: Cannot read property 'vjs_getProperty' of null" 
```js
vjs.Player.prototype.unloadTech = function(){
  this.isReady_ = false;
  this.tech.dispose();

  // Turn off any manual progress or timeupdate tracking
  if (this.manualProgress) { this.manualProgressOff(); }

  if (this.manualTimeUpdates) { this.manualTimeUpdatesOff(); }
  
  this.tech = false;
};
```
Check out dispose below.  Notice it sets this.el_ to null at the end but doesn't set isReady_ to false.  This means that vjs.Player.prototype.techGet will blindly try to get the 'currentTime' property and throw.

The fix is easy - set this.isReady_ to false right before setting this.el_ to false.
```js
/**
 * Dispose of the component and all child components
 */
vjs.Component.prototype.dispose = function(){
  this.trigger({ type: 'dispose', 'bubbles': false });

  // Dispose all children.
  if (this.children_) {
    for (var i = this.children_.length - 1; i >= 0; i--) {
      if (this.children_[i].dispose) {
        this.children_[i].dispose();
      }
    }
  }

  // Delete child references
  this.children_ = null;
  this.childIndex_ = null;
  this.childNameIndex_ = null;

  // Remove all event listeners.
  this.off();

  // Remove element from DOM
  if (this.el_.parentNode) {
    this.el_.parentNode.removeChild(this.el_);
  }

  vjs.removeData(this.el_);

  this.el_ = null;
};
```

**Comment by gkatsev** [comment]
This is fixed in 5.x and probably some time earlier: https://github.com/videojs/video.js/blob/0e1c424e48019b002ba542aaceb211b959f511a0/src/js/player.js#L597-L607
