### ISSUE TITLE
play() called "too early" with autoplay enabled

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#1413]
When `autoplay` is enabled, `play()` is called as soon as [a new source is set](https://github.com/videojs/video.js/blob/6b612d8cdc8f4d1b31432d304297e19aad30ad09/src/js/player.js#L1256). If the source is a Media Source, it will not be ready to begin playback and the call will be ignored. I will probably work around this by calling `play()` again for https://github.com/videojs/videojs-contrib-hls/issues/112 but it's worth considering whether the current implementation is correct. It seems to me this might be better handled at the tech level instead of in the player.

**Comment by dmlap** [comment]
I'm running into more autoplay shenanigans so I'm going to collect some observations here. The behavior seems incorrect across the board but the Flash tech is the most egregious offender because of its asynchronous startup and muddled initial playback behavior. If an mp4 is loaded in an initially empty player with autoplay and flash is selected for playback, `play` is emitted four times:

1. [HTTPVideoProvider.as](https://github.com/videojs/video-js-swf/blob/003e4a0484e82ca089223742ed770d007efeeee7/src/com/videojs/providers/HTTPVideoProvider.as#L283):
  `play` emitted as a result of setSrc from the Flash tech.
1. [player.js](https://github.com/videojs/video.js/blob/89c7b868f6044add119fa0e21aff9842f4faa0bb/src/js/player.js#L1191):
  play() called on the Flash tech as a result of options.autoplay which triggers the SWF to emit `play`
1. [flash.js](https://github.com/videojs/video.js/blob/89c7b868f6044add119fa0e21aff9842f4faa0bb/src/js/media/flash.js#L135):
  Trigger play() on a setTimeout when autoplay is true
1. [HTTPVideoProvider.as](https://github.com/videojs/video-js-swf/blob/003e4a0484e82ca089223742ed770d007efeeee7/src/com/videojs/providers/HTTPVideoProvider.as#L512):
  Triggered by the NetStream when playback begins.

If you had a good reason to pause the video temporarily (e.g. a preroll advertisement), you're going to have to play whack-a-mole. It's even messier than that would imply since one of the play() calls is asynchronous.

**Comment by gkatsev** [comment]
We're actually seeing it in the HTML tech sometimes as well.

**Comment by gkatsev** [comment]
Actually, the HTML tech issue might be different, though, still related to autoplay. Investigating.

**Comment by gkatsev** [comment]
> you're going to have to play whack-a-mole.

pun intended? :P

**Comment by heff** [comment]
> pun intended?

lol, wow

So yeah, that's a lot. Sounds like we should first take the autoplay responsibility away from the player. That would at least remove one instance.

**Comment by gkatsev** [comment]
I think all play and autoplay things are being handled completely differently at this point. Closing.
