### ISSUE TITLE
The video could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by wlbyml** [videojs/video.js#1421]
My English is so bad . I will describe the problem as possible ...
use HTML5 tag video and source, and  the src just like http://********.com/hls-vod/test.mp4.m3u8?wsSecret=e9761e8ff7943ff187ba1fe91ef9ed52&wsTime=20140806191515   and  the attribute type is 'video/mp4'  
if i don't init the videojs, it works fluently 
as soon as   init, just like  
var  myPlayer = vjs('video_1'); (the id is not wrong)
it doesn't work  
but it works  fluently in  IE compatible mode 
neither in FF ,Chrome 
I have no idea about it  .. 

oh  my  email  : wlbyml@163.com  
thanks

**Comment by q747985549** [comment]
# 

> _**123123**_
