### ISSUE TITLE
Log a helpful error when a plugin doesn't exist

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1460]
When a plugin doesn't exist but the configuration is still passed in for it in the options object, it throws an error that's not very obvious. This could come up if someone removes the plugin file, or if the plugin file loads too late.

The log would go here:
https://github.com/videojs/video.js/blob/1f33546f905a55f846b6db0dc4a1e0a9706e8ddf/src/js/player.js#L94

**Comment by gkatsev** [comment]
Fixed in 5.x: https://github.com/videojs/video.js/blob/0e1c424e48019b002ba542aaceb211b959f511a0/src/js/player.js#L161-L167
