### ISSUE TITLE
FLV video not playing locally

### ISSUE THREAD

**Issue by qwert789** [videojs/video.js#1461]
Flash video not playing locally:
Setup in index.html:
```
    <video id="example_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="264"
           poster="oceans-clip.png"
           data-setup="{}">
        <source src="http://www.mediacollege.com/video-gallery/testclips/20051210-w50s_56K.flv" type="video/flv" />
        <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
    </video>
```
Clicking on play button not triggiring any action and not playing the video , however removing  ['eventProxyFunction': 'videojs.Flash.onEvent'] from  "video.dev.js" and setting autoplay as true plays the video while control options is unavailable, so it's seems it's some kind of bug in video js here, playing video locally and the issue is caused by flash permissions.

**Comment by heff** [comment]
@juliemar, try using a full URL to the video file (http://...). I think that could fix your issue.

I'm going to close this because it doesn't appear to require changes to the codebase, but feel free to continue the discussion.
