### ISSUE TITLE
TypeError: this.error(...) is null in VJS 4.7.3

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#1471]
In Firefox 28.0 console:
Timestamp: 02.09.2014 23:12:35
Error: TypeError: this.error(...) is null
Source File: video.dev.js
Line: 6290

In IE 11:
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video. [object Object]
   "VIDEOJS:"
   "ERROR:"
   "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)"
   "No compatible source was found for this video."
   {
      [functions]: ,
      **proto**: { },
      code: 4,
      MEDIA_ERR_ABORTED: 1,
      MEDIA_ERR_CUSTOM: 0,
      MEDIA_ERR_DECODE: 3,
      MEDIA_ERR_ENCRYPTED: 5,
      MEDIA_ERR_NETWORK: 2,
      MEDIA_ERR_SRC_NOT_SUPPORTED: 4,
      message: "No compatible source was found for this video.",
      status: null
   }

Example http://jsfiddle.net/abekx6jq/
Minified version I used in this example.

**Comment by redbar0n** [comment]
This might detail the problem and the solution:
http://magnemg.tumblr.com/post/113251336220/how-to-solve-a-capybara-webkit-and-video-js

If it is the same problem, then it's an issue with the Webkit implementation that Qt 4 uses on OSX. The solution is to upgrade to Qt 5 which uses a newer version that doesn't throw TypeError's when trying to play MP4 videos. See the blog post for more details.
