### ISSUE TITLE
IE11 fullscreen triggered from keyboard

### ISSUE THREAD

**Issue by mynameisstephen** [videojs/video.js#1478]
Triggering the full screen button from the keyboard (tab to then enter/space) does not enter full screen mode in IE11.  No error is thrown.  Triggering full screen mode via the mouse works.

**Comment by gkatsev** [comment]
I investigated this some more and it seems like it's a bug in IE11. Even youtube's player doesn't work.

**Comment by gkatsev** [comment]
I'm not really sure there's anything we can do for this. Should it be closed? @mmcc @heff?

**Comment by mmcc** [comment]
I normally err on the side of closing things we have no control over. Although it might still be an issue, it's not like we can do anything about it, so there's no point in having an open issue.

How about a label for "can't fix" or something? That would allow us to periodically check the intersection of "browser bug" and "can't fix" as browsers update.

**Comment by heff** [comment]
That sounds reasonable. If we can find a link to a bug report about it
somewhere that'd be good. Does IE have a bug tracker?

**Comment by gkatsev** [comment]
They do: https://connect.microsoft.com/IE/Feedback

This reminds me, videojs should probably be checked out on MS Edge.

**Comment by gkatsev** [comment]
In my other issue on their tracker regarding tracks, they said they don't work on IE11, so, not sure whether it's even useful to open this issue :/
Closing since we can't do anything.

**Comment by prbaron** [comment]
A little late to the party but I faced the same issue in our project. I have been able to workaround it by creating a button from JS, adding the call to the fullscreen API and triggering a click.

```
 const button = document.createElement('button');
button.addEventListener('click', () => {
 document.querySelector('.media').msRequestFullscreen();
});
button.click();
```
