### ISSUE TITLE
vjs.hasData Error Spam

### ISSUE THREAD

**Issue by Manbearpixel** [videojs/video.js#1484]
Developing a video playing website on AngularJS and using videoJS as the video player. The video player is contained within a controller, which gets destroyed and comes back upon a new video being loaded. In angular, I can run functions prior to a controller being destroyed, this is where I call videoObject.dispose() 

**Expectation:**
I expected `videoObject.dispose()` to handle all the necessary removal of information related to the video player.

**Reality:**
It seems that if a video is exited (controller is destroyed) prior to the video fully loading, an error is thrown repeatedly from `vjs.hasData` (see screenshot below). This error seems to be thrown every second (assuming an event is still active somewhere that wasn't cleared) I tried tracking down the `.dispose()` function and commenting out `this.trigger({ type: 'dispose', 'bubbles': false });` but that seems to have no effect. If I try checking that el is not null or wrapping it in a try/catch it still goes through but instead the error comes from `vjs.trigger` (see screenshot below) 

At this point I am unsure how to debug this and am curious if anyone else has encountered this problem. I will try to create a plunkr that might replicate this issue since the site is currently not live.

**vjs.hasData Screenshot**
![screen shot 2014-09-04 at 12 27 07 pm](https://cloud.githubusercontent.com/assets/6686750/4156473/d2c5b71c-3474-11e4-95b8-b4801d2b3501.jpg)

**vjs.trigger Screenshot**
![screen shot 2014-09-04 at 3 47 04 pm](https://cloud.githubusercontent.com/assets/6686750/4156476/d90a05c4-3474-11e4-9d46-7709a8935c9a.jpg)

**videoPlayer.dispose() call**
![screen shot 2014-09-04 at 3 51 51 pm](https://cloud.githubusercontent.com/assets/6686750/4156535/53a686ae-3475-11e4-9424-7fe30ce7fd41.jpg)

**Comment by benjipott** [comment]
new on this issue

**Comment by mmcc** [comment]
This shouldn't be an issue anymore, it should have been closed along with #1656 and #1642. @benjipott can you put together a reduced test case?

**Comment by gkatsev** [comment]
Generally if you are seeing this, it means there's some other *unrelated* bug further up the chain.

**Comment by saxena-gaurav** [comment]
this should have been fixed by #2125
