### ISSUE TITLE
All about the styles: Stylesheet organization / Sass migration / third party themes.

### ISSUE THREAD

**Issue by mmcc** [videojs/video.js#1492]
We've been talking about doing this for quite some time, but I think it's finally time to actually start a conversation. We've always stuck to a single Less file for three main reasons:

- Simplicity (reduce the barrier to entry for folks new to preprocessors)
- Designer (one file to load into the designer and edit)
- Because, because.

As the time is getting nigh for version 5, one of the big things we'd like to tackle is standardizing practices for creating third party themes. Before we can start talking about third party themes, I think we need to lead by example with our default theme.

- Sass vs Less? To be quite honest, a big reason for picking Less in the first place was browser support for the preprocessor (so we could have the designer, for instance). That's definitely not an issue anymore and it seems that Sass is winning the war for designer's hearts (and I personally prefer it, which is obviously the most important).
- Separate repo or same? Should the default theme have its own home or still live within the core repo?
- Style guide? I've been ~~stealing~~ using a lot of @fat's [high level Less practices](https://medium.com/@fat/mediums-css-is-actually-pretty-fucking-good-b8e2a6c78b06). Is that ok with us? Do we want to use more? Less?
- Directory structure - How do we want to organize themes? What should the delivery mechanism be?

I have my own opinions on a lot of these things, but I'm going to keep quiet for now (other than Sass > Less :trollface:). Over the weekend I did a fast and dirty conversion to Sass while also breaking the files up a bit into a way that I thought made sense. It's in my personal repos right now and will stay there until we decide otherwise to avoid confusion, but opinions welcome: [mmcc/videojs-default-skin](/mmcc/videojs-default-skin). I went ahead and made a [codepen](http://codepen.io/mmcc/pen/ExzhH?editors=110) as well that shows how this could all potentially work together.

**Comment by gkatsev** [comment]
I think this has been decided on. Can it be closed? @mmcc @heff.

**Comment by mmcc** [comment]
Yep, with base theme merged this is done. 



—
