### ISSUE TITLE
videojs disables menu links on iPad and iPhone

### ISSUE THREAD

**Issue by MarioBaron** [videojs/video.js#1493]
When video is located under the menu item whether its through fixed navbar like on Bootstrap videojs.com theme (screenshot attached) or under a submenu item displayed over the video. The menu links become disabled and instead trigger the control bar element to show/hide on menu item touch/click.
This is pretty serious considering the iOS market share and Bootstrap theme usage (any fixed navbar for that matter).
I've attached the screenshot from videojs.com where this "misbehaviour" can be observed. Hope it helps in debugging.
![ios simulator screen shot 9 sep 2014 11 46 49 pm](https://cloud.githubusercontent.com/assets/5214118/4202711/4202b716-382a-11e4-868d-389e1fba71d1.png)

**Comment by AmirKaftari** [comment]
hi guys.
overridenative is not working in ios browser for me.
please help me?
