### ISSUE TITLE
IE11: vjs-playing classname doesn't change to vjs-paused when video ends

### ISSUE THREAD

**Issue by anttimo** [videojs/video.js#1498]
Test env. WIN7 and IE11 (11.0.9600.17239, update version 11.0.11) and HTML5 player

In IE11 browser videojs player stays in vjs-playing state even when video ends. This can be reproduced on home page video at http://www.videojs.com/. 'ended' event seems to work as in our playing analytics reporting sends video ended event correctly but the UI stays as if it would be still playing the video.

**Comment by mister-ben** [comment]
Um, this was fixed three years ago
