### ISSUE TITLE
Consider using <button> element

### ISSUE THREAD

**Issue by baloneysandwiches** [videojs/video.js#1499]
One of the bragging points of <a href="https://www.paypal-engineering.com/2014/09/05/introducing-an-accessible-html5-video-player/">Paypal’s new html5 player</a> is semantic markup. I think they have a point there. Best practice is to mark up a button as a `<button>`, and we’re currently not doing that. Given that we have proper ARIA roles, this is less of a concern. But `<button>`s get authors lots of accessibility goodness right out of the box, and I think they help to cover some edge cases, especially with screen readers. This would require a bit of an overhaul. Right now the menus are inside the button `<div>`s, and in the default skin they get hidden and shown with descendant selectors:

    .vjs-default-skin .vjs-menu-button:hover .vjs-menu {display: block;}

The idea would be to switch to markup like:

    <div class="subtitles-wrapper>
        <button class=“vis—menu-button”>Subtitles</button>
        <div class=“vjs-menu”></div>
    </div>

and switch to adjacent selectors in the CSS:

    .vjs-default-skin .vjs-menu-button:hover + .vjs-menu {display: block;}

Thoughts?

**Comment by mmcc** [comment]
Done! Kind of, but aside from Menu buttons, vanilla buttons are now buttons.
