### ISSUE TITLE
Better timeout handling

### ISSUE THREAD

**Issue by mmcc** [videojs/video.js#1541]
I've left this comment on a few issues, so it's probably time to create a new catch-all for this one.

@heff and I talked this over, and we think it makes sense to have a `setTimeout` utility method that is identical to `window.setTimeout`, but adds the timeout to an array on the player instance so we can dispose all of them at once when the player is disposed. 

This would clean up all the instances of having to create a dispose listener each time a timeout is created, and help us avoid accidentally missing one (which seems to happen pretty often) and allows plugins to utilize the same functionality.

Other (potential) references: #1521, #1484, #1505, #1431

**Comment by ppaul** [comment]
works like a charm! thank you; saved me from an ugly bug

**Comment by toru-sean** [comment]
Hi, I'm getting this error  so am assuming it's unresolved. Is it likely to ever get resolved? It's been over 2 years since it was opened so I'm guessing not.

**Comment by mmcc** [comment]
@toru-sean The original context of this issue was resolved with #1642. If you're seeing this issue again, it could be a regression or an entirely different problem altogether, but we need _some_ context here. Please use the [issue template](https://github.com/videojs/video.js/blob/master/CONTRIBUTING.md#filing-issues) so folks can take a look. Thanks!

**Comment by willpiam** [comment]
Hey I'm here 5 years after the last activity, with at the very least a very similar issue. I'll try deferring dispose but a) that's disgusting and  b) my error is coming from the line where I call videojs().

**Comment by willpiam** [comment]
yeah it didn't help

**Comment by mmcc** [comment]
It's really difficult to determine whether this is the same, new, or implementation issue without seeing a [reduced test case](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) that shows the problem. Think you could put something together there and we can take a look?
