### ISSUE TITLE
Subtitles font size

### ISSUE THREAD

**Issue by yamato938** [videojs/video.js#1546]
Hi, i am using wordpress plugin for video.js player, can you tell me how can i increase font size for subtitles only? font is too small, hard to read...

**Comment by pepijn809** [comment]
i'm probably overlooking something, but the subtitle font does not seem to change when i edit "font-size: 3em;" to some higher value in the video-js.css file.

I can host it myself and type it out each page in html, but using the plugin would save some time. Any suggestions?
