### ISSUE TITLE
SMIL support

### ISSUE THREAD

**Issue by cdekok** [videojs/video.js#1548]
Are smil playlist supported by video.js for example: http://flash.flowplayer.org/demos/standalone/plugins/streaming/bitrates.smil.xml

**Comment by ravituvar** [comment]
Any updates on this?
We want to implement SMIL in VideoJS..(http://flash.flowplayer.org/demos/standalone/plugins/streaming/bitrates.smil.xml).

Is there any plugin available so far?

**Comment by ravituvar** [comment]
Any updates on SMIL Support? Any one got the Plugin for such feature?

**Comment by BrandonOCasey** [comment]
I don't think that there is a plugin for this yet, at least not one mentioned on https://github.com/videojs/video.js/wiki
