### ISSUE TITLE
Choose and improve one set of mute + volume controls

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1553]
Currently we have two options for setting up the html of the mute and volume controls:
1. As completely separate controls
2. Combined as a MenuButton and the volume is hidden until the mute button is hovered over or tabbed to

The second option is relatively hidden however the new Brightcove player is actually using this as the base of all Brightcove players.

The two options complicate the CSS significantly and will create a divide between sets of skin files that rely on one or the other. For v5.0 we should simplify this down to one option, and hopefully make it possible to achieve both layouts. That will probably mean we need to start from scratch. At the same time we should break apart the volume menu button from extending the MenuButton class. They've become too different and that's part of what's added the CSS complication.

Related Issues: #1519

**Comment by heff** [comment]
We've essentially landed on the volume menu here, but the one research task left here I see is attempting to create the inline volume style using the volume menu button. Or at least the YouTube style where it expands within the control bar.

**Comment by dmlap** [comment]
Note: We're keeping both versions of the volume, but standardizing on using the volume menu as the default for all major players (video.js default and Brightcove player).

**Comment by dmlap** [comment]
Documented in the [migration guide](https://github.com/videojs/video.js/wiki/5.0-Change-Details#volume-menu-is-the-new-default-see-1553).
