### ISSUE TITLE
Switching src from flv to mp4 doesn't dispose properly?

### ISSUE THREAD

**Issue by klevenick** [videojs/video.js#1561]
In my particular instance, we have a playlist setup that dynamically loads videos. If a video requiring Flash is played (in this case, an flv), and then is followed by an mp4 (or some other HTML5 tech), there seems to be a mis-loading of the new player, or something similar. Behind the controls you can see another set of controls loaded. 

Switching the other way: from HTML5 to Flash works fine. The expected result should be, I would imagine, the reserve functions the same.

A test case is here (http://jsbin.com/mozawupuceke/1/edit), but the JS Bin doesn't load the FLV properly. Nonetheless, you can still click the Flash button, then click the HTML5 button to see the results. Included below is some test code if you want to see a version with a working FLV.

 ```html
<script src="video-js-4.9.0/video-js/video.dev.js"></script>
<link href="video-js-4.9.0/video-js/video-js.css" rel="stylesheet"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body>
<video id="test_player" class="video-js vjs-default-skin" controls preload="auto" width="70%" height="70%">

</video>
<button type="button" data-action="prev">html5</button>
<button type="button" data-action="next">flash</button>

<script>
      window.videos = [
        [{
            src: 'http://stream.flowplayer.org/bauhaus/624x260.mp4',
			type: 'video/mp4'
        }],
        [{
            src: 'http://techslides.com/demos/sample-videos/small.flv',
			type: 'video/flv'
		}]
      ];
      window.player = videojs('test_player', { 'autoplay': true });

      $('[data-action=prev]').on('click', function(e) {
        player.src(videos[0]);
      });
      $('[data-action=next]').on('click', function(e) {
        player.src(videos[1]);
      });
</script>

**Comment by tomorrowbetter** [comment]
Many of my friends recommend me to use iDealshare VideoGo to convert flv to mp4 at http://www.idealshare.net/video-converter/convert-flv-to-mp4-on-mac-windows.html

After have a try, it really works great.

It can easily convert FLV files to MP4 with quality preserved on Mac (Yosemite included) and Windows (Windows 8 included).

It also allows to convert FLV to other popular video and audio formats like FLV to MOV, FLV to AVI, FLV to WMV, FLV to MP3, FLV to WAV, FLV to M4A, etc.

It even can convert video to FLV, WebM, OGV etc
