### ISSUE TITLE
hiding/unhiding the (flash) player, or it's parent container, crashes the player

### ISSUE THREAD

**Issue by kelexel** [videojs/video.js#1570]
simple case, a vjs instance using the flash tech

apply any css style that tries to "hide" the player  (or it's parent), than, when you'll remove the style (or css class), the flash player will crash causing vjs to report various errors in the console

I tried several ways to hide the player,  like: display:none; visibility:hidden; height:1px; width:1px; position: absolute; left:-5000px, etc etc etc), but each combination crashes flash in a different way

what about a .show() and .hide() player methods that would unload the tech on .hide(), and reload the tech on .show() ?

cheers!

**Comment by kolinko-ant** [comment]
I face exactly the same problem. As I understand this bug is not fixed yet?

**Comment by mmcc** [comment]
Sadly, this is a Flash bug more than a Video.js bug (so there's not too much we can do), but yes, this is still an issue. Our suggestion is to [dispose the player](https://github.com/videojs/video.js/blob/master/docs/guides/removing-players.md) instead of showing / hiding.
