### ISSUE TITLE
Video size is smaller than Black video frame / Rtmp/flv playing

### ISSUE THREAD

**Issue by besimler** [videojs/video.js#1571]
Rtmp/flv video 

Black video frame size is 100%. Its working with size options. But video coming very smaller in the black frame. When i re-size browser window video size fixing.

if i use video/mp4 video, everything working normal.

Note: Code is clean. I am using only video.js and video.css files. i am testing with chrome, firefox and ie.

Thank you.

![cap1](https://cloud.githubusercontent.com/assets/1512608/4572701/856afb28-4f89-11e4-8d1e-29c7424f757d.png)
![cap2](https://cloud.githubusercontent.com/assets/1512608/4572704/88c5ffa2-4f89-11e4-8e53-ae51aef2021c.png)
![cap3](https://cloud.githubusercontent.com/assets/1512608/4572706/8b85c2ea-4f89-11e4-9d41-1f3b50b91a27.png)

**Comment by kaiyuanbaba** [comment]
直播流rtmp可以实现拖拽快进和快退吗

**Comment by kaiyuanbaba** [comment]
Can live streaming rtmp achieve fast forward and fast rewind?
