### ISSUE TITLE
Detection of dragging on timeline

### ISSUE THREAD

**Issue by ericjeedunn** [videojs/video.js#159]
Currently when the timeline cursor is dragged these things happen:
- On left click down  a "pause" event is fired, a light white overlay on the video and the spinner spin.
- On left click up       a "play"    event is fired, overlay is removed.
- timeupdate is fired according to the dragging position

I  need  more granularity and being able to detect when the the pause/play is fired by a dragging on the timeline or clicking on the pause button. Likewise I would like to be able to detect what fire the play event.

It would be also useful to have a function that return the positions (x,y) of the cursor relative to the upper left corner or the video. In this way it would be possible to implement a thumbnail on the cursor like YouTube is lately doing on some videos

**Comment by apesant** [comment]
Hi, is there a way today to know if the pause is a "real" pause , or a pause before seeking? I need to this to add an overlay when the video is paused by the user.

**Comment by gkatsev** [comment]
I'm not sure there's a good way to detect it directly other than with some heuristics. Like listen to the pause event, wait a few milliseconds and make sure that a `seeking` event hasn't fired.

**Comment by heff** [comment]
You could probably use the scrubbing property on the player.
`player.scrubbing() === true`

https://github.com/videojs/video.js/blob/48ec1fb3eea82559ceb3b5ae1cb958c51c234bb3/src/js/control-bar/progress-control/seek-bar.js#L103
https://github.com/videojs/video.js/blob/9f37a64146b802cf8f84b1b926b65d5085419f6e/src/js/player.js#L1345

**Comment by gkatsev** [comment]
That sounds like a better way of detecting it.

**Comment by apesant** [comment]
Thanks guys, using the player.scrubbing() method works like a charm!
