### ISSUE TITLE
Poster image not displayed with controls disabled

### ISSUE THREAD

**Issue by danxexe** [videojs/video.js#161]
The poster img tag is not added to DOM when the controls option is false.

Testet in Chrome 18, Firefox 11 and Safari 5 on OSX 10.7.

[edit] Looking at the source, the issue seems to be on `player.js` line 81. `initComponents` is only called if `options.controls` is set. Is that intended?

**Comment by tuanalumi** [comment]
In 6.4.0, I have to set poster in `video` tag's attribute to have the poster shown when there is no control. Setting it in javascript code doesn't work.

**Comment by gkatsev** [comment]
Please open a new issue if there's a problem with the poster. Please fill out the issue template in as much detail as you can when doing so. Thanks.
