### ISSUE TITLE
Play rates set to Default in IE9 & IE10.

### ISSUE THREAD

**Issue by AnshulAgrawal1** [videojs/video.js#1611]
I am facing one problem, when you chose speed other then 1x and click on pause and play then i will change to 1x automatically.  I can repro this @ http://jsbin.com/vikun/1/edit?output.

Please let me know if more info is needed.

**Comment by mmcc** [comment]
It looks like MDN is incorrect, it seems like it also happens on pause as well. The screenshot is from IE9, but I reproduced the same thing in IE 10. 

![ie9 screenshot](https://cloudup.com/ccHQSeDhjWh+)

Not really sure if there's anything we can / should do here. Working around this bug could get pretty ugly on the Video.js side of things.

**Comment by heff** [comment]
Sounds like the best we could do is test for this and disable playback rate, like we do with volume on iOS.
https://github.com/videojs/video.js/blob/64101051901423fc02736b743073d3f31f1469b5/src/js/tech/html5.js#L468

**Comment by mmcc** [comment]
I almost feel like we should just make a note of it and not change behavior. This is a bit of a weird edge case, and it's not like the (small percentage of) people on IE9 needing to select "2x" again is a huge issue. I would rather the current browser bug just stay than a) disable playbackrate entirely for them or b) try and hack around it.

**Comment by heff** [comment]
works for me

**Comment by gkatsev** [comment]
We decided to just live with this bug.
