### ISSUE TITLE
Support videoTracks and audioTracks properties

### ISSUE THREAD

**Issue by timgreenfield** [videojs/video.js#1618]
First, I love the way techs need to conform to the HTML5 video element spec to participate with video.js.

One suggestion I have however is to expose all properties found in the HTML spec through the main video.js object to avoid making developers call them through the tech object. For example, audioTracks is part of the video element spec, but to access it today you must call player.tech.audioTracks(). This is very minor but I thought I'd mention it since it could make it a little easier on developers by not requiring them to know which APIs are plumbed all the way to the top level and which are not.

---
Original Title: Plumb through all tech properties defined in HTML5 video element

**Comment by chimilord** [comment]
Hellos guys, exists some way to enable double audio for videos in dash.js and videojs?
Thanks!

**Comment by gkatsev** [comment]
We've started work for this. See #3137 and #3130.
I'm going to close this and ask people to follow along with #3137 for this if they want updates.
