### ISSUE TITLE
Issues with Flash fallback

### ISSUE THREAD

**Issue by bschaeffer** [videojs/video.js#1619]
### Original issue #1:

Title: Poster doesn't show with flash only tech
Text: It never shows with the default skin and flash tech.
### Original issue #2:

Title: Flash tech only just loops.
Text: The videos just loop.
### Original issue #3:

Title: Flash fallback only works when it's the first and only tech
Text: Using a `<video><source url=.. type=..></video>` and initializing video js doesn't work with flash fallback.

`{techOrder: ['html5', 'flash']}` does not fall back to flash. `{techOrder: ['flash']}` does.

(Combined by @mmcc while we triage)

**Comment by JellyWang** [comment]
Hi, would you mind posting the code for you "new example"? My flash fallback won't work for IE8's emulation but your example works perfectly fine. I really want to figure out how to fix mine.

**Comment by mmcc** [comment]
@JellyWang You can just add `/edit` to the end of the url to see the code (or view source): http://jsbin.com/turoze/1/edit?html,output

**Comment by JellyWang** [comment]
Thank you so much for replying this quick. I really appreciate that!

**Comment by mmcc** [comment]
To be honest, we really try not to even touch bugs with emulation mode. It's simply too much of a rabbit hole full of dead ends and inconsistencies.

Regarding the border-radius question, that's a known issue. IE8 [doesn't support it](http://caniuse.com/#feat=border-radius), so any time you use border-radius it's going to show up as just a square in IE8.

**Comment by JellyWang** [comment]
@mmcc Thanks a lot for taking time hleping me with my problem. I really appreciate that. So I actually solved by problem by adding this line of code:
	<script src="http://api.html5media.info/1.1.6/html5media.min.js"></script>
I'm using Flowplayer as a Flash fallback and now everything is working perfectly.
Video.js is by far the best video player! I'm glad problem is solved and I can keep using Video.js.

**Comment by mmcc** [comment]
Great! Glad to hear it. :)

**Comment by crviet92** [comment]
Execuse me! if i want to play video youtube in ie8 by videojs so how ?(English is bad,i'm sorry)

**Comment by mmcc** [comment]
@crviet92 This is a question for the [videojs-youtube](https://github.com/eXon/videojs-youtube/) issue tracker.

**Comment by crviet92** [comment]
@mmcc 
I have seen it but it don't show in ie8
