### ISSUE TITLE
Poster image doesn't show when Flash fallback is used and controls are disabled.

### ISSUE THREAD

**Issue by mmcc** [videojs/video.js#1625]
``` html
<video id="my_video_1" class="video-js vjs-default-skin" poster="/images/some-awesome-picture.png" preload="auto" width="640" height="268" 
  data-setup='{ "techOrder": ["flash"] }'>
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
    <source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
  </video>
```

Because of [these styles](https://github.com/videojs/video.js/blob/423939857fbdfbd8e4db2ba50af8fc9782c8b129/src/css/video-js.less#L949-L953), the poster will never be shown for a Flash player with controls disabled.

**Comment by gkatsev** [comment]
Still an issue for v5 for the same reason: https://github.com/videojs/video.js/blob/6bbd6f1a65d49566900a6d52979d4c9e10ea7fc4/src/css/components/_poster.scss#L38-L47
