### ISSUE TITLE
Firefox OSX when Flash disabled.

### ISSUE THREAD

**Issue by peterlenagh** [videojs/video.js#1662]
Hi.

The videos I'm trying to use this library for are only available in mp4. It seems like firefox native html5 video player can't play mp4s on mac.

So, if you're on a mac and in firefox, I'm setting the techOrder to ['flash'] to force the flash player to be used.

If flash isn't available, however, this throws an exception and stops js execution.

"VIDEOJS:" "ERROR:" "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" "No compatible source was found for this video." Object { code: 4, message: "No compatible source was found for this video." }

There is also a subsequent error "VIDEOJS:" TypeError: a.g is undefined.

Ultimately I want to know how to make video.js deal gracefully with flash being the only techOrder option when flash is not available (error message, download flash message or something that wont break the page.)

Thanks for your help!

**Comment by redbar0n** [comment]
This might detail the problem and the solution:
http://magnemg.tumblr.com/post/113251336220/how-to-solve-a-capybara-webkit-and-video-js

**Comment by nafisakanwal** [comment]
@peterlenagh 
Can you please help me how do you resolved this issue , i am facing the same issue for my Live stream.
Thanks in advance
