### ISSUE TITLE
PICASA URL NOT LOADED

### ISSUE THREAD

**Issue by pratikbgit** [videojs/video.js#1666]
Hello sir

 I m unable to find the pathe OF PICASA URL in this plugin i.e. videojs plugin

I Have to work on the below plugin
http://www.videojs.com/

picasaweb url is 
https://picasaweb.google.com/111375617856475380835/Variety1611#6082291343141589394

Can u please give me the help to load the URL of above PICASA

Thank's
Pratik

**Comment by mingkemed** [comment]
you mean like here http://moviehas.com ??
