### ISSUE TITLE
unable to play flv files via video.js

### ISSUE THREAD

**Issue by propertunist** [videojs/video.js#1670]
for a while i was able to use video-js to play flash files (.flv) - however, on recent tests the same code now no longer plays the same files that previously played ok. the only changes that i am aware of are with the server OS and with the browsers being tested (chromium and firefox).

chromium 38 (gnu/linux) produces this (regardless of whether the 'type' is set to 'video/x-flv' or 'video/flv'):

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video.
```

firefox 33.1 produces this:

```
Specified "type" attribute of "video/flv" is not supported.
```

if i download the file from the server directly and play it on my local OS, vlc plays it just fine.
i found this thread on this topic from nearly 3 years ago!! and still this is an issue:
http://help.videojs.com/discussions/problems/754-flv-videos-not-playing

anyone got a response / explanation here?
thanks

**Comment by Ahmedhaseeb** [comment]
i am using vjs 4.12.7 can any one tell me how can i play flash video. i search a lot over google and did not find solution.

**Comment by mmcc** [comment]
You just need to specify `video/x-flv` as the type, but otherwise it should just work (assuming you have the SWF set up correctly). [Example](http://output.jsbin.com/fimivo)

**Comment by Ahmedhaseeb** [comment]
what i am doing.
I just add this in the head
 <link href="http://vjs.zencdn.net/4.12.7/video-js.css" rel="stylesheet">
 <script src="http://vjs.zencdn.net/4.12.7/video.js"></script>
And This After The Video Tag

 <script type="text/javascript">
            videojs( '#main_video', { plugins : { resolutionSelector : {
                
                default_res : "360"
            } } } );
        </script>

I am also using resolution selector plugin.

When click on 240p (video/x-flv) resolution it does not play and this video source directly play into my browser.

You Can This Live Here

http://ytube.getintoworld.com/embed.php?id=ip_0CFKTO9E

Default Resolution is 360p
When you try to change it to 240p You Will See This Error in console

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) FLASH: srcnotfound Object { code=4,  message="FLASH: srcnotfound",  MEDIA_ERR_CUSTOM=0,  more...}

Sorry for bad english

**Comment by propertunist** [comment]
i just returned to video.js and now the new version has fixed some of the errors i was experiencing before - so thanks. however, i now have a variation on this flash issue.

essentially, if i view this flash video (http://test.ureka.org/file/view/8064/fluoride) in firefox 39 on win  7, the video.js plugins i am using fail to load (although the video does play) and in the console i see:
```
Specified "type" attribute of "video/x-flv" is not supported. Load of media resource http://test.ureka.org/file/download/8064/shocking government coverups hiding fluoride_s connection t.flv failed.
All candidate resources failed to load. Media load paused.
TypeError: The element or ID supplied is not valid. (videojs)
```
other video formats appear to be playing ok so far.

**Comment by hemanik** [comment]
It still isn't working for me. Can someone put latest working example for this ?

**Comment by cytGitHub** [comment]
@mmcc  demo not work

**Comment by cytGitHub** [comment]
@mmcc  I would like to use video.js broadcast flv format live stream。 how can i do it  ?

**Comment by barriber** [comment]
I encounter the same problem and all examples in this thread show the same error,
Is there any solution for it?

**Comment by mister-ben** [comment]
If you're using Video.js 6.x, the Flash tech is no longer included by default. You need to add [videojs-flash](https://github.com/videojs/videojs-flash) if you do need it.

Even when you have the Flash tech available browsers are making it increasingly difficult to use Flash, disabling it by default. You need to plan to not be reliant on Flash to play video.

There is an [flv.js](https://github.com/Bilibili/flv.js/) project to play FLV with Media Source Extensions, but this still won't play on iOS as it lacks MSE support. There's a [plugin](https://github.com/mister-ben/videojs-flvjs) to use flv.js as a Video.js tech.

On the whole it's best to get away from FLV completely to a modern format. VOD could be transcoded/transmuxed to MP4/h265. For live streams use HLS.
