### ISSUE TITLE
Make es5-shim a dependency

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1687]
For v5, we should consider making es5-shim a dependency that users of videojs need to include for older browser support. It will make our lives easier if we can assume a higher level of js support provided by ES5.

This would also mean that we probably don't need as many other helper functions that re-introduce array iterator functions.

### Remaining Tasks

- [x] Confirm this direction
- [x] Choose the CDN-hosted version to use
- [x] Update all guides and examples to include
    - [x] Getting started guide
    - [x] sandbox example files
    - [x] build/demo files
    - [ ] ~~Website example embed codes~~ Moved to videojs/videojs.comj#29
    - [ ] ~~jsbin.com/axedog~~ This will come after 5.0 is officially release
    - [ ] ~~What else ???~~ Nothing.
- [ ] ~~Identify areas of the codebase that could be improved with ES5 features, and create issues to update them~~ (:mans_shoe: :football:)

**Comment by heff** [comment]
I updated this issue to list steps needed to complete it.

**Comment by dmlap** [comment]
Decision: Bundle es5-shim, es5-sham, and html5 video/audio shim into a file that gets hosted on the video.js CDN.

Watch out for cross-browser issues when **not** using the shim, because it also improves support in modern browsers, though we'd like to avoid making it a requirement for everyone to include even if they're not trying to support ie8.

**Comment by ljharb** [comment]
If you're looking for an "assign" shim that's spec-compliant, https://www.npmjs.com/package/object.assign is what you want (it will only shim the environment if you explicitly ask it to).

Please do bundle it in a way that makes it easy to deliver `es5-sh*m` updates.

Also, please note that every single browser, including latest Chrome and IE, lacks 100% ES5 compliance, so everything needs the `es5-shim`, IE 8 or no. :-)

**Comment by heff** [comment]
Thanks for the note @ljharb. I think we still want to avoid requiring everyone to include the es5 sh*m for all browsers, so we'll have to be conservative with the features we use.

**Comment by heff** [comment]
Closing as all tasks are complete or moved or punted.
