### ISSUE TITLE
vjs-lock-showing class gets removed from menu when no longer hovering on menu-button.

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1690]

**Comment by u-nice** [comment]
Ran into the problem too and fixed it by downgrading to v4.8.5 as this bug appears in 4.9.0.

**Comment by jeffski** [comment]
+1 this - [videojs-speed plugin](https://github.com/nicetip/videojs-speed) is broken in latest version because menu items won't stay open. Using v4.8.5 works fine.

**Comment by mmcc** [comment]
@jeffski videojs-speed will only work with 4.8.5 because it's relying on [mangled properties](https://github.com/nicetip/videojs-speed/blob/master/video-speed.js#L63). To be honest, that should probably be removed from the plugins list, especially since playback rates are supported in core now.

```javascript
videojs('my-video', { playbackRates: [ 0.5, 1, 1.5] });
```

**Comment by jeffski** [comment]
Thanks @mmcc, will try the core way instead.

**Comment by gkatsev** [comment]
Btw, I updated the wiki page to "deprecate" the plugin.
