### ISSUE TITLE
scr with query strings

### ISSUE THREAD

**Issue by campones** [videojs/video.js#1697]
With query string parameter (for secure link for instance), the src isn't working and I receive a rtmpconnectfailure. 

Note that the src provided actually works on flowplayer so it shouldn't be the issue

``` html
<source src="rtmp://serverip/appname/streamname?e=1417468789&st=yddiuVR5Tn8Pb4vItVxQew" type='rtmp/mp4' />
```

Format: ![alt](http://i.gyazo.com/b4b2d585574ca89ed06a8a330f03f6a3.png)

**Comment by jantekb** [comment]
Got it, you can send arbitrary query param [this way](http://streamtoolbox.blogspot.hu/2015/10/videojs-authentication-with-wrench.html)

**Comment by walec51** [comment]
I have the same problem with a HLS stream secured by a token for my IP.

```
https://cdn3.wowza.com/2/VTkwUkd0cWdPcVRq/Qzh3U3hn/hls/sjn51jbq/playlist.m3u8?hdnts=ip=188.33.51.48~exp=1635414833~hmac=21b87576dcd436f3a8f154120aee99f7b12710c8b1da2970ea3affa38aec5891
```

prze part `?hdnts=...` gets cut out
