### ISSUE TITLE
Extending a Tech

### ISSUE THREAD

**Issue by ksheurs** [videojs/video.js#1699]
I am trying to create a new Tech that is an extension of the base Flash tech. The goal is to support HLS playback in Flash (via https://github.com/mangui/video-js-swf) if the browser doesn't natively support it via Html5.

My thought was to create a `flashhls` tech by extending `videojs.Flash` and then my `techOrder` would be `['flashhls', 'html5', 'flash']`. I tried simply overriding the `canPlaySource` method to contain this new logic, but it didn't seem to work. 3 questions:
1. Is trying to solve this with `techOrder` and having `flashhls` first the correct approach?
2. Is the below code incorrect?
3. Can you explain what `maybe` means? Is it `yes`, `no`, `maybe`? `true` or `false`?

``` javascript
videojs.Flashhls = videojs.Flash.extend({
  canPlaySource: function(source) {
    if (source.type.toLowerCase() === 'application/x-mpegurl' && videojs.Html5.canPlaySource(source) === false) {
      return 'maybe';
    } else {
      return '';
    }
  };
});
```

Thank you!

**Comment by benjipott** [comment]
+1

**Comment by scottmcdonnell** [comment]
I ran into this recently and have managed to get a working extension of the Flash tech so, in my case, I could have the flash playback swfs. This worked for me:
```
/**
 * custom Tech extending the existing Flash Tech
 */
videojs.Mycustomtech = videojs.Flash.extend({});

function copyProps(obj, copy) {
	for (var attr in obj) {
        if (obj.hasOwnProperty(attr)) copy[attr] = obj[attr];
    }
}
copyProps(videojs.Flash, videojs.Mycustomtech );

/**
 * Checks to see if this tech can play the given source
 * @param  {obj} srcObj {src: "source.file", type: "mime/type"}
 * @return {bool}       true if can be played
 */
videojs.Mycustomtech.canPlaySource = function(srcObj) {
	var type = srcObj.type.split("/").pop();
  	return (type == 'myextension');
}

//copy the default flash player option to your tech's options
videojs.options.mycustomtech = { swf: videojs.options.flash.swf }
```
I then point to the new custom flash player using 
`videojs.options.mycustomtech.swf = "/path/to/video-js.swf";`
