### ISSUE TITLE
How to load tracks in dynamically loaded videos

### ISSUE THREAD

**Issue by mikaelmoller** [videojs/video.js#1700]
I'm developing a solution where I need to load and initialize the videos dynamically. I have several tracks for each video, captions, chapters, etc. How to do this? From some sort of a tracks array like below?

{
    src : [
        'http://video-url.com/video/video.webm',
        'http://video-url.com/video/video.mp4',
        'http://video-url.com/video/video.ogv'
    ],
    tracks : [],
    poster : 'http://url-to-poster/poster.jpg',
    title : 'Video'
}

**Comment by EZWrighter** [comment]
So is dynamic track loading support now and if so, what version did it start being supported?  Also, any current documentation on it's use other than what heff described above?

**Comment by gkatsev** [comment]
Unfortunately, we don't have good docs quite yet.
But basically, you have a `player.addTextTrack` and `player.addRemoteTextTrack`. The latter takes an options object that has properties like the track element does in html5.

**Comment by EZWrighter** [comment]
Is the complimentary removeRemoteTextTrack also available in the current CDN 4.12 version of the player?  I tried it, get no error, but it also does not remove the track.  I am attempting to update a custom playlist to support tracks, without completely disposing and reloading the player.
.

**Comment by gkatsev** [comment]
Yeah, `player.removeRemoteTextTrack` will remove text tracks. You can get a list of them via `player.textTracks()`.

**Comment by EZWrighter** [comment]
hmm, doesn't seem to work.  I will file a bug.
