### ISSUE TITLE
Video doesn't play when techOrder is set to 'Flash'

### ISSUE THREAD

**Issue by EmperorRXF** [videojs/video.js#1723]
# problem

I'm using the very bare form of video.js. When the techOrder is given priority to Flash, the video doesn't play at all in Chrome (Version 39.0.2171.71 m) or IE 11.

When I open the Chrome console, this line below can be seen. Also the call to google-analytics.com from the videojs fails as well.

video.js:7 Uncaught TypeError: Cannot read property 'C' of undefined

vjs.html:7 GET file://www.google-analytics.com/__utm.gif?utmwv=5.4.2&utmac=UA-16505296-2&u…n%2Fvjs.html&utmcc=__utma%3D1.4459758391.1.1.1.1%3B&utme=8(vjsv)9(v4.10.2) net::ERR_FILE_NOT_FOUND
# contents of vjs.html file

http://jsbin.com/qibafituxu/1/edit?html,output

When setting the techOrder to "html5" first, everything works fine.
# expected outcome

The video should be played inside a Flash Player when techOrder is set to "Flash" when flash is intsalled on the system.

**Comment by VarunAgw** [comment]
I am having same issue. Even white-listing videojs.swf on "Global Security Settings" is not working for me for file stored on local hard disk.
