### ISSUE TITLE
Mimic the video element API and DOM operations with the player div

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1728]
We have some options for matching the video element workflow more closely with video.js.
## 1. Mimic the video element properties and functions exactly on the player div

The video.js player instance API currently uses functions for getters/setters because old IE doesn't support the defineProperty API (IE8 only on dom elements). e.g. `currentTime(60)` instead of `currentTime = 60`. Also the player div itself has no video API, only a reference to the player instance. Now that we only support IE8+, we could make the player div have the exact same properties as the video element.

One concern here is that it would add some confusion, providing two different APIs, one on the player div and one on the player instance. However anyone currently working with the video element and DOM libraries like jQuery could more easily switch over to using Video.js because the element would look almost identical. Alternatively we could add the player instance API functions to the player div for consistency.
## 2. Handle adding/removing text tracks to the player div

The text track API of the video element currently relies heavily on the dom operations.
- The only way to add a track that uses a remote source URL is through adding a track element to the the video element (you can't use the addTextTrack API)
- The only tracks you can remove are those that were added using a track element. Any track added with addTextTrack can never by removed, only disabled.

It could be good to make this workflow possible with the player div, using MutationObserver and a shim for older browsers. https://github.com/webcomponents/webcomponentsjs/blob/master/src/MutationObserver/MutationObserver.js

A couple potential issues with this one.
- There's no native track element in IE8, so I'm not sure what it would look like to create on in IE8 and add track values to it. It could very well just work. You wouldn't have access to the textTrack property on it unless the player specifically added one after it was embedded in the player.
- The track element would live among all the control elements in the player div, in no particular order. Not totally sure what issues that would cause. Maybe none.

Any thoughts on either of these from anyone? No one is specifically asking for these features yet that I'm aware of, so they probably fall into the "would be cool" category. The text track workflow will become more relevant once we have more robust support for tracks.

---

@gkatsev, @dmlap, and @mmcc were in the original IRC discussion

**Comment by gkatsev** [comment]
I'm going to close this. I think we're moving away from this. We have API methods for most things and I think a custom videojs element would be a better thing to use to provide a DOM interface to videojs.
It's also been two years with no movement :)
