### ISSUE TITLE
Enable Sauce testing of JS pull requests via Savage

### ISSUE THREAD

**Issue by cvrebert** [videojs/video.js#1738]
@heff Just let me know whenever you're ready to follow up on https://github.com/twbs/savage/issues/1 :smile:

**Comment by cvrebert** [comment]
Step-by-step setup instructions are at https://github.com/twbs/savage/blob/master/SETUP.md

**Comment by cvrebert** [comment]
@heff @mmcc Still interested in this?

**Comment by heff** [comment]
Absolutely! ...most of us have just been bogged down building the next major version. Any way we can bribe you to help us set it up? :) We can at least offer you free beer and pizza at the [SF Video meetup tonight](http://www.meetup.com/SF-Video-Technology/).

**Comment by cvrebert** [comment]
@heff Yeah. Drop me a line at code-AT-rebertia-DOT-com with y'all's availability and we can figure out a time to work through it together on IRC/Jabber/whatever.

**Comment by cvrebert** [comment]
Implemented, and demoed in #2143.

**Comment by heff** [comment]
Thanks again @cvrebert!
