### ISSUE TITLE
IE8 Play Button doesn't respond.

### ISSUE THREAD

**Issue by mikemcguire** [videojs/video.js#1757]
Whenever I load the page in IE8 it shows me the play button with the poster image, when I press play nothing happens, if I hide the poster image I can see the blacked out swf.

I know I am not the first to have this problem, but I have gone through every article to find the issue. Here is a list of things I have tried:
- Upgraded Flash Player
- Loaded JS in my head
- Absolute path to my swf
- Absolute path to my mp4
- Tested in native windows XP, 7, and 8
- Tested in native IE8 (xp), and IE 11 in IE8 standards mode
- No javascript Errors. 

Sorry if this has been resolved somewhere, but I am at a loss to find it.

**Comment by mikemcguire** [comment]
Sorry for the delayed response. I was testing on work computers originally, but over christmas break I tested on my native windows machine, a virtual box on my linux machine and browserstack, where everything appeared to be working as expected. I come to work today and it's magically working on all of our machines... I swear I cleared my cache.. Closing this.

**Comment by heff** [comment]
No worries. Thanks for following up!
