### ISSUE TITLE
Switch to 'handleClick' listener naming over 'onClick'

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1761]
At the moment, most components use the 'on[Event]' naming structure for private-ish event handler/listener functions. This could be confusing with the element attributes like `onclick` that let you add a listener without using `addEventListener`. We should switch to `handle[Event]` for the naming, unless anyone has a better suggestion.

This may or may not be a breaking change, so we should assume it is and release with 5.0.

**Comment by bc-bbay** [comment]
On it

**Comment by gkatsev** [comment]
Closed via #2093
