### ISSUE TITLE
Firefox Support for Autoplay

### ISSUE THREAD

**Issue by skynet** [videojs/video.js#1763]
Is there anything special with Firefox. "autoplay": "true" doesn't seem to work.
Although probably not related, I see this error in the js console: Error: Permission denied to access property 'Mb' video.js:9

**Comment by heff** [comment]
If you create a WebM version of the video too it will help this situation.

Closing since this doesn't appear to require any changes to the codebase, but if this didn't answer your question @skynet let us know.

**Comment by skynet** [comment]
I did. And actually switched to Bootstrap Carousel where it works in Firefox. The problem seems to be with Owl carousel library. Thanks.

**Comment by heff** [comment]
Ok great! Good to hear.
