### ISSUE TITLE
Remove 'save video'  to context menu

### ISSUE THREAD

**Issue by dk-wamp** [videojs/video.js#1771]
Hello,
is possible remove option 'Save video as..' when I click on right of the mouse on videojs player?

**Comment by dioobr** [comment]
Hello,

I know this record is old, but I have the same need. An alternative, which is even used by youtube, vimeo, is to include a layer in front of the video. Something like:

`<style>
video { position: absolute; z-index: 20; }
.canvas {position: absolute; z-index: 30; }
</style>

<div>
<video src="example.mp4"></video>
<div class="canvas"></div>
</div>
`
What do you think?
