### ISSUE TITLE
Video looping in Chrome

### ISSUE THREAD

**Issue by blasian** [videojs/video.js#1774]
For some reason, when I attempt to use video.js with Google Chrome, all fields within the 'data-setup' attribute will work except for the 'loop' field. I have used the following code to implement this.

    <video id="myVid" class="video-js vjs-default-skin" data-setup='{"width":372, "height":666, "controls":true, "autoplay":true, "loop":true}'>
        <source src="img/simonsaysdemo.mp4" type="video/mp4"></source>
        <source src="img/simonsaysdemo.ogg" type="video/ogg"></source>
        <source src="img/simonsaysdemo.webm" type="video/webm"></source>
    </video>

When I run this in Chrome all fields within data-setup seem to work except for 'loop'. I'm wondering what I can do to fix this. I have tried other options such as the following Javascript to no avail.

    myVid.setAttribute('src', "videos/clip1.mp4");
    myVid.autoplay = true;  
    myVid.addEventListener('ended', vidEnded);  
    function vidEnded()
    {
        myVid.setAttribute('src', "videos/clip1.mp4");
        myVid.autoplay = true;          
    }

Thanks in advance!

**Comment by mmcc** [comment]
This original issue seems to be fixed.

**Comment by surwasesandy** [comment]
not allowed to load local resource: file:///Users/..." this type error how to handle
