### ISSUE TITLE
vjs.woff error in FireFox (bad linegap)

### ISSUE THREAD

**Issue by SimonG04** [videojs/video.js#1775]
I am getting the following error in my console in FireFox 34 with the latest version of video.js:
```
downloadable font: OS/2: bad linegap: -64 (font-family: "VideoJS" style:normal weight:normal stretch:normal src index:1)
source: http://vjs.zencdn.net/f/3/vjs.woff
```

**Comment by mmcc** [comment]
We have indeed switched to a new icon set altogether for the default theme in version 5, so this shouldn't be an issue anymore in the near future. @mister-ben want to submit a patch PR for version 4 anyway with the fixed font?

**Comment by SimonG04** [comment]
Thanks guys, you rock!
