### ISSUE TITLE
Change HTTP Referer of Request of Video

### ISSUE THREAD

**Issue by carbos10** [videojs/video.js#1778]
I've a MP4 video that I've taken from an extern website. So the website close connection from extren website and I can't play the video.
I think that website use HTTP Referer and I can manage it using socket but request is by Video.JS. How can I manage this request? Can I use socket before?

**Comment by mmcc** [comment]
I'm not sure I follow...the request is simply made by the browser (unless you're using Flash), so we're not doing anything strange around the referrer. You might need use something like Media Source Extensions so you can have a bit more control over the requests?

**Comment by carbos10** [comment]
Emh, in xhr.js there's a HTTP Request... So i've tried to edit this code: http://vjs.zencdn.net/4.9/video.js
I edit this line: try{h.open("GET",a,f),e&&(h.withCredentials=f)}catch(r){d(r);return}try{h.send()}catch(w){d(w)}

in: try{h.open("GET",a,f),e&&(h.withCredentials=f)}catch(r){d(r);return}h.setRequestHeader("referer", "http://www.website.com");try{h.send()}catch(w){d(w)}

but when i see the Headers Request, the referer doesn't change

**Comment by gkatsev** [comment]
As @mmcc said, we don't make requests to the video ourselves in videojs. Either the the browser handles it itself or flash handles it. Either way, unless you're going to use Media Source Extensions and handling the downloading of the video yourself, you cannot change the referrer.

**Comment by carbos10** [comment]
i read topics on web about Media Source Extensions, but i don't find where i can change the Headers Request, do you have any idea?

**Comment by zjyfdu** [comment]
add the following to your head tag, referred from [here](https://stackoverflow.com/questions/40335856/no-referer-in-request-headers-from-video-tag-request-by-android-browser)
```<meta name="referrer" content="always">```
