### ISSUE TITLE
How do I add overlay advertisements?

### ISSUE THREAD

**Issue by TommehM** [videojs/video.js#1779]
How can I add small overlay advertisements to the bottom of videos with video.js?

**Comment by mmcc** [comment]
There's [videojs-contrib-ads](https://github.com/videojs/videojs-contrib-ads) for linear ads, but it doesn't support overlay advertising (that I know of). You're going to need custom JS to do something like this, but depending on what you want to do that could be pretty straight forward. 

In the simplest sense, you could just use css to position a div on top of your video and have a button to dismiss (or not). You could get fancier and have it change ads based on `currentTime` or something along those lines, but either way this would make for a great plugin. Any interest in working on it?
