### ISSUE TITLE
scale video to fill div

### ISSUE THREAD

**Issue by cytec** [videojs/video.js#178]
Hi,

i want to scale a video to fill the parent div.
i know the height="100%" and width="100%" stuff, but what i want to do is, that the video is scaled to fill the WHOLE div, not only width OR height.. i need both of them

like this:
http://i.imgur.com/Xkfvl.jpg

i need this because it should be a backround movie running in an div which is 70% width of the browser and 100% height atm im useing the 100% width parameter but if i shrink the window down (height > width) the video doesnt fill the div anymore ...

works verry well till u resize it to be wider than high...
http://test.vorsicht.de/video/videojs/index.html

scales to fitt the whole div on resize:
http://test.vorsicht.de/video/projekktor/index.html

i found out that projkktor can handle it (http://www.projekktor.com/docs/configuration#config)

/ scaling used for videos (flash and native, not youtube) "fill" or "aspectratio" / videoScaling: 'fill',

but i prefere to use videojs cause the player works better, also it loops perfectly :)

is there anyway i can do this?

**Comment by wilbefast** [comment]
Hate to necromancer - I wanted to report that ``<video class="video-js vjs-default-skin" data-setup='{ "width" : auto, "height" : auto }'>`` behaves the way OP wanted... provided that the player is implemented using an HTML 5 video tag rather than a flash object.

A flash object is generated when the video is being streamed via RTMP - at the moment I can't figure out how to make this RTMP flash video behave the way the HTML 5 one does. No amount of CSS and Jquery seems to make a dent in its behaviour, because Flash. Minimal code:

```
<html>

<head>
  <link href="http://vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.11/video.js"></script>  
</head>

<style>

video, #my_video, .video-js, .vjs-default-skin
{
  position: fixed; 
  right: 0; 
  bottom: 0;
  min-width: 100%; 
  min-height: 100%;
  width: auto; 
  height: auto; 
  z-index: -100;
}

</style>

<body>
  <video id="my_video" class="video-js vjs-default-skin" autoplay preload="auto" >
    <source src="rtmp://slznmw3zvood9.cloudfront.net/cfx/st/&mp4:big_buck_bunny.mp4" type='rtmp/mp4'>
  </video>
</body>

</html>
```

**Comment by Jul1u5** [comment]
I am really sorry, but I just cant get it to run. I have implemented the video player and used your code to do so but the width and height just stays the same....
Thank you for your help!

**Comment by Webolye** [comment]
@wilbefast, thanks. works for me.

**Comment by hijuuijj** [comment]
@wilbefast, thanks. works for me.

**Comment by vaishnavravi33** [comment]
Set data-setup option to true and set the div width and height as per your need. 
It will show video in full size of container div.

```
<div class="full-vid">
    <video id="vid1" class="video-js vjs-default-skin vjs-big-play-centered"
        controls
        width="100%"
        height="100%"
        data-setup='{ 
            "techOrder": ["youtube"],
            "aspectRatio":"16:9", "fluid": true,
            "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=PjGkVCAo8Fw"}]
        }'
      ></video>
</div>
```

**Comment by hammaduzair** [comment]
document.querySelector(video).setAttribute("style", "object-fit: cover");

**Comment by gkatsev** [comment]
You can use the `fill` option or `vjs-fill` class to make the player take up the size of its container: https://docs.videojs.com/tutorial-layout.html#fill-mode
