### ISSUE TITLE
muted attribute not completely handled

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#1780]
The muted attribute is transferred to the video element when the HTML tech is in use but the volume controls still show 100% volume (the default) initially. The Flash tech does not appear to honor the muted attribute. See [this example](http://jsbin.com/hiyemiwaci). Originally filed as https://github.com/videojs/videojs-contrib-hls/pull/149

**Comment by heff** [comment]
I can confirm this is happening. On the flash side it probably needs to be handled by the tech, through checking the player's muted value on init.

The volume control probably needs to do the same on init.

**Comment by mmcc** [comment]
Closed via #2408
