### ISSUE TITLE
Aurora.js and Silverlight Tech

### ISSUE THREAD

**Issue by Afterster** [videojs/video.js#1782]
Since recent video.js changes to be used as an audio player, video.js has bump a lot more interest to me :)
I'm currently using jPlayer for [Ampache](https://github.com/ampache/ampache) project which showing some serious limitation about video features compared to video.js.
I don't have much time to code on video.js for now but I'm wondering if adding additional fallback (=Tech here) is something on the roadmap? Silverlight is explicitly cited in https://github.com/videojs/video.js/blob/master/docs/guides/tech.md but I cannot found any existing Tech plugin like Flash, neither an VLC plugin Tech or anything similar.

I just contributed to jPlayer to add solution plugin and added Aurora.js in https://github.com/Afterster/jPlayer/blob/plugins/src/javascript/jplayer/jquery.jplayer.aurora.js (eg. for FLAC streaming) and more recently Silverlight in https://github.com/Afterster/jPlayer/blob/plugins/src/javascript/jplayer/jquery.jplayer.silverlight.js (for wma and wmv streaming) using [medialement.js](https://github.com/johndyer/mediaelement) project xap file. I believe most code could be reused to create new video.js Tech plugins.
[Aurora.js](https://github.com/audiocogs/aurora.js) Tech and even Silverlight / VLC plugin Tech would be great addition to improve audio support in video.js, what do you think?

**Comment by heff** [comment]
Absolutely, both would be great if you can find the time to put them together and release a plugin. You can look at some of the techs on [the plugin list](https://github.com/videojs/video.js/wiki/Plugins) or [the internal techs](https://github.com/videojs/video.js/tree/master/src/js/media) for inspiration. Aurora.js would be really cool to have access to as a tech. What browsers does it support?

**Comment by Afterster** [comment]
Ok :), I will try to do something then and discuss about development progress / ask for some advices here then. Thanks.
Aurora.js requires the Web Audio API, so it will work with modern browsers (Firefox, Chrome, Opera) but not IE (should be supported in IE 12 / Windows 10).

**Comment by heff** [comment]
Ok, that sounds great!

**Comment by Afterster** [comment]
@heff I just created a Silverlight tech to train myself about video.js development. This add WMV, WMA, MP4 and MP3 stream support through Silverlight (I updated wiki Plugins page ; btw videojs-wavesurfer  shouldn't be in Tech session, isn't it?).
This is my first video.js plugin and also the first time I'm using grunt and associated tools. Could you take a look on the repository just to be sure I don't make big mistakes? https://github.com/Afterster/videojs-silverlight
The Silverlight XAP component is a fork of mediaelement.js XAP source code. There is no real value to recreate another XAP that wrap MediaElement .NET Framework component, code would be the same...

During the plugin development I noticed vjs.getAbsoluteURL was private. I had to recreate this function in my plugin code. Shouldn't it be public as it is useful for most new tech?

I will wait some feedbacks before working on other tech, thank you ;)

**Comment by Afterster** [comment]
Ok I wanted to play more and didn't wait for your feedbacks sorry :)
I updated Silverlight Tech to add WAV (PCM only) and FLAC (no seeking for now) stream support.
Then I also created a new [VLC Tech](https://github.com/Afterster/videojs-vlc) using VLC Web Plugin just because I'm a VLC fan :smile:.
I finally end-up creating the [Aurora.js Tech](https://github.com/Afterster/videojs-aurora) quickly enough.
These three new Tech are working but I'm looking forward for feedbacks as these are my first play on Video.js, thanks!

From my opinion, Video.js is missing two major features to be a decent audio player: possibility to hide the unused video part, and audio-only Flash support (mp3 / ogg ?). After that few playlist improvement should also be done but that's another topic.

Btw, it would be great to have more demo file types hosted on zencoder.com, like http://video-js.zencoder.com/oceans-clip.flac (mp3, wav, flac, ogg, m4a, wmv, wma ...).

**Comment by Afterster** [comment]
I also created a dummy Java fallback (with JMS) mainly focused on audio for AIFF, AVI, GSM, MID, MPG, MP2, MOV, AU and WAV stream support through Java. Video is working but it has some continuous window refresh issues). See [videojs-java](https://github.com/Afterster/videojs-java).

**Comment by heff** [comment]
Woah @Afterster, you've been productive!! I'm about to review your plugins. I'll leave comments or post issues on those repos.

> I noticed vjs.getAbsoluteURL in lib.js was private

Yes, we should make that public. We're about to do an overhaul of API methods for 5.0, and that will be included.

> Btw, it would be great to have more demo file types hosted on zencoder.com

It would be great to have more examples like that. @mmcc?

**Comment by heff** [comment]
I'm going to close this since it doesn't require a change to the core code base, but we can continue the discussion here.
