### ISSUE TITLE
Setting src to an empty string throws an error.

### ISSUE THREAD

**Issue by WalrusCow** [videojs/video.js#1785]
Is there a good way to stop the current video from loading? `player.src('')` works but spews errors into the console, which is undesirable.

Why not dispose of the player? I want to continue playing the same video later, I just don't want it eating bandwidth while "paused".

**Comment by 02clams** [comment]
I ran into this several version ago and fixed it by using a single space for the src(" "). An empty string caused the video to continue loading, but the single space finally terminated the connection.

**Comment by mmcc** [comment]
Ok so I think we're all talking about different things here. There's an actual issue that was introduced in 4.11.3 that we're putting out a fix for right now.

@02clams if you're referring to the `MEDIA_ERR_SRC_NOT_SUPPORTED` error, that's an error that's getting thrown because a blank string is technically not a supported source, so we're getting that error from the video element.

**Comment by WalrusCow** [comment]
I was also referring to the `MEDIA_ERR_SRC_NOT_SUPPORTED` error (looks like two in console, but upon inspection seems to be just one).  Thanks for such a quick and helpful response! :)

**Comment by ange007** [comment]
Perhaps I do something not so, but in the last stable version *( with the editings given above )*, at: ***player.src (' ');***

**VIDEOJS: TypeError: Cannot read property 'handleSource' of null {stack: (...), message: "Cannot read property 'handleSource' of null"}**

**Comment by mmcc** [comment]
@ange007 #1787 fixed this and went out with today's patch release (4.11.4).

**Comment by ange007** [comment]
Last version.

>this.player.pause( );
this.player.src( '' );

Result:
http://i.imgur.com/0AcHrYe.png

**Comment by mmcc** [comment]
You're totally right. I'm going to edit this title to be a little more descriptive and re-open.

**Comment by ksheurs** [comment]
Is there a preferred way to clear out the source in `4.12.2`?

I am using the resolutions plugin that seems to set this on load. See https://github.com/vidcaster/video-js-resolutions/blob/master/video-js-resolutions.js#L42 for reference.

With that line in there, I am also seeing the `Uncaught TypeError: Cannot read property 'handleSource' of null` error.

**Comment by ksheurs** [comment]
thanks for that!
