### ISSUE TITLE
Name techs

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1786]
It'll be very helpful if tech components were named as such: `"Tech {{tech name}}"`. It'll make debugging easier when you just have a component with a name property set to null.

**Comment by heff** [comment]
I'm not following. Can you give an example?

**Comment by gkatsev** [comment]
If you print out a tech in the console, it's `name_` property is set to null. Only components like BigPlayButton have `name_` properties.
Or if you call `.name()` on them you get 'null'.

**Comment by gkatsev** [comment]
```js
player.tech.name() // using non-minified videojs
// null
```

**Comment by heff** [comment]
Are you saying specifically give all tech names like "Tech html5", or that in the case where a tech name is null, the name would be "Tech [nothing]".

The component names are used for option setting and parent object references, so I don't know if we want to be prefixing the names.
```
player.controlBar // <-- component name
videojs(id, { bigPlayButton: false }) // <-- component name
```

Could we just make sure the name property gets set for techs?

**Comment by gkatsev** [comment]
yeah, even if name returns 'tech' that give me a lot more info. I was debugging an issue earlier where a tech had no associated `el()` and was erroring out on timeupdate. Took me a long time to realize that the component that the timeupdate was triggered on was a tech.

**Comment by heff** [comment]
Cool. I think because of the point about how the name is used, adding a name to the techs by default would be the best approach. e.g.

```
vjs.Html5.prototype.name_ = 'html5';
```
