### ISSUE TITLE
need help in creating an outer fullscreen button

### ISSUE THREAD

**Issue by Elvin-Xhimitiku** [videojs/video.js#1788]
I need to create a ''fullscreen' button on the website, when clicked, it makes the video.js enter in fullscreen (as when the video player is displayed on smarttv, the controls dont show up on hover)

please help

**Comment by mmcc** [comment]
You're looking for the [requestFullscreen method](https://github.com/videojs/video.js/blob/master/docs/api/vjs.Player.md#requestfullscreen). Good luck!

**Comment by Elvin-Xhimitiku** [comment]
thanks a lot for the quick reply. can you please give me couple lines of code as i am exhausted from trying to figure this out all night :(

**Comment by mmcc** [comment]
Pseudo-code pretending you're using jQuery:

```js
var player = videojs('your-video-player');
$('#fullscreen-btn').click(function() { 
  player.requestFullscreen();
});
```

**Comment by Elvin-Xhimitiku** [comment]
i am using this on a drupal theme. should i put this on the plugin js or on the theme js?

**Comment by mmcc** [comment]
I'm sorry to say I know nothing about Drupal, so this where I leave you to your own devices. You should be able to put that anywhere after Videojs is loaded.

**Comment by Elvin-Xhimitiku** [comment]
ok thanks a lot for your time. i got a couple of errors but i will keep trying :)
take care
