### ISSUE TITLE
Pre defined duration

### ISSUE THREAD

**Issue by steelbrain** [videojs/video.js#1789]
There should be some option that allows us to set Predefined duration, as soon as the video is loaded and starts playing, the duration can then switch to it's length.

**Comment by heff** [comment]
Would the duration API work for your needs? `myPlayer.duration(100)`​

**Comment by mmcc** [comment]
The docs for the duration method are a little confusing since it's only mentioned as a getter, so the [source](https://github.com/videojs/video.js/blob/master/src/js/player.js#L730) might make a little more sense.
