### ISSUE TITLE
Firefox + mac skips video to end, and only plays after clicking the progress bar

### ISSUE THREAD

**Issue by stevenliemberg** [videojs/video.js#1791]
Hello,

I have found a weird issue with the videoJs player on mac in combination with firefox. When the play button is clicked the video skips almost to the end and wont play. It will only play after clicking on the progress bar multiple times and then clicking play.

The site having the issue is found here http://addmywindow.com/ (the video is at about 2/3 down below "verhalen")

Maybe Im missing something obvious, but it seem weird to me because the problem only occures on the combination firefox+mac.

I hope you nice folks can shed some light on the subject. 

cheers!

**Comment by stevenliemberg** [comment]
Thank you for your reply. It did not occur to me to just try a plain video tag. I think you are on to something here...

**Comment by mmcc** [comment]
This is almost certainly an issue with that specific video file, so I'm going to close this one.
