### ISSUE TITLE
video.js buffering in chrome - clicking HTML links doesn't respond

### ISSUE THREAD

**Issue by geibi** [videojs/video.js#1799]
I run video.js on my wordpress page with the video.js worpdress plugin. I got a fairly large video (about 130MB) on my home page. When loading my site, the video starts buffering.

When i now click on a link to another page on my page, e.g. in the navigation for getting to my contact page, Chrome continuously tries to buffer the whole video. Only after the full video is buffered, Chrome responds to my click and redirects to the new page. Which sometimes needs about 4 minutes on a normal internet connection.

I can disable preloading for the video in the video.js settings and everything works fine. But when i click "play" on the video, the same problem occurs. Chrome starts buffering and doesn't accept clicks on links and doesn't interrupt buffering.

In Firefox and Safari, everything works fine, whilst in Safari there's also a fairly longer delay after clicking a link to a new page compared to Firefox.

I also tried smaller videos (about 30MB), but the problem stays the same.

Is this a known issue in Chrome or video.js? What can i do to stop Chrome from buffering the video until the end?

**Comment by mmcc** [comment]
Hrm, that's really strange. No, this is not a known issue in either, I don't believe I've ever seen anything like it. Is there a demo page you could point us to? Can you try and put together a [reduced test case](http://jsbin.com/axedog/latest/edit)?

**Comment by geibi** [comment]
hi mmcc, after setting up a local isolated test case it turned out, that not video.js itsself is responsible for the crash, but the "secure html5 video player" which utilizes video.js.
you can close the issue and i thank you for your help

**Comment by gkatsev** [comment]
Closing per OP's request.
