### ISSUE TITLE
Translation files not accessible on CDN

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#1800]
When you build video.js using grunt a `cdn` folder gets created in `dist`. This contains the video.js source, css, a demo.html and the `lang` folder containing the translations. It seems all of these files are also actually available on the CDN (eg. http://vjs.zencdn.net/4.11.3/demo.html) except for the `lang` folder (eg. http://vjs.zencdn.net/4.11.3/lang/es.js gives permission error).

**Comment by thijstriemstra** [comment]
I'm assuming the dev team has control over that cdn and can fix the problem there. In the meantime, an alternative CDN that does host the language files is http://nl.cdnjs.com/libraries/video.js, for example `https://cdnjs.cloudflare.com/ajax/libs/video.js/4.11.3/lang/nl.js`.

**Comment by mmcc** [comment]
@thijstriemstra thanks for the heads up! you're correct, we need to add these to the CDN on our end. We should be able to take care of that with the next deploy.

**Comment by thijstriemstra** [comment]
Any news?

**Comment by heff** [comment]
I'm not sure what happened here. Our grunt task appears to be creating the
lang folder for the CDN upload, but then grunt-s3 must be excluding the
folder for some reason.​

**Comment by thijstriemstra** [comment]
Ok..

**Comment by heff** [comment]
http://vjs.zencdn.net/4.12/lang/ar.js

**Comment by thijstriemstra** [comment]
:) thx
