### ISSUE TITLE
The video playback was aborted due to a corruption problem or because the video used features your browser did not support.

### ISSUE THREAD

**Issue by JoshSmith** [videojs/video.js#1802]
In IE 11 on Windows 7 with video.js 4.11 I'm seeing the error `The video playback was aborted due to a corruption problem or because the video used features your browser did not support.`

The video tag looks like the following:

```html
<video id="ember1049_html5_api" class="vjs-tech" preload="none" data-setup="{ &quot;playbackRates&quot;: [0.5, 1, 1.5, 2] }" poster="https://res.cloudinary.com/cookacademy/image/upload/c_fill,h_720,w_1280/o8kdej2ah8xlk8gpi6co" src="http://dqmtr9mrpkd03.cloudfront.net/videos/11/oven_calibration.webm?Expires=1421341324&amp;Signature=AWz2dfk2JwUUTuddqdMVfNROzzEukahIzT1LSrlHNNo5SeBNNVflaFxWVnJk0vwYXnzaAUsVBozFyBebNFX~7jRH~cqch5MBvECBY91lVZVfH800DMlu9jS25JLa1XxIjcGaOPh3Cxs3sHDPcmIRkFERgTBys~3zlcNS6CG1AnzJTvUsL8dt4SSN5mNmZRJkkiJiIqpmMkB-P4tRFkHVui1pqOPFGejb1KlwhTG7lnc~wuyIEpKB8pyZOr~oUSt4r4Rpo7Z5k9IvN152pXqOg8~IogtotfdV4ar5mmW-SaW8QYlVakLE5hNvHEjRrWOkeLeQZ9lvqOo1NdXVCs9e3Q__&amp;Key-Pair-Id=APKAJLWXM4FN5YTBNNPA">
  <source src="http://dqmtr9mrpkd03.cloudfront.net/videos/11/oven_calibration.webm?Expires=1421341324&amp;Signature=AWz2dfk2JwUUTuddqdMVfNROzzEukahIzT1LSrlHNNo5SeBNNVflaFxWVnJk0vwYXnzaAUsVBozFyBebNFX~7jRH~cqch5MBvECBY91lVZVfH800DMlu9jS25JLa1XxIjcGaOPh3Cxs3sHDPcmIRkFERgTBys~3zlcNS6CG1AnzJTvUsL8dt4SSN5mNmZRJkkiJiIqpmMkB-P4tRFkHVui1pqOPFGejb1KlwhTG7lnc~wuyIEpKB8pyZOr~oUSt4r4Rpo7Z5k9IvN152pXqOg8~IogtotfdV4ar5mmW-SaW8QYlVakLE5hNvHEjRrWOkeLeQZ9lvqOo1NdXVCs9e3Q__&amp;Key-Pair-Id=APKAJLWXM4FN5YTBNNPA" data-bindattr-1050="1050" type="video/webm">
  <source src="http://dqmtr9mrpkd03.cloudfront.net/videos/11/oven_calibration.mp4?Expires=1421341324&amp;Signature=WX2SYSGmuNNfuItAVZ5RP2qHFFKqd2DU505Aua0ZAC6wO-ZJwTjzsGQL8S0Vux-ZSwV5vAm5voUo6EOyWPwIz-C53B~6NVKGhDad-YIEXMfhdGZsaHBhIbaK9MuIN5ngXnKUTN8iGAvOp~k8HsqPDk6eCNha2K0sgBmxepKZOm-JgXLIz2Y9DoqaowipLulNEHSjQiIDiRNKvxtnVco2Zpmm-Rv8hB1OIx0ZxEEW9fLc6hEi5nltDLs6cGTpQbyHVCtiutGupOP3yF2PR2A5W5R9V2ZTLRIfDwBb9nThcxzpWBz~bysaUhV157GHLRGQS8SBeevwVw901Ejypc~cHg__&amp;Key-Pair-Id=APKAJLWXM4FN5YTBNNPA" data-bindattr-1051="1051" type="video/mp4">
</video>
```

**Comment by mmcc** [comment]
Usually issues with Ember are due to not creating / disposing players in route transitions. Can you put together a reduced test case? IE11 / Windows 7 / VJS 4.11 work fine for me, so my guess is this is a case where Ember and VJS aren't playing nice.

**Comment by JoshSmith** [comment]
@mmcc I'll try to get together a reduced example for you later this afternoon.

For now, I'll also post the `video-tag` component I'm using:

I use it in handlebars like so:

`{{video-tag video=substep.video handleVideoEvent='handleVideoEvent'}}`

And here's the component itself:

```coffee
`import Ember from 'ember'`

VideoTag = Ember.Component.extend
  tagName: 'video'
  classNames: ['video-js', 'vjs-sublime-skin']
  attributeBindings: ['controls', 'preload', 'width', 'height', 'dataSetup:data-setup', 'poster']
  preload: 'none'
  dataSetup: '{ "playbackRates": [0.5, 1, 1.5, 2] }'
  poster: (->
    cloudinaryId = @get('video.posterCloudinaryId')
    if cloudinaryId
      Ember.$.cloudinary.url(cloudinaryId, {width: 1280, height: 720, crop: 'fill'})
    else
      ''
  ).property('video.posterCloudinaryId')
  controls: ''
  setupVideoJs: (->
    self = @
    video = @get('video')
    element = @get('element')
    videojs(element, {}, ->
      @on('play', ->
        self.sendAction('handleVideoEvent', video, 'Played', element)
      )
      @on('pause', ->
        self.sendAction('handleVideoEvent', video, 'Paused', element)
      )
      @on('seeked', ->
        self.sendAction('handleVideoEvent', video, 'Seeked', element)
      )
      @on('ended', ->
        self.sendAction('handleVideoEvent', video, 'Finished', element)
      )
      @on('error', (event) ->
        e = @error()
        if Raven? and e?
          Raven.captureMessage(e.message)
      )
    )
  ).on('didInsertElement')

`export default VideoTag`
```

**Comment by mmcc** [comment]
We have a strict no coffeescript rule in these parts, so this issue will now be closed :trollface:

Only kidding. To be honest, I'm a little surprised this is working at all since you're using the `data-setup` attribute and not initializing via JS. Keep in mind that the `data-setup` attribute is really only meant to be used to initialize players on page load, so if you're dynamically creating / destroying players you'll need to initialize by calling `videojs()` on the element. 

So, if that's what your goal is, I would suggest just creating a video element with the classes you'd like, then calling `videojs('ID', { playbackRates: [0.5 ... 2] })` on that new element after transitioning to the route containing the player. When you transition away from that route, you should call dispose on that player.

**Comment by mmcc** [comment]
Just a note, when you build out the reduced test case, it might be helpful to use the [Ember JSBin](http://emberjs.jsbin.com/?html,css,js,output)

**Comment by JoshSmith** [comment]
`data-setup` was never working and now I understand why. But even without that are you saying this should not be working?

**Comment by mmcc** [comment]
The `data-setup` bit was the primary reason that I was thinking your example wouldn't work. Did you ever get a chance to put together a reduced test case?

**Comment by jesusjjf** [comment]
I am also having this error. 
Was initializing the player with JS at first, but now i still get the error with `data-setup` attribute as well.

``` js
<video id="video-webinar" class="video-js vjs-default-skin vjs-big-play-centered" width="auto" height="auto" data-setup="{}" controls autoplay>
  <source src="the_video.mp4" type='video/mp4' />
</video>
```

Using `video.js 4.12.5` + latest version of Chrome
Doesn't break on Safari

```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The video playback was aborted due to a corruption problem or because the video used features your browser did not support.
```
```
t.J {
  code: 3,
  message: "The video playback was aborted due to a corruption problem or because the video used features your browser did not support."
}
```

**Comment by jesusjjf** [comment]
Error does not happen when I disable hardware-accelerated video decode on chrome.
URL `chrome://flags`
And disable `Disable hardware-accelerated video decode.`

**Comment by mmcc** [comment]
I feel like that last report is almost certainly a browser bug related to the native player and not something we can handle on the Video.js side. I'm going to close this issue, but if we should revisit just ping and we'll reopen.
