### ISSUE TITLE
Retry after network error

### ISSUE THREAD

**Issue by steelbrain** [videojs/video.js#1805]
Cloudflare has a bug or something that when a video is streaming for about ten minutes, It'll close the connection. You'll have to refresh the page to reload the video and fast forward to where you were.

It'd be nice to make videojs catch that error and retry to download the video atleast once.

**Comment by heff** [comment]
That would be cool. For the most part we try to mimic how the video element works exactly in the core player, but I think that could be a really useful plugin. Any interest in putting one together?

**Comment by steelbrain** [comment]
Aye Aye Captain.

**Comment by heff** [comment]
Nice! I'm gonna close this issue since it doesn't require changes to core, but we can continue to discuss this here if you have any questions or want feedback.

**Comment by ksheurs** [comment]
Happen to know if something like this ever came about? We started tracking errors/exceptions in production and there is surprisingly a lot of network issues: "The video could not be loaded, either because the server or network failed or because the format is not supported." or "A network error caused the video download to fail part-way.".

If not, what would be the best approach for a plugin? Listen for when VideoJS throws error code 2 and then reload the source? Thanks!

**Comment by mmcc** [comment]
@ksheurs I know a few other folks did something along those lines, so I think that sounds reasonable.

**Comment by ahomu** [comment]
Already a plugin to solve this problem?

**Comment by andrey-sw** [comment]
I have a similar problem.

player.on('error', function(event) {
  if (player.error().code === 2) {
    player.error(null); // clear out the old error
//////////////////////////////////////////////////
//    player.src(sources); // retry
// dont work
/////////////////////////////////////////////////////
//      player.load();
//      player.start();
// dont work
///////////////////////////////////////////////////////
    return;
  }
});

how to restart the video, it is desirable from the same position when the network is restored

**Comment by hzeroo** [comment]
Any updates on this?

**Comment by richardrails** [comment]
any updates?

**Comment by billwing** [comment]
I try this and solve the problem.

    var player = videojs('player', {}, function() {
        this.on('error', function(event) {
            var time = this.currentTime();

            if(this.error().code === 2) {
                this.error(null).pause().load().currentTime(time).play();
            }
        });
    });

**Comment by JeffreyWay** [comment]
I experience this often. Almost identical to what @ksheurs said. Would love an official workaround or solution for this...

**Comment by gkatsev** [comment]
This seems like an often requested feature that when a source errors to try the next source in the list, if available. Given that videojs tries to make life easier, this seems like something that should be in core, so, I'm going to re-open this.

**Comment by kavin-90** [comment]
@gkatsev thanks

**Comment by Yalhu** [comment]
It's great if this feature added in video.js core. I resolve this issue according to @sylvio-ruiz(#4044) and @billwing .
```javascript
var timer;
function onerror(){
  switch(player.error().code){
    case 2:
       document.getElementById('loadvideo').style.display = 'block';
       timer=player.setInterval(()=>{player.load().currentTime(time).play()},5000)
       break;
  }
}
function onplaying(){
  player.clearInterval(timer);timer=null;
}
```
I want to know which API should I use , `setTimeout` or `setInterval`. `error.code==4` will handle every other  time. `error.code==2` only handle once. 
And is `onplaying` the right event that I clear Interval? 

There is an another issue: player error event doesn't fire on mobile #5089.

**Comment by wowcut** [comment]
I am looking for exactly this and I am not able to answer these questions myself from the docs atm:
* How is the current state of reloading videos on errors? 
* What is the current best practice?
* Does videojs handle reloading the same source or loading next source on error at all?
* If yes, how can I configure the number of reload tries and timeouts?
* Does exist some advanced logic, e.g. increasing timeouts with each reload, like found in many network softwares that must handle network errors?
* Do I have to use some of the code snippets that fly around this issue tracker?
* If yes, I would really like to see a best practice code snippet right from the devs, tested and approved with your incredible test infrastructure.

Reloading on error is very important for a robust experience. It would be very appreciated if videojs devs would like to tackle this, make this a first class feature and add some canonical documentation about it, so it is clear how to handle that, which feature details exactly are supported and what the user has to do to.

Thank you very much for your attention!

**Comment by MW3000** [comment]
Any progress on this issue?

I sometimes experience _"A network error caused the video download to fail part-way"_ errors.

The player freezes with a big white **X** in the center and becomes totally inresponsive. For a user, the only way to recover seems to be, to reload the entire page.

It would be desirable, if a user could instead restart the video from the beginning in case of such an error.

**Comment by jayarjo** [comment]
Bump.

**Comment by gkatsev** [comment]
It's been a while, but we're finally adding this in. For now, we're doing it just as an option, but we'll consider enabling it by default in the future. See https://github.com/videojs/video.js/pull/7038
