### ISSUE TITLE
How to use Speed Controller of PlaybackRates Option on RTMP type.

### ISSUE THREAD

**Issue by KatsuyaHiguchi** [videojs/video.js#1806]
Hello. I have a question.

I would like to use PlaybackRates Option on RTMP type along the following lines.
But, Speed Controller is unshown.

Can someone help and tell me about it？

----------------------------------------------------------------------------

<html>

    <head>
        <title>sample_page.</title>
        <link rel="stylesheet" media="screen" href="/assets/stylesheets/reset.css">
        <link rel="stylesheet" media="screen" href="/assets/stylesheets/main.css">
        <link rel="stylesheet" media="screen" href="/assets/stylesheets/bootstrap.min.css">
        <link rel="stylesheet" media="screen" href="/assets/stylesheets/bootstrap-theme.min.css">
        <link rel="shortcut icon" type="image/png" href="/assets/images/favicon.png">
        <script src="/assets/javascripts/jquery-2.1.1.min.js" type="text/javascript"></script>
        <script src="/assets/javascripts/bootstrap.min.js" type="text/javascript"></script>
        <script src="/assets/javascripts/main.js" type="text/javascript"></script>

    <link href="http://vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/4.11/video.js"></script>

    </head>
    <body>

	<video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640" height="264"
	poster="http://video-js.zencoder.com/oceans-clip.png" data-setup='{"playbackRates": [0.5, 1, 1.5, 2]}'>
		<source src="rtmp://xxxxxxx.cloudfront.net/cfx/st/&mp4:xxxxxxx.mp4" type='rtmp/mp4' />
		<track kind="captions" src="/assets/data/demo.captions.vtt" srclang="en" label="English" />
		<track kind="subtitles" src="/assets/data/demo.captions.vtt" srclang="en" label="English" />
		<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
	</video>

    </body>

</html>

----------------------------------------------------------------------------

**Comment by heff** [comment]
Unfortunately RTMP uses Flash, and Flash doesn't support the playback rates. We've looked at ways of adding playback rate support in Flash and it's not easy.

@seniorflexdeveloper could OSMF support playbackRates a.k.a "trickplay"

**Comment by seniorflexdeveloper** [comment]
I do not believe OSMF supports playback rates.
