### ISSUE TITLE
Video.js subdirectories doesn't work

### ISSUE THREAD

**Issue by yurevich1** [videojs/video.js#1807]
neither rtmp://host:1935/vod/flv:a/flv.flv nor rtmp://host:1935/vod//a/flv.flv works for video.js !!!! how to fix it?
In all cases rtmpconnectionfailture.

**Comment by mmcc** [comment]
Since you followed this issue up with a question about your RTMP stream having the wrong framerate, I'm going to assume that you got playback working.

**Comment by yurevich1** [comment]
No. You are not right. IT doesn't depend on framerate.
rtmp://host:1935/vod/file.flv - WORKs!
