### ISSUE TITLE
Feature Request: isPlaying() method

### ISSUE THREAD

**Issue by dominic-p** [videojs/video.js#181]
Hello, in adding some custom event handlers I'm finding it necessary to determine if the video is currently playing or not. This is possible (albeit convoluted) with the HTML5 tech, but I have no idea how to go about it with the flash tech.

It might be nice to have an abstracted `isPlaying()` method that simply returns `true` or `false` based on if the video is playing or not.

**Comment by shaharmor** [comment]
Btw, `paused()` doesn't correctly reflect `isPlaying()` because if the player is stuck on buffering/downloading the movie, `pasued()` will be false, while the video is not really playing.

**Comment by oleynikd** [comment]
@shaharmor 100% agree! I'm also looking for `isPlaying()` method cuz `paused() == false` only tells that it is not paused...

**Comment by framerate** [comment]
Was there ever a solution on this? I'm getting the same instance state and it's quite annoying.

**Comment by misteroneill** [comment]
My $0.02 here is to listen to various events to track that state. Something like:

```js
var isPlaying = false;

player.on(['waiting', 'pause'], function() {
  isPlaying = false;
});

player.on('playing', function() {
  isPlaying = true;
});
```

The `playing` event definitely sounds like what you'd look for to determine that playback is beginning:

> Playback is ready to start after having been paused or delayed due to lack of media data.
