### ISSUE TITLE
Error event not documented

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#1810]
The `error` event isn't documented in the player api docs.

**Comment by mmcc** [comment]
Good catch. Any interest in submitting a PR? You can follow the example of one of the [other events](https://github.com/videojs/video.js/blob/master/src/js/player.js#L382) so it will show up in the generated documentation.

**Comment by thijstriemstra** [comment]
Alright. Looking at the source you create a stub method for each event so you can document it in the docstring? PR will follow.

**Comment by heff** [comment]
Closed by #1819
