### ISSUE TITLE
URL matching bug

### ISSUE THREAD

**Issue by H1D** [videojs/video.js#1813]
This is a buggy regexp - https://github.com/videojs/video.js/blob/e8235c9022ae60e656695205948b6de61d440dd2/src/js/media/html5.js#L327

For urls like "https://example.com/video.sd.mp4?s=foo" match group `#1` will be `sd.mp4` instead of expected `mp4`

Example: https://www.debuggex.com/r/qksngI_8cqz6SyCz
![image](https://cloud.githubusercontent.com/assets/697625/5819034/95c1a0ec-a0cb-11e4-9111-42c1b0549bb1.png)

Is it an urgent bug? Should i use `contrib hotfix start`?

**Comment by H1D** [comment]
fix is ready BTW https://github.com/H1D/video.js/commit/a24e79390b426322273df2913e808f1b46a3386f

**Comment by mmcc** [comment]
Thanks for the quick PR! This looks good to me, go ahead and submit a PR whenever you're ready.

On another note, did you end up using contrib? Any thoughts there?

**Comment by H1D** [comment]
@mmcc https://github.com/contrib/contrib is a fantastic idea! Dunno why no one created it before seems like an obvious idea.
Hope @heff will be able to make it as high quality OSS project as video.js is.
