### ISSUE TITLE
Issue playing mobile video.

### ISSUE THREAD

**Issue by xbgmsharp** [videojs/video.js#1815]
Hello,

I recently update to VideoJS 4.11.2, the latest available version, the ChangeLog refer to 4.11.3.

Now the player is unable to play any MPEG4 file for an iPhone source.
As a personal gallery, most video are from a mobile device or a personal camera.
Video from Android still seen to works.

I run multiple tests:
* On OSX 10.10.1 using Firefox 35 and Safari 8.0.2.
Both browser are unable to play an iPhone video recorded as it does in version 4.10.
Safari is unable to play any video file.
Firefox plays the WebM and Ogg and some MP4 file (Format profile Base Media).
I have 2 messages that appears in the console:
```
Media resource galleries/video/IMG_2669.mp4 could not be decoded.
"VIDEOJS:" "ERROR:" "(CODE:3 MEDIA_ERR_DECODE)" "The video playback was aborted due to a corruption problem....
```
Chrome 39 is playing any supported format without any issue.

* On Ubuntu 14.04LTS using Firefox 35, the iPhone video does not play.
I have 1 messages that appears in the console:
```
"VIDEOJS:" "ERROR:" "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" "No compatible ...."
```

* On Windows 7 using IE11, the video play correctly.
Firefox plays the WebM and Ogg and some MP4 file (Format profile Base Media).
I have 2 messages that appears in the console:
```
Media resource galleries/video/IMG_2669.mp4 could not be decoded.
"VIDEOJS:" "ERROR:" "(CODE:3 MEDIA_ERR_DECODE)" "The video playback was aborted due to a corruption problem...."
```

Maybe it is the way the browser handle the H264 format.

Using MediaInfo, it seen that the format MPEG-4 with the Format profile QuickTime is not supported anymore.

Sample video details from an iPhone.
```
# mediainfo galleries/video/IMG_2669.mp4 
General
Complete name                            : galleries/video/IMG_2669.mp4
Format                                   : MPEG-4
Format profile                           : QuickTime
Codec ID                                 : qt  
File size                                : 4.15 MiB
Duration                                 : 46s 83ms
Overall bit rate                         : 756 Kbps
Recorded date                            : 2014-06-24T11:23:05+0200
Encoded date                             : UTC 2014-07-19 17:12:33
Tagged date                              : UTC 2014-07-19 17:12:42
Writing application                      : 7.1.1
Writing library                          : Apple QuickTime
©xyz                                     : 
Model                                    : iPhone 5s
Make                                     : Apple
com.apple.quicktime.creationdate         : 2014-06-24T11:23:05+0200
com.apple.quicktime.model                : iPhone 5s
com.apple.quicktime.software             : 7.1.1
com.apple.quicktime.location.ISO6709     : 
com.apple.quicktime.make                 : Apple

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L3.0
Format settings, CABAC                   : No
Format settings, ReFrames                : 1 frame
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
...
```

Sample video details from an Android, working on FF but no Safari.
```
# mediainfo galleries/video/VID_20140720_Video_android_4.4.3_landscape.mp4 
General
Complete name                            : galleries/video/VID_20140720_Video_android_4.4.3_landscape.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 43.5 MiB
Duration                                 : 36s 32ms
Overall bit rate                         : 10.1 Mbps
Encoded date                             : UTC 2014-07-19 22:54:10
Tagged date                              : UTC 2014-07-19 22:54:10

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 1 frame
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
...
```

**Comment by heff** [comment]
It looks like v4.11.3 isn't making it to videojs.com for some reason. I can't see exactly why yet but you can get 4.11.3 here. https://github.com/videojs/video.js/releases/tag/v4.11.3

Can you try that and see if it fixes your issue?

**Comment by xbgmsharp** [comment]
Thanks, I updated to v4.11.3. Unfortunately, I still got the same issue.

**Comment by mmcc** [comment]
Do you have a source file available for testing? I don't know of any changes to the SWF that would have affected anything, but if we can get a source it'd be easy to narrow down what version broke things.

**Comment by xbgmsharp** [comment]
I created 2 jsfiddle files. Both include the same source file available for testing.
http://jsfiddle.net/xrota15w/3/
http://jsfiddle.net/js79L69r/7/

On OSX 10.10.1 using Safari 8.0.2 and Chrome 40.0, the video does play.
On OSX 10.10.1 using Firefox 35, the video does not play.

On Windows 7 using IE11, the video does play.
On Windows 7 using Firefox 35, the video does not play.

**Comment by xbgmsharp** [comment]
While trying to narrow down the issue, I discovered the techOrder which I never change before.
By changing the techOrder exactly (" won't replace ' ) as below Firefox play all the videos just fine.
```
data-setup='{"techOrder": ["flash","html5"]}'
```
Safari will not play any WebM or Ogg videos and raise a MEDIA_ERR_SRC_NOT_SUPPORTED.
The console report the following output:
```
VIDEOJS: 
Error
column: 16
line: 4209
message: "undefined is not an object (evaluating 'this.tech[method]')"
sourceURL: "https://localhost:4443/.../video.dev.js"
stack: "..."
__proto__: Error
```
Chrome play all the videos just fine just as before.

**Comment by mmcc** [comment]
Sadly, Safari (and IE) doesn't support [WebM](http://caniuse.com/#feat=webm), so no surprise there :(

Your first example works fine in [JSBin](http://jsbin.com/xopami) standalone, so I think the issue is actually JSFiddle not allowing Flash.
