### ISSUE TITLE
Swiping video causes video to play on ipad iOS 8.1

### ISSUE THREAD

**Issue by smohadjer** [videojs/video.js#1817]
If I go to videojs.com and swipe video in an attempt to scroll the page the video starts playing! If I pause video and swipe again, video does not start playing. Why video plays on first swipe? How can I avoid video play during page swiping?

**Comment by mmcc** [comment]
I can quasi-confirm this one. On both an iPad and iPhone it works fine if I scroll how I normally do, but if I shorten it to more of a quick, swiping motion then it will trigger a click event most of the time. We should probably decrease the length that's considered a swipe vs click?

**Comment by smohadjer** [comment]
I can accept that a slow swipe be mistaken for a click, but a fast swipe being counted as click is certainly wrong.

**Comment by mmcc** [comment]
Why would you expect an actual dragging motion to be mistaken for a click? I'm having to actively change how I scroll to reproduce this, but it seems like a reasonable movement so I agree that it's probably worth experimenting with a lower [tap movement threshold](https://github.com/mmcc/video.js/blob/master/src/js/component.js#L1041). Want to find a lower number that works for this movement and submit a PR?

**Comment by smohadjer** [comment]
No, I can play video after it's stopped by tapping anywhere on the video on iPad, but I can't play it by swiping. This makes me wonder if the problem lies indeed in swipe logic because then swiping should continue to trigger a click after video is stopped and hence play it, same as a click does.

**Comment by mmcc** [comment]
Well that's strange, I'll hold off opening an issue for that, then...For whatever reason click events on the player itself aren't working for me. Our iPad for testing just died, so I'll play with that more later today.

FWIW, I don't think that's related to the click / swipe confusion. A quick look around for the tap threshold in other projects shows anything from [2](http://hammerjs.github.io/recognizer-tap/) to 11, which even on the larger end is still half what our current tap movement threshold is.

I'll test the element-click issue more later today and open a separate issue if need be.

**Comment by smohadjer** [comment]
I don't think reducing the tap threshold is the right way to better differentiate taps from swipes. Perhaps it would be better if we take velocity also into account. This article explains the problem well:

http://minuum.com/taps-and-swipes/

**Comment by mmcc** [comment]
I think lowering the tap threshold would certainly improve things, but a PR taking velocity into account would certainly be welcome.

**Comment by Jackipy** [comment]
I am hitting the same issue on iPhone iOS 8.1.2 as well.

I am building a webpage with a list of videos, and scrolling through the page would inevitably open a video by accident. Unfortunately, iOS launches the video in full screen and interrupts the user's scrolling. The user has to close the full screen video and "be careful" not to scroll too fast. This makes the page very hard to use.

**Comment by steverandy** [comment]
There are two things that cause this issue:
1. `touchDistance` is always 0 on iOS devices (I tested on iOS 8).
2. `tapMovementThreshold` and `touchTime` values are set to high (currently 22 and 250)

I have already sent a pull request to fix point 1, https://github.com/videojs/video.js/pull/1809.
For point 2, I propose we use 10 for `tapMovementThreshold` and 200 for `touchTime` like what [fastclick](https://github.com/ftlabs/fastclick) lib is using.

**Comment by Jackipy** [comment]
Steve - thanks for submitting the fix for 1 and looking into 2! I am really looking forward to seeing this fixed in the next release.

**Comment by mmcc** [comment]
Thanks for the ping on this one, I'd been meaning to put out a PR for `tapMovementThreshold`, but I think it makes sense to also reduce the `touchTime` threshold to what @steverandy suggests. Patch PR: #1830

**Comment by mmcc** [comment]
That PR was merged in, so closing.
