### ISSUE TITLE
Flash support is broken

### ISSUE THREAD

**Issue by Rameshv** [videojs/video.js#1821]
Hi,
   Seems flash support is broken. As per this issue https://github.com/videojs/video.js/issues/1274, video elemet must have source node to make it work. But in the latest release both `src` and `source` are not working.

Check this fiddle http://jsfiddle.net/Anyt8/2/ with the different options

**Comment by Rameshv** [comment]
sorry,my bad.

**Comment by heff** [comment]
no problem :)​
