### ISSUE TITLE
videojs performs an awkward ajax request during initialization on a ie8 client 

### ISSUE THREAD

**Issue by DeveloperOfDeath** [videojs/video.js#1822]
Hello, 
I use videojs as a videoplayer for all webpages that play videos. I noticed a strange behaviour on clients that use IE8 (Im aware that shouldn't be used for about 10 years or so. But the integrated fallback is one reason i use videojs :D)
Btw, the url of the webpage i have problems with is [redacted - NSFW].
The site features erotic content, so dont visit if youre puritan or have a problem with that because of other reasons:) URL is only needed as an example anyway.
During initialization, it does an request to http://www.sehiba.com/VX/LP that seems unneccesary and has no effect on the playback of the page. Cause there is nothing there, our server performs a redirect.

Any help appreciated! Cheers

**Comment by mmcc** [comment]
While I don't consider myself a puritan, I think NSFW applies here. Thanks for the heads up, though.

Are you using the CDN version or hosting yourself? Are you using tracks? HLS? There are a few different things that could be making an AJAX request, but it's impossible to know without seeing a working (or not working, rather) example. Can you create a reduced test case using something like [JSBin](http://jsbin.com/axedog/latest/edit)?

**Comment by DeveloperOfDeath** [comment]
Hi, solved the problem by setting an poster image in the options. 
if poster image is left blank, the player requests the image in the path of the website. (line 6222).
While this behaviour is unproblematic in most applications, it means trouble for high traffic video ads using video.js. 
IMHO the problem could easily be solved by putting the method call (line 6222)inside the if branch (starting line 6222) that checks if the url is set.

**Comment by mmcc** [comment]
I think you're referring to [this method](https://github.com/videojs/video.js/blob/master/src/js/poster.js#L52-L67). Any interest in putting together a PR?

**Comment by DeveloperOfDeath** [comment]
Yes, you're right. The line numbers are different because i was referring to the whole skript video.dev.js 
A Pull request would be great. What do I have to do for that?

**Comment by mmcc** [comment]
This [guide](https://github.com/videojs/video.js/blob/master/CONTRIBUTING.md#contributing-code) might look daunting, but I promise it's not too bad. Let us know if you have any questions!
