### ISSUE TITLE
Cannot obtain original video dimensions in IE8

### ISSUE THREAD

**Issue by bewards** [videojs/video.js#1824]
I've gotten VideoJS to be responsive with just CSS in every browser besides IE8. And so my work around was to obtain the aspect ratio of the video to set the height accordingly. It seems that, in IE8 (also using html5shiv), getting the original dimensions of the video are not possible, as it defaults back to 300x150. This may not be a bug, as this is a SWF fallback inside a html5 video container, but I'd like to confirm if this is correct? If not possible, it seems the only work around would be to give a static aspect ratio.

**Comment by mmcc** [comment]
There's a pretty long thread about responsive sizing, and basically the tl;dr is yes, you have to specify the aspect ratio going in (at least that's what we've come up with so far). If you have any additional feedback, feel free to comment there: #982.

**Comment by bewards** [comment]
Thanks for the very quick response, I'm a big fan of this ongoing video work. I actually based the responsive off that thread. I'll contribute to it if my approach has a better support range.

**Comment by mmcc** [comment]
Excellent! That would be much appreciated.
