### ISSUE TITLE
Playlists are hard with ads involved

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#1825]
Filing this in the main repo so it has a few more eyes on it and because it touches on the event API that we want video.js users to interact with.

On mobile devices, advertisements may have to take over the video element. That causes all the regular video lifecycle events (e.g. `loadstart`, `playing`, `ended`) to fire. If you're a developer trying to implement something like a playlist plugin, your plugin would have to include ad detection code and ignore events that happen during ad playback. The complexity isn't confined to just playlists, either: end screens, overlays, and anything else that relies on the video timeline could be affected. Rather than force all those plugins to dance around ads, we should enhance [contrib-ads](https://github.com/videojs/videojs-contrib-ads) to keep this complexity away from people who don't care about it.

Details on the proposed changes are laid out in this [playlist API proposal](https://gist.github.com/dmlap/b70dbdbcaccc6707c531).

**Comment by dmlap** [comment]
I'd be really interested in opinions from any of the @videojs/contributors or @jgallen23 and @tim-peterson.

**Comment by heff** [comment]
It's looking good to me.

**Comment by mmcc** [comment]
@dmlap any reason to keep this open now? Seems like the the PR on contrib-ads is going swimmingly.

**Comment by gkatsev** [comment]
We got comments. Closing.
