### ISSUE TITLE
Plugins not working properly

### ISSUE THREAD

**Issue by Succo** [videojs/video.js#1827]
I am trying to create a plugin to integrate a new provider, as of now it is impossible to do in a "clean" way.
If I try to follow the plugins doc, the function I define get added to videoJS when I call `vjs.plugin` but the function is never actually called.
If create the plugin by oveloading the vjs object, I have to use the non mimified version as some public properties get there name reduced. 

Is there any solution to be able to use my provider as a plugin with the mimified version of videoJS?

**Comment by gkatsev** [comment]
I think `vjs` isn't exported in the minified code. You should use `videojs`.
Then for a plugin you can do something like:
```js
videojs.plugin('plugin', function() {
 /* do your plugin stuff here */
});

var player = videojs('my-video');
player.plugin();
```

**Comment by mmcc** [comment]
Ah, didn't realize the [docs](https://github.com/videojs/video.js/blob/master/docs/guides/plugins.md) were still referencing `vjs`. Just updated them to help others down the road.
