### ISSUE TITLE
Get "Not Implemented" error on IE11 (Win 8)

### ISSUE THREAD

**Issue by steverandy** [videojs/video.js#1832]
Video.js: 4.11.4
Browser: IE11
OS: Windows 8

The error is triggered by this line (media/html5.js line 390)
`vjs.Html5.prototype['featuresVolumeControl'] = vjs.Html5.canControlVolume();`

**Comment by steverandy** [comment]
![screenshot 2015-01-28 16 45 24](https://cloud.githubusercontent.com/assets/525332/5934642/150f0c9e-a70d-11e4-8b1a-e2b15caf099b.png)

**Comment by dmlap** [comment]
Were you seeing this on desktop or a Win8 mobile device?

**Comment by mmcc** [comment]
Hm...I'm not seeing this in 4.11.4 in IE11 on Windows 7, but I'm traveling so I don't have a Windows 8 VM to test with. @gkatsev any chance you can verify this on a VM or something from the device lab?

**Comment by steverandy** [comment]
@dmlap desktop win 8 running on a VM.

**Comment by mmcc** [comment]
Just double checked on a Windows 8 VM running IE11 and VJS 4.12.2 and there were no errors in the console. I'm going to close this, but if you can set up a reduced test case we can revisit this.

**Comment by whocreates** [comment]
We're seeing issue running IE 11 on Windows 7 (VMWare Fusion running on a OSX). VJS Version 4.12.15.

Stops the rest of the JavaScript from loading.

**Comment by laxplaer** [comment]
Hi I have the same issue as @whocreates and @steverandy..

**Comment by pravinweb** [comment]
Hi 

I am facing same issue 
version: Video.js 5.4.6 <http://videojs.com/>

Viertualbox IE 11 windows 7

<img width="1004" alt="screenshot at dec 06 00-11-55" src="https://user-images.githubusercontent.com/14888335/33624516-a7d3441c-da1a-11e7-86ea-43b89bf9956b.png">

Thanks,
Pravin
