### ISSUE TITLE
does it support multiply videos within one video tag?

### ISSUE THREAD

**Issue by gimm** [videojs/video.js#1836]
just got to know this awesome video.js, I was trying to build a chrome plugin to replace online flash video with a html 5 video, usually, the video were split into parts, and in different resolutions, formats maybe. what we can get form the flash video page is something like this:
```javascript
{
"hd":[
  {part1: {src:"url/to/hd/part/1"}},
  {part2: {src:"url/to/hd/part/2"}}
],
"1080P":[
  {part1: {src:"url/to/1080P/part/1"}},
  {part2: {src:"url/to/1080P/part/2"}}
]
}
```
and I want to use them like this:
```html
<video attributes>
  //movie were split into parts and formats(mp4 and ogg, both HD)
  <source src="movie-part-1.mp4" type="video/mp4" />
  <source src="movie-part-2.mp4" type="video/mp4" />
  <source src="movie-part-1.ogg" type="video/ogg" />
  <source src="movie-part-2.ogg" type="video/ogg" />
</video>
```
or even better:
```html
<video attributes>
  //different resolutions, can switch between in video controllers
  <hd-src-set>
    //hd source list goes here
  </hd-src-set>
  <1080p-src-set>
    //1080p source list goes here
  </1080p-src-set>
</video>
```

if not supported (yet), should I try make it happen(do some customization or plugins for video.js) or 'invent' my own html 5 player? How much pain will there be? Any better ideas?
thanks~

**Comment by mmcc** [comment]
As far as resolutions go, what you're looking for is probably something like [videojs-resolutions](https://github.com/vidcaster/video-js-resolutions) by Vidcaster. For the bit about multiple parts, it sounds like you want something along the lines of a playlist plugin. There are a few in the [plugins list](http://github.com/videojs/video.js/wiki/Plugins) that you can take a look at.
