### ISSUE TITLE
Add  ads ?

### ISSUE THREAD

**Issue by hieuhuynh93** [videojs/video.js#1837]
How to add ads to video and close ads to play video ?

**Comment by mmcc** [comment]
There are a few plugins that can help with advertising functionality. You might want to start with [videojs-contrib-ads](https://github.com/videojs/videojs-contrib-ads) or [videojs-ima](https://github.com/googleads/videojs-ima), but there are other [plugins](http://github.com/videojs/video.js/wiki/Plugins) that might be helpful to you as well.

**Comment by hieuhuynh93** [comment]
Thank you, but I have other problem, if I use CDN Hosted, the player work, but I hosted js and css files, the player still work but it doesn't display icon.

**Comment by mmcc** [comment]
Did you make sure to upload the font icons and update the location in the CSS file if necessary? The [self hosted guide](https://github.com/videojs/video.js/blob/master/docs/guides/setup.md#self-hosted) makes a quick reference, but basically the dist folder (or zip contents) need to be uploaded as is unless you make changes to the CSS file.

**Comment by hieuhuynh93** [comment]
I solved it, and does videojs support responsive?
