### ISSUE TITLE
iOS 8+ Play Error on iPhone Only

### ISSUE THREAD

**Issue by rogeruiz** [videojs/video.js#1845]
This bug occurs on iOS 8+ on iPhone, primarily. This is a very nasty bug that is not easily reproducible, but has happened many times with the version of Video JS we are running. The version of VJS we are using is 4.4.1.

1. Load up [player](http://player.cnevids.com/stage)
2. Press the play button using an iPhone with iOS 8 +

> Expected: The video (ad) should play.

> Actual: A click event is captured and a new tab is displayed, at the same time the video will play and open then close and you will be left with the new tab focused. Other times the video will play in-line without any controls, which is an anomaly for iOS on the iPhone. I am included screenshots of both scenarios described here.

![unnamed](https://cloud.githubusercontent.com/assets/706004/6029827/2044601a-abc1-11e4-8191-29134b0403e2.png)
![unnamed-1](https://cloud.githubusercontent.com/assets/706004/6029828/21b5d82a-abc1-11e4-8a66-bde4fd40e3ce.png)
![unnamed-2](https://cloud.githubusercontent.com/assets/706004/6029830/2413c406-abc1-11e4-9d9d-7a516fe6050a.png)
![unnamed-3](https://cloud.githubusercontent.com/assets/706004/6029831/25212c62-abc1-11e4-9c5c-6377abe0a99c.png)
![unnamed-4](https://cloud.githubusercontent.com/assets/706004/6029838/2a628126-abc1-11e4-8095-f7c63f069a24.png)
![unnamed-5](https://cloud.githubusercontent.com/assets/706004/6029839/2ce33f80-abc1-11e4-9d66-cc683ec4f1ee.png)
![unnamed-6](https://cloud.githubusercontent.com/assets/706004/6029841/2e2d1ef6-abc1-11e4-8059-b57011a989a3.png)
![unnamed-7](https://cloud.githubusercontent.com/assets/706004/6029843/2f4b8b88-abc1-11e4-97d8-b039e2d55388.png)
![inline-video-on-iphone](https://cloud.githubusercontent.com/assets/706004/6029846/31e8d580-abc1-11e4-9923-506ea80086cd.gif)

http://player.cnevids.com/stage
https://thescene.com/watch/verge/bill-gates-interview-how-the-world-will-change-by-2030

I'm not quite sure what is happening here. I have tried debugging this since iOS 8 has been released. I'm aware that we're behind on our version of VJS, and am hoping that there may be some feedback on what an upgrade path may look like, if needed.

Any feedback would be appreciated. This bug is very tricky to reproduce, but once you reproduce it it can be viewed consistently.

**Comment by gkatsev** [comment]
Hopefully, grabbing the latest version of videojs shouldn't require you to make any changes on your end.
Also, that's a very weird bug.

**Comment by rogeruiz** [comment]
Hey @gkatsev,

I've actually attempted the upgrade path before, and besides some tests failing in our test suite it was pretty seamless. I will try again to upgrade and see if I can still reproduce this bug.

I guess what my concern is if this is something that the VJS team has seen happen before? From your response it doesn't seem so. When iOS8 had first come out I thought that it was related to [this release](https://github.com/videojs/video.js/releases/tag/v4.8.4), so I actually just patched our version with the following where it was appropriate in our codebase.

```js
if (vjs.IS_IOS) {
  vjs.on(video, 'webkitbeginfullscreen', vjs.bind(this, function(e) {
    this.player_.isFullscreen(video['webkitDisplayingFullscreen']);
    if (this.player_.isFullscreen()) {
      vjs.on(video, 'webkitendfullscreen', vjs.bind(this, function(e) {
        this.player_.isFullscreen(video['webkitDisplayingFullscreen']);
        this.player_.trigger('fullscreenchange');
      }));

      this.player_.trigger('fullscreenchange');
    }
  }));
}
```

I see that you were the author of this patch. Is there anything in your research in fixing this that seems related to the bug I'm reporting?

Thanks! :raised_hands:

**Comment by gkatsev** [comment]
Nope, nothing strikes me as being related, at least at first glance. But with ios, who knows.

**Comment by mmcc** [comment]
@rogeruiz any chance you've had an opportunity to test this with the most recent version (4.12.1 at the moment)?

**Comment by gkatsev** [comment]
Needs to be tested with v5.
Going to close this as it has been awhile, but if you retest and there's still an issue, we can reopen.
