### ISSUE TITLE
Prevent video.js sending google analytics data

### ISSUE THREAD

**Issue by djangosdk** [videojs/video.js#1848]
Hi
I am hosting video.js on my server but video.js keeps sending  http://www.google-analytics.com/__utm.gif?u call.
My application is supposed to be intranet and customers are worried about this call as they want to keep their privacy.

Any suggestions to remove this ?

**Comment by djangosdk** [comment]
atleast make it configurable

**Comment by gkatsev** [comment]
I believe we're planning on making it configurable. In the meantime, the non-cdn version of videojs doesn't do that.

**Comment by djangosdk** [comment]
thankx i got  non-cdn version of videojs.
