### ISSUE TITLE
how to set "data-setup", if i want to use ["youtube"] and ["dailymotion"] on same player or

### ISSUE THREAD

**Issue by tuyhin** [videojs/video.js#1852]
use 2 or more api.

**Comment by dmlap** [comment]
Something like this:
```html
<video class="videojs vjs-default-skin"
            data-setup='{ "techOrder": ["youtube", "dailymotion"] }'
            controls>
</video>
```

You will need to check with those other projects to find out the correct MIME type to pass in so that the right tech is loaded for the right source. I think for YouTube, you would do something like this:

```js
myPlayer.src({ src: 'http://youtu.be/eXaMpLeViDeO', type: 'video/youtube' });
```
