### ISSUE TITLE
CDN expiration header

### ISSUE THREAD

**Issue by alexcasalboni** [videojs/video.js#1855]
Assets loaded via CDN does not provide any expiration header (browser cache).

![videojs-cdn-expiration-header](https://cloud.githubusercontent.com/assets/2457588/6111939/e55eb736-b08c-11e4-8af5-8c5e120f6516.png)

**Comment by heff** [comment]
@alexcasalboni, thanks for the heads up. The headers [were getting set](https://github.com/videojs/video.js/blob/master/Gruntfile.js#L101) in previous releases, but apparently something has broken with our grunt s3 plugin, which [is unmaintained now](https://github.com/pifantastic/grunt-s3) so we need to switch completely. I'll try to get to this soon, but if you have any desire to help out on this feel free.
