### ISSUE TITLE
Captions: Update vtt.js once it gets updated with new shim work

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1866]

**Comment by heff** [comment]
I'm assuming this is the related vtt.js milestone, but correct me if I'm wrong.
https://github.com/mozilla/vtt.js/milestones/Polyfill%20support

**Comment by gkatsev** [comment]
Specifically, [this PR ](https://github.com/mozilla/vtt.js/pull/338) or similar.

**Comment by gkatsev** [comment]
We've decided to maintain a parallel fork with changes that allow us to consume it more easily but otherwise, we'll keep up-to-date from current and push back fixes.
