### ISSUE TITLE
Opera 27.0 Pause bug

### ISSUE THREAD

**Issue by SeregaL** [videojs/video.js#1867]
Hi!
This bug occurs on Opera 27.0 with pause (one click on video).

For replication of bug:
> 1) Open video (you can try example on [http://www.videojs.com](http://www.videojs.com))
> 2) Press the play button.
> 3) Make one click on video (not the pause button).

Expected: The video should pause.

Actual: Video pauses only while you hold down left mouse. It continue playing when you release the left mouse button.

P.S. Pause button work great.

**Comment by mmcc** [comment]
Can confirm. Also looks like there are some bizarre style issues with the seek handle.

**Comment by Watch-Video** [comment]
The Problem occures in vjs.MediaTechController.prototype.onClick
if we remove the play pause part it works only in opera browsers

**Comment by anonym24** [comment]
Is there any solution to reselve that issue?

**Comment by mmcc** [comment]
No, there hasn't been any update here, and I just confirmed it's still happening with Opera 29. Anyone interested in taking a look at this one?

**Comment by anonym24** [comment]
https://forums.opera.com/discussion/1865677/html5-video-pause-by-mouse-doesn039t-work - someone said it works in developer version

**Comment by mmcc** [comment]
*sigh*...looks like this is still an issue. If you click, drag off the player, then release, things work. My guess is this is something to do with mouse down vs mouse up or double triggering events.

(╯°□°）╯︵ ┻━┻

**Comment by anonym24** [comment]
Works nice in Opera 31 (beta)

**Comment by mmcc** [comment]
@anonym24 woo! Ok that's good news, I tested in Opera 30.

**Comment by isaacminogue** [comment]
Yeah, I noticed this too. The mouse up triggers a pause on the video element. Works ok if you use the actual pause play button though...

**Comment by anonym24** [comment]
31 is released. It works. The issue can be closed now

**Comment by mmcc** [comment]
\o/
