### ISSUE TITLE
Check current version of videojs

### ISSUE THREAD

**Issue by denisvlr** [videojs/video.js#1871]
I'm writing a third party plugin and I would like to check the current version of videojs to make sure it will work as expected.
Is there a method to do that?

I saw that there's a dev attribute `CDN_VERSION` which has the info i'm looking for, but it gets minified on production releases.

**Comment by heff** [comment]
There hasn't been one up until now but the next version (4.12.0 going out today) will have a VERSION key. What's the feature/fix that you need for your plugin?

(closing but you can keep commenting)

**Comment by multivoltage** [comment]
Please @heff can you show me hot to check this version?
