### ISSUE TITLE
FR: Add controlsVisibilityChanged event

### ISSUE THREAD

**Issue by shawnbuso** [videojs/video.js#1879]
Hi, I work on the [IMA plugin for video.js](https://github.com/googleads/videojs-ima). We sometimes have bottom-third overlay ads on our videos, and when the controls are shown I want to bump the ad up so it's not covered by the controls. I thought I could do this using player.on("mouseover|mouseout"), but these end up being really unreliable when we have our ad container div over the video player. It would be nice if I could just catch an event when the controls are shown or hidden and update my ad position accordingly.

**Comment by mmcc** [comment]
This seems reasonable to me. Should be a pretty straight forward change, but the one issue is that we just released 4.12 and subsequently locked down Master as 5.0. The implication that has is this could take a bit longer to be released. @heff - Thoughts?

**Comment by gkatsev** [comment]
Isn't this what `useractive` and `userinactive` give us?

**Comment by mmcc** [comment]
Hm good point, but wouldn't that also be affected by whether or not controls were showing at all? If controls are disabled altogether, that affects this. 



—

**Comment by heff** [comment]
The controls rely on [player CSS states](https://github.com/videojs/video.js/blob/bcf164fd996ac25819990e7058d584cd5b8a67b7/src/css/video-js.less#L172) for showing/hiding (mouseover/mouseout wasn't enough), so there's not a simple javascript process we could tie into to create an event like that. Instead you would want to use similar CSS for the ads.

```css
.video-js.vjs-user-inactive.vjs-playing .my-ads {
    // Adjust position    
}
```

Or you could listen for the useractive/userinactive events and check if the video is paused.

**Comment by mmcc** [comment]
I'm going to close this because it seems like @heff's solution is ideal. @shawnbuso does that make sense for you?

**Comment by shawnbuso** [comment]
@heff thanks for the tip. I'm really close to solving this but for some reason vjs-user-active is not working for me the same way that vjs-user-inactive is. Any idea why this may be? I noticed that you're actually not using that anywhere in your CSS, but it does get set on the parent div when the user is active. Here's ym CSS:

```
.ima-ad-container {
  top: -30px;
  position: absolute;
  display: block;
}

// Move non-linears up when controls are active
.video-js.vjs-user-active.vjs-playing .ima-ad-container {
  top: 0px;
  position: absolute;
  display: block;
}

.video-js.vjs-user-inactive.vjs-playing .ima-ad-container {
  top: 0px;
  position: absolute;
  display: block;
}
```

I'm seeing the ```.video-js.vjs-user-inactive.vjs-playing .ima-ad-container``` rules get applied when the user is inactive, but the ```.video-js.vjs-user-active.vjs-playing .ima-ad-container``` rules do *not* get applied when the user is active.

**Comment by shawnbuso** [comment]
Sorry, disregard my above comment. Apparently something was funky with my line breaks and the comment was overflowing to the next line. No idea what caused that, but changing the comment to the /* */ format fixed the issue.

**Comment by heff** [comment]
Cool, glad you got it figured out. The `//` comment syntax isn't actually available in in real CSS, it can only be used in `.less` files.
