### ISSUE TITLE
IE Flash fallback freeze

### ISSUE THREAD

**Issue by shovemedia** [videojs/video.js#1881]
Note: pertains to Flash fallback ONLY
(Perhaps related to https://github.com/videojs/video.js/issues/1213)
* Completely removed all videojs css fonts etc and issue persists.

If user clicks video playback area, the browser locks up for about 2 minutes(!)
and is usually unrecoverable. Clicking play controls works fine.

I'm able to see flash's stageclick events routing back to JS,
and the video does, in fact, pause, but after that, the browser is unresponsive.
Intercepted these events JS-side and swallowed them, no change.

If by chance, the browser happens to recover, it seems that the
toggle behavior now works fine! But watch that 1st click ... :(

**Comment by mmcc** [comment]
What browser / OS are you seeing this in? What's the source file? Version of Video.js? Mind putting together a [reduced test case](http://jsbin.com/axedog/latest/edit) for us?

**Comment by shovemedia** [comment]
I'll do my best with a test case.

so far: 
IE8, IE11 with techOrder": ["flash"]
latest video.js -> from github
source file?

**Comment by shovemedia** [comment]
This is some sort of incompatibility between videojs (or flash player) and our internal code that manages focus. I'm sure I'll see it again, but it's not videojs' fault per se. Closing and thanks!
