### ISSUE TITLE
Text Tracks, Techs, and You

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1883]
In 4.12.0, emulated text tracks were stored on the tech itself. This caused an issue where if you switched techs, the tracks UI elements would stop workings. videojs 4.12.1 fixes this by storing the emulated text tracks directly on the player itself. However, this doesn't fix the case where you are using a tech that uses native text tracks and then switch to a tech that uses emulated text tracks.

There are several things that we can do to help out with this:
* Do nothing. Tech switches are probably at a video boundary and not midway through a video, so, there probably isn't anything we need to do to make sure the text tracks survive through it.
* Copy over the text tracks. This is closer to what the native video element would work like.
* Have the UI elements re-register event handlers with the current text tracks, if necessary, on a video change.

That last item isn't necessarily mutually exclusive from the first two.

**Comment by d4d4k** [comment]
In 4.12.0 (and 4.12.1), default subtitle feature is not available. Subtitles always off when the player is loaded.

**Comment by gkatsev** [comment]
@d4d4k can you open that as another issue please?

**Comment by gkatsev** [comment]
I believe we've fixed this already by having the TextTrackList be shared across techs and then just clearing out and updating tracks during tech switches in 5.x. So, closing.
