### ISSUE TITLE
"default" attribute for text tracks not work

### ISSUE THREAD

**Issue by d4d4k** [videojs/video.js#1884]
In 4.12.0 (and 4.12.1), default text track feature is not available. Subtitles (or captions) always off when the player is loaded.

**Comment by heff** [comment]
@gkatsev can you confirm this?

**Comment by gkatsev** [comment]
Very possible because we disable tracks on loadstart. Probably want to check that `default` attribute isn't ste.

**Comment by heff** [comment]
@gkatsev can i assign this one to you then?

**Comment by gkatsev** [comment]
What would we want the expected behavior to be?
Should `default` tracks be given to the browser to display and all other tracks be disabled?

But yes, I can assign myself.

**Comment by heff** [comment]
If by 'given to the browser' you mean just don't disable them on loadstart, that sounds good to me.

**Comment by gkatsev** [comment]
Yep, that's it

**Comment by brahiansoto** [comment]
Subtitles default does not work
