### ISSUE TITLE
On iPad, video does not work without specifying 'controls' option

### ISSUE THREAD

**Issue by Jackipy** [videojs/video.js#1886]
I want to *not* show the control bar. However, when [controls](https://github.com/videojs/video.js/blob/stable/docs/guides/options.md#controls) is not specified, video does not work (no big play button, video does not play on tap).

To workaround the issue, others online suggested doing the following instead, which has its own quirks:
`.vjs-control-bar  { display:none!important; }`
* Video does play on tap, but loading spinner remains on screen while the video is playing
* While Video_A is playing, tapping on Video_B *does not* play the video AND Video_A is paused as a result

Tested on
- iOS 8.1.2
- videojs 4.11, 4.12.

**Comment by mmcc** [comment]
Unfortunately, this is how the video element works as well. Disabling controls also disables click events, so if you want to set something like this up you'll need to add click event handlers to the Videojs element.
