### ISSUE TITLE
On iPad, videojs cannot play multiple videos inline at the same time

### ISSUE THREAD

**Issue by Jackipy** [videojs/video.js#1887]
When there are multiple videos on the same page, tapping on one video will pause the other.

Repro Steps
1. Tap on video A. Video A plays.
2. Tap on video B.

Expected Results
* Video B plays

Actual Results
* Video A is paused
* Video B plays

Tested on:
* iOS 8.1.2
* videojs 4.11, 4.12

**Comment by gkatsev** [comment]
This is an iOS feature rather than a bug. Apple doesn't want you to be playing multiple videos as it could drain the battery extra fast. Nothing that videojs can do.

**Comment by jackyyip** [comment]
Makes sense. Thanks for the quick reply.

**Comment by jackyyip** [comment]
Makes sense. Thanks for the quick reply.

**Comment by gkatsev** [comment]
Yep, no worries.
