### ISSUE TITLE
Add crossorigin documentation and explanation and update examples

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1888]
At least on iOS, we cannot use native text tracks with cross-domain tracks without applying the `crossorigin="anonymous"` property to the video element. We should apply that where appropriate.
Different browser react differently to that attribute, so, we definitely don't want to apply it by default. We want to apply it to a targeted range of browsers.

The takeaway from #2269:
* [x] We need to document the crossorigin property that when tracks are crossorigin and require CORS the video file itself will also require CORS (at least, as far as we understand it)
* [x] Document that users will need to be in charge of adding or removing the crossorigin attribute on the video element
* [x] We should print a warning in the console when we detect that captions wouldn't be loaded because of CORS
* [x] Update the sandbox example and the website to correctly use the crossorigin attribute

**Comment by gkatsev** [comment]
More info:  This is because native text tracks with VTT files on other origins require crossorigin="anonymous" on the video element to work but in some browsers if the crossorigin attribute is set but the video (mp4 in chrome, for example) doesn't have CORS headers set up as well then the video will fail.

**Comment by hparra** [comment]
:+1: I get the following error in Chrome Version 44.0.2403.157 (64-bit). No differences with crossorigin="anonymous". Problem is known CORS issue, but error unclear. Is the errorHandler not forwarding the exact error message?

```
VIDEOJS: ERROR: Error
    at errorHandler (http://localhost:8000/node_modules/video.js/dist/video-js/video.dev.js:1606:13)
    at XMLHttpRequest.request.onreadystatechange (http://localhost:8000/node_modules/video.js/dist/video-js/video.dev.js:1659:11)_logType @ video.dev.js:1457vjs.log.error @ video.dev.js:1481(anonymous function) @ video.dev.js:8604ret @ video.dev.js:885errorHandler @ video.dev.js:1609request.onreadystatechange @ video.dev.js:1659
```

**Comment by ndubbaka** [comment]
I get this error on video "The video could not be loaded, either because the server or network failed or because the format is not supported."
![image](https://cloud.githubusercontent.com/assets/545961/10927162/74342288-826b-11e5-8b16-dcdf47e67e4e.png)
