### ISSUE TITLE
Multiple videos don't start at the same time

### ISSUE THREAD

**Issue by zda** [videojs/video.js#1889]
I am trying to create four video players, each using the same source file, and play them all at the same time.

Right now, I can wait until all four `.ready()` callbacks have returned, and theoretically at that point all four videos should be ready to play. But when I loop through them and call `player.play()`, they don't start at the same time (even though there's only 1ms difference between when the first and last `.play()` are called).

On the other hand, if I wait for them to start, and then call `player.currentTime(t)` on all of them, they jump to the same time and remain in sync thereafter. But it seems like you should be able to do this without a hack like that.

**Comment by mmcc** [comment]
I'm not seeing the [same issue](http://jsbin.com/juwohibayu/1). If all the videos are buffered, playback does start within ms of each other, or at least to the point that I can see no discernible sync issues. Keep in mind that `.ready()` is returned when the *player* is ready, but doesn't necessarily mean that all of your videos have buffered to the same point.

To be terribly honest, though, if you really want to guarantee sync between multiple players, I think force syncing them via `currentTime` at a reasonable interval is probably your best bet. At the very least, you should probably not only wait for the `.ready()` event, but also check for things such as [`bufferedPercent()`](https://github.com/videojs/video.js/blob/master/docs/api/vjs.Player.md#bufferedpercent).

**Comment by mmcc** [comment]
Just out of curiosity, what are you doing that requires syncing multiple videos? Sounds cool, I'd love to see a demo.

**Comment by zda** [comment]
It was going to be this but with video on the four outer devices -- but our testing indicated video on another part of the page converted better, so I don't have a live demo right now.
![screen shot 2015-03-28 at 8 44 39 pm](https://cloud.githubusercontent.com/assets/4313606/6884030/7415034a-d58b-11e4-8290-079c0200f264.png)
