### ISSUE TITLE
Videos are darker in IE and Firefox

### ISSUE THREAD

**Issue by physikinstrumente** [videojs/video.js#1893]
Hello,
my problem is that much of my videos are white with products in it. And the page around it are also white. In chrome or safari it looks pretty nice but in IE and firefox the videos are a little bit darker and so you see the edge of the video.
Have you any idea?
best regards
Robert

**Comment by dmlap** [comment]
It's possible that you're seeing a difference between how the Flash tech renders video and the individual browsers' implementations of the HTML5 video element. You can check whether a particular browser is using Flash by right-clicking on the video during playback and looking at the context menu. If Flash is being used, you'll see something about VideoJS SWF in that menu.

There's probably not too much we can do about the issue, though. Blitting pixels onto the screen is normally handled by the operating system, browser, or playback tech and there aren't many knobs that can be turned in Javascript to affect it.
