### ISSUE TITLE
Add npm prepublish script

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1894]
We need to add an npm prepublish script that makes sure that the dist/ folder only has the bare essentials and not zip files from previous releases.

**Comment by mmcc** [comment]
Cool. I'll take a pass at pulling in recent Gruntfile changes to #1835, but we should get that merged in before doing this.

**Comment by heff** [comment]
I think we could just add the [grunt clean](https://github.com/videojs/video.js/blob/master/Gruntfile.js#L34) task to the [release process](https://github.com/videojs/video.js/blob/master/contrib.json#L186).

**Comment by gkatsev** [comment]
Yep, whichever way works best :)

**Comment by mmcc** [comment]
Agreed, I have no opinion whatsoever on how we do it, just saying let's please do this after the merge :)

**Comment by mmcc** [comment]
@gkatsev does [this](https://github.com/mmcc/video.js/commit/d6ef18d18ce1873a07744ebbc51ab2894e1781fa) look good to you?

**Comment by gkatsev** [comment]
That looks like it'll work.

**Comment by mmcc** [comment]
Closed via 972c8bd
