### ISSUE TITLE
Unable to `npm install` with git dependency vtt.js

### ISSUE THREAD

**Issue by silverwind** [videojs/video.js#1895]
I'm unable to install video.js's dependencies with the latest update that pulls in the git dependency of `vtt.js`. The issue seems to be something about git itself, which is at the latest version provided by Cygwin. Same installation works fine on OS X. Here's the error:

````
npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\silverwind\AppData\Roaming\npm-cache\_git-remotes\https-gith
ub-com-gkatsev-vtt-js-git-9a867bb9 C:\Users\SILVER~1\AppData\Local\Temp\npm-3612-ea415d7b\git-cache-aa2cb630bc7b\3ba274b332de18
7f7269f277733021be3dd1f5bd
````

And my versions:
````
$ npm -v
2.5.1
$ git --version
git version 2.1.4
````

Would it maybe be possible to publish `vtt.js` to npm to work around this, maybe under a dist-tag?

**Comment by heff** [comment]
I don't totally understand the error that's happening there, but why might publishing to npm fix this? @gkatsev any insight?

**Comment by silverwind** [comment]
@heff because npm dependencies are just tarball downloads, no git involved.

**Comment by heff** [comment]
Ah, that makes sense. I think we might just be waiting on mozilla/vtt.js#338 to be merged in before we can point directly at that project. @gkatsev will have a better idea of where that's at, and if it's worth publishing his own branch.

**Comment by silverwind** [comment]
You could also depend on a tarball link from GitHub like this:

````js
  "dependencies": {
    "videojs-swf": "4.5.3",
    "vtt.js": "https://github.com/gkatsev/vtt.js/tarball/3ba274b332de187f7269f277733021be3dd1f5bd"
  },
````

**Comment by mmcc** [comment]
Closing this based on the result of #1911

**Comment by gkatsev** [comment]
Fixed by https://github.com/videojs/video.js/pull/2905

**Comment by silverwind** [comment]
:+1:
