### ISSUE TITLE
Tracks test fails in Firefox

### ISSUE THREAD

**Issue by heff** [videojs/video.js#1898]
[This test](https://github.com/videojs/video.js/blob/550d44332b6ec7df93d8d509c553cdcf348e9c3f/test/unit/tracks/tracks.js#L55) fails in Firefox because we don't use native captions there even though they're supported. The test should be combined with [this firefox test](https://github.com/videojs/video.js/blob/550d44332b6ec7df93d8d509c553cdcf348e9c3f/test/unit/tracks/tracks.js#L273).

**Comment by gkatsev** [comment]
Closing because we're not going to be enabling native tracks in firefox because of issues described in #3261 and #1862.
