### ISSUE TITLE
why donot flash moude nonsupport ?start=12322 With other play support！

### ISSUE THREAD

**Issue by githubzhaoqian** [videojs/video.js#1902]
why donot flash moude nonsupport ?start=12322 With other play support！
sorry! my en is very poor!

**Comment by heff** [comment]
See the discussion here: https://github.com/videojs/video-js-swf/issues/13

**Comment by githubzhaoqian** [comment]
@heff   thank you! 谢谢  ！
I look at the article , is what I need. 
Videojs‘s video have a play a click to load of bug  in IE10.
