### ISSUE TITLE
Spam into log when error occured with text tracks

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#1903]
Hi!
Somewhere I saw an opened(or closed) issue with this error. At least for FF 35.0 and VJS 4.12.1 I see more than 6000 rows in log that cause big lags in browser.

I cannot understand why... I see in logs

> VIDEOJS: ERROR: b { name="ParsingError", code=1, message="Malformed timestamp: 00:59:21,160 --> 00:59:22,191", more...}

Chapters worked fine in the previous VJS 4.11 release.

PS! I'm use video.js with included vtt script.
If need demo please leave comment.

**Comment by gkatsev** [comment]
This is probably comes from the fact that our new vtt parsing is much more strict and spec compliant. According to the spec, the separator between seconds and second-fractions is a [U+002E FULL STOP character (.) [step 5]](http://dev.w3.org/html5/webvtt/#dfn-webvtt-timestamp)

**Comment by Globulopolis** [comment]
Thank you! Found that in subtitles separator isn't spec compliant.
But how about spam into log? Or it's not a VJS spam?

**Comment by gkatsev** [comment]
We print out the parsing errors from vttjs into the log.
We definitely do want to print out the errors, but if it's happening too much, we might want to collapse multiple print outs into one, or something.
Do you have the full log?

**Comment by Globulopolis** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/740757/6419880/287f72fa-bed2-11e4-8be6-6b530ae3573f.jpg)
Can't provide full log, but you can see screenshot.

Emm... Unfortunately I'm not JS guru. But I think we need something like "type error", so we can detect which type of error raised, and if more than n+1 errors happened - suppress them. At least for text tracks, I think, because for each track(can be several) logger throw error.

**Comment by gkatsev** [comment]
The screenshot is good. Yeah, we're currently print each error into the console.
What about print all the errors at the same time after the parsing as happened?

**Comment by Globulopolis** [comment]
@gkatsev sounds good as temporary solution. But what happens when VJS will throw all collected errors?

**Comment by gkatsev** [comment]
I think we can use the dev tool's `groupBy` functionality so everything gets grouped together.

**Comment by gkatsev** [comment]
Fixed by https://github.com/videojs/video.js/pull/3259
