### ISSUE TITLE
docs say playback rate is a boolean?

### ISSUE THREAD

**Issue by parke** [videojs/video.js#1907]
From the docs for playbackRate:

"PARAMETERS: rate Boolean New playback rate to set."

source: https://github.com/videojs/video.js/blob/stable/docs/api/vjs.Player.md#playbackrate-rate-

I believe rate should be a Number, not a Boolean.

**Comment by gkatsev** [comment]
Yep, the docs are wrong :)

**Comment by mmcc** [comment]
Wasn't there a recent PR to fix this?



—

**Comment by gkatsev** [comment]
Yes: https://github.com/videojs/video.js/pull/1876

**Comment by heff** [comment]
The PR was against master, so unfortunately it wouldn't go into the stable docs until the next minor release, which wouldn't be until 5.0 now. Not quite sure the best way to handle this.

**Comment by gkatsev** [comment]
Don't most people look at the docs in master?
If it's a huge concern, we probably should just cherry-pick the commit/PR.

**Comment by parke** [comment]
I do not know where most people look.

This page:  http://www.videojs.com/

Links to here:  https://github.com/videojs/video.js/blob/stable/docs/index.md

Which eventually leads to here:  https://github.com/videojs/video.js/blob/stable/docs/api/vjs.Player.md

**Comment by gkatsev** [comment]
In that case we should cherry-pick the commit/PR. Git will figure it out.
