### ISSUE TITLE
Any styling available in new VTT implementation?

### ISSUE THREAD

**Issue by ksheurs** [videojs/video.js#1912]
I am noticing in the new VTT implementation I am seeing odd line breaks, like so: http://cl.ly/image/0K1U1O1r160m. Seems to break on random characters or trailing periods / commas.

Is there anything I can do via CSS to widen the VTT container or is there a better way to address this?

**Comment by mmcc** [comment]
What browser are you seeing that in? If you'd like to style native captions, you can do so via the [`::cue` pseudo-element](http://dev.w3.org/html5/webvtt/#css-extensions). Keep in mind ymmv, though, browser support isn't totally coherent when it comes to styling cues.

Just checked, looks like [vtt.js has implemented the spec](https://github.com/mozilla/vtt.js/tree/master#spec-compliance), so it should be the same either way.

**Comment by ksheurs** [comment]
@mmcc that is in Chrome OSX 40.0.2214.115.

so it looks like `::cue` only supports color, opacity, visibility, text-decoration, etc. not sure i'll be able to adjust any widths or anything else that would prevent line breaking. any other ideas?
