### ISSUE TITLE
Subtitles default does not work

### ISSUE THREAD

**Issue by elfaxvaxec** [videojs/video.js#1914]
I'm very sorry, I have not worked default subtitle.

```
 <track kind="captions" src="demo.captions.vtt" srclang="en" label="English" default></track><!-- Tracks need an ending tag thanks to IE9 -->
    <track kind="subtitles" src="demo.captions.vtt" srclang="en" label="English" default></track><!-- Tracks need an ending tag thanks to IE9 -->
```

**Comment by mmcc** [comment]
What version of Video.js are you using? As of 4.12.3 this should be fixed (#1884), but ping this issue if not and we can re-open. If you are still seeing this in 4.12.3, the following would be really helpful for debugging:

- Video.js version
- Browser / OS / versions of each
- [reduced test case](http://jsbin.com/axedog/latest)

**Comment by elfaxvaxec** [comment]
I downloaded the latest version 

1) 4.12.3, video.js-4.12.3.zip\video.js-4.12.3\dist\video-js.
2) Tested in browsers: Mozilla Firefox version 36.0, Google Chrome version 40.0.2214.111 m
3) Tested reduced test case

Can make and upload a ready example with subtitles by default? Maybe I'm doing something wrong ? And with a ready example of you will be clear on which side , and where the error occurred.

**Comment by mmcc** [comment]
Mind putting together a [reduced test case](http://jsbin.com/axedog/latest/edit)?

**Comment by elfaxvaxec** [comment]
You specified works, but there is no default subtitle. Please help me with this. All I need is the default subtitles. How can I help you?

**Comment by elfaxvaxec** [comment]
You can write a small function which will simply mimic the subtitle selection, it may be the first subtitle in the list, this function can I put in the code page and will achieve the desired result for me.

**Comment by brookslyrette** [comment]
The provided demo.html in the 4.12.3 build does not show captions or subtitles in Chrome 41.0.2272.76 Mac OS/X. 

Here is a reduced test case:
http://jsbin.com/yuxosozohu

**Comment by gkatsev** [comment]
I think this is what is currently preventing default subs and captions from working: https://github.com/videojs/video.js/blob/01ea3d1ae3cda1754148967d0b170582ceb2dcc7/src/js/media/html5.js#L436-L446

**Comment by anonym24** [comment]
So is it not fixed yet? It shows subtitles at once with "default" attribute in Chromium-browsers, but not in Firefox & IE11. I tried with 4.12.15 & 5.1.0.
But on https://openload.co/f/SzqrdBEBziQ/ subtitles are displayed at once in any browsers (openload uses some 4 version of video.js).
Also it's normal with Edge and vj 4.12.15, but not with 5.*

**Comment by anonym24** [comment]
It works with some older versions (for e.g. 4.11.1)

**Comment by gkatsev** [comment]
Fixed by https://github.com/videojs/video.js/pull/3248
