### ISSUE TITLE
Captions on iPad 

### ISSUE THREAD

**Issue by zang** [videojs/video.js#1917]
The captions and subtitles of the video featured on videojs.com are not showing on iPad. Is that a bug or expected behaviour? 

Thanks,
Lucy

**Comment by Spaceninja7u** [comment]
There was recently a minor format change, I believe. This is how I set them up using the javascript setup method, it works for me in iPad:
```javascript
var playerSetup = {
    'techOrder': ['html5'],
    'controls': true,
    'tracks': [
    {
        'kind': 'subtitles',
        'label': 'English',
        'language': 'EN',
        'srclang': 'English',
        'src': 'absolute_url_to_a_webvtt_file'
    }
    ],
/* src, etc omitted */
};

var player = videojs('id_of_video_container_element', playerSetup, function() {});

```

**Comment by gkatsev** [comment]
Similar to #1904, stems from #1888.
Going to close this to track it in those issues instead. Thanks.
