### ISSUE TITLE
MPEG DASH player.load() fails in Chrome and Firefox

### ISSUE THREAD

**Issue by glennolsen** [videojs/video.js#1918]
Using `<video>` tag with autoplay, source loads and plays properly when page loads. 

On button click I switch sources:

```javascript
myButton.addEventListener('click', function() {
player.src('http://54.88.249.216:1935/avod/_definst_/mp4:amazons3/Panels_Standard.mp4/manifest.mpd');
player.load();
});
```

Fails with error:

`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported.`

URI is exactly the same on page load, but a different media file. 

In Firefox, videojs reports the initial attempt (on page load) as well as the button click to load the file as an error.

Using Wowza on the backend with no errors in the server logs. No issues with my use of Wowza and this media for any other player protocols (RTMP or HLS).

I am using videojs with videojs-tech-dashjs and dash.all

**Comment by glennolsen** [comment]
First sentence should read:

Using video tag

got stripped.

**Comment by mmcc** [comment]
This *might* be better suited for [https://github.com/Dash-Industry-Forum/dash.js), but let's try to debug this here first. Mind putting together a reduced test case on [JSBin](http://jsbin.com/axedog/latest/edit) for us to check out?

**Comment by glennolsen** [comment]
Matt,

Got pulled in another direction. Will be back to this next week and will set up a small test case. Thanks...

**Comment by mmcc** [comment]
No worries at all, just ping the thread when you get a chance.

**Comment by chemoish** [comment]
:+1:

**Comment by chemoish** [comment]
Similar issue, when calling `player.src({src: '...', type: 'application/dash+xml'})` it loads the DASH manifest and is ready to be played.

Calling `player.load()` results in a broken player interface.

![screen shot 2015-08-06 at 3 23 36 pm](https://cloud.githubusercontent.com/assets/549319/9124817/56437d4e-3c4f-11e5-8208-b1be35e80282.png)

![screen shot 2015-08-06 at 3 25 21 pm](https://cloud.githubusercontent.com/assets/549319/9124823/65421c56-3c4f-11e5-8398-cbe329740c5b.png)

**Comment by jemoreno** [comment]
I am experiencing the same issue.  The video played perfectly in firefox using video.js 4.12 but when I decided to go to 5.0 it stopped working, however it plays perfectly in chrome.

**Comment by sprice** [comment]
[Here's a test case](https://gist.github.com/sprice/2167aab3f0f2a63083a0) using
* video.js 5.0.0
* videojs-contrib-dash 2.0.0

Tested on OS X
* works in Chrome 46
* works in Firefox 43 (nightly)
* audio only in Safari 9 (I wonder if this is a problem with the media)

**Comment by gkatsev** [comment]
@sprice I see that you're just setting the src with a string, have you tried setting the source with an object containing `src` and `type` properties? Also, do we have a corresponding issue on the dash repo?

**Comment by sprice** [comment]
Weird. I think I got my issues mixed up. My test case above is using `videojs-contrib-dash`, not `videojs-tech-dashjs`.

Regardless, I updated my test case [here](https://gist.github.com/sprice/ea6018efe64127006315) using `videojs-contrib-dash` and the same sort of error is occurring. The `.mpd` loaded in the click handler will work fine if it's the one loaded initially. In Chrome I found if I triggered the click enough times it ended up working.

**Comment by sprice** [comment]
Replacing `player.load()` with `player.play()` in the click handler works for me. I still get the Media Not Supported error but it starts playing fine.

**Comment by gkatsev** [comment]
I think it could be that `load`/`play` are getting called too early before contrib-dash is actually ready to go. @imbcmdth @forbesjo thoughts?

**Comment by hyurtseven81** [comment]
You can use shaka player as videjs tech. You can use my fork of metacdn repository. It is using on production and there is no problem

https://github.com/hyurtseven81/videojs-shaka-player

**Comment by baqarrivi** [comment]
I am having a same error in firefox .

Videojs version 5.8.8
dash version 2.0.0
Contrib dash 2.0.0

Working fine everywhere but its not working in Firefox 45.0.2. sometimes it works sometime its not .

http://bestsongs.pk/videos/bol-do-na-zara-azhar-2016/

**Comment by gkatsev** [comment]
@forbesjo @nickygerritsen @chemoish know if this is still an issue with the latest contrib-dash, dashjs, and videojs?

**Comment by chemoish** [comment]
I don't think I'm even the latest video.js, but maybe. Works for me in IE
11, Edge, Chrome, Firefox. Using DRM. Haven't integrated anything with
Safari as I will be leveraging Fairplay and not Dash when I get back
:airplane:.

**Comment by gkatsev** [comment]
Alright, going to close this as fixed then. We can always re-open if it's still an issue.
