### ISSUE TITLE
full-screen button doesn't work, i am using iframe

### ISSUE THREAD

**Issue by tuyhin** [videojs/video.js#1921]

**Comment by hacfi** [comment]
@tuyhin We need a little more information (use case/code, browser) than that and ideally a jsfiddle which demonstrates the issue.

**Comment by tuyhin** [comment]
this is my code:<head>
<link href="//vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.11/video.js"></script>
<script src="/Public/player/youtube.js"></script></head><body>  <video id="vid1"  class="video-js vjs-default-skin"  controls preload="auto" width="100%" height="600">
  </video>
<script>var videourl = window.parent.frames.Player.Url;videojs(document.getElementById('vid1'), { "techOrder": ["youtube"] }).ready(function(){
     var myPlayer = this;
     myPlayer.src(videourl);
     myPlayer.play();});
</script> 

     On Tuesday, March 3, 2015 10:55 AM, hacfi <notifications@github.com> wrote:
   

 @tuyhin We need a little more information (use case/code, browser) than that and ideally a jsfiddle which demonstrates the issue.—

**Comment by hacfi** [comment]
And which browser are you using? Which version of video.js isn’t working - HTML5 or Flash? In your code it says youtube.js..if you’re using video.js with youtube this is the wrong place to ask your question as this is not included in the core of video.js but a plugin.

**Comment by hacfi** [comment]
You should also try the latest video.js version:

```html
<link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.12/video.js"></script>
```

**Comment by mmcc** [comment]
You're **not** using iFrames in this example? 

Unless I'm reading this wrong:

```javascript
// This seems to grab the Player frame from the parent of wherever this script is running
var videourl = window.parent.frames.Player.Url;

videojs(document.getElementById('vid1'), { "techOrder": ["youtube"] }).ready(function(){
     var myPlayer = this;
     // Then this sets that variable retrieved from another frame on the page
     myPlayer.src(videourl);
     myPlayer.play();
});
```
I might be reading this wrong, but that *looks* like iFrames are involved. To reiterate @hacfi, [working (or non working) examples](http://jsbin.com/axedog/latest/edit) make debugging a lot easier.

**Comment by hacfi** [comment]
@tuyhin You should post your issue over at https://github.com/eXon/videojs-youtube
I don’t even know if that plugin supports fullscreen.

**Comment by tuyhin** [comment]
thank you help! now i am useing iframe.all browsers are working good but IE11 no working. 

     On Tuesday, March 3, 2015 11:23 AM, hacfi <notifications@github.com> wrote:
   

 @tuyhin You should post your issue over at https://github.com/eXon/videojs-youtube
I don’t even know if that plugin supports fullscreen.—

**Comment by mmcc** [comment]
Ok, the issue title originally said you were *not* using an iFrame so that was a little confusing.

Are you setting the `allowfullscreen` attribute on your iFrames?
