### ISSUE TITLE
Export vjs.formatTime

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#1922]
My plugins use the `vjs.formatTime` method to manipulate display/remaining/duration time. Since it's not exposed in a public API I'm currently copying it into each plugin codebase which is not ideal at all. Is it possible to export this method?

Another request would be to add milliseconds support to `vjs.formatTime`. Right now I have something like [this](https://github.com/collab-project/videojs-wavesurfer/blob/master/videojs.wavesurfer.js#L503), a sligthly modified version. Interested in such a PR?

**Comment by carpasse** [comment]
Hi @thijstriemstra 
There is currently a discussion about exposing utility functions in https://github.com/videojs/video.js/issues/1232
I would add your request there.

**Comment by mmcc** [comment]
I'm going to close this since we've got the conversation moved over to #1232. Thanks for moving this conversation to the right place, @carpasse.
