### ISSUE TITLE
Black line on right side

### ISSUE THREAD

**Issue by shaandsingh** [videojs/video.js#1923]
I added video.js to my site using a self-hosted copy that I skinned. Here's the link: http://bluecocoa.com/posts/spaceship-canopy/. There's a thin black line appearing on the right side of the video when viewing in Safari. Resizing the browser sometimes makes it go away, but it often doesn't. Anyone have an idea about why this issue could be happening?

I didn't add any margins or borders (to my knowledge), so I think this is a bug.

![screenshot of issue]
(https://cloud.githubusercontent.com/assets/11204512/6478549/73907fee-c203-11e4-8f97-ffdbf40e5d5e.png)

**Comment by mmcc** [comment]
I can see a black line at the top of the video in FF as well. Inspecting the element, it looks like you're using one of the responsive CSS "hacks" (not really hacky, just for lack of a better term) that someone has posted in the comments and the aspect ratio you picked doesn't perfectly line up with that of the video.

**Comment by brandoncc** [comment]
I am experiencing this but the black line is on the left and right, left, or top and bottom depending on the width of the browser. I'm using the `vjs-16-9` class and `fluid: true`, no other css hacks. Is there a known solution?

**Comment by kp77** [comment]
I also experience a 1px black line on the right in certain screen resolutions when using `fluid: true`. No css hacks.

**Comment by brandoncc** [comment]
@kp77 I found the solution for our use case. Our poster has a white background, so I was able to change the background color of `.vjs-poster` to `white`, which resolved the issue. Hopefully, you are able to do something similar. Alternatively, maybe you can set it to `transparent`.,

```css
.vjs-your-skin .vjs-poster {
  background-color: white;
}
```

**Comment by kp77** [comment]
@brandoncc Thanks for the hint, it didn't make the black line disappear though. It seems to be unrelated to the background color of `.vjs-poster` (whatever color I set, it's always black). Strangest thing is that this 1px black line on the right is not even always displayed using the same resolution. Sometimes it's there, sometimes not. Anyway, thanks again.

**Comment by odairjtanes** [comment]
+1

**Comment by damjan25** [comment]
Is there any solution to this ?

**Comment by mister-ben** [comment]
Try `object-fit: cover` on `.vjs-tech`.

**Comment by chrismwendt** [comment]
This worked for me:

```css
.vjs-tech {
  width: 101% !important;
  height: 101% !important;
}
```

**Comment by eliamartani** [comment]
For those of you that may found similar issue within the poster, just change its sizing and maybe it helps:

```css
.vjs-poster {
  background-size: cover;
}
```

**Comment by pxim** [comment]
![image](https://user-images.githubusercontent.com/5111701/98211446-03cbe800-1f7d-11eb-84ac-639cd4658ca9.png)
`<div data-vjs-player style={{backgroundColor: 'transparent',}}>`

Before add 
![image](https://user-images.githubusercontent.com/5111701/98211542-28c05b00-1f7d-11eb-941f-7129c4072c83.png)

After add
![image](https://user-images.githubusercontent.com/5111701/98211585-370e7700-1f7d-11eb-9955-e5a97b0e9758.png)
