### ISSUE TITLE
Problems about video-js

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#1925]
Hi. I have a site in joomla in wich I have installed a video gallery called Apptha contus hd video share. This gallery have a problem, it's not html5 compatible. So I've added a button available only for mobile users under the player that open a spoiler where is sit Video-Js. Video-Js need to play the same video and the same thumb of the player above. So I tried to put this code in the spoler:

```
<video id="example_video_1" class="video-js vjs-default-skin"
  controls preload="auto" width="640" height="264"
  poster="<?php echo $video_thumb; ?>"
  data-setup='{"example_option":true}'>
 <source src="<?php echo $video_url; ?>" type='video/mp4' />
 <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video> 
```

The problem is that in this way I can get the same thumb of the old player but I cannot get the video playing. It says "the video could not be loaded, either because the server or network failed or because the format is not supported.". I think that somehow the player doesn't understand the script `<?php echo $video_url; ?> `. So what can I do? Please help...

And another question. There is a way for disable the download button, when somehow right-click on the player? Thank you.

**Comment by mmcc** [comment]
Does your poster work? If you inspect the element, what's the URL that you see for the source attribute? What is that source? Is there an example we can see?  

There's no way to disable the download button if you're using HTML5 video.
