### ISSUE TITLE
Volume local storage should be completely removed

### ISSUE THREAD

**Issue by pennello** [videojs/video.js#1929]
Volume local storage was buggy and ended up getting partially removed from the code base. Some brave soul needs to finish the job. (issue updated by @mmcc)

## Original Issue

I had noticed before that the volume state was not respected across page loads, but when looking into another matter, I did notice that the state actually was kept in local storage under the key `volume`.  Indeed, it's updated in real time as you use the volume slider UI.  So it would seem that the state is actually _meant_ to be respected, but for some reason isn't.
Reproducible in at least Chrome on a Mac on the demo page.

**Comment by thijstriemstra** [comment]
There's a separate plugin for this called `videojs-persistvolume`, so perhaps it's not meant to be respected, not sure :)

**Comment by pennello** [comment]
Ah, interesting, you're right!
It looks like the Onion plugin, though, stores the volume information under a separate local storage key, and even has a feature for namespacing the storage (something I thought was missing when I observed the bare `volume` key).
As it is, it seems like the volume storage implementation in core video.js is either incomplete or buggy.  Perhaps it should be removed?

**Comment by heff** [comment]
Yeah, the volume local storage was buggy and got half removed. It should be fully removed if you want to submit a PR for that.

**Comment by pennello** [comment]
Cool, thanks for the clarification.

**Comment by gkatsev** [comment]
I'm pretty sure it's gone now, at least in 5.0.
