### ISSUE TITLE
requestFullScreen works in Flash mode but not in HTML5 mode - v4.12

### ISSUE THREAD

**Issue by dmwhite3** [videojs/video.js#1933]
Hi, I'm hoping you can help,

I'm building a simple video player app in ASP.net that has the simple requirements to work in Flash mode on HTML4 browsers and self upgrade to HTML5 in the browser allows.  It also has basic requirements to jump to fullscreen mode on play/resume and to exit fulscreen when ended.

The above works perfectly when I force a HTML5 browser (Chrome, IE10/11) into flash mode using the techOrder['flash', 'HTML5'] or when I access on a non-HTML5 browser (IE6/8), but when I use a HTML5 browser in HTML5 mode the video plays perfectly but the requestFullScreen method has no effect at all - the javascript executes without error but the fullscreen behaviour is ignored.

A basic skeleton of the HTML my app renders is as follows:

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
        <script src="Scripts/modernizr.custom.25709.js"></script>
        <link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
        <script src="//vjs.zencdn.net/4.12/video.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>
        var player;
        $(document).ready(function () {
            player = videojs('my_video_1', {
                techOrder: ['html5', 'flash'],
                autoplay: false,
                sources: [{
                    type: "video/mp4",
                    src: "test.mp4"
                }]
            });
            player.on('loadedmetadata', function (e) {
                LogVideoInitiatialisingMIEvent();
            });
            player.on('firstplay', function (e) {
                LogVideoPlayMIEvent();
            });
            player.on('play', function (e) {
                GoFullScreen();
            });
            player.on('pause', function (e) {
                LogVideoPauseMIEvent();
            });
            player.on('ended', function (e) {
                LogVideoFinishedMIEvent();
                LeaveFullScreen();
            });
        });
        /**************************************************************************************
        function: Logs the Page Initialisation MI Event
        **************************************************************************************/
        function LogVideoInitiatialisingMIEvent() {
            $('#output').append($('<div>Page Initialisation Event</div>'));
        }
        /**************************************************************************************
        function: Logs the Play MI Event
        **************************************************************************************/
        function LogVideoPlayMIEvent() {
            $('#output').append($('<div>Play Event</div>'));
        }
        /**************************************************************************************
        function: Logs the Pause MI Event
        **************************************************************************************/
        function LogVideoPauseMIEvent() {
            $('#output').append($('<div>Pause Event</div>'));
        }
        /**************************************************************************************
        function: Logs the Finished MI Event
        **************************************************************************************/
        function LogVideoFinishedMIEvent() {
            $('#output').append($('<div>Finished Event</div>'));
        }
        /**************************************************************************************
        function: Jump to full screen if we aren't already
        **************************************************************************************/
        function GoFullScreen() {
            player.requestFullscreen();
        }
        /**************************************************************************************
        function: Exit full screen if we are currently viewing in fullscreen
        **************************************************************************************/
        function LeaveFullScreen() {
            player.exitFullscreen();
        }
        </script>
    </head>
    <body>
        <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="400" height="300"></video>
        <div id="output"></div>
    </body>
    </html>

Any help you can provide would be much appreciated.

Thanks
David

**Comment by dmwhite3** [comment]
2nd attempt at posting the code as follows ( it didn't render and went to the page source):


    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
        <script src="Scripts/modernizr.custom.25709.js"></script>
        <link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
        <script src="//vjs.zencdn.net/4.12/video.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>
        var player;
        $(document).ready(function () {
            player = videojs('my_video_1', {
                techOrder: ['html5', 'flash'],
                autoplay: false,
                sources: [{
                    type: "video/mp4",
                    src: "test.mp4"
                }]
            });
            player.on('loadedmetadata', function (e) {
                LogVideoInitiatialisingMIEvent();
            });
            player.on('firstplay', function (e) {
                LogVideoPlayMIEvent();
            });
            player.on('play', function (e) {
                GoFullScreen();
            });
            player.on('pause', function (e) {
                LogVideoPauseMIEvent();
            });
            player.on('ended', function (e) {
                LogVideoFinishedMIEvent();
                LeaveFullScreen();
            });
        });
        /**************************************************************************************
        function: Logs the Page Initialisation MI Event
        **************************************************************************************/
        function LogVideoInitiatialisingMIEvent() {
            $('#output').append($('<div>Page Initialisation Event</div>'));
        }
        /**************************************************************************************
        function: Logs the Play MI Event
        **************************************************************************************/
        function LogVideoPlayMIEvent() {
            $('#output').append($('<div>Play Event</div>'));
        }
        /**************************************************************************************
        function: Logs the Pause MI Event
        **************************************************************************************/
        function LogVideoPauseMIEvent() {
            $('#output').append($('<div>Pause Event</div>'));
        }
        /**************************************************************************************
        function: Logs the Finished MI Event
        **************************************************************************************/
        function LogVideoFinishedMIEvent() {
            $('#output').append($('<div>Finished Event</div>'));
        }
        /**************************************************************************************
        function: Jump to full screen if we aren't already
        **************************************************************************************/
        function GoFullScreen() {
            player.requestFullscreen();
        }
        /**************************************************************************************
        function: Exit full screen if we are currently viewing in fullscreen
        **************************************************************************************/
        function LeaveFullScreen() {
            player.exitFullscreen();
        }
        </script>
    </head>
    <body>
        <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="400" height="300"></video>
        <div id="output"></div>
    </body>
    </html>

**Comment by mmcc** [comment]
This is because `requestFullScreen` can only be requested via a user-generated event handler (such as a click or a key-press) for security reasons. The way around this would be to listen for a click event on the play buttons or something along those lines, but this isn't going to work simply listening for the `play` event.

**Comment by dmwhite3** [comment]
Do you have any code examples of how to attach the event handler to the various play buttons.  I've had a play around trying to add these to the vjs-play-control and vjs-big-play-button but keep getting various flavours of "undifined" javascript errors.

**Comment by mmcc** [comment]
I'm going to give you a snippet that will do what you're asking, but for the sake of your users, I'm going to **strongly** suggest you not do this. As a user, if I clicked a play button in your player and got unexpectedly booted to full screen, I would be really, really annoyed. Keep in mind there's a reason why browsers require a user action event to request full screen.

```javascript
player.bigPlayButton.on('click', function(e) { 
  v.requestFullScreen();
});
```
That being said, I once again implore you to use this with extreme prudence.

**Comment by dmwhite3** [comment]
Thanks for the info.  I take your point about user expectations and usability, but be reassured this is a well thought out requirement.  This is not for an internet application for "Joe Public", its for an internal colleague facing application to host training material and the jumping to full screen is just to save the colleague extra clicks to get the video into the preferred delivery mode. Sounds of little benefit but just a step to try and ensure consistency of delivery across a large internal user base.  Thanks again.

**Comment by mmcc** [comment]
:+1: Cool, internal applications are a different story :)

**Comment by dmwhite3** [comment]
I have one final (but critical issue) now. Due matters outside my control, the user base from my app are on ie6 for the next 12 months until they are upgraded to ie11. The app is now perfectly working on ie8 and chrome as these are my test beds for flash and html5 respectfully. But in ie6 the video player doesnt display and the JavaScript is failing. Error seems to be videos is undefined on the line of code "videojs.options.flash.swf =..." but I suspect it would fail on any videos reference. Is this a known issue in 4.12…?

**Comment by mmcc** [comment]
We don't officially support anything less than IE8, so this is very much known. There's an [issue](https://github.com/videojs/video.js/issues/539) that discusses the style changes necessary to get it working, but also keep in mind we're finally [actively removing workarounds](https://github.com/videojs/video.js/pull/1946) specific to IE6.

**Comment by dmwhite3** [comment]
Hi Matthew, I found that post before asking the question but it seemed to be about look and feel and styling issues where as my issue is functional where as nothing is rendered and JavaScript errors are thrown (as above). Any final suggestions? I'm going to give it a few more days detailed investigation but if I can't get around this I'm going to have to progress my second favourite option of media player js which would be a shame given how close I am now.

**Comment by dmwhite3** [comment]
FYI - the current solution that I am looking to replace is the flash version of flow player but we want open source so we can see inside and also future proofing ... Hence HTML5 with flash polifill

**Comment by mmcc** [comment]
To be honest, if IE6 is a requirement, you're probably better off using a different player. :sad: As I said, not only are IE6 / 7 not a priority, we're actively removing hacks required to make them work.

I realize this one's out of your control, but we think continuing to build for legacy browsers is holding back the web. Sorry we can't help, but I hope you understand.

**Comment by heff** [comment]
You could also try [older versions of video.js](https://github.com/videojs/video.js/releases). I can't say when IE6 was broken, but I'm pretty sure it was working javascript-wise in 4.0.
