### ISSUE TITLE
https files not playing

### ISSUE THREAD

**Issue by technotip** [videojs/video.js#1934]
I used video.js in one of my projects where I fetch the video URL dynamically. All the URLs start with https. But Video.js fails to play them :(

**Comment by mmcc** [comment]
HTTPS [should be fine](http://jsbin.com/rafeja/1/edit?html,output), but if you want to put together a reduced test case we can try and help debug.

**Comment by vijaykumargangani1110** [comment]
hiii

**Comment by vijaykumargangani1110** [comment]
HIIII

**Comment by vijaykumargangani1110** [comment]
svkvdskbvdkb

**Comment by vijaykumargangani1110** [comment]
sdfnvkdvnldvlndvb

**Comment by vijaykumargangani1110** [comment]
zdkdsnkdslvxcl dvzkl dvzkldvzkl vzd kldvzbkldzv
