### ISSUE TITLE
Default subtitle indeed does not work in v.4.12.3

### ISSUE THREAD

**Issue by dn5** [videojs/video.js#1936]
I saw this [issue](https://github.com/videojs/video.js/issues/1914) posted a couple of days ago but from what I can see, the user elfaxvaxec is lacking english knowledge so I'll rewrite the problem with debug/testing.  
  
Video.js version: 4.12.3 (latest)
Browser: Tried in both Mozilla Firefox (35.0.1) & Chrome (40.0.2214.115 m)
OS: Windows 7 Ultimate (64bit / latest patch-update)
Reduced test case: http://jsbin.com/tikiyogupi/1/

I'm not sure does HTML5 allow remote subtitles in "src" attribute. The subtitles are WEB-VTT formatted as seen here: http://dn5.ljuska.org/git/hb2.vtt  
Cheers.

**Comment by elfaxvaxec** [comment]
thanks, dn5!

**Comment by gkatsev** [comment]
Can you post this in #1914 so we can track this in one place as opposed to in several issues?
