### ISSUE TITLE
Poster image should appear after the video is finished

### ISSUE THREAD

**Issue by wjpdesigner** [videojs/video.js#1938]
Hi Video.js

I think the poster image should appear after the video is finished because right now I just see the last frame of the video (empty black screen).

Thanks,
Jack

**Comment by gkatsev** [comment]
Because videojs mimics and uses the native video element in browsers, we don't show the poster when the video finishes. You can see the native video element functionality here: http://www.w3.org/2010/05/video/mediaevents.html.

**Comment by mmcc** [comment]
You can listen for the ended event and show the poster yourself if you'd like, though. 



—

**Comment by heff** [comment]
You can also add the following to your CSS, as of v4.12.

```
.video-js.vjs-ended .vjs-poster {
  display: block;
}
```

**Comment by wjpdesigner** [comment]
Hi heff,

Thank you so much your method is working.

Thanks,
Jack

**Comment by wysocki** [comment]
Only my controls come up at the end. I'm running 4.12.5 and heff's css didn't work for me. I'd also like the big start button to reappear if possible.

**Comment by heff** [comment]
@wysocki that CSS didn't even bring up the poster? You could try:

```
.vjs-default-skin.vjs-ended .vjs-big-play-button {
  display: none;
}
```

You can see how the big play button is hidden with CSS [here](https://github.com/videojs/video.js/blob/master/src/css/video-js.less#L573).

**Comment by wysocki** [comment]
That did it, heff! That got the play button at the end now (although I believe you meant display:block instead of none). I also have the poster back but not sure exactly why. I stripped my code down to minimum and rebuilt, but at least it works now, THANKS!

**Comment by heff** [comment]
Nice, great to hear!

**Comment by miriBenShlomo** [comment]
heff's css didn't work for me...
any idea?

**Comment by miriBenShlomo** [comment]
heff's css didn't work for me...
any idea?

**Comment by miriam-wr** [comment]
heff's css didn't work for me...
any idea?

**Comment by carloscarnero** [comment]
> heff's css didn't work for me...
> any idea?

I'm currently using something like this:

```javascript
$videoPlayer.on("ended", function () {
  $videoPlayer.currentTime(0);
  $videoPlayer.hasStarted(false);
  $videoPlayer.trigger("ready");
});
```
