### ISSUE TITLE
vjs-load-progress not work properly

### ISSUE THREAD

**Issue by hanserdev** [videojs/video.js#1942]
Sometimes js-load-progress remain to 0% with the last version of firefox.
This seem to happen  usually with short videos.
And seems happen  only for all versions after the 4.7.

**Comment by heff** [comment]
Thanks @hanserdev, I can confirm this is happening. It happens on the main videojs.com video and http://jsbin.com/axedog/.

If you get the video element's `buffered.end(0)` property it has the entire video buffered already and the load progress bar is still at 0%. My best guess is that the video is cached, and either the video element isn't triggering a `progress` event, or the player isn't listening in time to catch the one event that's fired.

@hanserdev would you be able to help set up a reduced test case to show if the bare video element is still firing a progress event for these videos?

**Comment by mmcc** [comment]
@hanserdev ping?

**Comment by mmcc** [comment]
Closing this since we haven't heard back from OP.
