### ISSUE TITLE
use videojs for a project

### ISSUE THREAD

**Issue by myhq** [videojs/video.js#1945]
Hi Guys, I consider you the brain behind video editing on the web. Could you give me your thought on how to go about creating a webapp/mobile app (with cordova) that can:

1) record CLIPS of video (300x300, if not, see 3) "press and hold to record" (vine-style)
2) add CLIPS of video from Gallery
3) crop video size to squared 300x300 pixels
4) crop timeline per clip individually
5) give each clip an action effect: loop, loop+slowmo, slowmo, loop+reverse, etc
6) give clips or entire video a CSS effect
7) play video file in our web/app (no extrenal plays required)

NOTE: clips can last 1-10 seconds, total video can take max 10 seconds
NOTE2: due to action effects the play time of the 10 second vide can be longer than 10 seconds, but the filesize will be limited to 10 second video.

Looking forward to your thoughts

**Comment by heff** [comment]
Thanks for the compliment, but this is a pretty involved project and out of the scope of what we can handle in the issues here with everything else we're trying to manage. Good luck with the project!
