### ISSUE TITLE
Chapters button should have a different Icon from subtitles

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#1954]
If a 'chapters' track is present or added, an extra ControlBar item is added to select between the chapters. The [Chapters icon](https://github.com/videojs/video.js/blob/master/src/css/video-js.less#L105) is identical to the Subtitles icon, which is visually confusing (especially since Subtitles are more similar to Captions, which have a totally different icon!).

I suggest using one of the 'bookmark' type icons from the Icomoon font; unfortunately there isn't a nice 'book with bookmark' type icon in their free font. And I'm not clear how to add it, otherwise I'd do a PR!

**Comment by heff** [comment]
Thanks! Confirming this is an issue. @mmcc might be able to speak to the right font icon. We're switching fonts in 5.0 (I think).

**Comment by mmcc** [comment]
This was an oversight of sorts. When I initially made the font chapters weren't working yet, so an icon didn't make it into the set. I'll definitely make sure a bookmark makes it into the 5.0 font.

**Comment by OwenEdwards** [comment]
Sure, totally understand. Just wanted to make sure this was on your radar, moving forward. It came up as I'm looking at support for other types of text track. Do you have test cases for chapters track(s)? Do many people even use them? It seems like @gkatsev is fielding the majority of the work on TextTracks, but this crosses into a UI/UX issue.

**Comment by mmcc** [comment]
This should be fixed in master that #1999 is pulled in (new icons and the chapters button is indeed different).
