### ISSUE TITLE
Out of Date Tracks Documentation

### ISSUE THREAD

**Issue by brimanning** [videojs/video.js#1958]
The [text tracks documentation](https://github.com/videojs/video.js/blob/stable/docs/api/vjs.TextTrack.md) is currently out-of-date.

It looks like the captions overhaul of [4.12](https://github.com/videojs/video.js/releases/tag/v4.12.0) is probably why.

Notable example issues:

- Methods missing (e.g. [`vjs.TextTracks.activate()` is no longer a method](https://github.com/videojs/video.js/blob/stable/docs/api/vjs.TextTrack.md#activate))
- Links to code are wrong for links to src/js/tracks.js (e.g. [`activeCues()`](https://github.com/videojs/video.js/blob/stable/docs/api/vjs.TextTrack.md#activecues) link in documentation returns a [404](https://github.com/videojs/video.js/blob/master/src/js/tracks.js#L270))

**Comment by gkatsev** [comment]
Yes, you're correct. In 4.12, we reworked our text tracks completely. Unfortunately, documentation tends to fall behind :(

**Comment by brimanning** [comment]
Of course. Makes sense to me. It just took some digging to realize that.

**Comment by gkatsev** [comment]
Fixed by https://github.com/videojs/video.js/commit/18cdf08c0e784073d37d3dfc807dfb47eccdd344
