### ISSUE TITLE
FLV file plays small up in the left hand corner with flash

### ISSUE THREAD

**Issue by garymoon** [videojs/video.js#1959]
When attempting to play [this file](http://disco.pink/streamtest/video-js-3/DiscoMelee-13-Mar-15-22_32_34.flv) with the flash fallback, it plays very small up in the left hand corner.

What did you do? (steps to reproduce)
I took the demo and modified it to play this file. I removed the various demo formats & tracks, the poster, and forced techorder to flash only.

What happened? (actual results)
The video played very tiny in the upper left hand corner.

What should have happened? (expected results)
I expected the video to play normally - full size in the player.

Video.js version (e.g. v4.3.0)
4.12.5

Video.js plugins used (e.g. videojs-youtube)
None

Browsers + platforms where this is happening (e.g. Windows XP IE8)
OS X Firefox, OS X Chrome, Windows Chrome, Windows Firefox

Browsers + platforms where this is NOT happening (e.g. Mac Chrome 30)
None to my knowledge

Reduced test case or online example (link)
http://disco.pink/streamtest/video-js-3/demo.html

I've tried every single thing I could think of (we're using Video.js in production so I'd consider myself reasonably familiar with it). I've used it from the cdn, gone back as far as 4.1.0, played it locally and off http etc. The file is a recording from the [Nginx rtmp module](https://github.com/arut/nginx-rtmp-module/). Live, the stream plays perfect, but the recordings suffer this issue. Just in case, [here](http://disco.pink/streamtest/video-js-3/Jcich31-16-Mar-15-03_00_27.flv)'s another one from a different user.

I'm happy to try out any ideas.

Thank you.

**Comment by mmcc** [comment]
I'm fairly certain this is related to this [swf issue](https://github.com/videojs/video-js-swf/issues/55). There are even [other issues](1571) in this tracker that have reported similar problems (although that specific example is dealing with RTMP, it's almost certainly related).

**Comment by garymoon** [comment]
My apologies, apparently my existing-bug search was pathetically insufficient. Please feel free to mark as a duplicate, I'll watch the original ticket. Please feel free to hit me up if you need a hand with anything. Thanks for the quick reply also.

**Comment by mmcc** [comment]
No worries! I vaguely remembered the original ticket, so I had an idea of what to look for :)



—
