### ISSUE TITLE
Doesn't play on resume

### ISSUE THREAD

**Issue by dzarezenko** [videojs/video.js#1967]
I try to use video.js for football translations, but when I press pause and press play again video is still paused (http://dmytro.zarezenko.com/football/video.php).

What is wrong? Thanks!

**Comment by mmcc** [comment]
This is an issue with RTMP, but there's a solution proposed in #1920 (calling `load()` before resuming playback).

**Comment by dzarezenko** [comment]
Thanks a lot, now it works fine.

**Comment by mmcc** [comment]
No prob! Glad to help.
