### ISSUE TITLE
VideoJS - Header HTTP_RANGE

### ISSUE THREAD

**Issue by Majkelo23** [videojs/video.js#1968]
I'm trying to parse HTTP_RANGE header in PHP and finally watch this video on my web page but I can't do it. Here is my problem: http://stackoverflow.com/questions/29209806/videojs-header-http-range
How I can fix this problem?

**Comment by mmcc** [comment]
This question is pretty firmly outside of our wheel house, so I'm going to go ahead and close this one. We can help with the playback side, but implementing byte-range requests on the server side is beyond the scope of the player.
