### ISSUE TITLE
flashvar don't work on minify (video.js)

### ISSUE THREAD

**Issue by thiagovent** [videojs/video.js#1969]
I have created a simple html to test videojs:
```html
<html>
<head>
	<script src="video.js"></script>
	<link rel="stylesheet" type="text/css" href="video-js.css">
	<script type="text/javascript">
	 document.createElement('video');document.createElement('audio');document.createElement('track');
	</script>
</head>
<body>
	<video id="example_video_1" class="video-js vjs-default-skin"  data-setup='{"techOrder": ["flash","html5"]}'
				class="embed-responsive-item video-js vjs-default-skin" controls preload="none"
			poster="http://video-js.zencoder.com/oceans-clip.png">
				 <source src="video.mp4" type="video/mp4" />
	 			<p class="vjs-no-js">not supported</p>
	</video>
</body>
</html>
```
( I need use flash as default, sorry about that).
In runtime, the flashvars is wrong:
```html
<param name="flashvars" value="(...)preload=undefined(...)">
```
*preload=undefined* makes the video auto-load fully! 

If I load *video.dev.js* instead, all works:
```html
<param name="flashvars" value="(...)preload=none(...)">
```

Using the *jscompress.com* to minify the video.dev.js, works fine too.

**Comment by mmcc** [comment]
Sorry for the delay on this one, but the good news is, I think #1940 probably solves this. The bad news is, we're not doing another release from master until 5.0 is ready, which is going to mean at least a few weeks. Can you get by with using your own minified version until then?

**Comment by thiagovent** [comment]
No problems.. I'm already using my own minified version, thanks.
