### ISSUE TITLE
4.12.0+ replacement event for subtitlestrackchange

### ISSUE THREAD

**Issue by sbone** [videojs/video.js#1970]
Upgrading from an older version of VideoJS, and noticed the subtitlestrackchange/captionstrackchange event has been removed. Is there a comparable event to listen for? Nothing's jumping out at me.

**Comment by gkatsev** [comment]
There's a `change` event on the TextTrackList. You can get the TextTrackList from `textTracks()`.

**Comment by sbone** [comment]
@gkatsev Thanks!

**Comment by gkatsev** [comment]
No problem!
Let us know if you have any issues with it.
