### ISSUE TITLE
IE Browser freezes when audio duration is longer than video duration

### ISSUE THREAD

**Issue by sdecreme** [videojs/video.js#1971]
Hi,

I tried to open my video with video.js but it doesn't work correctly. I watch the video. At the end of the video, I try to go back to the middle of the video using the progress bar cursor but it doesn't work. My IE browser freezes. I have this problem only on IE with my version of video.js which is 3.2.0. 
I have the same problem with the last version of video.js.

When I open my video with MediaInfo software, I note the audio duration is longer than the video duration. The html5 native player can read my video without problems.

Do you know this bug ? Do you have a fix ? Could you correct it and give me the fix please ?

I can send you my video if you need it,

Thank you in advance,

Suzi

**Comment by mmcc** [comment]
Would you mind creating a [reduced test case](http://jsbin.com/axedog/latest/edit) for us?

**Comment by sdecreme** [comment]
Ok, I updated your jsbin webpage with my video. You can reproduce it with last IE.
http://jsbin.com/xiwuzuvomi/1/edit

**Comment by mmcc** [comment]
I see weird issues with the control bar because of the odd file, but the browser continues to run just fine. Testing with IE11 running on Windows 7 and Video.js 4.12.5.

**Comment by sdecreme** [comment]
It is really strange. I reproduce easily on IE11 with Windows 7 testing this link : http://jsbin.com/xiwuzuvomi/1/edit

Did you go to the end of the video with the cursor, and then go back to the beginning of the video with the cursor ? 

A progress bar appears into the video and the browser freezes.

**Comment by sdecreme** [comment]
I have the same problem with the video displayed into the official website : http://www.videojs.com/
On IE11 with Windows 7. If a watch all the video and I try to come  back to the middle of the video with the cursor, it doesn't work.

**Comment by mmcc** [comment]
I can occasionally get the seek handle to get stubborn around the end of the video, but the browser never freezes. I can do any combination of movement with seeking, and the worst case scenario is that it might not seek to the point I want, but a second attempt always works and the browser always stays responsive.

On slightly larger content (like the VJS website) that doesn't have the malformed metadata that the JSBin example has, I don't see any issues with the seek handle. Occasionally the video will take longer to load if the handle is dragged as opposed to just clicked, but again, browser never goes unresponsive, video eventually plays back as expected.

**Comment by sdecreme** [comment]
![img_01042015_091110](https://cloud.githubusercontent.com/assets/11627610/6936154/40d3a646-d84f-11e4-8bcd-3517e518cbc1.png)

I sent you a screenshot of the bug. The video freezes but not the browser. I can't never play the video.

**Comment by mmcc** [comment]
As I said, occasionally it hangs, but eventually it starts playing again. I've noticed I can get it to hang more often if I drag the slider as opposed to click the progress bar where I want.

For what it's worth, I seem get the same occasional blip using the native video element. Are you seeing that as well?
