### ISSUE TITLE
IE11 not working?

### ISSUE THREAD

**Issue by techytuppers** [videojs/video.js#1973]
Looking at the videojs website itself, it throws the same error as I get in my code - screenshot attach using Browserstack. 

Have seen other older posts about IE11 compatibility, but none including a screenshot of the videojs site itself doing the same thing. 

Thanks - TT

![screen shot 2015-03-24 at 15 33 31](https://cloud.githubusercontent.com/assets/2923033/6805543/70b93386-d23b-11e4-9899-ed7ffcd27959.png)

**Comment by gkatsev** [comment]
Hm... not sure what's going on. It's working on my IE11 VM. Any ideas @mmcc?

**Comment by techytuppers** [comment]
I'm thinking it might be a Browserstack issue? Thanks for the response and verification on the VM though @gkatsev

**Comment by gkatsev** [comment]
Yeah, it could definitely be a browserstack issue.

**Comment by techytuppers** [comment]
Can confirm it works on a real life IE11 setup. Browserstack issue it must be.

**Comment by mmcc** [comment]
Browserstack is unfortunately pretty hit or miss when it comes to testing the video element. I thought they'd improved things recently, but alas.



—
