### ISSUE TITLE
Wrong duration/time for MPEG-DASH live streams

### ISSUE THREAD

**Issue by frapontillo** [videojs/video.js#1977]
I am using [dash.js](https://github.com/Dash-Industry-Forum/dash.js) and the the related [contrib/videojs/videojs-tech-dashjs.js](https://github.com/Dash-Industry-Forum/dash.js/blob/development/contrib%2Fvideojs%2Fvideojs-tech-dashjs.js) to show a live stream via videojs.

While the stream works perfectly, the duration and time parts don't seem to be correct, as the "live" time is always stuck at "4:55", while the duration is always "5:00" (300 seconds).
The weird thing is that the native HTML5 video element shows the correct timings, so it can't be an issue on the dash.js side.

Live demo showing the problem: http://plnkr.co/edit/ntQdXErwbk1jIKbBSQD5?p=preview (the first one is video.js via dash.js/contrib, the second is native video via dash.js).

![Demo](http://i.imgur.com/RmGjJgf.png)

**Comment by heff** [comment]
Thanks for the demo, that helps. I'm seeing something similar, though the native element is an hour ahead for me.

![screen shot 2015-03-28 at 6 49 59 pm](https://cloud.githubusercontent.com/assets/166/6883788/6f612ece-d57b-11e4-9092-80b54e7de0c2.png)

The video.js tech gets it's duration value from the [dash player's `mediaPlayer.duration()`](https://github.com/Dash-Industry-Forum/dash.js/blob/development/contrib/videojs/videojs-tech-dashjs.js#L69).

It also gets it currentTime from [`mediaPlayer.time()`](https://github.com/Dash-Industry-Forum/dash.js/blob/development/contrib/videojs/videojs-tech-dashjs.js#L50). 

Those are the two values that are used to create the control bar. I'm not exactly sure what else should be done there for a live stream specifically. @dsparacio do you know if there's different time values we should be grabbing on the dash player for live streams?

**Comment by frapontillo** [comment]
I am debugging the `duration()` and `time()` for both the video.js and the native video Dash players, and it looks like they're the same, with the duration always staying at `300` and the time periodically resetting to about `290`.

```javascript
player.duration()
300
player.time()
289.85202343750007
player.time()
289.8650234375002
player.time()
289.86402343750024
player.time()
289.86302343750003
player.time()
289.85402343750025
player.time()
289.86002343750033
player.time()
289.84502343750023
```

As the native video element has the right timing, I am assuming that the proper way to get the timing would be using the native getters `videoElement.currentTime` and `videoElement.duration`, that return the proper values.

**Comment by dsparacio** [comment]
Is it a rolling DVR window? Time and duration should be static or stuck if so? Need to look at this on Monday!

Thanks,
- Dan

**Comment by frapontillo** [comment]
@dsparacio the latest manifest definition has `availabilityStartTime="2015-03-29T15:00:00Z"` and  `availabilityEndTime="2015-03-29T18:00:00Z"`, then it is automatically re-created and loops for 3 more hours, indefinitely.

In fact, the native video element has the correct `duration` set to `10800` seconds, that is 3 hours.

**Comment by AkamaiDASH** [comment]
@frapontillo @heff  There is in fact a 5 minute DVR window in this MPD  The time coming from mediaplayer duration and time is correct. The native HTML scrub and time is not accurate. 

timeShiftBufferDepth="PT5M">

**Comment by frapontillo** [comment]
I totally missed that `timeShiftBufferDepth`!
Thank you, the issue can be closed for what concerns me.

**Comment by mmcc** [comment]
Sweet! Thanks for the help debugging @AkamaiDASH and @dsparacio.

**Comment by AkamaiDASH** [comment]
@frapontillo - Great and thank you for taking the time to file the issue and supply great details on what the issue is. 

@mmcc @heff -There is still an issue with videojs however being tracked here
https://github.com/Dash-Industry-Forum/dash.js/issues/353 

By the way @AkamaiDASH and @dsparacio is the same person... I changed which username I use for this project - @AkamaiDASH is the correct one for dash.js Sorry for the confusion :)

**Comment by heff** [comment]
Just pinged Tom on the other issue.

**Comment by AkamaiDASH** [comment]
Thanks @heff   -  I can help by setting up the encoder to produce the issue.
