### ISSUE TITLE
event: onBuffering?

### ISSUE THREAD

**Issue by zakdances** [videojs/video.js#198]
I've read the VideoJS api (http://videojs.com/docs/api/) and I can't figure out how I can get the player to fire an event when it starts buffering. I want to know when the player pauses to buffer ( at any point in playback ) so that I can sync another video on my webpage. How can I get the player to listen for this event?

**Comment by MrWiLofDoom** [comment]
Has there been any progress on this issue? Has anyone come up with a solid method for detecting buffering?

**Comment by otoinsa** [comment]
Also interested in this...

**Comment by rxluz** [comment]
Me too

**Comment by manojvarmaboppisetti** [comment]
me too

**Comment by gkatsev** [comment]
This is a really old issue. You likely want to listen to the `progress` event to know when content is being loaded. Depending on your needs you also want to keep track on the `player.buffered()` property and see that the `player.buffered().end(0)` is increasing as you expect.
If you're having a separate problem, please open a new issue with a detailed description of it, ideally with a live minimal example.
