### ISSUE TITLE
Malware false positive (?)

### ISSUE THREAD

**Issue by vasklund** [videojs/video.js#1982]
Some anti-virus programs seem to react to the Video.js source:

http://sitecheck.sucuri.net/results/vjs.zencdn.net/4.12.5/video.js

At least one other anti-virus program has also had a positive, although on our concatenated source which includes other libraries too.

We are currently investigating and I will add more info as I can, but it would be interesting to know if this has been an issue for someone else too?

**Comment by mmcc** [comment]
It's reacting to VTT.js, which means it should also think Firefox is malware. Interesting to note, it thinks [videojs.com](http://sitecheck.sucuri.net/results/videojs.com) is fine, which pulls in 4.12.5.

I don't know anything about Sucuri, but I would take their results with quite a bit of salt.

**Comment by mmcc** [comment]
I tried to find other services to compare it with just to make sure, but I can't seem to get it to fail anywhere else (and not surprisingly, a lot of these sites seem pretty shady). [Google](https://www.google.com/safebrowsing/diagnostic?site=https://vjs.zencdn.net/4.12/video.js) reports things as ok, but I think that's a different kind of check than Sucuri is proposing.

Quasi-related, we're planning on adding a periodic checksum to monitor the CDN versions and make sure nothing changes that wasn't officially released (and ring alarm bells if it does).
