### ISSUE TITLE
vjs-text-track-display thrashing DOM changes

### ISSUE THREAD

**Issue by bryfry** [videojs/video.js#1985]
[Video for refrence](https://www.youtube.com/watch?v=Bi5SsWhA-68).  It looks like something is thrashing changes to the DOM. It never stops regardless of video state.  This might be normal functionality but it looked strange to me.

Same setup as in [this issue](https://github.com/videojs/video.js/issues/1984)

**Comment by gkatsev** [comment]
Yeah, this sounds like it's working as designed. For emulated text tracks, we update that div's children a lot from a `timeupdate` event. There's possibly some stuff we can do to make it update the DOM a bit less but I'd be inclined to only do so if this is actually having a perceived bad performance.
