### ISSUE TITLE
missing CSS style "vjs-slider-vertical" for vertical volume bar

### ISSUE THREAD

**Issue by yiran214** [videojs/video.js#1991]
Issue:
I have a vertical volume bar working with old videoJS (the way how I did is disable the volumeControl and muteToggle and enable volumeMenuButton and rotate it 90 degree ).
Recently I pulled the lastest code and noticed that the slider.js added vertical support and my volumeBar is broken. One thing I noticed is there's no "vjs-slider-vertical" in CSS files.
I assume that with the latest videoJS, I don't need to take care of the rotate and just add 
'volumeMenuButton': { volumeBar: { vertical: true } }, it should work. But that's not true.

Question:
1. How should I create the vertical volume bar? Should I do the rotate? Or videojs will automatically rotate the volume bar. And Should I define
.vjs-default-skin .vjs-volume-bar {
  width: 5em;
  height: 0.6em;
} 
Or
.vjs-default-skin .vjs-volume-bar {
  width: 0.6em;
  height: 5em;
} 
2. I tried to fix the issue by changing the slider.js, what I did is:
   In vjs.Slider.prototype.calculateDistance:
boxH = Math.max(el.offsetWidth, el.clientWidth); and change the updateHandlePosition and  vjs.Slider.prototype.update method accordingly. 

Is this the right way to fix the issue?

Thanks,
Jessica

**Comment by mmcc** [comment]
I just added a note to the Readme to make this explicit, but you should use the [stable branch](https://github.com/videojs/video.js/tree/stable). This is the case where we have a feature pulled in for 5.0, but other dependencies aren't ready yet (namely, the new base them).
