### ISSUE TITLE
TypeError on calling pause()

### ISSUE THREAD

**Issue by MarcoNiedermann** [videojs/video.js#1992]
Happens if I call pause() on player without controls. Used in an angularjs envorinment, tested under iOS8, Safari.

1. step: creating the player
```javascript
var playerHTML = angular.element('<video id="video' + activePlayerIndex + '" class="video-element video-js vjs-default-skin"><source src="' + scope.videoSrc.src + '"  type="video/mp4" /></video>');
activePlayer = videojs("video" + activePlayerIndex, {"techOrder": ["html5", "flash"], "preload": "true" }, function () {... this.play(); ...});
```

2. step: starts playing
works fine!

3. step: calling pause
```javascript
activePlayer.pause();
```

Expected: Player should pause

Actual: Player pauses, but fails afterwards with error:
TypeError: undefined is not an object (evaluating 'this.c.children[0].children')
...on video.js Line 1607

**Comment by mmcc** [comment]
I'm not sure I follow, could you create a [reduced test case](http://jsbin.com/axedog/latest/edit)? I put together an [example](http://jsbin.com/meyahezixe/1/edit?html,output) that has no controls and doesn't run into this issue, so feel free to clone / modify that one.

**Comment by MarcoNiedermann** [comment]
Many thanks for your reply!
As I saw in your example, there are several divs added to the dom: i.e. vjs-poster, vjs-loading-spinner, vjs-big-play-button, etc... these div's are completely missing in my dom. Ok, so it seems to be a problem on my side. Sorry for this! I'll better get back to my code and check, why these div's are gone!

**Comment by mmcc** [comment]
Great! Closing this, but let us know if you figure it out.
