### ISSUE TITLE
Android - fullscreen does not work

### ISSUE THREAD

**Issue by endrjuskr** [videojs/video.js#1995]
Opening video-js in `WebView` for instance from [here](http://www.videojs.com/) does not allow user to use full screen. 

There are no error logs and it was tested on Android 4.4.

Update: It fully works in native browser.

**Comment by mmcc** [comment]
This seems like something you'd need to handle within the [WebView itself](https://stackoverflow.com/questions/4748888/webview-with-full-screen-in-android).

**Comment by endrjuskr** [comment]
@mmcc problem described on stackoverflow it's totally different than mine.

When I click on fullscreen button in video-js player nothing happens.

**Comment by mmcc** [comment]
When you click on the fullscreen button from within a WebView, correct? But it works appropriately from a browser? That tells me this is an issue specific to the WebView, not Video.js.

**Comment by mister-ben** [comment]
An Android WebView does not have the same capabilities as Chrome out of the box. There's a fair amount of tweaking needed to get it to support video properly. Take a look at this custom WebView, it looks like all the hard work has been done for you:

https://github.com/cprcrack/VideoEnabledWebView
