### ISSUE TITLE
Version 4.5.0 and captions

### ISSUE THREAD

**Issue by harwooje** [videojs/video.js#1996]
I'm looking for a substitute for the "mediaelement.js" plugin.  Now that the plugin has been integrated into the WordPress core it appears the plugin is not being maintained.  The core implementation of "mediaelement.js" doesn't support captioning, which I need.

One thing I notice with a 480 X 360 video and the Version 4.5.0 videojs plugin is that when I hover over the "CC" icon, as soon as I move the mouse up to select "english" the cursor hits a clear space and the menu disappears.  Do you know about that?

**Comment by heff** [comment]
Is there a reason you're using v4.5 and not the latest stable version, v4.12?

**Comment by harwooje** [comment]
I am using the latest version of Wordpress (4.1.1) — I went to the “plugins” page, picked “Add new”, did a search for “videojs” and this is what Wordpress gave me.

There’s no “update” notice attached to the plugin.  Here is the text on the plugin page (I don’t know if the formatting will survive email):

Video.js - HTML5 Video Player for WordPress
Activate<http://129.59.138.44:8888/wp-admin/plugins.php?action=activate&plugin=videojs-html5-video-player-for-wordpress%2Fvideo-js.php&plugin_status=all&paged=1&s&_wpnonce=3571dc8be1> | Edit<http://129.59.138.44:8888/wp-admin/plugin-editor.php?file=videojs-html5-video-player-for-wordpress/video-js.php> | Delete<http://129.59.138.44:8888/wp-admin/plugins.php?action=delete-selected&checked%5B0%5D=videojs-html5-video-player-for-wordpress%2Fvideo-js.php&plugin_status=all&paged=1&s&_wpnonce=c69ddb1238>


Self-hosted responsive HTML5 video for WordPress, built on the widely used Video.js HTML5 video player library. Allows you to embed video in your post or page using HTML5 with Flash fallback support for non-HTML5 browsers.

Version 4.5.0 | By Dustin Lammiman<http://www.nosecreekweb.ca/>, Steve Heffernan<http://steveheffernan.com/> | View details<http://129.59.138.44:8888/wp-admin/plugin-install.php?tab=plugin-information&plugin=videojs-html5-video-player-for-wordpress&TB_iframe=true&width=600&height=550>








On Apr 1, 2015, at 2:26(24) PM, Steve Heffernan <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a reason you're using v4.5 and not the latest stable version, v4.12?

**Comment by heff** [comment]
Sounds like the wordpress plugin is badly in need of an update. Would you mind posting an issue on that project?
