### ISSUE TITLE
VJS 5: Use the built-in EventEmitter

### ISSUE THREAD

**Issue by eXon** [videojs/video.js#2002]
Once we are done migrating to ES6 modules + browserify, their is a built-in event system that we can use instead of writing our own. Better embrace the whole ecosystem.

Here is the official doc: [`EventEmitter`](https://nodejs.org/api/events.html)

**Comment by gkatsev** [comment]
Yes, you're 100% correct. We should totally do that.

**Comment by heff** [comment]
I like the idea if it does what we need.
Can we still support IE8 with that route?
Can babelify handle writing Component as an ES6 class that subclasses the non-ES6 EventEmitter, and would features like `super` and `instanceof` still work?

It would be quite an eventectomy, though not impossible. We rely on some advanced features of the current implementation like the [bind](https://github.com/videojs/video.js/blob/c9b53c5cfe780a584ec9f7e758bdacfc0023c685/src/js/lib.js#L196) function ID for removing listeners, even if the listeners were later wrapped in a binding function.

Also today, Component isn't really the EventEmitter itself. It has a reference to an element, and then uses `videojs.on/off/trigger` as an abstraction to make custom events work across browsers, so the element is really the EventEmitter and Component is just a proxy. So we could also be looking at how we could be removing our event logic and relying more on the underlying elements for that.

**Comment by dmlap** [comment]
I'm going to weigh in as the curmudgeon here. Our EventEmitter works. It's not much code. We don't struggle to maintain it. Why pull in a dependency that is significantly more complex than our needs?

**Comment by eXon** [comment]
@dmlap I don't get how the EventEmitter is either more complex or an additional dependency. It's basically a class with 5 easy functions everyone knows how they behave and it's from the Node.js core (browserify bundle it automatically). The goal is to embrace the things in the ecosystem that already exists. The more we do that and the more people will look at our code and feel like they can understand it and send pull requests.

Right now, there is a few weird things about the event system that is unique to VJS and I think we should be careful with that.

@heff I just did a few tests just to make sure I'm not talking through my hat and here 

IE8 can be supported if we use the sham. It is not because of the EventEmitter but because of the inheritance in ES6.

You can mix ES6 and ES5 classes with inheritance and constructor (super) their is absolutely no problem.

`instaceof EventEmitter` still work fine

For the binding problem, I'm not sure I like having this because it is not the expected behavior by most people. I've seen many people save the binding in the constructor lately and I think it's not bad:

```javascript
import {EventEmitter} from 'events';

class Test extends EventEmitter {
  constructor() {
    super();
    this.test = this.test.bind(this);
    this.on('event', this.test);
  }
  
  test(e) {
    this.printTest();
  }
  
  printTest() {
    console.log('test');
  }
  
  dispose() {
    this.removeListener('event', this.test);
  }
}
```

**Comment by heff** [comment]
@dmlap thanks for the practical perspective. :)

@eXon I think the bind magic makes things really clean, and doesn't break the typical use case if you're not expecting it, but it is still magic. I just wish there was a cleaner method than manually storing the bound methods back on the instance. I don't love that, but I could get over it.

Still though, I think you should check out how [component.on](https://github.com/videojs/video.js/blob/master/src/js/component.js#L581) just uses [vjs.on](https://github.com/videojs/video.js/blob/master/src/js/events.js#L18) to proxy event listeners to the component's dom element. If `domElement.dispatchEvent` and `addEventListener` worked in all the browsers we supported, we wouldn't need any additional event logic at all.

What the current set up does give us is automatically handling of both user triggered events (a mouse click) an code triggered events (`trigger('click')`). With EventEmitter we would still need to add handling of the user events.

So correct me if I'm wrong, but I don't think EventEmitter is going to help us much here. But if the API is the issue we could work towards matching the API more closely.

**Comment by eXon** [comment]
I'm not 100% familiar with the way the event system work right now. The more I look into it and the more I begin to understand this is not worth the hassle. Much better staying with what we got.

**Comment by heff** [comment]
Ok sounds good. Events are an important discussion we can continue to explore.
