### ISSUE TITLE
VJS 5: Download a custom skin

### ISSUE THREAD

**Issue by eXon** [videojs/video.js#2003]
By making it stupidly easy to create your own custom skin, I think people will start playing more with it and will overal improve the quality of the player. What if it took you only 2 minutes and you had a custom skin that reflect your branding?

One way we could help is with the dark force: a Web app on the Website. We could develop something in the same spirit as the [Theme roller of jQuery UI](http://jqueryui.com/themeroller/). We don't even need a backend for this. 

I'll be happy to write a first draft if it is something that interest enough people.

**Comment by eXon** [comment]
Just realized their is something right on the front page on videojs.com to build a custom skin. The idea is great but it looks a lot restraint on the options

**Comment by heff** [comment]
Yeah we also have [the designer](http://designer.videojs.com) and [a codepen](http://codepen.io/heff/pen/EarCt) that I've been keeping up to date (I'm thinking we'll drop the designer in favor of the codepen). The homepage is really simple and is good for showing of the power of a CSS-based skin, but doesn't go too deep on configuration. With the designer you can do anything but you need to know CSS. Striking a balance between the two is tough. @mmcc is trying to help that with some of the CSS changes in #1999, specifically adding more obvious variables. I'm sure he has some thoughts he could add here. If we could make working in Codepen almost as easy as configuring with form fields, that would be my favorite direction.

**Comment by talamaska** [comment]
the problem is that the codepen is not showing any custom skin in action.

**Comment by tankvn** [comment]
<a href="http://codecanyon.net/item/flat-skin-retina-for-videojs-4/12996945">Flat Skin Retina for VideoJS 4.12 - codecanyon.net</a>
- Skin with Flat style, unlimited colors
- Change color with LESS file
- Icons font generator using SVG files
<br/>(skin is not open source. sorry for the inconvenience)

**Comment by campones** [comment]
I see you included social sharing from iconmood but I dont know how to display this in the controlbar.

Also I ll be honest saying I don't like particularly the codepen editor

**Comment by halspace2001** [comment]
I'm getting a default server page here?!
http://designer.videojs.com/

Many thanks. Totally agreed - a theme roller like jquery mobile is going to be very helpful for customers.

**Comment by gkatsev** [comment]
Resurrecting the designer or the codepen with the latest video.js would be nice but the Video.js team doesn't really have the bandwidth for this, unfortunately.
If anyone is interested in adding it to the website, we'd really appreciate PRs against the website repo: https://github.com/videojs/videojs.com
