### ISSUE TITLE
VJS 5: Documentation on the Website

### ISSUE THREAD

**Issue by eXon** [videojs/video.js#2005]
Their is a great Getting Started guide on the readme. Awesome.
Their is a few guides for everything that we need on GitHub. Awesome.
We don't need that much documentation. VJS is simple.

Where VJS fall short is on making that documentation a little bit easier to find and navigate. I think we could do a much better user experience if we had those same guides within videojs.com (mainly the navigation). We can generate them from the markdown files already in GitHub.

[fluxible](http://fluxible.io/quick-start.html) at Yahoo is doing an awesome job with that and maybe we could build something similar for VJS. Everything you see there is from a markdown file on GitHub.

Not a game changer but a nice-to-have that I'm sure a lot of people would love.

**Comment by heff** [comment]
We used to have docs on the video.js 3.0 site, but they were just more than we (I) had time to manage, so Github was a nice no-effort option for 4.0. If we can find a good markdown to docs option for the new site that'd be great. I've opened  an issue on the videojs.com repo for this. Closing this in favor of that one.
https://github.com/videojs/videojs.com/issues/19
