### ISSUE TITLE
Error: Video could not be decoded” only when video tries to play in IE11

### ISSUE THREAD

**Issue by chrisjchrisj** [videojs/video.js#2007]
I posted this issue on StackOverflow with the above Headline, but StackOverflow wouldn't allow me to tag it with: "video-js", it reads as follows:
When trying to play/test a video(MP4) on my web page, (that has video-js player-v4.11.4, with a flowplayer fallback), using IE11, from my windows7 pc, I select the play button and see " Video Could Not Be Decoded", every time, after about 7 seconds of play in IE11, yet it plays fine in Chrome and Firefox. Any ideas?

Here is the player code:
<video id="_1200k.mp4" class="video-js vjs-default-skin"
preload="none" width="445" height="340" controls
poster="[var.thumb_file]" data-setup='{techOrder: [‘flash’,’html5’}'>

<source src="http://..........s3.amazonaws.com/[var.video_play]"     type='video/mp4' />

<object class="vjs-flash-fallback" width="445" height="340"    type="application/x-shockwave-flash"    data="https://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
<param name="movie" value="/flowplayer/flowplayer-3.2.16.swf" />
<param name="allowfullscreen" value="true" />
<param name="flashvars" value='config={"playlist":["/[var.thumb_file]",     {"url": "http://.........s3.amazonaws.com/    [var.video_play]","autoPlay":false,"autoBuffering":true}]}' />

<img src="[var.thumb_file]" width="640" height="264" alt="Poster Image"    title="No video playback capabilities." />
</object>
</video>

Thanks for any help.

**Comment by chrisjchrisj** [comment]
Here's the stackoverflow link:
http://stackoverflow.com/questions/29424048/error-video-could-not-be-decoded-only-when-video-tries-to-play-in-ie11

**Comment by mmcc** [comment]
Answering this one over on SO.

**Comment by Rebrahul** [comment]
test
