### ISSUE TITLE
Subtitles style video.js v4.12.5 

### ISSUE THREAD

**Issue by x3qmat** [videojs/video.js#2011]
Hello, I have problems with style of the subtitles and captions
With this version we can not change the font or background color, or put transparent , I think the problem is in video.js file, someone can solve this? Or explain me how can I do ? On IE11 background is transparent, but color wont change, and on Chrome, both dont work.

**Comment by mmcc** [comment]
We switched to using [VTT.js](http://github.com/mozilla/vtt.js), which is styled a little differently than VJS' custom captions implementation from before. The VTT.js docs forward along to the spec for [applying css styles](http://dev.w3.org/html5/webvtt/#applying-css-properties-to-webvtt-node-objects), so it should be the same for both native or emulated text tracks.

**Comment by x3qmat** [comment]
Too much confuse, for noob people.

**Comment by x3qmat** [comment]
Should have a tutorial how to implement this.

**Comment by OwenEdwards** [comment]
I don't know if this is what @x3qmat is referring to, but the ability of the user to style Captions and Subtitles in 4.12.x when rendered by VTT.js is __broken in the minified__ video.js, although it __works with the video.dev.js__. I've tracked it down to this line:

`
cueDiv = cues[i].displayState;
`

https://github.com/videojs/video.js/blob/stable/src/js/tracks/text-track-controls.js#L132

which gets mangled in minification. I don't know the fix - perhaps this?

`
cueDiv = cues[i].['displayState'];
`

@gkatsev, you're the expert on this!

**Comment by surikat1978** [comment]
x3qmat   install an older version 4.11.4, everything can be changed in CSS
New version for Java scripters unfortunately. And as more load to the site in last versions

**Comment by gkatsev** [comment]
With the new tracks, we're either relying on native tracks or emulated tracks. Emulated tracks have a captions settings dialog that allow you to test some styles on the cues.
In native tracks, you can style cues with the `::cue` pseudo-selector.
You could try grabbing the cue's `displayState` and modifying it but better to just rely on the settings dialog or using the browser/os level settings to change captions.

Closing as there's nothing else to do in videojs for this.
