### ISSUE TITLE
"Member not found" error when using IE11's IE8 emulation, Win8.1.  Ver 4.12.5

### ISSUE THREAD

**Issue by BurleighBill** [videojs/video.js#2012]
Ran into error on my test server. For a reduced test case I turned to the demo.html included with video.js.  Works flawlessly on chrome, safari, firefox, IE11 edge, IE11 in IE10 emulation, and IE11 in IE9 emulation.

When I try IE11 in IE8 emulation get console error "Member not found" which appears to correspond to text-track-list.js line 24 or 25.

I am getting the same behavior on an identically configured second computer.

For kicks, I linked to the zencdn version 4.12 and got the same error.

When I dropped back to the zencdn version 4.11 the error goes away and the video plays.

I hope I've provided enough information here.  This is my first attempt at a bug report so please let me know how I can improve for next time.

**Comment by mmcc** [comment]
This is a great report, but to be terribly honest emulation mode is rife with issues. Is there a reason why you're using it other than to test IE8? If not, would you mind making sure you see the issue in an actual installation of IE8?

**Comment by BurleighBill** [comment]
You're right on.  I went to modern.ie and set up a virtual win95 ie8 configuration.  

The error "No compatible source and playback technology were found." popped up but once I installed the latest Flash player things worked fine.

Too bad the error message isn't more specific.  I suspect typical users of my site won't think to upgrade (or install) Flash.

Thanks for your response.

**Comment by mmcc** [comment]
Glad I could help!



We used to specifically mention Flash, but some folks in the community were opposed to having the error message link to something proprietary like Flash. 

—
