### ISSUE TITLE
Triggering + resetting userActive

### ISSUE THREAD

**Issue by ksheurs** [videojs/video.js#2014]
I am adding a plugin that enables some keyboard hot keys. In certain scenario's, I want to ensure the controlbar is visible - like when a user is pressing left + right for seeking.

I found the `player.userActive(true)` method, but it seems that it competes with the default 2000ms timeout. ie. - each time I call `player.userActive(true)` it doesn't reset to a new 2000ms timeout, so every 2 seconds during keyboard interaction it will try to hide real quick. Is there a better way to be doing this?

**Comment by heff** [comment]
Try using `reportUserActivity()` and see if that fixes your issue.
https://github.com/videojs/video.js/blob/master/src/js/player.js#L1513

**Comment by mmcc** [comment]
Closing this since it seems like more of a question than an issue, but if there are any updates we can continue the conversation in comments.
