### ISSUE TITLE
Plugin development 

### ISSUE THREAD

**Issue by stacy-andrews** [videojs/video.js#2016]
Hi

I am trying to fix the following outstanding issue with the Range Slider plugin... https://github.com/danielcebrian/rangeslider-videojs/issues/8

The plugin relies on the Component model which has the options_ field and the createEl field, both of which are uglified as part of the video.js build process.  Is there some way to create components that does not use these uglified functions and fields?  A pointer in the right direction would be greatly appreciated.

Stacy Andrews

**Comment by mmcc** [comment]
We've [switched to Uglify](1940) in master (so for 5.0), so this shouldn't be an issue moving forward. In the meantime, there's really not a great answer short of using the dev (not minified) version of Video.js or forking / adding things to the exports for closure compiler.

I know those aren't great solutions, but this will be better soon. I'd tell you to go ahead and use master, but there are still a few pending PRs that need to get merged in before folks should think about using it.
