### ISSUE TITLE
Search box for track-chapter menu

### ISSUE THREAD

**Issue by veerendhar** [videojs/video.js#2018]
"video.js" working good for me. I got another idea that, when my video has too many chapters do i need to scroll to entire chapter menu list or is there any search facility to automatic scrolling to needed chapter name for track-chapter menu..

**Comment by mmcc** [comment]
No, there's nothing like this at this time. I don't think anyone currently working on 5.0 has the bandwidth to take something like this on, but if you'd like to take it on that'd be amazing.

**Comment by heff** [comment]
I think this would be great. I also think it'd be worth implementing as a plugin first, for whoever gets a chance to take it on. Going to close for now but feel free to continue to discuss here.
