### ISSUE TITLE
Help with adding an video-js player feature/tweak 

### ISSUE THREAD

**Issue by chrisjchrisj** [videojs/video.js#2020]
For some reason I'm unable to post this question on StackOverflow, so I hope you don't mind it here. 
I'm using several video.js players on a web page, side by side,(see code below). 

Currently, you can play all players at the same time. I'd like help adding the feature of having only one player play at a time - where if one player is playing, and another 'play' button is selected, the playing player pauses, and the newly selected player plays. Any help/ideas with that will be appreciated. Much thanks.

![player-code](https://cloud.githubusercontent.com/assets/4219457/7024322/da0c54d4-dcf0-11e4-8eb0-6a8fc047a313.png)

**Comment by mmcc** [comment]
This is a super rough, off the top of my head sketch, but basically you'd set up an event handler for play, then update some sort of `currentPlayer` object that keeps track of (you guessed it) the current player. When play is triggered by a player that isn't the currentPlayer, it needs to pause the currentPlayer, then set the new player as current and call play on it. Make sense?
