### ISSUE TITLE
Put new control in JSPlayer

### ISSUE THREAD

**Issue by m23cs** [videojs/video.js#2021]
Hi, I need to put the control of Resolutions in the jsplayer. How do I do it? What I have to write in the embed? Thanks.

![sin titulo](https://cloud.githubusercontent.com/assets/11838855/7027939/d1bd2724-dd52-11e4-9f2a-e7bc0726f17b.png)

**Comment by mmcc** [comment]
The core player doesn't handle manual resolution switching, but Vidcaster maintains a [plugin](https://github.com/vidcaster/video-js-resolutions).
