### ISSUE TITLE
IE8 won't play videos

### ISSUE THREAD

**Issue by stefanlange** [videojs/video.js#2023]
I create video players dynamically with Video.js **v4.12.5**. It works without problems for IE9+, but IE8 only shows a black box where the video should be visible. 
A "member not found" error occurs in the for loop somewhere close to the vjs.TextTrackList function. The missing property is "constructor".

Code:
```javascript
if (vjs.IS_IE8) {
    list = document.createElement('custom');

    for (prop in vjs.TextTrackList.prototype) {
      list[prop] = vjs.TextTrackList.prototype[prop];
    }
 }
```
The same problem exists if I open the video.js website.

**Comment by mmcc** [comment]
How are you testing IE8? Are you *actually* using IE8 or [emulation mode](2012)?

**Comment by mmcc** [comment]
I know that sounds like a weird distinction, but emulation mode is historically awful and gives false alarms all the time.

**Comment by gkatsev** [comment]
Another issue could be IE8 in quirks mode. If the page ends up loading in quirks mode instead of standards mode, it could be causing a whole bunch of isses.

**Comment by stefanlange** [comment]
I have to admit that I'm testing it in emulation mode in IE 10. Both browser and document mode are switched to IE8.

**Comment by mmcc** [comment]
Unfortunately, switching browser / document mode to IE8 won't fix the issues with emulation mode.

**Comment by mmcc** [comment]
Closing was actually an accident, but now that it is I'm going to leave it. If you can confirm in a native installation of IE8 that this is an issue ([reduced test case](http://jsbin.com/axedog/latest/edit) would be awesome), ping this thread so we can reopen and look into it.

**Comment by kheist** [comment]
I can confirm that this an issue with an IE8 native browser, not emulated. I'm currently working on an video for internals where most have IE8 as their default browser. I had my colleagues test the video.js homepage and it shows the same error as stefanlange pointed out. Screen grab below based off the video.js website homepage. 

![image](https://cloud.githubusercontent.com/assets/12748962/7986987/d3e7456a-0aa8-11e5-8983-b06fc41cde92.png)

**Comment by mmcc** [comment]
@kheist I'm seeing the errors, but they aren't affecting playback. I'll take a look at this for 5.0, but I'm seeing the same deal there (except only 1 error). Video playback isn't affected, though, so imo this is a pretty minor issue.
