### ISSUE TITLE
event.relatedTarget is undefined on Firefox

### ISSUE THREAD

**Issue by mischizzle** [videojs/video.js#2024]
In src/js/events.js we create the relatedTarget like this (line 55)

```
// Handle which other element the event is related to
event.relatedTarget = event.fromElement === event.target ?
  event.toElement :
  event.fromElement;
```

The problem is that Firefox does not support event.fromElement. Therefore the above code will overwrite the correct relatedTarget with undefined. 

Fix: Firefox does support relatedTarget (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget). So it simply needs to check the existence of this property before setting it.  

note: This issue has already been discussed in ES6ification pull request (https://github.com/videojs/video.js/pull/1976/files#r27894428).

**Comment by heff** [comment]
:+1: Want to make a pull request for it?

**Comment by mischizzle** [comment]
Yep - working on it now :)

**Comment by mischizzle** [comment]
Tried to use contrib feature submit to do the pull request but ended up getting undefined so instead created it manually https://github.com/videojs/video.js/pull/2025

**Comment by heff** [comment]
Bah, sorry. The contrib steps are out of date.
