### ISSUE TITLE
How to add/Used Google Drive video in Video JS ?

### ISSUE THREAD

**Issue by singhjan** [videojs/video.js#2027]
I want to use video stored in google drive in Video js . But In google drive, video links are given without extension .mp4. But They can be stream. Example : https://docs.google.com/file/d/0B-zKk5F6hm6rOXJicnBSOHIyd28/edit.

I do not know how to add on Videojs . But in some website , I found they used picasa video in Video.JS with resolution selector . Their used code: <video id="myplayer" class="video-js vjs-default-skin" controls autoplay width="100%" height="100%"><source src="https://r16---sn-ab5l6n7y.googlevideo.com/videoplayback?requiressl=yes&#038;shardbypass=yes&#038;cmbypass=yes&#038;id=6f289da203d1e5df&#038;itag=18&#038;source=picasa&#038;ip=104.207.132.224&#038;ipbits=0&#038;expire=1431460612&#038;sparams=cmbypass,expire,id,ip,ipbits,itag,mm,ms,mv,pl,requiressl,shardbypass,source&#038;signature=393E43F546BFF83B9B4EDDF44856A4962007682A.3BE1F8CAB0FFEE419C8C1DEE3B6A44061CEEEE43&#038;key=cms1&#038;cms_redirect=yes&#038;mm=31&#038;ms=au&#038;mt=1428868538&#038;mv=m&#038;pl=24" type="video/mp4" data-res="360" />

I want to know how to use with google drive video with resolution selector like 360p, 480, 720p and 1080p.
Note : I am using wordpress .

Help me or Talk to me how to do it.

**Comment by mmcc** [comment]
If there's any way you can get a direct link to the asset, that's going to be ideal. Otherwise I'm fairly sure Google Drive will embed using the YouTube player.

**Comment by singhjan** [comment]
But how some site are using picasa video ? They are also same as google drive video.

**Comment by singhjan** [comment]
@mmcc , But how some site are using picasa video ? They are also same as google drive video.

**Comment by mmcc** [comment]
You might want to try viewing their source to see how they're doing it. This is pretty specific to Google Drive / Picasa and not Video.js, so this tracker probably isn't your best bet in terms of answer.

**Comment by mister-ben** [comment]
Yo can modify the Google Drive URL to get a direct link - see e.g. http://www.labnol.org/internet/direct-links-for-google-drive/28356/

```
<source src="https://drive.google.com/uc?export=download&id=0B-zKk5F6hm6rOXJicnBSOHIyd28" type='video/mp4'>
```

**Comment by RathanakSreang** [comment]
Do we have any way to use google drive embed in VideoJS?
I do try to use this:
https://drive.google.com/uc?export=download&id=FILE_ID
But it have problem when file is big.
And I also  try with.
https://googledrive.com/host/FILE_ID, however google will close this service.

So can use the embed iframe like this to play in VideoJs?
<iframe src="https://docs.google.com/file/d/0B0D1U-EJjbfgbWs4SndvWUk0OTA/preview" width="640" height="480" id="video_iframe"></iframe>

**Comment by gkatsev** [comment]
It would depend on whether google provides an API for those embeds. If yes a tech like videojs-youtube can be made, otherwise, you wouldn't be able  to control it with the videojs controls.

**Comment by RathanakSreang** [comment]
Here the sample embed link which provide by google drive:
<iframe src="https://docs.google.com/file/d/FILD_ID/preview" width="640" height="480"></iframe>
So how can we use it in VideoJS?

**Comment by gkatsev** [comment]
I edited your message to code fence the iframe.
Unfortunately, just the iframe doesn't allow us to do anything. Does google provide a way to communicate with the player inside the iframe? For example, youtube has a js file you can load that lets you talk to the iframe.

**Comment by RathanakSreang** [comment]
I am not sure about it.
OH, in this post http://stackoverflow.com/questions/17779197/google-drive-embed-no-iframe it seem we have other way to get file.
Here:
https://video.google.com/get_player?docid=FILE_ID&ps=docs&partnerid=30

**Comment by yousef31** [comment]
Click here to Stream videos from Google Drive
http://pacestream.com/html5/drive

**Comment by phambanhan** [comment]
You have to get mp4 link before videojs, demo: http://demo.getlinkdrive.com/videojs.php
Code get link mp4 google drive here: http://getlinkdrive.com/code-get-link-google-drive-ipv4-cap-nhat-12-2016/

**Comment by lifehome** [comment]
May I know any _open source_ method that is able to get the link from Google Drive?
It seems to me the link provided from @yousef31 and @phambanhan is closed source...

**Comment by oshihirii** [comment]
The method that works for me when getting file id's is:

- Upload video file (for example)
- Click on file to open it.
- Click on the dots menu in the top right-hand corner
- Click Open in new window
- Copy the file id from the new window
- Use the link in this format:

https://drive.google.com/uc?export=download&amp;id=long-file-id-here

(Make sure the file is shared of course)

This works when using in a video's source tag (and running videojs on that), but not when defined in a videojs-playlist object unfortunately :(.

**Comment by kavin-90** [comment]
it will give 360,480,720,1080(redirector link) size or embed youtube player?

**Comment by lifehome** [comment]
I wonder if private files are capable to do so?

2017年2月6日 下午1:05 於 "Brandan White" <notifications@github.com> 寫道：

**Comment by DedSec002** [comment]
<head>
  <link href="http://vjs.zencdn.net/6.2.8/video-js.css" rel="stylesheet">

  
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
    <source src="https://drive.google.com/uc?export=download&id=1TV_NnBjt0fvH2UcjXKZD9l_1uBuMlcQ6sQ" type='video/mp4'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="http://vjs.zencdn.net/6.2.8/video.js"></script>
</body>

**Comment by corsa22ts** [comment]
create your free google drive player here http://free-embed.com
make your player google drive freeeeeeeee :D

**Comment by corsa22ts** [comment]
create your free google drive player here http://free-embed.com

**Comment by teera04164** [comment]
use this it work for me =>  https://drive.google.com/uc?id=FILE_ID&export=download

**Comment by MrShaded** [comment]
> https://drive.google.com/uc?export=download&id=0B-zKk5F6hm6rOXJicnBSOHIyd28

Here is another way using drive api...
Google Drive Video Player With Video.Js with self customised HTML5 video Player
 :- https://codexdindia.blogspot.com/2020/11/google-drive-video-player-with-videojs.html
