### ISSUE TITLE
How to Add Video resolution Selector in videojs Wordpress Plugin .(360p,720p and 1080p)

### ISSUE THREAD

**Issue by singhjan** [videojs/video.js#2028]
I have used  videojs Wordpress Plugin in my wordpress site. Now I want to add video resolution selector (306p,720p and 1080p ). How to add it ? How to edit plugin ? Help me with pliz with brief details

**Comment by raidpipe** [comment]
get a plugin . its availabe here https://github.com/dominic-p/videojs-resolution-selector

**Comment by mmcc** [comment]
Thanks, @raidpipe!
