### ISSUE TITLE
Video could not be loaded...

### ISSUE THREAD

**Issue by TekkGuy** [videojs/video.js#2030]
I am trying to use VideoJS v4.12.5 to play MP4 files. When I view the page with the VideoJS player, I see the following in MSIE:
     "The video could not be loaded, either because the server or network failed or because the format is not supported."

In Chrome, the video plays only with audio, the video itself is black.

Strangely enough, I have an older video I made from years back in MP4 format that plays perfectly fine. I used the same program to create both videos, but any "new" videos I create all have this issue now.

Any ideas?

Here is my code:
<pre>
&lt;video width="640" height="360" class="video-js vjs-default-skin" id="example_video_1" preload="auto" controls="controls" data-setup="{}"&gt;
     &lt;source src="http://www.MyDomain.com/Videos/MP4_640x360.mp4" type="video/mp4"&gt;&lt;/source&gt;
&lt;/video&gt;
</pre>

**Comment by 02clams** [comment]
I had this problem for quite a while with MSIE and on only one computer. It turned out that on that machine there was a plugin loaded in MSIE that cause a mp4 loading problem and it cause videoJS to throw the server/network fail message. That may or may not be your problem. Please check the issue across several computer before you consider it to be a video encoding or other problem.

**Comment by mister-ben** [comment]
Check the codecs used. Not all MP4 files are h264/aac.

**Comment by TekkGuy** [comment]
Thank you 02clams and mister-ben for your input.

02clams: I checked multiple computer as you suggested and found the problem existed everywhere. So at least that narrowed down that it wasn't machine specific.

mister-ben: Thank you so much for that bit of info. You were correct! The software I am using I have kept updated with all their patches. Apparently, over the years they changed the export feature. Before the "PC/Mobile" compatible export feature created an MP4 file that worked fine. Now it creates an MP4 that doesn't work in all cases...apparently because of the encoder used. There is a new "custom export" feature, where I was able to tell it to specifically create an H264 MP4 file. Once I did that....voila....it worked!

Thank you so much for your input guys, I appreciate it!

-Ben

**Comment by TekkGuy** [comment]
Ok, I have one question regarding encoding...

I have a video that doesn't play in VideoJS. I am trying to convert it to an encoding format that is supported. However I have tried several formats without success... I am at a loss...

I am using a free utility (Free MP4 Video Converter), I tried the following settings:
   Video Container: MP4
   Video Codec: H264_MAIN
   Frame Rate: 30fps
   Bitrate: 1 Mbit/s
   Width: 960
   Height: 640
   Audio Format: AAC
   Sample Rate: 44100 Hz
   Channels: Stereo
   Bitrate: 128 Kbit/s

The above setting doesn't work... I don't know what I should be setting to get my converted video to function. Any suggestions?

**Comment by ychoucha** [comment]
same problem here i make my video with vlc videoConverte i have the video but no sound 

to convert i musing this vlc onfiguration
![vlc01](https://cloud.githubusercontent.com/assets/301074/7177494/7118efb2-e427-11e4-8e57-3e04d5b68411.jpg)
![vlc02](https://cloud.githubusercontent.com/assets/301074/7177495/711a817e-e427-11e4-8561-ef6bfa3dc4e4.jpg)
![vlc03](https://cloud.githubusercontent.com/assets/301074/7177496/711f5df2-e427-11e4-9fa7-daa2e3a78480.jpg)
so what is wrong please ?

**Comment by mmcc** [comment]
I've never used the VLC UI for transcoding, but at a glance I'd say you should probably look into the warning in the first screenshot:

> This muxer is missing. Using this profile will fail.

**Comment by raditya-ab** [comment]
This issue still happened for me, I used mp4 with H 264 encoding and still get same error message.

**Comment by mister-ben** [comment]
That doesn't give much information to go on. If you've a current problem please open a new issue, making sure to fill out the issue template including a reduced test case with an example video.
