### ISSUE TITLE
Android and autorotating after fullscreen

### ISSUE THREAD

**Issue by waster** [videojs/video.js#2031]
Here is the test case with wrong behaviour in Google Chrome 41.0.2272.96 on Android 4.2.2 (4.4.4) with autorotating screen option enabled:

Source of the video is [here](http://radio-box.org/video/video-europalive.html).
1. Set mobile device in vertical orientation.
2. Click 'Play', video is playing.
3. Click ''Fullscreen', black screen appears.
4. Set mobile device in horizontal orientation, cropped video is playing.
5. Double tap to zoom, video fits to the screen width.
6. Set mobile device in vertical orientation again, video is cropped again.

Please see attached screenshots.

![screenshot_2015-04-13-21-00-36](https://cloud.githubusercontent.com/assets/2188440/7134864/bf670142-e2a9-11e4-870a-fe7562f5bdcc.png)
![screenshot_2015-04-13-21-01-26](https://cloud.githubusercontent.com/assets/2188440/7134863/bf64f898-e2a9-11e4-8119-932603c02455.png)
![screenshot_2015-04-13-21-01-42](https://cloud.githubusercontent.com/assets/2188440/7134866/bf69eaa6-e2a9-11e4-9bae-2b0dd32e4a24.png)
![screenshot_2015-04-13-21-02-27](https://cloud.githubusercontent.com/assets/2188440/7134867/bf6a3466-e2a9-11e4-91f0-a1a2b4e27d9a.png)
![screenshot_2015-04-13-21-03-49](https://cloud.githubusercontent.com/assets/2188440/7134865/bf6883fa-e2a9-11e4-8dc1-6d1b583ce523.png)
![screenshot_2015-04-13-21-05-23](https://cloud.githubusercontent.com/assets/2188440/7134868/bf6b84d8-e2a9-11e4-9149-ff036ab70c49.png)

**Comment by mister-ben** [comment]
Reproduced on videojs.com, on Chrome 41 and 42 on 4.4.4, with video.js versions 4.10+. I think it's `position:fixed` on `.video-js.vjs-fullscreen` that's doing it.

**Comment by gkatsev** [comment]
Does this still happen with videojs v5? I know it still has the `postition:fixed` on the fullscreen style.

**Comment by brianmontanaweb** [comment]
Ran into similar issue using a slightly older version but with the latest stable version it appears to be fixed.

**Comment by sahchos** [comment]
If it helps for someone... I had same issue. After change `position:fixed` to `position:absolute` and add `top:0` for `.video-js.vjs-fullscreen` everything is ok
