### ISSUE TITLE
Can’t listen on “«method» unavailable on «tech» playback technology element” error

### ISSUE THREAD

**Issue by sabberworm** [videojs/video.js#2032]
I sometimes get the following message in the console:

> VIDEOJS: Video.js: duration unavailable on Flash playback technology element. TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"}

([Source](https://github.com/videojs/video.js/blob/7f70f096218631ba1e0c62b5fd787d4897ccf62b/src/js/player.js#L663))

Followed by this error.

> Uncaught TypeError: undefined is not a function

I would love to know when this error occurs because I then have to re-initialize the player as this error leaves the player in an unusable state. I tried adding an event listener using `vjs.on('error'…` but this event isn’t fired for that particular kind of error.

This error should get dispatched to “error” event listeners. If it were possible to call `preventDefault` there to prevent [re-throwing the error](https://github.com/videojs/video.js/blob/7f70f096218631ba1e0c62b5fd787d4897ccf62b/src/js/player.js#L669), that would be even more useful.

**Comment by sabberworm** [comment]
Currently I’m monkey-patching Player.prototype.techGet to catch the error but I’d rather have a sanctioned way of doing this.

**Comment by gkatsev** [comment]
It's been awhile on this issue. Can you retest with v5?
Closing for now, but can reopen if still an issue.
