### ISSUE TITLE
Transparent Flash video with wmode and bgcolor set to transparent

### ISSUE THREAD

**Issue by Jip-Hop** [videojs/video.js#2036]
Hi, I just checked out video.js and tried to load a flv file with alpha channel and found out I couldn't change the background color of the player, neither could I see trough the player (which is what I want) because the 'wmode' is set to 'opaque' and the 'bgcolor' is set to #000000 in the video.js file under the Flash Media Controller - Wrapper for fallback SWF API section. I think it would be better to set both 'wmode' and 'bgcolor' to 'transparent'. Is there a reason for the current settings?

This issue is currently preventing me from using the cdn version.

**Comment by 02clams** [comment]
You can change these settings in the videojs development version. I set mine to transparent and it works fine. I also need transparency when viewing certain videos. Plus it allows the background around an mp4 to be transparent and thus you can set a color for it.

**Comment by dmlap** [comment]
`wmode transaparent` forces the browser to composite the SWF's display onto the DOM. This may prevent some video playback optimizations from taking place and can slow things down in general. In practice, everything may still be fast enough that you don't have to worry about it, so feel free to experiment with @02clams's solution and see if it works for you.
