### ISSUE TITLE
Window.xd instanceof test in min version

### ISSUE THREAD

**Issue by snichini** [videojs/video.js#2037]
Hello,

We encounter a problem during our testing with others javascript libraries.

We got an error raised by the setting and testing of the TOUCH_ENABLED property of videojs in the min version of videojs (4.12.5).

```
Uncaught TypeError: Expecting a function in instanceof check, but got #<HTMLDocument>
```

in the dev version we have in the 4.12.5 on line 1108:
```javascript
vjs.TOUCH_ENABLED = !!(('ontouchstart' in window) || window.DocumentTouch && document instanceof window.DocumentTouch);
``` 

In the min version on line 17:
```javascript
t.Eb=!!("ontouchstart"in window||window.xd&&document instanceof window.xd);
```
The dev version works well because test property DocumentTouch is not override by the other javascript libraries.

In the min version, the "window.DocumentTouch" is changed to "window.xd".
We also could not understand where the "window.xd" was set in the code or maybe it's a known alias for the DocumentTouch property.
Anyway, the problem here is that there is no test on the nature of window.xd. And "instanceof" accepts only a "function" type to test against.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

So we added the typeof function to ensure the nature of window.xd: 
```javacript
typeof window.xd == "function"
```

So we have now this for the min version : 
```javascript
t.Eb=!!("ontouchstart"in window||window.xd&&typeof window.xd == "function" && document instanceof window.xd);
```
and for the dev version :
```javascript
vjs.TOUCH_ENABLED = !!(('ontouchstart' in window) || window.DocumentTouch && typeof window.DocumentTouch == "function" && document instanceof window.DocumentTouch);
```

Maybe we are wrong but I think this ensure a better testing of this window property
This fix helps us using the min version of videojs and solve the problem.

Thanks !

**Comment by gkatsev** [comment]
This is a minifcation issue. What happens is that Closure Compiler's advanced compliation mode that we currently use mangles all dot-accessed names. So, `window.DocumentTouch` gets changed to `window.xd` even though we don't want it to. We probably should release a patch for the current version that updates this line to read:
```js
vjs.TOUCH_ENABLED = !!(('ontouchstart' in window) || window['DocumentTouch' && document instanceof window['DocumentTouch']);
```
Also, we're removing Closure Compiler and using uglify in a forthcoming version of videojs, so, hopefully, we won't have this issue in the future.

**Comment by snichini** [comment]
Ok great news.
I'm glad to read it.

**Comment by gkatsev** [comment]
I'm going to leave this open to hopefully remind us to make that patch. Though, if you want to send a PR our way with this change, that would be awesome (preferably, against the `stable` branch).

**Comment by gkatsev** [comment]
Going to close this since we shouldn't ever have this issue in v5 anymore.
