### ISSUE TITLE
Getting a Javascript error in IE8: 'this.tech is null or not an object'

### ISSUE THREAD

**Issue by tinwatchman** [videojs/video.js#2041]
So I've been having trouble going to the Flash Player in IE8. Finally got a virtual machine set up, and wound up getting this error on page load:

![videojs_javascript_error_4-15-2015](https://cloud.githubusercontent.com/assets/480204/7168372/ee81a112-e38a-11e4-956a-98edc19b3ba3.png)

Here's what my embed code / options looks like (note that I'm using [require.js](http://requirejs.org/) to load the library):

```
require(['main'], function () {
	require(
		[
			'videojs'
		],
		function(videojs) {
			videojs.options.flash.swf = "/stout/public/lib/VideoJS/video-js.swf";
			videojs("fragment-124__video",
				{
					"controls": true,
					"width": 576,
					"height": 324,
					"poster": "http://srv-td1/stout/public/img/bill.png",
					"autoplay": true,
					"loop": false,
					"preload": "metadata",
					"language": "en",
					"techOrder": ["flash", "html5"]
				},
				function() {
					// player should be ready
				}
			);
			jQuery("#fragment-124__video_container").show();
		}
	);
});
```

**Comment by gkatsev** [comment]
Are you using one of the VMs from modern.ie? If so, they don't ship with the flash player installed, so, that could  be a reason for the issue.
Another issue I can think off is that you're showing the video element with jquery after videojs is initialized. Flash really doesn't like that.
Hopefully, one of the above addresses the issue, if not, let us know :)

**Comment by tinwatchman** [comment]
Ah. Well, installing Flash on the Modern.ie virtual machine seems to have resolved this particular error. I'm now getting an entirely different error instead. I'll close this issue, but if this screen capture of the error looks familiar to you, I'd appreciate it if you could let me know:

![definepropertyscreencap](https://cloud.githubusercontent.com/assets/480204/7170032/a817a556-e398-11e4-8aaf-6309881c0bbd.PNG)
