### ISSUE TITLE
Listen to all fullscreenchange events

### ISSUE THREAD

**Issue by ThomasMorrison** [videojs/video.js#2042]
Currently `isFullscreen()` only reports `true`/`false` depending on if the players fullscreen is toggled via video.js functions. 

If you were to set the player to fullscreen via another method/script, `isFullscreen()` incorrectly reports false. This is present specifically with the [Youtube Plugin](https://github.com/eXon/videojs-youtube) as double clicking a youtube iframe enters fullscreen mode (but youtube gives no events to hook into).

I don't think this should be resolved in the Youtube plugin repo as this has the potential to help other such scenarios where the shown content enters/leaves fullscreen.

**Comment by eXon** [comment]
I think we can fix it within video.js if we listen for fullscreen events on the page. However, the problem we might face is if we have multiple player on the same page. How do you know which one is the one fullscreen?

See http://stackoverflow.com/questions/9621499/fullscreen-api-which-events-are-fired

**Comment by gkatsev** [comment]
I think this has been handled in v5: https://github.com/videojs/video.js/blob/6bbd6f1a65d49566900a6d52979d4c9e10ea7fc4/src/js/player.js#L557
