### ISSUE TITLE
Fails to play video on Samsung / HTC Default Android Browsers (4.3/4.4.2/4.1.2/4.4.3)

### ISSUE THREAD

**Issue by zrehmani** [videojs/video.js#2044]
Video loads and plays fine on Chrome but when I try to play the video on the Android Default Browser - even from the videojs site - what I see is a gray screen, loader spinning and then a flash of pause sign.  I have to press the play on the control bar and the player immediately pauses again (flashing pause sign).  I press it again - it pauses again.  I keep doing this a few times and then eventually it starts to play normally.  The same behavior is exhibited on Samsung 3 (Android 4.3), HTC One M7 (Android 4.4.2), Samsung 3 (Android 4.1.2), Samsung 3 (Android 4.4.3).  Any help would be much appreciated.

**Comment by freechelmi** [comment]
You confirm those 3 videos loads fine immediatly on those browsers? 

http://ie.microsoft.com/TEStdrive/Graphics/VideoFormatSupport/Default.html

**Comment by zrehmani** [comment]
Thank you for your response!  Tested and all three videos loaded and played on Samsung 3 (Android 4.3) and Samsung 3 (Android 4.4.2) and Samsung 3 (Android 4.1.2) default Android browsers.  Also in the last device, webm version sound and video was choppy.  HTC One M7 was recently upgraded from Android 4.4.2 to latest Android 5 which resolved the issue on that device.  Another HTC One M7 with Android 5 also works fine.  Tested also on Samsung 5 with Android 5 and that also works fine.

**Comment by zrehmani** [comment]
I just want to make sure I am clear that with Android version 5 - the original issue (videojs not loading and playing the video as expected) on default Android browser - is fixed.  The issue is on devices (Samsung, HTC) with variation of Android version 4.

**Comment by gkatsev** [comment]
In vjs 5, we've updated to default to the native controls on native browsers: https://github.com/videojs/video.js/pull/2499
Closing for now, but can reopen if still an issue.
