### ISSUE TITLE
how to get 3GP video compatbile 

### ISSUE THREAD

**Issue by ychoucha** [videojs/video.js#2049]
Hello, 

my phone make HD video but in 3GP format.

so how i can show him in videojs PLease ?

**Comment by odev79** [comment]
With iPodme software you can convert your video to mp4 :)

**Comment by odev79** [comment]
This is the link https://nodadev.wordpress.com/pc-projects/ipodme/

**Comment by ychoucha** [comment]
hello thanks.

i found a better way : 

just with this command u can convert 3GP video on mp4 compatible with videoJs

avconv -i VID_20150418_141227.3gp -acodec copy test.mp4


now i have to found a way to add it on the humhub framwork to make automatly when a user upload a 3gp video and that's would be cool

**Comment by heff** [comment]
You can always use [Zencoder](https://zencoder.com/) to automate the process. :)

Closing since this appears to be answered and doesn't require any changes.
