### ISSUE TITLE
Video.js player not working for my site.

### ISSUE THREAD

**Issue by singhjan** [videojs/video.js#2050]
I have used CDN Version and included in head.

but player is not shown correctly. and the video is also not playing. My Site Link: http://videos.sunnyleone4u.com/2015/04/18/yeeee/

   Help me Pliz.

**Comment by heff** [comment]
It's working for me.

![screen shot 2015-04-20 at 12 04 30 pm](https://cloud.githubusercontent.com/assets/166/7238200/7b230692-e755-11e4-83be-7e06fe28b7db.png)

If you're still seeing the issue can you provide more information about the problem and which browser you're seeing it in?

**Comment by singhjan** [comment]
Now , the player is working fine. Recently I have added resolution selector and It is working . But resolution selector is not shown in menu bar but can be found when mouse keep near volume menu.

Tell me how to keep seeing resolution button in menu bar ?

**Comment by mister-ben** [comment]
It doesn't look you have CSS to add an icon to that button. For help with a specific plugin, you'll get better help on the plugin's own repository.

**Comment by singhjan** [comment]
I have CSS and i donot know why is is not working.

Pliz Check my css:

@charset "utf-8";

/*
You are free to style the button however you wish. I plan to use
an icon from my site's own icon font to make it more visible. These
are just basic styles to make it look ok with plain text.
*/

/* Position the button */
.vjs-res-button {
    float: right;
    line-height: 3em;
}

/* Don't show hover effects on title */
ul li.vjs-menu-title.vjs-res-menu-title:hover {
    cursor: default;
    background-color: transparent;
    color: #CCC;

    -moz-box-shadow: none;
    -webkit-box-shadow: none;
    box-shadow: none;
}

/* Needed to keep text visible in video.js 4.9 */
.vjs-res-button .vjs-control-text {
    width: auto;
    height: auto;
    clip: auto;
}

**Comment by singhjan** [comment]
@mister-ben , Could you check my CSS above and tell me pliz, why is not working . The Above CSS is for resolution plugin.

**Comment by mister-ben** [comment]
Reading the comment in that CSS, the plugin author has left it to you to add a button icon. The approach approach in the standard skin is to use a font icon, e.g. for the play button:

    .vjs-default-skin .vjs-play-control:before {
      content:"\e001"
    } 

There's a cog icon in the video.js font at `\e600` which may suit you here.

**Comment by singhjan** [comment]
I have added your given css code and it is not still working.

**Comment by singhjan** [comment]
@mister-ben.  I have added your given css code and it is not still working.
