### ISSUE TITLE
Resolution selector button unseen in Video.js menu bar

### ISSUE THREAD

**Issue by singhjan** [videojs/video.js#2051]
Recently I have added resolution selector and It is working . But resolution selector is not shown in menu bar but can be found when mouse keep near volume menu.

Tell me how to keep seeing resolution button in menu bar ?

I have CSS and i donot know why is is not working.

Pliz Check my css:

@charset "utf-8";

/*
You are free to style the button however you wish. I plan to use
an icon from my site's own icon font to make it more visible. These
are just basic styles to make it look ok with plain text.
*/

/* Position the button */
.vjs-res-button {
    float: right;
    line-height: 3em;
}

/* Don't show hover effects on title */
ul li.vjs-menu-title.vjs-res-menu-title:hover {
    cursor: default;
    background-color: transparent;
    color: #CCC;

    -moz-box-shadow: none;
    -webkit-box-shadow: none;
    box-shadow: none;
}

/* Needed to keep text visible in video.js 4.9 */
.vjs-res-button .vjs-control-text {
    width: auto;
    height: auto;
    clip: auto;
}
…
@singhjan
singhjan commented 10 minutes ago

Pliz check my CSS above and tell me pliz, why is not working . The Above CSS is for resolution plugin.

**Comment by singhjan** [comment]
My Site link is http://videos.sunnyleone4u.com/2015/04/18/yeeee/.
Resolution button pop out  when mouse cursor is near to volume menu. I want to show button in menu with 360p as default

**Comment by heff** [comment]
The resolution button isn't adding an icon for itself. Try adding `.vjs-res-button { content:"\e006" }` and you should see the volume icon. I'm not sure what the resolution plugin should be doing though so you'll need to post on that project.

**Comment by singhjan** [comment]
@heff  I am using dominic-p/videojs-resolution-selector - https://github.com/dominic-p/videojs-resolution-selector.

Pliz Check out ?

**Comment by heff** [comment]
You should really submit this issue on the plugin.
