### ISSUE TITLE
Resolution selector button unseen in Video.js using dominic-p/videojs-resolution-selector

### ISSUE THREAD

**Issue by singhjan** [videojs/video.js#2059]
Recently I have added resolution selector ( dominic-p/videojs-resolution-selector - https://github.com/dominic-p/videojs-resolution-selector) and It is working . But resolution selector is not shown in menu bar but can be found when mouse keep near volume menu.

Tell me how to keep seeing resolution button in menu bar ?

I have CSS and i donot know why is is not working.

Pliz Check css:

@charset "utf-8";

/*
You are free to style the button however you wish. I plan to use
an icon from my site's own icon font to make it more visible. These
are just basic styles to make it look ok with plain text.
*/

/* Position the button */
.vjs-res-button {
float: right;
line-height: 3em;
}

/* Don't show hover effects on title */
ul li.vjs-menu-title.vjs-res-menu-title:hover {
cursor: default;
background-color: transparent;
color: #CCC;

-moz-box-shadow: none;
-webkit-box-shadow: none;
box-shadow: none;

}

/* Needed to keep text visible in video.js 4.9 */
.vjs-res-button .vjs-control-text {
width: auto;
height: auto;
clip: auto;
}

**Comment by mmcc** [comment]
Since this is an issue with a plugin and not core, this should be opened on the [plugin repo](https://github.com/dominic-p/videojs-resolution-selector)
