### ISSUE TITLE
Make player.tech a private property

### ISSUE THREAD

**Issue by heff** [videojs/video.js#2060]
player.tech should have always been a private property, but now that we're not mangling vars it's especially important to call that out.

Just want to make sure this happens for 5.0.

**Comment by gkatsev** [comment]
We probably want to renamed *all* properties into `_propName` except the ones that we know for sure should be exported. We could always change that in minor updates later on or as we work more towards 5.0.

**Comment by heff** [comment]
Agreed

**Comment by eXon** [comment]
You guys were already using stuff like `player.el_` for the mangled stuff. Maybe we could continue with that syntax and switch what makes sense.

**Comment by heff** [comment]
Yeah, we should continue with the trailing underscore until we decide to switch everything over at once to the preceding underscore for private vars.

**Comment by nickygerritsen** [comment]
So I was reading this issue "by accident" and I have a question related to it.

As you might have read in other issues, we are creating a quality switching component. However, we also support adaptive sources.

Now we really prefer the HTML5 tech and adaptive sources, so our plan was something like this:
* Check if the HTML5 tech can play any of the adaptive sources for a given "item"
* If so, use that as a source
* If not, use our quality switching plugin for "progressive" sources

In this way HTML5 is always preferred and Flash fallback is almost never needed.

I was thinking about doing this using `player.tech.canPlaySource` (assuming techOrder starts with HTML5).

However if player.tech becomes private, what would be the best way to do something like this?

**Comment by heff** [comment]
@nickygerritsen You could use `videojs.getComponent('Html5').canPlaySource` (in 5.x). Is that enough?

**Comment by nickygerritsen** [comment]
Yes :)
