### ISSUE TITLE
Subtitles button does not show up on iOS native player

### ISSUE THREAD

**Issue by Aratramba** [videojs/video.js#2062]
I cannot seem to get subtitles working on IOS. The only way I can get IOS to show the subtitles button in the native player is to not initialise videojs at all. 

Tested on Safari/iPhone with IOS 7.1 and 8.3 with videojs 4.1 and 4.12.

demo http://codepen.io/anon/pen/MwWGbB

1. click the video so it opens in the native player
2. check if the subtitles button shows up or not

__Screenshot of version with videojs enabled__

![4d3e027d-6585-4106-9932-da1717e0b5cc](https://cloud.githubusercontent.com/assets/580312/7297290/d1b34962-e9c7-11e4-92a8-a74defdc5599.png)

__Screenshot of videojs disabled, uses native player functionality__

![8ff09f60-4e41-445a-9cb3-e3f4d73d2cd4](https://cloud.githubusercontent.com/assets/580312/7297289/d1b0eef6-e9c7-11e4-94d0-ebb8811e7df1.png)

This might be related to or partly the same as #1904. Might be related to #1054. 
I don't think it's related to #1888 because adding the crossorigin attribute doesn't seem to make a difference.

**Comment by hxdev** [comment]
I saw that even of videojs.com the subtitle still doesn't show on all of iOS devices, sometimes I saw the subtitles button but it doesn't show any subtitles. What is going on guys?

**Comment by gkatsev** [comment]
I'm unable to reproduce this with latest versions of videojs. If it is still a problem and we get more information and a reduced test case, we will happily re-open the issue.
