### ISSUE TITLE
Can't get dynamic video to play in IE8

### ISSUE THREAD

**Issue by chrisjchrisj** [videojs/video.js#2063]
My issue yesterday was closed, and it was suggested there that I "Put something together on JSBin if you're still having trouble and we can help you debug".
Here's yesterday's closed issue: https://github.com/videojs/video.js/issues/2055 

where I replied:
"Thanks for your reply. I've corrected the closing ], thanks. I've removed the flowplayer and the data setup, and have the swf location accurately in the header, yet still no player appears in IE8. However, this isn't the same question as my StackO question that you refered to. This is self-hosted dynamically loaded videos (the SO question was about static videos - which works successfully)."

Here's the JSBin link:
http://jsbin.com/dimoko/2/edit?html,console,output
Any additional help/solution will be appreciated.

**Comment by mmcc** [comment]
We still get notifications for comments, so the conversation can continue on a closed issue.
