### ISSUE TITLE
grunt build on stable branch fails

### ISSUE THREAD

**Issue by EZWrighter** [videojs/video.js#2065]
Grabbed a clone of stable.
Did an npm install
It failed to install grunt-banner...forced install with npm install grunt-banner
attempted grunt
Failed with the following:
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module '_stream_transform'

**Comment by EZWrighter** [comment]
Woops...outdated node version causes this.  Closing.

**Comment by gkatsev** [comment]
Heh, what was the offending version?

**Comment by EZWrighter** [comment]
I don't know...I just cleaned it and grabbed stable...sorry.

**Comment by gkatsev** [comment]
No worries. If it's working now, great!
