### ISSUE TITLE
Video js issue

### ISSUE THREAD

**Issue by akhileshsingh** [videojs/video.js#2067]
Hello team,

I have used video js to play videos for all devices and browsers.

It is working fine in devices but i am not able to play video in IE11 on windows 7.

Please help me out

**Comment by mister-ben** [comment]
Some more detail including a reduced test case would help.

**Comment by mmcc** [comment]
Closing this until we get more info. Ping this issue with a [reduced test case](http://jsbin.com/axedog/latest/edit) and we can reopen.
