### ISSUE TITLE
no graphic under ie11

### ISSUE THREAD

**Issue by superchangme** [videojs/video.js#2069]
beacuse i use data-src to switch serval videos on only one videojs Obj,i can work on chrome,but ie11 has no graphic.
code like this:
~~~
$(list).on("click",function(index,item){
var poster=$(item).data("poster"),src=$(item).data("src");
videoDiv.attr("poster", poster);
videoObj.poster(poster);
videoObj.src(src);
videoObj.play();


})

~~~

**Comment by mmcc** [comment]
I'm not following, but this seems like an implementation question. I'm going to close this, but if you want to put together a [jsbin](http://jsbin.com/axedog/latest/edit) that shows that you mean I can try and help you debug.
