### ISSUE TITLE
Initialize VideoJS from dummy element using Require.js

### ISSUE THREAD

**Issue by ReNDeZOwnler** [videojs/video.js#2070]
Hi,

First of all, I explain my requirements:
- I have a dummy element to fire a video -> ```<div id="dummyElement"></div>```
- When the user clicks/taps the dummy element, a VideoJS must to be initialized and then have to play the media on most platforms.

Well, my problem is to approach this on IOS when I use [**Require.js**](http://requirejs.org)  library. This issue force the user to do **two** annoying clicks/taps to view the video.

I have made some examples from a simple example to a example with requirejs and jquery promises.
1- http://aitoraznar.com/lab/videojs/plain.html
 Simple example using HTML5 video tag
2- http://aitoraznar.com/lab/videojs/complex.html
 Example using require.js and jQuery promises
3- http://aitoraznar.com/lab/videojs/videojs.html
 Example using VideoJS
4- http://aitoraznar.com/lab/videojs/videojsComplex.html
 Example using VideoJS and require.js and jQuery promises
 
I can reproduce expected behaviour in the following devices:
* Samsung Galaxy Tab (GT-P6200) Android 3.2 - Native browser
* Samsung Galaxy Tab 2 Android 4.4 - Native browser
* LG Nexus 5 Android 5.0 - Chrome browser
* Blackberry Z10 (STL100-2) - Native browser

Detected devices where doesn't work (Primary IOS):
* iPad Mini 2 (A1489) - IOS 8.1.2 - Safari browser
* iPhone 4  (A1332)- IOS 7.1.2 - Safari browser
* Nokia E7-00 (RM-626) - Symbian Belle 3 (v111.040.1511) - Native browser (8.3) - Java 2.3 - Flash 4.0

I don't know why the 4th example (VideoJS & Require.js) is not working on IOS devices. Any help would be appreciated.
Thanks,
Aitor

P.D: Related Stackoverflow issue http://stackoverflow.com/questions/29894406/initialize-videojs-from-dummy-element-using-require-js

**Comment by mmcc** [comment]
> In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled. No data is loaded until the user initiates it. This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.

[source](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html)

**Comment by ReNDeZOwnler** [comment]
@mmcc thanks for replying. 

I do know the mobile devices limitations, specially for IOS devices. In my examples I'm trying to initialize VideoJS through a user action (click on dummy element) which is the same behaviour that Youtube has. 

I have made some examples to illustrate that I want to achieve. A simple look to the code or try the examples in Android/IOS devices will show you that the problem in sample 4 is not about user interaction.

Thanks for all.

**Comment by mmcc** [comment]
There's a lot going on in these examples, but I'm still not convinced this is a Video.js issue. I think @eXon (he responded to you on SO) and I are on the same page.

One thing that gives me pause is that Video.js examples seem to be pretty finicky between browsers.

Chrome And Safari: Seem to load VJS but no styles
![chrome](https://cloudup.com/cJDgaMEfH0O+)

Firefox: Doesn't load Video.js and the video never plays back at all
![Firefox](https://cloudup.com/c2S1-IjyZoB+)
