### ISSUE TITLE
Can't see the player at www.videojs.com main page, via IE8

### ISSUE THREAD

**Issue by chrisjchrisj** [videojs/video.js#2072]
If videojs.com player works with IE8, as you claim, how come the demo player doesn't appear when I view it via IE8 - on your www.videojs.com main page? I ask this because I've been trying to get my downloaded videojs player to appear in IE8 for over a week now, without success.

**Comment by mmcc** [comment]
@chrisjchrisj I'm pretty sure that's related to how we originally got responsive sizing to work. Video.js [works in IE8](http://jsbin.com/axedog/latest). Please stop opening tickets related to this, we've asked repeatedly for an example to help you debug. Again, we get comments on closed issues, so if you have questions related to this, please comment on one of your previous issues.
