### ISSUE TITLE
IE11 CORS HTML5 native tracks not loading

### ISSUE THREAD

**Issue by EZWrighter** [videojs/video.js#2073]
Cross domain web vtt files do not load in IE11 natively due to a bug in IE.

https://connect.microsoft.com/IE/feedback/details/817222/ie-11-unable-to-load-captions-cross-domain-with-track

This issue was originally referenced here: https://github.com/videojs/video.js/issues/1908#issuecomment-96139451

There is also a workaround in that issue for detecting IE11 and changing tracks to be emulated.

**Comment by gkatsev** [comment]
We've enabled emulated tracks always, except on iOS and Safari. https://github.com/videojs/video.js/blob/master/CHANGELOG.md#5140-2016-12-02
