### ISSUE TITLE
videojs.ready

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#2075]
I'd like to write some code that automatically configures and initializes some plugins on every player that is created in a page. It would be cool if video.js provided some way I could be notified whenever a new player was initialized.

**Comment by dmlap** [comment]
Proposal:
```js
videojs.ready(function(event) {
  console.log('created a new player:', event.player);
});
```

**Comment by heff** [comment]
Sounds good to me. We might want to name it `playerReady` or something to differentiate from `jQuery.ready()`

**Comment by gkatsev** [comment]
This has been implemented in the form of hooks.
