### ISSUE TITLE
use video-js with curl stream as source

### ISSUE THREAD

**Issue by markknochen1** [videojs/video.js#2079]
hello,

how can i use the videoJS player with a sourch from a curl-Stream?

thank you

mark

**Comment by mmcc** [comment]
I'm not sure what you mean by curl-stream ([curl?](http://curl.haxx.se/)).

I'm going to be honest, I'm totally at a loss for what you're asking. If you want to support live streams, the default flash fallback supports RTMP and there's an excellent [HLS plugin](http://github.com/videojs/videojs-contrib-hls).
