### ISSUE TITLE
Propose a solution when a 'Cannot Play' situation is reached.

### ISSUE THREAD

**Issue by freechelmi** [videojs/video.js#2090]
I'm using v4.9.0 in Piwigo but this is reproductible on a plain HTML website.

We have several cases when a browser cannot play an HTML5 video, the ones which I'd like to address first : 

1/ When only a Webm source is proposed 

- 1.1 IE9 not playing  : We should propose to install the webm codec for Mediafundation like done here : http://ie.microsoft.com/TEStdrive/Graphics/VideoFormatSupport/Default.html

- 1.2 Safari/OSX : Propose to install http://perian.org/

2/ When only a H264 source is proposed 

1.1 To be filled ....

**Comment by mmcc** [comment]
Are you referring to the message that's shown when no supported source is found? You can customize that to say whatever you'd like by overriding `notSupportedMessage` in the player options. By default, the message is:

> No compatible source was found for this video.

You could update this to show something specific to the user's browser, but by default we're being purposefully vague.

**Comment by mmcc** [comment]
So to be clear, you want to show different messages to users based on failures in specific situations? As I said in my reply, this is *not* a change we'll make to core, but you can easily specify your own error messages to contain any information you want about installing Perian or MediaFoundation.

This is an issue tracker, so we try to keep these issues specific to things that require action in the core project. Unless I'm reading your original issue wrong, this is an implementation question and not a bug, so I think this issue should remain closed. That being said, if you have questions about how to do any of this we can keep the conversation going in this thread.

**Comment by freechelmi** [comment]
Hi mmcc, I never understood why video.js shoud not care about making the video playable afterwards if it fails for current setup.

I think that something you should think about for core, at least when the solution is easy like installing a one click codec for webm support in IE9. 

Just showing 'I cannot play this' is lame. (BTW I'm seeing case when the message is not displayed at all) 

Don't you use this bug tracker for features ? Where else then ?

**Comment by EZWrighter** [comment]
As a videojs user, I would rather not have this code in the core.  I believe as long as you deliver an h264 encoded video the player should work in all modern browsers.  You can deliver multiple sources so the player even has options to choose from.  Making the player install third party cruff seems like a bad idea, with high maintenance costs.

If these are things that you want to support you could develop a plugin or even application logic that deals with this.

**Comment by mmcc** [comment]
@freechelmi As @EZWrighter said, one of the big benefits of Video.js is being able to provide an h264 source and have it work a vast majority of the time. If the browser can't play it back natively, our Flash fallback kicks in and takes care of it.

To highlight why we would *never* put messages about installing things like Perian in an error message, we had quite a bit of backlash over just telling users to install **Flash**. Because of this, we've gone the route of making those messages [easily configurable](http://jsbin.com/lafomo/1/edit), but vague by default.

If you're not seeing an error message at all, would you mind creating a [reduced test case](http://jsbin.com/axedog/latest/edit)?

**Comment by freechelmi** [comment]
@EZwrighter :what if you only serve Webm? 
This is where this would be useful. 

At least displaying a message that says to use xxxx browser to play the video would be a good start.

**Comment by EZWrighter** [comment]
@freechelmi - I have never seen a reason to just serve just that video type.  Transcoding is cheap and easy.  If you want to support lots of browsers it's easier to provide different encodings than it is to get users to jump through hoops to watch the video.

**Comment by mmcc** [comment]
Format issues aside, if the point here is the error message, I repeat, the error message is configurable. You can make it say *whatever you want*. [Here's a working example](http://jsbin.com/lafomo/2/edit?html,output).

**Comment by freechelmi** [comment]
@mmcc thanks, I understood we can configure the message, I just think that anybody using videojs should get the advantage to have solutions proposed but I understood this will never go to core.

@EZWrighter : Double encoding is not a solution for me anymore, Webm is really well supported apart from some minor mobile vendor :-) . H264 is not an option as it usually needs to illegally install some codecs on Free software platforms.

So yes we can end the discussion here, I'll do it myself then. Thanks anyway.
