### ISSUE TITLE
Cannot dispose videojs if i add a chapters track

### ISSUE THREAD

**Issue by space87** [videojs/video.js#2091]
I have created a plugin that add's markers and chapters to our video player.

if i use
 var textTrack = player.addTextTrack('captions', 'Chapters', 'en');
as a test it will dispose of the video and allow me to continue.

if i add the correct track that i attach cuepoints to for chapters

var textTrack = player.addTextTrack('chapters', 'Chapters', 'en');

if i do this then when i go to dispose of the video it crashes and i get this error message

**Comment by space87** [comment]
Uncaught TypeError: Cannot read property 'vdata1430317748204' of null

i followed the error down and it seems to break because this.el() in the trigger function is null.

and it happens one the component after the first video-js-title

**Comment by gkatsev** [comment]
I wonder if it's been fixed in a recent version of videojs.

**Comment by gkatsev** [comment]
Should be fixed in latest videojs 5.
