### ISSUE TITLE
Captions Settings not show in Chrome

### ISSUE THREAD

**Issue by alobimday** [videojs/video.js#2108]
Captions Settings not show in Chrome but in Firefox

**Comment by heff** [comment]
The captions settings don't show in chrome because we're using the built-in captions support in chrome, not the video.js custom captions. You'd instead be looking for Chrome's captions settings to customize them.

**Comment by OptimusKrish** [comment]
@heff Is it possible not to list or build the captions settings options in the caption menu using scripting (Not by css) by passing any flag like  'captions setting': false to the tracklist.

This is how I currently build caption dynamically in my video player.
var tracklist = $scope.mediaPlayer.addRemoteTextTrack({
          "kind": 'captions',
          "language": '',
          "label": '',
          "default": true,
          "src": 'path'
        });
Thanks in advance for your help :-)

**Comment by gkatsev** [comment]
You can tell the html tech to not use native captions by passing in the `nativeTextTracks` option:
```js
var player = videojs('video', {
  html5: {
    nativeTextTracks: false
  }
});
```

**Comment by OptimusKrish** [comment]
@gkatsev By using the above mentioned code the captions settings got displayed in chrome browser also. But my requirement is not to build or list that option at all in all browsers.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/7058950/12162476/a1743928-b528-11e5-8060-9c2c56558297.png)

**Comment by gkatsev** [comment]
Oh, I see. You want the opposite. No, there isn't a way of doing it.

**Comment by OptimusKrish** [comment]
Oops!Then I have no other option but to use CSS to hide it. Thanks!!!
