### ISSUE TITLE
Insert Button in Player?

### ISSUE THREAD

**Issue by carbos10** [videojs/video.js#2110]
I want to add a button for change quality of my video... How i can do it?

**Comment by Manbearpixel** [comment]
@carbos10 Hey, I would recommend you check out the known plugins for VideoJS through the VideoJS Wiki page: https://github.com/videojs/video.js/wiki/Plugins

The particular one you might be looking for is: https://github.com/vidcaster/video-js-resolutions

Hope this puts you in the right direction! Cheers ~
