### ISSUE TITLE
Hit-area on progress control is small

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#2117]
In the 5.0 skin, the hit area for the unplayed portion of the progress bar is just the 5-10px of the progress indicator itself. As a result, it can be a bit tricky to seek forward unless you grab the playhead control. Making the entire height of the control bar clickable over the progress control would make it easier to scrub.

**Comment by heff** [comment]
Yeah, I think that could be possible.


-- 
Sent from mobile

**Comment by mmcc** [comment]
I agree, I noticed this when I was showing someone the skin over the weekend.
