### ISSUE TITLE
Unable to Seek Video Embedded inside Reveal JS

### ISSUE THREAD

**Issue by abhinandankothari** [videojs/video.js#2119]
For my use-case, I have embedded video using VideoJS inside revealJS - http://lab.hakim.se/reveal-js presentation.
Everything is working fine but i am unable to seek the video.

OS: MacOSX 10.10.3
Browser: Chrome 42.0
VideoJS : Latest version
RevealJS : Latest Version

**Comment by mmcc** [comment]
That's strange, I've used VJS with Reveal.js and haven't noticed any issues. I do remember having a problem with Reveal's *extremely* aggressive global styling of everything within `.reveal`, so you might need to add some vjs specific CSS overrides to get rid of their cruft within the `.video-js` div.
