### ISSUE TITLE
How to play live streaming through wowza streaming server

### ISSUE THREAD

**Issue by shivamg705** [videojs/video.js#2120]
Hi,

Can you explain how to play live streaming through wowza streaming server in videojs.I appreciate you help.

**Comment by mmcc** [comment]
Are you trying to use HLS or RTMP? If HLS, you might want to use something like [videojs-contrib-hls](http://github.com/videojs/videojs-contrib-hls). If RTMP, we support it via our Flash fallback, you just need to specify the correct mime type.
