### ISSUE TITLE
Issue with https and live streaming

### ISSUE THREAD

**Issue by sobytes** [videojs/video.js#2122]
Hi All,

there seems to be a issue with live streaming over https.

Example over non https domain works.
~~~
<video id="video-5547ec62db367" class="video-js vjs-default-skin" controls preload="none" width="640" 
					      data-setup='{"techOrder": ["flash"]}'>
					    <source src="http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8" type="video/mp4" />
					</video>
~~~

But over a https domain this will fail with the error.
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) FLASH: srcnotfound 

If i change the stream url to https 
~~~
<video id="video-5547ec62db367" class="video-js vjs-default-skin" controls preload="none" width="640" 
					      data-setup='{"techOrder": ["flash"]}'>
					    <source src="https://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8" type="video/mp4" />
					</video>
~~~

No error load but doesn't play any suggestions?

Thanks

**Comment by EZWrighter** [comment]
I never get a response when attempting to connect to your https server: https://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8

However, I have also tried to get hls live streams working with videojs and it never seemed to work.  This is the national park service live stream of Old Faithful: http://cs3.pixelcaster.com:1935/live/faithful.stream/playlist.m3u8

Maybe with these couple of testing points something can be resolved.  I just never had time to dig in and figure it out.

**Comment by mmcc** [comment]
@EZWrighter Were you trying to use the old faithful stream along with the [videojs-contrib-hls plugin](http://github.com/videojs/videojs-contrib-hls)? If so, that probably didn't work because it doesn't look like it has CORS headers

    * Hostname was NOT found in DNS cache
    *   Trying 67.212.233.188...
    * Connected to cs3.pixelcaster.com (67.212.233.188) port 1935 (#0)
    > GET /live/faithful.stream/playlist.m3u8 HTTP/1.1
    > User-Agent: curl/7.37.1
    > Host: cs3.pixelcaster.com:1935
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Date: Tue, 05 May 2015 15:45:16 GMT
    < Content-Type: application/vnd.apple.mpegurl
    < Accept-Ranges: bytes
    * Server FlashCom/3.5.7 is not blacklisted
    < Server: FlashCom/3.5.7
    < Cache-Control: no-cache
    < Content-Length: 139

Using it in Safari (native playback support) seems to [work fine](http://jsbin.com/donace/1/edit?html,output), but the lack of CORS headers means we can't grab the manifest via JS (which the plugin requires).

@sobytes As the previous comment states, it looks like the url you're trying isn't available via https. Also, just a note, make sure you use the correct mime type (application/x-mpegurl instead of video/mp4) for HLS.

**Comment by EZWrighter** [comment]
@mmcc - That is exactly what I tried...dang those CORS headers :-(  Thanks for taking a peek.

**Comment by sobytes** [comment]
Hi All,  thanks for the feedback just to check it wasn't the stream url with https that was causing the issue it works fine on any non https domain but if i had the player on a page with a https domain that seemed to cause the issue.

I am using this hls plugin for videojs.
http://www.flashls.org/videojs/flash_demo.html

Is this the best option for HLS streaming?

Thanks for the update on the mime type should have spotted that.

**Comment by mmcc** [comment]
@EZWrighter *shakes fist at CORS* Gets me all the time, no worries :)

@sobytes You're probably running into the issue of [Mixed Content](https://developer.mozilla.org/en-US/docs/Security/MixedContent). If you're trying to load an insecure source on a secure page, the insecure source is frequently blocked altogether (depending on the browser).

**Comment by mmcc** [comment]
@sobytes to answer your question, we have our own plugin called [videojs-contrib-hls](http://github.com/videojs/videojs-contrib-hls), but I've heard great things about Flashls.
