### ISSUE TITLE
Progress bar doesn't work with self hosted video

### ISSUE THREAD

**Issue by AdvAliGames** [videojs/video.js#2134]
When i use my on video, I can't rewind movie, but When I use for example this: http://video-js.zencoder.com/oceans-clip.mp4 all works great. This is my code:

https://gist.github.com/AdvAliGames/67893518138ec2642659

**Comment by heff** [comment]
Sounds like a video file issue to me. You might try a different encoder. You could try running it through [zencoder](https://zencoder.com/en/).
