### ISSUE TITLE
How should I integrate video.js in meteor?

### ISSUE THREAD

**Issue by Billybobbonnet** [videojs/video.js#2140]
Hello,

I am looking for a reference or an example of how to integrate video.js in a meteor application. I don't want to use a package since I plan to add plugins to video.js.

Here are the elements I understood (correct me if I'm wrong):

  - video.js should be loaded in client/compatibility folder in order to be loaded first
  - It seems a script and style elements must be created. See: https://github.com/GitYong/meteor-videojs/blob/master/yong:meteor-videojs.js
  - On the page where the video.js player is, it is necessary to load it from js since we are in a dynamic HTML context.

A couple of questions:
  - Is there an easy way to change the lang and font path?
  - Are all the files in the video.js download mandatory for using it (except the demo files I guess)?

All feedbacks on a video.js integration in meteor are welcome.

Thank you for your help.

**Comment by mmcc** [comment]
I'm not terribly familiar with the Meteor world, but most of these questions seem like they could be pretty generic to using external client side libraries with Meteor. Yes, you have to include the Video.js script and styles, but however you want to do that is up to you (and Meteor).

To change the font path, you need to override the CSS styles, either by editing the CSS file or by importing the fonts yourself elsewhere. You need: video.js, font files, and the stylesheet.

All this being said, a quick glance at the Meteor docs says you should try and use a "smart package" (-_-), which it looks like @GitYong already built for you. Might be best to ping him for advice for Meteor-specific things?

**Comment by Billybobbonnet** [comment]
@mmcc thanks for taking the time to answer. I am already using the package made by @GitYong you refered to but I'd rather do it myself, just to understand meteor better. I'll probably fork it and remove the errors (see: https://github.com/GitYong/meteor-videojs/issues/4#issuecomment-101262320).

By the way, I love the video.js player. You, @heff and the others made an awesome work. 

I plan to invest a significant amount of time on it, try to make the [video record plugin] (https://github.com/collab-project/videojs-record) made by @thijstriemstra record indefinitely by sending chunks on server and encode them on the fly, and adapt it to video analysis (frame-by-frame, tags on timeline, "extract" chuncks using a pseudo record button, etc.). 

I am not sure of how it will go, but if i achieve anything worth contributing, I will.

**Comment by mmcc** [comment]
@Billybobbonnet Totally understandable, just curious. Thank you for the kind words, we look forward to hearing back about your findings. :)

If you wanted to put together a guide on using Video.js with Meteor we'd *love* to have something like that on our wiki. Please keep us in the loop on your progress!

**Comment by Billybobbonnet** [comment]
I just created a small guide in the wiki. I'm not sure if it fits your requirements and it is definitely not perfect, but i would have love to find that two days ago :smile: 

You can read it here:
https://github.com/videojs/video.js/wiki/Integrate-video.js-in-meteor

**Comment by heff** [comment]
Awesome!
