### ISSUE TITLE
Is there any way to jump to the next chapter in the video.

### ISSUE THREAD

**Issue by chaitanyapro** [videojs/video.js#2141]
So I've defined all the chapters and everything is working fine is there any api method to jump to the next chapter in the video.

**Comment by space87** [comment]
Hey chaitanyapro,

you can use the built in chapters menu that appears as a icon on the control bar, or just take the start time of each chapter and store them and use the currentTime() method to set to the time of the chapter when a button is clicked

**Comment by OwenEdwards** [comment]
Seems like a great opportunity for a simple plug-in feature!

**Comment by tmm1** [comment]
I've written a simple plugin for this at https://github.com/fancybits/videojs-chapter-nav, but it requires #4326 to function reliably.
