### ISSUE TITLE
Player not being responsive

### ISSUE THREAD

**Issue by dschinkel** [videojs/video.js#2146]
Here's my code, the player is not responsive meaning if I shrink the browser, it's not resizing inside my div appropriately.  My div is cutting off the player which has a fixed height and width.  I tried taking off the fixed height and width in the controls but same deal, same results.

as you can see I'm also using bootstrap

```
<div class="col-sm-9 well">
    <div class="row">
        <div class="col-sm-12">
            <div class="media">
                <p><h1><%= string.Format( "#{0} - {1}", ViewData.Model.Number, ViewData.Model.Name ) %></h1></p>
                <div class="media-body">
                    <p>
                        <video id="<%=ViewData.Model.Name%>" class="video-js vjs-default-skin"
                            controls preload="auto" width="1280" height="720"
                            poster="../../images/CastThumb_Large.png"
                            data-setup='{"autoplay": false, "preload": "auto"}'>
        
                            <source src=<% = ViewData.Model.FileName %> type='video/mp4' />
                        </video> 
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
```

I have even taken the step to trim all markup and just included the video player in the page alone inside a div.  I know that this player was definitely being responsive in the past but seems like now, it's just not working in that respect even when I put it alone in a page!

**Comment by dschinkel** [comment]
Resolved.  But I could have sworn this control was being responsive before this..maybe not.

I just added that padding and height per the article http://alistapart.com/article/creating-intrinsic-ratios-for-video/ to the containing div and it's working now, it's responsive in size.

**Comment by dschinkel** [comment]
related blog post I put up: http://code-zest.blogspot.com/2015/05/setting-up-videojs-with-intrinsic-ratios.html

**Comment by heff** [comment]
We're just about to merge #1952, which which will make this possible by default in version 5.0.
