### ISSUE TITLE
Can't load swf player with videojs#5.0.0-14 

### ISSUE THREAD

**Issue by LeleDev** [videojs/video.js#2148]
I can't load anymore the swf player with the script
```
videojs.options.flash.swf = "bower_components/videojs/dist/video-js.swf";
```
(error: Uncaught TypeError: Cannot read property 'flash' of undefined)

nor with

```
videojs.setGlobalOptions({
  flash: {
    swf: 'bower_components/videojs/dist/video-js.swf'
  }
});
```
(error: Uncaught TypeError: Cannot read property 'mergeOptions' of undefined)

How to solve this issue?

Thank you in advance

**Comment by gkatsev** [comment]
Interesting. I wonder why. Could you post a reduced test case on jsbin?
Also, is there a particular reason you're using the prerelease of 5.0? How are you getting videojs?
Thanks.

**Comment by LeleDev** [comment]
Sorry I'm a little busy to post a jsbin at the moment...

There's no particolar reason I'm using the prerelease, and I'm getting videojs from bower

**Comment by heff** [comment]
Ugh, does bower default to the latest prerelease tag??

**Comment by LeleDev** [comment]
Bower marks that version as the latest... some weeks ago the latest was 4.12.5 instead

**Comment by gkatsev** [comment]
Yeah, latest is 4.12.6. The 5.x releases are still pre-release, hence the build numbers.

**Comment by mmcc** [comment]
What version of Bower are you using? This appears to [have been fixed](https://github.com/bower/bower/issues/782)

**Comment by LeleDev** [comment]
I'm using bower v1.4.1

**Comment by LeleDev** [comment]
Mind that I've see the latest version from "bower list" command, but I triggered by hand the upgrande writing: bower install videojs#5.0.0-14

**Comment by heff** [comment]
Ok cool, thanks for clearing that up.

**Comment by LeleDev** [comment]
Still no way to embed the swf player on v.5?

**Comment by heff** [comment]
It should be fixed now.

**Comment by LeleDev** [comment]
Mmh I'm getting the same error on rc2

**Comment by LeleDev** [comment]
Same on 5.0.0-rc.24 ...what is the proper method to embed the sfw fallback player on video.js v5?

**Comment by heff** [comment]
At this point we've re-added the `videojs.options` object in 5.0, so this error shouldn't be happening any more. Essentially nothing has changed from 4.x now. So if it's still happening for anyone we need to set up a reduced test case to figure it out.

**Comment by heff** [comment]
I'm going to close but will reopen if it's still happening.

**Comment by LeleDev** [comment]
It seems ok now
