### ISSUE TITLE
Incorect image of Buttons?

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#2153]
Hi! Incorect image Buttons : http://2sub.ru/drama/9-4.html
I can't understand why? Help please guys!

**Comment by gkatsev** [comment]
Make sure you've included the font-icons. They should be in the `font/` directory available in the download. If you check your console, it complains that it can't find the fonts.
Going to close this as that's most likely the issue but feel free to keep commenting if you're having trouble with getting the fonts working.

**Comment by surikat1978** [comment]
Oh, thanks for the help brother! That I'm a fool, I thought that the work involved only three files video.js, video-js.css and video-js.swf. Forgot upload folder  font & lang //  I'm sorry!  Very Thanks!
