### ISSUE TITLE
Keyboard accessibility of control bar menus (e.g. captions, subtitles, etc)

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#2155]
In #1932, @heff wrote:

>we already support both spacebar and enter on our div buttons

That's true for buttons, but the way that menus are handled means that they are not keyboard accessible. Click propagation is prevented through the Menu component, but keyboard interaction is not, so, for example, pressing Enter on the captions button effectively clicks on the top menu item (often 'captions setting'), and pressing Enter on one of the other menu items doesn't behave correctly. (Actually clicking on the menu button, rather than a menu item, seems to select the top menu item, which is a weird behavior).

Menus ought to work like [W3C 'using ARIA menus'](http://www.w3.org/WAI/GL/wiki/Using_ARIA_menus), and the [OAA Accessibility Menubar example](http://oaa-accessibility.org/examplep/menubar1/). See also [Recommended WAI-ARIA implementation for navigation bar/menu on StackOverflow](http://stackoverflow.com/questions/12279113/recommended-wai-aria-implementation-for-navigation-bar-menu).

**Comment by OwenEdwards** [comment]
Note that we're talking about several distinct menus here rather than a 'menubar'. The biggest change needed is to support keyboard navigation of the menu widget's items (Up arrow, Down arrow, Enter, Space, Escape).

The next step would be to pass extra information when adding menu items so that the items can be distinguished with ARIA (and, potentially, in the CSS/skin) as either the [title of the menu](https://github.com/videojs/video.js/blob/master/src/js/menu/menu-button.js#L54) (which is a little redundant right now, since the menu title is handled as both the [button name](https://github.com/videojs/video.js/blob/master/src/js/button.js#L41) and also as a specific [ARIA label](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/captions-button.js#L14)), as one of a set of effectively radio buttons (e.g. different languages of captions, of which only one can ever be 'select'ed), or as a [control which brings up another control](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/captions-button.js#L41).

**Comment by OwenEdwards** [comment]
Another great resource is http://hanshillen.github.io/jqtest/#goto_menubar. Also, see http://hanshillen.github.io/jqtest/#goto_button for a combination of buttons and a 'button group'; the video.js Control Bar is a similar mix of buttons and other control widgets.

**Comment by gkatsev** [comment]
Fixed by #3033.
