### ISSUE TITLE
PlaybackRates and wrong html code

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#2157]
Good day!  Why is the default code :  data-setup='{"playbackRates" : [0.5, 1, 1.5, 2] }'    ?
After all, it works only in browsers such as:  data-setup="{quot;playbackRatesquot; : [0.5, 1, 1.5, 2] }"       Interesting?

**Comment by heff** [comment]
I don't follow. Whats the difference?

**Comment by surikat1978** [comment]
'{"  vs  "{   
 editor Tinymce helped me only and would not know how to work the correct code in the browser.
I put it '{"   in simple text, and it did not work
Now all Ok!

**Comment by mmcc** [comment]
`data-setup='{"playbackRates": [0.5, 1, 1.5, 2] }'` is correct, so this seems like something weird going on with tinyMCE.
