### ISSUE TITLE
Move CDN logic into its own repo, version the swf separately on the CDN

### ISSUE THREAD

**Issue by heff** [videojs/video.js#2159]
Having the CDN deployment inside the main repo complicates a bunch of things and it seem like a natural place to separate out some logic.

- Pushing to [hosting](https://github.com/videojs/video.js/blob/master/grunt.js#L99) and purging the CDN
- Updating the [SWF](https://github.com/videojs/video.js/blob/dc083f8cf44821dea3548f1173f4e3c8080f13db/src/js/video.js#L94) and [font](https://github.com/videojs/video.js/blob/master/build/tasks/dist-cdn.js#L12) urls
- Adding the (optional) [analytics](https://github.com/videojs/video.js/blob/master/build/cdn.js)

Along with this I think we should separate the fonts into their own module. The fonts are already versioned separately on the CDN.
We should also version the SWF separately on the CDN so we can share swf versions across minor video.js versions.

**Comment by dmlap** [comment]
+1

**Comment by mmcc** [comment]
All of this seems great to me, but I'd like to sit down and talk about the implications here. Particularly the font seems like it could be a bit tricky in terms of coordination (and I see similar tradeoffs to moving the whole default theme to its own repo).

**Comment by mmcc** [comment]
Just chatted about this with @heff IRL. Regarding the font stuff, we're going to move the font partial out of the main repo along with the font files, then import that into the base theme. It will still require a rebuild on the main lib, but that still feels like a better separation.

**Comment by gkatsev** [comment]
Dependencies ftw!
This also makes it easier for someone to use the vjs-font if they only care about that :D

**Comment by heff** [comment]
Closed by #2230
