### ISSUE TITLE
I'm not able to reproduce subtitles 

### ISSUE THREAD

**Issue by gregory0219998** [videojs/video.js#2162]
Hi guys i'm not able  to add subletitles with the last version of video js.
Anyone can help me? 
This is my code:
In the head:http://pastebin.com/PFs6K4gY
In body
http://pastebin.com/SW1WnkdG

Here where i put it: http://mcpocketeditionforapt.altervista.org/try.html

If i click italiano subletitles do not appear

**Comment by Globulopolis** [comment]
You subtitle file is wrong. VJS report an error about it in the console - "Malformed WebVTT signature."

**Comment by gregory0219998** [comment]
I uploaded an other one but still not work. Maybe my converter program is wrong? http://mcpocketeditionforapt.altervista.org/prova1.vtt

**Comment by Globulopolis** [comment]
Try to remove numbers before time.
> 1
> 00:03:27.677 --> 00:03:29.178
> Ragazzina?
> 
> 2
> 00:03:30.886 --> 00:03:32.336
> Sono un poliziotto.
> 
> 3
> 00:03:32.896 --> 00:03:34.256
> Ragazzina!`

Should be
> 00:03:27.677 --> 00:03:29.178
> Ragazzina?
> 
> 00:03:30.886 --> 00:03:32.336
> Sono un poliziotto.
> 
> 00:03:32.896 --> 00:03:34.256
> Ragazzina!`

**Comment by gregory0219998** [comment]
I don't think that this is the problem. As you can see here http://www.iandevlin.com/html5test/webvtt/html5-video-webvtt-sample.html subtitle works good.
I taked the source of vtt and they have the number http://www.iandevlin.com/html5test/webvtt/upc-video-subtitles-en.vtt

**Comment by OwenEdwards** [comment]
Your subtitles file needs converting from SRT to WEBVTT format; see http://www.webvtt.org/. Previous versions of VideoJS were less strict on checking the text track files, so SRT worked even though it was not officially supported. See [my comment](https://github.com/videojs/video.js/issues/1956#issuecomment-85633085) on #1956.

**Comment by gregory0219998** [comment]
Thank you!!!!! It works http://mcpocketeditionforapt.altervista.org/try.html
hot to center the play button?

**Comment by OwenEdwards** [comment]
For 'autostart' of subtitles, the track should be marked as `default` in the HTML. Unfortunately, issue #1914 means this doesn't work in V4.12.x.

**Comment by mmcc** [comment]
Thanks for digging in here, @OwenEdwards!

Re: centering the big play button, if you're using 4.12 you can use the `.vjs-big-play-centered` class.
