### ISSUE TITLE
Video.js doesn't try other available sources on failure

### ISSUE THREAD

**Issue by ReNDeZOwnler** [videojs/video.js#2164]
I don't understand why HTML5 fallback works properly but Video.js doesn't.

I have made two simple examples to illustrate that I'm trying to explain. If one source fails, the player should switch to the next available source.

**Base Layout**

    <video class="video-js vjs-default-skin"
             height="300"
             width="600"
             controls autoplay>
       <source src="http://vjs.zencdn.net/v/oceans_FAILS.mp4" type="video/mp4">
       <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4">   
    </video>

Example 1 - **HTML5**

http://output.jsbin.com/xadihumoka/3

It follows perfectly the W3C HTML5 spec of "The resource selection algorithm for a media element" described on http://www.w3.org/html/wg/drafts/html/master/semantics.html#concept-media-load-algorithm.

Example 2 - **Video.js**

http://output.jsbin.com/koracuboyo/1

Get errored and doesn't recover from error state.

I cannot find any documentation about this problem on video.js github page or the resource selection algorithm for a media element implementing by video.js. I know they use a tech order for determine the source to play, but they only consider **1 working¿?** source per tech. 

I have posted this issue on SO (http://stackoverflow.com/questions/30307131/video-js-fallback) too to guarantee that someone reads my question before closing.

**Comment by gkatsev** [comment]
I think it's because videojs does a pretty bad job on retrying the next available source on a failure. I think there's an issue tracking it somewhere, but not sure where.

**Comment by mmcc** [comment]
This could either fall under #1316 or #869. I'm leaning towards #869 since it's meant to be a catchall issue. @ReNDeZOwnler - want add this to that issue?

**Comment by ReNDeZOwnler** [comment]
I'll check #869 and the 5.0 implementation.

My team and I are working on a project based on video.js and we have to find a solution. We are working on videojs 4 version.

I think videojs should try all sources considering the tech order.

When we achieve it, you have been noticed. We want to return our effort to the community.

**Comment by mmcc** [comment]
@ReNDeZOwnler This logic hasn't changed in 5.0, so the source selection algo should be the same. There are a few hacky ways that you could get around this (keep all the potential sources around, if there's an error, delete the one that was attempted and try them all again), but if you find something you'd like to submit back as a PR that would be incredible. Thanks!

**Comment by mmcc** [comment]
I'm going to close this one, let's consolidate the conversation around this selection logic in #869.
