### ISSUE TITLE
 protect  video link 

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#2167]
Good Day!    Is it possible to protect the video link from the download or copy ?

**Comment by mmcc** [comment]
As you can guess, this is a pretty popular question (search "protect video" or "hide source"), but the short answer is no, it's not possible. There are some things you can do to make it more difficult (kinda), but that's about the extent of it.

**Comment by surikat1978** [comment]
It means better watermark video is not there ?! I would like to ask more about the subtitle .They are protected from downloading if they insert the track?

**Comment by mmcc** [comment]
You would need to watermark the video yourself if that's what you want. Regarding subtitles, no, someone could easily just view your source and grab the track. As a rule of thumb, I wouldn't consider anything in an html5 video element secure (EME is a different story, but I don't think that's what we're talking about here).

**Comment by Globulopolis** [comment]
According to my experience, protect video from downloading or grubbing is very hard and painfully. At least all content which rendered in browser can be grubbed w/o any problems. But you can hide direct links via anti-leech implemented on server-side.

**Comment by subhanisk532** [comment]
Do you have any links and documents related anti-leech

**Comment by Globulopolis** [comment]
@subhanisk532 search for mod_bandwidth or something similar for nginx.
For PHP look at the https://github.com/diversen/http-send-file where you can find basic idea, of course you need additional connection handling for anti-leechen.
