### ISSUE TITLE
video.js captions (not native browser captions) are broken in V5

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#2172]
In the sample `docs/examples/simple-embed/index.html`, when non-native captions are used (I'm using Firefox 37 on Windows 7), the captions menu includes the `captions setting` option. Selecting the `english` option does **not** display the captions.

I get a 'downloadable font rejected by sanitizer ... /build/temp/font/VideoJS.eot' error in the console.

**Comment by OwenEdwards** [comment]
The 'downloadable font rejected by sanitizer..." error was a red herring!

With further experimentation, a way to get captions displayed is to use the `captions settings` to change the font color; if this is done while a caption should be displayed, then the caption appears, otherwise the existing caption is cleared. If you change the color while no caption should be displayed, then nothing happens, and the upcoming captions aren't displayed.

I'm guessing this is due to caption events not getting fired by VideoJS, but that changing the captions settings somehow fires an event which may display the current caption? I'm hoping this gets fixed before V5 is released! @gkatsev, have you taken a look at this?

**Comment by heff** [comment]
Wow, that's amazing you found that! Yeah, this will have to be fixed for 5.0.

**Comment by psharmz** [comment]
this also occurs in chrome and safari with flash only and flash first tech orders. Should that be noted as a separate issue?

**Comment by gkatsev** [comment]
Flash and non-native vtt support is when the emulated captions *should* come up.
I'll take a look soon.

**Comment by heff** [comment]
#2215 should fixe this. Someone want to confirm?

**Comment by OwenEdwards** [comment]
Confirmed!

**Comment by OwenEdwards** [comment]
Confirmed; this is fixed in v5.0.0-rc.6.
