### ISSUE TITLE
Change dowload link to Release page?

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#2178]
Hi! As I see, latest release is 4.12.7, but on the videojs.com `Download` link point to old version of VJS. Maybe we could change this link to `https://github.com/videojs/video.js/releases/latest` so when the stable release will be released on github, users can immediately download latest release from the main site w/o waiting?!

PS! IMHO

**Comment by mmcc** [comment]
We agree! That's the plan for the new website, so that should be the case very soon. Want to open this issue on the [videojs.com](/videojs/videojs.com) repository as a reminder?

**Comment by heff** [comment]
We also need to update the current site with the latest patch version.
Thanks for letting us know.
