### ISSUE TITLE
5.0.0-8 Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by lonormaly** [videojs/video.js#2179]
I get this error, anyone share the same error?

On line #1:
import document from 'global/document';

**Comment by heff** [comment]
Are you trying to run the code without compiling it? The code in master (5.0) requires `grunt build` step before you can use it somewhere. You should instead grab a download from the releases. https://github.com/videojs/video.js/releases/tag/v5.0.0-18
