### ISSUE TITLE
Test for emulated VTT

### ISSUE THREAD

**Issue by ksheurs** [videojs/video.js#2181]
Per some other issue threads, it seems when using many tracks with emulated VTT's, the browser can lock or freeze before playback begins.

Is there a way I can test or know if videojs is going to fall back to emulated VTT's? I might try to disable this functionality, unless there is a better/preferred way to handle this issue.

Thanks!

**Comment by heff** [comment]
Well, ideally we'd figure out what the root cause is and fix it. But otherwise emulated tracks are used in Flash (mostly IE8), Firefox everywhere (currently), and with any external tech like youtube or vimeo.

**Comment by ksheurs** [comment]
Thanks @heff!
