### ISSUE TITLE
videojs Cannot be loaded mp4 for javascript api

### ISSUE THREAD

**Issue by xiaocen2050** [videojs/video.js#2183]
why ,videojs.options.src is readonly, Cannot be loaded mp4 for javascript api   js param load media url

**Comment by xiaocen2050** [comment]
only html tags <source src=''/> initilize

**Comment by xiaocen2050** [comment]
e.g.  loadurl(url){  videojs.options.src=url  } is not support

**Comment by mister-ben** [comment]
You're looking for videojs('player_id').src('url')

https://github.com/videojs/video.js/blob/master/docs/api/vjs.Player.md#src-source-
