### ISSUE TITLE
timeupdate not firing for Flash tech 

### ISSUE THREAD

**Issue by mmcc** [videojs/video.js#2184]
We noticed this while testing in IE8, but it's reproducible in modern browsers when using the Flash tech. Everything seems to work fine, including seeking via the play progress handle, but timeupdate never fires.

**Comment by mmcc** [comment]
@eXon since you recently spent so much time in the techs, do you mind taking a quick look at this one and see if anything jumps out at you?

**Comment by eXon** [comment]
Yep, it was on my todo list to check this soon
