### ISSUE TITLE
Controls are not shown after tap with video.dev.js on IPad

### ISSUE THREAD

**Issue by waster** [videojs/video.js#2187]
I'm using video.dev.js to set videojs.Flash.formats['application/x-mpegurl'] = 'M3U8'.

Testing it on IPad with Safari 5.1 with HLS stream. Controls are hidden automatically after playing start as expected but player does not show controls again after tap event. But long tap can pause/unpause player sometime.

Here is the link to test: http://77.221.142.84:8081/live/eplive-videojs-tap-test.html

**Comment by gkatsev** [comment]
If you're playing HLS on Safari or iOS, you shouldn't need to do any extra configuration to videojs as those platforms are able to play it natively. Also, Flash doesn't work on ipads.
Can you provide more info on your setup? What version of videojs you are using, etc.
Unfortunately, your test link is down.
Thanks.

**Comment by waster** [comment]
I guess inline playing on IPad (not IPhone) is possible with videojs controls (at least mp4). Sorry, the test link is http://77.221.142.84:8081/live/tap-test.html

**Comment by gkatsev** [comment]
It's been a long time since the last update (partly my fault) and we have a new version of videojs. Closing, but can reopen if there's still an issue with videojs v5.
