### ISSUE TITLE
Bug in _V_.flash.canPlaySource

### ISSUE THREAD

**Issue by edemaine** [videojs/video.js#219]
[crossposting from [Knowledge Base](http://help.videojs.com/discussions/problems/1995-bug-in-_v_flashcanplaysource)]

When using the Flash fallback, Video.js 3.2.0 doesn't support content types with optional codec etc. specs after a semicolon. For example, `<source src="video.mp4" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>` won't play despite video/mp4 being a supported format in `_V_.flash.prototype.support.formats.`

I fixed the bug by changing `_V_.flash.canPlaySource` to the following, but you might want to do it at a higher level (i.e. not Flash-specific)...

```
_V_.flash.canPlaySource = function(srcObj){
  var type = srcObj.type;
  if (type) {
    var i = type.indexOf (";");
    if (i >= 0)
      type = type.substr (0, i);
  }
  if (type in _V_.flash.prototype.support.formats) { return "maybe"; }
};
```

**Comment by FDiskas** [comment]
`TypeError: Cannot read property 'canPlaySource' of undefined`
```js
//...
      } else if (source instanceof Object) {
          // check if the source has a type and the loaded tech cannot play the source
          // if there's no type we'll just try the current tech
          if (source.type && !currentTech.canPlaySource(source)) {
            // create a source list with the current source and send through
            // the tech loop to check for a compatible technology
            this.sourceList_([source]);
          } else {
//...
```
