### ISSUE TITLE
Captions on bottom on Chrome 43

### ISSUE THREAD

**Issue by TearsDontFalls** [videojs/video.js#2193]
Since a few days and a chrome auto update, the **captions** of all Video.js players are **always at bottom:0**

Tested+affected: Windows 7 + Chrome 43
Tested+unaffected: Chrome 42 on Android, Windows 7 + Firefox 38

Example Screenshot of http://www.videojs.com/ :
![image](https://cloud.githubusercontent.com/assets/1379201/7774936/2304f9f2-00af-11e5-8de3-9646ed29c4c5.png)

**Comment by heff** [comment]
Hmm, that's annoying. Did the shadow dom class names change? I was pretty
sure we had CSS pushing the captions up, but I'm not finding it.

**Comment by TearsDontFalls** [comment]
On Chrome its using native tracks(so also no caption settings), so something is bugging there i think.

Found a quick workaround for now: Set these settings to false https://github.com/videojs/video.js/blob/5d550ffada237e937cf31ef344f3719112163ea6/src/js/tech/tech.js#L44 and it works as it isnt using native track support.

**Comment by heff** [comment]
Yeah, you can disable native captions, but long term I think we want to rely on Chrome's native captions because people can set the captions settings once and use them across sites. I thought we had CSS that pushed the captions up using the shadow dom.

**Comment by ksheurs** [comment]
Not sure if this is recommended, but this has been working for us:

```css
video::-webkit-media-text-track-container {
  bottom: 0.75em;
}
```

**Comment by mmcc** [comment]
Yep, seems reasonable to me, just kinda stinks that one of the only references I could find to this shadow selector was [Sam Dutton's website](http://www.samdutton.com/track/shadowDOM.html).

**Comment by gkatsev** [comment]
If you enable the shadow DOM in Chrome dev tools, you can see the selectors you could use.

**Comment by mmcc** [comment]
Someone want to put together a PR for this? @ksheurs?

**Comment by EZWrighter** [comment]
This affects Safari as well: https://github.com/videojs/video.js/issues/1904

**Comment by gkatsev** [comment]
It seems like `::-webkit-media-text-track-container` on safari is doing weird stuff. Like, the caption shows up in the appropriate place (say `2em` up) but then moves up another `2em`s...

**Comment by chemoish** [comment]
+1
