### ISSUE TITLE
there should be a min and normal js version for video.js 

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2197]
Hi it seems that the normal video.js  in dist is a min version please create both a normal version and a min version.

**Comment by paladox** [comment]
for version 4.x.x

**Comment by gkatsev** [comment]
Our naming scheme is slightly different in the currently release version. `video.js` is minified and `video.dev.js` is the unminified version. For 5.0, we've corrected this.
If the `.dev` file isn't available, then we should fix it, but it should be available.
Going to close this now, but please comment if you're having issues.
