### ISSUE TITLE
Implemented playbackRate/speed setting (2x, 0.5x, etc.)

### ISSUE THREAD

**Issue by edemaine** [videojs/video.js#220]
I wrote a video-speed.js add-on to video.js that adds a slew of buttons for adjusting playback rate in HTML5 on any browser supporting playbackRate (currently, Chrome, Safari, and IE9, though Firefox is planning to add it soon too).  There is a button marked "1.0x" that brings up a lot of options for speed.  You could easily adjust those options by changing the code, though it would be nice to have a more elegant way to change them.  (I used two columns, so I'm not sure how to make this easy to reconfigure without changing the code/layout...)  Using another tech (Flash), the button simply doesn't appear.  However, it will appear on HTML5 browsers like Firefox where it is unsupported (simply has no effect).

Demo: http://erikdemaine.org/software/video-js-speed/
JavaScript code: http://erikdemaine.org/software/video-js-speed/video-speed.js
CSS code: http://erikdemaine.org/software/video-js-speed/video-speed.css

I'd love to see this incorporated upstream into video.js (presumably turned on/off by an option).  Feel free to use/tweak/modify it to your heart's content...

**Comment by abirla** [comment]
not working...
