### ISSUE TITLE
 .srt file subtitles? 

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#2200]
Hello. The new version of the player does not support .srt file? in my not working.

**Comment by gkatsev** [comment]
The old version of the player only incidentally support srt files since they're similar to WebVTT files. The new version is much more strict in parsing WebVTT and fails if it isn't right.

**Comment by surikat1978** [comment]
Ok! And why does not work default subtitle track after updating my player? I am 100 news. Not one is not working ?! I regret that I did not know this was updated!

**Comment by surikat1978** [comment]
thanks
