### ISSUE TITLE
"No compatible source was found for this video" when using "AddThis Button" - not plugin

### ISSUE THREAD

**Issue by andrixnet** [videojs/video.js#2201]
I have encountered a problem when using videojs and the same page contains AddThis share button from 
<script type="text/javascript" src="http://s7.addthis.com/js/200/addthis_widget.js"></script>

The video player shows "No compatible source was found for this video". 

So far I've only found a workaround disabling the script for AddThis. 

See here: 
http://www.romania-muzical.ro/articol/un-numar-record-de-productii-radiofonice-si-noi-tari-participante-la-grand-prix-nova-2015/1341311/1811/1

Thank you.

**Comment by psharmz** [comment]
what browser are you using?

**Comment by psharmz** [comment]
I'm not sure if this makes a difference but have you tried changing
```
 <source src="http://static.srr.ro/video/articles/1811/art-video-1341311-grandprixnova2015_33s_1080.mp4" />
```

to 

```
<source src="http://static.srr.ro/video/articles/1811/art-video-1341311-grandprixnova2015_33s_1080.mp4" type='video/mp4'>
```

**Comment by andrixnet** [comment]
Firefox (latest)

**Comment by psharmz** [comment]
I'm having trouble reproducing the issue that you are seeing-
I don't get see video player showing"No compatible source was found for this video" but it doesn't show a video.js player it all- it just uses the native html player

can you put up a jsbin(http://jsbin.com/?html,output) that shows the issue? A reduced case might help in solving this.

Thanks!

**Comment by mmcc** [comment]
I'm unable to reproduce either, looks like the player is interacting fine with a ShareThis widget on the same page: [screenshot](https://cloudup.com/cjIGDx7RE3S+)
