### ISSUE TITLE
Default subtitle track & background-color Captions Settings Dialog ?

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#2202]
Good Day!  I have updating on 4.12.6 videojs and after  does not work default subtitle track ? <track kind="subtitles" src="---" srclang="en" label="English" default >
And subtitles not show in IE version 11.0.14 . How it is possible to fix it ? 
And how change black color background of subtitles to white example? 
I change the opacity to 0.05, but still black background and not transparent. In older versions of the beautiful was a transparent background, and now terrible.
Captions Settings Dialog */
.vjs-caption-settings {
  position: relative;
  top: 1em;
  background-color: #000;
  opacity: 0.05;

Thanks for help advance!

**Comment by surikat1978** [comment]
Rolling back to the old version of the player 11.4 - everything is functioning.

**Comment by mmcc** [comment]
Duplicate of #1914.
