### ISSUE TITLE
Install plugin

### ISSUE THREAD

**Issue by telemaxos71** [videojs/video.js#2211]
Hello,
I am not a developer so I am asking you to be patient with me, someone was patient with you ;) . I cannot understand how can I install plugins for video.js ! Do I upload .CSS and .js files on the plugin folder of my site. Do I include any code on the page of my site where I want to place the video.? I am particulary interested in the resolution plugin. As I understood I upload the 2 files ( .CSS and .js ) and then put that piece of code in the page where I want to make the video appear. Well nothing really happens :(.
Help!

**Comment by mmcc** [comment]
Hi there, always exciting to have new people trying out Video.js! :)

You'll want to include any relevant CSS and JS files in the head of your document, both for Video.js and the plugin you want to use. Vidcaster was kind enough to even provide a [working demo](https://vidcaster.github.io/video-js-resolutions/), so your best bet is to see how they did things:

```html
<html>
  <head>
    <title>Video JS Resolutions Example</title>

    <link href="video-js/video-js.min.css" rel="stylesheet" type="text/css" />
    <link href="video-js-resolutions/video-js-resolutions.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="video-js/video.dev.js"></script>
    <script type="text/javascript" src="video-js-resolutions/video-js-resolutions.js"></script>
  </head>
  <body>
    <h1>Video JS Resolutions Example</h1>

    <p>Currently the videos of the two resolutions are identical, they just differ by a superfluous parameter to fool the player into thinking they're different.  But you can at least see the stream switch over and get a sense for the UI.  If anyone has high res and low res videos hosted that they can contribute to this demo that'd be lovely. Vidcaster's hosted videos are video/mp4 only.</p>

    <video id="home_video" controls preload="none" poster="/img/poster.jpg" width="970" height="404" class="video-js vjs-default-skin">
      <source src="http://vjs.zencdn.net/v/oceans.mp4?hd" type="video/mp4" data-res="HD" />
      <source src="http://vjs.zencdn.net/v/oceans.mp4?sd" type="video/mp4" data-res="SD" />

      <source src="http://vjs.zencdn.net/v/oceans.webm?hd" type="video/webm" data-res="HD" />
      <source src="http://vjs.zencdn.net/v/oceans.webm?sd" type="video/webm" data-res="SD" />
    </video>


    <script type="text/javascript">
      vjs('home_video', {
        plugins: {
          resolutions: true
        }
      });
    </script>

  </body>
</html>
```

Just a note, in the future, questions like this are really better suited for [StackOverflow](http://stackoverflow.com) or something along those lines, as this issue tracker is really meant to be for Video.js bugs and related development issues, not support. 

Hope this helped!
