### ISSUE TITLE
v5.0.0-25: Progress bar sits on top of control bar in IE10

### ISSUE THREAD

**Issue by psharmz** [videojs/video.js#2212]
All other versions of IE, Chrome, and FF do not exhibit this issue. This looks to be IE10 specifc

![screen shot 2015-05-29 at 11 35 05 am 2](https://cloud.githubusercontent.com/assets/6305003/7886418/048f161c-05f8-11e5-88d7-a2299fe6145b.png)

**Comment by mmcc** [comment]
My guess off the top of my head is that I missed a vendor prefix or something along those lines. I'll take a look today

**Comment by psharmz** [comment]
@mmcc tried this in IE10 and I see the fix.

**Comment by mmcc** [comment]
@psharmz I assume that means you tested with a build from #2218?

**Comment by psharmz** [comment]
yes! sorry i meant to comment in the PR not here...
