### ISSUE TITLE
v5.0.0-25: No video only audio on iPad

### ISSUE THREAD

**Issue by psharmz** [videojs/video.js#2214]
1. Build the default player in sandbox
2. Play on iPad (i tried a version 7 and version 6.1)

Expected: Video and audio playback
Actual: No video, but audio plays

**Comment by heff** [comment]
@psharmz do we have a manual test suite or steps writing up that others could follow to test Video.js on different devices?

**Comment by meleyal** [comment]
It appears the video element is not present on iPad, compare the following screenshots:

### iPad

![screen shot 2015-06-19 at 12 41 14](https://cloud.githubusercontent.com/assets/15045/8251904/d6728cc0-1680-11e5-99a7-ace450133f63.png)

### Safari

![screen shot 2015-06-19 at 12 40 27](https://cloud.githubusercontent.com/assets/15045/8251912/f7f4b3f0-1680-11e5-8266-2a4444357bdd.png)

**Comment by meleyal** [comment]
Compare that to the 4.x version used on videojs.com, the video element is present:

![screen shot 2015-06-19 at 13 23 46](https://cloud.githubusercontent.com/assets/15045/8252457/89215c02-1686-11e5-8304-6dc4af8a9ca7.png)

**Comment by meleyal** [comment]
Changing the following line to return true seems to fix the issue (not sure what else it breaks :)

https://github.com/videojs/video.js/blob/d5605be8f542aaf8319d2569a75e69addc8a838d/src/js/tech/html5.js#L525

**Comment by gkatsev** [comment]
I can reproduce this with just the index.html from sandbox.

**Comment by gkatsev** [comment]
Looks like the issue is that we never actually re-add to the DOM after cloning it...
