### ISSUE TITLE
Include the src in NPM

### ISSUE THREAD

**Issue by eXon** [videojs/video.js#2222]
I am working on the YouTube tech for VJS 5 and I though hey! let's recode all this using ES6 and use the awesome stuff they already made. Then I looked at the NPM folder and realized nothing is there except the dist folder.

Don't you think it will make sense to include the src folder so that people developing with VJS can use all the stuff that already exists. I could extend from the Tech class directly and use all the cross-browser stuff that already work fine and been tested.

If you have a better way, let me know because I think it is important.

**Comment by gkatsev** [comment]
If we do include the src in the npm package, which I'm all for, users shouldn't be using it directly, for the most part. Files could be moved, changed, renamed, removed between versions.
Some npm packages like [`global`](https://github.com/Raynos/global) have a file API `require('global/document')` and `require('global/window')` which we would want to adopt if we were to go this route. Any changes to these files would then require a major version update.

**Comment by eXon** [comment]
That's a valid point. However, if I use `vjs.element` instead of `import element from 'video.js/src/js/element';`, nothing tells me that the API will not change. The only problem I can see is having duplicate code on both files but I don't think it is a big deal.

**Comment by gkatsev** [comment]
But if `vjs.element` is available, that means it's part of the external API. This does have some meaning in terms of stability. If you're using something internal, you have no such guarantees.
As I mentioned, I'd be ok with adding a `tech.js` file into the repo at the main level that basically just imported and exported whatever the internal path is. Then, you could do `import element from 'video.js/element'` which would count as part of the API.

**Comment by gkatsev** [comment]
Yes, I think we should publish everything to npm, though, keep things nice and tight and limited for the zip release on github and what we push to the cdn.

**Comment by gkatsev** [comment]
https://github.com/videojs/video.js/pull/3445 will fix this. Going to close this in the meantime.
