### ISSUE TITLE
Buffer bar doesn't show in Firefox after reload

### ISSUE THREAD

**Issue by deirdresweeney** [videojs/video.js#2224]
In Firefox, if video buffers completely and then the page is reloaded, the buffer bar does not show up at all. This was noticed on a personal application but is reproducible on the videojs home page.
NOTE: Only reproducible in Firefox.

To Reproduce: 
1) Open videojs homepage in Firefox. (http://www.videojs.com/)
2) Click Play on homepage video.
3) Wait for video to buffer completely.
4) Hit reload.
5) Click Play on homepage video.
6) Observe how buffer bar is not displayed.
Expected Result is that the buffer bar is still displayed.

Buffer bar before reload:
![screen shot 2015-06-01 at 2 07 37 pm](https://cloud.githubusercontent.com/assets/12234763/7920006/188c1790-086a-11e5-97d4-bf604b2251a5.png)

Buffer bar after reload:
![screen shot 2015-06-01 at 2 28 26 pm](https://cloud.githubusercontent.com/assets/12234763/7920072/7e59450c-086a-11e5-99dd-4535fb2b0d6b.png)

VideoJS version 4.11
Firefox version 38.0.1
Platform: MacBoox Pro OS X Yosemite Version 10.10.3

Reduced test case:
http://output.jsbin.com/novalugaru/1

**Comment by gkatsev** [comment]
The code and the example you posted do not use videojs but rather the native firefox toolbar. This sounds like a firefox bug in that case.

**Comment by heff** [comment]
Try starting from this example that uses video.js.
http://jsbin.com/axedog/edit?html,js,output

**Comment by deirdresweeney** [comment]
Sorry. I must've cut too much out from the test case. I still get the issue with the case you posted. and I still get the issue with the video on the homepage.

**Comment by heff** [comment]
Ah, sorry for missing that detail. I can confirm this (reopening). My best guess is that firefox never fires a `progress` event when the video is cached, or that we're not adding a progress listener quick enough to catch the one that it throws. My guess is the latter and we'll need to add something that checks the state of the buffer when the player is ready and/or the tech changes.

![screen shot 2015-06-01 at 1 26 56 pm](https://cloud.githubusercontent.com/assets/166/7922569/f9d91080-0861-11e5-8765-3d8bf2a19a26.png)

**Comment by deirdresweeney** [comment]
Yeah I figured it had something to do with an event listener not being called correctly between VideoJS and Firefox. Glad I could help. Sorry for the confusion earlier.

**Comment by heff** [comment]
Yeah, thanks for reporting! We're always looking for more help if you have any desire to try to fix the issue.

**Comment by gkatsev** [comment]
I believe this is fixed in latest videojs v5. Just tried it on videojs.com in Firefox 41.
Closing as fixed but if it's still an issue we can reopen it.
