### ISSUE TITLE
Where can I get the old version of the player? New versions are not suitable.

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#2228]
HI guys!    
Where can I get the old version of the player for January?
New versions did not work in IE - dark screen as if cut off the contrast! Subtitles VTT does not work in IE!
and Fire Fox and Google Chrome the default subtitles do not work! Subtitle black background and does not change the transparency! This player can not be used on the site , unfortunately! The new version 4.12.7 and githab 5.0.0.29 changes for the better is not found. I wish I updated! In the old version, that I had  in December 2014 January 2015 everything works fine!  Do not understand why?, but it's a fact ?!

**Comment by mmcc** [comment]
You can get any version you'd like via the CDN:

- CSS: http://vjs.zencdn.net/4.12/video-js.css
- HTML: http://vjs.zencdn.net/4.12/video.js

Or via the [releases page](https://github.com/videojs/video.js/releases).

**Comment by surikat1978** [comment]
Hi! Here is an example of the old version 4.11.4 .I added a few lines to lines did not merge. And as margin-botton  0.5 and transparency rgba 0.2. All corrections - nice view! The default subtitle track works. in IE great shows. For this choose videojs!
New versions are terrible. IMHO! Not possible, even easy fixes. Is it only for professionals
