### ISSUE TITLE
Small-size player places speaker button off the menu bar

### ISSUE THREAD

**Issue by lomok** [videojs/video.js#2234]
When I make a small video player with the default skin, the speaker button sets itself down underneath the player- any ideas as to why this happens?

(I am hiding the full-screen button- it does this even when that is visible)
![small_layer_speaker_button](https://cloud.githubusercontent.com/assets/3836962/8000033/d728e844-0b09-11e5-846d-43c492adad12.jpg)

**Comment by heff** [comment]
Can you check out 5.0 (in prerelease right now) and see if it works for you?
You can download it in the releases. https://github.com/videojs/video.js/releases

**Comment by lomok** [comment]
I downloaded version 4.12.8 and it has the exact same behavior.

**Comment by heff** [comment]
Sorry, here's a link to the 5.0 release.
https://github.com/videojs/video.js/releases/tag/v5.0.0-rc.1

**Comment by lomok** [comment]
Hi-
that works!


It looks like the interface art, etc, is slightly different - is this true?

Thanks!

**Comment by heff** [comment]
Yeah, brand new skin for 5.0 that uses flex box for layout.

**Comment by lomok** [comment]
5.0 looks great - any idea as to when it becomes official release and does it
work with existing plug-ins?

**Comment by heff** [comment]
I'm not sure yet how many plugins will need to be updated, but some definitely will. The sooner we get everything tested and all the bugs fixed we can officially release 5.0. Feel free to help out testing on different systems and reporting bugs!

**Comment by lomok** [comment]
I get these errors in the console window when using 5.0 - they do not seem to do anything, but I thought I would let you know:
Uncaught TypeError: videojs is not a function  video.js:9397 Uncaught TypeError: videojs is not a function

Could this be from :  data-setup="{}"

**Comment by lomok** [comment]
One question for you- I wondered if this was resolved in 5.0 or if it is what happens in all non-native players-
my video is wrapped in various iFrames (has to be- proprietary layers, etc) - as I understand it, all iFrames have to have "allowFullScreen"-
is this still true? And does it require all iFrames to have this set? This is a biggie for us. I noticed with the native html5 player it works, which I assume is because it detects no security issue when it is  native. Is there any easy solution to this?

**Comment by gkatsev** [comment]
@lomok `allowfullscreen` will always be required for when the player is put inside an iframe.

**Comment by mmcc** [comment]
@lomok regarding the previous comment, no, that error shouldn't have anything to do with `data-setup`. What steps are you going through to see that? FWIW, I can't reproduce on [JSBin](http://output.jsbin.com/fuxajo) using the CDN version of RC2.

**Comment by lomok** [comment]
Let me look again to see- I am using the downloaded version.
