### ISSUE TITLE
I cant increase font size

### ISSUE THREAD

**Issue by dgrm** [videojs/video.js#2237]
Here my code
.video-js .vjs-captions {
  color: #FFFFFF;
  font-family: 'tahoma';
  font-size: 16px;
}

.video-js .vjs-text-track {
  background-color: transparent;
}

**Comment by dgrm** [comment]
I increase font size but there is 2 subtitle in same time one is whit small font other with large.
And when i go on full screan controls are on the screan.

**Comment by mmcc** [comment]
What browser are you seeing this in? We've switched to [vtt.js](http://github.com/mozilla/vtt.js) and we use native captions support whenever possible, so my guess is you're having trouble with a browser with native support. I'm going to close this as a related issue to #1904, so feel free to comment there.

**Comment by gkatsev** [comment]
Also, you need to use the `::cue` pseudo element to target the native cues.
