### ISSUE TITLE
Video.js in Phonegap

### ISSUE THREAD

**Issue by nikitadesai82** [videojs/video.js#2238]
Implemented video.js in an html site and all worked fine. I passed this through phonegap and then ran the resulting .apk on an Android Kitkat Tablet (specifically HP 21K ) and while all else worked fine, the fullscreen toggle button no longer works. Any idea why that is happening.

Tried replacing video.js with another player - no issues there...fullscreen works fine
Had customized video.js and want to use this if possible. Can anyone suggest a solution or clue me into what may be going wrong.

Have used standard implementation as per git hub.

**Comment by heff** [comment]
What was the other player? Do you know if it was using HTML5 or flash?

**Comment by nikitadesai82** [comment]
used jwplayer as option - works fine except that in fullscreen mode - all
fixed html elements overlap it once it is passed through phonegap.

On Mon, Jun 8, 2015 at 9:05 PM, Steve Heffernan <notifications@github.com>
wrote:

> What was the other player? Do you know if it was using HTML5 or flash?
>
> On Mon, Jun 8, 2015 at 12:09 AM, nikitadesai82 <notifications@github.com>
> wrote:
>
> > Implemented video.js in an html site and all worked fine. I passed this
> > through phonegap and then ran the resulting .apk on an Android Kitkat
> > Tablet (specifically HP 21K ) and while all else worked fine, the
> > fullscreen toggle button no longer works. Any idea why that is happening.
> >
> > Tried replacing video.js with another player - no issues
> > there...fullscreen works fine
> > Had customized video.js and want to use this if possible. Can anyone
> > suggest a solution or clue me into what may be going wrong.
> >
> > Have used standard implementation as per git hub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/videojs/video.js/issues/2238>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/2238#issuecomment-110046322>.
>



-- 

*Nikita Desai*
Founder, Sr. Designer

+91 9825 169 337

**Comment by heff** [comment]
The fullscreen API is built here.
https://github.com/videojs/video.js/blob/stable/src/js/fullscreen-api.js

Any chance you could help us debug whether or not Phonegap + android supports the requestFullscreen API?

**Comment by gkatsev** [comment]
It's possible that phonegap only supports the old `enterFullscreen` or `requestFullscreen` on the video element itself as opposed to the videojs div.

**Comment by nikitadesai82** [comment]
@heff: I can try, but I'm a novice - what exactly do I need to do with the code on the link you've sent me? Also the play button in the centre of the video doesn't function either, only the player button works. 

@gkatsev: does this mean I should try an detect click event on the video element and manually all the fullscreen api?

**Comment by nikitadesai82** [comment]
I finally tried this simple code and passed it through phonegap onto my android hp 21k, and this doesn't work either. Could there be something inherently wrong with the way phonegap reads these functions or the device itself?

<!DOCTYPE html>
<html>
  <head>
    <title>msExitFullscreen API test</title>
  </head>
  <body>
    <div id="div1" class="fullScreen" style="width: 600px; height: 350px; background-color: yellow">
      Div1 
    </div>
    <div id="div2" class="fullScreen" style="width: 600px; height: 350px; background-color: red">
      Div2            
    </div>
    <script type="text/javascript">
      var inFullScreen = false; // flag to show when full screen

       var fsClass = document.getElementsByClassName("fullScreen");
      for (var i = 0; i < fsClass.length; i++) {
        fsClass[i].addEventListener('touchstart', function (evt) {
          if (inFullScreen == false) {
            makeFullScreen(evt.target); // open to full screen
          } else {
            reset();
          }
        }, false);
      }
	for (var i = 0; i < fsClass.length; i++) {
        fsClass[i].addEventListener('mousedown', function (evt) {
          if (inFullScreen == false) {
            makeFullScreen(evt.target); // open to full screen
          } else {
            reset();
          }
        }, false);
      }

  
      function makeFullScreen(divObj) {
        if (divObj.requestFullscreen) {
          divObj.requestFullscreen();
        }
        else if (divObj.msRequestFullscreen) {
          divObj.msRequestFullscreen();
        }
        else if (divObj.mozRequestFullScreen) {
          divObj.mozRequestFullScreen();
        }
        else if (divObj.webkitRequestFullscreen) {
          divObj.webkitRequestFullscreen();
        }
        inFullScreen = true;
        return;
      }

      function reset() {
        if (document.exitFullscreen) {
          document.exitFullscreen();
        }
        else if (document.msExitFullscreen) {
          document.msExitFullscreen();
        }
        else if (document.mozCancelFullScreen) {
          document.mozCancelFullScreen();
        }
        else if (document.webkitCancelFullScreen) {
          document.webkitCancelFullScreen();
        }
        inFullScreen = false;
        return;
      }


    </script>
  </body>
</html>

**Comment by nikitadesai82** [comment]
![code1](https://cloud.githubusercontent.com/assets/10462014/8145813/cb1ff474-1235-11e5-9cf4-8aa1e21a1928.jpg)
![code2](https://cloud.githubusercontent.com/assets/10462014/8145814/cc7058be-1235-11e5-8bf9-1b38e432b267.jpg)
The code is here in pieces

**Comment by d-schiff** [comment]
Was a solution ever found for this issue? I've run in to this exact issue, and have had no luck fixing it.

**Comment by nikitadesai82** [comment]
I ended up using jwplayer with kiosk browser for my project - together both
worked fine
jwplayer + phonegap also gave me no issues after their new update

On Fri, Jan 29, 2016 at 2:39 AM, d-schiff <notifications@github.com> wrote:

> Was a solution ever found for this issue? I've run in to this exact issue,
> and have had no luck fixing it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/2238#issuecomment-176417235>.
>



-- 

*Nikita Desai*
Founder, Sr. Designer

+91 9825 169 337

**Comment by satish0563** [comment]
same issue ,full screen button not working  when using videojs in phonegap .
plz anyone help me 
thanks in advance

**Comment by satish0563** [comment]
hi,any one can help me to resolve full screen issue .i m facing issue in video full screen

**Comment by vnts7** [comment]
Same issue. It happens when you use fastclick plugin or something like that (framework7 ect)
So, the **solution is**: remove fastclick OR just disable it on video container (better)

**Comment by d-schiff** [comment]
I wasn't using fastclick, and not having a fullscreen button wasn't an option for me. The way I ended up fixing it was making a slight tweak to video.js. The function vjs.Player.prototype.requestFullscreen first checks if the browser supports fullscreen at the element level, and if not then checks if the native controls can go fullscreen, and then as a last ditch it stretches the video element to make it fullscreen. Apparently on Android it supports one of the first two conditions (I don't remember which, maybe both), but the fullscreen doesn't actually work. So, I removed the first two conditions, forcing it to stretch the video, and that worked like a charm. Better still, it looks and works exactly the same on all platforms/browsers.

**Comment by gkatsev** [comment]
Sounds like this has been answered above and can be closed at this point.

**Comment by oudoken** [comment]
I confirm it works on latest videojs 7.4.1
Just replace the requestFullscreen with;

    _proto.requestFullscreen = function requestFullscreen() {
      var fsApi = FullscreenApi;
      this.isFullscreen(true);
        // fullscreen isn't supported so we'll just stretch the video element to
        // fill the viewport
        this.enterFullWindow();
        /**
         * @event Player#fullscreenchange
         * @type {EventTarget~Event}
         */

        this.trigger('fullscreenchange');
    };

> I wasn't using fastclick, and not having a fullscreen button wasn't an option for me. The way I ended up fixing it was making a slight tweak to video.js. The function vjs.Player.prototype.requestFullscreen first checks if the browser supports fullscreen at the element level, and if not then checks if the native controls can go fullscreen, and then as a last ditch it stretches the video element to make it fullscreen. Apparently on Android it supports one of the first two conditions (I don't remember which, maybe both), but the fullscreen doesn't actually work. So, I removed the first two conditions, forcing it to stretch the video, and that worked like a charm. Better still, it looks and works exactly the same on all platforms/browsers.
