### ISSUE TITLE
video js has jumps(ticks) while playing in html5 and flash

### ISSUE THREAD

**Issue by Sattar1** [videojs/video.js#2239]
Hi.
I faced a problem with showing video using video js.
for example in 4 min video, 2 min has been loaded. but when I play it, some where before 2 min (that have been loaded already) video jumps. I mean it pauses and resumes.
Here is the video I am talking about:
with html5, it jumps many times. with flash, it jumps fewer times.
Here is the link to the video I am talking about: (this is in flash tech)

https://www.alkhorasani.com/fa/moshahede-film/?film=4757

any HELP would be appreciated.
tnx.

**Comment by mmcc** [comment]
That's weird, but I'm not seeing the issue. It played through smoothly for me all the way to the end.

That being said, why are you forcing Flash first? You have a perfectly good [mp4 rendition](https://www.alkhorasani.com/fa/statics/film/2015/06/Bazgasht-be-Eslam-2.mp4) that will work in all the evergreen browsers now (Safari, Chrome, Firefox, Opera), and it looks like there's an ogg version that should work for any older versions of Firefox. Video.js will automatically fall back to Flash for older versions of IE that don't support MP4, so you should be fine just letting Video.js pick the playback tech and weird Flash playback glitches like this shouldn't be nearly as much of a problem.
