### ISSUE TITLE
Hiding a video on an iPad breaks video playback

### ISSUE THREAD

**Issue by tjlahr** [videojs/video.js#224]
When you hide a video on an iPad and then show it again, the video no longer plays. It appears either the video element is breaking down, or the connection between the HTML5 video tech and the element is getting lost.

What did you do? On an iPad, hid the video with display:none, then unhid it.
What happened? The video became unresponsive
What should have happened? The video should still play
What version of Video.js and any plugins used? 4.x, 3.x, no plugins
What browsers and platforms does this occur/not occur on? iPad
Can a reduced test case be created? http://jsfiddle.net/ffLNJ/3/

Related: #127 

Original Description from @tjlahr:  
I have video in a modal window that plays fine when you open it the first time. However, once you close the modal, if you open it again there is no video, all you see is a black container with video controls with pause button visible. Clicking anywhere on the controls or where the video should be doesn't do anything. This is just on iPad, as it works fine in all other browsers.

This does not look like a repeat of Issue [Issue #182](https://github.com/zencoder/video-js/issues/182) as playback is not just hidden, but completely unresponsive. There are no JS errors in the console.

**Comment by gkatsev** [comment]
I think this is just a browser bug that we can't really do anything about. I just tried hiding and showing the video element locally with the latest videojs and iOS 8.x and it's working just fine.
I'm going to close this as a browser bug.
