### ISSUE TITLE
Is there a minified version of the version 5.0 - should I use it?

### ISSUE THREAD

**Issue by Billybobbonnet** [videojs/video.js#2240]
Hello,

Did you, or someone, made a production-ready version of 5.0? I know it isn't the stable branch, but I assume that, since it is the main branch, it is stable enough to work with. Is that true?

I plan my first release for October. Would you advise to work now with 5.0, adapt the plugins I use, and bet for a stable release before October?

Thanks!

**Comment by heff** [comment]
Yeah, we should have a stable 5.0 by October, so 5.0 would be best to start with, however it's pretty untested right now and existing [plugins](https://github.com/videojs/video.js/wiki/Plugins) may not work with it.

Check out the releases page for downloadable version. We just released rc.1 a few minutes ago that you can kick the tires of.
https://github.com/videojs/video.js/releases/tag/v5.0.0-rc.1

We'll have a CDN hosted version soon as well. 

Closing this but if you have any immediate questions feel free to post them here.

**Comment by Billybobbonnet** [comment]
thanks @heff. I will take care of updating the plugins (hotkeys, record, and youtube-progress), it should be instructive. I plan to make some of my own.

Keep up the good work folks! :smiley:
