### ISSUE TITLE
Is there any alternative way to set a cc track - ie inject into player directly?

### ISSUE THREAD

**Issue by lomok** [videojs/video.js#2242]
Is there any way to inject the document/stuff  needed for captions right into the player itself, ala
myPlayer.setCC("afile"); or myPlayer.setTrack("afile")

Or does it always have to be:
track kind="captions" src="location of caption file" srclang="en" label="English"
 via track?

**Comment by mmcc** [comment]
So we need documentation on this method, but you're looking for `addRemoteTextTrack()`. You can see a basic usage example in our [test suite](https://github.com/videojs/video.js/blob/a5758019e51581500ead1af5948868a4c79c1802/test/unit/tracks/text-track-controls.test.js#L30-L37), but the gist is something like this:

```javascript
myPlayer.addRemoteTextTrack({ label: "English", srclang: "en", kind: "captions", src: "captions.vtt"});
```

**Comment by lomok** [comment]
One last question - can each video can only have 1 kind of  track (ie kind: "captions") attached to it? Either  a subtitle, caption, or chapter?

**Comment by gkatsev** [comment]
You can have multiple captions and subtitles. Chapters only use the first one currently.

**Comment by lomok** [comment]
I am trying to use removeRemoteTextTrack() - it does not seem to work - what parameters are sent, or is it broken? AddRemoteTextTrack works great.
