### ISSUE TITLE
Using both class and div ready functions to init videojs object....

### ISSUE THREAD

**Issue by lomok** [videojs/video.js#2244]
One rather weird thing is happening - 
I am using a loader which sends the file to a server for storage and then gets a url back, etc.

I have had to do this, which looks really weird/hacky , otherwise in some instances, when the video first loads, it does not display the videojs player, but rather just the default html5 player.
I am writing the video into a div and adding it via $"(div").html("blah-blah");

I get the metadata as I have to get the original size, etc...

Here it is:

    $('#video').on('loadedmetadata', function() {
             
               var newDimensions = calculateAspectRatioFit(this.videoWidth, this.videoHeight, 555, 310);

               // use both ready functions or view will not always appear
               videojs("video").ready(function(){

                   var myPlayer = this;
                   myPlayer.width(newDimensions.width);
                   myPlayer.height(newDimensions.height);
                   myPlayer.show();

                   videojs(document.getElementsByClassName('video-js')[0], {}, function() {
                       var myPlayer = this;
                       myPlayer.width(newDimensions.width);
                       myPlayer.height(newDimensions.height);
                       myPlayer.show();
                  });
              });
        });

Most of the time the second class name function never gets called.

I took it out at one point, but then I kept seeing the standard html5 video player interface pop in at times.

Thanks!

**Comment by mmcc** [comment]
Just like #2198, there really isn't much we can do without a [reduced test case](http://jsbin.com/axedog/latest/edit). To be blunt, if you're having to use a ready callback within a ready callback for the same player, something's wrong.

So to walk through your example:

1. The video tag with an id of `video` fires the `loadedmetadata` event
2. Calculate the new dimensions
3. Initialize a Video.js player on a video element with an id of `#video` (which should be `this` in this jQuery context)
4. Set the new dimensions and call `#show()` on the player ([is it starting with a class of `.vjs-hidden`](https://github.com/videojs/video.js/blob/stable/src/js/component.js#L847-L850)?)
5. Find all the elements with a class of `.video-js`, grab the first one, and initialize it.
6. Repeat step 4.

So is there only one player on each page? Ever? If potentially no, you should make sure you're using a unique ID on each player you initialize. Even if the answer is "probably not", I would still highly suggest just generating a unique ID to use.

I would also switch around your ordering and do more via the Video.js API to avoid potential weirdness like this. A common workflow similar to yours is people create an empty video tag, then initialize a Video.js player and do everything via the API.

**Comment by mmcc** [comment]
Just a note, I'm closing this because it *seems* like an implementation issue. We can keep working through it via these comments and if there's a bug, reopen. Again, a working (or not working) example would go a really long way in letting us help debug.

**Comment by lomok** [comment]
One other issue-
I am trying 
<video id="video-element" style="visibility: hidden;" etc
so I can put a loader in.

When I set visibility to hidden in the initial set-up(as above), then after after metadata loads I resize and set visibility to visible, I see the video and it plays, but the screen is black and all I get is the audio.

Any ideas as to what could be causing this?

**Comment by mmcc** [comment]
That's a tough one, not really sure what's going on there. Again, without a reduced test case, we really can't help you.

**Comment by lomok** [comment]
Could I hide it via adding the  .vjs-hidden class instead, and then to show simply remove that class?
Or is that basically the same thing as  -->  style="visibility: hidden;?

**Comment by mmcc** [comment]
If you want to use the helper hide / show methods, then yes, you'll want to add the `.vjs-hidden` class. I doubt it's going to solve the issue you're seeing though, since all it does is [toggle `display: none;`](https://github.com/videojs/video.js/blob/stable/src/css/video-js.less#L1054).

**Comment by lomok** [comment]
That actually did the trick! Thanks so much for recommending/mentioning it  in your initial comments above (#4).

**Comment by mmcc** [comment]
Nice! I'm surprised that worked, but I'm glad I could help :)
