### ISSUE TITLE
5.0.0-34 grunt aborted if replace techOrder by flash,html5

### ISSUE THREAD

**Issue by miyaji27** [videojs/video.js#2245]
Hello,

if replace default techOrder at global-options.js by
```
['flash','html5']
```
and grunt, 
```
Chrome 43.0.2357 (Mac OS X 10.10.3) ERROR
  Uncaught TypeError: this.el_.vjs_getProperty is not a function
```
Aborted due to warnings.

But replace by 
```
['flash']
```
this warning is not occured.
Is this already a known issue?

Best regards

**Comment by mmcc** [comment]
I believe this is just because of the test suite. If you *really* need to do this, you'll want to just set that option and run `grunt build` so the test suite isn't run. 

Why are you setting the tech order to Flash first?
