### ISSUE TITLE
Need a (better) collaborator guide

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2250]
We should document and create everything that a collaborator should be doing for things like accepting PRs and what not. Something akin to https://github.com/nodejs/io.js/blob/master/COLLABORATOR_GUIDE.md

**Comment by heff** [comment]
Sounds good to me. Want to start one?

On Wednesday, June 10, 2015, Gary Katsevman <notifications@github.com>
wrote:

> We should document and create everything that a collaborator should be
> doing for things like accepting PRs and what not. Something akin to
> https://github.com/nodejs/io.js/blob/master/COLLABORATOR_GUIDE.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/2250>.
>


-- 
Sent from mobile

**Comment by gkatsev** [comment]
I'll start posting comments here with snippets of what's useful, it could then be collated to a document.

**Comment by gkatsev** [comment]
There's a small release guide available on the wiki for the stable/4.x branch: https://github.com/videojs/video.js/wiki/Maintaining

**Comment by gkatsev** [comment]
All the contrib commands use the [`contrib`](http://npm.im/contrib) cli tool (not the old contribflow).
To accept a patch, for example, is `contrib patch accept`.

**Comment by gkatsev** [comment]
When accepting a patch or PR, `contrib` will automatically append `closes #xxx` to the commit message so the corresponding PR gets closed.

Side note, github only closes PRs and issues once the commit referencing them with `closes`, `fixes`, etc, gets merged into the `master` or the main branch.

**Comment by heff** [comment]
There's also these wiki pages that are related but may need to be updated. We could either include them or just link to them in the repo guide doc.
https://github.com/videojs/video.js/wiki/Issue-Tag-Guide
https://github.com/videojs/video.js/wiki/New-Issue-Response-Guide
https://github.com/videojs/video.js/wiki/New-Feature-Checklist

**Comment by gkatsev** [comment]
A period is provided for you.

**Comment by gkatsev** [comment]
This is done.
