### ISSUE TITLE
Less support

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2251]
Hi is there less support in video.js because I saw it was switched to another css format. if it was please could there be support for less and the other css format. Mediawiki extension TimedMediaHandler is thinking of switching from another video software to you and mediawiki only supports less. It was decided they would not support the other css format.

**Comment by mmcc** [comment]
4.x supports LESS (and will stay that way), but yes, we've officially switched to Sass for 5.0 and beyond and will no longer maintain an official LESS port of the default skin. If you'd like to port the default skin to LESS and maintain that project, that would be incredible, but otherwise is there something we can do in between? Does LESS allow for you to import vanilla CSS into a project?

**Comment by paladox** [comment]
Not sure.

**Comment by paladox** [comment]
We use https://git.wikimedia.org/tree/mediawiki%2Fvendor/a30ea32d228ea37447bda49fca8ad7db6d5b2888/leafo%2Flessphp

**Comment by paladox** [comment]
There was discussion about either support Sass  or less but less was decided I think they decided agaist Sass for security reasons. But I am not sure.

**Comment by paladox** [comment]
http://leafo.net/lessphp/

**Comment by mmcc** [comment]
Good news! Looks you can [import vanilla CSS into a Less file](http://stackoverflow.com/questions/11196915/import-css-file-into-less-file).

**Comment by paladox** [comment]
Ok thanks for looking to see if it can.

**Comment by mmcc** [comment]
Ok so the vanilla import feature is potentially a good stop gap, but what exactly were you all looking to get out of using our Less file? Our goal with the new styles was to make them really simple and *really* easy to override. The end goal is that devs wouldn't need to actually modify the original CSS, but simply override the base styles with their own. The hope is that this would improve portability and make it easier for folks to stay up to date with the most current version of the base skin (and not need to worry about what preprocessor we used behind the scenes), but we're always looking for feedback!

**Comment by paladox** [comment]
I thought with SCSS you would need a compiler or would the less compiler do it if you import all the files into one less file. But since by default it looks for SCSS files. I doint know how I can use a less file and import them all in there.

**Comment by paladox** [comment]
I think there should be css, less and SCSS files. for easer access for people that doint have a less or SCSS compiler they should use css and for people that only use less compiler then they should use less files and then for SCSS if people use the SCSS compiler then they should use the scss compile there should be an option for users to change css based on what compile they have. By default it should be SCSS.

**Comment by gkatsev** [comment]
Having two separate (or even 3 separate) css files is a huge maintenance burden. We compile the sass files down to regular old css during our publishing process and that should hopefully be sufficient for most people for most use cases. As @mmcc said, in most cases, the user should just include our compiled css file and they're off to the races without worrying about whether it was compiled down from less or sass or whatever.

**Comment by paladox** [comment]
Oh ok.

**Comment by paladox** [comment]
So if I use the scss file it will work without needing to change any compiler.

**Comment by gkatsev** [comment]
You should be able to include the `.css` file either by importing it into less or just by adding it to your page.

**Comment by heff** [comment]
@paladox you won't find the .css file in the master branch of this repo, but it's in the /dist directory in official tagged releases. (If you're npm-installing it)
https://github.com/videojs/video.js/tree/v5.0.0-rc.2

Or in the zip of releases if you're downloading it.
https://github.com/videojs/video.js/releases/tag/v5.0.0-rc.2

The `css` file is what you will use with your less compiler, not `scss`.

**Comment by heff** [comment]
Closing as this appears to be addressed, but feel free to continue to discuss if something's not clear.

**Comment by mmcc** [comment]
@paladox - just to reiterate, we're trying a new direction with the whole base styles thing, so feedback on working with them would be fantastic. Let us know if we can help.
