### ISSUE TITLE
Videos fullscreen doesnt work on Joomla Iframe wrapper

### ISSUE THREAD

**Issue by baouftou** [videojs/video.js#2262]
Hello,

I've made a video gallery with video.js on joomla using joomla's iframe wrapper to load the php files. The link to it is: http://i-wedding.gr/index.php/en/videos

Now if you open the php on it own: http://www.i-wedding.gr/video.php the videos play nicely and fullscreen's working.

But throught the iframe wrapper on joomla videos play fine but fullscreen is not working. http://i-wedding.gr/index.php/en/videos I've been trying to find out why and i cant make sence.

Anyone here could help? 
Thanks in advance, 
Jim

**Comment by gkatsev** [comment]
iframes require the `allowfullscreen` attribute on them for fullscreen to work. (Possibly, you want to add `webkitallowfullscreen` and `mozallowfullscreen` as well to cover all browsers).

I'm going to close the issue since it probably won't require any changes on our end but if you have any more issues, please feel free to continue discussion here. We'll still be notified and if there is an issue, we could always re-open the issue then.

**Comment by baouftou** [comment]
thanks for the answer. but since joomla iframe wrapper has no settings where do i add these "allowfullscreen" etc?

**Comment by gkatsev** [comment]
Sorry, I'm not familiar with how joomla works. Asking on something like stackoverflow will probably yield better answers as to how to make joomla do the right thing in this case.

**Comment by baouftou** [comment]
thanks!

**Comment by gkatsev** [comment]
Looks like you can allow iframes to be inserted via custom html or articles in joomla, which should allow you to have it have the `allowfullscreen` attribute: https://www.youtube.com/watch?v=v0aGVzcaFgw

**Comment by baouftou** [comment]
this is i use this code:

	<video id="highlights1" class="video-js vjs-default-skin vjs-big-play-centered"
  preload="auto" loop autoplay controls="true" width="470" height="264"
  poster="http://video-js.zencoder.com/oceans-clip.png"
  data-setup='{ "controls": true, "autoplay": false, "preload": "auto" }'>
 <source src="http://www.i-wedding.gr/videoflow/videos/vf_299695380_Highlights1.mp4" type='video/mp4' />
 <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video>

**Comment by baouftou** [comment]
I've fixed this on my own. If you please make this solved instead of closed for everyone else having the same problem to see.
I've posted it here:
https://github.com/videojs/video.js/wiki/Joomla-com_wrapper-allowfullscreen-for-video.js

**Comment by Bredamcguigan** [comment]
Hi Bauftou,
I'm having the same problem as you with the allow full screen on videos in Joomla and I'm reading your post where you say you solved it but the url provided no longer works:
https://github.com/videojs/video.js/wiki/Joomla-com_wrapper-allowfullscreen-for-video.js
Could you post here how you solved it?
thanks,
Breda

**Comment by baouftou** [comment]
Hi Breda.
It's been long since this happened to me and i dont recall exactly what
fixed it for me as i cant find documents on it anymore... Im sorry.
But i remember well it had to do with the <iframe> coding
. It was some phrase in addition i found over the internet other that the
allowfullscreen. search arround and im sure you can be helped with this
matter. ill try looking into old files of mine about this.

baou

**Comment by Bredamcguigan** [comment]
Thanks Baou
Yes I think you must have added the allow full screen to the component wrapper? I'm just not sure what files control that.
Regards
Breda
