### ISSUE TITLE
Preloading videos

### ISSUE THREAD

**Issue by Nivelis** [videojs/video.js#2265]
Hi!

In advance - sorry for bad english.

So, I need to preload all the videos before the page loads with a nice percentage-animation.
It seems pretty easy with this library: https://gianlucaguarini.github.io/jquery.html5loader/
Unfortunately tho, I've discovered that video.js won't play any video after jquery.html5loader preloads it.

Is there any easy way to fix it or do it differently?

Greetings,
Nivelis

**Comment by mmcc** [comment]
Really sorry about the delay getting back to you on this one. I've never used html5loader, but this seems like an issue that they might be able to help out with more.
