### ISSUE TITLE
In-band metadata tracks should be visible when emulated text tracks are active

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#2266]
If javascript-emulated text tracks are being used, `player.textTracks()` should return at least all the tracks that are returned from `video.textTracks`.

## Steps to Reproduce
1. Create a player and force emulated text tracks in Safari
1. Load a stream with an embedded metadata track
1. Call `player.textTracks()`

The returned TextTrackList should include a metadata text track but it will be empty.

**Comment by gkatsev** [comment]
I believe this has been taken care of.
