### ISSUE TITLE
IE7, IE8 Support

### ISSUE THREAD

**Issue by RookieRK** [videojs/video.js#2267]
I am using VideoJS and it works fine in Chrome, IE9. However, when I switch to IE7 or IE8, even the Demo VideoJS does not work

I get the following error:
SCRIPT438: Object doesn't support property or method 'defineProperty' 
video.js, line 153 character 142

Is it something additional that we need to do?

**Comment by meleyal** [comment]
Are you using 5.x?

If so did you include the IE shim?
https://github.com/videojs/video.js/commit/14c87055306f277d5437d3a42a7178649f20206e

**Comment by RookieRK** [comment]
I am using 4.12.7. Besides, doesn't videojs have SHIM included?
