### ISSUE TITLE
5.0-rc.2 - control bar is not full width on Android 4.1 stock browser

### ISSUE THREAD

**Issue by meleyal** [videojs/video.js#2274]
Happens on Android 4.1.2 using stock browser ("Internet" app).

Expected: Control bar is full width of video
Actual: Control bar only fills 2/3 of video
Test case: http://jsbin.com/halokodoxo/1/edit?output

![screenshot_2015-06-19-10-45-14](https://cloud.githubusercontent.com/assets/15045/8250153/68fe6dda-1671-11e5-90c9-b8bdc43f268e.png)

**Comment by mmcc** [comment]
Well that sucks. It looks almost like the browser is reporting that it
supports flex box and then...not. Can you see if the .vjs-no-flex class
exists on the videojs element?

**Comment by meleyal** [comment]
I could only find a way to inspect via Adobe Edge Inspect, I'm not sure which browser that uses, but according to that the `.vjs-no-flex` class is set on the videojs element.

**Comment by meleyal** [comment]
After testing with [Ghostlab](http://vanamco.com/ghostlab/) I can confirm the `.vjs-no-flex` is set.

**Comment by gkatsev** [comment]
I turned off the custom control bar in #2499. The native control bar should be used now on native android browsers. I'll close this now, but please let us know if there are issues and we can re-open, if necessary.
