### ISSUE TITLE
VideoJS buttons on controller bar not appearing and not working in IOS8.3

### ISSUE THREAD

**Issue by zmustapha** [videojs/video.js#2278]
If you view the main site, http://www.videojs.com/ on iPad IOS 8.3, the CC and volume buttons disappear. I tried adding other buttons on a sample I'm making, same issue.

**Comment by gkatsev** [comment]
The volume button not appearing is as designed. On iOS, you cannot change the volume of the video element instead you have to use the hardware volume buttons.
As for the captions button, that's a bug that we're working on. We have a tentative fix available here: #2269 and we're tracking that issue in #1904.
Thanks!

**Comment by zmustapha** [comment]
Cool, thanks!
