### ISSUE TITLE
vjs global variable and player.hasStarted fn missing on video.js mangled version.

### ISSUE THREAD

**Issue by carpasse** [videojs/video.js#2279]
It seems that the vjs global variable and some of the player component functions are renamed when the videojs script is mangled. 

I can understand vjs. But I was very surprise when I discovered that player.hasStarted was not available on the mangled version.

Is this the expected behaviour??

**Comment by heff** [comment]
It was when we were using google Closure Compiler, which mangles everything by default and you have to be specific about what you export. We were aiming for the smallest size possible. We've switched to non-mangling in 5.0.
