### ISSUE TITLE
what should `player.width` and `player.height` return?

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2282]
Right now, if you make a player without any dimensions (`<video src="video.mp4"></video>`), it will default to 300x150 px. If you then try to ask the player for it's dimensions, `player.width` will return `300` and `player.height` will return `150`. If you set dimensions on the player (`<video height=300 width=600></video>`), the dimensions will return `600` and `300` for width and height respectively. You can then also set `auto` for the dimensions (`<video height=auto width=auto></video>`) and then set the sizes using css (`.video-js { height: 200px; width: 400px; }`), and this player will also return the dimensions correctly (400 and 200 for width and height).
The issue is what should happen when we go fullscreen?
Right now, the default dimensions and hard-coded dimensions will continue to return the original values when fullscreen but in the `auto` case we get something closer to the computed style of the player as it will return 1920 and 1080 for the width and the height of the player in fullscreen.
Should `player.width` and `player.height` return the actual width and height of the player at the moment they were called? Or should they return the set width and height of the player? If the later, should we have a method to get the computed style values width and height? If the latter, should we have a method to get the set width and height values?

**Comment by gkatsev** [comment]
@imbcmdth brought up the point that the video element's attributes will always return what is set, so, it kind of makes sense for `player.width` and height to just return the set value. However, it does seem like we should have something like `player.currentWidth` which would just return the computed style.

@videojs/core-committers thoughts on the above?

**Comment by dmlap** [comment]
I think I lean towards less-is-more. `getComputedStyle(player.el()).width` isn't too bad and it doesn't require a new API.

**Comment by heff** [comment]
FYI, I think in 5.0 we've already moved to this. Or at least `auto` is gone.

I don't know what the current use case is, but it seems like there's usually better options for positioning then relying on calculated width, so I'd be cautious to add that and encourage using it.

**Comment by gkatsev** [comment]
The specific usecase that triggered this is the rendition selection in HLS. We have a check that looks for the correct rendition resolution with respect to the player's size. Previously, we used `player.width` and `player.height` but that means that in the cases above in fullscreen, we won't be able to upswitch based on the player size. In that case we need current computed style of the player.
I'm not certain that a `currentWidth` API is useful over just using `getComputedStyle` other than that `getComputedStyle` isn't available everywhere (IE8).

**Comment by gkatsev** [comment]
I think the answer is that you should just use `getComputedStyle` on `player.el()` if you want to know the *current* dimensions of the player.
