### ISSUE TITLE
rtmp with authentication parameters

### ISSUE THREAD

**Issue by pikadjou** [videojs/video.js#2285]
Hi everyone,

I have a little probleme with rmtp streaming. I need to put some parametres with the stream, like that: Rmtpe://xxxx?auth=xxx&token=xxx
But the player does'nt work with an url like this.. ( it works with a 'normal' rtmpe url). 
Do you have any idea? Or maybe i miss something in docs?

Thank you so much for your help.

Geoffrey

**Comment by mmcc** [comment]
Closing this as a duplicate of #858.
