### ISSUE TITLE
The guide should mention that your CDN version differs from your downloadable version and includes a third-party GA tracker

### ISSUE THREAD

**Issue by ChALkeR** [videojs/video.js#2286]
See also #751 and #1848.
This guide, I mean: [/docs/guides/setup.md](https://github.com/videojs/video.js/blob/stable/docs/guides/setup.md)

There are no mentions of Google Analytics in the sources either.

**Comment by heff** [comment]
We're working on it for 5.0. Thanks.
https://github.com/videojs/video.js/blob/master/docs/guides/setup.md

**Comment by ChALkeR** [comment]
Thanks.

**Comment by ChALkeR** [comment]
@heff What about http://videojs.com/getting-started/ ?

**Comment by ChALkeR** [comment]
@heff I believe it's past 5.0 already and your website still doesn't mention it.

Could you reopen this issue, please? I don't believe it's fixed.

**Comment by mmcc** [comment]
It's mentioned explicitly in the [setup documentation](https://github.com/videojs/video.js/blob/48ec1fb3eea82559ceb3b5ae1cb958c51c234bb3/docs/guides/setup.md#cdn-version), which is what gets pulled into the [docs website](http://docs.videojs.com/docs/guides/setup.html).

**Comment by ChALkeR** [comment]
It should clearly be present at http://videojs.com/getting-started/, as that's what suggests installing Video.js from CDN for newcomer users, and fails to mention that CDN version has GA.

**Comment by SirCmpwn** [comment]
You need to tell people that video.js includes spyware upfront, on /getting-started.

**Comment by misteroneill** [comment]
Yes, it should, particularly because the setup guide no longer mentions it (an oversight due to a semi-recent rewrite of it). I've opened [a PR](https://github.com/videojs/videojs.com/pull/65) for that.

**Comment by SirCmpwn** [comment]
I also opened a pull request that [removes spyware entirely](https://github.com/videojs/cdn/pull/6) because *why the fuck does this library have spyware in it*

**Comment by misteroneill** [comment]
Your attitude and behavior are totally unacceptable and immature. I'm locking this thread.
