### ISSUE TITLE
Seek problems

### ISSUE THREAD

**Issue by lemonlover** [videojs/video.js#2290]
Hello. I have some unexpected events while i am trying to sync 2 video layouts.

The task is to sync to videos without fade(out/in) 
effect up to 0.000001 because videos are 3D renders of small objects. 

I am using the code below to take time of the first video and seek the second up to it.

```javascript
function changer (ob1,ob2,call) {
			ob1.pause();
			var a = ob1.currentTime();
			ob2.on('loadedalldata', function ()
			{ 	
				ob2.off('loadedalldata');
				if(ob2.readyState() == 4 )
				{ 	ob2.off('loadedalldata');
					//ob2.play();
					ob2.currentTime(a);
					console.log("old a  "+a);
				         ob2.on("seeked",function()
					{	ob2.pause();
                                                ob2.off("seeked");
						console.log("new b "+ob2.currentTime());
						//ob2.play();
						setTimeout(function()
						{	
							$(ob2.L).parent().parent().show();
							$(ob1.L).parent().parent().hide();
					 		console.log("video changed!");
					        },200);
					});
				}			 
			});
		}
```

In other words, stop Ob1 - take Ob1 curtime to a - when Ob1 is seeked to a pause ob1.
Obviosly the a time and new ob1.curtime() must be the same but i have thouse outputs: 
------
old a  7.870086
new b 7.871417
-----
old a  5.868995
new b 5.870086
----
and it's the latest Chrome 43 version. 

old a  2.868995
new b 2.972241

latest mozilla 

If you can tell me why delta is so big it will be very good. Better if you can give the advice how to improve it. (cause i think it's bad idea to do something in the core "NEW")

Regards.

**Comment by mmcc** [comment]
I honestly *seriously* doubt you're ever going to be able to get accuracy out to 6 decimal places. I don't think this is anything we can reasonably help with to that degree of accuracy, but if you can put a reduced test case online we can take a look. I'm going to close this issue, but feel free to keep the conversation going in the comments.
