### ISSUE TITLE
5.0.0-rc.2 - handle errors in tech

### ISSUE THREAD

**Issue by cmwd** [videojs/video.js#2291]
Hello, I want to handle errors reported by tech (dash js) but I have some problems...
My code:
```
this.mediaPlayer.addEventListener(MediaPlayer.events.ERROR, (e) => {
            
    this.trigger('error', { code: 4, message: e.error });
});
```
this throws error
```
Uncaught TypeError: Cannot read property 'code' of null
```

And second question... How can I extend Media Error object with custom errors? I suppose I should write plugin for that but i cannot find reference to Media Error.

**Comment by gkatsev** [comment]
What you should do instead is call the error function with your object: http://docs.videojs.com/docs/api/player.html#Methodserror
It'll take care of triggering the error event and everything.
Hope that helps. Let us know if you have more questions.
