### ISSUE TITLE
li.vjs-menu-title should be INSIDE ul.vjs-menu-content, instead of directly after

### ISSUE THREAD

**Issue by BenMakesGames** [videojs/video.js#2292]
invalid DOM structure; happened to stumble upon this while doing accessibility testing with FireEyes.

it seems to be happening only in the chapters menu: [screenshot](http://i.imgur.com/0xteU6Z.png)

**Comment by mmcc** [comment]
I think I remember fixing something similar to this a few minor versions ago, but this could be something else. What version are you using?



—

**Comment by BenMakesGames** [comment]
4.1.0
