### ISSUE TITLE
Extending progressControl inherits all children

### ISSUE THREAD

**Issue by nbankzy** [videojs/video.js#2296]
When extending the progressControl object it's also taking a clone of the slider. You end up having multiple interactive sliders, not sure if this is intended behaviour or not, struggling to get a clean way to remove the behaviour.

To replicate

		<video id="example_video_1" class="video-js vjs-default-skin" width="640" height="480" controls>
	      <source type="video/mp4" src="http://video-js.zencoder.com/oceans-clip.mp4">
	      <source type="video/webm" src="http://video-js.zencoder.com/oceans-clip.webm">
	</video>

	videojs.TrimVideo = videojs.ProgressControl.extend({
	    init: function(player, options){
	        videojs.ProgressControl.call(this, player, options);
	    }
	});
	this.player = videojs("example_video_1", {});
	var thePlayer = this.player;
	thePlayer.controlBar.progressControl.trimVideo = thePlayer.controlBar.progressControl.addChild(
	    new videojs.TrimVideo(thePlayer, {
	        el: videojs.Component.prototype.createEl(null, {
	            className: 'vjs-trim-start-button vjs-menu-button',
	            innerHTML: '<div style="">words and words</div>',
	            role: 'button',
	            removeChild: 'seekBar'
	        })
	    })
	);

![Image of duplicate slider](https://cloud.githubusercontent.com/assets/1213930/8447746/b46f6554-2011-11e5-9827-5112853843da.png)

Only way I've found of getting rid of the extra slider is by calling `this.player.controlBar.progressControl.trimVideo.c.children[1].remove()`. Even when passing in the options in `addChild`, the `children` property seems to be ignored?

	this.player.controlBar.progressControl.addChild(
        new videojs.TrimVideo(thePlayer, {
            el: videojs.Component.prototype.createEl(null, {
                className: 'vjs-trim-start-button vjs-menu-button hsmt-trim',
                innerHTML: '<div style="">words and words</div>',
                role: 'button',
            }),
            children: {}
        })
    )

[Fiddle for working example](http://jsfiddle.net/tmonhyjs/1/)

**Comment by mmcc** [comment]
What exactly are you trying to achieve? Do you not want the seekbar? If so, you could set `seekBar` to false when initializing the new [`progressControl`](https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/progress-control.js) component.

**Comment by nbankzy** [comment]
That seems to of fixed the issue, couldn't find anything on the net about how to extend the [progressControl](https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/progress-control.js). Setting `children` to an empty object should of had the same affect though?

**Comment by mmcc** [comment]
Setting `children` to an empty object wouldn't work because we merge the options, meaning the seekbar component would still come with it. You'd need to explicitly set `seekBar: false` (or `{ children: { seekBar: false }}`)

**Comment by Klipmunk** [comment]
The above code is not working for the latest version of videojs. How to do the same thing in the latest version of videojs?

**Comment by gkatsev** [comment]
@Klipmunk can you please open a new issue with specifically what isn't working, what you expect to happen and what you want to happen? Providing a test case and screenshots would be helpful as well.
