### ISSUE TITLE
Pausing the player

### ISSUE THREAD

**Issue by campones** [videojs/video.js#2297]
hello,

Sorry for the question as it isn't a bug report.

I would like to know how I can pause the player using javascript so it goes in pause mode after a specified time. 
This would be a simple way to reduce the bandwidth

Thank you

**Comment by heff** [comment]
A specific time in the video, or a specific time after the page loads?

Time in video
```
var myPlayer = videojs('myId');
// Will pause after 1000 seconds of video
myPlayer.on('timeupdate', function pauseAtTime(){
  if (myPlayer.currentTime() > 1000) {
    myPlayer.pause();
    myPlayer.off('timeupdate', pauseAtTime);
  }  
});
```

Time after page loads
```
myPlayer.setTimeout(function(){
   myPlayer.pause():
}, 1000);
```
