### ISSUE TITLE
Inactivity check contains incorrect variable declaration leading to flickering behavior

### ISSUE THREAD

**Issue by pavelhoral** [videojs/video.js#2298]
Inactivity check is not behaving correctly as it "flickers" between states multiple times when the player is about to go to *inactive* state. The reason for this is incorrect variable declaration of `inactivityTimeout` variable in [player.js#1923](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1923-L1934):

    let activityCheck = this.setInterval(function() {
      let inactivityTimeout;
      // ...
      this.clearTimeout(inactivityTimeout);
      // ...
      inactivityTimeout = this.setTimeout(...)

Variable `inactivityTimeout` must be declared outside of the inner function to work properly (otherwise the `clearTimeout` is simply no-op).

**Comment by pavelhoral** [comment]
Demonstation of the incorrect behavior - http://jsbin.com/jipemubuhu/edit?js,output . Every inactivity timeout logs `timeout occured` in the browser console.

**What to do:** play video and move mouse in circles for 5 seconds
**Expected output:** see `timeout occured` once at the end of mouse movement
**Observed incorrect output:** `timeout occured` appears during the interaction and also after it ends

**Comment by heff** [comment]
Ah! Thanks for figuring this out. It was proving difficult to debug. Looks like we missed this requirement in the move to let scoping.
