### ISSUE TITLE
Is there an option for making video poster not clickable?

### ISSUE THREAD

**Issue by smohadjer** [videojs/video.js#2302]
I want my video to play only if user clicks on the play button, not on the poster. Is there an option that allows that?

**Comment by mmcc** [comment]
No, there isn't an off-the-shelf option, but you could just manually remove the [click handler](http://github.com/videojs/video.js/blob/master/src/js/poster-image.js#L95) from the poster image. Here's a [working example](http://jsbin.com/liroja/2/edit?html,js,output).

**Comment by smohadjer** [comment]
But your example doesn't work for me. The video still starts playback if I click the poster.

**Comment by gkatsev** [comment]
Make sure you re-run it or try the popped out version: http://output.jsbin.com/liroja/2
Also, you might be able to do the same by applying `point-events: none` css to the poster.

**Comment by mmcc** [comment]
Yeah, definitely working for me (unfortunately recordit doesn't emphasize click events).

![recording](http://g.recordit.co/iUVPsRIouo.gif)

**Comment by smohadjer** [comment]
My bad, I didn't know I have to re-run the example. It works now! :)

**Comment by mmcc** [comment]
:+1: Glad I could help.

**Comment by smohadjer** [comment]
You certainly did! My mistake was that I had presumed click handler is set on the poster element itself (div.vjs-poster) and not on a custom object. I guess there was no way around achieving what I needed except by looking into the code. Does setting event handlers directly on DOM elements have any disadvantages?

**Comment by mmcc** [comment]
I generally suggest doing as much as you can via the Video.js APIs simply because it makes it easier to debug (and upgrade later). We also try to help smooth out differences between browsers (similar to jQuery), so even though some things could easily be done directly via the DOM, keeping everything you can in the VJS world assures that you're taking advantage of any potential things there.
