### ISSUE TITLE
Can not use `videojs.extends` without a constructor function

### ISSUE THREAD

**Issue by pavelhoral** [videojs/video.js#2303]
Would be nice if we can use `videojs.extends` without a constructor function. In that case it can provide implicit constructor which would just call parent constructor:

    var Component = videojs.getComponent('Component');
    var Foo = videojs.extends(Component, { 
        // constructor: function() {
        //     Component.apply(this, arguments);
        // },
        createEl: function() {
        }
    });

Currently this does not work as the `videojs.extends` expects the second parameter to either be constructor or object with a `constructor` property.

**Comment by heff** [comment]
Yeah I agree, that would be nice. Wan to put together a PR for it?

**Comment by gkatsev** [comment]
PR for this was merged in. Closing.
