### ISSUE TITLE
Banner can't be show again after video start

### ISSUE THREAD

**Issue by RoyBellingan** [videojs/video.js#2306]
Using version 4.12.7 (downloaded from web site on 5/July/2015) the poster gain the class 
/* Hide the poster after the video has started playing */
.video-js.vjs-has-started .vjs-poster {
  display: none;
}

The suggested method to show again the poster (as https://github.com/videojs/video.js/issues/972) 
Is calling vid.posterImage.show();
Who use this.removeClass('vjs-hidden');

I'm using the same code as http://jsbin.com/pefanijuke/edit?html,output

IF I replace the downloaded file with
<link href="//advplace.ng/js/video-js.css" rel="stylesheet">
<script src="//advplace.ng/js/video.dev.js"></script>

Is working again...
(the cdn version is reported as v4.3.0)

**Comment by mmcc** [comment]
Sorry for the delay, but the JSBin works for me. The poster shows again when the ended event fires. Closing this, but feel free to comment if you have any questions.
