### ISSUE TITLE
Issues With Live Streaming Format

### ISSUE THREAD

**Issue by rizwansultan88** [videojs/video.js#2307]
I'm trying to embed link with live steam link but it doesn't work on videojs html 5 player, 
```html
<video id="example_video_1" class="video-js vjs-default-skin"
                       controls preload="auto"  width="960" height="264"
                        
                       data-setup='{"example_option":true}'>
                    <source src="http://abclive.abcnews.com/i/abc_live4@136330/index_1200_av-b.m3u8?sd=10&b=1200&rebase=on"  type="application/x-mpegURL"/>

                    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
                </video>
```

**Comment by gkatsev** [comment]
videojs cannot play HLS video (`.m3u8` files) natively. HLS only plays natively on mobile devices like iOS and Android (for some definition of "plays natively" :) and on OSX on Safari.
We have a project ([videojs-contrib-hls](/videojs/videojs-contrib-hls)) that enables HLS for other desktop browsers.

**Comment by rizwansultan88** [comment]
Thanks gkatsev I already check that repository for playing live streaming.
