### ISSUE TITLE
Progress Event does not fire in Safari

### ISSUE THREAD

**Issue by vincentson** [videojs/video.js#2309]
I am using the videojs plugin for all the videos on my website. And everything seems to work perfectly in all browsers except Safari. I have all control elements hidden, as I only want to have the Play Button and a Load-Progressbar. 

But the thing is: in Safari the progress event triggers once at 0 percent and then logs 1 as the video is downloaded completely. The progress bar just jumps straight to width:100%. Chrome, Opera, Firefox and Internet Explorer work fine.  

(Also only in Safari the video has to be downloaded completely, before it is played. Could this be the cause for the buffer problem aswell? Moov is in the right place and the videocodec is H.264) 

Any Idea what might be causing this? 

    $('video').each(function(){
	        
	        var thisidisit = $(this).attr('id');
	        
			videojs(this.id, { 
		        "controls": true,
		        "autoplay": false,
		        "preload": "none",
		        controlBar: {
					muteToggle: false,
					FullscreenToggle: false,
					TimeDivider: false,
					CurrentTimeDisplay: false,
					DurationDisplay: false,
					RemainingTimeDisplay: false,
					VolumeControl: false
  				}
			}, function(){
				
				this.on('progress', function(){
					console.log( 'buffered', this.bufferedPercent() );
				});
				/*
                                this.on("waiting", function(){ 
					$('#uparrow').show();
				});
				this.on("timeupdate", function(){ 
					$('#uparrow').hide();
				});
                                */
	  			this.on('loadedalldata', function(){
		  			$('#' + thisidisit + '_html5_api').siblings('.vjs-control-bar').children('.vjs-progress-control').fadeOut(timer);
	  			});
  			});

    });

**Comment by gkatsev** [comment]
It sounds to me like you're running into a caching issue. Since a value of `1` would mean that everything is loaded, so, if you only get one progress event which prints out a value of `1` it would mean that the whole video is cached.

**Comment by muzfuz** [comment]
I'm seeing this issue in Safari with not just VideoJS but also vanilla HTML5 video.

**Comment by gkatsev** [comment]
Yep, since this bug was filed, we've had to deal with a few other cases of `progress` events and seems like safari really doesn't like firing them at all. Not sure if there's really anything we can do there.

**Comment by ahmetaa** [comment]
I think video progress events are not reliable. From codec to codec things get sporadic. It is better to use a timer and check video progress periodically.

**Comment by gkatsev** [comment]
Closing this as there is nothing we can about it. This is how Safari functions.
