### ISSUE TITLE
how to set default volume

### ISSUE THREAD

**Issue by OPGamesTH** [videojs/video.js#2310]
how to set default volume ?

thanks.

**Comment by mmcc** [comment]
`defaultVolume` is dead (and will be removed from the global options), so you'll need to do this manually. Something like this should work for you:

```javascript
var defaultVolume = 0;
videojs('my-sweet-player', {}, function() {
  this.volume(defaultVolume);
})
```

**Comment by jbravo0304** [comment]
i have same problem and cant get it to work.

**Comment by Giovanni-Mattucci** [comment]
How do you do this with the `data-setup` attribute?

**Comment by DrOhReally** [comment]
sorry to bring this up again but setting the volume using the method given above will cause the volumechange event to be fired even though this is an initial setting. Any way to work around this?

**Comment by gkatsev** [comment]
I don't think that the video element provides a way to set a default volume, i.e. a setting it so that you don't get a volumechange event.

**Comment by spormeon** [comment]
Hi,   does this still work in latest version?  what the scale of the volume 0-10, 0-100 ?

var defaultVolume = 0;
videojs('content_video', {}, function() {
  this.volume(defaultVolume);
});

**Comment by gkatsev** [comment]
It still works, the scale is 0-1.

**Comment by lineldcosta** [comment]
Just to add to previous question, Is there any way i  can set default volume as system volume.

**Comment by Paderman** [comment]
> Just to add to previous question, Is there any way i can set default volume as system volume.
You can try to save the value into "localStorage" and if the site is reloaded, the volume should be loaded the saved volume.
