### ISSUE TITLE
Bug with Android 4.3 native browser on Play/Pause controls.

### ISSUE THREAD

**Issue by prat90** [videojs/video.js#2319]
On touching the play button (with Samsung Galaxy S3 , android 4.3) it is automatically pausing. its only works when we press it for longer time .
So play/pause touch is not consistent . I am using videojs 4.12 . Please suggest an workaround for touch devices.
This issue is also reproduced in www.videojs,com (website ) with galaxy s3, android 4.3.
 

Also, on preload "auto". the duration is not updated .

![capture](https://cloud.githubusercontent.com/assets/13232464/8565263/9d1c08fc-2571-11e5-9852-e27160106f34.PNG)

**Comment by MarcusOhman91** [comment]
+1. I've tested 4.04 aswell and it has the same behavior. Happens in the stock browser. Chrome seems to work fine

**Comment by zrehmani** [comment]
+1 https://github.com/videojs/video.js/issues/2044

**Comment by prat90** [comment]
@heff . Please look into this issue .

**Comment by aharris** [comment]
+1 I am seeing this on the Samsung GS3 running 4.3.

**Comment by Pacific112** [comment]
+1
I've got the same issue. Still, on v 4.9.1 it's working fine, and I can't find wnich change caused this problem.

**Comment by gkatsev** [comment]
In vjs 5, we've updated to default to the native controls on native browsers: https://github.com/videojs/video.js/pull/2499
Closing for now, but can reopen if still an issue.
