### ISSUE TITLE
videojs.bind gone in 5.0

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#2322]
videojs.bind is no longer exported so the native Function.prototype.bind() gets picked up by 4.x code that relied on this method.

**Comment by dmlap** [comment]
I see this has been sort of relegated to IE8 support. I'll make a note in the migration wiki.

**Comment by gkatsev** [comment]
Has it? I think it still makes sense to expose it because videojs's `bind` has some extra functionality regular bind doesn't have.

**Comment by heff** [comment]
Yeah, we should export it. You can use our bind for sharing listener ids.

**Comment by dmlap** [comment]
Where do we share listener ids? Are you sure it's worthwhile having a custom version of bind()?

**Comment by heff** [comment]
Anywhere we do something like...
```
// ...in one function
something.addEventListener('foo', Fn.bind(this, this.someInstanceHandlerMethod));
// ...in another function
something.removeEventlistener('foo', this.someInstanceHandlerMethod);
```
With the native bind that wouldn't work.

I don't think we could have `component.on()` automatically bind the component as context for the listener, and still have the original listener be use in component.off, without a system like this.

If you're not benefitting from that feature in the external code that uses videojs.bind(), then you should just use the native bind now. And then maybe we don't need to export this? We should probably either export it or throw a warning when it's used in 5.0.

**Comment by heff** [comment]
I'm gonna merge in the PR. If we want to discourage using this I think we should deprecate it first.
