### ISSUE TITLE
Question: Intergation of DRM and License Servers

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#2324]
I am trying to find more information on how DRM and Licensing integrates with video.js.

I am currently prototyping something with video.js and https://github.com/heff/videojs-dashjs (Which has https://github.com/videojs/videojs-contrib-dash and https://github.com/videojs/videojs-contrib-hls).

I understand there is multiple DRM's: PlayReady, WideVine, Adobe Access, FairPlay, other?

I have got the movie to start using video.js dynamic injection and videojs-dashjs, but it only plays for the first 9 seconds. I am sure I am just too scrub to piece together all of this information.

<img width="649" alt="screen shot 2015-07-08 at 12 23 54 pm" src="https://cloud.githubusercontent.com/assets/549319/8579914/48539628-256c-11e5-947f-2536492e18f8.png">

I noticed that dash.js and shaka-player both have points at which you add license servers. Does this also apply for video.js?

**Comment by heff** [comment]
Video.js DASH support uses dash.js under the hood. We're building out a
more robust integration, but for now a good starting point might be to get
it working with dash.js first.

**Comment by chemoish** [comment]
Are my comments about DRMs and licensing related to video.js? Or is that on my part to make work?

**Comment by chemoish** [comment]
After researching more about Dash.js API, I am going to keep working on it.

Thanks.

**Comment by cyberformed** [comment]
Hello guys. I need some information regarding 3rd party DRM server and licence keys integration. if so, what is the best DRM server that could I use. Help me in this regard.
