### ISSUE TITLE
Videojs does not add "src" attribute to "video" element if video source has an absolute path

### ISSUE THREAD

**Issue by smohadjer** [videojs/video.js#2325]
I've noticed that video-js has inconsistent behavior depending on whether the video source is a relative or an absolute path. If it's relative, then a "src" attribute is added to video element, but if it's absolute not. What's the reason for this inconsistency?

**Comment by heff** [comment]
Sounds strange. Do you think you could put together a live example or jsbin?

-- 
Sent from mobile

**Comment by smohadjer** [comment]
Here is a link to an example using relative path for video:
http://sandbox.saeidmohadjer.com/video_vjs.html

If you inspect the video element using a browser dev tool you see it has a "src" attribute. For an example with absolute path checkout video on videojs website homepage. That one has no "src" attribute.

**Comment by heff** [comment]
It's probably because we try not to disrupt the currently playing source if it already started when video.js first gets to the video element. This helps keep the player loading as fast as possible.
https://github.com/videojs/video.js/blob/004b1e8f7bfbae1749e7b141b9ccd45b3d1a5bca/src/js/tech/html5.js#L31

How are you using the player that this is causing a problem?

**Comment by smohadjer** [comment]
Not sure I understand your explanation. Are you saying native video element has different behavior depending on whether video source has a relative or absolute path?

I my experience inconsistencies always cause a problem, though in this case I should have not relied on "src" attribute on video element in a code I wrote to show poster of video after playback ends.

**Comment by heff** [comment]
We don't modify the source string in html5, so the only explanation I can
think of is that the browser loads one version quicker than other, causing
the source to already be partially loaded by the time our script sees it.

**Comment by smohadjer** [comment]
That's really weird, because if I turn off javascript the "src" attribute is no longer added to video element.

**Comment by heff** [comment]
Yeah, there's two ways to set the source of the video element, the src attribute and source tags. If you use source tags then the src attribute does not get set. That's why there's a `currentSrc` property on the video element, so you can know the source without needing to know how it was set.

**Comment by smohadjer** [comment]
But my link is using source tags, so there shouldn't be a "src" attribute on <video> tag! 

It seems browsers add a "src" attribute to <video> element if video <source> uses a relative path, but don't do so if the <source> uses an absolute path.

**Comment by mmcc** [comment]
I'm closing this because to be honest I'm not sure there's an issue here. If I'm wrong, ping the thread and we'll reopen.
