### ISSUE TITLE
Setting the src is not synchronous

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#2326]
Even when the tech is ready, setting the source doesn't take effect at the tech level for one tick because it's [wrapped in a call to ready()](https://github.com/videojs/video.js/blob/26a78627f1f231dbbe0fa1f7441bfc1b27893be5/src/js/player.js#L1521)

**Comment by heff** [comment]
Hmmm...that would appear be the result of #1667 and #2188.

We may want `ready` to be consistently async across techs, however we probably also still want the functionality that either calls the function synchronously or queues it for after the ready event.

Do we really need every function passed to ready(fn) to be triggered asynchronously, or do we just want the initial ready to happen async and then anything after that could be synchronous? If we could do the latter that would fix this issue.

**Comment by dmlap** [comment]
Yeah, I think this introduces a lot of accidental asynchronicity that will make things much more complicated. Another possibility would be to make the "public" version asynchronous but convert all internal usage to a synchronous version.

**Comment by heff** [comment]
Yeah, that could do it. Have a `readySync()` function, or a second arg, `ready(fn, async=true)`. Not sure what the best API is but I like it. @gkatsev any thoughts?

**Comment by dmlap** [comment]
@heff it looks like #2392 didn't completely fix setting the source synchronously for the Flash tech because we're still [setting it in an async ready handler](https://github.com/videojs/video.js/blob/3bf415e5221e4516ee6a9c795ecf23d8530a9efc/src/js/tech/flash.js#L33-L35) on construction.

**Comment by heff** [comment]
@dmlap that block sets sync=true (second arg) so it shouldn't be working any differently than 4.12 now. When that specific code runs the swf object is never ready. If we're trying to improve on the previous functionality then, we'll probably have to cache the source value and return that while the swf boots up.

**Comment by dmlap** [comment]
Oops... I missed the `true`. All of the tests in contrib-hls now require an extra tick of the clock in player setup but it seems like that is because of the conversion to a source handler and this guy should have stayed closed.
