### ISSUE TITLE
The big play button doesn't work on Android 4.1/4.2/4.4 (chrome) mobile devices. 

### ISSUE THREAD

**Issue by chandnidesai7** [videojs/video.js#2333]
The big play button doesn't work on Android 4.1/4.2/4.4 (chrome) mobile devices.

**Comment by gkatsev** [comment]
This is in reference to the "native" big play button, not ours. Given that we're preventing the default action of the click event that play button doesn't do anything, so, we can't really do anything about it.
I'm going to close this as I don't think we can do anything about it but it's nice that it's documented.
