### ISSUE TITLE
5.0 (rc) broken in IE8

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2335]
It seems that at least the video.js 5.0 RC's are broken in IE8 with the videojs-ie8 part.

It does play video, but as soon as the player controls "autohide" and you hover over the video, IE8 reloads the page in compatibility mode after an error.

After some investigation, it seems this is because of at least two reasons:

* vtt.js has some "trailing comma's" in object literals. They have fixed this, but not in the "shim-build" branch video.js is using. See https://github.com/mozilla/vtt.js/commit/db56965c978c0fd5a2993085a454f2fcc5934816 for the fix.
* The other problem seems to be related to babel. I get an "Accessors not supported!" exception and this appears somewhere in the babel code. I could not really find what goes wrong exactly, as the IE8 devtools are horribly slow and tend to crash

For a test case, see: http://jsbin.com/bihipoporo/edit?html,output
Note that this example uses "local" .js and .css files as I don't know of there are any 5.0 CDN versions yet.

**Comment by heff** [comment]
Thanks for digging in to that. We'll get the vttjs update in today. You can use rawgit.com and the tagged releases to load 5.0 versions into jsbin.

I'm not quite sure about the babel issue...

**Comment by gkatsev** [comment]
I have a PR out to fix the vttjs issue in master: https://github.com/videojs/video.js/pull/2331

**Comment by gkatsev** [comment]
I think we might be misconfiguring `babelify` to loose mode. Looking into it.

**Comment by gkatsev** [comment]
Well, looks like the main build is working fine for me. The test and watch builds don't specify loose mode so I'll add that but otherwise, I'm not seeing any issues.

**Comment by nickygerritsen** [comment]
I'll try on Monday if I can reproduce it then. If so I'll create a jsbin that is problematic.

**Comment by gkatsev** [comment]
I'm still seeing an error in ie8 but it doesn't seem to be affecting anything...
It's saying `Object doesn't support this property or method` on this line (in `buffered` method):
```js
    return _utilsTimeRangesJs.createTimeRange(0, this.el_.vjs_getProperty('buffered'));
```

**Comment by gkatsev** [comment]
And I'm no longer seeing that error anymore...

**Comment by heff** [comment]
#2316 probably fixed the getProperty error

**Comment by nickygerritsen** [comment]
I manually applied that PR indeed because I was getting that same error before.

**Comment by gkatsev** [comment]
Ah, yes, that would do it since I rebased to make PR #2337.

**Comment by nickygerritsen** [comment]
I still have some errors with IE8, especially when hovering over the video after the controls are hidden.

I have creates a jsbin that reproduces the problem. See: http://jsbin.com/tegofeboxi

For us it is also failing in automated tests using karma, but debugging in IE8 is not really ideal, so I'm not sure if this is the same problem. Anyway, for our testing the problem comes back to `es5.js`, line 43, which reads:

```js
if('get' in Attributes || 'set' in Attributes)throw TypeError('Accessors not supported!');
```

The exception here is thrown, but I can not figure out when this happens because I can not really print backtraces.

**Comment by gkatsev** [comment]
@nickygerritsen thanks for the example. I'll check it out.

**Comment by gkatsev** [comment]
@nickygerritsen I'm unable to see any errors. When you tested it out in IE8, did you run it on the jsbin page directly or did you pop the output out into a separate window? Flash particularly has issues running inline in jsbin. I cloned your example and uses this url to test in IE8 https://output.jsbin.com/hiqove/1 and it worked great for me. Can you try it out again and report back? Thanks.

**Comment by nickygerritsen** [comment]
OK tested it using your url. It still breaks if you hover over the video after the controls are hidden.
See https://dl.dropboxusercontent.com/u/2765/ie8-crash.mov for a video of what I mean.

As you can see, tested in Windows XP (using ievms).
Hope this video helps to solve the problem (although we already decided to drop ie8 support in our project...)

**Comment by gkatsev** [comment]
That is super weird. I wonder if it has to do with a Windows XP VM? I'm using IE8 on a Win7 VM.

**Comment by nickygerritsen** [comment]
@gkatsev Interesting; I am now downloading the Win7 ievms package, will let you know if it does the same there.

**Comment by gkatsev** [comment]
Awesome, thanks. Related, but what version of IE8 does your WinXP machine have?

**Comment by nickygerritsen** [comment]
8.0.6001.18702

**Comment by gkatsev** [comment]
I have 8.0.7601.17514. Might be a version issue.

**Comment by nickygerritsen** [comment]
@gkatsev Just installed a fresh ie8 win7 vm using ievms. I how have the same version string as you, but there it also crashes on hover after control-bar hides.

**Comment by gkatsev** [comment]
That is super weird. Not sure what could be happening.

**Comment by heff** [comment]
I've been testing pretty extensively on IE8 lately and I think this one can be closed. @nickygerritsen let me know if you're still seeing IE8 issues.

**Comment by stevus** [comment]
@heff why was this closed? What was the solution?

This issue should be reopened.

**Comment by heff** [comment]
@stevus if you're seeing a problem issue can you submit a new issue with the specific details of the problem you're seeing and steps to recreate? It appears this was closed because we weren't able to recreate it.

**Comment by mmcc** [comment]
We're also on 5.11 now (or close to it), so the version mentioned originally is ancient, and all the potential causes @nickygerritsen mentioned have changed significantly in the last year. If this is still happening for you in 5.11, _definitely_ open an issue so we can take a look!
