### ISSUE TITLE
How can I play HDS vod stream using html5 video tag

### ISSUE THREAD

**Issue by shivamg705** [videojs/video.js#2344]
I am using following code in video tag of videojs to play manifest.f4m vod stream through wowza media server .but it is not working Please help if anybody knows.

    <source src="http://192.168.67.97:1935/vod/_definst_/mainVideo/smil:mainVideo.smil/manifest.f4m" type='video/f4m' />

**Comment by mmcc** [comment]
This would require Flash support, which the default Video.js fallback doesn't support. There are other plugins, such as [videojs-osmf](https://github.com/tomjohnson916/videojs-osmf) that might be helpful.
