### ISSUE TITLE
videojs player free or purchase software?

### ISSUE THREAD

**Issue by jaisee** [videojs/video.js#2356]
Hi,

What license is VideoJS used? Can it be free or purchase software?
waiting for your reply

Thanks,
jaisee

**Comment by alsar** [comment]
You have a  LICENSE file in the root of the repository:
https://github.com/videojs/video.js/blob/master/LICENSE

**Comment by heff** [comment]
@alsar is correct. It's the Apache 2 License. No purchase necessary.
