### ISSUE TITLE
Muted video still display that there is volume.

### ISSUE THREAD

**Issue by jbravo0304** [videojs/video.js#2358]
I am a front end developer and i am having some hard time trying to get it to work. My boss wants it to auto-play on a muted state. So i got it to work but the volume bar still displays at 3 or at full volume as well as the mute icon wont display as muted.I  Need help so, people have to click on the muted button to be able to hear it.

**Comment by heff** [comment]
Sounds like a bug. Could you set up a jsbin showing the behavior?
- if you're using v4.x - http://jsbin.com/axedog/edit?html,js,output
- if you're using v5.x - http://jsbin.com/sofiwu/edit?html,output

**Comment by jbravo0304** [comment]
http://jsbin.com/piboxirabe/edit?html,js,output

**Comment by jbravo0304** [comment]
It starts muted but the volume shows as if it was on high.

**Comment by heff** [comment]
Yeah, that's pretty straight forward. We need to add a check for muted when the volume and mute controls are first created.

@mmcc might be able to do that in his current work around the volume button. It will probably only make it into 5.0 though either way.

Here's a version of your jsbin that works a little better.
http://jsbin.com/naxato/edit?html,js,console,output

**Comment by jbravo0304** [comment]
I was on vacation but this was on my head all along. Thank you so much!

**Comment by heff** [comment]
I'm gonna leave this open and assign to @mmcc, since we need a better long term solution than the one i had in the jsbin and it shouldn't be too hard to add.
