### ISSUE TITLE
embed url for using in facebook, twitter, ...

### ISSUE THREAD

**Issue by Sattar1** [videojs/video.js#2360]
Hi.
I am using videojs, it's great.
but I have a problem. I want to know how to create an "embed url" for using in fb, twitter, ...
I know that the "embed url" should be introduced with opengraph meta tags "og:video:url" and schema.org meta tags like itemprop="embedURL". exactly like youtube.
but HOW?
e,g when I share this page: https://www.alkhorasani.com/fa/moshahede-film/?film=4946 in fb, it just shows the thumbnail which is a link to the webpage. but doesn't play it on timeline, like Youtube.
I don't know, maybe I should create the "embed" page on my server and it's not related to videojs script. however, any HELP would be appreciated.
note: I read https://github.com/videojs/video.js/issues/1295 issue, but found no solutions there.

Thank You.

**Comment by mmcc** [comment]
#1295 doesn't really provide a solution because unfortunately there isn't one. [This comment](https://github.com/videojs/video.js/issues/1295#issuecomment-46209513) pretty much sums it up, unless you have a custom SWF to give to Facebook, they're going to use their own player.

**Comment by Sattar1** [comment]
wow! Fast answer. thanks @mmcc
it seems I should be pleasure with the thumbnail and the link to the webpage.

**Comment by Sattar1** [comment]
Hi.
searching the above problem and testing different methods, I found out that if I have "video/mp4" output from the page, then I can inline the video in FB timeline(for HTML5). or if I have access to swf file, then I can inline it with flash technology.
so now, my question is this. I hope you answer it like always:
when we open an mp4 file directly via the browser, the browser shows default HTML5 player and plays the video. page output content-type in this case is: video/mp4
now again I want to play mp4, outputting video/mp4 content-type, but <b> playing with VideoJS player, not the default player</b>.
I hope you've understood my question.
Thanks for the support.
