### ISSUE TITLE
Prevent click event on video player

### ISSUE THREAD

**Issue by itsvee** [videojs/video.js#2363]
How to prevent click event on video player ? I used preventDefault() with player and div, it not work for me. thanks for suggest.

**Comment by heff** [comment]
Which clicks? Any click, including on controls? You could try removing the controls attribute on the video tag.

**Comment by itsvee** [comment]
Any click on video display only. I don't want pause video by click. Can I prevent this event ?

**Comment by heff** [comment]
If you don't need controls then you can remove the controls attribute to turn them off and clicks on the display.

If you do need controls, then there's not an easy way to turn off clicks on the display. Why do you need that?

**Comment by mmcc** [comment]
Closing this since we haven't heard back and this seems like an implementation question. Feel free to ping this via a comment!
