### ISSUE TITLE
using custom controls and poster on iphones

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2365]
Loading up the player on iphones will currently display our custom controls and our custom poster element. This is an issue because on some iOS versions, our big play button will not work. It seems like on iOS 8, it might work under some circumstances, but I'm not certain it will work across the board.
The best solution is probably to just hide our poster and controls on iphones.
Thoughts, @videojs/core-committers

**Comment by gkatsev** [comment]
Also, `videoEl.controls` is always returning true on iphones, even if I specifically `removeAttribute` it.

**Comment by gkatsev** [comment]
The issue is partly that the tech is supposed to trigger `usingnativecontrols` for the player to listen to but it gets triggered in the constructor, so, the player will never get the event.

**Comment by dmlap** [comment]
I'm inclined to continue displaying native controls on iPhones by default. We should probably take another pass at custom controls some point soon, though.

**Comment by heff** [comment]
@gkatsev did a PR get merged for this?

**Comment by gkatsev** [comment]
Yes. This can be closed.
