### ISSUE TITLE
Disable flash player

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2368]
Hi. I have read that if I use h.264 video and a user visit my player with Opera, the player change from html5 to flash player. There is a way for avoid this? There is a way for put a message to people with Opera to change browser? My player must be only html5. Thank you

**Comment by mmcc** [comment]
You can specify a `techOrder` with just html5 in the array.

```json
videojs('player-id', { techOrder: ['html5'] });
```

**Comment by mister-ben** [comment]
Also, I think the information you've read is out of date. Opera will play h.264 in HTML5 nowadays.
