### ISSUE TITLE
on iOS it shows the duration of the video but on Android, videojs do not display the duration (minutes) of the VOD file (playlist.m3u8 from Wowza)

### ISSUE THREAD

**Issue by htn264** [videojs/video.js#2370]
on iOS it shows the duration of the video but on Android, videojs do not display the duration (minutes) of the VOD file (playlist.m3u8 from Wowza). 
How to fix this?

**Comment by mmcc** [comment]
That sounds like an Android bug. Do you have the same issue in the native player?

Closing this because I don't think there's anything we can do about it. Either way this is probably a better fit for the contrib-hls project.
