### ISSUE TITLE
RTMP: The & to separate connection and  stream is conflict with the & in the connection string

### ISSUE THREAD

**Issue by htn264** [videojs/video.js#2371]
As I know, videojs uses the character & to separate the connection and stream. However, if the connection itself has the character & also, then videojs will run into problem because it detects the first & (which is a part of the connection string), not the last &.  Thus, it took the wrong connection string. 

Where to change in videojs to make it take the last & instead of the first &?  VLC can play the link (without the & that separates connection and stream, only with the & in the connection string), but videojs can not.

**Comment by gkatsev** [comment]
I believe this has been fixed. https://github.com/videojs/video.js/pull/2787
