### ISSUE TITLE
Problem with custom css

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2374]
Hi guys. I have problem using css in my site. So, this is what I got working at http://designer.videojs.com/
: http://s22.postimg.org/pj5vf8bv5/image.jpg

but this is what I get when I copy the css in my site: http://s22.postimg.org/i1s2m9wy9/image.png

Why? What's wrong?

**Comment by mmcc** [comment]
Hi there, please stop opening new issues about this. This is an implementation issue, not a bug with Video.js, so these types of questions should either be continued on your initial, closed issue or moved to something like [StackOverflow](http://stackoverflow.com).

That being said, if you want help debugging, a screenshot isn't going to work. A functional example somewhere like [JSBin](http://jsbin.com/axedog/latest/edit) would go a long way.

**Comment by giggioman00** [comment]
if I put the player inside this code: http://pastebin.com/wSy4pycA

then the skin works corrrectly. If i put the player outside that spoiler code, then it doesn't. Maybe is ita problem of the template? Can you say why in that code the player can work but without that code not? Thank you... Tomorrow I'll use JSBIn anyway

**Comment by giggioman00** [comment]
Hi, here's to you the JSBin. Here the skin doesn't even appear... http://jsbin.com/zapiba/edit?html,console,output

**Comment by giggioman00** [comment]
Update: I tried to replace my custom css with default css and There is the same problem about the bar. So I really think is it a problem of the template... maybe you can take a look please? This is the testing site: http://test994.altervista.org/

Thank you

**Comment by giggioman00** [comment]
EDIT: Nope, it doesn't seems to be a template problem. I changed 3 template, but still I get this problem in every of them. Really, I don't undestand what's wrong... Help please

**Comment by mmcc** [comment]
@giggioman00 You had a bit of PHP code that was causing issues with your video tag (JSBin doesn't support PHP tags). Once I removed that, the player initialized and everything [worked as expected](http://jsbin.com/cahufe/edit?html,output). The icons are busted of course, but that's expected since we're not trying to point the URLs in the right location.
