### ISSUE TITLE
load video on exitFullscreen

### ISSUE THREAD

**Issue by stanceyu** [videojs/video.js#2377]
For mobile devices I've setup my players to play in full screen mode when the whole div is clicked.
I need the player to reload (or at least stop) wen user exit full screen. 
This one definitely not work:
```
video.on('exitFullscreen', function() {
video.load() });
```
I've also experimented with eventlisteners, but nothing seems to work :/

**Comment by gkatsev** [comment]
The event you want to listen for is `fullscreenchange`, then in the listener, you want to check whether it is fullscreen or not via `player.isFullscreen()`.

**Comment by stanceyu** [comment]
Yap! Works perfect! ...got it yesterday, and went to sleeep :D
```
vid.on('fullscreenchange', function() {
	var FS = vid.isFullscreen();
	if(FS == true){vid.play();} else{vid.load();}
	  });
```
Thank you!
