### ISSUE TITLE
Mp4 doesn't play on mobile device

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2380]
So, this is how works my site:

domain1.com - This is where are located my mp4 h.264 aac files
domain2.com - this is a domain where I use .htaccess commando for made a perm. redirect. This is the script used:

Options +SymLinksIfOwnerMatch
RewriteEngine On
RewriteCond %{HTTP_HOST} ^domain2.com$ [NC]
RewriteRule ^(.*)$ http://www.domain1.com/$1 [R=301,L]

domain3.com - This is where there is my main site and where I use video-js.

I notice that if I add link like this domain2.com/file.mp4 in video-js... In computer desktop the video start very well, but in my tablet it doesn't and appears this error: The video could not be loaded, either because the server or network failed or because the format is not supported.

Now: I don't use very much mobile device... So, could I have more information about this? Mayber 301 redirect doesn't work on mobile device? Or there is another reason? Thank you

**Comment by mmcc** [comment]
@giggioman00 This falls under the same lines as my initial response in #2374. Although this is tangentially related to Video.js, it isn't something we have control over so this really isn't the place for questions like this. Please post more general questions about serving HTML5 video to somewhere such as [StackOverflow](http://www.stackoverflow.com).
