### ISSUE TITLE
Component.extend() does not call subclass constructor

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#2383]
1. Create a subclass of Tech using `Tech.extend()` with some fancy constructor logic
1. Create a new instance of your subclass

Expected: your fancy constructor logic is run
Actual: Component's constructor is the only constructor that ran.

**Comment by heff** [comment]
Extending a component [changed](https://github.com/videojs/video.js/wiki/5.0-Change-Details#switched-to-es6-classes-updated-how-you-subclass-components). Use the `videojs.extends()` function now.

We should add a warning to `Component.extend`. It could be possible to shim the old way in 5.0 if it's worth it, but wouldn't be very pretty.

**Comment by dmlap** [comment]
The base tech tests are [using the deprecated way](https://github.com/videojs/video.js/blob/master/test/unit/tech/tech.test.js#L105), then.

**Comment by heff** [comment]
Yeah, that needs to be updated. And I believe that should be failing in IE8.

**Comment by misteroneill** [comment]
@dmlap To be clear, how were you adding "fancy constructor logic" via `Component.extend` - do you mean passing an `init` method to `extend` (in the old style)?

**Comment by heff** [comment]
@misteroneill that would be my guess what he means. In the old way it's the only way to do that.

**Comment by misteroneill** [comment]
After discussing in person, it seems his concern was related to doing `Tech.extend();` instead of `videojs.extends(Tech)`.

Making `Component.extend` work like `videojs.extends` would be a change to a deprecated function; so, we thought the best way forward was to make sure uses of `Component.extend` were removed and a deprecation warning was added.

**Comment by heff** [comment]
Sounds good. And just to be clear, Tech.extend (and extend for any other component besides Component) aren't just deprecated, they no longer work.
