### ISSUE TITLE
VideoJS keep listening "keydown" event, after player was disposed

### ISSUE THREAD

**Issue by vadya-san** [videojs/video.js#2388]
<b>Background</b>
I'm using videojs player inside web-application based on ExtJS framework
Player's instances are created dynamically in a pop-in windows(Using ExtJS framework, Ext.Window component). 
On window-close I'm calling for dispose() on player's instance
But after this, I noticed that vjs.Button.prototype.onKeyPress  still listening for keydown event, and as a result that's causing the problems. 

<b>Especially with next steps:</b>

<ul>
<li>Launch the videojs-player(flash, as I using hls stream)</li>
<li>Go to fullscreen by clicking on a fullscreen icon</li>
<li>Exit fullscreen using ESC key( So no blur event is called on the button, which should clear the listener)</li>
<li>Close the window with player inside my application(which triggers dispose())</li>
<li>Go to any textarea and stroke the ENTER key</li>
<li>See the error at line : "this.el_ is null"    this.el_[fsApi.requestFullscreen]();</li>
</ul>

The easiset way to solve this, is to add  <pre>this.on('dispose', this.onBlur); </pre> to the init method of vjs.Button. Or maybe some another solution exists?

**Comment by heff** [comment]
Thanks for the report. Which version of Video.js are you using?

It does sound like we're not handling the escape scenario well enough. We should be removing the listener when you press escape, but as a fallback we could make sure it's gone on dispose too. Thought I'd think that would already happen with some of the later component event features.

**Comment by vadya-san** [comment]
Version - 4.12.11
Also as I've notices, if I will make extra click inside player(in full screen or after ESC) it also solves the problem, as button loses the focus and blur is fired.

**Comment by heff** [comment]
Any chance you could set up a reduced test case (live example) for this?

**Comment by vadya-san** [comment]
Here you can see the similar behaviour : http://vadym-kovalenko.name/vjs/
<ul>
<li>Run the video</li>
<li>Go fullscreen</li>
<li>ESC to exit fullscreen</li>
<li>ESC to kill the player</li>
<li>focus to textarea and see that ENTER key doesn't work</li>
</ul>

**Comment by mmcc** [comment]
There were some unrelated moving parts in your example so I reproduced with one [a little more stripped down](http://output.jsbin.com/cudoja). Definitely see what you mean.

What if we did both? Call `onBlur` on escape **and** on dispose.

**Comment by vadya-san** [comment]
I think listening for dispose will be enogh, as blur event will be fired anyway, when player is present on the page, and we click somewhere else. Second, ESC, doesn't remove real focus from a button, removing listener will exclude posibility to push selected control via enter key(if user don't want to use mouse)
But, I think, that  dispose should trigger removing listeners anyway. Cause there is no sense in listening for an event, when component which do this, doesn't exists.

**Comment by mmcc** [comment]
@vadya-san want to put together a pull request?

**Comment by vadya-san** [comment]
Nope, do it yourself :)

On Wed, Jul 22, 2015 at 10:28 PM, Matthew McClure <notifications@github.com>
wrote:

> @vadya-san <https://github.com/vadya-san> want to put together a pull
> request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/2388#issuecomment-123835551>.
>



-- 


*Best regards, Vadym Kovalenko.*

**Comment by gkatsev** [comment]
I wonder whether this is an issue in v5. It probably is still, definitely requires investigation, though.

**Comment by gkatsev** [comment]
Looks like this is still a problem in v5.

**Comment by gkatsev** [comment]
I think this is no longer an issue in Video.js 6.x.
