### ISSUE TITLE
Distroying the video player and initializing it again..

### ISSUE THREAD

**Issue by ibnYusrat** [videojs/video.js#2393]
Hello,

I am building an application that lets users customize the VideoJS player in real-time. My Aim is to basically update the video player with new plugin options almost 20 times in a minute. Because some plugins can be enabled and others disabled by the user.. so I have re-initialize the video player all over again to show them the edits.

I tried videojs.dispose, but it removes the original video element too.. 
And there isn't anything such as videojs.distroy (which would simply remove the VideoJS edits).

Can any one please point me to the right direction where such a thing can be achieved?

**Comment by heff** [comment]
The video tag is meant to work as an embed code for the player, so it was never meant to be able to extract the player from the video tag after it's initialized. In fact we need to kill the video element if Flash is used.

Your best option I think is probably to create a function that builds the the video tag html again and initialize the player on a new tag each time.

If you have a live example of what you're doing it might be possible to see other options.

**Comment by mmcc** [comment]
Closing this since I think @heff's comment is probably the best option here.
