### ISSUE TITLE
Execuse me! if i want to play video youtube in IE8 by video.js so how ?

### ISSUE THREAD

**Issue by crviet92** [videojs/video.js#2394]
(English is bad,i'm sorry)

**Comment by mister-ben** [comment]
There's a You Tube plugin to do that. Documentation and example's are on the plugin's own repo: https://github.com/eXon/videojs-youtube

**Comment by crviet92** [comment]
Thanks you,i have seen it but it 's cannot  play in ie8 by flash
This is my code (i don't know make it <> my code</>)


<video  id="example_video_youtube"
        class="video-js vjs-default-skin vjs-big-play-centered" 
        controls="true"
        preload="auto" 
        width="640" 
        height="360" 
        data-setup='{ 
                        "techOrder": ["youtube"],
                        "src": "https://www.youtube.com/watch?v=DrZfYbOr6sE" 
                    }'>
</video>
<video  id="example_video_1" class="video-js vjs-default-skin" 
		controls preload="none" 
		width="640" 
		height="360" 
		data-setup='{"techOrder": ["flash"],
					"src": "https://www.youtube.com/watch?v=DrZfYbOr6sE" 
		}'> 

</video>

**Comment by crviet92** [comment]
<video  id="example_video_youtube"
        class="video-js vjs-default-skin vjs-big-play-centered" 
        controls="true"
        preload="auto" 
        width="640" 
        height="360" 
        data-setup='{ 
                        "techOrder": ["youtube"],
                        "src": "https://www.youtube.com/watch?v=DrZfYbOr6sE" 
                    }'>
</video>
<video  id="example_video_1" class="video-js vjs-default-skin" 
		controls preload="none" 
		width="640" 
		height="360" 
		data-setup='{"techOrder": ["flash"],
					"src": "https://www.youtube.com/watch?v=DrZfYbOr6sE" 
		}'>

**Comment by crviet92** [comment]
<pre>
    <video  id="example_video_youtube"
        class="video-js vjs-default-skin vjs-big-play-centered" 
        controls="true"
        preload="auto" 
        width="640" 
        height="360" 
        data-setup='{ 
                        "techOrder": ["youtube"],
                        "src": "https://www.youtube.com/watch?v=DrZfYbOr6sE" 
                    }'>
</video>
<video  id="example_video_1" class="video-js vjs-default-skin" 
		controls preload="none" 
		width="640" 
		height="360" 
		data-setup='{"techOrder": ["flash"],
					"src": "https://www.youtube.com/watch?v=DrZfYbOr6sE" 
		}'> 

</pre>.

**Comment by crviet92** [comment]
thanks you,i have seen it but it cannot play in ie8 by flash
