### ISSUE TITLE
cc performs differently on firefox - weird menu pops up (see attached)  - never shows captions

### ISSUE THREAD

**Issue by lomok** [videojs/video.js#2397]
I get by default a chooser window when I try to select something in off the cc tab.

It does not seem to be functional and all menus have a solid white background that shows no options. Also, and this has happened on a pc with chrome, the cc menu is in times-roman, as if it is defaulting to a typeface it cannot find.

![screen shot 2015-07-20 at 1 41 35 pm](https://cloud.githubusercontent.com/assets/3836962/8837819/37a1f858-307d-11e5-8f89-872bbfc843f8.png)

**Comment by chemoish** [comment]
Firefox 40.0.3

videojs@4.12.15
vtt.js@0.12.1

**does NOT work with videojs**

![screen shot 2015-10-14 at 5 32 55 pm](https://cloud.githubusercontent.com/assets/549319/10501789/ac71ecf2-7299-11e5-937f-7b983f245fe4.png)

![screen shot 2015-10-14 at 5 33 06 pm](https://cloud.githubusercontent.com/assets/549319/10501788/ac6268d6-7299-11e5-95d9-bfeb906cbcab.png)

**DOES work natively**

![screen shot 2015-10-14 at 5 36 43 pm](https://cloud.githubusercontent.com/assets/549319/10501827/2d67e2ee-729a-11e5-96a1-f3c08fb046a0.png)

**Comment by gkatsev** [comment]
I think the color thing might be fixed. But I'll have to verify it.

**Comment by gkatsev** [comment]
Seems to be working. closing.
