### ISSUE TITLE
Responsive sizing

### ISSUE THREAD

**Issue by jpeg729** [videojs/video.js#2399]
I tried using the percentage top padding trick with a wrapper element to have a responsive video player with a fixed width-height ratio. 

## What I tried
Contrary to the docs I set height=100% and width=100% on the player element.

## Result
the video element gets reset to 300x150.

## Desired result
In any case it would try to respect dimensions set to 100% on the video element.

**Comment by mmcc** [comment]
If you're trying to do the padding trick, you should be setting width / height to auto on the player, then specifiying 100% width on the .video-js wrapper div (along with the `padding-top` for the "hack").

If you're using 5.0, there's now fluid width features pulled in: #1952.

**Comment by jpeg729** [comment]
## Take 2
100% width and the padding-top on the wrapper div.
Width & height auto on the player

### Result
The video loads extra large and resizes itself into the desired size.
But the bar of controls is still in the 300x150 position.

Is 5.0 on the cdn, or do I need to host it myself?

**Comment by heff** [comment]
You can use rawgit.com pointing at a release tag, until we officially release 5.0.
https://cdn.rawgit.com/videojs/video.js/v5.0.0-rc.24/dist/video.js

**Comment by jpeg729** [comment]
Thanks, it works a treat.

**Comment by mmcc** [comment]
@jpeg729 Excellent! If you get a chance to kick the tires with it let us know what you think :)
