### ISSUE TITLE
VideoJS and Googlebot in webmaster tools

### ISSUE THREAD

**Issue by Sattar1** [videojs/video.js#2400]
Hi.
Fetching any video page of my website as Google in webmaster tools, Google says "No compatible source was found for this video."
I am using VideoJS script to play the videos and providing mp4 files, with HTML5 tech (and flash fallback as the second tech)
Here is a link to one of my video pages:
https://goo.gl/mqRgLR
Here is a link to an image of webmaster tools and Google error:
http://img.majidonline.com/pic/316855/1.png

Please note that although Google has indexed my video pages, but it is not showing my videos in video search (and it is not showing the video rich snippets too). 
I guess the problem above might be one of the reasons. any idea or help?
Thanks.

**Comment by mmcc** [comment]
I *highly* doubt that Googlebot actually tries to play back video. You can try with a vanilla video element, but I think you're going to see the same results.
