### ISSUE TITLE
Backward Compatibility Audit

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#2402]
I'm doing a run-through of the 4.x documentation and objects to look for properties and methods that are missing from the 5.x work or whose fate is otherwise unclear or undocumented in the wiki. A lot of this is up for discussion, but I wanted to get it in one place where we can all see it.

### Globals

Global | Resolution
--- | ---
`vjs` | _Document_

### `videojs` Properties

Property | Resolution
--- | ---
`JSON` | _Document_
`TOUCH_ENABLED` | _Restore_
`cache` | _Ignore_
`media` | _Ignore_
`options` | _Restore_ #2395 
`players` | _Restore_ #2395 
`util` | _Document_ No longer needed.

### `videojs` Methods

Method | Resolution
--- | ---
`bind` | _Document_ Wiki says removed, but was restored.
`createTimeRange` | _Document_ Wiki says removed, but was restored.
`parseUrl` | _Restore_
`round` | _Restore_
`trim` | _Restore_
`util.mergeOptions` | _Document_ Now top-level.

### Classes

Class | Resolution
--- | ---
`CoreObject` | _Document_
`EventEmitter` | _Restore_ as `EventTarget`
`MediaTechController` | _Document_

### Components

Component | Resolution
--- | ---
`SeekHandle` | _Document_ Moved to CSS
`SliderHandle` | _Document_ Moved to CSS
`VolumeHandle` | _Document_ Moved to CSS

### Other

Object | Resolution
--- | ---
`Component#init` | _Remove_ Shim and deprecate.

### Player

Property/Method | Resolution
--- | ---
`cancelFullScreen` | _Remove_ Had been deprecated in 4.x.
`getTagSettings` | _Document_ Now static.
`isFullScreen` | _Remove_ Had been deprecated in 4.x.
`onDurationChange` | _Document_ `handleTechDurationChange`
`onEnded` | _Document_ `handleTechEnded`
`onError` | _Document_ `handleTechError`
`onFirstPlay` | _Document_ `handleTechFirstPlay`
`onFullscreenChange` | _Document_ `handleFullscreenChange` / `handleTechFullscreenChange`
`onLoadStart` | _Document_ `handleTechLoadStart`
`onLoadedAllData` | _Document_ `handleLoadedAllData`
`onLoadedMetaData` | _Document_ `handleTechLoadedMetaData`
`onLoadedData` | _Document_ `handleTechLoadedData`
`onPause` | _Document_ `handleTechPause`
`onPlay` | _Document_ `handleTechPlay`
`onProgress` | _Document_ `handleTechProgress`
`onSeeked` | _Document_ `handleTechSeeked`
`onSeeking` | _Document_ `handleTechSeeking`
`onTimeUpdate` | _Document_ `handleTechTimeUpdate`
`onVolumeChange` | _Document_ `handleTechVolumeChange`
`onWaitEnd` | _Document_ Removed.
`onWaiting` | _Document_ `handleTechWaiting`
`requestFullScreen` | _Remove_ Had been deprecated in 4.x.

**Comment by dmlap** [comment]
I vote to re-export `TOUCH_ENABLED` and `EventEmitter`.

**Comment by misteroneill** [comment]
I'm curious why `EventEmitter` would be exported? It seems like the sort of thing that is outside the scope of the public API of a library like VideoJS.

**Comment by gkatsev** [comment]
I don't see why not export it. It could be useful.
Also, if it's available via `getComponents`, that counts as exported.

**Comment by misteroneill** [comment]
My concern was sort of two-fold. First, it increases the surface area of the API, which increases the cost of maintenance/support. Second, that it wasn't part of the core competency of VideoJS.

It's not available via `getComponent`.

**Comment by dmlap** [comment]
I was hoping EventEmitter would get exported because we've re-implemented it in videojs-contrib-media-sources and videojs-contrib-hls. That said, I agree it's outside the core competency of video.js and may not have broad applicability for plugins.

**Comment by misteroneill** [comment]
Well, if it's being used in plugins, then I would revise my position and say that `EventEmitter` should be exported. :)

**Comment by gkatsev** [comment]
Our event emitter implementation is the bare minimum and it is required for the text track work. There won't be any changes to it.

**Comment by heff** [comment]
Can we at least rename EventEmitter to [MockEventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) or something else that has less expectations behind it? EventEmitter sounds like we're building all our components off it but we just use it to emulate an element for tracks.

**Comment by heff** [comment]
@misteroneill this is awesome, thanks for putting it together.

- `vjs` -  This wasn't exported in the minified version and shouldn't be in any docs/guides. I guess we could still make a note for anyone relying on video.dev.js.
- `JSON` - Probably worth a deprecation warning since it was exported before
- `cache` - No need to document. Only used internally.
- `media` - No need to document. There was nothing in it.
- `parseUrl`, `round`,`trim` - Re-add? With these I was hoping we'd have more time to revisit our strategy for them. Do we need them, can we pull in a module for them instead, etc.
- `*Handle` - Handles live in CSS land now
- `MediaLoader` - This [should be there](https://github.com/videojs/video.js/blob/8be7810049c5b18eead67cbc656d416fe9d8668c/src/js/tech/loader.js#L47)
- `Component#init` - The function you mentioned can be removed. Whether or not we want to shim init is another question.

**Comment by misteroneill** [comment]
No problem! I've updated the tables with your feedback @heff. You're right that `MediaLoader` is there. Not sure where that came from.

What do you mean by shimming `init`? Maybe keeping it around with a deprecation warning?

Also, added `util` to the tables.

**Comment by dmlap** [comment]
I'm fine with renaming the EventEmitter but can we avoid using the adjective "Mock"? That's strongly associated with testing in my mind and the EventEmitter is intended for more than just unit testing.

**Comment by gkatsev** [comment]
I came here to say I could be convinced to rename `EventEmitter` to `EventTarget` but @dmlap basically said what I was thinking.

**Comment by gkatsev** [comment]
@misteroneill btw, vjs 4.0 had a bunch of helper functions that were available in the dev version (but not the minified version due to GCC's minification). For example `videojs.obj.isArray`. Would be great if you can find what we had previously.

**Comment by gkatsev** [comment]
@misteroneill in 5.0 we're no longer using Component's `init`. That was our old way of specifying constructors. So, if we want to keep it, we'll need to shim it so that the old `init` works like our new constructor method. See https://github.com/videojs/video.js/wiki/5.0-Change-Details#switched-to-es6-classes-updated-how-you-subclass-components

**Comment by heff** [comment]
(man, I'm totally gonna change my username to misterheff. It makes every response sound so respectful!)

:+1: EventTarget

There's levels of backwards compatibility we can support for component initialization. `init` alone wouldn't be hard. I'll try to summarize the rest later.

**Comment by misteroneill** [comment]
I demand formality in all things! (Actually, it's just that I have a common name/first initial, so a bunch of usernames and domains have been long-registered)

@gkatsev Interesting re: `videojs.obj.*` and similar. I've added a few of these from the unmangled version of VJS 4.x in case there's interest in restoring them. I'll keep digging.

**Comment by misteroneill** [comment]
Ok, so, in going through 4.x's `lib.js` it looks like the unmangled version had a _lot_ of functions that are not present in 5.0. Does it make sense to document each of these... or not?

**Comment by gkatsev** [comment]
Most of the stuff wasn't exported, so, documentation isn't necessary. However, a lot of those are super useful and we definitely should export them.
Stuff like `videojs.obj.isArray` however isn't necessary because for 5.0 we assume es5 or es5-shim, so, it should be available globally.

**Comment by misteroneill** [comment]
Alright, in that case, let's make a separate issue for things that were previously not exported and would be nice to export in 5.0. I don't want to lose focus of the purpose of this ticket - finding methods of `videojs` and `Player` that were lost in the transition to 5.0.

**Comment by misteroneill** [comment]
For `init` support, I'm thinking the simplest path forward is something like:

```js
if (typeof subClassMethods.init === 'function') {
  log.warn('The "init" method is deprecated in favor of "constructor".');
  subClassMethods.constructor = subClassMethods.init;
  delete subClassMethods.init;
}
```

Opinions?

**Comment by imbcmdth** [comment]
Time to put my :bike: in the shed. `EventTarget` sounds like something that receives events.. maybe `EventSource`? :smiley:

**Comment by gkatsev** [comment]
EventTarget is the name the DOM uses for it's EventEmitter implementation that DOM Elements extend from.

**Comment by imbcmdth** [comment]
@gkatsev I concede.

**Comment by gkatsev** [comment]
I still would prefer to keep EventEmitter.

**Comment by misteroneill** [comment]
Updated [wiki document](https://github.com/videojs/video.js/wiki/5.0-Change-Details#removals-and-changes) to reflect these changes/removals.

**Comment by misteroneill** [comment]
Upon further investigation, `trim` does not exist in the codebase anymore, so I'm changing it to _Remove_ from _Restore_.

**Comment by misteroneill** [comment]
Closing this in favor of PR #2406. Changes are moved to the wiki, which is the canonical source for changes/removals instead of this ticket.
