### ISSUE TITLE
Uploaded videos are not playing on mobile browser but are playing on desktop broswer

### ISSUE THREAD

**Issue by robinlery** [videojs/video.js#2404]
I have set up a server (gunicorn and nginx) to upload videos using python/django, and watch them in the browser. The video player I am using is videojs. All the videos are h.264 mp4. And the video size are between 5-40 MB. 

The video uploads fine and I can watch the uploaded video on the desktop and laptop browser too.

The problem is that I can't watch the same videos (which are playing on the desktop browser) on the mobile devices. 

I get this error:

> This video could not be loaded, either because the server or network failed or because the format is not supported.

And this for h.264 mp4 (only working firefox):

    ffmpeg -i inputfile.avi -codec:v libx264 -profile:v baseline -preset slow -b:v 250k -maxrate 250k -bufsize 500k -vf scale=-1:360 -threads 0 -codec:a libfdk_aac -b:a 96k output.mp4

Here are some points that I gathered along the way:

 1. Some of the videos which I downloaded from youtube and uploaded it on the server without encoding are playing nicely on all the browsers.
 2. However if I encode the same video (youtube video) and upload it on the server, it does not play on the mobile devices but only on desktop browsers.
 3. Videos which I took from my mobile (samsung s4 and iphone 6), and encode it with ffmpeg are not playing on the mobile browsers, only on desktop browsers.
 4. But, the url of the same videos (which I took from mobile) which are hosted on amazon s3 are playing nicely on all the browsers (even the non encoded videos).

What is wrong? Can you please help me out. Thank you.

**Comment by mmcc** [comment]
Do you have one of the troublesome encoded files online? Mind linking me so I can take a look? My first assumption was that you were using too advanced of a profile, but baseline should work with pretty much anything that supports h.264 so I don't think that's the case.

I'm going to close this because it's not actually a Video.js issue, but I'm happy to continue the conversation in the comments.
