### ISSUE TITLE
Make errors more generic. It won't always be "video"

### ISSUE THREAD

**Issue by sirlancelot** [videojs/video.js#2407]
If an error occurs while trying to play an audio file, I still get the generic "The video could not be loaded, either because the server or network failed or because the format is not supported." error message. Since video.js can play audio files as well, "video" should be changed to "media" or similar.

**Comment by mmcc** [comment]
Ah good point, it's pretty easy to forget about the audio-only use case. Interested in putting a PR together to make the messages more generic?

**Comment by gkatsev** [comment]
PRed and fixed.
