### ISSUE TITLE
Streaming in HTML // RTMP

### ISSUE THREAD

**Issue by Dermiste** [videojs/video.js#2410]
Hi,

I read that videoJS support RTMP in the flash fallback. I am working at this moment on a product that could seriously benefit from live RTMP streaming in the browser without flash.

Where is VideoJS at this moment regarding this? Is it safe to expect some prototype in the next year, in RTMP or a different format?

Thanks

**Comment by mmcc** [comment]
You are correct, there is RTMP support in the Flash fallback. Where we are is most likely where we'll stay in terms of RTMP support, at least in the core player / fallback. If anymore work there is done, it will be in the form of 3rd party plugins.

But regardless, RTMP without Flash is probably not going to happen. If you want live streaming via HTML5, your best bet is either [HLS](https://github.com/videojs/videojs-contrib-hls) or [Dash](https://github.com/videojs/videojs-contrib-dash), both of which are actively worked on.

Hope that helps!

**Comment by Dermiste** [comment]
Thank you for that ! I new about these formats but didn't there were some plugin for VideoJS allowing their support.

That helped!
