### ISSUE TITLE
Bubbling Issues in IE8

### ISSUE THREAD

**Issue by mmcc** [videojs/video.js#2414]
Noticed this while testing #2378, but event bubbling on the VolumeMenuButton menu seems to be busted in IE8 in master right now. Just tested to confirm, and it appears that the Captions menu is functioning as expected, so as far as I can tell, this seems to be VolumeMenuButton-specific.

To reproduce, try and use the volumeMenuButton in IE8 (in any configuration, inline or not). Things should appear to work normally until you finish adjusting the volume and mouseup. The volume will mute (or unmute) instead of staying at the intended location. Click, change volume, drag off the menu before mouseup, and the volume stays in the desired location.

@heff and I sprinkled a heavy dose of event `console.log`s around and so far the only thing we're sure of is that bubbling is broke in the component.

**Comment by heff** [comment]
What we found is that no matter how much we did event.preventDefault/stopPropagation/bubbles:false, on all levels of the slider, the click still bubbled up to the main control component, which is the mute button. Need to keep digging to try to keep that from happening.
