### ISSUE TITLE
Change Source fallback not load flv video

### ISSUE THREAD

**Issue by sufyandeveloper** [videojs/video.js#2416]
I have many sources in video player so i have created a function which change source if previous source not play or give an error its successfully working but problem is that you can see first two sources are mp4 and both are not valid sources its give an error so my function change source to last flv source and video.js successfully convert into flash player but video not play i don't what the problem is this and when i play this flv source separately with no other mp4 sources its play very well.
i hope you understand my problem.

`<video id="video__html5_api" class="vjs-tech" data-setup="{}" src="http://test.to/getac/9ug2alhggji0" __idm_id__="218113">
 <source src="http://test.to/getac/9ug2alhggji0" type="video/mp4">
<source src="http://test.to/getac/abc2alhggji0" type="video/mp4">
<source src="http://test.to/getah/df06a5da208d0" type="video/x-flv">
</video>`

here is my code of change source 

        `var save = [];
	     changeSource = function(){
			var error = myPlayer.error();
			if(error.code == 3 || error.code == 4){

				currentSource = myPlayer.currentSrc();
				if(save.length === 0){
					save = myPlayer.options().sources;
				}
				sourceRemoved = save.filter(function (el) {
		                        return el.src !== currentSource;
		                       });
				save = sourceRemoved; 
			}
			myPlayer.src(save);
		}
		myPlayer.on('error',changeSource);`

**Comment by heff** [comment]
Do you think you could set up a jsbin showing the issue? http://jsbin.com/axedog

**Comment by sufyandeveloper** [comment]
ok sir i am glad to conversation with you :) you are awesome developer and i also watch your tutorial on lynda about html 5 video its awesome

**Comment by heff** [comment]
thank you! :smile: 

Did you solve your problem or is there something else you need help with? Closing the issue for now but let me know otherwise.

**Comment by sufyandeveloper** [comment]
Hello sir i was very busy no sir my problem is not solved here is my jsbin http://jsbin.com/zoyocigimi sir when my player have both formats mp4 and flv and you know my functionality is change source when first source is not played it's load flv and video.js successfully change into flash player but video not played :( i don't know how to do this and sorry for late reply

**Comment by heff** [comment]
When I open this copy of your jsbin in chrome, it does work for me.
http://output.jsbin.com/cataco/1
