### ISSUE TITLE
How to set captions to be on in the data-setup

### ISSUE THREAD

**Issue by jbwyatt4** [videojs/video.js#2417]
My apologies if this has been asked before.

I want the captions to be automatically turned on. How I can I set them?

I tried in the data-setup:

data-setup="{'captions':'on'}"

or

data-setup="{'captions':true}"

**Comment by heff** [comment]
You should be able to add the 'default' attribute to the captions track you
want to show. I remember there being a bug around that though so comment
here if that doesn't work.
>
>

-- 
Sent from mobile

**Comment by mmcc** [comment]
Closing, but if you run into a bug please let us know.
