### ISSUE TITLE
iOS page crashes when video is played

### ISSUE THREAD

**Issue by isaacminogue** [videojs/video.js#2419]
On iOS emulator (I don't have an actual iphone to test) once the video is played (sometimes on first play, sometimes on second or third) the javascript crashes the page, giving the message "A problem occured with this webpage so it was reloaded." Happens on my local, as well as with the hero video on videojs.com. Non mobile browsers seem fine. Here is a gif showing the behavior.

![video js crashing](https://cloud.githubusercontent.com/assets/10933880/9000031/0ddfb1b6-3796-11e5-8ab4-b789646fbbc4.gif)

**Comment by zhanghan177** [comment]
Does it work on Mac Safari?

**Comment by isaacminogue** [comment]
Yeah, it does. It works fine.
But if I use v 4.12 (latest) on iOS, the custom controls are visible, but
it crashes when played.

**Comment by mmcc** [comment]
Are we sure this isn't emulator-specific? I'm having no issues on my phone and emulators in general are notoriously bad at video. 



—

**Comment by heff** [comment]
Also the `file:///` url of the page can add additional weirdness in testing that you may not see with an http url.

**Comment by isaacminogue** [comment]
Yeah, it must be just the emulator – it has some weird stuff happening.
I'll check today on an actual iPhone. Sorry for the hassle! Just thought
I'd check.

**Comment by gkatsev** [comment]
Sounds like all issues are resolved here, closing.
