### ISSUE TITLE
Text display flashes in the browser at video initialization

### ISSUE THREAD

**Issue by zrehmani** [videojs/video.js#2428]
I sometimes see a quick flash of some text on the desktop browser page before the video element initializes.  It disappears quickly so I can't tell what it is.  Is there any way to turn this off?

**Comment by mmcc** [comment]
Mind pointing us to an example? My only guess is the "unsupported" error, but you shouldn't really ever see that flash.

**Comment by mmcc** [comment]
Closing until we hear back with an example

**Comment by zrehmani** [comment]
![screen shot 2015-09-08 at 9 17 41 am](https://cloud.githubusercontent.com/assets/266330/9772586/25846ade-570b-11e5-8635-6830ca63b47e.png)

**Comment by zrehmani** [comment]
It's hard to grab it because when it does show up - its like a quick flicker right at the start.  Happens once in a blue moon but still happens.  This time it stayed for a bit longer and I was able to take a screenshot.  I can't believe this is only happening to me but I would obviously like to make sure it never shows up in production and how to turn it off.

**Comment by mmcc** [comment]
What you're seeing means that the Video.js CSS isn't included at all (or, at least, not working).
