### ISSUE TITLE
Video js throwing error: CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED

### ISSUE THREAD

**Issue by satyamnigam** [videojs/video.js#2429]
I am using video js v1.12.11. When I load video in a webpage, I am getting below error in the console:

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported.

Can some one please help me.

**Comment by mmcc** [comment]
This error can usually be taken at face value. A vast majority of the time this means the browser doesn't support the file format you're trying to use (and neither does the Flash fallback).

**Comment by YexuanGuo** [comment]
I've had the same problem. ...

**Comment by zhougq1989** [comment]
I've had the same problem. ...

**Comment by Tinywan** [comment]
video.js:22885 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either 

because the server or network failed or because the format is not supported.

**Comment by hartman** [comment]
This error is an indicator for a lot of potential problems. It basically means. "Could not find a playback engine that wants to play this source".

Please check:
1: The url actually work. Does it return something ?
2: Does the source specify the right codec ?
3: Does the URL return the right content type
4: Does the URL return range headers ?
5: When it's a HTML 5 native source, does it work without video.js ?

etc etc etc.

**Comment by Tinywan** [comment]
Hi! @hartman 
This question has been resolved, Thank you!

**Comment by hammadtariq** [comment]
I faced a similar issue and realized from @hartman  comment that I wasn't sending range headers
so followed this article and got it working fine 
https://www.codeproject.com/articles/813480/http-partial-content-in-node-js
