### ISSUE TITLE
Video.js doesn't work on IE

### ISSUE THREAD

**Issue by vanduzled** [videojs/video.js#2430]
Is there any fallback when a video.js is played on IE? I'm using the latest version of IE on windows 7 but it doesn't work.

![image](https://cloud.githubusercontent.com/assets/3022660/9052855/452a9170-3a9f-11e5-8002-858630c1dc11.png)

**Comment by mmcc** [comment]
It works on IE11 for me, but this was recently covered in [another issue](https://github.com/videojs/video.js/issues/2301)
