### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2434]
how can I change default languages in your player?

Already tried with
data-setup='{"language":"it"}'>  
but doesn't work, still load english language

**Comment by mmcc** [comment]
Have you imported the appropriate language file? [Working example](http://jsbin.com/zabowa/edit?html)

**Comment by tonykor** [comment]
Hello, can i ask how to use it on static (cached) pages? Load all the language files (lang/ folder)? So users from different countries can get the correct translation on cached pages? Is there any better way to do this, as making many requests to language files, where only one will be used is not very efficient, as for me.
