### ISSUE TITLE
initialize callback function not triggered

### ISSUE THREAD

**Issue by Vuuo** [videojs/video.js#2435]
The initialize callback function is not triggered some how.

Environment: Ubuntu 14.04, Firefox 39.0, Flash disabled

```html
<video id="videojs_player" class="video-js vjs-default-skin" controls preload="none" width="100%" height="auto" poster="<%= @video.thumbnail_url %>" data-setup='{"techOrder": ["flash", "html5"]}'>
      <source src="<%= @video.mp4_video_url %>" type='video/mp4'>
      <source src="<%= @video.webm_video_url %>" type='video/webm'>
      <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
      </p>
</video>
```
```javascript
(function() {
  $(document).ready(function() {
    var player;
    if ($('#videojs_player').length) {
      console.log("vjs init");
      return player = videojs("videojs_player", {}, function() {
        return console.log("Good to go!");
      });
    }
  });
}).call(this);
```

I can't see "Good to go!" in my console.

**Comment by heff** [comment]
If you're trying to initialize the player only after the document has loaded, then remove the `data-setup` attribute from the video tag and move those options to the options block before your ready function.

If you don't care when it's initialized then use `videojs("videojs_player").ready(function(){...})` instead. The data-setup attribute replaces the init step, so right now you're creating the player twice.

**Comment by Vuuo** [comment]
I see. Thank you for your explanation.
