### ISSUE TITLE
Track metadata issues with video.js#4.12.12

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#2436]
This works on `Video.dev.js#4.12.12`.

`Video.js#4.12.12` throws the following:

![screen shot 2015-08-04 at 3 03 02 pm](https://cloud.githubusercontent.com/assets/549319/9073933/f797b260-3ab9-11e5-9808-c321aadb4166.png)

Maybe:
```js
track.track['kind'] // from

track['track']['kind'] // to?
```

**Comment by heff** [comment]
@gkatsev is this related to the one already being fixed or is it new? At least sounds related to #2412.

@chemoish if you want to try moving to 5.0, we're not mangling anymore so shouldn't be an issue. http://jsbin.com/sofiwu/edit?html,console,output

**Comment by gkatsev** [comment]
Yeah, it's a silly mistake. We could probably fix it as part of #2412 (yay gcc...)

**Comment by gkatsev** [comment]
This will be removed as part of #2468 and #2475.

**Comment by gkatsev** [comment]
This should be fixed in stable now. https://github.com/gkatsev/video.js/commit/a02f0befbce7808aeb0d84f3a3cea817949a1cb2

**Comment by chemoish** [comment]
@gkatsev I am receiving an undefined track after this update.

Can you verify?

![screen shot 2015-08-28 at 2 10 07 pm](https://cloud.githubusercontent.com/assets/549319/9557165/9347dad2-4d8e-11e5-9099-7ed4ca8d1a0f.png)

https://github.com/videojs/video.js/blob/stable/src/js/tracks/text-track-list.js#L78

**Comment by chemoish** [comment]
Moving this to a new issue.
