### ISSUE TITLE
VideoJS - swf Loaded Metadata event only triggers on play button

### ISSUE THREAD

**Issue by cgeo7** [videojs/video.js#2439]
I am using exclusively the flash player (videojs - swf) so I can play various flv files. However, I also want to get their metadata one it is loaded. The metadata event is triggered though only after I push the "play" button. Please have a look at the SO below for more details:

The code is as follows
```
<video id="web_video" class="video-js vjs-default-skin" width="auto" height="auto"></video >

var player = videojs('web_video', {controls: true, autoplay: false, preload: "metadata"})
            .src({type: "video/flv", src: "path/to/my/video"})

player.ready = function() {
    var video = $('#web_video_flash_api').get(0)
    video.player.on('loadedmetadata', function(){alert("Loaded!!!"}))
}
```

Alternatively I have also tried the following with no luck...

```
videojs('web_video', {controls: true, autoplay: false, preload: "metadata"})
.src({type: scope.videoType, src: scope.videoSrc})
		.on('loadedmetadata', function(){alert("Yupiii!!!")})
```

**Comment by heff** [comment]
What video.js version are you using?

**Comment by cgeo7** [comment]
I'm using 4.12.12

**Comment by heff** [comment]
I submit an issue on the swf repo to see if anything changed.
https://github.com/videojs/video-js-swf/issues/177

If you can test if it still happens in older versions, e.g. 4.5 that would out a lot. Especially if we can determine which version the change happened in.

**Comment by bclwhitaker** [comment]
The preload attribute is only partially supported in the swf.  Setting it to `preload="metadata"` is equivalent to `preload="none"`.  If the preload attribute is changed to `preload="auto"` the loadedmetadata event will fire before play but you will also get the download hit.

**Comment by heff** [comment]
Ah, makes sense. There's not really an equivalent to only loading the metadata in flash. Thanks @bclwhitaker!
