### ISSUE TITLE
Fullscreen problem: Video cutted

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2440]
Hi guys, if I try to play 16:9 videos the fullscreen mode works very well, but if I need to play non-standard video resolution (just like 480*552) then when I use fullscreen the video is cutted and there is a big black padding on the top. How can I fix?

**Comment by heff** [comment]
That doesn't sound normal. Is there a live example of that somewhere we can look at?

**Comment by giggioman00** [comment]
Yes... How can I send you the link in private?

Anmyway, please note that I used this tutorial for made my videojs responsive: http://coolestguidesontheplanet.com/videodrome/videojs/

Maybe that code is the problem?

**Comment by heff** [comment]
Yeah, it's most definitely an issue with external code then, though I'm not sure what exactly. You might try 5.0 with built-in responsive support.
http://jsbin.com/pibici/edit?html,console,output
