### ISSUE TITLE
Poster not sizing correctly

### ISSUE THREAD

**Issue by iamthestreets** [videojs/video.js#2442]
When I first load my page the poster image is displayed, but it does not fit to the same width as the control bar. See screenshot.

![poster](https://cloud.githubusercontent.com/assets/8740821/9122034/57a85a38-3c54-11e5-9917-d1aca8e8fbaf.png)

notice the bottom left and bottom right of the poster is not the same width as the control bar. When I click play the video is then resized and everything looks ok. 

How do I fix this?

**Comment by mmcc** [comment]
Have you checked the size of the poster vs the video? Frequently thumbnails will end up a few px different from the actual video content. Your easiest route is probably going to be to use CSS to just slightly stretch the poster image to fill all available space.

**Comment by iamthestreets** [comment]
I have the css width and height of the poster set 100% and no matter what I change it does not fill in the spaces.

**Comment by mmcc** [comment]
It *might* be something specific with the Flat-UI skin you're using, but considering their demo looks fine, I'm pretty sure this is something specific to your implementation.

![screenshot](https://cloudup.com/cSY4AoIEs-k+)

**Comment by iamthestreets** [comment]
Ok I will take a little again, but I have not made any changes to the existing implementation. Thanks!

I asked a question about adding more controls such as the volume slider, but they have not responded. Can you help me with that? I can create another issue if I need.

https://github.com/designmodo/Flat-UI-Pro-Support/issues/522

**Comment by mmcc** [comment]
Sorry, we've got no relationship with Designmodo (although the skin looks *great*), so we can't really help there.

**Comment by iamthestreets** [comment]
Thanks any ways! I was able to fix the sizing issue. When I was creating a poster during my video conversion I was not sizing with the correct dimensions, but now everything is looking good.
