### ISSUE TITLE
IE 8, only on CO version - bug

### ISSUE THREAD

**Issue by adriel** [videojs/video.js#2452]
It seems this bug only occurs on the corporate laptop, not my IE8 in a VM Win7. The only difference in version is that the work one has "CO" at the end of the version number, and my IE8 is 64bit.

So the bug is on line 8730:
` Object.defineProperty(list, 'length', {
    get: function() {
      return this.tracks_.length;
    }
  });`

If I comment this out it works fine, otherwise I get a "TypeError: Object doesn't support this property or method"

**Comment by heff** [comment]
Your corporate laptop has a version with CO at the end? Which version of video.js are you using?

**Comment by adriel** [comment]
Yeah the corp laptop has the CO version. I'm using v4.12.11

**Comment by heff** [comment]
Your IE is probably going in compatibility mode for some reason. Any idea why? That function is only available in the normal standards mode.

**Comment by adriel** [comment]
That's what I thought, but when I checked the Dev tools menu (F12) it reported it was running IE 8 Standards mode. The whole site falls apart going any lower.

**Comment by heff** [comment]
I'm not seeing the issue on my VM either. I don't know that we can help much more unless we can narrow in on the specific difference.

**Comment by adriel** [comment]
It's alright, we're used to these strange bugs on the IE we have here. I've reverted to a pure flash based video player, not ideal but will work. Thanks for your help.
