### ISSUE TITLE
PR #2391 / #2425 break dispose when no native tt is supported

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2454]
Now that #2391 / #2425 is merged into master, it breaks disposing the player element in at least IE9 and IE10.

I think this is because those do not support native text tracks and the code removes event listeners on those elements.

See http://jsbin.com/tilobifaza/edit?html,output for a JSBin that fails in those browsers.

**Comment by gkatsev** [comment]
You're right. We need to do a null check before trying to remove or add the event listeners. Mind putting a PR for that?

**Comment by gkatsev** [comment]
Looks like this is causing issues in our CI. I'll take that on now.

**Comment by heff** [comment]
Now that #2466 is merged in, can we verify if this can be close?

**Comment by nickygerritsen** [comment]
I already applied it manually yesterday and my tests passed, so this can indeed be closed.

**Comment by heff** [comment]
Great! Thanks @nickygerritsen.
