### ISSUE TITLE
'contrib feature accept' should probably run 'npm install' before running grunt

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2458]
If you have a new clone, or a PR updates the dependencies, we probably want to get those installed before running the tests when we're trying to merge a PR or patch.

**Comment by heff** [comment]
Yeah, especially now that we have non-dev dependencies. `contrib update master` (and stable) should probably have npm install added to them too.

**Comment by gkatsev** [comment]
We're moving away from contrib for this type of work.
