### ISSUE TITLE
IE11 doesn't fire addtrack or removetrack events on native text tracks

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2465]
I noticed this as part of trying to fix tests in master for #2454. Some of the async tests would hang because these events would never fire.
It would be nice to see if we can fake these events but we probably can't.

**Comment by gkatsev** [comment]
One way to fix it is to force emulated captions for browsers that cannot fire the `removetrack` event.
```js
'removetrack' in Html5.TEST_VID.textTracks
```

**Comment by gkatsev** [comment]
Thoughts, @videojs/core-committers

**Comment by heff** [comment]
It looks like IE has an onaddtrack property, but it only works if you use the addTextTrack API...boo. Is there somewhere we can submit a bug for IE?

Seems like we'll need the native one if projects like dash.js are interacting with the video element directly, so this seems reasonable. You probably need to change 'removetrack' to 'onremovetrack'

**Comment by gkatsev** [comment]
Oops, yep, I meant `onremovetrack`. We could probably file a bug on modern.ie. I'll look into doing that.

**Comment by gkatsev** [comment]
Looks like IE11 doesn't fir it if we attach the events via `onaddtrack` or `onremovetrack`. Will file an issue with them. Possibly the same issue as #2438.

**Comment by gkatsev** [comment]
Yep, looks like Edge is the same issue.

**Comment by gkatsev** [comment]
And filed a bug against IE11: https://connect.microsoft.com/IE/feedbackdetail/view/1660701/text-tracks-do-not-fire-change-addtrack-or-removetrack-events

**Comment by heff** [comment]
Can we close this because of #2466?

**Comment by gkatsev** [comment]
Since we filed the bug and disabled native tracks on IE11/Edge, both this and #2438 can be closed.
