### ISSUE TITLE
Control buttons submit form, missing type="button" (5.0.0-rc.49)

### ISSUE THREAD

**Issue by nebrot** [videojs/video.js#2470]
In my web-application i have a player which is integrated in a form with a checkbox to mark uploaded video as deleted. My problem is that all control buttons of the player submit form, because they don't have type="button", default value is "submit" (http://www.w3.org/TR/html-markup/button.html).

Example: http://jsfiddle.net/sLsvLv0q/12/
Windows 8.1: Firefox 40, Chrome 44, IE 11

**Comment by mmcc** [comment]
@nebrot Thanks for the heads up! I opened #2471 to address this.

**Comment by nebrot** [comment]
@mmcc Thanks for your fast (upcoming) fix. Keep up the good work!
