### ISSUE TITLE
5.0: Excluding Child Components

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#2472]
video.js 5.0 will introduce an array-based method of configuring child components for a component. However, this means that any component whose children are configured via an array by default can only have individual children excluded via `Array#filter`:

```js
children: videojs.getComponent('ControlBar').prototype.options_.children.filter(function(c) {
  return c !== 'componentToExclude';
})
```

It seems to me there are a few solutions here.

1. This is fine, leave it as-is.
1. Provide a static method on the component to get at the default options for that component, e.g. `videojs.getComponent('ControlBar').getDefaultOptions()`, which can then be filtered as above.
1. Allow the old-style `children` option as an object to filter things out, e.g. `children: {componentToExclude: false}`.

Thoughts?

**Comment by heff** [comment]
You just need set the child name to false directly on the parent options, not under the children object.

```
playerOptions.controlBar.childName = false
// not
playerOptions.children.controlBar.children.childName = false
```

You can see the add method here. https://github.com/videojs/video.js/blob/master/src/js/component.js#L494
For every child, whether added with an array or object, we check for options for that child on the parent options.

Also this actually isn't new in 5.0. Array children went into 4 at some point.

**Comment by misteroneill** [comment]
Gotcha, thanks.
