### ISSUE TITLE
#2471 breaks in IE9/10

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2480]
The line in PR #2471 that adds `'type': 'button',` to the properties results in an error in `dom.createEl` in IE 9 / 10.

I'm not really sure why this is, but maybe we need to add `type` also to the check in `dom.createEl`?

**Comment by mmcc** [comment]
Well that sucks... Confirmed, this is the case (and seems to be for IE8 as well). I can test out adding this to the check this afternoon unless you want to test it / submit a PR.

**Comment by nickygerritsen** [comment]
Go ahead, I can only test this tomorrow (CEST)

**Comment by Temaruk** [comment]
Any news on this issue?

The error is appearing in IE11 as well. Apparentlz, the `type` attribute is read only in IE if directly accessed, `setAttribute` should be used instead in version >= IE9.

I could provide a PR if a helping hand is needed.

**Comment by mmcc** [comment]
@Temaruk Yep, pretty sure this is broken in IE in entirety. I literally just created a local branch to take care of this, but if you'd like to join the highly esteemed society of Video.js contributors you can take it instead :)

**Comment by mmcc** [comment]
@Temaruk Sorry if you were thinking about taking this one, wanted to get master fixed up sooner rather than later.

**Comment by mmcc** [comment]
Should be fixed via #2487

**Comment by Temaruk** [comment]
@mmcc No problem! It was quite late here when I wrote the message! Great news, thank you for your efforts!
