### ISSUE TITLE
Firefox warning when running 5.0

### ISSUE THREAD

**Issue by hartman** [videojs/video.js#2484]
Firefox reports the following when executing video.js

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

The line for which this is reported is:
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) subClass.__proto__ = superClass; }

**Comment by mmcc** [comment]
From what I've seen anything transpiled via Babel shows this warning in FF. If there's a way to quiet FF I'm all for it, but otherwise I'm fine with just leaving this be.

**Comment by TheDigitalOrchard** [comment]
I'm curious if this is causing my own window.load code to not run correctly. It works in Safari and Chrome properly, but very inconsistently in Firefox. Has there been any progress on addressing this issue?
