### ISSUE TITLE
playbackRates 4x does not work in Internet Explorer

### ISSUE THREAD

**Issue by adgoncal** [videojs/video.js#2485]
When setting playback rate to 4x in Internet Explorer, the video skips frames and displays a slide show instead of a fast video.

http://plnkr.co/edit/9ezxFT?p=preview

**Comment by gkatsev** [comment]
Thanks for the bug report. The playback rate support is implemented by the browser and there is, unfortunately, nothing we can do to make it better. One thing to check is to see if a regular video element (sans videojs) has the same issue with `4x` playback rate. If it doesn't, then videojs might be able to do something, but I have low hopes for that.

**Comment by adgoncal** [comment]
Thanks for the quick reply!

You are right, Internet Explorer does behave the same way without video.js:
http://plnkr.co/edit/e4fvPe?p=preview

The interesting thing is the following statement on the IE features page, which implies support for 4x speed:
> The W3C spec doesn't recommend an upper limit, **but Internet Explorer limits playbackRate up to 8x speed**.
https://msdn.microsoft.com/en-us/library/hh924823(v=vs.85).aspx

**Comment by gkatsev** [comment]
You should file a bug on http://modern.ie.

Going to close this since we can't really do anything about it.
