### ISSUE TITLE
Not able to play youtube Video

### ISSUE THREAD

**Issue by irbaaz** [videojs/video.js#2486]
I am using version 4.12.11 .

I have set a youtube video but it is giving error : 

http://216.172.184.121/~ibruser/aa-vv/demo.html not able to load video .

For my development purpose video.dev.js is very imporrtant.

Please assist me .

In the latest version 5.0.0-rc.51 I did't found video.dev.js so can not try with it.

Pleas help he out and suggest me the solution I have also tried to put the embed youtube video link also.

Thanks 
Help will be appreciable.

**Comment by mmcc** [comment]
Hi there, assuming you're using the [YouTube plugin](https://github.com/eXon/videojs-youtube/), this issue should be opened there.

**Comment by irbaaz** [comment]
No I am not using YouTube plugin.

I am using video.js plugin.

**Comment by mmcc** [comment]
To play YouTube videos via Video.js, you'll need to use the YouTube plugin.

**Comment by irbaaz** [comment]
Ok Thanks I will check and get back to you if need anything.

Thanks for giving your time to solve my query .

Thanks

**Comment by kotelesroberto** [comment]
http://stackoverflow.com/questions/17546633/enabling-youtube-playback-with-video-js-wrapper/17584510#17584510
