### ISSUE TITLE
SWF Default in 5.0

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#2488]
In 4.x, the location of the SWF defaulted to a Zencoder CDN URL. This default does not exist in `master` currently, but it would be good to have a default of some kind.

**Comment by heff** [comment]
So I forgot that I set up the CDN to add in a default swf location on the cdn. See the bottom of http://vjs.zencdn.net/5.0.0-rc.70/video.min.js

So that's half the issue at least. Looking into a sensible default for off of the CDN.
