### ISSUE TITLE
Pre Buferring not working when video is paused

### ISSUE THREAD

**Issue by sufyandeveloper** [videojs/video.js#2489]
i am using video.js great player but when i am playing video only little bit pre buffering is working when i pause video pre buffering also stop working i want when i pause video pre-buffering should work and loading. how could i do this thanks.

**Comment by heff** [comment]
If you're using an MP4, WebM, or Ogg video file (any non-adaptive format), the browser itself handles buffering the video, and we can't control that. With advanced formats like HLS and DASH we have more control over the buffering. Hope that answers your question.

**Comment by sufyandeveloper** [comment]
Sir here is my jsfiddle video is not buffering http://jsfiddle.net/EdjxN/60/ please review it thanks
