### ISSUE TITLE
video.js plugin registration order/dependencies documentation

### ISSUE THREAD

**Issue by gianniblanus** [videojs/video.js#2490]
hi, 
I would like to know if there is any method to specify the dependencies of a plugin on another.

For example I would like to know how to say that the 'second_plugin' depends on 'first_plugin', or if the mechanism is order based

```
videojs(rendered_dom, { 
                                         'children' : {
                                                           .....
                                                           ..... }
                                         'plugin' : {
                                                         'second_plugin : {},
                                                         'first_plugin' :{}
                                                        }
})
```

**Comment by gkatsev** [comment]
Currently, the mechanism is order based. You can also call the plugins manually, either in your own code or calling the second plugin from the first.
