### ISSUE TITLE
method to set alternate video source when flash fallback tech is used?

### ISSUE THREAD

**Issue by obstler42** [videojs/video.js#2493]
Is there some method to set a different video source URL before the video starts playing when the flash fallback tech is used?

I only provide http mp4 videos and use default html5 playback but when an older browser is using fallback to flash playback tech I need to change the video source url; so far looking at all the docs I couldn't find a way to do that. Is there some event that fires before video playback but after the tech has been chosen that allows me to check the used playback tech and then change the url accordingly in javascript?

or maybe even simpler a video source tag/setting/option that is only used for flash tech?

thanks.

**Comment by gkatsev** [comment]
Can you please provide more info about the usecase? Why would you want to swap to a different video based on what tech is loaded?

**Comment by obstler42** [comment]
The use case is to provide flash pseudo streaming/progressive playback seeking over http which needs a http server plugin that is not compatible with standard html5 byte range requests and therefore needs a different virtual host:

http://h264.code-shop.com/trac

I'm also open to other suggestions if there is a different/better solution to provide pseudo streaming to flash via http only.

**Comment by mmcc** [comment]
We don't support pseudo-streaming in the Flash fallback right now, so I think this might be a non-issue.

**Comment by obstler42** [comment]
well, since I can set a different flash player (that supports pseudo streaming), I think this is of interest.

I'm all for moving to native html5 video playback, but still want to provide a nice fallback solution...

**Comment by mmcc** [comment]
Which compatible Flash player would you use that does?

**Comment by obstler42** [comment]
I'm currently using an older version of jwplayer and would either use that for fallback, or flowplayer.

all it needs is simply a start query parameter in the request from the flash player to the server, and the server module seeks to the specified time and returns the appropriate bytes...

**Comment by mmcc** [comment]
We don't support those players as Flash fallbacks, so if you switch over to them it would have to be a total swap. My guess is you could listen for when that alternate player is initialized and then serve a different URL then?

**Comment by obstler42** [comment]
yeah, but which event or method would allow me to listen to that exactly?

**Comment by mmcc** [comment]
It would have to be an event or method on the alternate fallback's side of things since at that point you'd be out of Video.js-land.

To be clear, I don't think this is a great idea. You lose a lot of the benefit of Video.js by swapping out players entirely with the only upside being a marginally better streaming experience for IE8 users (or people that have somehow managed to avoid updating a greenfield browser for years).

**Comment by obstler42** [comment]
yeah, I mostly agree with that -- but an event that fires before flash fallback is initialized could be useful for many other reasons too, like displaying info in the browser, logging statistics so you know how many users fall back to flash etc...

**Comment by heff** [comment]
I think for your case you'd be better off using something similar to how video.js tests for html5 support.

```
if (document.createElement('video').canPlayType) {
  // use video.js
} else {
  // use a different player
}
```
