### ISSUE TITLE
Control bar in specific location

### ISSUE THREAD

**Issue by nppsbh** [videojs/video.js#2495]
Hi.
Is it possible to put control bar inside a specific element, not inside the default wrapper?
(4.12.11)
Thank you for your help.

**Comment by heff** [comment]
No, not easily. A lot of the control bar styling assumes it's inside the player div. You could try...
```
// after the player is initialized
someOtherElement.appendChild(myPlayer.controlBar.el())
```

That will take the control bar out of the player and put it into someOtherElement. But from there you would need to figure out what styles are missing for it to work correctly. 

You could also build some of your own controls externally using the player API.

**Comment by nppsbh** [comment]
Thank you for your quick answer.
As I just need the play/pause and mute/unmute buttons I decided to build them externally using player API as you suggested.

the script:

    (function($){
        videojs('bg-video').ready(function(){
            var myPlayer = this;

            $("#bg-play").bind("click", function(){
                play();
            });

            $("#bg-sound").bind("click", function(){
                sound();
            });

            function play() {
                var isPaused = myPlayer.paused();

                if (isPaused) {
                    myPlayer.play();
                    $("#bg-play").attr('class', 'icon-pause');
                } else {
                    myPlayer.pause();
                    $("#bg-play").attr('class', 'icon-play');
                }
            };

            function sound() {
                var isVolumeMuted = myPlayer.muted();

                if (isVolumeMuted) {
                    myPlayer.muted(false);
                    $("#bg-sound").attr('class', 'icon-volume-unmute');
                } else {
                    myPlayer.muted(true);
                    $("#bg-sound").attr('class', 'icon-volume-mute');
                }
            };

            videojs('bg-video').on('ended', function() {
                $("#bg-play").attr('class', 'icon-play');
            });

        });
    })(jQuery);

place the buttons with class based on play options ( if is autoplay and if starts muted/unmuted ):

    ...
    if ($video_autoplay) {
	$playClass = 'icon-pause';
    } else {
        $playClass = 'icon-play';
    }
    ...
    if ($video_mute) {
	$soundClass = 'icon-volume-mute';
    } else {
        $soundClass = 'icon-volume-unmute';
    }
					
    $new = '<div class="new-control-bar">
	         <span id="bg-play" class="' . $playClass . '"></span>
	        <span id="bg-sound" class="' . $soundClass . '"></span> 
	        </div>';

This is working very well except when i set it to loop video. In that case, when the video reaches the end the play button change from pause to play (this should be the normal behavior if the video is not looping), but is should keep in the pause because the video will start again.
Can you please help me?
I am using with video.js this plugins: videojs-background, videojs-youtube and videojs-vimeo.
Thanks.

**Comment by mmcc** [comment]
Even when you're looping, the `ended` event is still going to fire. Looks like you have an event listener for `ended` but none of the others, so I would suggest moving the rest of your icon logic over to event listeners as well to avoid situations like this.

```
myPlayer.on('ended', function() {
   $("#bg-play").attr('class', 'icon-play');
});
```

**Comment by nppsbh** [comment]
Thank you for your answer.
From what I realized from your answer I have to keep the function binding to my icons when pressed and remove from play() function only the classes attributes and put them like 

    myPlayer.on('ended', function(){
        $("#bg-play").attr('class', 'icon-play');
        myPlayer.currentTime(1);
    });

    myPlayer.on('play', function(){
        $("#bg-play").attr('class', 'icon-pause');
    });

    myPlayer.on('pause', function(){
        $("#bg-play").attr('class', 'icon-play');
    });

My doubts are:
About sound() function, i did not found event listeners to use with sound. Should i keep it as it is?
I HTML i should keep initial icons classes, right?

Thanks.
