### ISSUE TITLE
Firefox bug (maybe) with autoplay and preload

### ISSUE THREAD

**Issue by Sattar1** [videojs/video.js#2506]
Hi guys. thanks for the great plugin.
Something is wrong with Firefox or the plugin for me, can you help me?
Using `autoplay: false; preload:"none"` , when I play the video, Firefox tries to download all of the video, then plays it. if I use `autoplay: true` there is no problem. Chrome and Opera have no problems too.
And, I think firefox doesn't pay attention to "preload"! again using `autoplay: false; preload: "none"`, he tries to download many parts of the video (tested with Firefox > Developer > Network). What's wrong with me?
One more thing, As mentioned in #2191 , when are you going to release version 5?

Thanks.

**Comment by heff** [comment]
Can you tell if the it's using Flash or HTML to play back the video? (try right-clicking on the video to see)

We're working through the last issues in the 5.0 milestone so it's looking close now. If you'd like to help, we need people to start going through the [plugins in the wiki](https://github.com/videojs/video.js/wiki/Plugins) and testing/updating them for 5.0.

**Comment by Sattar1** [comment]
Well, I am using HTML5 tech, Firefox 40.
I give you more information about the problem from Firefox > Developers > Network.
When I open the page, it sends too many requests to the server. there are just 2 request headers which repeat after each other.
I have attached 2 photos to show you the content of headers. As I said, they repeat after each other.
please pay attention to the ranges that I have specified with arrows. **same headers have same ranges**
I mention again, Chrome and Opera are OK. the problem exists just in Firefox.
![contents of header 1](http://i.imgur.com/nTgFNeg.png)
![contents of header 2](http://i.imgur.com/0uf5zIX.png)

Thanks for the patience.

**Comment by heff** [comment]
This might just be Firefox's native operation. Can you try this same thing with a bare video element and see if it still happens?

```
<video src="YOUR_VIDEO" controls preload="none"></video>
```

**Comment by Sattar1** [comment]
WIthout videojs, just with Firefox's native operation:
With `preload:auto` or `preload:metadata` or `autoplay` he sends the too many repetitious requests to the server and doesn't play the video until downloads it completely.
With `preload:"none"`, it doesn't send too many requests on page load to server, but sends them after playing the video.
Firefox mustn't have such an obvious bug, why doesn't it send one request to server like Chrome and Opera and sends too many **repetitious** requests? it eats server resources like I/O. It's not acceptable. or there might be something wrong with me and my test. Any idea or help @heff ?

Thanks.

**Comment by heff** [comment]
It's really hard to say for sure without seeing it. Any chance you could set up a [jsbin](http://jsbin.com/) with this example? That would make it easier for me to see.

**Comment by mmcc** [comment]
It sounds like this is Firefox behavior, which means any issue would need to be opened against the [Firefox issue tracker](https://bugzilla.mozilla.org/). We can keep trying to help in the comments, but when using a standard video element like this we have no control over the actual content requests.
