### ISSUE TITLE
Do a pass on improving css selector strength and order

### ISSUE THREAD

**Issue by heff** [videojs/video.js#2509]
Before we officially release 5.0 with the new skin I think we should look over the strengths and order of CSS selectors. The CSS states are resulting in more and more complexity, which will just extend to skin designers, and I think we can create a better environment.

See: https://github.com/videojs/video.js/pull/2499/files#r37668964

**Comment by mmcc** [comment]
I think Gary might have been [right all along](http://glenmaddern.com/articles/css-modules)

**Comment by heff** [comment]
We chatted about this a bit on the side. CSS modules don't solve this specific issue for us because they don't do anything to about internal selector specificity. It might help with external conflicts, but we're already prefixing all our selectors with `vjs`. They could still be an interesting direction for other reasons.

**Comment by gkatsev** [comment]
Yes, this needs to happen.

**Comment by heff** [comment]
I did as much as I could for 5.0 in #2583. Any one can feel free to take another pass.
