### ISSUE TITLE
Akamai video with token won't load

### ISSUE THREAD

**Issue by EKabar** [videojs/video.js#2514]
Akamai video with token won't load 

http://penguinvideo.herokuapp.com/hls_test

Does someone can help me?

**Comment by mister-ben** [comment]
With Akamai's token auth only the master playlist is tokenised, cookies are used to control access to the variant playlists and ts segments. You need to use [withCredentials](https://github.com/videojs/videojs-contrib-hls#withcredentials) for cookies to be set/sent. `data-setup='{ "hls": { "withCredentials": true } }'`

**Comment by heff** [comment]
Thanks @mister-ben! Closing since it doesn't require change to video.js but feel fee to continue the discussion if needed.
