### ISSUE TITLE
how can i use video.js to play rtmp

### ISSUE THREAD

**Issue by delonglimin** [videojs/video.js#2518]
I do not know how to whrite code ,i want to use this to live

**Comment by mister-ben** [comment]
You need to use `rtmp/mp4` as the mime type and add an `&` to the URL to separate the server URL and stream name. Obviously this only works with the Flash tech.

    <source src="rtmp://your.streaming.provider.net/cfx/st/&mp4:path/to/video.mp4" type="rtmp/mp4">
