### ISSUE TITLE
Link to Microsoft's HTML5 caption maker is broken.

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [videojs/video.js#2520]
Inside the documentation in the Tracks chapter, it describes a link to Microsoft that has a convenient HTML 5 Caption maker.  This link no longer works, and can't find another one like it.

**Comment by mmcc** [comment]
Went ahead and removed the dead link in the master branch

**Comment by mmcc** [comment]
Thanks for the heads up!

**Comment by CoWinkKeyDinkInc** [comment]
Your welcome, I hope we could find something like that as that tool was great.

**Comment by forbesjo** [comment]
Looks like they're aware of it https://github.com/MicrosoftEdge/Demos/issues/92
