### ISSUE TITLE
VJS5: Allow the tech to set a default poster

### ISSUE THREAD

**Issue by eXon** [videojs/video.js#2525]
I have an issue that really need to be fixed because vjs-youtube is unusable. I though I made an issue about this before but I really can't find it (sorry).

I need a way in my tech to set the poster on the VJS player if there is none. This is because vjs-youtube needs to set a poster on top of YouTube iframe to hide the big ugly red play button. VJS already got one so this is really important (or it looks crappy).

The only way to communicate with the player now is with an event. Would it be a reasonable to set a default poster with an event or what would be the better way?

**Comment by moay** [comment]
+1

I currently set the poster when the plugin is done. But doing this outside the plugin seems a bit awkward, should be coming from inside vjs-youtube.

**Comment by dmlap** [comment]
What about if the player checked the poster attribute of the tech on load and at `posterchange` events from that point on? [posterchange is already hooked up](https://github.com/videojs/video.js/blob/master/src/js/poster-image.js#L24)

**Comment by gkatsev** [comment]
That sounds good to me. We changed how native controls are done and this would be similar to that.

**Comment by eXon** [comment]
@dmlap That would solve my problem if a `poster()` method on my tech could give the default poster value.

**Comment by heff** [comment]
The previous PR around this was #2339. It's worth a read through for background on the situation. It's also still open so we might consider combining.

I suggested something similar to @dmlap in [my last comment](https://github.com/videojs/video.js/pull/2339#issuecomment-121760195), so sounds good to me.

**Comment by eXon** [comment]
@heff it's the original discussion I was looking for! I will update the same PR.

**Comment by gkatsev** [comment]
I believe this is done.
