### ISSUE TITLE
when i execute grunt   I Encounter this problem  how should i do thanks  for your help 

### ISSUE THREAD

**Issue by delonglimin** [videojs/video.js#2526]
![qq 20150831132559](https://cloud.githubusercontent.com/assets/8324872/9572581/f3335c26-4fe3-11e5-9d85-ff5373af6045.png)

**Comment by mmcc** [comment]
Unfortunately I can't read that error and would have trouble debugging anyway since I don't develop on a Windows machine, but [this StackOverflow seems relevant](http://stackoverflow.com/questions/11059211/error-code-800a1391-source-microsoft-jscript-runtime-error-running-grunt-mod).
