### ISSUE TITLE
Are there functional tests for mobile platforms?

### ISSUE THREAD

**Issue by jimkang** [videojs/video.js#2529]
Hey, apologies if I missed it, but I just reading contributing.md, cloned and ran the tests. I noticed the config in the Gruntfile seems to indicate these are the covered platforms:

```
      // these are run locally on local browsers
      dev: { browsers: ['Chrome', 'Firefox', 'Safari'] },
      chromecanary: { browsers: ['ChromeCanary'] },
      chrome:       { browsers: ['Chrome'] },
      firefox:      { browsers: ['Firefox'] },
      safari:       { browsers: ['Safari'] },
      ie:           { browsers: ['IE'] },
      phantomjs:    { browsers: ['PhantomJS'] },

      // this only runs on PRs from the mainrepo on BrowserStack
      browserstack: { browsers: ['chrome_bs'] },
      chrome_bs:    { browsers: ['chrome_bs'] },
      firefox_bs:   { browsers: ['firefox_bs'] },
      safari_bs:    { browsers: ['safari_bs'] },
      ie11_bs:      { browsers: ['ie11_bs'] },
      ie10_bs:      { browsers: ['ie10_bs'] },
      ie9_bs:       { browsers: ['ie9_bs'] },
      ie8_bs:       { browsers: ['ie8_bs'] }
```

Now that you have BrowserStack, are there plans to cover Mobile Safari and the Android browsers? Or have you already somewhere else?

**Comment by heff** [comment]
Mobile platforms are still being tested manually because we've found them to be too inconsistent on Sauce/Browserstack. @forbesjo anything to add here?

**Comment by jimkang** [comment]
Ah, understood. Is there a list of either officially supported mobile browsers or a list of mobile browsers on which video.js is generally known to work?

**Comment by gkatsev** [comment]
Latest iOS and latest Chrome for Android should generally work. The Native Android Browser is having issues. In the master branch (5.0) we disabled our custom controls and it works mostly fine there too now.

**Comment by forbesjo** [comment]
I'll test out iOS and Android on BrowserStack and open a PR if it looks good. I think the tests were flaky on Sauce Labs which is why they were removed?

**Comment by moay** [comment]
Firefox on android seems to have major problems with VJS5. It works with vjs-youtube (more or less), but with local files it is not working for me. Maybe my fault, but there is one warning in the console:

    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by jimkang** [comment]
@gkatsev Thanks. We'll look out for issues on Android Chrome and Mobile Safari, but assume they're likely to be OK. Anyone have any experiences with the Android 4.0 default browser?

**Comment by gkatsev** [comment]
I don't think we're going to change our matrix right now but I put a task for myself to try it out again.
