### ISSUE TITLE
How to implement playsinline with in latest Videojs

### ISSUE THREAD

**Issue by rapsody** [videojs/video.js#2530]
From other posts I see playsinline has been added as functionality however I cannot get it to play inline on safari on my iPhone 6. I am using the latest release v4.12.13?

I have added playsinline: true, to my videoJs setup and its not detecting it.

**Comment by gkatsev** [comment]
I believe you need to add it as an attribute on the video element
```html
<video webkit-playsinline>
  <source src="somevideo.m3u8" type="application/vnd.apple.mpegurl">
</video>
```

**Comment by rapsody** [comment]
thanks for the reply I have tried that with no success, so currently I have

video#webcast-video1.video-js.vjs-default-skin.vjs-big-play-centered(videojs='', webkit-playsinline,  poster='/images/background.gif') 

and I am using an angular directive to initiate the videoJs

                  attrs.id = attrs.id || "videojs" + Math.floor(Math.random() * 100);
                  attrs.setup = attrs.setup || {};
                  var setup = {
                      'techOrder': ['html5', 'flash'],
                      'controls': false,
                      'preload': 'auto',
                      'autoplay': true,
                      'width': '100%',
                      'height': 'auto'
                  };
                 
                 player = videojs(attrs.id, setup, function() {.....

**Comment by rapsody** [comment]
Also to note I have MP4 files, not m3u8

**Comment by gkatsev** [comment]
Yes, m3u8 was just an example. It doesn't matter what media.

I'm not sure what your first line means but videojs should preserve any attributes on the element.

**Comment by rapsody** [comment]
The first line is just for Jade  a HTML template engine, I have tried on JSfiddle just a simple example and I'm testing on BrowserStack and  it doesn't play inline either  https://jsfiddle.net/s9v8kqe9/1/

**Comment by gkatsev** [comment]
`webkit-playsinline` also only works with webviews. (It might work with websites pinned to the home screen but I'm not certain). It won't work with just a regular page in safari.

**Comment by mmcc** [comment]
It will work with sites added to home as well, but no, it will not just work with a regular page in Safari.

**Comment by rapsody** [comment]
ok thanks
