### ISSUE TITLE
Youtube video fills the window after coming back from fullscreen.

### ISSUE THREAD

**Issue by kotelesroberto** [videojs/video.js#2535]
I've got a problem in Chrome  v44.0.2403.157m when I play Youtube videos. After starting the videos form the control bar of video.js (or with the big play button at start) and switching the video to fullscreen everything is great. But after switch back from fullscreen the layout is changed (no more fullscreen) but video fills the full window. This issue is not always happen but couple of times is possible to reproduce easily.

I think the problem is the syncronisation of switching to fullscreen and back between video.js controllers and youtube fullscreen methods. Which one could be first at switchin back from fullscreen?

My code is:
&lt;video id="video-youtube-src" src="" class="video-js vjs-default-skin" controls preload="none" width="590" height="332" data-setup='{ "techOrder": ["youtube", "html5", "flash"], "src": "//www.youtube.com/watch?v=_PVjcIO4MT4" }'>
&lt;/video>

![youtubevideo-fullscreen2](https://cloud.githubusercontent.com/assets/10416901/9628099/9abe5e00-5160-11e5-99de-100315e7adf7.jpg)

![Uploading youtubevideo-fullscreen2.jpg…]()

**Comment by gkatsev** [comment]
Does this happen with non-youtube videos? If it only happens with youtube videos, can you re-open the issue against the youtube tech's issue tracker?
