### ISSUE TITLE
Undefined track with `4.12.14`

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#2537]
When using, `video.js`, track is undefined and an exception is thrown.

```js
vjs.TextTrackList.prototype.addTrack_ = function(track) {
  var index = this.tracks_.length;
  if (!(''+index in this)) {
    Object.defineProperty(this, index, {
      get: function() {
        return this.tracks_[index];
      }
    });
  }

  track.addEventListener('modechange', vjs.bind(this, function() {
    this.trigger('change');
  }));
  this.tracks_.push(track);

  this.trigger({
    type: 'addtrack',
    track: track
  });
};
```

![](https://cloud.githubusercontent.com/assets/549319/9557165/9347dad2-4d8e-11e5-9099-7ed4ca8d1a0f.png)

https://github.com/videojs/video.js/blob/stable/src/js/tracks/text-track-list.js#L78

---

When using, `video.dev.js`, the track is properly defined.

![screen shot 2015-09-01 at 1 40 16 pm](https://cloud.githubusercontent.com/assets/549319/9615748/0a92921c-50af-11e5-8512-ad4e95b827dc.png)

Reference: https://github.com/videojs/video.js/issues/2436

**Comment by gkatsev** [comment]
I'm not exactly sure where the exception is. Do you have a live example I can take a look at?

**Comment by chemoish** [comment]
Sorry. The exception will be thrown on line `3820` (In the image above).

> Uncaught TypeError: Cannot read property 'addEventListener' of undefined

```bash
git clone https://github.com/chemoish/videojs-chapter-thumbnails.git

npm install

grunt
```

Update `example/index.html` to point to `video.js` instead of `video.dev.js`.

---

Let me make a bin as well.

**Comment by chemoish** [comment]
Closing as this doesn't seem to be an issue with 5.0.0
