### ISSUE TITLE
In IE8 I get a "no compatible source was found"

### ISSUE THREAD

**Issue by dcp3450** [videojs/video.js#2539]
What video file type do I need to get the video to work with the SWF fall back?

**Comment by mmcc** [comment]
An mp4 would be best, but an flv would also work.

**Comment by dcp3450** [comment]
I'm providing an mp4, webm, and an ogv file. I can't find anything in the docs that explain how to setup to allow for the flash fallback.

**Comment by mmcc** [comment]
If you're using the CDN version of the player, the Flash fallback should Just Work™. If it doesn't, my guess is your mp4 file is borked. If you're self-hosting, you might need to configure the [swf location](https://github.com/videojs/video.js/blob/master/docs/guides/setup.md#self-hosted).

What version of the player are you using?

**Comment by dcp3450** [comment]
I've tried both local (relative and absolute path) and via the CDN. My mp4 plays fine on supported browsers. I'm using the big buck bunny test videos: http://camendesign.com/code/video_for_everybody/test.html

**Comment by mmcc** [comment]
Do you have Flash installed in your IE8 installation? I just confirmed, [this example](http://output.jsbin.com/axedog/latest) works in IE8 with the Flash fallback.
