### ISSUE TITLE
Component's createEl is selectively adding attributes.

### ISSUE THREAD

**Issue by rubylibre** [videojs/video.js#2541]
Component's createEl is selectively adding attributes.
So this:
```javascript
    this.el_ = videojs.Component.prototype.createEl('iframe', {
      id: this.id_,
      className: 'vjs-tech',
      scrolling: 'no',
      marginWidth: 0,
      marginHeight: 0,
      frameBorder: 0,
      webkitAllowFullScreen: 'true',
      mozallowfullscreen: 'true',
      allowFullScreen: 'true'
    });
```
Is not creating te last three attributes on the iframe.
Following the code it comes down that in utils/dom.js createEl is using:
```javascript
el[propName] = val;
```
instead of:
```javascript
el.setAttribute(propName, val);
```

**Comment by heff** [comment]
We have a similar discussion around this happening in #2176, if you want to join in there and even help us get a fix created.
