### ISSUE TITLE
<track ... default> doesn't work

### ISSUE THREAD

**Issue by edegaudenzi** [videojs/video.js#2542]
Default flag doesn't seem to work in 4.12.13.

One source, two tracks:
```html
<video ...[stuff]... controls preload="auto">
  <source src="video.mp4" type='video/mp4'>
  <track label="English" kind="subtitles" srclang="en" src="sub-en.vtt" default>
  <track label="Italian" kind="subtitles" srclang="it" src="sub-it.vtt">
  fallback text
</video>
```

Chrome: it doesn't work, it starts on 'IT'
FF: subtitles don't start automatically
Safari: it properly works
Opera: it doesn't work, it starts on 'IT'

**Comment by gkatsev** [comment]
Can you please try 4.12.14? It should hopefully be fixed there.

**Comment by Globulopolis** [comment]
`default` not working in 4.12.15 too.

**Comment by jemoreno** [comment]
Also not working in 5.0

**Comment by bschi** [comment]
The bug I can also confirm. It would be great if this could be corrected promptly.

**Comment by gkatsev** [comment]
Closing this as a duplicate of #1914.
