### ISSUE TITLE
Problem with videojs.dev.js.

### ISSUE THREAD

**Issue by gangstaJS** [videojs/video.js#2545]
I download player on archive from videojs.com. Archive contain files video.js, video.dev.js etc.

When connect minifed video.js file player work ok, if connect videojs.dev.js  http://take.ms/falWM

**Comment by mmcc** [comment]
I just built the dev version of 4.12.15 and I'm not seeing this. Mind putting up an example? What version are you using?

![screenshot](https://cloudup.com/czEgTjUmfxY+)

**Comment by gangstaJS** [comment]
@mmcc video-js-4.12.11. Perhaps after the project build file videojs.dev.js spoils?

**Comment by mmcc** [comment]
I just downloaded and 4.12.11 and 4.12.15 from the releases and switched the `demo.html` file to use the dev version before checking in the browser. I'm not seeing this, and looking closer at your HTML it looks like you've initialized a player within a player (or something along those lines). Closing the issue, but how are you initializing the player?

**Comment by gangstaJS** [comment]
@mmcc Here my repo with init this player https://github.com/gangstaJS/foxplayer/blob/ads_foxplayer/js/init.js .
this is with video.js http://37.139.22.225/demo.html
this is with video.dev.js http://37.139.22.225/demo2.html

I solved the problem in a way, download a stable version of the repository videojs, corrected the source code to fit your needs and rebuilt.

**Comment by mmcc** [comment]
The player looks great! There's a bit too much going on in your initialization for me to dig in ([initPlayer](https://github.com/gangstaJS/foxplayer/blob/ads_foxplayer/js/init.js#L32) looks like it's defined outside of the linked init file), but here's a [live, functioning example](http://output.jsbin.com/moriduzequ) using the dev version from the dist folder of the 4.12.11 tag.
