### ISSUE TITLE
'webkitMovementX' is deprecated in Google Chrome

### ISSUE THREAD

**Issue by marina9568** [videojs/video.js#2548]
Good day.

After Google Chrome upgrade I get this notices in console:
'webkitMovementX' is deprecated. Please use 'movementX' instead. (video.dev.js:503)
 'webkitMovementY' is deprecated. Please use 'movementY' instead.  (video.dev.js:503)
In Firefox no such problem.

Thank you,
Marina.

**Comment by moay** [comment]
Got that, too. Doesn't change a thing for now...

**Comment by heff** [comment]
We don't actually use it, it just gets copied as part of our event process because the key still exists. We need to add it to the other deprecated keys, if anyone wants to make a PR for it.
https://github.com/videojs/video.js/blob/master/src/js/utils/events.js#L239

**Comment by forbesjo** [comment]
I'll open PRs for master and stable.

**Comment by heff** [comment]
Fixed in master and stable
