### ISSUE TITLE
VJS5: play() doesn't trigger on mobile devices.

### ISSUE THREAD

**Issue by moay** [videojs/video.js#2549]
Strange thing. I try this:

```javascript
videojs('myid',function(){
    alert('test');
    this.play();
});
```

This works on desktop (tested with several browsers), but it doesn't work on mobile phones. Both Chrome Android and Safari iOS don't like it. The `alert()` gets fired, but the `this.play()` doesn't happen.

Any idea why? Working with rc72.
Thanks!

**Comment by gkatsev** [comment]
You can't play a video on mobile devices without user interaction, this means that any kind of autoplay is out of the question.

**Comment by moay** [comment]
Aah, okay. Didn't know that, thats sad... Okay, thanks!

**Comment by moay** [comment]
Any way to check out via videojs if autoplay is possible?

**Comment by gkatsev** [comment]
Not certain that there's a test for it beyond trying to play and checking whether the `play` event was triggered or something. You can probably assume that you can't autoplay on mobile devices.

**Comment by sergibondarenko** [comment]
On Android, you can autoplay if you put `muted` option

    <video autoplay muted>
      <source src="video.webm" type="video/webm" />
      <source src="video.mp4" type="video/mp4" />
    </video>

https://developers.google.com/web/updates/2016/07/autoplay
