### ISSUE TITLE
`vjs-user-active` or `vjs-user-inactive` aren't added by default

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2550]
Only until the first triggered event happens does one of these get added.
`vjs-user-active` should probably be added by default on first play since at that time the user is definitely active.

**Comment by heff** [comment]
What's the result of not having it? Could we just add it on init?

**Comment by gkatsev** [comment]
Yep, basically, things that depend on those don't work quite right immediately after pressing play.
Not certain whether just adding user active on init is a good idea but a lot of css selectors also check for vjs-has-started, so, maybe not a huge issue in that respect.

**Comment by heff** [comment]
Yeah, I feel like we can consider the user active when the player is initialized. It at least seems better to have a default state from init instead of waiting until some point later. We could start there and see if it does what we need.

**Comment by gkatsev** [comment]
Looks like we already try doing something like this: https://github.com/videojs/video.js/blob/master/src/js/player.js#L202
Looking into switching it out with `this.userActive(true)` instead.
