### ISSUE TITLE
How to setup rtmp with html5 in videojs

### ISSUE THREAD

**Issue by nguyentungson** [videojs/video.js#2560]
Please help me!

Here I have the following code:

     <link href="https://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
     <script src="https://vjs.zencdn.net/4.12/video.js"></script>

video id="MY_VIDEO_1" preload="auto" width="640" height="264"
      source src="rtmp://xxxxx.cloudfront.net/cfx/st/mp4:1/xxxxx.mp4" type="rtmp/mp4"
/video

But I get the message: "No comtipable srouce was found for this video".

I have done nothing wrong!

**Comment by mister-ben** [comment]
Use an ampersand to separate the connection URL and stream name

    <source src="rtmp://xxxxx.cloudfront.net/cfx/st/&mp4:1/xxxxx.mp4" type="rtmp/mp4">
