### ISSUE TITLE
Better Mobile Support!

### ISSUE THREAD

**Issue by CosmicWebServices** [videojs/video.js#2561]
I can't seem to get my video working well on mobile here is the video: http://ilovecode1.github.io/video.js-del-plugin/

**Comment by mmcc** [comment]
It's working fine for me on iOS. What issues are you seeing and on what devices?



—

**Comment by CosmicWebServices** [comment]
Hmm I tested it on Ipad (latest) and fire os (Older) but, I just updated the plugin maybe that fixed it but, thanks.

**Comment by CosmicWebServices** [comment]
Oh yeah it did not play automatically like it should

**Comment by mmcc** [comment]
Ah got it, but unfortunately that's a limitation on mobile devices. Play
has to be triggered by a user action of some kind.

**Comment by CosmicWebServices** [comment]
Oh ok what devices is that limited too?

**Comment by mmcc** [comment]
You can reasonably assume pretty much any mobile device.

**Comment by CosmicWebServices** [comment]
ok thanks
