### ISSUE TITLE
VideoJS working correct on Chrome but not in Vivaldi

### ISSUE THREAD

**Issue by Sebi55** [videojs/video.js#2562]
I have noticeda strange behaviour. I cannot say if this only happens in Vivaldi or any other browser but Chrome, Internet Explorer and Firefox work correctly.
When I hit play on chrome it perfectly plays the video but if I do it on Vivaldi nothing happens. I do not have any errors in the console. I tried to run play from the console on chrome it of course works but in Vivaldi it mysteriously returns me the player object instead of playing the video.
Here my output on chrome:
![chrome](https://cloud.githubusercontent.com/assets/923505/9704445/16504e5e-54a7-11e5-80e1-b13815bf5ec9.png)
Here my output on vivaldi:
![vivaldi](https://cloud.githubusercontent.com/assets/923505/9704437/e2db080c-54a6-11e5-9cdb-d537673eea03.png)

I see that L is null but I init the player the same on both browser and I cannot figure out why this happens only on vivaldi.

**Comment by gkatsev** [comment]
Can you try grabbing the unminified code and using that? It would be interesting to know whether it only fails in vivaldi with the minified code or in general.

**Comment by Sebi55** [comment]
I noticed that it works when I go to the videojs.com with vivaldi. This video plays without any problems and they also use the minified version so that should not be the problem right?
I tried it with the unminified version but did not fix it.

**Comment by mister-ben** [comment]
What format(s) are you using? Vivaldi doesn't play MP4/h264 (on Mac at least) so you'd need Flash installed if that's the only source. The webm source is used on videojs.com.

**Comment by Sebi55** [comment]
Oh you are right vivaldi does not support MP4. I thought it would. It seems to be the problem.
