### ISSUE TITLE
How play video from given start time and end with given end time.

### ISSUE THREAD

**Issue by shivamg705** [videojs/video.js#2576]
I have a video url (http://video-js.zencoder.com/oceans-clip.mp4#t=14,20) in which start time and end time for playback. and when i play this url in videojs player then seekbar already seeked upto 14 sec and play onward.I want that player should understand 14 as initail point and end with 20 sec.it should seem like video is only 6 sec duration video.

Please tell me how can i do it.

**Comment by cladera** [comment]
I created a plugin to solve that use case. Check it out here: [videojs-offset](https://github.com/cladera/videojs-offset)

**Comment by mmcc** [comment]
@cladera Nice! Saw this one on the plugins list but hadn't actually checked it out.

**Comment by shivamg705** [comment]
@cladera Thanks!

**Comment by cshah123** [comment]
@cladera It fails in case of greater start time

**Comment by kamrapooja** [comment]
In video.js only cropped image gets displayed instead of complete video. Is there any provision, where complete image gets displayed but start with given time offset?
