### ISSUE TITLE
Can't get the Play Button Centered on videojs 5_rc2

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#2577]
We can't get the Play Button Centered on videojs 5 Release Candidate 2, anyone else with this problem. Is it a bug, or has the class been dropped or been renamed? We have tried:
vjs-big-play-centered

BUT NO SUCCESS...

**Comment by nebrot** [comment]
You need at least v5.0.0-rc.4 for "vjs-big-play-centered", see #2293 . RC1-3 don't have it.

**Comment by richardbushell** [comment]
OK, we got the version RC2 from the videojs.com latest blog:-
http://blog.videojs.com/
I should have checked for a later GitHub version first!

**Comment by richardbushell** [comment]
OK, so how do I find out the latest release number available on CDN?
Just tried 5.0.0-rc.80 in the CDN path but it's not available even though that's the last version I can see in GitHub. Where does it show the last CDN version? Please advise.

**Comment by nebrot** [comment]
The new release candidates aren't on CDN, i don't know why. But you can host yourself the newest versions until they release final v5.0:
Download: https://github.com/videojs/video.js/releases
Guide: https://github.com/videojs/video.js/blob/master/docs/guides/setup.md#self-hosted

**Comment by richardbushell** [comment]
Ah yes, thought so, the last CDN version is currently 5.0.0-rc.2 which is why I tested with this. I'll self-host for testing until the FINAL release, unless the team start updating the CDN version as they go...

**Comment by gkatsev** [comment]
v5 is now published and available on the CDN. Please try it out.
