### ISSUE TITLE
Adding button with plugin not working in lastest version

### ISSUE THREAD

**Issue by Albermg7** [videojs/video.js#2578]
Hello,
I am trying to implement a plugin for videoJs jsut to add a button to the control bar. I have followed seen how to do it in some tutorials but it is not working in the last version (4.12). I have downloaded an oldest version ([this dev version](http://brianpkelley.github.io/video-js-4-plugins/javascripts/video.dev.js)) directly from a  [demo page](http://tastybytes.net/creating-a-video-js-plugin/) and maggicallyl it is working. The code is this:

```javascript
    // Create the button
    videojs.InfoButton = videojs.Button.extend({
        init: function (player, options) {
            // Initialize the button using the default constructor
            videojs.Button.call(this, player, options);
            this.on('click', this.onClick);
        }
    });

    videojs.InfoButton.prototype.createEl = function () {
        var props = {
            className: 'vjs-info-button vjs-control',
            innerHTML: '<div class="vjs-info-button vjs-control-content"><span class="vjs-control-text">' + ('InfoButton') + '</span></div>',
            role: 'button',
            'aria-live': 'polite', // let the screen reader user know that the text of the button may change
            tabIndex: 0
        };

        return videojs.Button.prototype.createEl(null, props);
    };

    videojs.InfoButton.prototype.onClick = function () {
        alert("INFO!");
    };

    // Video.js Plugin Code 
    videojs.plugin('infoButton', function (options) {
        options = options || {};
        this.controlBar.addChild('InfoButton', options);
    });
```

With the latest version, the videojs.InfoButton.prototype.createEl function is actually not being called. So, is there a new way to do this? What have changed in new versions that is preventing my code from working properly?
Thansk a lot

**Comment by forbesjo** [comment]
Are you using the minified version of video.js? It looks like createEl is not available when minified so it is recommended to use the unminified version of video.js.

See https://github.com/videojs/video.js/issues/2016

**Comment by Albermg7** [comment]
Thanks forbesjo! That seems to be the problem. Since I have tried the minified version of the video.js used in the demo page I said and the plugin is not working either.

Can the unminified version be downloaded from the CDN?

**Comment by gkatsev** [comment]
Unfortunately, the unminified version of v4 isn't available on the CDN.
However, v5 is out and updating would be the recommended approach. It is available on the CDN in both [minified](http://vjs.zencdn.net/5.2/video.js) and [unminified](http://vjs.zencdn.net/5.2/video.js) flavors. See the [change details](https://github.com/videojs/video.js/wiki/5.0-Change-Details) page on the wiki for how to update.
