### ISSUE TITLE
Failing source with wrong headers

### ISSUE THREAD

**Issue by carpasse** [videojs/video.js#2580]
Hi guys I have encountered a problem trying to play a mp4 ad video source that has a "delivery:streaming" I am not very sure on what changes in the way the srcs are delivered

```
<MediaFile delivery="streaming" type="video/mp4" bitrate="400" width="320" height="180" scalable="true" maintainAspectRatio="true">
<![CDATA[http://e736daa9861a3da5faf4-49d13c85de3b1b0658221edbffbf1629.r69.stream.cf2.rackcdn.com/bigbuckbunny.mp4
]]>
</MediaFile>
<MediaFile delivery="progressive" type="video/mp4" bitrate="700" width="320" height="180" scalable="true" maintainAspectRatio="true">
<![CDATA[
http://8ea7863d68099f00b39c-49d13c85de3b1b0658221edbffbf1629.r69.cf2.rackcdn.com/bigbuckbunny.mp4
]]>
</MediaFile>
```

In a nutshell this source does not play in videojs
```
http://e736daa9861a3da5faf4-49d13c85de3b1b0658221edbffbf1629.r69.stream.cf2.rackcdn.com/bigbuckbunny.mp4
```
While this one does
```
http://8ea7863d68099f00b39c-49d13c85de3b1b0658221edbffbf1629.r69.cf2.rackcdn.com/bigbuckbunny.mp4
```

They are supposed to be the same video and if you download them, you do get the same bigbuckbunny video. 

I do see some discrepancies on the response headers

The non working src returns a wrong content-type and a wrong length
```
Cache-Control:max-age=0, no-cache
Connection:keep-alive
Content-Length:2147483647
Content-Type:video/x-flv
Date:Fri, 11 Sep 2015 09:30:49 GMT
Expires:Fri, 11 Sep 2015 09:30:49 GMT
Mime-Version:1.0
Pragma:no-cache
Server:AkamaiGHost
```

While the working one has the right type and length plus some other headers like Accept-Ranges and so on
```
Accept-Ranges:bytes
Access-Control-Allow-Origin:*
Cache-Control:public, max-age=259167
Content-Length:1339243
Content-Range:bytes 0-1339242/1339243
Content-Type:video/mp4
Date:Fri, 11 Sep 2015 08:39:49 GMT
ETag:76539d72062ad1a7dd1f5dd3fc12e245
Expires:Mon, 14 Sep 2015 08:39:16 GMT
Last-Modified:Thu, 09 Apr 2015 19:00:10 GMT
X-Timestamp:1428606009.00160
X-Trans-Id:tx1950324dcceb48e18df2a-0055f29355ord1
```

My guess is that the non working source is not properly delivered and that is the reason why videojs can not play it. 

With that said, I wanted to check this out with you to ensure that it is not a bug.
What do you think?

**Comment by mister-ben** [comment]
Despite the file extension, that file is FLV so the `Content-Type` header is correct there. You can check that with medainfo or by putting VLC through Charles proxy.

The Flash tech can play this (http://output.jsbin.com/lepaba) but the HTML5 tech (an HTML5 video element) cannot. 

The `type` in the VAST response is wrong, presumably the VAST plugin you're using wouldn't attempt to load an FLV into the HTML5 tech if it were corrected.

**Comment by carpasse** [comment]
Thanks @mister-ben you are right even though the extension is mp4 the file is flv. 
Thanks for the quick response.
