### ISSUE TITLE
video.js 5.0 - dimensions() does not override CSS sizing

### ISSUE THREAD

**Issue by forbesjo** [videojs/video.js#2581]
`dimensions()` does not resize the player if the player's size has been set through CSS.

Here's the 4.x behavior https://jsfiddle.net/forbesjo/jfpf2ybe/1/
Here's 5.0 rc 77 http://jsfiddle.net/uyszLa2n/5/

**Comment by heff** [comment]
That's actually how it should work. With the video element, when you set the width/height properties on the element, CSS is still dominant. In 4.x we used inline styles which had the reverse effect of making it impossible to style with CSS.

Closing this but let me know if you have other thoughts on how it should work.

**Comment by gkatsev** [comment]
Huh, didn't know. Good to know: https://jsbin.com/sofiqe/edit?html,css,output
