### ISSUE TITLE
I'm using "Track" Tag  encountered a problem, how to solve?

### ISSUE THREAD

**Issue by Xia-lj** [videojs/video.js#2585]
Text track from origin 'http://www.videojs.com' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'null' is therefore not allowed access.

----
    <video id="MY_VIDEO_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="264" poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
        <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
        <source src="MY_VIDEO.webm" type='video/webm'>
        <track kind="captions" src="demo.captions.vtt" srclang="en" label="English"></track>
    </video>
-----
or:
-------
Failed to load resource: net::ERR_FILE_NOT_FOUND
video.js:9 'webkitMovementX' is deprecated. Please use 'movementX' instead.
video.js:9 'webkitMovementY' is deprecated. Please use 'movementY' instead.
test1.html:1 Text track from origin 'file://' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'null' is therefore not allowed access.
-----

I'm using "Track" Tag  encountered a problem, how to solve?

<h3>I'm Dish Bird 。。Sorry!!!</h3>

**Comment by mmcc** [comment]
The deprecation notices you're seeing are unrelated, but the original track issue is due to a security feature in browsers called CORS. You can find more information about it [here](https://github.com/videojs/video.js/issues/2585), but you can fix it by hosting the vtt file in the same place as your player (or host it somewhere with CORS enabled). Hope that helps!

**Comment by gkatsev** [comment]
If it's hosted on somewhere with cors, you'll need to enable `crossorigin` attribute on the video element, which would require the video itself to also have CORS enabled on them.

**Comment by Xia-lj** [comment]
@mmcc @gkatsev 
Good. Thank you very much. I appreciate your help.
I understand.
