### ISSUE TITLE
How to add psuedo streaming on flash

### ISSUE THREAD

**Issue by sufyandeveloper** [videojs/video.js#2586]
When i seek forward flash video it's not working it's only forward 2 to 4 sec video and i think it will handle when i apply psuedo streaming on flash player but how can i implement pseudo streaming.

Thank you

**Comment by dmlap** [comment]
Psuedo-streaming isn't supported but there have been some efforts to add it. You can check them out in the [video-js-swf project](https://github.com/videojs/video-js-swf/pull/135)
