### ISSUE TITLE
Progressbar issue when src is a controller method

### ISSUE THREAD

**Issue by Albermg7** [videojs/video.js#2587]
Hi :)
I am using videoJs with ASP.NET MVC and I am having an issue when using as **source the url for a controller method returning the file**. Something like:

http://localhost/QuickPlayer/Play?Id=1234

The method returns a FileResult, with the corresponding mimetype and the **player is actually able to read and play it**. However, wherever I click in the progressbar the video start playing from the beginning (and so the marker goes there as well)

Is there a way to make it work properly calling a method that returns the mp4 (or mp3 where playing audios)?

**Comment by mmcc** [comment]
I don't think this is a problem with the way you're adding the source, normally this kind of issue is related to the application serving the file. Does your server support byte-range requests? One thing to test would just be setting the source statically instead of returning it via a method just to make sure you see the same symptoms. 




If you put up an example showing the issue (http://jsbin.org/axedog/latest/edit) it would make it a lot easier for folks to help debug.



—

**Comment by Albermg7** [comment]
Thanks for the fast answer :)

It's not about how I am adding the source cause it is working when the src is directly a mp3. I can't reproduce it totally since I need to be logged and we don't have access from the outside but an example could be the next one:

https://jsbin.com/tibugo/edit?html,output

Imagine the url in the second video returns a FileResult, in the first video, if I click at some point in the progressbar, it start playing from that point. However, in the second one, if I click at some point, the audio start from the beginning. 

I have also tried with [this link that download the mp3](http://www.youtube-mp3.org/get?video_id=KMU0tzLwhbE&ts_create=1442242509&r=ODQuMTI0LjUwLjE%3D&h2=f13a9f09c19fe42e859209c8cdbe6037&s=133680) instead of playing it directly in the browser and it is working.

Could it be a problem with the FileResult type in the method?


The method that returns the mp3 is that simple:

```c#
		[HttpGet]
		public FileResult Play(string recordingId, FileType recordingType, QuickPlayerModel.ActionType downloadType)
		{
		
				// Recoger la ruta de la reproducción de sessión
				string path = _recordingsSessionManager.GetPathRecordingById(recordingId, recordingType, downloadType);

				string mimetype;
				string extension;

				if (recordingType == FileType.Audio)
				{
					mimetype = "audio/mp3";
					extension = ".mp3";
				}
				else
				{
					mimetype = "video/mp4";
					extension = ".mp4";
				}

				return File(path, mimetype);

		}
```

Thanks a lot

**Comment by mmcc** [comment]
Progress! The bad news, this has me pretty convinced that this is an issue with how the file is being served. Again, based on what I'm seeing above, I highly doubt you've also implemented things like [byte range requests](https://en.wikipedia.org/wiki/Byte_serving) which would cause the issue you're seeing.

**Comment by Albermg7** [comment]
Hi, 
Sorry for my late answer but we have been trying to fix it and we don't think its something related with byte range requests because it is working properly on Firefox and IE11. This "buggy" behaviour is just happening in chrome.
Is that some of a clue?

We were using videojs 4.12 but I have updated it to the last RC of version 5.0 and the problem is still there. I will make you know if we discover where it is coming from. And if you have some clue, it would be extremly helpful since we are spending lot of time trying to find it

Thanks :)

**Comment by mmcc** [comment]
Really sorry, but there is absolutely nothing we can do without seeing an example that reproduces the issue. Despite it working in some browsers, if you're using your own, homegrown HTTP server to delivery media files, my money's on that being the problem. Don't mean that as a knock against you all, of course, just after enough time manning this tracker you start to see some pretty consistent trends with [this kind of thing](2198). :)

Try putting a problematic file on something like S3 and see if you still see the issue. If it does still happen, I'm wrong and your server isn't at fault, so what version of Chrome / OS are you using?

**Comment by Albermg7** [comment]
Thanks a lot Mathew. After take a deep search it seems you were right! IIS is implementing byte-range requests and that's why serving a file allocated in the server through a public address is working fine.

I will write here how we solved that in ASP.MVC as soon as we have something ;)

**Comment by mmcc** [comment]
Nice!! Glad to hear I at least *kinda* helped. :) Definitely fill us back in when you have a solution worked out.

**Comment by Albermg7** [comment]
Hi again!
We were able to fix it following your indications. You were totally right about the byte range requests so we implemented them after reading this (bit old) [http://tpeczek.blogspot.com.es/2011/10/range-requests-in-aspnet-mvc.html](example). 

Just to mention for people facing this problem that if they use URLs to the media itself, hosted somewhere in the server, it will work, because the Microsoft IIS is implementing byte range requests in a transparent manner. However if you need to add some authorization, or any other logic after returning the media, support for byte range requests will be necessary.  

Thanks a lot for your help guys ;)
