### ISSUE TITLE
loadstart getting triggered twice

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#2588]
This may be related to #1194

**Comment by mmcc** [comment]
There were also older issues that talked about similar things and if related, I don't think there's much we can do about it. IIRC, at least when preload is set to auto or true, the browser would start loading the file before VJS swaps the video element into the new wrapper div, then the second loadstart event is fired. I could be wrong, but I'll try to find the older issue when I get to a better internet connection.

**Comment by misteroneill** [comment]
FWIW, this appears to be a new issue in 5.0. It was revealed by a test for the videojs-contrib-ads plugin when I upgraded it for 5.0 compatibility. I then ran the same test against the previous 4.x compatible version of the plugin and only one loadstart was triggered.

Here's a JSBin demonstrating it: http://jsbin.com/xejigukepa/1/edit?html,console,output

**Comment by mmcc** [comment]
Ah bummer, that blows that theory to smithereens.
