### ISSUE TITLE
Volume button not showing correctly

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2592]
Hi I updated https://gerrit.wikimedia.org/r/#/c/212981/ yesterday to latest video.js release and seems volume is now along instead of straight up and also scroll bars are showing making it diffulculty in changing the volume.

Tested in internet explorer on windows 10.

**Comment by heff** [comment]
Which specific version are you using now? It sounds like you upgraded from
4.12.x to 5.0. In 5.0 we made a bunch of skin changes, and it's not
officially released yet, though it will be soon.

Any chance you can set up a test page where we can see the scroll bar issue?

**Comment by paladox** [comment]
Seems to be fixed since updating to latest rc which I just did. Latest as In upgraded from 5.0 rc 81 to rc 84.
