### ISSUE TITLE
Help choosing a resolution plugin

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2593]
Hi I am trying to get resolution plugin to work with this patch https://gerrit.wikimedia.org/r/#/c/212981/ but dosent seems to work.  it is using videojs version 5 rc 84.

**Comment by mmcc** [comment]
Hi there, you'll need to open an issue on the resolution selector plugins and have them update. Keep in mind that 5 is still pre-release software and although it's *mostly* stable, we're still ironing out the last kinks before going to production. Basically, at this point use 5.0 in production at your own risk, but it should be officially released very, very soon.
