### ISSUE TITLE
Stable API docs refer to master src

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#2595]
When clicking the javascript source link in the api docs of the stable branch, it gets redirected to the master docs, eg. https://github.com/videojs/video.js/blob/stable/docs/api/vjs.CoreObject.md goes to https://github.com/videojs/video.js/blob/master/src/js/core-object.js (that doesn't exist in master).

**Comment by heff** [comment]
Oh man, that's not good. Not sure how that happened. Thanks for pointing it out. We're trying to get the 5.0 docs built on jsdoc out soon. That might happen before we can get to fixing this issue.
