### ISSUE TITLE
Need help with mouse time display.

### ISSUE THREAD

**Issue by vtur** [videojs/video.js#2596]
How do I display a tooltip with time of transition on  vjs-play-progress? Like on youtube without picture.
![screenshot_1](https://cloud.githubusercontent.com/assets/11783415/9900081/ea3ea884-5c66-11e5-9e12-bd41a549d1f2.png)

**Comment by nebrot** [comment]
Do you mean something like this https://github.com/videojs/video.js/pull/2569 ? This feature was added with rc86.

**Comment by vtur** [comment]
Thank, in 4.8.4 version i must do it myself.
