### ISSUE TITLE
Plugin suggestion for videojs

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2598]
Hi could a plugin be created that lets users download the video in different resolutions please. Or please can this be built in.

**Comment by mmcc** [comment]
I don't feel like this necessitates a plugin, you could just iterate over the list of resolutions you're passing to your resolution plugin and show a URL somewhere for each one. If you think it should be built in, this seems like a feature request for the resolution switching plugin.

**Comment by paladox** [comment]
I mean a menu as in a big menu not but that shows a list just big menu covering the whole player. it will make sure there isent a lot of clutter since enabling all those buttons makes everything smaller.

**Comment by mmcc** [comment]
I'm not sure I follow. Are you thinking something similar to the captions settings menu? That could make a lot of sense, but I still think this belongs in the resolution switcher plugin if anywhere.

**Comment by paladox** [comment]
I mean a menu to see what I mean please see https://commons.wikimedia.org/wiki/File:Gymnothorax_javanicus_(by_night).webm there should be a button in the video player that says menu once clicked that is what I mean.

**Comment by mmcc** [comment]
Ah I follow, I like the menu idea but the worry is that it would immediately become the cluttered kitchen drawer. Either way, we wouldn't implement this in core so it would need to be a plugin.

**Comment by paladox** [comment]
Ok.

**Comment by paladox** [comment]
yes it may be cluttered but currently the whole control bar is cluttered if you have allot added. Where as keeping it in a menu most of it it will make the player look nicer.
