### ISSUE TITLE
How to enable selecting resolutions in videojs

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2600]
Hi how can I allow selecting resolutions in this patch https://gerrit.wikimedia.org/r/#/c/212981/ since Wikimedia is trying to convert timedmediahandler extension used on Wikipedia and whole of Wikimedia foundation to a better video player and have selected yours. We are currently switching from kaultra player. I doint know how to enable selecting resolutions since doing this is different in timedmediahandler.

**Comment by mister-ben** [comment]
This isn't a core feature but there are a couple of such plugins on the [plugins wiki page](https://github.com/videojs/video.js/wiki/Plugins).
