### ISSUE TITLE
Plugin for switching to different formats

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2601]
Hi is there any plugins or anything that you can enable to be eable to switch to different formats eg webm to ogv or ogv to webm please. I am working on a patch at https://gerrit.wikimedia.org/r/#/c/212981/

**Comment by mmcc** [comment]
What's the reasoning behind wanting a plugin like this? On that note, why support both WebM and ogv in the first place? At this point there are basically no browsers[1] that would support OGV and not WebM, so you're not getting any additional support by having both. From a UX perspective, showing viewers both in a rendition switcher is generally just going to confuse them unless they actually understand the video space, so this feels like it's going to confuse more than help.

That being said, this feels like the resolution switcher could probably be modified to do this without too much work (famous last words).

[1] There are a few *ancient* browsers that support OGV and not WebM, but I'm talking Chrome 5 old (current version is 45).

**Comment by paladox** [comment]
Well there are many videos on commons.wikimedia.org that play ogv videos. There is currently a plugin in working in the timedmediahandler extension that gets any browser to play ogv videos. Including internet explorer.
