### ISSUE TITLE
make sure only one `style-defaults` element is ever added to the DOM

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2606]
If you require videojs in a plugin but also include videojs separately as a global, you end up with two `style-defaults` elements. We want to make sure:
* `style-defaults` only ever gets added once
* make sure that we don't have any other side-effects of having multiple videojs's.

The particular usecase is to require videojs directly so a plugin could, for example, require videojs itself to get a component to extend.

**Comment by heff** [comment]
Sounds like we have a bigger problem to figure out there long term, in the direction of breaking out components.

**Comment by gkatsev** [comment]
Making `style-defaults` only show up once is an easy fix which we should definitely get into 5.0. The other part is definitely a bigger piece and can be punted on for 5.1 or later.

**Comment by heff** [comment]
Closed by #2619
