### ISSUE TITLE
Should component's internal options property be renamed `options`?

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2607]
Not exactly sure what the precedence for this is. We should definitely decide on this before 5.0.
But since `this.options_` is supposed to be used by users making custom components, should we just rename the variable to be `this.options`? The underscore would seem to imply that the user writing the component should try and avoid this variable as well since it generally means library private in addition to component private.

**Comment by heff** [comment]
`options` is still a (deprecated) setter/getter function, so I think it's going to be a longer road to changing that process. My hope is that we can move options to something that's just part of the init process, not something that gets used throughout the operations of the component. Component properties should be created for options that you need access to later, e.g. player.preload().

See #2033 and #2229. Does that answer your question or am I missing a detail?

**Comment by gkatsev** [comment]
Nope, I think that makes sense. Once it is completely removed, a user could always make their own `options` reference.
