### ISSUE TITLE
information about buffered ranges seems to be wrong wrong when jumping in video

### ISSUE THREAD

**Issue by IgelCampus** [videojs/video.js#2609]
**What did you do? (steps to reproduce)**
Used a plugin to check current position of played video compared to the given buffered ranges to find the currently played buffere range.

``` javascript
(function (videojs) {
    videojs.test = {
        testHandler: function () {
            if (new Date().getTime() - this.player_.test.options.lastUpdate > 2500) {
              this.player_.test.options.lastUpdate = new Date().getTime();
              var buffered   = this.player_.buffered();
              var currentPos = this.player_.currentTime();
              console.log("UPDATE test found " + this.buffered.length+" buffers, playing @ "+currentPos);
              for (bufferIdx = 0; bufferIdx < buffered.length; ++bufferIdx) {
                var start = buffered.start(bufferIdx);
                var end   = buffered.end(bufferIdx);
                console.log(bufferIdx + " from " + start + " to " + end + " is currently played = " + (currentPos > start && currentPos < end));
              }
            }
        }
    };
    videojs.plugin('test', function () {
        this.player_.test = {"options": {"lastUpdate": 0}};
        this.player_.on("timeupdate", videojs.test.testHandler)
        console.log("INIT test");
    });
})(videojs);
```

**What happened? (actual results)**
Clicking into the progress bar creates a situation where none of the reported buffered ranges contains the currently played position.

**What should have happened? (expected results)**
I would expect one buffer range containing the currently played position.

**Additional Information**
Tested videojs 4.12.11
Tested PaleMoon 25.7.0
Tested IE11
no difference in behavior for these different browsers

**Comment by dmlap** [comment]
What format videos were you testing with?

**Comment by IgelCampus** [comment]
I was testing with a MP4 generated by ffmpeg. I could also provide the exact ffmpeg settings if required.

**Comment by gkatsev** [comment]
This is a really old issue with a really old version of Video.js. Please re-test with a newer version of Video.js and let us know if it's still an issue. Thanks.
