### ISSUE TITLE
Suggestions for plugins to detect formats

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#2610]
Hi this is a suggestion and for a built in core feature but could the player add support for detecting if that browser can play the format the video is in. including in transcoded format. so that plugins can use that code to detect it. Please see https://github.com/dominic-p/videojs-resolution-selector/issues/35#issuecomment-140927902

**Comment by heff** [comment]
It sounds like you could just use the video element's canPlayType.

```
document.createElement('video').canPlayType('video/mp4; codecs=avc1.42E01E,mp4a.40.2');
```

Video.js also has
```
videojs.getComponent('Html5').nativeSourceHandler.canHandleSource({ src: '...', type: '...' })
```

We could probably make that more externally accessible.

Let me know if that doesn't do everything you need and we can reopen.

**Comment by paladox** [comment]
Well another user suggested that so that the player would return the resolutions and format that's the browser can play.
