### ISSUE TITLE
Flash doesn't work?

### ISSUE THREAD

**Issue by anonym24** [videojs/video.js#2613]
`<!DOCTYPE html>`
`<html>`
`<head>`
`<meta charset=utf-8 />`
`<title>Video.js Example Embed</title>`
  
`<link href="http://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">`
`<script src="http://vjs.zencdn.net/4.12/video.js"></script>`
  
`</head>`
`<body>`
`  <h1>Video.js Example Embed</h1>`
  
`  <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" data-setup='{ "techOrder": ["flash"] }'>`
 ` <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>`
  `</video>`

 ` <script>`
`  </script>`
  
`</body>`
`</html>`

 It doesn't work for me.
I can't play the video. Only HTML5 works for me.

**Comment by mmcc** [comment]
What browser are you using? [Works for me](http://output.jsbin.com/badefuwewo), but I did have to tell Chrome to allow the Flash plugin. Keep in mind most modern browsers have started to get pretty hostile towards Flash.

**Comment by anonym24** [comment]
I tested all browsers (FF, Opera & Chrome - the latest versions). I'm trying to test that code opening as local file (file:///C:/****Desktop/index.html).

**Comment by mmcc** [comment]
Yeah, unfortunately that's [not going to work](http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00000451.html). If you set up a simple http-server locally and test it should work fine.

**Comment by anonym24** [comment]
I forgot about it) Thanks.
It's just easier to test different videos when you have it on your PC (<source src="example.mp4" type='video/mp4'>). But I must upload it on some server first.

**Comment by mmcc** [comment]
Nah you don't need to upload it anywhere, you can just run a simple local server in that directory. My personal go-to is [http-server](https://www.npmjs.com/package/http-server).

**Comment by anonym24** [comment]
Ok) I find out something (but for Windows)

**Comment by mmcc** [comment]
Node runs on Windows.

**Comment by anonym24** [comment]
Yeah.. right
OK, thanks again
