### ISSUE TITLE
RMTP not Working

### ISSUE THREAD

**Issue by fbonesso** [videojs/video.js#2614]
Hey guys,

I'm trying to make this work with my Nginx + RTMP server but if no luck.

Here is my code:

`<video id="home_video" controls preload="none" class="video-js vjs-default-skin">`
`<source src="rtmp://my_ip/live/key" type="rtmp/mp4">`
`</video>`

The is anything wrong?

Thanks!

**Comment by mmcc** [comment]
Your source url is [formatted incorrectly](https://github.com/videojs/video.js/blob/fb5d0ce6ad28fe3aaeab35e0e4ce5779d75e3b4b/docs/guides/tech.md#enabling-streaming-playback). Give that a try and let us know if that helps.

**Comment by fbonesso** [comment]
Its a live stream, I only have the key at the end of URL, I dont have the file extension. Sorry, I don`t know if I`m doing something wrong. It works fine with wowza test player. Thanks for the help.
