### ISSUE TITLE
Video.js 5.0 - Cannot call videojs.extends in IE8

### ISSUE THREAD

**Issue by forbesjo** [videojs/video.js#2620]
it looks like extends is a reserved keyword in IE8 which causes calls to videojs.extends to give an "expected identifer" error. Using videojs['extends'] works around this. 

Perhaps this function should be renamed.

**Comment by misteroneill** [comment]
It seems that consensus on Slack is to rename it `extend`.

**Comment by heff** [comment]
Closed by #2624
