### ISSUE TITLE
Ads contrib for 5.0?

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2626]
Hi all!

We are already working against video.js 5.0 for an upcoming project.
However, one of the things we need is the google IMA for ads.
Before being able to do that I guess the videojs-contrib-ads plugin needs to work on 5.0, which it does not currently.

Are there any plans for updating this in the near future? I am willing to actively help develop the update in the comming weeks if that would help.

Please let me know!

p.s. I created the issue here as it seems the "main" projects issues seem to be read more often.

**Comment by gkatsev** [comment]
We do read the issues on the separate projects and it's more appropriate to open the issue on the corresponding project.
Also, we are in the process of updating those plugins to get 5.0 support. There's already a branch and PR you can try out: https://github.com/videojs/videojs-contrib-ads/pull/116
If you do try it out, please let us know if you have any issues.

Thanks.

**Comment by nickygerritsen** [comment]
OK sorry I didn't look hard enough I guess. I will try it out, thanks!

**Comment by gkatsev** [comment]
No worries.
