### ISSUE TITLE
No method to dynamically change <tracks>

### ISSUE THREAD

**Issue by hparra** [videojs/video.js#2628]
This is probably related to #2369.

**I was looking for something similar to `player.src([{}])` but for tracks**. I have browsed issues at https://github.com/videojs/video.js/milestones/Text%20Tracks and read https://github.com/videojs/video.js/blob/stable/docs/guides/tracks.md but I am still confused by how related TextTrack API is supposed to work. Any clarification and known pitfalls would help me to take a stab at this.

I'm still on 4.x and would be implementing anything against that.

Related: Would a method to dynamically change all video child tags at once be useful? I could see why changing just the tracks mid-play would be a more difficult change.

**Comment by hparra** [comment]
Anyone? @heff?

**Comment by gkatsev** [comment]
The API for working with text tracks currently mimic the native text track APIs.
There's a `player.addTextTrack` which creates a programmatic text track and allows you to manually add cues to that track that you get.
Also, more useful to you, there's `player.addRemoteTextTrack`, this is a function that takes an object that looks pretty similar to the track element. It will then go and create the track for you. There's a corresponding `player.removeRemoteTextTrack` method to remove these. Note, you cannot remove tracks created by `player.addTextTrack`
You can also see what tracks are available by getting them in `player.textTracks()` or just the remote tracks with `player.remoteTextTracks()`.
A quick way to swap out all the tracks would be to grab each of them with `player.remoteTextTracks`, remove them with `player.removeRemoteTextTracks`, and then add new ones with `player.addRemoteTextTracks`. Maybe something like:
```js
var oldTracks = player.remoteTextTracks();
var i = oldTracks.length;
while (i--) {
  player.removeRemoteTextTrack(oldTracks[i]);
}
myNewTracks.forEach(function(track) {
  player.addRemoteTextTrack(track);
});
```

And yes, we really need to fix up and update our documentation relating to text tracks and how to use them.

**Comment by gkatsev** [comment]
@hparra does my previous comment help? Sorry for the delayed responses.

**Comment by hparra** [comment]
Thanks @gkatsev. Not sure yet, other fires... Were there (planned) changes in between 4.x and 5.x?

**Comment by gkatsev** [comment]
There was a change between v4 and v5 around the main text track list object that videojs has but that shouldn't affect you.
Ok, let me know when you get a chance. I'll leave it open.

**Comment by chemoish** [comment]
@gkatsev is there currently a way to detect the loading of remoteTextTracks?

I initially thought to use `track.addEventListener('load')`, but this is only available to Chrome.

I reimplemented:

https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/text-track-button.js#L33
https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/chapters-button.js#L87

I also manage swapping remoteTextTracks similarly to what you suggested above.

However, there is that setTimeout race condition that seems to be exacerbated when encrypted content (MPEG-DASH). 100ms doesn't seem to be enough time to have cues get populated.

https://github.com/videojs/video.js/pull/1949 also doesn't seem to apply as native implementations bypass TextTracks.

Thoughts?

**Comment by chemoish** [comment]
The setTimeout *might* be a red herring. It seemingly difficult to filter through the events.

However, increasing the delay makes it work more consistently (200ms).

Could we instead leverage #1949 for emulated track load detection and use `track.addEventListener('load')` for native?

Not sure if this is best solution.

**Comment by chemoish** [comment]
Moving this to its own issue.

**Comment by hparra** [comment]
Thanks again @gkatsev. Was also bitten by _nativeTextTracks_ as mentioned in #2124.

Was the example in your comment supposed to remove the `<li>` children from the Chapter menu as well? It is not doing so, even though it is hiding the button.

**Comment by gkatsev** [comment]
Yeah, I think there are problems with the chapters menu right now. I'll be investigating them this week.

**Comment by hparra** [comment]
OK. FYI, this is with final version in 4.x series. Any clues for poking around welcomed. Was some listener supposed to remove them?

**Comment by gkatsev** [comment]
Closed by https://github.com/videojs/video.js/commit/18cdf08c0e784073d37d3dfc807dfb47eccdd344
