### ISSUE TITLE
Entering fullscreen triggers never-ending "fullscreenchange" events in Microsoft Edge

### ISSUE THREAD

**Issue by gfemec** [videojs/video.js#2640]
To reproduce go to http://www.videojs.com in Edge, play the video, and click on the full screen button.  The developer tools should show a `SCRIPT28: Out of stack space` exception.

I think the root cause is that Microsoft Edge doesn't use vendor prefixes for full screen events.  In particular it supports `exitFullscreen`.  https://msdn.microsoft.com/en-us/library/dn254936%28v=vs.85%29.aspx

This means the full screen api uses the first entry of `apiMap` and `FullscreenApi.fullscreenchange` equals `"fullscreenchange"`.  https://github.com/videojs/video.js/blob/master/src/js/fullscreen-api.js#L18

So this line https://github.com/videojs/video.js/blob/master/src/js/player.js#L1526 registers an event listener on the document for `"fullscreenchange"` which is then triggered by https://github.com/videojs/video.js/blob/master/src/js/player.js#L1534 when the event bubbles up creating a never-ending cascade of events.

I fixed this quickly by renaming the event videojs uses to `"vjs-fullscreenchange"` but I'm unsure if this is the best fix or if there are other ramifications of the way Edge handles full screen api events.

**Comment by forbesjo** [comment]
This looks to be fixed in video.js 5.0

**Comment by gfemec** [comment]
I see, thanks, yeah in 5.0 the default is for events to not bubble so the listener on the document for fullscreenchange is never triggered.
