### ISSUE TITLE
Video does not reset to 0 after finished playing

### ISSUE THREAD

**Issue by angelathewebdev** [videojs/video.js#2641]
I'm using version 4.12.11, and I saw that it has been mentioned in this pull request

https://github.com/videojs/video.js/pull/2519

But when the video finishes playing, it doesn't get reset to 0 (actually, I prefer it gets reset back to the initial state with posters). I have it online at http://raventech.com/

**Comment by mmcc** [comment]
I don't think that PR is going to make its way into a v4, but it's in v5 (which should officially be released as stable within a week)

**Comment by marceloxp** [comment]
Same to me :(
After finished the command player.currentTime(0) and/or player.play() not work; The loading is showing for ever.
