### ISSUE TITLE
"The video could not be loaded" on firefox 41

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2644]
Hi guys, I updated my firefox version to 41 and now I have problem to play videos on my site with Video-js. In every video appears this error: The video could not be loaded, either because the server or network failed or because the format is not supported

So I tried to downgrade to Firefox 40 and now every video started to work again. I don't know why, but it seems to be a problem with the 41 version. Do you know how to fix this problem?

In Chrome every videos works fine.

**Comment by mister-ben** [comment]
The video at http://www.videojs.com/ is fine for me on Firefox 41 (Mac). Can you provide any more information? Is it specific to your site?

**Comment by giggioman00** [comment]
Yes, it seems specific to my site. But this is pretty strange because in firefox 40 everything works OK, in google Chrome everything works OK but in firefox 41 I get that error.

Also, if I try to move the video files to another domain and then change URL on video-js script, then the video start again even in firefox 41. I really no have idea of the problem... What's your opinion?

**Comment by giggioman00** [comment]
EDIT: It seems the problem is about this line of htaccess

<FilesMatch "\.(?i:mp4)$">
  ForceType application/octet-stream
  Header set Content-Disposition attachment
</FilesMatch>

I don't know why... It's only a line for avoid double streaming at the source url... But if I remove this line, everything works again even in firefox 41... Do you have any idea?

**Comment by gkatsev** [comment]
It's forcing mp4 filetypes into `application/octet-stream`? That seems weird.
Closing this issue since it doesn't seem like an issue with videojs (or one we could fix anyway). But we can continue to discuss it, if there's anything else.
