### ISSUE TITLE
Out of date line numbers in documentation

### ISSUE THREAD

**Issue by kand** [videojs/video.js#2646]
Event line numbers are incorrect: https://github.com/videojs/video.js/blob/master/docs/api/vjs.Player.md#events

Links should be pinned to a pinned to a specific version (or at least the latest release) and not master.

**Comment by mmcc** [comment]
Agreed. Honestly we're moving documentation out of this repo and handling it [elsewhere](https://github.com/videojs/docs), so this shouldn't be an issue in the very, very near future. Going to close this since the process has already changed for 5.0.

**Comment by kand** [comment]
:+1: thanks
