### ISSUE TITLE
Full screen button don't work in bootstrap modal

### ISSUE THREAD

**Issue by leetas** [videojs/video.js#2648]
Hello,
Here is my code example:
`div class="modal fade bs-example-modal-lg" id="modal-video">`
   ` <div class="modal-dialog modal-lg">`
        `<div class="modal-content">`
            `<div class="modal-header">`
                `<h4 class="modal-title text-center" id="video-modal-title">`
                `</h4> <!-- .modal-title -->`
            `</div> <!-- .modal-header -->`
            `<div class="modal-body">`
               ` <video id="example_video_1" class="video-js vjs-default-skin"`
                     `  controls preload="auto" width="640" height="264"`
                       `poster="http://video-js.zencoder.com/oceans-clip.png"`
                       `data-setup='{"example_option":true}'>`
                    `<source src="http://video-js.zencoder.com/oceans-clip.mp4" type='video/mp4' />`
                    `<source src="http://video-js.zencoder.com/oceans-clip.webm" type='video/webm' />`
                    `<source src="http://video-js.zencoder.com/oceans-clip.ogv" type='video/ogg' />`
                    `<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>`
                `</video>`
            `</div> <!-- modal-body -->`
       ` </div> <!-- .modal-content -->`
   ` </div> <!-- .modal-dialog -->`
`</div> <!-- #modal-delete.modal.fade -->`

When I push the 'fullscreen' button video appears briefly and disappears.

**Comment by leetas** [comment]
Problem solved. 
Modal transfer the upper div.

**Comment by Syedwaheed** [comment]
@leetas can you please help me with how to show my video in modal when i click the play button. I m unable to do this. I need this ASAP. Any help from you would be appreciated. Thanks.

**Comment by leetas** [comment]
In our project was javascript conflict, when we resolved it video works fine.

**Comment by Syedwaheed** [comment]
Can you tell me how to show the video in modal. I m unable to do it.

**Comment by leetas** [comment]
I dont rimember... its very old issue
