### ISSUE TITLE
How to show videojs controls without any video

### ISSUE THREAD

**Issue by Albermg7** [videojs/video.js#2649]
Hi :)
I have videojs control-bar always visible at the [end of the page](http://postimg.org/image/jmzb4k5g9/). The user can select some recordings to be loaded there. However, at the beginning, when no recording has been selected I'd like to keep showing the control bar with the play button disabled. 

If I leave a the "src" attribute in blank, I got an error. I could use an mp3 with no sound on it, but I would like to avoid vidojs to try downloading any audio/video at this point. 
Is that posible? 

I manually hide the bigplayButton, and show the control bar

Thanks a lot

**Comment by mmcc** [comment]
Hm this is an interesting question, I don't know if I've ever thought through a scenario like this before...

Let me think through this one some more, but if you wanted to go the mp3 route you can simply set `preload="none"` on the element and it won't try to download anything.

**Comment by gkatsev** [comment]
A workaround would be to add `vjs-has-started` class to the player.

**Comment by gkatsev** [comment]
You may need to add the `vjs-has-started` class in a `loadstart` listener.

**Comment by scottmberry** [comment]
A note on this, vjs-has-started also causes the poster image to be hidden. So, while this shows the controls it has other, unintended effects.
