### ISSUE TITLE
videojs problem upgrade to 5.0

### ISSUE THREAD

**Issue by niozhanghuawei** [videojs/video.js#2650]
After videojs upgrade to 5.0, m3u8 can not play, hls extends error.

videojs.hls.min.js:3 Uncaught TypeError: Cannot read property 'extend' of undefined

Help!

**Comment by gkatsev** [comment]
The currently released version of HLS isn't compatible with videojs 5.0. There's a development branch there which adds support for videojs 5.0 and we'll hopefully be releasing a version of that very very soon.

**Comment by gkatsev** [comment]
Closing as this is an issue with contirb-hls which is already being addressed there.
