### ISSUE TITLE
Dynamically sized video

### ISSUE THREAD

**Issue by tfr** [videojs/video.js#2651]
Hi,

I'm trying to put a video player on a responsive site. The default/maximum width of the video box is 660x330px, so by default the video tag is defined as <video width="660" height="330">. However, on mobile devices, this should be scaled down so that the video is 100% of the container width (+padding on sides).

Omitting the width/height attributes and setting width to 100% and height to auto in CSS did not work, so I tried the following JavaScript approach:

    $("video").each(function(){
      var containerwidth=$(this).parent('div.videowrapper').width();
      if (containerwidth<660)
      {
        var containerheight=Math.round(containerwidth/2);
        $(this).attr('width',containerwidth);
        $(this).attr('height',containerheight);
      }
    });

This works fine on Safari, however does not work on other browsers (tried on Chrome and Firefox on Mac, did not get around to trying Windows ones yet).

Also, notably, if I set the video ID to id="myvideo" in the HTML, on Safari, $(this).attr('id') returns "myvideo" as expected, whereas Chrome and Firefox return "myvideo_html_api" and looks like this element is placed somewhere else in the DOM, because the parent('div.videowrapper').width() returns "undefined". I did a hacky workaround there:

    $("video").each(function(){
      var video_id=$(this).attr('id');
      video_id=video_id.replace('_html5_api','');
      var containerwidth=$('#wrapper_'+video_id).width();
      if (containerwidth<660)
      {
        var containerheight=Math.round(containerwidth/2);
        $(this).attr('width',containerwidth);
        $(this).attr('height',containerheight);
      }
    });

This way, I get the correct elements and their widths, but setting the width and height attributes does not affect anything on Chrome/FF.

I assume the different behaviour can most likely be blamed on native HTML5 support on one browser and Video.JS magic on the others, but skipping that, the baseline question is - is there a way and how to get this working?

Thanks in advance,
Indrek

**Comment by gkatsev** [comment]
Have you tried experiment with the `vjs-fluid` class? It should hopefully make it easier to change the size of the player more easily.

**Comment by gkatsev** [comment]
Closing since no response, but we can re-open if the suggested option doesn't help.
Thanks.
