### ISSUE TITLE
Emoji as Big Play button on iOS9?

### ISSUE THREAD

**Issue by surgevelocityllc** [videojs/video.js#2653]
See attachment. Only affects iOS so far. I am using the videojs CDN file.
![screenshot_2015-09-30-10-00-00](https://cloud.githubusercontent.com/assets/11379976/10195114/08a3beb0-675a-11e5-8c28-059f6bbcf189.png)

**Comment by gkatsev** [comment]
haha, this issue again. Looks like we need to change all our fonticon codepoint locations again.

**Comment by gkatsev** [comment]
Reference: https://github.com/videojs/video.js/issues/1160

**Comment by mmcc** [comment]
I see no bug here, this is clearly a feature. Didn't we say we switched fonts in 5.0? :trollface:

**Comment by gkatsev** [comment]
Do we have anything we can do here or does this require updating the codepoints of the fonticons? @mmcc

**Comment by surgevelocityllc** [comment]
I know this issue is popping up all over the web lately. It seems Apple has
done something recently to trigger this. It's obviously not critical, just
somewhat silly for my users to see play buttons as random smiley faces!

**Comment by gkatsev** [comment]
Is this still an issue?

**Comment by mmcc** [comment]
This should only be an issue if you don't specify the encoding on the overall page.

**Comment by surgevelocityllc** [comment]
Appears fixed. And I've always had utf-8 specified on all page headers.

**Comment by gkatsev** [comment]
Going to close this then. We can always re-open it again if it pops up again.
