### ISSUE TITLE
Minified stylesheet 5.0 failing

### ISSUE THREAD

**Issue by Tralapo** [videojs/video.js#2654]
Dear devs,

It seems the minified stylesheet for video.js 5.0 is broken. When I use the CDN-hosted files as advised in the Quick Start, I get the result as shown in the image. This happens in all browsers and both using CDN as well as hosting locally.

```
<link href="https://vjs.zencdn.net/5.0/video-js.min.css" rel="stylesheet">
<script src="https://vjs.zencdn.net/5.0/video.min.js"></script>
```

![videojs](https://cloud.githubusercontent.com/assets/11296429/10196346/c578aac2-6792-11e5-9696-ce101b9af2c7.jpg)

When I switch to the unminified version, the player does work as expected.
```
<link href="https://vjs.zencdn.net/5.0/video-js.css" rel="stylesheet">
<script src="https://vjs.zencdn.net/5.0/video.min.js"></script>
```
![knipsel](https://cloud.githubusercontent.com/assets/11296429/10196631/236ed79a-6794-11e5-98fd-f84e4f0a74ae.JPG)

**Comment by forbesjo** [comment]
That's weird, there's a quote missing at `url('../font/1.3.0/VideoJS.eot?)`

**Comment by calzoneman** [comment]
I ran into this same issue, and manually adding the quote fixed it.

**Comment by Tralapo** [comment]
@calzoneman Well, yes, that's true. But somebody should regenerate the one on the CDN ;)

**Comment by heff** [comment]
Fixed! (you may need to clear your browser cache) Sorry for the complication.
