### ISSUE TITLE
don't remove old docs

### ISSUE THREAD

**Issue by ZeeD** [videojs/video.js#2655]
switching on 5.0.0 you removed all 4.x documentation.

Instead you should let it be always available all (major) versions docs, something like https://docs.python.org/2.7/ vs https://docs.python.org/3.5/ docs

**Comment by gkatsev** [comment]
The docs are still available in the tags associated with a release: https://github.com/videojs/video.js/tree/v4.12.14/docs
But yeah, we probably should do a better job around linking to those from the new docs page. The new docs don't really live in the repo anymore.

**Comment by mmcc** [comment]
We can do something like Lodash, but they simply link from the current documentation on the website to old tags like we're suggesting. We should add a drop down like that to the docs page, so feel free to open an issue suggesting this on the [docs repo](http://github.com/videojs/docs).

**Comment by twig** [comment]
I really would have appreciated hosting of old docs somewhere.

Upgrading from v3 is a nightmare because of the lack of documentation.

**Comment by mmcc** [comment]
@twig I agree that ideally we could have a better experience around this, but @gkatsev's answer still applies here. You can still find 3.x documentation in the [Git history](https://github.com/videojs/video.js/tree/54ef0a775861061f8fb42125ec7d87ca82e13fa7/docs)

**Comment by twig** [comment]
ahh thanks.
had trouble finding repo tags only went back to v5

**Comment by mmcc** [comment]
Yeah unfortunately we weren't tagging yet in v3, so I had to dig through the releases for the commit hash :/
