### ISSUE TITLE
Update component page in docs to reflect new controls in 5.0

### ISSUE THREAD

**Issue by Tralapo** [videojs/video.js#2656]
With 4.x I used to hide almost all the controls in the controlbar, because I simply don't need them (live stream, no sound) and I like it clean. But it looks like that or the docs are wrong, or 5.0 isn't listening, but I can't get my controls hidden with the new version.

Both 

```javascript
var player = videojs('video-id', {
  controlBar: {
    muteToggle: false
  }
});
```
and
```javascript
data-setup='{ "controlBar": { "muteToggle": false } }'
```
from the docs do not seem to work at the moment. I tried all of them as muteToggle, MuteToggle and mutetoggle but nothing happens. I also tried starting a level higher like this (because that's how the component page in the docs starts):
```javascript
var player = videojs('video-id', {
  Player : {
     controlBar: {
       muteToggle: false
      }
  }
});
```
That won't work either.

**Comment by gkatsev** [comment]
The new volume control is a single control for mute toggling and volume. It's called the `volumeMenuButton`. If you replace `muteToggle` with `volumeMenuButton` it should work.
Going to close this, but please let us know whether it works or not.

Thanks!

**Comment by Tralapo** [comment]
A, well, thanks. That actually worked. Seems the 'Components' page in the docs needs an update then.

**Comment by gkatsev** [comment]
Looks like it does. Going to re-open it so we can track that.
Thanks!

**Comment by Tralapo** [comment]
Kind of related: In Microsoft Edge and on iOS, the player shows the text "LIVE" next to the Play/Pause button. This is hidden by default in the other browsers.

By checking with the inspector (oops, should have done that in the first place with the first issue) I found out this one is called 'liveDisplay' and can also be set to false so that text hides in every browser. (Don't know why it's only showing in some of the browsers by the way?).

Could be added to the components-page as well.

**Comment by richardbushell** [comment]
On the subject of the volume bar, I have tried everything I can think of to get vjs5 to use the vertical volume bar but I cannot get it to work, I have tried many many examples like:
{controlBar: {volumeMenuButton: {vertical: true}}}
but every combo I've tried fails.
What's the correct tree for this in vjs5?

**Comment by talamaska** [comment]
@richardbushell I think I have found the way you can mae the volume vertical, but it requires to change some css too
https://github.com/videojs/video.js/issues/2858

**Comment by richardbushell** [comment]
Great, please keep me in the loop if you find the solution.
Also, worth copying in @mmcc as I know he's working on the solution too in this post:
https://github.com/videojs/video.js/issues/2726

**Comment by talamaska** [comment]
```javascript
volumeMenuButton: {
                            vertical: true,
                            inline: false,
                            volumeBar: {
                                vertical: true
                            },
                            volumeLevel: false
                        },
```

**Comment by gkatsev** [comment]
The components page is now up-to-date with the default player components. https://github.com/videojs/video.js/blob/master/docs/guides/components.md
