### ISSUE TITLE
videojs.Flash undefined

### ISSUE THREAD

**Issue by spg** [videojs/video.js#2657]
I just tried the HLS getting started: http://videojs.github.io/videojs-contrib-hls/
I get errors that `videojs.Flash` is undefined.

I included video-js.css, video.min.js, videojs-media-sources.js and videojs-hls.js.

Any ideas what I might be missing?

**Comment by spg** [comment]
Response from my IRC chat with the team:

> if you're using videojs 5.0 videojs.Flash will be undefined. contrib-hls does not work with 5.0 just yet, but it is being updated soon. try using videojs 4.x in the meantime.

So the solution is to use video.js 4.x

**Comment by muneeb2542** [comment]
I just updated to the latest version of videojs and still experiencing this issue?
Any suggestions on what to do?

**Comment by gkatsev** [comment]
If you grade to the latest contrib-hls, it works with latest videojs 5.
