### ISSUE TITLE
HLS Stream

### ISSUE THREAD

**Issue by s2smatt** [videojs/video.js#2658]
Using an iPhone 6 (iOS 9) I can play back an HLS stream by placing the URL directly into Safari. No playback issues, I receive the video and audio. When I add a video element & video.js (version 4.12.15) to an empty web page, using the same HLS on-demand stream previously used above I get the video playing back, but no audio. 

I've tried using HLSv3 and HLSv4. I'm out of ideas on how to troubleshoot this one. Has anyone heard of this one before?

**Comment by gkatsev** [comment]
That's... bizarre. Would you happen to have a working example?
We've not had issues previously with native HLS playback and videojs because we just pass it through to the video element. We don't really do anything special and we can't even change the volume programmatically on ios.

**Comment by gkatsev** [comment]
Closing since no response, but we can re-open if still an issue and we get a reduced test case. Thanks.
