### ISSUE TITLE
Playback Rate buttons do not appear when loading video from hard drive

### ISSUE THREAD

**Issue by RAGolko** [videojs/video.js#2659]
I've specified the playbackRate parameters but they do not appear using video.js. Anyone know why? Below is working code; just copy to a text file, save as .htm and run it to see.
I have an example that works in the second block of code.

`<!DOCTYPE html>`

`<html>`

`<head>`
`<script>`
`window.onload=function(){`
   ` (function localFileVideoPlayerInit(win) {`
        `var URL = win.URL || win.webkitURL,`
            `displayMessage = (function displayMessageInit() {`
               `var node = document.querySelector('#message');`

               ` return function displayMessage(message, isError) {`
                node.innerHTML = message;
                node.className = isError ? 'error' : 'info';
            };
        }()),
        playSelectedFile = function playSelectedFileInit(event) {
            var file = this.files[0];
            var type = file.type;
            var videoNode = document.querySelector('video');
            var canPlay = videoNode.canPlayType(type);
            canPlay = (canPlay === '' ? 'no' : canPlay);
            var message = 'Can play type "' + type + '": ' + canPlay;
            var isError = canPlay === 'no';
            displayMessage(message, isError);
            if (isError) {
                return;
            }
            var fileURL = URL.createObjectURL(file);
            videoNode.src = fileURL;
        },
        inputNode = document.querySelector('input');                                               

    if (!URL) {
        displayMessage('Your browser is not ' + 
           '<a href="http://caniuse.com/bloburls">supported</a>!', true);

        return;
    }                                                                                              

  `  inputNode.addEventListener('change', playSelectedFile, false);`
`}(window));`
`}//]]>`
`</script>`
`<style>`
`video, input {`
   ` display: block;`
`}`

`input {`
   ` width: 100%;  `     
`}`

`.info {`
    `background-color: aqua;  `          
`}`

`.error {`
    `background-color: red;`
    `color: white;`
`}`
`</style>`
`</head>`
`<body>`
`<h1>HTML5 local video file player example</h1>`
`<div id="message"></div>`
`<input type="file" accept="video/*"/>`
`<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" `
`height="268" `
 ` data-setup='{ "playbackRates": [0.5, 1, 1.5, 2] }'>`
    `<source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>`
   `<source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>`
 ` </video>`
`</body>`
`</html>`

In the following code the playbackRate selector does appear. I can't figure out why it doesn't in the one above.

`<!DOCTYPE html>`
`<html>`
`<head>`
`<meta charset=utf-8 />`
`<title>Video.js Example Embed</title>`

  `<link href="http://vjs.zencdn.net/4.6.1/video-js.css" rel="stylesheet">`
  `<script src="http://vjs.zencdn.net/4.6.1/video.js"></script>`

`</head>`
`<body>`
 `<h1>Video.js Example Embed</h1>`

  `<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" `
 `data-setup='{ "playbackRates": [0.5, 1, 1.5, 2] }'>`
    `<source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>`
    `<source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>`
  `</video>`

  `<script>`
  `</script>`

`</body>`
`</html>`

**Comment by gkatsev** [comment]
I'm guessing it might have to do with the source being loaded over HTTP while the page itself was loaded over FILE. However, are there any errors in the console? Have you tried loading the page with a local webserver? In addition, what browser and videojs versions are you using?

Thanks.

**Comment by gkatsev** [comment]
Closing because there wasn't any response. We can re-open if it's still an issue.
