### ISSUE TITLE
Where is 4.x stable?

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#2660]
I was hoping 4.12.x would stay available somewhere but it seems the `stable` branch synced to v5 as well, and I can't find any 4.latest tags..

**Comment by mmcc** [comment]
Here's the last 4.x tag, [4.12.15](https://github.com/videojs/video.js/tree/v4.12.15).

**Comment by thijstriemstra** [comment]
I'll make a pull request to clarify this in the readme.

**Comment by gkatsev** [comment]
Unfortunately, github won't show any of the 4.x tags in the dropdown. You should be able to see all the tags in the releases page of the repo https://github.com/videojs/video.js/releases or use the URL that @mmcc used as a template for whatever tag you want.

**Comment by mmcc** [comment]
Thanks @thijstriemstra!

**Comment by hartman** [comment]
Perhaps put a link to a 4.x wiki page in the current README ? Then on that wiki page link to releases and the old docs ?
Might prevent too many questions on this front.

**Comment by gkatsev** [comment]
@hartman that sounds like a great idea. Want to put together a PR for that (linking to the 4.12.15 tag, for example)? Or even getting the wiki page ready.

**Comment by thijstriemstra** [comment]
a 4.x stable branch would be nice as well (as well as 4.x.x tags)..

**Comment by mmcc** [comment]
I don't like the idea of keeping old branches around like that. What would a branch provide for you that tags don't?
