### ISSUE TITLE
Player.tech_ nullcheck is flawed

### ISSUE THREAD

**Issue by Majiir** [videojs/video.js#2665]
I'm still getting familiar with this codebase, so I'm not 100% comfortable submitting a PR for this yet.

In `Player.prototype.techCall_` there's a null check which fails to do its job. From the latest master:

https://github.com/videojs/video.js/blob/aab92462531bfde481167909c148e02c950ba856/src/js/player.js#L1138

```javascript
if (this.tech_ && !this.tech_.isReady_) {
  this.tech_.ready(function(){
    this[method](arg);
  }, true);

// Otherwise call method now
} else {
  try {
    this.tech_[method](arg);
  } catch(e) {
    log(e);
    throw e;
  }
}
```

When `this.tech_` is falsey (which I've encountered) execution continues in the else block, which immediately tries to access a property of `this.tech_`. Both blocks will blow up in this case, so I'm not sure what to do. Drop the call entirely? Queue it up somewhere?

**Comment by gkatsev** [comment]
@Majiir @tbasse hey, do you have examples of when you could end up calling `techCall_` with the `tech_` being null? Would want to understand it a bit better before pulling @tbasse's PR #2676.

**Comment by gkatsev** [comment]
@Majiir @tbasse hey, just wanted to ping you again if you had a specific example of when your `techCall_` ends up getting called when `tech_` is null.

**Comment by gkatsev** [comment]
The PR was merged. Thanks.
