### ISSUE TITLE
Specify additional breaking changes for components?

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#2666]
https://github.com/videojs/video.js/wiki/5.0-Change-Details#propertiesmethodsevents-of-the-videojscomponent-class

Looks like many events were changed from `on` to `handle`. Should these be specified or are there too many?

See: https://github.com/videojs/video.js/commit/bb9fde0f82c27d086c9319b976c6253762bc04cb

Also, are there any plugins, to reference, that have been upgrade to 5.0? I am reading source code for examples, though some pieces still seem fishy…

```js
const VjsMenuButton = videojs.getComponent('MenuButton');

class MenuButton extends VjsMenuButton {
  constructor(player, options = {}) {
    // sometimes you need to modify options, but don't have access to `this` (e.g. `MenuItem`)

    super(player, options);

    // for when buildCSSClass isn't available
    this.addClass('Que?');

    // sometimes you need to modify things on `this.el_`
    this.el_.setAttribute('aria-label', 'Que?');
  },

  // only works on some components
  buildCSSClass() {
    return `${super.buildCSSClass()}`;
  }
}

// Kinda hidden
MenuButton.prototype.controlText_ = 'Que?';
```

**Comment by gkatsev** [comment]
We can probably mention that it was changed but I don't think these functions were really part of the public API in v4, so, it isn't really a breaking change in that respect.

contrib-hls and a bunch of the brightcove videojs plugins have working branches with changes to support 5.0. For example: https://github.com/brightcove/videojs-errors/pull/28 and https://github.com/brightcove/videojs-playlist/pull/10. https://github.com/brightcove/videojs-dock, for example, targets v5 initially.

**Comment by chemoish** [comment]
Ya. I am working on getting my plugins updated, then I will try and help make sure dash and others get upgraded as well.

I guess I was looking for more welly defined/consistent documentation/interface. Doesn't seem *quite* as easy for someone to jump in and contribute (Such is life—Perhaps small plugin/component tutorials would help).

**sparse documentation**

http://docs.videojs.com/docs/guides/components.html
https://github.com/videojs/video.js/wiki/5.0-Change-Details#videojs-50-subclassing-examples

**inconsistent interface**

http://docs.videojs.com/docs/api/menu-item.html (e.g. Doesn't interact with `buildCSSClass`)

---

Thanks for the examples though, I will keep plugging away.

P.S. All doc definitions, under nested folders, are broken.
- http://docs.videojs.com/docs/api/menu-item.html#createElHeader
- http://docs.videojs.com/docs/api/captions-button.html#buildCSSClassHeader
