### ISSUE TITLE
Incorrect link for Player API Docs

### ISSUE THREAD

**Issue by tucq88** [videojs/video.js#2667]
When I was reading Videojs API on [this page](http://docs.videojs.com/docs/guides/api.html#toc_3)
I have clicked on the link to Player API docs, but it showed me an [404 page](http://docs.videojs.com/docs/api/vjs.Player.md)
Then I checked the master branch and could not found the `vjs.Player.md` file. I think it's missing.

**Comment by mister-ben** [comment]
Thanks, I've created a PR for this in the [videojs/docs](https://github.com/videojs/docs) repo videojs/docs/pull/4

The correct link is http://docs.videojs.com/docs/api/player.html
