### ISSUE TITLE
video.js 5.0.0 does NOT work with videojs-contrib-dash 1.1.0 and dash.js 1.5.0

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#2670]
video.js 5.0.0 does NOT work with videojs-contrib-dash 1.1.0 and dash.js 1.5.0.

Any update on when this might be fixed please.

Thanks

Richard

**Comment by chemoish** [comment]
Maybe close in favor of the other one you have open?

**Comment by gkatsev** [comment]
Closing as a dupe of https://github.com/videojs/videojs-contrib-dash/issues/23
