### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by campones** [videojs/video.js#2671]
Hello,
Could it possible to change the "src not found" with a more explicit message. indeed, a high number of people don't know what means src.. and therefore don't understand the meaning of it

like.. video source not found. 
No video source is available. .etc.. 

thx

**Comment by Tralapo** [comment]
Check plugins https://github.com/brightcove/videojs-errors

**Comment by mmcc** [comment]
Thanks for the suggestion @Tralapo!
