### ISSUE TITLE
can't reorder components in 5.0

### ISSUE THREAD

**Issue by lupos** [videojs/video.js#2673]
this https://github.com/videojs/video.js/issues/1070 no longer seems to work in the newest version. I've attempted to do it in a variety of ways and it always ends up breaking the player. Is this still supported and if so what is the correct usage?

**Comment by heff** [comment]
The child lists have changed to arrays to make reordering consistent between browsers.

```
videojs.getComponent('ControlBar').prototype.options_ = {
      loadEvent: 'play',
      children: {
        'playToggle': {},
        'muteToggle': {},
        'volumeControl': {},
        'fullscreenToggle': {}
      }
}
```

**Comment by heff** [comment]
Forgot to change the example. :) It's updated now.

**Comment by lupos** [comment]
thanks for the quick reply. perhaps I'm a little thick or just tired but could you possibly give me and example options:{} that changes the order of the control bar? whenever I try and pass it in I end up not having a bigPlayButton because I don't specifically define that.

**Comment by lupos** [comment]
nm! sorted it out finally. Not sure what I was doing wrong before but I finally got the right combo. Thanks for your help.

**Comment by tneaves** [comment]
@heff where is the example you are describing? I am having trouble getting this to work.

**Comment by heff** [comment]
The example is just the code example above. If you're having issues with it, could you share a jsbin example of what you're doing?

**Comment by tneaves** [comment]
@heff Figured it out. The only way I could get it to work was by supplying object-styled members to the array: 
children: [
		        {name:'fullscreenToggle'},
		        {name:'playToggle'},
		        {name:'volumeControl'},
		        {name:'muteToggle'}
		      ]

**Comment by heff** [comment]
Interesting. That seems like a bug.

**Comment by tneaves** [comment]
It seems like this issue isn't resolved. Certain members won't display, either, like `CurrentTimeDisplay` or `DurationDisplay`

**Comment by mmcc** [comment]
`currentTimeDisplay` and `durationDisplay` are already in the dom, just hidden via CSS. Just change those to `display: block`. [Example](http://jsbin.com/bayegugidi/edit?html,css,output)

**Comment by weituotian** [comment]
@mmcc does it work?
```
        controlBar: {
            volumePanel: {inline: false},
            // fullscreenToggle: false,
            children: [
                "playToggle",
                "progressControl",
                "volumeMenuButton",
                "currentTimeDisplay",
                "timeDivider",
                "durationDisplay",
            ]
        }
```

**Comment by mmcc** [comment]
@weituotian I'm not sure which part you're asking about, but yes, [confirmed that reordering components this way does work in VJS 7+](https://codesandbox.io/s/o996xzy0k9).

**Comment by bozhouyongqi** [comment]
as described above, we could set the order of the control bars, but,if you would set the order of currentTimeDisplay and durationDisplay,you could set the css style also,because the display attribute of them were set to none default.
