### ISSUE TITLE
"ended" triggers an increasing number of times 

### ISSUE THREAD

**Issue by basiclaser** [videojs/video.js#2674]
I have a 'tv app' which plays videos one after another. I use the "ended" state to load the next video. However, every time this block of code fires, it doubles its number of requests: 

    tv.on("ended", function(){
    requestPlayheader(); 
    console.log("request");
    }),false);

1,2,4,8,16 ... until about 200 when the browser slows down and stops functioning.

I tried manually using the requestPlayheader() function, and alone it does not cause a doubling of requests, it works as expected. Are you aware of any issues which cause this build up of requests? 

I love this project, and I really appreciate your support!

here's the majority of the player code, including the AJAX request: 

```
var loadedmetadata = false;
if (window.addEventListener) {
    window.addEventListener('loadedmetadata', function(ev) {
            loadedmetadata = true;
    }, true);
}

document.createElement('video');
document.createElement('audio');
document.createElement('track');

tv = videojs(
    "tvcontainer",
    {
      "preload": "auto",
      "autoplay": true,
      "controls": false,
      "poster": "http://cdn.gifbay.com/2013/02/look_at_all_the_snow-32007.gif"
    }
  );

function requestPlayheader(){
var request = new XMLHttpRequest();
request.open('GET', '/json' + location.hash , true);
request.onload = function() {
  if (request.status >= 200 && request.status < 400) {
  	playChannel(JSON.parse(request.responseText));
  } else {
    // We reached our target server, but it returned an error
   console.log("error from server")
  }
};
request.onerror = function() {
   console.log("error with the request");
};
request.send();
};
var playChannel = function(resp){
	var title = resp[0];
	var URL = resp[1];
	var playheader = resp[2];

  tv.src(URL);

  window.addEventListener('loadedmetadata', function(ev) {
    tv.currentTime(playheader);
  }, true);

  tv.on("ended", function(){
    requestPlayheader();
    console.log("request")
  },false);

}

requestPlayheader();
```

**Comment by mister-ben** [comment]
You're adding an extra event listener each time you loop through. On the first run an event listener is added. When the video ends, it calls `requestPlayerheader()` which in turn calls `playChannel()` which adds another listener. When the next video ends, both are triggered and each adds another listener. 

Two options:
* Use `player.one()` instead. This adds an event listener that is only executed once.
* Add the event listener outside of the functions, e.g. immediately after the player is initialised.
