### ISSUE TITLE
infinite loop for unprefixed use.

### ISSUE THREAD

**Issue by jdalton** [videojs/video.js#2675]
I noticed in [src/js/player.js](https://github.com/videojs/video.js/blob/v5.0.0-rc.104/src/js/player.js#L1530-L1539) that if `fsApi.fullscreenchange` is unprefixed, so `fullscreenchange`, then it will [trigger](https://github.com/videojs/video.js/blob/v5.0.0-rc.104/src/js/player.js#L1538) an infinite loop.

```js
Events.on(document, fsApi.fullscreenchange, Fn.bind(this, function documentFullscreenChange(e){
  this.isFullscreen(document[fsApi.fullscreenElement]);

  // If cancelling fullscreen, remove event listener.
  if (this.isFullscreen() === false) {
    Events.off(document, fsApi.fullscreenchange, documentFullscreenChange);
  }
  this.trigger('fullscreenchange'); // <-- ohh noo
}));
```

**Comment by heff** [comment]
Thanks for the report! The listener is on the document but the context of the `documentFullscreenChange` function should be the player, so I'm not totally following how this is causing the loop yet, unless the event is bubbling up to the document from the player. Looking into it more.

**Comment by jdalton** [comment]
Actually [this](https://github.com/videojs/video.js/issues/2640) is the issue. Do you have any info on the commit that resolved?

**Comment by heff** [comment]
Ah, yeah. 
https://github.com/videojs/video.js/pull/2351
https://github.com/videojs/video.js/commit/07f0483780d4d3ca854c3e083a018eaa4663e466

So if you're using 5.0 (not an RC) I would expect this to be fixed.

**Comment by jdalton** [comment]
Rock! Is it tricky to induce bubbling? (curious if you're using a real event or fake one <kind of like jq>)

**Comment by heff** [comment]
Mostly [fake events](https://github.com/videojs/video.js/blob/aab92462531bfde481167909c148e02c950ba856/src/js/utils/events.js#L210) that are copied from real ones . Built off the JSNinja example years ago and improved along the way.

You can [set `event.bubbles = true`](https://github.com/videojs/video.js/blob/aab92462531bfde481167909c148e02c950ba856/src/js/utils/events.js#L164) and it will bubble up. That should work with native events that bubble automatically, though I'm starting to see some weird behavior with keyboard events.

**Comment by riking** [comment]
There are still pages in the wild hitting this bug, as per webcompat/web-bugs#2498 , such as mentioned in [this comment](https://github.com/webcompat/web-bugs/issues/2498#issuecomment-418402878). Would you consider releasing a hot-fix for the old versions on your CDN or working with the affected sites to update the library?
