### ISSUE TITLE
Spinner appears even after the video was loaded and is being played from beginning

### ISSUE THREAD

**Issue by lonormaly** [videojs/video.js#2677]
Hey there,

The video is set to autoplay and loop. The start is ok. Wheel spinning video loading. But after the first playback the spinner comes up again. Any solution for this?

(duplicate of this Stackoverflow issue but this wasn't resolved and it is a bug: http://stackoverflow.com/questions/13789097/video-js-spinner-not-dissapearing-in-ie)

**Comment by mmcc** [comment]
For anyone curious, here's an [example](http://jsbin.com/jiqamoluda/edit?html,output).

I don't think this is a bug that requires resolving on our end. The player ends and a loading event is fired on the loop start, so we show the spinner. If that's something you don't ever want, I would simply permanently hide the spinner after the initial play.

```css
.vjs-has-started .vjs-loading-spinner {
  display: none !important;
}
```

**Comment by mister-ben** [comment]
I haven't exhaustively tested this, but it looks like the looping state can be detected by checking `currentTime()` on `seeking` and `playing` events. Add a class and the spinner can still be shown if there's buffering at other times.

```javascript
player.on('seeking', function(e) {
  if(player.currentTime() === 0) {
    player.addClass('vjs-looping');
  }
})
player.on('playing', function(e) {
  if(player.currentTime() === 0) {
    player.removeClass('vjs-looping');
  }
})
```

```css
.vjs-looping .vjs-loading-spinner {
  display: none;
}
```

[Example](http://jsbin.com/wexaqo/edit?html,output)

**Comment by Themis68** [comment]
Hello folks

I had the same trouble.
After reading your posts I found this solution with success 

- CCS
.vjs-looping .vjs-loading-spinner {
  display: none;
}

- index.html
<video id="myVideo" class="video-js vjs-looping">

**Comment by lahbib** [comment]
Hello,

i have the some trouble with FireFox.

The simplest solution is in CSS:

`.vjs-ended .vjs-loading-spinner {
    display: none;
}`
