### ISSUE TITLE
the API doc doesnt list all the important events

### ISSUE THREAD

**Issue by lilchow** [videojs/video.js#2681]
Maybe I went to the wrong place but the link below doesn't event have end or play or pause event listed. What was the reasoning behind this decision?

http://docs.videojs.com/docs/api/player.html

**Comment by chemoish** [comment]
Not sure if purpose or accident. Best to just look at the source (There is a ton of native events).

https://github.com/videojs/video.js/blob/master/src/js/player.js#L536

Most methods are missing http://usejsdoc.org/tags-event.html

**Comment by gkatsev** [comment]
Basically, all the events are HTML5 events: http://www.w3.org/TR/html5/embedded-content-0.html#mediaevents

We probably should do a better job of documenting it.

**Comment by Soviut** [comment]
I might be able to take a crack at documenting these. I'll have to research how to integrate them into the current list of events but I think I have enough.

**Comment by gkatsev** [comment]
Related: https://github.com/videojs/video.js/issues/2101

**Comment by StaymanHou** [comment]
Any update on this? Recently upgraded from v4 to v5. Looks like quite a few documentations that were available for v4 are no longer there in v5

**Comment by gkatsev** [comment]
We're still working on it. Some of the events are available here: http://docs.videojs.com/docs/api/player.html#events
As I mentioned above, all the [html5 events](http://www.w3.org/TR/html5/embedded-content-0.html#mediaevents) are available.

Video.js doesn't have many custom events it triggers.

**Comment by xurizaemon** [comment]
link above is 404 now, new URL is https://www.w3.org/TR/2014/REC-html5-20141028/embedded-content-0.html#mediaevents ?

**Comment by micronax** [comment]
New link: https://www.w3.org/TR/html5/semantics-embedded-content.html#media-elements-event-summary
