### ISSUE TITLE
5.0: consider exposing some dom.js methods

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2683]
We are currently using some methods from `dom.js` in our project.
We can not directly `import` that file from outside of the video.js package, as it seems this is not allowed by browserify / babelify.

This means we now have a copy of some of these functions, which is a shame.

It would be better if either these functions are exposed separately or if the whole `dom` file is exposed.

We currently use these methods:

* `createEl`
* `hasElClass`
* `addElClass`
* `removeElClass`

Is this something that you would consider changing?

**Comment by nickygerritsen** [comment]
Btw I could create a PR for this :).

Furthermore: we need a check on IE9 in our code (because the IMA SDK does not work in IE9). Could such a check be added to `browser.js`? I could also PR that.

**Comment by nickygerritsen** [comment]
Any thoughts on this?

**Comment by gkatsev** [comment]
I don't think we're against exposing those if they're useful to users.
The question is whether we should expose all the dom functions under `videojs.dom` or directly on the `videojs` object. I'm leaning towards the `videojs` object because the methods have rather unique names and in previous discussions we wanted to do that so we don't just become a utility library.

**Comment by nickygerritsen** [comment]
So should I then create a PR with the four specifc methods?

And what about the IE9 check?

**Comment by gkatsev** [comment]
I think we've previously been reluctant to add user agent checks that videojs itself doesn't use.

**Comment by nickygerritsen** [comment]
Ok if al good I'll then create a PR with the four mentioned methods, ok?

**Comment by gkatsev** [comment]
That would be awesome. Thanks!

**Comment by gkatsev** [comment]
#2754 has been merged which should address this.
