### ISSUE TITLE
multiline control-bar

### ISSUE THREAD

**Issue by amitport** [videojs/video.js#2687]
Is there any way to create 2-line (or more) control-bar? This is very useful for cases where you have many buttons.

I managed to increase the controlbar size using `.vjs-default-skin .vjs-control-bar {height: 6em;}` but when adding extra buttons the line never wraps, and some elements, like to scrub-line are being vertically aligned to center.

**Comment by amitport** [comment]
I think I found a solution, please correct me if there's some better way:

I just add another toolbar when the player is ready. I give it a style class that positions it at the bottom (`bottom-bar: {bottom: 0 !important;`)
```
player.ready(function() {
            var ControlBar = videojs.getComponent('ControlBar');
            var controlBar = new ControlBar(player, {
                /* some controlBar options */
            });
            controlBar.el().classList.add('bottom-bar');
            player.addChild(controlBar);
        });
```

**Comment by mmcc** [comment]
I would highly suggest not adding another toolbar...just use CSS to reposition things as multiline. Here's an [example skin](http://blog.htbx.net/videojs-skin-twitchy/) that repositions the progress bar to the top of the control bar.

It will require a good bit of CSS to do right, but imo that's still preferable to creating a duplicate toolbar like this.
