### ISSUE TITLE
v5 migration guide

### ISSUE THREAD

**Issue by muratakbal** [videojs/video.js#2693]
Hi guys,

As far as I understand from https://github.com/videojs/video.js/wiki/5.0-Change-Details, you were planning to post a migration guide. Is that still on your roadmap and do you have ETA for that?

Thanks

**Comment by gkatsev** [comment]
That page more or less has all the information that one would need to upgrade to 5.0 from 4.x. Though, we probably should write a more accessible migration guide like the post that was linked on that page.
