### ISSUE TITLE
Seeked not work in flash player

### ISSUE THREAD

**Issue by sufyandeveloper** [videojs/video.js#2694]
When i move forward seek bar. seeking is not working the pointer of seek move forward but video is forward only 2 to 3 sec i have no idea what's going on please help me to solve this problem.

And when my player has mp4 source seeking is working well but on flv source seeking is not working

**Comment by gkatsev** [comment]
Flash can only seek to keyframes in an mp4, so, if your mp4 has keyframes that are spaced far apart, you'll only be able to seek to only some parts of the video.
If you are using standard options for videojs, then an mp4 will end up playing in html5 which can seek whereever.
Do you have a working example somewhere? Though, it's probably best to get away from flvs nowdays :)

**Comment by mmcc** [comment]
Closing this since it doesn't seem like an issue, but we can reopen if you want to put together an example.
