### ISSUE TITLE
Feature Request: Meteor Package

### ISSUE THREAD

**Issue by boustanihani** [videojs/video.js#2695]
Please provide an official package for **Meteor.js** on https://atmospherejs.com/

**Comment by mmcc** [comment]
We already spend way too much time keeping various package managers up to date, and this doesn't seem as trivial as just bumping a version number in a manifest file. I don't think this is something the core VJS team has the bandwidth to ensure it stays up to date, so I think it's best if we avoid it. Is there a reason you can't use the [npm package](https://github.com/meteorhacks/npm) with Meteor?

**Comment by boustanihani** [comment]
There is a project for automating the publishing-process whenever a version number is bumped. I never tried it but maybe you would like to take a look: https://autopublish.meteor.com/howitworks

**Comment by chrisbutler** [comment]
@mmcc it actually would likely be as trivial as you describe. i could create and test a PR for this?
