### ISSUE TITLE
TypeError: fn.apply is not a function (video.novtt.dev.js, line 885)

### ISSUE THREAD

**Issue by DaveVoyles** [videojs/video.js#2696]
**Update:** It seems the issue was that I was not wrapping my function within a function as a callback. 

This works:

```
  video.on('loadeddata', function() {
            console.log('data is loaded');
        });
```

This does not:

```
  video.on('loadeddata', 
            console.log('data is loaded');
      );
```

In hindsight, if there was a message warning me that I needed to wrap the function within a function, that would have been more helpful.

-------

I receive this when running video.js in my app, which can be found here:
https://github.com/DaveVoyles/Night-Trap/tree/alpha

I'm not sure of why this is happening, but it is coming from video.novtt.dev.js, line 885.  This also happens with *video.js* on line 14, but reads *'TypeError: c.apply is not a function'*

It only appears when I am attempting to apply an event handler to the videojs player. 

ex:

```
    video.on('canplay', handler); // returns TypeError: fn.apply is not a function
```
[Imgur](http://i.imgur.com/blS6X7P.png)

**Comment by gkatsev** [comment]
Sounds like this has been solved. Closing.
