### ISSUE TITLE
Vjs 4, how to tell when player is buffering?

### ISSUE THREAD

**Issue by shaharmor** [videojs/video.js#2697]
Hi,

I'm to figure out how to be notified from JS when the player is buffering.

The video itself stops playing while the video is downloaded, but no event is being triggered (Unless i'm missing something).

Any help will be greatly appreciated.
Thanks

**Comment by shaharmor** [comment]
I'm talking specifically about buffering while mid-play, not during startup

**Comment by shaharmor** [comment]
Never mind, i found out there is a `waiting` event, its just not documented anywhere

**Comment by gkatsev** [comment]
While we do need to do a better job of documenting events, most of our events come from the html5 spec. Glad you figured it out.
