### ISSUE TITLE
vtt.js version number in package.json

### ISSUE THREAD

**Issue by yatinrandive-lynda** [videojs/video.js#2704]
Is it possible to update 'vtt.js' dependency to just version number in package.json?

**Comment by gkatsev** [comment]
No, we're using a custom build of vttjs right now still. Though, I've been considering also just publishing the custom fork to npm so it's easier to use.
Are you having any issues with the git dependency?

**Comment by yatinrandive-lynda** [comment]
Yes we have an automated build system which is freaking out and failing due to this dependency.

**Comment by gkatsev** [comment]
I could possibly publish vttjs to scoped package under my name.

**Comment by gkatsev** [comment]
Fixed by https://github.com/videojs/video.js/pull/2905
