### ISSUE TITLE
Add ability to determine which tech would be chosen based on source type

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2705]
As discussed in #2701 it would make sense for us if we could have some function to determine which tech would be chosen based on source type(s).

The scenario we want to solve is the following:

We have a platform that can automatically expose progressive video, together with HLS and MPEG-DASH (among others). For progressive we have multiple files for the different qualities and the adaptive formats support this out of the box of course.

We have created some plugins already which support the progressive flow by rendering a menu to switch between qualities and some logic to choose a default quality.

However we of course want to add support for the adaptive types in our plugins. But we would really like to prefer HTML5 over Flash, so if an HLS stream can only be played using Flash (because the browser lacks MSE support), we would rather use the progressive files.

If an adaptive stream is used, we of course do not want to render the quality switching menu.
For this I think it makes sense if we somehow can determine which tech would play some video type.

If this gets added, our flow would be something like:

As soon as a new item gets loaded (an item for us is a video-item which contains all adaptive and progressive URL's):
* Check which tech can play the HLS stream. If the first tech can play it, use HLS
* If not, check which tech can play the MPEG-DASH stream. If the first tech can play it, use MPEG-DASH
* If not, use progressive qualities

The current way `selectSource` works is exactly like this flow, but we rather not pass all streams at the same time to `player.src()`, because in that case we would have to trigger and listen for some events to determine whether an adaptive stream is used.

So what is the best way to do something like this?
A suggestion would be to add a function (`whichTechSupportsType` as @gkatsev suggested?) which will return something to denote which tech supports a given type. However, if we return the name of the tech (i.e. `html5`) this is maybe not ideal, because there is no public way of finding out which tech order the player uses, right? So maybe it is better to return an integer that denotes the 0-indexed tech order number that will play the type?

@gkatsev mentioned in #2701:
> However, this is actually slightly different than how the native source selection works (and we should have an issue about it somewhere but I cannot find it). 

And I'm not sure what he means by this and what is different? Does this influence this issue?

**Comment by nickygerritsen** [comment]
Now that #2709 has been merged, I of course would like this to be implemented and can provide a PR if desired.

But we first need to decide on how to do this. After some thinking I think the most logical approach would be:
* Create a function `player.techOrder` which just returns `this.options_.techOrder`. Although tech's themselves should be private, I think the techOrder is public. You provide it as a player-option anyway.
* Add `whichTechSupportsType(type)` which just loops over the techs in order and returns the name of the first tech `t` where `t.isSupported() && t.canPlayType(type)`

I think this is an easy enough approach for such a function and doesn't over-complicate things.

But maybe others have a different opinion?

**Comment by nickygerritsen** [comment]
@gkatsev or someone else: already an opinion about this? Now that we also have source first ordering as an option we should think about this I guess

**Comment by gkatsev** [comment]
Yep, haven't forgotten about this. Just haven't had time to think about it.

**Comment by nickygerritsen** [comment]
No problem :)

**Comment by nickygerritsen** [comment]
@gkatsev While trying to see if I could implement this, I came acrooss `selectSource`. It seems this also returns the techName for that source.

Is this public API? Because if so, it seems we can use that function and we do not need a whichTechSupportsType anymore really (as long as we have a whole source and not only a type).

For me even exposing the `techOrder` is not really needed, but this might be nice adition?

**Comment by gkatsev** [comment]
Seems like it is a public API: https://github.com/videojs/video.js/blob/master/src/js/player.js#L1719-L1728 and http://docs.videojs.com/docs/api/player.html#MethodsselectSource

**Comment by gkatsev** [comment]
If you think that's sufficient, feel free to close this issue.

**Comment by nickygerritsen** [comment]
I'll try to use it and get back to here whether its enough :)

**Comment by gkatsev** [comment]
@nickygerritsen cool. Please report your finding either way.

**Comment by nickygerritsen** [comment]
It seems that `selectSource` is enough for me :).

What I now do is:
* Pass all adaptive sources to `selectSource`
* Check if it returns anything and if the tech is `Html5`
* If so, use the returned adaptive source, otherwise use progressive

So for me this issue can now be closed :)
