### ISSUE TITLE
playing audio never shows the video.js skin - just shows native player

### ISSUE THREAD

**Issue by lomok** [videojs/video.js#2712]
No matter what I do, I get the standard html 5 player skin-
I am embedding like this(had to modify code below  to make it show up):
html = "";
 html +=    audio id=audio_example controls=controls crossorigin=anonymous" class=video-js vjs-default-skin  data-setup{} ><source src=https: + gVideoURL + apiKey + /></video;
    $('#display-video').html(html);

I also tried it at your page showing responsive design with the hard-coded url- it also just showed the standard player.

**Comment by mister-ben** [comment]
You'll need to instantiate the player with `videojs('audio_example')` after adding to the DOM. Automatic setup of players only works when the video or audio element is present with a `data-setup` attribute when the script loads.

**Comment by lomok** [comment]
Hi- thanks!

One problem I am seeing with the new player ui is that the volume controls run under the main scrubber.
Is there a way to make the volume controls go vertical? And can one display total time/ time elapsed?
And, is there a page with all these apis available ? I am unable to find this information.

Thanks again.
