### ISSUE TITLE
build crashes on sass task, libsass bindings not found

### ISSUE THREAD

**Issue by Soviut** [videojs/video.js#2713]
NodeJS 4.2.1
npm 3.3.2
This is happening on both Windows 10 and Ubuntu.

```bash
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by gkatsev** [comment]
This is because the version of our sass didn't have node 4.x binaries yet. I just merged in a PR that updates that and should fix it. See #2643.
