### ISSUE TITLE
Re-load the video when using videojs-contrib-dash on ended event

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#2717]
Is it possible to re-load the video when using videojs-contrib-dash on ended event?

We previously used to listen to the ended event and used video.load() to re-load the video and re-display the poster image ready for a possible replay by the user.

I tried adding the .load() method to the videojs player when using videojs-contrib-dash, but it doesn't work, e.g. myPlayer.load()

Is there a way to re-load the video when using contrib?

Anyone got this to work, or know how to do it please?

**Comment by gkatsev** [comment]
This probably needs to be supported by contrib-dash, not certain.
