### ISSUE TITLE
Video-js 5.x questions

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2725]
Hi, I have some questions

1. I would like to update video js to 5.x, but I can't find any packages already made for self-hosting. 
2. There is a way for change the -0:00 and put the duration of the video?
3. The videojs hotkeys plugins will work with this new version?
4. Is it responsive?

Thank you

**Comment by chemoish** [comment]
Not really sure what you mean by 1) and 2).

3) Works, no breaking changes.
4) `.vjs-fluid`

**Comment by mmcc** [comment]
1) [Releases](https://github.com/videojs/video.js/releases)
2) Duration is available in the DOM, it's just hidden.

```
.video-js .vjs-duration, .vjs-no-flex .vjs-duration {
  display: block;
}
```
