### ISSUE TITLE
Components do not localize aria-label text

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#2728]
Several components of the UI have ARIA markup to improve compatibility of the player with assistive technologies such as screen readers. Some components use aria-label to add hidden text which is announced by the screen reader; unlike other component labeling, this text is not localized, so it may not be useful for screen reader users in non-English speaking locales.

All aria-labels in the source can be found with [this search](https://github.com/videojs/video.js/search?q=aria-label).

Examples include:
'volume level' in [volume-bar.js](https://github.com/videojs/video.js/blob/e58c2266de3325c30412c2dcd1ce8096d980b63e/src/js/control-bar/volume-control/volume-bar.js#L37)
'video progress bar' in [seek-bar.js](https://github.com/videojs/video.js/blob/e58c2266de3325c30412c2dcd1ce8096d980b63e/src/js/control-bar/progress-control/seek-bar.js#L38)

**Comment by nickygerritsen** [comment]
I'm not sure if the `controlText_` of controls is related to this? This does appear in the HTML but is hidden. However, these aren't translated either.

**Comment by OwenEdwards** [comment]
For buttons and everything which extends a button, I believe the `controlText_` is localized into the HTML element:

https://github.com/videojs/video.js/blob/master/src/js/button.js#L77

So the design pattern seems to be to localize at the point where video.js 'translates' into HTML, but keep as native within the JavaScript object (including the `controlText_`). This 'translation' step isn't present for aria-label content. @nickygerritsen, do you have an example of the hidden `controlText_` not being translated?

**Comment by nickygerritsen** [comment]
I'll check this ASAP :)
