### ISSUE TITLE
Volume slider doesn't reflect player.volume()

### ISSUE THREAD

**Issue by Soviut** [videojs/video.js#2737]
When I use the following code to reduce the player volume, the volume slider is still set at 100% when I hover over it.

```javascript
    var player = videojs('video');
    player.volume(0.1);
```

**Comment by nickygerritsen** [comment]
If you `player.trigger('volumechange');` afterwards, it will update the volume correctly I think

**Comment by Soviut** [comment]
I guess I can make a PR that triggers the `volumechange` event from the `.volume()` method.

**Comment by nickygerritsen** [comment]
I'm not entirely sure if that will be desired behavior, probably someone from video.js can eloborate :)

**Comment by gkatsev** [comment]
I'm not seeing this issue on videojs.com, is it still an issue with latest videojs?

**Comment by Soviut** [comment]
It seems to be working with 5.0.2 on the custom skin I'm building.
