### ISSUE TITLE
The CDN is broken

### ISSUE THREAD

**Issue by kenmazaika** [videojs/video.js#2738]
In the documentation there is a link to this CSS file to access the content over a CDN.  It gives an AWS Access Denied error.

http://vjs.zencdn.net/5.0.2/video-js.css

Is there someplace else I can get the CSS file?

**Comment by gkatsev** [comment]
The CDN does not currently have 5.0.2 released. I'll be releasing it today. Meanwhile, use the 5.0.0 CDN.
Thanks.

**Comment by gkatsev** [comment]
That URL should now be available.
