### ISSUE TITLE
bower.json - The files listed under the main key are wrong

### ISSUE THREAD

**Issue by mpetkov** [videojs/video.js#2740]
I tried installing the component using the Main Bower gulp plugin in my project.  This plugin is supposed to copy only the files listed in the main key that are the only files needed to run the module.  Well right now the listed files are the ones in src however it should have a list of the dist files.

**Comment by DatTran** [comment]
Also bower pulls in the SASS file instead of the css.

```javascript
"main": [
    "src/js/video.js",
    "src/css/video-js.scss"
  ],
```
Should be:

```javascript
"main": [
    "dist/video-js.js",
    "dist/video-js.css"
  ],
```

**Comment by mmcc** [comment]
@DatTran want to submit a PR to fix it?

**Comment by misteroneill** [comment]
This one is also related to #2611

**Comment by gkatsev** [comment]
The PR for this: https://github.com/videojs/video.js/pull/2775
