### ISSUE TITLE
how to update plugins index page?

### ISSUE THREAD

**Issue by petermekhaeil** [videojs/video.js#2745]
How can we update the plugins index page at http://videojs.com/plugins/?

Having a quick look, it looks like it's picking up NPM modules with keywords "videojs-plugin" and "videojs-skin". If that is so, how frequent does this registry update on your end?

Cheers,
Peter

**Comment by mmcc** [comment]
Just updated again, but it will update daily from here on out as of yesterday.

Cheers!
