### ISSUE TITLE
Minified vs unminified differences?

### ISSUE THREAD

**Issue by gabrieli** [videojs/video.js#2747]
I'm using the videojs-contrib-ads library and I see different behaviours when using videojs minified/unminified. 

Specifically, when the videojs-contrib-ads is in ad mode, the normal videojs events should be stopped (https://github.com/videojs/videojs-contrib-ads/blob/master/src/videojs.ads.js#L394) and only 'ad' prepended events should be triggered. 

For example, when an ad ends, the expected behaviour is to get 'adended' while the actual behaviour when using the cdn version of videojs (http://vjs.zencdn.net/4.12.14/video.js) is to get both 'adended' and 'ended'. With the dev version, built locally, the events work as expected. 

I've filed a ticket in the videojs-contrib-ads repo, specific to this difference, but I'm thinking something in the built process might be off

**Comment by gkatsev** [comment]
videojs 4.x uses google's closure compiler with advanced compilation which heavily mangles and modified the code. It's probably best to just use the unminified version of videojs and minify it yourself with contrib-ads. We're unlikely to do an update for 4.x anymore unless it's security fix or something major that needs to get fixed.
Going to close it but if you have thoughts or comments, feel free to reply.
