### ISSUE TITLE
How to transfer a player from one block to another without destroying it?

### ISSUE THREAD

**Issue by ange007** [videojs/video.js#2752]
How to transfer a player from one block to another without destroying it?
In particular it concerns player Flash.

I ask it because in case of hide/change of the unit there is an error:
`Error message: Uncaught TypeError: this.el_.vjs_getProperty is not a function
Line: 11960`
![_007](https://cloud.githubusercontent.com/assets/2736539/10784109/dc4a3170-7d64-11e5-84bd-0d520b183f49.png)

How to pause buffering, or at least timers native means?

**Comment by gkatsev** [comment]
You probably should dispose the player completely and then re-create it in another block. Flash definitely doesn't like moving elements or anything happening to it once it starts running.
If you're not using flash, you may be able to just get the player div and moving it to another element and it may work.

**Comment by gkatsev** [comment]
Closing. I'm not sure we can really do anything with regards to flash but it's better to dispose and recreate the player rather than trying to move it in the DOM.
