### ISSUE TITLE
videojs & vast & play real-time playback with RTMP

### ISSUE THREAD

**Issue by aionlj** [videojs/video.js#2757]
Hello everyone
I'm playing real time after the ad is over.
After the end of the ads can play MP4 RTMP video, but can not play real-time playback.
Do not know why the removal of advertising can play real-time playback, but the insertion of advertising can not do it?
Below is the code I wrote:

<p class="description">Video.js VAST plugin examples.</p>

  <div class="example-video-container">
    <p class="description">No autoplay.</p>

    <video id="vid1" class="video-js vjs-default-skin"  controls preload="auto"
        poster="http://video-js.zencoder.com/oceans-clip.png"
        data-setup='{}'
        width='640'
        height='400'
        >
      <source src="rtmp://192.168.137.190:1935/live/main" type='rtmp/mp4'> 

      <p>Video Playback Not Supported</p>
    </video>
  </div>

  <div class="example-video-container">
    <p class="description">With autoplay.</p>

    <video id="vid2" class="video-js vjs-default-skin"  controls preload="auto"
        poster="http://video-js.zencoder.com/oceans-clip.png"
        data-setup='{}'
        width='640'
        height='400'
        >
      <source src="rtmp://192.168.137.190:1935/vod/mp4:sample.mp4" type='rtmp/flv'> 
      <p>Video Playback Not Supported</p>
    </video>
  </div>

  <script>
    var vid1 = videojs('vid1'),
        vid2 = videojs('vid2');

    vid1.muted(true);
    vid1.ads();
    vid1.vast({
      url: 'spec/270.xml'    //'http://videoads.theonion.com/vast/270.xml'
    });

    vid2.muted(true);
    vid2.ads();
    vid2.vast({
      url: 'http://videoads.theonion.com/vast/270.xml'
    });
  </script>

**Comment by mmcc** [comment]
Hi there, this feels like it belongs more with the vast-plugin than core. Have you opened an issue on the plugin tracker?
