### ISSUE TITLE
Page Missing - 404

### ISSUE THREAD

**Issue by iamVP7** [videojs/video.js#2759]
visited this below page
https://github.com/videojs/video.js/blob/stable/docs/guides/api.md

In the below line  we  have hyperlink for the world 'player API docs'
"The full list of player API methods and events can be found in the player API docs."

When we click on that we are getting 404
https://github.com/videojs/video.js/blob/stable/docs/api/vjs.Player.md

Please change the link.

**Comment by gkatsev** [comment]
Looks like we need to update the link to the new API docs. http://docs.videojs.com/docs/api/player.html
Will you be able to provide a PR to fix this? Thanks!

**Comment by sprice** [comment]
Looks like this was fixed with 5f5357d535e7d58faddc7e04098c68b64a21829c

**Comment by gkatsev** [comment]
Yeah, calling this one fixed.
