### ISSUE TITLE
switch player from cdn url to local computer

### ISSUE THREAD

**Issue by apixon** [videojs/video.js#2762]
Hello,

I want to replace cdn url for js files to my own server. is that possible for this ? if yes then where to get source code for these files.

Thanks

**Comment by gkatsev** [comment]
See our [getting started guide](http://videojs.com/getting-started/#download). You can either download them from [releases](https://github.com/videojs/video.js/releases/tag/v5.0.2) here on github, or [from npm](https://www.npmjs.com/package/video.js) or from bower.
Thanks!
