### ISSUE TITLE
How to add new MenuItem to existed Menu

### ISSUE THREAD

**Issue by trungtin** [videojs/video.js#2764]
I'm new to this, so maybe I don't understand the basic of this, so please bear with me. I want to add a new `MenuItem` (select local captions...) to the existed `captionsMenu`, but just can't. When add to player, `controlBar`, or `captionsButton` itself, all works, and when I try:
```javascript
controlBar.captionsButton.addItem/addChild(new (a class extends MenuItem))
```
or:
```javascript
    controlBar.captionsButton.el().appendChild((new ...).el())
```
even:
```javascript
    controlBar.captionsButton.contentEl_.appendChild((new ...).el())
```
nothing work. Thanks.

**Comment by misteroneill** [comment]
The most straight-forward way of adding a captions track to your player is to have `<track>` element(s) in the `<video>` element. [See the tracks guide for more.](https://github.com/videojs/video.js/blob/master/docs/guides/tracks.md)

**Comment by trungtin** [comment]
Thanks, I have successfully add track captions, but the thing is, I need add a button for user select local caption file. As others have report, there is a problem with webkit based browser when displaying 'caption setting menu item', and when I add a menuItem to 'captions menu', the one got problem is Firefox, and Chrome display new added `menuItem` just fine.

**Comment by gkatsev** [comment]
The 'captions settings' option only shows up when our emulated captions are enabled. Native captions do not get this option as you can set the caption formatting natively in the browser or OS level.
As for adding local captions, you'll probably want to add a separate button for this outside of the menu, or maybe your own menu altogether, as the menu can get refreshed and remove your menuItem and working with local files is a very messy anyway.
