### ISSUE TITLE
CSP eval issue

### ISSUE THREAD

**Issue by sveinburne** [videojs/video.js#2766]
I'm using the dist raw sources from release 5.0.2, and need strict CSP policies. 
I thought the issue was addressed, cf #2077 but I do have an 'unsafe-eval' veto fired in chrome and firefox. This is the incriminated snippet, line 1982 of `video.js` : 

``` javascript
var bound = Function('binder', 'return function (' + boundArgs.join(',') + '){ return binder.apply(this,arguments); }')(binder);
```

Thanks for your help!

**Comment by gkatsev** [comment]
Looks like this comes in from our usage of [`object.assign`](https://github.com/ljharb/object.assign) which in turn uses [`function-bind`](https://github.com/Raynos/function-bind).

@ljharb thoughts?

**Comment by ljharb** [comment]
First, strict CSP policies are not possible to support when supporting pre-ES5 environments, because `bind` requires the `Function` constructor.

The best solution when using ES5+ environments is to use `browserify` to shim `function-bind` with `module.exports = Function.prototype.bind;`, in the projects that require overly strict CSP policies.

**Comment by sveinburne** [comment]
Great, thanks !

**Comment by gkatsev** [comment]
Thanks, @ljharb.
@sveinburne is that a satisfactory answer? Are you going to take care of that on your end or should we figure something out? (i.e., can we close this issue? :)

**Comment by sveinburne** [comment]
I don't yet have time to rebundle it with browserify, but I'll give you some feedback when I'll try the shim! 
Up to you to close/leave open ; anyway a big thanks to your reactivity!

**Comment by gkatsev** [comment]
Ok, I'll leave it open (especially since I'm not certain you'll be able to rebundle it because of how we publish videojs.). But let us know if you do get a chance and we'll see if we should make the change on our end.

**Comment by FelixAkk** [comment]
Hi, I also just ran into this CPS violation. I was wondering if it would be possible to rewrite that line in a future release to be more CSP compliant (I'm not familiar with the used JS features)? Many popular frameworks like Ember.js are pushing for CSP, so I suspect that there will be quite an increase of users running into this as well. It would be great (and user friendly) if users didn't have to rebundle it with browserify or add `unsafe-eval` just for VideoJS. Thanks for the great work on this player! :)

**Comment by gkatsev** [comment]
If someone wants to PR the browserify config update, I'll accept it. It'll happen at some point eventually, but will be a lot faster with a PR from someone :)

**Comment by gkatsev** [comment]
I think this is no longer an issue.
