### ISSUE TITLE
Transition to array children broke adding children via options object

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2767]
For, example, if you want to switch the `volumeMenuButton` for the old `muteToggle` and `volumeControl`, you could previously do
```js
videojs('player', {
  controlBar: {
    volumeMenuButton: false,
    muteToggle: {},
    volumeControl: {}
  }
});
```
However, now, the control bar will only loop through its children array to look for items. This means that the `volumeMenuButton` will get disabled correctly but it won't actually add `muteToggle` and `volumeControl` because it isn't in the list of items it's going through.

We probably should loop through the items in the array but also loop through the options object to make sure whether we need to add any other components.
https://github.com/videojs/video.js/blob/master/src/js/component.js#L490

**Comment by misteroneill** [comment]
Makes sense to me. :+1:

To be more clear to anyone else reading this; it's about adding _new children_ that are not in the `children` array for a component (in this case, the `controlBar` component has the `volumeMenuButton` in its `children`, but not the `muteToggle` or `volumeControl`).

**Comment by gkatsev** [comment]
I have a tentative fix locally but I'll want to consolidate some of the checks before PRing it.
