### ISSUE TITLE
Uncaught TypeError: this[c] is not a function While Using VideoJS Library

### ISSUE THREAD

**Issue by syedazampasha** [videojs/video.js#2768]
Iam not sure why this error is displaying in console

"Uncaught TypeError: this[c] is not a function"

videojs.js

.indexOf(" "+ c +" ")&&(a.className

http://stackoverflow.com/questions/33492214/uncaught-typeerror-thisc-is-not-a-function-while-using-videojs-library

**Comment by gkatsev** [comment]
Can you please provide some more information? What version of videojs are you using? When does this error come up? On what browsers do you see this error? Can you provide a reduced test case?

Thanks.

**Comment by gkatsev** [comment]
Any updates on this? The stackoverflow page is down as well.

**Comment by syedazampasha** [comment]
still the issue exists but even though iam able to play the video, so closing this issue. 

Thanks!
