### ISSUE TITLE
multiple plugin on control  bar

### ISSUE THREAD

**Issue by mzinko** [videojs/video.js#2771]
hello
i am trying to add multiple button on video.js control bar 
currently i can add only 1
i have videojs resolution selector and another plugin that show some text  on the control bar
it hide or disable one of them if i add them both 
how can i make display 2 plugin on the  control bar 
ready to hire a freelancer also to do this

**Comment by Soviut** [comment]
This problem might be due to the fact that your second plugin which is adding text is a videojs 4.x plugin while the resolution selector is a 5.x plugin. Videojs 5 revamped a lot of their component architecture which actually makes it easier to add buttons to the control bar; They should just line up one after the other. However, I'm not sure about 4.

**Comment by gkatsev** [comment]
What @Soviut said sounds correct. In v4, adding components to the control bar wasn't really something that we accounted for, though, it's definitely possible.

@mzinko 
What version of videojs are you using? What plugins? What browsers are you trying it on? Have a reduced test case?
It's possible that the plugins you're trying to use are broken or don't play well with each other.

**Comment by SomeJSGuy** [comment]
Hi, I'm having a somewhat related issue with a plugin I wrote. In the control bar, my control shows up at the last position, to the right of the Full Screen button. I'm working on VideoJS v. 5. On VideoJS v.4, my control is inserted at the leftmost position in the control bar. I have checked the code for the Component.addChild method in both versions, and it doesn't seems to have changed a lot. So, I used plain old DOM Scripting to add my control in the position I wanted. So, I wanted to know if there are plans to provide some way to, when adding come new control to the control bar, choose the position in which the new control will show up.

Thanks.

**Comment by mmcc** [comment]
@SomeJSGuy Keep an eye on #2540 for specific ordering utilities, but, especially if you plan on releasing a plugin in the wild, you really need to be careful to not be too picky about where it lands. We added the `customControlSpacer` for this reason, so custom plugins could just insert themselves after that spacer and at least be reasonably sure of the area the plugin would land for the default skin (and most others).

```
player.controlBar.el().insertBefore(player.controlBar.awesomeNewPluginButton.el(), player.controlBar.customControlSpacer.el().nextSibling);
```

That will place the new plugin after the `customControlSpacer`, between the remaining time and the fullscreen button (or playback rate, if that's visible) in the default skin.

**Comment by gkatsev** [comment]
@mmcc maybe we should consider something to go along with #2540 that would automatically insert after the custom control spacer?

**Comment by mmcc** [comment]
@gkatsev Yeah, I definitely think so.

**Comment by gkatsev** [comment]
I think this issue has been addressed. Also, having an accessible settings menu that plugins can add buttons to is something we want to add which will help with this. It's going on our roadmap.
