### ISSUE TITLE
Are Techs Components?

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2772]
While working on trying to make a generic solution for https://github.com/videojs/video.js/issues/2767 I ran into a problem creating components from a list of names. Namely, there isn't a good way to know whether a component is a component or a tech. There is also (at least) one major difference between the two -- a component takes the `player` and `options` as arguments but techs take `options` and `ready` as arguments. Meaning that you can initialize a tech and a regular component dynamically the same way.
So, the question is whether we should be registering Techs as components or do we need a tech registry?

```js
let componentName = 'Button';
let C = Component.getComponent(componentName);
let c = new C(player, options);

componentName = 'Html5';
C = Component.getComponent(componentName);
c = new C(player, options);  // error in some cases since Html5 assumes that the player is the options
```

**Comment by dmlap** [comment]
My feeling: based on the re-arch of techs we did in 5.0, it doesn't make sense for Techs to be Components. They have a lot in common but we did intentionally choose not to pass Techs references to the player.

**Comment by misteroneill** [comment]
I'm with @dmlap - things that are the same should be the same, things that are different should be obviously different.

**Comment by gkatsev** [comment]
I agree. Unfortunately, we can't remove Html5 and Flash from the component registration currently because semver.
Should we add a `registerTech`/`getTech` to mirror components in a future minor update?

**Comment by misteroneill** [comment]
I think that makes sense.

I guess that means until 6.0, `registerTech`/`getTech` would also register the tech as a component and `getComponent` would call `getTech` if no component is found.

**Comment by gkatsev** [comment]
we only need to maintain the compat for the built-in techs, Html5 and Flash. So, we could just register both as Techs and Components but have others only register Techs as Techs and not Components.

**Comment by gkatsev** [comment]
I have a PR for this: https://github.com/videojs/video.js/pull/2782
