### ISSUE TITLE
Video not playing in Firefox 42.0 64-bit

### ISSUE THREAD

**Issue by Tralapo** [videojs/video.js#2778]
I upgraded Firefox to the new 64-bit version 42.0 on Windows 10 yesterday, and it broke my Video.JS 5.0 player on https://-enabled websites. Plain http:// pages are fine.

My videocode looks like this and worked until yesterday, still works in all other browsers, Firefox 42.0 32-bit and also works in Firefox 42.0 64-bit at http:// websites:

```html
<video id="Videoname" class="video-js vjs-16-9 vjs-default-skin vjs-big-play-centered" poster="picture.jpg" preload="none" controls>
<source src="rtmps://streamlink" type="rtmp/mp4" />
<source src="https://streamlink/playlist.m3u8" type="application/x-mpegurl" />
</video>
```
At my https:// enabled website, the streams have stopped working. When I hit play, I get the 'X', but no error message which is normally shown below it.

In my console, I get the following error three times, nothing else:

```
VIDEOJS: ERROR: (CODE:0 MEDIA_ERR_CUSTOM)  Object { code: 0, message: "" }
e() video.min.js:19
[128]</h.error() video.min.js:19
[103]</Z</b.prototype.error() video.min.js:15
[103]</Z</b.prototype.handleTechError_() video.min.js:15
[125]</e/e() video.min.js:19
[125]</e/e() video.min.js:19
f/d.dispatcher() video.min.js:19
h() video.min.js:19
[63]</y</a.prototype.trigger() video.min.js:13
[112]</z</b.prototype.error() video.min.js:17
[109]</z.onError() video.min.js:16
```

On my http://-website, I do get the following errors I didn't get before updating to Firefox 42.0 64-bit by the way, but the videos do play normally:

```
Specified "type" attribute of "application/x-mpegURL" is not supported. Load of media resource https://streamlink/playlist.m3u8 failed.
Specified "type" attribute of "rtmp/mp4" is not supported. Load of media resource rtmps://streamlink failed.
```

**Comment by Tralapo** [comment]
I tried switching back to 4.x to see what would happen and that version did give me an error-message on the videoplayer:

```
FLASH: rtmpconnectfailure
```

It seems like Firefox doesn't know what to do with 'rtmps://'? It worked without problems in previous (32-bit) versions of the browsers and it still works in all the other browsers, so it's not a connection error with the server. It's Firefox-related.

**Comment by Tralapo** [comment]
Because nobody is responding and because it's maybe a bit theoretical, I made an example to look at. This is working in all other browsers, not in Firefox 42.0 (64-bit): http://bit.ly/1M02l5B

**Comment by Tralapo** [comment]
@gkatsev Tried this with your 5.2.0 today, still not working. Any ideas?

**Comment by heff** [comment]
I have no idea. Might be related to some specific Firefox security detail around Flash or networking.

**Comment by Tralapo** [comment]
@heff Ok. I will just wait for contrib-hls being ready then. Luckely Firefox Windows 64-bit has to installed by hand, because it's the first stable version, so the problem won't get very big in the next weeks.
