### ISSUE TITLE
VideoJs V5.1.0 CDN 403 Forbidden

### ISSUE THREAD

**Issue by vitor-faiante** [videojs/video.js#2780]
Hi I was following the documentation on http://videojs.com/getting-started/ and it says to include the JS and CSS for version 5.1.0 like so:

```html
<link href="http://vjs.zencdn.net/5.1.0/video-js.css" rel="stylesheet">

<script src="http://vjs.zencdn.net/5.1.0/video.js"></script>
```

However it seems that both of them are returning code 403 Forbidden. I tried to access both through the browser and they don't work.

Funny enough on the home page of the videojs site it says the npm version is 5.0.2.

**Comment by gkatsev** [comment]
5.1.0 hasn't been published to the CDN yet and it is released on npm under the `next` tag. This is so people can play around with it a bit before we promote it as a latest release.

Looks like our documentation is using the latest git tag? Hm...

**Comment by gkatsev** [comment]
I'm fixing the website from having the wrong version here https://github.com/videojs/videojs.com/pull/38

**Comment by gkatsev** [comment]
The website has been fixed. Also, 5.1.0 has been skipped over and 5.2.1 is now out as @latest.
