### ISSUE TITLE
videojs.options.flash.swf doesn't work if .swf file is not publicly available 

### ISSUE THREAD

**Issue by oleynikd** [videojs/video.js#2783]
Hi,

Well I spent a few hours digging... It turns out that video.js v5 won't use `.swf` file that was set by `videojs.options.flash.swf` if it is not accessible from internet (like in local dev env).

WTF??? WHY???
Thanks in advance.

**Comment by gkatsev** [comment]
How are you testing locally? Are you using a local webserver or opening the file directly in the browser.
Flash will not load unless you're using a local webserver.

**Comment by oleynikd** [comment]
I am testing locally. I'm using [a web server](https://hub.docker.com/_/nginx/). I can see that browser loads .swf file but video.js won't start playback. If I change URL to publicly available (like https://dl.dropboxusercontent.com/u/14522796/video-js.swf) everything works great with the same .swf!

**Comment by gkatsev** [comment]
Have a reduced test case?

**Comment by oleynikd** [comment]
What do you mean by "reduced"?

**Comment by gkatsev** [comment]
An example that removes everything unnecessary and irrelevant to the problem at hand to isolate the issue. https://css-tricks.com/reduced-test-cases/

**Comment by oleynikd** [comment]
OK, it was my own [issue with VM](https://github.com/mitchellh/vagrant/issues/351#issuecomment-1339640)
Everything works fine. I'm sorry and thank you for help.

**Comment by gkatsev** [comment]
Ah, cool.
