### ISSUE TITLE
Video play error on Firefox 41.0.2

### ISSUE THREAD

**Issue by mralexho** [videojs/video.js#2785]
I receive the following error while running on OS X v10.7.5 Firefox v41.0.2 -

```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. Object { code: 3, message: "The media playback was aborted due …" }
```

I'm not sure if this is a bug with FF or the player. Any ideas?

**Comment by gkatsev** [comment]
What version of videojs are you using? Also, what type of video are you trying to play?
It sounds like you may have a badly encoded video or encoding that isn't set up for firefox to work. Could also be an issue with flash not loading.

**Comment by mralexho** [comment]
Videojs is v5.1.0. The video I'm playing used to work for several weeks. I think I first noticed the bug occur last week. There are three video types to play from - h264 MP4, ogg ogv, and vp8 webm.

**Comment by mralexho** [comment]
I just updated Firefox to v.42.0 and the video is rendering fine again. Thanks.

**Comment by gkatsev** [comment]
Cool, thanks.
