### ISSUE TITLE
requestFullScreen() does not work

### ISSUE THREAD

**Issue by jduncanator** [videojs/video.js#279]
In Chrome 23.0.1271.97 no matter what I try, calling `requestFullScreen()` does not work! The fullscreen button on the controls works as expected and opens the video in fullscreen however calling `requestFullScreen()` does nothing. Calling it does set the `isFullscreen` to true but does nothing.

**Comment by vakuzmin** [comment]
any updates on the issue since its still not working for me 

"video.js": "^6.6.3",

    $modalPlayer.on('shown.bs.modal', function () {
      self.player.play();
      self.player.requestFullScreen();
    });

**Comment by gkatsev** [comment]
@vakuzmin the browsers require that requestFullscreen be called as part of a user gesture.

**Comment by vakuzmin** [comment]
@gkatsev ahh i see, thanks a lot for the getting back

**Comment by TrySpace** [comment]
PSA: note the capital `S` in `requestFullScreen` afaik is deprecated (but possibly still in firefox) and should have a small `s`; `requestFullscreen`.

This took me a while to figure out

**Comment by GalGurGurevich** [comment]
my working example

https://codepen.io/galgurevich/pen/JjMqXGO

player.on("play", function(){
   player.requestFullscreen();
 });

should work
