### ISSUE TITLE
How to detect a broken link?

### ISSUE THREAD

**Issue by vucuong12** [videojs/video.js#2790]
My site plays some videos, whose sources may change after a few days. When an user watch a video, if it doesn't work (because its source link has just been changed), how can I immediately know that the link has been changed, so that I can update new link for the video?

**Comment by pepijn809** [comment]
I am not sure if this is able to be done by any of the scripts for video-js. But i guess you can make a simple script where users can report a page where the video is on. 

In wordpress this would be extremely easy to do, but scripting it yourself is also a way to do it. Google around for a bit, i'm sure you can find something and implement it in your website.

**Comment by gkatsev** [comment]
You should be able to listen to the [`error`](http://docs.videojs.com/docs/api/player.html#Eventserror) event which would tell you that the something is broken which you can then log and send over to your metrics. If you want, you could even change the video on the fly (see https://github.com/videojs/video.js/issues/2810#issuecomment-157413458).
