### ISSUE TITLE
Spelling mistake in function name causing error

### ISSUE THREAD

**Issue by jawadsahil** [videojs/video.js#2793]
https://github.com/videojs/video.js/blob/master/src/css/components/_progress.scss

Line 105 has a typo:
background: ligthen($secondary-background-color, 25%);

correct the spelling of *ligthen*;
It should be 
background: lighten($secondary-background-color, 25%);

Thanks

**Comment by gkatsev** [comment]
Heh, oops.
Care to submit a PR with the spelling corrections? Thanks

**Comment by jawadsahil** [comment]
I am new to this Git thing.. and still not familiar how exactly these PR works.. but if anyone can tell me the steps?

**Comment by Soviut** [comment]
@jawadsahil The normal way to do a pull request (PR) is:

- Fork the repo (click the "fork" button up top) so you have your own version of it
- git clone the repo to your local system
- update the code
- run unit tests where applicable (in your case, not necessary)
- commit
- push back up to your fork
- click the "pull request" button on your repo in github

However, with something this simple, you can just:

- find the file on github
- click the "edit" button near the top
- use the inline editor to make the change
- submitting the change will create a new commit on a temporary fork and perform a PR

**Comment by gkatsev** [comment]
@Soviut thanks for those steps!

**Comment by Soviut** [comment]
I can confirm that this issue occurs in the CodePen theme builder. http://codepen.io/heff/pen/EarCt

![videojstypo](https://cloud.githubusercontent.com/assets/226882/11159299/64303c8c-8a2c-11e5-8a40-d07c1bc06b32.png)
