### ISSUE TITLE
Text Track doesn't get removed properly?

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#2799]
`removeTrack_(rtrack)` can oddly get called with either an `HTMLTrackElement` or a `{track: track}`—neither of which will be removed from
https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-list.js#L91, but instead it looks like its going to remove the last track in the loop?

---

Html5 tech will eventually fire a `removeTrack_(e.track)`. Which looks like it will remove the last track found in the previous loop.

``` js
this.remoteTextTracks().addTrack_(track.track);
```

https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L754

``` js
this.textTracks().addTrack_(e.track);
```

https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L275

``` js
this.remoteTextTracks().removeTrack_(track);
```

https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L772

``` js
this.textTracks().removeTrack_(e.track);
```

https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L279

``` js
if (this.featuresNativeTextTracks) {
  this.handleTextTrackChange_ = Fn.bind(this, this.handleTextTrackChange);
  this.handleTextTrackAdd_ = Fn.bind(this, this.handleTextTrackAdd);
  this.handleTextTrackRemove_ = Fn.bind(this, this.handleTextTrackRemove);
  this.proxyNativeTextTracks_();
}
```

https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L70

**Comment by gkatsev** [comment]
Don't remember the specifics but I think it's probably doing a slightly better job of removing things than you think but also probably not as good of a job as it should.
As for why `removeTrack_` takes either an `HTMLTrackElement` or `{track: track}` is because `{track: track}` is sort of our emulated `HTMLTrackElement` until we get a real emulated `HTMLTrackElement`.

**Comment by chemoish** [comment]
> probably doing a slightly better job of removing things than you think

Agreed, lol, hence the :question:.

**Comment by gkatsev** [comment]
There's been a lot of work around this. I hope we do a good job now.
I'm going to close this issue until someone raises it again.
