### ISSUE TITLE
How do I get the name of the current video file?

### ISSUE THREAD

**Issue by Ayorus** [videojs/video.js#2802]
Hello,

I am using video.js to reproduce a video (using the M3U format) and I need the name of the current video file. I tried the property: player.currentSrc(). However it returns the URL I use to generate the M3U file. 

Does anyone know how to accomplish this? 

In order to clarify the issue I add one example: 

URL which generates M3U file:  http://domain.com/getM3UFile

Response of URL: 

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-DISCONTINUITY
#EXTINF:10.000000,
http://domain.com/125953-00ff51fe.ts
#EXTINF:10.000000,
http://domain.com/130002-b843369b.ts
#EXTINF:10.000000,
http://domain.com/130011-e02026cd.ts
#EXTINF:10.000000,
http://domain.com/130020-589c41a8.ts
#EXTINF:10.000000,
http://domain.com/130030-623474f2.ts
#EXTINF:10.000000,
http://domain.com/130039-da881397.ts
#EXT-X-ENDLIST

If I use the property: player.currentSrc() It will return:  http://domain.com/getM3UFile

What I need to know is the name of the ts file which is playing (for example: 130020-589c41a8.ts)

I am working with IE 11 and Video.js v4.3.0

I need to track the time the video was recorded which is in the file name with the format: hhmmss_xxxxx.ts

Any help will be very appreciated
Regards

**Comment by gkatsev** [comment]
Can you tell us more about which version of videojs you are using and what browser? Also, are you using any videojs plugins?
If you're running in safari, it plays HLS natively and it doesn't give you any info about which segment is playing at the time.
If you're using contrib-hls, for example, you could inspect the internals of HLS to figure out.

Why do you need to know which segment is currently playing?

**Comment by Ayorus** [comment]
I am working with IE 11 and  Video.js v4.3.0

I need to track the time the video was recorded which is in the file name with the format: hhmmss_xxxxx.ts

**Comment by gkatsev** [comment]
Unfortunately, I don't think there's much you can do other than manually grabbing the manifest and checking to see where in it you are by comparing the durations and the currentTime.
This will unlikely require changes to videojs, so, I'm closing the issue, but we can continue discussing it here.

**Comment by Ayorus** [comment]
Thanks for your comments. In fact, I tried to do that. However the duration of the segments is not perfect, so, I get variations . If you get any idea how to tackle this I will appreciate any recommendation.  

Regards
