### ISSUE TITLE
Button text is not showing

### ISSUE THREAD

**Issue by osanwe** [videojs/video.js#2805]
Hello!

I have added the custom button  to control bar like this:

    var slidesButton = player.controlBar.addChild('button', {
        text: 'Slides'
    });
    slidesButton.addClass('vjs-hiding-button')

but I did not see any text because out html was like this:

    <button aria-live="polite" type="button" role="button" tabindex="0" class="vjs-control vjs-button  vjs-hiding-button">
        <span class="vjs-control-text"></span>
    </button>

Thanks in advance!

**Comment by chemoish** [comment]
I haven't created a button with text on it before (i.e. Button that doesn't have an icon), but I hope this helps.

http://docs.videojs.com/docs/api/button.html#addChildHeader

```js
var myButton = myComponent.addChild('MyButton', {
  text: 'Press Me',
  buttonChildExample: {
    buttonChildOption: true
  }
});
```

However, the text attribute is never parsed.

https://github.com/videojs/video.js/blob/master/src/js/button.js#L22
https://github.com/videojs/video.js/blob/master/src/js/component.js

Instead they do this…

```js
BigPlayButton.prototype.controlText_ = 'Play Video';
```
https://github.com/videojs/video.js/blob/master/src/js/big-play-button.js#L43

Another thing you can do is…

```js
var slidesButton = player.controlBar.addChild('button');

slidesButton.controlText('Slides');
```
