### ISSUE TITLE
Add custom Class to Video Element

### ISSUE THREAD

**Issue by stephanedemotte** [videojs/video.js#2806]
Hi !

Can we add custom class to the video element ?
In this doc : http://docs.videojs.com/docs/guides/components.html
We can't target the video tag.

Thanks !

**Comment by Soviut** [comment]
The `<video>` tag is intentionally obfuscated because it could be swapped out for a flash player depending what tech you support.

Instead, you'll have to use some javascript to get at it.

```javascript
// use queryselector to find the child video element
var videoElement = player.el().querySelector('video');

// if one is found, we're using html5 tech, so add a custom class
if (videoElement) {
    videoElement.classList.add('my-custom-class');
}
```

**Comment by gkatsev** [comment]
Why do you need to add a class to the video element itself? Would adding it to the player element not be sufficient?
Can you elaborate on the usecase? Thanks.

**Comment by stephanedemotte** [comment]
i need to use the css property "object-fit: cover" on it.
If i use it on its parent, the method don't work as expected.

I have use the @Soviut logic to get it.

Thanks !

**Comment by gkatsev** [comment]
Yep, in that case both things suggested above are recommended. Glad you got it figured out.
