### ISSUE TITLE
Safari 9 problems

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#2807]
We seem to have a problem getting VJS 5 to play, seek and re-play properly in Safari 9 on Mac 'El Capitan'. We are using DASH tech.
This issue was referenced here:
https://github.com/videojs/videojs-contrib-dash/issues/22
Our example is here:
https://living.video/direct5.php?item=hphfawsley
Not sure if it's a videojs issue or dashjs issue or contribdashjs issue, BUT Safari 9 does not seem to work.
All other browsers work fine. We have no problem in PC IE/Chrome/Firefox, and it's fine in Mac Chrome, but Safari 9 on Mac is not playing on initial poster click, not seeking correctly, and not re-playing at the end.
Help please!

**Comment by gkatsev** [comment]
Going to close this for now to let the conversation happen in videojs/videojs-contrib-dash#22. We can move it back here if it is found to not be a DASH issue but a vjs one.
