### ISSUE TITLE
unknown caption file in Safari

### ISSUE THREAD

**Issue by jemoreno** [videojs/video.js#2808]
Only when I access a video using video.js on safari do I see an unknown option for closed captions.  I do not see this in Firefox or Chrome.  Is this a known bug, or is there a simple patch?  

example: http://media.dcccd.edu/embed/?vid=1461

**Comment by gkatsev** [comment]
Unfortunately, this is how what Safari does: https://developer.apple.com/library/ios/qa/qa1801/_index.html
It's possible that by re-encoding the video, you may be able to fix it but it's probably not worth it and it isn't guaranteed.
Making as "browser bug", though, not really a bug, more of a limitation.
