### ISSUE TITLE
Update the video source url without refreshing page failed

### ISSUE THREAD

**Issue by rieonke** [videojs/video.js#2809]
I am trying to make a test iptv web page.
But I meet a trouble when updating the video source url .
When the video is playing,I try to change the video channel,but the video is only paused and never continue...
Unless I refresh the page and select the channel i want at first time .
But I want to change between different channels without refreshing the page ,how can i do it ? can you help me ?
Thanks a lot!!

**Comment by pepijn809** [comment]
Maybe this can help you, see my reply on the topic. (near the top of the page)
https://github.com/videojs/video.js/issues/2810

**Comment by rieonke** [comment]
Thanks a lot for your help!
Today I find it works when I switch between different file url like http://url.com/1.mp4  and  http://url.com/1.mp4 . and it's smooth and quite quick.
But when the sources are streams ,The trouble comes, I must refresh the page.

**Comment by gkatsev** [comment]
You should be able to use the [`src`](http://docs.videojs.com/docs/api/player.html#Methodssrc) method on the player object. Make sure to specify the type for the streams.
Closing for now, but reply if you have more questions and we can reopen if there are issues.
