### ISSUE TITLE
Alternative url for video

### ISSUE THREAD

**Issue by abrgitlab** [videojs/video.js#2810]
Is there any possibility to load video from another URL if the main one failed?
For example, I want to load video from http://main.url.com/video1.mp4, but this URL unavailable. So I got to try http://alt.url.com/video1.mp4

**Comment by pepijn809** [comment]
I am not sure if that could work, but perhaps. 

You may want to look over here, it's not what you want. But it may help you out.
http://stackoverflow.com/questions/16657369/video-js-update-video-source-when-clicking-on-a-link

**Comment by gkatsev** [comment]
I think what you want to do is listen to the [error event](http://docs.videojs.com/docs/api/player.html#Eventserror), unset the error using [`player.error(null)`](http://docs.videojs.com/docs/api/player.html#Methodserror) and [load in a new src](http://docs.videojs.com/docs/api/player.html#Methodssrc).
