### ISSUE TITLE
vjs-control-bar Not Rendering Correctly in IE 11

### ISSUE THREAD

**Issue by pvijeh** [videojs/video.js#2812]
The vjs-control-bar element does not render correctly in IE11.  It appears to render about 15px to low, and is partially cut off and outside of the video-js wrapper div.

**Comment by pvijeh** [comment]
was the result of external css

**Comment by gkatsev** [comment]
Ah, cool. May I ask what the offending code was?
I've been thinking that we need to have some css resets that affect the videojs div so that our styles are more consistent and less prone to breakage.

**Comment by pvijeh** [comment]
Ill let you know as soon as I figure it out :)

**Comment by gkatsev** [comment]
Heh, thanks.

**Comment by pvijeh** [comment]
This css was the problem ultimately.

.video-js .vjs-control:before {

}

It was either a cascading em or being overridden somehow only in IE.
