### ISSUE TITLE
pause before end event

### ISSUE THREAD

**Issue by vit-koumar** [videojs/video.js#2819]
Hello,

maybe this is not an issue, possibly this behavior is on purpose.

I noticed that when the playback ends (for ended playlists only), this event emits PAUSE event followed by END event.

So my question is, why there is that PAUSE event, for me it is not logical to receive the PAUSE event if the playback has been stopped.

Thanks for the reply.

Vit

**Comment by vit-koumar** [comment]
I use VideoJS 5.2.1.

**Comment by gkatsev** [comment]
This is according to the HTML video spec and it actually sort of makes sense. When a video ends it is also inherently paused. We're just passing through the native events here. http://www.w3.org/2010/05/video/mediaevents.html

**Comment by vit-koumar** [comment]
Thanks for the very quick reply.
