### ISSUE TITLE
dupliacted npm

### ISSUE THREAD

**Issue by yonatanmn** [videojs/video.js#2824]
Hi, 
What's the purpose of this : https://www.npmjs.com/package/videojs ? 
Looks the same, different npm owner

**Comment by gkatsev** [comment]
`video.js` is the official package. I believe that package is from before we started publishing videojs to npm ourselves. We have no control over the other one, though, I guess someone could send them a note to ask to point at the official package.

**Comment by gkatsev** [comment]
If we do, we should cc npm.

**Comment by heff** [comment]
I think it’s not the same person as last time. The old one got deleted. If
it gets removed again we should claim it.

**Comment by gkatsev** [comment]
We contacted them. Main concern was https://github.com/videojs/video.js/issues/2704 which I'll work on.

**Comment by mmcc** [comment]
Following up on this, the guy said he'd transfer the module after he gets back from holidays.
