### ISSUE TITLE
Fluid layout hides video when VIDEO ID begins with a numeric

### ISSUE THREAD

**Issue by nbibler** [videojs/video.js#2828]
Whenever the HTML `VIDEO` tag's `ID` attribute begins with a numeric value, the `fluid` option hides the video entirely. It looks as though the CSS rule is not generated for the element to set the proper padding.

For a demo of the failure, see http://jsbin.com/huveba/2/edit?html,output

Notice that the last two videos use a `1my-video` ID attribute value (begin with a numeric).

[HTML5 supports element IDs that begin with numerics](http://www.w3.org/TR/html5/dom.html#the-id-attribute) (different from earlier HTML versions).

**Comment by nbibler** [comment]
Seemingly, an ID starting with a numeric value is now valid in HTML5. However, it looks like a CSS class name that begins with a numeric may not be valid.

**Comment by gkatsev** [comment]
Huh, oops.
Changing the class makes sense, though, it might be considered a breaking change. We might want to special case this and only swap it if the id begins with a number and then when we're ready to do a major update do it for everything.
Care to submit a PR?
Thanks.

**Comment by nbibler** [comment]
Sure. If it's a concern about a breaking change… perhaps the approach going forward is to generate both, rather than conditionally generate one or the other?

**Comment by gkatsev** [comment]
Generating both might work, though, it might require us to make do blocks.
```css
/* this may fail completely if a single selector fails, at least on older browsers */
.dimensions-1my-video, .1my-video-dimensions {
...
}

/* we'll need to do this instead */
.dimensions-1my-video {
...
}
.1my-video-dimensions {
...
}
```

**Comment by gkatsev** [comment]
Though, it's only needed if it actually fails. I know it's an issue around fullscreen selectors. Not sure about this case.

**Comment by nbibler** [comment]
Pull request added at #2829.
