### ISSUE TITLE
On LIVE HLS stream media object is not updated

### ISSUE THREAD

**Issue by FDiskas** [videojs/video.js#2832]
Hello, on LIVE HLS (m3u8) stream
Everytime after playlist request was done the media object is not update.
FOr example if plailyst kontent is
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.000000,
1448020624.ts
#EXTINF:10.000000,
```
The media object content is `hls.playlists.media_`
```js
{
   allowCache: true,
   discontinuitySequence: 0,
   discontinuityStarts: [],
   mediaSequence: 0,
   playlistType: "EVENT",
   segments: [],
   targetDuration: 10,
   uri: "http://***.m3u8"
}
```
And on other request the playlist got the `#EXT-X-ENDLIST` tag the media object still shows nothing about that 
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.000000,
1448020624.ts
#EXTINF:10.000000,
#EXT-X-ENDLIST
```
Returns the same object
`hls.playlists.media_`
```js
{
   allowCache: true,
   discontinuitySequence: 0,
   discontinuityStarts: [],
   mediaSequence: 0,
   playlistType: "EVENT",
   segments: [],
   targetDuration: 10,
   uri: "http://***.m3u8"
}
```

It should return updated object
```js
{
   allowCache: true,
   discontinuitySequence: 0,
   discontinuityStarts: [],
   endList: true,
   mediaSequence: 0,
   playlistType: "EVENT",
   segments: [],
   targetDuration: 10,
   uri: "http://***.m3u8"
}
```

Pay attention to `endList: true`. If I manually change that object the player acts as it should on DVR streams.

Currently I'm using
"videojs": "4.12.15",
"videojs-contrib-hls": "0.17.8",
"videojs-contrib-media-sources": "1.0.0",

**Comment by gkatsev** [comment]
Already open https://github.com/videojs/videojs-contrib-hls/issues/442 which is the correct place to have this issue. Closing.
