### ISSUE TITLE
Problem with adding subtitles from JS.

### ISSUE THREAD

**Issue by osanwe** [videojs/video.js#2839]
Hello!

I received dynamic information about video and init the videoplayer with this information like this:

    var video_setup = { 'controls': true,
                        'preload': 'none',
                        'playbackRates': [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 3],
                        'poster': getPosterUrl(jsonObject),
                        'techOrder': [ 'html5', 'flash' ],
                        'tracks': [
                            { src: 'video/0546_prepod_01H.srt', kind: 'subtitles', srclang: 'ru', label: 'Русский' },
                        ],
                        'plugins': {
                            videoJsResolutionSwitcher: {
                                default: 'low',
                                dynamicLabel: true
                            }
                        }}

When I test this in Firefox, it works great. But in Google Chome and IE 11 I do not see the subtitles button on the control bar. HTML does not contain elements in switcher div. In Microsoft Edge there is a button for switching subtitles but nothing happens after clicking on it.

**Comment by gkatsev** [comment]
Unfortunately, we don't support srt anymore. We've transitioned to using native captions or using vttjs for captions and both of those use WebVTT only.

**Comment by osanwe** [comment]
Well. But this problem is with *.vtt-files as well - the button for switching subtitles is available in Firefox only.
P.S. I use *.srt because I did not find a way for hiding subtitles but making the switching button available (https://github.com/videojs/video.js/issues/2830).
