### ISSUE TITLE
First frame as poster?

### ISSUE THREAD

**Issue by Reaper507** [videojs/video.js#284]
Is it possible (could you add this possibility)?

**Comment by theshine** [comment]
Hi,
I tried this method but the poster is coming up a black screen.
This is how I have it set:

<video id="example_video_1" class="video-js vjs-default-skin"
  controls preload="auto" width="640" height="480"
    data-setup='{"controls":true, "autoplay": true, "loop": true, "preload": "auto"}'>

**Comment by gkatsev** [comment]
@theshine do you have more of the embed code? What type of video are you using? I'm not certain whether our flash fallback can do this. If you're using html it should work.

**Comment by gkatsev** [comment]
Also, what version of videojs and what browser did you use?

**Comment by theshine** [comment]
Hi,
Thanks for the help.
This is the final page:
http://thediamond.com/fancybox/vimeotestjs5.html
Its an mp4 file.

**Comment by theshine** [comment]
I am trying it on IE, chrome and FF.
Thanks

**Comment by vedankita** [comment]
Is it working on safari and iOS without using poster attribute?

**Comment by satches** [comment]
Not working on iOs w/Chrome.

**Comment by baronkoko** [comment]
Or add preload='metadata' to load only metadata when the page loads

**Comment by Kogoruhn** [comment]
@gkatsev Hi!
I use videojs 7.4.1
The player does not put the first frame as poster IF src is `.m3u8`, with `.mp4` works well. 
Found variant player.play, then stop, but this is a filth. Pls help

**Comment by Kogoruhn** [comment]
For future googlers:

```
function setPoster(player) {
  player.muted(true);

  player.play().then(function(){
    player.pause();
    player.hasStarted(false);
    player.removeClass('btn-hide');

    player.one('play', function(){
      this.muted(false)
    })
  })
}
```

class "btn-hide" hides control bar, big play button and spinner

**Comment by KristerV** [comment]
thanks @Kogoruhn , but browsers stop autoplay these days :(

**Comment by cataclysmuprising** [comment]
See the[ stackoverflow answer](https://stackoverflow.com/questions/7323053/dynamically-using-the-first-frame-as-poster-in-html5-video#50386123) 

just append time in seconds #t={seconds} to source URL

<source src="testvideo.mp4#t=0.1" type="video/mp4" />
