### ISSUE TITLE
MenuItem undefined!

### ISSUE THREAD

**Issue by mysamimi** [videojs/video.js#2840]
hi,
when I used video-js-resolutions got this error "undefined is not an object (evaluating 'videojs.MenuItem.extend')" 
videojs miss MenuItem class! what's wrong?

**Comment by gkatsev** [comment]
What version of videojs are you using?

**Comment by mysamimi** [comment]
I used latest version 5.2.1

**Comment by gkatsev** [comment]
It sounds like the plugin needs to update itself to support videojs 5. We've had some changes in that update. See https://github.com/videojs/video.js/wiki/5.0-Change-Details. Probably worth opening an issue against that plugin asking them to update with videojs 5 support.
Meanwhile, you can either drop back down to videojs 4 or you can grab the compatibility plugin that should fix the issue as a stopgap: https://github.com/videojs/videojs-4to5#the-plugin
Going to close this, but let us know if you have any more questions.

**Comment by mysamimi** [comment]
Tnx Gary,

**Comment by alvaromlg** [comment]
Hello,
I cannot see the change details for MenuItem in the link https://github.com/videojs/video.js/wiki/5.0-Change-Details you provided, which is the workaround for this?

**Comment by BrandonOCasey** [comment]
it can also be `videojs.getComponent('MenuItem');` as in the global `videojs` object. sorry for the late response.
