### ISSUE TITLE
How to position custom control in controlBar

### ISSUE THREAD

**Issue by vadikace** [videojs/video.js#2857]
I have added a few new buttons to ControlBar. They are displayed after DurationDisplay. How to position them inside the ControlBar with videojs?
```javascript
player.controlBar.addChild('button1', options);
player.controlBar.addChild('button2', options);
```

And this is how it looks for now:
![Preview] (http://i.imgur.com/se5waKt.png)

**Comment by gkatsev** [comment]
We're working on adding the child at a particular place, see #2540.
Meanwhile, you can call `addChild` like you do and then you can re-add the element where you want it go to:
```js
player.controlBar.el().insertBefore(player.controlBar.button1.el(), player.controlBar..customControlSpacer.el());
```

**Comment by gkatsev** [comment]
Closing, let us know if you have more questions and keep your eye out for #2540.

**Comment by vadikace** [comment]
@gkatsev Thanks, it's nice workaround
