### ISSUE TITLE
Cues are sometimes undefined in the updateForTrack function

### ISSUE THREAD

**Issue by imbcmdth** [videojs/video.js#2870]
I have seen several instances where `TextTrackDisplay.prototype.updateForTrack` tries to use cues that are `undefined`. In the `cues` array, I see that there are entries that are `undefined`.

This happens occasionally and the only time I have seen this behavior is when using 608 captions with the latest contrib-hls.

**Comment by gkatsev** [comment]
Fixed https://github.com/videojs/video.js/pull/2896
