### ISSUE TITLE
all plugins firing twice 4.12.13

### ISSUE THREAD

**Issue by elevenpast** [videojs/video.js#2871]
Hello,

I'm using several plugins in my 4.12.13 environment.   For someone reason, they all fire twice whenever I click the plugin menu item.   I've exhausted my know-how and I'm not even sure where to look any more.  

-seek plugin
-HD toggle plugin
-zoom plugin

Here is a simple example with the HD toggle plugin.  Clicking the button causes it to fire twice (as you'll see in the console).      http://tinyurl.com/hlzp677

Any thoughts?  

J

**Comment by gkatsev** [comment]
It's because you're binding another onclick handler to the button. Videojs does this for you by default: https://github.com/videojs/video.js/blob/v4.12.15/src/js/button.js#L21 so it's unnecessary to do it manually. Hope that helps.

**Comment by elevenpast** [comment]
Spot on!!! Thanks for the quick reply, I wish I had given up and asked sooner!

J

**Comment by gkatsev** [comment]
You can also come chat with us on IRC: #videojs on freenode.
