### ISSUE TITLE
How to add a custom button in control bar menu. I am using videojs version 5.2.4.

### ISSUE THREAD

**Issue by Viper177** [videojs/video.js#2872]
I am trying to add a custom button in control bar menu. I tried code given here http://stackoverflow.com/questions/16550897/videojs-4-0-plugin-how-to-properly-add-items-to-the-controlbar/

But it seems that our version of video js is causing a problem in calling functions.

What should i do? Also I want it to show/hide automatically as control bar hide and show. 

Please help.

**Comment by sprice** [comment]
Just recently [I wrote a Videojs 5 plugin](https://github.com/sprice/videojs-audio-tracks/blob/master/src/videojs-audio-tracks.js) that adds a button to the control bar. Take a look to see how it's done. Note it's in es6 and uses browserify/babelify to transpile.

**Comment by gkatsev** [comment]
We have an example of how you can do it if you're not using vjs5: https://github.com/videojs/video.js/wiki/5.0-Change-Details#videojs-50-subclassing-examples.
Hope that helps.
