### ISSUE TITLE
closed captions not working in IOS devices alone

### ISSUE THREAD

**Issue by jothikannan** [videojs/video.js#2873]
I knew that the issue is already discussed on multiple threads , but i can't get any working solution on those threads, so i just decided to post new issue here

Closed cpations on my player working well in all the Desktop and Andriod devices no issues on that, but it's not working alone in IOS devices like Iphone , Ipad. when we play the video it goes to fullscreen and i can't see any captions over the video

There is any quick solution resolve this issue ? am using video.js 4.12

**Comment by gkatsev** [comment]
Do you have a reduced test case we can see? It'll help us track down the issues.
However, at first glance, that thing you need to do is add the `crossorigin` attribute to the video element on ios (https://github.com/videojs/video.js/issues/1888).

**Comment by jothikannan** [comment]
Hi @gkatsev 

I solved myself this problem by adding the following line which adds the track elements after the videojs initialized, so now that the captions is working in all the devices

`document.getElementById("video_viewer_html5_api").innerHTML = '<track label="English Captions" srclang="en" kind="captions" src="demo.captions.vtt" type="text/vtt" default />';`

But When i use this i can't see CC menu in the video player, any trick to add the CC menu dyanamically ?

**Comment by gkatsev** [comment]
You should be able to use the `addRemoteTextTrack` method instead of trying to modify the `innerHTML`:
```js
player.addRemoteTextTrack({
  label: 'English Captions',
  language: 'en',
  kind: 'captions',
  default: true,
  src: 'demo.captions.vtt'
});
```
Hope that help.

**Comment by jothikannan** [comment]
@gkatsev 

I tried as you said but it says

`Uncaught TypeError: mplayer.addRemoteTextTrack is not a function`

As i said am using videojs 4.12 , could you tell me that the `addRemoteTextTrack` in not available in the version am using, else how could i reach the solution ?

**Comment by gkatsev** [comment]
4.12 [*should*](https://github.com/videojs/video.js/blob/v4.12.15/src/js/player.js#L1733-L1735) have this function.
I'm not sure I can help more without seeing a reduced live test case. Can you put one up on jsfiddle?

**Comment by jothikannan** [comment]
Hi @gkatsev 

Sorry my bad am using videojs 4.2 not 4.12, pls attached minified fiddle

http://jsfiddle.net/63oeempr/

**Comment by gkatsev** [comment]
Ah, videojs 4.2 didn't have that function. It was added in 4.12 along with a massive architecture of tracks. I would highly suggest that you upgrade to the latest 4.12 release, or even better to the current 5.x release.
Is there a particular reason why you cannot upgrade?

**Comment by gkatsev** [comment]
Closing because we're not going to make any changes to videojs 4.2. But we'll try and help you out if you have more details. I'm not even sure what the 4.2 tracks api is.
