### ISSUE TITLE
Doc.s are Inaccurate with Respect to Configuration of Player Controls, Syntax Inconsistent

### ISSUE THREAD

**Issue by tneaves** [videojs/video.js#2876]
I have been consulting [Options](http://docs.videojs.com/docs/guides/options.html#toc_1) and have found that the configuration options described in [Component Options](http://docs.videojs.com/docs/guides/options.html#toc_11) do not work. The syntax described is inaccurate.

This does not work with the CDN (as described by doc.s):

```javascript
videojs('video-id', {
  controlBar: {
    muteToggle: false // or true
  }
});
```

This does work:

```javascript
videojs('video_id', {
  controlBar : {
    children : {
      muteToggle:true
    }
  }
});
```

And this:

```javascript
videojs('video-id', {
				controlBar : {
					children : [
					    'playToggle',
						'muteToggle',
						'volumeControl',
						'fullscreenToggle'
					]
				}
			});
```

**Comment by gkatsev** [comment]
The first one *should* work again. It did break but we fixed it in 5.2 (https://github.com/videojs/video.js/blob/master/CHANGELOG.md#520-2015-11-10) (https://github.com/videojs/video.js/pull/2773).
What version of videojs are you using?

But you're correct, our docs don't reflect that you can make them an array.

**Comment by tneaves** [comment]
@gkatsev Does that mean I should pull source and use that as opposed to CDN

**Comment by gkatsev** [comment]
@tneaves it's available on the CDN as well. `//vjs.zencdn.net/5.2.4/video.js` or `//vjs.zencdn.net/5.2/video.js`.

**Comment by tneaves** [comment]
Gotcha. Thanks! I'll give it a shot. Apologies. Mine was targeted at 5.0.2 as described by docs.

**Comment by tneaves** [comment]
Broken, there, too:

```html
<!DOCTYPE html>
<html>
<head>
	<link href="http://vjs.zencdn.net/5.2.4/video-js.css" rel="stylesheet">
	<script src="http://vjs.zencdn.net/5.2.4/video.js"></script>
	<meta charset="ISO-8859-1">
</head>
<body>
	<video 	id="share_video_player" class="video-js vjs-default-skin"
	  		controls preload="auto" width="640" height="264">
	 	<source src="http://video-js.zencoder.com/oceans-clip.mp4" type='video/mp4' />
	</video>
	
	<script>
		videojs(document.getElementById('share_video_player'), {
			controlBar : {
				muteToggle:false
			}
		});
	</script>
</body>
</html>
```

**Comment by gkatsev** [comment]
That's very weird, I'm using it in a player and it seems to be working fine.
Also, http://videojs.com/getting-started/ points at the latest versioned url on the cdn :)

**Comment by tneaves** [comment]
@gkatsev http://docs.videojs.com/docs/guides/setup.html

**Comment by gkatsev** [comment]
Ah, yeah, those are statically generated and are old, not sure what to do about that.

**Comment by tneaves** [comment]
@gkatsev  Last question (sorry to bombard you): does the code I posted look accurate?

**Comment by gkatsev** [comment]
It looks correct. Could you put up the example on a jsfiddle or something and verify that it still is broken there and then post the link there if it does? Thanks.

**Comment by tneaves** [comment]
@gkatsev https://jsfiddle.net/09f509tg/ Looks like it is broken? I am not very good with JSFiddle -- check that the resources are being properly imported, there. It requires HTTPS, apparently.

**Comment by gkatsev** [comment]
@tneaves I updated your example to show how you can hide the volume button: https://jsfiddle.net/09f509tg/1/

**Comment by gkatsev** [comment]
Last updated a month ago. Closing for now. If still an issue, we could reopen.
