### ISSUE TITLE
Duration Live Not Showing

### ISSUE THREAD

**Issue by progredior** [videojs/video.js#2878]
When playing RTMP, LIVE control is not displayed, tested with 5.3.0 Pre-release, 5.2.4 and 5.0.0

Class remains <div class="vjs-live-control vjs-control vjs-hidden">

Streamed with nginx (1.9.7), also double checked LIVE duration works fine in JW Player, it does.

**Comment by gkatsev** [comment]
Would you happen to have an example or could you put together than example? Thanks.

**Comment by progredior** [comment]
Sure, here it goes...

http://videojsrtmp.s3-website-us-east-1.amazonaws.com

**Comment by gkatsev** [comment]
I'm actually not seeing it show live with either player.
In firefox:
![firefox players](https://cldup.com/LZ8pboy3Zk.png)

Trying to get the duration from both players I get `0` from videojs and `NaN` from jwPlayer.

Looks like we treat Live playback when the duration is set to Infinity or when the duration is negative (https://github.com/videojs/video.js/blob/a601fbb83fdc442f30f09ca15ff55b04c3e7c91d/src/js/player.js#L1322-L1325) but not when it's just `0`. I'm not positive that we can reliably treat `0` duration as Live on a consistent basis.

**Comment by progredior** [comment]
1.) Under what other conditions could video return 0?
2.) Is there a solution to force LIVE via components? (jQuery hacks excluded)

**Comment by gkatsev** [comment]
You can add `vjs-live` class to the player and then call `videojs.players['really-cool-video'].controlBar.liveDisplay.show();` since the liveDisplay won't show itself when the class is added unless duration is infinity.

**Comment by progredior** [comment]
OK solved that with custom controls, however poster image doesn't show up.

Supposedly that was taken care of since 4.0

https://github.com/videojs/video.js/issues/161#issuecomment-21218690

**Comment by tankerkiller125** [comment]
I also have the problem with live not automatically showing up on streams. (DASH plugin) I've had to do some really crazy work around just to get it to show.
