### ISSUE TITLE
googleusercontent redirect to google video

### ISSUE THREAD

**Issue by hide88** [videojs/video.js#2879]
anyone here knows how this is done?

1. https://lh3.googleusercontent.com/tvSBBRbfQZIypwiSJmkcRmO2fEX_jsiYrhS27x3Q59nJ=m22
2. https://r5---sn-npo7zn7z.googlevideo.com/videoplayback?id=c8f3a1ef3b2af2b6&itag=22&source=webdrive&begin=0&requiressl=yes&mm=30&mn=sn-npo7zn7z&ms=nxu&mv=m&nh=IgpwcjAyLnNpbjAzKgkxMjcuMC4wLjE&pl=16&mime=video/mp4&lmt=1448942741033927&mt=1449164761&ip=219.74.182.130&ipbits=8&expire=1449193687&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,nh,pl,mime,lmt&signature=32BB6D35F324BC814325FED2F234AE22C1737777.17E803C2BC03796D1A9D343D7E0BD2157E53D340&key=ck2

using link 1 to redirect to link 2. been searching on google but still get no answer to this.

**Comment by mmcc** [comment]
Sorry, but this is out of our wheel house. Good luck!

**Comment by robertdo** [comment]
@hide88 Where did you get the googleusercontent link from?
