### ISSUE TITLE
Vertical Volume Control

### ISSUE THREAD

**Issue by jemoreno** [videojs/video.js#2881]
I see that vertical volume control was addressed in 5.2.4, however, I can't seem to find an easy way to add it without adding a lot of code.  Is there a simple parameter or flag I can add when video.js initializes to force the control bar to act accordingly?

**Comment by gkatsev** [comment]
You should be able to just give it the option on the player:
```js
let player = videojs('myel', {
  controlBar: {
    volumeMenuButton: {
      inline: false
    }
  }
};
```
As always, we need to do better with documentation. Let me know if that works.

**Comment by jemoreno** [comment]
that works, thank you

**Comment by gkatsev** [comment]
No problem.

**Comment by maluklo** [comment]
Evaluate new skin video-js-6.2.4

https://github.com/maluklo/Skin-video-js-6.2.4
