### ISSUE TITLE
Need a way to access plugins created by inline options rather than calling their constructors directly

### ISSUE THREAD

**Issue by Soviut** [videojs/video.js#2884]
I've built a number of plugins that I'm configuring using a single options object:

``` javascript
var player = videojs('player', {
    plugins: {
        firstPlugin: { ... },
        secondPlugin: { ... }
    }
});
```

The problem is, I can't figure out how to access the plugins when they're created this way, as opposed to calling their constructors directly:

``` javascript
var player = videojs('player');
var first = player.firstPlugin({ ... });
var second = player.secondPlugin({ ... });
second.doSomethingToThisPlugin(...);
```

Is there some way I can access the plugins that have been attached to the player?

**Comment by gkatsev** [comment]
Yeah, plugins right now are pretty loosely defined, something I would like to get fixed as soon as possible.
If the plugin returns a new object for interaction then there's really nothing you can do.
What we've done before is had the plugins replace their namespace with the new object you interact with. For example: https://github.com/videojs/videojs-contrib-ads/blob/master/src/videojs.ads.js#L459-L460

**Comment by Soviut** [comment]
The namespace replacement is interesting, but it feels a bit hacky and unpredictable. Wouldn't it make more sense to set aside a `player.plugins` attribute to store references to all the plugins? The `videojs.plugin()` registration might be a good time to do this.

**Comment by gkatsev** [comment]
That is a possibility. Though, I would want to really think through some options for what to do with plugins before committing to anything.
Currently, plugins are super simplistic and aren't given much help at all and each plugin needs to figure things out on their own. We're working on a new plugin generator that will help out scaffold a project that will be a videojs plugin but I would like to make more of a framework around plugins, maybe something akin to popcornjs's plugins.
Some of the things for plugins could come as minor updates in v5 but I feel like ultimately, there will probably be at least some breaking changes.

**Comment by Soviut** [comment]
I agree, however, storing references to all the plugins the way I suggested wouldn't be a breaking change, so it might be a good intermediate step between 5.0 and 6.0.

**Comment by gkatsev** [comment]
Yep, it won't be a breaking change but I would still want to have a better idea of what we want from plugins in the future before we're adding more stuff that we'll need to support at least through one more version. :)

**Comment by gkatsev** [comment]
Also, is there a reason why you're initializing the plugins in the config as opposed to afterwards progranmatically?

**Comment by Soviut** [comment]
The player is part of a larger video site so on the player page I wanted to consolidate the player configuration options into a single payload. That makes it easier to populate and easier to expand upon when some of the future planned plugins are built.

**Comment by gkatsev** [comment]
I believe that the new Advanced Plugins in 6.0 allow you to handle this better but storing the state on the instance of the plugin. See http://docs.videojs.com/tutorial-plugins.html
