### ISSUE TITLE
Video Js 5.3.0 caption/subtitle not showing

### ISSUE THREAD

**Issue by hide88** [videojs/video.js#2885]
tried using version 5.3.0 but my video caption/subtitle does not appear. i have no problem when using version 4.11.4 .. here are the links for both version.

4.11.4 - http://example-video-js.blogspot.com
5.3.0 - http://example-video-js-530.blogspot.com

<track kind="subtitles" label="English" src="https://googledrive.com/host/0B9MfgZ0-qZZzRG0wOTlzUmFwNVk/English.vtt" srclang="En" default="default" />

**Comment by hartman** [comment]
"Cross-origin text track load denied by Cross-Origin Resource Sharing policy."

**Comment by gkatsev** [comment]
Yep, you need to have CORS headers on the vtt files.
Also, you probably need to add the `crossorigin` attribute to the video element. See #1888.
Closing for now but if you have more questions, let us know.
