### ISSUE TITLE
Android - Crosswalk app: Fullscreen button not working

### ISSUE THREAD

**Issue by tonyawad88** [videojs/video.js#2887]
Hello,

I have an app running on Android using Crosswalk version 15. 
The problem is that when I click the full screen button, the whole page flickers and the video remains to play in **non**-full screen mode. If I hold my thumb on the full-screen button for a couple seconds it successfully goes to full screen, however hitting the full screen button once / tap once, doesn't work.

On iOS it works fine, iOS / Safari Mobile, same code base.

Any idea if there is a fix for this ?

Thanks,

**Comment by gkatsev** [comment]
Are you using crosswalk directly or via cordova? Also, what version of Android?
We've previously had issues with our button handling on browsers like the native android browser on samsung devices so we've just disabled custom controls there until we can figure out what's going on.
That might be an easy workaround as well.

**Comment by tonyawad88** [comment]
It's a cordova application built with the intel xdk using crosswalk for android. I also tried it using the stock android web browser and had the same issue. 
Cordova version: 5.1.1 (if it matters)
Android version: 5.1.1

I am also using a samsung device. Not sure if I am using custom controls. I'm using the out of the box features as far as I know.

Here's my HTML:
```html
<div class="row row-items my-animation" style="padding:0;position: relative;">

    <div ng-hide="isvideo">
        <img class="img-responsive featured_crsl_imgs" ng-src="{{AdDetails.ad_landscape}}"/>
    </div>
    <div ng-show="isvideo" class="videogular-container">
        <video id='myVideo' videodir controls class="video-js vjs-default-skin">
        </video>
    </div>

    <md-button aria-label="dtlsbackbutton" class="m-0 p-0 img-responsive btn-back-dtls"
               ng-click="$root.navBackFromDetails=true;HistoryBack();">
        <i class="fa fa-2x" style="color:#ffffff;"></i>
    </md-button>
</div>
```
**JS**
```javascript
//Fn.6 - Check if Video and if so display and videojs
    $scope.CheckIfVideo = function(AdDetails){
        if(AdDetails.url_path != undefined &&
            AdDetails.url_path != "" && AdDetails.url_path.indexOf('mp4')>-1){
            $scope.isvideo = true;
            var setupOpt = {
                'controls' : true,
                'autoplay' : false,
                'preload' : 'metadata',
                'poster' : AdDetails.ad_landscape,
                'width' : '300',
                'height': '300'
            };

            //inject $sce to use any url, or fetch url from http request
            var vidSrc = $sce.trustAsResourceUrl(AdDetails.url_path);

            //create video js player dynamically
            videojs( 'myVideo', setupOpt, function(){
                $scope.vid = videojs( 'myVideo' ).src([ {type: "video/mp4", src: vidSrc} ]);
                $scope.vid.on("ended", function(){
                });
            });
        }
    }
    $scope.trustSrc = function(src) {
        console.log($sce.trustAsResourceUrl(src));
        return $sce.trustAsResourceUrl(src);
    };

    //Scope Destroy
    $scope.$on('$destroy', function() {
        if($scope.vid != undefined){
            $scope.vid.dispose();
        }
        $scope.AdDetails="";
        $scope.favorites.$destroy();
    });


    //II - Scope Functions
    var init = function () {
        $scope.AdDetails = JSON.parse(sessionStorage.getItem("AdDetails"));
        $scope.CheckIfVideo($scope.AdDetails);
        CheckIfIsFavorite($scope.AdDetails);
    };
    $timeout(function () {init();}, 120);
```

Thank you !

**Comment by tonyawad88** [comment]
@gkatsev Any idea if this is on the radar to be looked at?
Here's a snap if it helps. Please let me know if you need more from me on this.

Basically a tap/click on full screen button causes it to go on full screen for like 100ms then go back to non-full screen. However a long-tap on full-screen button for 2 or 3 seconds makes it successful...

Thanks

![video_js_bug](https://cloud.githubusercontent.com/assets/3638322/12876213/cdcb4d1c-cdca-11e5-8714-ede8ca267d9d.gif)

**Comment by chancezeus** [comment]
Ran into this myself and rememebered one thing, just like me you seem to be using Angular Material. Angular material implements it's own "FastClick" like implementation which triggers a second click, simply catching the "touchstart"/"touchend" events on the videojs element and "stopPropagation" will make prevent this synthetic click from happening...

**Comment by gkatsev** [comment]
If that is indeed the case, then there's nothing that videojs can do about it. And based on the flicker, it seems like that could be the problem.
Going to close this for now but please update if this isn't the case and we'll re-open.

**Comment by hartman** [comment]
It seems @chancezeus is referring to https://github.com/angular/angular.js/issues/6251

**Comment by tushargosalia** [comment]
@gkatsev @hartman  I'm also facing the same issue, but I'm not using the angular-material..I'm developing my app using `Ionic`. Please help.
