### ISSUE TITLE
Fix the hover state for themes

### ISSUE THREAD

**Issue by aolko** [videojs/video.js#2890]
```
/*hover fix*/
.video-js:hover .vjs-big-play-button,
.video-js .vjs-big-play-button:focus {
  outline: 0;
  background-color: $primary-background-color;
  background-color: rgba($primary-background-color, 0.5);
  -webkit-transition: all 0s;
  -moz-transition: all 0s;
  -o-transition: all 0s;
  transition: all 0s;
  }
```

**Comment by gkatsev** [comment]
I don't follow what this is supposed to be doing or fixing.
Can you please elaborate on the original issue you encountered and how this fixes it?
Also, please include version of videojs you're using and what browser and OS versions you used.

Thanks.

**Comment by aolko** [comment]
The response was so slow i might forget what was the __exact__ issue

**Comment by gkatsev** [comment]
I apologize for the long wait. Issues fall through the cracks and the ones without a lot of detail tend to get ignored first. Best to always be as details as possible. Better have extra information than not enough.

If you remember what the issue was, please post a comment.

**Comment by aolko** [comment]
it seems like it changes color to a "darker" variation and should fix sudden mousein transition(not fadein) (but it wont)
