### ISSUE TITLE
issue with windows 7 firefox 42

### ISSUE THREAD

**Issue by supersonicBlonde** [videojs/video.js#2891]
Hello

On windows 7, firefox 42, console logs a javascript error : improper value of height : NAN.
Can someone help ?
Thanks :)

**Comment by gkatsev** [comment]
Hi,
Can you provide some more information like what version of videojs used? Also, it would be even better if you can get together a [reduced test case](https://css-tricks.com/reduced-test-cases/).

**Comment by supersonicBlonde** [comment]
Hello Thanks for replying.

 

I use Video js 5.3 with bigvideo.js

 

I will do a reduced test case J

 

 

 

Nina Presotto 




 <http://ninapresotto.com/> 

 <http://ninapresotto.com/> ninapresotto.com

 

Tel: + 33 (0)6 64 24 45 96

 

De : Gary Katsevman [mailto:notifications@github.com] 
Envoyé : lundi 7 décembre 2015 17:52
À : videojs/video.js <video.js@noreply.github.com>
Cc : Nina <contact@ninapresotto.com>
Objet : Re: [video.js] issue with windows 7 firefox 42 (#2891)

 

Hi,
Can you provide some more information like what version of videojs used? Also, it would be even better if you can get together a reduced test case <https://css-tricks.com/reduced-test-cases/> .

**Comment by gkatsev** [comment]
None of the HTML went through. Would you be able to put the example on a site like jsfiddle.net?

**Comment by supersonicBlonde** [comment]
You can check the basic webpage provided by bigvideo.js on 

 

http://ninapresotto.com/ge/test.html

 

 

does not work on firefox 42 – windows 7 

 

Thanks J

 

 

Nina Presotto 




 <http://ninapresotto.com/> 

 <http://ninapresotto.com/> ninapresotto.com

 

Tel: + 33 (0)6 64 24 45 96

 

De : Gary Katsevman [mailto:notifications@github.com] 
Envoyé : lundi 7 décembre 2015 19:46
À : videojs/video.js <video.js@noreply.github.com>
Cc : Nina <contact@ninapresotto.com>
Objet : Re: [video.js] issue with windows 7 firefox 42 (#2891)

 

None of the HTML went through. Would you be able to put the example on a site like jsfiddle.net?

**Comment by mister-ben** [comment]
The player on http://ninapresotto.com/ge/test.html is not video.js

**Comment by supersonicBlonde** [comment]
Yes indeed. I switched to mpeg dash.

Thanks.

 

Nina Presotto 




 <http://ninapresotto.com/> 

 <http://ninapresotto.com/> ninapresotto.com

 

Tel: + 33 (0)6 64 24 45 96

 

De : mister-ben [mailto:notifications@github.com] 
Envoyé : mardi 8 décembre 2015 15:47
À : videojs/video.js <video.js@noreply.github.com>
Cc : Nina <contact@ninapresotto.com>
Objet : Re: [video.js] issue with windows 7 firefox 42 (#2891)

 

The player on http://ninapresotto.com/ge/test.html is not video.js
