### ISSUE TITLE
Is their any API can load HLS ?

### ISSUE THREAD

**Issue by dbFlower** [videojs/video.js#2892]
I updated video.js from 4.x to 5.x but some plugins don't work now.
In the old version I can use player.loadTech(techName, {src: source}) to load HLS . 
But now I didn't know how to load . I mean that I want to change resolution while playing.

**Comment by tankvn** [comment]
FYI
https://github.com/mangui/flashls

**Comment by gkatsev** [comment]
You need to make sure that you upgrade your plugins to versions that support videojs. `contrib-hls` does have a version that works with videojs. Check out that project if that' what you were using.
Also, you shouldn't be using `loadTech` as that's meant to be a private method. Instead, you should use `.src`:
```js
player.src({
  src: 'http://url.to/your.m3u8',
  type: 'application/vnd.apple.mpegurl'
});
```
Make sure that you have the `type` in there.

**Comment by dbFlower** [comment]
@gkatsev  Thanks, I tried `player.src({type: 'application/vnd.apple.mpegurl'})` and now it works

**Comment by dbFlower** [comment]
@tankvn  Thanks a lot!
