### ISSUE TITLE
IE9 Not implemented Error

### ISSUE THREAD

**Issue by cdeutsch** [videojs/video.js#290]
When you guys check for HTML5 video support (canPlayType) you should wrap it in a try catch because some versions of IE9 will throw an error. It mostly effects Windows Server without "Desktop Experience" installed, but I have a Windows 7 machine with the same issue:
https://github.com/Modernizr/Modernizr/issues/224

**Comment by aariacarterweir** [comment]
Possible regression? This issue seems to be happening again.

**Comment by lemonhead** [comment]
I have the same issue on SauceLabs as well. Could please anyone help. It happens on your project page as well so ist is a video.js bug.

**Comment by eavestn** [comment]
Yeah, @heff this is still happening: 
![capture](https://cloud.githubusercontent.com/assets/5882519/13121892/51932ffc-d582-11e5-86bd-8986ac7e70a4.PNG)

This is in IE on Windows Server 2008 without _Desktop Experience_ enabled. Would be great if my users didn't have to configure their server especially for the library.

**Comment by gkatsev** [comment]
I think this may be because the new sourcehandler work uses canPlayType without a trycatch.
