### ISSUE TITLE
How to use / initialize multiple players with dynamic id ( each with a unique id).

### ISSUE THREAD

**Issue by Viper177** [videojs/video.js#2904]
I have used player with dynamic ids (a unique id for each player). On my website I have 10+ players on the same page, some open in popups, some show in main post and some in comments, some video posts load using ajax. So for each player i have a different scenario on how to present them and in multiple sizes. Sizes is not an issue as it is controlled using css.

The problem is I am initializing players such that I am trying to initialize each player ( not sure if this should be done, but since there are various scenarios so i think its better if i initialize each player). I found once the very first player is initialize it is also initializing all players regardless of its "id".

Following is my code:

``` js
function initialize_video_player(elm_,player_id){

  var id_= player_id?player_id:elm_.attr("id"),
  player_elm = $("#"+id_),
  autoplay = player_elm.attr("auto_play"),
  if_autoplay = parseInt(autoplay)?true:false,
  overlay = document.createElement('div'),
  is_comment = player_elm.attr("is_comment"),
  $overlay = $(overlay);


  //add class to new div
  overlay.className = prepare_class(conf['videojs-video-detail']);

  var vid_player = videojs(id_, { controls: true, autoplay: if_autoplay, preload: "none" }, function() {
    //console.log('Good to go!');

    //this.play(); // if you don't trust autoplay for some reason

    // How about an event listener?
    /*this.on('ended', function() {
      console.log('awww...over so soon?');
    });*/

  });
//check if this element is created only once
var video_js_detail_elm = $("#"+id_).find(conf['videojs-video-detail']);
  if(!video_js_detail_elm.length)
  {
    if(!is_comment){
        //adding a div in player elm
        vid_player.el().appendChild(overlay);
    }
  }
  else
  {
    if(!is_comment)
    {
        //---- show/hide video detail info overly when on grid view ----//
        var battle_wrap = $("#"+id_).parents(".battle-wrap"),
        if_battle_wrap = battle_wrap.length?1:0,
        if_grid_view = if_battle_wrap?battle_wrap.attr("single_view"):1,
        video_detail_view_elm = battle_wrap.find(".battle_detail").clone();
        video_detail_view = video_detail_view_elm.addClass("vjs-video-detail");

        if(if_grid_view==0)
        {
          //console.log("video overlay div added to player")
          video_js_detail_elm.html(video_detail_view);
          video_detail_view.addClass("video-player-bottom");
          var battle_details = battle_wrap.find(".battle_detail").not(".vjs-video-detail");
          battle_details.addClass("none");

        }
    }

    vid_player.on('play', function () {

        video_js_detail_elm.addClass('none');
        video_js_detail_elm.find(".vjs-video-detail").removeClass("video-player-bottom");
        //console.log("video player play")
    });

    vid_player.on('pause', function () {

        video_js_detail_elm.removeClass('none');

      //  console.log("video player pause")
    });

    vid_player.on('firstplay', function () {
        //increment video view count when user start playing a video
        video_played_view(id_);

    });
    //-------------------- END ------------------------//
  }
}
```

I am using this function "initialize_video_player" every time my post is fetched via javascript and is initializing all players for all my scenarios.

A few questions:
1. How can i initialize player for each player/video? So that i can use player perfectly according to my need.
2. If above is not possible, what is a good way around?
3. In my code above for  "is_comment" variable, I do not need at have "overlay" div. If i use above code it is removing "overlay" from all the players. regardless of the condition, as it is initializing all the players at once.

**Comment by gkatsev** [comment]
> 1 How can i initialize player for each player/video? So that i can use player perfectly according to my need.

Basically how you have it, you just want to make sure that your id attributes are unique. Or you can give videojs a direct reference to a video element and it'll go from there.

> 2 If above is not possible, what is a good way around?

The above should be possible.

> 3 In my code above for "is_comment" variable, I do not need at have "overlay" div. If i use above code it is removing "overlay" from all the players. regardless of the condition, as it is initializing all the players at once.

Not sure what you mean.


Also, if you can put up a [reduced test case](https://css-tricks.com/reduced-test-cases/) on a site like jsfiddle, it'll make it a lot easier to understand what you mean and help out.

**Comment by Viper177** [comment]
@gkatsev Thanks for writing back. Yes I am giving all players a unique id and also triggering this function for them all. And my all players are working as well. 

But my all players are initializing at once. Means they are not id dependent. After my first player is initialize, i see console messages for all others like below:
VIDEOJS: WARN: Player "566909b393faa" is already initialised. Options will not be applied.
VIDEOJS: WARN: Player "566909b39267c" is already initialised. Options will not be applied.
VIDEOJS: WARN: Player "566909b39589e" is already initialised. Options will not be applied.
VIDEOJS: WARN: Player "566909b396bf2" is already initialised. Options will not be applied.

This could only mean that plugin instead of initializing a single player when an id is passed to it, it is initializing all the players at once. Right? So if I want a few of other player work differently it won't allow me to do so. 

Or I have to use a separate function for all other players but this is not a standard procedure to follow.

I haven't used fiddle until now. I'll check how it work.

**Comment by gkatsev** [comment]
You can check whether a player is already created by looking for it in `videojs.players`.
