### ISSUE TITLE
Unable to set options for a component. ( volume vertical )

### ISSUE THREAD

**Issue by TiagoEsterisco** [videojs/video.js#2907]
Hello, 

I am trying to do this: 
```
            this.video = videojs(video, {
                controls: true,
                autoplay: false,
                preload: 'metadata',
                children: {
                    controlBar: {
                        children: {
                            volumeMenuButton: {
                                volumeBar: {
                                    vertical: true
                                }
                            }
                        }
                    }
                }
            });
```

But `this.video.ready(function() {` is never ready. 
what am I missing? 

I know it works, because when I only set ```controls: true,
                autoplay: false,
                preload: 'metadata',``` it works 

Thanks.

**Comment by TiagoEsterisco** [comment]
On the latest version (`5.3.0`) it doesnt work: http://jsbin.com/zuciyubone/2/edit?html,css,js,output
On the (`4.10`) it is working fine. http://jsbin.com/cahikudavo/1/edit?html,css,js,output 

Did video.js change the way we set this?

**Comment by hartman** [comment]
```
videojs( video, {
    controlBar: {
			volumeMenuButton: {
				vertical: true, //this might be optional when you specify inline false....
				inline: false
			}
		}
  }
```

**Comment by TiagoEsterisco** [comment]
Perfect thank you @hartman! It worked. Where did you find that? I couldn't find any documentation about this.

**Comment by hartman** [comment]
It was discussed in another ticket before. I'm not sure why it breaks silently. Perhaps because mergeOptions (with the defaults), break them now that  children are supposed to be an array [].
