### ISSUE TITLE
Certain RTMP urls are not supported.

### ISSUE THREAD

**Issue by Liangfeiyu** [videojs/video.js#2909]
I use 5.3.0 which did not support such rtmp url below:
```
<source src="rtmp://live.mywebsite.com/test/test1?auth_key=4603425819-0-0-b68332d3ada166133e0b1dd9e5c32453" type="rtmp/flv"/>
```
Is there something wrong when dealing with such a url format?

**Comment by gkatsev** [comment]
@bdeitte any ideas? I know nothing about RTMP.

**Comment by bdeitte** [comment]
The URL above looks fine to me, and it should still work.  What type of errors are you getting?

**Comment by robbiegod** [comment]
got a link you can share?

**Comment by Liangfeiyu** [comment]
rtmp://live.realsion.com/test/test0?auth_key=1450011463-0-0-08dc9537a9b62f6b7043f5b5771bfba8
I use following code to play the rtmp url above which VLC works:
<link href="http://vjs.zencdn.net/5.3.0/video-js.css" rel="stylesheet" type="text/css">
<script src="http://vjs.zencdn.net/5.3.0/video.js"></script>
<video id="example_video_1" class="video-js vjs-default-skin" preload="none" width="640" height="480" autoplay="true" data-setup="{}"> 
<source src="rtmp://live.realsion.com/test/test0?auth_key=1450011463-0-0-08dc9537a9b62f6b7043f5b5771bfba8" type="rtmp/flv"/>
</video>

**Comment by mister-ben** [comment]
The token needs to be part of the connection string rather than the stream name. We use an `&` as separator between connection and stream, so that should look like

    rtmp://live.realsion.com/test?auth_key=1450011463-0-0-08dc9537a9b62f6b7043f5b5771bfba8&test0

FWIW the stream itself doesn't seem in good shape. Whether in video.js or in VLC I get short burts of playback between 30+ second pauses.

**Comment by Liangfeiyu** [comment]
Sorry it seem did not work for me, can you play this url which I've adjust the format as you said: rtmp://live.realsion.com/traffic/?auth_key=4603425819-0-0-b68332d3ada166133e0b1dd9e5c8d263&test1
I use the version of 5.3.0, could you please paste you code if you can.

**Comment by mister-ben** [comment]
Here you go. It doesn't seem to work with a trailing slash before the query string as you have in your last comment.

```
<link href="http://vjs.zencdn.net/5.3.0/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/5.3.0/video.js"></script>
<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" data-setup='{"techOrder":["flash"]}'>
  <source src="rtmp://live.realsion.com/traffic?auth_key=4603425819-0-0-b68332d3ada166133e0b1dd9e5c8d263&test1" type="rtmp/flv"/>
</video>
```

http://output.jsbin.com/cihika

**Comment by Liangfeiyu** [comment]
That's it! Thanks a lot for your patience. And I do hope VideoJS can deal with such full link without change its format one day. Thank you.
