### ISSUE TITLE
Fixed resolution/centered on large displays

### ISSUE THREAD

**Issue by ronbo613** [videojs/video.js#2911]
Using video.js in a fluid grid layout with a 640x360 video, everything works great until large displays where the video and poster are huge. Not much point in having a fullscreen option. Here is an example: http://www.watermanatwork.com/Mobile/KayakFishing/KayakFishingVideo/PacNWVideo/2014SalmonFishing/2014SalmonFishing.html
I've tried everything I can find to use CSS to limit the size of the video/poster, but not having much success. If a fixed size is used, I can't get the video/poster to center in the DIV.
Not being a coding expert, I appreciate any advice or insight into this issue so I don't go insane for the holidays.
Thanks.

**Comment by hartman** [comment]
#Video > .video-js {
max-width: 800px;
margin-left: auto;
margin-right: auto
}

Translated:
Inside the block named `Video`, give children with the classname `video-js`, a maximum width of 800px. Make the margins on either side equal (This takes care of the centering of a small block inside a large block).

**Comment by ronbo613** [comment]
That did the trick. I tried various combos of max-width and margins but just could not find the right solution.
Thanks hartman for your input, made my life a lot easier.

**Comment by ronbo613** [comment]
Thank you Derk-Jan for your assistance, I appreciate it.

Ron B

On Sun, Dec 13, 2015 at 6:31 AM, Derk-Jan Hartman <notifications@github.com>
wrote:

> #Video > .video-js {
> max-width: 800px;
> margin-left: auto;
> margin-right: auto
> }
>
> Translated:
> Inside the block named Video, give children with the classname video-js,
> a maximum width of 800px. Make the margins on either side equal (This takes
> care of the centering of a small block inside a large block).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/2911#issuecomment-164263287>.
>



-- 
*WatermanAtWork Website <http://www.watermanatwork.com>*  -
<http://watermanatwork.com/blog/>*Blog*

**Comment by gkatsev** [comment]
Also, I wanted to remind that in recent versions of Video.js, we have the `vjs-fill` class which makes Video.js conform to the parent element's size. Might make it easier to control then.
