### ISSUE TITLE
Can change rtmp live stream src

### ISSUE THREAD

**Issue by cherishsantosh** [videojs/video.js#2916]
Hello,
```html
<iframe width="100%" height="300" src="//jsfiddle.net/cherishsantosh/pK6fB/embedded/" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
```
trying to change src of live rtmp stream, aboue app have two button if I click on first button, first stream loading, but second button click nothing is happening, How can I load second stream?

**Comment by gkatsev** [comment]
You can use [`Player#src`](http://docs.videojs.com/docs/api/player.html#Methodssrc).
Should look something like:
```js
var player = videojs('myplayer');
player.src({
  src: 'rtmp://10.129.200.81/PanTestRoom/room1/Test'
  type: 'rtmp/mp4'
});
```

Though, I'm not seeing two buttons in your example. But basically, you want to set the `src` when the button is clicked.
Closing, but let us know if you have any more questions.

**Comment by cherishsantosh** [comment]
getting error 
TypeError: this.Od is not a function at t.src (http://localhost/flowplayer/video.js:95:86)

**Comment by gkatsev** [comment]
Do you have a live example? The fiddle you linked to above does not include the buttons optionality you were asking about. Also, what browser are you using and what version of videojs?

**Comment by cherishsantosh** [comment]
http://jsfiddle.net/cherishsantosh/e2ahsszp/#

**Comment by gkatsev** [comment]
I updated your example so that it doesn't throw errors: http://jsfiddle.net/gkatsev/e2ahsszp/2/
Now it just won't play which I think may be a similar issue to https://github.com/videojs/video.js/issues/2909

**Comment by cherishsantosh** [comment]
Finally issue is solved!! @legnaleurc @gkatsev very nice. Thanks.
