### ISSUE TITLE
inline volume menu button stays open on focus and doesn't hide on mouseout

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2918]
Found as part of https://github.com/videojs/video.js/pull/2638. The issue is that if you focus on the menu that shows up (i.e., if you click around the volume bar after hovering on the inline volume menu button and not the bar itself), it'll focus the menu button and thus it won't hide when the mouse leaves the area of the volume menu button. In #2638, we originally tried to `blur` the element on `mouseout` but this can be an issue if you tab into the volume menu button but then move the mouse. Instead, we should keep track whether we've entered elements with the mouse or the keyboard and only `blur` the element on `mouseout` when we entered it with the mouse. This way, if you tab into it with the keyboard and then move the mouse over it, it won't hide automatically.

Regular menus may also want to do a similar thing with how lock-showing works.

**Comment by gkatsev** [comment]
Should use `mouseleave` instead.

**Comment by adyballa** [comment]
I did it with a preventDefault on mousemove and mousedown in the VolumeMenuButton

**Comment by gkatsev** [comment]
I think this is fixed since we no longer use the volume menu button.
