### ISSUE TITLE
How to make VideoJS videos scale

### ISSUE THREAD

**Issue by cherishsantosh** [videojs/video.js#2921]
Hello,

I have a live rtmp stream, playing stream in VideoJS player, but problem is incoming stream size is less than player. How can maintain aspect ratio.

```html
<video align="center" id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="320" height="240" data-setup='{ "techOrder": ["flash"] }'>
<source src="rtmp://localhost/oflaDemo/final" type='rtmp/mp4'>
</video>
```
![screenshot from 2015-12-16 17 01 16](https://cloud.githubusercontent.com/assets/1272361/11840055/c7ec10ce-a418-11e5-9191-517ad5f8e5e0.png)

using video-js.css and video.dev.js version (Video.js v4.7.3). <b>publishing stream using oflademo (Red5 server) 320X240</b>

**Comment by kahwee** [comment]
The new video.js v5 scales. You may want to upgrade.

If you're stuck at an older version, you can try this http://coolestguidesontheplanet.com/videodrome/videojs/

**Comment by mmcc** [comment]
Unfortunately this is just a bug with RTMP / Flash. You can follow the issue on the [swf](https://github.com/videojs/video-js-swf/issues/55), but I seriously doubt much effort is going to be expended to fix this one.
