### ISSUE TITLE
not allowed to load local resource: file:///Users/..."

### ISSUE THREAD

**Issue by surwasesandy** [videojs/video.js#2922]
Accessing local  file out side of  project but its shows the error not allowed to load local resource: file:///C:/Users/.../video.mp4"

**Comment by mmcc** [comment]
If you're trying to use the Flash fallback, there are security restrictions there: #1322

Otherwise, we need more information, but it sounds like the error is pretty straight forward. Can you load the video directly into a raw video element? If you access it from your browser does it work?

**Comment by mmcc** [comment]
Btw, just closing this one since it seems like it's not a VJS issue specifically, but we can keep the conversation going.

**Comment by gkatsev** [comment]
Also, if you're loading in the website from http, you can't load in videos or things from file:/ due to security restrictions in browsers.

**Comment by surwasesandy** [comment]
but i want to load file:// so i what i do give solution
