### ISSUE TITLE
Component#name cannot be called

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#2925]
If you add a child component by passing the component directly to `addChild`, it attempts to call the `name()` method of that component. However, because components are functions, they have a `name` property and you get an error.

```js
this.addChild(MyComponent); // Uncaught TypeError: component.name is not a function
```

I'll reference a test case later.

**Comment by gkatsev** [comment]
`addChild` takes in a string as the component name or an instance of a component it does not currently accept constructors of components.

**Comment by misteroneill** [comment]
Yep, I realized that about 2 minutes after posting this.
