### ISSUE TITLE
Firefox blocks connection while loading huge video file in HTML5 player

### ISSUE THREAD

**Issue by CharlotteDunois** [videojs/video.js#2927]
Hello

I am experiencing a weird problem and I can only reproduce this in Firefox and the HTML5 player. In chrome everything works fine (only that he polls the video file twice (I can see two calls in the networks tab, the first one as cancelled) but other than that fine).

I tested that with Firefox 42.0 on Windows 7 (on two different machines) and Chrome 47.0.2526.80 on Windows 7.

My Problem: If I stream a huge video file, such as one with a size of 985MB, with the HTML5 video player, after some time Firefox blocks all other connections. That means I can't load any other websites, I'm just seeing circles. If I use the flash player everything seems to work fine.

I am using video.js v4.12.12 (Yup, rather old but you shouldn't change a working system, right?), I also tried to upgrade to a newer version before. But I got more issues than I actually got more features, which is why I disregarded that without solving since v4.12.12 was working without any problems before.
I am not sure if upgrading would fix the problem. It could also be a firefox bug (also most likely is), but I want to confirm before that it is an issue with video.js v4.12.12 and not with the browser.

I'll link now the file with the 985MB filesize so you can test it. Yes, it's actually a electro/house mix, but you can just turn off the sound and browse meanwhile it's streaming. It does take a while until FF blocks other connections, so around 5-10mins does it take.

Web link to the html5 player stream: https://www.anitube.ch/watch/-zD2u8MrjnGR?external
Web link to the flash player stream: https://www.anitube.ch/watch/-zD2u8MrjnGR?external&flash=1
Link to the video.js javascript file (edited, added some things and merged with other javascript files regarding video.js): https://www.anitube-nocookie.ch/js/video.js?nocache
Reduced test case on jsbin with v4.12.12: http://output.jsbin.com/noqijorula

If you could look at that issue, that would be great.

Regards,
Charlotte

**Comment by thomaspeeters** [comment]
How are you serving the file? Is it truly streaming or is this progressive download?
Seeking doesn't work for me in Chrome (`A network error caused the video download to fail part-way`), so I'm thinking it might have to do with the way the file is being served.

**Comment by CharlotteDunois** [comment]
With PHP. Even if I let Nginx serve the file, it doesn't change. Seeking used to work in Chrome, looks like something broke meanwhile. Seeking still works in Firefox, response from server looks fine too. Well, this issue is with Firefox only anyway.

**Comment by mmcc** [comment]
> Yup, rather old but you shouldn't change a working system, right?

It's going to get harder and harder to get support from the community, but I know what you mean :)

The stream isn't working at all for me in ~~Chrome~~ (scratch that, started working after some bizarre behavior such as negative current time and a loooooong loading time) or Safari and in Firefox (v43 on OS X)....it works flawlessly. I honestly think @thomaspeeters is on the right track, everything is point to this being an issue with how the file is served, and again, just to be honest, I've never once seen "serving the file via PHP" not turn out to be the source of the problem on this tracker. I know you've probably heard this before, so my apologies if I'm preaching to the choir and you have reasons for needing to do it, but serving media assets (especially large ones), is simply a job best left for a traditional web server.

I refreshed the HTML5 test in Chrome so I could check out the assets in the network tab, but now none of it's loading at all. All of the `anitube` examples eventually time out.

Assuming that's just a temporary issue, a file this large really does make more sense for a format like HLS or DASH. If you can't go with one of those, I'd be *absolutely certain* that your custom server is handling byte-range requests correctly.

**Comment by CharlotteDunois** [comment]
@mmcc I've tried to serve the files with Nginx, which didn't make a difference to serving the files with PHP. The byte-ranges are getting correctly handled, since Chrome doesn't bitch around (anymore). Chrome is very picky about that. :(
But I'll look into HLS and DASH.

**Comment by Abdurraheem** [comment]
Hi,
Why  this happens only in Chrome browser "a network error caused the video download to fail part-way"? Please help to resolve

**Comment by Abdurraheem** [comment]
The video is playing nicely but when i click on progress bar for forward or backward it gives the error "a network error caused the video download to fail part-way "
