### ISSUE TITLE
segment files stop downloading but new m3u8 files keep coming

### ISSUE THREAD

**Issue by billybobilly** [videojs/video.js#2929]
video.js version 5.4.4
videojs.hls.min.js  version 1.3.1
videojs.css  version 4.12.15

LIVE stream
All browsers
Occurs direct from our origin as well as from our CDN's edge
Desktop only.  Android does not have same problem.

Video plays for a short time (random, but usually about 5 or six segments) and then stops.  The ts files download and play normally for a while, then they stop coming.

m3u8 file continues to be downloaded (and it is not a cached version, each file is fresh) but no additional ts files are downloaded.

Resolved the issue by rolling back to these versions:

video.js  version 5.3.0
vidoejs.hls.min.js  version 1.2.2

**Comment by gkatsev** [comment]
Can you re-open this issue again the [contrib-hls](/videojs/videojs-contrib-hls/issues) project? Thanks.

**Comment by zymtx5g79k** [comment]
video.js version 5.10.4

LIVE stream
All browsers

Too many stalled requests per segment. It requests segments when video was paused.
After video stopped (video 30 seconds long), requests repeats more then 10 minutes for the same segment.

Source: `http://dev.rolik.co/api/posts/598/hls/video.m3u8`
Type: `application/x-mpegURL`
