### ISSUE TITLE
Using Function.prototype as an event handler has bad effects!

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#2930]
In a hack we were working on, we realized that `Function.prototype` was getting passed to `on()` at one point. However, because `on()` assigns a `guid` to the function, it was breaking event bindings after that point because all functions which didn't already have `guid`s could not be bound!

Also, stop using `Function.prototype` as a noop to avoid these sorts of issues in the future.

**Comment by gkatsev** [comment]
We stopped doing that.
