### ISSUE TITLE
Fullscreen & AspectRatio with Youtube video

### ISSUE THREAD

**Issue by Guillom** [videojs/video.js#2935]
Hello,

With videojs-youtube :
I need the YouTube video to scale/resize fullscreen depending on the browser size or device width.

Actually, I have black borders on screen resize.
Here's my pen : http://codepen.io/blancfonce/pen/obxVXm

Any tips ?
Thx

**Comment by mister-ben** [comment]
Closing in favour of eXon/videojs-youtube#348
