### ISSUE TITLE
Language files not on CDN for 5.4.5

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#2936]
http://vjs.zencdn.net/5.2.1/lang/nl.js works, http://vjs.zencdn.net/5.4.5/lang/nl.js doesn't.

**Comment by gkatsev** [comment]
5.4.5 hasn't been published to the CDN yet in general. When publishing a new version, I've been publishing it as a "prerelease" or "next" tag to github and npm. About a week later or something, assuming everything is going well, it'll get promoted to a full release and "latest" tag and which point it'll get published to the CDN.
5.4.5 should probably get pushed some time this week.
Thanks.

**Comment by thijstriemstra** [comment]
Looks like 5.4.6 has been created. But now both http://vjs.zencdn.net/5.4.5/lang/nl.js and http://vjs.zencdn.net/5.4.6/lang/nl.js are not available.
