### ISSUE TITLE
Can't click play button on video with link overlay on iOS9 / iPhone

### ISSUE THREAD

**Issue by dczaretsky** [videojs/video.js#2937]
I have dynamically created a video, and set a link on the video when you click it. The link is added below the control elements using insertBefore() so that the video controls remain on top of the &lt;a&gt; element and are clickable. For iPhone with iOS 8 and below, to get the play button to remain on top I had to additionally set the z-index for the native play button as follows:

<code>
video::-webkit-media-controls-start-playback-button
{
    z-index: 2147483647 !important;
}
</code>

However, in iOS 9 on iPhone, the native video play button is no longer clickable. Instead the link is clicked. I have tried everything, and can't seem to get the native play button to render on top of the <a> element. 

I was able to confirm that the native media controls are valid by setting other properties on like display:none which hide the button, or position:fixed which moved the play button out of the video frame and it became clickable. So it seems that only the z-index is not working.  Additionally, the big play button on iPad / iOS 9 works correctly in that the play button is on top of the <a> element. This leads me to believe it could possibly be a bug videojs support for iOS 9 / iPhone.

Here is the code I used to create the video and link:

&lt;video id="video" class="video-js vjs-default-skin"&gt;
&lt;source src="www.example.com/movie.mp4" type="video/mp4"&gt;
&lt;/video&gt;

&lt;script type="text/javascript"&gt;
videojs("video", {"techOrder":["html5","flash"]}, function(){
    var player = this;
    player.controls(true);
    player.preload(true);
    player.enableTouchActivity();
    player.fluid(true);
});

$(document).ready( function() {
    videojs("video").ready( function() {
        var clickthrough = window.document.createElement("a");
        clickthrough.href = "http://www.example.com";
        clickthrough.target = "_blank";
        this.el().insertBefore(clickthrough, this.controlBar.el());
    });
});
&lt;/script&gt;

**Comment by dczaretsky** [comment]
In case others are having the same problem, a simple hack I used to get around the problem was to implement the css below to hide the native play button on iPhone and instead enable the videojs play button:

video::-webkit-media-controls-start-playback-button
{
    display: none;
}

.video-js.vjs-controls-enabled .vjs-big-play-button
{
    display: none;
}

.video-js.vjs-controls-enabled.vjs-paused .vjs-big-play-button
{
    display: block;
}

**Comment by hartman** [comment]
Why would you insert a link though ? I mean, wouldn't a click handler on the player element be much simpler in this case ? Just wondering.

**Comment by dczaretsky** [comment]
Videojs creates multiple overlays, like controls, error messages, etc based on how the video is configured and stylized. The only way I see that you can properly distinguish areas and elements in the video is by creating separate overlays. I'm not sure that you can attach a click event to any particular part of the video without affecting the  ability to interact with the other overlays, like the controlls.

**Comment by phommata** [comment]
Using fluid video css fixes, and videojs z-index fix I was able to make the iOS play button clickable.

<video id="my-video" class="video-js vjs-big-play-centered" controls preload="auto" width="100%" height="100%" poster="" data-setup="{}">

			.video-js {
				-moz-user-select: none;
				background-color: #000;
				box-sizing: border-box;
				color: #fff;
				display: block;
				font-family: Arial,Helvetica,sans-serif;
				font-size: 10px;
				font-style: normal;
				font-weight: normal;
				line-height: 1;
				padding-bottom: 56.25% !important;
				padding-left: 0;
				padding-right: 0;
				padding-top: 0;
				position: relative;
				vertical-align: top;
			}
		
			.video-js .vjs-tech {
				height: 100%;
				left: 0;
				position: absolute;
				top: 0;
				width: 100%;
				z-index: 9999;
			}
