### ISSUE TITLE
HLS stream doesn't load (iOS & Android works well)

### ISSUE THREAD

**Issue by cowanmax** [videojs/video.js#2938]
Hi All!
I can't understand why but HLS stream doesn't work on desktop (windows) but works well on iOS and Android tablets. You can look at our website - http://www.bulgartravel.tv/videojs
I have installed videojs like in your example - http://videojs.github.io/videojs-contrib-hls/
Thanks!

**Comment by gkatsev** [comment]
Everything seems to be set up correctly. The one thing that's missing are CORS headers on the m3u8 file. It's required for contrib-hls to work: https://github.com/videojs/videojs-contrib-hls/#hosting-considerations

**Comment by cowanmax** [comment]
It works now :) Thanks ! But sometimes it plays with little stops (video), sound is ok. What you can recommend with it?

**Comment by gkatsev** [comment]
Glad you got it working. If you have specific issues with HLS not working on desktops, it's best to write up exactly what issues you're having and open [an issue against the contrib-hls project](https://github.com/videojs/videojs-contrib-hls/issues). Also, make sure you're using the newest version of contrib-hls.
