### ISSUE TITLE
v5.4.5 breaks vertical volume bar

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#2942]
v5.4.5 breaks vertical volume bar, see attached:-
![vjs545 vertical volume error](https://cloud.githubusercontent.com/assets/11416714/11944893/ba7c9210-a841-11e5-9314-6af2c84459c0.jpg)

**Comment by gkatsev** [comment]
Dammit, lol. Thanks for catching that. I'll look for a fix.

**Comment by gkatsev** [comment]
Thanks. It should be fixed in 5.4.6. Let me know if it's still broken.

**Comment by richardbushell** [comment]
Thanks, that fixed it.

**Comment by gkatsev** [comment]
Awesome, thanks for confirming.
