### ISSUE TITLE
Is it possible to change markup for big play button?

### ISSUE THREAD

**Issue by smohadjer** [videojs/video.js#2944]
Does videojs allow any customization of markup that is generated by default? I would like to use a simpler markup for big play button, so rather than this:
`<button class="vjs-big-play-button"><span class="vjs-control-text icon-play">Play Video</span></button>`

use this:
`<span class="vjs-big-play-button">Play Video</span>`

I've removed attributes apart from class attribute for sake of simplicity, but they can all stay as before. I don't want a hack that makes it difficult to upgrade to next version of videojs and I don't want to lose the default functionality of big play button.

**Comment by gkatsev** [comment]
Is there a particular usecase for doing this? One of the reasons why it's "heavy" markup is to support the play icon but also be accessible. It's also consistent within the rest of components that videojs uses.

We don't currently support it and unlikely to support it unless there's a really good use case. It's probably better to create your own custom big play button instead. You could subclass our big-play-button (https://github.com/videojs/video.js/wiki/5.0-Change-Details#videojs-50-subclassing-examples) and then add it to the player and hide the default one.

Closing as this probably won't need a change in core, but please reply if you have more questions or a more detailed usecase. Thanks.
