### ISSUE TITLE
Can't set currentTime in Firefox when the player display is set to "none"

### ISSUE THREAD

**Issue by Billybobbonnet** [videojs/video.js#2952]
Hello,
I designed a feature to play a compilation of several chunks extracted from several videos. In order to provide instant transitions between the chunks, I am using 2 different instances of videojs. One is passive, i.e.  hidden and preloading the next chunk, the other one is active, i.e displayed and playing the current one.

The steps are as follow:

- Initial loading
   - Player 1 is set as active
   - Player 2 is set as passive
   - Both sources are loaded
   - Once playerState()===4 for both players, player1.play()
   - Once player 1 currentTime() === end of the chunk, call "Switch player"
- Switch player
   - Active player is set as passive
   - Passive player is set as active
   - Passive player source is changed to the next chunk source
   - Passive player currentTime is set to the next chunk start
   - Once Active player currentTime() === end of the chunk, call "Switch player" and stop listening (remove the timechanged event hook on the current Active player)

When I use chrome, everything works smoothly. When I use Firefox, I can't use `currentTime()` even if the player is instanciated. If I do, I get the following error:

> VIDEOJS: DOMException [InvalidStateError: "An attempt was made to use an object that is not, or is no longer, usable"
code: 11

However, if I wait for the "loadedmetadata" event, it works smoothly but with a delay of approximatively one second (I assume this is the time needed to receive the event):

```javascript
 passivePlayer.one("loadedmetadata", function(){
    passivePlayer.currentTime(chunk[index].start)
 });
```

Note that both player are correctly instanciated.

**Comment by gkatsev** [comment]
I believe this is just how the video element works. You cannot seek before the element knows anything about the video, so, the recommended approach would be to listen to `loadedmetadata`.
Here, when using `loadedmetadata` event, it works: https://jsbin.com/fuxoge/1/edit?html,js,console,output
But here, when just trying to set it immediately it fails: https://jsbin.com/fuxoge/2/edit?html,js,console,output
Hope that helps, let us know if you have more questions.

**Comment by Billybobbonnet** [comment]
Thanks you very much for the (quick) answer.

What puzzles me is that the DOM is fully loaded when I call the main function described above. Moreover, since I set the `currentTime()` both in the initial loading and the switch player functions, if I wait for the `loadedmetadata` in the initial loading (where both player instances are already existing)  but don't wait for it in the `switch player` function, it works in Chrome but not in Firefox. It means that a previously loaded and used videojs object becomes unavailable when it is hidden. 

I might have misunderstood the obvious (newbie alert), maybe a DOM element with css `display:none;` is not available to Javascript. I will check that. If it is, I guess I will try something like this:

```css
.hide {
   position: absolute !important;
   top: -9999px !important;
   left: -9999px !important;
}
```

**Comment by gkatsev** [comment]
It's probably because the first video has had time to load before your javascript function runs. It's still available even if `display: none` is set.
See [for the .currenTime](https://jsbin.com/fuxoge/3/edit?html,css,js,console,output) and [for the `loadedmetadata`](https://jsbin.com/fuxoge/4/edit?html,css,js,console,output).
It should still work. However, it's possible that the browser will decide to not load the video if the video element is hidden.
