### ISSUE TITLE
Captions not displaying in audio

### ISSUE THREAD

**Issue by OptimusKrish** [videojs/video.js#2955]
Hi,

I am using videojs version 5.4.4 and I am trying to display caption for audio using the below code. It is working fine for video playback but it is not displaying caption for audio playback. Am I doing anything wrong here?The console is clear only problem is caption not displayed inside the player. Thanks in advance for your help.

Code:
```html
<!--HTML part--->
<audio crossorigin="anonymous" id="audio_example" class="video-js vjs-default-skin"></audio>
```
```js
<!--Script part--->
var audioSource = [
    {
      src: 'http://mybloburl.blob.core.windows.net/audio/assets/0ddeeee4-ab9a-11e4-89d3-123b93f75cba.mp3',
      type: 'audio/mp3'
    }
  ];
   var audioConfig = {
    "preload": "auto",
    "loop": false,
    "controls": true,
    "width": 640,
    "height": 360,
    "nativeControlsForTouch": false,
    "sources": audioSource,
    "plugins": {
      "videojsPlaybackSpeed": {
        playbackRates: playbackRates,
        dynamicLabel: true
      }
    }
  }
videojs(document.getElementById("audio_example"), audioConfig, function(){

//to add captions dynamically
        var myPlayer = this;
        var enTrack = myPlayer.addRemoteTextTrack({
          kind: 'captions',
          language: 'en',
          label: 'English',
          src: 'http://mybloburl.core.windows.net/audio/assets/en-11249846-ab78-11e4-89d3-123b93f75cba.vtt'
        });

        var frTrack = myPlayer.addRemoteTextTrack({
          kind: 'captions',
          language: 'fr',
          label: 'French',
          src: 'http://mybloburl.blob.core.windows.net/audio/assets/fr-11249846-ab78-11e4-89d3-123b93f75cba.vtt'
        });
        
        myPlayer.on("play", function () {
          //to play english caption by default
          myPlayer.textTracks()[1].mode = "showing";
          console.log(myPlayer.textTracks()[1]);
        });
  });
```

**Comment by hartman** [comment]
You are not doing anything 'wrong' I suspect. I recently found out that 
http://www.iandevlin.com/blog/2015/12/html5/webvtt-and-audio browsers apparently simply don't implement this for <audio>, which is like... incomprehensible...

Try changing to a video tag.

**Comment by OptimusKrish** [comment]
Thanks @hartman this is what I have done as a temporary fix but it would be nice to have audio to be wrapped inside audio tag as a proper standard :-)

**Comment by gkatsev** [comment]
Yeah, the spec says the difference between audio and video tags is that audio doesn't have any area to display "things", whether captions or not while video does. We generally try to stick to the spec for questions like these, though, there may be enough utility to have the option to give `audio` a display area. Though, for something like captions, it'll have to be emulated captions because it won't display it natively unless we change the audio element to a video element behind the scenes.

**Comment by hartman** [comment]
>  spec says the difference between audio and video tags is that audio doesn't have any area to display "things", whether captions or not while video does

@gkatsev the thing is that it seems that browsers also don't trigger cuechange events for `<audio>` however, which is not according to spec as far as I know.

**Comment by OwenEdwards** [comment]
We discussed this elsewhere, and checked with the W3C. IIRC, playing audio using a video tag _is_ the official W3C solution to having captions with an audio stream. Having  a poster image with an <audio> element also gives an area to display the captions, but I don't remember if VideoJS supports that?

**Comment by gkatsev** [comment]
I think videojs can display a poster in audio-mode.
My question: should videojs automatically change an `<audio>` element to a `<video>` element for the user if captions are involved? Or should we just document that if you need captions for audio, you would use a `<video>` element.

**Comment by hartman** [comment]
audio with cue changes page:
http://islmpeg.s3.amazonaws.com/mp3/SeasonsInTheSun.html

Seems FF [doesn't implement cuechange](https://bugzilla.mozilla.org/show_bug.cgi?id=1033144) at all.

**Comment by OptimusKrish** [comment]
Thanks@hartman as you said it worked for IE,Chrome, Safari but not in FF. So, I cannot use this method.

**Comment by OptimusKrish** [comment]
@gkatsev I am currently using video tag to display caption for audio but when I resize video the caption is also getting smaller and becomes unreadable :-(

**Comment by gkatsev** [comment]
Yeah, captions are relative in size to the size of the video. What you could do is enable emulated captions. Then you could use the caption settings dialog to set the size of the captions.

**Comment by gkatsev** [comment]
I think we want to follow the spec's recommendation here. When used with `audio` element, we won't provide an area for displaying things like poster and text tracks but when using the `video` element we do.

**Comment by MuhaiminS** [comment]
@hartman  Can u help me to do like this. I  tried out of my best. I want to read that lyrics based on text track time.
audio with cue changes page:
http://islmpeg.s3.amazonaws.com/mp3/SeasonsInTheSun.html

**Comment by hartman** [comment]
@MuhaiminS I built some module code for that at some point, but we decided to go with a video frame presentation after all.

But it's rather simple, you can find the old version here (GPL-2 licensed)
https://github.com/wikimedia/mediawiki-extensions-TimedMediaHandler/tree/5b47a562b95e99bb65a0922a7eb2727dee031e9c/resources/mw-audio-captions
and then from the globalconfig of the setup of your player load the `audioCaptions` plugin.
