### ISSUE TITLE
Question about plugin " videojs-ass "

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2956]
Hi guys, I have some questions about this plugin.

1. I seen the .ass file appear on HTML source. There isn't a way for hide this or unable people to download .ass?

2. Is this compatible with videojs 5?

3. In this page: https://www.npmjs.com/package/videojs-ass
you say "If you are not on a phone or using a very bad browser, come check out the demo here". 
So, will the subtitle appear only on desktop browser?

**Comment by gkatsev** [comment]
`videojs-ass` isn't an official plugin. You'll want to add the issue to their repo: https://github.com/SunnyLi/videojs-ass. When you do, could you link that issue here as well so that people can reference if they find this issue?
Thanks.
