### ISSUE TITLE
Inline Volume in Version 5.

### ISSUE THREAD

**Issue by KingSora** [videojs/video.js#2962]
Hi!

I've some trouble to get the inline Volume control in Version 5.
In the documentation is written:

"The default skin has switched from displaying in an inline volume bar to a volume menu that displays on hover. The inline volume bar will still be created by default however, so you can hide the menu and display the inline version with CSS."

It doesn't matter which css I am applying, the volume bar is: 1. completely disappeared or 2. the volume menu on hover bar.

Can some one help me a bit - it seems like, the inline volume bar isn't even created, because I cant find a div like that in the DOM.

Best regards,
Sora

**Comment by gkatsev** [comment]
Can you describe a bit more what you expect to happen? Do you want the volume bar to always be displaying? Currently, it only shows on hover or on focus with the keyboard.

**Comment by KingSora** [comment]
Right. In the previous Version of VIdeoJS there was a persistent inline Volume bar, and exactly this is what i want / expect.

**Comment by gkatsev** [comment]
Ah, I see. I'm not sure the new volume control has that option. You can try changing the style of the control to always show it. You can also re-enable the old control.
```js
var player = videojs('video', {
  controlBar: {
    // this is the new control, so, disable it
    volumeMenuBar: false,
    // the old control had a separate mute toggle
    muteToggle: {},
    // the actual volume bar
    volumeControl: {}
  }
});
```
Though, that will put the new controls at the end of the control bar.
To maintain order, you could configure it like so:
```js
var player = videojs('video', {
  controlBar: {
      children: [
        'playToggle',
        'volumeMenuButton',
        'currentTimeDisplay',
        'timeDivider',
        'durationDisplay',
        'progressControl',
        'liveDisplay',
        'remainingTimeDisplay',
        'customControlSpacer',
        'playbackRateMenuButton',
        'chaptersButton',
        'subtitlesButton',
        'captionsButton',
        'fullscreenToggle'
      ]
  }
});
```

**Comment by mmcc** [comment]
The menu is just hidden and shown via CSS, so I would suggest just styling it to be so instead of adding a new component.

If you have the default components, something like this would work:

```css
.vjs-volume-menu-button.vjs-menu-button-inline {
  width: 12em;
}

.vjs-volume-menu-button.vjs-menu-button-inline .vjs-menu {
  opacity: 1;
}
```

[Example](http://jsbin.com/pudosevava/edit?css,output)
