### ISSUE TITLE
How can I override the progress bar value?

### ISSUE THREAD

**Issue by Billybobbonnet** [videojs/video.js#2976]
Hello,

I am using videojs v5+ with the HTML tech. I would like to update the player progress bar value arbitrarily, using my own values.

I noticed that the videojs progress bar value is set in the `playProgressBar` component, in a [function named `updateDataAttr()`](https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/play-progress-bar.js#L38)

I planned to replace this function with my own.

I can access the `PlayProgressBar` object like this, `video1` being my Javascript variable where I store my videojs instance:

```
console.log(video1.controlBar.progressControl.seekBar.playProgressBar);
```

However, it does not work (no log appear) if I modify `updateDataAttr()`like this:

```
video1.controlBar.progressControl.seekBar.playProgressBar.updateDataAttr = function() {
  console.log(template.find(".vjs-play-progress"));
  $(template.find(".vjs-play-progress")).css('width', template.currentProgress+'%');
  template.find(".vjs-play-progress").setAttribute('data-current-time', formatTime(template.currentTime, globalDuration));
}
```

Note that the `template.find()` is similar to a jquery selection using `$()` (I am using meteor).

This is more an intuitive approach than an educated one: I am fairly new to Javascript and I am not sure this is the right way to proceed. Moreover, I wonder if it matters if, videojs being written in ES6,my code isn't ES6.

Is this how I should do this? If so, why isn't my new `updateDataAttr()` function executed on videojs `timeupdate` event?

**Comment by gkatsev** [comment]
You can probably do something using middleware at this point using latest versions of Video.js.
Docs: http://docs.videojs.com/tutorial-middleware.html
