### ISSUE TITLE
AccessDenied for CDN files

### ISSUE THREAD

**Issue by davestevens** [videojs/video.js#2977]
Some of your CDN files are returning forbidden errors:

http://vjs.zencdn.net/4.12/video-js.min.css
http://vjs.zencdn.net/4.12/video.min.js

The unminified version work fine:

http://vjs.zencdn.net/4.12/video-js.css
http://vjs.zencdn.net/4.12/video.js

**Comment by mister-ben** [comment]
The CDN responds access denied where a file is not found.

There was never a `video.min.js` for 4.x. `video.js` is the minifed version, `video.dev.js` is unminifed. `video.dev.js` and `video-js.min.css` aren't on the CDN but you can build or [download](https://github.com/videojs/video.js/releases/tag/v4.12.15) to self-host them.

For 5.x the more regular naming convention is used - `video.min.js` and `video.js`, and `video-js.min.css` and `video-js.css`. All are available from the CDN.

**Comment by davestevens** [comment]
You might want to update your site then? http://docs.videojs.com/docs/guides/setup.html

**Comment by mister-ben** [comment]
Thanks for pointing that out. The doc should be showing the latest 5.x urls:

//vjs.zencdn.net/5.4.4/video-js.min.css
//vjs.zencdn.net/5.4.4/video.min.js

**Comment by gkatsev** [comment]
Yeah, that setup guide is old. You should use this setup guide: http://videojs.com/getting-started/

**Comment by leup** [comment]
Still getting some AccessDenied with version 5.10.4

http://vjs.zencdn.net/5.10.4/video.min.js
http://vjs.zencdn.net/5.10.4/video.js

http or https

**Comment by jmoujaes** [comment]
Hello,

This is happening with the following urls
`https://vjs.zencdn.net/7.6.5/video-js.css`
`https://vjs.zencdn.net/7.6.5/video.js`

I'm using the code snippet at the top of the [getting started](https://videojs.com/getting-started/) tutorial.

**Comment by gkatsev** [comment]
@jmoujaes sorry about that. They should be working now.
