### ISSUE TITLE
VideoJS 5.4.4 was black on iPhone

### ISSUE THREAD

**Issue by hxdev** [videojs/video.js#2980]
It's work fine on iPad, Android phone and PC but isn't for iPhone.

I've try to debug and see this error: Uncaught TypeError: videojs is not a function

Live demo: http://tamnhinso.info/phim/chu-khung-long-tot-bung.898/watch

Look like the size of player cause of problem but why it's throw that error? hmm

**Comment by mmcc** [comment]
Just tested this on an iPhone and it seems to work fine. Closing this, but if you're still seeing this and have more issues, ping this thread and we can revisit.
