### ISSUE TITLE
player.width() and player.height() return 0

### ISSUE THREAD

**Issue by hc2p** [videojs/video.js#2983]
Hi all, 

the return value of `player.width()` and `player.height()` is always 0 for me.
I initialize the player without width and height, use the `.vjs-16-9` class and rely on wrapping divs for max-heights and -widths.

What's the rational behind returning 0? I feel like i'm missing an important point here.

What about calling through to `Component.dimension` if used as a getter (similar to 4.x)?
```
  Player.prototype.dimension = function dimension(_dimension, value) {
    var privDimension = _dimension + '_';

    if (value === undefined) {
      //return this[privDimension] || 0; // for me, this always resolves to 0
      return _Component.prototype.dimension.call(this, _dimension); // this will compute the actual width/height of the player
    }
```

I am using the [videojs-ima](https://github.com/googleads/videojs-ima) plugins which sets the ad-player dimensions by calling player.width() and player.height(). 

thanks for looking into this :)

**Comment by gkatsev** [comment]
Heh, we just had the same question a couple of days ago. See #2974 and #2282 for more information.
The short answer is that the `player#width` returns the configured dimensions of the player to mirror the video element's `width` attribute. To get the actual current dimension you'd want to use `getComputedStyle`.
Hope that helps.

**Comment by hc2p** [comment]
that makes total sense now. Thx
