### ISSUE TITLE
This video could not be load... why?

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#2986]
Hi guys. I'm testing you videojs 5 player.
Anyway I don't know why but I'm getting a problem using this mp4 testing file: http://test995.altervista.org/test.mp4

I used this to include the video: source src="http://test995.altervista.org/test.mp4" type='video/mp4' /
but I don't know why, when I try to play the video it say "This video could not be load". And i can't understand why. could you please help me?

**Comment by mister-ben** [comment]
It's because the server is redirecting to an HMTL document at http://hl.altervista.org/split.php?http://test995.altervista.org/test.mp4, presumably to prevent direct linking to the file.

**Comment by giggioman00** [comment]
Thank you. 
I have another question. I just made a custom videojs skin, but I don't know how to use it in my site. You can find the code here; http://codepen.io/anon/pen/GomvXb

**Comment by mmcc** [comment]
You need to include the CSS in the text box below the demo somewhere in your page after the default CSS. For example:

```html
<link href="videojs.css" rel="stylesheet">
<style>
  /* Styles from your codepen */
</style>
```
