### ISSUE TITLE
Usability: Show subtitles (or change subtitles) on icon click

### ISSUE THREAD

**Issue by q2apro** [videojs/video.js#2989]
For better usability I suggest to activate the subtitles when clicking the subtitle icon. 

The order should be (if off by default and we have 2 languages): 

 1. (activated:) language A 
 2. language B
 3. off
 4. repeat 1 to 3

This would really help all users.

**Comment by mister-ben** [comment]
If you have many tracks, cycling through them all to turn captions off could be annoying.
How would the user know which languages are available?

**Comment by q2apro** [comment]
Nope. 

The idea is: 

1. Click the field, change to the next subtitle.
2. Previous behaviour: Mouse over and showing the popup will still persist.

You give the user a faster way of changing subtitles.

And when the user clicks the subtite button, then of course the field in the little popup is highlighted. Should be easy.

**Comment by OwenEdwards** [comment]
I think the way the captions control works could be improved, but I'm not sure this suggestion works. Firstly, I don't think cycling through several languages matches a user's expectation - a better model would be for the user to set a preferred language (or list of languages), and for the player to remember that and use it to allow single-click on or off control. (There should also be a user preference for whether to default to captions on or off, to override the HTML `default` attribute).

Also, having click do something different from mouse over doesn't work for pure touchscreen (mobile) interfaces.

**Comment by gkatsev** [comment]
Yeah, while we definitely have more work to do to increase usability, I'm not sure this would actually be in the right direction because of user expectation.
Maybe what we do want to have in the end is something like how youtube does it. Have a captions button that toggles the showing of captions and then a separate menu for choosing the exact language. However, making such a change will probably have to wait till a major version update.

**Comment by OwenEdwards** [comment]
It feels somewhat inevitable that the next major version of video.js is going to need a settings menu or dialog, and then we'll be able to simplify things in the Control Bar. The Settings area will need a way for plugins to add to it, as well as on the Control Bar, in a clean and scalable way.

That seems to match what most users expect. At least we've got the icon for it already ;-)

**Comment by q2apro** [comment]
My wish would be to enable or disable the subtitles by one click if there is *only one language*. This is the case with all my 100+ videos. 

So: 1 subtitle track = 1 click to activate or deactivate.

Thanks for considering.

**Comment by gkatsev** [comment]
@q2apro in the meantime, you could write a plugin that hides the native captions button and adds your own with the functionality how you want it to be. We'd be happy to help answer questions you have if you end up writing such a thing.

**Comment by q2apro** [comment]
I have the flue currently... :(

**Comment by gkatsev** [comment]
I don't think we want to change the behavior of how the menus work at this time.
There are other improvements that can be made and those should be tracked in separate issues.
