### ISSUE TITLE
Using type when incorrect Content-Type

### ISSUE THREAD

**Issue by fzakaria** [videojs/video.js#2992]
Hi!

I was wondering if the use of the type attribute in the source tag should override the Content-Type sent by the server?

I have a server returning an MP4 file however with content type application/octet-stream.
I have set the type="video/mp4" however.

Should this be overriding the wrong content-type ?

**Comment by mmcc** [comment]
Similar things have come up before and I totally see where you're coming from. Unfortunately, the tl;dr here is that the server returning `application/octet-stream` is Doing It Wrong™ and should feel bad (:trollface:). This is pretty common with S3 when it doesn't accurately pick the right mime type and just defaults to an octet stream.

But ultimately, there's only so much we can do with "overriding" the content type in situations like this. For HTML5 playback, the browser might still take a look at the response headers no matter what we _say_ the content-type is, so it's a bit of a dead end. Certain workflows with various techs will work, regardless, but it's an unpredictable crap shoot and I'd highly suggest just making sure the mime type is correct (if you have any semblance of control over it).

**Comment by fzakaria** [comment]
Thanks!

Would good if VideoJS had a markdown file maybe with some common Q&A
(Couldn't find)

Farid Zakaria

**Comment by gkatsev** [comment]
I've been wanting to make an FAQ section. I'll add this to the list.
