### ISSUE TITLE
consider using ally.js to help out with accessibility issues

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2993]
Here's a list of [highlights from allyjs](https://www.smashingmagazine.com/2015/12/making-accessibility-simpler/#ally-js-highlights)
- add ability to distinguish between mouse and keyboard focus
- fix `:focus` bugs in webkit/IE

The ability to distinguish between keyboard and mouse focus is very useful and will help us fix issues like #2918.
Including ally.js will probably leave to a size increase of the built-code (unless we figure out dead-code elimination) and depending on how useful it is and how much of ally.js we use/need, it will be better than just trying to implement these features ourselves.

**Comment by gkatsev** [comment]
Looks like allyjs provides modular require points.

**Comment by gkatsev** [comment]
At this moment (looks like almost a year on), adding allyjs with our current build system is too much of a change in filesize. The minified gzipped version of videojs goes up from 56K to 74K. Almost 25% change.
I do hope that as we revamp our build system with tree shaking, we can start including allyjs.

**Comment by OwenEdwards** [comment]
@gkatsev I think we can close this in favor of `focus-visible` from WICG; I created a demo of how that would work at https://github.com/OwenEdwards/video.js/tree/experimental/use-focus-visible-package

**Comment by gkatsev** [comment]
Should we just include focus-visible?
But yeah, it sounds like we fixed the other issue that ally.js would've been useful for.

**Comment by gkatsev** [comment]
The minified file seems small enough, if the polyfill isn't too destructive, we could add it. Though, maybe it is best to just document it.

**Comment by gkatsev** [comment]
We're getting hotkey support in #5571 and we recently added focus-visible support, so, this can just be closed.
