### ISSUE TITLE
VideoJS video abort while playing multiple videos on firefox at same time.

### ISSUE THREAD

**Issue by adilsaeed31** [videojs/video.js#2996]
Hi,

I'm trying to play 4 videos on same time on firefox but firefox abort the media request all other browser are fine. i don't know what is this.

**Comment by mister-ben** [comment]
What is the behaviour with plain video elements without video.js?

**Comment by adilsaeed31** [comment]
that is working perfectly fine.

**Comment by mister-ben** [comment]
Do you have a link to a reduced test case?

**Comment by adilsaeed31** [comment]
Current scenario is,

I have 4 videos which are not playing through their play button, the controls are disabled, but i'm playing these videos with another single button. when i press the button. In JS code the videos manually play with below mentioned code, 

var myPlayer0 = videojs('#videoID');
myPlayer0.play();
var myPlayer1 = videojs('#videoID');
myPlayer1.play();
var myPlayer2 = videojs('#videoID');
myPlayer2.play();
var myPlayer3 = videojs('#videoID');
myPlayer3.play();


Then all videos starting buffering and then playing. but this technique work on all browser except firefox (43.0.4 ver) with videojs. but when you enable the controls and click on play button of video then videos starts fetch properly. This is the exactly issue.

Thanks

**Comment by adilsaeed31** [comment]
I have figure out this issue, videojs not buffering if the videos are hidden through CSS now i have remove the hidden visibility its working fine.

**Comment by gkatsev** [comment]
Is videojs playing back in flash or html5 mode? If it's flash, then having it hidden would *definitely* cause a problem.
Going to close this since you said you figured it out, but we can continue the discussion.
