### ISSUE TITLE
Docs example isn't loading

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#3005]
http://docs.videojs.com/docs/examples/simple-embed/index.html

![screen shot 2016-01-14 at 11 52 50 am](https://cloud.githubusercontent.com/assets/549319/12335696/5e1ed498-bab5-11e5-8300-1a4b7c57b8a0.png)

**Comment by gkatsev** [comment]
It's [fixed](https://github.com/videojs/video.js/pull/2915) but not yet deployed, thanks.
