### ISSUE TITLE
Make videojs 5 responsive without using fluid

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#3008]
There is a way for make the videojs 5 player responsive without using vjs-fluid?

**Comment by mmcc** [comment]
What's the reason for not wanting to use `.vjs-fluid`?

Closing since this is a question that doesn't need action, but we can keep talking in the comments.

**Comment by giggioman00** [comment]
I need to use the plugin "videojs-ass". But this plugin it's not full compatible with .vjs-fluid...

So I want to try to make my player responsive without .vjs-fluid, maybe without .vjs-fluid the plugin will works...

**Comment by gkatsev** [comment]
We probably should kindly ask `videojs-ass` to update itself to support fluidity since there isn't any other way to make the player response and have videojs-ass still function correctly, it sounds.

**Comment by giggioman00** [comment]
videojs-ass already support vjs-fluid, the problem is that it's not fully compatible. 
I mean, with .vjs-fluid sutitled are placed in wrong position and in some resolution subtitles doesn't even appear. 
If they could fix this compatibility problem would be awesome, but I need to make everything working by 1st February... I don't know how many chances for get everything working within 14 days. The owner of the plugin takes around 7 days for just answer a question.

**Comment by mmcc** [comment]
@giggioman00 If you're on a deadline, I would suggest not relying on OSS contributions to fix your problem. Not trying to be rude, just remember that your deadlines are not theirs, and it's unfair to make them so.

Do you have an example online we could take a look at? It looks like the plugin relies on the [player height](https://github.com/SunnyLi/videojs-ass/blob/master/src/videojs.ass.js#L55-L56) to make rendering calculations, which isn't going to work when the player is fluid-width. This could probably be done using CSS positioning instead, but if you have a hard timeline, you should fork and make the changes you need. You could also be awesome and consider contributing back!

Good luck! Let us know how things go.

**Comment by giggioman00** [comment]
That is the master branch, which is not compatile with videojs 5.
The branch compatible with videojs5 is the 0.5 and is here: https://github.com/SunnyLi/videojs-ass/blob/v0.5/src/videojs.ass.js

If you could tell me where is the problem I wil try to do something

**Comment by mmcc** [comment]
In the 0.5 branch things are a [little different](https://github.com/SunnyLi/videojs-ass/blob/v0.5/src/videojs.ass.js#L56-L59), but it's still not going to work given a fluid video. Here's [an example](http://jsbin.com/moyaye/edit?html,js,console,output) that shows what I mean.

**Comment by gkatsev** [comment]
I think the main issue with how `videojs-ass` is checking the size of the player is that it's relying on `player.width` to return the current size of the player. [It does not](https://github.com/videojs/video.js/issues/2974#issuecomment-169191472). `videojs-ass` should be updated to use the computed style of the player to calculate dimensions.
