### ISSUE TITLE
FullScreen Events

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#3009]
Are their any vjs EVENTS exposed for listening on full screen entry/exit?

I can see a whole load of FullScreen methods, all quite complicated, but nothing definitive for our purpose that fires when the fullscreen state is changed. We'd like to use a couple of listeners upon setup of the player, something like:

this.on('fullscreenEntered', ...
this.on('fullscreenExited', ...

We need to pickup FullScreen entered when either FullScreen or FullWindow.
And exit when return from either.

Are their any vjs EVENTS exposed for this?

**Comment by mister-ben** [comment]
There's a single `fullscreenchange` event that is triggered when switching into or out of fullscreen mode. You can use `player.isFulscreen()` in the handler to check whether the player is fullscreen.

**Comment by gkatsev** [comment]
Thanks @mister-ben. Was going to reply but then got distracted by other things.
This event is also inline with the html5 spec of how to listen to fullscreen things.

**Comment by richardbushell** [comment]
Yeh, I saw that, but I was worried that if I might poll the isFullscreen value before vjs had handled the  fullscreenchange event itself and had updated the isFullscreen property value.

If I read the value of player.isFullscreen() in my fullscreenchange event listener is this guaranteed to happen after that value had already been updated?

We use contrib-dash too so didn't know if the player.js fullscreenchange listener was tech related or not?

Anyway, please let me know if you are sure this value will already have been correctly updated by the time I read it, and that would answer my question.

**Comment by gkatsev** [comment]
Yeah, we try and [make sure](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1576) that it triggers after.

**Comment by gkatsev** [comment]
If you find there are issues with that, please open up an issue.

**Comment by richardbushell** [comment]
Perfect, will do, thanks . Please close.

**Comment by nisimjoseph** [comment]
thank you. please add it to the docs:
http://docs.videojs.com/docs/api/player.html
