### ISSUE TITLE
Method for using hls in chrome or firefox

### ISSUE THREAD

**Issue by djevo1** [videojs/video.js#3010]
I have tried the hls plugin for video.js but it does not want to load the .m3u8 stream in chrome or firefox. Attached is the code I used
![screen shot 2016-01-18 at 9 24 48 pm](https://cloud.githubusercontent.com/assets/16768999/12407958/f0b81432-be29-11e5-8c80-ba0313c7a609.png)

**Comment by mmcc** [comment]
You've got `type=video/mp4` instead of `application/x-mpegURL`.

**Comment by djevo1** [comment]
Tried that, same issue. Player appears but there is no video

---Sent from Boxer | http://getboxer.com

On January 18, 2016 at 9:36:24 PM EST, Matthew McClure <notifications@github.com> wrote:Closed #3010.  —Reply to this email directly or view it on GitHub.

**Comment by mmcc** [comment]
You should open an issue on the [specific plugin](/videojs/videojs-contrib-hls), but make sure you have a reduced test case (live example showing your problem) ready when you do.

**Comment by djevo1** [comment]
I was able to fix the issue, one moe thing, I have a DVR broadcast but I can't see the seekbar in video.js

**Comment by mmcc** [comment]
Glad to hear it! That's still a question for the plugin's tracker, but it looks like it's already an [open issue](/videojs/videojs-contrib-hls/issues/354).
