### ISSUE TITLE
Uncaught TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by nkhine** [videojs/video.js#3014]
I get this error on the console

```
Uncaught TypeError: Cannot read property 'close' of undefined
error @ player.js:2192
handleTechLoadStart_ @ player.js:754
ret @ fn.js:35
ret @ fn.js:35
data.dispatcher @ events.js:72
```

my code as a `blade` template (https://github.com/bminer/node-blade)  is as follows:

```
section#video
  -if(is_desktop)
    video#video-block.video-js.vjs-default-skin.vjs-playing.vjs-big-play-centered(poster="/images/home/video.jpg")
      source(src="//#{settings.cloudFrontDomain}/assets/videos/home/v1/video.mp4" type='video/mp4')
      source(src="//#{settings.cloudFrontDomain}/assets/videos/home/v1/video.ogv" type='video/ogg')
      source(src="//#{settings.cloudFrontDomain}/assets/videos/home/v1/video.webm" type='video/webm')
    :javascript
      videojs("video-block", {
          preload: 'auto',
          autoplay: true,
          fluid: true,
          loop: true,
          aspectRatio: '16:9',
          controls: false,
          errorDisplay: false,
          loadingSpinner: false
        });
```

if i remove `errorDisplay: false` there is no error - i am using video.js version 5.5.3

**Comment by gkatsev** [comment]
It sounds like your player got an error and it tried to display it in the error display but you've told the player to not create that error display so it errored out based on that expectation.
Is there a specific reason why you're disabling the error display?

**Comment by nkhine** [comment]
yes, i want to disable the error message as per https://github.com/videojs/video.js/issues/1930

**Comment by gkatsev** [comment]
Ok, I guess we need to do a null check in that case.
Would you be willing to submit a PR for a fix? Basically, [here](https://github.com/videojs/video.js/blob/master/src/js/player.js#L2180) and where-ever else the errorDisplay is referenced, we'd need to wrap it in a null check.

**Comment by artaommahe** [comment]
same error. i will use video.js only through api with my own html-skin, so i disabled all default components and got this error on `player.play()`

**Comment by ntadej** [comment]
This can now be closed I guess.

**Comment by gkatsev** [comment]
Looks like it. Thanks, @ntadej.
