### ISSUE TITLE
VideoJS video orientation rotate to 45 degree in FireFox.

### ISSUE THREAD

**Issue by adilsaeed31** [videojs/video.js#3019]
Hi,

I'm using VideoJS player for project, but this is seems that videojs display videos at 45 degree in firefox. and there is no config option available in videojs library so can you guys let me know how to fix it through JS or CSS. 

Here is the image attached this is firefox 43 version.

http://awesomescreenshot.com/0d85km401b

Here is the image attached this is chrome latest version, this is correct angle.

https://www.diigo.com/item/image/5jbyj/ndvw

Waiting for quick response.

Thanks

**Comment by gkatsev** [comment]
I believe the issue here is with the encoding of the video and seems like firefox doesn't know how to handle the metadata in the file that tells it to rotate the video but chrome can. I'm not sure that there's anything we can do in videojs to fix this. @mmcc thoughts?

**Comment by mmcc** [comment]
@gkatsev I think you've hit the nail on the head. Most consumer encoders will take care of this for you by default (including [zencoder](https://app.zencoder.com/docs/api/encoding/video-processing/rotate)), but there isn't anything we can do about this from the Video.js perspective.

**Comment by adilsaeed31** [comment]
Yes definitely, VideoJs should take care about this prospective.

**Comment by mister-ben** [comment]
The point is this needs to be fixed/implemented in Firefox. There's a bug for this on Mozilla's tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1228601
