### ISSUE TITLE
fullscreenchange event not firing properly on iPad

### ISSUE THREAD

**Issue by Siraris** [videojs/video.js#302]
VideoJS has been one of the best video libraries I've ever used.  I'm having one issue though.  I bind to the fullscreenchange event to handle some wonkiness with full screen in IE8.  In doing so, I've found that if I enter full screen mode, click done to exit full screen mode, and then try to re-enter full screen mode, it doesn't seem to fire the fullscreenchange event again.  If I press it once more after that though, it does, and full screen mode returns.  

Is this a known issue?  I'm trying to deploy to this for a client, and it's something that's going to come up as an issue they'll want resolved (I'm fairly certain). 

Any help would be appreciated!

**Comment by alicePan** [comment]
`if(ua.iPhone || ua.iPod) {
          var video = document.createElement('video')
          video.classList.add('m-player')
          video.id = 'mPlayer' + id++
          video.src = this.src
          document.body.appendChild(video)
          this.playerEle = video
          this.video = video

          $(this.video).on('webkitbeginfullscreen webkitendfullscreen', function() {
            alert(e.type)
          })
          $video.on('webkitbeginfullscreen webkitendfullscreen', function(ev) {
                        if (ev.type == 'webkitbeginfullscreen') {
                            player.isFullScreen(true);
                            player.trigger('fullscreenchange');
                        } else if (ev.type == 'webkitendfullscreen')  {
                            player.isFullScreen(false);
                            player.trigger('fullscreenchange');
                        }
                    });
          return
        }`

I dont kown why this code dose not work for me. My os version is ios 10.x.x
