### ISSUE TITLE
How to remove this?

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#3020]
I would like to remove the bubble of the current time and keep the other bubble.
<a href='http://postimg.org/image/73qgwpgxd/full/' target='_blank'><img src='http://s8.postimg.org/jid8x18fp/Senza_titolo_1.jpg' border='0' alt="Senza titolo 1" /></a>

**Comment by gkatsev** [comment]
That tooltip is created using only css: https://github.com/videojs/video.js/blob/master/src/css/components/_progress.scss#L42-L45
To hide it, you can add the following style after the videojs styles are loaded:
```css
.video-js .vjs-progress-control:hover .vjs-play-progress:after {
  display: none;
```
(Or use `!important` if you must).
Hope that helps. Thanks.

**Comment by giggioman00** [comment]
In this way both tooltip are disabled.
I want to disable just the one with the current time.

**Comment by gkatsev** [comment]
The code that I had should only hide the current time one.

**Comment by giggioman00** [comment]
Remove both to me

**Comment by giggioman00** [comment]
This is the result. As you can see, both tooltip are removed. Please tell me how the remove just  the first tooltip


<img src='http://s12.postimg.org/z1nn1j2h9/Senza_titolo_43.jpg' border='0' alt="Senza titolo 43" /></a>

**Comment by gkatsev** [comment]
Can you put up a reduced test case on a site like jsfiddle? Thanks.

**Comment by giggioman00** [comment]
Ok, fixed. It was my fault, I done the wrong change

**Comment by gkatsev** [comment]
Cool, glad you figured it out.
