### ISSUE TITLE
Make or use a module for resolving keycodes

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#3022]
In a lot of places in our code, we do checks against `event.which` and then having a comment saying that `9` is a tab and `13` is enter.
We should investigate the [keycode](https://github.com/timoxley/keycode) module and decide whether we need a whole module or if making a simple object map in our code is sufficient or worth it.
Afterwards, we should update the code that checks `event.which` to use what we chose above instead of magic numbers with comments.

**Comment by rizcheldayao** [comment]
@gkatsev can I take on this issue? Is it still needed?

**Comment by gkatsev** [comment]
I think it would be nice to do for readability and maintenance, though, the main thing I'd be worried about is that the size of the player increases too much if we use an existing library.
