### ISSUE TITLE
It seems that videojs don't work in Chrome for playing a flv  video

### ISSUE THREAD

**Issue by XiaoMaTongXue** [videojs/video.js#3024]
I am trying using videojs to play a flv video in Chrome and the html code like this:
![image](https://cloud.githubusercontent.com/assets/11328294/12517079/efa1b3a6-c16b-11e5-91c6-541114c3a5da.png)
but no movie was played.
I got this:
![image](https://cloud.githubusercontent.com/assets/11328294/12517179/7db3fa6e-c16c-11e5-95a7-e5341a9d8d1e.png)
player.isReady_ is always false.

I found that Flash.onReady is not be called.
Is it a bug or my wrong using ?

**Comment by mmcc** [comment]
My guess is that you're running into Chrome settings with this one. The default setting these days is "detect and run important plugin content", which, particularly for small FLVs means I have to click "play" twice: once to trigger play, and again to enable the plugin for chrome.
