### ISSUE TITLE
iPad play start position

### ISSUE THREAD

**Issue by donquibeats** [videojs/video.js#3025]
Hello

I'm a newbie to video.js, but I've looked in the forum and not found an answer to this, hopefully somebody can help.

I know that iOS blocks the conventional .play() method and requires the user to click a button. But does this categorically prevent the use of .currentTime(n) to set the play position within a video before the user clicks the play button?

I don't want the video to start automatically, I know that won't work on iOS, but I need the video to skip to a known number of seconds into the file, so that when the user does click the play button, the movie starts from the right place.

Is there any chance this is possible, even if .play() doesn't work?

And- just to push my luck here- if it's not possible in video.js, is it possible with any other player or wrapper? YouTube can do it... can anyone else?

Thanks for any help that you might be able to provide.

Stuart

**Comment by mister-ben** [comment]
Seeking on the play event should be ok:

    player.one('play', function() {
      player.currentTime(15);
    });

**Comment by donquibeats** [comment]
Unfortunately, I've tested it across several iOS devices and .currentTime does not get set, in my tests.
