### ISSUE TITLE
Fluid mode breaks on iOS 7

### ISSUE THREAD

**Issue by andfinally** [videojs/video.js#3026]
I am getting weird results on iOS 7 when I enable the "fluid" option.

I have a test page with two test video embeds. The first is a plain embed with the vjs-16-9 class to give it the 16:9 proportions. The other is a fluid player with this markup:

``` html
<p>Fluid player starts here:</p>

<video id="5678" class="video-js" controls poster="http://vjs.zencdn.net/v/oceans.png"
       data-setup='{"fluid":true, "preload":"auto"}'>
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
    <source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
    <source src="http://vjs.zencdn.net/v/oceans.ogv" type='video/ogg'>
</video>

<p>After fluid player</p>
```

And the standard video-js.css and video.js files from vjs.zencdn.net. The only other CSS I've applied is a max width of 640 on the content container.

When I view the page on an iPhone 4 with iOS 7, the 16:9 player renders OK, but the fluid one disappears completely when the JS kicks in. In this screenshot the player is located immediately after the paragraph "Fluid player starts here:".

![photo 3](https://cloud.githubusercontent.com/assets/1647564/12535763/bcdf398c-c285-11e5-918b-52ac14a031a8.PNG)

Added a [test case](http://jsbin.com/rutese/edit?html,output) and attached the full markup for my test page: [index.html.zip](https://github.com/videojs/video.js/files/102269/index.html.zip)

**Comment by gkatsev** [comment]
Hi, sorry it's taken us this long to get back to this issue and coming with bad news. Unfortunately, at this point we don't have the bandwidth to support iOS 7 given it's low market share and it's age.
