### ISSUE TITLE
VideoJS can't be instantiated as part of an object

### ISSUE THREAD

**Issue by bobgle** [videojs/video.js#3030]
Not sure if this is somehow related to JS, but if there is a workaround please tell me. VideoJS gives an unknown error:

    [8660][streamController] Video Element Error: UNKNOWN 

Refer to this StackOverflow question: http://stackoverflow.com/questions/34968124/videojs-wont-start-video-if-declared-as-part-of-an-object

**Comment by gkatsev** [comment]
Not quite sure what the issue is. Will you be able to put up a reduced test case on a site like jsfiddle?

**Comment by mmcc** [comment]
This feels like a better fit for StackOverflow (that error isn't coming from Video.js core), so closing this. As @gkatsev said, a JSFiddle or JSBin example would go a long way to help other folks help you, so I'd suggest adding one to the question.
