### ISSUE TITLE
Videojs on mobile: critical problem

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#3031]
It seems that the player is responsive, but not the control bar. 

Please take a look, this screenshot was taken on mobile (Galaxy S6)

<a href='http://postimage.org/' target='_blank'><img src='http://s15.postimg.org/cioe4frvf/Cattura33333.jpg' border='0' alt="Cattura33333" /></a>

**Comment by mmcc** [comment]
If you need to get this small, you need to do your own work there. There are [responsive classes](https://github.com/videojs/video.js/blob/master/src/css/components/_adaptive.scss) you can use to drop things off the control bar when you get down to this size.

Just to note, please consider combining issues whenever you can. You've opened quite a few issues in the last month, most of which where questions, which is *totally* fine, just please keep in mind that this is an issue tracker, not tech support. When it makes sense, instead of creating a new issue, consider opening a question on a forum such as StackOverflow and tagging it with Video.js or finding a related issue and commenting on that.

**Comment by hartman** [comment]
I also have a plugin https://github.com/hartman/videojs-responsive-layout that tries to deal with this problem. It's not really finished/stable however.

**Comment by giggioman00** [comment]
I tried to deal with this in the past few days 

```
.video-js.vjs-layout-tiny:not(.vjs-fullscreen).vjs-no-flex .vjs-custom-control-spacer {
  width: auto; }

.video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-current-time, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-captions-button, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-time-divider,
.video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-progress-control, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-duration, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-remaining-time, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-playback-rate,
.video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-mute-control, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-volume-control, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-chapters-button, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-captions-button,
.video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-subtitles-button, .video-js.vjs-layout-tiny:not(.vjs-fullscreen) .vjs-volume-menu-button {
  display: none; }

.video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-current-time, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-captions-button, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-time-divider,
.video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-duration, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-remaining-time, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-playback-rate, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-captions-button,
.video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-mute-control, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-volume-control, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-chapters-button,
.video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-subtitles-button, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-volume-button, .video-js.vjs-layout-x-small:not(.vjs-fullscreen) .vjs-fullscreen-control {
  display: none; }

.vjs-layout-small:not(.vjs-fullscreen) .vjs-current-time, .video-js.vjs-layout-small:not(.vjs-fullscreen) .vjs-captions-button, .video-js.vjs-layout-small:not(.vjs-fullscreen) .vjs-time-divider,
.vjs-layout-small:not(.vjs-fullscreen) .vjs-duration, .video-js.vjs-layout-small:not(.vjs-fullscreen) .vjs-remaining-time, .video-js.vjs-layout-small:not(.vjs-fullscreen) .vjs-playback-rate,
.vjs-layout-small:not(.vjs-fullscreen) .vjs-mute-control, .video-js.vjs-layout-small:not(.vjs-fullscreen) .vjs-volume-control, .video-js.vjs-layout-small:not(.vjs-fullscreen) .vjs-chapters-button,
.vjs-layout-small:not(.vjs-fullscreen) .vjs-subtitles-button {
  display: none; }
```

But it's seems to be completely useless.

**Comment by giggioman00** [comment]
Ok @mmcc using your way I can remove something from the bar. 
But then what I remove is removed even on bigger resolution. 
My player doesn't have the size of the image.
That size is when I su a mobile device.

**Comment by hartman** [comment]
@giggioman00 use my plugin, it applies those classes automatically. It might be good enough for what you are trying to do.

**Comment by giggioman00** [comment]
I have already installed 2 plugin. I don't want to install too many plugin

**Comment by mmcc** [comment]
@giggioman00 What's your concern about installing 3 plugins? His plugin looks like a good option, and honestly I don't _think_ we'll ever add this kind of functionality to core.

**Comment by giggioman00** [comment]
I just installed the plugin, but doesn't work
