### ISSUE TITLE
360 spherical video

### ISSUE THREAD

**Issue by jemoreno** [videojs/video.js#3044]
Are there any plans to support 360 spherical video in the near future?

**Comment by gkatsev** [comment]
It's unlikely that we will support it in core videojs. There is currently a plugin for videojs 4.x that adds geometric video support to videojs: https://github.com/slawrence/videojs-vr

**Comment by gkatsev** [comment]
To elaborate, we would encourage users who want this feature to write a plugin or a videojs tech for this feature and we would be happy to help make that a reality (within reason) but we would not add direct support for such videos directly into videojs.
