### ISSUE TITLE
iPhone - use canvas to bypass native?

### ISSUE THREAD

**Issue by alijaffar** [videojs/video.js#3048]
A known issue exists - playback in iOS, specifically I've noticed with iPhones as many have - that native playback has to be used... I propose possibly coupling a canvas element to make it work. There's an example someone made called canvid.js (http://gka.github.io/canvid/) and it uses canvas and html5 video to work for iPhones. Thoughts?

**Comment by mmcc** [comment]
While very cool, canvid actually doesn't have anything to do with html5 video, it's actually playing back JPEG sprites. This is solidly outside of the wheelhouse of this project, but this would be a really cool plugin / tech!

**Comment by bfred-it** [comment]
This should make inline playback possible with video.js too:

https://github.com/bfred-it/iphone-inline-video

Can you give it a try?

Related: https://github.com/videojs/video.js/issues/3209 https://github.com/videojs/video.js/issues/1978 https://github.com/videojs/video.js/issues/1364 https://github.com/videojs/video.js/issues/896
