### ISSUE TITLE
[bug] Broken links in Docs

### ISSUE THREAD

**Issue by allienworks** [videojs/video.js#3052]
While browsing though the docs, I found some pages link to 404s.. e.g. [Videojs Options](http://docs.videojs.com/docs/guides/options.html) links to [Components](http://docs.videojs.com/docs/guides/components.md) (broken) in the last paragraph.

Luckily it's just an issue of replacing ```.md``` to ```.html``` extensions in links, when pages are linking to themselves directly (meaning not from [docs index](http://docs.videojs.com/))

Another places where I found broken links:

* [Setup](http://docs.videojs.com/docs/guides/setup.html) -- link "**options**" in Step 2
* [Plugins](http://docs.videojs.com/docs/guides/plugins.html) -- link "**Video.js API**" in Step 1 paragraph

**Comment by gkatsev** [comment]
Thanks. Can I ask you to re-open this issue against the [docs](/videojs/docs) repo? Would be greatly appreciated. Thanks.

**Comment by allienworks** [comment]
No problem, I originally wanted. But you specifically asked to file issues here :)

**Comment by gkatsev** [comment]
hehe, yeah, this issue seems to be specific to the docs generator thing so would be more appropriate there. Thanks.
