### ISSUE TITLE
Flash tech doesn't load

### ISSUE THREAD

**Issue by whs** [videojs/video.js#3055]
With `data-setup='{"techOrder": ["flash"]}'` (or specifying it in the option object) the swf is loaded, but doesn't play the video or fire ready event.

Test case:

Both are the same, but one doesn't have flash force loaded. Notice that without Flash, the alert message will fire while the Flash one doesn't.

- **With flash:** https://jsfiddle.net/rLzjqmsy/
- **Without flash:** https://jsfiddle.net/jc8mhfr0/

Environment:

- **User agent:** Repository installed Chromium 64 bit on Arch Linux. Flash installed from aur/chromium-pepper-flash. `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36`
- **Flash:** 20.0.0.286

(Background: I'm trying to load RTMP live stream in a Chrome extension, but found that it doesn't work. I tried to reduce the problem and found that even with the most basic option, the flash tech never worked.)

**Comment by whs** [comment]
Tested on Chrome `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36` and found the same issue. I made sure that this time uBlock is disabled. The only message in console is

```
Mixed Content: The page at 'https://fiddle.jshell.net/rLzjqmsy/show/' was loaded over HTTPS, but requested an insecure video 'http://vjs.zencdn.net/v/oceans.mp4'. This content should also be served over HTTPS.
```

**Comment by mister-ben** [comment]
First, forget using JSFiddle with Flash. The results pane is a heavily restricted sandboxed iframe which blocks javascript access to the Flash tech. You can use similar site JSBin with their standalone preview links like http://output.jsbin.com/ceqatu. Their inline preview has the same limitations as JSFiddle, click ↗ to bust out of that. You *may* have similar sandbox-type restrictions to deal with in a Chrome extension, I can't say I've tried.

Second, do make sure you're using HTTPS resources on an HTTPS page. The same videos you are using are available over HTTP and HTTPS, so you can use protocol relative URLs like `//vjs.zencdn.net/v/oceans.mp4`.

Third, specify the source as a separate `source` element with a `src` and `type`. The Flash tech won't load a source specified as the `video`'s `src` attribute, which may be a bug as that worked in v4 with simple HTTP(S) MP4 sources. However even in v4 this wouldn't have worked for your RTMP case as that definitely needs the `rtmp/mp4` or `rtmp/flv` `type` to be specified to be handled correctly, and you do need a `source` element for that:

    <video id="video" class="video-js vjs-default-skin" autoplay controls data-setup='{"techOrder": ["flash"]}'>
      <source src="rtmp://example.com/searver&mp4:stream.mp4" type="rtmp/mp4"></source>
    </video>

Lastly, just as a survey question really, why do you choose RTMP live streaming over HLS?

**Comment by whs** [comment]
I suppose it is a problem with the CSP then. I'm not familiar with Flash so I couldn't check whether ExternalInterface works in CSP environment.

I'm closing this issue as it seems to be a problem with my environment.

For the reason I use RTMP: I'm making an extension for a live streaming site similar to [BetterTTV](https://nightdev.com/betterttv/) and I'm looking to make a player pop out option. As the site offer no embed script, scraping RTMP URI is the only way it could work.

The site just officially launched HLS support today, but it seems to have higher delay (30s+ over around 2-3s with RTMP) which is one of the major selling point of the site.

**Comment by Haraldson** [comment]
Did you ever find out more about your issue, @whs? I’m experiencing something similar in Electron – the player and swf loads, but then doesn’t play the video, and the error message I get is useless.
