### ISSUE TITLE
application/x-shockwave-flash support

### ISSUE THREAD

**Issue by shachr** [videojs/video.js#3057]
I'm getting a dynamic source and a mime-type, when I receive a SWF file and mime-type of: 'application/x-shockwave-flash', the following is being thrown: 
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video. MediaError {code: 4, message: "No compatible source was found for this video."}

code:
`
                                    player.src({"type":mediaFile.mimeType, "src":mediaFile.fileURL});
                                    player.play()
`

also tried:
`
                                    player.src(mediaFile.fileURL);
                                    player.play()
`

is it possible to play a swf file? 
Thanks,

**Comment by mister-ben** [comment]
It's not. SWF is not a video format.
