### ISSUE TITLE
play icons and control bar icons are broken

### ISSUE THREAD

**Issue by hatchbee** [videojs/video.js#3058]
Hi there, I am new to videojs.

I am trying to use the library on my page to render HTML5 players and to make custom playlist kind of application, but somehow the icons on the video player is getting overwritten with some weird texts
 
![image](https://cloud.githubusercontent.com/assets/5522264/12726008/55cd8e06-c8e3-11e5-89c6-a02eb9de1e76.png)

Also, my page have font styling of Open Sans, I am not able to figure out why this is happening so.. 

Thanks very much!

**Comment by gkatsev** [comment]
Looks like a character encoding issue.
Make sure you have `<meta charset="utf-8">` set in your page.
Also, what version of videojs are you using? We recently released a version that is supposed to address this sisue.

**Comment by hatchbee** [comment]
Hi @gkatsev ,

I am already using `<meta charset="utf-8">` on my page.

I am using videojs version `5.0.0`
