### ISSUE TITLE
.ts stream not playing

### ISSUE THREAD

**Issue by amohideen** [videojs/video.js#3059]
I was trying a test.. below is the code

        <meta charset=utf-8/>
        <link href="http://vjs.zencdn.net/5.5.3/video-js.css" rel="stylesheet">
    </head>
    <body>
        <video id=example-video width=640 height=320 class="video-js vjs-default-skin" controls>
        <source src="http://dammikartmp.tulix.tv/slrc1/slrc1/chunklist_w747273608.m3u8" type="application/x-mpegURL">
        </video>
        <script src="http://vjs.zencdn.net/5.5.3/video.js"></script>
        <script src="videojs.hls.js"></script>
    <script>
    var player = videojs('example-video');
    player.play();
    </script>

    </body>

the source chunklist_w747273608.m3u8 play list contains
 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:15
#EXT-X-MEDIA-SEQUENCE:3072
#EXTINF:10.0,
media_w747273608_3072.ts
#EXTINF:10.0,
media_w747273608_3073.ts
#EXTINF:10.0,
media_w74727360

however I was able to play hls

**Comment by gkatsev** [comment]
Hi, can you re-open this issue against the [`hls` project](/videojs/videojs-contrib-hls)?
Also, please include which version of contrib-hls you are using and what is happening when you try to play? Are you getting errors or anything else. Thanks.

**Comment by amohideen** [comment]
The player progress just keeps on circling. I will open a new thread on the hls project.. cheers
