### ISSUE TITLE
menus aren't getting sized correctly anymore

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#3062]
vjs-menu's width is set to 0 but vjs-menu-content is supposed to be set to 24em but ends up getting set to 'inherit', so, menus aren't showing up properly, at least for the chapters menu.
also, `vjs-selected` isn't getting applied properly to the selected element.

**Comment by smilemd** [comment]
+1

**Comment by kylegilman** [comment]
I just discovered this problem too. Menu sizing and vjs-selected works in 5.5.3 but not in 5.6 and later.

**Comment by jorydekort** [comment]
When initialising videojs using javascript (see #3151 ) and changing css line 1131 in video-js.css by removing:

```
.vjs-chapters-button .vjs-menu {
  left: -10em;
  width: 0; }
```

The popup now shows! How ever the header is at the bottom. This should be on top of the list.

**Comment by jorydekort** [comment]
Sorry to keep posting here. But maybe other people are searching for a solution to this as well. Changing line 3578 in video.js from (in v7.2.1):

```
// Add the UI object's element to the container div (box)
// Having an element is not required
if (typeof component.el === 'function' && component.el()) {
      var childNodes = this.contentEl().children;
      var refNode = childNodes[index] || null;
      this.contentEl().insertBefore(component.el(), refNode);
}

````

to (from v5.2.1):

```
// Add the UI object's element to the container div (box)
// Having an element is not required
if (typeof component.el === 'function' && component.el()) {
      this.contentEl().appendChild(component.el());
}

```

seems to fix the order issue where the title shows above the list of items under Chapters.

**Comment by smilemd** [comment]
How about with vjs-selected? it seems that vjs-selected is not fixed.

**Comment by gkatsev** [comment]
It seems to be getting applied correctly for me now, @smilemd.
Can I ask about your setup? Would be good if you can put together a reduced test case.

**Comment by smilemd** [comment]
@gkatsev , i'm not very familiar with reduced test case, but i'll try to explain...

i use video.js + https://github.com/kmoskwiak/videojs-resolution-switcher

till the ~5.5.0 version vjs-select was working, here is an example:

![vjs550](https://cloud.githubusercontent.com/assets/6599359/14506232/6b89b236-01c5-11e6-920c-eb01b9090fe3.jpg)

Later, vjs-select isn't applied:

![vjs590](https://cloud.githubusercontent.com/assets/6599359/14506281/a40e3b9a-01c5-11e6-8775-fc76dab56eec.jpg)

**Comment by smilemd** [comment]
sorry, it seems to be a videojs-resolution-switcher bug.
