### ISSUE TITLE
Donate videojs-youtube to videojs organization

### ISSUE THREAD

**Issue by eXon** [videojs/video.js#3065]
Hey there,

I would like to donate to the videojs organization the YouTube tech plugin. I do not longer have the time to give the proper support because I'm awefully busy with other projects and I feel bad for those in needs of fixes.

Since this tech is very popular, I though it will be better to donate it to the videojs organization instead of ignoring it until it dies.

I can also donate the videojs-vimeo plugin, but it's not as near used and have not been upgraded to work with VJS 5.

@heff @gkatsev What are your though on that?

**Comment by gkatsev** [comment]
That sounds fine to me. We've been trying to do some stuff around an [open governance](https://github.com/videojs/video.js/wiki/Governance) that I would probably like to have happen before this would go through.
@videojs/core-committers any thoughts?
If we do this, would we keep `videojs-youtube` named that way to keep it more separate than the contrib plugins like `contrib-ads` and `contrib-hls` or would we adopt it fully and rename it to `videojs-contrib-youtube`?

**Comment by heff** [comment]
Sorry to hear that @eXon! Hope we can still count on you for some occasional help.

This sounds ok to me. I could go either way on the naming. We might throw people off if we rename it now. On the the other hand it would make it more prominent in the plugins.

**Comment by eXon** [comment]
Hey @heff,

It's more about making sure the users are getting proper support and isn't all about me. I hate when a user want to use it in production but just can't and the bug issue takes a month or two before getting a simple fix. 

I'll be happy to stay as a contributor but I think this tech deserves more attention than the time I'm able to give.

**Comment by gkatsev** [comment]
Wow, it's been a long time since we looked at this. Sorry about that.
@eXon I assume you still want this to happen? If so, want to add me as an admin on that repo?
I'm going to be spending the afternoon looking at issues.

**Comment by gkatsev** [comment]
Also, just wanted to formally announce that we accept @eXon's proposal to donate the repos to the videojs organization.
We're sorry to see you go @eXon but hope that you'll come back some time in the future when the time is right. We appreciated your work and input on videojs 5.0 and, of course, the videojs-youtube tech.
