### ISSUE TITLE
Access Plugin on runtime

### ISSUE THREAD

**Issue by KingSora** [videojs/video.js#3067]
Hello,

I am building a plugin, but I cant find a way to access that plugin on runtime. I need this because I want to change the plugin settings on runtime, for any videojs instance.

I hope someone can help me.
Best regards!

**Comment by mmcc** [comment]
When you say "on runtime", what do you mean? After initialization?

**Comment by KingSora** [comment]
exactly

**Comment by mmcc** [comment]
You'll need to handle that kind of situation yourself, but you have a few options.

1. At plugin initialization, have the plugin create a new object on the player aside from itself. This violates the whole "don't modify things you don't own" rule, so be careful. For example, you have a plugin you want to be called `foo`, so you make the plugin initialize as `fooInitializer` (or something). During initialization, that adds `player.foo()`, which is what can be called to update options.

2. Have the user initialize the plugin directly and have it return the new plugin instance.

    ```
    var player = videojs('my-player');
    var yourPlugin = player.yourPlugin();
    
    // ...later
    yourPlugin.whateverThingToUpdateOptions({ /* new options */ });
    ```

3. Have your plugin replace itself on the player prototype after initialization.

**Comment by gkatsev** [comment]
This is something that we'll be looking into fixing as part of the new plugin work I want to do.
Also, just wanted to add that `videojs-contrib-ads` has chosen to go with option # 3 but they're all valid.

**Comment by KingSora** [comment]
I think I will go with option 3, but can you help me to accomplish this? - I dont really know how to do that. I simple examplecode would do it.

**Comment by mmcc** [comment]
@KingSora Your best bet is to take a look a the source for [videojs-contrib-ads](/videojs/videojs-contrib-ads) and see how that project does it, but it's really as simple as just replacing the plugin object on the player [with a new one](https://github.com/videojs/videojs-contrib-ads/blob/master/src/videojs.ads.js#L359). As @gkatsev mentioned, this is something we'd like to document / support better in the near future.
