### ISSUE TITLE
Caption Settings Appear Below Player When Using "Fluid: True"

### ISSUE THREAD

**Issue by mcbanderson** [videojs/video.js#3069]
The caption settings pop-up menu is appearing below the player when using "'fluid': true" instead of overlaying the player. It appears this is a result of the padding that is being applied to the player by the fluid option. A possible solution is to use absolute positioning of the menu when the fluid option is being used.

**Comment by mcbanderson** [comment]
Here is a fiddle demonstrating the problem:

https://jsfiddle.net/qxv81akt/2/

**Comment by gkatsev** [comment]
This has since been fixed.
