### ISSUE TITLE
TextTrackList doesn't work in IE8 with minified version.

### ISSUE THREAD

**Issue by steplerbox** [videojs/video.js#3070]
TextTrackList constructor: https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-list.js#L22
In bundled version constructor function is turning from function expression to named function expression:
`var TextTrackList = function TextTrackList(tracks)`
And In minified version it's getting different name:
`n = function p(a) {`
In IE8 p.prototype is not n.prototype, so IE8 hook does not work properly.

**Comment by gkatsev** [comment]
[nooooooo](http://www.nooooooooooooooo.com/)

Also, could possibly be related to #3064.

**Comment by gkatsev** [comment]
Closed by a2f5430
