### ISSUE TITLE
IE10: Text track display prevents clickthroughs on ads, even when not displaying anything

### ISSUE THREAD

**Issue by incompl** [videojs/video.js#3072]
Probably because IE10 doesn't support pointer-events.

One solution might be to remove or resize the text track display when not showing anything.

**Comment by gkatsev** [comment]
We could possibly hide it if `captions-off` is selected but otherwise, we can't really do anything.
Ad techs should probably make sure to get their elements insert above the text track display.

**Comment by robertoamici** [comment]
Non-native tracks add a big div that covers the entire video element, which also prevents the click-the-video-to-pause behaviour (as mentioned, even when there are no text tracks to show)

**Comment by gkatsev** [comment]
We've dropped support for IE10 and lower in Video.js 7. Since we've been OK with it as it was, I'm closing this issue.
