### ISSUE TITLE
Supporing MMR streaming to overcome VDI Issues

### ISSUE THREAD

**Issue by winterfellzone** [videojs/video.js#3073]
Well, there are a lot of big guys out there implementing VDI infrastructures, but still no support for video streams playback over VDI clients, especially due to the VDI protocols character.
There is no known player that support MMR (HTTP-Based Redirection), which is able to contain and request it's streams to be recieved from an other channel than the VDI - Redirect it through a thin client to a VDI vm.
It looks like it can be a very beneficial feature.

**Comment by gkatsev** [comment]
Hi, thanks for the question.
It's unlikely that videojs will implement or accept an implementation of MMR into core videojs. However, videojs is made in a way that you can create Techs that allow you to add various technology into the player. For example, the [youtube tech](https://github.com/eXon/videojs-youtube). You can use this tech system to create a custom playback tech that uses MSE to implement things like HLS streaming in the browser which is what we've done with the [contrib-hls](/videojs/videojs-contrib-hls) project -- which is actually a Source Handler, a subset of Techs.
We'll be happy to help answer questions about how Techs and Source Handlers work if you were to attempt to make such a project.
Thanks.
