### ISSUE TITLE
Add `player.currentWidth` and `player.currentHeight`

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#3074]
# Purpose
We've recently had [a](2282) [lot](2983) [of](3008) [questions](3045) about using `player.width` and `player.height` and getting back values like 0 (zero) or unexpected values. Because of the rise in issues and the usefulness of knowing the computed style of player, we want add this functionality to videojs.
This would also help the user from having to do browser specific tests themselves, see the previous solutions section.
# Background
The dimension methods on the player, and actually most methods on it, are designed to mimic the native attributes on the video element. So, in the same way that `player.currentTime()` is a method that is similar to `video.currentTime`, `player.width()` is similar to `video.width`. This mean that `player.width()` return the value that the player is *configured* with. For example:
```html
<video width=1280 height=720 src="oceans.mp4></video>
```
In videojs 4.0, the dimension methods were a bit less strict and so when the dimensions were set to `auto` or were not set directly, `player.width` ended up returning more or less the computed style
# Previous solution
Previously, we've told users to use `getComputedStyle` with the player element. The user would also have to know to use `el.currentStyle` fallback for IE8.
# Proposal
We want to mirror the way that `width` and `height` currently work with the dimension methods.
## API Spec
**All these methods are only getters.**
* `Component`
  * `Component.prototype.currentDimension(widthOrHeight) -> Number` - It takes a string value of either `width` or `height` to return back the appropriate value
  * `Component.prototype.currentDimensions() -> Object{width: Number, height: Number}` - Returns an object with `width` and `height` properties
  * `Component.prototype.currentHeight() -> Number` - Delegates to `Component#currentDimension` to get back the height value
  * `Component.prototype.currentWidth() -> Number` - Delegates to `Component#currentDimension` to get back the width value
* `Player` - We probably don't need to make any changes in the player because it extends from component and will inherit the functionality from it.

## API Details
`currentDimensions` should use `getComputedStyle` where-ever possible. If necessary, mostly for ie8's sake, it should delegate to `el.currentStyle`, at least, while we support IE8.

# Acceptance Criteria
* [ ] All the methods from the API Spec section are implemented
  * [ ] `Component#currentDimension`
  * [ ] `Component#currentDimensions`
  * [ ] `Component#currentHeight`
  * [ ] `Component#currentWidth`
* [ ] The current* methods work in all browsers that videojs supports: IE8+, Firefox, Chrome, Safari, iOS, Android.
* [ ] There are thorough unit tests for the each of the functions
  * [ ] `Component#currentDimension`
  * [ ] `Component#currentDimensions`
  * [ ] `Component#currentHeight`
  * [ ] `Component#currentWidth`

------------------
Note: `Component#currentWidth` is shorthand for `Component.prototype.currentWidth`.

**Comment by misteroneill** [comment]
Looks reasonable to me. :+1:

**Comment by heff** [comment]
Sounds ok to me. Nice writeup. The player dimensions get pretty complex when it comes to the responsive options and how we set everything with CSS, but I think that's more on the setter side of things.

**Comment by gkatsev** [comment]
Yep, these are strictly getters, so, the function should be super simple actually.

**Comment by gkatsev** [comment]
@defli sorry it took so long but here's the writeup for the new functionality if you want to give it a shot.

**Comment by defli** [comment]
@gkatsev thanks :) I wiil take a look.

**Comment by gkatsev** [comment]
@defli hey, just wanted to check in to see if you were able to find the time for this?

**Comment by defli** [comment]
@gkatsev sorry, It is in my mind, I will take a look tomorrow and the weekend.

**Comment by defli** [comment]
@gkatsev I have opened a PR.

**Comment by gkatsev** [comment]
This has been added.
