### ISSUE TITLE
Ignore Colors Setting on IE and FF causes controls to disappear

### ISSUE THREAD

**Issue by vdeshpande** [videojs/video.js#3075]
Internet Explorer and Firefox have accessibility settings that let customers turn off custom colors and background images in order to increase contrast on web pages. When this happens, the sliders become invisible and the fullscreen button's icon disappears.
While the slider does disappear, you can actually hover in the area and see the duration and current time pop-ups.

_1) Goto Preferences --> Content -->Colors --> Check the Use System Colors Box and set Override options to Always.
2) Hit OK and observe the player._

**A proposed solution to this as follows:**
We will need to get the computed styles for the particular element in question, and then compare the computed value with the actual value.
What this basically does is this if we get a value of white from the computed style or we can even alter the logic slightly by checking if the value is anything other than default colors then we can assume that the user has turned ON the setting for system colors within the browser, and we can then proceed to invert the colors.
`window.getComputedStyle(document.getElementsByClassName("CLASS_WHICH_WE_WANT_TO_TARGET")[0]).backgroundColor`

> If we use class name for example vjs-play-progress" we get a value "rgb(255, 255, 255)"
> which means the color has changed to white and the accessibility mode of system colors has been turned ON

**Comment by gkatsev** [comment]
I don't think there's really a way for us to handle this without a massive re-write of our control bar which we're not ready to do just yet. Closing for now.
