### ISSUE TITLE
Fluid with Big Play Button

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#3082]
Hi Guys

Loving the Fluid option, but there's one issue that arises when combining it with Big Play Button (in our case centred).

With Fluid you obviously don't need to specify a width and height in the Video tag input to VJS. But if you don't supply dimensions, then the Big Play Button noticably appears at the Top of the screen until it relocates to the Centre of the screen. Note the Poster does NOT do this (Case 1 below).

If you specify dimensions (although not needed as they are completely ignored of course for fluid sizing) then the Big Play Button does not appear at the top of the screen, instead it waits until initialisation is finished before only showing correctly in the Centre of the screen (Case 2 below)

Here's our reduced test cases:
https://living.video/fluid1.html
https://living.video/fluid2.html

Adjust the browser window to any size and repeatedly refresh in each case to see the issue. Note that this seems to apply in Chrome and Firefox (latest versions), but not in IE or Edge.

The Big Play Button seems to Display too early in the initialisation which makes this very obvious and not desirable. Obviously supplying (unneeded) dimensions as a hack isn't ideal, but I would guess a couple of possible fixes would be:

1) Create but then Hide the Big Play Button until after last step in initialisation, then UnHide it.
2) Make the Big Play Button creation the last item in initialisation.

Is there a simple fix in the SRC your end to make the Big Play Button always show only as the last step in the process. The poster doesn't have the same issue of repositioning, so I'm guessing it's a sequence or timing issue. Supplying spurious dimensions seems wrong as a hack?

Richard

**Comment by gkatsev** [comment]
I'm guessing the issue is that the big play button is created before the player div ends up getting sized. So, the big play button's CSS sounds like it is working correctly. Since it calls for 50% top and 50% left on an absolutely positioned div.
This is an interesting case that we probably didn't think about for the center-positioned element. I do agree we probably should fix it because having it flash from top to middle isn't nice.
A simple solution could be to hide the big play button until the player is ready.

**Comment by ingles98** [comment]
I see this was closed, was it ever actually fixed tho ? I'm having the same issue where sometimes the button just doesn't ever appear.

**Comment by gkatsev** [comment]
@ingles98 you're replying to a really old issue. If you have some problem, can you please create a new issue with as much detail as you can provide, ideally with a live minimal test case you can share.
