### ISSUE TITLE
Keep localisations up to date

### ISSUE THREAD

**Issue by mister-ben** [videojs/video.js#3085]
There are now a few strings that are not in all or most of the lang files. Some used with `localize()`:

- 'Play video' - Big play button
- 'Close' (or 'Close dialog') - Close button
- 'Modal Window' - Modal dialog
- 'This is a modal window' - Modal dialog
- 'This modal can be closed by pressing the Escape key or activating the close button.' - Modal dialog

Plus a couple more set with `controlText`, which the component should localise:

- `', opens ' + options['kind'] + ' settings dialog'` - Captions settings menu
- ', selected' - Menu item

Would the easiest approach be to keep an en.json up to date? It should be more obvious that other lang files are missing entries.

Also, "dialog", "modal window" and "modal" being used interchangeably. Would that be confusing to screen reader users?

**Comment by gkatsev** [comment]
Having an `en.json` sounds like a great idea.
We should probably update all usages of modal dialog, dialog, modal, window, etc, to be consistent.

**Comment by gkatsev** [comment]
I'm going to close this as it's been "fixed" by #3096.
