### ISSUE TITLE
Can't close CC button on iPad in browser mode

### ISSUE THREAD

**Issue by marguinbc** [videojs/video.js#3087]
When viewing the player on an iPad in browser mode, once you click the CC button, you cannot make it go away.

Steps to reproduce:
1) View player with captions in browser mode on ipad
2) Tap CC button to open captions menu
3) Select an option ('english', captions off)
4) Tap CC button to dismiss

Expected behavior: Captions menu closes but CC button maintains focus

Actual behavior: Captions menu remains open.  Even after the control bar hides due to inactivity, when it appears again, the captions menu is still open.

Tested on vjs 5.7.0 and an iPad 3 on iOS 9.2.x (latest)

**Comment by OwenEdwards** [comment]
@marguinbc any chance you can confirm this fixes the problem you reported? Then we can close this issue.

**Comment by marguinbc** [comment]
@OwenEdwards, using a fresh build of vjs 5.8.5 on iPad in browser mode, I am no longer seeing a captions button.  Captions are displaying but I can't turn them on or off...  When I go to fullscreen/native I see the captions button and everything is hunky dory.

I've even messed with the browser size in case the controls were being hidden due to player width but at 1024px wide, still no captions button visible.  For my test file, I was just using index.html sample in the sandbox dir.

**Comment by OwenEdwards** [comment]
Closed by #3158.
