### ISSUE TITLE
Content of http://docs.videojs.com still refers to video.js 4

### ISSUE THREAD

**Issue by svetlin-mladenov** [videojs/video.js#3091]
It seems that the content of http://docs.videojs.com hasn't been updated for a long time. For example: http://docs.videojs.com/docs/guides/setup.html still refers to video.js 4 altought the content of [setup.md](https://github.com/videojs/video.js/blob/master/docs/guides/setup.md) has long been updated to refer to video.js 5.

I don't completely understand the relation between http://videojs.com/getting-started/ and http://docs.videojs.com/ but if `docs.videojs.com` is deprecated than you should remove the link from http://videojs.com (the `docs` button).

PS. I tried disabling the browser case and getting the page using curl and the results were the same so I don't think that this is a client caching issue.

**Comment by gkatsev** [comment]
The docs that are available come from the `docs` directory in this repo, and unfortunately, it is a bit out of date.
The getting started page should be the new starting point if you're looking at where to start.
I have plans to go through and update the docs and guides but would appreciate any help.
Hope that helps, thanks.

**Comment by svetlin-mladenov** [comment]
The [official videojs website](http://videojs.com/) contains a muxture of up-to-date and outdated information. Isn't this a problem? Why did you close this issue?

If a novice user, who doesn't know about videojs versions, visits the website and clicks the `docs` button then they will end up using videojs 4. If they click `start` they will use videojs 5.

**Comment by gkatsev** [comment]
I closed it because we're already aware of the issue and have plans to update the docs. I didn't close it because we weren't going to fix it. And fixing up docs already has a bunch of issues for various parts of it.

**Comment by gkatsev** [comment]
Actually, now that I'm thinking about it, I'm going to open this to track removal of vjs 4 stuff from docs.
If you have any specific vjs4 only stuff that is no longer applicable, if you could list them, that would be great.

**Comment by clark-stevenson** [comment]
Thanks for this, I was having the trouble of not really knowing what was what, as it was my colleagues nature to go to docs, while I was going to getting started so we were not on the same ball park.  

I would honestly prefer the complete removal of that `docs` button or have it go to `getting started` but I obviously have no regard for users of previous versions etc.  So it is not that simple.

**Comment by gkatsev** [comment]
most of the info in the docs generally still applies to v5 of the videojs as well.
But yes, we do need to update all the docs and change all the references to point at vjs5 and remove parts that no longer apply.

**Comment by gkatsev** [comment]
We'll be working on documentation soon. Closing in the meantime.
