### ISSUE TITLE
Full width progress control & flexbox

### ISSUE THREAD

**Issue by dlo83** [videojs/video.js#3094]
Hi there, does anyone have any tips for getting the progress control to sit above the rest of the controls, as in the previous default skin in Video.js 4.x?  With the shift to flexbox for layouts, I can't think of a way to have the progress control wrap the trailing and leading controls down.

Thanks!

**Comment by mmcc** [comment]
Flexbox actually makes this a crap ton easier (to use the official terminology) without breaking everything else. You just need to remove the progress control from the flow (via absolute position, for example), and all the other components should simply reflow as necessary.

I made a [Twitch-like skin](https://github.com/mmcc/videojs-skin-twitchy) that does this, ([example](https://mmcc.github.io/videojs-skin-twitchy)). It's a little out of date, but the only real difference is now you can / should use the spacer element to push things to the right by setting it to auto so it fills the void left by the progress bar.

**Comment by dlo83** [comment]
Thanks!

On Tue, Feb 9, 2016 at 5:52 PM, Matthew McClure <notifications@github.com>
wrote:

> Flexbox actually makes this a crap ton easier (to use the official
> terminology) without breaking everything else. You just need to remove the
> progress control from the flow (via absolute position, for example), and
> all the other components should simply reflow as necessary.
>
> I made a Twitch-like skin <https://github.com/mmcc/videojs-skin-twitchy>
> that does this, (example <https://mmcc.github.io/videojs-skin-twitchy>).
> It's a little out of date, but the only real difference is now you can /
> should use the spacer element to push things to the right by setting it to
> auto so it fills the void left by the progress bar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/3094#issuecomment-182119755>.
>



-- 
Thanks,

Dan Lourenço

**Comment by tmm1** [comment]
None of the "style 1" skins on http://www.scriptsmashup.com/Video_Skin_Generator/Videojs/videojs-skin-generator.html, nor the videojs-skin-twitchy referenced above, show a full-width progress bar on video.js 5.19.2

**Comment by tmm1** [comment]
Here's a working stylesheet for v5.19.2: http://stackoverflow.com/a/43767895/332798
