### ISSUE TITLE
videojs().play() silently fails for the Flash tech when called before videojs is ready.

### ISSUE THREAD

**Issue by svetlin-mladenov** [videojs/video.js#3099]
Steps to reproduce:
Create a videojs instance configured to use the `flash` tech and autoplay turned off. Call `play()` before the instance is ready . Here is the code I am testing with:

```html
<!DOCTYPE HTML>
<html>
<head>
  <link href="http://vjs.zencdn.net/5.6.0/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/5.6.0/video.js"></script>
  <!-- <link href="http://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.12/video.js"></script> -->
</head>
<body>
  <video id="my-video" class="video-js vjs-default-skin" controls preload="auto" width="640" height="264">
  </video>
  <script>
    videojs('#my-video', {"techOrder": ['flash']}, function() { });
    videojs('#my-video').src({type: 'video/flv', src: 'http://www.sample-videos.com/video/flv/480/big_buck_bunny_480p_30mb.flv'});
    videojs('#my-video').play();
  </script>
</body>
</html>
```

Expected behavior:
After the player gets ready it should commence playing.

What went wrong:
The player remains paused.

The issue is present only with videojs 5. With videojs 4 everything works as expected. Comment out the include of video.js 5.6.0 and uncomment the include of videojs 4.12 to test.

I looked into the documentation and the implementation of videojs().play() and it seems that this behavior is indeed defined and should be supported. If the tech is not ready the code in [player.js](https://github.com/videojs/video.js/blob/master/src/js/player.js)  waits until it is and then calls `play` of the current tech. When debugging I noticed that the call fails silently on the flash side.

Workaround:
specify `autoplay: true` or call the play method in the videojs ready callback.

**Comment by gkatsev** [comment]
This is no longer an issue with Video.js 6 and newer.
