### ISSUE TITLE
CDN is no longer working.

### ISSUE THREAD

**Issue by kenmazaika** [videojs/video.js#3102]
The documentation here says the javascript file is hosted on a CDN.

http://videojs.com/getting-started/

It references the following file:
http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js

Yet it looks like there is an amazon hosting error.

**Comment by gkatsev** [comment]
Looks like we forgot to get that version published on the CDN. I'll take care of that right now. Thanks.

**Comment by gkatsev** [comment]
Alright, should be up now.

**Comment by kenmazaika** [comment]
Thanks!
