### ISSUE TITLE
VideoJS skin

### ISSUE THREAD

**Issue by JasterTDC** [videojs/video.js#3103]
Can I set videojs with an empty skin?

**Comment by gkatsev** [comment]
Hi, can you elaborate on what you mean?
You can always include videojs and not include the css for it.

**Comment by mmcc** [comment]
Or, if you don't want controls at all, just don't include the `controls` attribute on the `<video>` tag (or set `controls` to false).

**Comment by designbyadrian** [comment]
The controls attribute is set on my <video> element by VideoJS even if my setup option is *false*...

**Comment by gkatsev** [comment]
@designbyadrian Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? Also, what version of videojs, browser, and OS are you testing on? I'm unable to reproduce.

**Comment by designbyadrian** [comment]
I'm terribly sorry. I'm feverish and had the device emulator on in Chrome!

--  
Design by Adrian Ltd.
Sent with Airmail
