### ISSUE TITLE
access to video.min.js.map is forbidden

### ISSUE THREAD

**Issue by frontendschlampe** [videojs/video.js#3106]
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) https://vjs.zencdn.net/5.4.6/video.min.js.map

see ticket https://github.com/videojs/video.js/issues/700

OsX El Captain
Safari 9.0.3

http://stackoverflow.com/questions/18407543/video-js-map-throwing-a-404-not-found

**Comment by gkatsev** [comment]
hm... I thought we got that taken care of.

**Comment by tjbee** [comment]
Has this been resolved?

**Comment by gkatsev** [comment]
Nope, unfortunately, still an issue.

**Comment by gkatsev** [comment]
Will be fixed once videojs 3.12 is released as part of #3445. Closing.

**Comment by jemoreno** [comment]
This is still an issue

**Comment by gkatsev** [comment]
What version of videojs is it still an issue for?

**Comment by jemoreno** [comment]
http://vjs.zencdn.net/5.8/video.js.map
http://vjs.zencdn.net/5.9/video.js.map
http://vjs.zencdn.net/5.10/video.js.map
http://vjs.zencdn.net/5.11/video.js.map

They all return a 403 error

**Comment by jemoreno** [comment]
any update on this?

**Comment by gkatsev** [comment]
This will be removed from 5.11 soon (https://github.com/videojs/video.js/pull/3710) and already isn't available in 5.12. We'll consider adding *proper* sourcemaps sometime later.
