### ISSUE TITLE
Also live if duration is Number.MAX_VALUE?

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#3111]
Apparently dash.js uses `Number.MAX_VALUE` for the duration of live video streams, because of a bug in Chrome. See https://github.com/Dash-Industry-Forum/dash.js/issues/428

However, if we then use video.js the stream is not considered to be live and produces a very useless progress seekbar (`1.7e308` is quite big...).

Could we also assume live if the duration is `Number.MAX_VALUE` and/or very close to it?

I could create a PR if wanted :).

**Comment by nickygerritsen** [comment]
For now I've added a check in my own code that changes the duration to `Infinity` if it is `Number.MAX_VALUE`, but this gives a small UI flicker.

**Comment by gkatsev** [comment]
I think it would be best if we can fix this just in contrib-dash. The spec asks for live streams to have a duration of Infinity. The source handler should be able to fix this and keep it contained.
Closing this in favor of videojs/videojs-contrib-dash#35.
