### ISSUE TITLE
Player keeps loading playlist even if player is in paused state.

### ISSUE THREAD

**Issue by erarjit** [videojs/video.js#3113]
We are using m3u8 playlist for playing live video on video.js (v4.12.7) and on other devices. Our playlist doesn't contain #EXT-X-ENDLIST (which marks playlist end). This had to be done to support live video for other devices.

The issue is- Even after clicking pause button the playlist keeps loading. video segments don't download anymore but playlist does.

**Comment by gkatsev** [comment]
Are you using videojs-contrib-hls? If so, please re-open the issue against that.
Also, videojs 4.12.7 is very old and we're very unlikely to make changes to fix things related to it or any libraries that target 4.12.x. contrib-hls does have a videojs 5 compatible version.
Thanks.

**Comment by erarjit** [comment]
Thanks for reply @gkatsev.

Yes, we are using videojs-contrib-hls.

4.12.x to 5 will be a big migration. I tried that locally but it didn't work straight away.
