### ISSUE TITLE
Provide unbundled code

### ISSUE THREAD

**Issue by AlicanC** [videojs/video.js#3114]
The files in the "dist" directory are bundled. This causes bloat because they get re-bundled and also prevents shared dependencies from being optimized.

The dist directory should actually be the transpiled (but not bundled) version of the "src" directory in CommonJS format. (Just like a regular Node.js application.)

**Comment by gkatsev** [comment]
Yep, we have plans for that. It's being tracked in #2750.
Also, just wanted to mention that videojs doesn't use that many dependencies and the few it does use are unlikely to be used by others as well, so, the size savings aren't actually that big, I don't think.
