### ISSUE TITLE
VideoJS does not play cached parts of video

### ISSUE THREAD

**Issue by alirezastack** [videojs/video.js#3115]
I have used videojs with source tag in order for videos to be played:

`<source src="http://www.example.com/videos.php?f=8dF-CyWctyOM2SMb6K3bhxybEI3KQH8p.mp4" type="video/mp4">`

When video is rendered until lets say 1 minute and I want to get back to the 30th second, it again sends a request to nginX server in order to get the file and play it.

Why is this happening? I think videoJS should handle this part by its own. If I'm wrong in any way correct me please. Thanks.

This is interesting that videoJS has no problem on Firefox 44.0.2, but the issue is present on Chrome 48.0 (64bit) on OS X.

**Comment by mmcc** [comment]
Is the file actually served through PHP? If so, does your PHP-server implementation support byte-range requests? Can you put up an example for us to take a look at? Do you see the issue with a vanilla video tag (by that I mean, just a `<video>` element without Video.js initialized)?

Without knowing more about the problem this is merely conjecture, but for what it's worth, to this day I've [never seen an issue](https://github.com/videojs/video.js/search?q=PHP&type=Issues&utf8=%E2%9C%93) where someone is serving the file with PHP that the issue hasn't ended up being the PHP implementation.

**Comment by mmcc** [comment]
I'm actually going to close this because I'm pretty confident this isn't a Video.js issue, but if that's not the case we can absolutely reopen.

**Comment by alirezastack** [comment]
Well, yes actually. It is served from PHP, But as I mentioned above in some browsers it is OK and works perfectly. I can fast forward the parts downloaded or backward. If byte-range was not supported on server there shouldn't have been different behaviors on different browsers.

**Comment by mmcc** [comment]
Just because it works on some browsers and not on others doesn't mean there's not a problem. One browser might ignore an issue or handle an idiosyncrasy differently than another, but that simply means your implementation works in one browser and not another.
