### ISSUE TITLE
How to completely disable Flash, while enabling YouTube, so IE works?

### ISSUE THREAD

**Issue by Amstercad** [videojs/video.js#3119]
Having read the current issue, '[Donate videojs-youtube to videojs organization #3065](https://github.com/videojs/video.js/issues/3065)', I'm [cross-posting an issue](https://github.com/eXon/videojs-youtube/issues/362) now to this general videojs issue queue.

With a site that we are developing we have encountered an issue that when we try to play a Youtube hosted video under IE 11 on Windows 7, the video will consistently attempt to fall back to Flash, seemingly crash, and then use the standard Youtube skin (without controls) rather than the desirable html5 video.js player. We discovered that if we disable flash in the IE browser everything works as expected. Unfortunately, as this will be a public website, that will not be a realistic solution.

Our site uses a mixture of self-hosted MP4 videos, MP3 audio files, and YouTube-hosted videos. To completely disable Flash from being used, at the server-level, I've tried every combination of techOrder possible, along with trying to set the techOrder *settings* without Flash like this:

videojs.options.techOrder = ["html5", "youtube"];

I've also tried everything with and without the techOrder option: "sourceOrder": true

None of my efforts to disable Flash at the server-level have been successful. Note that my efforts also include disabling the video-js.swf file from loading in the first place.

Perhaps an answer to this question might resolve the related VideoJS YouTube plugin issues [#342 (Video not playing Internet Explorer](https://github.com/eXon/videojs-youtube/issues/342)), and [#361 (Not compatible with latest video.js 5.7.0?](https://github.com/eXon/videojs-youtube/issues/361)).

Here are examples of the latest VideoJS YouTube plugin working (at least when using pure html5 browsers) and various versions of VideoJS libraries:

http://5-0-2.videojs-test-xyz.org
http://5-1-0.videojs-test-xyz.org
http://5-2-4.videojs-test-xyz.org
http://5-3-0.videojs-test-xyz.org
http://5-4-6.videojs-test-xyz.org
http://5-5-3.videojs-test-xyz.org
http://5-6-0.videojs-test-xyz.org
http://5-7-1.videojs-test-xyz.org

You can also try these same versions without any caching influence:
http://5-0-2.dev.videojs-test-xyz.org
http://5-1-0.dev.videojs-test-xyz.org
http://5-2-4.dev.videojs-test-xyz.org
http://5-3-0.dev.videojs-test-xyz.org
http://5-4-6.dev.videojs-test-xyz.org
http://5-5-3.dev.videojs-test-xyz.org
http://5-6-0.dev.videojs-test-xyz.org
http://5-7-1.dev.videojs-test-xyz.org

The sub-domain URLs indicate which version of the VideoJS library is used, with all else being equal.

What is the appropriate mechanism to prevent Video.js from falling back to flash on the site, to ensure IE only displays videojs using the html5 player, just like other common up-to-date browsers that work well?

**Comment by gkatsev** [comment]
I think this discussion should stay over in https://github.com/eXon/videojs-youtube/issues/362, so, closing.
