### ISSUE TITLE
Announce Big Play Button on first tab into player on IE9 with JAWS

### ISSUE THREAD

**Issue by marguinbc** [videojs/video.js#3121]
The Big Play button is not being announced when using JAWS (version 15/16/17) on IE9. 

When you first tab into the player, the big play button should receive focus and be announced by JAWS. Somehow it is announced when you tab out and back into the BPB (shift+tab).  It also appears to work on other versions of IE and JAWS.

Confirmed this on VideoJS 5.7.1 on IE9 and JAWS 16

**Comment by OwenEdwards** [comment]
@marguinbc is there a specific page this was happening on, or do you have a reduced test case?

I've been doing some investigation of this, and I *think* it's related to some weirdness around the fallback line inside the video element itself:

`<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>`

It seems like the link receives focus, but isn't announced correctly; then the BPB receives focus, and is announced, but then when focus moves back to the link (Shift-Tab), it is announced as the BPB.

**Comment by OwenEdwards** [comment]
@marguinbc see #3187.

**Comment by marguinbc** [comment]
So, it seems that the real issue is what you described in 3187 and the vjs-no-js div causing the issue on IE. If so, I'm thinking this can be closed.
