### ISSUE TITLE
Pattern for displaying tooltips above controls?

### ISSUE THREAD

**Issue by dlo83** [videojs/video.js#3122]
Hi there,

What's the correct pattern for showing a tooltip above a control button with said control's control text?  I'd like to grab the control text from the volume button and dynamically update the tooltip with the status (Mute/Unmute).  Because the new player skin doesn't appear to use the control text, I'm wondering how to grab that data within and display it in said tooltip.  Any insight would be much appreciated.  Thanks!

**Comment by mmcc** [comment]
I think I'm missing something about the question. What do you mean "doesn't appear to use the control text"? All of the components do still have a span with the class `.vjs-control-text`, including the mute button.

We should probably abstract these styes into a tooltip class, but if you're implementing this right now I'd start with the [current tim tooltip](https://github.com/videojs/video.js/blob/52453351478b26c2d06f0cc3fe12fe59f6a1eb23/src/css/components/_progress.scss#L84-L98) as a reference.

**Comment by dlo83** [comment]
@mmcc Sorry if I wasn't clear.  I'm aware all of the components have that span with a .vjs-control-text class.  I did see the current time tooltip, but the problem is, in that example, the content property accesses a dynamic data attribute. No such data attribute exists for volume, correct? If that is indeed the case, I can't see how I can access the dynamic content of the span ("mute" vs "unmute") in my tooltip.

Cheers!

**Comment by mmcc** [comment]
Ah right, sorry about that. No I didn't mean literally use CSS `content`, since those don't have data-attrs, I just meant the related styles. You'll need to actually pull in the status via JS, but we can revisit adding data-attrs to other components as well in the future.
