### ISSUE TITLE
IE11 - currenTime()  and waiting wheel problem

### ISSUE THREAD

**Issue by calanor** [videojs/video.js#3124]
In IE11 when call currenTime( seconds ) to go to a certain point, the image of the waiting wheel image remains and does not disappear. 

In Firefox, Safari, Chrome, Android, IE8 (with flash fallback) works well.

Versión of video.js:  5.8.0

**Comment by mmcc** [comment]
Would you mind filling out the issue report template so we can better help debug? 

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

## Results
### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by calanor** [comment]
A example:
http://jsbin.com/caxokomelo/edit?html,console,output

**Comment by lily2016** [comment]
Agree. I see the same problem on my box as well. And it is not only to IE, I recall I saw similar thing in FF as well. 
Another way to reproduce this issue is to simply using the VideoJS's home page: open VidoeJS home page. Start playing the ocean video. Try to use arrow key on the keyboard to jump forward or back (sometimes to make that work, you may need a few tries, or may need to seek the video a few times). Once you are able to do it, you will see the spinning waiting wheel never disappear.

**Comment by gkatsev** [comment]
I think it might be that IE11 doesn't send the correct event to clear out the waiting state of the player. Looking.

**Comment by gkatsev** [comment]
Yep, looks like it doesn't IE11 doesn't trigger any events that we use clear out the waiting state. It's weird that clicking on the progress bar works fine but seeking using the arrow keys doesn't/currentTime doesn't since they essentially all go through the same pipe.

**Comment by gkatsev** [comment]
A potential solution is to listen to `timeupdate` after we attach the waiting state.

**Comment by gkatsev** [comment]
I have a proposed solution in #3138.
