### ISSUE TITLE
this video could not be loaded issue

### ISSUE THREAD

**Issue by mylovesit** [videojs/video.js#3125]
Hi,

i have a problem. this page using xml, html5, video.js

HTML
```
<script type="text/javascript">	
		$(document).ready(function () {
			content1 = $.trim(content1);
			content2 = $.trim(content2);
			$("#movURL1").attr("src",(content1));
			$("#movURL2").attr("src",(content2));
			$("#video_viewer").load();
		});
		</script>
```

```
<div id="video" style="position:absolute; left:50%; margin-left:-358px; top:50%; margin-top:-215px;">
			<video id="video_viewer" class="video-js vjs-default-skin" preload="auto" autoplay controls width="718" height="399" data-setup='{}' >
				<source id="movURL1" src="" type='video/mp4'>
				<source id="movURL2" src="" type='rtmp/mp4'>
			</video>
		</div>
```

xml
```
<content name="content1" contentTitle="movie">
						<![CDATA[http://movie.mp4]]>
					</content>
					<content name="content2" contentTitle="rtmpmovie">
						<![CDATA[rtmp://movie.mp4]]>
					</content>
```

case by case, some pepole look at this message "this video could not be loaded either because the server or network"

why display this message?

i could not find problem T^T

**Comment by mmcc** [comment]
I think this is a question better suited for [StackOverflow](http://stackoverflow.com), so I'd suggest asking this over there. A common reason for this is a server sending incorrect mime types, but there's a lot of other moving pieces to what you're doing, so it's hard to say what the exact problem could be.
