### ISSUE TITLE
[Question] Best way to pass options to sourcehandler?

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#3129]
This is not really an issue, but more of a question.

Say I want to pass options to a sourcehandler. In particular, I want to be able to pass an option to `videojs-contrib-dash` whether it should use the portal to limit bitrate (i.e. call `setLimitBitrateByPortal` on the Dash.js MediaPlayer).

What is the best way to do this?
I know I could pass it as an option during player initialization in the `html5` tech, but then the way to get to it would be to call `tech.options()` in the source handler and apparently that function is going away.

Normally you'd set the options you need during the construction of a component, but that is not really possible with a source handler I think. So what is a good way?

**Comment by gkatsev** [comment]
Sounds similar to #2616.
But I think we don't have an answer for you right now :).
The way that contrib-hls chose to go is to attach a `hls` object to the tech that you can then get and modify the options on. If you have any suggestions for solving this in a good way that could be applied to all source handlers, we'd be happy to hear and work on it together with you.

**Comment by nickygerritsen** [comment]
Hmmm interesting, didn't see #2616 yet.
I do have some idea, but will type it there as I do think it makes more sense there

**Comment by gkatsev** [comment]
Sounds good. Should we close this then and make sure that #2616 is updated to address updating options after initialization as well?

**Comment by nickygerritsen** [comment]
I think what I want would even work without updating options after initialization. Or at least, if you define "initialization" as "when calling `handleSource`".

Anyway, I think this can be closed.

**Comment by gkatsev** [comment]
Yeah, I mean that we need a good way of giving options to source handlers on initialization but also afterwards.
Closing, we can continue discussion in #2616.
