### ISSUE TITLE
Player didn't change screen after a interval time when playing multiply video

### ISSUE THREAD

**Issue by minh1903** [videojs/video.js#3132]
## Description
Hi, I am having a trouble with playing multiply video. **Player will not change frame (It doesn't pause ) after a interval time when playing multiply video**. However, I see XHR still continue load in develope tools of Chrome.

## Steps to reproduce

1.Create a web page with 10 video player, open on Chrome and playing in the same time.
2. The players play in a few seconds and stop ( It doesn't pause ). Videos are type of HLS from CameraIP system.
3. Open develop tool and see XHR still continue load (time by time )
4. I try to create an other webpage with only one player. It has played in a longer time but still stop after about one minute. Network still is OK. 
5. Test video is ok in http://osmfhls.kutu.ru/ with flash player. It runs forever.

### Expected
All players need run infinity real time

#### videojs
5.0.2
#### videojs-hls
1.3.7
#### browsers
Chrome
#### OSes
Window 10
### plugins
HLS plugin

**Comment by mmcc** [comment]
Hi there, please use the [issue template](https://github.com/videojs/video.js/blob/master/ISSUE_TEMPLATE.md) when creating a new issue. Thanks!

**Comment by minh1903** [comment]
Hi @mmcc , I have re-updated my issue. Thanks!

**Comment by gkatsev** [comment]
It may be just a resource limit that we can't do anything about. See related issue: https://github.com/videojs/videojs-contrib-hls/issues/496

**Comment by minh1903** [comment]
@gkatsev But see the above testing (4), I still get issue with only one player. It play in a few seconds or minutes, after that it show static screen ( not pause ). I guess that is related to logic update metadata for player?

**Comment by gkatsev** [comment]
Is the `http://osmfhls.kutu.ru/static/vod/sl_vod.m3u8` your m3u8?

**Comment by minh1903** [comment]
No, this is my url: http://05h1.vp9.tv:8484/chn/VP9HN1T/v.m3u8  (I will hidden soon since secure reason )

**Comment by gkatsev** [comment]
I moved this issue over to contrib-hls as that's this issue should live: https://github.com/videojs/videojs-contrib-hls/issues/565
Thanks.
