### ISSUE TITLE
Update NPM to v5+

### ISSUE THREAD

**Issue by BorelTung** [videojs/video.js#3133]
## Description
Videojs on npm is still under v5.0.0/\.
Would you please update it to the latest version.

## Steps to reproduce
`$>npm install videojs`

### Expected
`$>videojs@5.8.0`

### Actual
`$>videojs@4.12.15`

## Additional Information
`$>npm info videojs version`
`$>4.12.15`

**Comment by gkatsev** [comment]
Hi,
The official package name is called `video.js`. Thanks.
Please check it out instead: https://www.npmjs.com/package/video.js

**Comment by BorelTung** [comment]
Oh, my fault. But it would be nice if we mention the usages on the README page.
Thank you.

**Comment by gkatsev** [comment]
You're right, we should. Also, I plan on deprecating on publishing or something the `videojs` package so that this stops happening :)

**Comment by gkatsev** [comment]
Will be fixed by https://github.com/videojs/video.js/pull/3134

**Comment by BorelTung** [comment]
excellent

**Comment by gkatsev** [comment]
I also deprecrated `videojs` on npm and updated the README of that package on npm.
