### ISSUE TITLE
Does Videojs have Problems with IE11??

### ISSUE THREAD

**Issue by xcuben** [videojs/video.js#3135]
Description

Hi Guys,
I am doing implementing a Rollover_Ad with Videojs iin an iFrame that would opened when the user is scrolling to a certain ActiveViewPort.

Error output

iframe is opened in chrome and Firefox but not in IE11.
Is there any explanations for that?
Thanks

versions

videojs

Videojs 5.0.0

browsers

- [x] Chrome/48.0.2564.95 
- [x] IE11

OSes

Windows  64bit

plugins

Videojs-vast-vpaid

**Comment by gkatsev** [comment]
Can you elaborate on what you mean by it not opening in IE11? Are there any errors in the console? If so, can you post it?
Also, can you provide a reduced testcase for this?
