### ISSUE TITLE
video.min.js and video.js both broken in IE8 when using data-setup="{}"

### ISSUE THREAD

**Issue by sethborg** [videojs/video.js#3142]
Version 5.7.1 and 5.8.0 have a bug. Version 5.6 works fine. My previous video.min.js issue was apparently addressed in 5.7.1 but now IE8 support is broken again.

Here's the error, it errors only when you use data-setup="{}" rather than videojs('video', {}, function(){ }); it errors on: var player = videojs(mediaEl);

video.js
line: 12786
char: 13

...

// Check if data-setup attr exists.
// We only auto-setup if they've added the data-setup attr.
if (options !== null) {
  // Create new video.js instance.
  var player = videojs(mediaEl);
}

...

**Comment by gkatsev** [comment]
Does it happen with just an empty data-setup?

**Comment by sethborg** [comment]
I have never tried but I'd guess it would be the same result

**Comment by sethborg** [comment]
OK I confirmed, it still errors even with: data-setup='{"controlBar": { "muteToggle": false }}'

**Comment by sethborg** [comment]
I don't see this as having been patched in the latest patches. Videojs is still broken and will not work on all IE8s when using data-setup="{}" instead of javascript to initiate the player. Could someone please address this?

**Comment by gkatsev** [comment]
Just tested it locally and it's working just fine. Can you provide a reduced test case where it breaks for you?

**Comment by sethborg** [comment]
OK I just tested 5.8.6 and it does work so it must have been fixed since 5.8.0 thanks

**Comment by gkatsev** [comment]
Awesome, thanks for verifying. Closing for now then.

**Comment by sethborg** [comment]
I apologize, the issue is still occurring. I've narrowed it down though. Start by first clearing your cache whenever you visit the page to test. When you include <meta charset="utf-8" /> on the page and visit it in IE8 you get the error message. If you refresh the page, usually once but sometimes it takes 2 refreshes, you'll get the play button but missing the play triangle (utf8 issue) but if you mouse over the play button it appears correctly. The video will then play fine too.

It's even more curious that refreshing the page fixes it than the fact that including the utf8 meta tag breaks it.

Any ideas on what utf8 has to do with the error message? If I try to use videojs('video', {}, function(){}); to initialize, it works fine. Maybe there's some delay on loading the page that causes an issue but since initializing with javascript at the end of the page waits for everything to load there isn't an issue?

Here's my minimal test case: http://ivcmiami.com/test/

**Comment by gkatsev** [comment]
It looks like you're experiencing the same issue as https://github.com/videojs/video.js/issues/2386.
