### ISSUE TITLE
"appendChild" not there

### ISSUE THREAD

**Issue by VictorLULI** [videojs/video.js#3143]
Hi 

I'm quite newbie and my first question at Github...-_-!...it takes me couple of days for troubleshooting.... I don't know what's really wrong there...hope someone would help me~~

Problem: 
this.controlBar.el().appendChild(HD.el()); 
I got e() undefined error

**And I found**:
1. controlBar below this.opthons_ and no el() method 
2. no appendchild method anymore (just addchild)??

**Questions:
How can i add a button by plugin way?**

-------------------------------  Related Information -----------------------------------
Version:
script(src="//vjs.zencdn.net/5.4.6/video.min.js")

Code:
```javascript
var Component = videojs.getComponent('Button');
    videojs.HD = videojs.extend(Component, {
      constructor: function(player, options) {
      Component.call(this, player, options);
      this.on('click', this.onClick);
       }
    });

videojs.HD.prototype.onClick = function(event) {
    console.log("I've been clicked");
  }

var createHDButton = function() {
       var props = {
           className: 'vjs-HD-button vjs-control',
           innerHTML: '<div class="vjs-control-content">' + ('HD') + '</div>', 
           role: 'button',
           'aria-live': 'polite', 
           tabIndex: 0
         };
       return Component.prototype.createEl('div', props, null);
     };

var HD;
     videojs.plugin('HD', function() {
       var options = { 'el' : createHDButton() };
       HD = new videojs.HD(this, options);
       this.controlBar.el().appendChild(HD.el());
     });


var player, overlay, templateEl, $overlay;

var player = videojs('myplayer', {
                controlBar: {
                    children: {
                        playToggle: true,
                        progressControl: true,
                        currentTimeDisplay: true,
                        timeDivider: true,
                        durationDisplay: true,
                        volumeMenuButton: {
                            vertical: true,
                            inline: false,
                            volumeBar: {
                                vertical: true
                            },
                            volumeLevel: false
                        },
                        fullscreenToggle: true
                    }
                },
                aspectRatio: '16:10',
                plugins : { HD : {} }
            });
```

**Comment by VictorLULI** [comment]
I found How to do it from here: http://jsfiddle.net/Hussnain1/unrjrqee/
use Jquery~~~ enjoy

**Comment by mmcc** [comment]
Just a reminder, that JSFiddle is for v4, so ymmv with 5.

We do have [`addChild`](https://github.com/videojs/video.js/blob/master/src/js/component.js#L315-L343), but the `appendChild` you're looking for is just standard [JavaScript](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild). `el()` simply returns the element for that component, so from there you can just use standard JS.
