### ISSUE TITLE
expose access to videojs.Flash.formats

### ISSUE THREAD

**Issue by BorelTung** [videojs/video.js#3153]
## Description
In my project, I need to add some formats to Flash.formats.

Before v5, I can do it like this:
```
videojs.Flash.formats['application/x-mpegurl'] = 'M3U8';
videojs.Flash.formats['application/vnd.apple.mpegurl'] = 'M3U8';
```

But, since the access to `videojs.Flash.formats` is hidden from v5, and I can only change it in the source code:
```
Flash.formats = {
  'video/flv': 'FLV',
  'video/x-flv': 'FLV',
  'video/mp4': 'MP4',
  'video/m4v': 'MP4',
  'application/x-mpegurl': 'M3U8',
  'application/vnd.apple.mpegurl': 'M3U8'
};
```

Can you expose the access to videojs.Flash.formats?

## Additional Information
`video.js@5.7.1`

**Comment by gkatsev** [comment]
You should be able to get access to the Flash tech via `videojs.getTech('Flash')`. Then modify its formats object.

**Comment by BorelTung** [comment]
Thank you!

**Comment by BorelTung** [comment]
@gkatsev Could you show me where the docs of this method is? I can not find it in the [official docs](http://docs.videojs.com/docs/api/video.html).

**Comment by gkatsev** [comment]
Looks like we need to update the docs site. See here: https://github.com/videojs/video.js/blob/v5.7.1/src/js/video.js#L214-L226

**Comment by BorelTung** [comment]
Glad to hear that.
