### ISSUE TITLE
Capturing and finding metadata with live stream

### ISSUE THREAD

**Issue by vpezeshkian** [videojs/video.js#3161]
I have live stream coming to Videojs in rtmp format and I'm able to see it. along with it there are events fired with live stream. How can I capture those events?

When I use `loadedmetadata` listener, I can see that videojs reacts to the fired event at the right moment, but how can I access to that event metedata when the listener is trigged? 
I have asked this question in here:
http://stackoverflow.com/questions/35855637/how-can-i-listen-to-video-metadata-in-videojs

### versions
I tried this on version 5.7.1 and 5.8.1
#### browsers
I'm working in Chrome but essentially need the same behavior on all browsers

**Comment by gkatsev** [comment]
the `loadedmetadata` event in html5 means that the metadata has loaded, unlike in the swf/flash, it doesn't contain the metadata itself.
Also, at the moment, unless explicitly exposed, additional metadata isn't available about the video from the swf in videojs.
