### ISSUE TITLE
mp4 works in IE /FireFox but not in Chrome 49

### ISSUE THREAD

**Issue by stewbie** [videojs/video.js#3167]
I have a mp4 that will play correctly in a video tag in IE and Firefox but in chrome it just endlessly spins.

If I change the type to video/m4v the flash fallback loads and the video plays as expected.

There are no msgs in the dev console either.

Has anyone else experienced this?

**Comment by stewbie** [comment]
Unfortunately I do not because there is customer data in there I can't release. But I've tried using the mp4 as a local resource rather than dishing it up from a controller and this scenario works.

**Comment by gkatsev** [comment]
the same mp4 is working correctly when served through a different server?

**Comment by stewbie** [comment]
No it doesn't not work when served from a different server either. Using: 
return File(doc, document.MIMETypeOfEncapsulatedDocument);
on a MVC ActionResult method.

**Comment by mmcc** [comment]
This sounds like a pretty cut and dry source-related issue, so without the actual source we can't really help debug on this one.

**Comment by stewbie** [comment]
Here's the html we load the video in:

```
<!DOCTYPE html>
<html>
<head>
	@Styles.Render("../Scripts/Plugins/video-js/video-js.less")
	<style type="text/css">
		.video-js {
			padding-top: 52.25%;
		}
		.vjs-fullscreen {
			padding-top: 0;
		}
		.vjs-fullscreen-control {
			display: none; /* Hide fullscreen button since it doesn't work in an iframe */
		}
		.vjs-volume-control.vjs-control {
			padding-right: 10px;
		}
	</style>
</head>
<body>
	<video id="video" class="video-js vjs-default-skin vjs-big-play-centered"
		   controls preload="auto" width="auto" height="auto"
		   data-setup='{}'>
		<source src="@Request.Url.AbsoluteUri&forceLoad=true" type="video/m4v" />
		<p class="vjs-no-js">To view this video please enable JavaScript and consider upgrading to a more modern browser.</p>
	</video>
	@Scripts.Render("../Scripts/Plugins/video-js/video.js")
</body>
</html>
```

And we serve the file using this in our controller method:

            byte[] dicomFile = GetDatasetProvider().GetDataset(datasetID, 0, int.MaxValue);
            MemoryStream stream = new MemoryStream(dicomFile);
			using (DicomFile df = new DicomFile(stream, RequiredTags.Dataset, true)) {
				var document = new EncapsulatedDocumentModuleIOD(df.Dataset);
				if (!forceLoad) {
					if (document.MIMETypeOfEncapsulatedDocument.StartsWith("video")) {
						return View("Media");
					} else if (document.MIMETypeOfEncapsulatedDocument.StartsWith("image")) {
						return View("Image");
					}
				}
				byte[] doc = new byte[document.EncapsulatedDocument.Length];
				document.EncapsulatedDocument.Read(doc, 0, doc.Length);

                StudyContext context = new StudyContext {
                    StudyUID = studyUID,
                    PatientID = patientID,
                    PatientGroup = patientGroup
                };
                Logging.Default.Audit("Study Opened", null, System.Web.HttpContext.Current.User.Identity.Name, context);

                return File(doc, document.MIMETypeOfEncapsulatedDocument);
