### ISSUE TITLE
Get frame metadata through Flash player

### ISSUE THREAD

**Issue by antoniogiordano** [videojs/video.js#3171]
## Description
Hi everybody, i built a real-time application with a RTMP stream from a user to another.
The RTMP stream flows from an Android app to an NGINX server, which a web browser with VideoJs gets the stream from.
Now, my problem is that i don't know the delay between the source and the destination (it could vary from ~2 to ~10 seconds) .
One solution is to send within the frames metadata info (like timestamp) and read it from VideoJs, and thanks to socket IO that is very fast and with a delay less of ~1 second i can have a very accurate video streaming delay information.
The question is, there is a wey to get frame by frame metadata information?
If yes, how?
If no, it could be possible with Flash / as technology?
If yes, i have to fork video.js and videojs-flash to make it work, right?

Thanks

**Comment by mmcc** [comment]
Hi there! All RTMP decoding is done in the videojs-swf project, so yes, this would need to be done in Flash. Also yes, this would almost certainly require a pretty non-trivial amount of work, so trying to get things working in a fork is probably your best bet.

Sounds like a cool project, though, keep us in the loop on how things go!
