### ISSUE TITLE
videojs time

### ISSUE THREAD

**Issue by momkin** [videojs/video.js#3174]
Hello 
i wanna change the player time 

currently the time is countring down 

i want to make it count up ( if the movie duration 2 hours it must start from 1 sec tell 2 hours  ...and so on

**Comment by mmcc** [comment]
Both are already in the DOM as components, so you just need to [unhide the one](https://github.com/videojs/video.js/blob/master/src/css/components/_time.scss#L16-L19) you want (and hide the one you don't).
