### ISSUE TITLE
Turn off warnings on browser console

### ISSUE THREAD

**Issue by tjbee** [videojs/video.js#3176]
Is there a way to turn off warnings in the browser console like these below?

VIDEOJS: WARN: Player "product51154948" is already initialised. Options will not be applied.
video.js:16869 VIDEOJS: WARN: Player "product51154934" is already initialised. Options will not be applied.

**Comment by mmcc** [comment]
I don't believe there is, but we should probably add a setting for log level.

That being said, I would also consider updating your code to avoid re-initializing the player repeatedly.

**Comment by tjbee** [comment]
The way I have it set up is -

I need to make sure when one video is playing and another video gets clicked on, I want to make sure all other videos are paused and for me to do this, I need to find all videos on the page and I think this is trying to re-initializing them.

Is there a way to target all videos without re-initializing?

**Comment by mmcc** [comment]
Yep, the `videojs.players` object should contain a reference to all initialized players on a page.

**Comment by gkatsev** [comment]
While we should have log levels, this warning should probably stay enabled by default.

**Comment by tjbee** [comment]
Following up on this,

I see a 404 for video.min.js.map. Is there a way to turn it off

**Comment by gkatsev** [comment]
@tjbee the sourcemap errors are going to go away in 5.12.

**Comment by gkatsev** [comment]
You can turn off warnings now using the new log level API: http://docs.videojs.com/tutorial-debugging.html
