### ISSUE TITLE
No good way to run coverage locally

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#3177]
## Description
If a user wanted to run the tests locally and see what the test coverage is, there currently isnt a good way of doing that. The configs currently only run those in the CI and don't expose a way to do so on a local machine.

**Comment by yanglinz** [comment]
Hey @gkatsev I took a stab at this, which was just enabling the coverage reporting for all tests. I'm probably missing something obvious, so happy to take any feedback :)

**Comment by gkatsev** [comment]
@yanglinz thanks! I think what I was looking for is an option to enable it, rather than having it always run, since it makes the tests even slower.
Another thing is to make sure that it doesn't try and report the coverage results to coveralls when run locally.

**Comment by yanglinz** [comment]
@gkatsev that makes sense. Did you have something in mind on what that toggle is? `npm test --coverage`, `npm run test:coverage`, `COVERAGE=true npm test`, etc. 

So nothing is sent to coveralls. From what I can tell, karma coverage reporter is configured to:
1. output coverage result to `coverage/coverage.txt`
2. output the coverage summary to stdout.

**Comment by gkatsev** [comment]
`--coverage` sounds good to me. I think that is relatively standard as well.

**Comment by gkatsev** [comment]
Also, looks like coveralls is already set to only run on travis as seen [here](https://github.com/videojs/video.js/blob/master/build/grunt.js#L498-L499).

**Comment by gkatsev** [comment]
Fixed by #3539.
Thanks @yanglinz!
