### ISSUE TITLE
Can't play mp4 with Windows XP, Firefox 45.0

### ISSUE THREAD

**Issue by MCGallaspy** [videojs/video.js#3178]
## Description
mp4 playback fails with Firefox 45 on Windows XP. I'm using video.js 5.8. See this reduced test case: http://jsbin.com/zenonarito/edit?html,output

I can't even get Flash fallback to work. I've tried fiddling around with the `techOrder` option to no avail. Basically I seem to be encountering the same issue here: https://github.com/videojs/video.js/issues/343

## Steps to reproduce
1. On Windows XP, install Firefox + Flash plugin.
2. Check out the reduced test case linked above.
3. Observe the error `Specified "type" attribute of "video/mp4" is not supported. Load of media resource http://vjs.zencdn.net/v/oceans.mp4 failed.`

### Expected
The video should be playable.

### Actual
It is not.

### Error output
Here's the js console output from the linked test case:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create video.js:13600:415
Specified "type" attribute of "video/mp4" is not supported. Load of media resource http://vjs.zencdn.net/v/oceans.mp4 failed. runner
All candidate resources failed to load. Media load paused. runner
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video. Object { code: 4, message: "No compatible source was found for …" } runner-3.35.11.min.js:1:9080

All candidate resources failed to load. Media load paused.
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.8
#### browsers
Firefox 45
#### OSes
Windows XP SP3
### plugins
None.

**Comment by MCGallaspy** [comment]
Hi, thanks for taking the time to build & release this great open source project! I understand how much work it is to do that, so I don't want to sound pushy. That said, this issue is pretty critical to me. Is it a "WONTFIX"? Or have the project maintainers just not had a chance to look at it?

**Comment by mmcc** [comment]
Totally understand the need, thanks for the empathy :)

Can you reproduce this on any other OS than Windows XP (I haven't been able to, but only OS X / IE 11)? If so, I think this is definitely something we should dig into, but if not, it's been [off of life support for 2 years](https://www.microsoft.com/en-us/WindowsForBusiness/end-of-xp-support) and unfortunately I don't think we can or should continue to support it on our end.

**Comment by mmcc** [comment]
A little stalking and I see you're probably asking about this for Learning Equality, which probably wants to support XP due to its continued prevalence in some parts of the world.

What's going wrong with the Flash fallback? Setting it [works fine](http://output.jsbin.com/valorejere) for me, so if that's a solution you might just need to do a manual check on your end and preemptively fall back to Flash for that browser.

That being said, requiring Flash at this point in time almost feels like it's a step back, especially with the recent vulnerabilities which seem to just keep coming. Have you considered adding WebM as an option?

**Comment by MCGallaspy** [comment]
> probably wants to support XP due to its continued prevalence in some parts of the world.

Right, I'd love to leave XP in the dust, but it's very tenacious. :)

> Can you reproduce this on any other OS than Windows XP

No, flash fallback behavior works fine on all other OSes I've tried. A little digging turned up these issues, which also suggests something is up with XP specifically:
* https://support.mozilla.org/en-US/questions/1053509
* https://support.mozilla.org/en-US/questions/1052837

I have a pretty limited understanding of these issues, and how to debug them, but I'll take a closer look at it tomorrow.

> Have you considered adding WebM as an option?

We're definitely taking a very close look at it!

**Comment by mister-ben** [comment]
> I can't even get Flash fallback to work.

As your example is on jsbin, bear in mind that the Flash tech can not work in their output pane because it's in a sandboxed iframe. If you open the output in its own window, this plays in Flash on XP: http://output.jsbin.com/yaqojumuri/1

**Comment by MCGallaspy** [comment]
>If you open the output in its own window, this plays in Flash on XP:

Really? Did you try it? I can't get it to work.

**Comment by MCGallaspy** [comment]
Which is to say that the flash player seems to load, but the video does not. I get the following output in my js console:

```
Specified "type" attribute of "video/mp4" is not supported. Load of media resource http://vjs.zencdn.net/v/oceans.mp4 failed.
All candidate resources failed to load. Media load paused.
```

**Comment by MCGallaspy** [comment]
> I can't get it to work.
Wait, I take it back! Seems like the popped-out page does indeed work. Initially I just copied the example html snippet into a new document and opened it in a browser, to get the original error. I don't understand why it should be different?

But this seems to indicate an error on my end, so closing.
