### ISSUE TITLE
Cues is undefined in FireFox

### ISSUE THREAD

**Issue by vpezeshkian** [videojs/video.js#3182]
## Description
When using cuechange listener, cues is undefined in FF. Also for some reason it's fired twice.
ERROR:
 TypeError: cueChangeEvent.target.cues is undefined

CODE SNIPPET:
`track.addEventListener('cuechange', (cueChangeEvent) => {
        const cuedata = cueChangeEvent.target.cues[0].value.data;`

### versions
FireFox 45.0
#### videojs
5.8.1
#### browsers
FF
#### OSes
OS X El Capitanv 10.11.3

**Comment by gkatsev** [comment]
Can you provide an example of the vtt file you're using? Preferably, if you can do it in a reduced test case on a site like jsfiddle.net. Thanks.
