### ISSUE TITLE
`vtt.js` delivered from CDN

### ISSUE THREAD

**Issue by MCGallaspy** [videojs/video.js#3183]
## Description
Forgive me, this took me some time to figure out and I'd actually be quite happy if you pointed out that I've made some noob mistake.

I noticed that `vtt.js` was being delivered from a CDN, but I wanted to self-host everything. I'm using video.js 5.8.0. When I run `npm install` and look at the video.js source in my node_modules directory, this line:
https://github.com/videojs/video.js/blob/v5.8.0/src/js/tech/tech.js#L329

Actually looks like this:
```js
script.src = this.options_['vtt.js'] || 'https://cdn.rawgit.com/gkatsev/vtt.js/vjs-v0.12.1/dist/vtt.min.js';
```

Ultimately I noticed the `videojs-vtt.js` directory *also* in my node_modules (presumably because it's a dependency for `video.js`) and I was able to get everything working by adding the `WebVTT` object to the global scope like so:
```js
var vtt = require("videojs-vtt.js");
global.WebVTT = vtt.WebVTT;
```

This is not mentioned at all in the documentation about self-hosting.

**Comment by gkatsev** [comment]
We definitely need better documentation around this, however, if you're using the main videojs file, vttjs *should* be included. Or are you requiring videojs directly rather than using the file in `dist`?

**Comment by gkatsev** [comment]
Would you be willing to write a short blurb for it in the guides? Perhaps as another section in https://github.com/videojs/video.js/blob/master/docs/guides/setup.md?

**Comment by MCGallaspy** [comment]
> Or are you requiring videojs directly rather than using the file in dist?

To be honest, I'm not really sure. The project is using browserify and I have a statement like this:
```js
var videojs = require("video.js");
```

> Would you be willing to write a short blurb for it in the guides?

Sure thing.

**Comment by gkatsev** [comment]
Closing since #3229 is merged, thanks @MCGallaspy!
