### ISSUE TITLE
Custom 'no compatible source found' message

### ISSUE THREAD

**Issue by alex-phillips** [videojs/video.js#3186]
Is there any way to have a custom message being displayed when this is the case? Or maybe a callback function that can return markup or DOM elements? It'd be nice to be able to instead display a message such as 'Flash is not installed' or something.

**Comment by mmcc** [comment]
If you want more control over all your error messages, I'd check out the [videojs-errors](https://github.com/brightcove/videojs-errors) plugin. If you only want to update that specific message, you can include a custom `notSupportedMessage` in your options object.

**Comment by alex-phillips** [comment]
Perfect, exactly what I was looking for. Thanks!
