### ISSUE TITLE
Broken autoplay

### ISSUE THREAD

**Issue by doublex** [videojs/video.js#3188]
Hello,

The pull request (https://github.com/videojs/video.js/pull/2971) broke the autoplay (at least on my computer - FF on Ubuntu). I don't know why - "this.src()" returns an empty string (maybe a race condition?).

The down below patch fixes this issue (and https://github.com/videojs/video.js/issues/2825).

Thanks a lot
Markus

````
*** src/js/player.js-o        2016-03-17 17:02:39.290288039 +0100
--- src/js/player.js    2016-03-17 17:04:47.529929151 +0100
*************** class Player extends Component {
*** 731,738 ****
      // In Safari (5.1.1), when we move the video element into the container div, autoplay doesn't work.
      // In Chrome (15), if you have autoplay + a poster + no controls, the video gets hidden (but audio plays)
      // This fixes both issues. Need to wait for API, so it updates displays correctly
!     if (this.src() && this.tag && this.options_.autoplay && this.paused()) {
!       delete this.tag.poster; // Chrome Fix. Fixed in Chrome v16.
        this.play();
      }
    }
--- 731,740 ----
      // In Safari (5.1.1), when we move the video element into the container div, autoplay doesn't work.
      // In Chrome (15), if you have autoplay + a poster + no controls, the video gets hidden (but audio plays)
      // This fixes both issues. Need to wait for API, so it updates displays correctly
!     if (this.tag && this.options_.autoplay && this.paused()) {
!         try {   // Safari 5 throws: "TypeError: Unable to delete property."
!         delete this.tag.poster; // Chrome Fix. Fixed in Chrome v16.
!       } catch (e) {}
        this.play();
      }
    }
````

**Comment by dennissch** [comment]
I have noticed the same issue with:
Mozilla/5.0 (PlayStation 4 3.15) AppleWebKit/537.73 (KHTML, like Gecko) 

```
'message' => 'Unable to delete property.',
'name' => 'TypeError',
'logData'` => 'Exception info',
```
```
if (this.src() && this.tag && this.options_.autoplay && this.paused()) {
->  delete this.tag.poster; // Chrome Fix. Fixed in Chrome v16.
  this.play();
}
```

**Comment by gkatsev** [comment]
Given that the `delete` statement seems to be a fix for older Chrome and fixed in chrome 16, do we even need to have that line altogether?
I guess wrapping it in a try/catch is "safer" but if it's just causing problems now, we should just remove it.
Thoughts, @videojs/core-committers, particularly @heff (you probably added it in)?

**Comment by heff** [comment]
Yeah, the delete could definitely be removed. You'd want to check Safari first before removing the whole block. And probably not just the latest Safari but whatever versions are in use, because removing it could immediately break playback for people. If it works now though it'd be great to get rid of all that.

**Comment by gkatsev** [comment]
I'm just talking about removing just https://github.com/videojs/video.js/blob/3070e738f1c63044eae24d78847466d5ece4010f/src/js/player.js#L754 and not the whole block.

**Comment by heff** [comment]
But the addition of `this.src()` in #2971 is apparently what caused the issue, so I don't know if that's a full fix for this issue.

**Comment by doublex** [comment]
Sorry - there are two issues:
a) ```this.src()``` broke the autoplay (maybe only on my setup - I will investigate futher)
b) ```delete this.tag.poster``` breaks old Safari browser (and old ipad tablets)

Maybe the best fix for now: Could you add a ```try/catch``` block arround the ```delete``` and ignore the ```this.src()```?

**Comment by rbran100** [comment]
I seem to be having the same issue, the only way I get the video to auto-play in chrome 50 is to add src manually into my video tag.

**Comment by gkatsev** [comment]
PR for this was merged. See #3337.

**Comment by doublex** [comment]
@gkatsev 
Thanks for supporting legacy apple devices.
