### ISSUE TITLE
Seo problem + feature request

### ISSUE THREAD

**Issue by Abdullaor** [videojs/video.js#3193]
Hi guys, I have a SEO problem with your player. 
If I put video js in my page, google use the following text for meta description:

To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video
Even if I add a description to the video, google still use this line as meta description. How can I tell to google to not index this line? If it's not possible, then is possible to replace this line with an image that say the user to enable javascript? In this way google will index the video description.

Also, please take a look at this video js player: [redacted]
please, start the video and then right click on the video. 
As you can see, option like "save video" has been disabled, and they added the "copy url" function. How can I do the same thing with my player? Thank you

**Comment by mmcc** [comment]
It's *incredibly* inappropriate to post links to nsfw content on the issue tracker.

**Comment by Abdullaor** [comment]
It's not my site, it was just an example. Please tell me how to do that

**Comment by mmcc** [comment]
You can't ask people to visit that site here. Regardless, this is an issue tracker, not a support forum, so I think your questions are a better fit for StackOverflow.

**Comment by Abdullaor** [comment]
Well at least the first problem is an issue

**Comment by mmcc** [comment]
It's simply a paragraph tag, so I'd consider the SEO issue an implementation problem.
