### ISSUE TITLE
DVR preload

### ISSUE THREAD

**Issue by nextlivetv** [videojs/video.js#3197]
May anyone help me
How determine time or by request for preload in video js.
My bandwidth does not permit to download my dvr length of 4 hours for all clients
How to do preload max for 1 min or 10 reguist .
I use hls mpeg ts.
Thank you very much

my embed code
```
<video id=video  height="320px" preload="none" style="width:100% !important; " class="video-js vjs-default-skin" controls>
```

**Comment by mmcc** [comment]
Hi there! This question is probably better suited for either [StackOverflow](https://stackoverflow.com) or, if you think you've found an issue with contrib-hls, [issue tracker](https://github.com/videojs/videojs-contrib-hls).
