### ISSUE TITLE
How to show progress bar in HLS live event

### ISSUE THREAD

**Issue by sheny35** [videojs/video.js#3198]
## Description
It seems that VideoJS shows the progress bar only when we're playing VOD. For live or live event playlist, where the "#EXT-X-ENDLIST" tag is not provided, VideoJS doesn't show the progress bar. 
If there any way we can let videojs show it?
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Unfortunately, there isn't a way right now and build out controls that support it is tricky; however, we are aware of the issue and are considering what we want to do about it.
We'd want the controls to support things like videojs-contrib-hls, videojs-contrib-dash, and also native HLS playback on browsers like Safari and MS Edge.

**Comment by gkatsev** [comment]
I'm going to close this for now.

**Comment by Ampelmann23** [comment]
Is there a solution now or is it planned?

**Comment by jienco** [comment]
It would be awesome to have this feature... Could this issue be reopened @gkatsev ? Should this be implemented here or as a plugin? I would like to help with this feature. Thanks very much!

**Comment by tim1mw** [comment]
I've been trying to work out how to do this when I found this issue. Any chance of this being re-opened for consideration?
