### ISSUE TITLE
Video.Js Not Picking Up Browser Language Configuration

### ISSUE THREAD

**Issue by eavestn** [videojs/video.js#3199]
## Description

Video.JS does not pick up browser language settings as [described in the documentation](http://docs.videojs.com/docs/guides/languages.html#determining-player-language). 

You can test this using the [starter template](http://jsbin.com/axedog/edit?html,output) and by mucking the file types or url. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Set the language settings in Chrome (or another browser) to a language other than English (I chose Spanish)
2. Use a bad URL or file type
3. Attempt to play the video

### Expected
The error messages (among other literals) should be localized

### Actual
The error message displayed by the video player are not localized

**Comment by mister-ben** [comment]
Make sure you're [adding the translations](http://docs.videojs.com/docs/guides/languages.html#adding-languages-to-video-js). video.js will detect the language but still default to English if the localised strings for that language have not been made available. 

http://jsbin.com/sazizo/edit?html,console,output

**Comment by eavestn** [comment]
@mister-ben Oh! That makes so much sense!!!!! Thank you!! I feel like a dummy.

**Comment by gkatsev** [comment]
We probably should update the docs to make it more clear.

**Comment by eavestn** [comment]
@mister-ben is it possible to due the language addition if I am hosting the source, myself?
