### ISSUE TITLE
Add ARIA region role and ARIA label to player element

### ISSUE THREAD

**Issue by chrisauclair** [videojs/video.js#3201]
If a document contains multiple players, screen readers can inadvertently combine some of the controls. A specific example occurs when using JAWS in IE 9+. 

The solution is to add a "role" attribute with the value "region" to the player element, and also add an ARIA label identifying the player as an "audio player" or "video player", depending on the type. This has the benefit of adding the player to the screen reader navigation, and also fixing any bugs with the controls.

**Comment by chrisauclair** [comment]
Identifying a region as a video or audio player eliminates the need to label controls as "video control name" ("video progress bar" comes to mind). That's redundant, because the SR user will know they're in a "video" region. It will also eliminate the current issue where some audio controls identify as video controls because "video" is hardcoded into their label.

**Comment by gkatsev** [comment]
Makes sense to me. @OwenEdwards thoughts?
Care to submit a PR?

**Comment by OwenEdwards** [comment]
What I was thinking of in #2770 was essentially this coupled with the specific [Title functionality from the videojs Dock plug-in](https://github.com/brightcove/videojs-dock). So yes, I think it makes sense.

**Comment by chrisauclair** [comment]
@gkatsev , I can submit a PR that fixes this when I get a chance, since I've already fixed it locally.

**Comment by gkatsev** [comment]
Closed by #3227.
