### ISSUE TITLE
VideoJs controls opposite way bug

### ISSUE THREAD

**Issue by akuneum** [videojs/video.js#3204]
VideoJs player is weird when it's on an arabic language website, have a look
![r2mljyq](https://cloud.githubusercontent.com/assets/18068072/14041918/578c93a0-f286-11e5-95a0-32ca3e8d1071.png)
http://akuneum.blogspot.com/2016/03/the-good-dinosaur.html

**Comment by mister-ben** [comment]
This is because the controls are laid out with flexbox and that changes order based on text direction. A quick fix is to add `lang="ltr"` to the player but a proper fix probably needs to be more nuanced to make sure Arabic text display correctly in dialogs.

**Comment by gkatsev** [comment]
Thanks for the workaround, @mister-ben. I guess the question now is whether videojs should be doing that by default?
At least until we get around to figuring out proper rtl langauge support?

**Comment by mister-ben** [comment]
I think setting dir on controlBar and loadingSpinner is enough, and everything else behaves when inheriting directionality. The captions dialog does need to be updated to use `localize()` though.

**Comment by gkatsev** [comment]
Yeah, the captions settings dialog has a whole bunch of accessibility issues that need updating :), I think @OwenEdwards has a writeup elsewhere about it.

**Comment by mister-ben** [comment]
Fixed in 5.8.7
