### ISSUE TITLE
Sass error: Import directives may not be used within control directives or mixins

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#3205]
## Description
The sass file video-js.scss is failing in the sass compiler with the message:
`error video-js.scss (Line 6: Import directives may not be used within control directives or mixins.)`
Sass then stops working and I am unable to output any css.

## Steps to reproduce
1. Follow the Install tutorial from [GitHub](https://goo.gl/E6WcFR).
2. Install Ruby and Sass.
3. In the Command Prompt (Windows) cd to the project directory and enter `sass --watch vjs.scss:_somepath/output.css`

## Results
The following error is generated `error video-js.scss (Line 6: Import directives may not be used within control directives or mixins.)` and the Sass compiler stops functioning.
### Expected
The output.css file should export without failing.

## Additional Information
A search on StackOverflow comes up with [this answer](http://goo.gl/Rl3jrG) stating that the syntax in video-js.scss is not allowed within sass?

#### videojs
5.8.0
#### OSes
Windows 10
### Sass
3.4.21

**Comment by gkatsev** [comment]
It was working on node-sass (and libsass) but looks like it was a bug that recently got fixed: https://github.com/sass/libsass/issues/1724 https://github.com/sass/libsass/releases/tag/3.3.3. Though, node-sass hasn't updated to support that version of libsass yet (there's a beta version).

**Comment by edwinbradford** [comment]
Okay then it seems best to wait for the update. If I comment out the mixin on my local version I found I can build everything.
