### ISSUE TITLE
Video.js cdn access denied error  

### ISSUE THREAD

**Issue by baqarrivi** [videojs/video.js#3208]
Video.js cdn access denied error  at hosted files .

**Comment by jimaek** [comment]
You can always use as an alternative http://www.jsdelivr.com/projects/videojs

**Comment by mister-ben** [comment]
Can you elaborate? These work:

http://vjs.zencdn.net/5.8.0/video.js
http://vjs.zencdn.net/5.8.0/video-js.css

**Comment by gkatsev** [comment]
I did forget to push 5.8.6 to the CDN. But otherwise, things should work.

**Comment by baqarrivi** [comment]
Hello
Thanks for you reply actually i am talking about this link /
http://vjs.zencdn.net/5.8.6/video-js.css and this
http://vjs.zencdn.net/5.8.6/video.js

On Sat, Mar 26, 2016 at 10:25 PM, Gary Katsevman <notifications@github.com>
wrote:

> I did forget to push 5.8.6 to the CDN. But otherwise, things should work.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/3208#issuecomment-201898634>
>



--

**Comment by gkatsev** [comment]
Published. Please include the specific url you're trying to hit next time, would make it a lot easier to verify.
