### ISSUE TITLE
Question Mobile Videojs Default Skin

### ISSUE THREAD

**Issue by Shrhawk** [videojs/video.js#3209]
## Description
I am using videojs version **5.8.0** on mobile(Iphone) the player is working fine but the videojs default skin is not applying, also i am using the option ```{nativeControlsForTouch: false}``` but no effect.

<img width="316" alt="screen shot 2016-03-26 at 2 38 13 pm" src="https://cloud.githubusercontent.com/assets/7054417/14059349/14c1c59c-f360-11e5-91cb-5865d9837553.png">

**Comment by mister-ben** [comment]
iOS will always play video in a separate fullscreen player and not within the browser on iPhone, and this player's controls cannot be customised. It's a design decision that made a bit more sense on early iPhones with small screens. Hopefully Apple will revise that thinking eventually.

**Comment by Shrhawk** [comment]
thanks @mister-ben for reply and one other thing is i am using webkit-playsinline in hybrid app so its does not go to fullscreen by default.Any way looks like its expected behaviour.
