### ISSUE TITLE
Video.js uses default browser font on progress timers

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [videojs/video.js#3210]
As shown in the screenshot with the browser zoomed in, it uses the default font in the browser (which is obviously Times New Roman), which is inconsistent with the other font used in the far left, which is Arial.

![wow](https://cloud.githubusercontent.com/assets/7586568/14063396/66bab4cc-f38c-11e5-8483-1cafff6607d9.png)

Obviously, this makes it much harder to read it since Times New Roman isn't designed to be read in such small print.  I also think you should make the font size slightly bigger overall.

**Comment by gkatsev** [comment]
Fixed by #3213, though, the changes aren't released yet.

**Comment by CoWinkKeyDinkInc** [comment]
Thanks!  It was bugging me for a while
