### ISSUE TITLE
HLS&WindowsMobile

### ISSUE THREAD

**Issue by brylek** [videojs/video.js#3234]
Hi All,

Does videojs support HLS stream on Windows mobile? if yes, do you have any example?
till now, I am not able to do that :(

thx,
Luke

**Comment by gkatsev** [comment]
Unfortunately, windows phone doesn't support HLS natively yet. It may receive support ones it's updated to windows 10 (if and when it happens).
It seems that windows phone supports Media Source Extensions, but unfortunately, [videojs-contrib-hls](/videojs/videojs-contrib-hls) doesn't work on it either.
I tested this on a Windows Phone 8.1 device and it's native IE browser.

If you are running video inside an app, there are apparently plugins you can include that enable HLS video.

Hope that helps!

**Comment by brylek** [comment]
hi,

I found that project. 
https://github.com/dailymotion/hls.js/tree/master

it seems to be integrated to videojs :) I will test it.

R>
Luke
