### ISSUE TITLE
live streaming is not working in android firefox

### ISSUE THREAD

**Issue by nafisakanwal** [videojs/video.js#3239]
## Video js Live Streaming
I have setup my live stream page in video JS , it is working fine in every browser except the android 's Firefox and Samsung native browser .

### Error output
The media could not be loaded,either because the server or network failed or because the format is not supported.

## Additional Information
i am using rtsp source as well 
and loading sign remains in loading along with a crosse sign
#### videojs
this is occurring in 5.8 and 4.1 as well
#### browsers
android firefox version 45.0.1
#### OSes
android version :5.0.2
### plugins
no plugin is used

**Comment by gkatsev** [comment]
This may be just a limitation of those browsers. What format are you using for the livestream? Only RTSP? Or HLS?

**Comment by nafisakanwal** [comment]
gkatsev Thanks for reply 
yes i am giving both RTSP and HLS .its working in the android chrome but not working in firefox .

**Comment by gkatsev** [comment]
Yeah, unfortunately, it seems that firefox for android just doesn't support HLS.
I'm not sure whether firefox on android supports media source extensions, but you could try running [videojs-contrib-hls](/videojs/videojs-contrib-hls) but we haven't tested it there.
Unfortunately, there's really not much we can do in this case, sorry.
