### ISSUE TITLE
Media could not be loaded IE11

### ISSUE THREAD

**Issue by JeffWeb9999** [videojs/video.js#3242]
Hello,
In IE11 when loading the video on my website page I get this error message "the media could not be loaded either because the server or network failed of because the format is not supported"

1. Open website page with video player embedded on page
2. click play
3. I see this error message: "the media could not be loaded either because the server or network failed of because the format is not supported"

Player is working with no error message on MAC Chrome, Safari, Firefox, Windows Chrome, Firefox, IE8, 9, 10

The issue is seen on the homepage of videojs as well http://videojs.com/
Could this be a setting in the browser or a setting with the video code?
This is my video code:

```
<video id="my-video" class="video-js" controls preload="auto" width="500" height="375" poster="video-poster.png" data-setup="{}">
	<source src="video.mp4" type='video/mp4'>
	<p class="vjs-no-js">To view this video please enable JavaScript or consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video>
```

Thank you!

**Comment by gkatsev** [comment]
Unfortunately I only have a virtual machine with IE11, but videojs.com is working fine for me on it and everywhere.
Only thing that I can think off is that maybe IE11 on Win10 is having issues as I've tested on win7, but I feel like we've tested on win10 as well as part of the contrib-hls project and haven't seen issues.

**Comment by mister-ben** [comment]
I can play video at videojs.com (and elsewhere) on IE11 on a real Win 10.  Have you tested playback in a plain HTML5 video tag on that machine?

Some of IE's advanced security settings break the browser in various ways that mess with video playback - you could try resetting the internet zone security settings to the default values.

**Comment by JeffWeb9999** [comment]
Thank you for your response. I can't get video's to work with the plain HTML5 video tag on our server so it is looking like and IE setting controlled by my IT department. I will go to them and ask. Thanks!

**Comment by gkatsev** [comment]
Thanks for getting back to us.
Closing this issue because it's unlikely to require a change to videojs itself. However, we can still continue the discussion here and if it turns out to actually be an issue with videojs, we can re-open the issue.

**Comment by mister-ben** [comment]
If it's a Windows server, also bear in mind there's an additional OS component you need to install for media playback (for IE, other browsers do their own thing). It's called something like desktop experience, iirc.
