### ISSUE TITLE
Workaround a bug in the LG Player 1.0 for Android?

### ISSUE THREAD

**Issue by agwells** [videojs/video.js#3243]
## Description
The cause of this problem is actually an operating system bug, in LG's version of Android. But this bug report is to see if VideoJS might be able to more gracefully handle the error caused by this bug.

I recently added VideoJS to a web application I work on. While testing it on my phone (an LG G2 Mini running Android 5.0.2), I noticed what appears to be a bug in LG's version of Android 5, described here: https://bugs.launchpad.net/mahara/+bug/1567208

In brief, the bug causes an HTML5 video to get requested **without** the same cookies as the page it's on, which means that if it's being served by a web application that requires cookie-based authentication, an error response is served instead of the actual video file. The browser then goes on to try to display that error response as a video, which results in the VideoJS controls showing up over what looks like a very short video consisting of an empty black rectangle.

It would be preferable if VideoJS could detect that this situation has occurred and display an error screen instead of this semi-working black rectangle. However, I tried a few things and wasn't able to get anything to work. And when I used Chrome remote debugging, it appeared that the underlying DOM element wasn't even indicating that an error had occurred, so that may mean it's not possible for VideoJS to detect and handle this problem. But I thought I would toss it out there in case anyone has any ideas, or encounters this same issue.

## Steps to reproduce
1. Install a website that uses cookie-based authentication, and that can restrict access to a video file depending on whether or not the user is authenticated.
2. Embed one of these access-restricted video files into a page using JSVideo
3. Load the website in Android Chrome on an LG device with LG Player 1.0.
4. Authenticate into the website
5. Attempt to view the page with the embedded video file

### Expected
The video displays correctly in VideoJS

### Actual
The video displays as if it were a valid video composed of one frame with a black rectangle in it. That is, you see a black rectangle with the VideoJS "play" button over it. Clicking the play button causes the VideoJS controls to briefly appear, with the play/pause button indicating that it's playing, but the time status indicator doesn't move forward. The controls can be clicked and selected like a valid video, but with no content displayed.

### Error output
In the web server logs, it will be apparent that the video file was requested by a program with this user-agent string: ""Player/LG Player 1.0 for Android 5.0.2 (stagefright alternative)". The request contains no cookies.

### versions
videojs: 5.6.0
#### browsers
Chrome 49.0.2623.105
Opera 36.0.2126.101812
Stock browser ("Internet") 5.2.34G06
#### OSes
Android 5.0.2, LG G2 Mini LG-D620k, with "LG Player 1.0" in place of AOSP Stagefright library

**Comment by gkatsev** [comment]
The only thing I can think to try is setting the [`crossorigin`](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) attribute to use the `use-credentials` property:
```html
<video crossorigin="use-credentials" class="video-js" controls>
  <source type="video/mp4" src="http://example.com/video.mp4">
</video>
```
It should tell the video element to send credentials along with the mp4. Other than that, I don't think there's really anything we can do if the video element doesn't error out.

**Comment by gkatsev** [comment]
Also, we can continue discussion even though the issue is closed. That just means that I think it's unlikely to require a change in videojs but we can always re-open if necessary.

**Comment by agwells** [comment]
In the end, the best workaround I've been able to come up with, is to have my server-side application detect the LG Player 1.0 user-agent, and display an error message instead of trying to display the video.
