### ISSUE TITLE
Override Click event on video

### ISSUE THREAD

**Issue by rahulagarwal86** [videojs/video.js#3250]
I would like to know if there is a method to disable the default video onclick play/pause method so that i could do some other thing when the video is clicked, like redirecting user to new url in new bar

**Comment by gkatsev** [comment]
See https://github.com/videojs/video.js/issues/2302 and https://github.com/videojs/video.js/issues/3372.

**Comment by foobarhe** [comment]
In the [least version](https://github.com/videojs/video.js/blob/c632b24364e8c4c196fbadd7fa5542889cb1e56b/src/js/player.js#L1237), you can overwrite the `mousedown` event. 

```
player.tech_.off('mousedown');
player.tech_.on('mousedown', function(e) {
    e.preventDefault();
    // you customized callback  
});
```
