### ISSUE TITLE
vjs-16-9 class doesn't work on Firefox when container has display: flex

### ISSUE THREAD

**Issue by amercier** [videojs/video.js#3255]
## Description

`vjs-16-9` class doesn't work on Firefox when container has `display: flex`

JSFiddle: https://jsfiddle.net/alexmercier/jbhfn1ao/10/

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Open JSFiddle on Firefox
2. Click Run

### Expected

![screen shot 2016-04-13 at 1 22 23 pm](https://cloud.githubusercontent.com/assets/1246795/14508092/cc642a14-017a-11e6-9bdf-7442e3dfee2f.png)

### Actual

![screen shot 2016-04-13 at 1 22 08 pm](https://cloud.githubusercontent.com/assets/1246795/14508165/0b94a650-017b-11e6-9540-975a42a87fad.png)

### Error output

No JavaScript error.

## Additional Information

- Using `flex-direction: column;` or not does not change the behavior.
- Could this be related to [Firefox #958714](https://bugzilla.mozilla.org/show_bug.cgi?id=958714)?

#### videojs

what version of videojs does this occur with? **5.8.8** (couldn't try with 5.9.0 as it's not available from CDN).

#### browsers
what browser are affected? **Firefox**
#### OSes
what platforms (operating systems and devices) are affected? **OSX**
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
That's weird. That firefox issue does look like it could be the culprit here.

**Comment by gkatsev** [comment]
Looks like a workaround is to add another div in between the container div and the video element.

**Comment by amercier** [comment]
@gkatsev Your trick seems to work indeed: https://jsfiddle.net/alexmercier/61cuejzq/1/ 

Maybe, this is an edge case and having this workaround is enough? In this case I guess this issue can be closed.
