### ISSUE TITLE
Firefox video not playing most of the time

### ISSUE THREAD

**Issue by ZohaibGhafoor** [videojs/video.js#3258]
my video is not playing in firefox browsers most of the time..

here is the link which is not working in firefox http://bestsongs.pk/videos/dear-dad-trailer-2016/

**Comment by gkatsev** [comment]
You seem to be using videojs-contrib-dash, can you re-open the issue over there instead? Also, please include versions of Firefox, videojs, and the OS you're using.

https://github.com/videojs/videojs-contrib-dash/issues

Thanks.
