### ISSUE TITLE
Duration is reported to be `0` on iOS 8 for live stream

### ISSUE THREAD

**Issue by incompl** [videojs/video.js#3262]
## Description

Duration is reported to be `0` on iOS 8 for a live streaming video. The [spec](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-duration) indicates that the duration should be positive Infinity. It would be great if videojs could pave over that iOS8 bug.
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1. Load a live streaming video on a device running iOS8
2. Check the value of `player.duration()`
### Expected

`Infinity`
### Actual

`0`
### Error output

No errors are reported.
## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs

5.9.0
#### browsers

iOS Safari
#### OSes

iOS 8.1.2
### plugins

Observed with the default set of plugins used in the Brightcove player. I don't believe plugins are related to this issue.

**Comment by gkatsev** [comment]
Given that this has sat around for a while and iOS8 market share is tiny and this point and Video.js 7 doesn't support this, I'm closing issue.
