### ISSUE TITLE
Default caption track 

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#3264]
It does not work has default subtitles.
Libs.js  initialized in this way:
`var options = {
	"playbackRates" : [0.7, 0.8, 0.9, 1, 1.2, 1.5],
    "html5": { nativeTextTracks: false},
   "flash": {"swf": "http://2sub.ru/engine/editor/scripts/common/2sub/video-js.swf"}
};
var player = videojs('2sub', options);`

What wrong has been done?
The full news here:
`<Track kind = "captions" src = "http: //website/uploads/test.vtt" srclang = "en" label = "English" default >`

**Comment by gkatsev** [comment]
Default tracks turning on is a known issue ( #1914 ) with a fix upcoming ( #3248 ). Please follow those issues for updates. Thanks.
