### ISSUE TITLE
Full Screen Button Not Always Working

### ISSUE THREAD

**Issue by jlieb10** [videojs/video.js#3265]
## Description
When clicking the full screen button on the player, the video sometimes does not expand.

## Steps to reproduce
Place video in iframe, embed iframe, click button for fullscreen

### Expected
The player to expand full-screen

### Actual
In cases where the video player is the only player on the page and being used as the 'poster' for an article, full screen behaves properly. In cases where it is in the body of an article or there are other iframe players on the page, the player does not expand. As each player is running on its own URL in an iframe, there shouldn't be an issue of JS confusion.

### Error output
N/A

#### videojs
Most recent (5.8)
#### browsers
Error tested consistently in Chrome & Safari
#### OSes
Most recent OS X (10.11.4)
### plugins
https://github.com/googleads/videojs-ima

**Comment by mister-ben** [comment]
Do you have an `allowfullscreen` attribute on your iframe?

**Comment by jlieb10** [comment]
Thanks very much @mister-ben 👍 stupid mistake

**Comment by resource11** [comment]
Also: if you happen to have an iframe nesting another iframe containing a page with videojs content (yeah. THAT happened)... you need to add the `allowfullscreen` attribute to *both* iframes.

**Comment by gkatsev** [comment]
Haha, yeah, you'd need `allowfullscreen` all the way down.

**Comment by resource11** [comment]
Good times.
