### ISSUE TITLE
Including custom components when reordening ControlBar childrens

### ISSUE THREAD

**Issue by torresandres** [videojs/video.js#3268]
I need to include a custom components between the default ones in the ControlBar.

This [trick](https://github.com/videojs/video.js/issues/2673#issuecomment-145573055) to override controls order provided by @heff works fine:
```
videojs.getComponent('ControlBar').prototype.options_ = {
      loadEvent: 'play',
      children: [
        'playToggle',
        'muteToggle',
        'volumeControl',
        'fullscreenToggle'
      ]
}
```
I'm initializing my custom button component like this:
```
var ButtonComponent = videojs.getComponent('Button');
var MyButtonComponent = videojs.extend(ButtonComponent, {
  constructor: function() {
    ButtonComponent.call(this, player);
  },
  handleClick: function(){
    // On click stuff
  }
});
var MyButton = player.controlBar.addChild(new MyButtonComponent());
MyButton.addClass("vjs-logo-button");
```

Which is the correct way to include my custom component between, let's say, `muteToggle` and `volumeControl` ? 

Thanks in advance and awesome work from you guys.

**Comment by gkatsev** [comment]
I think there are two ways of achieving what you want to do. The first is to insert your item in the index you want (which is a new feature as of videojs 5.7).
The line would be something like:
```js
// the second argument to addChild is a zero-based index of where you want it to go
var myButton = player.controlBar.addChild(new MyButtonComponent(), 2);
```

The other way is registering your component with videojs and then listing it in the children array:
```js
// register the component by giving it a name and a reference to the constructor
videojs.registerComponent('MyButtonComponent', MyButtonComponent);

// then just use it like the built-ins:
videojs.getComponent('ControlBar').prototype.options_ = {
      loadEvent: 'play',
      children: [
        'playToggle',
        'muteToggle',
        'myButtonComponent',
        'volumeControl',
        'fullscreenToggle'
      ]
}
```

Hope those help.

**Comment by torresandres** [comment]
@gkatsev The second argument seems to be for the component's options but looking at the [addChild function declaration](https://github.com/videojs/video.js/blob/master/src/js/component.js#L343) now I see that it was the third argument what I needed and now I get it to work.

So this is the correct way to insert my custom component in the index that I want using `addChild` method:
```
var MyButton = player.controlBar.addChild(new MyButtonComponent(), {}, 6);
```
Works perfectly now. Thank you again 👍

**Comment by gkatsev** [comment]
Lol, oops, yeah, the 3rd argument is what I meant :)

**Comment by chemoish** [comment]
```
videojs('player', {
  controlBar: {
    children: [
      'playToggle',
      'muteToggle',
      // this
      'myButtonComponent',
      'volumeControl',
      'fullcreenToggle',
    ],
  },
}, function ready() {
  // or this
  this.controlBar.addChild('myButtonComponent', {}, 2);
});
```

**Comment by ahmadawada11** [comment]
Hi,
i am using the plugin "videojs-hls-source-selector" that add a button after the fullscreen button i can change the location by modifying the source file and pass the index of the button. is there another method? i tried to use videojs.getComponent('ControlBar').prototype.options_ and place the name of the component in the array but it is not working.
i ma using video jsversion 6.2.5

Thank you.
