### ISSUE TITLE
auto muted in mobile devices

### ISSUE THREAD

**Issue by ZohaibGhafoor** [videojs/video.js#3270]
I am using current version of videojs which is 5.9.2 and also test other versions . it works fine on desktop browsers but it auto muted on mobile browsers please solve this issue or any option ?

**Comment by gkatsev** [comment]
That shouldn't be the case. Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.
Also, what browsers/OSes specifically are you seeing this with?

**Comment by antiadiaz** [comment]
Hi!
I hace the same issue. The video is in autoplay with sound, and it works OK in desktop, but in mobile the video is muted. How can I solve it?
