### ISSUE TITLE
Videojs videoSource fallback error.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [videojs/video.js#3271]
i am using recent version of videojs and checked all versions. i am using dash mpd video with mp4 fallback. but whenever my mpd get some problem or videojs can not get it read. it is not falling back to mp4. and get error.

**Comment by gkatsev** [comment]
videojs has never done this before but we realize that it's probably a useful feature to have. Please follow https://github.com/videojs/video.js/issues/1316 for updates. Also, any help in implementing such a feature would be greatly appreciated.
Thanks.
