### ISSUE TITLE
the plugin marker is not accurate.

### ISSUE THREAD

**Issue by DonkeyInBeijing** [videojs/video.js#3273]
## Description
this is the markers array:
	    markers: [
			    {time: 9.5, text: "one"},
			    {time: 16,  text: "two"},
			    {time: 23.6,text: "three"},
			    {time: 28,  text: "four"}
		    ]
but what i see in the video, they are moved forward.

**Comment by gkatsev** [comment]
Is this for a specific plugin? Please open the issue against that plugin.
