### ISSUE TITLE
Mute video in data-setup

### ISSUE THREAD

**Issue by beyoyo2** [videojs/video.js#3274]
I can't seem to locate the proper syntax to mute the audio on a video from the data-setup line of code. 
Here is what i have.

data-setup='{ "controls": true, "autoplay": true, "preload": "auto", "fluid": true, "loop": true, "muted": true }'

Mac Firefox, Safari still play the audio. Chrome seems to be the only browser that honors it.

videojs 5.1.2

**Comment by gkatsev** [comment]
Have you tried just setting the muted attribute on the video element? I think we have some issues with it not working great when set through data-setup.

**Comment by beyoyo2** [comment]
this appears to work...
data-setup='{ "controls": true, "autoplay": true, "preload": "auto", "fluid": true, "loop": true }' muted

**Comment by gkatsev** [comment]
Cool. Using the video element attributes is definitely recommended over setting the properties in the data-setup, but we should definitely make it work still.

**Comment by beyoyo2** [comment]
thanks

**Comment by gkatsev** [comment]
This has been fixed and landed in 5.11.
