### ISSUE TITLE
How to change close caption button behaviour

### ISSUE THREAD

**Issue by sgavali** [videojs/video.js#3276]
## Description
vjs-caption-button currently shows a list of subtitle options, I want it to behave like default chrome button which just enable \ disable captions text after clicking on to it.

**Comment by gkatsev** [comment]
The best option is probably to not use the default menus but instead create your own Button component that [enables and disables the track as necessary](https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#showing-tracks-programmatically).

Hope that helps.
