### ISSUE TITLE
Android playback fails when cookies are required

### ISSUE THREAD

**Issue by powrsurg** [videojs/video.js#3277]
On Android every request that needs withCredentials to secure content fails because the native playback function does not send cookie data with it. This issue is described here:

https://code.google.com/p/android/issues/detail?id=66050

Note that I am testing on an S7 with Android 6.0.1, a very modern implementation at the time of this writing. This issue is still present. Also please be aware that this is not a browser-specific issue since it's occurring on Chrome and Firefox for Android.

Currently I was able to make playback work for me by editing the Html5.nativeSourceHandler.canPlayType, and Html5.nativeSourceHandler.canHandleSource to detect Android requests prevent them from return a successful criteria (all of my requests needed cookies so it was simpler for me to test this way to see if I could get it working and I am aware that a more robust solution would be needed for this procject)..

I have currently figured out how to detect Android, but have not yet determined how to detect the specific player for the given request that is being tested. Once I do that I will submit a pull request to patch such.

**Comment by gkatsev** [comment]
Have you tried setting the `crossorigin` attribute to `use-credentials`? If that doesn't work, I'm not sure there's really anything that videojs can do.

**Comment by powrsurg** [comment]
Wow, I really wish I considered this a week ago. Just set it and everything is working. Thank you!

**Comment by gkatsev** [comment]
Glad that works.
