### ISSUE TITLE
Not much of an issue - lag on updating currentTime on a drag event

### ISSUE THREAD

**Issue by jakelaz** [videojs/video.js#3278]
I am using a drag event in jquery to adjust the currentTime of a video, and am noticing about 500ms delays each time the function fires. If there is a limit to the frequency with which you can set currentTime values, is there a way to disable it within the video.js source code. If not, is there a different method to jump to a specific frame within the video based on a fraction of 1 generated by computing drag event left position over video frame width.

Here is the code:

                    $(".videoTimeAdjustor").mousedown(function () {
                        $(this).mousemove(function () {
                            var adjustorWidth=$(".videoTimeAdjustor").width();
                            var adjustorLeft=$(".videoTimeAdjustor").position().left;
                            var eventLeft=event.pageX - 170;
                            var percentage_across=eventLeft/adjustorWidth;
                            var myPlayer = videojs('videoAdjustorMedia');
                            var lengthOfVideo = myPlayer.duration();
                            
                            var videoTimeSet = percentage_across*lengthOfVideo;
                            console.log(videoTimeSet);
                            myPlayer.scrubbing(true);
                            myPlayer.currentTime(videoTimeSet);
                            
                        });
                    }).mouseup(function () {
                        $(this).unbind('mousemove');
                    }).mouseout(function () {
                        $(this).unbind('mousemove');
                    });

If anyone can suggest a better way of creating this functionality, please share.

**Comment by gkatsev** [comment]
I don't quite follow what a "drag event" is.
`player.currentTime` is basically the only way of seeking the player.

**Comment by gkatsev** [comment]
Closing this issue because it's unlikely to require a change to videojs itself. However, we can still continue the discussion here and if it turns out to actually be an issue with videojs, we can re-open the issue.
