### ISSUE TITLE
Video.js plays video too fast on firefox

### ISSUE THREAD

**Issue by mayanksriv** [videojs/video.js#3279]
Trying to run Videojs sample on different browsers to check compatibility with HLS (stream-url: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8)

This below code works fine on chrome and IE, but the video runs too fast on firefox (v45).

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="node_modules/video.js/dist/video-js.css" rel="stylesheet">
    <script src="node_modules/video.js/dist/video.js"></script>
    <script src="videojs-contrib-hls.js"></script>
  </head>
  <body>
    <video id="my-video" class="video-js" controls preload="auto" width="640" height="264" data-setup='{}'>
    <source src="http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8" type='application/x-mpegURL'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
  <script>
    var player = videojs('my-video');
    player.play();
  </script>
  </body>
</html>`

**Comment by ntamblyn** [comment]
I have noticed this as well, however i dont think this is a videojs issue but a videojs-hls-contrib issue.

**Comment by gkatsev** [comment]
As @ntamblyn said, it's a contrib-hls issue. Can you re-open this issue against [contrib-hls](/videojs/videojs-contrib-hls)?
Thanks.
