### ISSUE TITLE
Edge and Android out of sync on timed TextTrack cues

### ISSUE THREAD

**Issue by billybobilly** [videojs/video.js#3280]
We have a series of TextTrack cues loaded with a video and IE, Chrome, FF all play them in perfect sync.  On Windows 10 using Edge, the cues fire about 60 seconds off, in a range of plus or minus 20 seconds. The same thing happens with Android devices, firing around 85 seconds off, in about the same range.

## Steps to reproduce
1.  load a HLS video to play
2.  add text tracks and cues - subtitles, for example
3.  on playing, the subtitles fire at random times as stated above.

We are timing the cues based on an offset to the beginning timestamp of the first .ts segment in the m3u8 manifest.  Does anyone know if there is a case where these browsers are not starting with the first segment in the list?

Video.js 5.9.2
videojs-contrib-hls version 2.0.1

**Comment by dmlap** [comment]
Edge and Android use their own native HLS implementations for playback. I know Android's is particularly finicky and that can cause strange issues elsewhere during playback.

Are you seeing this issue with an actual live stream or a standard VOD HLS stream?

**Comment by billybobilly** [comment]
We don't do any VOD, just live.  Is there any way to tell the browser through javascript to use videojs instead of the native players on those devices/browsers?

**Comment by gkatsev** [comment]
There isn't really a way to force contrib-hls on for a browser right now. We probably should have such a thing, though.
