### ISSUE TITLE
Replay button

### ISSUE THREAD

**Issue by hartman** [videojs/video.js#3284]
Feature request:

I'm really enjoying the idea of flipping the look of the play button to a replay button on (non live) videos, after they have ended. I've been seeing this in more and more players and I think it is a very simple, elegant UI feature that would really benefit VideoJS as well.

**Comment by gkatsev** [comment]
We had a PR for this recently (https://github.com/videojs/video.js/pull/3154) which we ended up closing as it's not something that we'll be making in v5, however, for a v6, we'll consider making that change.
In the meantime, someone should make a small plugin that swaps the play toggle icon into a replay icon when the video ends.

**Comment by hartman** [comment]
Plugin
https://www.npmjs.com/package/videojs-replay

**Comment by misteroneill** [comment]
Nice! 👍

**Comment by gkatsev** [comment]
Awesome stuff @hartman!

**Comment by hartman** [comment]
Let's also extend a ping towards @aydinkn

**Comment by gkatsev** [comment]
Mentioning this in the vjs 6.0 megathread and closing this issue in the meantime.

**Comment by hartman** [comment]
See also: #3868

**Comment by gkatsev** [comment]
This was pulled into 6.0
