### ISSUE TITLE
Video element overlaying other components (refNode refers to wrong child) when a browser extension-added element is present before the video element prior to components being added to the DOM

### ISSUE THREAD

**Issue by orzage** [videojs/video.js#3286]
Certain browser extensions, such as the video speed controller for Chrome (https://github.com/igrigorik/videospeed,) may add an element directly before the video element.

The order of elements is as expected if this extension-added element happens to be added after the video.js components have been added (this depends on the timing, which can vary.) However, if it happens to be added before the video.js components have been added, then the refNode variable ends up being set to the video element, and the video.js components get added before the video element instead of after it:

http://oi64.tinypic.com/2ytwdo0.jpg
http://oi67.tinypic.com/28iq0ew.jpg

Since all of the components' elements, such as the control bar, get placed before the video element, the video element ends up overlaying them.

This occurs because the index used defaults to `this.children_.length` in addChild in component.js, which does not take into account the element added by the extension, while later code in the same function that uses the index does take such elements into account:

`let childNodes = this.contentEl().children;
 let refNode = childNodes[index] || null;`

**Comment by gkatsev** [comment]
We probably should update videojs to be resilient against things like this.
Either the [default index](https://github.com/videojs/video.js/blob/6385d1d4295c2b8d409dc7ba525f0fb609b1d997/src/js/component.js#L341) needs to change or the code for actually [adding the child](https://github.com/videojs/video.js/blob/6385d1d4295c2b8d409dc7ba525f0fb609b1d997/src/js/component.js#L404-L411) as you mentioned.

**Comment by gkatsev** [comment]
This seems to have been fixed because I use this extension and don't have issues with Video.js anymore.
