### ISSUE TITLE
Show menus onclick not on hover

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#3289]
Hi,

I'm trying to change menus to show and hide on click events and not on hover events so they behave the same way as YouTube buttons. I'm starting with the captions button. I commented out the hover class in the css and found the click functionality already existed.

However the menu was being hidden when the mouse was moved outside the button area. I found the Javascript responsible for this behaviour in src/js/menu/menu-button.js and commented out the line attaching the `unlockShowing` function.

Is this the right approach or will it cause problems elsewhere? It seems to be working.

Thanks.

```Javascript
   /**
   * When you click the button it adds focus, which
   * will show the menu indefinitely.
   * So we'll remove focus when the mouse leaves the button.
   * Focus is needed for tab navigation.
   * Allow sub components to stack CSS class names
   *
   * @method handleClick
   */
  handleClick() {
    this.one('mouseout', Fn.bind(this, function(){
      // I disabled the next line...
      // this.menu.unlockShowing();
      this.el_.blur();
    }));
    if (this.buttonPressed_){
      this.unpressButton();
    } else {
      this.pressButton();
    }
  }
```

**Comment by gkatsev** [comment]
Hi @edwinbradford, it does sound like you're on the right track with removing that `unlockShowing` line, also, you'll probably want to remove that `mouseout` listener altogether since otherwise you'll end up losing the focus of the button/menu when you mouse out which could be confusing.

Closing this issue because it's unlikely to require a change to videojs itself. However, we can still continue the discussion here.

**Comment by edwinbradford** [comment]
Thanks @gkatsev. Yes please, close the issue and thanks for the advice. I'm really enjoying working with VideoJS.

**Comment by hauk0101** [comment]
@edwinbradford In fact this problem can be solved by CSS ，you can set like this:
`.vjs-workinghover .vjs-menu-button-popup:hover .vjs-menu {
    display: none;
}`

**Comment by VasiliyRusin** [comment]
@gkatsev, Are you shure that change source code is the best idea? I suppose it should have API for this. Some kind of init parameter for all menu buttons.

**Comment by otoinsa** [comment]
Would be nice if the MenuButton component had the handler for "mouseenter" event in a class method, so we could override it (just like there is one for "mouseleave")!
