### ISSUE TITLE
Video.js/Youtube.js seek bar not working in Ipad

### ISSUE THREAD

**Issue by pirahana** [videojs/video.js#3292]
## Description
Briefly describe the issue.
I am using youtube.js and video.js(5.9.1).It is working fine on browsers.
Scenario 1.
When using without yrcontrols paramneter.
But in ipad just clicking on the video , pauses the video every time,so i cannot move the video forward or backward without the video being paused.

Scenario 2:
When using ytcontrols =2,
In this case the video doesnt pause on the first click.It works fine.But the seek bar of youtube video,cannot be moved forward or backward by clicking on seek bar..In this case i have hidden the video.js control bar because otherwise 2 controls were visible one of video.js and other of youtube.js.

I have also used the  nativeControlsForTouch and  customControlsOnMobile,but of no use.

## Steps to reproduce()Code
Explain in detail the exact steps necessary to reproduce the issue.

  "techOrder": ["youtube"],
        "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=" + videoId }],
     /*   "nativeControlsForTouch" : false ,
        "customControlsOnMobile": true ,*/
        "youtube": { "ytControls": 2 ,"iv_load_policy": 3}

what version of videojs does this occur with?  Video.js 5.9.1
what platforms (operating systems and devices) are affected? ipad 
### plugins
youtube.js

**Comment by gkatsev** [comment]
Can this be re-opened on videojs-youtube, if it doesn't exist there already?
