### ISSUE TITLE
Captions not show in fullscreen on iPad

### ISSUE THREAD

**Issue by alobimday** [videojs/video.js#3293]
## Description
Captions not show in fullscreen on iPad.

#### videojs 
5.9.2

#### browsers
iPad browser

### plugins
no plugins

**Comment by misteroneill** [comment]
There is not enough detail here to make any sort of judgment about what might be the cause. However, the iPad will use its native player in fullscreen.

Can you provide a test case on JSBin or public URL that demonstrates the issue?

**Comment by gkatsev** [comment]
Also please review this document https://github.com/videojs/video.js/blob/master/docs/guides/tracks.md#subtitles-from-another-domain specifically the "subtitles from another domain" section as that's often an issue on ios.

**Comment by alobimday** [comment]
This is url: http://fcine.net/videojs51/examples/elephantsdream/
caption will not shows if viewing fullscreen.

**Comment by hartman** [comment]
In fullscreen on iOS you can only use native subtitles.

**Comment by gkatsev** [comment]
As @hartman mentioned, you can't disable the native text tracks for iOS because if you go fullscreen it won't know what to do.
