### ISSUE TITLE
Error Message Not Displayed By Video.JS

### ISSUE THREAD

**Issue by eavestn** [videojs/video.js#3302]
## Description
Video.JS error message not displaying when file cannot be played, though added to DOM. 

Cannot provide reduced test case; read below reproduce instructions. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Take a copy of a bad video file natively compatible with your browser (e.g. mp4, ogg, etc.). A good way of doing this is renaming a .txt file to a .mp4 file
2. Use that file as the source for your player

### Expected
The "_The media could not be loaded, either because the server or network failed or because the format is not supported._" message should be displayed.

### Actual
The message is hidden. 

#### videojs
5.9.2
#### browsers
IE, all; Chrome, Mozilla

**Comment by mmcc** [comment]
Made a [reduced test case](http://jsbin.com/kimiwureri/edit?html,output) for you.

> Video.JS error message not displaying when file cannot be played, though added to DOM.

Just to clarify, this is inaccurate. The error is _thrown_, but the error display in the DOM is still empty.

**Comment by gkatsev** [comment]
It works for me with the latest code: https://jsbin.com/jafexe/1/edit?html,output
