### ISSUE TITLE
set 'nativeControlsForTouch'  and 'usingNativeControls' dosen't effect in mobile(ios,android)

### ISSUE THREAD

**Issue by yqb1989** [videojs/video.js#3305]
i saw this in the [source code](https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L116)
```
    // Determine if native controls should be used
    // Our goal should be to get the custom controls on mobile solid everywhere
    // so we can remove this all together. Right now this will block custom
    // controls on touch enabled laptops like the Chrome Pixel
    if (browser.TOUCH_ENABLED && options.nativeControlsForTouch === true ||
        browser.IS_IPHONE ||
        browser.IS_NATIVE_ANDROID) {
      this.setControls(true);
    }
```
it seems that the **nativeControlsForTouch** will never effect if set to **false** in ios or android

**Comment by Dracoborg** [comment]
Same issue here.

Phone: Nexus 5
OS: Android 6.0.1
Browsers:
    Chrome 50.0.2661.89
    Firefox 46.0.1

Also checked on Galaxy S5 but I don't know details.

**Comment by gkatsev** [comment]
#3410 has been merged and fixed in master. Release soon.
