### ISSUE TITLE
Issue with TOUCH_ENABLED in browser.js with touch screen and Windows 10 and Windows Phone 10

### ISSUE THREAD

**Issue by PatrikCarlander** [videojs/video.js#3306]
Current code:
```js
TOUCH_ENABLED = !!(('ontouchstart' in window) || window.DocumentTouch && document instanceof window.DocumentTouch);
```
This evaluate false with Windows 10 with touch screen and Browser: IE11, Edge and also with Windows Phone 10 and Edge, 
it evaluate true with Windows 10 and Browser: Chrome 50

Here is a bug fix:
```js
TOUCH_ENABLED = !!(('ontouchstart' in window) || window.navigator.maxTouchPoints || window.DocumentTouch && document instanceof window.DocumentTouch);
```
This evaluate true with Windows 10 with touch screen and Browser: Chrome 50 and IE11, Edge and also with Windows Phone 10 and Edge.
With a Windows 10 computer without touch screen it evaluate false as it should.

**Comment by gkatsev** [comment]
Interesting. I guess they changed some stuff.
Care to submit a PR to fix this?

**Comment by s1iqbal** [comment]
Ill get on it

**Comment by gkatsev** [comment]
@s1iqbal hey, did you want to make a PR for this?

**Comment by s1iqbal** [comment]
@gkatsev  yes please

**Comment by gkatsev** [comment]
@s1iqbal Hey, seems like you have a commit with this change? Do you need help making it into a pull request?
