### ISSUE TITLE
Native play overlay is layered underneath the video.js play overlay on iPhone

### ISSUE THREAD

**Issue by jrw95** [videojs/video.js#331]
![iphone-play-overlay](https://f.cloud.github.com/assets/359060/157126/7a95041c-76b6-11e2-8b02-c6943b9763c0.jpg)
Found during an exploratory test pass on my iPhone 4 running iOS 6.1.  Also reproduced on an iPhone 5 running iOS 6.0.

Not reproducible on iPad.

A test page is available at http://solutions.brightcove.com/jwhisenant/testpages/video-js/sandbox/ios-test.html

I'll attach a screen capture.

**Comment by pradeeprajr93** [comment]
Almost 5 years 😛 
https://stackoverflow.com/questions/19521667/disable-fullscreen-iphone-video
