### ISSUE TITLE
Custom video-js width and height on Dynamically Loaded Content

### ISSUE THREAD

**Issue by dpDesignz** [videojs/video.js#3311]
I'm dynamically loading video-js inside a [foundation reveal](http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html), and I have to trigger the width and height each time it loads. The odd thing is, once I've loaded one video on the page, it won't change it again no matter what, it only sticks to the one size.

This is my code

```
$(document).on('opened.fndtn', '[data-reveal]', function () {
        if($('.sd-video').length) {
            console.log('SD Detected');
            videojs($('.sd-video')[0], {"width": 640,"height": 480}, function() {});
        }
        if($('.hd-video').length) {
            console.log('HD Detected');
            videojs($('.hd-video')[0], {"width": 1287,"height": 720}, function() {});
        }
    });
    $(document).on('closed.fndtn', '[data-reveal]', function () {
        $('#'+$(this).attr('id')).html('');
    });
```

and no matter what I try, once it's loaded HD, the SD will not resize, and vice-versa. Any ideas?

**Comment by gkatsev** [comment]
Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.
Also, what versions of video.js, browsers, and OSes are used?

Are you sizing the player by trying to give `videojs()` options again? If so, you'd probably want to change it to call `player.dimensions(width, height)` instead because videojs ignores subsequent options given to it and just returns the original player.

**Comment by dpDesignz** [comment]
@gkatsev Thanks, I tried adding the code you mentioned, but I think I've got something wrong? It says `ReferenceError: player is not defined`

My updated code

`$(document).on('opened.fndtn', '[data-reveal]', function () {
			if($('.sd-video').length) {
				console.log('SD Detected');
				videojs($('.sd-video')[0], {}, function() {player.dimensions(640, 480);});
			}
			if($('.hd-video').length) {
				console.log('HD Detected');
				videojs($('.hd-video')[0], {}, function() {player.dimensions(1287, 720);});
			}
		});`

I'll try put a reduced test case up when I can if we can't sort this. :)

**Comment by gkatsev** [comment]
in that callback function, the context of the function is the player. so, you could do `this.dimensions(640, 480)`. However, that function doesn't get called if you call videojs again. Instead, you'd want to keep a reference to the player and use it later:
```js
var player = videojs($('.sd-video')[0]);
player.dimensions(640, 480);
```

**Comment by dpDesignz** [comment]
@gkatsev Hmm, I don't know what I'm doing wrong. I've uploaded a Reduced Test Case at http://www.kctv.new/assets/rtc/

**Comment by gkatsev** [comment]
That seems to be working fine, except you have both set to be 640x480.

**Comment by dpDesignz** [comment]
Whoops! I've updated the code. Still the same issue though :(

**Comment by gkatsev** [comment]
Looks like the issue is that the same id is used for both videos so videojs thinks it the same player.

**Comment by dpDesignz** [comment]
Oh perfect! Can't believe I missed that. Thanks heaps. Works perfectly now :)

**Comment by gkatsev** [comment]
Cool.
