### ISSUE TITLE
Javascript errors when no Windows Media Player available

### ISSUE THREAD

**Issue by marcinpl87** [videojs/video.js#3315]
My users use windows server 2012 and IE 11 (there is no Windows Media Player installed on win 2012).
When I open my app on win 2012 I see error "Not implemented" in videojs.js:15437 in "Html5.TEST_VID.volume = volume / 2 + 0.1;
I reproduce this issue with video.js 5.4.4 and 5.9.2 and 5.10.1 (I didn't check other versions, I assume this issue is in all versions).

It looks very similar to https://github.com/videojs/video.js/issues/984 , but that issue is closed. Can you please explain why that issue is closed? I use require.js to add video.js library to my app so this error breaks JS execution in my app.

**Comment by mister-ben** [comment]
[This](https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L907) fixed it at that time, but `canControlVolume()` and `canControlPlaybackRate()` get called first now.

**Comment by gkatsev** [comment]
I guess we need to add in a few more try/catches?

**Comment by misteroneill** [comment]
I'm seeing something similar that also seems related to this class of issues. I have IE10 throwing `SCRIPT65535: Unexpected call to method or property access.` [here](https://github.com/videojs/video.js/blob/master/src/js/tracks/audio-track-list.js#L17). I haven't dug into it, but wanted to log it here.
