### ISSUE TITLE
Video not working using video.js version 4.11 in Safari desktop and iOS

### ISSUE THREAD

**Issue by niravvarma** [videojs/video.js#3316]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Hit the following url: http://wcs.dksh.com/cs/dksh_com/testvideo
2. Same url works properly in other browsers  like firefox, chrome, IE but fails to work in safari browser

### Expected
Please describe what you expected to see.
Video should have loaded. Video is loaded with very basic setup using video.js src code within one single script file - scriptFooter.js

### Actual
Please describe what actually happened.
Video not working in any safari browser be it mobile or desktop

### Error output
If there are any errors at all, please include them here.
The element or ID supplied is not valid. (videojs)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
4.11
#### browsers
what browser are affected?
Safari
#### OSes
what platforms (operating systems and devices) are affected?
Mac OS and iOS

### plugins
are any videojs plugins being used on the page? If so, please list them below.
Nope

**Comment by hartman** [comment]
You sure it works in other browsers ?
```
            var videoId = $(videoContainer).attr('id');
            _V_(videoId).ready(function() {
```
Because your video doesn't have an id attribute, so videoId is undefined.

**Comment by niravvarma** [comment]
Yes, I tried with other browsers and video is working fine even if the error of id is visible in console. Only issue is with Safari browser :( in Mac and iOS devices.

**Comment by niravvarma** [comment]
As you suggested, I just added id to the video tag, now I get the following error:

CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED
The video could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by hartman** [comment]
That means that Safari does not think that your video track is HTML5 compatible. BTW. these kinds of questions have little to do with the video.js sourcecode and are probably better suited for something like stackoverflow.

**Comment by gkatsev** [comment]
One thing to try it adding `crossorigin="use-credentials"` to the video element. It seems like the back-end could want cookies but safari doesn't send them by default.

Anyway, I'm closing this issue because as @hartman said it's most likely not a video.js issue.
