### ISSUE TITLE
volume bar background not displaying until clicked - video.js 4.12

### ISSUE THREAD

**Issue by codeEnthusiast2** [videojs/video.js#3317]
I am using video.js 4.12 and prior to my video starting and during play, the volume bar background I have styled via 
`background: #000 url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAYAAAAGCAYAAADgzO9IAAAAP0lEQVQIHWWMAQoAIAgDR/QJ/Ub//04+w7ZICBwcOg5FZi5iBB82AGzixEglJrd4TVK5XUJpskSTEvpdFzX9AB2pGziSQcvAAAAAAElFTkSuQmCC) -50% 0 repeat`
does not appear until the user clicks on the volume bar. 

Observe:
![snip_20160512005423](https://cloud.githubusercontent.com/assets/19325726/15213761/b547b0c0-1823-11e6-9197-137e1c80e13f.png)
This is what it should look like:
![snip_20160512005504-2](https://cloud.githubusercontent.com/assets/19325726/15213777/d828b0ee-1823-11e6-86d0-7987d0cb82fc.png)

How do I fix it?

**Comment by gkatsev** [comment]
Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? There could be a magnitude of reasons why it is happening and it's hard to narrow down based on the information provided. Also, please provide versions of browsers you're using.

However, version 4.12 of videojs is quite old and we're unlikely to fix any issues. Is there any reasons you can't update to version 5?

**Comment by codeEnthusiast2** [comment]
No worries! I simply needed to add `width:100%` to the CSS for `.vjs-default-skin .vjs-volume-level`. As for why I have not upgraded, I have spent quite some time styling my player and when I switch that all goes out the window. 4.12 seems to be sufficient for my needs.
