### ISSUE TITLE
player.hls is deprecated warning

### ISSUE THREAD

**Issue by pedromcunha** [videojs/video.js#3318]
Hey all, thanks for creating this great library. I'm currently playing hls video and every time I try to access the tech via this function:

```
var playlist = e.tech({
   IWillNotUseThisInPlugins: true
}).hls.playlists.media();
```

I receive a warning that looks like this:
_VIDEOJS: WARN: player.hls is deprecated. Use player.tech.hls instead._

Is there a different way that I should be accessing the tech? I tried to do tech.hls but it results in undefined.

**Comment by gkatsev** [comment]
That sounds like a bug. It shouldn't be printing that warning when used that way. Can you re-open this issue against the [contrib-hls project](https://github.com/videojs/videojs-contrib-hls/issues/new)?
Thanks.
