### ISSUE TITLE
Player .on method

### ISSUE THREAD

**Issue by AdielMtz** [videojs/video.js#3319]
I want to get whether or not the player is in full screen. If is in fullscreen, with Jquery move DOM element inside the player.

**Comment by gkatsev** [comment]
You can [listen](http://docs.videojs.com/docs/api/player.html#Methodson) to the [`fullscreenchange`](https://github.com/videojs/video.js/blob/master/src/js/player.js#L223) event and then ask the player to see if it [isFullscreen](http://docs.videojs.com/docs/api/player.html#MethodsisFullscreen).
```js
var player = videojs('my-video');
player.on('fullscreenchange', function() {
  if (player.isFullscreen()) {
    moveElement();
  } else {
    moveItBack();
  }
});
```
Hope that helps.
