### ISSUE TITLE
customized mpd file is playing on the video js 4.6 version but it is not playing on video js version 5.8

### ISSUE THREAD

**Issue by amitgaikwad712** [videojs/video.js#3322]
I have started with video js 5.8 version and I had done with playback of youtube video, normal uploaded video on our site, HLS and Dash as well. But our mpd file structure changed with few parameters like segment sequence generated on the server side and it seen like no playback of .mpd file on the latest version of video js. thats why I have tried with video js 4.6 version and surprisingly its work on it. But the Problem is other playback stuff is broken like youtube video, normal uploaded video and HLS .m3u8 file. So any one know which changes should I have to do for dash file that will work on the video js latest version.

**Comment by gkatsev** [comment]
Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.
Also, are you using contrib-dash? What version of contrib-dash are you using? Can you [open an issue](https://github.com/videojs/videojs-contrib-dash/issues/new) on that repo instead?
