### ISSUE TITLE
Allow us to change sources even if we hit a media that is not supported in the currentbrowser

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#3323]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

When you select a media for example webm in Internet Explorer it causes it to show an error that says this media is not supported or something similar to that but you carn't do anything else, you carn't change source or do anything else. With ogv.js it supports the ogv format in Internet Explorer and Microsoft Edge with js.

The only way to get the player to do anything is to refresh the page and I think it selects the media it supports. But again if you select webm from source switcher it causes the error and you carn't do anything else until you refresh again. Please could you support changing sources even if the media your on is not supported. Would solve having to refresh everytime.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.10.1
#### browsers
what browser are affected?
All that doint support the format you click on
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.
https://github.com/kmoskwiak/videojs-resolution-switcher

**Comment by gkatsev** [comment]
You should be able to call `player.error(null)` to clear out the error and then change the src afterwards. Automatic re-sourcing -- trying a different source when the first chosen source is selected -- is something that has been discussed and something we want to make happen but it'll probably be a while before we get to it ourselves.

**Comment by paladox** [comment]
Ok thanks for replying.
