### ISSUE TITLE
Unable to play flv videos on a local html.

### ISSUE THREAD

**Issue by Zzzen** [videojs/video.js#3324]
## Description
  Videojs doesn't work if I open a local html.

## Steps to reproduce
1. create a index.html on your machine. ( important! Don't use jsbin. )
2. set the content of it:
```
<head>
<link href="http://vjs.zencdn.net/5.8/video-js.min.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/5.8/video.min.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264" data-setup="{}">
    <source src="http://www.mediacollege.com/video-gallery/testclips/20051210-w50s.flv" type='video/x-flv'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="http://vjs.zencdn.net/5.9.2/video.js"></script>
</body> 
```
3. double click to open it.

### Expected
It should play when I click the giant play button.

### Actual
Nothing happens, there is even no error output on console.

### Error output
No output

## Additional Information
`video-js.swf` was loaded successfuly
#### videojs 
5.8
#### browsers
Chrome, firefox, edge
#### OSes
windows10 64.
### plugins
No plugins.

**Comment by gkatsev** [comment]
Unfortunately, that is a limitation of flash and not videojs. It won't really load properly when loaded in over the `file:` protocol. We strongly recommend to use local web servers when working with anything dealing with flash, and even when working with websites locally as well.

**Comment by Zzzen** [comment]
Do you know any workaround? I want to videojs and electron to make a player.

**Comment by gkatsev** [comment]
Why not run a local webserver and load it over that?

**Comment by Zzzen** [comment]
Interesting. I'll try it.

**Comment by Zzzen** [comment]
It has a severe problem that seeking is not available until whole file is "downloaded".

**Comment by gkatsev** [comment]
If seeking isn't available until the whole file has loaded that means that the file metadata is at the end of the file and there isn't much you can do about it other than re-transcode (in which case, I would suggest using an mp4 or webm or something that electron/chrome supports natively).
