### ISSUE TITLE
mutating the prototype of an object will cause your code to run very slow

### ISSUE THREAD

**Issue by nmpribeiro** [videojs/video.js#3325]
I have the following warning:
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

Supposedly from the following line of video.js:
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

Versions and details as follows:

#### videojs
Video.js 5.10.2
#### browsers
firefox 45.1.0
#### OSes
centos 7
### plugins
no plugins for video.js, I am using bigvideo and ngvideo

**Comment by gkatsev** [comment]
That's a warning that firefox generators but it's harmless and can be ignored.
Specifically, it's caused because we're using the new javascript `class` syntax and compiling it down using babel.
