### ISSUE TITLE
Latest documentation: are addChild() methods up to date? Seem to be missing 'index' param?  

### ISSUE THREAD

**Issue by videojs-user** [videojs/video.js#3331]
Should the child passed in with the index replace the current component at the children[index] position?

**Comment by videojs-user** [comment]
If it is an insert action, could we have a 'replaceChild()' method? Or do we have to use removeChild() and then addChild()?

**Comment by gkatsev** [comment]
Yeah, I think the docs are out of date. It's the next thing to tackle on my agenda.

**Comment by videojs-user** [comment]
Hi Gary,


That's fine - I'll read the code directly. I'm using removeChild() + addChild() to do a replace.


Thanks


Bob


________________________________

**Comment by erikyuzwa** [comment]
I'm not sure where to do that, but feel free to pull me in @gkatsev.

**Comment by gkatsev** [comment]
We're going to be working on updating the docs in the coming months. Closing in the meantime.
