### ISSUE TITLE
If we right click on player then 'Show controls' option is visible, if we select that then basic HTML5 player controls along with custom player controls are visible

### ISSUE THREAD

**Issue by dineshb-qa** [videojs/video.js#3332]
**Steps to Reproduce**

1. Hit the URL : http://videojs.com/
2. Play the video
3. Right click on the player 
4. Observe that options like : 'Loop', 'Show controls' etc are visible on player
5. Now select the 'Show controls' option
6. Observe that : Basic HTML5 player controls along with custom player controls are visible for player

**Expected Results** : 

1. 'Show controls' option should not be visible when we right click on player
2. Only custom player controls should be visible on video player

**Actual Results** :  
If we right click on player then 'Show controls' option is visible, if we select that then basic HTML5 player controls along with custom player controls are visible

**Configuration Manifesting** :
Windows 8, Chrome 50

**Content Manifesting** :
http://videojs.com/

**Video.js Version** : v5.9.2

**Notes** :
See the attached screen shot : 
![two_player_controls_20may](https://cloud.githubusercontent.com/assets/6957604/15431779/fffea280-1ec8-11e6-8f16-95d2294aaa91.png)

**Comment by gkatsev** [comment]
Unfortunately, there isn't really much we can do about this beyond overriding the entire context menu completely. For videojs, we're not quite ready to do that by default yet. You can either disable it or override it by using the [`contextmenu`](https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu) event.
