### ISSUE TITLE
When the player is loading the basic HTML5 player controls are visible for few seconds

### ISSUE THREAD

**Issue by dineshb-qa** [videojs/video.js#3333]
**Steps to Reproduce**

1. Hit the URL : http://videojs.com/
2. Observe that : When the player is loading the basic HTML5 player controls are visible for few seconds. And after that start screen is visible

**Expected Results** : 
When the player is loading the basic HTML5 player controls should not be visible

**Actual Results** :  
When the player is loading the basic HTML5 player controls are visible for few seconds

**Configuration Manifesting** :
Windows 8, Chrome 50

**Content Manifesting** :
http://videojs.com/

**Video.js Version** : v5.9.2

**Notes** :
See the attached screen shot :
![basic_html5_player_controls_while_player_loading_20may](https://cloud.githubusercontent.com/assets/6957604/15432253/191b94ec-1ecb-11e6-89af-63d826d87b57.png)

**Comment by gkatsev** [comment]
Yeah, this is a sort of known "flash of native controls" issue. If you add the controls attribute to the video element by default, it will be shown while the player is loading. However, if you remove it and forget to configure videojs with the controls options, you will be left without controls.
There also isn't really anything we can do with css about this, so, it's really up to users of videojs to decide whether that is an issue or not and then do the above workaround.

**Comment by mister-ben** [comment]
`video.video-js::-webkit-media-controls { display:none; }` works on Chrome and Safari
