### ISSUE TITLE
Controls can be improved for mobile environments

### ISSUE THREAD

**Issue by ZOulou2b** [videojs/video.js#3336]
## Description
On phones and tablets devices, controls are a bit too small to provide the users a smooth and easy experience of video playing.

Use the default reduced test case to see what I meen, for instance with Chrome on an android tablet
http://jsbin.com/axedog/edit?html,output

## Steps to reproduce
1. Tell your 'big fingers' bro' Marcus to come to your desk
2. Run the given test case on a tablet or mobile phone
3. Tell him to use the controls bar (play button, cc and full screen toggle buttons, ...)

### Expected
Marcus would easily launch the video, switch to full screen mode, and back to minimized mode.

### Actual
Well, if he's agile, he'd probably go fine...
But he'll surely find that it's a bit complicated to precisely use the controls.

### Error output
N/A

## Additional Information
Indeed, the underlying issue is that the API does not provide a specific option for mobile native controls anymore.
The `nativeControlsForTouch` still affects the behavior of the player, which means that the Videojs' custom controls are then replaced by the native one.
**But**, the option is not documented anymore, and is buggy with android.
Once the native controls bar is automatically hidden, it's very hard to get it back visible.
See: http://jsbin.com/tohobexicu/2/edit?html,output

Edit: We've also detected that with embedded VideoJS' control bar on mobile devices, it isn't fluid when one wants to move forward and backward by clicking the PlayProgressBar.
Also we can't drag the progress button to smoothly move the video back and forth.
That'd be nice if we could provide our users this kind of experience with the VideoJS player.

#### videojs
5.1
#### browsers
Tested on Chrome, Safari, Samsung Internet for Android
#### OSes
- Galaxy S6 / Android 5.1.1
- Galaxy Tab 4 / Android 5.1.1
- Ipad mini 3 / iOS 9.3.1

### plugins
N/A

**Comment by ctaity** [comment]
+1

**Comment by gkatsev** [comment]
Yes, this is something that can be improved. Historically, we've disabled our custom controls on mobile devices because the controls weren't thoroughly tested or had device-specific issues.
We have an old issue about this that I'm going to close this in favor of: https://github.com/videojs/video.js/issues/396.
