### ISSUE TITLE
Subtitles off

### ISSUE THREAD

**Issue by ntamblyn** [videojs/video.js#3340]
is there a way to detect when the subtitles off is triggered ?

**Comment by gkatsev** [comment]
Heh, apparently, that's the only thing I forgot to mention in this doc: https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md
But you can listen to the `change` event which is triggered on the `player.textTracks()` object when the `mode` of a particular text track changes.

**Comment by ntamblyn** [comment]
Thanks for the fast response. 

It helped a lot, i have implemented this now. 

So will close the ticket.
