### ISSUE TITLE
Question: fluid layout

### ISSUE THREAD

**Issue by marktaylor46** [videojs/video.js#3341]
## Description
I am using videojs to create a background video on my website and have used the fluid layout. What I am trying to do is to always have the video take up the whole background (ie. the container) all the time so that no "black" area would ever show. I accept that if the video is letter box aspect ratio that the fluid behaviour is making the video fit 100% width but this means I end up with a black area at the bottom of the page which is not what I want. 

What I'd like to happen is for the sides of the video to be clipped so that 100% height is maintained. 

Conversely, I don't ever want to see left/right black border either (even if that means clipping the top/bottom too).

Is there an option to do this with videojs?

Latest version of videojs used.
Windows 10 64bit
All browsers and versions.

**Comment by gkatsev** [comment]
Videojs doesn't have that option built-in. And we're probably not going to be adding it.
I would suggest checking out projects like [bigvideo.js](http://dfcb.github.io/BigVideo.js/) and [videojs-background](https://github.com/matthojo/videojs-Background).
