### ISSUE TITLE
Strech the PlayProgress for ranged videos

### ISSUE THREAD

**Issue by rahbr** [videojs/video.js#3346]
I'm using Rangeplay plugin to delimit the start and end video duration. But it dont changes the playprogress behavior.

I need to stretch the PlayProgressBar and recalculate the seekRange to reflect this start and end range. 

IE the video lenght is 58seconds. The ranges are start 15 sec and the end is 49 sec.

0-------|=======|-----58        <= Before with ranges
15|===============|49    <= After playprogress stretch (desired)
video 0/37

What would be the easiest way to do this?
Thankyou!

**Comment by mmcc** [comment]
Sorry, but there's no easy way to do this out of the box, so you'll need to do custom work to get that behavior. Sounds like a great idea for a plugin, though :)
