### ISSUE TITLE
HD/Resolution/Quality selector feature?

### ISSUE THREAD

**Issue by fmp777** [videojs/video.js#3347]
A pretty big standard online is to serve SD quality content first, and allow user selection to HD content.

Does videojs have this?  I've seen a third party attempt to implement it, but its not very solid IMO, and requires non-CDN version of video.js, and doesn't work with playlists.

**Comment by hartman** [comment]
There are two plugins that do something in this area:
* [videojs-resolution-switcher](https://github.com/kmoskwiak/videojs-resolution-switcherl) if you have multiple sources
* [videojs-quality-picker](https://github.com/streamroot/videojs-quality-picker), which is more suited for HLS, dash, youtube type of streams.

Both are not without some manual configuration of course.

**Comment by fmp777** [comment]
ahh videojs-resolution-switch seems like it'll work, thanks @hartman !!  Tried to get it to work with playlists though and just leaves "undefined" in the control bar.  Will the playlists pass the variables properly like this?

"sources":[
				{
					"src":"video.mp4?sd",
					"label": "SD", "res": '480'
				},
				{
					"src":"video.mp4?hd",
					"label": "HD", "res": '1080'
				}]

**Comment by sikanderzel** [comment]
how to change resolution order in video js ?
means my player resolution settings order is 240 at top . i want to have 240 at bottom how to do that ?

**Comment by gkatsev** [comment]
@sikanderzel you'll want to check the documentation of the plugin you're using.

**Comment by JanSichula** [comment]
The link to videojs-resolution-switcher is broken as it contains an additional "l" at the end of URL.

But anyway, this is exactly what I was looking for to use in our church video archive where we need to publish both SD and HD versions of videos and let the users switch which one they prefer.

**Comment by SolmazKh** [comment]
The plugins mentioned here only work with videojs v5. What if I want to add this feature for videojs v6?

**Comment by rikai** [comment]
@SolmazKh https://github.com/silvermine/videojs-quality-selector should work, i think? :)
