### ISSUE TITLE
playing video failed to render its background when it has a poster attribute.

### ISSUE THREAD

**Issue by DonkeyInBeijing** [videojs/video.js#3348]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.add poster attribute with a image (640 * 264) pixel.
2.click play button to play the video.
3.the background was white until click on the video screen again.
![Uploading a.png…]()

### Expected
it should be black background.

### Actual
it was white except the actual video area.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Sorry, it isn't clear what your issue is. Please make a reduced test case as described in the issue template.

**Comment by DonkeyInBeijing** [comment]
this is my reduced test case url.
[http://10.1.243.77:8099/rc/demo.html](url)

on the demo.html page, if i add a width and height as well as poster attributes to video element. i get this problem:
when i click on play icon, the video can not render its background. 

thank you.

**Comment by DonkeyInBeijing** [comment]
Sorry it is a LAN IP，I post my code as below:
`<!doctype html>
<html lang="zh-CN" ng-app="app">
  <head>
    <script src="video.js" type="text/javascript"></script>
    <link href="video-js.css" rel="stylesheet">
  </head>
  <body>
    <div>
      <video id="video-example" class="video-js vjs-default-skin" controls preload="auto"  width="640" height="264"  poster='D-501.jpg' data-setup='{}'>
        <source src="demo.mp4"></source>
      </video>
    </div>
  </body>
</html>

<script type="text/javascript">


      var player = videojs('video-example', { /* Options */ }, function() {
        console.log('Done!');
      });

</script> `

**Comment by DonkeyInBeijing** [comment]
Sorry it is a LAN IP，I post my code as below:
<!doctype html>
<html lang="zh-CN" ng-app="app">
  <head>
    <script src="video.js" type="text/javascript"></script>
    <link href="video-js.css" rel="stylesheet">
  </head>
  <body>
    <div>
      <video id="video-example" class="video-js vjs-default-skin" controls preload="auto"  width="640" height="264"  poster='D-501.jpg' data-setup='{}'>
        <source src="demo.mp4"></source>
      </video>
    </div>
  </body>
</html>

<script type="text/javascript">


      var player = videojs('video-example', { /* Options */ }, function() {
        console.log('Done!');
      });

</script> 

> 

> 

>

**Comment by DonkeyInBeijing** [comment]
on the demo.html page, if i add a width and height as well as poster attributes to video element. i get this problem:
when i click on play icon, the video can not render its background.
**<!doctype html>
<html lang="zh-CN" ng-app="app">
  <head>
    <script src="video.js" type="text/javascript"></script>
    <link href="video-js.css" rel="stylesheet">
  </head>
  <body>
    <div>
      <video id="video-example" class="video-js vjs-default-skin" controls preload="auto"  width="640" height="264"  poster='D-501.jpg' data-setup='{}'>
        <source src="demo.mp4"></source>
      </video>
    </div>
  </body>
</html>**

`<script type="text/javascript">

      var player = videojs('video-example', { /* Options */ }, function() {
        console.log('Done!');
      });

</script> `

thank you.

**Comment by DonkeyInBeijing** [comment]
on the demo.html page, if i add a width and height as well as poster attributes to video element. i get this problem:
when i click on play icon, the video can not render its background.
```html
<!doctype html>
<html lang="zh-CN" ng-app="app">
  <head>
    <script src="video.js" type="text/javascript"></script>
    <link href="video-js.css" rel="stylesheet">
  </head>
  <body>
    <div>
      <video id="video-example" class="video-js vjs-default-skin" 
controls preload="auto"  width="640" height="264"  poster='D-501.jpg' data-setup='{}'>
        <source src="demo.mp4"></source>
      </video>
    </div>
  </body>
</html>
```
```javascript
<script type="text/javascript">
      var player = videojs('video-example', { /* Options */ }, function() {
        console.log('Done!');
      });
</script> 
```
