### ISSUE TITLE
Exit of full screen scroll content to page top

### ISSUE THREAD

**Issue by vaske** [videojs/video.js#3355]
## Description
I have about 120 videos in grid and the whole content is scrollable, once when I scroll down from top visible part of page an play video, open it in full screen mode and close it the focus on page jumps to page top. This occurs only in chrome.

## Version
Video.js 5.10.2
chrome

**Comment by vaske** [comment]
Looks like this is Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=142427

**Comment by gkatsev** [comment]
Thanks for finding that chrome bug. Sounds like a browser bug. It may be possible to create a work-around for it. Capture the scroll-top on the first `fullscreenchange` event -- when entering fullscreen -- and then restoring it on the second `fullscreenchange` event -- when exiting fullscreen.

**Comment by gkatsev** [comment]
Looks like that issue is fixed.

**Comment by nirdil** [comment]
I don't believe this issue is fixed. I still encounter it.
Moreover - capturing the scroll-top on fullscreenschange event doesn't work as it's too late and the scroll-top is already zeroed out.
How can I capture the full screen toggle click before it is handled?

**Comment by nirdil** [comment]
Update:
I did something like this instead:
`
_player = window.videojs(_videoID, _options);
_controlBar = _player.getChild("controlBar");
_fullscreenToggle = _controlBar.getChild("fullscreenToggle");
        		
_fullscreenToggle.on(["tap", "click"], function() {
     if (_player.isFullscreen()) {
          // get current scroll top
          // ...
     }
});     		
_player.on('fullscreenchange', function() {
     if (!_player.isFullscreen()) {
          // restore scroll top
          // ...
     }
});
`
This works fine in desktops (tested only in chrome, windows) but on an android mobile chrome produced inconsistent results- if the video (e.g. the scrolling position) is near the end of the scrolling area, then when restoring to the prefetched scrolltop produces a slightly offsetted scrolltop.

BTW, Maybe I'm running into these problems as my page's layout is somewhat complex - the videos are contained within a scrollable div that is accelerated with a "transform: translate3d(0, 0, 0);"...

**Comment by gkatsev** [comment]
You may want to restore the scroll top after a short set timeout (maybe 100ms, worth playing around with this value). This is because `fullscreenchange` triggers when the change begins and there can be a short animation before the fullscreen change is finished.
