### ISSUE TITLE
Error When Open using playback google drive

### ISSUE THREAD

**Issue by creativefull** [videojs/video.js#3359]
yes i get error to when i using url from google drive

like this

````
https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=d1b3cfed90e018aa&itag=18&source=webdrive&app=texmex&ip=2604:a880:0:1010::8d4:8001&ipbits=32&expire=1465299416&sparams=requiressl%2Cid%2Citag%2Csource%2Cip%2Cipbits%2Cexpire&signature=7F83952D684CAA839E328E2970F856D2B5BCBDFA.2F1D4D036078433372BF390513971605320DC65C&key=ck2&mm=30&mn=sn-ab5l6n7z&ms=nxu&mt=1465284882&mv=m&nh=IgpwcjAxLmxnYTA3KgkxMjcuMC4wLjE&pl=48
````

please help me :(

player wan't play get show this error

`ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not`

but if i open using video html5 without it's working without error

 ````
<video controls>
    <source src="https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=d1b3cfed90e018aa&itag=18&source=webdrive&app=texmex&ip=2604:a880:0:1010::8d4:8001&ipbits=32&expire=1465299416&sparams=requiressl%2Cid%2Citag%2Csource%2Cip%2Cipbits%2Cexpire&signature=7F83952D684CAA839E328E2970F856D2B5BCBDFA.2F1D4D036078433372BF390513971605320DC65C&key=ck2&mm=30&mn=sn-ab5l6n7z&ms=nxu&mt=1465284882&mv=m&nh=IgpwcjAxLmxnYTA3KgkxMjcuMC4wLjE&pl=48" type="video/mp4"></source>
</video>`

**Comment by gkatsev** [comment]
Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.
Also, can you include the other information that the issue template asked for like videojs, os, and browser versions.

**Comment by misteroneill** [comment]
Also, that URL returns a 403 Forbidden, which may have something to do with it.

**Comment by creativefull** [comment]
no no no no 403 forbiden ,.. ok i'll give you real url ,.. wait

**Comment by creativefull** [comment]
https://redirector.googlevideo.com/videoplayback?requiressl=yes&id=d1b3cfed90e018aa&itag=18&source=webdrive&app=texmex&ip=2604:a880:0:1010::8d4:8001&ipbits=32&expire=1465328278&sparams=requiressl%2Cid%2Citag%2Csource%2Cip%2Cipbits%2Cexpire&signature=142897B8481D7454AD0DD6E2C8003026A1969F05.9E6827C1F0C715A337CC170615B3A7509978BB3A&key=ck2&mm=30&mn=sn-ab5l6n7z&ms=nxu&mt=1465313673&mv=m&nh=IgpwcjAxLmxnYTA3KgkxMjcuMC4wLjE&pl=48

try click that's link and see

**Comment by gkatsev** [comment]
That link plays great for me in videojs.

**Comment by creativefull** [comment]
ok i just remove attribute crossorigin and it's fix :)

**Comment by creativefull** [comment]
sorry i reopen again ,. because this's not fix for me ,..

if i remote attribute crossorigin i can't load subtitle and cover from other site ,.
and if i use crossorigin video.js can't play that video ,..

help me again :)

**Comment by gkatsev** [comment]
Unfortunately, that's a known issue and there's nothing we can do about it unless google adds CORS headers to the mp4 files. See https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#subtitles-from-another-domain for some more information.

**Comment by polaris0227** [comment]
Hi, @creativefull 
How are you?
Would you plz guide me to get "redirector.googlevideo.com..." url using google file id?
Here is a link [https://drive.google.com/file/d/0B-5JhYOpAOVKVVFpd1oyRVJxdms/view?usp=sharing](url)
Thanks.

**Comment by creativefull** [comment]
@polaris0227 just access api https://docs.google.com/get_video_info?docid=xxxxxxx&mobile=true

**Comment by creativefull** [comment]
@polaris0227 or message me for got full script http://facebook.com/muzaksay

**Comment by polaris0227** [comment]
Thank you for your reply.

Would you plz check this url?
https://embed.streamdor.co/video/328237
You will find its docid (0B3LPTilvbqc3TG1odk1ZWWg1ODA) and it exists.
But I can't get redirector url using it.
It says no file exists.
Plz guide me the solution if possible.

Kind regards.

**Comment by creativefull** [comment]
https://embed.streamdor.co/api/video/328237 because that using ajax bro, i've server got redirector.googlevideo

**Comment by polaris0227** [comment]
But we can get doc id using chrome develop console.
This is the result:

{"playlist":[{"sources":[{"file":"https:\/\/redirector.googlevideo.com
\/videoplayback?id=afad1eafa175cad2&itag=22&source=webdrive&requiressl=yes&ttl=transient&pl=33&ei=E94_WdfqGcK2qwWTtKTwDg&driveid=0B3LPTilvbqc3ajU0b0dpZ1VsYk0&mime=video%2Fmp4&lmt=1493954879257333&ip=2600%3A3c01%3A%3Af03c%3A91ff%3Afe60%3A9103&ipbits=0&expire=1497372243&sparams=driveid,ei,expire,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,ttl&signature=4C17CC93B585DD580F1A22596095C861D4FFACDA.805338226E18136D9EFEE38E9B8EDFDA9119DEB0&cms_redirect=yes&mm=31&mn=sn-n4v7sn7y&ms=au&mt=1497357757&mv=m&key=cms1&app=explorer","type":"mp4","label":"720p"},{"file":"https:\/\/
redirector.googlevideo.com
\/videoplayback?id=afad1eafa175cad2&itag=59&source=webdrive&requiressl=yes&ttl=transient&pl=33&ei=E94_WdfqGcK2qwWTtKTwDg&driveid=0B3LPTilvbqc3ajU0b0dpZ1VsYk0&mime=video%2Fmp4&lmt=1493954898570737&ip=2600%3A3c01%3A%3Af03c%3A91ff%3Afe60%3A9103&ipbits=0&expire=1497372243&sparams=driveid,ei,expire,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,ttl&signature=3977C1DC947D2EDEA1788A7264401D91C6123086.1F3C2F87F22775D2E9F7877B663496EE2A77A956&cms_redirect=yes&mm=31&mn=sn-n4v7sn7y&ms=au&mt=1497357757&mv=m&key=cms1&app=explorer","type":"mp4","label":"480p"},{"file":"https:\/\/
redirector.googlevideo.com
\/videoplayback?id=afad1eafa175cad2&itag=18&source=webdrive&requiressl=yes&ttl=transient&pl=33&ei=E94_WdfqGcK2qwWTtKTwDg&driveid=0B3LPTilvbqc3ajU0b0dpZ1VsYk0&mime=video%2Fmp4&lmt=1493952254857613&ip=2600%3A3c01%3A%3Af03c%3A91ff%3Afe60%3A9103&ipbits=0&expire=1497372243&sparams=driveid,ei,expire,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,ttl&signature=2D7C6DE8DE5A849339FE4665FA2B266655E8EA7D.3273E99CFB665E4DBDD06160F9655C0252DC8E34&cms_redirect=yes&mm=31&mn=sn-n4v7sn7y&ms=au&mt=1497357757&mv=m&key=cms1&app=explorer","type":"mp4","label":"360p","default":true}],"tracks":[{"default":true,"file":"\/\/
embed.streamdor.co
\/grabber-api\/webvtt\/328237.vtt","label":"English","kind":"captions"}]}]}

**Comment by creativefull** [comment]
so ? what i can help for u ?

**Comment by polaris0227** [comment]
Thank you for your kind reply.

As you see, we can get driveid from the above response.
But I can't get url using the driveid and api you send me.
Is there any way to get urls from driveid we found?
(Seems driveid is changed)

Kind regards.

**Comment by dorklord23** [comment]
@creativefull, could you tell me where did you put crossorigin attribute?

**Comment by polaris0227** [comment]
@creativefull 
Do you have any solution to remove driveid from the link?
Thanks.
