### ISSUE TITLE
webkit-playsinline not working anymore in videoJS 5+

### ISSUE THREAD

**Issue by rossi256** [videojs/video.js#3360]
## Description
Briefly describe the issue.
We are using Videojs in our ionic app (UIWebView) and on version videoJS version 4.11.4 we have working custom skin/controls on iPhone.
Now we upgraded to 5.10.5 and webkit-playsinline seems to not work anymore - native controls on iPhone coming up always.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. have webkit-playsinline in video tag on 4.11.4 --> native controls hidden on iPhone
2. upgrade videoJS to 5.10.5 --> native controls take over and can't be hidden

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs 
4.11.4 vs 5.10.5

#### 
platform: iOS / devices: iPhones

ref:
https://github.com/videojs/video.js/issues/1367

**Comment by rossi256** [comment]
#1367

**Comment by rossi256** [comment]
https://github.com/videojs/video.js/issues/1367

**Comment by rossi256** [comment]
#1367

**Comment by rossi256** [comment]
Looking into this more, 
in safari inspector, when i remove:
_vjs-using-native-controls vjs-controls-disabled_ from the wrapping <div> and
_controls_ in the resulting <video tag
native controls disappear and only custom videojs skin stays.

**Comment by gkatsev** [comment]
The custom controls are disabled by default. You'll want to tell videojs to use custom controls for that.
There's the `nativeControlsForTouch` option that should be set to `false` but apparently we have a bug with it right now: https://github.com/videojs/video.js/issues/3305

**Comment by gkatsev** [comment]
I'm going to close this as it will be addressed when #3305 is fixed.

**Comment by gkatsev** [comment]
#3305 is being fixed in the upcoming release. The PR for it was just merged.
