### ISSUE TITLE
5.10.5 broke our deploy to heroku

### ISSUE THREAD

**Issue by mreinsch** [videojs/video.js#3361]
## Description

When using 5.10.5 (through bower) we couldn't deploy our ember app to heroku anymore as the compilation of the ember app failed with: 

`ENOENT: no such file or directory, open '/tmp/build_6c3b96ae3272f1c4cc703b1edf299365/ember-frontend/tmp/concat_with_maps-input_base_path-UDAdEhKQ.tmp/0/bower_components/video.js/dist/node_modules/global/document.js'`

We then downgraded to 5.10.4 and deploy is back to normal now.

### Notes
I couldn't reproduce the build issue locally actually using `ember build` which made debugging this issue quite difficult. Further, I can't really say what is happening, just that this is happening and took me about half a day to resolve. I assume it has to do with 
### Setup
In our setup we're using Rails asset pipeline, where video.js is used as a bower component as part of a ember.js project using ember-cli-rails / ember-cli.
#### videojs
5.10.5
#### node
4.2.6 (but seems to happen on other versions as well)
#### npm
2.13.4
#### ember-cli
1.13.8
#### ember-cli-rails
0.7.3

**Comment by gkatsev** [comment]
That's really bizarre. We haven't changed any such usage in 5.10.5. The changes are literally a handful of lines (at the end of https://github.com/videojs/video.js/compare/v5.10.4...v5.10.5). I don't know why `ember build` would be looking for a `node_modules` folder inside of `bower_components` let alone `video.js/dist`. Our [`bower.json`](https://github.com/videojs/video.js/blob/b7fdf21a05fca4158041b95b30f3950495414444/bower.json#L4-L7) specifically says to just use `dist/video.js` and `dist/video-js.css` which are pre-built files.

**Comment by misteroneill** [comment]
It's hard to say what might be going on. How is video.js being included in your Ember app?

**Comment by mreinsch** [comment]
yes, it's very bizarre. I'm suspecting the changes to `package.json` to be a contributing reason - which actually prompted me to try and downgrade to 5.10.4. 
I'm quite sure it wasn't some temporary thing, I tried to deploy quite a couple time, including purging heroku's cache, and it would repeatedly fail with the above error. 
Once downgraded, it deployed flawlessly.

**Comment by mreinsch** [comment]
@misteroneill we're including it through https://github.com/IvyApp/ivy-videojs

**Comment by gkatsev** [comment]
It looks like ivy is using [the dist file](https://github.com/IvyApp/ivy-videojs/blob/master/index.js#L35) so, I'm not sure why `node_modules` is involved at all at this point.
As for the `package.json` change, that just makes the versions be explicit instead of ranges, so, I don't understand how it could affect anything.

**Comment by gkatsev** [comment]
@mreinsch hey, does 5.10.6 work for you? 5.10.5 apparently had some issues also with unminified `video.min.js` file.

**Comment by mreinsch** [comment]
5.10.6 seems to indeed resolve the issue we were having with 5.10.5. Thanks, closing.

**Comment by gkatsev** [comment]
That must've been it.
