### ISSUE TITLE
Mass videos not loading.

### ISSUE THREAD

**Issue by owinckle** [videojs/video.js#3362]
## Description
I have a website, hosting multiple videos on the same pages, and some video take about 5 mins to load.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Open nicolaswinckler.fr
2. Go to Video page, and chose a category.
3. Try loading a video, some won't load, or will take forever.

## Results
Some are not loading, and some are taking forever.
### Expected
I expect to have the video load instantly.

### Actual
Some video are not loading, or taking foerver.

## Additional Information
I have the latest video.js version.

**Comment by misteroneill** [comment]
This isn't an issue with video.js, but with your server and the way you've set up your web pages to load dozens of MP4 files totaling well over 100MB (I closed the page at ~110MB).

**Comment by owinckle** [comment]
Hi, I'm currently using a Godaddy hosting "Economy" offer, and I'd appreciate if you could suggest another hosting plan that would suit my website. Thanks

**Comment by gkatsev** [comment]
A potential solution would be to just set `preload="none"` on all the videos so they don't start loading until a particular video is played.
