### ISSUE TITLE
Question: Is there a way to start without the bigPlayButton, but already showing the controls?

### ISSUE THREAD

**Issue by githubdoramon** [videojs/video.js#3364]
## Description
I can remove the big play button, but then the user don't have how to start the playback. I want to load the player with the controls already enabled.
I tried to force the controls to be show with css, but only the play appears.

## Steps to reproduce
Just init the player with:
 var options = {
        bigPlayButton: false
}

## Results
No controls are shown.
### Expected
I want the controls to be available on load.

#### videojs
5.10.2
#### browsers
using Chrome

**Comment by gkatsev** [comment]
Probably the easiest way is to add this rule:
```css
.video-js .vjs-control-bar {
  display: flex;
}
```
However, this will only work for browsers that support flexbox and will actually cause issues in browsers that don't since we use table layout as a fallback.
Another potential fix is to add `vjs-has-started` class to the player which hides the big-play-button and displays the controls.

**Comment by githubdoramon** [comment]
Since the first option may be a issue, I tried the second one, but the player removes this class... Even when I try to add after like this:

`audio = videojs(videoMarkupId, options);
audio.addClass("vjs-has-started");`

So I tried

`audio = videojs(videoMarkupId, options).ready(function(){
        var myPlayer = this;
        myPlayer.addClass("vjs-has-started");
    });`

Nothing.... Then

`audio = videojs(audioMarkupId, options);
    setTimeout(function () {
        audio.addClass("vjs-has-started");
    }, 2000);`

And that works... nut it seens like the WORST option ever... Any idea why adding the class immediatelly don't work?

**Comment by mmcc** [comment]
Your second solution seems to [work fine for me](http://jsbin.com/jotuzomejo/edit?html,output).

Assuming you have an audio tag:
```
<audio 
    id="my_video_1" 
    class="video-js vjs-default-skin" 
    controls
    preload="auto"
    width="640"
    height="268"
    src="http://www.stephaniequinn.com/Music/Allegro%20from%20Duet%20in%20C%20Major.mp3">
```

Add the class in the `ready` callback (or `.ready()`, works either way):

```
  <script>
    var audio = videojs('my_video_1', {}, function() {
      this.addClass('vjs-has-started');
    });
  </script>
```

**Comment by githubdoramon** [comment]
Found the problem :(

I am using HLS, and things happen a little different apparently... Just for future reference I solved like this:

`
var audio = videojs(audioMarkupId, options);
    var hls = audio.tech({ IWillNotUseThisInPlugins: true }).hls;
    hls.playlists.on("loadedplaylist", function() {
        audio.addClass("vjs-has-started");
    });
`

Thanks for the help

**Comment by gkatsev** [comment]
@mmcc I'm actually unable to add `vjs-has-started`. It seems to get removed by videojs. Not sure exactly how or why.

**Comment by gkatsev** [comment]
if you add the class before `loadstart` has triggered, it'll get removed [here](https://github.com/videojs/video.js/blob/819b787f5f92f498a8b357774bf0d1920f491437/src/js/player.js#L831) which comes from [`handleTechLoadStart_` calling `hasStarted(false)`](https://github.com/videojs/video.js/blob/819b787f5f92f498a8b357774bf0d1920f491437/src/js/player.js#L808) *after* our player ready function has ran.

**Comment by gkatsev** [comment]
I'm not sure there's anything we can or should do.
As a workaround, you can just do re-add the class on `loadstart` event.
