### ISSUE TITLE
doesn't work in IE

### ISSUE THREAD

**Issue by crimsonmouse** [videojs/video.js#3365]
Hi,
I tested video examples from http://videojs.com/advanced/. All work perfectly in FF, Chrome, Opera, Safari except IE.
I get the message:
{"code":4,"message":"The media could not be loaded, either because the server or network failed or because the format is not supported."}
I cannot find any error. 
Help, please and make any suggestions, please.

error{"code":4,"message":"The media could not be loaded, either because the server or network failed or because the format is not supported."}
srchttp://d2zihajmogu5jn.cloudfro(…)ed_hd.mp4
currentSrchttp://d2zihajmogu5jn.cloudfro(…)ed_hd.mp4
crossOrigin
networkState2
preload"auto"
buffered[0.00, 0.00]
readyState0
seekingfalse
currentTime0
duration46.6133333
pausedtrue
defaultPlaybackRate1
playbackRate1
played
seekable
endedfalse
autoplayfalse
loopfalse
controlstrue
volume1
mutedfalse
audioTracks{"length":1}
videoTracks{"length":0}
textTracks{"length":7}
width0
height0

currentWidth1302
currentHeight0
videoWidth1280
videoHeight720
poster//d2zihajmogu5jn.cloudfront.ne(…)poster.png
readyState0
loadstart2
suspend0
abort0
error1
emptied2
stalled0
loadedmetadata1
loadeddata1
canplay1
canplaythrough0
playing0
waiting0
seeking0
seeked0
ended0
durationchange1
timeupdate0
progress3
play0
pause0
ratechange0
volumechange0

**Comment by mister-ben** [comment]
Cloudfront has the wrong Content-Type header for the Blender videos: `Content-Type:application/octet-stream`

**Comment by crimsonmouse** [comment]
thank you:)
you resolved the issue!
