### ISSUE TITLE
IE11 loaded metadata never fires 

### ISSUE THREAD

**Issue by psharmz** [videojs/video.js#3368]
## Description
In IE11, annotations do not show up for this video:

Ran into the same issue as this post:
http://stackoverflow.com/questions/28681917/video-js-loadedmetadata-event-never-fires

We expect that it is related to the flash fallback as the issue does not occur in Chrome, Safari, or Firefox. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the following video in chrome http://hapyak_demos.s3.amazonaws.com/demandgen.html
2. Click on the annotations, such as ask a question, fill out form etc. 
4. Load the same video in IE11 http://hapyak_demos.s3.amazonaws.com/demandgen.html
5. Click on the annotations again

### Expected
Annotations show up in both Chrome and IE11

### Actual
Annotations such as button, form, and MC show up in Chrome but not IE11. 
There was a fix to this....if you use player ready instead of loadedmetadata then it works on IE11
http://hapyak_demos.s3.amazonaws.com/demandgen-v2.html

### Error output
In IE11 console the error 'unexpected token' was shown. Looking at the Network tab, you see that hapyak.js loaded but not config.js so that confirms that loadedmetadata did not fire. 

## Additional Information
http://hapyak_demos.s3.amazonaws.com/demandgen-v2.html (works on IE11) and
http://hapyak_demos.s3.amazonaws.com/demandgen.html (does not work on IE11)
you can compare the page source for both 

This issue is resolved but looking at the documentation at https://support.brightcove.com/en/perform/docs/known-issues-studio-and-brightcove-player#player, it doesn't say anything about IE11 limitations. It may be good to note this for the future, that ready should be used instead of loademetadata

**Comment by gkatsev** [comment]
We believe this is fixed as part of https://github.com/videojs/videojs-contrib-media-sources/pull/94 and https://github.com/videojs/videojs-contrib-hls/pull/672
