### ISSUE TITLE
Current Time and Remaining Time not synchronized

### ISSUE THREAD

**Issue by rezwanhaleem** [videojs/video.js#3369]
Is it normal for the current time and remaining time to not be in sync?

I noticed that the current time display is a few milliseconds slower than the remaining time display.

Thank you!

**Comment by gkatsev** [comment]
That sounds like a side-effect of how we handle the updates for those components. We listen for `timeupdate` and then update each one. So, if the current time controls listens before the remaining time control, it could get drawn a few milliseconds earlier. A possible solution would be to use `requestAnimationFrame` to do the actual DOM updates which should hopefully align the two draws together, though, I'm not positive it will help.
Are you seeing a delay large enough for the times to be largely out of date?

**Comment by rezwanhaleem** [comment]
No, its not large and I dont think normal people would really care to notice. I am a noob at this stuff so was just asking out of curiosity. Thanks!

**Comment by gkatsev** [comment]
If anyone wanted to help out, this should be a simple one. It requires wrapping the code that updated the DOM of the time components in a requestAnimationFrame (if it isn't already).

**Comment by gkatsev** [comment]
Actually, looks like this was done in a recent refactor: https://github.com/videojs/video.js/blob/master/src/js/control-bar/time-controls/time-display.js#L117
