### ISSUE TITLE
http://vjs.zencdn.net/5.10.4/video.js Return 403 Forbidden

### ISSUE THREAD

**Issue by amit777** [videojs/video.js#3371]
## Description
Briefly describe the issue.
The CDN link mentioned in the documentation returns 403 Forbidden:
http://vjs.zencdn.net/5.10.4/video.js

The following link does work:
http://vjs.zencdn.net/5.10.2/video.js

and 
http://vjs.zencdn.net/5.10/video.js  returns 5.10.2

**Comment by dpDesignz** [comment]
Same issue here

**Comment by alexcroox** [comment]
Same issue

**Comment by gkatsev** [comment]
Published, sorry for the wait.
