### ISSUE TITLE
remove event

### ISSUE THREAD

**Issue by FuDengrong** [videojs/video.js#3372]
## Description
When I click this video panel, it can toggle play() and pause() ,  how can I  remove this event?
## Expected
I want it does nothing when I click this video panel, only can click the button to toggle play() and pause()

Can you help me? Thank you!

**Comment by mmcc** [comment]
There was an [issue](2302) for this a while back, but the example was for 4.12. Lucky, it looks like it [still works](http://jsbin.com/hoqohifula/edit?html,js,output)!

Relevant JS:
```javascript
var player = videojs('your_player_id', {}, function() {
  this.posterImage.off(['click', 'tap']);
});
```

**Comment by FuDengrong** [comment]
thank you! It works.
