### ISSUE TITLE
Is there is any example in the web of emulated texttracks working? 

### ISSUE THREAD

**Issue by davidtorroija** [videojs/video.js#3375]
Hi, I'm trying to use the emulated tracks to change the caption styles and positioning but in the v5.10. 
I'm only able to see the native captions.
when I add this line of code the captions dissapear
html5: {
             nativeTextTracks: false
}

the question is there is any example in the web of emulated texttracks working? 
Thanks!

**Comment by gkatsev** [comment]
If you load a player in firefox or force the flash tech, it'll use emulated text tracks.

**Comment by davidtorroija** [comment]
mmm I will create a reduced test case to see if it's working, thanks

**Comment by davidtorroija** [comment]
Ok was a problem with my skin in :) thanks

I have another question, how to change the texttrack color for example programatically without using the textttrack settings menu? 
this answer in [https://github.com/videojs/video.js/issues/1721](url) is old and I think does not apply to the v5 version

**Comment by gkatsev** [comment]
There isn't really a good way of doing it programmatically. You could probably override the `textTrackSettings` `getValues` method but it'll still be be limited to those values.

**Comment by rejais** [comment]
@gkatsev so how do I change for example : track background transparancy ?

**Comment by gkatsev** [comment]
It isn't really a supported feature right now, it's partly a side-effect of how vttjs, the library we use for making the text tracks work, creates the the text track display.
If native tracks are used, you can style them using the `::cue` pseudo selector, though, I'm not certain of the browser support for that.

**Comment by gkatsev** [comment]
Going to close this because the original question is answered.
