### ISSUE TITLE
Autoplay working on iPhone but does not working on iPad

### ISSUE THREAD

**Issue by gaoshanyu** [videojs/video.js#3377]
I use video.js in my node project for play video, everything is well(it working well on Chrome(MAC&Windows), Safari(MAC&iPhone), Android), but the only problem is the "autoplay" function does not working on iPad Safari. Does anyone here knows and tells me why?
All the related code as below( you can copy the code to a .html file and try it on your browser ):
`<!DOCTYPE html>
<html lang="en">
<head>
	<link href="http://vjs.zencdn.net/5.0.2/video-js.css" rel="stylesheet">
	<script src="http://vjs.zencdn.net/ie8/1.1.0/videojs-ie8.min.js"></script>
	<script src="http://vjs.zencdn.net/5.0.2/video.js"></script>
</head>
<body>
<video id="example_video_1" class="video-js vjs-default-skin" controls autoplay preload="auto" webkit-playsinline="true" x-webkit-airplay="true" width="750" height="460" poster="" data-setup="{}">
				<source src="http://vjs.zencdn.net/v/oceans.mp4">
</video>
</body>
</html>`

**Comment by misteroneill** [comment]
I am not sure how `autoplay` is working on an iPhone unless you're testing with an old version of iOS (pre-6.1). [Apple disables `autoplay` and `preload` on iOS](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html):

> In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled. No data is loaded until the user initiates it. This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.

Sorry, it's not possible.

**Comment by gaoshanyu** [comment]
Yes, it can auto play on my iPhone5(iOS9.3.3 beta), and I also tried it on iPhone6p(iOS9.3.2), iPhone5s(iOS9.3.2), all works. Have you tried the code I sent in the question? If not, please try and then to say 'it's not possible'. Genuine knowledge comes from practice.

**Comment by gkatsev** [comment]
I just tried it and cannot get it to autoplay on an iOS device. Apple disallows it in all currently released versions of iOS. Apple just announced that on iOS 10, you will be able to autoplay on iOS if your video doesn't have an audio track or the audio track is disabled. See https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html#//apple_ref/doc/uid/TP40014305-CH11-DontLinkElementID_11

However, if you are running this inside a webview, things could be different. The above definitely applies to Safari on iOS but webviews could have slightly different rules.

**Comment by gaoshanyu** [comment]
Thanks guys for help to testing! Here is my mistake, I've just retried for this again, it can autoplay with WeChat browser but cannot autoplay with Safari. So, sorry for confused.

**Comment by sanex3339** [comment]
Hi, in the last 6 months, there any dirty hack to allow autoplay on IOS?

**Comment by 1tincup** [comment]
Autoplay should work if audio is muted

**Comment by amrutkarsagar** [comment]
Not working on iPhone as well...Anyone can you please suggest how fix this issue or has any working hack for it..Need urgently..

**Comment by gkatsev** [comment]
muted autoplay should work well in the latest release of Video.js. However, it's recommended to use the `play()` method over the `autoplay` attribute.

**Comment by amrutkarsagar** [comment]
Not working on iPhone.This is react component
`import React, { Component, PropTypes } from 'react';
import videojs from 'video.js';
import 'video.js/dist/video-js.min.css';

class MediaPlayer extends Component {
  constructor(props) {
      super(props);

      this.state = {
          player: null
      };
  }  

  componentDidMount() {
    const {video} = this.props,
        player = videojs(video.id).ready(function() {
          this.play();
          let myPlayer = document.querySelector('video');
          myPlayer.setAttribute('autoplay', 'autoplay');
      });
    
    this.setState({player});
  }

  componentWillUnmount() {
    if (this.state.player) {
      this.state.player.dispose()
    }
  }

  render() {
    const {video: {id, src}} = this.props;
    const videoHtml = `
      <video id="${id}" class="video-js vjs-default-skin" controls muted autoplay webkit-playsinline="true" x-webkit-airplay="true">
        <source src="${src}" type="video/mp4" />
      </video>
    `
    return (
      <div dangerouslySetInnerHTML={{__html: videoHtml}}></div>
    )
  }
};

MediaPlayer.propTypes = {
    video: PropTypes.object
};

export default MediaPlayer;`

Please let me know if I did anything wrong over here.

**Comment by gkatsev** [comment]
What version of video.js are you using? Also, it's just `playsinline` now.

**Comment by amrutkarsagar** [comment]
"video.js": "^6.2.7"

**Comment by amrutkarsagar** [comment]
Any review on my above comment ?
