### ISSUE TITLE
TextTracks cause VoiceOver to stutter (iOS)

### ISSUE THREAD

**Issue by powrsurg** [videojs/video.js#3379]
When VoiceOver is enabled for iOS 9.3.2 with VideoJS 5.10.4 we have found that the VoiceOver stutters when reading off the text from a WebVTT file. The file is actually displayed to users properly so this works for deaf viewers, just not blind viewers that need audio descriptions.

**Comment by powrsurg** [comment]
Update, this appears to happen on OS X desktop as well.

**Comment by hartman** [comment]
Does it still give entire sentences ? Or is it like continuously trying to read the start of the line ?

**Comment by powrsurg** [comment]
I kept on stripping things away and I was able to determine that this is not a VideoJS issue. I had our videos in a parent element with aria-live="assertive" in it which is what made VO continuously read everything (even the time). So I do not know if this is VO being too strict or NVDA not being strict enough, but either way this is not an issue with VideoJS and as such I am closing this ticket.

**Comment by gkatsev** [comment]
Thanks for reporting your findings @powrsurg!
