### ISSUE TITLE
How can I let the voice button on  the right

### ISSUE THREAD

**Issue by zhangwei900808** [videojs/video.js#3385]
I want to control the voice button on the right how can to do that?

**Comment by mister-ben** [comment]
Do you mean the audio tracks button? Can you explain what you want to achieve?

**Comment by zhangwei900808** [comment]
yes I want to left audio button on the panel right

**Comment by gkatsev** [comment]
Do you want to move the volume button over?
You can create a player and tell the control bar the order of children that you want. See: https://jsbin.com/qawoneh/edit?html,output

**Comment by zhangwei900808** [comment]
Thanks^_^
