### ISSUE TITLE
How to properly close a video.js

### ISSUE THREAD

**Issue by Gabyheavy** [videojs/video.js#3386]
I am using a video.js div that I create dynamically then I use this to initialized it :

```
videojs("last", { "fluid": true }, function () {
    var myplayer = this;
    myplayer.currentTime(20);
    $(document).click(function (event) {
        if (!$(event.target).closest('#must-relative').length &&
           !$(event.target).is('#must-relative')) {
            rmDiv(video); // function that supress the div
        }
    })
});
```
It supress the div but the problem here is that I can't reopen the video and I get this warning:

> VIDEOJS: WARN: Player "last" is already initialised. Options will not be applied.

Also I read about a closebutton but couldn't find a way to use it :'(

**Comment by misteroneill** [comment]
If you have a reference to a player, you can use the `dispose()` method to destroy it:

```js
videojs.getPlayers().last.dispose();
```

Then creating a new player with that same name/ID won't cause that warning.

**Comment by Gabyheavy** [comment]
Thanks for the fast reply, I can indeed recreate it but then I when I want to close it again I get

> video.js:20082 Uncaught TypeError: Cannot read property 'vdata1466608873924' of null

**Comment by misteroneill** [comment]
That error usually means you're trying to dispose something that's already disposed.
