### ISSUE TITLE
Win7 IE9 doesn't play audio

### ISSUE THREAD

**Issue by kmcarter** [videojs/video.js#3387]
I am doing IE9 testing through Browserstack, and what I am finding is that HTML5 video does not play audio. If an `embed` tag is used, as opposed to video.js's `video` tag usage, audio works again. You can reproduce these results with video.js's homepage video demo.

To reproduce:

1. In IE9, go to the videojs.com homepage and start the video. Note the lack of audio.
2. Open just the sample video - http://vjs.zencdn.net/v/oceans.mp4 - in its own new tab in IE9. Note that you now have audio.

Here is the HTML that IE9 uses to play the working video when it's loaded by itself:

`<embed width="100%" height="100%" src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4" fullscreen="yes"/>`

Workarounds until this is fixed are very welcome (I have a product to ship)! I'm currently trying to find a way to force swf usage in IE9.

**Comment by misteroneill** [comment]
I just tested this using Win7/IE9 via VirtualBox and got audio just fine.

If you want to force SWF usage for IE9 (not sure why you'd want to, though), try something like:

```js
var isOldIE = somehowDetermineThatThisIsOldIE();

videojs('my-player-id', {
  techOrder: isOldIE ? ['flash', 'html5'] : ['html5', 'flash']
});
```
