### ISSUE TITLE
video.js failing when changing source

### ISSUE THREAD

**Issue by xtatanx** [videojs/video.js#3389]
## Description
Helo guys,
I am creating a video carousel using Brightcove smart player which is built on top of videojs, every time I click on a thumbnail I update the src of the video player and automatically play the video. This is working good across all browsers however, on IE11 Windows 8.1 and also IE11 Windows7 I am having an intermittent error.

`VIDEOJS: TypeError: Unable to get property 'playlist' of undefined or null reference`

Which seems to be related to this block of code:
```
/**
   * Pass values to the playback tech
   *
   * @param {String=} method Method
   * @param {Object=} arg Argument
   * @private
   * @method techCall_
   */

  Player.prototype.techCall_ = function techCall_(method, arg) {
    // If it's not ready yet, call method when it is
    if (this.tech_ && !this.tech_.isReady_) {
      this.tech_.ready(function () {
        this[method](arg);
      }, true);

      // Otherwise call method now
    } else {
        try {
          this.tech_[method](arg);
        } catch (e) {
          _utilsLogJs2['default'](e);
          throw e;
        }
      }
  };
```

## Steps to reproduce
We are just getting an instance of the player using `var $player = videojs.getPlayers()["ideas-video-module"];` and every click on a thumbnail we are doing this:

```
	/**
	 * Update videoPlayer url, share metadata and poster image
	 *
	 * @param  {String} videoUrl       url of the new video
	 * @param  {Object} socialMetadata metadata to be used in share overlay
	 * @param  {String} posterUrl      url of the new poster image
	 */
	function updatePlayer(videoUrl, videoUrlMp4, socialMetadata, posterUrl) {
		$player.pause();
        // we change poster image here and add social metadata
		$player.src([
			{type: "application/x-mpegURL", src: videoUrl},
			{type: "video/mp4", src: videoUrlMp4}
		]);
	}
```

For security reasons I don't think I will be able to share the url of the website. I will try to place a JSbin emulating this as soon as posible.

I appreciate if you guys have some inputs on why could we be facing this issue and probably if is related to the fact we are using HSL on this.

Regards

**Comment by gkatsev** [comment]
The above does seem like a contrib-hls issue. We are aware of this issue but I'm not sure it's logged on contrib-hls, where hls-related issues should be logged.

**Comment by xtatanx** [comment]
Thanks @gkatsev  I am going to replicate this message in contrib-hsl and see if I can get any answers.

Regards

**Comment by gkatsev** [comment]
Cool. Closing in favor of https://github.com/videojs/videojs-contrib-hls/issues/755
