### ISSUE TITLE
Error in safari running rtmp.

### ISSUE THREAD

**Issue by sobytes** [videojs/video.js#3391]
Hi All,

I am getting this error in safari only, when trying to run rtmp works in firefox and chrome fine.

Video.js: currentTime unavailable on Flash playback technology element.

~~~
<video id="video" class="video-js vjs-default-skin" controls>
  <source type="rtmp/mp4" src="rtmp://example/live/stream" />
  <source type="application/x-mpegURL" src="https://example/mobile/stream.m3u8" />
</video>
                
var videoPlayer = videojs("video", {
    "preload": "none",
    "techOrder": ["flash", "html5"],
    "autoplay": true
}, function() {

});
~~~

![screen shot 2016-06-23 at 16 11 25](https://cloud.githubusercontent.com/assets/2689776/16308662/cf01066e-395d-11e6-80a5-8dce4769ad68.png)

I have just this as a current work around.
~~~
var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
var videoPlayer = videojs("video", {
    "preload": "none",
    "techOrder": (isSafari) ? ["html5"] : ["flash","html5"],
    "autoplay": true
}, function() {

});
~~~

Any suggestions 

I am running 

Video.js 5.10.5
with
videojs-contrib-hls version 3.1.0

Thanks

**Comment by gkatsev** [comment]
Why not just set html5 as the default tech?

**Comment by sobytes** [comment]
Hi @gkatsev 

Because of my setup i want to serve RMTP for all desktops if possible as the delay is significantly less with RTMP from my live stream.

The same thing is happening with this example.

http://output.jsbin.com/cayake

![screen shot 2016-06-23 at 16 27 06](https://cloud.githubusercontent.com/assets/2689776/16309083/5cb1bc50-395f-11e6-90c4-69fd3e492845.png)

**Comment by mister-ben** [comment]
This is playing without error for me in Safari 9 both in your example which uses 4.11 and a [copy](http://output.jsbin.com/lapelokuno) using 5.10.7.

**Comment by gkatsev** [comment]
Thanks for confirming @mister-ben.
Going to close this but if we get more info and it's still an issue, we can re-open.
