### ISSUE TITLE
Playback rate button behaviour

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#3394]
I've been developing a new skin theme which is almost complete. I have one function I need help with please. I've disabled hover states so that all the control button menus open onClick events like YouTube and not on hover states like Videojs. It's mostly for aesthetic reasons only.

Everything is working for Captions, Subtitles, Descriptions and Chapters which all open their respective menus onClick. Playback rate is not functioning the same way. When I click on the playback button the playback rate value toggles but the menu does not open as it seems it should in the demo [here](http://jsbin.com/vikun/1/edit?html,output)

Is there a way to get the playback rate menu to open onClick?

The only amend I have made to the videojs javascript files is to comment out part of `handleclick()` in menu-button.js as follows:

```javascript
handleClick() {
    /**
     * Disabled for Neue theme because we only want
     * menus to respond to clicks
     *
    this.one('mouseout', Fn.bind(this, function(){
      // this.menu.unlockShowing();
      this.el_.blur();
    }));
    */
    if (this.buttonPressed_){
      this.unpressButton();
    } else {
      this.pressButton();
    }
  }
```

**Comment by mister-ben** [comment]
`handleClick()` is overridden in [the playback rate button](https://github.com/videojs/video.js/blob/master/src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js#L95) so your changes to the menu button aren't effective. You'd need to modify or extend `PlaybackRateMenuButton`.

The playback rate control/menu should probably have the same behaviour as the other menu buttons, but which behaviour should be the default will be divisive - some want the toggle/cycle on click behaviour for captions.

**Comment by edwinbradford** [comment]
Thanks for the solution -- I'm more of a designer than a developer but I was just able to figure it out a few hours before I got your reply. The code in VideoJS is very clearly commented. I don't know how much work it is to make the control/menu behaviour a parameter that can be set in the player config. That would enable either setting and keep both parties happy but it's just a thought.

Thanks for the answer again.
