### ISSUE TITLE
Cancel icon

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#3397]
Can anyone tell me where and what the Cancel icon used in the style vjs-close-button is used for? It is referenced as `cancel: '\f115'` in _icons.scss in the node_modules directory. This is the only used icon I can't find in the player so I'm assuming it only appears under certain circumstances.

**Comment by gkatsev** [comment]
The cancel icon is used for the close button on the modal dialog.

**Comment by edwinbradford** [comment]
Thanks -- that's really helpful. I'll try to locate it tomorrow. Should be possible to force it to appear now I know where to look.

**Comment by gkatsev** [comment]
You can see it by doing `player.createModal('foo')` which creates a temporary modal dialog for you.

**Comment by edwinbradford** [comment]
That's going to save me a lot of time. Thanks very much.

**Comment by gkatsev** [comment]
No problem. What are you trying to do with the cancel icon/button?

**Comment by edwinbradford** [comment]
I've been working on a new theme for my portfolio site although it turned
out to be a lot more work than I thought. It's forked from the main project
under the name videojsneue. I've replaced the font icons with svgs and the
cancel icon was the only icon I couldn't find but sass complained when I
tried to remove it. Your feedback has saved me a lot of head scratching --
thanks.


+ + + + + + + + + + + + + + + + +

Email: edwinbradford@gmail.com

Tel.: +44 7981 873 771

+ + + + + + + + + + + + + + + + +

2016-06-27 20:04 GMT+01:00 Gary Katsevman <notifications@github.com>:

**Comment by gkatsev** [comment]
Cool! Good luck.

**Comment by edwinbradford** [comment]
You're welcome to check it out. I take it you can find it from the forked
projects. I only made it for myself and I can only vouch for it on Chrome
at the moment but hopefully I haven't hacked it to death.


+ + + + + + + + + + + + + + + + +

Email: edwinbradford@gmail.com

Tel.: +44 7981 873 771

+ + + + + + + + + + + + + + + + +

2016-06-27 20:13 GMT+01:00 Gary Katsevman <notifications@github.com>:
