### ISSUE TITLE
My player messed up when i using resolution switcher

### ISSUE THREAD

**Issue by truongdatnhan** [videojs/video.js#3398]
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.I Included the it in the heder.php (Don't know if i'm adding it in the right way i just know basic css like to make simple thing like margin,etc...)
```
<head>
<link href="http://127.0.0.1/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/5.10.4/video.js"></script>
<script src="http://127.0.0.1/videojs-resolution-switcher.js"></script>
<script src="http://127.0.0.1/videojs-resolution-switcher.css"></script>
<meta charset="<?php bloginfo( 'charset' ); ?>" />....
</head>
```
2.Use the code given from video-resolution switcher [with my video]
```
<video id="video" class="video-js" width="1000" height="500" controls preload="auto" poster="https://i.ytimg.com/vi/MmeAPpEoGAI/maxresdefault.jpg" controls data-setup='{}'>
   <source src="https://lh3.googleusercontent.com/vvT0ZbARuW8E17sX9MbpbFJ81fe_p_TlzSPSWwn3bVVXzPeN6bMsW3h0YsUaAsoxyw5dGkKAHBw=m18" type='video/mp4' label='360p' />
   <source src="https://lh3.googleusercontent.com/vvT0ZbARuW8E17sX9MbpbFJ81fe_p_TlzSPSWwn3bVVXzPeN6bMsW3h0YsUaAsoxyw5dGkKAHBw=m22" type='video/mp4' label='720p'/>
   <source src="https://lh3.googleusercontent.com/vvT0ZbARuW8E17sX9MbpbFJ81fe_p_TlzSPSWwn3bVVXzPeN6bMsW3h0YsUaAsoxyw5dGkKAHBw=m37" type='video/mp4' label='1080p'/>
</video>
<script>

  videojs('video').videoJsResolutionSwitcher()
</script>
```
3.my player messed up when i play with this code but when i play with the code from demo it fine nothing messed up but no resolution option

### Expected
I MUST see the option resolution like in the demo

### Actual
My Player messed up when i play it. This is it
http://i.stack.imgur.com/qVaYv.jpg
http://i.stack.imgur.com/vouqa.png

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.10.4
### plugins
Video Resolution Switcher [newest version]

**Comment by gkatsev** [comment]
Do you have a reduced test case? Only thing I can think off is that your page styles or the videojs resolution styles are somehow messing up with videojs styles.

**Comment by truongdatnhan** [comment]
i don't think videojs resolution style is a problem. i tried to add resolution to syle to videojs.css and the player still mess up.
Inside of video resolution style it only have wordpress css for the resolution option.

**Comment by mmcc** [comment]
Sorry, without actually being able to dig into the page itself, there's not much we can do. Screenshots unfortunately aren't very helpful for diagnosing. I'm going to close this issue, but if you post a link to the page someone might be able to take a look and dig in. For what it's worth, I think this question is probably a better fit for a more general forum such as [StackOverflow](http://www.stackoverflow.com).
