### ISSUE TITLE
Second player starting playback causes another, paused player to begin playing

### ISSUE THREAD

**Issue by Fenrirthviti** [videojs/video.js#3399]
## Description
Having an issue with video.js and a window popout script. I have two video.js players. One is in the main site, and one is loaded in a new window when a button is clicked and invokes a JS popout script. The script pauses the player in the main window, but as soon as the new player loads, the old player begins playing again as well. They both have different IDs, and this only occurs with the autoplay flag set.

## Steps to reproduce
1. Create video player (with autoplay) on a page with a button that invokes a script for a popout window that also pauses the player, and a second page called as the popout window (see gist for code examples)
2. Wait for the video to start playing, click the button to popout the window and pause the player. Player in the main window stops playing.
3. As soon as the video in the new window loads and begins player, the player in the old window starts playing again as well.

Gist code snippets: https://gist.github.com/Fenrirthviti/69a6d05fe0ed0422ffa8ed91fbae7170

### Expected
Expect the player in the old window to stay paused.

### Actual
Player in old window resumes when new player starts

### Error output
No errors.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Tested on Video.js 5.7.1
#### browsers
Chrome, Firefox, Internet Explorer 11, Edge (all latest releases)
#### OSes
Tested on Windows.
### plugins
https://github.com/kmoskwiak/videojs-resolution-switcher (tested without, same issue occurs)

**Comment by gkatsev** [comment]
Would you be able to put up a live [reduced test case](https://css-tricks.com/reduced-test-cases/) for this? It'll make it easier to see what is going on exactly.

**Comment by Fenrirthviti** [comment]
Unfortunately not, I don't have the time to build one out. My full code can be found in my stream-site repo.

I can provide access to my dev site if that would help, but I won't be able to build out a live test case for some time.

**Comment by Fenrirthviti** [comment]
Please close this. I discovered the issue was a conflicting .js that was reloading the page on certain functions. Not video.js related.

**Comment by gkatsev** [comment]
Thanks for getting back to us. Glad you figured it out.
