### ISSUE TITLE
the video.js run in my android dev has a problem

### ISSUE THREAD

**Issue by zhangwei900808** [videojs/video.js#3402]
you can see it
![Uploading QQ截图20160628101112.png…]()

**Comment by gkatsev** [comment]
Please follow the [Issue Template](https://github.com/videojs/video.js/blob/master/ISSUE_TEMPLATE.md) when opening an issues. It allows us to more easily understand the problem and try to help you.

**Comment by zhangwei900808** [comment]
sorry my shotscreen cant upload please waiting for me

**Comment by zhangwei900808** [comment]
![dd](https://cloud.githubusercontent.com/assets/4385154/16401740/6bdd2bca-3d19-11e6-96e7-f4767742c089.png)

**Comment by zhangwei900808** [comment]
you can see it ,but my pc is not this problem,you can see it
![image](https://cloud.githubusercontent.com/assets/4385154/16401807/fd79df88-3d19-11e6-996d-cf15f8d90bab.png)
