### ISSUE TITLE
stuck when there is 302 redirect

### ISSUE THREAD

**Issue by yuchengzhen** [videojs/video.js#3408]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. there is an redirect url _url_1 in website  _website_1, which redirect to an url _url_2 in website _websit_2
2. _url_2 is a http flv live stream
3.use vedio.js to play _url_1 in firefox, chrome

### Expected
the vedio can play as it is

### Actual
the vedio stuck a lot when playing

### Error output
no error, just stuck

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
newest
#### browsers
firefox chrome
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
flash

**Comment by gkatsev** [comment]
It's currently a known issue with our plugin. See https://github.com/videojs/videojs-contrib-hls/issues/548. There may be a way to get it working in newer browsers but not in all browsers.
Also, please direct contrib-hls issues at that project first.
Thanks.
