### ISSUE TITLE
No sound for video using mp3 codec in HLS Live stream

### ISSUE THREAD

**Issue by egick666** [videojs/video.js#3409]
## Description
I've tried to play **Live** HLS stream with **mp3** audio track onboard using source code of videojs from 9f37a641 commit and CDN-hosted videojs-contrib-hls plugin.

## Steps to reproduce
1. Use any HLS live stream with mp3 audio and CORS headers enabled.
2. Run "grunt dev" target from videojs directory
3. Play stream from sandbox page

### Expected
There is a sound played in live video stream.

### Actual
There is no sound but only video.

#### videojs
v.5.10.7
#### browsers
Chrome 51.0.2704.103 m and Firefox 47.0 were checked and confirm issue
#### OSes
Windows 8.1 64 bits
### plugins
CDN-hosted videojs-contrib-hls plugin from

https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.1.0/videojs-contrib-hls.js

**Comment by gkatsev** [comment]
We do not currently support mp3 audio for HLS streams. See https://github.com/videojs/videojs-contrib-hls/issues/209.
Also, please open contrib-hls related issues on that project, in the future.
Thanks.
