### ISSUE TITLE
Progress bar goes back to previous position while movie goes forward

### ISSUE THREAD

**Issue by esteban-dosztal** [videojs/video.js#3418]
There is a bug happening on the progress bar, in IE11 and Edge on Windows 10. Given some VOD content, as it goes on, the progress bar comes back to position 0 at some random time. I researched the code that sets the progress bar width, and I've got these results:

I'm using VideoJS v 5.10.4 with HLS.js, and the plugin at https://github.com/benjipott/videojs-hlsjs. I cannot use videojs-contrib-hls because of a custom stream switcher I wrote that doesn't plays well with it.

In the function Slider.prototype.update, we get the current progress of the playback from SeekBar.prototype.getPercent:

    var progress = this.getPercent();

Then, we convert it to a string with onlt two decimal places:

    var percentage = (progress * 100).toFixed(2) + '%';

And then, we use percentage to set:

    bar.el().style.width = percentage;

I console.log percentage to see it's value when the error happens, and it happens to be 0.38, but it's value from the previous loop was 10.33. I guess it could be the case that, inside of SeekBar.prototype.getPercent, the line this.player_.currentTime() / this.player_.duration() is doing some weird roundind.

I cannot make a reduced test case, because I don't have a free HLS content with length > 30 minutes. I have debugged the SeekBar.prototype.getPercent in order to know where this.player_.currentTime() and this.player_.duration() get the values from, and it seems it is from the <video> element. So, it doesn't seems to depend on HLS, neither on the plugin.

Hope the description of the problem is good enough and useful.

**Comment by gkatsev** [comment]
Is the `currentTime` and `duration` correct during both iterations? My first instinct would be that either `videojs-hlsjs` or the video element itself is lying to us and causing issues.
I know what in contrib-hls we've ended up going Flash-only for HLS because the MSE implementations was causing too many issues and they were inconsistent enough that we couldn't really build work-arounds. I wonder if this is related to those weird inconsistencies.

**Comment by esteban-dosztal** [comment]
@gkatsev You're right. I've debugged this on Chrome on Windows, and I've got the same error. currentTime is 0, and it's value is taken from the <video> element. So, I'm about to close this issue.

Thanks.

**Comment by gkatsev** [comment]
Cool. You might want to open this issue against videojs-hlsjs or even hlsjs itself. It's potentially an issue there, though, possibly just an MSE bug.
