### ISSUE TITLE
Playlists?

### ISSUE THREAD

**Issue by Jzarecta** [videojs/video.js#3420]
Does this player support playlists, or if I want to play multiple videos I need to use this in combination with something else?

**Comment by misteroneill** [comment]
We at Brightcove have a open source [playlist plugin](https://github.com/brightcove/videojs-playlist) available as well as a [playlist-ui plugin](https://github.com/brightcove/videojs-playlist-ui) (if you don't want to build your own UI on top of the playlist plugin).

**Comment by misteroneill** [comment]
Also, there are [a bunch of other plugins](http://videojs.com/plugins/) available.
