### ISSUE TITLE
small video plays in container unless fullscreen-ed when using flash

### ISSUE THREAD

**Issue by lalberto0309** [videojs/video.js#3422]
## Description

I posted this on SO but I got no bites so hopefully I can get some help here:
http://stackoverflow.com/questions/38102550/streaming-video-gets-stuck-in-upper-left-corner

I'm currently trying to use an rtmp stream using video.js. When i press play, another play button appears and a small video in the top left corner of my video container shows up. I can play this video, but it stays small. When I fullscreen the video and exit fullscreen, the video resizes back to the correct size of the container. Is there a way to force this to fit the video without having to fullscreen?

Here's a picture of the issue. Note this is after pressing play initially 
![videojs_issue](https://cloud.githubusercontent.com/assets/18368768/16704519/f32dcdee-4545-11e6-893e-b9a4a3037802.png)

code for setting up the player

```
                d3.select('#myVideoDiv')
                    .append('video')
                        .attr('id', 'mystream')
                        .attr('class', 'video-js vjs-default-skin vjs-big-play-centered')
                        .attr('height', 250)
                        .attr('width', 280)
                        .append('source')
                            .attr('src', myVidObj.url)
                            .attr('type','rtmp/mp4');
                videojs("mystream", { controls: true });
```
### Expected

Video should play after hitting play once and should fill whole container
### Actual

Video shows another play button and video stream is small in the top left corner of 280x250 container
## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs

Using version 5.10.4
#### browsers

Chrome,FF

**Comment by nickygerritsen** [comment]
The extra play button is because your <video> element is not 4:3 or 16:9 so Chrome blocks Flash by default.

The fact that it plays in a small window is not related to this; we encountered the same and I haven't found the issue in code yet.

**Comment by lalberto0309** [comment]
ok ill try setting the aspect ratio then ty. What's going on with the small window though? This only seems to happen with Flash/rtmp, the same container loading up the example oceans video which is html5 i believe doesnt have this problem..

**Comment by nickygerritsen** [comment]
It indeed only happens in RTMP, so it's probably some error in the flash component

**Comment by lalberto0309** [comment]
I'm still getting a second play button here, I edited the above code so the height is now 210 and the width is 280 (giving a 4:3 ratio) and added a player.aspectRatio('4:3') after initializing the videojs element...

**Comment by risingratul** [comment]
Having the same issue... anyone can help with this?

**Comment by mister-ben** [comment]
I think it's the size rather than aspect ratio that triggers Chrome's click to play. IIRC 400x300 is ok.

The scaling is an [old issue on the Flash tech](https://github.com/videojs/video-js-swf/issues/55) with multiple causes and so hasn't had a single solution.

**Comment by gkatsev** [comment]
I don't think there's much we can do about this. You need to make sure that your element is large enough, also, if you have too many elements in front of it, browsers may determine it isn't important enough to run the swf.
