### ISSUE TITLE
Flash set to "Ask to activate" makes video invisible

### ISSUE THREAD

**Issue by arni2033** [videojs/video.js#3423]
### Description
Flash overlays appear above the video and don't respond to click if Flash is set to "Ask to activate"
Testcases:
http://www.dorkly.com/video/79494/5-gamebreaking-bugs-that-ruined-our-trust
http://macs.about.com/od/usingyourmac/qt/Os-X-Lion-Scroll-Bars.htm

### Steps to reproduce
1. Set Flash to "Ask to activate" or install obsolete version of Flash
2. Open one of 2 urls above, scroll that page to the video
3. Click on the gray area that appears over the video

### Expected Result
Either X or Y
X) Video should be visible after Step 2
Y) Video should be covered by Flash overlays, but after Step 3 browser should ask confirmation for Flash, and after user allows Flash, the video should become visible

### Actual Result
After Step 2 Flash overlays appear above the video and don't respond to click

### Additional Information
Firefox:   Win7_64, Nightly 49, 32bit, ID 20160526082509
GoogleChrome:   Win7_64, Chrome 49.0.2623.112 m
![2016 07 10 18-40-13](https://cloud.githubusercontent.com/assets/9205283/16715613/deba4c26-46ed-11e6-86c9-47851b03219c.png)

**Comment by gkatsev** [comment]
Looks like this isn't an issue with videojs itself but rather the ad integration.
I've pinged the team about it. Closing in the meanwhile since it isn't directly relating to videojs itself.
