### ISSUE TITLE
error - not supported or 404 ?

### ISSUE THREAD

**Issue by IamFake** [videojs/video.js#3424]
Hi.

Is there a way to know that request for video file returns http 404? I want use this for "video converting, please wait" feature (e.g. if 404 then do subrequest to queue server)? Thx.

**Comment by gkatsev** [comment]
You probably want to [listen](http://docs.videojs.com/docs/api/player.html#Methodson) to the [`error` event](http://docs.videojs.com/docs/api/player.html#Eventserror).
In the handler, you'll want to call [`player.error()`](http://docs.videojs.com/docs/api/player.html#Methodserror) to get the current MediaError and then you'll probably want to make sure that the MediaError's `code` is [2 for Network Error](http://docs.videojs.com/docs/api/player.html#Methodserror).
You can hide the default error dialog by calling `player.error(null)`. And then display your own message.

Hope that helps.
