### ISSUE TITLE
showTextTrack in Video.js 5

### ISSUE THREAD

**Issue by bolt088** [videojs/video.js#3427]
Hi,

I am trying to change the active caption track from JavaScript in Video.js v5.10.4. I saw a few posts about this and they all suggested to use `showTextTrack`, but when I execute the command it says that `showTextTrack is not a function`. I currently have the following code:

`var video = videojs('video', { html5:{ nativeTextTracks: false }});`
`var first_track_id = video.textTracks()[0].id;`
`video.showTextTrack(first_track_id, "captions");`

The first and the second line work fine, the second line returns `vjs_track_399`, but the third line shows that showTextTrack is not a function. Also all other functions like: `addRemoteTextTrack, addTextTrack, textTracks` are working fine.

What is the correct way to accomplish this?

**Comment by bolt088** [comment]
I just figured out that I should actually use 

`video.textTracks()[0].mode = 'showing';`

**Comment by gkatsev** [comment]
Glad you figured it out. Also, I also wanted to mention that there's some documentation around text tracks here: https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md
