### ISSUE TITLE
.mp4 Not Playing In Firefox Even With Flash Fallback

### ISSUE THREAD

**Issue by neilchaudhuri** [videojs/video.js#343]
I have configured Video.js to display .mp4 videos very well with Chrome and Safari, but I am having issues with Firefox. Here is the HTML:

<video id="video_3_html5_api" class="vjs-tech" preload="auto" 
data-setup="{'techOrder': ['html5', 'flash']}" 
src="https://s3.amazonaws.com:443/my-bucket/myVideo.mp4">
</video>

Note 1) the absolute URL to the video 2) the Flash fallback configured in data-setup. These are things I've seen in similar posts, but adding these hasn't helped.

I am testing on a Mac with v.18.0.2 of Firefox and the latest Flash install.

Any insight on the matter is appreciated.

Thanks.

**Comment by redbar0n** [comment]
This might detail the problem and the solution:
http://magnemg.tumblr.com/post/113251336220/how-to-solve-a-capybara-webkit-and-video-js

If it is the same problem, then it's an issue with the Webkit implementation that Qt 4 uses on OSX. The solution is to upgrade to Qt 5 which uses a newer version that doesn't throw TypeError's when trying to play MP4 videos. See the blog post for more details.
