### ISSUE TITLE
Please update the npm package version

### ISSUE THREAD

**Issue by yleo77** [videojs/video.js#3432]
Please update the npm package version.

Current it’s 5.10.4, and this version has a bug that related to #3305 ( Option `nativeControlsForTouch` not work as expected )

I saw source code and package.json is fixed and updated, but npm package is not updated.

:)

**Comment by gkatsev** [comment]
5.10.7 *is* available on npm.
```sh
$ npm dist-tag ls video.js
latest: 5.10.4
next: 5.10.7
```
However, it definitely needs to be promoted to `latest`.
Also, the PR that fixes #3305 hasn't been merged in yet. I'm going to try and get a new release of videojs out this week, including promoting 5.10.7 to `latest` and merging some of the outstanding PRs that are good to go.

**Comment by gkatsev** [comment]
#3305 is being merged now, will be out soon.
