### ISSUE TITLE
Wowza mediacache

### ISSUE THREAD

**Issue by voltan** [videojs/video.js#3434]
Hello
Can video js play wowza mediacache source? like this : 
```
http://[wowza-ip]:1935/mediacache/_definst_/mp4:http/myfolder/myfile.mp4/manifest.mpd
````

this type support on jwplayer

**Comment by nickygerritsen** [comment]
Looking at the URL's described at https://www.wowza.com/forums/content.php?121-How-to-scale-video-on-demand-streaming-with-Media-Cache#mediacacheconf_playback Wowza offers multiple output formats.

You can use the following with video.js:

* RTMP using the Flash tech. So only on Flash enabled browsers
* Apple HTTP Live Streaming natively on iOS devices, macOS and Microsoft Edge and on browsers supporting either Flash (but not IE8/IE9) or Media Source Extensions using [https://github.com/videojs/videojs-contrib-hls](videojs-contrib-hls)
* MPEG-DASH on browsers supporting Media Source Extensions using [https://github.com/videojs/videojs-contrib-dash](videojs-contrib-dash)

I hope this helps!
