### ISSUE TITLE
how to set the video width and height to adapt to the mobile device screen

### ISSUE THREAD

**Issue by lovearthhome** [videojs/video.js#3435]

**Comment by AleksP** [comment]
My simple solution

        $(document).ready(function($) {
            videojs('video', {height: 'auto', width: 'auto'}).ready(function() {

                var player = this,
                    aspectRatio = 9/16;

                function resizeVideoJS() {
                    var width = document.getElementById(player.id()).parentElement.clientWidth;
                    player.width(width).height(width * aspectRatio);
                }

                resizeVideoJS();
                window.onresize = resizeVideoJS;
            });
        });

**Comment by misteroneill** [comment]
When creating your player, you can pass the `fluid: true` option:

```js
var myPlayer = videojs('my-video', {fluid: true});
```

Or you can set it after initialization at some point:

```js
myPlayer.fluid(true);
```
