### ISSUE TITLE
Dynamically load source and at given start time (Firefox/ie)

### ISSUE THREAD

**Issue by mikeRead** [videojs/video.js#3437]
I'm making a custom bitrate menu. When the viewer clicks a button it will run something like this

```javascript 
var currentTime = player.currentTime();
player.src({ type:"video/mp4", src: "//url.com/video.mp4" });
player.currentTime(currentTime);
```

This works fine in safari and chrome but seems to not work for IE and firefox (video plays at 0:00). I saw a few other people say setting the current Time after video is loaded, however, I can't because ill be adding a new listener every time someone click that button Ill end up with multiple event listeners.

Is there any other way to start a video at a certain  time on IE and firefox

Thanks

**Comment by nickygerritsen** [comment]
Couldn't you use `player.one('load', ...);`?

So that it's only called once. That is what we are doing roughly

**Comment by gkatsev** [comment]
You should be able to either use `player.one` or just remove previous handlers before adding in a new one with `player.off`
