### ISSUE TITLE
currenttime update before Seeking & Seeked fired

### ISSUE THREAD

**Issue by pankajanupam** [videojs/video.js#3446]
## Description
currenttime update before Seeking & Seeked fired. Ideally currentTime time should update after seeked fire.

## Steps to reproduce

vlayerObj.on('timeupdate', function () {
      console.log( 'timeupdate  -  current time', vlayerObj.currentTime() ); // first this fire and time value will be 150s, after seeking it's fire again and time value will be 150s
});

vlayerObj.on('seeking', function () {
      console.log( 'seeking  -  current time', vlayerObj.currentTime() ); // first this fire and time value will be 150s
});

vlayerObj.on('seeked', function () {
      console.log( 'seeked  -  current time', vlayerObj.currentTime() ); // at last this fire and time value will be 150s
});

Suppose video at 20s when we seeked to 150s above three event are fired.

Ideally currentTime time should update after seeked fire but it's update as soon as I click so there is no way to check if time update due to seeking or to know seeking start time.

Ideally currentTime time should update after seeked fire.

**Comment by gkatsev** [comment]
Unfortunately, that isn't really something that videojs handles but rather the browsers themselves.
Here's the output in chrome using the native video element on this live example: http://jsbin.com/jobeneyuja/edit?html,js,console,output:
```
"seeking"
12.253769
"timeupdate"
12.253769
"seeked"
12.253769
```
