### ISSUE TITLE
Is it possible to work as an audio player?

### ISSUE THREAD

**Issue by zh-wowtv** [videojs/video.js#3448]
I'm wondering if it's possible to play mp3 as an audio player? Thanks.

**Comment by mmcc** [comment]
Yep! Just use an [`<audio>` tag](http://blog.videojs.com/Video-js-4-9-Now-can-join-the-party/).

**Comment by zh-wowtv** [comment]
@mmcc Awesome! Does it support lyrics?

**Comment by gkatsev** [comment]
audio elements don't have an area for captions but you can use a video element with an mp3 just fine and then you can provide the lyrics as a caption or subtitles track.
