### ISSUE TITLE
Confusions about event handlers in "player.js"

### ISSUE THREAD

**Issue by elfo4bj** [videojs/video.js#3456]
## Description
   I am using videojs as a framework to develop some extra functionality in my project. I'd like to say that the design of videojs is just elegant, very easy to extend. However, I came across a problem in the source file "player.js". What are those event handlers by the end of "player.js" file for? I have never found their declarations or implementations ! Can someone explain it? Thanks a lot in advance.

Event handlers examples by the end of "player.js" file:
`Player.prototype.handleLoadedMetaData_;`
`Player.prototype.handleTextData_;`
`Player.prototype.handleLoadedData_;`
`Player.prototype.handleUserInactive_;`
`Player.prototype.handleTimeUpdate_;`

**Comment by misteroneill** [comment]
@elfo4bj There should probably be a comment there explaining that, but - and another core contributor can correct me if I'm wrong! - those seem to be there for documentation purposes.

The actual methods included in the `class` definition are `@private` from JSDoc's perspective, but we want to document the events which trigger on the player. JSDoc likely needed some code to recognize as related to a documentation block (`/** ... */`) and those no-op references to the method(s) worked. This can probably be improved, but you can safely ignore that for all intents and purposes!

In general, when working with events on a video.js player, you'll want to focus on the [standard HTML5 media events](https://www.w3.org/TR/html5/embedded-content-0.html#mediaevents).

**Comment by gkatsev** [comment]
Yup, these are purely for documentation purposes, as @misteroneill says.
