### ISSUE TITLE
Video stops and wont play again

### ISSUE THREAD

**Issue by sriman** [videojs/video.js#3466]
[##](`url`) Description
On switching to fullscreen and back in the videojs player makes the hls video stop and it doesnt play again(screen recorded and attached)

<img width="1280" alt="screen shot 2016-07-27 at 12 55 32 am" src="https://cloud.githubusercontent.com/assets/2287197/17152356/0601bfe0-5395-11e6-946a-3774241bb2cc.png">

## Steps to reproduce
1. play the video
2. click fullscreen and video will be played in fullscreen
3. click escape player switches back to original size from fullscreen
4. continue this for 4 or 5 times
5. we can see video stops and wont play again automatically
6. recreated the issue in the attached video

### Expected
Video should start playing even after continuous change of fullscreen and normal mode.

### Actual
Video stops and wont play again

[fullscreenissue.mp4.zip](https://github.com/videojs/video.js/files/384595/fullscreenissue.mp4.zip)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
5.10
#### browsers
what browser are affected? Chrome 51.0
#### OSes
Mac OS Capitan 10.11.3

**Comment by sriman** [comment]
Can you guys fix this issue, we are facing the issue in our website everyday, about 25% of users are affected by this issue.

**Comment by gkatsev** [comment]
The discussion is taking place in https://github.com/videojs/videojs-contrib-hls/issues/798
