### ISSUE TITLE
Disable big button

### ISSUE THREAD

**Issue by anacrolix** [videojs/video.js#3471]
I don't want the "big button", as it requires the user to start playing the button locally before a Chromecast plugin's cast button is revealed. How do I disable this button and go straight to the controls?

**Comment by mister-ben** [comment]
You can use a combination of `"bigPlayButton": false` in your setup options to hide the button and `.vjs-paused .vjs-control-bar { display: flex; }` in CSS to show the control bar.

**Comment by anacrolix** [comment]
The first still requires that the user click the video and start it before the controls appear. The second has no noticeable effect.

**Comment by mister-ben** [comment]
Disabling the button alone doesn't reveal the controls, hence the CSS. Here's an example: http://jsbin.com/zamizuc/edit?html,output

**Comment by anacrolix** [comment]
I had to put !important on the CSS you gave. I suspect because in your example you had it in an internal stylesheet, and I was putting it in an external stylesheet. Thanks for the help. Perhaps you could include this in the documentation somewhere, or add an option "alwaysShowControls" or something.
