### ISSUE TITLE
The correct way to add a button with video js 5

### ISSUE THREAD

**Issue by sobytes** [videojs/video.js#3473]
Hi All,

I am looking for the correct way to add a button to the control bar using the new video js 5 methods there seems to be a lot of conflicting advice out there so thought i would ask here to get a definite answer.

Currently i am using add child which i see is now depreciated.

~~~
videoPlayer.controlBar.addChild('button', {
    text: "Back",
    tabIndex: 3
}).addClass("button-back");
$(".button-back").html("<a href='#' target='_blank'><i class='fa fa-undo'></i></a>");
~~~

Also tabIndex never seem to work they always seem to end up before the fullscreen button can someone please advise me on the correct way to do this.

Thanks

**Comment by sobytes** [comment]
This works for me.

~~~
function addNewButton(data) {

    var myPlayer = data.player,
        controlBar,
        newElement = document.createElement('div'),
        newLink = document.createElement('a');

    newElement.id = data.id;
    newElement.className = 'downloadStyle vjs-control';

    newLink.innerHTML = "<i class='fa " + data.icon + " line-height' aria-hidden='true'></i>";
    newElement.appendChild(newLink);
    controlBar = document.getElementsByClassName('vjs-control-bar')[0];
    insertBeforeNode = document.getElementsByClassName('vjs-fullscreen-control')[0];
    controlBar.insertBefore(newElement, insertBeforeNode);

    return newElement;

}

var btna = addNewButton({
    player: videoPlayer,
    icon: "fa-download",
    id: "downloadButton"
});
btna.onclick = function() {
    alert("download");
};

var btnb = addNewButton({
    player: videoPlayer,
    icon: "fa-twitter",
    id: "downloadButton"
});
btnb.onclick = function() {
    alert("twitter");
};
~~~

**Comment by gkatsev** [comment]
That method works just fine. If you want to create a videojs component button, you can ["extend"](https://github.com/videojs/video.js/wiki/5.0-Change-Details#videojs-50-subclassing-examples) one of the built-in components. For example:
```js
var Button = videojs.getComponent('Button');
var MyButton = videojs.extend(Button, {
  constructor: function() {
    Button.apply(this, arguments);
    /* initialize your button */
  },
  handleClick: function() {
    /* do something on click */
  }
});
videojs.registerComponent('MyButton', MyButton);
var player = videojs('myvideo');
player.getChild('controlBar').addChild('myButton', {});
```
Hope that helps.

**Comment by douglas-lee** [comment]
gkatsev, your code is working, but how to setup a icon for the button?

**Comment by eseffair** [comment]
i am in the same point, the code work, but how to setup a icon for the button?

**Comment by hartman** [comment]
video.js uses an icon font for player icons. If you are adding your own buttons, you probably need to roll your own icon font.

**Comment by tonykor** [comment]
@gkatsev @hartman Not clear for me as well how to add icon and text to button. Tried to read the API docs http://docs.videojs.com/docs/api/button.html but it's not completed. Please post a use case, @gkatsev example nither create a button, but just an empty space is control bar. Thanks.

**Comment by onigetoc** [comment]
Yeah, we never find a complet solution with button icon

**Comment by Adynnor** [comment]
@onigetoc using gkatsev's example just add the class in the constructor
So for example if I was using font awesome for icons and I wanted to use fa-bars I would add it like so

`constructor: function() {
    Button.apply(this, arguments);
    this.addClass( 'fa-bars' );
},`

**Comment by onigetoc** [comment]
Ok, i may use the videojs icon fonts
http://videojs.github.io/font/
or using css fontface way like the button in the videojs css.
https://vjs.zencdn.net/5.16.0/video-js.css
But i do not plan to load all the FA library for just 2 or 3 mores buttons.
I have a example on [Codepen](http://codepen.io/onigetoc/pen/wJRyvZ)

**Comment by tonykor** [comment]
Hello all,

I'm currently using this to add custom button with icon to control bar:
```
var VjsButton = videojs.getComponent("Button");
var customButton = videojs.extend(VjsButton, {
           constructor: function(player, options){
            VjsButton.call(this, player, options);
                this.controlText("Some text");
           },
           handleClick: function() {
            //do something on click for example
            window.open("http://www.someurl.com");
           },
           buildCSSClass: function() {
            return "vjs-icon-custombutton vjs-control vjs-button";
           }
        });
        videojs.registerComponent("customButton", customButton);
        player.getChild("controlBar").addChild("customButton", {});
```
I have regenerate videojs fonts adding new icon vjs-icon-custombutton,  like it was described here https://github.com/videojs/font . My video-js.css had class 
```
.vjs-icon-custombutton {
  font-family: VideoJS;
  font-weight: normal;
  font-style: normal; }
  .vjs-icon-custombutton:before {
    content: "\f11f"; }
```
Hope this helps

**Comment by onigetoc** [comment]
@tonykor Thank you,
I'm almost there.
http://codepen.io/onigetoc/pen/wJRyvZ

Testing a existing icon, but i want my own NEXT and Previous button but do not want to load a big css icon font library.
I just see that there's no NEXT and PREVIOUS button on the videojs icon fonts. 
May be with fontface or custom font on http://fontello.com/

**Comment by onigetoc** [comment]
@tonykor Do i have to do it all over again for another button like my Next button to add a Previous button?
I.E a Previous and Next buttons.

**Comment by tonykor** [comment]
You can add next and previous buttons from Google's material icons 

https://material.io/icons/#ic_skip_next
https://material.io/icons/#ic_skip_previous

In order to use them you need to edit icons.json file in this pakage 

https://github.com/videojs/font

By adding something like (depending of where is icons svg's are located)
```
{
    "name": "skip_next",
    "svg": "av/svg/production/ic_skip_next_48px.svg"
},
{
    "name": "skip_previous",
    "svg": "av/svg/production/ic_skip_previous_48px.svg"
}
```
after running `grunt` replace videoJs fonts files, and find generated css for your icons which you need to add to your video-js.css

**Comment by tonykor** [comment]
@onigetoc yes you need to make this for each unique button, as each button will have different actions, icons, etc.

**Comment by onigetoc** [comment]
My website already use material icons but i use the icon font way from Material icon CDN.
`<i class="material-icons">skip_next</i>`

But Material design use a single way to add font icon, With their class and text. 
But it can be done. 
Adding class and text.

For testing i did it with Font Awesome for now and it work. (but i think i will use fontello with a custom build, i will create 4-5 icons font i will eventually use)
http://codepen.io/onigetoc/pen/wJRyvZ

**Comment by onigetoc** [comment]
If it's well done, it may will be a futur plugin for the videojs playlist if i get some help.

TO DO.
- Show/hide Next previous button if there's a playlist or not
- Work with multiples players.
- add opacity if there's no next or previous videos.

**Comment by Adynnor** [comment]
@onigetoc 
for your third one, you could just hide it with
```javascript
this.addClass( 'vjs-disabled' );
```

**Comment by onigetoc** [comment]
@Adynnor ok but i think we need more complicated stuff, checking if there's previous or next video, and hide the two button if there's no playlist, (I should read more the playlist api :)

**Comment by Adynnor** [comment]
@onigetoc Yeah it was just a pointer not the logic :)

**Comment by onigetoc** [comment]
Previous and Next buttons done.
http://codepen.io/onigetoc/pen/wJRyvZ

**Comment by Kadajett** [comment]
@onigetoc Why do you have a click event listener and a handleClick function? They are redundant, correct? 
I can't seem to get the handleClick function to work, so I am curious why you have both.

**Comment by jaceluoath** [comment]
The event listener is for the button under the video player whereas the handleclick is for the video player control bar

**Comment by aritouni** [comment]
hello if this can help for font awesome just insert two classes like this to @gkatsev exemple 👍 

var Button = videojs.getComponent('Button');
var MyButton = videojs.extend(Button, {
  constructor: function() {
    Button.apply(this, arguments);
    /* initialize your button */
this.addClass( 'fa' );
this.addClass( 'fa-toggle-off' );
  },
  handleClick: function() {
    /* do something on click */
  }
});
videojs.registerComponent('MyButton', MyButton);
var player = videojs('myvideo');
player.getChild('controlBar').addChild('myButton', {});

**Comment by hidnarola** [comment]
### **Below code is working for me. please check screenshot also. I have added a custom button in the video.js player.**

var vjsButtonComponent = videojs.getComponent('Button');
            videojs.registerComponent('DownloadButton', videojs.extend(vjsButtonComponent, {
                constructor: function () {
                    vjsButtonComponent.apply(this, arguments);
                },
                handleClick: function () {
                    alert('Logic will be added here');
                },
                buildCSSClass: function () {
                    return 'vjs-control vjs-button vjs-icon-subtitles addNoteButton';
                },
                createControlTextEl: function (button) {
                    return $(button).html($('<i class="fa fa-download"></i>').attr('title', 'Add Note'));
                }
            }));
            var player = videojs('video', {
                playbackRates: [0.5, 1, 1.5, 2, 4]
            });
            player.getChild('controlBar').addChild('DownloadButton');``

**Comment by liwuwuzhi** [comment]
@tonykor i create a button with your demo, also just an empty space is control bar, how to fix it?

**Comment by 690797590** [comment]
i want to add some button width text innner,how to build or which methods can use?
`init() {
                let videojs = VideoPlayer.videojs;
                let Button = videojs.getComponent('Button')
                let myButton = videojs.extend(Button, {
                    constructor: function (player, options) {
                        Button.apply(this, arguments)
                        this.addClass('normal-stream')
                    },
                    handleClick: () => {
                        console.log(11111)
                    },
                    buildCSSClass: function () {
                        return 'vjs-icon-custombutton1 vjs-control vjs-button'
                    },
                })
                videojs.registerComponent('myButton', myButton)

                console.log(myButton)
                this.$nextTick(() => {
                    this.$refs.videoPlayer.player.getChild('controlBar').addChild('myButton')
                })

            },`

and how to add a menu list like the default rate list?

**Comment by Muthukumaruma** [comment]
> That method works just fine. If you want to create a videojs component button, you can ["extend"](https://github.com/videojs/video.js/wiki/5.0-Change-Details#videojs-50-subclassing-examples) one of the built-in components. For example:
> 
> ```js
> var Button = videojs.getComponent('Button');
> var MyButton = videojs.extend(Button, {
>   constructor: function() {
>     Button.apply(this, arguments);
>     /* initialize your button */
>   },
>   handleClick: function() {
>     /* do something on click */
>   }
> });
> videojs.registerComponent('MyButton', MyButton);
> var player = videojs('myvideo');
> player.getChild('controlBar').addChild('myButton', {});
> ```
> 
> Hope that helps.

How to add custom class name for this button?

**Comment by samueleastdev** [comment]
I add extra classes like this.

~~~
var Button = videojs.getComponent('Button');
var MyButton = videojs.extend(Button, {
    constructor: function() {
        Button.apply(this, arguments);
        /* initialize your button */
      	
      	this.addClass('vjs-class1');
      	this.addClass('vjs-class2-etc');
      
    },
    handleClick: function() {
        /* do something on click */
    }
});
videojs.registerComponent('MyButton', MyButton);
var player = videojs('myvideo');
player.getChild('controlBar').addChild('myButton', {});
~~~

**Comment by Muthukumaruma** [comment]
> I add extra classes like this.
> 
> ```
> var Button = videojs.getComponent('Button');
> var MyButton = videojs.extend(Button, {
>     constructor: function() {
>         Button.apply(this, arguments);
>         /* initialize your button */
>       	
>       	this.addClass('vjs-class1');
>       	this.addClass('vjs-class2-etc');
>       
>     },
>     handleClick: function() {
>         /* do something on click */
>     }
> });
> videojs.registerComponent('MyButton', MyButton);
> var player = videojs('myvideo');
> player.getChild('controlBar').addChild('myButton', {});
> ```
> 
> Then just add your extra width in css.
> 
> ```
> .vjs-class1 {
>   width: 70px;
> }
> ```

how to change the order of this button?

**Comment by VWXmeisold** [comment]
Is there anyone out there, who is able to post a simple example on how to add a button before the fullscreentoggle on the right of the control bar? It appears this topic is one of the most ignored issues.

**Comment by Jaluco** [comment]
Hello, is there a way to add buttons to the controlbar as a default?
All examples use an instance of a player.

**Comment by ndorofeeva** [comment]
> Is there anyone out there, who is able to post a simple example on how to add a button before the fullscreentoggle on the right of the control bar? It appears this topic is one of the most ignored issues.

In the code above just add a third argument to addChild:
player.getChild('controlBar').addChild('myButton', {}, **index**);

description: https://docs.videojs.com/player#addChild

**Comment by Prashu2017** [comment]
> That method works just fine. If you want to create a videojs component button, you can ["extend"](https://github.com/videojs/video.js/wiki/5.0-Change-Details#videojs-50-subclassing-examples) one of the built-in components. For example:
> 
> ```js
> var Button = videojs.getComponent('Button');
> var MyButton = videojs.extend(Button, {
>   constructor: function() {
>     Button.apply(this, arguments);
>     /* initialize your button */
>   },
>   handleClick: function() {
>     /* do something on click */
>   }
> });
> videojs.registerComponent('MyButton', MyButton);
> var player = videojs('myvideo');
> player.getChild('controlBar').addChild('myButton', {});
> ```
> 
> Hope that helps.

Thanks it help and saved me too.

**Comment by RaviJayagopal** [comment]
var player = videojs('video');

	var skipBehindButton = player.controlBar.addChild("button");
	var skipBehindButtonDom = skipBehindButton.el();
	skipBehindButtonDom.innerHTML = "30<<";
	skipBehindButton.addClass("buttonClass");
		
	skipBehindButtonDom.onclick = function(){
		skipS3MV(-30);
	}  

	var skipAheadButton = player.controlBar.addChild("button");
	var skipAheadButtonDom = skipAheadButton.el();
	skipAheadButtonDom.innerHTML = ">>30";
	skipAheadButton.addClass("buttonClass");
		
	skipAheadButtonDom.onclick = function(){
		skipS3MV(30);
	}  

	function skipS3MV(skipBy) {
		player.currentTime(player.currentTime() + skipBy);
	}

That's the exact implementation I've done for my plugin https://S3MediaVault.com .

The reason I've used text ("30<<" and ">>30") is because in my player, the colors are all customizable. So if I used an icon image for skip-back and skip-forward, then I wouldn't be able to change the color of the icon every time someone customizes the player colors (which includes the all the text in the control bar).
![s3mv skip buttons](https://user-images.githubusercontent.com/58879484/86204869-6ddf0700-bb1d-11ea-9d17-52341e2ab781.png)

**Comment by lalizita** [comment]
> ```js
> videojs.registerComponent('MyButton', MyButton);
> ```

Thank you so much! this tip help me a lot
