### ISSUE TITLE
Hope to use the same playlist style as in http://videojs.com/advanced/

### ISSUE THREAD

**Issue by fangvv** [videojs/video.js#3475]
I don't know where to find the source code for such a playlist? Thanks.

**Comment by mister-ben** [comment]
This is using https://github.com/brightcove/videojs-playlist and https://github.com/brightcove/videojs-playlist-ui.

**Comment by gkatsev** [comment]
I have a blog post about the videojs.com/advanced example: http://blog.videojs.com/Video-js-5-s-fluid-mode-and-playlist-picker/
