### ISSUE TITLE
How to insert a custom component ?

### ISSUE THREAD

**Issue by jokerrider007** [videojs/video.js#3488]
I'm try to insert custom component in videojs version 5.10.7 
I'm want to insert a element to second element but my element append to last element.
How can i insert a second element in component ?

`var test = document.createElement('div');`
`test.className = 'test';`
`player.el().insertBefore(test, player.el().firstChild.nextSibling);`

**Comment by misteroneill** [comment]
The standard DOM methods should work fine. For example, `player.el().appendChild(test)` would make `test` the last element inside the player.

**Comment by gkatsev** [comment]
Yup, you can use just standard DOM methods to insert custom elements.
However, you can also create "Button" or other videojs components and use that instead. See https://github.com/videojs/video.js/issues/3473

**Comment by nikushx** [comment]
https://nikushx.com/blog/2019/05/21/creating-custom-components-with-video-js/

Made a tutorial on doing this in a fully custom fashion. Docs aren't super helpful, so I tried to be as explicit as possible.
