### ISSUE TITLE
Rework inclusion of vtt.js

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#3491]
## Description

We currently include vttjs by concatenating it to the release file. We also allow it to be included via a url in the novtt alternative build.
With the new build system coming from #3445 we probably want to include it another way that works with bundlers properly while still maintaining the ability to produce the novtt build.

**Comment by gkatsev** [comment]
So, I think what we want to have happen that we require vttjs directly but then in the `dist` builds, specifically, the novtt builds, it should be removed to use the asynchronous loading mechanism.

**Comment by BrandonOCasey** [comment]
perhaps by using the [envify](https://github.com/hughsk/envify) and [unreachable-branch-transform](https://www.npmjs.com/package/unreachable-branch-transform) browserify transforms

**Comment by gkatsev** [comment]
Fixed.
