### ISSUE TITLE
When using youtube videos and video.js the customers will experiment youtube ads?

### ISSUE THREAD

**Issue by ricardopolo** [videojs/video.js#3507]
In some situations Youtube will play ADs in the videos we embedded with Video.js?

Thanks

**Comment by gkatsev** [comment]
That's very possible. I'm not sure there's a way to control that, it's pretty much whatever youtube wants to do. Sorry I don't have a better answer.

Also, would be better to open these issues on the [videojs-youtube repo](https://github.com/videojs/videojs-youtube), in the future.

Thanks.
