### ISSUE TITLE
Accessing window.localStorage throws SECURITY_ERR: DOM Exception 18 on Chrome when cookies are blocked

### ISSUE THREAD

**Issue by drench** [videojs/video.js#351]
I'm using Chrome 25.0.1364.99 on OS X 10.8.2 with cookies blocked (Settings -> Privacy -> Content Settings -> Cookies -> Block sites from setting any data). When in this state, just referencing window.localStorage throws an exception.

To reproduce:
1. Go to http://videojs.com/ using Chrome with cookies blocked
2. Start playing the demo video
3. Adjust the video's volume control

The problem seems to be this line:
https://github.com/zencoder/video-js/blob/master/src/js/lib.js#L514

**Comment by morris** [comment]
https://code.google.com/p/chromium/issues/detail?id=426206
