### ISSUE TITLE
video stretches and truncates on chrome.

### ISSUE THREAD

**Issue by videoen** [videojs/video.js#3511]
## Description
Video playback with 480p videos stretches and truncates on chrome with HTML5 tech.
We are using wowza for HLS streaming.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Play any 480p video using Flash tech on chrome.
2. Compare the same with HTML tech there is a significant stretch and truncation in the video.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.11.0
#### browsers
chrome 52.
#### OSes
windows.
### plugins
videojs-contrib-hls. 3.3.0

**Comment by gkatsev** [comment]
Can you open the issue against the contrib-hls repo? Thanks.

**Comment by videoen** [comment]
Sure. Thanks.

**Comment by gkatsev** [comment]
Moved to https://github.com/videojs/videojs-contrib-hls/issues/811
