### ISSUE TITLE
Version 5.11.1 is missing the dist directory

### ISSUE THREAD

**Issue by JosephHalter** [videojs/video.js#3512]
Had to revert to previous version 5.10.8 - please ensure next release is okay. Have a nice day and thanks for everything.

**Comment by BrandonOCasey** [comment]
After installing `video.js@5.11.1` manually I found that there is a dist directory in `node_modules/video.js/dist`. Is 5.11.1 the version that you had issues with?

**Comment by gkatsev** [comment]
5.11.1 doesn't have a dist folder in the github tag. Something went wrong last night during publishing and I didn't have time to fix it. Will look into republishing again this morning.

**Comment by gkatsev** [comment]
Fixed in 5.11.2.

**Comment by Deckluhm** [comment]
`dist` directory is missing again in `5.11.3`.

**Comment by gkatsev** [comment]
ugh, thanks for letting me know @Deckluhm.

**Comment by gkatsev** [comment]
Fixed.

**Comment by gkatsev** [comment]
Check out 5.11.4.
