### ISSUE TITLE
Context menu appears outside window on full screen using videojs-contextmenu-ui 

### ISSUE THREAD

**Issue by shanthu89** [videojs/video.js#3517]
## Description
I am trying to build a custom context menu using videojs-contextmenu-ui plugin. When I do full screen on the video and do a right click at the right corner on the video, the custom context menu goes outside the window. 
Below image of the videojs-contextmenu-ui plugin
![videojs-contextmenu](https://cloud.githubusercontent.com/assets/12282419/17534854/2b3dcdf2-5e40-11e6-9225-8c11c125a657.png)

Is there a way we could have the context menu appear inside the window oriented the opposite side on full screen as in Youtube?
Expected result as in youtube context menu:
![youtube- contextmenu](https://cloud.githubusercontent.com/assets/12282419/17534598/bd2a08e0-5e3e-11e6-8161-d4b49f59a97b.png)

## Steps to reproduce

1. Load video using videoJS-contextmenu-ui
2. Do a full screen on the video and right click at the right corner of the video. You can see the custom context menu appear outside the window. Although the native context menu appears correctly oriented inside the screen.

### Expected

Make custom context menu appear inside the window when clicked on the right corner of video in full screen as in YouTube.

#### videojs 
video.js -  5.10.4
#### browsers 
occurs in all browsers
### plugins
 videojs-contextmenu - 1.1.0
 videojs-contextmenu-ui - 3.0.2

**Comment by gkatsev** [comment]
Hi, thanks for the issue. Looks like something that should be fixed. However, all the work happens in the videojs-contextmenu-ui plugin. Can you re-open this issue against that repo?
Thanks!

**Comment by shanthu89** [comment]
Thanks. Sure I will reopen in videojs-contextmenu-ui repo.

**Comment by gkatsev** [comment]
Thanks!

Here's a link to the issue: https://github.com/brightcove/videojs-contextmenu-ui/issues/2
