### ISSUE TITLE
Move Flash tech out of core

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#3520]
Flash is going away. Should we make it an optional add-in like the YouTube or Vimeo techs? Discuss.

Some more context in [the video.js blog](http://blog.videojs.com/the-end-of-html-first/).

**Comment by BrandonOCasey** [comment]
Would it be possible to make it like vtt.js is right now? Where we request the flash portion of the player if we need it?

**Comment by gkatsev** [comment]
@BrandonOCasey the idea is that we rip all the flash parts out of videojs and put it into a separate tech plugin like videojs-youtube. A user of videojs could include the Flash tech plugin and even potentially include it asynchronously.

**Comment by mister-ben** [comment]
It might make any transition less painful if the Flash tech plugin were CDN hosted so the documentation could be as simple as "add this script tag for Flash support". Or host some bundles like core + flash, core + contrib-hls.

I do wonder how many use RTMP for live streams could use HLS but just don't know about videojs-contrib-hls.

**Comment by gkatsev** [comment]
Probably a lot. We could potentially publish it to the videojs CDN.

**Comment by misteroneill** [comment]
I think it's a great idea provided it's part of a video.js 6.0 release.

**Comment by cycleos** [comment]
I support the idea, while this in fact should be announced at least 6 months before actually taking effect. So users can find the time to plan their actions.

**Comment by dmlap** [comment]
@cycleos yeah, it would be nice to give more notice. I feel like Chrome and the other browsers are forcing the timeline with all the limitations they're planning for Flash between now and December. 

On the good news front: right now we're only talking about extracting it from the core. You could still include it manually and get backwards-compatible behavior.

**Comment by misteroneill** [comment]
Also, it should be noted that this would definitely be a breaking change, which would necessitate a major version bump. Unless you're always including the latest version of video.js no matter what (which you definitely should _not_ be doing), you wouldn't break on the 5.x line.

**Comment by spodlecki** [comment]
While I personally would support Flash on most properties, I'd lean towards removing it out of core. The fallback would be easy enough just included a plugin and call it a day.

This way; the sites who would still require fallback can use it -- and those that don't can lighten the network load a little.

**Comment by gkatsev** [comment]
We've decided this is the way to go and will be doing it at some point, hopefully lined up with chrome/firefox released.

**Comment by spodlecki** [comment]
💭  Is there a related issue / task to link to? If not, maybe keep this open / tag it for a milestone? (Not entirely sure how you guys work, but worth a mention)

**Comment by Stefanbracke** [comment]
What options do i need to remove Flash? I have this CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED error and I think it is due to not having (and not requiring) Flash from my users.
