### ISSUE TITLE
I want to use video.js play hls and google ima. cant i use version?

### ISSUE THREAD

**Issue by lipxitutvl10** [videojs/video.js#3522]
I want to use video.js play hls and google ima. cant i use version?

**Comment by mister-ben** [comment]
You use plugins to add this functionality.

- [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) adds HLS support to browsers that don't have native support.
- [googleads/videojs-ima](https://github.com/googleads/videojs-ima) adds the IMA SDK.
