### ISSUE TITLE
Video.js crash when Chromecast CastPlayer is in background

### ISSUE THREAD

**Issue by slaby93** [videojs/video.js#3526]
## Description

Im developing library for chromecast device that can show video in overlay. I tested it on multiple Google Chromecast demo apps and everything works.
Problem occur in Cast Videos Sample app.
You choose video on android application and web application download it from server and plays on chromecast device. I wanted to stop video in the middle, show my short film and then play to the end. But when I load video.js player i get this:
## Steps to reproduce

https://github.com/googlecast/CastVideos-android
https://github.com/googlecast/CastReferencePlayer
They use there 
```
var playerDiv = document.getElementById('player');
    new sampleplayer.CastPlayer(playerDiv).start();
```
### Expected

I expect to just play video by video.js because trying to show video before or after works perfectly.
### Actual

Please describe what actually happened.
Video.js starts and throws error below. But all HTML elements stay in place, loader works etc.
### Error output

If there are any errors at all, please include them here.
```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. MediaError {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}code: 3message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."__proto__: Object_logType @ colortv_sdk.js:40741log.error @ colortv_sdk.js:40692error @ colortv_sdk.js:31980handleTechError_ @ colortv_sdk.js:30785ret @ colortv_sdk.js:40570ret @ colortv_sdk.js:40570data.dispatcher @ colortv_sdk.js:40218
undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```
## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs

what version of videojs does this occur with?
`5.10.7`
#### browsers

what browser are affected?
Chrome
#### OSes

what platforms (operating systems and devices) are affected?
Chromecast 2
### plugins

are any videojs plugins being used on the page? If so, please list them below.
videojs-vast-plugin

**Comment by gkatsev** [comment]
Are you trying to play back the same video in both chromecast and videojs?

**Comment by slaby93** [comment]
No, completely different

**Comment by slaby93** [comment]
If I play video before playing cast video or after everything works so it cant be corrupted media etc. I think it's some kind of battle between those two players on some HTML5 resource. I tested it also like firstly playing Video.js and during video start cast player and he cant start neither.
