### ISSUE TITLE
'title' attribute doesn't appear for audio button

### ISSUE THREAD

**Issue by pagarwal123** [videojs/video.js#3528]
## Description
`title` attribute doesn't appear for audio button

## Steps to reproduce

1) Load the player in socrates
2) Under Media section -> select "advanced bip-bop"
3) Click on Audio button

### Expected
There should be a `title` attribute displayed on clicking the Audio button

### Actual
'title' attribute doesn't appear for audio button

#### videojs
what version of videojs does this occur with?
`5.11.2`

#### browsers
what browser are affected?
`chrome`

#### OSes
what platforms (operating systems and devices) are affected?
`OS X`

**Comment by gkatsev** [comment]
The [`controlText_`](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/captions-button.js#L75) is missing for the [`audio-track-button`](https://github.com/videojs/video.js/blob/master/src/js/control-bar/audio-track-controls/audio-track-button.js) element.
This is one of those easy bugs that can should allow entry into the project or open-source in general.

**Comment by jbarabander** [comment]
@gkatsev I'd love to take a stab at this if that's ok with you!  Also much love to all you guys for Video.js.  It absolutely kicks butt.

**Comment by gkatsev** [comment]
@jbarabander that would be awesome! Let me know if you need help either here or on slack (or irc).

**Comment by jbarabander** [comment]
@gkatsev Awesome!  Thanks so much and will do! :)
