### ISSUE TITLE
Synchronize  audio with video

### ISSUE THREAD

**Issue by sethbrandom** [videojs/video.js#3535]
Hi, everyone! Maybe this isn't an issue, but I try many things but doesn't work... that is a way to play an audio just when the player starts a video? 

Thanks for help

**Comment by gkatsev** [comment]
You should be able to listen `play` event and then play your `audio` as part of the listener.
Hope that helps.

**Comment by sethbrandom** [comment]
Mr. Katsevman, thanks for help, but if you don't mind, could you lead me the way how to implemment this? I'm using the videojs because it's much more easy and customizable for someone who don't have much knowledge on this, my case. 

Anyway, thanks for all 

Seth

**Comment by gkatsev** [comment]
You can listen to events with [`on`](http://docs.videojs.com/docs/api/player.html#Methodson) and you can play a player with [`play`](http://docs.videojs.com/docs/api/player.html#Methodsplay).
