### ISSUE TITLE
Fullscreen resolution issue using videoJS

### ISSUE THREAD

**Issue by rpundlik** [videojs/video.js#3545]
## Description
Hello All,

We are displaying the video using videoJS library in bootstrap modal, the video looks fine in modal popup. However, when we try to see the video in full screen mode the video look quite blur. So, my is question do we need to set the resolution if going for full screen mode OR it is explicitly handled by VideoJS, if yes then how?

### Expected
The video should be seen with correct video quality and resolution

### Actual
Video looks blur if we switch on to full screen mode

#### videojs
5.10.8
#### browsers
Firefox, Chrome
#### OSes
Windows 7

Thanks for the help !
Rohit

**Comment by gkatsev** [comment]
What kind of video are you playing? Is it playing back in flash or not? Would be easiest if you can provide a [reduced test case](https://css-tricks.com/reduced-test-cases/).

If it's an mp4, videojs chooses the first mp4 in the sources list and plays it. It doesn't switch sources when it goes fullscreen.
If you're using HLS, it should be upswitching, assuming sufficient bandwidth, but it can take a few seconds.
In flash, in fullscreen flash has more trouble playing back videos, so, could be related.

There are plugins for videojs that provide resolution switchers for mp4s like https://github.com/kmoskwiak/videojs-resolution-switcher.

**Comment by rpundlik** [comment]
Thanks for the reply !
I have resolved using https://github.com/kmoskwiak/videojs-resolution-switcher.
Rohit

**Comment by gkatsev** [comment]
Cool!
