### ISSUE TITLE
IE8 hack, \0screen broke less js

### ISSUE THREAD

**Issue by Alex-Ferreli** [videojs/video.js#3546]
Hi!

I have a problem with the latest version of video js. I used search but didn't find an already opened issue.

I must import the compiled CSS file because i use less js in my project. But less js fail to compile due to a media query error broken (HACK for IE8). How can i let compile the css with less? I'm using a post css plugin to support the less files, but the issue is with normal less tools too.

I read the same problem with sass, but i can't modify the video.js CSS before import it with less.
How can i fix my problem? Thanks in advance!

**Comment by gkatsev** [comment]
Are you trying to compile the release version of the videojs css with less? What's the specific usecase for that?

Does http://stackoverflow.com/a/16830938 help?
