### ISSUE TITLE
Player downloads whole video on pause

### ISSUE THREAD

**Issue by paweldziura** [videojs/video.js#3548]
## Description
I was checking the network tab in chrome and I found out that video gets progresively, slowly, downloaded during play. And this is totally ok. However, when user click pause, whole video gets downloaded. This can be bad for mobile devices as it downloads a lot of data which may not be used.
It would be good if player woudn't download the rest of the video.

## Steps to reproduce
1. click play
2. click pause 

### Expected
Nothing happens. Eventually part of the video after timeline marker gets downloaded.

### Actual
Whole video gets downloaded

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.8
#### browsers
Tested on chrome
#### OSes
Tested on Windows 10

**Comment by gkatsev** [comment]
What type of video are you loading? Is it an mp4? Is it being loaded in flash or not?
Assuming it's an mp4 not being loaded in flash, this is native behavior and all depends on the browser itself. videojs has no control over how the browsers choose to load things natively.

**Comment by paweldziura** [comment]
It is mp4 and it's not using flash. Does extension of the file matter in that case?
Thanks

**Comment by gkatsev** [comment]
No, was just wanting to verify whether it was loading natively or not. mp4s generally load using the natively and we have no control over how it's done, unfortunately.
