### ISSUE TITLE
Is there a way to start a  videojs after loaded all new created Components(Buttons, etc)?

### ISSUE THREAD

**Issue by apatinoyu** [videojs/video.js#3552]
I used to create my new Buttons after the videojs is ready, because I didn't find a way to implement every change I have to my video before it is ready.
Somehow sometimes depending on the connection, platform my video starts after long time because sometimes takes time to create any component but I would not to show my Player, buttons.
I know the VideoPlayer works async  but I would like to know if there is a callback to confirm when I should reproduce the  videoPlayer.
Thanks for this Player.

I used to do this before creating my Buttons and all the new things I want to implement.

```
videojs('id', options, function () { }).ready(function () {
//creating ...
newComponent("newButtonFeature", "Button");
buttonWithNewFeature = videoPlayer.controlBar.addChild("newButtonFeature");
}
```

**Comment by gkatsev** [comment]
You probably want to create your components after videojs loads but before loading the player. You can then configure the component on the player via options. Here's some sample/pseduo code:
```js
// videojs is loaded via a script before here

class MyButton extends videojs.getComponent('Button') {
  // your class
  // this uses ES6 class syntax but can be done with videojs.extend instead
}

videojs.registerComponent('MyButton', MyButton);

var player = videojs('id', {
  controlBar: {
    myButton: {}
  }
}, function() {
  console.log('my player is ready!');
});
```

Hope that helps.
