### ISSUE TITLE
Subtitles embedded in dash manifests dont display consistently 

### ISSUE THREAD

**Issue by jinpark** [videojs/video.js#3556]
## Description
Captions when bundled up in a dash manifest only gets displayed when you don't change the caption language or dont display at all. A test page is at https://jsfiddle.net/jvv0h0bL/ using https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-wvtt/dash.mpd manifest with videojs-contrib-dash 

## Steps to reproduce

1. Prepare videojs to handle dash (add dash.js and videojs-contrib-dash.js libraries)
2. Load up video src with a manifest that has embedded subtitles ex. https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-wvtt/dash.mpd or https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd
3. Switch caption languages through the controlbar and see that no more captions appear

### Expected
Captions should appear as long as theyre not disabled.

### Actual
Captions either show initially and then disappear when you change the language or do not show up at all.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
tried with videojs versions 5.2 and 5.10 with same results
#### browsers
tried this with google chrome 52.0.2743.116
#### OSes
only tried with mac + chrome
### plugins
dash.js latest (2.20)
videojs-dash-contrib latest (2.4.0)

Please let me know if this is in the wrong repo. I wasn't sure if this should be in the contrib-dash repo or even the vtt repo.

**Comment by gkatsev** [comment]
Can you re-open this against the [contrib-dash repo](https://github.com/videojs/videojs-contrib-dash/issues/new)?
I've confirmed that the captions aren't showing up but they do show up in the [dashjs reference player](http://dashif.org/reference/players/javascript/nightly/dash.js/samples/dash-if-reference-player/index.html), so we need to investigate a bit more and see where the issue lies specifically.

**Comment by jinpark** [comment]
yup no problem!

**Comment by gkatsev** [comment]
Thanks!
