### ISSUE TITLE
Video streaming stuck

### ISSUE THREAD

**Issue by Rohitrcp** [videojs/video.js#3557]
## Description
When i am trying to play stream after some time video is stuck also  video swirling - refresh did not work - closing reopen worked.
How can change dynamically video resolution from manifest url.

## Additional Information
i am using stream in this format ".m3u8".

#### videojs
5.10.7
#### browsers
Chrome
IE
Firefox
#### OSes
Windows
### plugins
videojs-contrib-hls

**Comment by dmlap** [comment]
You should probably file this issue over in [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) but we would need a [reduced test case](https://css-tricks.com/reduced-test-cases/) or a more detailed list of steps to reproduce to help you.
