### ISSUE TITLE
videojs not consistent between firefox and chromium

### ISSUE THREAD

**Issue by bzb2** [videojs/video.js#3561]
Using videojs 5.10.8
let ff=FireFox 48
let ch=Chromium Version 51.0.2704.79
Test system is lubuntu 16.04.01 xenial
All test files are local to the test system.

```
    player           use vtt subtitle    use srt subtitle
--------------------------------------------------------
    video/3gpp
ff    fail             n/a                 n/a
ch    fail             n/a                 n/a
    video/webm
ff    ok               ok                  fail
ch    ok               fail                fail
    video/mp4
ff    ok               ok                  fail
ch    ok               fail                fail
    video/ogg
ff    ok               ok                  fail
ch    ok               fail                fail

    audio/mpeg
ff    ok
ch    ok
    audio/ogg
ff    ok
ch    ok

```
To interpret the chart, let's take a look at the 1st 2 row sections.
For mimeType=video/3gpp, the player does not work properly for both firefox and chromium.
For mimeType=video/webm, For firefox, the player displays the video properly and shows the subtitles properly when the subtitles are specified in the webVTT format. But fails to show the subtitles when specified in the SRT format.  For chromium, the player displays the video properly but fails to display subtitles either specified in webVTT or SRT format.

The bottom 2 row sections indicates that firefox displays the audio player and plays audio properly for both audio/mpeg and audio/ogg. Likewise for chromium.

Below is a sample of relevant html code used for the test with the appropriate values changed for each test.

```
<head>
...
<link href="http://vjs.zencdn.net/5.10.8/video-js.css" rel="stylesheet">
<!-- If you'd like to support IE8 -->
<script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>

<body>
...
<video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="500" height="281" poster="media/poster.jpg" data-setup="{}">
    <source type="video/mp4" src="media/test.mp4" />
    <track srclang="en" kind="subtitles" src="media/test-en.srt" ></track>
    <track srclang="fr" kind="subtitles" src="media/test-fr.srt" ></track>
</video>
<audio controls>
    <source type="audio/mpeg" src="media/test.mp3"/>
    Your browser does not support the audio element.
</audio>
...
<script src="http://vjs.zencdn.net/5.10.8/video.js"></script>

```
Hope this helps.
Thanks

**Comment by gkatsev** [comment]
Thanks for the issue. 3gpp video is not supported in either Chrome or Firefox. Both browsers don't support srt subtitle files as well, though, we may add support for them in videojs via our emulated caption handling -- by default, we try and have the browser handle it. Though, it's weird that chromium isn't able to play back the webvtt files. Can you put up a reduced test case where you saw these failures? We've definitely seen webvtt files working in chrome.

**Comment by bzb2** [comment]
Here is the sample code to reproduce the issue. On firefox you will be able to see the video with the caption (you need to selected it).  On chromium, the video plays well and the cc icon is shown. But if you were to select any language, the subtitles would not show.  You can use the html code provided below and use the sample webVTT subtitles from https://github.com/minakov/CastMediaPlayerStreamingDRM/blob/master/captions.vtt
Just create a file called test-en.vtt and copy the subtitle text into it.

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Test videojs</title>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.1.min.js"></script>

<link href="http://vjs.zencdn.net/5.10.8/video-js.css" rel="stylesheet">
<!-- If you'd like to support IE8 -->
<script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>
<body>
<video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="500" height="281" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4">
    <track srclang="en" kind="subtitles" src="test-en.vtt" label="English" ></track>
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>

<script src="http://vjs.zencdn.net/5.10.8/video.js"></script>
</body>
</html>
```

**Comment by bzb2** [comment]
Having done more testing I found that webVTT subtitles only fail on chromium when the subtitle files come from the local harddrive.  It works from is the subtitles come from the web.

**Comment by gkatsev** [comment]
Loading it in, I see a CORS error in the console for the raw.githubusercontent.com. You'd want to add in the `crossorigin="anonymous"` attribute if you're [loading subtitles from another domain](https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#subtitles-from-another-domain).
Also, browsers don't support loading things like captions over the `file:///` protocol.

Hope that helps.
