### ISSUE TITLE
plugin developpment

### ISSUE THREAD

**Issue by MehdiGuelloub** [videojs/video.js#3567]
Hello everyone,

I looked everywhere on the internet but I couldn't find any clear documentation or some examples to create my verySimplePlugin for videoJS 5 (Since it uses ES6).

I just want to add a button next to the big play button... Can someone help me?

I tried this code btw:

`var SharingButton = videojs.getComponent('Button');`

```
videojs.SharingButton = videojs.extend(SharingButton , {
    constructor: function(player, options){
      videojs.Button.call(this, player, options);
      this.player = player;
    },
    createEl: function() {
    return SharingButton.prototype.createEl('div', {
        className: 'vjs-my-button',
        innerHTML: '<div>my button</div>'
      });
    },

    buildCSSClass: function() {
      return 'vjs-sharing-btn';
    },

    handleClick: function() {
      console.log('####### Hey ##');
    }
});
```

`videojs.registerComponent('SharingButton', SharingButton);`

Thanks...

**Comment by misteroneill** [comment]
Hi @MehdiGuelloub - you may want to check out [our Yeoman generator for video.js plugins](https://github.com/videojs/generator-videojs-plugin). You can use it for bootstrapping a plugin project.

That code is fine as a start, but to get it to show up, you need to inject it into the player's DOM. One way to do this simply is add `'sharingButton'` to your player's `children` option.

**Comment by BrandonOCasey** [comment]
it also looks like your code may want to start/end more like this: (right now you are not actually registering SharingButton, but the base button class)
```JavaScript
var Button = videojs.getComponent('Button');

var SharingButton = videojs.extend(Button , {
...
});
videojs.registerComponent('SharingButton', SharingButton);
// Add as a child to the player here
```

**Comment by yshterev** [comment]
Hi @MehdiGuelloub - After way too much time spent on this, here is my solution. I hope it saves time to someone else. 
```
// Wait for the player being "ready" in the main plugin function, 
// so you can access this.controlBar or other components directly

this.ready(function () {

  var Button = videojs.getComponent('Button');

  // Extend default
  var SharingButton = videojs.extend(Button , {
    constructor: function(player, options){
      Button.apply(this, arguments);
    },

    createEl: function() {
      return Button.prototype.createEl('button', {
        className: 'vjs-my-button',
        innerHTML: 'my button'
      });
    },

    handleClick: function() {
      console.log('click');
    }
  });

  // Register the new component
  videojs.registerComponent('SharingButton', SharingButton);

  // Add it to DOM
  this.controlBar.addChild('SharingButton');

});
```

**Comment by gkatsev** [comment]
You shouldn't need to wait for the player to be ready to create and register the component. You'd only need to wait to do the `addChild` part.

**Comment by BrandonOCasey** [comment]
also this may be something helpful to stick in the docs

**Comment by MehdiGuelloub** [comment]
Ok thank you guys. As @BrandonOCasey said I was registering the base class Button which I'm calling SharingButton. Now it works.

Just an other small problem I want to add this button to the player next to bigPlayButton.

when I add it to the controlBar I can see it
`player.getChild('controlBar').addChild('SharingButton');`

But when I do 
`player.addChild('SharingButton');`

It doesn't work. Any solution?

**Comment by gkatsev** [comment]
You should be able to add children directly to the player.
Have a live test case up somewhere?

**Comment by MehdiGuelloub** [comment]
@gkatsev yes I made a plunker in which my button is in the controlBar. here is the link [http://plnkr.co/edit/cGEZIQh3K3XYIrAKtM3r?p=preview](url)

**Comment by gkatsev** [comment]
@MehdiGuelloub looks like it was working but just missing some styles. Here's an updated plnkr: http://plnkr.co/edit/sFfqpY?p=preview

Going to close this now because it doesn't require any direct changes to videojs. And we're well aware that our documentation will need to be updated.

**Comment by richardbushell** [comment]
I can see this is closed, but can I just ask whilst this functioning example is clicking around, what would be the correct component to register if we wanted this new element to be an anchor to link elsewhere? A button doesn't allow links does it? And it isn't showing the hand icon to signal to press it.

**Comment by gkatsev** [comment]
@richardbushell I guess just a component? Or maybe a `clickable-element` component?
