### ISSUE TITLE
Vertical Volume Slider doesn't auto-hide after adjusting volume level

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#3573]
Here's my reduced test case with Vertical Volume enabled:-
https://living.video/vjsreduced.html
Steps to reproduce:-
Play video
Click on the Volume Button icon (should mute video)
Now click on any mid-Volume Level in the Vertical Slider
Now move the mouse away from the video
Wait for all controls to auto-hide
Now mouseover video again
Volume Slider still there.
(fairly sure this used to hide correctly in previous versions)
Tested on all browsers with the same result.
Using VJS 5.11.0
p.s. the same thing happens if you click onto the grey background behind the slider (even without first clicking the Volume Button first).

**Comment by chemoish** [comment]
@richardbushell It seems like it might have to do with some accessibility focus bug?

Playing around with it I noticed that if you *hover* over the Volume Button, change the volume, then hover out, it will put your focus on either a) the Volume Button or b) The Progress Bar.

If the focus stays on the Volume Button, then it will reproduce a similar bug (Which I assume is for accessibility).

**Comment by richardbushell** [comment]
Yep, I agree.
Anyone in core-dev team have the js/css knowledge to track down and sort the problem?

**Comment by gkatsev** [comment]
The volume control has been completely rewritten in v6 and v5 is since deprecated, we are unlikely to fix it in v5. If this is still an issue in v6/v7, we can look into it and hopefully #5503 makes it be a none-issue as well.
