### ISSUE TITLE
Videojs skin builder generator

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#3575]
I don't where to post this, i did a Videojs skin maker page to build your own Videojs Skin easly.
http://toolurl.com/Video_Skin_Generator/Videojs/videojs-skin-generator.html

**Comment by gkatsev** [comment]
That's awesome!
If you tweet it with @videojs or #video.js in it, we can RT it. You can also probably add it to the [skins page](https://github.com/videojs/video.js/wiki/Skins) on the wiki.

Going to close it because no changes required to videojs.

**Comment by onigetoc** [comment]
Thank you, i will do it
