### ISSUE TITLE
how to extjs add video.js framework?

### ISSUE THREAD

**Issue by inviss** [videojs/video.js#3582]
how to extjs add video.js framework?

What should I do??
thank you

**Comment by misteroneill** [comment]
The GitHub issues tracker is generally for reporting software bugs. If you're asking a question about usage, you might get better results [on StackOverflow](https://stackoverflow.com/questions/tagged/video.js).

That said, I don't think any of the core contributors use ExtJS, but if you have access to the DOM, you can use video.js! Sorry I couldn't be more helpful.
