### ISSUE TITLE
vjs-big-play-button not working for google chrome (Version 52.0.2743.116 (64-bit)) in Ubuntu 16.04

### ISSUE THREAD

**Issue by Dowwie** [videojs/video.js#3584]
My setup:
Ubuntu 16.04
Google Chrome (Version 52.0.2743.116 (64-bit)) 

problem:   vjs-big-play-button isn't working within google chrome

further, I've verified that vjs-big-play-button works in FireFox

## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by misteroneill** [comment]
Do you have a source loaded? There was a recent change to make the big play button not do anything if there is no source.

**Comment by misteroneill** [comment]
You shouldn't need to build from source, but I'm glad it's working now.

However, I had meant did you have a video source (e.g. a `<source>` element, a `src` attribute, etc) loaded. The player will just sit there without one!

Also, sounds like the README could stand to be updated as part of the build process! 😆
