### ISSUE TITLE
 Undefined variable: "$ie8screen"

### ISSUE THREAD

**Issue by pavankumarkatakam** [videojs/video.js#3587]
## Description
when using the videojs with webpack automation tool (minifying), it is saying error
````
Undefined variable: "$ie8screen".
      in project_location/bower_components/video.js/dist/video-js.css (line 1297, column 1)

````

**Comment by misteroneill** [comment]
What version of video.js are you using?

**Comment by gkatsev** [comment]
I'm guessing webpack is complaining about the *commented out* css variable here? https://github.com/videojs/video.js/blob/v5.12.1/dist/video-js.css#L1297-L1318

**Comment by pavankumarkatakam** [comment]
Hi im using 15.12.1 version, the variable is not commented out so webpack is showing the error and stopping the build.

**Comment by BrandonOCasey** [comment]
you can try using the video.min.css, as that will not have the `$ie8screen` variable in it

**Comment by gkatsev** [comment]
As far as I can tell, it's commented out. Though, we should just remove that comment altogether, it's not necessary.

**Comment by gkatsev** [comment]
Should be fixed by https://github.com/videojs/video.js/pull/3625
