### ISSUE TITLE
Access denied for CDN files

### ISSUE THREAD

**Issue by wasik** [videojs/video.js#3588]
## Description
I suspect the most recent files (5.11.6) weren't pushed to S3. They are listed on this page: http://videojs.com/getting-started/

## Steps to reproduce
Visit here in a browser:
http://vjs.zencdn.net/5.11.6/video-js.css

### Expected
The .css file

### Actual
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4BB8E02B90E5C0B5</RequestId>
<HostId>
bU9fogRjslsihu48ZilVUdgDuo+/+A3Rs23PzYISskFf0JVA8FOPo9S/OHU5iSbJ
</HostId>
</Error>

**Comment by gkatsev** [comment]
Thanks for letting us know. We forgot to publish it to the CDN.

**Comment by gkatsev** [comment]
Published, thanks. Sorry for the issues.
