### ISSUE TITLE
Changelog does not indicate which changes are breaking

### ISSUE THREAD

**Issue by ljharb** [videojs/video.js#3590]
https://github.com/videojs/video.js/blob/master/CHANGELOG.md#500-2015-09-29 doesn't tell me which changes are semver-patch, semver-minor, and semver-breaking - so I don't know which of the long list of things I need to read in order to figure out what things might be breaking me as I go from v4 to v5.

 1. what were the breaking changes that required a v5 bump?
 1. Can the changes in the changelog indicate their individual semver status?

**Comment by forbesjo** [comment]
There is a section in the wiki for 4->5 changes https://github.com/videojs/video.js/wiki/5.0-Change-Details however it might not have all breaking changes since the last time it was updated.

**Comment by ljharb** [comment]
Thanks, that helps a ton. I still think semver info belongs in the change log, and this wiki should be linked from there.

**Comment by chemoish** [comment]
There was some talks about using commitizen, but not sure if that is going to be used. cz does provide changelog which would help https://www.npmjs.com/package/cz-conventional-changelog.

Either way, sectioning out PR's would be nice (https://github.com/angular/angular.js/blob/master/CHANGELOG.md#158-arbitrary-fallbacks-2016-07-22).

I found a breaking issue earlier https://github.com/chemoish/videojs-chapter-thumbnails/pull/20. But not sure if it could have been mitigated.

**Comment by misteroneill** [comment]
Our team at Brightcove are currently planning out some work for Q4 around improving release workflow for video.js. Commitizen is definitely on the list for investigation as are other tools.

This is really useful feedback and is something I think we should definitely consider for future additions to the CHANGELOG.

**Comment by gkatsev** [comment]
We're (more like me :P) following conventional-changelog now. First release with it was 5.12.3: https://github.com/videojs/video.js/releases/tag/v5.12.3.
We're not going to update the old versions but it should be better starting now.

**Comment by ljharb** [comment]
Great, thanks!
