### ISSUE TITLE
Chrome 52 HTML5 Video playback distortion

### ISSUE THREAD

**Issue by majianxiong** [videojs/video.js#3594]
## Description
In the new chrome 52.0.2743.116 m (64-bit) version , HTML 5 video playback appear distortion phenomenon.
http://output.jsbin.com/suqojarenu/1
http://jsbin.com/suqojarenu/1/edit?html,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Using a mobile phone video source size dimension.
2. Using Chrome on Window7 64bit , open a videojs player .
3. Click play.

### Expected
Using Chrome 50.0.2661.102 version , Cell phones play a normal size.
![image](https://cloud.githubusercontent.com/assets/887531/18153460/16503748-7030-11e6-8ad5-f770e51237f6.png)

### Actual
Using Chrome 52.0.2743.116 m (64-bit) version.
![image](https://cloud.githubusercontent.com/assets/887531/18153506/89f38948-7030-11e6-93b8-7b762b461852.png)

### Error output
N/A.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Video.js 5.0.2
#### browsers
Chrome 52.0.2743.116 m (64-bit) version
#### OSes
Window7 64bit 
### plugins
No..

**Comment by mister-ben** [comment]
This is a bug in Chrome, fixed in 53.

https://bugs.chromium.org/p/chromium/issues/detail?id=632624

**Comment by majianxiong** [comment]
@mister-ben 	
thank you!

**Comment by dmlap** [comment]
I don't think there's anything we can do about this one so I'm closing it. We'll just have to wait for Chrome 53 for the fix.
