### ISSUE TITLE
webpack error Cannot set property 'vttjs' of undefined

### ISSUE THREAD

**Issue by Avolons** [videojs/video.js#3598]
in the webpack ，have a error
import ‘video.js’

 Cannot set property 'vttjs' of undefined

**Comment by BrandonOCasey** [comment]
what version of video.js are you using?

**Comment by misteroneill** [comment]
My guess here is that `window` is undefined, maybe? Is the code being run in a non-browser environment?

**Comment by gkatsev** [comment]
Please fill out the [issue template](https://github.com/videojs/video.js/blob/master/ISSUE_TEMPLATE.md). It makes it a lot easier for us to understand your problem and help you.
Though, I think this is potentially related to https://github.com/videojs/video.js/issues/3491.
