### ISSUE TITLE
MS Edge (Win 10) reports @font-face Error

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#3599]
Reduced Test Case:
https://living.video/vjsreduced.html

MS Edge on Windows 10:-

Console Error is:-
CSS3120: No fonts available for @font-face rule
video-js.css (12,7)

All other browsers OK, except Edge, so is there an incompatibility with Edge?

**Comment by richardbushell** [comment]
IF I REMOVE:

@font-face {
  font-family: VideoJS;
  src: url("font/VideoJS.eot?#iefix") format("eot"); }	

then it works OK.

Not sure why this causes Edge to fail, can it be removed at source now, or is this still required?
Or sortable?

**Comment by gkatsev** [comment]
We can't remove or reorder that because that's what makes IE8 still work.
Though, I wonder why it's causing issues on Edge. Maybe it's a browser bug.

**Comment by misteroneill** [comment]
As far as dropping IE8 support, I would guess - but this is _not_ a promise - that 6.0 will probably drop support entirely. We moved in that direction with 5.0 relegating a bunch of the IE8 specific code to [videojs-ie8](https://github.com/videojs/ie8).

**Comment by hartman** [comment]
FYI, even at Wikipedia, we have dropped IE8 from our list of browsers that receives JS enhancements. That means that only the CSS and HTML still have to be compatible with IE8.

**Comment by richardbushell** [comment]
So, not tried 6.0 beta, but as per @misteroneill comment above, was IE8 support indeed dropped in VJS 6.0?
IE8 is currently showing 0% usage!!!:-
https://www.w3schools.com/browsers/browsers_explorer.asp
Please advise...

**Comment by gkatsev** [comment]
6.0 isn't removing support for IE8 but we're also not going to be developing new features for it. We'll basically be maintaining the current level of support and we won't be breaking IE8 usage in 6.0.

**Comment by gkatsev** [comment]
I wonder if this is still an issue with Video.js 7 given we removed IE8 support and simplified the font.

**Comment by gkatsev** [comment]
I'm going to close this. Please open a new issue if this is still a problem.
