### ISSUE TITLE
to Android in Firefox environment , error player ready callback.

### ISSUE THREAD

**Issue by savethegreen7** [videojs/video.js#3600]
## Description
player.ready(fn) fn a call you do not use Android in Firefox environment.
player.ready(fn), not call the function fn . It seems to lose scope.
Please confirm.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.13.0
#### browsers
firefox
#### OSes
android 6
### plugins
no.

**Comment by gkatsev** [comment]
Unfortunately, without a reduced test case of much more detailed description there's not much we can do here. `player.ready` works for me on Android and in Firefox.
Closing in the meantime but we'd be happy to re-open if we get more information and it turns out to be an actual issue.
