### ISSUE TITLE
Issues with Flash Fallback

### ISSUE THREAD

**Issue by JohnnyDev0918** [videojs/video.js#3604]
This is regarding "Issues with Flash fallback #1619" (https://github.com/videojs/video.js/issues/1619) that was closed a while back (Oct 29, 2014).

The Working example (http://jsbin.com/negodamazu/2/edit?html,output) that mmcc (Matthew McClure) gave for "Issue 1 - poster" only works on Video.js version 4.10.2 (<script src="http://vjs.zencdn.net/4.10/video.js"></script>). It does not work on the latest version 5.11.6 (<script src="http://vjs.zencdn.net/5.11.6/video.js"></script>)

Could someone from Videojs such as mmcc post the new code (solution) that would work on the latest version (<script src="http://vjs.zencdn.net/5.11.6/video.js"></script>)?

Very much appreciated.

**Comment by misteroneill** [comment]
@JohnnyDev0918 It does work. I've created [a fork of Matt's original JSBin](http://jsbin.com/nutibonupe/edit?html,output) to demonstrate it. 

The poster shows up just fine, but the video may not play in certain cases in Chrome because Google is on a path toward disabling Flash by default. I had to right-click and enable Flash to get the video clip to play.

**Comment by JohnnyDev0918** [comment]
Hi misteroneill,

It's working now for some reason, even for the latest version 5.11.6 <script src="http://vjs.zencdn.net/5.11.6/video.js"></script>. I noticed that when "flash" is the first in the techOrder (for example, {"techOrder": ["flash", "html5"]} ), the Flash version is always used even though the browser supports HTML5.

Is there a way to make video.js use the HTML5 version and ignore the Flash version even though "flash" is first in the order when the code is run in HTML5 browsers?

Also, when the techOrder property is used in javascript initialization of videojs() as shown below, do I need the double quotes around techOrder (e.g, {"techOrder": ["flash", "html5"]})???

var myPlayer = videojs("videoPlayerID", {techOrder: ["flash", "html5"]});
myPlayer.src({
   src: "http://some-domain.com/videos/mymovie.mp4",
   type: "video/mp4"
});

Many thanks in advance.

**Comment by JohnnyDev0918** [comment]
I noticed that you closed this issue (3604). I didn't know you closed it so I entered some comment / questions in the ticket. Could you please read my comment and answer my questions there?
Very much appreciated.
Thank you.
 

    On Thursday, September 8, 2016 1:52 PM, misteroneill <notifications@github.com> wrote:
 

 @JohnnyDev0918 It does work. I've created a fork of Matt's original JSBin to demonstrate it. The poster shows up just fine, but the video may not play in certain cases in Chrome because Google is on a path toward disabling Flash by default. I had to right-click and enable Flash to get the video clip to play.—

**Comment by gkatsev** [comment]
A closed issue doesn't mean end of discussion. We still receive notification and will reply when we have the chance.
As for your question, you probably just want to remove the tech order altogether. This way videojs will automatically choose either html5 or flash playback and will prefer html5 playback if possible.

**Comment by JohnnyDev0918** [comment]
Oh ok thanks. Will do.
