### ISSUE TITLE
How to play aws cloudfront rtmp on videojs?

### ISSUE THREAD

**Issue by ziippy** [videojs/video.js#3607]
## Description
I was make the rtmp distribution on aws cloudfront.
The url is rtmp://s1fxhnn7qms3tq.cloudfront.net/cfx/st/example.mp4

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. code is like that
   source src="rtmp://s1fxhnn7qms3tq.cloudfront.net/cfx/st/example.mp4" type='rtmp/mp4'

2. test webpage running on my localhost webserver
  - does not show

3. the the url via VLC
  - show

### Expected
show the move in webpage

### Actual
does not show

### Error output
The browser's console message is none

#### videojs
5.11.6
#### browsers
IE11, Chrome

Anyone.. can see the aws cloudfront rtmp video in videojs.
Please help.

**Comment by ziippy** [comment]
Full code is like that

`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=EUC-KR">
<link href="https://vjs.zencdn.net/5.11.6/video-js.css" rel="stylesheet">
<script src="https://vjs.zencdn.net/5.11.6/video.js"></script>
</head>
<body>

	<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="264" data-setup='{ "techOrder": ["flash"] }'>
	  <source src="rtmp://s1fxhnn7qms3tq.cloudfront.net/cfx/st/mylove.mp4" type='rtmp/mp4'>
	</video> 

</body>
</html>`

**Comment by ziippy** [comment]
code is like that

```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=EUC-KR">
<link href="https://vjs.zencdn.net/5.11.6/video-js.css" rel="stylesheet">
<script src="https://vjs.zencdn.net/5.11.6/video.js"></script>
</head>
<body>

	<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="264" data-setup='{ "techOrder": ["flash"] }'>
	  <source src="rtmp://s1fxhnn7qms3tq.cloudfront.net/cfx/st/mylove.mp4" type='rtmp/mp4'>
	</video> 

</body>
</html>
```

**Comment by ziippy** [comment]
I was find the solution.

add the **&mp4:** before the filename.

`<source src="rtmp://s1fxhnn7qms3tq.cloudfront.net/cfx/st/&mp4:mylove.mp4" type='rtmp/mp4'>`

you can see the movie

**Comment by misteroneill** [comment]
Sounds like this is solved! Hopefully it helps others stuck on the same issue! 😄

**Comment by neunygph** [comment]
Hi @misteroneill ,

I know this is very long time ago, I'm just wondering if you still remember the set up. I tried it but it never worked for me, Please help.

Thanks,

**Comment by mister-ben** [comment]
RTMP requires Flash. The Flash tech was included in Video.js 5, the version discussed above but was removed in version 6. You need to explicitly add the Flash tech now.

https://github.com/videojs/videojs-flash

Also consider that modern browsers don't necessarily have Flash and even if they do, may disable it and make the user take action to use it.

**Comment by neunygph** [comment]
Hi @mister-ben ,

Is https://github.com/videojs/videojs-flash a plug in for  https://github.com/videojs ? or they are 2 separated things ?

Thanks,
