### ISSUE TITLE
this Library can play rmvb format video?

### ISSUE THREAD

**Issue by moahmn** [videojs/video.js#3610]
## Description
my project have a lost of video which format is rmvb...i step by step with docs.but the brower show me a text:The media could not be loaded, either because the server or network failed or because the format is not supported.what wrong with me?

 

### Expected
Please describe what you expected to see.

i hope the rmvb format can play with chrome,firefox,ie9+,or have other way to do it?
Look forward to your reply,thanks man!

**Comment by moahmn** [comment]
this is my code:

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="video-js.min.css">

</head>
<body>
	<video id="example_video_1" class="video-js vjs-default-skin"
	  controls preload="auto" width="640" height="264"
	  data-setup='{}'>
	 <source src="CNS152.mp4" type="video/mp4" />
	 <source src="CNS152.webm" type="video/webm" />
	 <source src="CNS152.ogv" type="video/ogg" />
	 <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
	</video>

	 <script type="text/javascript" src="video.min.js"></script>
</body>
</html>

**Comment by mister-ben** [comment]
Browsers don't support rmvb and I'm not aware of any active project that adds support for it. You'd be best off converting the files into a format suitable for the web. Sorry if that's not the answer you were hoping for.
