### ISSUE TITLE
Menu's have non-component children

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#3612]
Both the default menu-button (https://github.com/videojs/video.js/blob/master/src/js/menu/menu-button.js) and the chapters button (https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/chapters-button.js) (might) add a `<li>` to the `children_` array of a menu, while I think children of `Component`s should all be a `Component`. We can (probably) fix this by creating something like a `MenuItemTitle` component.

**Comment by misteroneill** [comment]
I am on board with the idea that we should be able to expect the contents of `children_` to be components.

Probably wouldn't even need a custom component - unless it's doing something beyond what a generic component does - it could create the el and pass it as an option to a generic component.

Perhaps generic components should be able to take a DOM configuration to make this easier? Something like:

```js
new Component(this, {
  dom: {
    tagName: 'li',
    props: {},
    attrs: {}
  }
});
```

**Comment by nickygerritsen** [comment]
That does sound like a good idea IMHO :).

**Comment by misteroneill** [comment]
Or it could be an array to match the `createEl` arguments: `dom: ['li', {}, {}]`.

**Comment by nickygerritsen** [comment]
Yeah that'd make even more sense I guess, then we can just pass it to that function
