### ISSUE TITLE
Adding Hindi language support

### ISSUE THREAD

**Issue by resource11** [videojs/video.js#3617]
## Have Hindi translations... JSON unhapppy

Hey there,

I have translations ready for Hindi language support, yet when I add the translations to a JSON file, I'm seeing extraneous characters showing up.

Do you have a special process for entering characters that use Devanagari script?

I'd love to get this into a pull request.

Thanks

**Comment by resource11** [comment]
Ahhh. It was my editor. 

Sublime doesn't like displaying Hindi. 

Atom loves displaying Hindo.

**Comment by gkatsev** [comment]
Glad you figured it out.
It's possible that sublime was trying to display the file as an ASCII file but it needed to be a UTF-8 encoded file.
