### ISSUE TITLE
External Controls

### ISSUE THREAD

**Issue by mxmtsk** [videojs/video.js#3618]
Hi,

I have a general question. Is it possible and if yes is there a simple way to completely seperate the controls from the actual video element? I wanna have my controls on a different place on my page.

Thanks!

**Comment by misteroneill** [comment]
Yeah, that's definitely possible. The video.js-provided controls are normal DOM elements; so, you can move them around as you see fit. Of course, the styling will probably be a mess if they're taken out of the `<div>` created by video.js, but you could do that and adjust the CSS as necessary.

Another alternative - and, in my opinion, a better/cleaner one - is to build your own custom controls. The [video.js player API](http://docs.videojs.com/docs/api/player.html) offers methods for most things you'd want to do (e.g. `play()`, `pause()`, `volume()`, etc) when interacting with your custom controls.

These custom controls could be completely built by you or you could take advantage of video.js' [many components](http://docs.videojs.com/docs/api/index.html) to build your own controls UI.

Hope that helps!
