### ISSUE TITLE
Sometimes calling .src(...) and then .play() synchronously doesn't always work in Safari

### ISSUE THREAD

**Issue by incompl** [videojs/video.js#3622]
## Description

Sometimes the video does not play when play is called right after setting the source. @gkatsev explained to me that this is because reasons but I don't know the details. I have only seen this in Safari 9.1.3.
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.

```
player.src(myVideo);
player.play();
```
### Expected

Video plays
### Actual

Video doesn't play
### Error output

No errors, unfortunately
## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs

5.11.3
#### browsers

Safari 9.1.3
#### OSes

I don't think it's OS dependant but I'm on OSX 10.11.6
### plugins

are any videojs plugins being used on the page? If so, please list them below.
Found in the Brightcove player with its suite of plugins

**Comment by gkatsev** [comment]
Related #3099 and #3495.

**Comment by gkatsev** [comment]
I wonder whether this is an issue in latest versions of Video.js.

**Comment by gkatsev** [comment]
Going to close this since we've done some work around this, it should do a much better job at handling it. A new issue should be filed if we find more problems around it.
