### ISSUE TITLE
transforming video in css without transforming controls

### ISSUE THREAD

**Issue by lukasIO** [videojs/video.js#3628]
I'm trying to add a zoom-feature to the video player, but I cannot figure out how to transform the video without also transforming the video controls.
I know there would be a workaround of creating own, custom controls, but I'd like to avoid it in order to use other videojs plugins...
Is there a way to rotate/scale the video only and leaving the control bars in place?

**Comment by gkatsev** [comment]
You probably would want to limit your css to only apply to the `vjs-tech` class rather than `video-js` class.

**Comment by lukasIO** [comment]
exactly what I was looking for, thanks! 
is there a class structure overview somewhere in the docs that could help me next time with a similar issue?

**Comment by misteroneill** [comment]
@lukasIO There's not, but we're about to start on a big push toward better docs across the board; so, we'll definitely note that as one possibile addition we could make (no promises, of course) - thanks!
