### ISSUE TITLE
Contrib-uglify needs to be updated 0.11 to keep uglify in version 2.6

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#3631]
## Description

Uglify 2.7 introduced a [_breaking_ change](https://github.com/mishoo/UglifyJS2/pull/1179#issuecomment-248803837) with regards to IE8 support.
This means that our minified files that were released after 2.7 was released did not work in IE8.

contirb-uglify 0.11 switches the uglify dependency from being installed with a `^` to a `~` so it will never pick up 2.7.

**Comment by misteroneill** [comment]
:rage4:

**Comment by gkatsev** [comment]
This has been addressed.
