### ISSUE TITLE
Should we switch video.js away from UglifyJS?

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#3635]
Uglify released [a breaking change](https://github.com/mishoo/UglifyJS2/pull/1179) in 2.7.0 that broke us in production. They have refused to revert and issue a major version bump as semver would warrant. It's abundantly clear that the maintainers don't care about following semver despite what their version numbers suggest.

There are a few alternative paths:
1. Lock down to `2.6.4` and evaluate patch releases as we notice they are released. We cannot safely apply a semver range for this project.
   - This has extra issues because we use Uglify indirectly via grunt-contrib-uglify, which is what we'd ultimately need to lock down.
2. Switch to [Google Closure Compiler](https://developers.google.com/closure/compiler/)
3. Switch to [babili](https://github.com/babel/babili)

@videojs/core-committers

**Comment by gkatsev** [comment]
Google's Closure Compiler is now available fully in javascript and they're even [following semver!](https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/package.json#L3).
It would also be good to evaluate what the compression and time differences would be between GCC and uglify.
Also, are there any other potential contenders?

**Comment by BrandonOCasey** [comment]
I only really have questions for switching to Google Closure Compiler 
* Does it support IE8?
* is the JS version https://github.com/google/closure-compiler-js equivalent to the main Java version (one forces java to be installed) https://github.com/google/closure-compiler? 
* What will the size difference be?

**Comment by BrandonOCasey** [comment]
Also here is a comparison from 2011 (long ago...) https://www.peterbe.com/plog/comparing-google-closure-with-uglifyjs

**Comment by gkatsev** [comment]
This is the package for the js-only version of closure compiler: https://github.com/google/closure-compiler-js

Also, I'm not sure that particularly sure that those comparisons are going to be that helpful. They're still helpful but they compare GCC's "ADVANCED" mode, which we would *not* be using.

**Comment by heff** [comment]
Anything big we'd be missing out on by locking down Uglify? Otherwise that seems ok to me, and not evaluate each new patch but just wait until there's something new we want from it.

I was hoping there'd be a good Esprima-based minifier by now. Is there?

**Comment by misteroneill** [comment]
@ljharb suggested [babili](https://github.com/babel/babili) in Slack so I'm adding it to the OP.

**Comment by tomByrer** [comment]
I suggest using babili's [benchmark test suite](https://github.com/babel/babili#benchmarks).

**Comment by gkatsev** [comment]
I think for now we should stick with uglify because it works (mostly) and it's better not to change if we can.
