### ISSUE TITLE
controlBar options don't seem to do anything

### ISSUE THREAD

**Issue by wcndave** [videojs/video.js#3638]
## Description
 data-setup='{ "controlBar": { "muteToggle": false } }'>

none of the options for this controlBar element seem to do anything.

http://codepen.io/anon/pen/ALqjZN

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. added in the above for controlBar

### Expected

The mute button removed

### Actual
Nothing was removed

**Comment by misteroneill** [comment]
@wcndave I presume you're looking at [this documentation](http://docs.videojs.com/docs/guides/options.html)? Unfortunately, it's not 100% accurate. While the code does work, the muteToggle component is not included by default; so, that example won't have any effect. We are going to have a big push in Q4 of this year to update all our documentation, so our users hopefully won't encounter this sort of confusion!

[Here's an example](http://jsbin.com/lelivorijo/edit?html,output) I put together just now that demonstrates that type of usage for passing options to child components.

**Comment by gkatsev** [comment]
Also, this page has the default enabled components and whether they're shown by default: https://github.com/videojs/video.js/blob/master/docs/guides/components.md
