### ISSUE TITLE
Unable to access 'click to enable plugin' menu on Chrome

### ISSUE THREAD

**Issue by spodlecki** [videojs/video.js#3641]
## Description

Using `Flash` as a tech, a user that has opted into manually enabling Adobe Flash is unable to access the "Enable Plugin" prompt. This is due to the poster displaying over the video element (`object`). If the poster is hidden (css: `display: none;`) the Enable Plugin feature is displayed properly.

Test Case: https://jsbin.com/kopoqewifo/edit?html,js,output
**Note regarding the test case -- You'll want to run it somewhere else. JS Bin and Fiddle do not like running the SWF File.**
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1. Open Chrome (OS won't matter) and navigate to [chrome://plugins/](chrome://plugins/)
2. Find Adobe Flash Player and uncheck "Always Allowed to Run"
3. Restart Browser
4. Visit the [test case](https://jsbin.com/kopoqewifo/edit?html,js,output) and attempt to play the video
### Expected

The desired result would simply be to display the native browser feature. If a user has this option on, the box would display to enable. Once enabled, the video player would act as normal.
### Actual

The poster displays over the disabled flash object and is unable to take any action.
### Error output

N/A
## Additional Information

A simple solution is to have the Video JS SWF create a simple JavaScript callback to videojs.

When the Flash SWF is loaded, it can send out a call to say, `videojs.hasFlashAvailable = true;`
After a specific time limit, if the value isn't `true` then we can assume that flash is disabled and take proper action(s). The easiest solution was to just disable the poster.
### versions

videojs: 5+
#### browsers

Any browser that has the capability to disable Flash and enable for specific objects

**Comment by spodlecki** [comment]
I've side stepped this by writing a simple plugin:

### CoffeeScript
```coffeescript
FlashDisabledDetection = (config)->
  player = @

  timer = setInterval(->
    if player.techName_
      if player.techName_.toLowerCase() == 'flash'
        poster = player.el().querySelector(".vjs-poster")
        if poster
          poster.style.display = 'none'
          player.on('ready', ->
            poster.style.display = null
          )

      clearInterval(timer)
  , 200)

module.exports = FlashDisabledDetection
```

If you guys have a better way of handling this, let me know. I'm using `techName_`, but from the look of the var, I'm not sure that I should. Maybe I should be disabling controls? There is a play button by default that is on there too, but it doesn't block the enabling of the plugin.

**Comment by gkatsev** [comment]
You can try seeing whether the `player.$('.vjs-tech')` returns an `object` element or a `video` element.
We'll take a look to see if we can easily do something about it.

**Comment by spodlecki** [comment]
Updated the script I'm using, that feels much better. I did a bit of a google and it seems this is basically what people are doing to detect if adobe flash has been disabled.

It's essentially adding an event to fire from SWF. If the SWF doesn't fire the event, it's disabled.

**Comment by gkatsev** [comment]
Looks like adding a `pointer-events: none` css property does help (you are then able to right-click to enable the swf) but you still don't know that you need to do that.
I wonder if we just need to do something like the above in core/ the flash tech? If so, how long should we wait before hiding the poster? 200ms is most likely too short but is something like 5 seconds too long?

**Comment by spodlecki** [comment]
I think 5s would be too long; the average person spends ~20s on an entire page with the majority dropping off in less than 10s -- so I'm not sure 50% of that should have the user possibly confused.

Why do you feel that 200ms is too short? I'd aim for at least something around 1s imho.

Love the CSS! Didn't even think about that.

**Comment by gkatsev** [comment]
Because if someone is loading the swf from their own server or is far away from the videojs CDN, the swf could take a while to load and we don't want the poster to be hidden if the swf loaded successfully and re-showing the poster after hiding it would be worse user experience.

**Comment by spodlecki** [comment]
I see, but the user can't take any action without the flash player being ready, right? If that is the case, I'd argue the opposite.

Being given a Poster Image along with a Play button indicates that I'd be ready to consume media. If the SWF has not been loaded yet due to connection issues, clicking the Play Icon would confuse me as nothing would happen.

----

However, if we pressed play with the SWF still loading, does the spinner icon display? If this is true, then that would make more sense that it is disruptive. I think you'd be able to gather some CDN data for average response times and go from there.

**Comment by spodlecki** [comment]
considering Flash is not part of this repo any longer... should we simply close the issue?

**Comment by gkatsev** [comment]
I think that makes sense. Maybe move the issue to the videojs-flash repo?

**Comment by gkatsev** [comment]
I'm going to close this. Feel free to re-open against the videojs-flash repo.
