### ISSUE TITLE
Fix style `MouseTimeDisplay`

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#3645]
## Description

When hovering over the `ProgressControl` the `MouseTimeDisplay` activates outside of the expected boundary of the `SeekBar`.

I suspect it has to do with `margin: 0 0.45em 0 0.45em;` identified in https://github.com/videojs/video.js/blob/master/src/css/components/_slider.scss#L6 and possibly how parent element calculates the `MouseTimeDisplay`?
## Steps to reproduce
1. Go to http://videojs.com/
2. Play video
3. Attempt to hover to the edges of the `SeekBar`
### Expected

For the `MouseTimeDisplay` to be bound by the `SeekBar`.
### Actual

![image](https://cloud.githubusercontent.com/assets/549319/18855683/8c49429a-8409-11e6-9ae1-cebde7679f51.png)
## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs

`5.11.6`
#### browsers
- `Chrome`
- `Firefox`
- `Safari`
#### OSes

OSX `10.11.5`

**Comment by chemoish** [comment]
Possibly, easy, but naive fix would be to update the `ProgressControl` to have the `margin` instead.

**Comment by gkatsev** [comment]
Huh, oops. Also, I'm thinking when we do a new major release for videojs we make the "keepToolstipsInside" option on the progress control be the default and only option, which, I think would also fix this issue.
