### ISSUE TITLE
Ios multiple audio tracks are not shown when calling .audioTracks()

### ISSUE THREAD

**Issue by Prendo93** [videojs/video.js#3647]
## Description
When calling .audioTracks() on ios, an empty AudioTrackList is returned

If you have access to safari and a dev iphone
http://jsbin.com/wihufemuno

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Inspect a Safari tab running the demo above
2. Run player.audioTracks() from the console
3. Repeat above in safari to see correct output

### Expected
Should see 3 audio tracks
 - This is true in safari, note you will get CORS errors in Chrome

### Actual
See 0 audio tracks

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.11.0
####video-contrib-hls
3.4.0
#### browsers
ios browsers
#### OSes
ios
### plugins
video-contrib-hls as above

**Comment by imbcmdth** [comment]
The audioTrackList is populated by the browser asynchronously. You should be listening for the `addtrack` and `removetrack` events. 

Try replacing the `setTimeout` with:
```js
 player.audioTracks().addEventListener('addtrack', function() {
    console.log(player.audioTracks().length);
  });
``` 

See: http://jsbin.com/gokelusuza/edit?html,console,output

**Comment by mohamedaasif** [comment]
Any updates on this issue ? I am facing the same problem but in android it's working.

**Comment by gkatsev** [comment]
Please open a new issue with as detailed information as you can. Ideally with a live minimal test case.

**Comment by mohamedaasif** [comment]
> Please open a new issue with as detailed information as you can. Ideally with a live minimal test case.
Yes, created a new issue. please check
https://github.com/videojs/video.js/issues/7467#issue-1015855287
