### ISSUE TITLE
Playing video by remote link, Reference header in GET request

### ISSUE THREAD

**Issue by koinas** [videojs/video.js#3649]
Hello everyone,
I'm trying to play video by the link on it to external server. It does not playing. When i open the link in the browser the download starts.So it't not the video problem.
I have compared the HHTP traffic when i place link in browser with video.js and found out thet video.js adds a Reference header into GET request. There is a my local IP there so that is the problem.
Browser does not add any Reference headers. Is there any way to remove it?
There was a question about the same problem here and it was stated that video.js does not sends any GET requests by itself. It can be browser or flash player. But as i stated above there is no Reference header when i enter link directly into browser so it must be somewhere else. What part of video.js library do i need to check?
Thanks,

**Comment by gkatsev** [comment]
Trying it out locally in chrome, I see the exact same headers both in chrome dev tools and when running charles. As stated in other issues you've looked at, videojs does nothing extra (and really, cannot do anything extra) if we're just playing back an mp4 in the native video element.
Unfortunately, without a concrete example we cannot help out any further.

**Comment by koinas** [comment]
Hello and thanks for reply. For some links i see these headers:

X-Requested-With: ShockwaveFlash/22.0.0.209
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Accept: */*
Referer: http://192.168.1.100/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: S2SIDCDNSITE=25dd9fccd4956eafb3c4995b0578db04

So Shockwave player is involved here somehow. 
I want to debug the library to understand what is going on.
I'm new to web programming but have a lot experience with C++.
What instruments do i need to debug the library?

**Comment by koinas** [comment]
I doesn't look that video is playing. OK. I will try to exam what is going on.

**Comment by gkatsev** [comment]
Closing this issue because it's unlikely to require a change to videojs itself. However, we can still continue the discussion here and if it turns out to actually be an issue with videojs, we can re-open the issue.
