### ISSUE TITLE
Handle play and pause event and prevent their default actions

### ISSUE THREAD

**Issue by gfiore88** [videojs/video.js#3651]
Hi guys, I'd like to handle the play and pause events and prevent their default actions (play video / pause video). 

In this way I would lock the default event immediately and activate it maybe later, when some other conditions are verified and maybe from another function through the play() method invoked on videojs object

Here an example:

```
vjs.on("play", function (e) {
e.preventDefault(); //NOT WORKING, ONLY AN EXAMPLE
//do something else...
});
```

```
function example(){
vjs.play();
}
```

**Comment by gfiore88** [comment]
Any idea?

**Comment by gkatsev** [comment]
Unfortunately, the only thing you can do right now is pause the player when you get a play event and then play it at a later point.

**Comment by simpleauthority** [comment]
I don't see that this has ever been implemented, but the need is great. Playing/pausing in the event is faulty, when you have both a play/pause handler.

Player is played and manually paused in handler; pause handler is called and player is played.

Now we've started a loop. Can we just get some event cancellation in this? Thanks.
