### ISSUE TITLE
Spinner hides before video has loaded and can play.

### ISSUE THREAD

**Issue by floorish** [videojs/video.js#3653]
## Description
On a slow connection it can take a while to load the video, but the spinner is hidden before the video is loaded and the `canplay` event is fired. This means the spinner is hidden too soon and the user gets no feedback about what's going on. Only a black screen is visible while loading.

## Steps to reproduce
1. Open http://jsfiddle.net/floorish/gvu1rwdr/ in Chrome
2. Set Network throttling to something low (GPRS)
3. (make sure the video is not cached)
4. Click play on the video

### Expected
Spinner shows until video is ready to play (after `canplay` event fired)

### Actual
Spinner hides after first `timeupdate` event, but video is still buffering so a black screen is visible.

## Additional Information
What happens is when the video enters `waiting`, the spinner is hidden after the first `timeupdate` event. See  https://github.com/videojs/video.js/pull/3138  ,  https://github.com/videojs/video.js/blob/master/src/js/player.js#L908.
The `timeupdate` event is fired even though the video is buffering/loading (Might be connected to this issue: https://github.com/videojs/video.js/issues/1641), which shouldn't happen. 

#### videojs
5.11.6
#### browsers
Tested on Chrome 53 with network throttling enabled. Also reproducible on iPad with slow connection.
#### OSes
macOS
### plugins
none

**Comment by misteroneill** [comment]
I can verify this behavior per your instructions - thanks for the detailed test case!

I'm not sure what the best path forward here would be. Perhaps we could track whether we've seen `canplay` for the current source and only add the one-off `timeupdate` listener if we have seen `canplay`?

**Comment by floorish** [comment]
Yes, I think that would be an option.

Although I'm wondering why the `timeupdate` events are fired anyway. They're not fired by the browser, but manually by videojs: https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js#L224 , which is called on `play` here: https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js#L198

I'm not too familiar with the code so there's probably a good reason for this, but if I compare to the native video events API  the `timeupdate` events are not fired before `canplay`.
See for example: http://jsfiddle.net/floorish/yajp71pc/2/
(Again enable Network throttling)

--- 

Tracing back further I noticed that the manual `timeupdate` events are fired because `featuresTimeupdateEvents` is always false, see: https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js#L79-L81  and  https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js#L679 . Probably to keep it consistent across browsers?

**Comment by gkatsev** [comment]
That `manualTimeUpdates` should only be used for things like Flash. It looks like we disable the progress events but not the time events in the html5 tech (https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L1290-L1294). So, potentially, the fix would just be to add `Html5.prototype.featuresTimeupdateEvents = true` to the html5 tech.

**Comment by floorish** [comment]
@gkatsev Yep, looks like that solves the issue!

**Comment by gkatsev** [comment]
Oh, cool. Would you be interested in submitting a PR for this change? Would just want to follow how [`featuresProgressEvents`](https://github.com/videojs/video.js/blob/e479f8c34ce0831778c5a87b8d0537830072cdef/src/js/tech/html5.js#L914-L918) looks but for `featuresTimeupdateEvents`.

**Comment by floorish** [comment]
Sure, I'll try to not break everything :)

**Comment by misteroneill** [comment]
Weird, I had no idea we were firing synthetic `timeupdate` events for HTML 5 - thought it was a Flash-only thing!

**Comment by gkatsev** [comment]
Fixed by #3656
