### ISSUE TITLE
Issues scrubbing or clicking in the timeline with Flash plugin

### ISSUE THREAD

**Issue by BCjwhisenant** [videojs/video.js#366]
Found during an exploratory test pass with Windows 7, IE9, Flash 11.6.602.171 and Firefox 14, Flash 11.2.202.233.

STR:
1. Copy index.html.example to index.html
2. Load the page in IE9 or Firefox.  Use the ?flash URL parameter to load the Flash plugin.
3. Start playing the sample video.
4. After the video starts playing, scrub into a part of the video that's already buffered.
5. Another test is to click somewhere in the timeline where the video has already buffered.

Expected:
The scrub is smooth.
Whether scrubbing or clicking, the playhead lands where the mouse pointer is (or at least very close to it - understood if the plugin is seeking to the nearest keyframe).

Actual:
The scrub is very jittery, in that the scrubber does not follow the mouse pointer closely at all.
Whether scrubbing or clicking, the playhead lands at a point well away (as in, seconds away) from where the mouse pointer is located.

I've also seen this behavior using a local, high-quality MP4 test video.

**Comment by gkatsev** [comment]
I think this may have been fixed and addressed by now. Also, there's some scrubbing related work that I want to do which will be going on the roadmap I'm working on. Going to close this in favor of that.
