### ISSUE TITLE
es5 build calls document.createElement unchecked

### ISSUE THREAD

**Issue by ljharb** [videojs/video.js#3665]
The es5 build contains this JS:
```js
// HTML5 Element Shim for IE8
if (typeof HTMLVideoElement === 'undefined') {
   _document2['default'].createElement('video');
   _document2['default'].createElement('audio');
   _document2['default'].createElement('track');
}
```

In node, `HTMLVideoElement` does not exist, but neither does `document.createElement`.

Can this also check `_document2['default'].createElement` before trying to call it?

**Comment by gkatsev** [comment]
Potential fix here: https://github.com/videojs/video.js/pull/3706
