### ISSUE TITLE
Provide basic responsive theme

### ISSUE THREAD

**Issue by klodeckl** [videojs/video.js#3666]
The default theme is not responsive, the video is not downsized. Please provide a basic theme which is responsive (like the one on http://videojs.com), otherwise changes to make it responsive have to be adopted for every version.

**Comment by gkatsev** [comment]
The responsive theme on videojs.com is just the standard theme with the `fluid` option set.
Not everyone wants a fluid theme like that, so, it's still not a default; plus it was added as a feature in 5.x, so, we couldn't turn on this option without potentially breaking users of videojs.
Also, once https://github.com/videojs/video.js/pull/3614 is merged, just adding `vjs-fluid` class will also indicate that you want the player to be fluid.

Unfortunately, currently, the best documentation of `fluid` mode is [this blogpost](http://blog.videojs.com/Video-js-5-s-fluid-mode-and-playlist-picker/#How-to-use-it-in-video-js).

Hope that helps.
