### ISSUE TITLE
Problems running videojs in an iframe using Safari.

### ISSUE THREAD

**Issue by Ljugoboss** [videojs/video.js#3667]
I'm currently having problem running video.js inside of an iframe using Safari version 10.0 and in Safari in IOS 10.0.1. 
I'm running video.js version 5.11.6.
This seems to be related to issue [#2703](https://github.com/videojs/video.js/issues/2703)

The error I'm getting is:

```
Blocked a frame with origin "http://localhost:8081" from accessing a frame with origin "http://localhost:8080". Protocols, domains, and ports must match.
```

This code causes the problem:

```
var hasAutomationEqualityBug = (function () {
    /* global window */
    if (typeof window === 'undefined') { return false; }
    for (var k in window) {
        try {
            if (!excludedKeys['$' + k] && has.call(window, k) && window[k] !== null && typeof window[k] === 'object') {
                try {
                    equalsConstructorPrototype(window[k]);
                } catch (e) {
                    return true;
                }
            }
        } catch (e) {
            return true;
        }
    }
    return false;
}());
```

It is working fine outside of an iframe and it is working fine inside of an iframe in Chrome, Firefox and Opera.

**Comment by misteroneill** [comment]
I wonder if this is a regression in `object.assign`? cc @ljharb

**Comment by ljharb** [comment]
That code hasn't changed in awhile, so it might be something new in Safari 10.

@Ljugoboss can you provide a jsfiddle that reproduces the problem? If not I can still give it a shot, but it'd speed things up considerably.

**Comment by gkatsev** [comment]
That's apparently a very old version of videojs (5.0.2), it should be fine with a newer version like 5.11.7.

**Comment by Ljugoboss** [comment]
Updated the [jsfiddle](http://jsfiddle.net/xL6xoxgj/4/) embedding [videojs.com](http://videojs.com/). It throws the same error. I am also getting the same error embedding [videojs.com/advanced/](http://videojs.com/advanced/). 
I'm assuming those are running version 5.11.7 as that is what is advertised over the player on that site.

**Comment by ralcar** [comment]
@gkatsev any idea what could cause this? Having the same issue

**Comment by ljharb** [comment]
@ralcar with what version of video.js?

**Comment by ralcar** [comment]
@ljharb currently this is my dependencies in package.json, after trying to run the latest on everything:

```
"video.js": "^5.12.3",
"videojs-contrib-dash": "^2.5.1",
 "videojs-contrib-hls": "^3.6.0"
```

My applications is doning everything in react/redux, importing like this:
```
import * as $videojs from 'video.js';
import dash from 'bundle?lazy&name=dash!videojs-contrib-dash'; // eslint-disable-line
import hls from 'bundle?lazy&name=hls!videojs-contrib-hls'; // eslint-disable-line
```

I have tried to load the videojs in all different kind of ways, this is just version #53 that gives me the same result:
(using Recompose to setup)
```
withState('videojs', 'setVideojs', () => {
    const video = document.createElement('video');
    video.setAttribute('webkit-playsinline', '');
    const options = { hls: {
      withCredentials: true,
    } };
    return $videojs.default(video, { flash: options, html5: options });
  })
```

and the component looks like this (sorry for not cleaning up before pasting, this is a test component):
```
class SimpleVideojs extends Component {
  static propTypes = {
    className: PropTypes.string,
    videojs: PropTypes.object,
  };
  componentDidMount() {
    const { videojs } = this.props;
    const videoElement = videojs.tech({ IWillNotUseThisInPlugins: true }).el();
    this.videoElement = videoElement;
    videoElement.classList.add('videojs__video');
    this.element.appendChild(videoElement);
  }
  render() {
    const {
      className,
      ...props, // eslint-disable-line no-unused-vars
    } = this.props;
    const inner = (<div
      className={classnames('videojs', className)}
      ref={ref => (this.element = ref)}
    />);
    return inner;
  }
}
```

But the jsfiddle that @Ljugoboss created seems to give this error regardless of implementation, with the latest videojs.

**Comment by misteroneill** [comment]
As mentioned above, it's probably related to a new window property that Safari is protecting, but the `object.assign` package isn't aware of (yet). 

I don't think it actually causes execution to stop or anything, does it? It simply logs an error, right?

**Comment by ralcar** [comment]
@misteroneill I have tried on a iPad running safari 9.x and a iPhone 7 running IOS10/Safari10. Right now it stops it seems. If anyone has a correct way/example of loading videojs/videojs-contrib-hls in react, and loading a hls stream into that player, it would be great to  see so that im not doing silly stuff.

**Comment by misteroneill** [comment]
Ok, if it stops, that's a bigger problem. I was pretty sure I'd seen it on desktop, but not seen it stop.

**Comment by gkatsev** [comment]
For better or worse, we've also removed object.assign in videojs 5.14, so, I think this is no longer an issue.
