### ISSUE TITLE
Support full screen api in Internet Explorer

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#3673]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. GO to a video in Internet Explorer

### Expected
I expect full screen to show when I click full screen.

### Actual
I see that it only covers half the screen.

### Error output
Nope

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.12.2
#### browsers
Internet Explorer
#### OSes
Windows 10.
### plugins
videojs-ogvjs

**Comment by paladox** [comment]
See https://msdn.microsoft.com/en-us/library/dn265028(v=vs.85).aspx

Internet explorer prefixes fullscreen api when Microsoft Edge dosen't

**Comment by paladox** [comment]
http://caniuse.com/#feat=fullscreen

so we need to add ms infront of full screen api code, so we should detect If we use Internet Explorer and use the prefix version of full screen and then fallback to the normal full screen code if we use other supported browsers that doint need prefixing it.

**Comment by gkatsev** [comment]
We do [support it](https://github.com/videojs/video.js/blob/d6e49a4095a2824a02acceec16fb53ab336fc96d/src/js/fullscreen-api.js#L52-L61), though, only [IE11](http://caniuse.com/#search=fullscreen) supports the fullscreen API from the IEs.
On older versions of IE, videojs should default to the "full window" mode.

**Comment by paladox** [comment]
Oh, using videojs-ogvjs this isen't working on Internet Explorer, with patch https://github.com/hartman/videojs-ogvjs/commit/882dcf34735330b08b2befe598de760ee18bf6e1 and set it to true.

**Comment by paladox** [comment]
I can also reproduce it on http://videojs.com/

**Comment by paladox** [comment]
The full screen goes behind the task bar.

**Comment by paladox** [comment]
@gkatsev 

https://github.com/videojs/video.js/blob/3a859f97d0647fc3d1ef6b2f4b755c71da8bef63/src/js/control-bar/fullscreen-toggle.js#L17 doesn't use the prefixed one too

https://github.com/videojs/video.js/blob/3a859f97d0647fc3d1ef6b2f4b755c71da8bef63/src/js/tracks/text-track-display.js#L86

https://github.com/videojs/video.js/blob/920c54a65cf614618bdf91aa0c57ca9f27ffac7f/src/js/tech/html5.js#L454

https://github.com/videojs/video.js/blob/ae3e27788db2ad2386f7194ffd2ac1aa9321f74e/src/js/player.js#L319

https://github.com/videojs/video.js/blob/ae3e27788db2ad2386f7194ffd2ac1aa9321f74e/src/js/player.js#L714

**Comment by paladox** [comment]
https://github.com/videojs/video.js/blob/ae3e27788db2ad2386f7194ffd2ac1aa9321f74e/src/js/player.js#L1589

**Comment by gkatsev** [comment]
All of those use our [fullscreen api shim](https://github.com/videojs/video.js/blob/d6e49a4095a2824a02acceec16fb53ab336fc96d/src/js/fullscreen-api.js) which I linked above.

**Comment by paladox** [comment]
Oh

**Comment by paladox** [comment]
![screenshot 16](https://cloud.githubusercontent.com/assets/5727000/19198228/ecc73794-8cb5-11e6-8c73-5a12e7ecbcf9.png)

This is what it looks like on videojs website on internet explorer 11.

**Comment by gkatsev** [comment]
That might be a browser/OS issue. I sometimes see that with native video players as well, like VLC.

**Comment by paladox** [comment]
Oh

**Comment by paladox** [comment]
Hi yes it's fixed now in windows 10 build 14342
