### ISSUE TITLE
Distinguishing between Player and ControlBar clicks

### ISSUE THREAD

**Issue by PB314** [videojs/video.js#3680]
It does not appear to be possible to distinguish between controlBar and Player clicks.   This means that when dragging the video container there appears to be no way to avoid stopping and starting the player as the _mouseup_ and _mousedown_ events are triggered.

**Comment by gkatsev** [comment]
You should be able to differentiate between them by looking at the `target` property of the event object passed to the event handler.
```js
player.on('mouseup', function(evt) {
  console.log(evt.target);
});
```

Hope that helps.
