### ISSUE TITLE
Loading "Gruntfile.js" tasks...ERROR

### ISSUE THREAD

**Issue by kevgithub** [videojs/video.js#3683]
<img width="438" alt="screen shot 2016-10-14 at 16 31 09" src="https://cloud.githubusercontent.com/assets/813641/19380918/02185ba2-922c-11e6-8df9-bfbdea66c570.png">

I tried to install the "conventional-changelog" but still not work.

**Comment by gkatsev** [comment]
Are you running grunt from the build folder? You should be running it from the root of the project. I'm guessing that the issue is that shelljs-nodecli is not handling that correctly.

**Comment by kevgithub** [comment]
Yes I ran it from the root

**Comment by misteroneill** [comment]
Yes, `shelljs-nodecli` is not seeing binaries in `node_modules/.bin`. I'll see what I can do about fixing it.

**Comment by misteroneill** [comment]
@kevgithub For the time being, if you `npm install -g conventional-changelog-cli`, the build will work.

**Comment by BernardoFBBraga** [comment]
@misteroneill I have the same issue but your suggestion did not work for me

@kevgithub did it work for you?

**Comment by BernardoFBBraga** [comment]
@misteroneill I copied the modifications from your commit #3687 and the grunt command now works (after running "npm install npm-run")
at the end it says it "Done, without errors", although I saw some stack traces so I don't feel very confident. Here is the output http://pastebin.com/F3KbARDz

**Comment by misteroneill** [comment]
@BernardoFBBraga Thanks for checking.

That output looks like #3692 to me - I don't think there's a good solution to it at the moment. 😕

**Comment by gkatsev** [comment]
Yeah, the current solution is, unfortunately, to not use macos sierra (or remove the style generation from the build and use the pre-built styles).

**Comment by BernardoFBBraga** [comment]
@gkatsev I am runnin El Capitain 10.11.6
If you need any testing on my setup let me know

**Comment by gkatsev** [comment]
Oh, actually, you're right. I was too quick. Looks like your error isn't with sass but with fs-events. #3692 is a sass-related issue. I wonder what's up with fs-events.

@BernardoFBBraga what version of node and npm are you using?

**Comment by gkatsev** [comment]
Looks like it might be an issue with node 6.

**Comment by BernardoFBBraga** [comment]
@gkatsev 
npm version 3.10.8
node version 6.8.1
I tried uninstalling everything following this stackoverflow post : http://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally

and now I'm currently trying to make the grunt work again. Maybe since my pc was freshly formatted and didn't have some stuff installed (such as xcode) I ran into some unexpected scenario
