### ISSUE TITLE
keyboard accessible and ADA compliant ?

### ISSUE THREAD

**Issue by vinothvk** [videojs/video.js#3688]
Hello

Sorry for posting a question in this area rather an issue. I am not sure whether a forum exists for Video JS.

may i know whether the player is keyboard accessible & ADA compliant ? also like to knoww whether the framework is extensible, if some of the accessibility needs are not met. Thanks

**Comment by gkatsev** [comment]
We try to make it as accessible as we can - it definitely works with the keyboard and screen readers - but there's definitely a lot more work to be done. It is extensible and we would love help to fix any shortcomings we have with regards to accessibility.
I'm not sure about ADA compliance. Maybe @owenedwards can talk to that some more.

**Comment by OwenEdwards** [comment]
@vinothvk we've put a lot of work into making video.js accessible, referring particularly to WCAG 2.0 Levels A and AA (with some consideration of Section 508 and the Revised Section 508 requirements). "ADA" requirements are generally interpreted as being WCAG 2.0 Levels A and AA, although there isn't any concrete regulatory definition of that, only case law.

Generally speaking, we support captions and audio description, and the player itself is designed to be accessible for keyboard-only users, screen reader users, and users of other assistive technology like Dragon NaturallySpeaking, ZoomText, etc.

Having said that, we don't make any specific claims about compliance/conformance with WCAG; video.js is open-source, and changes rapidly; also, any worthwhile WCAG Conformance Statement would come from a third-party, which costs money (full disclosure, my day job is with [Level Access](https://www.levelaccess.com/) where we do that kind of work).

So we would encourage anyone looking at using video.js who is covered by accessibility requirements/regulations (ADA, WCAG, Section 508, AODA, etc.) to consult with their regulatory compliance office/officer, and decide whether they need to retain outside help to establish whether their whole site (including video.js) complies with those regulations.

At the same time, if users of video.js or websites which include it encounter accessibility issues or barriers, they should file an issue in this GitHub repo. Known accessibility issues can be found at https://github.com/videojs/video.js/issues?q=is%3Aissue+is%3Aopen+label%3Aa11y

(I'm also obliged to add that I'm not a lawyer, and none of this constitutes legal advice :-) )
