### ISSUE TITLE
Audio Live Stream

### ISSUE THREAD

**Issue by frequeradio** [videojs/video.js#3696]
Hello

I understood that video.js is mainly to stream video files, i was wondering if it's also a good player for live audio streaming ? 
I saw that it supports the audio tag but i'm not sure if it's compatible with streams from icecast / shoutcast servers

thanks

**Comment by samueleastdev** [comment]
Hi @frequeradio,

We would also live to know about this we use video js as our audio player using hls .m3u8 format bottom of the page here. https://s3bubble.com

I have always had issues trying to setup audio streaming in the past do you or anyone know where i could get hold of a demo url to test with cause i want to look into this?

We are using video js hls contributor i assume audio streaming is in .m3u8 format?

**Comment by gkatsev** [comment]
You can actually use the audio and video tags interchangeably.
As for icecast support, I'm not sure. It seems like it potentially works but different browsers support different audio codecs so you can't just stream an mp3 and get all browsers.
HLS works great for streaming and you can even use [contrib-hls](https://github.com/videojs/videojs-contrib-hls) to get it to work on desktop browsers.

Hope that helps.
