### ISSUE TITLE
In IE8 can't see control buttons

### ISSUE THREAD

**Issue by chengang0621** [videojs/video.js#3697]
why In IE8 can't see control buttons，but when mouse over can see tootip and can operate.
![qq 20161020224553](https://cloud.githubusercontent.com/assets/17420002/19564698/0136ac6c-9717-11e6-9e15-f06de16d5929.png)

**Comment by misteroneill** [comment]
Hmm, this does appear to be broken in IE8. http://output.jsbin.com/nokiqeh

**Comment by cucygh** [comment]
[webfontloader](https://github.com/typekit/webfontloader) can solve icon issue in ie8

**Comment by vagari** [comment]
Has this particular bug been fixed? I do not see any issues loading that jsbin. I read the title and thought it might be a similar issue to #3999. I fixed missing control icons in IE8 by making sure the font file that contains the icons was properly pointed to. Check line 11 (in the un-minified version at least).

`@font-face {
  font-family: VideoJS;
  src: url("font/VideoJS.eot?#iefix") format("eot"); }`

**Comment by gkatsev** [comment]
I believe this has been fixed. If it's still an issue, let us know and we can re-open this issue.
