### ISSUE TITLE
videojs player crashes when switching from flash to hls

### ISSUE THREAD

**Issue by Kannaj** [videojs/video.js#3702]
Sorry for not using the prescribed template. but i'm not sure if this is a bug or me going wrong somewhere

I'm building a streaming app which supports flash, hls and html5 dash

```

    this.src = [
      {type: 'rtmp/mp4', src: `**/live/${this.props.stream.id}`},
      {type: 'application/x-mpegURL', src: `**/live/${this.props.stream.id}/playlist.m3u8`},
      {type: 'application/dash+xml', src: `**/live/${this.props.stream.id}/manifest.mpd`},
    ];

```

I've also included an option to switch between techs inbetween streams. switching works fine in all cases unless its from flash to hls in which case it looks like the flash player crashes and no video is played until i refresh the page. my code is

```
        if(newType === 'rtmp/mp4'){
          console.log(player.tech({ IWillNotUseThisInPlugins : true }))
          player.play()
        }else if (newType === 'application/x-mpegURL') {
          player.play()
          console.log(player.tech({ IWillNotUseThisInPlugins : true }))
        }else{
          console.log(player.tech({ IWillNotUseThisInPlugins : true }))
          console.log('src  : ',player.currentType())
          player.pause()
        }
```

I can switch quite seamlessly from flash -> html Dash -> hls without no errors

When switching to `hls` from flash - `player.tech` in the console reveals that the the tech used is still Flash which seems to tell me that that the player has crashed.

However , there seems to be no error raised in the console. 

Please let me know how i can correct this.

Thanks,

**Comment by gkatsev** [comment]
I think this has been fixed in latest version of all the plugins and Video.js. Please re-test and if it's still an issue, please open a new issue, if possible, with a reduced test case.
Thanks.
