### ISSUE TITLE
Uglify does not work

### ISSUE THREAD

**Issue by doublex** [videojs/video.js#3707]
CDN is fine, but the "video.min.js" from "video-js-5.11.7.zip" and newer is not properly minified:
filesize `5.11.6`: 281 kb
filesize `5.11.7+`: 494 kb

**Comment by gkatsev** [comment]
Looking at it, it's minifying it just fine but for some reason comments are still preserved.

**Comment by gkatsev** [comment]
Looks like what `preserveComments` does in uglify changed.

**Comment by gkatsev** [comment]
Potential fix: https://github.com/videojs/video.js/pull/3709

**Comment by gkatsev** [comment]
Fixed by #3709.

**Comment by gkatsev** [comment]
Fixed in 5.11.9.
