### ISSUE TITLE
the media could not be loaded

### ISSUE THREAD

**Issue by hachihub** [videojs/video.js#3712]
iphone Safari has error:the media could not be loaded,either because the server network failed or because the format is not supported,

windows Safari OK

**Comment by hartman** [comment]
Does your media adhere to the set of media supported by iOS ?
https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/MediaLayer/MediaLayer.html#//apple_ref/doc/uid/TP40007898-CH9-SW6

Mobile phones use hardware decoding, so you can only use media that is supported by the device's hardware, a comparison with Windows is therefor useless.

**Comment by hachihub** [comment]
Soryy,Solved the problem.According to the firewall.It deny video
