### ISSUE TITLE
the screen is black

### ISSUE THREAD

**Issue by hachihub** [videojs/video.js#3716]
Hi , I use chrome, can hear the sound but the screen is black.

**Comment by gkatsev** [comment]
Unfortunately, we cannot help if you don't answer the questions in the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by tanuu** [comment]
I see "videojs" in the source of this page:
http://www.independent.co.uk/news/world/americas/the-inside-story-of-the-drug-overdose-photograph-that-shocked-the-world-ohio-heroin-east-liverpool-a7383896.html
(looks familiar)
On Windows 7 in Chrome 54, the video plays normally, in Firefox 49 audio is OK, but no video (black) - see screenshot. FF running Adblock, but disactivated for independent.co.uk.
![ff-49-videojs](https://cloud.githubusercontent.com/assets/8893700/19784470/377cd61e-9c96-11e6-8f31-e57261464afa.png)

**Comment by misteroneill** [comment]
That independent.co.uk is working for me in Firefox in Private Mode on OS X. I can try on Windows when I have access to it.

**Comment by boushley** [comment]
Given the lack of details I think we're good to close this issue. It can be reopened if more details come to light.
