### ISSUE TITLE
Multiple Audio Tracks not working with videojs-dashjs

### ISSUE THREAD

**Issue by architsinha** [videojs/video.js#3717]
## Description

I am using dash.js with video.js (along with videojs-contrib-dash). I tried playing a stream which has multiple audio tracks. I was able to play the stream but I did not find any option to select/change the audio track and therefore the default audio track keeps playing throughout. When I tested the same stream on the dash-if reference player, it worked fine and I could switch between the different audio track.

Is this a known issue, or is there something wrong in the way I am using video.js(with dash.js)?
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.
1. Include video.js, dash.js and videojs-dash.js in the index.html file in that order.
2. Play the following video: http://dash.akamaized.net/dash264/TestCases/10a/1/iis_forest_short_poem_multi_lang_480p_single_adapt_aaclc_sidx.mpd
   The video will play but there is no option to switch between audio tracks
3. You can verfiy the video by playing it on the dash-if reference player present at: http://dashif.org/reference/players/javascript/v2.3.0/samples/dash-if-reference-player/index.html
   It plays the video and gives option to switch between the two audio tracks( english and german)
### Expected

User should be able to switch between the different Audio Tracks
### Actual

There is no option to switch between the different Audio Tracks
### Error output

None
### versions

Videojs version --- 5.10.7
dashjs version ---- 2.3.0
videojs-contrib-dash version --- 2.4.0
#### browsers

I tested on chrome version 54.0.2840.71
#### OSes

I tested on Windows 7 
### plugins

Yes, videojs-contrib-dash is being used.

**Comment by forbesjo** [comment]
videojs-contrib-hls needs to be updated to add the tracks from the dashjs mediaplayer to the video.js player, it wont automatically pick them up. Could you open this issue in videojs-contrib-hls? Thanks

**Comment by gkatsev** [comment]
Please re-open this issue against [videojs-contrib-dash](https://github.com/videojs/videojs-contrib-dash/issues/new) if it's still an issue.
