### ISSUE TITLE
[Feature request] Integration with Bilibili/flv.js for FLV playback and livestream

### ISSUE THREAD

**Issue by m13253** [videojs/video.js#3719]
https://github.com/bilibili/flv.js is a new JavaScript library to play and stream FLV videos.

It supports:
- FLV container with H.264 + AAC codec playback
- Multipart segmented video playback
- HTTP FLV low latency live stream playback
- FLV over WebSocket live stream playback
- Compatible with Chrome, FireFox, Safari 10, IE11 and Edge
- Extermely low overhead, and hardware accelerated by your browser

I hope flv.js can integrate with video.js to provide native FLV playback without the support of Flash.

Also, HTTP FLV live stream provides much lower latency than HLS or DASH, and is chosen by many leading livestream sites (at least in China, e.g. Bilibili.com, Douyu.tv, Panda.tv). By integrating with flv.js can we provide lower latency stream with pure HTML5.

I am ready to help with the integration.

**Comment by gkatsev** [comment]
flvjs sounds like an interesting project. Unfortunately, we don't have the bandwidth to write and support a videojs Tech or a videojs Source Handler for flvjs. However, we'd encourage you or the community to write one. There's videojs-contrib-hls which is a videojs source handler for hls playback that could be used for inspiration, as well as community projects like [videojs-hlsjs](https://github.com/benjipott/videojs-hlsjs) and https://github.com/Peer5/videojs-contrib-hls.js/

If someone wants to take a stab at it, we'd be happy to help over in our [slack channel](http://slack.videojs.com).
