### ISSUE TITLE
Play FLV in HTML5 Player

### ISSUE THREAD

**Issue by 872517414** [videojs/video.js#3723]
https://github.com/Bilibili/flv.js
An HTML5 Flash Video (FLV) Player written in pure JavaScript without Flash. LONG LIVE FLV!
This project, inspired by hls.js, relies on Media Source Extensions to work.

**Comment by mister-ben** [comment]
I'm not personally convinced FLV will be around that much longer, but regardless if you're looking to integrate flv.js with video.js you'd be looking at building a source handler. See the comment in #3719
