### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) This video is not supported by your device

### ISSUE THREAD

**Issue by supert3d** [videojs/video.js#3726]
We've come across this issue on the qvc.com website (I do not work for QVC). Video on this page randomly does/doesn't load: http://www.qvc.com/Conair-1-Root-Boost-Tourmaline-Ceramic-Crimper.product.A285320.html?sc=A285320-SRCH&cm_sp=VIEWPOSITION-_-7-_-A285320&catentryImage=http://images.qvc.com/is/image/a/20/a285320.001?%24uslarge%24&vid=y

It may? be an issue with how qvc.com is distributing the video, but digging deeper it seems to be something to do with video.js

I believe they are using delvenetworks.com/limelight network to CDN the content, but are using video.js for playback. Example...  

In reviewing some of the components QVC load in I'm 100% certain they are using the video.js project to serve video content (example): 
http://www.qvc.com/etc/designs/qvc-global-ui/components.7b8eed4af6f17ab123b14a6fcf59405e.js

Contains references to: https://github.com/videojs/video.js/issues/2617 which leads me here. 

Is there a setting in the browser that's preventing this video from loading? We've tried Chrome 54, Firefox 42, Safari 10. Browsers on both PC and Mac' and the video does/doesn't load randomly. 

We also note that qvc.com are pulling in an m3u8 playlist which will sometimes HTTP1.1/206 

http://qvc0.cpl.delvenetworks.com/media/4826bb17d50c481b98a9e427e1c29c79/e2a7e515b68443a89dbaab3b31be1516/c--ftp-newqvideo-limelight-production-a285320-16080220-a98a5dafc35ce62997ad1a9e0be562a6df573967.m3u8

However, every time it loads we get similar issues across all browsers. Video content will not load. 

Any ideas?

**Comment by misteroneill** [comment]
They are indeed using video.js to embed the video. I tried loading the page referenced and each time I clicked the "play" button it created a player and began playing. I tried about 10 times total. This is in Chrome 54.

**Comment by mister-ben** [comment]
I haven't seen any error in-browser, but Quicktime has problems. The window resizes over and over, so it looks like it's trying but failing on several variants before finding one that works.

`mediastreamvalidator` complains that the h264 level of the media segments for three of the variants is different (lower) than stated in the master manifest.

**Comment by misteroneill** [comment]
It sounds like there could be an issue with the serving of the content or a proxy or something. Regardless, it doesn't sound like an issue related to Video.js, being a client-side library.

If you can share a reduced test case that demonstrates the issue, that'd be helpful, and we can reopen the issue.
