### ISSUE TITLE
Can't play rtmp stream in ff or my iphone

### ISSUE THREAD

**Issue by HebutJipeng** [videojs/video.js#3731]
hi, 
thank for this libs,
i play rtmp stream recently. it works well in my chrome, but when it can't work in firefox  or in safari  of my iphone, 

the error is 
" video.min.js:22VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. "

how it works  well in ff, or safari?

thanks.

**Comment by mmcc** [comment]
RTMP requires Flash for playback, so unfortunately that's a non-starter for trying to play it back on iOS. In general, I'd _highly_ suggest moving away from Flash as browsers are getting more and more hostile or [removing support altogether in the near future](http://www.theverge.com/2016/5/15/11679394/chrome-to-block-flash-later-2016).

I'm going to close the issue, but if you have other questions on getting things working in browsers that do support Flash we can keep the conversation going here.
