### ISSUE TITLE
canPlayType return '' for 'video/rtmp

### ISSUE THREAD

**Issue by steplerbox** [videojs/video.js#3733]
Chrome, Firefox.
Flash enabled.
Method player.canPlayType('video/rtmp') returns ''. Why?

And one question. Just interested, why this method returns empty string? Maybe should be false?

**Comment by mister-ben** [comment]
The types supported by the Flash tech are `rtmp/mp4` and `rtmp/flv`.

video.js's `canPlayType()` returns the same values are the HTML5 video element - `'probably'`, `'maybe'` or `''`. I'd agree `''` is unintuitive, but it's the standard.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType

**Comment by steplerbox** [comment]
https://github.com/videojs/video.js/blob/master/src/js/tech/flash.js#L446 - here list of formats

Flash.formats = {
  'video/flv': 'FLV',
  'video/x-flv': 'FLV',
  'video/mp4': 'MP4',
  'video/m4v': 'MP4'
};

I think here should be 'video/rtmp'.

**Comment by mister-ben** [comment]
This is where to look for RTMP:

https://github.com/videojs/video.js/blob/3a859f97d0647fc3d1ef6b2f4b755c71da8bef63/src/js/tech/flash-rtmp.js#L5-L8
