### ISSUE TITLE
{ fluid: true } dose not work well with flv video

### ISSUE THREAD

**Issue by hojas** [videojs/video.js#3741]

**Comment by mister-ben** [comment]
Can you use the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md), including a reduced test case with a sample video.

There's an update in master that changes the default aspect ratio for fluid where the video dimensions can't be detected. It's impossible to know if that fixes your issue without understanding  what "doesn't work well" means and seeinga same video. If you are able to build from master and test, that would be great.

**Comment by hojas** [comment]
The update in master fixed my problem. Thanks. @mister-ben

**Comment by mister-ben** [comment]
Great. Thanks for testing!
