### ISSUE TITLE
Mute and volume level session

### ISSUE THREAD

**Issue by campones** [videojs/video.js#3746]
Hi, 
I was wondering why user volume session and mute isn't stored in local storage or cookies

### versions

tried v5.11

what version of videojs does this occur with?

all..

**Comment by mmcc** [comment]
This feels like a pretty implementation-specific feature to include in core by default, but I can see why it'd be useful. Our philosophy has traditionally been to follow the video element's functionality, which we haven't been totally strict about, but I think it makes sense for things like this to fall back on "What Would The Spec Do."

If you want tips on rolling this yourself, let us know!

**Comment by campones** [comment]
well yes, I m using this plugin videojs.persistvolume.js 
I really feel these should be part of the core videojs.. all others players keep user volume session.  It isn't normal to have to include  a plugin and some javascript to have this working in my opinion

**Comment by hartman** [comment]
I've suggested in the past that we need a thin 'persistence' framework, that components etc can hook into. I agree that this is something that misses right now, and having each and every tool implement this itself is annoying and will likely lead to conflicts and inconsistencies.

For instance on Wikimedia, we always assume that multiple instances of a tool can reside on the same domain, so all storage keys are prefixed with a instance-id, to avoid conflicts.

I think ideally, we could have a 'videojs-contrib-persistence' plugin, and when it's installed, core components and plugins could automatically use it.

**Comment by mmcc** [comment]
@hartman I could get behind that idea!
