### ISSUE TITLE
videojs rtmp autoplay not work

### ISSUE THREAD

**Issue by zhang852774731** [videojs/video.js#3748]
## Description
http://stackoverflow.com/questions/40337141/videojs-rtmp-cant-autoplay

### Error output
on error info in console window

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
4.6 and 5.11.9
#### browsers
chrome
#### OSes
OS X
### plugins
no plugins

**Comment by mister-ben** [comment]
From the code you've put on Stackoverflow, you're setting the player size to 300x400. At this size [Chrome will block automatic loading of Flash](https://chrome.googleblog.com/2015/06/better-battery-life-for-your-laptop.html) -- including the player's Flash tech -- until user interaction. It will shows this play icon until the user clicks if the browser is configured to "detect and run important plugin content (recommended)". https://support.google.com/chrome/answer/142064?hl=en-GB

As a user preference, you or video.js cannot influence the behaviour. You could make the player larger, but you'll still get issues where browsers are configured to block or prompt for all Flash content.

It will get harder and harder to use Flash as all major browsers are phasing out support. You might want to look at other ways of streaming your content, such as using HLS with [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls).

Closing as this isn't a video.js issue, but you can still use the comments to discuss implementing modern video formats.

**Comment by zhang852774731** [comment]
i solved this problem. i changed my browser, used firefox instead. Besides, i updated my flash. So i think it maybe the version of flash! Thank you any way!

**Comment by missdora** [comment]
@mister-ben it solved my problem! thanks!
