### ISSUE TITLE
Marker length on videojs Timeline

### ISSUE THREAD

**Issue by tessact** [videojs/video.js#3749]
I am using videojs in my react application. I am having markers of different length on timeline. Currently what I am doing is, I am passing the time where marker should begin and the length of the marker, through a JSON object. Problem is the length I am passing is not equivalent to the time length I want as I am passing the length in px (obviously). I don't want to pass the length in px. I want to calculate the time length through start time and end time of a marker. Below is my Json and code to set the length of marker.

Json (I am not taking use of startTime and endTime right now, but I want to use it for calculating lenght)

```
player.markers({
            markerStyle: {},
            markers: [
                {length: 8, startTime: 9.5, endTime: 15, time: 9.5, text: "Cigarette"},
                {length: 2, startTime: 16, endTime: 25, time: 16, text: "Cigarette"},
                {length: 15, startTime: 23.6, endTime: 38, time: 23.6, text: "Cigarette"},
                {length: 11, startTime: 23.6, endTime: 38, time: 23.6, text: "Alcohol"},
                {length: 25, startTime: 28, endTime: 55, time: 28, text: "Cigarette"},
                {length: 10, startTime: 35, endTime: 80, time: 35, text: "Alcohol"},
                {length: 15, startTime: 50, endTime: 115, time: 50, text: "Alcohol"},
            ]
```

This is where I set the width of each marker in css (acc to length in JSON) This code iterates for each marker and sets the respective width of markers.

```
function createMarkerDiv(marker, duration) {
                var markerDiv = $("<div class='vjs-marker'></div>");
                console.log(marker.length);
                markerDiv.css(setting.markerStyle)
                    .css({
                        "width": marker.length, "margin-left": -parseFloat(markerDiv.css("width")) / 2 + 'px',
                        "left": getPosition(marker) + '%',
                    })
```

**Comment by mister-ben** [comment]
You could try setting the width to `(end-start)/player.duration()*100 + '%'`

I'll close this as this isn't an issue that requires a change to video.js. For help on plugins, issues are best filed on the plugin repository, or for more general implementation help Stackoverflow can be useful.
