### ISSUE TITLE
Cache breaks video

### ISSUE THREAD

**Issue by RaymondLC92** [videojs/video.js#3751]
1. Create html video tag
2. Load page, video is rendered.
3. Go to address bar, hit enter.
4. Page is loaded, video yields "The media could not be loaded, either because the server or network failed or because the format is not supported."
5. Clear cache.
6. Go to address bar, hit enter.
7. Page loads, video is rendered.

Disabling cache via the developer tools fixes the issue, behavior is consistent across browsers.

I attempted to fix this by adding a time stamp to the request in the hopes that the browser would consider it a unique request and bypass the cache.  This has not yielded results .I am unsure if it matters but my app is using MeteorJS. 

I would like to get the videos working - with cache - if possible. Any assistance is greatly appreciated, I can provide whatever additional information is request.

**Comment by mister-ben** [comment]
Caching is browsers' default behaviour and doesn't generally break video playback. Please use the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md) and provide a reduced test case reproducing the issue.

**Comment by RaymondLC92** [comment]
@mister-ben 
All attempts at creating a reduced test case have failed. Everything works when loading the videos via static html i.e.:
`<video id="my_video_1" class="video-js vjs-default-skin" width="640px" height="267px"
         controls preload="none" data-setup='{ }'>
         <source src="http://media.clamor.io/videos/kfzfTMXYB6rDX7q5m.mp4?play=true?time=1478511683779" type="video/mp4">
         <source src="http://media.clamor.io/videos/kfzfTMXYB6rDX7q5m.webm?play=true?time=1478511683779" type="video/webm">
  </video>`
http://jsbin.com/bavelexoni/edit?html,output

However loading the videos via templates only works once (until the cache is cleared):

```
<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268"
		  data-setup='{}'>
			<source src="{{videoURL videoFile true}}" type="{{videoFile.type}}" />
			<source src="{{videoURLAlt videoFile true}}" type="video/webm" />
	  </video>
```

The following is everything else in line with the issue template:

**Description**

Videos loaded dynamically through MeteorJS are displayed one, subsequent requests fail - unless you clear the browser cache.

**Steps to reproduce**

1. Create html video tag
2. Load page, video is rendered.
3. Go to address bar, hit enter.
4. Page is loaded, video yields "The media could not be loaded, either because the server or network failed or because the format is not supported."
5. Clear cache.
6. Go to address bar, hit enter.
7. Page loads, video is rendered.

**Results**

_Expected_

The video should load on any subsequent request the same as it did on the first, caching should have no effect. Requests should be made as usual.

Healthy header recieved on first request:
```
HTTP/1.1 206 Partial Content
Server: nginx/1.10.1
Date: Mon, 07 Nov 2016 10:28:47 GMT
Content-Type: video/mp4
Content-Length: 1055736
Last-Modified: Mon, 07 Nov 2016 04:21:15 GMT
Connection: keep-alive
ETag: "5820013b-101bf8"
Content-Range: bytes 0-1055735/1055736
```

_Actual_

The video loads one, any subsequent requests made fail unless the cache has been cleared. No additional server requests show in the Network log, as such no response headers are available.

**Error output**

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

**Additional Information**

_versions_

VideoJS: 5.11.9
Browsers Affected: Chrome/54.0.2840.89, Firefox 49.0.2 (Edge\IE not available for testing)
OSes: All
Plugins: None

Any additional insight you can grant would be appreciated.

**Comment by hartman** [comment]
Please see [Alternative setup for dynamically loaded html](http://docs.videojs.com/docs/guides/setup.html#alternative-setup-for-dynamically-loaded-html)

If you use those kinds of JS libraries, you cannot rely on the DOM structure alone, you need to TELL videojs where and what to load, after each update.

**Comment by RaymondLC92** [comment]
@hartman Thank you, using the follow javascript I can resolve the issue:

```
$(window).load(function(){
  videojs("my_video_1", {}, function(){
    this.src({type: 'video/mp4', src: 'http://media.clamor.io/videos/kfzfTMXYB6rDX7q5m.mp4?play=true?time=1478516169353'});
  });
});
```

However, this leaves me wondering how I am supposed to loading countless videos all of which are loaded dynamically?

If I have a page with 10 videos do I need to iterate through every item with getElementsByClassName in order to set the source?

**Comment by hartman** [comment]
Yes, you collect the dom elements and for-loop over the elements and initialize them using the function. You don't need this.src if the element already has a <source> tag element nested inside, but the video.js library does 'consume' these elements, so i'm not sure how that effects your Meteor.JS template logic. That seems like questions that belong in the meteor.js support forums really.

**Comment by RaymondLC92** [comment]
@boushley Yes, you can close the issue.

For those wondering the ideal solution is to do the initialization in the templates onRendered function.
