### ISSUE TITLE
VideoJS @font-face embeds two Data URIs

### ISSUE THREAD

**Issue by zachleat** [videojs/video.js#3758]
## Description

The CSS contains a `@font-face` block that includes both `woff` and `ttf` Data URIs.

## Steps to reproduce

1. Open up the Video JS CSS
2. Look for the `VideoJS` `@font-face` block.
3. Notice that both the WOFF and TTF Data URIs are included in the block. This duplication greatly increases the size of your blocking CSS. These Data URIs are _8.09KB_ (this is an estimate—I removed them from the core stylesheet and gzipped them standalone).

## Results

You have a couple of options here. You could switch to a one Data URI (just the WOFF) approach, since that’d give you almost all of the browser support you’re currently supplying. The TTF format will give you Android 2.2-4.3 support, but you could very easily just make this an external file reference rather than a Data URI.

The one Data URI approach would leave you with a 3.8KB Data URI rather than the 8.09KB combination above.

Questions:

* Have you included both Data URIs to avoid FOIT issues with font-icons?
* Does the VideoJS browser support requirements include older Android? Is it worth it to FOIT for just these older browsers to speed up the experience for everyone else?

Alternatively, you can make both Data URIs external file references to reduce the amount of blocking CSS and move to an asynchronous font loading approach. This would require a little bit more JavaScript for a font loader but it’d reduce the amount of blocking CSS significantly. If you’re interested in this, I’ve written a few blog posts that I could share.

**Comment by gkatsev** [comment]
Hi, in Video.js 7 and videojs-fonts 3.0 we have removed the ttf and the eot support and are only using one embedded woff font.
