### ISSUE TITLE
poster and title for Audio Track : support on mobile OS ?

### ISSUE THREAD

**Issue by dvidal49** [videojs/video.js#3767]
Hello,
Is it possible to display the title of my audio track (and cover) on mobile OS (iphone for me) ? 
If yes, how ? I do not find the solution. Before, I used jPlayer and it's working for the title :
$Jplayer.jPlayer ("setMedia", {title: appData.media_title, mp3: url ...

**Code with video.js:**
player.src ({"type": "application / x-mpegurl", "src": "https: //xxxxx.m3u8"});

Thank you for your help.

![question_videojs](https://cloud.githubusercontent.com/assets/16623161/20153713/55f5e116-a6c4-11e6-9465-1e0155f87ee7.png)

**Comment by hartman** [comment]
You can do player.el() (to get the HTML5 media element) and then just set the .title attribute. This is what will show up in the iOS player. Or just <audio title="Your titles"> of course. It might also work on the <source> elements, but I've never really tried that.

As far as I know, it is not possible to set the poster art element (which i find somewhat strange actually, but whatever).

**Comment by dvidal49** [comment]
Thanks hartman ! 
It was so simple :)

**Comment by dvidal49** [comment]
Now i search for audio cover art, any idea ?

**Comment by gkatsev** [comment]
Thanks for the answer @hartman. I'm not aware of anything else for the poster.
