### ISSUE TITLE
Add support for missing video element options

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/video.js#3780]
## Description
Looking at the specification for video elements [here](https://www.w3.org/TR/html5/embedded-content-0.html#htmlmediaelement) I see that we are missing a few options. We should probably implement these:

* `playbackRate`
* `defaultPlaybackRate`
* `volume`
* `defaultMuted`

**Comment by gkatsev** [comment]
We have support for playback rate. Is this for html attributes on the video element specifically?

**Comment by BrandonOCasey** [comment]
I think we are missing these function in the Html5 tech and I don't think these options will work if they are passed to the tech either. I could be wrong though

**Comment by gkatsev** [comment]
[playbackRate](https://github.com/videojs/video.js/blob/master/src/js/player.js#L2391-L2411) and [volume](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1478-L1507) available, though, the others may not be.

**Comment by gkatsev** [comment]
There's a section in `player.js` about methods we're missing: https://github.com/videojs/video.js/blob/master/src/js/player.js#L2572-L2577

**Comment by gkatsev** [comment]
This is probably a better place to keep track, though :)

**Comment by BrandonOCasey** [comment]
sometimes it almost seems like Tech should inherit from player or player from tech

**Comment by misteroneill** [comment]
Are `playbackRate` and `volume` supported as `options` though? Perhaps I'm missing some magic in the player that sets them from `options`...

**Comment by BrandonOCasey** [comment]
I also see that we are missing `[crossOrigin](https://www.w3.org/TR/html5/embedded-content-0.html#dom-media-crossorigin)`, `[mediaGroup](https://www.w3.org/TR/html5/embedded-content-0.html#dom-media-mediagroup)`, and `[controller](https://www.w3.org/TR/html5/embedded-content-0.html#dom-media-controller)`. Do we want to implement these?

**Comment by gkatsev** [comment]
`crossorigin` we should probably add. The others can be ignored as they're likely going to be removed from the spec and isn't really supported on any browser.

**Comment by gkatsev** [comment]
`crossorigin` is super tricky, though, see the "using text tracks across domains" section in the docs.

**Comment by BrandonOCasey** [comment]
ok I also saw mention of `startOffsetTime` and `initialTime` which both appear to be gone from the spec.

**Comment by BrandonOCasey** [comment]
I think I will make one PR for all the other attributes and one PR for `crossorigin`
