### ISSUE TITLE
does the starttime/startTime option work? Do we want to keep it?

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/video.js#3781]
## Description
Right now I see an option for start time referenced in a few places under two different names. I am thinking that it is a legacy option that probably does not work anymore. Do we want to make it work again, or fix the option?

Code Links: 
* [starttime](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1023)
* [startTime](https://github.com/videojs/video.js/blob/master/src/js/player.js#L657)?

**Comment by misteroneill** [comment]
I vote to kill it. I don't think it's documented. And it's not a standard attribute.

**Comment by misteroneill** [comment]
We discussed this morning and I believe the path forward will be to remove the `startTime` option being passed to the tech since it isn't used and we will deprecate the `starttime` option of the player in case someone is using it.

**Comment by BrandonOCasey** [comment]
Found a place where startTime is used. https://github.com/videojs/video.js/blob/master/src/js/tech/flash.js#L49

**Comment by misteroneill** [comment]
http://www.nooooooooooooooo.com/

**Comment by BrandonOCasey** [comment]
Do we want to keep `startTime` and deprecate `starttime` then?

**Comment by misteroneill** [comment]
Yeah, I think that's probably what we need to do for now. It's mainly harmless.
