### ISSUE TITLE
Do we want to support three different ways to watch a `ready` event in Player?

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/video.js#3782]
## Description
There are three ways to check for a player ready event, are we sure that we want to have three ways rather than just 1?

Pass a callback to the `videojs()` function as a third argument:

```js
// Passing `null` for the options argument.
videojs('my-player', null, function() {
  this.addClass('my-example');
});
```

Pass a callback to a player's `ready()` method:

```js
var player = videojs('my-player');

player.ready(function() {
  this.addClass('my-example');
});
```

Listen for the player's `"ready"` event:

```js
var player = videojs('my-player');

player.on('ready', function() {
  this.addClass('my-example');
});
```

**Comment by misteroneill** [comment]
I think the only real candidate for removal would be the `player.ready` function. I can't think of any other event that has a special method to add a listener like that.

**Comment by mister-ben** [comment]
`player.ready()` triggers the function is the player is already ready. `on('ready'...` does not.

**Comment by misteroneill** [comment]
Good point.

**Comment by BrandonOCasey** [comment]
Ok with that in mind I guess it does make sense to keep all three of these unless we want to remove the ready function argument from `videojs()`.

**Comment by dmlap** [comment]
... or get rid of `ready` altogether.

**Comment by misteroneill** [comment]
How would that be possible @dmlap?

**Comment by gkatsev** [comment]
I think we're not ready to remove ready :D

**Comment by BrandonOCasey** [comment]
Maybe we should abstract ready away from users and wrap our own methods in ready calls. We would just need to make sure that ready calls things in order.

**Comment by gkatsev** [comment]
Whether we abstract it away, I don't think we want to remove it's functionality.
