### ISSUE TITLE
Video does not play in In iOS device - iPad and iPhone

### ISSUE THREAD

**Issue by VinaykumarNM** [videojs/video.js#3784]
Hi,
I am using videoJs with following setUp. 

#Description
var setup = { 'techOrder': ['html5', 'flash'],
						'preload': 'none',
						'autoplay': false
					};
var videoJsObject = videojs($videoTag[0], setup);
videoJsObject.controls(true);

videoJsObject.src({
          type: 'video/mp4',
	 src: 'https://<myhost>/Download/06836000001ydBCAAY' 
});

### Expected
Should run the video in iOS device. The same works in desktop and android tablet and phones.

### Actual
In iPad and iPhone show error : "The video could not be loaded, either because the server or network failed or because the format is not supported"

### Error output
"The video could not be loaded, either because the server or network failed or because the format is not supported"

## Additional Information
The same works in desktop and android tablet and phones. When traced the response on desktop its following -
   Cache-Control:private
   Content-Disposition:attachment; filename="1.mp4"
   Content-Length:1250296
   Content-Type:video/mp4;charset=UTF-8
   Date:Wed, 16 Nov 2016 07:36:51 GMT

#### videojs
what version of videojs does this occur with?
videoJs - v5.12.6

#### OSes
iOS - iPad and iPhone

**Comment by mister-ben** [comment]
Check that your server is responding properly to range headers - Safari will not play your video otherwise. Most HTTP servers do by default but if your URL is to a script that fetches and returns the video, that script needs to implement byte range requests.

**Comment by andreassp** [comment]
Hello - i have (still) have the same problem with videos on Safari an iOS Devices.
I tried it on different apache hosts with different setting (and added video mime-type to htacess), but still get MEDIA_ERR_SRC_NOT_SUPPORTED.
How can i configure the host correctly?

**Comment by andreassp** [comment]
btw: i am getting the same error when visiting http://videojs.com with safari (version 10, OSX 10.12)

**Comment by misteroneill** [comment]
This URL looks wrong as well... `https:///Download/06836000001ydBCAAY`

**Comment by VinaykumarNM** [comment]
Hi,
Actually the url like this - https://[MyHost/Download/06836000001ydBCAAY. This returns mp4 media file and this works well in desktop and android devices. Problems is only in iOs.

**Comment by hartman** [comment]
@VinaykumarNM As ben said in the first reply: Does your server support Range headers ? Because this seems to be a requirement in more recent versions of Safari and it has been the cause for many of these kinds of reports.

**Comment by andreassp** [comment]
I tested safari with current video.js over different networks (home and office) - at home (or via ios on the go) it works, at the office not. If i try on ios via local w-lan neither.
So i guess the server supports range headers but there might be local a firewall issue...

**Comment by gkatsev** [comment]
Sounds like we've found the root cause and unfortunately, it doesn't involve videojs. Firewalls sometimes do weird stuff to headers, so, it makes sense it could be an issue. Sorry we won't have a better answer.

**Comment by VinaykumarNM** [comment]
Hi,
I could make it work by adding 'Content-Range' header to response. It is working now.

Thanks

**Comment by rdevetibr** [comment]
@VinaykumarNM facing the same problem. Can you say how do you "add 'Content-Range' header to response', please? I've tried somethings but no success. Thank you very much.

**Comment by Jogii** [comment]
@VinaykumarNM  even i am facing the same problem. Please share how to add content-range to the response. Thanks in advance.
