### ISSUE TITLE
DOM utility tweaks for 6.0

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#3785]
The Flash removal PR - #3678 - has raised a question for me. Note that it necessarily exposes the `Dom` util. I want to propose some additional changes related to that:

- Expose it as `videojs.dom`. It's not a constructor and calling it `Dom` doesn't make sense given the comon naming convention used in JavaScript to denote constructors.
- Deprecate previously-exposed DOM methods: `videojs.createEl`, `videojs.addClass`, etc.
- Rename class methods to more familiar names (with deprecation wrappers for old names):
  - For example, `dom.addElClass` becomes `dom.addClass`. `dom.addElClass` becomes a wrapper with a deprecation warning.

**Comment by BrandonOCasey** [comment]
On the same note:
* We may also want to see if there are any other things worth exposing
* I know Url also does something similar to what Dom does (only exposes specific methods). We should probably do the same thing for that and see if there are any others with this issue.

**Comment by gkatsev** [comment]
Just wanted to add that the reason why we kept it all shallow on the videojs object and kept things minimal is so that videojs doesn't turn into a DOM utility library. I'm not against this, just wanted to resurface the reasoning behind the current state of affairs.

This makes sense to me. We use all these helpers internally and there's no reason to not expose them.
@videojs/core-committers thoughts?

**Comment by dmlap** [comment]
I'm torn about this. I understand the utility but I am also worried about API bloat. I lean towards keeping it internal but I wouldn't put up a fight if everyone else felt it was important for the ecosystem.

**Comment by BrandonOCasey** [comment]
Maybe we should split utlis into their own modules so other projects can just npm install them?

**Comment by misteroneill** [comment]
@dmlap The Flash plugin needed `utils/dom` and `utils/urls` exposed as it relied on both of them.

**Comment by misteroneill** [comment]
I was bored last night and [threw together a branch](https://github.com/misteroneill/video.js/compare/feat/seperate-flash-tech...misteroneill:dom-tweaks) on top of @BrandonOCasey's Flash tech removal branch.
