### ISSUE TITLE
Question on clicking progressbar

### ISSUE THREAD

**Issue by AlexLi88** [videojs/video.js#3791]
Hi, there, I have a problem related to issue #159. 
So once you click down timeline cursor, 'pause' event is fired. Is it possible to let 'play' event not fired automatically on left click up?  Cause I want to add a function after the mouse up.

Thanks in advance.

**Comment by Romain** [comment]
Hi @AlexLi88,
I'm not sure if you can do this in VideoJS initialization, but you could trigger a play event when you detect a click on the timeline:

```js
$(document).on("click", ".vjs-play-progress", function() {
    var isPaused = videojs.paused();
    if(isPaused) {
        videojs.play();
    }
});
```

Is this what you need?
Romain

**Comment by AlexLi88** [comment]
Hi @Romain , thanks for reply.  Actually, I want to disable autoplay after user mouse up from the progress bar.  Is it possible to do this or override https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/seek-bar.js#L119  this function.   

Thank you 
Alex

**Comment by Romain** [comment]
I'm not sure how you could override this function without changing the core files, which would be a mistake because you wouldn't be able to upgrade the source files safely...
Personally, I would do it using jQuery:

```js
$(document).on("mouseup", ".vjs-play-progress", function() {
    var isPaused = videojs.paused();
    if(isPaused == false) {
        videojs.pause();
    }
});
```

**Comment by gkatsev** [comment]
It seems like @Romain's answer solves this problem. Though, you could also potentially just use `videojs.on` or even `player.controlBar.progressControl.on` instead of jquery.
Going to close this for now, we can always reopen if it doesn't actually solve the issue. Though, I'd love more info on the usecase because I'm not quite certain what it tries to achieve.

**Comment by AlexLi88** [comment]
Thanks for you guys answer.  I'm doing a project a which need to calculate the data of each frames. So if users drag on the control bar, I need to do a calculation before the playback start.
