### ISSUE TITLE
[docs] mention the optional fluid classes

### ISSUE THREAD

**Issue by scheinercc** [videojs/video.js#3795]
The "options" guide - http://docs.videojs.com/docs/guides/options.html - seems to be missing those new-ish fluid classes - .vjs-fluid, .vjs-4-3, .vjs-16-9 - that can be set for responsive player dimensions as noted in this blog post http://blog.videojs.com/Video-js-5-s-fluid-mode-and-playlist-picker/.

## Steps to reproduce

1. Setting up the player
2. Trying to find information about (all) options
3. Only finding examples with fixed dimensions
4. Lots of reading through https://github.com/videojs/video.js/issues/982 , https://github.com/videojs/video.js/pull/1952 , https://github.com/videojs/video.js/issues/2399 assured me the functionlaity existed
5. more searching brought me finally here: http://blog.videojs.com/Video-js-5-s-fluid-mode-and-playlist-picker/

### Expected
I would have expected those classes in the docs around where setting the dimensions is described

### Actual
Only a "fixed dimensions" example in the docs and here http://docs.videojs.com/docs/examples/simple-embed/index.html

## Additional Information
maybe I just didn't find the right place in the docs!?
#### videojs
version 5.12.6

**Comment by misteroneill** [comment]
Thanks for the issue @scheinercc - our docs are out of date. Luckily, we are currently in the process of revamping all the guides and adding new ones. The `fluid` option will _definitely_ be part of the new guides! I've already added it [in the options guide](https://github.com/videojs/video.js/pull/3703/files#diff-6c58c8262d964811ca6826c5442522c6R113), but I think the fact that this was challenging for you to discover is a good reminder that we need to more thoroughly document player sizing.

I think we can leave this issue open for the time being, until we've merged all the documentation updates.

**Comment by scheinercc** [comment]
Thanks for the update @misteroneill - will keep my eyes open for the new docs! :)

**Comment by lifenautjoe** [comment]
Years after, no documentation on this still?

**Comment by steveDL** [comment]
still nothing?

**Comment by phloxic** [comment]
https://docs.videojs.com/tutorial-layout.html is _something_ ;-), especially as https://docs.videojs.com/docs/ is considered outdated.

**Comment by scheinercc** [comment]
Docs in @phloxic link above fix this. Thanks!
