### ISSUE TITLE
Display a clickable cue of texttrack (how?)

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#3797]
Hi guys

Been stuck with this one for quite a few day

What I want to achieve is to have a clickable cue-text-track on video, when click it will trigger something (not a whole sentence but a single word - for translation).

Trying but it doesn't seem possible to me, then I thought maybe I could ignore the whole texttrack thing and use the ModalDialog to a nice html over video where I could control it (spend another few day and no success so far), is there a way to achieve this?

Please help!
Thank a lot in advance.

**Comment by kocoten1992** [comment]
Think I have figure something, it is this method:

https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-display.js#L218

inside this there is processCues method

It use https://github.com/mozilla/vtt.js/blob/master/lib/vtt.js#L1017

I'll use a self build videojs with my custom vtt.js, hope it will success

**Comment by kocoten1992** [comment]
This thing sure take time, so here the deal:

First, it videojs-vtt.js, look for keyword "leaf" (only one in the world, you don't miss it), override it there

Second, for the subtitle clickable make sure you add css 
```
pointer-events: auto; /*(or anything you but not "none")*/
```

And build it, voila, @Alanser you might interest :)

@gkatsev , I've notice https://www.npmjs.com/package/videojs-vtt.js surely not github.com/mozilla/vtt.js, maybe create it own package?

**Comment by gkatsev** [comment]
the videojs-vtt.js package lives in my fork right now: https://github.com/gkatsev/vtt.js
