### ISSUE TITLE
Can't play simple mp3 with flash

### ISSUE THREAD

**Issue by ayayy** [videojs/video.js#3799]
In chrome I try to play simple mp3,  but it give me an error:
No compatible source was found for this media

here the code,
```
<video id="my-video" class="video-js vjs-track" controls preload="auto" width="640" height="264" >
</video>
<link href="http://vjs.zencdn.net/5.8.8/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/5.8.8/video.js"></script>

<script>
    videojs.options.flash.swf = "http://vkpm/101/videojs/video-js.swf";
</script>
<script>
    var player;
    player = videojs('my-video', {
        techOrder: ['flash'],
        autoplay: true,
        sources: [{
            type: "audio/mp3",
            src: "1.mp3"
        }]
    }, function() {
        this.on('playing', function() {
            console.log("playing");
        });
        this.on('pause', function() {
            console.log("pause");
        });
    });
</script>
```
If I switch to html5 tech order, it works fine. What am I doing wrong ?

**Comment by mister-ben** [comment]
The flash tech does not support mp3 sources. With the default techOrder `['html5', 'flash']` then the audio would play using the htm5 element. Any reason you're trying to force Flash?

**Comment by ayayy** [comment]
Thank you for answer. Just example with mp3. Firstable, I wanted to play AAC stream via html5 - not playing, then AAC stream via flash - not playing, another players, for example Uppod - playing AAC stream without any problem. Stream is generated by Icecast. Can you tell me why Videojs not playing AAC stream and what I need to fix it ? I can't find any full information about Videojs via google. Thanks in advance

**Comment by ayayy** [comment]
Sorry, plays ok

**Comment by JSoon** [comment]
@I'm developing an audio player based on mp3 sources in CEF1, which doesn't support both <video> and <audio> elements, any luck with videojs now? For example, A audio-js.swf?
