### ISSUE TITLE
Video js multiple player in one html page

### ISSUE THREAD

**Issue by harikris2007** [videojs/video.js#3804]
i am facing the an issue when i added multiple video player in same page.
The js code as follows.
`var stream_url = $(this).attr('data-stream'); wiFetchBroadcast(entryId); player = videojs('wiPlayer'); player.src({ src: **stream_url** , type: "application/x-mpegURL", useCueTags: true }); window.onOrientation(player, 'wiPlayer'); player.play();
`
The video html is like:
Here the player div is generated according to the values returned from an api call used in my project.
In the api ,it returns the video url (stream_url )and i directly assign the url to the js.

`<video id="wiPlayer" width=600 height=364 class="video-js vjs-default-skin" controls autoplay="autoplay"> <!-- <source src="media/demo.mp4" type="video/mp4"> --> <p class="vjs-no-js">We're sorry, but your browser doesn't support Video</p> </video>`

Here the first player is only playing the video and the rest are not playing.Any solution for this?

**Comment by misteroneill** [comment]
Thanks for taking the time to report an issue.

Unfortunately, there is no practical action we can take when issues do not follow the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md). Without a reduced test case, we cannot verify that there is a bug in Video.js.

If there is a demonstrable bug, we will gladly re-open this issue.
