### ISSUE TITLE
Events are not getting attached for videos in Mac Safari browser

### ISSUE THREAD

**Issue by yammini211** [videojs/video.js#3807]
## Description
Events are not getting attached for videos in Mac Safari browser

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. I have a private site which plays Vimeo videos with the help of videojs.
2. Everything works fine in Chrome/Firefox browser.
3. I need to update progress based on the events getting fired(play/timeupdate etc)
4. This gets triggered only at times in Safari and fails many time. Is there a solution for this

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
Version 3.0 BETA
#### videojs
Version 3.0 BETA
#### browsers
Mac Safari 
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by BrandonOCasey** [comment]
What version of safari is broken? Is version `3.0-beta` the version of `video.js` that you are using? (the current version is `5.13+` so you may want to try updating). I assume this is using the [video.js vimeo](https://github.com/videojs/videojs-vimeo) plugin? It would also be really helpful if you could provide us with a reduced test case of this bug on jsbin. [Here]((http://jsbin.com/axedog/edit?html,output)) is a starter template to work with.
