### ISSUE TITLE
Hide links to subtitles ...?

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#3808]
Good Day!
  
Is it possible to hide links to subtitles in the source code of the page?

track kind="captions" src="/uploads/MV04/film1/film1_Track02.vtt" srclang="en" label="English" 

Thanks advance!

**Comment by misteroneill** [comment]
Do you mean to obscure the URL (e.g. "/uploads/MV04...")?

If so, no, that's not possible.

**Comment by surikat1978** [comment]
Well, can connect URL subtitles using some JS script? Thus URL subtitle will not even source code?
There are some ways to protect content? Otherwise, everything is open source, it is very bad.
Thanks in advance!

**Comment by misteroneill** [comment]
Even if you do it in JavaScript, it has to be in the script to write it into the DOM. At which point it's exposed anyway. It's exposed again when the browser downloads the VTT file.

That's just the way the web works.

**Comment by surikat1978** [comment]
And if you use instead of simple code videojs HLS? In this case it will be possible to protect the content?
