### ISSUE TITLE
Sometimes video doesn't start properly

### ISSUE THREAD

**Issue by Nojbee** [videojs/video.js#3813]
## Description
Hey,

I have an API to record live streams between two specified dates. The API creates .ts segments and a .m3u8 file from the stream. The finished video has no duration, detects as a live stream so I calculate the duration and set it:
this.on('timeupdate', function() {  
       this.player.duration(duration);
 });

**My first problem:**
For some reason the player wants to start the video from the last 29 seconds in chrome, so I have to set the currentTime to 0.
In MS Edge the player plays only the first 29 seconds. Only some .ts are downloaded, and then get stuck.
What can cause these problems?

**My second problem:**
Sometimes after I load a video and click to play, it can't remove the vjs-live and because of this can't appear the seekbar. The video doesn't start. The .ts files doesn't start downloading. 
Only the m3u8:
![pic](https://cloud.githubusercontent.com/assets/10439187/20743242/8f137168-b6d5-11e6-9149-3ce4cbeb27a8.JPG)

After I click again on the player, the LIVE label disappears and the seekbar appears. But the video doesn't start as long as I not click on the seekbar. After the click it starts to download the .ts files, and the video starts.
This happens unpredictable. I click a video -> can't start, click an other -> starts, then click to the previous -> can start... and so on
Maybe it's just a simple problem, but i can't figure out the cause. Please help me out. Thank you

**Comment by mister-ben** [comment]
You need to fix this in the HLS playlists. Append an `EXT-X-ENDLIST` tag.

**Comment by Nojbee** [comment]
Thank you
