### ISSUE TITLE
How to restart when video stucks for 3 seconds

### ISSUE THREAD

**Issue by fakirpic** [videojs/video.js#3815]
Hi

when live stream stucks for 3 seconds like this
https://i.imgur.com/uIetKox.jpg
how can i restart it?

**Comment by misteroneill** [comment]
Thanks for submitting a bug report!

Unfortunately, we cannot take action on bug reports that do not adequately follow [the issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md). Following this template provides the Video.js team with a way to reproduce and investigate the bug you are reporting.

**Comment by misteroneill** [comment]
Further, this issue could be any number of things not related to video.js core (server, plugins, network, browser, etc).

**Comment by fakirpic** [comment]
its releated to my server,sometimes live stream stucks and restarts , btw i want stream restart itself

**Comment by fakirpic** [comment]
i need sample code please

**Comment by gkatsev** [comment]
Unfortunately, we can't really help without more information. It's possible that you can find more help by reading the [FAQ](https://github.com/videojs/video.js/blob/master/docs/guides/faq.md) or the [Troubleshooting Guide](https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md).

One thing you can try to restart is just giving the player the source again.

I'm going to close this now but if we get more information (by following the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md)) and a reduced test case, we can re-open this.
