### ISSUE TITLE
[Feature] Fully cache whole video in browser (not just a few minute)

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#3824]
Hi guys,

I'm running in to a problem, it not an issue with videojs but very relevant to post here.

Currently, when user click seek part of the video there are chance it will send a 206 http to server to ask for the part content of that file (I said chance but it will most likely to happen, it just didn't when you just click for a few seconds ahead).

![videokeep206load](https://cloud.githubusercontent.com/assets/7130705/20836831/c84dba74-b8d3-11e6-9bd0-3c5aa49a7a63.png)

As you can see, the video is 940 MB, but when I click seek part of it, it will keep send 206 http request to server, result in almost 4 GB. I have test with firefox and chrome, same result.

(The behavior even more unpredictable when sometimes it will display cache from disk if you click and drag ahead with low speed :\ - most of the time it will just download it again)

Compare to youtube, when the video is loaded, where ever user seek, it will not send anything, result immediately seek and play.

Here is my theory about that:

At first I thought maybe it write direct to disk, but according to http://caniuse.com/#search=filewrite it not possible, some html5 cache like webstorage not gonna work due to it limit, could be Blob url or just a normal javascript object (the last one).

I've try Blob and it does work (result in instant seek and play), I'll try a bit more and updating here.

Any idea is welcome.

**Comment by gkatsev** [comment]
Using a blob url makes sense but then you have to load a giant file into the browser. Another option is to forgot the browser altogether and use the MSE APIs to play the video yourself.
Unfortunately, this isn't really something that videojs is directly involved in, though, we would potentially bounce around ideas in our [slack](http://slack.videojs.com) channel.
