### ISSUE TITLE
Option to ignore video aspect ratio and size?

### ISSUE THREAD

**Issue by Programming4life** [videojs/video.js#3831]
Is there an option to ignore all the videos metadata and have the video element always take up the full page regardless of the aspect ratio of the video or size? Right now when I play a video the player gets resized to the video aspect ratio and size. I need it to not do this.

**Comment by gkatsev** [comment]
If you add `vjs-fill` class to the player, with a new enough version of Video.js, it'll fill up the parent element as much as it can.
