### ISSUE TITLE
How to check if the rmtp live stream is off?

### ISSUE THREAD

**Issue by exdestroyer** [videojs/video.js#3832]
## Description
I successfully played my rmtp live stream with video.js, but the problem is now I am not able to check when the stream is off. I tried on('error') and on('ended'), but it doesn't work

**Comment by gkatsev** [comment]
I would assume we trigger an `ended` event but I'm not sure about that.

Looking at the code it looks like it [should be triggering an `ended` event](https://github.com/videojs/video-js-swf/blob/master/src/com/videojs/providers/RTMPVideoProvider.as#L528-L536).

Also, is the question whether you can check if the stream is live or not? or that you've played the video and the stream finished broadcasting?
