### ISSUE TITLE
How to customize the button function

### ISSUE THREAD

**Issue by LittleXiaosi** [videojs/video.js#3843]
hi

I need some help，I want to use videojs for my webpage,but the fullscreen button I want to change the function,not use videojs function,I need to call some hybrid API of our app,so how can I change the function after I click  the FULLSCREEN button,and If I want to customize other button,what should I do?

**Comment by gkatsev** [comment]
I think our recommendation for that would be to turn off the default fullscreen button and make your own button which does what you want instead. Unfortunately, we don't have a good guide for creating buttons [yet](https://github.com/videojs/video.js/issues/3823) but there's some code you can start with [here](https://github.com/videojs/video.js/issues/3823).
As for turning the fullscreen button off, you can configure it like so:
```js
var player = videojs('player', {
  controlBar: {
    fullscreenToggle: false
  }
});
```

Hope that helps.
