### ISSUE TITLE
New Chrome Version 55.0.2883.75 causes download icon to appear in video player control bar

### ISSUE THREAD

**Issue by NickOttrando** [videojs/video.js#3844]
## Description
Since my Chrome recently updated to Version 55.0.2883.75, a download icon now appears in my video.js player on the far right side that didn't used to be there. I'm wondering if this is a bug, and if there is any way to hide the button because I do not see it listed in the API docs. 

## Steps to reproduce
Open a video.js player in chrome browser Version 55.0.2883.75.

### Expected
Expected to see no download button for the video.

### Actual
Download button appears in far right side of control bar.

I just saw the [release notes](https://googlechromereleases.blogspot.com/2016/12/chrome-for-android-update.html#gpluscomments) for Chrome 55 which mentions this feature, and am wondering how it can be hidden using videojs or using css on the native attribute. I realize this isn't specific to video.js and should probably be closed but hopefully this thread can help other people with same issue.

**Comment by gkatsev** [comment]
Unfortunately, the only recommendation I can give you is to use custom controls. I tried inspecting the DOM of the control bar and it has pseudo elements in the shadow DOM but they're marked internal and so it doesn't seem like you can target it.
![](https://cldup.com/q9C1nFWXN9.png).

And while you're here... can I recommend our great custom control bar? :D
