### ISSUE TITLE
¿How to change the current time format?

### ISSUE THREAD

**Issue by RodrigoMaster7** [videojs/video.js#3850]
Hello, I would like to change the format in which the current time is displayed in VideoJS, for example:

"0:23:07 / 3:02:54" to "23:07 / 3:02:54" or
"0:08:14 / 1:24:20" to "8:14 / 1:24:20"

That is, display the time only when required in current time.

Thank you.

Translated by Google

**Comment by RodrigoMaster7** [comment]
Thank Yoy :"v

**Comment by gkatsev** [comment]
Unfortunately, nothing yet. Dupe of https://github.com/videojs/video.js/issues/2931.
