### ISSUE TITLE
Force to rerender the video element

### ISSUE THREAD

**Issue by DonkeyInBeijing** [videojs/video.js#3852]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. I get a video element in a dialog and call videojs on this element
2. I close the dialog and destroy it, then reopen it , call videojs to rerender the video element

### Expected
I expected to see the video rerender formally as the first time.

### Actual
Actually get the error  Player "lvjs_ltile_video" is already initialised. Options will not be applied.

### Error output
Player "lvjs_ltile_video" is already initialised. Options will not be applied.

## Additional Information
Please include any additional information necessary here. Including the following:

**Comment by gkatsev** [comment]
Do you actually call `player.dispose()`? If the dialog is just removed from the DOM, videojs doesn't know anything about it and when trying to re-create the player it'll think that everything still works. So, right before the dialog is closed and the elements removed from the DOM, you should call `player.dispose()`, then you'll be able to call `videojs` without any issues.

**Comment by DonkeyInBeijing** [comment]
Thanks, Gary, it works now!
