### ISSUE TITLE
Add a hookOnce method

### ISSUE THREAD

**Issue by misteroneill** [videojs/video.js#3855]
Right now, `videojs.hook()` registers a callback to be called every time the hook fires - similar to `Events.on()`.

It would be useful to have a `videojs.hookOnce()` function, which would operate similarly to `Events.one()`.

For the time being, users can implement this themselves with something like:

```js
var myHook = function() {
  videojs.removeHook('beforesetup', myHook);
  // Do other stuff...
};

videojs.hook('beforesetup', myHook);
```

**Comment by gkatsev** [comment]
It's in!
