### ISSUE TITLE
RTMP stream via OBS doesn't play anything on web 

### ISSUE THREAD

**Issue by DeyvidDimitroff** [videojs/video.js#3859]
## Description
I tried passing my stream from OBS via nginx server to web page but it displayed nothing.. All it does was keeping the big centered button without happening anything when clicking on it :/

## Steps to reproduce

1. Started nginx server on localhost
2. Started the OBS stream
3. Tried to play it on videojs player but didn't played anything

```
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="video-js.min.css">
    <link href="http://vjs.zencdn.net/5.11.9/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js">  </script>
<script src="http://vjs.zencdn.net/5.11.9/video.js"></script>
    <script src="video.min.js"></script>
</head>
<body>
   <video id="livestream" class="video-js vjs-default-skin vjs-big-play-centered"
     controls autoplay preload="auto" width="1280" height="720"
     data-setup='{"example_option":true}'>
           <source src="rtmp://127.0.0.1:2035/live/1234" type='rtmp/flv' />
   </video>
</body>
</html>

```

### Expected
Live stream of my web camera / window capture or whatever I try to capture displayed on the browser.

### Actual
It did stayed with the big play button which on click did nothing.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
OBS v0.659b
#### videojs
Last version available as of writing this topic.
#### browsers
Google Chrome (Last version available as of writing this topic.)
#### OSes
Windows (OBS, Chrome) Linux(nginx)

**Comment by gkatsev** [comment]
For better or worse videojs uses the & as the connection and stream separator. This means that instead of `/` between `live` and 1234 you should use a &.

**Comment by Fenrirthviti** [comment]
Appears to be related to #3849. I've spoken with this user directly, he's probably just not as patient waiting for the flash tech to load.

**Comment by discord3463456473** [comment]
I am having the same issue with an RTMP stream from OBS to a nginx server to a web page running Video.js.

This is my html file :

<!DOCTYPE html>
<html>
<head>
<title>RTMP Embed</title>
<link href="http://vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/4.11/video.js"></script>
</head>
<body>
<h1>RTMP Embed</h1>

<video id="streamContainer" class="video-js vjs-default-skin" controls preload="auto" width="640" height="320" data-setup='{}'>
    <source src="rtmp://IP ADDRESS/live/&mp4:test" type='rtmp/fla'>
</video>

</body>
</html>

Any thoughts?
