### ISSUE TITLE
Allow video.js to be run in node

### ISSUE THREAD

**Issue by nicksorrentino** [videojs/video.js#3869]
## Description
I am server rendering my frontend using node.  We are unable to server render any modules that import video.js.  Due to running `document.createElement`

https://github.com/videojs/video.js/blob/881cfcb346b588013768f538faf3d5f20ce42109/src/js/utils/browser.js#L74

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. run node dist/video.js
2. See stacktrace `TypeError: _document2.default.createElement is not a function`

### Expected
Video.js to not crash

### Actual
It crashes running  `document.createElement`

### Error output
`TypeError: _document2.default.createElement is not a function`

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
5.12.6
#### browsers
what browser are affected? None
#### OSes
what platforms (operating systems and devices) are affected? node any

cc @ljharb

**Comment by misteroneill** [comment]
You should be able to `require`/`import` video.js in Node, but you shouldn't use the `dist/video.js` file - that is the browser-global distributable.

Rather, use `es5/video.js`, which is the `"main"` entry-point for the package (using `require('video.js')` should do this automatically).

**Comment by ljharb** [comment]
That's what we're requiring - but since everything is browserified/webpacked, the same code will run in node and in the browser for us. Why is document.createElement being called without checking for its existence first, even in the browser build?

**Comment by misteroneill** [comment]
@ljharb @nicksorrentino Will #3889 address your issue? It allows `require('video.js')` to not throw; so, modules that import video.js should be fine. However, _calling_ `videojs()` will almost certainly throw outside of a browser.

**Comment by ljharb** [comment]
@misteroneill thanks! close - i made some comments. It's totally fine for anything to throw in node as long as it's not *upon require*.

**Comment by misteroneill** [comment]
Agreed 💯  thanks for bringing it to our attention!

**Comment by gkatsev** [comment]
This should be available as part of 5.15.1, in the `next` tag on npm. Hopefully, it fixes these issues for good.

**Comment by ljharb** [comment]
Thanks!

**Comment by nicksorrentino** [comment]
Thank you!
