### ISSUE TITLE
Video can not autoplay on mobile

### ISSUE THREAD

**Issue by giangmd** [videojs/video.js#3874]
I just try set autoplay on video tag html, setup in videojs BUT no anyway auto play my video on mobile.
It is ok on laptop

**Comment by gkatsev** [comment]
Unfortunately, this is a browser limitation on mobile. Most mobile browsers will not autoplay. iOS10 recently added the ability to autoplay if there is no audio in the video or if the video has been muted. I think some other browsers are moving towards that as well.
Hope that helps.
