### ISSUE TITLE
Setting "defaultVolume" automatically possible? with latest version 5 [HELP REQUEST}

### ISSUE THREAD

**Issue by tweed** [videojs/video.js#3875]
days now trying to find way to automatically set defaultvolume - using latest VJS version - can do regular HTML5 onclick button to manually lower volume though **automatically setting a lower default "volumeLevel" has eluded me**

I have done and been everywhere i can think of - could really use some help
guessing a lot of people would like to lower the default volume automatically

i have found and am going to try/use persistent volume plugin as well - thanks!

**do you know how to get the default to be WAY lower?**

**Comment by mister-ben** [comment]
You can set the volume when the player is ready, e.g.

```
videojs('my-player', {}, function() {
  this.volume(0.5);
});
```

**Comment by tweed** [comment]
mister-ben !!! 
fantastic to have had your reply (just got back)

I've done a wee struggle with your code - can i ask where the code goes - within script tags EXACTLY as you've written? I have a single HTML page with working video - how does your code know when the player is ready - basically just need to get your code to work with the most basic videojs example - it's so hard to do.

**Comment by tweed** [comment]
WOOHOO! boy, i do struggle a fair bit - SUCCESS i believe - thanks to your help (no reply needed of course)

I used this - which is the 2nd 'by ID' example in this section
Alternative Setup for Dynamically Loaded HTML
`
  <script>
  videojs(document.getElementById('vid001'), {}, function() {
  this.volume(0.2);
});
    </script>
`

**Comment by gkatsev** [comment]
Glad you figured it out.
