### ISSUE TITLE
Video.js not working in Weebly

### ISSUE THREAD

**Issue by 5t3ph4n13** [videojs/video.js#3876]
## Description
When using the Video.js CDN hosted header code and the body code in Weebly it doesn't show up on the website, but works when I test it on html test websites, such as http://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro

Steps:

1. Go to Pages > SEO > Header, and paste in the video.js host code:

```
<head>
  <link href="http://vjs.zencdn.net/5.8.8/video-js.css" rel="stylesheet">

  <!-- If you'd like to support IE8 -->
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>
```

2. Drag an html embed box into the site page and paste the video code:

```
<body>
  <video id="my-video" class="video-js vjs-default-skin vjs-big-play-centered" controls preload="auto" width="950" height="534" data-setup="{}">
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
    <p class="vjs-no-js">

      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="http://vjs.zencdn.net/5.8.8/video.js"></script>
</body>
```

3. Publish your website.

Expected results:
I expected to see the default video.js player and to be able to click play and watch the video.

What actually happened:
What happened was that there was no player at all on the website, not even the default html5 player that all the browsers have.

Additional information:
what version of videojs does this occur with? - Version 5.8.8

**Comment by mister-ben** [comment]
I had a quick look at "Weebly". They are already including an old version of video.js (4.2.2) on the pages they generate, and two versions won't co-exist. You could get a player to initialise with `videojs('my-player')` but their styles will hide it. You may be able to override these styles - try reaching out to their support for help with that.

The simplest option is likely to be putting a player on a standalone page and embedding with an `iframe`.
