### ISSUE TITLE
How to play rtmp stream with video.js in my phone browser

### ISSUE THREAD

**Issue by houruicheng** [videojs/video.js#3878]
## Description
Hi, I would like to play rtmp streaming in the mobile browser using video.js, but it does not work.
 Can be run in the PC browser. 
Is this possible? 
Or are there other solutions? 
Grateful!

**Comment by gkatsev** [comment]
Rtmp more or less requires flash to run, which isn't available in mobile devices. Unfortunately, there isn't much you can do.
