### ISSUE TITLE
CDN links at in Readme

### ISSUE THREAD

**Issue by arpit1997** [videojs/video.js#3895]
CDN links for `videojs` needs to be updated from
```
<link href="//vjs.zencdn.net/5.11/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/5.11/video.min.js"></script>
```
to
```
<link href="http://vjs.zencdn.net/5.11/video-js.min.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/5.11/video.min.js"></script>
```

**Comment by gkatsev** [comment]
Is there a reason why you think that we should add the protocol? We're specifically using protocol-relative urls there. That way, if a user copies that url, it'll load via http on an http site or on https on an https site.

I'm going to close this for now, but we should continue the discussion and we can always re-open if necessary.
