### ISSUE TITLE
Playing video and displaying document one after each other

### ISSUE THREAD

**Issue by rpundlik** [videojs/video.js#3900]
I am using videoJS for LMS (Learning management system) project where we need to show videos,documents one after each other.

For playing with video its working fine, but lets see I have some document (pdf,word,ppt) to show after the video is ended, then in which event I need to check whether the next object is video,document or something else.

For e.g. I want to track below sequence.
1. Some video will be played.
2. document is shown (After reading the document by on clicking on 'next' button video is played)
3. some another video is shown

Does videoJS provides such functionality to know the loading objects/next-prev object information OR to handle the sequence of events ?

Regards,
Rohit

**Comment by mister-ben** [comment]
Video.js emits an `ended` event when the video ends.

```
player.on('ended', function() {
  // video has ended, do something
});
```

If you are looking to load a new video into the existing player in 3, you can use `src()`:

    player.src([{ type: 'video/mp4', src: '//example.com/video.mp4'}])

**Comment by misteroneill** [comment]
Also, if you're switching from a Video.js player to something else (text, document, etc) you'll probably want to dispose your player so you don't leak memory.

```js
player.dispose();
```
