### ISSUE TITLE
Can't display video files stored in AWS S3 bucket.

### ISSUE THREAD

**Issue by cedricve** [videojs/video.js#3903]
## Description
I'v been using VideoJS for a while, and it works great. Now I want to display videos, which are stored on AWS S3 and are protected by a signed link. This works when I use the link directly in the HTML5 video object, but doesn't if I want to display it in VideoJS. PS: I also tried to use public files from S3, so it doesn't have to do anything with permissions.

Result: 

![screen shot 2016-12-31 at 12 00 48](https://cloud.githubusercontent.com/assets/1546779/21577148/cd6e5642-cf50-11e6-8b0e-f3b29078246f.png)

Payload:

![screen shot 2016-12-31 at 11 55 57](https://cloud.githubusercontent.com/assets/1546779/21577144/b40bb3f2-cf50-11e6-8ff4-ce521ebb34b9.png)

#### videojs
^5.14.1
#### browsers
all
#### OSes
all
### plugins
videojs-playlist

**Comment by cedricve** [comment]
Found out that AWS S3 objects don't contain the Connection: keep-alive header. Is there any way to do this, or is CloudFront required?

http://stackoverflow.com/questions/36530707/how-to-enable-keep-alive-connection-in-aws-s3-or-cloudfront

**Comment by cedricve** [comment]
I've add the attribute `crossorigin="anonymous"` attribute to the video element. After removing this, the issue was resolved.

**Comment by joe455** [comment]
@cedricve Any luck solving this issue.
