### ISSUE TITLE
Include videoJS on a WordPress plugin

### ISSUE THREAD

**Issue by br0k3n** [videojs/video.js#3904]
Hi,

great plugin 👍 
I would include it in a WordPress plugin, the main problem is that I've to use only local files, so I need to change the path to "video-js.swf", the fonts and all other files.

Please, could you explain me how can I procede?

Thanks

**Comment by gkatsev** [comment]
If you download the zip from the [releases](https://github.com/videojs/video.js/releases/tag/v5.14.1) or copy over the dist folder from npm or git, everything is set up to be local. The only thing you'd need to potentially change is the swf url location when you load videojs see the [sandbox for an example](https://github.com/videojs/video.js/blob/master/sandbox/index.html.example#L16).

Also, not sure whether it applies but there's a videojs wordpress plugin already.
