### ISSUE TITLE
Clicking muted icon after setting volume slider to 0% has no user-visible effect

### ISSUE THREAD

**Issue by kevinlitchfield** [videojs/video.js#3909]
Clicking the muted icon (<img width="24" alt="screen shot 2017-01-03 at 6 25 01 pm" src="https://cloud.githubusercontent.com/assets/11491159/21626879/f6de45bc-d1e1-11e6-8e87-b6f0a9271d9a.png">) after setting the volume slider to 0% has no user-visible effect.

![videojs](https://cloud.githubusercontent.com/assets/11491159/21626859/bef7164c-d1e1-11e6-90e3-70941a619e49.gif)

This is because:

- The muted icon is displayed whenever `volume` is `0`, regardless of whether `muted` is `true` or `false`.
- Clicking the muted icon toggles the `muted` property and has no effect on `volume`.

So in this case, since `volume` is `0`, the muted icon doesn't change on repeated clicks, despite the changing `muted` property and despite the changing tooltop text ("Mute"/"Unmute"). This has confused users of the app I use Video.js in.

Two suggestions for a solution:

### 1. YouTube solution

![youtube](https://cloud.githubusercontent.com/assets/11491159/21626815/7f0c1d0c-d1e1-11e6-94f4-f0712dc11a37.gif)

When clicking the muted icon after moving the volume slider to zero, **unmute and set `volume` to the last value before it was manually set to `0`**. This is what YouTube does, and I think this is the best UX.

### 2. macOS solution

When clicking the muted icon after moving the volume slider to zero, **unmute and show the normal volume icon, while keeping `volume` at `0`**. This is what macOS does.

![macos](https://cloud.githubusercontent.com/assets/11491159/21626808/71ffa598-d1e1-11e6-9248-2981c396613f.gif)

Would the maintainers consider a PR addressing this issue?

**Comment by mister-ben** [comment]
There was a discussion about this a little while back, maybe on Slack. I don't recall whether a consensus was reached but I'd agree that it would be better UX if clicking unmute were to set volume to something greater than 0 if volume is 0.

**Comment by gkatsev** [comment]
We're in the process of making a major update to videojs. Making the change sounds ok to me.
@videojs/core-committers any thoughts?

**Comment by heff** [comment]
Just asked a friend from youtube about the thinking behind their behavior and they consider a slide-to-zero as the same action as clicking the mute button, storing the volume at the beginning of the slide as the previously set volume (even though the volume is updated as you slide). So when you click the mute icon after that it'd go back to where you were at the beginning of the slide.

That actually makes a lot of sense to me.

Also related is a conversation on font-awesome: https://github.com/FortAwesome/Font-Awesome/issues/288#issuecomment-16835466

**Comment by Raveem13** [comment]
Please look into my code for dependency between volume bar and mute button and also buffer visibility in progress bar.  [https://github.com/Raveem13/BootStrap/blob/Functionalities/cvideoplayer02/scripts.js](url)
