### ISSUE TITLE
MPEG(divX) .mp4 not support

### ISSUE THREAD

**Issue by uikoo9** [videojs/video.js#3911]
this mp4:http://7sbn90.com1.z0.glb.clouddn.com//danmu/05.mp4

in your website not support

![qq 20170104183318](https://cloud.githubusercontent.com/assets/10345351/21639777/c391dff4-d2ac-11e6-8fe5-abfb3ed666f6.png)

**Comment by mister-ben** [comment]
Browsers don't support the divx codec. You need to use h264 video and aac or mp3 audio in MP4.
