### ISSUE TITLE
Tracks and track related buttons are not working

### ISSUE THREAD

**Issue by chemoish** [videojs/video.js#3917]
## Description

This issue was created to try to further understand the direction and issues of `TextTrack`'s and `AudioTrack`'s.

I am recently having race conditions when generating `TextTrack` controls (need to verify environments)—sometimes the button doesn't exist, but I have also noticed that `AudioTrack` and `CaptionTrack`s are no longer working as expected (need to verify environments).

Some issues include…

- UI isn't generated
- Cues aren't generated, but the track shows in the DOM
- Cannot toggle between menu items
- Default option is not represented in the UI

#### Video.js Test 1 (ran in `videojs-contrib-dash` sample)

- `video.js#5.10.8`
- `videojs-contrib-dash#2.3.0`
- `.mpd` file
- embedded `en` (default) and `es` captions
- embedded `en` and `es` audio
- embedded `es` 5.1 audio

1. `CaptionsMenuButton` created
2. `ChaptersMenuButton` represents embedded `en` and `es` `TextTrack`s
3. `CaptionsMenuButton` UI does not reflect that `en` is defaulted (even though it is)
4. `es` doesn't work
5. Toggling between `TextTrack` will make all `TextTrack`s stop working

 Issue 3 applies to Chrome, but works in Safari.
 Issue 5 applies to Chrome, but works in Safari.

#### Video.js Test 2 (ran in `videojs-contrib-dash` sample)

- `video.js#5.15.1`
- `videojs-contrib-dash#2.6.0`
- `.mpd` file
- embedded `en` (default) and `es` captions
- embedded `en` and `es` audio
- embedded `es` 5.1 audio

1. `CaptionsMenuButton` is not created

#### Dash.js Test 1 (ran in http://dashif.org/reference/players/javascript/v2.1.1/samples/dash-if-reference-player/index.html)

- `.mpd` file
- embedded `en` (default) and `es` captions
- embedded `en` and `es` audio
- embedded `es` 5.1 audio

1. `CaptionsMenuButton` is created
2. `ChaptersMenuButton` represents embedded `en` and `es` `TextTrack`s
3. `ChaptersMenuButton` properly defaults to `en`
4. `ChaptersMenuButton` properly toggles between `en` and `es`

#### Dash.js Test 1 (ran in http://dashif.org/reference/players/javascript/v2.4.0/samples/dash-if-reference-player/index.html)

- `.mpd` file
- embedded `en` (default) and `es` captions
- embedded `en` and `es` audio
- embedded `es` 5.1 audio

1. `CaptionsMenuButton` is created
2. `ChaptersMenuButton` represents embedded `en` and `es` `TextTrack`s
3. `ChaptersMenuButton` properly defaults to `en`
4. `ChaptersMenuButton` properly toggles between `en` and `es`
5. `AudioMenuButton` is created
6. `AudioMenuButton` represents embedded `en` and `es`, but properly excludes `es` 5.1
7. Audio and captions seem to be tied together, changing the caption will change the audio, but you cannot have `en` captions and `es` audio.

## Additional Information

I have seen some related content, but I am not sure if they are actually related…

- https://github.com/videojs/video.js/pull/3798
- https://github.com/videojs/video.js/pull/3794
- https://github.com/videojs/video.js/issues/1866
- etc.

#### Oses

OS X El Capitan#10.11.6

#### Browsers

Chrome#55.0.2883
Safari#10.0.1

**Comment by chemoish** [comment]
I don't have a publicly available sample file, but I am working on getting one I can share.

**Comment by gkatsev** [comment]
I think it's been fixed.
