### ISSUE TITLE
`mouseup` over `MuteToggle` after dragging `VolumeBar` to zero incorrectly fires `handleClick` on `MuteToggle`

### ISSUE THREAD

**Issue by kevinlitchfield** [videojs/video.js#3918]
After clicking and dragging `VolumeBar` to zero, if the user releases the mouse over `MuteToggle`, `handleClick` fires on `MuteToggle`. Watch the checkbox tracking the `muted` property in these screencaptures:

### `mouseup` over `MuteToggle`, `handleClick` fired on `MuteToggle` and `muted` is toggled to `true`

![click](https://cloud.githubusercontent.com/assets/11491159/21685972/9973213a-d331-11e6-91b1-0038039d8d70.gif)

### `mouseup` over `VolumeBar`, `handleClick` not fired on `MuteToggle` and `muted` remains `false`

![noclick](https://cloud.githubusercontent.com/assets/11491159/21685943/7707220e-d331-11e6-80b5-14085b6c3e15.gif)

Currently, this bug has no implications for the user, because as discussed in #3909, clicking `MuteToggle` after setting the volume slider to 0% has no user-visible effect. But fixing it is important to addressing #3909, because if clicking `MuteToggle` when `volume` is zero sets `volume` to something greater than zero, then users will be able to accidentally trigger that behavior by `mouseup`ing over `MuteToggle` after dragging `VolumeBar` to zero.

**Comment by misteroneill** [comment]
Thanks for the nice report. 👍

**Comment by gkatsev** [comment]
This is probably something we should fix for 5.x. As part of 6.0, we're moving to a better, and more accessible volume control which would actually be two separate controls, so, it potentially won't be an issue. But we should keep an eye out for this when working on it. /cc @BrandonOCasey.

**Comment by BrandonOCasey** [comment]
This should be fixed in master now that #3957 is merged in

**Comment by gkatsev** [comment]
I think this is fixed with the new volume behavior in 6.0.
