### ISSUE TITLE
How to set  buffer(latency < 500ms) on clicent

### ISSUE THREAD

**Issue by palyak47** [videojs/video.js#3924]
## Description
On my html =>
```html
<source src="rtmp://127.0.0.1/livepkgr/264" type="rtmp/flv" />
```
When I play rtmp streaming, the latency timing > 1000 ms on my viewer.
Maybe I need checked buffer size, but I doesn't 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Can I change it?   EX: setbuffer(200);     latency < 500ms

**Comment by gkatsev** [comment]
Unfortunately, we don't really support doing that. We're also unlikely to be changing to adding functionality to change the buffer size from javascript as flash is becoming less and less important.
However, you probably could to update the [swf with a different buffer time](https://github.com/videojs/video-js-swf/blob/master/src/com/videojs/providers/RTMPVideoProvider.as#L425). You could then tell videojs to use your build of the swf by setting the `videojs.options.flash.swf` property.

You should also check out this [answer](https://github.com/videojs/video.js/blob/master/docs/faq.md#q-how-can-i-play-rtmp-video-in-videojs) in the FAQ, regarding RTMP urls. We except the connection and stream to be separated by an `&`.

Hope that helps.
