### ISSUE TITLE
Github downloaded videojs-contrib-media-sources.min.js in IE9 under the error

### ISSUE THREAD

**Issue by Tinywan** [videojs/video.js#3926]
## Description
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. {"code":4,"message":"No compatible source was found for this media."}

**Comment by gkatsev** [comment]
Unfortunately, that project does not support IE9.

**Comment by gkatsev** [comment]
It only supports IE10+.

**Comment by Tinywan** [comment]
@gkatsev Thank you, has been resolved
