### ISSUE TITLE
Return a Promise From play() when possible

### ISSUE THREAD

**Issue by brandonocasey** [videojs/video.js#3927]
## Description
There is currently a PR (#3907) that returns the native value of play to the user. In some cases (such a newer version of Chrome) this will be a Promise. 

I think that we should try to always return a Promise if the browser supports them or a Promise library is provided (`window.Promise || this.options_.Promise`). This means that we will return the native Promise from `play()` if it is returned and return a "psuedo-native" Promise if `play()` does not return a Promise. 

We will also have to be mindful of browsers that don't support promises at all and the [specification for Promises from play](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-play).

**Comment by misteroneill** [comment]
This was actually a question at the meetup yesterday: would we support a polyfill or creating our own promise. So, that's a vote in this direction, I'd say.

**Comment by gkatsev** [comment]
Yup, I don't want to write our own promise implementation :)

**Comment by misteroneill** [comment]
Sorry, I meant we'd return a Promise as @BrandonOCasey is suggesting - not "create our own". Poor phrasing. 😆

**Comment by shikkaba** [comment]
Is there any update on this?

**Comment by gkatsev** [comment]
@shikkaba in Video.js v6, we already are returning a Promise from `play()` if the browser supports this. We have not made progress on making our own promise for the times that the browser doesn't support it.

**Comment by shikkaba** [comment]
@gkatsev Thank you for the reply. I'm just wondering because in Chrome I'm seeing the following:
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. [object Object]
 /absorica/js/video.js:489:47 logByType()
 /absorica/js/video.js:607:10 Function.log.error()
 /absorica/js/video.js:22620:11 Player.error()`

**Comment by KevinBrogan** [comment]
videojs 7 does not return the native result from play

**Comment by gkatsev** [comment]
Actually, re-opening this one for the follow-up work for IE11 and browsers that don't return a `promise` from `play()`.

**Comment by Puritanic** [comment]
@gkatsev Any update on this? :)

**Comment by gkatsev** [comment]
So, looks like this issue should be closed. At some point we did add promise support for older browsers. However, you must either provide videojs with a promise polyfill or include a promise polyfill globally on those platforms.

@Puritanic can I ask you to open a new issue with more info filled out in the issue template? Like video.js versions and preferably a reduced test case.
