### ISSUE TITLE
Default skin is unattractive

### ISSUE THREAD

**Issue by kaatt** [videojs/video.js#3928]
Compared to YouTube, vimeo, or [this 3rd party video player](http://plyr.io), video.js's skin is largely unattractive.

I believe a nicer looking skin would make the project more popular.

Is changing the default style planned for a future update or open to PRs?

**Comment by mmcc** [comment]
Thanks for the feedback, we're always open to PRs and suggestions for how we can improve things. 

One thing to keep in mind is that we intentionally designed the default skin to get out of designer's way and to be a "blank canvas" for people to build on top of. YouTube and Vimeo are designed to be stylistic, branded players with very little to no room for modification, so we actively avoided going that route. What we'd *love* to see is a thriving third-party ecosystem of skins that cover all sorts of styles and preferences!
