### ISSUE TITLE
Captions/Subtitles for iPhone and iPad ?

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#3932]
Captions/Subtitles does not work on the iPhone and ipad.
How to fix a bug?
Version of Videojs   5.14.1

**Comment by gkatsev** [comment]
Please answer the questions in the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md) as thoroughly as possible. And be as details as possible in what is happening. Are there errors? What does "doesn't work" mean in this case?
Also, this part of the [text track guide](https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#text-tracks-from-another-domain) might be helpful.

**Comment by surikat1978** [comment]
Subtitles shows, if  set  nativeTextTracks:true 
instead    nativeTextTracks:false
this is normal? in this case, the iPhone shows.

**Comment by gkatsev** [comment]
Yup, if you want text tracks on iphone in fullscreen, you need to use native tracks.
