### ISSUE TITLE
[IE8] Object doesn't support this action 

### ISSUE THREAD

**Issue by DrizzlyOwl** [videojs/video.js#3938]
## Description
When loading a HTML5 video in Internet Explorer 8, (whilst including a shim in the head as per the docs), an error is thrown "Object doesn't support this action".

Reduced Test Case: http://jsbin.com/xaxegiw/edit?html,js,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load the [test case preview](http://output.jsbin.com/xaxegiw) in IE8 or IE11 and set 'Emulation Document Mode' to IE8.
2. View Javascript Console

### Expected
IE8 shim to allow the main script to execute and for the video to display.

### Actual
An error occurs with the standard video.js file and any further javascript execution stops.

### Error output
`File: video.js, Line: 16868, Column: 3` - `Object doesn't support this action`

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
```
5.15.1
5.14.1
```
Not tested any further
#### browsers
Internet Explorer 8
or newer Internet Explorer versions running in IE8 Document Mode
#### OSes
what platforms (operating systems and devices) are affected?
Windows only 
### plugins
n/a

**Comment by misteroneill** [comment]
The test case appears to be using 5.0.2. The line in question is looking at `console[method].apply`, which would error in IE8 if you tried to call it.

In 5.14, that line appears to call `Array#splice` which IE8 does support. So, I suspect the issue is you're using Video.js 5.0.2 (check by `videojs.VERSION` in console).

**Comment by jimmywarting** [comment]
why do ppl still support ie8?

**Comment by DrizzlyOwl** [comment]
@misteroneill Thanks for the prompt response. Closing this issue as obviously user error. Updated version seems to work fine.

**Comment by chetanrbhat** [comment]
I am still getting similar issue in IE8 : SCRIPT445: Object doesn't support this action. 
I have included the IE shim and i am using videojs 6.2.0.

Code:

<!DOCTYPE html>
<html>
<head>
	<title></title>
	
	<link href="./video-js-6.2.0/video-js.css" rel="stylesheet">
	
  	<script src="./video-js-6.2.0/ie8/videojs-ie8.js"></script>
</head>
<body>
<video id="myvideo" class="video-js vjs-big-play-centered" controls
 preload="auto" width="200" height="100" poster="./video_thumbnail.png" data-setup="{}" >
<source src="./ACCB_test_video.mp4" type='video/mp4'>
</video>
 <script src="./video-js-6.2.0/video.js"></script> 	
</body>
</html>

**Comment by y4my4my4m** [comment]
Same error on 6.7.1
