### ISSUE TITLE
Support for RTSP

### ISSUE THREAD

**Issue by mburger81** [videojs/video.js#3939]
## Description
We are using your player and it works great. We have a question about the formats and streams you support.

Does you support an RTSP or an RTSPH stream?

I tried doing something described like here
http://stackoverflow.com/questions/36404307/live-streaming-in-video-js-is-not-working-in-android-firefox
`<source src="rtsp://****" type="rtsp/mp4"/>`
but it doesn't work.

So my question is, do you support it?
If not, this would be a **feature request** :)
Do you think you can support something like that?

thx

**Comment by gkatsev** [comment]
Hi,

Thanks for your interest in videojs. We don't currently support RTSP. We have some support RTMP but we're actually in the process of removing flash from core. I think our aim is to try and keep core focused on just what you can do natively in browsers while supporting the usecases of adding more formats. For example, we have the videojs-contrib-hls plugin that allows a user to play back HLS but it doesn't ship with videojs directly. RTSP support, like HLS, would belong in a separate plugin that users can add or not.
However, we'd be happy to help with any issues that arise when working on such a plugin.

Thanks.
