### ISSUE TITLE
Synchronized multi stream support

### ISSUE THREAD

**Issue by martabel** [videojs/video.js#394]
Hi all, 
I'm Martin Abel and I'm involved in the community project Opencast Matterhorn. Matterhorn is a lecture recording tool with a multi stream web player, see http://opencast.org/matterhorn/feature-tour for more information's about the project.
Our currently multi stream player is very outdated and we want to develop a new one with plugin support and a multi stream html5 video-display. In our research about a video-display we find the videoJS project. The videoJS player implements many of our issues but without support of synchronized multi streams. We have a developer team which can manage this issue and we want to share our results with the videoJS project in hope that a next version of videoJS has a integrated multi stream support. My question here is, whether the videoJS should support multi streams? And can we count on your support?

regards
Martin

**Comment by Surt** [comment]
@martabel did you finally release a videojs multistream plugin? I found another player fully "opencast" compatible but we will love to use videojs in our solution (good community).
