### ISSUE TITLE
IE11 "Function expected" error.

### ISSUE THREAD

**Issue by raasumy** [videojs/video.js#3940]
## Description
IE11 returns error in console that states Function expected. See screenshot below.

### Expected
Please describe what you expected to see.

### Actual
I have HLS stream and once m3u8 url is passed to videojs this error happens. Works like charm in Chrome or Firefox.

### Error output
![image](https://cloud.githubusercontent.com/assets/2698773/21932793/acb19516-d9a2-11e6-9d2f-84277f28db5f.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
latest version
#### browsers
IE11
#### OSes
Win 7 x64
### plugins
ima
ads
hls
media sources

**Comment by gkatsev** [comment]
We've done a lot of work in this area so, hopefully, it's fixed since. Please retry using latest version of contrib-hls and video.js. If it's still an issue, we can re-open this issue (or open a new one against contrib-hls :)).
