### ISSUE TITLE
[IE9] remaining time control is too wide on IE9

### ISSUE THREAD

**Issue by EricSousaLopes** [videojs/video.js#3952]
## Description
The remaining time control is too wide on IE9
So the timeline seems too small.

[captureie9videojs]
(https://cloud.githubusercontent.com/assets/25181081/22031594/5ea3a46c-dce1-11e6-8709-112ba2eb176f.JPG)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Go to http://videojs.com/ under IE9 

### Expected
Controls are well aligned

### Actual
The remaining time control is too wide on IE9

### Error output
N/A

#### videojs
5.15.1
#### browsers
IE9

#### OSes
Windows7

### plugins
N/A

**Comment by gkatsev** [comment]
My comments from slack:
```
looks like the remaining-time control is super wide for some reason
ah, I think it's because ie9 is bad at math or something
with `width: auto` it ends up taking the most possible room instead of least possible room
```

**Comment by BrandonOCasey** [comment]
I am working on this alongside the volume accessibility changes (as they make the problem much worse). Seems that `width: 0px; white-space: nowrap;` on `.vjs-control.vjs-time-control.vjs-remaining-time` fixes the problem for ie8/ie9 but breaks chrome etc

**Comment by gkatsev** [comment]
I believe this is fixed by https://github.com/videojs/video.js/pull/3983
