### ISSUE TITLE
Video.js  Playlist  for RTMP Video

### ISSUE THREAD

**Issue by zxy12666** [videojs/video.js#3954]
## Description
Recently I need to use Video-js to do RTMP format video play in the project，I use playlist.js to make a play list;but when I click the list to switch video ,the video's src will wrong .Plug in tips in playlist “data-src“” do not need to write file extensions, but when I click list "data-src" will be followed by "mp4"instead of "sdp",I don't konw why,If you know how to solve please contact me ,thks.

### Error output
![image](https://cloud.githubusercontent.com/assets/23500521/22100982/59f41c76-de6c-11e6-9e5a-8db2ef0110b5.png)
the src is wrong ,the right file extensions is "sdp" ,rtmp://182.105.82.16/live/839855235.sdp,but it always
mp4
## Additional Information
this is my code:
![image](https://cloud.githubusercontent.com/assets/23500521/22101676/5ed65512-de6f-11e6-86d8-71da9b52b398.png)

#### videojs
5.4.6
### plugins
video-js playerlist.js

**Comment by mister-ben** [comment]
Can you provide a reduced test case? It's hard to offer much in the way of help from a screenshot of partial code, other than the DOM doesn't look like the playlist plugin I'm familiar with.

**Comment by gkatsev** [comment]
Also, from the screenshot, it looks like the other playlist items don't have a type associated with them. Types are super important in figuring out what and how to play things and figuring it out just from urls ranges from hard to impossible.

**Comment by gkatsev** [comment]
We cannot help further without a reduced test case, unfortunately.
