### ISSUE TITLE
Problem with rtmp source playing to iOS devices 

### ISSUE THREAD

**Issue by therealmrzippy** [videojs/video.js#3965]
Here's my code on index.html (converted to text file):

[index.txt](https://github.com/videojs/video.js/files/720924/index.txt)

Plays fine in a computer browser (Chrome, Firefox) but I get "no compatible source was found for this media" when attempting to view on iOS 10 devices.

The source of the video encoding is a Raspberry Pi2, running raspbian Jessie. FFMPEG is installed, and we use this line of code to start the encoding:

raspivid -w 800-h 600 -fps 15 -t 0 -b 1800000 -o - | ffmpeg -y -f h264 -i - -c:v copy -map 0:0 -f flv -rtmp_buffer 100 -rtmp_live live rtmp://NGINX/live/hd

what Am i doing wrong? ideas?

I've tried putting in various data-setup options mentioned, as well as videoplayer functions.. but to no avail.

**Comment by gkatsev** [comment]
Unfortunately, RTMP is not playable on devices that do not have flash available like iOS. 
This is answered in our FAQ as well: https://github.com/videojs/video.js/blob/e3424f6a4d19cf8117946fefe6aa6ccf23a2a7e3/docs/faq.md#q-how-can-i-play-rtmp-video-in-videojs

**Comment by mister-ben** [comment]
Consider using HLS for live streaming. Mobile browsers have native support. You'll increasing find end users' browsers lacking Flash or with Flash disabled, but HLS can cover desktop too: [videojs-contrib-hls](http://github.com/videojs/videojs-contrib-hls) adds support for HLS without Flash to modern desktop browsers.
