### ISSUE TITLE
Videojs in the Android Browser

### ISSUE THREAD

**Issue by cytGitHub** [videojs/video.js#3966]
Videojs in Andrews phone will call the system player, how to prohibit the system call the player? Or is there any hack method ？

**Comment by mister-ben** [comment]
Sorry, I'm not sure what you are asking. I don't know of a modern Android phone that does not play HTML5 video.

**Comment by cytGitHub** [comment]
thank you!


原始邮件
发件人:mister-bennotifications@github.com
收件人:videojs/video.jsvideo.js@noreply.github.com
抄送:常运涛_Yesssh_github@163.com; Authorauthor@noreply.github.com
发送时间:2017年1月24日(周二) 17:46
主题:Re: [videojs/video.js] Videojs in the Android Browser (#3966)


Sorry, I'm not sure what you are asking. I don't know of a modern Android phone that does not play HTML5 video.
