### ISSUE TITLE
KnockoutJS and VideoJS Not Working Together

### ISSUE THREAD

**Issue by SteveV0189** [videojs/video.js#3967]
## Description
Briefly describe the issue.
When using a foreach loop on an array to spawn videos using VideoJS, the video no longer functions as expected. Included in the test case are Knockout-spawned videos with and without <source> tags, as well as a normally-functioning video without a source tag, and 3 buttons to attempt to switch the sources of each. 

Minimal Test Case: https://shifty.site/uploads/files/test.html
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Create an array within a viewmodel from Knockout
2. Set up a loop through the array
3. Try to play the videos

### Expected
The video to work.
### Actual
Video is stick and not able to be interacted with -- black screen with the play button.
### Error output
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. Object { code: 4, message: "No compatible source was found for …" }

#### videojs
5.8.8
#### browsers
Firefox & Chrome
#### OSes
Windows
### plugins
No

**Comment by BrandonOCasey** [comment]
Hi @SteveV0189! Is there any way that you can provide a [reduced test case](https://css-tricks.com/reduced-test-cases/) showing the issue in isolation? We have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin for these kinds of things. It is hard to find out what is going on by just looking at the page.

**Comment by SteveV0189** [comment]
@BrandonOCasey 
http://jsbin.com/jeboxadano/1/edit?html,console,output

That's about as reduced as I can get it while still showing the functionality I'm missing that this library should theoretically provide.

Knockout doesn't render the <video> tags on load, rather it does when it iterates over the clips array in the viewmodel. It seems that this library doesn't agree with that idea -- it needs to the <video> tags to exist on the page when the page is loaded.

I've demonstrated that there are two separate errors when trying to use Knockout -- as you can see, one video errors out, saying "No compatible source was found for this media", and the other one (the second video) _appears_ to load correctly, but the controls will not work, and manually calling .play() will not play the video.

The three buttons up top attempt to set the source to a .webm url. It works with the last video, which is loaded without Knockout.

**Comment by gkatsev** [comment]
It looks like you need to move away from using data-setup and instead initialize the player manually. See https://github.com/videojs/video.js/blob/master/docs/guides/setup.md#manual-setup for more info.

**Comment by SteveV0189** [comment]
http://jsbin.com/lerajugobi/edit?html,console,output

Is there something in there that you see is incorrect? I still get a generic "Error: Videojs" console. This does look like the solution I need though, thank you!

**Comment by SteveV0189** [comment]
Fix was to initialize the video at the end of the script, after applying knockout's viewModel to the page. Thanks for the help guys! 

http://jsbin.com/yogubaxatu/edit?html,console,output
