### ISSUE TITLE
Shouldn't be necessary to check attribute for autoplay, playsinline, muted, etc.

### ISSUE THREAD

**Issue by incompl** [videojs/video.js#3970]
## Description
We have code that does this:

```
(player.autoplay() || player.el_.hasAttribute('autoplay'))
```

It would be ideal if autoplay() returned the right value instead.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
This has been fixed as part of the autoplay work done in september 2017.

**Comment by incompl** [comment]
🎉
