### ISSUE TITLE
video.js breaks HTML5 Video in MS Edge

### ISSUE THREAD

**Issue by simonhermann** [videojs/video.js#3992]
video.js does not work __at all__ in MS Edge (38.14393.0.0) on Windows 10 (1607).

There's always the same error: _'No compatible source was found for this media.'_

Examples: http://videojs.com, https://www.theguardian.com/video

If video.js is not used, Edge plays the HTML5 Videos – so the source format can not really be a problem. Interestingly IE11 works like a charm with video.js...

**Comment by mister-ben** [comment]
I checked a few machines with this version of Edge. None has a problem, and I've heard of no other reports of issues, so this may be something specific to your configuration. Have you tried with browser extensions disabled and default settings?

**Comment by simonhermann** [comment]
Thanks for your reply, after some testing I found the reason: I had flash player disabled in settings. If enabled, everything is okay. 
Sorry for bothering, I was totally not aware that flash is needed here!

**Comment by mister-ben** [comment]
You should not need Flash on Edge

**Comment by simonhermann** [comment]
Does videojs work for you if you disable Flash in Edge settings?

**Comment by paulomedia** [comment]
we just have to use flash on EDGE windows 10, if we have need for a special reason to reproduce rtmp/rtmpe or flv formats, if not we don't need flash with videojs
EDGE for window 10, works fine with ( mp4, mp3, hls live/vod ) using native video tag or videojs.

but in IE11 for windows 10, videojs don't detect that the browser can't support hls in video tag HTML5, so don't change the tech for flash to reproduce, we have to forze to change of tech.

tested in videojs v5.12.6 videojs-contrib-hls v3.6.12

**Comment by gkatsev** [comment]
This sounds like videojs/videojs-flash#39, which is merged and released in videojs-flash (for Video.js 6, we haven't merged it into Video.js 5 yet).
