### ISSUE TITLE
On the www.videojs.com advanced examples page, Video.js doesn't properly clean up Audio Descriptions button/menu in the control bar when no descriptions are present

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#3994]
## Description
Video.js doesn't properly clean up Audio Descriptions (Text Track) button/menu in the control bar, leaving a menu with only a single option when no descriptions are present after a video with description track(s) is played.

The Descriptions text track support seems to have fallen behind captions & subtitles in its implementation, and doesn't handle this switch correctly.

## Steps to reproduce
1. Go to http://videojs.com/advanced/
2. Select the "Elephant's Dream" video
3. Press the "big play button"
4. Observe that the "AD" menu is present in the control bar, with two options (_English_, and _Descriptions Off_)
5. Select any other video (e.g. Disney's Oceans)
6. Press the "big play button"

### Expected
Since there is no Descriptions Text Track associated with the second video, the "AD" menu button should not be present in the control bar

### Actual
The AD menu button is present, but the only menu option is _Descriptions Off_

### Error output
Console reports:
````
VIDEOJS: WARN: Calling addRemoteTextTrack without explicitly setting the "manualCleanup" parameter to `true` is deprecated and default to `false` in future version of video.js
logByType @ video.js:22914
log.warn @ video.js:22964
addRemoteTextTrack @ video.js:17499
addRemoteTextTrack @ video.js:15649
addRemoteTextTrack @ video.js:12058
playItem @ advanced.js:51077
currentItem @ advanced.js:51255
switchPlaylistItem_ @ advanced.js:50692
bound @ video.js:22702
data.dispatcher @ video.js:22493"
````
when Elephants Dream video is selected. No error report when switching to the second video.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.15.1
#### browsers
Firefox 50.1
#### OSes
Windows 7
### plugins
videojs-contrib-hls, videojs-playlist, videojs-playlist-ui (there may be others - it's the current version of http://videojs.com/advanced/, so it ought to be easy to check!

**Comment by gkatsev** [comment]
Seems to have been fixed.
