### ISSUE TITLE
Fix typo or obsolete option

### ISSUE THREAD

**Issue by sideris** [videojs/video.js#3995]
In here 

https://github.com/videojs/video.js/blob/05b39fe281c4b299207334dd1da3cdbcbbc36c78/docs/guides/react.md

`autoPlay` should be `autoplay`

**Comment by gkatsev** [comment]
Want to submit a PR? Would be greatly appreciated!

**Comment by Epipong** [comment]
I submit a PR https://github.com/videojs/video.js/pull/4080.

**Comment by gkatsev** [comment]
Thank @Epipong!
