### ISSUE TITLE
White space in fullscreen for Android and Firefox

### ISSUE THREAD

**Issue by AndriyOleksyuk** [videojs/video.js#3997]
## Description
On Android device in firefox after open fullscreen displayed white line on the bottom.
After device rotation it disappeared

## Steps to reproduce
1. Open http://videojs.com in firefox on android device
2. Launch fullscreen.

## Results
Check white line on the bottom

You can check image:
![screenshot_2017-01-31-12-16-07 1](https://cloud.githubusercontent.com/assets/2687326/22461667/d805061c-e7b2-11e6-8da5-cee2780408c0.png)

**Comment by gkatsev** [comment]
Can you elaborate on which Android device and version as well as which version of Firefox? On my Google Pixel with Firefox 50.1.0, I do not see such a white bar.

**Comment by mister-ben** [comment]
Hmm, I get this on Firefox 50.1.0 / Android 6.0.1 with _anything_ using the fullscreen API, not just Video.js

**Comment by gkatsev** [comment]
Weird. Sounds like it's a browser bug then.

**Comment by mister-ben** [comment]
The gap is exactly the same size as Android's status bar, so my guess is Firefox calculates the fullscreen area as the screen space minus the status bar, but then they go and remove the status bar and shift up. There a few issues on Mozilla's tracker for behaviour that is similar but not exactly the same (for some the empty space is at the top), so it probably varies by Android version and / or device. I don't think this is anything that can be addressed within Video.js.

**Comment by Firedingo** [comment]
I'm not a video.js user but I see this issue also. I have a Samsung Galaxy tab s running Android 6.0.1 and Firefox 53.0.2.
Just wanted to say thanks @AndriyOleksyuk for mentioning that screen rotation got rid of it for you. Worked for me too and it was driving me nuts till now.

**Comment by gkatsev** [comment]
Yeah, this sounds like a browser bug and not something we can work around, unfortunately.
