### ISSUE TITLE
No icons in IE11, document mode = IE8

### ISSUE THREAD

**Issue by ownmaster** [videojs/video.js#3999]
Hi,

I have similar problem to the one described in #2982. I can even play the video, but during playback I can't see control icons (play/pause, sound), though I can see the popup labels above them when hovering ('Pause', 'Mute').

I check it in IE11, Windows 10 64-bit, in IE8 mode: `<meta http-equiv="X-UA-Compatible" content="IE=8"/>`. Video.js version: 5.15.1.

This has to do something with fonts because, for example, if in video-js.css I change
```
.vjs-icon-play:before, .video-js .vjs-big-play-button:before, .video-js .vjs-play-control:before {
    content: "\f101"; }
```
to
```
.vjs-icon-play:before, .video-js .vjs-big-play-button:before, .video-js .vjs-play-control:before {
    content: "XXX"; }
```
I can see `XXX` on a big play button.

I tried solution above about adding font mime types to IIS web.config but that didn't change anything, actually this should not be server problem, since player renders correctly if I switch to IE9, IE10 or IE11 mode in the same browser. It also renders correctly in Opera and Firefox.

The problem is that I have to use IE8 mode, otherwise other page functionality fails, so there is no option.

Can this be 'fixed'?
If not, can you give suggestions how can I rework default CSS file to show the buttons (using images, for example)?
Or maybe I should downgrade video.js to some old version?

Here is how it looks (preview and playback):
![ie8mode-preview](https://cloud.githubusercontent.com/assets/10141077/22475815/df315248-e7e8-11e6-93b1-443ef50ad6d3.png)
![ie8mode-playback](https://cloud.githubusercontent.com/assets/10141077/22475855/09eebcf0-e7e9-11e6-93b4-df80dfd7bc30.png)

**Comment by mister-ben** [comment]
Works [here](http://output.jsbin.com/duwakeb). Do you have a reduced test case?

**Comment by ownmaster** [comment]
Provided example doesn't load player at all, it crashes with the following info in console:
```
HTML1201: jsbin.com is a website you've added to Compatibility View.
duwakeb
SCRIPT438: Object doesn't support property or method 'isArray'
video.js (22676,3)
SCRIPT5007: The value of the property 'videojs' is null or undefined, not a Function object
duwakeb (31,5)
```
Tested in MS IE11-Win7 virtual machine under VMplayer, added jsbin.com to compatibility list. I get same errors in my IE11 on Windows 10.

I will try to prepare an example that reproduces the problem.

**Comment by mister-ben** [comment]
Sorry, that example was missing the IE8 compat script, try again. On a clean install of IE11 on Win10, that's triggering IE8 mode and the icon fonts are displaying.

I don't recall whether adding `<meta http-equiv="X-UA-Compatible" content="IE=8"/>` as I've done there and you mentioned initially, and adding a site to the compatibility list have exactly the same effect - the browser may be even more crippled in the latter case.

**Comment by ownmaster** [comment]
Now page receives 403 Forbidden when it is trying to load http://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js.

**Comment by ownmaster** [comment]
I prepared a [sample](https://output.jsbin.com/xanenekofu) (it is actually almost exact copy of sample from [here](http://videojs.com/getting-started/)).

**Comment by ownmaster** [comment]
This is how example looks in native IE8 (IE-Win7 MS VM):
![ie8-preview](https://cloud.githubusercontent.com/assets/10141077/22514573/70a47254-e8a8-11e6-9fcd-14feac88e9f1.png)
![ie8-playback](https://cloud.githubusercontent.com/assets/10141077/22514575/74680fe0-e8a8-11e6-84ae-aece21d67798.png)

**Comment by singhalsurbhi07** [comment]
Facing the same issue. @ownmaster were you able to resolve it??

**Comment by ownmaster** [comment]
No, because I managed to use IE10 mode.
But if that wouldn't happen I had the following plan:
a) dig into fonts loading - this is the core reason behind this problem, the icons are created using font which is (for unknown reason) not loaded correctly in IE8
b) extract all necessary font icons as images (.png) and modify video.js CSS to use these images instead.

**Comment by vagari** [comment]
I noticed this issue using IE 8 in the Microsoft VirtualBox image. I have things self hosted and in my CSS file on line 11 I saw the following. 

`@font-face {
  font-family: VideoJS;
  src: url("font/VideoJS.eot?#iefix") format("eot"); }`

Once I tweaked that declaration to point to where the VideoJS.eot file actually exists everything started working again. Hope that helps everyone else.

**Comment by ownmaster** [comment]
@vagari, this is not the issue in this case.

The solution is described [here](https://github.com/videojs/video.js/issues/3238#issuecomment-276782474): #3238.
