### ISSUE TITLE
Audio amplification on VideoJS

### ISSUE THREAD

**Issue by massoudAfrashteh** [videojs/video.js#4000]
## Description
Hi is there any package to amplification the audio? (e.g to reach it to 200%) I cound not find any thing about.

**Comment by gkatsev** [comment]
There's nothing built-in. It might be possible to do so with the web audio API but I'm not sure.

Unfortunately, this would be a bit out of the foray of the github issues. We could discuss it on [slack](http://slack.videojs.com) but other than trying the web audio API I'm not sure there's anything that can be done. If that is possible, making a videojs plugin would be pretty great, though.
