### ISSUE TITLE
[RFC] Drop Bower Support

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#4012]
Hey All,

We're thinking of dropping support for Bower in the 6.0 release of Video.js. Video.js is very invested in the npm ecosystem and none of the core contributors to video.js use bower on a regular basis. We also believe that checking in build files to the main repo is not a good thing. Currently our bower support is a hacked together script that creates a branch that we create the version tag against. The branch is then deleted and the tag pushed up to github. While this works, it's not very maintainable and kind of hacky.
Also, there's a resolver plugin for bower that allows you to install modules from npm and we'd make sure to document that if there are users that use bower if we drop support.

Please let us know if you're using bower and whether the bower npm resolver would be an acceptable solution.

**Comment by BrandonOCasey** [comment]
https://github.com/mjeanroy/bower-npm-resolver

**Comment by ljharb** [comment]
The more people get encouraged to move off bower, the better.

**Comment by gkatsev** [comment]
We are removing bower support in 6.x.
