### ISSUE TITLE
Progress bar text for screen reader should include the duration, if available

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#4024]
## Description
The progress bar uses `aria-valuetext` to convey the current time to screen reader users. Visually, the current time is displayed as a point on the progress bar line where the _length of the bar_ represents the duration of the video. Screen reader users should also be presented with this information from the progress bar, for example as "01:23 of 12:34", rather than just "01:23" (and then needing to navigate through the control bar for the duration separately).

**Comment by gkatsev** [comment]
Would that mean we would need to localize `of`?

**Comment by OwenEdwards** [comment]
I guess so! Probably more localize the "%1 of %2", in case some languages reverse the order ("%2 de %1")??

**Comment by gkatsev** [comment]
Interesting. I guess we'd want some kind of tokenization system for the localizations.

**Comment by OwenEdwards** [comment]
Yeah, that's how more advanced i18n systems work. Might be a little too advanced to do at this point, so just being able to localize the "of" would be enough, I guess. It'd be nice to get this into v6, though - _some_ other video players have it ;-)
