### ISSUE TITLE
$ and $$ inside components can't get `:focus` and `*`

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#4032]
When inside a component and using the `$` and `$$` helpers to get all elements or the focused element, it ends up returning null.
```js
this.$$('*');
```
should return similar output as
```js
this.el_.querySelectorAll('*')
```

**Comment by gkatsev** [comment]
Found as part of implementation of https://github.com/videojs/video.js/pull/4025

**Comment by misteroneill** [comment]
@gkatsev I believe you said yesterday that this was because of a misunderstanding about how the `ModalDialog` component worked? If I'm imagining things again, please re-open.

**Comment by gkatsev** [comment]
Yeah, I think it might be because elements I'm looking for aren't available yet or something.
