### ISSUE TITLE
reseting a plugin back to its initial state

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#4033]
Hi All, 

I really need to reset a plugin back to its initial state, I am building a playlist switcher and I need to add/update plugins on list click to load the new video with plugins from their initial state instead of loading them twice. 

For instance, I have this code. 
~~~
var videoPlayer = videojs("video", {
    autoplay: true,
    nativeControlsForTouch: false
}, function() {

});

// Load the thumbnail plugin
videoPlayer.thumbnails("<!-- thumbs array -->");


// now when i click on my list element.
$(".playlist-click").on("click", function(event) {

    event.preventDefault();
    var pIndex = parseInt($(this).data('id'));
    // gets the new media data from the api
    getData(pIndex, function(_response) {

        if (_response.error) {

            console.log(_response.message);

        } else {


            // setup the sources which sets fine
            videoPlayer.src(_response.sources);

            // set the poster image which sets fine
            videoPlayer.posterImage.setSrc(_response.poster);


            // Load the thumbnail plugin
            videoPlayer.thumbnails("_response.thumbs"); // ISSUE the thumbnails load again twice over the current thumbs i need them to run as if from scratch.

        }

    });

});
~~~
I am looking to reinitialize the plugin thumbnails again but it loads twice.

#### videojs 5.15.1

Any suggestions? Thanks ;)

**Comment by misteroneill** [comment]
Are you using a custom thumbnails plugin or an open source one?

This illustrates one of the problems with Video.js plugins as they stand today: they have no lifecycle. They're a "run once and done" experience out of the box. If the plugin you're using now doesn't offer anything like a "dispose" or "teardown" process, you're basically left with two options:

1. Dispose the _player_ entirely and re-create it.
2. Manually tear down the thumbnails plugin, so it can be re-initialized.

I wish I had a better answer, but that's the state of the world in Video.js 5-land.

_However_, the good news is that Video.js 6 is coming _very_ soon and includes a whole [new plugin architecture/concept](http://blog.videojs.com/Feature-Spotlight-Advanced-Plugins/) that allows plugins to have a "dispose" step the same way components do.

**Comment by samueleastdev** [comment]
Hi @misteroneill,

Thanks for the info yes I looked into disposing the player but this doesn't work for me.

Currently, I am removing all the added divs from the dom so they can be recreated on the click function.

~~~
$(".vjs-thumbnail-holder").empty(); // obviously a bad soltuion
~~~

Been looking into building some custom plugins i used the https://github.com/videojs/generator-videojs-plugin which doesn't seem to support the new setup yet.

Just building a simple title and description overlay plugin as a test that updates on click.

Thanks for the link i will look into this http://blog.videojs.com/Feature-Spotlight-Advanced-Plugins/ 

Do you know if there is a skeleton plugin already created with the new setup that i can use as a example running and compiling with npm etc,

Cheers

**Comment by gkatsev** [comment]
Advanced plugins have already shipped and we use them already for some things (outside of Video.js). The generator should make a stubbed out advanced plugin for you, I believe.
Feel free to ping us on [slack](http://slack.videojs.com) if you need more help.
