### ISSUE TITLE
Make `Player#src` work more like the video element

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/video.js#4036]
## Description
* Investigate how the video element handles the following arguments, and mimic the behavior:
  * `[]`
  * `{}`
  * `''`
  * `{src: ''}`
* Write unit tests to verify that these functions return the correct value:
  * `Player#src`
  * `Player#currentSrc`
  * `Player#currentSource`
  * `Player#currentSources`
  * `Player#currentType`
* Better internal names (suggestions):
  * `source` -> `initialSource`
  * `sources` -> `initialSources`
  * `src` -> `elSrc`

**Comment by gkatsev** [comment]
Don't forget `currentType` test.
Maybe we should also use a convention where `src` means just a string, and `source` means an object? It would be consistent with the function naming right now.

**Comment by gkatsev** [comment]
Also, we potentially don't have to mimic behavior. Since in the html5 tech, we just pass set the `src` attribute, we could potentially lean on that some more.

**Comment by gkatsev** [comment]
I think we are doing this already with the new middleware work or am I missing something?
