### ISSUE TITLE
videoJs Component Options not work!

### ISSUE THREAD

**Issue by weituotian** [videojs/video.js#4038]
## Description
![image](https://cloud.githubusercontent.com/assets/7270968/22675745/78fad2a8-ed22-11e6-823a-4baaa3e1a127.png)

i want to disable the muteToggle but the option not work!
not work!
not work!
not work!

## Steps to reproduce
` data-setup='{ "controlBar": { "muteToggle": false } }'`

### Expected
to disable the muteToggle, RemainingTimeDisplay
![u 2780806826 1521009098 fm 73](https://cloud.githubusercontent.com/assets/7270968/22675873/14b181a6-ed23-11e6-8114-1b6c62d16894.jpg)

**Comment by mister-ben** [comment]
That control is a `volumeMenuButton`, so `data-setup='{ "controlBar": { "volumeMenuButton": false } }'`

**Comment by weituotian** [comment]
and i want to replace the RemainingTimeDisplay to CurrentTimeDisplay
it is not work too!not work!not work!not work!not work!

`        var player = videojs("myvideo", option, function () {
            console.log("ready");
        });
        player.controlBar.removeChild("RemainingTimeDisplay")//it work!;
        player.controlBar.addChild('CurrentTimeDisplay');//not work!`

So how to deal with this problem?i need help?

And how to find the correct way to configure it, 
i try to read document many times but it does not helpful to me. 
What the document describe is not correct, having no effect?

![default](https://cloud.githubusercontent.com/assets/7270968/22718411/3df247fe-eddb-11e6-87de-456a595e6b30.jpg)

**Comment by mister-ben** [comment]
The current time display is present in the control bar by default - but it's also hidden by the default style. Try this:

```css
.video-js .vjs-current-time,
.vjs-no-flex .vjs-current-time {
  display: block;
}
``` 

Does this diagram help understand the component used?
https://github.com/videojs/video.js/blob/master/docs/guides/components.md#default-component-tree

**Comment by weituotian** [comment]
ehhhh,
when i trying to practice the new [document](https://github.com/videojs/video.js/blob/master/docs/guides/components.md#default-component-tree)
the new problem is:

>         var option3 = {
>             children: [
>                 'BigPlayButton',
>                 'controlBar'
>             ]
>         };
>         var player = videojs("myvideo", option3, function () {
>             console.log("ready");
>         });

when i click the bigPlayButton
![image](https://cloud.githubusercontent.com/assets/7270968/22766762/5c1e85ee-eeb2-11e6-9a4f-6b40d689926b.png)
it not work! because
![image](https://cloud.githubusercontent.com/assets/7270968/22766782/78891762-eeb2-11e6-835b-41671d1a2b45.png)

![image](https://cloud.githubusercontent.com/assets/7270968/22766987/802f6056-eeb3-11e6-9e13-9d72bb2b7c9d.png)

**Comment by weituotian** [comment]
@mister-ben 
Is the problem to hard to solve?

**Comment by weituotian** [comment]
@mister-ben 
Is the problem to hard to solve?

**Comment by mister-ben** [comment]
Setting an array elements for children will overwrite the default children. In this case you now have no MediaLoader component. Without that there's no playback, so you don't want to do that.

You can remove the volume control and remaining time with setup options:

    "controlBar": {
      "volumeMenuButton": false,
      "remainingTimeDisplay": false
    }

You can show the current time with CSS:

    .video-js .vjs-current-time,
    .vjs-no-flex .vjs-current-time {
      display: block;
    }

**Comment by NabiKAZ** [comment]
@mister-ben 
Can use `remainingTimeDisplay` and `fullscreenToggle`,... Why can not use another option in [[here](https://github.com/videojs/video.js/blob/master/src/js/control-bar/control-bar.js#L56)] be like `currentTimeDisplay`, `durationDisplay`,... ? and why must use css and theme for show some options?

**Comment by ArgHakobyan** [comment]
### ###
