### ISSUE TITLE
"Hotkeys" plugin should be native in 6.0

### ISSUE THREAD

**Issue by AdielMtz** [videojs/video.js#4039]
Also the plugin "replay" should be native.
I think it would be better if they were integrated automatically when you initialize the player (or disable with the options).

**Comment by kavin-90** [comment]
Yeah, hotkeys are part of jwplayer core so it did be great if videojs support it 

Also resolution plugin.

**Comment by OwenEdwards** [comment]
Adding "Hotkeys" while maintaining keyboard operation of each of the individual controls to make the player accessible for people with disabilities (aka 'a11y') would require the change in #4048.

Note that hotkeys, aka keyboard shortcuts, are a _usability_ feature, not an _accessibility_ feature; the accessibility requirement would be to provide a way for users with disabilities to find out what the available shortcuts are, and to ensure that all controls and features are accessible with normal keyboard-only operation (Tab, Enter, Space, Arrow keys), **not just** by shortcuts.

**Comment by kavin-90** [comment]
@OwenEdwards SPACE key should be added for Play/Pause if not any other keys.

**Comment by OwenEdwards** [comment]
@kavin-90 if you click on the Big Play button with the mouse, then keyboard focus moves to the Play/Pause toggle button once playback starts, and Space **does** Play/Pause the video, without you having to do anything else. Is that not what you see?

**Comment by richardbushell** [comment]
@OwenEdwards 
Nope! Here's a previous test case:
https://living.video/vjsreduced.html
But it's the same in 5.16 that we are currently using.
Big Play click doesn't transfer focus to Play/Pause for us, so SPACE doesn't work, unless we click on the Play/Pause button manually.

**Comment by OwenEdwards** [comment]
@richardbushell my mistake - this is fixed in #4018, which will be part of the v6 release. I guess you might ask @gkatsev if that could be back-ported into v5.x.

**Comment by AdielMtz** [comment]
I think probably the most used are the arrow keys, to forward or rewind the video 'X' seconds.

**Comment by OwenEdwards** [comment]
@AdielMtz arrow keys work when keyboard focus is on the progress bar. They also work for the volume when keyboard focus is on the volume slider.

If you want to implement the feature in #4048, then arrow keys could be supported on other controls which don't use them (such as the play/pause toggle button).

**Comment by kavin-90** [comment]
I tested videojs click on big play button then press space key it does not pause/play video but it scroll page that is must needed feature i needed.

SPACE key should be added for Play/Pause if not any other keys.
