### ISSUE TITLE
The problem exists in Webstorm

### ISSUE THREAD

**Issue by huanghe2015** [videojs/video.js#4042]
##Description##
When I'm trying to download JavaScript file "video.js" in example on offical website(on "Use Now→CDN") and copy it to Webstorm,the CPU usage of Webstorm suddenly up to about 100%(My laptop's CPU is "Core i7-4710MQ").That is incredible!

**Comment by gkatsev** [comment]
That seems like a problem with webstorm and not videojs. Not sure how we can help.
