### ISSUE TITLE
How to reload or replay the video.(In case of Error)

### ISSUE THREAD

**Issue by arishvarunmishra** [videojs/video.js#4044]
Video is playing fine when we disconnect the internet and reconnect it. The player is not able to resume or replay video.

**Comment by sylvio-ruiz** [comment]
You must to listen the error events and try to reset the player if it is not able to resume by itself like a disconnection (network error).

This is an example that I got from my code, where el is the video tag, trying to reset the player each 5 second until no other network error is fired, and player_api is my videojs global variable. There are many others checks, I just resumed it for you understand, but my code has variable to handle a limit for trying, check for others error types, etc.

```
    var resetPlayer = function doResetPlayer(){
        reloading = true;
        try {
            console.info('[info] > Reseting media ...');
            player_api.reset().src({type: 'application/x-mpegURL', src: String(play_path), withCredentials: false});
        } catch(err) { console.error(err); } finally { reloading = false; }
    };
    
    function doRecoverOnError(ms){
        if (!reloading) { reloading = true; player_api.setTimeout(resetPlayer,ms); }
    }

    el.addEventListener('error', function(e) {
        var mediaError=e.currentTarget.error;
        switch(mediaError.code) {
            case mediaError.MEDIA_ERR_NETWORK:
            doRecoverOnError(5000);
            break;
        }
     });
```
I hope it help you to write your own error handles.

**Comment by gkatsev** [comment]
You don't have to listen to the error event on the video element itself, you can do it on the Video.js player but the idea still works.
Thanks @sylvio-ruiz.
