### ISSUE TITLE
Pulling Up Controls Timeline

### ISSUE THREAD

**Issue by ricking06** [videojs/video.js#4045]
It would be great if the pulling of timeline control is possible.

On long videos the timeline is very small to seek . 
Like in youtube  if we pull up the timeline control it increases and we can seek more accurately.

Similiar feature is required by videojs 
Thanks

**Comment by gkatsev** [comment]
That's an interesting enhancement. I'm not sure that we have the resources to implement it ourselves and I'm not sure we want that in core (yet?). It should definitely be doable as a plugin, I would think (hope). If you are interesting in tackling that and need help making the plugin, feel free to ping us on [slack](http://slack.videojs.com).
