### ISSUE TITLE
Add support for "bubbling" unused keypresses up through control bar components to the player

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#4048]
We've been working hard on keyboard accessibility for the video.js control bar, using Tab/Shift-Tab, Enter, Space, and the arrow keys. Each component knows what key presses it supports, and which ones it ignores. There's a basic structure in place to pass keypresses up through the component hierarchy to the base `Component`, but it would make sense to then pass them to the `parent` Component, and onwards up to the player itself.

That way, we could either implement hotkeys ourselves later on, or provide a single point to attach a plug-in to handle keypresses which aren't used by the controls themselves.

Thoughts?

**Comment by petercunha** [comment]
Has anyone followed up on this issue? I think hotkey support would be a very valuable feature.

I might try to work on this myself and make a pull request if nothing is in the works yet.

**Comment by OwenEdwards** [comment]
@petercunha I've got a project on the back burner to implement this; I'll do a little more work on it and create a PR, so you can at least take a look at it. Give me a day or two.
