### ISSUE TITLE
Stream stops playing on Android when screen turned off

### ISSUE THREAD

**Issue by grantfeldman** [videojs/video.js#4051]
Hi, i am finding that when playing an audio stream on an android device, when turning the screen off the stream stops playing. Is this a known issue and something that can be changed?

I know that playback is possible as the BBC radio 1 stream continues to play whether the screen is off or on.

**Comment by mister-ben** [comment]
I'm not sure that it's possible. The BBC site launches the BBC Media Player app to play the audio, and opens the Play Store if it's not installed.

**Comment by gkatsev** [comment]
This is up to the browser implementation. Trying it out locally in Chrome for Android, chrome auto-pause the video/audio when the browser is put into the background or when the screen turns off. I haven't been able to programmatically play the video again. However, if the user clicks play on the persistent notification that chrome provides, it'll continue playing in the background.

Unless things change, I'm not sure there's anything we can do.

**Comment by kontrollanten** [comment]
@gkatsev Do you know if anything has changed since this was closed? iOS Safari behaves in a similar way, but there I solved it by calling play upon visibilityState change. In Android Chrome I only get that solution working  in ~40% of the time.

**Comment by gkatsev** [comment]
I don't know. Haven't explored this area at all since.
