### ISSUE TITLE
Unable to resolve this error MEDIA_ERR_SRC_NOT_SUPPORTED

### ISSUE THREAD

**Issue by manishchauhanquovantis** [videojs/video.js#4052]
I am just trying to play a sample code it showed me this error.

```
Not allowed to load local resource: blob:null/044b9ca6-928d-4cd2-a555-81c7f06f7f48
video.js:22933 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}
logByType @ video.js:22933
log.error @ video.js:22969
error @ video.js:11664
handleTechError_ @ video.js:10434
bound @ video.js:22721
bound @ video.js:22721
data.dispatcher @ video.js:22512
main.html:45 error: Object {type: "error", target: div#myVideo.myVideo-dimensions.vjs-workinghover.vjs-user-active.vjs-playing.vjs-waiting.vjs-error.vj…, relatedTarget: undefined, defaultPrevented: false, which: undefined}
main.html:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```

**Comment by gkatsev** [comment]
There's not a lot of information to go on from here. You need to make sure to [use a format videojs supports](https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#make-sure-you-are-using-formats-that-videojs-can-play) and make sure that your video is [hosted properly](https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#problems-when-hosting-media). If you add a reduced test case, and fill out the information in the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md), we can reopen this issue and continue the discission. Though, hopefully, the above links point you in the right direction.
