### ISSUE TITLE
Adding Slider Component to ControlBar gives error

### ISSUE THREAD

**Issue by hhentschel** [videojs/video.js#4053]
I want to add the Slider to the ControlBar,
for later making a Panning-Slider to control right and left volume.

My Code is:
```
var Slider = videojs.getComponent('Slider');

var panningSlider = videojs.extend(Slider, {
  constructor: function () {
    Slider.apply(this, arguments);
  },

  calculateDistance: function (event) {
  },

  handleClick: function (event) {
  },
});

//register Component
videojs.registerComponent('panningSlider', panningSlider);

//Videoslider
var video = videojs('videoPlayer', {
  controls: true,
  autoplay: false,
});

video.getChild('controlBar').addChild('panningSlider', {});
```

But i get following error:
`Uncaught TypeError: Cannot read property 'guid' of undefined`

I added other Buttons (e.g. for looping) the same way and had no problems.

vide. js Version: 5.16

Cannot find the problem, thanks for suggestions!

**Comment by gkatsev** [comment]
I'm not having any issues when running the above code locally. Would you be able to provide a reduced test case that showcases the issue? You can use the started template that's linked from the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by hhentschel** [comment]
I made a jsbin
http://jsbin.com/covunok/edit?html,js,output

adding for now a button and extending it for a loop button.
(the slider button i will try later)
but it does not work in the fiddle, but works locally on my computer.
what do i do wrong?
thanks!

**Comment by gkatsev** [comment]
Ah. It works if you update to videojs 5.16 or 5.17. Older versions of video.js, require that the component be registered as TitleCase and then used as a camelCase.
If you see http://jsbin.com/covunok/1/edit?html,js,console,output, you can see it works.

Hope that helps.

**Comment by hhentschel** [comment]
thanks for your help, that cleared a bit.

now the loop button works, but only for version between 5.14-5.16,
from version 5.17 on, only a download button is visible with this code.
so the latest stable version is 5.16? or which one should i use?

i also added a button for loading another slow version of a video (with stable sound),
same like the loop button.

then i also added the slider button, which was my initial question, which does not work.
can you have a look?
http://jsbin.com/covunok/edit?html,js,output

thx.

**Comment by gkatsev** [comment]
The download button sounds like it's using the native control bar. videojs's controls don' have a download button.

**Comment by hhentschel** [comment]
Then it must have been a version Number of video.js, which does not really exists.

But if i am using Version 5.14., everything works (Loop Button, Button to load other video),
but not the slider Button.

What do i do wrong here?
http://jsbin.com/covunok/edit?html,js,output

thx.

**Comment by gkatsev** [comment]
You have an error in the console if you look, you're trying to add the slider to `player` which doesn't exist, you use `video` in the code. Then if you debug further, you notice it failing because `playerEvent` isn't set up on the slider. You need to add something like
```js
panningSlider.prototype.playerEvent = '';
```

We potentially shouldn't fail if it doesn't exist, though.
