### ISSUE TITLE
Clicking the mute button also sets the volume slider to 0, but not the ARIA value of the slider

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#4064]
## Description
Clicking on the mute button changes its icon and also updates the volume slider to the 0 (leftmost) position. But using a screen reader, the volume level is still read out as its previous value.

Please include any additional information necessary here. Including the following:
#### videojs
v6.0.0-RC.2
#### browsers
IE11 & JAWS
#### OSes
Windows 7
### plugins
_(none)_

**Comment by OwenEdwards** [comment]
This is related to, but distinct from, #4056.

**Comment by gkatsev** [comment]
@kevinlitchfield can I ask you to take a look at this one as well?

**Comment by kevinlitchfield** [comment]
@gkatsev Sure thing!
