### ISSUE TITLE
Videojs as lot of bugs and issues after version 5.4.6

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#4065]
Video position with flash player.
flash loading is very slow. 
No more Loading image with flash video.
Time show -0 on flash video.
Some CSS are bad, video time on progress hover do not look good.
Do we should update the swf file?

**Comment by gkatsev** [comment]
Catch all issues likes these are not helpful and incredibly discouraging. For actual issues, please open an github issue per problem. It's possible that by this time, the latest versions of Video.js have already fixed some of these as well.

**Comment by onigetoc** [comment]
10 month latter i did find out :)
