### ISSUE TITLE
Chrome replaces videojs's control bar with it's own

### ISSUE THREAD

**Issue by apurvgandhwani** [videojs/video.js#4066]
Chrome is adding it's own control bar with videojs. I am not able to see the default videojs control bar. This is my code and js fiddle https://jsfiddle.net/t1gsrsu5/2/
``` 

<div class="main">
  <div class="video-container">
  <div class="video-wrapper">
<video controls>
  <source src="http://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
  <source src="http://www.w3schools.com/html/mov_bbb.ogg" type="video/ogg">
  Your browser does not support HTML5 video.
</video>
</div>
  </div>
  <div class="section">

  </div>

</div>
```
```

.main {
  height: 500px;
  width: 100%;
  display: flex;
}

.video-container{
  background: red;
  flex: 2;
  display: flex;
  align-items: center;
}

.section {
  background: blue;
  flex: 1;
}

.video-wrapper {
  position: relative;
  padding-bottom: 56.25%; /* 16:9 */
  padding-top: 25px;
  height: 0;
  flex: 1;
}

.video-wrapper > video {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

**Comment by gkatsev** [comment]
It looks like what you're seeing is the native control bar. The example that you've provided does not include videojs at all.

**Comment by apurvgandhwani** [comment]
But I have included videojs tag <video/> . Can you please explain it?

**Comment by gkatsev** [comment]
Your example only has a video element. You're not actually including videojs.
Here's an example with videojs included: https://jsfiddle.net/t1gsrsu5/4/

Also, the controls may look a tiny bit similar because we both use the material design icons.

**Comment by apurvgandhwani** [comment]
I did this. But it doesn't give me a responsive videojs player. The player in your fiddle is also not responsive. I am having troubles with making it responsive

**Comment by kavin-90** [comment]
videojs is responsive you need responsive parent div so videojs width change according to it.

My code
`<video id="my-video" width="800" height="450" class="video-js vjs-default-skin vjs-big-play-centered" controls fluid="true" data-setup='{}' >`
