### ISSUE TITLE
how to dynamically change src track on videojs

### ISSUE THREAD

**Issue by fchedro** [videojs/video.js#4068]
I'm looking for a solution to dynamically change src of track tag with videojs.
I try lots of things but nothing work.
It will be really cool if could help me.
```
$("#playlist li").on("click", function() {
   player.pause();
   player.src( $(this).attr("movie_url"));
   // set src track corresponding to new movie //
   player.load();  
   player.play();
}
```
thanks a lot for answer ;) !

**Comment by mister-ben** [comment]
You're on the right track as `src()` is for setting as new source. Can you put a minimal live example up on jsbin or similar?

**Comment by kavin-90** [comment]
example `<?php echo $sources; ?>` is array of files and type and quality(360px to 1080px) 

```
<script type="text/javascript">
videojs('video', {
    width: 'auto',
    height: 'auto',
    controls: true,
    plugins: {
      videoJsResolutionSwitcher: {
        default: 480,
        dynamicLabel: true
      }
    }
}, function(){
    var player = this;
    window.player = player
    player.updateSrc(<?php echo $sources; ?>)
    player.on('resolutionchange', function(){
      	console.info('Source changed to %s', player.src())
    })
});
</script>
```

**Comment by mister-ben** [comment]
If your issue is with that plugin, please open an issue on its tracker. `updateSrc()` isn't part of Video.js core.

**Comment by kavin-90** [comment]
Maybe that exists in older version of Videojs

**Comment by mkhazov** [comment]
@kavin-90 it is part of `videojs-resolution-switcher`: https://github.com/kmoskwiak/videojs-resolution-switcher#updatesrcsource

**Comment by kavin-90** [comment]
@mkhazov https://jsfiddle.net/Lkejx2yt/ working demo by using your code.

**Comment by mister-ben** [comment]
I hadn't noticed the first reply wasn't from the original poster. Can we please leave @fchedro to update with details of what he's actually doing. Introducing examples relying on plugins will just make this more complicated than it needs to be.

**Comment by kavin-90** [comment]
That Example is Only Videojs nothing else.

**Comment by ownmaster** [comment]
Did you check #339?

**Comment by fchedro** [comment]
Hello, 
thank you for your answers, but I think my question was not well understood or maybe it was not precise enough. That what I need is **to dynamically change the url of the subtitle file (vtt file) at the same time as the video file**. I have no problem to change video file with Videojs, but it is impossible to change subtitle simultaneously.

<Track kind = "subtitles" label = "english" src = "subtitle_file.vtt" srclang = "en">

Thank you to help me !

**Comment by sylvio-ruiz** [comment]
Your answer is here : http://docs.videojs.com/docs/guides/text-tracks.html

**Comment by gkatsev** [comment]
@sylvio-ruiz pointed in the right direction. When you change the source, you'll want to remove the previous text tracks and then add a new text track with the new url. The docs linked should help.
