### ISSUE TITLE
multiple player issue

### ISSUE THREAD

**Issue by shazvan275** [videojs/video.js#4071]
i am working on socialmedia website for that i need to make multiple videos and when i play something other video should stopped...

pls help me in this
 and sorry for my engish

**Comment by gkatsev** [comment]
Assuming you have a list of players that are playing, you'd want to listen to the `play` event on each player and then `pause()` the other players on the page.
Something like:
```js
var players = [player1, player2, player3];

players.forEach(function(player) {
  player.on('play', function() {
    players.forEach(function(pl) {
      if (pl !== player) {
        pl.pause();
      }
    }
  }
});
```

Hope that helps.
