### ISSUE TITLE
Length of playing/seek bar

### ISSUE THREAD

**Issue by apurvgandhwani** [videojs/video.js#4072]
Is it possible to get the width of seekbar in px of videojs. For example when player is full screen and when player is not full screen I want to get the length of seek bar. Is it possible?

**Comment by mister-ben** [comment]
`player.getChild('ControlBar').getChild('ProgressControl').currentWidth()`

**Comment by apurvgandhwani** [comment]
Okay it gives me an integer.I am getting 40. What does it mean?

**Comment by gkatsev** [comment]
The width in pixels of the component.

Can you elaborate on what exactly you're trying to do? We'd be able to give a better answer then.

**Comment by apurvgandhwani** [comment]
The width of progress bar is 775 px right now in my application. I measured  it using some tool. But this line of code gives me 40. So clearly 40 is not in pixels. I want the width of progress bar in pixels. How can I get it?

**Comment by thijstriemstra** [comment]
I'd also like to get the measurements of the player in fullscreen mode.

**Comment by gkatsev** [comment]
The `.currentWidth` method uses [`getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) to read back the value. 
You can also do a similar thing with the player by calling `player.currentWidth()`.

Also, the reason why I'm asking for your usecase is because a lot of times questions like these fall into under [the XY Problem](http://xyproblem.info), where someone asks for a specific thing to do something (get the width of the seek bar) because they think it's the best approach, where if we had more background we could direct you to a better solution altogether.

**Comment by thijstriemstra** [comment]
@gkatsev if you visit https://collab-project.github.io/videojs-wavesurfer/examples/ and open a web console, then press full screen, you'll see the height of the player is incorrect because I don't (or didn't) have a good way to measure the player.

**Comment by gkatsev** [comment]
`getComputedStyle` is always the recommended approach to seeing styles, the `current{Width,Height}` is just a convenience method.

Also, the XY Problem mention was directed at @apurvgandhwani.

**Comment by apurvgandhwani** [comment]
@gkatsev I don't know how to be more specific in my requirement. I want the progress bar width in pixels to place the markers of custom length on progress bar. The method suggested in previous comment is giving me an integer (40) which is not in pixel because I measured the progress bar width and it is around 775px currently. I just wanted to know how can I get the width in px.

**Comment by apurvgandhwani** [comment]
```
 var self = this;
              
                var player = videojs(this.refs.video, this.props.options).ready(function () {
                    self.player = this;
                    self.player.on('play', self.handlePlay);
                });
               
                if (this.props.onPlayerInit) this.props.onPlayerInit(player);


                
                this.setState({player: player});
                this.state.player.markers.getVideoDuration(this.props.video_file_selected_reducer.videoDuration);
```

**Comment by thijstriemstra** [comment]
sorry for intruding on the ticket and thanks for the feedback @gkatsev, I'll give it a try.

**Comment by gkatsev** [comment]
Ah, I think I figured out the problem. You're calling it too early. The default width of controls in the control bar is `4em` with a default font-size of `10px`, so, they are sized `40px`. However, if you run it when the player is initialized, the control bar hasn't resized itself properly using flexbox since it is hidden. If you hit play, and then read in the `currentWidth()`, it'll give you back a more accurate number.

@thijstriemstra that's ok. Glad you got an answer as well :)

**Comment by apurvgandhwani** [comment]
@gkatsev I am reading the currentWidth() after I hit the play now. It is giving me 597.203 but it should give me around 775. What do you think is causing this error?

**Comment by gkatsev** [comment]
I'm not sure. How was 775 measured?
Would you be able to provide a reduced test case?

**Comment by apurvgandhwani** [comment]
775 was measured using a chrome plugin which allows me to drag the rectangle and measure height and width. It's called page ruler.

**Comment by gkatsev** [comment]
The only thing I can think off currently without a specific example (or maybe a screenshot) is that what you're measuring and what you're getting the width off aren't the same element.

**Comment by tessact** [comment]
![size](https://cloud.githubusercontent.com/assets/18860378/22963009/7a6ca1ac-f376-11e6-8611-35c306ddbdd0.PNG)

@gkatsev have a look the screenshot.

**Comment by apurvgandhwani** [comment]
![size](https://cloud.githubusercontent.com/assets/7307993/22963157/53fc6060-f377-11e6-92e8-3b23840df918.PNG)

@gkatsev have a look at the screenshot

**Comment by apurvgandhwani** [comment]
@gkatsev update: For the very first time when I click play  buttom, the currentWidth() gives me 597, which is wrong. But after the after whenever I click play and pause, I get the correct width i.e. 777. This is a weird behavior I am seeing.

**Comment by gkatsev** [comment]
That's really weird. Only thing I can think off is that the 597 is somehow calculated when the volume is opened and squished the progress bar slightly.

**Comment by gkatsev** [comment]
Not sure we have anything else to add. Hopefully, this has been solved. It's possible that getting the bounding box might get a better answer than getComputedStyle but it shouldn't really be different in most cases.
