### ISSUE TITLE
Problem/Bug

### ISSUE THREAD

**Issue by mikhoul** [videojs/video.js#4092]
Hi'

First I'm new to "Video.js",

I've  read a lot the documentation and so far I've no problem playing MP4 movie but when I try to play m3u8 stream it did not work, it behave like if the player was "buggy" of have hard time trying to decode m3u8 stream.  :disappointed: 

I've setup a JsBin to test here: http://jsbin.com/hicijo/edit?html,output

And here'S a scrennshot where the player is frozen and the .TS file are "loaded" in the console.

From the console I the player "freeze"for ~15-30 seconds when loading HLS plugin, but the plug-in itself is loaded and after I can see the .ts files loading but nothing on the screen.

The player behaving is erratic... :bug: 

When I try the same stream in other players like "mediaelement" or even VLC I have no problem at all, so I know that the stream itself is not the problem.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Try to play the stream few times.
2.
3.

### Expected
Just play the stream fine at the best quality it can.

### Actual
 Erratic behavior of the player ending most of the time not playing the stream.

**N.B.:** Tried on Firefox and Chrome under Win7/64.

Let me know if you need more informations.

Best Regards :octocat:

**Comment by gkatsev** [comment]
Hi @mikhoul, seems like the issue is with contrib-hls. Would you be able to re-open the issue on that repo? (https://github.com/videojs/videojs-contrib-hls)

Thanks.

**Comment by mikhoul** [comment]
Yes !


Regards ! :octocat:
