### ISSUE TITLE
Adding `vtt.js`'s exports to `window` breaks `addCue` in Chrome

### ISSUE THREAD

**Issue by justinanastos** [videojs/video.js#4093]
## Description
In [`tech.js#addWebVttScript_`](https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js#L515-L521), all of the exports from `vtt.js` are blindly added to `window`. This will break the ability to call Chrome's native `TextTrack.prototype.addCue()` because Chrome expects an instance of it's native `VTTCue` and not the `vtt.js` version.

This will effect all use cases of calling `textTrack.addCue()`. I found the issue while trying to restore text track functionality to `videojs-contrib-dash` in https://github.com/videojs/videojs-contrib-dash/pull/135. The details of the error can be seen specifically in this comment https://github.com/videojs/videojs-contrib-dash/pull/135#issuecomment-278740001.

### Reduced Test Case

http://jsbin.com/tomegu/7/edit?html,js,output

The console will show the error thrown.

### Expected
I expect `TextTrack.addCue(new VTTCue( ... ))` to add cues.

### Actual
Chrome will throw an error, shown below.

### Error output
```
Uncaught TypeError: Failed to execute 'addCue' on 'TextTrack': parameter 1 is not of type 'TextTrackCue'.
```

#### videojs
I haven't checked any versions besides `v5.16`, but the same code exists in `master` so I assume all of the version.

#### browsers
Chrome

#### OSes
Only tested on MacOS 10.12.3 (latest as of this writing)

### plugins
None

## Resolution

I propose that only values that do not exist on `window` are defined when iterating through `vtt.js`'s exports.

This reduced test case shows a cue being added as expected when using the native `VTTCue` in Chrome.

http://jsbin.com/yelizon/5/edit?html,js,output

**Comment by gkatsev** [comment]
Yeah, that sounds like an issue. Historically, we haven't needed to handle this because either native tracks or emulated tracks would be used. The current proposed fix, unfortunately, will break emulated caption support, at least with the current version of vttjs that we're using. If it doesn't, let me know I'm wrong!
We already have an issue for updating vttjs (https://github.com/videojs/video.js/issues/3819) and we recently updated how vttjs is included. However, it seems like we need to spend some more time on this, potentially making vttjs be much more contained within tracks.

**Comment by justinanastos** [comment]
@gkatsev I'm minimally versed with emulated captions so please forgive the naive question: why would this break it? Is the shimmed `VTTCue` from `vtt.js` adding some functionality that doesn't exist natively?

**Comment by gkatsev** [comment]
I believe that there's some extra stuff that's currently happening in there that isn't available natively for the features we support with emulated tracks. I do remember that it wasn't sufficient to use native cues at the time I implemented it. It's possible things have changed and we probably should verify. Maybe we would only want to do this for older browsers or something. Though, I think making vttjs more contained with our emulated tracks functionality sounds like a good move regardless.

**Comment by justinanastos** [comment]
Thanks @gkatsev .

**Comment by gkatsev** [comment]
Thanks for looking into this @justinanastos.

**Comment by gkatsev** [comment]
I took a look today, I think the way everything is set up can be tweaked to fix the issue and also do it as a minor (so we can fix it in 5.x as well). I'll be working on this some more tomorrow.

**Comment by justinanastos** [comment]
Awesome, any way I can help @gkatsev ?

**Comment by gkatsev** [comment]
I'll ping you when I have something ready to test, thanks @justinanastos.

**Comment by gkatsev** [comment]
@justinanastos hey, I have a PR open against our vttjs fork with updates (https://github.com/gkatsev/vtt.js/pull/7), I also published it as a beta tag on npm `videojs-vtt.js@0.12.2-0`. If you can give it a shot, that would be awesome.

**Comment by gkatsev** [comment]
Just realized that we needed an extra piece here: https://github.com/videojs/video.js/pull/4115. Please try out that branch, it's currently including the pre-release of vttjs in the PR.
