### ISSUE TITLE
Video plays in Opera but the skin is not the one defined in options (and it doesn't play in Firefox)

### ISSUE THREAD

**Issue by ssaguiar** [videojs/video.js#4102]
I am developing a page with a popup to show the video selected. I use Bootstrap and the video is shown in a modal dialog.

The problem is that, even if I define the skin as vjs-tech (or the default - video-js vjs-default-skin), the one wich is shown is the white one. In Firefox, the skin is shown but the browser don't play the video.

The video is in h264 and the audio is in aac formats (it's a stream).

The web page code, for the modal popup is:

	<div class="modal fade" id="myModalAstraPlayer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog videocenter" id="videocontainer">
			<div class="modal-content">
				<div class="modal-body">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<div style="width:560px; height:340px;" id="videoplayer">

					</div>
				</div>
			</div>
		</div>
	</div>

and the javascript code (wich generates the modal contant for the video), is:

  var video;

    var videoaddress = document.getElementById("videoaddress").value;
    channelname = row.output;
    var n = channelname.lastIndexOf('/');
    var result = channelname.substring(n + 1);
    var videotoshow = videoaddress + "/" + result; // this is the video address...

    var mainDiv = document.getElementById('videoplayer');

    var divContainer = document.createElement('div');
    divContainer.class = 'example-video-container';
    divContainer.style.display = 'inline-block';
    divContainer.id = "videodiv";
    mainDiv.appendChild(divContainer);

    // Create Video Player
    video = document.createElement('video');
    video.id = 'vid2';
    video.width = 560;
    video.height = 315;
    video.autoplay = true;
    video.controls = true;
    video.muted = false;
    video.preload = 'auto';
    video.poster = "../images/loading.jpg";
    video.setAttribute("example_option", "true");
    video.setAttribute("playbackRates", "[1, 1.5, 2]");
    //video.setAttribute("controlspreload", "none");
    video.setAttribute("class", "vjs-tech"); //video-js vjs-tech video-js vjs-default-skin");

    function addSourceToVideo(element, src, type)
    {
        var source = document.createElement('source');
        source.src = src;
        source.type = type;
        element.appendChild(source);
    }

    addSourceToVideo(video, videotoshow, 'video/mp4');
    //addSourceToVideo(video, videotoshow, 'video/mp4; codecs="avc1.42E01E, mp4a.40.2"');
    //addSourceToVideo(video, videotoshow, 'video/mp4; codecs="avc1.58A01E, mp4a.40.2"');
    //addSourceToVideo(video, videotoshow, 'video/mp4; codecs="avc1.4D401E, mp4a.40.2"');
    //addSourceToVideo(video, videotoshow, 'video/mp4; codecs="avc1.64001E, mp4a.40.2"');
    //addSourceToVideo(video, videotoshow, 'video/mp4; codecs="mp4v.20.8, mp4a.40.2"');
    //addSourceToVideo(video, videotoshow, 'video/mp4; codecs="mp4v.20.240, mp4a.40.2"');
    //addSourceToVideo(video, videotoshow, 'video/mp2t');
    //addSourceToVideo(video, videotoshow, 'video/mpeg');
    //addSourceToVideo(video, videotoshow, 'video/msvideo');
    //addSourceToVideo(video, videotoshow, 'video/3gpp');
    //addSourceToVideo(video, videotoshow, 'video/3gpp2');
    //addSourceToVideo(video, videotoshow, 'video/avi');
    //addSourceToVideo(video, videotoshow, 'video/mpeg');
    //addSourceToVideo(video, videotoshow, 'video/msvideo');
    //addSourceToVideo(video, videotoshow, 'video/quicktime');
    //addSourceToVideo(video, videotoshow, 'application/octet-stream');

    console.log("Video Creation End");
    console.log("Paragraph Started");

    var paragraph = document.createElement('p');
    paragraph.innerHTML = "Video PlayBack Not Supported";
    video.appendChild(paragraph);
    divContainer.appendChild(video);

    $("#div_video_html5_api").show(); // Not necessary?

    video.load();
    video.play();

    $('#myModalAstraPlayer').modal('show');

    jQuery('#myModalAstraPlayer').on('shown.bs.modal', function (e)
    {

    });

    jQuery('#myModalAstraPlayer').on('hidden.bs.modal', function (e)
    {
        video.pause();
        videojs(video).dispose();

        try
        {
            document.getElementById("videodiv").remove();
        }
        catch(err)
        {
            console.log(err.message);
        }
    });

    var myVideo = document.getElementById("vid2");

    // disable right-click over video...
    if (myVideo.addEventListener)
    {
        myVideo.addEventListener('contextmenu', function(e)
        {
            e.preventDefault();
        }, false);
    }
    else
    {
        myVideo.attachEvent('oncontextmenu', function()
        {
            window.event.returnValue = false;
        });
    }

Anyone has any clue about this?
Thanks

The way it is now (in Opera, wich works and plays the generated videos streams):
![opera_videopopup](https://cloud.githubusercontent.com/assets/5515284/23094418/b4e8e8b6-f5df-11e6-93f4-d0006d9cd197.png)

The way it should be (this is the firefox one, wich doesn't play):
![firefox_videopopup](https://cloud.githubusercontent.com/assets/5515284/23094423/c11c3cdc-f5df-11e6-9336-ad5d1d9aa900.png)

**Comment by gkatsev** [comment]
Looking at the code, it doesn't seem like you're running videojs. You're just using the plain video element.
You want to actually include the videojs javascript and [initialize videojs](https://github.com/videojs/video.js#quick-start)

**Comment by ssaguiar** [comment]
Thanks for your answer, but it's VERY hard to find ANY complete example in javascript for the application of videojs.

**Comment by mister-ben** [comment]
SImple example putting the quickstart doc into practice http://jsbin.com/tixogohocu/edit?html,output.

As to why the video doesn't play in Firefox, have you checked the [troubleshooting guide](https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md)?

**Comment by ssaguiar** [comment]
Thanks, mister-ben.
I will look at this and try to implement.
The gratest problem I have is, as the stream address is not allways the same, I need to update the address dynamically.
Thanks again.
