### ISSUE TITLE
ReactJS integration example link broken. 

### ISSUE THREAD

**Issue by jasan-s** [videojs/video.js#4103]
[the link](https://github.com/videojs/video.js/blob/master/docs/guides/guides/react.md)

**Comment by mister-ben** [comment]
Where did you find this link so we can correct it?

**Comment by gkatsev** [comment]
I think this one is in the FAQ.

**Comment by four-eyes-04-04** [comment]
was this issue fixed? any updates about the link?

**Comment by mister-ben** [comment]
The React guide is where it has always been, at https://github.com/videojs/video.js/blob/master/docs/guides/react.md, and now also at http://docs.videojs.com/tutorial-react.html.

I'm still not sure where jasan-s found a link to https://github.com/videojs/video.js/blob/master/docs/guides/guides/react.md

**Comment by jasan-s** [comment]
That link was from the repo docs, Its fixed now. :)
