### ISSUE TITLE
Adaptive mp4?

### ISSUE THREAD

**Issue by genxstylez** [videojs/video.js#4107]
## Description
I know this question might be a lil noobish, but do I have to use HLS/DASH to do adaptive bitrate? (for VOD videos not LIVE).

I presumed I can use multiple mp4 files and with a .smil file? Does videojs supports it?

Thanks

**Comment by gkatsev** [comment]
I don't think you can really do adaptive mp4s in HTML5 without a format like HLS/DASH.

**Comment by genxstylez** [comment]
Thanks!
