### ISSUE TITLE
Why does VideoJS fail on all blogger sites ?

### ISSUE THREAD

**Issue by bilkorkmaz4486** [videojs/video.js#4108]
<a href="https://1.bp.blogspot.com/-ZGAXVVgrFhU/WKs1bBkVlaI/AAAAAAAAByk/7IwL4l4415QP0NT6aYz4b-lKf_BjUpSmwCLcB/s1600/tumblr_nu2x0g38Pa1rgsmwio1_500.gif" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="179" src="https://1.bp.blogspot.com/-ZGAXVVgrFhU/WKs1bBkVlaI/AAAAAAAAByk/7IwL4l4415QP0NT6aYz4b-lKf_BjUpSmwCLcB/s320/tumblr_nu2x0g38Pa1rgsmwio1_500.gif"></a>

**Comment by mister-ben** [comment]
Does "fail" just mean the tool tip formatting? That's because this page has `body {word-break: break-all;}`in it's stylesheet. Either remove it or override it with `.video-js {word-break: normal;}`,

**Comment by bilkorkmaz4486** [comment]
Very  thanks 😊
