### ISSUE TITLE
Videojs dynamic Poster

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#4109]
I'm surprised that videojs do not include a poster setting when we dynamically load a video.

I see a lot of video player who add it with a poster option.

```
myPlayer.src({
   "src":"http://mysite.com/video/video.mp4",
   "type":"video/mp4", 
   "poster":"http://mysite.com/img/poster.jpg"
});
```
OR
`myPlayer.poster("http://mysite.com/img/poster.jpg");`

I will create a plugin for poster and Youtube poster but i think poster setting should be part of videojs core.

**Comment by mister-ben** [comment]
`myPlayer.poster("http://mysite.com/img/poster.jpg")` will set the poster

**Comment by onigetoc** [comment]
i did the right suggestion but didn't try it :(
But we never find a example on any search on documentation or on Google, bizarre

**Comment by mister-ben** [comment]
Hopefully the new docs make it easier to find this info: http://docs.videojs.com/tutorial-player-workflows.html

**Comment by onigetoc** [comment]
ok, the document search never show this page if i'm searching for the word poster.
but thank you
