### ISSUE TITLE
addRemoteTextTrack() are not added to textTracks() list

### ISSUE THREAD

**Issue by crobinson42** [videojs/video.js#4111]
I found when I add textTracks programmatically, they're not available in the textTracks() list but they work and show up in the player, ie:

```js
player.addRemoteTextTrack({
  kind: 'captions',
  src: url,
  srclang: track.iso639,
})

console.log(player.textTracks().length) // 0
console.log(player.remoteTextTracks().length) // 0
```

Is this a bug or is there missing documentation?

*testing in chrome browser, osx, w/ videojs version 5.16*

**Comment by gkatsev** [comment]
That's... weird. It seems to be working fine for me. Can you make a reduced test case please?

**Comment by crobinson42** [comment]
I can't. I realized we're using an SDK (castlabs) that is probably doing some overwriting of the videojs api.
