### ISSUE TITLE
With v5.16.0. The HLS vod stream can't  playback on IE11 + Win10

### ISSUE THREAD

**Issue by aritakoichiro** [videojs/video.js#4121]
## Description
If  I using video.js to playback HLS on IE11 + Windows10 envirnment.
video.js sets the Html5 playback capability as 'maybe' . But It will not.
Because of 'Not support media format error' occured.
Suppose I change the Tech order as 'flash','html5' , It can playback by 'flash'.
This case,unfortunately evry browser using flash no matter whether the browser has native hls supprt.
 
## Steps to reproduce
The sample video definition is follows.
  <video id="test" class="video-js vjs-default-skin"
                 controls
                 width=640
                 height=360
                 preload="auto"
                 data-setup="{}">
      <source src="some.m3u8" type="application/x-mpegURL">
      <track kind="chapters" src="chapters.vtt" srclang="ja" label="Japanese" default>

      <track kind="captions" src="captions_ja.vtt" srclang="ja" label="Japanese" default>
      <track kind="captions" src="captions_en.vtt" srclang="en" label="English" >
  </video>

## Results
The video remains blackout.
Playback seems to starting.
No error messeages.
In the developper tool(F12) error shows as 
 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this medeia. [object Object]
### Expected
Please describe what you expected to see.
Playback normaly on IE11 + win10

I modified video.js as follows. It can playback on IE11 + win10 and more.
video.js line number 15705
Html5.isSupported = function () {
  // IE9 with no Media Player is a LIAR! (#984)
  try {
    Html5.TEST_VID.volume = 0.5;
  } catch (e) {
    return false;
  }
  /************************************************************************************************/
  /* Added at 2017.02.22 by K.ARITA                                                              */
  /* In case of IE11 + Win10. It won't playback HLS.                                              */
  /************************************************************************************************/
  var can=false;
  can = !!(Html5.TEST_VID && Html5.TEST_VID.canPlayType);
  if(can){
      var b = videojs.browser;
      if(!b.IS_ANDROID && !b.IS_ANY_SAFARI && !b.IS_CHROME && !b.IS_EDGE
           && !b.IS_FIREFOX && !b.IS_IE8 && !b.IS_IOS && !b.IS_IPAD && !b.IS_IPOD
           && !b.IS_NATIVE_ANDROID && !b.IS_SAFARI){
           //Probablly IE11 on Win10
           can = false;
         }
  }
  return can;
  /************************************************************************************************/
  /* End of Add                                                                                   */
  /************************************************************************************************/
  //return !!(Html5.TEST_VID && Html5.TEST_VID.canPlayType); //Commented at 2017.02.22 by K.ARITA
};

### Actual
Please describe what actually happened.
Can't playback.

### Error output
If there are any errors at all, please include them here.
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this medeia. [object Object]
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
5.16.0
#### browsers
what browser are affected?
IE11.576.14393.0
#### OSes
what platforms (operating systems and devices) are affected?
Windows 10 pro
### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-contrib-hls.js

**Comment by gkatsev** [comment]
I think this issue is more appropriate for the contrib-hls repo. However, if I'm understanding your question correctly, HLS is known to not work well on IE11 in html5 mode and flash is recommended in that case: https://github.com/videojs/videojs-contrib-hls#ie11.
If it's still an issue, I would recommend re-opening this issue against the contrib-hls repo, otherwise, if you're just unsure and have more questions, come talk to us on slack (http://slack.videojs.com, #playback channel).

**Comment by aritakoichiro** [comment]
I appriciate your sugestion. I abondon modified video.js.
I add codes prior creation player object which chaneges tech order to Flah first when the browser is IE.
Like this...
      videojs.options.flash.swf = "js/video-js.swf";
      if(isIe()){
        videojs.options.techOrder = ['flash', 'html5'];
      }
      player = videojs('myVideo',{ html5:{nativeTextTracks: false} });

Thanks.
