### ISSUE TITLE
Almost all links in docs.videojs.com show NOT FOUND

### ISSUE THREAD

**Issue by mpyw** [videojs/video.js#4122]
[Home | Video.js Documentation](http://docs.videojs.com/index.html#troubleshooting)

Dead links:

- http://docs.videojs.com/guides/faq.md
- http://docs.videojs.com/guides/troubleshooting.md
- http://docs.videojs.com/guides/setup.md
- http://docs.videojs.com/guides/player-workflows.md
- http://docs.videojs.com/guides/options.md
- http://docs.videojs.com/guides/tracks.md
- ...

**Comment by kavin-90** [comment]
New link is http://docs.videojs.com/tutorial-faq.html

**Comment by gkatsev** [comment]
Yeah, we need to update it. We're using this file right now https://github.com/videojs/video.js/blob/master/docs/index.md and have the links be relative so it works in github. We probably want to figure out a way for them to work in either case -- when in github, it work; and when on the docs site, it works.

**Comment by belling** [comment]
This has eaten up tons of my time the last week. I wish I'd thought of filing a bug here earlier, since this seems to be the only way to find a link to documentation that works.

**Comment by gkatsev** [comment]
I've restored the old `docs/` directory so, those links should continue working. We'll make sure to do a better job of updating urls and potentially setting up redirects for the old urls to the new urls.

**Comment by belling** [comment]
Thank you. Very much appreciated.

**Comment by mpyw** [comment]
Thanks, but hash links (e.g. `<a href="#foo"></a>`) don't seem to work...

**Comment by gkatsev** [comment]
Should be working now.
