### ISSUE TITLE
Flash to html5

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#4123]
Hi,
I have a web page where i can load all videos extensions formats. (mp4, fvl, Dash, m38u, rtmp ect...)
If i load a rtmp video, the player become a flash player and it's okay, but if i want to load a m3u8 video inside the same player after, the player stay in flash mode and the video do not start. but if i load a Youtube video after a rtmp flash video, it will work and the player go back to a html5 player, then after loading this Youtube video i can now load a m3u8 video in the same player. 
If i load a HLS video after a rtmp video it won't work, can i force the player to return to a html5 player?
the Youtube video do it but not the m3u8 video.

**Comment by gkatsev** [comment]
Can you please provide more information by answering the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md)? What browsers are you running this on and what are their versions? which version of videojs are you using? any plugins? how are you playing back HLS, DASH?
How are you switching between the different videos?
Would be great if you can provide a reduced test case.

**Comment by onigetoc** [comment]
Hi, if you enter url or click links, it will load a new video.
the code used in this web page is in the source code. with de HLS and Youtube plugin.
To test, Click the Bloomberg video, then load the "LIVE RTMP .STREAM:
Alb Uk HD" Link, try clicking Bloomberg link again, it will not work, then click on of the two Youtube links. After that, the Bloomberg will work again.
http://www.scriptsmashup.com/scripts/videojs-contrib-hls-master/demo-mix-YT-m3u8.html

```
      (function(window, videojs) {
        var player = window.player = videojs('vid1');
        //techOrder: ["html5", "flash", "youtube"]

        // hook up the video switcher
        var loadUrl = document.getElementById('load-url');
        var url = document.getElementById('url');
        loadUrl.addEventListener('submit', function(event) {
          event.preventDefault();
          
          console.log(getType(url.value)); // SEE TYPE
          
          player.src({
            src: url.value,
            type: getType(url.value)
            //type: 'application/x-mpegURL'
          });
          return false;
        });
      }(window, window.videojs));
```

Video type will appear in the console.log
we can see that it's alway the right one.

**Comment by gkatsev** [comment]
contrib-hls works with either the flash or html techs. I believe the issue, though, is that you're using incompatible contrib-hls and swf versions. You'd want to either downgrade your version of contrib-hls or tell videojs to use a newer version of the swf, I think you want to use version 5.3.0 of the swf.
The reason why it works when you go through the youtube video first is because it switches to the youtube tech and then back to the html5 tech because it's preferred, but contrib-hls can and will try to continue using the current tech if it is supported.

Hope that helps.

**Comment by onigetoc** [comment]
I thought that using: https://vjs.zencdn.net/5.16.0/video.min.js 
will load the lattest swf?

is there a download link just to get the 5.3.0 swf ?

**Comment by gkatsev** [comment]
You can set an option for the swf url on the flash tech
```
{
  flash: {
    swf: 'http://vjs.zencdn.net/swf/5.3.0/video-js.swf'
  }
}
```

**Comment by onigetoc** [comment]
Ok, my test worked with versio 5.3.0
is there a way to force the tech to return to html5 video if i want to?
Like the Youtube plugin seem to do.

**Comment by gkatsev** [comment]
The youtube plugin is its own tech, so, when switching from a youtube video to another video it chooses techs again. There's currently no way to choose a specific tech.
