### ISSUE TITLE
VideoJS and RTMP

### ISSUE THREAD

**Issue by BrkCoder** [videojs/video.js#4124]
## Description
Briefly describe the issue.
Hello I am try to run rtmp video on videojs but with no success.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. I used the  following url(for example only):
[rtmp://aljazeeraflashlivefs.fplive.net/aljazeeraflashlive-live/aljazeera_ara_high](url)
2. I am trying to load videojs controller and insert the above url as a source. This is my code:

```
<link href="http://vjs.zencdn.net/5.0.2/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/ie8/1.1.0/videojs-ie8.min.js"></script>
    <script src="http://vjs.zencdn.net/5.0.2/video.js"></script>
    
  <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640" height="264" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
    <source src="rtmp://aljazeeraflashlivefs.fplive.net/aljazeeraflashlive-live/aljazeera_ara_high" type="rtmp/mp4">
    <track kind="captions" src="../shared/example-captions.vtt" srclang="en" label="English"></track>
    <!-- Tracks need an ending tag thanks to IE9 -->
    <track kind="subtitles" src="../shared/example-captions.vtt" srclang="en" label="English"></track>
    <!-- Tracks need an ending tag thanks to IE9 -->
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>
```

Does VideoJS support rtmp streaming, it says according to the documentation that it support flash videos(is that include rtmp?)

### Expected
I expected to see a video streaming.

### Actual
Actually I don't received any streaming.

**Comment by gkatsev** [comment]
I think this is answered in the [FAQ](https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-play-rtmp-video-in-videojs).
Relevant section:
> The main thing to be aware of is that video.js splits the connection url and stream name with the & character. So, you'd want to update the url to follow that format. For example: `rtmp://example.com/live&foo` or `rtmp://example.com/fms&mp4:path/to/file.mp4`

**Comment by BrkCoder** [comment]
where do I need to split it, it isn't clear enought to me
