### ISSUE TITLE
Nit-pick: v5.17.0 version bump not on 5.x branch

### ISSUE THREAD

**Issue by MattiasBuelens** [videojs/video.js#4133]
It looks like something went wrong with the commits for the 5.17.0 release.

The version bump for version 5.17.0 ([`b8c6e63`](https://github.com/videojs/video.js/commit/b8c6e6303e7605a924c0d7c2e0af5ef4dc5f35ad)) was not pushed to the [`5.x` branch](https://github.com/videojs/video.js/tree/5.x), it is only accessible on the [`v5.17.0` tag](https://github.com/videojs/video.js/tree/v5.17.0). As a result, the current head for the `5.x` branch ([`fa97309`](https://github.com/videojs/video.js/tree/fa97309a7835f5d66dbefec7dcc3b4aa37b6d291)) still [lists `5.16.0` as version number](https://github.com/videojs/video.js/blob/fa97309a7835f5d66dbefec7dcc3b4aa37b6d291/package.json#L4), and [does not have the changelog](https://github.com/videojs/video.js/blob/fa97309a7835f5d66dbefec7dcc3b4aa37b6d291/CHANGELOG.md) for 5.17.0.

This is not really a big deal, it's just a bit confusing when you pull the `5.x` branch in a fork and you see an older version number in `package.json`. I don't know if there's a good way to fix this either:
* You could cherry-pick `b8c6e63` onto `5.x` now, but then users may incorrectly believe that the newer changes after 5.17.0 was published are already part of the 5.17.0 release.
* You could rebase `5.x` onto `b8c6e63`, but then you're rewriting history which will cause issues for forks.

I guess it's better to just do nothing for now, but maybe try to remember to fix the changelog whenever you release the next `5.x` version? 😉

**Comment by gkatsev** [comment]
Whoops, good catch. I guess I forgot to push it to the branch at some point. I might just make a commit that updates the package.json but we're do for another release anyway.

**Comment by MattiasBuelens** [comment]
Fixed in commit [`d838cd8`](https://github.com/videojs/video.js/commit/d838cd8c33e27385461a54cd161f974f725a0973).

**Comment by gkatsev** [comment]
Thanks @MattiasBuelens forgot to close this.
