### ISSUE TITLE
vjs-selected class was not added to playback and caption setting show below player

### ISSUE THREAD

**Issue by kavin-90** [videojs/video.js#4142]
Older version add vjs-selected class to menu item when click but latest version does not add them is it me or it was removed?

**Comment by gkatsev** [comment]
Can you describe what you're referring to? The only place I'm aware it should be used it the menus and it seems to still be present there.
A test case would be great as well.

**Comment by kavin-90** [comment]
i added playback rate when i click on 5.4.6 version selected class added but when using latest version it never added to menu to check it u need to press F12.

**Comment by gkatsev** [comment]
Hm... there might be a bug with the playback rate menu. Seems to be working fine with things like the captions menu, though.

**Comment by kavin-90** [comment]
It seems working but i can't tell working but i also faced other issue too it related to caption .

Caption setting window show below player so i've to use own css to position it correctly.

**Comment by gkatsev** [comment]
Which version of videojs are you using?

**Comment by kavin-90** [comment]
Latest version 5.16.0

**Comment by gkatsev** [comment]
Looks like the captions settings are dropping down because of fluid mode. The playback rate item is being fixed.
