### ISSUE TITLE
Where are the Docs for 5.x?

### ISSUE THREAD

**Issue by adgoncal** [videojs/video.js#4144]
## Description
http://docs.videojs.com/
The docs are pointing to versions v6.0.0-RC.2. Is there an option to view the docs for 5.x? 

- If yes, how?
- Otherwise, why show the docs for the release candidate instead of the stable release on the official website?

## Steps to reproduce
Visit http://docs.videojs.com/ and look for the docs for v5.x

### Expected
Docs for stable release or option to see the docs for stable release.

### Actual
Only the docs for v6.0.0-RC.2 are available

**Comment by gkatsev** [comment]
Most things haven't changed and still apply. You can find the old docs at http://docs.videojs.com/docs.

**Comment by adgoncal** [comment]
Thank you!
