### ISSUE TITLE
Firefox font flash, when creating and disposing videojs

### ISSUE THREAD

**Issue by UralZima** [videojs/video.js#4151]
Hello. I am using videojs 5.17.0 in jQuery UI Dialog. I have multiple clickable items on the page, every have a video. I want to show different video in same dialog, based on which item user clicks.
So when dialog opens, I create a video element with jQuery.html() function and initialise videojs on that element. When closing dialog, video destroys with player.dispose().

When dialog is opened, custom font used on the site flashes on the whole site, the same occurs when closing dialog. Every time. How to avoid font flash in firefox when creating/destroying videos? Also not only flashes, it is like CSS reloading, many items flashes or moving in size fastly.

In chrome all seems fine. It is not jQuery UI dialog issue, it works well without videojs

Please help. Thanks

**Comment by mister-ben** [comment]
Could you create a minimal test case that reproduces the issue? I've put together an approximation of what you describe [here](http://output.jsbin.com/qisekax) which does not cause this behaviour.
