### ISSUE TITLE
Quick Start uses 5.11 URLs

### ISSUE THREAD

**Issue by forbesjo** [videojs/video.js#4159]
## Description
The [quick-start](https://github.com/videojs/video.js/tree/5.x#quick-start) uses 5.11 URLs when video.js is up to 5.16 (http://vjs.zencdn.net/5.16/video.min.js). Should there be a major version URL on the CDN so the README is up to date?

**Comment by gkatsev** [comment]
We do have a major url `5-unsafe`. Historically, we didn't have a `5/` because it's probably not a good idea to have it auto-upgrade across minor versions like that as it's likely to break things.
However, maybe it's not as big of an issue and we should just do that.

**Comment by forbesjo** [comment]
Closing since the 6.0 is a higher priority
