### ISSUE TITLE
v5.18.2 is missing the dist folder

### ISSUE THREAD

**Issue by d3x7r0** [videojs/video.js#4162]
Hello,

It looks like the recently released v5.18.2 is missing the dist folder. We just noticed this when builds started breaking for us.

**Comment by gkatsev** [comment]
Oh, that's not good. I'll take a look. Thanks for letting us know.

**Comment by fabrigit** [comment]
Please fix this asap...

**Comment by gkatsev** [comment]
5.18.3 is up with the dist folder.

**Comment by ben-rabid** [comment]
Thank you @gkatsev - our pipeline is working again :)
