### ISSUE TITLE
RTMP .f4v

### ISSUE THREAD

**Issue by haietza** [videojs/video.js#4165]
## Description
How to use VideoJS with RTMP and .f4v

## Steps to reproduce
1. Insert working HTML5 video source code for HTTP/.f4v
`<video
          id="my-player"
          class="video-js"
          controls
          preload="auto"
          data-setup="{&quot;language&quot;: &quot;en&quot;}">
        <source src="http://www.appstate.edu/~meltonml/mighty_mouse.f4v" type="video/mp4"></source>
</video>`
2. Modify for RTMP
`<video
          id="my-player"
          class="video-js"
          controls
          preload="auto"
          data-setup="{&quot;language&quot;: &quot;en&quot;}">
        <source src="rtmp://streams-dev.appstate.edu/private/&amp;mp4:meltonml/mighty_mouse.f4v" type="rtmp/mp4"></source>
</video>`

### Expected
Expected to see Flash player output from VideoJS, as with .mp4 and .flv extensions
### Actual
Flash player is output, but video does not play

### Error output
No visible errors

#### videojs
5.11
#### browsers
Chrome
#### OSes
macOS Sierra 10.12.3
### plugins
No plugins

**Comment by mister-ben** [comment]
I'm unable to reproduce. Your source works [here](http://output.jsbin.com/sawojiq), as long as Flash is available of course.

**Comment by haietza** [comment]
I found my issue - I had included a closing </source> tag that appeared to be causing a problem, as well as having another player with the same id that was conflicting. I just wasn't sure if my code for the .flv version was correct - thank you so much for the quick response and working example!
