### ISSUE TITLE
Not implemented at t.e.Pd

### ISSUE THREAD

**Issue by dkchittimilla** [videojs/video.js#4168]
Hi,

Can some one please let us know why this browser error will occur. 

Error: Method Not implemented at t.e.Pd

Currently we are getting huge number of these errors being logged into application insights. When I try to browse the page I am not able to see anything in developer tools. This is for IE11 browser.

**Comment by gkatsev** [comment]
Hi, can you please include which version of videojs you're using? Preferably, answer the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md) in full?

**Comment by dkchittimilla** [comment]
Hi, we are using v4.12.11 version of Video.js

**Comment by gkatsev** [comment]
Video.js 4.12.11 is quite old. You're also using the minified file which mangles all names, making it hard to debug. I would highly recommend updating to Video.js 5 (if not 6 which just came out :D).
Another option is trying the unminified file and seeing whether it's fixed there.
