### ISSUE TITLE
Android Chrome , Mac Safari this.trigger('seeking'); called on clicking replay button after completion of video playback 

### ISSUE THREAD

**Issue by naveen2245** [videojs/video.js#4178]
Seek function is called when the replay button is clicked on videojs video in Android chrome,Chrome windows,Mac Safari without reloading the video .

Please confirm whether this a videojs behaviour or is it specific to these browser ?

**Comment by gkatsev** [comment]
Yup, if you [check the spec,](https://www.w3.org/TR/html5/embedded-content-0.html#dom-media-play) it says to seek to the beginning of the video if we've ended.

Hope that helps.
