### ISSUE TITLE
How to moving video settings to one place?

### ISSUE THREAD

**Issue by sohrabzia** [videojs/video.js#4179]
Hi,  I have several videos on page  I want to move video settings to separate page since they all are same for all videos  (i-e)
``controls preload="auto" width="640" height="268" 
  data-setup='{}'``

To reduce markup for video and DRY things up. currently I have this settings on separate js page

```
videojs("myPlayer", { 
"techOrder" : ['html5', 'flash'],
"controls": true, 
"autoplay": false, 
"preload": "none",
"aspectRatio":"640:200",
"playbackRates": [1, 1.5, 2],
 });
```

here is markup for all videos
```
<video id="myPlayer" poster='Theme/img/banner/thumbnail1.jpg'>
     <source src="https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.mp4" 
     type='video/mp4' />
 </video>
```

My issue is that it is only working with first video and other videos are not working.
I know I have to do something with ID but I have no idea. can someone please help.
Thanks.

(P.S) I am adding css classes with jquery that's why it is not in markup and is working fine.

**Comment by Globulopolis** [comment]
It's described in Docs https://github.com/videojs/video.js/blob/master/docs/guides/setup.md#manual-setup
But I suggest to use automatic setup for you. It's clean and does not require additional coding.

**Comment by sohrabzia** [comment]
Thanks for your response. I have created [JsBin](http://jsbin.com/qexijegadi/edit?html,js,output)
can you check this. I have added 
```
data-setup='{}'
```
its not working, am I missing something?
how do i refer data-setup in js file?

**Comment by Globulopolis** [comment]
1. If you setting up an options via data-setup do not use JS to setup and otherwise.

Try
```
data-setup='{"techOrder": ["html5", "flash"], "controls": true, "autoplay": false, "preload": "none", "aspectRatio": "640:200", "playbackRates": [1, 1.5, 2]}'
```
2. You can access data-setup via(for single player instance)
```
var opts = $('.player_class').data('setup');
opts = JSON.parse(opts);
```
addClass() is this necessary? I'm not tested but if you trying to add css class, you need to do it before player init.

**Comment by sohrabzia** [comment]
addClass() is not necessary I just wanted to reduce markup for developers. I cannot use one data-setup for several video players?  like normally in any jquery library we have "settings" function.

**Comment by Globulopolis** [comment]
> I cannot use one data-setup for several video players?

You can. But you mean something like a global settings https://github.com/videojs/video.js/blob/master/docs/guides/setup.md#global-defaults.

**Comment by sohrabzia** [comment]
Yes I was just reading that. this is what I am looking for. one more thing....where do I put this 
```
videojs.options.autoplay = true;
```

Excuse for basic question, I am not  good at js.

**Comment by Globulopolis** [comment]
```
<script>
videojs.options.autoplay = true;
</script>
```

**Comment by sohrabzia** [comment]
thank you so much :1st_place_medal:  but how do i write multiple options
I have tried 

```
<script>
videojs.options.autoplay = true;
videojs.options.controls = true;
videojs.options.aspectRatio= "640:50",
videojs.options.playbackRates= [1, 1.5, 2]
</script>
```

this doesn't work.
