### ISSUE TITLE
Youtube to hsl src change crashes with error at mediaSecondsLoaded

### ISSUE THREAD

**Issue by amosgwa** [videojs/video.js#4182]
## Description
I am trying to play a hls video at the end of a youtube video. But, it kept crashing the player. I can't seem to find where I did wrong. This also happens with MP4 to hls; but the player works from Youtube to MP4. Here is the [jsfiddle](https://jsfiddle.net/amosgwa/avyto22v/).

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Press play button. Then, skip to the end of the video.
2. The player crashes.

### Expected
The video should continue to play a hls video. It loads the captions but not the video.

### Actual
The source of the video is blob:something instead of the actual hls video link.

### Error output
> `VIDEOJS: TypeError: Cannot redefine property: mediaSecondsLoaded`
#### videojs
5.18.3
#### browsers
Chrome
#### OSes
MacOS
### plugins
hls and youtube

**Comment by gkatsev** [comment]
It looks to me like a problem with Vuejs where it's somehow making some internal objects in videojs "reactive" and when they change it blows up.
