### ISSUE TITLE
Full Screen Issue on IOS

### ISSUE THREAD

**Issue by juanpamv3** [videojs/video.js#4183]
Hello,

I have an issue with the video player that is happening only in IOS devices, for example Ipad Pro,
When the user click the full screen button the video goes to full screen mode and immediately goes to normal view mode. A strange behavior we noticed is that if the user clicks the button and leave it pressed for a couple of seconds it works ok.

Explain in detail the exact steps necessary to reproduce the issue.
1. Click full screen button on IOS devices

## Results
video goes to full screen mode and immediately goes to normal view mode

### Expected
video should open in full screen mode normaly

### Error output
No error ouputs

**Comment by gkatsev** [comment]
One thing that could potentially be happening here is that the fast-click library is being used. Then the button ends up being basically clicked twice because of fast-click.
