### ISSUE TITLE
player.requestAnimationFrame undefined?

### ISSUE THREAD

**Issue by Mike-Bell** [videojs/video.js#4194]
## Description
[Relevant docs](http://docs.videojs.com/Player.html#requestAnimationFrame) refer to a `requestAnimationFrame` function on the player object. This does not seem to be defined. See [relevant jsbin](http://jsbin.com/kepoqixoci/edit?html,console,output).

## Steps to reproduce
Open [relevant jsbin](http://jsbin.com/kepoqixoci/edit?html,console,output), see that the player.requestAnimationFrame function is undefined.

### Expected
I expect player.requestAnimationFrame to be a function I can call and function as the docs specify.

### Actual
player.requestAnimationFrame is undefined

#### videojs
Tried on 5.11, 5.17, and 5.0
#### browsers
At least Chrome.
#### OSes
At least Windows
### plugins
No

**Comment by Mike-Bell** [comment]
Perhaps this is a new feature coming in 6?

**Comment by OwenEdwards** [comment]
@Mike-Bell yes, the docs you're talking about specifically mention "v6.0.0-RC.2"; the `requestAnimationFrame` function was added in 1ba1f5aabddd0d59872bf25cedad7e64881f5d99, which is part of the v6.x development. It isn't supported in v5.x.

**Comment by Mike-Bell** [comment]
@OwenEdwards Thanks for the clarification. Guess I'll close this as not a bug.
