### ISSUE TITLE
Minimum time to play

### ISSUE THREAD

**Issue by dyagilevart** [videojs/video.js#4195]
Is it possible to set the minimum time interval for the downloaded file, or the minimum percentage of downloads after which the player will resume playing again. Now, with a poor connection, the video is played and interrupted several times in a row.

**Comment by gkatsev** [comment]
For the most part, we're relying on the browser to handle the downloading and playing of video, so, there's not much you can do if you're playing an mp4.
If, however, you're using something like HLS (or another adaptive format), you could tweak it a bit but if you have a lot of users with poor connections, you'd want to have a really low bitrate rendition.
I would definitely recommend using something like HLS over trying to play mp4s.

Hope that helps.
