### ISSUE TITLE
Buffered ranges show not correctly

### ISSUE THREAD

**Issue by esaker** [videojs/video.js#4201]
## Description
Sometimes when jumping in video there is empty space between position of jump and buffered ranges

### Expected
![2017-03-14 14 01 34](https://cloud.githubusercontent.com/assets/5815419/23901813/8919a428-08c7-11e7-988f-0792e92f819a.png)

### Actual
![2017-03-14 14 01 51](https://cloud.githubusercontent.com/assets/5815419/23901821/92da0390-08c7-11e7-8e41-85cdca34ab14.png)
![2017-03-14 14 02 28](https://cloud.githubusercontent.com/assets/5815419/23901838/9c300d4a-08c7-11e7-88bd-f4a0bdcff86c.png)

## Additional Information
videojs v.5.15.1

**Comment by gkatsev** [comment]
this is probably as designed. At some point, we decided that we should reflect the value of `buffered()`.
When you get into a situation like this, try logging out `player.buffered().length` and then also each item and it should match up.

**Comment by GooG2e** [comment]
can you say please why in firefox I see Expected buffer and on chrome actual...
And where is logic - buffer area that forward your zone...
How can I change this?
videojs 7.0.5
