### ISSUE TITLE
VIDEOJS: ERROR: SyntaxError: Unexpected token ' in JSON at position 1

### ISSUE THREAD

**Issue by TheKassaK** [videojs/video.js#4205]
Hello, I'm using <script src="http://vjs.zencdn.net/5.8.8/video.js"></script> and I get this error on my page :

```
video.js:81VIDEOJS: ERROR: SyntaxError: Unexpected token ' in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.SafeParseTuple [as default] (video.js:5)
    at Function.getTagSettings (video.js:81)
    at new Player (video.js:81)
    at videojs (video.js:81)
    at autoSetup (video.js:81)
```

The player is working well, but I don't know why I have this error in my console ? Thanks for help :)

**Comment by gkatsev** [comment]
It sounds like your data-setup property isn't valid JSON.

**Comment by OwenEdwards** [comment]
@TheKassaK see #2022. You can't use `'` (single quote) in JSON, only `"` (double quotes).

**Comment by masoudit** [comment]
In python you can use json.Dump(str) before send result to html template. with this command string convert to correct json format and send to html template. After send this result to JSON.parse(result) , this is correct response and you can use this.
