### ISSUE TITLE
Guide docs links are broken

### ISSUE THREAD

**Issue by Dottenpixel** [videojs/video.js#4206]
## Description
Guide docs links are broken

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Go to http://docs.videojs.com/
2. Click any link under 'Guides'
3. Experience the 404-ness

### Expected
A guide to help me with video.js

### Actual
404

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by BrandonOCasey** [comment]
You should be able to use the side-bar to look at guides for now, we are working on a fix in https://github.com/videojs/video.js/pull/4200 that should fix any links to guides. However, it is not live yet

**Comment by gkatsev** [comment]
This has been fixed. Thanks for reporting @Dottenpixel
