### ISSUE TITLE
HLS streaming works on Chrome and Firefox but not on Safari.

### ISSUE THREAD

**Issue by aditya-vadlamani** [videojs/video.js#4207]
## Description
Streaming newbie here. I have HLS streaming setup with 1080p videos being served. VideoJS along with videojs-contrib-hls seems to play videos on Chrome and Firefox but not on Safari. I here only audio. What could be the error?

#### videojs 
5.18.0
#### browsers
Safari 10.0.2
#### OSes
OS X 10.12.2
### plugins
VideoJS-contrib-hls

**Comment by mister-ben** [comment]
It's hard to say without the stream in question. What's the URL? Does it play in the player at http://videojs.github.io/videojs-contrib-hls ?

**Comment by aditya-vadlamani** [comment]
Test site URL: https://videostreaming.mookit.co/hls/

Video URL: https://videostreaming.mookit.co/test3.mp4/master.m3u8

It's not working at that link.

**Comment by s3bubble** [comment]
Safari has its own implementation of hls playback so this might be the issue.

videojs-contrib-hls can override the Safari default and utilise their setup might be worth giving it a try.

Add this to your setup.
~~~
videojs.options.hls.overrideNative = true;
videojs.options.html5.nativeAudioTracks = false;
videojs.options.html5.nativeVideoTracks = false;
~~~

**Comment by aditya-vadlamani** [comment]
Issue solved. Turns out that the video was interlaced. Transcoding it into progressive solved the issue.

**Comment by mister-ben** [comment]
Thanks for reporting back. Interesting data point that videojs-contrib-hls was handling it ok on Chrome and Firefox, but Safari's native playback cannot.

**Comment by craacker** [comment]
i solved my case by changing the video  frame rate to 60 . 
ffmpeg -i example.mp4 -r 60  output.mp4 , then make the  hls from vod.
