### ISSUE TITLE
Android Chrome Issues Chrome is forcing download

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#4214]
## Description
Hi all I thought it was worth posting the issue I am experiencing here to see if anyone else is experiencing the same problem or can suggested a solution.

I was testing on Android chrome on my Galaxy S3 as I was having issues getting my videos to play, then I decide to strip the whole setup right back to just the video js example.

http://jsbin.com/qizopal

This works fine in the desktop chrome browser but wouldn't work on mobile chrome browser on Android.

So after investigating, I noticed that even if I pasted the direct mp4 link into the browser I was still getting the issue it would automatically start the downloading the file instead of playing it.

Then I noticed the same thing was happening on my desktop chrome browser if you paste the mp4 link in then it will download instead of play worked on firefox.

So I spoke to AWS support and it was an issue with the mimetype upon upload the content type was getting set to application/octet-stream not video/mp4.

I download the main video js video from here http://vjs.zencdn.net/v/oceans.mp4 uploaded to s3 and then set the mime type to video/mp4 in AWS s3 

https://s3.amazonaws.com/Loop.Sam/oceans.mp4

This ink would then play fine in chrome when opened so thought great the issue is resolved but tested on Android chrome and it won't play not only with video js but also just with the standard video tag here is an example can someone else test on their Android phone I am testing on my Galaxy S3.

http://output.jsbin.com/qizopal 

## Steps to reproduce
Try this test in Android Chrome browser it works on firefox mobile browser.
http://output.jsbin.com/qizopal

### Error output
no errors just hangs

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.18.4
#### browsers
Android Chrome

**Comment by samueleastdev** [comment]
Update so after debugging some more updating chrome on Android if i remove the https:// from the url and just set it to //s3.amazonaws.com/Loop.Sam/oceans.mp4 then it works?

**Comment by samueleastdev** [comment]
Reset my phone now everything works

**Comment by gkatsev** [comment]
That's weird. Not really sure what else to add. Making sure that the content-type is set correctly is crucial. It's possible that android is very strict in terms of protocols matching as well, but I would be surprised by it.
Glad you were able to figure out some way of making it work, though.
