### ISSUE TITLE
API method for accessing HTML Media Element (ie. `tag`)

### ISSUE THREAD

**Issue by silverbucket** [videojs/video.js#4224]
In some cases it may be necessary to get access to the actual HTML Media Element (video tag) that the video.js player was initialized with, without having any context about when / where / with what options a particular video.js player instance came from. 

The return object from `player.tech()` does not contain the `tag` element (which is the video element / HTML Media Element).

Regardless of which plugin (dash, hls, etc.) is being used. It would be extremely useful to have a defined "official" API method for accessing the media element that any give player instance is operating on. 

So my question is twofold:

1) Does something already exist that I'm just missing?

2) If not, would you be open to accepting a pull request? I was thinking the most obvious place would be to add a method to the `Player` class. Assigning `this.tag_` and creating a method to fetch it. As for the name - do you have any suggestions? (`getTag`, `getMediaElement` ?)

**Comment by gkatsev** [comment]
Each component has an `el()` method that returns the DOM element that is tied to it (though, we're moving away from requiring components to have DOM elements, it's still mostly used for that).
Given that the Tech is a Video.js component as well you should be able to do `player.tech().el()`.
And as the `tech()` says in master/6.0, "I hope you know what you're doing" :)

Hope that helps.

**Comment by silverbucket** [comment]
Thanks @gkatsev! 

`this.player.tech({ IWillNotUseThisInPlugins: true }).el();` looks like it's just what I'm looking for.
