### ISSUE TITLE
Video format not supported...

### ISSUE THREAD

**Issue by Octtavius** [videojs/video.js#4225]
## Description
I have a webpage that uses videoJS to load different type of videos (mp4, vimeo, youtube ) and all works fine. Now, I am trying to load a video from Kaltura but it says the format is not supported. 

## My Codes
HTML

    `  <video
           id="myVideo"
           ng-show="urlProvided"
           class="video-js vjs-default-skin"
           controls
           width="600"
           data-setup='{ "techOrder": ["html5", "flash", "youtube", "vimeo"]}'
       >
      </video>`

JS
This function checks what type of video is the url (mp4, vimeo or youtube), and passes the right parameter. All works EXCEPT the if statement that checks for kaltura video:

     `function playApropriateType(url) {

                    //check if video is from youtube
                    if(url.indexOf('youtube') != -1) {
                        scope.player.src({type: 'video/youtube', src: url});
                        scope.player.load();
                    }

                    //KALTURA not working
                    else if(url.indexOf('kaltura') != -1) {
                        scope.player.src({"type":"video/mp4", "src":url});
                        scope.player.load();
                    }

                    //check if link is vimeo from payed account
                    else if( ((url.indexOf('mp4') != -1) && (url.indexOf('vimeo') != -1)) || url.indexOf('mp4') != -1) {
                        scope.player.src({"type":"video/mp4", "src":url});
                        scope.player.load();
                    }

                    //check if video is simple vimeo
                    else if(url.indexOf('mp4') == -1 && url.indexOf('vimeo') != -1){
                        scope.player.src({type: 'video/vimeo', src: url});
                        scope.player.load();
                    }
                }`

## Results

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
My question is, does VideoJS support Kaltura videos at all or it is just me missing something in my code????

### plugins
videojs-vimeo
videojs-youtube
videojs-markers

**Comment by gkatsev** [comment]
If the Kaltura video is just a plain mp4, it should be working. Otherwise, if it's something more than that, unless there's a Video.js tech or plugin for Kaltura, we won't be able to play it.
Do you have a live reduced test case?

**Comment by Octtavius** [comment]
Hi, I do not have a reduced test case unfortunately.
I will try to see then if Kaltura provides links to mp4 files. Also I saw that VideoJS has a plugin that supports HLS something like this: 

`<source
     src="https://example.com/index.m3u8"
     type="application/x-mpegURL">`

Hopefully that will work.

**Comment by gkatsev** [comment]
You can use [contrib-hls](https://github.com/videojs/videojs-contrib-hls) to play back HLS video.
But make sure to read the [hosting considerations](https://github.com/videojs/videojs-contrib-hls#hosting-considerations) section. If they don't provide CORS, then it won't work.

I'm going to close this now because I don't think it'll require any changes to videojs, but discussion can definitely continue in this issue.
