### ISSUE TITLE
https://vjs.zencdn.net/font/2.0.0/VideoJS.eot returns forbidden

### ISSUE THREAD

**Issue by s-o-na** [videojs/video.js#4226]
## Description
https://vjs.zencdn.net/font/2.0.0/VideoJS.eot returns forbidden when I include video-js.min.css css file from CDN. 
This is the output when I opened the font file from browser:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A7265B3FD54E7CCB</RequestId>
<HostId>
C1U8mjMv/Fcjy9DoJDiHvo7cR3ajXUuRHJ67o1y+UudlmAsxmYGZANxdz6odiE1TRkNf6tyJ0qc=
</HostId>
</Error>
```

**Comment by gkatsev** [comment]
Looks like we never actually published it. Looking into it now.

**Comment by gkatsev** [comment]
Should be up now. Thanks!

**Comment by s-o-na** [comment]
Thanks a lot :)

**Comment by gkatsev** [comment]
You're welcome. Not sure how it's been published for so long but not actually available.
