### ISSUE TITLE
Video not played with type="video/quicktime"

### ISSUE THREAD

**Issue by shenhf** [videojs/video.js#423]
Video not play in Chrome, Workded after change type="video/mp4"

Is this a bug of video-js? Carrierware recognize .mov content_type to "video/quicktime", and all the .mov can't played in video-js player.

``` html
<video id="video_3" class="video-js vjs-default-skin" controls="" preload="none" width="768" height="576" poster="/video/29/3/poster.png" data-setup="{}">
<source src="/video/29/3/051-rails-routing.mov" type="video/quicktime">
</video>




```

**Comment by HeyWrecker** [comment]
Bad link to the mimes document.

**Comment by heff** [comment]
@HeyWrecker found the old page and put it back up here: http://videojs.com/mimes.html

**Comment by myconnec** [comment]
@akinne please help.... how did you get it to work for you? i would like to allow users to upload .mov and all cell phone mp4's and play them back in chrome. however, chrome will not play either format

**Comment by myconnec** [comment]
i am using rails and here is my video.js code " <%= videojs_rails sources: {mp4: @listing.pin_image.url, webm: @listing.pin_image.url, ogg: @listing.pin_image.url }, autoplay: true, setup: "{}", width:"450", height:"450" do%>
      <% end %> for some reason i cant play .mov and some mp4 videos...

**Comment by mister-ben** [comment]
You've got to use formats and codecs that browsers can play. MP4s are only widely playable with the h264 and aac codecs. MOV isn't supported in HTML5 video.

**Comment by myconnec** [comment]
Thanks but i am new to raiks how do i do this please help



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by myconnec** [comment]
Or better yet what do i do.. i need to know how to convert the video for the user when they upload their videos



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by HeyWrecker** [comment]
You would need to set-up some type of transcoder on your server (for
example, ffmpeg) that receives the file and transcodes it to an HTML5
friendly codec. I'm not familiar with Rails so I can't give you the details
of how that would be set-up.

**Comment by myconnec** [comment]
Thanks for the insight however i know what is needed from what I've research, i need to know how to write it in rails so that it fits in my project.. i cant find rails example.    Btw i am using Cloud9

Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by HeyWrecker** [comment]
You could look to see if there are any existing libraries that extend Rails
to include a transcoder. Otherwise, you'll have to write a service in Rails
that calls / executes FFMPEG. For example, I've used the ColdFusion
<cfexecute> to issue a command to FFMPEG in the past. To try to write a
transcoder on your own is something I don't think you want to involve
yourself in.

**Comment by myconnec** [comment]
Got it thanks i will research that



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
