### ISSUE TITLE
this.el_.vjs_getProperty('buffered');   always return []

### ISSUE THREAD

**Issue by xiachaoxulu** [videojs/video.js#4232]
## Description

when i use rtmp , i pause the video, then i wait for a min and paly the video again ,but it play the next frame from the pause position. not the frame which is a min later.

so, i debug the code ,discover Flash.prototype.buffered function always return []. that means the rtmp source can not buffered?  

This is contradictory to the above phenomenon

 
thank you for give me some tips

**Comment by gkatsev** [comment]
As far as I can tell, the swf should be returning a range of `[0, duration]` for RTMP streams: https://github.com/videojs/video-js-swf/blob/master/src/com/videojs/providers/RTMPVideoProvider.as#L153-L160

**Comment by gkatsev** [comment]
Looking at it some more, I think it's because the RTMPVideoProvider is wrong. It should be `_metadata.duration` instead of `duration`. @xiachaoxulu would you be able to make a PR for it?
