### ISSUE TITLE
How to delete the download button??

### ISSUE THREAD

**Issue by Aki-lili** [videojs/video.js#4234]
How to delete the download button

**Comment by gkatsev** [comment]
Video.js's controls don't have a download button. If you're using Chrome with native controls, there's currently no way to do so but in chrome 58, they're adding an [experimental way of modifying the native controls](https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist).

Hope that helps.

**Comment by HankBrown** [comment]
` <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" controlsList="nodownload" width="640" height="360">
`
Adding **controlsList="nodownload"** seems like a fast fix.

https://stackoverflow.com/questions/39602852/disable-download-button-for-google-chrome/40975859#40975859

https://stackoverflow.com/questions/39602852/disable-download-button-for-google-chrome/40975859#40975859
