### ISSUE TITLE
problem with frame by frame when accessing last frame (25fps) of second odd

### ISSUE THREAD

**Issue by ale1967** [videojs/video.js#4240]
## Description
While reproducing a video at 25fps frame by frame, when the second is odd (for example the second 1'') the frame 01:24 (0-24) is not displayed, but it is always displayed the frame relative to timecode 02:00 (for second 1.96 and 2.0).
If doing the same test for an even second (for example second 2'') the last frame 02:24 is correctly displayed.

This behavior happens for all even and odd seconds.

We are using a video with the timecode overburned on it to check the result; playing the video with a player it's possible to see all frames (so also 01:24). 

The version we are using is 5.18.4, but we have tested the same behavior with 6.0 r5.
The player has been tested on Chrome

On the attached screenshots it's possible to see that if we set the time 1.96 (lower left corner) the player shows the frame at timecode 02:00, while if you set the time 2.96 the player shows the frame at timecode 02:24

![si1](https://cloud.githubusercontent.com/assets/8517668/24464231/7c7a29ac-14a9-11e7-9563-5031f575ecd8.JPG)
![no1](https://cloud.githubusercontent.com/assets/8517668/24464237/82651174-14a9-11e7-9728-9b90f3c09059.JPG)

UPDATE ----------------
This seems a problem on Chrome.

<img width="1440" alt="schermata 2017-04-04 alle 07 16 08" src="https://cloud.githubusercontent.com/assets/8517668/24642532/2736b15a-1908-11e7-8241-07c9a7f29ba0.png">

In this screenshot it's possible to see Safari in upper part and Chrome in lower part.
Any hints ?

Thanks

**Comment by oopoopoop** [comment]
Don't know about Safari, yet, but Firefox has similar issue. (windows box btw)

With the same video source I have, Chrome doesn't let me see 05:24 whereas Firefox won't let 06:00 to show.

I suspect your video has its GOP length at 50? Please test with GOP length set to 25 and see if it now happens every second instead of every other second.

**Comment by gkatsev** [comment]
Yeah, unfortunately, seeking isn't frame accurate. some browsers handle it better than others but there isn't a good answer here, I don't think.
