### ISSUE TITLE
I tested the demo error on IE8

### ISSUE THREAD

**Issue by JayenLee** [videojs/video.js#4244]
## Description

I tested the demo error on IE8

### Error output
If there are any errors at all, please include them here.
![image](https://cloud.githubusercontent.com/assets/10287391/24500009/5cf7d94e-1576-11e7-9bb0-b7c81a4fd933.png)
#### videojs 
5.19.1  5.18.4
#### browsers 
 ie8

**Comment by mister-ben** [comment]
Sorry, I don't know what that error message means. Do you have the IE shim in `<head>`?

    <script src="//vjs.zencdn.net/ie8/1.1.1/videojs-ie8.min.js"></script>
