### ISSUE TITLE
Plugin has a delay before it gets to its normal size

### ISSUE THREAD

**Issue by absalone** [videojs/video.js#4246]
Hi there,

I've been using video.js plugin through an adobe muse website.
It all works except for one thing : when the page loads, the video frame appears (with a background image), but it isn't at its normal height, and it takes a little while till the video frame is set to its proper size. After about 10 seconds, the frames get to their regular height. 
Would you know what is this issue? Why is there such a delay?
Here is the example I'm talking about : http://cenzanne01.businesscatalyst.com/manawatu-river.html

Thanks!

**Comment by mister-ben** [comment]
Your using fluid mode (you have the `vjs-fluid` class. This adjusts the player to match the aspect ratio of the video -- but it doesn't know the video aspect ratio until it's loaded video metadata. Until then, it defaults to 16:9.

This video is 4:3, so you could use the `vjs-4-3` class and it would start and remain at the same aspect ratio. Although for this particular video 4:3 might have been unintentional, perhaps re-exporting at 16:9 without the letterboxing is what you really want.

**Comment by absalone** [comment]
Thank you very much!!!
