### ISSUE TITLE
Call method in myPlayer.on('pause', function(event) { ...}); but shows "VIDEOJS: ERROR: TypeError: this.updateTime is not a function"

### ISSUE THREAD

**Issue by WaldenH** [videojs/video.js#4248]
## Description
In reactjs and code is in componentDidMount. If I call my own method in 
 `  myPlayer.on('pause', function(event) { ...}); `
it will  shows `"VIDEOJS: ERROR: TypeError: this.updateTime is not a function"`

Code as follows:
```
@autobind
export default class VideoBox extends React.Component {
... ...
  componentDidMount() {
    this.state.myPlayer = videojs( "test_video_1", {},
    function () {...
    });

    this.state.myPlayer.on('pause', function(event) {
      this.updateTime();
      //updateTime(); // both not work
    });// end of componentDidMount

  updateTime() {
      ...
   }
  }

```

**Comment by gkatsev** [comment]
Videojs's event system auto-binds the handlers to the object that they were called on. Meaning that the `pause` method was called with `myPlayer` as the context.
I would recommend either switching to use arrow functions or to bind the context yourself.

Hope that helps.
