### ISSUE TITLE
Problem: Player Controls Fail

### ISSUE THREAD

**Issue by davutcavdar** [videojs/video.js#4250]
## Description 
We have a problem with video.js player control elemets as you can see screenshot below. We are developing an angular project that displays live rtmp stream. 

### Actual
![error-ss](https://cloud.githubusercontent.com/assets/10333379/24553591/598944ec-1633-11e7-95b8-73d9f658eaeb.jpg)

Live stream is ok but control elements of  player fails.
## Additional Information
 HTML codes are standard, we have not changed anything.

```
  <div *ngFor="let Camera of cameras" >
     <div class="cam ">
       <video id="example_video_1" class="video-js vjs-default-skin vjs-big-play-centered"
          controls autoplay preload="auto" width="640" height="264" data-setup='{"example_option":true}'>
        <source [src] ='camURL(Camera)' type="rtmp/flv" />
        .......
```
### versions
 our project is using latest version of video.js ( "video.js": "^5.19.0",)

What could be possible reason for this problem?

**Comment by gkatsev** [comment]
It looks like you're not including the CSS file.
