### ISSUE TITLE
New build system doesn't have automatic github releases

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#4251]
We can re-use what we have setup in grunt on a postpublish.
We have disabling generating and updating the CHANGELOG.md for pre-releases, but pre-releases published to github releases would benefit from changelogs.

**Comment by smilemd** [comment]
Would be good to have dist folder with compiled version like it was before...

**Comment by joshuairl** [comment]
:( Really wish this had a dist/ directory already. 
<3 you guys.

**Comment by emilz0r** [comment]
Any progress on this? 

Really love the project, and would like to use it with bower. A bower package would not be essential as I could point the bower.json to the git repo.

**Comment by defaria** [comment]
Same issue. I am using bower and noticed that a bunch of stuff is missing... now I know why my code wasn't working.

**Comment by gkatsev** [comment]
We have this now.
