### ISSUE TITLE
have two control bar

### ISSUE THREAD

**Issue by luojianet** [videojs/video.js#4259]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.
![image](https://cloud.githubusercontent.com/assets/13119913/24735148/0818d2f0-1ab4-11e7-9ed7-46cf7573f3f1.png)

**Comment by gkatsev** [comment]
Weird. Might be that the native control bar is showing up behind our control bar. Unfortunately, it's hard to debug without more information requested in the issue template.

**Comment by luojianet** [comment]
http://mobile.xunlei.com use xunlei browser

**Comment by luojianet** [comment]
video::-webkit-media-controls {
		  display: none;
		}

		/* Could Use thise as well for Individual Controls */
		video::-webkit-media-controls-play-button {}

		video::-webkit-media-controls-volume-slider {}

		video::-webkit-media-controls-mute-button {}

		video::-webkit-media-controls-timeline {}

		video::-webkit-media-controls-current-time-display {}

**Comment by luojianet** [comment]
done,thank u
