### ISSUE TITLE
Using videojs with webpack

### ISSUE THREAD

**Issue by t-io** [videojs/video.js#4260]
I tried to get videojs up and running with webpack. 
I'm a novice when it comes to webpack so I'm not sure if this is really a bug or lack of knowledge.
As far as I understood the already closed issues in this repo it should work without any adjustments.

What I did so far was to install the latest videojs version with npm (5.19.1) `npm install video.js --save`
and in my source file I imported it like this: `import videojs from 'video.js';`

When I restart my development server I get the error `Uncaught TypeError: Cannot read property 'vttjs' of undefined`

Any suggestions how to get this working?

**Comment by gkatsev** [comment]
Hm... that's interesting. I can see it working here: https://www.webpackbin.com/bins/-Kh2p3H9xFzGq-vq0rmI

Can you provide more info, perhaps your webpack config? If you can, maybe even make an example on webpackbin or a git repo that reproduces your behavior. Would make it a lot easier for us to debug.

**Comment by t-io** [comment]
Thanks for the response and the webpackbin. With your code I was able to debug this. 
I was missing the exclude for the babel-loader. So there is no issue. 
Now it looks like this:
```
{
    test: /\.js$/, //Check for all js files
    use: [{
        loader: 'babel-loader',
        options: { presets: ['es2015'] }
    }],
    exclude: [
       path.resolve(__dirname, 'node_modules/')
   ],
}
``` 
and works like it should. 
Thanks for the help.

**Comment by gkatsev** [comment]
You're welcome. Glad you figured it out!
