### ISSUE TITLE
init vedio,how to hidden control bar.

### ISSUE THREAD

**Issue by luojianet** [videojs/video.js#4264]
In h5 page,initialize video player,I want hidden control bar,click video,show control bar,how can i do?

**Comment by luojianet** [comment]
online waiting...

**Comment by gkatsev** [comment]
If you want a more real-time answers, please head over to our [slack](http://slack.videojs.com).
To turn off the control bar, you can just call [`controls`](http://docs.videojs.com/Player.html#controls) with `false`. `player.controls(false);`.
