### ISSUE TITLE
Advices to read videos with subtitles and diferent languages on a website.

### ISSUE THREAD

**Issue by saturday92** [videojs/video.js#4265]
Hello people. Sorry for the bother, but i have an issue.
i dont know if it is ok to ask something like this here, but if not, please send me a link where to go. Thanks.
And my question is:
I'm building an website an i need to add a video with diferent language tracks and subtitles. For example... an .MKV video.
So i need an advice. Does it work with videojs? And if yes do i need to add a certain code?
If not, what player do you advise me, and there is a certain procedure to do use it?
Many thanks to all and have a nice day/night

**Comment by gkatsev** [comment]
Yup, Video.js supports captions. Check out our [text tracks guide](http://docs.videojs.com/tutorial-text-tracks.html).

This [mdn article](https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video) might also be useful for the general section. Video.js already provides UIs for choosing the subtitles language.

Hope that helps.
