### ISSUE TITLE
Default Component Tree doc doesn't contain VolumePanel component

### ISSUE THREAD

**Issue by alex-barstow** [videojs/video.js#4266]
## Description
The default component tree in master's `components.md` does not include the`VolumePanel` component. Should it? Currently, the tree still lists the `VolumeMenuButton` as a child of `ControlBar`, though it isn't added as a child in `control-bar.js` and appears to be a remnant from video.js 5.

Default Component Tree (in `components.md`)
https://github.com/videojs/video.js/blob/master/docs/guides/components.md#default-component-tree

**Comment by gkatsev** [comment]
Yes it should. We must've missed it in the update.

**Comment by alex-barstow** [comment]
If it's as simple as swapping out `VolumeMenuButton` for `VolumePanel` I can go ahead and make the PR if you'd like.

**Comment by gkatsev** [comment]
I think it is. A PR would be awesome.

**Comment by alex-barstow** [comment]
Do you want the tree to also list the children of `VolumePanel` (`MuteToggle` and `VolumeControl`)?
