### ISSUE TITLE
Videos with PCM sound not playing in Firefox on Mac.

### ISSUE THREAD

**Issue by seabasss** [videojs/video.js#4269]
My videos with uncompressed PCM sound are not playing the audio in Firefox on Mac.
It works great in Safari and Chrome.

Files encoded in AAC works in Firefox. Both have 48k sample rate if that matters.

Any ideas? My file is hosted on dropbox and it actually plays with sound in the dropbox video player if I load it without the dropbox ?raw=1 flag, not with it.

Thank you!

**Comment by gkatsev** [comment]
I assume it dropbox may be doing some kind of transcoding on their end without the `?raw=1` query param. I'm not sure that firefox supports raw PCM audio. I would definitely recommend using AAC or some other audio format that is known to be supported across all browsers you need to support.

**Comment by seabasss** [comment]
@gkatsev Thanks! Yeah the problem is that I let people fill in their own links to their own videos, which means that I need to tell them how to encode their videos, which is not likely to happen unfortunately. So then I need to store all their video content and have a compression engine to remove that responsibility from the user. Get in the game Firefox!
