### ISSUE TITLE
Vague error message when adobe flash is not up to date.

### ISSUE THREAD

**Issue by rjb25** [videojs/video.js#4270]
## Description
You have a very vague error message "No compatible source was found for this media." When flash has not been updated to latest version. I am using video js to host .flv videos and the last 3 devices I tried needed to update flash.
## Solution
Change the error message to either include "Try updating your flash version." Or replace the error entirely with "Your version of adobe flash is not up to date".
This would save me and I would guess many others the time having to write "If you are getting the error 'No compatible source was found for this media.' then try updating to the latest version of adobe flash".

**Comment by gkatsev** [comment]
We have removed Flash from core videojs support. It's still available in videojs-flash project. That project should probably add that message when trying to load that tech. You can also override the text of  `notSupportedMessage` as an option to the player to include anything.
