### ISSUE TITLE
Error message with the big X

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#4272]
In every version, in any test case.
The error mask or overlay message Show a big X with a message on top.
I do not understand why this big X is can't be clicked and closed.
You can do nothing on the player control bar, can't click Pause, can't click Previous Next, (I created a Previous Next button in the control bar)

On other video player, these big X error can be clicked and closed.
Sometime, i load another video with javascript and the video play but the big X ans message are still there. (i think it happen when we load another tech video, like flash ect)

And i find out that all messages are not showed on the top like the Youtube message or others messages.
But i can see it in my console.log with this javascript.

```
player.on('error', function() {
  console.log('The following error occurred:', this.error());
});
```
Like Youtube error show in my console.log

`Playback on other Websites has been disabled by the video owner. undefined`

**Comment by gkatsev** [comment]
The main reason is because normally, when we get an error, it's not really something recoverable.
The error can be hidden by calling `error` with `null`: `player.error(null)`.
There's also the [videojs-errors](https://github.com/brightcove/videojs-errors) project that gives you more customizeable errors.

**Comment by onigetoc** [comment]
For the X to be clickable and and hide remove the mask overlay?

**Comment by gkatsev** [comment]
The default errors that Video.js handles are generally unrecoverable without the developer doing something smart with the error, so, you can just hide the error display with the `player.error(null)` when you handle it. Or you can always just disabled it altogether by giving `errorDisplay: false` to the Video.js player options.
