### ISSUE TITLE
RTMP in Electron

### ISSUE THREAD

**Issue by pmachan** [videojs/video.js#4273]
Hi,
im trying use this libs for my App written in Electron (react, redux, webpack). I needed play RTMP video stream but when is APP packed by electron-packager RTMP stream is not working. If i build App by webpack and run it then its working (dev with hot reloading or builded version by webpack). Html file for electron is loaded by express so i dont use file:// protocol but http (no problem with flash trust restrictions). I tried use iframe with embeded RTMP videojs and its not working too :( (but on webpage is working).

Any idea what im doing wrong?

### Error output
`ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)`

#### electron-rebuild
^1.1.5
#### electron-packager
^7.3.0
#### videojs
^5.11.7 or ^6.0.0 with flash plugin
#### browsers
Chromium in Electron 1.3.5 (i cant update electron now)
#### OSes
All platforms

**Comment by mister-ben** [comment]
I've no experience in using Flash in Electron, but their guide on using Flash does note that you may need to adjust permissions for RTMP.

https://github.com/electron/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md
