### ISSUE TITLE
( Docs) README.md says that the video.js script needs to be added in the <head>, but the videojs.com Getting Started guide shows it being added at the end of the <body>

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#4276]
## Description

At https://github.com/videojs/video.js/blob/master/README.md#quick-start, it says:

> Thanks to the awesome folks over at Fastly, there's a free, CDN hosted version of Video.js that anyone can use. **Add these tags to your document's `<head>`**:
> 
> ````html
> <link href="//vjs.zencdn.net/5.11/video-js.min.css" rel="stylesheet">
> <script src="//vjs.zencdn.net/5.11/video.min.js"></script>
> ````
> 
> > For the latest URLs, check out the Getting Started page on our website.

But at the page that [Getting Started](http://videojs.com/getting-started/)  links to, the example shows:

````html
<head>
  <link href="http://vjs.zencdn.net/5.19.1/video-js.css" rel="stylesheet">

  <!-- If you'd like to support IE8 -->
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
    <source src="MY_VIDEO.mp4" type='video/mp4'>
    <source src="MY_VIDEO.webm" type='video/webm'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="http://vjs.zencdn.net/5.19.1/video.js"></script>
</body>
````

so the `video.js` script is added at the **end of the body**.

Is this a bug, or are there situations where one should be used instead of the other? This could use clarification.

**Comment by mister-ben** [comment]
I think putting the script in the head was only a requirement when it still contained the video shim for IE8.

**Comment by gkatsev** [comment]
Yup, what @mister-ben said. We probably should consolidate on recommending that video.js itself be put at the end of the body element with the ie8 shim (if necessary) in the HEAD.
