### ISSUE TITLE
ERROR : VIDEOJS: ERROR: TypeError: this.ytPlayer.getDuration is not a function.

### ISSUE THREAD

**Issue by mpmanwar** [videojs/video.js#4284]
When i am using youtube video in list view above error is showing and video is not playing in list.

**Comment by gkatsev** [comment]
Generally errors related to youtube should be opened against its repo: https://github.com/videojs/videojs-youtube

Can you provide more info about what you're doing? You're using a youtube playlist?

**Comment by bernhardriegler** [comment]
see also: https://github.com/videojs/videojs-youtube/issues/475
There are issues if the same youtube video is used more than once on the same page.
