### ISSUE TITLE
Volume Control not displaying on iphone iOS 10.2

### ISSUE THREAD

**Issue by lucascharrierpulpix** [videojs/video.js#4289]
The Volume Control is not displaying on my iPhone under iOS 10.2, and it always has the class "vjs-hidden". It seems it was disabled because iOS used to forbid to change volume programmatically, so, the decision was made to just hide the volume control.

I tried using the options for the volume, doing: 
```
videojs($el, {
...
                    controls: true,
                    controlBar: {
                        volumeMenuBar: true,
                        muteToggle: true,
                        volumeControl: true
                    }

                }
```

But it didn't change anything.

I'm using videojs with these plugins:
videojs-contrib-ads: 4.2.4
videojs-ima: 0.5.0
videojs-vast-vpaid: 1.0.0
videojs-contrib-hls: 5.4.1
videojs-contrib-quality-levels : 2.0.2

**Comment by gkatsev** [comment]
It's hidden by apply a class that hides it. You can either force it to be displayed via CSS, or you can do something like:
```js
var player = videojs('vid');
player.controlBar.volumeMenuButton.show();
```
which should re-show it.

Hope that helps.

**Comment by lucascharrierpulpix** [comment]
Yes it kinda fixes it, but if I change the source I have to call it again to display the volume button. Actually, I'd like to be able to set this in the options.
The problem is that Html5.canControlVolume is always False for iOS. Indeed it is not possible to control the volume, but it's possible to mute/unmute it. But in volume-menu-button.js it hides it because Html5.featureVolumeControl is false.

`
// hide mute toggle if the current tech doesn't support volume control
    function updateVisibility() {
      if (player.tech_ && player.tech_.featuresVolumeControl === false) {
        this.addClass('vjs-hidden');
      } else {
        this.removeClass('vjs-hidden');
      }
    }
`
