### ISSUE TITLE
keep control on the screen

### ISSUE THREAD

**Issue by angelochen960** [videojs/video.js#429]
Hi,

when player plays, control will be hidden, is there a way to keep it in the screen? Thanks

**Comment by HediMaiza** [comment]
Hello,

I tried this styles, but it's not working. Maybe too old.

**Comment by heff** [comment]
Yeah, that note is out of date. We changed the controls [to use CSS states](https://github.com/videojs/video.js/blob/master/src/css/video-js.less#L182). Try this.
```js
.vjs-default-skin.vjs-has-started.vjs-user-inactive.vjs-playing .vjs-control-bar {
  visibility: visible;
  opacity: 1;
}
```

**Comment by HediMaiza** [comment]
Very good for me. Thanks !

**Comment by artemshapovalov** [comment]
@angelochen960 You can also use 
`player = videojs('player', {
    inactivityTimeout: 0
});`
