### ISSUE TITLE
On Android KitKat (and below) Fullscreen not working

### ISSUE THREAD

**Issue by dreasn** [videojs/video.js#4290]
## Description
I tested it on KitKat (4.4.2), video js play normally but won't go full screen at all.  While on Lollipop (and above)  the full screen works just fine.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load the html file in WebView
2. Press the full screen toggle button

### Expected
Go full screen.

### Actual
Nothing happens.

### Error output
None.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.14.1
#### browsers
Android Webview Chrome
#### OSes
Android KitKat 4.4.2 and below.
### plugins
None.

**Comment by gkatsev** [comment]
I believe this is a webview limitation in kitkat and ealier. You potentially need to implement extra things yourself as mentioned here: https://developer.android.com/reference/android/webkit/WebView.html.
Some other related issues: https://github.com/videojs/video.js/issues/1995 and https://github.com/videojs/video.js/issues/2160
