### ISSUE TITLE
video/audio off sync in ad stitch live stream

### ISSUE THREAD

**Issue by lemonwhale** [videojs/video.js#4292]
## Description
When playing a server side ad stitched stream, the video/audio gets off sync after a ad break or two. The theory is that this might be caused by discontinuity. 

video url:
http://csm-e.cds1.yospace.com/csm/live/122906630.m3u8

## Steps to reproduce
1. Play the video url in videojs player in chrome.
2. Wait for at least one ad break
3. When the content starts again, check the sync between audio and video 

### Expected
the video/audio is synced

### Actual
the video/audio is not synced (roughly 2-3 seconds)

### Error output
No console error. 

## Additional Information
No additional information

#### videojs
    "video.js": "^5.19.0",
    "videojs-contrib-hls": "^5.3.3"
#### browsers
Chrome
#### OSes
Apple desktop
### plugins
No additional plugins

**Comment by gkatsev** [comment]
It's nicer to only open one issue and not cross post. Given that this is a contrib-hls issue, https://github.com/videojs/videojs-contrib-hls/issues/1090 is where the discussion should happen.

**Comment by lemonwhale** [comment]
Alright, sorry about that.
