### ISSUE TITLE
textTracks().on('change', handler) triggered for every caption

### ISSUE THREAD

**Issue by arski** [videojs/video.js#4294]
Hi, i dont know if this is intended behaviour but this seems wrong to me - the above event is triggered for every caption in the captions list when a caption is changed. E.g. I have 10 captions, i pick one, 10 events are triggered... This makes any kind of analytics tracking on my side very hard. Could you check if tjis is a bug or if there is a workaround? Thanks!

**Comment by gkatsev** [comment]
This is "as designed", though, I guess more like "as implemented". It's a lot easier to just listen to each track's mode change and then re-trigger it.
Also, when we enable one track via the UI, we potentially disable all the other tracks, though, we probably don't need to do that and make sure that we only change the mode on the previously enabled track.

We probably should have it rollup multiple change events into one but it's probably tricky to do right.

**Comment by arski** [comment]
> make sure that we only change the mode on the previously enabled track.

indeed that would make quite some sense if we sent 2 events, but not for those tracks that were already disabled..

oh well.. ill try to figure how to do this, but it sure is highly annoying to track and identify an actual change :(

**Comment by gkatsev** [comment]
This has been addressed.
