### ISSUE TITLE
different version of the code on npm?

### ISSUE THREAD

**Issue by coryc5** [videojs/video.js#4302]
It appears the code installed from npm is not current with what is hosted on github, at least some parts of it. Particularly, this line in the current code:
https://github.com/videojs/video.js/blob/master/src/js/player.js#L1608

is not found in the player.js file when you npm install video.js. Instead this version of the code from 5 months ago is:
https://github.com/videojs/video.js/commit/eb2093e16e1440fd7988bac11036083e83686df2#diff-3b0266ff1c037b289ec624ab25b0272eR1600

the videojs package.json file is version 5.19.2

**Comment by gkatsev** [comment]
Can you elaborate what you mean? The source code is in ES6 and compiled via babel before publishing to npm, so, it isn't directly the same thing.

**Comment by coryc5** [comment]
sorry yes, the player.js module's play function in the current source code returns a promise or undefined, but in the npm package, the player.js module's play function returns a reference to the Player object, which is an old implementation of that function. that is what I meant to establish with those links

**Comment by gkatsev** [comment]
Ah, it's a different version of videojs. Master currently has videojs 6.0. Soon, 6.0 will be made `latest` on npm. We're still going to be supporting the 5.x versions for a bit. You can see the code for the 5.x versions on the `5.x` branch on the repo.

**Comment by coryc5** [comment]
ah i see, thanks
