### ISSUE TITLE
Stream from OBS to Video.js via nginx rtmp does not show stream - Works in VLC

### ISSUE THREAD

**Issue by discord3463456473** [videojs/video.js#4303]
## Description
When streaming from OBS to Video.js via nginx-rtmp, installed following [this guide](https://obsproject.com/forum/resources/how-to-set-up-your-own-private-rtmp-server-using-nginx.50/), it does not show my stream in Video.Js (but it does show other streams).

If I load my nginx-rtmp/OBS steam with VLC, it works. 

Here is my HTML file:

`<!DOCTYPE html>`
`<html>`
`<head>`
`<title>RTMP Embed</title>`
`<link href="http://vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">`
`<script src="http://vjs.zencdn.net/4.11/video.js"></script>`
`</head>`
`<body>`
`<h1>RTMP Embed</h1>`
`<video id="streamContainer" class="video-js vjs-default-skin" controls preload="auto" width="640" height="320" data-setup='{}'>`
`<source src="rtmp://MY RTMP SERVER IP ADDRESS/live/&mp4:test" type='rtmp/fla'>`
`</video>`
`</body>`
`</html>`

## What I've tried
- The above source tag can be changed to this and it displays a stream:
`<source src="rtmp://54.255.176.172/trans/&mp4:nnstate_160p" type='rtmp/mp4'>` 

- If I open VLC : go to media - open network stream and put in this,  I get my stream.
`rtmp://MY RTMP SERVER IP ADDRESS/live/test`

The above html page does not show my stream.
I don't get any errors, just shows a black void.
I've tried with Chrome, Firefox & IE, Friend said he tried it with Edge with same results everywhere.

## General Questions  ( that could lead to an answer )
- How can I further investigate what the solution is?
- Does Video.Js support the "default" broadcasted stream type from OBS? (If not, where can I find more information on this?)
- From what I understand nginx just forwards whatever stream it receives. Could it be a setting in nginx? I get no error from OBS.

## Any thoughts?
Help is appreciated, Thank you ahead of time.

**Comment by SuiriuS** [comment]
Try

> data-setup='{ "techorder" : ["flash", "html5"]  }'

and

> type='rtmp/mp4'

with

> src="rtmp://SERVER.IP:port/live/test"

Are you using nginx as the webserver?

**Comment by discord3463456473** [comment]
OMG!! @SuiriuS THANK YOU!!

I'm not sure what is what, I changed those things because of recommended thoughts of others...
I changed them back and it worked!

**Comment by Simple78** [comment]
Hi, you can write the final version? 
I have the same problem. Sorry for my english, i am spanish.
Thank you

**Comment by SuiriuS** [comment]
```
<!DOCTYPE html>
<html>
<head>
<title>RTMP Embed</title>
<link href="https://vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
<script src="https://vjs.zencdn.net/4.11/video.js"></script>
</head>
<body>
<video id="streamContainer" class="video-js vjs-default-skin" controls preload="auto" width="640"
height="320" data-setup='{}'>
<source src="rtmp://SERVER.IP:1935/live/test" type='rtmp/mp4'>
</video>
</body>
</html>
```
This is the minimum you need to view an rtmp stream using html
` "techorder" : ["flash", "html5"]  ` in data-setup is a fix for some browsers 
OP had his source a bit weird
note that the javascript doesnt seem to work if the webpage is opened as a local file, but works when hosted on a webserver

**Comment by mister-ben** [comment]
4.11 is a very old version. Note if you're using Video.js 6, the flash tech isn't included by default, so you'd need to add that script too. See videojs/videojs-flash.
