### ISSUE TITLE
Video.js not raising error event on rtmp timeout

### ISSUE THREAD

**Issue by arshanawais** [videojs/video.js#4304]
I am using video.js v.5.19.2 to play an rtmp stream. I can successfully play the rtmp link when live video feed is available on that link. But if there is no video on rtmp link, video.js doesn't trigger error event so that I can display error that video feed is not available.

**Comment by gkatsev** [comment]
I'm not that familiar with how RTMP works but Video.js relies on the swf triggering an error, if the swf doesn't trigger an error for us, we can't trigger the error event on the player.
