### ISSUE TITLE
Spaces (+) in src URL do not work for RTMP

### ISSUE THREAD

**Issue by haietza** [videojs/video.js#4305]
## Description
Source URLs with spaces in the filename (substituted with a '+') do not work for RTMP (but they do work for HTTP).

## Steps to reproduce
1. Create audio snippet with RTMP source URL that uses a subdirectory with a '+' in the name
2. View webpage

The source URL works in the Wowza test RTMP Flash player, so the URL appears to work from the streaming server. It also works in the iOS direct link: http://streams-dev.appstate.edu/private/_definst_/mp3:meltonml/sub+sub/demo.mp3/playlist.m3u8

### Expected
Expect to see player work, as it does with HTTP.

### Actual
Get error. See example: http://www.appstate.edu/~meltonml/videojs-audio.html

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.12
#### browsers
Chrome
#### OSes
OSX

**Comment by mister-ben** [comment]
A literal space rather than `+` in the URL works with Flash. However your example uses `rtmp/mp3` as the type which isn't a type recognised by the Flash tech. I was able to play your stream by cangin the URL to use a space and changing the type to `rtmp/mp4`.

**Comment by haietza** [comment]
@mister-ben Thank you for the info - this is working for me now.
