### ISSUE TITLE
Whether there is a time period callback function

### ISSUE THREAD

**Issue by Shangxq** [videojs/video.js#4306]
Whether there is a time period callback function

**Comment by misteroneill** [comment]
Sorry, but it's hard to understand what you're asking.

JavaScript has a global `setTimeout` function that executes a callback after a specified amount of time and Video.js components have `setTimeout` methods that do the same, but are disposed when the component is disposed.

**Comment by gkatsev** [comment]
Also, depending on what you want, you could need to listen to the `timeupdate` event on the player.
