### ISSUE TITLE
How do I Move text track

### ISSUE THREAD

**Issue by GregXunKasaFrank** [videojs/video.js#4308]
## Description
Hi I am trying to move the text track and style it as well. I need to move it further up when our controls appear not the videojs control bar. But I can't seem to figure out how these are moved even by Video js. I see nothing about moving emulated tracks.

How do I move the track display up when the controls are visible and is that something I can manually do? 

Using Video JS version 5.17.0

**Comment by gkatsev** [comment]
This is how video.js moves our emulated text tracks: https://github.com/videojs/video.js/blob/master/src/css/components/_text-track.scss#L11-L14

We default to `bottom: 3em;`. We tried to also style the native controls with `::cue { bottom: 3em; }` but we did not have good success with that. Some browsers didn't apply it or others applied it but had interesting behavior such as removing and reapplying that property every second if video.

Hope that helps.

**Comment by GregXunKasaFrank** [comment]
Thanks
