### ISSUE TITLE
Not working on XHTML document (caused by &nbsp;)

### ISSUE THREAD

**Issue by dreasn** [videojs/video.js#4309]
## Description
Not working on xhtml document, caused by (at line 4644 on version 6.0.1)::
`el.innerHTML = '&nbsp;';`

I had to change it to:
`el.innerHTML = '\u00a0';`

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use it on xhtml
2.
3.

### Expected
fully working.

### Actual
video not playing. only sound. no controls.

### Error output
Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
6.0.1 and earlier.
what version of videojs does this occur with?
Opera, Chrome.
what browser are affected?
Windows, Android
what platforms (operating systems and devices) are affected?

**Comment by misteroneill** [comment]
The relevant source code is [here](https://github.com/videojs/video.js/blob/c9022795fdfcda166a79bef51dfeab29c1f7c191/src/js/control-bar/spacer-controls/custom-control-spacer.js#L37).

**Comment by gkatsev** [comment]
A PR to change the code that @misteroneill linked to sounds fine but we're unlikely to officially support XHTML.

**Comment by gkatsev** [comment]
Made this a first-timers only issue.

**Comment by thecotne** [comment]
@gkatsev i have sent pull request #4825

**Comment by gkatsev** [comment]
Thanks @thecotne, we'll take a look soon.
