### ISSUE TITLE
ClickableComponent enable and disable method register events multiple times

### ISSUE THREAD

**Issue by sagawater** [videojs/video.js#4312]
## Description
i'm adding plugins to VideoJS version 5.19.2 and I created some buttons that can be disabled/enabled. When we call the enable() method and the button is already enabled, it will register the click event a second time.
 
~~~~
class TestButton extends Button {
   constructor(player, options) {
        super(player, options);
        this.on(player, 'play', this.updateShowing);
    }
    buildCSSClass() {
        return `vjs-test-control ${super.buildCSSClass()}`;
    }
    handleClick(event) {
        //this will be called 1, 2, 4, 8, 16, 32, ... times
        this.player_.play();
    }
    updateShowing(event) {
        if (true) {
            this.enable();
        } else {
            this.disable();
        }
    }
}
~~~~
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Create a button and call enable() multiple times.
2. Click on that button.

## Results
handleClick() will be called more than once.
### Expected
handleClick() is called once. The enable() call should have no effect if it's already enabled. Same for disable().

**Comment by mister-ben** [comment]
Good point, I've created a quick PR for this.
