### ISSUE TITLE
VJS6 Outline on focused component

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#4313]
I am testing VJS6 and get an Outline on focused components:
e.g. Press Big Play, then Play Component shows outline.
e.g. Press Volume Component, and it shows outline.

Is this focused component Outline by design in VJS6? Obviously it's not there in VJS5, and I find it very unsightly.

Please advise.

**Comment by gkatsev** [comment]
Yes, this was [intentional](http://blog.videojs.com/Feature-Spotlight-Accessibility/#Outlines).

Having outlines is a huge improved for accessibility and is easy to turn off if you really want, though, I would urge you not to.

You can remove it by adding something like the following css:
```css
.vjs-control {
  outline: none
}
```
