### ISSUE TITLE
 Setting TextTrack to defaults not working when text track and video player are created dynamically.

### ISSUE THREAD

**Issue by Pinank08** [videojs/video.js#4315]
## Description
I wan't to create a dynamic video player i.e. video src and caption src comes from different file on click event.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. I have created a dynamic video player in videojs.
2. Than to add text track I have used addRemoteTextTrack() function.
3. But I am not able to make the track added as default as it always selects subtitle off as default.

Here is the code that I have used. 
```js
var oldTracks = player.remoteTextTracks();
  var i = oldTracks.length;
  while (i--) {
    player.removeRemoteTextTrack(oldTracks[i]);
  }

var trackk = new function() {
    this.kind = 'subtitles';
    this.label = 'english';
    this.language = 'en';
    this.id='track1';
    this.src = url+'.vtt';
    this.default= 'true'; // i have tried default too
}
    player.addRemoteTextTrack(trackk, true);

/*  I have used 
player.TextTrack = 'default';
player.TextTracks.mode='showing';
and many more... but subtitles are always off bydefault
*/ 
```

### Expected

I Expect to see subtitles when video is loaded.   

### Actual

When Video is loaded subtitles are off.

**Comment by jthomerson** [comment]
@Pinank08 please see my description in #4403. Are you using version 6.x? If so, please let us know because your problem is likely caused by #4403. Can you try the workarounds I show in that example to see if they fix your issue?

**Comment by gkatsev** [comment]
Closing as potentially fixed and due to lack of activity. If we get more information, we can re-open.

**Comment by partap** [comment]
I am having this problem with version 6.6.2.

Actually, I have the video and a default track loaded initially with HTML tags, and the track is selected by default...this works fine.  The page implements a very rudimentary subtitle editor...for now, any time a cue is edited, it deletes the entire TextTrack and reloads it using `Player.removeTrack()` and `Player.addRemoteTextTrack()`.  This is also working, except when the new track is loaded with `default: true` option set, it remains unselected in the player until I click it in the menu.  

The documentation is not clear as to how to activate a loaded TextTrack from Javascript, other than setting `default: true`

**Comment by partap** [comment]
I just spent a while stepping through with devtools... it looks like the property that is affected by selecting the text track from the menu is `mode`, which toggles between `'disabled'` and `'showing'` 

So, if I pass the option `mode: 'showing'` to `addRemoteTextTrack()`, it works.  The `mode` parameter in the documentation could use a little touch-up...  

...I'm actually seeing the `TextTrack.mode` constants specified at MDN, now that I know... but I didn't know the class wasn't part of videojs at the time, obviously...

**Comment by pegasus1982** [comment]
@partap Thanks man.
I followed your way, and finally I could resolve my issue.
But I still can't know why it happens when I use that option.
