### ISSUE TITLE
Version 6.0.1 not available on CDN

### ISSUE THREAD

**Issue by jorrit** [videojs/video.js#4317]
The URL https://vjs.zencdn.net/6.0.1/video.js does not exist. Are prereleases not available on CDN intentionally?

**Comment by gkatsev** [comment]
I was planning to put it up but forgot. Though, we've previously not been diligent on making pre-releases available on the CDN.
I'll get it up soon, in the meantime, you could try getting it from unpkg.com: https://unpkg.com/video.js@5.19.2/dist/video.js

**Comment by gkatsev** [comment]
It's published now.

**Comment by jorrit** [comment]
Thanks!
