### ISSUE TITLE
Casting to Chromecast and basic auth is not working

### ISSUE THREAD

**Issue by trollkarlen** [videojs/video.js#4323]
## Description
Briefly describe the issue.
Enable web UI with username and password, and then try to cast from the web player after login.
It fails.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Enable web UI
2. Set user and password
3. Open homepage and login
4. Play video and then cast it
5. It fails

### Expected
Same as without basic auth

### Error output
VIDEOJS: Session initialized: 8a8e4f94-ff55-43a4-ac0d-110d49e2a138 source : http://192.168.0.173:8080/vfs/.....mkv type : video/mp4
cast_sender.js:88 VIDEOJS: Cast Error: {"code":"session_error","description":"LOAD_FAILED","details":{"type":"LOAD_FAILED"}}

## Additional Information
Chrome 
It works if i turn off basic auth

It can be due to the Headers "Access-Control-Allow-Origin:*" and more from here:
https://www.wowza.com/docs/how-to-stream-from-an-android-device-to-the-google-chromecast-device

/T

**Comment by Tha-Robert** [comment]
My bad i did not see it was a plugin to this project.
Can be closed for now.

/T

**Comment by trollkarlen** [comment]
My bad i did not see it was a plugin to this project.
Can be closed for now.

/T
