### ISSUE TITLE
QUESTION [Solved]: this used to work to set inline "Default Volume"

### ISSUE THREAD

**Issue by tweed** [videojs/video.js#4324]
Using version 6 which is so great!

I need a replacement for this - it stopped working with version 6 i believe.

`  <script>
  videojs(document.getElementById('myvid'), {}, function() {
  this.volume(0.18);
});
    </script>`

**Comment by mister-ben** [comment]
[Works here](http://jsbin.com/lotolufaho/edit?html,output). Could you use the issue template and include a reduced test case to help replicate what you're seeing?

**Comment by tweed** [comment]
SUPER-NICE   SUPER-HELPFUL   Thanks to your confirmation I'll be able to sort it now with no concern on spinning my wheels. It'll be something simple and obvious i've missed. great to know it works still.

I have a question about setting a 'lower' default volume in the 'data-setup' part of inline code.
in the script example you showed as working via link above there's this:
// Use this OR `data-setup='{}'` to initialize player

Not a problem if I never find out as I'm happy with the way it works with the script- YET, i wonder if it's now possible to set a default volume in the 'data-setup' options.

maybe I'll find it in some doc though I've tried and will try again i expect. I will post back here if i find out how to set default volume with 'data-setup' option


THANK YOU

**Comment by mister-ben** [comment]
Sorry, the "use this or data-setup" comment is just from my template and is confusing in that example. It's meant to mean don't use options there or in data setup, but no options are used in this case. Setting volume as the example is the way to go.
