### ISSUE TITLE
Question and error

### ISSUE THREAD

**Issue by androids7** [videojs/video.js#4327]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

i want to make a project use videojs to play rtmp stream video,put show me the message is no compation found the media,how to usr videojs to play rtmp stream.best to write a example use the address rtmp://cyberplayerplay.kaywang.cn/cyberplayer/demo-L1

thanks you

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs 5.19
what version of videojs does this occur with?
#### browsers
uc browser
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
android 6.0
### plugins
are any videojs plugins being used on the page? If so, please list them below.
rtmp

**Comment by mister-ben** [comment]
You list Android under OSes. RTMP can only be played with Flash, which Android does not support.

**Comment by gkatsev** [comment]
As @mister-ben said, you can't play RTMP on Android devices.
Also, the RTMP url you used isn't formatted correctly for Video.js. Video.js expects the stream and connection portions to be separated by `&` as outlined in our [FAQ](https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-play-rtmp-video-in-videojs).

Hope that helps.
