### ISSUE TITLE
Keep the current volume level

### ISSUE THREAD

**Issue by peter-gribanov** [videojs/video.js#4328]
## Description

It would be better keep current volume level.

## Steps to reproduce
1. Open sum video
2. Change volume level
3. Open other video

### Expected
Keep the volume level since the last modification

### Actual
Volume level is 100%

## Additional Information

Example solution for me:

```js
var player = videojs('video-player', {}, function() {
    var volume = $.cookie('_player_volume');
    if (typeof volume != 'undefined') {
        this.volume(volume / 100);
    }
});

player.on('volumechange', function () {
    // save current volume in cookie
    var el = $(this.controlBar.volumeMenuButton.volumeBar.volumeLevel.el());
    var level = (el.width() / el.offsetParent().width()) * 100;
    $.cookie('_player_volume', level);
});
```

**Comment by hartman** [comment]
cookie's should be avoided for these kinds of things. localstorage is better. There is a plugin available on https://github.com/theonion/videojs-persistvolume that does this, but it probably should be cleaned up a bit. 

Ideally, i think you'd want a more generalized concept of storing data for any type of plugin. It was on my personal todo list a while back, but never got around to it.

**Comment by peter-gribanov** [comment]
@hartman this plugin is not work now :confused:

**Comment by gkatsev** [comment]
There's apparently a PR that fixes the plugin: https://github.com/theonion/videojs-persistvolume/pull/17. Looks like there's a fork that has the fixes: https://github.com/jbboehr/videojs-persistvolume (that fork is also what's available on npm).

Unfortunately, I don't think we're doing to be adding this back into core. We used to have this feature but it was removed a while ago.
