### ISSUE TITLE
TypeScript Version ??

### ISSUE THREAD

**Issue by aljibbs** [videojs/video.js#4332]
This is an amazing library to use. Great work. Will there ever be a .ts version ?

**Comment by gkatsev** [comment]
Thanks. Unfortunately, we don't currently have any plans to provide official .ts versions.

**Comment by citosid** [comment]
The [plnkr that you can find online](http://embed.plnkr.co/DrXJoH02IJLEdkYFu8HE/) after a 5 seconds search on Google (@Kogoruhn) does not work anymore. 

Do you have any example on how to do it @ypavlotsky ?

I have this code:

```typescript
import videojs from 'video.js';
import { AfterViewInit, Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-player-component',
  templateUrl: 'component.html',
  styleUrls: [
    'component.scss',
  ],
})
export class PlayerComponent implements OnInit, AfterViewInit {
  public idPlayer;
  public url = '//vjs.zencdn.net/v/oceans.mp4';
  public type = 'video/mp4';
  private video;
  public ngOnInit() {
    this.idPlayer = Math.ceil(Math.random() * 1000);
  }

  ngAfterViewInit() {
    const elementId = `video_${this.idPlayer}`;
    this.video = videojs(elementId);
  }
}
```

With this template:

```
<video id="video_{{idPlayer}}" class="video-js vjs-default-skin vjs-big-play-centered vjs-16-9" controls preload="auto">
  <source [src]="url" [type]="type">
</video>
```

And it creates the player, but the styles are all wrong:

![screenshot 2018-07-03 16 59 42](https://user-images.githubusercontent.com/201430/42244298-803d4e80-7ee2-11e8-9b28-8e9ea0b4837e.png)

Any suggestion?

**Comment by citosid** [comment]
I found the answer to my question:

Since Angular 2+ uses `ViewEncapsulation` by adding a `_ng-content-c*` attribute to each element under a component and adding the same attribute to the styles, you need to disable this feature to integrate third party libraries such as VideoJS.

Your component definition should be something like this:

```typescript
@Component({
  selector: 'app-player',
  templateUrl: 'component.html',
  styleUrls: [
    'component.scss',
    '../../../node_modules/video.js/src/css/video-js.scss',
  ],
  encapsulation: ViewEncapsulation.None, // This plus the sytleUrl are the important parts
})
export class PlayerComponent implements OnInit, AfterViewInit {
}
```

**Comment by acharyaks90** [comment]
@citosid  can you please guide me i am trying to register for Plugin using typescript class
it give me the erro No overload matches this call.


Code : 
MyPlugin.ts 
import videojs from 'video.js'

const Plugin = videojs.getPlugin('plugin');
interface Myplugin  {
 options :any 
}

 class Myplugin extends Plugin  {

    constructor(player, options) {
        super(player);
    
        if (options.customClass) {
          player.addClass(options.customClass);
        }
    
        player.on('playing', function() {
          videojs.log('my plugin works playback began!');
        });
      }
}

 videojs.registerPlugin('Myplugin', Myplugin);

But Its gives me the error 

No overload matches this call.
  Overload 1 of 2, '(name: string, plugin: (this: VideoJsPlayer, ...options: unknown[]) => unknown): (...options: unknown[]) => unknown', gave the following error.
    Argument of type 'typeof Myplugin' is not assignable to parameter of type '(this: VideoJsPlayer, ...options: unknown[]) => unknown'.
      Type 'typeof Myplugin' provides no match for the signature '(this: VideoJsPlayer, ...options: unknown[]): unknown'.
  Overload 2 of 2, '(name: string, plugin: { new (player: VideoJsPlayer): Plugin; prototype: Plugin; BASE_PLUGIN_NAME:

**Comment by citosid** [comment]
I'm sorry @acharyaks90 , have not been able to look into this. @jienco do you have any suggestion?

**Comment by gkatsev** [comment]
Hey, the person currently maintaing the Definitely Typed definitions for Video.js wrote up this post https://joeflateau.net/posts/video-js-heart-typescript, hopefully, it's helpful.

**Comment by jienco** [comment]
Hi, for the plugin writing in TypeScript @acharyaks90 you will need to install the types package in your package.json devDependencies:

```json
"@types/video.js": "7.3.5",
```

Then in your TypeScript code:

```javascript
import videojs from 'video.js';

const Plugin = videojs.getPlugin('plugin');

export class MyPlugin extends Plugin {
  constructor(player, options) {
    // @ts-ignore
    super(player, options);
  }
}

videojs.registerPlugin('myPlugin', MyPlugin);
```

To make it work I had to add ts-ignore to the call to super since the typing only accepted one argument.

**Comment by acharyaks90** [comment]
thanks for Update I have done with typescript integration in angular
