### ISSUE TITLE
Forcing flash tech is not working in Chrome

### ISSUE THREAD

**Issue by JSoon** [videojs/video.js#4333]
Hello, I start to working with video.js today and i just made some tests. And, there comes an issue :)

Browser: Chrome 58.0.3029.96 (64-bit)
IE: 8.0.6001.18702
Videojs: 5.19.2

---
### Situation:
With the option below, everything seems nice:（Chrome will use html5 to play mp4, while IE will use flash fallback）
```js
techOrder: ['html5', 'flash'],
sources: [{
  src: './v/oceans.mp4',
  type: 'video/mp4'
}],
flash: {
  swf: '/nm/video.js/dist/video-js.swf'
}
```
but when it's becoming this: (which i'd like to force using the flash tech)
```js
techOrder: ['flash'],
sources: [{
  src: './v/oceans.mp4',
  type: 'video/mp4'
}],
flash: {
  swf: '/nm/video.js/dist/video-js.swf'
}
```
Then here comes an error saying in Chrome:
> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.
MediaError {code: 4, message: "No compatible source was found for this media."}

---
### Question:
***My plan is just to force using flash to play my mp4 file in any browsers.*** Hope my description before is clear enough, any help? Thanks :)

**Comment by JSoon** [comment]
I just worked it out, the reason is Chrome, that the flash is set to ask status, but it is blocked in fact. Then i just switched the status from ask to allow, and back from allow to ask, jesus, it worked like magic. Still wonder why this happened, just note to someone else who meet with the same situation.

**Comment by gkatsev** [comment]
I wonder if making that options change put the swf into chrome's "known list" or something like that.
also, make sure that your video is relatively large in size because chrome will block flash in those cases as well.
