### ISSUE TITLE
Not able to compile and make it up

### ISSUE THREAD

**Issue by Gunachandra** [videojs/video.js#4337]
Hi All,

I am trying to use video.js and i followed the steps given in http://videojs.com/getting-started/#customize.
I have done till "$ npm install", when i go to next step i.e "$ grunt dev". I am getting below error:

>>D:\videoplayer\video.js>grunt dev --force
Loading "Gruntfile.js" tasks...ERROR
TypeError: Map#toJSON isn't generic
Warning: Task "dev" not found. Used --force, continuing.
Done, but with warnings.

Can anyone help me in resolving this issue. Thanks in advance.

**Comment by Gunachandra** [comment]
@gkatsev can you please help me in resolving the issue.

**Comment by gkatsev** [comment]
What version of node/npm are you using? Did you run `npm install` inside of the video.js directory?
We use this everyday and it works.
