### ISSUE TITLE
How to play YouTube videos using their URL?

### ISSUE THREAD

**Issue by ShahzaibChadhar** [videojs/video.js#4341]
i want to play YouTube videos using the their URL How i can do i tried but not able to do this.Can you help me?

**Comment by gkatsev** [comment]
You need to use the [videojs-youtube](https://github.com/videojs/videojs-youtube) tech to be able to play back youtube videojs. But once you load it in, just add a new source with type `video/youtube` and the youtube url as the src.

Hope that helps.
