### ISSUE TITLE
Feature Proposal: loadMedia, getMedia

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#4342]
More and more, when videojs is used, more than just a source is needed. There's the poster image, there's captions, and there's also various properties like muted, and loop, and autoplay.
Loading all these things are often implemented in places like [videojs-playlist](https://github.com/brightcove/videojs-playlist/blob/master/src/js/play-item.js#L36-L49) and Google has a new [Media Session API](https://github.com/videojs/videojs-media-session) that expects similar items.
This method would accept an object that has all these properties and when called, it'll make sure to unset all the old things. That means that all old posters, all old text tracks would be removed and unset and then the new things would be set. This would be different than something like `src` which wouldn't necessarily remove old textTracks or posters.

@imbcmdth I wonder if we'd want to revert the change to the addRemoteTextTrack flag for remove on src change in this case? Or maybe, just keep the default the same?

Also, we're thinking of having it be native in 6.x and be a simpler plugin 5.x that doesn't have as deep of integration with the rest of the player (like removing old text tracks).

**Comment by heff** [comment]
This sounds cool to me. A single API for loading a "video" would be pretty convenient. Wrapping in controls like muted and loop feels a little odd to me, but I haven't read the spec and what they're trying to accomplish.

You might consider how this would overlap with the [video object schema](http://schema.org/VideoObject). If only for terminology of the properties.
https://developers.google.com/webmasters/videosearch/schema

**Comment by gkatsev** [comment]
Yeah, not sure whether we want to have those other properties or not yet, just threw it out there.
That VideoObject schema sounds interesting.
