### ISSUE TITLE
Updating options dynamically?

### ISSUE THREAD

**Issue by ErraticFox** [videojs/video.js#4343]
Hello, I'm wanting to update my options dynamically and use videojs offset plugin. 

My initializing code is 

```js
var options = {
    controls: 'true',
    preload: 'metadata'
}

var player = videojs('player', options)
```

But how could I update the options dynamically so I could add the videojs offset plugin options?

**Comment by gkatsev** [comment]
A lot of these options are available as setters on the player: [`player.preload()`](http://docs.videojs.com/Player.html#preload), [`player.controls()`](http://docs.videojs.com/Player.html#controls).
As for plugins, it would depend on the plugin. Some are ok with being called multiple times, for others, you'd want to consult their documentation on how to interact with them.

Hope that helps. Thanks.

**Comment by subarudad** [comment]
To set the volume bar to vertical, you can initialize like this:
var options = {
    controlBar: {
        volumePanel: {inline: false}
    },
};

Is there an available setter for dynamically changing the volume control to vertical?
