### ISSUE TITLE
videojs HTML5 Player

### ISSUE THREAD

**Issue by bhartendukumar12** [videojs/video.js#4349]
## Description
I m new to this area please help me out.
I m able to play the video by videojs player in web browser but not in android and ios devices.
I m providing the video as a source from s3 bucket.

when i open it in the mobile browser the video keeps buffering it does not play the video.

plugins i used
```
  <link href="videojs/videojs-panorama.min.css" rel="stylesheet">
      <script src="videojs/videojs-panorama.v5.min.js"></script>
```
this is the video tag i m using
```
 <video id="videojs-panorama-player" class="video-js vjs-default-skin"  crossorigin="anonymous" controls preload="none">
           <source src="https://s3.ap-south-1.amazonaws.com/viyatrademo/anthem+plus+head+toss.mp4" type='video/mp4'>		
          </video>
```
how do i make it possible to play in the mobile browser.
please provide the code for this

**Comment by mister-ben** [comment]
You'll probably just need a lower bitrate video. 25mbps is very high and would need a consistently high download rate.
