### ISSUE TITLE
'muted' option does not mute the player except in one specific case

### ISSUE THREAD

**Issue by alex-barstow** [videojs/video.js#4351]
## Description
Providing the `"muted": true` option does add the `muted` attribute to the `<video>` element, but does not actually mute content audio unless all of the following conditions are true:
- the option is passed into the `videojs()` function rather than the `data-setup` attribute
- the video.js CDN link is included in the `head` of the document instead of the `body`
- the player is loaded in Chrome

In all other cases, the player is not muted despite the presence of the `muted` attribute because the value of the `<video>` element `muted` property is `false`.

#### Test pages
Option provided via `data-setup`:
- [CDN link in head](http://jsbin.com/fukatapela/1/edit?html,output)
- [CDN link in body](http://jsbin.com/jifedupoho/1/edit?html,output)

Option provided via `videojs()` function:
- [CDN link in head](http://jsbin.com/xodesehuwa/1/edit?html,output)
- [CDN link in body](http://jsbin.com/sonadevuco/1/edit?html,output)

## Steps to reproduce
1. Open above test links in Chrome, Firefox, and Safari.
2. Begin playback and inspect `<video>` element

### Expected
- `muted` attribute is present on the `<video>` element
- `MuteToggle` button is in it's muted state
- audio should be muted

### Actual
- (pass) `muted` attribute **is** present on the `<video>` element in all cases
- (fail) `MuteToggle` button is **not** in it's muted state and content audio is **not** muted, except for the 3rd test link in Chrome

## Additional Information
I have not tested this behavior with video.js installed via `npm`
#### videojs
5.19.2
#### OSes
Tested on MacOS Sierra v.10.12.3

**Comment by KevinBrogan** [comment]
I can confirm this.

```
player = videojs('videoPlayer',
{
	muted: false
})
```

does not work except on chrome, ie10 and ie11, if the video tag has the muted attribute.

A workaround is to do this

```
player = videojs('videoPlayer',
{
	muted: muteState
},
function()
{
	// regarding 'muted: muteState,' in the above setup,
	// muted is not being set properly by videojs on firefox edge or safari. set it here.
	player.el_.children[0].muted = muteState;
});
```

**Comment by gkatsev** [comment]
Working on it! See #4562.
