### ISSUE TITLE
Can't start playing video on opera mini iphone 5s

### ISSUE THREAD

**Issue by crmsoft** [videojs/video.js#4360]
## Description
Latest Opera mini browser running on iphone 5s with ios 10.3.1. First play on video js player, touch on big play button not play's the video.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. install latest opera mini from app store
2.go to [videojs.com](http://videojs.com)
3.try to play video

## Results
It seems like to hover the button.

**Comment by leoafarias** [comment]
@crmsoft  Just tried to play a video on Opera Mini on similar version device and was able to play fine. Can you try to play the following link?
http://videojs.com/advanced/

**Comment by gkatsev** [comment]
Browsers on iOS are basically just safari, so, it should work. Also, thanks for checking @leoafarias.
