### ISSUE TITLE
private loading or namspaced videojs

### ISSUE THREAD

**Issue by denisvlr** [videojs/video.js#4361]
For compatibility reasons, we need to have several versions of videojs on the same page, including plugins such as ads and hls.

By default, videojs creates a global object window.videojs. It's possible to load it as an AMD module, but as far as I know it breaks the plugins.

Is it possible to achieve this using modules?
Otherwise, is it possible to load videojs and its plugins under a different namespace?

**Comment by gkatsev** [comment]
We have a `noConflict` method in work and you could probably do a similar thing yourself: https://github.com/videojs/video.js/pull/4671
Basically, load in videojs, store that reference in a variable, then load in another version of Video.js. Unfortunately, most plugins when loading as globals, expect `window.videojs` to be their version of video.js, so, you might need to juggle versions a bit.

**Comment by gkatsev** [comment]
Hope that helps.
