### ISSUE TITLE
HLS Video wrong playing in Safari mobile

### ISSUE THREAD

**Issue by PavloKhilko** [videojs/video.js#4362]
## Description
While playing a HLS video in Safari browser, and move in the same tab to another site, continue to load TS files pre-open site.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open the Web page on which the player playing video (videojs player)(local sandbox)
2. Using a utility like watching mitmproxy loaded .m3u8 and .ts files during playback
3. Staying on this tab in Safari browser turn on any other web site
4. In program mitmproxy, when loading a new page, watching downloading video content from the previous site.

### Expected
The transition to a new website, download the content from the previous need to stop.

### Actual
When moving to another web page in the browser safari, staying in one tab from a previous video site continues to downloading

#### videojs
videojs - 5.12.6
VideoJS Contrib HLS:3.3.0
#### browsers
Safari mobile
#### OSes
iOS
### plugins
Youbora plugin:5.3.5

**Comment by mister-ben** [comment]
Playing audio in the background is a feature of iOS Safari. You could pause the video when the page becomes hidden, for example:

    document.addEventListener('visibilitychange', function() {
      if(document.hidden) {
        player.pause();
      }
    });
