### ISSUE TITLE
Muted button disappear in iphone(ios 10.3)

### ISSUE THREAD

**Issue by kayakyelf** [videojs/video.js#4373]
## Description
I added videojs in my project and testing it  on my iphone.  

## Steps to reproduce
1. I set the player muted so that it can autoplay. 
2.But cannot find the mute button and volume button to control the audio.

### Expected
have the mute button to control muted or not

### Actual
No mute button and cannot control the volume

#### videojs
video-js-5.20.1
#### browsers
safari
#### OSes
ios 10.3

Could anyone help to solve this?

**Comment by arashilan** [comment]
Me too. Set autoplay on iOS
When set "autoplay muted" in `<video>` ,then the video can autoplay.
When set "autoplay" `<video>` ,then video can't autoplay.

**Comment by misteroneill** [comment]
@arashilan That is a limitation of Safari, not something Video.js can control.

**Comment by misteroneill** [comment]
This looks like a duplicate of #4478

**Comment by couchcrew-thomas** [comment]
The current iOS Safari supports JS control of the muted behaviour. So this is indeed a bug.

**Comment by gkatsev** [comment]
Duplicate of #4478

**Comment by moti5565** [comment]
#4478

**Comment by gkatsev** [comment]
This should be fixed in master now, a release of 7 is coming soon and it'll be back ported to 6.x at some point as well.
