### ISSUE TITLE
Please make aria lable and region role configurable

### ISSUE THREAD

**Issue by taoning2014** [videojs/video.js#4376]
## Description
In [videojs source code](https://github.com/videojs/video.js/blob/master/src/js/player.js#L415), it sets a `role` and `aria-label` for the container of `video` tag. It will be great if you could make these attributes configurable. So user can pass in an option to let videojs NOT adding these a11y attribute.

The reason we want this feature is that we implemented a11y by adding some wrappers to `video` tag, these aria label are duplicate and hard to remove on client side.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue. Setup videojs in any of [three ways](https://github.com/videojs/video.js/blob/master/docs/guides/setup.md) can reproduce it. Or:

1. Clone videojs source code, run a local server on the cloned folder.
2. Visit http://localhost:8080/sandbox/combined-tracks.html
3. Open Chrome inspector, check that the `video` container has `role=region` and `aria-label="Video player"`

### Expected
User could pass in an option to disable adding the aria labels.

### Actual
Aria labels are always added.

### Error output
None.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with? 6.0.0-RC.6.
#### browsers
what browser are affected? Chrome.
#### OSes
what platforms (operating systems and devices) are affected? Mac OS 10.12.5.
### plugins
are any videojs plugins being used on the page? If so, please list them below. None.

**Comment by gkatsev** [comment]
I think the workaround provided by @OwenEdwards is sufficient.
