### ISSUE TITLE
Iphone6's Safari browser in video.js has two control columns. How do you get rid of the default control bar?

### ISSUE THREAD

**Issue by fanerge** [videojs/video.js#4384]
video.js中iphone6的safari浏览器有两个控制栏，怎么去掉它默认的控制栏？
Iphone6's Safari browser in video.js has two control columns. How do you get rid of the default control bar?

**Comment by coolrex** [comment]
你可以通过样式控制
video::-webkit-media-controls-panel-container {
  display: none !important;
}
