### ISSUE TITLE
No error when dash stream fails

### ISSUE THREAD

**Issue by scosden** [videojs/video.js#4385]
Issue: videojs not raising error when dash stream can't be played

Steps to reproduce:
- videojs version: 5.19.2
- use HTTP proxy like Charles and blacklist/block the video server domain
- play a live or vod DASH stream from that video server

Expected behavior:
- videojs eventually gives up on playback and throws an error event for the application

Actual behavior:
- videojs does give up on playback (no HTTP requests going out) but does not notify the application

**Comment by squarebracket** [comment]
Closed by videojs/videojs-contrib-dash#224 and published in v2.9.3 of that package. You can go ahead and close this now.

**Comment by gkatsev** [comment]
Thanks @squarebracket!
