### ISSUE TITLE
Can't update an existing component's text (playback-rate-menu)

### ISSUE THREAD

**Issue by creeptonik** [videojs/video.js#4386]
I'm trying to change the text showing in the playback rate menu from [VALUE]x to Speed([VALUE[x]) but I can't get a way to do this <reference to https://github.com/videojs/video.js/blob/master/src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js>. 

I'm getting and setting the component's label this way:
`player.getChild('controlBar').getChild('playbackRateMenuButton').labelEl_('Speed (1x)');` but it's not working. I also would like to update the text each time a speed rate is selected (instead of overriding with the default `this.player().playbackRate() + 'x'`, what's the best way to approach this please?

Any recommendations on how to do this differently and make sure I can add text to the standard 1/1.5/2x is greatly appreciated (see screenshot for more info)
![playback-rate-issue](https://cloud.githubusercontent.com/assets/10048338/26640896/f86980a0-4620-11e7-8d9d-34f2a265cb84.png)

**Comment by gkatsev** [comment]
`labelEl_` is a reference to the DOM element itself, so, you could just change it via standard DOM API.
You can listen to the `ratechange` event to know when things have changed and then set the textContent on the labelEl_ based on the playback rate.

The other option is to extend the playback rate menu and make the changes so `speed` is a default thing.

Hope that helps.

**Comment by creeptonik** [comment]
That's what I did in the end, thanks:
```
player.on('ratechange', function(e){
 var currentRate = playbackComponent.innerText;
  if(currentRate == '1x'){ currentRate = 'Normal'; }
  playbackComponent.innerText = 'Speed (' + currentRate + ')';
});
```
