### ISSUE TITLE
vjs-fluid not working in angular 2 material grid list context

### ISSUE THREAD

**Issue by sohil-kshirsagar** [videojs/video.js#4387]
## Description
Please see: https://plnkr.co/edit/6bxZt3hX28m4gdOvIM0U - I have a video in a tile of md-grid-list. The video doesnt render (only audio plays) when 'vjs-fluid' is used but it works fine without vjs-fluid.

The same video tag works fine outside md-grid-list context with vjs-fluid.

## Steps to reproduce
View plunker at https://plnkr.co/edit/6bxZt3hX28m4gdOvIM0U

### Expected
Video resizes properly.

### Actual
Video does not show up - only audio.

**Comment by gkatsev** [comment]
Unfortunately, seems like the example is broken and I'm unfamiliar with Angular to be able to debug it. Would you be able to fix up the example so we can see what's happening? Thanks.
