### ISSUE TITLE
set time by currentTime does not work

### ISSUE THREAD

**Issue by WaldenH** [videojs/video.js#4389]
Two cases when using currentTime to set time, 
if in pause state, video will jump to target time, but when press to play, video will begin from beginning;
if in playing state, video will jump to target time, but immediately video will play jump to begin to play.

Version 5.20.1
relevant code:

```

import React          from 'react'                  ;
import { autobind }   from 'core-decorators'        ;
import videojs        from 'video.js';

@autobind
export default class VideoBox extends React.Component {
  constructor(){
    super();
    this.state = {
      myPlayer    : '',
      videoUrl    : 'http://hk-hkbn7.acgvideo.com/vg8/a/a9/7757534-1.mp4?expires=1496239800&platform=pc&ssig=Rz1vwjo_uSXjVZXLxYHlWw&oi=3732844561&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2065532129',
    };
  };

  componentDidMount() {
    this.state.myPlayer = videojs( 'test_video_1', {}, function () {});
  }

  setAndPlay(){
    this.state.myPlayer.currentTime('9');
  }

  render(){
    return(
      <div>
        <video  id = 'test_video_1'
          className='video-js vjs-default-skin'
          controls
          preload='auto'
          width='640'>
          <source src = {this.state.videoUrl} type='video/flv' />
        </video><br/>
          <button onClick={this.setAndPlay}>
            Set and play
          </button>
      </div>
    );
  }
}

```

**Comment by mister-ben** [comment]
It sounds like your server isn't responding correctly to range headers, and is giving the start each time instead of the range requested.

https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#problems-when-hosting-media

**Comment by gkatsev** [comment]
I wou make adjustments based on what @mister-ben mentioned (and check the troubleshooting doc). If it's still an issue, please create a reduced test case for us to take a look at.
