### ISSUE TITLE
Cannot navigate in progress bar when the video is opened for the first time.

### ISSUE THREAD

**Issue by FestinaI** [videojs/video.js#4390]
## Description
I want to use video.js to play videos on my website which are hosted on Azure, but when I try to navigate to a specific time frame from the progress bar, the video starts playing from the beginning again. 

## Steps to reproduce
1. Load a video from the server
2. Play the video
3. Try to navigate to a specific time frame on the progress bar 

## Results
The progress indicator on the progress bar moves back to the beginning of the video and the video starts from the beginning.

### Expected
The video should begin to play from the position I chose on the progress bar.

### Actual
From my testing, I have noticed that the only time I get the expected result is if I let the majority of the video load (>70%), then close the video player and open it again. Any other test case fails, even if I let the video load and try to navigate to different times on the progress bar while the video player is still open.

### versions 
Latest version (I forked the project last week)
#### browsers
Tested on Chrome

**Comment by omeryounus** [comment]
I have faced similar problem but on Firefox browser. In my case, player stuck loading the video and If I try couple of time to on progress bar to move forward it then throws error "media playback unsupported" It only happens to MP4 videos on Firefox browser only.

Can anyone help me on this issue?

**Comment by mister-ben** [comment]
For these types of issues make sure the file is appropriate for streaming with its metadata at the start, and that the server is correctly handling byte range requests.

https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#problems-with-playback

**Comment by gkatsev** [comment]
I would read the troubleshooting guide and make adjustments based on what @mister-ben mentioned. If it's still an issue, please create a reduced test case for us to take a look at.
