### ISSUE TITLE
Google IMA sdk throw erorr when vast document return no ads on Mobile Devices

### ISSUE THREAD

**Issue by omeryounus** [videojs/video.js#4393]
## Description
Briefly describe the issue.
Google imaSDK ima3.js throw exceptions when there is no ads return from the vast xml. 

## Steps to reproduce

1. Set the ima-container on the videojs player
2. Let the vast xml return no ads or empty vast xml document

var videoPlayer = videojs("video");
videoPlayer.ima({
    id: "video",
    adTagUrl: "https://pubads.g.doubleclick.net/gampad/ads?"ADS_URL"
});
videoPlayer.ima.initializeAdDisplayContainer();
videoPlayer.ima.requestAds();

videoPlayer.one("click", function() {
    videoPlayer.play();
});

### Expected
It should be able to click on the video to play it on the mobile devices browsers. On desktop it works fine.
### Actual
Please describe what actually happened.
It throws error and you cannot able to play the video 
### Error output
Uncaught TypeError: Cannot read property 'apply' of undefined
    at Jq (ima3.js:303)
    at Hq.K (ima3.js:304)
    at Zg (ima3.js:82)
    at tq.h.dispatchEvent (ima3.js:80)
    at tq.w (ima3.js:294)
    at Wg (ima3.js:77)
    at Sg (ima3.js:78)
    at ima3.js:76

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
videojs version = 5.19.2

#### browsers
what browser are affected?
Chrome, safari on Mobile devices
#### OSes
what platforms (operating systems and devices) are affected?
IOS, Android
### plugins
are any videojs plugins being used on the page? If so, please list them below.
Google IMASDK platform 
ima3.js

**Comment by mister-ben** [comment]
Can you open this against the IMA plugin instead? Thanks

https://github.com/googleads/videojs-ima/issues
