### ISSUE TITLE
What is the default buffer for 'videojs' to play the rtmp stream? Can i change the size of this value?

### ISSUE THREAD

**Issue by eguid** [videojs/video.js#4399]
I found that I used Videojs to play live video of the delay is very large, more than three seconds; so I just want to ask, what is the default buffer for Videojs to play the rtmp stream? Can i change the size of this value?

**Comment by gkatsev** [comment]
The current bufferTime setting is `1`. There's no way to change this setting other than recompiling the swf. There are a few PRs for it on the videojs-swf project: https://github.com/videojs/video-js-swf/pull/207

Hope that helps.
