### ISSUE TITLE
How can I hide videojs error message?

### ISSUE THREAD

**Issue by maroontr** [videojs/video.js#4401]
I want to hide player error message, how can i do this, please help me?

**Comment by gkatsev** [comment]
Depending on what you want to do, you can call `player.error()` with `null` to tell Video.js to hide the error: `player.error(null)`.
If you want to just disable errors, you can set `errorDisplay` option to be false in the player options:
```js
var player = videojs('vid', {
  errorDisplay: false
});
```

Hope that helps.
