### ISSUE TITLE
VideoJS, CSS Modules and ReactJS

### ISSUE THREAD

**Issue by albertoarana** [videojs/video.js#4402]
Hello, 

I would like know as I can integrate VideoJS in ReactJS with CSS Modules activated, because when I import the css to file the classes are ignored.

`import 'video.js/dist/video-js.css'`

render method:

`<div data-vjs-player>
        <video ref={ node => this.videoNode = node } className="video-js" />
      </div>`

**Comment by gkatsev** [comment]
You want to have the `className='video-js'` on the vjs-player div, could this be is the issue? Otherwise, I'm not sure that our css works with css modules.

Hope that helps.
