### ISSUE TITLE
Google Ads are not played on Android Devices in a Webpage

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/video.js#4406]
Hello,
I'm using Google ads and it works fine on PCs.
However on mobile (web), I get this error:
> videojs.min.js:12 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

```
<script type="text/javascript">
                    var player = videojs('videojs');
                    var options = {
                        id: 'videojs',
                        adTagUrl: '@Html.Raw(adTemp.Id)'
                    };
                    player.ima(options);
                    player.ima.requestAds();
                    player.play();
</script>
```

Thank you.

**Comment by gkatsev** [comment]
Are you able to play back the content video on Android? Can you provide a reduced test case?
In a lot of these cases it means that either the ad or the content video formats are not supported on Android but are supported on your PC. We have a [troubleshooting doc](https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#choosing-a-video-format) you can check out.

If swapping out the video for videos that are know to work still doesn't work, it would be good to try and see whether the player plays with and without ads. Video.js itself doesn't deal with ads directly, so, if it ends up being ads related, I'd ask you to open the issue against the ad plugin itself.

**Comment by maryam-abdullah** [comment]
Yes, it's played normally on mobile when there aren't any ads. However, when I test it on PC (with mobile view), it won't work with/without ads, giving the previously mentioned error.

Here's the test case:
```
<video id="videojs" class="video-js vjs-default-skin vjs-16-9 " width="640" height="264">
          <source src="http://5flix.cdn.octivid.com/vod/_definst_/smil:2017-04-13/vidtYBiZA7jIF.smil/playlist.m3u8" type='application/x-mpegURL'>
</video>
```
Ad: 
> http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&vid=short_onecue&correlator=

**Comment by maryam-abdullah** [comment]
It turns out setting up the video (data-setup='{"fluid": true,"playbackRates": [1, 1.5, 2] }) prevents the video from playing on mobile.
