### ISSUE TITLE
Can't disable fullscreen button

### ISSUE THREAD

**Issue by caleyshemc** [videojs/video.js#4407]
## Description
The example of disabling the fullscreen button in the docs does not work.

See example [here](http://jsbin.com/kiyuvej/2/edit?html,js,output).

### Expected
The fullscreen button is gone.

### Actual
The fullscreen button is still there.

### Error output
None.

#### videojs
Using the current CDN.
#### browsers
Broken in at least Firefox and Chrome.

**Comment by gkatsev** [comment]
The name you're using is incorrect. It's `fullscreenToggle`. You can see a list of the default controls at the bottom of this page: http://docs.videojs.com/tutorial-components.html.

Hope that helps.
