### ISSUE TITLE
video player play icon click event

### ISSUE THREAD

**Issue by maroontr** [videojs/video.js#4409]
is there a video player play icon click event in videojs, i could not find in docs?

**Comment by mister-ben** [comment]
`.getChild('bigPlayButton').on('click', function() {
  // do something
})`

**Comment by misteroneill** [comment]
You may also be interested in the `playing` event if you're trying to hook into the moment when playback begins:

```js
player.on('playing', function() {
  // do something
});
```

**Comment by maroontr** [comment]
I used to play event to solve my problem,misteroneill, is there a difference between play and playing events?

**Comment by gkatsev** [comment]
the `play` event is a request to play where-as `playing` means that playback has resumed.
Since things work, I'm closing this.

**Comment by schmod** [comment]
Does `click` actually fire on mobile clients?
