### ISSUE TITLE
Open .m3u8 as URL with user agent

### ISSUE THREAD

**Issue by Esteban555** [videojs/video.js#4412]
On this player using Contrib HLS for my app is there a way to open a .m3u8 file just by doing the URL?
Or is there a way to open the file it self on the player?

Example:

I have this file:
#EXTINF:0,Canal America
#EXTVLCOPT:http-user-agent=iPhone
http://prepublish.f.qaotic.net/epa/ngrp:americatvlive-100056_all/Playlist.m3u8

If u copy paste the URL will not open unless you do the whole file with user agent.

Im all ears for the better way to open this file on the video.js player of my app.

Thank you

**Comment by mister-ben** [comment]
I'm not exactly sure what you mean but you may be able to set a user agent header with `xhr.beforeRequest` if that's it.

https://github.com/videojs/videojs-contrib-hls/blob/master/README.md#hlsxhr

**Comment by Esteban555** [comment]
Right, the example I gave can only be open as a .m3u8 file. Now i can only do links to stream, not files, What i need is a URL link from the example where i can play or a way to open the file on my video.js player

**Comment by gkatsev** [comment]
Only Safari can play back m3u8 urls directly in the browser and not in a webpage.  You can try the [videojs webextensions for chrome](https://chrome.google.com/webstore/detail/videojs-webextension/cebdpbolebkmgidigfffifoemdcbhibf?hl=en) to be able to open m3u8 urls directly in the browsers.
