### ISSUE TITLE
Video is not played on Mobile!

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/video.js#4414]
Hello,
I'm using videojs without ads. On PC, it works fine, however on mobile (web), I'm getting this error.

> IDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. r {code: 4, message: "No compatible source was found for this media."}

```
<video id="videojs" class="video-js vjs-default-skin vjs-16-9 " width="640" height="264" controls preload="none">
                            <source src="@src" type="application/x-mpegURL">
</video>
```

Test case:
http://5flix.cdn.octivid.com/vod/_definst_/smil:2017-03-29/studioZWWMH.smil/playlist.m3u8

Thank you.

**Comment by maryam-abdullah** [comment]
After investigating the problem, it turns out "data-setup='{"fluid": true,"playbackRates": [1, 1.5, 2] }'" is the reason behind this error. Once it's removed, the error no longer exists.

Any thoughts why?

**Comment by mister-ben** [comment]
Works [here (6.1)](http://jsbin.com/kezubuq/edit?html,output) and [here (v5.20)](http://jsbin.com/kezubuq/edit?html,output) on both Android Chrome and iOS Safari with what you have mentioned there.

**Comment by maryam-abdullah** [comment]
Aha, I see.
I actually was getting this error on PC (with the mobile view). 

Thank you.

**Comment by mister-ben** [comment]
A desktop browser "emulating" mobile won't play HLS unless it's Safari or Edge. You can use videojs-contrib-hls for desktop HLS support.

**Comment by omeryounus** [comment]
you should include the HLS support in the html 
e:g
<script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>
