### ISSUE TITLE
How to enable picture in picture mode for safari?

### ISSUE THREAD

**Issue by sohrabzia** [videojs/video.js#4415]
I want to enable picture in picture placeholder for video for IOS devices.
I have tried this code
```
$("video").webkitSetPresentationMode("picture-in-picture");
```
This works on plan simple html5 player but it is not working with videojs.
I have tried to trigger  code with fullscreen button but still not working.

 [This is demo code](http://jsbin.com/tejenuluce/1/edit?html,js,output),

## Steps to reproduce

1. Play video on Iphone or Ipad.
2. Go full screen and click picture in picture button ( beside exit fullscreen button)
3. it wont fill video spot on webpage with place holder.

### Expected
when I play video in (picture in picture) mode there should be placeholder on video's original location.
![pip](https://user-images.githubusercontent.com/15019255/27038985-466938b8-4f95-11e7-8b11-d855345aec62.PNG)

### Actual
Video tag location is not showing anything at all.

## Additional Information

what browser are affected?
Safari 10 +

what platforms (operating systems and devices) are affected?
IOS

**Comment by mister-ben** [comment]
Safari triggers a webkitbeginfullscreen event when it enters pip mode, which caused us to add fullscreen styling to the inline placeholder.  This is fixed is 6.2.1

**Comment by sohrabzia** [comment]
Hi, thanks for the response. Is there any way i can get 6.2.1 js and css file without getting uncompiled files ? like minified just two files (js and css), I have search all over but all cdn, codepen or demo includes older version. Thanks,

**Comment by gkatsev** [comment]
Looks like the 6.2.1 zip didn't get uploaded to github releases properly. Just updated it. https://github.com/videojs/video.js/releases/tag/v6.2.1

**Comment by sohrabzia** [comment]
Thanks gkatsev  👍

**Comment by gkatsev** [comment]
@sohrabzia does everything work now? If so, can you close this issue. Thanks!

**Comment by sohrabzia** [comment]
sorry for the late response, I have tried v6.2.1 but it doesnt seem to be working. here is [Demo](odepen.io/sohrabzia/pens/public/)

**Comment by mister-ben** [comment]
Your example won't work for a few reasons. You're using jQuery without having the jQuery library loaded, and trying to go to picture in picture too early - Safari will only allow PIP mode after the video has started. 

You need to call `webkitSetPresentationMode()` on the tech el - the video element after the player has initialised, e.g.

      player.one('playing', function() {
        var techEl = player.tech(true).el();
        if (techEl.webkitSupportsPresentationMode && typeof techEl.webkitSetPresentationMode === "function") {
          techEl.webkitSetPresentationMode('picture-in-picture')
        }
      });

[example](http://jsbin.com/lekeluq/edit?html,output)

**Comment by thijstriemstra** [comment]
I guess this is different from the Picture-in-Picture API (https://googlechrome.github.io/samples/picture-in-picture/) that is available since Chrome 70+. Can this be supported? New ticket?
