### ISSUE TITLE
AC3 Audio support (No audio on most .mkv files)

### ISSUE THREAD

**Issue by jkrakenda** [videojs/video.js#4420]
I have no sound on most of my .mkv films. Files with AAC audio are working fine. Does video.js have some dropdown menue like vlc player to set the audio layer? Or does it simply not support AC3?

The issue was also discussed on the nextcloud forums.
https://help.nextcloud.com/t/video-app-problem/7643?source_topic_id=13834

**Comment by gkatsev** [comment]
As far as I understand, no browser currently supports AC3 audio.
