### ISSUE TITLE
How to solve CSS the problem with vjs-thumbnail-holder?

### ISSUE THREAD

**Issue by kukrik** [videojs/video.js#4422]
Normally, I would not rush with the issue here. I will try to solve the problem themselves. It turns out that the CSS problem solving can be difficult for me.

My player is version 6.0.1, I use https://github.com/dirkjanm/videojs-vtt-thumbnails.

I could not vjs-thumbnail-holder postpone to the left or right. I looked that it should be possible. Please see https://docs.brightcove.com/en/player/brightcove-player/guides/thumbnails-plugin.html.

Perhaps I think that this problem is related to the CSS box-sizing, which does not allow to break out?

This example works for me here: https://player.ead.ee/. My question here is that if anyone has managed to get a thumbnail holder operating procedures? Or have other ideas or suggestions?

My question is illustrated below screenshot:
![thumbnail-holder-place_1200](https://user-images.githubusercontent.com/2853034/27264741-f1c05834-548d-11e7-9f73-ef035f2850ce.jpg)

I am grateful for any thoughts!

**Comment by gkatsev** [comment]
The position of the thumbnail is calculated in javascript, you're probably not able to move it over with just CSS. You'll probably need to modify the plugin itself. I think it's this part that's causing this behavior: https://github.com/dirkjanm/videojs-vtt-thumbnails/blob/master/videojs.thumbnails.js#L198-L205.

Hope that helps.
