### ISSUE TITLE
6.1.0 Icons not rendering

### ISSUE THREAD

**Issue by timcosta** [videojs/video.js#4423]
## Description
VideoJS 6.1.0 installed via NPM does not render icons.

## Steps to reproduce
1. `yarn add video.js`
2. import vjs files via webpack
```javascript 
import 'video.js/dist/font/VideoJS.ttf';
import 'videojs-font/css/videojs-icons.css';
import 'video.js/dist/video-js.css';
```
3. Icons do not render

### Expected
I expected to see icons

### Actual
Any icon location is blank. I can see in the CSS file generated that it expects an icon placeholder to exist in the DOM, however my DOM does not have an icon placeholder.

Also, please note the `videojs-font` import. Without it, there are no references to any icons in the CSS included from VideoJS. I've checked the files on my laptop pre-webpack inclusion, and saw `@import "node_modules/videojs-font/scss/icons";` which is not valid, as `node_modules` does not exist inside the video.js folder in newer versions of npm.

If I remove all of my CSS imports and use `http://vjs.zencdn.net/6.1.0/video-js.css` the icons still do not render. If i use `http://vjs.zencdn.net/5-unsafe/video-js.css` as your homepage does, icons do render.

### Error output
None.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
6.1.0
#### browsers
tested on chrome
#### OSes
macOs 10.12.1
### plugins
none.

**Comment by clintonb** [comment]
I am seeing the same issue. If I use video.js without any plugins and with the 6.2.7 CSS from the CDN, the icons appear (because the `vjs-icon-placeholder` is present).

When I add the videojs-chromecast plugin, the icons disappear. It seems the plugin is triggering an old behavior in video.js.

**Comment by gkatsev** [comment]
You shouldn't need to import `videojs-font` directly as the video.js css includes them. If you're not seeing icons but using the 5.x css you are, it seems like maybe the version of video.js you end up including is still 5.x and not 6.x?
We changed the way that the icons are in v6 (the addition of the vjs-icon-placeholder) for accessibility and it could potentially have issues around that.
