### ISSUE TITLE
traffic drop from google after moving to videoJs

### ISSUE THREAD

**Issue by tonykor** [videojs/video.js#4428]
## Description

Hello, we have flash player, and after moving to html5 videoJs player our google traffic dropped about -50%, here is the screenshot https://i.imgur.com/3Jqq1jO.jpg, https://i.imgur.com/KJXHjj8.jpg marks on timeline is when we turn on/off videoJS. I'v tried it 2 times, with a month interval and the results is the same, the next day i'm turning on videojs google traffic drops, while all the other traffic behavioral parameters (bounce rate, visit duration, pageviews per visit) are at least the same.  I have think may be a videojs framework is so huge that google penalize websites.

Here is more info on our configuration:

videoJS v 5.13.12
plugins enabled:
+ [contrib-ads v4.1.4](https://github.com/videojs/videojs-contrib-ads)
+ [ima](https://www.github.com/googleads/videojs-ima)
+ [endcapCTA](https://github.com/wulfsolter/videojs-endcapCTA)
+ [brand](https://github.com/manelpb/videojs-brand)
+ [persistvolume](https://github.com/theonion/videojs-persistvolume)
+ [resolution-switcher](https://github.com/kmoskwiak/videojs-resolution-switcher)
+ one custom overlay plugin, like endcapCTA but overlay appears while video plays (midroll overlay).

I was thinking that the problem due to IMA plugin, which is requesting many third party resources, but after turning off contrib-ads and IMA, nothing changed, only after switching back to flash player the traffic from google grows again. I'm also must mention that video file link is not available in page source code and <video tag on the page without src attribute, its generated by javascript to protect video url from grabbing. 

I'd like to know does anyone have the same issues? Any help appreciate.

Thanks.

**Comment by mister-ben** [comment]
Perhaps Google was inferring some additional metadata from the previous embed? It may be worth adding schema.org metadata if you're not already.

https://developers.google.com/search/docs/data-types/videos

**Comment by tonykor** [comment]
Hi thanks for info, but i have not put any metadata on flash player.

**Comment by gkatsev** [comment]
Not exactly sure what could be the cause of this. The timing of the tests is also relatively low, it is possible that the rates will bounce back after a while and that the issue is related to a major change in the website. v6 of the player is a bit smaller, especially if you don't include the flash player. I've not really heard of things like this before as generally people end up switching from a much heavier flash-based player to the comparably much lighter Video.js player.
