### ISSUE TITLE
ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)  Chrome Live server

### ISSUE THREAD

**Issue by mhassanist** [videojs/video.js#4429]
## Description
When I open my encrypted stream locally, it works on chrome and firefox.
After upload to my hosted ubuntu server, It works on firefox but in chrome I get this error

`video.min.js:18 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.`

Media Link
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/play/videojs-widevine/bakkar_sample/player_test/

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.Open the link in fire fox. Working
2.Open same link in chrome. Not working
3.Error show in the console.

### Error output
`video.min.js:18 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.`

**Comment by BucherTomas** [comment]
Encrypted content needs to be served over https for Chrome 58 and newer, see WIDEVINE QUARTERLY PARTNER UPDATE- Q1 2017 paragraph at http://www.widevine.com/product_news.html . Localhost is considered secure, that is why it worked for you locally.

**Comment by BucherTomas** [comment]
Forgot to add that your player test page needs to be served over https, too.

**Comment by gkatsev** [comment]
Thanks @BucherTomas.
