### ISSUE TITLE
Protect video from download

### ISSUE THREAD

**Issue by dioobr** [videojs/video.js#4430]
Hello,

About the issue **https://github.com/videojs/video.js/issues/1771**. An alternative, which is even used by youtube, vimeo, is to include a layer in front of the video. Something like:

```
<style>
video { position: absolute; z-index: 20; }
.canvas { position: absolute; z-index: 30; }
</style>

<div>
<video src="example.mp4"></video>
<div class="canvas"><!-- --></div>
</div>
```

What do you think?

**Comment by michalrames** [comment]
The proposed overlay wouldn't prevent video download. What's worse it would negatively impact the user experience by preventing default behaviour of clicks, touches, and potentially mouse moves.

No matter what overlays you place over the video, the easiest way to download the video is to go to the developer tools (F12 in most browsers) and access the media URL from the network tab. 

You can stop the common user from downloading the video by overriding the context menu as suggested in the other thread. If you really want to prevent a more advanced user from downloading the video, look into live streaming and/or custom API and blob-based sourcing. 

But even that wouldn't stop anyone from using a screengrabbing software to simply record the video from their screen.

**Comment by misteroneill** [comment]
@dioobr You are free to make this UX choice in your app, but it's not something that Video.js will be introducing to the core library. As @michalrames said, it won't prevent users from downloading a plain MP4, HLS, or any other non-DRM stream.

Also, we have [an FAQ entry for this](https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-hide-the-links-to-my-videosubtitlesaudiotracks).

**Comment by gamma425** [comment]
4 years later... still accurate?
