### ISSUE TITLE
es6 import on iPad causes videojs/default system player to load??

### ISSUE THREAD

**Issue by ashtonlance** [videojs/video.js#4435]
## Description
Briefly describe the issue.
So I'm building an app using Vue to play back panorama videos using videojs and it works beautifully on web, iPhone and android. However, when I load the same code on my iPad I'm experiencing a strange issue - videojs AND the system's default video player both load the player. Pressing the videojs big-play-button causes the system player to take over. Tapping the 'Done' button in the system player brings me back to the videojs player, with the video paused at the correct timestamp - upon clicking play brings the system player back.

On the same device, building a similar app in Ionic/Angular 1.x using <script> tags to import the videojs / panorama-videojs files works just fine.

## Code
Here: [Video Player component on Github](https://github.com/atlance01/vue-quasar-app/blob/master/src/components/VideoPlayer.vue)

### Expected
I expected videojs to play back my video the same way it does on web, iPhone and Android.

### Actual
See description

### Error output
No errors

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
5.20.1
#### OSes
iPad / iPad Pro
### plugins
are any videojs plugins being used on the page? If so, please list them below.
panorama-videojs

**Comment by gkatsev** [comment]
That's really strange. It sounds like on iOS it's entering the fullscreen native playback mode when you hit play. Are you running this on the web on the iPad for is it an app so it runs in a webview?

**Comment by atlance01** [comment]
I'm using it in a hybrid app, so a webview. I've tried it using both Ionic and Quasar!
