### ISSUE TITLE
VideoJS #Translation problems

### ISSUE THREAD

**Issue by nvybvl** [videojs/video.js#4438]
## Description
Hi, I have a problem with the translations for the videoJS.
The "Mute" and "Full screen" buttons doesn't translate.

## Steps to reproduce
There is no steps to reproduce. 

### Expected
I expect to see the tooltip translated when I hover the buttons with my mouse.

### Actual
If you hover the "Mute" or "Full screen" buttons, a tooltip come out with the text which its not translated.

### Error output
No errors

### plugins
I use hola player, videojs thumbnails, videojs markers, videojs settings, videojs suggested videos

**Comment by nvybvl** [comment]
This is the code I use for "ES" (for example)

`videojs.addLanguage('es', {
        "Play": "Reproducir",
        "Pause": "Pausa",
        "Mute": "Silenciar",
        "Unmute": "Reanudar",
        "Settings": "Configuración",
        "Full screen": "Pantalla Completa",
        "Exit full screen": "Salir de pantalla completa"
    });`

**Comment by mister-ben** [comment]
The [text on the fullscreen control](https://github.com/videojs/video.js/blob/master/lang/es.json#L12) is `Fullscreen` without a space, so your translation of `Full screen` with a space wouldn't match. I can't say why Mute wouldn't work for you - please add a reduced test case to demonstrate the issue.

**Comment by nvybvl** [comment]
Yea, problem solved right that:

`videojs.addLanguage('es', {
        "Play": "Reproducir",
        "Pause": "Pausa",
        "Cinema": "Cine",
        "Mute": "Silenciar",
        "Unmute": "Reanudar",
        "Settings": "Configuración",
        "Quality": "Calidad",
        "Full screen": "Pantalla Completa",
        "Exit full screen": "Salir de pantalla completa"
    });`
