### ISSUE TITLE
How to get a download button?

### ISSUE THREAD

**Issue by 617429782** [videojs/video.js#4441]
## Description
I can user videojs play a mp4 in my web site ,but when I try to through the link to download video to the local, the browser automatically play the video but did not download, what should I do

**Comment by misteroneill** [comment]
This is more of a question of how to use a browser and doesn't have anything to do with Video.js.

However, you should be able to do something like right-click and "Save file as..." or in the browser's "File" menu, choose "Save Page As...".

Again, what your browser does with links to MP4 files is outside the scope of Video.js.

**Comment by hanumantha03** [comment]
I am trying to add a download button to the player created by the videojs. Could please tell me how can I get that. Is there any plugin that I have to install or any other work around that can be done
