### ISSUE TITLE
I use 6.2.0  video.js can not play rtmp video

### ISSUE THREAD

**Issue by best4s** [videojs/video.js#4446]
I use 6.2.0  video.js can not play rtmp video

anyone find this problem ?

**Comment by gkatsev** [comment]
Is videojs-flash project included? In 6.x the Flash tech is no longer available by default.

**Comment by AuSong** [comment]
`<script>
	videojs.options.flash.swf = 'js/video-js.swf';
	videojs('my-video', {
	sourceOrder: true,
	sources: [{
		src: 'rtmp://124.89.119.44:19350/live/livestream2',
		type: 'video/mp4'
	}],
	techOrder: ['flash']
});
  </script>`
--------------------------------------
videojs.VERSION = '6.1.0';
videojs-flashVersion version = "5.4.0";
--------------------------------------
![catch](https://user-images.githubusercontent.com/6788943/27618964-f2b867f2-5bf1-11e7-9ca8-9cb5908051d9.jpg)


--------------------------------------
click the play button ,but noting happened.
help.

**Comment by gkatsev** [comment]
Looks like the issue is with the url format, video.js expects the stream and connection pieces to be separated by `&`, see the [FAQ](https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-play-rtmp-video-in-videojs).

**Comment by AuSong** [comment]
i changed my code,but it doesn't work.

![image](https://user-images.githubusercontent.com/6788943/27622822-1444d454-5c0c-11e7-8967-ab1a2daf9ba4.png)

**Comment by mister-ben** [comment]
> type: 'video/mp4'

This content type is wrong. It should be `rtmp/mp4`.

**Comment by AuSong** [comment]
thanks , i changed but doesn't work .

**Comment by AuSong** [comment]
i changed ,but it doesn't work.
i test `rtmp://124.89.119.44:19350/live/livestream2` in flash ,it work well, code as:
![image](https://user-images.githubusercontent.com/6788943/27623565-98e13fe2-5c0f-11e7-9025-6d87f9bd7efe.png)
when i use video.js, html dom element inserted as 
![image](https://user-images.githubusercontent.com/6788943/27623637-ea0219be-5c0f-11e7-916e-c1224450abf9.png)
is there something wrong?

**Comment by AuSong** [comment]
thanks @gkatsev @mister-ben  ,it works well when i push it in tomcat;
my fault is open it from a file directly. 
difference i do not know between them.

**Comment by mister-ben** [comment]
The difference is that when you open from the file system, the browser will prevent javascript from that page from interacting with the swf because of the protocol mismatch - `file://` vs `http://`.
