### ISSUE TITLE
Custom subtitles

### ISSUE THREAD

**Issue by moshwebs** [videojs/video.js#4448]
I've been trying to find the following features in videojs but I couldn't find what I'm looking for

Basically I want to allow the user to be able to add a subtitle, manage the delay & size
I already found a website running videojs and have them but I couldn't the right resources
Please check this screenshot to better understand what I need
http://i.imgur.com/nZq6hQv.png

**Comment by gkatsev** [comment]
Adding subtitles is pretty easy assuming that you're using WebVTT files. See http://docs.videojs.com/tutorial-text-tracks.html for more info.

Sizing is generally either handled by the OS (like on iOS and Safari) or via the text track settings dialog that is used everywhere else when we have emulated text tracks.

Having subtitle delays is quite tricky actually. I'm not sure we can do it easily across the board. We can probably do it for emulated text tracks but I'm not sure we can do it for native text tracks. However, the way you'd do it is basically going through each of the cues in the Text Track and adjust the start and end times of each cue by the delay adjustment value.
