### ISSUE TITLE
this video can not paly on chrome

### ISSUE THREAD

**Issue by uikoo9** [videojs/video.js#4452]
on this url  https://codepen.io/heff/pen/EarCt  modify video src to http://zbywsvod.weclassroom.com/vod/zby/_43592_14736.mp4

on chrome can not play,but firefox can play why?

**Comment by mister-ben** [comment]
Chrome doesn't like this video's audio track - if you open `chrome://media-internals` you'll see the error "audio decoder initialization failed".

Chrome Canary gives a little more detail: "Audio configuration specified 2 channels, but FFmpeg thinks the file contains 1 channels"

**Comment by gkatsev** [comment]
Unfortunately, not much we can do in this case. We recommend you re-encode your video for web.
Also, check out our [troubleshooting guide](https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#problems-with-media-formats).
