### ISSUE TITLE
Which one is the latest stable 5.x version?

### ISSUE THREAD

**Issue by borzaka** [videojs/video.js#4453]
I currently use the `5.19.2`, but I see there are two newer versions: `5.20.0` and `5.20.1`, but they are labelled as `Pre-release`. They are not stable, or what?

The 5.x branch is no longer maintained?
I use many 3rd party plugins, switching to 6.x would couse me pain?
Thx.

**Comment by gkatsev** [comment]
Latest 5.x is 5.20.1, I always forget to update the pre-release tag on github. npm is always up-to-date, though.
```sh
$ npm dist-tag ls video.js
latest-5: 5.20.1
latest: 6.2.0
next-5: 5.20.1
next: 6.2.1
```

I've updated the github release flag as well.

Depending on how well maintained the plugins you're using are, it could be not much of a problem. A lot of the plugins that we maintain for video.js and also a lot of the Brightcove plugins have been updated to support both 5.x and 6.x of video.js.

Hope that helps.
