### ISSUE TITLE
Bower not install the distributed version

### ISSUE THREAD

**Issue by CHEWX** [videojs/video.js#4465]
## Description
As per title.

## Steps to reproduce
1. `bower install video.js --save`
2. doesn't install the dist version.

### Expected
Would expect to see a file structure as per http://videojs.com/getting-started/

### Actual
See source code available on Github

Thanks.

**Comment by gkatsev** [comment]
Unfortunately, we no longer support bower with Video.js 6.
I would recommend you to switch to npm (or yarn) or if you need to continue using bower look into the npm provider plugin for bower.

I'm going to update the website this this change. Thanks for issue and sorry to be the bearer for bad news.

**Comment by betelgeuse** [comment]
@gkatsev did something change or is the web page still not updated?

https://docs.videojs.com/docs/guides/setup.html

**Comment by mister-ben** [comment]
https://docs.videojs.com/docs is an archive of an old version. https://docs.videojs.com/tutorial-setup.html is current.
