### ISSUE TITLE
Using webpack with videojs-contrib-hls v5.8.0 is not working ?

### ISSUE THREAD

**Issue by zcoding** [videojs/video.js#4472]
I follow the [document](https://github.com/videojs/video.js/blob/master/docs/guides/webpack.md#using-webpack-with-videojs-contrib-hls) and ...
__Just not working!__
Need a complete example with webpack configuration and code.
Please... 🙃

**Comment by thijstriemstra** [comment]
@zcoding any errors?

**Comment by jgreeee** [comment]
Hi

On Jul 8, 2017, at 12:39 PM, Thijs Triemstra <notifications@github.com> wrote:

@zcoding any errors?

**Comment by zcoding** [comment]
I'm not sure if it is an issue of videojs-contrib-hls. It seems that the `Hls` object is not injected into the videojs object.

**Comment by zcoding** [comment]
```javascript
import VideoJS from 'video.js'
import * as HLS from 'videojs-contrib-hls'
console.log(VideoJS.Hls) // undefined
```

**Comment by gkatsev** [comment]
Unfortunately, contrib-hls doesn't work with webpack by default. See https://github.com/videojs/videojs-contrib-hls/issues/600
