### ISSUE TITLE
advanced player example/playlist question (docs are broken)

### ISSUE THREAD

**Issue by ivo1981** [videojs/video.js#4474]
When loading an external playlist the now playing is not working anymore.
How can I fix this?

I Copied the advanced example, added a link to the index.html:
```
<a href="#"  onclick="load_daltons()" >
        <img src="images/dedaltons.png" alt="de Daltons" class="img-responsive" style="max-height:220px">
</a>
```

included an external playlist with array daltons:
`<script src="media/daltons/playlist.js"></script>
`
onclick event:

```
<script>
function load_daltons(){
    player.playlist(daltons);
    player.playlist.first();
    //player.playlistUi();
}
</script>
```

## Results
loads the default playlist on page load.  vjs-playlist-now-playing class added.
On clicking the link;
playlist loads, the player shows the first video. but when you play the video, there is no vjs-playlist-now-playing class added

### Expected
on pageload: load default playlist, vjs-playlist-now-playing class added.
on click: playlist loads, the player shows the first video, vjs-playlist-now-playing class added to current item.

### Error output
console throws:
```
VIDEOJS: ERROR: TypeError: Cannot read property 'name' of undefined
    at Player.<anonymous> (advanced.js:59)
    at HTMLDivElement.bound (video.js:22751)
    at HTMLDivElement.data.dispatcher (video.js:22542)
    at Object.trigger (video.js:22664)
    at Player.trigger (video.js:1522)
    at Player.handleTechLoadStart_ (video.js:10014)
    at Html5.bound (video.js:22751)
    at HTMLVideoElement.bound (video.js:22751)
    at HTMLVideoElement.data.dispatcher (video.js:22542)
```

**Comment by gkatsev** [comment]
Can you provide more info? Is the issue that playlist-ui fails to load properly? If so, it sounds like the issue is that maybe playlist-ui doesn't have an element to insert stuff into?
