### ISSUE TITLE
I want to edit "headers" 

### ISSUE THREAD

**Issue by coder0wang** [videojs/video.js#4476]
I want to play ours video,but we need get some value from head;
I can't find that how to edit head.
Get me some help,please.
thx.

**Comment by gkatsev** [comment]
Are you playing back an mp4 or what type of file? If you're playing back mp4, it's not possible to change the headers sent. If you're using HLS, you can, see [the docs](https://github.com/videojs/videojs-contrib-hls/#hlsxhr).
