### ISSUE TITLE
Cannot read property 'xhr' of undefined

### ISSUE THREAD

**Issue by nhatdev1193** [videojs/video.js#4479]
Hello everyone and thanks for you offering help.  I tried to send Headers into the videojs.Hls.xhr.beforeRequest function, so I implement:
`<script src="http://vjs.zencdn.net/6.2.0/video.js"></script>`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.8.0/videojs-contrib-hls.min.js"></script>`

`var player = videojs('my-video')`
 ```
player.hls.xhr.beforeRequest = function(options) {
        options.headers['X-User-Id'] = 'nhat';
        console.log(options);
        return options;
      };
```
```
 player.src({
        src: 'http://localhost:3000/video',
        type: 'video/mp4',
        withCredentials: true
      });
```
But it seen, player.hls is underfined :cry: Plese help me fix this error,
Regards.

**Comment by gkatsev** [comment]
Please just open one issue, no need for two. Closing in favor of https://github.com/videojs/videojs-contrib-hls/issues/1192.
