### ISSUE TITLE
How can i detect that a live url is streaming 

### ISSUE THREAD

**Issue by luyingjia** [videojs/video.js#4480]

**Comment by luyingjia** [comment]
I get a Live Streaming Which Isn't Live yet.when the live stream is active,the player can not play.

**Comment by gkatsev** [comment]
Is this HLS? if so, can you open an issue against [contrib-hls](https://github.com/videojs/videojs-contrib-hls/issues/new) instead? Please include more details about your livestream, what your expectations are, and what actually happens. Also, does the live stream url return a 404 while it isn't live?
