### ISSUE TITLE
The "flash" tech is undefined &&  No compatible source was found for this media

### ISSUE THREAD

**Issue by zhanyulong** [videojs/video.js#4482]
## react with video.js and videojs-flash rtmp live video not working
Fllowed http://docs.videojs.com/tutorial-react.html

<img width="790" alt="dingtalk20170713170506" src="https://user-images.githubusercontent.com/6070885/28158812-869f8d36-67ed-11e7-8bd8-f91dba27cb16.png">

<img width="780" alt="dingtalk20170713170645" src="https://user-images.githubusercontent.com/6070885/28158870-af717b20-67ed-11e7-892c-a4394cfeb1c1.png">

**Comment by mister-ben** [comment]
Video.js 6 does not include the Flash tech. See https://github.com/videojs/videojs-flash

**Comment by zhanyulong** [comment]
@mister-ben Did include videojs-flash and did read all the docs, just not work. 
<img width="626" alt="dingtalk20170714092928" src="https://user-images.githubusercontent.com/6070885/28194467-03e2f92a-6877-11e7-8d19-0a6e105a0002.png">
So I switch to other service.

**Comment by suiwenfeng** [comment]
![5b65cfa8-733a-4f16-a9e8-33db5e8cdabf](https://user-images.githubusercontent.com/2735407/29113213-09cc80d4-7d23-11e7-848c-7dcd44346e65.png)

Attach my trouble shooting, Will keep tracking the issue.

**Comment by Statfine** [comment]
@zhanyulong  Same problem in  my react project, have you solved it

**Comment by FlyingBugger** [comment]
Same problem in my Vue project.
when i turn to mobile,it shows 
![image](https://user-images.githubusercontent.com/24517261/32314554-65871a62-bfe3-11e7-8bf3-4d94d776b653.png)

**Comment by gkatsev** [comment]
There's a lot more information in this issue: https://github.com/videojs/videojs-flash/issues/26
We have a fix in progress.

**Comment by josholdham** [comment]
Hi @gkatsev - glad to hear this is being addressed. Sorry to be a pain, but any update on when this might be ready?

**Comment by gkatsev** [comment]
Closing this in favor of videojs/videojs-flash#39. We have a potential fix in that PR but it has potential issues and we want to make sure we don't break any browsers when we deploy it but it's out there for people to use if they want.
