### ISSUE TITLE
Playing video encrypted with clearkey or other DRMs

### ISSUE THREAD

**Issue by mhassanist** [videojs/video.js#4484]
I want to play encrypted media with VideoJs. I have videos encrypted with ClearKey. I tried the 2 plugins available with no luck. Please refer to 
https://github.com/videojs/videojs-contrib-eme/issues/20

Can I integrate with the player directly and set the encryption information without using plugin ? Would you please guide in this.

**Comment by gkatsev** [comment]
Closing in favor of videojs/videojs-contrib-eme#20, though, I'm not sure we would be able to help much without a reduced test case.
