### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by robindra** [videojs/video.js#4485]
Hi All, 
Recently, I have implmented videojs libary in our project and it is working as expected for all case but it got fails when I start implementing hls-with-credential true setup. As for information, I am using the below link for the library 
https://unpkg.com/video.js/dist/video.js
https://unpkg.com/videojs-flash/dist/videojs-flash.js
https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js

and I had setup the js as below 
```js
videojs("vElmId",{
                    controls: true,                    
                    width: "80%", 
                    aspectRatio: "16:9",
                    html5: {
                        hls: {
                            withCredentials: true
                        }
                    }
                }, function(){
                }); 
```
I have checked most of the available link for the similar issue but not able resolve even after falling those steps mentioned. So, can any one help me out whether I have missed something in my setup or need to include any more library? 

Regards, 
Robindra Singha

**Comment by silverxp** [comment]
Are you still having this issue? I had some trouble too with setting up HLS credentials. The setup seems fine and the right files are included.

I recently started using encrypted HLS with signed cookies for Amazon CloudFront. I recommend checking the network tab in Chrome for possible errors. If this is a cookie related problem you can check if your browser is sending the cookies.

If it's sending the cookies, there had to be a problem with your application. If it's not sending cookies there possible is a problem with Video.js.

**Comment by robindra** [comment]
Actually, I have found out that the issue was in my code when setting cookies. As the HLS source url and my domain was different. Hence, I was setting the cookies with my domain instead of HLS source domain. Now, cookies are sending when both domain are same and setting the cookies with same domain of HLS source. 

Finally, I would like to thank your time and suggestion.

**Comment by haseeb-zechtech** [comment]
@robindra  I am using videojs in angular with same configuration . but is not working
