### ISSUE TITLE
video is not playing after hiding the Video Js play button 

### ISSUE THREAD

**Issue by usamamashkoor** [videojs/video.js#4492]
Hi i using videos js 5 what i am trying to here is i want to hide the video js by default plat button which i have done using this code 
```
.vjs-default-skin.vjs-paused .vjs-big-play-button 
{
	display: none;
} 
```
by default the video will be paused and i am showing a poster on the video when the video is not played.
but when some one clicks on video poster or video then i want to play the video.
Here is my code 
```
<div class="wrapper-banner" id="video_containerss">
       <video class="video-js vjs-default-skin" id="video_player" poster="image_path" controls data-setup="{}" width="100%" style="width:100%;" >
	        <source src="video_path" type="video/mp4" />
       </video>   
</div>
```
and here is my JavaScript 
```
var player = 	videojs("video_player");
player.ready(function(){

	    var myPlayer = this;    // Store the video object
	    var aspectRatio = 9/16; // Make up an aspect ratio

	    function resizeVideoJS(){
	    
	      var width = document.getElementById('video_containerss').offsetWidth;
	    
	      myPlayer.width(width).height( width * aspectRatio );
	    }

	    resizeVideoJS(); // Initialize the function
	    window.onresize = resizeVideoJS; // Call the function on resize
});
```
my player is working fine on desktop but on tablet and mobile devices when the page is load and the video poster is showing when i click on the video poster then the video does not play.
Can some one please help me on this issue please.

Thanks in advance.

**Comment by ethernetweb** [comment]
I can confirm this issue. I use autoplay and don't want / need the "big play button".
Upon hiding the CSS element, it will not auto-play. Also I should note that this was Firefox on Linux and not a mobile device.

**Comment by asd29696** [comment]
2017年9月25日 下午1:00，"ethernetweb" <notifications@github.com>寫道：

**Comment by gkatsev** [comment]
When controls are disabled (no `controls` attribute or option), click-to-play is disabled. This is most likely causing the issue.
Also, you can use our [`aspectRatio()` method](http://docs.videojs.com/player#aspectRatio) like `player.aspectration('9:16')`.
