### ISSUE TITLE
MEDIA_ERR_SRC_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Komak57** [videojs/video.js#4495]
Setting up video.js in an attempt to preview RTMP/FLV live stream feed in a local environment for debuggins purposes. I've tried to obtain the raw NGINX feed, and the FFMPEG re-encoded feed, and every time I load the page, video.js says "No compatible source was found for this media." Chrome Console returns the following error:

`video.min.js:18 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. dcode: 4message: "No compatible source was found for this media."__proto__: ObjectMEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: 0message: ""status: nullconstructor: function d(a)MEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4defaultMessages: ObjecterrorTypes: Array(6)arguments: (...)caller: (...)length: 1name: "d"prototype: Object__proto__: function ()[[FunctionLocation]]: video.min.js:14[[Scopes]]: Scopes[3]__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
c.logByType @ video.min.js:18`

Is there further configuration settings required, or does video.js simply not support RTMP live streams?

	<head>
	...
	<link href="//vjs.zencdn.net/5.19/video-js.min.css" rel="stylesheet">
	<script src="//vjs.zencdn.net/5.19/video.min.js"></script>
	</head>
	...
	<body>
	...
	<video
		id="stream-feed"
		class="video-js vjs-default-skin"
		controls
		preload="auto"
		poster=".../tears.png"
		data-setup='{}'
		width="640" height="360">
	  <source src="<?php echo "rtmp://$baseurl/stream/" .  $_SESSION["nicename"];?>" type="video/flv"></source>
	  <source src="<?php echo "rtmp://$baseurl/raw/" .  $key;?>" type="video/flv"></source>
	  <p class="vjs-no-js">
		To view this video please enable JavaScript, and consider upgrading to a
		web browser that
		<a href="http://videojs.com/html5-video-support/" target="_blank">
		  supports HTML5 video
		</a>
	  </p>
	</video>
	...

EDIT: It looks like video/flv is not a supported type. However, none of the available types that I can find will play the stream feed. It just continues to buffer forever with a console error `profile.php:1 GET rtmp://192.168.1.239/raw/{alpha-numeric key} net::ERR_UNKNOWN_URL_SCHEME`

**Comment by mister-ben** [comment]
Use `rtmp/flv` as the type.

**Comment by Komak57** [comment]
<source src="<?php echo "rtmp://$publicurl/raw/" .  $key;?>" type="rtmp/flv"></source>

Reports `CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED`

I've tried through public, and local ip's. VLC confirms that the feed can be obtained in both scenarios. Raw feed uses Codec H264 - MPEG-4 AVC (avc1) and MPEG AAC Audio (mp4a). I get this error even when the feed is not available.

**Comment by betterjun** [comment]
The same issue to me. I tried with VLC player and it works, but vidoejs doesn't work on any of chrome,firefox,ie,edge. The rtmp stream info is h264-mpeg-4 avc(part10)avc1 from VLC. My code is below,
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">  
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">  
<head>  
<meta http-equiv="content-type" content="text/html; charset=utf-8" />  
<title>live-player</title>  
<style type="text/css">  
</style>  

<link href="http://vjs.zencdn.net/5.19/video-js.min.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/5.19/video.min.js"></script>
</head>  
<body>  
	<video
		id="my-player"
		class="video-js"
		controls
		preload="auto"
		poster="http://vjs.zencdn.net/v/oceans.png"
		data-setup='{}'

		>
		
		
	  
	  <source src="rtmp://live.hkstv.hk.lxdns.com/live/hks" type="rtmp/mp4">
	  
	  

	  <p class="vjs-no-js">
		To view this video please enable JavaScript, and consider upgrading to a
		web browser that
		<a href="http://videojs.com/html5-video-support/" target="_blank">
		  supports HTML5 video
		</a>
	  </p>
	</video>

</body>  
</html>  `

**Comment by suiwenfeng** [comment]
+1

**Comment by Komak57** [comment]
It appears that VideoJS requires a techOrder specification in order to load Flash content (only thing capable of playing rtmp:// direct links) in order to work, or HLS needs to be configured in NGINX to create the m3u8 playlist file, and then be set up in techOrder to stream HTML5 content.

`	var streamPlayer = videojs('streamPlayer', {
				techOrder: ['html5','flash'],
				sources: [{
					src: '//<?= $surl ?>/hls/<?= $current_channel ?>.m3u8',
					type: 'application/x-mpegURL',
					withCredentials: true
				},{
					src: 'rtmp://<?= $surl ?>/stream/<?= $current_channel ?>',
					type: 'rtmp/flv',
				}],
	});`

**Comment by suiwenfeng** [comment]
@Komak57  i have test it only not work in chrome yestoday.
i compiled video.js,video-flash,video-js-swf using the master branch, and only chrome not work no my rtmp stream.

**Comment by Komak57** [comment]
Have you told Chrome to allow Flash on your site? Left of your URL bar, there should be an (i) icon (or a lock with HTTPS sites). Click it, it will pull a drop down, set Flash to "Always Allow on this Site" and it should work for Chrome. Chrome has it's own built-in Flash player. Hope that helps.

**Comment by suiwenfeng** [comment]
@Komak57 Edge and Chrome not working and prompt to all flash

**Comment by gkatsev** [comment]
Yeah, unfortunately, chrome disables flash by default and doesn't expose the API for it. We have a potential fix in videojs/videojs-flash#39 but it's on hold to make sure we don't break anything.
