### ISSUE TITLE
npm install  error

### ISSUE THREAD

**Issue by coder0wang** [videojs/video.js#4499]
npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-21312-2fcdbcb6/registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm ERR! Expected: 4de911e667b0eae9124e34254b53aea6fc618d3e
npm ERR! Actual:   59f0fcdcbe693ae76d84d47fdfb532befa8bbc71
npm ERR! From:     https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/video/video.js1/npm-debug.log

i always got this error,help me!

**Comment by gkatsev** [comment]
That happens sometimes and usually I've been able to fix it by clearing node_modules and re-installing.
