### ISSUE TITLE
Subtitle tracks menu disappears on Android native

### ISSUE THREAD

**Issue by arski** [videojs/video.js#4502]
Hi, I'm wondering if you ever experienced an issue with subtitle tracks menu disappearing on Android. We send tracks to the video.js player and if they are auto-enabled they show just fine. But the menu seems to appear for an instant (if the loading is slow enough) and then disappear. Would you know why this is happening? Only happens on Android, not iOS or desktop..

Thanks!

cc @luarmr fyi

**Comment by gkatsev** [comment]
That's pretty weird. What version of video.js is being used? Have a reduced example? I've mostly seen it because the tracks got removed somehow, though, not sure how/why it would happen.
