### ISSUE TITLE
Cannot read property 'BANDWIDTH' of undefined

### ISSUE THREAD

**Issue by SzHeJason** [videojs/video.js#4503]
![image](https://user-images.githubusercontent.com/20609396/28398586-6f7db2de-6d3a-11e7-9bd0-1b09418ccb4c.png)
![image](https://user-images.githubusercontent.com/20609396/28398599-8690e810-6d3a-11e7-884c-c0031d49ce61.png)

**Comment by gkatsev** [comment]
Looks like this would be an issue with [contrib-hls](https://github.com/videojs/videojs-contrib-hls/). Can you please re-open this [there](https://github.com/videojs/videojs-contrib-hls/issues)? Also, please follow the [Issue Template](https://github.com/videojs/videojs-contrib-hls/blob/master/.github/ISSUE_TEMPLATE.md) and fill it out completely for us to be able to help you, even better if you can provide a reduced test case.
