### ISSUE TITLE
The "Setup" link on the doc home page is broken

### ISSUE THREAD

**Issue by defaria** [videojs/video.js#4504]
When you go to http://docs.videojs.com/
You read: 

...

Getting Started

Setup

The setup guide covers all methods of setting up Video.js players.

....

The word setup is a link, which is broken. It links to -> /#setup.html when it should probably link to /tutorial-setup.html

**Comment by defaria** [comment]
The jump anchors on the table of contents are also not working. It look like the section IDs were removed.

http://docs.videojs.com/tutorial-options.html#muted

**Comment by gkatsev** [comment]
These should be fixed now.
