### ISSUE TITLE
Show overlay while the user has paused the video

### ISSUE THREAD

**Issue by jackocnr** [videojs/video.js#4505]
## Description
I would like to show a small "share" overlay over the video while the user has paused it. I'm listening for the `pause` event, which is working, but AFAICT at that point, there's no way to know if the pause was the user's intent (e.g. they clicked the pause control, clicked on the video, or hit space) or for some other reason (e.g. the user is seeking ahead, or we're just on a slow connection and the video needs to buffer). Am I missing something?

I've tried utilising the `working` and `progress` events, or checking if the container has the `vjs-working` class, but none do the job properly.

#### videojs
v5.11.6
#### browsers
Chrome v59
#### OSes
MacOS v10.12.5
### plugins
videojs-contrib-hls
videojs-resolution-switcher

**Comment by gkatsev** [comment]
You can see whether it's happening as part of a seek by checking the `seeking()` flag which will tell you whether you're seeking or not.

Hope that helps.

**Comment by jackocnr** [comment]
Hi there, thanks for your reply. So yes I can rule out seeking by checking the `seeking()` flag as you say, and I guess I can rule out scrubbing by checking the `scrubbing()` flag? But what about buffering? And are there any other situations I need to check for, where a pause could be triggered by videojs when no action has been performed by the user?

Ideally there would be something like a `userpause` event.
