### ISSUE TITLE
npm notice created a lockfile as package-lock.json. You should commit this file. added 1569 packages in 207.838s

### ISSUE THREAD

**Issue by coder0wang** [videojs/video.js#4509]
I just "npm install",got that msg,but haven't "dist" folder

Testing binary
Binary is fine
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> video.js@6.2.4 prepublish /Users/wangyudi/code/git/videojs/video.js1
> not-in-install && run-p docs:api build || in-install

npm notice created a lockfile as package-lock.json. You should commit this file.
added 1569 packages in 207.838s

**Comment by gkatsev** [comment]
Thanks. We're not quite ready to upgrade to npm 5 so we'll refrain from checking one in. However, we're aware of this and we'll check it in when we upgrade to npm 5. Hopefully sooner rather than later.
