### ISSUE TITLE
The variation of getting textTrack cues in android and ios

### ISSUE THREAD

**Issue by Xixiao007** [videojs/video.js#4510]
## Description
I have a hybrid mobile app with videojs embeded.  The way to retrieve textTrack cues are different in Android and iOS. 
In Android, it is `textTracks().cues.cues_`
In iOS, it is `textTracks().cues` 

## Steps to reproduce
in Android, to get the first textTrack cue text, 
```
videoJSplayer.textTracks()[0].cues.cues_[0].txt;
```
in iOS, to get the first textTrack cues
```
videoJSplayer.textTracks()[0].cues[0].txt;
```

### Expected
I would expect a consistent method in both platform

### plugins
no

**Comment by gkatsev** [comment]
That's incorrect. You can get the cues the same way on both platforms. `.cues` is always the TextTrackCueList. Our emulated text tracks have the same API as native text tracks.
So,
```js
console.log(player.textTracks()[0].cues[0].text)
```
will work on both platforms.

Also, properties suffixed with `_` are generally marked such to indicate they are private and users should try and avoid using them.

Hope that helps.
