### ISSUE TITLE
textTracks() not returning the number of text tracks immediately after initialization.

### ISSUE THREAD

**Issue by rparjun** [videojs/video.js#4511]
## Description
`textTracks()` not returning the number of text tracks immediately after initialization.

## Steps to reproduce
https://jsfiddle.net/psnnpff2/

## Results
fiddle will show an alert with number of tracks present in player, first it shows 0, then in the 50ms setTimeout it shows 1.

Not sure if this is a bug or known behavior.
Is there any other event which will be triggered when tracks are loaded?

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
videojs - 6.2.0
#### browsers
Chrome - 59.0.3071.115
#### OSes
Linux - Ubuntu
### plugins
none

**Comment by borzaka** [comment]
Try the `loadedmetadata` event inside your ready callback:

```js
player.on('loadedmetadata', function() {
	//Fires when the browser has loaded meta data for the audio/video.
});
```

I have a similar issue (#4468), where sometimes my Text Tracks not ready even in the `loadedmetadata` event.

**Comment by rparjun** [comment]
Thanks @borzaka ! I will try it out and let you know.

**Comment by gkatsev** [comment]
That's a bit weird. I'd have expected it to be available on player ready. `loadedmetadata` as @borzaka mentioned is a great event to listen to and is most likely the time it should be available in.

Though, it's possible that there's some tweaks that need to happen with regards to the player and text tracks initialization.

**Comment by Yalhu** [comment]
`videojs.hook('setup', function(player){ })` textTracks() not retrun the tracks. 
Then i use `loadedmetadat` and select one track ,the first subtitle appear at the top-left of player.#4659

**Comment by rparjun** [comment]
`loadedmetadata` event worked!
Thanks @borzaka @gkatsev
