### ISSUE TITLE
Recorded mp4 video is not supported

### ISSUE THREAD

**Issue by hamid96Macking** [videojs/video.js#4515]
Hi
I have recorded a **mp4 video by screen recorder** then I used source tag to include it within my website page, But I received and error which tells that the **media is not supported by video js** or couldn't be found. (I'm sure that src value is correct)

**Comment by mister-ben** [comment]
It's possible the software is using a codec other than h264, which is needed for web playback. You can use mediainfo or ffprobe to check the codecs (should be h264 and aac or mp3) and whether the container really is MP4. VLC or Quicktime will also tell you the codecs but not about the container.

You also need to check your server is serving the file correctly - there should be a `Content-Type: video/mp4` header and it must respond to range requests properly.

**Comment by hamid96Macking** [comment]
@mister-ben I've checked the codec and it was equal to **MPEG-4 Video, AAC**. So is it correct?

**Comment by hamid96Macking** [comment]
Okay! problem has been solved.
Just need to check video's codec and type and make sure video codec is equal to **MPEG-4 Video, AAC**.

**Comment by hamid96Macking** [comment]
Okay! problem has been solved.
Just need to check video's codec and type and make sure video codec is equal to MPEG-4 Video, AAC.
