### ISSUE TITLE
Add a stop method

### ISSUE THREAD

**Issue by kitsunde** [videojs/video.js#452]
Since there is `play`, it's unexpected to not have a `stop` method, it could probably be an alias for:

```
video.pause();
video.currentTime(0);
```

**Comment by shazvan275** [comment]
afadf

**Comment by thebkbuffalo** [comment]
Honestly, how do you not have a stop method? Please please please add one

**Comment by heff** [comment]
Can you explain the use case in more detail where a stop button is valuable?
