### ISSUE TITLE
Line 8645 (video.js) reports "Unresolved variable or type rects"

### ISSUE THREAD

**Issue by chrisdeeming** [videojs/video.js#4521]
## Description
I'm not sure this has any adverse affects but my IDE is always complaining.

```    
    var rects = (rects = obj.div.childNodes) && (rects = rects[0]) &&
                rects.getClientRects && rects.getClientRects();
```

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Most IDEs will likely be complaining about this line as `rects` is indeed an unresolved variable.

### Error output
`Unresolved variable of type rects`

#### videojs
6.2.4
#### browsers
N/A
#### OSes
N/A
### plugins
N/A

Suggested fix:
```
    var rects;
    rects = (rects = obj.div.childNodes) && (rects = rects[0]) &&
                rects.getClientRects && rects.getClientRects();
```

**Comment by gkatsev** [comment]
While it's a bit of a weird construct, it's definitely valid javascript.
