### ISSUE TITLE
IE11 Error: "TypeError: Unable to get property 'open' of undefined or null reference"

### ISSUE THREAD

**Issue by ytakane** [videojs/video.js#4522]
## Description
Brightcove video with videoJS is timing out in IE11 with error: Error: TypeError: Unable to get property 'open' of undefined or null reference.  

Test link: http://jsbin.com/virahulero/1
HTML: http://jsbin.com/virahulero/1/edit?html  (example works in html editor, but not in output mode above)

![videojs_err](https://user-images.githubusercontent.com/8632143/28638409-cacccc74-7212-11e7-98e6-9d5e6f37d521.PNG)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Click play on video

### Expected
Video plays after clicking play button

### Actual
Video spins then times out

### Error output
Error: TypeError: Unable to get property 'open' of undefined or null reference

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
6.2.0
#### browsers
IE11 - possibly earlier versions of IE as well, but not Edge or Chrome
#### OSes
Windows 7
### plugins
http://players.brightcove.net/4413047261001/default_default/index.min.js

**Comment by gkatsev** [comment]
The issues comes up because both the brightcove player and videojs are included on the page. The Brightcove Player already includes video.js, so, there's no need to include it as well.

Hope that helps.

**Comment by ytakane** [comment]
Sorry I forgot to check back on this ticket because we found a workaround.  Thank you for your help, I didn't realize Brightcove included video.js.  I will update our code to remove the extra library.
