### ISSUE TITLE
How a MenuItem can be selected only one?

### ISSUE THREAD

**Issue by Yalhu** [videojs/video.js#4524]
## Description
1. I create a Menu and add some MenuItems to it ,but it can't be selected only one.
2. And I want to cancel the first item event of hover so it will not have a white background-color.
## Steps to reproduce
``` javascript
var rate_list=[
            {rate:0.25,text:'0.25x'},
            {rate:0.5,text:'0.5x'},
            {rate:1,text:'Normal Rate'},
            {rate:1.25,text:'1.25x'},
            {rate:1.5,text:'1.5x'},
            {rate:2,text:'2x'},
            {rate:4,text:'4x'},
        ];
        function set_playbackRate(player){
            rate=menuButton.createMenu();//menuButton is a MenuButton class
            rate.addItem(new MenuItem(player,{label:'Rate'}));
            for(let i=0;i<rate_list.length;i++){
                var rate_item=new MenuItem(player,{label:rate_list[i].text,selectable:true});
                rate_item.on('click',function(){
                    player.playbackRate(rate_list[i].rate)
                })
                rate.addItem(rate_item);
            }
            player.controlBar.addChild(rate)
        }
```
## Results
![problem_videojs](https://user-images.githubusercontent.com/27722787/28655184-6d147798-72cc-11e7-9e95-2535c1fcfd9a.png)
### Expected
I want to select the MenuItem like radio Button.

**Comment by OwenEdwards** [comment]
The `onclick` handler for the `MenuItem` needs to disable all the other MenuItems (rates). See https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/text-track-menu-item.js#L77-L114 for how this is handled for Text Tracks.
