### ISSUE TITLE
How do I make the play progress transition smoother for VideoJS plugin?

### ISSUE THREAD

**Issue by mawenmaywin** [videojs/video.js#4526]
I am trying to make the play progress transition smoother for VideoJS plugin. I've tried to edit the CSS but it causes a delay when the video is paused or stopped. Please help.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play a short video that's about 5 seconds long.
2. You will notice that the slider is jumpy.
3. If you play a video on Youtube it is smooth even if it is a short video.

I am using the latest version of VideoJS.

**Comment by gkatsev** [comment]
Yeah, it's something we'd like to improve. We probably need to cancel the old animation and switch to animating to the new position each time the time changes.
Help in this area would be greatly appreciated.

**Comment by mawenmaywin** [comment]
Thanks for the reply. I was really hoping someone already found a way to do it. I've tried to edit the Javascript code myself, but with no luck. Help in this area would indeed be greatly appreciated.

**Comment by vhmth** [comment]
Seems like it wouldn't be that we cancel the old animation @gkatsev. Looking here:

https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/seek-bar.js#L37

It seems like we update the seekbar on `timeupdate` and `ended` and throttle to be called at most once every 50ms. We need to do [~ 15ms if we want 60fps](https://stackoverflow.com/a/27460015/696130). Calling `update` on the `SeekBar` is directly tied to updating the `PlayProgressBar`:

https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/play-progress-bar.js#L42

However, I can't find anywhere where we actually update the width of the `PlayProgressBar`. Could y'all help me find that?

**Comment by vhmth** [comment]
Nevermind I ended up changing that throttle time but it's not doing much. I think it's because the function itself is called on `timeupdate`, which isn't called 60 times a second. We have to set an interval on play and clear it on pause and ended. Tested locally and that seems to do it.

**Comment by apurvgandhwani** [comment]
Was this solved? @gkatsev Please let us know. Because we are still not able to implement it.

**Comment by BrandonOCasey** [comment]
I think this was solved by: https://github.com/videojs/video.js/pull/4591 which has been in every version since `6.5.0`. The progress bar is updated at `60fps`.

**Comment by apurvgandhwani** [comment]
Still it is jumpy.

**Comment by gkatsev** [comment]
Jumpy how? Can you provide a gif or video of how it looks and a reduced test case? How does it look to you videojs.com? Would be good if you could fill out our [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by vhmth** [comment]
@BrandonOCasey the progress bar updates at ~ `33 fps` (just to clarify).

@apurvgandhwani what version of video.js are you using?

**Comment by apurvgandhwani** [comment]
Yes I want it to update at every frame. That is how I can make it's
movement smooth even on 5 sec video. Even on 33 fps, it will look jumpy.
