### ISSUE TITLE
playback hls with AES-128 does not work

### ISSUE THREAD

**Issue by zlm900125** [videojs/video.js#4531]
## Description
Now we playback hls with AES-128 does not work very well.
It told us "VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist". And loading the first .ts with loop.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.just click the link.
https://lmt.blackboard.com.cn/webapps/bb-byresources-BBLEARN/index3.html

### Expected
play the hls very well

### Actual
It cannot playback

### Error output
It told us "VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the final playlist". And loading the first .ts with loop.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
//vjs.zencdn.net/5.19/video.min.js
#### browsers
firefox and IE11
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.8.2/videojs-contrib-hls.js

**Comment by mister-ben** [comment]
This doesn't play on browsers with native HLS support (e.g. Safari), so the problem appears to be with the stream rather than videojs-contrib-hls.
