### ISSUE TITLE
playToggle can't remove attribute 'title'

### ISSUE THREAD

**Issue by Yalhu** [videojs/video.js#4533]
## Description
`controlBar.playToggle.removeAttribute('title')` can't remove playToggle attribute 'title'. And when mouse in ,the title show.
1. But i remove other component attribute 'title' after playToggle.
2. when i call  `controlBar.playToggle.removeAttribute('title')` on console(chrome), it works. 

## Steps to reproduce
``` javascript
controlBar.playToggle.removeAttribute('title');//doesn't work
controlBar.volumePanel.muteToggle.removeAttribute('title');//ok
controlBar.fullscreenToggle.removeAttribute('title');//ok
```

### Expected
playToggle attribue 'titlt' should disappeare when page load ok.
Is there any way to remove attribute 'title' at the beginning of player initialize via options ?

**Comment by Yalhu** [comment]
``` javascript
document.onkeydown=function(e){
  e.whick==32&&arvplayer.controlBar.playToggle.handleClick()
}
```` 
doesn't work too !

**Comment by Yalhu** [comment]
when component above clicked ,title show again . I want to remove attribute:'title'  and show other tips.

**Comment by mister-ben** [comment]
The `PlayToggle`'s `title` will be set each time the video pauses or plays. What are you actually trying to achieve? From the last comment it sounds like you just want to change the text, in which case the native localisation mechanism would be the better way to do it than setting the attribute value.

**Comment by Yalhu** [comment]
I want to remove attribute 'title' so it won't show , because different view on different browser . I set the controlText to a tip for users. But there seems a little problem:
![title](https://user-images.githubusercontent.com/27722787/29054629-c7ead868-7c29-11e7-949c-1d8fd239828f.png)
``` javascript
controlBar.volumePanel.muteToggle.on('mouseover',function(){this.setAttribute('title','')});
controlBar.volumePanel.muteToggle.on('click',function(){this.setAttribute('title','')});
```
After click, attribute 'title' of browser default  behavior will show if mouse have a small range move. Does that mean I should set a `new Button()` rather than default videsjs' component(MuteToggle) to avoid this effect?
