### ISSUE TITLE
using custom CC button behaviour 

### ISSUE THREAD

**Issue by morangil** [videojs/video.js#4537]
## Description
i'm loading my subtitles dynamically, sometimes it can be only 1 track and sometimes more. is there an option when it's only 1 track to disable the CC default open menu and instead make the 'cc' button show immediately the subtitles?  (clicking the button again will hide the subtitles)

i'm using Video.js 6.2.4

**Comment by mister-ben** [comment]
The text tracks control button does not have any option to behave as a simple toggle. You could add a new button to the player instead.

**Comment by morangil** [comment]
thanks
