### ISSUE TITLE
Video progress bar does not show up

### ISSUE THREAD

**Issue by kasperslusarczyk** [videojs/video.js#4538]
## Description
I have an issue with html videos on Chrome. Whenever I play video (with type video/webm; codecs=vp8) at the beginning of the video I see live mode on and no progress bar. The situation is changing at the end of the video - live mode disappear and the progress bar shows up. It looks like it is a problem with preloading the video but maybe it is related to video.js.

<img width="467" alt="screenshot" src="https://user-images.githubusercontent.com/11523252/28917255-44e44b3a-7845-11e7-9d30-6bf104e324d6.png">

### Expected
I would like to have progress bar working, start to finish
### version
5.11.6
#### browsers
Chrome
#### OSes
macOS Sierra

**Comment by mister-ben** [comment]
The live controls are triggered by the video duration having a duration of `infinity` (or a negative value), so it's most likely bad metadata in the source.
