### ISSUE TITLE
RTMP video show only in small top left in the player

### ISSUE THREAD

**Issue by vitordangelo** [videojs/video.js#4539]
## Description
Hi! I have a problem when execute RTMP (type: video/x-flv) video.
The size of player is 300x300px but the video is only small square in top left side player.
![Screen](https://s3-sa-east-1.amazonaws.com/v2share-s3/883883.png)

## Steps to reproduce
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  
  <!-- Old version compatible with flash -->
  <!-- <link href="//vjs.zencdn.net/5.19/video-js.min.css" rel="stylesheet">
  <script src="//vjs.zencdn.net/5.19/video.min.js"></script>   -->

  <!-- New version uncompatible with flash -->
  <link href="http://vjs.zencdn.net/6.2.4/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/6.2.4/video.js"></script> 
  <script src="./videojs-flash.min.js"></script>
  <script> videojs.options.flash.swf = './video-js.swf'; </script>
</head>

<body>
  <video id="my-player" class="video-js">
    <source src="http://52.67.154.16:6604/rtmp/1501786585151/?M2MwOWNiMWQtZWQwNi00OTExLWI5ZDEtYjE1YzVjZmVkYmI3LDEsMTExMTExMSwwLDEsMCww" type="video/x-flv"></source>
  </video>
</body>

<script>
  videojs('my-player', {
    controls: true,
    autoplay: true,
    preload: 'metadata',
    flash: {
      swf: './video-js.swf'
    },
    height: 300,
    width: 300,
    poster: 'https://s3-sa-east-1.amazonaws.com/v2share-s3/logo-v2tech.jpg',
    language: 'pt'
  });
</script>

<script>
  videojs.addLanguage('pt', {
  'Play': 'Iniciar',
  'Pause': 'Pausa',
  'Current Time': 'Tempo de Reprodução',
  'Duration Time': 'Duração Total',
  'Remaining Time': 'Tempo Restante',
  'Mute': 'Mudo'
})
</script>

</html>
```

### Expected
Video full in the player, not only small square in top left.

### Actual
Please describe what actually happened.

### Error output
The size of player is 300x300px but the video is only small square in top left side player.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
  <link href="http://vjs.zencdn.net/6.2.4/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/6.2.4/video.js"></script> 
  <script src="./videojs-flash.min.js"></script>
  <script> videojs.options.flash.swf = './video-js.swf'; </script>
#### browsers
Tested in Chrome 60 and Firefox
#### OSes
Ubuntu 17.04 and Windows 10

**Comment by mister-ben** [comment]
There's a PR for a potential fix in https://github.com/videojs/video-js-swf/pull/229

**Comment by biswajitmuvi** [comment]
Hi,

I have also got exact same problem. Could you please help me to solve the issue.
