### ISSUE TITLE
No compatible source was found for this media.

### ISSUE THREAD

**Issue by firofame** [videojs/video.js#4540]
```
<head>
  <link href="http://vjs.zencdn.net/6.2.4/video-js.css" rel="stylesheet">

  <!-- If you'd like to support IE8 -->
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
    <source src="http://smumcdnems03.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Star_Vijay/Star_Vijay_400.m3u8" type='application/x-mpegURL'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="http://vjs.zencdn.net/6.2.4/video.js"></script>
</body>
```
what am i doing wrong? Thanks in advance.

**Comment by mister-ben** [comment]
You need to add [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) to play HLS on browsers without native support.

**Comment by firofame** [comment]
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.8.2/videojs-contrib-hls.js"></script>
<script src="http://vjs.zencdn.net/6.2.4/video.js"></script>

<video width=600 height=300 controls>
	<source src="http://smumcdnems03.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Star_Vijay/Star_Vijay.m3u8" type="application/x-mpegURL">
</video>
```

i tried adding videojs-contrib-hls. still its not working

**Comment by mister-ben** [comment]
That source returns a server error, `405 not allowed`. If you're getting a non-error response, the most common cause of not being able to play HLS is the server not sending [CORS headers](https://enable-cors.org).

**Comment by firofame** [comment]
i don't have access to the server. is there some way to bypass CORS

**Comment by mister-ben** [comment]
I've seen some try to use CORS proxies, but that does not work and perform well (if at all) with segmented media. You really do need to get the server sending the right headers.

**Comment by gkatsev** [comment]
Yeah, unfortunately, not much we or you can do if the right headers aren't set.

**Comment by moeinomidii** [comment]
i used "contrib-hls" .  is it fine or not?
ERROR CODE : 4 (Without Flash)
