### ISSUE TITLE
Infinite pending request (Chrome)

### ISSUE THREAD

**Issue by SBoudrias** [videojs/video.js#455]
Hi, I found an issue with some infinite pending request on Chrome. This seems related to the HTML5 video elements has it happens on Video-js, but also any other HTML5 video player I can found out there (media-element, etc)

I explained the bug more clearly over StackOverflow: http://stackoverflow.com/questions/16137381/html5-video-element-request-stay-pending-forever-on-chrome

**Comment by booherbg** [comment]
Believe it or not, this works for me. I just have to execute this before any new video is added. NOTHING ELSE worked for me.

``` javascript
	// this hack clears up any pending socket issues. damn it chrome.
	if(window.stop !== undefined) {
	    window.stop();
	} else if(document.execCommand !== undefined) {
	    document.execCommand("Stop", false);
	}
```

**Comment by thomasbrodin** [comment]
@booherbg This worked for me too! Thanks for sharing!

**Comment by Adoratus** [comment]
@booherbg Thank you! It works!

**Comment by vin-ni** [comment]
This didn't work for me unfortunately. (I'm using just the video tag and replacing the src dynamically)
I had to set `preload` to `none`.

**Comment by jayarjo** [comment]
Bumped on this today. Common Chrome, employer blames this shit on me! It's bloody 2019.

**Comment by simbrams** [comment]
@jayarjo have you found a workaround for this? I'm facing the same issue in 2021.
