### ISSUE TITLE
Version 5.20.2 does not appear to be published on zencdn

### ISSUE THREAD

**Issue by fwilkens** [videojs/video.js#4552]
## Description
I may be missing something, but I don't see that 5.20.2 is published on the zencdn. Should it be?

## Steps to reproduce
Visit http://vjs.zencdn.net/5.20.2/video.min.js

Earlier versions are available, for example http://vjs.zencdn.net/5.20.1/video.min.js

### Expected
Expect that 5.20.2 is available via CDN. Brightcove player 5.24.3 appears to be targeting 5.20.2.

### Actual
It appears to not be hosted/published/public as far as I can tell.

#### videojs
5.20.2

**Comment by gkatsev** [comment]
This should be available on the CDN now. We don't always release new releases on the CDN immediately on publish as they're published to npm as `next` (or `next-5`). It stays in that state for around a week and unless there are major issues it is then promoted to `latest` (or `latest-5`). At that point it is definitely published to the CDN.
