### ISSUE TITLE
Div on front in Fullscreen mode

### ISSUE THREAD

**Issue by Arkentus** [videojs/video.js#4554]
## Description
For a e-learning portal, i want to show a popup on front for check If customer is present.  On fullscreen mode, i can't show my <div> (popup) on front of user. 

I try to change all z-index (my popup / your player) but no success. How can i do it ?

Thx for your job, this plugins is very great !

**Comment by mister-ben** [comment]
Your div would only show in fullscreen if it were a child of the element that is fullscreen, i.e. the player. You could use a modal for this http://docs.videojs.com/tutorial-modal-dialog.html

**Comment by Arkentus** [comment]
Godness ! Modal .. I've not think at this keyword .. Thank you very much !
