### ISSUE TITLE
Click on video to not pause in Android device.

### ISSUE THREAD

**Issue by huangyanbin** [videojs/video.js#4557]
## Click on video to not pause in Android device.
I use video.js to play video, on the PC side, the video is playing, click on the middle of the video, it can pause, but when I'm at the android device, click on the middle of the video, trying to pause the video invalid. I suspect that there may be no mouse event on the mobile side, only the touch event. I tried to add click event  for player or video, but without any effect. Thank you very much for your help.

**Comment by huangyanbin** [comment]
Thank you. I've found a solution. Add a code in player  protoype handleTechTap_ . When the control bar is activated, click the middle of the video to pause.
`b.prototype.handleTechTap_ = function () {
                        if(this.userActive_) this.controls() && (this.paused() ? this.play() : this.pause());
                        this.userActive(!this.userActive())`

**Comment by gkatsev** [comment]
This is actually a design decision. To make a consistent experience on mobile devices and given that the controls are overlayed over the player we decided that tapping on mobile should toggle the control bar rather than toggle playback state.
Glad you figured out a workaround.
