### ISSUE TITLE
Streaming a 4k mp4 file h.264 compression from wowza shows a stutter? has any body seen this?

### ISSUE THREAD

**Issue by nlattupalli** [videojs/video.js#4563]
## Description
Briefly describe the issue.
I have a 4k mp4 file , when trying to stream the video to videojs player, the video stream stutters

**Comment by gkatsev** [comment]
It probably isn't an issue with the wowza stream but rather the browser and hardware you're streaming to. Older browsers would have much more trouble playing back 4k content even on beefy hardware. 4K content requires quite a lot of power to be able to display smoothly.
Not sure there's anything we can do about it.

**Comment by nlattupalli** [comment]
Hello,
Initially i also thought the same but found out that woza streams fine to the Wowza player, jwflash player .
Video js is only where we see this stutter
