### ISSUE TITLE
The first two ts section requests are not played in Safari

### ISSUE THREAD

**Issue by kobe0116** [videojs/video.js#4566]
## Description
The first two ts section requests are not played in Safari

Please include any additional information necessary here. Including the following:
#### videojs 6.2.0

####Safari

**Comment by gkatsev** [comment]
Safari uses native HLS playback. We have no control over what is included or not. Have you tried Apple's Media Stream Validator tool to see if your stream has issues? You can try to see if it plays on [this page](http://videojs.github.io/videojs-contrib-hls/) in chrome using our videojs-contrib-hls plugin.

**Comment by kobe0116** [comment]
Thank you for your advice, Google Chrome video playback is normal, try to set up the videojs. Options. HLS. OverrideNative = true;
Videojs. Options. HTML 5. NativeAudioTracks = false;
Videojs. Options. HTML 5. NativeVideoTracks = false;
It was found that normal video could be played, but the video broadcast area showed the following display:
![image](https://user-images.githubusercontent.com/18303048/29346187-2e160d18-8276-11e7-942c-8e6f1e27dc39.png)

**Comment by gkatsev** [comment]
You're trying to use contrib-hls on Safari? We haven't really tested that I don't think. Would you be able to open up a detailed issue with a reduced test case against the [contrib-hls repo](https://github.com/videojs/videojs-contrib-hls/issues/new) if you are using contrib-hls?
