### ISSUE TITLE
Audio File not showing the poster

### ISSUE THREAD

**Issue by lekhrajgit** [videojs/video.js#4571]
## Description
Briefly describe the issue.

![poster_js](https://user-images.githubusercontent.com/22751525/29380078-84b0d8e4-8292-11e7-9dcf-ea181609c48c.png)
![pster_html](https://user-images.githubusercontent.com/22751525/29380077-84b0043c-8292-11e7-8fa0-160bd0f73109.png)
![poster_issue](https://user-images.githubusercontent.com/22751525/29380079-84b1c01a-8292-11e7-8360-6aa4dc418ee8.png)

Audio File not showing the poster
version 6.2.5

**Comment by OwenEdwards** [comment]
Try using a `<video>` tag instead of an `<audio>` tag. The rendering of a `poster` or `text track` on an `<audio>` element is a bit ambiguous in the HTML spec - we talked to a member of the W3C group that wrote the spec for this, and using a `<video>` tag instead is their recommended solution.

**Comment by lekhrajgit** [comment]
Thank you @OwenEdwards for taking a look on this but it still doesn't work on mp3 file but it works on mp4

![video](https://user-images.githubusercontent.com/22751525/29530779-61cf1004-8673-11e7-8ed2-289ef52c0ce1.png)
![audio](https://user-images.githubusercontent.com/22751525/29530780-61d0a036-8673-11e7-8ec1-53a50816091f.png)

**Comment by lekhrajgit** [comment]
Anybody having similar issue ?

**Comment by codex-corp** [comment]
@lekhrajgit check this https://github.com/videojs/video.js/issues/2777#issuecomment-252796887

**Comment by lekhrajgit** [comment]
Thank you :+1:
