### ISSUE TITLE
React Video Resolution change

### ISSUE THREAD

**Issue by mrmaan4u** [videojs/video.js#4575]
## Description
I was trying to change video quality 1080(FDH), 720(HD) and 480(SD) manually and auto depending on user bandwidth. I have been looking all around web but not finding anything helpful. Can anybody help me out on this one.

### versions
I am using Video Js version 5.8

**Comment by gkatsev** [comment]
If you are using mp4s, there isn't really a good way of doing it automatically. You should instead look at an adaptive bitrate format like HLS and DASH and then use [contrib-hls](https://github.com/videojs/videojs-contrib-hls/) or [contrib-dash](https://github.com/videojs/videojs-contrib-dash).

Hope that helps.
