### ISSUE TITLE
Flash-based content not displaying captions.

### ISSUE THREAD

**Issue by mparisi76** [videojs/video.js#4576]
I apologize if this is not the right place to post this, I'm not sure where to turn. I can't get closed captioning to work with flash media. I see the menu button in the control bar and when I select the captions from that menu, nothing shows up. I am able to see the captions when viewing an HLS pre-recorded stream. Any direction would be greatly appreciated. Thank you!

**Comment by mister-ben** [comment]
A reduced test case to demonstrate would help understand what's happening.
