### ISSUE TITLE
Initialize player by class

### ISSUE THREAD

**Issue by blackflow** [videojs/video.js#4581]
Question:
Is it possible to use class instead of id?
var player = videojs('my-video');

We have a feed with videos and each one has unique ID so it's not possible to call it by ID.  
I found this in documentation but it only allows me to call a specific video.

videojs(document.getElementsByClassName('awesome_video_class')[0], {}, function() {
  // You can grab an element by class if you'd like, just make sure
  // if it's an array that you pick one (here we chose the first).
});

How I can target all videos on the page? I want to use some plugins but can't do it for all videos.

**Comment by mister-ben** [comment]
You could [iterate through the NodeList returned by`getElementsByClassName`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach), but this sounds like a good use for Video.js's  [setup hooks](http://docs.videojs.com/tutorial-hooks.html):

```js
videojs.hook('setup', function(player) {
  player.somePlugin();
});
```

**Comment by gkatsev** [comment]
Hooks sounds like a great contender as @mister-ben mentioned, as well as looping through the response from `getElementsByClassName` or `querySelectorAll`.
