### ISSUE TITLE
change the order of the controlbar button that has been added from other plugins

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/video.js#4584]
## Description
i am using plugins like videojs-hls-source-selector that add button(ResolutionButton) to the control bar i am trying to change the place of this button to be placed before the full screen button using the following code but it doesn't work. if you change the location of built in button it works but not for custom button. i am using videojs version 6.2.5

```
videojs.getComponent('ControlBar').prototype.options_ = {
                                children: [
                                    "playToggle",
                                    "volumePanel",
                                    "currentTimeDisplay",
                                    "timeDivider",
                                    "durationDisplay",
                                    "progressControl",
                                    "liveDisplay",
                                    "remainingTimeDisplay",
                                    "customControlSpacer",
                                    "playbackRateMenuButton",
                                    "chaptersButton",
                                    "descriptionsButton",
                                    "subsCapsButton",
                                    "audioTrackButton",
                                    "chromeCastButton",
                                    "ResolutionButton",
                                    "fullscreenToggle"
                                ]
                            }
```

thanks,

**Comment by Morkowski** [comment]
You can change it by using flex order. But there is another problem with this approach. Flex order change visual order, but html order stays the same. When you change focused element with your keyboard (TAB key) it keeps order defined by HTML. Tab index is scoped globally, so it is not right solution.

Read more here: http://adrianroselli.com/2015/10/html-source-order-vs-css-display-order.html

Any idea how to inject elements with right order without using flexbox?

**Comment by gkatsev** [comment]
A lot of plugins add the buttons manually so using the `children` array won't be a viable option.
As @Morkowski, you can use the flex css `order` property to position things as you want. Otherwise, you can also use js to reposition the components where you want.
Another option is to re-order your plugin initialization order so the plugins add their buttons in a different order.

Hope that helps.
