### ISSUE TITLE
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

### ISSUE THREAD

**Issue by qnlpkuge1** [videojs/video.js#4587]
## Description
I am having problems watching videos in some webpages. I get the error "The media playback was aborted due to a corruption problem or because the media used features your browser did not support.". This only happens on certain websites,  The problem startet a couple of weeks ago, and i cant seem to find a fix on the web. Any suggestions on how to fix this?

## Steps to reproduce
When using VideoJS HLS, I always open the Developer Tool in Chrome to
find errors :)

I also use h264 which has support to
generate HLS stream. I can watch the generated HLS stream in Safari.
Unfortunately, I got the following errors in Chrome:

VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was
aborted due to a corruption problem or because the media used features
your browser did not support.

### Actual
just like this:

https://www.snotr.com/video/18694/Wrong_Place_Wrong_Time

**Comment by mister-ben** [comment]
Please use the issue template and provide a reduced test case. It's hard to give any meaningful help without more specific information. Thanks

**Comment by qnlpkuge1** [comment]
thanks for help

**Comment by morkov4o** [comment]
is this already fixed ?

**Comment by gkatsev** [comment]
The original post provides very little data to be able to help. The example does work most of the time but uses a very old version of Video.js and likely an old version of contrib-hls. There have been a lot of updates to both since.

**Comment by chianhsieh** [comment]
Hello,

I also faced this problem after I upgraded to Chrome 64.0.3282.119.
Here are the details about the errors: 
( I used the latest version which are Videojs 6.6.3 and videojs-contrib-hls 5.12.2 )

`VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. MediaError {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}`

`VIDEOJS: ERROR: (CODE:-3 undefined) Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null. `

And more details about the above errors:

```
MediaError {code: -3, type: "APPEND_BUFFER_ERR", message: "Failed to execute 'appendBuffer' on 'SourceBuffer'…The HTMLMediaElement.error attribute is not null.", originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribu…}code: -3message: "Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null."originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
    at Object.wrapper.(anonymous function) [as appendBuffer] (/js/videojs-contrib-hls.js.2:19810:34)
    at VirtualSourceBuffer.concatAndAppendSegments_ (/js/videojs-contrib-hls.js.2:20527:29)
    at VirtualSourceBuffer.processPendingSegments_ (/js/videojs-contrib-hls.js.2:20475:14)
    at VirtualSourceBuffer.done_ (/js/videojs-contrib-hls.js.2:20202:12)
    at Worker.VirtualSourceBuffer.transmuxer_.onmessage (/js/videojs-contrib-hls.js.2:20013:22)code: 11message: "Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null."name: "InvalidStateError"stack: (...)get stack: ƒ nativeGetter()set stack: ƒ nativeSetter()__proto__: DOMExceptiontype: "APPEND_BUFFER_ERR"__proto__: Object
logByType @ videojs.6.6.3.js:498
log.error @ videojs.6.6.3.js:620
error @ videojs.6.6.3.js:23525
concatAndAppendSegments_ @ videojs-contrib-hls.js.2:20530
processPendingSegments_ @ videojs-contrib-hls.js.2:20475
done_ @ videojs-contrib-hls.js.2:20202
VirtualSourceBuffer.transmuxer_.onmessage @ videojs-contrib-hls.js.2:20013
```

Could any one have any ideas on this? 

Many Thanks.
