### ISSUE TITLE
On volume change with javascript bar always 100%

### ISSUE THREAD

**Issue by nik0s100** [videojs/video.js#4590]
## Description
When I'm using .volume to change volume with javascript the bar stays always at 100% but the sound is where I choose to be with javascript

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
6.2.7
what version of videojs does this occur with?
Any
what browser are affected?
#### OSes
Any
### plugins
videojs-hotkeys

**Comment by thijstriemstra** [comment]
Also when you disable the `videojs-hotkeys` plugin?

**Comment by damongant** [comment]
This is something we're seeing when volume is set before the `playing` event. We persist player volume in local storage and set it as soon as the player signals ready, leading to this bug. Our workaround was simply to set the volume to itself on `playing`.

**Comment by gkatsev** [comment]
I am unable to reproduce. Can you provide a reduced test case? Testing with Video.js 6.5.0.

**Comment by damongant** [comment]
(Not involved with that project anymore; CC: @silvea12 )
