### ISSUE TITLE
How can I detect the video is stuck and load fail?

### ISSUE THREAD

**Issue by etc1208** [videojs/video.js#4596]
In my recent project, i use video.js to play video,include live and recorded video.
Now I have a problem，I need to statistical video failure load for the first time,and how many times the video is stuck in every 2 minutes? 
I have try some ways, use events of video ，but i find my way is not accurate

**Comment by xunSweet** [comment]
你们的说的话，我听不懂

**Comment by gkatsev** [comment]
If the video failed to load completely, you should get an `error` event with one of these types: http://docs.videojs.com/MediaError.html#.errorTypes
If it's just taking a while to load you could get `stalled` event. Hope that helps.

**Comment by apurvgandhwani** [comment]
@gkatsev is there any event listener for video buffering? For example, in slow internet, video pauses and loads, I want a listener for such events.

**Comment by TeresaHsieh** [comment]
@apurvgandhwani maybe what you are looking for is `waiting` and  `canplay` event?

**Comment by xunSweet** [comment]
Are you foreigner?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Teresa Hsieh"<notifications@github.com&gt;; 
发送时间: 2020年4月10日(星期五) 下午3:24
收件人: "videojs/video.js"<video.js@noreply.github.com&gt;; 
抄送: "狼、吻~"<1172618241@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [videojs/video.js] How can I detect the video is stuck and load fail? (#4596)





 
@apurvgandhwani maybe what you are looking for is waiting and  canplay event?

**Comment by apurvgandhwani** [comment]
> @apurvgandhwani maybe what you are looking for is `waiting` and `canplay` event?

Will it catch when the video is stuck because of say slow internet.
