### ISSUE TITLE
Support NOTE and classes in vtt files

### ISSUE THREAD

**Issue by rcrooks** [videojs/video.js#460]
I'm finding these issues with .vtt files:
- NOTE comments are not respected (treated as part of text)
- \<c.class> not respected (appears classes are ignored)

**Comment by gkatsev** [comment]
This may have been fixed by 4e5c28cc561487ff29394d19dce3a420675e4f9d

**Comment by gkatsev** [comment]
I'm going to close this for now but if it isn't fixed in the latest version please let us know and we can re-open this issue.
