### ISSUE TITLE
Video not rendering in Desktop Mode, but renders in mobile

### ISSUE THREAD

**Issue by rdh755** [videojs/video.js#4606]
Hello,

I'm creating a responsive application that uses videoJS that is responsive. I've created three templates for my application: Left (Video on left side), Right (Video on right side) and full. I've tested videoJS and it works on Left and full for the responsive design. However I'm running into a problem w/ my right template.

When the browser is in desktop mode, my video shows up as a black box. When I shrink the browser to a mobile mode, the video shows up. Just to let you know, I am using videoJS and videoJS HLS.

**Comment by gkatsev** [comment]
Are you using fluid mode in Video.js? Try switching to fill mode instead? `vjs-fill` instead of `vjs-fluid`.

That's the most I can probably help without a live reduced test case.

**Comment by rdh755** [comment]
I'm using the vjs-16-9. It loads in my left template (Desktop & Mobile), but not in my right template (Mobile). I will let u guys know if it works when a video is queued up.

**Comment by rdh755** [comment]
Well, it's not working. It's like the the video isn't event rendering. When it's in desktop mode.

**Comment by rdh755** [comment]
I do get the following warning: video player already initialised. Options will not be applied. Maybe this is what's preventing it to work.

**Comment by rdh755** [comment]
Figured it out, it wasn't an issue w/ my template. I had to dispose the settings and reset them.

**Comment by gkatsev** [comment]
Oh, cool. Glad you figured it out!
