### ISSUE TITLE
Rounding errors with player.remainingTime() 

### ISSUE THREAD

**Issue by treyhoover** [videojs/video.js#4608]
## Description
Demo of the problem here: [http://jsbin.com/caderis/1/edit?js,output](http://jsbin.com/caderis/1/edit?js,output)

It seems the best solution would be to make `player.remainingTime` take an argument for the number of significant figures, or even a rounding function to use. Then it can properly round the remainingTime to be consistent with other time labels. This is important any time you're displaying remainingTime, as there's currently no way to use `remainingTime` anywhere in our app and have it be consistent with the other (pre-rounded) time labels.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Display the `.vjs-time-control` component
2. Note that currentTime + remainingTime !== duration (visually)

### Expected
I expect time labels to appear consistent to the user.

### Actual
Rounding errors cause time labels to be inconsistent at times.

#### videojs
6.2.5

Happy to help and submit a PR if you can give me some direction as to how you'd like to address this. Something like this would probably be most versatile:

```
  /**
   * Calculates how much time is left in the video. Not part
   * of the native video API.
   *
   * @param {function}
   *        - an optional rounding function
   *
   * @return {number}
   *         The time remaining in seconds
   */
  remainingTime(roundFn) {
    const round = typeof roundFn === "function" ? roundFn : (x) => x; // noop (default)

    return round(this.duration()) - round(this.currentTime());
  }
```

```
// now if we need the remaining time to display visually, we can do this:
const remainingTime = player.remainingTime(Math.floor);
```

But simply fixing the value shown in the `vjs-remaining-time-display` component would be an improvement.

**Comment by gkatsev** [comment]
Let me see if I am understanding you correctly. You're saying that because the currentTime display and the duration display each end up rounding, the remaining time display ends up looking weird because it does its rounding after doing the subtraction and so the display values of currentTime plus remainingTime do not always add up to the duration due to rounding errors?

I wonder if we should just change the remaining time display to not use `player.remainingTime`? Not sure which option is better.

**Comment by treyhoover** [comment]
> Let me see if I am understanding you correctly. You're saying that because the currentTime display and the duration display each end up rounding, the remaining time display ends up looking weird because it does its rounding after doing the subtraction and so the display values of currentTime plus remainingTime do not always add up to the duration due to rounding errors?

Yep - exactly.

I wasn't sure which option is better either. Though I will say that I currently need to use `remainingTime` for other things (like a countdown for an ad) and need this same behavior. `remainingTime` ends up being pretty useless for me the way it's calculated now so I end up having to ignore it and use a new function. Anyone else using the `remainingTime` value visually will likely run into a similar problem of perceived accuracy/synchronization.

**Comment by gkatsev** [comment]
Another idea I just had is to have it `remainingTime` do the rounding that matches what is done elsewhere given a passed in option.
@videojs/core-committers any thoughts?

**Comment by gkatsev** [comment]
To clarify my last option, it'll mean that if we pass the option to `remainingTime`, we are telling it we're going to be using the value from it for display purposes, so, it should do the `floor(duration()) - floor(currentTime())`. The potential benefit of this is that videojs users that want to use `remainingTime` for display won't need to know that `Math.floor` is used.

**Comment by treyhoover** [comment]
@gkatsev Yep, that's another option I was playing with. If we go with the significant figures/numDecimals approach we can do something like `remainingTime(0)` and have it round for you using the same rounding function used elsewhere.

**Comment by gkatsev** [comment]
What are your thoughts on #4620?

**Comment by treyhoover** [comment]
👍  That's probably the simplest solution.
