### ISSUE TITLE
About switching between SD and HD for mp4 ?

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#4610]
Hola!  
When using two MP4 files, SD and  HD ..  how to make a simple switch between them? So that the user can switch the quality himself!  Not everyone can watch in high quality ..
   Videojs version  5.20.3

Thanks Advance!  
Regards!

**Comment by gkatsev** [comment]
You'd want to use a plugin like [videojs-resolution-switcher](https://github.com/kmoskwiak/videojs-resolution-switcher). Video.js doesn't have functionality like that built into core.

**Comment by surikat1978** [comment]
Unfortunately this plugin is not working ..
