### ISSUE TITLE
Disable right click seek videojs

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#4611]
I want to disable right-click seek video, https://github.com/videojs/video.js/issues/4120 doesn't help disable right click seek

**Comment by gkatsev** [comment]
How do you right-click to seek? But we might want to update our code that handles seek to make sure that we only consider left clicks.

**Comment by kocoten1992** [comment]
I'm using v5.20, doesn't do anything special, it was right clickable seek by default

**Comment by gkatsev** [comment]
Oh, when I tried it earlier it didn't work but was able to get it to work after trying again.
Yup, sounds like we need to update our slider component to only work with the left click rather than any click event. Would you be interested and able to work on this, @kocoten1992?

**Comment by kocoten1992** [comment]
ye, I'll fix it, my project need that too

**Comment by kocoten1992** [comment]
Fixed :+1:

**Comment by asd29696** [comment]
Chuong <notifications@github.com> 於 2017年11月17日 週五 15:36 寫道：
