### ISSUE TITLE
Add a custom button on/off to control Bar 

### ISSUE THREAD

**Issue by anoosi** [videojs/video.js#4621]
i have no good experience  to deal with js
so, as the title i just need make a toggle button on/off to this plugin JavascriptSubtitlesOctopus
https://dador.github.io/JavascriptSubtitlesOctopus/videojs.html
the plugin work on videojs 5.*,
i need it to rendering ass subtitles, its work perfectly with videojs 
but there is not a button to off or on the subtitles, i googled and tried to create costume button but failed!
here is the code
--
  |  var video = this.tech_.el_;

  | window.SubtitlesOctopusOnLoad = function () {
  | var options = {
  | video: video,
  | subUrl: '/JavascriptSubtitlesOctopus/test.ass',
  | fonts: ['/JavascriptSubtitlesOctopus/font-1.ttf', '/JavascriptSubtitlesOctopus/font-2.ttf'],
  | //onReady: onReadyFunction,
  | //debug: true,
  | workerUrl: '/JavascriptSubtitlesOctopus/subtitles-octopus-worker.js'
  | };
  | window.octopusInstance = new SubtitlesOctopus(options); // You can experiment in console
  | };
  | if (SubtitlesOctopus) {
  | SubtitlesOctopusOnLoad();
  | }

thanks.

**Comment by anoosi** [comment]
i need a button to hide and show div class vjs-ass libjass-wrapper!

**Comment by asd29696** [comment]
2017年9月17日 下午12:25，"anoosi" <notifications@github.com>寫道：
