### ISSUE TITLE
Delay in showing live stream after stop/restart

### ISSUE THREAD

**Issue by jabulon** [videojs/video.js#4638]
## Description
I'm using nginX+RTMP module to stream live video. As part of my solution, the stream is often stopped and then restarted after a few seconds. The issue is: sometimes, it takes the player a very long time (3-30 secs) to register that the stream is restarted, and keeps on showing the last frame of the previous video until so. If I'm using ffplay to connect to the stream during this time, I see that the stream is alive.
Important note: I'm using the flash player, and not the HTML5 one - which I was unable to get to play rtmp (is it even supported?)
The version I'm using is 5.10.2. I've tried using. I've tried to use version 6.2.7 (video.js), but couldn't find the flash portion of the player (video-js.swf)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play an existing RTMP stream
2. Kill the stream and start it anew
3. Look at the status of the player

### Expected
The player picks up the restarted stream

### Actual
It sometimes takes the player half a minute to show the stream again

### Error output
If there are any errors at all, please include them here.

#### browsers
FF54, Chrome 61
#### OSes
Windows 10

**Comment by gkatsev** [comment]
RTMP cannot be played outside of flash. Also, Video.js 6 does support flash but it requires a separate plugin, where-as it was built-in previously. Have you tried a newer 5.x version? The latest is 5.20.3 currently.
However, this probably is an issue with the swf itself, if it's an actual issue and not just how it works. Probably needs to be opened against the swf repo.
In addition, RTMP and Flash are slowly going away and it's low priority for the maintainers.

**Comment by gkatsev** [comment]
Closing because of lack of a response.
