### ISSUE TITLE
Issue with the video content width

### ISSUE THREAD

**Issue by Syiok** [videojs/video.js#4645]
I tried different browsers and some browsers have some problem with the video content being 'cut'
attached the code. (It's working fine at my chrome but not opera)

Opera
![image](https://user-images.githubusercontent.com/32477335/31162787-e09f75b6-a911-11e7-979e-1a68841a5b0f.png)

Chrome
![image](https://user-images.githubusercontent.com/32477335/31162812-0380f1cc-a912-11e7-9fd1-9c9a874bf75a.png)

code:
http://jsbin.com/jiniyozoxa/edit?html,output

**Comment by Syiok** [comment]
Found the problem. When cast it can only cast certain resolution... else will have this problem

**Comment by hoodsy** [comment]
@Syiok what's the issue, were you able to get around it?

**Comment by gkatsev** [comment]
Sounds like this has been fixed? Also, does this issue occur with the latest versions of all the plugins at this point?
I'm going to close this issue for now, please open a new one if it's still a problem. Thanks.
