### ISSUE TITLE
v6.3.1 missing dist folder

### ISSUE THREAD

**Issue by vacchi** [videojs/video.js#4646]
Hello,

on bower released v6.3.1 is missing the dist folder. 
Can we not have it instead to install npm dependencies and have run grunt?

thanks

**Comment by gkatsev** [comment]
Video.js 6 has dropped bower support. #4012, #4238, #4465. We're not planning to bring it back because it is a maintenance burden for us.
You can grab the release files from github releases or use the bower npm plugin.

**Comment by vacchi** [comment]
ok thanks
