### ISSUE TITLE
Modal dialog open on Iphone/Ipad - safari, embed video gets page scrolled 

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/video.js#4653]
Hi,

when the player is embeded in iframe and i click a button to open modal dialog the page get scrolled. the following function is causing the scroll. 

this.focus() is the problem.

  ```
ModalDialog.prototype.conditionalFocus_ = function conditionalFocus_() {
    var activeEl = document_1.activeElement;
    var playerEl = this.player_.el_;

    this.previouslyActiveEl_ = null;

    if (playerEl.contains(activeEl) || playerEl === activeEl) {
      this.previouslyActiveEl_ = activeEl;     
      this.focus();

      this.on(document_1, 'keydown', this.handleKeyDown);
    }
  };
```

**Comment by Elemb** [comment]
Hi,
Have you noticed that this bug also happens when you play the player?

**Comment by ahmadawada11** [comment]
Hi i had the same problem for play button but it was from the hotkey plugin so i stop it on mobile and now the play button working fine without the scroll issue.

**Comment by Elemb** [comment]
@ahmadawada11 This happens not only when you just click, but just when the play event is triggered, and the player is not fully on the screen
for example test here http://elemb.com/projects/yaplakal/html5player/dist/app/tests/demo.php
scroll to third player, but don't center the player full on screen, make it like that [sample](http://joxi.ru/Y2L6dMes9jn9Xr)

**Comment by gkatsev** [comment]
This is due to a longstanding iOS bug where when you call `focus()` on an element in an iframe, it will scroll, even if that element is in the viewport already.
One idea we've had is to change our calls to focus to basically be no-ops when we're on iOS and an iframe. Kind of like we did in https://github.com/videojs/video.js/pull/4607.
