### ISSUE TITLE
Safari buffering issue (multiple versions)

### ISSUE THREAD

**Issue by nurdyguy** [videojs/video.js#4656]
I'm not sure if this is related to the other Safari issues but if you are playing a video, then pause it, then switch tabs (or in any way move the video's tab back so it is not the focus) then any current .ts request will be cancelled.  When you do go back to the video's tab, the entire process starts over (beginning with the m3u8 requests).  

This is a significant issue if the requests are time limited (for security reasons) as the new request line will fail.

## Steps to reproduce
1. Go to http://videojs.com/ 
2. Open the networks tab.
3. Start the video, then pause it. 
4. Go to a different tab in the browser. You will notice that any .ts requests are cancelled.
5. Return to the video's tab.  Notice the m3u8 requests are fired and the entire set of .ts requests begins again.

This is happening on multiple versions of Safari and for multiple versions of video.js.

**Comment by mister-ben** [comment]
The video at videojs.com isn't HLS, but this is reproducible with an HLS source.

This is a (new?) behaviour of Safari's native playback. You could try using [`overridenative`](https://github.com/videojs/videojs-contrib-hls/blob/master/README.md#overridenative) with videojs-contrib-hls to force playback in MSE.

**Comment by nurdyguy** [comment]
In some cases we override to use hls.js and this does solve this issue.  However, it has two drawbacks:
  1.  iOS doesn't have MSE and the issue does exist on iOS Safari
  2.  We would prefer to be able to take advantage of HEVC when possible

**Comment by gkatsev** [comment]
You can override it everywhere except iOS. Unfortunately, this is just how the browser works and there's nothing we can do about this.
It would probably be good to maybe increase the TTLs on the segments/manifests (within reason) to better support safari.
