### ISSUE TITLE
black line on right side, only happened in windows desktop

### ISSUE THREAD

**Issue by lanxan** [videojs/video.js#4658]
## Description
Hi I using videos js Video.js v4.12.11.
The black line on the right side like this, this happens only in the Windows desktop.
mac, linux and notebook is work fine.

I don't konw what happened, please help me.
Thanks!

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. enter [video link](https://ani.gamer.com.tw/animeVideo.php?sn=8790)
2. click "同意", the left button

### Expected
no black line

### Actual
![image](https://raw.githubusercontent.com/lanxan/image/master/22426120_1431522153609673_1770719137_o.png)

#### videojs
v4.12.11.
#### browsers
chrome
#### OSes
windows 10

**Comment by kocoten1992** [comment]
```
code: 11
message: "Our Services are available in Taiwan."
```

Could you try follow the black line to find what css line causing that (due to the error, wasn't able to)

**Comment by lanxan** [comment]
Our designer thought the problem maybe with the browser render.
