### ISSUE TITLE
Last frame picture gets pixelated

### ISSUE THREAD

**Issue by bozolozo** [videojs/video.js#4666]
Dear all,
when the video has finished playing, the last frame is displayed, but it gets pixelated.
This happens in Firefox and IE 11 (I haven't tested the others).
Is there any way to keep it as it is in the video ?

Thanks,
Bruno

**Comment by bozolozo** [comment]
I have found the solution, it was a video problem apparently, nothing to do with videojs player...

**Comment by gkatsev** [comment]
Glad you figured it out!
