### ISSUE TITLE
White becomes grey in Firefox

### ISSUE THREAD

**Issue by bozolozo** [videojs/video.js#4670]
Dear all,

I have some videos with a white background and white becomes grey in Firefox (works fine in IE and Chrome). Any idea why ? Is there a way to solve this problem ?

Thanks !

**Comment by kocoten1992** [comment]
That depends on how browser handle video

If you are using vlc (video lan), window media player or some other video player at their default setting. If you take a screenshot at the exact video frame, you'll notice the color are very much different

This behavior happen on browser as well, can do a little experiment

1. go to : videojs.com
2. open console: ```player.currentTime(1.5)``` (on both firefox and chrome)
3. quickly switch between two browser, you'll notice a very clear color diff

If that solve your issue 👍

**Comment by bozolozo** [comment]
Thank you for your reply, I'll check ! :)

**Comment by kocoten1992** [comment]
try at 15s, firefox darken color quite a bit

**Comment by gkatsev** [comment]
We aren't doing anything to change the color of videos, as @kocoten1992, this is probably just a difference in how the browsers handle decoding.
