### ISSUE TITLE
Video addEventListener not work well on mobile

### ISSUE THREAD

**Issue by Yalhu** [videojs/video.js#4674]
## Description
Video(not player) `addEventListener` not work well on mobile ,but PC is ok.

## Steps to reproduce
```javascript
   var video1=document.getElementById('video1');
    var player=videojs('video1');
    video1.addEventListener("loadedmetadata", function(){
        console.log('load');//can log
    });
    video1.addEventListener("timeupdate", function(){
        console.log('timeupdate');//log once when video loaded
    });
    player.on("timeupdate", function(){
        var s=video1.width;//0
        var t=video1.currentTime;//0
    });
```
It seems video event unbind when player is ready. `Load` can be work; `play,playing,timeupdate,pause`  only trigger once.
And when i addEventlistener on player, I can't get the right video's attribute.

### Expected
Cause a lot work (added event on video) my colleague have done , I really do not want to update code. 

It works well on PC. Is anything I can do to resolve this problem on mobile?

#### videojs
videojs 6.2.1
#### browsers
chrome 60

**Comment by gkatsev** [comment]
You should not be interacting with the video element at all once you give it to Video.js, instead you should use the Video.js API. Here's an updated snippet:
```js
   var video1=document.getElementById('video1');
    var player=videojs('video1');
    player.on("loadedmetadata", function(){
        console.log('load');//can log
    });
    player.on("timeupdate", function(){
        console.log('timeupdate');//log once when video loaded
    });
    player.on("timeupdate", function(){
        var s = player.currentWidth();//0
        var t = player.currentTime();//0
    });

```
Hope that helps.

**Comment by Yalhu** [comment]
But PC works. I had updated it with Videojs API.
