### ISSUE TITLE
muted option not documented

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#4676]
`muted` is missing from options guide.

**Comment by thijstriemstra** [comment]
It's documented in the repository but first hit on google for `video.js options` is very outdated: http://docs.videojs.com/docs/guides/options.html

**Comment by mister-ben** [comment]
/docs/ is an old version. We need to work on our SEO so http://docs.videojs.com/tutorial-options.html would come up instead.

**Comment by thijstriemstra** [comment]
A 302 forward or something.

**Comment by gkatsev** [comment]
It's hard to do a 302 via github pages. Also, we still want the old docs up for people using the old version of the player.

**Comment by gkatsev** [comment]
Unfortunately, not much we can do if we still want the legacy docs up (which we still do for at least a bit longer). At some point, we can keep legacy docs as something like `legacy-docs.videojs.com` in which case we can remove/redirect the old pages to the new pages.
