### ISSUE TITLE
Middleware gets recreated on source change, duplicating event handlers bound within

### ISSUE THREAD

**Issue by onebytegone** [videojs/video.js#4677]
## Description

_Disclaimer:_ Not positive this is a bug, but does somewhat go against expectations. Therefore making a note about it.

In the [feature spotlight for middleware in Video.js 6.X](http://blog.videojs.com/Feature-Spotlight-Middleware/), it uses the following [example from `videojs/videojs-playbackrate-adjuster`](https://github.com/videojs/videojs-playbackrate-adjuster/blob/38cffe524232b1592b9bda763da967ea97cc636e/src/js/index.js#L18-L21) where an event handler is bound inside the factory for the middleware:

```js
videojs.use('*', function(player) {
   let tech;

   player.on('ratechange', function() {
      tech.trigger('durationchange');
      tech.trigger('timeupdate');
   });

   return {
      /* ... */
   }
});
```

Following this pattern does work. However if the player's source is changed, the [factory for middleware gets reran](https://github.com/videojs/video.js/blob/03529163b677001f2ca994608d2026c55b11b73d/src/js/tech/middleware.js#L66) thus causing another event handler to be bound. This in turn causes more handlers to be fired than one might expect. Additionally a more fundamental question comes to mind, is it expected for middleware to be recreated each time the player's source changes?

This behavior was originally discovered when investigating https://github.com/silvermine/videojs-quality-selector/issues/5. A reduced test case can be seen at: http://jsbin.com/tabove/edit?html,console,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load the reduced test case from: http://jsbin.com/tabove/edit?html,console,output
2. Play video and press the `TestCaseButton` on the player's control bar. Note that `triggering "onTestCaseButtonPress"` and `responding to "onTestCaseButtonPress"` are each logged once to the console.
3. Press the `Reload source` button. Note that `loading middleware` is called
4. Play video and press the `TestCaseButton` on the player's control bar. Note that `triggering "onTestCaseButtonPress"` is logged once and `responding to "onTestCaseButtonPress"` is logged twice

### Animated example of issue

![videojs-reinit-middleware](https://user-images.githubusercontent.com/8900251/31789963-d44c2a1c-b4e1-11e7-9c28-5a386b6309ff.gif)

### Expected
Please describe what you expected to see.

Based on the example usage of binding an event handler in the middleware setup (see last code snippet in [this Video.js blog post](http://blog.videojs.com/Feature-Spotlight-Middleware/)) and the [`videojs/videojs-playbackrate-adjuster`](https://github.com/videojs/videojs-playbackrate-adjuster/blob/38cffe524232b1592b9bda763da967ea97cc636e/src/js/index.js#L18-L21), it leads one to think that the middleware's factory is a safe place to bind a middlware-related event handler to the player.

### Actual
Please describe what actually happened.

Each time the source for the player is changed, the [middleware's factory is re-ran](https://github.com/videojs/video.js/blob/03529163b677001f2ca994608d2026c55b11b73d/src/js/tech/middleware.js#L66). Thus causing any event handlers in the factory to be bound again which can lead to [more handlers being existing than expected.](https://github.com/silvermine/videojs-quality-selector/issues/5)

### Error output
If there are any errors at all, please include them here.

n/a

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?

6.x.x

#### browsers
what browser are affected?

all

#### OSes
what platforms (operating systems and devices) are affected?

all

### plugins
are any videojs plugins being used on the page? If so, please list them below.

no plugins are needed to reproduce, however somewhat related to [`videojs/videojs-playbackrate-adjuster`](https://github.com/videojs/videojs-playbackrate-adjuster)

**Comment by gkatsev** [comment]
Thanks for the issue. Glad to see middleware being used in the wild!
This does seem like an underspecified/underdocumented issue. The current implementation, clearly, calls the factory each time, it might make sense to cache the response from the factory and and re-use that across source changes. Is that what you're suggesting?
I guess the work-around now is to unbind previous events in `setSource`? Or bind it outside of the factory.

**Comment by gkatsev** [comment]
Or I guess, the factory should only be called once-per player.

**Comment by onebytegone** [comment]
Thanks for the quick response @gkatsev!

I do think that the factory should only be called once per player, i.e. there is only one instance of a given middleware for a player, but a player can have an instance of many different middlewares. Since `player` is passed to the middleware factory, it seems to lend itself to this type of relationship. In theory, "a middleware factory creates a piece of middleware for the supplied player." 

With regards to the implementation, caching the response from the factory does make sense. That's probably the simplest option. I do wonder, instead of "caching" a map of middleware instances for each player in `middleware.js`, what if the player "owned" the middleware instances for itself? It perhaps could be similar to how a player has a tech. (e.g. `player` gets created, middleware is setup for it, when source changes, player looks though middleware to see all that apply and runs them) Doing so might be more complicated than needed though. 🤷‍♂️

As to the reported issue that brought the question up, https://github.com/silvermine/videojs-quality-selector/issues/5, binding the event [using `videojs.hook('setup', function(player) { ... });`](https://github.com/silvermine/videojs-quality-selector/pull/6/files#diff-99a85c3932c0670278158f38d818e0efR14) looks to have taken care of the issue. Just wanted pass this along in case it is an issue or someone else ends up having a similar problem.

**Comment by gkatsev** [comment]
I didn't have any particular implementation in mind for "caching" and having each player instance own the middleware instances does make sense. The player already has a list of middleware that were chosen for a particular source, so, it would makes sense it would also own the instances as well. I think the main difficulty here would be to keep things in sync if we were to allow removing middleware but that's probably out of scope right now.

Yeah, hooks are another great way of doing it.

**Comment by gkatsev** [comment]
It's been a while but finally getting back to this. One thing that I thought about when getting started is whether a newly registered middleware should have us go through the middleware selection algorithm again or not. In a conversation in [slack](https://videojs.slack.com/archives/C43LGP955/p1517859449000277) (I would've linked via [slack-archive](https://videojs.slackarchive.io/discussion/page-48/ts-1517861299000322), but it doesn't have support for slack threads) we came to the conclusion that we shouldn't. The middleware selection will only happen during source changes.

I'm thinking of adding a private method on the player to work with middleware. It would be something like `player.getOrCreateMW_`, which given a mw factory and a type, it will either return the cached mw instance or create a new one and cache it. Thoughts?

**Comment by gkatsev** [comment]
I have initial implementation of the fix in this PR https://github.com/videojs/video.js/pull/4939
Hopefully, we'll have it in a release in a week or two.
