### ISSUE TITLE
player reset() should reset UI state of control bar etc

### ISSUE THREAD

**Issue by Force-Wj** [videojs/video.js#4683]
## Description
when i use reset() api,   controlBar UI not reset

## Steps to reproduce
1. playing video
2. call reset function

**Comment by gkatsev** [comment]
Can you elaborate on what you mean by the control bar UI not being reset?

**Comment by Force-Wj** [comment]
when i execute player.reset() , the vjs-control-bar has not be reset. The status of play buttom is playing, the progress-control UI is not right too

**Comment by gogoku** [comment]
Any update on this issue?, i am still facing the same issue
#3816 trying to use this solution to update the video player

**Comment by gkatsev** [comment]
No update yet, we should reset the control when `reset` is called, but its main purpose was to reset the state of the techs, which it does. Any help with this would be appreciated.

**Comment by gogoku** [comment]
i guess calling dispose to remove the player from the dom and adding again is the right way to do it ,
Can you please tell me , What is the case that reset tech is used for?
