### ISSUE TITLE
Video.js  - hide controls at the end of the video

### ISSUE THREAD

**Issue by bozolozo** [videojs/video.js#4685]
Hello,

I would like the controls not to be displayed automatically at the end of the video.
The controls would still appear if the user rolls its mouse over though.

Is there any way to do that ?

Many thanks!

**Comment by kocoten1992** [comment]
you could do via javascript:
```js
player.on('ended', () =>  console.log('ended!'))
```

**Comment by bozolozo** [comment]
Hi,

thank you very much for your reply.
I am not really a javascript person though, so could you be a little more specific ?
Where do I place this code ?

Thanks a lot in advance !

**Comment by kocoten1992** [comment]
@bozolozo something like this:

```js
var player = videojs('id_of_video') // I assume you will have this line somewhere

// then place this line (after the line above)
player.on('ended', () =>  player.controls(false))
```

**Comment by bozolozo** [comment]
Hello Kocoten,
actually, I just pasted your code after I called the video <video id...></video> and it works fine on Firefox and Chrome, but not on IE, any idea why ?
Also, is there a way to make the control bar disappear as soon as the user clicks on the big button ?
Thank you again for your help :)

**Comment by gkatsev** [comment]
Depending on the source type and IE version, you may not get an `ended` event because of issues in the browser.
In addition to the `ended`, you could listen to the first `play` event on the player and then hide the controls that way.
