### ISSUE TITLE
Middle mouse can play/pause videojs

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#4689]
#### Steps to reproduce
1. go to videojs.com
2. press play
3. now, you can use middle mouse to play/pause video (click on the video, not triangle play button)

#### Expected
Shouldn't be able to do that

Problem might be here:
https://github.com/videojs/video.js/blob/master/src/js/player.js#L1384

Related issue: https://github.com/videojs/video.js/issues/4611 (fixing that will give enough experience to fix this)

**Comment by gkatsev** [comment]
I wasn't able to reproduce but I can definitely see it happening on some browsers and OSes.

**Comment by sziberov** [comment]
Can do this too.
v5.4.6
Opera Developer
Windows 10

**Comment by gkatsev** [comment]
@sziberov it's fixed in 6.5.0, please give that a try!

**Comment by sziberov** [comment]
@gkatsev Yeah, it is, but time tooltip completely broken now.

**Comment by kocoten1992** [comment]
@sziberov open new issue, take a picture before and after maybe, I recall the slider have ```box-shadow``` (but never really show before, only show after fix the left click), didn't recall time tooltip though

**Comment by elypter** [comment]
i can reproduce the problem on the official demo https://videojs.com/city and im using firefox on windows 10
