### ISSUE TITLE
FLASH: NetConnection.Connect.Rejected

### ISSUE THREAD

**Issue by kimsoyeon7408** [videojs/video.js#4692]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
```
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="ui" uri="http://egovframework.gov/ctl/ui"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
```
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Insert title here</title>

<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-3.2.1.min.js"></script>
<link rel="stylesheet" href="${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css" />
<script type="text/javascript" src="${pageContext.request.contextPath}/bootstrap/js/bootstrap.min.js"></script>

<%-- <script src="<c:url value='/js/videojs/rtmp.js' />"></script>
<script src="<c:url value='/js/videojs/plugin.js' />"></script> --%>
<link href="http://vjs.zencdn.net/6.2.8/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/6.2.8/video.js"></script>  
<script src="https://unpkg.com/videojs-flash@2.0.1/dist/videojs-flash.js"></script>
</head>
<body>
	<div class="container">
  		<video id="video-js-video" class="video-js vjs-default-skin" controls width="640" height="320" data-setup='{"techOrder": ["flash","html5"]}'>
   			<source src="rtmp://A.com:1935&mp4:/BVod/1/2017/10/25/C.stream_2017-10-25-16.43.30.746-KST.mp4" type='rtmp/mp4'>
		</video>
	</div>
</body>
</html>
```
FLASH: NetConnection.Connect.Rejected

WHAT'S WRONG???

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
FLASH: NetConnection.Connect.Rejected

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected? CHROME
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
That's weird, we didn't do any changes, though, maybe FBSubscribe changes in the swf are an issue? But if you're using swf 5.1 it shouldn't be an issue. The stream in this issue https://github.com/videojs/video.js/issues/4779 which has the same error also reproduced the error in other players, so, it could just be a backend issue.

**Comment by gkatsev** [comment]
The stream in #4779 was fixed so going to say it's a stream issue.
