### ISSUE TITLE
currentTime() does not work inside player.ready() in safari

### ISSUE THREAD

**Issue by scottgrayson** [videojs/video.js#4696]
## Description
currentTime() does not work inside player.ready() in safari

http://jsbin.com/lizarefopo/edit?html,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. try the jsbin in chrome (jumps 10s ahead)
2. try it in safari (starts at 0s)

### Expected
Video should start at 10s

### Actual
Video starts at 0s

```
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Video.js Example Embed</title>
  
  <link href="http://vjs.zencdn.net/6.2.8/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/6.2.8/video.js"></script>
  
</head>
<body>
  <h1>Video.js Example Embed</h1>

  <video id="my_video_1" class="video-js" muted controls preload="auto" width="640" height="268" 
  data-setup='{}'>
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
    <source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
  </video>
  
  <script>
    var player = videojs('my_video_1').ready(function () {
      this.currentTime(10)
      this.play()
    })
  </script>
  
</body>
</html>
```

**Comment by gkatsev** [comment]
Yeah, this is because Safari is weird and you can't actually change the current time at least until loadedmetadata but sometimes even later like until `canplay` is fired.
Video.js should probably handle this better, though.

**Comment by haojia321** [comment]
Tested on Chrome, Safari on iPhone. Both are not working.
Any suggestion how to work around it for now?

**Comment by BonBonSlick** [comment]
Still currentTime() not working in 7+ version. ..

**Comment by 0xc0d3r** [comment]
@scottgrayson Have you found the solution to make it work in Safari and iOS devices?
