### ISSUE TITLE
Multiple videos playing at the same time

### ISSUE THREAD

**Issue by Syedwaheed** [videojs/video.js#4701]
Hi,
Can any one give me some direction regarding multiple videos playing at the same time. I have multiple videos in my page and i wanted to play the one video at a time. When i click the play button the previously playing video should be stop.I have two videos with different ids i.e
```
<video id="video" class="video-js vjs-default-skin vjs-big-play-centered" controls preload width="280" height="200" 
        poster=""  data-setup='{"fluid": false, "playbackRates": [0.5, 1, 2], "html5": {"nativeTextTracks": false}}'>
            <source src="/Admin/video/tears-of-steel-battle-clip-medium.mp4" type="video/mp4">
          <!--  <source src="http://vjs.zencdn.net/v/oceans.webm" type="video/webm">-->
            <track kind="captions" src="<?php echo base_url(); ?>sintel-en.vtt" srclang="en" label="captions on" default>
        </video>
<video id="video1" class="video-js vjs-default-skin vjs-big-play-centered" controls preload width="280" height="200" 
        poster=""  data-setup='{"fluid": false, "playbackRates": [0.5, 1, 2], "html5": {"nativeTextTracks": false}}'>
            <source src="/Admin/video/highres.mp4" type="video/mp4">
          <!--  <source src="http://vjs.zencdn.net/v/oceans.webm" type="video/webm">-->
            <track kind="captions" src="<?php echo base_url(); ?>sintel-en.vtt" srclang="en" label="captions on" default>
        </video>
```
and I have also checked the @gkatsev script i.e 
```
var players = [video, video1];

players.forEach(function(player) {
  player.on('play', function() {
    players.forEach(function(pl) {
      if (pl !== player) {
        pl.pause();
      }
    }
  }
});
```
but thats giving me error.
![capture](https://user-images.githubusercontent.com/14071753/32162337-74f00e34-bd7a-11e7-96b0-053aa2a60482.JPG). Any suggestion regarding this would be highly appreciated. 
Thanks for this great feature.

**Comment by rahulsinghvuclip** [comment]
Hi can you share code as player is taking single instance

**Comment by khullah** [comment]
@Syedwaheed the error is what it says: it was missing ")" in code. Correction:

```
players.forEach(function(player) {
  player.on('play', function() {
    players.forEach(function(pl) {
      if (pl !== player) {
        pl.pause();
      }
    })
  })
});
```

**Comment by gkatsev** [comment]
Looks like this is solved?

**Comment by knight4life** [comment]
@Syedwaheed @bernardoadc Where does that JS code reside? the Players.foreach portion? Is that in the actual video.js file, or is called somewhere in the html using a <script> tag?

Thank you,

**Comment by pawan2601** [comment]
@gkatsev 

Looks like, it is not working in latest version. This functionality should be there in-built in the script.

`<script type="text/javascript">
window.onload = function(){
    var players = [vid-1, vid-2, vid-3];
    players.forEach(function(player) {
  player.on('play', function() {
    players.forEach(function(pl) {
      if (pl !== player) {
        pl.pause();
      }
    })
  })
    })
});
</script>`
