### ISSUE TITLE
Latest build fail, HEAD is now at 79639138

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#4706]
#### Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. git clone https://github.com/videojs/video.js
2. npm install
3. npm run test

It fail by ```open() hides controls, close() shows controls``` at test/unit/modal-dialog.test.js

**Comment by mister-ben** [comment]
I believe #4690 is causing this

**Comment by gkatsev** [comment]
Thanks, yeah, I noticed that it was failing after merging in but didn't have the time to fix it last night.
