### ISSUE TITLE
Videojs Plugin webpage update request

### ISSUE THREAD

**Issue by Lethea** [videojs/video.js#4709]
In wiki page I added the plugin that I publish npm and github.

Unfortunately the page doesnot show the plugin. Can anyone update the http://videojs.com/plugins/ page

https://github.com/Lethea/videojs-marquee-overlay-scrolling-text

https://github.com/Lethea/videojs-dynamic-overlay

**Comment by gkatsev** [comment]
videojs.com/plugins pulls from npm but the automated process we had broke so it doesn't update anymore. I'll be taking a look soon.

**Comment by Lethea** [comment]
Ok @gkatsev thanks for the info ;)

**Comment by gkatsev** [comment]
The page has been updated with data as of ~30 minutes ago.

**Comment by gkatsev** [comment]
Site is live.
