### ISSUE TITLE
Preload None Not Works on Ajax Video

### ISSUE THREAD

**Issue by amiremami** [videojs/video.js#4712]
Hi
I have a video in this website which loads by ajax:
http://topimagesites.com/

The size of the video is 3 mb and it causes loading time of the website become 60 sec! So I added "preload none" to the code:
```
<div class="video_modal">
    <div class="inner_video">
        <video id="my-video" class="video-js" controlsList="nodownload" loop controls width="100%" height="auto"
          poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
            <video preload="none"><source src="http://topimagesites.com/wp-content/tis-video.mp4" type='video/mp4'><source src="http://topimagesites.com/wp-content/tis-video.mp4" type='video/webm'>
            <p class="vjs-no-js">
              To view this video please enable JavaScript, and consider upgrading to a web browser that
              <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
            </p>
        </video>
```
The video not preloading now, but when I click on play image, it is broken:
https://i.imgur.com/Yq3qkwV.png

Can you tell me how can I fix this?

Thanks a lot

**Comment by kocoten1992** [comment]
In your code, there is 2 video tag inside each other (that shouldn't happen, really, how?), the outside video tag should be a ```div```, once fixing that, everything should work.

**Comment by amiremami** [comment]
Thanks a lot :)

**Comment by gkatsev** [comment]
If it's still an issue, let us know if you still need more help, a reduced test case would be super helpful as well.
closing the issue in the meanwhile.
