### ISSUE TITLE
[proposal],[hack] Seekbar should immediately reflect by css when click

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#4721]
###### I'm posting here to inform and introduce a work around for this problem, because I'm not sure it gonna get fix very soon (and I can't wait) :grin:

This is hard to reproduce online since the content is not available

I'll explain here first, step to reproduce are below:
- When you click on seekbar, the css are ```not really``` catch up immediately, youtube and facebook player have css reflected instantly when mouse down
- In videojs, there is 2 two way for css to catch up, I've read some of the code but not really dig deep, only can tell so far..
-- 1, you click and then release the mouse (that will trigger ```handleMouseUp``` on seekbar)
-- 2, network catching up, then css will make the jump

For instance, if you click and then hold (scrubbing), then css not gonna be reflect, look at the image below

![cssnotcatchup](https://user-images.githubusercontent.com/7130705/32409752-2c15b15a-c1e4-11e7-9056-d7fba32a7626.png)

(the red circle was from ```keymon``` software when click, if css was catch up immediately, I can never take that picture)

### Step
1. go to https://durian.blender.org/download/, download 1GB version
2. set up page, open f12 chrome, set tab network to slow 3G (increase chance of success)
3. click and hold mouse
4. profit...

I not sure this was the intended behavior, css catch up quickly would make user feel more comfortable

Any how, here the quick hack for anybody run into this one:

```js
var SeekBar = videojs.getComponent('SeekBar')

class MySeekBar extends SeekBar {
  handleMouseDown(event) {
    // these two line are none trivial hack, only when play
    // css can make the jump instantly, don't know why, but it has to be playing
    // also, in the process, I've introduce new bug (play() <- promise, then pause(), pause always win)
    // https://stackoverflow.com/questions/30233302/promise-is-it-possible-to-force-cancel-a-promise
    // but nothing serious though, everything work as expected, play() just throw err
    this.videoWasPaused = this.player_.paused()
    this.player_.play()

    super.handleMouseDown(event)
    super.handleMouseUp(event)

    const doc = this.bar.el_.ownerDocument
    this.one(doc, 'mouseup', this.handleMouseUp)
    this.one(doc, 'touchend', this.handleMouseUp)
    this.player_.pause()
  }

  handleMouseMove(event) {
    super.handleMouseMove(event)
    super.handleMouseUp(event)

    const doc = this.bar.el_.ownerDocument
    this.one(doc, 'mouseup', this.handleMouseUp)
    this.one(doc, 'touchend', this.handleMouseUp)
    this.player_.pause()
  }
  
  handleMouseUp(event) {
    super.handleMouseUp()

    if (this.videoWasPaused) {
      this.player_.pause()
    } else {
      this.player_.play()
    }
  }
}

videojs.registerComponent('SeekBar', MySeekBar)
```

Any thought? Should it change to reflect css instantly ?

**Comment by gkatsev** [comment]
Yeah, this is a longstanding problem/by design. It has to do with how the seek is being done in video.js where we actually seek when you move the mouse. Other players like youtube don't actually seek the video until the mouse is released. There was an issue about this previously (https://github.com/videojs/video.js/issues/4460#issuecomment-313002033).

Given how tied the seekbar is to the current play position, I'm not sure how good it would be to have it update "early" during seeks without a corresponding refactor of the seek internals.

**Comment by kocoten1992** [comment]
For the record, I do think youtube really seek when ```mousedown``` and ```mousemove```

I just did a small experiment:
1. open youtube
2. open f12, tab network, check ```disable cache```
3. go to a video, try ```mousedown``` or ```mousemove``` seek and watch network tab go crazy

They send a serious amount of get request, that is clearly seeking ?

**Comment by gkatsev** [comment]
They do a bunch of stuff, it's possible that things have changes but last time I checked they only got new thumbnail images when scrubbing.
