### ISSUE TITLE
PopupButton and Popup component undefined

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#4725]
### Description
http://jsbin.com/qodopuzona/edit?html,console

**Comment by gkatsev** [comment]
Thanks for the PR @asronihidayat.
Though, looking into this, it was only used in 5.x with the old VolumeMenuButton component which no longer exists. I'm thinking we can just remove these files until/unless they're needed?
Thoughts? @OwenEdwards would be good to have your take as well.

**Comment by asronihidayat** [comment]
Actually,i use popup and popup button for custom component videojs, but if you really want to remove both of them, i can refactor my code, so, it will compatible with videojs future updated.

**Comment by kocoten1992** [comment]
Hi, this is not total relevant but while we on the topic, think we are missing a something like ```ComponentList```

I'm implementing something like resolution list like youtube (1080, 720, 480...), that is a list only know length at runtime (when manifest fetched).

Our component currently is just a single component, thing like ```handleClick```, ```handleMouseDown``` will point to the root element instead of child element.

In my app I manually add event to child element, that rather cumbersome, but I'm not sure this idea 
 useful either, what your though ?

**Comment by gkatsev** [comment]
@asronihidayat what about if we release the popup stuff as a separate plugin?

**Comment by gkatsev** [comment]
I'm leaning towards leaving it out of core but publishing it as a separate plugin. In v6 we already moved videojs-flash out of core and core doesn't use the popup buttons anymore, so, including them seems a bit odd to me.

**Comment by gkatsev** [comment]
@asronihidayat so, after some thinking about this, we aren't going to be including PopupButton and Popup back in Video.js by default. Feel free to grab the files though and use them in your project. But be aware that we stopped using PopupButtons because of accessibility issues around our old volume menu button. See some info here: http://blog.videojs.com/feature-spotlight-accessibility/.
