### ISSUE TITLE
Missing / in Readme.md Quick Start section

### ISSUE THREAD

**Issue by FirefoxMetzger** [videojs/video.js#4729]
In the Quick Start section of the Readme.md where instructions are given on how to include video.js through unpkg and cdnjs there is this code:

    
    <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
    <script src="https://unpkg.com/video.js/dist/video.js"><script>

    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/6.3.3/video-js.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/6.3.3/video.js"><script>

In both cases the `<script>` tag is not closed. I think it should be `</script>`.

**Comment by gkatsev** [comment]
Whoops, yes, those should've been `/script`. Care you make a PR to fix it? Thanks.

**Comment by FirefoxMetzger** [comment]
Sure thing

**Comment by FirefoxMetzger** [comment]
Fixed it in #4730 
@gkatsev care to review? =)

**Comment by gkatsev** [comment]
Thanks @FirefoxMetzger! Merged.
