### ISSUE TITLE
IE10, PlaybackRateMenuButton

### ISSUE THREAD

**Issue by CHOJUIL** [videojs/video.js#4732]
## Description
I disabled hover of PlaybackRateMenuButton.
Like this.
`  /* playbackrate remove hover */
/* .vjs-workinghover .vjs-menu-button-popup:hover .vjs-menu,
.vjs-menu-button-popup .vjs-menu.vjs-lock-showing {
  display: block; } */`

## Steps to reproduce
1.  
2.
3.

### Expected
Playbackrate menu popup not display when mouse over.
PlaybackRateMenuButton change when PlaybackRateMenuButton mouse click.

### Actual
It works well on ie11.
But it does not work well on ie10.
Like this.
It works well on Button area(red square).
It does not work well on Value area(white square).
![playback](https://user-images.githubusercontent.com/16010967/32595327-d44dc2ae-c572-11e7-808f-ffa4ef0d605e.PNG)

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
video.js 6.2.8
#### browsers
ie 10, 11
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Are you trying to hide the menu of the playback rate but still have clicking the button work? Maybe it would be better to do something like:
```css
.vjs-playback-rate.vjs-menu-button.vjs-button .vjs-menu {
  display: none;
}
```

**Comment by CHOJUIL** [comment]
Playbackrate menuitems is visible when hover.
I want change to.
PlaybackRate menuitems is visible when click.

**Comment by edwinbradford** [comment]
You need to edit [playback-rate-menu-button.js](https://github.com/videojs/video.js/blob/master/src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js) and comment out the `handleClick(event) {...}` from lines 115 to 130. This function overrides the default behaviour of other buttons causing the conflict.

After doing this you will need to rebuild the VideoJS JavaScript files. If you don't know how or don't want to do this you can grab my Javascript files from [my fork](https://github.com/edwinbradford/videojsneue) in which this has already been done. N.B. Don't copy my CSS files unless you want my theme and please be aware there's one more minor JavaScript style change to the style of the [Live Display](https://github.com/edwinbradford/videojsneue/blob/master/src/js/control-bar/live-display.js).

In my theme all the Menus works onClick and not on hover.

**Comment by gkatsev** [comment]
I think my CSS should help otherwise, you should follow the advice in https://github.com/videojs/video.js/issues/4837 to create a custom playback rate menu item.
