### ISSUE TITLE
Caption Setting Error

### ISSUE THREAD

**Issue by Syedwaheed** [videojs/video.js#4734]
Hi,
Can anyone help me with the caption setting?I m facing an error in all browsers. Text is not showing in dropdown menu? I need this feature asap. Any help would be appreciated.
![capture](https://user-images.githubusercontent.com/14071753/32602880-9caa75c6-c569-11e7-8c87-1464d298b469.JPG)

**Comment by gkatsev** [comment]
You probably have extra styling on the page that are overriding the styles for `select` and `option` elements and that is causing issues in video.js. This is especially the case if you're using a css framework like Foundation.
What version of video.js are you using? I think we fiddled to make it more resilient previously.

**Comment by Syedwaheed** [comment]
Thanks for your prompt reply @gkatsev . I m using the latest version of video.js and having the Code Igniter framework in my application. I will go through the CSS file and will see to over come this problem.

**Comment by gkatsev** [comment]
It's been a while and I assume this is solved. If you know what was causing the issue, we might be able to make it less likely to happen with some reset inside of Video.js like we [have right now](https://github.com/videojs/video.js/blob/master/src/css/components/_layout.scss#L45-L57).
