### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

### ISSUE THREAD

**Issue by QbjGKNick** [videojs/video.js#4735]
## Description
Can't play video FLV rtmp/flv video rtmp://10.10.77.141:1935/live/9e617662eb8841eda5d97227b3783f48

## Steps to reproduce
here is my js code and html
html:
`<link rel="stylesheet" href="../../../static/css/video-js.css" />
<script type="text/javascript" src="../../../static/script/plugins/videojs-ie8.min.js"></script>
<script type="text/javascript" src="../../../static/script/plugins/video.5.8.8.js"></script>
<video id="liveVideo" class="video-js vjs-big-play-centered" >
	<source src="" type='rtmp/flv'></source>
</video>`

js:
`var url = "";
if(browserRedirect() == "pc"){
	url = result.data[0]['url'];
}else{
	url = result.data[2]['url'];
}
$('source').attr('src', url);`

### Expected
i hope to see this online video,but it doesn't work,i use chrome to play,but 
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. `

**Comment by kocoten1992** [comment]
possible this pending fix, https://github.com/videojs/videojs-flash/pull/39

**Comment by gkatsev** [comment]
Yup, this is videojs/videojs-flash#39.
