### ISSUE TITLE
the latest chrome version(62.0.3202.89) can't load rtmp/flv

### ISSUE THREAD

**Issue by QbjGKNick** [videojs/video.js#4736]
## Description
1、the latest chrome version can't play the type of rtmp/flv,however the old version of chrome can load the type of rtmp/flv for the same code.
2、my ie and fireFox can load this type and don't throw error,but the video is black when play

## Results
the same code for different chrome version can't load rtmp/flv, the old chrome version can load this.IE and fireFox can play but the screen is black and doesn't throw error.

**Comment by mister-ben** [comment]
Each Chrome version has tweaked the threshold at which Flash is disabled by default and it should now be for all sites going by [their schedule](https://www.chromium.org/flash-roadmap#TOC-Shipping-Schedule).

See videojs/videojs-flash#39 for progress on a change to make the Flash tech not always believe the browser when it says it's not available.

It's going to be increasing less likely that end users have Flash installed at all so I'd recommend moving away from RTMP as soon as you can.

**Comment by gkatsev** [comment]
Closing this in favor of tracking in vidoejs/videojs-flash#39.
