### ISSUE TITLE
Is there a way to flush the buffered data?

### ISSUE THREAD

**Issue by mconiglio** [videojs/video.js#4742]
Hello, I have an issue that can be seen here: http://jsbin.com/xaluxihige/1/edit?html,output

The thing is that, when changing the language of the video, it doesn't change the track until new video content is downloaded. So the old language is reproduced for all the part of the video that is already buffered, and when that part finishes, the new language starts being reproduced.

I found the way to listen to the event when the language is changed, but I would need to clean the buffer in this callback and I can't find the way to do that.

Is there a way to do that? Or can this be done with another approach?

Thanks

**Comment by gkatsev** [comment]
Hey, this looks like a DASH issue, would you be able to re-open this issue against the [contrib-dash](https://github.com/videojs/videojs-contrib-dash/issues/new) project?

Thanks.

**Comment by mconiglio** [comment]
Hello @gkatsev, thanks for your answer.

I already opened an issue in that project as well: https://github.com/videojs/videojs-contrib-dash/issues/220

**Comment by gkatsev** [comment]
Ah, cool. In that case I'm going to close this issue in favor of videojs/videojs-contrib-dash#220. I'll try and get someone to look at it as well.
Thanks for your patience.

**Comment by mconiglio** [comment]
Ok, great! Thanks for your help.
