### ISSUE TITLE
Seek Triggers Pause() Function?

### ISSUE THREAD

**Issue by casbboy** [videojs/video.js#4744]
## Description
If I seek while the video is playing, it causes the pause() function to launch. I'm trying to avoid this. Is there a way to tell the player that, if currently playing at time of progress bar seek, not to launch the pause() function?

## Steps to reproduce
Click anywhere on the progress bar while video is playing.

### Expected
Would like pause() trigger not to happen.

### Actual
Pause() trigger fires.

Happens on all browsers.

Cheers!
Ryan

**Comment by forbesjo** [comment]
@gkatsev should we instead set playback rate to 0?

**Comment by gkatsev** [comment]
Yeah, unfortunately, that's how it works currently to support both HTML5 and Flash (and other tech) playback. Back when it was first implemented `playbackRate` didn't exist. Unfortunately, just changing how this works could potentially be a breaking change and so we can't do this easily but ideally, I'd like to move this type of functionality into the tech itself. That way, the Html5 tech can use `playbackRate` and the Flash tech/default can continue using `pause()`.

**Comment by casbboy** [comment]
Interesting. As a minor solution, is there a way I can tell when the player was paused manually over being paused on seek?

**Comment by forbesjo** [comment]
I know that the `videojs-errors` plugin only looks for `paused()` and not `seeking()` as well for its timeout logic. So if someone scrubbed without moving it would eventually timeout.

**Comment by gkatsev** [comment]
Yup, you can check whether we are seeking with `player.seeking()` as @forbesjo mentioned.
