### ISSUE TITLE
Android System WebView issues

### ISSUE THREAD

**Issue by casolorz** [videojs/video.js#4748]
Hi, I don't use your product but I've noticed a few websites have issues playing videos on the Android System WebView. I contacted one of those sites, uptostream.com, and they fixed the issue and they told me the issue came from this player. 

This is the description they gave me of the issue:

_videoJs2['default'].browser.IS_CHROME but chrome object is not available. JS crashing if chromecast didn't exist. 

if (!_videoJs2['default'].browser.IS_CHROME || _videoJs2['default'].browser.IS_EDGE) {
return;
}
if(typeof chrome == 'undefined') {
return;
}

Let me know if you have any questions. Thank you.

**Comment by kocoten1992** [comment]
Thank you for taking time solving other people problem (like me :/)

But I believe something wrong when they conducting their test

1. videojs.com
2. f12 to open dev tool
3. type in ```videojs.browser```

We will see that IS_CHROME is existed

**Comment by casolorz** [comment]
I believe the issue is that `videojs.browser.IS_CHROME` returns true on the Android System WebView but `window.chrome` is undefined on the Android System WebView. 

I believe these lines are their fix:

if(typeof chrome == 'undefined') {
return;
}

**Comment by gkatsev** [comment]
So are they using `videojs.browser.IS_CHROME` to see whether `window.chrome` exists? That sounds like a bad check. They should just check if `window.chrome` exists before using it.
I'm not seeing any usage of `chrome` in videojs but it can still be helpful for videojs users. Given that there's nothing actionable in video.js itself I'm going to close this issue.

Thanks for posting @casolorz and hopefully it helps someone down the road.
