### ISSUE TITLE
ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by iuzhakov** [videojs/video.js#4751]
## Description
I can't to init few video players on one page (360° video). First video player run ok (may be even second). Second and others not work. Tell me please, this is my mistake or videojs or my device.
On desktop PC all video players work fine

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Download my example (link below)
2. Run example on the tablet which I pointed out (if you have)
3. First video player run ok. Second and others not work

### Expected
All video players should to work ok

### Actual
Please describe what actually happened.
First video player run ok. Second and others not work

### Error output
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Video.js 5.19.2
#### browsers
Chrome 61.0.3163.98
#### OSes
Android 7.0
#### Device
Samsung Galaxy Tab A. Model number:  SM-T585
### plugins
I using plugin - videojs-panorama (https://github.com/yanwsh/videojs-panorama) but the problem is not in it

Download example - https://drive.google.com/open?id=1lPd-6BRIsapaSXfpBxVqMWP2bW6QsQm8

**Comment by mister-ben** [comment]
I seem to remember Chrome used to not like having multiple video elements with the same source and would cancel the network requests. That isn't happening with this for me in your example on Chrome on my desktop or phone but is perhaps is what you see on the tablet. Does it make a difference if you change the sources to `blood.mp4?1`, `blood.mp4?2` etc?

**Comment by iuzhakov** [comment]
Hi @mister-ben 
Thanks for the quick reply
I tried adding a different source as "blood.mp4?1", "blood.mp4?2" but the error still reproduced. No difference

Can the video metadata whether been a reason the error? Perhaps a high bitrate, too many frames per second and etc?

**Comment by uBlock-user** [comment]
Hello this is happening on `http://kimcartoon.me/Cartoon/Justice-League-Action-Shorts/Episode-16` on Chromium and Firefox for me, I don't know why as of past 30 days.

**Comment by uBlock-user** [comment]
Line is `fn[Array.isArray(args) ? 'apply' : 'call'](_window2['default'].console, args);`

**Comment by gkatsev** [comment]
Unfortunately, I am unable to reproduce either problem on on desktop and the original issue on mobile either. The mp4 plays just fine for me.
@iuzhakov are you using the samsung browser or chrome for android on the tablet?

**Comment by iuzhakov** [comment]
Hi @gkatsev 
I am using chrome browser (v. 61.0.3163.98)

**Comment by lpsBetty** [comment]
I basically have this setup: http://hlsbook.net/how-to-serve-hls-video-from-an-s3-bucket
The video works everywhere, but in Android Mobile Chrome v72.

You can also see the described Error when emulating e.g. Galaxy on the Desktop Chrome on this site: http://hlsbook.net/how-to-serve-hls-video-from-an-s3-bucket ... just scroll down, you will see that the video will not load.

Has anyone solved this?

**Comment by knownasilya** [comment]
Seeing this as well.

**Comment by VladimirMikulic** [comment]
For developers using this library for developing Android app in JavaScript (Cordova, React Native etc.).
HLS streaming won't work on Android 9+ because of a Webview's security policy introduced in Android 9 (Pie) which prevents loading resources from insecure URLs (HTTP).

To disable this security feature, set `android:usesCleartextTraffic="false"` in your AndroidManifest.xml.

**Comment by gkatsev** [comment]
I would highly recommend investing in making sure that everything is over HTTPS over allowing HTTP, if possible.

**Comment by damjan25** [comment]
@knownasilya @lpsBetty @iuzhakov did you guys find any fix for this ? I am getting this on IOS ( video.js + ima sdk)

**Comment by qiumeihui** [comment]
> Hi @mister-ben
> Thanks for the quick reply
> I tried adding a different source as "blood.mp4?1", "blood.mp4?2" but the error still reproduced. No difference
> 
> Can the video metadata whether been a reason the error? Perhaps a high bitrate, too many frames per second and etc?

Hi, @gkatsev. Have you solved your problem? I had the same problem: 
```js
ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
```
I alse guess the reason is metadata error. Just as you said: a high bitrate, too many frames per second.
Looking forward to your reply.

**Comment by PaserSRL** [comment]
> > Hi @mister-ben
> > Thanks for the quick reply
> > I tried adding a different source as "blood.mp4?1", "blood.mp4?2" but the error still reproduced. No difference
> > Can the video metadata whether been a reason the error? Perhaps a high bitrate, too many frames per second and etc?
> 
> Hi, @gkatsev. Have you solved your problem? I had the same problem:
> 
> ```js
> ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
> ```
> 
> I also guess the reason is metadata error. Just as you said: a high bitrate, too many frames per second.
> But not sure how to solve it. Looking forward to your reply.

I have the same issue...
If I use VLC, Plyr, HLS.js works like a charm but with Video.js I always get error...

**Comment by gkatsev** [comment]
Please open a new issue with a test stream. We constantly work to improve our playback engine but we can only do so if we have sources to test with.
Also, worth testing with https://videojs-http-streaming.netlify.app, which always has our latest playback engine.
