### ISSUE TITLE
audioTracks of player object

### ISSUE THREAD

**Issue by EyalIsr** [videojs/video.js#4759]
It must be something that I'm missing...
But #3137 closed and I can't figure out why `player.audioTracks()`'s length always equals 0, although my mp4 has 4 audio streams (tested on chrome).
My final goal is to have mp4 with multiple audio tracks to be playable and audio tracks could be selectable from the `AudioTrackButton`.
Is it a browser compatability issue? Is it a container issue? 
Thanks

**Comment by gkatsev** [comment]
We probably aren't doing a good job at polyfilling the audio tracks capabilities. Right now, only techs and browsers that support audio tracks would end up filling that list out. Meaning that a browser like Safari with an HLS manifest that has multiple tracks or any browser that supports contrib-hls with a similar manifest would have items in the audio tracks. I'm not aware of any browsers that support multiple audio tracks in mp4s, though, Safari may.
I would probably suggest you transcode your mp4 to an HLS manifest with multiple audio streams, you're more likely to have support for audio tracks at this point.

Hope that help!
