### ISSUE TITLE
Hide controls after video launched

### ISSUE THREAD

**Issue by bozolozo** [videojs/video.js#4760]
Hello,

I would like to keep the big button to launch the video, and as soon as the user clicks on it the controls would disappear (and would not appear again on mouseover).

Also, if possible, I would like to disable the "start/pause" when the user clicks on the video.

Is there a way to do that ?

Thank you very much for your help !

**Comment by gkatsev** [comment]
You're probably looking for [`Player#controls`](http://docs.videojs.com/Player.html#controls). Just call `player.controls(false)` the first time the video is played.
Hope that helps.
