### ISSUE TITLE
Live Stream Dropped and not connected automatically

### ISSUE THREAD

**Issue by Lethea** [videojs/video.js#4761]
I have a middleware and wowza that handle ip / dvr camera . Sometimes some of the camera streams drops ( because of wowza or camera network problem or something else ) , as I see in the network tab of chrome, videojs tries a few times to get the chunklist, i guess there is a timeout , after a few seconds, it gave up trying and shows black screen ( then error message ) .
is there any plugin that handle this kind of streams that frequently drop . For ie : in my flash application, it shows the last success frame  and wait for the new frame to show ( froozen but no error showing ) 
What is the best way to handle this situation ? 
I can handle the error and reload the stream. unfortunately still the end user see the black screen or error message.
*Note: The clappr.io handle this , it shows loading dot and wait until  ts comes.

**Comment by gkatsev** [comment]
Are you using contrib-hls? Also, what version of video.js and contrib-hls? Also, what browser are you using?

**Comment by Lethea** [comment]
@gkatsev yes using contrib-hls
the version
@version 5.11.1
the video js
Video.js 5.20.4
Chrome 
Version 62.0.3202.94 
Windows 10 x64

**Comment by gkatsev** [comment]
That's weird. From a contrib-hls dev:
> Hmm I would expect that it would blacklist playlists til it gets to the last one and then retry requesting that indefinitely (trying the otehrs again when their blacklist duration has ended)

**Comment by gkatsev** [comment]
Would you be able to re-open this issue against the contrib-hls project? Would be great if you can provide a reduced test case for us to try.

**Comment by javaxiu** [comment]
https://flowplayer.com/i/flowplayer/plugins:rtmp-streaming-reconnect-a

it seems like there is no solution for auto-reconnect when using rtmp protocal ?
