### ISSUE TITLE
To add custom header in video src request

### ISSUE THREAD

**Issue by sajadhaja** [videojs/video.js#4770]
## Description
Is is possible to customize request header on to video server request.

My video was located in server, it have some authentication mechanism like JWT Auth2. How can i pass
access-token as request header using videojs.

## Results  
Header is not possible to customize.

### Expected
Will send access-token in request header.

### Error output
NA

### versions 6.4.0

what version of videojs does this occur with? 6.4.0
#### browsers
what browser are affected? All

**Comment by gkatsev** [comment]
What kind of videos are you playing? mp4s or HLS? And if you're using HLS, are you doing it with contrib-hls?
If you're playing back mp4s, unfortunately, there is no way to add custom headers as the requests are made by the browser itself and we have no access to it.
If you're using contrib-hls, please check out `beforeRequest` in it's [API docs](https://github.com/videojs/videojs-contrib-hls/#hlsxhr).

Hope this helps. Closing as it doesn't require action in video.js core, but if there's still a bug we can re-open or redirect the issue where appropriate.
