### ISSUE TITLE
Broken volume-bar and time tooltip styling after update from 5.4.6 to 6.5.0

### ISSUE THREAD

**Issue by sziberov** [videojs/video.js#4772]
## Description
All in the title. You can download archive and change versions directly in the end of demo.html file.

### Expected
Nothing visually changed.

### Actual
5.4.6:

![5 4 6_1](https://user-images.githubusercontent.com/7362968/33325330-9f73251e-d45a-11e7-83fa-6980eb0070a6.png)
![5 4 6_2](https://user-images.githubusercontent.com/7362968/33325331-9fb5727a-d45a-11e7-957a-66db85f6147d.png)
![5 4 6_3](https://user-images.githubusercontent.com/7362968/33325332-9fde43bc-d45a-11e7-9560-f4988f674924.png)
6.5.0:

![6 5 0_1](https://user-images.githubusercontent.com/7362968/33325335-a01eaec0-d45a-11e7-923e-a9a724ec2a66.png)
![6 5 0_2](https://user-images.githubusercontent.com/7362968/33325336-a0ae8fe0-d45a-11e7-96b1-513f9c670ec6.png)

#### videojs
5.4.6, 6.5.0
#### browsers
Tested on Opera Developer 51.0.2781.0
#### OSes
Tested on WIndows 10 64bit

#Download#
[video2.zip](https://github.com/videojs/video.js/files/1510301/video2.zip)

**Comment by gkatsev** [comment]
Looks like you have a pretty custom skin for Video.js. Video.js 6, as the version implies, is a major breaking change.
Specifically, we've changed how the volume and time tooltips work to make them more accessible to just simpler to work with. The new VolumePanel is a wrapper component that uses the VolumeControl and the MuteToggle. The time tooltips were refactored to be simpler code-wise but the markup for them changed as well.
Unfortunately, given that this is a major change, there isn't much that can be done other than updating the CSS to work with the new markup.

**Comment by sziberov** [comment]
@gkatsev Well, then I will stay on old ver, as there is no really a important things for me to update. Only more work.

**Comment by maluklo** [comment]
test 
https://unpkg.com/video.js@6.5.0/dist/video-js.css
https://unpkg.com/video.js@6.5.0/dist/video.js

vsg-skin.css --> ok working
yt-skin.css --> modify css

**Comment by gkatsev** [comment]
Makes sense, I don't think there's a lot of work there but hopefully at some point you'd be able to find the time to fixit and update.
