### ISSUE TITLE
missing src/js folder on the npm

### ISSUE THREAD

**Issue by geoshar** [videojs/video.js#4776]
why?:)

**Comment by gkatsev** [comment]
This is because our we use rollup to pre-build all our source files into a single file which is then referenced as `main` in our `package.json`.
The files should be available in `dist/` in npm.

**Comment by gkatsev** [comment]
Hope that helps.

**Comment by geoshar** [comment]
Thanks! But how will i connect some pieces, not the bundle file of the `dist/` folder?

**Comment by gkatsev** [comment]
Not sure what you mean? If you're using imports or require with things like webpack or browserify, it will just continue to work. The file that is set as `main` in the package.json isn't the pre-build UMD file that we recommend users who don't use bundlers use.

**Comment by geoshar** [comment]
Hm, I meant that i want not just to connect the entire 23k lines of code, but to have the ability to choose which modules to connect which one to not, etc, to use things of the player i use, making the code less than it is. Connecting things like on this file on the head 
[src/js/video.js](https://github.com/videojs/video.js/blob/master/src/js/video.js)
Is that possible to work with, or maybe that's totally useless? Maybe there's no reason at all to include the src/js for a reason that there's no modules you can exclude from the project?

**Comment by gkatsev** [comment]
The way that video.js is built, there isn't really an easy way to exclude pieces, though, that is something that we would like to add.

**Comment by geoshar** [comment]
Thanks! That's what i wanted to know. Now i understand.
I like the way JQuery is built with the `define`'s (or maybe there's a better way?), really nice would be to connect just the core of the player, with the minimal things on it(just to make things of the player work).
Would it be hard to rewrite the structure?
