### ISSUE TITLE
ModalDialog      How to hide?

### ISSUE THREAD

**Issue by a7517** [videojs/video.js#4781]

**Comment by gkatsev** [comment]
You can call `close` on it: http://docs.videojs.com/ModalDialog.html#close

Hope that helps.

**Comment by a7517** [comment]
"vjs-modal-dialog vjs-hidden  vjs-text-track-settings"
Shouldn't it be in the options settings?

**Comment by gkatsev** [comment]
not sure what you mean then. Do you want to disable text track settings dialog? Or do you want to close a particular dialog?

**Comment by a7517** [comment]
https://i.loli.net/2017/12/02/5a22293f050db.jpg

**Comment by gkatsev** [comment]
Ah, that's because the video.js css isn't being included. A lot of the elements are hidden using css and if you're not including the default css you're going to need to handle it yourself.

**Comment by a7517** [comment]
Is there no way to get rid of it before loading?

**Comment by gkatsev** [comment]
You can turn it off by adding this option:
```js
{
  "textTrackSettings": false
}
```
example: https://jsbin.com/qafuweb/2/edit?html,output

**Comment by a7517** [comment]
Thank you so much for helping out.

**Comment by gkatsev** [comment]
you're welcome.

For future reference, the clearer you can make the initial question, the best we can answer and minimize back and forth :)
This is why we have the issue template

**Comment by a7517** [comment]
> This is a modal window.

This section has not been removed

**Comment by gkatsev** [comment]
That's a separate component, I think it's the error display, which you can hide in a similar manner it's called `errorDisplay`.

**Comment by devstefancho** [comment]
> You can turn it off by adding this option:
> 
> ```js
> {
>   "textTrackSettings": false
> }
> ```

this works for me, Thanks!

`errorDisplay: false` also works
