### ISSUE TITLE
Can you provide a complete children array?

### ISSUE THREAD

**Issue by 0x2018** [videojs/video.js#4782]
https://github.com/videojs/video.js/blob/master/docs/guides/components.md

**This is incomplete and lacks a lot, such as: SubsCapsButton...**

> Player
> ├── MediaLoader (has no DOM element)
> ├── PosterImage
> ├── TextTrackDisplay
> ├── LoadingSpinner
> ├── BigPlayButton
> ├─┬ ControlBar
> │ ├── PlayToggle
> │ ├── VolumePanel
> │ ├── CurrentTimeDisplay (hidden by default)
> │ ├── TimeDivider (hidden by default)
> │ ├── DurationDisplay (hidden by default)
> │ ├─┬ ProgressControl (hidden during live playback)
> │ │ └─┬ SeekBar
> │ │   ├── LoadProgressBar
> │ │   ├── MouseTimeDisplay
> │ │   └── PlayProgressBar
> │ ├── LiveDisplay (hidden during VOD playback)
> │ ├── RemainingTimeDisplay
> │ ├── CustomControlSpacer (has no UI)
> │ ├── PlaybackRateMenuButton (hidden, unless playback tech supports rate changes)
> │ ├── ChaptersButton (hidden, unless there are relevant tracks)
> │ ├── DescriptionsButton (hidden, unless there are relevant tracks)
> │ ├── SubtitlesButton (hidden, unless there are relevant tracks)
> │ ├── CaptionsButton (hidden, unless there are relevant tracks)
> │ ├── AudioTrackButton (hidden, unless there are relevant tracks)
> │ └── FullscreenToggle
> ├── ErrorDisplay (hidden, until there is an error)
> └── TextTrackSettings

**Comment by a7517** [comment]
> vjs-play-control

How to hide this class?I did not find the document.

**Comment by gkatsev** [comment]
That section is pretty complete, though, it does not mention the SubsCapsButton. You didn't really provide a lot of info in your follow-up comment, though, it's probably the play toggle component?
