### ISSUE TITLE
In IE, when pause and play again, will auto  change playbackRate to 1

### ISSUE THREAD

**Issue by etc1208** [videojs/video.js#4784]
Hello, 
I find that in IE browser，when I pause the video,and then play again, the player will always change the playbackRate to 1.
how can i prevent this ? 
Thank you

**Comment by gkatsev** [comment]
That's a weird. Most likely a browser bug. A potential workaround would be to set `defaultPlaybackRate`. `player.defaultPlaybackRate(2)` as an example.

**Comment by etc1208** [comment]
@gkatsev I get it, Thanks a lot!
