### ISSUE TITLE
change flash@5.1.0 to @5.4.1

### ISSUE THREAD

**Issue by myuanyuan** [videojs/video.js#4785]
error throw when i use videojs in IE11 ,windows7 system, fininally i change flash@5.1.0 to @5.4.1
then it is ok;

**Comment by gkatsev** [comment]
What version of Video.js are you using? The latest Video.js 5.x uses the 5.4.1 swf already as does the lastest version of `videojs-flash` which is used for Video.js 6.

**Comment by gkatsev** [comment]
Closing, can be re-opened if necessary.
