### ISSUE TITLE
IE 11.0.9600.17843

### ISSUE THREAD

**Issue by myuanyuan** [videojs/video.js#4786]
## Description
It is available on some IE versions, and other versions are not available,
for example：on IE 11.0.9600.17843IS is available but on IE 11.0.9600.17843 is not available;
And, do not throw error

**Comment by gkatsev** [comment]
What is available on some IE versions but not others?

**Comment by myuanyuan** [comment]
The reason is: the flash version is wrong, and when I update the flash, it's normal, but the problem of the flash version should be in the videojs project.thanks
