### ISSUE TITLE
how to hide video when coming blank data from streaming

### ISSUE THREAD

**Issue by bhargavghodasara** [videojs/video.js#4788]
## Description
I am using rtmp live streaming.Its working for me.but i want to hide player when data is coming blank.and show when data is coming.

**Comment by gkatsev** [comment]
What do you mean by blank data? like the stream is live but there's no video data in it? I'm not sure we expose any such mechanism and I'm not even sure if such a thing exists.

@mister-ben, for better or worse, you're probably most familiar with rtmp, any ideas?

**Comment by bhargavghodasara** [comment]
means we have one rtmp link and its working fine with this library but we cant identify if device disconnected with server or its not sending streaming.

**Comment by mister-ben** [comment]
Trying to monitor the state from an RTMP client would be complex, and wouldn't work when you hide the player -- most browsers pause or unload the swf when hidden. I think you'd be better off monitoring this on the server somehow and have an endpoint you can poll to check the state.
