### ISSUE TITLE
HTML5 Video player doest not show markers tip on live server. Its working fine on localhost.

### ISSUE THREAD

**Issue by fahedusmanrana** [videojs/video.js#4789]
I have created a script for interactive video and I got some requirements to show markers in the process bar of video. I worked on that and it works perfectly on localhost but when I put it live, only markers are showing. The text with those markers is not showing. I have searched everywhere on google and lot on videojs guides but I am not able to fix it. Below is my code for creating markers:

```html
<video width="100%" controls id="sgm_2" class="video-js vjs-default-skin" preload="auto">
						<source src="video.mp4" type="video/mp4">
						<source src="video.webm" type="video/webm">
					  	<p class="vjs-no-js">Your browser does not support HTML5 video.</p>
					</video>
```
```js
var player = videojs('sgm_2');
			player.markers({
				markerTip:{
			        display: true,
			        text: function(marker) {
			        	return marker.text;
			        },
			        time: function(marker) {
				    	return marker.time;
				    }
			    }
			});
			player.markers.reset([
				{
			    	time: 10,
			    	text: "Caption 1"
			    },    
			    {
			    	time: 20,
			        text: "Caption 2"
			    },
			    {
			    	time: 30,
			        text: "Caption 3"
			    },
			    {
			    	time: 40,
			        text: "Caption 4"
			    }
			]);`
```
Can anyone please check what is the thing I am missing or what is wrong with this code? I have also use the funcltion of add instead of reset markers but no luck. I will appreciate any help.

Thank you.

**Comment by gkatsev** [comment]
You probably should open this issue against the markers plugin, though, if you can provide a reduced test case, we might be able to help as well.

**Comment by fahedusmanrana** [comment]
Thank you for your reply. Ok let me open this issue against marker plugin if they can help. I appreciate your passion of help.
