### ISSUE TITLE
RTMP not playing in chrome 62.0.3202.94

### ISSUE THREAD

**Issue by muralimnmcse** [videojs/video.js#4791]
## Description
After chrome's updation Version 62.0.3202.94 i am facing Cross-origin plugin content from http://vjs.zencdn.net/swf/5.3.0/video-js.swf must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. I am using RTMP for live streaming.
2.<source src="rtmp://URL&Stream" type="rtmp/mp4">
3.<video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640" height="450" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{techOrder: ['flash', 'html5']}">

#### OSes
Windows 7
### plugins
        <link href="http://vjs.zencdn.net/5.0.2/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/ie8/1.1.0/videojs-ie8.min.js"></script>
    <script src="http://vjs.zencdn.net/5.0.2/video.js"></script>

**Comment by gkatsev** [comment]
Yeah, unfortunately, that's just how flash is nowadays in chrome. We have a potential fix in https://github.com/videojs/videojs-flash/pull/39 but we want to make sure it doesn't break older browsers before deploying it. We'll probably port the fix from videojs-flash to v5 after we're sure it's good to go.

**Comment by muralimnmcse** [comment]
Thanks for your quick feedback. Tentatively when this fix can be expected in v5.
