### ISSUE TITLE
A network error caused the media download to fail part-way

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#4793]
## Description
When you rewind the video, an error occurs: "A network error caused the media download to fail part-way"

## Steps to reproduce

video width="640" height="360" style="display:block;margin-left:auto;margin-right:auto;" id="video_1" class="video-js vjs-default-skin" poster="/uploads/posts/2017-08/1502749904_game_of_thrones_season_7_2017.jpg" preload="none" controls data-setup="{ &quot;html5&quot;: { &quot;nativeTextTracks&quot;: true },&quot;playbackRates&quot; : [0.7, 0.8, 0.9, 1, 1.2, 1.5]}"
source src="/TS01/Game_of_Thrones_2017_S07/Game_of_Thrones.S07E03.mp4" type="video/mp4"
video

### Expected
rewind without error.

### Actual
Please describe what actually happened.

### Error output
A network error caused the media download to fail part-way

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
Version  5.20.4
#### browsers
 Google Chrome?
#### OSes
Windows  7, 8, 10
### plugins

1) videojs-resolution-switcher

2) Hotkeys

![ccd8804fa3](https://user-images.githubusercontent.com/10182540/33680196-826b4b0c-dac9-11e7-9ca1-8d55d33a3274.png)

**Comment by mister-ben** [comment]
This error is coming directly from the video element. When you seek the server is not responding in the way the browser expects. A common cause for this type of issue is the server not responding correctly to byte-range requests.

http://docs.videojs.com/tutorial-troubleshooting.html#problems-when-hosting-media

**Comment by surikat1978** [comment]
I use HFS for video distribution. Via port 32500. So how to get rid of the problem?
Thanks advance!
Regards!

**Comment by surikat1978** [comment]
This happens only for some users.  Not everyone.

**Comment by gkatsev** [comment]
I'm not sure this is something that we can fix in video.js. As @mister-ben said, it's mostly a server problem.

**Comment by yinbanghui** [comment]
@surikat1978 I had the same problem.  This happens only for some users. Not everyone.  Is realy a server problem ?

**Comment by ljcom** [comment]
I face this problem also. My ssue not about the error. The issue is how to retry again when the network recover or server already no busy. Can we show up the button to refresh?
