### ISSUE TITLE
playbackRate on change

### ISSUE THREAD

**Issue by azappa** [videojs/video.js#4798]
## Description
Get the event when user change playbackRate

## Steps to reproduce
1. Set two or more speeds as playbackRate when setup VideoJS instance
2. Play the video and change speed

### Expected
Get an event, like 'volumechange'

### Actual
No event is available. I can accomplish this task with mix of player.on('play') plus player.on('pause') but an active listener is more fit, for example if a video is ten minutes length and user change speed at 0:10 until he paused I don't know actual speed

#### videojs 6.2.8

**Comment by gkatsev** [comment]
You should be able to listen to [`ratechange`](http://docs.videojs.com/player#event:ratechange).
Hope that helps.
