### ISSUE TITLE
Is there a way to prevent the play button changing to a replay button after the video completes?

### ISSUE THREAD

**Issue by chrisbell08** [videojs/video.js#4802]
Is there an option to prevent replay on completion? The click  on the video to replay functionality I can fix just by overlaying a div I guess but the control bar play button switching to a replay button is a little trickier

**Comment by thijstriemstra** [comment]
listen for finish/complete event and remove the related css class (vjs-end or something)?

**Comment by gkatsev** [comment]
Maybe this is something that should be configurable? We had a lot of requests to add this in 5 and we liked this direction as well so we made this change but if not everyone likes it, maybe it should just be configurable. Thoughts @videojs/core-committers?

**Comment by chrisbell08** [comment]
I think that would be handy,

I had to do it with this line of code in the ended event:
this.videoHandler.controlBar.playToggle.removeClass('vjs-ended');

an option would be much cleaner

**Comment by ldayananda** [comment]
An option seems reasonable

**Comment by arshadkazmi42** [comment]
I can take this up. if its still available

**Comment by BrandonOCasey** [comment]
Yeah I think this is something we would still like an option for, if you want to take it on @arshadkazmi42 , go for it! 👍
