### ISSUE TITLE
Need help for Videojs and Dailymtion for version 5.0+

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#4810]
Hi, 
I need help and contributors to create a working version for video.js 5.0+
This is a very basic version

I started a new project here:
https://github.com/onigetoc/videojs-5.0-dailymotion

Basic version on Plunker : https://plnkr.co/edit/s6Ql4I324cYioADy9CPS?p=preview

**Comment by gkatsev** [comment]
Have you tried one of the existing dailymotion plugins? Like https://github.com/benjipott/video.js-dailymotion
Also, what you have in the example seems to work. Unfortunately, we can't provide help on really generic "need help" questions and need more specific questions to provide help with. If you're asking for contributors, well, anyone feel free to join in :)
Hope your project is a success.

**Comment by onigetoc** [comment]
This is a plugin do not work on Videojs 5.0. 
There's any help, any reply to issues, it's seem abandoned.
