### ISSUE TITLE
Feature request: broadcast support

### ISSUE THREAD

**Issue by burstpay** [videojs/video.js#4811]
Hello

Is it possible to add broadcast functionality, to stream a video from the pc to the smart tv? Like youtube does?

Are there any plans for implementing such functionality?

Thank you very much!

**Comment by gkatsev** [comment]
We're unlikely to be adding anything like that ourselves. There are a few chromecast plugins for video.js (like https://github.com/benjipott/video.js-chromecast) that can have you push the video from your device to a chromecast. There are also plugins for adding an airplay button (like https://github.com/jgubman/videojs-airplay).

Hope that helps.
