### ISSUE TITLE
player pause/play with a tap on mobile

### ISSUE THREAD

**Issue by SolmazKh** [videojs/video.js#4817]
Hello.
On smartphones if you tap on video it just showing controls so you need to tap second time on the controls to play/pause. Is there any way to video.js player act similar on mobile as on desktop. One tap on video (not controls) play second tap pause?

**Comment by gkatsev** [comment]
You probably can add this functionality by listening to the `click` event on the player and then toggling playback.

Hope that helps.

**Comment by SolmazKh** [comment]
I actually want the "touch" event of mobile.Should I add it to the player('#player-id')?

**Comment by gkatsev** [comment]
You should still be getting a click event on mobile as well, but you can also listen to the `tap` event we trigger.
Yeah, it's basically just:
```js
var player = videojs('#player-id');
// can also be `tap` or `touchend` or some other event instead of `click`
player.on('click', function() {
  if (player.paused()) {
    player.play();
  } else {
    player.pause();
  }
});
```

**Comment by markandcurry** [comment]
@gkatsev - That solution just seems to make the player deactivate. Do you have any other ideas? I'd just like it to pause when it's touched the first time. thanks

**Comment by ericleroy01** [comment]
click and tap event are not fired on android (only tested with android v8)

tap only display controlbar.

Is there a a way to overrid tap event managed by player ?
