### ISSUE TITLE
 Problem to load a video and several audio sources at the same time before playing

### ISSUE THREAD

**Issue by xMADOXX** [videojs/video.js#4818]
## Describe
I would like to make sure that all my medias are downloaded before playing and at any time during the video, if for example the user switch the timecode of the video 

Ex: video starts at 0:00, then user switch to 1:00. Then before playing the video + all of my audio files, the player will load 30s of each media and after that he will start playing.

### Actual
For the moment, the video is well treated by videojs with a buffer but I would like to be sure that all medias are treated by the framework also. So my question would be : How can I add a new source to videojs, and be sure that videojs will take all my medias in consideration ?

Thanks in advance for your help!

#### videojs
what version of videojs does this occur with? Video.js V5.20.4
#### browsers
what browser are affected? Google Chrome Version 62.0.3202.94
#### OSes
what platforms (operating systems and devices) are affected? Windows 10
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Unfortunately, there really isn't a good way to forcibly preload preload data in browsers. Though, to make sure that multiple videos and audio are at least preloaded partially, you could resort to loading in multiple players/video elements. Each one will preload the video and you can either swap out the players as you're switching media or rely on the browser cache when you put the other video into the main player.

**Comment by gkatsev** [comment]
Actually, now that I'm thinking about it, it might be possible to fully preload the data using service workers assuming that the media requests come are directed through service workers.
If media requests don't come through the service workers, you'll probably need to do some stuff with MSE.
Multiple players might help out enough for the least amount of work.

Sorry I don't have a better answer, hope the above helps.
