### ISSUE TITLE
Show captions in block on full size video and font-size isn't changing

### ISSUE THREAD

**Issue by Syedwaheed** [videojs/video.js#4820]
I m using the video-js 5.19.2 and i have customized it to what i want.I want to show the caption in the block on full screen and font-size is also not changing on full screen. I have added this
```
.video-js .vjs-captions { font-size: 20px; }
.video-js.vjs-fullscreen .vjs-text-track { font-size: 3em; }
```
in the css file of video-js but font-size is not changing.
Following is the images of the font-size.
![capture](https://user-images.githubusercontent.com/14071753/33997998-0e301142-e108-11e7-920f-e28b4b851621.JPG)
![capture1](https://user-images.githubusercontent.com/14071753/33997999-0e63dbb2-e108-11e7-8ad4-152792c78f11.JPG)

**Comment by gkatsev** [comment]
Unfortunately, this isn't something that's supported. Also, The caption size should be changing when we go fullscreen (it may only change once a new caption is loaded, though, we try to change it immediately).
The way that vtt.js works, the library we use for captions, unfortunately, adds the styles inline and doesn't really support overrides like that.
Also, the classes you're using seem to be from a long time ago in vjs 4 before we switched over to vtt.js.

Hope that helps, sorry that this isn't supported.

**Comment by Syedwaheed** [comment]
hi @gkatsev for your prompt response. Can you please tell me how do i change with new caption or add vtt.js or anything that can make the font-size pleasant. Thats all i left for my player to look good. I have used the new video.js version and have seen the captions in full screen that looks in block with average font-size. I dont want to move to newer version as it gives error on my playlist for hd. So if anything i could do to make a font-size a bit small would be best way to move on with this player. Thanks in advance.
