### ISSUE TITLE
When the player is embed in an iframe, keyboard-only users are unable to select a caption track.

### ISSUE THREAD

**Issue by mfairchild365** [videojs/video.js#4821]
## Description
When the player is embed in an iframe, keyboard-only users are unable to select a caption track.

Example: 
https://mfairchild365.github.io/notes/vjs-caption-button-bug.html

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Using Google Chrome 
2 .go to the above example
3. Press the `tab` key until you reach the captions button and press `enter`
4. the captions list shows, but you are unable to select a track by pressing arrow keys.

### Expected
[WCAG 2.1.1: Users should be able to select a captions track by using a keyboard only](https://www.w3.org/WAI/WCAG20/quickref/#qr-keyboard-operation-keyboard-operable)

### Actual
Focus was never sent to the sub-menu (captions list), and thus was inoperable. This causes a failure of WCAG 2.0 Level A

### Error output
none

## Additional Information

This appears to be a result of https://github.com/videojs/video.js/pull/4607 

However, I believe the logic in that should have been `if (ios && in-iframe) { dontFocus() }` instead of `if (!IS_IOS && !isInFrame()) { doFocus()}` (this is causing the bug in all browsers).

Additionally, I don't see the behavior that the PR was trying to fix when I test with IOS and remove that condition. Is it even needed anymore? 

## Proposal

Revert https://github.com/videojs/video.js/pull/4607

**Comment by gkatsev** [comment]
Good catch, definitely something we should fix. Yeah, unfortunately, we still see this on iOS, we probably want to invert the check like you suggested. The conditional probably needs to be `!(IS_IOS && isInIframe)`. Would you be able to submit a PR?

**Comment by mfairchild365** [comment]
I believe that would still violate WCAG for IOS. Is there another approach that won't break accessibility?

**Comment by mfairchild365** [comment]
Actually, I just tested IOS Safari + Voice Over and it appears to be functional without sending focus. *magic*. I will submit a PR.
