### ISSUE TITLE
.srt to .vtt function

### ISSUE THREAD

**Issue by payflix** [videojs/video.js#4822]
I'm using **VideoJS 6.5.1**
I always had to convert my .srt files to .vtt for videojs to pick it up, is it possible to use my small function in the videojs library to convert srt to vtt syntax?
Does anyone know where I can use my function before videojs parse the subtitle?
```
function srt2vtt(srt) {
		var vtt = ''
	 	srt = srt.replace(/\r+/g, '');
	  	var list = srt.split('\n');
	  	for (var i = 0; i < list.length; i++) {
	  		var m = list[i].match(/(\d+):(\d+):(\d+)(?:,(\d+))?\s*--?>\s*(\d+):(\d+):(\d+)(?:,(\d+))?/)
	  		if (m) {
	  			vtt += m[1]+':'+m[2]+':'+m[3]+'.'+m[4]+' --> '+m[5]+':'+m[6]+':'+m[7]+'.'+m[8]+'\n';
	  		} else {
	  			vtt += list[i] + '\n'
	  		}
	    }
	    vtt = "WEBVTT\n\n\n" + vtt
	    vtt = vtt.replace(/^\s+|\s+$/g, '');
	    return vtt
	}
```

**Comment by OwenEdwards** [comment]
We've talked about doing something like this previously, but the main problem is that video.js sometimes relies on the browser's native support for text tracks, so this patch to handle SRT tracks wouldn't work in that case.

But take a look at my test implementation, at https://github.com/OwenEdwards/video.js/tree/support-srt-text-tracks, which uses a similar SRT to WebVTT conversion, from code developed by @silviapfeiffer. You can get it working in a similar way.

**Comment by mister-ben** [comment]
Another approach would be to convert the SRT to VTT, create a blob URL with `URL.createObjectURL()` and add that URL with `addRemoteTextTrack()`.

**Comment by OwenEdwards** [comment]
It **would** be nice if there was a way to hook into the video.js text track file handling so that a user could add essentially a text track _tech_ which could do this kind of conversion straight into the internal cue format, rather than having to convert to WebVTT as an intermediate format.

Feel free to propose something with a PR :-)
