### ISSUE TITLE
PrettyPhoto+Video.Js

### ISSUE THREAD

**Issue by vdanelia** [videojs/video.js#4830]
Hello Can anyone tell me how to configure Videojs with PrettyPhoto
I want that videos played by video js
Thank you

**Comment by gkatsev** [comment]
Not quite sure what PrettyPhoto is but assuming it's a lightbox/overlay type thing, you'd want to create a player inside of the PrettyPhoto element when it opens and then dispose the element when it closes.
You'd probably have more luck asking in a more general forum, like StackOverflow, about how to use PrettyPhoto.
