### ISSUE TITLE
VIDEOJS: ERROR: TypeError: this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by machao669** [videojs/video.js#4832]
The below errors happen after showing another page(without video tag) from original page(videojs with flash tech). My app is a single application page based on react.Switch from the live component to another component.How can I resolve it! Thanks Thanks Thanks...
![screen shot 2017-12-21 at 18 24 49](https://user-images.githubusercontent.com/14209984/34252065-2133e15e-e67d-11e7-9cd4-f7f677b6e40a.png)
![screen shot 2017-12-21 at 18 25 09](https://user-images.githubusercontent.com/14209984/34252066-24074f42-e67d-11e7-907b-636a864dacbd.png)

**Comment by gkatsev** [comment]
This generally means that the swf hasn't loaded properly for whatever reason. In chrome, it often happens if the player is smaller than 400x300 but it can happen for many reasons. Do you have a reduced test case for this?

**Comment by CNzxy0820** [comment]
> This generally means that the swf hasn't loaded properly for whatever reason. In chrome, it often happens if the player is smaller than 400x300 but it can happen for many reasons. Do you have a reduced test case for this?

hello,when I used a click event to make the video display: block or none;  Then it show this ERROR
![image](https://user-images.githubusercontent.com/51101525/72308470-90887b00-36b7-11ea-8cdc-cc78b85067ca.png)

**Comment by CNzxy0820** [comment]
> > This generally means that the swf hasn't loaded properly for whatever reason. In chrome, it often happens if the player is smaller than 400x300 but it can happen for many reasons. Do you have a reduced test case for this?
> 
> hello,when I used a click event to make the video display: block or none; Then it show this ERROR
> ![image](https://user-images.githubusercontent.com/51101525/72308470-90887b00-36b7-11ea-8cdc-cc78b85067ca.png)

video.js:23216 VIDEOJS: ERROR: TypeError: this.el_.vjs_getProperty is not a function
    at Flash.currentTime (video.js:13981)
    at Player.techGet_ (video.js:10579)
    at Player.currentTime (video.js:10703)
    at PlayProgressBar.updateDataAttr (video.js:4184)
    at Player.bound (video.js:23004)
    at HTMLDivElement.bound (video.js:23004)
    at HTMLDivElement.data.dispatcher (video.js:22790)
    at Object.trigger (video.js:22917)
    at Player.trigger (video.js:1553)
    at Player.<computed> [as handleTechTimeupdate_] (video.js:12510)
