### ISSUE TITLE
Disable function through plugin

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#4837]
## Description
I know I can add features through a plugin but can I disable a function too? Currently the Playback Rates Menu opens on hover. In [my theme](https://github.com/edwinbradford/videojsneue) it opens on click for which I had to disable the `clickHandler(event) {...}` in [playback-rate-menu-button.js](https://github.com/edwinbradford/videojsneue/blob/master/src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js). Everything works as expected but it would be nice to move this single JavaScript change to a plugin so I can use the VideoJS JavaScript library instead of having to build my own.

I'd like to know if this is possible and if so can anyone point me to some reading material or documentation.

Thanks.

**Comment by gkatsev** [comment]
The best direction is probably to extend the default playback rate menu button and then make the clickHandler a no-op (or only do what you want it to do).
For example:
```js
const PRMB = videojs.getComponent('PlaybackRateMenuButton');
class MyPRMB extends PRMB {
  handleClick() {}
}
```

**Comment by edwinbradford** [comment]
Thanks. I'll give it a go and post back.

**Comment by edwinbradford** [comment]
I'm getting the following error in the Chrome console:

> Uncaught TypeError: Class constructor MyPRMB cannot be invoked without 'new'

Here is my code:

```JavaScript

    const PRMB = videojs.getComponent('PlaybackRateMenuButton');

    class MyPRMB extends PRMB {
      handleClick() {
        videojs.log('Playback Rate Menu Button Clicked');
      }
    }

    videojs.registerPlugin('MyPRMB', MyPRMB);

    var player = videojs('videoJSElement'); // Where videoJSElement is the ID of my video tag 
    player.MyPRMB();

```
I managed to reproduce the other examples from the [Plugins Guide](http://docs.videojs.com/tutorial-plugins.html) without problem so I think its something to do with extending a component that's causing the issue.

**Comment by gkatsev** [comment]
Ah, it's not a plugin, you'd need to register it as a component and then use that component instead of the default playback rate menu button component:
```js
videojs.registerComponent('MyPRMB', MyPRMB);

var player = videojs('vjsEl', {
  playbackRates: [0.5, 1, 1.5, 2],
  controlBar: {
    myPRMB: {},
    playbackRateMenuButton: false
  }
});
```

**Comment by edwinbradford** [comment]
Thanks its working now. I just had to move the class declaration above the component registration in your example and then it worked straight away.

**Comment by gkatsev** [comment]
Awesome, glad you got it working. Also, feel free to drop by our [slack](http://slack.videojs.com) for questions (though, we'll be away for about a week :)

**Comment by edwinbradford** [comment]
Thanks, I really appreciate your helping out, Have a great break :)
