### ISSUE TITLE
Does videojs support scrubber previews?

### ISSUE THREAD

**Issue by dandelionred** [videojs/video.js#4839]
Here http://docs.videojs.com/docs/guides/tracks.html it is said vjs supports VTT but text tracks only. I wonder if there is some _official_ way of VTT scrubber previews in vjs?

I've found this plugin https://github.com/dirkjanm/videojs-vtt-thumbnails idk how well it works. I'd prefer stable code from the vjs devs but ...

**Comment by misteroneill** [comment]
It's certainly supported, but only though community plugins like the one you mentioned.

**Comment by gkatsev** [comment]
metadata text tracks are a great way of specifying this information as that plugin specifies (or rather JWPlayer). We don't maintain such a plugin and unlikely to do so.
Best to reach out to the maintainer of that plugin and offer help if it is no longer maintained or has issues. We'd be happy to help answer issues related to it on our [slack](http://slack.videojs.com).
Hope that helps.
