### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media

### ISSUE THREAD

**Issue by avinash-chopra** [videojs/video.js#4843]
Hi All,
I am facing a serious problem. I am developing an encrypted video player using Chromium Embedded Framework and video js.
Chromium Embedded Browser uses Chromium Browser so if our video plays fine in Chromium Browser than it will work on Chromium Embedded Framework.

Our Problem -
I have an encrypted WebM file when I am trying to play this encrypted video file by using video js and videojs-contrib-hls then it always shows error message "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media" on the Chromium Browser.
It is working fine in all other browsers like Chrome, IE, Opera etc. But I have to use Chromium Browser because there is no other option of Controlled Browser in .Net which is just only a Chromium Embedded Framework.
When I play an unencrypted video file it plays fine so there is no issue with codecs so this is an issue of video js.
I am attaching zip file having codes and please change the encrypted-key file path in .m3u8 file to play the example [Sample.zip](https://github.com/videojs/video.js/files/1587273/Sample.zip) and please also add the CDN of video js and videojs-contrib-hls.

## Steps to reproduce
Play a simple encrypted file (should be in .WebM).

### Error output
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media
![chromium error](https://user-images.githubusercontent.com/20415299/34356190-d8501294-ea61-11e7-94d1-8b65e4787960.png)
#### videojs
Video.js 6.2.5
#### browsers
Chromium
Version 65.0.3305.0 (Developer Build) (64-bit)
#### OSes
Tested on Windows 10
### plugins
videojs-contrib-hls @version 5.12.2

**Comment by mister-ben** [comment]
Despite the file extension these media segments are MPEG-TS with h.264/AAC-LC, not WebM, which is why this works in the other browsers. Chromium doesn't support h.264/aac.

For Chromium, DASH/WebM with ClearKey would be more suitable than [HLS which can only be used with MPEG-TS and fMP4](https://tools.ietf.org/html/rfc8216#section-3.1)

**Comment by camille666** [comment]
yeah, I also encounter this issues. is there some way to solve this error?

**Comment by avinash-chopra** [comment]
Hi @camille666, Can you explain your issue?

**Comment by anjaneyulugulla** [comment]
yes same issue 7.5 version also

**Comment by avinash-chopra** [comment]
@anjaneyulugulla, That issue was not from the videojs side but it's due to media codec or due to the media file.
