### ISSUE TITLE
play rtmp stream use flash, when i hide it will be through a error

### ISSUE THREAD

**Issue by ch-zgh-1993** [videojs/video.js#4844]
i use videojs play stream, use type of rtmp/flase, when i do : myVideo.style.display = 'none';
it would throw error like this: 
           ##  "duration unavailable on Flash playback technology element"
will, i do this: myVideo.hide(), it have the same error.
then, i use hide(), next set myVideo display "none",  when i need, i would set myVideo "block", set it show();
it will throw error like:
           ## currentTime unavailable on Flash playback technology element
i want to konw which Method can work with my scene. or really i need to dispose myVideo and reStart ?
thank you!

**Comment by mister-ben** [comment]
This is because browsers pause or unload hidden SWFs. Disposing and reinitialising would be better for a player using the Flash tech.
