### ISSUE TITLE
Expanding height of control bar on smaller devices

### ISSUE THREAD

**Issue by SolmazKh** [videojs/video.js#4845]
Hello
I was wondering is there any way to increase the height of control bar on mobile and other smaller devices?
The control buttons are too small to interact smoothly with video player.
I am using the latest version of videojs.

**Comment by misteroneill** [comment]
I believe most of the styles/sizes in the player are `em`-based, so increasing the font size with your own custom CSS could work, perhaps targeting with media queries as needed.

**Comment by gkatsev** [comment]
Yup, the easiest way is to set the `font-size` either per-component, or just on the `.video-js` based on media queries or however.
