### ISSUE TITLE
can i know the stream when i can see the picture ?

### ISSUE THREAD

**Issue by ch-zgh-1993** [videojs/video.js#4848]
i use the VideoJS play a stream, but sometimes it would connecting, but not have the picture .
i want to konw there is any api method have the ability. to judging  if the picture appears.

thank you!

**Comment by misteroneill** [comment]
If I understand, you want to know when playback can begin?

The best choice there is probably the `canplay` event, which should be triggered on the player when it can begin playback. We usually recommend referring to [the W3C standard events](https://dev.w3.org/html5/spec-preview/media-elements.html#mediaevents) for tracking changes in player state.

**Comment by gkatsev** [comment]
The earliest event that could potentially have enough info display any frames of data would be `loadedmetadata`. `canplay` will trigger when you also have enough data to actually start playing the video.
Also, the `preload` attribute, as well as OS and device, can affect how these are triggered or when the events are triggered.

Hope that helps.
