### ISSUE TITLE
Unable to play webm/ ogv videos in IE.

### ISSUE THREAD

**Issue by NavaneethSankaradevan** [videojs/video.js#4850]
Hi,
I am currently implementing video playback in my own application. When I tried to play WEBM and OGV videos in IE11 using videojs as like in below code.

# HTML
```
<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268"  data-setup='{ "playbackRates": [0.5, 1, 1.5, 2],"loopbutton": true  }'>
<source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
</video>
```

# **JS:**
```
videojs('my_video_1', {
        plugins: {
          loopbutton: true 
        }
      }, function () {
        // Player (this) is initialized and ready.
      });
```
I am facing the below issue only in IE.

issue: VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video. [object Object] 

The same is works fine in chrome and firefox. Please suggest me is there is any solution to overcome this problem ?

**Comment by kocoten1992** [comment]
you could use x264 mp4 as backup (all browser support x264 mp4), more about that here https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

```
<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268"  data-setup='{ "playbackRates": [0.5, 1, 1.5, 2],"loopbutton": true  }'>
    <source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
</video>
```

**Comment by sarathmunusamy** [comment]
@kocoten1992 you mean I need to phyiscally convert my webm/ ogv files into mp4 format and then write the below code.
`<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268"  data-setup='{ "playbackRates": [0.5, 1, 1.5, 2],"loopbutton": true  }'>
    <source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
</video>`

if so, why i need write `<source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>` this line as i already done the mp4 conversion. i am little confused with your above comment 

> you could use x264 mp4 as backup 

it would be more helpful if you clarify this. Thank you

**Comment by kocoten1992** [comment]
x264 is an old codec

With the same size, x264 video quality is worst than vp9 (webm) or with the same quality, file size of vp9 is smaller than x264

That why we priority vp9, then if browser don't support then x264

Hope that clear the confusion :+1:

**Comment by kocoten1992** [comment]
FYI, between codec, it usually go like this:

AV1 (around 2019) > x265 (proprietary - no browser support yet) > vp9 > x264 ~ vp8 ...

**Comment by sarathmunusamy** [comment]
@kocoten1992  Sorry for asking again. i am very new for this video stuff. The comments which you have mentioned above having more technical stuff. i need to know the two points.

1.  you (@kocoten1992 ) told like i could use x264 mp4 as backup . is it mean I need to conver my webm/ ogv video to Mp4 ? (format conversion).

2. If first point is Yes, why need following code `<source src="http://vjs.zencdn.net/v/oceans.webm" type='video/webm'>` as I already changed my video from webm to mp4

3. If First point is No, how should i actually want to do this. 

Please, help me on this. Thank you.

**Comment by kocoten1992** [comment]
@sarathmunusamy 
1. yes, you need convert webm to mp4
2. if you are new, just use mp4 from now on, it will work on every browser (remove webm src altogether)

**Comment by gkatsev** [comment]
IE doesn't support webm and ogv video. I believe that Edge now supports it in the latest version of win 10, though. Also, yeah, using mp4 with h264 will probably cover the most browsers, still. Thanks for answering @kocoten1992!
