### ISSUE TITLE
I have added the videos js and css files, but when I try to embed the code in the html and open the webpage, it does not embed anything. I am not able to see the vjs-big-play-button or vjs-loading-spinner loaded in the html. Am I missing something? 

### ISSUE THREAD

**Issue by a-birla** [videojs/video.js#4854]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
It's impossible to say what's missing from so little information. Please provide a reduced test case so we can see what you have.

**Comment by gkatsev** [comment]
Please open a new issue with the issue template filled in as thoroughly as possible. Best to create a reduced test case as well. As @mister-ben said, there isn't enough information to know where to start investigating the issue.
