### ISSUE TITLE
Video is starting playing from beginning when the progress bar is clicked in Chrome.

### ISSUE THREAD

**Issue by sarathmunusamy** [videojs/video.js#4856]
Hi,

I am facing one strange issue in videojs. In Chrome when I clicked the progress bar the video is start playing from the beginning but, working fine in all other browsers.

Also, I am facing this issue only when I use video from my local server, eg: http://localhost/MFWA-Test/sample.mp4 but working fine when using other video url eg: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 . 

It would be helpful if I get any help for your end. Thank you.

**Comment by mister-ben** [comment]
This happens when your server doesn't properly support [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). Instead of sending the part of the video seeked to, it's sending the start of the file.

**Comment by gkatsev** [comment]
Closing as this has been answered. If you still have questions, please feel free to reply. A closed issue is temporary at best and can always be re-opened plus discussion can continue.
