### ISSUE TITLE
Videojs: cannot play videos in Safari

### ISSUE THREAD

**Issue by sarathmunusamy** [videojs/video.js#4863]
Hi Team,

While Implementing the video playback in my application using videojs, I am facing one issue in Safari browser. none of the videos (all format) are playing in safari but working fine in all other browser. 

I am facing the following issue:
![screen shot 2018-01-08 at 2 04 35 pm](https://user-images.githubusercontent.com/22632082/34663621-abcd6764-f47d-11e7-840c-1d2a70c36725.png)

Please find the network call of speific video request:
![screen shot 2018-01-08 at 2 07 56 pm](https://user-images.githubusercontent.com/22632082/34663634-b96dab04-f47d-11e7-9be7-423e329a07ab.png)

I would be more helpful I get any help from your end. Thank You

**Comment by mister-ben** [comment]
This sounda like a case of not implementing range headers on the server. Playback on Safari will fail in this case, and you may notice problems with seeking on other browsers.

See e.g. http://docs.videojs.com/tutorial-troubleshooting.html#problems-when-hosting-media

**Comment by gkatsev** [comment]
Are you able to play other videos, like our [oceans videos](https://vjs.zencdn.net/v/oceans.mp4)? But @mister-ben is probably right that it's most likely a hosting issue.
Going to close this but let us know if that isn't the case and we can re-open if necessary.

**Comment by Parpita** [comment]
Hi All,
I am facing also the same problem in safari browser while using video js. please, anyone can suggest me.

Thank you

**Comment by gkatsev** [comment]
Have you looked through the troubleshooting docs above or tried playing back other videos?
If after doing that it still isn't working, can you create a reduced test case and open a new issue following the issue template? Thanks.

**Comment by dancingmonkey** [comment]
> This sounda like a case of not implementing range headers on the server. Playback on Safari will fail in this case, and you may notice problems with seeking on other browsers.
> 
> See e.g. http://docs.videojs.com/tutorial-troubleshooting.html#problems-when-hosting-media

So is this ever going to be supported on netlify?
