### ISSUE TITLE
Player "my_video" is already initialised. Options will not be applied.

### ISSUE THREAD

**Issue by davy-gan** [videojs/video.js#4865]
![1ac9c493-574e-42b2-bbed-92fb371a2446](https://user-images.githubusercontent.com/21240946/34703313-389547f2-f52d-11e7-90d2-88d183849733.png)
![3465d849-1e59-4543-9c8a-5be2730ebab2](https://user-images.githubusercontent.com/21240946/34703315-38f5ac1e-f52d-11e7-988a-d4333ea494ef.png)
![63959764-f94c-4a6c-8597-aa275d917535](https://user-images.githubusercontent.com/21240946/34703316-392bf83c-f52d-11e7-906d-3d9b5c7efc5d.png)
![cdabe697-4710-4b83-b8a4-5ca414448c91](https://user-images.githubusercontent.com/21240946/34703317-39889af6-f52d-11e7-8696-f8931469bf31.png)
![e1847260-f35b-4b98-bafd-1414e186a976](https://user-images.githubusercontent.com/21240946/34703318-39d1767c-f52d-11e7-948a-2233c46ed3a8.png)

**Comment by davy-gan** [comment]
In a single page application, the first visit to the component can be used normally, but the second visit again, this error occurs, options can not be injected into

**Comment by mister-ben** [comment]
You probably need to `dispose()` the player. I think this is Vue but it might be useful to compare the approach taken in the [react guide](https://github.com/videojs/video.js/blob/master/docs/guides/react.md).

**Comment by gkatsev** [comment]
`videojs()` only creates the player once and does not update options when called again with different options. We're in the process of adding a better way of getting a player: https://github.com/videojs/video.js/pull/4836
If you want to reuse the same player, a lot of the options do have setters that you can call once the player has been created -- `player.aspectRatio('430:265')` for example, unfortunately, `setPlaybackRates` is missing currently.
However, it's possible that what you want is to actually dispose the player and recreate it each time completely.

Also, there's an issue with an example of using Video.js with Vue in an issue: https://github.com/videojs/video.js/issues/4167#issuecomment-344731747

**Comment by davy-gan** [comment]
Thank you very much. According to your guidance, I have now solved this problem @gkatsev @mister-ben

**Comment by gkatsev** [comment]
Awesome, glad to hear it.

**Comment by bevikram** [comment]
@davy-gan, Do you mind sharing the solution, I have the same isssu. the video does not show up second time.

**Comment by Amily008** [comment]
How did you solve this problem

**Comment by denisk1984** [comment]
var oldPlayer = document.getElementById(video_id); 
videojs(oldPlayer).dispose();

**Comment by denisk1984** [comment]
`var oldPlayer = document.getElementById(video_id); 
            videojs(oldPlayer).dispose();`

**Comment by BonBonSlick** [comment]
**dispose will destroy DOM elemtn, new initialization is not possible.**

**Comment by talhabaig** [comment]
I also face the same problem. Videojs gets automatically initialized

Just Remove "data-setup" and the player will not initialize by itself

![image](https://user-images.githubusercontent.com/12812266/106105778-583ec800-6166-11eb-858e-6cb76006fb21.png)

**Comment by bikash-s-bhandari** [comment]
![1d72d7bf5d9a8b8e09ec008bb86e9115f7bfc77d](https://user-images.githubusercontent.com/33630192/148492519-bab724a4-5080-4d30-b68f-ac26dd05314c.gif)
