### ISSUE TITLE
I can not play my stream at my phone but it works at pc

### ISSUE THREAD

**Issue by Faterjames** [videojs/video.js#4867]
it works well while using pc to watch the stream on the web page ,but when i use my phone , it says  no compatible sourece was found for this media.

```
<!DOCTYPE html>
<html>
<head>
<title>RTMP Embed</title>
<link href="//vjs.zencdn.net/6.4.0/video-js.min.css 

" rel="stylesheet">
<script src="//vjs.zencdn.net/6.4.0/video.min.js 

"></script>
<script src="https://cdn.jsdelivr.net/npm/videojs-flash@2/dist/videojs-flash.min.js 

"></script>
</head>
<body>
<h1>RTMP Embed</h1>
<video id="streamContainer" class="video-js vjs-default-skin" controls preload="auto" width="640" height="320" data-setup='{ "techorder" : ["flash", "html5"] }'>
<source src="rtmp://192.168.31.240/rtmp/live 

" type='rtmp/flv'>
</video>
<p id="text1"></p>
</body>
<script src="app.js"></script>
</html>
```

**Comment by mister-ben** [comment]
RTMP requires Flash, which mobile devices don't support. Consider using HLS output, which mobile devices support natively and Video.js can play on desktop browsers with [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls).

**Comment by gkatsev** [comment]
As @mister-ben said, you cannot play RTMP on mobile devices as it requires Flash.

**Comment by ROBERT-MCDOWELL** [comment]
unless if someone create an JS rtmp socket
