### ISSUE TITLE
Recommended way to switch source from rtmp/mp4 to application/x-mpegURL ? 

### ISSUE THREAD

**Issue by cAstraea** [videojs/video.js#4869]
## Description
I want on browsers that support flash to play the stream in the flash version but when flash is not supported to play the HLS version ?
I'm thinking could go a way to detect mobile and straight up inject the full HTML with video and source but maybe there's a better way ?  

Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.
Tried to see if I could change the source on the fly but seems it's not possible 
http://jsbin.com/suqahe/edit?html

## Results
http://output.jsbin.com/suqahe
### Expected
Please describe what you expected to see.
Well I expected it not to work since it can't switch from flash to html5 ..

### Error output
If there are any errors at all, please include them here.
videojs-contrib-hls.js:2056 Uncaught TypeError: _videoJs2.default.AudioTrack is not a constructor
    at Object.AUDIO (videojs-contrib-hls.js:2056)
    at videojs-contrib-hls.js:2325
    at Array.forEach (<anonymous>)
    at setupMediaGroups (videojs-contrib-hls.js:2324)
    at PlaylistLoader.<anonymous> (videojs-contrib-hls.js:706)
    at PlaylistLoader.data.dispatcher (video.js:18045)
    at Object.trigger (video.js:18149)
    at PlaylistLoader.EventTarget.trigger (video.js:7729)
    at videojs-contrib-hls.js:3901
    at videojs-contrib-hls.js:8399
#### videojs
what version of videojs does this occur with?
5.

### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-contrib-hls

**Comment by gkatsev** [comment]
This is a mismatch of Video.js and contrib-hls versions. If you update to the latest 5.x of Video.js (or to 6.x) it should work fine. Here's an updated jsbin: http://output.jsbin.com/vehevanafu

Hope that helps.
