### ISSUE TITLE
Demo not playing in Microsoft Edge 40

### ISSUE THREAD

**Issue by dhanishapa** [videojs/video.js#4870]
Video not seems to be loading  in Edge version 40.
The demo page itself seems not loading. I could see an error throwing up 

![image](https://user-images.githubusercontent.com/4947459/34782561-176884c2-f64f-11e7-9f39-a099f482fdac.png)
 Any thoughts on this?

**Comment by mister-ben** [comment]
That's a very old version of Video.js that probably predates Edge, with an old verison of a complex plugin.

There's an [up-to-date fork of videojs-vr that is maintained by the Video.js team](https://github.com/videojs/videojs-vr). Please try using that instead. You'll probably find you don't have issues with that, but if so please log against that repo.
