### ISSUE TITLE
videojs-contrib-hls.js Uncaught RangeError

### ISSUE THREAD

**Issue by kobe0116** [videojs/video.js#4871]
## Description
Briefly describe the issue.
An exception was found when using videojs-contrib-hls.js 
Uncaught RangeError: Offset is outside the bounds of the DataView at DataView.getUint32

browsers : Chrome, Firefox

OSes: windows 10

plugins: video.js videojs-contrib-hls.js jquery.js

**Comment by gkatsev** [comment]
Unfortunately, this doesn't include enough information for us to help you. Can you please re-open this issue against [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls/issues/new)? Please fill out the issue template as thoroughly as possible, even better if you can provide the manifest you're using. Also, include versions of Video.js and videojs-contrib-hls used.
