### ISSUE TITLE
How to set fullscreen mode on Android devices right after clicking the play button?

### ISSUE THREAD

**Issue by maketroli** [videojs/video.js#4872]
I need to know how to go into fullscreen mode right after clicking the play button of the video (On Android only).

I've tried something like this:

```javascript
    var videoPlayer = document.getElementById('myPlayer');
    var user_agent = navigator.userAgent.toLowerCase();
    if(user_agent.indexOf('android') > -1) { // Check for Android.
       videoPlayer.requestFullscreen();
    }
```

But I am getting this error:

>TypeError: videoPlayer.requestFullscreen is not a function. (In 'videoPlayer.requestFullscreen()', 'videoPlayer.requestFullscreen' is undefined)

Any suggestions?

**Comment by mister-ben** [comment]
With `document.getElementById('myPlayer')` you're getting the player element rather than the player. That el may or may have a vendor prefixed `webkit`/`mozFullscreen()`. Use the Video.js API's `requestFullscreen()` in response to a user interaction event. 

```js
var player = videojs('myPlayer');
player.bigPlayButton.one('tap', function() {
  if (videojs.browser.IS_ANDROID) {
    player.requestFullscreen();
  }
});
```
