### ISSUE TITLE
timeupdated event always tracking as manuallyUpdated

### ISSUE THREAD

**Issue by arski** [videojs/video.js#4873]
Hi there, is there a reason why the "timeupdated" event is triggered with "manuallyUpdated: true" during the 250ms time tracking while the video is playing in https://github.com/videojs/video.js/blob/82c8b805488a520f26447917da736e069181727a/src/js/tech/tech.js#L310 ?

I understand it in the seek-bar, where it is indeed manually updated https://github.com/videojs/video.js/blob/baf0982515013f80f3de61b777a9781ee70d9982/src/js/control-bar/progress-control/seek-bar.js#L256

If you agree this is an oversight, I'm happy to raise a PR. Thanks!

**Comment by gkatsev** [comment]
Those `timeupdate` events are indeed manually triggered. The ones in `tech.js` are only triggered when something like the flash tech is used which doesn't have its own `timeupdate` mechanism like the video element. The `timeupdate` is the seek-bar is related where we want to let everything know that a seek has happened as early as possible.

Thanks for asking!

**Comment by arski** [comment]
thanks, I found the seeked event which is what I needed. Sorry for the disturbance! :)
