### ISSUE TITLE
New event on failed track loading?

### ISSUE THREAD

**Issue by arski** [videojs/video.js#4876]
Hi again, I'm wondering if I'm missing an event being triggered when e.g. TextTrack loading/parsing is failing. I'm aware of loadeddata - but obviously that only fires on successful load.. is there anything for when the URL fetching fails, or when parsing fails? If not, would you be open to adding a new triggered event for this?

**Comment by gkatsev** [comment]
We do have a `load` even on the HTMLTrackElement (both native and [our emulated one](https://github.com/videojs/video.js/blob/f22cb50574e0c68e93cbc9e09b046479348799f8/src/js/tracks/html-track-element.js#L121)). We probably should do a similar thing for errors with an `error` event.
Note: while `loadeddata` is available, it isn't documented and only used internally, I would urge you to listen to the `load` event like at the end of [`addRemoteTextTrack` section](https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#remote-text-tracks).

**Comment by gkatsev** [comment]
Also, if you're interested in making a PR for this, that would be great!

**Comment by arski** [comment]
aaactually I'm realizing that I don't need this as loadeddata/load is called on parser.flush() even if there were errors, so I can pretty easily infer things from there. Thanks! I'm personally happy to close this.
