### ISSUE TITLE
Class name for caption-settings font component incorrectly set 

### ISSUE THREAD

**Issue by RonakSumbaly** [videojs/video.js#4879]
## Description
The class name is being incorrectly set to `vjs-track-settings-font">` for the font component within caption-settings.

## Code Reference
https://github.com/videojs/video.js/blob/f22cb50574e0c68e93cbc9e09b046479348799f8/src/js/tracks/text-track-settings.js#L437

### Expected
Excepted class name `vjs-track-settings-font`

**Comment by OwenEdwards** [comment]
This is fixed in #4835; that PR hasn't landed yet, but if/when it does, it will fix this issue.
