### ISSUE TITLE
Video is playing abit fast not syncing exactly with controlbar currentTime.

### ISSUE THREAD

**Issue by BijayRai** [videojs/video.js#4887]
My issue is There is many video i have in which there is something like this.

let say in 3.45 sec one screen change is shown in video. 
So, when i play this video in quickRealTime Player on mac. That screen change is appearing on same  exact 3.45 sec of that player currentTime . 

But in video js player,That screen change is happening abit before 3.45 sec. it showing like its appearing on 32.some seconds. 
So, what's the issue on video js player and how we can solve this?

**Comment by gkatsev** [comment]
Unfortunately, I think this is just how it is with browsers. If you try several different browsers or try playing back the video multiple times you'll end up having that frame show up at a slightly different time. We've spent some time looking into frame accurate seeking (this relates to it) and basically browsers don't do it very well.
Unfortunately, there isn't really anything you can do, though, the video should still end up playing back correctly, even if the frame and currentTime don't quite match up.

Are you doing anything specific where you need the frame to be accurate or just something you noticed during playback?

**Comment by BijayRai** [comment]
@gkatsev  Yes i am using maker and overlay plugins too in my video and since Time is slightly different on video, Markers and overlays are plotted on exact given time but since screen is changed abit before then given time it looks abit messed up.

**Comment by gkatsev** [comment]
Spoke with @mjneil who has looked into this a bit and unfortunately, there isn't really much we can do. The browsers are just not frame accurate and this means that if you need exact timing for things like scene transition it will be obvious that it's a bit off.
Marking this a browser bug (more like a browser limitation). Sorry I don't have a better answer.

**Comment by FutureKen** [comment]
@BijayRai If you need to do something while the video is paused, you could add **this.currentTime(this.currentTime());** on video 'pause', it asks video player to seek current time. I have this issue in Chrome too, but after adding this, it seems the issue has gone now.
