### ISSUE TITLE
How to add a event to be called on a specific time

### ISSUE THREAD

**Issue by jvitoroc** [videojs/video.js#4897]
Something like
this.on(60000, function() {
    videojs.log('1 minute');
  });

**Comment by gkatsev** [comment]
There are two main ways for you to do this, listen to `timeupdate` events and then wait till `currentTime` is set to 1 minute or on something like that `playing` event, set your own timeout for 1 minute.
For example:
```js
player.on('timeupdate', function() {
  var ct = player.currentTime();
  if (ct === 60) {
    doSomething();
  }
});
```
or
```js
player.on('playing', function() {
  // it's possible this is just what you care about too
  player.setTimeout(function() {
    doSomething()
  }, 60000);
```

Hope that helps.
