### ISSUE TITLE
Update Netflix skin for 6.x.x?

### ISSUE THREAD

**Issue by Jad3z** [videojs/video.js#4901]
Could we update the netflix skin for v6.x.x ?

[https://codepen.io/benjipott/pen/JELELN](https://codepen.io/benjipott/pen/JELELN)

**Comment by payflix** [comment]
@Jad3z Something like this?
![https://i.imgur.com/CWZOt3D.png](https://i.imgur.com/CWZOt3D.png)
Tested on v6.x.x

**Comment by gkatsev** [comment]
Unfortunately, we don't maintain that page. I would suggest notifying the creator of that skin. Or update it yourself or with the help of @payflix.
It looks like there are fewer issues than I expected. There's some information on our [upgrade guide](https://github.com/videojs/video.js/wiki/Video.js-6-Migration-Guide#ui-and-accessibility-changes).
We'd be happy to help with specific questions on our [slack](http://slack.videojs.com).
