### ISSUE TITLE
Fullscreen issue on IE11

### ISSUE THREAD

**Issue by l0v3w4v3** [videojs/video.js#4905]
Hi, I am using videojs 6 on my web app project. But I got a problem with Fullscreen API on IE11 when video is in 2 iframes. No problem if video is in 1 iframe, all other browsers are working perfectly.
![ie11 issue](https://user-images.githubusercontent.com/6983104/35434009-2021fb78-02b8-11e8-87da-823861ff3ea8.png)

My code:
```
  var videoContainer = $( '#videoContainer' );
    videoContainer.addClass( 'video-js vjs-default-skin vjs-big-play-centered vjs-show-big-play-button-on-pause' );
    videoContainer.css( {
        'position': 'absolute',
        'top': 0, 'left': 0,
        'right': 0, 'bottom': 0,
        'margin': 'auto',
        'width': width + "px",
        'height': height + "px",
        'z-index': 1555
    } );
    var videoElement = $( '<video id ="videoId"></video>' );
    videoElement.attr( 'controls', '' );
    videoElement.attr( 'data-setup', '{"asdf": true}' );
    videoElement.css( {
        'border': '1px',
        'margin': '0px 0px 10px 0px',
        'margin-left': 'auto',
        'margin-right': 'auto'
    } );
    var sourceElement = $( '<source>' );
    sourceElement.attr( 'src', videoUrl );
    if ( extension === 'mp4' ) {
        sourceElement.attr( 'type', 'video/mp4' );
    }
    videoElement.append( sourceElement );
    videoContainer.append( videoElement );
    $( document ).ready( function() {
        // allow full screen mode on  Firefox
        window.parent.$( '#parentIframeId' ).attr( 'allowfullscreen', '' );
    } );
```
Anyone help?

**Comment by gkatsev** [comment]
What do you mean by "2 iframes"? Do you have an iframe inside of an iframe? If so, you need to make sure that each iframe, in turn, has the correct `allowfullscreen` attribute on it (since it's IE, `msallowfullscreen`).
How are you entering fullscreen? Also, if you have a reduced test case, that would be great as well.

**Comment by l0v3w4v3** [comment]
@gkatsev I tried and it didn't work. I am entering fullscreen by just click on the fullscreen button at the bottom left of the player
![untitled](https://user-images.githubusercontent.com/6983104/35493355-175d8528-04e5-11e8-95b9-4778c7b2ce6e.png)

**Comment by l0v3w4v3** [comment]
@gkatsev what should I do?

**Comment by gkatsev** [comment]
Hm... I just tried a thing locally and it seems to be working for me. One thing I noticed is that you're setting a specific height and width on the video container and that could potentially cause issues.

**Comment by l0v3w4v3** [comment]
@gkatsev I tried to remove that width and height setting on the 'fullscreenchange' event but it still didn't work. Sad react only.

**Comment by gkatsev** [comment]
Unfortunately, I'm out of ideas and can't really help more without a reduced test case showcasing the problem.
