### ISSUE TITLE
Problem of loading of library in header or on specific page.

### ISSUE THREAD

**Issue by Syedwaheed** [videojs/video.js#4906]
I have problem of loading the library for my application. i have seen most of the time the following screens:
![cap1](https://user-images.githubusercontent.com/14071753/35436430-3eae20ce-02b0-11e8-82df-a33a1fa2bad3.jpg)
![cap11](https://user-images.githubusercontent.com/14071753/35436431-3ee53820-02b0-11e8-87ec-06256ea7915e.jpg)
I m using the video type playlist.m3u8 and video.js version 5.19.2. 
Everything is working fine sometime when i load the page these errors comes up and i will reload page and everything is fine like following:
![capture1](https://user-images.githubusercontent.com/14071753/35436612-e6f0c854-02b0-11e8-8aa0-70b1a2779943.JPG)
Any help to avoid such problems. Thanks.

**Comment by ldayananda** [comment]
@Syedwaheed Any chance you can provide a reduced test case for this issue? If not, can you explain how you are trying to load the library? How are you creating a player?

**Comment by Syedwaheed** [comment]
Thanks for your prompt reply @ldayananda. Here is the file how m i loading the video.js library in my application. I have gotten this error so frequently on live webserver. When i refresh the page everything works fine. This isn't put a good impression. Your help is greatly appreciated. Thanks
[https://gist.github.com/Syedwaheed/9879ad9473184f3feddc5dfab116768d]

**Comment by gkatsev** [comment]
One thing I noticed is that you have two video.js references in the player. Both `video.js` and `video.min.js`. Then you're also trying to get the player initialized via its automatic setup `data-setup` functionality but also try to reference it via `videojs('my-player1')`. There's probably a timing issue where one version of Video.js ends up initializing the player but then the second Video.js loads and then your code tries to use that one. Also, I think the hls plugin is being loaded twice as well `hls.min.js` and `vjs-hls.min.js`.
I think making sure that video.js and plugins only get loaded once and you should consider not using data-setup but only initializing via `videojs('my-player1', {...})`

**Comment by Syedwaheed** [comment]
Thanks for your prompt reply @gkatsev. I have done the changes and the reduced test file link is below.
https://gist.github.com/Syedwaheed/7719384b8598a989a323be958990bfcd
I m now facing two problem when removing the data-setup from the file. Following is the first screen.
![cap1](https://user-images.githubusercontent.com/14071753/35562938-def643bc-05d6-11e8-93f5-e45817c07bec.jpg)
As there is playing button as library is not loaded.
I m getting the following error on console.
![capture-](https://user-images.githubusercontent.com/14071753/35562985-0ac7397e-05d7-11e8-8c01-776dca282239.JPG)
And above Black model with no compatible pop-up. 
Please suggests me changes in my gist or either modifies it would be great for me. Thanks for your help in advance.

**Comment by gkatsev** [comment]
Looks like you're also trying to have the player in a modal? If so, I would suggest to initialize and dispose the player whenever the modal opens and closes.
I would also try to get the player working outside of the modal first and then work on getting it working in the modal. I can't really find any issues with the modal. Would you be able to make a live example of this somewhere like jsbin?

**Comment by Syedwaheed** [comment]
Yes i m using the player outside on the page and also use it in the modal.
I will make one live example and will share a link with you.. Thanks you.

**Comment by Syedwaheed** [comment]
Hi @gkatsev . I m unable to make a live example on JS bin because it requires pro account for things to upload.But i have changed the some of the code and video is working fine now. I think now i m not going to have such issue again. Please have a look at below file and suggest changes.
https://gist.github.com/Syedwaheed/7719384b8598a989a323be958990bfcd
I have added data-setup on the page where i want the play button for user. Below is the image.
![cap1](https://user-images.githubusercontent.com/14071753/35626406-761892e6-06b7-11e8-8d88-b2996000c187.jpg)
And using javascript for the modal and its working fine for me uptill now. Below is the image:
![cap11](https://user-images.githubusercontent.com/14071753/35626493-af814640-06b7-11e8-88bf-3b3a4948ba99.jpg)
Please look at the file and suggest me changes if it requires. I think its working fine now. Thanks for your time and great work.

**Comment by gkatsev** [comment]
Cool, glad you got it figured out. I don't really have anything to add to your latest gist.

**Comment by Syedwaheed** [comment]
Thank you :) for your responses 🖒

**Comment by gkatsev** [comment]
You're welcome.
