### ISSUE TITLE
how make Video.js Player to luck like openload player?

### ISSUE THREAD

**Issue by Leo01985** [videojs/video.js#4909]
i try to copy the css code from openload but i don't find it!

**Comment by gkatsev** [comment]
Hi,

Unfortunately, I'm not sure what the problem you're having is. Would you be able to elaborate? What is openload? Best if you can have a live reduced test case.

**Comment by campones** [comment]
openload.co  :)

**Comment by gkatsev** [comment]
OK, wasn't sure which openload. Yeah, you could try using their CSS or basically just use their player as inspiration as you style your own player manually.
We can assist with specific CSS-related questions in our [slack](http://slack.videojs.com).
