### ISSUE TITLE
Videojs autoplay not working on android chrome

### ISSUE THREAD

**Issue by ngoyal16** [videojs/video.js#4927]
We added videojs as a media player with ima ad manager. the autoplay function is working with all other browser but not with android chrome.

### Error output
DOMException: play() can only be initiated by a user gesture.

**Comment by gkatsev** [comment]
This is a browser limitation. Mobile browsers (and soon some desktop browsers as well, Safari already and desktop Chrome with version 66) disallow playing back video with audible audio. If you mute the video, you should be able to autoplay, otherwise, you cannot autoplay on mobile devices.

**Comment by dandelionred** [comment]
Check this out https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by ngoyal16** [comment]
@gkatsev the video is in the mute mode but still it is not working with the mobile browser

**Comment by dandelionred** [comment]
Is it an android phone? I guess autoplay is even more restricted on phones up to no autoplay at all. Tablets are less restricted.

**Comment by horcrux2301** [comment]
@ngoyal16 Found any solutions?

**Comment by mohit546** [comment]
@ngoyal16 i am facing the same problem
tested on latest mobile browsers UC, Mozila, Opera but only on chrome autoplay is not working
if you found something please let me know, thanks

**Comment by ngoyal16** [comment]
for me the problem was that if a person limited access to their internet data "data saver mode" then it not allow to play any video by autoplay.

**Comment by sudhakarsukumar** [comment]
For me autoplay is working on scroll but, while clicking on the ads the player stops and ads gets resumed and paused also when we click on mute and unmute the issue occurs
