### ISSUE TITLE
[WARNING] Demo don't working- Videojs CDN is blocked:mixed-content

### ISSUE THREAD

**Issue by RayNEXT** [videojs/video.js#4928]
Hello. You can see [Picture](https://imgur.com/a/WpcuF)
Thank you

**Comment by gkatsev** [comment]
The video.js CDN is available via both [http ](http://vjs.zencdn.net/6.6.3/video.js)and [https](https://vjs.zencdn.net/6.6.3/video.js). Hope that helps.
