### ISSUE TITLE
videojs v6.x global setup

### ISSUE THREAD

**Issue by mysuf** [videojs/video.js#4932]
Hi guys, I did not find any clue how to set plugin/component with options globally. I have multiple videos on page. Example cases:

1. I would like to add component to given controlBar's index globally
Now I do `player.addChild('customComponent', options, index);` 
2. I would like to set vertical volumeBar globally (my findings leaded me to threads with obsolete volumeMenuButton) I tried many forms of:
```
videojs.options.controlBar = {
  volumeControl: {
    volumeBar: {vertical: true}
  }
}
```
Also trying to set VolumeControl's protype.options_, but without success

Could you provide correct steps for v6.x to achieve it? Thanks

**Comment by gkatsev** [comment]
You want to to set `volumePanel: {inline: false}` for Video.js 6.
Here's an example of setting it globally: https://jsbin.com/haqifof/edit?html,js,output
Hope that helps.
