### ISSUE TITLE
Standard h264 with aac audio not playing in Safari iOS with files hosted on dropbox

### ISSUE THREAD

**Issue by seabasss** [videojs/video.js#4941]
I've seen a copule of threads about this but I haven't found a solution. I'm loading movie files into a videojs player and sometimes I just get a big X and an error message in desktop versions of Safari/Chrome/Firefox and far more often on iOS safari. I assume it's related to files being hosted on dropbox, but I'm not sure. Since it's working sometimes and for some users it gets tricky to debug.

The desktop version works pretty well so the iOS situation is a bit more crucial since it happens extremely often. I get this message 

> "The media could not be loaded, either because the server or network failed or because the format is not supported."

If I save the website to the home screen and access the site from there the error message shows up 100% of the time for files hosted on dropbox. If that's a security thing in the homescreen version it's not ideal, but I can live with it, but it would be great to be able to play non-locally stored videos in the normal Safari browser in iOS.

**Comment by gkatsev** [comment]
I think this is because Safari uses byte-range requests to playback. I think that dropbox doesn't support byterange requests for video files and thus videos fail to play.

**Comment by seabasss** [comment]
Running this little guy on the Dropbox links seem to fix it! :D 

`str_replace('www.dropbox.com/s/', 'dl.dropboxusercontent.com/s/', $url);`
