### ISSUE TITLE
Is there any way to use Videojs Plugins in Angular 4 ? 

### ISSUE THREAD

**Issue by Hashmi0** [videojs/video.js#4942]
## Description
Hello there !
i am unable to use <a href="https://www.npmjs.com/package/videojs-watermark">videojs-watermark plugin</a> in my angular 4 project.
Is there any way to use any videojs plugin in angular 4 ?

Code
![capture](https://user-images.githubusercontent.com/13191665/35971168-d4f22c68-0cee-11e8-82dc-67924afee19a.PNG)

### Error output
![1](https://user-images.githubusercontent.com/13191665/35971189-e3909606-0cee-11e8-9c13-bf9e24c3cc00.PNG)

#### videojs
 "^6.6.3"
#### videojs-watermark
 "^2.0.0"

**Comment by gkatsev** [comment]
Can you elaborate on your build setup? Webpack, npm, node versions? Sometimes what happens is that Video.js ends up getting included twice, once for the plugin and once for the application.

**Comment by cshah123** [comment]
+1

**Comment by gkatsev** [comment]
[Someone in slack](https://videojs.slack.com/archives/C43LGP955/p1518687857000339) has solved a potentially related issue by doing the following:
```
For me the solution was just to add the js files of both video.js and my plugin to the angular-cli.json scripts
and then
```declare const videojs: any;```
to the typings.d.ts files (edited)
```

hope it helps.

**Comment by Hashmi0** [comment]
Thanks It works (Y)

**Comment by gkatsev** [comment]
Closing as answered.

**Comment by madox35** [comment]
Hey there,

I've got same issue here. But I'm running with : 
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

I've already include in my angular.json differents scripts i need and it works for video.js. But my plugin videojs is still not recognized. I can't find any typings.d.ts and I'm new with this kind of things..
Have you got any tips for me ?

PS: I tried to import one of my own plugin generate with "yo doctor" so I think that there is no mistake inside the plugin to import.

Thanks in advance for your help

**Comment by acharyaks90** [comment]
Now its working 

# Video.js and Angular integration

Here's a basic Angular player implementation.

It just instantiates the Video.js player on `OnInit` and destroys it on `OnDestroy`.

```ts
// vjs-player.component.ts
import { Component, ElementRef, Input, OnDestroy, OnInit, ViewChild, ViewEncapsulation } from '@angular/core';
import videojs from 'video.js';
@Component({
  selector: 'app-vjs-player',
  template: `
    <video #target class="video-js" controls muted playsinline preload="none"></video>
  `,
  styleUrls: [
    './vjs-player.component.css'
  ],
  encapsulation: ViewEncapsulation.None,
})
export class VjsPlayerComponent implements OnInit, OnDestroy {
  @ViewChild('target') target: ElementRef;
  // see options: https://github.com/videojs/video.js/blob/master/docs/guides/options.md
  @Input() options: {
      fluid: boolean,
      aspectRatio: string,
      autoplay: boolean,
      sources: {
          src: string,
          type: string,
      }[],
  };
  player: videojs.Player;
  constructor(
    private elementRef: ElementRef,
  ) { }
  ngOnInit() {
    // instantiate Video.js
    this.player = videojs(this.target.nativeElement, this.options, function onPlayerReady() {
      console.log('onPlayerReady', this);
    });
  }
  ngOnDestroy() {
    // destroy player
    if (this.player) {
      this.player.dispose();
    }
  }
}
```
Don't forget to include the Video.js CSS, located at `video.js/dist/video-js.css`.
```css
/* vjs-player.component.css */
@import '~video.js/dist/video-js.css';
```

You can then use it like this.

```html
<app-hls-player [options]="{ autoplay: true, controls: true, sources: [{ src: '/path/to/video.mp4', type: 'video/mp4' }]}"></app-hls-player>

**Comment by thijstriemstra** [comment]
@acharyaks90 any idea how to properly include video.js plugins in angular?

**Comment by acharyaks90** [comment]
@thijstriemstra 

yes I have made an plugin you can check  it from here also check how to include in angular 
https://www.npmjs.com/package//ng-tactful-lib#uses--example-of-videojs-marking

**Comment by acharyaks90** [comment]
Also can find git code 
https://github.com/acharyaks90/ng-tactful-library/tree/master/projects/ng-tactful-lib/src/lib/ng-tactful-video-tag
