### ISSUE TITLE
How to select a part of the video in Angular 2 by using Video JS and download that clipped part?

### ISSUE THREAD

**Issue by mujtabaejaz** [videojs/video.js#4943]
## Description
I'm working on a simple Angular 2 project. Where I've to select a specific part of the video and then download that clipped part in different video formats. Any help in this regards are highly appreciable. Thanks.
![videoclipping-angular2-videojs](https://user-images.githubusercontent.com/22595265/35972532-1309a544-0cf4-11e8-8eec-d5d93e5a5150.png)

### Expected Result
To being able to download the clipped part of the video.

### Actual
I'm getting the values of selected part but not able to download it.

### versions
6.6.3
#### videojs
are any videojs plugins being used on the page? If so, please list them below.
- Range Slider

**Comment by gkatsev** [comment]
Hi,

Video.js specializes in playing in playing back video in the browser. For clipping, you'd need to send the start and end times to your backend and then use something like ffmpeg to cut the clip the video based on the times provided. I am not aware of any way to do this clipping in the browser itself.
Unfortunately, browsers aren't frame accurate, so, it's possible that if you're trying to during a scene transition you'll end up cutting slightly before or after.

Hope that points you in the right direction.

**Comment by Furholeder** [comment]
i also need complete clip a segment  video, but at the moment i do not know how to achieve the style and the function in your player caption picture, can you tell me how i can do to complete  your same style and the function of your video player.  or can you suggest me any useful plugins to achieve the select a segment of video
