### ISSUE TITLE
UC browser default player

### ISSUE THREAD

**Issue by krisnamargono** [videojs/video.js#4945]
Sorry if this is a newbie question, but it seems like UC browser is overriding video js player and all my custom element attached to video js player is being overlap by the UC browser player.

```
videoType = 'application/x-mpegURL';

player.ready(function () {
   this.src([{
        type: videoType,
        src: source
    }]);

    this.play();
})
```
The 'source' is m3u8 type.

Is there any way to disable the UC browser default video player?

videojs version 6.2.4
occur in UC Browser version 12.0.0.1088
device Motorola Nexus 6

And I added these two as well
```
<script src="assets/videojs.hls.min.js"></script>
<script src="assets/videojs-flash.min.js"></script>
```

Thank you

**Comment by mister-ben** [comment]
This would seem to be a limitation of that browser. Like Opera mini it pre-compiles pages in a proxy, and it apparently plays back media in a native player layered over the rendered html.

**Comment by krisnamargono** [comment]
Okay thank you for the answer @mister-ben

**Comment by rahulsingh-kits** [comment]
How to disable download button on uc browser player as i m not able to debug uc browser playre.
Any help?

**Comment by pintocarlos** [comment]
@mister-ben Would you be able to point to the source where you found that the UC browser plays back media in a native player above rendered html? I am also running into this issue and it does seem to be the [top unanswered question](https://stackoverflow.com/questions/tagged/uc-browser?sort=votes&pageSize=50) related to UC browser on Stackoverflow as well. Knowing the source of the problem would help a ton. Thanks!

**Comment by mister-ben** [comment]
That was a while ago that I looked but my findings were based mainly on observation. There's no good documentation for that browser that I know of.

**Comment by gkatsev** [comment]
This is what we found as well when we looked at UC Browser.

**Comment by pintocarlos** [comment]
We noticed the same but unable to find it documented anywhere on UC Browser. My assumption is that the UC Browser team sees this as a feature given that their video player displays additional controls and features.

**Comment by gkatsev** [comment]
You're probably right. But because their usage of the video element is non standard, it ends up causing us issues :(
