### ISSUE TITLE
Broken page in API docs

### ISSUE THREAD

**Issue by Scopestyle** [videojs/video.js#4946]
http://docs.videojs.com/docs/api/index.html 

The item _PlayProgressBar_ is listed twice, and the first item points to a broken page.

This is all.

Carry on.

**Comment by gkatsev** [comment]
Thanks for bringing this up. Unfortunately, these are our legacy documentation and we're unlikely to update them (beyond adding a banner that says they're legacy docs).
Check out the new docs here: http://docs.videojs.com/playprogressbar
