### ISSUE TITLE
Slider bar goes out of the player

### ISSUE THREAD

**Issue by kshitij0392** [videojs/video.js#4949]
## Description

Every time I use the Offset plugin, my Seek slider goes out of the player. It works normal when I play it without the offset.

What could be the cause to this ?

### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs offset

![videojs issue](https://user-images.githubusercontent.com/21281356/36119982-afa7f176-100f-11e8-8fd1-c05a87a6a356.png)

**Comment by gkatsev** [comment]
Can you elaborate on what version of Video.js you're using also which videojs-offset plugin are you using? A reduced test case would be great, too.
Though, based on the description, it sounds like what the offset plugin does is interacting badly with the player causing the seekbar to grow too much.

**Comment by gkatsev** [comment]
Is it https://github.com/cladera/videojs-offset?
Does it work with 5.20.4? Does it work with a newer version of 6.x? Like 6.7.1? There's been a lot of bug fixes in 6.x.

**Comment by kshitij0392** [comment]
Yes that's the one!! 

We recently updated Videojs to 6.0.2 and this is the first time we are trying to use offset

**Comment by kshitij0392** [comment]
Any way I could tackle this ? @gkatsev 
I tried updating the player, but to no good.

**Comment by gkatsev** [comment]
Yeah, it's a plugin issue. There's even a PR to look into fixing it: https://github.com/cladera/videojs-offset/pull/28
With Video.js 6, one can use middleware and not have to do unsupported things like overriding video.js methods like videojs-offset does. If you'd be interested in creating such a plugin, we can offer help in [our slack](http://slack.videojs.com).
