### ISSUE TITLE
How to set TextTrack kind with playlist?

### ISSUE THREAD

**Issue by alexchern** [videojs/video.js#4963]
Hi all,

I'm trying to use a WebVtt subtitles (as metadata) for live HLS stream. I can't add a track programmatically as it is done via master playlist (and the vtt files are created on the fly). It works Ok for text, but I need it as "metadata kind", so it would not be shown on the screen. If I set the mode to "hidden" I'm not getting the cue events until I select the track explicitly using GUI.  
The only workaround I found is to set the mode to "showing" and (after delay)  back to "hidden" (this works for some time, but I eventually stop getting the events...).

How can I do it in a correct way? 

Thanks,

Alex

**Comment by gkatsev** [comment]
Is this on iOS or Safari? We've noticed that unless you add a captions track to the player, hidden tracks will not trigger events.

**Comment by alexchern** [comment]
Hi Gary,
I'm using Windows + Chrome. So far I could not find any reliable way to get 'metadata kind' WebVtt with master playlist... So, I'm polling the server instead (and I really don't like it :-( 

Thanks,
Alex

**Comment by gkatsev** [comment]
Yeah, I don't think that HLS has a way to specify metadata tracks only subtitles and captions. Generally, people use ID3 cuepoints in the media which gets exposed as metadata tracks.

**Comment by alexchern** [comment]
That would require remultiplexing the stream. Metadata tracks are "out of band"...
Is there any way to suppress presentation of the subtitles? Make them fully transparent, font size 0 or something like that. Not nice, but it would work...

**Comment by gkatsev** [comment]
Why not just load the metadata track outside of the HLS manifest in the player directly?

You could potentially set the text track display area to have opacity 0 or something, but I would try the above first.
```css
.vjs-text-track-display {
  opacity: 0;
}
```
Also, this wouldn't work on iOS/Safari, but for those you could potentially use the ::cue pseudo selector:
```css
::cue {
  opacity: 0;
}
```

**Comment by alexchern** [comment]
**Thanks for that!**
As for _loading the metadata track outside of the HLS manifest in the player directly_... 
I create the metadata right after the ts segment is created (live stream) and update the manifest, so I wanted to leave this job to the player... Once recording is complete, I finalize the manifest, making it VOD.  Now, the player should do all the job of bringing the correct metadata segments (on random access as well).  So, this should work for both, Live and VOD. Though it is probably possible to figure out what track to add and what track to delete, the player should do this automatically - it is already in the manifest.

**Comment by gkatsev** [comment]
I think this has been answered. Closing. If there's more to discuss, we can continue in this issue, even if it's closed.
