### ISSUE TITLE
Captions not working in FF

### ISSUE THREAD

**Issue by TheSunrise** [videojs/video.js#4966]
## Description
We have a video which we start via a JS call. Everything good but in FF the captions won't show up. We included the captions like in the jsbin example but on load, video.js removes the track in FF.

http://jsbin.com/vufupugito/edit?html,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Start FF
2. Go to URL
3. No captions shown

### Expected
Showing captions in every browser. 

### Actual
Video captions not shown in FF

### Error output
There is no error output but the expected captions won't be shown

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
video.js version 4.12.15
#### browsers
Firefox 58.0.1 (64-Bit)
#### OSes
Linux, Windows
### plugins
None

**Comment by gkatsev** [comment]
Video.js 4.12.15 is a very old and unsupported version. Upgrading to Video.js 6.7 does not seem to have an issue with playing back the captions: http://jsbin.com/xibuxeduno/edit?html,output
Hope that helps. Let us know if you need help upgrading to Video.js 6.
