### ISSUE TITLE
How can I add an explicit content cover?

### ISSUE THREAD

**Issue by mawenmaywin** [videojs/video.js#4981]
## Description
I need a way to add a cover to a video (preferably blurred) that covers the entire video until someone clicks on the uncover content button similar to Facebook and other social media sites.

**Comment by gkatsev** [comment]
Thanks for asking. I can point you in the right direction but generally generic questions like these are better served by asking or searching on a forum like StackOverflow. Unfortunately, we just can't really answer questions like these on a regular basis.
But basically, you can add a css filter in a mask element over the player and then in a click handler, remove the filter or the mask. See this SO answer for a starting point https://stackoverflow.com/a/27592975, example from there: http://jsfiddle.net/u2y2091z/623/

Hope that helps and points you in the right direction.
