### ISSUE TITLE
How to use it in react

### ISSUE THREAD

**Issue by BigEagleWY** [videojs/video.js#4987]
Now , more and more front end project using npm , but the example in your readme.md still imports it by script tag . Can you give us a example that how to use it in react

**Comment by gkatsev** [comment]
Hi,
Our read me could use some sprucing up but you can definitely import video.js using your favorite bundle. We also have a guide specifically for react you can take a look at: http://docs.videojs.com/tutorial-react.html

**Comment by BigEagleWY** [comment]
Thank you very much.  In the video.js website index, we can see that if the browser not support html5 , video.js will auto change it to flash. I want to make sure that I do not need any extra code to solve this problem and just follow your document.

**Comment by gkatsev** [comment]
We have split off the flash support into a separate project if you're using Video.js 6: https://github.com/videojs/videojs-flash/

**Comment by daizch** [comment]
@gkatsev Hi, Doest video.js support to use in web component? Because I use it in web component, it can't work well 😭

**Comment by walkinMrwang** [comment]
So good!

**Comment by gkatsev** [comment]
I think the original question has been answered, so, I'm going to close this.

If there are problem with Video.js and webcomponents, please open a new issue. Best if you can provide a reduced test case as well.
