### ISSUE TITLE
SCRIPT438: 对象不支持“isArray”属性或方法 (ie8)

### ISSUE THREAD

**Issue by lengjiaxin** [videojs/video.js#4994]
/**
 * @license
 * Video.js 5.0.2 <http://videojs.com/>
 * Copyright Brightcove, Inc. <https://www.brightcove.com/>
 * Available under Apache License Version 2.0
 * <https://github.com/videojs/video.js/blob/master/LICENSE>
 *
 * Includes vtt.js <https://github.com/mozilla/vtt.js>
 * Available under Apache License Version 2.0
 * <https://github.com/mozilla/vtt.js/blob/master/LICENSE>
 */

**Comment by gkatsev** [comment]
Assuming google translate isn't lying to me, this question is about isArray not being available in IE8?
Video.js 5.x does support IE8 but it still requires an ES5 environment. We have files you can include in our [IE8 repo](https://github.com/videojs/ie8) you can also just include it from the CDN before including Video.js: http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js

Hope that helps. (Also, I would recommend updating to a later version of 5.x. There have been so many new features and fixes!)

**Comment by lengjiaxin** [comment]
Thank you
