### ISSUE TITLE
subtitles cannot remove/disable by javascript on iOS Fullscreen until fullscreen exit

### ISSUE THREAD

**Issue by Pong420** [videojs/video.js#5003]
## Description
subtitles cannot remove/hidden by javascript on iOS Fullscreen until fullscreen exit
( iOS10.3.3 works fine but iOS11.0.1 not work   )

## Steps to reproduce
1. enter fullscreen
2. pause video with subtitles overlay
3. using javascript to disable text track 
```js
 var tracks = player.textTracks().tracks_ || [];

 tracks.forEach(function (track) {
     if (track.mode === "showing") {
         track.mode = "disabled"
     }
 })
```
### Expected
subtitles removed/hidden

### Actual
subtitles overlay on screen until fullscreen exit, 

#### videojs
6.7.3
#### browsers
safari
#### OS
iOS 11.0.1
### plugins
videojs-contrib-hls
videojs-contrib-ads
videojs-ima

**Comment by gkatsev** [comment]
You shouldn't use the private `tracks_` property but instead, you can delegate to the array-like object returned by `player.textTracks()`. While it is available publically, the general convention is that properties prefixed or suffixed with an underscore are private and shouldn't be used outside of the package.

I can reproduce this behavior but I do not need to exit fullscreen for the subtitles to hide. If I continue playing the subtitles don't continue showing. This must be a change in iOS that keeps the currently visible cue on screen until something else happens with the video like fullscreenchange or playback continuing.

**Comment by Pong420** [comment]
it works after restore the subtitles and continue playing, but not work if content video changed
actually i am working on video ad,  the subtitles continue showing on mid roll. Even content video is restored, the new subtitles will overlap on the old one

**Comment by Pong420** [comment]
Solved by changing the position of active cue before ad start and restore AD ended

Tested on iOS 11.0.1 and 10.3.3 

Working example:
```js
function hideTextTrack(player) {

    var tracks = player.textTracks();
    var originPosition;
    var activeCue;

    var check = function (track) {
        if (track.mode === "showing" && track.activeCues.length) {
            activeCue = track.activeCues[0]
            originPosition = activeCue.position;
            activeCue.position = 100;
        }
    }

    for (var i = 0; i < tracks.length; i++) {
        check(tracks[i])
    }

    return function () {
        if (activeCue) {
            activeCue.position = originPosition;
        }
    }

}

// usage
var restoreTextTrack;

// before AD start and only use for iOS
restoreTextTrack = videojs.browser.IS_IOS && hideTextTrack(player);

// AD ended
if ( restoreTextTrack ) {
    restoreTextTrack();
    restoreTextTrack = null
}

```

**Comment by gkatsev** [comment]
Thanks for posting your workaround.
