### ISSUE TITLE
Unable to disable autoplay after autoplay has been enabled

### ISSUE THREAD

**Issue by tjaneczko** [videojs/video.js#5005]
## Description
If autoplay is enabled via player options it is not possible to disable autoplay via `player.autoplay()` due to the introduction of `forceAutoplayInChrome_` ( #4804 ).

JSBin: http://jsbin.com/wuhoniwopu/edit?html,output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Instantiate a player using `window.videojs` on an existing video element with the `autoplay` option set to `true`
3. Call `autoplay(false)` on the player
4. Load a video using `src()`

### Expected
Expected the video to be loaded but not play automatically

### Actual
Video is autoplayed

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
v6.3.3
#### browsers
Tested on Chrome and IE11, but should affect all browsers.
#### OSes
Tested on Mac OS X and Windows 7, but should affect all operating systems
### plugins
None

**Comment by gkatsev** [comment]
So, I think it's possible that we can just remove `forceAutoplayInChrome_`, removing it seems to work in latest chrome. I should see whether it works in chrome 64 too.
