### ISSUE TITLE
Safari Native and VideoJS Players Both appear

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/video.js#5010]
Hey there,

When testing videoJS on Safari, the menus of the native and videoJS players appear above each other before I enter full screen.
 

I know it's not possible to override the native player. Is there a chance to hide the menu of the native player before entering full screen?

**Comment by gkatsev** [comment]
Hi, seems like most of your message got cut off. Can you update it following the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by maryam-abdullah** [comment]
I edited it.
Thanks for informing me.
