### ISSUE TITLE
The media playback was aborted

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/video.js#5021]
Hey there,

I sometimes get the following error (when tested on MAC Safari) (very rare but it happens):
The media playback was aborted due to a corruption problem or because the media used features your browser did not support

I'm using 5.13.0 version of videojs-contrib-hls and I've read somewhere that 5.11 version uses only a single audio/video track when multiple are present to prevent the distortion. 

Many thanks.

**Comment by gkatsev** [comment]
By default contrib-hls doesn't get used on safari. If you're using the default options, it means that safari itself can't play the video for whatever reason.

**Comment by maryam-abdullah** [comment]
Safari native player sometimes play the video and sometimes (very rare) it gives the error I've mentioned above.

Is it possible it's happening cause of the stream?

**Comment by gkatsev** [comment]
Yup, it's possible that some segments are malformed or something like that. @gesinger any ideas on what could cause the stream to fail?

**Comment by gesinger** [comment]
No ideas of the specific issue offhand, but if it happened with the native Safari HLS player, then it is almost definitely an issue with the content. The native Safari HLS player is pretty robust, and quite spec compliant (especially since they write the spec).

**Comment by maryam-abdullah** [comment]
I see.
But that happened before pressing the play button, just loading the video caused this error.
Does it make any difference?

**Comment by gkatsev** [comment]
it can still happen because safari is preloading some of the video, so, during preload it might fail.

**Comment by gesinger** [comment]
Yeah, Safari can start preloading some of the video segments even before playing.

**Comment by maryam-abdullah** [comment]
I see.
Thank you for your explanation.

**Comment by gkatsev** [comment]
Answered.
