### ISSUE TITLE
Roku Tv Support

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#5030]
Hi All,

This is more of a question than an issue but not sure the best place to ask so feel free to close.

I keep getting asked about Roku Tv I am not familiar with Roku Tv. 

https://www.roku.com/en-gb/how-it-works

But from what I gather it's another apple tv, Chromecast, fire stick?

You buy a stick like Chromecast and the make the connection over your wifi.

https://www.amazon.com/Roku-Express-more-powerful-Streaming/dp/B075XN1NZC/ref=sr_1_4?s=tv&ie=UTF8&qid=1521448720&sr=1-4&keywords=roku

The only information I can get connecting videojs and Roku tv is here: https://apiant.com/connect/Video.js-to-Roku & https://www.muvi.com/tag/video-js

Do I need to integrate the Roku Tv sdk https://developer.roku.com/en-gb/develop/sdk-documentation/sdk-index into a videojs button to provide the same sort of functionality as Chromcast apple airplay etc?

Figured it was worth asking someone might be able to point me in the right direction instead of me wasting time working on something that's already done or doesn't even work how I think it does?

Thanks

**Comment by rudemateo** [comment]
I don't believe there is anyway for video.js to control or "cast" to a Roku directly from the browser without the user installing an extension, like this: https://github.com/pranav-prakash/RokuCast. Typically developers publish "channels" to the Roku Platform through their developer portal, using the Roku SDK and writing a complete content browse and playback application in the 💩 BrightScript language. The way that RokuCast extension works is using the SSDP and DIAL protocols, as described here: https://sdkdocs.roku.com/display/sdkdoc/External+Control+API  but neither of those is possible to implement without an extension. Hope that helps. I think this ticket should be closed.

**Comment by samueleastdev** [comment]
Thanks, @rudemateo this is helpful feel free to close gives me some information to run some tests with.
