### ISSUE TITLE
Frequency capping not working with VAST ads

### ISSUE THREAD

**Issue by razor1907** [videojs/video.js#5034]
## Description
I'm running a VAST ad in my player and the problem I encounter is that there is no frequency to be set. Everytime you enter a video page, the advertisement starts before the video starts playing which is very bad for user experience.
I assume that cookies are not being send with the request to a the vast url.

### Expected
Fix the cookie/frequency issue.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
v4.12.15
#### browsers
Any broswer
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
videojs.ads.js
videojs-vast-plugin

**Comment by gkatsev** [comment]
Hey, unfortunately, we don't really handle much of the ad related things beyond an ad plugin to make writing ad integrations easier. This issue should probably be raised against the videojs-vast-plugin you're using. The videojs-vast-plugin should be in charge of making the VAST requests.
