### ISSUE TITLE
Video js- Video ended events taking some time to call.

### ISSUE THREAD

**Issue by BijayRai** [videojs/video.js#5042]
## Description
For other videos its working perfectly fine.
But One of the video having 5 min 52 sec. Whenever i play this video and on the end of video, ended event takes more than 10 sec to be called. 

## Steps to reproduce
Whenever i played video and at the end of video ended event is calling perfectly fine. but on this one particular video video end call back taking time. 

### Expected
Ended event should be call back immediately. 

```
            player.on('ended',function(){
              console.log('video ends');
            });
```

Since on that particular video it taking along time to trigger ended event . On timeupdate , i ve checked the current time equals to video duration. On that case that section is called multiples time unless and ended event is called. 

```
            player.on('timeupdate', function(){
              if(player.currentTime() == player.duration()){
                  console.log('video is ended');
              }
            });
```
While doing this, when progress bar reached to the end **video is ended** is called multiples times more than 100 times and then **video ends** is called and it stops. 
And one more thing is like when **video ends** is called and again i replay or like come next time to the same video then **video ends** is called perfectly after the end of video whithout taking time but if i refresh the whole browser and play this video again at the very beginning its taking time to call ended event . 

So, what might be issue here which is preventing video js to call ended event after progress bar reached to the end of video.

**Comment by gkatsev** [comment]
Hi, can you provide more information about your scenario? is the player set up with ads, specifically videojs-ima? What version of video.js is this? Does it happen what browser is this?
Would you be able to provide a reduced test case?

**Comment by gkatsev** [comment]
Closing due to lack of information. We can re-open if we get more info.

**Comment by hgsadhrakiya** [comment]
@BijayRai 
Yes, you are right.
It is taking around 5 seconds to call that function.
I am also trying to find that reason, but it is not being resolved.
