### ISSUE TITLE
VideoJs Not Fitting on Embed Container

### ISSUE THREAD

**Issue by ecchirealm** [videojs/video.js#5045]
## Description
The Video JS video is not fitting in the embed container. There is a scrolling option instead of it just fitting in the container. 
How do you stretch to fit? Thanks

**Comment by gkatsev** [comment]
Try adding the `vjs-fill` class to the player.

**Comment by ecchirealm** [comment]
which folder do i add that to?

**Comment by Gokhan1990** [comment]
its players class

**Comment by gkatsev** [comment]
yup, the class, something like:

```html
<video class="video-js vjs-fill">
```
