### ISSUE TITLE
playing from vimeo links,  only sound working with black screen video. 

### ISSUE THREAD

**Issue by Gokhan1990** [videojs/video.js#5047]
ONLY SOUND COMING AND EVERYTHING WORKS PERFECT BUT NO VIDEO SHOWN ONLY BLACK SCREEN.

**Comment by Gokhan1990** [comment]
i noticed that height is coming 0. but on the other hand playing from youtube works perfect. the height is problem.

**Comment by gkatsev** [comment]
How are you playing the vimeo link? Is it an m3u8/mp4 url from vimeo pro or is it using the vimeo tech?

**Comment by gkatsev** [comment]
Closing due to lack of information. If we can get more info, we can take a look.
