### ISSUE TITLE
Does Setting OverrrideNative to True Affect VideoJS on Mac Safari?

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/video.js#5048]
Hey,

I was wondering if I've set **overrideNative** to true when setting up videoJS,
does it affect the player on Safari (Mac)?
Because I'm getting this error: "The media playback was aborted due to a corruption problem or because the media used features your browser didn't support" or "cannot read property **bytelength** of undefined" or "The object is in an invalid state".

Below is how I've set up the player:
```
videojs.options.hls.overrideNative = true;
	var options = {
	html5: {
    nativeAudioTracks: false,
    nativeVideoTracks: false
  },
		controls:true,
		autoplay: true,
		preload:"auto",
	};
```

Is Safari native player used in case I didn't set overrideNative to true?

Thank you in advance.

**Comment by gkatsev** [comment]
By default, contrib-hls uses native playback when available. Safari is one of those places. Setting overrideNative will use contrib-hls and MSE but we haven't really tested it or currently recommend it.
We're currently investigating MSE support on safari.
As for the errors, are they happening with native playback or just with override native?
