### ISSUE TITLE
Use Media Capabilities Decoding Info API

### ISSUE THREAD

**Issue by beaufortfrancois** [videojs/video.js#5068]
The Media Capabilities API is an API for querying the user agent about decoding and encoding capabilities of the device, providing better information about the display properties, and real-time feedback about playback so that adaptive streaming can better alter the quality of content based on user perceived quality. The intent of this API is to give more control for content delivery while providing a better user experience.

I think this would be great to integrate it into video.js as it is going to be enabled by default in Chrome 66 and is already used by YouTube player.

Example:

```js
const mediaConfig = {
  type: 'media-source', // or 'file'
  audio: {
    contentType: 'audio/webm; codecs=opus',
    channels: '2', // audio channels used by the track
    bitrate: 132266, // number of bits used to encode a second of audio
    samplerate: 48000 // number of samples of audio carried per second
  },
  video: {
    contentType: 'video/webm; codecs="vp09.00.10.08"',
    width: 1920,
    height: 1080,
    bitrate: 2646242, // number of bits used to encode a second of video
    framerate: '25' // number of frames used in one second
  }
};

navigator.mediaCapabilities.decodingInfo(mediaConfig).then(result => {
  log('This configuration is' +
      (result.supported ? '' : ' NOT') + ' supported,' +
      (result.smooth ? '' : ' NOT') + ' smooth and' +
      (result.powerEfficient ? '' : ' NOT') + ' power efficient.');
});
```

Resources:
- https://wicg.github.io/media-capabilities/
- https://developers.google.com/web/updates/2017/12/chrome-63-64-media-updates#media-capabilities-decoding-info-api
- https://googlechrome.github.io/samples/media-capabilities/decoding-info.html
- https://www.chromestatus.com/feature/5869632707624960

**Comment by gkatsev** [comment]
@videojs/playback media capabilities is shipping soon!

**Comment by forbesjo** [comment]
Looks pretty cool, we'll take a look at it for the ABR in https://github.com/videojs/http-streaming

**Comment by beaufortfrancois** [comment]
Great! Let me know if you have any questions.

**Comment by forbesjo** [comment]
Moving this to VHS and labeling for our backlog

/move to @videojs/http-streaming

**Comment by forbesjo** [comment]
@gkatsev looks like you'll have to move it
