### ISSUE TITLE
Video loaded from source with invalid securtiy certificate in IE11 throws MEDIA_ERR_SRC_NOT_SUPPORTED error

### ISSUE THREAD

**Issue by sicLotus** [videojs/video.js#5069]
## Description
If I try to play a video with IE11 from a url which has an invalid security certificate the media could not be loaded. Firefox and Chrome do not cause any problems. I don't know if this is a bug/feature from IE11 but it took me some time to find out the problem. Maybe it would be great if there could be a flag to disable security issues or at least show a different error for easier debugging?

**Comment by gkatsev** [comment]
I think it might be an IE feature that we can't really do much about it. It's pretty strict in a few cases and there's not really much we can do from inside the browser without asking the user to change security restrictions.

**Comment by gkatsev** [comment]
Closing as a browser bug, it isn't really a bug but it is a browser specific behavior as far as I can tell.
If you have an example, we could maybe take a look.
