### ISSUE TITLE
Any way to expose the native video download button?

### ISSUE THREAD

**Issue by nightsurge** [videojs/video.js#5075]
Since Chrome 65, google decided to now block downloading of resources using the <A download/> attribute if the resource is from another domain. My use case was simple: Allow users to download the video they are already able to watch from any origin.

While I can no longer download cross-origin videos using the <a> tag, it appears the built in video player for Chrome's download button still works just fine! But when using videojs, that native download button goes away, so is there any way to tie into that or expose it back into the videojs display without using a custom (and now broken) <a> tag?

**Comment by gkatsev** [comment]
I don't think there's a way for us to expose the download button directly. You can try disabling the Video.js controls and use the native controls or you could probably add a button yourself that will trigger a download of the video.
Also, the native download functionality should be available via the native right click menu.
We won't be adding a button ourselves, but we'd be happy to help you out in making your own custom button. I'm going to close this issue, but you can continue asking questions in here or in our [slack](http://slack.videojs.com).
