### ISSUE TITLE
Player setTimeout Use Unkind To Battery Life

### ISSUE THREAD

**Issue by cjbarth** [videojs/video.js#5076]
## Description
There is a setTimeout loop in that causes JS to be executed every 250 ms and then the associated garbage collection. This doesn't respect battery usage. It also doesn't scale very well if you have multiple video players on the page at the same time, even if they aren't doing anything. Each player is firing 4 events per second, so if you have 6 players on the screen, like in a gallery, then you'll have 24 timeouts occurring every second on a page that the user hasn't yet interacted with and isn't apparently doing anything.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Visit http://jsbin.com/axedog/edit?html,output
2. In Firefox (easiest to see), gather Performance statistics
3. Note the events firing without having had any interaction with the player, not even a mouse-over on the player.

### Expected
I expect that when the page loads and there is no user interaction, it just sits there. Additionally, I expect that a page that isn't apparently doing anything, is actually not doing anything.

### Actual
The player causes a timeout to occur, and code to be executed, every 250 ms. This also causes garbage collection to happen.

### Error output
No errors.

#### videojs
https://github.com/videojs/video.js/blob/7da77661fc76ad911540764209eb597060b68979/src/js/player.js#L3015-L3047
#### browsers
All of them, but very easy to see on Firefox.
#### OSes
All of them.
### plugins
No plugins used.

**Comment by gkatsev** [comment]
It probably makes sense not to start `listenForUserActivity_` until play is request on a video.
Would you be interested in making the change?

**Comment by cjbarth** [comment]
Then there should be a way to turn it off. I have only just started looking at the code. Could someone point me in the right direction about the best way to do this (functions I should start reading)? Otherwise, reading and comprehending all this could take a while:)

**Comment by cjbarth** [comment]
That only captures the first part of the problem. The second part of the problem is that there is nothing to unset the interval when the player is destroyed or when play stops.

Really, even the johnresig.com suggestion isn't very good as good JS will never leave an interval orphaned. It seems what probably should happen is something like this:

```
var eventTimer;
element.on('event', function () {
    clearTimeout(eventTimer);
    eventTimer = setTimeout(function () {
        doWork();
    }, 250);
});
```

What do you think?

**Comment by cjbarth** [comment]
Indeed, I was using `.destroy()` incorrectly, and thus leaking the interval.
