### ISSUE TITLE
HLS video player with an playlist.

### ISSUE THREAD

**Issue by JoshaGibs** [videojs/video.js#5079]
Can someone supply me with the code to get an HLS with Playlist video player to work. I have tried putting the codes together but it's not working for me. I don't doubt that it doesn't work at all. I just don't have very strong coding skills to almost none at all. Hoping that support for my issue is quick and helps other people get this solved.

**Comment by JoshaGibs** [comment]
The playlist is the advance.js file correct? Does anyone have that file with the needed urls supplied in it. I hate that the code is so lengthy. It would take me forever to put the needed sources into it.
I mean I will put the playlist items in it but the source links to the main codes I can't find their origins.

**Comment by gkatsev** [comment]
This has been answered in slack.
