### ISSUE TITLE
player error event doesn't fire and not same on different brower

### ISSUE THREAD

**Issue by Yalhu** [videojs/video.js#5089]
## Description
Player error event doesn't fire on some mobile and I don't have a test on Mac.
On chrome it work well.

On Edge boswer , `CODE:3 MEDIA_ERR_DECODE` happed ,not 'CODE:2 ' which happend on Chrome.
And dash video doesn't fire on error, whatever code.videojs/video.js#4385

## Steps to reproduce
1. play video
2. disconnect network
3. error event doesn't fire until the cache run out .

I want to resolve issue videojs/video.js#1805 and where are reference code.

#### videojs
6.2.8
#### OSes
what platforms (operating systems and devices) are affected?
iphone 7(IOS:11.3) 
And I test two Andrio devices ,one is ok, one is not ok;
I don't have a test on Mac. 
### plugins
videojs-contribute-dash

**Comment by gkatsev** [comment]
We don't filter out errors that are fired on the video element when we re-trigger them on the player. The [four types of error codes](https://dev.w3.org/html5/spec-author-view/video.html#mediaerror) defined by the spec happen under various conditions we rely on the browser to trigger the errors and don't handle triggering these errors ourselves. If the error isn't triggered, it means that the browser didn't trigger it for whatever reason.
