### ISSUE TITLE
What is the correct way to extend the "user active" logic?

### ISSUE THREAD

**Issue by dandelionred** [videojs/video.js#5095]
I would like to prevent the control bar from hiding while it is hovered. 

What is the correct way to add the "the control bar is hovered" rule to the logic implemented in [listenForUserActivity_()](https://github.com/videojs/video.js/blob/4399bdce5d88f713a9736ccfbe446c7bbfc74986/src/js/player.js#L2964)

I'm using the stock default skin. BTW.

**Comment by gkatsev** [comment]
the `inactivityTimeout` option dictates whether the control bar will hide or not. A potential solution would be to listen to `mouseover` on the control bar and set `inactivityTimeout` to `0` and then set it back to it's old value via on a `mouseleave`.
You can set the option after the fact via something like `player.options().inactivityTimeout = 0`

**Comment by dandelionred** [comment]
Thanks, the issue is resolved.

The only thing is I had to disable videojs logging since each time `player.options()` is called a warning is issued into console.

**Comment by gkatsev** [comment]
Cool, closing as resolved then.
