### ISSUE TITLE
Stream application/octet-stream 

### ISSUE THREAD

**Issue by vlafranca** [videojs/video.js#5103]
Hi,
I am using a provider that actually sends video files as application/octet-stream chunked request.
Event if the file is specified mp4 the video never load. 
Is it possible to make it load ?

Here is the request streaming the video file : 
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Disposition: attachment; filename=my-video.mp4
Content-Length: 545197475
Content-Range: 0-545197474/545197475
Content-Type: application/octet-stream
Date: Mon, 16 Apr 2018 22:44:56 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

Thanks in advance for your help

**Comment by gkatsev** [comment]
I think browsers generally even ignore the content-type in the header. However, most require support for byte-range requests.

**Comment by gkatsev** [comment]
As far as I can tell, you need a backend that supports byte-range requests. You can also see if http://docs.videojs.com/tutorial-troubleshooting.html will help out.
