### ISSUE TITLE
RTMP link in M3U playlist

### ISSUE THREAD

**Issue by sfanous** [videojs/video.js#5114]
Hi

Is it possible to directly play an RTMP link that is embedded in an M3U playlist. The following is the M3U playlist being served

`#EXTM3U
#EXTINF:-1 ,Stream
rtmp://.....`

I have been unable to get this to play directly in videoJS 6.8.0 using either application/vnd.apple.mpegurl or rtmp/mp4 types.

My current workaround is to make an Ajax call to download the playlist then use [m3u8-parser](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwixorH_2cnaAhXl8YMKHf3nDR4QFjAAegQIABAq&url=https%3A%2F%2Fgithub.com%2Fvideojs%2Fm3u8-parser&usg=AOvVaw0xKFyYOQQEungYWnJQiqSe) to parse out the rtmp link and feed that to videoJS with the rtmp/mp4 type.

Is there a better/more direct way of doing this?

Thanks in advance

**Comment by gkatsev** [comment]
you can probably use middleware to rewrite the source from the m3u to the rtmp url http://docs.videojs.com/tutorial-middleware.html#setsource)
With a middleware set up to do the above (which would basically do what you're doing now) you'd be able to basically do something like:
```js
player.src({
  src: 'myplaylist.m3u',
  type: 'rtmp/m3u'
});
```
then have your middleware look for `rtmp/m3u` urls. Hope that helps.
