### ISSUE TITLE
The screen stretches before the start of the video.

### ISSUE THREAD

**Issue by 201511006** [videojs/video.js#5116]
## Description
The video screen stretches before the start of the video when I tested on my smartphone.
So the video size is different from the original one at first. 
but when the video starts, the size is changed to the original size.
## Steps to reproduce
I filled the video with 50vh height on the device screen. and I use object-fit: cover because I have to preserve the aspect ratio of the video. Also, hide the rest part of video with overflow: hidden.

```
#video {    
            width: 100%;
            height: 50vh;

            overflow: hidden;
 }
```

```
.vjs-tech{
            object-fit: cover;
}
```

### Expected
![kakaotalk_photo_2018-04-23-15-13-36_75](https://user-images.githubusercontent.com/26540887/39109927-11a1086e-470a-11e8-9153-5dcbcfb84ae4.jpeg)

### Actual
![kakaotalk_photo_2018-04-23-15-13-34_97](https://user-images.githubusercontent.com/26540887/39109948-2531b400-470a-11e8-84b1-9c9033bd8f00.jpeg)

I wonder why this is happening. Is it a browser issue?
How to solve this problem?

#### videojs
6.8.0
#### browsers
I tested on my smartphone and it occurs everywhere except Chrome browser. 
#### OSes
I use android devices.

**Comment by gkatsev** [comment]
Unfortunately, I can't reproduce it but it sounds like it may be just a browser bug, potentially the browser doesn't support `object-fit: cover`. Some only support object-fit for images.

Are you trying to maximize the video but not have any black bars on the top or the side?

**Comment by 201511006** [comment]
Yes. I'm trying to show video without black bars. 
How can I maximize the video with the aspect ratio preserved?
Is there another way to maximize the video?
