### ISSUE TITLE
HLS events error vs the video.onerror event

### ISSUE THREAD

**Issue by melodysummer** [videojs/video.js#5126]
## Description
You know The Hls player can catch errors as below:

```
this.Hls.on(Hls.Events.ERROR, (e,data) => {
        if (data.fatal) {
          switch (data.type) {
            case Hls.ErrorTypes.NETWORK_ERROR:
             /*hanle here*/
              break;
            default:
              break;
          }
        }
      });
```

and the video itself can catch errors by vide.onerror function.

The question is why no video onerror when hls triggers errors.
the video onerror is blocked by Hls,js?
I cannot find any code related.

**Comment by gkatsev** [comment]
`video.onerror` is how to catch errors on the native element. Given that HLS errors aren't native errors, they aren't available as `video.onerror`.
Instead, it would be best to listen to errors via `player.on('error', function() {})`.

**Comment by melodysummer** [comment]
there is a very strange result after I had the test.
video.onerror trigger an error of "MEDIA_ERR_SRC_NOT_SUPPORTED" when the src http response code is 404 or 403. but not MEDIA_ERROR_NETWORK.
why is it? network error is what kind of error?

**Comment by PeakJ** [comment]
I also have this problem, when trigger videoElement onerror,videoElement.error is null,i can't find the reason for error
