### ISSUE TITLE
Auto height based on aspect ratio

### ISSUE THREAD

**Issue by jcreek** [videojs/video.js#5127]
## Description
It has been a long time since issue #771 and it seems the same problem still exists. I am producing two sets of videos to go on a single page - one in landscape and one in portrait - and have set up my CSS grid so that the landscape video takes up 9 columns and the portrait takes up 3 columns. Ideally the portrait video should fill the available space above and below it in the containing div (which would also hide the JS warning text) but I have been unable to find a way to do so. 

Here's the JSBin based on the template: 
http://jsbin.com/neneyisife/1/edit?html,output 

I've had to use the landscape video file on there for the example but my actual video file for the right hand video is in 9:16 aspect ratio rather than 16:9. 

### Expected
Having added the data-setup="{"aspectRatio": "9:16"}" to the tags of my portrait video I was hoping it would auto height. 

### Actual
There was no change. It's the same as the default. 

## Additional Information
I've tested this in multiple browsers and its definitely my code that's the issue. Is there now a way to achieve what I'm looking for or would I have to find a way of coding it in javascript or something?

**Comment by gkatsev** [comment]
Hey, I fixed up your example a bit and it seems to be working. Unless I'm missing something wrt the 9:16 aspect ratio: see https://output.jsbin.com/yarelot/1

**Comment by jcreek** [comment]
Hi @gkatsev ,

Your code seems to work perfectly! It seems changing the double quotes to single quotes and using a more updated version solved my problem - thank you!
