### ISSUE TITLE
Unable to set default value for playbackRate

### ISSUE THREAD

**Issue by nodegin** [videojs/video.js#5128]
## Description
Cannot set the default playbackRate value during player init.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Create a new player instance
2. Listen playback ratechange event and save the playback rate
3. Refresh the page and restore the saved rate setting

### Expected
First visit: rate 1x, setting to 2x, reload the page
Next visit: rate should now be 2x

### Actual
First visit: rate 1x, setting to 2x, reload the page
Next visit: rate does changed to 2x from console.log result, but being reset to 1 by something

### Error output
```
Restoring config,  1
ratechange event 1.5
ratechange event 2
[page reload]
Restoring config,  2
ratechange event 2
ratechange event 1
```

#### videojs
what version of videojs does this occur with?
6.9.0
#### browsers
Chrome 65
#### OSes
macOS
### plugins
videojs-contrib-hls

**Comment by nodegin** [comment]
My sample code for reproducing the issue:

```js
this.player = window.videojs(video, {
  playbackRates: [0.5, 1, 1.5, 2]
})
// restore config
console.log('Restoring config, ', savedRate)
this.player.volume(savedVolume)
this.player.playbackRate(savedRate)


// attach event listeners
this.player.on('volumechange', () => {
  saveRateToLocalStorage("volume", this.player.volume())
})
this.player.on('ratechange', () => {
  console.log('ratechange event', this.player.playbackRate())
  saveRateToLocalStorage("rate", this.player.playbackRate())
})
```

**Comment by mister-ben** [comment]
The video element's playback rate is transient and resets itself to its default value on source change. If you're setting the rate before a source is loaded, use `this.player.defaultPlaybackRate(savedRate)`. Or set  `this.player.playbackRate(savedRate)` only after the source has loaded.

**Comment by gkatsev** [comment]
also, restoring the configs should probably be done when the player is ready, as as doing it in the callback to the videojs() method:
```
this.player = window.videojs(video, {
  playbackRates: [0.5, 1, 1.5, 2]
}, function() {
  // restore config
  console.log('Restoring config, ', savedRate)
  this.player.volume(savedVolume)
  this.player.defaultPlaybackRate(savedRate)
});
```

**Comment by nodegin** [comment]
Hi, thanks for your explainations!

I have moved my restoration code into the `loadedmetadata` event block and it works fine now!

**Comment by gkatsev** [comment]
You're welcome. Glad you figured it out.
