### ISSUE TITLE
Subtitles not working after uglifying the code by Angular CLI

### ISSUE THREAD

**Issue by qstiegler** [videojs/video.js#5131]
We are using the video.js Player in combination with an angular-cli project. By the `addRemoteTextTrack` method of the player, I add subtitles to the video.

```
this.vjsPlayer.addRemoteTextTrack({
    kind: '/path/to/file.vtt',
    label: 'Test',
    src
}, true);
```

This works great when I´m in the development mode of the project. But when I uglify the code by angular-cli by the command `ng build --prod`, the subtitles will not update anymore. What I mean is, that it stays on the subtitle text when you have activated the subtitles but the text does not get updated.

Most of the time I use Chrome for development but this happens in every browser.

## Versions
- "video.js: "6.8.0"
- "videojs-contrib-dash": "2.9.3"
- "videojs-contrib-hls": "5.14.1"
- "`@angular/cli`": "1.7.4"
- "`@angular/core`": "5.2.10"

**Comment by gkatsev** [comment]
Looking at the cli, not really sure what's wrong. Would you be able to make a simple page with Video.js and upload it somewhere?

**Comment by Chocobozzz** [comment]
@gkatsev We have the same bug. It's because of `this.activeCues` https://github.com/videojs/video.js/blob/4d3331e3be17198d9e0eefab29d06134928de5d8/src/js/tracks/text-track.js#L181 that is removed by uglify.

**Comment by gkatsev** [comment]
@Chocobozzz interesting, do you know which rule removes that?

**Comment by Chocobozzz** [comment]
@gkatsev Yes, it's the `pure_getters` rule https://github.com/mishoo/UglifyJS2/#compress-options

Unfortunately we cannot change this rule in angular-cli...

An easy fix would be to change the line to `this.activeCues = this.activeCues` since the `activeCues` setter has no effect.

**Comment by gkatsev** [comment]
@Chocobozzz seems like that should work, would you be interested in making a PR for that?

**Comment by gkatsev** [comment]
Thanks @Chocobozzz! I plan on doing a release of Video.js today, so, it should go out then.

**Comment by Chocobozzz** [comment]
Yeah! Thanks @gkatsev, it's really a pleasure to have a module with a great support, that releases a fixed version just a few hours later. :kissing_heart:

**Comment by thenewbeat** [comment]
Applying this fix `this.activeCues = this.activeCues` in an older version (5.8.0) also addresses this bug. Thank you @Chocobozzz
