### ISSUE TITLE
VIDEOJS: ERROR: {CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED} when playing .ISM files on IE Edge using videojs

### ISSUE THREAD

**Issue by subhranshudas** [videojs/video.js#5132]
Issue-
VIDEOJS: ERROR: {CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED} when playing .ISM files on IE Edge on Windows 10, using videojs while trying to play ISM file.

Expected-
Able to play the same media `http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest`
using DASH player. But when i try to use videoJs to play i get the above error.

the MimeType i have given is - `application/vnd.ms-sstr+xml` for the ISM file.

Any help? 

Regards,
Subhranshu

**Comment by gkatsev** [comment]
I think edge just can't play that source type natively, at least, when testing via browserstack I'm getting an invalid source https://output.jsbin.com/canifij

**Comment by subhranshudas** [comment]
@gkatsev so here's the thing - when i use `dash.js` to play the same media right there is some change i do in `dash.js` source code to get it working for `dash.js` when i include their `mss` package. https://github.com/Dash-Industry-Forum/dash.js/issues/2478#issuecomment-377419260

Now i have done the same change when using `VideoJS` with `dash.js` internally. But i get error while playing it with Video.JS

**Comment by gkatsev** [comment]
are you using videojs-contrib-dash? Video.js by itself can't play DASH or ISM unless the browser supports it.

**Comment by subhranshudas** [comment]
yes, i am using the following --

  require('../../dist/dash.all.debug');
  require('../../dist/dash.mss.debug.js');
  require('videojs-contrib-dash');

While i am able to play `.MPD` format, with the same code.

**Comment by gkatsev** [comment]
ah, contrib-dash probably doesn't know that `application/vnd.ms-sstr+xml` is available with the mss build.

**Comment by forbesjo** [comment]
Yes it only looks for `application/dash+xml` (https://github.com/videojs/videojs-contrib-dash/blob/master/src/js/videojs-dash.js#L373)

**Comment by subhranshudas** [comment]
Am able to play non-protected stream....sweeeeet....

**Comment by gkatsev** [comment]
I wonder if it's possible to detect whether the mss build of DASH is on the page and then support the above mimetype? But maybe if just the DASH mimetype works, we can just tell people to use that?
