### ISSUE TITLE
text track menus use role of menuitemcheckbox, menuitemradio more appropriate

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#5136]
Text Track Menus currently use role of menuitemcheckbox for the menu items. This isn't strictly correct because we only allow one text track at a time. Instead, it would be more accurate to use menuitemradio.
Chapters menu is also a weird one because while using it, it's acts like a menuitemradio, but it also gets updated automatically like a progress bar as you play the video. menuitemradio is probably most appropriate for it.

**Comment by OwenEdwards** [comment]
See https://github.com/videojs/video.js/blob/master/src/js/menu/menu-item.js#L33-L39

**Comment by OwenEdwards** [comment]
See also #3663 for issues related to the Chapters menu. Note that we need to make sure that the Chapters menu is no aria-live and announced when playback moves to a new Chapter, but the Chapter menu does need to be updated.
