### ISSUE TITLE
How does video. Js remove the video event after the video area is clicked?

### ISSUE THREAD

**Issue by LuoRiWuSheng** [videojs/video.js#5137]
## Description
In actual development, I control the play of video through a unified button，So I want to remove the default click-to-play event.

Can someone tell me what to do?

**Comment by ldayananda** [comment]
I'm not sure what you mean by removing the play event itself, can you explain a little more about what you are trying to do?

**Comment by LuoRiWuSheng** [comment]
@ldayananda  Hello. now in the Web when  the video area is clicked, the video will play.
But in my situation, i want to remove this play event. It means, when the video area is clicked, nothing happens.
How can i get it? 
![question](https://user-images.githubusercontent.com/23192097/39619357-1f3a2010-4fba-11e8-9c31-a831f0fe5408.png)

**Comment by ldayananda** [comment]
Looks like the player is being played/paused by this code: https://github.com/videojs/video.js/blob/master/src/js/player.js#L1521-L1537

There's a couple of things I could suggest you trying:

- We could potentially add an option to disable that behavior
- Make a dom element that is positioned over each player to block the clicks until you click the play button
- Use a [middleware mediator(http://docs.videojs.com/tutorial-middleware.html) to block calls to play until the user clicks on the outside play button

@gkatsev is there a good way to disable this behavior?

**Comment by gkatsev** [comment]
The only way to turn that off currently is to disable the controls (i.e., pass in `controls: false` to options). Having a stageClick option might be reasonable.
Though, maybe for use case just `controls: false` might be good enough?

**Comment by gkatsev** [comment]
We've provided a few potential solutions. Let us know if those fit your need or not.
