### ISSUE TITLE
TypeError when using vtt with span using version 6.2.5

### ISSUE THREAD

**Issue by morangil** [videojs/video.js#5138]
## Description
I set my tracks to nativeAudioTracks: false and nativeTextTracks: false and console is throng an error when there's is a span on my vtt file (such as `<i><b>..` )

### Error output
`VIDEOJS: ERROR: TypeError: Cannot assign to read only property 'localName' of object '#<HTMLElement>'
`

**Comment by gkatsev** [comment]
This happens when vttjs runs in strict mode. We can probably remove `localName` from vttjs, but I haven't had a change to make this change and test it.
As a workaround for now, try disabling running video.js/vtt.js in strict mode.

**Comment by vermie** [comment]
Is this resolved by https://github.com/videojs/vtt.js/pull/40?

**Comment by gkatsev** [comment]
Yes, it does! Looks like it's been in Video.js since 7.7.2: https://github.com/videojs/video.js/blob/main/CHANGELOG.md#772-2019-12-02
Good catch @vermie!
