### ISSUE TITLE
how to separate audio from video

### ISSUE THREAD

**Issue by melodysummer** [videojs/video.js#5139]
## Description
video.js can play the video by attachMedia.
but how to separate audio from video? so I can get an audio file and mix other audio as well.
Some sofeware like adobe premiere, audio tracks can easily be separated. how to do this by javascript?

**Comment by gkatsev** [comment]
yeah, you can do it in javascript, we sort of do this in our http-streaming project.
What's your specific usecase?

**Comment by melodysummer** [comment]
thanks for reply @gkatsev .
The use case is to separate audio from a video with mp4 or m3u8 format.
Then we can edit the   audio, concat it with other audio file, or remove the audio from the video.
how do you do it in javascript, by what kind of tech? @gkatsev 
can videojs do it or other js library?

**Comment by gkatsev** [comment]
Are you trying to edit the audio in the browser? Can you elaborate some more on your usecase? But it seems like video.js isn't what you're looking for. Video.js is generally just for playing back video or audio in the browser.

**Comment by melodysummer** [comment]
yeah, we want to separate the audio track from the video file itself. so we can get the video track and the audio track separately. And we can play the audio or video independently.
so how can you get this? @gkatsev . All is in browser,  in the web environment.

**Comment by magikstm** [comment]
@melodysummer basically, you want to sync a video with an audio track?

See that: https://stackoverflow.com/questions/39046644/synchronize-video-and-audio-preferably-without-javascript/39214452#39214452

You may need to adjust the javascript a bit. Depending on your exact needs, I think muting the main video (or removing its sound entirely before publishing it) then syncing the audio track may be the best option.

**Comment by melodysummer** [comment]
thanks for the reply @magikstm 
I saw the code you listed.  But it's not my condition.
You have two files, one audio, one video.
I just have only one file, eg. m3u8 or mp4 file.  how to separate audio data from the file.

**Comment by magikstm** [comment]
I would suggest ffmpeg.

With something like this:
https://stackoverflow.com/questions/9913032/ffmpeg-to-extract-audio-from-video?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by gkatsev** [comment]
ffmpeg would be my suggestion as well.

**Comment by Richardengle** [comment]
could this be used in closed captioning videos for the deaf
