### ISSUE TITLE
Player reset() function causes text track issues

### ISSUE THREAD

**Issue by DougGore** [videojs/video.js#5140]
## Description
The `reset()` function in the Player class appears to have seemingly intentional but undesired side effects. As part of the unloading and reloading of the tech plugin the unloadTech, loadTech functions take a JSON snapshot of the associated text tracks prior to the reset and restores them post reset. Unfortunately when using video.js with plugins like DASH and HLS which usually manage their own text tracks they are removing them during the tech plugin dispose stage and having them subsequently restored afterwards without the plugin itself being aware of this.

I have reproduced this in a simplified [test case here](http://jsbin.com/widotiwile/1/edit?html,output), simply play the video and press "Click me". You will see an accumulation of subtitle tracks in the subtitle selector.

In the case of videojs-contrib-dash you may need to pull this change in as well: https://github.com/videojs/videojs-contrib-dash/pull/251

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Have a video with subtitle loaded
2. Invoke player.reset()
3. Load another stream or the same stream again.

### Expected
The expected outcome is that only the subtitle tracks associated with the new video should be displayed.

### Actual
The subtitle tracks from the original video and additionally the new video will both be displayed.

### Error output
No errors seen, this appears to be intentional behaviour. 

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
6.8
#### browsers
Tested with DASH on Chrome and native HLS on Safari
#### OSes
Test with Chrome on Windows 10 and Safari on OSX
### plugins
videojs-contrib-dash (for DASH)
None for HLS

**Comment by gkatsev** [comment]
Having reset remove text tracks sounds like the correct behavior. Would you be interested in making a PR for that? I'd be happy to help you figure out what needs to happen.

**Comment by DougGore** [comment]
Sure, I can pick this up early next week. From studying the source I think the text track backup/restore code is only used as part of the unloadTech and loadTech functions so this should be mostly a case of deleting code.

**Comment by gkatsev** [comment]
Maybe, though, we do want to make sure that text tracks are kept around during tech switches outside of `player.reset()`. If you have any questions or for more real-time chat, drop in by [our slack](http://slack.videojs.com) when you're working on this.

**Comment by gstrat88** [comment]
There is a bigger problem regarding hls, reset and text tracks.
Hls saves segment metadata as text tracks, so each time a reset is called these text tracks are copied. After some loads and resets the copied json is very big, causing reset to halt because of the addRemoteTextTrack execution. Solution is easy, just call tech().clearTracks("text") before reset as in my situation there are no "real" text tracks. But it seems this is all part of whole in the plot.
