### ISSUE TITLE
Error "Cannot set property 'videojs' of undefined" when minificate video.js file

### ISSUE THREAD

**Issue by nguyenxuanluong-luvina** [videojs/video.js#5141]
Hi,
I using video.js file in my project beside another js sources and it working very well.

But when deploy to a product environment, it have to minification all js file to one file for some reason to use.
( I have reason not using video.min.js version because my project not allow to using a minificated version)
Then I get a problem with error "Cannot set property 'videojs' of undefined" after minificated.

this is videojs source after minificated

`............;!function(a,b){"object"===("undefined"==typeof exports?"undefined":_typeof2(exports))&&"undefined"!=typeof module?module.exports=b():"function"==typeof define&&define.amd?define(b):a.videojs=b()}(void 0,function(){function a(a,b){return b={exports:{}},a(b,b.exports).........,`

After research, I found it occurrce indentity in this line `(global.videojs = factory()`  in video.js file

```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.videojs = factory());
}(this, (function () {
```

Certainly, another js source in same minification method working well.
Somebody can help me to explain what happend with it?
Thank you very much! .

**Comment by gkatsev** [comment]
Looks like this is an issue with uglify and their unsafe transform of typeofs. Uglify 3 has an option to disable it, it's on by default. See the `typeofs` option for compress https://github.com/mishoo/UglifyJS2#compress-options

**Comment by nguyenxuanluong-luvina** [comment]
Thank you very much @gkatsev 
I will check again about this problem
I have another question:
In case of can not change Uglify option, is there any other way to fix this problem? ( example modify source ..etc..)
Thank in advance.

**Comment by nguyenxuanluong-luvina** [comment]
Well, I checked source and my project using `uglify 2.8` then it have no option for disable `typeofs` transform. And I can not change to `uglify 3.0` version to avoid affect another working part in project
is there anyway to modify video.js to workaround this problem?

**Comment by gkatsev** [comment]
How are you including Video.js in your project? Are you using a bundler like webpack or browserify? Or just including the video.js script? If you're using a bundler, make sure to just `import videojs from 'video.js'` or `var videojs = require('video.js')` and have the bundler handle things properly. If you're using the file, you may need strip out the UMD code and make it just be a global script file or building Video.js manually but having rollup output an iife instead of a umd file.

**Comment by gkatsev** [comment]
I have suggested some workarounds in my previous comment.

**Comment by gkatsev** [comment]
Try setting the `comparisons` compress option to false, it might help.
