### ISSUE TITLE
currentTime() sets to different frame in different browsers

### ISSUE THREAD

**Issue by djambrecina** [videojs/video.js#5142]
## Description
Using `player.currentTime()` in different browsers doesn't set the video to the same frame. In Chrome and Safari video was set to the same frame, but in Firefox it was set to the frame that comes before the frame from Chrome and Safari case.

## Steps to reproduce
If video with 30 frames per second is used, and `currentTime` is called with the value 9.562167, in Chrome and Safari it will be set frame 269, in Firefox it will be frame 268.
Frame 268 starts at 9.533333333333333 (`Math.floor(9.562167 * 30) / 30`), and if `currentTime` is called with that value, it will show frame 268 in all browsers.

### Expected
Show the same frame in all browsers.

### Actual
In Chrome and Safari was shown frame that comes after the frame that was shown in Firefox.

### Error output
No errors.

#### versions
6.8.0
#### browsers
Chrome, Safari, Firefox
#### OSes
All

**Comment by gkatsev** [comment]
Unfortunately, this is because browsers are not frame accurate and there's decoding differences between browsers. There isn't really anything that Video.js can do to make this better.

**Comment by gkatsev** [comment]
Closing as "That's life".
