### ISSUE TITLE
First text track (captions) in a list of text tracks not rendering after Chrome 66, no issues before Chrome 66

### ISSUE THREAD

**Issue by sevagsim** [videojs/video.js#5145]
First text track (captions) in a list of text tracks not rendering after Chrome 66, no issues before Chrome 66

Any text track that is not the first renders just fine during playback.  I can see the text tracks in the DOM, but for some reason the first one is always empty.  Stepping through the code, the text track is not always empty, but it becomes empty for some reason.

I thought it may be the track itself, so I swapped it with another track, and the issue is simply related to the first text track in the list of tracks.

Any ideas?  Suggestions ?

**Comment by sevagsim** [comment]
@ldayananda my issue is this: https://github.com/Dash-Industry-Forum/dash.js/issues/2564

**Comment by gkatsev** [comment]
Sounds like this is a DASH issue? From my understanding dash.js renders captions themselves rather than relying on the browser or having us do it via videojs-contrib-dash.

**Comment by gkatsev** [comment]
Closing this as a DASH issue, especially since the linked issue has been closed.
