### ISSUE TITLE
Error on install from NPM via composer

### ISSUE THREAD

**Issue by devaptas** [videojs/video.js#5146]
Composer file:
```
...
"npm-asset/video.js": "^6.9.0",
...
```
Error log using `composer update -vvv`:
> Package operations: 1 install, 0 updates, 0 removals
> Installs: npm-asset/video.js:6.9.0
>                                                                                                                        
>   [InvalidArgumentException]                                                                                                           
>   Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.

**Comment by mister-ben** [comment]
It seems this is an issue with the composer npm plugin: https://github.com/fxpio/composer-asset-plugin/issues/321

**Comment by devaptas** [comment]
But it's strange, because only this package fail for me, and I'm using various on my project. Take a look on this article talking about **npm-signature**: https://blog.npmjs.org/post/172999548390/new-pgp-machinery

**Comment by gkatsev** [comment]
Does v6.10.0 work?

**Comment by devaptas** [comment]
No, same problem.

**Comment by gkatsev** [comment]
I have to do a patch release, I'll try using a newer npm to release but if that doesn't work, I'm not sure what to do.

**Comment by mister-ben** [comment]
All recently published packages will have the npm-signature property that the composer plugin is choking on, and eventually older ones will too. From that [npm post](https://blog.npmjs.org/post/172999548390/new-pgp-machinery):

> You’ll notice that the signatures are only available on newly-published package-versions. We’ll backfill signatures for all packages published earlier than our signing launch, but we’ll do this slowly, so as not to destroy everyone’s registry caches all at once.

**Comment by mister-ben** [comment]
The composer plugin should be fixed in fxpio/composer-asset-plugin/pull/324
