### ISSUE TITLE
about loading, i want to know?

### ISSUE THREAD

**Issue by ch-zgh-1993** [videojs/video.js#5149]
When i give the rtsp url to videoJS,  before play is a loading animate. can i play without the loading time,
not only don't have the loading animate, what i want to do is play the video after loading. ah, there is no loading, and no black screen, too.

there is some configuration to do this?

very thanks!

**Comment by gkatsev** [comment]
Not exactly sure what you mean but you can't play without any loading at all. If you want the video to load before playing, you'd probably want to make sure that player isn't set up to autoplay and then try to play on an event like loadedmetadata or canplay or canplaythrough.

**Comment by ldayananda** [comment]
Do you mean that there is a loading-spinner before content starts to play? If so there's a couple of things you could do:

- set `preload: auto` to download more data before playback starts. Keep in mind that this uses more bandwidth than the other preload settings.
- you can remove the loading spinner from the player by passing `loadingSpinner: false` to the player options, but this will only remove the loading spinner animation and will not make the content load any faster.

The loading time you describe is the player waiting for enough content to download to be able to play and that depends on network speed among other things.

**Comment by ch-zgh-1993** [comment]
thanks, I'm sorry I didn't describe my problem clearly. 
Now, i remove the loading-spinner.
Because my users don't care what frame the picture is.

Thank you for your answer!
