### ISSUE TITLE
Triggering action based on video time

### ISSUE THREAD

**Issue by erik18xk** [videojs/video.js#5150]
I need help for an idea i had this afternoon, is there a way for keep tracking the time of the video and when it match with some variable trigger one action? I'm currently using reactJs and webpack. But once I create the videojs in the componentDidMount I can't get the time. Anybody knows a way?

**Comment by gkatsev** [comment]
You probably want to either listen to the `timeupdate` event, or just have your own timer and then check when `player.currentTime()` is around the time you want to happen.

**Comment by erik18xk** [comment]
Yea, I tried listening to the timeupdate, but due the lifecycle of react I can't re-render new components in the DOM. Cause componentDidMount render just once, and I can't change the state or render new component. Do you know other ways for reactjs?

**Comment by ldayananda** [comment]
You aren't able to change the state of the component itself? If not, you could potentially have the parent component to the one containing the player change it's props to cause a rerender, though the best way is to modify the state of the same component.

**Comment by gkatsev** [comment]
You should be able to use the video.js API to attach a listener for currentTime so that DOM doesn't change and it doesn't re-render the component.

**Comment by gkatsev** [comment]
@erik18xk hey, I noticed you closed this, were you able to figure something about?
