### ISSUE TITLE
Issues with the new Chrome version 66 / Video auto play without sound not working

### ISSUE THREAD

**Issue by gera3d** [videojs/video.js#5152]
## Description
Briefly describe the issue.
Hi Gary, Thank for creating such an awesome piece of code. I have been rocking it on all our sites for over a year with zero issues.  More recently with chromes anti-auto play stuff, it seems like this code may have gotten caught in the crossfire.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Go to https://www.nioralsurgery.com/
2. Just watch the video load and pause on the first frame

You can see the same result on a few of our sites.  Built the same way.  They all stopped working together.
https://amarillooralsurgery.com
https://www.mtstateoms.com/
https://nalortho.com/

### Expected
The video to keep playing over and over

### Actual
Currently, it's just passing on the first frame. You can see what I want it to look like if you click on any page off the homepage then click the homepage link to get back to the homepage.

### Error output
video.min.js?ver=5.0.2:16 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.

This seems to be acting as though my video has audio when it does not.

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?
5.0.2

#### browsers
Chrome

#### OSes
Current version os OSX

### plugins
Nope

**Comment by gera3d** [comment]
Here is the most simple version someone else put together:
https://codepen.io/bav/pen/opvMmx

**Comment by mister-ben** [comment]
Also see this post for an outliner on modern autoplay best practices.
 
http://blog.videojs.com/autoplay-best-practices-with-video-js/
