### ISSUE TITLE
TextTracks change event fired multiple times

### ISSUE THREAD

**Issue by dtranBC** [videojs/video.js#5159]
## Description
The "change" event of the TextTracksis triggered multiple times. You can see a page to reproduce the issue here: https://cs1.brightcodes.net/dtran/BC-40804.html

## Steps to reproduce
Load the sample provided
1. Click Play
2. Change closed caption option
3. Observe the Message Log

**Test Scenario: Choose English then work your way down the list**
Expected Result:

> Language Switched: en
> ************
> Language Switched: fr
> ************
> Language Switched: es
> ************
> Language Switched: ja
> ************
> Language Switched: 

Actual Result:

> Language Switched: en
> Language Switched: en
> ************
> Language Switched: fr
> ************
> Language Switched: es
> ************
> Language Switched: ja
> ************
> Language Switched: 

**Test Scenario 2: Starting from cc1 and work your way up the list**
Expected Result:
> Language Switched: ja
> Language Switched: es
> Language Switched: fr
> Language Switched: en

Actual Result:
> Language Switched: ja
> Language Switched: ja
> Language Switched: es
> Language Switched: es
> Language Switched: fr
> Language Switched: fr
> Language Switched: en
> Language Switched: en

## Additional Information
The results are actually different when you are testing in Safari as the duplicate record is occurring when you switch in any order. With Chrome and Firefox, the event is fired multiple times only when you are going backward from the bottom of the list.
On IE Edge, it actually produces triplets event fired.

The issue is reproducible also on mobile playback.

**Comment by gkatsev** [comment]
It's working as expected currently. You get two change events per change because of the way it's implemented, it's non-trivial to make it only fire one. I think the output looks a bit weird because of how you're reading the tracks list and how Video.js updates the tracks when changes are made and it's basically an issue of ordering.
Previously, we should fire a change event for each track that's in the list but now we don't fire one if the mode of the track didn't change. Now, it just fires per track that's changed and given that we only allow one to be showing, we get two `change` events. Ideally, we'd only fire one change event.

**Comment by dtranBC** [comment]
@gkatsev  - Just to clarify, the multiple events are as expected, however, my only confusion is that the multiple events are only fired if you move up the list rather than down the list.

For example, if you change from English to French, the event only fires once. But if you move back from French to English, the events are fired twice.

Should I not also expect the events to fire twice when I move down the list as well? Either direction, the behavior of the event should be the same right?

**Comment by dtranBC** [comment]
I have a workaround which is now implemented in https://cs1.brightcodes.net/dtran/BC-40804.html

I have also created #5278 to add a new event which would have a different purpose than the current "change" event. The proposed "ttChange" event is only fired for the textTrack which the mode is set to "showing".

**Comment by gkatsev** [comment]
I have a fix for this in #5332
