### ISSUE TITLE
won't auto play , cause chrome autoplay policy of cross origin iframe 

### ISSUE THREAD

**Issue by Yalhu** [videojs/video.js#5160]
## Description
When a video page is loaded on a iframe, which is cross origin from the top page, video won't autoplay. even I set propotype of video as [autoplay-policy-changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) describe:`<iframe  allow="autoplay; fullscreen" scrolling="no" src="crossorigin.php"></iframe>`

When I call play on videojs ready event `setTimeout(function(){arvplayer.play()},200);`, there is an error: `play() failed because the user didn't interact with the document first`. And I can't listen this error on videojs error event or other event, like `window.onerror`. How do  I detect this case?

When work with videojs-contrib-hls, event `loadedmetadata` won't fired, see videojs/videojs-contrib-hls#1418.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
video auto play.
### Actual
video won't auto play.

### Error output
no.

## Additional Information
Please include any additional information necessary here. Including the following:
firefox is ok.
#### videojs
video.js 6.2.8
#### browsers
chrome  66.0.3359.139
#### OSes
win 10
### plugins
videojs-contrib-hls 5.14.1

**Comment by gkatsev** [comment]
From what I understand, the `allow="autoplay"` attribute tells chrome that the iframe is allowed to inherit the embeding page's autoplay policy. So, if the main page isn't allowed to play, the iframe will not either, and vice-versa: if the main page is allowed to play, the iframe embed will be allowed to play as well. We recently published a blogpost about autoplay best practices http://blog.videojs.com/autoplay-best-practices-with-video-js/. You should be able to tell that autoplay was reject by using the promise that's returned from the play() method.

**Comment by Yalhu** [comment]
Thank you very much! It's really helpful.

**Comment by gkatsev** [comment]
You're welcome.
