### ISSUE TITLE
No compatible source was found for this media.

### ISSUE THREAD

**Issue by qianxuemin** [videojs/video.js#5161]
## Description
My chrome find an error which is
```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."}
```
how to result it?

## Results Expected
no error

## Actual
video won't auto play.

## versions
videojs
video.js 6.2.8

## browsers
chrome 66.0.3359.139

## OSes
win 10

## plugins
videojs-contrib-hls 5.14.1

**Comment by gkatsev** [comment]
There's not much to go on here based on your provided information. Assuming that you're playing back an HLS video in chrome on windows and you're getting that, it could be one of several issues. The most likely culprit is Video.js's "late init" where it doesn't try to play back if the browser has already started handling it. There are two ways to work around this. Using the `<video-js>` element or by providing the src via the `player.src()` method.

**Comment by magikstm** [comment]
What are your video specs?

Please share full specs from MediaInfo (https://mediaarea.net/en/MediaInfo) or a similar tool.

**Comment by gkatsev** [comment]
Unfortunately, there's not much to go on here. Check out http://docs.videojs.com/tutorial-troubleshooting.html and http://docs.videojs.com/tutorial-faq.html, maybe there's something that will help.
If you can provide a reduced test case, we'll be able to take a look as well.
