### ISSUE TITLE
Video only working with normal Chrome-Videoplayer

### ISSUE THREAD

**Issue by Litschler** [videojs/video.js#5181]
## Disclaimer
I started using video.js yesterday, so I am not that skilled in using it.

## Description
I made a kind of "video proxy" with express.js and request to load videos whose sources I listed in a MySQL-Table, but it doesn't seem to work with video.js.
Here is a brief overview how it works internally:
```javascript
router.get('/:id', function (req, res, next) {
    db.query(`SELECT * FROM videos WHERE id=${req.params.id}`, function (err, rows, fields) {
        request.get(rows[0].source).on('response', response => {
            res.contentType(response.headers["content-type"]);
        }).pipe(res);
    });
});
```

I think it is related to the HTTP-headers, but I'm not sure.
Here are my HTTP-Headers:
```
X-Powered-By →Express
accept-ranges →bytes
cache-control →max-age=2592000
connection →Upgrade, close
content-length →369887
content-type →video/webm
date →Wed, 16 May 2018 12:48:21 GMT
expires →Fri, 15 Jun 2018 12:48:21 GMT
last-modified →Wed, 28 Oct 2015 12:36:24 GMT
server →Apache
upgrade →h2,h2c
```

I can't seem to find an answer on previous issues that solve my problem.

## Steps to reproduce
1. Start an Express-Server which uses the "Proxy-Server"-Code I included above
2. Try loading a video from the "Server" using video.js

### Expected
I expected to be able to watch the video as I could if I were using the normal video-player

### Actual
I get the error-message ```No compatible source was found for this media.``` instead of the actual video.

### Error output
```
ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.
```

#### videojs
6.9.0
#### browsers
Chrom, Firefox, (most likely others)
#### OSes
Windows 10, (most likely others)
### plugins
video.js-chromecast
video.js-airplay

**Comment by mister-ben** [comment]
The most common problem with these type of proxy implementation is not implementing byte ranges. You do have an `accept-ranges: bytes` header, but do you return the requested range?

**Comment by Litschler** [comment]
Thanks. I suspected something similar. I'll try to fix it when I have time.

**Comment by gkatsev** [comment]
Going to close this for now, I do hope that supporting byte-range requests was enough to fix the issue.
