### ISSUE TITLE
Elements with ARIA roles must ensure required owned elements are present

### ISSUE THREAD

**Issue by jcbreel** [videojs/video.js#5187]
## Description
I'm running [this extension](https://chrome.google.com/webstore/detail/wcag-accessibility-audit/kpfleokokmllclahndmochhenmhncoej) to check the accessibility of the site I'm working on and I'm getting errors related to VideoJS.
Not sure if I'm missing something:
[https://monosnap.com/file/iBVrP27Y7CdA4WYLuq1p6cLq1Li38r](https://monosnap.com/file/iBVrP27Y7CdA4WYLuq1p6cLq1Li38r)

Anyone fixed this?

**Comment by OwenEdwards** [comment]
Okay, this is a testing tool false positive; the ARIA role of menu on menus which don't have any children is what's being flagged (in this case, Playback Rate, Chapters and Audio Track), but those menus have a class of `vjs-hidden` which gives `display: none !important;`, so the menus are hidden both visibly and from Assistive Technology.

I'll do some more digging later to see if there's an obvious/easy way to work around it, but it also should be reported back to the testing tool team.

**Comment by OwenEdwards** [comment]
@jcbreel  I've confirmed that this isn't flagged as an error with Chrome's native accessibility audit, nor with [the Chrome aXe extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd). So I recommend you flag this back to the author of that extension as a false positive.

I'm going to close this issue, but let us know if you see any other problems, especially if you can confirm them with multiple tools.
