### ISSUE TITLE
White space in fullscreen  video for Android device Chrome browser

### ISSUE THREAD

**Issue by Gnanamani2018** [videojs/video.js#5196]
## Description
I have implemented the video js in my project. When video is playing in full screen mode, a blank white space is showing at the bottom of the video randomly. 

The issue is reproducible in the sample video given in the videojs.com 

## Steps to reproduce
1.Load the Url in Android 6.0.1 version (Samsung S6) url =http://videojs.com/
2.Click the full screen icon in the video

### Expected
Video view should be shown in the entire screen.

![video](https://user-images.githubusercontent.com/39554409/40426570-0d50f60e-5eb9-11e8-8bd2-95e8f44851ee.png)

### Actual
Video view is not fully occupied in the device screen
![white bar](https://user-images.githubusercontent.com/39554409/40426628-302242a0-5eb9-11e8-807c-5a4f1c19d347.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
latest version
#### browsers
Chrome
#### Platform
Android version 6.0.1  chrome browser

**Comment by gkatsev** [comment]
That's weird. Can I ask what version of Chrome is this happening with?

**Comment by Gnanamani2018** [comment]
Samsung s6 Android version 6.0.1 Chrome browser 66.0.3359.158

**Comment by alexbes** [comment]
I have the same problem with Chrome 67, Android 8.1.

**Comment by gkatsev** [comment]
On the samsung device I have, I can partially reproduce it. It will go fullscreen like in the above screenshot but it does refresh itself and hide that piece after a second. I'm not really sure that's anything we can do about it, though. It looks like a device specific bug around the fullscreen API.
