### ISSUE TITLE
Is there is a way to set up a adaptive bitrate? 

### ISSUE THREAD

**Issue by patidarkishor777** [videojs/video.js#5198]
I have a Nuevo skin for video.js and skins working fine. I want to implement adaptive bitrate in the player.

Is this possible for you to provide me a demo how I can set up an adaptive bitrate?

**Comment by patidarkishor777** [comment]
I am using video 7.0 can you provide me a documentation how I can enable
this or setup. I am using html5 player with some js config

**Comment by gkatsev** [comment]
you just need to provide an HLS url with the correct mimetype to the player, as a source element or by calling `player.src` after the player has been initialized.

**Comment by patidarkishor777** [comment]
Is there any demo available?

**Comment by patidarkishor777** [comment]
Okay I got demo on nuevolab's website, Is this possible to use HLS plugin with MP4 video file, I didn't have "m3u8" format of playlist.

Or can we create m3u8 playlist from MP4? If yes then how we can?

**Comment by gkatsev** [comment]
You can't really have adaptive bitrate with mp4 files due to how they work. You do need a format like HLS or DASH (.m3u8 or .mpd). If you have an mp4, you can use tools locally like ffmpeg or services like zencoder to re-encode the video into the correct HLS or DASH for you to use.

**Comment by patidarkishor777** [comment]
I really appreciate your help, but I have a website with more than 200000 videos, can you suggest me a better option to use HLS.

**Comment by gkatsev** [comment]
I'm not really sure what to say. You can't have a good ABR experience using regular mp4s.

**Comment by misteroneill** [comment]
In other words, if you want to convert 200,000 MP4s to HLS or another ABR-capable format, you'll need to use a transcoding service, like that provided by Brightcove or similar.

**Comment by magikstm** [comment]
> I really appreciate your help, but I have a website with more than 200000 videos, can you suggest me a better option to use HLS.

Get 10-20 dedicated servers to do transcoding for some months. You should be done in less than a year even with average servers.

**Comment by valecarlos** [comment]
Adaptive bitrate works well but is there a way to force the player to use one when selected? e.g. youtube player lets you know which bitrates are available and lets you choose. is this something we can configure?
