### ISSUE TITLE
Memory leak in Component.requestAnimationFrame

### ISSUE THREAD

**Issue by Ismael** [videojs/video.js#5199]
## Description
Component.requestAnimationFrame leaks functions. Take a look at the code here:

https://github.com/videojs/video.js/blob/954f3d979f5514337d7b6195130da96dcb939c3b/src/js/component.js#L1373-L1388

Every time this is called, a disposeFn is attached to this.on('dispose'). The problem is this function is never freed. So you end up with an ever growing list of disposeFns for long-gone frames.

Only if you actually call cancelAnimationFrame a this.off('dispose', disposeFn) is run and the fn is freed.

I don't know how to fix this because I don't understand why you need to save that function.

## How to reproduce the issue
Load a video in Chrome. In dev tools, select Memory tab. Take a heap snapshot. Wait a few minutes, take another snapshot. Select latest snapshot, click "Comparison" (left of "class filter") and compare to previous snapshot.
Look for "(concatenated string)", if there's a bunch of "vjs-raf-2222" (the functions guids), then you are leaking functions. They also appear in "(closure)", but it's a bit harder to identify them there.

**Comment by gkatsev** [comment]
That makes sense, we probably want to clear out this dispose function when no longer necessary. The reason for the disposeFn is so that if the component or player get disposed before the rAF has triggered, we don't want to trigger the callback method because it could produce errors, in some cases.

I guess we probably want to wrap use a separate callback that nulls out the disposeFn and then calls `fn` with the arguments.

**Comment by Ismael** [comment]
Something like this?

``` javascript
const id = window.requestAnimationFrame((t) => {
        if (this.player_) {
          fn(t);
        }
      });
```
And then removing all the code for disposeFn.

I thought of checking this.player_ since it seems to be the most "fundamental" thing that should be alive. But maybe checking this.el_ makes more sense?

**Comment by gkatsev** [comment]
Yeah, checking .el_ is probably better, could even check both.
Also, I was actually event thinking of doing the same thing as in cancelAnimationFrame for removing the dispose handler
https://github.com/videojs/video.js/blob/954f3d979f5514337d7b6195130da96dcb939c3b/src/js/component.js#L1410-L1414

**Comment by Ismael** [comment]
Want me to do a pr?

**Comment by gkatsev** [comment]
That would be great @Ismael!

**Comment by Ismael** [comment]
I don't understand why the tests fail. It requires deeper knowledge of what's going on...
