### ISSUE TITLE
Fastly/Zencdn hosted versions of 7.0.3 return Access Denied messages.

### ISSUE THREAD

**Issue by enzanki-ars** [videojs/video.js#5208]
## Description

Fastly/zencdn hosted versions of 7.0.3 listed on https://videojs.com/getting-started/ return Access Denied messages.

- https://vjs.zencdn.net/7.0.3/video-js.css
- https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js
- https://vjs.zencdn.net/7.0.3/video.js

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Visit any of the above links.

### Expected
Return actual file.

### Actual
Printed below error.

### Error output
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>[removed]</RequestId>
  <HostId>[removed]</HostId>
</Error>
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.0.3
##### CDN
vjs.zencdn.net
#### browsers
All
#### OSes
All
### plugins
None.

**Comment by gkatsev** [comment]
Whoops, forgot to publish it to the CDN, thanks for noticing.

**Comment by gkatsev** [comment]
Should be up now.

The latest ie8 script is http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js, I guess the code that does the version replacement on the getting started page didn't account for us removing it in v7.
You shouldn't need with version 7 of the player anyway.

**Comment by enzanki-ars** [comment]
Thanks! 

I just noticed I missed the `If you'd like to support IE8 (for Video.js versions prior to v7)` comment.
