### ISSUE TITLE
html5.js createEl does not reinsert <video> tag into DOM

### ISSUE THREAD

**Issue by tomsaffell** [videojs/video.js#521]
## To recreate
1. instantiate vjs via JS, w/o a source, and specify tech order as [html5, somethingelse]
2. play an asset that use the somethingelse tech  (using .src(), then .play() )
3. try to play an asset that use the html5 tech
## Observed behavior

At (3), the audio can be heard, but there is no visible video
## Cause / Fix
1. When the somethingelse tech is loaded (at 2), the html5 tech is unloaded
2. The unloading calls .dispose(), which ultimately uses .removeChild(), which removes the object from the DOM, but leaves it in memory [1]
3. When html5 tech is reloaded (at 3), createEl is called in html5.js, which does
   
   ```
   if (!el || this.features.movingMediaElementInDOM === false) {
     // If the original tag is still there, remove it.
     if (el) {
       player.el().removeChild(el);
       el = el.cloneNode(false);
     } else {
       el = vjs.createEl('video', {
         id:player.id() + '_html5_api',
         className:'vjs-tech'
       });
     }
     // associate the player with the new tag
     el['player'] = player;
   
     vjs.insertFirst(el, player.el());
   }
   ```

In this case el is truthy, so the insertFirst never gets called, and the <video> element remains outside the DOM. 
## Suggested Fix

```
    if (!el || this.features.movingMediaElementInDOM === false) {

      // If the original tag is still there, remove it.
      if (el) {
        player.el().removeChild(el);
        el = el.cloneNode(false);
      } else {
        el = vjs.createEl('video', {
          id:player.id() + '_html5_api',
          className:'vjs-tech'
        });
      }
      // associate the player with the new tag
      el['player'] = player;


    }

    if (!el.parentNode){
      vjs.insertFirst(el, player.el());
    }
```

https://developer.mozilla.org/en-US/docs/Web/API/Node.removeChild?redirectlocale=en-US&redirectslug=DOM%2FNode.removeChild

**Comment by dopors** [comment]
has anyone had this error in the latest version(7.8.2)? This is really intermittent. when you first open the browser and click the list of video. 

{video tag}
<video
					                id="vid1"
					                class="video-js vjs-default-skin vjs-big-play-centered w-100"
					                controls
					                preload="auto"
					                height="264"
					                data-setup='{ "techOrder": ["html5","youtube"],{"inactivityTimeout": 0},"youtube": { "start": 0 } }'
					                poster="//vjs.zencdn.net/v/oceans.png"
					              >
					                <source src="//vjs.zencdn.net/v/oceans.mp4" type="video/mp4">
					              </video>




{function to load video using vuejs.}
loadVideo(video){
			var player = videojs.players.vid1;
		      player.poster(video.poster);
		      player.src({src: video.sLink, type: video.sType});	
		      player.ready(function() {
				 player.play();
			  });

		      var sLoadTime = 1000;
		      //Load the marker 	
		      if(video.sLink.includes("youtube")){
		      	 sLoadTime = 2000;
		     }
		    
			  setTimeout(() => this.addQuestionMarker(video), sLoadTime)
		},

When the first time it load it will not show the video but you can hear the audio in the background. But if you keep refreshing(alt+f5) it will then load the video and then you can see the video. And it will be okay the rest of the video. 
i have tried this in chrome and in safari. 

plugins used:
 videojs-abLoop
 videojs-marker
 videojs-youtube

**Comment by gkatsev** [comment]
Please open a new issue with a live reduced test case.
