### ISSUE TITLE
How to implement custom buttons and menus in the control bar React

### ISSUE THREAD

**Issue by inerc** [videojs/video.js#5216]
Good afternoon guys.

I had the task of creating custom buttons in the player and the configuration menu. Please tell me how to do this.

We need to form a menu like this.

<a href="https://ibb.co/bKw4nd"><img src="https://preview.ibb.co/dNOTDJ/2018_05_28_13_57_12.png" alt="2018_05_28_13_57_12" border="0"></a>
<a href="https://ibb.co/i2gvSd"><img src="https://image.ibb.co/n1tmYJ/2018_05_28_13_57_20.png" alt="2018_05_28_13_57_20" border="0"></a>

I need to understand how to interact with the player.

Thank you very much for your help

**Comment by ldayananda** [comment]
Hi, @inerc. Sorry for the late response-

You would want to create a  [MenuButton](https://github.com/videojs/video.js/blob/master/src/js/menu/menu-button.js), add menu items to it and add it to the ControlBar. 

An existing example you could look at is how the [TextTrackButton](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/text-track-button.js) extends the [TrackButton](https://github.com/videojs/video.js/blob/master/src/js/control-bar/track-button.js) and then added as a child to the [ControlBar](https://github.com/videojs/video.js/blob/master/src/js/control-bar/control-bar.js).

Hope this helps, also we have a [Slack](videojs.slack.com) if you need more help.

**Comment by inerc** [comment]
Thx!!
