### ISSUE TITLE
HLS issue in IE11 (Windows 7)

### ISSUE THREAD

**Issue by rmnbrd** [videojs/video.js#5222]
## Description
I read in the latest release post that video.js now supports HLS out of the box.
After many tests, it seems to work really well in all the various environments I tested. Good job on that!
But I've come across an issue in IE11 (Windows 7) where it seems HLS is not supported out of the box by the latest version of video.js

Here is [the codepen](https://codepen.io/rmnbrd/pen/ERjKWe) I used to reproduce the bug in IE11, which shows this error message:
![screenshot 2018-05-31 14 58 57](https://user-images.githubusercontent.com/426749/40783586-38905bb8-64e3-11e8-99f6-e38cdc0858e6.png)

The weird part is that it works like a charm in IE11 with Windows 8.1/10.

I thought this problem could have been related to Flash in some way.
But even after adding the `videojs-flash` plugin, the problem persisted 😕 

#### videojs
+ 7.0.3
#### browsers
+ IE11
#### OSes
+ Windows 7
### plugins
+ No plugins

**Comment by forbesjo** [comment]
For Flash HLS playback you'll want something like Flashls. There's a source handler plugin found here https://github.com/brightcove/videojs-flashls-source-handler

**Comment by magikstm** [comment]
For IE11, you could add this line (or adjust to deliver yourself):
`<script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script>`

Ref: https://github.com/videojs/videojs-flash

**Comment by magikstm** [comment]
@rmnbrd there seems to be an issue on codepen on IE11 for some code.

Test here:
https://www.w3schools.com/code/tryit.asp?filename=FRZ361W2IFCC

Same code doesn't work:
https://codepen.io/anon/pen/RJrjNw

It works for me with IE11 on Windows 7 x64.

**Comment by rmnbrd** [comment]
Thank you guys for the quick replies! I got it working using the `videojs-flashls-source-handler` package.

@magikstm Thank you for your advices but I wanted to import the packages from NPM and it didn't work in IE11 on Windows 7 in my tests (using a real example not depending on a codepen)

**Comment by WeBBLiu** [comment]
I have the same problem.
video-js-7.3.0 verison to play m3u8 source .
Not working in windows7 IE11.

**Comment by SergeyKozlov** [comment]
@WeBBLiu I completely agree. I have the same problem. Windows 7, IE 11.

**Comment by Cozmoz** [comment]
I got this working by adding the following two lines in the head only:

```
<link rel="stylesheet" type="text/css" href="//vjs.zencdn.net/7.6.0/video-js.min.css">
<script type="text/javascript" src="//vjs.zencdn.net/5.4.6/video.min.js"></script>
```

**Comment by Cozmoz** [comment]
I also have the video player set up as follows:

```
  <video id='my-video' class='video-js' controls width='640' height='264'
   data-setup='{}'>
    <source src='MY_VIDEO.mp4' type='video/mp4'>
    <source src='MY_VIDEO.webm' type='video/webm'>
    <p class='vjs-no-js'>
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
    </p>
  </video>
```

If you remove `data-setup='{}'` it stops working in IE 11.

**Comment by Jertsa** [comment]
Can you find the code to place the Holaspark player?

Costa Gauci <notifications@github.com>, 22 Ağu 2019 Per, 17:22 tarihinde
şunu yazdı:

**Comment by iamzeki** [comment]
> @WeBBLiu I completely agree. I have the same problem. Windows 7, IE 11.
> I have the same problem.
> video-js-7.3.0 verison to play m3u8 source .
> Not working in windows7 IE11.

I have the same problem too. videojs 7.3.0 verison, videojs-contrib-hls 5.11.1 verison.
How to resolve it? Update videojs and videojs-contrib-hls?
