### ISSUE TITLE
Insecure origin for HTTP request to proxy node server calling actual Playready DRM in Microsoft Edge.

### ISSUE THREAD

**Issue by subhranshudas** [videojs/video.js#5229]
Hi,

I am trying to use VIDEO JS plugin  videojs, `videojs-contrib-dash`, `dash.mss` to run a protected playready stream in Microsoft Edge. But i get the following
```
VIDEOJS: ERROR: (CODE:5 MEDIA_ERR_ENCRYPTED) DRM: KeySystem Access Denied! -- Insecure origins are not allowed [object Object]
```

When i try to run this using plain dash.js, it runs without any issues.

Any help?

Regards.

**Comment by squarebracket** [comment]
When you're trying to use the videojs player, are you accessing it via https but providing a license url that's http?
