### ISSUE TITLE
Support `played` attribute

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#523]
video.js 4.0 does not yet implement the [`played` attribute](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#dom-media-played). `played` is available in Chrome 26 (at least).

http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#dom-media-played

**Comment by mmcc** [comment]
Does #2384 mean this can be closed?

**Comment by heff** [comment]
Hello Matthew, I do not think so. Played has not been fully implemented.
Good bye.



-- 
Sent from mobile

**Comment by mmcc** [comment]
@heff this is super creepy and I'm going to assume you were trying to be @pam just then.

**Comment by heff** [comment]
Aw dang. I thought that was gonna be from pam. I'm lame.
