### ISSUE TITLE
Help! Where is the function `vjs_snap()` ?

### ISSUE THREAD

**Issue by plainheart** [videojs/video.js#5231]
Where is the function `vjs_snap()` ? I find anywhere but get nothing...

**Comment by mister-ben** [comment]
I've never heard of it. It's not a part of video.js core, but it's possible that it's part of some third party plugin. What are you trying to do?

**Comment by plainheart** [comment]
@mister-ben Thanks for your replying! I want take a snapshot of what the player is playing. Now I can realize it in html5 but I don't know how to do in flash ? Will you please do me a favour? ☺

**Comment by mister-ben** [comment]
Unfortunately you can't capture a frame from flash with javascript, except possibly from the context of a browser extension.

**Comment by plainheart** [comment]
That's a pity! But thank you very much.I think I should try to find other possible ways. I will close this issue.

**Comment by mafengkai1995** [comment]
楼主，videojs  rtmp 播放时实现快照解决了吗？
