### ISSUE TITLE
mediaStream in videojs container not working

### ISSUE THREAD

**Issue by erc2804** [videojs/video.js#5243]
I am trying to get my mediaStream from the local webcam to show in the videojs container.
Without videojs it is working fine.

First I'm getting the userMedia, then I add it to the video element with srcObject.

The error I get:
- MEDIA_ERR_SRC_NOT_SUPPORTED 

What I tried so far:
- using the deprecated URL.createObjectURL(mediaStream) and add it directly to a dynamically added source container.

JS:
```
navigator.mediaDevices.getUserMedia(constraints).then(function(mediaStream) {
                var vid = $("#stream")[0];
                vid.srcObject = stream;
                vid.onloadedmetadata = function () { vid.play(); }
                videojs('stream');
}).catch(function(e) { console.log("error: ", e); });
```
HTML:
```
<video id="stream" class="video-js vjs-default-skin" preload="none"></video>
```

**Comment by gkatsev** [comment]
Video.js moves or re-creates the video element when it is initialized which could potentially cause issues setting the srcObject.
I would initialize Video.js as early as possible, potentially before even calling `getUserMedia()` and then you can get the video element via `player.tech().el()` to which you can then set the srcObject. Something like:

```js
var player = videojs('stream');
navigator.mediaDevices.getUserMedia(constraints).then(function(mediaStream) {
  var vid = player.tech().el();
  vid.srcObject = mediaStream;
});
```

Hope that helps.

**Comment by Exlord** [comment]
If you pause the stream then play button does not starts it again https://codepen.io/exlord-the-styleful/pen/oNWjBjR?editors=1000
