### ISSUE TITLE
Adding custom slider into VideoJS control bar

### ISSUE THREAD

**Issue by vs-kiann** [videojs/video.js#5244]
Hi there, 

i am wondering if i am able to add a custom slider( eg: angular slider) on to the videojs control bar? 
i am able to add a button on to the contorl bar, as i want to toggle the button to show the normal progress bar and the custom slider. 

PS: I am using Angular 1.4

Thank you

**Comment by gkatsev** [comment]
You can add custom elements to the control bar. Our control bar is just standard HTML/DOM.
So, you'd probably want to create your angular component and then move it into the video.js control bar.

**Comment by VladimirGoldenberg** [comment]
Hi! I need to create custom slider (scrubber) and move handle bar while animation is playing. Is there any example how to do this?
