### ISSUE TITLE
[Problem]How to set the height when fluid is set to true.

### ISSUE THREAD

**Issue by acodercat** [videojs/video.js#5245]
## Description
How to set the height when fluid is set to true.

### Expected
no
### Actual
no

### Error output
no

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
last
#### browsers
chrome
#### OSes
no
### plugins
hls

**Comment by magikstm** [comment]
Did you try adding something like this to your main player div:
`min-height: 150px;`

This may be useful: https://blog.videojs.com/video-js-5-s-fluid-mode-and-playlist-picker/

**Comment by gkatsev** [comment]
yup, min-height should do it.
