### ISSUE TITLE
Zip file with sources in npm package

### ISSUE THREAD

**Issue by Demivan** [videojs/video.js#5248]
## Description
Video.js installed from npm includes zip file with all source files in dist folder.
8Mb file slows down video.js install and I don't know if it is useful when using video.js as npm package.
### Suggestion
Do not include video-js-{version}.zip in npm package files

## Steps to reproduce
1. Install video.js using npm
2. Check video.js folder in node_modules

### Expected
Expected to see compiled source files and assets

### Actual
video.js folder additionally contains zip file with video.js sources

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.0.3

**Comment by gkatsev** [comment]
Yeah, probably not necessary to be published to npm since all the contents on the zip file are already available.
Want to submit a PR to add the zip file to the [npmignore](https://github.com/videojs/video.js/blob/master/.npmignore)?

**Comment by Demivan** [comment]
Will create PR
