### ISSUE TITLE
No way to set poster image after initialization

### ISSUE THREAD

**Issue by tomsaffell** [videojs/video.js#525]
After initialization, there is no way to set the poster image. 
The player does have a .poster(src) function, but it doesnt change have any effect on the poster image src after initialization.

There are two possible fixes:
1. improve the .poster() function to handle changes to the poster at any time
2. allow a poster attribute to be passed with src, eg.
   
   ```
   .src({src: 'http://foo.com/foo.mp4', poster: 'http://foo.com/foo.jpg'});
   ```

Does anyone have a preference?

**Comment by faiyazalam** [comment]
My working code:
let player = videojs('videoplayer', options);
player.poster("video_poster_url");
player.src({src: "video_url", type: "video/mp4"});

**Comment by gkatsev** [comment]
We also have a [`loadMedia`](https://docs.videojs.com/player#loadMedia) method you can use to do it one operation:
```js
player.loadMedia({
  src:  {
    src: 'video.mp4',
    type: 'video/mp4'
  },
  poster: 'poster.png'
});
```
