### ISSUE TITLE
Subtitles on videoJS chromecast receiver don't load

### ISSUE THREAD

**Issue by Bnabais** [videojs/video.js#5253]
## Description
I'm using videoJS on a chromecast custom receiver and I'm sending a .mpd file to this receiver. I'm not getting any tracks back from this file.
It gets back as an empty array of tracks.
Is videoJS downloading the tracks from the .mpd file on cast mode?

function setTextTrack(textCode) {
     //textCode is 'en' in this case
    window.messageBus.send(senderId, JSON.stringify(player.textTracks().tracks_));
    player.textTracks().tracks_.forEach(function (textTrack) {
        if (textTrack.language === textCode) {
            if (textTrack.mode !== 'showing') {
                textTrack.mode = 'showing';
            }
        } else if (textTrack.mode !== 'hidden') {
            textTrack.mode = 'hidden';
        }
    });
}

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. send message to the receiver
2. put video url on videoJS in the receiver
3. get tracks (is failing)
4. play it

### Expected
Subtitles should show up

### Actual
Subtitles don't show up

### Error output
Array of video tracks is empty

**Comment by BrandonOCasey** [comment]
Do the tracks show up on a non-chromecast player with the same source?

**Comment by Bnabais** [comment]
Yes, they do.

**Comment by BrandonOCasey** [comment]
Do you have an example that you could link? This is a very complex problem as there are a lot of moving parts when dealing with chromecast.

**Comment by Bnabais** [comment]
Already solved it. I could only set and showed subtitles on player.on('loadeddata') method on the receiver side.
Thanks for your time.

**Comment by BrandonOCasey** [comment]
OK feel free to open another issue if you have any more trouble!
