### ISSUE TITLE
Help sincerely : Video.js can not work in Firefox! 

### ISSUE THREAD

**Issue by plainheart** [videojs/video.js#5254]
Hello everyone ~ 
I found that video.js can not work in Mozilla Firefox when I try to play a RTMP stream, it always tells me that `No compatible source was found for this media`. Once I set the type of video source to `rtmp/flv`, an error tip like this will appeared. Unlike Chrome and Opera, it seems that Video.js didn't check that the video of this type need call Flash Tech because the `video` tag didn't be replaced  by a tag of `object`. Is it because there are some errors in my settings?
This makes me puzzled and crazy! (ノへ￣、)
Looking forward to your sincerely help online! ｡:.ﾟヽ(｡◕‿◕｡)ﾉﾟ.:｡+ﾟ

## My Settings
```
<script src="https://cdn.bootcss.com/video.js/7.0.3/video.min.js"></script>
<script src="https://cdn.bootcss.com/videojs-flash/2.1.0/videojs-flash.min.js"></script>
videojs('my-player', {
	techOrder: ['html5', 'flash'],
	flash: {
		swf: './video.js/video-js.swf'
	},
	preload: 'auto',
	controls: true,
	autoplay: true,
	sources: [{
		src: 'rtmp://live.hkstv.hk.lxdns.com/live/hks',
		type: 'rtmp/flv'
	}]
});
```

**Comment by gkatsev** [comment]
Make sure that Firefox allows Flash to load on the page. Also, Video.js requires the stream and connection pieces of the url to be separated by an &, see more info here: http://docs.videojs.com/tutorial-faq.html#q-how-can-i-play-rtmp-video-in-videojs

Hope that helps.

**Comment by Narendrakanneti** [comment]
VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) A network error caused the video download to fail part-way.
--
i am facing this problem in firefox.....
whats the solution for this?

**Comment by plainheart** [comment]
Hi, @gkatsev . 
I can confirm that my Firefox allows Flash to load on the page and RTMP stream url is correctly separated by an `&`, but I have tried many ways, the tip `No compatible source was found for this media` is staying there and doesn't leave. Could you have a test in your environment? I hope that you can send an correct example here if it works well. Thanks a lot!

**Comment by plainheart** [comment]
Are there some developers who can play a RTMP stream well with video.js in Firefox ? Hope that anyone can do me a favour!

**Comment by BrandonOCasey** [comment]
Does the following example work for you? https://output.jsbin.com/wusakisibu/1

That is an example of the flash tech playing an mp4, that seems to work for me.

You can find the code at: `https://jsbin.com/wusakisibu/1/edit?html`

**Comment by plainheart** [comment]
It is still not working for me. Once I try to use flash tech to play a steam or video file in Firefox, it will tell me `No compatible source was found for this media.`. I'm almost crazy now.
![image](https://user-images.githubusercontent.com/26999792/41806350-182ff73e-76ef-11e8-9b1e-a6459369c817.png)
My Firfox version is `60.0.2`.
And video.js is working well in Chrome and Opera.

**Comment by plainheart** [comment]
Thanks! It works finally for me! I tried to use another computer, not my company's, and I saw that Firefox gave me a tip of allowing Flash. And after I allowed that, the video could be played normally. 
Though it works finally, but I'm still puzzled that video.js can not work in Firefox of my company computer which has the same version 60.0.2.
