### ISSUE TITLE
Videojs controls autohide

### ISSUE THREAD

**Issue by mysuf** [videojs/video.js#5258]
Hi guys,

I have one suggestion for possible improvement. It is logic behind controls bar showing/hiding. Now, it has really confusing behaviour that gradually increases user's rage and decreases user's experience. It disapears even if cursor is placed on control bar because of 2s hard timeout. So user is going to click, but it fades out meantime but shows again 1s later, because cursor probably trigger event on underlying player's DOM (this actually loops). I would expect behaviour like:

1. cursor moves over player -> user active
2. cursor stops inside player's bounds(outside control bar) -> sets timeout 2s before going inactive
3. cursor stops inside control bar -> nothing happens or increased timeout about 10s
4. cursor leaves player bounds -> sets timeout 2s before going inactive

Thanks

Version: 7.0.3
Player state: playing

**Comment by gkatsev** [comment]
Thanks for the issue. There's definitely room for improvement here and you've provided some interesting ideas. I'm currently working on a roadmap for Video.js and there's already some stuff related to this there, so, definitely going to reference this issue there.
