### ISSUE TITLE
.mp4 Not Playing In Firefox Even With Flash Fallback

### ISSUE THREAD

**Issue by riveramj** [videojs/video.js#526]
Reopening of #343 

I tried the below code in FF 21 (current) and it does not work. I had 20 but that didnt work either. I also have the latest flash installed and working. "Plug-in version 11.7.700.203 is installed" according to adobe. Also on OS X 10.8 (ML)

from FF inspector: 

> [00:46:24.615] Specified "type" attribute of "video/mp4" is not supported. Load of media resource http://video-js.zencoder.com/oceans-clip.mp4 failed. @ file:///Users/mjr/dev/workspace/mercury/portal/src/main/webapp/templates-hidden/videoJsTest.html
> [00:46:24.615] All candidate resources failed to load. Media load paused. @ file:///Users/mjr/dev/workspace/mercury/portal/src/main/webapp/templates-hidden/videoJsTest.html
> [00:46:24.901] GET http://video-js.zencoder.com/oceans-clip.png [HTTP/1.0 304 Not Modified 41ms]
> [00:46:24.901] GET http://vjs.zencdn.net/4.0/video-js.swf [HTTP/1.1 304 Not Modified 17ms]

The play button shows but if you click it nothing happens and in the console I get

> [00:46:59.464] TypeError: this.b.vjs_play is not a function @ http://vjs.zencdn.net/4.0/video.js:91
> [00:46:59.464] [(new TypeError("this.b.vjs_play is not a function", "http://vjs.zencdn.net/4.0/video.js", 91))]

Code:

``` html
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link href="http://vjs.zencdn.net/4.0/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.0/video.js"></script>
</head>
<body>

<video id="example_video_1" class="video-js vjs-default-skin"
       controls preload="auto" width="640" height="264"
       poster="http://video-js.zencoder.com/oceans-clip.png"
       data-setup='{"example_option":true}'>
  <source src="http://video-js.zencoder.com/oceans-clip.mp4" type='video/mp4' />
</video>

</body>
</html>
```

**Comment by arifulhb** [comment]
@rsadwick Your jsfiddle example still helping in 2015 :) You saved a lot of my time. Though for me, the issue wasn't with Firefox but with Safari (8.0.4) in Mac 10.10.2
