### ISSUE TITLE
 A network error caused the video download to fail part-way.

### ISSUE THREAD

**Issue by Narendrakanneti** [videojs/video.js#5260]
VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) A network error caused the video download to fail part-way.

-------
how to fix this issue...?

**Comment by BrandonOCasey** [comment]
There are a lot of reasons that this can happen. Do you have a specific example? What version of videojs? What type of video format?

Also here is a blurb about the error from MDN, just FYI. 

> Some kind of network error occurred which prevented the media from being successfully fetched, despite having previously been available.

**Comment by gkatsev** [comment]
Also, take a look at our troubleshooting doc: http://docs.videojs.com/tutorial-troubleshooting.html

**Comment by Narendrakanneti** [comment]
Hello...@BrandonOCasey ..
Using version 4.0 in Sap Hybris, working fine with chrome, whene using firefox getting [ VIDEOJS: ERROR: (CODE:2 MEDIA_ERR_NETWORK) A network error caused the video download to fail part-way. ] this error on top of the video  while playing video...
