### ISSUE TITLE
strange lines when buffering

### ISSUE THREAD

**Issue by sagikarni** [videojs/video.js#5264]
## Description
Briefly describe the issue.
When the network is slow and the plugin waits for additonal data videojs presents strange lines.
Please take a look the following video 
 https://www.youtube.com/watch?v=665XbXyz8Y8&feature=youtu.be

**Comment by gkatsev** [comment]
That may be the loading spinner not rendering correctly. Do you have a reduced test case we can take a look at?
Also, what browser and OS is this on? Also, what version of Video.js?

**Comment by sagikarni** [comment]
I'll try to upload a case.
Anyway, see this behaviour bth on my laptop (windows 10 / chrome)
and in my mobile device (android/chrome)
My videojs looks like this 
<video-player class="vjs-custom-skin vjs-big-play-centered"...
and I tried to remove the spinner with css :
.vjs-has-started .vjs-loading-spinner {
  display: none !important;
}
without any luck.
using video.js@6.10.3
thx
Sagi
