### ISSUE TITLE
Video Seeking is not working in Chrome browser

### ISSUE THREAD

**Issue by Narendrakanneti** [videojs/video.js#5266]
I am using Video.js 7.0.3 version ...
i am unable to seek the video(sap hybris -site)..in chrome ..working fine with firefox.

**Comment by gkatsev** [comment]
Can you provide a reduced test case please? Also, which version of Chrome on which OS?
I cannot reproduce locally.

**Comment by Narendrakanneti** [comment]
Hi @gkatsev ...

i am using Chrome Version 67.0.3396.87 (Official Build) (64-bit)  - on windows 7,

// version of videojs.
Video.js 7.0.3 <http://videojs.com/> Copyright Brightcove, Inc.

// test case  .Jsp file  (This is my code snippet)
<video `class="video-js`  vjs-default-skin  vjs-big-play-centered"  
	 width="300" 
	 height="200"						  
	data-setup='{ "controls": true, "autoplay": false, "preload": "auto", "seek": true  }'
          >
<source src="${video.downloadUrl}"  type="video/mp4">															
 </video>

-> video seeking is not working in Sap hybris site, but working with plain html page ,
[  when i check with onseeking="VideoSeeking()" method, getting Uncaught ReferenceError: VideoSeeking is not defined at HTMLVideoElement.onseeking (8355-3062037:1328) in the console ].

-> can you provide solution for this issue ...
   &

How to define seeking option in videojs ?

**Comment by gkatsev** [comment]
I'm not really sure what a sap hybris site is.
I am also unsure what you mean by seeking option or what `seek: true` refers to.

A live [reduced test case](https://css-tricks.com/reduced-test-cases/) would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.

If you're trying to listen to seeking and seeked events, it's best to use the video.js API

```js
player.on('seeking', () => console.log('we got a seeking event'))
```
