### ISSUE TITLE
Multiple stream variants in m3u8 playlist won't play on Android

### ISSUE THREAD

**Issue by vinchi9** [videojs/video.js#5267]
## Description
I am encoding video into multiple streams with different resolution and bitrate in order to enable adaptive HLS playback in video.js player. All the variants are present in single m3u8 playlist, which is passed to the player. In desktop browsers (Firefox, Chrome), iPhone browser and in Android Firefox the playback works fine, but in Android Chrome, Dolphin and Opera the player refuses to play the stream with message "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

Interestingly if only one quality variant is present in the m3u8 playlist, it plays the stream without any problems on all platforms and browsers.

### Stream Information
```
Input #0, hls,applehttp, from '':
  Duration: N/A, start: 9810.060333, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 640000
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 640000
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 640000
  Program 1 
    Metadata:
      variant_bitrate : 192000
    Stream #0:2: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 320x180 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 192000
    Stream #0:3: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 192000
  Program 2 
    Metadata:
      variant_bitrate : 1216000
    Stream #0:4: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 824x464 [SAR 1:1 DAR 103:58], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 1216000
    Stream #0:5: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 1216000
  Program 3 
    Metadata:
      variant_bitrate : 2240000
    Stream #0:6: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 2240000
    Stream #0:7: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 2240000
  Program 4 
    Metadata:
      variant_bitrate : 4288000
    Stream #0:8: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 4288000
    Stream #0:9: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 4288000
```

#### videojs
I am using videojs 7.0.3
#### browsers
Not working in Android Chrome, Opera, Dolphin. 
#### OSes
Affected is only Android (tested on 7.0, 8.0)
### plugins
videojs-flash 2.1.0, videojs-contrib-hls 5.14.1

**Comment by gkatsev** [comment]
Android support for HLS is fairly rudimentary and can fail on more complicated streams. By default VHS (the replacement to contrib-hls) doesn't run on Android and needs to be forced via the [overrideNative](https://github.com/videojs/http-streaming/#overridenative) option.
Also, Video.js 7 includes VHS by default and so contrib-hls shouldn't be necessary.

Hope that helps.
