### ISSUE TITLE
m3u8 type video not working

### ISSUE THREAD

**Issue by yoko10000** [videojs/video.js#5275]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.video.js 6.8+videojs-contrib-hls , it's OK.
2.video.js 7.0.3 ,Google Chrome is OK,but , iphone IOS11.4,it's wrong

### Expected
Please describe what you expected to see.

### Actual
don't work

### Error output
don't work

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.0.3
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
iphone ios 11.4
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
It's impossible to tell what's wrong without an example. Strange, since HLS is played natively in iOS.

**Comment by AlphaFase** [comment]
Maybe you didn't quote ：https://github.com/videojs/videojs-contrib-hls
