### ISSUE TITLE
It seems videojs in Android 7 does not work.  

### ISSUE THREAD

**Issue by marvieir** [videojs/video.js#5276]
It seems videojs in Android 7 does not work.  have an error like "the media playback was aborted due to a corruption problem media used features your browser did not support"

All videos are working in Iphones or desktops with many browsers but in Android using version 7 or later are not working. It seems a clear bug in videojs for Android using version 7 and later

**Comment by gkatsev** [comment]
Hi,

Thanks for opening the issue, can you elaborate on which browser you're using on Android? We have seen it working on Chrome for Android and also Firefox for Android.
Also, what device are you using it on? We have sometimes seen different devices being able to play video differently.
Lastly, what type of content are you playing? Is it an mp4 or an m3u8? A working test page would be great.

Are you able to reproduce the issue when going to videojs.com, as an example?

**Comment by marvieir** [comment]
The mobile for example is a J5 or Samsung S7 or S8 using Google Chrome for example with Android 7 or later. It is a HlS m3u8.

If you create a user in the link www.guitarpedia.com.br then you will be able to see some free videos.

If you are using a Android version 7.1 for example you can see the error.

Regards

Marco

Em 25 de jun de 2018, à(s) 14:31, Gary Katsevman <notifications@github.com> escreveu:

**Comment by gkatsev** [comment]
Can you provide a reduced test case?

Also, Android often has trouble playing back HLS, I would recommend trying to enable videojs-http-streaming on Android making sure to enable overrideNative, at least for Android (https://github.com/videojs/http-streaming#overridenative)

**Comment by marvieir** [comment]
Gary

We use HlS due security concerns. All videos were working fine up to the latest 6 versions in Android but now is not working

There are a lot of other players working in Android 7

Is there any other people complaining about the same issue?

Regards 

Marco

Em 25 de jun de 2018, à(s) 14:51, Gary Katsevman <notifications@github.com> escreveu:

**Comment by gkatsev** [comment]
Are you using DRM or encrypted HLS?

We haven't had other reports of HLS not working outright on Android though Android's HLS support is very rudimentary, hence the suggestion for using VHS.

**Comment by marvieir** [comment]
We are going to move to DRM and MPEG dash soon

Marco

Em 25 de jun de 2018, à(s) 18:15, Gary Katsevman <notifications@github.com> escreveu:

**Comment by gkatsev** [comment]
It could be the DRM you're using isn't supported on Android

**Comment by marvieir** [comment]
Hi Gary

We don’t use DRM yet. Any other advise?

Regards 

Marco

Em 26 de jun de 2018, à(s) 12:14, Gary Katsevman <notifications@github.com> escreveu:

**Comment by gkatsev** [comment]
It's hard to say without a [reduced test case](https://css-tricks.com/reduced-test-cases/).

**Comment by marvieir** [comment]
Gary

Which kind of reduced test we could do to provide more information that help in the analysis?

Regards 

Marco

Em 26 de jun de 2018, à(s) 12:14, Gary Katsevman <notifications@github.com> escreveu:

**Comment by gkatsev** [comment]
Just a single video.js player playing a single video that's reproducing the issue on a page that doesn't have anything else in it.
