### ISSUE TITLE
Seeking after media URL expires does not trigger an error in Safari

### ISSUE THREAD

**Issue by ajw725** [videojs/video.js#5277]
## Description
I'm not exactly sure how to create a reduced test case for this, so I'll describe it as well as I can, but let me know if you need more.

I'm initializing a player for a video hosted on Amazon S3. The bucket is private, and documents can only be accessed via signed URLs with 30-second expiration times (this cannot be changed). In Chrome or Firefox, I can add a listener for the "error" event on the player, and when an error occurs with code 2, I can: 1) store the current time; 2) fetch a new URL and set the player's src to it; and 3) set the current time to the stored time. This looks kind of like the following (except that I'm doing it in React):

```javascript
var player = videojs(videoElement);
var storedTime = 0;
var autoPlay = false;
player.ready(function() {
  refreshSource();
});
player.on('error', function() {
  if(player.error().code === 2) {
    storedTime = player.currentTime();
    autoPlay = true;
    refreshSource();
  }
});

refreshSource = function() {
  player.off('ready');
  $.get(serverEndpoint, function(data) {
    player.src({
      type: 'video', src: data.stream_url.replace(/&amp;/g, '&')
    });
    player.ready(function() {
      if(storedTime > 0) {
        player.currentTime(storedTime);
      }
    
      if(autoPlay) {
        autoPlay = false;
        player.play();
      }
    });
  });
}
```

In Safari, this does not work. It's not that the error event is *never* fired; for example, if I do something like
`player.ready(function() { player.error('uh oh'); });`,
it does trigger the error handler. However, when I try to seek after the URL has expired, it does **not** trigger the error handler. All that happens is that I see a 403 response in the console. If I set the debugger to pause on uncaught exceptions, it never pauses, so there's no error at all for me to handle.

I don't know if this is a Safari bug, a Safari "feature" that videojs just doesn't handle, or a videojs bug, but I'm pretty stuck, so I'd appreciate any feedback or suggestions.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Initialize a video element with a source URL that expires after some time
2. Add an error handler to the video, like `player.on('error', function() { /* stuff */ });`
3. Load the video in Safari
4. Either wait to click play until after the URL expiration time, OR start the video and try to seek to a later time point after the URL expiration time
5. Observe that the stuff in the error handler does not happen

### Expected
The video's "error" event is fired, which I could use to refresh the video source. This is what happens in Chrome and Firefox.

### Actual
The "error" event is **not** fired in Safari.

### Error output
"Failed to load resource: the server responded with a status of 403 (Forbidden)" (this is expected and is also seen in Chrome/FF)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.0.3
#### browsers
Safari 11.1
#### OSes
macOS 10.13.4
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Hey, what type of content are you playing back here? Is it HLS?

I was talking to the @videojs/playback team in our slack channel and for HLS, they'd expect no errors to be thrown if a particular segment 404s or 403s because we'd want to just blocklist that rendition and move along to other alternate renditions. We believe and if there's just one rendition left it'll just continue retrying.

**Comment by ajw725** [comment]
I'm not using HLS - just an old-fashioned URL to a video. I initialize the player and set the src (with JS) to the signed URL of the video in its S3 bucket. The URL expires after 30 seconds, so any request to an un-buffered section of the video will fail, and I need to reset the source to a new URL.

**Comment by gkatsev** [comment]
🤔 sounds like this is just a browser difference where Chrome and FF will throw an error an the byte range request fails but Safari doesn't.

You can probably do something like detect a seek, see if it's within the buffered range, and if not reload the source. You can use middleware to have a good idea of where the user is seeking ahead of time via the `setCurrentTime` middleware function http://docs.videojs.com/tutorial-middleware.html and then use `buffered()` to know where the buffer is http://docs.videojs.com/player#buffered
