### ISSUE TITLE
How to know when video is ready to play

### ISSUE THREAD

**Issue by madprops** [videojs/video.js#5284]
## Description
I'm getting some cases when I reload the tab and the m3u8 stream is not starting.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. I load the video and play it immediately after the ready event is fired
2. Sometimes the video doesn't play.

```
function load_stream(url)
{
	video_player.src({type:"application/x-mpegURL", src:url})

	clearTimeout(video_player_play_timeout)

        // I'm using this as a temporary workaround
	video_player_play_timeout = setTimeout(function()
	{
		video_player.play()
	}, 1000)
}


function prepare_video_player()
{
	videojs('video_frame').ready(function()
	{
		video_player = this
		fix_video_frame()
		load_stream(stream_selected.url)
	})
}
```

I'm guessing it has something to do with the video not being loaded before hitting .play()

As a temporary workaround I'm triggering play() on a 1 second timeout, but I was wondering if there's a better way.

**Comment by DoomTay** [comment]
Try putting this under prepare prepare_video_player

```
videojs('video_frame',{sources: [{type:"application/x-mpegURL", src:stream_selected.url}]}).ready(function()
{
	video_player = this
	fix_video_frame()
	video_player.play()
})
```
