### ISSUE TITLE
MP3 stream freezes videojs native HLS support

### ISSUE THREAD

**Issue by gjactat** [videojs/video.js#5285]
## Description
Videojs 7.0.5 freezes Chrome browser when trying to play a MP3 stream.
We already had this kind of issue in an old videojs-hls-contrib version.

See the following fiddle : https://jsfiddle.net/Jakhob/fLdjho79/13/

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Instantiate videojs with mp3 audio stream
2. browser freezes
3. Browser tab finally crashes

### Expected
The audio should play

### Actual
The browser freezes

### Error output
No output

#### videojs
v7.0.5
#### browsers
Chrome
#### OSes
Windows 10 pro
### plugins
videojs-flash (for flash fallback on legacy browsers)

**Comment by gkatsev** [comment]
Is this an HLS playlist with mp3? I believe VHS doesn't support it yet.

**Comment by gjactat** [comment]
I'll give [this procedure](https://www.wowza.com/docs/how-to-configure-wowza-server-to-stream-audio-only-apple-hls-using-transport-stream) a shot (who knows...)

**Comment by aecorredor** [comment]
@gjactat did following the above procedure work? I am having my player freeze on any non-apple player when switching audio tracks (specifically to audio description).

**Comment by gjactat** [comment]
@aecorredor It didn't work for me. I had to switch back to the latest videojs 6+videojs-contrib-hls which is more stable. I'll get back to version 7 when native HLS support will be ok.
These kind of issues reminds me the problems I encountered with videojs-contrib-hls in 2016. These issues were finally fixed (you can still find traces of them on Google/Github).

**Comment by aecorredor** [comment]
@gjactat alright thanks, and for videojs-contrib-hls which version are you using?
