### ISSUE TITLE
Add module field to package.json

### ISSUE THREAD

**Issue by edoardocavazza** [videojs/video.js#5288]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

As for the [`m3u8-parser`](https://github.com/videojs/m3u8-parser/blob/master/package.json) package, the `module` field in the package.json would be great for bundlers.

### Expected

```json
"main": "./dist/video.cjs.js",
"module": "./dist/video.es.js",
"style": "./dist/video-js.css",
```

### Actual

```json
"main": "./dist/video.cjs.js",
"style": "./dist/video-js.css",
```

#### videojs
7.0.5

**Comment by gkatsev** [comment]
That's something we wanted to add as part of the rollup upgrade and 7.x release but we completely forgot to add it back in.
Would you be interested in making a PR to add that field?

**Comment by edoardocavazza** [comment]
Sure!
