### ISSUE TITLE
hidden captions textTrack not triggering "cuechange" events

### ISSUE THREAD

**Issue by kalieye** [videojs/video.js#5308]
## Description
When setting a 'captions' text track to 'hidden' mode and adding a cuechange event, the events are not being fired.

## Steps to reproduce
1. set the captions track to hidden
2. add cuechange event listener
3. send some cue events

### Expected
cuechange event triggered with the data

### Actual
event is not being triggered, but works when setting the track mode to 'showing' 

### Error output
no error output

#### videojs
7.11
#### browsers
Chrome Latest
#### OSes
OSX

**Comment by sgrogov** [comment]
Hello,

I've got the same problem.
Here is reduced test case https://github.com/sgrogov/bug-cases/tree/master/videojs/mode-hidden-cuechange.

My code is pretty similar to yours
```javascript
player.on('loadedmetadata', function() {
	const trackElement = p.addRemoteTextTrack({src: 'captions.vtt'}, false);
	trackElement.addEventListener('load', function() {
		const track = this.track;
		track.addEventListener('cuechange', printActiveCuesContent);
		track.mode = 'hidden';
	});
});
```
but `cuechange` callback is never fired.

I tried your code but it threw an error because the `track` variable is `undefined`.

**Comment by kalieye** [comment]
@gkatsev sorry for my late reply, your code works but only with the metadata track, which is not what i'm looking for, i'm pushing a subtitles track in a live event and that's the one i need to work on, when i try to add the listener to it nothing gets triggered, it works perfectly if i manually select the CC track from the button, the problem is that i want to render it somewhere else and not on the player so i need it to be hidden or to hide it in another way (on both mobile and desktop clients of course)

**Comment by kalieye** [comment]
@gkatsev thanks so much, will test ASAP and get back to you

**Comment by kalieye** [comment]
@gkatsev i updated and i can confirm that the issue is now fixed, thank you!

**Comment by gkatsev** [comment]
You're welcome. Thanks for checking back in!
