### ISSUE TITLE
Is there any way to embed facebook video in videoJS ?

### ISSUE THREAD

**Issue by kundanshrivastava** [videojs/video.js#5314]
## Description
How to embed facebook videos in videoJS player.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
I know that people have gotten facebook live video working via videojs-flash. Unfortunately, for regular videos I'm not aware of any plugins that can embed facebook videos within Video.js like videojs-youtube.
However, it may be possible to create such a plugin and we could provide help in doing so over on our [slack](http://slack.videojs.com).
Unfortunately, the core team doesn't have the bandwidth to create and maintain such a plugin ourselves.
