### ISSUE TITLE
No translations in subtitle settings window

### ISSUE THREAD

**Issue by Akxe** [videojs/video.js#5316]
## Description
If you delay `addLanguage` function just to next tick, you won't get everything translated correctly.
[Minimal test case](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

Side note:
Delay more than 25ms and none of the UI will get translated

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Initialise video using `videojs(videoElement, options)`
2. Add tranlation using `setTimeout(() => videojs.addLangulage('cz', { ... }), 0)`, this is to simulate `import('./lang/cz.json').then(...)` of language file.
3. most of UI is translated, however not the setting of subtitles.

### Expected
Translations will appear instead of original texts.

### Actual
Text are in english

#### videojs
6.x.x possibly 7.x.x too
#### browsers
all
#### OSes
all
### plugins
none

**Comment by gkatsev** [comment]
This is because the components get translated when they are initialized. If the translations aren't available then, it'll use the default language (english).
I'm not sure there's a reasonable way to fix this in Video.js. I would recommend to make sure to only create the player after the language has been loaded.

**Comment by Akxe** [comment]
I get that, but why the main UI get correct translation anyway? 

---------- Původní zpráva ----------
Od: Gary Katsevman 
Datum: 13. 7. 2018 v 08:05:46
Předmět: Re: [videojs/video.js] No translations in subtitle settings window 
(#5316)


This is because the components get translated when they are initialized. If 
the translations aren't available then, it'll use the default language 
(english).
I'm not sure there's a reasonable way to fix this in Video.js. I would 
recommend to make sure to only create the player after the language has been
loaded.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/videojs/video.js/issues/5316#issuecomment-404735252), or
mute the thread

**Comment by Akxe** [comment]
It would mean that then settings window is initialised before main UI, so my options are, either re-create the component or delay initialisation after languages?

**Comment by gkatsev** [comment]
Do you have a specific component in mind that you see is being translated? Could it be a component that updates it's state and thus could be translated during that transition?

I think the best scenario is to wait until the languages have loaded before loading the player. Though, it may be possible to notify components that a new language became available and they may want to re-render themselves to get the new translations. However, I'm not sure it's really useful to do.

**Comment by Akxe** [comment]
Play button, track, everything on GUI actually, that is why it confused me so much... See the example, it is very interesting behaviour.
