### ISSUE TITLE
Event before source changed

### ISSUE THREAD

**Issue by morgo77** [videojs/video.js#5319]
Hello

I got only a question about source changing process.
VideoJS 7.0.5 in use with a resolution-switcher plugin. I had to modify a bit but the main functionalities still the same.
I know there is an event called "resolutionchange" that is fired after a successfull source change. But I'm looking for the event that is fired before the source change started. Especially I'm looking for it to know what source should be loaded.

Is it an existing event or I should implement it for myself? 

Thank you in advice

player.updateSrc([
  {type: 'video/mp4', res: 360, label: "360p", src: "https://vjs.zencdn.net/v/oceans.mp4?sd"},
  {type: 'video/mp4', res: 720, label: "720p", src: "https://vjs.zencdn.net/v/oceans.mp4?hd"}
]);

**Comment by mister-ben** [comment]
Switching between MP4 variants isn't part of Video.js core'a functionality. The `resolutionchange` event and any event before switching would be part of whichever switcher plugin you are using, so I'd recommend checking with the developer of that plugin.

**Comment by gkatsev** [comment]
We do have an experimental `sourceset` event that may help: http://docs.videojs.com/player#event:sourceset

**Comment by morgo77** [comment]
Thank you for the quick answer. I'll modify the 3rd party plugin then.
