### ISSUE TITLE
Buffering while looping a section of the video

### ISSUE THREAD

**Issue by msushanktheglitch** [videojs/video.js#5323]
I have been using videojs for one of my websites. What I am doing is looping a section of the video. Please see the example below.

myPlayer = videojs('main_video');
setInterval(function(){
    if(myPlayer.currentTime() > 24){
        myPlayer.currentTime(20);
    }
}, 40);

On the desktop it works perfectly fine, but on the phone when the video goes back to 20th second, the video gets stuck for a second and then continues. This happens every time it goes back to 20th second. Because of this glitch the loop doesn't look seamless. On my phone browser(e.g. MI browser) i observed that every time it goes back to 20th second the video starts buffering, not sure why it buffers every single time. Please help.

**Comment by gesinger** [comment]
Hey @msushanktheglitch thanks for reporting. Does this only happen on the MI browser, or have you also observed the behavior on others?

If you would be able to test on mobile Chrome as well, and provide a demo page, we'd appreciate it. Often, particularly with mobile browsers, the behavior can vary quite a bit.

Thanks.

**Comment by msushanktheglitch** [comment]
Thank your for your response. I have observed this on all mobile browsers. I will share the demo link shortly. Meanwhile do you see any possible solution for the same.
