### ISSUE TITLE
How do I  set up the key file only one request? 

### ISSUE THREAD

**Issue by Bluebang** [videojs/video.js#5336]
The movie file is only used with a keyfile, how to set it to make it unnecessary to request TS files every time to request video.key file?

![qq 20180722172303](https://user-images.githubusercontent.com/22443960/43044165-f81fbc8a-8dd3-11e8-8951-c2fd27e4eb86.png)

This effect I want:
![qq 20180722173612](https://user-images.githubusercontent.com/22443960/43044269-bc8f8068-8dd5-11e8-8f8f-6d1f4d932600.png)

**Comment by gkatsev** [comment]
There's a PR in progress over here https://github.com/videojs/videojs-contrib-hls/pull/1433
