### ISSUE TITLE
Don't play video in Opera on Ubuntu 16.04 

### ISSUE THREAD

**Issue by IhorVimmi** [videojs/video.js#5337]
## Description
Problem with player on Ubuntu 16.04, Opera Browser

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open page with player in Opera on Ubuntu

## Results 
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
### 
Expected - Video should play

### Error output
code:4
message:"The media could not be loaded, either because the server or network failed or because the format is not supported."

#### videojs
"video.js": "^6.6.3",
#### browsers
Opera 54.0.2952.41
#### OSes
Ubuntu 16.04
### plugins
    "video.js": "^6.6.3",
    "videojs-contrib-ads": "^6.4.1",
    "videojs-contrib-hls": "^5.14.1",
    "videojs-hotkeys": "^0.2.21",
    "videojs-ima": "^1.5.1"

**Comment by IhorVimmi** [comment]
Working solution enable opera flag Negotiation with encrypted header extensions for SRTP in WebRTC

**Comment by IhorVimmi** [comment]
Fixed in Opera 54.0.2952.60

**Comment by gkatsev** [comment]
Sounds like this can be closed?
What type of content are you playing that you got this error?

**Comment by surikat1978** [comment]
Enable opera://flags/#dynamic-demuxer-selection.

And, if you want, set opera://flags/#autoplay-policy to "No user gesture required".
