### ISSUE TITLE
Leak of ResizeManager and event listeners in 7.0.5

### ISSUE THREAD

**Issue by davidstelter** [videojs/video.js#5339]
## Description
While troubleshooting a memory leak in our app which was using videojs 7.0.3, I came across an apparent memory leak resulting from some flaw in Player.dispose() or one of the components it deferred disposal duties to. I upgraded to 7.0.5 to see if the issue just got better and it did! But then there was a different leak. Using Chrome's heap snapshot comparison feature, I found that there were lots of "Detached EventListeners" piling up. Digging into the leaked objects I found a number of ResizeManager instances, which were coming from inside videojs. I was able to get it to stop just by supplying `resizeManager = false` in the options. We are properly calling `Player.dispose()` when we're finished with a player instance and then releasing our reference to it.

Our use case involves creating and disposing lots of (sometimes quite short) videos, so we might be a pretty good canary for this leak. I've seen it climb to around 1GB in a few hours!

Is there some additional cleanup required by the user when using the default ResizeManager on a Player that I'm just missing? Or should I create a reduced test case? 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Take a heap snapshot in Chrome
2. Create & dispose lots of players in a loop, leave it running for 10-100 cycles
3. Take another heap snapshot & compare
4. look for objects with deltas close to the number of disposed videos & find "Detached EventListeners"
5. Also note overall memory use climbing

### Expected
Dispose should clean up all resources allocated by a Player.

### Actual
Player.dispose() leaks ResizeManager objects possibly via EventListeners, or vice versa. Consumes a gradually ballooning amount of memory.

### Error output
Eventually Chrome will Aww, Snap as it does when memory is exhausted.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.0.5

#### browsers
Chrome (latest) at a minimum, but I expect others

#### OSes
Would expect all, observed on OS X

### plugins
No plugins

**Comment by gkatsev** [comment]
Theoretically, the user shouldn't need to do anything and video.js should take care of everything on dispose. The only requirement is that the elements shouldn't be removed from the DOM until Video.js is done disposing.

 A reduced test case would be great!

Also, if you find any other leaks, we'd be happy to take a look and work with you to fix them!

**Comment by gkatsev** [comment]
Also, would be good to look and see if the dispose method of the ResizeManager is working properly and whether things are getting unbound: https://github.com/videojs/video.js/blob/e63776862fcc7b4d659a4b67747c049da31b9d24/src/js/resize-manager.js#L98-L118

**Comment by davidstelter** [comment]
OK, pretty sure dispose is called before anything happens to the DOM on our side, I'll try to get a reduced test case together this week. Thanks!

**Comment by gkatsev** [comment]
@davidstelter it's possible we found out the source of the leak and it should be fixed in #5369. Should be out in our next release.
