### ISSUE TITLE
can not find source of http://videojs.com/advanced/

### ISSUE THREAD

**Issue by wowcut** [videojs/video.js#5345]
Sorry, but I can not find the source for http://videojs.com/advanced/.
There are at least two github.com urls on that page, but they go to https://github.com/videojs/video.js - n advanced.js anywhere to see. Is there a repo for this advanced player example?
Thanks!

**Comment by gkatsev** [comment]
We should probably link to it on the site but all the website code is on the website repo: https://github.com/videojs/videojs.com

html: https://github.com/videojs/videojs.com/tree/master/_harp/advanced
js: https://github.com/videojs/videojs.com/blob/master/_src-js/advanced.js

Hope that helps.
