### ISSUE TITLE
A gap appears underneath a player that takes up the entire page, such as in an iframe embed

### ISSUE THREAD

**Issue by DoomTay** [videojs/video.js#5351]
On a minimal example, this only comes up in Firefox, but in a real-world implementation, not only would it happen in Chrome as well, but on Chrome, the scrollbar would rapidly appear and disappear

[Here](https://github.com/videojs/video.js/files/2234111/embed.zip) is a minimal use case, along with a real-world example

**Comment by gkatsev** [comment]
So, a workaround for this is to add `scrolling="no"` to the iframe embeds.

In Chrome, locally, it actually works fine but I do see it in Firefox.

Investigating it, it seems like the progress-control is the one that causes this issue.

**Comment by gkatsev** [comment]
Looks like it's the time tooltip of the play progress bar that causes the overflow.

**Comment by gkatsev** [comment]
Seems like the fix is pretty easy to just change `position: relative` to `position: absolute` for the tooltips?
