### ISSUE TITLE
Advanced example down

### ISSUE THREAD

**Issue by Akxe** [videojs/video.js#5358]
## Description
See title

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. go to https://videojs.com/advanced/

### Expected
Example

### Actual
Nothing really?

### Error output
`Uncaught TypeError: Cannot read property 'dom' of undefined`

**Comment by gkatsev** [comment]
Thanks for pointing this out, we'll take a look. Could be related to forcing HTTPS recently.

**Comment by Akxe** [comment]
Not sure it is few days already, thought it would be reported by now... But 
at least it is now... 

---------- Původní zpráva ----------
Od: Gary Katsevman 
Datum: 1. 8. 2018 v 16:48:31
Předmět: Re: [videojs/video.js] Advanced example down (#5358)


Thanks for pointing this out, we'll take a look. Could be related to forcing
HTTPS recently.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/videojs/video.js/issues/5358#issuecomment-409601215), or
mute the thread

**Comment by gkatsev** [comment]
Thanks, should be fixed as soon as netlify deploys the updates.

Also, if possible, making these issues against the videojs.com repo would be preferable :)

**Comment by gkatsev** [comment]
Looks like it's live now.

**Comment by Akxe** [comment]
Sorry haven't thought about it, didn't even knew about page github, maybe we could write it into issue as a note?
