### ISSUE TITLE
Better way to initialise plugins

### ISSUE THREAD

**Issue by Akxe** [videojs/video.js#5360]
## Description
VideoJS should have better way to initialising plugin than `player.myPlugin(...options)`, this is a problem if you encounter TypeScript. 

### Actual
`player.myPlugin(...options)`, this is fine for JS but TS must cast player to any.

### New proposal
`player.usePlugin(name: string, ...options: any[]): any` find plugin by name and apply options.
`player.usePlugin(plugin: videojs.Plugin)` use plugin
`player.usePlugin<T, K>(name: string, (...options: T[]) => K, ...options: T[]): K` Create plugin with name and use it immediately.

1. Useful, as it will mitigate use on `(player as any).myPlugin(...options)`.
2. I personally never used this, but it might be useful to some.
3. Most convenient to single player scenarios as well as for TS since we have options in one function and therefor it can be strongly typed.

**Comment by gkatsev** [comment]
Why do you have to cast it to `any`? Is it because the typings for the player don't include plugin methods?

**Comment by Akxe** [comment]
Indeed player don't have it typed unless you extend the player by yourself... Also as I think about it, if some public variables, maybe `player.acces(name, property)` but that's an other thing...

**Comment by misteroneill** [comment]
Hmm, interesting. It would be nice if Video.js were easy to use with TypeScript.

I think the `usePlugin` idea has more potential for this specific use-case. I think something like this:

```js
player.usePlugin('foo', options);
```

is a nicer interface than this:

```js
player.access('foo')(options);
```

Though, I could see the latter generic property getter being a useful thing in some cases. Similar to `getattr` in Python, for example.

**Comment by Akxe** [comment]
That was exactly what it was meant to be, `player.acces(name, attr)`. I 
would love that, just keep in mind to edit type definitions too. And many 
thanks for your time on making it accessible to typescript 

---------- Původní zpráva ----------
Od: misteroneill 
Datum: 4. 8. 2018 v 18:57:39
Předmět: Re: [videojs/video.js] Better way to initialise plugins (#5360)


Hmm, interesting. It would be nice if Video.js were easy to use with 
TypeScript.

I think the usePlugin idea has more potential for this specific use-case. I 
think something like this:


<span>player</span>.<span>usePlugin</span>(<span><span>'</span>foo<span>'</span></span>, options);


is a nicer interface than this:


<span>player</span>.<span>access</span>(<span><span>'</span>foo<span>'</span></span>)(options);


Though, I could see the latter generic property getter being a useful thing 
in some cases. Similar to getattr in Python, for example.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/videojs/video.js/issues/5360#issuecomment-410462842), or
mute the thread

**Comment by misteroneill** [comment]
Another benefit of a `usePlugin` interface would be that we could dispense with the plugin-wrapping we do now in a future major version of Video.js.

**Comment by Akxe** [comment]
This is the old way, it is working and isn't even too bad. But you have to cast few types to

./plugin/example.ts
```ts
import videojs from 'video.js';

interface IinnerPlayer extends Iplayer {
	//	We need to tell TS that in this plugin, there is this part of player always accessible, since it is his own definition
	example: {
		doStuff(): void
	}
}

export function registerExample(player: IinnerPlayer, options: { someOptions: any }, globalOptions: IglobalOptions) {
	if (player.usingPlugin('uloztoExample')) { return }

	videojs.registerPlugin('uloztoExample', function({}: typeof options, {}: typeof globalOptions) {
		player.example = {
			doStuff() { console.log('stuff') }
		}
	} as any);
	(player as any).uloztoExample(options, globalOptions);
}
export const registerPlugin = registerExample;
```

./player.ts
```ts
import videojs from 'video.js';

interface Iplayer extends videojs.Player {
	example?: {
		doStuff(): void;
	};
	possiblyOtherPlugin?: any;
}

const player: Iplayer = videojs(videoElement, options);
const globalOptions = {
	initTime: new Date(),
}
import('./plugin/example.ts').then(({ registerPlugin }) => registerPlugin({}, globalOptions));
```

New proposal
```ts
import videojs from 'video.js';

export function registerExample(player: Iplayer, options: { someOptions: any }, globalOptions: IglobalOptions) {
	if (player.usingPlugin('uloztoExample')) { return }

	player.usePlugin('uloztoExample', function({}: typeof options, {}: typeof globalOptions) {
		player.expose('example', 'doStuff', function doStuff() {
			console.log('stuff');
		});
	}, options, globalOptions);
}
export const registerPlugin = registerExample;
```

and 
```ts
import videojs from 'video.js';

const player: videojs.Player<{
	example: {
		doStuff(): void
	},
	possiblyOtherPlugin: any;
}> = videojs(element, options);

const globalOptions = {
	initTime: new Date(),
}
import('./plugin/example.ts').then(({ registerPlugin }) => registerPlugin({}, globalOptions));
```

It is not perfect, open to suggestions.

**Comment by gkatsev** [comment]
So, I think that something like usePlugin is probably useful and helps TS but I'd be wary of adding things just for TS support. For example, I see little benefit to having an `.access` method on Video.js beyond easier typing in TS.

Also, I don't think that `usePlugin`, or whatever we want to call the method should allow you to register the plugin and then enable it. APIs that are overloaded like that often cause issues and confusion. It should probably be just the first option.

@Akxe would you be interested to get the ball rolling with a PR?

**Comment by Akxe** [comment]
But what we have agreed upon? :D I am confused... also, why is that register plugin returns something that when called with `.apply(player, options)` will enable the plugin but not register it as used. (`player.usingPlugin(‘name’) == false`)

**Comment by gkatsev** [comment]
I'm not quite sure I understand your question.

As for what to start working on, a method, that for now we'll call `usePlugin`. We can always change the new later up until release. `usePlugin` is basically equivalent to calling `player.myPlugin(...)` manually.

**Comment by Akxe** [comment]
I’ll get to it right tomorrow. Thanks! :)

**Comment by Akxe** [comment]
For the question I’ll make an playground or something tomorrow to demonstrate it.

**Comment by gkatsev** [comment]
That would be helpful!
