### ISSUE TITLE
Player.play() does not return promise

### ISSUE THREAD

**Issue by Akxe** [videojs/video.js#5362]
## Description
I seem not to get promise from `player.play()` method call.

## Steps to reproduce
1. Set up player
2. Call `player.play()`

### Expected
Promise as return value for supported browsers, undefined in others.

### Actual
Undefined only.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.2.0
#### browsers
Chrome, iOS (probably all that support Promise..., therefor all expect IE)
#### OSes
Probably all?

## A bit of background

`player.play()` does not work on iOS, if you get source to be played via http request or other asynchronous means. Therefor I need to intercept, if the play method succeeded, or failed. To my knowledge, all browsers that do prevent `player.play` also supports the promise from play method, therefor we should be able to intercept this and show some button to play the video.

**Comment by misteroneill** [comment]
The `Player#play()` method will currently only return a promise under a few conditions:

- The player/tech must be ready.
- The player must have a source.
- The player must not be changing sources.

We are currently undertaking some work to improve this situation, though, but hopefully that helps you understand the current situation.

**Comment by Akxe** [comment]
I did work around this using `player.el().querySelector('video').play()`... I suspect that it is due to having `player.src(data.streamPreviewUrl)` on previous line. It is somewhat inconvenient as  often those two go hand in hand, Maybe, you could pass the rejection, if it happened? It is usually due to safari bug.

**Comment by gkatsev** [comment]
I'm about to merge #5227 which should greatly improve returning `Promise` from `play()` in all cases. Following that, we're going to work on polyfilling the promise as necessary for browsers that don't return a promise from play like IE11.

**Comment by gkatsev** [comment]
#5227 has been merged and will be released in the next patch release. Going to close this in favor of #3927 to track work for IE11/browser that don't return a promise from `play()` work.
