### ISSUE TITLE
vjs-dimensions converting percentage in pixels

### ISSUE THREAD

**Issue by MatheusMoura17** [videojs/video.js#5364]
Adding a percentage value into `width` attribute in the `video` tag. Videojs is converting % into pixel.

Minimal example:
https://jsfiddle.net/7avfe0zm/5/

**Comment by gkatsev** [comment]
This used to work in Video.js 4 and older but it was removed in Video.js 5 and newer as it was a non-standard behavior and allowed us to simplify the code a bit. The `width` and `height` attributes on the video element expect a pixel value.
I guess our parsing currently ignores any symbols and treats the parsed value as the pixel value. We should potentially just use the default width (or match width to height via the aspect ratio) if the value is incorrect.

However, an interesting thing I found is that Chrome and Firefox are not spec compliant ([Dimension Attributes at the WHATWG spec](https://html.spec.whatwg.org/multipage/embedded-content-other.html#dimension-attributes) and [At the W3C version](https://www.w3.org/TR/html52/semantics-embedded-content.html#sec-dimension-attributes) and will parse the value as a percent. However, Safari does not and it will fallback to the default value for width (`300px`).

I would suggest using CSS to apply dimensions that aren't just pixel values.

**Comment by MatheusMoura17** [comment]
> I would suggest using CSS to apply dimensions that aren't just pixel values.

I thought about it, but I opened the issue to confirm, since some browsers support.

Tks @gkatsev!

**Comment by gkatsev** [comment]
You're welcome!

Did you have any thoughts on what our behavior should be when the value given isn't just a number?

**Comment by MatheusMoura17** [comment]
Considering the above specifications, the behavior is fine. 
Developers who have the same problem will find this issue.

**Comment by gkatsev** [comment]
Sounds good. Thanks for chiming in!
