### ISSUE TITLE
Incorrect zoom for VideoJS on Chrome seems to be an issue with object-fit

### ISSUE THREAD

**Issue by swaraasolutions** [videojs/video.js#5366]
## Description
The player has been generated using videojs-contrib-hls plugin however when viewing on chrome the player seems to be zoomed and the portion on right is not visible. But with the same code it is visible with IE Edge, Firefox and Safari correctly

## Sources
Not Sure

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Create a basic videojs player and check the view in chrome, firefox and Safari. Chrome will display it differently.
![chrome](https://user-images.githubusercontent.com/12116208/43915890-b36a8cb4-9c29-11e8-9d90-c64c2ccbac95.png)
![firefox](https://user-images.githubusercontent.com/12116208/43915896-b75338c6-9c29-11e8-9db7-1824628e52bd.png)
![ie](https://user-images.githubusercontent.com/12116208/43915903-bae9976e-9c29-11e8-9059-4c1e6acc6442.png)

### Expected
It should show the full video instead of zoomed version
![firefox](https://user-images.githubusercontent.com/12116208/43916001-f76c24cc-9c29-11e8-8c03-bba41c8dd83e.png)

### Error output
No Errors available

### videojs-contrib-hls version
what version of videojs-contrib-hls does this occur with?
    "videojs-contrib-hls": "^5.14.1",

### videojs version
what version of videojs does this occur with?
"video.js": "7.2.0",

### Browsers
what browsers are affected? please include browser and version for each
Chrome

### Platforms
what platforms are affected? please include operating system and version or device and version for each
Desktop + Mobile Windows 10

### Other Plugins
are any other videojs plugins being used on the page? If so, please list them with version below.
"videojs-contrib-ads": "^6.4.3",
"videojs-ima": "^1.5.1"

### Other JavaScript
are you using any other javascript libraries or frameworks on the page? if so please list them below.
jQuery

**Comment by alex-barstow** [comment]
Can you please create and share a reduced test case using this [template](http://jsbin.com/axedog/edit?html,output)? I am not seeing the same behavior with v7.2.0 out of the box. Providing a test page that you have verified reproduces the problem will help us better assist you.

**Comment by swaraasolutions** [comment]
Hi Alex,

 

Thanks for your quick response

 

Following are the versions that I have created

 

V6 = http://jsbin.com/lirogavoni/edit?html,output

V7 = http://jsbin.com/qihojaluho/edit?html,output

 

If you are unable to play the video please visit the below link as it manages session cookies for authentication

 

https://bit.ly/2vUIdjJ

 

The first in the list is the video that I am trying to play in VideoJS.

 

Let me know if you need any further details from my end.

 

Thanks

Varun V.

**Comment by alex-barstow** [comment]
Thank you. I was able to reproduce the issue. At first glance, it looks like the player's `padding-top` is being set differently in Chrome than other browsers when the `fluid` option is `true`. I'll look into it

**Comment by swaraasolutions** [comment]
Thanks Alex

 

Much appreciated. Any time frame when we can expect a resolution or maybe a patch that we can apply.

 

Thanks

Varun V>

**Comment by alex-barstow** [comment]
I don't expect it will take long to find the root cause of this, but I don't have an exact time frame. As a short (or long) term fix you can add the `vjs-16-9` class to the player which will force the 16x9 aspect ratio across every browser. I've confirmed that this works on my end.

**Comment by swaraasolutions** [comment]
Hi Alex,

 

Thanks for the response.

 

Is there any possibility I can add vjs-4-3 and will it be able to resolve the issue?

 

Thanks

Varun V.

**Comment by alex-barstow** [comment]
Yes, both `vjs-4-3` and `vjs-16-9` should ensure a consistent aspect ratio is used across browsers.

**Comment by gkatsev** [comment]
You can also pass in `aspectRatio` option with a value like `'16:9'` to get any aspect ratio. `vjs-4-3` and `vjs-16-9` are just so common that we provide the classes for them by default.

**Comment by swaraasolutions** [comment]
@alex-barstow I tried the solutions that you provided however when i try it on the vjs-7 jsbin that i shared it doesn't reflect the changes

[http://jsbin.com/renogawodi/edit?html,output](url)
@gkatsev i tried using your solutions too but that too didn't workout on the vjs7.

Your help is much appreciated.

Thanks
Varun

**Comment by alex-barstow** [comment]
Interesting, it works for me on that page. The aspect ratio changes accordingly when adding/removing `vjs-4-3` and `vjs-16-9`, and when setting the `aspectRatio` option.

**Comment by alex-barstow** [comment]
I have only tested with Chrome and Safari so I can only speak to the disparity there, but it looks like the root cause in that case is that the aspect ratio is falling back to the default 16:9 in Safari (instead of the correct 4:3) because the video's width and height are still 0 at the time the `loadedmetadata` event occurs (which is when the player attempts to calculate the video's dimensions). The player uses native HLS in Safari and MSE in Chrome, so that likely explains the different behavior. @gkatsev Do you know if HLS content's width and height are supposed to be available on 'loadedmetadata' in Safari?

**Comment by gkatsev** [comment]
Yeah, they should but I guess as always the answer is "it depends". It should have it but it's possible that there's a bug or something that's preventing it from working properly.

**Comment by alex-barstow** [comment]
Ah OK, after looking at the [spec](https://html.spec.whatwg.org/multipage/media.html#event-media-loadedmetadata), it is pretty explicit about the media's dimensions being available on `'loadedmetadata'`. I've tested various HLS content in Safari, and in all cases the dimensions are 0 on loadedmetadata, so this does appear to be a Safari bug.

**Comment by gkatsev** [comment]
@alex-barstow Is this all with Video.js have you tried a plain video element?

**Comment by alex-barstow** [comment]
Sorry, should have been more specific. I was testing in Safari with just the video element.

**Comment by gkatsev** [comment]
Interesting, do you get the info later on like on a `playing` event?

**Comment by alex-barstow** [comment]
Yes, the dimensions are available on `'loadeddata'`

**Comment by gkatsev** [comment]
We could make the case that if there's no dimensions in `loadedmetadata` we can wait till `loadeddata`, but we probably should also open an issue against safari for this as well.

Also, is this with m3u8 or also mp4?

**Comment by alex-barstow** [comment]
It's only an issue with HLS. I'll look into the feasibility of that workaround.

**Comment by alex-barstow** [comment]
Looks like it's a [known issue](https://bugs.webkit.org/show_bug.cgi?id=172223)

**Comment by swaraasolutions** [comment]
@alex-barstow @gkatsev thanks very much for all your help i have checked the known issue however the same functionality works on videojs 6 without issues. Also if it might help i am using google chrome version 68.0.3440.106.

I have reported a similar bug on videojs-contrib-hls but haven't received any response yet.

Thanks for all your help

**Comment by alex-barstow** [comment]
I am not seeing any difference in behavior between your v6 and v7 test pages in Chrome 68. Can you describe in detail the differences you are seeing?

**Comment by swaraasolutions** [comment]
Hi Alex,

 

V6 works fine and the issue with the video is not there however in v7 we are seeing this issue I have tried it on multiple google chromes.

 

Thanks

Varun V.

**Comment by swaraasolutions** [comment]
@alex-barstow @gkatsev i have finally found the issue.
When i disable Hardware Acceleration and it started working perfectly. How can i ensure that the hardware acceleration does not affect other users.

**Comment by misteroneill** [comment]
@donlaur Hardware acceleration in Chrome can be disabled via a toggle in Settings - "Use hardware acceleration when available".

**Comment by donlaur** [comment]
Yes, thank you.  I disabled Hardware acceleration in chrome.  That fixed the issue for my computer but isn't a great overall solution.  You can't use code or settings to turn off that setting, is there a way to suggest a certain ratio?  Use classes or some way to fix?  Do we know what calculation is being done in the hardware accelerator?

**Comment by kbinliu** [comment]
@misteroneill We have the same problem and hope to solve it as soon, thank you
