### ISSUE TITLE
Support Audio

### ISSUE THREAD

**Issue by heff** [videojs/video.js#537]
Video.js isn't meant to support audio yet, but there's been a number of requests for it, and we have progress on support for mp3s in the swf.

I'm creating this issue to consolidate and point to audio issues/requests.

#533 (Tom has made some progress in a branch)
#534

**Comment by gkatsev** [comment]
@mmcc I'm 100% ok with not supporting IE8 for the audio-player and then calling this done. Thoughts?

**Comment by mmcc** [comment]
Sounds good to me!



—

**Comment by gkatsev** [comment]
Closing as done. If someone PRs changes needed for flash/IE8 and the audio player, we'll accept it but unlikely to built it out ourselves.
