### ISSUE TITLE
this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by liuhaoliang** [videojs/video.js#5375]
Hi!This is an interesting [demo](https://github.com/liuhaoliang/videojsDemo/blob/master/%E7%9B%B4%E6%92%AD%E6%8B%96%E6%8B%BD.html).

I use the  latest html5 function dragable in my project which is combined with videojs, when drag the element,it doesn't work and says "this.el_.vjs_getProperty is not a function" in Chrome but it works well in Firefox.

The demo again https://github.com/liuhaoliang/videojsDemo/blob/master/%E7%9B%B4%E6%92%AD%E6%8B%96%E6%8B%BD.html

**Comment by alex-barstow** [comment]
Thank you. I can verify that I am seeing this error in Chrome but not Firefox. I'll check back in once I have had a chance to look into it.

**Comment by liuhaoliang** [comment]
Thank you！The demo is to exchange the videojs widges between the two containers.It works well in Firefox but has error in Chrome.Hope your well done work!

**Comment by hunkriyaz** [comment]
The issue is still, whenever anything updated in my component, it alway start to display the error on console.
