### ISSUE TITLE
Is there any function like set buffer at a certain time?

### ISSUE THREAD

**Issue by WaldenH** [videojs/video.js#5387]
## Description
As currentTime(time) does not work when video is paused, I have to put the set time at the callback of Play().
Is there any function to set buffer at a certain time? I guess it can improve user experience.

**Comment by alex-barstow** [comment]
Are you just trying to seek? `player.currentTime(newTime)` should seek even while the player is paused. Can you create a test page from [this template ](http://jsbin.com/axedog/edit?html,output) that demonstrates the problem so that we can better understand the issue you are encountering?

**Comment by Akxe** [comment]
Not that I know of, but! You could use an other video and seek it so that the part of video is cached.

**Comment by WaldenH** [comment]
Issue fixed, my coding error.
