### ISSUE TITLE
mpegdash playlist keeps downloading

### ISSUE THREAD

**Issue by slash197** [videojs/video.js#5388]
I have tried a few options to stop a live mpd stream and clear the player but none can stop the manifest file to download, it seems that even after reset/dispose or manually removing the html tag videojs keeps downloading the file over and over.

Anything I can do to stop this?

**Comment by alex-barstow** [comment]
Can you please provide a reduced test case using [this template](http://jsbin.com/axedog/edit?html,output) so that we can better assist you?
