### ISSUE TITLE
How to capture RTMP using video

### ISSUE THREAD

**Issue by AsuraZhu** [videojs/video.js#5391]
How to capture RTMP using video

**Comment by mister-ben** [comment]
Are you trying to _play_ an RTMP source? If you could give some more information, like an example of what you've tried, it would be easier to help.

**Comment by AsuraZhu** [comment]
@mister-ben  I use video. Js to play RTMP, so I cannot use canvas capture. So I want to know whether video. Js can take screenshots

**Comment by Akxe** [comment]
I don't think so, video.js (usually) uses `videoElement` and to my knowledge, it does not have a method for capturing current frame.

**Comment by mister-ben** [comment]
RTMP can only be played in Flash, and it's not possible to capture that as you would with an html5 canvas. Saving a frame would have to be done within the swf, but Video.js's swf does not support this.

**Comment by Akxe** [comment]
You basically you can, but it would mean that you need to tweak the flash library and add screenshot functionality, quite a bit harder, than you might like, but doable.

**Comment by misteroneill** [comment]
That's true, one could probably fork and customize [the Video.js SWF](https://github.com/videojs/video-js-swf) to achieve this, but to the point of the original question, the Video.js SWF does not support this and the Video.js organization is not actively maintaining our Flash implementations.
