### ISSUE TITLE
Documentation about css classes

### ISSUE THREAD

**Issue by Surt** [videojs/video.js#5392]
## Description
There is many css classes to control the video proportions, with height, etc but there is no documentation on them. Internet is full of questions about how to make them, but there is no official information anywhere.

Please someone with knowledge about this css classes ``` embed-responsive embed-responsive-4by3 vjs-fill vjs-fluid``` please create a documentation somwhere.

**Comment by mister-ben** [comment]
You're right, this could be better documented. Here for now:

* `.vjs-fill` Width 100% and height 100% of parent
* `.vjs-fluid` Width 100%, height determined by aspect ratio of the video once known. Defaults to 16:9
* `.vjs-16-9` Width 100% and 16:9 aspect ratio
* `.vjs-4-3` Width 100% and 4:3 aspect ratio

`embed-responsive`, `embed-responsive-4by3` etc belong to Bootstrap, and can be used if you use that https://getbootstrap.com/docs/4.1/utilities/embed/

**Comment by alex-barstow** [comment]
This [blog post](https://blog.videojs.com/video-js-5-s-fluid-mode-and-playlist-picker/) also gives a quick walkthrough of `vjs-fluid`, `vjs-16-9`, and `vjs-4-3`

**Comment by Surt** [comment]
Thanks a lot!

**Comment by misteroneill** [comment]
We don't accept donations, but we would deeply appreciate any help in documenting things!
