### ISSUE TITLE
404 on website link

### ISSUE THREAD

**Issue by japo32** [videojs/video.js#5394]
The GET STARTED link on your website leads to a 404.

https://github.com/videojs/video.js/blob/stable/docs/guides/setup.md

Apologies if this is the wrong avenue for submitting this bug.

**Comment by alex-barstow** [comment]
That link is out of date. You can find the current "Getting Started" guide [here](https://docs.videojs.com/#getting-started). May I ask where on our website you found that link?

**Comment by japo32** [comment]
Right there in the main menu
http://www2.videojs.com/

**Comment by gkatsev** [comment]
That's an incredibly old version of the website. Our main website is https://videojs.com/.
Can I ask how you got to the www2 version of the site? Kind of still surprised it's still live, actually.

**Comment by japo32** [comment]
Haha, yeah I thought as much when I found the newer website.

It was the third hit when I googled 'js video player with playlist'. :)

**Comment by gkatsev** [comment]
Heh, I just tried the same search and definitely not getting it but my data is probably tainted by videojs and video related stuff already.

Unfortunately, I don't think I have a good answer for a fix for this other than maybe turning it off and directing you to the latest page https://videojs.com/getting-started/

Thanks and sorry 🙂

**Comment by japo32** [comment]
No worries guys. maybe a redirect from the www2 website to the newer one? 👍  Cheers
