### ISSUE TITLE
can't play m3u8 on IE 11

### ISSUE THREAD

**Issue by goforwork** [videojs/video.js#5395]
error:
![image](https://user-images.githubusercontent.com/28641986/44507823-92c2f180-a6de-11e8-84aa-fcafb496d778.png)

example:(notice: these code from examples.i just change the video source)
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Video.js | HTML5 Video Player</title>
    <link href="http://vjs.zencdn.net/7.0/video-js.min.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/7.0/video.min.js"></script>

</head>
<body>

  <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640" height="264" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
    <source src="http://vdbo.koo6.cn/Videofile/HMAVZLO1/xdd/etts_001/index.m3u8" type="application/x-mpegURL">
    <track kind="captions" src="../shared/example-captions.vtt" srclang="en" label="English">
    <track kind="subtitles" src="../shared/example-captions.vtt" srclang="en" label="English">
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>

</body>

</html>

**Comment by mister-ben** [comment]
Is it IE11 on Windows 7? If so, that browser lacks Media Source Extensions so Flash is unfortunately needed for HLS playback.

You can use videojs-flash and videojs-flashls-source-handler for HLS support via Flash on IE11/Win7. See https://github.com/brightcove/videojs-flashls-source-handler/blob/master/README.md

**Comment by goforwork** [comment]
@mister-ben thank you very much. the method you provide solved the problem perfectly!
