### ISSUE TITLE
don't autoplay sometimes in Chrome.

### ISSUE THREAD

**Issue by goforwork** [videojs/video.js#5398]
problem : don't autoplay sometimes in Chrome.

console : Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

**Comment by mister-ben** [comment]
[Chrome changed its autoplay policies a few months ago](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes). We've a good writeup here, but in short autoplay won't always work on all browsers: https://blog.videojs.com/autoplay-best-practices-with-video-js/

Often a video can autoplay if muted. We've recently added an option to Video.js to try to play the video with sound, and then try to play it muted if that's not allowed. See the `'any'` option described here:  
https://blog.videojs.com/video-js-7-1-and-6-11-autoplay-and-fullscreen-changes/

**Comment by misteroneill** [comment]
As @mister-ben indicated, there isn't anything to be done here.
