### ISSUE TITLE
window.videojs is undefined in React component

### ISSUE THREAD

**Issue by WaldenH** [videojs/video.js#5401]
## Description
To decrease the bundle size, I use cdn to include videojs.
But in react component, the window.videojs is undefined, window does not contain videojs.
In chrome dev-tool connection, video.js file is loaded.
Does I use something wrong?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. use videojs example case
2. in react component, call window.videojs to initialize video

### Expected
window.videojs successfull

### Actual
Please describe what actually happened.

### Error output
window.videojs is undefined in component

#### videojs
7.1.0
#### browsers
chrome 68.0.3440.106
#### OSes
Mac
### plugins
Webpack, react

**Comment by misteroneill** [comment]
Is `window.videojs` available in the browser console?

**Comment by himalreddy** [comment]
I am facing same issue, any help.
window.videojs is exists in console.
