### ISSUE TITLE
Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

### ISSUE THREAD

**Issue by Yijx** [videojs/video.js#5408]
## Description
When I play a very big m3u8 4K Video, it can play a few seconds and videojs tell me
 **'Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.'.**
It maybe a piece of ts is bigger than cache.I search this queation in videojs/videojs-contrib-hls,I know official is solving this queation but I am so anxious.Can I change source code to remove the cache limit? or Can I use some API to change it? I am not good at English,I hope some good man Can help me.Thanks!

## Additional Information
https://v2.gaiamount.com/works/player/28 (or other video in this website)
#### videojs
video.core.min.js 7.22
#### browsers
Chrome 68
### plugins
videojs-contrib-hls.js 5.14.1
videojs-contrib-dash 2.10.0

**Comment by gkatsev** [comment]
We're currently working on 4K support in this PR https://github.com/videojs/videojs-contrib-hls/pull/1416. However, it's quite complicated and may take some time still to get merged in.

**Comment by gkatsev** [comment]
Please follow that PR for updates on the status of this issue.

**Comment by ttshivers** [comment]
Any update on this issue as your PR was never merged?

**Comment by gkatsev** [comment]
We've done a lot of other work in background in VHS master that will help, once we're confident that we can switch to that branch 4K support is next on our agenda.
