### ISSUE TITLE
keep consistent video ID regardless the method executed

### ISSUE THREAD

**Issue by alecsgone** [videojs/video.js#5411]
## Description
The ID of the video instance changes after `reset()`, is a small change but it should be consistent. 
https://jsbin.com/fisoyabuve/edit?html,console,output

## Steps to reproduce
1. Go to the js bin from the description
2. Open the console
3. hit play and wait for 5s

### Expected
if not the inial class of the video tag a consistent all lowercase id

### Actual
it Capitalizes the previously lowercase `tech`

### plugins none
![screen shot 2018-09-05 at 9 42 33 am](https://user-images.githubusercontent.com/1099589/45102152-a31d9800-b0f2-11e8-9c76-7e42ff2f9544.png)
![screen shot 2018-09-05 at 9 54 39 am](https://user-images.githubusercontent.com/1099589/45102160-a6b11f00-b0f2-11e8-9869-efc10d325318.png)

**Comment by alecsgone** [comment]
I narrowed down to https://github.com/videojs/video.js/blob/master/src/js/player.js#L948 and I'll be happy to create a PR I just need confirmation to: changing this line is the way to go?

**Comment by alex-barstow** [comment]
Hm, I believe they should be the same, although @gkatsev will need to chime in on this one. If they are supposed to match, the fix will depend on whether it should be uppercase or lowercase. If it should be lowercase, the fix will be changing `titleTechName` to `camelTechName ` in the line you linked above. If it should be uppercase, the fix will be updating the string here: https://github.com/videojs/video.js/blob/master/src/js/player.js#L623

**Comment by misteroneill** [comment]
Looks like line 623 is older, so it should be considered correct - so, lower-case. Really, I think line 948 should be using `${camelTechName}` as @alex-barstow said and 623 should be using `${camelTechName}_api`.

Ideally, these would be unified into a single function - maybe a static method on the `Tech` class - so we don't encounter this sort of issue again.

@alecsgone A PR would be very welcome here! 😄

**Comment by gkatsev** [comment]
Yeah, it should be `camelTechName`. Technically, we already potentially broke people when we made that change to line 948. Given that this is internal, I'm ok with making that change and if it breaks anyone, we can revert and patch.
I'm not sure that a helper method would've helped here given that we have two separate usages for tech names.
