### ISSUE TITLE
iOS Touch Event Issue

### ISSUE THREAD

**Issue by iq-dot** [videojs/video.js#5412]
## Description
I have an issue that is driving me nuts and would appreciate the help.

We use videoJS 5 and have integrated SpotX (for ad serving), when an ad plays, there is an iframe that sort of overlays and handles click/touch events so that it takes you to the advertisers page.

On my test page, this behaviour works on Desktop (Chrome and Safari) and Android mobile but not on iOS.

I don't know if the issue is with iOS specifically or any special behaviour within VideoJS that prevents this from happening.

The reason I am not eliminating videoJS completely is because if the ad is loaded in a separate HTML5 video element (not videoJS managed) then it works (the click behaviour on the video).

Please help with any insights. I have linked out test page below.

## Steps to reproduce
1. Go to https://build.suggestv.io/test/index.html
2. When viewed on Desktop it will auto-play and on Android you need to click the video
3. An ad with an orange background for SpotX will appear, click on the video and should take you to the spotx site (iOS not working)

### Expected
Clicking on the video should take you to the Spotx site.

### Actual
Does not work on iOS, seems like the touch events are being ignored or eaten up by something else.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
VideoJS 5
#### browsers
what browser are affected?
iOS Safari, iOS Chrome
#### OSes
what platforms (operating systems and devices) are affected?
iOS
### plugins
videojs playlist
videojs overlay

**Comment by gkatsev** [comment]
What version of iOS are you testing with? Also, would you be able to try with a newer version of Video.js?
I think Video.js 5, I believe, used the native controls on iOS, particularly iphones and older versions of iOS (and maybe newer ones still do?) disallowed elements from receiving clicks when overlayed on top of the video element when native controls were used.
I think there's an option `nativeControlsForTouch` that you can set to false to use custom controls which may improve things.

**Comment by iq-dot** [comment]
Thanks for your quick response, I am testing on iOS version 10 to 11.3, all have the problem.

What I will try however is the nativeControlsForTouch option and see if that helps.

Upgrading videoJS is definitely something I want to do but may not be quick to do right now, if the nativeControls option fails me then I will see if I can quickly hack something up with a newer version of videoJS to see if the issue goes away.

**Comment by gkatsev** [comment]
It's actually not autoplaying for me in chrome but does work after I click play.
Unfortunately, I don't have an iOS device handy on me but can probably take a look next week.

**Comment by iq-dot** [comment]
If you do take a look next week, can you please use this url now: 

https://build.suggestv.io/test/iqbal.html

The previous URL has now changed.

Thanks
