### ISSUE TITLE
videojs() does not work on same <video> id twice when destroying and recreating the player

### ISSUE THREAD

**Issue by CorruptMonkey** [videojs/video.js#5423]
## Description
videojs() does not work on same <video> id twice when destroying and recreating the player

An example of where this isn't working is here: https://lasershark.army/aeon/notice/2377854#post-2377854

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Create media player with jquery html() function on element.
2. Run videojs() on the new element. This will work as intended at this point.
3. Destroy the <video> and recreate it again with the same id
4. Run videojs on the <video> again and it will not convert the player to the videojs player.

### Expected
The player should appear as the videojs player

### Actual
The player appears as the default html5 player

### Error output
No errors

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.1.2
#### browsers
Firefox, Chrome
#### OSes
Linux, Windows
### plugins
No plugins

**Comment by mister-ben** [comment]
Make sure to dispose of the player with `dispose()` rather than just removing the player element from the DOM.

**Comment by CorruptMonkey** [comment]
`ReferenceError: dispose is not defined`.

**Comment by gkatsev** [comment]
Can't get to the example but `dispose()` is a method on the player.
So, you want to do something like:
```js
player.dispose()`
```
Before removing things from the DOM and creating the player.

**Comment by CorruptMonkey** [comment]
That works. Thanks :)

**Comment by gkatsev** [comment]
You're welcome!
