### ISSUE TITLE
How to get video metadata infomation?

### ISSUE THREAD

**Issue by victoryboss** [videojs/video.js#5424]
## Description
I want to get video metadata infomation like audiocodecid、fps、displayHeight,etc.
but I can not find any APIs in the website (https://docs.videojs.com ).
Can you help me ？
Best wishes to all of  contributors

### Expected
Give some APIs to get video infomation like：
audiodatarate:128,
audiosamplerate:44100,
videodatarate:1200,
audiocodecid:10,
videocodecid:7
LiveServer:"CloudLeopard/1.3.6.2",
displayHeight:720,
displayWidth:1280,
Server:"jcloud-live/1.0.1",
framerate:25,
fps:25,
bandwidth:200kb/s

**Comment by gkatsev** [comment]
Unfortunately, not all metadata is available in the browser without download the media manually and inspecting it directly. In act, I think the only real thing that's available are the intrinsic height and width of the video.
You can get these via `player.videoHeight()` and `player.videoWidth()`.
Most of the other info needs to be provided out of band.

**Comment by victoryboss** [comment]
Thank you for your answer.
Best wished to you!

**Comment by cuiD2488** [comment]
这个问题解决了吗？有什么其他的办法可以获得吗？我也遇到了同样的问题，跟您请教一下
