### ISSUE TITLE
the entry for native video? I want to know how to prevent vjs request files only using vjs for stylesheet of playback

### ISSUE THREAD

**Issue by ENGLISH-LIGHT** [videojs/video.js#5425]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
Edge,the newest

**Comment by misteroneill** [comment]
I'm not sure I understand what you're trying to say. Can you provide an example or reduced test case, following the issue template?
