### ISSUE TITLE
deregisterPlugin function not exposed?

### ISSUE THREAD

**Issue by Pawes** [videojs/video.js#5430]
## Description
I can't seem to deregister a plugin, and I can't find any documentation on it.
I thought it was supposed to be exposed from the videojs object as the registerPlugin() function is.
But when I try to call videojs.deregisterPlugin() I am told that it is not a function. 
Maybe it is a misunderstanding on my part, but either way it would be nice to have it documented maybe in here : https://github.com/videojs/Video.js/blob/master/docs/guides/plugins.md

## Steps to reproduce
It can be tested by trying to call 
videojs.deregisterPlugin("playlist")

On the advanced example page:
https://videojs.com/advanced/

### Expected
I expected it to deregister the plugin.

### Actual
It says in the console that deregisterPlugin is not a function

#### videojs
6.6.3
#### browsers
Chrome, Firefox
#### OSes
Windows 7
### plugins
mux, playlist, playlistui

**Comment by Pawes** [comment]
Btw, the version of videojs reflects what is used on videojs's advanced page I use 7.1.0 and get the same result.

**Comment by gkatsev** [comment]
It was exposed in Video.js 7.2 and 6.12.

**Comment by gkatsev** [comment]
Apparently, 7.2 was never promoted to latest. Probably time to do that.

**Comment by gkatsev** [comment]
Just promoted 7.2.2 to latest.

**Comment by gkatsev** [comment]
Also, looks like the Video.js url that the advanced page uses hasn't been updated in a while.

**Comment by gkatsev** [comment]
I just updated the website to load the latest version of Video.js it can from unpkg.com. It currently still thinks that it's 7.1.0, but it should hopefully get updated to 7.2.2 soon.

Hope the above helped.

**Comment by Pawes** [comment]
Thanks a lot, everything works now!

**Comment by gkatsev** [comment]
You're welcome!
