### ISSUE TITLE
Looking for more extensive HLS error reporting

### ISSUE THREAD

**Issue by webcast33** [videojs/video.js#5435]
I am attempting to playback live streams with video.js 7 and the built-in VHS plugin. All works fine, but when the stream ends, the "ended" player event doesn't fire. Eventually, 404 errors start to show on the console because the manifest is deleted, but nothing propagates to the player and the "error" event.

Is there some way to get greater granularity of what is happening in the hls engine? The "hls.js" client, for example, returns significant events like "buffer stalled" and "level load" errors. These message help assess the health of the live stream and can also be used to determine if the stream has ended. It would be great if there was a way to get this level of detail from VHS.

I know I can use video.js 7 with another plugin that loads the hls.js client. But the one that also exposes hls.js events - https://github.com/Peer5/videojs-contrib-hls.js - uses a very old version of hls.js and appears to be currently unmonitored.

Thank you.

**Comment by forbesjo** [comment]
Your stream may not be appending an endlist tag when the stream ends, do you know if this tag is showing up when you end your live stream? If the tag does appear then perhaps this is related to https://github.com/videojs/videojs-contrib-hls/pull/1425

**Comment by webcast33** [comment]
Thank you for your comment. Indeed, the "Problem encountered with the current HLS playlist. Trying again since it is the final playlist." message does appear on the console along with 404/504 errors after the manifest is deleted. It doesn't appear that our stream has an "endlist" tag, but that is a function of our encoders and CDN and is, I believe, out of our control.

With HLS streaming, there is always an issue in determining if the live stream has stopped or is just stalled (perhaps because of a network error).

Being able to detect occurrences like the deleted manifest would help our application determine what action to take. But unfortunately, I can't seem to find a way to get such event information from VHS.

Thank you.

**Comment by webcast33** [comment]
Hello. Still looking for a way to detect the end of a live HLS stream. I noticed there are VHS "usage events" that could convey the information that the manifest is no longer being updated and eventually disappears (resulting in xhr 404/504 errors). But I can't get any of these events to fire. Is it possible that I'm not using them correctly? Here is a section of my code:

    video.ready(function() {
      var player = this;
      player.tech().hls.on('hls-unknown-waiting', function() {
        console.log('hls-unknown-waiting');
      });
      player.tech().hls.on('hls-live-resync', function() {
        console.log('hls-live-resync');
      });
      player.on('hls-error-reload-initialized', function() {
        console.log('hls-error-reload-initialized');
      });
      player.on('hls-error-reload', function() {
        console.log('hls-error-reload');
      });
    });

**Comment by micktaiwan** [comment]
_But I can't get any of these events to fire_

Same here. Someone knows how to catch 404 from HLS ?

**Comment by webcast33** [comment]
The VHS (videojs-http-streaming) plugin has an undocumented event called "retryplaylist" that seems to correspond to 404/504 responses received once the live stream manifest has been deleted. Attach the event to the HLS tech, as follows:

```
      player.tech_.on('retryplaylist', () => {
        console.log('retryplaylist');
         (and do something)
      });

```

**Comment by meikidd** [comment]
> Hello. Still looking for a way to detect the end of a live HLS stream. I noticed there are VHS "usage events" that could convey the information that the manifest is no longer being updated and eventually disappears (resulting in xhr 404/504 errors). But I can't get any of these events to fire. Is it possible that I'm not using them correctly? Here is a section of my code:
> 
> ```
> video.ready(function() {
>   var player = this;
>   player.tech().hls.on('hls-unknown-waiting', function() {
>     console.log('hls-unknown-waiting');
>   });
>   player.tech().hls.on('hls-live-resync', function() {
>     console.log('hls-live-resync');
>   });
>   player.on('hls-error-reload-initialized', function() {
>     console.log('hls-error-reload-initialized');
>   });
>   player.on('hls-error-reload', function() {
>     console.log('hls-error-reload');
>   });
> });
> ```

"usage event" listener should look like this:

```
video.ready(function() {
  var player = this;
  player.tech().hls.on('usage', event => {
    if (event.name === 'hls-live-resync') {
      console.log('hls-live-resync');
    }
  });
});
```

**Comment by hethcox** [comment]
NB: My 3rd-party component was adding its own callbacks after my ready state code so my 'retryplaylist' callback was getting deleted. By adding my callback in the player ready callback I was able to get 'retryplaylist' to work.
