### ISSUE TITLE
7.2.0 to 7.2.2 playback does not restart after ended

### ISSUE THREAD

**Issue by Everlag** [videojs/video.js#5436]
## Description
Video fails to play after its reaches the end. This also breaks looping.

Repro(Note the version pulled in from cdnjs):
http://jsbin.com/repipayogu/1/edit?html,output

## Steps to reproduce
1. Let video end(seeking to near end is fine); play button should change to replay
1. Press play

### Expected
Video plays again

### Actual
Video fails to play; loading spinner spins continuously
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Seeking to the start with or without invoking play successfully restarts playback.

7.2.0 to 7.2.2 changes the http-streaming version from 1.1.0 to 1.2.4

#### videojs
7.2.2 fails to play

7.2.0 does not fail to play
- http://jsbin.com/puseyajuto/1/edit?html,output

7.1.0 does not fail to play
- http://jsbin.com/zovosuzenu/edit?html,output

#### browsers
Chrome; others may be affected

#### OSes
Windows, OSX, and Linux

### plugins
http-streaming(videojs 7 builtin)

**Comment by bcdarius** [comment]
This [issue](https://github.com/videojs/http-streaming/pull/204) was fixed in @videojs/http-streaming v1.2.5  (v7.2.2 is still on v1.2.4). VHS version containing a fix, I believe, will be upgraded in the upcoming VideoJS release.

**Comment by Everlag** [comment]
Looping still seems to be broken. Manually invoking play is solved by the latest release but we still see the spinner blocking at the end.

Want me to open a new issue for this?

Repro
http://jsbin.com/kamavaduru/1/edit?html,output

**Comment by gkatsev** [comment]
@Everlag can you open one against the [videojs/http-streaming repo](https://github.com/videojs/http-streaming/issues/new)? Thanks!

**Comment by Everlag** [comment]
Will do
