### ISSUE TITLE
Fluid layout for 5:4 aspect ratio

### ISSUE THREAD

**Issue by marcusfrenkel** [videojs/video.js#5440]
I kindly request the developers to add support for 5:4 aspect ratio in the fluid layout style. This is needed for resolution of 720x576 (PAL DVD).

**Comment by misteroneill** [comment]
Thanks for the idea @marcusfrenkel! If you'd like to take a stab at it, you'd be welcome to open a PR and we'd appreciate it. I suspect what you're looking for is a pre-defined `vjs-5-4` class name, which could easily be added in `css/components/_layout.scss`.

In the meantime, those wanting this feature can call `player.aspectRatio('5:4')` and it should have the same effect.

**Comment by gkatsev** [comment]
I don't think we want a new default class. You can configure the player via an `aspectRatio` option or by calling the method. If that isn't sufficient, we can see whether we need default classes for it.

**Comment by marcusfrenkel** [comment]
The `aspectRatio` is sufficient. Thanks!

**Comment by gkatsev** [comment]
You're welcome!

Going to close this issue in that case. Let us know if you have any questions about it.
