### ISSUE TITLE
googlevideo.com issues with HTTPS redirect in firefox

### ISSUE THREAD

**Issue by T4eus** [videojs/video.js#5442]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.using Ublock origin at firefox
2.go to https://invidio.us/
3.try to watch some videoes

## Results
some videos don't work properly using ublock origin, at least with the "disable pre-fetch" checked

### Expected
as the "disable pre-fetch" is a default setting, I expect to work with it, but on https://invidio.us/ some videos don't work with this option

### Actual
Please describe what actually happened.

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
Firefox
#### OSes
Windows 10
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by T4eus** [comment]
![image](https://user-images.githubusercontent.com/43221359/45848931-3dd6c300-bcfe-11e8-9957-c90b14eb0484.png)
https://invidio.us/watch?v=z04XOX_XVJA
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." } video.min.js:1:30651
	Ze https://invidio.us/js/video.min.js:1:30651
	Ge.error https://invidio.us/js/video.min.js:1:31392
	Fo</e.prototype.error https://invidio.us/js/video.min.js:6:31825
	Fo</e.prototype.handleTechError_ https://invidio.us/js/video.min.js:6:22119
	n https://invidio.us/js/video.min.js:2:2073
	n https://invidio.us/js/video.min.js:2:2073
	X/n.dispatcher https://invidio.us/js/video.min.js:1:7127
`

and also
https://invidio.us/watch?v=_Fxil2QY0wE
https://invidio.us/watch?v=IJwFhK-UsM0
https://invidio.us/watch?v=HKp-r0eTK9U

**Comment by T4eus** [comment]
Mozilla Firefox 62.0 64-bits
Windows 10 1803 64-bits
Ublock Origin 1.16.20

**Comment by T4eus** [comment]
all works before unckeck "disable prefetch"
exept this one, maybe another error
https://invidio.us/watch?v=_Fxil2QY0wE

**Comment by gkatsev** [comment]
All those worked for me, though, I am on macOS. Also, it seems like these all loaded mp4s for me. Is it loading HLS for you?

**Comment by gkatsev** [comment]
I'll try and check it out on a win10 machine.

**Comment by gkatsev** [comment]
Just tried on a win10 machine and still couldn't reproduce, unfortunately.

**Comment by T4eus** [comment]
I will investigate more, maybe is something related just to me

**Comment by gkatsev** [comment]
Maybe another extension as well? Try disabling all other extensions.

Let us know.

**Comment by T4eus** [comment]
https://github.com/omarroth/invidious/issues/161#issuecomment-423756026
![image](https://user-images.githubusercontent.com/43221359/45952773-17eb4000-bfd6-11e8-9de1-5dfaadbafdae.png)

**Comment by mister-ben** [comment]
I tried thottling bandwidth and it made no difference for me: some videos load, others do not. The ones that do not are simply 403 responses, likely because the You Tube CDN URLs they are scraping expire.

**Comment by gkatsev** [comment]
Based on https://github.com/omarroth/invidious/issues/161#issuecomment-424006846, it's possible that this is a googlevideo redirect issue and not something we can do anything about

**Comment by T4eus** [comment]
but if I use firefox default player, I don't get the error.
if I open the video source on other tab and wait the redirect, I can reload the invidio.us page and it will work.

this problem don't occurs on chrome, all videos plays well.

this fail specifically on the videojs player at firefox,
if get the redirect on external tab, and retry videojs player, it works.
