### ISSUE TITLE
Binding click events to container/video does not work while playing (GC)

### ISSUE THREAD

**Issue by koosvanderkolk** [videojs/video.js#545]
Using the latest version of the code, in Google Chrome.

``` javascript
videojs(video_element).ready(function(){
  videojs_player = this;
  videojs_player.play();
  $video_container = $video_element.parent();

  $video_container.bind('click', function(event){
    //does not fire in GC
  });
});
```

http://jsbin.com/ijigac/1/

**Comment by pingram** [comment]
@gkatsev do you know if the behavior has changed with respect to listening to 'tap' events? I have the same business case as GFoley83 and wasn't able to get the touch events to work

**Comment by gkatsev** [comment]
I haven't tested this on iphones in recent versions but it probably still behaves in the same manner.
