### ISSUE TITLE
The size of the video player determines the HLS video quality

### ISSUE THREAD

**Issue by jwoertink** [videojs/video.js#5451]
## Description
HLS video quality should be determined by how fast your internet is, but it seems the latest version (7.2.0) uses the size of the video window to determine the HLS quality. If the video window is small, then a 420p video will play. Resizing the window to full screen on a large monitor, then 1080p will play. 

## Steps to reproduce
1. Visit https://jsbin.com/cucakeyilo/edit?html,output
2. Open your browser tools debug inspector
3. View the response from the hls_playlist.m3u8 file, and look for the bandwidth option for the 1080p video. At the time of this writing, mine was `18724800`. 
4. Update the `bandwidth` option to this number
5. Enlarge your dev tools (must be attached), and use the built-in slider to shrink the video size. (I'm using roughly 800x450)
6. Play the video, and watch the network tab of your dev tools. You'll see the 420p video play even though the 1080p video bandwidth was specified. 
7. Scale out your video player as large as you can make it, and see that the 1080p video loads.

## Results
I expected to always see the 1080p load no matter the size of the video window. In the case of really powerful phones on wifi, they should see 1080p and not the 420 just because their window size is small.

I also expect that the quality, when no bandwidth is specified, to be determined by the speed of the network connection, and not by the size of the video.

### Actual
Smaller screens show lower quality video, and larger screens show higher quality video.

### Error output
The only relevant warning from the above link was
> VIDEOJS: WARN: Problem encountered with the current HLS playlist. Aborted early because there isn't enough bandwidth to complete the request without rebuffering. Switching to another playlist.

## Additional Information

Videojs - 7.2.0
MacOS - 10.13.6
Firefox - 62.0.2
Chrome - 69.0.3497.100

**Comment by gkatsev** [comment]
This is actually our expected behavior. We restrict the renditions to player size + 1 as outlined in this document https://github.com/videojs/http-streaming/blob/master/docs/bitrate-switching.md

There's actually a feature request and PR ongoing to ignore the player size: https://github.com/videojs/http-streaming/pull/238

**Comment by jwoertink** [comment]
oh sweet. Ok, that PR sounds like exactly what I need. Thanks for the doc as well. I was digging around and wasn't sure what to call this feature to see if there was already a config or docs.

**Comment by gkatsev** [comment]
You're welcome. Going to close this issue then, if you can follow along with the PR.
