### ISSUE TITLE
Must have a visible size larger than 400 x 300 pixels

### ISSUE THREAD

**Issue by liuhaoliang** [videojs/video.js#5455]
I use "videojs-flash" and this library to play rtmp video.But when the video size is smaller than 400 x 300,the autopaly property will not work.the video will blocked and I have to play it manully.How can I fix it?It is the console log bellow .

 Cross-origin plugin content from <URL> must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.

<img width="1154" alt="2018-09-28 3 15 10" src="https://user-images.githubusercontent.com/16020037/46193607-5dd73980-c331-11e8-9102-11234e1483e1.png">

**Comment by mister-ben** [comment]
Try hosting the swf on your own domain, so it is not cross origin content. You can set that globally with `videojs.options.flash.swf = 'path/to/video-js.swf'`

**Comment by gkatsev** [comment]
Yeah, unfortunately browsers are putting restrictions on flash and there's not much we can do. @mister-ben's suggestion is definitely worth trying but I'm not sure there is anything else to try. I would also recommend moving off of flash if you can.
