### ISSUE TITLE
VideoJS causes Cordova mobile app to crash

### ISSUE THREAD

**Issue by weiz18** [videojs/video.js#5457]
## Description
When playing video in Cordova app[IOS], the app crashes.

## Steps to reproduce
1. Build a production version of Cordova app for IOS using ionic
2. Play video

### Expected
Plays video successfully

### Actual
App crashed.

### Error output
[LayoutConstraints] Unable to simultaneously satisfy constraints.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
v7.2.3
#### OSes
Across all IOS devices

**Comment by gkatsev** [comment]
Do you have any more details about this? Are there any specific errors being logged? Does the app work without Video.js? Can it play with just a native video tag? Can you provide a sample project that shows this problem?
We've never really dealt with cordova, so, you'll have to bear with us.
