### ISSUE TITLE
VHS DASH playback errors when trying to play an audio only manifest

### ISSUE THREAD

**Issue by webrolls** [videojs/video.js#5460]
## Description

I am trying to play simple dash stream, I can only see videojs shows some spinner but I don't see stream playing.

## Steps to reproduce

const playDashVideoJsOptions = {
  autoplay: false,
  controls: true,
  sources: [{
    src: 'https://pmqa.on24.com/media/news/corporatevideo/events/11/15/56/57/rt/50247373_mpd/stream.mpd',
    type: 'application/dash+xml'
  }]
}

I have a sample dash stream links which I am trying to play in videojs player

### Expected
dash stream should be working fine and we should see stream playing in media player

### Actual
I am getting following javascript error in chrome browser console.

### Error output
index.js:2178 VIDEOJS: ERROR: TypeError: Cannot read property 'attributes' of undefined
    at isLowestEnabledRendition (video.es.js:26027)
    at DashPlaylistLoader.<anonymous> (video.es.js:40542)
    at DashPlaylistLoader.data.dispatcher (video.es.js:1716)
    at trigger (video.es.js:1848)
    at DashPlaylistLoader../node_modules/video.js/dist/video.es.js.EventTarget.trigger (video.es.js:2319)
    at video.es.js:35101

## Additional Information
This stream I am trying to play, works fine in different media player but its not working on videojs player.
this means the stream is fine.

### versions
    "dashjs": "^2.9.0",
    "video.js": "7.2.2"
    "videojs-contrib-dash": "^2.10.0"

#### browsers
chrome

#### OSes
Windows 7/ windows 10/ macbook 

### plugins
    "video.js": "7.2.2"
    "videojs-contrib-dash": "^2.10.0"

**Comment by johnbyers** [comment]
I see the same issue too, the stack trace on my browser shows it starting at `onClientServerClockSync_` when it tries to do `_this4.trigger('loadedmetadata')`. 
Here is a snippet:
```
      key: 'onClientServerClockSync_',
      value: function onClientServerClockSync_() {
        var _this4 = this;

        this.master = this.parseMasterXml();

        this.state = 'HAVE_MASTER';

        this.trigger('loadedplaylist');

        if (!this.media_) {
          // no media playlist was specifically selected so start
          // from the first listed one
          this.media(this.master.playlists[0]);
        }
        // trigger loadedmetadata to resolve setup of media groups
        // trigger async to mimic behavior of HLS, where it must request a playlist
        window_1.setTimeout(function () {
          _this4.trigger('loadedmetadata');
        }, 0);

        // TODO: minimumUpdatePeriod can have a value of 0. Currently the manifest will not
        // be refreshed when this is the case. The inter-op guide says that when the
        // minimumUpdatePeriod is 0, the manifest should outline all currently available
        // segments, but future segments may require an update. I think a good solution
        // would be to update the manifest at the same rate that the media playlists
        // are "refreshed", i.e. every targetDuration.
        if (this.master.minimumUpdatePeriod) {
          window_1.setTimeout(function () {
            _this4.trigger('minimumUpdatePeriod');
          }, this.master.minimumUpdatePeriod);
        }
      }
```
