### ISSUE TITLE
Play/pause button doesn't show cursor pointer

### ISSUE THREAD

**Issue by gjanblaszczyk** [videojs/video.js#5462]
## Description

The player doesn't show correct pointer when the user moves the mouse cursor over the play/pause controlbar button. The issue is visible only on Firefox browser.

## Steps to reproduce
1. Open the code pen example: https://codepen.io/grbla/pen/qYVXbY
on Firefox browser.
2. Play the video
3. Use the mouse to roll over the play/pause controlbar button.

## Results
Wrong cursor.
### Expected
Cursor pointer is shown on mouse over.

#### videojs
video.js 7
#### browsers
Firefox

**Comment by gkatsev** [comment]
Huh, really weird. When I try it out on videojs.com, it's working just fine but not locally.

**Comment by gkatsev** [comment]
Oh, looks like the website includes the following rule: `input[type="button"] { cursor: pointer; }`

**Comment by picasik** [comment]
You can add
`.video-js .vjs-play-control {
    cursor: pointer;
}`

**Comment by gkatsev** [comment]
@picasik thanks, there's a PR with a fix for this in progress #5463

**Comment by gkatsev** [comment]
Fixed via https://github.com/videojs/video.js/pull/5463
