### ISSUE TITLE
CDN resources on "Getting started" returning HTTP 403

### ISSUE THREAD

**Issue by rromanchuk** [videojs/video.js#5464]
## Description
Follow the getting started steps here https://videojs.com/getting-started/#download-cdn

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Follow the getting started steps
2. Player fails because the cdn remote resource returns http 403 denied 
3.

### Expected
CDN listed in getting started guide should be able to load

### Actual
Returns access denied

### Error output
 GET https://vjs.zencdn.net/7.2.3/video.js net::ERR_ABORTED 403

**Comment by misteroneill** [comment]
Confirmed.

@gkatsev We may need to manually send these to the CDN? Looks like the newest version up there is 7.2.0

**Comment by gkatsev** [comment]
Oops, guess I've forgotten to publish them.

**Comment by gkatsev** [comment]
I've published 7.2.1, 7.2.2, 7.2.3, and 7.2.4. 7.2/ also works now and points at 7.2.3.

**Comment by mikefogg** [comment]
@gkatsev Looks like maybe the latest one (7.4.1) may also not be up there :)

**Comment by gkatsev** [comment]
At some point I'll remember to publish to the CDN immediately. And some time in the future, it'll just publish itself.

**Comment by gkatsev** [comment]
Published.

**Comment by mikefogg** [comment]
Thank you!
