### ISSUE TITLE
getFileExtension incompatible with Azure Media Services

### ISSUE THREAD

**Issue by amtins** [videojs/video.js#5466]
## Description
Azure Media Services provide URLs like  :
**HLS**
{streaming endpoint name-media services account name}.streaming.mediaservices.windows.net/{locator ID}/{file name}.ism/Manifest(format=m3u8-aapl)

**DASH**
{streaming endpoint name-media services account name}.streaming.mediaservices.windows.net/{locator ID}/{file name}.ism/Manifest(format=mpd-time-csf)

The following function tries unsuccessfully to retrieve the multimedia extension.

https://github.com/videojs/video.js/blob/966eb56c02fd82d20173840eb83ae80499620ea7/src/js/utils/url.js#L135

## Steps to reproduce
Run the following regex, `/^(\/?)([\s\S]*?)((?:\.{1,2}|[^\/]+?)(\.([^\.\/\?]+)))(?:[\/]*|[\?].*)$/i.exec("{streaming endpoint name-media services account name}.streaming.mediaservices.windows.net/{locator ID}/{file name}.ism/Manifest(format=mpd-time-csf)")`

### Expected
The ability to handle URLs from Azure Media Services 

### Actual
The file extension is not returned 

## Additional Information
Related documentation https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-portal-vod-get-started#publish-content

#### videojs
7.2.4
#### browsers
All
#### OSes
All

**Comment by gkatsev** [comment]
Our recommendation is always to add the mimetype to the media via a source element (`<source src="...windows.net..." type="application/dash+xml"`>) or as an object passed to `player.src()` (`player.src({src: '...windows.net...', type: 'application/dash+xml'});`).
That piece of code tries to detect the type of the video by looking at a file extension if it exists.
