### ISSUE TITLE
Please need help

### ISSUE THREAD

**Issue by fahadpk01** [videojs/video.js#5468]
I have tried hard to find the correct code for m3u8 live streaming in video.js player with google ads but i don't find them anywhere. 

I want to play m3u8 files with Google's IMA SDK integration. Can anyone help me find the code that plays google ads before the streaming of m3u8 files?

**Comment by gkatsev** [comment]
Video.js 7 can play m3u8 files natively, just make sure to add the correct mimetype to it. I would then look at https://github.com/googleads/videojs-ima for IMA support.
They have a getting started section in their README and they have an example you can take a look at https://codepen.io/imasdk/pen/wpyQXP

Hope this helps.
