### ISSUE TITLE
Streaming. The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by Mefistosss** [videojs/video.js#5470]
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
If we move video to other html block.

[jsfiddle. The example (fast click on the button two times)](https://jsfiddle.net/gqpr0nmL/24/)
Google Chrome 69.0.3497.81

**Comment by gkatsev** [comment]
Hey,

Unfortunately, I can't reproduce this locally. However, that warning is purely information and isn't an issue. If calling pause() and play() is called but before it's had to play chrome will print it. Google wrote a good blogpost about it and how to deal with it here https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

Hope this helps.

**Comment by Mefistosss** [comment]
Hey,

**Comment by Mefistosss** [comment]
Hey,

Please, go to the link [https://jsfiddle.net/gqpr0nmL/24/](https://jsfiddle.net/gqpr0nmL/24/) then open console and click two times on th "change container" button. The error is inside videojs.

**Comment by gkatsev** [comment]
I cannot reproduce locally even after making sure that the button doesn't move. However, this is most likely not an issue from Video.js but maybe it could just be arising from the video element itself when chrome moves it in the DOM.
