### ISSUE TITLE
Feat: Add support for Live DVR

### ISSUE THREAD

**Issue by gjanblaszczyk** [videojs/video.js#5477]
## Description
The player is playing Live DVR as a standard Live stream. 
In other players, I don't have to use any extra plugins to play Live DVR.
Are you planning to add DVR functionality to the player in near future?

**Comment by gkatsev** [comment]
This is something that we are going to be working on really soon.

**Comment by gkatsev** [comment]
This is something that we are going to be working on really soon.

**Comment by gjanblaszczyk** [comment]
Great, I can help you with that. Of course, if you need any help.

**Comment by gkatsev** [comment]
We'll let you know, thanks!

**Comment by gkatsev** [comment]
We've started work on it in #5511.

**Comment by gjanblaszczyk** [comment]
Cool, thanks for the info. I will take a look at the PR later...

**Comment by gkatsev** [comment]
This has been released in 7.4 (and 7.4.1), please try it out with the `liveui` option.

**Comment by gjanblaszczyk** [comment]
Thanks, I am planning to check it soon.
