### ISSUE TITLE
How to integrate properly videojs + video-flash with reactjs

### ISSUE THREAD

**Issue by kasidesh** [videojs/video.js#5480]
## Description
As a flash project is separate from video.js in version 7, I try to combine the script in the component, like the code (https://gist.github.com/kasidesh/2d119252f37407fbf8a399651432ef2e).

- https://github.com/videojs/video.js
- https://github.com/videojs/videojs-flash
- https://github.com/brightcove/videojs-flashls-source-handler

## Steps to reproduce
try this code 
https://gist.github.com/kasidesh/2d119252f37407fbf8a399651432ef2e

### Expected
Play the video with flash when some browser does not support HTML5 with the mediaSource

### Actual
Currently I can't play the video with flash player on video.js 7+ (in case I open IE11 on Windows 7

**Comment by gkatsev** [comment]
Hey, I updated your example a bit in a live codesandbox: https://codesandbox.io/s/xl5m5q2wjo

If you pop it out into another view and force enable flash in chrome you should be able to see it working: https://xl5m5q2wjo.codesandbox.io/

The main change I did was swap out the dependency to point at `@brightcove/videojs-flashls-source-handler`, I think that's the one the one to use.

**Comment by kasidesh** [comment]
> Hey, I updated your example a bit in a live codesandbox: https://codesandbox.io/s/xl5m5q2wjo
> 
> If you pop it out into another view and force enable flash in chrome you should be able to see it working: https://xl5m5q2wjo.codesandbox.io/
> 
> The main change I did was swap out the dependency to point at `@brightcove/videojs-flashls-source-handler`, I think that's the one the one to use.

This code is work fine!

**Comment by NuttaponTamburanavit** [comment]
This work!
I waste time to find solution for solve `@brightcove/videojs-flashls-source-handler` Error registerSourceHandle.

That is my fault, I use `yarn` is not work when I change to 'npm' it solved.

**Comment by theprimone** [comment]
@gkatsev Hello, could you explain why it working after pop it out. It doesn't work when I used the same code in storybook.

**Comment by gkatsev** [comment]
codesandbox and similar sites load the preview in an iframe which is severely restricted in what it can do, such as use flash. When you pop it out, those restrictions are lifted and you can allow flash to run on that page.
