### ISSUE TITLE
how to use rtmp in video.js

### ISSUE THREAD

**Issue by scorpionZK** [videojs/video.js#5485]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
You need to add the Flash tech from https://github.com/videojs/videojs-flash

Then use an ampersand (&) to split the stream name from the connection URL in src and use `rtmp/mp4` or `rtmp/flv`.

```player.src({
  src: 'rtmp://example.com/live&foo',
  type: 'rtmp/flv'
});
```

https://docs.videojs.com/tutorial-faq.html#q-how-can-i-play-rtmp-video-in-videojs

Of course this is only possible where Flash is available, and subject to any restrictions the browser puts on Flash content.
