### ISSUE TITLE
no tooltips on full screen mode

### ISSUE THREAD

**Issue by DineshBhudia** [videojs/video.js#5488]
## Description
When the video is on full screen mode the tooltips won't appear.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Expand video to full screen 
2. put mouse over any buttons.
3.

### Expected
Please describe what you expected to see.
text of the button appear as a tool tip
### Actual
Please describe what actually happened.
no text appears
### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### chrome ie and firefox
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Unfortunately, I cannot reproduce the issue. I still see the tooltips in fullscreen mode.
Also, Video.js 5 is a pretty old version, I would recommend updating to latest v6 or v7.
