### ISSUE TITLE
Live HLS go to live

### ISSUE THREAD

**Issue by Surt** [videojs/video.js#5490]
## Description
When playing a VOD HLS m3u8 it seems to have more delay than the ts segments. 3 seconds TS segments and player playing 40 seconds from actual time) Is there any way to command the player to go to the last segment when playing (go to live)?

**Comment by gesinger** [comment]
Hey @Surt , would you be able to put together a sample page with our [starter template](https://jsbin.com/gejugat/edit?html,output) on JSBin and the source you are looking at?

Also, are you looking at a VOD asset or a LIVE asset?

Thanks.

**Comment by Surt** [comment]
Hi @gesinger 

I was triying to set a live m3u8 online so you can see the differences, but then I saw that if I set a playbackrate 2x it reach the last segment and I can play the HLS with minimun delay.

Is there a way to set the playback time to the current time on code, I could create a button with that and everything will be fine.
