### ISSUE TITLE
iOS player embedded in iframe in Cordova WKView Webview opens up empty native controls and playsinline underneath

### ISSUE THREAD

**Issue by bcorvino** [videojs/video.js#5493]
## Description
Briefly describe the issue.
I'm seeing this issue in WKWebView. I'm loading the following page in an iframe in an Ionic3 app. I get empty native controls with no video on iOS10. The video begins playing inline underneath. If I close the native controls, I can then interact with the video. This is in the simulator and on actual devices.

It works on iPad, but not on iPhone. Any info would be greatly appreciated.

playsinline is set on the video tag in the player and AllowInlineMediaPlayback is true in my app (hence the video playing inline underneath the empty native controls.

<img width="696" alt="screen shot 2018-10-10 at 11 53 50 am" src="https://user-images.githubusercontent.com/7740747/46755240-957ba500-cc92-11e8-9c76-9e771d6fde14.png">

<img width="700" alt="screen shot 2018-10-10 at 11 53 58 am" src="https://user-images.githubusercontent.com/7740747/46755244-990f2c00-cc92-11e8-999c-0162392ae931.png">

Player can be seen here:
https://p.batterypop.net/apps/omv/?distribution_id=760d645f-0071-0e6e-cbc0-c082db5b2649&ms_uuid=51be9511-c822-c147-4b26-5c4805671ff4&autoplay=true&autoresume=true&debug=1

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. In Cordova WebView, place an iframe whose source contains a videojs player
2. Launch in simulator or browser

### Expected
Please describe what you expected to see.
VideoJS player to display inline and operate

### Actual
Please describe what actually happened.
VideoJS player plays inline underneath empty Native controls.  Closing Native Controls reveals the inline VideoJS player.

### Error output
If there are any errors at all, please include them here.
None

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
6 and 7
#### browsers
what browser are affected?
Cordova WebView
#### OSes
what platforms (operating systems and devices) are affected?
iOS
### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-ima
videojs-contrib-ads
canAutoplay

**Comment by bcorvino** [comment]
So after a day, I found the issue.  Posting here in hopes of saving someone else time.  The phantom native player was being created by canAutoplay.  So, if you're using canAutoplay, remember to add the "inline" option to your calls if you're looking to display the eventual video inline.

canAutoplay
    .video({
      timeout: 100, 
      muted: false,
      inline: true
    })

Hope this helps someone!

**Comment by gkatsev** [comment]
Glad you were able to figure it out and thanks for posting your solution!
