### ISSUE TITLE
Playing a video that is being recorded on a webcam

### ISSUE THREAD

**Issue by bostinait** [videojs/video.js#5495]
Hi,

We are currently recording the video from a webcam using the videojs-record plugin.

Every 5 seconds we grab a slice of the recorded video, upload it to the server and concantenate to a master video file (mp4)

VideoJs will load that video but stop playing after the first 5 seconds despite the video being appended to in the background.

We realise that on first load it is evaluating the latest duration but I am wondering if there is anyway for videojs to re-evaluate the source video and get the updated video and continue playing?

Any help greatfully received.

**Comment by gkatsev** [comment]
Unfortunately, there isn't really a good way to do it with mp4s. You could re-add the source to the player and seek forward but that's not ideal. What you really want is a segment file format that provides live stream capabilities like DASH or HLS. Then each 5 second slice can be turned into an fmp4 segment in the DASH/HLS manifest.

Hope this helps.
