### ISSUE TITLE
Blob Url Support broke with 7.2.1

### ISSUE THREAD

**Issue by flipace** [videojs/video.js#5504]
## Description
When using a dynamically generated blob url as a video source, any player interaction will be silenced by video.js

It works flawlessly when triggering `.play()` directly on the HTMLVideoElement though.

Reproduction case with comparison of 7.2.0 and 7.2.1: https://github.com/flipace/video.js-7.2.1-blob-issue. This is related to a change made in https://github.com/videojs/video.js/pull/5371

## Steps to reproduce
1. Generate a blob url for a video
2. Pass the blob url as a src (with type) to videojs
3. Try triggering playback of the video

### Expected
Playback should start when clicking the play button(s).

### Actual
Nothing happens.

### Error output
No errors. video.js is stuck and will always wait for the video to be loaded into its internal source cache (which never happens though)

#### videojs
7.2.1 and above are affected
#### browsers | OSes
since this is a videojs internal issue probably all of them

**Comment by gkatsev** [comment]
Just merged a fix, we should be making a release tomorrow.

**Comment by flipace** [comment]
awesome! thanks @gkatsev and @BrandonOCasey !

**Comment by gkatsev** [comment]
It's out in 7.3.0, please try it out and report back if there are problems. If necessary, we can make a 7.2 patch but hopefully it won't be :)

**Comment by maxpaj** [comment]
I just tried using a blob:// source URL. It doesn't work (HTML5 tech says it can't play it) unless you specify a source object like this:
```
player.src({ src: "blob://...", type: "video/webm" });
```

**Comment by BrandonOCasey** [comment]
Interesting, you may want to open this as a new issue
