### ISSUE TITLE
a part of m3u8 file can not be played, how to ignore it and play the rest.

### ISSUE THREAD

**Issue by wj20160318** [videojs/video.js#5510]
just ignore the bad, not stop the whole.

**Comment by forbesjo** [comment]
Once we support EXT-X-GAP tags we can use those to skip over segments that have problems and there are no other playlists that we can fall back to. If there is no GAP tag then the experience of seeking over content would not be great and we would prefer to fallback to another rendition. 

Does this sound similar to the scenario you're experiencing?
