### ISSUE TITLE
Rounded corners and shadow, how to do it?

### ISSUE THREAD

**Issue by stek2000** [videojs/video.js#5513]
## Description
I would like to have the video.js video-player rounded corners (say 5px ) and a small shadow.
Alas I can not get this done and hope any of you experts can help me how to do this.
Already many thanks for your help and advice.
Kind Regards,
Frans

## St

**Comment by stek2000** [comment]
Hi Pat,
Thanks for your message, I really appreciate this.
Indeed Video.js is a stunning, beautiful player, by far the best I ever used.
Your solution works perfect, great job.
Kind Regards,
Frans

**Comment by misteroneill** [comment]
Thanks so much, Frans! Glad that worked for you.
