### ISSUE TITLE
Some m3u8 resource couldn't play!

### ISSUE THREAD

**Issue by jinaviva** [videojs/video.js#5517]
## Description
http://124.232.231.246:6610/000000001001/201500000003/index.m3u8?IASHttpSessionId=OTT983820181017024353153904
HLS Link like above couldn't play in video-js,but could play in desktop player such as VLC media player or PotPlayer.Why?

## Steps to reproduce
use video-js v7.2.3 play above url

**Comment by mister-ben** [comment]
If you check the browser's dev tools you'll see an error similar to this:

> Access to XMLHttpRequest at 'http://124.232.231.246:6610/000000001001/201500000003/index.m3u8?IASHttpSessionId=OTT983820181017024353153904' from origin 'http://example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Your server must set correct headers in the response, otherwise your browser blocks the request. Desktop apps like VLC don't enforce the use of these headers.

See https://enable-cors.org/server.html
