### ISSUE TITLE
weird overlay

### ISSUE THREAD

**Issue by slash197** [videojs/video.js#5521]
What is this and how can I remove it? It's not the big-play-button as I've set that display to none. Usually appears if source is not playable or some sort of error.

![screenshot_20181023-122829](https://user-images.githubusercontent.com/11959840/47351046-dbd3f980-d6bf-11e8-9f1b-6f82b4c54d66.png)

**Comment by mister-ben** [comment]
android webviews will show this on a video element if there is no content. iirc setting a poster image is enough to prevent it.
