### ISSUE TITLE
video size is incorrect 

### ISSUE THREAD

**Issue by wilddylan** [videojs/video.js#5529]
i want full width....  but not worked 

![image](https://user-images.githubusercontent.com/2519544/47557270-d508e900-d942-11e8-994a-43e905e54a56.png)

![image](https://user-images.githubusercontent.com/2519544/47557285-d9350680-d942-11e8-816a-6fedb3a60c26.png)

![image](https://user-images.githubusercontent.com/2519544/47557294-de925100-d942-11e8-85a4-f23043793361.png)

![image](https://user-images.githubusercontent.com/2519544/47557299-e520c880-d942-11e8-9212-fa44285580f9.png)

**Comment by misteroneill** [comment]
If you set `fluid: true` in your options, it should give you the effect you want.

**Comment by gkatsev** [comment]
`aspectRatio` option will set fluid for you. Oceans video has a 2.4 aspect ratio compared to the 1.7 ratio that you've set the player. This is why the black bars are showing with that poster image.

**Comment by wilddylan** [comment]
thanks, fixed this...  👍
