### ISSUE TITLE
Streaming bitrate selection is too low for mpeg-dash

### ISSUE THREAD

**Issue by edwinbradford** [videojs/video.js#5532]
## Description
Bitrate selection is much lower in the video.js player than the [DASH Reference Client](http://mediapm.edgesuite.net/dash/public/nightly/samples/dash-if-reference-player/index.html) for the exact same stream fetched from the same server. My [sample 15 second stream](https://raw.githubusercontent.com/edwinbradford/media/master/mpd-2s/media.mpd) is encoded for mpeg-dash streaming at six different bitrates following a number of guides. 

In video.js running on my local machine the bitrate quality starts at medium, after one second it drops to the lowest, then it returns to medium until the end.

In video.js running on [jsfiddle ](http://jsfiddle.net/edwinbradford/t1d516um/) the quality starts very low, drops to the lowest, then returns to very low until the end.

In the [DASH Reference Client](http://mediapm.edgesuite.net/dash/public/nightly/samples/dash-if-reference-player/index.html) the quality starts low then immediately jumps to high and remains high until the end.

It would also be helpful if there is a method to set the default bitrate when streaming starts to prevent such a low resolution being chosen. I see that the [JWPlayer does this](https://www.jwplayer.com/blog/improving-video-startup-quality-with-adaptive-streaming/) but I'm not sure if this is possible or how to implement it in the video.js player.

## Steps to reproduce
Load the [source mpd](https://raw.githubusercontent.com/edwinbradford/media/master/mpd-2s/media.mpd) into any instance of a video.js player, press the full screen button then play the source from beginning to end multiple times and compare the bitrate quality switching.

Load the same source into the DASH Reference Player, press the full screen button and compare the quality with that of the video.js player.

If you wish to compare the effects of different fragment intervals for the same stream you can easily do so by selecting a different directory from my [media](https://github.com/edwinbradford/media) repository on github. Each directory has the same content encoded with the same parameters except for fragment length where the folder "mpd-4s" for example refers to a 4 second interval.

### Expected
The video.js player should establish the bandwidth at the start of the video then select the optimum bitrate as seen in the DASH Reference Player.

### Actual
The video.js player appears to drop the bitrate after streaming begins then raise it again but to a level below that the bandwidth can support.

### Error output
No errors are generated.

## Additional Information
video.js version 7.2.4, no plugins.
Chrome Browser
Windows 10

**Comment by edwinbradford** [comment]
Two more examples.

1. The JW Player. Please load my stream into their [Stream Tester](https://developer.jwplayer.com/tools/stream-tester/)

2. The Shaka Player. Please load my stream into the field labelled "Custom Manifest" in their [Shaka Player Demo](https://shaka-player-demo.appspot.com/demo/#lang=en-GB;build=uncompiled)

If you compare the quality of the text in my sample stream you can see it pretty much renders perfectly from the outset in all three players above. In video.js the quality is so bad I've had to disable streaming and revert back to non streaming mp4s.

I'm sorry but I get the impression streaming is just not fully working yet in video.js.

**Comment by edwinbradford** [comment]
Thanks for the suggestions, I tried both of them but unfortunately they had no effect.

I re-tried my test streams in the DASH Reference Client today and the results are more consistent than before with every stream I try dropping to the lowest bitrate available. I'm therefore coming to the opinion that something must be wrong with the encode.

**Comment by nakov** [comment]
The `limitRenditionByPlayerDimensions` option should be nasted in `html` -> `hls`.

This examples works for me:
```
<!DOCTYPE html>
<html>
  <head>
  <link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />
</head>

<body>
  <video id="my-video" class="video-js vjs-16-9" controls="true"
    preload="auto" data-setup='{"playbackRates": [0.75, 0.9, 1, 1.25, 1.5, 2], "html5": {"hls": {"limitRenditionByPlayerDimensions": false}}}'>	
      <source label="auto" src="https://videos.softuni.org/hls/demo-,1080p,720p,480p,360p,240p,.mp4/urlset/master.m3u8" />
  </video>
  <script src="https://vjs.zencdn.net/7.8.4/video.js"></script>
  </body>
</html>
```

It starts with 1080p, even on small screens and keeps the 1080p bitrate when the connection speed is good enough.
