### ISSUE TITLE
VideoJS events stop firing in Chrome 70

### ISSUE THREAD

**Issue by wturrinVemba** [videojs/video.js#5546]
## Description
All events after ads are not firing

## Steps to reproduce
I am using the following plugins:

videojs-contrib-ads
videojs-ima
videojs-playlist
videojs-vtt

With autoplay on or off, the video queues an ad, which plays with all events firing. The video then plays to completion, but no events are fired on Chrome 70. We've tested this in other browsers and we do not see this issue duplicated.

## Results
All events should fire.

### Error output
There are no errors.

**Comment by gkatsev** [comment]
Would you be able to provide a reduced test case please?
