### ISSUE TITLE
Segments metadata track is shown when changing source

### ISSUE THREAD

**Issue by johnbyers** [videojs/video.js#5553]
## Description
If you had captions on, and then change the video source, you get some weird text on the screen. The guys on videojs slack thought it was the segments metadata track.

## Steps to reproduce
1. Visit the VHS test page at https://videojs.github.io/http-streaming/
2. Play the video, choosing the very bottom closed caption track, "cc1". (Not sure what language it is for, but the captions show English)
3. Reset the player's source by clicking the "Load" button again.
4. Play the video, and see the weird text/json

### Expected
No captions after changing source.

### Actual
Even though closed captions are set to "off" after switching the source, this appears as a caption over the video:
`{"bandwidth":915905,"resolution":{"width":960,"height":540},"codecs":"mpra.40.2,avc1.4d401f","byteLength":1046972,"uri":"https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/gear3/main.ts","timeline":0,"playlist":"gear3/prog_index.m3u8","start":9.976644444444446,"end":19.91992222222223}`

#### videojs
I've seen it in 7.2.2 and 7.2.4
#### browsers
Chrome, Firefox, and IE11. 
Edge doesn't even show captions.
Mobile Safari doesn't show that bottom "CC" caption option, so it doesn't seem to have the problem.
#### OSes
Microsoft Windows 10
### plugins
None

**Comment by gkatsev** [comment]
Ooh, thanks for the reproducible test case!

**Comment by ldayananda** [comment]
From taking the quickest of looks at this, I think it's because `userPref.language` and `track.language`(for the metadata-track) are both `''` here:

https://github.com/videojs/video.js/blob/6bff3ce77977fe5026e994c0b65680f8ffbe45d3/src/js/tracks/text-track-display.js#L154

We should probably ensure that text-track-display completely ignores non-visible track types

**Comment by ldayananda** [comment]
It might also make sense to clear the TextTrackList queue on source changes too?

https://github.com/videojs/video.js/blame/8c92cbfb3e98259999224d5dd7778f35dfe1cab7/src/js/tracks/text-track-list.js#L31

**Comment by gkatsev** [comment]
clearing the event queue makes sense.
We should update the preselectTrack method to ignore when language is the empty string and also ignore tracks that are chapters or metadata

**Comment by johnbyers** [comment]
What is special about that "cc1" caption? All the others have a language, but that one just says "cc1". Is there something different about it?

**Comment by gkatsev** [comment]
cc1 is the first caption track for 608 captions which live inside the video data. Not sure if that has language data but we should consider setting one for it as well.

**Comment by johnbyers** [comment]
That is interesting, I thought we were using WebVTT captions in our project, I guess they have turned into 608 captions

**Comment by gkatsev** [comment]
It looks like any caption without a language would trigger this issue.
