### ISSUE TITLE
TypeError: null is not an object (evaluating 'player.$('.vjs-tech').tagName')

### ISSUE THREAD

**Issue by subhranshudas** [videojs/video.js#5554]
I am getting the above error in SAFARI ONLY when i try to run the same code that works in Chrome.

Basically i am initializing videojs by -

      const video = document.createElement('video');
      video.setAttribute('width', '100%');
      video.setAttribute('height', '100%');
      video.setAttribute('id', 'video-el');
      video.removeAttribute('controls');
      videojs(video);

<img width="1186" alt="screen shot 2018-11-05 at 5 26 58 pm" src="https://user-images.githubusercontent.com/6158624/48033208-08582e80-e120-11e8-8996-ef5e8a7b0062.png">

Any direction as to what may cause this.

Thank You.

**Comment by gkatsev** [comment]
`$` is shorthand for `querySelector` and it requires that the elements be in the DOM, which your sample code doesn't do. Also, that erroring code snippet doesn't seem to be in Video.js core. Is it in a plugin or in your code?
I would suggest making sure that `video` is in the DOM before initializing Video.js; Video.js should be warning about this already. Also, if the erroring code snippet is in your code, I would add a null-check.

**Comment by subhranshudas** [comment]
Thanks @gkatsev for the reply.
The code where the above error occurs is 
https://github.com/videojs/videojs-contrib-eme/blob/d966e5b3ce8a82a84bf2f189937c33e348cc20eb/src/plugin.js#L186

I have verified, the DOM element is actually present. 
Happens when i try to doing https://github.com/videojs/videojs-contrib-eme/#initialization for FPS as described in the link.

**Comment by subhranshudas** [comment]
So while i am trying to create a reduced test case, here is what i have found so far.

I am basically using 2 layers - 1 for my React UI, the other to delegate things to Video JS which is in pure JS. The flow goes like this--
1) REACT UI passes a dynamically created DOM element (DIV) which is yet to be inserted inside the DOM, to the Video JS layer.
  componentDidMount() {
     this.videoDIVElement = document.createElement('div');
     videoJSLayer(this.videoDIVElement);
  }

  appendVideoToWrapper = (wrapper) => {
    if (wrapper) {
      /* this is the un-inserted DIV that is passed when calling the Video JS layer  in below code*/
      wrapper.appendChild(this.videoDIVElement); 
      this.videoWrapperRef = wrapper;
    }
  }

render() {
   if (allDataAvailable) {
        return (
        <div
          ref={this.appendVideoToWrapper}
        >
          
        </div>
    );
   }
}

2) The Video JS layer takes this un-inserted into DOM DIV, and does the following -

videoJSLayer(htmlDIV) {
const video = document.createElement('video');
  video.setAttribute('width', '100%');
  video.setAttribute('height', '100%');
  video.setAttribute('id', 'video-el');
  video.removeAttribute('controls');
  videojs(video); // line X
  htmlDIV.appendChild(video); // line Y
}

// And later when we do some data fetching and give Video JS all it needs for the player.src(). We call this function.
finallyPlay() {
player.src();
player.play()
}

Then we setState and the UI component and the "videoDIVElement" is inserted into the DOM. This approach makes sure that the component is rendered only when everything is ready.

This works very well in CHROME, though VideoJS warns about the element supplied not in the DOM due to the order of line X and line Y. But even with the warning it is still able to play the video in CHROME.

But for Safari, the difference i have noticed is 
// "videojs-contrib-eme" is imported
finallyPlaySafari() {
player.eme()
player.src();
player.play()
}

And then it throws the error TypeError: null is not an object (evaluating 'player.$('.vjs-tech').tagName')

So just curious how is Video JS itself cool with the Video element not present in the DOM and works fine in case of Chrome, but for Safari when we add the plugin "videojs-contrib-eme" and call player.eme() before the other two standard calls -- player.src() & player.play(), it breaks down.

Is there any way to keep the workflow which works in Chrome also in Safari.

Thanks.

**Comment by subhranshudas** [comment]
@gkatsev i went back and placed the VIDEO element in the HTML and now the DOM latency doesn't creep up any error. But it will remain a mystery to me as to why for Chrome video JS is cool, but when we introduce player.eme() to the flow for safari, it breaks. 

Closing this for now.
