### ISSUE TITLE
Clicking on a menu button causes the first menu item to change background color

### ISSUE THREAD

**Issue by gjanblaszczyk** [videojs/video.js#5557]
## Description
The first captions in the language menu change the background color after click on the captions button on the control bar.

![videojsmenuclickfocusissue](https://user-images.githubusercontent.com/5346546/48101526-9e2ab100-e227-11e8-9bdb-a2e004570430.gif)

## Steps to reproduce
1. Go to the focus-visible sandbox page
2. Click the captions button on the control bar.
3. You will see that first element in the menu changes the background color.

### Expected
The first element in the menu doesn't change the background color.
### Actual
The first element in the menu changes the background color.

#### videojs
Latest
#### browsers
all
#### OSes
all

**Comment by gkatsev** [comment]
Closed by #5558
