### ISSUE TITLE
Not working in android chrome used fmp4

### ISSUE THREAD

**Issue by neil74123** [videojs/video.js#5560]
## Description
When videojs play fmp4 format hls stream in android chrome(v64+), it always show the error message . But it play success in android firefox(v60+) and in windows(8.1+) chrome(v64+)、firefox(v60+). 

## Error Output
the media playback was aborted due to a corruption problem or because the media used features your browser did not support

## Versions
Videojs 7.3.0

## OS
Android(6.0+)

**Comment by Hank9** [comment]
I also have the same problem,I hope there is a solution.

**Comment by neil74123** [comment]
I solved it. This issue happened because the default player is not videojs in android chrome. Use overrideNative option can solve it.
