### ISSUE TITLE
Update the reduced test case starter template

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#5562]
## Description
The [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin uses http for its links even though JS Bin itself forces the URL to use https. This causes some failures.

The template also uses video.js v5, which is deprecated now; it needs updating to v6.

**Comment by gkatsev** [comment]
I created a codepen template that we can start using: https://codepen.io/gkatsev/pen/GwZegv?editors=1010#0

**Comment by gkatsev** [comment]
Made a PR for it https://github.com/videojs/video.js/pull/5570
