### ISSUE TITLE
Playing DRM content on Android

### ISSUE THREAD

**Issue by slash197** [videojs/video.js#5563]
## Description
Implemented widevine drm with videojs for dash streams and it works great on desktop and mobile, however I get an error message playing it in a mobile app's webview. The error is: 

> Uncaught (in promise) NotSupportedError: Unsupported keySystem or supportedConfigurations.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Run the same videojs config through an android webview

### Expected
Playing video content

### Actual
No playback and error message

### Error output
Uncaught (in promise) NotSupportedError: Unsupported keySystem or supportedConfigurations.

## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
chrome webview?
#### OSes
Android 8+
### plugins
videojs-contrib-eme

## videojs config
```
_vjs.eme();
_source = {
	src: options.url,
	type: _mime,
	keySystems: {
		'com.widevine.alpha': {
			getLicense: function(emeOptions, keyMessage, callback){
				var message = new Uint8Array(keyMessage);

				videojs.xhr({
					uri: 'https://wv-keyos.licensekeyserver.com/',
					method: 'POST',
					responseType: 'arraybuffer',
					body: message,
					headers: {
						customdata: App.player.drm.key
					}
				}, function(err, response, responseBody){
					if (err) {
						callback(err);
						return;
					}
					callback(null, responseBody);
				});
			}
		}
	}
};

```

**Comment by mister-ben** [comment]
An Android webview doesn't support DRM by default. You need to override [`onPermissionRequest`](https://developer.android.com/reference/android/webkit/PermissionRequest) in the webview's `WebChromeClient`, something like

    public void onPermissionRequest(PermissionRequest request) {
      // Crude example, you need to check which permissions were requested 
      String[] perms = {PermissionRequest.RESOURCE_PROTECTED_MEDIA_ID};
      request.grant(perms);
    }

Even then you may find support varies by device.

**Comment by forbesjo** [comment]
Thanks @mister-ben for the answer, we'll add this to a FAQ

**Comment by halilozel1903** [comment]
@mister-ben Thank you very much Señor 💯 It worked successfully. 👍

**Comment by halilozel1903** [comment]
> An Android webview doesn't support DRM by default. You need to override [`onPermissionRequest`](https://developer.android.com/reference/android/webkit/PermissionRequest) in the webview's `WebChromeClient`, something like
> 
> ```
> public void onPermissionRequest(PermissionRequest request) {
>   // Crude example, you need to check which permissions were requested 
>   String[] perms = {PermissionRequest.RESOURCE_PROTECTED_MEDIA_ID};
>   request.grant(perms);
> }
> ```
> 
> Even then you may find support varies by device.

@mister-ben Thank you very much Señor 💯 It worked successfully. 👍

**Comment by alpkahveci** [comment]
> An Android webview doesn't support DRM by default. You need to override [`onPermissionRequest`](https://developer.android.com/reference/android/webkit/PermissionRequest) in the webview's `WebChromeClient`, something like
> 
> ```
> public void onPermissionRequest(PermissionRequest request) {
>   // Crude example, you need to check which permissions were requested 
>   String[] perms = {PermissionRequest.RESOURCE_PROTECTED_MEDIA_ID};
>   request.grant(perms);
> }
> ```
> 
> Even then you may find support varies by device.

You are the best, thanks a lot !

**Comment by JoaoCEAlmeida** [comment]
I'm having this problem with videojs "7.7.6" on web with m3u8 links also, when I have DRM enable...

![image](https://user-images.githubusercontent.com/9196047/92763671-b0c62200-f38b-11ea-9f28-7156f1aa2775.png)

@slash197 @mister-ben Can this be related some how with this ?

Thanks in advance.

**Comment by alpkahveci** [comment]
> I'm having this problem with videojs "7.7.6" on web with m3u8 links also, when I have DRM enable...
> 
> ![image](https://user-images.githubusercontent.com/9196047/92763671-b0c62200-f38b-11ea-9f28-7156f1aa2775.png)
> 
> @slash197 @mister-ben Can this be related some how with this ?
> 
> Thanks in advance.

Which drm do you use? playready?
