### ISSUE TITLE
find a empty box

### ISSUE THREAD

**Issue by fanbaobao** [videojs/video.js#5564]
![image](https://user-images.githubusercontent.com/22856474/48189096-4fd9f700-e37a-11e8-9fb5-faed320c58d0.png)

Click play button and then an empty box appears when video loads

**Comment by gkatsev** [comment]
That looks like the border of an iframe element. We use an iframe element when ResizeObserver isn't available. You can disable it by passing in `resizeManager: false` option to the player.
Does video still play or do you get a blank video?

**Comment by gkatsev** [comment]
Can you try version 7.3.0? We had a fix related to it: https://github.com/videojs/video.js/pull/5522

**Comment by fanbaobao** [comment]
I'm sorry that this problem still exists. The version I'm using now is 7.3.0, mainly focused on the iphone, and most android phones are available

**Comment by gkatsev** [comment]
Oh, I see. I think it's happening because we didn't turn off the border for iframes. As a workaround, you can turn off the resizeManager until it is fixed.

**Comment by gkatsev** [comment]
Looking into this, it seems like we properly set up the ResizeManager iframe to not have a border. In 7.3.0, we changed how the ResizeManager iframe is done: https://github.com/videojs/video.js/pull/5522.
Would you be able to provide a reduced test case? I am having a hard time reproducing it locally. I'm guessing that it's some styles on the page conflicting with our styles for the iframe. Any CSS frameworks used on the page?

**Comment by fanbaobao** [comment]
Today I created a new demo, and the frame did not appear again, probably because I just updated VJS version to 7.3.0 last time,But no update it min. CSS file, this is my demo address [](https://github.com/fanbaobao/video-test), thanks again for your help!!！
This demo also shows some other issues on android phones, in China a lot of browsers are x5 cores,
On these browsers VJS is so high up when they play video that there's nothing to cover them,
My tests on chrome and firefox are good, but running on the browsers of Wechat and Tencent creates a hierarchy problem.
I feel very helpless, because there is no way around tencent in China
