### ISSUE TITLE
m3u8 not release memory

### ISSUE THREAD

**Issue by WzFFzW** [videojs/video.js#5567]
## Description
In SPA web application, I use video.js to play media in m3u8 format. 
What is strange is that you enter the play route to play the video, and return to the index route after about 2s. Repeat 10 times and you will find that memory usage is high.

## Steps to reproduce
in spa web application
1.entry http://localhost:8080/index
2.entry http://localhost:8080/play
3.about 3s back to http://localhost:8080/index
4.repeat 10 times

### Expected
memory release

### Actual
Memory increase and repeat too many times memory leak

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
video.js@7.2.4
#### browsers
70.0.3538.77 chrome
#### OSes
mac os mojava 10.14
### plugins
no plugin
### code
react 16.5.2 
react-router 4.3.1

**Comment by gkatsev** [comment]
You probably want to dispose the player in `componentWillUnmount`, see https://docs.videojs.com/tutorial-react.html for an example.

**Comment by WzFFzW** [comment]
thk, it's work
