### ISSUE TITLE
在Safari和ios上报无法播放是什么原因啊 video.cjs.js?0e26:450 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) 此视频暂无法播放，请稍后再试 MediaError {code: 4, message: "此视频暂无法播放，请稍后再试"}

### ISSUE THREAD

**Issue by JInvent** [videojs/video.js#5572]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Please use the template and make a very simple example that demonstrates the problem ("reduced test case"). That makes it much easier to understand the problem, especially when we do not speak the same language.

One problem that causes that error in Safari is if your server does not support byte range headers.

**Comment by gkatsev** [comment]
Also, are you running the video.cjs.js file in the browser? That should only be used via a bundler like webpack. Make sure you're using the video.js or video.min.js file if you're not running a bundler.
