### ISSUE TITLE
Browser crashes when progressControl is true under IE11

### ISSUE THREAD

**Issue by jinyaqiao1102** [videojs/video.js#5575]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

   When I play an MP4 video with Videojs under IE11, when the progressControl is set to true, the browser will be minimized, and the CPU will rise to 30%, causing the IE browser to become unresponsive. If the progressControl is set to false, the CPU usage will be Stay at around 2% and there will be no browser stuck

## Results
IE cpu usage rate soared, causing page stuck
### Expected
Don't want to crash under IE
Please describe what you expected to see.
I don't expect this kind of CPU rise to cause a stuck problem.
### Actual
Please describe what actually happened.
CPU 
### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does te
his occur with?
7.3.0
#### browsers
what browser are affected?
IE
#### OSes
what platforms (operating systems and devices) are affected?
WIN 10
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
The progress control is enabled by default and Video.js works fine in IE11Win10. Can you provide a test case of your scenario?

Also, I just tried the following option and didn't see any unexpected spike in CPU:
```js
var player = videojs(vid, {
  progressControl: true
});
```

**Comment by jinyaqiao1102** [comment]
> The progress control is enabled by default and Video.js works fine in IE11Win10. Can you provide a test case of your scenario?
> 
> Also, I just tried the following option and didn't see any unexpected spike in CPU:
> 
> ```js
> var player = videojs(vid, {
>   progressControl: true
> });
> ```

You have to minimize the IE window to see what I said. If you keep the window visible, it won't happen. What I said is the problem. If CPU goes up, the IE window will be maximized at this point, and CPU usage will drop to normal.

**Comment by jinyaqiao1102** [comment]
![videojs](https://user-images.githubusercontent.com/12856504/48537055-4ce78500-e8eb-11e8-9ba8-404ef638333c.gif)

**Comment by gkatsev** [comment]
I can reproduce that, though, when verifying on a page with just Video.js, it doesn't get as high. Also, it drops when the video isn't playing.
There's definitely more performance fixes that we can do though it's weird that this is happening only on IE11

**Comment by jinyaqiao1102** [comment]
Will this performance problem be solved in the near future?

**Comment by gkatsev** [comment]
I've been able to track down the issue an opened #5879 which I believe fixes the problem.
