### ISSUE TITLE
Autoplay Does not work in Chrome 70

### ISSUE THREAD

**Issue by afridley** [videojs/video.js#5581]
## Description
Autoplay does not function in chrome when used with data-setup or in the video tag itself.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. use autoplay attribute on a Video tag running videojs
2. use autoplay in the data-setup attribute running videojs
3. Notice autoplay does not function on chrome

https://jsfiddle.net/afridley/dvLgr1cb/
### Expected
Autoplay functions in chrome

### Actual
The video does not autoplay

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Latest cdn 7.0.4
#### browsers
Chrome Version 70.0.3538.102
#### OSes
Mac OS mojave

**Comment by gkatsev** [comment]
This is expected. Browsers now will not autoplay by default anymore, unless the video is muted. To that end, we have extra values for the autoplay option to video.js: https://docs.videojs.com/tutorial-options.html#autoplay. However, that option seems to not be working properly right now, and it's something we should fix.

For more information on autoplay, you should check out our [autoplay best practices](https://blog.videojs.com/autoplay-best-practices-with-video-js/) blogpost.

**Comment by afridley** [comment]
I have added the muted tag to the example but the player still is not working in chrome 70. I also added a standard html5 video player with the same attributes that does autoplay. I would expect videojs to function in a similar way as the default player in regards to these attributes.

https://jsfiddle.net/afridley/dvLgr1cb/13/

**Comment by gkatsev** [comment]
Yeah, there's definitely something weird going on, we'll take a look.

**Comment by gkatsev** [comment]
Looking into this a bit, it seems like there's some weird timing issue. I can't reproduce it at all locally but if I create a new page on say codepen, I can reproduce it. And there's more chatter of things being an issue in #4720.

**Comment by afridley** [comment]
Yeah it definitely looks like it's the same issue as #4720 
Both the solutions that were posted there seem to work

```
var player = videojs('video_delay');
player.ready(function() {
  setTimeout(function() {
    player.autoplay('muted');
    player.fluid('true')
  }, 1000);
});


var video = $("video").get(2);
video.load();
video.play();
if (video.paused) {
  location.reload(true);
}

```

**Comment by joe455** [comment]
It's happening with chrome latest version and videojs version 7.3.0. Can someone help me to resolve this issue.

**Comment by gkatsev** [comment]
@joe455 you can see autoplay still being broken in chrome 71 with Video.js 7.3? What OS are you on? Do you have an example?

The fiddle created by @afridley works great for me in chrome 71 on macos currently.

**Comment by gkatsev** [comment]
Also, I want to redirect this issue into #5233 so that we have only one issue on going related to this.

**Comment by ssutikno** [comment]
Hi All,

I found solution here.

chrome://settings/content/sound

allow you domain there..
