### ISSUE TITLE
no compatible source was found for this media

### ISSUE THREAD

**Issue by farhoudi** [videojs/video.js#5582]
## Description
"no compatible source was found for this media" error on virtual host.

## Steps to reproduce
I have implemented player as the article below:
https://radek350.wordpress.com/2017/10/29/dash-encrypting-and-playing-video-with-clearkey-videojs/
Video is playing via localhost url like "http://localhost/project/public/courses/10/math".
But it is not playing and is showing "no compatible source was found for this media" error on virtual host like "http://project.test/courses/10/math".

### Expected
Playing video.

### Actual
Showing "no compatible source was found for this media" error.

### Error output
no compatible source was found for this media

## Additional Information
Laravel back-end.
PHP 7.2

### versions
video-js-7.2.3
dash.js-2.9.1
videojs-contrib-dash-2.9.1

#### browsers
google chrome 68
google chrome 69

#### OSes
windows 7
fedora 27 workstation

**Comment by gkatsev** [comment]
Encrypted video isn't available via HTTP, only via HTTPS, though, I thought that localhost was exempt. It's worth trying it via HTTPS.
