### ISSUE TITLE
RTMP Support

### ISSUE THREAD

**Issue by heff** [videojs/video.js#559]
Creating a wrap-up issue for RTMP support questions.

Summary: RTMP has been in development for awhile, but we haven't had the time/resources to polish it off yet. It's been tested in a few applications but there's no direct interface to it from the javascript, or documentation around it yet. We don't yet have priority around this or a release date, but I'll update this issue when we do.

For anyone experience with Flash, you can see the implementation in the swf here:
https://github.com/videojs/video-js-swf/blob/master/src/com/videojs/providers/RTMPVideoProvider.as

Related issues include: #352, #176, #229, #180, #151
SWF Issue: https://github.com/videojs/video-js-swf/issues/8

**Comment by mdipierro** [comment]
Will video.js be able to play rtmp on browsers that do not support flash or does it require flash?

**Comment by mister-ben** [comment]
RTMP playback requires the browser to have the Flash plugin. The Flash tech for Video.js (since moved to a separate repository, videos/videojs-flash) only enables Video.js to play videos with Flash; it does not emulate Flash.

**Comment by hoodsy** [comment]
@mister-ben do you know of any way to play RTMP .flv _without_ using Flash?

**Comment by ROBERT-MCDOWELL** [comment]
https://github.com/Bilibili/flv.js

**Comment by mister-ben** [comment]
You can't use RTMP in a browser without Flash. It is possible to transmux FLV and play it with media source extentions, like flv.js does, but they're using HTTP(S) or occasionally websocket, not RTMP.

**Comment by ROBERT-MCDOWELL** [comment]
technically html5 video object is protocol agnostic, so everything is possible, depend the developers to do it

**Comment by gkatsev** [comment]
The problem is that browsers cannot access anything that isn't HTTP or WebSockets. So, RTMP isn't accessible outside of flash.

**Comment by ROBERT-MCDOWELL** [comment]
https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Live_streaming_web_audio_and_video
