### ISSUE TITLE
Removing all HTML created by VIDEO JS, need just the VIDEO element without any styling

### ISSUE THREAD

**Issue by subhranshudas** [videojs/video.js#5596]
Hi All,

I am trying to set up Video JS in a way that, i do not want any HTML created by VIDEO JS for controls, rather i will have my own own controls using player interface from Video JS.

I tried using 
`
 const videoJSOptions = {
        controls: false,
        autoplay: true,
        preload: 'auto',
        width: '100%',
        height: '100%',
      };
videojs('video_el_id', videoJSOptions);
`
But i still get a ton of HTML related to the Player controls.

Can i get only VIDEO element in the HTML rather than all the controls.

Thanks :)

**Comment by subhranshudas** [comment]
Was able to fix it using https://github.com/videojs/video.js/blob/master/docs/guides/options.md#children-1

But i had a query regarding the `width` option. Can we provide percentage instead of pixels to it? Seems to be not working.

**Comment by subhranshudas** [comment]
I am using "video.js": "6.8.0", tried with `fluid: true`, but does not fit the container.

**Comment by gkatsev** [comment]
`controls: false` option will disable the control bar, though, it may still create the DOM element.

> Can we provide percentage instead of pixels to it? 

The `width` option is equivalent to the `width` attribute, so, it does not accent a percentage. Only pixel values. You should use CSS if you want percentage values.

> I am using "video.js": "6.8.0", tried with fluid: true, but does not fit the container.

Do you want the player to fit the container? Then maybe [`vjs-fill` class (or `fill: true`](https://docs.videojs.com/tutorial-layout.html#fill-mode) if you're on the newest video.js, it's coming to 6.x soon) will work.

> i am able to override the style applied by VIDEO JS through *-dimensions class. Is there any way in options to tell video js not to add that class so that i don't need to have to do it through CSS??

You should be able to just add a class called `.video-js`, you don't need to look for anything specific.
You can also perhaps set the [`window.VIDEOJS_NO_DYNAMIC_STYLE = true`](https://docs.videojs.com/tutorial-skins.html#disabling-additional-style-elements).
