### ISSUE TITLE
Keep original resolution in fullscreen mode.

### ISSUE THREAD

**Issue by fenbitou** [videojs/video.js#5598]
## Description
When we try to see the video in full screen mode the video look quite blur.
How can I keep the video original resolution when the video player entered the full screen mode. It means do not scale the width/height to fit the screen width/height.

**Comment by gkatsev** [comment]
What do you mean keeping the original resolution? Do you mean changing the bitrate/resolution of the video when going fullscreen? If so, are you using an adaptive bitrate format that allows that? Like HLS?
If you're just playing back an mp4 there isn't much we can do.

For HLS and DASH, we should be doing that, I think in the latest version of Video.js, we automatically upscale upon fullscreen, but in older versions we tried to do a smoother transition, so, we may have upscaled in a few seconds.
