### ISSUE TITLE
Setting new source resets mute state

### ISSUE THREAD

**Issue by mimse** [videojs/video.js#5599]
## Description

Changing source on exists player resets the mute state.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Create a player with options autoplay set to 'muted'
2. Start video
3. Unmute video
4. Change source

### Expected
The next source should play unmuted

### Actual
Next source is muted

### Demo
https://codepen.io/anon/pen/aQWVzy

### Hint
https://github.com/videojs/video.js/blob/b5e6bdcf7a66b5189243e29698d6dec9ba378b7c/src/js/player.js#L1331

The previous state is saved but only restored if the test fails.

**Comment by mimse** [comment]
Any news here?

**Comment by gkatsev** [comment]
Haven't gotten much time to look at it, though, there are times when I can and can't reproduce. We generally re-use the tech (the video element) if both sources can be played on the same tech, as they should via an mp4, so, I would expect the native behavior to be present.

**Comment by mimse** [comment]
I worked around it by checking if player.muted() if false. Then I assume the user has toggled the muted button.
So before setting the new source, I set player.autoplay('any') to force playback with sound for the next source.
