### ISSUE TITLE
Disable full screen on double click

### ISSUE THREAD

**Issue by bantikyan** [videojs/video.js#5604]
I want to completely disable full screen functionality. I removed fullscreen button like this: 

```
videojs('videoPlayer', {
            controlBar: {
                fullscreenToggle: false
            }
        });
```

But on double click it still goes to full screen. How to disable double click?

**Comment by bcdarius** [comment]
The current `dblclick` handler doesn't take into consideration whether fullscreen toggle is disabled. It is on by default and there is currently no settable option to disable it. As of now, you could try and cancel out `dblclick` listener on tech.

```javascript
player.ready(function() {
 player.tech_.off('dblclick');
});

@gkatsev You think we should only fullscreen on double-click when fullscreen toggle button is enabled or is it better to have a separate option to turn fullscreen on double-click off?

**Comment by bantikyan** [comment]
Hi @bcdarius , I tried to cancel `dblclick` with tech, but it not work. I need some quick workaround. Can you suggest something else? Thanks

**Comment by bcdarius** [comment]
Removing `dblclick` listener from tech works for me https://output.jsbin.com/lugopuzaqa. Do you have a test _case?

**Comment by bantikyan** [comment]
Ok, I have figured it out. 
I have called `reset`  function, and have to remove `dblclick` listener after that.
Thank you @bcdarius

**Comment by gkatsev** [comment]
This is something we should have an option for. @OwenEdwards make a PR for it https://github.com/videojs/video.js/pull/5611
Though, I'm still not sure of the name and if it should be tied to hotkeys like https://github.com/videojs/video.js/pull/5571 since the videojs-hotkeys plugin does do both as well.

**Comment by asadmalik3** [comment]
> ```js
> dblclick
> ```
@bcdarius @gkatsev 
How to turn it on again? is there any method like this.jsPlayer['tech_'].on('dblclick')

**Comment by asadmalik3** [comment]
> The current `dblclick` handler doesn't take into consideration whether fullscreen toggle is disabled. It is on by default and there is currently no settable option to disable it. As of now, you could try and cancel out `dblclick` listener on tech (see below).
> 
> @gkatsev You think we should only fullscreen on double-click when fullscreen toggle button is enabled or is it better to have a separate option to turn fullscreen on double-click off?
> 
> ```js
> player.ready(function() {
>  player.tech_.off('dblclick');
> });
> ```

@bcdarius @gkatsev
How to turn it on again? is there any method like this.jsPlayer['tech_'].on('dblclick')

**Comment by gkatsev** [comment]
Please don't use that workaround. As of Video.js 7.5.0, we have an option to turn it off directly.

**Comment by elektronik2k5** [comment]
For whoever is looking for the right way to do this nowadays, here's the docs link: https://docs.videojs.com/tutorial-options.html#useractions.doubleclick

BTW, @gkatsev it looks like all the links with a dot in them are broken. The links on the page look like this, without the dot: https://docs.videojs.com/tutorial-options.html#useractionsdoubleclick, while the id has the dot: https://docs.videojs.com/tutorial-options.html#useractions.doubleclick

Looks like a bug in the docs generator.
