### ISSUE TITLE
on ipad, video can not auto-fullscreen and it's no use rotating screen when video is in fullscreen, it will out of fullscreen and pause

### ISSUE THREAD

**Issue by summerLoveqq** [videojs/video.js#5605]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

1. in ipad, auto-fullscreen is no use
2. when fullscreen and rotate screen, it will out of fullscreen and pause

videojs version: 7.2.2
browsers: weixin
no plugins

**Comment by gkatsev** [comment]
We haven't really tested with the wechat browser but we've definitely seen weirdnesses with it often. I think that they have their own special handling of the video element which causes issues with Video.js.
