### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 

### ISSUE THREAD

**Issue by Lynn0108** [videojs/video.js#5606]
## Description
I init a videojs instance and when I get a new source, I want to change the source. Unfortunately I get an error.

## Steps to reproduce
here are an example in jsbin.
https://jsbin.com/qusiwik/edit?html,output
1.init a videojs instance
2.change the source

### Expected
change video source

### Actual && Error output
source change failed and i get an error
![image](https://user-images.githubusercontent.com/25974463/48751337-d073ee00-ecbe-11e8-866b-7bf9d26922b8.png)

#### videojs
v7.3.0
#### browsers
chrome（I haven't tried in other browser）

Do I use wrong function? waiting for your anwser~~thx

**Comment by gkatsev** [comment]
Unfortunately, due to the way that Video.js works currently, if a type is not given and it cannot figure the type out from the URL, it cannot play it back. Adding a type as a source object (or working around it by adding `#.mp4` to the url makes it work. The source object approach is the preferred one.
```js
player.src({
  src: 'http://img-ys011.didistatic.com/static/didiglobal/do1_pcUZZjSG7vFlMbdr8fA6',
  type: 'video/mp4'
});
```

```js
player.src('http://img-ys011.didistatic.com/static/didiglobal/do1_pcUZZjSG7vFlMbdr8fA6#.mp4')
```

Hope this helps

**Comment by Lynn0108** [comment]
it works~thx

**Comment by gkatsev** [comment]
You're welcome.

**Comment by 4unkur** [comment]
This should be documented somewhere...

**Comment by Tapudp** [comment]
I tried to do this but now my video stops playing after one second of play. Please suggest something that I can do

**Comment by huangyuan0315** [comment]
"video.js": "^6.13.0"
  "videojs-contrib-hls.js": "^3.2.0"
"vue-video-player": "^5.0.2"

我已解决此问题

**Comment by codeshort** [comment]
It's working at this link, But why is it not working with the youtube link or google drive link?

**Comment by codeshort** [comment]
> It's working at this link, But why is it not working with the youtube link or google drive link?



> Unfortunately, due to the way that Video.js works currently, if a type is not given and it cannot figure the type out from the URL, it cannot play it back. Adding a type as a source object (or working around it by adding `#.mp4` to the url makes it work. The source object approach is the preferred one.
> 
> ```js
> player.src({
>   src: 'http://img-ys011.didistatic.com/static/didiglobal/do1_pcUZZjSG7vFlMbdr8fA6',
>   type: 'video/mp4'
> });
> ```
> 
> ```js
> player.src('http://img-ys011.didistatic.com/static/didiglobal/do1_pcUZZjSG7vFlMbdr8fA6#.mp4')
> ```
> 
> Hope this helps

**It's working at this link, But why is it not working with the youtube link or google drive link?**

**Comment by ParfectShot** [comment]
Hey, I am building a screen recordder app on electronjs. I record it in HLS format. The chunks are stored locally and are uploaded simultaneously. In my app I am building a video preview from the chunks stored locally. I have the path for `playlist.m3u8` file. I load the videopreview using the path of that file as `src` in videojs options.

I've specified the correct type ( `application/x-mpegURL` ) also. Still getting the error - `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media`.

Videojs version - 7.11.4
Chrome version - 87.0.4280.141 (Official Build) (64-bit)

**Comment by gkatsev** [comment]
@ParfectShot if you're loading a `file:///` path, it won't work. We must be able to make XHR requests. Make sure you have a local server you can hit.

**Comment by ranjbarreza** [comment]
> Hey, I am building a screen recordder app on electronjs. I record it in HLS format. The chunks are stored locally and are uploaded simultaneously. In my app I am building a video preview from the chunks stored locally. I have the path for `playlist.m3u8` file. I load the videopreview using the path of that file as `src` in videojs options.
> 
> I've specified the correct type ( `application/x-mpegURL` ) also. Still getting the error - `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media`.
> 
> Videojs version - 7.11.4 Chrome version - 87.0.4280.141 (Official Build) (64-bit)

I have the exact same issue!
