### ISSUE TITLE
not working double tap on video to fullscreen on mobile devices videojs 7.30

### ISSUE THREAD

**Issue by tecg87** [videojs/video.js#5609]
## Description
Hello,im havin issues with videojs 7.30 on desktop machines fullscreen works on double click but on mobile devices it doesnt work,only when i click the full screen window.
tryed multiple browsers (chrome,firefox,doplhin)
my config attached

i tried putting this script ( <script>var vid1 = videojs('player_1'); vid1.on('dblclick', function() { vid1.requestFullscreen(); }); vid1.on('dblclick', function() { vid1.exitFullscreen(); });</script> 	)
under the video id,but the video window freezez when i put it there,i'm sure its a noobish mistake but i've been stucked all day with this issue.
[index.txt](https://github.com/videojs/video.js/files/2605047/index.txt)

any help its appreciated
thanks in advance

**Comment by tecg87** [comment]
thanks,for replaying could you suggest a workaround for this inconvenience?

**Comment by OwenEdwards** [comment]
I doubt it's possible to work around this - at least on iOS, the Safari browser consumes a double-tap event as a zoom/un-zoom event on the page, so it isn't passed through to the page itself.

@tecg87 can you give any examples of where `dblclick` is passed to a web page by a mobile browser?

**Comment by tecg87** [comment]
hi Owen,
Thanks for replaying,my goal was to succeed in making the video player to go in fullscreen when double tap on mobile devices,maybe  i shouldn't use a dbclick event but something else. I've browsed a little from my mobile devices and visited sites that have videojs and tryied  on double tapping the video player ,didn't go in fullscreen automatically so i can assume its a normal function?
On my video i have the play button,clicking on it makes the video run,but after when double tapping nothing happens,is it possible at least to make the video stop/play on double tap because in this moment when double tapping nothing happens.
i was used with jwplayer that goes in fullscreen when double tapping on mobile devices.but i whant to start using videojs player for its huge potentiality.

thanks again.
regards.

**Comment by gkatsev** [comment]
You can probably implement it by listening to successive touchstart events that happen within a short duration and without a touchmove in between (yes, it's tricky). However, it seems that on mobile, more and more players are moving towards seeking forward and back when double tapping each side of the player, so, I'd be reluctant to add that in to Video.js by default.

**Comment by gkatsev** [comment]
Also, just realized that Video.js has a "tap" event that we generate when we think there's a tap, so, you could listen to two tap events, theoretically. Should make it slightly simpler then.

**Comment by tecg87** [comment]
thanks,i will try to figure it out how to listen to two tap events then.
Regards

**Comment by gkatsev** [comment]
I think we don't want this in Video.js by default.

**Comment by bigrck64** [comment]
Hey tecg87, I got the same question than you.
So, did you succeed to listen to double tap to make videojs go into fullscreen mode on Mobile ?
