### ISSUE TITLE
MPEG-DASH not loading (Error: CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)

### ISSUE THREAD

**Issue by passledevelopers** [videojs/video.js#5610]
## Description
Briefly describe the issue.
When attempting to load this MPEG-DASH manifest, the video fails to load and I get the error: MPEG-DASH not loading (Error: CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)

I have tried this in Chrome and Edge, it fails in both. This MPEG-DASH loads fine in other players.

The URL for the mpeg dash manifest is here: https://d3fhqzzxhz3oev.cloudfront.net/Passle/565d6ae1da69ad26f022aba3/MediaLibrary/Video/Transcoded/2018-11-21-16-22-15-649-sample/2018-11-21-16-22-15-649-sample_MPEG-DASH.mpd

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
I have created a JSFiddle here that you can see:
https://jsfiddle.net/Passle/myL5qdjr/1/

### Expected
The video should work fine. If you enter the video URL  on the videojs-contrib-dash test page it works 
https://videojs.github.io/videojs-contrib-dash/

### Actual
The video does not load. The player shows the replay button as if the video has actually played. Error shown in the console (in MS Edge) is CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED

### Error output
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.3.0
#### browsers
Chrome and Edge, maybe more
### plugins
No

**Comment by andreiucm** [comment]
The same problem is happening to me too. I run 7.4.1 version

**Comment by gkatsev** [comment]
@passledevelopers Thanks for your patience, looks like this is a DASH playlist with SIDX, which we recently added support for VHS 1.10 (https://github.com/videojs/http-streaming/pull/455). It has been merged into Video.js latest (https://github.com/videojs/video.js/commit/98e86ea235b719eb13763c4ed4f214d1d80afbb3) but there hasn't been a release done yet.
