### ISSUE TITLE
How to can show (visible) controls before start video?

### ISSUE THREAD

**Issue by ahmadshc** [videojs/video.js#5612]
Hello
im use videojs 7.3.0 and use preload attribute for my videos and resolution switcher plugin too
i need visible controls (time, volume, quality and more) before start video (like big play button)
i need visible big play button and controls together, i can visible big play button, but i cant visible controls
please help me if you can, i need solution

**Comment by gkatsev** [comment]
I don't think we have a good mechanism for this. You could work around it by adding the `vjs-has-started` class to the player.
