### ISSUE TITLE
how to use classes of videojs?

### ISSUE THREAD

**Issue by ilaipi** [videojs/video.js#5613]
hello, I don't know how to use the classes in the api docs e.g. FullscreenToggle, BigPlayButton , 

can't find any usage example .

can anyone give some examples?

I have new a instance:
```
import videojs from 'videojs';

    this.player = videojs(this.videoNode, {
      controls: true
    }, () => {
      console.log('onPlayerReady', this)
    });
    const FullscreenToggle = videojs.getComponent('FullscreenToggle');
    const fullscreenToggle = new FullscreenToggle(this.player);
    // and then how to deal with the fullscreenToggle?
```

thanks!

**Comment by misteroneill** [comment]
@ilaipi Most users do not need to use the component classes directly.

Component classes are most useful when heavy customization is required. You may not need to instantiate the `FullscreenToggle` component as you've done - by default, the `FullscreenToggle` component is automatically instantiated as a child of the `ControlBar` component (see: [Default Component Tree](https://docs.videojs.com/tutorial-components.html#default-component-tree)).

When instantiating a component directly, as you've done, you can add the component instance to another component as a child, using the [`Component#addChild` method](https://docs.videojs.com/component#addChild).

Overall, for advanced use-cases, the [Components guide](https://docs.videojs.com/tutorial-components.html#default-component-tree) is a great place to start.

Hope this helps!

**Comment by ilaipi** [comment]
@misteroneill thank you for your kind reply, I think I may need heavy customization and I will try.

But it seems [Components guide](https://docs.videojs.com/tutorial-components.html#default-component-tree)  don't show me how to add a Component instance to a Dom element, maybe I can't find it. [Component#addChild method](https://docs.videojs.com/component#addChild) this page only show me how to add one instance to another, but can't bind to a Dom element.

**Comment by ilaipi** [comment]
and I want to create one more controlBar and put on the top of the video.

![image](https://user-images.githubusercontent.com/1689135/49053682-133c4580-f22c-11e8-9757-fa53df7fa52c.png)

**Comment by Pong420** [comment]
Add a component to player before player created

```js
videojs.getComponent('Player').prototype.options_.children.splice(0, 0, 'FullscreenToggle');
```

or, add a component after player create

```js
const FullscreenToggle = videojs.getComponent('FullscreenToggle');
const fullscreenToggle = new FullscreenToggle(player);
player.addChild(fullscreenToggle, {}, 0);
```

For heavy customization

```js
const component = videojs.getComponent('component');

// create a custom control container
class customControl extends component {
  constructor(player, options) {
    super(player, options);

    this.addClass('vjs-custom-control');
  }
}

// register the container
videojs.registerComponent('customControl', customControl);

// set child component of the container
customControl.prototype.options_ = {
  children: [
    'PlayToggle',
    'FullscreenToggle',
    'Registered_Component',
    // you could also use an object and pass options to the component
    {
      name: 'Registered_Component'
      // option for this component
    }
  ]
};

// assign custom control to player
videojs.getComponent('Player').prototype.options_.children.splice(0, 0, 'customControl');
```

**Comment by gkatsev** [comment]
You don't need to splice the component into the children array of options_. In fact, that's actively discouraged.

Instead, you can just add it as an option to the player or a component, either under children, or even as a top-level. The children option can also be an array in which case it'll only initialize the items in that array. The [using options](https://docs.videojs.com/tutorial-components.html#using-options) section of the components guide has info about it.

But basically:
```js
// add myComponent to the player automatically
var player = videojs('foo', {
  myComponent: {}
});

// add myComponent to the player automatically
var player2 = videojs('foo', {
  children: {
    myComponent: {}
  }
});

// create a player with a control bar that only has myComponent
var player3 = videojs('foo', {
  controlBar: {
    children: ['myComponent']
  }
});
```

**Comment by Pong420** [comment]
Thanks for your correction. 
But seems not inconvenient if i want to insert a component.
Just like [videojs-settings-menu](https://github.com/videojs/videojs-settings-menu). User need to list all existing component.

```js
var player = videojs('videojs-settings-menu-player', {
  playbackRates: [0.5, 1, 1.5, 2],
  controlBar: {
    children: {
      playToggle: {},
      muteToggle: {},
      volumeControl: {},
      currentTimeDisplay: {},
      timeDivider: {},
      durationDisplay: {},
      liveDisplay: {},

      flexibleWidthSpacer: {},
      progressControl: {},

      settingsMenuButton: {
        entries: ['subtitlesButton', 'playbackRateMenuButton']
      },
      fullscreenToggle: {}
    }
  }
});
```

If plguin already splice the button into children array, above options and can be removed

```js
var controlBarChildren = videojs.getComponent('controlBar').prototype.options_.children;
var indexOfFullscreenToggle = controlBarChildren.indexOf('fullscreenToggle');

if (indexOfFullscreenToggle !== -1) {
  controlBarChildren.splice(0, indexOfFullscreenToggle, 'settingsMenuButton');
} else {
  videojs.log.warn('fullscreen toggle does not exists');
}
```

**Comment by gkatsev** [comment]
Make sure it's an array ant not an object or else it may create extra items.

You can provide an index when you call `componet.addChild()` but you're correct that we need to provide a better way of configuring it.

It's just that the `prototype.options_` property, while technically publicly available, is private by convention and therefor should be avoided.

**Comment by Pong420** [comment]
thanks
