### ISSUE TITLE
HLS - create a buffer of chunks

### ISSUE THREAD

**Issue by darkdrgn2k** [videojs/video.js#5615]
When playing a HLS live stream

We have an issue where the backed is not as responsive as it should be when providing the m3u8 file (File may not be updated for a chunk or two, but then update fine)

My question is

- is there a way to have it download the last 3 chunks but start playing 3rd last chunks (so the second last and last chunk is a buffer)

**Comment by forbesjo** [comment]
You can back off from the live edge by setting current time farther back on the first play. We don't really have an API for configuring the start position for a live stream

**Comment by darkdrgn2k** [comment]
> you can back off from the live edge by setting current time farther back on the first play.

How would one set a relative position in time?

**Comment by forbesjo** [comment]
You could do: 
```js
player.on('firstplay', function() {
  var chunkSize = 10;
  var startPos = player.seekable().end(0) - (2 * chunkSize);
  player.currentTime(startPos);
}
```

**Comment by gkatsev** [comment]
`firstplay` is deprecated, and non-standard. You could do `player.one('play', ...)` instead.

**Comment by darkdrgn2k** [comment]
Durring live a live stream  `.seekable().end(0)` is always 0 but `.currentTime()` keep increasing from 0

is that correct?
