### ISSUE TITLE
Videojs still fetching live stream when video player has paused

### ISSUE THREAD

**Issue by tonyjhang** [videojs/video.js#5617]
## Description
In order to reduce browser loading, I do a function when the hls live stream has retried playlist too many times it will pause. But it seems videojs still retry the hls source when I paused the player, is there any solution I can stop retrying the hls source if i paused the video?

Issue like these link below:
<https://jsfiddle.net/1nsmptfc/2/>
<https://imgur.com/a/yxcxLZD>

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.play the live streaming and pause it
2.open developer tools
3.see "Network"

**Comment by gesinger** [comment]
Hey @tonyjhang , we added a troubleshooting entry to explain what might be going on in this case: https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md#network-requests-are-still-being-made-while-paused

We don't currently have a way of pausing the manifest refreshes, as they are usually small requests and help to keep sync with the stream.
