### ISSUE TITLE
createEl not accessible outside dev mode

### ISSUE THREAD

**Issue by ldoguin** [videojs/video.js#563]
Hi,

I m trying to adapt the following rangeslider plugin: https://github.com/arthurian/Catool-videojs-plugins/
So far I made it work only using video.dev.js: https://github.com/ldoguin/Catool-videojs-plugins
Now it looks like I cannot redefine createEl function for my custom objects when I m using the minified version video.js. Is this a bug or a feature? If it's a feature, any recommendation on how to make it work?

Thanks!

**Comment by heff** [comment]
This is fixed by #1940 and will be available in 5.0.
