### ISSUE TITLE
Intermittent No Compatible Source / Src Not Supported

### ISSUE THREAD

**Issue by iq-dot** [videojs/video.js#5631]
## Description
I seem to get issues on our remote logs regarding:

No compatible source was found for this media

or

The media could not be loaded, either because the server or network failed or because the format is not supported

However when I try to replicate this on my end, the video plays and it works fine. Most of these videos are video/mp4 (h.264/aac)

Here is a sample video source:

https://secure-cf-c.ooyala.com/Z0YzVqZjE6bKEu6fN4_pKbhkpolSFDfe/DOcJ-FxaFrRg4gtDEwOjFsaTowODE7WX

I have seen errors happening mainly on Chrome, majority of it on Mobile. Though I haven't been able to reproduce it but I have seen someone else get the error.

I am a bit confused and not sure where to pinpoint the error. I use videoJS playlist to manage it and these errors are quite frequent.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
It is intermittent but generally when it happens:

1. Load a page with the video
2. The error may occur.

### Expected
It should be consistent and work.

### Actual
Intermittent, some people have issues, others don't.

### Error output
No compatible source was found for this media

or

The media could not be loaded, either because the server or network failed or because the format is not supported

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.3
#### browsers
Chrome, some IE Edge

Some detailed device info we captured:

userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15',
platform: 'Linux x86_64',
vendor: 'Google Inc.',
version: '5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15'

#### OSes
what platforms (operating systems and devices) are affected?
Majority of it is iOS
### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-playlist
videojs-overlay
videojs-http-streaming
spotx-sdk

**Comment by gkatsev** [comment]
How are you loading the source into the player? I've tried loading it as type video/mp4 and it's been working great so far.

**Comment by iq-dot** [comment]
I am also doing the same but sometimes on mobile it will throw the error. I
have only been able to replicate once but logs shows that it happens to
others.

I am unsure if there is anything such as prematurely trying to start the
video before enough data is retrieved or any browser issues?

**Comment by gkatsev** [comment]
Are you autoplaying the video? Have an example embed code?
