### ISSUE TITLE
Dealing with time

### ISSUE THREAD

**Issue by benjisympa** [videojs/video.js#5641]
Hi, thanks for your work !

I try basic functionality, I can play a video but when I try to change the currentTime as you describe in https://docs.videojs.com/tutorial-player-workflows.html there is no effect, if I do an alert just after I got 0.
I also try to see the duration and the remainingTime of the video and if I alert this, I got Nan.
Do you know what is the problem ?

Thanks very much.

**Comment by gkatsev** [comment]
You probably want to listen to the `loadedmetadata` event as beforehand, none of the information may be available.
Do you have your code snippet available?

**Comment by gkatsev** [comment]
Glad to hear that loadedmetadata fixed the issue.

I don't think I've heard of anything like that before. Would you mind opening a new issue with a reduced test case?

Going to close this issue since the original question has been resolved.
