### ISSUE TITLE
videojs.off() removes all internal event listeners, not just the ones the user has added

### ISSUE THREAD

**Issue by KevinBrogan** [videojs/video.js#5648]
## Description
When calling the off function with no parameters, all of videojs's components lose their event notifications as well, resulting in the controls no longer updating.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
 videojs(videoElement,{controls: true},function(){ this.off(), this.src('videoFile.mp4'); this.play(); })

### Expected
A video file get loaded and begin playing, with the user interface and controls staying in sync with the video status as you control the video.

### Actual
Videojs interface stops updating.

### Error output
no error

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.3
#### browsers
chrome
#### OSes
windows 10
### plugins
no plugins

**Comment by gkatsev** [comment]
This is currently the indented behavior. There currently is no distinction between "internal" Video.js events and "external" user events. `component.off()` is discouraged outside of the `dispose` handler.

**Comment by mrieck** [comment]
If this is expected behavior, then why does changing the player source clear all the user events but keep the internal events?  For example this stops my timeupdate from working without breaking the progress bar:
```
                player.ima.changeAdTag(adTagUrl );
                player.ima.requestAds();
                player.src({
                    src: masterSrc,
                    type: 'video/mp4'
                });                    
                player.load();    
                player.play();         
```
So I try to do player.off('timeupdate'); so I can re-add my event, but then the progress bar is broken because videojs clears the internal events.  Is there a way to keep both my events and the internal events  working when changing src?

**Comment by mrieck** [comment]
After looking at it again, my player seems to be in a strange state after changing source.  

If I seek to another position, or pause/play 500 ms later, my timeupdate starts to fire again.  Is there some bad state videojs gets put in when you change the source programmatically and call play?  It also seems that the spinner is on the player loading even though the new video is playing fine.

**Comment by gkatsev** [comment]
@mrieck changing a source shouldn't clear user events unless something manually clears out events on source change. I'm not sure I've seen an issue as you describe, would you mind making a new issue with steps to reproduce, preferably with a reduced test case? Thanks!

**Comment by gkatsev** [comment]
@kevinbrogan there's currently no way to clear out just user events beyond disposing and re-creating the player.
