### ISSUE TITLE
vjs-ended class stays on container element after scrubbing video location until play

### ISSUE THREAD

**Issue by KevinBrogan** [videojs/video.js#5654]
## Description
When a video ends and the vjs-ended class is added to the container element, I would expect that when changing the video position with the scrub bar, moving from the end of the video to any other position, that the vjs-ended class is removed. Instead, the vjs-ended class stays until the video is unpaused from its new position.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play a video to the end
2. move the scrub bar some where that isn't the end

### Expected
I expect the vjs-ended class to be removed since the video is no longer at the end, just as it is removed from the play/pause/replay button.

### Actual
The class stays until play is resumed.

### Error output
no errors

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.3
#### browsers
chrome
#### OSes
windows
### plugins
none

**Comment by gkatsev** [comment]
Can confirm this happens.

**Comment by gkatsev** [comment]
I have a fix for this here https://github.com/videojs/video.js/pull/5728
