### ISSUE TITLE
Muted sound play on ios

### ISSUE THREAD

**Issue by Mapteg34** [videojs/video.js#5659]
## Description
Muted video work fine in all browsers, but in ios - played with sound...

## Steps to reproduce
1. Open https://clothia.malahov-artem.ru/test.php in not ios - video play, sound no - ok
2. Open https://clothia.malahov-artem.ru/test.php in ios - video play, sound play - bad

Link - sample page with small standart code, you can try it.

How we can fix this problem?

**Comment by mister-ben** [comment]
I tried this in Safari on iPad and it was muted. I don't see any reason audio would play. Are you seeing this in a particular iOS version?

**Comment by Mapteg34** [comment]
> I tried this in Safari on iPad and it was muted. I don't see any reason audio would play. Are you seeing this in a particular iOS version?

Sefari 12.1 iPhone. iOS 12.1

**Comment by AntaliaTasha** [comment]
I'll make a small remark. The sound is not plays by default, but it happens on iOS if you turn it on in the video player. So, we have the following steps:
- wait until the video starts playing
- tap on the volume control icon or move the volume slider (decrease - increase)
- video plays with sound

iPhone7 iOS 12.1.1, iPad (4th generation) iOS 10.3.3, Safari browser in both cases.

**Comment by AntaliaTasha** [comment]
[Link to the test video - problem reproduced in Safari 12.1. iPhone 7. iOS 12.1](https://vimeo.com/user95221651/review/317818477/e475ac67aa)
