### ISSUE TITLE
What do I have to do to disable autoplay????

### ISSUE THREAD

**Issue by ttly20** [videojs/video.js#5660]
I use videojs7 in vue,My videojs always play automatically, the same in chrom, but I don't need this feature.
Here is the code:
![image](https://user-images.githubusercontent.com/20431764/49663595-2a7bfe00-fa8a-11e8-923a-691da5ad5ce3.png)
Issues:
1.I added :data-setup="{autoplay:false}" or autoplay="false" to the video tag, and videojs will still play automatically.
2.I added autoplay: false when video was created, and it will still play automatically!
3. And why  is my player interface messy?
![image](https://user-images.githubusercontent.com/20431764/49663417-8abe7000-fa89-11e8-96aa-20a31cc097de.png)
4.please help me, thanks.

**Comment by gkatsev** [comment]
The `autoplay` attribute on the video element is a boolean attribute, meaning when it's present the value is true and when it isn't, the value is false. This means that even though you have `autoplay=false` in there, you are still enabling autoplay. This attribute also likely overrides the option you pass to `videojs()`. You should just remove both mentions of autoplay from the video element and the options. The default is always not to autoplay.
The reason for the UI not looking proper is likely because the Video.js CSS hasn't loaded properly.

**Comment by ttly20** [comment]
> The `autoplay` attribute on the video element is a boolean attribute, meaning when it's present the value is true and when it isn't, the value is false. This means that even though you have `autoplay=false` in there, you are still enabling autoplay. This attribute also likely overrides the option you pass to `videojs()`. You should just remove both mentions of autoplay from the video element and the options. The default is always not to autoplay.
> The reason for the UI not looking proper is likely because the Video.js CSS hasn't loaded properly.
I tried to remove these options one by one, but they didn't work. I really don't know where to delete them.
Here is is the code:
![image](https://user-images.githubusercontent.com/20431764/49666050-c65d3800-fa91-11e8-9883-19efbc0e7588.png)

**Comment by gkatsev** [comment]
What do you mean "doesn't work"? The screenshot you provided should be fine. Can you provide a reduced test case? It's hard to debug without a live example.

**Comment by ttly20** [comment]
@gkatsev 

> What do you mean "doesn't work"? The screenshot you provided should be fine. Can you provide a reduced test case? It's hard to debug without a live example.

[details.zip](https://github.com/videojs/video.js/files/2658420/details.zip)

This is code filem,it is a vue2.0 SPA file.thanks.

**Comment by gkatsev** [comment]
Unfortunately, I'm not familiar with Vue, can you provide a live example on something like https://codesandbox.io?

**Comment by ttly20** [comment]
@gkatsev 
ok
This is demo link:https://codesandbox.io/s/kyym6kmpo

**Comment by gkatsev** [comment]
OH, just realized you had a call to play in your ready handler (line 44)
```
, function () {
      this.play()
}
```
Removing that will prevent it from autoplaying.

**Comment by ttly20** [comment]
@gkatsev 
OMG,It turned out to be here，thank you every much.

**Comment by gkatsev** [comment]
You're welcome!
