### ISSUE TITLE
How can video. js play the file ending with. flv? Can you give an example? Thank you

### ISSUE THREAD

**Issue by lliiuu** [videojs/video.js#5667]

**Comment by gkatsev** [comment]
Hi, you need to make sure to include videojs-flash and make sure that the player is sized large enough -- most browsers will block flash if the size is smaller than about 400x300. In addition, most browsers make it really hard to get flash working, so, I would highly recommend transcoding the flv file into an mp4.

Here's a simple example of all that's necessary
```html
<html>
<head>
<link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
<style>
  .video-js {
    width: 1280px;
    height: 720px;
  }
</style>
</head>
<body>
<video-js controls data-setup="{}">
  <source src="https://example.com/video.flv" type="video/flv">
</video-js>

<script src="https://unpkg.com/video.js/dist/video.min.js></script>
<script src="https://unpkg.com/videojs-flash/dist/videojs-flash.min.js></script>
</body>
</html>
```

**Comment by davestewart** [comment]
Thanks for the example! Great timing and works great.

For any HTML noobs, the last two script tags are missing quotes.

```html
<script src="https://unpkg.com/video.js/dist/video.min.js"></script>
<script src="https://unpkg.com/videojs-flash/dist/videojs-flash.min.js"></script>
```

**Comment by gkatsev** [comment]
Oops, been making that mistake a lot lately. Updated my comment, thanks :)
