### ISSUE TITLE
TextTracks not working with audio-only encoded streams

### ISSUE THREAD

**Issue by mparisi76** [videojs/video.js#5672]
Hello. We have recently upgraded to the latest and greatest videojs. I'm seeing an issue with TextTracks where if we are only encoding audio and no video, the cuechange event doesn't seem to ever fire. Is it by design that a video stream is required for TextTrack functionality?

We are using Wirecast to encode AAC Stereo at 96 kbits 44,100 kHz

Perhaps there is some additional setting or configuration that I have missed?

Any help would be greatly appreciated.

Thank you.

**Comment by gkatsev** [comment]
How are you including the text track? Also, wirecast generally means that this is a livestream, timing in a livestream are a bit different and it's probably a timing mismatch between the livestream and the tracks.

Do you have a live reduced test case we can take a look at?

**Comment by mparisi76** [comment]
The ID3 tags are added on the FMS side. I'm not exactly sure without digging into the code. I do know that streams with video data do work. Here is a current live stream which should have an injected ID3 tag every 10 seconds. The data should include "Overlay Command"

https://mp120547release.cdn.mediaplatform.com/mp-player-wc/debug.html

Let me know your thoughts. Thanks.

**Comment by gkatsev** [comment]
Can you even have id3 tags inside of an audio stream? @videojs/playback?

Thanks for the example!

**Comment by mparisi76** [comment]
I do recall that in the past, when I was using videojs-contrib-hls, I modified the code there so that I was able to get ID3 tags in the player.

**Comment by mparisi76** [comment]
Just to be clear, this is not an audio format, this is HLS - m3u8 with just audio data and no video data.

**Comment by mparisi76** [comment]
@gkatsev Any updates on this? We have issues with clients and we may need to roll back to videojs 5, which I do not want to do under any circumstance.

**Comment by ldayananda** [comment]
@mparisi76 would you mind providing a new example link? If this also happens with VOD content, then that would be even better for us to debug with. Thanks!

**Comment by mparisi76** [comment]
Unfortunately, we do not preserve the id3 injections in VOD content. I have set up a live stream and I will keep it running for you for a few hours.

This link contains the newest videojs library. It will not detect the ID3 injections:
http://services001.mediaplatformdev.com/mp-player-wc/debug.html

This link is using the old videojs 5 with video-contrib-hls (which I modified to work):
http://services001.mediaplatform.com/mp-player-wc/debug.html

Much appreciated!

Matt

**Comment by ldayananda** [comment]
@mparisi76 just to clarify, for the newer setup(with VHS) are you also applying the modification you had been using for videojs-contrib-hls?

If not, we appear to not be adding the ID3 cues to the textTrack at all for audio-only streams currently. Thanks for reporting the issue, now we know there is demand! We'll prioritize adding support for ID3 parsing from audio-only streams in VHS. 

Here's an issue you can follow: https://github.com/videojs/http-streaming/issues/130

**Comment by mparisi76** [comment]
Thanks @ldayananda.

We had forked videojs-contrib-hls in the past for a couple reasons - this being one of them, but I am not running forked videojs code now and I don't want to have to modify the videojs code directly..

I will follow that closely. Do you have a target release date? I need to figure out if it makes sense to apply the fix temporarily until you guys release it.

**Comment by ldayananda** [comment]
We currently don't have an estimated date. One way to get it in faster would be to submit a PR to [VHS](https://github.com/videojs/http-streaming) with a fix and provide sample content to test with(we have very little audio-only content with ID3). That said, I would not count on a release before January.

**Comment by mparisi76** [comment]
Hello all and Happy New Year!! I wanted to revisit this issue and see if anyone has had a chance to look at it? If not, I might try with a PR.

**Comment by ldayananda** [comment]
Happy New Year! As it stands we haven't gotten a chance to look at this yet. Please feel free to try out a PR.

If you run into trouble, you can reach us via the [video.js slack](http://slack.videojs.com/) on the #playback channel

**Comment by forbesjo** [comment]
The fix for this issue is in VHS 1.8.0 (https://github.com/videojs/http-streaming) and should get into video.js soon

**Comment by gkatsev** [comment]
This has been merged and published already.
