### ISSUE TITLE
Data-setup not Working

### ISSUE THREAD

**Issue by cdanielgomes** [videojs/video.js#5678]
## Description
data-setup is not working right. In the link i have an attribute data-setup  that include autoplay, muted and the video does not start. However with attributes autoplay and muted the video runs correctly.
https://jsfiddle.net/6v7k8jz2/ - with data-setup

https://jsfiddle.net/t2hL3w1n/ - without data-setup

## Results
first example does not start automatically, the second does

### Expected
in both cases the video should start automatically 

### Actual
first example does not start automatically, the second does

#### videojs
7.3.0 but with the current version in the repo this happen too

#### browsers
only tried in chrome 70
#### OSes
I am using Ubuntu 18.10 LTS

**Comment by gkatsev** [comment]
We do have this issue for autoplay with chrome https://github.com/videojs/video.js/issues/5581
We hope to investigate it soon.

**Comment by cdanielgomes** [comment]
I know, but i just tried with other values in data-setup and they do not work. I just used autoplay as an example. Autoplay work as an attr outside of data-setup. But with both it does not work.
https://jsfiddle.net/6v7k8jz2/1/
Here i removed the autoplay and just let controls and fluid in data-setup... it does not work

**Comment by gkatsev** [comment]
Your first example above (https://jsfiddle.net/6v7k8jz2/) does create the player, it just doesn't autoplay it. The second example (https://jsfiddle.net/t2hL3w1n/) is just a plain video element. Video.js is on the page but Video.js isn't used.
In your last example, the data-setup has malformed JSON, if it is fixed, the player is created correctly: https://jsfiddle.net/6v7k8jz2/2/

**Comment by cdanielgomes** [comment]
ok, that was  my mistake. So this only have connection to the malfunction of autoplay...
Thanks
One more thing, i just updated chrome to version 71 and autoplay works correctly

**Comment by gkatsev** [comment]
If autoplay is fixed in chrome 71, that's great news. It's definitely possible that chrome did something in chrome 70 that interacted badly with what we do.

**Comment by cdanielgomes** [comment]
I think that i did not make mistakes now so if someone's want to check with chrome version 71, i used this: https://jsfiddle.net/2mueqs0x .

**Comment by gkatsev** [comment]
Closing this. We're continuing any autoplay related discussion in #5233.
