### ISSUE TITLE
videojs 7 requirejs js error: Script error for: global/window

### ISSUE THREAD

**Issue by lanxan** [videojs/video.js#5680]
## Description
package with requirejs make errors.
```
Uncaught Error: Script error for: global/window
Uncaught Error: Script error for: global/document
```

my mainConfigFile like this

```
requirejs.config({
    paths: {
        order: "js/order",
        videojs: "js//video",
        qualitylevel: "js/videojs-contrib-quality-levels", 
         ....
    },
    shim: {
        qualitylevel: {
            deps: ['videojs']
        }
    },
    map: {
        '*': {
            "video.js": "videojs"
        }
    }
}
```

### Error output
```
require.js:8 Uncaught Error: Script error for: global/document
http://requirejs.org/docs/errors.html#scripterror
    at B (require.js:8)
    at HTMLScriptElement.onScriptError (require.js:30)
require.js:8 Uncaught Error: Script error for: global/window
http://requirejs.org/docs/errors.html#scripterror
    at B (require.js:8)
    at HTMLScriptElement.onScriptError (require.js:30)
```

## Additional Information
I try to add something in map, like this
```
map: {
    '*': {
        "video.js": "videojs",
        'global/window': window,
        'global/document': window.document
    }
}
```
but error message become ``` require.js:7 Uncaught RangeError: Maximum call stack size exceeded```

#### videojs
7.3.0
#### browsers
chrome 71.0.3578.98 
#### OSes
macOS Mojava 10.14.2

**Comment by Neroxiezi** [comment]
Hi,I also encounter such a problem, how to solve it?

**Comment by lanxan** [comment]
@Neroxiezi 
Would you tell more detail? Thank you.
I tried some case, If I didn't modify defined function, the key word 'global/window' still make error.

If I add two file into the config
```
window: "js/window.js"
document: "js/document.js"
``` 

and change define like this
```
define(['window', 'document'], function(window, document) {
    factory(window, document);
});
```
videojs will be not defined.

**Comment by Neroxiezi** [comment]
@lanxan 
![image](https://user-images.githubusercontent.com/11400329/51324422-a44dd100-1aa5-11e9-8627-4699bb06e368.png)

Hello, as shown in the figure above, I created a new global directory on the same layer as my requirejs, and then I called it as follows


![image](https://user-images.githubusercontent.com/11400329/51324531-eecf4d80-1aa5-11e9-9c22-75888442e623.png)

**Comment by lanxan** [comment]
@Neroxiezi 
Thx for your help.
Unfortunately, it is not work for me.

I still use verson 6 and keep looking for solution.
Thank you again.

**Comment by Jonastt** [comment]
@lanxan Did you ever find a solution to this? I have a similar issue.

**Comment by lanxan** [comment]
> @lanxan Did you ever find a solution to this? I have a similar issue.

No, I still use version 6.
Sorry for that.

**Comment by jatyson** [comment]
This is working for me, not confident if it's the right way to do it though.  

```
define('global/window', [], () => {
  return window;
});

define('global/document', ['global/window'], (window) => {
  return window.document;
});

require(scripts, (videojs: any) => {
  window.videojs = videojs;
  // any other initialization you want here
});
```

**Comment by gkatsev** [comment]
@jatyson that looks like a fine workaround.

Unfortunately, we don't really use requirejs ourselves, though, I'm not exactly sure why it stopped working. Theoretically, rollup should've configured this properly but maybe there's a bug or something. I'm not sure.

**Comment by lanxan** [comment]
@jatyson It is working for me. Thank you for you solution.

**Comment by mafar** [comment]
The proposes way is as following:
create 2 files , see below then set requirejs.config paths.
These files dont need to be in global folder, just place them where u see fit

1. document.js
1. window.js
```js
// document.js file
define('global/document', ['global/window'], function (window) {
return window.document;
});
```
```js
// window.js file
define('global/window', [], function () {
return window;
});
```
then set **requirejs.config** =>  paths
```js
requirejs.config({
    paths: {
           'global/window': './path_where_you_placed/window',
           'global/document': './js/path_where_you_placed/document'
    }
});
```

**Comment by navanshu** [comment]
Thanks this has been a great healp

**Comment by AwokeKnowing** [comment]
this is honestly super annoying. and there is zero reason for it.  the reason it happens is because those dummy packages for window and document were added for npm code to TEST videojs server side (where there is no window/document).  they should not end up in the actual release for browser.

**Comment by AwokeKnowing** [comment]
https://github.com/videojs/video.js/blob/main/rollup.config.js#L71
https://github.com/videojs/video.js/blob/main/src/js/video.js#L6
