### ISSUE TITLE
Track window movement to recheck for touch support after player initialization

### ISSUE THREAD

**Issue by miguelpduarte** [videojs/video.js#5683]
## Description
(See videojs/video.js#2999 and discussion in #5663)
Add window tracking so that whenever the window changes monitor the touch support check is redone, so that applying the `vjs-touch-enabled` is dynamic and can change after player creation.

## Steps to reproduce
1. Open a website using video.js that has different styling for desktop and mobile devices, using the `vjs-touch-enabled` CSS class (see Issue and PR mentioned above)
2. Drag the window to a screen that has the opposite touch support (from a monitor that supports touch to another that does not, or vice-verse)

### Expected
The styling of the page would change upon the window switching monitor.

### Actual
Due to the check not being performed again, the page stays the same.

### Error output
No errors would be output.

**Comment by gkatsev** [comment]
I'm going to close this. It's probably not worth doing.
