### ISSUE TITLE
player fullscreenchange firing twice

### ISSUE THREAD

**Issue by nackd** [videojs/video.js#5685]
In browsers that support the unprefixed fullscreen API (FF 64+ GC71+), the fullscreenchange event is firing twice every time fullscreen is toggled.

https://jsfiddle.net/jbrhq4s1/1/

**Comment by gkatsev** [comment]
This is a side-effect of using `alert()`. The alert brings the element out of fullscreen causing the second fullscreenchange event to trigger.
If you change the alert to a console.log, as in this example https://jsfiddle.net/jbrhq4s1/2/, you will only get one `fullscreenchange` event.

Hope that helps.

**Comment by nackd** [comment]
No it's not a side effect, it also happens with console.log.

**Comment by gkatsev** [comment]
I only see a single console.log event for each time the fullscreen toggle button is pressed.

**Comment by gkatsev** [comment]
Interesting, just tried it in Firefox, I can reproduce it there but can't reproduce it in my version of chrome.

**Comment by nackd** [comment]
Funny. Is that Chrome 71 or later, @gkatsev?

**Comment by gkatsev** [comment]
I was on chrome 70, I upgraded to 71 and can reproduce it in chrome as well now.

**Comment by nackd** [comment]
BTW, in case this helps others, I took advantage of the two events coming from different sources and having some different properties to workaround this by adding this code to the top of the event handler in our product:

```javascript
    if (event.composed) {
      // Workaround events firing twice
      return;
    }
```

In unaffected browsers the rest of the event handler still runs and in the affected ones it runs once.

**Comment by gkatsev** [comment]
Looking at it more, this only worked previously by accident. Elements fired prefixed `fullscreenchange` events, so `webkitfullscreenchange` still fired. So, had we been listening to `webkitfullscreenchange` we would've been bit by this previously as well.
Chrome 71 unprefixed the fs API: https://bugs.chromium.org/p/chromium/issues/detail?id=383813

**Comment by gkatsev** [comment]
It works in Chrome but has some issues in firefox and ie11...

**Comment by gkatsev** [comment]
Ok, I think I have it working across all browsers now in that same PR
