### ISSUE TITLE
I can't play live rtmp stream while playback stream is ok，FLASH: rtmpconnectfailure

### ISSUE THREAD

**Issue by cucumbersunny** [videojs/video.js#5691]
## Description
I have imported all plugins and only live rtmp stream can't play with error 'FLASH: rtmpconnectfailure', I use Wireshark captured the tcp datagram and compare with normal datagram, and the same steam can play with FlashMediaEncoder2.2 while failing with video.js. The datagram shows that it's my client the one do disconnecting. The only difference between woking datagram and failing datagram  is that the normal one  without a '/'.
![image](https://user-images.githubusercontent.com/27407901/50069776-82430380-0206-11e9-9874-8c24940f9bb8.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
The rtmp stream is as follow:
options: {
 sources: [
{
type: "rtmp/flv",
src: 'rtmp://10.100.14.38:1935/live/&XIAOYUANTEST333_0_2?code=4231422736'
}
],
techOrder: [ 'html5', 'flash']
}``

### Error output
FLASH: rtmpconnectfailure

## Additional Information
The big play button has shown and after I click the button the error info shows. I have  also tried autoplay.
### versions
"video.js": "^7.3.0",
 "videojs-contrib-hls": "^5.15.0",
"videojs-flash": "^2.1.2",
#### browsers
Chrome

**Comment by mister-ben** [comment]
The query string should be part of the connection URL rather than the stream name, i.e before the `&` separator. Try this:

rtmp://10.100.14.38:1935/live?code=4231422736&XIAOYUANTEST333_0_2

**Comment by cucumbersunny** [comment]
> The query string should be part of the connection URL rather than the stream name, i.e before the `&` separator. Try this:
> 
> rtmp://10.100.14.38:1935/live?code=4231422736&XIAOYUANTEST333_0_2

Still not wok and this time get 'RTMP	516	Handshake C2|connect('live?code=4231425040')', the work url is 'rtmp://50.226.99.201:1936/playback/ZMD13KVGD000009_0?code=rvprhen28cgei9vktt90e83rk4' and tcp datagram show just 'Handshake C2|connect('live')'
┭┮﹏┭┮

**Comment by cucumbersunny** [comment]
I'am very sure the url is usefulo(╥﹏╥)o
![image](https://user-images.githubusercontent.com/27407901/50075401-d86d7200-0219-11e9-913d-68f4fa984ad7.png)

**Comment by misland** [comment]
@cucumbersunny hi,do you solve this question eventually?I meet the same question you have.
另外，哥们应该也是中国人吧:)

**Comment by xiao-ma-nong** [comment]
解决了吗同志们

**Comment by cucumbersunny** [comment]
要不就是hls调用的位置不对要不就是后端流问题，插件安装顺序也有影响



发自我的iPhone


------------------ Original ------------------
