### ISSUE TITLE
"No compatible source was found for this media." while playing AWS S3 signedurl with videojs.

### ISSUE THREAD

**Issue by joe455** [videojs/video.js#5696]
## Description
"No compatible source was found for this media." while playing AWS S3 signedurl with videojs.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. get AWS s3 signed url
2. try to play using videojs libarary

### Expected
video should play

### Actual
"No compatible source was found for this media."

### Error output
"No compatible source was found for this media."

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs latest
what version of videojs does this occur with?
#### All browsers
what browser are affected?
#### Windows
what platforms (operating systems and devices) are affected?
### videojs-markers
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
I can play a presigned MP4 URL without problems. Do you have a reduced test case with an example URL?

**Comment by rbokel** [comment]
Seeing this as well for hls urls. 
It seems like the GET parameters are cut off from the video url somewhere. 
They contain what makes the url "signed" 

Original url
https://[some video]?AWSAccessKeyId=[some key]&Expires=[some timestamp]&Signature=[some signature]

Url used by the tech
https://[some video]

**Comment by weiluri** [comment]
I get it with .wav .avi format as well

**Comment by Jogii** [comment]
Same here. Recently i fount the same error while playing .avi extention files with the latest 7.11.1 videojs version. How to fix the same? @gkatsev tagging you for your attention.

**Comment by mister-ben** [comment]
Browsers don't support AVI. MP4 with H.264 and AAC is the most widely supported format.
