### ISSUE TITLE
VideoJS v6.11.0 + VideoJS-Contrib-HLS v5.14.1 made a mistake displaying VOD Controlbar become Live Controlbar

### ISSUE THREAD

**Issue by dioramayuanito** [videojs/video.js#5708]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.
VideoJS made an error in displaying the ControlBar. VOD Controlbar from HLS Source, become Live Controlbar while playing the streaming. was it a bug in Duration of Streaming? How to avoid this bug?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.
VOD Controlbar should be displayed to User. Source was Wowza VOD.

### Actual
Please describe what actually happened.
VideoJS Switched automatically VOD Controlbar become Live Controlbar while playing.

### Error output
If there are any errors at all, please include them here.
There was no error displayed in console browser.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
VideoJS v6.11.0 + VideoJS-Contrib-HLS v5.14.1

#### browsers
what browser are affected?
Chrome Android - old Samsung Galaxy Duos

#### OSes
what platforms (operating systems and devices) are affected?
Android 4.2.2

### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
One thing to note is that contrib-hls, by default, uses native HLS implementations and android's native hls implementation is pretty bad. I would recommend making sure to set [overrideNative](https://github.com/videojs/videojs-contrib-hls#overridenative) for contrib-hls. If that doesn't fix it, we're likely going to need the stream to reproduce with.

**Comment by dioramayuanito** [comment]
Ok Mr gkatsev, your clue is very important to us, thanks alot. I will check overrideNative option in contrib-hls...

**Comment by dioramayuanito** [comment]
Hello, @gkatsev ... thx alot for your info. after adding overrideNative there are 2 conditions: 1. in Chrome Android 4.2.2 old Samsung Galaxy Duos, vod still appears as live, but 2. in WebView Test App (you can install it via Google Play), vod seems Normal, appears with Duration. i think Chrome Android has some flaws 😂
