### ISSUE TITLE
Feature Request: Progress Adjustment

### ISSUE THREAD

**Issue by brubakerjeff** [videojs/video.js#5710]
Hi,

We're creating a video display. My understanding is this creates a "vjs-duration-display" object and "vjs-play-progress" (any pointers would be appreciated) encapsulated inside of the videojs project (we are using videojs-youtube but would that logic still be contained within the first?)

We are looking for a way to avoid the last x (generally 15 seconds) of a video. By breaking the encapsulation we've been able to update the UI viz below. (except clicking on the progress bar we've been unable to find a way to adjust). Could we get some pointers on a way to get a complete solution, ideally working within the patterns and possibly updating, if it doesn't already exist, the existing project with the feature.

```
$(".vjs-duration-display").first().text(formatted)
 
progress = Math.min(timeElapsed/(endTime)*100,100);
$(".vjs-play-progress").css("width",progress + "%")
```

```
player = videojs(id, {
	techOrder: ['youtube'],
	youtube: { "enablejsapi": 1, "autoplay" : playState, "start" : startTime, "version" : 3, "loop": false, "inactivityTimeout": 500},
	poster: '',
	sources: [
			{
				type: 'video/youtube',
				src: src
			}
		]});
```

**Comment by gkatsev** [comment]
I think what you're looking for is middleware. You can use it to adjust the timeline to your heart's content. We have a [blogpost about it](https://blog.videojs.com/feature-spotlight-middleware/) as well as [a guide](https://docs.videojs.com/tutorial-middleware.html).

Also, the youtube tech does have support for an end time, so, that may be something to look into as well.

Let me know if any of the above make sense and are pointing you in the right direction!

**Comment by brubakerjeff** [comment]
Thank you. You're referring to this PR then? https://github.com/videojs/videojs-youtube/pull/422 Looks straight forward enough, I'll give it a try. Thank you.

**Comment by brubakerjeff** [comment]
Just to make sure I'm understanding, the middleware has to run server side and it runs as part of node? I'm thinking the best option for us would be to convert to a python/flask backend to match our existing backend.

**Comment by gkatsev** [comment]
No, the middleware I'm referring to is Video.js middleware, I linked to documentation in my previous post.
