### ISSUE TITLE
How to implement videojs-dvrseekbar plugin correctly?

### ISSUE THREAD

**Issue by CAglar62** [videojs/video.js#5712]
want to implement a videoJS player capable of playing live DVR stream. It should play the live stream but the user should be able to go back and watch like 30 minutes back.

I tried to use videojs-dvrseekbar plugin as shown in the following web page https://www.npmjs.com/package/videojs-dvrseekbar.

Like in the web page I tried the following

<script src="//path/to/video.min.js"></script>
<script src="//path/to/videojs-dvrseekbar.min.js"></script>
<script>
   var player = videojs('my-video');

   player.dvrseekbar();
</script> 
I was expecting a video bar that you can jump back but It just plays it like a live video. For a reason that I don't understand, sometimes a short bar appears and you cannot move it. However today I was able to c\move it and DVR was working the only problem was it was too short. However, when I refreshed the page It disappeared again. I do not understand why any of these things happen. And there is not enough info on the plugin page. My whole code is as follows:

<video id="player" class="video-js vjs-default-skin" style="width: 100%;" height="400" controls></video>

<script>
  var player = videojs('player');
  player.ready(function() {
      player.src({
        src: srcurl,
        src: 'https:..../Manifest.mpd',
        type: 'application/dash+xml'});

      player.dvrseekbar();

    });

</script>

**Comment by gkatsev** [comment]
This is now built-in to video.js. Just set [`liveui`  option](https://docs.videojs.com/tutorial-options.html#liveui). See our [guide](https://github.com/videojs/video.js/blob/master/docs/guides/live.md) for more info.

**Comment by CAglar62** [comment]
Thanks for the help, I was able to make it work with hls but it does not work with dash. And I don't know the problem. Do you have any idea
