### ISSUE TITLE
样式语法错误

### ISSUE THREAD

**Issue by siriusSupreme** [videojs/video.js#5713]
## Description
```
_captions-settings.scss

.vjs-text-track-settings .vjs-track-settings-controls {
    // make this take up both columns
    grid-column: 1 / -1;
 }
```

![image](https://user-images.githubusercontent.com/20105166/50499259-289ecc80-0a83-11e9-88da-b211f2d599cb.png)

报语法错误！

**Comment by gkatsev** [comment]
Looks like the tool you're using doesn't understand the new css grid syntax.
