### ISSUE TITLE
Not able to play locally hosted .mpd files

### ISSUE THREAD

**Issue by hanumantha03** [videojs/video.js#5726]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

I am not able to play the videos which I have hosted on my system. The format of the video files is .mpd
I am getting GET 'localhost:8080/.../file.mpd' net: :ERR_TIMED_OUT

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. I stored the video in .mpd format and kept it in videos folder.
2. Gave the source of the file in src option of player.
3. Hit the localhost URL in the browser.
## Results
Video is not playing

### Expected
Please describe what you expected to see.
I expected that the video would play.

### Actual
Please describe what actually happened.
this happened : The media playback was aborted because too many consecutive download errors occurred.

### Error output
If there are any errors at all, please include them here.
**GET https://localhost:8080/videos/crypto.mpd net::ERR_TIMED_OUT**
![error_video_player](https://user-images.githubusercontent.com/32599055/50680396-9cb21500-102d-11e9-99b4-09e1382b407d.PNG)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
**Version 7.X**

#### browsers
what browser are affected?
**Chrome**

#### OSes
what platforms (operating systems and devices) are affected?
**Windows 10**

### plugins
are any videojs plugins being used on the page? If so, please list them below.
Video.js plugin used : 
-> **video-contrib-dash**

**Comment by forbesjo** [comment]
Does your source work when using the dash.js reference player? http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

**Comment by hanumantha03** [comment]
no it is not. I am hosting the .mpd file on my local system.

**Comment by hanumantha03** [comment]
Can you please tell me what other information is needed?

**Comment by forbesjo** [comment]
The ERR_SSL_PROTOCOL_ERROR error leads me to believe that there's something wrong with the way the file is being served, are you able to request the file without a player and see it complete?

**Comment by gkatsev** [comment]
your link `https://localhost:8080`, is your local server enabled for serving HTTPS?

**Comment by hanumantha03** [comment]
I am using this command for server : **python -m http.server**. and it is giving me a message that the server has started at localhost:8080.

**Comment by hanumantha03** [comment]
> The ERR_SSL_PROTOCOL_ERROR error leads me to believe that there's something wrong with the way the file is being served, are you able to request the file without a player and see it complete?

I am sorry, I didn't understand this question :  **are you able to request the file without a player and see it complete?**

**Comment by gkatsev** [comment]
`python -m http.server` doesn't serve HTTPS. Try using `http://localhost:8080/` instead

**Comment by hanumantha03** [comment]
![2143214](https://user-images.githubusercontent.com/32599055/50904190-b6949300-1445-11e9-84fe-7bc888a053dc.PNG)

I have used shaka-packager to create my .mpd file using the below command:

**packager-win.exe in="video.mp4" stream='video', out='video.mp4' --mpd_output="video.mpd"**

but the video is not getting played. Player is showing a loading icon and I am getting the above error.
