### ISSUE TITLE
Icon deviation

### ISSUE THREAD

**Issue by yuluqqvip** [videojs/video.js#5734]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
![image](https://user-images.githubusercontent.com/16302664/50766246-71405c00-12b3-11e9-83b1-0c635e4c9e9e.png)

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
Firefox Quantum 64.0
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
What OS are you on? Locally on firefox 64 and macos, I am  unable to reproduce.

**Comment by yuluqqvip** [comment]
windows10
