### ISSUE TITLE
Question: What values should Tech methods return when duration, seekable, and buffered values are unknown?

### ISSUE THREAD

**Issue by yokuze** [videojs/video.js#5742]
Note: This issue contains questions, not necessarily a defect. My apologies if submitting an issue isn't the proper way to pose these questions. Just let me know and I'll re-direct it elsewhere.

When writing a custom `Tech`, we are required to implement the `duration`, `seekable`, and `buffered` functions. However, there are cases where the `duration`, `seekable` time ranges, and `buffered` time ranges are unknown. I’m not able to determine from the `Tech` documentation what values to return for those functions in the case when they are unknown. So, I have the following questions (with examples given using a custom Chromecast `Tech`):

   1. If the `duration` of a media item is unknown (and will likely never become known), but the item is playable/playing, what value should the `duration` function return? 
      * For example, in the case of a Chromecast `Tech`, we may cast a video but the Chromecast API may never let us know the duration of the video. It’s safe to play, pause, and seek while the video is casting, it’s just that the duration is unknown. What value should be returned from the `duration` function so that the Video.js player can continue to function as smoothly as possible (i.e. not cause errors, allow the user to seek, etc)?
   2. If the `seekable` time ranges are not known, what value should the `seekable` function return so that the Video.js player can continue to function as smoothly as possible (i.e. not throw an error, and allow the user to seek)? 
      * E.g. the Chromecast API does not have a concept of seekable time ranges, but it handles requests for seeking out of bounds and requests for seeking unbuffered portions of the media item well.
   3. If the `buffered` time ranges are not known, what value should the `buffered` function return so that the Video.js player can continue to function as smoothly as possible? 
      * E.g. the Chromecast API does not have a concept of buffered time ranges.

Thank you!

**Comment by gkatsev** [comment]
This is fine for asking such questions. You can also join our [slack](http://slack.videojs.com) if you want.

We generally try to follow the spec for these types of things.
- For `duration`, an unknown duration should return NaN and a live stream should return Infinity. We actually recently got a fix in regarding having NaN as a valid duration.
- For `seekable` and `buffered`, you'll want to return an empty TimeRange object. We have a helper method on `videojs` for creating TimeRange objects, they accept a start and end period, but since it's empty, you'll want to call them without anything: [`videojs.createTimeRanges()`](https://docs.videojs.com/module-videojs-videojs.html#.createTimeRanges)

Hope this helps!

**Comment by gkatsev** [comment]
We should make sure to document this along with #5737

**Comment by yokuze** [comment]
@gkatsev Sorry, one additional question for a function that I hadn't considered until compiling the list in #5737:

What value should the `networkState` function return, when it is unknown? All I really know in the Tech that I'm implementing is whether or not the item is playing. I read through the HTML spec, and it's unclear to me what value I should return (if any).

**Comment by gkatsev** [comment]
I guess it depends on what's happening. If you're loading data, then it should be NETWORK_LOADING, 2, or there's no data and you're currently not loading then it should be NETWORK_EMPTY, 0. I guess NETWORK_EMPTY can be used as a catch-all default value. See https://www.w3.org/TR/html50/embedded-content-0.html#dom-media-networkstate for more info.
