### ISSUE TITLE
Seekbar not working in chrome

### ISSUE THREAD

**Issue by ideatedevelopers** [videojs/video.js#5744]
I've got an issue with seekbar in chrome (tested with macOS and win10).

On seeking through mouse, keyboard (hotkeys plugin) or even the buttons (seekbuttons plugin), It moves sets back the player position to starting position no matter you forward or backward from whatever current position. 

This seems to be working fine with firefox so it seems to be a chrome specific issue and that is too with some of the videos only i guess but i'm having it on almost all the videos on my site.

Web Page URL : https://yiddishevinkel.com/archives/31358
Reduced Test Case : https://codepen.io/anon/pen/xmyYRE

**Comment by gkatsev** [comment]
This is likely an issue with the mp4 file itself. I can't open it using VLC or quicktime, so, kind of surprised that chrome plays it at all. ffprobe says that the file doesn't have a `moov` atom and that there's invalid data in the file as well.

**Comment by ideatedevelopers** [comment]
Alright it seems to be cloudflare issue. resolves itself if i disable it.
