### ISSUE TITLE
7.4.2: vjs-fullscreen class not added (regression)

### ISSUE THREAD

**Issue by blacktrash** [videojs/video.js#5745]
## Description
Player element in fullscreen is missing the `vjs-fullscreen` class.
Test case: https://blacktrash.org/test/videojs/issue5745.html

## Steps to reproduce
1. Go fullscreen
2. Check player element for `vjs-fullscreen` class - the test case demo logs whether it is present.

### Expected
Player element should have `vjs-fullscreen` class in fullscreen mode.

### Actual
Player element does not have `vjs-fullscreen` class in fullscreen mode.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.4.2 - perhaps a regression caused by https://github.com/videojs/video.js/commit/2bc90a1899aec36ef57b7c2f207e7f7b15042f85

**Comment by gkatsev** [comment]
What browser and OS are you using? We tested pretty thoroughly, also, I'm unable to reproduce using your example in Chrome 70 Win 10.

**Comment by blacktrash** [comment]
On Mac OS:
- Firefox 64.0.2
- Safari 12.0.2
- Chrome 71.0.3578.98
- Chrome Canary Version 73.0.3669.0

**Comment by blacktrash** [comment]
@gkatsev - are you sure? This is what I get with Win 10 Chrome 70 in browserstack:
<img width="893" alt="screen shot 2019-01-12 at 5 59 27 pm" src="https://user-images.githubusercontent.com/168338/51076059-0c5e7a80-1694-11e9-8745-a0a741375f9e.png">

**Comment by gkatsev** [comment]
Hm... I think I can reproduce on my mac but on my win machine it seemed to have worked fine. We'll take a look.

**Comment by gkatsev** [comment]
I'll see if I can fix the fix or whether we should revert it in favor of a more complete refactor/rewrite of the fullscreen functionality.

**Comment by blacktrash** [comment]
@gkatsev - thanks!

**Comment by gkatsev** [comment]
Thanks for noticing and helping to test! It's out now in 7.4.3.
