### ISSUE TITLE
/src/js/utils/dom.js中的isNonBlankString函数逻辑描述有误

### ISSUE THREAD

**Issue by wyake** [videojs/video.js#5753]
源码中的函数以及其描述是：
/*
@return {boolean}
          Will be `true` if the string is non-blank, `false` otherwise.
*/
function isNonBlankString(str) {
  return typeof str === 'string' && (/\S/).test(str);
}
按照函数的注释，如果参数str不包含空格字符，那么就返回true。但实际相反。
所以函数应该更改为
return typeof str === 'string' && !( (/\S/).test(str) );
对第二个判断加上“非”处理，即可。

**Comment by mister-ben** [comment]
It works as described. The function returns `true` if `str` is a string and it contains any non-whitespace character.

Your version would return `true` if `str` is a string and it contains no non-whitespace characters. It could be an `isBlankString()` function.

**Comment by gkatsev** [comment]
As @mister-ben mentioned this is working as intended and the description is correct. Though, perhaps it can be elaborated on.
