### ISSUE TITLE
MenuButton title is not registered? Call to el() fails

### ISSUE THREAD

**Issue by gmkll** [videojs/video.js#5759]
## Description

An exception is thrown in blur handler for custom menubuttons (or may be even build in buttons as ChaptersButton). 

Using custom MenuButtons with custom entries registered by createItems. VideoJS sets before the items in the Menu list the title as list element (menu-title is inserted) -> Menu component.

This happens in menu-button.js createMenu function:
`menu.children_.unshift(title);`. 

N.B. title is no component, just an DOM element!
 
## Steps to reproduce

Explain in detail the exact steps necessary to reproduce the issue.

1. click any (custom) menubotton icon with title set
2. select, what you want, or click elsewhere
3. the selectable list should be hidden by default and no exception should be thrown.

### Expected
- the selectable list is hidden by default and no exception is thrown in step 3

### Actual
- the list is not hidden, instead an exception is thrown.

In src/menu/menu.js function handleBlur does check the menu list (children) like this:

`  if (!this.children().some((element) => {    return element.el() === relatedTarget;  ..  `

The first entry in children() is the title from MenuButton and throws this exception.

`TypeError: element.el is not a function. `.

This first entry in children of Menu component is just an DOM element not extending Component (see menu-button.js above). The call to el() being a prototype function of component fails.

First Thought solution: Do not check the title by removing the title entry from children (do not check this first entry) as the other are correctly registered components (MenuItem).  But this element is optional, and missing if no title is set. 

Better make it a component?

### Error output
Exception is thrown: `TypeError:` element.el is not a function. `.

#### videojs
7.4.1
#### browsers
Chrome 
#### OSes
Windows
### plugins
- errors
- perSourceBehaviors

**Comment by gkatsev** [comment]
Yeah, the menu title isn't a component for bad historical reasons. There's a PR out to fix it: https://github.com/videojs/video.js/pull/5722. There's also this related issue: https://github.com/videojs/video.js/issues/3612
