### ISSUE TITLE
Fullscreen video locked to portrait on ios only

### ISSUE THREAD

**Issue by joe-scotto** [videojs/video.js#5760]
## Description
Having a weird issue, I've tried overriding via swift and objective c but am not able to figure it out. When full-screening a video it will not allow landscape orientation even though no where in my app am I limiting it to only portrait. What's even stranger is that the entire ui of the phone will rotate (notification center, control center, etc) but the controls of the player will remain in portrait.

I am running this in a ionic-cordova app, my ionic info is as follows, updating this is not an option as I have plugins that require these versions:

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/jscotto/.nvm/versions/node/v6.11.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 1.3.7

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 6.4.0, ios 4.4.0
   Cordova Plugins       : no whitelisted plugins (23 plugins total)

System:

   ios-deploy : 1.9.2
   ios-sim    : 7.0.0
   NodeJS     : v6.11.3 (/Users/jscotto/.nvm/versions/node/v6.11.3/bin/node)
   npm        : 2.15.12
   OS         : macOS
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Full screen video
2. Doesn't allow landscape

### Expected
Video should rotate to landscape

### Actual
Video does not rotate to landscape

### Error output
No errors in xcode inspector or safari

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.16.2
#### browsers
ios
#### OSes
ios

**Comment by gkatsev** [comment]
Not really familiar with ionic, Video.js doesn't really do anything related to locking to a particular orientation. Could it be that it's locked at ionic level? https://ionicframework.com/docs/native/screen-orientation/
