### ISSUE TITLE
Inability to seek on PlayStation

### ISSUE THREAD

**Issue by Akxe** [videojs/video.js#5761]
## Description
Inability to seek on PlayStation does extend to `volumeBar` too. Focusing the element is possible, but "clicking" is not. However, one can use arrows to seek.

Sidenote: Normal buttons work, but clicking on video (to toggle play/pause, does not)

## Steps to reproduce
VideoJS homepage is enough... any video will do. Play it, try to seek.

### Expected
Video should seek.

### Actual
Click focused seekBar, not doing anything else,

### Error output
none (at least got called via `video.on('error', console.log)`)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7+ not tested earlier
#### browsers
PlayStation
#### OSes
PlayStation
### plugins
none

**Comment by Akxe** [comment]
Also, I would make a note in the FAQ: 
**Video not playing on PlayStation?**
It might be due to SSL encryption being too low. Either use higher, or none at all.

**Comment by Antex** [comment]
This issue still not resolved.

**Comment by Antex** [comment]
dirty hack to fix this issue:
function isSingleLeftClick(event) { return true; }

**Comment by gkatsev** [comment]
> how well VideJS was truly 'cross-platform'.

We try to be as cross platform as we can within reason. Unfortunately, we're a small team and can't test on all devices.

---------------------

Unfortunately, we don't have a PlayStation available for testing, so, are likely unable to make a fix ourselves. If someone is able to submit a fix with tests, we'd be happy to merge.
