### ISSUE TITLE
Disable videojs loading animation

### ISSUE THREAD

**Issue by masudhossain** [videojs/video.js#5763]
I integrated youtube into videojs and since youtube already has a loading animation, there's no need for one from videojs (example: http://prntscr.com/maqt2z). 

Is there a CSS way to disable it? Otherwise, a JS way is fine too.

**Comment by Akxe** [comment]
Nothing simpler than this: `.vjs-loading-spinner{display:none!important;}`

**Comment by gkatsev** [comment]
You can also pass in `loadingSpinner: false`.

**Comment by masudhossain** [comment]
@Akxe I tried doing this too, but it seems to still show the loading animation.

**Comment by masudhossain** [comment]
I went ahead and removed it from the video-js.css directly.

**Comment by gkatsev** [comment]
@masudhossain did you try going the option route?

**Comment by webdeveloperpr** [comment]
I'm trying the options route. It doesn't seem to be working, or maybe I'm doing it wrong

**Comment by gkatsev** [comment]
If you can post a reduced test case on a site like codepen, we can take a look.

**Comment by franconeilglovasa** [comment]
Hi, how did you able to disable the loading spinner?

this one makes my video blank
`.vjs-loading-spinner{display:none!important;}`


How do you use this one?
`loadingSpinner: false`

html:
`  <video #target class="video-js" controls playsinline preload="none" ></video>`

ts:
```
  ngOnInit(): void {
    if(this.options.isStreaming){
      this.preInitVideoJs();
    }
    this.player = videojs(
      this.target.nativeElement,
      this.options
    );
  }
```

tried adding loadingVideo on my viewmodels options and it didnt like it
