### ISSUE TITLE
How to hidden this modal dialog in iPhone? 

### ISSUE THREAD

**Issue by SmallWeed** [videojs/video.js#5767]
![img_2644](https://user-images.githubusercontent.com/11731944/51798546-45c7e600-224f-11e9-85d3-95e408914705.PNG)

**Comment by mister-ben** [comment]
The CSS is missing.

**Comment by SmallWeed** [comment]
@mister-ben which css is missing? i help my company other program fix this bug  - -

**Comment by SmallWeed** [comment]
<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
  data-setup='{"bigPlayButton": false,"posterImage": false,"textTrackDisplay": false,"controlBar": false,"errorDisplay": false,"textTrackSettings": false}'>

CSS like this ?

**Comment by SmallWeed** [comment]
<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" data-setup='{"bigPlayButton": false,"posterImage": false,"textTrackDisplay": false,"controlBar": false,"errorDisplay": false,"textTrackSettings": false}'>

CSS like this？

**Comment by SmallWeed** [comment]
（<video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
  data-setup='{"bigPlayButton": false,"posterImage": false,"textTrackDisplay": false,"controlBar": false,"errorDisplay": false,"textTrackSettings": false}'>）

CSS like this?

**Comment by SmallWeed** [comment]
![wechatb2252d5d612db2991c248804a7bcc097](https://user-images.githubusercontent.com/11731944/51810750-bb31c600-22e4-11e9-92ed-23f8a5e5630d.png)

CSS like this?

**Comment by gkatsev** [comment]
The Video.js CSS file seems to be missing on the page. You need to make sure to include the CSS file in addition to the JavaScript file.
