### ISSUE TITLE
Better way to reload track(subtitles) src by url?

### ISSUE THREAD

**Issue by hankwang** [videojs/video.js#577]
I use a online url to load my subtitle webvtt, like http://mydomain.com/abc.vtt

But I need reload my subtitle realtime. So I use this code to force reload specific TextTrack:

```
vjs.TextTrack.prototype.reload = function() {
    this.readyState_ = 0;
    this.cues_ = [];
    this.load();
}
```
But I think it had a best way to do this, any suggest?

**Comment by gkatsev** [comment]
The new recommended way to reloading the track is to remove the old track and add a new one. This is how browsers expect text tracks to work and how we've implemented our new captions support.
