### ISSUE TITLE
npm behind a few versions

### ISSUE THREAD

**Issue by tomByrer** [videojs/video.js#5771]
npm lists the current version to be `7.4.1`.
I can see not bumping up to 7.5.0 right away, but I'm confused why 7.4.3 is not the default npm versions.
All the new releases are availbe on direct request; at least via [jsDelivr CDN](https://www.jsdelivr.com/package/npm/video.js?version=7.5.0&path=dist).

Test procedure; opened `https://www.npmjs.com/package/video.js` via Fx 'Private Window'.

**Comment by tomByrer** [comment]
I'm kinda confused by the release system you have; no mention of 'beta' or 'pre-release' anywhere.  Both CHANGELOG & release notes don't mention that 7.5.0 , 7.4.3, & 7.4.2 are not officially the `latest`.  But if do see many patched bugs that folks who pull from npm normally will go without.

If a version is a 'pre-release ', please mark the version number as `7.4.3-pre`, or `7.8.0-rc` so it would be more clear what your intentions are.

Thanks for all your hard work!

**Comment by gkatsev** [comment]
7.4.3 should be made latest, didn't get a chance to do so before leaving on a trip. We've generally been using the npm and github releases tags for marking things as "prerelease". The main reason why we've avoided adding tags to this is that after about a week, we promoted that release to `latest` and it means that we don't have to do another release beyond changing the tag on npm and github releases.
Releases are generally tested and we think the risk is generally pretty minimal but it is why we don't tag as latest immediately. We've rarely had to do a patch release before promoting those both (7.4.2 is one such case in recent times, though). Most CDNs like jsdelivr know what the latest tag is and you can target that one, for example https://cdn.jsdelivr.net/npm/video.js/dist/video.min.js or https://cdn.jsdelivr.net/npm/video.js@latest/dist/video.min.js.

Also, I know it isn't ideal, but we do mention whether it's a pre-release or not on twitter https://twitter.com/videojs/status/1088895901291212807 as well as in our release notes blogposts.
