### ISSUE TITLE
The currenttime working incorrect on mobile devices

### ISSUE THREAD

**Issue by ersul4ik** [videojs/video.js#5772]
## Description
I implementing this logic to set current time if the user watched this video. 
I tried to use the code below:

```
player = videojs('tvshow-player');

$('.someClass').on('click', function () {
    var $this = $(this).closest('.item');
    var src = $this.data('src');
    var poster = $this.data('poster');

    episodeSlug = $this.data('slug');

    player.src(src);
    player.poster(poster);
    player.currentTime(localStorage.getItem(episodeSlug));

});
```
On mobile devices is not working. If user previously watched the video it starts from the proper moment but only for a second and than start from the begginig. 

## What I did ?
I had research this issue and refactor code the next way:

```
player.on('loadedmetadata', function(e) {
    console.log("We are in the loadedmetadata handler");
    if ( player.bufferedPercent() > 0 ) {
        console.log("We are in bufferedPercent condition");
        player.currentTime(localStorage.getItem(episodeSlug));
        player.pause();
    }
});
```

## Results
I checked my refactored code with dev debbugining on mac oc. And here what I got:

>     We are in the loadedmetadata handler;
>     We are in bufferedPercent condition;

On the **mobile devices** I see:

>     We are in the loadedmetadata handler;

The mobile device is failling on this validation ( _player.bufferedPercent() > 0_ )

I tried to:

- Remove the  _bufferedPercent_ condition
- Move the player.currentTime(localStorage.getItem(episodeSlug)) to other line
- Use  the player.currentTime() without the localStorage logic 

#### videojs
7.1.0

#### browsers
Chrome 71.0.3578.99 (mobile)
Xiaomi Browser 9.8.5

### plugins
videojs-dash.min.js
videojs-flash.js
videojs-contrib-hls.js

**Comment by gkatsev** [comment]
Seeking on `loademetadata`, without the bufferedPrecent check should be fine, though it still won't be perfect. This is because on mobile devices, no data is generally loaded, so, by the time loadedmetadata is fired it's possible no actual video data has loaded. Even without video.js, you'll have similar behavior with native element on mobile devices.

We've been thinking about this for a while and we may add something like https://github.com/brightcove/videojs-urlparams/blob/master/videojs.urlparams.js#L97-L105 to Video.js, otherwise, you can try doing that yourself.

**Comment by gbarrett1988** [comment]
I'm experiencing an issue where during live HLS streams on mobile the player.currentTime() returns a number less than the current elapsed time (seems like the offset of the last buffer segment)

example:
live desktop returns: ~300 seconds
live mobile returns: ~6 seconds

Scratching my head for a workaround at the moment.

**Comment by gbarrett1988** [comment]
UPDATE: Only seeing this on my Android test devices ATM.
