### ISSUE TITLE
[Question] Supported Formats

### ISSUE THREAD

**Issue by zero77** [videojs/video.js#5779]
I am trying to find out if mkv, avi, mpg and wmv are supported.
Where can i find documentation on supported formats.
Thanks

**Comment by magikstm** [comment]
https://docs.videojs.com/tutorial-faq.html#q-what-media-formats-does-videojs-support

https://docs.videojs.com/tutorial-troubleshooting.html

**Comment by mister-ben** [comment]
PR for a few updates to that format info, https://github.com/videojs/video.js/pull/5783/files

None of mkv, avi, mpg and wmv are supported for HTML5 video playback by modern browsers. You might be able to trick some browsers into playing some mkv videos if you use the webm type, but I wouldn't rely on it.

**Comment by zero77** [comment]
@mister-ben @magikstm 
Thanks

**Comment by gkatsev** [comment]
mkv technically works in chrome since webm is basically mkv but you won't get any sound, unfortunately. So, best to just discount it altogether. Your best bet is still an mp4.
