### ISSUE TITLE
Player is broken sometimes 

### ISSUE THREAD

**Issue by hrachbkweb** [videojs/video.js#5780]
## Description
Sometimes when we try to watch the video we get this error 

![slack-imgs com](https://user-images.githubusercontent.com/34035420/52214654-9375cb80-28ab-11e9-8aa2-4b43b200bbe1.png)

After refreshing the age usually error is gone but from time to time it happens , And no error in console whatsoever .
It happens on Chrome on Firefox so far .

Code used 

```
var myPlayer = null;
           videojs('videoPlayer').ready(function () {
                      myPlayer = this;
           });
```
And after sending video source via 
`myPlayer.src({type: 'video/mp4', src: video_url});`

Version Video.js 7.1.0
Any  idea what is the issue and how to solve?

**Comment by bcbclifford** [comment]
If it looks like that, then the browser has not loaded the CSS for Video.js. Maybe the request for the CSS is timing out?

**Comment by mister-ben** [comment]
If it looks like that, then the browser has not loaded the CSS for Video.js. Maybe the request for the CSS is timing out?

**Comment by hrachbkweb** [comment]
Thanks for response .
slow internet issue ?
Any way to resolve ?

**Comment by misteroneill** [comment]
It could also be that the page CSS is colliding with the Video.js CSS in some way. It's kind of out of the scope of an open source project to figure out these implementation-specific issues.

First, as @mister-ben suggested, I'd make sure you're including the Video.js CSS. If the Video.js CSS is being included, I'd check what styles on the page are conflicting and fix that.

**Comment by hrachbkweb** [comment]
Well  supposing it was(and still does sometimes ) caused  by slow internet  (which is quite weird).

**Comment by gkatsev** [comment]
What url are you loading the Video.js CSS from? Try loading from another CDN closer to you geographically? You can also inline the Video.js css into your html file, our css isn't that big, especially minified.
