### ISSUE TITLE
HLS Video Aspect Ratio changing on player resize

### ISSUE THREAD

**Issue by dangrima90** [videojs/video.js#5790]
## Description
I'm testing out an HLS stream for a project I'm working on, and for some reason when the window is resized several times it seems that the stream changes to a 16:9 aspect ratio and after a few moments switches back to the aspect ratio set in the videojs instance.

In my case the aspect ratio is set to 256:239, and if the window is resized most times it results in the aspect ratio being changed with the video displaying like so:

![image](https://user-images.githubusercontent.com/36479149/52564410-6756cf00-2e04-11e9-93c7-9721a31d0646.png)

The stream is via a 3rd party and although I am in communication with the 3rd party I've been told that the issue is not from their end. I'm not sure where the issue is to be honest, but after seeing this: https://github.com/videojs/videojs-contrib-hls/issues/305 I'm lead to believe that it might be a similar issue. Are there any configurations from my end that I can set, or this is an issue from the stream itself?

I'm creating the video with the following settings:

`this.player = videojs('video', {
    aspectRatio: '256:239',
    controls: true,
    autoplay: false,
    muted: true,
    html5: {
        hls: {
            overrideNative: true
        }
    }
});`

I have created a stackblitz to replicate the issue and the same thing is happening: https://stackblitz.com/edit/videojs-hls-issue?file=src%2Fapp%2Fvideo%2Fvideo.component.ts

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load https://stackblitz.com/edit/videojs-hls-issue?file=src%2Fapp%2Fvideo%2Fvideo.component.ts
2. After UI loads, resize the preview window a few times
3. Most often than not the aspect ratio of the stream changes and then later resets itself

### Expected
That the stream stays with the same aspect ratio when player is resized.

### Actual
Most times the stream changes the aspect ratio when player is resized.

### Error output
No errors to report

## Additional Information

Version Numbers:

- VideoJS version 7.5.0
- Although it might be irrelevant, since this is an Angular application I'm also using the VideoJS Typings version 7.2.8

Furthermore I've testing this on Angular 5.2.8 as well as Angular 7.2.4 and the issue seems to occur more frequent on macOS.

**Comment by gkatsev** [comment]
Unfortunately, I cannot reproduce.

**Comment by dangrima90** [comment]
Hi @gkatsev it's been a while since the issue was opened, sorry for not updating the issue. From the testing I made the issue from the video stream provider. They basically had set the stream to switch to a 16:9 aspect ratio for low bandwidths and when the stream was loading.

Unfortunately the provider didn't mention this setting when I was testing so it took a while for me to realise what was the problem. After raising the issue several times I think they realised that the issue was from their end.

Apologies once again for not updated the issue.

**Comment by gkatsev** [comment]
No worries, glad it got resolved!

**Comment by aandreigromov** [comment]
I use iDealshare VideoGo to change video aspect ratio: Click "Setting..." ->"Advanced Settings" ->"Aspect Ratio" column, click the Auto drop down button to select 4:3 or 16:9 or just overwrite your desired one like 2.35:1, 1.85:1, 1:1, and etc.

**Comment by aandreigromov** [comment]
Here is the detailed guide: https://www.idealshare.net/video-converter/change-video-aspect-ratio.html
