### ISSUE TITLE
Cannot record video on Safari

### ISSUE THREAD

**Issue by ledzgio** [videojs/video.js#5791]
## Description
Cannot record video/audio on Safari 12.0.3 using the following libraries:
VIDEOJS: Using video.js 7.5.0 with videojs-record 3.4.2 and recordrtc 5.5.4

## Steps to reproduce
Just try to record a video using Safari browser

### Expected
Record the video correctly

### Actual
The video has a small delay (less than 2 seconds) and when I start recording, the video doesn't stop and I see the error below in the console

### Error output
Browser console produces the following:
VIDEOJS: – "ERROR:" – "Your browser does not supports Media Recorder API. Please try other modules e.g. WhammyRecorder or StereoAudioRecorder."
(funzione anonima) — video.min.js:12:1481
error — video.min.js:12:2368
dispatcher — video.min.js:12:10365
pe — video.min.js:12:11112
trigger — video.min.js:12:15153
(funzione anonima) — video.min.js:12:193742
n — video.min.js:12:12359
n — video.min.js:12:12359
dispatcher — video.min.js:12:10341

**Comment by gkatsev** [comment]
Unfortunately, we don't maintain videojs-record. Looks like you opened an issue against that project already (https://github.com/collab-project/videojs-record/issues/332). We can definitely help if need be but it's unlikely anything we'd be able to help with.
However, it does seem like MediaRecorder isn't available on Safari.
