### ISSUE TITLE
Start HLS live stream at first segment

### ISSUE THREAD

**Issue by darklink41** [videojs/video.js#5794]
Hello,

First thanks for your hard work the player is really useful !

I'm using the brand new seekbar and trying to start an HLS live stream at the first segment but currentTime() doesn't seem to work even with negative integers.

```
  componentDidMount() {
    // instantiate Video.js
    this.player = videojs(this.videoNode, this.props, function onPlayerReady() {
      this.player_.currentTime(0)
    });
  }
```
I'm probably doing something wrong, thanks a lot !

**Comment by gkatsev** [comment]
Seeking on `loadedmetadata` is probably more reliable and safer. Additionally, you probably should be seeking to the beginning of the seekable range rather than 0. Something like:
```js
player.on('loadedmetadata', function() {
  player.currentTime(player.seekable().start(0));
});

**Comment by darklink41** [comment]
Thanks a lot, it works as intended !
