### ISSUE TITLE
Subtitles/Closed Captioning not displaying for Edge 44

### ISSUE THREAD

**Issue by stephenkalnoske** [videojs/video.js#5796]
In the new MS Edge 44 update, the CC button in the toolbar is not appearing at all. Works in previous versions of Edge as well as other browsers. Setting "use native text tracks" to false will resolve it, but that seems like a bad workaround.

**Comment by gkatsev** [comment]
What version of Video.js is used? For a long time now, Video.js hasn't used native captions on Edge due to lots of issues with the native caption support.
