### ISSUE TITLE
Question: Reset Cues for Text Track

### ISSUE THREAD

**Issue by richardbushell** [videojs/video.js#5797]
Hi, is there any way/method to reset the CUES in an existing text track?
I have a JavaScript Variable Reference to the Text Track itself, and I can change the track's SRC value, but this does not force or trigger a reset of the existing cues. I'd like to clear the existing cues and add the new ones from the revised SRC.

I am dynamically changing the video source on the same player, and also changing the poster, and that's working fine to play different videos from the same instance, but I'd really like to dynamically overwrite/reset the cues on the existing track too. I can't see a method for this in the API? (p.s. I'd rather not remove and add tracks as we tie in with a third-party plugin to display thumbnails). If the cues auto-updated when we changed the track SRC, or if there was a reset/refresh cues method then our dynamic switching of videos would be sorted.

Please advise if there's a way of doing this??? p.s. It's an EMULATED and HIDDEN Text Track containing Metadata.

**Comment by gkatsev** [comment]
The best bet would be to remove the previous track and add a new one. changing the src won't load in the new cues unless you do so manually.
You can remove and add cues with methods on the TextTrack object (https://docs.videojs.com/texttrack#addCue)

**Comment by richardbushell** [comment]
Thanks (again) @gkatsev - yes, it may be easier to remove and re-add a new metadata track in that case and then re-setup the thumbnails via the plugin (rather than fetch, parse and re-write the cues manually). I had hoped there was a built-in API function to serve this re-parse purpose. Unfortunately there's no dispose function within the thumbnails plugin (so I'll just have to manually dispose the elements and listeners etc beforehand instead).

**Comment by gkatsev** [comment]
What you could do is add a new remote track, wait for it to load, and then for each cue in the new track addCue it to the old track.

**Comment by richardbushell** [comment]
Yes, that's a good idea. Would I even have to use the addCue method at all?
Could I just wipe the original cues_ array directly with:
myPlayer.textTracks()[0].cues_.length = 0;
and then just Concat (or otherwise merge/push) the new array onto the former?

**Comment by gkatsev** [comment]
That may work, but I don't promise that thing's won't break if things change internally :)

**Comment by richardbushell** [comment]
OK, trying to stay future proof, I have implemented the following:-

```
var i = myPlayer.textTracks()[0].cues.length;
while (i--) {
	myPlayer.textTracks()[0].removeCue(myPlayer.textTracks()[0].cues[i]);
}

myPlayer.newVttTrack = myPlayer.addRemoteTextTrack(...);

var j = myPlayer.textTracks()[1].cues.length;
while (j--) {
	myPlayer.textTracks()[0].addCue(myPlayer.textTracks()[1].cues[j]);
}
```

What I hadn't expected was that the 2nd loop actually REMOVES the Cue from the new track (which ends up with no Cues), so I had to iterate in reverse again. The downside of this is that the timings in each Cue is in reverse, so the last array member has the initial StartTime. Not necessarily a problem, but is this expected, and is this the correct/best way to call the addCue method (my code looks a bit duplicated).

**Comment by gkatsev** [comment]
yeah, the spec says a cue can only be in one track at a time. You can try something like:
```
while( myPlayer.textTracks()[1].cues.length ) {
  myPlayer.textTracks()[0].addCue(myPlayer.textTracks()[1].cues[0]);
}
```

**Comment by richardbushell** [comment]
Genius! Yes, that solves the order issue, and it works perfectly.

Just to note, when I subsequently execute:
```
myPlayer.removeRemoteTextTrack(myPlayer.newVttTrack);
```
Then the myPlayer.textTracks() still has getters for get1: (as well as get0: of course), so the removeRemoteTextTrack method perhaps should just tidy up the Getters too for the removed track if that is possible? Doesn't affect my code working at the moment, don't know if it might throw/cause errors for subsequent repeats of multiple switching/removals?

**Comment by gkatsev** [comment]
Yeah, it's a bit tricky but while the getter exists it shouldn't return anything.

**Comment by richardbushell** [comment]
OK, thanks so much for your help, this provided a neater solution than disposing and cleaning up the third-party plugin with multiple initiations. If anyone wants a replaceRemoteTextTrack method then hopefully they'll find this. Will close the question/issue now.

**Comment by acap91** [comment]
Traceroute ip

gomo. klate
