### ISSUE TITLE
Display multiple subtitles at once

### ISSUE THREAD

**Issue by Spartanace1024** [videojs/video.js#5798]
## Description
Native HTML5 seams to allow displaying multiple text tracks at once. However video.js emulated text tracks fail to allow doing this. 

I have tried displaying multiple tracks programmatically using 
` 
               toggleTracks: function() {
                    let tracks = videoPlayer.textTracks();
                    for (let i = 0; i < tracks.length; i++) {
                        const track = tracks[i];
                        if(this.showingTracks){
                            track.mode = 'showing';
                            continue;
                        }
                        track.mode = 'hidden';
                    }
                }
`
### Expected
I expect to see the subtitles overlaying each other allowing styling if necessary to move them to desired location.
See https://iandevlin.com/html5/track/index-multiple.html
### Actual
Please describe what actually happened.
Only the first track set to `showing` is displayed (as documentation suggests)

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.4.1

**Comment by gkatsev** [comment]
This is being fixed by #5817.
