### ISSUE TITLE
Question: How to get currently playing chunk?

### ISSUE THREAD

**Issue by greenya** [videojs/video.js#5800]
Hello.

How to get currently playing chunk of a playlist (a specific ts file). Maybe there is an event of similar? I need to know exactly when a chunk starts playing.

Thank you for any help.

**Comment by mister-ben** [comment]
With MSE playback you can listen to `cuechange` on the [segment metadata track](https://github.com/videojs/http-streaming#segment-metadata) and check the active cue.

**Comment by hold-baby** [comment]
player.textTracks().tracks_[0].activeCues_[0].value.uri

**Comment by gkatsev** [comment]
It's possible that the segment metadata track won't be the first one, but assuming it is, it's preferable to do the following instead:
```js
player.textTracks()[0].activeCues[0].value.uri
```

It's best to avoid any property that is prefixed or suffixed with `_`.

**Comment by hold-baby** [comment]
嗯  很好的建议 感谢
