### ISSUE TITLE
How can I play live (m3u8) streams as close to live as possible?

### ISSUE THREAD

**Issue by casolorz** [videojs/video.js#5801]
I have an m3u8 live stream that has like 2 hours of previously aired stuff in the m3u8 manifest. How can I tell videojs to start loading the last few segments and ignore all the old segments? 

Thanks.

**Comment by bc-paul** [comment]
The [live ui](https://github.com/videojs/video.js/blob/c1475819b2e2983ece6e0c42ae7a29daaf4ae51b/docs/guides/live.md) should help you accomplish that.

**Comment by casolorz** [comment]
Thanks, I'll take a look.
