### ISSUE TITLE
The audio is m3u8 file of mp3, there is no sound but only video

### ISSUE THREAD

**Issue by jeanneze** [videojs/video.js#5807]
## Description
The audio is m3u8 file of mp3, there is no sound but only video.
e.g.
https://72757-playvod.jdcloud.com/vod/product/2019/0218/143073/182/output.m3u8

## Steps to reproduce
1. Use any HLS live stream with mp3 audio and CORS headers enabled
2. Tried to use videojs v7.4.1 or v7.5.0

### Expected
There is a sound played in Safari ，PotPlayer, and can play with hls.js

### Actual
There is no sound but only video.

### versions
 videojs
v.7.4.1 and v.7.5.0

#### browsers
Chrome v72.0.3626.109

#### OSes
Windows 10  64 bits

**Comment by mister-ben** [comment]
Only aac is supported currently

**Comment by jeanneze** [comment]
Thank you !

**Comment by OoNaruto** [comment]
> Thank you !

how do you work it out？
