### ISSUE TITLE
DRM content does not play on any browser on Android 6.0

### ISSUE THREAD

**Issue by pushkar100** [videojs/video.js#5808]
## Description
No DRM content plays on Android 6.0. Identified on multiple browsers (Chrome, Firefox, UC browser) and their multiple versions.

This issue seems to be specific to this platform; the DRM content playback works fine on android 7.0

## Steps to reproduce
1. Open: https://reference.dashif.org/dash.js/v2.9.3/samples/dash-if-reference-player/index.html on an android 6.0 phone

### Expected
Expected to successfully play DRM protected content without any errors being thrown.

### Actual
Player throws the MEDIA_ERR_DECODE (code 3) error and fails to initialize the player.

### Error output
```
"code: 3, 
mediaError: MEDIA_ERR_DECODE, 
message: PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: timestamp=0 duration=21333 size=512 side_data_size=0 is_key_frame=1 encrypted=1 discard_padding (us)=(0, 0) decrypt=key_id:'EB676ABBCB345E96BBCF616630F1A3DA' iv:'3E0E41CCFDA83F8B0000000000000000' mode:CENC subsamples:[(clear:7, cypher:505)]"
```

## Additional Information
* Video.js version: ~6.2.8 
* Dash.js version: 2.9.2 (Happening on 2.9.3 as well)
* Browser name/version: Chrome 71.0.3578.99 & 72.0.3626.105 (Detected on Firefox & UC Browser too)
* OS name/version: Android 6.0 (Marshmallow)

![dashjs2 9 3 drm issue](https://user-images.githubusercontent.com/11087299/53015054-14b68c00-3470-11e9-8e40-80b348a42cb5.png)

**Comment by gkatsev** [comment]
If you're using Dash.js, that handles all the set up with EME and DRM. I would open an issue against Dash.js for this instead.
