### ISSUE TITLE
Question: How to use video tracks.

### ISSUE THREAD

**Issue by estebanz01** [videojs/video.js#5809]
Hello everyone!

I have a video file which contains multiple *video* and *audio* tracks. I managed to get the player to show me the audio tracks list and I can switch between them, but that's not the case with video tracks.

I'm trying to serve a video with multiple tracks, where:
* Main video track: normal video.
* Main audio track: normal audio.
* Alternative video track: video with some required pauses for descriptive audio to sync properly.
* Alternative video track: descriptive audio.

The docs do not specify how can that be implemented and I do not see any example on the examples folder.

Thanks!

**Comment by gkatsev** [comment]
What media type are you using it with? HLS? mp4?
For mp4, browsers (aside from safari) don't support audio or video tracks.
For HLS, we [don't currently support](https://github.com/videojs/http-streaming/blob/fae533e02e6b5bff08ecf9f50163480987ce56e7/design/media-groups.md#future-considerations) video tracks in VHS and I think only Safari supports it natively.

However, the video track API is similar to the audio track API.

**Comment by estebanz01** [comment]
I'm using HLS and I can create some MPEG-DASH xml as well.
OK, I think I'll find another way to expose the alternative video, probably as another video file.

Thanks for the info!
