### ISSUE TITLE
How to remove the click event of the progress bar 

### ISSUE THREAD

**Issue by xiaomengheiheihei** [videojs/video.js#5810]
The project I'm working on doesn't want to change the video schedule when I click on the progress bar, so I want to drop the click event of the progress bar, but I haven't found a good solution.

I hope someone can help me.

Thanks！

**Comment by gkatsev** [comment]
You can [disable the progress bar ](https://docs.videojs.com/progresscontrol#disable)
Something like:
```js
player.controlBar.progressControl.disable()
```
It'll then prevent mouse events on it until `enable` is called.
