### ISSUE TITLE
Question: Is it supported to play from separate audio and video files?

### ISSUE THREAD

**Issue by khashish** [videojs/video.js#5811]
Hello everyone,

I have a use case where I have the video file(no audio) and the audio file as two separate files. Basically what I want to do is to be able to playback both the video and the audio files together. I couldn't find any example as to how to do this other than using MPD/HLS. 

Is there any other way that I can play a video file together with another audio file in videojs possibly using the audio tracks api ?

Thanks.

**Comment by gkatsev** [comment]
You can do it in HLS and MPD. Here's an example from the HLS spec: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-8.6

I would definitely advise against going the multiple element route as it's likely to cause more issues. Investigating HLS and DASH is definitely the recommended approach.

**Comment by khashish** [comment]
@gkatsev Thanks alot for your quick response will give it a try with the DASH and HLS approach
