### ISSUE TITLE
how to disable text tracks?

### ISSUE THREAD

**Issue by coolicer** [videojs/video.js#5812]
## Description
I don't want to use text tracks(or subtitle / captions ?).

**Comment by tomByrer** [comment]
Have a demo so we can see how your are using VideoJS?

**Comment by OwenEdwards** [comment]
The easiest way to not use text tracks (subtitles or captions) is to not include them in the HTML or JavaScript which creates the video player in the first place. Otherwise, you could just disable the control bar control for subtitles and captions (the `subsCapsButton`):

```
videojs('my-player', {
  controlBar: {
    subsCapsButton: false
  }
});
```

**Comment by gkatsev** [comment]
We don't currently provide a way to remove text track support from Video.js, though custom/modular builds are coming. In the meantime, you can disable the button as @OwenEdwards mentioned above or make sure that captions aren't added to the player.

**Comment by justinIs** [comment]
Unless I'm misunderstanding the question, I have a similar desire to start the video with the captions toggled off.

I want the button to still be there. I just want to have the video playing with the captions toggled off.  Is this possible via the config?

**Comment by gkatsev** [comment]
Yup, if your captions aren't set to `default: true` it'll be available but not turned on by default.
