### ISSUE TITLE
DOMException: Failed to execute 'setAttribute' on 'Element': '$' is not a valid attribute name.

### ISSUE THREAD

**Issue by jviney** [videojs/video.js#5813]
## Description

`DOMException: Failed to execute 'setAttribute' on 'Element': '$' is not a valid attribute name.`

This error occurs when creating the video player.

## Steps to reproduce

We have not been able to reproduce this bug in our local testing, but it its regularly reported through our production error tracking. It occurs when creating the video player on Mobile Safari.

We are running VideoJS in an Ember app. VideoJS is created as part of the EmberJS component lifecycle.

### Expected
Create the video player without this error.

### Actual
DOMException: Failed to execute 'setAttribute' on 'Element': '$' is not a valid attribute name.

## Additional Information

The source of this error is [Player#createEl](https://github.com/videojs/video.js/blob/master/src/js/player.js#L664):
```
    Object.getOwnPropertyNames(attrs).forEach(function(attr) {
      // don't copy over the class attribute to the player element when we're in a div embed
      // the class is already set up properly in the divEmbed case
      // and we want to make sure that the `video-js` class doesn't get lost
      if (!(divEmbed && attr === 'class')) {
        el.setAttribute(attr, attrs[attr]);
      }

      if (divEmbed) {
        tag.setAttribute(attr, attrs[attr]);
      }
    });
```

`attrs` is normally something like:

```
{"id":"vjs_video_3","autoplay":true,"muted":true,"playsinline":true,"preload":"auto","poster":"<url here>","class":"video-js ","tabindex":"-1"}
```

This looks fine.

However, occasionally in Safari `Object.getOwnPropertyNames(attrs)` returns the properties of `window` instead of `attrs`!? Eg:

`Object,Function,Array,Number,parseFloat,parseInt,Infinity,NaN,undefined,Boolean,String,Symbol ...`

Our `window` contains `$` for jQuery, which then causes the error above.

I do not know why this sometimes occurs on Safari. Does anyone have any idea?

Perhaps using `Object.keys(attrs)` instead of `Object.getOwnPropertyNames(attrs)` would fix the issue for us. We will probably try that soon.

To me this looks like it could possibly be an iOS Safari bug.

#### videojs
7.4.1 and many previous versions
#### browsers
Occurs intermittently on iOS Mobile Safari (10, 11, 12).
#### OSes
iOS

**Comment by jviney** [comment]
Using `Object.keys` instead of `Object.getOwnPropertyNames` appears to fix this problem. However, now the same problem occurs in another place where `Object.getOwnPropertyNames` is used is a similar way.

Thoughts from any of the maintainers? Could this be a Safari bug?

**Comment by jviney** [comment]
We have worked around this problem on iOS Safari for now:

```
  if (isMobileSafari) {
    Object.getOwnPropertyNames = Object.keys
  }

  try {
    return VideoJs(el, options)
  } finally {
    if (isMobileSafari) {
      Object.getOwnPropertyNames = originalGetOwnPropertyNames
    }
  }
```

This does seem like a pretty odd fix though, and could cause other problems.

**Comment by salemhilal** [comment]
I'd like to note that we have the same issue, also on version 7.3.0.

**Comment by salemhilal** [comment]
Hey @jviney, it sounds like you were able to reproduce the bug (unless you patched `getOwnPropertyNames` and watched your error logs). What did you end up doing?

**Comment by jviney** [comment]
We use the code above. We were not able to reproduce the bug.

The bug still occurs very rarely on non-iOS systems. We get occasional error reports on Edge 17, 18, and even Chrome on Windows. But for the most part this change seems to have solved the problem for us.

It could be broadened to include all browsers - but we haven't done that.

**Comment by TVS-Bruno** [comment]
Hello,

I have the same issue on VideoJS 7.55 with Safari 12.1 not reproducible in local but we have it in production. For me, the problem is not solved, and sorry @jviney but your workaround is dangerous. I didn't try it but it's strange that it works, the difference between getOwnPropertyNames() and keys() is that keys() only returns enumarable properties and '$' is an enumerable property, both return it.

**Comment by SVyatoslavG** [comment]
Having the same issue. Can't reproduce the bug locally but getting 5-10 bug reports from JS our production error tracking.

**Comment by gkatsev** [comment]
If someone can provide a live reduced test case, we can take a look. Otherwise, it's kind of hard to figure things out and help.

**Comment by golmansax** [comment]
Want to echo that we have seen this issue with Video.js 6.13.0 and Mobile Safari 12.1.2, 13.0.4, 13.0.5.

**Comment by golmansax** [comment]
In case it helps, we're seeing the issue on Facebook and Google browsers (see screenshot below).  Also this weird key below is being grouped in this same error.

`Failed to execute 'setAttribute' on 'Element': 'MOATMTU5MDQyMjY4Mw==' is not a valid attribute name.`

<img width="874" alt="Screen Shot 2020-05-25 at 17 06 51" src="https://user-images.githubusercontent.com/5068929/82843199-671ffd00-9eaa-11ea-8640-eb18b4ba9f74.png">
