### ISSUE TITLE
Option to Select/Change Video quality

### ISSUE THREAD

**Issue by Abdulmanan0315** [videojs/video.js#5818]
## Description
This is basically not a issue but a question itself.
Is there any option by which we can enable video quality selection? If so please provide an example i ll be very much grateful .Thanks for the great plugin. 

### Expected
I want to have a button that can select video quality like Youtube.

**Comment by bc-paul** [comment]
There isn't an out of the box solution in video.js for a quality selection button or menu. However, you can use the [representations() method](https://github.com/videojs/http-streaming/blob/609beb3400bde4f3c5469acdc0a2c681c736c287/README.md#hlsrepresentations) or the [videojs-contrib-quality-levels plugin](https://github.com/videojs/videojs-contrib-quality-levels) as a base.

**Comment by AntonTrapp** [comment]
Just in case you didn't tried that (or maybe it fits to your problem):

If the quality depends on the screen resolution or bandwidth .m3u8 is supported and makes the adjustments just fine. For me the solution was to change the player size - and the system then checks if there is enough bandwidth for that size and chooses that, if not you get a lower resolution video. But not higher than needed. So I just made some resolution buttons and the quality adjusts automatically.

**Comment by Abdulmanan0315** [comment]
Is there any way we can enable quality levels for mp4 localy hosted video? or We can define size attribute in Video Sources,Like
<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" type="video/mp4" size="576">
<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-720p.mp4" type="video/mp4" size="720">
<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-1080p.mp4" type="video/mp4" size="1080">

**Comment by Abdulmanan0315** [comment]
Or infact a working example of [videojs-contrib-quality-levels](https://github.com/videojs/videojs-contrib-quality-levels) With video-js v7 or Above might help anyone .

**Comment by bc-paul** [comment]
videojs-contrib-quality-levels doesn't have built-in support for MP4s. 

It has built-in support for [videojs-contrib-hls (HLS), and videojs/http-streaming (HLS/DASH)](https://github.com/videojs/videojs-contrib-quality-levels#supported-projects). The [index.html](https://github.com/videojs/videojs-contrib-quality-levels/blob/master/index.html) is a good example if you can get a hold of that kind of content. 

You can also see it in action [here](https://codepen.io/anon/pen/drGxNr).

This [plugin](https://github.com/silvermine/videojs-quality-selector) could be an option for you  however, it's not maintained by the core Video.JS maintainers.

**Comment by Abdulmanan0315** [comment]
Thanks for the plugin it works.
