### ISSUE TITLE
VideoJs Live Streaming

### ISSUE THREAD

**Issue by AyoubBani** [videojs/video.js#5819]
I'm facing a problem while streaming with videojs. It's like if the player is playing segments in sequence order. I want to force it to play the last downloaded segment. is there any way to do that ?

**Comment by bc-paul** [comment]
This seems to be the same as #5801; the [live ui](https://github.com/videojs/video.js/blob/c1475819b2e2983ece6e0c42ae7a29daaf4ae51b/docs/guides/live.md) should help you accomplish that.

**Comment by gkatsev** [comment]
If the stream is live (i.e., without an end list tag for HLS), then we should be playing back from the live point, which is 3 target durations from the end of the playlist.
We don't really have an option to be closer, but if you want to be more live, try making shorter segments. We're currently working on low latency live hls support, but it will take a few months before it's ready.
