### ISSUE TITLE
Flash playback slow/choppy in Chrome

### ISSUE THREAD

**Issue by clowerweb** [videojs/video.js#582]
Using VideoJS 4.0.4 (it also did this in version 3) the playback is slow/choppy in Chrome (not tested in other browsers) when using the Flash player. The playback smooths out after the buffer finishes loading the full video. All settings are default except forcing Flash player. Is there any fix for this?

**Comment by devdavidkarlsson** [comment]
This is a very known issue: https://code.google.com/p/chromium/issues/detail?id=142102
Pepper flash has been performling worse that the npapi version. Wonder what will happen when google kick out npapi. https://www.chromium.org/developers/npapi-deprecation

**Comment by heff** [comment]
I think it will only affect those who manually turned off pepper flash?
