### ISSUE TITLE
Segments resolvedUri property ignores updated hostname

### ISSUE THREAD

**Issue by zhulduz** [videojs/video.js#5821]
Hi, 
I get an error with incorrect segment hostname when I get redirect path in source request.

**Descriptive steps**

1. Try to get source `oldHostNameToFile.m38u` through video.js
2. Get an error 303 with redirect header `Location: newHostNameToFile.m38u`
3. Video.js sets incorrect hostname for segment path: resolvedUri contains `oldHostNameToFile`

**Expected**
The player doesn't ignore the hostname in the redirect header, so segment path should contain ` newHostNameToFile`

I hope I made the problem clear)

Are there any solution or is it a bug?

Thanks in advance.

**Comment by gkatsev** [comment]
This is a known issue and we're currently working on it! Unfortunately, for backwards compatibility it'll be turned off by default for a bit, at least. You can track the work over on the http-streaming repo: https://github.com/videojs/http-streaming/pull/412

**Comment by zhulduz** [comment]
Thanks @gkatsev for the quick response
