### ISSUE TITLE
VTTCue error in Chrome

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#5823]
VTTCue error in Chrome (Look like with Audio track options)
Video js error for some HLS video (Videojs 5 can play these video with the HLS Contrib plugin)

`Uncaught TypeError: Failed to construct 'VTTCue': The provided double value is non-finite.`

Error exemple HLS live video: https://rcavlive.akamaized.net/hls/live/664044/cancbft/master.m3u8

**Comment by RafalLukawiecki** [comment]
I am experiencing the same error, but in Firefox desktop, also HLS. Plays in Safari and Chrome. Video.js 6 played correctly, we are just assessing video.js 7, and this is something that just came up. Any clues welcome.

**Comment by gkatsev** [comment]
I have a PR that should fix this: https://github.com/videojs/http-streaming/pull/437
Unfortunately, I can't try the example above, it's giving me a 403.

**Comment by RafalLukawiecki** [comment]
See my comment in your PR, happy to test before the weekend using our media.

**Comment by RafalLukawiecki** [comment]
As I mentioned in the PR comment, your fix resolves the issue. Video now plays in both Chrome and FIrefox (it was OK in Safari). Many thanks, can't wait to get back to further testing of video.js 7.

**Comment by RafalLukawiecki** [comment]
@gkatsev, thanks for closing this issue. Just to confirm: do you still need me to host an externally available video stream for the purpose of testing this issue, or is that no longer needed? It means extra work, so I am happy not to have to do it, but if it helps, I will.

**Comment by gkatsev** [comment]
No, we're all set then, thanks!
