### ISSUE TITLE
Replace node-sass

### ISSUE THREAD

**Issue by tomByrer** [videojs/video.js#5826]
Node-sass is a pain to install for many.  Took me an half an hour of Google, downloading a bunch of MS Visual Studio/C++ stuff that I'll likely only use for node-sass, then re-reinstalling node-sass.  It was great tech 4 years ago, but now feels to be too much when other alternatives are available.

 #### [css-in-js ](https://css-tricks.com/bridging-the-gap-between-css-and-javascript-css-in-js/)
Worth looking into for new projects with some unicorn devs, [many options available](https://blog.bitsrc.io/9-css-in-js-libraries-you-should-know-in-2018-25afb4025b9b), but perhaps too much rewriting for a legacy project like this.

#### [Dart-Sass](https://sass-lang.com/dart-sass)
The reference SASS (RIP Ruby).  Can be used from CLI as binary, or [complied as JS](https://www.npmjs.com/package/dart-sass), which could be a bit slower than binary, but might be fast enough.

#### PostCSS
Seems switching to PostCSS [requires little extra coding](https://medium.com/@im.simonecorsi/moving-from-sass-to-postcss-why-what-and-how-f68b1bc760dc), considering you'll have to sweep though to remove baked-in prefixes & let [Autoprefixer](https://github.com/postcss/autoprefixer) handle that chore. [PostCSS SASS](https://github.com/jonathantneal/postcss-sass) will load Dart SASS if you want less friction, but Dart SASS might have a few differences with libsass.  Perhaps adding some [new CSS tech](https://css-tricks.com/bridging-the-gap-between-css-and-javascript-css-modules-postcss-and-the-future-of-css/#article-header-id-1) will benefit Video.JS also.  Popular enough & used in many large projects.

Most of the projects listed are recently updated.  I vote PostCSS, since it is fast, JS-only to avoid installing extra headaches, reduces the transition costs.

Thoughts?

**Comment by gkatsev** [comment]
This is definitely something that we have been thinking about. We definitely feel the pain of node-sass but moving away from sass is no easy task. While our CSS isn't really that complex, rewriting it away from sass is not trivial by any means. In addition, we expose our sass files in npm, so, moving away from it would be a breaking change and we're not quite ready for another major rev just yet.
dart-sass might be fine, at least the non-binary version, depending on how much slower it is. We don't want to depend on anything that can't be installed via npm and if the compiled-to-js version isn't 10x slower (2x slower is probably fine), we can probably make the switch.
Also, any change has to be backwards compatible.

Would you be interested in conducting some experiments with the `sass` npm package to see what the speed differences are?

Also, doesn't node-sass have windows binaries? For me, it generally just downloads the right thing and it works, though, yeah, if that doesn't work it's probably a painful process.

**Comment by tomByrer** [comment]
Thanks for fast reply!

> moving away from sass is no easy task

I was thinking the rest of your (plural) work at BrightCove might involve more SASS as well...

Can't commit to Dart-Sass experiments now, but I'll put it in my TODO bin!  I'm more interested to see if PostCSS can be a drop-in replacement.

> Also, doesn't node-sass have windows binaries?

`npm install` makes me build using [`node-gyp`](https://github.com/nodejs/node-gyp#installation) to build, which requires Python 2.7 (NOT 3.x) & MS Visual C++ Build Environment, then a few CLI commands for paths.  It was a pain in the sass, but once installed I can `yarn` any repo with the current `node-sass` just fine, for both a plugin & Video.js main repo.
However, I suspect I have to rebuild when I change node versions, since I use 'node version manager for windows' (installs each node version in a fresh folder for easy switching).

**Comment by thijstriemstra** [comment]
> Node-sass is a pain to install for many.

Fair enough, but how manuy actually checkout video.js code/plugins and work on it? It's a noble cause but not sure if this is worth the effort.

**Comment by gkatsev** [comment]
> I was thinking the rest of your (plural) work at BrightCove might involve more SASS as well...

It's definitely still used in some places but we have moved away from it where we could.

We can definitely plan on moving away from sass, but there generally ends up being more important or interesting things to work on. And @thijstriemstra makes a good point that to many people, it doesn't really matter as they just use the pre-build files.

> I'm more interested to see if PostCSS can be a drop-in replacement.

Unfortunately, I really doubt that's possible. It would need to compile the CSS as-is and create a backwards compatible output.

> `npm install` makes me build using [`node-gyp`](https://github.com/nodejs/node-gyp#installation) to build

Aaah, right, it doesn't just curl it or something.

**Comment by tomByrer** [comment]
> how many actually checkout video.js code/plugins and work on it?

Well you do have almost 5,900 forks of the main repo alone :)   Maybe not as many messing with plugins (like me).  But those numbers are tiny compared to  your user base.  I understand those users are your main concern.

**Comment by tomByrer** [comment]
Ooops, [Dart allows only UTF-8 files](https://www.npmjs.com/package/dart-sass#behavioral-differences-from-ruby-sass), not sure if you guys want the encoding changed?

```cli
~/OneDrive/Documents/github/tombyrer/webvtt/scss-video.js/src/css (master)
$ file --mime-encoding *
_print.scss:             us-ascii
_private-variables.scss: us-ascii
_utilities.scss:         us-ascii
_variables.scss:         us-ascii
components:              binary
utilities:               binary
video-js.scss:           us-ascii
vjs.scss:                us-ascii
vjs-cdn.scss:            us-ascii
```

**Comment by mister-ben** [comment]
UTF-8 encodes the characters in us-ascii the same as us-ascii for backward compatibility, so a UTF-8 file with only characters in that range is identical to us-ascii. (Unless you use byte order markers with UTF-8, which generally you should not).

**Comment by tomByrer** [comment]
> a UTF-8 file with only characters in that range is identical to us-ascii

Are you worried about non-US-ASCII characters getting into the SASS files?  If so, how will you enforce it?

**Comment by tomByrer** [comment]
I looked at using only PostCSS & their huge ecosystem that would likely work with Video.js' current scss codebase with minor tweaks, but decided to run with `dart-sass` instead for legacy compatibility.

But if I would start a new larger project, I'd start with CSS (including new & future specs), use PostCSS to make compat browser CSS & add dashes of SCSS branching & looping with PostCSS plugins.  Easier to have people just to learn CSS & a few extra commands than re-learn SCSS's programming.  SCSS feels like jQuery to me; great tech for it's time, but an extra API that's not needed now.
