### ISSUE TITLE
HLS Stream set currentTime relative to the Presentation Timestamp

### ISSUE THREAD

**Issue by silltho** [videojs/video.js#5827]
Hey

First of all i want to thank you for your great work maintaining this project.

I'm using video.js in our ReactJS project to show a HLS Live Stream. As part of the requirements i have to set the currentTime relative to the PTS (Presentation Timestamp). 
An example would be a movie stream which the client is opening an hour after the movie was started. The currentTime (or this.player.seekable()) of the downloaded chunks would be a few seconds, but the PTS is already over an hour.

We want to set the currentTime relative to the PTS not the seekable time. Is there any chance to calculate and set the currentTime relative to the PTS.

As far as i could tell from reading the docs, there is no way to get PTS relative to the current seekable TimeRange nor getting the PTS at all.

I hope my description is understandable and someone can help me.
Thanks

**Comment by gkatsev** [comment]
Unfortunately, I don't think the PTS information is really exposed anywhere. And if you need to support Safari, at least on iOS, you don't have any control over this.

**Comment by silltho** [comment]
I'm now using [hls.js](https://github.com/video-dev/hls.js) to achieve this. It gives u access to the PTS time in the INIT_PTS_FOUND event.
