### ISSUE TITLE
hotkeys focus question

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#5832]
Testing the new keyboard hotkeys feature, and the docs state:

"Note that the `Space` key activates controls such as buttons and menus if that control has keyboard focus. The other hotkeys work regardless of which control in the player has focus."

But the hotkeys **do not** work regardless of which control in the player has focus, they only work after clicking the control bar (anywhere) or any other control. Can this be confirmed?

My config:

```javascript
var options = {
    controls: true,
    width: 320,
    height: 240,
    fluid: false,
    userActions: {
        hotkeys: function(event) {
            // `this` is the player in this context

            // `x` key
            if (event.which === 88) {
                console.log('x');
            }
            // `y` key
            if (event.which === 89) {
                console.log('y');
            }
        }
    }
};
```

**Comment by gkatsev** [comment]
If you provide a function to `hotkeys`, you're expected to implement your behavior, none of the default behaviors are applied. This probably should be made more explicit in [the docs](https://github.com/videojs/video.js/blob/master/docs/guides/options.md#useractionshotkeys)
https://github.com/videojs/video.js/blob/e612056bfa8e6e77ca6379e74ba14e9a75da32d6/src/js/player.js#L2782-L2790

**Comment by thijstriemstra** [comment]
I did implement a function, but none of the keys (either default of custom key function) work unless you first click the control in question, or the control itself.

**Comment by OwenEdwards** [comment]
@thijstriemstra just trying to clarify what you're saying (without having a test case to look at); are you expecting hotkeys to work on a player in a page even if keyboard focus isn't on some part of the player? That's to say, page-wide hotkeys for the video.js player?

**Comment by thijstriemstra** [comment]
@OwenEdwards yea that is what I understood from the docs:

`The other hotkeys work regardless of which control in the player has focus.`

Maybe the docs should clarify there isn't support for page-wide hotkeys for the video.js player?

**Comment by gkatsev** [comment]
Yeah, we should clarify that it only works when there is focus inside the player. This is for accessibility purposes, so if you are somewhere else on the page, hitting a key won't do something unexpected with the player.

It may be useful to have an option to turn on global hotkey support, though.

**Comment by thijstriemstra** [comment]
> It may be useful to have an option to turn on global hotkey support, though.

+1

**Comment by OwenEdwards** [comment]
Yeah, I'm not sure I fully understand how global hotkey support would work, though. If you have more than one player in a page, in particular, which one should a global hotkey affect if none of the players (or their components) have focus?

> The other hotkeys work regardless of which control in the player has focus.

Right - "which control in the player has focus", not "whether any control in the player has focus".

Strictly speaking, this hotkey feature isn't "for accessibility", so much as hotkeys are something that a lot of users (and designers/developers) want, and it's tricky to implement them in a way that doesn't _break accessibility_. Page-wide hotkeys would definitely have other accessibility impacts.

**Comment by Ashesh3** [comment]
> > It may be useful to have an option to turn on global hotkey support, though.
> 
> +1

+1 , i have only one player in my page and i need global hotkey support please. Many other players have this feature and it'll make videojs more complete to have it. Thanks

**Comment by gkatsev** [comment]
Unfortunately, we don't have the bandwidth to add that feature but we can direct people who are interested in submit a PR.
