### ISSUE TITLE
Twitch integration with VideoJS

### ISSUE THREAD

**Issue by masudhossain** [videojs/video.js#5835]
Is it possible to integrate twitch with videojs too? We depend on a lot of dependencies from videojs.

If anyone is willing to do this, i'm paying.

Docs: https://dev.twitch.tv/docs/embed/video-and-clips/#interactive-frames-for-live-streams-and-vods
Example: http://prntscr.com/ms1daa

it's pretty easy to get the twitch video all setup, i just wanna "connect" it with videojs.

**Comment by masudhossain** [comment]
UPDATE: It's been built. We will open source it if anyone wants.

**Comment by kvrban** [comment]
> UPDATE: It's been built. We will open source it if anyone wants.

@masudhossain Yes, please share the source. I'am looking for the same solution.

**Comment by aolko** [comment]
@kvrban [over here](https://github.com/masudhossain/videojs-twitch/blob/master/videojs-twitch.js)

**Comment by kvrban** [comment]
perfect, thanks!

**Comment by fandy** [comment]
@masudhossain your repo seems to be deleted. Would you mind sharing it again? 🙏

**Comment by snaildos** [comment]
?? why is the repo deleted??
