### ISSUE TITLE
Feature Request: Support for incomplete source files which are still beeing written

### ISSUE THREAD

**Issue by platinum55** [videojs/video.js#5837]
## Description
trying to play video files which are still transcoding, with enough room for the client to watch until he reaches the actual transcoding point(EOF)

## Steps to reproduce
1. transcode a video, i.e. with ffmpeg
2. while transcoding, access the file which was just created and is incomplete yet
3. see the playback stopping at the point where the filesize was when player/webserver opened the file

### Expected
Maybe an option "maybeIncomplete" - to tell the player to retry and compare the reported Content-Length from (web-)server, if greater then before, continue fetching chunks to keep playback alive :)

### Actual
Video stops exactly at the point where the server reported EOF(Content-Length) when video started.

### Error output
No Errors.

## Additional Information
At least with mp4-files, the browser/player always requests the whole file instead of (useful) chunks (header: Range: 0-)

I tried to fake the "real" or bigger size via webserver and php, but the client is not sending any additional requests, even if the servers replies with less bytes then the client requested. for example:

Request has header "Range: 0-" - which means "send me anything  starting with byte 0".
Reply has header "Content-Range: 0-5000".
Client should send another request starting at offset 5000, which he doesn't.

#### videojs
latest master branch

#### browsers
Chromium Version 71.0.3578.98
#### OSes
xubuntu 18.10
### plugins
none

**Comment by gkatsev** [comment]
Is this for an mp4? If so, we're unlikely to add support for it ourselves as mp4 playback is almost always handled by the browser. I would suggest maybe outputting HLS/DASH?
However, it should be possible to do it via MSE and byte-range requests. You could create a tech or a source handler that loads the mp4 by chunks. Also, I would guess that this mp4 would need to be some form of fmp4 (ISOBMFF or CMAF) and that a regular old mp4 won't work for this.
