### ISSUE TITLE
how to remove videojs's seekbar click event?

### ISSUE THREAD

**Issue by xiaomengheiheihei** [videojs/video.js#5845]
## Description
I just want to keep the drag event of seekbar, and I don't want users to click on it to adjust the video schedule.

## Try
1. i try to do this "this.player.controlBar.progressControl.seekBar.disable()"
2. this.player.controlBar.progressControl.seekBar.handleClick = () => {}

But none of this is helpful.

Please help me. I've tried my best.

**Comment by gkatsev** [comment]
```js
this.player.controlBar.processControl.disable()
```
[should work](https://docs.videojs.com/progresscontrol#disable). Doing it on the seekBar itself is probably too low level.

**Comment by xiaomengheiheihei** [comment]
The way you provide it doesn't work, but my problem has been solved. I use a fake progress bar to block the progress bar of videojs, which can prevent the click of the progress bar. Thank you.

**Comment by gkatsev** [comment]
Oh, just remembered we had a bug in Video.js 7.4 related to it, it's fixed in 7.5 (https://github.com/videojs/video.js/pull/5721). 7.5 should be promoted to latest sometime next week.

**Comment by mr1985** [comment]
> ```js
> this.player.controlBar.processControl.disable()
> ```
> 
> [should work](https://docs.videojs.com/progresscontrol#disable). Doing it on the seekBar itself is probably too low level.

The following works on v7.5.0
`player.controlBar.progressControl.disable()`
