### ISSUE TITLE
Audio Tracks Not Switching

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#5848]
## Description
I have encoded my hls with audio tracks and it works fine in safari you can use the menu to switch between tracks but when using videojs it always uses the same track no matter what one I select.

You can test with this url in Safari native. 
https://dwpurpmwfzvap.cloudfront.net/videojs-for-github/master.m3u8

And here is an example template with VideoJS.
https://jsbin.com/gutaras/11/edit?html,output

## Steps to reproduce
Paste url directly into Safari and change audio tracks in menu
Use the example template with latest VideoJs and you will see the issue

### Expected
Audio tracks to change like they do in Safari native.

### Actual
VideoJs doesn't switch tracks

### Error output
None

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Latest

#### browsers
all

**Comment by samueleastdev** [comment]
Updated template: https://output.jsbin.com/gutaras/8

**Comment by samueleastdev** [comment]
Sorry I removed my example and file I have added everything again for testing I tried to access the tech directly as its working in hls.js but no luck. Even with the bipbop videojs example, it will fail if you click it a few times.

**Comment by monkeytroy** [comment]
> Sorry I removed my example and file I have added everything again for testing I tried to access the tech directly as its working in hls.js but no luck. Even with the bipbop videojs example, it will fail if you click it a few times.

Did you happen to figure this out?   I see the same issue.

**Comment by gkatsev** [comment]
We recently fixed an issue regarding audio track switching in Video.js: https://github.com/videojs/video.js/pull/7163. It's available in 7.12.x.
