### ISSUE TITLE
Video.js video in IE 11 shows audio button when not needed

### ISSUE THREAD

**Issue by Footprint-Addons** [videojs/video.js#5851]
I'm experimenting with videojs and when I play a HLS video on EI 11 on Windows 8.1, it shows an audio button and when you hover over it, it shows two options: Default and Unknown. Clicking on either of them results in crashing the video. Reloading the page doesn't work, I have to set the cursor in the address bar gain and hit enter before it shows the initial video again.
I can use css like: .videojs-audio-button{display:none}
to hide the button but I wonder why it shows up in the first place since no separate audio versions are included in the m3u8 manifest.
Here is a demo page: https://enterprise.wp21century.com/videojs/hls-encrypted.html

![videojs-audio-button](https://user-images.githubusercontent.com/8578344/54086932-70c54f80-434e-11e9-83b8-ed6429d73853.png)
![videojs-audio-button2](https://user-images.githubusercontent.com/8578344/54086933-70c54f80-434e-11e9-85f1-150c3921f1df.png)

### Version
7.5.0

**Comment by OwenEdwards** [comment]
That demo page requires sign in credentials, so it isn't very useful. Can you create a reduced test case?

**Comment by Footprint-Addons** [comment]
Oh, sorry, I forgot about that, OwenEdwards. Here is the test: https://enterprise.wp21century.com/videojs/hls-encrypted.html
Thank you beforehand!

**Comment by Footprint-Addons** [comment]
Anyone has this issue also?

**Comment by gkatsev** [comment]
I would look into setting [overrideNative](https://github.com/videojs/http-streaming#overridenative), as I believe we default to native playback on MS Edge but our playback engine likely works better.

**Comment by Footprint-Addons** [comment]
Someone was so good to give me a solution via e-mail.  Here it is:

> I would look into setting [overrideNative](https://github.com/videojs/http-streaming#overridenative), as I believe we default to native playback on MS Edge but our playback engine likely works better.

It works fine for me when adding the following:
` 
  { html5: {hls: {overrideNative: true}}, 
`

**Comment by polucorus** [comment]
I've had this issue initially and solved it by removing that unknown audio track upon the loadedmetadata event, but it stopped working once I introduced a preroll. The overrideNative solution, fortunately, works in both scenarios, thanks.
