### ISSUE TITLE
Can not play HLS video if segment type is combined. 

### ISSUE THREAD

**Issue by zlatkojosic** [videojs/video.js#5866]
## Description

Can not play HLS video if segment type is combined. 

In video.es.js:

        var type = segment.type;
        var data = segment.data;
        var initSegment = segment.initSegment;
        segmentObj[type].segments.push(data);

I get type=combined, segmentObj only has video and I get error

### Error output
TypeError: segmentObj[type] is undefined[Learn More]
video.es.js:35248

    sortedSegments video.es.js:35248 reduce (index):359 processPendingSegments_ video.es.js:35244 done_ video.es.js:35038 onmessage video.es.js:34935 

#### videojs
7.4.1
#### browsers
Firefox
#### OSes
MacOS

**Comment by hold-baby** [comment]
I have the same problem.

**Comment by gkatsev** [comment]
Do you have a test stream we can try out?

**Comment by zlatkojosic** [comment]
Here is test stream link http://95.216.117.37:81

**Comment by hyingreborn** [comment]
I have the same problem.
@zlatkojosic Do you have a solution now?

**Comment by zlatkojosic** [comment]
Hi,

Sorry for the late response. No, I did'nt find a solution.
I'am going to open this question again.
