### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#5869]
Guys, can you please tell me if it's possible to add a custom ads video before each video playing?

**Comment by giggioman00** [comment]
I mean pre-roll video ads
the plugin doesn't work anymore, How can I add that

**Comment by gkatsev** [comment]
We maintain [videojs-contrib-ads](https://github.com/videojs/videojs-contrib-ads) which allows easier integrate of ad libraries with Video.js. However, we don't maintain any ad plugins directly. [videojs-ima](https://github.com/googleads/videojs-ima) is a well used one that should work with any VAST/VMAP
