### ISSUE TITLE
Can't get bufferedPercent()

### ISSUE THREAD

**Issue by DONSA** [videojs/video.js#587]
I want to play an HTML5 video only after it loads, so i used the "var howMuchIsDownloaded = myPlayer.bufferedPercent();" to know when the buffering is done (=1) . 
However the variable "howMuchIsDownloaded"  is always zero and it stuck's in the loop.
Any help?
I have the following code:

VideoJS("video_logo_1").ready(function(){

```
var myPlayer = this;
```

  do{
   var howMuchIsDownloaded = myPlayer.bufferedPercent();
   alert(howMuchIsDownloaded)
  } while (howMuchIsDownloaded<1);

```
myPlayer.play();  //start playing the video 
```

 });

**Comment by chandr123** [comment]
Here you find the answer :)

http://dinbror.dk/blog/how-to-preload-entire-html5-video-before-play-solved/
