### ISSUE TITLE
How to show preview frame image when hover on control bar

### ISSUE THREAD

**Issue by quangnd92** [videojs/video.js#5871]
## Description
How to show preview frame image when hover on control bar like youtube?
![image](https://user-images.githubusercontent.com/12739900/54513709-c91dd200-498a-11e9-9859-82b99234c384.png)

**Comment by gkatsev** [comment]
There are plugins like [videojs-vtt-thumbnails](https://www.npmjs.com/package/videojs-vtt-thumbnails) that do this. However, we have no plans to add it natively to the core of Video.js.
