### ISSUE TITLE
"The play request was interrupted by a new load request"

### ISSUE THREAD

**Issue by evanfarina** [videojs/video.js#5875]
## Description
Briefly describe the issue.
Reproduction is not trivial, but we are seeing many errors in our company error log due to this issue. The issue occurs when a `play` request is in-motion at the time of teardown. On teardown, `resetMediaElement` is called which proceeds to call `video.load()`.

## Steps to reproduce
Again, difficult to setup a reproducible demo but here is the issue, [simplified in a jsFiddle](https://jsfiddle.net/pe1htmw8/1/). See the console for an error.

### Expected
There should be no error.

### Error output
"The play request was interrupted by a new load request"

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
video.js @7.4.1
#### browsers
Chrome
#### OSes
I'm currently on a Mac, but this is an OS-independent issue
### plugins
None.

**Comment by gkatsev** [comment]
Being worked on in #5876
