### ISSUE TITLE
RTMP cannot be played on mobile phones

### ISSUE THREAD

**Issue by luguoeryi** [videojs/video.js#5877]
## Description
The problem I encountered was
My video stream format is rtmp, but Unable to play at phone Webpage，
The code was written as an example, 
I wonder if it's because the mobile phone webpage itself can't play rtmp ?

**Comment by gkatsev** [comment]
Unfortunately, you cannot use RTMP on mobile devices. RTMP is a flash-based technology and no modern phone allows the usage of flash, nor do they implement RTMP natively. I would recommend you take a look at HLS or DASH.

**Comment by luguoeryi** [comment]
Okay, you've got a quick response, 
Thank you very much for your answer
Good night
