### ISSUE TITLE
Incorrect decoding of subtitles embedded in manifest

### ISSUE THREAD

**Issue by pkosmala** [videojs/video.js#5882]
## Description
Special characters in subtitles are not displayed correctly resulting in `å` being shown as `Ã¥`. 

## Steps to reproduce
1. Load up video src with a manifest that has embedded subtitles. Example contents can be found below: 

> #EXTM3U
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Dansk",DEFAULT=NO,AUTOSELECT=NO,FORCED=NO,URI="https://domain.com/mu/subtitles/playlist/urn:dr:mu:manifest:5b5d29c66187a5106075a3f1?segmentsizeinms=60000&subtitleType=HardOfHearing",LANGUAGE="da"
#EXT-X-STREAM-INF:SUBTITLES="subs",PROGRAM-ID=1,BANDWIDTH=278000,RESOLUTION=640x360,CODECS="avc1.66.30, mp4a.40.2"
https://domain.com/i/all/clear/streaming/f1/5b5d29c66187a5106075a3f1/U--1-8-_04abf6ac510945d580a5253de8a3af5b_,281,434,714,1550,2215,.mp4.csmil/index_0_av.m3u8?null=0

2. Player follows the link to load a list of subtitle chunks:

> #EXTM3U
#EXT-X-TARGETDURATION:60
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:60,
https://domain.com/mu/subtitles/segment/urn:dr:mu:manifest:5b5d29c66187a5106075a3f1?segmentsizeinms=60000&index=0&subtitleType=HardOfHearing
#EXTINF:60,
https://domain.com/mu/subtitles/segment/urn:dr:mu:manifest:5b5d29c66187a5106075a3f1?segmentsizeinms=60000&index=1&subtitleType=HardOfHearing

3. And then it loads a specific WEBVTT chunk:

> WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000
00:00:03.880 --> 00:00:08.520
 I storbyerne står køberne i kø.
    Det væltede ind med folk.
00:00:08.640 --> 00:00:12.720
  Ejendomsmæglerne har det godt.
    Syv dage, så var den løst.

### Expected
Subtitles are displayed without any changes like so:
Ejendomsmæglerne har det godt.
Syv dage, så var den løst.

### Actual
Special characters are not shown correctly:
EjendomsmÃ¦glerne har det godt.
Syv dage, sÃ¥ var den lÃ¸st.

#### videojs
6.9.0
#### browsers
IE11+
#### OSes
Windows

**Comment by elsassph** [comment]
Extra notes: server is serving chunks with mimetype `text/plain; charset=utf-8`.

**Comment by mister-ben** [comment]
This was fixed a while back (see #5070), but you're using an older version of Video.js. The fix is in http-streaming as of Video.js 7.2.

**Comment by pkosmala** [comment]
Upgrading to Video.js 7.2 has fixed the issue.
