### ISSUE TITLE
Audio track selection is broken in v7.5.1 on Chrome/Firefox

### ISSUE THREAD

**Issue by 0caspy** [videojs/video.js#5887]
## Description
Audio track selection is broken in v7.5.1 on Chrome/Firefox

## Steps to reproduce
1. setup any HLS stream with more than one audio (even bipbop) with v 7.5.1
2. start video
3. try to change audio track

### Expected
Audio track changed, menu-list correctly rendered.

### Actual
Chrome/Firefox on macOS:
Audio track NOT changed, menu-list incorrectly rendered.

### Error output
no errors

## Additional Information
on 7.5.0 there is no this issue. appeared only on 7.5.1

#### videojs
v 7.5.1
#### browsers
Chrome 72, Firefox 65
#### OSes
macOS Mojave
### plugins
no plugins

**Comment by 0caspy** [comment]
commit 142cc67 (changes to src/js/tracks/audio-track-list.js) introduce this behaviour.

reverting back addeventlistener to:
  track.addEventListener('enabledchange', () => {...code here...});
recovers audio track switching.

**Comment by gkatsev** [comment]
Thanks, we'll take a look.

**Comment by gkatsev** [comment]
Should be fixed in 7.5.2. Thanks for opening the issue!
