### ISSUE TITLE
Link to cdn with IE8 compatible videojs is broken

### ISSUE THREAD

**Issue by lab6net** [videojs/video.js#5889]
## Description
Heres the link (from getting started page on site):
https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js

## Steps to reproduce
Try to open link above in any browser

## Results
Server responds access denied

### Expected
Script should be served

### Actual
Server outputs xml with access denied message

### Error output
As above

**Comment by gkatsev** [comment]
We probably should just hardcode the url at this point. ie8-version is supposed to be updated based on information received in runtime but we're not ever going to update it. You can find it at https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js

**Comment by gkatsev** [comment]
Fix for it should be live on the site now.
