### ISSUE TITLE
Hotkey available only if it's control bar component is visible

### ISSUE THREAD

**Issue by cosmini** [videojs/video.js#5892]
## Description
Fullscreen hotkey ('f') should be ignored if `fullscreenToggle` is undefined or false for under 
control bar.

Same for the other hotkeys ('k', 'spacebar' and 'm' respectively) equivalent to `playToggle` or `volumePanel` components.

If some control bar options are not included it means that there's a reason behind and those actions should not be available at all including via hotkeys or shortcuts.

Or at least to have an easy way to disable the hotkeys if the control bar excludes the component.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Load a player using control bar options without play, volume and full screen toggle

```let player = videojs('progress_bar_video', {
            controlBar: {
                children: {
                    playToggle: {},
                    progressControl: {},
                    currentTimeDisplay: {},
                    timeDivider: {},
                    durationDisplay: {}
                }
            },
          hotkeys: true // this is for the play toggle because we need it
        });
```

2. Load the page and try press 'm' or 'f' key while control bar is in focus

3. Video will be muted or enter fullscreen even if button is not available in control bar

### Expected
On the press of 'm' or 'f' key it should do nothing.
On the press of 'k' or 'spacebar' I should toggle play/pause of the video.

### Actual
On the press of 'm' key video will be on mute.
When 'f' key is pressed video will toggle fullscreen.

#### videojs
7.5.1

**Comment by gkatsev** [comment]
We thought about it but came to the conclusion that they should be configured separately. It's definitely possible that you'd want the hotkey enabled but not the control bar or control. Also, you should be able to configure each item manually or just pass in in a function to have custom functionality altogether. In addition, hotkeys are disabled by default currently and have to be opted in.
We have some documentation about how to turn pieces off or set custom functionality: https://docs.videojs.com/tutorial-options.html#useractions-hotkeys.
