### ISSUE TITLE
Loading fragments from another source (non CDN)

### ISSUE THREAD

**Issue by MarkoNikolov** [videojs/video.js#5893]
Hello. This is my first time posting an issue here so sorry if my question/issue is a bit off.

I'm using video.js with webRTC and I'm passing fragments from one user to another.
Is there a way to load the fragments I have transferred?
I've used HLS.js previously and the pLoader allowed me to load the fragments via a callback.
My concrete issue is not being able to load any fragment other than those I have received as a response from the CDN.

Is there maybe a workaround or is it already available and I'm just missing it?

**Comment by gkatsev** [comment]
Unfortunately, we do not currently have an API for loading chunks manually. You either need to have an HLS or DASH playlist or handle most things yourself via a Tech or a Source Handler.
