### ISSUE TITLE
"Next" button does not appear in Safari(iOS) and Firefox + Safari (macOS Mojave) when video playback ended

### ISSUE THREAD

**Issue by TokugawaTakesi** [videojs/video.js#5900]
## Description
In the case when playlist has more than one video, once video playback ended, "next" button does not appear. Occurred in:

- Device: iPhone 8
- OS: iOS
- Browser: Safari

and

- Device: PC
- OS: macOS Mojave
- Browser: Firefox 65.0.1 (64bit) and Safari 12.0.3

![image](https://user-images.githubusercontent.com/41653501/55132180-d98d3400-5164-11e9-9b28-4c1d8ee796a3.png)

## Steps to reproduce
1. Prepare one of above environment
2. Prepare some playlist
3. Setup video player with following options:

```json
{
  "inViewPlay": false,
  "autoplay": false,
  "preload": false,
  "controls": true,
  "muted": false,
  "nativeControlsForTouch": false,
  "controlBar": {
    "volumeMenuButton": true,
    "currentTimeDisplay": true,
    "remainingTimeDisplay": true,
    "volumePanel": {
      "inline": false
    }
  }
}
```

4. Launch any video and wait until it will end (if video is long, using timeline is O'K). 
5. When video playback ended, if "next" button will not appears, the bug reproduction is success.

### Expected
In the red rectangle area, "next" button will appear.

![image](https://user-images.githubusercontent.com/41653501/55132199-f0338b00-5164-11e9-8a21-bd5f8788b5b5.png)

**Comment by gkatsev** [comment]
Video.js has no natively playlist functionality built-in. Are you using a particular plugin? Do you have a live example we can take a look at?

**Comment by TokugawaTakesi** [comment]
Oh, very sorry. You right, we use [videojs-playlist](https://www.npmjs.com/package/videojs-playlist) library. Unfortunately, I have not permission to publish out application. If you have not any recommendationsб, please close this issue. Sorry for improper issue.

**Comment by gkatsev** [comment]
videojs-playlist doesn't include any buttons either. Unfortunately, I'm not sure there's much we can do to help.
