### ISSUE TITLE
MIddlewares and React

### ISSUE THREAD

**Issue by iseekyouu** [videojs/video.js#5901]
## Description
There is a problem with cleaning up the middlewares, I can not remove the middlewares that Im added to videojs by myself.

### Expected
only one middleware on videojs after react component initialization;

### Actual
I am using React 16.6.
On the file page I have import videojs from 'video.js';
On componentDidMount im add middlware on videojs `videojs.use middleware ('*', player => ({...})`
on `componentWillUnmount`, I do `player.dispose()`;
Then, without overloading the page, I go to the login page (or any other, the main thing is that there is no reload), then I return to the page with the file and the following situation is obtained.
I have 2 middlvars hanging on videojs!
the first with the old component of which is already gone, and the second with the current one.

The documentation does not have a method for cleaning middlewares, there is a clearCacheForPlayer method called in `dispose()`, but it cleans `middlewareInstances`, this is useless, since all middlewares are stored in the middlewares object.

How can I remove all the middleware?
#### videojs
7.5.2
#### browsers
chrome latest
#### OSes
linux\windows\mac
### plugins
videojs-quality-selector

**Comment by gkatsev** [comment]
The way that middleware are designed is that the middleware itself is attached globally to Video.js and then each player initialization, the middleware method is called with a new player. The middleware will then be called depending on whether setSource called `next` with an error or not.
You shouldn't be calling videojs.use() on componentDidMount.

**Comment by iseekyouu** [comment]
and what can i do when i dont need middleware in some instance of player?

**Comment by gkatsev** [comment]
The `setSource` method gets called with a `next` method, you can pass in an Error (or I think any thing that isn't `null` as the first argument to not attach the middleware to the current player/source combination. You can decide whether you want it to be used either by checking the source or even by checking a property/option on the player. We have [documentation on middleware](https://docs.videojs.com/tutorial-middleware.html). Here's an example:

```js
videojs.use('*', function(player) {
  return {
    setSource(srcObj, next) {
      if (player.options()['use-middleware']) {
        next(null, srcObj);
      } else {
        next(new Error("don't use middleware"));
      }
  };
});
```

Also, can I inquire into what you're using middleware? Depending on your usecase, we may want to modify middleware to make what you're doing easier, especially if we see more people doing what you're doing.

**Comment by iseekyouu** [comment]
I use middleware to limit the allowed time to watch the video, in the video preview, my code: 
 ```
this.player = videojs(this.videoNode, videoOptions, () => {
  this.onPlayerReady(this.player);
});

onPlayerReady() {
  ....
  this.initMiddlewares();
}

initMiddlewares(){
  ....
  const previewMaxPlayTime = () => ({
    setCurrentTime: (time) => {
      if (time > this.props.duration) {
        return this.props.duration - 1;
      }

      return time;
    },
  });

  videojs.use('video/mp4', previewMaxPlayTime);
}
```
The page with the video file looks like this - i have a react component in which the video player is rendered. 
In this component, the maximum allowed time for playing video is transmitted through the props, each video has its own maximum allowed playing time. 
When an onplayerready player event occurs, I initialize the middleware with the desired maximum duration
The problem occurs when the user does not reload the page and uses the navigation buttons in the browser. 
Middlewar is registered every time you open the player with a video preview. Because of this, already on the second opened video, there may be a problem that the preview stops at the wrong time, since the last triggered middleware is the stop time not from the current video.

why do I use middleware ? I need to limit the length of the video preview. 
When I tried to limit some other way, any related ProgressBar drag and drop and other errors.
Middleware works correctly, but there is a problem described above, that they accumulate on the global object and there is no way to clear them.

**Comment by gkatsev** [comment]
Instead of initializing the middleware on player ready, you should add the middleware to Video.js and then depending on the player, make setCurrentTime be a no-op or not. Either by disabling the middleware in the setSource method based on a player check or by doing a check inside setCurrentTime.
The method that you pass into `videojs.use` gets a reference to the player and you can use [`setSource`](https://docs.videojs.com/tutorial-middleware.html#setsource) to have the middleware not run for a particular player/source combination.
I would probably add `this.props.duration` as a player option and then read that value, something like:

```js
// in the main file
videojs.use('video/mp4', function(player) {
  return {
    setCurrentTime((time) => {
      if (player.options().propDuration && time > player.options().propDuration) {
        return player.options().propDuration - 1;
      }
      return time;
    }
  };
});
```
```js
// inside the react component
videoOptions.propDuration = this.prop.duration;
this.player = videojs(this.videoNode, videoOptions, onPlayerReady);
```
Then, you can update `this.player.options().propDuration`.

Hope this helps.
