### ISSUE TITLE
HLS audio streaming pauses on Android in google chrome when I lock the phone or screen turned off (videojs 7.5)

### ISSUE THREAD

**Issue by NikodimYuryev** [videojs/video.js#5904]
## Description
HLS audio only streaming pauses on Android in Google chrome browser when I lock the phone, screen turned off or turn browser to background (videojs 7.5)

Now I use videojs 5.19.2 with viblast 6.53.3 plugin to play HLS audio only streams. It function normally, but the size of this plugin is great and it is not updated (I don't know reason). So, I plan to switch to videojs 7 with built-in HLS support instead of using viblast plugin. I test videojs 7.5 and all are well except one thing - playing of audio stream pauses when I turn browser to background or screen turned off on Android phone. In my old scheme with viblast plugin - no such effect, all audio streams play without pause in any browser in background and with screen off. This problem is observed only in chrome browser (or chromium browsers). When I use Firefox - no problem. But Google chrome is the main browser in Android and it is really great problem - all users are listening online audio with screen turned off. 
Are there any solutions to this problem?

If Viblast player solved this problem - may be there is some way to solve it in videojs by modifying code?
I try to listen "paused" event and start player immediately after the event fired - it work, but the sound is interrupted for 3-4 seconds after I press lock button on the phone. If I can programmatically start player after pause - may be there is some way not to pause it?

#### videojs
7.5.0
#### browsers
Google chrome (73.0.3683.90) and Firefox (68.0a1)
#### OSes
Android 8.0.0
### plugins
viblast.com (6.53.3) for videojs 5.19.2

**Comment by gkatsev** [comment]
I am not sure there's a better way. It's possible that setting up a mediasession would make it better (https://wicg.github.io/mediasession/, https://github.com/videojs/videojs-media-session) but I am not sure. Likely that listening to pause and calling play is the only way, though, I would urge you not to do so and let the users decide. I've looked at some of the demos on viblast's website and cannot get it to continue playing in the background either.
