### ISSUE TITLE
[Question] how much behind stream from live

### ISSUE THREAD

**Issue by vksbansal** [videojs/video.js#5907]
Hi Video js team,

Scenario
If a user pauses a live stream, how to find how much behind the user is from a live stream.

Please help, many thanks,

yours thanks full,
vikas bansal

**Comment by gkatsev** [comment]
You probably want to check the different from currentTime and seekable end.
Something like:
```js
var behind = player.seekable().end(0) - player.currentTime();
console.log('we are ', behind, ' seconds behind live');
```
