### ISSUE TITLE
Video.js creates HTML control elements when 'controls' attribute is not set.

### ISSUE THREAD

**Issue by tundratier** [videojs/video.js#5913]
## Description
I want to use video.js only via JavaScript. I don't want it to create any HTML elements or require a CSS file. Not setting the "controls" attribute does not suffice. The HTML elements are still created.

## Steps to reproduce
1. Open: https://jsbin.com/wehesaviro/edit?html,js,output
2. Check the output frame with the inspector: The control HTML elements are created.

### Expected
There are no control elements created.

### Actual
Video.js creates a lot of HTML elements.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.4.1
#### browsers
all latest browsers (FF, Chrome, Safari, Edge)
#### OSes
MacOS, Ubuntu, Windows 10
### plugins
no plugins used

**Comment by gkatsev** [comment]
You can set `controlBar: false` as an option to disable it.

**Comment by tundratier** [comment]
That only disables the control bar, not the other UI elements like the play button or progress track. I would like a clean video player with video.js only working in the background.

**Comment by tundratier** [comment]
I have managed to disable all custom UI elements using:
```
{
		controlBar: false,
		loadingSpinner: false,
		bigPlayButton: false,
		textTrackDisplay: false,
		errorDisplay: false,
		textTrackSettings: false,
		posterImage: false
}
```
It works without adding the CSS file.
https://jsbin.com/gadopuzuru/edit?html,js,output

However it would be good, if there was a "headless" variant of video.js that without the sources for the UI components. Is such a thing planned?

**Comment by gkatsev** [comment]
Having a custom/modular build of Video.js is planned, though, there aren't any updates on it currently.
