### ISSUE TITLE
uncaught error on fullsreen (in iframe)

### ISSUE THREAD

**Issue by Kogoruhn** [videojs/video.js#5918]
## Steps to reproduce

1. request url with player as iframe 
2. double click on player

### Expected
No errors

### Actual
on first double-click:
```
Uncaught (in promise) TypeError: fullscreen error
    at Player.requestFullscreen
    at Player.handleTechDoubleClick_
    at Html5.bound
    at HTMLVideoElement.bound
    at HTMLVideoElement.data.dispatcher
```

on second double-click:
```
 Uncaught (in promise) TypeError: Document not active
    at Player.exitFullscreen
    at Player.handleTechDoubleClick_
    at Html5.bound 
    at HTMLVideoElement.bound 
    at HTMLVideoElement.data.dispatcher
```

### versions
videojs 7.4.1
#### browsers
Last Google Chrome
#### OSes
Win 7

**Comment by gkatsev** [comment]
Ah, this is because those methods now return a promise and the iframe disallows going fullscreen. We probably want to wrap it in our `silencePromise` wrapper (until fs support is refactored).

**Comment by Kogoruhn** [comment]
@gkatsev Yup, it will be quite enough :) Thanks!

**Comment by gkatsev** [comment]
@Kogoruhn hey, would you be interested in making a PR for this?

**Comment by Kogoruhn** [comment]
@gkatsev Hi! not enough exp for this, sorry :(

**Comment by gkatsev** [comment]
I made a PR for this: #5970.

**Comment by ufologist** [comment]
When iframe's `document.fullscreenEnabled` is `true`, than `<video>` element could fullscreen.

You should set `allowfullscreen` attribute when create `<iframe>` element,
**dynamic set iframe's `allowFullscreen` attribute is NOT take effect, `document.fullscreenEnabled` is still `false`**.

I suggest test `document.fullscreenEnabled` before call the `requestFullscreen()` method.
