### ISSUE TITLE
Using SRT Captions/Subtitles in Videojs

### ISSUE THREAD

**Issue by Anan5a** [videojs/video.js#5923]
## Description
I want to use SRT subtitles in my videos alongside WebVTT because SRT has a huge selection of subs in sites like subscene.com But it seems support for it was dropped since v4.12+ Additionally suggested BubblesJS library /repository seems dead. the provided link no longer work.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
Add a ``` <track> ``` element with srt source file inside ``` <video> ```

### Expected
Have option for displaying captions
### Actual
Nothing there
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.3.0
#### browsers
All? 
#### OSes
Android,  Windows, Linux
### plugins
NO PLUGIN

**Comment by mister-ben** [comment]
The easiest option is probably just to convert srt to webvtt in advance.

You _could_ convert to webvtt on the fly and load as a remote text track, along these lines.

```js
var srtText = `1
00:00:00,500 --> 00:00:02,000
One caption

2
00:00:03,000 --> 00:00:05,000
Another caption`;
var srtRegex = /(.*\n)?(\d\d:\d\d:\d\d),(\d\d\d --> \d\d:\d\d:\d\d),(\d\d\d)/g;
var vttText = 'WEBVTT\n\n' + srtText.replace(srtRegex, '$1$2.$3.$4');
var vttBlob = new Blob([vttText], {type : 'text/vtt'});
var blobURL = URL.createObjectURL(vttBlob);
player.on('loadedmetadata', function() {
  this.addRemoteTextTrack({
    src: blobURL,
    srclang: 'en',
    label: 'english',
    kind: 'subtitles'
  }, true);
});
```

The regex is a bit simplistic and there will be edge cases it doesn't work with, there's more robust code to do the conversion part at https://github.com/silviapfeiffer/silviapfeiffer.github.io/blob/master/index.html

**Comment by Anan5a** [comment]
@mister-ben thanks. But is there any way to convert them on the fly when the video is playing?

**Comment by mister-ben** [comment]
That's the idea of the js code there. Fetch the captions, convert to vtt and add to the player as a text track with the `addRemoteTextTrack` API.

**Comment by Anan5a** [comment]
@mister-ben  very very thanks!
I'm now trying to write a function to do the job

**Comment by Anan5a** [comment]
@mister-ben Thank you for the RegEx. Successfully implemented on the fly conversion 
![Screenshot_2019-04-12-15-25-51](https://user-images.githubusercontent.com/16373480/56027394-cc14a400-5d37-11e9-801c-872879d9f046.png)
