### ISSUE TITLE
TypeError: cannot read property 'touchmove' of undefined at video.js 1806

### ISSUE THREAD

**Issue by 122177638** [videojs/video.js#5924]
## Description
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
There will be no problem with the first broadcast. This problem occurs if you switch the volume key several times or press the volume key for a long time to drag the volume and increase the volume value. If you pop up the video custom mask after playback and add a share button to the mask, this problem will also occur when you click on replay, which happens on Android 6.0, vivoX9L, AppLoader. Causes a global touchmove event error.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
TypeError: cannot read property 'touchmove' of undefined at video.js 1806

## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
AppLoader(apicloud)
#### OSes
Use environment:  AppLoader(apicloud)
Use system: Android6.0
Use type：vivo X9L

### plugins
nothing

**Comment by gkatsev** [comment]
Is this happening with a live device or just in apploader?
