### ISSUE TITLE
Source supplied as a blob:// URL string won't play

### ISSUE THREAD

**Issue by maxpaj** [videojs/video.js#5926]
## Description
Using a blob:// source URL, like this:
```
player.src("blob://...");
```

Video.js won't play the video even though it's a valid source. HTML5 tech says it can't play it (MEDIA_ERR_SRC_NOT_SUPPORTED). 

However, if you specify a source object like this, with a `type`, it works:
```
player.src({ src: "blob://...", type: "video/webm" });
```

I suspect it's due to:

1. Sources supplied as strings are reconstructed as a source object with [Util.filterSource](https://github.com/videojs/video.js/blob/master/src/js/utils/filter-source.js#L38) and tries to find the mime type using [Util.getMimeType](https://github.com/videojs/video.js/blob/master/src/js/utils/mimetypes.js#L38)
2. [Url.getFileExtension](https://github.com/videojs/video.js/blob/master/src/js/utils/url.js#L133) won't return anything since the blob URL ends with no file extension
3. [Html5.nativeSourceHandler.canHandleSource](https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L1913) determines whether it can play the source from the mime type 

It's totally fine to supply the `type` for the source object, but with no good error being produced when you don't provide it, it can be quite confusing.

https://github.com/videojs/video.js/issues/5504#issuecomment-481143136

## Codepen
https://codepen.io/anon/pen/MRpwNL?editors=1010

## Steps to reproduce
1. Create a blob URL from a video source
2. Supply the blob URL as a string into player.src(...)

### Expected
Video should play

OR

Video doesn't play, but the error shows that it can't be played because of missing mime type

### Actual
Video doesn't play (MEDIA_ERR_SRC_NOT_SUPPORTED)

### Error output
MEDIA_ERR_SRC_NOT_SUPPORTED

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.4.1
#### browsers
Google Chrome + potentially more
#### OSes
Windows 10 Pro + potentially more
### plugins
No

**Comment by mister-ben** [comment]
It's not really a valid source if the type is not given and it cannot be inferred, but logging a warning in `fixSource` makes sense.

For your code pen example you could get the type from the blob:

    player.src({src: blobURL, type: blob.type});
