### ISSUE TITLE
H.265 video playing support.

### ISSUE THREAD

**Issue by sparkmorry** [videojs/video.js#5927]
Hi there, I am working on a live streaming web application, and there is a case where **HEVC** video need to be supported to be played on modern browsers. As w3c is not planning to put HEVC codec in the standards currently, I am managing to implement a HEVC video player through canvas and web audio API. It works quite well via WebAssembly. Thus, I am thinking about making it a plugin to extend web video playing ability, can also be AV1 video player or some thing else in the future. 

However, videojs project is mainly working with a video DOM tag, right? If I want to play the video through a canvas tag as a plugin, does that make sense?

**Comment by gkatsev** [comment]
Video.js has a concept of Techs that can be used to swap out how the video is actually rendered. Initially, we just had HTML5 and Flash techs but there are a few other techs at this point.
Here's an example tech that allows playing back ogv video via ogvjs in Videojs: https://github.com/hartman/videojs-ogvjs

Let us know if you have questions implementing that. Feel free to drop by our [slack](http://slack.videojs.com) for more real-time help.

**Comment by sparkmorry** [comment]
> Video.js has a concept of Techs that can be used to swap out how the video is actually rendered. Initially, we just had HTML5 and Flash techs but there are a few other techs at this point.
> Here's an example tech that allows playing back ogv video via ogvjs in Videojs: https://github.com/hartman/videojs-ogvjs
> 
> Let us know if you have questions implementing that. Feel free to drop by our [slack](http://slack.videojs.com) for more real-time help.

Thank a lot for the information. I'll dive into the videojs-ogvjs project and find out a way to plugin. Have joined the slack group, also, wondering if anyone have the similar situation here. 😊

**Comment by gkatsev** [comment]
Here are a few more examples of techs: https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js, https://github.com/videojs/videojs-flash

**Comment by hold-baby** [comment]
请问找到相关解决办法了吗？

**Comment by gkatsev** [comment]
@hold-baby unfortunately, until @sparkmorry or someone writes an hevc tech, your best bet is still to convert to h264 or other widely supported format.

**Comment by gkatsev** [comment]
Going to close this as the original question has been answered. If you have any more questions @sparkmorry, please reach out on slack.

**Comment by sparkmorry** [comment]
> Going to close this as the original question has been answered. If you have any more questions @sparkmorry, please reach out on slack.

ok, thank you @gkatsev. I'm managing the project, I've join the slack team, and will reach you out if necessary.

**Comment by coffe1891** [comment]
I am working on this now .

**Comment by maxpaynebupt** [comment]
> I am working on this now .

How is it now? We are trying to find a solution to handle this, as converting every h265 stream to h264 would cost huge resource, playing 265 on end device would be the perfect solution.

**Comment by coffe1891** [comment]
> > I am working on this now .
> 
> How is it now? We are trying to find a solution to handle this, as converting every h265 stream to h264 would cost huge resource, playing 265 on end device would be the perfect solution.

this progress is 75%

**Comment by coffe1891** [comment]
https://www.npmjs.com/package/videojs-flvh265

I have finished this work.

**Comment by crazywin3** [comment]
> https://www.npmjs.com/package/videojs-flvh265
> 
> I have finished this work.

Thank you so much for this implementation.
Does this only support FLV, how 'bout MP4?
Can I control it through functions like onSeeking()?

**Comment by hold-baby** [comment]
> https://www.npmjs.com/package/videojs-flvh265
> 
> I have finished this work.

额 老铁 你这不支持hls啊

**Comment by coffe1891** [comment]
> > https://www.npmjs.com/package/videojs-flvh265
> > I have finished this work.
> 
> 额 老铁 你这不支持hls啊

so it is called "flvh265" :P
