### ISSUE TITLE
can't play video in ios 12.2.

### ISSUE THREAD

**Issue by dengweijing** [videojs/video.js#5928]
I think I meet something trouble in IOS 12.2 ，and I can't play video by invoke video.play() method.

**Comment by mister-ben** [comment]
Try muting the video first. Safari (and increasingly other browsers) does not allow programmatic play without user interaction unless muted.

**Comment by gkatsev** [comment]
Mobile devices in generally don't allow unmuted autoplay. See our [autoplay best-practices blogpost](https://blog.videojs.com/autoplay-best-practices-with-video-js/) for more info.
