### ISSUE TITLE
video.min.js:12 VIDEOJS: ERROR: DOMException

### ISSUE THREAD

**Issue by coolicer** [videojs/video.js#5936]
## Description
Got error when network is bad. 
Use videojs7

## Steps to reproduce
I guess when the network is not good, it causes this problem.

### Expected
When this happens, you can stop and load, then play again.

### Actual
It can't load and play any more.

### Error output
```
video.min.js:12 VIDEOJS: ERROR: DOMException: 
Failed to set the 'duration' property on 'MediaSource': 
The 'updating' attribute is true on one or more of this MediaSource's SourceBuffers.
```

**Comment by coolicer** [comment]
https://github.com/videojs/http-streaming/issues/378

**Comment by Simon-Bin** [comment]
@coolicer  How to solve
