### ISSUE TITLE
Can't play a .MOV file

### ISSUE THREAD

**Issue by gpalomar** [videojs/video.js#5938]
## Description
I'm working on a project where users can upload content and preview them after upload completes. When the uploaded file has .MOV format (a video from an iPhone), video does not play correctly. Only audio is played, but not video image.

I've downloaded a video from [this](http://file-examples.com/index.php/sample-video-files/sample-mov-files-download/) website and all works as expected. So there is a difference between my uploaded iPhone movie and this sample.

The non working video --> [KO_1.MOV.zip](https://github.com/videojs/video.js/files/3083562/KO_1.MOV.zip)

What should I do?

Thanks!

## Steps to reproduce
(Explained above)

### Expected
MOV files should work.

### Actual
...

### Error output
No errors displayed.

#### videojs
7.4.1
#### browsers
Chrome
#### OSes
MacOS
### plugins
No plugins

**Comment by gkatsev** [comment]
Unfortunately, I don't think there's anything you can do aside from re-encoding the video. Chrome doesn't officially support the .mov container type (though, it may read it if you set the type to be `video/mp4` when you pass it into video.js). Using ffprobe on the .mov file, I see that it uses HEVC. Chrome doesn't support HEVC, so, the video won't play. See https://caniuse.com/#feat=hevc for browser support of HEVC.

**Comment by gpalomar** [comment]
I suposed that this may work with this library because I've uploaded this video to Dropbox (they use video.js as far as I could see in this library's website and inspecting their one) and preview is working fine. Or there is another way to make it work, or Dropbox re-encodes the video in their servers. But if I download the video again from Dropbox, [exifinfo](https://exifinfo.org) shows me the exactly same data. So, there's any other possible answer? Thanks!

**Comment by gkatsev** [comment]
I believe that dropbox re-encodes the preview video.

**Comment by mister-ben** [comment]
They do; they use HLS in their preview.

**Comment by gpalomar** [comment]
Thanks @mister-ben and @gkatsev for your information.
