### ISSUE TITLE
[Query] How to pass query params in chunk calls (safari fariplay)

### ISSUE THREAD

**Issue by bansalvks** [videojs/video.js#5939]
Hi Video Js team,

I am struggling to find a way to pass query params in the segment calls in safari fairplay

it does not provide a way to access before request method as you cannot override HLS to true in case of fariplay.

Please help

Many thanks,
Vikas Bansal

**Comment by gkatsev** [comment]
By default, we use native playback on Safari which doesn't let you override how segments are requested.
For Safari on desktop _only_, you can use [overrideNative](https://github.com/videojs/http-streaming#overridenative) and then use VHS's [beforeRequest](https://github.com/videojs/http-streaming#hlsxhr) to add in extra things but it won't work for mobile safari as it doesn't support MSE.
