### ISSUE TITLE
How to customize the video type

### ISSUE THREAD

**Issue by kslr** [videojs/video.js#5942]
Hi

I found that Chrome can play MKV, So I made a UserAgent judgment.
But if you simply pass it will get "notSupportedMessage"

```javascript
const player = videoJs();
player.src(data.url);
player.play();
```

Do I have a way to bypass the judgment and give it to the browser to play?

Thanks

**Comment by mister-ben** [comment]
You can, and generally should, include a type by passing an object to `src`

    player.src({type: 'video/mp4', src: 'https://example.com/file.mp4'});

Including the source allows Video.js to figure which tech or source handler can play it. If the type is not given then we try to infer it if it has one of a few known file extensions commonly supported, but it's always best to give the type.

Now you _could_ say your mkv is a different type and see if the browser's video element can deal with it, but on the whole it would be better to convert the file to something more widely supported in HTML5 video, i.e. MP4/h264/aac.

**Comment by kslr** [comment]
@mister-ben Yes, Just now, setting it to video/webm solves this problem. although this is a hack.
