### ISSUE TITLE
Live Streaming with HLS on Mobile not working

### ISSUE THREAD

**Issue by AyoubBani** [videojs/video.js#5944]
I tested the player on android device with chrome browser while streaming videojs is playing the video (Video on demand ) not live. for example if the playlist contains 35 segments and we are live streaming the player on android device loads the first segment and plays the video instead of playing the last segment and refreshing the playlist.

**Comment by mister-ben** [comment]
When the browser has native support for HLS we default to letting the browser handle the playback. Sometimes the native HLS support isn't very good though, even on Chrome. You can try the `overridenative` option, since Chrome supports Media Source Extensions (MSE).

https://github.com/videojs/http-streaming/blob/master/README.md#overridenative

**Comment by AyoubBani** [comment]
even setting the overrideNative option the player still playing the video from the beginning instead of live streaming. The player works fine on the web but I'm having this problem on the android chrome browser.

**Comment by gkatsev** [comment]
Would you be able to provide a reduced test case? We've not seen such behavior before.

**Comment by gkatsev** [comment]
Would you be able to provide a reduced test case? We've not seen such behavior before.

**Comment by AyoubBani** [comment]
I'm using ffmpeg to stream from camera : 
sudo ffmpeg -y -threads 4 -i '/dev/video0' -f hls -map 0:v -c:v libx264 -vf scale=w=1280:h=720:force_original_aspect_ratio=decrease -preset ultrafast -x264opts keyint=25:min-keyint=25:no-scenecut -sc_threshold 0 -r 25 -hls_time 1 -hls_playlist_type event -b:v 2800k -maxrate:v 2996k -bufsize:v 4200k -c:a aac -b:a 128k -ac 2 -ar 48000 -pix_fmt yuv420p -segment_list_flags +live -hls_flags independent_segments+program_date_time+second_level_segment_index -strftime 1 -hls_segment_filename 'segment_%%06d_%Y%m%d%H%M%S.ts' 'playlist.m3u8'
this generates 1 second segments. With just setting the source of the video the player works fine on the web it displays the live streaming from camera without a problem. But testing the player on the android chrome it reads from the first segment and plays the video (on Demand profile) instead of playing the last segment and refreshing the playlist.
