### ISSUE TITLE
I can't send cookie with Headers when the withCredentials property is true

### ISSUE THREAD

**Issue by pocketChao** [videojs/video.js#5945]
I set the withCredentials property of video-js to true, and then the server configured withCredentials to true, access-control-allow-headers: Requested (Origin, x-requested With, content-type, Accept), access-control-allow-origin :'.$_SERVER['HTTP_ORIGIN '], but I found no cookie in the HTTP request by grabbing the package, I hope to be able to get help, I will be very grateful 
![AA1EE92D-9F3C-455E-8EC7-FB10EB622514](https://user-images.githubusercontent.com/21028807/56401745-05e03000-628d-11e9-8470-caa5b9c0912d.png)
![9E35EAF8-5D84-4752-A898-FB7D4DA31621](https://user-images.githubusercontent.com/21028807/56401781-1c868700-628d-11e9-8a52-f509b16d8f9c.png)
![67B00C85-8534-45C1-B06B-597EBFCDC3D8](https://user-images.githubusercontent.com/21028807/56401847-79823d00-628d-11e9-8076-2cef2ebb9208.png)

**Comment by gkatsev** [comment]
What browser are you running this on? MS Edge? I believe we play HLS natively on Edge by default. I know that we play natively by default on Safari (and we can't handle it on iOS at all since MSE doesn't exist). When native playback is done then the withCredentials option isn't being set. You'll need to [overrideNative](https://github.com/videojs/http-streaming#overridenative) to use our playback engine. For truly native playback, you should set the [`crossorigin` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) on the video element

**Comment by bayko** [comment]
late to the party here but just wanted to add we were able to get this working properly using

      player.ready(function() {
        player.src({
          src: 'https://videos.example.com/#{@model.video_source_url}',
          type: 'application/dash+xml',
          withCredentials: true
        });

this is forcing cookies now to be sent on every request

**Comment by pocketChao** [comment]
> 来到这里的派对很晚但只想添加我们能够正常使用
> 
> ```
>   player.ready(function() {
>     player.src({
>       src: 'https://videos.example.com/#{@model.video_source_url}',
>       type: 'application/dash+xml',
>       withCredentials: true
>     });
> ```
> 
> 这是强制cookie现在每次请求发送

Ok, thank you very much. I will try. I rewrote the options of player before, but it did not work.

**Comment by pocketChao** [comment]
> 你在用什么浏览器运行它？MS Edge？我相信我们默认在Edge上本地播放HLS。我知道我们默认在Safari上播放本地（我们无法在iOS上处理它，因为MSE不存在）。完成本机播放后，未设置withCredentials选项。您需要使用[overrideNative](https://github.com/videojs/http-streaming#overridenative)来使用我们的播放引擎。对于真正的原生播放，您应该在视频元素上设置[`crossorigin`属性](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes)



> 你在用什么浏览器运行它？MS Edge？我相信我们默认在Edge上本地播放HLS。我知道我们默认在Safari上播放本地（我们无法在iOS上处理它，因为MSE不存在）。完成本机播放后，未设置withCredentials选项。您需要使用[overrideNative](https://github.com/videojs/http-streaming#overridenative)来使用我们的播放引擎。对于真正的原生播放，您应该在视频元素上设置[`crossorigin`属性](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes)

I am not playing video in native, now our video server has removed the check of cookie, thank you very much for your answer.
