### ISSUE TITLE
使用video.js在安卓上全屏时，不能横屏

### ISSUE THREAD

**Issue by huangyingyy** [videojs/video.js#5946]
## Description
在移动端使用video.js播放视频，全屏播放，在iOS能根据重力感应自动横屏竖屏，但是在安卓上无法根据重力感应横屏播放。是要设置什么吗？

**Comment by mister-ben** [comment]
Sorry, Google translate isn't very clear. I think you are saying that a video in full screen mode is not rotating when the phone orientation changes. This is handled by the browser, Video.js does not do anything special to make that work.

The question may be clearer with an example link, screenshots, and details of what browser you are using.

**Comment by tmj1220** [comment]
the same question

**Comment by gkatsev** [comment]
As @mister-ben said, if this is regarding auto-rotating when going fullscreen, that isn't something that we can (or should) handle as it's generally handled by the browser and if we tried to "fix" it, we'll just end up fighting the native orientation and cause more issues.
If you have a specific example that you think doesn't fall in the above category, can you please file a new detailed issue with a reduced test case? Thanks.
