### ISSUE TITLE
移动端iOS点击播放禁止自动全屏

### ISSUE THREAD

**Issue by huangyingyy** [videojs/video.js#5948]
## Description
在移动端使用video.js，在iOS点击播放会自动全屏播放，怎么样可以禁止自动全屏播放呢？

**Comment by mister-ben** [comment]
Add the `playsinline` attribute.

**Comment by huangyingyy** [comment]
> Add the `playsinline` attribute.

加了，没有用呢

**Comment by zhoujiuyi** [comment]
我也遇到这个问题,请问该怎么解决呢

**Comment by huangyingyy** [comment]
> 我也遇到这个问题,请问该怎么解决呢
让原生改配置： webview.allowsInlineMediaPlayback = YES

**Comment by mister-ben** [comment]
It sounds like you found a solution? If using a webview you do often have to make configuration changes to make it behave as Safari does.

**Comment by gkatsev** [comment]
If you're inside a webview, the webview needs to be configured to allow fullscreen or inline playback.
