### ISSUE TITLE
ios禁止自动全屏

### ISSUE THREAD

**Issue by huangyingyy** [videojs/video.js#5949]
## Description
在ios12中，使用了webkit-playsinline属性和playsinline都不能禁止自动全屏的情况。是还要加上什么属性属性吗？

**Comment by huangyingyy** [comment]
是移动端的

**Comment by mister-ben** [comment]
Duplicate of #5948?

**Comment by gkatsev** [comment]
If you're inside a webview, the webview needs to be configured to allow fullscreen or inline playback.
