### ISSUE TITLE
React video.js does not support RTMP

### ISSUE THREAD

**Issue by jamesofcn** [videojs/video.js#5961]
## Description
We follow the instruction of video.js in 
https://docs.videojs.com/tutorial-react.html
and adjust the source url to a RTMP url
however, it does not work in our React application.

## Steps to reproduce
The videoJsOptions are:
const videoJsOptions = {
  autoplay: true,
  controls: true,
  sources: [{
    src: 'rtmp://****/live/test',
    type: 'rtmp/flv'
  }]
}

When we switch src to a mp4 url, it is ok.
### Error output
 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."}

## Additional Information
IF we use video.js 5.18.4 like this
`<script src="http://vjs.zencdn.net/5.18.4/video.min.js"/>	`
` <video id="my-video" class="video-js" controls preload="auto"  width="640" height="264"
		  data-setup="{}">`
`<source src="rtmp://****/live/test" type="rtmp/flv"/>  `
`</video>`

This works.

### versions
Both lastest React Video.js v7.5.4 AND v5.18.4 do not work in React
A single html with v5.18.4 js works.

#### browsers
Firefox & Chrome

**Comment by mister-ben** [comment]
For Video.js 6+ you need add the Flash tech as it's not included by default. I'm not sure whether there are any special considerations to using that with React though.

https://github.com/videojs/videojs-flash

**Comment by jamesofcn** [comment]
Thanks Ben
We finally find a solution as following:
use `import videojs from "video.js/dist/video.js";`
instead of `import videojs from "video.js"`
in react componentDidMount add 
` this.player = videojs('myVideo', options);`
`        this.player.src({`
`            src: "rtmp://xxx/live/test",`
`            type:'rtmp/flv',`
        `});`
        `this.player.load();`
this works, cheers

**Comment by coder054** [comment]
@jamesofcn , Could you please give me the source code?
