### ISSUE TITLE
change videojs src with reloading the player

### ISSUE THREAD

**Issue by AyoubBani** [videojs/video.js#5971]
I'm trying to update the video src using video.src = '........./playlist.m3u8'. but the problem is that the player reloading. I would like to ask if there is a way to change the src of the player without reloading the video. The purpose is changing the src of the video to playing an ad. after the ad is played we want the player to get back and keeps playing the video where it's left.

**Comment by gkatsev** [comment]
You should use the player API to change the source. See https://docs.videojs.com/tutorial-player-workflows.html#dealing-with-the-source-or-the-poster-on-the-player for an example.

**Comment by klemensz** [comment]
Have you found a solution for this?
