### ISSUE TITLE
'headless' video.js?

### ISSUE THREAD

**Issue by tomByrer** [videojs/video.js#5974]
> [custom/modular builds are coming](https://github.com/videojs/video.js/issues/5812#issuecomment-487757789)

Hey that's great!
I thought it would be neat to separate out the UX from the logic/unified-API.  You've all have done great work, but wanted to try something different for the UX.  When I tried to separate out the HTML/(s)CSS from the rest of Video.js, I got lost in the maze.  ;)  Seems much of the logic is integrated with the UX, rather than simpler functions that the UX calls. (But maybe I misread the code?)
EG: `player.js` imports `modal-dialog` & `stylesheet`.

I think separating out the presentation code from the logic & API resurfacing glue    (tech) could be a good first step for your goal as well.  Then you can add the modular build system after easier.

**Comment by gkatsev** [comment]
There's definitely stuff we can do there. At the moment we're shying away from breaking changes and I have a feeling that to do something like this would really require a breaking change.
Depending on your needs, you could potentially just import/use a Tech directly and that's likely the direction we'll go for the "headless" mode.
