### ISSUE TITLE
default mute

### ISSUE THREAD

**Issue by JiangKunbo** [videojs/video.js#5976]
I set the default mute when the videojs is initialized. Although the video has been muted on the interface, the sound can still be transmitted from the microphone. But manually restore the sound, then click Mute but mute.

my html code
```
 <video id="my_video" class="video-js" data-setup='{"techOrder": ["flash"]'
           autoplay="autoplay"
           controls="controls"
           muted="muted"
           width="520"
           height="380">
      <source :src="url" type="rtmp/mp4">
    </video>
```
and my js code
```
      player = videojs('my_video', {
          sources: [{
            type: 'rtmp/mp4',
            src: this.url
          }],
          muted:true,
          autoplay:true,
          bigPlayButton: false,
          techOrder: ['flash']
        }, () => {
});
```

**Comment by NoXCZJ** [comment]
Me too, Have you solved it?

**Comment by NoXCZJ** [comment]
同时调用this.volume(0);this.muted(true);能暂时解决

**Comment by gkatsev** [comment]
This may be a bug with the swf where it doesn't respect the muted attribute.
You could try calling `player.muted(true)` on `player.ready`.
