### ISSUE TITLE
Subtitles/captions button is named incorrectly in the docs

### ISSUE THREAD

**Issue by dpipchenko** [videojs/video.js#5980]
Hello,

Please update the list of components here: https://docs.videojs.com/tutorial-components.html
...and here: https://docs.videojs.com/docs/guides/components.html
...to include the correct button name for subtitles/caption.

As I found at https://github.com/videojs/video.js/blob/master/src/js/control-bar/control-bar.js it should be 'subsCapsButton'

It took me a couple of hours to find that (specifically, to disable that button), so will definitely save someone's time in the future.

This is for the latest video.js version at least.

**Comment by gkatsev** [comment]
The docs in `docs.videojs.com/docs` is the v5 docs. We probably want to add a header there that says so.
There info in on the current page isn't incorrect, just a bit out of date, apparently.

**Comment by dpipchenko** [comment]
Ok, makes sense for that specific link. What about the first link I mentioned? It is for v7 as it says - so should the list be updated there?
![Снимок экрана 2019-06-04 в 21 15 00](https://user-images.githubusercontent.com/50346584/58903616-84deda00-870e-11e9-9185-6e268e5ae17d.png)

**Comment by gkatsev** [comment]
That isn't incorrect. We do have a SubtitlesButton and a CaptionsButton. We default to a SubsCapsButton now (which should be on there but isn't).
