### ISSUE TITLE
Retrieving lost connection in Safari

### ISSUE THREAD

**Issue by mparfeniuk** [videojs/video.js#5981]
## Description
We are using vjs in our livestream solutions. We faced an issue in Safari with retrieving lost connection.

## Steps to reproduce
1. Switch on the stream and start playing it on the player
2. Stop the stream 
3. Reactivate it again

## Results
Player keep processing waiting mode in Safari and not retrieve livestream connection as it is in Chrome, FF

### Expected
We expect VJS to handle this case in the same way as in other browsers

#### videojs
tested in VJS 6.10.1 and VJS 7.4.1
#### browsers
Safari
### plugins
VJS 6.10.1 with videojs-contrib-hls 5.14.1

**Comment by gkatsev** [comment]
If you are on desktop safari, you can enable overrideNative to use our playback engine (caveat, we haven't done extensive testing with it). Unfortunately, there's not much you can do other than enabling a timer and trying to load the stream again, particularly if you're on iOS.
