### ISSUE TITLE
Ubuntu/Firefox (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) for HLS and MPEG-DASH sources

### ISSUE THREAD

**Issue by pjc89** [videojs/video.js#5983]
## Description
Videojs is not able to play HLS or MPEG-DASH streams on Firefox running on Ubuntu Linux. 
In the steps to reproduce I included only the HLS stream but i tried both (HLS and MPEG-DASH), both gave me `MEDIA_ERR_SRC_NOT_SUPPORTED`.

The same configuration works on other OS/Browser combinations. Had no problems with firefox on Windows and MacOS, I tried Chromium on Ubuntu and again no problems.  

## Steps to reproduce
Try to open an HLS or MPEG-DASH stream on Firefox/Ubuntu.  

This is the code of the page where i saw the error: 
```html
<!doctype html>
<html lang="it">
<head>
    <title>Test Videojs</title>
    <link href="https://vjs.zencdn.net/7.5.4/video-js.css" rel="stylesheet">
</head>
<body>
<video id=example-video width=960 height=540 class="video-js vjs-default-skin" controls>

</video>
<script src='https://vjs.zencdn.net/7.5.4/video.js'></script>
<script>
    const player = videojs('example-video', {});
    player.src({
        src: "https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8",
        type: "application/x-mpegURL"
    });
    player.play().catch(e => console.error);
</script>
</body>
</html> 
```

### Expected
Videojs plays the video 

### Actual
Videojs shows the error message: `No compatible source was found for this media.`

### Error output
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.`

#### videojs
- 7.5.4
#### browsers
- Firefox 66.0.3 (64-bit)
#### OSes
- Ubuntu 18.04.2 LTS (Bionic Beaver) - This is a VM running on Parallels Desktop
### plugins
*None*

**Comment by mister-ben** [comment]
Firefox doesn't include patented codecs such as h.264 and depends on the OS for support. Ubuntu also does not install these codecs by default, but you can add them with the [ubuntu-restricted-extras](https://en.wikipedia.org/wiki/Ubuntu-restricted-extras) package. Chromium its own separate package for such codecs.
