### ISSUE TITLE
No problem running locally, e is not defined on the server

### ISSUE THREAD

**Issue by virtueDe** [videojs/video.js#5985]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
**1.I wrote according to the official documentation, there is no problem running the project locally, but the project is deployed to the server, the console will report an error, and the video cannot be played.**
**2.Code in the face**
**3. The project is urgent, I hope to give a reply, thank you very much.**
@gkatsev

### Expected
Please describe what you expected to see.
**Running normally on the server**
### Actual
Please describe what actually happened.
**Component code**
`   <ayl-video :url="videoOptions.sources[0].src"></ayl-video>`
```
<template>
  <div>
    <video ref="videoPlayer" class="video-js"></video>
  </div>
</template>
<script>

import videojs from 'video.js';
export default {
  props: {
    url: {
      type: String,
      default: ''
    }
  },
  // props: {
  //   options: {
  //       type: Object,
  //       default() {
  //           return {};
  //       }
  //   }
  // },
  data() {
    return {
      player: null
    }
  },
  methods: {
    
  },
  mounted() {
    this.player = videojs(this.$refs.videoPlayer, {
          autoplay: true,
          controls: true,
          aspectRatio: '16:9',
          sources: [
              {
                src: this.url,
                type: "application/x-mpegURL"
              }
          ],
        poster: "https://gydev-1252687978.piccd.myqcloud.com/gy/pc-upload/20190506/768d8f3a-20cb-4e3f-bb8b-7b2ba459cc2c.png"
    }, function onPlayerReady() {
      console.log('onPlayerReady', this);
    })
  },
  beforeDestroy() {
    if (this.player) {
      this.player.dispose()
    }
  }
}
</script>
<style scoped lang="scss">
  
</style>
```

### Error output
If there are any errors at all, please include them here.
`ReferenceError: e is not defined`
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
`    "video.js": "^7.5.4",`
#### browsers
what browser are affected?
**Chrome  72.0.3626.119**
#### OSes
what platforms (operating systems and devices) are affected?

**windows、mac**

### plugins
are any videojs plugins being used on the page? If so, please list them below.
`    "vue-dplayer": "^0.0.10",`
`    "vue-video-player": "^5.0.2",`

**Comment by gkatsev** [comment]
Can you provide more of the error? Better yet, do you have a live reduced test case for us to see?
That error, unfortunately, is too generic to provide much feedback.

**Comment by virtueDe** [comment]
@gkatsev  
Thank you very much for your reply！！！ it was ok when I was running the project locally with video.js.
![image](https://user-images.githubusercontent.com/46802209/57349429-a63ebb80-718c-11e9-824d-ce443c467afa.png)

But when I deploy the project to the server test environment, the console displays:
![image](https://user-images.githubusercontent.com/46802209/57349495-e7cf6680-718c-11e9-969d-fae4414b41cf.png)

**Comment by virtueDe** [comment]
@gkatsev Has been resolved, thank you for your reply！！

**Comment by thienedits** [comment]
@virtueDe How did you fix this error. I am getting this error on server and not locally.
