### ISSUE TITLE
ie11 second play causes: object doesn't support property or method 'terminate'

### ISSUE THREAD

**Issue by KevinBrogan** [videojs/video.js#5988]
## Description
Using ie 11 on windows 10, when the videojs library is in a different window context then the player is, the player will crash the second time the source is set.

Object doesn't support property or method 'terminate'

https://playcode.io/310678?tabs=console&script.js&output

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use ie 11
2. load the videojs script inside of an iframe
3. call videojs(element) on an element that is outside of the iframe
4. load a video file and play it
5. when the video is ended, on the ended event, load another media file and try to play it
6. load fails, error outputted

### Expected
second video source loads

### Actual
crash

### Error output
Object doesn't support property or method 'terminate'

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.5.4
#### browsers
ie 11
#### OSes
windows 10
### plugins
no plugins

**Comment by gkatsev** [comment]
This is the cross realm issue right? Where Video.js is loaded in an iframe?

**Comment by KevinBrogan** [comment]
Where the videojs code and the video element it is controlling are in
different frames.

**Comment by KevinBrogan** [comment]
But the frames have the same origin

**Comment by gkatsev** [comment]
Yeah, just wanted to make sure we get this info here so we don't forget :)

It's unlikely something we'll be able to spend time addressing considering everything else in flight and on the queue, but we won't say no to a fix ;)
