### ISSUE TITLE
[Question] is there a way to monitor quality change?

### ISSUE THREAD

**Issue by vksbansal** [videojs/video.js#5989]
I there a way to monitor the quality/adaption/rendition/bitrate change?

**Comment by mister-ben** [comment]
See the segment metadata track: https://github.com/videojs/http-streaming#segment-metadata

This does not exist for native HLS playback e.g. on Safari, but you can listen for `resize` on the player to at least get resolution changes.

**Comment by vksbansal** [comment]
many thanks @mister-ben
