### ISSUE TITLE
Autoplay on iPad

### ISSUE THREAD

**Issue by gregfr** [videojs/video.js#5990]
(this is not a bug report)
Greetings Community
For years I've held for a certainty that Apple was definitive on "no autoplay on iPad". So I added a "click on the video" message for iPad users.
But now I see that Flowplayer have a functional autoplay on iPad.
How comes?
Regards

**Comment by mister-ben** [comment]
Safari allows autoplay if the player is muted.

**Comment by gregfr** [comment]
Thanks that's very interesting to know! do you have a link to some documentation on the subject?

**Comment by turshija** [comment]
You can read more about autoplay policy here - https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by gkatsev** [comment]
We also have an overview with links to browsers (firefox is currently out of date as they no longer allowing unmuted autoplay) here: https://blog.videojs.com/autoplay-best-practices-with-video-js/

**Comment by gregfr** [comment]
Thanks for all the tips! :+1:
