### ISSUE TITLE
VJS selects source with lowest bandwidth after retrieving connection

### ISSUE THREAD

**Issue by mparfeniuk** [videojs/video.js#5993]
## Description
VJS selects source with lowest bandwidth after retrieving connection. It takes about 3 - 5 min. then it back to normal

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Start play livestream video
2. Check current stream
3. Switch off livestream and then switch it on after a while
4. Check active stream
5. After retrieving connection source with lowest bandwidth is activating

### Expected
Is it it programmed behavior for such case?
I expect to see source with proper bandwidth which player.hls.selectPlaylist returns

### Actual
**From the start it activates**
#EXT-X-STREAM-INF:BANDWIDTH=5311568,RESOLUTION=1280x720,CODECS="avc1.640029,mp4a.40.2",SUBTITLES="subs"
738_2.m3u8?m=1557500218

**After retrieving connection during 3 - 5 min I have this stream**
738_2.m3u8?m=1557500218
#EXT-X-STREAM-INF:BANDWIDTH=291715,RESOLUTION=416x234,CODECS="avc1.4D401E,mp4a.40.2",SUBTITLES="subs"
738_3.m3u8?m=1557500218

#### videojs
I replicated this on vjs 6.10.1 and last vjs 7.5.4 version. I suppose it happens across all versions.

**Comment by mattfrankly** [comment]
bump
