### ISSUE TITLE
HELP！video run time exceed from actual run time in IE 11

### ISSUE THREAD

**Issue by iveydady** [videojs/video.js#5994]
https://github.com/videojs/video.js/issues/1260
https://github.com/videojs/video.js/issues/1136

IE11  vjs7.5.4

when Network speed is slow  and  it happens only the first time.
player.buffered().end(0) === player.currentTime()  >> player.duration()

**Comment by gkatsev** [comment]
Have a reduced example we can try out?

**Comment by iveydady** [comment]
sorry，I can't provide examples, but I'm sure this problem exists.
Just as  mentioned above 

when Network speed is slow  I paly my  video  the  first  time  

console log  player.buffered().end(0) === player.currentTime() >> player.duration()  

currentTime  beyond  duration
