### ISSUE TITLE
Console.log AFTER seeked fires when using tech integrations 

### ISSUE THREAD

**Issue by masudhossain** [videojs/video.js#5995]
Doing this block of code 

```
var vid = document.querySelector('#vid');
vid.addEventListener('timeupdate', function() {
  console.log('timeupdate', vid.currentTime);
});
vid.addEventListener('seeking', function() {
  console.log('seeking', vid.currentTime);
});
vid.addEventListener('seeked', function() {
  console.log('seeked', vid.currentTime);
});
```

Works fine when you have traditional `<video src="example.mp4"></video>,` but fails when you're integrating other videos like YouTube or twitch.tv to use with VideoJS + techOrder API.

**Comment by gkatsev** [comment]
What is `#vid`? Is it the video element that you initialize video.js with? If so, when Video.js plays the youtube video, that element is removed. You should use the player api to listen to the events instead.

**Comment by masudhossain** [comment]
@gkatsev when you say player api, are you referring to videojs api (if so, I didn't see any `seeked` function in the docs) or the youtube api?

**Comment by gkatsev** [comment]
Video.js builds on top of the standard video API, so, seeked should be available. Looking at the videojs-youtube tech, I can confirm that we make sure that seeked events are available (it's possible seeking events won't be available in videojs-youtube currently).
