### ISSUE TITLE
Can't adjust volume and control bar when use videojs combine jquery.swiper.js

### ISSUE THREAD

**Issue by sang-dang** [videojs/video.js#5999]
I'm trying handle swipe action in my video. I find the library: jquery.swiper.js to implement. But when I integrate it with videojs, i can't  drag volumn or progress bar.

**Comment by xuwankang** [comment]
.video-js .vjs-big-play-button .vjs-icon-placeholder:before, .vjs-button > .vjs-icon-placeholder:before, .video-js .vjs-modal-dialog, .vjs-modal-dialog .vjs-modal-dialog-content {
  /*position: absolute;*/
  top: 0;
  left: 0;
  width: 100%;
  height: 100%; 
}
去掉 absolute，我是这么解决的

**Comment by mister-ben** [comment]
I'm not familiar with that library, but note that you can configure it to ignore elements with a particular class: https://idangero.us/swiper/api/#parameters

**Comment by gkatsev** [comment]
Looks like adding `swiper-no-swiping` class to the player is the best solution.
