### ISSUE TITLE
I can't play my rtmp stream, the stream is ok, and I can use the code play another rtmp stream.

### ISSUE THREAD

**Issue by wenjijie** [videojs/video.js#6006]
# I can't play my rtmp stream, the stream is ok, and I can use the code play another rtmp stream.

## Description

this is the code to test.

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>video.js</title>
    <!-- <link href="https://unpkg.com/video.js@6.11.0/dist/video-js.min.css" rel="stylesheet">
    <script src="https://unpkg.com/video.js@6.11.0/dist/video.min.js"></script> -->
    <link href="https://vjs.zencdn.net/7.5.4/video-js.css" rel="stylesheet">
    <script src="https://vjs.zencdn.net/7.5.4/video.js"></script>
    <script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script>
  </head>
  <body>
    <video id="my-player" class="video-js" controls>
        <!-- <source src="rtmp://live.hkstv.hk.lxdns.com/live/hks2" type="rtmp/flv"> -->
        <source src="rtmp://192.168.1.33/videotest" type="rtmp/flv">
        <p class="vjs-no-js">
          not support
        </p>
    </video>
    <script type="text/javascript">
      var player = videojs('my-player',{
        width:300,
        heigh:200
      });
    </script>
  </body>
</html>
```

when I use "rtmp://live.hkstv.hk.lxdns.com/live/hks2" test the code.It's successful.

![the code is ok](https://blog.qiuluo.xin/wp-content/uploads/2019/05/hks-web.png)

but if I use "rtmp://192.168.1.33/videotest", I get the Error:

```
VIDEOJS: ERROR: (CODE:0 MEDIA_ERR_CUSTOM) FLASH: rtmpconnectfailure MediaError {message: "FLASH: rtmpconnectfailure"}
```

![my stream fail](https://blog.qiuluo.xin/wp-content/uploads/2019/05/cam-web.png)

I have tested the stream with potPlayer, it works fine.

I use ffmpeg push the stream.

![potplayer success](https://blog.qiuluo.xin/wp-content/uploads/2019/05/cam-pot.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
6.11.0

7.5.4

#### browsers
chrom 74.0.3729.169

#### OSes
windows 10
### plugins
videojs-flash.js

**Comment by gkatsev** [comment]
You need to make sure that the connection url and stream name pieces are split with an & for videojs-flash to properly be able to initialize the RTMP connection. See our FAQ: https://docs.videojs.com/tutorial-faq.html#q-how-can-i-play-rtmp-video-in-videojs.

**Comment by ccamero8** [comment]
Copying/pasting the example code above gives me the error "videojs is not defined"
