### ISSUE TITLE
Video is not ready. (Video.js) Exeception thrown inside ready handler in iOS Safari

### ISSUE THREAD

**Issue by m90** [videojs/video.js#601]
I cannot play video using videojs on iOS Safari (iPad running iOS 6).

I use the following markup:

```
<video id="vid" class="video-js vjs-default-skin" data-setup='{ "controls": false, "autoplay": false, "preload": "auto" }'>
   <source src="movies/vid.mp4" type="video/mp4">
</video>
```

and the following JS:

```
var videoPlayer = _V_('vid');

videoPlayer.ready(function(){
   videoPlayer.play();
});
```

This will work fine on all desktop browsers and technologies, yet Safari on iOS will throw the following exception:

```
DOMExceptionConstructor, "Video is not ready. (Video.js)"
```

The ExceptionConstructor unfolds to `INVALID_STATE_ERR: DOM Exception 11` leading me to the conclusion that the video actually is NOT ready, even though the ready handler already has fired.

**Comment by benedict-w** [comment]
I'm also having exactly this issue was it resolved?

**Comment by mmcc** [comment]
@benedict-w Can you give any more details? I'm not able to reproduce on an iPhone 6 and @heff was unable to reproduce on an iPad running iOS 7.

**Comment by benedict-w** [comment]
After restarting XCode and the iOS simulator it started working, so panic over! Thanks for your quick response.=
