### ISSUE TITLE
Ability to abstruct/hide video src

### ISSUE THREAD

**Issue by waakobrian** [videojs/video.js#6010]
## Description
We need a plugin that can abstruct the player src link making it VERY differicult to download videos even using video downloaders

**Comment by gkatsev** [comment]
This is kind of tricky as ultimately, you need to have a URL available. However, segment file formats like HLS or DASH do make it a lot harder to get the URL (and generally the download video context menu isn't available for those types of videos). You can also go further by implementing HLSe and even DRM, depending on your needs. In addition, you probably want to have some kind of id to source mapping service. So, at runtime, you can grab the id from the page and make a request that gives you back your source.

Hope this points you in the right direction.
