### ISSUE TITLE
Package Size Issue

### ISSUE THREAD

**Issue by hammaduzair** [videojs/video.js#6012]
I am currently using v7.1.0. The gzip size is ~100kb, which is way too much. Is there any way to reduce this size?

**Comment by gkatsev** [comment]
Unfortunately, there isn't much else. We plan to write something around why the size is what it is. The tl;dr is that Video.js does quite a lot and there's not really much that can be done to reduce the size out of the box. We have plans to make custom builds/modular pieces of the library so that you can remove pieces that you don't use yourself but that isn't ready yet.

**Comment by ehrig** [comment]
@gkatsev Any updates on the custom build process? I'd love to reduce the file size for projects that only require certain features. Is this going to be a web app that automatically generates the bundles and minified JS and CSS files according to my configuration?

**Comment by ewwwgiddings** [comment]
@ehrig I haven't tried it yet, but how you import it may be able to help you. Seems these people had success with at least if to include vtt or hls/dash. Thought it might be of use when I read your comment if you haven't seen it:

https://github.com/videojs/video.js/issues/6166

**Comment by ehrig** [comment]
Thanks for your reply @ewwwgiddings. I am actually using https://github.com/sampotts/plyr now instead, which is already super lightweight and skin customization is super simple.

**Comment by ewwwgiddings** [comment]
Hi, That is a really great alternative. I use that for an audio player I built. It has great functionality for YouTube/Vimeo videos also. Like you said it's very light.

Only thing that it doesn't have, as far as I know, is easy support for HLS/Dash if you ever need to introduce that it will be a lot less out-the-box than this library. Could be wrong with that.

Glad you figured it out. If you ever need this library again I can confirm for you the process in that link does drastically reduce the size.
