### ISSUE TITLE
Fullscreen control button left

### ISSUE THREAD

**Issue by AlbEagle** [videojs/video.js#6013]
hello,
the full screen button was always on the right, please can help me with to change to left the fullscreen control button.

Thanks

**Comment by gkatsev** [comment]
There are several ways of changing the button order, you can use flexbox css properties and set the order property to on the various controls to be what you want, though, that's not ideal. However, it does mean you just need to add some css.
You can manually move the button after the player is created, also, not ideal.
You can change the options for the player's control bar:
```js
var player = videojs('vid', {
  controlBar: {
    children: [
      'fullscreenToggle',
      'playToggle',
      'volumePanel',
      'currentTimeDisplay',
      'timeDivider',
      'durationDisplay',
      'progressControl',
      'liveDisplay',
      'seekToLive',
      'remainingTimeDisplay',
      'customControlSpacer',
      'playbackRateMenuButton',
      'chaptersButton',
      'descriptionsButton',
      'subsCapsButton',
      'audioTrackButton'
    ]
  }
});
```
You can see the default component tree on [our docs](https://docs.videojs.com/tutorial-components.html#default-component-tree). You can also find it [in the code](https://github.com/videojs/video.js/blob/master/src/js/control-bar/control-bar.js#L54-L72).

Hope this helps.
