### ISSUE TITLE
video can't play when video tag doesn't wrap source tag in it

### ISSUE THREAD

**Issue by SilentFlute** [videojs/video.js#6014]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.use script&link to loaded video.js&video-js.css
2.there is a video tag : 
```
        <video id="my-player" class="video-js vjs-default-skin vjs-big-play-centered" controls="controls" height="400" poster="xxx.jpg" src="xxx.mp4" width="400"></video>
```
3.video.js("my-player")
4.everything looks all right, no error on console, html render as well, the play button in the center, perfect!!!

## Results
but!!!!!!!!!!!!!!!!!
when I press the play button, it dosen't work, video does not play at all, and no error is been thrown either
### Expected
Please describe what you expected to see.
the video should play
### Actual
Please describe what actually happened.
video does not play 
### Error output
If there are any errors at all, please include them here.
no error message been thorwn

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
7.5.4
#### videojs
what version of videojs does this occur with?
7.5.4
#### browsers
what browser are affected?
74.0.3729.169
#### OSes
what platforms (operating systems and devices) are affected?
macOS Mojave 10.14.4
### plugins
are any videojs plugins being used on the page? If so, please list them below.
I don't think so, I only used `video-js.min.css` and `video.min.js`, it's a html file from the native, even without the devServer, the webpack thing u know

**Comment by SilentFlute** [comment]
and when I read the docs many times, I try this:
```
<video id="my-player" class="video-js vjs-default-skin vjs-big-play-centered" controls="controls" height="400" poster="xxx.jpg" width="400">
<source src="xxx.mp4" type="video/mp4">
</video>
```
video tag wrapped source tag in it, then it worked, when I press the play button, it works, video plays!!!
Is this a bug or thing???
cause I use `video.js` in the `ckeditor 4`, with the video upload plugin: `html5video`, when I insert a video into the editor, the video tag do not warp source tag in it, so if I want use `video.js` with, I should operate the dom element to make sure video tag wrap a source tag in it!
And btw, `ckeditor` the editor area is a `iframe`, `video.js` create a style tag with class `vjs-styles-defaults` and `vjs-styles-dimensions`, the contains the `width` and `height` information on it, but the video tag that user created is in the `iframe`, in the editor area, so `div.video-js` won't have the `width` and `height`, cause `div.video-js` in the `iframe`, but the style tag in the out of the `iframe`, is there a way to figure these things out??

**Comment by SilentFlute** [comment]
and the docs doesn't tell to use video tag wrap a source tag in it explicitly, I just realize that many examples use video tag warp a source tag, so I try, and it worked

**Comment by SilentFlute** [comment]
oh, the browser is chrome, chrome 74.0.3729.169

**Comment by gkatsev** [comment]
Yeah, unfortunately, it's a long standing issue with Video.js. See #5701 and #4851. We have the beginning of a fix for it in #5762 but we haven't had time to fix the issues with it.
I thought that we did document that users should use source elements but maybe it fell through the cracks as we expected users to follow the examples.

**Comment by SilentFlute** [comment]
@gkatsev oh thx, and one more thing: when I use the native video tag with the native control bar, is there possible to disable the double click to fullscreen on it? I tried listen the dblclick event on the video node, then event.preventDefault(); event.stopPropagation(); even the return false, but still not working: when I double click the video tag, it will go full screen
And I want to add a event listener on "mousemove", when the mouse move to the control bar area, the control bar show up, that I can play/pause the video, when the mouse move out of the control bar area, I remove the "controls" attribute, make the control bar "invisible", but I can't get control bar 's height dimension, so if u can give any advices it will be very appreciate🤣🤣

**Comment by gkatsev** [comment]
If you're using video.js, you can disable the double click by setting `userActions.doubleClick` to false: https://docs.videojs.com/tutorial-options.html#useractions-doubleclick
As for the native element, I'd expect listening to the event and calling preventDefault to work.

You won't be able to get the control bar height of the native controls and it'll be different depending on the browser you're in.

**Comment by SilentFlute** [comment]
I listening the `dblclick` event and calling `preventDefault` even `stopPropagation`, they doesn't work at all, the `video` will go full screen when I double click on it, but I finally find a way to figure this out:
the `controlsList` attribute in the `video` tag, write this in it, will disable the full screen function:
`<video controls="controls" controlslist="nofullscreen" .....`
the `fullscreen` button in the native control bar will become dim, and in the mean time, video won't go full screen when u double click it, and u click the dim full screen button on the control bar, the full screen function won't work either, but I can use some style code to make this button invisible, still thx❤️❤️

**Comment by gkatsev** [comment]
Ah, cool, I always forget about controlslist, mostly because it's a chrome-only feature right now :)

I'm going to close this issue for now as we still have #4851 and #5762 for tracking the src attribute work.

If you have more questions, feel free to post them here or drop by [our slack](http://slack.videojs.com).

**Comment by willpiam** [comment]
This is still and issue. It would be nice if an error was thrown which mentioned that this is a known issue. If that's not possible it should at least be mentioned in the docs in the section regarding the play() function and the PlayToggle component.  Probably in red bold text.
