### ISSUE TITLE
m3u8 playlist, with m4s segments not able to continue playback if EXT-X-ENDLIST is present

### ISSUE THREAD

**Issue by Shannonf** [videojs/video.js#6016]
Using an m3u8 playlist, I can successfully play back all of the m4s files in a Live-stream mode. 

But once the playlist is changed to having the "#EXT-X-ENDLIST", only the m3u8's get loaded, the initilization.mp4, and the first m4s segment. First segment will play normally, but player never even attempts to call the next segment. Is this something that simply is not supported?

The same playlist, mp4 and m4s's place correctly in VLC player.

No errors reported in console, even with the videojs.log.level('all'); -- it simply just stops playing after the first segment.

we are using videojs 7.5.4 in Google Chrome ,Windows 10
no additional plugins

**Comment by gkatsev** [comment]
Huh, that's weird. I'd expect it to work. Do you know if you get the same behavior with ts segments or extension like mp4?
