### ISSUE TITLE
why in some mobile phone can`t play went the first .ts file loaded

### ISSUE THREAD

**Issue by AboyL** [videojs/video.js#6017]
## Description

in a webivew,we use m3u8 file as our  media resources,at most Mobile phone,they playing when the fisrt ts file loaded,bug at some mobile we find by charles，they playing after load 4 or 5 .ts file，we do a test，in one mobile download the first .ts file use 2~3s,in other mobile also use 2~3s,their speed are  adjacent,why have the different ？
What can I do to solve the problem？

### Error output
no error output

## Additional Information
The normal  mobile is one plus 3t
the abnormal mobile is vivo x7
our application is in a webview not in browser

#### videojs
v7.4.1

#### OSes
android

### plugins
don`t use

**Comment by gkatsev** [comment]
by default, mobile devices play HLS natively. Whether a device will play back after one segment or 3 segments is handled by the browser/webview. You can try setting [overrideNative](https://github.com/videojs/http-streaming#overridenative) to use our playbackengine if MSE APIs are supported in the webview, it will generally work more reliably and more similarly.

**Comment by AboyL** [comment]
> by default, mobile devices play HLS natively. Whether a device will play back after one segment or 3 segments is handled by the browser/webview. You can try setting [overrideNative](https://github.com/videojs/http-streaming#overridenative) to use our playbackengine if MSE APIs are supported in the webview, it will generally work more reliably and more similarly.

thank you very much!they can solve my problem!

**Comment by gkatsev** [comment]
You're welcome. If you have more issues, feel free to open another issue.
