### ISSUE TITLE
Googlebot smartphone does not load videojs video

### ISSUE THREAD

**Issue by tanuu** [videojs/video.js#6023]
## Description
My website publishes videos using videojs. Over the past month, Google has de-indexed 80% of my video pages as "soft-404" errors, meaning they have "little or no content" (see https://tinyurl.com/yx9gaxlh). In the Google Search Console Live test, which uses Googlebot smartphone, the embedded videos fail to load due to a video.js javascript error. In Google's mobile-friendly test, which also uses Googlebot smartphone, the video on the videojs.com homepage also fails to load, again due to a javascript error. In very limited tests of other pages with embedded html5 video, videos loaded successfully with no errors. The error does not occur in Chrome developer tools (see below) or in any real world device I've tested on. This issue was reported by Sattar1 (https://github.com/videojs/video.js/issues/2400) in 2015 but was misunderstood -- the issue is not whether Googlebot smartphone *plays* videojs videos, but why it cannot LOAD them and how this might affect Google search crawling, indexing and ranking of pages that use the videojs player.  
![videojs](https://user-images.githubusercontent.com/8893700/58863529-4405a780-86b3-11e9-9620-08be8933373f.png)

   
 
## Steps to reproduce
1. Go to https://search.google.com/test/mobile-friendly
2. Paste https://videojs.com and hit TEST URL
3. See screenshot and javascript console messages (under "page loading issues", top left)
For comparison, repeat above with, https://flowplayer.com/demos/standard-setup and http://www.casedasole.it/googletest/index.html (basic html5 video)

### Expected
Googlebot smartphone would load the video and display it in the screen rendering

### Actual
The screen rendering shows a cross (X) in place of the videojs play button and the error message "No compatible source was found for this media".
 
### Error output
The Google results page reports under javascript console messages:
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. [object Object]"
Source: https://unpkg.com/video.js@7.5.4/dist/video.min.js:12

#### browsers
Googlebot smartphone user agent - Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) - see https://tinyurl.com/ltj6kod
#### OSes
Presumably Windows, Android, iOS?
### plugins
Unknown

**Comment by bcbclifford** [comment]
The problem is the Googlebot browser cannot play any video format, so the error is correct - there is no source that can be played. You could hide the error display so the preview renders just the poster and play button. That won't hide the console error, and I'd be very cautious about adding any special handling for Google's user agent.

```js
player.on('error', function() {
  if (player.error().code === 4 && navigator.userAgent === GOOGLEAGENTSTRING) {
    player.error(null);
  }
}
```

**Comment by tanuu** [comment]
The issue is not that the Googlebot doesn't play videos. It's that Googlebot is not _loading_ videojs videos. In the two examples I gave (under 3 above),  Googlebot does seem to load a basic html5 player and Flowplayer (at least, there is no error message on the video and you can see the play button).

I don't know how Google ranks a page with a video that does not load. But it does signal it as an error.

**Comment by tanuu** [comment]
Further to, following some webmaster advise I have added what Google calls "more highQ stuff" to my video pages - basically words, words, words. Googlebot is now happy and is starting to re-index the pages. Artificial intelligence in action.

**Comment by mister-ben** [comment]
Also a PR here to add an option to suppress the message #6057
