### ISSUE TITLE
video js liveui problem with dash 

### ISSUE THREAD

**Issue by CAglar62** [videojs/video.js#6025]
Hello. I am working on live DVR (or nDVR) functionality. With HLS stream, I am able to implement this functionality. As you can see in the following url https://codepen.io/caglar62/pen/BebKMX , There is a live stream but you can go back and watch DVR. However, when I tried the same thing with DASH stream, I t did not work like this. There is no problem with regular DVR with dash but when it comes to nDVR (or Live DVR) the seekbar does not work. The indicator starts at the beginning and it stops playing after a few seconds. This is dash with nDVR https://ibb.co/znkKDLP. This is dash with regular DVR https://ibb.co/Yp0Wrwf. Dash with liveui does not work like HLS with liveui. Is there any solution to this.

**Comment by gkatsev** [comment]
Do you have the dash source available for us to test with?

**Comment by gkatsev** [comment]
Using the built-in liveui functionality and this test live stream with dash (https://vm2.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd), it's working correctly for me.
