### ISSUE TITLE
Videojs failed to resolve the authentication play address

### ISSUE THREAD

**Issue by xubingbing** [videojs/video.js#6026]
How does videojs parse the URL with authentication parameters?

**Comment by gkatsev** [comment]
I'm not quite sure what you mean by authentication param, but if it's a query parameter on the url, we don't do anything with it and use the url directly as is or pass it to the browser as is.

**Comment by xubingbing** [comment]
您好，我们是用阿里云直播URL推流，推流URL加了鉴权，是为了防止盗链，当时用videojs不能播放

**Comment by gkatsev** [comment]
Can you provide more information on what you're playing? Is it HLS? Have any examples on how it looks or documentation? What browsers are you targeting and what version of Video.js is being used?

**Comment by xubingbing** [comment]
你好，我用的阿里云推流带鉴权URL：播流地址  rtmp://test.xajyun.com/xjdas/rmvf862815039459530?auth_key=1558518717-0-0-3f8acf65e2fb9f1907e02389d414aac4；
浏览器：谷歌和火狐；
Video.js版本：Video.js 5.0.2；
播放器：VideoJS.swf

**Comment by mister-ben** [comment]
Try rtmp://test.xajyun.com/xjdas?auth_key=1558518717-0-0-3f8acf65e2fb9f1907e02389d414aac4&rmvf862815039459530

**Comment by xubingbing** [comment]
Try rtmp://test.xajyun.com/xjdas? Auth_key = 1558518717-0-0-3f8acf65e2fb9f1907e02389d414aac4&rmvf862815039459530 What do you do with &rmvf862815039459530?

**Comment by mister-ben** [comment]
With RTMP there is a connection URL, and a stream name. Video.js uses an `&` as a separator in the source string to tell which part is which.

    rtmp://example.com/app&streamname

So if `?auth_key=123` is aquery string which needs to be part of the connection URL, it should appear before the separator and stream name.

    rtmp://example.com/app?auth_key=123&streamname

I'm assuming from your example `rmvf862815039459530` is the stream name as it's the last part of your URL.

That's not guaranteed to work, as there many implementations of RTMP servers that all do things differently, but I've known that to work in some instances.

**Comment by xubingbing** [comment]
The video stream is encrypted and cannot be played. Authentication prevents theft.
