### ISSUE TITLE
Too many globals added by videojs

### ISSUE THREAD

**Issue by jelbourn** [videojs/video.js#603]
Right now, videojs seems to add 5 properties to the global object. 
Example: http://jsbin.com/izovid/7/edit

Some of these properties are minified by the closure compiler (in the example, "xd", "yd", "pd")

This is problematic for anyone that includes the minified videojs script in a project that has been independently minified with the closure compiler because it is possible that the minified properties collide and overwrite.

Ideally, the library would only touch the global object with the single "videojs" property.

**Comment by mreinstein** [comment]
@heff @gkatsev This still seems to be a problem in 6.10:

http://jsbin.com/nuveduhutu/7/edit?html,js,console,output

```
"Globals added: "
[ "vdata1532308500384", "vttjs", "WebVTT", "videojs" ]
```

can we re-open this issue please?
