### ISSUE TITLE
Video js seek is not working on chrome

### ISSUE THREAD

**Issue by arunwebber** [videojs/video.js#6030]
Hi, I am using video js for playing videos on my website everything is working perfectly on firefox but if I see the video on chrome it's not working as expected. Seek bar is not working if I press on seek bar the video will start to play from the beginning.

But I am able to seek the video on localhost with chrome

**Comment by gkatsev** [comment]
This is likely because whatever is serving the media doesn't support byte-range requests which chrome requires. See https://docs.videojs.com/tutorial-troubleshooting.html#problems-when-hosting-media for more info.

**Comment by ijunaid8989** [comment]
I am sending the correct content type for mp4 file but still seek bar is not working.
