### ISSUE TITLE
Dependency failures under node 12.4.0

### ISSUE THREAD

**Issue by brion** [videojs/video.js#6033]
## Description
Testing with node 12.4.0 as installed on MacOS 10.14 via Homebrew.
Clone the repo and run `npm install`.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. `git clone git@github.com:videojs/video.js.git`
2. `cd video.js`
3. `npm install`

### Expected
Successful install of dependencies.

### Actual
Compilation errors in `node-sass` and `fsevents` modules.

### Error output
If there are any errors at all, please include them here.

```
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:223:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:356:37: error: too few arguments toIn file included from  ../fsevents.ccfunction: 6call,:
 In file included from expected../../nan/nan.h :2,223 :
haveIn file included from  ../../nan/nan_new.h1:189
:
../../nan/nan_implementation_12_inl.h:356:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/brion/.node-gyp/12.4.0/include/node/v8.h:5380:3: note: 'New' declared here  return v8::StringObject::New(value).As<v8::StringObject>();

         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/brion/.node-gyp/12.4.0/include/node/v8.h:5380:3: note: 'New' declared here  static Local<Value> New(Isolate* isolate, Local<String> value);

  ^
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
```
etc etc etc

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
git commit ef49a9be7e413915961bb9ab6b20d9f5c92a907c
#### browsers
n/a
#### OSes
tested macOS 10.14
### plugins
n/a

I was able to work around the installation failures by updating `fsevents` from 1.2.7 to 1.2.9, and `node-sass` from 4.11.0 to 4.12.0.

**Comment by gkatsev** [comment]
Thanks! Looks like we need to update our dependencies/package-lock file.
