### ISSUE TITLE
Seekbar is not working in chrome

### ISSUE THREAD

**Issue by adnanalidzinemedia** [videojs/video.js#6037]
## Description
The seekbar is not working the chrome but it is working in the firefox and microsoft edge what the problem with chrome and how to resolved it.

#

**Comment by gkatsev** [comment]
Can you elaborate on what you mean by "not working"? Have a minimal reproducible example?
Is it always restarting from the beginning of the video when seeking? If so, that means that the place serving your media doesn't support byte-range requests and unfortunately it's required for proper playback and seeking on Chrome.
