### ISSUE TITLE
How to remove a videojs player after showing ads?

### ISSUE THREAD

**Issue by BorisJ28** [videojs/video.js#6039]
Hello, 
I have this question: How to remove a videojs player when the user presses the ads skip button or after showing ads.  I know the about player.dispose();, but I can’t determine when the user presses the skip button or if the ads ended.
Thank you.

**Comment by gkatsev** [comment]
Assuming you're using contrib-ads and your ad integration is calling the proper methods, you could listen to the `adskip` event on the player.

**Comment by BorisJ28** [comment]
Hi
I already did it myself thanks a lot for your response.

**Comment by gkatsev** [comment]
Glad to hear it. Thanks for circling back.

**Comment by lakshmikanth-reddy-au2** [comment]
Hi @BorisJ28 / @gkatsev can any of you please tell me exactly how to use adskip event? Or any example to skip ads please?
