### ISSUE TITLE
Chapter Menu tooltip positon in IE is not the same as in chrome.

### ISSUE THREAD

**Issue by TulikaRajpoot** [videojs/video.js#6040]
When mouse over in chapter menu, the tooltip position is above the  pointer postion while it is in chrome  below the pointer
attachment for chrome and IE attached please see # 1 for chrome #2 for IE
![2019_06_11_16_31_16_chrome](https://user-images.githubusercontent.com/51709675/59279008-c9bfbf00-8c80-11e9-8c18-a9e0fd081b80.png)

![2019_06_11_16_33_47_Internet_Explorer](https://user-images.githubusercontent.com/51709675/59279022-d3492700-8c80-11e9-9ebc-f16d92b1100d.png)

Is there any way to fix  the position of tooltip  as chrome has for Internet Explore.

Please help to fix the position In IE

**Comment by gkatsev** [comment]
This is due to our usage of the `title` attribute. Different browsers display it differently.
At some point when we catch up on high priority work, we'll implement custom tooltips. Unfortunately, until then there isn't anything that can be done.
