### ISSUE TITLE
Breaking changes during minor v7

### ISSUE THREAD

**Issue by mysuf** [videojs/video.js#6047]
Hi, I found out that there was number of breaking changes during minor versioning of v7 (tested on v7.5.4)

~~As you know, best practice for dev automated testing is using node_modules libraries. We are testing each major version of video.js with selenium and **now there is breaking change in dist folder because all js files was moved** to alt folder (or missing in npm bundle). Of course it also broke your package.json links to common and es modules.~~

Edit: Uff. This is npm push issue. 7.5.4 bundle is missing some dist files. v7.5.5 works. Closing

Another example: static prefix "-" in remaining time component createEl() method.
I would expect two methods for handling the text. One for static label and second for dynamic value so it could be easily overriden. Now it is fragmented into 3 methods and I'm missing purpose of such change. createEl sounds like core method that does not handle content..

You should do breaking changes as minor only if necessary and not for cosmetic impression. I'm not sure where video.js is heading, but I don't feel good about it.

**Comment by gkatsev** [comment]
We definitely try to not make any breaking changes outside of a major release. As far as I can tell 7.5.4 has all the correct files as viewed by https://unpkg.com/video.js@7.5.4/dist/.
If a breaking change happened inadvertently, we would definitely revert the change and do a patch release to bring it back.

I'm not quite following the createEl() issue, if it's still a problem, can you create a new issue, perhaps with examples? Thanks.

**Comment by mysuf** [comment]
Hi @gkatsev , maybe I had broken node_modules. Anyway, how would you display custom remaining time without leading "-" prefix? The only way that I know is ugly calling of grandparent `createEl() { return TimeDisplay.prototype.createEl.call(this);` } `.
