### ISSUE TITLE
Why is options function deprecated? 

### ISSUE THREAD

**Issue by cristian-atehortua** [videojs/video.js#6048]
This is a question: Why is options function deprecated? I mean, is there a way to set options after a component is constructed? Is there a way to get options later without using "private" property options_?

**Comment by gkatsev** [comment]
The thought at the time was that option() shouldn't be publicly available and that individual plugins and components should expose the specific items that can and should be changed via an API. However, it seems like there's a lot of usage of options() and removing it is likely to cause a lot of churn, so, we may end up never removing it.
