### ISSUE TITLE
音视频不同步的问题

### ISSUE THREAD

**Issue by tianqbubai** [videojs/video.js#6052]
hi, 直播的时候，为了保证实时性，会丢弃一部分媒体数据，我们在用flvjs播放的时候，丢数据只会，会出现音视频不同步的情况，当不同步之后，设置下video的currentTime, 就恢复同步了。同时，我们试用ffplay拉流，未出现这个情况，请教一下，这可能因什么导致呢？

**Comment by gkatsev** [comment]
We do have an issue with AV sync, unfortunately. See https://github.com/videojs/video.js/issues/6000#issuecomment-496561271.

**Comment by gkatsev** [comment]
Closing as a dupe of #6000.
