### ISSUE TITLE
multiple video players(infinite feed) one after another

### ISSUE THREAD

**Issue by hammaduzair** [videojs/video.js#6060]
We are making a sort of video platform where videos are present one after another in the mobile web. The video in the viewport is autoplayed. But I also prefetch the data of the next 5 videos to improve performance. this is an infinite feed, so the videos keep on loading. Having so many video players are affecting the platform performance. So I was hoping to keep only 5 video players ( 2 above and 2 below current video in viewport) and  dispose of the rest and reload them when the current video in viewport changes. This isn't quite working out. Is there something i am missing or is there function to handle the same

**Comment by gkatsev** [comment]
You can call `dispose` on the player to dispose it.
Alternatively, you can use link tags with prefetch attributes to initiate connections early as well and use just one player.
Unfortunately, your question is a big vague, so, I can't have a better answer for you.
