### ISSUE TITLE
Open devtool, the video size ratio changed.

### ISSUE THREAD

**Issue by Luncher** [videojs/video.js#6069]
## Description

when i open the devtool,  the video size ratio changed.

`normal: `
![image](https://user-images.githubusercontent.com/5138977/59998469-139da180-9692-11e9-93df-3eded99bf8c2.png)

`open devtool`
![image](https://user-images.githubusercontent.com/5138977/59998466-0bddfd00-9692-11e9-9e64-0311aa80674e.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. my options:

```js
{
autoplay: true,
controls: true,
sources: [{
src: "rtmp://10.200.20.49:2345/2akrar93dqurh/ipc-4342117?domain=1playx.domain1.com&e=1561362481&policy=eyJwbGF5TGltaXQiOjQwfQ%3D%3D&route=MTQwLjIwNi42Ni40Ml8xMC4yMDAuMjAuMjk%3D&token=test123%3AYkx7845jrfv5BDp9W9nN7knVrAI"
type: "rtmp/mp4"}],
techOrder:  ["flash", "html5"]
}
```

2. class:

**video-js vjs-big-play-centered**
width: 100%
height: 100%

### Expected
I want the open devtool result.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
`5.20.5`

#### browsers
`74.0.3729.169`

#### OSes
`Darwin Kernel Version 18.6.0`

**Comment by gkatsev** [comment]
We have a version of the video.js swf which may [fix it](https://github.com/videojs/video-js-swf/commit/9235db741bc188abb21e03fa78cd8c59a8392c8b): https://github.com/videojs/video-js-swf/releases/tag/v5.4.2.

**Comment by Luncher** [comment]
What should I do? I see that my version is already higher than 5.4.

**Comment by gkatsev** [comment]
Do you have 5.4.2 specifically? Otherwise, I'm not sure and we'll be very unlikely to take a look given that it's Flash.
