### ISSUE TITLE
there is an unknown character in the vjs-spacer

### ISSUE THREAD

**Issue by anyGuest** [videojs/video.js#6072]
I don't know why there is an unknown character

`<div class="vjs-custom-control-spacer vjs-spacer ">聽</div>`

**Comment by gkatsev** [comment]
The spacer has a no-break space character in it. If you're viewing it using a different encoding (other than utf-8), it may show up incorrectly.
https://github.com/videojs/video.js/blob/master/src/js/control-bar/spacer-controls/custom-control-spacer.js#L37
http://www.fileformat.info/info/unicode/char/00a0/index.htm
