### ISSUE TITLE
Video stalling on chrome

### ISSUE THREAD

**Issue by flexicious** [videojs/video.js#6074]
## Description
Briefly describe the issue.
Video seems to stall after a few seconds on chrome. Works fine in FF and IE

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load the test case
2. Click the play button
3.

## Results
Video stalls mid way
### Expected
Video should play all the way through the end
### Actual
Video stalls mid way

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
latest
#### browsers
chrome

#### OSes
windows
### plugins
none

Below is the test case:
[videotest.html.txt](https://github.com/videojs/video.js/files/3323081/videotest.html.txt)

**Comment by flexicious** [comment]
`<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>videojs-contrib-hls embed</title>
 <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
</head>
<body>
 <h1>Video.js Example Embed</h1>

 <video-js id="my_video_1" class="vjs-default-skin" controls preload="auto" width="640" height="268">
   <source src="http://wowza.montessorirx.com:1935/vod/smil:06Order_1Mb.smil/playlist.m3u8" type="application/x-mpegURL">
 </video-js>
 
 <script src="https://unpkg.com/video.js/dist/video.js"></script>
 <script src="https://unpkg.com/@videojs/http-streaming/dist/videojs-http-streaming.js"></script>
 
 <script>
   var player = videojs('my_video_1');
 </script>
 
</body>
</html>
`

**Comment by gkatsev** [comment]
This is super weird. I can confirm that it works in Firefox and Safari but not in Chrome. I've also reproduced this behavior with Shaka player and hls.js.

**Comment by llioor** [comment]
I have the same issue....
1. Video is stalling on Chrome for the first segment.
2. If I click "Replay" I have the same lags on the beginning.
3. If I change the time manually to 0:00 and click "play" I don't have lags at all!

It happens only when I load the video first time or click "replay"

**Comment by gkatsev** [comment]
This is likely related to our detection of non-idr keyframes: https://github.com/videojs/mux.js/issues/237.

**Comment by flexicious** [comment]
Not sure i understand. Is there a configuration setting i can use to change this behavior?

**Comment by gkatsev** [comment]
The quick answer is that to get it working, you'll likely have to retranscode or wait till we have time to fix the linked issue.
