### ISSUE TITLE
HLS video not playing in mobile browser.

### ISSUE THREAD

**Issue by melzoSMIS** [videojs/video.js#6076]
## Description
I am working on aframe and video.js in react to show a 360 video (hls video) in browser.
It is working fine in desktop browser but in mobile browser it shows black screen and plays only audio.
Search almost everything.
Project url : https://melzo.com/dekho/5d0b7e1ab263bf000fa383a7
open this in mobile browser and and click on tutorial2

Browser error : VIDEO.JS (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

### Expected
HLS 360 video should work perfectly.

### Actual
Browser shows black screen while playing .m3u8(hls) 360 video

### Error output
VIDEO.JS (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

#### videojs
7.5.5
#### browsers
Google chrome 75
#### OSes
Android, iPhone

**Comment by gkatsev** [comment]
The above link is working for me on Chrome for Android, though, there's no "tutorial2" link.
on iOS, there are definitely some restrictions and caveats to getting 360 video working, particularly around cross origin video, though, I think recent versions of iOS are working better.

**Comment by marshalys** [comment]
I get the same error on iphone safari.
I found the reason is the video `tag` in safari not support set a m3u8 link to `src` attribute, if you set cause error `MEDIA_ERR_SRC_NOT_SUPPORTED `. 
And I check the code,  maybe this line cause the error: https://github.com/videojs/video.js/blob/83541dceeb6a665dabf80a9749539b221b34e075/src/js/tech/html5.js#L46

**Comment by abolffax** [comment]
hello 
i have a video player my video player name (elite video player HTML5)
my video format is HLS (m3u8)
how i can set domain in embeded code for palying video in one website
that's means :
don't showing in other website
and only playing on my website  Or only on user website show
.
.
.
< help me in  github telegram instagram>
[telegram](https://t.me/abolffax)
[instagram](https://www.instagram.com/abolffax)
