### ISSUE TITLE
how to avoid loading the whole video on iOS Safari

### ISSUE THREAD

**Issue by levi0214** [videojs/video.js#6082]
## Description
When I play the video and pause it on **iOS Safari**, it would keep loading the whole video.... Is it normal and how can I control it? 

(ps: I have multiple videos on the same page)

**Comment by gkatsev** [comment]
How long/large is your video? Is it an mp4? We don't handle the buffering for any video formats on iOS currently as MSE is not supported. Safari handles it however it feels creates the best user experience.
If the videos are short and small, Safari could definitely end up preloading the entire video but I believe it tends to only load a portion if it's a large video.

**Comment by levi0214** [comment]
Thank you! I found that iOS Safari would load about 30MB of the mp4 video.
For multiple videos on the same page, I think `preload=none` is the best choice.
