### ISSUE TITLE
LiveUI doesn't work properly in Edge

### ISSUE THREAD

**Issue by davemevans** [videojs/video.js#6086]
## Description
In Edge, the live indicator is not lit and the scrub bar sits around 30s back from the live edge.
The liveui sandbox demonstrates the problem: http://localhost:9999/sandbox/liveui.html, codepen https://codepen.io/anon/pen/ydqELd?editors=1000#0

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. open liveui sandbox example (or https://codepen.io/anon/pen/ydqELd?editors=1000#0) and click play

### Expected
Live indicator is lit red, scrub bar is filled all the way

### Actual
Live indicator not lit, scrub bar around 30s behind live

### Error output
No errors in console

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.0
#### browsers
Edge
#### OSes
Windows 10
### plugins
N/A

Note that it makes no difference whether `overrideNative` is enabled or not.

**Comment by mister-ben** [comment]
I just tested this on Edge 18 in browserstack. I saw this behaviour with Edge's native HLS, but it did work properly with overrideNative.

**Comment by davemevans** [comment]
Agreed.

I was adding `overrideNative: true` in the `src` object, and that did not work.

Adding: 
```
,
                              
  html5: {
    hls: {
      overrideNative: true
    },
    nativeAudioTracks: false,
    nativeVideoTracks: false,
  }
```
does work.

Thanks.
