### ISSUE TITLE
LiveUI does not work on Firefox for Android

### ISSUE THREAD

**Issue by davemevans** [videojs/video.js#6087]
## Description
LiveUI completely unavailable in Firefox for Android. See https://codepen.io/anon/pen/ydqELd?editors=1000#0 on Firefox for Android.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Navigate to https://codepen.io/anon/pen/ydqELd?editors=1000#0 and press play

### Expected
Live indicator shows, scrub bar full.

### Actual
No live indicator, scrub bar starts at zero and increments

### Error output
No console :(

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.0
#### browsers
Firefox for Android
#### OSes
Android 9
### plugins
N/A

**Comment by mister-ben** [comment]
It works with MSE playback instead of native. You can add this to the player options

```
{
  html5: {
    hls: {
      overrideNative: true
    },
    nativeAudioTracks: false,
    nativeVideoTracks: false,
  }
}
```

**Comment by davemevans** [comment]
Yes, that works.

I assumed because Firefox Android is not listed at https://github.com/videojs/http-streaming#via-mse, I assumed it would work without those options.

Thanks!
