### ISSUE TITLE
 tsml is no longer maintained

### ISSUE THREAD

**Issue by Sozialarchiv** [videojs/video.js#6089]
## Description

The package tsml is not longer maintained

## Steps to reproduce

1. yarn upgrade

### Expected

No warning/error

### Actual

tsml@1.0.1: no longer maintained

### Error output

tsml@1.0.1: no longer maintained

#### videojs
7.5.5
#### browsers
All
#### OSes
All

**Comment by gkatsev** [comment]
Thanks! We have noticed but we thought this is a relatively minor issue that we can avoid looking at while we have more pressing concerns.
We would definitely appreciate help in removing the dependency, but otherwise, it may be a while before we remove it.

**Comment by retrocausal** [comment]
@gkatsev production builds are failing because of this. most of our builds are automated, and do a fresh npm i per build via jenkins. This means, we can no longer deploy as long as we use video.js.

**Comment by gkatsev** [comment]
@retrocausal can I ask you how you have things set up that it fails? Does it reject builds that contain any warnings?

**Comment by Sozialarchiv** [comment]
@brandonocasey Thank you

**Comment by gkatsev** [comment]
This is out in the 7.6.3 prerelease.
