### ISSUE TITLE
[7.6.0] click event is not triggered

### ISSUE THREAD

**Issue by boris-petrov** [videojs/video.js#6092]
## Description
`click` event is not triggered for the small play button.
[Reduced test case](https://codepen.io/anon/pen/xoBwPG?editors=1111).

## Steps to reproduce
Press the big play button and you see a log in the console. But then pressing pause/play (the small button on the bottom left) doesn't log it any more. Changing the version to `7.5.6` fixes the issue and every click produces a log in the console.

### Expected
Expected multiple logs.

### Actual
A single log appears.

## Additional Information
[Here is more information](https://github.com/videojs/video.js/pull/5803#issuecomment-510389720) about the issue and the potential PR that broke it.

**Comment by gkatsev** [comment]
Thanks for opening the issue, finally have time to look at it. The #5803 is definitely what introduced the issue and it's definitely something that we should handle. Looking into it some more, it sounds like polymer 2.x and newer don't recommend the usage of the `tap` event. Using the `click` event doesn't exhibit the bad behavior. I'm not sure if polymer 1.x has `click` events but fixing polymer's tap event while breaking everyone else's click handler on the player is not a good trade off.
I'll revert the changes from #5803 and then think about whether there's anything we can do beyond strongly suggesting people follow polymer's recommendation of *not* using the `tap` event.

**Comment by boris-petrov** [comment]
@gkatsev - thank you for the time and fixing this! I also think this is a major regression. So thanks again for the support!

**Comment by gkatsev** [comment]
@boris-petrov you're welcome. I hope to have the patch released this week.
