### ISSUE TITLE
PIPELINE_ERROR_DECODE with HLS playback on Chrome

### ISSUE THREAD

**Issue by mikeodysseos** [videojs/video.js#6093]
## Description
We are experiencing an issue with Chrome Version 75.0.3770.100 (Official Build) (64-bit) where Video.JS (https://vjs.zencdn.net/7.5.4/video.min.js) brings a "The media playback was aborted due to a corruption problem or because the media used features your browser did not support." error. It is not specific with a single HLS playlist and the issue is persistent only with Chrome. Firefox and mobile browsers work well. It is only the 2nd time I am opening a ticket so I hope I followed all the guidelines.

## Steps to reproduce
1. Go to https://www.ant1.com.cy/webtv/show-page/episodeinner/?showID=99809&episodeID=109813
2. Play Video
3. At on average 15 minutes in, the error comes up.

### Expected
Video should play without interruptions. 

### Actual
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

### Error output
**In the console** I see this error:

video.min.js:12 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 
Tt {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}
code: 3
message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."
__proto__: Object

**chrome://media-internals/** brings this output 

`00:19:04.671 | error | Failed to send audio packet for decoding: timestamp=1143274666 duration=21333 size=226 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (us)=(0, 0)
-- | -- | --
00:19:04.671 | error | audio decode error
00:19:04.691 | error | audio error during playing, status: PIPELINE_ERROR_DECODE
00:19:04.691 | pipeline_error | PIPELINE_ERROR_DECODE
00:19:04.691 | pipeline_state | kStopping
00:19:04.691 | event | PAUSE
00:19:04.692 | pipeline_state | kStopped`

### plugins
videojs-hls-quality-selector.min.js
videojs-contrib-quality-levels.min.js
videojs-brand.min.js
videojs-preroll.min.js

**Comment by gkatsev** [comment]
One thing to verify is whether AAC SSR is being used. It seems like in chrome, that isn't supported and a potential source of the PIPELINE_ERROR_DECODE error message. See https://bugs.chromium.org/p/chromium/issues/detail?id=808064.
If that's the case, there's not much we can do unfortunately.

**Comment by mikeodysseos** [comment]
> One thing to verify is whether AAC SSR is being used. It seems like in chrome, that isn't supported and a potential source of the PIPELINE_ERROR_DECODE error message. See https://bugs.chromium.org/p/chromium/issues/detail?id=808064.
> If that's the case, there's not much we can do unfortunately.

Thank you for your feedback! Audio codec is aac (LC) so I think that the error is not relevant to the link you posted, although I have thoroughly investigated the possibility. Of course I believe it still remains an issue of Chromium, since it works fine on other browsers.

**Comment by mikeodysseos** [comment]
UPDATE: I might have to close this issue. I found out that when running 
"ffmpeg -i segm000140.ts -v debug"
(which is the file that Chrome tried to play after switching from 720p to 540p before it crashed), this information came up (it didn't came up with the 720p version in the playlist):

[mpegts @ 00000192c2b987c0] Packet had TEI flag set; marking as corrupt

but my question is, why does this only happen with Chrome? Does anyone have an idea why this is not a problem with Firefox? or any other player like VLC for example?

**Comment by gkatsev** [comment]
Unfortunately, it's kind of hard to diagnose. Chrome is very persnickety with its media decoding.

**Comment by mikeodysseos** [comment]
New update: it seems that the PIPELINE_ERROR_DECODE isn't related to quality switching. I have transcoded again the original video and the player crashed again. This happens on a very random basis and largely seems unrelated to specific packets.

**Comment by vkulov** [comment]
We are having the same issue. PIPELINE_ERROR_DECODE when using video.js on Android, Chrome

After trying a lot of ffmpeg options thinking it's a codec or container issue we tried switching the player.

The stream is audio only AAC codec in a x264 container.

Here's a link to the stream.
https://ds60kqpssvcah.cloudfront.net/master.m3u8

And here's a test page using hls.js npm package that can play the stream above just fine in Chrome on Android.
https://ds60kqpssvcah.cloudfront.net/test.html

**Comment by dalecurtis** [comment]
This (historically) has always been due to corrupt aac packets. Using ffmpeg I tested the stream you have on that bug (if replicating, make sure you're using tip-of-tree ffmpeg):
ffmpeg -err_detect explode -v debug -i http://ds60kqpssvcah.cloudfront.net/media.m3u8 -vn -acodec pcm_f32le out.wav

It was able to decode the audio for the stream just fine, so it seems likely that there's some demuxing issue with video.js which is corrupting the AAC packet along the way. I don't know where that might be.

I also converted it to an adts file while copying the aac bitstream and Chrome played the file without issue:
ffmpeg -err_detect explode -v debug -i http://ds60kqpssvcah.cloudfront.net/media.m3u8 -vn -acodec copy out.adts

As such the video.js folks to take a closer look to figure out what's going on.

**Comment by dalecurtis** [comment]
ADTS does have an incorrect duration though, so that may be a hint. If you write it as an mp4 file:
ffmpeg -err_detect explode -v debug -i http://ds60kqpssvcah.cloudfront.net/media.m3u8 -vn -acodec copy out.mp4

You end up with something that's 1m20s in length.

**Comment by wkh237** [comment]
We've been into similar issue and that turns out we're using a very high bitrate in out video stream (~19Mbps). After reduce it to ~5kbps it works seemly.

**Comment by mikeodysseos** [comment]
> We've been into similar issue and that turns out we're using a very high bitrate in out video stream (~19Mbps). After reduce it to ~5kbps it works seemly.

Interesting. We encode at 2.5mbps which should be fine. The issue here is that Chrome says it's the players' fault and video.js community says it's Chrome's fault! Firefox and Edge play fine so it would be extremely nice if Chrome pushes some sort of an update for working in the same way :/
