### ISSUE TITLE
No Autoplay attribute but still autoplaying in chrome 

### ISSUE THREAD

**Issue by CommunityMediaPA** [videojs/video.js#6094]
Sorry if this is posted somewhere else. I'm embedding an hls source.  I didn't add the autoplay attribute but the video is still autoplaying in chrome on the desktop.  
https://www.communitymedia.net/live

```
<video-js id=cm_main_live class="vjs-default-skin vjs-16-9 vjs-big-play-centered" controls>
<source
     src="https://dvgedpnbdtxi2.cloudfront.net/out/v1/a7982831f1264e5c8ab4eeb63d105194/mainout2.m3u8"
     type="application/x-mpegURL">
</video-js>
<script src="http://communitymedia.net/assets/videojs/videojs-http-streaming.js"></script>
<script>
var player = videojs('cm_main_live');
player.play();
</script>

```

#### videojs
Video.js 7.3.0
#### browsers
chrome
### plugins
http-streaming

**Comment by mister-ben** [comment]
You have `player.play()`. Chrome's restriction on autoplay, or calling `play()` without user interaction, is based on the user's previous interaction with the site, so it may autoplay for you. It doesn't for me. See https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Other modern browsers simply don't autoplay unless muted.

**Comment by CommunityMediaPA** [comment]
> 
> 
> You have `player.play()`. Chrome's restriction on autoplay, or calling `play()` without user interaction, is based on the user's previous interaction with the site, so it may autoplay for you. It doesn't for me. See https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> 
> Other modern browsers simply don't autoplay unless muted.

Thanks for the info!
