### ISSUE TITLE
rtmp can not play

### ISSUE THREAD

**Issue by 875029946** [videojs/video.js#6096]
rtmp://live.rainfo.cn/test/tee?auth_key=15631787372-0-0-c2f97e94b5a243198f449bb10e379b02
video.js  can not play
use other flash video can play

**Comment by mister-ben** [comment]
Assuming you are using the [Flash tech](https://github.com/videojs/videojs-flash) and a browser that still supports Flash and had it installed, then you probably need to hcange your URL to make the query param part of the connection URL and not the stream name.

There are different conventions to writing the connection URL and stream name as one string, but it gets complicated when using query params. It _might_ work like this - the stream name is at the end after an `&` separator.

    { type: 'rtmp/flv', src: 'rtmp://live.rainfo.cn/test?auth_key=15631787372-0-0-c2f97e94b5a243198f449bb10e379b02&tee' }

**Comment by scy1211** [comment]
@875029946 Hello, I have the same problem as you. How did you finally solve this problem?
