### ISSUE TITLE
VIDEOJS: ERROR: DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

### ISSUE THREAD

**Issue by wmlgl** [videojs/video.js#6097]
## Description
Play a live address, Sometimes, got this error.
Demo:  https://wmlgl.github.io/webtest/bug_report/videojs/20190715/
This demo's video was downloaded when error occurring.

## Steps to reproduce
1.open demo in browser
2.click play button
3.display a error

### Expected
no error

### Actual
can't play

### Error output
[Violation] 'setTimeout' handler took 79ms
video.js:142 VIDEOJS: DEBUG: VHS: SegmentLoader[main] > playlist update [null => http://14.18.146.169:58801//live//139_hrs_live/14149/index.m3u8]
video.js:142 VIDEOJS: DEBUG: VHS: SyncController > syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]
video.js:142 VIDEOJS: DEBUG: VHS: MPC > seekable updated [0 => 4]
video.js:142 VIDEOJS: DEBUG: VHS: MPC > Setting duration from NaN => Infinity
video.js:142 VIDEOJS: DEBUG: VHS: SegmentLoader[main] > INIT -> READY
11XHR finished loading: GET "<URL>".
video.js:142 VIDEOJS: DEBUG: VHS: SourceUpdater[main][video/mp2t; codecs="avc1.4d400d, mp4a.40.2"] > created SourceBuffer
video.js:142 VIDEOJS: DEBUG: VHS: SyncController > syncPoint for [time: 4] chosen with strategy [Playlist]: [time:0, segmentIndex:0]
video.js:142 VIDEOJS: DEBUG: VHS: SegmentLoader[main] > READY -> WAITING
video.js:142 VIDEOJS: DEBUG: VHS: SyncController > time mapping for timeline 0: [time: 2] [mapping: -14770.076]
video.js:142 VIDEOJS: DEBUG: VHS: SegmentLoader[main] > WAITING -> APPENDING
video.js:142 VIDEOJS: DEBUG: VHS: SegmentLoader[main] > appending [1] of [15665, 15671] from playlist [0] [2 => 3.900000000001455] in timeline [0]
video.js:142 VIDEOJS: ERROR: DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at Object.get$$1 (https://unpkg.com/video.js@7.6.0/dist/video.js:51172:32)
    at buffered (https://unpkg.com/video.js@7.6.0/dist/video.js:51081:21)
    at VirtualSourceBuffer.get$$1 (https://unpkg.com/video.js@7.6.0/dist/video.js:51309:18)
    at SourceUpdater.buffered (https://unpkg.com/video.js@7.6.0/dist/video.js:53112:35)
    at VirtualSourceBuffer.onUpdateendCallback_ (https://unpkg.com/video.js@7.6.0/dist/video.js:53041:63)
    at VirtualSourceBuffer.data.dispatcher (https://unpkg.com/video.js@7.6.0/dist/video.js:1824:33)
    at trigger (https://unpkg.com/video.js@7.6.0/dist/video.js:1960:27)
    at VirtualSourceBuffer.EventTarget.trigger (https://unpkg.com/video.js@7.6.0/dist/video.js:2479:5)
    at SourceBuffer.<anonymous> (https://unpkg.com/video.js@7.6.0/dist/video.js:51463:31)
(anonymous) @ video.js:142
log.error @ video.js:330
data.dispatcher @ video.js:1826
trigger @ video.js:1960
EventTarget.trigger @ video.js:2479
(anonymous) @ video.js:51463
video.js:142 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}
(anonymous) @ video.js:142
log.error @ video.js:330
error @ video.js:27437
handleTechError_ @ video.js:25735
bound @ video.js:2200
bound @ video.js:2200
data.dispatcher @ video.js:1824
error (async)
on @ video.js:1844
listen @ video.js:2708
on @ video.js:2758
listen @ video.js:2710
on @ video.js:2758
HlsHandler @ video.js:60323
handleSource @ video.js:60798
_Tech.setSource @ video.js:12616
Html5 @ video.js:21793
loadTech_ @ video.js:24710
src_ @ video.js:26918
(anonymous) @ video.js:26865
setSourceHelper @ video.js:12979
(anonymous) @ video.js:12974
setSource @ video.js:59974
setSourceHelper @ video.js:12963
setSourceHelper @ video.js:12981
(anonymous) @ video.js:12722
bound @ video.js:2200
(anonymous) @ video.js:4540
setTimeout (async)
setTimeout @ video.js:4537
setSource @ video.js:12721
src @ video.js:26857
MediaLoader @ video.js:13200
addChild @ video.js:3637
handleAdd @ video.js:3757
initChildren @ video.js:3806
Player @ video.js:24088
videojs$1 @ video.js:29327
autoSetup @ video.js:2083
setTimeout (async)
autoSetupTimeout @ video.js:2114
(anonymous) @ video.js:29444
(anonymous) @ video.js:16
(anonymous) @ video.js:17
video.js:142 VIDEOJS: DEBUG: VHS: SegmentLoader[main] > playlist update [http://14.18.146.169:58801//live//139_hrs_live/14149/index.m3u8 => http://14.18.146.169:58801//live//139_hrs_live/14149/index.m3u8]
video.js:142 VIDEOJS: DEBUG: VHS: SyncController > syncPoint for [segmentIndex: 0] chosen with strategy [Segment]: [time:2, segmentIndex:0]
video.js:142 VIDEOJS: DEBUG: VHS: MPC > seekable updated [2 => 5.900000000001455]
video.js:142 VIDEOJS: DEBUG: VHS: SegmentLoader[main] > live window shift [1]

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Video.js 7.6.0
#### browsers
版本 75.0.3770.100（正式版本） （64 位）
#### OSes
window 10
### plugins
none

**Comment by wmlgl** [comment]
Oh, sorry. I accidentally put the contents of two files into the index.m3u8,  fixed it now.

**Comment by wmlgl** [comment]
I think this error is occurring when some not quite the same TS file, maybe the reason is a problem of key frames or non-key frames.

**Comment by gkatsev** [comment]
One thing that I noticed is that the first two segments don't start with iframes and the second segment doesn't contain an iframe at all. This definitely can cause issues with playback.
Additionally, I found that the stream contains b-frames, which we have an issue we're looking into right now and so once that's in, it may help with it.

**Comment by fuguiguan** [comment]
> Oh, sorry. I accidentally put the contents of two files into the index.m3u8, fixed it now.
大佬，请问你是怎么解决这个问题的呢

**Comment by wmlgl** [comment]
> > Oh, sorry. I accidentally put the contents of two files into the index.m3u8, fixed it now.
> > 大佬，请问你是怎么解决这个问题的呢

我建了个分支，做了一些修改，https://gitee.com/wmlgl/http-streaming
