### ISSUE TITLE
Encription key is downloading for each segment in HLS Stream playback 

### ISSUE THREAD

**Issue by durgeshksh1** [videojs/video.js#6106]
## Description
Hi,
I am working on a project in which encrypted HLS stream is played with Videojs. Everything is working fine but the encryption key keeps downloading for each segment which will increase the number of requests for the server. Other players usually download only once for each stream not for segments. 

## Steps to reproduce

1. Play any encrypted HLS stream.
2.
3.

### Expected
Key should download only once for each video.

### Actual
Key is getting downloaded for each segment of the video

### Error output
no error

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
All versions which I have tested
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by blacktrash** [comment]
Try setting [cacheEncryptionKeys](https://github.com/videojs/http-streaming/#cacheencryptionkeys) to `true`

**Comment by gkatsev** [comment]
Setting cacheEncriptionKeys works, but we still strongly recommend setting the appropriate cache control headers instead; for example `max-age: 500; private`. The private there tells intermediary caches not to cache and only the browser should cache.
