### ISSUE TITLE
video.js(V7.6.0) no support RTMP?

### ISSUE THREAD

**Issue by zqtlin** [videojs/video.js#6107]
video.js(V7.6.0) no support RTMP?

**Comment by mister-ben** [comment]
You need to add the Flash tech. You also need end users who have browsers that still support Flash and have it installed.

https://github.com/videojs/videojs-flash

**Comment by zqtlin** [comment]
import videojs from 'video.js'
import 'video.js/dist/video-js.css'
import 'videojs-flash'
import SWF_URL from 'videojs-swf/dist/video-js.swf'
videojs.options.flash.swf = SWF_URL 

I've done that, but I still can't used

**Comment by zqtlin** [comment]
import videojs from 'video.js'
import 'video.js/dist/video-js.css'
import 'videojs-flash'
import SWF_URL from 'videojs-swf/dist/video-js.swf'
videojs.options.flash.swf = SWF_URL 

I've done that, but I still can't used

**Comment by gkatsev** [comment]
I'm not sure what `import SWF_URL from 'videojs-swf/dist/video-js.swf'` does. Is the swf url being set properly? Try not setting it at all.
Also, as @mister-ben mentioned, browsers right now are having flash disabled by default so you need to make sure that you force the browser to allow it.

**Comment by zqtlin** [comment]
I only import these plugins:
import 'video.js/dist/video-js.css'
import videojs from 'video.js'
import 'videojs-flash'
and set up a browser to allow flash, but it report:
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)
VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.

**Comment by kiragame** [comment]
It works in my project.

import WVideo from "video.js";
import "video.js/dist/video-js.css";
require("videojs-flash");

......
WVideo(this.videoElem, dealProps(), () => {
    console.log("ready");
});
.....


function dealProps() {
   return {
  techOrder: [
    'flash',
  ],
  autoplay: true,
  muted: true,
  aspectRatio: '16:9',
  sources: [
    {
      src: 'rtmp://xxxx/live/xxxx',
      type: 'rtmp/flv',
    },
  ],
  width: 1200,   // required
   };
}

**Comment by zqtlin** [comment]
/***
"video.js": "^7.6.0"
"videojs-flash": "^2.2.0"
***/
// index.vue
<template>
  <div class="video-container">
    <video
      id="myVideo"
      class="video-js vjs-default-skin"
      style="width:100%;height:100%;object-fit: fill"
      poster="@/assets/imgs/vedio-bg.jpg">
      <source src="" type="rtmp/flv">
      <p class="vjs-no-js">不支持播放</p>
    </video>
  </div>
</template>
<script>
import videojs from 'video.js'
import 'video.js/dist/video-js.css'
import 'videojs-flash'
export default {
  name: 'VideoTmp',
  data () {
    return {
      options: {
        techOrder: ['flash'],
        autoplay: true,
        sources: [
          {
            src: 'rtmp://live.chosun.gscdn.com/live/tvchosun1.stream',
            type: 'rtmp/flv'
          }
        ]
      }
    }
  },
  mounted () {
    let elm = document.getElementById('myVideo')
    videojs(elm, this.options)
  }
}
</script>
<style lang="scss">
.video-container {
  width: 600px;
  height: 400px;
}
</style>

report error: 
VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

**Comment by zqtlin** [comment]
/***
"video.js": "^7.6.0"
"videojs-flash": "^2.2.0"
***/
![微信截图_20190725155855](https://user-images.githubusercontent.com/35000925/61856695-3d4a2280-aef5-11e9-92d7-60f15d1f9f72.png)

report error:
VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

**Comment by zqtlin** [comment]
/***
"video.js": "^7.6.0"
"videojs-flash": "^2.2.0"
***/
![微信截图_20190725155855](https://user-images.githubusercontent.com/35000925/61856904-a893f480-aef5-11e9-9d5b-eb47b1751884.png)
**report error:
VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.**
@mister-ben @gkatsev @kiragame

**Comment by gkatsev** [comment]
What browser are you running this with? Also, check out our FAQ about RTMP: https://docs.videojs.com/tutorial-faq.html#q%3A-how-can-i-play-rtmp-video-in-video.js%3F
You need to separate the connection url and stream name with an `&`.

**Comment by kiragame** [comment]
我使用的typescript；且@types没有videojs-flash，所以使用的require引入；不确定你那边引入是否有效。
chrome 75


发自我的iPhone

------------------ Original ------------------

**Comment by coder054** [comment]
I think It's awesome if we have an example folder, in which have a sub folder about rtmp

**Comment by shscy** [comment]
https://github.com/videojs/video-js-swf/issues/91
RTMP SecureToken authentication not support !! hate to drop video.js for my project !
