### ISSUE TITLE
currentTime() is not working in phones

### ISSUE THREAD

**Issue by avedisdeclabs** [videojs/video.js#6111]
I am trying to start the video in a specific momento on the video and in web is working properly but when I test it on the phone it's doesn't work in any moment.

You have any solution for it ?

**Comment by gkatsev** [comment]
We've had issues about this before on iOS. The general recommendation is to wait to call currentTime to seek until at least loadedmetadata is set. Also, you can take a look at [this code](https://github.com/brightcove/videojs-urlparams/blob/master/videojs.urlparams.js#L81-L124) for inspiration on how to make it more bulletproof.
We'd want to have video.js do it automatically, but we've been swamped with other issues and haven't had a chance to look into that yet.

**Comment by gkatsev** [comment]
(Also, I closed the issue as answered, but we're still around. If you have more questions, feel free to ask them here and we'll try to answer.)
