### ISSUE TITLE
Refresh Poster via Interval - fn.apply is not a function 

### ISSUE THREAD

**Issue by chbardel** [videojs/video.js#6112]
I am trying to refresh the poster from a livestream with the following code
`var player = videojs("NetatmoStream_8904");`
`player.setInterval(player.trigger('posterchanged'), 5000);`

It works, that the function is called every 5 seconds, but it gives me the error:
`Uncaught TypeError: fn.apply is not a function`

I also tried the following code:
`var player = videojs("NetatmoStream_8904");
player.setInterval(player.poster("http://BlablaMyURL.jpg"), 5000);`

This fails as well:
`Cannot read property 'guid' of undefined`
    `at bind (video.js:2194)`
    `at Player.setInterval (video.js:4602)`
    `at test.html:15`

How do I do this right?
PS: My Image URL to the Poster does not change, it should just be refreshed.

**Comment by chbardel** [comment]
I found a solution to realiably call the methods I want, but the poster is not refreshed. It seems, that if the URL is the same, it does not fetch the newest picture. Can I somehow force a poster refresh?

**Comment by cameronfarina** [comment]
Hi @chbardel,

This doesn't appear to be a bug. I spun up a local server and verified that this works as expected. I believe the issue here is one of context; the first argument to setInterval should be a function. In your example, you're passing the result of a function. So, if you change to the below you should get the desired result.

`player.setInterval(() => player.poster("http://BlablaMyURL.jpg"), 5000);`

Let me know if you're still having any issues.

**Comment by mister-ben** [comment]
As above, `setInterval()`'s first argument must be a function, but you also need to _change_ the poster URL to have it load again. Try adding a random query string.

**Comment by gkatsev** [comment]
Try something like:
```js
player.setInterval(() => player.poster("http://BlablaMyURL.jpg?" + Date.now()), 5000);
```

Closing as it's answered but if you still have questions, feel free to post them here.

**Comment by chbardel** [comment]
Danke für die Antworten, das war genau, was ich gesucht habe! Für jeden der nach mir ein ähnliches Problem hat:
Es funktioniert wirklich nur mit ganz normalen Funktionen die man sich selbst definiert hat. Methodenaufrufe und Ähnliches funktionieren nicht. Wenn ich mich richtig erinnere funktioniert es auch nicht die Funktion direkt im Aufruf zu deklarieren, sonst wäre ich auch schon früher auf die Lösung gekommen.

Danke auch für den Hinweis mit dem Cache-Breaker. Mit dem angehängten Date String ruft Chrome das neue Foto nun auch wirklich ab!
