### ISSUE TITLE
Audio over hls m3u8 with wowza not loading

### ISSUE THREAD

**Issue by thom44** [videojs/video.js#6117]
## Description
I'm new to video.js and possible missing something. 
We try to stream audio/mp3 files over wowza with hls. 
https://codepen.io/schuh/pen/zgvNpO
Videos working well with the same setup. 
https://codepen.io/schuh/pen/VovbLg

## Steps to reproduce
1. Setup player with <audio>-Tag and stream playlist.m3u8 with audios. @see https://codepen.io/schuh/pen/zgvNpO
2. Load page in a browser

### Expected
Audio should load and play

### Actual
Audio file not loaded. Browser crash. 
In the browser inspector > Networking tab, I can see the mp3 file request is sent, but the download stuck. If I call the url in the browser directly the mp3 is playing. In Wowza are no errors reported. 

#### videojs
7.6.0
#### browsers
We tested Ubuntu (Firefox, Chrom), Windows (Chrom), Android (Chrom)
#### OSes
Testet with Ubuntu, Windows, Android
### plugins
videojs-http-streaming

**Comment by mister-ben** [comment]
MP3 is not supported by http-streaming, AAC is. I don't think the browser used to crash when attempting to play MP3 before though.

**Comment by gkatsev** [comment]
Yes, unfortunately, we don't support mp3 audio in HLS/DASH currently. We would like to add it at some point but unfortunately, we don't have it scheduled at this time and probably won't get around to it in a long time as we have a lot of higher priority issues.
