### ISSUE TITLE
Is it possible to use two subtitles at the same time?

### ISSUE THREAD

**Issue by alexmo3** [videojs/video.js#6118]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Yes! That's available now thanks to https://github.com/videojs/video.js/pull/5817 (via c61f3d3e49d0d63bb92e2236b5ccb7ed973b90c3). It's available in Video.js 7.6.0. The only caveat is that our captions menu still only allow one subtitle at a time. To show multiple at a time requires using the API directly. See https://docs.videojs.com/tutorial-text-tracks.html#showing-tracks-programmatically for help.

**Comment by alexmo3** [comment]
Thanks @gkatsev
