### ISSUE TITLE
VideoJS HLS | video hangs after loading a small chunk

### ISSUE THREAD

**Issue by loveisalie92** [videojs/video.js#6122]
## Description
My video hangs after loading a very small size chunk(704 Bytes) when using HLS.
I have tested the playlist link with some online hls tester and it working, most of them use Jwplayer.
Is there any config that i can change to make it work?

## Steps to reproduce
This is the screenshot i got

![](https://lh3.googleusercontent.com/-_1IPHP97ngY/XTa_7kwxRyI/AAAAAAAAEu4/oUKZdK9SY5UyUc4XWv0reI37CrCg2nvegCLcBGAs/s0/videojs.png)

### Actual
The video hang after loading a small size chunk

### Error output
There is no error

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs 
7.4.1
#### browsers
Chrome
#### OSes
Linux
### plugins
No plugin

**Comment by gkatsev** [comment]
The screenshot isn't working. Also, hard to diagnose without sample content.
