### ISSUE TITLE
Wrong when playing audio: VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

### ISSUE THREAD

**Issue by YuFy1314** [videojs/video.js#6126]
## Description
In a div in the current page, there are both video playback and audio playback functions, only based on whether the acquired data is video or audio.
1. Just playing video is no problem. 
2. Is playing mp3 or ogg format audio can not play

## Steps to reproduce
I have tried two ways of writing that have not taken effect.
1.  Will read all files in all formats, whether audio or video, in the video tag
![image](https://user-images.githubusercontent.com/24446694/61710524-6b5c2500-ad84-11e9-9ee7-325b39cd6162.png)

2.Access the read files separately
![image](https://user-images.githubusercontent.com/24446694/61758104-02ad9080-adf6-11e9-9073-a7e6f0b72dec.png)

### Expected
Audio and video can play normally

### Actual
The above two writing results are the same, the audio file cannot be played, and an error is reported:
![image](https://user-images.githubusercontent.com/24446694/61757870-00970200-adf5-11e9-9abc-c47bc73d5d98.png)

![image](https://user-images.githubusercontent.com/24446694/61757866-fd9c1180-adf4-11e9-8e53-df6987c7f6bd.png)

only the video file can be played normally:
![image](https://user-images.githubusercontent.com/24446694/61757941-4227ad00-adf5-11e9-9933-bbd60254a08f.png)

### Error output
log.js:73 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.11.4
#### browsers
Chrome latest
#### OSes
windows10
### plugins
No plugin

**Comment by YuFy1314** [comment]
![image](https://user-images.githubusercontent.com/24446694/61760275-9cc50700-adfd-11e9-8a77-a6e7a20ce58a.png)
![image](https://user-images.githubusercontent.com/24446694/61760338-c2521080-adfd-11e9-8030-976be510ab8d.png)
This is the result of checking the elements on Google Chrome, Figure 1 is audio, Figure 2 is video

**Comment by mister-ben** [comment]
You must use the correct type, because Video.js asks the audio or video element whether it can play the source's type. `audio/mpeg` and `audio/ogg`.

**Comment by YuFy1314** [comment]
Thank you very much for your answer, perfect solution to my problem.
