### ISSUE TITLE
Unable to play m3u8 on IE 11

### ISSUE THREAD

**Issue by AccountGc** [videojs/video.js#6127]
![image](https://user-images.githubusercontent.com/46801445/61798405-d3316f00-ae5b-11e9-8ad7-62cf98355515.png)
![image](https://user-images.githubusercontent.com/46801445/61798434-e17f8b00-ae5b-11e9-8fdc-a0facef7de14.png)

Example：
```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		  <link rel="stylesheet" href="js/video-js.min.css" />
		  <script type="text/javascript" src="js/video.min.js" ></script>
		  <script type="text/javascript" src="js/videojs-flashls-source-handler.min.js" ></script>
		<script>
			var player = videojs('my-video', {
				flash: {
					swf: '/js/video-js.swf'
				}
			});
		</script>
	</head>
	<body>
		<video id='my-video' class='video-js' controls preload='auto' width='640' height='264' poster='MY_VIDEO_POSTER.jpg' data-setup='{}'>
			<source src='http://192.168.0.114/video/hls/lucene.mp4' type='video/mp4'>
		</video>
	</body>
</html>
```

@mister-ben 
Thank you

**Comment by AccountGc** [comment]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		  <link rel="stylesheet" href="js/video-js.min.css" />
		  <script type="text/javascript" src="js/video.min.js" ></script>
		  <script type="text/javascript" src="js/videojs-flashls-source-handler.min.js" ></script>
		<script>
			var player = videojs('my-video', {
				flash: {
					swf: '/js/video-js.swf'
				}
			});
		</script>
	</head>
	<body>
		<video id='my-video' class='video-js' controls preload='auto' width='640' height='264'
		  poster='MY_VIDEO_POSTER.jpg' data-setup='{}'>
		<source src='http://192.168.0.114/video/hls/lucene.mp4' type='video/mp4'>
  </video>
	</body>
</html>

**Comment by AccountGc** [comment]
<link rel="stylesheet" href="js/video-js.min.css" />
		  <script type="text/javascript" src="js/video.min.js" ></script>
		  <script type="text/javascript" src="js/videojs-flashls-source-handler.min.js" ></script>

**Comment by AccountGc** [comment]
var player = videojs('my-video', {
				flash: {
					swf: '/js/video-js.swf'
				}
			});

**Comment by AccountGc** [comment]
<video id='my-video' class='video-js' controls preload='auto' width='640' height='264'
		  poster='MY_VIDEO_POSTER.jpg' data-setup='{}'>
		<source src='http://192.168.0.114/video/hls/lucene.mp4' type='video/mp4'>
  </video>

**Comment by AccountGc** [comment]
<video id='my-video' class='video-js' controls preload='auto' width='640' height='264'
	  poster='MY_VIDEO_POSTER.jpg' data-setup='{}'>
	<source src="http://192.168.0.114/video/hls/lucene.m3u8" type="application/x-mpegURL"></source>
  </video>

**Comment by mister-ben** [comment]
1. You need to add the videojs-flash.min.js script from the [Flash tech](https://github.com/videojs/videojs-flash) script too, before videojs-flashls-source-handler.min.js
2. Your script to initialise the player won't work, because it's too early. The element with the id `my-player` has not been added to the document yet. Move it to the end of `body`.
3. Remove `data-setup='{}'` from the video element. This is for automatic setup, but you are trying to initialise it with `videojs('my-video', ...`. You should not have both.
4. Make sure the swf is the one from videojs-flashls-source-handler, not the one from videojs-flash

**Comment by AccountGc** [comment]
@mister-ben The problem has been solved，Thank you！ If I can, I am willing to give you some funding.
