### ISSUE TITLE
Cannot read property 'segments' of undefined

### ISSUE THREAD

**Issue by tryyou** [videojs/video.js#6133]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.准备一份m3u8文件.该m3u8文件的 .ts分片时长大于10秒钟,例如 .ts分片的时长为60秒
2.使用videojs进行播放
3.

### Expected
能否配置 .ts分片时长最大值
### Actual
Please describe what actually happened.
在播放音频转换的 .m3u8文件时,如果.ts文件分片时间过长会出现异常, .ts文件时长为10秒时正常播放.

### Error output
Uncaught TypeError: Cannot read property 'segments' of undefined

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.0
#### browsers
chrome 71.0.3578.98 （64 位)
#### OSes
windows 10 64位
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Can you provide a stream we can test with? Is this an audio-only playlist?
