### ISSUE TITLE
I need help! ! Thank you!

### ISSUE THREAD

**Issue by AccountGc** [videojs/video.js#6134]
1.The videojs plugin cannot play ts files converted by the ffmpeg tool.

2.This is my conversion command
   ffmpeg -i oceans.mp4 -hls_time 10 -hls_list_size 0 -hls_segment_filename ./hls/oceans%05d.ts ./hls/oceans.m3u8

3.This is the m3u8 file content I generated using ffmpeg
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:11.387133,
oceans00000.ts
#EXTINF:11.011733,
oceans00001.ts
#EXTINF:9.051311,
oceans00002.ts
#EXTINF:8.592489,
oceans00003.ts
#EXTINF:6.506933,
oceans00004.ts
#EXT-X-ENDLIST

4.This m3u8 file can be played, is my ffmpeg used incorrectly?
https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

5.The error is as follows:
![image](https://user-images.githubusercontent.com/46801445/61953616-6cda5700-afe9-11e9-8cbd-22f04eaeca99.png)

![image](https://user-images.githubusercontent.com/46801445/61953739-c8a4e000-afe9-11e9-81ae-c2ed4dcf0966.png)

Thank you!
@mister-ben

**Comment by gkatsev** [comment]
Can you provide the test stream? Unfortunately, it's impossible for us to help with such a generic issue without more information.
Try reading the troubleshooting guides we have: https://github.com/videojs/http-streaming/blob/master/docs/troubleshooting.md and https://docs.videojs.com/tutorial-troubleshooting.html

**Comment by mister-ben** [comment]
One of the error messages mentions the `access-control-allow-origin` header, so you probably just don't have CORS configured on the server hosting the HLS.

See https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS and https://enable-cors.org/server.html.

**Comment by AccountGc** [comment]
@gkatsev @mister-ben Thanked everyone! !
