### ISSUE TITLE
Moodle Videojs plugin preload option is always reset to auto

### ISSUE THREAD

**Issue by doctsh** [videojs/video.js#6135]
## Description

I am using videojs plugin in my Moodle site. I have multiple videos on course page. Therefore dont want all videos to get preloaded.

I am trying to configure  'preload' => 'none'. Therefore I tried to change auto to none in the file media/player/videojs/classes/plugin.php:

#190    $attributes += ['preload' => 'none', 'controls' => 'true', 'title' => $title];

## Steps to reproduce
go to the file reset to none, after some time it becomes auto
3.

### Expected
I want the preload property to remain as none

### Actual
It is set to none but after sometime returns to auto. I dont know when and why but after a week or so

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

**Comment by mister-ben** [comment]
It sounds like your modified PHP file is being overwritten. Maybe Moodle automatically updates itself. I recommend you ask Moodle about that
