### ISSUE TITLE
how Download Button

### ISSUE THREAD

**Issue by myzf** [videojs/video.js#6136]
I want to display the download button through video. Then I click Save to save the video to IOS phone or Android phone. How do I set it up?

**Comment by kiragame** [comment]
是新增按钮吗？可以参考https://docs.videojs.com/tutorial-components.html

**Comment by myzf** [comment]
> 是新增按钮吗？可以参考https://docs.videojs.com/tutorial-components.html

不是的呢，我想在播放视频那里，显示video.js的下载按钮，然后点击下载后可以把视频保存到手机里面的

**Comment by myzf** [comment]
>  Thanks for opening your first issue here! 
> 
> If you're reporting a  bug, please make sure you include steps to reproduce it. We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.
> To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/videojs/video.js/blob/master/CONTRIBUTING.md).
I mean: when playing the video, the download button is displayed below. After clicking the download button, you can save the video directly to your mobile phone. I don't know if video. JS supports this function

**Comment by gkatsev** [comment]
There is a sample document against the brightcove player that you can look at https://support.brightcove.com/brightcove-player-sample-download-video-plugin but be aware that this likely doesn't work on iOS due to platform specific restrictions.
