### ISSUE TITLE
textTrack fontPercent 100% and edgeStyle "none" not working

### ISSUE THREAD

**Issue by kbunch** [videojs/video.js#6143]
## Description
If you set the text track styling using the textTrackSettings.setValues call similar to
https://github.com/videojs/video.js/issues/4852
Everything will work while viewing the video except for fontPercent 1.00 (100%) and edgeStyle (none).

If you restart the video these settings will apply, but not at runtime.

The code has a conditional in parseOptionValue which prevents the edgeStyle from comparing correctly to the option value
value !== 'none'

In the same way, the fontPercent has a custom parser
parser: (v) => v === '1.00' ? null : Number(v)

This returns null for the value and when it runs through the parseOptionValue call it doesn't return a value since it has a conditional that the value must be defined. This prevents a positive match against the option.

I'm assuming there are reasons for these conditionals but they prevent updating the settings in real time.

**Comment by kbunch** [comment]
Noting the above, we are facing this issue as we wrote a custom captions menu/dialog that is suited for TV with key controls. Thus we need to set the caption settings from code for this.

**Comment by gkatsev** [comment]
This likely because we don't really have a real API for setting these values. The multiplicative sizing doesn't seem to be an issue via the dialog. Might be a side-effect of using the setValues method.
I believe the workaround would be to call `textTrackSettings.updateDisplay()` after calling `setValues()`.

**Comment by kbunch** [comment]
@gkatsev  That has no effect. What worked was calling setDefaults() prior to calling setValues. This would resolve it as it wouldn't work as overrides.
