### ISSUE TITLE
Issue or Config Problem?

### ISSUE THREAD

**Issue by rayj00** [videojs/video.js#6152]
## Description
Showing a live streaming video, there are vertical  black bars on both sides of the video.

I changes the width and height of the div tag and also have width=640 height=360 in the video tag.

Here is what the video looks like:
![image](https://user-images.githubusercontent.com/6609523/62251863-1b521380-b3bf-11e9-806d-f4bcbb08314c.png)

what version of videojs does this occur with? 7.6.0
#### browsers
what browser are affected? Chrome and FF
#### OSes
what platforms (operating systems and devices) are affected? Win 7
### plugins
are any videojs plugins being used on the page? If so, please list them below.
None.

**Comment by sampathkumar7** [comment]
set aspectratio to 16:9 or change in css 
.video-js .vjs-tech {
    object-fit: fill;
}

**Comment by rayj00** [comment]
> set aspectratio to 16:9 or change in css
> .video-js .vjs-tech {
> object-fit: fill;
> }

I tried this but it did not work.   Nothing changed.
