### ISSUE TITLE
Playback doesn't start for low FPS HLS videos

### ISSUE THREAD

**Issue by gjanblaszczyk** [videojs/video.js#6163]
## Description
Playback doesn't start for low FPS HLS videos on Firefox browser.
This is probably a problem in `httpstreaming` plugin.

I created a reduced test case demo here: https://codepen.io/grbla/pen/jgZJJM

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open the demo page on Firefox browser.
2. Click on the player to start playback.

### Expected
To see the video instead of loading spinner.

### Actual
Loading spinner shows and stays forever.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
latest 7.6.0
#### browsers
Firefox only.
#### OSes
All
### plugins
none

**Comment by gkatsev** [comment]
You're in luck, we have a fix for this that we're going to be testing soon https://github.com/videojs/http-streaming/pull/624 (also, we're going to back port it to the 1.x branch on VHS).
If you can take that branch for a spin, that would be useful.

**Comment by gjanblaszczyk** [comment]
Thanks, I will keep an eye on it. If the PR passes the review then I will do a test for it.

**Comment by gkatsev** [comment]
We have two fixes in VHS that are likely related: https://github.com/videojs/http-streaming/pull/666 and https://github.com/videojs/http-streaming/pull/616.
videojs/http-streaming#616 is already in VHS, but videojs/http-streaming#666 is merged but not yet released.

**Comment by gjanblaszczyk** [comment]
Thanks for the info, I have just tested http-streaming v1.11.1 (This version should contains these two PR's) but unfortunatly I can still reproduce the issue. However, It works fine on the following PR https://github.com/videojs/http-streaming/pull/624

**Comment by gkatsev** [comment]
Ah, yeah, that PR has a much better inherent fix. Unfortunately, it'll be a bit before the changes in master and that PR is ready for prime time.
