### ISSUE TITLE
Is there any option to select language from drop down for captions?

### ISSUE THREAD

**Issue by SayantaniS** [videojs/video.js#6169]
## Description
Briefly describe the issue.
Is there any option to select language from drop down for captions?

## Steps to reproduce
NA

### Expected
There should be a drop down from where user can select the caption's language

### Actual
NA

### Error output
NA
#### videojs
7.6.1
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by mister-ben** [comment]
You will get a menu button when you add caption/subtitle tracks - see https://videojs.com/advanced/#elephantsdream
