### ISSUE TITLE
Restarting Playing a video with tap on a resolution button.

### ISSUE THREAD

**Issue by zapliv** [videojs/video.js#6170]
## Description

if you click on switching the video quality on the iPad, the video restarting playing.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.play video for Ipad
2.Tap for resolution button.

### Expected
Continued Play

#### videojs
7.5.5

#### browsers
safari mobile

#### OSes
Ios

### plugins
videojs-resolution-switcher

**Comment by gkatsev** [comment]
This sounds like an issue with the resolution switcher plugin. I would open this issue against the plugin.
