### ISSUE TITLE
playbackRates is inconsistently showing up

### ISSUE THREAD

**Issue by atebit** [videojs/video.js#6172]
## Description
I'm not sure why, but this setting seems to not work 90% of the time, and once in a while it just magically does...

`
var player = videojs('#urm-vjs', {
  controls: true,
  autoplay: false,
  preload: true,
  loop: false,
  playbackRates: [0.5, 1, 1.5, 2]
}
`

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. refresh the page

### Expected
playbackRates controlBar ui element should show up

### Actual
playbackRates controlBar ui element doesn't show up

### Error output
nope..

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs 
7.6.0
#### browsers
Chrome 76
#### OSes
macos mojave
### plugins
silvermine-videojs-quality-selector.min.js
videojs.hotkeys.min.js

**Comment by mister-ben** [comment]
If I were to guess, I'd suspect you have the `data-setup` attribute on your player element, and sometimes your player is being set up automatically because of the attibute with the options defined there, and sometimes by your setup line above with the options there. That could vary just by the timing of when scripts download.

We ask for a reduced test case for issues because then we can respond to the specific circumstances, rather than inefficient guesswork.

**Comment by atebit** [comment]
Sorry, here's more context:

`

				<link href="https://vjs.zencdn.net/7.6.0/video-js.css" rel="stylesheet">
				<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
				<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
				<script src='https://vjs.zencdn.net/7.6.0/video.js'></script>
				<script src="//cdn.sc.gl/videojs-hotkeys/0.2/videojs.hotkeys.min.js"></script>
				<script src="https://unpkg.com/silvermine-videojs-quality-selector/dist/js/silvermine-videojs-quality-selector.min.js"></script>


				<div class='urm-video-player'>
					<video id='urm-vjs' class='video-js vjs-default-skin vjs-16-9 vjs-big-play-centered vjs-playback-rate' oncontextmenu="return false;" controls controlsList="nodownload" preload='auto' width='640' height='264' poster='<?php echo $vimeo_image_url; ?>' data-setup='{"fluid": true}' autoplay>
				    <source src='<?php echo $vimeo_video_url; ?>' type='video/mp4'>
				    <p class='vjs-no-js'>
				      To view this video please enable JavaScript, and consider upgrading to a web browser that
				      <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
				    </p>
				  </video>
				</div>


`

**Comment by atebit** [comment]
So, I should remove the data-setup?

**Comment by atebit** [comment]
Actually, I added the playbackRates array to the data-setup and it works consistently now.. I think this is fine to close out. It's odd that even if I call the `videojs` setup function after `$(window).ready` it seems to not do what I think it should. Maybe just need more time trying to understand the init process

**Comment by mister-ben** [comment]
So yes, you can use `data-setup` or `videojs()` to init the player, but don't use both. Both init the player, but calling `videojs()` on an already intialised player does not uplate its options.

**Comment by atebit** [comment]
Makes sense. Will do a little refactoring. However, calling videojs and then using the "ready" callback, is still fine it looks like?

**Comment by brandonocasey** [comment]
Yeah the ready option will always work no matter where the player was initialized, as it will always run when the player, or right away if the player is already ready.
