### ISSUE TITLE
Subtitles not showing

### ISSUE THREAD

**Issue by NPankaj** [videojs/video.js#6178]
## Description
WebVTT subtitles are not showing in the HLS video.

Same issue is happening with both HLSv3 and HLSv4 videos. In case of HLSv4, the first vtt segment loads successfully, for all the subsequent segments, getting a parsing error 'VIDEOJS: WARN: Error encountered when parsing cues: Malformed WebVTT signature'. The vtt parser is expecting WebVTT header in all the segments.

Not sure whether this is an issue or something i am missing, but have tested the video in other video players and the subtitles are coming fine.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. HLSv3 playlist for the video : 
https://dbq3da34mdptq.cloudfront.net/HLS/migration/output-test-video-2.m3u8

2. HLSv4 playlist for the video:
https://dbq3da34mdptq.cloudfront.net/HLS/migration/output-test-video-1.m3u8

### Expected
Expected subtitles to be shown

### Actual
Subtitles are not shown after the caption is selected.

### Error output
Have mentioned above.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.0
#### browsers
Chrome
#### OSes
MacOS

**Comment by mister-ben** [comment]
The second and subsequent segments dont have a WEBVTT header.

https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-04#section-3.5

> Each WebVTT Segment MUST either start with a WebVTT header or have an EXT-X-MAP tag applied to it.

**Comment by NPankaj** [comment]
@mister-ben this explains HLSv4 playlist issue.

For HLSv3 playlist, have asked the same question on slack channel, it seems the reason is the space before **LOCAL** in the vtt file

X-TIMESTAMP-MAP=MPEGTS:0, **LOCAL**:00:00:00.000

Can this be handled in videojs?

We are using aws elastic transcoder for generating HLS playlists and the subtitles are also encrypted.
