### ISSUE TITLE
duration() not working in Safari

### ISSUE THREAD

**Issue by clarke32** [videojs/video.js#6179]
## Description
The duration method returns NaN when the video hasn't started in Safari, therefore the duration display is not being shown.

### Expected
I can see the duration display when the video hasn't started.

### Actual
I can not see the video's duration in the player, when the video hasn't started.

#### videojs
7.6.1
#### browsers
Safari

**Comment by gkatsev** [comment]
If the video metadata hasn't loaded yet, we are supposed to be returning `NaN` according to the HTML spec.
