### ISSUE TITLE
No compatible source was found for this media

### ISSUE THREAD

**Issue by Parad1seF0x** [videojs/video.js#6180]
## Description
More than sure that the problem is not in the Video.JS but do not know where to turn... As far as I understand it is somehow connected with the browser cache, I was looking for methods to combat my problem, but apparently this is an isolated case. I apologize for the poorly formatted issue

## Steps to reproduce
1. Go to https://tripletcam.com/video/nasa-live-official-stream-of-nasa-tv/page/1?
2. Start embed live
3. refresh page

### Expected
Live is loading without problems

### Actual
I have error 
```
MediaError
code: 4
message: "No compatible source was found for this media."
```

### Error output
https://pastebin.com/n44zEwss

#### videojs
Video.js 7.4.1
#### browsers
All
#### OSes
All
### plugins
rtmp

**Comment by Parad1seF0x** [comment]
if you refresh the page with the cache reset(ctrl+f5), then there is no problem, but the next normal update again this problem.

**Comment by mister-ben** [comment]
There's a paywall at that URL. A reduced test case would help you isolate the problem and present it to others to take a look.
