### ISSUE TITLE
How to disable a button ??

### ISSUE THREAD

**Issue by wenganxiang** [videojs/video.js#6181]
How to disable a button? I try to add an 'disabled' attribute to any button(full screen button, for example) on control bar, it does not work. On the contrary,  it will cause the button not work normally, even I set 'disabled=false'. I use videojs 7

**Comment by mister-ben** [comment]
Call the disable method on the button, e.g. `player.controlBar.fullscreenToggle.disable()`

**Comment by wenganxiang** [comment]
> Call the disable method on the button, e.g. `player.controlBar.fullscreenToggle.disable()`

Thank you so much mister-ben, it works.
