### ISSUE TITLE
How to set id for a button?

### ISSUE THREAD

**Issue by wenganxiang** [videojs/video.js#6187]
How to set an id for a button? For example, how to set id for fullscreen toggle? Should I set it in 'fullscreen-toggle.js'?  It's easy to set an id for a class extends Component, you just need add a 'id' attribute in 'createEl()'. But I don't know how to set an id for a class extends Button? Anyone can help??

**Comment by bc-paul** [comment]
You can pass an 'id' attribute in createEl() when extending a Button just the same as Component.

[createEl(tagopt, propsopt, attributesopt)](https://docs.videojs.com/button#createEl)

Another option could be to set it in the options of the Component.

```js
var VjsButton = videojs.getComponent('Button');
var MyNewButton = videojs.extend(VjsButton, {
  constructor: function() {
    options.id = 'my-button-id';
    VjsButton.call(this, player, options);
  },
  otherFunc: function() {
    // do something
  }
});
videojs.registerComponent('MyNewButton', MyNewButton);
var player = videojs('myvideo');
player.getChild('controlBar').addChild('myNewButton', {});
```
