### ISSUE TITLE
CustomEvent support for plugins

### ISSUE THREAD

**Issue by jackpope** [videojs/video.js#6203]
## Description

I have a [Videojs plugin](https://github.com/contently/videojs-annotation-comments) that heavily relies on `CustomEvent`s to communicate with other JS on the page. I use `CustomEvent` because I can send and receive `detail` data which makes for a flexible API. Here is where the event is created and triggered: https://github.com/contently/videojs-annotation-comments/blob/master/src/js/lib/event_dispatcher.js#L106

I am now upgrading Videojs from v6 to v7 and am running into the following error when triggering these events. `
VIDEOJS: ERROR: TypeError: "setting getter-only property "target""`

I believe this is due to the change made here https://github.com/videojs/video.js/pull/4993/files#diff-e0dad58af20bbb65a9cf3690f5ae31e0R417

### Question

Is there a way to send `CustomEvent`s through the plugin trigger system? Or, is there a better way to do event based communication with attached data between the plugin/videojs/external scripts?

#### videojs
v7.6.0, after upgrading from v6
#### browsers
Currently using Firefox, also experienced on Chrome
#### OSes
Currently on PopOS, also experienced on MacOS
### plugins

The error is coming from my own plugin: https://github.com/contently/videojs-annotation-comments No other plugins are being used.

**Comment by gkatsev** [comment]
Yeah, we probably should be able to support this. Unfortunately, I'm not sure when we'll be able to get to it.

**Comment by jackpope** [comment]
In case anyone else runs into this, I got around it by attaching a light weight event bus to my API and piping all of the interactions through that.

 https://github.com/contently/videojs-annotation-comments/pull/49/files#diff-e13eebc3c482253da86bbdc418e5de46R69
