### ISSUE TITLE
iOS 12.4.1 incompatibility?

### ISSUE THREAD

**Issue by anibarro** [videojs/video.js#6211]
Hi, I have a muted video playing that worked in iOS until 12.3.1, but it doesn't work in iOS 12.4.1.
Is there any breaking changes in this version or something that I'm doing wrong?

Please check [this demo](https://codepen.io/anibarro-the-sasster/pen/wvwrBwL?editors=1000) in iOS 12.4.1 and then on earlier versions.

**Comment by gkatsev** [comment]
Playback works for me on iOS 12.4.1 via your demo. What exactly are the symptoms you are seeing?

**Comment by anibarro** [comment]
> Playback works for me on iOS 12.4.1 via your demo. What exactly are the symptoms you are seeing?

I got complaints from other people and for me the video is not starting in an iPhone SE running on iOS 12.4.1, I just see the image set as poster. It does work in an iPhone 5s running iOS 12.3.1.
Which device are you testing in? Is the [video in this page](https://www.medel.com/hearing-solutions/accessories/remote-controls/audiokey#my-player) also playing for you when it gets into the view? 

Thank you!

**Comment by gkatsev** [comment]
Yup, I can see the video play back on that page as well.

I'm testing on an ipad mini as it's the only iOS 12.4.1 device available to me.

**Comment by anibarro** [comment]
Ummm... it might be a device-related issue, I'll check tomorrow in other devices and post my results.
Thanks a lot for testing!

**Comment by gjanblaszczyk** [comment]
I have tested your website on my iPhone 7 on IOS 12.4.0 and It works fine. However, please note that iPhone will not autoplay videos when it is in "Low power mode".

**Comment by anibarro** [comment]
> I have tested your website on my iPhone 7 on IOS 12.4.0 and It works fine. However, please note that **iPhone will not autoplay videos when it is in "Low power mode"**.

Oh God...!! I was getting crazy because it looked totally random, but it that's exactly the issue!!
Thanks a lot for pointing that out, and sorry for the stupid mistake... :$

**Comment by gjanblaszczyk** [comment]
np and I guess you should consider adding some big play button control over the player if the autoplay policy blocks video playback...

**Comment by anibarro** [comment]
The poster image didn't look good, but you are right, after fixing that the next thing would be adding a button :)

**Comment by simeyla** [comment]
Regarding LOW POWER MODE
(in caps because I always forget this one).

Here's my tentative solution:
 
    const player = videojs(element, 
                   { 
                      autoplay: true,
                      controls: true, 
                      sources: ....
                   });

     // hide big play button (it's kinda ugly - sorry but it is)
     const bigPlayButton = player.bigPlayButton;
     bigPlayButton.hide();
 
     // if autoplay doesn't start then we show it
     setTimeout(() => bpp.show(), 1500);

This will hide the big play button and show it if playback doesn't start within 1.5 seconds. May need fine tuning based on preference. And in case you're wondering the play button won't suddenly appear because of the CSS (the hide() sets the class `.vjs-hidden` which hides the button and in addition once playback has started the `.vjs-has-started` class permanently hides it anyway).

Would welcome a built in better approach if there is one. This seems to work fine for me.
