### ISSUE TITLE
global/window and global/document  ?

### ISSUE THREAD

**Issue by ToMissYou** [videojs/video.js#6212]
Loading videoJS with reqyure.js
There will be two unrelated JS loads.

![Image of Yaktocat](http://ftps.zj14.cn//image/POI/011B.png)
![Image of Yaktocat](http://ftps.zj14.cn//image/POI/011A.png)

Edition：7.3.0

**Comment by misteroneill** [comment]
These are dependencies of Video.js as you can see [in the package.json](https://github.com/videojs/video.js/blob/master/package.json#L85), but they should be installed when you install Video.js via npm.

You may need to tell RequireJS where to find those modules.

**Comment by gkatsev** [comment]
You could also configure requirejs to return `window` or `document` globals for the `global/window` and `global/document` requests.

**Comment by mafar** [comment]
to fix this, please read my answer #5680 (comment)

I think **Documentation** should be **updated !!!**
