### ISSUE TITLE
Player loses height on IE11 after exiting Fullscreen mode

### ISSUE THREAD

**Issue by leandronsp** [videojs/video.js#6214]
## Description
My player has a height of `400px` but after *exiting* the fullscreen mode on IE11, the height is smaller and goes to approximately`~100px`. 

_Please don't take in consideration the message on the player. It's there to protect the source. The problem is at the height only_

Before fullscreen:
![Screenshot 2019-09-05 at 14 23 08](https://user-images.githubusercontent.com/385640/64346194-98d5f880-cfe9-11e9-9967-0a1012182165.png)

After fullscreen (pressing ESC to exit):
![Screenshot 2019-09-05 at 14 23 30](https://user-images.githubusercontent.com/385640/64346208-9d9aac80-cfe9-11e9-8f1a-b90f669d9771.png)

## Steps to reproduce

1. Enter the fullscreen mode
2. Exit the fullscreen mode

### Expected
The player height should be intact. 

### Actual
The player height decreases.

### Error output
No errors on the JS console so far.

#### Environment
* video.js 7.4.1
* IE11
* Windows (tested using 8 and 10)

Any help appreciated. 

Thanks,
Leandro

**Comment by mister-ben** [comment]
Can you produce a reproducible test case, e.g. with the [starter template](https://codepen.io/gkatsev/details/GwZegv)?
