### ISSUE TITLE
I need help Thank you! !

### ISSUE THREAD

**Issue by AccountGc** [videojs/video.js#6215]
## Description
Played using the intranet player, the playback environment cannot access the internet.

Using IE browser to play hls error is as follows.

![image](https://user-images.githubusercontent.com/46801445/64350014-87611080-d02a-11e9-9837-52e203150e35.png)

![image](https://user-images.githubusercontent.com/46801445/64350045-93e56900-d02a-11e9-8ff3-fbfddeb067ba.png)

@mister-ben

**Comment by NatalieStrong** [comment]
I faced something when I tried to embed this https://youtu.be/3IJYHdq36io over my blog

**Comment by gkatsev** [comment]
Unfortunately, there isn't really enough here to help out. Can you provide more information on what's the setup? Which verison IE? Which OS? What version of Video.js and which version of flash and the flashls source handler? When is the error happening? Does another video work in the same player?
