### ISSUE TITLE
Add buttons to the controlBar after initialization

### ISSUE THREAD

**Issue by gauravrele87** [videojs/video.js#6218]
I am fairly new to videojs and javascript as a whole so i dont really understand whats going on but here is my problem that i've been trying to solve

I have a articulate Rise exported file that includes videojs videos which are instantiated when you run the index.html file. The video screenshot is below
![image](https://user-images.githubusercontent.com/13090752/64468639-fcd8e980-d0db-11e9-96ec-71aeb3e715a3.png)

The videojs video is instantiated with the controlBar that you can see in the image. I want to add a subtitles menu button and a playbackratemenubutton to this. The main problem is that i dont have access to the original scripts to make this happen so i have to rely on doing something after the page loads. is this even possible?

I tried to use the following but it didnt work. Another question was, when you use dispose(), you lose the actual div that video player was created in. How can you reinitialize the video player in the same div as before? is this possible? Hope that makes sense
```
var v = video("id") 
v.dispose()
player = videojs('#id??', {techOrder: ["html5", "flash"],
  autoplay: false,
  sources: [{
      type: "video/mp4",
      src: "asset source file"
    }],"playbackRates":[1,1.5,2,2.5,3], controlBar: {
        children: [
            "playToggle",
            "volumeMenuButton",
            "durationDisplay",
            "timeDivider",
            "currentTimeDisplay",
            "progressControl",
            "remainingTimeDisplay",
            "fullscreenToggle",
            "playbackRateMenuButton"
        ]
    }
```

**Comment by mister-ben** [comment]
player.controlBar.addChild('SubsCapsButton');
    player.controlBar.addChild('PlaybackRateMenuButton');
