### ISSUE TITLE
videojs playbackRates doesnot work in mobile

### ISSUE THREAD

**Issue by lt978613** [videojs/video.js#6221]
In my project I use videojs play video  formate of m3u8, the setting of playbackRates is not work in mobile ,but it works on PC chrome.

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Video.js Sandbox</title>
  <link href="video-js.css" rel="stylesheet" type="text/css">
  <script src="video.js"></script>
  <style>
    .video-js{
      width:100%;
    }
  </style>
</head>
<body>

<video
  id="vid1"
  class="vjs-playback-rate video-js"
  controls
  preload="auto">
  <source src="https://cdn.letv-cdn.com/2018/12/05/JOCeEEUuoteFrjCg/playlist.m3u8"
          type="application/x-mpegURL">
  <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a
    href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video>
<button id="btn">alt video playbackRates</button>
<script>
  var vid = document.getElementById('vid1');
  var btn = document.getElementById('btn');
  var player = videojs(vid, {
    controls: true,
    playbackRates: [0.5, 1.0, 1.5, 2.0,10]
  },function(){
    /*this.currentTime(300)*/
  });
  player.on('loadeddata',function () {
    this.currentTime(300);
  })

  btn.addEventListener('click',function(){
      document.getElementById('vid1_html5_api').playbackRate=4
  })

</script>

</body>
</html>
```
I try operate video playbackRate directly, it does not  work on mobile ,but  it wokrs on PC chrome.
The currentTime is the same.

videojs version 7.6.4

**Comment by mister-ben** [comment]
Android Chrome's native HLS does not support playback rates, but MSE does.

You can add `html5: { hls: { overrideNative: !videojs.browser.IS_SAFARI } }` to use MSE, but you should also remove the source from the video element, as if the source is already loaded when the player is initialised it won't be reloaded. You can load the source in the ready callback.

**Comment by lt978613** [comment]
In my project I use videojs play video  formate of m3u8, the setting of playbackRates is not work in mobile ,but it works on PC chrome.

**Comment by lt978613** [comment]
Thanks very much @mister-ben that works for me
