### ISSUE TITLE
Unable play/pause and mute/unmute the video in mobile view 

### ISSUE THREAD

**Issue by gouravmore** [videojs/video.js#6222]
## Description
When I'm trying to play any video in mobile view using videoJs-7.6.0 lib, I'm unable to play/pause and mute/unmute the video in mobile view but I'm able to click and access only progress bar and fullscreen button.
**note**:- If I long-press the play/pause OR mute/unmute button then it is working correctly 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Integrate videoJs-7.6.0 lib into your project
2. Play MP4 video
3. Open this MP4 video in mobile view

## Results
Unable to play/pause and mute/unmute the video in mobile view
### Expected
User should be able to click and access the play/pause and mute/unmute button

### Actual
PFA youtube video for your reference
https://youtu.be/pnAxeeC47BE

### Error output
No Error

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
videoJs-7.6.0
#### browsers
All mobile browsers
#### OSes
Android Mobile
### plugins
- vjsdownload
- videojs-contrib-quality-levels
- videojs-hls-quality-selector
- videojs-contrib-hls

**Comment by mister-ben** [comment]
I can't replicate. Can you produce a reproducible test case, e.g. with the [starter template](https://codepen.io/gkatsev/details/GwZegv)?

**Comment by gouravmore** [comment]
@mister-ben Thanks for the reply. We are facing this problem when we integrate this lib with ionic. You can reproduce this by adding this following line.

`<script src="http://code.ionicframework.com/1.3.3/js/ionic.bundle.min.js"></script>`
**steps to reproduce:-**
- Add this above(library) line in your index.html.
- Open it in mobile view
- Try to pause/play a video

PFA youtube video for your reference:- https://youtu.be/gXC1ROF8BDM

Codepen link:- https://codepen.io/gouravmore/pen/JjPvYdZ
**Note:-** To reproduce this issue - open this in mobile view

**Comment by gkatsev** [comment]
ionic framework has a fastclick-like feature. There is a way to disable it I believe but it conflicts with Video.js touch support.
