### ISSUE TITLE
UI when playing Icecast streams

### ISSUE THREAD

**Issue by carloscarnero** [videojs/video.js#6224]
## Description
I'm currently (ab)using Video.js for playing MP3 Icecast streams (live audio). It works very well in every device I've tested, except for the user interface which displays the progress bar.

Is there a way to force or tell Video.js that this particular case is a live stream and should display the live control and hide the progress bar? (I've tried, unsuccesfully, using the `vjs-live` class.) Note that a reduced test case is [available here with real world source](https://codepen.io/carloscarnero/pen/mdbxzLa?editors=1000).

**Comment by mister-ben** [comment]
_Most_ of the time this shows the live display and no progress control for me, as the video element is reporting its duration as `Infinity`. When it doesn't, the video element has a finite duration.

You could remove the progress control from the player with `{ "controlBar": { "progressControl": false} }`, and use CSS to make the live display always visible, but using [middleware](https://docs.videojs.com/tutorial-middleware.html) you can make the duration always report as infinite:

```
videojs.use('audio/mpeg', function(player) {
  return {
    duration: function() {
      return Infinity;
    }
  }
});
```

[Example](https://codepen.io/mister-ben/pen/WNezLvM?editors=1000)

**Comment by carloscarnero** [comment]
The solution using the middleware is the one that nicely works for me. Thank you!
