### ISSUE TITLE
Custom element (tag) for <audio> is not working

### ISSUE THREAD

**Issue by Wolfcast** [videojs/video.js#6225]
## Description
On your [doc page](https://docs.videojs.com/tutorial-setup.html) you state:

> Note: Video.js works with `<video>` and `<audio>` elements, but for simplicity we'll refer only to `<video>` elements going forward.

and later: 

> You can use a `<video-js>` element instead of `<video>`. Using a `<video>` element is undesirable in some circumstances, as the browser may show unstyled controls or try to load a source in the moments before the player initialises, which does not happen with the `<video-js>` custom element.

But if I use an `<audio-js>` tag, the library does not process the tag at all.

## Steps to reproduce
Sample that do not work:
```
<audio-js class="video-js" width="300" height="150" preload="none" controls="controls"  data-setup='{}'>
    <source type="audio/mpeg" src="audio-sample.mp3">
    <p>Your Web browser does not support audio playback!</p>
</audio-js>
```

But this work:
```
<audio class="video-js" width="300" height="150" preload="none" controls="controls"  data-setup='{}'>
    <source type="audio/mpeg" src="audio-sample.mp3">
    <p>Your Web browser does not support audio playback!</p>
</audio>
```

### Expected
I expect `<audio-js>` elements to be processed as they were `<audio>`.

### Actual
`<audio-js>` elements are not processed and the alternative content is displayed.

### Error output
None

## Additional Information
I'm using the latest version (7.6.5) and I get the same result for all OS/browsers.

**Comment by OwenEdwards** [comment]
There is no mention of an `<audio-js>` element in the documentation, because no such element is supported. `<video-js>` is a custom HTML element of the `video.js` framework.

In general, a <video> element is able to play audio-only media. You should be able to use a `<video-js>` element (with an audio-only source or set of sources) wherever you would otherwise use an `<audio>` element. Did you try that?
