### ISSUE TITLE
Does VideoJS meet the WCAG 2.0 Level AA standard?

### ISSUE THREAD

**Issue by katlamen** [videojs/video.js#6228]
Hi All, 

Just a simple question, does the current version of VideoJS meet the WCAG 2.0 Level AA standard?

Besides, I know that the latest version is WCAG 2.1, may I ask if it is also met in the current version of VideoJS? If not, any timeline to enhance in order to meet this requirement?

Thank you.

**Comment by gjanblaszczyk** [comment]
Yes, It should. You can read more about it here: https://github.com/videojs/video.js/issues/5732

**Comment by OwenEdwards** [comment]
See the [wiki article "Accessibility (a11y) is video.js accessible ADA compliant WCAG compliant?"](https://github.com/videojs/video.js/wiki/Accessibility-(a11y)---is-video.js-accessible---ADA-compliant---WCAG-compliant%3F)
