### ISSUE TITLE
,i changed the videoBox border-radius to 24px, than, i can see two black thin lines above the video on the macOS

### ISSUE THREAD

**Issue by huangjian199304** [videojs/video.js#6229]
## Description
i use the videojs to play the video,i changed the videoBox border-radius to 24px, than, i can see two black thin lines above the video on the macOS, how can i fix it? plz

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.change the videoBox css border-radius to 24px
2. on the macOS,i can see two thin lines above the video

### Expected
on the macOS, didn't have two thin lines above the video

### Actual
on the macOS,i can see two thin lines above the video

### Error output
no error output

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
videojs  v7.4.1
#### browsers
chrome
#### OSes
macOS
### plugins
none
![QQ图片20190912155654](https://user-images.githubusercontent.com/32724076/64765043-f8964b80-d575-11e9-8e26-4d209a097f81.jpg)

**Comment by gkatsev** [comment]
I'm not following the issue. What is the "videoBox"? Have a live reduced test case that exhibits the issue we can take a look at?
