### ISSUE TITLE
Autoplay on mp3 file after pre roll

### ISSUE THREAD

**Issue by matlortie** [videojs/video.js#6230]
## Description
I run a video.js player with the IMA SDK Plugin for Video.js and when I change the source tag for an mp3 file, the autoplay do not work anymore.

## Steps to reproduce
Here's the example I used from the IMA SDK Plugin for Video.js
https://codepen.io/imasdk/pen/wpyQXP

And here's the one I want to use, the only thing that changed is the source tag and the type.
https://codepen.io/matlortie/pen/ExYRaJx
 
## Results
On the second one, I need to click the play button to start the audio.

### Expected
How can I have the autoplay working?

### plugins
IMA SDK Plugin for Video.js
https://github.com/googleads/videojs-ima

**Comment by gkatsev** [comment]
`autoplay` isn't an ima plugin option. You can pass it to videojs and it seems to be working, for example: https://codepen.io/gkatsev/pen/KKKPZgV

**Comment by matlortie** [comment]
ok, I see.
Thank's
