### ISSUE TITLE
MPEG-DASH manifest file is constantly requested from the server

### ISSUE THREAD

**Issue by zhulduz** [videojs/video.js#6233]
## Description
I noticed that after I stop a player, even if I dispose of it, the video player continue request manifest file. It appears only for mpeg-dash type.

This issue appears also in the example player 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. https://videojs.github.io/http-streaming/ set any example with mpeg-dash type
2. open network
3. stop the player

## Results
requests for manifest continues

### Expected
but shouldn't

Any thoughts? Or is there additional settings for it?
Please describe me, what should I do.

Thanks in advance.

**Comment by gkatsev** [comment]
Closing in favor of https://github.com/videojs/http-streaming/issues/658
