### ISSUE TITLE
Plugin won't be activated if I only use registerPlugin

### ISSUE THREAD

**Issue by ckybonist** [videojs/video.js#6238]
## Description
Use only `videojs.registerPlugin` will not activate example plugin. After stuck on this problem for few hours, I found that adding `plugins: {yourPluginName: {} }` in `VideoJsPlayerOptions` will solve this issue.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Create a example plugin from [official doc](https://docs.videojs.com/tutorial-plugins.html)
2. Register the plugin: `videojs.registerPlugin('examplePlugin', pluginExample);`
3. Finally, check the browser console, and there is no any outputs from `video.js`

### Expected
After invoking `videojs.registerPlugin('examplePlugin', pluginExample)`, I should see the log outputs from examplePlugin.

### Actual
Here is my sample code:
```
// Plugin
import videojs from 'video.js';

function examplePlugin(options) {
  if (options.customClass) {
    this.addClass(options.customClass);
  }

  videojs.log.error('test');

  this.on('volumnchange', () => {
    videojs.log('volume change');
  });

  this.on('playing', function() {
    videojs.log('playback began!');
  });
}
```

```
// Player
import videojs from 'video.js';
import pluginExample from './pluginExample';

videojs.registerPlugin('examplePlugin', pluginExample);

const Player = () => {
  const videoNode = useRef<HTMLVideoElement>(null);
  const [player, setPlayer] = useState<VideoJsPlayer | undefined>(undefined);

  // Init player that use native controls in safari,
  // otherwise use video.js' controls.
  useEffect(() => {
    const initialPlayer = videojs(videoNode.current, createConfig(), () => {
      if (isSafari()) {
        videoNode!.current!.controls = true;
      }
    });

    setPlayer(initialPlayer);

    return function cleanup() {
      if (player) {
        player.dispose();
      }
    };
  }, []);

  if (player) {
    console.log(player.hasPlugin('examplePlugin'));
  }
```

### Error output
N / A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
v7.6.4

#### browsers
what browser are affected?
Chrome 76.0.3809.132 (64 bit)

#### OS
what platforms (operating systems and devices) are affected?
macOS Mojave 10.14.6

### plugins
N / A

**Comment by gkatsev** [comment]
This is the expected behavior. Registering a plugin doesn't mean that you want to have the plugin run. There are two ways to initialize the plugin once its been registered. Either by passing the plugin name to the plugins option to the player by calling the plugin name as a method on the player.
We have documentation here https://docs.videojs.com/tutorial-plugins.html#setting-up-a-plugin
