### ISSUE TITLE
What is happening? Video URLs cut from the source! Doesn't appear anymore and I touch nothing!

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#6240]
Hello!
Basically I have downloaded a free plugin for wordpress.
This script use your player, video.js. But it allows me to add video URL from the wordpress backend.

The problem is, the plugin worked fine until yesterday. But today video.js doesn't play the video anymore. I didn't updated anything, not the plugin, not wordpress. It simply doesn't work anymore ou of nowhere. 

After checking the source code, what I've seen is that... the player script lack some parts! Indeed, all the parts about the video URL is cut away and doesn't appear anymore on the source the problem. This is an example:

```
<!-- Begin Video.js -->
	<video id="Videojs_id_1547379451" class="video-js vjs-default-skin vjs-16-9 vjs-big-play-centered vjs-fluid" width="720" height="420" poster="/wp-content/uploads/2019/03/thumb_1547379451.png" controls preload="none" data-setup='[]'>
		<source src="" type='video/mp4' />
		
		
        
		
		
		
<script> jQuery(document).ready(function(){
    jQuery('video').bind('contextmenu',function() { return false; });
});
</script>
```

As I said, I didn't updated anything and I touch nothing! So I don't know where to start for looking for a solution.

I can't even ask support to the plugin dev as they dismissed the plugin. I really need this plugin working! What happened? I would even be glad to have some kind of advice to where to start looking for support in a situation like this!

**Comment by mister-ben** [comment]
If parts are missing in the source code, the problem is server side and not something Video.js itself can influence. You'd best look into the Wordpress plugin's source to figure out how it is creating the player HTML.
