### ISSUE TITLE
I need autoplay only for mobile devices ?

### ISSUE THREAD

**Issue by Sanitehsi** [videojs/video.js#6244]
HI, Guys.

Can any one tell me how i can get the functionality of autoplay only for mobile devices not for web autoplay attribute works but i just need in mobile (android and ios both).

And once i scroll if video show on screen it should play and if it goes above then stop.

Thanks for help in advance.

**Comment by Eke** [comment]
Hello,

I think the best way is to detect mobile devices manually (without video.js) and based on detection set autoplay option before initing the player.

**Comment by gkatsev** [comment]
Video.js supports autoplay on mobile. However, mobile browsers are very strict and will not allow autoplay with sound unless it is part of a user gesture. We have a blogpost about best practices with autoplay: https://blog.videojs.com/autoplay-best-practices-with-video-js/. We also have a new option for autoplay to help out developers to choose the best available autoplay scenario: `any`, `muted`, and `play`. https://docs.videojs.com/tutorial-options.html#autoplay.

For what you're looking to do, assuming you've muted your video, you can use an IntersectionObserver (or good old-fashioned polling of the scroll top) to know when the video is in view and then call play on the player.
