### ISSUE TITLE
I need to get the letterbox or video aspect ratio

### ISSUE THREAD

**Issue by yuyu04** [videojs/video.js#6248]
Can you tell videoJS about the size of Video's letter box or aspect ratio of the playback file?

Each file has a different aspect ratio, so it's hard to overlay it with accurate information.
No matter how I find it, there is no way to know?

**Comment by gkatsev** [comment]
You can provide an aspectRatio option and call the method manually with a value like `"16:9"`.
https://docs.videojs.com/tutorial-options.html#aspectratio and https://docs.videojs.com/player#aspectRatio for docs.
You can also figure out the aspect ratio of a playing video by getting the [`videoHeight()`](https://docs.videojs.com/player#videoHeight) and [`videoWidth()`](https://docs.videojs.com/player#videoWidth).

Hope this helps.

**Comment by yuyu04** [comment]
> You can provide an aspectRatio option and call the method manually with a value like `"16:9"`.
> https://docs.videojs.com/tutorial-options.html#aspectratio and https://docs.videojs.com/player#aspectRatio for docs.
> You can also figure out the aspect ratio of a playing video by getting the [`videoHeight()`](https://docs.videojs.com/player#videoHeight) and [`videoWidth()`](https://docs.videojs.com/player#videoWidth).
> 
> Hope this helps.

thank you.

As a result of testing, aspect ratio could be calculated using player.videoWidth () and player.videoHeight () at the start of video playback.

**Comment by gkatsev** [comment]
Yup, just be aware that the earliest those values will be accurate is in the `loadedmetadata` handler.

**Comment by gkatsev** [comment]
Sounds like this has been answered?
