### ISSUE TITLE
Seeking video through external scrubber throws error

### ISSUE THREAD

**Issue by asadmalik3** [videojs/video.js#6252]
## Description
Briefly describe the issue.
I am using an external slider to seek my video player. When scrubber/slider is changed i use currentTime method to update time in video js. Slider can throw hundred of values inside a second so currentTime method will be called hundred of times in a second. This seems to be working fine but sometimes it throws error like below

![image](https://user-images.githubusercontent.com/6158094/66101397-27796d80-e5c8-11e9-9428-ca098e68ec79.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.When video starts playing, use set current time method to change seek position of video. 
2.Call this method randomly hundred of times in a second.
3.Watch console log of browser.

### Expected
Player should seek smoohtly.

**Comment by gkatsev** [comment]
Do you have a live reduced test case? I just tried locally to call currentTime locally a bunch and am not seeing any issues. I'm not sure that the issue is due to Video.js.

**Comment by nvahalik** [comment]
Potentially related...

We are using VideoJS with the `videojs-mux` plugin and we've begun getting errors (only on WebKit, however!) when pausing while full-screen.

This is in the context of a Hybrid/mobile app using Ionic.

**Comment by gkatsev** [comment]
@nvahalik that's likely a separate issue. Can you open a new issue with more details preferably a reduced test case?
