### ISSUE TITLE
Video.js Setup & Instruction

### ISSUE THREAD

**Issue by cijtx210** [videojs/video.js#6255]
I've downloaded v7.6.5 , the source code, and Node.js. How do I implement them? Are they to be placed in a particular location/folder on my computer or within a certain directory where my site's files are located at, which is FileZilla. I'd apprciate some assistance in getting set up. Thank you.

**Comment by cijtx210** [comment]
![video js](https://user-images.githubusercontent.com/56218587/66272026-26477b00-e82a-11e9-92d2-a9a98e8e54a3.jpg)

**Comment by gkatsev** [comment]
We have a short [getting started](https://videojs.com/getting-started/) guide on the website and a [quick start guide](https://github.com/videojs/video.js/#quick-start) in our README. You can link the javascript and css files in the HTML page by using the `<script>` and `<link>` elements on in the  HTML.
