### ISSUE TITLE
Change source with type='application/x-mpegURL' in Windows 7 IE11 

### ISSUE THREAD

**Issue by semel1** [videojs/video.js#6256]
## Description
In case of initially video type='application/x-mpegURL' specified (regardless “videojs-contrib-quality-levels” & “videojs-http-source-selector” plugins installed and initialized), player throws an error: “VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.”
That’s understandable because Windows 7 IE11 doesn’t support HLS.
However, further attempt to dynamically change source caused: 
ProgressBar, vjs-duration/vjs-remaining-time, vjs-play-contrl (play/pause) does not update as expected, showing duration/remaining time - “NONE” even “player.duration()” shows correct value, source gets changed and could be played back. 

## Steps to reproduce
```
<video id="video"  class="video-js vjs-default-skin "  width="640" height="360" poster="https://bitmovin-a.akamaihd.net/content/sintel/poster.png"  controls preload="auto" 
data-setup='{"liveui": true, "autoplay": false}'>
<source src="https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8", type='application/x-mpegURL' />
</video>
```
```
<script>
var player=videojs("video")	
player.on('error', function() {
console.log("error due to the unsupported format")
	//---attemt to change source
player.reset();	
player.src([
  { type: "video/mp4", src: "//vjs.zencdn.net/v/oceans.mp4" },
]);	
player.ready(function(){
    player.on('loadedmetadata', function(){
	console.log("player duration:",player.duration())
})});			
player.play();
});
</script>
```
### Expected
Changing sources and proper controls behavior

### Actual
1.Source gets changed and could be played/paused
2.ProgressBar, vjs-duration/vjs-remaining-time, vjs-play-contrl (play/pause) does not update as expected, showing duration/remaining time - “NONE”.
3.Progress control slider could not be dragged, current time could not be changed.
4.Play control doesn't updated (always showing "play" icon regardless of "playing"/"paused" state). 
### Error output
Console shows no errors after script execution

## Additional Information

Video.js 7.6.5 IE 11 Windows 7 only

**Comment by gkatsev** [comment]
There is no need to call `player.reset()`, you can call `player.error(null)` to hide the error and then set the new src as you have your example.

**Comment by semel1** [comment]
Unfortunately it doesn't work.
Case1:
```
 <script>
var player=videojs("video")	
player.on('error', function() {
console.log("error due to the unsupported format")
	//---attemt to change source
//player.reset();	
player.error(null);
player.src([
  { type: "video/mp4", src: "//vjs.zencdn.net/v/oceans.mp4" },
]);	
player.ready(function(){
player.on('loadedmetadata', function(){
console.log("player duration:",player.duration())
})});			
player.play();
});
</script>
```
![case1](https://user-images.githubusercontent.com/53234248/66334100-38d6b880-e8ed-11e9-8d9b-322cbd866c6f.jpg)

Case2:
```
 <script>
var player=videojs("video")	
player.on('error', function() {
console.log("error due to the unsupported format")
	//---attemt to change source
//player.reset();	
//player.error(null);
player.src([
  { type: "video/mp4", src: "//vjs.zencdn.net/v/oceans.mp4" },
]);	
player.ready(function(){
player.on('loadedmetadata', function(){
console.log("player duration:",player.duration());
player.error(null);
})});			
player.play();
});
</script>
```
![case2](https://user-images.githubusercontent.com/53234248/66334262-87845280-e8ed-11e9-944b-868ce5a449ef.jpg)

**Comment by semel1** [comment]
Accidentally closed an issue. Problem still exists.

**Comment by gkatsev** [comment]
Looks like this isn't an IE11 specific issue. I can reproduce this by trying to swap a source on the error, for example: https://codepen.io/gkatsev/pen/JjjdYWQ

**Comment by gkatsev** [comment]
Looks like when the first source fails to load, the tech isn't loaded and thus things are never hooked up properly. We'll investigate.

**Comment by semel1** [comment]
Does it mean that this possibly video.js bug?
Is there any workaround?

**Comment by gkatsev** [comment]
Definitely something we have to fix. We'll post here if we think of a workaround.

**Comment by semel1** [comment]
Yes, It looks like that for me too - "the tech isn't loaded and thus things are never hooked up properly".
One thing I've noticed - if "videojs-playlist"/"videojs-playlist-ui " is installed  and initialized - sources changes, controls and  behaves properly

**Comment by gkatsev** [comment]
Looking into it, it seems like this behavior has been around in Video.js for ages. I've reproduced this issue with Video.js 5.x as well.
When using videojs-playlist, I assume you're not setting the "bad" source directly but rather via the playlist right?

**Comment by semel1** [comment]
Yes, via playlist that ignores direct  source and load the first playlist item(or specified as "first" in the playlist options).

**Comment by hydra3333** [comment]
bump

**Comment by hex0id** [comment]
I don't think this issue is outdated as I experience it right now in version 7.8.3. My case is pretty much the same, but I try to load live video over empty source (sources: [{}] in config). I tried many ways to workaround this problem but with not luck, is there a way to "force" live mode in player? I tried adding css class, but it won't make actual difference, play / pause button and other controls will still be buggy.

**Comment by semel1** [comment]
Unfortunately looks like this issue still not resolved. My workaround (ugly) is to move player inside wrapper (in order to preserve player position in the DOM),dispose player and dynamically re-initialize it with initial attributes/options and new source and move it inside wrapper again.
