### ISSUE TITLE
 How can I fix the native player in full screen on iOS?

### ISSUE THREAD

**Issue by yuyu04** [videojs/video.js#6257]
I'm using videojs to add features such as bookmarks.

However, there is a problem that the native player works on iOS, and all my controllers disappear when the native player works. Added playsinline as a video option, but pressing the full screen will cause the native player to work again. 

However, if it works in full screen, it does not look good. Is there any solution in this regard?

**Comment by gkatsev** [comment]
On iPhones, when going fullscreen you will always be taken to the native player and there isn't anything that can be done about it. It's a platform limition. On iPads, starting with iOS 12, the fullscreen API has been supported and Video.js should be using it already.

**Comment by sajinthom** [comment]
Hi @gkatsev , this issue with player controls does not happen on YouTube.com's HTML5 player on the same iOS device in fullscreen. Does this not mean, it can be fixed within video js?

**Comment by thanhkhanhcntt** [comment]
This issue should re-open because Youtube.com can play without fullscreen.

**Comment by gkatsev** [comment]
Looks like the iframe api now has a `playsinline` option https://developers.google.com/youtube/player_parameters#playsinline
That didn't exist back when this was initially closed.

**Comment by dani3l3** [comment]
Hi, has there been any further progress on this? I also found this other thread https://github.com/videojs/video.js/issues/6567

**Comment by MannanK** [comment]
I would also like to know if there has been any change in this area, especially after the latest iOS release. Thanks!

**Comment by gkatsev** [comment]
It is not possible to use our fullscreen on iPhones. You can on iPads. This is a platform limitation.

**Comment by dani3l3** [comment]
> It is not possible to use our fullscreen on iPhones. You can on iPads. This is a platform limitation.

thanks for your answer. Keep up the great work.

**Comment by tankvn** [comment]
You can fix it by add **playsinline** attribute to video tag:
`<video src="..." controls playsinline></video>`

[https://css-tricks.com/what-does-playsinline-mean-in-web-video/](https://css-tricks.com/what-does-playsinline-mean-in-web-video/)

**Comment by dani3l3** [comment]
Very interesting, thanks @tankvn !
mozilla documents it as https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video 

> playsinline
> A Boolean attribute indicating that the video is to be played "inline", that is within the element's playback area. **Note that the absence of this attribute does not imply that the video will always be played in fullscreen.**
> 

but Apple seems to have missed the last piece, apparently :-)
