### ISSUE TITLE
How to check if video is  muted?

### ISSUE THREAD

**Issue by BonBonSlick** [videojs/video.js#6260]
```
                this.player.on('volumechange', (event) => {
                    console.log('1', event.target); // video player element
                    console.log('4', this.player.volume()); // wrong value if volumeBar clicked
                });

```

```
type: "volumechange",
 target: div#vjs_video_3.video-js.vjs-big-play-centered.vjs-fluid.vjs_video_3-dimensions.vjs-controls-enable…, 
relatedTarget: undefined,
preventDefault: ƒ, defaultPrevented: false, …}
defaultPrevented: false
isImmediatePropagationStopped: ƒ returnFalse()
isPropagationStopped: ƒ returnFalse()
preventDefault: ƒ ()
relatedTarget: undefined
stopImmediatePropagation: ƒ ()
stopPropagation: ƒ ()
target: div#vjs_video_3.video-js.vjs-big-play-centered.vjs-fluid.vjs_video_3-dimensions.vjs-controls-enabled.vjs-workinghover.vjs-v7.vjs-layout-large.vjs-has-started.vjs-paused.vjs-user-inactive
type: "volumechange"
which: undefined
```

Event fired when the volume is changed,

The issue is, it is called when the user uses a slider or just clicks on the volume bar.

The difference is when using the slider, volume changes, but when just clicking on volume bar, the volume is still 1.0, but the video is muted. As a result, we got the wrong value from the player.volume().

Also tried  according to [docs](https://tradecaptain.com/Component/website/campaigns/walid/video.js/docs/api/control-bar_volume-control_volume-bar.js.html)
```
player.VolumeBar // ndefined
// or
player.VolumeBar() // not a function
```

**Is there any way to check if a video was muted?**

**Comment by BonBonSlick** [comment]
Solved

`                    this.setVolume({volume: true === this.player.muted() ? 0 : this.player.volume()});
`

But still, why 
```
player.VolumeBar // ndefined
// or
player.VolumeBar() // not a function
```

**Comment by gkatsev** [comment]
If you want to know whether the video is muted you should check `player.muted()`.
Historically, setting volume level 0 didn't mark it as muted as in the video element volume and mute are completely separate but in Video.js 6 we've consolidated the two so when volume is set to 0 it also marks the player as muted. However, it does still mean that you can have a volume of 1 and be muted.
