### ISSUE TITLE
under given condition， browser get the m3u8 response rightly but no TS request happen ,always make m3u8

### ISSUE THREAD

**Issue by tonyload** [videojs/video.js#6262]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.get the m3u8 request rightly and then stop push stream, make the browser get m3u8 request 404
2. wait a few seconds, restart push the stream
3.u will see, the browser always make the m3u8 request but no ts request make

### Expected
Please describe what you expected to see.
if the m3u8 get the response rightly,then should make the ts request rightly

### Actual
Please describe what actually happened.
no ts request,the browse always make the m3u8 request, the video cant play move on 

### Error output
If there are any errors at all, please include them here.

what version of videojs does this occur with？
7.6.0
what browser are affected?
chrome

![1570671186(1)](https://user-images.githubusercontent.com/53110897/66532193-0cb37580-eb41-11e9-81bb-332c60dea604.png)

**Comment by salsaweb** [comment]
any updates here?
