### ISSUE TITLE
When toggle between full-screen and non-fullscreen in safari, player may become black and/or freeze

### ISSUE THREAD

**Issue by jeffrey20191231** [videojs/video.js#6263]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Prepare a live hls stream with abr
2. Play the stream
3. Toggle between full-screen and non-fullscreen

### Expected
The playback keep playing or only stop for a small amount of time when toggle between fullscreen and non-fullscreen.

### Actual
Either these results may happen sometime
1. The playback stop and resume in about 10 second
2. The playback stop and become black screen and resume in about 10 second
3. The playback stop and become black screen and never resume

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.6.5
#### browsers
what browser are affected?
Safari 12.1.2
#### OSes
what platforms (operating systems and devices) are affected?
macOS 10.13.6

**Comment by alpkahveci** [comment]
i have similar issue with dash source and just opened it https://github.com/videojs/video.js/issues/7696
