### ISSUE TITLE
How to let users use their own subtitles?

### ISSUE THREAD

**Issue by Medow** [videojs/video.js#6269]
Hi:
openload.co use videojs player , and they have a feature that let users upload their own subtitles from PC or from external direct URL.
How can i make this feature on my videojs player?
Thanks.

**Comment by gkatsev** [comment]
You can also allow them to upload srt files by then running the text through this processor https://github.com/silviapfeiffer/silviapfeiffer.github.io/blob/master/index.html#L150-L216
