### ISSUE TITLE
Pack with webpack, mux.js caption-parser not found

### ISSUE THREAD

**Issue by Lyrillind** [videojs/video.js#6271]
## Description
When pack using webpack, it told me like this:
```
This dependency was not found:

* mux.js/lib/mp4/caption-parser in ./node_modules/video.js/dist/video.es.js
```

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. npm install video.js
2. write "import videojs from 'video.js'"
3. run webpack to pack

## ENV
"video.js": "^7.6.5"

**Comment by Saw-zall** [comment]
Exact same issue, caption-parser is missing

**Comment by TylerK** [comment]
Running into this as well. Any help would be appreciated :)

**Comment by Saw-zall** [comment]
I fixed it by manualy installing mux.js `npm install --save mux.js`

**Comment by AjaxSir** [comment]
> 我通过手动安装mux.js进行了修复 `npm install --save mux.js`

Have you solved it

**Comment by AlexZ33** [comment]
![image](https://user-images.githubusercontent.com/21971405/71808579-1baab500-30a9-11ea-9bba-a7244ec7e9b9.png)
Exact same issue

**Comment by aloksoni11** [comment]
This dependency was not found:

* mux.js/lib/mp4/caption-parser in ./node_modules/videojs-flash/node_modules/video.js/dist/video.es.js

To install it, you can run: npm install --save mux.js/lib/mp4/caption-parser
