### ISSUE TITLE
How can I override values/actions of progress line

### ISSUE THREAD

**Issue by gyerts** [videojs/video.js#6274]
I work with live stream of video HLS (m3u8). Do I have possibility to get full control over progress bar. 

Example cases:

1) set my custom progress value independent of real progress
* For example we have live stream, when I set it to the videojs player, player knows nothing about duration, current progress, etc... But our application knows this information. How can I tell to the progress-bar this information?

2) send http request when click somewhere in progress-bar
* Also we need functionality to handle click on progress-bar -> after click send request to backend -> get new http-stream link -> set to player -> set new progress-value to progress-bar 

3) get position of mouse over progress-bar
* for future, show helper-pictures (video frame)

All this functionality can by implemented by react-player-controls, but if to be honest I want to use one library to achieve results like a pro :))  (https://alexanderwallin.github.io/react-player-controls/)

**Comment by gkatsev** [comment]
That's a pretty cool project.

However, you probably want to look at our middleware functionality. It allows you to intercept and fiddle around with the values that show up in the control bar. Take a look at https://docs.videojs.com/tutorial-middleware.html and https://videojs.com/blog/feature-spotlight-middleware/
