### ISSUE TITLE
Layout fluid is not working on ios

### ISSUE THREAD

**Issue by klimentLambevski** [videojs/video.js#6277]
## Description
I set fluid: true in videojs constructor and  it works great on desktop browsers but on IOS the padding of videojs  container is bound to 16:9 container

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Add preload attribute to video
2. Add playsinline attribute to video
3. Play video in ios

### Expected
Expected to see video in full width

### Actual
The video frame is in full width but the video is bound to 16:9 container

### Error output
If there are any errors at all, please include them here.

#### videojs
7.6.0
#### browsers
IOs 13

**Comment by mister-ben** [comment]
What is your source url?

**Comment by gkatsev** [comment]
I cannot reproduce fluid: true not working on iOS. Can you provide a reduced test case?
