### ISSUE TITLE
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

### ISSUE THREAD

**Issue by BlockCanary** [videojs/video.js#6278]
1.chrome version  77.0.3865.75      64bit
2.in Vue  
3.It can be playing  a  little while then stoped by “ The media playback was aborted due to a corruption problem or because the media used features your browser did not support.“
4.it works well in  IE.

**Comment by gkatsev** [comment]
Unfortunately, there is not enough information for us to answer. Preferably, please include a test stream in a live example.

**Comment by asself** [comment]
the same issue

**Comment by pmendozav** [comment]
same issue on chromecast. that happens when change html5 to youtube tech

**Comment by Pouryakordi** [comment]
I had the same issue
I used the constructor like this to override native
```
      var player = window.player = videojs('video', {
      html5: {
      hls: {
      overrideNative: true
      },
      nativeAudioTracks: false,
      nativeVideoTracks: false
     }
      });
```

and also you should use source like the example below if you use "<source src='$moviesHls' type='application/x-mpegURL'>" inside video tag chrome native player may take the control (I think) so it didn't work with just "overrideNative: true" you should use the method below to add source.

```
player.src({
       type: 'application/x-mpegURL',
        src: '$moviesHls'
           });
```

At least it Solved my Error So i decided to share it.
