### ISSUE TITLE
How to catch VIDEOJS ERROR?

### ISSUE THREAD

**Issue by saifeiLee** [videojs/video.js#6280]
![image](https://user-images.githubusercontent.com/28710808/67205380-37a3a080-f442-11e9-8ff7-9717f4ec3245.png)
I want to catch the VIDEOJS ERROR and show some tips to users. I've tried `player.error()`, but it did not show error message.So, how can I catch VIDEOJS ERROR?

**Comment by mister-ben** [comment]
`player.error()` returns the most recent error. you can listen to the `error` event:

```
player.on('error', function() {
  console.log(player.error());
});
```

**Comment by saifeiLee** [comment]
Wow! That's exactly what I need. Thank you so so so much!!!!!!
