### ISSUE TITLE
[question]Extract blob from the video player

### ISSUE THREAD

**Issue by mhamri** [videojs/video.js#6281]
I'm trying to create a chrome extension to help to download videos without wasting bandwidth, the idea is the user watch the video and if they like it they can download it from the cache. so fo this I need to create blob and push the data into it from the streaming data. 

I am seeing that the cache data is available. but don't know which event I should hook into, or what property I should call. if you shed some light on the internal process it can help me a lot to increase my progress speed.

thanks

**Comment by gkatsev** [comment]
Unfortunately, once we put the data into the source buffer you can't retrieve it again. We don't currently expose the XHR of the segment request. We have had a lot of requests for access to the XHR and it's likely that with access to it, you could be able to grab the byte data after the request is done. I'd follow the http-streaming repository for this feature. Though, I'm not sure when it'll be ready.
If you're interested, I can write up a spec/req doc and you can implement it.
For now, I'm going to close this issue, but we can continue discussions here as well.
