### ISSUE TITLE
TS segment with SPS/PPS in the end of access units when using HLS can't be played.

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [videojs/video.js#6282]
## Description
If the TS segment with SPS/PPS in the end of access units, like the below image,  the audio stream can't be played. 
![image](https://user-images.githubusercontent.com/9837705/67362920-d1806000-f59e-11e9-8d24-1533b95458cb.png)

At the same time, we using the `VLC` and Android `ExoPlayer` to play well.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
Use this url [http://111.10.31.199:9500/shaoer/2erge/7zhongyingwentongyao/zywty005/zywty005.m3u8]() can reproduce the issue.

**Comment by gkatsev** [comment]
Seems like this is working using VHS version 1.11.2 (and or Video.js 7.7 which includes VHS 1.11.2). Can you retry?

**Comment by gkatsev** [comment]
Starting with VHS 1.11.2, we are now able to play back the video. Unfortunately, we are unable to play back the audio because it is mp1 audio but we only support aac audio.
