### ISSUE TITLE
VIDEO js throw error while playing mp4 file with ac3 audio codec

### ISSUE THREAD

**Issue by asadmalik3** [videojs/video.js#6284]
## Description
I have an mp4 file (specs given below). When i try to play it in browser, video js throws below given error `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.`

File specs:
![image](https://user-images.githubusercontent.com/6158094/67465670-06ec8280-f65f-11e9-82eb-656610f4c117.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Download video file from [here](https://www.dropbox.com/s/8swy6zodbaggx56/ac3-audio-codec.mp4?dl=0)
2. Try to play in video js
3. See console log

### Expected
Video should play in video js

### Actual
Video is not playing

### Error output
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

### versions
7.6

#### browsers
Chrome

#### OSes
Windows 10

**Comment by mister-ben** [comment]
MP4 support in browsers means the MP4 container, with the h.264 (or avc) video codec and acc audio codec. You'd need to re-transcode the video.

**Comment by gkatsev** [comment]
Unfortunately, we don't support ac3 and I don't think most browsers do. Your best bet is to retranscode as @mister-ben mentioned.
