### ISSUE TITLE
nativeControlsForTouch: false, not working on some Android

### ISSUE THREAD

**Issue by saifeiLee** [videojs/video.js#6285]
## Description
I set `nativeControlsForTouch: false` in options. On ios, it shows custom controll bar.But on Android the native controll bar shows.My question is how can i really disable the custom controll bar?
Please help me. Thanks very much!

### Expected
Video shows my custom controll bar not the native.

#### videojs
video.js@7.6.5

**Comment by mister-ben** [comment]
Can you elaborate on "soe Android", e.g. browser and Andorid versions?

**Comment by saifeiLee** [comment]
> Can you elaborate on "some Android", e.g. browser and Android versions?

Android 9 and Android 7.11

**Comment by gkatsev** [comment]
What happens if you don't set nativeControlForTouch at all? I believe we default to showing our custom controls by default except on some older devices.

**Comment by saifeiLee** [comment]
> What happens if you don't set nativeControlForTouch at all? I believe we default to showing our custom controls by default except on some older devices.

Thank you for replying. I did not use `nativeControlForTouch `. If i dont set `overrideNative`, for some Android devices, it displays the native control bar. I tried using `player.src({overrideNative: true})`, it seems to work. I will test more android devices. Thanks again.

**Comment by BH-NOTHING** [comment]
@saifeiLee 朋友，能详细说下解决方案么，我现在也掉坑了，也在处理华为手机默认显示原生控制条问题。
