### ISSUE TITLE
[question]: pass EXT-PROGRAM-DATE timestamp from m3u8 to live ui time

### ISSUE THREAD

**Issue by Llorito** [videojs/video.js#6288]
Is there any method to change live ui time to EXT-PROGRAM-DATE timestamp?
Example:

Our live session start at 9:00 am and the user initialize the live playblack at 10. Now we have a DVR window of 1hour, but we want to see in the live bar from 10:00 (live) to 9:00 instead of 1:00.

**Comment by gkatsev** [comment]
You may be able to achieve something like that using the videojs middleware functionality.
