### ISSUE TITLE
I need help! !

### ISSUE THREAD

**Issue by AccountGc** [videojs/video.js#6291]
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.Can videojs play hls to prevent dragging the progress bar?

@gkatsev  @mister-ben Thank you!

**Comment by bcbclifford** [comment]
Call `disable()` on the progress bar.

    player.controlBar.progressControl.disable();

**Comment by AccountGc** [comment]
@bcbclifford Thank you

**Comment by AccountGc** [comment]
@bcbclifford How does videojs add background images to audio files?
