### ISSUE TITLE
how to get   h264  codec sei information

### ISSUE THREAD

**Issue by xueyongapple** [videojs/video.js#6298]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by xueyongapple** [comment]
I want to get the extension information of video. Is there such an interface（sei）

**Comment by gkatsev** [comment]
I don't think we expose a way to get this information.

**Comment by gkatsev** [comment]
We don't currently have any plans to expose the sei information unless that is subtitle data.

**Comment by LuciferDarkstone** [comment]
> 
> 
> We don't currently have any plans to expose the sei information unless that is subtitle data.

So did it support expose sei infomation now?
