### ISSUE TITLE
How to disable video fast forward operation

### ISSUE THREAD

**Issue by littlesalt** [videojs/video.js#6299]
I am developing a training video that requires not to fast forward the video.I found some information on the Internet and did not meet the demand.

**Comment by papigers** [comment]
Hi, issues are used to report bugs, not asking for help.
You can search or ask a new question on [StackOverflow](https://stackoverflow.com/questions/tagged/video.js).

Have a look at this [question](https://stackoverflow.com/questions/19112255/change-the-video-playback-speed-using-video-js).

**Comment by littlesalt** [comment]
ok



---Original---

**Comment by mister-ben** [comment]
Call `disable()` on the progress bar.

    player.controlBar.progressControl.disable();
