### ISSUE TITLE
index.m3u8"+token

### ISSUE THREAD

**Issue by Rishushree** [videojs/video.js#6300]
I am working in project. I want to use links with token in videojs player.
like index.m3u8"+token

I have a code of jw player

var playerInstance=jwplayer("iwplElement");
--
  | var token ;
  | var play= false;
  | $.getJSON( "/micros/live-tv-token.php", function( data ) {
  | $.each( data, function( key, val ) {
  | token  =  val;
  | });
  |  
  | var video_file = "/index.m3u8"+token;
  | function loadToken(){
  | $.getJSON( "/micros/token.php", function( data ) {
  | $.each( data, function( key, val ) {
  | token  =  val;
  | });
  | });
  | return token;

but
i want to use this process in videojs can you please help me how to use m3u8 liks and token file together in videojs.

Thank you.

**Comment by Rishushree** [comment]
Thats not issue..

i want suggestion how to use above both things together..

**Comment by gkatsev** [comment]
You can use beforeRequest to update the urls for each request for the m3u8: https://github.com/videojs/http-streaming/#hlsxhr
Just be aware that this doesn't work on Safari as we use native playback there. In addition, beforeRequest is currently required to be called synchronously.
