### ISSUE TITLE
browser throw error: global or document is undefined

### ISSUE THREAD

**Issue by shuiyuelinghui** [videojs/video.js#6303]
## Description
use npm install video.js in angular6, and then import video.js in my compontent; open in the browser and then throw the error: 'global  is undefined';
the error is becouse of  the dependence of has-symbols moudle; 
relation issues: https://github.com/inspect-js/has-symbols/issues/6;

**Comment by gkatsev** [comment]
I'm not sure we can do anything reasonable about this. I would recommend following the suggested workaround given in that issue.
