### ISSUE TITLE
H264 - MPEG-4 AVC (part 10) (avc1) -> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media

### ISSUE THREAD

**Issue by acemtp** [videojs/video.js#6306]
## Description

I try to display a video made with Tesla dashcam.

From VLC info, the video format is "H264 - MPEG-4 AVC (part 10) (avc1)"

* It renders correctly with VLC, quicktime player, safari (native video player), firefox (native video player)
* It doesn't render on chrome with native player (issue reported)
* With videojs it doesn't render on chrome nor on safari and give the error: VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

If you want to do some test, you can get the mp4 here: 
https://talkus.io/test.mp4

#### videojs
7.6.5 from CDN
#### browsers
all
#### OSes
latest mac os
### plugins
no plugin

**Comment by gkatsev** [comment]
Unfortunately, if the browser can't play the mp4 itself, there's nothing we can do.
When playing back, I'm seeing the following in media-internals:
```
FFmpegDemuxer: unfixable negative timestamp.
FFmpegDemuxer: demuxer error: 13
DEMUXER_ERROR_COULD_NOT_PARSE
```
I would recommend re-transcoding the video to something that would work on all browsers.

**Comment by acemtp** [comment]
Thanks @gkatsev 

Just 2 small questions if you are kind to answer:

- What was the command that display this error? I tried with ffmeg and didn't get errors.

- The video play correctly with firefox but not with videojs on firefox, why is that?

**Comment by gkatsev** [comment]
The error is from chrome's media internals, you can see the output by going to `chrome://media-internals`. I'm not sure why firefox would be different between with and without videojs. But Firefox plays things different and there are definitely times when a video plays in firefox but not chrome and vice versa.
