### ISSUE TITLE
How to distribute middleware in a plugin

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#6311]
I have a plugin that uses middleware to customize `setSource`, e.g.

```javascript
// register a star-middleware
videojs.use('*', player => {
    // make player available on middleware
    myMiddleware.player = player;

    return myMiddleware;
});
```

How should I include this in a plugin?

- I don't want this middleware to take over other video.js instances on a page
- I also don't want to put this extra burden on the user, them having to use `videojs.use`

Thoughts?

**Comment by mister-ben** [comment]
Middleware is always global but perhaps test `player.usingPlugin('myPlugin')` in `setSource` and pass the source through unmodified if not.

**Comment by gkatsev** [comment]
Yeah, middleware is global right now. The key to distribution is not to register it as part of the plugin method itself but doing so at the top level.
If it works with your plugin, doing the check as @mister-ben suggested is our recommended approach right now. Here's an example in our contrib-ads plugin: https://github.com/videojs/videojs-contrib-ads/blob/master/src/playMiddleware.js#L40-L44. If you have thoughts on this or ways to improve this please let us know.

**Comment by thijstriemstra** [comment]
Sorry for the late reply and thanks for the feedback @gkatsev and @mister-ben.

I ended up using your suggested check:

```javascript
// register a star-middleware
videojs.use('*', player => {
    // make player available on middleware
    WavesurferMiddleware.player = player;

    return WavesurferMiddleware;
});

const MyMiddleware = {
    /**
     * Setup the routing between a specific source and middleware
     * and eventually set the source on the Tech.
     *
     * @param {Tech~SourceObject} [srcObj] - Source object to manipulate.
     * @param {Function} [next] - The next middleware to run.
     */
    setSource(srcObj, next) {
        if (this.player.usingPlugin('myPluginName')) {
            // do plugin middleware stuff here
        } else {
            // ignore middleware and load source into video.js
            next(null, srcObj);
        }
    }
};
```
thanks!

ps. I wasn't able to access the player on the middleware so I assigned like shown above, but maybe there's a better way to do it?

**Comment by gkatsev** [comment]
That works. We've also just inlined the object, and so we have `player` available in the scope.
