### ISSUE TITLE
full screen of huawei  is invalid

### ISSUE THREAD

**Issue by pocketChao** [videojs/video.js#6312]
## Description
I used the X5 kernel to play m3u8 video on the huawei phone. After clicking the full-screen button, there was no response and the page was stuck.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.device: Huawei p10
2.X5 kernel
3.play m3u8
4.click the full screen button

## Results
No response and the current page is jammed
### Expected
Full screen play video

### Actual
No response and the current page is jammed

### Error output
no error output

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
^7.6.0
#### browsers
X5 kernel
#### OSes
Android 8.0 webView
### plugins
![屏幕快照 2019-11-11 下午1 55 16](https://user-images.githubusercontent.com/21028807/68564237-fcb5eb00-048a-11ea-8111-8ca0e6433e78.png)
![屏幕快照 2019-11-11 下午1 55 00](https://user-images.githubusercontent.com/21028807/68564239-ffb0db80-048a-11ea-91fd-d7a8d0612518.png)

**Comment by pocketChao** [comment]
![屏幕快照 2019-11-11 下午1 57 53](https://user-images.githubusercontent.com/21028807/68564416-86fe4f00-048b-11ea-8b18-3bc9265179fc.png)

**Comment by liyoubdu** [comment]
maybe this is bug from huawei phone

**Comment by pocketChao** [comment]
> maybe this is bug from huawei phone

I agree. See if anyone else has the same problem and find a solution 0.0

**Comment by gkatsev** [comment]
Is this chrome browser or another browser? It's possible that the fullscreen functionality isn't really avilable even though the API is available.

**Comment by gkatsev** [comment]
Unfortunately, I don't think we have the bandwidth to look into this especially given that it's likely a browser bug.
The workaround is to disable the fullscreenToggle manually when on a huawei phone.
