### ISSUE TITLE
Picture in Picture Remove For Audio

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#6314]
## Description
Hi, I am using videojs to play an audio hls stream.

Is there a way to hide picture in picture if no video tracks are present?

Something like this.
~~~
var vtracks = player.videoTracks();
                    if(vtracks.length === 0){
                        var pip = player.getChild('controlBar').getChild('PictureInPictureToggle');
                        pip.hide();
                    }
~~~~

If there was some way of knowing if the hls is audio only I could easily do this with the code above.

Thanks

**Comment by mister-ben** [comment]
How about checking `player.videoHeight()`?

**Comment by samueleastdev** [comment]
Great thanks @mister-ben this works.

~~~
// EVENTS
player.one('loadedmetadata', function(_event) {

    if (this.videoHeight() === 0) {

        var pip = player.getChild('controlBar').getChild('PictureInPictureToggle');
        pip.hide();

    }

});
~~~

**Comment by gkatsev** [comment]
you can also do something like `player.controlBar.removeChild('pictureInPictureToggle')`
