### ISSUE TITLE
Add an ES6 distribution in NPM

### ISSUE THREAD

**Issue by boris-petrov** [videojs/video.js#6315]
The latest `video.js` version from NPM comes with a few files in the `dist` directory, but all of them are transpiled from the original source to an ES5-compatible version. Browsers nowadays support directly ES6+ so it would be better if you could build an ES6 version of the code for use by modern browsers. That version would be *much* smaller and faster.

**Comment by gkatsev** [comment]
Yeah, this is something we'll be looking into soon.
