### ISSUE TITLE
Unsolicited backwards seeking after currentTime() set in iOS 13

### ISSUE THREAD

**Issue by salaamender** [videojs/video.js#6316]
## Description
Briefly describe the issue.
Player jumps back 10 - 20 ms after video is seeked via Player.currentTime(xyz) in iOS 13.
Example: https://jsfiddle.net/okf5wch7/8/

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use iOS 13
2. Set Player position via currentTime(xyz)
3. Despair

### Expected
Continuous playback onwards from position xyz after Player.currentTime(xyz) is called

### Actual
After currentTime(xyz) is called, player seeks to xyz and then jumps back to (xyz minus ~15ms).

### Error output
From an iPad on iOS 13.2.2 running the JSFiddle (in Chrome)!
currentTime: 2.762545796
currentTime: 3.01473235
currentTime: 10                          [ successful seek! ]
currentTime: 10
currentTime: 9.737431884         [ unsolicited backwards seeking D: ]
currentTime: 9.991138877
currentTime: 10.490918454
currentTime: 10.741956559

From a well-functioning instance of the same fiddle on Chrome on Windows 10:
currentTime:  2.948039
currentTime:  3.197766
currentTime:  10
currentTime:  10.197509
currentTime:  10.447404

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
Tested and confirmed broken on video.js 7.6.5 and 7.2.3 
#### browsers
Safari and Chrome
#### OSes
iPhone 8 running iOS 13.1.3 and
iPad (6th gen) running iOS 13.2.2

**Comment by gkatsev** [comment]
Unfortunately, I am unable to reproduce either in Safari or Chrome on iOS 13.

**Comment by bainro** [comment]
I replicated it on two devices. I got the same type of log progression on both an iPhone v13.1.3 and on an iPad v13.3 (beta version) using Chrome. I got the log using another tab: chrome://inspect. 

This didn't occur until a recent update, 13.1.2 I believe.

**Comment by mister-ben** [comment]
I can replicate on an iPhone with 13.1.3, but also with a plain video element - https://jsfiddle.net/bhL6am3j/1/ which makes sense as `currentTime()` is jsut passing through to a video element in this case.

I don't see how Video.js could influence the behaviour. It's probably not seeking forward and jumping back but rather reporting the position it's seeking to and then what it has seeked to.

**Comment by bainro** [comment]
I used BrowserStack to view your fiddle on version 12.x and the logs looked the way they should. 

It must be that 13.x changed the <video> behavior. Thanks for your help :)

**Comment by daianaszwimer** [comment]
hey, i'm also having this issue, how can i fix it?

**Comment by YG-qualson** [comment]
I guess this is an iOS behavior.
