### ISSUE TITLE
Any custom skin has broken time/duration/remaining output

### ISSUE THREAD

**Issue by Anan5a** [videojs/video.js#6320]
## Description

If I use any skin other than the default one I get broken time in control bar. I primarily used the Skin Generator .

## Steps to reproduce

To test you can create a skin there and try using it.

Explain in detail the exact steps necessary to reproduce the issue.
1. Generate a skin in Skin Generator and use it

## Results
![Screenshot_2019-11-16](https://user-images.githubusercontent.com/16373480/68990977-f5f7f100-0859-11ea-98b4-a5ac6a9eb096.png)

### Expected
The timer should be inline

### Actual
The timer displays vertically

### Error output
No programmatic error

#### videojs
what version of videojs does this occur with?
7.4.1
7.5.5
I checked on these
#### browsers
All
#### OSes
All (maybe)
### plugins
Seek Buttons

Generator https://www.scriptsmashup.com/Video_Skin_Generator/Videojs/videojs-skin-generator.html (Found in wiki)

**Comment by mister-ben** [comment]
Which skin generator? I'd suspect it's designed for an older version of Video.js

**Comment by Anan5a** [comment]
@mister-ben https://www.scriptsmashup.com/Video_Skin_Generator/Videojs/videojs-skin-generator.html

**Comment by mister-ben** [comment]
That is using a very old version, 5.11.9, so unfirtunately it's not surprising there are some issues. I tried a couple of their skins and saw some other problems but not yours with the time display, however.

**Comment by Anan5a** [comment]
@mister-ben  any way to fix it? Or any known generator for latest version?

**Comment by gkatsev** [comment]
I don't know of a generator for the new version of Video.js but we just released a couple of new themes along with our new blog post. More info here: https://mux.com/blog/the-new-video-js-themes/

**Comment by Anan5a** [comment]
@gkatsev  I'll definitely try

**Comment by gkatsev** [comment]
I'm going to close this issue for now. If we find a skin generator that works with the latest versions of Video.js we'll reply. If you have more questions feel free to ask here.
