### ISSUE TITLE
HTML5 seekable not matching player seekable

### ISSUE THREAD

**Issue by DaveStein** [videojs/video.js#6325]
## Description
`seekable` method from player does not give back same values as `seekable` property from video tag.

https://codepen.io/davestein/pen/VwwgGvB?editors=1011

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use codepen
2. Update manifest where & when commented (video broken at start on purpose)
3. When seeing video, do the code snippet in codepen console:

```js
// Run me in console after you see video in preview
var video = document.querySelector('video');
var timeRangesObject = video.seekable;
var timeRanges = [];
//Go through the object and output an array
for (let count = 0; count < timeRangesObject.length; count ++) {
    timeRanges.push([timeRangesObject.start(count), timeRangesObject.end(count)]);
}
console.log(timeRanges[0][1], player.seekable().end(0));
```

It appears that this doesn't always happen, but is increasingly likely with the player opened closer to start of stream / stream length is shorter.

### Expected
The end time should match every time.

### Actual
The time from the HTML5 property is usually seconds higher. It sometimes matches.

### Error output
N/A

#### videojs
Latest from your codepen
#### browsers
Latest Chrome & Safari at least
#### OSes
Tested in MacOS
### plugins
N/A for this codepen

**Comment by gkatsev** [comment]
This shouldn't be a problem. We don't ever rely on the video element's seekable when playing back HLS. We calculate the values manually from the video and audio data and this may not match up with how browsers calculate this value. I would suggest relying on the player methods for best compatability.
