### ISSUE TITLE
Is it possible to overlay VideoJS over a canvas?

### ISSUE THREAD

**Issue by immortal-sky** [videojs/video.js#6327]
I am making a media player in Electron and feel limited by HTML5 Video's current capabilities. I was looking into some solutions with WASM and using something like libVLC to draw onto a canvas. Is it possible to use VideoJS while targetting such a canvas, and just using callbacks for events such as play and pause with my custom implementation? Thanks.

Would the process be similar to this issue:
https://github.com/videojs/video.js/issues/2941

**Comment by gkatsev** [comment]
The answer is that you can. You can make a Video.js tech that is backed by a canvas. For an example, check out videojs-ogvjs and ogvjs itself: https://github.com/hartman/videojs-ogvjs and https://github.com/brion/ogv.js/.
If you need more help with making a tech, I would suggest browsing around the html5.js file, videojs-ogvjs, videojs-flash and videojs-youtube. https://github.com/videojs/videojs-flash https://github.com/videojs/videojs-youtube. Also, feel free to jump into our slack where we can answer questions there as well (http://slack.videojs.com).

Hope this helps.
