### ISSUE TITLE
Silvermine Chromecast plugin doesn't work in v7.7.0

### ISSUE THREAD

**Issue by DJ-PD** [videojs/video.js#6328]
## Description
Silvermine Chromecast plugin doesn't work in v7.7.0.
https://codepen.io/DJ-PD/pen/jdWWEg

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Under settings/html/head replace v7.6.6 to v7.7.0 both script and css `***SCRiPTS***/ ***STYLESHEETS***`
2. Test with above codepen e.g test 7
3. Chromecast icon disappear

### Expected
Chromecast icon present and function works.

### Actual
Chromecast icon disappear.

### Error output
n/a

## Additional Information
Will share this information with Silvermine Chromecast plugin team as well.
#### videojs
7.6.x and 7.7.0
#### browsers
Chrome version 78.0.3904.108 and probably more.
#### OSes
Windows 10, Android, iOS
### plugins
Silvermine chromecast

**Comment by gkatsev** [comment]
Thanks, looking like it broke when we were moving things around to reduce file size.

**Comment by gkatsev** [comment]
I can confirm that it is working again with 7.7.1.
