### ISSUE TITLE
Invalid HLS key at URL

### ISSUE THREAD

**Issue by saifeiLee** [videojs/video.js#6339]
## Description
Hello(Sorry for my bad English) . I want to play encrypted HLS stream. Here is my code:
```javascript
<!DOCTYPE html>
<html>

<head>
    <meta charset=utf-8 />
    <title>videojs</title>

    <link href="https://vjs.zencdn.net/7.6.5/video-js.css" rel="stylesheet">
    <script src="../node_modules/video.js/dist/video.js"></script>
</head>

<body>
    <h1>Video.js Example Embed</h1>
    <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="600" height="268"
        data-setup='{}'>
    </video>
    <script>
        let videojshls = videojs('my_video_1', {
            html5: {
                hls: {
                    overrideNative: true
                }
            },
        });
        videojshls.src({
            src: 'http://cvte-dev-public.oss-cn-hangzhou.aliyuncs.com/wenjibin-test/m3u8-3/jiami.m3u8',
            type: 'application/x-mpegURL',
            overrideNative: true,
        })
    </script>
</body>

</html>
```

The XHR request for key got the expected response:
![image](https://user-images.githubusercontent.com/28710808/69718505-7c111300-1149-11ea-873f-0dc4fb3e74f9.png)

But the video cannot played,.when I debug by breakpoint, I found an error:
![image](https://user-images.githubusercontent.com/28710808/69718355-1886e580-1149-11ea-8ce1-fbe16ea77b1f.png)
In fact, I can play this hls stream by hls.js. Any help please? Thanks~~~!!!

**Comment by gkatsev** [comment]
Neither the ts segment nor the key load for me when trying it in Video.js or hls.js demo pages.

**Comment by saifeiLee** [comment]
I found the reason is we restricted `response.byteLength !== 16` in source code. But the  response of segment in my demo is 28.
![image](https://user-images.githubusercontent.com/28710808/70031135-933a7f80-15e5-11ea-8a6b-64c01ae31474.png)

**Comment by saifeiLee** [comment]
> I found the reason is we restricted `response.byteLength !== 16` in source code. But the response of segment in my demo is 28. Could you please explain to me why the byteLength should be 16? Thanks~
> ![image](https://user-images.githubusercontent.com/28710808/70031135-933a7f80-15e5-11ea-8a6b-64c01ae31474.png)

I got it. AES-128 key must be 16 byte.
