### ISSUE TITLE
Buttons not in place on IE11

### ISSUE THREAD

**Issue by dgroh** [videojs/video.js#6343]
## Description
The native videojs buttons of control-bar are not in place on IE11 **Version:** 11.0.9600.19541

It works in Edge and other browser versions.

## Additional Information

![image](https://user-images.githubusercontent.com/16785357/69968608-062af400-151b-11ea-88da-928c9ea74a25.png)

**VideoJs Version**: 7.6.5
**IE11 Version**: 11.0.9600.19541

**Comment by mister-ben** [comment]
That's not the standard Video.js skin so hard to say from a screenshot what might be missing or conflicting in your custom CSS.

**Comment by gkatsev** [comment]
I've also just confirmed that the default Video.js skin functions correctly. If you have a reduced test case, we may be able to help but otherwise, it's likely some interaction of your custom styles.
