### ISSUE TITLE
how to disable plugin in brightcove video player index.min.js file 

### ISSUE THREAD

**Issue by bgity** [videojs/video.js#6344]
I am using brightcove player for palying video in samsung smart tv. I am using brightcove cloud videos and cloud js file i.e. index.min.js which is configure with player.

I am facing problem **Cannot read property 'getChild' of undefined**.This is happen bcz on cloud js file having plugin that get conflict with my player code.

So is there any way to disable plugin?

I us player.advanced().dispose(); but its not working.

**Comment by gkatsev** [comment]
I'm not really sure what's "advanced()" or what plugin you're referring to but if it's related to a Brightcove player you should reach out to Brightcove support.
As for plugins, turning off plugins depends on the plugin in question.
