### ISSUE TITLE
vue-cli3 after webpack build: progressEvent.target= null, in function getProgressStats

### ISSUE THREAD

**Issue by diveDylan** [videojs/video.js#6347]
video.js 7.6.6
umd/es/cjs version works in development env, but after build the error comes in function getProgressStats

**Comment by gkatsev** [comment]
progressEvent and getProgressStats come from https://github.com/videojs/http-streaming/blob/master/src/media-segment-request.js#L46-L62. Though, everything seems in order there. Not sure what the error is about. Is this happening at build time or run time? If it's at runtime, can you create a reduced test case?

**Comment by diveDylan** [comment]
@gkatsev in the runtime(video.js ^7.6.6), when hls stream keep pending or with a status 404, it happened, but in the development env works well. I use the cnd resource it works well. Maybe it is a problem with webpack config.Sorry, private project can not provide for a test case
