### ISSUE TITLE
Unable to modify headers on media requests

### ISSUE THREAD

**Issue by michal-lipski** [videojs/video.js#6348]
## Description

I need to play a video from an endpoint that needs token authentication.
Video is in type: "video/webm". When I am trying to set headers using:

`videojs.Hls.xhr.beforeRequest = function(options) {
    options.headers = options.headers || {};
    options.headers.Authorization = 'Bearer token'
    return options;
  };`

`beforeRequest` callbac is not executed and headers are not set.

http://plnkr.co/edit/TVY1cDD49kJgZNZBS2zP?p=preview

I know that using `videojs.Hls.xhr` we are supposed to be modifing XHR request, but is there a way to modify a request for WebM file that is using media type reqyest?

![image](https://user-images.githubusercontent.com/758497/70065133-e19e4d00-15ea-11ea-897e-65952f436074.png)

### Expected
The headers are added to the all types of request

### Actual
No way to append headers to the media request

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.5.5

#### browsers
chrome

**Comment by gkatsev** [comment]
The beforeRequest method only works for HLS or DASH media. When playing back a regular webm, we fallback to the browser and it doesn't provide a way to fiddle with headers.

**Comment by michal-lipski** [comment]
Thanks for answer. Is this a limitation of webm, that we cannot tamper with headers or it can be implemented in the future?

**Comment by gkatsev** [comment]
This is a platform limitation. Since we hand over loading of the media to the browser in the case of webm, we have no control over being able to set headers.
