### ISSUE TITLE
SCTE-35 Digital Program Insertion Cueing Message

### ISSUE THREAD

**Issue by vitaliy-shahanyants** [videojs/video.js#6349]
Hello,

This is more of a question than an issue, but I was wondering if vidoejs supports SCTE-35 (Digital Program Insertion Cueing Message)?

If yes, are there examples?

If no, is there a contribution library I can use?

**Comment by anagonm** [comment]
@vitaliy-shahanyants Hi Vitaliy did you find out about any libs or support or documentation around this SCTE support ?

thanks
