### ISSUE TITLE
VideoJs does not generate the url BLOB

### ISSUE THREAD

**Issue by Lestadt** [videojs/video.js#6350]
Hello, I used this player in the past, I have decided to use it in one of my projects and I have installed it in a test installation, everything worked fine, see that VideoJs generated a url: blob for the video that was played and that is what I expected and that is what I wanted, however, I do not know why or how this url has stopped generating and the url of the original video is shown .. I did not touch anything of the code, I was just manipulating the css to center and change the play button, I have changed it back to its original state, as I put it the first time, I have even tried other versions, but the blob url for the video is no longer generated. No errors are displayed on the console and the video plays correctly. As I said before, I have tried it in a test installation, this installation does not have any cache system or anything to optimize the ccs or js, everything is intact. The code that I used took it from its website, it is a simple insert code that uses cdn, it looks more or less like this:

```
<link href="https://vjs.zencdn.net/7.5.5/video-js.css" rel="stylesheet" />
<script src="https://vjs.zencdn.net/7.5.5/video.js"></script>

  <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="929"
    height="465"
    poster="http://mytestside.com/my-img-cover.jpg"
    data-setup="{}"
  >
    <source src="http://mytestside.com/my-video.mp4" type="video/mp4" />

  </video>
```

I would like VideoJs to generate the url: blob again just as it did the first time I implemented it, what should I do? Any suggestions?

**Comment by mister-ben** [comment]
A blob URL is not used for MP4, only HLS and DASH.

**Comment by Lestadt** [comment]
Thank you for responding and for the clarification ... but, then, is it that at first, if a blob url was generated, using the same code I published and a mp4 video?

**Comment by mister-ben** [comment]
I don't know how that could be possible with MP4
