### ISSUE TITLE
How to prevent big Play Button default action

### ISSUE THREAD

**Issue by willy025896** [videojs/video.js#6351]
I want to do some action when the big play button clicked,and i don't want the video play immediately
I've tried like this: 

```
player.bigPlayButton.on('click',function(e){
      WhatIWant();
      e.preventDefault();
    });
```
but it didn't work

**Comment by mister-ben** [comment]
Remove the standard event listener before you add yours with `off('click')`.

**Comment by willy025896** [comment]
@mister-ben  thanks it works
