### ISSUE TITLE
Can't player rtmp video

### ISSUE THREAD

**Issue by Sayid1** [videojs/video.js#6352]
## Description
[example](https://codesandbox.io/s/youthful-kilby-uuut4)

## Steps to reproduce
Click the play button

### Expected
It can play RTMP normally

### Actual
can't

### Error output
No error messages

### plugins
videojs-flash

**Comment by mister-ben** [comment]
Your player is below the 300 pixel threshold that will stop Chrome from running Flash even if the user has enabled it, so that could be an issue, but I can't play that stream URL on any player.

**Comment by Sayid1** [comment]
Sorry, Please use this url rtmp://148.70.34.168:1935/live/openUrl/EJ5OJb2 @mister-ben

**Comment by mister-ben** [comment]
This also doesn't play in other players.

I'd suggest using a modern format such as HLS instead. Even if you get your RTMP stream working, increasingly few users' browsers run Flash and Flash reaches end of life next year.

**Comment by TTimage** [comment]
I commit this rpoblem too

**Comment by gkatsev** [comment]
You need to make sure that the player is above the 300pixel size threshold and then you need to separate connection url the stream name with `&` as outlined here https://docs.videojs.com/tutorial-faq.html#q%3A-how-can-i-play-rtmp-video-in-video.js%3F.
In addition, as @mister-ben said, browsers are making it harder and harder to use Flash and Flash itself reaches end of life next year. We highly recommend switching to HLS or DASH, perhaps via nginx-rtmp.

**Comment by theprimone** [comment]
@mister-ben Something goes wrong? I run this code below.

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>video.js</title>
  <link href="https://vjs.zencdn.net/7.5.4/video-js.css" rel="stylesheet">
  <script src="https://vjs.zencdn.net/7.5.4/video.js"></script>
  <script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script>
</head>

<body>
  <video id="my-player" class="video-js" controls width="640px" height="400px">
    </source> -->
    <source src="rtmp://fms.105.net/live/rmc1" type="rtmp/mp4">
    <p class="vjs-no-js">not support</p>
  </video>
  <script type="text/javascript">
    window.onload = () => {
      console.log("window.onload")
      var player = videojs('my-player', {
        techOrder: ['flash'],
      },
        function onPlayerReady() {
          videojs.log('Your player is ready!');

          // In this context, `this` is the player that was created by Video.js.
          this.play();

          // How about an event listener?
          this.on('ended', function () {
            videojs.log('Awww...over so soon?!');
          });
        });
    }
  </script>
</body>

</html>
```

this RTMP url is work in https://www.hlstester.com/ , but this demo is not work, and function `onPlayerReady` is not executed to videojs.log.

**Comment by theprimone** [comment]
> @mister-ben Something goes wrong? I run this code below.
> 
> ```
> <!DOCTYPE html>
> <html lang="en" dir="ltr">
> 
> <head>
>   <meta charset="utf-8">
>   <title>video.js</title>
>   <link href="https://vjs.zencdn.net/7.5.4/video-js.css" rel="stylesheet">
>   <script src="https://vjs.zencdn.net/7.5.4/video.js"></script>
>   <script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script>
> </head>
> 
> <body>
>   <video id="my-player" class="video-js" controls width="640px" height="400px">
>     </source> -->
>     <source src="rtmp://fms.105.net/live/rmc1" type="rtmp/mp4">
>     <p class="vjs-no-js">not support</p>
>   </video>
>   <script type="text/javascript">
>     window.onload = () => {
>       console.log("window.onload")
>       var player = videojs('my-player', {
>         techOrder: ['flash'],
>       },
>         function onPlayerReady() {
>           videojs.log('Your player is ready!');
> 
>           // In this context, `this` is the player that was created by Video.js.
>           this.play();
> 
>           // How about an event listener?
>           this.on('ended', function () {
>             videojs.log('Awww...over so soon?!');
>           });
>         });
>     }
>   </script>
> </body>
> 
> </html>
> ```
> 
> this RTMP url is work in https://www.hlstester.com/ , but this demo is not work, and function `onPlayerReady` is not executed to videojs.log.

It's embarrassed that I used in `file:///C:/path/to/player.html` and it's failed to play. With the http server, It's works \_(:3J∠)\_
