### ISSUE TITLE
Live Captions Failing on Refresh

### ISSUE THREAD

**Issue by DaveStein** [videojs/video.js#6353]
## Description
My caption data is properly embedded with fragmented MP4. I did not know that videos would automatically read the manifest information and show captions. I hadn't seen it work an entire day. I came to work and there they were. I realized that if I refresh a video after ~3 minutes, it won't work. I think it has to do with the way it tries to download all the fragments from the manifest on reload.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open a browser window with player. 
2. Start streaming valid IMSC1 caption data
3. See captions come in
4. Watch for ~3 minutes
5. Open new browser window
6. See that captions aren't showing in new window
7. See that captions are still showing on old window

### Expected
The captions did not show up.

### Actual
The captions should show

### Error output
None

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with? 7.6.5
#### browsers
what browser are affected? tested latest chrome & firefox
#### OSes
what platforms (operating systems and devices) are affected? on mac currently
### plugins
are any videojs plugins being used on the page? If so, please list them below.
```
    "videojs-contrib-quality-levels": "^2.0.9",
    "videojs-dvr": "^1.4.0",
    "videojs-errors": "^4.3.0",
    "videojs-hls-quality-selector": "^1.1.0"
```

**Comment by DaveStein** [comment]
My options btw:
```
export const VIDEO_JS_CONFIG = {
  controls: true,
  autoplay: true,
  playsinline: true,
  preload: 'auto',
  fullscreen: true,
  html5: {
    nativeTextTracks: false,
    preloadTextTracks: false
  },
  liveui: true, // @todo: only use for live videos
  controlBar: {
    children: {
      playToggle: true,
      progressControl: true,
      customControlSpacer: true,
      volumePanel: true,
      fullscreenToggle: true
    }
  }
};
```

I tried without the `html5` options first, and then the second. I had seen with preload, a very large amount of Fragment calls are made from the manifest so I thought it might overload when the stream gets too long.

**Comment by DaveStein** [comment]
One more note: The failures show manifest calls being made, but no fragment calls to get the actual caption data. Obviously since the original window is still showing captions, the manifest data must be fine.

**Comment by DaveStein** [comment]
Another test run took 4.5 minutes before refresh caused captions to fail

**Comment by DaveStein** [comment]
More info! Rewinding with DVR shows captions again

**Comment by gkatsev** [comment]
Video.js doesn't support IMSC captions itself. Are you playing back in Safari? That's the only browser that I know supports IMSC captions inside of fmp4 segments.
Is this HLS content? Kind of hard to help out without a sample.

**Comment by DaveStein** [comment]
This is an HLS example. I know that Azure Media Player handles these captions. Are you saying I should create a manifest with live captions and upload all of the various files here? Not sure how I would do that well considering the manifest links out to new URLs per segment so that's quite a bit... and that's binary which isn't the best thing to upload places.

**Comment by gkatsev** [comment]
https://github.com/videojs/http-streaming/pull/741#issuecomment-593599766

**Comment by johndeu** [comment]
Not sure why this Issue is marked as closed.  Maybe it should be re-titled to Video.js does not support IMSC1 fragments in CMAF per the ISO 14496 part 30 specification that is supported by Apple.
