### ISSUE TITLE
'zh-Hant)*.json'' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ajingopi-bridge** [videojs/video.js#6355]
## Description
'zh-Hant)*.json'' is not recognized as an internal or external command,
operable program or batch file.

## Steps to reproduce
1. clone the repository, and move into that directory
2. run npm install or npm ci to install all necessary packages
3. run npm start to start the local server

### Expected
open http://localhost:9999/sandbox/live.html in a web browser

### Actual
Not executed

### Error output
'zh-Hant)*.json'' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! video.js@7.7.3 watch:lang: `chokidar --initial 'lang/**/!(zh-Hans|zh-Hant)*.json' -c 'npm run build:lang'`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the video.js@7.7.3 watch:lang script.

![image](https://user-images.githubusercontent.com/46883176/70700270-7b06e680-1cf0-11ea-841f-8cd6926d4484.png)

#### videojs
7.7
#### browsers
git bash
#### OSes
Windows 10
### plugins
NA

**Comment by gkatsev** [comment]
Did you run this in `cmd.exe` or powershell? I assume that command won't work there right now. I would suggest trying out WSL or just disable that command for now.

**Comment by ajingopi-bridge** [comment]
I tried git bash and power shell. I have found other ways to fulfill my requirement so you might close this issue.

**Comment by etomProductions** [comment]
@ajingopi-bridge
Would you please advise how you solve it?

Thank you

**Comment by ajingopi-bridge** [comment]
@etomProductions I didn't get a solution for this..!!
But you might remove this porion from your package.json and try, not sure though
`'lang/**/!(zh-Hans|zh-Hant)*.json'`

**Comment by etomProductions** [comment]
Thank you @ajingopi-bridge,

In node 14 I remove it as you mention and its work fine., But for me as it is I downgraded to node 10 and its now working without any issue. However, 

Thank you so much for the answer.

**Comment by lolPlatinumPlayer** [comment]
> @etomProductions I didn't get a solution for this..!!
> But you might remove this portion from your package.json and try, not sure though
> `'lang/**/!(zh-Hans|zh-Hant)*.json'`

it work, then I see `Error: Can't find stylesheet to import`...  - -||

I tryed on node12.16.2 and node 10.23.3 on win10.
