### ISSUE TITLE
Accessing the Src Object

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#6356]
Hi All,

I am just curious if there is a way to access the src object from within the loadstart event as we are dynamically setting the src.

for instance something like this;

~~~
var player = videojs('player', {});

player.src({
    type: 'video/mp4',
    src: 'https://example.com/myvideo.mp4',
    bif: 'https://example.com/myvideo.bif'
});

// EVENTS  
player.on('loadstart', function(_event) {

    if (player.src.bif) {
        //Do something with the bif if its set? This can the run every time set src is called 
    }

});
~~~

**Comment by mister-ben** [comment]
[Middleware](https://docs.videojs.com/tutorial-middleware.html#setsource) lets you access or modify the source before it is loaded.

    videojs.use('*', function(player) {
      return {
        setSource: function(srcObj, next) {
          // Do something with srcObj and pass it on 
          next(null, srcObj);
        }
      };
    });

**Comment by samueleastdev** [comment]
Thanks @mister-ben this is super handy ;) just need to find the best way to implement it in a plugin. 

~~~
var player = videojs('player', {});

player.src({
    type: 'video/mp4',
    src: 'https://example.com/myvideo.mp4',
    bif: 'https://example.com/myvideo.bif'
});

videojs.use('*', function(player) {
    return {
        setSource: function(srcObj, next) {
            // Do something with srcObj and pass it on 

            if (srcObj.bif) {
                console.log('loadBif', srcObj);
            }
            next(null, srcObj);
        }
    };
});
~~~

**Comment by gkatsev** [comment]
Middleware works, in addition `player.currentSource()` will give you back the source object of the chosen source whenever you want.

**Comment by samueleastdev** [comment]
Hi @gkatsev 

Thanks for the suggestion player.currentSource() with only return the video source not the whole object.

I am working on a plugin to add bif images to the progress bar.

Example here: https://output.jsbin.com/semolid

Question here. https://stackoverflow.com/questions/57711372/html-video-fast-scrubbing

Because we do not want the player to have to be disposed of everytime we feel it makes sense to be able to update the UI with a new bif on every set source call by passing the bif url along with the src object.

Middleware seems like the best option for this.

**Comment by gkatsev** [comment]
`player.currentSource()` returns the object given to it. For example:
```
> player.src({src: "http://vjs.zencdn.net/v/oceans.mp4", type: "video/mp4", foo: "bar"});
> videojs.players.vjs_video_3.currentSource()
< {src: "http://vjs.zencdn.net/v/oceans.mp4", type: "video/mp4", foo: "bar"}
```

However, yes, it's likely that middleware serves your needs better.

**Comment by samueleastdev** [comment]
Apologies @gkatsev I am talking nonsense.
~~~
player.currentSource()
~~~
Does return the full object I thought I have tried that already thanks both either of these will work great.

**Comment by gkatsev** [comment]
Yeah, might be a bit confusing since we have `player.src()`, `player.currentSrc()`, and `player.currentSource()`. There's also `player.currentSources()` too, which will give you a list of all sources provided.

**Comment by samueleastdev** [comment]
Yep I've been trying this one player.currentSrc()

Thanks for the info ;)

**Comment by gkatsev** [comment]
Hehe, you're welcome.
