### ISSUE TITLE
Progress bar length miscalculation

### ISSUE THREAD

**Issue by hlibmykhailov** [videojs/video.js#6359]
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use any short video or audio (1-2 seconds)
2. Play the video or audio and watch for progress bar.
3. Progress bar finishes at ~90-95% of progress length (but it shows 100% aria-valuenow)

### Expected
I expect to see a full completed progress bar(100%).

### Actual
Progress is not filled in completely if video or audio is too short (1 second to 2-3 seconds) when it should be 100%.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.3+
#### browsers
All
#### OSes
All
### plugins
videojs-contrib-quality-levels
videojs-http-source-selector

**Comment by gkatsev** [comment]
Is the 2-3 second video HLS or just an mp4? Are you able to provide the sample video? Thanks.

**Comment by hlibmykhailov** [comment]
> Is the 2-3 second video HLS or just an mp4? Are you able to provide the sample video? Thanks.

As main format we using HLS (the most important for us), but also we have mp4 sources. 
I`m using this video. Its just simple example, but we converting it in .m3u8 and mp4 on AWS side.  As main source we using .m3u8. 
https://drive.google.com/open?id=17aPOPosQLJ2h-DpHNTscElDTCqjuTQJZ

**Comment by mister-ben** [comment]
I don't see an issue playing that MP4, but note it's video track is 21 ms shorter than the audio track. That might be causing mismatched durations in your HLS.
