### ISSUE TITLE
Picture in picture

### ISSUE THREAD

**Issue by Histonic** [videojs/video.js#6362]
Hi, I've just set video js on my website and chosen the Fantasy theme, but it doesn't display any picture in picture button, whereas it's displayed in this theme on video js mainpage...
Is it possible to activate it ?
Thank you

PS I'm French

**Comment by gkatsev** [comment]
Which browser were you testing against? The PiP button will only currently show up in chrome.

**Comment by Histonic** [comment]
Thank you, well actually in in Chrome.

**Comment by Histonic** [comment]
![image](https://user-images.githubusercontent.com/59024679/71104094-8c059b00-21bb-11ea-80d9-39041b0b3b79.png)

**Comment by MarioEisold** [comment]
Hello, I am having the same issue. The PIP button appears in all the demos shown on videojs.com. However, even if you follow the instructions and set up an example (with a skin/theme), no PIP button is shown when using chrome. This makes me wonder if I am missing any libraries or plugins. I could not find any documentation on how to set this this up or troubleshoot.

**Comment by Histonic** [comment]
As for me, I used it just following the steps described here https://videojs.com/getting-started/
But maybe we have to replace the targetted files by newest versions ? Which ones ?

**Comment by gkatsev** [comment]
Ah, yeah, looks like that is hard-coded into 7.5.5, you should use 7.6.6 instead. 7.6 added the PiP button.

**Comment by Histonic** [comment]
Super ! Well... I've had a look at the files by there, but, I can't find which ones I should include instead of those I had ? Too many directories...

**Comment by Histonic** [comment]
Great ! Thank you !
