### ISSUE TITLE
How to play from a certain timecode from a link ?

### ISSUE THREAD

**Issue by Histonic** [videojs/video.js#6363]
Hello,
I need to start the play of a video from a certain timecode, but from a link in the page. So far I had this short code I used with a standard html `<video>` element and that used to work :

```
<script type="text/javascript">
		var lecteur;
		function timecode(secondes) {
		    lecteur = document.getElementById("mavideo");
		    lecteur.currentTime = (secondes);
		    lecteur.play();
		}
	</script>
```

and the link :
`<a href=#mavideo onclick="timecode(60)">play from 1 min</a>`

I just copyed it after using video.js and... it doesn't work.
Can anyone help me please ?

**Comment by mister-ben** [comment]
Use Video.js's API - https://docs.videojs.

    lecteur = videojs.getPlayer("mavideo");
    lecteur.currentTime(secondes);
