### ISSUE TITLE
Hello, How to use the player's method: getCache

### ISSUE THREAD

**Issue by diveDylan** [videojs/video.js#6364]
> getCache()
Get object for cached values.

> Defined in https://github.com/videojs/video.js/blob/master/src/js/player.js line number: 1156

I have a hls live video, i search some way to cache the live video with video player.  I see the method getCache,just some words show on doc,  how to use the cache values.

<img width="668" alt="WX20191219-143014@2x" src="https://user-images.githubusercontent.com/28706090/71150305-20c7d180-226c-11ea-81b3-eecae5ed99e1.png">

**Comment by mister-ben** [comment]
`getCache()` returns the cache of the values which are used internally for performance rather than querying the video element or other tech repeatedly. It's nothing to do with caching video data.

**Comment by gkatsev** [comment]
Yeah, it probably should've never been public but... ¯\_(ツ)_/¯
You probably want to use something like `player.currentSource()` or `player.currentSources()`.
