### ISSUE TITLE
videojs crop frame 

### ISSUE THREAD

**Issue by SourceCodeZone** [videojs/video.js#6369]
Hi I just want to know that, is it possible  to crop the video frame based on the rectangle given. I actually I have to dipspaly only part of the video, I have checked the video.js file but could not find the section where I can get each frame before playing.

**Comment by gkatsev** [comment]
We don't have anything built-in for this but you can likely achieve this with CSS by targeting the `.vjs-tech` element and resizing it based and positioning it within the `.video-js` element.

**Comment by SourceCodeZone** [comment]
Thanks for the hint, so video js library do not process frame, like in the case of hls stream the html video not support HLS, where as videojs do it. I thought the  decoding is done by videojs and I can access frame there.

**Comment by gkatsev** [comment]
Video.js does allow playback of HLS but the processing doesn't give access to the raw video. We unpack the TS segments and repackage them up in fragmented mp4s for the browser to play back via [MSE](https://en.wikipedia.org/wiki/Media_Source_Extensions). Ultimately, it's the browser that ends up playing the encoded video data.

**Comment by SourceCodeZone** [comment]
Thanks for the clarification, I will try the CSS way.
