### ISSUE TITLE
Playready not working v7.6.6

### ISSUE THREAD

**Issue by ZHAJOR** [videojs/video.js#6374]
## Description
I'm upgrading from videojs 5 to 7.6.6
I also included contrib-eme-3.5.4 and http-streaming-1.10.5
Everything is working fine, HLS no DRM, HLS DRM, DASH DRM on safari/Chrome/Firefox for Mac/linux/W10... except DRM on Edge or IE11 (W10).

## Steps to reproduce
Try to play a DRM encrypted DASH manifest (no HDCP restriction) on Edge/IE11 (Windows 10)
```
        player.src({
            src: dash_obj.url,
            type: 'application/dash+xml',
            keySystems: {
                'com.widevine.alpha': {
                    url: wv_license_server_url,
                    licenseHeaders: headers

            },
                'com.microsoft.playready': {
                    url: pr_license_server_url,
                    licenseHeaders: headers
                }
            }
        })
```

### Expected
It should play.

### Actual
CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED
The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
I just tried with videojs 6.13 (keeping same http-streaming and contrib-eme) and it's playing on IE11 but not on Edge, still the code 4.
I already checked the issues on the different github projects, but nothing yet. I'm still investigating, if I find anything new I will add it here.

Thanks, and Happy Christmas!

**Comment by ZHAJOR** [comment]
So I tested multiple v7/v6 and it's not playing at all on Edge, IE11 is loading the movie, playing the first chunk then stalling. I can fast-forward/rewind, the image will be updated but it's not playing.

I created a really light project on the side with just videojs to avoid any side effect.

**Comment by gkatsev** [comment]
It's likely that you need to specify the audio and video content types to be used. Some browsers can't pick up the content type automatically and require to be told for things to work properly. For example:
```js
        player.src({
            src: dash_obj.url,
            type: 'application/dash+xml',
            keySystems: {
                'com.widevine.alpha': {
                    "audioContentType": "audio/mp4; codecs=\"mp4a.40.2\"",
                    "videoContentType": "video/mp4; codecs=\"avc1.42c01e\"",
                    url: wv_license_server_url,
                    licenseHeaders: headers

            },
                'com.microsoft.playready': {
                    "audioContentType": "audio/mp4; codecs=\"mp4a.40.2\"",
                    "videoContentType": "video/mp4; codecs=\"avc1.42c01e\"",
                    url: pr_license_server_url,
                    licenseHeaders: headers
                }
            }
        })

```

**Comment by ZHAJOR** [comment]
Thanks for the example!
It was working fine without having to add the audio/video type with videojs5.
I managed to  make it work by adding the option
`html5.hls = { overrideNative: true };`
when initializing the player.
I don't understand why this hls option is impacting the playback considering the type of the source has been specified ('application/dash+xml').

Also with overrideNative enabled I'm not able to play on safari (Fairplay).
Anyway, the fix I'm choosing is to conditionally enable overrideNative for anything except safari.

If you think there is a bug I can create the issue on http-streaming's repo.
If not, I'm curious, do you have an explanation?

**Comment by gkatsev** [comment]
Safari cannot play back widevine or playready. Yeah, I'm surprised that overrideNative was required. You can use `overrideNative = !videojs.browser.IS_ANY_SAFARI;` instead to only override native on non-safari browsers.

**Comment by ZHAJOR** [comment]
I know for safari, I tried to play with Fairplay, but it's in the doc that overrideNative should be false in this case; I just wanted to pointed it out if someone else is reading this issue.

Already in place, thanks!

Closing this issue and opening a new one on http-streaming for the overrideNative strange behavior.
