### ISSUE TITLE
Rtmp stream is not playing in angular

### ISSUE THREAD

**Issue by helxsz** [videojs/video.js#6379]
I am using angular 7 and video.js to build a simple app to receive the rtmp stream, the rtmp stream ‘**rtmp://58.200.131.2:1935/livetv/hunantv’** can be played in the VLC player. But it can’t play any rtmp stream in the angular app, the code is shown below, can anyone help me how to debug it?

```
<video id="my-video" class="video-js vjs-default-skin vjs-big-play-centered"
controls preload="auto" width="360px" height="270px"
data-setup="{}" autoplay>

<source [src]="safeUrl" type='rtmp/flv'>

<p class="vjs-no-js">
    To view this video please enable JavaScript,
    and consider upgrading to a web browser that
  <a href=" " target="_blank">
    supports HTML5 video</a >
</p >

```

```
constructor(
            private sanitizer: DomSanitizer
            ) {

  this.getUrl(this.url);

} 
url = 'rtmp://58.200.131.2:1935/livetv/hunantv'; safeUrl: any;

getUrl(url: string) {
  this.safeUrl = this.sanitizer.bypassSecurityTrustUrl(url);  
}
```

**Comment by mister-ben** [comment]
Do you have the Flash tech added? Can you play it outside of Angular?

**Comment by helxsz** [comment]
I can play the rtmp stream outside angular, it is playing well in vlc player.  

I don't think flash tech added, what should I do

**Comment by gkatsev** [comment]
You need to make sure to include the videojs-flash tech. In addition, the player must be large enough for browsers like Chrome to let flash be allowed to play, 360x270 is way too small. Also, you and your users will be forced to allow flash each time they go to the page.

Additionally, Video.js expects the stream name and connection url to be separated by `&`. See https://docs.videojs.com/tutorial-faq.html#q%3A-how-can-i-play-rtmp-video-in-video.js%3F
