### ISSUE TITLE
Quality selector not displaying for Mpeg Dash videos in Video JS 7 player

### ISSUE THREAD

**Issue by AsifContus** [videojs/video.js#6380]
Hi Friends!
I am using Videojs version 7. I am able to play the mpd video in the player. But its quality like 360p, 720p are not displayed. Whereas quality selectors are displayed for m3u8 video. Any help would be appreciated.

## Steps to reproduce
1. Initiate the video js player
2. Pass the mpd url
3. check the quality selector. It is not displayed.
4, Please pass and check m3u8 url, and check it quality selector is displayed.

### Expected
I want to see the quality selectors displayed for the mpd video. I should be able to switch between the quality selectors.

### Actual
Previously I was using only m3u8 video source, which played well with the presets (i.e.,) Quality selector.

### Error output
Videos are playing but without presets.

### plugins
Videojs http-streaming
Videojs dashjs

**Comment by gkatsev** [comment]
Video.js doesn't ship with a quality selector. If you're using a particular plugin, I would recommend opening an issue against the plugin you are using.
Thanks.

**Comment by priya1890** [comment]
Hi, 
Am also facing the same issue and my requirement matches the one stated above. For mod format the 
player.qualityLevels(), is empty

**Comment by MRawhani** [comment]
I had the same problem, it was related to the source of the mpd file.
I installed the plugin httpSourceSelector, and it worked perfectly.

**Comment by sahilkashyap64** [comment]
> Hi,
> Am also facing the same issue and my requirement matches the one stated above. For mod format the
> player.qualityLevels(), is empty

here's a demo player video.js demo-player with dash quality selector https://sahilkashyap64.github.io/dash-player-buydrm/index.html
