### ISSUE TITLE
Fairplay can't play a second video: Code:3 MEDIA_ERR_DECODE

### ISSUE THREAD

**Issue by ZHAJOR** [videojs/video.js#6382]
## Description
The issue is happening with a very basic homemade playlist system.
To switch, I simply do a player.reset(), then set a new source.
All the videos are DRM protected (without HDCP enforced).
Everything is working fine for DASH, each time I set a new source a license request is fired.

Only the first video is playing for HLS, if I set another one it's stalling for 20-30s, then Code:3.
The 20-30s are explained by the player trying all the renditions.
I started to investigate the videojs-eme's code, "webkitneedkey" is only fired for the first video, that would explain why getContentId and getLicense are never called afterwards.
It's like I need to reset something else, any idea?

## Steps to reproduce
1. Init the player and eme.
2. Set a source (DRM)
3. It's playing fine.
4. Set a new source (DRM)
5. No license request, getContentId and getLicense are never called.
6. After 20-30s: Code:3 MEDIA_ERR_DECODE error

### Expected
The video should be playing.

### Actual
Code:3 MEDIA_ERR_DECODE error

#### videojs
7.6.6
#### browsers
Safari 13
#### OSes
MacOS 10.15 Catalina
### plugins
eme

**Comment by ZHAJOR** [comment]
I want to add that even a player.reset() isn't helping in this situation.
So it's not just a playlist issue, it looks like once it played a DRM movie then it's not requesting anything again.

The last solution I see right now is to try to remove the player from the dom and create a new one.

Any better idea?

**Comment by joopvanduin** [comment]
Hi

I have the same problem. ZHAJOR did you fix it?

Could you please tell / show me how

All the best
Joop

**Comment by ZHAJOR** [comment]
Hi Joop,

Sadly I didn't have the time to look into it.
What I did as a really bad hotfix was to refresh the page with the new video.

I think the issue is coming from the videojs-contrib-eme, if I well remember there is even a comment in the code talking about resetting the session properly. If you have some time maybe you can try to dig into that. On my own it could take multiple months before I dive back into this issue.

Good luck,

**Comment by joopvanduin** [comment]
Hi

Thank you for the quick reply! 

Will try to fix and keep you up to date.

All the best
Joop

**Comment by nicootto** [comment]
Hi @joopvanduin,

Did you find any solution?

Regards,
Nico

**Comment by ZHAJOR** [comment]
Hey @nicootto,
Are you using the latest version of eme?

**Comment by joopvanduin** [comment]
Hi Nico

No I didn't. In the end I 'solved' it by disposing the current player and adding a new one to the DOM...

All the best
Joop

**Comment by nicootto** [comment]
@ZHAJOR,

I'm have the following versiones:
- videojs: "7.12.2"
- videojs-contrib-eme: "3.8.1"

I just realised that my problem here is a bit different. I'm playing dash+widevine.

Steps:
1. Init the player and eme.
2. Set a source (dash + widevine)
3. It's playing fine.
4. Reset de player
5. Set a new source (dash + widevine
6. No license request. Eme activeSrc is the one for the first source, not the second one. Player keeps "loading" forever, no error is throw. 

It's working as expected if I don't reset the player before changing the source. 
I'll dig deeper on why the activeSrc is not refreshed after the player is reset and open a new thread if I find something.

**Comment by ZHAJOR** [comment]
@nicootto 
A call to reset resets the tech (https://docs.videojs.com/player.js.html#line3515) and if we look at what eme is doing when being initialized (https://github.com/videojs/videojs-contrib-eme/blob/main/src/plugin.js#L209) and more especially with Widevine (https://github.com/videojs/videojs-contrib-eme/blob/main/src/plugin.js#L272).
I think in your case eme isn't listening for 'encrypted' anymore which explains why it's not requesting a license.

I just look into the sources but this will help you.

**Comment by Chill-Studio** [comment]
Any news on that ?

The same problem occurs with widevine, it's really critical , we can't reset a stream when using drm basically. :/

Really easy to reproduce.

### Step 1 : Init a player

Have a video-js element in your dom

```
 <video
                        id="videoContainer"
                        className="video-js"
                        ref={this.setVideoRef}
 />
```

Then create an instance of videojs

```
var player = videojs("videoContainer", {
            controls: true,
            autoplay: false,
            preload: "auto",
            fluid: true,
            liveui: true,
        })
```

### Step 2 : enable DRMs

`player.eme();`

### Step 3 : Load a source with drm (this one is public)

```
player.src({
                src: "https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd",
                type: "application/dash+xml",
                keySystems: {
                    "com.widevine.alpha": {
                        url: "https://drm-widevine-licensing.axtest.net/AcquireLicense",
                        licenseHeaders: {
                            "X-AxDRM-Message":
                                "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImZpcnN0X3BsYXlfZXhwaXJhdGlvbiI6NjAsInBsYXlyZWFkeSI6eyJyZWFsX3RpbWVfZXhwaXJhdGlvbiI6dHJ1ZX0sImtleXMiOlt7ImlkIjoiOWViNDA1MGQtZTQ0Yi00ODAyLTkzMmUtMjdkNzUwODNlMjY2IiwiZW5jcnlwdGVkX2tleSI6ImxLM09qSExZVzI0Y3Iya3RSNzRmbnc9PSJ9XX19.FAbIiPxX8BHi9RwfzD7Yn-wugU19ghrkBFKsaCPrZmU",
                        },
                    },
                },
            });
```

### Step 4 : play the stream

`player.play()`

**All of this work.**


### Produce the issue : 

`Run step 3 then step 4 `


Result : Infinit loading
