### ISSUE TITLE
video.js Audio Tracks

### ISSUE THREAD

**Issue by Ars2932001** [videojs/video.js#6383]
On Android video.js not getting audio tracks, but on Browser it is woking.

**Comment by gkatsev** [comment]
Try setting `overrideNative`:
```js
var player = videojs('vid', {
  html5: {
    hls: {
      overrideNative: !videojs.browser.IS_ANY_SAFARI
    }
  }
});
```

**Comment by Ars2932001** [comment]
> Try setting `overrideNative`:
> 
> ```js
> var player = videojs('vid', {
>   html5: {
>     hls: {
>       overrideNative: !videojs.browser.IS_ANY_SAFARI
>     }
>   }
> });
> ```

Thanks for answer, but not working. Audio Tracks array is empty.
