### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by yanyunlong** [videojs/video.js#6385]
{
        key: "probeSegmentInfo",
        value: function(e) {
            var t = e.segment
              , i = e.playlist
              , n = void 0;
            return (n = t.map ? this.probeMp4Segment_(e) : this.probeTsSegment_(e)) && this.calculateSegmentTimeMapping_(e, n) && (this.saveDiscontinuitySyncInfo_(e),
            i.syncInfo || (i.syncInfo = {
                mediaSequence: i.mediaSequence + e.mediaIndex,
                time: t.start
            })),
            n
        }

**Comment by JFrankfurt** [comment]
Were you able to resolve this? I'm experiencing the same issue.
