### ISSUE TITLE
VideoJS keeping connections to Wowza alive after dispose & recreation

### ISSUE THREAD

**Issue by ezbDoubleZero** [videojs/video.js#6387]
## Description
If you create then dispose of a player multiple times before the connection to Wowza times out, it will keep those old connections alive, although it doesn't seem to be using any bandwidth when it does.  If you dispose and recreate after Wowza times out the connection, everything will work fine.  The behavior is the same for Firefox and Chrome.

## Steps to reproduce
Simply create an HTML page with a video.js player with it's src pointing to a Wowza HLS stream that has a button that will toggle the player.  By toggle I mean dispose and create the player over and over as described in the Docs on how to show/hide the player.

### Expected
I'd expect to see the connections to Wowza to drop after the timeout period back to 1 connection.

### Actual
The number of connections to Wowza remains the same as the number of times you've toggled the player, and stays that way.

### Error output
None.

#### videojs
7.7.4
#### browsers
Firefox 71.0
Chrome 79.0.3945.88
Edge build 18362
#### OSes
Win10
### plugins
videojs-http-streaming

**Comment by himalreddy** [comment]
Hi @ezbDoubleZero,
I am also facing the same issue.
but I solved this issue in two ways
1: modify the some part videojs code
`

his.mainSegmentLoader_.on('error', function() {
--
  | if (_this3.mainSegmentLoader_.duration_() === Infinity \|\| (_this3.mainSegmentLoader_.error().code == 2 && _this3.mainSegmentLoader_.error().status != 0)) {
  | _this3.tech_.trigger({
  | type: 'error',
  | error: _this3.mainSegmentLoader_.error()
  | });
  | } else {
  | _this3.blacklistCurrentPlaylist(_this3.mainSegmentLoader_.error());
  | }
  | });

and another part

this.masterPlaylistLoader_.on('error', function() {
--
  | if (_this2.mainSegmentLoader_.duration_() === Infinity \|\| (_this2.masterPlaylistLoader_.error.code == 2 && _this2.masterPlaylistLoader_.error.status != 0)) {
  | _this2.tech_.trigger({
  | type: 'error',
  | error: _this2.masterPlaylistLoader_.error
  | });
  | } else {
  | _this2.blacklistCurrentPlaylist(_this2.masterPlaylistLoader_.error);
  | }
  | });
`
2: Add hlsjs plugin (best solution):
https://cdn.streamroot.io/videojs-hlsjs-plugin/1/stable/videojs-hlsjs-plugin.js
for more info about hlsjs project: https://github.com/streamroot/videojs-hlsjs-plugin

VideoJS doesn't support mp3 audio.
so, I am using the second method(hlsjs plugin supports any type of audio by using webmix transformation).

I hope it will help to solve your issue.

**Comment by himalreddy** [comment]
Hi @ezbDoubleZero,
I am also facing the same issue.
but I solved this issue in two ways
1: modify the some part videojs code
`this.masterPlaylistLoader_.on('error', function () {
          if(_this2.mainSegmentLoader_.duration_() === Infinity || (_this2.masterPlaylistLoader_.error.code == 2 && _this2.masterPlaylistLoader_.error.status != 0)){
            _this2.tech_.trigger({type:'error',error:_this2.masterPlaylistLoader_.error});
          }else{
            _this2.blacklistCurrentPlaylist(_this2.masterPlaylistLoader_.error);
          }
        });

this.mainSegmentLoader_.on('error', function () {
          if(_this3.mainSegmentLoader_.duration_() === Infinity || (_this3.mainSegmentLoader_.error().code == 2 && _this3.mainSegmentLoader_.error().status != 0)){
              _this3.tech_.trigger({type:'error',error:_this3.mainSegmentLoader_.error()});
          }else{
            _this3.blacklistCurrentPlaylist(_this3.mainSegmentLoader_.error());
          }
        });`
2: Add hlsjs plugin (best solution):
https://cdn.streamroot.io/videojs-hlsjs-plugin/1/stable/videojs-hlsjs-plugin.js
for more info about hlsjs project: https://github.com/streamroot/videojs-hlsjs-plugin

VideoJS doesn't support mp3 audio.
so, I am using the second method(hlsjs plugin supports any type of audio by using webmix transformation).

I hope it will help to solve your issue.

**Comment by ezbDoubleZero** [comment]
> 
> 
> Hi @ezbDoubleZero,
> I am also facing the same issue.
> but I solved this issue in two ways
> 1: modify the some part videojs code
> `this.masterPlaylistLoader_.on('error', function () {
> if(_this2.mainSegmentLoader_.duration_() === Infinity || (_this2.masterPlaylistLoader_.error.code == 2 && _this2.masterPlaylistLoader_.error.status != 0)){
> _this2.tech_.trigger({type:'error',error:_this2.masterPlaylistLoader_.error});
> }else{
> _this2.blacklistCurrentPlaylist(_this2.masterPlaylistLoader_.error);
> }
> });
> 
> this.mainSegmentLoader_.on('error', function () {
> if(_this3.mainSegmentLoader_.duration_() === Infinity || (_this3.mainSegmentLoader_.error().code == 2 && _this3.mainSegmentLoader_.error().status != 0)){
> _this3.tech_.trigger({type:'error',error:_this3.mainSegmentLoader_.error()});
> }else{
> _this3.blacklistCurrentPlaylist(_this3.mainSegmentLoader_.error());
> }
> });`
> 2: Add hlsjs plugin (best solution):
> https://cdn.streamroot.io/videojs-hlsjs-plugin/1/stable/videojs-hlsjs-plugin.js
> for more info about hlsjs project: https://github.com/streamroot/videojs-hlsjs-plugin
> 
> VideoJS doesn't support mp3 audio.
> so, I am using the second method(hlsjs plugin supports any type of audio by using webmix transformation).
> 
> I hope it will help to solve your issue.

Thanks for the reply.  I tried using the plugin, as well as a different HLS plugin, and neither fixed the issue.  It's possible I didn't set them up correctly, but the documentation is nearly useless, so I'll never know.

I can't try your first fix as I have no idea where in the code that code actually is.
