### ISSUE TITLE
Picture in Picture - your demo videojs.com

### ISSUE THREAD

**Issue by ShinJii89** [videojs/video.js#6393]
Hi,
Why on your page videojs.com demo player doesn't show ability to play picture in picture button? 
This button is disabled, but I can play PiP after right button (mouse) click....

Browser: Firefox 72.0.1 (64bit)
System: Linux

**Comment by marguinbc** [comment]
Hi!

Thanks for the question and for contributing to the Video.js community.

Firefox does not use the PiP API but instead uses its own implementation to support Picture-in-Picture which we cannot interact with.  This is why we don't display the button in our player.
