### ISSUE TITLE
Video Streaming in WKWebView iOS not working

### ISSUE THREAD

**Issue by abhinavchopra** [videojs/video.js#6394]
Hi,

I am trying to load html file in native iOS app with using WKWebView which is a web view container of native library in iOS.

Here is the html:

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/dashjs/3.0.0/dash.all.debug.js"> </script>

    <script src="https://unpkg.com/video.js/dist/video.js"> </script>
    <script src="https://unpkg.com/videojs-contrib-dash/dist/videojs-dash.js"> </script>

    
    <style>
        html {
            height: 100%;
        }

        body {
            margin: 0 !important;
            width: 100%;
            height: 100%
        }

        .video-js {
            margin: 0 auto;
            width: 100%;
            height: 100%
        }

        .video-js .vjs-big-play-button {
            top: 50% !important;
            left: 50% !important;
        }
    </style>

</head>

<body>

    <video id="example" class="video-js vjs-default-skin" controls>
    </video>
    <script>

        var player = videojs('example', {
            html5: {
                dash: {
                    setLimitBitrateByPortal: true,
                    setMaxAllowedBitrateFor: ['video', 2000]
                }
            }
        });
		player.src({ src: 'https://bitmovin-a.akamaihd.net/content/playhouse-vr/mpds/105560.mpd', type: 'application/dash+xml' });

    // player.play();

    </script>

</body>

</html>

Please help me with this issue ASAP

**Comment by mister-ben** [comment]
As far as I know WKWebView does not support Media Source Extensions, so you wouldn't be able to play DASH. Do you have an HLS source instead?
