### ISSUE TITLE
Capture screenshot of video using React

### ISSUE THREAD

**Issue by sadashivm** [videojs/video.js#6395]
Hello Team,
I'm using your react base plugin as below,

`npm i -s video.js`

How to capture screenshot while playing the video.
For example - clicking on button I need to take screenshot. How to do?

Can you please tell the steps.

**Comment by mister-ben** [comment]
Video.js doesn't have any built in functionality for this, but you can check out examples like this for grabbing a frame from the video element http://jsfiddle.net/onigetoc/v80khg1L/

**Comment by sadashivm** [comment]
Thanks for reply,
I got the solution.

class MediaPlayer extends Component {

    handleMetadata = event => {
        const duration = event.currentTarget.duration;
        // ...
    }

    render() {
        const {src} = this.props;

        return(
            <video src={src} onLoadedMetadata={this.handleMetadata} />
        );
    }
}

**Comment by chenhl05** [comment]
Hello @sadashivm ,
I am troubled by the same problem.
Can you provide me with more details of the demo for my reference?
Thank you very much.

**Comment by sadashivm** [comment]
> Hello @sadashivm ,
> I am troubled by the same problem.
> Can you provide me with more details of the demo for my reference?
> Thank you very much.

Here is the below solution,

` ==== 1.  VideoPlayer.js =======`

import React from 'react';
import videojs from 'video.js';
import './VideoPlayer.css';
import CaptureScreenshot from './CaptureScreenshot';

const options = {
  autoplay: true,
  sources: [{
    src: ''
  }],
  controls: true,
  fluid: true,
  responsive: true,
  controlBar: {
    fullscreenToggle: false,
    pictureInPictureToggle: false
  }
};

class VideoPlayer extends React.Component {
  state = {
    capture: false,
    videoWidth: 0,
    videoHeight: 0
  }

  componentDidMount() {
    const { videoFilePath } = this.props;
    this.playVideoHandler(videoFilePath);
  }

  componentWillUnmount() {
    if (this.player) {
      this.player.dispose();
    }
  }

  playVideoHandler = srcPath => {
    options.sources[0].src = srcPath;
    this.player = videojs(this.videoNode, options);
  }

  handleMetadata = () => {
    const video = document.querySelector('video');
    if (video) {
      this.setState({
        videoWidth: video.videoWidth,
        videoHeight: video.videoHeight
      });
    }
  }

  resetCapture = () => this.setState({ capture: false });

  render() {
    const { capture, videoWidth, videoHeight } = this.state;

    return (
      <>
        <div data-vjs-player>
          <video
            id="videoPlayer"
            ref={node => this.videoNode = node}
            className="video-js vjs-default-skin vjs-big-play-centered"
            onLoadedMetadata={this.handleMetadata}
          />
        </div>
        <CaptureScreenshot
          captured={capture}
          videoWidth={videoWidth}
          videoHeight={videoHeight}
          resetCapture={this.resetCapture}
        />
      </>
    );
  }
}

export default VideoPlayer;


` ==== 2.  CaptureScreenshot.js =======`

import React from 'react';
import './VideoPlayer.css';

const CaptureScreenshot = props => {
  const {
    captured, resetCapture, videoWidth, videoHeight
  } = props;

  const canvasStyle = {
    position: 'absolute',
    visibilit: 'hidden'
  };

  if (captured) {
    const video = document.querySelector('video');
    const canvas = document.querySelector('#screenshot_canvas');
    if (video && canvas) {
      canvas.width = videoWidth;
      canvas.height = videoHeight;
      const context = canvas.getContext('2d');
      context.fillRect(0, 0, videoWidth, videoHeight);
      context.drawImage(video, 0, 0, videoWidth, videoHeight);

      const img = document.createElement('img');
      img.setAttribute('crossOrigin', 'anonymous');
      img.setAttribute('src', canvas.toDataURL());

      const link = document.createElement('a');
      link.download = 'Download.png';
      link.href = img.src;
      link.click();
      link.remove();
      img.remove();
    }
    resetCapture();
  }

`return (`
    `<>`
      `<canvas id="screenshot_canvas" style={canvasStyle} />`
    `</>`
  `);`
`};`

export default CaptureScreenshot;

**Comment by ChR-iSz** [comment]
> Video.js doesn't have any built in functionality for this, but you can check out examples like this for grabbing a frame from the video element http://jsfiddle.net/onigetoc/v80khg1L/

This not work with m3u8 streams...

**Comment by sadashivm** [comment]
Hello @chenhl05 and @talalz94 ,
here is the code,

1. VideoPlayer.js

[VideoPlayer.txt](https://github.com/videojs/video.js/files/8550062/VideoPlayer.txt)

2. CaptureScreenshot.js

[CaptureScreenshot.txt](https://github.com/videojs/video.js/files/8550064/CaptureScreenshot.txt)

Note: Please chage file extension .txt to .js file, because github doesn't allow javascript file to upload.
Hence I changed the file extension to .txt

Note: For VideoPlayer.js please use purecomponent/class based component instead of functional based component.
