### ISSUE TITLE
video.js:23216 VIDEOJS: ERROR: TypeError: this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by CNzxy0820** [videojs/video.js#6401]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.
I use videojs to play rtmp video,and I add a button to display videoBox display: none  / block, but then I click button , chrome show this error.And the video is black screen.
`VIDEOJS: ERROR: TypeError: this.el_.vjs_getProperty is not a function
    at Flash.currentTime (video.js:13981)
    at Player.techGet_ (video.js:10579)
    at Player.currentTime (video.js:10703)
    at PlayProgressBar.updateDataAttr (video.js:4184)
    at Player.bound (video.js:23004)
    at HTMLDivElement.bound (video.js:23004)
    at HTMLDivElement.data.dispatcher (video.js:22790)
    at Object.trigger (video.js:22917)
    at Player.trigger (video.js:1553)
    at Player.<computed> [as handleTechTimeupdate_] (video.js:12510)
logByType @ video.js:23216
`
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.use videojs to play rtmp video
2.add a button to control video display: none / block

### Expected
Please describe what you expected to see.
I expected to see I can control wherther the video is displayed, and the video is still play.
### Actual
Please describe what actually happened.
The video is black screen
### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?  
#### browsers chrome
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Hiding an element containing a swf with `display:none` will cause it to be unloaded on most modern browsers. You're probably better off calling `dispose()` on the player and creating a new player when you want to show it again.

**Comment by CNzxy0820** [comment]
> Hiding an element containing a swf with `display:none` will cause it to be unloaded on most modern browsers. You're probably better off calling `dispose()` on the player and creating a new player when you want to show it again.

thanks,I will try it soon
