### ISSUE TITLE
when play .m3u8 and throw error ReferenceError: _create is not defined

### ISSUE THREAD

**Issue by candivan** [videojs/video.js#6403]
version =>"video.js": "^7.6.6",

I use video.js in uniapp project and when use .mp4 it can play normally but use .m3u8 it throw and error.
```
<template>
	
	<view class="content">
		<view class="video-js" ref="video">
	
		</view>
	</view>
	
</template>

<script>
	
	import videojs from 'video.js'
	import 'video.js/dist/video-js.css'
	
	export default {
		data() {
			return {
				
			};
		},
		
		onReady() {  
			
			var video = document.createElement('video')
			video.id = 'video'
			video.style = 'width: 300px;height: 150px;'
			video.controls = true
			var source = document.createElement('source')
			source.src ='/static/v0new/v0new.m3u8'
			// source.src ='/static/v0-new.mp4'
			video.appendChild(source)
			this.$refs.video.$el.appendChild(video)
			videojs('video')	
				  
		},  
	}
</script>

<style>

</style>
```
the error info as below: 
d2df116a-7ca9-42dd-b75f-f9d2b42d6ed0:52 Uncaught ReferenceError: _create is not defined
    at inherits (d2df116a-7ca9-42dd-b75f-f9d2b42d6ed0:52)
    at d2df116a-7ca9-42dd-b75f-f9d2b42d6ed0:427
    at d2df116a-7ca9-42dd-b75f-f9d2b42d6ed0:471
    at d2df116a-7ca9-42dd-b75f-f9d2b42d6ed0:679

**Comment by simidaliang** [comment]
source's  type  "application/x-mpegURL";

**Comment by gkatsev** [comment]
Please try to include the type `application/x-mpegurl` for HLS content.
What version of Video.js are you using? What browser are you running on? Can you provide a reduced example?

**Comment by liuxin-iw** [comment]
'document' objects are not supported in uniapp
