### ISSUE TITLE
how to hide fullscreentoggle icon

### ISSUE THREAD

**Issue by leekang** [videojs/video.js#6406]
hello,I want to hide fullscreentoggle icon. 
I tried many ways.example:
vjs-fullscreen-control {
    display:none;
}
or
videojs("my-video", {
    controlBar: {
      fullscreenToggle: false
    }
});
but it still here.
my videojs's version is 7.5.4. thanks!

**Comment by gkatsev** [comment]
Looks like the issue with the css one is specificity. Updating the selector to `.video-js .vjs-fullscreen-control` makes it work.
The option works for me as well and probably the recommended approach as it will not even create the component in the first place.

**Comment by mister-ben** [comment]
If `videojs("my-video", options) isn't working it could be because you've already set up the player by including the `data-setup` attribute.
