### ISSUE TITLE
npm installed version 7.6.6

### ISSUE THREAD

**Issue by Arametheus** [videojs/video.js#6417]
## Description
Briefly describe the issue.
installed a fresh install of video.js and I have missing files.

## Steps to reproduce
1. npm install --save-dev video.js

### Expected
Please describe what you expected to see.

### Actual
it to install all necessary files.

missing these packages
@videojs
aes-decrypter
m3u8-parser
mux.js
pkcs7

### Error output
Uncaught Error: Cannot find module 'mux.js/lib/mp4/caption-parser'
    at webpackMissingModule (app.js:67845)
    at Object../node_modules/video.js/dist/video.cjs.js (app.js:67845)
    at __webpack_require__ (app.js:20)
    
if I go look in that directory that file is no were to be found.  any suggestions?

**Comment by gkatsev** [comment]
I think this is the same issue as #6271, so, re-opening that one for tracking.
