### ISSUE TITLE
Video player shakes in chrome but not other browsers when width is a specific value

### ISSUE THREAD

**Issue by sethborg** [videojs/video.js#6428]
## Description
video-js and vjs-fluid causes the player to shake in Chrome (not Firefox or Edge) as it tries to adjust size. All vjs-fluid does is width: 100%; padding-top: 56.36942675159236%; so that combined with the video-js class causes the issue in chrome.

Example animated gif: (note I cropped out the taskbar from this 1920x1080 original) https://imgur.com/a/UQvUAaE

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Make sure you're running 1920x1080, that your taskbar is not set to auto hide, turn off the bookmark toolbar in chrome, and make sure you don't have the download toolbar at the bottom of the screen open.
2. Host this file somewhere and visit it. Note the video is a 1280x720 resolution video.

Not sure how to put html in here so here's a pastebin: https://pastebin.com/4FYLXdSQ

### Expected
no shaking

### Actual
shaking

### Error output
none

## Additional Information
latest stable chrome and videojs

**Comment by sethborg** [comment]
keeping this open and not stale

**Comment by JosephKimbrough** [comment]
I'm having the same experience using 16:9. as soon as I remove the class (I also tried it using player options) the video plays without the jitter. I should note that I am using vuejs and vuex but the jitter only occurs in Chrome for me as well.

**Comment by JosephKimbrough** [comment]
my video was in a "container-fluid" div, once I removed fluid from the container it played without the jitter in Chrome.

**Comment by sethborg** [comment]
See chromium bug 1048261
