### ISSUE TITLE
full screen icon disabled in IE11 (grayed out)

### ISSUE THREAD

**Issue by markusd1984** [videojs/video.js#6429]
## Description
I created a scorm (learning) module with articulate rise that seems to use this player for video playback and in some LMS platforms the full screen button is disabled on IE11, but I can't figure out why. Chrome is working fine.

I noticed that the sourced rendered includes "**vjs-disabled**"

`<button tabindex="0" title="Fullscreen" disabled="disabled" class="vjs-fullscreen-control vjs-control vjs-button **vjs-disabled**" aria-disabled="true" aria-hidden="false" type="button"><span class="vjs-icon-placeholder" aria-hidden="true"></span><span class="vjs-control-text" aria-live="polite">Fullscreen</span></button>`

## Steps to reproduce
Since this is LMS platform depended, I'm still thankful for any thoughts what could cause IE11 to disable the button and how possibly I could check this in the console? 
FYI - I'm hosting the package on a drupal server (apache on ubuntu)

### Expected
Full screen button clickable and switching video playback to full screen. 

### Actual
Full screen button is grayed out.

#### videojs
unknown
#### browsers
IE11
#### OSes
Win10

**Comment by gkatsev** [comment]
The icon is greyed out if fullscreen capabilities aren't available for whatever reason. For example, the player is in an iframe but permissions isn't granted to the iframe.
Do you have a test case we can look at?
