### ISSUE TITLE
The requested module '../../global/window.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by tuomassa** [videojs/video.js#6443]
## Description
When installing via npm and trying to import with `import { videojs } from 'video.js';`
I get
```
Uncaught SyntaxError: The requested module '../../global/window.js' does not provide an export named 'default'
```
How am I supposed to import it? Everything else I install from npm i can import like this. What is non-standard about how video.js works? The documentation is severely missing someting about the npm step.

**Comment by AwokeKnowing** [comment]
yeah I saw another bug report about this ages ago and they just said they 'don't use requirejs much' and weren't willing to look into it.

many of us have solved but just actually creating those dummy files

ie  create a global folder and create global/window.js: 

// https://github.com/videojs/video.js/issues/5680
define('global/window', [], function () {
return window;
});


global/document.js:

// document.js file https://github.com/videojs/video.js/issues/5680
define('global/document', ['global/window'], function (window) {
return window.document;
});


yes. it's super annoying.

**Comment by AwokeKnowing** [comment]
https://github.com/videojs/video.js/blob/main/rollup.config.js#L71
https://github.com/videojs/video.js/blob/main/src/js/video.js#L6
