### ISSUE TITLE
Consider Exporting videojs.MenuButton

### ISSUE THREAD

**Issue by dominic-p** [videojs/video.js#647]
I'm working on a plugin that will add a new menu style button similar to the captions button. All of the other properties I need seem to be available (e.g. `videojs.MenuItem`), but `videojs.MenuButton` isn't exposed.

I'm sure I could recreate the functionality by extending `videojs.Button`, but that would mean a lot of copy/pasting from the core. Any reason not to export `videojs.MenuButton` that I'm missing?

**Comment by raidpipe** [comment]
hello guys i am about to add resolution selector to my site having video.js player, do i need to create different copies for each video resolution ???

**Comment by dominic-p** [comment]
@raidpipe, take a look at the [example file](https://github.com/dominic-p/videojs-resolution-selector/blob/1.6.1/example.html) for the plugin. You should setup your video files to match that.
