### ISSUE TITLE
How to locate the actual video with videojs blob link from the website?

### ISSUE THREAD

**Issue by littlegreenhead** [videojs/video.js#6489]
Here's the 2 links i found from the website using inspect, but it seems like i cant locate the actual video with these links, need help with this.

blob:https://www.jvid.com/a29aa598-b01f-4b53-a191-0231f71e4359

https%3A%2F%2Fimg.jvid.com%2Ftranscode_video%2F1582208512038_34479%2F2020%2F02%2F20%2F8b25fa59bc15b141c765609cac9b1c0672858068f6f2ad3a76a72591c6b04700_1080p_playList.m3u8&vid=7950

**Comment by gkatsev** [comment]
When MSE is used, the source URL isn't available on the video element. You'll want to use the player API to get the source [`player.src()`](https://docs.videojs.com/player#src).
