### ISSUE TITLE
Nuxt js and videojs  control bar icon is not shown properly 

### ISSUE THREAD

**Issue by ngels** [videojs/video.js#6491]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.having a working instance of nuxt.js
2.install video.js from npm
3. below is the component that use video.js 
```
<template>
  <div>
    <video ref="videoPlayer" class="video-js  vjs-theme-fantasy"></video>
  </div>
</template>

<script>
import videojs from 'video.js'
import 'video.js/dist/video-js.css'
import '@videojs/themes/dist/fantasy/index.css'
export default {
  name: 'VideoPlayer',
  props: {
    src: {
      type: String,
      default() {
        return {}
      }
    },
    videotype: {
      type: String,
      default() {
        return {}
      }
    }
  },
  data() {
    return {
      player: null,
      options: {
        autoplay: false,
        techOrder: ['html5'],
        controls: true,
        preload: 'auto',
        playbackRates: [0.5, 1, 1.5, 2],
        suppressNotSupportedErro: true,
        responsive: true,
        aspectRatio: '16:9',
        fluid: true,
        sources: [
          {
            src: this.src,
            type: this.videotype
          }
        ]
      }
    }
  },
  mounted() {
    this.player = videojs(
      this.$refs.videoPlayer,
      this.options,
      function onPlayerReady() {
        console.log('onPlayerReady', this)
      }
    )
  },
  beforeDestroy() {
    if (this.player) {
      this.player.dispose()
    }
  }
}
</script>
<style scoped>
.vjs-default-skin.vjs-big-play-button {
  background: #00ff00;
}
</style>
```
### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by DispatchCommit** [comment]
In your `nuxt.config.js` file add video.js's CSS file to the css array:

```js
// nuxt.config.js
...
css: [
    'video.js/dist/video-js.css',
],
```

**Comment by ngels** [comment]
// nuxt.congig.js
![image](https://user-images.githubusercontent.com/31316002/75273485-e9f9d300-583b-11ea-87ec-eec3b85c568b.png)

@DispatchCommit it was already the case when i submited this issue. i import the css in my nuxt.config.js
![image](https://user-images.githubusercontent.com/31316002/75273337-a4d5a100-583b-11ea-8a49-5805c63ed683.png)

**Comment by gkatsev** [comment]
Do you have a live example of the issue? We've previously had this occur if the pages weren't served with a utf-8 character encoding.
