### ISSUE TITLE
Multiple audio - out of sync

### ISSUE THREAD

**Issue by popler** [videojs/video.js#6493]
I have problem with HLS ABR stream including multiple audio tracks. I tested the same stream with other players (eg. hlsjs) and also with single audio track - it is working ok.

You can check with any HLS stream included multiple audio track 

I tested with videojs 7.6.0 and 7.7.5 in Chrome and Firefox (Windows)

**Comment by gkatsev** [comment]
This is something we're aware of and we're working on fixing. There's a bunch of work happening in VHS (recently merged https://github.com/videojs/http-streaming/pull/778). Hopefully, we'll be confident in releasing it soon and it should improve things.
