### ISSUE TITLE
Question about videojs progress control.

### ISSUE THREAD

**Issue by AccountGc** [videojs/video.js#6495]
## Description
Briefly describe the issue.
The progress bar is allowed to be dragged for the part that has been played, and the progress bar is not allowed to be dragged for the unplayed part.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.The 5 minute video has been played for 3 minutes. The progress can be dragged in the first 3 minutes, and cannot be dragged in the next 2 minutes.

Thank you！

## Additional Information
Please include any additional information necessary here. Including the following:
videojs versions 7.0

what version of videojs does this occur with?
browsers IE

#### OSes
what platforms (operating systems and devices) are affected?
windows 7

### plugins
are any videojs plugins being used on the page? If so, please list them below.
no use plugins.

@mister-ben 
@gkatsev

**Comment by bcbclifford** [comment]
Do you mean you have this behaviour but don't want it (in which case, where is a reproducible test?) or are you asking how to prevent a user from seeking forward?

**Comment by gkatsev** [comment]
I believe that what you're looking for can be solved using middleware. On the Brightcove Support pages, we have a writeup of how to do it: https://support.brightcove.com/brightcove-player-sample-disable-forward-scrubbing.
Hope this helps.

**Comment by 1154742732** [comment]
hi !  I'm a rookie . I would like to ask about the link you sent . 
How do I cancel that operation because I'm using that code that will repeatedly call the middleware in the link on a page Because I'm calling the middleware method repeatedly on the meeting page but I've only created one middleware so I want to know how to close it .
thanks you !
 @gkatsev
