### ISSUE TITLE
Question about global components

### ISSUE THREAD

**Issue by Jaluco** [videojs/video.js#6496]
Is there a way to add components to all players as a default? I've searched but the only examples add components to instanced players.

**Comment by DispatchCommit** [comment]
Why not create a custom class or function that generates all the players you want with the same configuration?

**Comment by gkatsev** [comment]
You can use our hooks system to modify options for all players or after creation add things to it. Beyond that there's no way to configure things globally.
See our docs on hooks here: https://docs.videojs.com/tutorial-hooks.html
