### ISSUE TITLE
Cacheencryptionkeys does not work

### ISSUE THREAD

**Issue by nikolamakin** [videojs/video.js#6501]
#versions
#### videojs
v 7.6.6
#### browsers
google
#### OSes
mac os
### plugins
none

`
var options = {
        cacheEncryptionKeys: true
    };
`
Cacheencryptionkeys does not work
Did I write that wrong? 
please ,thank u

**Comment by sgotre** [comment]
@nikolamakin try using: 

```js

var options = {
    html5: {
         hls: {
              cacheEncryptionKeys: true
         }
},
`
