### ISSUE TITLE
There is no text tracks in Safari

### ISSUE THREAD

**Issue by Seokky** [videojs/video.js#6506]
Using videojs with Vue. 

In all browsers except Safari I can get text tracks via ```this.player.textTracks()```. 
In Safari there is no tracks in ```tracks_``` variable. 

P.S.: i'm using the last videojs version. Tried to downgrade version to 6.x. Tried to disable native Safari tracks.
P.S. 2: sorry about my English.

**Comment by gkatsev** [comment]
What are you doing that you need access to `tracks_`? You should be treating the object returned from `player.textTracks()` as an array-like object (passing it to `Array.from` is beneficial).
On Safari, we use native text tracks by default and so `tracks_` isn't present. On other platforms, we use our emaulted text tracks.
See https://docs.videojs.com/tutorial-text-tracks.html#working-with-text-tracks for working with tracks on a platform agnostic manner.

**Comment by Seokky** [comment]
> You should be treating the object returned from `player.textTracks()` as an array-like object (passing it to `Array.from` is beneficial).

but...

> In all browsers except Safari I can get text tracks via this.player.textTracks()

and

> Tried to disable native Safari tracks.

**Comment by gkatsev** [comment]
You can get text tracks in all browsers via `player.textTracks()` if that isn't returning an object with tracks then it's something else that's going on. We can try and help with a test case.
