### ISSUE TITLE
Auto preload url from sources and emit error events

### ISSUE THREAD

**Issue by zzuzsj** [videojs/video.js#6509]
## Description
I use npm video.js to play hls sources.It's supposed to be the source data is loaded after the play button is clicked.However,the source data is loaded after i created a videojs instance,even i set autoplay false and preload 'none'.So,I want to know ,how to load the source data  after the play button is clicked.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.instance create 
![image](https://user-images.githubusercontent.com/20783807/76051512-05847c80-5fa6-11ea-9b63-01aa66d9746b.png)

2.videojs options
![image](https://user-images.githubusercontent.com/20783807/76051533-19c87980-5fa6-11ea-8f18-d93e8902d019.png)

3.load source data immediately and emit error events
![image](https://user-images.githubusercontent.com/20783807/76051565-306ed080-5fa6-11ea-8c76-eaba39f39c38.png)

### Expected
source data load after user gesture

### Actual
source data load start

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
"video.js": "^7.6.6",

#### browsers
chrome v80

#### OSes
os

### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Unfortunately, with VHS we currently still load the manifest with a preload value of none. It's something that is on our shortlist of tasks.
