### ISSUE TITLE
Trying to play video without file extension

### ISSUE THREAD

**Issue by pritamguha** [videojs/video.js#6510]
Trying to play spoof link in Safari but it is not working.

For security concern, I fetch an API that serves the video as streamed data, it is working perfectly in chrome. Video is stored in AWS.

API looks like `https://abc.com/api/v1/follower/content/[content ID]/[user token]`

**Comment by gkatsev** [comment]
Have an example? Are you specifying a type when setting the source? Are you playing back something that safari can handle?

**Comment by faysalcse28** [comment]
Still, now i didn't get any kind of solution from here. Disapointed.

**Comment by gkatsev** [comment]
The solution is to provide a type for the video. Unfortunately, we can't really handle urls with an extension and without a mimetype.
