### ISSUE TITLE
"nativeTextTracks: false" is not working in Chrome Mobile on iOS.

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#6514]
nativeTextTracks: false" is not working in Chrome Mobile on iOS. 

Tracks are still displayed native, not html.

Tested on Chrome Mobile 78, iOS 13.2

Videojs version :  7.7.4 & 7.7.5

Thanks, advance!

**Comment by gkatsev** [comment]
This is likely a bug, though, we would recommend using native text tracks on iOS because if you go fullscreen into the native player, you can't overlay the captions there. Also, the safari implementation of vtt is pretty good.
