### ISSUE TITLE
Video only has audio on android 9

### ISSUE THREAD

**Issue by TinOrion** [videojs/video.js#6515]
## Description
On Android 9 (Android TV), when I open any video with videojs (include case embed iframe), video only has audio without not show the image although duration still loads and count down. On Android 7, Android 8, everything works well. I using Cordova to build cross-platform.

![89690838_666820477455731_341692187727101952_n](https://user-images.githubusercontent.com/14829388/76266095-f6007e80-6298-11ea-97d5-9e23c5ce5184.jpg)

When I use mode overrideNative is true, another issue appears: 'The media playback was aborted due to a corruption problem or because the media used features your browser did not support'.

I have an example (https://codepen.io/TinOrion/pen/abOEVGv) you can check or use it.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Input example into the source (build with Cordova or same anything). You can embed iframe.
2. Play video.
3. Duration load and count down. 

### Expected
Video play normal (show audio and images).

### Actual
Video only has audio, not show images

### Error output
Don't error output.
#### videojs
Videojs version 7.6.6
#### OSes
Android 9 (Android TV)

Thanks, everyone!

**Comment by manzajaro** [comment]
+1 in mi case Android 9 (Mibox4)

**Comment by gkatsev** [comment]
And the video you're playing is the same one as in the codepen?
I definitely would recommend using overrideNative (we're probably going to turn it on by default soon on non Safari browsers).

**Comment by TinOrion** [comment]
Thanks for your reply. But when I use mode overrideNative is true, another issue appears: 'The media playback was aborted due to a corruption problem or because the media used features your browser did not support'. It just happened on Android 9. It's working normally on Android 8.
