### ISSUE TITLE
What component(s) to use for HTML forms?

### ISSUE THREAD

**Issue by stevendesu** [videojs/video.js#6518]
When creating a custom component with a complex UI (e.g. a modal overlay with text inputs and a button for submitting the form), it's often best to create nested components like so:

 - ModalForm
    - TextInput
    - TextInput
    - SubmitButton

For the `ModalForm` there's already a `ModalDialog` component provided by VideoJS, so the UI can be constructed like so:

```
var modal = new ModalDialog();
modal.addChild(new TextInput());
modal.addChild(new TextInput());
modal.addChild(new SubmitButton());
```

My question is, do any components already exist for the `TextInput` and `SubmitButton` portions? I noticed there's a `ClickableComponent` component, but the description explicitly states:

>Component which is clickable or keyboard actionable, ***but is not a native HTML button.***

There's also a `Button` component, but this component seems to have no text and instead expects you to display a small icon (like the control bar buttons)

If no such component exists it's not too hard to create them, I just would prefer to use what's natively in VideoJS before writing my own components

**Comment by mister-ben** [comment]
Video.js doesn't have have an exhaustive set of components, only for things intended as par tof the player UI. You could extend and crearte custom components for other elements, but for a form it probably makes more sense to create the arbitrary HTML elements and populate the modal with that with `modal.fillWith(htmlElement)`.
