### ISSUE TITLE
Problem with install video.js

### ISSUE THREAD

**Issue by MarcinPHP** [videojs/video.js#6526]
I have nodejs 12.16.1

When I install, a got this:
_npm WARN saveError ENOENT: no such file or directory, open 'C:\AppServ\www\klasy\videojs\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for pkcs7@1.0.2: wanted: {"npm":"^1.4.6","node":"^0.10"} (current: {"node":"12.16.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: pkcs7@1.0.2
npm WARN enoent ENOENT: no such file or directory, open 'C:\AppServ\www\klasy\videojs\package.json'
npm WARN videojs No description
npm WARN videojs No repository field.
npm WARN videojs No README data
npm WARN videojs No license field._

Does this mean that I should install an older version of nodejs

**Comment by gkatsev** [comment]
What is the command that you ran? Also, you can probably ignore those warnings.

**Comment by awbenson** [comment]
I've have the same error message and this was just with "npm install --save video.js"

**Comment by MarcinPHP** [comment]
Ok, I ignored that, and is ok. Thanks

**Comment by gkatsev** [comment]
Also, make sure you're installing `video.js` and not `videojs`.
Specifically, `npm install video.js`.
The videojs npm package is a placeholder.
