### ISSUE TITLE
Not support H265(HEVC) decode?

### ISSUE THREAD

**Issue by hxm108** [videojs/video.js#6528]

**Comment by mister-ben** [comment]
H265 can only be played on browsers that support it.

**Comment by hxm108** [comment]
Which browsers support decoding h265?

**Comment by gkatsev** [comment]
Basically only safari. Some devices may support it, like chromecast ultra.
Also, on Safari, we use native playback for HLS by default.

**Comment by hxm108** [comment]
Is there any way to make chrome or Firefox compatible with h265?

**Comment by gkatsev** [comment]
I guess it's theoretically possible to decode h265 in javascript (or I guess wasm) and draw it on a canvas or something, similar to what ogvjs is doing but it isn't a simple task and I'm not aware of such projects yet.
Unfortunately, right now the answer is no. Your best bet with those browsers is likely av1 or vp9.
