### ISSUE TITLE
No `ended` event on Android 4.0.4 + Chrome 28

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#653]
Found with a video.js 4.0 player on an Android 4.0.4 device running Chrome 28.

Steps to reproduce
1. Register an event listener for the `ended` event
2. Play back a video

Expected:
The `ended` event listener is called.

Actual:
The event listener is not called.

I believe the root cause is a Chromium bug: https://code.google.com/p/chromium/issues/detail?id=263569

**Comment by gkatsev** [comment]
Android 4.0.4 has a tiny market share at this point ([0.8% globally](https://developer.android.com/about/dashboards/index.html)) and Chrome 28 is a really old version. Going to close this.
