### ISSUE TITLE
Wrong path for font scss in video-js.scss 

### ISSUE THREAD

**Issue by suchal** [videojs/video.js#6531]
## Description
The `node_modules/video.js/src/css/video-js.scss` file line 5 

> @import "../../node_modules/videojs-font/scss/icons";

So it is trying to import from` node_modules/video.js/node_modules/videojs-font/scss/icons` even though the actual location is `node_modules/videojs-font/scss/icons`
it is missing an additional `../`

## Steps to reproduce
Import the videojs scss file
@import "~video.js/src/css/vjs";
Start compilation

## Results
ERROR in Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
@import "../../node_modules/videojs-font/scss/icons";

## Additional Information
I can send a pull request
#### videojs
7.6.6

**Comment by helmerdavila** [comment]
If you want a quick fix I returned to `7.7.3` and is working again.

**Comment by lawchihon** [comment]
@helmerdavila , do you mean `7.6.3`?

**Comment by gkatsev** [comment]
Can you try 7.7.x? We have a potential fix for this via https://github.com/videojs/video.js/pull/6326.

**Comment by fewbadboy** [comment]
> Can you try 7.7.x? We have a potential fix for this via #6326.

7.8.0 also have the same bug

**Comment by gkatsev** [comment]
I'm not sure there's anything else we can do. We originally switched the path from what we use now to `../../` in our switch to `sass` from `node-sass` but then we switched it back in our internal usage of sass with `--load-path`. From what I can tell, sass expects dependencies to have the paths be `node_modules/...` rather than with the `../../` so, it sounds like where we settled is correct.
Unless someone can provide an example of it not working and help us figure out what the true path should be, I'll likely have to mark this as fixed.

**Comment by fewbadboy** [comment]
> I'm not sure there's anything else we can do. We originally switched the path from what we use now to `../../` in our switch to `sass` from `node-sass` but then we switched it back in our internal usage of sass with `--load-path`. From what I can tell, sass expects dependencies to have the paths be `node_modules/...` rather than with the `../../` so, it sounds like where we settled is correct.
> Unless someone can provide an example of it not working and help us figure out what the true path should be, I'll likely have to mark this as fixed.

when i build  the Project,  the following error is displayed.
![error](https://img-blog.csdnimg.cn/20200411225324328.png)

**Comment by fewbadboy** [comment]
> I'm not sure there's anything else we can do. We originally switched the path from what we use now to `../../` in our switch to `sass` from `node-sass` but then we switched it back in our internal usage of sass with `--load-path`. From what I can tell, sass expects dependencies to have the paths be `node_modules/...` rather than with the `../../` so, it sounds like where we settled is correct.
> Unless someone can provide an example of it not working and help us figure out what the true path should be, I'll likely have to mark this as fixed.

when i build  the Project,  the following error is displayed.

![error](https://user-images.githubusercontent.com/12499323/79047360-abcc3d80-7c48-11ea-98c3-0831f5876aa9.png)

**Comment by DispatchCommit** [comment]
`build:css` fails on windows (same error as @fewbadboy), but using WSL it works.
