### ISSUE TITLE
I have some question about pictureInPictureToggle and currentTimeDisplay

### ISSUE THREAD

**Issue by ChanMenglin** [videojs/video.js#6534]
This is my code.
```javascript
controlBar: {
  children: { 
    playToggle: true,
    volumePanel: {
       inline: false,
    },
    volumeMenuButton: true,
    currentTimeDisplay: true,
    timeDivider: true,
    durationDisplay: true,
    remainingTimeDisplay: false,
    progressControl: true,
    subtitlesButton: true,
    pictureInPictureToggle: true,
    fullscreenToggle: true,
  },
},
```

I have some question could you help me?
1. pictureInPictureToggle show on Safari and Chrome on mac, and show on android chrome too, I just tested this, and it disabled on Safari and android chrome, I think pictureInPictureToggle should be hidden  on Safari and android chrome, What is wrong?

2. about `currentTimeDisplay`, `timeDivider`, `durationDisplay`, `remainingTimeDisplay`, I set these  like the code but I have to add some style(scss) to show or hide this controls, can I use javascript only？

```scss
.video-js /deep/ .vjs-time-control {
  display: block;
}
.video-js /deep/ .vjs-remaining-time {
  display: none;
}
```

_Originally posted by @ChanMenglin in https://github.com/videojs/video.js/pull/6131#issuecomment-601556337_

**Comment by bariartz** [comment]
Which version you're using ?

**Comment by ChanMenglin** [comment]
"video.js": "^7.6.6",

**Comment by ChanMenglin** [comment]
There is a [live demo](https://warehousemanagementsystem.github.io/WMS/Demo-Content-c-video) - [code](https://github.com/WarehouseManagementSystem/WMS/blob/b18bf3d0dcc6a536de3b2777ce40b119f3272e1b/view/src/components/base/Content/Video/c-video.vue#L64)

**Comment by bariartz** [comment]
1. you want to hide or disabled PIP on safari and chrome for Android ?
2. what you meaning ? you want to hide currentTimeDisplay, timeDivider, durationDisplay, remainingTimeDisplay too ?

Ok, give me a time for i make a code. If done, i will give you my code. :)

*Sorry for my bad english.

**Comment by bariartz** [comment]
1. Please can you visit my demo in here: https://bariartz.github.io/videojs-by-pp/
what PIP is disabled ? if disabled you can copy my videojs  which I have experimented on my own.

for question number 2, what you meaning ?

*Sorry for my bad english.

**Comment by bariartz** [comment]
*Bonus, my videojs player there is video preview then you drag hover mouse at duration bar.

**Comment by ChanMenglin** [comment]
thank you very much for your help
1. about the first question: I want to show PIP on supported browsers and hide it on unsupported browsers, But now it shows up on all browsers and is disabled on unsupported browsers
2. about the second question: Just like in the [demo](https://warehousemanagementsystem.github.io/WMS/Demo-Content-c-video), but I use scss (you can think of it as css) to control the display and hide of time info, I have done what I want, I just want to ask if it can be controlled only by JavaScript , Which is easy to control through config

**Comment by bariartz** [comment]
1. You can using Javascript with if/else, then bottom you can add code for show or hide PIP, before if/else you must using code for what that chrome or IE or anything. Then, if(chrome){this code for show PIP}else{this code for hide PIP}. Btw, for show/hide PIP code, there is at videojs github.

2. Yes, you can using javascript. I think you cant uses css for show/hide. I already testing for that. Maybe javascript can do it.

**Comment by bariartz** [comment]
Oh ya, i have ever to using jquery, but cant. Javascipt can do.

**Comment by ChanMenglin** [comment]
1. I understand, I think video.js Should be improved about it: show PIP on supported browsers and hide it on unsupported browsers
2. I think so, but I tried, and I can not use only JavaScript, I have to use css, can you show me a demo, thank you!

**Comment by bariartz** [comment]
![image](https://user-images.githubusercontent.com/52082691/77430842-65847b00-6e0e-11ea-8a24-377a1b3199ee.png)
 this for question number 2, what like that ? you want videojs player like Youtube player ?

**Comment by bariartz** [comment]
for number 2: you can visit my demo : https://bariartz.github.io/videojs-by-pp/

and place this code to <style>
.video-js .vjs-duration,
.vjs-no-flex .vjs-duration {
  display: block;
}

.video-js .vjs-current-time,
.vjs-no-flex .vjs-current-time {
  display: block;
}

.video-js .vjs-remaining-time,
.vjs-no-flex .vjs-current-time {
  display: none;
}

.vjs-live .vjs-time-control {
  display: block;
}

.vjs-time-divider {
  display: block;
}

</style>

**Comment by bariartz** [comment]
And for number 1, i testing with videojs version 7.7.4, PIP on my chrome for PC is show, and chrome for Android is hide, my edge too is hide. Maybe just chrome for PC is show.

**Comment by ChanMenglin** [comment]
OK, I get it,Thank you every much

**Comment by bariartz** [comment]
Your welcome,,, :)

**Comment by bariartz** [comment]
If you have problem, you can asking for me, dont forget follow me, ok ? :D hehehe
