### ISSUE TITLE
Playback issue Safari from seeking/source change

### ISSUE THREAD

**Issue by cmshnrblu** [videojs/video.js#6535]
## Description
In safari only. I have a custom player configured to run at 480, 720, 1080, 2k and 4k. Playback defaults based on browser. In safari, if playback begins at default resolution, and then after watching playback for 10-30s the user switches to 4k. Once it has loaded, the player appears to speed up playback beyond real time, looking like it's trying to "catch-up". I would interpret this as the player is starting playback too soon, and so if "playback" starts 300ms prior to video playing, then 1000ms of video is playing in 700ms. That sort of thing. I don't know how I can prevent this. Is there a buffer setting I should set to make certain that playback is properly synced with calculated playback time? 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. An example of the embed player can be found at
2. watch for 30s on safari, then change resolution to 4k
3.After load, there should be a playback bug where it playback speed increases to "catch up" the video playback to the playback time. 
4. This bug has reproduced reliably across different macos computers. 

### Expected
Expected normal playback where video playback is synced with playback time. 

### Actual
Asyncrony occurs between video playback and playback time, leading to a diminished user experience in changing resolutions (source)

### Error output
No errors detected

#### videojs
Version 7.6.6
#### browsers
Safari
#### OSes
MacOS
### plugins
Silvermine Quality Selector, Playlist

**Comment by gkatsev** [comment]
Are you switching between different mp4s? I would definitely recommend using a format that's inherently supports bitrate switching like HLS.
Unfortunately, I'm not sure that there's anything to do beyond tweaking potentially tweaking seeking logic. Likely, it ends up seeking "too soon"? But ultimately, there's little that can be done.
I see you're using silvermine quality selector, ultimately, the seeking logic will be there. We do have https://github.com/videojs/video.js/pull/6507 which may or may not help with this.

**Comment by cmshnrblu** [comment]
It seems as though the answer is to go towards adaptive bitrate VOD. This will be the next step in development of this project. Thanks for looking into it.

**Comment by gkatsev** [comment]
You're welcome.
