### ISSUE TITLE
Memory leak after dispose

### ISSUE THREAD

**Issue by imwtr** [videojs/video.js#6537]
## Description
Using the latest version of videojs, after calling 7 players dispose method, chrome devtool shows that these 7 players still stay in memory, maybe the `bind` closure is the main reason~
![image](https://user-images.githubusercontent.com/11251240/77255784-f2132a00-6ca4-11ea-8948-1b04a9422326.png)
![image](https://user-images.githubusercontent.com/11251240/77255863-81204200-6ca5-11ea-8389-0617a903bcca.png)

## Steps to reproduce
1. Render 10 players
2. Dispose 7 players
3. Make a heap snapshot in devtool memory tab, filter Player class 
(using uncompressed code or you cannot find the `Player`)

### Expected
Just 3 players stay in memory

### Actual
The 7 disposed Players still exist

### Error output
None

#### videojs
7.3.0
#### browsers
Chrome
#### OSes
Mac
### plugins
None

**Comment by imwtr** [comment]
Wow, I just solved this leak problem, by setting the `player_`  to `null` after calling `ResizeManager` dispose method, so can you make some patch for it as soon as possible ?
![image](https://user-images.githubusercontent.com/11251240/77257050-dc096780-6cac-11ea-855e-d587e024cfbd.png)

Comparison:
3 players:
![image](https://user-images.githubusercontent.com/11251240/77257291-51c20300-6cae-11ea-8af5-3b2aaabac097.png)

100 players (and dispose 97 of them)
before:
![image](https://user-images.githubusercontent.com/11251240/77257244-16273900-6cae-11ea-9f5f-1e7ab14b92ee.png)

after:
![image](https://user-images.githubusercontent.com/11251240/77257158-926d4c80-6cad-11ea-8c94-9c8af7c783e8.png)

**Comment by gkatsev** [comment]
Looks like we added a call to `super.dispose()` about a year ago in version starting with version 7.5.1 (https://github.com/videojs/video.js/pull/5853). The parent class (Component) does set `this.player_ = null`.

Can you please update to the latest version of Video.js and test again? Thanks.

**Comment by imwtr** [comment]
> Looks like we added a call to `super.dispose()` about a year ago in version starting with version 7.5.1 (#5853). The parent class (Component) does set `this.player_ = null`.
> 
> Can you please update to the latest version of Video.js and test again? Thanks.

Yes it works with vesion 7.6.0, thx ~

**Comment by gkatsev** [comment]
You're welcome!
