### ISSUE TITLE
How to register Plugin in typescript ? 

### ISSUE THREAD

**Issue by acharyaks90** [videojs/video.js#6538]
## Description
When try to register plugin in typescript it show
No overload matches this call.

## Steps to reproduce
Code : Myplugin.ts
import videojs from 'video.js'

const Plugin = videojs.getPlugin('plugin');
interface Myplugin  {
 options :any 
}

 class Myplugin extends Plugin  {

    constructor(player, options) {
        super(player);
    
        if (options.customClass) {
          player.addClass(options.customClass);
        }
    
        player.on('playing', function() {
          videojs.log('my plugin works playback began!');
        });
      }
}

 videojs.registerPlugin('Myplugin', Myplugin);

### Expected
It should be registered with no error

### Actual
No overload matches this call.
  Overload 1 of 2, '(name: string, plugin: (this: VideoJsPlayer, ...options: unknown[]) => unknown): (...options: unknown[]) => unknown', gave the following error.
    Argument of type 'typeof Myplugin' is not assignable to parameter of type '(this: VideoJsPlayer, ...options: unknown[]) => unknown'.
      Type 'typeof Myplugin' provides no match for the signature '(this: VideoJsPlayer, ...options: unknown[]): unknown'.
  Overload 2 of 2, '(name: string, plugin: { new (player: VideoJsPlayer): Plugin; prototype: Plugin; BASE_PLUGIN_NAME: string; deregisterPlugin(name: string): void; getPlugin(name: string): ...; getPluginVersion(name: string): string; getPlugins(names?: string[]): { ...; }; isBasic(plugin: string | (() => any)): boolean; registerPlugin<T, K>(name: string, plugin: (this: VideoJsPlayer, ...options: K[]) => T): (...options: K[]) => T; registerPlugin<T extends ...>(name: string, plugin: T): () => T; }): () => { ...; }', gave the following error.
    Argument of type 'typeof Myplugin' is not assignable to parameter of type '{ new (player: VideoJsPlayer): Plugin; prototype: Plugin; BASE_PLUGIN_NAME: string; deregisterPlugin(name: string): void; getPlugin(name: string): ...; getPluginVersion(name: string): string; getPlugins(names?: string[]): { ...; }; isBasic(plugin: string | (() => any)): boolean; registerPlugin<T, K>(name: string, p
### Error output
If there are any errors at all, please include them here.

#### videojs
Version 7

**Comment by gkatsev** [comment]
A contributor wrote up a good blogpost and updated the DefinitelyTyped type defs for Video.js about how to use plugins and TS together. Hopefully, you find it useful and it answers your question: https://joeflateau.net/posts/video-js-heart-typescript.

**Comment by acharyaks90** [comment]
@gkatsev  Thanks for your Quick reply. It worked for me.
