### ISSUE TITLE
Videojs full screen button does not work in Android webview application.

### ISSUE THREAD

**Issue by halilozel1903** [videojs/video.js#6544]
Hello,

I use videojs player in the webview application.

When I open the Player screen, the full screen icon appears in passive state. It doesn't let me click on the icon.

I cannot perform full screen mode.

Can you help?

**Comment by mister-ben** [comment]
A webview does not support full screen by default, you need to add a WebChromeClient. See e.g. https://stackoverflow.com/questions/3815090/webview-and-html5-video

**Comment by halilozel1903** [comment]
@mister-ben I created a class named Chrome client. I inherited from the WebChromeClient class.

```
private class ChromeClient extends WebChromeClient {
        private View mCustomView;
        private WebChromeClient.CustomViewCallback mCustomViewCallback;
        protected FrameLayout mFullscreenContainer;
        private int mOriginalOrientation;
        private int mOriginalSystemUiVisibility;

        ChromeClient() {
        }

        public Bitmap getDefaultVideoPoster() {
            if (mCustomView == null) {
                return null;
            }
            return BitmapFactory.decodeResource(getApplicationContext().getResources(), 2130837573);
        }

        public void onHideCustomView() {
            ((FrameLayout) getWindow().getDecorView()).removeView(this.mCustomView);
            this.mCustomView = null;
            getWindow().getDecorView().setSystemUiVisibility(this.mOriginalSystemUiVisibility);
            setRequestedOrientation(this.mOriginalOrientation);
            this.mCustomViewCallback.onCustomViewHidden();
            this.mCustomViewCallback = null;

            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

        }

        public void onShowCustomView(View paramView, WebChromeClient.CustomViewCallback paramCustomViewCallback) {
            if (this.mCustomView != null) {
                onHideCustomView();
                return;
            }


            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);


            this.mCustomView = paramView;
            this.mOriginalSystemUiVisibility = getWindow().getDecorView().getSystemUiVisibility();
            this.mOriginalOrientation = getRequestedOrientation();
            this.mCustomViewCallback = paramCustomViewCallback;
            ((FrameLayout) getWindow().getDecorView()).addView(this.mCustomView, new FrameLayout.LayoutParams(-1, -1));
            getWindow().getDecorView().setSystemUiVisibility(3846 | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);


            // getWindow().getDecorView().setSystemUiVisibility(3846 | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
        }
    }
```

After these operations, the screen works in landscape mode but it does not work as I want.

It goes into strange shapes like in the pictures.Then it goes into horizontal mode. The same happens when I get out of landscape mode. How can I get rid of this situation?

<img width="869" alt="Screenshot 2020-03-30 at 11 40 42" src="https://user-images.githubusercontent.com/22895813/77892568-79e7ce00-727b-11ea-914b-a13ff4b3f646.png">

<br>

<img width="869" alt="Screenshot 2020-03-30 at 11 40 28" src="https://user-images.githubusercontent.com/22895813/77892579-7e13eb80-727b-11ea-993e-a2279481f5fa.png">

**Comment by halilozel1903** [comment]
I tried the examples but the same problem continues.
I need to solve this problem urgently. Can you support me? @gkatsev

**Comment by gkatsev** [comment]
Sorry, I've never dealt with enabling fullscreen on android webviews and it's a bit out of scope for the issue tracker. I did find this github project https://github.com/cprcrack/VideoEnabledWebView via this SO post https://stackoverflow.com/a/16179544 that may be helpful to you.

**Comment by StarStarCat** [comment]
@halilozel1903，hello，Finally ,do you solve this problem
