### ISSUE TITLE
Video progress bar does not show up on screens bigger then iPad

### ISSUE THREAD

**Issue by raresherta** [videojs/video.js#6545]
## Description
I have an issue with videos on Chrome. Whenever I play a video on a bigger screen than the iPad resolution I see no progress bar and the label LIVE is showing, the duration is also Infinity. When I resize the browser screen the duration is fixed and the control bar is displayed.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Progress bar displayed on bigger screens also.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
Chrome
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
LIVE only shows up when we are playing a live stream, this generally is represented by a duration of `Infinity`. Is the duration changing from a finite value to `Infinity` when you resize the player or is it Infinity only on load?
Have a reduced test page we can try it out on?

**Comment by raresherta** [comment]
Yes the duration changes to Infinity when I resize the browser from a smaller screen to a bigger screen.

**Comment by gkatsev** [comment]
That's incredibly bizarre. This is the first time I've heard anything like this. Can you provide a reduced test case? Unfortunately, without a reduced test case there isn't much we can do to help.
