### ISSUE TITLE
ios  sometimes play button doesn't work

### ISSUE THREAD

**Issue by hxw93** [videojs/video.js#6550]
## Description
Briefly describe the issue.
On ios, when you get the path, you create a popover, initialize the video, close the popover and destroy the video. The problem is that after the video is initialized, sometimes the play button is clicked and the play event is not triggered, and sometimes the play event can be triggered by clicking the play button
This problem doesn't appear on android

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
click play button， can play or show loading.

### Actual
click play button,neither the play event is triggered nor the state in the load is displayed,just change the background color of the play button

### Error output
no error output

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
v6.13.0 and  v7.7.6 both has the problem

#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Do you have a reduced example?

**Comment by hxw93** [comment]
> Do you have a reduced example?

I'm really sorry to reply you so late, but I found that this kind of situation happens when the network speed is very slow. At this time, clicking the play button will not respond, and there will be no prompt
