### ISSUE TITLE
use videojs-flashls-source-handler, can't play m3u8 on IE 11(win7、10)

### ISSUE THREAD

**Issue by yanliang-code** [videojs/video.js#6552]
## Description
I want play m3u8 on IE11/win7,use videojs-flash and videojs-flashls-source-handler,both can't play m3u8 on IE 11(win7、10)
![issue1](https://user-images.githubusercontent.com/60208330/77869916-a814e000-7272-11ea-9ff7-bb4b7bdf1d72.png)
![issue2](https://user-images.githubusercontent.com/60208330/77869920-ab0fd080-7272-11ea-94fb-c9d69a8e057f.png)

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
IE 11(win7、10)
### plugins
videojs-flash2.2.1  videojs-flashls-source-handler1.1.2

**Comment by gkatsev** [comment]
Any errors in the dev console? Did you configure Video.js to use the custom swf, see https://github.com/brightcove/videojs-flashls-source-handler#usage.

Also, generally, we recommend opening this issues against the specific plugin used rather than Video.js.

**Comment by yanliang-code** [comment]
ok. I see
I can play m3u8 in ie11/win7 now, but I have new problems
dev console have a error，and  timeline no use . click to restart automatically (ie11/win7)
![issue3](https://user-images.githubusercontent.com/60208330/78022479-94a76900-7387-11ea-9f4d-fcffee0dcbd7.png)
![issue4](https://user-images.githubusercontent.com/60208330/78022489-98d38680-7387-11ea-9eda-cece41bb4f72.png)

**Comment by yanliang-code** [comment]
Above phenomena exist in vue project (require plugins)
Above phenomena no exist in html (script)
