### ISSUE TITLE
How to get back and forth using video.js in Android webview app?

### ISSUE THREAD

**Issue by halilozel1903** [videojs/video.js#6559]
Videojs is used in the Android webview application. The back-forward functions on video.js do not work. How do I solve this situation. I am waiting for your support.

**Comment by gkatsev** [comment]
Can you please elaborate on what you mean? I don't understand what you're trying to do and need help with. Please be as detailed as possible, preferably with a test case.

**Comment by halilozel1903** [comment]
I open the application on the Android device. I'm playing live streaming content.I can't get the player bar back - forth. When I do this, the content is stopped.How can I do forward-backward transactions. Help me please.

![image](https://user-images.githubusercontent.com/22895813/78042165-548db980-737a-11ea-8d30-5581fcfff243.png)

**Comment by gkatsev** [comment]
It would definitely depend on the live stream. Some live streams only include a couple of segments in the manifest and so it doesn't allow seeking. In Video.js 7.7.6, we added a fix that hides the liveui if the amount of segments in the manifest is too short to be meaningful (~30 seconds) https://github.com/videojs/video.js/pull/6409.

**Comment by halilozel1903** [comment]
> It would definitely depend on the live stream. Some live streams only include a couple of segments in the manifest and so it doesn't allow seeking. In Video.js 7.7.6, we added a fix that hides the liveui if the amount of segments in the manifest is too short to be meaningful (~30 seconds) #6409.

I can get back and forwards 45 minutes in the web application. The range value is not as short as you say. It doesn't let me take it back and forth on the Android app.

**Comment by gkatsev** [comment]
Oh, I somehow completely missed that this is for Android, sorry.  You likely need to enable `overrideNative` https://github.com/videojs/http-streaming/#overridenative
For example:
```js
// via the constructor
var player = videojs('playerId', {
  html5: {
    hls: {
      overrideNative: !videojs.browser.IS_ANY_SAFARI
    },
    nativeAudioTracks: false,
    nativeVideoTracks: false
  }
});
```
