### ISSUE TITLE
Some HLS playlists return (CODE:3 MEDIA_ERR_DECODE) on Chrome

### ISSUE THREAD

**Issue by gargshivank** [videojs/video.js#6560]
### Description
Some HLS playlists return MEDIA_ERR_DECODE  and (CODE:-3 undefined) on Chrome browser (Version 80.0.3987.149 ). Stream works fine in other browsers like: Firefox(Version: 75.0b11 ),Opera(Version: 67.0.3575.97)

## Steps to reproduce
 http://cdnk.onmo.com/cdntest.html?clip=05540548.mp4&ext=m3u8&streaming=1&context=/MADE/KIDS/&type=video
   1.click on the link 

## Results
Video is stopping just after start in 1 second.

### Error output
There are 2 kind of errors in the console after click on play button:

VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.
      MediaError {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}

VIDEOJS: ERROR: (CODE:-3 undefined) Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
     MediaError {code: -3, type: "APPEND_BUFFER_ERR", message: "Failed to execute 'appendBuffer' on 'SourceBuffer'…The HTMLMediaElement.error attribute is not null.",
     originalError: DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attrib…}

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Video.js 7.7.5
#### browsers
Chrome browser (Version 80.0.3987.149 )
#### OSes
Windows 10,Mac Os

**Comment by maheshkumarpatil** [comment]
Hi,

We are also facing the same issue and is exactly the same issue posted. Any help will be appreciated.

Thanks in advance

**Comment by vkulov** [comment]
We are getting the same error in Chrome

video.js:84 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 

```

00:00:00.000 | info | "ChunkDemuxer"
-- | -- | --
00:00:00.005 | pipeline_state | "kStarting"
00:00:00.107 | kVideoTracks | [{"alpha mode":"is_opaque","codec":"h264","coded size":"1280x720","color space":"{primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}","encryption scheme":"Unencrypted","has extra data":false,"hdr metadata":"unset","natural size":"1280x720","orientation":"0°","profile":"h264 baseline","visible rect":"0,0 1280x720"}]
00:00:00.107 | kAudioTracks | [{"bytes per channel":2,"bytes per frame":4,"channel layout":"STEREO","channels":2,"codec":"aac","codec delay":0,"discard decoder delay":false,"encryption scheme":"Unencrypted","has extra data":false,"profile":"unknown","sample format":"Signed 16-bit","samples per second":16000,"seek preroll":"0us"}]
00:00:00.120 | kIsAudioDecryptingDemuxerStream | false
00:00:00.120 | kAudioDecoderName | "FFmpegAudioDecoder"
00:00:00.120 | kIsPlatformAudioDecoder | false
00:00:00.120 | info | "Selected FFmpegAudioDecoder for audio decoding, config: codec: aac, profile: unknown, bytes_per_channel: 2, channel_layout: STEREO, channels: 2, samples_per_second: 16000, sample_format: Signed 16-bit, bytes_per_frame: 4, seek_preroll: 0us, codec_delay: 0, has extra data: false, encryption scheme: Unencrypted, discard decoder delay: false"
00:00:00.120 | debug | "Video rendering in low delay mode."
00:00:00.122 | kIsVideoDecryptingDemuxerStream | false
00:00:00.122 | kVideoDecoderName | "MojoVideoDecoder"
00:00:00.122 | kIsPlatformVideoDecoder | true
00:00:00.122 | info | "Selected MojoVideoDecoder for video decoding, config: codec: h264, profile: h264 baseline, level: not available, alpha_mode: is_opaque, coded size: [1280,720], visible rect: [0,0,1280,720], natural size: [1280,720], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
00:00:00.122 | pipeline_state | "kPlaying"
00:00:00.123 | debug | " Detected midstream configuration change PTS:0 Sample Rate: 8000 vs 16000, ChannelLayout: 2 vs 3, Channels: 1 vs 2"
00:00:00.124 | audio_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}
00:00:00.169 | video_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}
00:00:00.169 | dimensions | "1280x720"
00:00:00.169 | kResolution | "1280x720"
00:00:00.169 | pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
00:00:00.048 | duration | 3046.283999
00:00:01.755 | info | "Effective playback rate changed from 0 to 1"
00:00:01.755 | event | "kPlay"
00:00:45.928 | info | "video decoder config changed midstream, new config: codec: h264, profile: h264 baseline, level: not available, alpha_mode: is_opaque, coded size: [448,252], visible rect: [0,0,448,252], natural size: [448,252], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
00:00:46.302 | error | "VDA Error 4"
00:00:46.302 | error | "video decode error!"
00:00:46.594 | pipeline_error | "PIPELINE_ERROR_DECODE"
00:00:46.594 | event | "kPause"
00:00:46.594 | pipeline_state | "kStopping"
00:00:46.596 | pipeline_state | "kStopped"

```

The hls stream plays fine after Chrome restart. But after a few days of using the browser it gets stuck again with the exact same error. And it gets stuck every time you try to play the stream. Again after restarting the browser it plays fine.

We have tried different versions of video.js even 2 year old ones and it behaves the same way.

The playback works fine with hls.js with the exact same stream so we are thinking of switching the player.

**Comment by gkatsev** [comment]
Can you try your stream with https://videojs-http-streaming.netlify.app/ and see if it's improved?

Also, there's some more info on PIPELINE ERROR DECODE on here https://github.com/videojs/video.js/issues/6093 and it seems one solution is to re-encode the stream.
