### ISSUE TITLE
[suggestion] Make the middle mouse button toggle fullscreen

### ISSUE THREAD

**Issue by elypter** [videojs/video.js#6562]
The middle mouse button/scroll wheel click is currently not used. Generally it is often used as a double click replacement so in my opinion that bahavior would fit quite well for a media player. Switching between fullscreen and normal mode is an action that is performed quite often and it is alway a little jarring if the video is shortly paused or played or longer if you happen to click once too often or too few. It could make for a much cleaner ux for users who are using a mouse or a touchpad with a middle button or a middle button gesture if only a single button press is needed.

**Comment by gkatsev** [comment]
Thanks, that's an interesting idea. We do have double-click to fullscreen, so, I'm not sure also having it on middle click is necessary.

**Comment by elypter** [comment]
vido.js doesn't use the middle button for anything currently, so why not?

**Comment by gkatsev** [comment]
It's still extra code that we need to maintain, even if it's not a large piece. Also, we have limited bandwidth for implementing features that are not largely requested.
