### ISSUE TITLE
Quality levels not working in VideoJS V7.7.6 having issue with 

### ISSUE THREAD

**Issue by sunilstg** [videojs/video.js#6563]
## Description
I am facing issue with quality bitrate selection with videojs version v7.7.6. Also I have tried adding hls video bitrate selector plugin for below output but it is available only for nodejs not for normal self hosted javascript. Please help on this. 

 qualityLevels = player.qualityLevels();

for (var i = 0; i < qualityLevels.length; i++) {
  var quality = qualityLevels[i];
  if (quality.width >= 720) {
    quality.enabled = true;
  } else {
    quality.enabled = false;
  }
}

**Comment by gkatsev** [comment]
Can you provide more information on what you're trying to do and what you're seeing and what you're expecting to see? Preferably, please include a reduced test case as well.
I just tried quality levels locally with Video.js 7.7.6 and it is working fine.

**Comment by sunilstg** [comment]
Hi Gary,

Many thanks for your prompt response. Please find below details process of
self hosted video player development using video js framework on plain
html5, javaScript and CSS

1) Downloaded the latest version of video js from  -
https://github.com/videojs/video.js/releases/tag/v7.7.6
2) Added "video.min.js" file in project directory for locally use (Self
hosted) along with CSS and html5 pages.
3) Created videojs instance as given below in separate JS file - (sample
code copied from  https://github.com/videojs/http-streaming)
    var player = videojs('some-video-id');

player.src({
  src: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
  type: 'application/x-mpegURL',
  withCredentials: true

});

4) waiting for player ready event -
    player.ready(function(){
      console.log("Player ready for playback and next process....")
    })
5) I have review the documents - https://github.com/videojs/http-streaming
but as mentioned   *hls.representations  " * It is recommended to include
the videojs-contrib-quality-levels
<https://github.com/videojs/videojs-contrib-quality-levels> plugin to your
page so that videojs-http-streaming will automatically populate the
QualityLevelList exposed on the player by the plugin *"*

6) I have added below JS file just below the "*video.min.js*" file in html
page -
https://cdn.jsdelivr.net/npm/videojs-contrib-quality-levels@2.0.9/dist/videojs-contrib-quality-levels.cjs.min.js


7)  I tried getting below  qualityLevels on event *loadedmetadata but it is
giving me error on js loading itself- *
[image: image.png]

var qualityLevels = player.qualityLevels();
for (var i = 0; i < qualityLevels.length; i++) {
  var quality = qualityLevels[i];
  if (quality.width >= 720) {
    quality.enabled = true;
  } else {
    quality.enabled = false;
  }
}


However I have tried all possible way but not able to find proper js for
above quality levels or the same which will work in standalone (self
hosted) video.min.js in plain html JavaScript file.
Please help on this.


Warm regards,
Sunil Kumar

Solution Architect - Video and Streaming
New Delhi (India)
Mobile no. : +91 9784505007
Email: sunilstg@gmail.com
Google Hangout/Skype : sunilstg
Linkedin: http://linkedin.com/in/sunilstg

**Comment by gkatsev** [comment]
What you wrote sounds like it should work. Would you be able to put it up on a codepen or somewhere else live we can see and debug?

**Comment by sunilstg** [comment]
Hi Gary,

I got the issue why it was not working. Actually my project file
optimization (js minify and compiler) was creating issue but when I put js
file in ascending order it started working.  Please close this thread.

Many thanks for your valuable time and support to help on  this.


Best regards,
Sunil Kumar

**Comment by gkatsev** [comment]
Thanks for circling back.
