### ISSUE TITLE
Typescript: extend Plugin: 'player' does not exist

### ISSUE THREAD

**Issue by zhangciwu** [videojs/video.js#6564]
## Description

Using video.js and typescript, define a plugin using `extends` would come with error `'player' does not exist` if using `this.player`

It seems that typescript do not know there is a `player` member in `videojs.getPlugin('plugin')`

## Code 
```typescript
import videojs from 'video.js/core';

const Plugin = videojs.getPlugin('plugin');

class Danmaku extends Plugin {
  constructor(player, options) {
    super(player, options);
    this.player.on('pause', () => {});  // Error happens this line
  }
}

videojs.registerPlugin('Danmaku', Danmaku);
export default Danmaku;

```

### Actual
typescript compiler report an error:
```
Error:(8, 10) TS2339: Property 'player' does not exist on type 'Danmaku'.
```

### packages

```
    "video.js": "^7.6.6"
    "@types/video.js": "^7.3.5",
```

## Work around 
replace
```
const Plugin = videojs.getPlugin('plugin');
```
to
```
const Plugin = videojs.getPlugin('plugin') as any;
```
(let typescript think it's a blackbox)

**Comment by gkatsev** [comment]
The definitely typed video.js types maintainer wrote up this blog post, I hope that you'll find it useful: https://joeflateau.net/posts/video-js-heart-typescript.

**Comment by zhangciwu** [comment]
> The definitely typed video.js types maintainer wrote up this blog post, I hope that you'll find it useful: https://joeflateau.net/posts/video-js-heart-typescript.

I have read it, it just didn't cover this scenario (or any `this.xxxx` in the child class, like `this.player`, ` this.on`, etc. )

Or should I refer this bug to **DefinitelyTyped** ?

**Comment by gkatsev** [comment]
@joeflateau can you chime in? Is that something that's missing or just not obvious?

**Comment by joeflateau** [comment]
@gkatsev taking a look now

**Comment by gkatsev** [comment]
Thanks!

**Comment by joeflateau** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43558 fixed here

**Comment by gkatsev** [comment]
Awesome, greatly appreaciated!

**Comment by joeflateau** [comment]
You’re welcome. The DT PR has been merged. This can be closed.
