### ISSUE TITLE
Change language after instantiation

### ISSUE THREAD

**Issue by JohMun** [videojs/video.js#6565]
```
The language method of the player can be used to set the language after instantiation with language('es'). However, this is generally not useful as it does not update text that is already in place.
```

Is there no "good" option to change the language of the controls after instantiation? 
Would it be an option to reset the player and pass another language code to the constructor?
I have tried to reset the player by calling `.dispose` or `.reset` and call videojs again. Something happened, but then the player doesnt' work as expected anymore.

**Comment by gkatsev** [comment]
Disposing the player and creating a new with a new language should work. Unfortunately, we do not currently support changing the language after instantiation.

**Comment by JohMun** [comment]
Thx for your fast reply. Yes, I'm using this method and I found a solution for my issue. However, if the player disposes, it removes the video element from the DOM. So, I rerender my videojs component again, after the language changes. Furthermore, settings like the volume's value and the video playback time, must be set by hand.
