### ISSUE TITLE
Fullscreen on IOS uses native player

### ISSUE THREAD

**Issue by davidevaliante** [videojs/video.js#6567]
## Description
Pressing the fullscreen on IOS (both on safari and chrome) switches to native player while i would like to keep my own player since i've added some utility overlay. 
Works fine on Desktop and Android (Chrome)

## Steps to reproduce
Use video-js on ios device and enter fullscreen mode

## Additional Information
video-js version : 7.6.6
IOS version : 13.3.1

**Comment by gkatsev** [comment]
Unfortunately, there isn't anything that can be done on iOS beyond disabling the fullscreen button. Chrome on iOS will always use the native player. Safari will use the native player on iPhones but it should take the player fullscreen on iPads with version 12 and newer.

**Comment by rudyryk** [comment]
@gkatsev Just wondering, why not implement fullscreen emulation? Like, put style `"position: fixed"` and stretch to the entire viewport? This is not trivial but seems to be working approach to me. We'd also probably need apply rotation transform and get viewport size with script. This could be implemented on user side, of course, but it fits better to the library itself as an optional behaviour.

**Comment by gkatsev** [comment]
We do have a `fullWindow()` method available to do this. We think that it's actually not a great user experience compared to switching to the native player since there is still a lot of the native UI available.

**Comment by rudyryk** [comment]
@gkatsev Thank you, will take a look! Yes, I agree the native player works best for most cases but also sometime we want to display overlays / graphics / domain specific controls etc.
