### ISSUE TITLE
Click on Progress Bar

### ISSUE THREAD

**Issue by lawchihon** [videojs/video.js#6568]
## Description
Briefly describe the issue.
When clicking on the progress bar, sometimes it didn't jump to the clicked time.
Instead, the progress bar is in focus state.
https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Click randomly on specific time on the slider

### Expected
Please describe what you expected to see.
The video jump to the clicked time range

### Actual
Please describe what actually happened.
Sometimes, the progress bar get focused but the play time remain the same. 

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.7.5
#### browsers
what browser are affected?
Chrome
#### OSes
what platforms (operating systems and devices) are affected?
MacOS
### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-hotkeys
videojs-resolution-switcher

**Comment by gkatsev** [comment]
Unfortunately, I am unable to reproduce. Does it happen in the code pen or only on your site?

**Comment by risharde** [comment]
I notice that if I click anyone not within the grey line within the progressbar, the on mouse up event does not trigger either. Weirdest thing ever. 

This is the code I'm using, it works fine clicking on the small grey line within the progress bar, but clicking the black area doesn't trigger the event. However, the actual player does seek to that part of the video. Wondering if its a similar issue?

`
							player.controlBar.progressControl.seekBar.on('mouseup', function(event) {
								var seekBarEl = player.controlBar.progressControl.seekBar.el();
								var seekBarRect = videojs.dom.getBoundingClientRect(seekBarEl);
								var seekBarPoint = videojs.dom.getPointerPosition(seekBarEl, event).x;
								var duration = player.duration();
});
`

**Comment by chenbingchang** [comment]
我在7.5.5版本中也遇到类似的问题。点击进度条，有时候会没有反应或者定位的地方不对。有时候点击.video-js .vjs-play-progress:before这个元素会往前或往后跳一大段距离；

**Comment by lawchihon** [comment]
@gkatsev It happens on both code pen and my website. Also base on the comments above, I believe it is not something specific
