### ISSUE TITLE
Can I use brightcove videojs.ima3.min.js with open source VideoJS framework for commercial use of video player? 

### ISSUE THREAD

**Issue by sunilstg** [videojs/video.js#6569]
Hi, I am developing video player application of my own self hosted using videojs Framework  which will commercial be used for Indiatoday.in  Media Company based in India. 
I want to use below plugin in my opensource videojs player for playing ads. Can you please advise if below plugins I can use freely or any paid subscription have to take? 

https://players.brightcove.net/videojs-ima3/3/videojs.ima3.min.js
https://players.brightcove.net/videojs-ima3/3/videojs.ima3.min.css

Also I am using any other library from "players.brightcove.net" is also free for use of I need to take prior permission.  

Please advise on this so that I can use it in my player as open source free to use. 
Thanks

**Comment by marguinbc** [comment]
That version of the IMA plugin is specifically for use with Brightcove Players but Google's IMA SDK team has published a Video.js IMA plugin that you can use instead: 
[https://github.com/googleads/videojs-ima](https://github.com/googleads/videojs-ima
)

**Comment by gkatsev** [comment]
Most players.brightcove.net plugins are only licensed for usage with the Brightcove Player and while they are available aren't free to use.
Please use google's videojs-ima plugin that @marguinbc linked to.

**Comment by sunilstg** [comment]
Sure,

Thanks for your suport.
