### ISSUE TITLE
play .flv files with your product without flash plugin

### ISSUE THREAD

**Issue by martijintro** [videojs/video.js#6570]
is that possible?

**Comment by gkatsev** [comment]
You can try https://github.com/bilibili/flv.js and https://github.com/mister-ben/videojs-flvjs, but if that doesn't work for you there's not much else that can be done.

**Comment by martijintro** [comment]
OK thx, will look about it when i have the time...

Regards, Jan

**Comment by kaiyuanbaba** [comment]
用videojs-flvjs之后播放的时候报下面的错误：堵塞导致的吗？怎么解决
Maximum buffering duration exceeded, suspend transmuxing task

**Comment by jayjupdhig** [comment]
???
