### ISSUE TITLE
requestFullscreen not trigger under custom Playback Technology

### ISSUE THREAD

**Issue by lawchihon** [videojs/video.js#6573]
## Description
Briefly describe the issue.
The customized Playback Technology doesn't have control with fullscreen.
Customized `requestFullscreen` function will never be trigger
Fullscreen trigger doesn't call `supportsFullScreen` for the custom tech

Example: https://codepen.io/lawchihon/pen/bGdXvBy

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. register a custom tech with specify `requestFullscreen` and `supportsFullScreen` function 
2. Use the custom to play video, and click on the fullscreen trigger

### Expected
Please describe what you expected to see.
The custom tech `requestFullscreen` will be fired

### Actual
Please describe what actually happened.
It is still firing the original `requestFullscreen`

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.7.5
#### browsers
what browser are affected?
Chrome
#### OSes
what platforms (operating systems and devices) are affected?
MacOS
### plugins
are any videojs plugins being used on the page? If so, please list them below.
As an example, a simply modified `videojs/videojs-youtube`

**Comment by gkatsev** [comment]
By default, Video.js will take the Player itself to fullscreen if possible, that is, if the [fullscreen api](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) is present in the browser. Only if it isn't, then it will ask the tech if it can handle it. This is mostly used for handling thigs like iPhones or older iPads (as newer iPads support teh fullscreen api).
Should the tech not support handling fullscreen, then it'll use Video.js's "full window" mode which stretches the player to the size of the viewport.
