### ISSUE TITLE
Adding Child

### ISSUE THREAD

**Issue by vamsimudadla** [videojs/video.js#6575]
## Description
1. I want to add a react component as child in videoJS and I have gone through the docs. But I understand how to add child. Could anyone give me an example to add a react component as child using player.addChild('Component').
https://docs.videojs.com/tutorial-react.html

2. Can we render components in ModalDialog?

**Comment by gkatsev** [comment]
The second section https://docs.videojs.com/tutorial-react.html shows how to add a react component as a child of Video.js. The syntax highlighting is a but broken but the info is there. Eventually, the new componnt gets added in the player's componentDidMount method
```
    this.player.getChild('controlBar').addChild('vjsEpisodeList', {});
```

You probably can use the same method to render as part of a modal dialog but the modal dialog also just accepts a DOM element, so you could theoretically just do `player.createModal(myReactComponentEl)` or something.

**Comment by vamsimudadla** [comment]
thank you @gkatsev

**Comment by gkatsev** [comment]
You're welcome.

**Comment by Blueguy0301** [comment]
Hi, is there any functional component sample of this ?
