### ISSUE TITLE
Can't stream RTMP

### ISSUE THREAD

**Issue by jingwei95** [videojs/video.js#6578]
## Description
I am a newbie to videojs so please forgive me but I have tried a lot and look into the requests.

I am trying to build a website with rtmp stream. It worked with only implementing on the html file, but what i am trying to do is to allow user to click on a button so the video player only shows. So i moved the initializing video player code to the backend as below
![image](https://user-images.githubusercontent.com/23036188/78886160-577e5d80-7a90-11ea-8e17-2ff37a4b70a9.png)

but then i encounter two problems which are 
1. **video.es.js:95 VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.**
and
2.**video.es.js:95 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.** 

Is there any solution to solve this?

**Comment by mister-ben** [comment]
You'd need to include the [flash tech](https://github.com/videojs/videojs-flash) if you haven't, but the bigger issue now is increasingly few end users' browsers support Flash, have it installed and have it enabled. Most live streaming is now HLS.

**Comment by jingwei95** [comment]
> You'd need to include the [flash tech](https://github.com/videojs/videojs-flash) if you haven't, but the bigger issue now is increasingly few end users' browsers support Flash, have it installed and have it enabled. Most live streaming is now HLS.

Thank you for ur reply. I did add in the videojs-flash in my HTML file but it is still now working.
![image](https://user-images.githubusercontent.com/23036188/78958938-20558e00-7b1c-11ea-965d-f0ad1570ea20.png)
Is there anything I am still missing?
I noticed the problem of browsers supporting Flash. Because I am getting the source from an rtsp link and I converted it to rtmp. And I also noticed that chrome will not be supporting Flash after December 2020, so does that mean that the only will be converting my rtsp link to https?

**Comment by nameToJune** [comment]
I had the same problem with flash enabled, but RTMP didn't play,
Error CODE: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.
Looking forward to answer

**Comment by nameToJune** [comment]
That solved the problem,
All you need to do is import videojs-flash,
React Code
import "videojs-flash";

**Comment by gkatsev** [comment]
We highly recommend avoiding sending rtmp to clients. You can use things like nginx-rtmp to convert rtmp to hls or dash.

But meanwhile, you must include videojs-flash project and also you have to workaround browser restrictions like not having the player size too small.
