### ISSUE TITLE
HLS segments stopped downloading but the manifest was updating properly.

### ISSUE THREAD

**Issue by justinoue** [videojs/video.js#6580]
## Description
I have a very basic nginx rtmp in to hls out setup, single index.m3u8 manifest, and a completely stock cdn hosted video js player. I'm using cloudfront to serve the manifest and segments. Segments are set to cache for 3 hours, manifest is set to cache for 5 seconds.

I had two players running in different tabs. One player worked fine. The other just stopped downloading segments. The last downloaded segment was a 200. The manifest continued to download properly with no gaps. It eventually started working again after missing about 10 segments. Inspecting the manifest downloads shows a proper progression through the filenames with no stale manifests being fetched.

![image](https://user-images.githubusercontent.com/7965150/78918214-0d7c8400-7a5e-11ea-8484-5a969179bf9d.png)

There was no output in the console meaning no 404s or anything. Is there a way to turn on a verbose mode?

#### videojs
https://vjs.zencdn.net/7.7.5/video.js
#### browsers
Chrome 80
#### OSes
Ubuntu 18.04

**Comment by gkatsev** [comment]
Can you retry your stream with https://videojs-http-streaming.netlify.app? It's our upcoming playback engine which we hope to release this week. It has a lot of fixes around playback.
