### ISSUE TITLE
2Gb not streaming at all with latest version

### ISSUE THREAD

**Issue by thewebdevelopment** [videojs/video.js#6582]
2GB video file not streaming at all.It download 1Gb first then it starts to play.Any solution or suggestions.

I just want it to start the video after couple of mbs downloaded or even min 1000 200 or 500MB.

```
<head>
  <link href="https://vjs.zencdn.net/7.7.5/video-js.css" rel="stylesheet" />

  <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  


  <script src="https://unpkg.com/videojs-contrib-hls.js@3.2.0/dist/videojs-contrib-hlsjs.min.js"></script>

</head>

<body>

  <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="640"
    height="264"
    poster="MY_VIDEO_POSTER.jpg"
    data-setup="{}"
  >
    <!-- <source src="jellyfish-25-mbps-hd-hevc-30MB.mp4" type="video/mp4" /> -->
    <source src="http://127.0.0.1:8000/images/movie.mp4" type="video/mp4" />

    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a
      >
    </p>
  </video>

  <script src="https://vjs.zencdn.net/7.7.5/video.js"></script>


</body>
```

**Comment by gkatsev** [comment]
It's possible that your file doesn't have the metadata (moov atom) for playing back the file at the front of the file but rather at the back, which is fairly common for non-web focused encoders. The only real fix here is to re-encode the file to make sure that the moov atom is at the beginning of the file so playback can begin properly.
However, I don't really recommend trying to play a 2GB mp4 on the web, I'd recommend switching to a segment file format like HLS (or DASH).
