### ISSUE TITLE
"Error in parsing value for ‘right’.  Declaration dropped." spammed in console in Firefox when viewing HLS stream.

### ISSUE THREAD

**Issue by Robbcode** [videojs/video.js#6586]
## Description
"Error in parsing value for ‘right’.  Declaration dropped" is constantly spammed to console log when viewing HLS Stream in Firefox.

## Steps to reproduce
View HLS stream using videojs v7.7.5 - v7.8.0 in using Firefox v75.0

### Actual
Please describe what actually happened.

### Error output
Console log is constantly filled with Error in parsing value for ‘right’.  Declaration dropped

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Seems to effect v7.7.5 - v7.8.0 
Previous version v7.7.4 of videojs did not have this issue.

#### browsers
Firefox
#### OSes
Windows 10
### plugins
None

**Comment by gkatsev** [comment]
Do you have a test stream we can play around with that you see this issue happen in?
