### ISSUE TITLE
cors to enable cookies not working for captions

### ISSUE THREAD

**Issue by khavishbhundoo** [videojs/video.js#6587]
I already have `crossorigin="use-credentials"` in my `<video>` tag and i can stream videos from `test.example.com` just fine with cookies. However within tracks cookies are not being set.

Here is how i set the tracks inside `<video>` 

`<track kind="captions"  src="https://test.example.com/..."   srclang="es-MX" label="Spanish (Mexico)" />`

**Comment by gkatsev** [comment]
That's been a long-standing issue because we haven't had a native crossOrigin property. Now with that in Video.js 7.8.0, we can finally add it in: #6588.

**Comment by khavishbhundoo** [comment]
@gkatsev 

Thanks for the quick fix . I created another issue for VHS cors so that its easy to track

https://github.com/videojs/http-streaming/issues/812
