### ISSUE TITLE
Issue clicking black area within the progressbar

### ISSUE THREAD

**Issue by risharde** [videojs/video.js#6589]
I notice that if I click anywhere within the progress bar other than the actual grey line within the progressbar, the on mouse up event does not trigger. The video will seek like normal to the new clicked time but the event will not get triggered.

This is the code I'm using, any ideas? Is this a bug? Spent days so far trying to figure this out, any help would be appreciated, thanks!

> 
player.controlBar.progressControl.seekBar.on('mouseup', function(event) {
   var seekBarEl = player.controlBar.progressControl.seekBar.el();
   var seekBarRect = videojs.dom.getBoundingClientRect(seekBarEl);
   var seekBarPoint = videojs.dom.getPointerPosition(seekBarEl, event).x;
   var duration = player.duration();
});

**Comment by actionTurtle** [comment]
following

**Comment by DispatchCommit** [comment]
Just add your `mouseup` event listener to the entire player. Right now you're only listening for mouse up events that occur exactly on `player.controlBar.progressControl.seekBar`, so naturally you'll receive events from *that* dom node. If you want to get events from the entire controlBar, just add the mouse up event listener to `player.controlBar`, or if you want to get it on the player, add it on the player.
