### ISSUE TITLE
docs need an update re: HLS support

### ISSUE THREAD

**Issue by chapman** [videojs/video.js#6590]
## Description
New to videojs, was trying to figure out HLS and confused by the official docs (e.g. FAQ) referring to videojs-contrib-hls. Did more digging and discovered built-in to videojs v7+, so just a note that those docs need updating to help avoid new users going down the wrong path (as I did!)

**Comment by chapman** [comment]
e.g. https://docs.videojs.com/tutorial-faq.html

**Comment by gkatsev** [comment]
You're 💯 we need to update those.
