### ISSUE TITLE
Why videojs is not working 2nd time with dynamically added html 

### ISSUE THREAD

**Issue by EABangalore** [videojs/video.js#6591]
## Description

I'm facing very much difficulty to initialize videojs, with dynamically added html.

In my project i need to display image,video in an single wrapper. that is why i'm adding html code dynamically

Steps to see my problem:

1. go to this codepen link  https://codepen.io/eabangalore/pen/PoPwQjZ

2. wait for 30sec videojs will come for the 1st time correctly in a dialog.

3.wait for another 30sec now videojs won't load.

want to answer this question on stackoverflow here is that https://stackoverflow.com/questions/61152985/why-videojs-is-not-playing-all-the-time-it-plays-for-the-first-time-only

**Comment by gkatsev** [comment]
I believe that the automatic initialization only happens when the viedo.js script loads and doesn't run again later. After adding your second video element to the page, you should call `videojs()` with that video element.

**Comment by EABangalore** [comment]
@gkatsev, as you said, After adding your second video element to the page, you should call `videojs()`

but i'm not adding 2 video element, i'm showing either `image` or `video` by replacing html.
