### ISSUE TITLE
> We need VAST for videojs 7.

### ISSUE THREAD

**Issue by geco** [videojs/video.js#6592]
> We need VAST for videojs 7.

No one yet implemented it or found a solution?

_Originally posted by @geco in https://github.com/videojs/video.js/issues/4766#issuecomment-612799034_

**Comment by gkatsev** [comment]
Unfortunately, we have no bandwidth to provide such a plugin.

You should be able to use the videojs-ima plugin as they support Video.js 6/7 and it supports vast, though, you'll have to be ok using IMA. Also, if there are any plugins that support Video.js 6, then they should work with Video.js 7 as well (the only major change was dropping support for IE8-10).
