### ISSUE TITLE
Can not load subtitle

### ISSUE THREAD

**Issue by asas111111** [videojs/video.js#6593]
Hello,
The VideoJS is can not loading subtitle(.vtt file) in the new Microsoft Edge based on Chromium. I can not see anything in it, and in the old Microsoft Edge is good for test.
I don't know why it doesn't working.
subtitle path contains Chinese characters
subtitle language: Chinese
VideoJS language: Chinese

**Comment by gkatsev** [comment]
Do you have a sample? Does this happen on windows or macos or both?
Just tried locally on macos and it loaded fine.

**Comment by asas111111** [comment]
The Windows 10 Version 1909。It's good before I installed new Microsoft Edge based on Chromium.
I don’t have samples because the movie is large.
