### ISSUE TITLE
feature request: libmpeg2 support

### ISSUE THREAD

**Issue by grkblood13** [videojs/video.js#6594]
I would like to request that support be added for mpeg2 video via the free decoder libmpeg2.  http://libmpeg2.sourceforge.net/

Thanks!

**Comment by gkatsev** [comment]
Thanks for the suggestion however that isn't something that we are able to do. It's a pretty major undertaking, and we don't have the bandwidth. Maybe if someone spent the time to compile it with emscripten or ported it to wasm, creating a tech for it to video.js wouldn't be hard.

**Comment by grkblood13** [comment]
Do you know if theres a tech for ffmpeg since that was already been ported using emscripten? I've gotten ffmpeg_asm.js running, but I have no clue about this tech feature you're talking about.
