### ISSUE TITLE
Fast forward by double click the right side of the screen &  Rewind by double click on the Left Side of the screen.

### ISSUE THREAD

**Issue by javgod** [videojs/video.js#6595]
Hello,
I am trying to achieve the above mentioned scenario with video JS but It's not working,
The Code within the script tag that I am using;

`<script>var vid1 = videojs('example_video_1'); vid1.on('dblclick', function() { vid1.currentTime() + 10; }); vid1.on('dblclick', function() { vid1.currentTime() - 10; });</script>`

You mentioned [here](https://github.com/videojs/video.js/issues/4662) that it's fairly easy to attain, but It's not working for me.
I would be glad if I could know where my code is wrong.

Thanks

Best Regards.

**Comment by tomByrer** [comment]
Might be best if you put up a demo with everything else working, including a button that can fastforward & rewind (even if not on the screen, maybe by the play buttton).  That would be far easier to troubleshoot.

**Comment by javgod** [comment]
Hello,
@tomByrer 
Thanks for replying. 
Here is the demo of the HTML code that I am using: 

https://codepen.io/ChrisPandey/pen/eYpJEBa

Thanks again,

Best Regards.

**Comment by tomByrer** [comment]
ty @javgod, unfortunately it doesn't work in Firefox or Vivaldi Win10.
FF wrong meme time
V nothing will play

**Comment by javgod** [comment]
@gkatsev Sir,
Can you please review this & point to the right direction ?

Regards.

**Comment by gkatsev** [comment]
It's likely that because Videojs listens to `dblclick` you aren't able to get it. See https://docs.videojs.com/tutorial-options.html#useractions.doubleclick for docs on how to customize the built-in double click action.

**Comment by jayrajzala** [comment]
for me changing the **z-index** of certain elements worked. see my code, 


`//use this only after the player is ready, wither on callback function or like this.

playerJS.ready(function () {
  this.el_.querySelector(".vjs-big-play-button").style = "z-index: 102";
  this.el_.querySelector(".vjs-poster").style = "z-index: 101";
  this.el_.querySelector(".vjs-text-track-display").style = "z-index:100; pointer-events:auto;";

// ".vjs-text-track-display" is the actual video element excluding the controls, so you want to set an event listener on that rather than the whole player.

  document.querySelector(".vjs-text-track-display").addEventListener("dblclick", function (e) {

//the class ""vjs-touch-enabled"" is only present when the device is touch-enabled. 
    if (playerJS.el_.classList.contains("vjs-touch-enabled")) {
      const playerWidth = document.querySelector("#my-player").getBoundingClientRect().width;

//I have divided screen into three equal parts. if i double click on middle it will play/pause the video 
      if (0.66 * playerWidth < e.offsetX) {
        playerJS.currentTime(playerJS.currentTime() + 10);
      } else if (e.offsetX < 0.33 * playerWidth) {
        playerJS.currentTime(playerJS.currentTime() - 10 < 0 ? 0 : playerJS.currentTime() - 10);
      } else {
        if (playerJS.paused()) {
          playerJS.play();
        } else {
          playerJS.pause();
        }
      }
    }
  });
});`

**Comment by jayrajzala** [comment]
**setting pointer-events to auto on ".vjs-text-track-display" worked.** 

- the provided userActions.doubleClick event function only works with desktop. and not mobile. but this workaround works for both. see my code

`

> //use this only after the player is ready, either on callback function or like this.

playerJS.ready(function () {
  this.el_.querySelector(".vjs-text-track-display").style.pointerEvents = "auto"

> // ".vjs-text-track-display" is the element excluding the controls, so you want to set an event listener on that rather than the whole player.

  document.querySelector(".vjs-text-track-display").addEventListener("dblclick", function (e) {

> //the class ""vjs-touch-enabled"" is only present when the device is touch-enabled. 

    if (playerJS.el_.classList.contains("vjs-touch-enabled")) {
      

> //I have divided screen into three equal parts. if I double click on middle it will play/pause the video, otherwise, it will forward or rewind.

const playerWidth = document.querySelector("#my-player").getBoundingClientRect().width;
 
      if (0.66 * playerWidth < e.offsetX) {
        playerJS.currentTime(playerJS.currentTime() + 10);
      } else if (e.offsetX < 0.33 * playerWidth) {
        playerJS.currentTime((playerJS.currentTime() - 10) < 0 ? 0 : (playerJS.currentTime() - 10));
      } else {
        if (playerJS.paused()) {
          playerJS.play();
        } else {
          playerJS.pause();
          }
      }}});});`
