### ISSUE TITLE
Building Components with Plugin 

### ISSUE THREAD

**Issue by abprojects** [videojs/video.js#6596]
I've run into a bug trying to get the rangeslider plugin to work with videojs. (Found here https://github.com/danielcebrian/rangeslider-videojs). I am aware that the author doesn't maintain the plugin anymore, but am trying to get it to work. I've also followed some of the compiler issues mentioned in #2016, #2578, and followed the thread on the switch to Uglify. I've used the developer version to avoid those issues, but still get the same error thrown.

The error that's thrown is this:
![Screenshot_2020-04-15_12-00-17](https://user-images.githubusercontent.com/12670336/79382486-6f366580-7f18-11ea-8e4e-5eba5b171aaa.png)

The component is loaded onto the player via this:
![rs_2020-04-15_12-00-17](https://user-images.githubusercontent.com/12670336/79382607-9ab95000-7f18-11ea-9ba2-d7c9ab608881.png)

When I inspect the player component, I can see RSTimeBar (the source of where the error is thrown) loaded in the array for options_.children of seekbar, but it is not loaded under seekbar.children:
![console_2020-04-15_12-35-23](https://user-images.githubusercontent.com/12670336/79382731-d5bb8380-7f18-11ea-89c8-de3d4018f73d.png)

I've run out of ideas. Could someone point me in the right direction on this? 

Thanks!

**Comment by gkatsev** [comment]
Are you trying to add this component as a child of the seek bar at runtime? If so, you generally want to use `addChild`. I would also advise against modifying pseudo-private (suffixed with `_`) properties.

```js
player.controlBar.addChild('controlTimePanel');
```
