### ISSUE TITLE
Please tell me how to set the resolution

### ISSUE THREAD

**Issue by YO55-lab** [videojs/video.js#6597]
How should I implement it so that the resolution can be selected in video.js?

For example, 720p, 480p

Where should I look in the official guidelines?

**Comment by gkatsev** [comment]
As was answered in video-dev slack, you can use https://github.com/chrisboustead/videojs-hls-quality-selector or the silvermine quality picker plugin for mp4s. Though, doing it for mp4s isn't a great user experience.
