### ISSUE TITLE
XHR is never used when the src type is different from "application/x-mpegURL"

### ISSUE THREAD

**Issue by pauloolileal** [videojs/video.js#6601]
## Description
I'm using HLS simply because I need to pass a token, it's not live streaming. 
However I found that when I change the mime to "video/mp4" it doesn't work and when I leave "application/x-mpegURL", my endpoint accepts and delivers the video but VideoJS does not play and displays the message "Problem encountered with the current HLS playlist. Trying again since it is the only playlist ".

If I remove security from my endpoint, without using hls and with the "veideo / mp4" mime it works normally.

```
videojs.Hls.xhr.beforeRequest = function (options) {
        var token = JSON.parse(localStorage.getItem("UserAuthenticated")).Token;
        options.headers = options.headers || {};
        options.headers.Authorization = 'Bearer ' + token;
        console.log('options', options);;
        return options;
    }
```

```
var player = videojs(id, {
        controls: true,
        preload: 'auto',
        html5: {
            hls: {
                withCredentials: true,
                overrideNative: true
            },
            nativeAudioTracks: false,
            nativeVideoTracks: false
        }
    });
```

```
player.ready(function () {
        this.src({
            src: source,
            type: "application/x-mpegURL",/*"video/mp4",*/
        });
    });   
```

#### videojs
Last
#### browsers
I tested on Chrome and Firefox
### plugins
Just the VHS for the HLS

**Comment by gkatsev** [comment]
I'm confused, is your content HLS or mp4? If it's HLS setting the `video/mp4` mimetype wouldn't work for playback and vice versa.
The `beforeRequest` thing only runs with HLS content and not mp4. For mp4 content we just hand the source to the browser for playback.

**Comment by pauloolileal** [comment]
So, my video is a mp4 hosted on a .net server, when I use the `video/mp4` mime and the server is unprotected it works, however this endpoint needs protection so I needed to use hls to be able to pass the header. The request with `application/x-mpegURL` reaches my endpoint but returns an error. `Problem encountered with the current HLS playlist. Trying again since it is the only playlist`

**Comment by gkatsev** [comment]
You can't play an mp4 as HLS, it won't work as you've seen.
Your best bet for mp4 playback may be to enable cookies and then set `crossorigin="use-credentials"` on the video element.

**Comment by pauloolileal** [comment]
Thanks for the quick answers, but how do I include the bearer token with cookies?

**Comment by gkatsev** [comment]
Not sure, your backend would need to be able to handle authorization via cookies instead. Alternatively, re-encode your video into HLS to be able to use the beforeRequest

**Comment by programisti** [comment]
I need to add bearer token when playing mp4 and other video formats, 
Is this possible?
