### ISSUE TITLE
How to remove the border around the player?

### ISSUE THREAD

**Issue by andrecool-68** [videojs/video.js#6602]
Please help to remove this border. This is increased by 400%

![Рамка вокруг плеера 0000](https://user-images.githubusercontent.com/3471892/79645089-ce64d600-81b5-11ea-897c-3afc35d9df64.png)
```

        <!DOCTYPE html>
        <html>
        <head>
          <link href="https://vjs.zencdn.net/7.7.5/video-js.css" rel="stylesheet" />

          <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
          <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
        </head>

        <body>
          <video
            id="my-video"
            class="video-js"
            controls
            preload="auto"
            width="640"
            height="264"
            poster="./video_film/Big_Buck_Bunny_Trailer_480x270.png"
            data-setup="{}"
          >
            <source src="./video_film/Big_Buck_Bunny_Trailer.m4v.mp4" type="video/mp4"/>
            <source src="./video_film/Big_Buck_Bunny_Trailer.ogv" type="video/ogv"/>
            <source src="./video_film/Big_Buck_Bunny_Trailer.webm" type="video/webm"/>
            <p class="vjs-no-js">
              To view this video please enable JavaScript, and consider upgrading to a
              web browser that
              <a href="https://videojs.com/html5-video-support/" target="_blank"
                >supports HTML5 video</a
              >
            </p>
          </video>

          <script src="https://vjs.zencdn.net/7.7.5/video.js"></script>
        </body>
        </html>
```

**Comment by andrecool-68** [comment]
To remove the border added these styles:
```
<style>
*:focus {
    outline: none;
}
</style>
```

**Comment by OwenEdwards** [comment]
Removing the focus outline, as described by @andrecool-68 above, violates WCAG accessibility - see http://www.outlinenone.com/ and https://a11yproject.com/posts/never-remove-css-outlines/. **Don't do it!!**

The simplest way to improve focus outline handling is by using the `:focus-visible` polyfill, as shown in https://github.com/videojs/video.js/blob/master/sandbox/focus-visible.html.example.

**Comment by andrecool-68** [comment]
@OwenEdwards 
> Don't do it!!

Very good advice)))
How do I remove this border?

**Comment by andrecool-68** [comment]
@OwenEdwards Do I need to add this script to the html file?
```
  <script>
    var vid = document.getElementById("vid1");
    var player = videojs(vid);

  </script>
  <script src="https://unpkg.com/focus-visible"></script>
```

**Comment by OwenEdwards** [comment]
@andrecool-68 yes, that will remove it on the video.js player for mouse users. It will still be visible for keyboard users. 

You may also need to change the CSS for the rest of your page to support the `:focus-visible` polyfill on any controls outside the video.js player, so that the behavior of the whole page is consistent. See https://github.com/WICG/focus-visible for more information.
