### ISSUE TITLE
How Can I use different URL?

### ISSUE THREAD

**Issue by mrseankumar25** [videojs/video.js#6606]
Hello I want to use different URL so that nobody can download my video, you have used blob:https://videojs.com/2b06667a-98a5-4682-ada3-4cfbdd266491

**Comment by gkatsev** [comment]
That source gets set when HLS or DASH video gets used. If you want to make it harder for people to download or capture your video look into DRM.

**Comment by mrseankumar25** [comment]
Hi Gary,

I have no idea about HLS and DASH or DRM, do you have any tutorial or something regarding this?

**Comment by mrseankumar25** [comment]
Hi Gary,

I am facing a new issue, it showing me this in the console and video not showing.

![2020-04-24_11-48-44](https://user-images.githubusercontent.com/43328839/80181106-d8f1f600-8621-11ea-8a6b-1ef5303c3db1.jpg)

**Comment by gkatsev** [comment]
That warning may be something you can ignore. Unfortunately, we can do very little to help without specific questions.

**Comment by mrseankumar25** [comment]
I am using this js
https://vjs.zencdn.net/7.7.5/video.min.js

and this js I am using for the player.
```
<video id="my-video" class="video-js vjs-theme-forest" width="640" height="264" poster="" data-setup="{}"></video>

<script>
  videojs(document.getElementById('my-video'), {
    autoplay: true,
    controls: true,
    loop: false,
  }).src({
    type: 'application/x-mpegURL',
    smoothQualityChange: true,
    src: "video/sample.mp4",
    withCredentials: true,
    overrideNative: true,
  });
</script>
```

**Comment by mrseankumar25** [comment]
Hi Gary, did you find anything?

**Comment by gkatsev** [comment]
I would recommend reading https://www.brightcove.com/en/blog/2018/07/dealing-drm-understanding-drm-and-how-produce-protected-content and https://bitmovin.com/guide-selecting-implementing-premium-content-protection/

**Comment by gkatsev** [comment]
Another resource https://github.com/Axinom/drm-quick-start
