### ISSUE TITLE
Only Audio Plays in a Video

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/video.js#6609]
I'm using the videojs-youtube plugin and sometimes only the audio plays as the poster of the video doesn't change. Other times, it plays normally.

Here's my code:

```
var options = {
	html5: {
    nativeAudioTracks: false,
    nativeVideoTracks: false
  },
 autoplay: false,
		controls:true,
		preload:"auto",
		    
	};
```
`	var player = videojs('my_video', options, function onPlayerReady() {
`  
```
   player.src({
      src: 'https://www.youtube.com/embed/b6QnHZEfI18',
       type: 'video/youtube'
     });
});

```

Any thoughts why is this happening? Thank you!

videoJS version: 6.7.4 (I tested newer versions but it didn't solve the problem)
browsers: chrome, firefox
plugins: videojs-youtube

**Comment by maryam-abdullah** [comment]
When I added this to my project, the player played without the video (only audio).
However, I found a way to reproduce this, if you only add some breakpoints (at handleTechLoadStart_ in video.js file), that way it will take more time to run the scripts, which results in playing only the audio.

**Comment by gkatsev** [comment]
Closing in favor of https://github.com/videojs/videojs-youtube/issues/560
