### ISSUE TITLE
Incorrect aspect ratio

### ISSUE THREAD

**Issue by ert55** [videojs/video.js#6611]
How do I change the aspect ratio of videos if at all possible? I have two rtsp camera streams one being 1280x720 the other 704x576. The latter should be displayed in 16:9 but it's always 4:3. I've tried using the aspectRatio function but it only changed the player size keeping the actual video proportions intact. I thought creating a master m3u8 playlist and changing the resolution there to e.g. 1024x576 would solve the issue by giving videojs a hint as to how to display the video, but it seems videojs disregards it.

**Comment by gkatsev** [comment]
Can you provide a couple of screenshot examples? Hard to tell what could be the issue. Is the video coming out squished? Or just playing back with a pillarbox or letterbox?
The aspectRatio option is for the player itself and has no bearing on the video. Often times, these issues arise from the video being badly encoded.

**Comment by ert55** [comment]
Video basically looks like the images below. The low res image should be stretched to 16:9. I managed to solve the problem by adding a listener that adds/removes a "transform:scale" style propery to/from the video container when the source resolution changes/player goes fullscreen etc. But I'm wondering if videojs already has a buildin function for that.
high res: https://i.imgur.com/erKAPdj.jpg
low res: https://i.imgur.com/Grdibts.jpg

**Comment by gkatsev** [comment]
Video.js doesn't apply any transform CSS to the video element.
