### ISSUE TITLE
Picture in Picture question

### ISSUE THREAD

**Issue by rayj00** [videojs/video.js#6612]
So I am using a single instance of video.js to play two separate  webrtc broadcasts.  I am using Cloudfront to distribute.  This works fine as I can view both broadcasts.

Now, when I try to do Picture-In-Picture,  I can't do both at the same time.  If I have one PIP up and try to PIP on the other, the original PIP goes away.

Is this normal or is not possible?

Thanks,

Ray

**Comment by gkatsev** [comment]
The browser only allows one video element to be using the native PiP at any given time.

**Comment by rayj00** [comment]
Is there any way around this on the client side?  I’d love to be able to play multiple PIP’s.

 

Ray

**Comment by gkatsev** [comment]
Not using the native browser PiP.

**Comment by rayj00** [comment]
So, even with two separate instances of Firefox up, it still can't be done.   That,  I don't understand?
I admit I'm a newbie at this.

**Comment by rayj00** [comment]
So, even with two separate instances of Firefox up, it still can't be done. That, I don't understand?
I admit I'm a newbie at this.


Ray
