### ISSUE TITLE
iOS 13.4 native player does not show captions

### ISSUE THREAD

**Issue by locpd** [videojs/video.js#6615]
## Description
On iOS 13.4.1 (iPhone specifically, no idea about iPad), native player (full screen mode) does not show captions/subtitles. Native player on iOS 13.3 works fine.
https://codepen.io/nastar/pen/VwvpjEM

Captions on [demo page](https://videojs.com/advanced/?video=elephantsdreammp4) seem to work though, but I have no idea how captions are added there.

#### videojs
Latest
#### browsers
Safari
#### OSes
iOS 13.4.1

**Comment by gkatsev** [comment]
Huh, that's super weird. I can't imagine it not work.

**Comment by ayconanw** [comment]
i have the same problem.
and ipad seems ok.

**Comment by blessedsan** [comment]
when i upgrade it from 13.4 to 13.4.1, the subtitle does not show on iphone .
then i try to upgrade to 13.5 beta3 see if apple has fixed the problem, but the problem remains.
---------
then i find, when i close the full screen mode by click X , and they click play, the subtitles shows.
it seems the ios can not load the subtitle at the first time, so need to exit the full screen mode, and then click play , and by doing that, the subtitles shows up.

but it is very bad experience for visitors, hope video.js can fix this compatibaility problem.

**Comment by raytiley** [comment]
I think I’m seeing something similar, however if I load the HLS stream in safari natively the captions are rendered way off the video screen. Seems like the videojs css might cover this up?

![49A582FF-2F2B-4FC1-A88C-9551172F8F81](https://user-images.githubusercontent.com/41680/83579832-56096880-a508-11ea-80d8-05f5bbbbb19f.jpeg)

**Comment by gkatsev** [comment]
Looks like this is the same as #6640. This is an iOS issue as things broke without us doing anything. It is likely an interaction with Video.js CSS and something that changed in iOS 13.4.1. We have a workaround in 7.8.3. See #6640 and #6673 for more info.
