### ISSUE TITLE
Video duration is NAN？

### ISSUE THREAD

**Issue by tanhao8** [videojs/video.js#6616]
Get video in Android for Nan, ask for help
Thank you @brandonarbini @heff

**Comment by gkatsev** [comment]
Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and helping you fix.

**Comment by tanhao8** [comment]
![微信截图_20200425100606](https://user-images.githubusercontent.com/47964060/80268756-714cb100-86dc-11ea-87ac-e0eb2922106b.png)
![微信截图_20200425100525](https://user-images.githubusercontent.com/47964060/80268760-77429200-86dc-11ea-9dfe-2b582eaa1dc0.png)

**Comment by tanhao8** [comment]
Hello, the above is my code snippet. The red mark is the length of time to get the video, but it can't be obtained in Android. It's Nan. @gkatsev

**Comment by tanhao8** [comment]
@gkatsev Apple 7 mobile phone can't get time

**Comment by gkatsev** [comment]
Apple 7 phone meaning iOS 7 or iPhone 7 because those are two very different things.

**Comment by smrb76** [comment]
@gkatsev 
here is my snapshot code:
`      this.player.on('loadedmetadata', () => {
          console.log(this.player.duration()) // log is NaN
        }
      }`
      in desktop everything is work but in mobile it`s log NaN!!

**Comment by robbiemie** [comment]
> @gkatsev here is my code: ` this.player.on('loadedmetadata', () => { console.log(this.player.duration()) // log is NaN } }` in desktop everything is work but in mobile(android and ios) NaN is displayed!!

Thanks!  you've solved my problem.
