### ISSUE TITLE
video.js file not loading in Samsung Smart TV

### ISSUE THREAD

**Issue by shahabvalizade** [videojs/video.js#6620]
I cannot play video on videojs player on Samsung smart TV (I play HLS stream)
to find the problem, I wrote a simple one line script and found that video.js (or video.min.js) local file not loading completely in smart TV. I also used CDN version and it didn't load too.
But in Desktop and mobile it will load completely.
is there any way to load it well on smart TV too?
I guess it is because of low TV memory and cannot load this whole file for player.

**Comment by gkatsev** [comment]
We've been able to play using Video.js on samsung smart TVs. Depending on the age of your samsung TV, it could be browser support. Older TVs are built on different versions of chromium and have a harder time being able to run things like Video.js.

**Comment by saffari-m** [comment]
@gkatsev what's the solution for older TVs? did you have any idea?

**Comment by dextermapalya** [comment]
did any one manage to play hls on samsung tv, I am experiencing same problem. Media Error file is corrupted....

**Comment by gkatsev** [comment]
Make sure you have overrideNative enabled https://github.com/videojs/http-streaming#overridenative

**Comment by JeppeTh** [comment]
What Samsung Version? I'm able to run at least some streams on K-series.

**Comment by mesutkoc** [comment]
Hi,
I want to ask some special question about this issue.
I am working on smart tv application based Samsung Tizen. 
Application works 2017+ model of year normally but 2015 and 2016 model couldnt work video. Using Video.js in application. If there is anyone who support me about this issue, thank you.
