### ISSUE TITLE
Tap on mute button twice caused video to pause on mobile view

### ISSUE THREAD

**Issue by xsq007** [videojs/video.js#6622]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play video on a mobile browser
2. Tap "mute" icon twice, you'll find the video is paused.

### Expected
Please describe what you expected to see.
Tap "mute" should not make video pause

### Actual
The video is paused once you tap the "mute" icon on a mobile browser.

### Error output
If there are any errors at all, please include them here.

## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs
Latest version of video.js (7.8.1).  The issue also exists on older versions.
#### browsers
Mobile browsers.
#### OSes
Android 10.0
### plugins
None

**Comment by xsq007** [comment]
Any update on this?

**Comment by gkatsev** [comment]
I cannot reproduce this via videojs.com/advanced on Android and latest Chrome.
