### ISSUE TITLE
Can we add the source mimetype for dash as well?

### ISSUE THREAD

**Issue by ssanth** [videojs/video.js#6623]
## Description
Briefly describe the issue.
"No compatible source was found for this media." for dash on chrome browser when you fail to pass in the mimetype for the video source.

We use a custom player built on top of videojs, noticed that dash playback worked fine on IE11 but failed on chrome. After little debugging we found it didnot send the mimetype along with the source file. We are now adding it on our side but it would be nice to be added to videojs mimetype 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. https://auricledstorm.htmlpasta.com/ provided repro page with code

Fix:
can we add mpd: 'application/dash+xml' to 
https://github.com/videojs/video.js/blob/master/src/js/utils/mimetypes.js#L10

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

what version of videojs does this occur with?
7.6.6, latest too
what browser are affected?
chrome, firefox, safari
what platforms (operating systems and devices) are affected?
Mac 
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Added in #7602
