### ISSUE TITLE
PR 6405 removed triggering the seekableendchange event from LiveTracker

### ISSUE THREAD

**Issue by SnapStreamJason** [videojs/video.js#6624]
## Description
This change - https://github.com/videojs/video.js/commit/668c7f44d62ce497042b659e948c9681339b4ddd - removed the triggering of the seekableendchange event from LiveTracker. This event was documented here: https://docs.videojs.com/tutorial-live.html

We had been using this event in our application to know when segments were added to the HLS playlist that was being played.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play an HLS playlist that has segments being added to it
2.
3.

### Expected
seekableendchange is triggered when the underlying m3u8 playlist changes

### Actual
No more events triggered 

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by brandonocasey** [comment]
Hey SnapStreamJason, we probably needed to do a better job communicating on this. The LiveTracker and the new liveui are still fairly experimental and the events that the `LiveTracker` fired were never intended to be relied upon. I wrote up a quick snippet of code for how the `seekableendchange` worked so that you can get similar functionality.

```js
var getSeekableEnd () => {
    var seekable = player.seekable();
    var seekableEnds = [];
    let i = seekable ? seekable.length : 0;

    while (i--) {
      seekableEnds.push(seekable.end(i));
    }

    // grab the furthest seekable end after sorting, or if there are none
    // default to Infinity
    return seekableEnds.length ? seekableEnds.sort()[seekableEnds.length - 1] : Infinity;

}

var lastSeekableEnd;

window.setInterval(funciton() {
	const seekableEnd = getSeekableEnd()

	if (!lastSeekabeEnd || lastSeekableEnd !== seekable) {
		// seekableendchange happened
	}
	lastSeekableEnd = seekableEnd;
}, 30);
```
