### ISSUE TITLE
Live UI not showing

### ISSUE THREAD

**Issue by ert55** [videojs/video.js#6628]
On my old samsung galaxy s2 the LIVE label never shows up for a live HLS stream. The seekbar is always visible though. The knob moves for ~10 sec, but when reaches 0:00 the bar won't disappear. On a desktop computer there's no such issue. It behaves like that with or w/o the liveui option. How do I fix that?

**Comment by gkatsev** [comment]
You may want to enable overrideNative to get our playback engine rather than using the native playback. https://github.com/videojs/http-streaming#overridenative
