### ISSUE TITLE
liveui has no effect for chrome

### ISSUE THREAD

**Issue by spring-zs** [videojs/video.js#6630]
## liveui has no effect for chrome
liveui has no effect when I use chrome of version 80.0.3987.149. The progress bar isnot hidden and in its place is not text that indicates LIVE playback.  But progress bar is hidden and in its place is LIVE.

So it is my fault,or it is a bug for chrome?

**Comment by gkatsev** [comment]
If the live stream has a short live window (less than 30 seconds) then we hide the live ui because seeking within a few segments isn't worth it.

**Comment by kellen** [comment]
Setting `options.trackingThreshold` to a lower value will get the liveUI to show up even with a short playlist, e.g.:

```
var options = {"liveui": true, "trackingThreshold": 2}
```
