### ISSUE TITLE
avi

### ISSUE THREAD

**Issue by liudianwei** [videojs/video.js#6634]
How to  play avi format video? anyone can help me?

**Comment by gkatsev** [comment]
Unfortunately, most browsers do not support avi format. Your best bet is to convert it to an h264 encoded mp4, for example via handbreak with the "for web" profile.

**Comment by liudianwei** [comment]
> Unfortunately, most browsers do not support avi format. Your best bet is to convert it to an h264 encoded mp4, for example via handbreak with the "for web" profile.

Thanks first, can we use js to tranform the format?

**Comment by xiaoqiMikko** [comment]
> 如何播放AVI格式的视频？有人可以帮助我吗？

你解决播放AVI格式的了没

**Comment by liudianwei** [comment]
> > 如何播放AVI格式的视频？有人可以帮助我吗？
> 
> 你解决播放AVI格式的了没

https://github.com/videojs/video.js/issues/6634#issuecomment-624171025

No, as Gary Katsevman said , most browsers do not support avi format.

**Comment by liudianwei** [comment]
> Unfortunately, most browsers do not support avi format. Your best bet is to convert it to an h264 encoded mp4, for example via handbreak with the "for web" profile.

And Can we use the specified browser to play avi format video?

**Comment by xiaoqiMikko** [comment]
Ok, thanks for your reply

**Comment by xiaoqiMikko** [comment]
Ok, thanks for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liudianwei"<notifications@github.com&gt;; 
发送时间: 2020年5月6日(星期三) 中午12:06
收件人: "videojs/video.js"<video.js@noreply.github.com&gt;; 
抄送: "哆啦A梦"<f670215631@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [videojs/video.js] avi (#6634)





   
如何播放AVI格式的视频？有人可以帮助我吗？
  
你解决播放AVI格式的了没
  
＃6634（评论）
 
不，正如Gary Katsevman所说，大多数浏览器不支持avi格式。
 
— 
因为评论，您收到此消息。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by liudianwei** [comment]
@mister-ben Sir,may I ask about that, can we use javascript to tranform the format?
https://github.com/videojs/video.js/issues/6634#issuecomment-624394034

**Comment by mister-ben** [comment]
No. You need to transcode videos first and delvier a supported format to the browser.

**Comment by xiaoqiMikko** [comment]
> 不需要。您需要先对视频进行转码，然后将支持的格式传送到浏览器。

Well, yes, I converted the avi format to mp4 format first and then sent it to the browser. Thanks for your advice
