### ISSUE TITLE
Library removes <track> tags, ¿why?

### ISSUE THREAD

**Issue by ATejerina** [videojs/video.js#6636]
## Description
Im trying yo use <track> tags on my videos, but video.js removes it.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open video.js tester , and add a 'track' tag after 'source' tag : https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0
2. Inspect elements, and you can see 'source' still there but 'track' doesnt.
3. If i check track list of my video, the result is: TextTrackList {length: 0, onchange: null, onaddtrack: null, onremovetrack: null}

Hope someone can help me.

**Comment by mister-ben** [comment]
It's normal for no track elements to be present in the rendered player DOM. There's probably a problem with your tracks or how they are hosted but without a reduced test case, it's impossible to say what.

**Comment by gkatsev** [comment]
In addition, you should use the Video.js API rather than interacting with the DOM directly. See https://docs.videojs.com/tutorial-text-tracks.html#text-tracks
