### ISSUE TITLE
Video.js 7.7.6 and above working with CDN

### ISSUE THREAD

**Issue by nwaughachukwuma** [videojs/video.js#6637]
I am getting the error: `Failed to load resource: the server responded with a status of 403 () ReferenceError: Can't find variable: videojs` when using the cdn for versions >= 7.7.6, but it works when I use version 7.7.5. Please what could the issue be?

**Comment by gkatsev** [comment]
The issue is that we still don't have an automated CDN deployment system and I always forget to push to the CDN. I'll do so now.

**Comment by gkatsev** [comment]
It is now up. Thanks for letting us know.

**Comment by nwaughachukwuma** [comment]
> The issue is that we still don't have an automated CDN deployment system and I always forget to push to the CDN. I'll do so now.

How could this be resolved? Is there any help needed to achieve this? @gkatsev

**Comment by gkatsev** [comment]
Just been incredibly busy with other things and so hadn't had a chance to prioritizing getting this automated yet. Unfortunately, I'm not sure there's much that others can help out with on that.

**Comment by ebeloded** [comment]
Seeing that the issue is closed, is the CDN deployment process automated? I wonder if we can rely on the published video.js version to grab it from CDN in production.

**Comment by gkatsev** [comment]
You can rely on the Video.js CDN for deployed versions. Unfortunately, the releases aren't automated right now, so, definitely verify the version you want is up before pushing it to production.
