### ISSUE TITLE
video can play hls,but no sound

### ISSUE THREAD

**Issue by hxw93** [videojs/video.js#6638]
## Description
In some browsers of ios, the video can play HLS, and the earphones have sound but no sound is played outside. It doesn't matter whether it is in mp4 or m3u8 format.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. load video
2. play video
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
###7.5+
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by liudianwei** [comment]
I have the same problem.Have you solved the problem

**Comment by liudianwei** [comment]
It may has been caused by Chrome ! Auto play with sound is not allowed!

**Comment by hxw93** [comment]
> It may has been caused by Chrome ! Auto play with sound is not allowed!

My problem is caused by the mute mode on the phone. I wonder if your problem is also caused by this reason, you can try to turn off the mute mode on the phone

**Comment by hxw93** [comment]
> It may has been caused by Chrome ! Auto play with sound is not allowed!

My problem is caused by the mute mode on the phone. I wonder if your problem is also caused by this reason, you can try to turn off the mute mode on the phone

**Comment by liudianwei** [comment]
No，The test I did on Windows

**Comment by liudianwei** [comment]
No. The test is done on Windows
