### ISSUE TITLE
No playback on android chrome

### ISSUE THREAD

**Issue by navanshu** [videojs/video.js#6639]
## Description
I am using the latest version of scripts videojs, contrib quality levels and https source selector. It was working perfectly in older version but now it is not working.

## Steps to reproduce
```javascript
var options =
        {
            userActions: {
                hotkeys: true,
            },
            plugins: {
                httpSourceSelector:
                {
                    default: 'auto'
                },
            },
            suppressNotSupportedError: true,
        };
        var player = videojs('#my-video', options);
        player.qualityLevels();
        player.httpSourceSelector();
```
## Results
On a desktop it is working fine. But on mobile devices it is not working. it says. 

### Error output
The media playback was aborted due to corruption problem.

## Additional Information
Please include any additional information necessary here. Including the following:
#### video.js@7.7.6
what version of videojs does this occur with?
#### browsers
chrome 81 and firefox 68
#### OSes
Android 10 
### plugins
videojs-contrib-quality-levels
videojs-http-source-selector

**Comment by gkatsev** [comment]
I can't imagine why it stopped working. Can you provide an example where you see it not working?
