### ISSUE TITLE
Captions are not displaying when using ios fullscreen mode

### ISSUE THREAD

**Issue by loveisalie92** [videojs/video.js#6640]
## Description
Hi,
I'm having issue with captions, when using ios phone in fullscreen mode. the caption is not displaying
This is the demo link (I'm using iphone x to test):
https://codepen.io/grbla/pen/xxxZPQm

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. open demo link with ios phone
2. play the video in fullscreen

### Expected
Caption displays in fullscreen mode

### Actual
Caption is not displaying

### Error output
None

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7
#### browsers
safari, chrome on ios
#### OSes
ios
### plugins
none

**Comment by ATejerina** [comment]
Im also interested in this issue, cause it happens to me with subtitles. It works for me in desktop, also on android devices, but not doesnt work for iOs.

**Comment by gkatsev** [comment]
Taking a look, there's definitely something funky going on here. We haven't changed anything related to captions. I think it's something that happened in a safari update.
Not sure what the root cause is yet, though.

**Comment by gkatsev** [comment]
FYI, I opened a webkit issue for this https://bugs.webkit.org/show_bug.cgi?id=212102

**Comment by loveisalie92** [comment]
Not sure if you know this product, Look like it's a videojs plugin.
The demo in this page doesn't has caption issue on my iPhone (tested on both chrome and safari)
https://www.nuevodevel.com/nuevo/showcase/captions

**Comment by loveisalie92** [comment]
Hi guys,
I think I got to the bottom of the issue.
This happens because of 1 css rule at:
.video-js.vjs-fullscreen {
  width: 100% !important;
  height: 100% !important;
  **padding-top: 0 !important;**
}

If you remove "padding-top: 0 !important;", caption will display normally in ios fullscreen mode but 
you will lose the control bar when in fullscreen mode for android devices.

I have fixed this by a work around:
1) remove the rule padding-top: 0 !important in .video-js.vjs-fullscreen
2) Check user agent to detect if it is not an iOS device, add that css rule:
var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent)
    if (!iOS) {
        var style = $('<style>.video-js.vjs-fullscreen{padding-top: 0 !important;}</style>');
        $('html > head').append(style);
    }

I can give you a working example which is my website if required

**Comment by gkatsev** [comment]
I can reproduce locally but I need to disable the entire set of fullscreen styles and not just the padding-top. I'll post a comment on the webkit bug.

Thanks for finding this @loveisalie92!

**Comment by GiuseppeEliano** [comment]
This answer from @loveisalie92 is a trick, but I believe that it cannot handle all cases.

**Comment by gkatsev** [comment]
Working on getting the workaround into Video.js https://github.com/videojs/video.js/pull/6673

**Comment by gkatsev** [comment]
Now available as part of v7.8.3, which is out as `next` on npm

**Comment by vladislavSp** [comment]
Problem is not fix... On IOS 14.6 in mobile safari caption (subtitles) is not displaying
Styles for .video-js.vjs-fullscreen:not(.vjs-ios-native-fs) available (videojs vesion 7.11.8)
`.video-js.vjs-fullscreen:not(.vjs-ios-native-fs) {
  width: 100% !important;
  height: 100% !important;
  padding-top: 0 !important;
}`

**Comment by vladislavSp** [comment]
@gkatsev
