### ISSUE TITLE
How to add a custom header in every request made by videojs

### ISSUE THREAD

**Issue by krackjack234** [videojs/video.js#6643]
## Description
Hi,

We want to add a custom header in every request that is made by video js.
We are using the videojs hls /dash contrib library for hls and dash

For HLS,

If we use the below code 

```
videojs.Hls.xhr.beforeRequest = function(options) {
  /*
   * Modifications to requests that will affect every player.
   */

    if (options.headers == undefined){
       options.headers = {}
    }
    options.headers["x-playback-session-id"] = "1234"
   
    return options;
  };

```

all the requests EXCEPT the parent manifest is getting modified with the new header. However we want even the parent manifest to have this custom header.

For DASH, we are not able to find a suitable way to add this custom header

Can someone please help?

Thanks.

**Comment by krackjack234** [comment]
One update.

We are able to add custom header in the master manifest file also. Problem was we were calling the code after the player was ready.

For DASH, however, we are still looking for the equivalent code to add the custom header.

Any help will be greatly appreciated

**Comment by gkatsev** [comment]
The same code will work for DASH content as well. `videojs.Hls` is our playback engine and plays back HLS and DASH. In VHS 2, we deprecated that name in favor of `videojs.Vhs` exactly to avoid this confusion.

**Comment by PaulCheriyan009** [comment]
i have used similer code  but it doesn't work  @gkatsev 
`    videojs.Hls.xhr.beforeRequest = function (options) {
      if (options.headers != undefined) {
        options.headers = { "user-agent": "session_id" };
      }
      return options;
    };`

**Comment by udf2457** [comment]
@gkatsev / @krackjack234 any chance one of you could give me some hints as to how you got this working with DASH ? Neither the “global” form (`videojs.Vhs.xhr.beforeRequest`) or the “player” form (`player.tech().vhs.xhr.beforeRequest`) seem to have any effect (no headers are ever sent)

**Comment by gkatsev** [comment]
Posting here for future reference for people. `beforeRequest` is a playback feature of the playback engine the Video.js project developers: videojs-http-streaming, or VHS for short. It's accessible via `videojs.Vhs.xhr.beforeRequest`.
Please make sure that you aren't including something like videojs-contrib-dash or another playback engine as that option won't work there. In addition, it may not be available if the native playback engine is used (for example HLS on Safari).

**Comment by BruceWheaton** [comment]
Thanks for that info - may save some head scratching. We're using videojs-contrib-dash to try to (no luck yet) get quality levels for a videojs-http-source-selector menu. Does that mean we won't have beforeRequest? Is there a known workaround?

**Comment by gkatsev** [comment]
It's likely that dashjs has a way to do it, but I'm not sure how. You'd have to check dashjs's documentation.

videojs-http-source-selector should work with our native playback too.

**Comment by BruceWheaton** [comment]
I'll look, thanks. I'd rather use the built-in player, but it won't play our mpd DASH files.

**Comment by gkatsev** [comment]
The types lib is likely out of date and doesn't include it. Unfortunately, it will always lag behind our functionality since we don't maintain it.

**Comment by DoanhNV** [comment]
Same Isssue. anyone have solution?

**Comment by dijonkitchen** [comment]
For HLS, I have this in a useEffect hook for a React component and it works for me. I ignored the Typescript error. 

```js
useEffect(() => {
            // Global change for all requests
            // @ts-ignore
            videojs.Vhs.xhr.beforeRequest = (options) => {
                    if (!options.headers){
                        options.headers = {}
                    }
                    options.headers["x-playback-session-id"] = "1234"
                }

                return options;
            };
}
```
