### ISSUE TITLE
In iOS,  fullscreenchange event is not firing while exit from the full screen

### ISSUE THREAD

**Issue by senthil88** [videojs/video.js#6645]
## Description
In iOS safari browser, when I am clicking on fullscreen icon fullscreenchange event is triggering.
The same event should be trigger while clicking on Exit fullscreen icon. But it's not triggering.

### Expected
fullscreenchange event should be trigger on both the fullscreen & exit fullscreen mode.

### Actual
fullscreenchange is not triggering.

## Additional Information
This issue might be on because of #6424 . Still I am not sure. 

When ever clicks on the fullscreen icon in the iOS safari browser, native player starts to play the video in fullscreen and also triggers the fullscreenerror event. On fullscreenerror, it's removing the following listener fullscreenchange, fullscreenerror. DomData (fullscreenchange,fullscreenerror) WeakMap reference also got removed. Dispatcher & elem is not available while  running this code 

this.trigger('fullscreenchange', {isFullscreen: false});

#### videojs
7.8.1
#### browsers
Mobile Safari
#### OSes
iOS

**Comment by LaughSun0513** [comment]
same here . The control bar play icon is error class when i exit .expect `.vjs-playing` but i got
`.vjs-paused`

**Comment by LaughSun0513** [comment]
> 👋 Thanks for opening your first issue here! 👋
> 
> If you're reporting a 🐞 bug, please make sure you include steps to reproduce it. We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.
> To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/videojs/video.js/blob/master/CONTRIBUTING.md).

same here . The control bar play icon is error class when i exit .expect .vjs-playing but i got
.vjs-paused

**Comment by chandarsunderraj** [comment]
can you try this ? 
`video.addEventListener('webkitendfullscreen', (e) => { //code to destroy my custom modal on close of x icon in ios native close button });`

I had a similar use case #6574

**Comment by gkatsev** [comment]
Thank you for everyone's patience. We have a potential fix for this with #6735. You can give it a shot here https://deploy-preview-6735--videojs-docs.netlify.app/test-example/. If you do, please let us know if it fixes the issue for you.
I'll be testing it this week and hopefully we can get the fix out this soon.
