### ISSUE TITLE
Passing JSON object as source: no compatible source found

### ISSUE THREAD

**Issue by ToishY** [videojs/video.js#6648]
## Description
After reading the documentation from `http-streaming`, which is already integrated in VideoJS 7, I wanted to parse a m3u8 file (using `m3u8-parser`) and stream the TS content.

The following is the example code from the [documentation](https://github.com/videojs/http-streaming#object-as-source):

```
var player = videojs('some-video-id');
const parser = new M3u8Parser();

parser.push(manifestString);
parser.end();

player.src({
  src: `data:application/vnd.videojs.vhs+json,${JSON.stringify(parser.manifest)}`,
  type: 'application/vnd.videojs.vhs+json'
});
```

I downloaded a random playlist, changed the TS segments to have absolute (working) URLs, and manually added it to a [**snippet**](https://codepen.io/toishy/pen/qBOyVRz). The manifest is parsed fine, but the problem is that VideoJS does not recognize it as compatible source (see error messages below). 

So I don't know if I'm missing something crucial here or if I'm just using it incorrectly.

#### Expected
I expect to see the stream, defined by the parsed m3u8

#### Actual
"No compatible source was found for this media."

#### Output console
```
"VIDEOJS:" "ERROR:" "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" "No compatible source was found for this media." Object {
  code: 4,
  MEDIA_ERR_ABORTED: 1,
  MEDIA_ERR_CUSTOM: 0,
  MEDIA_ERR_DECODE: 3,
  MEDIA_ERR_ENCRYPTED: 5,
  MEDIA_ERR_NETWORK: 2,
  MEDIA_ERR_SRC_NOT_SUPPORTED: 4,
  message: "No compatible source was found for this media.",
  status: null
}
```

#### videojs
videojs 7.7.6
#### plugins
m3u8-parser 4.3.0
#### other javascript
JQuery 3.5.1

**Comment by mister-ben** [comment]
This is available in prelease versions of http-streaming e.g. https://github.com/videojs/http-streaming/releases/tag/v2.0.0-rc.2, not the version that is included in Video.js 7.7.6. It's more useful for testing than production, since you can't use it where only native HLS playback is possible, notably iOS>
