### ISSUE TITLE
How to provide the provide complete content length in Range header request

### ISSUE THREAD

**Issue by astrodad** [videojs/video.js#6650]
## Description
The back end content server I'm using doesn't respond to "byte=0-" because it needs the complete size (eg bytes=400-25455467) for example. Is there any way to have video.js request byte ranges that include the total size of the content? We deal with MP4 only.

### Expected
I expect to see the video playback start

### Actual
When I pass the URL to my content server (third party) it returns back an error instead of the bytes requested since it does not support 0- as a valid range.

### Error output
The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.7.6
#### browsers
Chrome and IE 11
#### OSes
Windows 10 
### plugins
none

**Comment by gkatsev** [comment]
Unfortunately, the answer is no. When playing back mp4s, we almost always hand it over to the browser to play itself. Browsers may or may not use byte-range requests, and we have no way to affect how they load mp4s. Unfortunately, your best bet is to make sure that your server can respond to all valid byte range requests.

**Comment by astrodad** [comment]
I should also add that if I request any valid range other than Range: bytes=0- (such as bytes=0-100), the server does return a 206 with a Content-Range of bytes 100-107/2374067 .

**Comment by astrodad** [comment]
> Unfortunately, the answer is no. When playing back mp4s, we almost always hand it over to the browser to play itself. Browsers may or may not use byte-range requests, and we have no way to affect how they load mp4s. Unfortunately, your best bet is to make sure that your server can respond to all valid byte range requests.

Ok thanks! I’m working with our content server provided to fix the problem.
