### ISSUE TITLE
Video not play after HLS preroll in Firefox

### ISSUE THREAD

**Issue by EhsanCh** [videojs/video.js#6651]
## Description
When a HLS ad play on preroll, main video will not start to play in Firefox.
for example play videos in middle of this page in Firefox 76.0.1 :
https://www.asriran.com/fa/news/727893

it thrown this error on start playing main video:
VIDEOJS: DOMException: "An attempt was made to use an object that is not, or is no longer, usable"

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Click play button when there is an HLS preroll video.
2. Let preroll to end.
3. Main video will not start.
 
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?  tested with vjs >7
#### browsers
what browser are affected? Firefox
#### OSes
what platforms (operating systems and devices) are affected? Windows , Android
### plugins
are any videojs plugins being used on the page? If so, please list them below.
vast plugins

**Comment by 9527Robin** [comment]
I encountered the same problem

**Comment by 9527Robin** [comment]
When I updated to the latest version 7.12.3, the problem was solved 。
