### ISSUE TITLE
Player losing characteristics when changing pages

### ISSUE THREAD

**Issue by phrm000** [videojs/video.js#6652]
## Description
Player lose all his divs and configurations when changing pages 

## Steps to reproduce
1. See the video in this link https://vimeo.com/user115431449/review/418239543/245c428f29
2. See the pics in Additional Information

### Expected
I wanted to continue configured when I change pages

### Actual
Video lost all his divs when changing pages

## Additional Information
I am pretty new in front-end, don't judge me

Before changing pages (working)
![before](https://user-images.githubusercontent.com/61545580/81876858-04e60480-955a-11ea-91a2-14238b4f7285.png)

After changing pages (not working)
![after](https://user-images.githubusercontent.com/61545580/81876856-044d6e00-955a-11ea-8bc7-3c5ccc8e8a4b.png)

#### videojs
v7.7.6

#### browsers
All
I am using Chrome 81.0.4044.138 in windows
#### OSes
All

### plugins
No plugins

**Comment by mister-ben** [comment]
if you're relying on `data-setup` to init the player, the order in which you add the script and the video element matter. try removing that attribute and explicitly initialising the player with `videojs('my-video')`. if this is a single page app then you might need to dispose your player with `player.dispose()` to unload it properly.

**Comment by phrm000** [comment]
So, what I'm doing is implementing the video property with js in my html page.
I tried to do what you said, but I think i didn't get how to do it right.
Can you help me showing where to put this things you mentioned? 
This is the part where I insert the video in my .js

		const videodiv= document.createElement("div");
		videodiv.setAttribute("class", "video-div");
		cntdAula.appendChild(videodiv);

		const videoid = document.createElement("video");
		videoid.setAttribute("data-setup", "{}");
		videoid.setAttribute("id", "my-video");
		videoid.setAttribute("class", "video-js");
		videoid.setAttribute("controls-preload", "auto");
		videodiv.appendChild(videoid);

		const videosrc = document.createElement("source");
		videosrc.setAttribute("src", aulasCntd[tp].fonte);
		videoid.appendChild(videosrc);

**Comment by mister-ben** [comment]
Call `videojs` with the id of the element or the element itself, so `videojs(videoid)`. Also you can remove `data-setup` and need to fix `controls` and `preload`. It's better to set the source via API than a source element, and you can do that in the ready callback:

```js
const videodiv = document.createElement("div");
videodiv.setAttribute("class", "video-div");
document.body.appendChild(videodiv);

const videoid = document.createElement("video");

videoid.setAttribute("id", "my-video");
videoid.setAttribute("class", "video-js");
videoid.setAttribute("controls", "controls");
videoid.setAttribute("preload", "auto");
videodiv.appendChild(videoid);

videojs(videoid).ready(function() {
  this.src({ type: 'video/mp4', src: 'https://vjs.zencdn.net/v/oceans.mp4' });
});
```
