### ISSUE TITLE
Touch / Mouse events are not propagated from the seekBar child to the Player

### ISSUE THREAD

**Issue by evanfarina** [videojs/video.js#6655]
## Description
An event that is initiated by a tap, mousedown, mouseup, or click on seekBar will not propagate up to the player. This is an issue because interactions on other controls correctly propagate up to the player, which is to say that I've assumed this behavior to be reliable across all components.

## Reduced test case
Admittedly, this issue is not reproducible 100% of the time. In this [reduced test case](https://codepen.io/efarina/pen/JjYazRe) I've created a simple plugin which listens for interaction events with the player. Most of the time, interacting with the progress bar will not be caught by the plugin because the [seekBar catches the event and stops propagation](https://github.com/videojs/video.js/blob/a4ea1f9657e1f36471e20225526d0460e77f8b40/src/js/control-bar/progress-control/seek-bar.js#L231). This is necessary because the seekBar's parent, progressControl, [makes a call to seekBar.mousedown](https://github.com/videojs/video.js/blob/a4ea1f9657e1f36471e20225526d0460e77f8b40/src/js/control-bar/progress-control/progress-control.js#L178) upon receiving a mousedown event. So, without the stopPropagation call we'd run into an infinite loop scenario.

In my testing I've found that, on occasion, the progressControl handles the click, resulting in an interaction event being picked up by the plugin. This is rare, though, and in our app ([LinkedIn](https://linkedin.com/feed)) this almost never happens.

## Steps to reproduce
1. View isolated test case above
2. Open dev tools
3. Interact with the player, notice that console.logs appear on interaction
4. Click on the progressControl. Notice that no event fired.

### Expected
I expect that each player control bubbles up interaction events to the player.

## Additional Information

- Version being used in my app: 7.6.5. However, I am using the CDN url for video.js in the attached Pen.

#### browsers
I've tested in Chrome, Firefox and Safari.

**Comment by dalalRohit** [comment]
I'm also facing the same issue. `SeekBar` seems to react to `mousemove` and `mouseup`. But, it does not react to `mousedown`.

Needed this to enable the dragging feature on the `SeekBar`.

Any help appreciated ;)

**Comment by kkm** [comment]
I found a bug I am not sure when I click with my mobile then it show wrong in "range" like infinity:
![image](https://user-images.githubusercontent.com/134290/123871004-6bcba600-d933-11eb-88b6-4953e52a82c3.png)


correctly on PC with video.js seekable:
![image](https://user-images.githubusercontent.com/134290/123871057-7c7c1c00-d933-11eb-98c2-babe880bded6.png)

**Comment by gkatsev** [comment]
Please open a new issue with a live, minimal, reproducible test page.
