### ISSUE TITLE
Expose video's frame rate

### ISSUE THREAD

**Issue by dirn** [videojs/video.js#6661]
## Description

Is it possible to get the frame rate of the current video? As was mentioned in #5846, video.js can't get this information directly from the video, but it was mentioned that the information could be captured from the HLS manifest. My source provides manifests similar to the following.

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud128k",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="..."
#EXT-X-STREAM-INF:BANDWIDTH=272000,CODECS="mp4a.40.2, avc1.42001E",RESOLUTION=576x360,FRAME-RATE=60.0,NAME=360p,AUDIO="aud128k"
...
#EXT-X-STREAM-INF:BANDWIDTH=672000,CODECS="mp4a.40.2, avc1.4D001F",RESOLUTION=768x480,FRAME-RATE=60.0,NAME=480p,AUDIO="aud128k"
...
#EXT-X-STREAM-INF:BANDWIDTH=1472000,CODECS="mp4a.40.2, avc1.4D001F",RESOLUTION=1152x720,FRAME-RATE=60.0,NAME=720p,AUDIO="aud128k"
...
#EXT-X-STREAM-INF:BANDWIDTH=4372000,CODECS="mp4a.40.2, avc1.4D0028",RESOLUTION=1728x1080,FRAME-RATE=60.0,NAME=1080p,AUDIO="aud128k"
...
```

Knowing that `FRAME-RATE` is included, is it possible to extract that using video.js?

**Comment by anaghs** [comment]
👆Looking for this info as well.

**Comment by posita** [comment]
☝️ ➕1️⃣

**Comment by gkatsev** [comment]
Thanks for your patience, you should be able to get these properties via the following:
```js
player.tech().vhs.playlists.media().attributes
```

**Comment by dirn** [comment]
@gkatsev Thanks for getting back to me. I don't see a `vhs` attribute on `player.tech()`. I'm using 7.6.6; I see `@videojs/http-streaming` as a dependency. Is there something I need to do to enable it?

**Comment by gkatsev** [comment]
Ah, oops, `vhs` is what we're standardizing with the new version of the playback engine. You can use `.hls` instead right now.
```js
player.tech().hls.playlists.media().attributes
```

**Comment by dirn** [comment]
I don't have an `his` attribute either. I've tried clicking around in my console and I haven't been able to find anything that references `his`, `playlists`, or `media`.

**Comment by gkatsev** [comment]
Have a test page or stream you can share? Also, what browser are you testing on?
