### ISSUE TITLE
7.8.1 release?

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#6664]
When will 7.8.1 be released on npm? It's been in pre-release for a month now..

**Comment by third774** [comment]
`7.8.1` is on npm now. You can install it with `npm i video.js@7.8.1`

![image](https://user-images.githubusercontent.com/8732191/82400365-c1d5d680-9a1c-11ea-980a-102b7d3a6979.png)

**Comment by jinyeng** [comment]
Any dates when 7.8.1 will be released ? Seems stuck in pre-release for quite sometime. We are planning to upgrade but would like release version if possible.

**Comment by gkatsev** [comment]
Hey, sorry for the delay. 7.8.2 is now out as latest. Also, as @third774 has said, the release was available on npm previously but it wasn't marked latest.
