### ISSUE TITLE
skin is not working in mobile browser

### ISSUE THREAD

**Issue by AndrLin** [videojs/video.js#6665]
## Description
skin is not working in moblie borwser。skin just working in pc borwser。
![image](https://user-images.githubusercontent.com/9127707/82636494-5286ff00-9c35-11ea-8fb3-5d25dca31252.png)

![image](https://user-images.githubusercontent.com/9127707/82636372-0dfb6380-9c35-11ea-8867-ef65342c8bde.png)

why changed "display: none" in mobile borwser.

![image](https://user-images.githubusercontent.com/9127707/82636706-cfb27400-9c35-11ea-81de-586ccc5216ac.png)
 `https://videojs.com/sea` showed skin in mobile borwser.

How can I fix it.

## code
`create-react-app` `TypeScript`

```javascript
import React, { useEffect, FC, useRef, CSSProperties } from "react";
import videojs from "video.js";
import "video.js/dist/video-js.css";
import "@videojs/themes/dist/sea/index.css";

const VideoPlayer: FC<{
  src?: string;
  poster?: string;
  width?: number;
  height?: number;
  style?: CSSProperties;
}> = ({ src, poster, width = 480, height = 480, style }) => {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    if (videoRef.current) {
      var play = videojs(
        videoRef.current,
        {
          autoplay: false,
          controls: true,
          nativeControlsForTouch: true,
          sources: [
            {
              src: src + "",
              type: "video/mp4",
            },
          ],
          poster: poster,
          width: width,
          height: height,
        },
        () => {
          console.log("player ready");
        }
      );

      play.addClass("vjs-theme-sea");

      return () => {
        play.dispose();
      };
    }
  }, [videoRef]);

  return (
    <div ref={wrapperRef} style={style} data-vjs-player>
      <video
        id="my-video"
        ref={videoRef}
        className="video-js"
        preload="auto"
        x5-video-player-type="h5"
        x5-video-player-fullscreen="true"
        playsInline={true}
        webkit-playsinline="true"
        width={width}
        height={height}
        poster={poster}
        controlsList="nodownload"
      />
    </div>
  );
};

export default VideoPlayer;

```

#### videojs
`^7.7.6`
#### browsers
Mobile browsers
#### OSes
`Android` `iOS`

**Forgive me for my bad English**

**Comment by mister-ben** [comment]
It's because you are using `nativeControlsForTouch: true`

**Comment by AndrLin** [comment]
> It's because you are using `nativeControlsForTouch: true`
@mister-ben 
First of all, thank you for your reply.
Yeah, that's it.
I remember I added it because controlbar click to pause is hard when `nativeControlsForTouch: false`.
I didn't know it would deactivate the skin.
I have to double-click the pause button to pause，when `nativeControlsForTouch: false`.
How can I fixed it.

**Comment by AndrLin** [comment]
I know what's wrong.
It's my fault，I used the "FastClick" cause.
