### ISSUE TITLE
Problems in mobile Firefox to playback HLS stream by nginx rtmp module

### ISSUE THREAD

**Issue by NKnuelle** [videojs/video.js#6666]
## Description
HLS stream does not playback using video js 7 on mobile Firefox (Android). The HLS stream is generated with the nginx rtmp module: [Link on GitHub](https://github.com/arut/nginx-rtmp-module)
I can't give a minimal example yet, because the video stream is business internal so I can't provide the streaming URL. If I find some time I can create a test URL if necessary.

Firefox on Desktop, Chrome (mobile&desktop) and Safari (iOS) are playing back the stream without problems.

## Steps to reproduce

1. Just add hls playlist file produced by nginx rtmp module to video js
2. Use Mobile Firefox (I am using v68 on Android) to open webpage including the video
3. nginx config used:
```

rtmp {
  server {
    listen 1935;
    chunk_size 4096;
    application live {
      live on;

      record all;
      record_path ~/recording;
      record_unique on;

      #turn on hls
      hls on;
      #hls_continuous on;
      hls_path /var/www/stream/hls/;
      hls_fragment 3;
      hls_playlist_length 60;
      #disable consuming the stream from nginx as rtmp
      deny play all;

      #record off;
    }
  }
}
```

4. The RTMP stream is generated by GStreamer from a 720p video input:
`GST_DEBUG=2 gst-launch-1.0 flvmux streamable=true name=mux ! rtmpsink location="rtmp://localhost:1935/live/stream live=1" v4l2src io-mode=2 ! "video/x-raw,framerate=50/1,format=UYVY" ! v4l2h264enc output-io-mode=2 extra-controls="controls,video_bitrate=6000000;" ! video/x-h264,profile=high ! h264parse ! queue ! mux.`

### Expected
Playback of the HLS Stream in Mobile Firefox

### Actual
First, Mobile Firefox is loading and then stops with default error message that playback is not possible.

### Error output
The console logs the following error:
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
video.es.js:95:47
    lt video.es.js:95
    error video.es.js:283
    error video.es.js:24434
    handleTechError_ video.es.js:22707
    dispatcher video.es.js:1898`

#### videojs
7.7.5 via npm
#### browsers
Firefox Mobile 68.8.1
#### OSes
Android
### plugins
No. Just HLS which is now included by default in videojs 7

**Comment by gkatsev** [comment]
Make sure that you're setting overrideNative, without it, it's using native HLS playback.

**Comment by theCalcaholic** [comment]
@gkatsev Is that still a recommended practice for all platforms/browsers? Or shoud we set this selectively for those with broken native playback?

**Comment by gkatsev** [comment]
We definitely recommend doing so on all non-safari browsers. In fact, in an upcoming release we plan on turning that switch on ourselves (the release that'll include VHS 2.1)
