### ISSUE TITLE
浏览器即将全面禁用flash

### ISSUE THREAD

**Issue by snineksy** [videojs/video.js#6668]
rtmp该怎么播放，当完全没有flash的环境的时候

**Comment by mister-ben** [comment]
You can not play rtmp in a browser without flash. You need to use a modern format, such as HLS.

**Comment by gkatsev** [comment]
You can use something like nginx-rtmp-module to convert your rtmp to DASH or HLS but once Flash is done at the end of the year, rtmp won't work.
