### ISSUE TITLE
Is there any way to get the real-time status of the buffer？？？

### ISSUE THREAD

**Issue by tfh12345** [videojs/video.js#6669]
For example, I want to get the initial size of the player buffer, and I can get the size of the buffer occupied in real time while the video is playing。How can I do that？

Any comments and suggestions please let me know without hesitation！Thank you！

**Comment by gkatsev** [comment]
You can use the [`buffered()`](https://docs.videojs.com/player#buffered) method. Theoretically, you could listen to `progress` events to know when it changes but realisticly you probably want to check on some kind of timer depending on whatever frequency you want to know.

The return value is a TimeRange object, see https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges.

Hope this helps.
