### ISSUE TITLE
mp4 recorded from NDI camera cannot play on mobile device

### ISSUE THREAD

**Issue by restart08** [videojs/video.js#6674]
## Description
I have a mp4 that recorded from NDI camera which can play well on PC, but report error message on android mobile device. I changed the source to another mp4 download from web and play well on both devices, so I think there is some bug in VideoJS

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.You can download the NDI mp4 from [here](https://drive.google.com/file/d/1pNGxio72wGeuboJ1pc3kHl5VreYJUc4T/view?usp=sharing)
2.Create a simple VideoJS player to test it on PC and Android mobile device.

### Expected
Play well on both devices

### Actual
Play well on PC but not mobile devices

### Error output
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support" report on mobile player screen.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
/vjs.zencdn.net/7.8.2/video.min.js (I tried 7.0.0 and get the same result)
#### browsers
Chrome 81.0.4044.138
#### OSes
Android 7.1.1 on HTC U11
### plugins
none

**Comment by mister-ben** [comment]
The browser/OS needs to be able to decode the video - this MP4 uses the 'High 4:4:4 Predictive' h264 profile which won't have broad support. Desktop Safari doesn't play it either.

**Comment by restart08** [comment]
Hello, thanks for your responds.
I use ffmpeg to transcode this mp4 again and add "-pix_fmt 420p". Now it works on any device.
