### ISSUE TITLE
Analytics events emmited by the player

### ISSUE THREAD

**Issue by Leo-Paulus** [videojs/video.js#6675]
Hello!

I'm investigating about video analytics with video.js and I would like to know if there a list of events that the player generates.

Thank you,
Leonel.

**Comment by Leo-Paulus** [comment]
Is this the right place to ask this?

**Comment by gkatsev** [comment]
We generally rely on the native video element events https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events.
