### ISSUE TITLE
Play/Pause events not triggering in iOS Safari (Angular)

### ISSUE THREAD

**Issue by CodyDunlap** [videojs/video.js#6679]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

I'm running into an issue where the **onplay**, **onpause**, and **onplaying** events are not being triggered in **mobile Safari**, specifically on **iPhone**. We are using Angular, but the workings should all be the same. What I have discovered is that these events will trigger as expected if I use just the native HTML5 video element but as soon as I use videojs to configure the video element, the events stop firing. 

Some events, such as **loadedmetadata** works in both solutions.

Reproduction on Stackblitz: https://stackblitz.com/edit/videojs-safari-issue

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Bind onplay and onpause events to video element
2. Using an iPhone simulator or physical iPhone, open the stackblitz demo.
3. Click 'Preview'
4. Once the app has loaded in the preview, click play on the video player. The 'no events' message should change to 'playing'/'paused' as you toggle playback. 

### Expected
The onplay, onpause, and onplaying events should be triggered correctly in Safari iOS.

### Actual
No events are triggered in Safari. However, if you open the same stackblitz demo in Chrome/Firefox/Desktop Safari, it works as expected. 

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.2
#### browsers
iOS Safari (iPhone only)
### plugins
none

**Comment by mister-ben** [comment]
On iOS a new video element is created, as moving the original el into the player div can be problematic. In general you shouldn't try to interact directly with the video element - use the Video.js API which will work whatever element or other tech is underneath, e.g. `player.on('play', ...`

**Comment by luzh0422** [comment]
> On iOS a new video element is created, as moving the original el into the player div can be problematic. In general you shouldn't try to interact directly with the video element - use the Video.js API which will work whatever element or other tech is underneath, e.g. `player.on('play', ...`

So, how can I get this new element? Because I have to listen to some native events. Thank you.

**Comment by luzh0422** [comment]
This problem has been solved. Obtaining the element after the ready event will be the actual Video element obtained.
