### ISSUE TITLE
Images support. Whammy?

### ISSUE THREAD

**Issue by dsovino** [videojs/video.js#6682]
I've been looking for a video resource that allows me to reproduce a videos/images playlist of files. Video.js seems the best alternative around, however i'm not sure if i can "reproduce" images for a certain period of time.

Has anyone been able to do this with existing plugins, or natively?

Looking around i found this realtime video generator from images:

https://github.com/antimatter15/whammy

I'm guessing how much work would it be to generate such plugin that will allow me to extend video.js to "play images" as well as videos while reproducing a playlist. Another approach would be using an AWS Lambda function and simple generate a video for each uploaded image, but i'm not no sure about that particular approach.

Looking forward for your thoughts about this.

**Comment by gkatsev** [comment]
Generating on lambda isn't a terrible idea, though, the ergonomics of it are probably slightly awkward. As for a Video.js plugin, it's certainly possible. You'll probably want to create a tech like the videojs-youtube tech or the [ogvjs tech](https://github.com/hartman/videojs-ogvjs) which runs [ogvjs](https://github.com/brion/ogv.js/] a Media decoder and player for Ogg Vorbis/Opus/Theora and WebM VP8/VP9/AV1 video. Not sure which is necessarily better, though. With a Video.js tech you can probably do whatever you want including just displaying images directly without the usage of whammy.
