### ISSUE TITLE
ERROR (CODE:3 MEDIA_ERR_DECODE)  on IOS

### ISSUE THREAD

**Issue by at2012** [videojs/video.js#6683]
I'm running into an issue where “MediaError {code:3, message:"The media playback was aborted due to a corrution……media used feature your browser did not support}”。
Only if there are many videos in one page，like 20.It's strange that the video in the front of this page can play，but the video in the back can't 。

**Comment by gkatsev** [comment]
It's possible that iOS doesn't let you load too many videos at the same time. I would definitely recommend against having 20 working players on the same page. I've often seen issues with pages that include 10s of players on the page.
Instead, I would recommend having thumbnails and creating the player on demans in response to a user click.
