### ISSUE TITLE
videojs.ima.js:1445 AdsLoader error: AdError 1005: There was a problem requesting ads from the server. Caused by: Error: 6

### ISSUE THREAD

**Issue by kalyanirawal** [videojs/video.js#6688]
Hi,

### Description:
We are using videojs and have integrated ima plugin for videojs.
We are creating options variable and passing it to ima which is called on player instance as follows:
var options = {
id: videoTagID
  adTagUrl: 'Adtagurl'
};
player.ima(options);

### Results
Getting an error 1005 for the adtagurl

### Error output
We are getting an error on requesting the ad as below:
videojs.ima.js:1445 AdsLoader error: AdError 1005: There was a problem requesting ads from the server. Caused by: Error: 6
And 400 error code for the Adtag url. 
The same adtag url is working fine on VSI  but is giving error when we are using it in our player.

Thanks

**Comment by mister-ben** [comment]
That's a few steps removed from Video.js itself. You'll be able to get better help in the googleads/videojs-ima repo, or the IMA SDK group.
https://groups.google.com/forum#!forum/ima-sdk
