### ISSUE TITLE
Video has green teint

### ISSUE THREAD

**Issue by KammererTob** [videojs/video.js#6689]
## Description
We are currently transcoding some videos to m3u8 for streaming/VOD. In this process we noticed that videos which originally had the MTS format have a green teint when played back with video.js. The output looks normal in VLC. 

## Steps to reproduce
Here is a sample URL: http://locatenote.de/upload/green/green.m3u8

### Expected
![image](https://user-images.githubusercontent.com/1510949/83793015-3440ea80-a69c-11ea-99b2-9a048c7bf7f5.png)

### Actual
![image](https://user-images.githubusercontent.com/1510949/83793074-4de23200-a69c-11ea-82aa-c27dba043049.png)

### Error output
No errors.

#### videojs
Tried with the latest video.js version
#### browsers
Chrome (Desktop) at the very least
#### OSes
Windows 10 64-bit at the very least
### plugins
No plugins

**Comment by mister-ben** [comment]
That's usually a local machine issue - updating graphics drivers or disabling hardware acceleration in the browser settings might help. It appears correctly on every browser on my Mac.

**Comment by KammererTob** [comment]
Thanks. It works correctly when i turn off hardware acceleration in Chrome! Is there anything we can do on our end to prevent his as much as possible? Other videos which are transcoded in the same way work normally, even with hardware acceleration.

**Comment by vgrafe** [comment]
I'm interested in finding a way to detect such random decoding errors as well. Telling my users to remove HW accel or to refresh is not very a neat UX.

**Comment by gkatsev** [comment]
I'm not sure there's a way to detect this beyond looking for a particular pixel and seeing if it's displaying in the expected color.
