### ISSUE TITLE
Disable preload spinner?

### ISSUE THREAD

**Issue by davidgeorgehill** [videojs/video.js#669]
Is it possible to easily disable the pre-load spinner? It hangs on some browsers and continues to spin even after the video begins. Thanks.

**Comment by hlolli** [comment]
By adding `data-setup='{"children": {"loadingSpinner": false}}'` I get

TypeError: Cannot read property 'on' of undefined and then something about `qualityPickerPlugin`, guess this doesn't merge the json maps but overwrites it.

Not really a question, just in case someone drops by this issue and has a similar problem and a solution...

**Comment by rayfoss** [comment]
The spinner behavior is different on chrome/safari than ff... if a caption is empty or missing, it will get stuck spinning :/

Seems like my subtitle source should default to null, not `''` an empty string. This confused firefox.

**Comment by eligocs** [comment]
Nothing to preview
