### ISSUE TITLE
Watermark plugin that cannot be disabled.

### ISSUE THREAD

**Issue by netcxz0** [videojs/video.js#6690]
## Description
I built a watermark plugin using the DIV tag, but it can be easily disable by hide the element in the Chrome Browser.  What can I do to build a watermark plug that cannot be disabled.
what browser are affected?
Chrome 
what platforms (operating systems and devices) are affected?  Windows 10
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Any element can be manipulated. The most you can do is regularly check its present and visible. Robust watermark solutions modify the video itself.
