### ISSUE TITLE
Video on top of all the elements

### ISSUE THREAD

**Issue by joseduin** [videojs/video.js#6691]
## Description
I am developing an application where videos are shown, I only allow one video at a time to be active, to pause the videos while scrolling on the screen I am using the _ng-in-viewport_ library.

When the video is paused, it appears that the video is on top of all the elements, both the video controls and any element that is there.

### Expected
The expected behavior is that the video is paused without interrupting the other elements

### Actual
This behavior only happens in IOS, I have tested the application on Android and the video is paused without problems.

<img width="306" alt="Captura de Pantalla 2020-06-05 a la(s) 09 51 01" src="https://user-images.githubusercontent.com/19161796/83884031-49f0f700-a712-11ea-8051-b0640a9cba1e.png">

![image (5)](https://user-images.githubusercontent.com/19161796/83884338-b9ff7d00-a712-11ea-9157-cce0e4ed8a0c.png)

![WhatsApp Image 2020-06-05 at 9 31 52 AM](https://user-images.githubusercontent.com/19161796/83881970-72c3bd00-a70f-11ea-872e-cb2b75d7950d.jpeg)

i tried adjusting everything with z-index but it didn't work.
PD: it is not the poster of the video, it is the paused video

### plugins
ng-in-viewport

Here's my code
![image](https://user-images.githubusercontent.com/19161796/83884721-51fd6680-a713-11ea-959c-917db0e91a91.png)

**Comment by xumoqiu** [comment]
@joseduin I noticed that you use Angular too. How do you dynamically switch video address

**Comment by gkatsev** [comment]
Weird, not sure what's going on. Do you have a minimal, complete, verifiable example you can share?

**Comment by gkatsev** [comment]
Interesting, glad you figure out what was going on and thanks for circling back here.
