### ISSUE TITLE
Can't set the video player width/height other than fixed pixels, so It doesn't adjust to page/div size.

### ISSUE THREAD

**Issue by alenieto97** [videojs/video.js#6695]
I'm using vue-video-js but it's the same for video-js and I'm super stuck so I would appreciate some help. I guess anyone who is embedding the player to their site needs to make it's size responsive.
I really like the video player but can't seem to set a size to other than pixels. On the video player settings only numbers/pixels are allowed. If I don't set a width or height on playerOptions and rather use CSS to set the player width to lets say 50% it doesn't apply, event with !important. 

The Player
```      <div
        class="video-player-box vjs-16-9"
        v-if="sourceList[0]"
        @ended="onPlayerEnd($event)"
        v-video-player:myVideoPlayer="playerOptions"
      ></div>
```

These are my settings
```    }
  playerOptions: {
        muted: false,
        autoplay: 'play',
        loop: false,
        width: 1000,
        language: 'en',
        playbackRates: [0.7, 1.0, 1.5, 2.0],
        sources: [
          {
            type: 'video/mp4',
            src: "asd"
          }
        ]
      }
```

My CSS, which the player is ignoring

```
.video-player-box{
  margin: auto;
  width: 50vw !important;
  align-content: center;
  align-items: center;
  text-align: center;
}
 ```

Also why when deployed the play button displays on the top left of the player, even on videojs official homepage?

**Comment by mister-ben** [comment]
You could set `width: "50vw"` on a parent element rather than the player, and use the `fluid: true` setup option to make the player fit to it, maintaining aspect ratio.
Top left is the default position, but you can add the `vjs-big-play-centered` if you prefer centered.

**Comment by alenieto97** [comment]
Solved, I was using it inside a VUE component, which styling is by default scoped. But since the videjs styling is inserted on the head, it wasn't being affected. Removing the scoped solved the problem. This issue should be closed.
