### ISSUE TITLE
HLS on Android Chrome Playback Issue

### ISSUE THREAD

**Issue by gpdeedler** [videojs/video.js#6696]
## Description
Using the bipbop sample video with the minimal player code, it plays fine on Chrome OSX, Safari OSX, but fails on Chrome Android.

## Steps to reproduce
Click this link and click play on an Android Chrome browser:
http://ec2-13-57-178-182.us-west-1.compute.amazonaws.com/playit5.html

### Expected
Should play

### Actual
Gives the error described below

### Error output
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 

## Additional Information
using the copy and pasted code from the homepage of videojs github but pointing to my hosting of the bipbop.

It seems like a CORS issue but if you:
curl -v http://ec2-13-57-178-182.us-west-1.compute.amazonaws.com/bipbop_16x9_variant.m3u8
You'll find:
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
< Access-Control-Expose-Headers: Content-Length,Content-Range
< Accept-Ranges: bytes

Also, I don't think it's CORS because I can remotely debug and spy on the network and see that the m3u8 was properly attained (in the response tab):
#EXTM3U
  
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="bipbop_audio",LANGUAGE="eng",NAME="BipBop Audio 1",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="bipbop_audio",LANGUAGE="eng",NAME="BipBop Audio 2",AUTOSELECT=NO,DEFAULT=NO,URI="alternate_audio_aac_sinewave/prog_index.m3u8"

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE="en",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog, public.accessibility.describes-music-and-sound",URI="subtitles/eng/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English (Forced)",DEFAULT=NO,AUTOSELECT=NO,FORCED=YES,LANGUAGE="en",URI="subtitles/eng_forced/prog_index.m3u8"

#EXT-X-STREAM-INF:BANDWIDTH=1030138,CODECS="mp4a.40.2, avc1.4d401f",RESOLUTION=1280x720,AUDIO="bipbop_audio",SUBTITLES="subs"
gear4/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=339492,CODECS="avc1.4d401f",URI="gear4/iframe_index.m3u8"

#EXT-X-STREAM-INF:BANDWIDTH=41457,CODECS="mp4a.40.2",AUDIO="bipbop_audio",SUBTITLES="subs"
gear0/prog_index.m3u8

Another reason I don't think it's a CORS issue is that I can playback MPD files from the same server without any issue.

**Comment by mister-ben** [comment]
Try using `overrideNative` so it's played back with MSE rather than Android's native playback. https://github.com/videojs/http-streaming#overridenative

**Comment by gpdeedler** [comment]
Funny, I had just tried that last night and that solves the issue.

Thank you @mister-ben
