### ISSUE TITLE
BlobBuilder is not a constructor in video.es.js when using in angular 8+

### ISSUE THREAD

**Issue by cloudtechpk** [videojs/video.js#6697]
I just integrate video.js via npm i video.js , after running application it throw error

BlobBuilder is not a constructor in video.es.js file on line shown below

var blob = new BlobBuilder();
blob.append(str);

Is there any fix exist to utilize video.js smoothly in my angular project.

**Comment by gkatsev** [comment]
Looks like it's coming from https://github.com/gkatsev/rollup-plugin-bundle-worker/blob/master/src/workerhelper.js.
Unfortunately, I am not sure what angular is doing with things. This is the first time we've seen such an issue.
Would you happen to have a live minimal, complete, verifiable example page?
