### ISSUE TITLE
VasttagUrl not calling

### ISSUE THREAD

**Issue by RajasekarPR** [videojs/video.js#6702]
![image](https://user-images.githubusercontent.com/39621436/84269656-1fa29d80-ab47-11ea-9694-f90671be4114.png)

VastTagUrl not yet called. Getting above debug information in my console. 

Kindly do the needful

**Comment by gkatsev** [comment]
You likely want to open the issue against the ad plugin you're using. For example, if you're using ima, against videojs-ima. Video.js doesn't handle loading vast urls directly.
