### ISSUE TITLE
Player not working

### ISSUE THREAD

**Issue by sreejithGravity** [videojs/video.js#6703]
I just loaded simple.html to my test server. Its shows just a player. Nothing happens
http://teamgravity.in/tests/videojs-youtube-master/examples/simple.html

**Comment by jayrajzala** [comment]
> I just loaded simple.html to my test server. Its shows just a player. Nothing happens
> http://teamgravity.in/tests/videojs-youtube-master/examples/simple.html

Video.js library is not getting loaded. so, something must have gone wrong while installing 'videojs' node module.  
to see that for yourself, you can include 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.8.3/video.min.js"></script>' 
in your HTML and it will work. 

but, a better solution would be to reinstall the node module using 'npm install video.js --force' or by deleting the node_module folder altogether and then executing 'npm install'.

**Comment by sreejithGravity** [comment]
@

> > I just loaded simple.html to my test server. Its shows just a player. Nothing happens
> > http://teamgravity.in/tests/videojs-youtube-master/examples/simple.html
> 
> Video.js library is not getting loaded. so, something must have gone wrong while installing 'videojs' node module.
> to see that for yourself, you can include
> `<script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.8.3/video.min.js"></script>'
> in your HTML and it will work.
> 
> but, a better solution would be to reinstall the node module using 'npm install video.js --force' or by deleting the node_module folder altogether and then executing 'npm install'.

Ok

**Comment by gkatsev** [comment]
if you've downloaded the videojs-youtube repo from github directly, things won't work. I would recommend loading both video.js and the youtube tech from a CDN. Using cdnjs mentioned above, 

```html
<!DOCTYPE html>
<html>
<head>
  <link type="text/css" rel="stylesheet" href="../node_modules/video.js/dist/video-js.min.css" />
</head>
<body>
  <video
    id="vid1"
    class="video-js vjs-default-skin"
    controls
    autoplay
    width="640" height="264"
    data-setup='{ "techOrder": ["youtube", "html5"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}] }'
  >
  </video>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.8.3/video.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-youtube/2.6.1/Youtube.js"></script>
</body>
</html>
```
