### ISSUE TITLE
Cant use play/ pause / stop with dynamic jquery player

### ISSUE THREAD

**Issue by Bluchip-Studio** [videojs/video.js#6704]
Hi i have an issue with using the player everything is working perfect when it comes to loading the player and playing the video dynamicly using jquery 

but i have an issue my website is a web app one page with all content loaded into the html from jquery depending on the users selection it all works good until i tru and connect some div selections on the page to player constoles 

when the player is created and opened i have a dynamic menu of controls play / pause / stop / full screen that is loaded i have these tied to key press functions on the keyboard when i select a key press i get the error 

    video.min.js:19 Uncaught (in promise) TypeError: The element or ID supplied is not valid. (videojs)

i have tried using myPlayer.pause(); i get the same kind of error stating myplayer is not valid i also tried

var player = videojs('myPlayer'); 
player.pause();

that had the same issue 

i am just wondering is there a way to interact with the player in a global scope once the player has been created dynamicly ?

**Comment by gkatsev** [comment]
Do you have a live, minimal, complete, verifiable example page for this?
You can get existing players via `videojs.getPlayer({{playerid}})` or you can store your player instance somewhere you can access it.
