### ISSUE TITLE
Safari not playing error 

### ISSUE THREAD

**Issue by sampathkumar7** [videojs/video.js#6705]
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="recording",LANGUAGE="English",NAME="English",AUTOSELECT=YES, DEFAULT=YES,URI="/english.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="recording",LANGUAGE="Spanish",NAME="Spanish",AUTOSELECT=YES, DEFAULT=NO,URI="/spanish.m3u8"
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:AUDIO="recording"
100670_20200609123000.m3u8

this is the master playlist im passing to player but getting error in safari 13
VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "The media could not be loaded, either because the server or network failed or because the format is not supported."

whereas same working with theoplayer in safari

**Comment by gkatsev** [comment]
In Safari, we do not handle playback ourselves but hand the m3u8 directly to safari for playback. If this is failing in Safari, it likely means that your stream is somehow malformed and should be fixed to work on Safari.
