### ISSUE TITLE
在移动端上样式丢失

### ISSUE THREAD

**Issue by crownclownwl** [videojs/video.js#6711]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.在pc端上没问题
2.在Android 和 IOS 上，就显示成了 h5的video 标签，videojs的自带的操作栏和我自定义的操作栏都失效了
3.虽然都支持 MP4 和 m3u8 但是样式和 pc完全不一样了

## Results
希望能和pc 端一样，请问是需要什么设置嘛，还是要引入特殊的插件

### Expected
代码如下
```
import videojs from 'video.js';
import 'videojs-errors';
// 初始化videojs对象
 player = videojs(
            playerRef,              // video 标签
            vidoConfig,             // 配置项
            function onPlayerReady() {
                    ......
               } 
);
```
### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by crownclownwl** [comment]
我用的最新的 videojs V7.8.2

**Comment by crownclownwl** [comment]
`jsx
import videojs from 'video.js';
import 'videojs-errors';
// 初始化videojs对象
player = videojs(
    playerRef, // video 标签
    vidoConfig, // 配置项
    function onPlayerReady() {
        ......
    }
);
`

请问这里是不是需要配置别的插件呀

**Comment by gkatsev** [comment]
Are you including the CSS somehow? Is it possible that the styles aren't loading on mobile for some reason?

**Comment by gkatsev** [comment]
Also, a live minimal, complete, verifiable example would be very useful to help debugging.

**Comment by crownclownwl** [comment]
nativeControlsForTouch: true,
