### ISSUE TITLE
FullscreenToggle.click() not work: safri 13.1.1.1 + https://videojs.com/city.

### ISSUE THREAD

**Issue by sisihi** [videojs/video.js#6712]
## Description
Using JS to click the FullScreenToggle button can not get video fullscreen in safari.
But chrome works.

## Steps to reproduce
1.open vidoejs homage with safari: https://videojs.com/city
![image](https://user-images.githubusercontent.com/16377386/84759862-deeccd80-aff9-11ea-9868-f6c9d22e9ced.png)

2.open safari element inspect:
![image](https://user-images.githubusercontent.com/16377386/84760009-0e9bd580-affa-11ea-9e5c-41e54e3461a6.png)

3.Use JS to get FullScreenToggle:
![image](https://user-images.githubusercontent.com/16377386/84760139-325f1b80-affa-11ea-93f8-bf4b06eed6e9.png)

4.Use JS to click FullScreenToggle
![image](https://user-images.githubusercontent.com/16377386/84760308-6b978b80-affa-11ea-8db4-88fbc4c51286.png)

### Expected
The video played on the full screen.
### Actual
The video view gets disappeared but left the control bar with the small screen button.

![Jun-17-2020 12-06-07](https://user-images.githubusercontent.com/16377386/84853973-ffb53180-b092-11ea-81da-b907029cf87d.gif)

![image](https://user-images.githubusercontent.com/16377386/84760346-76522080-affa-11ea-88ad-7f3de582a7a2.png)

### Error output
NA

## Additional Information
NA
#### videojs
Not sure about the videojs version running on the https://videojs.com/city

#### browsers
SAFARI 13.1.1
![image](https://user-images.githubusercontent.com/16377386/84760656-ee204b00-affa-11ea-897b-1015c1064069.png)
#### OSes
MACOS 10.15.5
### plugins
NA

**Comment by mister-ben** [comment]
Browsers don't allow fullscreen without user interaction. I'm more surprised that it works on Chrome.

The player collapsing is because the player's fullscreen class is being added before knowing the fullscreen request has been successful. That's fixed in newer versions of Video.js, that page is using a slightly old version.

**Comment by gkatsev** [comment]
Sounds like we need to update the Video.js version on the site.

**Comment by gkatsev** [comment]
Website is now live with the updated Video.js version which seems to fix things.
