### ISSUE TITLE
videosjs + DVR + Google Loadbalancer + Wowza Streaming Server

### ISSUE THREAD

**Issue by IosXcodeDeveloper** [videojs/video.js#6713]
## Description
We have elastic multiple Wowza Streaming Edge Servers and a Google Loadbalancer in us Infrastructure.

As example:

- Website with videojs: **mywebsite1.foo.com**
- Website with videojs: **mywebsite2.foo.com**
- LoadBalancer: **lb.foo.com**
- Wowza Edge1 Streaming Server: **edge1.foo.com**
- Wowza Edge2 Streaming Server: **edge2.foo.com**

The videojs src URL are lb.foo.com/live&wowzaplayliststart=20200606235900?DVR

The Google Loadbalancer can handle ClientIP redirects, or cookie Session redirects.

ClientIP is not a option for us. If we have multiple users on the same IP (like a big office), so all users are redirected to one Edge Streaming Server. Too much.

The other Options "Cookie-Session" based ist that what we need.
**The plan**: videojs make the first video connect to the LoadBalancer, this redirect to edge2.foo.com (as example) and send back a cookie to the client. If the user now seek in the dvr timeline, we need a option to send the cookie again for all dvr seek requests, so the LoadBalancer can redirect to the right Edge Server.

The Problem, what we have:

**Problem 1)**
With `withCredentials: false` in the videojs source the dvr not working. In the first video request we send the wowzastarttime in the VideoURL, and we get a many mediafiles and chunks. If we now seek in the DVR, it is possible that the Google Load Balancer redirect us to another Wowza Edge Server. We now lost the Media/Chunks information for seeking.

The Result ist a flapping DVR Timeline. The videojs dvr durations bounces around 12:00 hours (that's the complete Wowza dvr store) or few minutes (Time since wowzaplayliststart parameter), As example: wowzaplayliststart=20200606201020 and i seek at 20:11:20 it bounce between 12:00 hours (complete dvr) or 00:01:00 minute (one minute is the time since wowzaplayliststart parameter)

**We try to resolved, but a new Problem comes up.**
We set the `withCredentials: true` option in videojs. Now we still get a cookie from the Google LoadBalancer, and it looks like the videojs player send the cookie back to the LoadBalancer if i seek/jump in the dvr timeline. That sounds good,
**BUT**
That works only if i set a the Access-Control-Allow-Origin to the domain which the videojs are embedded: as example: Access-Control-Allow-Origin: **mywebsite1.foo.com** in the Wowza MediaServer. But we have multiple websites! If i set Access-Control-Allow-Origin: * Google Crome get me Message:  

`Access to XMLHttpRequest at 'https://lb.foo.com/live.......&DVR&wowzadvrplayliststart=20200616155000' from origin 'https://mywebsite2.foo.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

Summary: 
- Without `withCredentials=true` Loadbalancer + DVR + Wowza not work. It's result in a flapping timeline/duration.
- With `withCredentials=true` is looks like videojs send the cookie, but the option `withCredentials=true` is not allowed for wildcard Access-Control-Allow-Origin.

**Question**
Exist a option, that we can send the cookie to the Load Balancer, without the videojs option: `withCredentials=true`.
I think that can be resolve the issue, then we can use `Access-Control-Allow-Origin: *` in the Wowza Media Server and the LoadBalancer got the correct cookie.

Any other suggestions ?

**Comment by gkatsev** [comment]
Unfortunately, there is no way to send cookies and set the Allow-Origin header to `*`. Most CDN have an option to set the header to the request origin. I would investigate your server options.
