### ISSUE TITLE
video frames' timestamp for RTMP protocol

### ISSUE THREAD

**Issue by SinaRanjkeshzade** [videojs/video.js#6715]
## Description
Hi, Is there any way to find out video frames' timestamp (pts) for RTMP at the front-end (to synchronize server and client on two different devices reading video from a source).
Any help will be appreciated.

**Comment by gkatsev** [comment]
Unfortunately, this isn't something that is exposed. In addition, Video.js doesn't support Flash out of the box anymore, and flash itself basically doesn't work in browsers nowadays anymore.
For HLS and DASH, we don't currently expose the pts values for the playing segments, but it could be something we expose.
I would recommend not shipping RTMP to users in browsers anymore.
