### ISSUE TITLE
iphone Safari and Chrome: FullScreen portrait video auto resizing large to small  vice-versa

### ISSUE THREAD

**Issue by iamabhyas** [videojs/video.js#6716]
## Description
When we play the video and go to full-screen auto-resizing in random

Please see the attached video https://drive.google.com/file/d/13UNDXS7ZpjMJAfIWvDtoDb7hKiYlMMgz/view?usp=sharing

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
See the attached video

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers : Safari and Chrome
what browser are affected?
#### OSes : Iphone
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
The fix is out in version 7.8.3.

**Comment by iamabhyas** [comment]
> The fix is out in version 7.8.3.
Hi @gkatsev, This is not fixed. I am using the m3u8 file format. Could you please look? Your reply will make my day.

**Comment by gkatsev** [comment]
Yeah, not sure why I closed it, we should investigate. Would you be able to share a minimal, completed, verifiable example?

**Comment by iamabhyas** [comment]
@gkatsev Thanks for your reply. Please have a look at this page on Mobile devices(iPhone & Android) https://staging.activeplace.com/a/postvideocheck101/.

**Comment by iamabhyas** [comment]
No, I am waiting for response.

**Comment by mister-ben** [comment]
You have renditions of different aspect ratios. The 9:16 renditions fill the screen and the 16:9 renditions fill the width.

**Comment by gkatsev** [comment]
Yeah, looks like a stream issue. You have renditions with burned in pillar boxing.
