### ISSUE TITLE
Videojs 7.7.6 Error - Code -2 without any description

### ISSUE THREAD

**Issue by claudineimendes-hotmart** [videojs/video.js#6721]
## Description
Hello Guys,

We are experiencing a common error Error - Code -2 in many clients watching our videos.

We can not find any documentation about this error and doesn't have a message when this occurs.

### Error output
Error - Code -2

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.7.6+
#### browsers
All browsers
#### OSes
All OSes

**Comment by gkatsev** [comment]
code -2 might be related to https://github.com/brightcove/videojs-errors#custom-errors which refers to a player timeout, where we're not in a paused state, but we haven't been playing back for 45 seconds.
Though, without a test page, it'll be hard to help out.
