### ISSUE TITLE
Audio desync when scrubbing around videos

### ISSUE THREAD

**Issue by ctd1500** [videojs/video.js#6722]
## Description
I was in the process of updating my build of video.js and I noticed major audio desync issues in Firefox when seeking around videos.
My testing shows that the issue seems to be caused by the FastSeek feature #6525 

I created two examples built from the Main branch to reproduce this:
FastSeek feature causing desync: https://codesandbox.io/s/videojs-fastseek-test-gvvx0
FastSeek commit reverted, fixes desync: https://codesandbox.io/s/videojs-fastseek-removed-test-94tnc

## Steps to reproduce
Seek around the video in the FastSeek feature example and you'll start to see audio desync.
An easily recognizable example would be the bird at 00:20.

### Expected
No desync

### Actual
Major audio desync

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Main branch
#### browsers
Firefox 77
#### OSes
All OSes (tested on Windows 10, and Mac via BrowserStack)

**Comment by gkatsev** [comment]
Huh, it's with an mp4? We don't handle playback of that ourselves. Sounds like we probably want to limit the functionality to safari and then expand it to our source handlers whenever we get around to implementing iframes in VHS.

**Comment by gkatsev** [comment]
This is probably something that we should report to Mozilla as well because we don't handle things like mp4 playback. Adding a PR to limit fastSeek to only Safari based browsers.
