### ISSUE TITLE
how to avoid downloading multiple files?

### ISSUE THREAD

**Issue by ssp4all** [videojs/video.js#6724]
## Description
how can I avoid downloading multiple files?

## Steps to reproduce
when the user hit retry after clicking an image then again click an image, then after clicking the download button two images are getting downloaded but I want the latest one.

PROBLEM: 
sourcecode for capturing images using video.js is below
```    
<video id="myImage" class="video-js vjs-default-skin"></video>
<button id="getItem">DOWNLOAD</button>

```

``` 
var player2 = videojs("myImage", {
            controls: true,
            width: 320,
            height: 240,
            fluid: false,
            controlBar: {
                volumePanel: false,
                fullscreenToggle: true
            },
            plugins: {
                record: {
                    image: true,
                    debug: true
                }
            }
        }); 
        player2.on('finishRecord', function () {

            dwnl.style.display = "block"; //display download button
            $("#getItem").click(function () {.  //download image when use click on download button
                download(player2.recordedData, "img", "png"); //download.js for downloading image in png format
            });
        });
```

### Expected
Download latest image clicked

### Actual
If a user tries n times before clicking download and then after clicking the download all n images are getting downloaded one by one.

### Error output
If there are any errors at all, please include them here.

## Versions
Make sure to include the following versions:
### videojs/wavesurfer
what version of video.js, videojs-wavesurfer and wavesurfer.js does this occur with?
video.js 7.3.0 with videojs-record 2.4.1 and recordrtc 5.4.8
### Browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
### OSes
what platforms (operating systems and devices) are affected?

**Comment by gkatsev** [comment]
Video.js itself doesn't provide any download functionality. As @thijstriemstra mentioned in https://github.com/collab-project/videojs-wavesurfer/issues/107#issuecomment-648430771, maybe you meant to open an issue against videojs-record?
