### ISSUE TITLE
Preloading full video for very fast frame jumping (currentTime)

### ISSUE THREAD

**Issue by dbonattoj** [videojs/video.js#6725]
## Description

I'm doing an application where people can jump randomly between a lot of images.

My first design used 441 images, this worked quite well but every time someone load the page, the application need to preload all the images for an amount of more than 200 Mo, this is not very nice for the user.

So I'm changing the design of the application. I firstly compressed all the images in webm format which resulted in a 5Mo video file. I rewrote the core logic of the application to let the user move as before. However, now, every time the user jumps in the video, the video shows a 'loading' symbol and it is no more visually pleasant to use.

[TL;DR]
I would like to preload the full video (even if it takes time at start) and let the user change very frequently and rapidly the position in the video using currentTime(position) without the 'loading' symbol appearing every time.

### Some code
I tried to preload the video, but the buffered function always gives me a small number of frames, and even when they are loaded, it seem to be showing the loading symbol.

```javascript
preload() {
        var req = new XMLHttpRequest();
        req.open('GET', this.file, true);
        req.responseType = 'blob';

        var self = this;
        req.onload = function() {
            if (this.status === 200) {
               var videoBlob = this.response;
               var vid = URL.createObjectURL(videoBlob); // IE10+
               self.player.src({
                type: 'video/webm',
                src: vid
              });
               console.log(vid)
            }
         }
         req.onerror = function() {
            // Error
         }
         
         req.send();  
    }
```

Testing code:

```javascript
video_set_frame(video) {
        // Selected 40 as the buf variable here always was displaying 44.1
        let r = Math.floor(Math.random() * 40);
        console.log(r)

        this.player.currentTime(r)
        this.player.pause();

        var buf = this.player.buffered().end(0) - this.player.buffered().start(0)
        console.log(buf, this.player.bufferedPercent())
    }
```

Player creation:
```javascript
this.player = videojs(css_player, {
    aspectRatio: '1:1',
    fluid: true,
    responsive: true,
    controls: false,
    preload: 'auto'
})
```

### After some more digging

It seems to work with a 88Mb Webm file! So I guess it is a matter of file encoding, but I have no idea on how to encode a lot of png files into a webm file and make it fluid:

Very fluid:
![image](https://user-images.githubusercontent.com/28501597/85611148-f52d0600-b657-11ea-8f97-c6eb8873f2b8.png)

Not fruid at all:
![image](https://user-images.githubusercontent.com/28501597/85611198-0249f500-b658-11ea-8352-f5619ac4a508.png)

The ffmpeg commands I used with 441 images (512x512) to compress are:
```
# ffmpeg -y -framerate 10 -f image2 -i out_%03d.png -c:v libvpx-vp9 -pix_fmt yuv420p -lossless 1 \
          -pass 1 -b:v 1000K -threads 1 -speed 4 \
          -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 \
          -g 9999 -aq-mode 0 -an -f webm /dev/null

# ffmpeg -framerate 10 -f image2 -i out_%03d.png -c:v libvpx-vp9 -pix_fmt yuv420p -lossless 1 \
          -pass 2 -b:v 1000K -threads 1 -speed 0 \
          -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 \
          -g 9999 -aq-mode 0 -c:a libopus -b:a 64k -f webm output_lossless.webm

# ffmpeg -framerate 10 -f image2 -i out_%03d.png -c:v libvpx-vp9 -pix_fmt yuv420p \ 
          -pass 2  -b:v 1000K -threads 1 -speed 0 \
          -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 \
          -g 9999 -aq-mode 0 -c:a libopus -b:a 64k -f webm output.webm
```

If you want to try yourself the ffmpeg compression, here is a sample of 441 images: https://we.tl/t-v2oLJ6tjcS
And here you can find the fluid file: https://upload.wikimedia.org/wikipedia/commons/8/88/Big_Buck_Bunny_alt.webm

As I'm far from an expert in ffmpeg, I'm bruteforcing it in the hope that one parameter will give a nicer video:
```
ffmpeg -y -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -lossless 1 -pass 1 -b:v 1000K -threads 1 -speed 4 -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25  -g 9999 -aq-mode 0 -an -f webm /dev/null

ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -lossless 1 -pass 2 -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 -g 9999 -aq-mode 0 -c:a libopus -b:a 64k -f webm output_lossless.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 -g 9999 -aq-mode 0 -c:a libopus -b:a 64k -f webm output01.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 -aq-mode 0 -c:a libopus -b:a 64k -f webm output02.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -aq-mode 0 -c:a libopus -b:a 64k -f webm output03.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -aq-mode 0 -f webm output04.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -frame-parallel 0 -auto-alt-ref 1 -f webm output05.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -frame-parallel 0 -f webm output06.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -tile-columns 0 -f webm output07.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -f webm output08.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -f webm output09.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -f webm output10.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2 -f webm output11.webm
```

Also,
If you have any other way of doing this, let me know, I'm really interested :)

### Expected
When the user move in the interface, random frames of the video are loaded

### Actual
Every time the user move, a loading cursor appears and he needs to wait killing the purpose of the application

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with? 7.8.2
#### browsers
what browser are affected? Chrome at least
#### OSes
what platforms (operating systems and devices) are affected? Windows at least
### plugins
are any videojs plugins being used on the page? If so, please list them below.
No.

**Comment by gkatsev** [comment]
Unfortunately, you can't really preload the entire video unless it's really really small. For webm and mp4, we just hand it off to the browser and nowdays browsers don't provide a mechanism to let more or less data load aside from the `preload` attribute, which is generally "load _some_ data" or "don't load _any_ data". If you were to use HLS or DASH, you could configure the goal buffer length in VHS (but not safari because we rely on native playback for HLS on Safari) but that's still limited because you can only put so much data into MSE.
Your best bet would be to experiment with what the browsers will let you do as there isn't many knobs you can turn for this.

**Comment by gkatsev** [comment]
You may have slightly more control if you manually request the video file and add it to the video element via MSE.

**Comment by dbonattoj** [comment]
Thanks!

But is seems that with my code, a video of 88Mb run just fine.. I guess it is my compression commands for webm that are doing something wrong.

I've updated my issue with additional informations.

The preloading using the `preload()` function seems to work

**Comment by dbonattoj** [comment]
I add some more details on the compression using MediaInfo:
![image](https://user-images.githubusercontent.com/28501597/85620160-b2712b00-b663-11ea-9c67-6cc5a402a9e7.png)

and 
![image](https://user-images.githubusercontent.com/28501597/85620229-c583fb00-b663-11ea-8374-0bc0decd2645.png)

**Comment by dbonattoj** [comment]
I will close the issue here for the moment as it seems I found some ffmpeg command combinations that seems ok, 

if someone is interested:

```
# 07-08 identified as fluid (variations on 08 here:)
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 -g 9999 -aq-mode 0 -c:a libopus -b:a 64k -f webm output12.webm
# This one (13) is terribly bad!
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -auto-alt-ref 1 -lag-in-frames 25 -g 9999 -aq-mode 0 -c:a libopus -b:a 64k -f webm output13.webm


# 11 seems perfect!!! here a lossless tuning
# This one (14) is terribly bad!
#ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -lossless 1 -pass 2 -f webm output14.webm


# BEST ONES:
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2 -f webm output11.webm
ffmpeg -framerate 10 -f image2 -i input_Cam%%03d_frame000.png -c:v libvpx-vp9 -pix_fmt yuv420p -pass 2  -b:v 1000K -threads 1 -speed 0 -frame-parallel 0 -auto-alt-ref 1 -lag-in-frames 25 -g 9999 -aq-mode 0 -c:a libopus -b:a 64k -f webm output12.webm
```

So apparently it is a mixture of `-tile-columns 0` and `-frame-parallel 0` that do the problems, but, keeping all the others parameters for max compression without them results in terribly bad results.

I guess too much compression is bad for what I'm trying to do. Something even more strange is the resulting file sizes:
![image](https://user-images.githubusercontent.com/28501597/85629518-55c93c80-b672-11ea-8e56-da6b030579ee.png)

So, without trying to optimize the compression, I achieve the smaller files and the more fluid animation. 11 and 12 are comparable in speed but not at all in size! and the more compressed one (12) is the bigger one!

I guess I was overengineering it.

Hope this can help somebody else :)
