### ISSUE TITLE
 getPointerPosition returns wrong position if the container is transformed

### ISSUE THREAD

**Issue by vakarelov** [videojs/video.js#6726]
## Description
Briefly describe the issue.
The algorithm of getPointerPosition assumes that video container is not subject to scaling and rotation transformations. As a result, it produces the wrong value what such transformations exist. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Add the video container in a div that has a transformation.  See attached file
[video_test.zip](https://github.com/videojs/video.js/files/4827875/video_test.zip)

2. The slider does not provide correct position

#version: 7.7.5

**Comment by gkatsev** [comment]
Yeah, there's definitely an issue and there is a PR that needs to be fixed up that addresses this https://github.com/videojs/video.js/pull/5773
