### ISSUE TITLE
how to prevent native player in ios fullscreen mode?? 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [videojs/video.js#6727]
## Description
when i use fullscreen mode, ios execute native player.
how can i prevent this situation??
I add the playinline in video tag.
but when fullscreen mode, native player executed...
please help me.
![image](https://user-images.githubusercontent.com/30399546/85652270-2f90b480-b6e5-11ea-951f-3a45b9ca320f.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. fullscreen mode
2.
3.

**Comment by gkatsev** [comment]
On iPhones, there isn't a way to do so beyond removing the fullscreen button.
