### ISSUE TITLE
MEDIA_ERR_SRC_NOT_SUPPORTED When play video m3u8 on chrome android

### ISSUE THREAD

**Issue by datnguyenthe** [videojs/video.js#6728]
I'm use videojs 7.8.2 for m3u8 video. It working normal in MacOS, Windows, iOS.
But on android it's error code 4: MEDIA_ERR_SRC_NOT_SUPPORTED
Thanks,

**Comment by gkatsev** [comment]
If you're playing HLS or DASH streams, consider including the `overrideNative` setting for VHS: https://github.com/videojs/http-streaming#overridenative. We're going to set it by default soon. Make sure not to set overrideNative on Safari.
Without a test stream, unfortunately, we can't help further. We have some troubleshooting advice here https://docs.videojs.com/tutorial-troubleshooting.html#problems-with-media-formats.
