### ISSUE TITLE
Buffering Configuration

### ISSUE THREAD

**Issue by zhulduz** [videojs/video.js#6729]
Hi guys!

I have just two questions about network/buffering configs:
1.  Is there some way to add some settings for buffers.
For example, how much content we should keep in a buffer (in seconds) before playing, while playing, after playhead?
2. Can we set how many times the player can try to get manifest/segment files? Like some **retry parameter**?

I couldn't find any info in docs 🤔 
Thanks in advance!

**Comment by gkatsev** [comment]
We have a couple of options in our playback engine but it isn't possible to change things when native playback is used. For example, when playing back an mp4 or when playing HLS on Safari.
For our engine we have `GOAL_BUFFER_LENGTH`, and `MAX_GOAL_BUFFER_LENGTH` (and a couple more https://github.com/videojs/http-streaming/blob/1.x/src/config.js). You can set them via `videojs.Hls.{{propertyName}}` (soon to be `videojs.Vhs.{{propertyName}}`).
