### ISSUE TITLE
video player does not follow streaming engine load balancer, it does not seem to redirect

### ISSUE THREAD

**Issue by elieobeid7** [videojs/video.js#6730]
We have 2 wowza servers which use wowza load balancer. The android application is working fine. The reactJS PWA web application player which uses react-player, which contains hls.js and video.js isn't redirecting to the correct  url

I don't know which of the above components is faulty, no error is shown whatsoever is there anything we need to do in order to help react-player redirect to the correct URL?

Some settings in Wowza or some tweaks to the player? Does anyone have any experience regarding that?

Note: if I disable the load balancer and give the player a normal link, the player works.

**Comment by elieobeid7** [comment]
https://www.wowza.com/community/questions/56919/wowza-loadbalancer-web-hls-player-does-not-redirec.html?childToView=56947#answer-56947

According to by Alexey Ostroumov 

> load balancer URL like: https://[load-balancer-ip-address]/redirect/[application-name]/[stream-name]?type=m3u8 may not work because of mime type. You can set it by hls.js setting if react-player allows to add it.

Where is that setting?

**Comment by gkatsev** [comment]
Video.js doesn't use hls.js by default and are not directly involved with that project. It sounds like react-player uses hls.js and not Video.js. They have replied to the issue over there: https://github.com/CookPete/react-player/issues/950#issuecomment-650634366.
