### ISSUE TITLE
The problem with the delayed start of the broadcast

### ISSUE THREAD

**Issue by Raino** [videojs/video.js#6731]
## Description
Briefly describe the issue.
I use the videojs player to view HLS videos. If you go to the page with the player while the broadcast is going on, everything is fine. If you go to the page first, and then the broadcast starts, you get an error related to"file format is not supported". To transmit a stream, I use links that live for 75 seconds. If you disable and start the broadcast within these 75 seconds, everything works, but if it takes more than that, you get this error that "the format is not supported". Although the link is correct, because it started in VLC, but not in the videojs player.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.Go to the page with the player
2.Wait 75 seconds (the lifetime of the video link)
3.To start the stream

### Expected
The player is created without an error and you can watch the broadcast, even if it started later

### Actual
There is an error that "incorrect video format"

### Error output
Failed to load resource: net::ERR_FAILED
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or beacuse the format is not supported. MediaError (video.js:84)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Recent version
#### browsers
Yandex.Browser
#### OSes
Windows
### plugins
videojs-http-streaming.js

**Comment by Raino** [comment]
@gkatsev Can you help me, please?

**Comment by gkatsev** [comment]
Unfortunately, Video.js tried to load the stream as soon as it is given to Video.js. We can't know why the url is returning a 404 and we do not currently have a feature to wait for this. Your best bet is to wait until the event is live and only set the source at that time.

**Comment by Raino** [comment]
@gkatsev I tried destroying the player with "disponse", but it didn't work
