### ISSUE TITLE
master vs main branches

### ISSUE THREAD

**Issue by tomByrer** [videojs/video.js#6732]
`This branch is 1 commit ahead, 7 commits behind main.`
oops

https://github.com/videojs/video.js/tree/master/src/js/tech

**Comment by tomByrer** [comment]
Also the docs all point to master still I assume

https://docs.videojs.com/tutorial-tech_.html

**Comment by gkatsev** [comment]
We are moving towards using inclusive terminology where-ever we can and thus switched our default branch name to be `main`. https://twitter.com/videojs/status/1274023906358300674

It reason that it's one commit ahead and 7 behind is that I accidentally merged a PR against the old branch but I've cherry-picked it into the new branch already (https://github.com/videojs/video.js/commit/6e7cc75aaa179cfce0819d2f99dac21b9a01b67d).

**Comment by tomByrer** [comment]
gotcha
