### ISSUE TITLE
HLS CMAF with Widevine and PlayReady ERROR IN VIDEO.JS using Azure Media Services

### ISSUE THREAD

**Issue by MircoFiocchiSW** [videojs/video.js#6733]
## Description
Hello, we have an issue when we try to reproduce HLS CMAF  with DRM (Widevine or PlayReady according to the browser) in live stream. The isses were found in EDGE v44.18362.449.0 and also in ANDROID. 

### Expected
Reproduce the content.

### Actual
Video.js show this message: 
The media could not be loaded, either because the server or network failed or because the format is not supported. 

### Error output
By console debug this: 
ERROR function () { for (var _len2 = arguments.length, args = new Array(_len2), _key2 = 0; _key2 < _len2; _key2++) { args[_key2] = arguments[_key2]; } return logByType('error', level, args); }

#### videojs
Video.js 7.8.2
#### browsers
EDGE v44.18362.449.0
Edge Chromium-based  v83.0.478.50+ (only live stream )
#### OSes
Windows 10 with Edge (previously mentioned)
Android with all browsers
### plugins
videojs-contrib-eme

**Comment by gkatsev** [comment]
Is it using SAMPLE-AES? If so, we unfortunately, don't support that currently. Can you switch to AES-128 instead?
