### ISSUE TITLE
android does not execute fullscreen mode in hybrid app.

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [videojs/video.js#6734]
## Description
I used webview in app (hybrid app)
in android, fullscreen mode is not working.
when executed in webview is working, but in app is not working...
please help me

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
If your webview does not support the fullscreen API, fullscreen won't work. Webviews don't have all the functionality of a browser. Unfortunately quite a lot of configuration needed, especially on Android. See e.g. https://stackoverflow.com/questions/15768837/playing-html5-video-on-fullscreen-in-android-webview/16179544#16179544
