### ISSUE TITLE
Add new seekbar with current-time and remaining-time

### ISSUE THREAD

**Issue by clixmat** [videojs/video.js#6736]
## Description

Hello, I am having difficulty adding a new progress bar in vue, I have all the necessary fields, but when I try to create a new component to be heard from video.js, it doesn't work. Please @gkatsev  help.

### Expected

![video](https://user-images.githubusercontent.com/41817274/86332280-ede59980-bc0f-11ea-8cfc-fc9503da1ead.png)

This is the result that I want to achieve.

### Actual

This is what I have right now ...

![videojs](https://user-images.githubusercontent.com/41817274/86332416-1ff6fb80-bc10-11ea-8167-180fb6ccc905.PNG)

Thanks

**Comment by gkatsev** [comment]
Can you provide a live minimal and complete example of what you're trying to do?
