### ISSUE TITLE
Force rotation metadata?

### ISSUE THREAD

**Issue by Directory** [videojs/video.js#6738]
## Description
Sorry im not formatting this issue properly but a lot of the fields do not apply. But for my purposes i need to be able to rotate video. I have a video thats 720 wide and 1280 high which is encoded with a 90 degree rotation. I need to be able to display it rotated -90 or 270 degrees so it looks normal again (with the visual resolution of standard 1280x720). I noticed video.js has support for video rotation metadata encoded within the .mp4 file source. However it would be very difficult to get the backend to apply rotation metadata with ffmpeg. I was wondering if i can force rotation metadata within video js somehow. Im aware there are a few plugins that can rotate a video but they are all abandoned and dont work well. Is it possible to force video rotation metadata or possibly some other alternative to rotate the video?

#### videojs
the newest distribution from the unpkg cdn
### plugins
https://github.com/mister-ben/videojs-seek-buttons

**Comment by gkatsev** [comment]
I'm not exactly sure what you're looking for, but we don't have anything for this. If you have an example, it may help and screenshots.
You can try using CSS to rotate the video element?

**Comment by Directory** [comment]
thanks for being useless
