### ISSUE TITLE
VIDEOJS: TypeError: Cannot read property `warn` of undefined

### ISSUE THREAD

**Issue by nwaughachukwuma** [videojs/video.js#6742]
## Description
I get a `VIDEOJS: ERROR: TypeError` on my browser (Chrome & Opera) console when I start playing a video 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Start playing a video 
2. After 1 sec, the error gets logged on the browser console

### Expected
No errors thrown

### Actual
After 1 sec, the error gets logged on the browser console

### Error output
If there are any errors at all, please include them here.

```ts
video.es.js?3d45:97 VIDEOJS: ERROR: TypeError: Cannot read property 'warn' of undefined
    at TextTrack.eval (videojs-mux.js?ea32:8)
    at TextTrack.data.dispatcher (video.es.js?3d45:1899)
    at trigger (video.es.js?3d45:2035)
    at TextTrack.EventTarget.trigger (video.es.js?3d45:2438)
    at TextTrack.eval (video.es.js?3d45:7429)
    at HTMLVideoElement.data.dispatcher (video.es.js?3d45:1899)
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
Video.js: 7.8.3
Mux: 3.1.0
#### browsers
what browser are affected?
`Chrome` and `Opera`
#### OSes
what platforms (operating systems and devices) are affected?
MacOs
### plugins
are any videojs plugins being used on the page? If so, please list them below.

1. Video.js-mux (3.1.0)

**Comment by gkatsev** [comment]
Do you have a minimal, complete, verifiable example you can share please?

**Comment by nwaughachukwuma** [comment]
Hi @gkatsev, I have tried to reproduce the error on a minimal Vue app on code sandbox, to no avail. But then I discovered that when I commented out `videojs-mux` import in `main.js` I didn't get the error. This means that the latest version of [mux 3.1.0](https://www.npmjs.com/package/videojs-mux) has issues which isn't present in the previous `3.0.0` version which I downgraded to.

**Comment by gkatsev** [comment]
Interesting. I would contact mux support and let them know.

**Comment by jsanford8** [comment]
Hi @nwaughachukwuma - please update the videojs-mux plugin to v3.1.2 or newer, which should address this issue.

**Comment by nwaughachukwuma** [comment]
Ok thanks @jsanford8

**Comment by nwaughachukwuma** [comment]
Hi @jsanford8, so I tried the latest releases of videojs-mux and video.js, and still got the same error. This happens whenever I hit the bigPlayPause button and I'm not sure what's happening.

<img width="349" alt="Screenshot 2020-12-11 at 11 19 26" src="https://user-images.githubusercontent.com/20521315/101891757-bf96bd80-3ba2-11eb-91ad-63750e002ca4.png">
