### ISSUE TITLE
Black poster - Prevent of that (set own poster generated by JS)

### ISSUE THREAD

**Issue by SkuterPL** [videojs/video.js#6743]
Hey,
I use the newest version of video.js and I have problem with my movie, because on first 0.5 second I have black screen, so before starting it, I see just black box, there is any option to automatically create poster from middle of movie or specific time which I set?

**Comment by gkatsev** [comment]
Unfortunately, there's no way to automatically create a poster from the middle of the video. Your best bet is to provide a separate poster via the `poster` attribute on the video element.
