### ISSUE TITLE
textTracks returns empty on Android device running Chrome

### ISSUE THREAD

**Issue by sturbefield** [videojs/video.js#6745]
When calling .textTracks() returns an empty array on a Android Pixel 2 XL in Chrome. Below is the code that I am running on Windows and Mac devices in many browsers which is able to get a timestamp from the video metadata successfully. This is decoding a HLS stream being streamed from Wowza.

```
player.textTracks().addEventListener('addtrack', function (addTrackEvent) {
    var track = addTrackEvent.track;
    track.mode = 'hidden';

track.addEventListener('cuechange', function (cueChangeEvent) {
    cueData = track.activeCues[0];
    if (cueData != undefined && cueData.value.key === 'TXXX') {
        console.log(cueData.value.data)
    }              
});

});
```

Many thanks
Stuart

**Comment by gkatsev** [comment]
Are you using `overrideNative`? I would make sure it's set, native HLS on Android likely can't parse the id3 metadata track.
