### ISSUE TITLE
How to use plug-ins with Angular 9 & Webpack?

### ISSUE THREAD

**Issue by ksilz** [videojs/video.js#6747]
## Description
I have video.js running in my Angular 9 app just fine. But I can't get any plug-in to work. I use 'videojs-seek-buttons` as an example here.

## Steps to reproduce
1. I use Angular 9.1.11.
1. I use Webpack 4.43.0.
1. I use `video.js` 7.8.4.
1. I use [`videojs-seek-buttons` 1.6.0](https://www.npmjs.com/package/videojs-seek-buttons). Since there are no Typescript types for `videojs-seek-buttons`, I don't import it but use `require` instead.
1. Here's how I set up the player. I actually use two different ways of trying to get the `videojs-seek-buttons` to show:

```typescript {.line-numbers}
require('videojs-seek-buttons');

[...]

const playerOptions = {
  autoplay: autoPlay,
  controls: this.configuration?.controls,
  loop: this.configuration?.loop,
  muted: this.configuration?.muted,
  preload: this.configuration?.preload,
  fluid: this.configuration?.fluid,
  responsive: this.configuration?.responsive,
  sources: [
    {
      src: file.source,
      type: file.type
    }
  ],
  plugins: {
    seekButtons: {
      forward: 15,
      back: 15
    }
  }
};

const videoPlayer = document.getElementById('videoPlayerProprietary');

if (videoPlayer != null) {
  videoPlayer.style.display = 'block';
  this.player = videojs(videoPlayer, playerOptions);

  this.player.seekButtons({
    forward: 15,
    back: 15
  });
}
```

### Expected
I expect the seek buttons to show up.

### Actual
The seek buttons **don't** show up.

### Error output
The lines starting with `this.player.seekButtons({` create this error in Chrome:

```
Error: plugin "seekButtons" does not exist
```

When I restart Angular, then it doesn't even compile: `error TS2339: Property 'seekButtons' does not exist on type 'VideoJsPlayer'.`

If I take these lines out and leave the plug-in configuration to ` plugins: {`, then the code compiles and shows no runtime error - but no seek buttons, either.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.4
#### browsers
Chrome 83.0.4103.116 (Official Build) (64-bit)
#### OSes
macOS Catalina 10.15.5 (19F101)
### plugins
videojs-seek-buttons 1.6.0

**Comment by gkatsev** [comment]
Using require for the plugin instead of import may mean that the plugin gets a different file for Video.js loaded by the bundler since we set a main and module attribute in the package.json https://github.com/videojs/video.js/blob/main/package.json#L5-L6

**Comment by thijstriemstra** [comment]
I'm running into the same issue: trying to get a plugin to work with angular.

**Comment by ksilz** [comment]
@thijstriemstra Thank you for your response! Sorry for only getting back to you now. I‘ll try the import over the next couple of days and will let you know.

**Comment by thijstriemstra** [comment]
@ksilz I managed to work it out.

**Comment by ksilz** [comment]
@thijstriemstra Would you mind sharing your solution? Thank you!

**Comment by thijstriemstra** [comment]
@ksilz see either https://collab-project.github.io/videojs-wavesurfer/#/angular or https://collab-project.github.io/videojs-record/#/frameworks/angular, both video.js plugins.
