### ISSUE TITLE
Cannot add click handler for Closed Caption menu item (vjs-menu-item)

### ISSUE THREAD

**Issue by bilberryfm** [videojs/video.js#6748]
## Description
Hi,

We use VideoJS player, I'm trying to add simple click handler  for items in Closed Caption menu popup (To track how many clicks happened on each item). However, the click even is never triggered for me.

To be more specific, I need to have click handler for following element: `.vjs-subs-caps-button .vjs-menu-item:nth-child(1) .vjs-menu-item-text`. Tried for this one too: `.vjs-subs-caps-button .vjs-menu-item:nth-child(1) .vjs-menu-item-text`, but that doesn't work: the handler is not triggered. I confirmed that this jquery selector works fine and the html element is presented when I am trying to register click handler:

```
$(.vjs-subs-caps-button .vjs-menu-item:nth-child(1) .vjs-menu-item-text').click(function (e) { 
     console.log("click on vjs-menu-item");
});
$(.vjs-subs-caps-button .vjs-menu-item:nth-child(1)').click(function (e) { 
     console.log("click on vjs-menu-item");
});
```
Tried with `live()` too, tried unbind - bind clicks. Clicks on all other control bar items work fine.

Is there anything in video js code that prevents click on menu item to happen?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Add custom click handler in javascript as shown in example above.

### Expected
Click handler should be triggered on CC menu item click

### Actual
Click handler is not triggered on CC menu item click

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
Chrome
#### OSes
Mac OS
### plugins
No

**Comment by bilberryfm** [comment]
Hi, any updates on this?

**Comment by gkatsev** [comment]
Just tried
```js
document.querySelector('.vjs-subs-caps-button .vjs-menu-item:nth-child(1) .vjs-menu-item-text').addEventListener('click', function() { console.log('foo')});
```
locally and seems to be working. Have a live minimal example where you can reproduce the issue?
