### ISSUE TITLE
If there are problems with the HLS stream

### ISSUE THREAD

**Issue by Raino** [videojs/video.js#6749]
Hello! 
I have a question. I use videojs to show HLS streams, but sometimes the following errors occur when working with them. For example, a playlist has not been formed yet, but the player is already requesting it, or there was a network outage. In these cases, the player issues errors and stops working. I spent a few days looking for solutions, but none of them worked for me. I read about the `reloadSourceOnError` method, but it restarts the player only once. I read that in the videojs 6.0 version there was a "problem" that the player endlessly tried to restore the connection. I tried using this version, but it didn't work. Please tell me if there are any videojs methods or algorithms that I can use to make the player always try to establish a connection or try to repeat the playback attempt, but so that there is no situation that the player is trying to download some broken .ts file, as it was described in the same issue about the videojs version 6.0. 
I Will be very grateful if your answer will include a full-fledged code example. 
Thanks!

**Comment by AndrewFeeney** [comment]
@Raino Did you ever find a solution for this?
