### ISSUE TITLE
No playback in Chrome on Ubuntu

### ISSUE THREAD

**Issue by jskarpe** [videojs/video.js#675]
Accessing: http://www.videojs.com/

Version 28.0.1500.71 Ubuntu 12.04 (28.0.1500.71-0ubuntu1.12.04.1)

Works fine using Chrome in Windows 7 (28.0.1500.95 m)

Chrome reads the mp4 in both Windows 7 and Ubuntu - but mp4 is not supported in Chrome for Ubuntu

**Comment by Kief5555** [comment]
I am having the same issue on mac. Twitter, Tiktok, etc. dont work
