### ISSUE TITLE
Volume and Play button icon not changing on click 

### ISSUE THREAD

**Issue by manojkumar3692** [videojs/video.js#6751]
## Description
When Im Trying to Click on the Play Button and Volume Button , The icon is not changing to Mute or Pause 

Second is how do we make the video play the live feed after the user click on pause/play button . When even the use press pause and click play again the video has to play the latest live video . 

```
    const videoJsOptions = {
      controls: true,
      autoplay: 'any',
      preload: 'auto',
      poster: LoaderImg,
    }

       <div className="video-js vjs-default-skin" playsinline data-vjs-player >
          <video className="video-js vjs-default-skin" ref={ node => this.videoNode = node } playsinline className="video- 
          js">
              
          </video>
        </div>
```

**Comment by gkatsev** [comment]
I cannot reproduce the first thing.

As for the second piece, you can seek to the seekable end point on a play request.
