### ISSUE TITLE
Does Videojs player support with Hybrid Android App?

### ISSUE THREAD

**Issue by kvmoondra** [videojs/video.js#6753]
Hello there,
Hope you are doing well.

With regards, we are developing a hybrid video news android app(from our app: we are going to distribute the hyperlocal video news feed to end-users, only video content).

For the above, we are looking to integrate Videojs player and the technologies we are using to develop the Hybrid Android App are:
Ionic, Angular JS, Node JS & MySQL

Does videojs player support with hybrid android app(Ionic, Angular Js, Node JS & MySQL)?

Will wait to hear from you

Thanks & Regards
Kumar Vansh Moondra

**Comment by gkatsev** [comment]
It's definitely possible to use Video.js in hybrid apps as we've seen them before.
Unfortunately, we aren't able to provide guidance on how to use it directly as we don't have much experience with Angular or hybrid apps ourselves.
