### ISSUE TITLE
live stream interpretation unconsistancy using "liveui" interface

### ISSUE THREAD

**Issue by semel1** [videojs/video.js#6755]
## Description
Live stream sources  interpretation is not consistent with "liveui" interface . 
## Steps to reproduce
1.Install videojs player with data-setup='{"liveui": true}'
2.Case 1:Specify live video source from:<source src="//rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master_3360.m3u8", type='application/x-mpegURL' />
3.Case 2:Specify live video source from:<source src="https://5b44cf20b0388.streamlock.net:8443/live/ngrp:live_all/playlist.m3u8", type='application/x-mpegURL' />
## Results
In both cases streams recognized and could be played back
In case #1 - control panel shows  the progress/seek bar and lets the user seek backwards/forwards within the live window. Next, it adds a button, via the "SeekToLive" component that can be clicked when the user is behind live that will seek to the live current time.
In case #2 -  control panel shows "live" text only and doesn't show:  the progress/seek bar and "SeekToLive" component.
### Expected
In both cases I expect to see the same "liveui" controls on the control bar.
![Live_false](https://user-images.githubusercontent.com/53234248/87497797-2bccbf80-c60b-11ea-9974-cc86fa044fc5.jpg)
![Live_true](https://user-images.githubusercontent.com/53234248/87497798-2c655600-c60b-11ea-86ca-16c2a3eafa43.jpg)

### Actual
On tested live streams from different sources 
(https://gist.github.com/HayriGomer/06d957eeb1f87d817b3d1901576a6e40), proper "liveui" interface showed up approx in 3:10 ratio. (From approx 10 tested sources only 3 gets recognized by "liveui" and shows it's interface.)
### Error output
There is no error output on console
## Additional Information
Tested on videojs versions started from 7.0.1 till 7.8.4
#### browsers
Firefox,Opera,Chrome,Edge,Safari
#### OSes
Windows7/10s,Android
### plugins
no plugins been used.

**Comment by mister-ben** [comment]
It depends on the stream having a DVR buffer to seek within. The first stream has keeps segments in the playlist, so is seekable. The second has only three, so is not.
