### ISSUE TITLE
 When the player starts for the first time, something strange appears on the screen in aos webview

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [videojs/video.js#6756]
## Description

When the player starts for the first time, something strange appears on the screen in aos webview.
This screen is only aos webview.
When the video is being prepared, I want a black screen.
please help me

## Results
<img width="605" alt="스크린샷 2020-07-15 오후 6 52 13" src="https://user-images.githubusercontent.com/30399546/87531714-13bd7480-c6cd-11ea-9879-698f453f3661.png">
### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
That's the webview's default styling of a video el before a source has loaded, I think. Try using a `<video-js>` element instead.

**Comment by juuuuuuuuuuuuuu** [comment]
> That's the webview's default styling of a video el before a source has loaded, I think. Try using a `<video-js>` element instead.
<video-js> is html tag?? instead <video> ??
it is not working...

**Comment by mister-ben** [comment]
`<video-js>` instead of `<video>`. See https://docs.videojs.com/tutorial-setup.html#creating-a-player
