### ISSUE TITLE
Videojs does not send cookie receive from Set-Cookie in Headers

### ISSUE THREAD

**Issue by whatever1211** [videojs/video.js#6758]
## Description
I'm building a video player page, which getting m3u8 file from server. The server require a token to access which first send as parameters. The response header return the access token in Set-Cookie, however the following videojs's request to get *.ts filesdoes not add access token cookies in xhr request. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Here is my code:
```
<video id="my-video" class="video-js" crossorigin="use-credentials"></video>

<script>
    var streamUrl = "video.example.com/video.m3u8?hdnts=accessToken;
    player = videojs("my-video", {
        "controls": true,
        "preload": 'auto'
    });
    player.src({
        src: streamUrl,
        type: 'application/x-mpegURL'
    });
</script>
```
2. My first response Headers with Set-Cookie is the accessToken
```
HTTP/1.1 200 OK
Server: nginx
Last-Modified: Sat, 20 Jun 2020 06:16:55 GMT
Accept-Ranges: bytes
Content-Encoding: gzip
Content-Length: 200
Date: Sat, 18 Jul 2020 04:42:34 GMT
Connection: keep-alive
Vary: Accept-Encoding
Akamai-Mon-Iucid-Del: 836817
Content-Type: application/x-mpegURL
Set-Cookie: hdntl=accessToken; Domain=video.example.com; Path=/; Expires=Sun, 19-Jul-2020  4:42:31 GMT
Access-Control-Max-Age: 86400
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Server,range,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC
Access-Control-Allow-Headers: origin,range,hdntl,hdnts
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Origin: *
```
3. My first response data
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=339968,RESOLUTION=428x240
e5b7cfef-447b-4197-b310-f0f5ee8ef265_1_.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=650240,RESOLUTION=640x360
e5b7cfef-447b-4197-b310-f0f5ee8ef265_2_.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1175552,RESOLUTION=864x480
e5b7cfef-447b-4197-b310-f0f5ee8ef265_3_.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2325504,RESOLUTION=1280x720
e5b7cfef-447b-4197-b310-f0f5ee8ef265_4_.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4317184,RESOLUTION=1920x1080
e5b7cfef-447b-4197-b310-f0f5ee8ef265_5_.m3u8
```
4. The following xhr request send to video.example.com does not include any cookie which is the access token for my video.example.com server domain.
```
GET /video1/2020/06/20/12/e5b7cfef/e5b7cfef-447b-4197-b310-f0f5ee8ef265_1_.m3u8 HTTP/1.1
Host: video.example.com
Connection: keep-alive
User-Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Mobile Safari/537.36
Accept: */*
Origin: http://localhost:9694
Referer: http://localhost:9694/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
```

### Expected
Videojs continue xhr request for m3u8 files include cookies from Response Header's Set-Cookie.

### Actual
Videojs continue xhr request with only stream url. The server return error 403 for missing access token.

### Error output
![player](https://user-images.githubusercontent.com/32158927/87845439-a63e5d80-c8f1-11ea-8824-44cf6bf1c8f0.png)
![error](https://user-images.githubusercontent.com/32158927/87845442-a9394e00-c8f1-11ea-8bc9-9577fc18b28f.png)

#### videojs
video.js 7.6.1
#### browsers
Chrome
#### OSes
Android
### plugins
None

**Comment by mr-sven** [comment]
I've got the same issue on my video portal.

I was able to reproduce the issue with videojs 7.0.0 and 7.8.4 using Firefox Mobile 68.11.
The users reported me the problem with Android Chrome.
Opera Mobile seems to work.

The browser requests the file first including the cookie and the second request is without cookie.
```
127.0.0.1 - - [03/Aug/2020:18:13:23 +0000] "GET /hls/video.m3u8 HTTP/2.0" 200 931 "https://example.com/video/?video" "Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0"
127.0.0.1 - - [03/Aug/2020:18:13:23 +0000] "GET /hls/video.m3u8 HTTP/1.1" 302 170 "-" "Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0"
```
Chrome Useragent: `Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-T510) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/12.0 Chrome/79.0.3945.136 Safari/537.36`

**Comment by gkatsev** [comment]
The short answer is that VHS doesn't currently use the video element's `crossorigin` attribute. You must supply `withCredentials` on the source object or elsewhere.
We do plan on making VHS use the crossOrigin property from the player at some point but it isn't available right now.

**Comment by mr-sven** [comment]
Using `withCredentials` don't help. Error is still there
```JavaScript
    player.src({
        src: streamUrl,
        type: 'application/x-mpegURL',
        withCredentials: true
    });
```

**Comment by mr-sven** [comment]
I found an issue with the Native Player. 
```JavaScript
player = videojs("video-container", {
    html5: {
        hls: {
            withCredentials: true,
            overrideNative: true
        }
    }
});
```

By disabling the native player it works, so for me it looks like there is a bug in the cookie transport between browser and native player.

**Comment by gianlucamozzillo** [comment]
> I found an issue with the Native Player.
> 
> ```js
> player = videojs("video-container", {
>     html5: {
>         hls: {
>             withCredentials: true,
>             overrideNative: true
>         }
>     }
> });
> ```
> 
> By disabling the native player it works, so for me it looks like there is a bug in the cookie transport between browser and native player.

Hello, have you found a solution?

**Comment by mr-sven** [comment]
Nope, due the fact that nobody respond to it and it is currently running, I stopped investigating on it.

**Comment by jonydog** [comment]
I have tried everything and cookies were not being sent in the requests... 

Indeed your solution (overrideNative: true) worked! 

@mr-sven  thanks a lot!!

**Comment by gurstacey** [comment]
I have set overrideNative: true but cookies are still not sent with requests for the mp4 segments (i see them sent for m3u8 manifest requests). I wired up the beforeRequest and can see both the mp4 and m3u8 requests coming in and both have the 'withCredentials' option set to true but still only the m3u8 requests send the cookies. @mr-sven do you have any suggestions?

**Comment by mr-sven** [comment]
Hi,
I faced some problems with the urls in the m3u8 file. If I use full URLs the cookies may lost. If I use relative urls from videojs to m3u8 to ts file, it works th most.

**Comment by gurstacey** [comment]
Thank you mr@sven. It was actually due to CORS that the request was failing. We pass a Range header for mp4 requests and we hadnt configured that as an allowed-header on the server. Once that was configured it all worked
