### ISSUE TITLE
Chapters are broken in 4.x

### ISSUE THREAD

**Issue by joepvl** [videojs/video.js#676]
Chapters functionality is completely broken in 4.x. This occurs on at least Chrome 28, Firefox 22 and IE9.
#### Expected:

When adding a line like
`<track kind="chapters" source="chapters.vtt" default>`
to a `<video>` element, a chapters button should be shown, with named chapters linking to cue points within the video.
#### Actual:

A js error (`Uncaught TypeError: Cannot read property 'id' of undefined`) occurs and the player crashes, not showing any controls.
See http://jsbin.com/uceyam/1/
#### Further info:

In 3.x, the chapters menu was only created (or at least displayed) if the `<track>` element with attribute/value `kind="chapters"` also had the `default` attribute declared. It seems this attribute is still of influence, since without it defined on the chapters track there is no crash (no chapters, either, though).

If it is defined, like i've done in [this example](http://jsbin.com/uceyam/1/) (it doesn't seem to allow cross-origin linking of track files, but the result is the same - the error seems to occur before it gets to requesting the file), Chrome's js console will show the following error:

`Uncaught TypeError: Cannot read property 'id' of undefined`

This error comes from the `vjs.Component.prototype.addChild` method, which in this instance is being called, presumably somewhere along the creation of the chapters track, button or menu object, without valid `child` and `option` parameters (both having a value of `undefined` when the error occurs). In addition to failing on the chapter tracks, this error causes the player to crash, never showing the controls bar.

People have reported this before on StackOverflow (see [here](http://stackoverflow.com/questions/17063712/video-js-chapter-selection-from-vtt-file-not-working-menu-not-showing-cap) and [here](http://stackoverflow.com/questions/16846560/chapter-tracks-dont-show-with-videojs)).

**Comment by vhmth** [comment]
Is this fixed? I'm not able to get the programmatic or pure markup approach to work. For reference:

*relevant markup*

```
<video controls poster="<%= videoPosterURL %>" class="video-js vjs-default-skin vjs-big-play-centered vjs-fluid">
  <source src="<%= videoURL %>" type="video/mp4" />
</video>
```

*relevant js*

```
var player = videojs(this.$video[0], {}, function () {
  var playTracked = false;
  // we track the first video play only
  this.on('play', function () {
    // we can't simply 'off' the play event since other UI elements depend on it
    if (!playTracked) {
      mixpanel.track(mixpanelEvents.FEEDBACK_VIDEO_PLAYED);
      playTracked = true;
    }
  });
});

player.addRemoteTextTrack({
  kind: 'chapters',
  language: 'en',
  src: '/assets/demo.vtt'
});
```

*demo.vtt*

```
WEBVTT

1
00:00:00 --> 00:00:22
Chapter 1

2
00:00:22 --> 00:00:30
Short chapter

3
00:00:30 --> 00:00:45
Finale
```
