### ISSUE TITLE
I need a custom event

### ISSUE THREAD

**Issue by mrsai** [videojs/video.js#6763]
## Description

I have a heartbeat function. After dragging the progress bar, the length of the user's drag will be uploaded to the server to calculate how much progress the user has skipped. However, the "seeked" event will be triggered several times, and the video progress before dragging cannot be obtained. Therefore, we hope to add a custom event,like "seekedonce", which is triggered only once after seeked, and record the start and end positions of the video when the event is triggered.

**Comment by mrsai** [comment]
handleMouseDown  [slider.js,progress-control.js]

`handleMouseDown(event) {
    const doc = this.bar.el_.ownerDocument;
    this._mouseDownTime = this.player_.currentTime();
    ...
}`

handleMouseUp [slider.js]
`

    /**
     * Triggered when the slider is no longer in an active state.
     *
     * @event Slider#sliderinactive
     * @type {EventTarget~Event}
     */
    .....
    this.trigger('sliderinactive');
    this.off(doc, 'mousemove', this.handleMouseMove);
    this.off(doc, 'mouseup', this.handleMouseUp);
    this.off(doc, 'touchmove', this.handleMouseMove);
    this.off(doc, 'touchend', this.handleMouseUp);
    this.update();
    if(this.timer){
      clearTimeout(this.timer)
    }
    this.timer = setTimeout(()=>{
      const start = this._mouseDownTime
      const end = this.player_.currentTime()
      this.player_.seekData = {
        start,
        end
      }
      this.player_.trigger("seekedonce")
    })

`

how to use

`  
var player = videojs(vid);
    player.on("seekedonce",(e)=>{
      console.log(player.seekData)
    })
`

**Comment by gkatsev** [comment]
If the native controls are being used, you can use [videojs middleware](https://docs.videojs.com/tutorial-middleware.html) to know exactly where a user seeked to.
But you can definitely trigger your own events like that. However, we don't plan on supporting something like that in Video.js.
