### ISSUE TITLE
How to use with NPM

### ISSUE THREAD

**Issue by gregg-cbs** [videojs/video.js#6768]
How do you use this with javascript imports!?

There is nothing in the docs except for the install command.
No examples of importing. No examples of where to go from there.

Even on NPM the examples are of using a CDN.

I am trying to do the below, but nothing happens. What is the procedure to get video js running?
```
import "video.js";
```

**Comment by gkatsev** [comment]
Looks like it is something we're a bit lacking. You can use the react example for a sample of how to use it with imports https://docs.videojs.com/tutorial-react.html.
