### ISSUE TITLE
VIDEOJS: TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by vkulov** [videojs/video.js#6769]
## Description
Seeing an odd error on a client machine

## Steps to reproduce
We play a hls audio stream that is playable everywhere else we tried.

### Expected
Audio plays correctly

### Actual
Audio doesn't play

VIDEOJS:ERROR:TypeError: Reduce of empty array with no initial value
### Error output
If there are any errors at all, please include them here.

VIDEOJS:DEBUG:VHS:SegmentLoader[main] >playlist update [null => 0-https://xxxxxxxxxx.m3u8]
VIDEOJS:DEBUG:VHS:SyncController >syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]
VIDEOJS:DEBUG:VHS:MPC >seekable updated [0 => 1429.247999999999]
VIDEOJS:DEBUG:VHS:MPC >Setting duration from NaN => 1429.247999999999
VIDEOJS:DEBUG:VHS:SegmentLoader[main] >playlist update [0-https://xxxxxxxx.m3u8 => 0-https://xxxxx…
VIDEOJS:DEBUG:VHS:SyncController >syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]
VIDEOJS:DEBUG:VHS:SegmentLoader[main] >live window shift [0]
VIDEOJS:DEBUG:VHS:SegmentLoader[main] >INIT -> READY
VIDEOJS:DEBUG:VHS:SourceUpdater[main][audio/mp2t; codecs="mp4a.40.5"] >created SourceBuffer
VIDEOJS:ERROR:TypeError: Reduce of empty array with no initial value
VIDEOJS:
ERROR:
TypeError: Reduce of empty array with no initial value
VIDEOJS:DEBUG:VHS:SyncController >syncPoint for [time: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]
VIDEOJS:DEBUG:VHS:SegmentLoader[main] >READY -> WAITING
VIDEOJS:DEBUG:VHS:SegmentLoader[main] >WAITING -> READY
VIDEOJS:WARN:Problem encountered with the current HLS playlist. Trying again since it is the only playlist.
VIDEOJS:DEBUG:VHS:SegmentLoader[main] >playlist update [0-https:/xxxxxxxxxxx.m3u8 => 0-https://xxxxxx…
VIDEOJS:DEBUG:VHS:SyncController >syncPoint for [segmentIndex: 0] chosen with strategy [VOD]: [time:0, segmentIndex:0]
VIDEOJS:DEBUG:VHS:SegmentLoader[main] >live window shift [0]

Windows 10 Win64
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

**Comment by gkatsev** [comment]
Does it fail with any audio-only HLS? Have a stream you can share with us that you can reproduce this in?
Also, can you try testing on https://videojs-http-streaming.netlify.app/?

**Comment by vkulov** [comment]
Must be something specific to the hardware of the user or his OS in a weird state. We were not able to reproduce it on our end with the same stream and same player. I think it started to work for the user after OS restart as he didn't report it again.

**Comment by gkatsev** [comment]
Interesting. Any more to do here right now? Or can we close it until this issue arrises again?
