### ISSUE TITLE
when I rotate video tag, the progress is not working.. 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [videojs/video.js#6770]
## Description

 I rotated video element, the progressbar is not working.  

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. I rotateed video element, the progressbar is not working.  
2.
3.

![image](https://user-images.githubusercontent.com/30399546/88363823-3ed65100-cdbc-11ea-8e87-3743cd33f7c8.png)
![image](https://user-images.githubusercontent.com/30399546/88363839-51508a80-cdbc-11ea-9594-bf7c82f93235.png)

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
The mouse logic of the progress control specifically looks for left-right position. It is possible for a seekbar to look for top-bottom mouse position but it needs to be configured for that and won't work automatically when the player is rotated.
Something like
```js
const player = videojs('myPlayer', {
  controlBar: {
    progressControl: {
      seekBar: {
        vertical: true
      }
    }
  }
});
```

**Comment by hncsjxxxx** [comment]
do it work?i have same problem too

**Comment by hncsjxxxx** [comment]
i try, but faild

**Comment by hncsjxxxx** [comment]
i solved ,find the source code, find the getPointerPosition method ,change ' position.y = Math.max(0,Math.min(1,(pageY-boxY)/boxW))',and find the ' var sizeKey',change to ' var sizeKey = _this2.vertical()? 'width':'width';
