### ISSUE TITLE
Bug on VideoJS webview Android Chromium

### ISSUE THREAD

**Issue by Borna-f** [videojs/video.js#6771]
## Description
Hi,
The video gets buggy on loading sometimes. It does not happen always. So not sure how to reproduce. What I do is to go through loading videos a couple of times so that I encounter this problem.

Here is the link that shows what happens:

https://www.youtube.com/watch?v=aWQzY-1VYq4&feature=youtu.be

The error I get on the android side is 
E/chromium: [ERROR:shared_image_factory.cc(471)] CreateSharedImage: could not create backing.
E/chromium: [ERROR:shared_image_stub.cc(169)] SharedImageStub: Unable to create shared image
E/chromium: [ERROR:shared_image_manager.cc(141)] SharedImageManager::ProduceGLTexture: Trying to produce a representation from a non-existent mailbox. 

#### videojs
Any version I guess. I used the latest one 7.9.2
#### browsers
Chromium (Android webview)

#### OSes
Android webview

**Comment by deveshmishra34** [comment]
Did you resolve this issue... because I’m also facing a similar kind of issue only in android devices with all type of video formats (MP4, HLS, Youtube, DASH). Currently I’m using 7.6.6 videojs and 1.10.6 @videojs/http-streaming

https://youtu.be/5pFBt8JwGpU

**Comment by deveshmishra34** [comment]
I suppose this problem is related to latest android webview. because when i tried with 80.0.3987.99 version it worked.

**Comment by Borna-f** [comment]
I don't think it is related to webview. I use wendu dsbridge DWebView and I have the problem. It's something related to videoJS and it happens randomly (It's not always the case). I really hope that some dev people from VideoJS see this issue and fix it. Otherwise the other solution would be using HTML 5 video instead of videoJS library.

**Comment by DwaineSaunderson** [comment]
@Borna-f I've been able to reproduce this issue when embedding a video using a standard HTML `<video>` element too, so I don't think this is necessarily caused by VideoJS.

**Comment by Borna-f** [comment]
@DwaineSaunderson Thanks for the info. That's good to know.

Has anyone found any solution yet?
