### ISSUE TITLE
Cannot play RTMP f4m or f4v

### ISSUE THREAD

**Issue by precision1980** [videojs/video.js#6772]
I am trying to play media streams over rtmp. I have tried mp4, f4v, m3u8u, and f4m. is there something I am doing wrong?

I get this error: VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. [object Object]

I am able to use VLC and connect to it. I can also broadcast to it.

I am using Adobe Media Server Enterprise

```
  <div class="video-container">
	<video id="main-video" width="960" height="540" class="video-js vjs-default-skin" controls>
	  <source src="rtmp://localhost/video/mp4:rtmp_sample1_manifest.f4m" type="rtmp/mp4">
	</video>
  </div>
  <-------------------  // Different attempts \\  ------------------------>
  <div class="video-container">
	<video id="main-video" width="960" height="540" class="video-js vjs-default-skin" controls>
	  <source src="rtmp://localhost/video/mp4:rtmp_sample1_manifest.f4m" type="rtmp/flv">
	</video>
  </div>

```

**Comment by gkatsev** [comment]
You didn't provide the version of Video.js you're using. However, if you're using a recent version of Video.js, you must include the videojs-flash tech separately. In addition, a lot of browsers make it really difficult to run Flash content, so, I would highly advise looking into alternative video delivery formats.
