### ISSUE TITLE
HLS remote live stream quality is poor at the beginning when open the stream

### ISSUE THREAD

**Issue by heaven-dev** [videojs/video.js#6774]
## Description

This is not a bug report. This is question and I will be happy if someone can give me some advices how to proceed.

I am developing [application](https://github.com/heaven-dev/tv7samsung) to Samsung smart TV. It is web application. I am using **video.js** to show **HLS** live stream.

HLS live remote stream quality is poor at the beginning when I open the stream, but after 10 - 20 seconds quality is good. How to avoid poor quality at the beginning? When I run app in Samsung emulator and when I check video element using inspector of the browser I see that the blob URL is not created to the **src** attribute in that poor quality case. When I run same application using **live-server** web server locally the blob URL like (blob:http://127.0.0.1:8080/60aadab0-0521-4c3b-938b-42da77ce3cab) is created to the **src** attribute and the quality of stream is good from beginning.

Is there know problem when using HLS remote URLs with video.js? Or is this issue related somehow to Samsung smart TV emulator and TV? 

I have implemented same application also to Android TV ([exoPlayer](https://github.com/google/ExoPlayer)) and there same URL quality is good from the beginning.

  - My application: https://github.com/heaven-dev/tv7samsung
  - My video tag in the application in HTML: https://github.com/heaven-dev/tv7samsung/blob/master/html/player.html#L19
  - My javascript implementation (video.js): https://github.com/heaven-dev/tv7samsung/blob/master/js/player.js#L22

## Steps to reproduce
1. Samsung smart TV example app, see above bullet list
2. URL to reproduce: https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8'
3. Same happens also to other HLS remote URLs.

### Expected
Quality should be good from the beginning of the stream.

### Actual
Quality is not good from the beginng (10 - 20 seconds) of stream. You can check GIF animation from [here](https://github.com/heaven-dev/tv7samsung/blob/master/README.md#tv7samsung) to see that HLS stream quality is not good from the beginning (subtitles) but at the end of animation it is better.

### Error output
No errors.

#### videojs
video.js version 7.9.2

#### browsers
Not known what is version of the browser in Samsung Smart TV emulator or TV.

#### OSes
Samsung [Tizen SDK for TV](https://developer.tizen.org/tizen/tv).
### plugins
No

**Comment by gkatsev** [comment]
You can try setting the [bandwidth property](https://github.com/videojs/http-streaming#bandwidth) assuming that you are setting [overrideNative](https://github.com/videojs/http-streaming#overridenative) so that our playback engine is being used. Setting `bandwidth` would make our playback engine try and find the playlist closest to that. I believe by default we look for a 0.5MBps playlist.

**Comment by heaven-dev** [comment]
@gkatsev 

Thank you for your response. You were right. Setting those options fixed the issue. 

This kind of **video.js** options did a trick.
```ts
var options = {
    preload: 'auto',
    autoplay: true,
    muted: false,
    fluid: true,
    html5: {
        hls: {
            overrideNative: true
        },
         nativeAudioTracks: false,
         nativeVideoTracks: false
     },
     bandwidth: 80000000
};
```

**Comment by lineldcosta** [comment]
@heaven-dev  could you please update the video.js version, I am using 7.10.1 version which does not allow me to define bandwidth property using typescript.

**Comment by heaven-dev** [comment]
Hi @lineldcosta 

Not sure but the following configuation might work with the HLS stream. Now I am using video.js 7.11.4.

```ts
let options = {
    ...
    html5: {
        vhs: {
            overrideNative: true,
            bandwidth: 80000000
        },
        nativeAudioTracks: false,
        nativeVideoTracks: false
     }
};
```

**Comment by lineldcosta** [comment]
Tried the same configuration with 7.11.4 but still quality is poor in chome(windows) at the beginning of video then they load fine after some seconds.

**Comment by heaven-dev** [comment]
Check the following configuration: https://github.com/heaven-dev/tv7SamsungNg/blob/main/src/app/components/archive-player/archive-player.component.ts#L110

The configuration is from my app. No poor quality when using the configuration like on the link.

You can run the app on a browser by changing value of this https://github.com/heaven-dev/tv7SamsungNg/blob/main/src/app/helpers/constants.ts#L1 to **true**.

After that:
- npm install
- ng serve
- navagate to: http://localhost:4200

When the first page opens, press enter and the HLS stream starts with good quality.

**Comment by heaven-dev** [comment]
Actually the configuration link above was from the wrong file. Right configuration link is here: https://github.com/heaven-dev/tv7SamsungNg/blob/main/src/app/components/tv-player/tv-player.component.ts#L68

I have two player components. One is TV player and the other is video player for archive videos. When the enter key is pressed on the first page of the app the TV player component is used and it shows live HLS stream.

**Comment by lineldcosta** [comment]
Forgot to update here... I was able to achieve this functionality using `videojs-contrib-quality-levels` library.
