### ISSUE TITLE
VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "The media could not be loaded..

### ISSUE THREAD

**Issue by chanof** [videojs/video.js#6775]
## Description
Using Safari 13.1.2 on dash live stream on www.unknow.tv:
- I'm unable to resume the pause, when clicking play again the stream crash:

```
[Error] VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "The media could not be loaded, either because the server or network failed or because the format is not supported." – _t {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported.", status: null, …}
_t {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported." 
```

- The js console is full of errors per second like:

`17719][SourceBufferSink] getAllBufferRanges exception: The object is in an invalid state. `

- Im not sure about player cache management, since is a live setup I need to avoid waste of ram

Video.js version is 7.8
Video js contrib dash 2.11
Mpeg dash live streaming 4 representation + audio powered by MP4Box pass the dash conformance tool validation.

The streaming is online, may ask special help to debug this player and give your feedback about the correct live streaming setup/configuration

Thanks a lot
Gian

**Comment by gkatsev** [comment]
I was able to reproduce the issue in Chrome for a minute and it seemed to work in our playback engine via (https://videojs-http-streaming.netlify.app/) until CORS errors started happening.

Also, it seems like that page is using Video.js 7.4 which is quite old, definitely worth upgrading. As for DASH playback, it seems like contrib-dash is being used which is DASH.js which we don't maintain. Does your stream work in their test page?

**Comment by pradeepaanumalla** [comment]
This is still occuring in chrome
