### ISSUE TITLE
Handling Airpods events

### ISSUE THREAD

**Issue by Mootook** [videojs/video.js#6778]
## Description
Opening this because nothing is coming up so I'm not sure what the discussion surrounding this is.
Airpods when removed pause videos and play when put back into the ear.
I know this is intended on Apple's part, but I'm wondering if there's anything we can set on our end
to prevent or at least control this behavior.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Have a videoJs element with a loaded, playing video
2. Have airpods in and connected to computer through bluetooth
3. Remove/Insert airpods and notice video pauses/plays accordingly

### Expected
Again, this is expected...mainly curious if anyone has more info into this behavior.

**Comment by gkatsev** [comment]
Unfortunately, there's no way to handle specific airpod events. To us it looks just like a regular pause event.
