### ISSUE TITLE
After closing fullscreen on iOS Chrome browser, controls are no longer updating 

### ISSUE THREAD

**Issue by mikeswart** [videojs/video.js#6779]
## Description

When using the chrome browser on iOS, after exiting exiting full screen display of the video, videoJS controls no longer respond to video player state. 

## Steps to reproduce
Using the chrome on an iOS device (I used a 7'th gen iPad)
1. Navigate to https://videojs.com
1. Tap play on the sample video
1. Tap  fullscreen
1. Close fulllscreen

### Expected
The controls for the video should continue to match the current state of the player.

### Actual
* The play / pause button no longer updates, but still controls the video playback. 
* Time remaining does not update while the video plays

### Error output
 N/A

#### videojs
[7.9.2](https://github.com/videojs/video.js/releases/tag/v7.9.2)
#### browsers
iOS Mobile Chrome (84.0.4147.71)
#### OSes
iOS 13.6 (7'th Gen iPad)
### plugins
N/A

**Comment by gkatsev** [comment]
Videojs.com currently uses Video.js version 7.8.3 which doesn't contain the fix for this which is available in 7.8.4 and 7.9.2.

**Comment by gkatsev** [comment]
The fix was https://github.com/videojs/video.js/pull/6735

**Comment by mikeswart** [comment]
Thank you @gkatsev! I'll update to the latest and this out.

**Comment by gkatsev** [comment]
Just updated the website to use 7.9.2, should deploy in a minute.

**Comment by mikeswart** [comment]
Confirmed working 👍

**Comment by gkatsev** [comment]
Thanks!
