### ISSUE TITLE
Video decoding breaks randomly

### ISSUE THREAD

**Issue by vgrafe** [videojs/video.js#6780]
## Description
Some of my users report what seem to be decoding issues on all major browsers (FF< chrome, safari). MPEG-DASH manifests with .m4f segments are used, except for safari, on which I send a HLS manifest (that refers the same m4f segments). Encodings are h264 for HD content, h265 for 4K, but I've seen the bug on both encodings. Bitrates are in standard value range for each representation.

I've also seen this happen a lot more when using `contrib-eme` used in the context of getting DRM licences, but in this scenario it is not used.

Screenshots at the bottom of the description.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load the manifest, observe the video going green and pixelated within the first second. The decoder never recovers. 
2. Refresh. Chances are it does not happen again.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.4
#### browsers
Chrome, FF, safari
#### OSes
macOS
### plugins
no plugins used.

Thank you for your help on this!

Please ignore the overlaid text and controls.

![Screen Shot 2020-07-30 at 1 41 56 PM](https://user-images.githubusercontent.com/3950855/88956827-f0b5c780-d26b-11ea-892e-604300aa8759.jpg)

**Comment by vgrafe** [comment]
This seems to be serious... am I really the only one who's experienced this?

**Comment by gkatsev** [comment]
Unfortunately, these types of issues are often very device dependent. Often, turning off hardware acceleration in chrome settings fixes it.

**Comment by vgrafe** [comment]
Good to know. Thank you!
