### ISSUE TITLE
Feature request: A setting to turn off artifical clicks?

### ISSUE THREAD

**Issue by dryoma** [videojs/video.js#6781]
## Description
And are having the same issue that has already been reported here (like #6613): video.js' implementation of clicks conflicts with a 3rd party solution that does that as well. As a result, clicks on the toolbar of a video get triggered twice and thus don't work for a user.

We're using https://github.com/pukhalski/tap/ as our mobile clicks solution. It's lightweight and otherwise bulletproof, we really like it and wouldn't want to drop it.

### Possible solution

What I'd like to propose is a setting that would turn off video.js' artificial click functionality and would be usable in solutions like Brightcove which we're using as our video hosting. Assuming it would be opt-out (i.e., to turn video.js' implementation a user would have to enable the feature.), and developers know what they're doing, this could remove conflicts with any other lib that is doing their click implementation.

## Steps to reproduce

Any video with the default configuration would have this bug. Here is a Fiddle I've put together:https://jsfiddle.net/s8zn1ray/1/ The code of `pukhalski/tap` has just been copied into the JS area.

### Actual
Clicks on the Play/Pause, Mute buttons trigger twice, thus nullifying the effect. The Full screen button seems to work, as well as pausing and resuming when the main player area is clicked.

### Error output
No errors in the console.

**Comment by gkatsev** [comment]
I'm not sure that there's a way to do this without completely reworking the way that click and touch behavior works in video.js and if we're already doing that we can likely make sure that it doesn't conflict with things like fastclick and tap. Unfortunately, we don't have the bandwidth to look into this in the short term.

**Comment by dryoma** [comment]
@gkatsev I see, that's unfortunate. Still, if you're planning to add this feature or the no-conflict behavior to your long-term roadmap, could you please track that in this issue? So we could get notified when it gets implemented, however far in the future.
