### ISSUE TITLE
Cache entire video (frame accurate seek)

### ISSUE THREAD

**Issue by chazhenry** [videojs/video.js#6782]
### Slow to seek
I'm making a telestrator video player that allows instant seek to any frame of the video. Videos are limited to 30 seconds max. I want to load the entire video and turn off the spinner when you stab the timeline and jump to an exact frame. I have buttons that advance one frame (0.0166 secs). They work if clicked slowly, but not in rapid succession. Has my video been unloaded? Seems if it can play at 60 fps, it could keep up with my clicks. Thanks.

**Comment by gkatsev** [comment]
Is it an mp4 file or HLS/DASH? Unfortunately, seeking in browsers is unreliable and it's possible that the issue is occurring because a new seek has happened before the previous seek has completed.
