### ISSUE TITLE
Errors and warnings for deprecated code in videojs-ie8.min.js

### ISSUE THREAD

**Issue by yoshie902a** [videojs/video.js#6784]
## Description
Depreciation warnings when the ie8 link is added from tutorial. I would like old browsers like ie8 supported.

## Steps to reproduceld
```
<!DOCTYPE html>
<html>
<head> <link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />
  <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

</head>

<body>
  <div id='vi' style="height: 100px;">
  <video
    id="my-video"
    class="video-js vjs-fill vjs-16-9 vjs-big-play-centered"
    controls
    preload="auto"

    poster="eposter.png"
    data-setup="{}"
  >
    <source src="https://videodelivery.net/secret-video-id/manifest/video.mpd" type="application/dash+xml" />
    <source src="https://videodelivery.net/secret-video-id/manifest/video.m3u8" type="application/x-mpegURL" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a
      >
    </p>
  </video>
  </div>

  <script src="https://vjs.zencdn.net/7.8.4/video.js"></script>

<!-- https://www.iana.org/assignments/media-types/media-types.xhtml#video -->

<script>
  
  var myPlayer = videojs('my-video');
  
  myPlayer.ready(function(){
    var myPlayer = this;

    // EXAMPLE: Start playing the video.
    myPlayer.play();

  });
  
  </script>
  </body>
</html>
```

### Expected
I expect no errors when the ie8 link is added

### Actual
Video plays with no issue, but do not know why given the error given the ie8 code should only be run for ie8.

### Error output

Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. videojs-ie8.min.js:1:9637
onmozfullscreenchange is deprecated. videojs-ie8.min.js:1:9637
onmozfullscreenerror is deprecated.

when play button is pressed we get..
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.4

#### browsers
what browser are affected?
Firefox for Mac 79
#### OSes
OS X 10.13.6
are any videojs plugins being used on the page? If so, please list them below.
videojs-ie8.min.js

**Comment by gkatsev** [comment]
Video.js 7 doesn't support IE8.
If you must support IE8 you'll need to use Video.js 6.x.
