### ISSUE TITLE
The Playbutton on the starting interface is wider than its size.

### ISSUE THREAD

**Issue by AdityaTeltia** [videojs/video.js#6785]
## Description
![PlayButtom](https://user-images.githubusercontent.com/67232537/89284190-03fdd400-d66c-11ea-9814-1b6c0aef8d88.PNG)
The play-button when we switch to city theme is wider which makes UI weird and UX not good.

### Expected
The play-button to be the size of icon play

### Actual
Wide Play button

**Comment by mmcc** [comment]
Hi there! The play button being centered is intentional in the design. You can [override the styles](https://github.com/videojs/themes/blob/master/city/index.css#L50-L54) if you'd like and set the `flex` value to something smaller.
