### ISSUE TITLE
How to detect if the user changed player time?

### ISSUE THREAD

**Issue by laloix** [videojs/video.js#6786]
## Description

Is there a way to detect when the player change the video time by clicking on the progression bar?

I know there is `player.on(timeupdate, ...)` but it triggers for every... time update, and I just want a callback for manual time change.

I am looking for a way to call a function when the user interact with the progression bar.

**Comment by deveshmishra34** [comment]
You can use seeking method to detect that.
https://docs.videojs.com/docs/api/player.html#Methodsseeking

For Example: 


`
this.player.on('play', () => {
      const seeking = this.player.seeking(); // return true|false

      if (seeking) {
        // video time changes by clicking on the progression bar
      } else {
       // other code
      }
    });
`
