### ISSUE TITLE
移动端h5 在beforeRequest 里设置属性不生效

### ISSUE THREAD

**Issue by haobingG** [videojs/video.js#6788]
pc端属性都生效 但移动端不生效，代码如下
videojs.Hls.xhr.beforeRequest = function(options) {
              if(!options.headers) options.headers = {}
              options.headers.Authorization = Authorization
              options.uri = options.uri + '?Authorization=' + Authorization
              return options;
            };
这两种设置在pc端浏览器都生效 在html5 移动端 不生效

**Comment by gkatsev** [comment]
Which browser are you trying this on? `beforeRequest` is a feature of our playback engine which doesn't run on iOS devices and for android devices you must make sure you set `overrideNative`.

**Comment by haobingG** [comment]
> Which browser are you trying this on? `beforeRequest` is a feature of our playback engine which doesn't run on iOS devices and for android devices you must make sure you set `overrideNative`.

IOS

**Comment by gkatsev** [comment]
Unfortunately, that isn't going to work. For iOS you could try passing this information in a query parameter of the media but you can't modify the headers for the media requests.
