### ISSUE TITLE
On Chrome browser in Android, videojs liveui is enabled but seeking is not possible but works on desktop

### ISSUE THREAD

**Issue by venkat0708** [videojs/video.js#6789]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Seek to any position while live is going on

### Actual
seeking is not possible in liveui

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
7.8.4
#### videojs
what version of videojs does this occur with?
#### browsers
Chrome
what browser are affected?
#### OSes
Andriod
what platforms (operating systems and devices) are affected?
### plugins

are any videojs plugins being used on the page? If so, please list them below.

hls plugin

```
<script src="https://vjs.zencdn.net/7.8.4/video.js"></script>
--
  | <script src="https://unpkg.com/videojs-contrib-hls.js"></script>
  |  
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-overlay/1.1.4/videojs-overlay.min.js"></script>


(function(window, videojs) {
--
  | var player = window.player = videojs('player',
  | {
  | html5: {
  | hls: {
  | overrideNative: !videojs.browser.IS_ANY_SAFARI
  | },
  | nativeAudioTracks: false,
  | nativeVideoTracks: false
  | },
  | liveui: true
  | });
  | overlay_content = '<div class="myOverlay"><h2>Live</h2></div>';
  | player.overlay({
  | overlays: [{
  | start: 'loadstart',
  | content: overlay_content,
  | end: 'playing',
  | align: 'top-left',
  | showBackground: false
  | }, {
  | start: 'pause',
  | content: overlay_content,
  | end: 'playing',
  | align: 'top-left',
  | showBackground: false
  | }]
  | });
  | }(window, window.videojs));

```

**Comment by gkatsev** [comment]
One thing to note is that you're including contrib-hls. That's a very old version of our playback engine which is now also included by default in Video.js. I would recommend removing that script and trying again. We've successfully seeked using liveui and latest Video.js.
