### ISSUE TITLE
videojs7 and videojs6 error for ios safari

### ISSUE THREAD

**Issue by tmkmk** [videojs/video.js#6790]
## Description
videojs7 and videojs6 error for ios safari UA Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

code:
window.onload = function () {
  var pl = videojs("video", {}, function (params) {
    this.on("loadedmetadata", function (params) {
      console.log(this.tech_.hls.playlists.media_.segments);
    });
    pl.src({
      src: inputUrl.value,
      type: "application/x-mpegURL"
    });
  });
}

video.js version 7.9.2
console:
VIDEOJS:
(anonymous)	@	video.js:85
dispatcher	@	video.js:1915
trigger	@	video.js:2049
(anonymous)	@	[native code]:1
bound	@	[native code]:1
dispatcher	@	video.js:1913

**Comment by gkatsev** [comment]
The `.hls` property is set by our playback engine and is only available when our engine is being used. On iPhones, it is not possible to use our playback engine and thus that property won't be available.
Unfortunately, there's only so much information you can glean from what is provided on iOS.
