### ISSUE TITLE
Some m3u8 videos have gaps when playing with video.js

### ISSUE THREAD

**Issue by Vsevo1od** [videojs/video.js#6792]
## Description
When I play https://dev.valt.fora-soft.com/uploads/videojsGapsRepro/chunklist_w955096496.m3u8 directly using any desktop player (VLC, PotPlayer) everything is fine. 
But in the video.js player, there are gaps.
<img width="733" alt="Annotation 2020-08-06 124729" src="https://user-images.githubusercontent.com/5249361/89532462-7f8d8b80-d7fa-11ea-876d-09f6cd0a9984.png">

 The player starts loading animation and the picture is frozen when on these gaps. After a second it continues to play.
If you click on these gaps to seek there the player will hang, there will be the loading animation and a picture will be frozen and there will be no sound.

[Codepen](https://codepen.io/vsevo1od-the-vuer/pen/abNzbBM)

## Steps to reproduce
1. Open [this codepen](https://codepen.io/vsevo1od-the-vuer/pen/abNzbBM)
2. Start playing the video
3. Skip to 00:19

### Expected
Video continues to play smoothly, as in VLC, PotPlayer

### Actual
Video is frozen, there is a visible vjs-loading-spinner

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
the latest one, 7.8.4
#### browsers
tested in the latest Chrome and the latest Firefox
#### OSes
I tested only on Windows 10
### plugins
No plugins

**Comment by gkatsev** [comment]
I can see a gap in audio buffer via https://videojs-http-streaming.netlify.app/utils/stats. Because the gap is relatively small we can skip it easily but I guess it ends up being long enough that the spinner still shows up.
Desktop players can do a much better job at making these types of gaps invisible.
