### ISSUE TITLE
Player not adapting to size of container when shrinking

### ISSUE THREAD

**Issue by Wuschba** [videojs/video.js#6793]
## Description
The player chooses the right version/resolution of the video initially, but when shrinking the container while it's playing, the played resolution stays the same.

## Steps to reproduce
I'm splitting a video with ffmpeg:
```
ffmpeg -i "source.mov"
 -i "watermark.png"
 -y
 -keyint_min 100 -g 100
 -sc_threshold 0
 -c:v libx264
 -filter_complex "[0][1:v]overlay=24:960,format=yuv420p, split=5[outTxt0][outTxt1][outTxt2][outTxt3][outTxt4],[outTxt0]drawtext=text='320x180':x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.5:boxborderw=5:fontcolor=white:fontsize=96:fontfile='C\:/Windows/Fonts/arial.ttf'[out0],[outTxt1]drawtext=text='640x360':x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.5:boxborderw=5:fontcolor=white:fontsize=96:fontfile='C\:/Windows/Fonts/arial.ttf'[out1],[outTxt2]drawtext=text='960x540':x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.5:boxborderw=5:fontcolor=white:fontsize=96:fontfile='C\:/Windows/Fonts/arial.ttf'[out2],[outTxt3]drawtext=text='1280x720':x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.5:boxborderw=5:fontcolor=white:fontsize=96:fontfile='C\:/Windows/Fonts/arial.ttf'[out3],[outTxt4]drawtext=text='1920x1080':x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.5:boxborderw=5:fontcolor=white:fontsize=96:fontfile='C\:/Windows/Fonts/arial.ttf'[out4]"
 -map [out0] -s:0 320x180 -b:v:0 2048k -maxrate:0 2048k -bufsize:0 1024k
 -map [out1] -s:1 640x360 -b:v:1 4096k -maxrate:1 4096k -bufsize:1 2048k
 -map [out2] -s:2 960x540 -b:v:2 5461.3333333333k -maxrate:2 5461.3333333333k -bufsize:2 2730.6666666667k
 -map [out3] -s:3 1280x720 -b:v:3 8192k -maxrate:3 8192k -bufsize:3 4096k
 -map [out4] -s:4 1920x1080 -b:v:4 32768k -maxrate:4 32768k -bufsize:4 16384k
 -init_seg_name "output_$RepresentationID$.$ext$"
 -media_seg_name "output_$RepresentationID$-$Number%05d$.$ext$"
 -use_template 1 -use_timeline 1
 -seg_duration 4 -adaptation_sets "id=0,streams=v"
 -f dash "output.mpd"
```
I'm using the video.js player like this on a machine with high bandwidth (local webserver):
video class="video-js vjs-fluid" controls id="myvideo" poster="myposter.png">
	<source src="output.mpd" type="application/dash+xml">
	<source src="output.mp4" type="video/mp4">			
</video>	

### Expected
Starting with a container sized 800x450, video.js picks (correctly) the video 960x540 and plays it. When shrinking the container in which the video is played, video.js should pick the appropriate video with the appropriate resolution. So when shrinking the browser so that the container is sized 200x112, video.js should switch to play the video with the resolution 320x180.

Same with fullscreen: Switching from container sized 800x450 to fullscreen, video.js switches to play the video 1920x1080. Going back from fullscreen to container sized 800x450, video.js should go back to 960x540.

### Actual
Instead of switching to the video with the resolution 320x180, video.js keeps playing the video 960x540, even when a new video-chunk is loaded.

Instead of switching back from 1920x1080 to 960x540 when coming back from fullscreen, video.js keeps playing the 1920x1080 video, even when a new video-chunk is loaded.

### Error output
None. The event playerresize is triggered but there is no adaption of the video to the new player-size.

#### videojs
video.js 7.9.2
#### browsers
Chrome 84.0.4147.105 (latest version), FF 79.0 (latest version)
#### OSes
tested on windows 10 64bit
### plugins
none, just including video.js

**Comment by gkatsev** [comment]
How is the player being resized? Also, we do end up downswitching but we don't do it immediately like with fullscreen. As playback continues at the smaller size we should switch down based on the player resolution when downloading new content (likely 30+ seconds from the current time position).
