### ISSUE TITLE
Videojs is falsely showing "LIVE" instead of a progress bar

### ISSUE THREAD

**Issue by ctrl-shift-glitch** [videojs/video.js#6794]
## Description
Videojs is falsely showing "LIVE" in the beginning when trying to play a .mp4 video. However, it looks like after a few seconds the LIVE disappears and I see the progress bar. But I only want to see the progress bar. How can I remove the "LIVE" from the beginning? Thanks.

Please have a look at the screen recording to better understand this issue: 
https://drive.google.com/file/d/1kXbee5cD897eN_0XXuiaOlhZ1UpxDR50/view?usp=sharing

### Expected
Please describe what you expected to see.
I expected the progress to show as soon as the video starts
![image](https://user-images.githubusercontent.com/60304029/89580057-a98a8200-d7e9-11ea-8ac5-ef1298a072dd.png)

### Actual
Please describe what actually happened.
I am seeing "LIVE" written instead of a progress bar. 
![image](https://user-images.githubusercontent.com/60304029/89579844-50bae980-d7e9-11ea-8f11-7d4159dd4f09.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?

#### browsers
what browser are affected?
All browsers

#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
My guess is that we aren't getting a duration from the video until more of it has loaded, it's likely returning a duration of Infinity or -1 during this transition period. Generally, this means that the mp4 metadata inside the file isn't at the head of the file. Retrascoding for web often fixes similar issues.
We can help more if you're able to provide a sample video.

**Comment by ctrl-shift-glitch** [comment]
Hi @gkatsev, thank you for your reply. Below is the link to video which I recorded using the videojs-record": "^3.11.0" (https://github.com/collab-project/videojs-record/releases/tag/3.11.0)

**Video:** https://drive.google.com/file/d/1YlSAJQTY7i_3qyHGDGff5hLecl-G4EXM/view?usp=sharing

**Comment by gkatsev** [comment]
ffprobe is telling me that the file is actually an mkv/webm and that it has no duration set. Both of those would explain the weird behaviors.
```
Input #0, matroska,webm, from 'wmzzAILfPfBtggqFS24P (4).mp4':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
```
