### ISSUE TITLE
Multiple webcameras with multiple video tags not working

### ISSUE THREAD

**Issue by ubul86** [videojs/video.js#6795]
## Description

I use this example: https://github.com/collab-project/videojs-record/blob/master/examples/change-video-input.html and I want to use multiple webcams (like notebook integrated and usb webcam) in multiple "video" tags at once.

I don't know it's possible, but I can't change the video: {                   
                    soruceId: src
                },
option, every video tag opens the first camera that founds in device list.

I try to get all devices that connects:

```
(async () => {
        await navigator.mediaDevices.getUserMedia({audio: false, video: true});
        let devices = await navigator.mediaDevices.enumerateDevices();
        devices = devices.filter(device => device.kind === 'videoinput')
        createPlayer(devices);
    })();
```

in the createPlayers function:

```
let j=1,deviceInfo;
for (i = 0; i !== devices.length; ++i) {
        deviceInfo = devices[i];
        createPlayer("video_" + j, deviceInfo.deviceId)
        j = j + 1;
```
in the createPlayer fnc:

```
function createPlayer(id, src) {        
    let player = videojs(id, {
        controls: true,
        fluid: true,
        controlBar: {
            volumePanel: false,
        },
        plugins: {
            record: {
                audio: false,                
                video: {                   
                    soruceId: src
                },
                videoMimeType: 'video/mp4',
                maxLength: 10,
                convertEngine: 'ts-ebml',
                debug: true,
                frameWidth: 320,
                frameHeight: 240,

            }
        }
    }, function () {        
    });


    player.on('deviceReady', function () {       
        player.record().enumerateDevices();
    });

    player.on('ready', function () {
        player.record().getDevice();
    });

    player.on('enumerateReady', function () {        
        devices = player.record().devices;
    });

    // error handling
    player.on('enumerateError', function () {
        console.log('enumerate error:', player.enumerateErrorCode);
    });

    // error handling
    player.on('deviceError', function () {
        console.warn('device error:', player.deviceErrorCode);
    });

    player.on('error', function (element, error) {
        console.error(error);
    });

    // user clicked the record button and started recording
    player.on('startRecord', function () {
        console.log('started recording!');
        recordedFramerate = deviceFrameRate;
    });

    // user completed recording and stream is available
    player.on('finishRecord', function () {
        console.log('finished recording: ', player.recordedData);
    });

    player.on('finishConvert', function () {
        // the convertedData object contains the converted data that
        // can be downloaded by the user, stored on server etc.
        console.log('finished converting: ', player.convertedData);
        readAsBuffer(player.convertedData).then(function (videoTypedArray) {
            recordedVideo = videoTypedArray;
        });
    });
}
```

in html:

```
 <div class="row">
        <div class="col-xs-6">
            <video id="video_1"
              class="video-js vjs-default-skin"></video>
        </div>
        <div class="col-xs-6">
      
            <video id="video_2"
              class="video-js vjs-default-skin"></video>
            </div>
        </div>
```

but i can get the first camera in each video tag when all the webcams are ready. How can I create multiple players and give different video source (like webcams) if it perhaps?

If I use navigator.mediaDevices, it's ok:

```
var deviceInfo,i, j = 1;
    for (i = 0; i !== devices.length; ++i) {
        deviceInfo = devices[i];
        let stream = await navigator.mediaDevices.getUserMedia({
            audio: false,
            video: {
                deviceId: {exact: deviceInfo.deviceId},
                width: {'min': 640},
                height: {'min': 480}
            },
        });
        const videoElement = document.getElementById("video_" + j);
        videoElement.srcObject = stream;   
        j=j+1;     

    }
```

**Comment by MetSystem** [comment]
The same problem

**Comment by ubul86** [comment]
> The same problem

I can create multiple videos with html video tag with this code:

package json deps..:
`
    "video.js": "^7.8.4",
    "videojs-record": "^4.1.0",
    "webrtc-adapter": "^7.7.0"
`
`
(async () => {
        await navigator.mediaDevices.getUserMedia({audio: false, video: true});
        let devices = await navigator.mediaDevices.enumerateDevices();
        devices = devices.filter(device => device.kind === 'videoinput')
        createStreams(devices);
    })();
`
createStream function:

`
devices.forEach(async function (deviceInfo, id) {

        var player = videojs('myVideo_' + id, options, function () {
            // print version information at startup
            var msg = 'Using video.js ' + videojs.VERSION +
                    ' with videojs-record ' + videojs.getPluginVersion('record') +
                    ' and recordrtc ' + RecordRTC.version;
            videojs.log(msg);            
        });

       player.on('deviceReady', function () {
            console.log('ready');
            player.record().enumerateDevices();
        });

        player.on('ready', function () {

            player.record().getDevice();
            player.record().setVideoInput(deviceInfo.deviceId)
            player.record().loadOptions(options);
        });


        player.on('enumerateReady', function () {

        });

        // error handling
        player.on('enumerateError', function () {
            console.warn('enumerate error:', player.enumerateErrorCode);
        });

        player.on('deviceError', function () {
            console.warn('device error:', player.deviceErrorCode);
        });

        player.on('error', function (element, error) {
            console.error(error);
        });

// user clicked the record button and started recording
        player.on('startRecord', function () {
            console.log('started recording!');
        });

// user completed recording and stream is available
        player.on('finishRecord', function () {
            // the blob object contains the recorded data that
            // can be downloaded by the user, stored on server etc.
            myConsole.log('finished recording: ', player.recordedData);
            stopRecord();
        });

        player.on('finishConvert', function () {
            readAsBuffer(player.convertedData).then(function (videoTypedArray) {
                recordedVideo = videoTypedArray;
                recordedVideos.push(recordedVideo);
                videos.forEach(function (videoJson, index) {
                    if (index == id) {
                        myConsole.log(recordedVideo);                       
                    }
                })
            });
        })
        players.push(player);

}
`
my options variable:
`
var options = {

    fluid: true,

    bigPlayButton: false,
    controlBar: {
        volumePanel: false
    },
    plugins: {
        record: {
            audio: false,
            video: {
                videoMimeType: 'video/x-matroska;codecs=avc1',
                videoRecorderType: 'WhammyRecorder',
                videoBitRate: 2000,
                width: 1280,
                height: 768,
                frameRate: 60,
            },
            maxLength: "7200",
            convertEngine: 'ts-ebml',
            debug: true,
            videoMimeType: 'video/x-matroska;codecs=avc1',
            videoRecorderType: 'WhammyRecorder',
            videoBitRate: 2000,           
            frameRate: 60,
        }
    }
};
`
