### ISSUE TITLE
Player keeps fetching data from old source

### ISSUE THREAD

**Issue by BasharAbuJoub** [videojs/video.js#6796]
## Description
I have a videojs player next to videojs-flvjs package installed.
The application have multiple channels which allows the user to switch between them and change the player source.
I have noticed a weird behavior that happens **intermittently** where the player keeps fetching from old source when switching 
between channels. I tried to reset the player before changing the source to ensure that the old source is destroyed but that didn't help. Also I have checked the player source using (DevTools console) and it was valid (pointing to the new source). but that was not the case in the DevTools network tab, the player was fetching the data from the old source. 

#### videojs
Video.js 7.7.5
#### browsers
Edge, Chrome
### plugins
mister-ben/videojs-flvjs

**Comment by gkatsev** [comment]
Are you playing back an flv file?

**Comment by BasharAbuJoub** [comment]
@gkatsev Live streaming an flv.

**Comment by gkatsev** [comment]
My guess is that flvjs somehow continues to update the flv even though videojs-flvjs does detach the video on a new source https://github.com/mister-ben/videojs-flvjs/blob/master/src/plugin.js#L41-L45
Can you reproduce your issue via http://bilibili.github.io/flv.js/demo/?

**Comment by BasharAbuJoub** [comment]
The issue is related to flv.js.
