### ISSUE TITLE
关于安卓微信浏览器打开视频播放

### ISSUE THREAD

**Issue by gitkuyxy6104** [videojs/video.js#6798]
使用video.js  添加视频播放倍速功能.在pc端是正常的,在移动端浏览器也是正常的,但是在安卓下的,微信浏览器打开,无功能,

**Comment by gkatsev** [comment]
playback rate is a browser dependent feature. Not all mobile browsers let you adjust the playback rate.

**Comment by gitkuyxy6104** [comment]
现在video.js在某些安卓手机上的微信不兼容某些功能，例如播放速率
