### ISSUE TITLE
Get original error that caused videojs error

### ISSUE THREAD

**Issue by andrinja** [videojs/video.js#6799]
## Description
In my application that uses videojs to play media, I am consuming an API that will throw a specific error when the same user tries to play media from two different devices at the same time. 

## Steps to reproduce
I load pass the url into the video source as follows:
```javascript
player.src({
    src: url,
    type: 'audio/mp4',
});
```
and then I listen to an error event as follows:
```
player.on('error', event => console.log(event.target.error)
```

### Expected
I expect to get the part of the error that contains the error code thrown by the API i.e. the part that contains error code "429" in the screenshot below.

<img width="244" alt="oBt7Q" src="https://user-images.githubusercontent.com/25619536/89942151-57e45c00-dc1c-11ea-9745-72d23c3c415f.png">

### Actual
I get the internal error code, namely, "4" of videojs. 

### Final thoughts
I've tried a lot of StackOverflow e.g. https://stackoverflow.com/questions/61878817/catching-invalid-source-error-using-videojs, but it has not yielded any usable results for me. I am convinced there surely must be a way to access the error object that caused the videojs error that I get.

**Comment by gkatsev** [comment]
Unfortunately, I'm not sure it's possible. mp4s are handled by the browser and we provide the error we are given via `player.error()`. It's possible that player.error().message may contain more info, but it's unlikely. The media elements only provide these errors https://developer.mozilla.org/en-US/docs/Web/API/MediaError.
For HLS/DASH, it could be possible get more granular errors but that would only be for platforms that native playback isn't being used (and we don't currently surface those, but nothing is necessarily stopping us from doing so).
