### ISSUE TITLE
IOS ERRORVIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) crashes whole player 

### ISSUE THREAD

**Issue by damjan25** [videojs/video.js#6800]
**Device**: Mobile IOS
**Browser**: Chrome (also on safari)
"**@types/video.js": "^7.2.16**" (tried with 7.3.10 and it didnt work)
"**videojs-ima": "^1.7.2**" (tried with 1.8.1 and it didnt work)

I am using videojs with ima sdk plugin.
How can I set listener for MEDIA_ERR_SRC_NOT_SUPPORTED error ? So I can then at least close the whole player, because right now it just shows the black screen and mentioned error and the close button doesnt work.
I tried with this, but it does not work.
`player.on('MEDIA_ERR_SRC_NOT_SUPPORTED', function () {}); `

I also tried with player.on('error',...) but it was not triggered and I couldnt close the player

Is it possible to handle to catch this error and close player somehow ?

**Comment by gkatsev** [comment]
First of, no need to ping older issues when this one has been opened recently.
You can listen to the error event and then you can get the error from the player. For example:
```js
player.on('error', function() {
  const err = player.error();
  // code 4 is MEDIA_ERR_SRC_NOT_SUPPORTED https://developer.mozilla.org/en-US/docs/Web/API/MediaError
  if (err.code === 4) {
    player.dispose() // not sure what you mean by close the player, feel free to do what you want here instead
  }
});
```

**Comment by damjan25** [comment]
- Sorry for pinging in other issues, I just wanted to ask devs if they maybe found some solution for this error(sometimes people find solution and don't post it in issue).
- I tried with this again (listen to error event) but for some reason it does not catch the error. It is not disposing the player and I tried to console.log custom msg on error and it didn't get logged. 
But I can see still in console this error :
`ERRORVIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. [object Object]`

- I saw you posted in other ticket that it could be problem with HTTP, so now we will try to deliver all videos over HTTPS, and I will get back to you if this solves the problem and then close this issue

Thank you for help I really appreciate it :)

**Comment by damjan25** [comment]
@gkatsev  looks like this happens, when there are 2 instances of videojs with ima sdk plugin on same page.
But it is really weird that it happens only on IOS

**Comment by gkatsev** [comment]
Ah, during ads, errors may be available via the `aderror` event because contrib-ads retriggers events during ads (for reasons http://videojs.github.io/videojs-contrib-ads/integrator/redispatch.html). There's also `contenterror`, so, you may want to do `player.on(['error', 'aderror', 'contenterror'], ...`.

**Comment by damjan25** [comment]
That did not work unfortunately either. I am still getting a blank after ad was played :(

**Comment by edudiego** [comment]
I'm having the same issue as @damjan25 now, can we re-open this?
