### ISSUE TITLE
Can't disable Picture In Picture

### ISSUE THREAD

**Issue by Artem-Schander** [videojs/video.js#6801]
## Description
The title says it all. I'm trying for a few hours now without success.
Here is a sandbox: https://codesandbox.io/s/loving-thompson-z3u3d?file=/index.html

## Steps to reproduce
1. Open the sandbox
2. look for the different methods i tried
3. ???
4. Profit!!!

### Expected
The Picture In Picture toggle should be gone

### Actual
It is still in the control panel

### Error output
If I try to get it done with the documented method `video.disablePictureInPicture(true)`
I get `(index):44 Uncaught TypeError: video.disablePictureInPicture is not a function`

**Comment by gkatsev** [comment]
The issue is that you're initializing using both `data-setup` and programmatically. You need to make sure to only use one initialization method. Here's a working sample: https://codesandbox.io/s/quizzical-proskuriakova-yddry?file=/index.html

Also, the method isn't available in Video.js 7.8, it was added in Video.js 7.9 (which we should probably promote to latest)

**Comment by yzfedora** [comment]
If you want to hide the picture in picture button, set up the `pictureInPictureToggle` to `false`.

```
      var player = videojs('vjs-player', {
          preload: true,
          autoplay: true,
          controls: true,
          controlBar: {
              'liveDisplay': true,
              'pictureInPictureToggle': false
          }
      });
```

**Comment by Artem-Schander** [comment]
Thanks for the quick response.

**Comment by yoxud** [comment]
For me ,  
`videojs.options.disablePictureInPicture = true; `
disables the pip action but the icon still shows up on mousemove, even after using 
`controlBar: {
              'liveDisplay': true,
              'pictureInPictureToggle': false
          }`
Anybidy know how to get rid of the icon?

**Comment by RuslanMelnykFE** [comment]
Not working for Firefox

**Comment by dioramayuanito** [comment]
Firefox disablePictureInPicture thread https://bugzilla.mozilla.org/show_bug.cgi?id=1611831
