### ISSUE TITLE
HLS audio streaming stops on Android in google chrome after 5 minutes in background (videojs 7.8.4)) 

### ISSUE THREAD

**Issue by agursoy** [videojs/video.js#6804]
Hi, we are using latest video.js version(7.8.4) to play hls audio. Everything is look like okay in browsers but in android chrome; audio stops after exactly 5 minutes. 

I think is strongly related with this issue: https://github.com/videojs/video.js/issues/5904

We also implement Media Session Api to our app. It means to stoping play is not important when user lock screen. User can see play button when screen locked but main problem is audio is stopping after 5 minutes.

**Comment by gkatsev** [comment]
Is `overrideNative` being used to use our playback engine? Have a sample page?

**Comment by nickrobillard** [comment]
I would like to add - I am observing the exact same behavior with an AAC audio only HLS stream. The audio stops playing exactly 5 minutes after locking my screen.

**OS**: Android 10 (Samsung variant)
**Browser**: Chrome 88.0.4324.152
**Video.js version**: 7.7.5
**HLS details**: Audio only AAC 256k continuous live stream produced using nginx-rtmp. (Even though it is audio only, .ts extension is still used)

Observe the pause event after 304 seconds of play time and the `MediaSource` error. After the error occurs, the playback is broken and `currentTime` never progresses.

Log:
```
log: audio currentTime: 260.677143
log: audio liveCurrentTime: Infinity
log: audio currentTime: 275.687726
log: audio liveCurrentTime: Infinity
log: audio currentTime: 290.671264
log: audio liveCurrentTime: Infinity
log: audioPlayer pause
log: audio currentTime: 304.554223
log: audio liveCurrentTime: Infinity
error: VIDEOJS: ERROR: {"stack":"Error: Failed to set the 'duration' property on 'MediaSource': The 'updating' attribute is true on one or more of this MediaSource's SourceBuffers.\n at Yu.value (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:28:82768)\n at i (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:28:143182)\n at Vo.<anonymous> (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:28:143340)\n at Vo.o.dispatcher.o.dispatcher (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:12:10881)\n at pe (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:12:11670)\n at Vo.ye.dispatchEvent.ye.trigger (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:12:13265)\n at Vo.value (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:28:3520)\n at https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:28:7620\n at Object.callback (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:28:10484)\n at s (https://cdn.jsdelivr.net/npm/video.js@7.7.5/dist/video.min.js:19:575)"}
log: audio currentTime: 304.554223
log: audio liveCurrentTime: Infinity
log: audio currentTime: 304.554223
log: audio liveCurrentTime: Infinity
log: audio currentTime: 304.554223
log: audio liveCurrentTime: Infinity
log: audio currentTime: 304.554223
```

This seems to be related to this Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=415344 which is related to power saving mechanisms that stop JS timers after a certain period of time. Although it is marked as "Won't Fix", it appears to have been resolved. More importantly, I am _not_ observing the same problem using the Hls.js demo page (https://hls-js.netlify.app/demo/) with the identical source m3u8. In my numerous tests there, I have gone well over 15 minutes  of locked screen time with no interruptions.

I have tried using `html5.hls.overrideNative: true` and without it - but it doesn't affect this problem.
