### ISSUE TITLE
VideoJS doesnt play a m3u8 playlist

### ISSUE THREAD

**Issue by MichaelSalp** [videojs/video.js#6805]
## Description
I would like to play a m3u8 playlist which was generated by AWS MediaConvert. 

## Steps to reproduce
Take a look @  https://jsfiddle.net/sjzhg3ap/ 
(INFO: jsfiddle doesnt work because of mixed active contents, but the HLS problem also appears on my dev server...)

### Expected
Video plays

### Actual
Video doesnt play

### Error output
"VIDEOJS:", "WARN:", "Problem encountered with the current HLS playlist. Trying again since it is the only playlist."
"VIDEOJS:", "WARN:", "Problem encountered with the current HLS playlist. Trying again since it is the only playlist."

Additional Firefox says:
Das angegebene "type"-Attribut "application/x-mpegURL" wird nicht unterstützt. Das Laden der Medienressource https://drm-test-2020-storage-2020.s3-eu-west-1.amazonaws.com/output/8062bcff562132a857cf154b6e014e108cbd677f2211.mp4.m3u8 ist fehlgeschlagen.

## Additional Information
The Video plays without  ()! problems in mediaelementsjs and theoplayer, so I m pretty sure the AWS MediaConvert generated m3u8 is okay

The License Server runs local... If you need a online version for helping with my problem, please tell me :-)

#### videojs
7.8.3
#### browsers
Firefox 7.8.3
Chrome, Edge
#### OSes
Windows 

Thanks for your help! :-) If you need more information, please ask

**Comment by MichaelSalp** [comment]
It looks like if the HLS Key seems to be a Problem... After I added a second video, the error message shows more details... i will investigate

**Comment by JoaoCEAlmeida** [comment]
I'm having this problem with m3u8 links also, when I have DRM enable...
![image](https://user-images.githubusercontent.com/9196047/92763671-b0c62200-f38b-11ea-9f28-7156f1aa2775.png)

I think it could be related with you  @MichaelSalp ...

Did you found any solution?

Thanks in advance.

**Comment by MichaelSalp** [comment]
Problem solved for me:
Wordpress returned 17Bytes instead of 16Bytes for the Key. Sadly other players can handle the extra byte at the end and work smoothly, so it was very hard work to find the problem for me...

So if you have the same problem: Check the http request and the return length of the key
