### ISSUE TITLE
H.265 for Video.js

### ISSUE THREAD

**Issue by coffe1891** [videojs/video.js#6811]
Hi, I have made a plugin for Video.js, 
it make Video.js has the ability to play flv + live/local video encoded with h264/h265.

[videojs-flvh265](https://github.com/coffe1891/videojs-flvh265)

best wishes.

**Comment by gkatsev** [comment]
🎉 That's pretty cool! Thanks for posting about it.

Going to close this but hopefully someone may find it helpful.
