### ISSUE TITLE
Event Playlist jumps to end of received playlist.

### ISSUE THREAD

**Issue by sethurv** [videojs/video.js#6815]
## Description
When an Event Playlist received in chunks, play position jumps to end of the received playlist.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Send Event Playlist as chunks, say `#EXT-X-MEDIA-SEQUENCE:` as 0, 50, 100 etc. with corresponding content.

### Expected
VideoJS plays the end of first chunk, second chunk and so on.

### Actual
Play should be smooth.

### Error output
No error reported in console

#### videojs
7.8.4
#### browsers
Chrome, FireFox
#### OSes
All
### plugins
NA

**Comment by gkatsev** [comment]
Unfortunately, when an end list tag isn't present, our playback engine starts from the end of the playlist.

**Comment by sethurv** [comment]
Yes for a live stream this can be expected, not necessarily for a Event stream and when the event stream is populated, this looks completely awkward.

I doubt there will be a setting to configure this. Is there a possibility to handle it in upcoming release?

**Comment by sethurv** [comment]
Does this is considered as an issue or not?
