### ISSUE TITLE
An error is not propagated to a player instance

### ISSUE THREAD

**Issue by bmind12** [videojs/video.js#6816]
## Description
There is sometimes a problem occur, and a `MEDIA_ERR_NETWORK HLS playlist request error {code: 2, status: 403}` is  logged in a console but not propagated to a `videojs` player instance, but in most of the cases  for the same scenario the `MEDIA_ERR_SRC_NOT_SUPPORTED {code: 4, status: 403}` is triggered and thrown correctly instead (or before) the `MEDIA_ERR_NETWORK` one.  Unfortunately I cannot represent a reduced test case as it still unclear under what circumstances it happens. 

## Steps to reproduce
It's hardly reproducible, but happens to us when:
1. there are blocked live streams which return `403` error
2. user switches quickly through those blocked live streams for few minutes

## Results
Most of the time `MEDIA_ERR_SRC_NOT_SUPPORTED {code: 4, status: 403}` error is thrown and propagated to the player

### Expected
`videojs` should continue throw `MEDIA_ERR_SRC_NOT_SUPPORTED {code: 4, status: 403}`, which propagates to the player

### Actual
at some point instead of `MEDIA_ERR_SRC_NOT_SUPPORTED {code: 4, status: 403}` there is a `MEDIA_ERR_NETWORK HLS playlist request error {code: 2, status: 403}` logged into a console, but _not_ propagated to the player

### Error output
`MEDIA_ERR_NETWORK HLS playlist request error {code: 2, status: 403}`

#### videojs
7.7.6
#### browsers
Chrome
#### OSes
MacOS Mojave
iPad Pro 11.4.1
### plugins
No

**Comment by gkatsev** [comment]
On iOS, we hand playback directly to the device, and the error we expose is the error we received from the media element. Information like whether it was a 403 just isn't available.

**Comment by bmind12** [comment]
@gkatsev, yes it's fine, but this is about an error event not being triggered on a `video.js` player instance under certain circumstances
