### ISSUE TITLE
Video has to be manually scrolled after changing quality on Safari 11.1

### ISSUE THREAD

**Issue by kangelov1** [videojs/video.js#6817]
## Description
After manually changing quality on Safari through player.vhs.representations()[i].enabled(true) for the desired and player.vhs.representations()[i].enabled(false) for the others the video loads the chunks but keeps displaying the loader and has to be manually scrolled to a new time with the progress bar to start playing.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Go to https://jsfiddle.net/L43vkade/7/
2. Play the video
3. Change the video quality

### Expected
Video changes to new quality and continues playing

### Actual
Video changes to new quality but show loader and does not start playing

### Error output
No errors. The only strange thing is that while it is playing before changing quality all representations show enabled(true).

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.4
#### browsers
Safari 11.1
#### OSes
Mac High Sierra
### plugins
No plugins but using this options to override native HLS

html5 : {
            hls: {
                overrideNative: true
            },
            nativeAudioTracks: false,
            nativeVideoTracks: false 
        }

**Comment by gkatsev** [comment]
You can use https://github.com/videojs/videojs-contrib-quality-levels to help choose renditions a bit more easily.

Also, does this happen on other browsers? While it's definitely possible to use our engine on desktop Safari, we haven't really tested there and don't recommend doing so.

**Comment by kangelov1** [comment]
Thanks for the reply. I tried the proposed solution but is still not working. The strange thing is that we were previously using HLS.js and the same issue occured but when starting a video and on Safari 11.1 - you had to scroll manually to start playing. 

I guess the best choice is to use native hls for Safari, since the only player I have seen succesfully override it with working quality levels is youtube.
