### ISSUE TITLE
HLS Streaming Issue: when performing seek operation if is stream  20-25 hrs  of recording ,facing seek bar playback issue. 

### ISSUE THREAD

**Issue by ravindrasatpute** [videojs/video.js#6819]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. start player and wait to run normally.
2. directly click on more than 15-20 hrs on the buffer, player stuck over there.
3. perform 1 min,5 min seek bar operation using =>player.currenttime(time). on browser 

### Expected
the player should run normally on 25-30 hrs recording smoothly.

### Actual
the player gets stuck or hangs on the 20-25hrs recording.
player continuously sending the request.
![image-20200825-142929](https://user-images.githubusercontent.com/62382650/91425018-37e9a500-e878-11ea-9046-2fed069e6ea3.png)

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers

what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

[Uploading Video js player issue_.zip…]()

**Comment by gkatsev** [comment]
Can you try your stream in https://videojs-http-streaming.netlify.app/ and see if it's any better?
I do know we have issues seeking very far into long streams, particularly if the segment duration is not very close to the target duration.

**Comment by ravindrasatpute** [comment]
Thank you,
 I checked it, still am facing an issue with 19-20 hrs back seek operation, actually I have 25 hrs recording stream is there. I want to perform seek operation but after 15 or 16 hrs back seek operation players get stuck, not responding, it's stuck endlessly.

please help me.

Thank you.

**Comment by ravindrasatpute** [comment]
Please find attachment.
![video js issue](https://user-images.githubusercontent.com/62382650/92073749-16d20880-edd2-11ea-87b1-f467312f8665.png)
![video js issue](https://user-images.githubusercontent.com/62382650/92073783-27827e80-edd2-11ea-9e5b-1d329a845c5f.png)

**Comment by ravindrasatpute** [comment]
please find attachment
![video js issue](https://user-images.githubusercontent.com/62382650/92073845-4da81e80-edd2-11ea-9e7d-773fa19b9b6b.png)

**Comment by ravindrasatpute** [comment]
Please find attachment
![video js issue](https://user-images.githubusercontent.com/62382650/92074134-f0609d00-edd2-11ea-8200-11e2ba0da855.png)

**Comment by ravindrasatpute** [comment]
@gkatsev please help me on the above issue.

Thank you.

**Comment by visbits** [comment]
Bumping this as we have the same problem with long playback windows.   Unsure how to provide adequate debug info short of a playlist that will stall the player immediately.

This should stay live for anyone to debug:  https://live1a-iad1.vrf.tv/ashland_depot_ptz/rewind-386400.m3u8 

Seems okay in hls.js but instantly crashes video.js
