### ISSUE TITLE
How to Play the Stream from the Stream Object in the Video JS

### ISSUE THREAD

**Issue by FahadRS** [videojs/video.js#6820]
I am not able to play the streamObject which i am receiving through the WEBRTC in the video js. stream is working fine in the html 5 video player though the following code

`htmlVideo.srcObject = stream;`

so my question is there any way in the video js to pass the stream object or what is alternative of html5 srcObject in the video js

i have also created the sample project on the stackblitz https://stackblitz.com/edit/video-js-in-angular2-with-webrtc?file=src%2Fapp%2Fapp.component.ts

**Comment by gkatsev** [comment]
I don't think we have official support for it but you can definitely get at the video element via `player.tech().el()` and set it that way.
