### ISSUE TITLE
Unable to read state variable during event's "ended" callback

### ISSUE THREAD

**Issue by jenlai1345** [videojs/video.js#6823]
## Description
Unable to read state variable during event's callback

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.  I have a simple page that plays through a `list of videos`. I tried achieving it by using the "ended" event callback. At the end of playing video, I advance the index and play the next video.
However, I discovered `currentIndex` is always `0` in the callback function, so videos will be played in the order: videoUrls[0], videoUrls[1],videoUrls[1], videoUrls[1], ..... 
 
```
        player.on("ended", () => {
            if (videoUrls.length > 0) {

               // advance index
                const nextIndex = (currentIndex + 1) % videoUrls.length;
                const nextUrl = videoUrls[nextIndex];
                setCurrentIndex(nextIndex);

                // play next video
                player.src(nextUrl);
                player.load();
                player.play();
            }

        });
```

### Expected
videos played: videoUrls[0], videoUrls[1],videoUrls[2], videoUrls[3], ..... 

### Actual
videos played: videoUrls[0], videoUrls[1],videoUrls[1], videoUrls[1], ..... 

Thank you very much for your help!

**Comment by mister-ben** [comment]
You've probably got a problem with variable scope, but it's not possible to say what from that snippet.

You might want to use the playlist plugin, which takes care of this kind of logic already https://github.com/brightcove/videojs-playlist
