### ISSUE TITLE
Video occasionally does not start

### ISSUE THREAD

**Issue by kangelov1** [videojs/video.js#6825]
## Description
Videos sometimes do not start. After calling play() the promise is pending and does not resolve or reject. Tried calling play after initializing the player and after the ready event is fired. In both cases it happens occasionally. It happens on certain videos more often.

Previous tries involved calling play after ‘loadedmetadata’ event, but it is not always fired so the play() method is not called. However the duration of the video was found judging by the appended duration to the control bar, so I guess some metadata was loaded. 
Usually the main m3u8 file is loaded, then two playlists are loaded one for 270p and one for 360p, but no chunks are received.

After starting another video and later returning to the problematic one it usually starts playing.

In the attached jsFiddle, I think it happened a couple of times, but is more stable. Unfortunately the videos with which I have issue are copyrighted and can't use them for a demo.

As can be seen we have one hidden div element, containing a video tag. When we click on a list item we attach the associated source and initialize a player. When we click another list item, we dispose the current player, create a new video element, append it to the hidden div and initialize again.

Is there something wrong with the workflow or is the issue probably with the videos themselves, given that issue is not so prevalent with the sample videos. Our videos we converted with amazon video convert.
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.https://jsfiddle.net/h1yjd936/12/
2.Try playing a video

### Expected
Video plays every time

### Actual
Video occasionally does not start.

### Error output
No errors. The play() promise is pending and video.paused() is false, while a loader is showing.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.4
#### browsers
Chrome, Safari

**Comment by mister-ben** [comment]
Rather than disposing of and recreating the player each time, this would probably work better if you use a single player and change its source on the click with `player.src({src: '...', type: '...'})`.

**Comment by kangelov1** [comment]
I have tried that, but the issue still exists. It sometimes happens even on the first video when the player is initialized for the first time.

![not working video2](https://user-images.githubusercontent.com/42936830/92232621-866df380-eeb7-11ea-92db-bbf044b60799.png)

As you can see above the playlist was loaded I think since the segments array has the segments, the state is 'HAVE_METADATA' and started is true.

But as you can see below no request are sent for the chunks. Only the playlist is loaded. Is it possible to be due to video transcoding since with the sample videos in the jsFiddle i don't think it happens, at least not that often.

![not working requests](https://user-images.githubusercontent.com/42936830/92233139-67bc2c80-eeb8-11ea-8657-ebba8b15a96c.png)

**Comment by eduards-amped** [comment]
I have the same issue and using `player.src({src: '...', type: '...'})` does not solve it.

**Comment by gkatsev** [comment]
One think that I can think off that could be causing an issue is that in your example you're entering fullscreen immediately upon player initialization. This can cause an issue as we clear the buffer on fullscreen change and could potentially put us into a weird state. You can also try loading in VHS 2.1 (currently in pre-release) and see if it helps things.

I would also recommend not entering fullscreen directly because, as a user, I find it incredibly frustrating.
