### ISSUE TITLE
Do you support frame by frame playback

### ISSUE THREAD

**Issue by xiaoxian521** [videojs/video.js#6826]
Do you support frame by frame playback

**Comment by gkatsev** [comment]
Sort of. Nothing built-in.
I believe there's a plugin that helps out with it and you can seek forward a frame by calculating the time needed to seek forward by a frame if you know the frame rate of the video. However, the media element isn't frame accurate and may skip frames even if you seek to the correct time for that frame.

**Comment by xiaoxian521** [comment]
Thanks! Can I ask the name of this plug-in
