### ISSUE TITLE
current video duration not display

### ISSUE THREAD

**Issue by bharatdevparmar** [videojs/video.js#6827]
## Description
Video duration not display, I've added style for display current duration but video timing not display.

```
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Video.js Example Embed</title>
<style type="text/css">
  .video-js .vjs-time-control{
    display: block;
  }
  .video-js .vjs-remaining-time{
    display: none;
  }
</style>
  <link href="http://vjs.zencdn.net/7.8/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/7.8/video.js"></script>
  <script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>
</head>
<body>
  <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" 
      data-setup='{}'>
      <source src="http://vjs.zencdn.net/v/oceans.mp4" type='video/mp4'>
  </video>
</body>
</html>
```

### Expected
Display video current duration / total duration.

### Actual
Video duration not display, it's only display **/** 

### Error output
![Screenshot 2020-09-01 at 5 28 41 PM](https://user-images.githubusercontent.com/30338831/91849364-900a1800-ec79-11ea-8ffd-b77770a9ce19.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8

**Comment by gkatsev** [comment]
The Video.js styles are overriding your styles. If you move the `link` element above the `<style>` element where you have the CSS that displays the time controls it should work.
