### ISSUE TITLE
Content over full screen mode

### ISSUE THREAD

**Issue by 786482ajay** [videojs/video.js#6830]
If I play video in full-screen mode on all browsers in the window operating system, works well. If I am using it on mac, and change to it full-screen mode, website's some content appear on video, I tried to solve it with z-index but not resolved.

**Comment by gkatsev** [comment]
Hi, can you provide more information about what's happening? Which browser is being used what version of Video.js? What isn't showing correctly?
Ideally, provide a minimal, complete, verifiable example.
