### ISSUE TITLE
Fallback for multiple sources does not work

### ISSUE THREAD

**Issue by dchaur** [videojs/video.js#6831]
## Description
It is a shame that since 2014 the fallback keeps failing using multiple sources.

## Steps to reproduce
Open whatever editor an include `video js`.
1. Include more than one source
2. "Break" the first source just modifying the url making it invalid
3. Run the player

### Expected
**VideoJS** follows the same approach as the standard HTML video, spec of "The resource selection algorithm for a media element" described on (https://html.spec.whatwg.org/multipage/media.html#concept-media-load-algorithm).

### Actual
**VideoJS** does not fallback correctly trying to play the other available source.

### Error output
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. `

## Additional Information
![image](https://user-images.githubusercontent.com/28889792/92134411-c6769d00-ee09-11ea-86fd-41b787c718f4.png)

#### videojs
All of them
#### browsers
All of them
#### OSes
All of them
### plugins
no.

**Comment by gkatsev** [comment]
This is basically expected behavior right now, and we have a long-standing issue to fix it https://github.com/videojs/video.js/issues/1805.
We hope to finally fix it in the next quarter.
