### ISSUE TITLE
player.currentTime() always 0 on android chrome

### ISSUE THREAD

**Issue by damjan25** [videojs/video.js#6832]
Why is player.currentTime() always 0 or 0.4 on android chrome, even though the video length is 15s.
![image](https://user-images.githubusercontent.com/60606529/92176188-41f24180-ee3e-11ea-8530-045cb389fe83.png)

Version: 7.8.4
Device: Android Chrome
Plugins: ima

It works normally if I try in Iphone X emulator in chrome

What Am I trying to do?
- pause player 0.3s before END
- show replay button (on click video.currentTime = 0) and play the video

**Comment by damjan25** [comment]
Ok I found a way to get the correct currentTime on android chrome as well, but now I still don't know how to set currentTime via ima. Since setting currentTime = 0 on html5 video element doesn't do anything(since currentTime is always 0.04 or 0) in chrome 
```
player.ima.addEventListener(EventType.AD_PROGRESS, (IMAEvent) => {
        let adProgressData= IMAEvent.getAdData();
        console.log(parseInt(adProgressData.duration)-parseInt(adProgressData.currentTime));
      });
```

Any ideas ? :)

**Comment by mister-ben** [comment]
I don't think IMA supports this. Closing in favour of the questions you've asked at at https://github.com/googleads/videojs-ima or https://groups.google.com/g/ima-sdk. They're the right place, as this is not controlled by Video.js.

**Comment by damjan25** [comment]
@mister-ben what about through this object ? https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdProgressData#currentTime

Does it expose just get functions or set() as well ? :thinking:
