### ISSUE TITLE
how to default play back speed?

### ISSUE THREAD

**Issue by zala143** [videojs/video.js#6834]
## Description

I see how to set array of playback rates (e.g. playbackRates: [0.5, 1, 1.5, 2]). but how do you set a default playback rate?

trying to use as headless embedded player so no onscreen controls and would like to set video as play half speed?

Thanks for help....

**Comment by gkatsev** [comment]
You can use [`player.playbackRate()`](https://docs.videojs.com/player#playbackRate) to set a specific playback rate manually, though, if a new source is set it will be reset. You can also use [`player.defaultPlaybackRate()`](https://docs.videojs.com/player#defaultPlaybackRate) to set a default playback rate.
