### ISSUE TITLE
Videojs player.width not working in fireos webview app

### ISSUE THREAD

**Issue by thepenstock** [videojs/video.js#6836]
## Description
I have a webview app that is packaged with Cordova that I use to stream HLS content on,  it has a div wrapper around the video tag that positions the video and makes it a certain size.  Everything worked great until a new update to firestick or fireos that now causes the video to always be fullscreen?  The div is the correct size and the video itself is just a small portion of the full screen instead of fitting inside completely like it used to.  Very weird issue that I cant figure out what is wrong.  When loading the video stream, the loader is spinning in the middle of the div box but the video itself wraps the entire screen.  This only happens on FireOS and I can test on chrome or edge and it works normally.  

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
Video width should be what is stated with player.width(value)

### Actual
Video width is fullscreen no matter what

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
7.2.3
#### videojs
what version of videojs does this occur with?
7.2.3
#### browsers
what browser are affected?
Webview for FireOS, 
#### OSes
FireOS
### plugins
None

**Comment by gkatsev** [comment]
Have a live a example we can see?
Also, if you want to see the current size of the player, you may want to use `player.currentWidth()` instead.

**Comment by thepenstock** [comment]
Ok,

I have put together an example for testing.  As previously stated, the same error occurs but only on fireos webview app.  You can test as long as you have a cors plugin or older MEdge browser and see that the code works fine in a browser but has different actions on fireos.

The html page is available at:
https://www.zipmaven.com/example.html

It has a few scripts attached, i.e. jquery,video.js,etc.

I also compiled this into an android webapp for FireTv, this apk can be found at:
http://www.zipmaven.com/example.apk

If you download the app and install on Firestick or Firestick 4K, you'll see what I am talking about. I'm open to provide any more info needed but I am pretty sure it has to do with video.js but I could be wrong, I have been before.

**Comment by thepenstock** [comment]
I have also included a simple app with no videojs, just using a regular video html5 tag and it works as expected.

http://www.zipmaven.com/example2.apk

**Comment by gkatsev** [comment]
Maybe it doesn't like it that we're changing the size via CSS?
You can try setting `window.VIDEOJS_NO_DYNAMIC_STYLE = true` before Video.js loads and see if that fixes it.

**Comment by thepenstock** [comment]
I set window.VIDEOJS_NO_DYNAMIC_STYLE = true before video.js loads and nothing changed.  Like I said originally, the preview window worked absolutely perfect, including changing the size via css, until a forced FireOS update.  And as the examples above the video tag alone does not cause this to happen.  It is very strange issue which is the reason I came on here to point it out.  I have tried a multitude of different things and even checked the player.currentwidth() after loading videojs and running player.play().  The player width is exactly the same as the preview div width, but the video as you can see is filling the size of the screen.
