### ISSUE TITLE
User activity classes with no controls on touch devices

### ISSUE THREAD

**Issue by nackd** [videojs/video.js#6837]
## Description
With no controls, the 'vjs-user-active' and 'vjs-user-inactive' are used, but don't reflect user activity reliably on touch devices.

### Expected
Either the classes are not there at all or they can be relied upon.

### Actual
If you tap the screen for less than the `touchTimeThreshold` of 200ms the 'vjs-user-inactive' class is kept. This is because the call to `this.addTechControlsListeners_()` is skipped, which is required for detecting this type of activity.

**Comment by gkatsev** [comment]
What is the effect on controls in the case of the tap lasting under 200ms? Do they still show up or do they stay hidden? As long as the state of the controls and the classes are in sync, it should be fine.
Also, you probably should use `player.userActive()` rather than the class existence to see whether the player is active or not.

**Comment by nackd** [comment]
Well, the controls are hidden via CSS with selectors that use the classes, so the visibility can never be out of sync with them. I now see that my description might be a little ambiguous: when I said 'no controls' I meant that this only happens when videojs is setup with `{controls: false}`.

We set `controls: false` and have many different themes that include custom video controls that use the API. One of our developers tried to hide the controls on inactivity based on the `vjs-user-inactive` class. This works fine on desktop with a pointer device, but not on touch devices. Once the controls are hidden, to make them shown again, you have to make a tap longer than 200ms but shorter than what the system deems as a long tap.

We use custom controls, so maybe we should implement our own activity detection instead of using `vjs-user-inactive`. But if the classes are there, they should be reliable. If they are not meant for `controls: false` that's fine, but then they shouldn't be there at all under that configuration.
