### ISSUE TITLE
Related Video just like JWPlayer

### ISSUE THREAD

**Issue by sunilstg** [videojs/video.js#6838]
Hi, 

I am looking for VideoJS Related video showcase and user engagements using JSON object file just like JWplayer given in below screenshot or VideoJS nuevodevel plugin - https://www.nuevodevel.com/nuevo/showcase/related. I have tried - https://www.npmjs.com/package/videojs-related  but it is not working. 

Please find below screenshot and share any working sample or advise the step to load videoJs Related videos at the end of the player and also toggle from controlbar button. 
![image](https://user-images.githubusercontent.com/2465993/92376270-fa123980-f11f-11ea-912a-6ad2b5c445c0.png)

Please help on this. 

Best regard,
Sunil

**Comment by gkatsev** [comment]
Unfortunately, we don't have a related plugin ourselves and cannot help with maintenance of a 3rd party plugin.
You could use the nuevo plugin as you posted. Alternatively, you may need to fix up the code for that videojs-related plugin if it isn't working. We can try and help out with specific questions around Video.js but we don't have the bandwidth to help develop and fixup the plugin.
