### ISSUE TITLE
Write a proxy over videojs

### ISSUE THREAD

**Issue by Niharika098** [videojs/video.js#6841]
## Description
Briefly describe the issue.

Unable to find how to write a proxy over videojs

### Expected
An approach to write a proxy over videojs

### Actual
Hi
I want to know what is the approach to write a proxy over videojs.

I am planning to implement a mid-stream CDN switcher to use the best CDN based on performance and for this the approach I thought would be to intercept the request from videojs using a proxy, fetch the content from cdn of my choice and give the response back to videojs.

Would love to know if there are any inbuilt methods in videojs which facilitate above kind of approach. If not can I use any open source solutions to implement the same ? Would love to get your feedback.

Thanks for your time.

**Comment by gkatsev** [comment]
You probably should look at Service Workers instead of trying to do it client side. You have a lot more control over various things like this via Service Workers.

**Comment by Niharika098** [comment]
I have come across 3 approaches to solve this problem online
1. Run a local http server on each client and change the url to videojs to point to the local http server and then do loadbalancing
2. Overwrite XMLHttpRequest
3. Use serviceworker

Now I am not sure which would be a better approach to solve this problem.

**Comment by gkatsev** [comment]
I would definitely recommend looking at service workers first as they are basically designed for this task.

**Comment by Niharika098** [comment]
Sure that makes a lot of sense. I was confused between whether to use XMLHttpRequest or serviceworker. Will start out with serviceworker. Thanks for the help

**Comment by Niharika098** [comment]
@gkatsev The serviceworker needs to have a js file present in the local directory and then install it by loading. What I would like to have is a plugin js file which can be loaded using <script> tag and can take control of the video requests to send a custom response.
There shouldn't be any dependency of the js file to be present in the directory of the website since this plugin should be used by anybody who wants to integrate multi-cdn/p2p with videojs. Any feedback with regards to this ?

**Comment by gkatsev** [comment]
I would still not recommend doing stuff like overriding XHR.
Generally, HLS or DASH can work with multi-cdns by just having both in the manifest and have the player choose, though, they will generally go with the first one but the different renditions are available in the renditions list and can be disabled and enabled at will.
