### ISSUE TITLE
720x1080 video playback

### ISSUE THREAD

**Issue by PeterPilley** [videojs/video.js#6844]
## Description
Attempting to play videos with the latest version of videojs, videos that are 720x1080 do not play at all. The video format is mkv which I am loading as a webm.

When the video is loaded into the view we are presented with a black screen and the duration is shown however nothing is playable.

I have tried other videos of different resolution with the exactly same codec and it works perfectly. however if I do a mp4 of the same resolution I get no playback as well.

## Results
Expected the video to play correctly

### Actual
No playback

### Error output
If there are any errors at all, please include them here.

## Additional Information

ExifTool Version Number         : 10.80
File Name                       : video.mkv
Directory                       : .
File Size                       : 625 kB
File Modification Date/Time     : 2020:09:14 19:04:48+12:00
File Access Date/Time           : 2020:09:14 19:04:58+12:00
File Inode Change Date/Time     : 2020:09:14 19:04:58+12:00
File Permissions                : rw-r--r--
File Type                       : MKV
File Type Extension             : mkv
MIME Type                       : video/x-matroska
EBML Version                    : 1
EBML Read Version               : 1
Doc Type                        : matroska
Doc Type Version                : 4
Doc Type Read Version           : 2
Timecode Scale                  : 1 ms
Muxing App                      : Lavf58.20.100
Writing App                     : Lavf58.20.100
Duration                        : 0:00:36
Track Number                    : 1
Track Language                  : und
Codec ID                        : V_MPEG4/ISO/AVC
Track Type                      : Video
Image Width                     : 368
Image Height                    : 640
Display Unit                    : Unknown (4)
Tag Name                        : DURATION
Tag String                      : 00:00:36.069000000
Image Size                      : 368x640 <-- Working
Megapixels                      : 0.236

ExifTool Version Number         : 10.80
File Name                       : video2.mkv
Directory                       : .
File Size                       : 375 MB
File Modification Date/Time     : 2020:09:15 04:47:23+12:00
File Access Date/Time           : 2020:09:15 04:48:21+12:00
File Inode Change Date/Time     : 2020:09:15 04:48:18+12:00
File Permissions                : rw-rw-r--
File Type                       : MKV
File Type Extension             : mkv
MIME Type                       : video/x-matroska
EBML Version                    : 1
EBML Read Version               : 1
Doc Type                        : matroska
Doc Type Version                : 4
Doc Type Read Version           : 2
Timecode Scale                  : 1 ms
Muxing App                      : Lavf58.20.100
Writing App                     : Lavf58.20.100
Duration                        : 0:28:18
Codec ID                        : V_MPEG4/ISO/AVC
Image Width                     : 720
Image Height                    : 1280
Display Unit                    : Unknown (4)
Track Number                    : 2
Track Language                  : und
Video Codec ID                  : A_AAC
Track Type                      : Audio
Audio Channels                  : 2
Audio Sample Rate               : 22050
Output Audio Sample Rate        : 22050
Audio Bits Per Sample           : 32
Tag Name                        : DURATION
Tag String                      : 00:28:18.596000000
Image Size                      : 720x1280 <!-- not working
Megapixels                      : 0.922

ExifTool Version Number         : 10.80
File Name                       : video3.mkv
Directory                       : .
File Size                       : 115 MB
File Modification Date/Time     : 2020:09:15 05:35:14+12:00
File Access Date/Time           : 2020:09:15 05:36:16+12:00
File Inode Change Date/Time     : 2020:09:15 05:35:14+12:00
File Permissions                : rw-rw-r--
File Type                       : MKV
File Type Extension             : mkv
MIME Type                       : video/x-matroska
EBML Version                    : 1
EBML Read Version               : 1
Doc Type                        : matroska
Doc Type Version                : 4
Doc Type Read Version           : 2
Timecode Scale                  : 1 ms
Muxing App                      : Lavf57.83.100
Writing App                     : VLC 3.0.8
Duration                        : 11 days 18:30:08
Codec ID                        : A_MPEG/L3
Audio Channels                  : 2
Audio Sample Rate               : 44100
Track Number                    : 2
Track Language                  : und
Audio Codec ID                  : V_MPEG4/ISO/AVC
Track Type                      : Video
Video Frame Rate                : 1000
Image Width                     : 480
Image Height                    : 360
Display Width                   : 256
Display Height                  : 81
Display Unit                    : Unknown (3)
Tag Name                        : DURATION
Tag String                      : 282:30:08.833000000
Image Size                      : 480x360 <!-- works and is same video as video2.mkv but I changed the resolution
Megapixels                      : 0.173

**Comment by PeterPilley** [comment]
Example MP4
ExifTool Version Number         : 10.80
File Name                       : hd.mp4
Directory                       : .
File Size                       : 10 MB
File Modification Date/Time     : 2020:09:15 12:45:19+12:00
File Access Date/Time           : 2020:09:15 12:46:37+12:00
File Inode Change Date/Time     : 2020:09:15 12:46:48+12:00
File Permissions                : rw-rw-r--
File Type                       : MP4
File Type Extension             : mp4
MIME Type                       : video/mp4
Major Brand                     : MP4  Base Media v1 [IS0 14496-12:2003]
Minor Version                   : 0.2.0
Compatible Brands               : isom, iso2, avc1, mp41
Movie Data Size                 : 10899492
Movie Data Offset               : 48
Movie Header Version            : 0
Create Date                     : 0000:00:00 00:00:00
Modify Date                     : 0000:00:00 00:00:00
Time Scale                      : 1000
Duration                        : 0:01:12
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Track Header Version            : 0
Track Create Date               : 0000:00:00 00:00:00
Track Modify Date               : 0000:00:00 00:00:00
Track ID                        : 1
Track Duration                  : 0:01:12
Track Layer                     : 0
Track Volume                    : 0.00%
Image Width                     : 720
Image Height                    : 1280
Graphics Mode                   : srcCopy
Op Color                        : 0 0 0
Compressor ID                   : avc1
Source Image Width              : 720
Source Image Height             : 1280
X Resolution                    : 72
Y Resolution                    : 72
Bit Depth                       : 24
Video Frame Rate                : 12.827
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 0000:00:00 00:00:00
Media Modify Date               : 0000:00:00 00:00:00
Media Time Scale                : 44100
Media Duration                  : 0:01:12
Media Language Code             : und
Handler Description             : SoundHandler
Balance                         : 0
Audio Format                    : mp4a
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Handler Type                    : Metadata
Handler Vendor ID               : Apple
Encoder                         : Lavf58.20.100
Avg Bitrate                     : 1.2 Mbps
Image Size                      : 720x1280
Megapixels                      : 0.922
Rotation                        : 0

**Comment by gkatsev** [comment]
Are you able to share a copy of your video file? We've seen vertical videos play in Video.js. Though, for mp4 and mkv/webm it's up to browser support. Generally, we've seen mkv not work or only play the video.

**Comment by PeterPilley** [comment]
Yep I will share a link
