### ISSUE TITLE
A strange error after selecting 240p or 270p quality

### ISSUE THREAD

**Issue by babahh** [videojs/video.js#6845]
## Description
When playing HLS adaptive bitrate and selecting 240p or 270p qualities there would be an error:
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support."
[https://videolevels.com/landing/bc/LiaMHMV7s8w](url)

I've tried it with different versions of video.js and it seems that 7.7.7 and earlier versions did not have that problem. What has chanegd since then?

## Steps to reproduce
1. Use video.js player starting from 7.8.*
2. Try to play adaptive HLS stream: https://pepe-play.babahhcdn.com/bvod/_definst_/smil:vod/bahh/silver/bunny/play.smil/playlist.m3u8
3. After playback try to select quality 240p

### Expected
Smooth playback and transition to quality profile.

### Actual
Playback is stopped and error message shown: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

### Error output
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

#### videojs
7.8.* and higher
#### browsers
Chrome
#### OSes
Mac
### plugins
videojs-contrib-quality-levels
videojs-hls-quality-selector

**Comment by gkatsev** [comment]
I do not have any issues playing back and switching qualities on here https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fpepe-play.babahhcdn.com%2Fbvod%2F_definst_%2Fsmil%3Avod%2Fbahh%2Fsilver%2Fbunny%2Fplay.smil%2Fplaylist.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false
The versions of our playback engine there are in Video.js 7.10 and 7.11.
