### ISSUE TITLE
[Question] Splitting one video source to many clips?

### ISSUE THREAD

**Issue by woniesong92** [videojs/video.js#6847]
## Description
How would one split one video element (from a URL source or data URL) into multiple clips, and play through video.js?

## Steps to reproduce
1. Embed one video URL to the video.js player
2. Let the user enter timestamps where they want to split the video into multiple clips. The user can choose to trim each clip as well

## Results
The video can be separated into multiple clips

## Additional Information
This might not be achievable via `video.js` out of the box. I would be grateful for any relevant insights from video.js contributors, who should be experts at manipulating videos on HTML! :)

## Considered approach
- Represent the split clips as `Array<start_time, end_time>` Play the video in a hidden video.js player. For every frame update received from `requestAnimation`, check if the current timestamp is within the split clips
  - I think this might not be feasible because of performance issues

**Comment by gkatsev** [comment]
Video.js itself doesn't really allow you to split a video into pieces (I don't think the video element does it natively either). The easiest is to just fake it with clever seeking and playback, which can be made easier by using [middleware](https://docs.videojs.com/tutorial-middleware.html).
