### ISSUE TITLE
Use hls timestamp on progress bar

### ISSUE THREAD

**Issue by yangkghjh** [videojs/video.js#6848]
## Description

I am building a live player with a hls live stream supporting time shift .

Is it possible to show the current playing time on the progress bar?

Example:

![Snipaste_2020-09-21_16-09-14](https://user-images.githubusercontent.com/3609399/93745047-6f543300-fc25-11ea-8f5d-e908af6253f9.png)

## Additional Information

Current state:

Live:

![Snipaste_2020-09-21_16-18-44](https://user-images.githubusercontent.com/3609399/93745477-323c7080-fc26-11ea-8c84-f0659042ec38.png)

Time shift:

![Snipaste_2020-09-21_16-16-08](https://user-images.githubusercontent.com/3609399/93745322-e689c700-fc25-11ea-9ba0-7ba1b11880f7.png)

**Comment by gkatsev** [comment]
Unfortunately, that's kind of tricky to do right. We do want to add support for that, but we have no plans currently.
You can try doing it yourself by hooking up various metadata from the stream and [Video.js middleware](https://docs.videojs.com/tutorial-middleware.html).

**Comment by yangkghjh** [comment]
Is that possible to get the timestamp of the playing ts file?

That I can print it in a text area.

**Comment by ftirej** [comment]
> time shift

Hey, did you finish building the live player?, do have a repo?

**Comment by ftirej** [comment]
> Is that possible to get the timestamp of the playing ts file?
> 
> That I can print it in a text area.

Hey, did you finish building the live player?, do have a repo?
