### ISSUE TITLE
there are multiple audio tracks to choose from under IE11 and none under Chrome

### ISSUE THREAD

**Issue by mraiguo** [videojs/video.js#6849]
## Description
Briefly describe the issue.
https://codepen.io/mraiguo/pen/GRZwmVy?editors=1010

## Steps to reproduce
For the same video source, there are multiple audio tracks to choose from under IE11 and none under Chrome or firefox

### Expected
 can select audio tracks under Chrome

### Actual
can't select audio tracks under Chrome

### Error output
in IE11
![image](https://user-images.githubusercontent.com/22299421/93759416-b863b180-fc3c-11ea-889c-d3a31adf63c9.png)
in chrome
![image](https://user-images.githubusercontent.com/22299421/93759449-c6b1cd80-fc3c-11ea-9818-a158c9451085.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
latest
#### browsers
chrome ie11 firefox
#### OSes
windows 10
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Unfortunately, Chrome doesn't support alternate audio tracks present in mp4s. Video.js only handles alternate audio in HLS and DASH. Your best bet for alternate audio tracks is using HLS or DASH rather than an mp4.

**Comment by mraiguo** [comment]
@gkatsev so If I use HLS with multiple audio tracks, it will display properly ?

**Comment by gkatsev** [comment]
Yup. Safari handles HLS natively, and we handle HLS in other browsers.

**Comment by mraiguo** [comment]
@gkatsev ok, thanks
