### ISSUE TITLE
Blocked by CORS Policy

### ISSUE THREAD

**Issue by imkaranmaur** [videojs/video.js#6850]
#### How to Enable Access-Control-Allow-Origin to all resource 
[https://prnt.sc/ulauke]( https://prnt.sc/ulauke )
I am using this player on video streaming script but it does not play video from external URL
Please help me to Fix this issue

**Comment by gkatsev** [comment]
This is not possible to do. Since you don't own the video, you won't be able to play it back. CORS headers must be set by the server that hosts the video.

**Comment by imkaranmaur** [comment]
How I can Add Access-Control-Allow-Origin: * rule to the response header Because player work when we enable this extension on chrome https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?utm_source=chrome-ntp-icon

**Comment by gkatsev** [comment]
The server that hosts the media must set it and Google Drive won't set the headers. If you're trying to play content you don't own, unfortunately, we cannot help you. If this is content you do own, I would suggest hosting the content elsewhere and making sure that the host has the appropriate CORS headers.
