### ISSUE TITLE
option to enable / disable subtitles

### ISSUE THREAD

**Issue by awistudio** [videojs/video.js#6852]
can you turn on / off the subtitles with one button
only enable / disable 

without language selection and other options

**Comment by gkatsev** [comment]
Unfortunately, we do not have a button for that. However, it is something that can be done via the APIs that Video.js exposes.

**Comment by awistudio** [comment]
are you able to do this for me?

**Comment by gkatsev** [comment]
Unfortunately, we don't have the time to do it, sorry.
