### ISSUE TITLE
How to catch http error codes?

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#6854]
## Description
I would like to be able to capture HTTP errors codes so that I can display useful information back to my users about why their videos are not playing.

For instance, this is one user case in AWS Cloudfront you can block users from accessing content based on their Geolocation.

For this, it will normally return a 403 forbidden but in Cloudfront you can create custom error responses so I could change the error code to 503 and this is the code I would like to catch to display a useful message that this content is not available in their country.

![Screenshot 2020-09-24 at 15 38 39](https://user-images.githubusercontent.com/1894778/94160449-880a5600-fe7c-11ea-8608-fdf5bdcca60b.png)

Example URL: https://dw6ffjjssjmrq.cloudfront.net/livetime/index.m3u8 (blocked everywhere except Canada)

Example jsbin: https://jsbin.com/guzakowabo/edit?html,output

There may be a better way of doing this but I am not sure.

**Comment by gkatsev** [comment]
Unfortunately, that isn't really possible. The native media element doesn't provide this information and because of that we never exposed that in our playback engine. So, even if it worked in our playback engine it wouldn't work in Safari or whenever the native video element is used.

**Comment by samueleastdev** [comment]
Hi, @gkatsev thanks for clearing that up at least I know now.

Think the only way to combat this is to give a really generic error message back for all errors in my situation for instance.

Media Unavailable
Try again soon.

**Comment by gkatsev** [comment]
You're welcome!
