### ISSUE TITLE
View and Switch Audio Tracks in Chrome Without enable Chrome Flags

### ISSUE THREAD

**Issue by mzumbo** [videojs/video.js#6855]
I have a videojs with embeded audio. 

It's work fine in IE

but in chrome/Firefox I need to enable  experimental-web-platform to see the audio tracks.

example: chrome://flags/#enable-experimental-web-platform-features.

It's possible to add some code to the player to see the audio tracks without enable the flags in chrome?

**Comment by gkatsev** [comment]
If you're playing back an mp4 that isn't possible. We give mp4s directly to the browser to handle. If it's enabled in a flag that's good to hear because maybe it'll be available in the future natively.
Unfortunately, the mean time your best bet is to switch to HLS or DASH.

**Comment by mzumbo** [comment]
ok. I will try with:

<script src="video.js"></script>
<script src="videojs-http-streaming.js"></script>

But in this case I can't use my .mov files. Right? I need to convet to....?

<source src="https://test.m3u8" type="application/x-mpegURL">

This is correct?
