### ISSUE TITLE
Segment issue parsing (fragmented mp4)

### ISSUE THREAD

**Issue by thecodeassassin** [videojs/video.js#6856]
## Description
Briefly describe the issue.

Segments with certain naming schemes work fine when we package an HLS playlist with MPEG-TS segments but not with fragemented mp4 segments.

360_segment_160096693714548.ts => works fine
360_segment_160096693714548.mp4 => playback breaks

The following error appears:

videojs-http-streaming.js:20863 Uncaught TypeError: Cannot read property 'timingInfo' of null
    at SegmentLoader.updateTimingInfoEnd_ (videojs-http-streaming.js:20863)
    at SegmentLoader.handleAppendsDone_ (videojs-http-streaming.js:20902)
    at SegmentLoader.checkAppendsDone_ (videojs-http-streaming.js:20808)
    at Object.action (videojs-http-streaming.js:21240)
    at shiftQueue (videojs-http-streaming.js:21168)
    at SourceBuffer.<anonymous> (videojs-http-streaming.js:21377)

We also see that the video jumps a couple of times.

Sample player:

https://videojs-http-streaming.netlify.app/?debug=true&autoplay=false&muted=false&minified=false&liveui=true&partial=false&url=https%3A%2F%2Feurope-west-hls.mls.mycujoo.tv%2Fstephen%2Fckfdpcb6801x80148tukiw8u0%2Fmaster.m3u8%3Fis_drm%3Dtrue&type=application%2Fvnd.apple.mpegurl&keysystems=%7B%0A%20%20%22com.widevine.alpha%22%3A%20%22https%3A%2F%2Fwidevine-dash.ezdrm.com%2Fproxy%3FpX%3D83A430%22%0A%7D

Sample playlist with TS segments:
https://europe-west-hls.mls.mycujoo.tv/stephen/ckfdpcb6801x80148tukiw8u0/master.m3u8

Sample playlist with MP4 segments (please use the player above):
https://europe-west-hls.mls.mycujoo.tv/stephen/ckfdpcb6801x80148tukiw8u0/master.m3u8?is_drm=true

## Steps to reproduce
Use the player mentioned above

### Expected
Working stream without changing our segment names

### Actual
Stream playback halts because of JS error

### Error output
videojs-http-streaming.js:20863 Uncaught TypeError: Cannot read property 'timingInfo' of null
    at SegmentLoader.updateTimingInfoEnd_ (videojs-http-streaming.js:20863)
    at SegmentLoader.handleAppendsDone_ (videojs-http-streaming.js:20902)
    at SegmentLoader.checkAppendsDone_ (videojs-http-streaming.js:20808)
    at Object.action (videojs-http-streaming.js:21240)
    at shiftQueue (videojs-http-streaming.js:21168)
    at SourceBuffer.<anonymous> (videojs-http-streaming.js:21377)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Version used here: https://videojs-http-streaming.netlify.app

#### browsers
what browser are affected?

At least chrome
#### OSes
OSX 10.15.6
### plugins
No, works in our player, doesn't work in the player listed above (https://videojs-http-streaming.netlify.app)

**Comment by gkatsev** [comment]
I'm not seeing any timingInfo errors and I see the same behavior for bother DRM and non-DRM streams. We take a bit to start and after playing a couple of segments we stall.
Looks like we start playing towards the end of the playlist because it's live, and then we stall because the playlist doesn't refresh, and we've played through what was given.
Is this a live stream or a VOD? If it's VOD, you need to add the `EXT-X-ENDLIST` tag to the manifest.

Also worth noting there was a new VHS release after you had opened up this issue.

**Comment by thecodeassassin** [comment]
@gkatsev this was a live stream. I can send you an updated URL for another live stream. 

Works on these releases:
video.js@7.8.5
http-streaming@1.13

New live stream URL (the rest is the same, license server etc)

https://europe-west-hls.mls.mycujoo.tv/stephen/ckfpdu9zs002a0137oktt6mu4/master.m3u8?is_drm=true

**Comment by rhyswilliamsza** [comment]
This has just started happening to me too. Going to investigate quickly and see where this is being thrown :)
