### ISSUE TITLE
Vimeo support with VideoJS (v7.8.4)

### ISSUE THREAD

**Issue by lewismalpas** [videojs/video.js#6858]
Hi GH,

I'm hoping to use the use Vimeo URLs within VideoJS, however from my reading it seems the videojs-vimeo plugin is no longer maintained and from my attempt at implementing does not work with the latest release of VideoJS which I've raised a separate ticket for on their repo - Can anyone advise on how I can add support for Vimeo URLs (e.g https://vimeo.com/290702348)?

Is the only way to have a Vimeo Pro account which provides you with the MP4 links which I can then use directly with VideoJS without requiring any additional plugins?

Any help / advice would be much appreciated!

Thank you,
Lewis

**Comment by gkatsev** [comment]
Answered in https://github.com/videojs/videojs-vimeo/issues/152

Having a Vimeo Pro account which gives you direct source URLs is definitely the easiest method.
