### ISSUE TITLE
Can we have the video played in portrait fullscreen mode in mobile devices? (Vertical video)

### ISSUE THREAD

**Issue by Kaywee27** [videojs/video.js#6859]
## Description
Refer to this link. Please do watch in a mobile device for a better understanding
https://youtu.be/vXeMJZVzlzA

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Click on the fullscreen button with auto-rotation off in your device without rotating the device

### Expected
The video should be resized to portrait fullscreen and played the same as the behavior in Tiktok video
### Actual
The video will go into landscape mode and will be played in fullscreen mode

**Comment by gkatsev** [comment]
I would assume so. We don't do any rotation of the device when you enter fullscreen, so, if you have a vertical video I'd expect it to work.
What browser are you testing with? Do you have a sample page?

**Comment by Kaywee27** [comment]
I didn't test with a vertical video, what I have actually asked is the ability for resizing a regular video so that it gets played as a vertical video in portrait full-screen mode just as Tiktok videos do.
