### ISSUE TITLE
Height and width options ignored/overridden

### ISSUE THREAD

**Issue by Frank071** [videojs/video.js#6860]
## Description
Setting height/width (both as startup options and with the functions) of a player has no effect, seem to be overridden by video-js.css contents.

## Steps to reproduce
1. Launch player with call to videojs, with options including setting width/height

### Expected
Player of the specified size

### Actual
Options are ignored, player is 100% of parent element
![vjs height_width overridden](https://user-images.githubusercontent.com/807403/94483762-a4d7be00-01db-11eb-9a37-c41b2674208d.png)
### Versions
videojs: 7.8.4
browsers: firefox, chrome, edge (all current)
os: windows
no plugins

### Resolution
1. removing the dimension-styling from video-js.css for vjs-fluid, vjs-16-9 and vjs-4-3 (this solves inactivating the settings for the _cointainer_-dimensions class )
2. adding 'padding-top: 0px' for both vjs-16-9 and vjs-4-3 (thus overruling the padding setting that is put inside the _container_-dimensions style by the javascript code (no idea what purpose is served by that padding-top, the effect is a player container that has two large black area's above the player

### Test
A test URL can be made available upon request

**Comment by mister-ben** [comment]
The `.vjs-16-9`, `.vjs-4-3` and `.vjs-fluid` classes fit the player to its container's width, keeping the player aspect ratio at 16:9, 4:3 or the detected video aspect ratio respectively. If you want to use fixed sizes, remove those classes from your player.

**Comment by Frank071** [comment]
Oh... The javascript code (function `updateStyleEl` ) adds a runtime stylesheet when and if dimensions are set that (a) acknowledges the aspect-ratio and (b) includes a specific style for the `.vjs-fluid` class. So the behaviour to ignore/overrid settings is somewhat unexpected. I can see reason for ignoring either height or width (given the enforcement of a ratio), but not for ignoring both... If however this is as it should work, then I would suggest adding a little note saying so in the docs and perhaps the code.

**Comment by gkatsev** [comment]
The aspect ratio classes are documented as being part of fluid mode https://docs.videojs.com/tutorial-layout.html
