### ISSUE TITLE
Long m3u8 files cannot be played normally. Occasionally a click progress bar appears, and the progress bar goes back to the first second

### ISSUE THREAD

**Issue by sss2016** [videojs/video.js#6861]
## Description
Briefly describe the issue.
When playing a long video, clicking on the progress bar will always be loading and occasionally jump back to the first second

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.This happens when you play a 71 hour m3u8 file and click the progress bar to fast forward
2.And the short m3u8 file can be dragged normally
3.

### Expected
After clicking on the progress bar, you can quickly see what you want to see

### Actual
clicking on the progress bar will always be loading and occasionally jump back to the first second

### Error output
none

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
There are a lot of things that could affect it. Can you try testing on https://videojs-http-streaming.netlify.app/ and see if things are improved? Are you able to share a test stream?
