### ISSUE TITLE
Vertical volume bug in version 7.9.5

### ISSUE THREAD

**Issue by dargre** [videojs/video.js#6863]
I used to have vertical volume bar in my videojs theme. This was working correctly in last version I used 7.8.4. When I upgraded to 7.9.5 I found that videojs calculates volume slider and volume level opposite. It's not possible to have properly working vertical volume slider now, no way to fix it through css only. Since videojs theme demos use only horizontal volume I guess, vertical volume was not verified to work properly. Hope to see the fix soon.

**Comment by gkatsev** [comment]
Do you have the same issue with Video.js 7.9.3? My first thought would be that https://github.com/videojs/video.js/pull/5773 messed it up.

**Comment by gkatsev** [comment]
Yup, looks like that did it. I would downgrade back to 7.8 (or 7.9.3) while we fix the issue.

**Comment by dargre** [comment]
7.9.3 is fine with vertical volume... I just verified it.

**Comment by gkatsev** [comment]
Thanks for verifying @dargre!

**Comment by gkatsev** [comment]
I have a fix for this in https://github.com/videojs/video.js/pull/6864
