### ISSUE TITLE
Captions stopped working with ios14 and macOS Safari 14

### ISSUE THREAD

**Issue by jaunt** [videojs/video.js#6866]
## Description

I have been adding my caption tracks with:

player.addRemoteTextTrack(
                  {
                    src: my.vtt,
                    label: "English",
                    srclang: "en",
                  },
                  false
                );

This has been working great on safari and all browser.

Since iOS 14 and macOS Safari 14, it has stopped working.  Chrome on iOS 14 also doesn't work.

Other browsers on macOS are fine.

I will provide more technical detail as I continue to investigate.

**Comment by jaunt** [comment]
I think Safari 14 and iOS 14 are being more strict about CORS.  

Adding crossorigin to the video element seems to fix the issue.

`        <video
          crossorigin="anonymous"
        />`

**Comment by gkatsev** [comment]
Ah, that makes sense. If the captions are loading from another origin, it's worth setting `crossorigin` appropriately.

We've considered doing it automatically, but we think that will be too unexpected and could potentially cause more issues than it solves.
