### ISSUE TITLE
VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!

### ISSUE THREAD

**Issue by chrisformula** [videojs/video.js#6868]
## Description
When having multiple videos the VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins! keeps popping up

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Install Videojs
2. Create Vue Component
3. Have multiple videos

### Expected
No warnings of already registered

### Actual
VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!

### Error output
VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!

what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by etomProductions** [comment]
Maybe this link help you?
https://github.com/videojs/videojs-contrib-hls/issues/1427#issuecomment-399581417
