### ISSUE TITLE
Why when I console log myPlayer it has (player_) infinite loop?

### ISSUE THREAD

**Issue by etomProductions** [videojs/video.js#6869]
## Description
I'm developing video.js plugin, I tried to console log my results and I noticed when I log myPlayer it has infinite nested (player_) with the exact same results. I decided to download local copy and tried and the result is the same.

CDN videoJs , the result is the same. 

I tried to check in your website but you are using the webpack.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. `let player1 = videojs('videojs-etom-extras-player1', playerOptions1)`
2. console.log(player1)
3.

### Expected
player_ will show once per player.

### Actual
Please describe what actually happened.
Nested  infinite loop of player_  
You need to open the tree and search again for player_  then open its tree and search again for player_ , you will keep have the same for ever.

### Error output
No errors.

## Additional Information
Im not sure if this is normal or no.

### versions
All versions. Tested in CDN and 7.9.x

#### videojs
what version of videojs does this occur with?
 CDN and 7.9.x

#### browsers
All browsers 

#### OSes
what platforms (operating systems and devices) are affected?
Windows 10 + Node

### plugins
are any videojs plugins being used on the page? If so, please list them below.
No Plugin.

Thank you,
Tariq

**Comment by gkatsev** [comment]
There is a reference to the player on components, the player being a component it gets a reference to the player via `player_`. Since it's a reference to itself you can expand it intl the console infinitely. This is completely normal and expected. The only potential issue is if you try to output the object to JSON but that's not recommended.
