### ISSUE TITLE
Do not play my video only on TOR browser

### ISSUE THREAD

**Issue by peterpetor** [videojs/video.js#6872]
I have a problem, I uploaded my  videos for my website, but under internet explorer, chrome, and firefox  I always got this message when I am trying play:
The media could not be loaded, either because the server or network failed or because the format is not supported.

But under TOR brwoser works fine!
By TOR I see something what which is not the case with other browsers.
TOR loading this message: transfering data from ... and loads the videos. 
Can you help me, what could be the problem?

**Comment by gkatsev** [comment]
Unfortunately, there isn't really much information to help out. We do have an FAQ and a troubleshooting doc that may be helpful: https://docs.videojs.com/tutorial-faq.html and https://docs.videojs.com/tutorial-troubleshooting.html
