### ISSUE TITLE
Proper react hook with video js

### ISSUE THREAD

**Issue by jimmycallin** [videojs/video.js#6873]
Hi! 👋 

I've made a react hook for video.js that properly interacts with React, including modifying properties without leaving any event listeners or DOM nodes hanging. This isn't super easy, since video.js removes the parent DOM node, which is sort of a no-no in React land.

If you find it according to your standard, perhaps you want to include it in your documentation for how to use it with React.

https://github.com/jimmycallin/react-hook-videojs

**Comment by gkatsev** [comment]
Thanks @jimmycallin! One day I'll actually take the time to learn react hooks.

(going to close this, but hopefully this helps people who are looking for it.)
