### ISSUE TITLE
worker_threads dependency not found while using require("../../../../node_modules/ffmpeg.js/ffmpeg-worker-mp4.js")

### ISSUE THREAD

**Issue by faheem-larasoft** [videojs/video.js#6875]
I've used `require("../../../../node_modules/ffmpeg.js/ffmpeg-worker-mp4.js") `in my vuejs codebase as follows:

<img width="1012" alt="Screenshot 2020-10-06 at 5 56 46 PM" src="https://user-images.githubusercontent.com/60872728/95204392-78382d80-07fd-11eb-847e-ff1da2f0bf87.png">

and When I do compile codebase using `yarn serve` I am getting following error:

This dependency was not found:
* worker_threads in ./node_modules/ffmpeg.js/ffmpeg-worker-mp4.js
To install it, you can run: npm install --save worker_threads

Also check error screenshot below:
<img width="966" alt="Screenshot 2020-10-06 at 5 58 57 PM" src="https://user-images.githubusercontent.com/60872728/95204497-a0279100-07fd-11eb-8df8-6f814283c9d1.png">

**But I am unable to find worker_threads when using `npm install --save worker_threads` or `yarn add worker_threads`**

**Please note, I am using:**
Node.js version = v12.18.4
yarn version = 1.22.5
MacOS Catalina

Any help in this regard?

**Comment by gkatsev** [comment]
You'll want to open up an issue against videojs-record https://github.com/collab-project/videojs-record.
