### ISSUE TITLE
video.pauseTime not working on chrome

### ISSUE THREAD

**Issue by sciracioglu** [videojs/video.js#6876]
## Description
Hi, 

i added questions to some seconds of the video, 

when i load the video, i know when stop the video and ask a question.

i use video.pauseTime method.

its work perfectly on firefox but video never stops in chrome.

please help me urgent

### Error output
there is no error

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
"video.js": "^7.8.4"
#### browsers
chrome Version 85.0.4183.121
#### OSes
windows, mac
### plugins
-

**Comment by gkatsev** [comment]
Closing dupe in favor of #6877
