### ISSUE TITLE
in chrome video.pauseTime couldn't work

### ISSUE THREAD

**Issue by sciracioglu** [videojs/video.js#6877]
## Description
Hi, 

i added questions to some seconds of the video, 

when i load the video, i know when stop the video and ask a question.

i use video.pauseTime method.

its work perfectly on firefox but video never stops in chrome.

please help me urgent

### Error output
there is no error

#### videojs
"video.js": "^7.8.4"
#### browsers
chrome Version 85.0.4183.121
#### OSes
windows, mac
### plugins
-

**Comment by gkatsev** [comment]
Unfortunately, I'm not sure what `video.pauseTime` refers to. It isn't in the Video.js API or the video element's API.
Do you have an example?
