### ISSUE TITLE
What are the WebView support specs?

### ISSUE THREAD

**Issue by Sujin1135** [videojs/video.js#6878]
## Description
video.js player test was conducted on WebView of Android 4.4.2 version but the player was not working.
So I looked up video.js support spec. but It was not listed about WebView.
I need a support specification of WebView.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play a video on WebView of Android 4.4.2 version.
2. It was not working and The error phrase "The media could not be loaded either because the server or network failed" came out.

### Expected
I thought videojs player does not support WebView of Android 4.4.2.

### Error output
"The media could not be loaded either because the server or network failed"

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
^7.8.4

#### android
4.4.2

**Comment by gkatsev** [comment]
Android 4 is so old, and we haven't actively tested it in a while that it's definitely possible that things have broken.
I would try Video.js 6.x, it's more likely to still be working.

What type of media are you trying to play? You likely won't be able to play anything other than mp4s there, if I remember correctly.
