### ISSUE TITLE
is there any way to control the segment downloadable size in hls or dash ?

### ISSUE THREAD

**Issue by Liocat-sp** [videojs/video.js#6879]
## Description
i am using dash and hls adaptive streaming and i have a video of 720p rendered at 1.2Mbps from aws. when my video first load's the size of the chunk is around 700 kb or 1mb sometime. and i wanted to know is there any way to control the bitrate or size  of video segment. i want to have around 120kb so that my video starts as fast as possible. i have seen at https://videojs-http-streaming.netlify.app/utils/stats/ site it shows that measured bitrate is 363kbps and video bitrate is 40.5 kbps. so can anyone help me in this. and if there is anything related to aws rendering please help me with that.   

i am new to the video streaming and i will appreciate any kind of help. 

## Additional information
i am using video.js in react.js in functional components.

#### videojs
what version of videojs does this occur with?
v7.8.3

**Comment by gkatsev** [comment]
Unfortunately, there isn't really a way to control this. We make an XHR for segments and the chunk sizes are determined by the backend or the browser.

**Comment by Liocat-sp** [comment]
that's ok and thanks for responding.

**Comment by Liocat-sp** [comment]
got my answer.
