### ISSUE TITLE
The player control does not work on android

### ISSUE THREAD

**Issue by deletron247** [videojs/video.js#6881]
version videojs 7.8.4

### Console log
video.min.js:12 VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!
(anonymous) @ video.min.js:12
video.min.js:12 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead

**Comment by gkatsev** [comment]
If you're seeing that warning it means that contrib-hls or http-streaming (VHS) twice. Video.js 7 includes VHS by default, so, including it separately isn't necessary. Also, that warning can be ignored and shouldn't actually cause an issue.

As for the control bar not working, can you provide more information? What video are you playing? What version of android? Which browser? We test with Android on a regular basis and haven't seen any major issues.

**Comment by deletron247** [comment]
Android 9
Browser Google Chrome
Movie m3u8
