### ISSUE TITLE
Failed to play HLS in any android browser

### ISSUE THREAD

**Issue by Anan5a** [videojs/video.js#6882]
## Description
HLS streams are unplayable in Android chrome, firefox, brave etc...

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. try to play this hls https://fs-uk-1-vodcache-seedbox-project.driveload.co/c17e44ef54bfa612/master.m3u8 (will be deleted after few days)
2. observe error, 
3.

### Expected
Play the video

### Actual
Loading error
### Error output
The media playback was aborted due to a corruption problem or media use features not supported by your browser

## Additional Information

player config 
```js

        window.current_player = videojs('my-video', {
          controls: true,
          autoplay: true,
          preload: "auto",
          html5:{
            nativeAudioTracks:false,
            nativeVideoTracks:false,
            nativeTextTracks:false,
            hls:{
              overrideNative: !videojs.browser.IS_ANY_SAFARI
            },
            vhs:{
              overrideNative: !videojs.browser.IS_ANY_SAFARI
            }
          },
          controlBar: {
            volumePanel: true,
            volumeControl:true
          },
          liveui:true
        });
        window.current_player.src(src_for_hls)

```
Encoder settings
```
ffmpeg -i %s -map %s -map 0:a? -c:v libx264 -s -2:480 -c:a aac -b:a 128k -b:v 800k -pix_fmt yuv420p -movflags +frag_keyframe+separate_moof+omit_tfhd_offset+empty_moov -keyint_min 120 -g 120 -sc_threshold 0 -b_strategy 0 -hls_list_size 0 -hls_segment_type fmp4 -hls_playlist_type event -hls_playlist -hls_master_name %s/master.m3u8 

```
```%s is replaced with corresponding values```
#### videojs
7.8.4
7.9.7
#### browsers
chrome
firefox
brave
...maybe others as well
#### OSes
Android 10

**Comment by gkatsev** [comment]
Can confirm that it's not working. Good news is that it seems to be working on https://videojs-http-streaming.netlify.app/ which is coming to Video.js really soon.

**Comment by Anan5a** [comment]
Update:

It seems ```mp4s``` is the problem, that means no fragmented mp4 in android 
I changed to conventional .ts and it's working 

Working hls: https://fs-uk-1-vodcache-seedbox-project.driveload.co/004e1bcd12a224c1/master.m3u8

**Comment by maleking** [comment]
any Update on this problem  @gkatsev  ?
changing  video progress not working in v7.8.4 (android 10)  but it works in https://videojs-http-streaming.netlify.app

**Comment by gkatsev** [comment]
We just released Video.js 7.10 which includes VHS 2, which is what was used by https://videojs-http-streaming.netlify.app.
Please try it out.
