### ISSUE TITLE
build videojs

### ISSUE THREAD

**Issue by dspape** [videojs/video.js#6883]
Hi guys,
To begin, I would like to point out that I am new to using videojs and the nodejs environment.
I want to install videojs but after build I cannot do the grunt command because the error tells me that I am missing Gruntfile.
Do I have to create it or there is a way to generate it automatically

Reproduce

cd video.js
npm install
npm run build
and I get the error when I do grunt.

![te](https://user-images.githubusercontent.com/68599892/95653382-4b7f6100-0af0-11eb-9eba-a67ddd51eb64.png)

**Comment by gkatsev** [comment]
We haven't used grunt for building for a while. To build you can run `npm run build`.
Do we still have some documentation that says to use `grunt` for building?

**Comment by dspape** [comment]
Okay, but maybe the ticket title isn't being used properly.
In fact I will install openveo-player from veo-labs and it requires videojs.
so i dropped videojs in the openveo-player folder.
once in the videojs folder I run npm install it works without problem but when I run npm run build it gives me errors

reproduce
git clone https://github.com/veo-labs/openveo-player.git
cd openveo-player
git clone https://github.com/videojs/video.js.git
cd video.js
npm install
npm run build  (I get the following error)

![Uploading te.png…]()

**Comment by dspape** [comment]
![Errors](https://user-images.githubusercontent.com/68599892/95676991-60c0c200-0bba-11eb-8b09-8ef4eaf68148.png)

**Comment by gkatsev** [comment]
Which version of node are you running? I think there may be an issue with the latest node.

**Comment by dspape** [comment]
Sorry for the delay, I am using node v14.10.0 and npm v6.14.8
