### ISSUE TITLE
mute control will trigger by space key when focused

### ISSUE THREAD

**Issue by mraiguo** [videojs/video.js#6884]
## Description
https://codepen.io/mraiguo/pen/ExyjXWx?editors=1000
![image](https://s1.ax1x.com/2020/10/11/0gsItP.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. click mute button
2. Press the space key
then change mute

The original video tag was paus/play by pressing the space bar always

### Expected
pressing the space bar just toggle pause/play

### Actual
toggle status witch is active

**Comment by gkatsev** [comment]
This is the expected behavior for Video.js. When a particular button in the control bar is focused, pressing space will toggle its functionality. This is done for accessibility and otherwise it will be hard for a keyboard only or a screen reader user to mute the video.

**Comment by mraiguo** [comment]
@gkatsev Is there anything you can do to turn it off?

**Comment by gkatsev** [comment]
Not really, what are you trying to do that this is needed?

**Comment by mraiguo** [comment]
@gkatsev Our testers thought it was a bug， Because it's inconsistent with the default behavior of the browser

**Comment by gkatsev** [comment]
We do not try to fully mimic the native control bar. In a lot of cases our behavior differs due to the choices we have made, often for accessibility.

**Comment by mraiguo** [comment]
@gkatsev   But that's the logic I see on YouTube and so on，  So it's hard for me to argue
