### ISSUE TITLE
Can video.js play HEVC/H.265?

### ISSUE THREAD

**Issue by RafalLukawiecki** [videojs/video.js#6889]
## Description

This is of a request for information. I could not find this information elsewhere, so asking here, the reliable source. Many thanks for a reply and apologies if this is not the right place to ask—please redirect me.

**Can the current version of video.js play HEVC/H.265-encoded fMP4 in desktop Safari (native), or any other browser (non-native)?** From my limited testing I can see my HEVC streams play using video.js **7.8.4** on iOS devices where it is handled natively. I expected the same functionality in desktop Safari on macOS, where, if I understand correctly it defaults to native playback unless overridden, but it does not play and returns error 3: _The media playback was aborted due to a corruption problem or because the media used features your browser did not support._

I can see there are a couple of issues mentioning HEVC/H265 in video.js but nothing that is conclusive or authoritative as far as I could find. Thanks again.

**Comment by gkatsev** [comment]
Safari playback is pretty much always handed off to the browser by default, so, HEVC will play there. For other browsers, the answer is more complicated. With VHS 2 which just shipped in Video.js 7.10, if the browser supports HEVC and it is packaged in an fmp4 container, we could play it. Unfortunately, the only environment that this is available outside of Safari is the Chromecast Ultra and the new Chromecast with Google TV. No other browser supports HEVC currently, afaik.

**Comment by RafalLukawiecki** [comment]
Thank you, @gkatsev. I can confirm that using VHS 2.2.3 in video.js 7.10.1 Safari and native browsers now playback HEVC content, ie. the handover works well. Thank you for your work on VHS 2.
