### ISSUE TITLE
Hiding vjs-big-play-button and cursor styling for inactive stream source

### ISSUE THREAD

**Issue by watershed** [videojs/video.js#6890]
## Description
My client wants to instantiate a `video-js` player with a dormant Wowza `.m3u8` stream source, and then activate the live stream close to its start time. In this way they can render a custom 'poster' image to the player area regardless of whether the stream is active or not.

So I want to be able to reliably hide `vjs-big-play-button` and restyle the mouse cursor when the stream is _inactive_. I thought I could use `vjs-error` as a hook as this seems to get written under these circumstances. The problem is that class is added _most_ of the time but not always. So not only does the big play button sometimes appear, but also the following is not reliable:

```
.vjs-error .video-js .vjs-big-play-button, 
.vjs-error .vjs-poster {
    cursor: default;
}
```

It's possible this is to do with `vjs-themes-fantasy` being used.

I will add a CodePen here ASAP.

**Comment by gkatsev** [comment]
What are the cases where you don't get an error event? An example would be super helpful.
If you know when the stream becomes live, you can always just set the cursor to the default until such a time using a custom class.
