### ISSUE TITLE
MEDIA_ERR_SRC_NOT_SUPPORTED 

### ISSUE THREAD

**Issue by gothika666** [videojs/video.js#6894]
hi I have no clue about coding or anything to do with technology and could use some help i was watching an anime on funimation and I've never had this happen before but I tried skipping onto the next episode and it wouldn't allow me to even play it 
![IMG_3940](https://user-images.githubusercontent.com/72914824/96101390-501b8f00-0ecd-11eb-88cd-41dc7fb8d669.jpg)

**Comment by gothika666** [comment]
I don't know how to do any of that I didn't cause the error it just happened I have no idea what caused it

**Comment by gothika666** [comment]
I don’t know how to do that stuff I didn’t cause the error so have no clue
how it happened to reproduce it

**Comment by gkatsev** [comment]
Does refreshing the page work? If not, you may want to contact funimation support as to why it's not working for you.
