### ISSUE TITLE
dist/video.js and video.min.js 7.10.0 still include videojs-http-streaming 1.13.4

### ISSUE THREAD

**Issue by RafalLukawiecki** [videojs/video.js#6895]
## Description
Thank you for releasing video.js 7.10.0, I much appreciate the work you are doing. Unfortunately, despite the comment that this version includes videojs-http-streaming 2.2.3, the bundled distribution artefacts available on npm in dist/video.js and dist/video.min.js still contain the older VHS 1.13.4.

## Steps to reproduce
- Install via `npm i video.js@7.10.0`, or
- Download and unzip from https://github.com/videojs/video.js/releases/download/v7.10.0/video-js-7.10.0.zip
- Navigate to dist/video.js
- See around line number 40092, which shows:
```
 /**
   * @videojs/http-streaming
   * @version 1.13.4
   * @copyright 2020 Brightcove, Inc
   * @license Apache-2.0
   */
```

Further, in testing, I can confirm that the behaviour of the just-released dist/video.js is identical to 1.13.4 and not 2.2.3.

### Expected
VHS 2.2.3

### Actual
VHS 1.13.4

**Comment by blacktrash** [comment]
Seems to be the same for https://cdnjs.cloudflare.com/ajax/libs/video.js/7.10.0/video.js

**Comment by gkatsev** [comment]
Oops, I think you're right. That's why I really should set up automated releases... Making a patch release.

**Comment by gkatsev** [comment]
Ok, Video.js 7.10.1 is out with VHS 2, sorry about that.

**Comment by RafalLukawiecki** [comment]
Thank you @gkatsev. I have updated and indeed the correct VHS 2.2.3 is now in the dist/ artefacts. I will continue testing with regards to the other issues I have found.
