### ISSUE TITLE
How are controlbar designed in rtl language?

### ISSUE THREAD

**Issue by mraiguo** [videojs/video.js#6899]
## Description
How are controlbar designed in rtl language.I'm not an expert on this and not sure that if there's an interface for this.
If I change the direction by force, clicking on the progress bar will cause problems

## Steps to reproduce

[![0jZzeH.png](https://s1.ax1x.com/2020/10/18/0jZzeH.png)](https://imgchr.com/i/0jZzeH)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
It appears the same as with ltr languages, because media controls shouldn't be flipped in RTL contexts. The control bar has `dir="ltr"` explicitly so that it doesn't inherit rtl from elsewhere.

**Comment by mraiguo** [comment]
https://stackoverflow.com/questions/40225889/how-to-make-videojs-progress-bar-responsive-to-click-tap-right-to-left     I found this, convinced the designer.
