### ISSUE TITLE
Setting currentTime to anything sets time back to 0 in videojs

### ISSUE THREAD

**Issue by jovi-juan** [videojs/video.js#6900]
## Description
I'm doing something fairly simple with videojs. I simply want to set the time to an arbitrary point on the timeline by clicking on an externally build UI (not the default seek stuff, but a set of divs that are acting like a progress bar.)

All the documentation and every post seems to indicate that setting currentTime as in object.currentTime(time) works. But in my case it doesn't. Not in the console, not anywhere. 

Though this jsfiddle works, the my code does not.
https://jsfiddle.net/jovijuan/kms65e1x/24/

## Steps to reproduce
Here's my code:
Here's my code:
```
function clearSetTimeBug(videoObj,timeToSetTo){		
		console.log('timeToSetTo:'+timeToSetTo);
		console.log("-1."+videoObj.id()+" readyState(): "+videoObj.readyState());//returns 4 (loaded)
		console.log("0."+videoObj.id()+" bufferedEnd(): "+videoObj.bufferedEnd());//returns about 2 seconds ahead of where the playhead is)
		if(videoObj.bufferedEnd()>timeToSetTo){
			console.log("1."+videoObj.id()+" currentTime(): "+videoObj.currentTime()); // returns a valid videojs object id and then shows the currentTime to be where the video's current timecode as a float.
			videoObj.currentTime(timeToSetTo);//this should totally work!
			console.log("2."+videoObj.id()+" currentTime(): "+videoObj.currentTime());// shows that the current time is 0!
		}else{ 
			//I added this to just go to as far as it's buffered, but this doesn't work either
			console.log("3."+videoObj.id()+" currentTime(): "+videoObj.currentTime());
			console.log("4. newTime: "+videoObj.bufferedEnd());
			videoObj.currentTime(videoObj.bufferedEnd());
			pageTime=videoObj.bufferedEnd();
			console.log("5."+videoObj.id()+": "+videoObj.currentTime());// still shows that the current time is 0!
			console.log("6. pageTime:"+pageTime);
		}
	}
```
The player is spun up like this:
```
function setUpPlayers(playerId,playlist,local_file,index){
		let myAspectRatio=heightRatio+":1"
		
		let videoTag="";
		videoTag +="<video id='playerInstance"+index+"' class='video-js vjs-fluid' width='100%' height='100%'>\n";
		videoTag +="\t<source src='"+playlist+"' type='video/mp4'>\n";
		videoTag +="</video>\n"
		$('#player'+index).html(videoTag);
		window["vjPlayer"+index]=videojs("playerInstance"+index, {"autoplay": false, "preload": "auto" });
	}

```
## Results
currentTime() cannot be set. Not to the anytime before the playhead or after, even though the video is loaded.

### Expected
I would expect currentTime() to work.

### Actual
The time just gets set back to 0

### Error output
Nor errors

## Additional Information
Play() and pause() and even currentTime() to get the current time works. But trying to set it just forces the player to go back to 0. The video is completely loaded (.readyState()=4)I'm pretty much at my wit's end. Any ideas?

I'm working in a mac in Chrome Version 86.0.4240.80, if that helps. Though, strangely, it works  with Firefox developer's edition 71.0b1 (64-bit) and in Safari 14.0 (15610.1.28.1.9, 15610) (though not locally for some reason). These are all local files and I'm running it from http://localhost:8000/index.php.

#### videojs
what version of videojs does this occur with?
7.8.4
#### browsers
what browser are affected?
Chrome 86.0.4240.80
#### OSes
what platforms (operating systems and devices) are affected?
Mac (as far as I know)
### plugins
are any videojs plugins being used on the page? If so, please list them below.
No.

**Comment by gkatsev** [comment]
Can you set up a jsfiddle showcasing the issue you're seeing?

**Comment by jovi-juan** [comment]
I did, but it actually works in the fiddle. Strangely, as I just checked this, it does work online, but not locally. That's really strange. I can even set the time deeper into the video with just a slight loading symbol popping up. Huh. I wonder why it wouldn't work locally. Anyway, thanks for looking at this.

**Comment by g3wd** [comment]
im am too experiencing issues with currentTime(). In my case the same code works fine on desktop browsers but currentTime() gets ignored on mobile. Im following your debugging curiously.

**Comment by mister-ben** [comment]
This sounds like the server delivering the source is ignoring `range` headers on the requests and always returning the start of the file.

**Comment by jovi-juan** [comment]
Oh. Ok. I don't know much about how to set that stuff actually, or much about the inner workings of the server in general. Is that something that would be defined in the .htaccess file? Do you have an example of a file? Would that be relevant to serving files locally? Serving video seems like a black art, cast by sorcerers to keep their business models afloat.

But if you have an example of how this might be set and not ignored, I'd really appreciate it.

**Comment by sven-ra** [comment]
Did you get this fixed somehow? I am also running into the same issue when using VideoJs for Audio.
