### ISSUE TITLE
video request question

### ISSUE THREAD

**Issue by xiaoxian521** [videojs/video.js#6901]
Video will continue to be requested during the dragging process of the videojs progress bar. Can you set the request video after dragging to make the request less frequent so as to avoid the back-end request from hanging up

**Comment by gkatsev** [comment]
Unfortunately, there isn't really a way to do this. I think we already throttle it so that it doesn't seek too much, but we can't do it too much or else it won't be responsive enough.

**Comment by xiaoxian521** [comment]
oh thanks
