### ISSUE TITLE
player problem aborted early because there isn't enough bandwidth

### ISSUE THREAD

**Issue by sitthajaid77** [videojs/video.js#6902]
## Description
I found WARN during playback and console display "Problem encountered with the current HLS playlist"(captured image with link) and sometime this problem make my playback freeze even audio still continue playing. 

## Steps to reproduce
I cannot reproduce this problem and it happens time to time.

### Expected
Any idea about this problem, which things I need to check.

### Actual
Cannot guarantee and it happens time to time in some devices.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
I not sure about version, but I attached video.vie in the link too.
#### browsers
what browser are affected?
Chrome.
#### OSes
what platforms (operating systems and devices) are affected?
Chrome web browser.
### plugins
are any videojs plugins being used on the page? If so, please list them below.

![messageImage_1603178163352](https://user-images.githubusercontent.com/22445538/96558977-a716cf00-12e6-11eb-97b3-0f3a728e2630.jpg)

video.vue
https://drive.google.com/file/d/1vEONedwuCE84nTYrC1dgtAEonq5tYn-n/view?usp=sharing

**Comment by gkatsev** [comment]
If playback continues without issues, you can just ignore this warning. We're actually even removing it altogether in an upcoming version of the playback engine.

**Comment by sitthajaid77** [comment]
Thank you gkatsev

**Comment by gkatsev** [comment]
BTW, we just released our the exterimental ABR algorithm in Video.js 7.11 pre-release. If you configure `experimentalBufferBasedABR` for VHS, you can try it out. If you do, please let us know how it works! We hope it should work much better!

**Comment by sitthajaid77** [comment]
Thank you and let me try
