### ISSUE TITLE
docs: Autoplay blog link in FAQ leads to 404

### ISSUE THREAD

**Issue by aminamos** [videojs/video.js#6905]
## Description
The autoplay blog hyperlink under the "Q: How do I autoplay a video?" section of the [FAQ](https://docs.videojs.com/tutorial-faq.html#q%3A-how-do-i-autoplay-a-video%3F) leads to an error page.

Expected link: https://videojs.com/blog/autoplay-best-practices-with-video-js/
Current link: https://docs.videojs.com/%5C/%5C/blog.videojs.com/autoplay-best-practices-with-video-js/

## Steps to reproduce
1. Navigate to the FAQ section: https://docs.videojs.com/tutorial-faq.html#q%3A-how-do-i-autoplay-a-video%3F
2. In the last line of that section, click the link 

### Expected
Autoplay blog is available.

### Actual
404 page not found error.

### Error output
![404](https://user-images.githubusercontent.com/26092352/96617154-1c1ee000-12b8-11eb-9dcb-c3a45aefe3fe.png)

**Comment by gkatsev** [comment]
My assumption is that our fix link script is misunderstanding this url and editing it unnecessarily.

**Comment by gkatsev** [comment]
Actually, looks like jsdoc or something is translating the url badly. It's coming out as `https:%5C/%5C/videojs.com/blog/autoplay-best-practices-with-video-js/` with those `%5C` for some reason. Sounds like some weird escape issue in jsdoc or something.

**Comment by gkatsev** [comment]
Not sure what's up with jsdoc's linkification. Made this as a workaround: https://github.com/videojs/video.js/pull/7027

**Comment by aminamos** [comment]
Thank you!
