### ISSUE TITLE
how to play RTMP with videojs swf 7.10.1 in React

### ISSUE THREAD

**Issue by pwj126** [videojs/video.js#6906]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.npm install video.js 7.10.1 and video-flash.js 2.2.1
2.Creat react component VideoPlayer

import React from 'react'
import videojs from 'video.js'
import 'video.js/dist/video-js.css'
import 'videojs-flash'

interface IVideoPlayerProps {
  key: any
  videoOptions: any
}

export default class VideoPlayer extends React.Component<IVideoPlayerProps, {}> {
  private videoNode = null
  private player = null
  public componentDidMount() {
    this.player = videojs(this.videoNode, this.props.videoOptions, function onPlayerReady () {
       console.log('onPlayerReady', this)
    })
    this.player.play()
  }
  public componentWillUnmount() {
    if (this.player) {
      this.player.dispose()
    }
  }
  public render() {
    return (
          <video
            ref={(node) => this.videoNode = node}
            id={this.props.key}
            autoPlay={true}
            className="video-js vjs-styles-defaults vjs-big-play-centered"
            style={{width: '100%', height: '100%'}}
          />
    )
  }
}

3.call VideoPlayer 
   const videoJsOptions = {
      controls: true,
      autoplay: true,
      sources: [{
        src: "rtmp://live.hkstv.hk.lxdns.com/live/hks",
        type: src.split(':')[0] === 'rtmp' ? 'rtmp/flv' : 'application/x-mpegURL'
      }]
    } 
   <VideoPlayer
       key={`video_${layer.id}`}
       videoOptions={videoJsOptions}
    />

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.
Run result error in front end console: webpack-internal:///./node_modules/_video.js@7.10.1@video.js/dist/video.cjs.js:104 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
![image](https://user-images.githubusercontent.com/8382753/96688962-5a99c500-13b4-11eb-8b3b-ed1dd9e29cbf.png)

## Additional Information
Please include any additional information necessary here. Including the following:
### versions

development tool: intellij idea     runtime version: 11.0.3+12-b304.10 amd64
#### videojs
what version of videojs does this occur with?
V7.10.1
#### browsers
what browser are affected?
chrome:  V86.0.4240.75
#### OSes
what platforms (operating systems and devices) are affected?
windows 10
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Is the browser is configured to allow Flash? In any case no browser will support Flash at all past the end of 2020. Try switching to HLS playback.

**Comment by pwj126** [comment]
thanks, please recommending a better plan of switching to HLS playback

**Comment by DinYin** [comment]
I have met seem question，video/flv can play by script but cannot play in react。videojs V7.10.1， "videojs-flash": "^2.2.1"。

**Comment by gkatsev** [comment]
Make sure that flash is enabled in your browser page. However, your best bet is to use something like flv.js or switch to HLS or DASH playback.

**Comment by pwj126** [comment]
> Make sure that flash is enabled in your browser page. However, your best bet is to use something like flv.js or switch to HLS or DASH playback.

please how to switch to HLS?
