### ISSUE TITLE
Are closed captions not handled by `videojs` in iOS Safari and other iOS browsers?

### ISSUE THREAD

**Issue by BaggioWongHK** [videojs/video.js#6907]
## Description
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

_While I'd like to produce a minimal reproducible sample for this, our project setup is a bit difficult to pry apart in a short time, and screenshots are the best I can do. Consequently, I understand that a lot of this will be based on assumptions and discussions, which I think is still valuable not just to this problem, because I suspect this is something that affects the whole community._ 

I'd like to get a better understanding of how CC's work under the hood (if anyone could point me in the right direction, or provide a conceptual overview, that'd be really helpful!).

I was looking at the DOM to locate where the text tracks are in iOS Safari, but they aren't in iOS Safari's DOM. For all other browsers I've tested on, I've seen them in Android Chrome, Desktop Chrome, Desktop Safari - but not in iOS Safari. The node I'm referring to specifically is the child `div` of the `div` with the `class` `vjs-text-track-cue` attached. It's noticeably absent when I'm looking at the Chrome and Safari consoles for the iOS Chrome 

This is the sample video no the `videojs` website that I used to test: https://videojs.com/advanced/?video=elephantsdream. 

Screenshot of the Safari console when attaching my real iPhone to it and opening https://videojs.com/advanced/?video=elephantsdream in iOS Safari:

![cc-not-in-dom](https://i.imgur.com/Olye55m.png) 

Also referring to the same screenshot above ☝, I see that the `vjs-hidden` class is attached to the `div` with `vjs-text-track-display`. (Why is that?)

I just discovered that Desktop Safari doesn't have it either: 

![desktop-safari-similar](https://i.imgur.com/MTQAJzN.png)

While Chrome has it

![desktop-chrome-has-cc](https://i.imgur.com/WFVqG9Z.png)

I'm guessing the tracks are empty because of this: https://github.com/videojs/video.js/blob/affc0611d978b1a6d02e443a46d14a58f2b1441c/src/js/tracks/text-track-display.js#L124

(From here on, though, it's a lot of conjecture as to why the text tracks aren't detected _**solely**_ in iOS Safari, Desktop Safari.)

Based on what I've seen so far, I think it's to do with the way that `<video>` elements are handled by iOS Safari (and I guess Desktop Safari). For any streams with a `.m3u8` file and captions, I think that iOS Safari intercepts the network request so that it would be able to handle it natively, and by default tries to strip it out of the video data so that the web player (`videojs` in this case), won't be able to render it. This is done so that it doesn't clash with any web players' own implementation of captions. 

Is this an accurate description? Or am I off my rockers here? To reiterate my previous question, is this behaviour also why the `vjs-hidden` class is added to the `div` that usually houses the CCs? 

To provide a bit more context, I've been dealing with a persistent bug where captions are showing in a giant font (it covers ~40% of the video), but this _**only**_ happens in iOS browsers (iOS Safari AND Chrome). 

![giant-font-cc](https://i.imgur.com/8A212Uz.jpg)

(Yes, that entire black area is the whole area of the video, so you can imagine if the screen starts filling up with frames with things like animals, people, weather phenomena, the CC's block out a large part of the video.)

After digging and investigating for a bit, I can't help but to think that 
1. There's nothing we can do to fix this, because it's handled at the system level by iOS (changing Closed Captions + SDH doesn't do anything - the user _**has**_ to select the "Off" setting in the bottom right corner in the full screen display if they want to turn it off - a webpage can't override this setting / nor is there an API to forcibly change this setting to off);

![the-cc-setting-to-the-right-fullscreen](https://i.imgur.com/1kRIUeO.png)

2. One way to deal with it is to simply exclude CCs, or only include them in a format that isn't interpretable by iOS's web video player, and send the CC metadata separately so that we can render this natively in HTML (if I'm not mistaken, I believe that YouTube does this)
3. Alternatively, I was thinking of whether we could experiment with different closed captions formats to see if this blown up font size display bug is specific to interpreting one kind of CC data format. 

Does this sound far fetched? Or are there better ways to handle this? Any thoughts / ideas would be greatly appreciated. 

(Apologies if my language is imprecise or my understanding is off, I'm still new to video and streaming tech. 😅)

Thanks again! 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Playing a stream where the CC metadata is encoded into the stream in each `.ts` segment pointed to in the `index.m3u8` file
2. Opening up the video in iOS Safari / Chrome

### Expected
Expected it to show CC normally as with other browsers (in the `div` with `vjs-text-track-cue`), or if not in the DOM, to show up in a normal font size with iOS's CC display. 

### Actual
CCs showed up in a giant font size, as seen in the screenshot above. (Attaching again here.)

![giant-font-cc](https://i.imgur.com/8A212Uz.jpg)

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
`7.6.6`
#### browsers
what browser are affected?
- iOS Safari
- iOS Chrome
#### OSes
what platforms (operating systems and devices) are affected?
- iOS 14.0.1 (but I don't think this is relevant)
### plugins
are any videojs plugins being used on the page? If so, please list them below.
N/A

_Images hosting courtesy of imgur: https://imgur.com/a/xFq0hox._

**Comment by gkatsev** [comment]
Yes, captions on Safari and iOS is handled natively by Safari by default. I would recommend keeping native behavior on iOS due to the native player.
As for sizing, you can have some minimal CSS to style the captions. But yes, it is a user setting too.

Can you share a sample of your captions? Maybe there're some settings there that's causing it to be weird?

**Comment by BaggioWongHK** [comment]
Hey @gkatsev, thanks for getting back to me! 

(To simplify matters, I'm just going to concentrate on iOS Safari [and by extension WebView, but I'm just going to be concentrating on iOS Safari first], and not Mac Safari, because even though the I was able to reproduce the error with my minimal reproducible sample for Mac and iOS Safari, in our prod app, the problem seems to exists only on iOS - emulated tracks did work on Mac Safari. This is strange because like with iOS Safari, Mac Safari also defaulted to native tracks with my minimally reproducible example. More on that below.)

(By minimally reproducible example, I means this)

```
<head>
  <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
</head>

<video
  id="my_video"
  class="video-js"
  controls
  preload="auto"
  width="640"
  height="268"
  data-setup="{}"
  playsinline
>
  <source src="leaving blank for now">
</video>
<script src="https://unpkg.com/video.js/dist/video.js"></script>
```

So I've managed to make some progress with the problem, I'm not 100% sure but I found [this with regards to media controls in WebCore](https://opensource.apple.com/source/WebCore/WebCore-7602.2.14.0.5/css/mediaControls.css.auto.html) - I suspect that captions have default styles applied to them in the Webkit browsers. The good news is that after some experimentation, I was able to override those styles via webkit styles on Safari, and they seem to work. By webkit styles I mean, `video::cue`, `video::-webkit-media-text-track-display` and `video::-webkit-media-text-track-container` specifically. 

The bad news is that those fixed the styles in the inline player (so they look perfectly fine now in normal mode), but in fullscreen, the captions become so tiny it's really hard to read. I've tried using things like `@media (orientation: portrait)`, `video::-webkit-media-text-track-display:fullscreen`, `video:fullscreen::-webkit-media-text-track-display`, `@media screen and (display-mode: fullscreen)` - all to no avail - it seems like the `:fullscreen` and `@media (display-mode:fullscreen)` pseudo selector and query just aren't respected. 

I don't think I got the syntax wrong, but just in case, here's a few more code snippets.

```
@media screen and (display-mode: fullscreen) {
  video::-webkit-media-text-track-display {
    font-size: 100px;
  }
}
```

and this

```
video::-webkit-media-text-track-display:fullscreen {
  font-size: 100px;
}
```

and this

```
@media (orientation: portrait) {
  video::cue {
    color: green;
  }
}
```

So if this wasn't possible to style (and these `:fullscreen` and `::cue` are not possible via Javascript (they all live in the shadow DOM), then I had to go a different direction. 

So I revisited the documents and tried out the [emulated text tracks setting](https://github.com/videojs/video.js/blob/0c081a3520b2776756abf5f7ad8a7310ade59995/docs/guides/text-tracks.md#emulated-text-tracks). However, I tried turning them off, but that setting was simply not respected in Safari. 

I tried passing this programmatically into our application code, which didn't work
```
{
  html5: {
    nativeTextTracks: false
  }
}
```

I also tried passing it through the `data-setup` in the `video` element in my minimally reproducible example ([as demonstrated here with the Elephant's dream example](https://github.com/videojs/video.js/blame/0c081a3520b2776756abf5f7ad8a7310ade59995/docs/examples/elephantsdream/index.html#L20)), also to no avail

```
<video
  data-setup="{ 'html5' : { 'nativeTextTracks' : false } }"
  playsinline
>
```
At this point, I'm sort of lost - I think I might try looking through the source later to see if I can pinpoint the issue - but I was wondering if this is a Safari specific issue? It seems strange that we can switch text tracks and use emulated text tracks in desktop browsers, but we can neither (a) switch them off, nor (b) make the emulated text tracks show up in iOS Safari? 

Would you be able to point me to the part of the code so I could perhaps take a closer look? 🤔 (Might very well be something weird in our application code as well, just want to cover what I can.)

While I'd like to provide a sample of the captions, in our streams, captions are encoded into each `.ts` video segment, so I don't have any data. I do know for a fact that they conform to the `CEA-608` standards. (That said, it's interesting that this problem doesn't appear with the Elephant's dream `hls` example (https://videojs.com/advanced?video=elephantsdream) - I did see one difference being the Elephant's dream stream sends captions over separately in `.vtt` files, so I wonder if it's something specific to `CEA-608`. 

That said, for legacy reasons, we're unable to migrate to a different format of captions, so I'll have to try to clamp down on it on the client side (it's still strange that `nativeTextTracks` wouldn't work in iOS Safari, right?). 

I will double check our application code to see that there's no iOS specific logic - I didn't author the video portion of it and it's entirely possible might have missed something. 

Thanks again for jumping in, I really appreciate it! I'll try to provide a minimal example (but I have to check with the team first because it uses one of our own streams - since I can't seem to reproduce the captions bug with the Elephant's Dream `hls` stream).

**Comment by gkatsev** [comment]
Ah, if they're 608 captions then they're always handled by Safari/iOS natively. On desktop safari if you set overrideNative it will be our emulated tracks and our playback engine, but we don't recommend that. On iOS, it's not possible to do so.
This stream has 608 captions embedded, so, you can try select that track and see whether it looks right for you or not https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8.

**Comment by BaggioWongHK** [comment]
Ah I see! That's really interesting, and also hard to find information on. Yes! `overrideNative` works as expected in Desktop Safari but not in iOS Safari, and there's been no problem so far. 👍 

Thanks for sharing the `m3u8` file to test out! I had a closer look, and it seems like the `.m3u8` manifest file is structured differently than our manifest files - if I'm not mistaken, copying directly from 

https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

the below means that the subtitle tracks live in a separate file 

```
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE="en",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog, public.accessibility.describes-music-and-sound",URI="subtitles/eng/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English (Forced)",DEFAULT=NO,AUTOSELECT=NO,FORCED=YES,LANGUAGE="en",URI="subtitles/eng_forced/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Français",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,LANGUAGE="fr",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog, public.accessibility.describes-music-and-sound",URI="subtitles/fra/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Français (Forced)",DEFAULT=NO,AUTOSELECT=NO,FORCED=YES,LANGUAGE="fr",URI="subtitles/fra_forced/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Español",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,LANGUAGE="es",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog, public.accessibility.describes-music-and-sound",URI="subtitles/spa/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Español (Forced)",DEFAULT=NO,AUTOSELECT=NO,FORCED=YES,LANGUAGE="es",URI="subtitles/spa_forced/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="日本語",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,LANGUAGE="ja",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog, public.accessibility.describes-music-and-sound",URI="subtitles/jpn/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="日本語 (Forced)",DEFAULT=NO,AUTOSELECT=NO,FORCED=YES,LANGUAGE="ja",URI="subtitles/jpn_forced/prog_index.m3u8"
```

English for example, has a manifest file 

https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/subtitles/eng/prog_index.m3u8

which in turn, points to 

https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/subtitles/eng/fileSequence0.webvtt
https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/subtitles/eng/fileSequence1.webvtt
https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/subtitles/eng/fileSequence2.webvtt

etc., whose styling information is respected in Safari without any modifications

```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

00:01:01.000 --> 00:01:03.000
English subtitle 1 -Unforced- (00:01:01.000)

00:01:03.000 --> 00:01:05.000
<i>English subtitle 2 -Unforced- (00:01:03.000)</i>
<i>Italics</i>

00:01:05.000 --> 00:01:07.000
<b>English subtitle 3 -Unforced- (00:01:05.000)</b>
<b>BOLD</b>
```

Our stream manifest looks more like this

```
#EXTM3U
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p30",NAME="720p30",AUTOSELECT=YES,DEFAULT=YES,VIDEO="720p30"
#EXT-X-STREAM-INF:TYPE=VIDEO,BANDWIDTH=2400000,CODECS="avc1.4D401F,mp4a.40.2",PROGRAM-ID=1
/2582e8dc-a23c-4fbc-b253-87b5029db73b_lvs.2582e8dc-a23c-4fbc-b253-87b5029db73b_2747137297_171760817/720p30/index.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p30",NAME="480p30",AUTOSELECT=YES,DEFAULT=YES,VIDEO="480p30"
#EXT-X-STREAM-INF:TYPE=VIDEO,BANDWIDTH=900000,CODECS="avc1.4D401F,mp4a.40.2",PROGRAM-ID=1
/2582e8dc-a23c-4fbc-b253-87b5029db73b_lvs.2582e8dc-a23c-4fbc-b253-87b5029db73b_2747137297_171760817/480p30/index.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="360p30",NAME="360p30",AUTOSELECT=YES,DEFAULT=YES,VIDEO="360p30"
#EXT-X-STREAM-INF:TYPE=VIDEO,BANDWIDTH=600000,CODECS="avc1.4D401F,mp4a.40.2",PROGRAM-ID=1
/2582e8dc-a23c-4fbc-b253-87b5029db73b_lvs.2582e8dc-a23c-4fbc-b253-87b5029db73b_2747137297_171760817/360p30/index.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="160p30",NAME="160p30",AUTOSELECT=YES,DEFAULT=YES,VIDEO="160p30"
#EXT-X-STREAM-INF:TYPE=VIDEO,BANDWIDTH=120000,CODECS="avc1.4D401F,mp4a.40.2",PROGRAM-ID=1
/2582e8dc-a23c-4fbc-b253-87b5029db73b_lvs.2582e8dc-a23c-4fbc-b253-87b5029db73b_2747137297_171760817/160p30/index.m3u8
```

and the there are no `.vtt` files sent over the network - my understanding is that they're embedded directly into each `.ts` segment itself. 

I did have luck bringing the blown up font size under control via webkit pseudo styles that Safari respects

Before

<img width="296" alt="Screen Shot 2020-10-30 at 12 57 41 AM" src="https://user-images.githubusercontent.com/28295117/97674536-efeb2800-1a4a-11eb-8c86-ed4b032489bd.png">

After

<img width="496" alt="Screen Shot 2020-10-30 at 12 50 53 AM" src="https://user-images.githubusercontent.com/28295117/97674162-4ad04f80-1a4a-11eb-8264-83f750b82865.png">

```
:global(video::cue) {
        font-size: 0.7em;
}
        
:global(video::-webkit-media-text-track-display) {
        min-width: unset;
        max-width: 60%;
        width: auto;
        margin: auto;
        
        left: 0;
        right: 0;
        top: 90%;
        
        font-size: unset;
        text-align: center;
}
```

Unfortunately, I ran into one final barrier - there was a `div` in the shadow DOM containing the `<video>` that's selectable by `::-webkit-media-text-track-display-backdrop` that superimposes styles - because they're all `!important`, it's impossible to override (I guess Apple does like to maintain a consistent look and feel lol). 

![Image from iOS (1)](https://user-images.githubusercontent.com/28295117/97673912-cd0c4400-1a49-11eb-8c2b-8b4ae6da5f5e.jpg)

There was also another issue where the text tracks were appeared twice overlapping each other (but I honestly think that's to do with how Safari interprets the captions, not sure what else can be done). 

<img width="496" alt="Screen Shot 2020-10-30 at 12 52 21 AM" src="https://user-images.githubusercontent.com/28295117/97674176-50c63080-1a4a-11eb-862d-b772f59b4c10.png">

I don't know at this point what else can be done, but wanted to share in case anyone runs into a similar issue. What do you think @gkatsev?

**Comment by BaggioWongHK** [comment]
I'm closing the issue because strictly speaking, this isn't an issue to do with `video.js` - I think it's a Safari / Webkit engine issue (the cause of this is predefined styles that I presume are imposed by WebCore to match the style of the settings in 

```
Accessibility --> Subtitles and Captioning --> Style
```

Unfortunately, some styles, like `padding` can't be overridden because they have the highest level of specificity with the `!important` operator. I filed an issue to Apple, but I think I'll have more luck re-filing that issue on the consumer side, not on the developer side. Adding here for reference: https://developer.apple.com/forums/thread/664954. 

Thanks again for your help @gkatsev!

**Comment by gkatsev** [comment]
The bipbop url has in-manifest tracks but it also has 608 captions as well (if you select `cc1` from the menu it's a 608 track).
But yeah, apple provides override capabilities for users which may or may not conflict with authored styles.

**Comment by BaggioWongHK** [comment]
That's interesting - I was only able to see the different language tracks in Safari (Desktop and iOS)

![Image from iOS (2)](https://user-images.githubusercontent.com/28295117/98034834-76499600-1dcc-11eb-926e-913f7a8bfa9b.jpg)

<img width="730" alt="Screen Shot 2020-11-03 at 11 59 35 AM" src="https://user-images.githubusercontent.com/28295117/98034847-7b0e4a00-1dcc-11eb-8fb2-0f8427256a1f.png">

though I was able to see `CC1` in Firefox

<img width="730" alt="Screen Shot 2020-11-03 at 12 03 43 PM" src="https://user-images.githubusercontent.com/28295117/98034966-a42eda80-1dcc-11eb-9459-5ded491e3c22.png">

But I guess the user settings have the highest privilege, I don't think there's anything we can do about that 🤷‍♂️

**Comment by gkatsev** [comment]
Interesting, yeah, not sure why it's not showing up in Safari, though, that's a whole other issue 😆
