### ISSUE TITLE
use js error

### ISSUE THREAD

**Issue by xianwu24** [videojs/video.js#6908]
## Description
Briefly describe the issue.
I use it in Magento and report the following error. Does anyone know how to use it in Magento

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
![微信图片_20201024093349](https://user-images.githubusercontent.com/26613246/97064884-1852cc80-15dc-11eb-94d8-ac3ce7d2fd03.png)

![微信图片_20201023175324](https://user-images.githubusercontent.com/26613246/96989731-ae451380-1558-11eb-9361-12ad2c096a37.png)

### Expected
How to solve this problem

**Comment by xianwu24** [comment]
Can anyone help me?

**Comment by KayakinKoder** [comment]
I'd recommend editing the "description" of this issue, and actually including a reduced test case. The description of your issue currently has just copy/pasted the template for creating an issue. In general, you'll need to include a lot more information :)

**Comment by xianwu24** [comment]
> 我建议编辑此问题的“描述”，并实际上包括简化的测试用例。您问题的描述当前仅复制/粘贴了用于创建问题的模板。通常，您需要包括更多信息：）

I have updated it, you can help to see, if there are other suggestions, please put forward
