### ISSUE TITLE
playlist.m3u8 with no streams causes overflow of active connections to streaming server

### ISSUE THREAD

**Issue by TheRealMattLear** [videojs/video.js#6910]
## Description

We've discovered an issue occurring specifically when attempting to load a playlist.m3u8 file that contains no streams. This occurs specifically through Wowza Streaming Engine when using transcoder with ngrp and there is no stream online.

If you contact me directly i can provide the server environment using WSE for testing.

## Steps to reproduce

1. Create a Live application in Wowza Streaming Engine, enable transcoder and link to the stream group playlist.m3u8 file. When the stream is offline, you will note the file contains only the following:
```
#EXTM3U
#EXT-X-VERSION:3
```

2. Use standard VideoJS embed code pointing to this file:
```
<!-- Paste the following into the <head>  -->
<link href="https://unpkg.com/video.js@7/dist/video-js.min.css" rel="stylesheet">
<!-- Paste the following into the <body> -->
<video id="videojs" class="video-js vjs-fluid vjs-default-skin vjs-big-play-centered" controls preload="auto" autoplay muted fluid="true" >

    <source src="https://testserver.com:1935/mcptest/ngrp:mcptest_all/playlist.m3u8" type="application/x-mpegURL">
    <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
</video>
<script src="https://unpkg.com/video.js@7/dist/video.min.js"></script>
<script type="text/javascript">
    var player = videojs('videojs');
</script>
```
3. Open the player in your browser and press play

## Results

Connections count in Wowza Streaming Engine continually grows, without ever decreasing until the browser tab containing the HTML code is closed

### Expected

Older connections should disconnect and connections count should not be growing continuously.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs

Tested in VideoJS 7.3.0 and latest @7

#### browsers
Tested in Chrome Browser

#### OSes
Windows

### plugins

No additional plugins

**Comment by gkatsev** [comment]
Looks like this is similar to the issue outlined here https://github.com/videojs/http-streaming/issues/975
