### ISSUE TITLE
Is videojs-contrib-hls still required to set live stream videoplayers up? Uncaught TypeError issue

### ISSUE THREAD

**Issue by pstascavage** [videojs/video.js#6913]
I'm running into "videojs-contrib-hls.js?DEC-VER=6.12.0.64871:3957 Uncaught TypeError: Cannot read property 'EventTarget' of undefined" while attempting to initiate a video element then load videojs to it. 

`
MyControl.prototype.initialize = function(host, component){
  try {
/*Here we load our libraries. We must load it this way because of the way we integrate javascript into the no code solution*/
   $.when(
     $DP.ScriptLoader.LoadScript(
       virtualPath + "/scripts/FormControls/jsFiles/videojs.js"
     )
    ) 
   
 
   $.when(
     $DP.ScriptLoader.LoadScript(
       virtualPath + "/scripts/FormControls/jsFiles/videojs-contrib-hls.js"
     )
    )

   

  // Here we assign 'host' to a variable on this control,
    //   so that we can access it later:
  this.host = host;
  
  

  // Create and configure the video elemnt:
  var video = document.createElement('video');
  video.setAttribute("id","videoplayer");
  video.setAttribute("class","video-js vjs-default-skin");
  
 
  // Add the video to the 'host' jquery object:
  host.append(video);
  //Gets the source and plays on our video element previosuly made. Dependant on Libraries. When not commented out, breaks the form.
  const player = videojs('videoplayer');
    player.src({
      src: 'http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8',
      type: 'application/x-mpegURL'
    });} catch (ignore) {}
  
 };
`

**Comment by mister-ben** [comment]
If you are using an up-to-date version of Video.js you should not use videojs-contrib-hls. It was succeeded by videojs/http-streaming, which is included in the default build of Video.js 7.x.

**Comment by pstascavage** [comment]
Thanks @mister-ben  I found out more about that doing some research last night!
