### ISSUE TITLE
jQuery.Deferred exception: videojs is not defined ReferenceError: videojs is not defined

### ISSUE THREAD

**Issue by pstascavage** [videojs/video.js#6916]
**Description**
Getting a "videojs is not defined" error while trying to run script which makes the video element. I've found work arounds that involve the following:

import videojs from 'video.js';
window.videojs = videojs;
require('videojs-http-source-selector');

The issue being, import isn't supported in the module I'm building in (a no code solution. This is a form component). I use a script loader to load the library file. You can see this in the below Jfiddle file. 

Is there a way to work around this without the import?

**Steps to reproduce**
Explain in detail the exact steps necessary to reproduce the issue.
JSFiddle Code: https://jsfiddle.net/pstascavage/Lky3bteg/

**Actual**
JS hits exception revolving around undefined videojs, probably around being unable to use the import mentioned above.

**Error output**
Query.Deferred exception: videojs is not defined ReferenceError: videojs is not defined

**Additional Information**
Please include any additional information necessary here. Including the following:
what version of videojs does this occur with? - 7.9.7

**browsers**
Chrome

**OSes**
Windows 10

**plugins**
no plugins

**Comment by gkatsev** [comment]
Unfortunately, I couldn't get the jsfiddle to work to show the issue. Can you update it so that we can see the error?

You can definitely use Video.js in a script on a page but you want to use the built version, for example https://unpkg.com/videojs/dist/video.js or from our cdn https://vjs.zencdn.net/7.9/video.js.
