### ISSUE TITLE
Streaming Issue Post Bump from version 7.8.4 to 7.9.0

### ISSUE THREAD

**Issue by feliperobledo** [videojs/video.js#6919]
## Description

Hello. I'm experiencing a very strange issue streaming after bumping to version >= 7.9.0. I'll try to describe it as best I can.

Our web page has a mechanism to keep track of where you last left off watching a video. We use `player.currentTime` to set the current playback time from a value we have stored on local storage.

However, for streamed videos on desktop browsers **except Safari**, we see the following:
- I load a video for the first time. Say it is 9 minutes.
- I watch some of it, even seek through the contents.
- I reload the page when the marker says I've watched 4 minutes and maybe 5 minutes have been buffered.
- When the page reloads, the UI now shows the video is 5 minutes long, not 9. Because we set the time with `player.currentTime`, the progress bar shows that the user has watched 4 out of 5 minutes. I would expect the content to playback from where the user left off,  but instead the content that starts playing is actually relative to the new % the UI says that has been watched, so in this case the content played back is from minute 7.2 (4/5 of 9 minutes).

Again, this doesn't happen on **Safari**. 

## Steps to reproduce
I can't really describe concrete steps to reproduce this issue. I tried reloading the docs pages for video.js like I described above, but I think the bug is a mixture of our code + some of the changes introduced in version 7.9.0.

### Expected

When I reload the page of  a video in our domain that I am currently playing, the video should playback from where it left off and the player to not truncate the length.

### Actual

Upon reload of a page:
- The player truncates the video length (possibly to the current time + the offset that has been buffered)
- The video plays back from further ahead

### Error output
None that I can see in the console.

## Additional Information

In Chrome, I can see the browser making tons of request:
<img width="456" alt="chrome_loads_1st_then_rest_of_hls" src="https://user-images.githubusercontent.com/6238302/97640492-1afb5a80-19fe-11eb-816b-e91b19f55f67.png">
What's weird is that we first make a request to the first part, and then we make a request for all other missing parts between the last playback and the video's end.

Safari is much more civilized. It loads only a few frames from the buffer:
<img width="708" alt="safari_loads_only_handful_of_hls" src="https://user-images.githubusercontent.com/6238302/97640606-5eee5f80-19fe-11eb-9068-9d2e1fc53408.png">
It doesn't even load the first one, like Chrome does.

Furthermore, as we are rolling out subtitles, I've noticed that subtitles do seem to playback relative to the timestamp that is advertised. 

#### videojs

`>= 7.9.0`

#### browsers

Chrome

#### OSes

macOS

### plugins

[videojs-offset](https://github.com/cladera/videojs-offset)

**Comment by feliperobledo** [comment]
**update**: I've managed to isolate the issue to the code from the only plugin we use: [videojs-offset](https://github.com/cladera/videojs-offset/blob/master/src/plugin.js). When I remove the plugin, everything works as expected on chrome. I guess the problem we are experiencing is a combination of changes on how `currentTime` works internally in version >= 7.9.0 of `video.js` and the assumptions the plugin makes. And in that case, I'm not sure how to tell who is in the right 😅

**Comment by feliperobledo** [comment]
For the record, I removed our only plugin (`videojs-offset`), and that only made matters worst. Originally, when we reload the page twice, the video's current time resets to 0 on the second reload. Without `videojs-offset`, reloading the page only sets the current time to 0 when the reload happens on a video that is done playing back.

**Comment by feliperobledo** [comment]
As described in the issue, we have functionality that sets `currentTime` based on the time the user left off from when they last watched the video. When I remove this functionality, and in particular the call to set `currentTime` we no longer have issues streaming.
Just a reminder that the issue does not happen on **Safari**.

**Comment by gkatsev** [comment]
In Safari, we let Safari handle playback of HLS video, so, that would explain the difference there.
Are you able to share a test page with us? (You can message me privately on slack or via email if that's doable too). Creating a reduced test case may help track down the issue as well.

**Comment by feliperobledo** [comment]
@gkatsev I'll get back to you about the test page. I'll ping you directly.

**Comment by feliperobledo** [comment]
We bumped video.js to `7.11.8` recently, and since we haven't had this issue happen anymore.

**Comment by gkatsev** [comment]
Thanks, great to hear!
