### ISSUE TITLE
Feature Request: single step one frame forward (and if possible, one frame backward too!)

### ISSUE THREAD

**Issue by nick-name** [videojs/video.js#692]
Add a "single step frame forward" button, that advances until the next frame, and pauses on it.

(The way that I'm aware that should work is to keep updating the the time forward by e.g. 1ms, until the picture changes somehow - but I'm not sure if there's a better way)

It would be awesome if there would also be a way to step backwards.

Another way to support this is to have an auxiliary file that gives the timestamp of every frame, and then we look up the current time, determine the frame, find the time of prev/next frame, and seek there.

I can contribute that as a plugin, but perhaps there's something I'm missing that makes it much easier to implement with help from the main videojs code?

Will what I suggest work on both flash and html5? I have no experience with flash.

**Comment by goutamdh** [comment]
Hi sir there is bug in videojs.min.js ? im using angular and electron js.
