### ISSUE TITLE
Click the video on the mobile terminal and cannot pause and play

### ISSUE THREAD

**Issue by pxim** [videojs/video.js#6923]
## Description
Click the video on the mobile terminal and cannot pause and play.
It is ok on PC.

## Steps to reproduce
1.Click the video on the mobile terminal 

### Expected
Click the video on the mobile terminal and can pause and play.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.10.1
#### browsers
what browser are affected?
chrome 73.0.3683.68
#### OSes
what platforms (operating systems and devices) are affected?
ios 13.4.1
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Tapping the video on mobile toggles the display of the controls, as there is no mouseover. Is that what you mean?

**Comment by pxim** [comment]
> Tapping the video on mobile toggles the display of the controls, as there is no mouseover. Is that what you mean?

![image](https://user-images.githubusercontent.com/5111701/99329166-9b540380-28b8-11eb-90da-fb693f93f48e.png)
Through this method, I solved the problem temporarily.
Thanks
