### ISSUE TITLE
rollup-plugin-progress needs to be updated to 1.1.2

### ISSUE THREAD

**Issue by danrossi** [videojs/video.js#6924]
In my Node version I get this error when building. It needs to be updated to 1,1.2 to get this fix

https://github.com/jkuri/rollup-plugin-progress/pull/18

**Comment by gkatsev** [comment]
Looks like it's a node 14 issue.
We generally only run and test with LTS versions of Node, though, I guess node 14 was just promoted to LTS. We'll check it out soon.

**Comment by gkatsev** [comment]
Closed by https://github.com/videojs/video.js/commit/90f3e39b3314d716e0df3092051a426f9d478b62
