### ISSUE TITLE
No audio when playing HLS after upgrade to 7.10.x

### ISSUE THREAD

**Issue by tiberiuana** [videojs/video.js#6931]
## Description

After upgrading from 7.8.4 to 7.10.2, our HLS videos are not playing audio in most browsers.

## Steps to reproduce

Please see test video here: http://videojs-7.10-bug.surge.sh

Play *certain* HLS videos, that used to work in 7.8, in 7.10. This does not seem to affect all HLS videos. I tried other HLS streams online and they worked fine.

I was unable to determine what exactly about our files causes the problem. 

### Expected
Video and audio play normally.

### Actual
Audio is missing. 

### Error output
No errors in console.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.10.2
#### browsers

All browsers below, except Safari, have normal video and sound on Video.js 7.8.4.

On Video.js 7.10.x:

- Chromium 85.0.4183.83, Linux  
video: yes, sound: no

- Firefox 81.0, Linux  
video: yes, sound: no

- Edge 80.0.361.109, Windows  
video: no, sound: yes (!!)

- Edge: 86.0.622.63, Windows
video: yes, sound: no

- Safari 14.0 (15610.1.28.1.9, 15610, macOS  
video: no, sound: no
(Safari plays only sound, but no video, even with Video.js 7.8.4, so that is probably an unrelated codec issue)

### plugins
No plugins or extra options used.

**Comment by gkatsev** [comment]
Looks like this should be fixed in Video.js 7.11. This was likely fixed with https://github.com/videojs/http-streaming/pull/981

**Comment by LanceUMatthews** [comment]
I have been experiencing a similar (but opposite) problem, though with a couple twists:
- v7.8.4, hosted locally, worked fine...until it didn't.  I didn't change anything, and yet somehow my very simple 1 video variant + 1 audio variant segmented fMP4 stream went from both video and audio working to **audio but no video**.  Upgrading to v7.10.2 made no difference, though I found that configuring that with...
  ```javascript
  html5: {
      vhs: {
          enableLowInitialPlaylist: true
      }
  }
  ```
  ...would invert the problem to **video but no audio** that stalls indefinitely after the first two segments.  For a time, setting [`bandwidth`](https://github.com/videojs/http-streaming#bandwidth) to the full playlist bitrate had the same inversion effect, but I'm not able to reproduce that any more.  I tested and experienced this all on...
  - Windows 10: vChrome 87.0.4280.66, Edge v87.0.664.47, and Firefox v83.0
  - Debian Linux v10.5.0 Buster: Firefox v68.10.0 ESR
- Safari for OSX (unknown version) and Firefox for Android v83.1.0 work fine with both versions.  Chrome for Android I don't think I've ever gotten to work, which I believe is to be expected(?).

**Comment by LanceUMatthews** [comment]
> for chrome for android make sure that you're setting `overrideNative: true` or maybe to `!videojs.browser.IS_ANY_SAFARI`.

Yes, I have been using `!videojs.browser.IS_EDGE && !videojs.browser.IS_ANY_SAFARI`.

> As for playback, can your stream have changed?

The content of the stream changes regularly but the source video format and the way I encode it has not.

> I would try with Video.js 7.11 and see if things have improved.

With v7.11.0 clicking the play button just results in a spinning circle.

> Otherwise, if you can share your stream it would make it easier to help out.

I have created a minimal example at [https://lanceumatthews.github.io/HLS_Test/](https://lanceumatthews.github.io/HLS_Test/) that behaves the same as my stream:

| Browser/Video.js Version | v7.8.4 | v7.10.2 | v7.11.0 |
| ------------------------- | ------ | -------- | ------- |
| Chrome v87.0.4280.88 for Windows | Audio only | Audio only | Spinning circle |
| Chrome v87.0.4280.86 for Android | **See error below** | Audio only | Spinning circle |
| Edge v87.0.664.55 for Windows | Audio only | Audio only | Spinning circle |
| Firefox v83.0 for Windows | Audio only | Audio only | Spinning circle |
| Firefox v83.1.0 for Android | **Video + audio** | Audio only | Spinning circle |

All of those "Audio only" fields for v7.8.4 were working for me as recently as a month ago.  Chrome for Android gives the following error with v7.8.4:

> The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

Enabling `enableLowInitialPlaylist` changes the results to this:

| Browser/Video.js Version | v7.8.4 | v7.10.2 | v7.11.0 |
| ------------------------- | ------ | -------- | ------- |
| Chrome v87.0.4280.88 for Windows | Audio only | Video only | **Video + audio** |
| Chrome v87.0.4280.86 for Android | **See error above** | Audio only | **Video + audio** |
| Edge v87.0.664.55 for Windows | Audio only | Video only | **Video + audio** |
| Firefox v83.0 for Windows | Audio only | Video only | **Video + audio** |
| Firefox v83.1.0 for Android | **Video + audio** | Video only | **Video + audio** |

That flips all but one of the "Audio only"s to "Video only" for v7.10.2, and makes _everything_ work with v7.11.0.  That would seem to be my fix right there, but the question is, why is setting `enableLowInitialPlaylist` now necessary?

**Comment by blacktrash** [comment]
Could be related to the fact that both stream1.m3u8 and stream3.m3u8 throw a 404 not found.

**Comment by gkatsev** [comment]
With `enableLowInitialPlaylist` we choose the lowest video/mixed rendition available. Without it, we choose the rendition that closest matches 0.5MBps, in this case it'll be the audio only rendition. Video.js 7.11 should be able to play this back (with videojs/http-streaming#981), I'm not sure why it isn't. However, you'd still be stuck in audio-only mode in that case.

**Comment by tiberiuana** [comment]
Closing this because I tried my test case again with the latest 7.11.4 and everything works again as expected.
