### ISSUE TITLE
Vertical Volume Slider not work with custom skin

### ISSUE THREAD

**Issue by decastpro** [videojs/video.js#6932]
### ## Description

Hello Guys. I have issue with vertical volume slider enabling with my custom skin.
it's work with default videojs skin, but not with mine..
Can you help me to solve this, issue.it's been a while now-i have tried many ways & many times.So, any help i am appreciate.

Code pen link with custom skin: [Link ](https://codepen.io/sportex-holdings/pen/MWeqaOz)

Code pen link with default video js  skin: [Link](https://codepen.io/sportex-holdings/pen/zYBJvmg)

Thanks!

 **I am using videojs 7.10.2 js lib.**

**Comment by gkatsev** [comment]
Hey, looks like both of the codepens you posted aren't working.

**Comment by decastpro** [comment]
Hi!,Thanks! ,for your response..I figured it out...
