### ISSUE TITLE
Build serve is not working

### ISSUE THREAD

**Issue by baligithub** [videojs/video.js#6933]
## Description
Briefly describe the issue.
I have downloaded the code and ran npm i all works

but running npm build serve is not running the application.
Please advise.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. how to run the downloaded code.
2.I am running command npm build serve and it is not running
3.

### Expected
videojs downloaded code should run.

### Actual
Please describe what actually happened.

### Error output
In attached

## Additional Information
Please include any additional information necessary here. Including the following:
[error-logs.txt](https://github.com/videojs/video.js/files/5504242/error-logs.txt)

#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by baligithub** [comment]
I also tried npm test. It gives me error in attached.
Please advise
[error-logs2.txt](https://github.com/videojs/video.js/files/5504244/error-logs2.txt)

**Comment by gkatsev** [comment]
hey, looks like we don't yet work with node 14. Please try using node 12 (we recently switched the nvmrc file to point at 12 as well). We'll fix it up with node 14 support soon.

**Comment by gkatsev** [comment]
Closed by https://github.com/videojs/video.js/commit/90f3e39b3314d716e0df3092051a426f9d478b62
