### ISSUE TITLE
cannot catch error on error event

### ISSUE THREAD

**Issue by mraiguo** [videojs/video.js#6934]
## Description
I want to be able to do something with the error message when something goes wrong.
But in this case I can't get the error message.  

[![BIkBss.png](https://s1.ax1x.com/2020/11/07/BIkBss.png)](https://imgchr.com/i/BIkBss)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Using the wrong video source
2. Listen for error events or try catch the code 
```
player.on('error', function(err) {
  console.log(err)
})

try {
  // videojs code
} catch(e) {
  console.log(e)
}
```

### Expected
can see the same error message as the picture above

### Actual
get this error info
![img](https://i.loli.net/2020/11/07/mVhvkBljrJUyf2I.png)

**Comment by mister-ben** [comment]
The error event doesn't contain error information currently, but `player.error()` returns the last error. You can do this:

```
player.on('error', function() {
  console.log(player.error());
}
```
