### ISSUE TITLE
novtt builds including external file "https://vjs.zencdn.net/vttjs/0.14.1/vtt.min.js"

### ISSUE THREAD

**Issue by fmonts** [videojs/video.js#6935]
Is this file needed in the novtt versions? 
By its name I wouldn't say so. Can these 2 lines be removed?

    var script = document.createElement('script');
    script.src = this.options_['vtt.js'] || 'https://vjs.zencdn.net/vttjs/0.14.1/vtt.min.js';

Considering that it's only 7kb, I'd bundle it with the package anyway to improve efficiency, it's not worth the time spent to dns resolve, connection and https handshaking, to include just one file on a third party origin.

![image](https://user-images.githubusercontent.com/8755314/98462270-c012f180-21bb-11eb-929c-adefbf6043a4.png)

**Comment by fmonts** [comment]
The doc says this:

> vtt.js  Type: string
> Allows overriding the default URL to vtt.js, which may be loaded asynchronously to polyfill support for WebVTT.
> This option will be used in the "novtt" build of Video.js (i.e. video.novtt.js). Otherwise, vtt.js is bundled with Video.js.

But I don't understand the reason. If I'm using a novtt version, it means I don't want to use any webvtt functionality... why loading that file?

**Comment by gkatsev** [comment]
The novtt build is probably badly named. That build's purpose is to not bundle vttjs directly with Video.js and have it be loaded separately. The main builds of Video.js includes vtt.js.
It does make sense that if `vtt.js` is set to `false` we don't load vtt.js at all or something. We'd also need to make sure that other caption functionality doesn't cause video playback to fail if this is done and a video with captions is played.
Would you be interested in adding this in?
