### ISSUE TITLE
 Cannot set property HlsHandler of function Ka(e,t,i){var n=Ka.getPlayer(e);if(n)return t&&qe.warn('Player "'+e+'" is already initialised. Options...<omitted>...n} which has only a getter

### ISSUE THREAD

**Issue by wf0206** [videojs/video.js#6936]
Cannot set property HlsHandler of function Ka(e,t,i){var n=Ka.getPlayer(e);if(n)return t&&qe.warn('Player "'+e+'" is already initialised. Options...<omitted>...n} which has only a getter

**Comment by gkatsev** [comment]
Can you provide more information about what you're doing that you're getting this issue? A reduced test case would be immesibly helpful.

**Comment by amrit-codebuckets** [comment]
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import videojs from 'video.js';
import 'video.js/dist/video-js.css';
// import videoJsContribHls from 'videojs-contrib-hls';

// videojs.registerPlugin(
//     videoJsContribHls
// );

// import 'videojs-contrib-hls/dist/videojs-contrib-hls.js';
// Workaround for webworkify not working with webpack
window.videojs = videojs;
require('videojs-contrib-hls/dist/videojs-contrib-hls.js');

class VideoPlayer extends Component {
    startVideo(video) {
        videojs(video);
    }
    
    render() {
        return (
                <video ref={this.startVideo} width={600} height={600} className="video-js vjs-default-skin" controls>
                    <source src={this.props.video} type="application/x-mpegURL" />
                </video>
        );
    }
}

VideoPlayer.propTypes = {
    width: PropTypes.string.isRequired,
    height: PropTypes.string.isRequired,
    source: PropTypes.string.isRequired,
};

export default VideoPlayer;

**Comment by amrit-codebuckets** [comment]
and I am getting this error

×
TypeError: Cannot set property HlsHandler of function videojs$1(id, options, ready) {
  var player = videojs$1.getPlayer(id);

**Comment by arbisyarifudin** [comment]
> and I am getting this error
> 
> ×
> TypeError: Cannot set property HlsHandler of function videojs$1(id, options, ready) {
> var player = videojs$1.getPlayer(id);

uh.. im gettting this error too..

**Comment by jws2003** [comment]
> > and I am getting this error
> > ×
> > TypeError: Cannot set property HlsHandler of function videojs$1(id, options, ready) {
> > var player = videojs$1.getPlayer(id);
> 
> uh.. im gettting this error too..

ME TOO,anyone can tell us why?

**Comment by jiyarong** [comment]
same here

**Comment by xiaofang11** [comment]
也遇到了这个问题，有没有解决方案

**Comment by hutufairy** [comment]
> 也遇到了这个问题，有没有解决方案

可以试着卸载 `@videojs/http-streaming` 
video.js 7.x包含了这个库: [https://blog.videojs.com/video-js-7-is-here/](https://blog.videojs.com/video-js-7-is-here/)

**Comment by Anush-TFT** [comment]
Did any one found any solution?
