### ISSUE TITLE
I'm not able to speed up this website video

### ISSUE THREAD

**Issue by lawr3nce4u** [videojs/video.js#6937]
## Description
There is a website (which is not mine) that has a playlist of videos which are streamed through videojs. I'd want to skip this playlist and get into stream of the next playlist. However, when I try to speed up/fast-forward the video speeds up but it pauses and changes (I think it doesn't save the last video minute the user has played) don't get saved when I reload the page. When I try to set a new video position the video rewinds (and start from the 0:00 minute), so basically changes aren't saved.
Video controls (to skip and other) are disabled.

All I can do is starting the video, pausing the video, backing the video for 10 seconds, rewinding the video and full-screen. 

## Steps to reproduce
I get into the video streaming page and open Firefox Console. Then I launch a simple `document.querySelector('video').playbackRate = 2.0;`, video gets faster but then it stops (and the exact time it stops I get the following `TypeError: The expression cannot be converted to return the specified type. 2 video.js:10958` error).

### Expected
Video speeds up or its position gets changed without any problem (I don't want it gets pause or other), and **also the minute the user was at (with the speed up or minute-change trick) should persist at the next page reload**.

### Actual
Video speeds up but it gets paused after a while. I can't seem to change video current time position.

### Error output
`TypeError: The expression cannot be converted to return the specified type. ---- video.js:10958`, [here you can see the website version of videojs](http://loveyoub.altervista.org/code.js), I'm not sure if it's forked or the original code. (I had to host it on my website because the code was way too long)

#### videojs
Video.js 5.17.0 
#### browsers
Firefox, I didn't test on other browsers, but the same result should be expected.
#### OSes
Debian GNU/Linux

Anyone has an idea of why this is happening?

**Comment by gkatsev** [comment]
That version of Video.js is incredibly old. I'm not really sure what's up there. Though, I would recommend using the Video.js player API to change these things instead of interacting directly with the video element. `player.playbackRate(2)` will likely work better.
