### ISSUE TITLE
Fluid mode is not working for HLS videos on mobile Chrome, Safari

### ISSUE THREAD

**Issue by ilyakorman** [videojs/video.js#6939]
## Description
The player fails to keep itself sized to a particular aspect ratio, using the fluid mode, when using HLS video source on mobile Chrome, Safari

## Steps to reproduce

1. Use the code, with 21:9 aspect ratio HLS video as a source

```
<html>

<head>
  <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
  <meta charset="utf-8">
  <title>Video.js Starter Template</title>
</head>

<body>
  <video
         id="my_video"
         class="video-js vjs-fluid"
         controls
         preload="auto"
         data-setup="{}"
         >
 <source src="https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" type="application/x-mpegURL" />
   
  </video>
  <script src="https://unpkg.com/video.js/dist/video.js"></script>
</body>

</html>
```

### Expected
the player should be resized to the video aspect ratio, works on mobile Firefox:
![image](https://user-images.githubusercontent.com/47973395/98706110-1f712d00-2387-11eb-967e-93c557e09022.png)

### Actual
The player is not resized, keeping its original size and leaving black spaces above and below the video on mobile Chrome, Safari:
![image](https://user-images.githubusercontent.com/47973395/98706557-a1f9ec80-2387-11eb-8ccc-1d49f805c7be.png)

![image](https://user-images.githubusercontent.com/47973395/98706713-d9689900-2387-11eb-882b-3cbb14693e36.png)

#### videojs
Latest
#### browsers
Chrome, latest. Safari
#### OSes
Android, iOS
### plugins
none

**Comment by mister-ben** [comment]
It's because the video element reports `0` for the video width and height at `loadedmetadata` so we use the default 16:9 aspect ratio. I thought we updated the player on `resize` events too but apparently not. A workaround would be to set resize to true on `resize` events, `player.on('resize', function() {this.fluid(true)})`
