### ISSUE TITLE
Adaptive Streaming Support

### ISSUE THREAD

**Issue by sprice** [videojs/video.js#695]
Adaptive streaming would allow the player to automatically switch source files to use a different bitrate depending on the speed of the users connection. This would provide an improved experience for users by playing the best quality file possible.

I think we would need to add this to the Flash fallback first, as Media Source Extensions are not in all browsers yet (AFAIK just part of the spec is in Chrome).

**Comment by naveen2245** [comment]
Hi,
 Is there any way to get the bitrate of the videojs  current video played in Mac Safari , iOS Safari and android chrome ?
 I have tried player.tech({ IWillNotUseThisInPlugins: true }).hls.bandwidth which is not working on the above mentioned browsers . I have added <script src="videojs-contrib-hls.min.js"></script>

**Comment by samueleastdev** [comment]
@naveen2245,

If you are using the hls plugin you can get everything you need with this call,
~~~
videoPlayer.on('loadedmetadata', function() {
  
    var player = this;
    console.log("player.tech_.hls", player.tech_.hls);
  

});
~~~

**Comment by bhartendukumar12** [comment]
is there a facility of adaptive bit rate streaming in videojs player for all browsers.
if yes could u pls snd me that part of code responsible for this.
