### ISSUE TITLE
Focus Not Trapped in Caption Settings Dialog

### ISSUE THREAD

**Issue by josephshanak** [videojs/video.js#6950]
## Description
The dialog used for Closed Captioning settings does not trap focus within the dialog contents. 

It seems like this was meant to be fixed as part of #2746 / #4025.
> Keyboard focus is not trapped inside the dialog while it is open

## Steps to reproduce
1. Go to https://videojs.com/advanced/?video=elephantsdream
2. Tab to the Captions Menu
3. Enter the Caption Settings Dialog
4. Tab to the Close button.
5. Tab again.

### Expected
The focus is moved to the first element in the Caption Settings Menu

### Actual
The focus is moved outside of the video player.

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Happens on 7.7.5 and 7.10.2 at least

#### browsers
Firefox, Chrome. Possibly others but untested.

#### OSes
Verified on MacBook Pro running MacOS Catalina 10.15.7

### plugins
Unsure

**Comment by gkatsev** [comment]
Interesting, looks like this is a regression. It worked previously.

**Comment by gkatsev** [comment]
Interestingly, it's still working with tabbing back but not forward.

**Comment by gkatsev** [comment]
Trying it out in various versions, it looks like this broke between v7.5.4 and v7.5.5. My guess is that it was this change https://github.com/videojs/video.js/pull/5969

**Comment by kannapples** [comment]
I created a PR for this issue: https://github.com/videojs/video.js/pull/6983

My fix prevents Tab keydown events from firing the parent `handleKeyDown` function in `close-button.js`. I couldn't think of a reason why you'd want to allow a Tab keydown to escape the context of the container, but I thought I'd call it out jic.
