### ISSUE TITLE
LoadMedia doesn't trigger the emptied event

### ISSUE THREAD

**Issue by amtins** [videojs/video.js#6958]
## Description
When a media is loaded, calling the `loadMedia` function doesn't trigger the **emptied** event.

See [example](https://amtins.github.io/empty-banana-space/)

Code [source](https://github.com/amtins/empty-banana-space/blob/main/index.html)

## Steps to reproduce
The exact steps necessary to reproduce the issue.

1. Create a `videojs` instance
2. Add a listener to the `emptied` event
3. Add a source with `src` or `loadMedia`
4. Finally call `loadMedia` again

### Expected
The **emptied** event should be triggered.

### Actual
The **emptied** is not triggered.

#### videojs
Since [v7.5.0](https://github.com/videojs/video.js/releases/tag/v7.5.0) #5652 #4342

#### browsers
Chrome, Firefox, Safari (works on Safari MacOS)

#### OSes
Linux, Windows, Android, iOS(13/14), MacOS (except for Safari)

**Comment by gkatsev** [comment]
This is likely because `loadMedia` calls `reset()` before setting the new source. This disposes of the old video element and created a new one.

Is there a particular reason why you want the `emptied` event?

**Comment by amtins** [comment]
Thank you @gkatsev for your answer. 

We use this event for statistical purposes only. 

In our case instead of the `emptied` event we could listen to the `playerreset` event, or use the `src`. However, it is unfortunate to lose a standard event coming from HTMLMediaElement and to have a difference in behavior with Safari. What do you think?

**Comment by gkatsev** [comment]
In that can I would probably recommend not using loadMedia and continue using .src. I'm not sure it's worth it for us to trigger an artificial emptied event in `loadMedia`, though, we could.

**Comment by amtins** [comment]
@gkatsev thank you, so then I think we can close this case. Thank you again. 👍🏽

**Comment by gkatsev** [comment]
You're welcome!
