### ISSUE TITLE
Using the media element to grab a MediaElementSource from an AudioContext causes no audio to be played.

### ISSUE THREAD

**Issue by dyc3** [videojs/video.js#6963]
## Description
Trying to pass the audio from a videojs player through an `AudioContext` causes audio to not be played from the video.
Example 1: https://codepen.io/dyc3/pen/MWjYZOq
Example 2: https://codepen.io/dyc3/pen/abmzPje

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Create a video js player with any video that has sound
2. Create an `AudioContext`, and connect the media element to it:
```js
let context = new AudioContext();
let video = document.getElementsByTagName("video")[0];
let node = context.createMediaElementSource(video);
node.connect(context.destination);
```
3. Play the video
4. See that no audio is being played.

### Expected
Expected audio to be passed through the audio context, allowing audio to be played.

### Actual
No audio was played. `createMediaElementSource` succeeds, and connecting it to the audio context's destination succeeds.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.11.0
#### browsers
what browser are affected? 
Firefox, Chrome
#### OSes
what platforms (operating systems and devices) are affected?
Linux, Desktop
### plugins
are any videojs plugins being used on the page? If so, please list them below.
None

**Comment by GeorgesMainville** [comment]
@dyc3 You could try to add `crossorigin='anonymous'` to your video tag. This solved the problem for me.
```
  <div data-vjs-player>
    <video crossorigin='anonymous'className="video-js" />
  </div>
```

**Comment by gkatsev** [comment]
Yeah, pretty sure a crossorigin setting is required for these types of operations.

**Comment by dyc3** [comment]
Looks like that works. Closing
