### ISSUE TITLE
The control bar loses focus when click Mute

### ISSUE THREAD

**Issue by mraiguo** [videojs/video.js#6965]
## Description
(https://codepen.io/mraiguo/pen/jOMPEKz?editors=1000) 

## Steps to reproduce
1. Click the Mute button to mute it
2. Click the up and down buttons on the keyboard

### Expected
up button can increase volume
down button can reduce volume

### Actual
up and down button just scroll the page, lost focus of controlbar

**Comment by gkatsev** [comment]
Being focused on the mute toggle doesn't let you change the volume. You have to be focused on the volume slider for it.
This is either workings as expected or maybe related to https://github.com/videojs/video.js/issues/6862

**Comment by OwenEdwards** [comment]
This is working as expected - up and down arrow keys do not change the volume when focus is on the Mute button, nor do they change the volume when focus is on the Play/Pause button or the Fullscreen button. The control bar definitely doesn't "lose focus" when the Mute button is clicked - focus Moves to the mute button, as expected.

There _is_ a reasonable argument that the volume control should be a single focusable control that implements both the volume slider and the Mute/Unmute functionality, but it is not implemented that way right now.

Alternatively, up and down arrows _could_ be treated as 'hotkeys' in https://github.com/videojs/video.js/blob/main/src/js/player.js#L3169-L3216, and change the player volume if they are pressed while focus is on any control which doesn't do something else with the up and down arrow keys. Again, that _could_ be implemented (to be closer to the functionality of YouTube, for example), but currently isn't.
