### ISSUE TITLE
Video.js seeker highlight color issue

### ISSUE THREAD

**Issue by jimmyScrub** [videojs/video.js#6966]
hi
I've simply used your starter reduced test case on codepen that you've provided to describe the issue I'm having.
(https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0)
After much searching I cannot find which class affects the 'blue' glowing outline that occurs on mobile (iOS) versions of the player seek bar/timeline/ (I'm not sure which) when the user taps on it. This also occurs on the play/pause button and fullscreen button. I don't see this blue outline on desktop - only mobile phone. I would like to completely eliminate this effect. attached is a screen grab from my iPhone
I'm only using Jquery and Javascript (not react) and would like to know where I can change this class or eliminate it on activation with Jquery or Javascript.
I'm using Video.js 7.8.4
loaded in my header like this:
 <script src="https://vjs.zencdn.net/7.8.4/video.js"></script>
 and this stylesheet loaded like this:
link href="https://unpkg.com/video.js@7/dist/video-js.min.css" rel="stylesheet"
thanks
James
 
![seekbar](https://user-images.githubusercontent.com/49075899/100657300-0b807180-331c-11eb-8f33-462c1cf54732.jpg)

**Comment by mister-ben** [comment]
The focus ring is important for some users for accessibility. Rather than trying to remove it which runs the risk of removing it for users who do need it, you can add a polyfill for the `:focus-visible` pseudo-selector for browsers like Safari that don't support it. That hide the focus ring when there's not keyboard interaction.

https://github.com/WICG/focus-visible

**Comment by jimmyScrub** [comment]
hi
Thanks for the quick reply. I'm relatively new to Jquery, HTML and Javascript so please forgive my naive follow up question. Shall I then just install this script on my page and then go find the classes that have 'data-focus-visible' references. 

I noticed a few that exist in the video-js.css that I've managed to find and link to since I wrote my first question that already have implemented this:

(copied from my css):
.js-focus-visible .video-js *:focus:not(.focus-visible) {
  outline: none;
  background: none;
}

.video-js *:focus:not(:focus-visible),
.video-js .vjs-menu *:focus:not(:focus-visible) {
  outline: none;
  background: none;
}

**Comment by jimmyScrub** [comment]
WOW, this worked! THANKS!
my mobile version no longer displays the 'blue' border (Now known to me as 'focus ring'?)
However I had no idea this was an accessibility issue for some users. How can I check if keyboard only users can still access the information on my page now?

**Comment by mister-ben** [comment]
You should be able to just press tab on the page to move the focus and see the focus being applied

**Comment by jimmyScrub** [comment]
I see that working on Mac Chrome ( and on Mac Safari you have to hold Option and Tab )

I’ve discovered several divs that I’ve programmed as menu buttons on some sites I created that the Tab key doesn’t recognize. I’m inspired to fix those.

Thank you very much for your help.
James
