### ISSUE TITLE
official website bug ,"Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by linhaihero** [videojs/video.js#6969]
## Description

Chrome ios mode, I think there is a problem with my code, but the result is the same error even on the official website. . So, what happened, how can I fix it? Thank you...

https://videojs.com/advanced?video=disneys-oceans

![image](https://user-images.githubusercontent.com/8591451/100857877-35769700-34c8-11eb-8f63-c18840d1bce2.png)

**Comment by LongShengWen** [comment]
The same question

**Comment by gkatsev** [comment]
Is this happening on a real device too or just the chrome emulator?

**Comment by ghazalhafezi** [comment]
HI
this is my problem too. on 7.13.4.
can you help me?  @gkatsev

**Comment by SaizFerri** [comment]
Hey @gkatsev I just had the same issue and it also ocurrs on your provided links. If you load the page and then go onto the emulator it does not occur. BUT if you load the page with the emulator already in mobile mode it occurs. Hope that helps.
