### ISSUE TITLE
video quality issue with multiple sources in different browser( HLS-v3, HLS-v4, DASH )

### ISSUE THREAD

**Issue by ravi-kiran-ash** [videojs/video.js#6970]
With video sources from Azure Media Services (AMS), I am appending the format necessary for different formats like below and I see all browsers using HLS-v3 version. Only IE11 shows good quality video and Chrome and Safari shows a blurry video.
```
Note: this.resource.mediaPath is the url from AMS. eg: https://xxxxxxxxxxx.ism/manifest
videojs.src([
{
	// IE11 doesn't support HLS protocol version 4 so need to use version 3 instead. IE11 HLS-V3
	src: `${this.resource.mediaPath}(format=m3u8-aapl-v3)`,
	type: 'application/x-mpegURL',
},
{
	// Safari only supports HLS protocol and we can use HLS version 4.
	src: `${this.resource.mediaPath}(format=m3u8-aapl)`,
	type: 'application/x-mpegURL',
},
{
	// All browsers other than IE and Safari would fallback to DASH protocol which is supported in remaining browser that ASH supports.
	src: `${this.resource.mediaPath}(format=mpd-time-csf)`,
	type: 'application/dash+xml',
},
]);
```
When I remove HLS-v3 and only use (HLS-v4) Safari shows up good quality video but won't be consistent either. HLS-v4 doesn't work in IE11. 
How to support IE11, safari and chrome with different sources HLS-v3, HLS-v4 and DASH respectively?

## Steps to reproduce
1. initialize videojs player
2. add sources give above with AMS url
3. videojs.currentSource() gives the current source which is always the first source in the list that it supports

**Comment by gkatsev** [comment]
Unfortunately, the source that is chosen is the first playable source. Since HLS can be played on all browsers, only the first source is ever chosen.
What you'd want to do is browser check before setting the sources. Something like:
```js
if (videojs.browser.IE_VERSION) {
  videojs.src({
    // IE11 doesn't support HLS protocol version 4 so need to use version 3 instead. IE11 HLS-V3
    src: `${this.resource.mediaPath}(format=m3u8-aapl-v3)`,
    type: 'application/x-mpegURL',
  });
} else {
  videojs.src([
    {
    // Safari only supports HLS protocol and we can use HLS version 4.
    src: `${this.resource.mediaPath}(format=m3u8-aapl)`,
    type: 'application/x-mpegURL',
    },
    {
    // All browsers other than IE and Safari would fallback to DASH protocol which is supported in remaining browser that ASH   supports.
    src: `${this.resource.mediaPath}(format=mpd-time-csf)`,
    type: 'application/dash+xml',
    },
  ]);
}

**Comment by ravi-kiran-ash** [comment]
Got it. Thanks @gkatsev

**Comment by gkatsev** [comment]
You're welcome!
