### ISSUE TITLE
Video js cannot play HLS stream with which VLC and Plyr has not problem

### ISSUE THREAD

**Issue by walec51** [videojs/video.js#6973]
## Description
Stops playing at beginning with error:

```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Video found in segment when we expected only audio. We can't switch to a stream with video from an audio only stream. To get rid of this message, please add codec information to the manifest. Switching to another playlist.
```

## Steps to reproduce

https://codepen.io/walec51/pen/KKgVKew

### Expected
Play the stream. VLC and Plyr had no problem with opening

https://cdn3.wowza.com/2/amtleCs5MHlKamdX/YmtOQ242/hls/vyzpcz8d/playlist.m3u8

### Actual
Stopped with error after first second

### Error output

version 7.6.0
```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Video found in segment when we expected only audio. We can't switch to a stream with video from an audio only stream. To get rid of this message, please add codec information to the manifest. Switching to another playlist.
```

version 7.11.0

```
MEDIA_ERR_DECODE
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.0 and 7.11.0
#### browsers
probably all, tested on Firefox and Chrome
#### OSes
tested on Windows 10
### plugins
plain video js

**Comment by gkatsev** [comment]
Looks like that zero-length segment at the beginning of the video is tripping us up for some reason. Is that something you're able to change?
Looks like that segment includes only audio and no video as well as no i-frames which would cause issues.

**Comment by gkatsev** [comment]
Closing in favor of https://github.com/videojs/http-streaming/issues/1020.
Please try and only open the issue in one repo.
