### ISSUE TITLE
How to ignore the issues which we get from node_modules and which wont effect the app behaviour

### ISSUE THREAD

**Issue by bhargavavarma** [videojs/video.js#6981]
## Description
- null is not an object (evaluating 'e.classList')
- null is not an object (evaluating 'this.el_[e]')

I am getting this issues from node_modules at `node_modules/video.js/dist/video.es.js` file

### Expected
How can we stop this errors which we get from node_modules

### Actual
no error..

### Error output
What will be the possible solution to ignore the issues which we get from node_modules and which doesnot effect app behaviour

### versions
- 7.6.6
#### browsers
- Chrome Mobile iOS - version: 86.0.4240
- iOS version: 14.2
### plugins
- https://github.com/jfujita/videojs-http-source-selector
- https://github.com/spchuang/videojs-markers
- https://github.com/mister-ben/videojs-seek-buttons
- https://github.com/post-programming/videojs-landscape-fullscreen

**Comment by gkatsev** [comment]
When and how does this happen? Can you provide a reduced test case?

**Comment by dalalRohit** [comment]
yes, facing the same issue. And it happens randomly, most of the time when changing routes (in my case Next.js SPA).
```
TypeError: null is not an object (evaluating 'e.classList') video.es.js:1048
```
