### ISSUE TITLE
Is there a way to display VideoJS controls when in fullscreen mode on iPhone iOS?

### ISSUE THREAD

**Issue by MannanK** [videojs/video.js#6985]
Hey. I'm using videojs as my player and have added a custom button to the control bar with custom functionality, which works fine on all browsers except Safari on iPhone iOS. Whenever you go fullscreen, the native controls of iOS will take over, despite `nativeControlsForTouch` being set to `false`, and so I no longer see the VideoJS controls. iPad, iOS inline, and all other browsers still work fine though. `playsinline` is also set to `true`, of course. I saw related issues to this in #6764, #1096, #6567, and others.

Is there any solution in this regard, or is this still a limitation of iOS on iPhones even after iOS 14? Thanks!

**Comment by gkatsev** [comment]
The short answer is no.
It's a platform limitation. Depending on your needs, you could remove the default fullscreen toggle and use `player.enterFullWindow()` in conjunction with `playsinline` to make it take up the entire screen area but that won't be a true fullscreen. However, I probably wouldn't recommend that.
iPadOS as of version 12 uses the fullscreen API so it uses our controls.

**Comment by MannanK** [comment]
@gkatsev Got it, thanks for the clarification. So it sounds like there's no way to have custom controls and the likes when in fullscreen on iOS. This might be out of VideoJS' scope but does that also mean there is no way to display any HTML content on top of the video player when in fullscreen, since the native iOS player has taken over at that point?

Thanks for the quick reply!

**Comment by gkatsev** [comment]
Exactly. There's no way to draw on top when the native fullscreen is used.

**Comment by MannanK** [comment]
got it, thank you. Closing the issue.

**Comment by gkatsev** [comment]
You're welcome.
