### ISSUE TITLE
Part of subtitle text from stream not shown after `<br/>` tag.

### ISSUE THREAD

**Issue by suryakun** [videojs/video.js#6987]
## Description
Subtitle text from stream not shown completely, part of the text not shown. 
The missing part is the part after `<br/>` tag

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Select a caption
2. Caption shown at the player
3. When the stream text contains `<br/>` tag, the part after the tag has not shown
![DeepinScreenshot_select-area_20201208132758](https://user-images.githubusercontent.com/8948071/101448914-6dfbf200-395a-11eb-9e7f-2b5505752ca8.png)

### Expected
The text should be shown completely
expected text from the example image: "Boleh kupakai kamar mandimu sebentar?"

### Actual
Part after `<br/>` tag has not shown.
Actual text currently shown: "Boleh kupakai kamar mandimu", word "sebentar?" is missing

sample of text stream
```
hmoofmfhd Ptraftfhd 
 tfdt¨ trunpzÀmdat<?xml version="1.0" encoding="UTF-8"?><tt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ebutts="urn:ebu:tt:style" ttp:timeBase="media" xml:lang="en" ttp:cellResolution="50 30"><head>
<styling>
<style xml:id="paragraphStyle" tts:fontStyle="normal" tts:fontSize="125%" tts:lineHeight="normal" ebutts:linePadding="0.5c" tts:fontFamily="monospace" tts:color="#ffffff" tts:textAlign="center" tts:wrapOption="noWrap"/>
<style xml:id="textStyle" tts:backgroundColor="#000000" tts:color="#ffffff"/>
</styling>
<layout>
<region xml:id="speaker" tts:origin="10% 10%" tts:extent="80% 80%" tts:overflow="visible" tts:displayAlign="after"/>
</layout>
</head>
<body style="paragraphStyle">
<div>
<!-- text-based TTML -->
	<p xml:id="s0" begin="00:06:14.033" end="00:06:15.053" region="speaker"><span style="textStyle">Aku harus cuci muka.</span></p>
	<p xml:id="s1" begin="00:06:16.273" end="00:06:18.833" region="speaker"><span style="textStyle">Boleh kupakai kamar mandimu<br />
sebentar?</span></p>
	<p xml:id="s2" begin="00:06:18.833" end="00:06:20.433" region="speaker"><span style="textStyle">- Tentu.<br />
- Terima kasih.</span></p>
	<p xml:id="s3" begin="00:06:20.873" end="00:06:22.873" region="speaker"><span style="textStyle">Aku harap kau suka kamar mandinya.</span></p>
</div></body></tt>
stypmsdhmsdhmsix4sidx_¨zÀ
```

### Error output
No error appears.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Version 7.10.1
#### browsers
Chrome Version 86.0.4240.75 (Official Build) (64-bit)
Firefox

#### OSes
Linux
Windows
OSX

### plugins
- dash.js
- videojs-dash
- videojs-contrib-quality-levels
- videojs-contrib-hls
- videojs-http-source-selector

**Comment by gkatsev** [comment]
We don't support TTML ourselves. It sounds like you're using dash.js for playback? It supports TTML and the issue will be on their end.

**Comment by suryakun** [comment]
> We don't support TTML ourselves. It sounds like you're using dash.js for playback? It supports TTML and the issue will be on their end.

**Comment by suryakun** [comment]
@gkatsev Thank you for your respond. Yes, I am using dash.js,
is that mean the issue comes from dash.js which parsing the text?

**Comment by gkatsev** [comment]
Yes. I would look through their issues and if one doesn't exist open one on their repo.

**Comment by suryakun** [comment]
Sure, Thanks :+1:

**Comment by suryagenflix** [comment]
> Yes. I would look through their issues and if one doesn't exist open one on their repo.

Hi @gkatsev any update with this issue?

**Comment by gkatsev** [comment]
This isn't a Video.js issue but a dash.js issue as that is what was used to the OP.
