### ISSUE TITLE
Seeking via tab on seekBar does not work properly on iOS

### ISSUE THREAD

**Issue by nimoatwoodway** [videojs/video.js#6988]
## Description
When seeking via tab on the seekBar, currentTime is not set correctly.
Player must be in fullscreen mode to see the problem. The problem occurs from version 7.9.0 and above.

![video-js-7 9 0-not-working-properly](https://user-images.githubusercontent.com/4716780/101603487-ecf73600-39ff-11eb-88fc-4d0d28007e7e.gif)

## Steps to reproduce

Tested on iOS iPad Simulator with iOS 13.7

Created two code pens:

### Working properly:
video.js v7.8.4
https://codepen.io/nimoatwoodway/full/NWRRRpo

### Working not properly:
video.js v7.11.0
https://codepen.io/nimoatwoodway/full/WNGGGEW

Open in fullscreen and tab on the seek bar. Then you will see the offset. In the codepen the offset is much smaller than in my example in the description but you can see it.

**Comment by gkatsev** [comment]
Does this happen on a real device? I'm not sure the emulator is a good enough indicator. However, we did recently update mouse/touch handling on sliders and this could be related to that.

**Comment by nimoatwoodway** [comment]
Yes, this happens on real devices too. Now tested it on an iPad 7. generation with iOS 14.2. 

With my example on codepen and the default video.js settings and no plugins, the offset is small. On my working project (gif in description), the offset gets really big. 

On the real device it seems, that approx. 500ms after the touch, the offset occurs. When switching back to version 7.8.4 everything is fine on my project and the example on codepen. Something must have changed between 7.8.4 and 7.9.0 which results this problem. Thanks for checking!

**Comment by charliefancelli** [comment]
+1

**Comment by gkatsev** [comment]
Actually, I think this might be because of our switch to use fastSeek while scrubbing https://github.com/videojs/video.js/pull/6525, where it ends up being used always instead of just during scrubbing. `fastSeek` is not precise compared to setting the currentTime manually.

**Comment by gkatsev** [comment]
This will be fixed via https://github.com/videojs/video.js/pull/7527
