### ISSUE TITLE
progress bar stay at 0 and no event are dispatched

### ISSUE THREAD

**Issue by lunika** [videojs/video.js#6992]
## Description

Randomly, the progress bar doesn't move, the button progress stay at timeline 0 we there is no info about video duration in the interface. In the same no event are dispatched by the player.

## Steps to reproduce

It's pretty hard to reproduce, I never reproduce it on https://videojs-http-streaming.netlify.app/ 
But here is my config and the context
1. Videojs options : 
```
{
    controls: true,
    debug: false,
    fluid: true,
    html5: {
      vhs: {
        overrideNative: !videojs.browser.IS_SAFARI,
      },
    },
    language: 'en',
    playbackRates: [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 4],
    plugins: {
      httpSourceSelector: {
        default: 'auto',
      },
    },
    responsive: true,
  }
```
2. video used: https://d2jfelqo7q6dny.cloudfront.net/a3e213a7-9c56-4bd3-b71c-fe567b0cfeb9/cmaf/1605900804.mpd
3. browser used: all chromium based browser

### Expected

When the video start playing I expect to see video duration on the interface and the button should move on the progress bar.

### Actual

I made a capture to understand what is happening: https://d2jfelqo7q6dny.cloudfront.net/a3e213a7-9c56-4bd3-b71c-fe567b0cfeb9/thumbnails/videojs-bug.gif

![](https://d2jfelqo7q6dny.cloudfront.net/a3e213a7-9c56-4bd3-b71c-fe567b0cfeb9/thumbnails/videojs-bug.gif)

### Error output

No error output

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
`7.10.2`
#### browsers
All chromium based browser
#### OSes
All OS
### plugins
are any videojs plugins being used on the page? If so, please list them below.

- videojs-contrib-quality-levels: 2.0.9
- videojs-http-source-selector: 1.1.6
- mux.js: 5.7.0

**Comment by gkatsev** [comment]
I'm unable to reproduce it on https://videojs-http-streaming.netlify.app/ with the given mpd file.

**Comment by lunika** [comment]
> I'm unable to reproduce it on https://videojs-http-streaming.netlify.app/ with the given mpd file.

Yes i'm unable too but is there the same plugins installed ? Is it the same options ? It's related with the `overrideNative` option. When set to false, it works fine. When set to true, sometimes there are no event dispatched.

**Comment by gkatsev** [comment]
overrideNative is set to true and there's only one plugin installed. It's a fairly minimal player and where we do a lot of our testing.
Does it fail for you consistently? Or just sometimes?

Do you have a live page where you can reproduce it that you can share?

**Comment by lunika** [comment]
> Do you have a live page where you can reproduce it that you can share?

Not yet, I will update this issue when the live page is available.
Thanks

**Comment by lunika** [comment]
Hi,
you can check on this test page https://staging.marsha.oc.openfun.fr/videos/3443512d-23f1-d745-8d27-61efbfc7ece8
You can safely accept the certificate, it's a staging environment with a let's encrypt staging certificate.
I reproduce the issue on this page, remember to use a chromium base browser

**Comment by lunika** [comment]
You can also test on our production environment https://marsha.education/videos/c7193e53-9059-bad8-32e4-05127ed67649

**Comment by gkatsev** [comment]
I think it's something to do with your usage of Video.js.
If I reset the source by doing `player.src(player.currentSource())` in the console, the times are set properly. Unfortunately, because all the files are minified I can't help further to track down what might be the issue.

**Comment by lunika** [comment]
If you want to know how the player is instanciated and configured you can take a look here, all the project is open source : https://github.com/openfun/marsha/blob/a2de9a3b2f8dc9432a4c895f7fc487af109ceefc/src/frontend/Player/createVideojsPlayer.ts

Tomorrow I will test to move all the listener in a ready function, maybe the player is not ready at that time.

**Comment by lunika** [comment]
A quick update. This issue is directly related to the usage of DASH. I removed in our solution the usage of dash to use only HLS and we don't have this problem anymore.
