### ISSUE TITLE
Chrome browser: uncaught promise, when pausing/playing video 

### ISSUE THREAD

**Issue by sebastianvog** [videojs/video.js#6998]
## Description
When playing a video on a slow connection in Chrome, e.g. https://videojs.com/advanced?video=disneys-oceans
It's possible that a uncaught promise is thrown in the javascript console when clicking pause/play while the video has not loaded yet.

## Steps to reproduce
1. With google chrome  to the demo sample https://videojs.com/advanced/?video=disneys-oceans.
2.  Before Starting the video change the "network" in the chrome javascript console to "Slow 3G" to simulate a slow connection
2.Start the video, and scrub/drag to the middle of the video
3. While the video is attempt to load/reload, press the pause/play buttons quickly

### Expected
No errors displayed in javascript console

### Actual
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

### Error output
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
We are using 7.11.0
Not sure what version runs on https://videojs.com/advanced/?video=disneys-oceans but i would assume the latest version?
#### browsers
Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
#### OSes
OSX Mojave

**Comment by FredZeng** [comment]
You can just ignore this error by catching the promise in most situation. In `videojs`, they use `silencePromise` to ignore this error.

```
silencePromise(this.el_.play());
```

```
/**
 * Returns whether an object is `Promise`-like (i.e. has a `then` method).
 *
 * @param  {Object}  value
 *         An object that may or may not be `Promise`-like.
 *
 * @return {boolean}
 *         Whether or not the object is `Promise`-like.
 */
export function isPromise(value) {
  return value !== undefined && value !== null && typeof value.then === 'function';
}

/**
 * Silence a Promise-like object.
 *
 * This is useful for avoiding non-harmful, but potentially confusing "uncaught
 * play promise" rejection error messages.
 *
 * @param  {Object} value
 *         An object that may or may not be `Promise`-like.
 */
export function silencePromise(value) {
  if (isPromise(value)) {
    value.then(null, (e) => {});
  }
}
```

Read carefully over [play-request-was-interrupted](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted).
![image](https://user-images.githubusercontent.com/17154608/113957740-5eca7980-9852-11eb-89ad-babaf0e0d42e.png)

**Comment by gkatsev** [comment]
This is basically expected. We do try and silence these errors, but I guess the play toggle didn't silence the promise.
