### ISSUE TITLE
JS error in Chrome on OS X

### ISSUE THREAD

**Issue by hosiawak** [videojs/video.js#700]
Mac OS X Mountain Lion
Chrome Version 29.0.1547.57

To reproduce turn on the inspector with Alt + Cmd + i the Console tab

and visit http://www.videojs.com

I get "GET http://vjs.zencdn.net/4.1.0/video.js.map 403 (Forbidden) "

**Comment by thijstriemstra** [comment]
This error is back, http://vjs.zencdn.net/5.4.6/video.min.js.map is missing.
