### ISSUE TITLE
How can I make a vertical volume control?

### ISSUE THREAD

**Issue by Anox3D** [videojs/video.js#7003]
Hello, I'm trying to make my volume control vertical but without success.
I have already tried this code:
```
let player = videojs('video_1', {
    controlBar: {
        volumeMenuButton: {
            inline: false
         }
    }
});
```
But it didn't work.

Hope you could help me!

**Comment by blacktrash** [comment]
@Anox3D,  try `volumePanel` instead of `volumeMenuButton`.

**Comment by Anox3D** [comment]
Okay I'l this.

**Comment by gkatsev** [comment]
using `volumePanel` should work if you're using Video.js 6 or 7. See https://codepen.io/gkatsev/pen/poErQem for a working example.

**Comment by Anox3D** [comment]
Thanks! It worked!
