### ISSUE TITLE
Can't play HLS on macOS Big Sur safari

### ISSUE THREAD

**Issue by jinqinghua** [videojs/video.js#7009]
## Description
Can't play HLS on macOS Big Sur safari

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. copy URL https://videojs.github.io/http-streaming/ to macOS Big Sur safari

### Expected
Can play the HLS sample

### Actual
Can't play

### Error output
The media playback was aborted due to a corruption problem or because the media used features your browser did not support

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Use page https://videojs.github.io/http-streaming/, should be 7.10.2+
#### browsers
Safari 14
#### OSes
macOS 11
### plugins
N/A

Is it a macOS Big Sur safari issue?

**Comment by mister-ben** [comment]
The bip bop sample? Plays for me. Also, on Safari it's playing with the browser's native playbac.

**Comment by jinqinghua** [comment]
[](url)

> The bip bop sample? Plays for me. Also, on Safari it's playing with the browser's native playbac.

Yes, The bip bop sample.

Thanks for your feedback, But it really not plays for me.

**Comment by jinqinghua** [comment]
https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

It works on           macOS Catalina 10.15.7 safari 14
but not works on macOS Big Sur 11.0.1 safari 14

**Comment by 9527Robin** [comment]
When I use VideoJS, Safari is full screen with sound and no graphics。

**Comment by jinqinghua** [comment]
it works when I upgrade macOS Big Sur to 11.2.2

**Comment by gkatsev** [comment]
Sounds like a browser bug. We don't handle playback on Safari by default and if it's fixed with an update, that's great.
