### ISSUE TITLE
The progress-dot's position is not right at videojs v7.10.2!

### ISSUE THREAD

**Issue by SongJuXin** [videojs/video.js#7011]
## Description
The progress-dot's position is not right,and the same phenomenon is occurs in volume-bar.
![image](https://user-images.githubusercontent.com/20874344/102845934-a6ff9080-4449-11eb-9cb7-4d82ec996b46.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.https://codepen.io/SongJuXin/pen/WNGEMRX is the online show.

### Expected
Progress-dot is vertical middle.

### Actual
Progress-dot is dropdown.

#### videojs
v7.10.2
#### browsers
chrome  87.0.4280.88
#### relation issue
https://github.com/videojs/video.js/issues/7004

**Comment by gkatsev** [comment]
No need to open a new issue. I just hadn't gotten back to the old one yet.
