### ISSUE TITLE
how to customize decryption key fetching module in video.js?

### ISSUE THREAD

**Issue by akshaybhuradia2020** [videojs/video.js#7012]
## Description
I have build key server for encrypting and decrypting HLS content. All key are stored in encrypted form. Before starting encryption and decryption, I need to decrypt key first which is get from key server and then start encryption or decryption(playback). so please give me direction how to achieve this and please provide me details where i need to make changes in video.js file.

Note : This is done to safe key which is specified in m3u8 file.

**Comment by gkatsev** [comment]
We only really provide one mechanism, but it's probably not good enough for your needs. We have a `beforeRequest` method you can override which allows you to change the options we would use to make XHRs for various things including key fetching. In addition, this won't work on Safari and iOS as native playback is used there and there's no way to override how encrypted HLS works there.
Your best bet if you're trying to protect your content is probably to switch to DRM.

**Comment by akshaybhuradia2020** [comment]
@gkatsev  I am not able to understand where do i make changes in this code section can you tell me ? 
` 
  var videojsXHR = videojs$1.xhr,
      mergeOptions$1$1 = videojs$1.mergeOptions;

  var callbackWrapper = function callbackWrapper(request, error, response, callback) {
    var reqResponse = request.responseType === 'arraybuffer' ? request.response : request.responseText;

    if (!error && reqResponse) {
      request.responseTime = Date.now();
      request.roundTripTime = request.responseTime - request.requestTime;
      request.bytesReceived = reqResponse.byteLength || reqResponse.length;

      if (!request.bandwidth) {
        request.bandwidth = Math.floor(request.bytesReceived / request.roundTripTime * 8 * 1000);
      }
    }

    if (response.headers) {
      request.responseHeaders = response.headers;
    } // videojs.xhr now uses a specific code on the error
    // object to signal that a request has timed out instead
    // of setting a boolean on the request object


    if (error && error.code === 'ETIMEDOUT') {
      request.timedout = true;
    } // videojs.xhr no longer considers status codes outside of 200 and 0
    // (for file uris) to be errors, but the old XHR did, so emulate that
    // behavior. Status 206 may be used in response to byterange requests.


    if (!error && !request.aborted && response.statusCode !== 200 && response.statusCode !== 206 && response.statusCode !== 0) {
      error = new Error('XHR Failed with a response of: ' + (request && (reqResponse || request.responseText)));
    }

    callback(error, request);
  };

  var xhrFactory = function xhrFactory() {
    var xhr = function XhrFunction(options, callback) {
      // Add a default timeout
      options = mergeOptions$1$1({
        timeout: 45e3
      }, options); // Allow an optional user-specified function to modify the option
      // object before we construct the xhr request

      var beforeRequest = XhrFunction.beforeRequest || videojs$1.Vhs.xhr.beforeRequest;

      if (beforeRequest && typeof beforeRequest === 'function') {
        var newOptions = beforeRequest(options);
        if (newOptions) {
          options = newOptions;
        }
      }

      var request = videojsXHR(options, function (error, response) {
        return callbackWrapper(request, error, response, callback);
      });
      var originalAbort = request.abort;
      
      request.abort = function () {
        request.aborted = true;
        return originalAbort.apply(request, arguments);
      };

      request.uri = options.uri;
      request.requestTime = Date.now();
      return request;
    };

    return xhr;
  };`

**Comment by akshaybhuradia2020** [comment]
@gkatsev i have found the way to decryt the key value from key server(key is in encrypted form). I need a help. How can i add property to videojs object define in below code so that i can use in handlekeyresponse function.
 

```
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import videojs from '../../../node_modules/video.js/dist/video.js';

@Component({
  selector: 'app-playerdemo',
  templateUrl: './playerdemo.component.html',
  styleUrls: ['./playerdemo.component.css']
})
export class PlayerdemoComponent implements OnInit {
  @ViewChild('myplayer', { static: false }) videoElement: ElementRef;
  constructor() { }
  dash : any;
  ngOnInit(): void {
  }

  ngAfterViewInit() {
    this.dash = videojs(this.videoElement.nativeElement, {
      preload: 'auto',
      autoplay: false,
      liveui: true,
      controls: true,
      fluid: true,
      decryptionkey : 'XYZCETYUOONM' // i want to add this property and it should be access in videojs handlekeyresponse function defination.
    });

    this.dash.src({ type: 'application/x-mpegURL', src: 'http://localhost:8080/480p.m3u8'});
  }

}
```

**This is videojs file code where i make changes**
```
  var handleKeyResponse = function handleKeyResponse(segment, finishProcessingFn) {
    return function (error, request) {
      var response = request.response;
      let ciphertext = new TextDecoder().decode(response);
      
      let CryptoJS = require("crypto-js");

      let bytes  = CryptoJS.AES.decrypt(ciphertext, CryptoJS.enc.Hex.parse(// key value come from videojs object), {iv: CryptoJS.enc.Hex.parse('00000000000000000000000000000000')});
      let encodedWord = CryptoJS.enc.Utf8.stringify(bytes);
      var strlen = encodedWord.trim().length;
     
      var buf = new ArrayBuffer(strlen); 
      var bufView = new Uint8Array(buf); 
      for (var i = 0; i < strlen; i++) { bufView[i] = encodedWord.charCodeAt(i);}
      response = buf;
      
      var errorObj = handleErrors(error, request);
      if (errorObj) {
        return finishProcessingFn(errorObj, segment);
      }

      if (response.byteLength !== 16) {
        return finishProcessingFn({
          status: request.status,
          message: 'Invalid HLS key at URL: ' + request.uri,
          code: REQUEST_ERRORS.FAILURE,
          xhr: request
        }, segment);
      }

      
      var view = new DataView(response);
      segment.key.bytes = new Uint32Array([view.getUint32(0), view.getUint32(4), view.getUint32(8), view.getUint32(12)]);
      return finishProcessingFn(null, segment);
    };
  };
```

**Comment by grishkovelli** [comment]
@akshaybhuradia2020 look at https://azure.microsoft.com/en-us/blog/how-to-make-token-authorized-aes-encrypted-hls-stream-working-in-safari/

**Comment by gkatsev** [comment]
That basically says you need a proxy server that re-writes your manifest for you. Definitely an option but doesn't help if you need it to be client-side only.

**Comment by salehasadi** [comment]
@gkatsev Hi, I need to pass a custom decryption key to player which I receive that in api response beside file information and is not present in playlist file, but I don't know if this is possible in videojs or not! I added a question with more explanations about it in stackoverflow https://stackoverflow.com/q/67336442/6644806

**Comment by gkatsev** [comment]
@salehasadi you could use https://github.com/videojs/http-streaming#vhsxhr to set `beforeRequest` which we pass in an options object for the request we're about to make. You can detect when it's the key request and modify the request. The only caveat is that this will *not* work on iOS. iOS doesn't provide the MSE APIs for us to be able to handle playback ourselves, and so we are dependent on the native behavior which doesn't provide a way to make customer requests. Basically, your only option there is the proxy server.

**Comment by salehasadi** [comment]
@gkatsev Thanks, I tried  `beforeRequest` but there seems only I can change xhr request options and cannot return my client side processed key as response, or maybe I'm wrong!?
