### ISSUE TITLE
IE11 - Fullscreen doesn't work when disposing of another player on the same page

### ISSUE THREAD

**Issue by tieutuvdanh** [videojs/video.js#7013]
## Steps to reproduce
1. I have two videos on the same page, suppose that video1 and video2
2. Dispose of video1 by calling videojs("video1").dispose()
3. Call videojs("video2").requestFullscreen()

## Results
Video2 is not full screen and lost control bar
![image](https://user-images.githubusercontent.com/29733908/103073395-28962080-45fa-11eb-8cac-57ea2cad924e.png)

### Expected
fullscreen is normal

#### videojs
 videojs 7.8.4
#### browsers
IE 11 OS  18363.1256

**Comment by gkatsev** [comment]
Oops, this may be related to us listening to an event with a method on the Player prototype, then when getting disposed it removed all handlers rather than just for the instance.

**Comment by tieutuvdanh** [comment]
> Oops, this may be related to us listening to an event with a method on the Player prototype, then when getting disposed it removed all handlers rather than just for the instance.

Thanks for your answer, so have any ways to quickly fix it?
Currently, I'm using " delete videojs.getAllPlayers()["video1"]"  and remove DOM HTML then creating new video

**Comment by gkatsev** [comment]
probably no easy way for you to fix it, but I'll take a look, it shouldn't be a hard fix for this. I'll take a look today.

**Comment by tieutuvdanh** [comment]
> probably no easy way for you to fix it, but I'll take a look, it shouldn't be a hard fix for this. I'll take a look today.

I don't want to manually remove DOM so thank you very much.

**Comment by gkatsev** [comment]
This is out in v7.11.3 now
