### ISSUE TITLE
How can remove Picture in Picture button?

### ISSUE THREAD

**Issue by Anox3D** [videojs/video.js#7014]
I would like to remove the Picture in Picture button on my player I've already try something but it only remove the possibility to use the PiP.
Here's a demo with the code: https://anox3d.github.io/disablepictureinpicture/

**Comment by kvmsc** [comment]
You can do it using css

```
.vjs-picture-in-picture-control{
    display: none;
}
```

**Comment by Anox3D** [comment]
@kvmsc Thanks it worked!

**Comment by gkatsev** [comment]
You can also do it via an option:
```js
videojs('video', {
  controlBar: {
    pictureInPictureToggle: false
  }
});
```
