### ISSUE TITLE
segment-metadata text track is not available in Safari, iOS and Mac

### ISSUE THREAD

**Issue by kvmsc** [videojs/video.js#7015]
## Description
I tried the same example given in the [ https://github.com/videojs/http-streaming#segment-metadata ](tutorial) to read the segment-metadata text track, it was not working in ios/mac devices. I thought it might be a native playback issue, so tried toggling the native override in the hls tech, it didn't work. 

After closely observing, in browsers other than safari, for the activeCue I'm getting an object with VTTCue type, but in safari it is coming as DataCue.

Is there any setting that I should do for getting a VTTCue type for safari?
Or is there any other way by which I can get the name/uri of the current segment that is being played on every new segment fetch ( I tried cuechange event, as I'm not getting segment-metadata text track it didn't work)?

## Steps to reproduce

1. On a livestream try to get the segment-metadata using the [ https://github.com/videojs/http-streaming#segment-metadata ](tutorial).
2. segment-metadata text track is available in other browsers, but not in safari.

### Expected
Please describe what you expected to see.
I expected that the segment-metadata text track would be available in safari too, both ios and mac.

### Actual
Please describe what actually happened.
The segment-metadata track is not available in safari both ios and mac.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.11.0

#### browsers
what browser are affected?
Safari 13+

#### OSes
what platforms (operating systems and devices) are affected?
iOS, Mac

### plugins
are any videojs plugins being used on the page? If so, please list them below.

 "videojs-contrib-quality-levels": "^2.0.9",
 "videojs-errors": "^4.3.2",
 "videojs-font": "^3.2.0",
 "videojs-hls-quality-selector": "^1.1.4",
 "videojs-hlsjs": "^1.4.8",
 "videojs-hotkeys": "^0.2.27",
 "videojs-vtt.js": "^0.15.2"

**Comment by gkatsev** [comment]
This is the expected behavior. The segment metadata is only used when our playback engine is used. By default, on Safari, we use the native playback for HLS, so, you would need to set overrideNative.
Looks like there is a bug here, though. You can work around it by setting `nativeTextTracks: false`:
```js
videojs('video', {
  html5: {
    nativeTextTracks: false,
    vhs: {
      overrideNative: true
    }
  }
});
```
It looks like it's a bad interaction between our track creation and the native Safari text tracks.

**Comment by asadmalik3** [comment]
@gkatsev I can confirm this behavior. I have created a small snippet below to explain the problem. First open [this](https://web-platform-dwpqf8.stackblitz.io) URL on any windows browser, active cue of "segment-metadata" text track will be printed below player. Now open in IPAD or IPHONE (haven't tested yet with mac), you can see that text track is never found.

Stackblitz Editor: [https://stackblitz.com/edit/web-platform-dwpqf8?file=index.html](https://stackblitz.com/edit/web-platform-dwpqf8?file=index.html)
Stackblitz viewer: [https://web-platform-dwpqf8.stackblitz.io](https://web-platform-dwpqf8.stackblitz.io)

**Comment by asadmalik3** [comment]
It turned out that MSE playback is not yet supported on IOS 12 and i was trying to run this code on IOS 12 and segment-meta-data text track is not supported on non-mse based video playback.

**Comment by gkatsev** [comment]
Yes, segment-metadata track is only available when our playback engine, [VHS](https://github.com/videojs/http-streaming), is being used. This only works on browsers that have MSE-enabled and by default it only runs on non-Safari based browsers. We also don't currently recommend using our playback engine on Safari browsers.
