### ISSUE TITLE
Non-preloaded, default text track is loaded and parsed twice

### ISSUE THREAD

**Issue by sethcarlton** [videojs/video.js#7019]
## Description

When not preloading text tracks and setting a default, the default text track is being loaded and parsed twice, resulting in a "double caption"

Reduced test case: https://codepen.io/scarlton/pen/ZEpvaEo

## Steps to reproduce
1. Set `preloadTextTracks` to `false`
2. Set one of your text tracks as `default`
3. Load the player

### Expected
A single network request for the `default` text track, the `default` track to be selected, the selected track cues to be shown.
![image](https://user-images.githubusercontent.com/5727047/103246182-39130780-4928-11eb-93f2-554eb2326698.png)

### Actual
Two network requests for the `default` text track, the `default` track is selected, the selected track cues are showing double.
![image](https://user-images.githubusercontent.com/5727047/103246144-154fc180-4928-11eb-9507-edcbf1b68eb1.png)

## Additional Information
On track load, if we are preloading OR this track is default, then `loadTrack` is called. However, when we are NOT preloading, `loadTrack` is also called for each track when its mode changes. Since a track set as `default` fires a mode change, `loadTrack` ends up being called twice.

As far as I can tell, the issue could be resolved by removing `|| default_` from [line 344 of text-track.js](https://github.com/videojs/video.js/blob/affc0611d978b1a6d02e443a46d14a58f2b1441c/src/js/tracks/text-track.js/#L344). When preloading, all tracks would still be loaded here while non preloaded default tracks would load when its mode changes.

#### videojs
7.10.2
#### browsers
Chrome (probably others)
#### OSes
macOS (probably Windows)

**Comment by isabelleingato** [comment]
New here! I'd like to grab this one if that's okay.

I agree with the assessment in the issue description of https://github.com/videojs/video.js/pull/6043. The other option would seem to be to assume the default track has always been preloaded and not try to load it a second time on mode change to "showing": https://github.com/videojs/video.js/blob/affc0611d978b1a6d02e443a46d14a58f2b1441c/src/js/tracks/text-track.js/#L240; that might be more aligned with the original intent of https://github.com/videojs/video.js/pull/2192.

**Comment by sethcarlton** [comment]
Yep that could also be a solution and may be more clear/more aligned with the original intent. Thanks for picking this up!
