### ISSUE TITLE
videojs play() returns promisestate as pending forever

### ISSUE THREAD

**Issue by Jogii** [videojs/video.js#7031]
## Description
videojs play() returns promisestate as pending , doesn't get fullfilled
[https://jsbin.com/dimikoh/edit?html,console,output](https://jsbin.com/dimikoh/edit?html,console,output)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. After executing the above code the player does not play on play btn click

2. In browser console type 
 var video = videojs("my_video");
 video.play();  //returns a promise which has a promisestate as pending

3. again type,  document.getElementById("my_video_html5_api").play();  //video starts playing,returns a promise in fullfilled state

## Results
![image](https://user-images.githubusercontent.com/6221017/103999957-98440800-51c3-11eb-912f-12b44a6fc0c1.png)

### Expected
Please describe what you expected to see.
var video = videojs("my_video");
video.play();  //should returns a promise state fullfilled

## Additional Information
I was earlier using a legacy version 4.12.6, and i am trying to upgrade to v7.10.2 or above.
Also is there a problem on how i am assigning to the src attr?
#### videojs
7.10.2,  7.11.1
#### browsers
chrome, firefox

**Comment by kenluck2001** [comment]
I looked at the code, but I cannot find the source tags as it is in the documentation. Add the source tag with the src attribute as shown below and also add the  data-setup='{}' or use videojs tag to be sure that video.js is loaded at the moment you file is about to be played.

<video
    id="my-player"
    data-setup='{}'>
  <source src="https://vjs.zencdn.net/v/oceans.mp4" type="video/mp4"></source>
</video>


Secondary, ensure that your video loading is not a cross-origin request (CORS). Otherwise, do the necessary adjustments

**Comment by Jogii** [comment]
@kenluck2001 Thanks for reviewing the code,I really appreciate it.
I did not use the data-setup but used an options object to achieve the same. also i am not sure whether source tag is necessary.

**Comment by Jogii** [comment]
Solved the same using source in options object.
![image](https://user-images.githubusercontent.com/6221017/104281180-14479400-54d3-11eb-820d-c8c3a3d6e036.png)

**Comment by gkatsev** [comment]
Was just going to say. The issue is that we don't currently support the src attribute. You need to use either an option or use a `<source>` element in the video element. At some point I'll fixup this PR which adds src support: https://github.com/videojs/video.js/pull/5762.

**Comment by gkatsev** [comment]
Glad you were able to figure it out.
