### ISSUE TITLE
Change the text of time tooltip 

### ISSUE THREAD

**Issue by ardian-c** [videojs/video.js#7033]
Hi, 

I am looking to change the tooltip content to contain some more info, i.e. 11:30 remaining instead of just 11:30. I see the class `.vjs-time-tooltip` and there is a component in the documentation, however, I'm not sure what options I should provide to get that functionality. 

Thank you!

**Comment by SerjLeo** [comment]
> Hi,
> 
> I am looking to change the tooltip content to contain some more info, i.e. 11:30 remaining instead of just 11:30. I see the class `.vjs-time-tooltip` and there is a component in the documentation, however, I'm not sure what options I should provide to get that functionality.
> 
> Thank you!

Hi, Ardian! First you need to get tooltip component from videojs player instance
```
const player = videojs(this.$refs.videoPlayer, this.options) //I'm using Vue here, it doesn't matter

const timeTooltip = player
        .getChild('controlBar')
        .getChild('progressControl')
        .getChild('seekBar')
        .getChild('mouseTimeDisplay')
        .getChild('timeTooltip')
```
Then you I suggest overwrite tooltip method "update", that is invokes when we hover on seekbar. To render data in tooltip we use it's method "write" and here we have result!
```
timeTooltip.update = function (seekBarRect, seekBarPoint, time) {
          this.write("Hello from tooltip")
        }
```
![image](https://user-images.githubusercontent.com/51518243/119221884-35139c00-bafa-11eb-9cc2-92b31c76c574.png)
Method "update" recieves time of hover point, so we can use it +add some styling to tooltip
```
timeTooltip.update = function (seekBarRect, seekBarPoint, time) {
          this.write(`${time} remaining`)
        }
```
```
.vjs-time-tooltip {
  white-space: nowrap;
}
```
And here is final result:
![image](https://user-images.githubusercontent.com/51518243/119222099-53c66280-bafb-11eb-8178-860c64c64ca5.png)

**Comment by ardian-c** [comment]
Thank you for the detailed answer :)
