### ISSUE TITLE
MP3 playback not working on Safari 14.x 

### ISSUE THREAD

**Issue by amtins** [videojs/video.js#7037]
## Description
MP3 playback doesn't seem to work properly on Safari 14.x, at least on MacOS Big Sur.

## Steps to reproduce

1. Open [BrowserStack](https://live.browserstack.com/?utm_source=chrome&utm_medium=extension&utm_campaign=quick-launch#os=OS+X&os_version=Big+Sur&browser=Safari&browser_version=14.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Famtins.github.io%2Fempty-banana-space%2Faudio.html&speed=1&host_ports=google.com%2C80%2C0)
2. Select MacOS Big Sur
3. Select Safari 14
4. Open `https://amtins.github.io/empty-banana-space/audio.html`
5. Click play

NB: It possible to load a video.js specific version by adding a `version` parameter to the URL like so
`https://amtins.github.io/empty-banana-space/audio.html?version=7.4.2`
`https://amtins.github.io/empty-banana-space/audio.html?version=7.6.5`

### Expected

Playback should work.

### Actual

The player displays the "Replay" button. Clicking the "Replay" button has no effect. The "Mute/Unmute" button seems to bring the media back to life.

![Screenshot](https://user-images.githubusercontent.com/34163393/104327577-39e09780-54eb-11eb-8f03-15a7ba98d231.png)

#### videojs
All

#### browsers
Safari version 14.x

#### OSes
MacOS

**Comment by mister-ben** [comment]
It seems like an audio element that is muted just doesn't play on Big Sur/Safari, and that's also the case without Video.js involved. It's not entirely illogical to refuse to play audio at all when muted rather than "play" silently. I guess the change is part of Mac OS becoming more like iOS.

**Comment by amtins** [comment]
@mister-ben thank you for your answer. IMO it would make sense if the play promise was rejected as described here [play](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#return_value). However we can see in the console [bare player](https://amtins.github.io/empty-banana-space/safari.html) that the play promise is not rejected and it fires a ended event.

We will report the issue to Apple to see what they have to say about this behavior.

**Comment by mister-ben** [comment]
There's a report for the same behaviour on iOS Safari here https://bugs.webkit.org/show_bug.cgi?id=219295#c5

**Comment by gkatsev** [comment]
Looks like this has been fixed since then.
