### ISSUE TITLE
Is not supported H.265?

### ISSUE THREAD

**Issue by L1yp** [videojs/video.js#7039]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
The short answer is H265 is not supported.
The longer story is that it really depends on the browser/device. For example, Safari supports HEVC and if you're playing back HLS with HEVC, we pass HLS directly to Safari, so it works. Most other browsers do not support HEVC. However, Chromecast with Google TV or Chromecast Ultra also support HEVC but regular Chrome doesn't. We'll play back HEVC on those Chromecasts.
While I wouldn't recommend it personally, someone did write a video.js plugin for playing back HEVC. See https://github.com/videojs/video.js/issues/6811 and https://github.com/coffe1891/videojs-flvh265

**Comment by L1yp** [comment]
> The short answer is H265 is not supported.
> The longer story is that it really depends on the browser/device. For example, Safari supports HEVC and if you're playing back HLS with HEVC, we pass HLS directly to Safari, so it works. Most other browsers do not support HEVC. However, Chromecast with Google TV or Chromecast Ultra also support HEVC but regular Chrome doesn't. We'll play back HEVC on those Chromecasts.
> While I wouldn't recommend it personally, someone did write a video.js plugin for playing back HEVC. See #6811 and https://github.com/coffe1891/videojs-flvh265

Thank you very much！！！
