### ISSUE TITLE
Can't set volume when using iPhone without full screen

### ISSUE THREAD

**Issue by Hsueh-Jen** [videojs/video.js#7040]
## Description
When I use **iPhone** to watch videojs player on all browsers like chrome, safari, etc.  I **can** set volume when player is full screen, but I **can't** set volume when player is **NOT** full screen. I can't drag and drop the dot on volume bar to set volume. It always stay at default volume. **Android** phone can set volume smoothly. Whether it is full screen or not full screen

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. use iPhone and go to videojs official demo: https://videojs.com/advanced/?video=disneys-oceans
2. try to set volume, and you can't set volume.

**Comment by mister-ben** [comment]
It's normal that you can't set the volume on iOS Safari other than with the physical volume buttons. The volume control shouldn't be showing at all, there should just be the mute toggle, but apparently the check we make to see if setting the volume doesn't work now on latest iOS - the volume getter will briefly return the value it was set to.

**Comment by gkatsev** [comment]
> the volume getter will briefly return the value it was set to.

oh no. I guess we'll want to do a workaround for it.

**Comment by klemensz** [comment]
I ran into the same issue now. Is there a workaround already?

**Comment by tania-shevtsova-gl** [comment]
hey @gkatsev i have the same issue when using mobile/tablets. is there any way to fix that? thanks in advance.

**Comment by gkatsev** [comment]
I have a proposed solution here https://github.com/videojs/video.js/pull/7514
