### ISSUE TITLE
video.js custom playlist vue integration

### ISSUE THREAD

**Issue by shrw** [videojs/video.js#7044]
Is it possible to have vue events on video.js custom playlist play integration

**Comment by TroyDota** [comment]
just listen to the events and then emit the vue events. and then unlisten on destroy

**Comment by gkatsev** [comment]
Yup, it's possible. There's nothing vue specific in Video.js. A plugin like videojs-playlist can give you playlist support. You can use eithe ruse videojs-playlist-ui for a UI, but it doesn't integrate with vue directly. Instead, you'd probably want to listen to the correct events and create related vue components based on that information.
