### ISSUE TITLE
Android5.1-Fullscreen doesn't work

### ISSUE THREAD

**Issue by FiggerDancer** [videojs/video.js#7053]
## Steps to reproduce
1.call videojs.requestFullscreen()

## Results
video is not full screen.
call ”video.webkitRequestFullScreen“ is normal

### Expected
fullscreen is normal

#### videojs
videojs7.2.0
#### browsers
android browser 5.1.0

**Comment by gkatsev** [comment]
Is this inside of a webview or in Chrome?

**Comment by FiggerDancer** [comment]
> Is this inside of a webview or in Chrome?

webview

**Comment by gkatsev** [comment]
Unfortunately, webviews don't support fullscreen by default. See the link here for more info: https://github.com/videojs/video.js/issues/6734#issuecomment-652618076

**Comment by ingdaeho** [comment]
worked with 
`<WebView allowsFullscreenVideo={true} />`
