### ISSUE TITLE
Could not play the single encrypted FMP4

### ISSUE THREAD

**Issue by Modeux** [videojs/video.js#7055]
## Description
I have a fragmented video that package by bento4 mp4dash with HLS option.
Also, the video is encrypted by SIMPLE-AES.
Try to play the video via videoJS and error occurred.

This the script to convert fragmented video to HLS:
`
KID=$(openssl rand -hex 16)
KEY=$(openssl rand -hex 16)

mp4dash \
    -v \
    -d \
    --no-split \
    --use-segment-list \
    --hls \
    --hls-key-url key.bin \
    --encryption-key "$KID":"$KEY" \
    --encryption-cenc-scheme cbcs \
    --hls-master-playlist-name=test-main.m3u8 \
    --hls-iframes-playlist-name=test-iframes.m3u8 \
    [type=audio]test-a.mp4 \
    [type=video]test-v.mp4
`

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.  Prepare the test sample: 
2. Use codepen.io and import videoJS code to test the playlist

`
<video
    id="my-player"
    class="video-js"
    controls
    preload="auto"
    poster="//vjs.zencdn.net/v/oceans.png"
    data-setup='{}'>
  <source src="https://d18xttvm0lwo37.cloudfront.net/dash-hls-test-aes/test-main.m3u8" type="application/x-mpegURL"></source>
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a
    web browser that
    <a href="https://videojs.com/html5-video-support/" target="_blank">
      supports HTML5 video
    </a>
  </p>
</video>
`

### Actual
The error occurred in Chrome.
`Uncaught RangeError: byte length of Int32Array should be a multiple of 4
    at new Int32Array (<anonymous>)
    at new u (ffb24e6e-a988-4c74-8ad4-b15ae6bf8c72:2)
    at a.onmessage (ffb24e6e-a988-4c74-8ad4-b15ae6bf8c72:5)`

I also test the video on the firefox, edge, safari

The error occurred in Firefox.
`
RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer 2 e3e07564-47a0-1b46-8309-2a8eea2cb00f:2:3000
    u blob:https://cdpn.io/e3e07564-47a0-1b46-8309-2a8eea2cb00f:2
    onmessage blob:https://cdpn.io/e3e07564-47a0-1b46-8309-2a8eea2cb00f:5
`

The error occurred in Edge.
`
5359dcf5-bb55-4a84-b91b-44ed176d4c38:2 Uncaught RangeError: byte length of Int32Array should be a multiple of 4
    at new Int32Array (<anonymous>)
    at new u (5359dcf5-bb55-4a84-b91b-44ed176d4c38:2)
    at a.onmessage (5359dcf5-bb55-4a84-b91b-44ed176d4c38:5)
`

Only Safari could play the video correctly.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.11.2
#### browsers
Google Chrome - 87.0.4280.141
Firefox - 84.0.2
Edge - 87.0.664.75
Safari - 14.0.1

**Comment by gkatsev** [comment]
Unfortunately, we don't support SAMPLE-AES decryption right now. See this document for more information https://github.com/videojs/http-streaming/blob/main/docs/supported-features.md#hls-missing-features

**Comment by Modeux** [comment]
I see,  thx for your reply
