### ISSUE TITLE
Cannot play Youtube videos with links 

### ISSUE THREAD

**Issue by mfsiat** [videojs/video.js#7056]
Hello, on the **` source `**  tag whenever I try to place any types of youtube videos the video doesn't play. It just loads and loads. 
here is my code on the **` source `** tag 
```js
<source src=<?php echo $course_details['video_url'];?> type="video/mp4"></source>
```
well, I'm taking the src from my database. The video link appears on the src tag but the video in unplayable.  
What should I do then?

**Comment by mmcc** [comment]
Hi there, if you want to play YouTube videos in Video.js you'll need to use a special tech to do so. You might want to check out the [videojs-youtube](https://github.com/videojs/videojs-youtube) plugin. Hope that helps!
