### ISSUE TITLE
Hook Events in YouTube Tech 

### ISSUE THREAD

**Issue by txwizard** [videojs/video.js#7061]
## Description
While player events are caught and handled when the default **HTML5** tech plays the video through the native code player that is built into the Web browser, when those events arise in a video that plays through the generated player implemented by the **YouTube** tech, they are ignored.

I needed two JSBins, each accompanied by a small console log, to demonstrate the issue.

1. **MP4_Demonstration_CodePen.HTML** demonstrates the behavior of the **HTML5** tech, where the play and ended events are logged, as shown in **codepen.io-1611382256396.log**.
2. **YouTube_Demonstration_CodePen.HTML** demonstrates the behavior of the **YouTube** tech, where the play and ended events are ignored because the corresponding events on the generated player don't bubble. The corresponding console log, **codepen.io-1611381660973.log**, shows but one event, **Player Opened**, whereas the **MP4** log shows three additional events: **Begin Playing**, **Pause Playing**, and **Finished Playing**.

[Hook_Events_in_YouTube_Tech_Demonstration.zip](https://github.com/videojs/video.js/files/5859772/Hook_Events_in_YouTube_Tech_Demonstration.zip) contains both pens and both log files.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Display **MP4_Demonstration_CodePen.HTML** in a Web browser.
2. Open the Developer tools, which should, by default, display the JS console log.
3. Play the video.
4. Observe the four events that appear in the log: **Player Opened**, **Begin Playing**, **Pause Playing**, and **Finished Playing**.
5. Display **YouTube_Demonstration_CodePen.HTML** in a Web browser.
6. Open the Developer tools to make the JS console visible.
7. Play the video.
8. Observe that only the first event, **Player Opened**, is logged, because it fires when the page loads.

### Expected
I expected the YouTube tech to honor the event callbacks on the standard video player events.

### Actual
The YouTube tech ignored the event callbacks on all standard video player events.

### Error output
The error is the absence of a record of _any_ of the video player events in the JS console log.

## Additional Information
Since I couldn't find the **YouTube Playback Technology for Video** plugin on a CDN, I incorporated the copy on the server where the page that hosts my completed player will reside. That page performs some very detailed logging to the database of a proprietary application on which we have several patents pending.

Since this issue is a roadblock, and I think I know how to resolve it, I cloned the repository, and I expect to submit a PR when I have a working fix.
#### videojs
The only version that I have used is the latest, **7.10.2**, since this project began at the tail end of 2020.
#### browsers
I am using Chromium **Edge**, Version **88.0.705.50** (Official build) (64-bit), as of late last night although I suspect the issue is browser agnostic.
#### OSes
I am using **Microsoft Windows Professional, Version 10.0.19042.685**, 64 bits, running on an i9 processor. However, again, I suspect this issue is OS and hardware agnostic, since the player at issue is _dynamically generated by the YouTube API_.
### plugins
**YouTube Playback Technology for Video.js 2.6.1**, taken from [https://www.npmjs.com/package/videojs-youtube-update](url)

**Comment by mister-ben** [comment]
`onplay` etc attributes are not supported by Video.js. Attaching events to or calling methods on the original element won't work with the You Tube tech as another element is used, but it also won't work consistently across all browsers with the HTML5 tech. You should always use the Video.js API instead. To add event listeners, you can use the ready callback:

```
videojs('my_video', {"techOrder" : ["youtube", "html5"]}, function() {
  this.on('play', function() {
    //...
  })
});
```

**Comment by txwizard** [comment]
Having discovered that the YouTube tech doesn't support those events, I am about to extend it so that it does. With that in mind, I just opened [Issue 578](https://github.com/videojs/videojs-youtube/issues/578) on that repository.

**Comment by gkatsev** [comment]
As @mister-ben said, `onplay` isn't officially supported. If it works, it only works incidentally, and it isn't something that we plan on supporting officially.
I would highly recommend moving away from these properties and using the Video.js events API as mentioned above. It is definitely not something that we'll be investigating to add support for when working with the YouTube tech. If `player.on('play', ...` isn't working properly, we'd be happy to take a look, though.

To elaborate on the above, the issue you see it working is that by default, we re-use the video element and because the those properties are on the video element they end up triggering. However, if you call `player.reset()` and then set a new source, you'll see that your event handlers aren't working. This is because we swap out the video element in that case. In the case of the YouTube tech we swap out the video element for an iframe element.
