### ISSUE TITLE
How to dynamically set the type in the source only through the url of the video

### ISSUE THREAD

**Issue by qiumeihui** [videojs/video.js#7064]
## Description
How to dynamically set the type in the source only through the url of the video？And my video url does not have a suffix, just a string of hash values. 

I saw the Global member `getMimeType` in the document, can someone tell me how to use it, and can it get the real mimeType of the video by just a string url?

Thanks to everyone who helped me

**Comment by qiumeihui** [comment]
Can someone help answer my question

**Comment by mister-ben** [comment]
`getMimeType()` infers the type from a few well known file extensions. If your source URL does not have a known extension, then you must specify the type.

**Comment by qiumeihui** [comment]
> `getMimeType()` infers the type from a few well known file extensions. If your source URL does not have a known extension, then you must specify the type.

thank you for your reply.
