### ISSUE TITLE
Noise at video playback on change of video quality

### ISSUE THREAD

**Issue by QuatschSalat** [videojs/video.js#7065]
## Description
While a video is played, there is a noise while switching form 360p to 720p (automatically).
The noice is produced in the Browser. It can't be reproduced in VLC or QuickTime. There is also no noise on Safari.

## Steps to reproduce
Open the following link in Chrome and wait until 15 seconds played. At approx. the 12th second, a noise can be heard at the left audio channel.
https://www.schwaebische.de/landkreis/landkreis-ravensburg/ravensburg_video,-skitour-zur-veitsburg-und-abfahrt-zum-kunstmuseum-_vidid,157944.html

### Expected
Audio playback should be without a noise while changing video quality automatically. 

### Actual
Please describe what actually happened.
Audio playback has a noise while changing video quality automatically from 360p to 720p. At approx. the 12th second.
In Firefox, there is a short silence at this point, instead a noise.

### Error output
No error in the console.

## Additional Information
Link to the HLS playlist:
https://s3.eu-central-1.amazonaws.com/video.schwaebische.de/live/hls/157944/1/157944_1_orgv_210118_Video_Skifahrer_Veitsburg.m3u8

#### videojs
Video.js 7.10.1
#### browsers
Chrome Version 87.0.4280.141 (Offizieller Build) (x86_64)
Firefox 84.0.2 (64-Bit)
#### OSes
macOS Big Sur Version 11.1 (and others)
### plugins
No

**Comment by gkatsev** [comment]
I'm not exactly sure why this is happening but I think it is likely due to the encoding of the video and potentially not anything we can do something about. I've tried a few other MSE based players as well and I can reproduce this issue there as well.

**Comment by Chinchilla86** [comment]
Hi gkatsev, we checked that already. If you open all videos directly from the playlist file, all sound streams are fine and have no noise.
The noise only appears in the video.js player when switching quality. Unfortunately not in all cases.

**Comment by gkatsev** [comment]
What players are you testing with? As I said, I've tested in a few MSE based players and got the audible pop in a few of them and not just Video.js.
If you're testing with desktop players like VLC, unfortunately, that isn't a completely accurate representation because desktop players don't have the same limitations that we have with MSE based playback.

**Comment by DanielHudson** [comment]
Maybe not related, but I'm having a similar issue with the noise artifacts when switching quality on Chrome (Mac), but the same m3u8 playlist seems fine on Safari (Mac).

**Comment by DanielHudson** [comment]
> I'm not exactly sure why this is happening but I think it is likely due to the encoding of the video and potentially not anything we can do something about. I've tried a few other MSE based players as well and I can reproduce this issue there as well.

Long shot, but if this is something to do with the encoding - can any one hazard a guess as to what might be the issue with encoding?

Also, is there anyway to hook into when stream changes so the sound could be muted during the glitch perhaps?
