### ISSUE TITLE
How to hide the control bar of mobile browser, especially, the browser of MIUI

### ISSUE THREAD

**Issue by zSergeant** [videojs/video.js#7071]
How to hide the control bar of mobile browser, especially, the browser of MIUI

**Comment by zSergeant** [comment]
This is actually a compatibility problem for mobile browsers. The control bar of video tags cannot be disabled. Other mainstream browsers, I have found a way to disable, but Xiaomi's browser is not found. So I came to this to find a solution

**Comment by mister-ben** [comment]
There's a `nativeControlsForTouch` option. You could set it to `true` for those browsers.

https://docs.videojs.com/tutorial-options.html#nativecontrolsfortouch

**Comment by SunShinewyf** [comment]
I also have this bug in Xiaomi browser, the naive control bar of browser is shown
