### ISSUE TITLE
the media playback was aborted due to a corruption problem

### ISSUE THREAD

**Issue by clintonbosch** [videojs/video.js#7072]
## Description
Playing a given hls/m3u8 in videojs causes the error 'the media playback was aborted due to a corruption problem'. This ONLY seems to happen on chrome browser on MacOS. Can not be reproduced on any other OS. The steam is provided by a third party and has been working for years, just recently started giving this error.

## Steps to reproduce
1. Play the following source in videojs player: https://dk7psf0dh3v1r.cloudfront.net/KMTV/playlist.m3u8?no_audio_only
2. Example of full hosted player can be found at https://kmtv-cdn.baobabsuite.com/public/kmtvimiginocomux.html

## Results
On most browser/OS combinations the video plays without issue, but on chrome on MacOS is fails to play back with above-mentioned error
### Expected
Normal video playback
### Actual
Please describe what actually happened.
On chrome on MacOS is fails to play back with above-mentioned error

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Have tried with multiple versions of videojs, the latest being 7.10.2
#### browsers
Chrome 88.0.4324.96 (and others)
#### OSes
macOS (Catalina 10.15.7)
### plugins
As can be seen in full player in point 2 above videojs-brand and videojs-contextmenu-ui are used

**Comment by laurent-d** [comment]
Hi @clintonbosch did you try on a Mac ARM based ?
We have same issue on M1 based mac but not on Intel ships based.

**Comment by briveira** [comment]
Any news on this? We've also hit the same problem, but I see you have already solved it somehow on the sample URL above... (can't repeat it with my Mac)

**Comment by Miran-Mirantee** [comment]
How you solved this problem?

**Comment by mister-ben** [comment]
Closing as the original stream doesn't appear to have an issue.

If anyone else is havving  a similar issue, please open a new issue with steps and a video to reproduce - these generic error messages from the video element can be bcause of various issues with the stream.
