### ISSUE TITLE
Memory Leaks From Orphaned Event Listeners

### ISSUE THREAD

**Issue by philn5d-ar** [videojs/video.js#7081]
## Description
Memory Leaks Because event listeners are not being cleaned up on dispose.

Any instance of video js would repro this, just destroy the player and check memory snapshot in devtools for Object with handlers for "bandwidthupdate" "timeupdate" etc. I've spent considerable time tracking this down already and the code needs work to clean this up - it's self-evident if you look at the on("bandwidthupdate", function()...) and there is no off("bandwidthupdate") 

Also, the anonymous function isn't helping matters either since it cannot be removed by name.

This is especially a problem with several videos, each loading new instances of whatever wires up the event handlers. I'm looking at obfuscated code in a production environment so it's hard to say exactly what's what. Ima SDK is also leaving orphans when the AdsLoader is destroyed but that's a different problem.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Look at the code and see the evidence that some event listeners are added but not removed. Others are being removed during dispose but not all.
2. Suggested fix: keep track of the event listeners, name the event listener functions rather than using anonymous, make life grand!

### Expected
No memory leaks from orphaned event handlers.

### Actual
Memory leaks from orphaned event handlers.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.10.2
#### browsers
what browser are affected? That would be all browsers, right?
#### OSes
what platforms (operating systems and devices) are affected? Would be all platforms too.
### plugins
are any videojs plugins being used on the page? If so, please list them below. This is probably from videojs/http-streaming. After a search through the whole videojs org, "bandwidthupdate" is there.

```
        t.setupSegmentLoaderListeners_ = function() {
            var n = this;
            this.mainSegmentLoader_.on("bandwidthupdate", function() {
                var e = n.selectPlaylist()
```

**Comment by gkatsev** [comment]
This was discussed in slack. The tl;dr was that a bunch of the previously seen leaks have been fixed. We look out for them every so often and fix it as we go.
Going to close this for now but if we get actionable intel on memory leaks we'd definitely take a look.
