### ISSUE TITLE
Video freezes after a few second in high speed playback on Chrome

### ISSUE THREAD

**Issue by blizzardplus** [videojs/video.js#7084]
## Description
I have a videojs player embedded in an HTML page and by default I set the playback speed to 10x.
The video starts playing but after a few seconds, the video freezes while the audio is still playing. If I rewind manually the video will start playing again.
This only happens on Chrome. The same video plays fine in Firefox.

## Steps to reproduce
1. Open a video page in Chrome (Version 88.0.4324.96 (Official Build) (64-bit))
2. Play the video.
3. Wait a few second, the video will freeze.

### Expected
The video will freeze after a few seconds. Rewind or fast forward using seek buttons, and the video will start playing again.

### Actual
The video should not freeze.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.7.5
#### browsers
what browser are affected?
Chrome (Version 88.0.4324.96 (Official Build) (64-bit))
#### OSes
what platforms (operating systems and devices) are affected?
Windows 10 and Ubuntu 20.10
### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-seek-buttons

**Comment by blizzardplus** [comment]
I noticed that with lower playback speed, e.g. 8x or 6x, there's less chance of running into this issue.

**Comment by blizzardplus** [comment]
Another point: The video seems to be jumping to a frame from few minutes in the future and freezes on that frame, while the audio is playing. The video restarts when the audio catches up to the same frame as the video.
So basically, it's an issue with video jumping too far ahead, while the audio doesn't, causing the player to skip a chunk of the video and the video/audio to be out of sync for a while.

**Comment by blizzardplus** [comment]
Same result with videojs 7.11.4

https://hoomanm.info/video-player-test2/index2.html?VideoID=da7da6a6e60b20fb-42f45a41&VideoSpd=10

**Comment by blizzardplus** [comment]
I found a work around: every 2 seconds, reset the `currentTime` variable: 
```
var isPlaying = false;

player.on(['waiting', 'pause'], function () {
    isPlaying = false;
});

player.on('playing', function () {
    isPlaying = true;
});

function refresh_player() {
    if (isPlaying) {
            var ct = player.currentTime()
            player.currentTime(ct);
    }
}

setInterval(refresh_player, 2000); // Time in milliseconds

```

I still think this bug needs to be investigated!

**Comment by blizzardplus** [comment]
After some digging, I realized this is a bug in HTML5 video playback in Chrome and reported it here: 
https://bugs.chromium.org/p/chromium/issues/detail?id=1175393

**Comment by gkatsev** [comment]
Thanks for opening an issue against Chrome. Sounds like it'll be fixed soon in Chrome 89? If so, can this be closed?

**Comment by blizzardplus** [comment]
Yes, closing this.
