### ISSUE TITLE
The seek bar and the video feed is not up-to-date when switching back from other tab

### ISSUE THREAD

**Issue by boldizsarnemeth** [videojs/video.js#7086]
## Description
The seek bar and the video feed is not up-to-date when switching back from other tab

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Go to the example video: https://videojs.com/city
2. Start playing it
3. Switch to another tab
4. Wait for the video to finish
5. Switch back to the video tab

### Expected
The video player looks the same as it would after playing the video normally.
![Screenshot 2021-02-08 at 10 30 28](https://user-images.githubusercontent.com/53467689/107201008-bd14e080-69f8-11eb-8e5a-7383113c4a47.png)

### Actual
The video feed and the seek bar is not updated to the latest frame.
![Screenshot 2021-02-08 at 10 29 58](https://user-images.githubusercontent.com/53467689/107201483-53490680-69f9-11eb-8ba3-b3f9a1a0a7a8.png)

### Error output
There is no error output.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Latest (tested with the demo page.)
#### browsers
Chrome 88.0.4324.150
#### OSes
MacOS 11.0.1
### plugins
None that I know of.

**Comment by gkatsev** [comment]
I believe we don't update the control bar when hidden, like in an inactive tab. Then, if were still playing, when we come back, the progress bar continues updating. It sounds like when we're ended, we don't end up updating it, or we potentially should update it once we become active again.

**Comment by boldizsarnemeth** [comment]
@gkatsev Yes, and please update the video frame to the last as well once the user navigated back.

**Comment by gkatsev** [comment]
I'm not sure if we'd be able to update the video frame because that is up to the browser.
But we'll definitely look into it.

**Comment by gkatsev** [comment]
Looks like it's because of the requestAnimationFrames we have. We have an older one queued up with the previous percentage and then when we get back it triggers before the new one which causes our internal checks to get out of sync and not update the control bar.

**Comment by gkatsev** [comment]
Looks like the fix I have often does have the frame update with it, but I have seen it not get updated some times. Unfortunately, I think we can't do anything about that.
