### ISSUE TITLE
Video  always  at the top level

### ISSUE THREAD

**Issue by lqdahv** [videojs/video.js#7089]
When the video is played, the browser style overwrote the video.js style, and the video is always on the top layer, so the pop-up layer cannot be operated
![Screenshot_2021-02-13-16-58-47-858_com qihoo contents](https://user-images.githubusercontent.com/24808833/107846301-a36f0100-6e1d-11eb-8d2f-ed22a943cbe2.jpg)
![Screenshot_2021-02-13-16-58-55-281_com qihoo contents](https://user-images.githubusercontent.com/24808833/107846303-a833b500-6e1d-11eb-8c2e-70e8fea3f557.jpg)

**Comment by mister-ben** [comment]
What browser are you using? It sounds like the browser doesn't allow any HTML to display over the video element, which is beyond Video.js's control.

**Comment by lqdahv** [comment]
> What browser are you using? It sounds like the browser doesn't allow any HTML to display over the video element, which is beyond Video.js's control.

This seems to be a browser problem, there is no solution, it will not happen if I use chrome
