### ISSUE TITLE
CSP blocks videojs from playing in firefox addon

### ISSUE THREAD

**Issue by dhaven** [videojs/video.js#7092]
Hi ! 
I'm looking for some guidance regarding using videojs from within a browser extension. The issue I am having is regarding CSP constraints within a browser extension which a blocking the video from playing. If I setup a minimal firefox addon with a html such as

```html
//redacted
<body>
  <video-js id=example-video width=960 height=540 class="vjs-default-skin" controls>
  <source
     src="https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8"
     type="application/x-mpegURL">
  </video-js>
</body>
<script src="app.bundle.js"></script> --> videojs bundled using webpack
```

The error I get is :

`Content Security Policy: The page’s settings blocked the loading of a resource at blob:moz-extension://874afab4-75ee-5a4d-8319-4c0cb3dca1f6/ea522760-f5b2-7c4a-9b09-fbcc58afcf3d (“script-src”).`

This message seems to be triggered after a player.src() command which updates the video tag with `src="blob:moz-extension://874afab4-75ee-5a4d-8319-4c0cb3dca1f6/909f2695-efe9-3a4f-9aeb-0a01cde67e53"`

One workaround I have found is to update the manifest.json for the browser addon with the entry :
`"content_security_policy":"script-src 'self' blob:; object-src 'self';"`

But changing the CSP rules like this is [documented](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy#invalid_examples) as being a security risk. What would be the recommended way to get this working ?

**Comment by gkatsev** [comment]
Given that we use MSE for HLS based playback, allowing blob urls is a must. Looking at the page you linked it sounds like mozilla disallows addons that do this? In that case, it sounds like this won't  be allowed, unfortunately.

Looking at similar extensions for mozilla, looks like they have the same issue. They're only able to play back m3u8 if opened directly rather than embedded on a site.

**Comment by dhaven** [comment]
By 'opened directly' you mean if the video file is present on the client ?

> Looking at similar extensions for mozilla, looks like they have the same issue.
Could you point me to these extensions please ?

The part I was concerned with is : `Note: Valid examples display the correct use of keys in CSP. However, extensions with 'unsafe-eval', 'unsafe-inline', remote script, blob, or remote sources in their CSP are not allowed for extensions listed on addons.mozilla.org due to major security issues.` But I haven't gone through a release process so I can't know for sure.

Thanks for your help,

**Comment by gkatsev** [comment]
I.e., if you a user navigates directly to https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 rather than having it be on a page.
https://addons.mozilla.org/en-US/firefox/addon/native_hls_playback/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by dhaven** [comment]
Thanks for your help ! I will close this as no further action is needed.
