### ISSUE TITLE
During live video streaming seek bar not being displayed, only able to see Live

### ISSUE THREAD

**Issue by chinmaykude** [videojs/video.js#7095]
## Description
When live streaming a video the seek bar is not being displayed, This was not the case earlier. Now only Live is being displayed. 
After the live stream is over then seekbar is visible. 
This happens in both chrome and firefox.
Using video.js inside reactjs project.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load video with the intended source url
2. Play the live video and it the issue would replicate. No seekbar and only Live is displayed
3. After the live stream ends seekbar successfully appears.

### Expected
While streaming live videos seekbar should be visible.

### Actual
During live video streaming seek bar not being displayed, only able to see Live

### Error output
N/A

#### videojs 
7.8.2

#### browsers 
Chrome, Firefox

#### OSes
Mac

### plugins
videojs-contrib-quality-levels, videojs-hls-quality-selector

**Comment by brandonocasey** [comment]
1.You will have to pass in the `liveui` option as `true` when creating the player in order to show the new live ui with a seek bar. 

2. Your stream will also have to have a total seekable range of >= 30s by default. Unfortunately we haven't documented changing that 30s threshold yet, but its just another option that has to be passed in during player creation. It should be passed in as a liveTracker option:  `liveTracker: {trackingThreshold: <someNumber>}`, if you wanted to change that.

**Comment by gkatsev** [comment]
Though, I'd probably recommend against decreasing the tracking threshold.

**Comment by chinmaykude** [comment]
@brandonocasey 
I am passing the `liveui` option as `true` when creating the player. But still, the issue remains.

**Comment by chinmaykude** [comment]
@gkatsev 
Can you please elaborate more on why not to decrease the tracking threshold? 
And any know causes causing this behavior?

**Comment by gkatsev** [comment]
If your stream only has 30 seconds worth of content to seek with, that doesn't really help the user much since they'll only be able to seek within the 30 second timeframe.
Do you have a stream you can share with us?

**Comment by chinmaykude** [comment]
Cool got it, but in my case, the stream would last for a minimum of an hour.

I can't share the stream, unfortunately.

This was not an issue before but since few days, seek bar is not being displayed in the live stream and appears after the stream is over.
