### ISSUE TITLE
player.tech({ IWillNotUseThisInPlugins: true })

### ISSUE THREAD

**Issue by rastogi19** [videojs/video.js#7100]
for getting bitrate information can we use the below api in the latest video.js versions 
player.tech({ IWillNotUseThisInPlugins: true })
as this is mandatory in older versions of video.js 5.x

**Comment by gkatsev** [comment]
You no longer need to pass that clunky object in Video.js 6 and newer. `player.tech()` will work, though it'll log a warning. You can pass *anything* to that method to prevent the warning.
