### ISSUE TITLE
Timeupdate keeps running after video is paused.

### ISSUE THREAD

**Issue by danavangard** [videojs/video.js#7101]
@gkatsev, you mentioned: _I believe this is fixed in videojs 5. We no longer attach the `play`/`pause` events for `manualTimeUpdatesOn` to the player._

_Originally posted by @gkatsev in https://github.com/videojs/video.js/issues/1641#issuecomment-235100787_

However, **the issue is recurring for me at least when I use the Youtube Tech 2.6.1 and play a Youtube video from the Youtube site**. Before videojs 7.11.4 up to the latest version, the "`timeupdate`" still keeps running _after_ the player gets paused. I manage to replicate this annoyance by using a custom slider of `input type range` whose focus dynamically pauses the player ( `videojs.pause()` ) immediately before seeking with the slider's "`input`" event ( `videojs.currentTime(slider.val())` ). This only happens if the player was _playing_ prior to seeking with the slider. If I would stop the player via a custom button ( `videojs.pause()` ), then go to my slider and move the handle, the "`timeupdate`" event will stop after I release the slider handle.

I gather in the former manner the slider, while the video is playing, being a `range input`, _trips_ the "`timeupdate`" event while sliding (even if it pauses the video) which "`timeupdate`" gets stuck and doesn't stop on its own this way once the slider is not used anymore. This means "`timeupdate`" is running in the background while other code is being used, which makes for erratic seeking behavior and poor UX which must be avoided in my application.

Any thoughts on how I can detach the "`timeupdate`" event from my slider?

UPDATE: I've put in bold what has been updated above.

**Comment by gkatsev** [comment]
I'm not really sure if I follow you. Can you make a reduced test that showcases your issue?

**Comment by danavangard** [comment]
Thx for swift reply. I've updated my original post (in bold). It currently happens when using the Youtube Tech 2.6.1 and playing a Youtube video from the Youtube site. I'm fiddling on this now.

**Comment by danavangard** [comment]
Ok, I adapted a CodePen to replicate the issue. Make sure CodePen console is open, play video, then drag the range slider below. Clear console to see if any "`timeUpdate`" log _reappears_, repeat the above until it does because it's erratic and unpredictable to replicate, but ultimately Youtube will provoke it. Looks like Youtube's buffering is the culprit. Maybe detaching "`timeUpdate`" while seeking would help? In my application, "`timeUpdate`" while seeking is of no use.

See CodePen here: codepen.io/danavangard/pen/poNrwRR

**Comment by gkatsev** [comment]
I'm not seeing anything wrong on the page. `timeupdates` happen during seeking because they are triggered each time that the currentTime of the video changes.
Using either the Video.js progress control or the slider you made, when I seek around by dragging, I get lots of timeupdate events. When I stop, while it may take a second to catch up to already triggered timeupdate events, the timeupdates also stop.
I've tried seeking and what not for a few minutes now, and it seems to be working as expected.

**Comment by danavangard** [comment]
Hmm. I manage to replicate it on my end. I also observe that the `timeupdate` triggering seems to be caused when the `waiting` event is triggered, which also keeps the spinning buffer logo displayed forever until the `play` button is pressed again.

If `timeUpdate` would stop running while videos are in `waiting state` (buffering), then everything would be fine. Is it possible to detach `timeupdate` during `waiting state`?

**Comment by danavangard** [comment]
But too many unknowns here. I'll have to dig in deeper into this since it affects the UX of my application. Feel free to close issue if nothing can be done at your end. Thx for input.

**Comment by danavangard** [comment]
On line 10828 of Video.js 7.11.4, if I change `this.manualTimeUpdatesOn` to `this.manualTimeUpdatesOff` like so:

```
   if (!_this.featuresTimeupdateEvents) {
        _this.manualTimeUpdatesOff();
      }
```
... then the `timeupdate` bug is solved, at least on my end.

**Comment by danavangard** [comment]
Using `_this.clearInterval(this.currentTimeInterval);` behaves better. Where in VideoJs should I set the interval back again while player is playing?

**Comment by danavangard** [comment]
This 2014 issue pretty much sums up what I've detected: https://github.com/videojs/video.js/issues/1641

"If you just let the video play without interfering, everything will work as expected. The [`timeupdate`] event will stop firing every time that playback stalls. However, once you seek to another time you'll notice that the event will keep on being fired even when playback stops due to buffering."

That's what currently also happens to me. I don't know if this issue can be definitely solved, still working on it, in meantime, as mentioned in my previous comment, if I could clear the interval upon seeking and have it reenabled once buffering is over and video is ready to play again would be awesome indeed. Thx for input.

**Comment by danavangard** [comment]
**UPDATE**

I think I solved the issue! The code below works for me with YouTube external video and local video. Only the code below needs to be amended accordingly:

**video.js 7.11.4**
Between lines 11030 - 11050. See "Added code" comments:

```
_proto.manualTimeUpdatesOn = function manualTimeUpdatesOn() {
      this.manualTimeUpdates = true;
      this.on('play', this.trackCurrentTime);
      this.on('pause', this.stopTrackingCurrentTime);
      this.on('seeking', this.stopTrackingCurrentTime); // Added code
      this.on('waiting', this.stopTrackingCurrentTime); // Added code
    }
    /**
     * Turn off the polyfill for `timeupdate` events that was created in
     * {@link Tech#manualTimeUpdatesOn}
     */
    ;

    _proto.manualTimeUpdatesOff = function manualTimeUpdatesOff() {
      this.manualTimeUpdates = false;
      this.stopTrackingCurrentTime();
      this.off('play', this.trackCurrentTime);
      this.off('pause', this.stopTrackingCurrentTime);
      this.off('seeking', this.stopTrackingCurrentTime);  // Added code
      this.off('waiting', this.stopTrackingCurrentTime);   // Added code
    }
```
So now when video plays the `timeUpdate` runs according to VJS setInterval, and when I drag my range input slider that dynamically pauses and seeks VJS player, `timeupdate` stops running. Finally, I can rest my head lol! Hope this helps others.
