### ISSUE TITLE
video/mp2t not working

### ISSUE THREAD

**Issue by ghost** [videojs/video.js#7104]
I have a problem to be able to reproduce a type of stream, with the VLC player it works, but not here, the type of codec is in the image below, and also my code

![Sem Título](https://user-images.githubusercontent.com/9480073/108602149-5f897800-7398-11eb-8adc-8ef13604c417.png)

![Sem Título3](https://user-images.githubusercontent.com/9480073/108602211-ce66d100-7398-11eb-9cf6-7a1a263d221d.png)

![Sem Título2](https://user-images.githubusercontent.com/9480073/108602175-89429f00-7398-11eb-85ad-9d424327daab.png)

**Comment by gkatsev** [comment]
Unfortunately, we don't support playing back mp2t video directly, only in the context of an HLS stream.

**Comment by mjoelmendes** [comment]
OK.
Can using: videojs / mux.js reproduce?

**Comment by joseantmazonsb** [comment]
Any updates on this? Or any suggestions on where to look to implement it myself and submit an PR?
