### ISSUE TITLE
Changing play/pause button & full screen button controls to text instead of icons

### ISSUE THREAD

**Issue by benlevywebdesign** [videojs/video.js#7105]
Hello,

I would like to know if it's possible to change the play/pause button control and the full screen button control into text instead of the icon font. It would match the design of my website a bit more if this is something easy to do.

Thank you!

**Comment by benlevywebdesign** [comment]
I'm leaning away from the idea of text instead of icons someone still might want to know how to do it!

**Comment by Lavish883** [comment]
I am not a expert in css but where you have Video-js.css. Open it up and there are going to be a lot of classes and pretty sure you can change ::before for whatever class or icon you want to change delete it and set a background-image of the image/icon you want to put. 
For Example , I want to change the pause Icon. I go in the css file and find class .vjs-icon-pause:before, .video-js .vjs-play-control.vjs-playing .vjs-icon-placeholder:before. Remember to pick the one that has ::before. And delete it contents like for pause delete content =""\f103";" Keep in mind for every icon the content is different. And after you delete that set the background image to a url where you have the custom pause icon. Like this background-image: url(/images/pause.svg);

Hope you find it helpful, I am not sure if it would work 100%. But with my knowledge of css it should work. Tell me if it works. 😄

**Comment by benlevywebdesign** [comment]
I don't want any icons. Instead I want text or the words play, pause, full screen etc. It's easy enough to make the changes in the css though but I do like the icons and I am getting used to the look not being how I use to have it with the words.
