### ISSUE TITLE
Reset cached values when the source changes

### ISSUE THREAD

**Issue by iamjem** [videojs/video.js#711]
The internal cache should be reset whenever a new video source is loaded, otherwise its possible to read values from a previous video. For example

```
// embed a video at some point, and attach an event listener
var player = videojs('video-id');
player.on('loadstart', function(){
    initOtherComponentsThatDependOnVideoSrc();
});

var initOtherComponentsThatDependOnVideoSrc = function(){
    // to guard against race conditions components might
    // do player state checks, for example looking to see if
    // duration() is available yet, if not attaching an event listener
    // to durationchange/loadedmetadata, etc and prostponing
    // certain initialization code till later
};

// playback carrys on for a few seconds, then we do this:
player.src({ type: "video/mp4", src: "some/other/video.mp4" });

// initOtherComponentsThatDependOnVideoSrc gets triggered again, BUT
// their state checks return old meta data from the previous video. fail.
```

**Comment by alirezastack** [comment]
I have the same issue on videoJS v4.0.4. The link is the same but the video is changed on the server side. When I copy that link into browser address bar it plays the newly updated one but video js plays the old one. What is the solution? Is there a way to clear internal cache?

**Comment by ganeshchukka** [comment]
> I have the same issue on videoJS v4.0.4. The link is the same but the video is changed on the server side. When I copy that link into browser address bar it plays the newly updated one but video js plays the old one. What is the solution? Is there a way to clear internal cache?

same thing

**Comment by MarcinKarpeta** [comment]
Same here. I'm using dash streaming. Each time I change source I have old cache_ object which leads to i.e. displaying artefacts...
