### ISSUE TITLE
Odd mobile issues (maybe a bug?)

### ISSUE THREAD

**Issue by altude** [videojs/video.js#7110]
## Description
On mobile (iPhone, Android not tested) my videos are not working. At first, they would load forever. (File type: MOV) This made me think that perhaps it was an issue with my CDN. However, when I access it from the source (no video.js) it works just fine. I tried encoding my videos using Azure Media Services (MP4) After that I get a "File type not supported" error. All this time, desktop is working just fine.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Using video.js forest from the unpkg CDN
2. Using Azure blob storage for videos but I'm using a CNAME that goes to cdn.huelet.net, "File not supported" error after encoding
3. Mobile, iPhone, sorry I'm not human because I don't have an android.

## Results
Loading forever (no encoding) file not supported error (AMS encoding)
### Expected
I expected it to play the video, maybe with some loading time.
### Actual
Loading forever (no encoding) file not supported error (AMS encoding)
### Error output
"File not supported" error
### version
7.10.2 (css & js)
#### browsers
All iOS browsers 
#### OSes
IOS (Maybe android)
### plugins
None

**Comment by mister-ben** [comment]
mov isn't widely supported in browsers, but MP4 is. If it doesn't play there's a problem with how the file is encoded or hosted. Safari is fussy about range header support for example.

**Comment by lerichardson** [comment]
Unfortunately, the exact same thing happens with mp4 with mov.  
So, a summary:  
MOV unencoded; loads forever
MP4 unencoded; loads forever
MOV encoded to MP4; "File type not supported"
MP4 encoded to MP4; "File type not supported"

**Comment by gkatsev** [comment]
Are you able to a sample mp4/mov file that isn't playing for you?

**Comment by lerichardson** [comment]
You mean use a sample video? I tried [this one](https://vjs.zencdn.net/v/oceans.mp4). Worked great on desktop, same issue on mobile.

**Comment by gkatsev** [comment]
are you playing it from our CDN or from your own host/CDN?

**Comment by lerichardson** [comment]
The test video is from your CDN. All the other videos I've tried are from my CDN.

**Comment by lerichardson** [comment]
I was able to get a friend to try it out on android. I can now confirm this is an iOS-only issue.

**Comment by lerichardson** [comment]
Sounds like the same thing, but I can't check the console on my iPhone. What would abort the media? Any ideas?

**Comment by altude** [comment]
Very stale issue
