### ISSUE TITLE
【mobile】the native control bar is shown in MIUI browser when nativeControlsForTouch is false

### ISSUE THREAD

**Issue by SunShinewyf** [videojs/video.js#7115]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. create an example with videojs
2. open in MIUI browser
3. the native control bar of MIUI browser is shown

### Expected
show my custom control bar instead of native control bar

### Actual
show the native control bar of MIUI browser

![image](https://user-images.githubusercontent.com/11244400/109787181-ecf68300-7c48-11eb-8b6a-1c45deeb1d7c.png)

**Comment by mister-ben** [comment]
Unfortunately it's a problem with the MIUI browser, which we can't influence. It doesn't allow other elements including controls to be placed on top of the video element.

**Comment by SunShinewyf** [comment]
@mister-ben is there any solution to hide the native control bar, such as use css or js?

**Comment by mister-ben** [comment]
No. The regular Video.js controls _are_ CSS and JavaScript. It's a browser limitation.
