### ISSUE TITLE
How to remove the click event, but remain the fullscreen event

### ISSUE THREAD

**Issue by DevsimX** [videojs/video.js#7123]
## Description
-  i use the the controls, but when i click the video, it will pause, i want to remove this event, what should i do? 
 if i cancel the pointer-event in css, the all controls will be removed. but i want to use the fullscreen button.
 which means i only need to use the fullscreen button, how can i do it? help

**Comment by gkatsev** [comment]
Unfortunately, we don't have an option for that right now. Though, I think we've gotten a few requests for this, so, maybe an option for this makes sense. We have [`userActions.doubleClick`](https://docs.videojs.com/tutorial-options.html#useractions.doubleclick), so, maybe a `userActions.click` makes sense.
If you're interested in making a PR, that would be great. Would require updating `handleTechClick_` here https://github.com/videojs/video.js/blob/0cc8684120ef645cf1cf9975082b9e29168dc78e/src/js/player.js#L1921-L1925 with that option similarly to how it's used in `handleTechDoubleClick_` right now here https://github.com/videojs/video.js/blob/0cc8684120ef645cf1cf9975082b9e29168dc78e/src/js/player.js#L1950-L1977

**Comment by Youmyin** [comment]
Following
