### ISSUE TITLE
The Media playback was aborted due to... on samsung TV on videojs 7.10.0 and higher

### ISSUE THREAD

**Issue by Pouryakordi** [videojs/video.js#7125]
Hi
I've been trying to stream video using hls on Samsung TV but I kept getting this error "The media playback was aborted due to a corruption problem or because the media used features your browser did not support" and it's not just me we've got a lot of reports from users so I'm sure it's not the TV.
I accidently used lower versions of Videojs using a cdn and it started working so I traced back the problem, the issue doesn't exist till Videojs 7.9.7 and it appears from 7.10.0 and higher.

some context:
1. I've tryed 
    var player = videojs('video', {
      html5: {
        vhs: {
          overrideNative: !videojs.browser.IS_SAFARI
        },
        nativeAudioTracks: false,
        nativeVideoTracks: false,
        nativeTextTracks:true
      }
    });

2. I've tried different video formats and manifests and turns out not all videos have this problem for example these two one of them works fine and the other prompts that mentioned error:

works fine: https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/gear4/prog_index.m3u8

has error: https://traffic.upera.tv/2752930-0-hls.m3u8?ref=erMA

unfortunately the second link is not available outside of Iran it's h264 turned into .ts files using ffmpeg and a standard manifest.

3. the problem appears only on samsung TVs other devices even other smart TVs are fine (at least the ones we could test on).

**Comment by gkatsev** [comment]
Are you saying that Video.js 7.9.7 is working but v7.10 and newer isn't?

**Comment by Pouryakordi** [comment]
> Are you saying that Video.js 7.9.7 is working but v7.10 and newer isn't?

Yes

**Comment by gkatsev** [comment]
Thanks for confirming. In Video.js 7.10 we updated to a major version of our playback engine and something there must've changed and broke for samsung TVs

**Comment by Pouryakordi** [comment]
Yeah Samsung TVs have a weird relation with js if it works on every other device and browser it's not guaranteed that it'll work on Samsung TVs and most of the time we have to test Separately.
Currently this is not a major issue for us I just wanted to let you know and also we would like to update to newer versions whenever it's possible.
thanks for your Response.

**Comment by gkatsev** [comment]
Yeah, unfortunately, we don't really have any TVs to test with, however, it's something that we'd want to support. In addition, we're kind of swamped with issues, particularly dash related, on regular browsers, so, samsung tv support is kind of on the back burner.

**Comment by EgidijusL** [comment]
The same problem that causes me to use version 7.9.7
