### ISSUE TITLE
Vue3 support?

### ISSUE THREAD

**Issue by elinholde** [videojs/video.js#7126]
Are Vue3 supported?

Cant seem to find any info regarding Vue3 and my attempts so far has been unsuccessful.

**Comment by gkatsev** [comment]
We don't really use vue ourselves but Video.js is framework-agnostic and should work with all major frameworks. We have a sample on creating a vue component for Video.js here https://docs.videojs.com/tutorial-vue.html

**Comment by srkn65** [comment]
When I add subtitles to a youtube video with videojs it works with vue2. But it doesn't work with vue3
