### ISSUE TITLE
Add dynamic watermarks

### ISSUE THREAD

**Issue by EthosData** [videojs/video.js#7130]
Hello,

First of all, congratulations for this! it is an awesome player.

We are trying to use this player for our web application to give the possibility to play videos on the browser. One of our needs is that videos must have some kind of watermark (text) showing through the whole video for security purposes. 

I know there is a plugin that allows this (https://www.npmjs.com/package/videojs-watermark-with-text). However we would like to have a dynamic one instead of having the same watermark for all the videos. Ideally if we can add to the watermark text some of the user context information; for example, the user email ID.

As background our web application authentication uses cookie sessions.

Is this something that can be done? 

Thanks!

**Comment by mister-ben** [comment]
If you know that information about the current users, you could just intialise that plugin with whatever options you want e.g. `player.watermark({text: 'user: 1234'});`

**Comment by sbbullet** [comment]
Hey @EthosData,  I wanted the same functionality and used the same package but it didn't fulfill my needs. I wanted to customize the appearance of my text watermark as well. Also, I found that one can inspect the watermark element and remove it from DOM. Even if it is revived by the plugin, we can easily change the CSS of the class of the watermark element and easily remove it. Also, we can easily change the CSS class of that watermark element and make it disappear.

These problems led to making this plugin [`videojs-dynamic-watermark`](https://www.npmjs.com/package/videojs-dynamic-watermark) that can't be removed from the DOM and the appearance of the watermark element can be customized as per your needs.

```js
var player = videojs("my-video");

  player.dynamicWatermark({
    elementId: "unique_id",
    watermarkText: "It will be displayed over video",
    changeDuration: 1000,
    cssText:
      "display: inline-block; color: grey; background-color: transparent; font-size: 1rem; z-index: 9999; position: absolute; @media only screen and (max-width: 992px){font-size: 0.8rem;}",
  });

```

If you want the watermark to be an image or any other element, there's a tricky hack to do that like this:

```js
var player = videojs("my-video");

  player.dynamicWatermark({
    elementId: "unique_id",
    watermarkText: "<img height='20' width='20' src='https://i.pravatar.cc' />",
    changeDuration: 1000,
    cssText:
      "display: inline-block; color: grey; background-color: transparent; font-size: 1rem; z-index: 9999; position: absolute; @media only screen and (max-width: 992px){font-size: 0.8rem;}",
  });
```

If you have any other suggestions, you can make a PR or drop an idea.
