### ISSUE TITLE
Play at start event missing

### ISSUE THREAD

**Issue by jozeflambrecht** [videojs/video.js#7131]
I track in a database who clicked on the Play button with
```
player.on('play', function() {
	    $.ajax({
	      	type: 'POST',
	        url: '/resources/{{ $resource->id }}/started',
	        data: {
	        	videoId: {{ $resource->id }},
	        	_token: "{{ csrf_token() }}"
	        }
	    });
	});
```
When the user pauses and resumes, I have a new entry. How can I avoid this? Is there an event for playing/starting the video at t = 0?

Thanks!

**Comment by gkatsev** [comment]
While `firstplay` exists, I would recommend against using it and instead checking the `currentTime()` of the video when you receive the `play` event. `firstplay` is currently deprecated and will be removed with the next major version.

**Comment by jozeflambrecht** [comment]
@gkatsev thanks! I used `myPlayer.one('play');` instead. Or is this also deprecated?

**Comment by gkatsev** [comment]
Oh, totally forgot about that. Yes, that's a great usecase for `.one`.
