### ISSUE TITLE
Live Videos don't seek to the live edge when playback starts on Safari with overrideEnabled = true

### ISSUE THREAD

**Issue by claudiah12** [videojs/video.js#7132]
## Description
When overrideEnabled is true, live videos on Safari will start playing from the 00:00 timestamp rather than the live edge of the video.

It looks like in live-tracker, seekToLiveEdge() is being called on the first time update after play, but at this point isAtLiveEdge() returns true, so no seeking occurs. I believe this is due to the fact that when we haven't seen a timeupdate yet, we set isBehindLiveEdge to false([source](https://github.com/videojs/video.js/blob/3d676d68ca863795e2c6902bc9b495a0e8a7571a/src/js/live-tracker.js#L111)). When the first time update is seen, we immediately call seekToLiveEdge(), but trackLive_ is just executing at an interval so it may have not been called again to update the isBehindLiveEdge before we check its state in seekToLiveEdge().

It seems that this race condition would be solved by adding a call to trackLive_ inside handleFirstTimeupdate(), to ensure the value of isBehindLiveEdge is updated immediately.

Unfortunately I don't have a sample stream to share since this issue is specific to live streams.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Enable overrideNative in the vhs options
2. Play a live video on Safari (autoplay or manual play)

### Expected
Video will start playing from the current live time

### Actual
Video starts playing from the 00:00 timestamp

**Comment by hattapoglu** [comment]
I had experienced the same issue with Safari and I solved it by adding: 

```
player.one('loadedmetadata', player.liveTracker.seekToLiveEdge();
```

**Comment by gkatsev** [comment]
```
player.one('loadedmetadata', player.liveTracker.seekToLiveEdge);
```
seems like an ok workaround.

While it generally works, we definitely don't do much testing in Safari right now and would probably recommend against using VHS with Safari.

**Comment by luesp15** [comment]
> I had experienced the same issue with Safari and I solved it by adding:
> 
> ```
> player.one('loadedmetadata', player.liveTracker.seekToLiveEdge());
> ```

Hi ,
I tried this solution and it seems to work at first (see image). 
![Schermata 2021-04-29 alle 18 23 56](https://user-images.githubusercontent.com/61965311/116589998-88d8fe00-a91d-11eb-9c88-329382602ea7.png)


But when I click play, the tracker goes back to the beginning and the video doesn't start live.

Any solution?
