### ISSUE TITLE
When the sound and picture of the video source are not synchronized, the playback on the phone fails

### ISSUE THREAD

**Issue by a354123417** [videojs/video.js#7133]
## Description
If you use videojs, it fails to play on the phone, if you use alipayer, you can play, and the loading speed of alipayer is faster than videojs.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.https://5gvr.school-live.cn/vr/aliplayer/vplayer.html

**Comment by mister-ben** [comment]
The example plays on Android Chrome. Can you explain the issue and steps to reproduce in more detail?

**Comment by a354123417** [comment]
> The example plays on Android Chrome. Can you explain the issue and steps to reproduce in more detail?

em... in wechat

**Comment by a354123417** [comment]
There are also problems in the latest version of firefox.

**Comment by gkatsev** [comment]
I was able to get the stream to play on our test page in firefox https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&sync-workers=false&liveui=false&partial=false&llhls=false&url=https%3A%2F%2Fschool-live.oss-cn-shanghai.aliyuncs.com%2Frecord%2Ftx_live%2F2924_3153_2%2Fceshi_ts_1.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&override-native=true&preload=auto&mirror-source=true

**Comment by gkatsev** [comment]
I would try and see if Video.js 7.11.7 helps at all, there's a slightly updated playback engine there.

**Comment by a354123417** [comment]
> I would try and see if Video.js 7.11.7 helps at all, there's a slightly updated playback engine there.

OK, Thanks!
