### ISSUE TITLE
YouTube Iframe problem [Question]

### ISSUE THREAD

**Issue by snaildos** [videojs/video.js#7135]
## Description
Hello, Recently, I moved a live stream too another youtube channel, video-js works perfectly with livestreams, HOWEVER, YouTube has **died** on me, I CANNOT enable iframe (on the livestream settings) without getting a api error. 🤔 So, is there any other way I could achieve this without a Iframe?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use video.js on a live stream
2. Turn off iframe on video.js
3. Won't work.

### Expected
Obviously this wont work. but, is there anyway I can achieve a better solution?

All answers appreciated!

**Comment by gkatsev** [comment]
Can you elaborate on what you mean by step 2? How are you loading the video? If you're using videojs-youtube to play a youtube video, you *must* allow iframes because the youtube API works via iframe.
If you can provide a live reduced example we can help see what the issue is.

**Comment by snaildos** [comment]
So- I can't enable the Iframe on youtube,
https://media.discordapp.net/attachments/736072741228118016/819522466673328128/unknown.png
As seen here, there is a API error regarding too update the settings. I don't know where/how to contact youtube support. 
Is there any other way to do this?

**Comment by snaildos** [comment]
I'm just trying to think of a workaround- 🤔 
I honestly don't know what to do here. YouTube is absolutely broken...

**Comment by snaildos** [comment]
This won't work
