### ISSUE TITLE
Twitch Support??

### ISSUE THREAD

**Issue by snaildos** [videojs/video.js#7137]
## Description
Quick question, does video.js support twitch?
If not, is there anyway I can get it too work?

**Comment by gkatsev** [comment]
We don't support it natively. Someone would need to create a tech for it. There used to be one, but it seems to be gone now https://github.com/videojs/video.js/issues/5835.
It isn't something that we have any plans to work on ourselves.

**Comment by snaildos** [comment]
Darn it. Alright, thanks.
