### ISSUE TITLE
get "bandwidth, media bytes transferred, media transfer duration, video playback quality"

### ISSUE THREAD

**Issue by cuiD2488** [videojs/video.js#7139]
## Description
How can I get "bandwidth, media bytes transferred, media transfer duration, video playback quality" on IOS，I want to try to use them to express the streaming media loading speed

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.1
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Following up from https://github.com/videojs/http-streaming/issues/1102, unfortunately, this just isn't possible. The native playback engine is used there, and it doesn't give much access to knowing what's happening. Your best bet is looking at the `videoWidth()` and `videoHeight()` which can give you the current resolution of the selection rendition.
