### ISSUE TITLE
TypeError: this.videoPlayer.httpSourceSelector is not a function 

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/video.js#7144]
## Description
We are using `videojs-http-source-selector` plugin in our project for 2 years and it's working well. Now, we would like to extend its support to our other projects. 

But, when tried to replicate the entire `videojs` related code to the new project, everything went well except for this httpSourceSelector error. This would be a blocker for us to make the feature live.

Could you help us out with what might have gone wrong or any additional details to take care of?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Install `video-js-http-source-selector` in `package.json` using yarn 
2. Import it using require in the Video component developed using React and TypeScript
3. Add `videojs-contrib-quality-levels` as a peer dependancy
3. Initialize the plugin with `this.videoPlayer.httpSourceSelector()`. 
4. Use //@ts-ignore above the initialization to ignore typescript errors

![image](https://user-images.githubusercontent.com/36617018/112109450-9b05a500-8bd7-11eb-89c8-f7976e5a6803.png)

### Expected
`videojs-http-source-selector` plugin should be initialized and the user should be able to see the quality change option

### Actual
`videojs-http-source-selector` is not getting initialized

### Error output
TypeError: this.videoPlayer.httpSourceSelector is not a function 

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.6
#### typescript
3.7.2
#### browsers
Chrome 89
#### OSes
Linux
#### videojs-contrib-quality-levels
2.0.9
#### videojs-http-source-selector
1.1.6

**Comment by gkatsev** [comment]
This sort of came up in #7091. One thing to try is to remove video.js and quality-levels and the source selector plugins via `yarn remove`. Verify that the yarn lockfile does not include these anymore. Then, re-add the packages starting with `video.js` and then the source selector and quality-levels. Hopefully, it'll shake up the tree, so things are correct.

We'll be investigating this as part of #7091 and #7109 so that hopefully it won't be required.

**Comment by Kaywee27** [comment]
> This sort of came up in #7091. One thing to try is to remove video.js and quality-levels and the source selector plugins via `yarn remove`. Verify that the yarn lockfile does not include these anymore. Then, re-add the packages starting with `video.js` and then the source selector and quality-levels. Hopefully, it'll shake up the tree, so things are correct.
> 
> We'll be investigating this as part of #7091 and #7109 so that hopefully it won't be required.

Thanks for the reply. Tried it out, but couldn't resolve the issue. 

We are using `Yarn`.

But, when we removed all `video-js` related packages and reinstalled them using `NPM`, the issue was resolved.

Any specific reason?

**Comment by gkatsev** [comment]
I'm not really too sure. What version of yarn are you using?
I'm guessing that somehow the dependency tree that's being made by npm vs yarn is different and so plugins end up using their own version of Video.js since plugins depend on Video.js directly rather than having it be a peer dependency.

**Comment by Kaywee27** [comment]
"engines": {
      "npm": ">=5.6.0",
      "yarn": ">=1.17.3",
      "node": ">=12.6.0"
   },
