### ISSUE TITLE
Can't see subtitles when playing video on ios mobile  

### ISSUE THREAD

**Issue by jacob89098ty** [videojs/video.js#7153]
## Description

I don't know why but I can't see the subtitles when the video play on mobile safari

**Comment by gkatsev** [comment]
Can you provide more information on when this happens? What version of iOS? What version of Video.js? Is it an iphone or an ipad? How are you loading the captions?
Even better if you can provide a reduced test case.

**Comment by jacob89098ty** [comment]
It's an iphone and it happens with iOS 14.4.2  with the latest version of Video.js.  And I'm loading the caption from another site

**Comment by gkatsev** [comment]
You probably need to set `crossorigin=anonymous`. iOS 14 is stricter with requiring it. Can be added as a video element attribute or a videojs option.

**Comment by jacob89098ty** [comment]
how do i do that. could you write the code for me ?

**Comment by FredZeng** [comment]
```html
<video crossorigin="anonymous">
  <track kind="subtitles" src="sampleSubtitles.vtt" srclang="en">
</video>
```
