### ISSUE TITLE
A few instances of plugins on the page. 

### ISSUE THREAD

**Issue by ol3j** [videojs/video.js#7154]
In an application I run a few instances of plugins  2-4. 
The stream is HLS. 
The first instance works correctly but when second is playing a player is frozen and video is cutting.
This problem occurs for mobile device (iOS - Safari, Android - Chrome)
I would like to achieve effect view from a few cameras at the same moment. 
Do you have any experienced in this or any recommendations?

**Comment by gkatsev** [comment]
Unfortunately, due to platform limitations, mobile devices generally only allow one video to be playing at any given time.

Though, I just tested on my iPad I can see two muted videos playing together but not two unmuted videos. Though, this may not apply on Android.

Do you have a reduced example we can take a look at?

**Comment by ol3j** [comment]
@gkatsev thanks for comment 
This is my app https://bit.ly/3rBuycm, go to views with 8 videos and  try run fours simultaneously in iOS in mobile safari

**Comment by gkatsev** [comment]
Are you running it on an iPad or an iPhone? Unfortunately, nowadays, there is a distinction between the two. iPad is generally less restrictive than iPhone.

**Comment by gkatsev** [comment]
Trying it out on my ipad, I can see the first video working mostly fine but the other videos being super choppy. More like a slideshow than a video.
One thing I noticed is that it's trying to play 4 1080p videos. This is likely too much for the device. If you're able to generate custom playlists for the iPad that don't include higher renditions, that probably would help a lot.

**Comment by ol3j** [comment]
I tested in iPhone(https://bit.ly/3sPgGN7) and iPad (https://bit.ly/3rDdQck).
Yeap, In app we are focused on quality of videos.  We use adaptive streaming.  
What version of videos for  ipad do you recommend to achieve this goal (4 videos running simultaneously)
Do you know where I can find information about safari/iphone/device performance?  I need more knowledge about this issues.

**Comment by gkatsev** [comment]
Decoding 4 1080p streams is quite cpu intensive. I'm not really sure what the performance implications. I would try out various combinations. A complete guess is that 1 1080p and 3 480p streams should work ok.

**Comment by ol3j** [comment]
@gkatsev thank you, we will check some scenarios. If I have a feedback I will update it.
