### ISSUE TITLE
Remove PIP Icon?

### ISSUE THREAD

**Issue by yoxud** [videojs/video.js#7155]
## Description
I want to set up a video background, no controls, no picture in picture, just the video.
However there is a browser pip icon that floats above my video on mousemove. This does not seem to stem from video.js per se but rather from a hidden chrome extension. The extension needs to be manually disabled in the settings by the user so that the icon disappears... Is there anyway I can setup my video.js so that this extension icon is disabled without anu user intervention?

**Comment by gkatsev** [comment]
There is no way to control extensions or browser features from within Video.js.
