### ISSUE TITLE
The event listens to the bandwidth changes of hls content in videojs

### ISSUE THREAD

**Issue by PhatBK** [videojs/video.js#7156]
I am using videojs for playing my multimedia content. Content is in hls (.m3u8) format. How can I catch an event when the video player bandwidth changes automatically?

**Comment by mister-ben** [comment]
For MSE playback you can listen to cue changes on the segment metadata track https://github.com/videojs/http-streaming#segment-metadata

That is not available for native HLS playback. The closest you can get is to listen for `resize` on the player.

**Comment by PhatBK** [comment]
Thank you, I used it

**Comment by PhatBK** [comment]
> For MSE playback you can listen to cue changes on the segment metadata track https://github.com/videojs/http-streaming#segment-metadata
> 
> That is not available for native HLS playback. The closest you can get is to listen for `resize` on the player.

Thank you, I used it
