### ISSUE TITLE
Issues when using video.js with MediaStream

### ISSUE THREAD

**Issue by michaelvobejda** [videojs/video.js#7159]
## Description
When playing from a MediaStream, you cannot play again after pausing. This works with vanilla HTML5 video player perfectly fine, but video.js seems to have trouble handling this.

## Steps to reproduce
1. Initialize video.js player and new MediaStream
2. Set player.tech().el().srcObject = mediaStream (from #5243)
3. Play, pause, then try to play again

### Expected
The player should resume playback.
### Actual
The player remains frozen.

### Error output
No errors.

#### videojs
^7.11.4
#### browsers
Tested on Chrome. On Safari, playback doesn't work at all (maybe related?) but Chrome usage is my primary concern.
#### OSes
Tested on MacBook Pro running Catalina.
### plugins
No plugins.

**Comment by gkatsev** [comment]
Seems to be working for me locally, testing with 
```
navigator.mediaDevices.getUserMedia({audio: true, video: true}).then(function(mediaStream) {
  var vid = player.tech().el();
  vid.srcObject = mediaStream;
});
```
Do you have a reduced example?

**Comment by ReArno** [comment]
+1
Minimal example:

```
function BaseVideo() {
  const ref = React.useRef();
  const [video, setVideo] = React.useState(null);

  const stream = React.useMemo(() => {
    return new MediaStream();
  }, []);

  React.useEffect(
    () => {
      const _video = VideoJS(ref.current, {
        autoplay: true,
        controls: true,
        bigPlayButton: false,
        liveui: true,
      });
      setVideo(_video);
      return () => {
        _video.dispose();
      };
    },
    [setVideo],
  );

  React.useEffect(
    () => {
      if (!video) return;
      AgoraRTC.createMicrophoneAndCameraTracks().then(
        ([audioTrack, videoTrack]) => {
          stream.addTrack(audioTrack.getMediaStreamTrack());
          stream.addTrack(videoTrack.getMediaStreamTrack());
          video.tech(true).el().srcObject = stream;
        },
      );
    },
    [video, stream],
  );

  return (
    <React.Fragment>
      <button
        onClick={() =>
          video
            .tech(true)
            .el()
            .play()
        }>
        Play
      </button>
      <video ref={ref} className="video-js vjs-theme-city" />
    </React.Fragment>
  );
}
```
The additional button works, so if I access the native video element it works, but with the player button doesn't works.

**Comment by Exlord** [comment]
Same issue here 
https://github.com/videojs/video.js/issues/7304
https://codepen.io/exlord-the-styleful/pen/oNWjBjR?editors=1000

**Comment by Exlord** [comment]
https://github.com/videojs/video.js/issues/7304#issuecomment-876220163
