### ISSUE TITLE
Video.js v7.11.4 can't play correct in Chrome  Iphone Emluated Device。

### ISSUE THREAD

**Issue by xjl271314** [videojs/video.js#7166]
## Description

![image](https://user-images.githubusercontent.com/20588030/113803073-60326e00-978e-11eb-9ec5-26d2a4ae439c.png)

When I use Iphone Emluated Device，the video is always throw the error，when I use an android Emluated Device, the video is play correct.

![image](https://user-images.githubusercontent.com/20588030/113803451-29108c80-978f-11eb-8408-9e452f27680c.png)

## Steps to reproduce

UA：

- iphone: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1

- android: Mozilla/5.0 (Linux; U; Android 4.0; en-us; GT-I9300 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

### Expected

I hoped the video can play in Iphone Emluated Device。

### Error output

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

#### videojs

video.js v7.11.4

#### browsers

![image](https://user-images.githubusercontent.com/20588030/113803401-0a11fa80-978f-11eb-914a-84a8ac8bf6eb.png)

**Comment by xjl271314** [comment]
the video type is m3u8。

**Comment by ziddey** [comment]
I believe VHS uses native hls playback if it detects ios by default. Simulating an ios/safari user agent will then cause vhs to attempt to play the stream natively, which will fail.

**Comment by mister-ben** [comment]
Chrome's "emulation" just spoofs user agent and simulates touch events. It is useful for testing layout but not anything complex like video where the browser behaviour and capabilities are fundamentally different. The only way to really test iOS without an actual device is Xcode's simulator, or a service such as Browserstack.

**Comment by gkatsev** [comment]
Unfortunately, this is basically expected. If we detect iOS, and we are given HLS, we try and play it back natively, which doesn't work in Chrome.
