### ISSUE TITLE
Long pressing rewind hotkey doesn't update progress immediately if video is paused

### ISSUE THREAD

**Issue by justprobst** [videojs/video.js#7168]
## Description
Long pressing rewind hotkey doesn't update progress immediately if video is paused. If it isn't, progress updates correctly.

## Steps to reproduce
Use next option:
`
userActions: {
    hotkeys(event) {
        const duration = this.duration();
        const isPaused = this.paused();
                switch (event.which) {
                        case 37: {
                            event.preventDefault();
                            const seekTime = Math.max(0, this.currentTime() - 10);
                            this.currentTime(seekTime);
                            break;
                        }
`
Then pause video, press and hold left arrow btn, progress/slider-bar should have actual position with every event call.

### Expected
Progress (vjs-play-progress vjs-slider-bar) updates immediately with every event

### Actual
Looks like progress (vjs-play-progress vjs-slider-bar) updates only on 'seeked' event

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.11.8
#### browsers
Safari 14.0.2
#### OSes
macOS Big Sur 11.2.3

**Comment by gkatsev** [comment]
I am able to see the progress bar update during the seek while the player is paused using your example userAction.
Can you provide a test case where you can reproduce this?
