### ISSUE TITLE
TypeError: this.b.vjs_getProperty is not a function when hiding video

### ISSUE THREAD

**Issue by doits** [videojs/video.js#717]
See this fiddle:

http://jsfiddle.net/sHWHc/3/

When clicking "hide" in firefox, the following error is produced:

```
TypeError: this.b.vjs_getProperty is not a function
```

When showing and hiding the video again, the error occurs again, too.

This errors also happens when the video is inside a jqueryui accordion and the video is hidden there, for example.

(note: not sure why there is a `Error: Permission denied to access property 'toString'` error in the fiddle - I am not seeing this on my live system)

**Comment by 4z5lz** [comment]
Hi!

I see this error in v4.12.11:

Uncaught TypeError: this.c.vjs_getProperty is not a function
video.js:139 Uncaught TypeError: this.c.vjs_getProperty is not a functiont.g.currentSrc @   video.js:139M @ video.js:68s.currentSrc @ video.js:77b.Hls.fillBuffer @ videojs.hls.min.js:3b.Hls.checkBuffer_ @ videojs.hls.min.js:3e @ video.js:14

**Comment by mmcc** [comment]
Are you trying to hide the Flash fallback? If so, you *need* to dispose it first. Flash simply will not play nice if you're trying to just set `display: none` or something along those lines.
