### ISSUE TITLE
CSS transform: scale not applied during fullscreen on Chrome/Edge with HW acceleration on.

### ISSUE THREAD

**Issue by DenisIvanovIvanov** [videojs/video.js#7171]
## Description
I've written zoom plugin for our project with preview. I was using Firefox at the time and everything worked fine, till I decided to test on Chrome/Edge. Then suddenly it stopped working. The problem is that `transform: scale()` is not being applied/ignored while on fullscreen. If I turn off hardware acceleration everything suddenly starts working. Been researching/trying everything but still no success. I'm pretty sure its not related to videojs, but I have to ask. I've also used `scale3d(5, 5, 5)` to 'force' it to be done on the GPU, but still no effect.

## Steps to reproduce
1. head to https://jsfiddle.net/5osL4ctr/9/ and hit the zoom button
2. Now while the video is 'zoomed' hit the fullscreen button.

### Expected
Zoom should still be present

### Actual
On Chrome/Edge with HW acceleration on the transform: scale() is ignored. With turned off everything is fine. No issues on Firefox with both HW acceleration on/off.

#### browsers
Microsoft Edge/Chrome

Is there a way to fix that?

**Comment by gkatsev** [comment]
Looks like the browser adds a default `transform: none !important` to fullscreen elements. Theoretically, adding a `!important` to your property should fix it.
