### ISSUE TITLE
Videojs not playing

### ISSUE THREAD

**Issue by Vazza202** [videojs/video.js#7173]
I'm having issues with this player. The playlist works fine but the mp4 files will not play... you push the play button.. nothing happens, it worked last time I used it and now it's not working. I have everything set up and I know it's a small problem, so if anybody can help here's the URL to the page, you can look in the console to see what's wrong, alien-network.xyz/videos/Videos.html you can view the source here. it's been a while since I used it.

The test video is the one I want working... the others I know won't play cause they're old CDN.
Let me know thanks.

**Comment by ycl310** [comment]
Wait how do you even make playlists

**Comment by eduardonwa** [comment]
Can you share a Codepen? I think it is useful to see how you're doing what you're trying to achieve. There is a boiler plate already (skin maker) and in that example a file is being used: https://codepen.io/heff/pen/EarCt

**Comment by gkatsev** [comment]
@ycl310 you can use a plugin like videojs-playlist

**Comment by gkatsev** [comment]
@Vazza202 looks like your page isn't working anymore. Can you create another reduced test page and share it please?

**Comment by NikolayChankov90** [comment]
I have faced the issue as well, the player was on  Waiting event , and no other event was fired. This happened only on Live.

> autoPlay: true

When i open the player , i make player.pause() , and the moment you hit play() it fires Waiting event and nothing else. 
The way i fixed this is , on Waiting event, i take the current live duration and  player.currentTime(liveDuration).

And the timeUpdate() and durationChange() events are fired and it works. 

Hope this helps.
