### ISSUE TITLE
Responsive properties on data-setup not kicking in.

### ISSUE THREAD

**Issue by eduardonwa** [videojs/video.js#7175]
## Description
I cannot make the video player to be responsive, below I have added a Codepen.
https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0

## Steps to reproduce
Although the Codepen does not play the video, in my local environment I get playback from this youtube URL, and im using the VideoJS youtube extension, version listed at the bottom. I am working on a Laravel 8 project and these are the links and scripts that im calling on my master layout file, also I have installed it through NPM. 

```
<link href="//vjs.zencdn.net/7.10.2/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/7.10.2/video.min.js"></script>
<script src="{{ asset ('/js/Youtube.min.js') }}"></script>
```

This is what I do:
1. When I placed the link and script tags I placed the attributes and properties that the Codepen contains
2. One of them being the responsive property which is set to true. 

### Expected
The video player should respond and the breakpoint classes should kick in anytime the browser is at a certain breakpoint. 

### Actual
When I try to expand and collapse the window browser the video player does not respond in the way that it should because the video player maintains the same width and height through out. However I have tried removing those fixed values but it still doesn't work. 

### Error output
Not sure if it matters but I get this on the console tab, 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).
```

#### videojs
 7.12.0
#### browsers
Mozilla Firefox
#### OSes
Windows 10
### plugins
 Videojs-Youtube-extension, https://github.com/videojs/videojs-youtube.

Hope the information is useful, :-) wonderful plugin.

**Comment by mister-ben** [comment]
Your test links to the boilerplate Codepen rather than your version.

**Comment by eduardonwa** [comment]
```
      <video
        id="vid1"
        class="video-js"
        controls
        preload="auto"
        height="600px"
        width="1230px"
        poster='img/vido-poster.svg'
        data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=zY5nYmTUfnQ"}], "responsive": "true", }'
      >
    </video>
    ```

**Comment by eduardonwa** [comment]
I solved it, I think, key was that the property "responsive", is not the appropiate term? If I leave my video tag exactly like this:

1. The youtube extension works
2. The video player is responsive

```
        <video
            id="vid1"
            class="video-js"
            controls
            preload="metadata"
            height="600px"
            width="1230px"
            data-setup='{ 
              "techOrder": ["youtube"], 
              "sources": [{ "type": "video/youtube", 
              "src": "https://www.youtube.com/watch?v=zY5nYmTUfnQ"}], 
              "fluid": true 
            }'
        >
        </video>
```

**Comment by gkatsev** [comment]
Yup, fluid is what you were looking for. See https://docs.videojs.com/tutorial-layout.html for more info.

**Comment by eduardonwa** [comment]
Just beautiful! :-)
