### ISSUE TITLE
Spurious dependency to 'remove'

### ISSUE THREAD

**Issue by vbfox** [videojs/video.js#7176]
## Description

While upgrading video.js I had errors in my license check script (using `license-checker`) because `video.js` is now dependent on `seq`, `hashish` and `traverse` that don't have a correct SPDX identifier via `remove` (All are very old packages with a last publish 10 years ago and predate the SPDX identifier unification in package.json).

This is not a problem as all are MIT and I could whitelist them but I wondered why and noticed that the dependency seem unused.

I suspect it's a spurious dependency introduced in https://github.com/videojs/video.js/pull/7128 that doesn't even seem to mention it.

https://github.com/videojs/video.js/blob/main/package.json#L90

#### videojs
7.11.8

**Comment by gkatsev** [comment]
Thanks, yup, it was accidentally added. We'll remove it.
