### ISSUE TITLE
Browsers autoplay if muted is on, referencing a issue-comment.

### ISSUE THREAD

**Issue by eduardonwa** [videojs/video.js#7180]
This is expected. Browsers now will not autoplay by default anymore, unless the video is muted. To that end, we have extra values for the autoplay option to video.js: https://docs.videojs.com/tutorial-options.html#autoplay. However, that option seems to not be working properly right now, and it's something we should fix.

For more information on autoplay, you should check out our [autoplay best practices](https://blog.videojs.com/autoplay-best-practices-with-video-js/) blogpost.

_Originally posted by @gkatsev in https://github.com/videojs/video.js/issues/5581#issuecomment-438733223_

**Comment by eduardonwa** [comment]
So what came out of this? I'm learning this right now and yes, the video does not autoplay unless is muted and I had it set on almost all possible locations including inside the ```<script>```, just wanted to know what's the best possible solution for this, thank you.

**Comment by gkatsev** [comment]
Pretty sure we've fixd that option since. It's been ~2 years. What are you looking for exactly with autoplay?

**Comment by eduardonwa** [comment]
Just looking to autoplay the video basically, the video gets loaded in a different page by clicking an ```<a>```, this view only has the video element and that's it. I made this codepen but since im using the youtube extension it doesn't seem to work but this is basically what I have there; https://codepen.io/eduardonwa/pen/qBRYWOB

**Comment by gkatsev** [comment]
I think your issue is a timing issue. You're trying to load a youtube source via the auto-setup mechanism of Videojs. This means that the player ends up trying to load before the youtube tech has loaded. Here's a fixed example. You can see the the video does autoplay: https://codepen.io/gkatsev/pen/QWdrLMV

**Comment by eduardonwa** [comment]
I mean I got it to autoplay so as long as if it was muted, I wanted to know if it was possible to autoplay without it being muted.

**Comment by mister-ben** [comment]
> I wanted to know if it was possible to autoplay without it being muted.

Only if the browser allows it.

**Comment by eduardonwa** [comment]
How can I make an "unmute" button?
