### ISSUE TITLE
full screen

### ISSUE THREAD

**Issue by Julycc41** [videojs/video.js#7181]
How to set a component to display in full screen and set zindex invalid

**Comment by eduardonwa** [comment]
I would love to help you out but I think I should see your code, however it seems to me that you're doing something else with an HTML element and applying z-index to it. If your component means the videoplayer and you want it to have a z-index value of "invalid" maybe you could try adding negative values to the property, what else is in play here? and are you trying to show the video fullscreen and have an external HTML element on top of the video player? :-)

**Comment by Julycc41** [comment]
![1618453010](https://user-images.githubusercontent.com/80231740/114804327-b7aa8c80-9dd3-11eb-8304-98af9a59038d.png)
First of all, thanks for your reply. I tried to set Zindex as 2147483647 online.But it doesn't seem to work, I want to show a component in full screen, just like a pop-up attached to full screen, I don't know what to do

**Comment by eduardonwa** [comment]
I think this is what you're looking for: https://docs.videojs.com/tutorial-modal-dialog.html

**Comment by gkatsev** [comment]
I think likely what they're looking for is an overlay rather than a modal dialog: https://github.com/brightcove/videojs-overlay

Can you share a reduced example? A bit hard to help diagnose without a minimal live example.
