### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 

### ISSUE THREAD

**Issue by zzs1016** [videojs/video.js#7182]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.Version 5.11 can't play videos in m3u8 format
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?  5.11
#### browsers
what browser are affected?  chrome
#### OSes
what platforms (operating systems and devices) are affected?  mac
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
Video.js 5 is very old now. It doesn't include HLS support out of the box, but you can add it with videojs/videojs-contrib-hls. But I strongly recommend updating to latest Video.js instead, which includes HLS support as standard.
