### ISSUE TITLE
Smooth transition between different video sources

### ISSUE THREAD

**Issue by picanumber** [videojs/video.js#7184]
I'm trying to use video js in a way that when the source url for a video changes, the player won't display a black frame or stall. I'm assuming that the network quality is good enough to not cause any problems with this, and the behavior I'm looking resembles "double buffering", i.e. start the new video and only bring it forward when it's ready to "play".

Is there a way to do this, is it planned?

**Comment by gkatsev** [comment]
Unfortunately, doing this isn't simple. Perhaps the best way is to have two players and swap between them. Alternatively, you can look at things like prefetch https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ.
There are more advanced techniques like re-used the same source buffers when you're playing back HLS/DASH, but this isn't something we have planned.
