### ISSUE TITLE
export 'addSidxSegmentsToPlaylist' was not found in 'mpd-parser

### ISSUE THREAD

**Issue by TongBig** [videojs/video.js#7185]
WARNING  Compiled with 2 warnings                                      15:10:22

 warning  in ./node_modules/_video.js@7.11.8@video.js/dist/video.es.js

"export 'addSidxSegmentsToPlaylist' was not found in 'mpd-parser'

**Comment by gkatsev** [comment]
Can you post the output of `npm ls mpd-parser` or similar command in yarn, if you're using yarn?

**Comment by TongBig** [comment]
基础平台 git:(feature-webRtc) ✗ npm ls mpd-parser
magicsky-base@1.0.0 /Volumes/T/web_mjzn_git/基础平台
└── UNMET DEPENDENCY mpd-parser@0.8.2

npm ERR! missing: mpd-parser@0.8.2, required by magicsky-base@1.0.0
➜  基础平台 git:(feature-webRtc) ✗

**Comment by gkatsev** [comment]
Sounds like `mpd-parser` isn't available locally for you for whatever reason.
