### ISSUE TITLE
video.js not working with React.js + WebComponents

### ISSUE THREAD

**Issue by MatteoBuffo** [videojs/video.js#7187]
Has anybody ever managed to make video.js work with React.js together with WebComponents?

My video player is in the shadowDOM. I've read [here](https://github.com/videojs/video.js/issues/4697) that video.js ignores videos outside the DOM: in fact, I get this warning
`video.es.js:142 VIDEOJS: WARN: The element supplied is not included in the DOM`

How can I overcome this?

**Comment by swieckonrad** [comment]
Hi, could you share the solution?

**Comment by VityaSchel** [comment]
> Hi, could you share the solution?

Use default browser player :) 

Any other players I tried refuse to work with next.js
