### ISSUE TITLE
Question: use fetch() on preloaded video without downloading it again?

### ISSUE THREAD

**Issue by nelsoncarr** [videojs/video.js#7188]
Hello!

**What I want to achieve:**
I want a video to preload in video.js and then use fetch() to grab and further use the already downloaded/preloaded video. Thus **avoiding having to download the video twice** (once for preload/playing + another time with fetch()).

**Problem:**
I don't know how to access the preloaded video or where it is stored in the browser to be able to further use it. Is there any way to access it?

**What I tried:**
I tried fetching the video with fetch() and then inserting it as video source – which does work but the preloading functionality is lost and the video has to be completely fetched before it can play.

Any help with this would be highly appreciated!

**Comment by gkatsev** [comment]
I would recommend against trying to do that directly on the page. For preloading/prefetching, you can look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ, which will prime the browser cache with the download items. Alternatively, I would look at creating a service worker that be given a video url which it then downloads and serves back to XHR/fetch requests from it's local cache.

Hope this give you a way forward.
