### ISSUE TITLE
HTTP “Content-Type” of “video/mp2t” is not supported. Load of media resource http://m2.websecureme.net/1QzXhQcuQZJ4vYC/CXjsAuUIN2/102475 failed.

### ISSUE THREAD

**Issue by rajmylav** [videojs/video.js#7191]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
video is working fine on vlc but fails to start on web using video.js

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs

latest 
what version of videojs does this occur with?
#### browsers
all browsers
what browser are affected?
#### OSes
mac and windows
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

```

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Video.js Sandbox</title>
    <link href="//vjs.zencdn.net/7.10.2/video-js.min.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/7.10.2/video.min.js"></script>
</head>
<body>
<div style="background-color:#eee; border: 1px solid #777; padding: 10px; margin-bottom: 20px; font-size: .8em; line-height: 1.5em; font-family: Verdana, sans-serif;">
    <p>You can use /sandbox/ for writing and testing your own code. Nothing in /sandbox/ will get checked into the repo, except files that end in .example (so don't edit or add those files). To get started make a copy of index.html.example and rename it to index.html.</p>
    <pre>cp sandbox/index.html.example sandbox/index.html</pre>
    <pre>npm run start</pre>
    <pre>open http://localhost:9999/sandbox/index.html</pre>
</div>

<video-js
        id="vid1"
        controls
        preload="auto"
        width="640"
        height="264">
    <source src="http://m2.websecureme.net:80/1QzXhQcuQZJ4vYC/CXjsAuUIN2/102475" >

    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video-js>

<script>
    var options = {};

    var player = videojs('vid1', options, function onPlayerReady() {
        videojs.log('Your player is ready!');

        // In this context, `this` is the player that was created by Video.js.
        this.play();

        // How about an event listener?
        this.on('ended', function() {
            videojs.log('Awww...over so soon?!');
        });
    });

</script>

</body>
</html>
```

![image](https://user-images.githubusercontent.com/21015698/115123949-91c8e780-9f8d-11eb-9635-7249fd6f478e.png)

**Comment by gkatsev** [comment]
Video.js doesn't support M2TS directly. Only when it's inside of HLS.

Also, you should make sure to provide a type in the source element.
