### ISSUE TITLE
videojs Play Caton

### ISSUE THREAD

**Issue by XFJ712** [videojs/video.js#7192]
chrome && phone

I use videojs play about m3u8 video, video is stored s3, but first play is good, but second play
scoure read from disk(chorme cache) this video play caton about 3m, but i use option autoplay: true videojs is normal

![image](https://user-images.githubusercontent.com/57062007/115225997-4d7e4880-a141-11eb-8e40-d6393011c5b9.png)

**Comment by gkatsev** [comment]
Is it failing to play on the second play?
Are you able to share your stream?
