### ISSUE TITLE
VIDEOJS: WARN: Problem encountered with playlist 0-https://******. Trying again since it is the only playlist.

### ISSUE THREAD

**Issue by TigerTh** [videojs/video.js#7195]
## Description
Briefly describe the issue.
VIDEOJS: WARN: Problem encountered with playlist 0-https://******. Trying again since it is the only playlist.use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.VIDEOJS: WARN: Problem encountered with playlist 0-https://******. Trying again since it is the only playlist.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
Please open a new issue and fill out the issue template. Given your issue, you probably want to include a live sample as it's unlikely we can help figure things out otherwise. If you're unable to share your stream publicly, you can message me the stream on our videojs slack.
