### ISSUE TITLE
【Confused】Why `loadTech_` would set `this.tag = null` if not using `Html5` Tech

### ISSUE THREAD

**Issue by FredZeng** [videojs/video.js#7196]
## Description
I'm using [videojs-flvjs](https://github.com/mister-ben/videojs-flvjs/blob/master/src/plugin.js) Tech.
I'm dealing with WeChat `X5-Kernel` browser by adding unofficial attribute on `<video>`, e.g. `x5-video-player-type='h5-page'`. In my scenario, I checked the `<video>` through DevTools, but found that the existed `<video>` only contained limited attributes while others were dropped.
By reading through the source, I found that using a Tech except `Html5` would cause setting `this.tag = null;` <https://github.com/videojs/video.js/blob/main/src/js/player.js#L1120>, which would cause later creating a new `<video>`. However, the original `<video>` attributes didn't pass on the `Tech` constructor, which makes the new one different from the original one. <https://github.com/videojs/video.js/blob/main/src/js/player.js#L1133>

1. Why set `this.tag = null` if not using `Html5` Tech?
2. Should I also pass `<video>` on tech options?
```js
videojs(videoNode, {
  flvjs: {
    tag: videoNode,
  }
})
```

## Steps to reproduce
```js
const Index = () => {
  const videoRef = useRef();

  useEffect(() => {
    const player = videojs(videoRef.current, {
      controls: true,
      autoplay: true,
      techOrder: ['html5', 'flvjs'],
      html5: {
        hls: {
          withCredentials: false,
          overrideNative: true,
        },
      },
      flvjs: {
        config: {
          fixAudioTimestampGap: true,
        },
        mediaDataSource: {
          isLive: true,
          cors: true,
          withCredentials: false,
        },
      },
      sources: [], // any flv source
    });
  }, []);

  return (
    <div data-vjs-player>
      <video ref={videoRef} x5-video-player-type='h5-page' webkit-playsinline='isiPhoneShowPlaysinline' />
    </div>
  );
};

```

### Expected
1. New created `<video>` element can also copy customed attributes.
2. Or enable passing `<video>` attributes on `Tech` constructor. 

### Actual
Customed `<video>` attributes have dropped after loading `flvjs` Tech.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
`video.js@7.11.4`
#### browsers
Windows10 `Chrome 89.0.4389.128`
#### OSes
Windows10
### plugins
none

**Comment by gkatsev** [comment]
Techs in Video.js are expected to create their own display container, whether it be a video element, an iframe, or a canvas element. We default to the Html5 tech and re-use the default video element provided. We can't know that another tech would want to re-use the video element as well.

**Comment by FredZeng** [comment]
It seems [Html5 line387-line388](https://github.com/videojs/video.js/blob/main/src/js/tech/html5.js#L387) not longer needed as they run in the `else` block.
