### ISSUE TITLE
Add `playbackRates()` method

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#7198]
Add a new `playbackRates(rates)` method to the player which will update the playback rates used by the playback rate menu. It should also turn the menu button on if it is off.

Currently, the only way to turn it on is by providing a `playbackRates` option during player initialization. This will allow users to update the menu and turn it on after a player has already been created.

**Comment by AwokeKnowing** [comment]
this would match several other things like poster() autoplay() etc and help us keep our clients in compliance with regulations that require users to complete training where there should be no rates faster than 1.0  since training must take a minimum amount of time, and be enforced in software.  So there's a list of items in a playlist, and playbackrates > 1 only show for videos that have already been watched.  for unviewed videos, the lower playback rates are helpful for some people, especially foreign language speakers, as well as some process demonstrations

**Comment by gkatsev** [comment]
> since training must take a minimum amount of time

I still think that's a completely ridiculous requirement since different people have different needs, but that's definitely a separate story.

**Comment by mister-ben** [comment]
Makes sense to have this. What should it do if rates were present and then removed? Disable or hide the menu button?

> since training must take a minimum amount of time

If I have to listen to training with someone speaking far too slowly, I start "multitasking" and paying less attention. Completely counterproductive to prevent me setting a comfortable speed.

**Comment by brandonocasey** [comment]
Seems like a good idea to me.

**Comment by gkatsev** [comment]
Oh, yeah, forgot to add it in later but I was thinking that `playbackRates([])` should remove/hide the button.

**Comment by AwokeKnowing** [comment]
question, should changing playbackrates enforce changing the playback rate to an option in the list?

(I assume answer is no..)

**Comment by gkatsev** [comment]
Yeah, it shouldn't affect the actual playback rate, only the display of the menu.

**Comment by AwokeKnowing** [comment]
> If I have to listen to training with someone speaking far too slowly, I start "multitasking" and paying less attention. Completely counterproductive to prevent me setting a comfortable speed. (off topic for this thread, and meant as feedback rather than a rant...)

haha, yeah, tell that to your local state government regulators that measure required training in minutes.

**Comment by AwokeKnowing** [comment]
for reference, my current implementation:

```js
let rates = this.player.disableFF()?[0.25, 0.5, 0.75, 1]:[0.25, 0.5, 0.75, 1, 1.25, 1.5, 2];
controlBar.replaceChild('PlaybackRateMenuButton',{playbackRates:rates})

```

**Comment by misteroneill** [comment]
I am in favor of this idea!
