### ISSUE TITLE
OnBeforeFetch hook for webm videos

### ISSUE THREAD

**Issue by darind** [videojs/video.js#7201]
## Description

I am trying to register a custom function which will be called before fetching a `video/webm` content from the server so that I can add some custom headers. Also it would be great if I could intercept the response from the server and manipulate it before feeding the stream to the player. 

This seems to be possible with HLS videos: https://github.com/videojs/videojs-contrib-hls/issues/665

Can we achieve the same for webm videos?

This is how the player is initialized:

```html
<video 
    id="player" 
    controls
    preload="none"
    width="640"
    height="264" 
    class="video-js">
    <source src="video.webm" type="video/webm" />
</video>
```

```javascript
player.on("loadstart", function (e) {
    // player.tech()...... Can I register the onBeforeRequest hook somehow here?
});
```

**Comment by gkatsev** [comment]
Unfortunately, it isn't possible to do. For videos like webm, we hand off to the browser to handle completely. There isn't a way to hook there to modify the source or the request.
Potentially, you [WebCodecs](https://github.com/w3c/webcodecs/blob/main/explainer.md) could help you out, but that's brand-new technology which isn't widely available.
