### ISSUE TITLE
Cannot play ClearKey encrypted webm video in Firefox

### ISSUE THREAD

**Issue by darind** [videojs/video.js#7204]
## Description

I have a `video/webm;codecs=vp9` video that I have encrypted with a hardcoded key using [webm-encrypt](https://github.com/austinleroy/webm-encrypt).

I am trying to play this video using videojs and failing to do so in FireFox (works fine in Chrome, Edge and Opera).

## Steps to reproduce

Here's the code I wrote using [videojs-contrib-eme](https://github.com/videojs/videojs-contrib-eme):

```html
<video
    id="player"
    controls
    preload="none"
    crossorigin
    class="video-js">
</video>
```

and the following script:

```javascript
var KEY = new Uint8Array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]);

function toBase64(u8arr) {
    return btoa(String.fromCharCode.apply(null, u8arr)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=*$/, '');
}

var player = videojs("player");
player.eme();

player.src({
    src: 'https://downloads.getfiddler.cc/foo/video_a_encrypted.webm',
    type: 'video/webm;codecs=vp9',
    keySystems: {
        'org.w3.clearkey': {
            videoContentType: 'video/webm;codecs=vp9',
            getLicense: function(emeOptions, keyMessage, callback) {
                const parsed = JSON.parse(new TextDecoder().decode(keyMessage));
                var keyObj = {
                    kty: 'oct',
                    alg: 'A128KW',
                    kid: parsed.kids[0],
                    k: toBase64(KEY)
                };
                const lic = new TextEncoder().encode(JSON.stringify({
                    keys: [keyObj]
                }));
                callback(null, lic);
            }
        }
    }
});
```

This code works in Chrome but in FireFox it throws:

```
video_a_encrypted.webm could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: Encrypted content not supported outside of MSE
```

### Expected

The video plays fine in Firefox

### Actual

The video doesn't start

### Error output

```
video_a_encrypted.webm could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: Encrypted content not supported outside of MSE
```

#### videojs
7.11.4
#### browsers
Firefox
#### OSes
Mac OS Big Sur 11.2.3
### plugins
videojs-contrib-eme: 3.8.0

**Comment by gkatsev** [comment]
Based on the error, it seems like Firefox doesn't support encrypted content that isn't MSE based. All the EME examples I see for Firefox use MSE.

**Comment by darind** [comment]
That’s correct, is there any plugin that can enable MSE in videojs?

**Comment by gkatsev** [comment]
We use MSE when you play back HLS or DASH content. When it's a file like webm, we hand it off to the browser for playback.
