### ISSUE TITLE
no sound on mp4 file with ac3 audio

### ISSUE THREAD

**Issue by fadysawairas** [videojs/video.js#7206]
## Description
when i upload mp4 video files with ac3 audio format the video play without sound 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.upload the video to my script supported with videojs player
2. try to play the video
3. no sound in the video

### Expected
video should play with sound

### Actual
video play without sound

### Error output
no error appear to me

**Comment by gkatsev** [comment]
Unfortunately, most browsers do not support the ac3 audio codec. Your best bet is retranscoding and using aac or mp3 audio.

**Comment by fadysawairas** [comment]
i made a lot of search yesterday and i found this and we now retranscoding again 
the problem that we need to transcoding around 1000 video now

**Comment by gkatsev** [comment]
That sucks, sorry.

**Comment by DuncanStone** [comment]
Any chance this could spit out an error to the console along the lines of "audio codec not found <codecname>"?

**Comment by gkatsev** [comment]
Unfortunately, not really. It should be possible to do for something like HLS or DASH, but isn't possible for an mp4. The Media panel in Chrome might log whether the codec isn't supported or not.
