### ISSUE TITLE
Can't resolve node_modules import in video-js.scss with yarn berry

### ISSUE THREAD

**Issue by rtritto** [videojs/video.js#7208]
## Description
I'm using [yarn](https://yarnpkg.com) (berry version) with `video.js`, `sass`, `sass-loader` and `webpack` modules.
I have a `scss` file with `video.js/src/css/video-js.scss` import.
`video.js/src/css/video-js.scss` file imports `node_modules/videojs-font/scss/icons`.
During compiling, I get an import error on `node_modules/videojs-font/scss/icons`.

## Steps to reproduce
1. `yarn init -y`
2. `yarn set version berry`
3. `yarn add sass sass-loader video.js@next webpack webpack-cli`
4.  Create files:
- `src/index.js`
```JS
import './styles.scss'
```
- `src/styles.scss`
```SCSS
@import 'video.js/src/css/video-js.scss';
```
- `webpack.config.js`
```JS
module.exports = {
  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [
          {
            loader: 'sass-loader',
            options: {
              implementation: require('sass')
            }
          }
        ]
      }
    ]
  }
}
```
5. `yarn webpack`

### Expected
Build completed.

### Actual
During build, I get this error:
```console
SassError: Can't find stylesheet to import.
  ╷
5 │ @import "node_modules/videojs-font/scss/icons";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

#### OS
Windows

## How to fix (Updated)
1. In file `video.js/src/css/video-js.scss` change the import (remove hardcoded *node_modules*):
```diff
 @import "private-variables";
 @import "utilities";
 
- @import "node_modules/videojs-font/scss/icons";
+ @import "videojs-font/scss/icons";
 
 @import "components/layout";
 @import "components/big-play";
```

2. In scripts of *package.json* change the value of option [load-path](https://sass-lang.com/documentation/cli/dart-sass#load-path) (from *'./'* to *node_modules*):
```diff
- "build:css:cdn": sass --load-path='./' --no-source-map src/css/vjs-cdn.scss dist/alt/video-js-cdn.css
- "build:css:default": sass --load-path='./' --no-source-map src/css/vjs.scss dist/video-js.css
+ "build:css:cdn": sass --load-path=node_modules --no-source-map src/css/vjs-cdn.scss dist/alt/video-js-cdn.css
+ "build:css:default": sass --load-path=node_modules --no-source-map src/css/vjs.scss dist/video-js.css
```

## Workaround
1. `yarn patch video.js`
2. Go to created folder and edit _src/css/video-js.scss_ with:
```diff
 @import "private-variables";
 @import "utilities";
 
- @import "node_modules/videojs-font/scss/icons";
+ @import "videojs-font/scss/icons";
 
 @import "components/layout";
 @import "components/big-play";
```
3. `yarn patch-commit -s "<created_folder_path>"`
4. `yarn`

**Comment by gkatsev** [comment]
I'd have to investigate some more, but I think changing the path in there will potentially break all current users of our sass styles. In addition, we'd want to make sure that our regular dist builds continue working as well, and based on what I've seen from the `sass` module, it doesn't do module resolution itself.

**Comment by rtritto** [comment]
Should I use some configuration in webpack to rewrite/resolve that import?

**Comment by rtritto** [comment]
Is there any update?

**Comment by gkatsev** [comment]
I haven't had a chance to investigate this. Does our CSS build still work after removing `node_modules`?
Also, I'd be worried about folks using various sass scripts like `sass` and `node-sass`. We can't breaking people in a patch or minor release.

**Comment by rtritto** [comment]
Thanks for reply.
Running current scripts `build:css:cdn` and `build:css:default`, I get:
```
Error: Can't find stylesheet to import.
  ╷
5 │ @import "videojs-font/scss/icons";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\css\video-js.scss 5:9  @import
  src\css\vjs-cdn.scss 3:9   root stylesheet
```
I solved both builds changing, in script, the value of option `--load-path` from `'./'` to `node_modules`.

**Comment by rtritto** [comment]
@gkatsev `video-js.scss` file can't be imported or compiled with `node-sass` but only with `sass` like scripts, in `package.json` of `video.js`, that use `sass`.

Anyway `node-sass` isn't supported by `sass-loader` using Yarn PnP (berry/v2).

Source from [documentation](https://webpack.js.org/loaders/sass-loader/) of `sass-loader`:
- ℹ️ We highly recommend using [Dart Sass](https://github.com/sass/dart-sass).
- ⚠ Node Sass does not work with [Yarn PnP](https://classic.yarnpkg.com/en/docs/pnp/) feature and doesn't support [@use rule](https://sass-lang.com/documentation/at-rules/use).

**Comment by rtritto** [comment]
Up

**Comment by rtritto** [comment]
Added a workaround.
