### ISSUE TITLE
videojs-chapter-thumbnail error in IOS version above 14 (Safari)

### ISSUE THREAD

**Issue by KayKim106** [videojs/video.js#7211]
I recently, found out this issue that videojs-chapter-thubmnails throw an error in IOS version 14 and Safari.
As far as I know, there are two requests that calls my server to get "subtitle" and "chapters" information.
There was no problem for calling subtitle and chapter under the IOS version 14, but above the version 14, chapters call was failed for some reason.
However, everything worked fine  under IOS version 14, Android, and the other computer browsers( except the safari)
So what I did for solving this issue, 

1. Update the up to dated Videojs, and videojs-chapters-thumbnails.
2. Added crossOrigin = "use-credentials" or "anonymous"
Both of attempts were failed. 

What Error looks like :   
Unsafe attempt to load URL https://resource4.earthcam.net/v0/object/xDc5DW5cmkXABa60brCcrPtpibcwa8b89t4Pf7Fr18M!/chapters?k=fbe9c2670248dedcd8fe4a00f37cefac from origin http://public.earthcam.net. Domains, protocols and ports must match.

You will be able to compare the issue from chrome browser and safari with below link 
http://public.earthcam.net/earthcam/earthcampus/work_zone_cam_exterior/view_1/timelapse

Issue product :
1. Apple product IOS version 14 ( Chrome, Safari )
2. Safari version 14.0.03

did anyone has this kind issue recently?

**Comment by gkatsev** [comment]
We have seen some issues around native track load on iOS/Safari 14 which generally was solved with crossorigin=anonymous.

**Comment by KayKim106** [comment]
> We have seen some issues around native track load on iOS/Safari 14 which generally was solved with crossorigin=anonymous.

Thank you for the comment. If you meant to adding the "crossorigin=anonymous" into video tag, I already tried, but it did not let me play the video. 
here is the image what I got after I added up the crossorigin=anonymous into video tag.

![image](https://user-images.githubusercontent.com/20199377/117149385-2badd400-ad85-11eb-9d47-c9c81b766089.png)

and what source this video is referencing from : 
https://resource4.earthcam.net/videos/xDc5DW5cmkXABa60brCcrKutc5lqFkISvxDJUSmQrGbZAvw4_XCXiTNiKypWxBN52T0UwLvJ4wXvgjvJAWPacw!!.mp4

and I just curious that why adding the crossorigin=anonymouse into video tag affects "chapters" request? It seems like subtitle request looks fine without adding crossorigin=anonymouse.

![image](https://user-images.githubusercontent.com/20199377/117150422-23a26400-ad86-11eb-9d0f-6b4bc3b17ec6.png)

Is there any other solution I can try?

**Comment by gkatsev** [comment]
Can you provide a reduced example that doesn't use minified code? It'll make it a lot easier to help out.
My initial guess is that your response is setting `access-control-allow-credentials` to true when credentials aren't being used, and it's possible that Safari 14 is stricter about that.
