### ISSUE TITLE
videojs-vr-sd - how to modify Camera Position for 360° video?

### ISSUE THREAD

**Issue by issimissimo** [videojs/video.js#7212]
Hello,
I'm using "videojs-vr-sd" plugin to show some 360° videos.

I can get the Camera Position with:
var player = videojs('my-video');
player.vr().cameraVector;

But how can I modify Camera Position (to rotate the camera to initial view with a button, for example) ?

Maybe this is not the right place to post question on plugin, but I can't find any other place for it
Many thanks!!

**Comment by FredZeng** [comment]
```js
var vr = player.vr();
// vr.movieScreen.position.set(x, y, z); // `movieScreen` instanceof `THREE.Mesh`
```
