### ISSUE TITLE
Help: How can we change the audio tracks with video.js ?

### ISSUE THREAD

**Issue by hrithikppawar** [videojs/video.js#7222]
## Description
I have video file of .mp4 format. It has multiple audio tracks in-built in it. 

Video.js is not detecting those audio tracks. Is there any way to target particular audio track.

How to target those audio tracks and how can we change them with video.js ?

**Comment by gkatsev** [comment]
Unfortunately, that isn't possible with most browsers. I believe that Safari may expose the audio tracks, but other browsers do not currently expose it. I think Chrome was working on it, but I don't think that has shipped. Your best bet if you want multiple audio tracks is to generate HLS or DASH content with the other audio tracks enumerated in the manifests.

**Comment by hrithikppawar** [comment]
@gkatsev Thank you for your response.
I am working on a use case, where I have one video file and multiple **separate** audio files of multiple languages and we are trying to build a video player where user can play any of this audio files in the background of that video like a audio track. 

This task of adding audio tracks must be done at the frontend because backend is providing us URLs for multiple audio files.

I tried adding .mp3 audio file to .mp4 video using **FFmpeg**  and then playing it using Video.js but it is not detecting the audio tracks.
```javascript
const addAudioTack = async () => {
        // write the files to memory
        ffmpeg.FS('writeFile', 'video.mp4', await fetchFile(video));
        ffmpeg.FS('writeFile', 'audio.mp3', await fetchFile(audio));

        // run the ffmpeg commands
        await ffmpeg.run('-i', 'video.mp4', '-i', 'audio.mp3', '-map', '0', '-map', '1:a', '-c:v', 'copy', '-shortest', 'result.mp4');
        
        // read the result file
        const dataMp4 = ffmpeg.FS('readFile', 'result.mp4');
        const dataMp4Url = URL.createObjectURL(new Blob([dataMp4.buffer], { type: 'video/mp4' }));
        setResultMp4Video(dataMp4Url);
```

After adding audio track I also tried to convert the .mp4 file to the .m3u8 file and then tried create an URL but it gives a error while doing that.

I tried :
```javascript
const addAudioTack = async () => {
        // write the files to memory
        ffmpeg.FS('writeFile', 'video.mp4', await fetchFile(video));
        ffmpeg.FS('writeFile', 'audio.mp3', await fetchFile(audio));

        // rum the ffmpeg commands
        // adding audio track to video
        await ffmpeg.run('-i', 'video.mp4', '-i', 'audio.mp3', '-map', '0', '-map', '1:a', '-c:v', 'copy', '-shortest', 'result.mp4');
        // .mp4 to .m3u8
        await ffmpeg.run('-i', 'result.mp4', '-b:v', '1M', '-g', '60', '-hls_time', '2', '-hls_list_size', '0', '-hls_segment_size', '500000', 'resultVideo.m3u8')

        // read the result file
        const data = ffmpeg.FS('readFile', 'resultVideo.m3u8');
        const dataUrl = URL.createObjectURL(new Blob([data.buffer], { type: 'application/x-mpegURL' }));
        setResultVideo(dataUrl)
```

but I got this error: 
```
resolve-url.js:26 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at resolveUrl (resolve-url.js:26)
```

Can you suggest any **way** or **method** or any **resource** from where I can learn more about it to implement this use case with video.js or any other player?

**Comment by gkatsev** [comment]
What you're trying to do sounds exactly what HLS and DASH can do for you. It does take a bit more set up but the output manifest has the video and can have the audio completely separate. The HLS spec has an example here https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-8.6

**Comment by gkatsev** [comment]
I would recommend updating your backend to generate HLS or DASH directly rather than trying to combine it haphazardly into it on the client-side.

**Comment by hrithikppawar** [comment]
@gkatsev Thank you for your suggestion. I totally agree. But we have a web app which helps user to manipulate with video on browser itself. Is there any way to perform above mentioned task on browser itself? and Is there any way to create HLS content in browser itself or is there any API which can help us to create HLS content by providing video and audio files?
