### ISSUE TITLE
fail to play encrypted HLS

### ISSUE THREAD

**Issue by salehasadi** [videojs/video.js#7225]
## Description
when I try to play an encrypted HLS file, it throw a warning to console and does not play the file (I can play same file with hls.js and other players).

I created a pen with your own starter template and put my url there and you can check that if needed
https://codepen.io/saleh-asadi1994/pen/poevBrO

a working pen with same file and other player
https://codepen.io/saleh-asadi1994/pen/wvJBZyp

![image](https://user-images.githubusercontent.com/14921568/117534320-1a272f00-b006-11eb-89c1-a8b79d396130.png)

#### videojs
7.11.8 and older versions too
#### browsers
Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
#### OSes
Ubuntu 20.04.2 LTS
### plugins
vhs

**Comment by ziddey** [comment]
tip: `videojs.log.level('debug')` will help you see what's going on

![chrome_rT0PJgAdxr](https://user-images.githubusercontent.com/3846501/117597738-344f3300-b114-11eb-88ab-d859e6916c34.png)

https://github.com/videojs/http-streaming/blob/552b012035b6f2fd8da8440a41928668d85e25a8/src/media-segment-request.js#L121-L128

looks like vhs requires the response be 16 bytes. Your key is 16 bytes, but the newline puts the response at 17 bytes.

**Comment by salehasadi** [comment]
> tip: `videojs.log.level('debug')` will help you see what's going on
> 
> ![chrome_rT0PJgAdxr](https://user-images.githubusercontent.com/3846501/117597738-344f3300-b114-11eb-88ab-d859e6916c34.png)
> 
> https://github.com/videojs/http-streaming/blob/552b012035b6f2fd8da8440a41928668d85e25a8/src/media-segment-request.js#L121-L128
> 
> looks like vhs requires the response be 16 bytes. Your key is 16 bytes, but the newline puts the response at 17 bytes.

thanks @ziddey I will check that 👍🏻

**Comment by gkatsev** [comment]
Fwiw, I'm unable to get the video to work in Safari either. This generally implies an issue with the stream rather than the player.

**Comment by salehasadi** [comment]
@ziddey @gkatsev thanks, problem was a `\n` at the end of key, which was changing key to 17 bytes instead of 16 and is solved by dropping that, but maybe that could be better if key processor consider such stuffs, because in some situation maybe front developer has not access to backend guys and can't fix this problem server side.

**Comment by gkatsev** [comment]
Good find, must've not been easy. Unfortunately, I'm not sure if we can do anything about that, we can't know whether that is intended to be present or not.
