### ISSUE TITLE
videojs.Hls.xhr.beforeRequest doesn't work in Safari iOS

### ISSUE THREAD

**Issue by Raino** [videojs/video.js#7226]
Hello everyone!
I searched for information on this issue and found only old discussions of this problem (#1280, #1384).
It all came down to the fact that **Safari on iOS** does not support custom JS handlers and uses only its own, which is why the `videojs.Hls.xhr.beforeRequest` function cannot work. After that, I read that Apple has introduced support for the **FullScreen API** in **Safari** since **iOS 12**. 
I tried to play around with 
```
videojs.options.hls.overrideNative = true;
videojs.options.html5.nativeAudioTracks = false;
videojs.options.html5.nativeVideoTracks = false;
```
but it did not bring any result. 
Maybe I messed up something and the **FullScreen API** doesn't affect how **HLS** works? 
Perhaps there are some solutions to this problem with the operation of `videojs.Hls.xhr. beforeRequest` in **Safari on iOS** in 2021, or there are some workarounds for using `videojs.Hls.xhr.beforeRequest`?

**Comment by gkatsev** [comment]
Unfortunately, iPhones do not support the fullscreen API nor Media Source Extensions, the API behind our playback engine. MSE not being supported means our playback engine cannot run and thus `beforeRequest` isn't available.
The Fullscreen API also doesn't work, but that's unrelated to `beforeRequest`.

**Comment by gkatsev** [comment]
To add, the fullscreen API is available on iPads but not iPhones.

**Comment by gkatsev** [comment]
To be clear, it's supported but only on iPads, not on iPhones. Why? Weird decisions from Apple.

What do you mean update src without restarting the player? You can pass a new source to the player via `player.src()` or `player.loadMedia()`

**Comment by Raino** [comment]
@gkatsev To replace the src player on the go, I used
```
videojs.Hls.xhr.beforeRequest = function(options){
	options.uri = ...
```
Is there a cross-browser solution with the same meaning?

**Comment by gkatsev** [comment]
I would *highly* recommend against using that method to change the source of the player. Instead, you should be setting a new source via the player.src() method.
```js
player.src({
  src: 'http://example.com/video.m3u8',
  type: 'application/x-mpegur'
});
```

**Comment by gkatsev** [comment]
There isn't anything you can do client-side for iPhones due to platform limitations.
