### ISSUE TITLE
Stop Exit Of Full Screen

### ISSUE THREAD

**Issue by ProdigyView** [videojs/video.js#7229]
I am playing multiple films via a Live Stream with VideoJS. The streams using the same url and play one after another each other. The issue I am running into is when the player is full screen, and the stream stops, the player exits full screen. The user has to back to full screen when the next video starts.

Is there a way to prevent full screen from exiting because a stream/video ends?

**Comment by gkatsev** [comment]
I don't see that behavior. Via this simple test page https://videojs-preview.netlify.app/sandbox/index.html, I can see it stay fullscreen when the video ends. It's potentially an issue with your integration. Can you provide a reduced test case?

**Comment by gkatsev** [comment]
It looks like your page refreshes the iframe where the player is embedded when the stream ends.
