### ISSUE TITLE
Double click fullscreen 360 videos

### ISSUE THREAD

**Issue by abannach** [videojs/video.js#7231]
## Description
When viewing a 360 degree video, double clicking on the video does not enter fullscreen. From my limited investigation it appears that the `<canvas>` element that covers the `<video>` element is there to facilitate the click and drag functionality. However, this means that it eats the double click event and the `<video>` element doesn't receive it.

Looks like https://github.com/videojs/video.js/pull/5148 incorporated double click functionality on the media element, but doesn't pass through the event when clicking on the canvas.

Example: https://widendev.widen.net/s/g9qbpkjkhd/360_video_sample
 
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Render a 360 degree video in the player 
2. Notice that you can click and drag to rotate, but can not double click to go fullscreen

### Expected
Double clicking on 360 degree video goes to fullscreen.

### Actual
Double clicking on 360 degree video does not go to fullscreen.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
`7.11.4`
#### browsers
All
#### OSes
All? limited investigation was done on `macOs Catalina 10.15.7`
### plugins
`"videojs-contrib-quality-levels": "^2.0.9"`

**Comment by FredZeng** [comment]
Check the video element, it has been setted `display: none;`. 

![image](https://user-images.githubusercontent.com/17154608/118344981-28c09980-b564-11eb-958c-04c4b30b674f.png)

It seems that the example is using `videojs-vr` plugin, which hasn't handle the 'dblclick' event on 'canvas'. You may need to handle by yourself.

**Comment by FredZeng** [comment]
You may want to try this:

```js
var player = window.player = videojs('videojs-vr-player');
player.mediainfo = player.mediainfo || {};
player.mediainfo.projection = '360';

// AUTO is the default and looks at mediainfo
var vr = window.vr = player.vr({
  projection: 'AUTO', debug: true, forceCardboard: false, omnitone: Omnitone,
  omnitoneOptions: {}
});
var playerDoubleClick = (e) => {
  player.handleTechDoubleClick_(e);
};
// handle double click
vr.on('initialized', () => {
  vr.renderedCanvas.addEventListener('dblclick', playerDoubleClick);
});
vr.on('dispose', () => {
  vr.renderedCanvas.removeEventListener('dblclick', playerDoubleClick);
});
```

**Comment by abannach** [comment]
Ah, we will look into that. I wasn't aware we leveraged `videojs-vr`, but looks like my company had forked the `videojs-vr` plugin a while back. Thanks for the code snippit to try.

**Comment by abannach** [comment]
Created a ticket on our end for investigation and resolution.
