### ISSUE TITLE
Failed to construct 'URL': Invalid URL on videojs 7.12.2

### ISSUE THREAD

**Issue by khavishbhundoo** [videojs/video.js#7240]
## Description
I am getting the following issue on 7.12.2 only with no issue on 7.12.1

Stack trace:

```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at resolveUrl (video.js:30781)
    at setupMediaPlaylists (video.js:38549)
    at addPropertiesToMaster (video.js:38672)
    at parseMasterXml (video.js:41203)
    at DashPlaylistLoader.handleMaster_ (video.js:41819)
    at video.js:41728
    at callbackWrapper (video.js:40435)
    at Object.callback (video.js:40460)
    at cbOnce (video.js:7904)
    at XMLHttpRequest.loadFunc (video.js:7978)

```

Source: base64 encoded dash manifesh

&lt;source  src="data:application/dash+xml;charset=utf-8;base64...." type="application/dash+xml"       /&gt;
&nbsp;

<br class="Apple-interchange-newline">

It might be related to this commit 

https://github.com/videojs/vhs-utils/commit/e7eaab9969e61d487c35e78bd907f7589bdc8e16

#### videojs
7.12.2

**Comment by gkatsev** [comment]
Interesting, we'll definitely take a look. Meanwhile, continue using version 7.12.1.

**Comment by gkatsev** [comment]
Do you have a sample DASH manifest you can share? I've tried an an HLS manifest and I've noticed that if all the URLs are absolute it works fine but that relative URLs don't work.

**Comment by khavishbhundoo** [comment]
All the urls in the dash manifests are absolute

**Comment by gkatsev** [comment]
Out in 7.12.3
