### ISSUE TITLE
Links on the website are broken

### ISSUE THREAD

**Issue by ZacBoyet** [videojs/video.js#7243]
The "Get Started", "Docs" and "Designer" links on the website nav bar are broken.

**Comment by gkatsev** [comment]
They seem to be working for me. Anyone else able to confirm?

**Comment by ZacBoyet** [comment]
Ok, it appears that there are two versions of the site. www2.videojs.com and videojs.com. videojs.com seems to be fine but the www2.videojs.com version that I hit from a google search has the broken links.

**Comment by gkatsev** [comment]
That's really weird that www2.videojs.com is still surfacing from google. It's a very old version of our site.
