### ISSUE TITLE
it doesn't work on IE11。vue + video.js

### ISSUE THREAD

**Issue by LITTMER** [videojs/video.js#7246]
## Description
在Chrome是正常的，IE 报错无法播放。
### Expected

正常播放
### Actual
![3c325288cdccf0cfd6cf20410f245c4](https://user-images.githubusercontent.com/26783653/119447642-c9803780-bd62-11eb-96bf-e0f5ee32c725.png)

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
"video.js": "^7.11.8",
#### browsers
what browser are affected?
IE11  11.3808.14393.0
#### OSes
window 10

**Comment by jinqinghua** [comment]
try to use "video.js": "7.9.7"?

**Comment by gkatsev** [comment]
We regularly test with IE11 (and it's part of our CI process), so, it should work. I've also confirmed that Video.js is working on IE11.
This is likely an issue with your integration rather than with Video.js itself. If you can share a live reduced example we may be able to help.

**Comment by LITTMER** [comment]
> 我们定期使用 IE11 进行测试（它是我们 CI 过程的一部分），因此它应该可以工作。我还确认 Video.js 正在 IE11 上工作。
> 这可能是您的集成问题，而不是 Video.js 本身的问题。如果您可以分享一个现场简化示例，我们可能会提供帮助。
