### ISSUE TITLE
Progress bar time tooltip out of bounds on the right

### ISSUE THREAD

**Issue by nochev** [videojs/video.js#7248]
## Description
Hello all, I updated `video.js` from `5.20.5` to `7.12.3` and having issue with the time tooltip.

When I moving mouse at the end of progress bar time tooltip going out of bounds. Seems the issue has come from this PR https://github.com/videojs/video.js/pull/5773/. In `TimeTooltip.update` method invoked by the mouse move event `seekBarRect` doesn't contain `right` property and  this produce wrong calculation. When I add the following debug https://screenrec.com/share/Unp5mABVWo I'm seeing this https://screenrec.com/share/IRwJPp8nZ0. On the player `ready` event, object contains all properties https://screenrec.com/share/1Vl4iWBcFq.

## Steps to reproduce
1. Move the mouse to the end of progress bar

### Expected
The time tooltip fitting the bounds as at the left side https://screenrec.com/share/cY6PQmxRs4

### Actual
The time tooltip going out of bounds on the right side https://screenrec.com/share/LXBeKnQm27

## Additional Information
If I replace `findPosition(seekBarEl)` with `getBoundingClientRect(seekBarEl)` in `ProgressControl.handleMouseMove` method problem is solving https://screenrec.com/share/tKp1VvlcG4.
#### videojs
`7.12.3`
#### browsers
Tested on `Version 90.0.4430.212 (Official Build) (64-bit)`
#### OSes
`Windows 7`
### plugins
`videojs-contrib-ads` and `videojs-ima`

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
+1


https://user-images.githubusercontent.com/73130443/123659303-0e93ff80-d822-11eb-8557-58da4a91a62f.mp4

**Comment by PikachuEXE** [comment]
The calculation of `spaceRightOfPoint` is broken by the `undefined` value in `seekBarRect.right` on
https://github.com/videojs/video.js/blob/v7.14.0/src/js/control-bar/progress-control/time-tooltip.js#L75-L76

The `seekBarRect` is from
https://github.com/videojs/video.js/blob/v7.14.0/src/js/control-bar/progress-control/progress-control.js#L75

And it's using [`findPosition`](https://github.com/videojs/video.js/blob/v7.14.0/src/js/utils/dom.js)
Which would never return `right`

By updating the calculation of `spaceRightOfPoint` to `spaceRightOfPoint = seekBarRect.width - seekBarPointPx`
I am able to see correct tooltip position calculation

![image](https://user-images.githubusercontent.com/1018543/124433724-a7d49000-dda5-11eb-9657-e03b4e5766f4.png)
https://user-images.githubusercontent.com/1018543/124434104-0f8adb00-dda6-11eb-9d9e-9f06db975fdd.mp4
