### ISSUE TITLE
Live HLS stream constantly buffering using video.js but not when using hls.js

### ISSUE THREAD

**Issue by ctoppel** [videojs/video.js#7249]
## Description
We have an HLS live stream url that is mp4 (H264 + AAC) behind the scenes and using the video.js player in it's most basic form I am unable to have playback in live mode without major buffering issues. Using the same url on an hls.js based player, I have no problems. Also the url viewed directly in safari has no issues. I would like to use video.js for skinning purposes, but cannot if the underlying functionality does not work with our stream.

As it is only a live stream, I cannot share a demo unless it is live (or within our token limit of 5 min).

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. instantiate videojs with basic options
2. Experience buffering issues
3. Instantiate hls.js player with same url
4. Don't experience buffer issues

### Expected
Expected same playback experience as using hls.js

### Actual
Terrible experience with constant buffering

### Error output
No errors 

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.12.3

#### browsers
what browser are affected?
Chrome

#### OSes
what platforms (operating systems and devices) are affected?
macOS Catalina

### plugins
none

**Comment by gkatsev** [comment]
Unfortunately, without a sample, there isn't anything we can do. Does your stream play any better in https://videojs-http-streaming.netlify.app/?
