### ISSUE TITLE
How can I handle split mp4 files

### ISSUE THREAD

**Issue by ericls** [videojs/video.js#725]
The thing is that I've got lots of video clips on my server , but many of them are split into 2 or 3 files(the duration of each file are already known).
Join those files on my server can be painful and consuming,so is there a way to deal with this without joining them on server.
Actually,I think allowing me to set the  maybe  helpful.
PS:English is not my mother language I hope it not a pain for you to read.

**Comment by tomorrowbetter** [comment]
I use a video splitter called iDealshare VideoGo  to split MP4 files 

Step by step guide at http://www.idealshare.net/video-converter/split-mp4-files.html

It can split video with or without re-encoding.

It can split all kinds of video files like MP4, MKV, MOV, WMV, VOB, FLV and etc

It even can split audio mp3, wav, m4a, aac, flac and etc.

**Comment by aimkeepachieve** [comment]
I use iDealshare VideoGo to split MP4 files

I like its split MP4 video without re-encoding

You may find it and the step by step guide at http://www.idealshare.net/video-splitter-for-mac-windows.html

 

http://www.idealshare.net/video-splitter-for-mac-windows.html
