### ISSUE TITLE
Autoplay (muted or unmuted) doesn't work in Chrome (Windows) with latest video.js

### ISSUE THREAD

**Issue by damienbuckley** [videojs/video.js#7250]
Autoplay is not working in Windows (only) Chrome v91.0.4472.77 

Using video js v7.11.4 with the following code - same muted or unmuted:

`              <video
                id="video-1"
                class="video-js vjs-fluid vjs-theme-ncr"
                controls
                preload="auto"
                loop="loop"
                autoplay
                muted
                data-setup='{}'
                poster="">
                <source src="" type="video/mp4">
                <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that
                 <a href="https://videojs.com/html5-video-support/" target="_blank" rel="noopener">supports HTML5 video</a>
                </p>
              </video>`

Seems to work fine in everything else…

**Comment by mister-ben** [comment]
I don't experience this on a similar version, v91.0.4472.19. Most likely a local issue. Does it work with a fresh profile?

**Comment by damienbuckley** [comment]
I have v91.0.4472.77 but it is also playing for me now…

That's really bizarre. I think this might be related to this:- https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Can you take a look at this please and tell me if it works for you - [http://newcenturyresources.propeller-dev.com](url)

**Comment by gkatsev** [comment]
Working for me on Windows with Chrome 91.0.4472.77.
Muted autoplay should generally always work, unmuted autoplay likely doesn't work.

**Comment by damienbuckley** [comment]
That's the weird thing. The client reported this initially as not working but I didn't see it until testing in windows Chrome (I was only working in other browsers to that point) where it also did not autoplay for me.

With no changes to the code, the client later reported the video autoplaying and when I checked today it is also autoplaying for me…

Is this the Chrome MEI policy at work? I absolutely assure you this was not previously autoplaying for either me or the client in windows chrome - either my local version or on the staging server posted above.

**Comment by gkatsev** [comment]
If it's muted, MEI shouldn't be involved. MEI should only affect things when the video is playing unmuted.

If you try an incognito window or a fresh profile, does it still autoplay for you?

**Comment by damienbuckley** [comment]
Bit of a wait but it did eventually autoplay in incognito mode. What do you mean by fresh profile?
