### ISSUE TITLE
Some Stream not work in QQ browser

### ISSUE THREAD

**Issue by whoisyourlove** [videojs/video.js#7252]
## Description
一些类型的流无法在一些chromium内核的浏览器上播放，比如在QQ浏览器,2345浏览器，但在Chrome和edge上可以正常播放

**在线测试地址**：https://video.isyour.love/test.html

**流文件类似：**
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:3,
https://p1.pstatp.com/img/tos-cn-i-0000/96049701c21e47bcb433bf7c1b56eb6d~tplv-obj.image
#EXTINF:3,
https://p1.pstatp.com/img/tos-cn-i-0000/74093883254b4b5aa378f823f95ce500~tplv-obj.image
#EXTINF:3,
https://p1.pstatp.com/img/tos-cn-i-0000/a363010355e4483f80d6e3683147ce4f~tplv-obj.image
#EXTINF:3,
https://p1.pstatp.com/img/tos-cn-i-0000/594b822148ea48b396304e41a514ea9d~tplv-obj.image
#EXTINF:5.24,
https://p1.pstatp.com/img/tos-cn-i-0000/9cac02dccc2345dbbfdbc1c5395e0213~tplv-obj.image

## Steps to reproduce
1.下载QQ浏览器
2.打开测试地址 https://video.isyour.love/test.html
3.报错

## Results
运行出现错误

### Actual
希望能兼容这些chromium的浏览器，谢谢

### Error output
1.video append of 35945b failed for segment #0 in playlist 0-https://vod.bunediy.com/20200509/MT1wvLmS/index.m3u8
2.runner-4.1.8.min.js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
在线测试：https://video.isyour.love/test.html
M3u8地址:https://vod.bunediy.com/20200509/MT1wvLmS/index.m3u8
QQ浏览器下载地址:https://browser.qq.com/
### versions
V7.11.8
#### browsers
QQ浏览器 2345浏览器
#### OSes
Window 10
### plugins
没有

**Comment by mister-ben** [comment]
https://browser.qq.com says QQ is Chromium 70. If that's true it's two and a half years behind Chrome and Edge.

**Comment by whoisyourlove** [comment]
> https://browser.qq.com说 QQ 是 Chromium 70。如果这是真的，它比 Chrome 和 Edge 晚了两年半。

这个错误很奇怪。当我尝试用JS创建播放器时，它有10%概率可以在QQ浏览器正常播放。应该是一个很小的的兼容问题，你能修复它吗，谢谢

**Comment by dinglino1** [comment]
I met the same problem. Have you solved it?
