### ISSUE TITLE
Does video.js support HLS protocol to play H265 encoded video format? If so, how should it be implemented.

### ISSUE THREAD

**Issue by vhjmlw** [videojs/video.js#7257]
## Description
Does video.js support HLS protocol to play H265 encoded video format? If so, how should it be implemented.

### Expected
Get the final result

#### videojs
7.11.4
#### browsers
chrome 90.0
#### OSes
widnows 10 x64
### plugins
no

**Comment by FredZeng** [comment]
Maybe u need [http-streaming](https://github.com/videojs/http-streaming/blob/main/docs/supported-features.md)

**Comment by mister-ben** [comment]
Only if the browser supports h264. Currently that's only Safari.

**Comment by gkatsev** [comment]
See my answer over here https://github.com/videojs/video.js/issues/7039#issuecomment-759577302
As @mister-ben said it's mostly dependent on the browser support.
