### ISSUE TITLE
react-native-web: isImmediatePropagationStopped is not a function

### ISSUE THREAD

**Issue by awinograd** [videojs/video.js#7259]
The event "polyfill" detection

https://github.com/videojs/video.js/blob/4238f5c1d88890547153e7e1de7bd0d1d8e0b236/src/js/utils/events.js#L107

 doesn't seem to be compatible with react-native-web's event system.  `isPropagationStopped` is defined on MouseEvents (https://github.com/necolas/react-native-web/blob/66d01734ce3ffcfea61e05aa1b45015658b3f2af/packages/react-native-web/src/modules/createEventHandle/index.js#L69) but isImmediatePropagationStopped is not which causes the error ` isImmediatePropagationStopped is not a function` to be thrown here:

https://github.com/videojs/video.js/blob/32630d964b3fc502143a935c219d092eb683fce0/src/js/utils/events.js#L304

**Comment by kentferolino** [comment]
Are you able to solve this @awinograd ?

**Comment by awinograd** [comment]
I applied the following patch with `patch-package`. It's worked well for me so far, but use at your own risk!

```
diff --git a/node_modules/video.js/dist/video.es.js b/node_modules/video.js/dist/video.es.js
index 94e1f35..3612ca6 100644
--- a/node_modules/video.js/dist/video.es.js
+++ b/node_modules/video.js/dist/video.es.js
@@ -2024,7 +2024,7 @@ function fixEvent(event) {
   // with the Javascript Ninja code. So we're just overriding all events now.
 
 
-  if (!event || !event.isPropagationStopped) {
+  if (!event || !event.isPropagationStopped || !event.isImmediatePropagationStopped) {
     var old = event || window.event;
     event = {}; // Clone the old object so that we can modify the values event = {};
     // IE8 Doesn't like when you mess with native event properties
```

**Comment by kentferolino** [comment]
Thanks for the suggestion @awinograd !

**Comment by kentferolino** [comment]
I got mine working using this snippet

- if (event.isImmediatePropagationStopped()) {
+ if (event && event.isImmediatePropagationStopped && event.isImmediatePropagationStopped()) {

**Comment by gkatsev** [comment]
@awinograd care to submit a PR for this?

Seems like react-native-web basically implements a lot of the same type of events that we do, but it only implements `isPropagationStopped` but not `isImmediatePropagationStopped`. This means that we do want to "fix" this event into our event system.

**Comment by necolas** [comment]
`preact/compat` also adds `isPropagationStopped` to native events as part of emulating React synthetic events. It's not great, and I don't think this library should be emulating React's synthetic event extensions either.

**Comment by gkatsev** [comment]
Yeah, everyone is basically following jQuery's lead here hehe

**Comment by awinograd** [comment]
I'm happy to open a PR. Though I do agree with @necolas in that this event emulation is pretty fragile. Unfortunately I dont have much to contribute towards a better solution in that regard.

**Comment by gkatsev** [comment]
It's been working (mostly) great for us for years, though, yeah, it's definitely not great.
At some point, maybe we'll find the time to see if we can rip out the entire event system and only rely on native events. But for now, we're stuck.
A PR would be appreciated!

**Comment by awinograd** [comment]
@gkatsev I definitely understand the need to find the right balance! Thanks for all your work on the library. I've opened a PR as requested.

https://github.com/videojs/video.js/pull/7286

**Comment by gkatsev** [comment]
Thanks!
