### ISSUE TITLE
Api to get audio bitrate for demuxed hls streams

### ISSUE THREAD

**Issue by rastogi19** [videojs/video.js#7262]
## Description
Briefly describe the issue.
video.js version 7.12.3
Currently i am using the cuechange event on the segment metadata referred from the  following link :- https://github.com/videojs/http-streaming#segment-metadata but from this we get combined bitrate in case of hls muxed streams and only video bitrate in case of HLS demuxed streams .
Please suggest api or some way to get the audio bitrate or combined bitrate (audio + video) for Hls demuxed streams.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Play any HLS demuxed stream.
2. try to get the bitrate information using 'cuechange' event on the segment metadata.
3. Match the value with the audio+ video bitrate mentioned in the video manifest file.

### Expected
Combined Audio + Video bitrate value being reported .

### Actual
Only Video bitrate is being reported.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.12.3
#### browsers
what browser are affected?
Al browsers
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.
vhs 2.8.2

**Comment by gkatsev** [comment]
I'm not sure that there's a good way to get the audio bitrate. If native playback is used, there's no way to get it at all. For non-native playback, it's trickier.

For muxed streams, I believe, we don't actually unpack stuff enough to calculate, and the data isn't really exposed.

For demuxed streams, it might be possible to calculate this, but it isn't something that is officially publicly available, and we'd recommend *against* using it. However, for posterity, you could do it by calculating the bitrate based on the bandwidth available on the audio segment loader. You can find it via `player.tech().vhs.masterPlaylistController_.audioSegmentLoader_.bandwidth` but this value is also cumulative, so, each segment's size gets added to this, so, you'd need to calculate differences and what not for each time a segment is loaded. Also, this bandwidth isn't the actual bitrate but might be a good enough approximation.
