### ISSUE TITLE
i have issue segmentation

### ISSUE THREAD

**Issue by Ammar441** [videojs/video.js#7264]
when i play any m3u8 url the video js player is segmentation every min
also when i play any hd  or fhd image not displaying just play sound

**Comment by gkatsev** [comment]
Are you able to provide us with your stream? Unfortunately, we won't be able to help without it.

**Comment by Ammar441** [comment]
I can't because the subscription for iptv

**Comment by gkatsev** [comment]
Unfortunately, without some kind of sample that displays your issue, we can't help.
