### ISSUE TITLE
video.js not working on chrome and brave browser

### ISSUE THREAD

**Issue by lucius100** [videojs/video.js#7266]
## Description
I have a website built with node js and embed using video.js, 
using these default code on npm guide

https://pastebin.com/kSCGQ7pB

Firefox browsers working fine, chrome mobile working fine, only chrome and brave desktop can't play the videos.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

what version of videojs does this occur with? videojs 7.12.3

what browser are affected? chrome browsers

what platforms (operating systems and devices) are affected? windows 10 OSes

are any videojs plugins being used on the page? If so, please list them below.
no plugin

**Comment by lucius100** [comment]
> 
> 
> Using the code from your pastebin, I created a codepen and I can see playback happen: https://codepen.io/gkatsev/pen/mdWGybZ. I verified in Chrome on macOS and Windows 10.
> We regularly test with Chrome and Firefox. We don't test on Brave, but it should generally work there too.
> 
> Is your issue with your content or are you able to reproduce specifically with the oceans video? Have you tried restarting your browser or windows? I have seen some times where Chrome's media stack fails and won't play any more video until it is restarted.

I see that u have many video sources inside the code.
I only have mp4 files, and I put it inside like this

  <source src="//vjs.zencdn.net/v/oceans.mp4" type="video/mp4"></source>
  <source src="//vjs.zencdn.net/v/oceans.mp4" type="video/webm"></source>

Does the chrome grabbing from webm sources ?
I didn't test yet with zen videos, My problem is video loading, but it just stuck there for chrome browsers, I can see the preload, but the video won't move, stuck at 00:00. I will provide screenshoot and test more later, currently outside atm.

**Comment by gkatsev** [comment]
If you're able to share your sources, that would be helpful as well. It's likely that your sources are not encoded in a way that the browser can play them properly.

**Comment by lucius100** [comment]
> 
> 
> If you're able to share your sources, that would be helpful as well. It's likely that your sources are not encoded in a way that the browser can play them properly.

Strange, after I check this morning, it's working now.
Didn't know what caused the issue last night.
Maybe some of my plugin blocking it or something, but it's working fine now. Thanks
