### ISSUE TITLE
DASH Stream (webm) not working with VideoJS

### ISSUE THREAD

**Issue by agmorpheus** [videojs/video.js#7267]
## Description
Hello, for a help application that is based on the Chromium Embedded Framework (CEF) I want to use videojs. By default the CEF is not playing h.264 encoded video. So I want to use webm encoded videos. Playing single webm files with videojs is no problem but I can not play dashed webm streams. 
**Please help me to get this dash stream working with videojs. The dash files are created via ffmpeg.**

## Steps to reproduce
I have created a fiddle without any additional dash scripts: https://jsfiddle.net/agmorpheus/pdegsch3/3/
Videojs is displaying an error: Playback cannot continue. No available working or supported playlists. (Playing HLS streams works perfectly)

I also created a fiddle with dash.js and videjs-dash.js file: https://jsfiddle.net/agmorpheus/pdegsch3/4/
Video is playing for a second and then stops. 
A lot of buffer errors are shown in the console

### Expected
I expect that videojs plays the dash stream.
When I use the [dash.js](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html) script without videojs the dash stream works.
What I also expect, if the dash stream is not working or supported by videojs, then if should play a fallback source. The fiddle example has a fallback source and it is not played.

### Actual
see Steps to reproduce

### Error output
see fiddle examples

#### videojs
latest
#### browsers
Chrome
#### OSes
Win10
### plugins
no plugins

**Comment by gkatsev** [comment]
Unfortunately, looks like jsfiddle won't work anymore. Their CSP on their results pane forbids workers and blob urls.
you're actually in luck. We recently (finally) added a new option `retryOnError` which handles this.
I've copied your example to codepen and added the option and I can see it choosing a different source and playing back: https://codepen.io/gkatsev/pen/wvJVJwa?editors=1011

**Comment by agmorpheus** [comment]
Thank you for this hint. The new option is good but it only mask the main problem. Why is the dash stream not playing? The stream plays well when only the Dash.js file is used. Combined with videojs it is not.

**Comment by gkatsev** [comment]
Totally forgot that part of the question. Unfortunately, we don't support webm segments in dash right now. All our code depends on inspecting mp4 and adding webm likely isn't trivial. If you prefer DASH playback and DASH.js works for you, you can add it into Video.js with https://github.com/videojs/videojs-contrib-dash

**Comment by unixfox** [comment]
Can this be reopened? It's not working
