### ISSUE TITLE
Firefox does not play video through Media Source Extensions

### ISSUE THREAD

**Issue by shirik534** [videojs/video.js#7275]
## Description
When trying to play a video through a media source
`player = videojs(document.querySelector('video'), {
	autoplay: true,
	controls: true,
	muted: true,
	width: 1,
	height: 1
}, function onPlayerReady() {
	console.log(player)
});
...
mediaSource  = new MediaSource()
player.src([{type: 'video/mp4', src: window.URL.createObjectURL(mediaSource)}])
`

the Firefox browser gives an error

`Security Error: Content at «http://127.0.0.1:3000/#/stream» may not load or link to blob:http://127.0.0.1:3000/50ebe20f-bc55-4fa6-9fc5-446db0df11da.`

In other browsers the video plays correctly. Native html5 video also plays without errors. 

### Error output
`Security Error: Content at «http://127.0.0.1:3000/#/stream» may not load or link to blob:http://127.0.0.1:3000/50ebe20f-bc55-4fa6-9fc5-446db0df11da.`
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported`

#### videojs
7.11.8
#### browsers
Firefox 89.0
Chrome 91.0.4472.106
Opera 76.0.4017.177
Microsoft Edge 91.0.864.48
#### OSes
Windows 10

**Comment by gkatsev** [comment]
I believe the recommended way to attach a MediaSource is via `srcObject`, you wouldn't be able to do it via `player.src()` right now.
```js
player.tech().el().srcObject = mediaSource;
```

**Comment by shirik534** [comment]
> I believe the recommended way to attach a MediaSource is via `srcObject`, you wouldn't be able to do it via `player.src()` right now.
> 
> ```js
> player.tech().el().srcObject = mediaSource;
> ```

Thanks, it helped me
