### ISSUE TITLE
Plugin EventListeners not correctly removing themselves upon player.dispose

### ISSUE THREAD

**Issue by dwassing** [videojs/video.js#7276]
## Description
Hello VideoJS maintainers, I am developing with VideoJS and I am using the silvermine chromecast plugin (that you refer to yourselves). Whether the problem I am facing is related to videoJS or the plugin itself is beyond me, however. I have an [issue thread](https://github.com/silvermine/videojs-chromecast/issues/97) up on the chromecast repo, but I will briefly explain what is going on here as well.
First, the [reduced test case](https://codepen.io/wassing/pen/qBrQQab), I am quite new to web development myself (approx 6 months so far), so bear with me as I try to elaborate on this. I am developing a web app that includes dynamically loaded and disposed videoplayers, and this has been working excellently for me so far (I am utilizing your [angular component](https://docs.videojs.com/tutorial-angular.html) to create and destroy players as I go). The issue pertains to event listeners not detaching themselves properly on player.dispose(), causing memory leaks and clogging up my console.

## Steps to reproduce

1. Go to the reduced test case (duh), make sure you have a casting device available or the plugin won't fire (you do not need to cast, the plugin simply needs to load).
2. Press play. Pause the movie if you want, this is irrelevant.
3. Open the console log.
4. Press the mute button, I have wired it to cause the player to dispose.
5. Tab to another browser tab or change application completely (make sure you cannot visually see the test case page with the now dismantled player).
6. Tab back in to the browser tab with the player gone. Check the console log. An error similar to this should appear
![ChromecastDisposeErrorLog](https://user-images.githubusercontent.com/5759474/122056350-cc160000-cde9-11eb-8b19-2953de3fb5b7.PNG)

## Results
See steps to reproduce

### Expected
Console log should be empty because the event listeners should be gone.

### Actual
Event listeners are processing requests from the cast API framework to a removed player, thus causing it to produce aforementioned error.

### Error output
See steps to reproduce

## Additional Information
I found a [similar thread](https://github.com/videojs/video.js/issues/7081) upon searching for this specific issue, and therefore I thought it would be warranted to at least notify you about this problem. The actual code that should add/remove event listeners for the plugin is located at `@silvermine/videojs-chromecast/src/js/chromecast/ChromecastSessionManager.js`, on [lines 40 through 80](https://github.com/silvermine/videojs-chromecast/blob/master/src/js/chromecast/ChromecastSessionManager.js):
```
   init: function(player) {
      this.player = player;
      this._addCastContextEventListeners();

      // Remove global event listeners when this player instance is destroyed to prevent
      // memory leaks.
      this.player.on('dispose', this._removeCastContextEventListeners.bind(this));
      this._notifyPlayerOfDevicesAvailabilityChange(this.getCastContext().getCastState());
      this.remotePlayer = new cast.framework.RemotePlayer();
      this.remotePlayerController = new cast.framework.RemotePlayerController(this.remotePlayer);
   },

   // Add event listeners for events triggered on the current CastContext.
   _addCastContextEventListeners: function() {
      var sessionStateChangedEvt = cast.framework.CastContextEventType.SESSION_STATE_CHANGED,
          castStateChangedEvt = cast.framework.CastContextEventType.CAST_STATE_CHANGED;

      this.getCastContext().addEventListener(sessionStateChangedEvt, this._onSessionStateChange.bind(this));
      this.getCastContext().addEventListener(castStateChangedEvt, this._onCastStateChange.bind(this));
   },

   // Remove event listeners that were added in _addCastContextEventListeners}.
   _removeCastContextEventListeners: function() {
      var sessionStateChangedEvt = cast.framework.CastContextEventType.SESSION_STATE_CHANGED,
          castStateChangedEvt = cast.framework.CastContextEventType.CAST_STATE_CHANGED;

      this.getCastContext().removeEventListener(sessionStateChangedEvt);
      this.getCastContext().removeEventListener(castStateChangedEvt);
   },
```
I can confirm that this code indeed gets called upon dispose, but the event listeners do not get removed. I would very much appreciate to know if I am mis-using the player, the plugin or the framework in some way, but at this point I am starting to believe that there is some other problem going on.

I also fully understand if you do not recognize this as an issue because it is the event listeners of a plugin that do not get removed properly. If you firmly believe that the problem lies with the plugin, then this can be closed.

#### videojs
Latest and 7.10.2, both produce the same error.
#### browsers
Chrome: 91.0.4472.101 
#### OSes
Windows 10
### plugins
Chromecast plugin: 1.3.1

Thank you for your time, as well as your time spent developing Video.js! Regards, Daniel

**Comment by dwassing** [comment]
Found the issue, see the referenced thread in the other repo. Closing this, sorry for the inconvenience.

**Comment by gkatsev** [comment]
Cool, yeah, these types of things are generally a problem of the plugin. Have been busy so I couldn't look at it.

**Comment by dwassing** [comment]
All good, thanks for the ups @gkatsev, I have issued a pull request to the plugin repo to have this addressed. Hope to get some responses.
