### ISSUE TITLE
How to enable retryOnError option

### ISSUE THREAD

**Issue by John2397** [videojs/video.js#7277]
I dynamically create a video js player that streams HLS:

```
    let source = document.createElement('source');
    $(source).attr('type', "application/x-mpegURL");
    $(source).attr('src',  "video_link.m3u8");
    $(video_div).append(video_element)
    $(video_element).append(source);
    videojs(video_element)
```

However, because it takes for the stream a few seconds to be available,
I have to reload the page every few seconds until it is available.

My question is, would it be possible to make the player keep retrying the same source as long as it receives
this error?  `ERROR: (CODE:2 MEDIA_ERR_NETWORK) HLS playlist request error at URL `
(and possibly set a time period that keeps retrying?)

I've seen the newly added feature [retryOnError](https://github.com/videojs/video.js/pull/7038), but I'm not sure how to use it (and last comment states it's still not on documentation).

I've tried replacing `videojs(video_element)` with `videojs(video_element,{'retryOnError': true})` with no luck.

**Comment by FredZeng** [comment]
`retryOnError` only works when you declare more than one source. If one failed, player will try the next.
In your case, you can try the `reloadSourceOnError` Plugin. @see [reload-source-on-error.md](https://github.com/videojs/http-streaming/blob/c2154d71990c7d8498e11689dde8967042052448/docs/reload-source-on-error.md)

```js
var player = videojs(videoEl, options);
// activate the retry plugin
player.reloadSourceOnError({
    // customize your interval
    errorInterval: 5,
});
```

Or, retry by yourself by listening the `error` event.

```js
var player = videojs(videoEl, options);
player.on('error', () => {
    const error = player.error();
    if (error.code === 2) {
        // player.setSrc();
    }
});
```

**Comment by gkatsev** [comment]
Thanks, @FredZeng!
