### ISSUE TITLE
How to add menu button to the control bar?

### ISSUE THREAD

**Issue by aminekha** [videojs/video.js#7280]
I'm trying to add a menu button with 2 items to the control bar but none of the suggested solutions are working. 
Here's what I tried so far: 

```
addNewButton(data: { player: any; id: string; icon: string }) {
    var Button = videojs.getTech('Button');
    var myPlayer = data.player,
      controlBar,
      newElement = document.createElement('div'),
      newLink = document.createElement('a');

    newElement.id = data.id;
    newElement.className = 'downloadStyle vjs-control';

    newLink.innerHTML = "<i class='fas " + data.icon + " line-height' aria-hidden='true'></i>";
    newElement.appendChild(newLink);
    controlBar = document.getElementsByClassName('vjs-control-bar')[0];
    var insertBeforeNode = document.getElementsByClassName('vjs-quality-selector')[0];
    controlBar.insertBefore(newElement, insertBeforeNode);

    return newElement;
  }
```
```
var btna = this.addNewButton({
        player: this.player,
        icon: 'fa-info-circle',
        id: 'infoButton',
      });
      btna.onclick = function () {
        window.open('http://www.earthtv.com');
      };
```

This code produces a normal button but I want to improve it to become a menu button. How can I do that?

**Comment by mister-ben** [comment]
You can create a custom MenuButton by extending it and overriding `createItems` to populate the menu

```js
var MenuButton = videojs.getComponent('MenuButton');
var MenuItem = videojs.getComponent('MenuItem');

var CustomMenuButton = videojs.extend(
  MenuButton,
  {
    createItems: function() {
      // Must return an array of `MenuItem`s
      // Options passed in `addChild` are available at `this.options_`
      return this.options_.myItems.map(function(i) {
        var item = new MenuItem(player, {label: i.name});
        item.handleClick = function() { /* ... */ };
        return item;
      });
    }
  }
);

// Register as a component, so it can be added
videojs.registerComponent('CustomMenuButton', CustomMenuButton);

// Use `addChild` to add an instance of the new component, with options
player.controlBar.addChild('CustomMenuButton', {
  title: 'My menu',
  myItems: [{name: 'Hello'}, {name: 'World'}]
});
```

**Comment by aminekha** [comment]
> You can create a custom MenuButton by extending it and overriding `createItems` to populate the menu
> 
> ```js
> var MenuButton = videojs.getComponent('MenuButton');
> var MenuItem = videojs.getComponent('MenuItem');
> 
> var CustomMenuButton = videojs.extend(
>   MenuButton,
>   {
>     createItems: function() {
>       // Must return an array of `MenuItem`s
>       // Options passed in `addChild` are available at `this.options_`
>       return this.options_.myItems.map(function(i) {
>         var item = new MenuItem(player, {label: i.name});
>         item.handleClick = function() { /* ... */ };
>         return item;
>       });
>     }
>   }
> );
> 
> // Register as a component, so it can be added
> videojs.registerComponent('CustomMenuButton', CustomMenuButton);
> 
> // Use `addChild` to add an instance of the new component, with options
> player.controlBar.addChild('CustomMenuButton', {
>   title: 'My menu',
>   myItems: [{name: 'Hello'}, {name: 'World'}]
> });
> ```

I'm getting this error "Property 'extend' does not exist on type 'typeof videojs'"

**Comment by FredZeng** [comment]
just ignore the type checking, the latest `@types/video.js` lack of declaring `videojs.extend`

**Comment by aminekha** [comment]
I tried this but I'm getting 2 errors, one in **this.options_.myItems** and the other in **this.player** 
1- Property 'myItems' does not exist on type 'MenuButtonOptions'
2- Argument of type '() => VideoJsPlayer' is not assignable to parameter of type 'VideoJsPlayer'.
  Type '() => VideoJsPlayer' is missing the following properties from type 'VideoJsPlayer': bigPlayButton, controlBar, errorDisplay, liveTracker, and 132 more.

```
class CustomMenuButton extends MenuButton {
        createItems() {
          // override
          return this.options_.myItems.map((i: { name: any }) => {
              var item = new MenuItem(this.player, { label: i.name });
              item.handleClick = function () {
                /* ... */
              };
              return item;
            });
        }
      }

      // Register as a component, so it can be added
      videojs.registerComponent('CustomMenuButton', CustomMenuButton);

      // Use `addChild` to add an instance of the new component, with options
      this.player.controlBar.addChild('CustomMenuButton', {
        title: 'My menu',
        myItems: [{ name: 'Hello' }, { name: 'World' }],
      });
```

Am I doing it wrong?

**Comment by FredZeng** [comment]
> I tried this but I'm getting 2 errors, one in **this.options_.myItems** and the other in **this.player**
> 1- Property 'myItems' does not exist on type 'MenuButtonOptions'
> 2- Argument of type '() => VideoJsPlayer' is not assignable to parameter of type 'VideoJsPlayer'.
> Type '() => VideoJsPlayer' is missing the following properties from type 'VideoJsPlayer': bigPlayButton, controlBar, errorDisplay, liveTracker, and 132 more.
> 
> ```
> class CustomMenuButton extends MenuButton {
>         createItems() {
>           // override
>           return this.options_.myItems.map((i: { name: any }) => {
>               var item = new MenuItem(this.player, { label: i.name });
>               item.handleClick = function () {
>                 /* ... */
>               };
>               return item;
>             });
>         }
>       }
> 
>       // Register as a component, so it can be added
>       videojs.registerComponent('CustomMenuButton', CustomMenuButton);
> 
>       // Use `addChild` to add an instance of the new component, with options
>       this.player.controlBar.addChild('CustomMenuButton', {
>         title: 'My menu',
>         myItems: [{ name: 'Hello' }, { name: 'World' }],
>       });
> ```
> 
> Am I doing it wrong?

It's not your fault, the typings of `@types/video.js` is not that complete, you can ignore the typing errors. If you are using `typescript`, you can declare the type of `options_`.
And `this.player` is a function, you can use `this.player_` or `this.player()` to retreive the player instance.

```typescript
class CustomMenuButton extends MenuButton {
    options_: any;  // for typescript
    createItems() {
        const player = this.player(); // or this.player_
    }
}
```

**Comment by gkatsev** [comment]
there is also the `options()` method, which might be available in the types.

**Comment by mister-ben** [comment]
If using typescript and there are definitions missing then an issue or PR at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/video.js would be best. This isn't maintained by Video.js.

For anything new you add to Video.js - components, plugins etc - you may need to create new definitions as with this guide https://joeflateau.net/posts/video-js-heart-typescript
