### ISSUE TITLE
HLS variant playback issue in Android 6 chrome

### ISSUE THREAD

**Issue by kharegaurav** [videojs/video.js#7281]
## Description
I am trying to play HLS playlist on Android 6 devices (Moto G2, Galaxy S5, Huawei P9 to name a few) on chrome browser and getting two different errors on devices.
1. VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)
2. VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE)

Now inspect element shows the last request to variant playlist as success with below response in all devices but fails to request any further (either the rendition manifest or chunks).

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=804932
/MADE/TheTourist/554ddeede78b6770fd5db0813fea525a/_804932_/manifest.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=593829
/MADE/TheTourist/554ddeede78b6770fd5db0813fea525a/_593829_/manifest.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1589017
/MADE/TheTourist/554ddeede78b6770fd5db0813fea525a/_1589017_/manifest.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2676159
/MADE/TheTourist/554ddeede78b6770fd5db0813fea525a/_2676159_/manifest.m3u8

URL to test
https://streaming-stg.fonestarz.com/canvasMediaPlayer_js7.html?clip=05269044.mp4&streaming=1&ext=m3u8&context=/MADE/TheTourist

In the response, content type is set to : application/vnd.apple.mpegURL

Seeing few github issue resolutions, 
I even tried setting overrideNative=true but it didn't help.
I even tried setting auto play to false but it didn't help.

Please help me and let me know if you require more logs/links for debugging.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Use any android 6 device.
2. Open Chrome and try to play URL (https://streaming-stg.fonestarz.com/canvasMediaPlayer_js7.html?clip=05269044.mp4&streaming=1&ext=m3u8&context=/MADE/TheTourist)

### Expected
Expect to see the video playing as it plays on android versions > 6 or desktop browsers

### Actual
On Moto G2, after the variant file gets served successfully, I get VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) in console log of chrome
On Huawei P9, after the variant file gets served successfully, I get VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) in console log of chrome

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Video.js 7.0.0 using VHS

#### browsers
Chrome browsers

#### OSes
Android 6

### plugins
videojs-http-streaming.js

**Comment by mister-ben** [comment]
Does it play on those devices on https://videojs-http-streaming.netlify.app/ ?

**Comment by kharegaurav** [comment]
Hello,

I have a variant manifest along with profile manifest and chunks.

1st Test: videojs player along with manifests and chunks hosted together. Below is the URL to test it. The URL does not work on the devices in question.
https://streaming-stg.fonestarz.com/test.html?source=test/bbb/master.m3u8

2nd Test: As you suggested, I tried using https://videojs-http-streaming.netlify.app/  and providing the URL of variant manifest (https://streaming-stg.fonestarz.com/test/bbb/master.m3u8)  hosted on my end. The devices were able to play.

**Comment by mister-ben** [comment]
That's using a much newer version of Video.js and VHS than you have with version 7.0.0. Try updating to the latest release (7.12.3) or prerelease (7.13.3) version.

**Comment by kharegaurav** [comment]
Hello,

The issue is resolved.

It happened due to certificate serving issue by web servers owing to the confusion of two separate signing paths, introduced by Lets Encrypt recently. Very specific to Android versions < 7.1
Refer articles
https://www.androidpolice.com/2020/11/07/many-websites-will-stop-working-on-older-android-versions-in-2021/
https://www.androidpolice.com/2020/12/21/the-internet-wont-break-on-older-android-devices-in-2021-thanks-to-certificate-authoritys-workaround/

Thanks for the time.
