### ISSUE TITLE
player.on('error') not called when streaming URL(hls) is expired in-between while playing

### ISSUE THREAD

**Issue by natheeshsunway** [videojs/video.js#7290]
## Description
player.on('error',function(e) {}) was not called when streaming hls url is expired while playing. Keep showing the buffer state.

## Steps to reproduce
1. Generate 30 seconds valid  streaming hls url.
2. Play and wait for 30 seconds to expire (We use 400 as Status code)
3. VideoJs keep showing in buffer state and dosen't call player.on('error',function(e) {}),

### Expected
Should call player.on('error',function(e) {}), it help us to regenerate valid streaming url.

### Actual
keep showing in buffer state

**Comment by gkatsev** [comment]
This is by design. We can't know whether the stream is having a hiccup and will recover or not. In the latest Video.js (7.13.3), you can set `maxPlaylistRetries` to limit how much we keep retrying playlists. See https://github.com/videojs/http-streaming#maxplaylistretries for more info.
