### ISSUE TITLE
Use 'click' insteadof 'mouseup' event to trigger tech click

### ISSUE THREAD

**Issue by Chocobozzz** [videojs/video.js#7291]
## Description

When you click somewhere on a page that includes a videojs player, and release the button in the videojs player then the video is stopped/played.

You can observe this issue on the official videojs website: https://videojs.com/city

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. go on https://videojs.com/city
2. play the video
3. click somewhere on the page, move the cursor on the player and release the button
4. the video is played again

### Expected

The video should only be played on a player click (`mousedown` **and** `mouseup` inside the player) 

### Actual

The video is played again. Seems to be related to https://github.com/videojs/video.js/blob/a221be1d832b10b80f3412aabba7d35573cd6ec4/src/js/player.js#L1325. Not sure what is the status of flash for video.js, so maybe we can use the classic behaviour now (`click` event).

#### videojs

7.12.3

#### browsers

firefox, chrome

**Comment by gkatsev** [comment]
Flash is no longer a thing. It probably makes sense to switch to click there. Care to submit a PR?
