### ISSUE TITLE
Use 'click' with fullScreenToggle

### ISSUE THREAD

**Issue by kkm** [videojs/video.js#7292]
```
  player.controlBar.fullscreenToggle.on('click', function (event) {
    var container = document.getElementById("container");
    container.requestFullscreen();
  });
```

 I am not sure, what is correctly.

**Comment by gkatsev** [comment]
You should be able to listen to the click event. What are you trying to do?

**Comment by NameKelly** [comment]
`if (this.$refs.video[index].requestFullscreen) {
              this.$refs.video[index].requestFullscreen();
            } else if (this.$refs.video[index].msRequestFullscreen) {
            this.$refs.video[index].msRequestFullscreen();
            } else if (this.$refs.video[index].oRequestFullscreen) {
              this.$refs.video[index].oRequestFullscreen();
            } else if (this.$refs.video[index].webkitRequestFullscreen) {
              this.$refs.video[index].webkitRequestFullScreen();
            }`
I failed to use this method to achieve full screen effect when it run in some Android phone. I wonder if I missed anything or I wrote the wrong method.thanks for readding.
