### ISSUE TITLE
Video cache issue

### ISSUE THREAD

**Issue by domadev812** [videojs/video.js#7301]
## Description
The internal cache should be reset whenever a new video source is loaded, otherwise its possible to read values from a previous video.

`return new HttpResult(file, videoData.Type);`

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Load video from server
2. Change video file in server
3. Load old video

### Expected
if the video file is changed in server side, the new video should be played even though it is same API endpoint.

### Actual
It plays old video.

**Comment by gkatsev** [comment]
Video.js doesn't cache anything itself. Make sure to check your cache-control headers. It could be cached at the browser or CDN level.

**Comment by domadev812** [comment]
![Screenshot 2021-07-02 045915](https://user-images.githubusercontent.com/29895368/124218552-ba776c80-dafa-11eb-97d2-53b623788ea3.png)

As you can see the cache control is set correctly.

On front-end side, I upload the video and after uploading is done, I show video-player.
When the 1st video is uploaded, it works well.
But if I upload the 2nd video, the 1st video is always played and I should clear cache and restart the app.

**Comment by gkatsev** [comment]
Consider setting max-age to zero as well. However, it looks like you're playing back an mp4, this is handled entirely by the browser, and we don't have any control over it.

**Comment by domadev812** [comment]
I see
Thanks for your support.
I will check more detail on my end.

**Comment by domadev812** [comment]
By the way there is one more thing.
When new video is uploading, I remove the video-player and add it again after uploading is finished using v-if.
But it doesn't hit the API.
I think the issue is related with this one.

**Comment by domadev812** [comment]
if I update the src manually in inspect mode and it hits the API.
