### ISSUE TITLE
Question About view counter

### ISSUE THREAD

**Issue by Vazza202** [videojs/video.js#7303]
Is there a way to add a current viewer count? Like twitch? Let me know thanks.

**Comment by markhv-code** [comment]
@Vazza202 I too would like to know? Have you found out anything? Thank you for your time!

**Comment by gkatsev** [comment]
We don't have a way to disable a view count. It's not something that Video.js could know without some kind of backend call. It isn't something that we are planning to include.

To do it yourself, you'll need to make a backend call to retrieve your view count and then create a component that will display that number inside the player or in the control bar.

**Comment by markhv-code** [comment]
@gkatsev Thank you for your help!
