### ISSUE TITLE
Playlist UI

### ISSUE THREAD

**Issue by Vazza202** [videojs/video.js#7305]
The playlist UI is not working so whoever is good with html and java, here's the site >> 

https://errorslippy.000webhostapp.com/

if i add  src="https://nmxlive.akamaized.net/hls/live/529965/Live_1/index.m3u8" inside the video tag, it works with the Livestream... but for the playlist ui, it will not play for some reason, like even if i use mp4 format of file on the playlist it still will not play. I been on this for months now and just can't figure it out. I know it's something simple I'm missing but it's always the simple things that get me.

If you know how to fix it... please let me know.

**Comment by mister-ben** [comment]
The playlist functionality you are using is form the "nuevo" plugin. It'd be better to ask for help from that plugin's developers - it is not maintained by the Video.js team.

**Comment by Vazza202** [comment]
> The playlist functionality you are using is form the "nuevo" plugin. It'd be better to ask for help from that plugin's developers - it is not maintained by the Video.js team.

I been there and done that. No reply. It was working a year ago idk if something changed in the browser or in the code somewhere... it's something very small though. it just wont play the playlist is all it plays everything else.
