### ISSUE TITLE
No audio tracks without experimental web platform features

### ISSUE THREAD

**Issue by mguiking** [videojs/video.js#7306]
## Description
I want to play audio only, from an mp4 file, since the video is processed and shown in a canvas. Not all mp4 files have audio so I want to hide the (custom made) audio controls when there is no audio. audioTracks() seems to be the right way to detect audio. But this works only when I enable experimental features, with `chrome://flags/#enable-experimental-web-platform-features`

The audio plays fine either way. How can this behavior be explained? And what is the correct way to detect audio?

## Steps to reproduce
Try this example with and without the feature flags and watch the console to see the audio tracks.
https://codepen.io/mguiking/pen/NWjxREE

### Expected
Audio tracks whenever there is audio.

### Actual
No audio tracks are detected.

#### videojs
7.13.3
#### browsers
Firefox and Chrome. Chrome with experimental web platform features does work.
#### OSes
Linux, didn't try any other

**Comment by gkatsev** [comment]
Unfortunately, in Chrome, there isn't a good way to know whether the mp4 has audio tracks enabled or not. Chrome is working on audio tracks support, but it isn't available yet, as you noticed.

**Comment by mister-ben** [comment]
There's `webkitAudioDecodedByteCount` on the video el, although that won't populate until the video has stated playing.

**Comment by mguiking** [comment]
> Unfortunately, in Chrome, there isn't a good way to know whether the mp4 has audio tracks enabled or not. Chrome is working on audio tracks support, but it isn't available yet, as you noticed.

Thanks for helping out, good to know they are indeed still working on audio track support.

**Comment by mguiking** [comment]
> There's `webkitAudioDecodedByteCount` on the video el, although that won't populate until the video has stated playing.

Thanks, I thought this was deprecated, but it works on Chrome. It didn't get it working on Firefox though. Hopefully audio tracks will be supported on Chrome, Firefox and Safari soon. In the meantime I'll try to find browser specific solutions, and show the controls regardless :-)

**Comment by gkatsev** [comment]
Yeah, unfortunately, it's only available in Chrome (and maybe Safari too). Not seeing anything similar in Firefox.

**Comment by mister-ben** [comment]
It has`mozHasAudio`, but it's also deprecated
