### ISSUE TITLE
What is the minimum Chrome version of the supported browser?

### ISSUE THREAD

**Issue by zhangxue61** [videojs/video.js#7307]
## Description
What is the minimum Chrome version of the supported browser?
chrome 53.0.2785.134。support?
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

#### videojs
7.12.3
#### browsers
chrome 53.0.2785.134
#### OSes
Android TV box

**Comment by gkatsev** [comment]
Practically, latest and 2 versions back, but we don't generally remove support for older browsers outside a major version. However, soft breakages can happen. I know that at some point Chrome switched from PTS to DTS handles and so things like HLS broke with Video.js 7.10, I believe. You can force native HLS playback with [`overrideNative: false`](https://github.com/videojs/http-streaming#overridenative), which is the default. MP4 playback should definitely continue working with that version of chrome.

**Comment by phloxic** [comment]
@gkatsev - isn't the default for overrideNative `true` (except for Mac OS Safari and iOS) since quite a while?

**Comment by gkatsev** [comment]
The default was changed in VHS 2, which was included in Video.js 7.10.

**Comment by phloxic** [comment]
Sure, in the light of that

> You can force native HLS playback with overrideNative: false, which is the default.

had a ring of `false` being the default. np

**Comment by gkatsev** [comment]
Oh, sorry, I must've miswrote or didn't complete my thought. The current default is `overrideNative` but on older chrome you likely want to turn it off.

**Comment by gkatsev** [comment]
Also, I guess the question is also whether you're playing back HLS or DASH or an mp4. For an mp4, it shouldn't be an issue. For HLS, you likely want to turn off overrideNative and rely on the native HLS support. For DASH, I'm not sure there's anything easily doable, since I don't think Android supports DASH directly.

**Comment by decision4fr** [comment]
![image](https://user-images.githubusercontent.com/48681930/128119193-b4c3ca22-77a0-41ed-b2ab-0e970b4e6ebb.png)
It cannot be played in 69.0.3497.0, and an error is reported
