### ISSUE TITLE
HLS not supported in Android

### ISSUE THREAD

**Issue by ka28740093** [videojs/video.js#7309]
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Here is my test video: [link](https://static.hhask1.com/177df6bc-083b-494d-8718-c3174f106676/hls/dce7f4f437b51e41625a283c3f7d2ed8.m3u8)
2. I've tested it [here](https://videojs-http-streaming.netlify.app/), and it works, and it works fine at my own code too.
3. But when I tried to test it at Android 7.0, It's not working any more.
4. So I use _chrome://inspect_ to get debug info.
5. VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

### Expected
Works fine.

### Actual
Not work.

### Error output
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
The latest 7
#### browsers
The default browser (chrome) in android 7.0/6.0
#### OSes
android
### plugins
none.

**Comment by mister-ben** [comment]
Which _exact_ version of Video.js 7 are you using? Earlier minor versions of 7 defaulted to any browser's native HLS playback, but Android's native HLS isn't good. Later versions will override and play with our playback engine.

**Comment by gkatsev** [comment]
Also, could be related to https://github.com/videojs/video.js/issues/7297

**Comment by ka28740093** [comment]
> Which _exact_ version of Video.js 7 are you using? Earlier minor versions of 7 defaulted to any browser's native HLS playback, but Android's native HLS isn't good. Later versions will override and play with our playback engine.

"video.js": "^7.11.8"

**Comment by mister-ben** [comment]
The stream plays on Andorid 6 and 7 devices on Browserstack with 7.11.8 and 7.14.0. Try to put together a reduced test case that reproduces your issue.

**Comment by ka28740093** [comment]
> The stream plays on Andorid 6 and 7 devices on Browserstack with 7.11.8 and 7.14.0. Try to put together a reduced test case that reproduces your issue.

I’ve tried [this test site](https://videojs-http-streaming.netlify.app/) on android 6/7, neither the default stream nor my own steam works.

**Comment by gkatsev** [comment]
Are you running Chrome? What version of Chrome is it?

**Comment by ka28740093** [comment]
> Are you running Chrome? What version of Chrome is it?

I try to create `Pixel 3 API 24(Android 7.0)` AVD in AndroidStudio. The browser is chrome, but not works.

**Comment by mister-ben** [comment]
Emulators aren't always the best way to test video, but the likely problem here is that if you create an AVD in Android Studio it will start with a very old version of Chrome, whatever was current when Android 7 was released. That's not representative of what users would have in the wild. Check the **Chrome version** and try updating it.

**Comment by gitamj** [comment]
I opened bug #7297. Our users on real Android devices are reporting this bug.

**Comment by ka28740093** [comment]
> Emulators aren't always the best way to test video, but the likely problem here is that if you create an AVD in Android Studio it will start with a very old version of Chrome, whatever was current when Android 7 was released. That's not representative of what users would have in the wild. Check the **Chrome version** and try updating it.

I've tried on real Android devices too, not only AVD

**Comment by gkatsev** [comment]
We'll be taking a look at these. If you have other sources you're able to share that you can see don't work on android but are working in desktop Chrome, please share them.

**Comment by ka28740093** [comment]
> We'll be taking a look at these. If you have other sources you're able to share that you can see don't work on android but are working in desktop Chrome, please share them.

you can just check the default source from this test site [https://videojs-http-streaming.netlify.app/](https://videojs-http-streaming.netlify.app/)

**Comment by gkatsev** [comment]
well, hopefully, it'll be fixed as part of https://github.com/videojs/mux.js/pull/393

**Comment by gkatsev** [comment]
We just released Video.js 7.14.1 with some fixes, can you try it out please?

**Comment by ka28740093** [comment]
> We just released Video.js 7.14.1 with some fixes, can you try it out please?

well, I've tried, but not works.
