### ISSUE TITLE
After version 7.11.1 (included) on('loadedmetadata') is not being triggered

### ISSUE THREAD

**Issue by gabycperezdias** [videojs/video.js#7315]
Same code works before 7.11.1 and breaks after.

```
videojs(video, this.props, function onPlayerReady() {
  player.on('loadedmetadata', function() {
    ...
  });
}
```

**Comment by gkatsev** [comment]
I've seen it working for sure. Are you able to share a live example where it isn't working? Also, what browser/OS are you seeing it with?

**Comment by gabycperezdias** [comment]
Hummm

I managed to find out why it is not triggering, I have a Custom PlayButton and apparently this is breaking on this line and therefore doesn't trigger the loadedmetadata

`var validateTarget = function validateTarget(target) {
  if (!target.nodeName && !isEvented(target)) {
    throw new Error('Invalid target; must be a DOM node or evented object.');
  }
};`
this is my custom button
```
videojs.registerComponent('PlayPauseAnimation', PlayPauseAnimation);
const playPauseAnimationContainer = player.addChild('PlayPauseAnimation');
playPauseAnimationContainer.on('click', () => {
if(player.paused()) {
  player.play();
} else {
  player.pause();
 }
});
```

**Comment by FredZeng** [comment]
Can you show more details of your Custom PlayButton? Or create a [reduced test case](https://css-tricks.com/reduced-test-cases/) follow the [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

**Comment by gabycperezdias** [comment]
It is very simple:

I declare it like this:
````
// Get the Component base class from Video.js
const Component = videojs.getComponent('Component');
export class PlayPauseAnimation extends Component {
  public constructor(player, options) {
    super(options);
  }

  public createEl() {
    return super.createEl('div', {
      className: 'vjs-play-pause-animation'
    });
  }
}
````

and then, use it like this:

````
import { PlayPauseAnimation } from './helper';

this.player = videojs(video, this.props, function onPlayerReady() {
    videojs.registerComponent('PlayPauseAnimation', PlayPauseAnimation);
    const playPauseAnimationContainer = player.addChild('PlayPauseAnimation');
        playPauseAnimationContainer.on('click', () => {
            if(player.paused()) {
                player.play();
            } else {
                player.pause();
            }
        });
});
````

**Comment by gkatsev** [comment]
Thanks, I can reproduce locally. Definitely doesn't seem right that it fails there. I'll take a look.

**Comment by gkatsev** [comment]
Ah, figured out why. When you call super in the constructor, you're only passing through `options`, but you need to pass the player as well.
```
  public constructor(player, options) {
    super(player, options);
  }
```

**Comment by gabycperezdias** [comment]
OMG

Thank you SO much, worked perfectly... sorry about that

**Comment by gkatsev** [comment]
Haha, no worries. It's the little things that are easy to overlook!
