### ISSUE TITLE
Videos play but have no audio in IE11

### ISSUE THREAD

**Issue by MarkDonatelli** [videojs/video.js#7317]
## Description
I am building a nuxt app with brightcove player loader. I have used this setup on a few other projects and it usually works perfectly. However I have run into an issue with IE11. The videos all play but there is NO AUDIO. I'm having a hard tie debugging this and finding the cause of this.

## Steps to reproduce
1. Play any video
2. video plays fine
3. no audio

### Expected

videos play with audio

### Error output
There are zero errors in the console when trying to play videos. However I do get this VIDEOJS warning which I have never seen before

VIDEOJS: WARN: Invalid playlist STREAM-INF detected. Missing BANDWITH attribute

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
IE11

what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

https://github.com/brightcove/player-loader

**Comment by gkatsev** [comment]
If you're seeing that error, you should fix your manifest to include BANDWIDTH attributes on the various rendition playlists.
Afterwards, if you're able to share your stream, we could potentially take a look.

If you're a Brightcove customer, consider opening a ticket with their support instead.
