### ISSUE TITLE
To make 4 separate mp4s look like one continuous video?

### ISSUE THREAD

**Issue by arpitchannawar** [videojs/video.js#7323]
Is there any way to do? If yes then can you please suggest me how we can achieve this.

**Comment by sghosh1810** [comment]
Are these files in any sequence like file 1 then 2 and 3 and so on? Or a bit from 1 then 2 then 1 again then 3 like this?

**Comment by arpitchannawar** [comment]
Yes all files are bit from 1 then 2 then 1 again then 3

**Comment by arpitchannawar** [comment]
Hi, is there any update how we can achieve above screens?

**Comment by gkatsev** [comment]
Are you trying to do this in the client? You can try setting up a playlist of your 4 videos using videojs-playlist and to merge it into a single timeline, you could use [middleware](https://docs.videojs.com/tutorial-middleware.html). However, transitioning between videos won't be seamless.
If at all possible, I would recommend re-encoding your video into something like HLS instead.

**Comment by arpitchannawar** [comment]
Yes, I want to implement for my client, but previously I have done below player 
![image](https://user-images.githubusercontent.com/83327434/126189872-994173b0-5b6a-4746-9288-d0e8863f5d75.png)

But can we achieve same design pattern in existing one.

**Comment by gkatsev** [comment]
You can probably do something using middleware as mentioned above. You might be able to do it using MSE too, but that would likely be a lot more work as we don't expose MSE directly.
I would still highly recommend not trying to do this client-side.

**Comment by arpitchannawar** [comment]
So its means whatever we have player currently the one we can't customize with new one which we have shared .

**Comment by gkatsev** [comment]
You can but it would likely be more work.

**Comment by arpitchannawar** [comment]
Also we need to upgrade the plugin or we need to provide any option about this view. videojs-playlist and  merged thats why its showing all sequence video. But I want customize player look like new one.

**Comment by arpitchannawar** [comment]
Okay for now, we can scratch the titles. The progress bar can be unique to each video.

![image](https://user-images.githubusercontent.com/83327434/126199941-b3aa08a8-2bce-4080-8c02-2d9f07094c6f.png)

But the menu at the top should still work.

**Comment by gkatsev** [comment]
You can use https://github.com/brightcove/videojs-playlist-ui and then customize its UI to match your design
