### ISSUE TITLE
BUG: player with HLS doesn't work correctly. Makes Infinite requests.

### ISSUE THREAD

**Issue by nsurghy** [videojs/video.js#7325]
## Description
Hi everybody. I have a problem with the player that I can't solve. I have seen before in this forum that others have had the same problem, however I haven't found a concrete solution.
I am working with Angular 12, running the player in Chrome v91, and with the latest version of video.js. For the player I use an HLS stream. At the beginning, this seems to work correctly, however sometimes (not always), when I change the audio track or the subtitles from the player, or when I set the player to full screen, it starts to make infinite requests, which are canceled, and, obviously, the player stops working. The infinite requests only stop when reloading the page.
I have tested the same stream with other libraries, even with hls.js, and it works perfectly. In turn, I have tested video.js with mp4 streams, and it works too. Hope we can find a solution.
I leave my code so you can read it:

import { Component, OnDestroy, OnInit, ViewEncapsulation } from '@angular/core';
import videojs, { VideoJsPlayerOptions } from 'video.js';

@Component({
  selector: 'app-video-player',
  template: `
  <video id="target" width="640" height="264" preload="auto" class="video-js vjs-big-play-centered vjs-fluid vjs-live" controls data-setup="{}"></video>
  `,
  styleUrls: ['./video-player.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class VideoPlayerComponent  implements OnDestroy, OnInit {
  videoLink= 'Url Of My Stream.;
  options: VideoJsPlayerOptions;
  player: any;
  constructor() {
    this.options = {
      autoplay: true,
      sources: [{
          src: this.videoLink,
          type: "application/x-mpegURL",
      }],
    };
  }

  ngOnInit(){
      let target = document.getElementById('target');
      if (target !== null){
        this.player = videojs(target, this.options, function onPlayerReady() {
          console.log('onPlayerReady', this);
        });
      }
  }

  ngOnDestroy() {
    // destroy player
    if (this.player) {
      this.player.dispose();
    }
  }
}

Thank you very much for your attention, I await your response.
 - Nicolás Surghy.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Run the code.
2. Start watching (it seems perfectly).
3. Change something in the player (audio, subtitles, full screen).

## Results
Infinite requests. Player stops working.

### Expected
Player working properly.

### Actual
Player not working.

### Error output
(254) XHR failed loading: GET "<URL>".
33-05000.ts (cancelled)

## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
chrome version 91.0.4472.164 (Official Build) (64-bit)

**Comment by gkatsev** [comment]
Are you able to provide a live minimal example? Try codesandbox.io for making the example. Unfortunately, without a stream, we can't help much.

**Comment by Enoooch** [comment]
https://codesandbox.io/s/spring-resonance-r8wol?file=/index.html
