### ISSUE TITLE
!HLS broken on all new safari versions! ( high impact this goes for all videoJS users ) 

### ISSUE THREAD

**Issue by onair-lena** [videojs/video.js#7326]
## Description
HLS streaming stopped working on IOS safari and safari on mac. 

During the last week we noticed issues with playing HLS streams on safari ( both IOS and desktop versions) After a big troubleshoot we found that not only our player is working but non of the HLS examples are working either. It looks like none of the demo HLS implementations are working anymore when using later safari versions. 

For example: 
[https://videojs.github.io/videojs-contrib-hls/ ](https://videojs.github.io/videojs-contrib-hls/ ) and 
[https://www.nuevodevel.com/nuevo/showcase/hls](https://www.nuevodevel.com/nuevo/showcase/hls)
Works on chrome etc.... does not work in safari anymore.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. go to https://videojs.github.io/videojs-contrib-hls/ or https://www.nuevodevel.com/nuevo/showcase/hls with safari big sur, catalina, or a latest IOS version
2. Press play
3. put your popcorn ad cola back where it came from, it will not play with a bug "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

### Expected
The video,  popcorn and cola

### Actual
Threw bug "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."

### Error output
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

## Additional Information
We have tested with multiple streams that do work in other players. this seems to be safari specific and very recent
#### videojs 
what version of videojs does this occur with?
( Latest 4 versions minimal) 
#### browsers
what browser are affected?
Safari on Big sur, catalina
safari on IOS latest version
safari on an old Iphone 6 does work 
#### OSes
what platforms (operating systems and devices) are affected?
All latest apple devices ( above iphone 6) 
Big sur
Catalina

### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-landscape-fullscreen

**Comment by sanderkooger** [comment]
All, I tested and verified none of the HLS implementations work on safari. 

The only solution i see for now is temporarily implementing another player so that clients can still be served. 

List of dead players
https://github.com/videojs/video.js/issues/7326
https://openidconnectweb.azurewebsites.net/VideojsHls.html
https://codepen.io/melina34/pen/eeMgBB
https://codepen.io/ewrewr/pen/eeLKbK

I also noticed JW players HLS implementation has broken too 
https://developer-tools.jwplayer.com/stream-tester/

It looks like Apple broke the internet once again :(

**Comment by sanderkooger** [comment]
@gkatsev Do you by any chance have an idea on this issue?

**Comment by onair-lena** [comment]
I have been looking further, but have not been able to find a solution. I did notice that even the videoJS demo does not load on safari either https://videojs.com/advanced/?video=big-buck-bunny

**Comment by mister-ben** [comment]
Two of these (https://openidconnectweb.azurewebsites.net/VideojsHls.html and https://codepen.io/melina34/pen/eeMgBB) won't play on any browser as DNS lookup fails for the domains in the video sources. The server for the media in https://codepen.io/ewrewr/pen/eeLKbK doesn't respond. The others play normally on Safari.

I can't tell what problem you're seeing, but it's more limited in scope than all playback broken on all Safari. Safari is native HLS playback which unfortunately doesn't give much insight into what's happening during playback. The network and console tabs in dev tools might have more information.

**Comment by sanderkooger** [comment]
hey @mister-ben 

The sources we checked play in chrome on mac, but not in IOS ( iphone 10 > and safari on catalina and higer I did test on my old iphone 6 that works)

One of the examples is this one [https://videojs.com/advanced/?video=big-buck-bunny](https://videojs.com/advanced/?video=big-buck-bunny) 

We also noticed a lot of other players ( Shaka JW) display the same behaviour. 

As of network, players all start caching.

**Comment by sanderkooger** [comment]
So we just tested the [https://openidconnectweb.azurewebsites.net/VideojsHls.html](https://openidconnectweb.azurewebsites.net/VideojsHls.html ) page with http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8 as source, verified it was working first on chrome. 

works in chrome not in safari

We have also been testing codepens, we found a working implementation with version 7.7.5 but all versions after fail.

**Comment by onair-lena** [comment]
In attempts to find any solution to the issue i found the only one working example of HLS implementations  that works on safari. This one - https://codesandbox.io/s/v61w1. But in the example version of a player is 7.7.5. If upgrade it to the latest one video doesn`t play and I see the error.

Also tried to downgrade videoJS in my implementation (made a codesandbox with example  - https://codesandbox.io/s/videojs-hls-test-forked-di3zb), but that doesn`t work for me.

**Comment by brandonocasey** [comment]
Using the latest demo https://v7-14-1--videojs-preview.netlify.app/sandbox/index.html and manually setting the source in the console to `player.src({src: 'http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8', type: 'application/x-mpegurl'});` appears to playback in safari.

**Comment by mister-ben** [comment]
I can reproduce playback not starting on Safari on https://codesandbox.io/s/videojs-hls-test-forked-di3zb

The empty track element (in src/components/Video.js) seems to be the problem. Remove that and it plays - https://zot5s.csb.app

Video.js will handle adding tracks to the video if needed, there's no reason to have that element there.

**Comment by sanderkooger** [comment]
Thanks MR ben that solved it for me and for @onair-lena !!! ur a rockstar!

**Comment by jf20201225** [comment]
How was the issue resolved?  

I have found my hls livestreams on safari on ios iphone fail to play, endless gray circle, on iphone 12 pro max - ios of 15.3.1 while Iphone 7 plus on 13.6.1 played them flawlessly.

@onair-lena and @sanderkooger  - any advice you have would be greatly appreciated.
