### ISSUE TITLE
How to load Video.js to display soft subtitles for local videos

### ISSUE THREAD

**Issue by alphabiz-se2** [videojs/video.js#7331]
How to load Video.js to display soft subtitles for local videos

**Comment by FredZeng** [comment]
```html
<video id="mainvideo" controls autoplay loop>
  <track src="en_track.vtt" srclang="en" label="English" kind="caption" default>
</video>
```

**Comment by alphabiz-se2** [comment]
@FredZeng Only one video file, no subtitle file, the subtitle file is hidden in the video

**Comment by gkatsev** [comment]
Unfortunately, that isn't available. Your best bet is to use something ccextractor to get the internal captions and output a vtt file you can load like @FredZeng mentioned.
