### ISSUE TITLE
Not receiving bluetooth-mic audio with onscreen-media audio

### ISSUE THREAD

**Issue by richard-dch** [videojs/video.js#7332]
## Description
I have built an angular screen-sharing web-app, using the video-js library, I have used the video-js angular installation documentation (**[link here](https://collab-project.github.io/videojs-record/#/frameworks/angular)**) for implementing this. Below is my configuration within the constructor of my typescript file:

```
this.config = {
            controls: true,
            autoplay: false,
            fluid: false,
            loop: false,
            width: 320,
            height: 240,
            bigPlayButton: false,
            controlBar: {
                volumePanel: false,
            },
            plugins: {
                // configure videojs-record plugin
                record: {
                    screen: true,
                    video: false,
                    audio: true,
                    debug: true,
                    maxLength: 60,
                    videoMimeType: 'video/webm;codecs=H264',
                },
            },
        };
```
In addition to screen-sharing, as you may notice from my configuration settings, I am also allowing for recording of the screen-share (`screen: true`).

When the browser modal, for selecting the tab to screen-share, opens I am not able to see the **Share Audio** checkbox when selecting the specific tab I want to screen-share.

![image](https://user-images.githubusercontent.com/70823153/126306172-730ab28f-eb63-41a7-ad4b-571de9b26483.png)

The below image is a what I want to achieve, a browser modal which shows this checkbox:

![image](https://user-images.githubusercontent.com/70823153/126306244-be7eb78c-f021-4d1f-ac96-c3dea78b92ec.png)

For clarity, my main objective here (in the saved recording) is to receive both microphone-audio from my **bluetooth headset**, and also the media-audio playing on the selected tab. This is currently separated by the checkbox being selected or not. If the **Share Audio** checkbox is **checked**, you receive on-screen media audio without **bluetooth-microphone audio**, and keeping this checkbox **unchecked** does the direct opposite.

So to tie it all back, if I am able to view this checkbox, have it **checked**, and find a means of **recording bluetooth-microphone audio** separately to merge into one saved video at the end, in theory I should be achieving what I am looking for. 

However if this is not the right approach, please provide me all the criticism and information, as there is little to no information on any of the topics described in this issue, online.

Heres my codepen **[reduced test case](https://codepen.io/richard-dch/pen/BaRdKOB)**, please note however, theres seems to be a conflict with running this on codepen since my typescript is configured for angular. I have this angular project in a **github public repo**, where you can directly clone **[here](https://github.com/richard-dch/video-js-recorder.git)**

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Clone repository **[here](https://github.com/richard-dch/video-js-recorder.git)**
2. Run these two commands in terminal to run the project: `npm install` -> `ng serve`
3. Open the running project in `localhost:4200` on your browser, and immediately you can use the features described above, there is no more navigating required. 

**(NOTE: my issue is specifically related to bluetooth headphones, other means of receiving microphone audio do not necessarily have the same problem)**

### Expected
Expected to see a **Share audio** checkbox within the share-screen modal in the browser

### Actual
The **Share audio** checkbox was not visible

### Error output
No errors, but important to understand. Since the Share audio checkbox is not visible, it may be equivalent to being unchecked, and thus in the saved video I am **not** receiving the **on-screen media audio** whilst **receiving** microphone- audio from my bluetooth headset.

## Additional Information
The only installations made in the project were through the command provided in the video-js angular installation documentation:
- `npm install --save videojs-record @types/video.js`

which installs video-js, video-js-record and RecordRTC

**Comment by gkatsev** [comment]
We don't handle anything around this recording functionality, you probably want to re-open this issue against [videojs-record](https://github.com/collab-project/videojs-record)
