### ISSUE TITLE
Videojs with bootstrap fullscreen modal popup is losing background color on fullscreen

### ISSUE THREAD

**Issue by Anil-matcha** [videojs/video.js#7335]
## Description
Bootstrap class modal-backdrop-fullscreen has black shaded background which is working without fullscreen but on fullscreen the background is gone

<img width="920" alt="normal" src="https://user-images.githubusercontent.com/4326215/126634840-66998f07-cd49-48c1-94f4-c3f62d77edb3.png">
<img width="960" alt="fullscreen_popup" src="https://user-images.githubusercontent.com/4326215/126634860-b0606d2e-370d-4563-a103-ecf33961372d.png">

These are 2 images showing the behavior of popup without and with fullscreen. As can be seen without fullscreen there is a black shaded background to popup which disappears on fullscreen

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Go to https://dev.vadoo.tv/landing_page?vid=3twAi1sXKOGvHS9H4aWYySBgC9NOtuUz
2. Play the video till 5 seconds with and without fullscreen to observe the difference, use skip to prevent entering any details

### Expected
Same UI is expected with and without fullscreen i.e having the dark shaded background

### Actual
Background is removed on fullscreen

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?  
7.12.1 but occurs with other versions as well
#### browsers
what browser are affected?
All browsers
#### OSes
what platforms (operating systems and devices) are affected?
All device

**Comment by FredZeng** [comment]
You should notice that video.js use `Element.requestFullscreen()` method to make the element be displayed in full-screen mode. It means anything you want to show in full-screen mode should be placed inside the videojs div container.
![image](https://user-images.githubusercontent.com/17154608/126730107-e380753a-1b26-4c81-828d-9be9f9eaae1f.png)
In your demo, the bootstrap mask is outside the videojs container, while the modal is inside. When I place the mask inside the container, everything works well for me.

**Comment by Anil-matcha** [comment]
Thanks a lot @FredZeng , the suggestion works great !!!

I am closing this issue now
