### ISSUE TITLE
How to display soft subtitles

### ISSUE THREAD

**Issue by alphabiz-se2** [videojs/video.js#7338]
How to display soft subtitles

**Comment by FredZeng** [comment]
```html
<video id="mainvideo" controls autoplay loop>
  <track src="en_track.vtt" srclang="en" label="English" kind="caption" default>
</video>
```

**Comment by alphabiz-se2** [comment]
> How to display soft subtitles

a

**Comment by gkatsev** [comment]
Duplicate of #7331. Please try and not open the same issue multiple times. It may take several days before we're able to reply, please be patient. Thanks.
