### ISSUE TITLE
Looks like accessing to player duration inside a "player.ready()" in VueJs returns NaN!

### ISSUE THREAD

**Issue by Sphirye** [videojs/video.js#7339]
I'm doing a couple of tests to visually customize a player control panel, but looks like that accessing the current video duration inside a ```player.ready()``` callback returns NaN.

This is how i am instantiating VideoJsComponent (i'm using Typescript btw):

```ts
export default class VideoJs extends Vue {
  options = {
    autoplay: true,
    muted: true,
    controls: true,
    sources: [{
      type: "video/mp4",
      src: "../assets/somevideo.mp4"
    }]
  }
  
  player: VideoJsPlayer | null = null

  setPlayer() {
    this.player = videojs("videoPlayer", this.options)
    this.player!.ready(() => { console.log(this.player!.duration()) }) //This returns NaN
  }

  mounted() {
    this.setPlayer()
  }
}
```
I think its important to detail that this occurs only when I try to access ```duration()``` in this way.

Spoiler: I want to manipulate my VideoJs current time position through a external basic range input, thats why i need to access it as soon as the VideoJs instance starts.

I'm not sure if I'm forgetting to do something important, or if this is normal in VideoJs, as i'm seeing people with this problem before (unlike me, they were not using VueJs, reactivity may have something to do with it, but i'm just digressing).

**Comment by gkatsev** [comment]
That's expected. If there isn't any media yet, it returns NaN for the duration as per the HTML spec: https://html.spec.whatwg.org/multipage/media.html#dom-media-duration
You likely want to listen to `durationchange` in there which will trigger when the duration changes.

**Comment by Sphirye** [comment]
```durationchange``` didn't worked, but i noticed that vue (decorators) support the event ``` onLoadedMetadata```, after using them now it's working correctly.

Thanks for the help anyway! Here i'm leaving what i did.

```html
<!--Component template-->
<template>
  <v-container>
    <v-row align="center" justify="center">
      <v-col cols="6">
        <video id="videoPlayer" @loadedmetadata="log(player.duration())" class="video-js">
        </video>
      </v-col>
    </v-row>
  </v-container>
</template>
```


Component script:
```ts
/* Component script */
export default class VideoJs extends Vue {

  options = {
    preload: "auto",
    autoplay: true,
    muted: true,
    controls: true,
    sources: [{
      type: "video/mp4",
      src: "../assets/beat_drop.mp4"
    }]
  }
  
  player: VideoJsPlayer | null = null

  setPlayer() {
    this.player = videojs("videoPlayer", this.options)
  }
  
  //Called on loadedMetaData event.
  log(v: any) {
   console.log(v)
  }

  mounted() {
    this.setPlayer()
  }
}
```

Greetings. :)
