### ISSUE TITLE
Time tooltip not displaying correctly

### ISSUE THREAD

**Issue by manhtqb** [videojs/video.js#7342]
## Description
I am implementing videojs with vuejs, everything is fine until i play the video. Time tooltip on hover is not displaying correctly. 

### Expected
![image](https://user-images.githubusercontent.com/17952579/126862639-2e7f6304-6a1c-4e0c-9770-3d777dbb0f71.png)

### Actual
![image](https://user-images.githubusercontent.com/17952579/126862554-b25b3782-8579-4afa-b45c-f1cc530a0efc.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
6.6.0
#### browsers
Edge, Chrome
#### OSes
Window

**Comment by gkatsev** [comment]
Video.js 6.6.0, do you still see this issue with a recent version? For example 7.14.3?

**Comment by manhtqb** [comment]
> Video.js 6.6.0 is really old, do you still see this issue with a recent version? For example 7.14.3?

Very sorry, the problem was caused by conflict with my project's css, no problem with the library at all.
