### ISSUE TITLE
Correct use of breakpoints

### ISSUE THREAD

**Issue by bagaweb** [videojs/video.js#7343]
Hello I'm looking for the correct code to load different qualities of the same video, for example something like this:

```<video class="video-js" autoplay loop muted playsinline>
<source src="960x540.mp4" type="video/mp4">
<source src="1280x720.mp4" type="video/mp4" media="only screen and (min-width: 640px)">
<source src="1920x1080.mp4" type="video/mp4" media="only screen and (min-width: 1280px)">
</video>```

960x540.mp4 should load only on screens smaller than 640px;
1280x720.mp4 should load only on screens larger than 640px and smaller than 1280px;
1920x1080.mp4 should load only on screens larger than 1280px.

Is there a way to achieve that?

I had a look at this documentation https://docs.videojs.com/tutorial-layout.html#responsive-mode, not really sure that's what I'm looking for.

**Comment by mister-ben** [comment]
Responsive mode is about the layout of the controls.

Providing different sized sources on breakpoints isn't the best way to go about this. If you use an HLS source, the appropriate rendition based on player size and available bandwidth will be used automatically and when these factors change during playback, the transition is automatic and smooth.

**Comment by bagaweb** [comment]
Thanks for getting back @mister-ben!
I converted my mp4 files to HLS, I have now these files:

960x540.ts
960x540.m3u8
1280x720.ts
1280x720.m3u8
1920x1080.ts
1920x1080.m3u8

What should I do next? What is the best practice?

**Comment by bagaweb** [comment]
Any help?

**Comment by gkatsev** [comment]
You'd want a main manifest that contains the media playlists, which are the individual renditions.
HLS isn't really a one-to-one mapping between mp4 and ts. Ideally, you can use ffmpeg or another tool to take the highest rendition you have and generate *segmented* HLS across the various renditions that you'd like to have. Here's a tutorial on that https://docs.peer5.com/guides/production-ready-hls-vod/

**Comment by bagaweb** [comment]
Thanks a lot @gkatsev!
After creating these files what's the correct way?

<video class="video-js" autoplay loop muted playsinline>
<source src="playlist.m3u8" type="application/x-mpegURL">
</video>

will this work?

**Comment by gkatsev** [comment]
yup

**Comment by bagaweb** [comment]
Excellent thanks :)
