### ISSUE TITLE
m3u8 视频播放过程卡住 Video.js 6.2.0

### ISSUE THREAD

**Issue by fuguiguang001** [videojs/video.js#7345]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.m3u8 ts是加密过的
2.解密后可以正常播放
3.播放大概20分钟左右画面卡住，声音也卡住了

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
6.2.0 is very old. Does your source play at https://videojs-http-streaming.netlify.app ?
