### ISSUE TITLE
Modal dialog `select` text invisible with certain CSS resets applied

### ISSUE THREAD

**Issue by rossng** [videojs/video.js#7346]
## Description

If `select` is set to `color: inherit;` by a CSS reset, dropdown text is invisible in modal dialogs.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Embed videojs in an application that uses a CSS reset that sets `select {color:inherit;}`. I was using Chakra UI https://github.com/chakra-ui/chakra-ui/blob/752910bb1f4604213134fc8ea9f547bccd6a2f09/packages/css-reset/src/css-reset.tsx#L250
2. Open the captions settings dialog

### Expected

Text should be visible.

### Actual
Please describe what actually happened.

video.js theme sets the `color` to white inside the player (since most text in the player UI is on a dark background). However, the background in a `select` (and possibly other form elements - I haven't tried) is white. Due to the reset, the color is inherited as white. The result:

![image](https://user-images.githubusercontent.com/565371/126986634-429e95c5-f4b4-44b0-916a-d2bb8ef857e2.png)

Perhaps the solution is for videojs to explicitly set the color of these elements inside the modal dialog? Short of becoming a web component, I don't see another easy solution 🙂

### Error output

N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with? 

7.13.3
#### browsers
what browser are affected? 

N/A
#### OSes
what platforms (operating systems and devices) are affected? 

N/A
### plugins
are any videojs plugins being used on the page? If so, please list them below. 

N/A

**Comment by gkatsev** [comment]
Yeah, this happens every so often, and we apply some kind of work around like #4859. We've had an old issue to figure out how to handle this completely (#1880) but it's complicated and hasn't happened yet.

I think the workaround for us is to set `color: initial` on select in here
https://github.com/videojs/video.js/blob/ef1fce68225194d1eb37d11f97862f3fb5082f37/src/css/components/_captions-settings.scss#L56-L59 and here
https://github.com/videojs/video.js/blob/ef1fce68225194d1eb37d11f97862f3fb5082f37/src/css/components/_captions-settings.scss#L71-L74

Care to submit a PR?
