### ISSUE TITLE
inspect the console isssues

### ISSUE THREAD

**Issue by sudhir2** [videojs/video.js#7353]
[webtv.nettv.com.np-1627617325151.log](https://github.com/videojs/video.js/files/6904984/webtv.nettv.com.np-1627617325151.log)
[webtv.nettv.com.np-1627617320052.log](https://github.com/videojs/video.js/files/6904985/webtv.nettv.com.np-1627617320052.log)
[webtv.nettv.com.np-1627617313298.log](https://github.com/videojs/video.js/files/6904986/webtv.nettv.com.np-1627617313298.log)
[webtv.nettv.com.np-1627617303935.log](https://github.com/videojs/video.js/files/6904987/webtv.nettv.com.np-1627617303935.log)
[webtv.nettv.com.np-1627617266376.log](https://github.com/videojs/video.js/files/6904988/webtv.nettv.com.np-1627617266376.log)

**Comment by gkatsev** [comment]
Sorry, there isn't really anything actionable there. If you're able to provide a live minimal test case, we'll be happy to take a look.
