### ISSUE TITLE
HLS trackingThreshold to hide progress bar not honored in iPhone player

### ISSUE THREAD

**Issue by jdunham2** [videojs/video.js#7359]
## Description
When playing HLS videos on iPhone (not fullscreen), the `video play progress bar` is always showing even when `trackingThreshold` is set.

This can be reproduced using this StackBlitz: https://bug-videojs-hls-iphone-scrubber-always-showing.stackblitz.io

When using a desktop browser, the `video play progress bar` does NOT show using the same threshold as expected.

## Sources
https://bug-videojs-hls-iphone-scrubber-always-showing.stackblitz.io
https://github.com/jdunham2/bug-videojs-hls-iphone-scrubber-always-showing/

## Steps to reproduce

1. Use the following options for an inline HLS player
``` javascript
var options = {
  controls: true,
  preload: "auto",
  liveui: true,
  playsinline: true,
  autoplay: true,
  fill: true,
  liveTracker: {
    /**
     * Minimum amount of seconds of live playlist duration
     * in order to display the live UI with scrub bar.
     *
     * On Desktop No scrubber is present
     * On iPhone it is there.
     */
    trackingThreshold: 60
  },
  html5: {
    hls: {
      overrideNative: false
    }
  },
  techOrder: ["html5"]
};
```

2. Play a HLS video such as https://moctobpltc-i.akamaihd.net/hls/live/571329/eight/playlist.m3u8
3. Notice the progress bar is present on iPhone browsers but not Desktop browsers

We've also created a Stackblitz with the code for demo
1. Using an iPhone, open the stackblitz link
2. Press play (may need to then click in the player afterward on mobile) which opens an inline player
3. Notice the video playback progress bar is visible

### Expected
The inline player on iPhone should work with the same configuration as the desktop player and hide the progress bar when the stream is smaller than the trackingThreshold config value.

### Error output
No errors

## Additional Information
Please include any additional information necessary here. Including the following:

### videojs-http-streaming version
what version of videojs-http-streaming does this occur with?
videojs-http-streaming 2.2.4

### videojs version
what version of videojs does this occur with?
video.js 7.11.0

### Browsers
what browsers are affected? please include browser and version for each
* Chrome 87.0.4280.77 on iPhone
* Safari on iOS 14.2

### Platforms
what platforms are affected? please include operating system and version or device and version for each
* iOS 14.2

**Comment by gkatsev** [comment]
This issue fell behind because it was opened on the repo.

**Comment by gkatsev** [comment]
I'm unable to reproduce using your test page. I've tried Desktop Safari, Safari on my iPad, as well as on an iPhone.
In addition, we've had some fixes related to live tracking in Video.js since v7.10.
