### ISSUE TITLE
Dash fastSeek issue in safari

### ISSUE THREAD

**Issue by marcobouwmeester** [videojs/video.js#7360]
## Description
When in safari, we are encountering an issue where the progress bar does not work properly when using Dash. While playing the video, when we click in the progress bar and then click before the current time, the video playback stops and shows strange behaviour. I included a potential fix and reproduction steps here: https://codepen.io/MarcoTradecast/pen/ZEKoJYb. For the fix I disabled fastSeek only for safari, since fastSeek is also possible for Firefox.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open https://codepen.io/MarcoTradecast/pen/ZEKoJYb in Safari.
2. Change/revert the code as described in the comment.
3. Play the video and click (no dragging) to around 70% percent of the video in the progress bar.
4. Now click near the beginning of the video in the progress bar (once again no dragging).

### Expected
The video should go back to the desired timestamp.

### Actual
Video playback stops and currentTime is not being updated. Play/pause button is also not responding anymore.

### Error output
There are no errors

#### videojs
7.13.3
#### browsers
Safari (in my case 14.1.1)
#### OSes
macOS Big Sur 11.4
### plugins
No additional plugins are being used in the example.

I hope this issue is clear enough to reproduce :-)

**Comment by gkatsev** [comment]
I believe that this will be fixed via https://github.com/videojs/video.js/pull/7527
