### ISSUE TITLE
音量和播放进度条圆点在windows10下150%缩放非居中

### ISSUE THREAD

**Issue by friendtasy** [videojs/video.js#7362]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.使用 Video.js 7.14.2这个版本，语言为中文
2.显示器是27/2K 2560*1440分辨率，系统windows 10，缩放设150%
3.音量和播放进度条那个小圆点有点偏下，非正中，chrome 92，浏览器内显示是100%缩放，但从页面上观察应是系统缩放下的放大了的布局，用IE11使用100%缩放，字明显小很多，然后工具栏的文字提示成单列了，但是音量和进度条那个小圆点位置却是正中的。

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by crixue** [comment]
Hello, I have the same question with u. And would I know u how to handle this question now?

**Comment by dioramayuanito** [comment]
/* how to hide little circle in progressbar */
.vjs-icon-circle:before, .vjs-seek-to-live-control .vjs-icon-placeholder:before, .video-js .vjs-volume-level:before, .video-js .vjs-play-progress:before {
  content: "";
}

**Comment by friendtasy** [comment]
> /* css how to hide little circle in progressbar */
> .vjs-icon-circle:before, .vjs-seek-to-live-control .vjs-icon-placeholder:before, .video-js .vjs-volume-level:before, .video-js .vjs-play-progress:before {
> content: "";
> }

ha ha,why you can understand chinese?maybe you way is the only way to slove it~

**Comment by dioramayuanito** [comment]
i just curious what this chinese letters means with google translate 😉
i hope my answer will solve his problem

**Comment by gkatsev** [comment]
We've had this question before and as far as I could tell other on-page styles were interfering with the CSS for the seek handle. See https://github.com/videojs/video.js/issues/7004

**Comment by friendtasy** [comment]
> We've had this question before and as far as I could tell other on-page styles were interfering with the CSS for the seek handle. See #7004

thank you~
