### ISSUE TITLE
Hover on mute button disturbs the width of the control bar and as a result the fullscreen button is displayed outside the player

### ISSUE THREAD

**Issue by raghavshivi94** [videojs/video.js#7364]
## Description
Hover on mute button disturbs the width of the control bar and as a result the fullscreen button is displayed outside the player

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Hover on mute button
2. Volume control slider appears
3. Full screen button shifted outside the player

### Expected
Full screen button is not visible on hovering the mute button and visible if not hovered on mute button

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
^7.14.3
#### browsers
Chrome

**Comment by raghavshivi94** [comment]
![vdo](https://user-images.githubusercontent.com/53443659/128333961-be570fe8-75ae-4b6c-807c-86681d90a94c.JPG)

**Comment by gkatsev** [comment]
Do you have live example for this?
