### ISSUE TITLE
Rightclicking / clicking on player changes size of thumbnail

### ISSUE THREAD

**Issue by jonalange** [videojs/video.js#7366]
## Description
When rightclicking the player (left click will also work but as you start the video you won't notice it) or setting the div `.vjs-poster` on focus in devtools will make the thumbnail jump to it's original size.

My video sits inside a wrapper and the video is set to `.vjs-fluid`

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Import basic code from getting started page
2. Add `.vjs-fluid` to video element
3. Put video inside wrapper
https://jsfiddle.net/yshgo6u9/

### Expected
Nothing

### Actual
Thumbnail jumps and changes size
GIF: https://gyazo.com/f156ca6a00b61fc5d80aa373cff9be53

**Comment by mister-ben** [comment]
A fix for a related issue with menu items (#7202) also fixed this. That was released in v7.12.2, the latest is v7.14.3.
