### ISSUE TITLE
后端把m3u8返回内容和key、ts分别加密了，我应该在哪个函数下处理解密播放呢，我有解密函数

### ISSUE THREAD

**Issue by fuguiguang001** [videojs/video.js#7368]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
If I understand you correctly via google translate, you're using encrypted HLS (HLSe). Unfortunately, there isn't a good hook to be able to add your own decryption logic. If you're playing back on Safari, which uses native playback, it's not possible to do this at all.
I'd recommend that if you're use HLSe you should keep the segments encrypted with the key url provided in the manifest. If you need more security than that, look into DRM technologies.
