### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by chaitanya71998** [videojs/video.js#7370]
## Description
We previously used `video` tag for rendering sources in our React app as shown below

```JS

renderSources = () => {
  return <>
         {this.videoSources.map((source, index) => (
           <source
                src={source.src}
                type={source.type}
                key={source.src}
            />
         ))}
      </>
 }

render() {
<div>
      <video
         alt={'testing-video'}
         className={'video-js vjs-default-skin vjs-big-play-centered'}
         controls
         preload={auto}
         id={'some-id'}
         width={width}
         height={height}
         data-setup='{}'
         poster={poster}
         playsInline
      >
            {this.renderSources()}
      </video>
<div>
}
```

When there is an error on the player, we listen to it using 

```JS
this.player.on('error', this.onError)
```

and we change the source URLs based on server load like this.

```JS
this.videoSources = [...newSources]
```

There was no problem with this until we did an update.

Recently, we changed the tag from `video` to `video-js` as suggested in the docs for better.

But, when trying to do the same operation of changing the source URLs, we are getting the following error.

```JS
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node
```

Observing the elements tab in dev tools, 

Previously we used to have a structure in this way

```JS
<video src="url-1">
     <source src="url-1">
     <source src="url-2">
</video>
```

Now, we have it this way

```JS
<video-js>
     <video src="url-1">
           <source src="url-1">
           <source src="url-2">
     </video>
</video-js>
```

Can you please suggest a way to fix this?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Implement Video.js in react way
2. Change `video` tag to `video-js` tag
3. Try changing the video Source URLs after the player is loaded 

### Expected
The sources should be changed properly and there should be no error reported

### Actual
The player is getting crashed without changing the sources

### Error output
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.13.3
#### browsers
Chrome 92
#### OSes
Ubuntu 18.04
### plugins
videojs-contrib-quality-levels: 2.1.0,
videojs-http-source-selector: 1.1.6
@types/video.js: 7.3.23

**Comment by gkatsev** [comment]
Replacing the source elements inside of Video.js to update the sources isn't a supported use-case right now.
Our recommendation would be that to change sources you should be using the Player API such as `player.src()` or `player.loadMedia()`.

If you make a minimal live reduced example we can take a look, but it'll still be a low priority.

**Comment by chaitanya71998** [comment]
@gkatsev 

Yeah, replacing the sources is not for updating the sources for videoPlayer.

We are using `player.src('url')` to change the source.

But, to locally maintain the updated sources, we are just trying to change the existing array state.

This error is happening at that point. 

Otherwise updating the source URL is not an issue here.

**Comment by gkatsev** [comment]
I don't see a need to do so. I would recommend not touching the video element once Video.js has been initialized.

**Comment by chaitanya71998** [comment]
@gkatsev 

We are consciously doing that. We understood that changing the source elements will not affect the video element that wraps the sources, and hence the source URL will also not get disturbed.

That is why we are updating the source using `player.src()`

The need here is,

We are exposing the URLs in the inspect tab in the form of blob URLs. 

Hence, we wanted to change the URLs every time we update them.

This doesn't have any effect on the Video element.
