### ISSUE TITLE
Accuracy of player.currentTime()

### ISSUE THREAD

**Issue by kaikiat** [videojs/video.js#7371]
## Description
I am creating a function to seek to a particular timestamp for my video.

## Steps to reproduce
This is how I wrote my function in TypeScript
```
const seekTime = (secs: number) => {
     player.currentTime(secs)
     console.log(player.currentTime())
}
```
It works fine when in most cases except when `secs` is in 2 d.p or above , i.e

```
const seekTime = (secs: number) => {
     player.currentTime(30.01) // assume that secs is 30.01
     console.log(player.currentTime()). // It gives 33.009999 instead of 30.01
}
```
### Expected
Expects it to give me 30.01

### Actual
It gives 33.009999 instead

### Error output
No error

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.13.3
#### browsers
Chrome Version 92.0.4515.131
#### OSes
macOs Big Sur v 11.4
### plugins
No

**Comment by gkatsev** [comment]
Unfortunately, seeking on the web is not frame accurate.
