### ISSUE TITLE
Unsupported keySystem or supportedConfigurations

### ISSUE THREAD

**Issue by vinitgundeti** [videojs/video.js#7374]
## Description
Hi, I am using video js 7.14.0 version. 
I want to play dash manifest or video. some videos are playing but the one which has configured with vp9 are not playing. when i am trying to play this i am receiving Unsupported keySystem or supportedConfigurations Error. first i thought this is only happening with DRM video but this error is also coming in without DRM manifest as well.
but this videos are playing in other libraries such as dash.js and theOplayer.

## Steps to reproduce
```
player = videojs('player-1', {
        html5: {
            nativeAudioTracks: false,
            nativeVideoTracks: false
        },
    });

    player.src({
        src: "https://travelxp.s.llnwi.net/watch1/61025c11781ce3c543f5abcd/manifest_v4.mpd",
        type: "application/dash+xml",
    });
    player.play();
```
### Expected
video should play

### Actual
video is not playing.

### Error output
Unsupported keySystem or supportedConfigurations Error

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.14.0
#### browsers
Chrome
#### OSes
Mac
### plugins
https://www.nuevodevel.com/

**Comment by gkatsev** [comment]
I believe the issue is that we don't currently support webm segments right now and the only codec that's available in fmp4 segments is HEVC, which isn't playable in most desktop browsers.

**Comment by vinitgundeti** [comment]
but if i load this manifest (https://travelxp.s.llnwi.net/watch1/61025c11781ce3c543f5abcd/manifest_v4.mpd) here
https://videojs.github.io/videojs-contrib-dash/

it is playing

**Comment by gkatsev** [comment]
contrib-dash uses DASH.js which isn't our default playback engine. Definitely nothing stopping you from using videojs-contrib-dash.

**Comment by vinitgundeti** [comment]
okay. but in [this blog](https://blog.videojs.com/video-js-7-is-here/) it is mentioned that Video.js support for HLS and experimental DASH support via the Video.js HTTP Streaming (VHS) project. so still we need to use videojs-contrib-dash ?

**Comment by gkatsev** [comment]
Yup, we support DASH, but we don't yet support webm segments, unfortunately. DASH with fmp4 works, which we found is pretty common, especially since a lot of folks produce both HLS and DASH and having fmp4 segments minimizes differences between the two.

**Comment by vinitgundeti** [comment]
okay so to play the video which has webm segments i need to download Dash.js and videojs-contrib-dash. Include them both in my web page along with video.js ?

**Comment by gkatsev** [comment]
I believe latest contrib-dash includes dash.js inside it, so you shouldn't need to include dash.js separately anymore.

**Comment by gkatsev** [comment]
Yeah, I can see we do `import dashjs`. I guess the README is slightly out of date then.

**Comment by vinitgundeti** [comment]
added  videojs-contrib-dash (videojs-dash.min.js) script but i got error 
VIDEOJS: TypeError: Cannot read property 'MediaPlayer' of undefined

this is because it was trying to access dash
this.player.dash.mediaPlayer

so i added dash js script (dash.all.min.js)
now i am getting VIDEOJS: TypeError: this.mediaPlayer_.setTextDefaultEnabled is not a function

sharing screenshots for reference :
![Screenshot 2021-08-12 at 7 00 39 PM](https://user-images.githubusercontent.com/47896506/129205445-283330ed-da39-41d7-a556-21bfcee37b5d.png)

![Screenshot 2021-08-12 at 7 02 42 PM](https://user-images.githubusercontent.com/47896506/129205735-21bdac9f-d759-43ff-8161-68870ab596da.png)

**Comment by vinitgundeti** [comment]
Hi @gkatsev, i observerd that video is not playing with latest release of dash.js but it is playing with v3.1.0
when i added 
`<script src="https://cdn.dashjs.org/v3.1.0/dash.all.min.js"></script>`
it is playing
but with 
`<script src="https://cdn.dashjs.org/v4.0.1/dash.all.min.js"></script>`

getting error
video.min.js:19 Uncaught TypeError: this.mediaPlayer_.setTextDefaultEnabled is not a function

**Comment by prashantchothani** [comment]
Hello @gkatsev Thanks for your help here. We are facing same issue.

> I believe latest contrib-dash includes dash.js inside it, so you shouldn't need to include dash.js separately anymore

Do we need to include or should not ?
