### ISSUE TITLE
Latest version via CDN

### ISSUE THREAD

**Issue by jonalange** [videojs/video.js#7376]
I had a bug and submitted an issue and as response I got that my version isn't the latest and the bug has already been fixed.

How do I get the latest version via cdn?
On your page here https://videojs.com/getting-started/#videojs-cdn
It's only 7.11.4 and I can't change the url manually to 7.14.3

**Comment by gkatsev** [comment]
Looks like I forgot to publish the latest to the CDN.
Also noticed that the website hasn't been getting rebuilt on netlify as it's supposed to, which would show an up-to-date version.

**Comment by gkatsev** [comment]
Latest script is up on the CDN.

**Comment by gkatsev** [comment]
And fixed the website deploy too.
We're going to be adding some automation soon so that the our CDN is up-to-date.
