### ISSUE TITLE
how to play  “WS” video  source  src like ‘ws://10.2.145.66:559/openUrl/CLJ52BW’

### ISSUE THREAD

**Issue by yinqigithub** [videojs/video.js#7382]
how to play  “WS” video  

source  src like ‘ws://10.2.145.66:559/openUrl/CLJ52BW’
![image](https://user-images.githubusercontent.com/22470142/129822833-e76280fc-a901-4177-9b89-6f4a7e7ba5fe.png)

**Comment by gkatsev** [comment]
Unfortunately, we only support HTTP/S based urls by default. I'm not aware of any websocket based plugins, but it's definitely possible to make a plugin that enables websocket playback in Video.js. Unfortunately, it isn't something that we're able to provide ourselves.

**Comment by yinqigithub** [comment]
ok， thank you
