### ISSUE TITLE
when i change size of my video it generates a black small square without thumbnail

### ISSUE THREAD

**Issue by w4t3r-45** [videojs/video.js#7388]
hello i'm having an issue using video js  when i change the size of my video  video goes up my thumbnail and cotrols all hides up and it's showing a black small square without my video  and controls why this is happening ?

**Comment by gkatsev** [comment]
How are you changing the player size? What version of Video.js are you using?
Are you able to share a live minimal example with us?
Video.js doesn't provide any thumbnails itself. You'll want to open an issue with the plugin you're using.
