### ISSUE TITLE
Weird "cougin" or "looping" behavior on iPad

### ISSUE THREAD

**Issue by gregfr** [videojs/video.js#7398]
Greetings
I'm experiencing a weird behavior on iPad, I don't know if it's related to videojs or not.

I'm creating a 5 streams multiple bitrate HLS with 3 seconds chunks which works OK on devices other than iPad.
On iPad, after a few minutes, it's starting to "cough", i.e. it returns in time one or two seconds, making the speaker "stutter", but it continues to play and the drift is accumulating until the end of the playlist is reached.

I have no idea on how to investigate that, does anyone have an idea?

Thanks in advance

Regards

**Comment by gregfr** [comment]
Thanks for your answer. I connected to Apple's website and tried to found the software but with no success.
How di you open the network panel on iPad Safari?

**Comment by gkatsev** [comment]
You can't open the network panel on iPad without a Mac computer. You need to do remote debugging with safari on Mac to have access to the developer tools.

**Comment by gregfr** [comment]
Thanks for your answer.
I don't have a Mac available, but iPads are actually almost a zero audience population for me so... too bad lol
