### ISSUE TITLE
How to avoid Player Css conflict with Theme Css?

### ISSUE THREAD

**Issue by arunk9034** [videojs/video.js#7403]
Hi Team,

My player CSS is conflicting with theme CSS because there are some important rules on all div inside the body, Is there any way to avoid theme CSS conflict with the player. I'm trying to push the player script and CSS changes using the java script.

Thanks

**Comment by gkatsev** [comment]
Unfortunately, it isn't something simple. You'll likely want to do a CSS reset for these rules against `.video-js div` or whatever else that's interfering. Alternatively, put the player inside an iframe.
