### ISSUE TITLE
Adding markers on Video progress bar

### ISSUE THREAD

**Issue by spchuang** [videojs/video.js#741]
I see there are plugins to add thumbnail preview when hovering on the video progress bar, but I don't find any ways to put customizable markers upon progress bars like the ones shown in the picture. This is necessary to show some breaks in the video.

![screen shot 2013-09-16 at 3 36 48 pm](https://f.cloud.github.com/assets/1685857/1153387/81e47276-1f20-11e3-9966-324fa1524f9d.png)

I'll go ahead and make a plugin for this feature.

**Comment by ShinyBoy0** [comment]
I really appreciate you!
