### ISSUE TITLE
Video not streamable

### ISSUE THREAD

**Issue by Applepiee** [videojs/video.js#7411]
Hi,

Since a few days ago, the mobile browsers are no longer to play a video without first downloading the whole thing.
When I opened the chrome debug network tab I saw that the video only plays after the whole video file is completely downloaded.

How do we fix this?

**OS**
Android

**Browser**
Chrome

**Device**
Xiaomi Mi 10

**Comment by FredZeng** [comment]
Are you playing MP4? Have you ever checked your mp4 format? Make sure your mp4 did place the `moov` atom at the start.

**Comment by Applepiee** [comment]
Hi @FredZeng 
Yes, it is MP4 format and worked perfectly until recently. I'm not sure what changed. An update to google chrome mobile maybe?

**Comment by FredZeng** [comment]
@Applepiee  Check your MP4 `moov` atom first, then open your MP4 directly in your mobile browser. You should notice that Video.js actually uses native `<video />` to play MP4, which depends on browser's media ability.

**Comment by Applepiee** [comment]
Hi @FredZeng 
It seems like the problem is with the videos itself. They were copied from a backup server, and after the copy they are unable to do video streaming, and instead want to download the whole video first before it's able to start..

This is the moov info:

[root@ns571525 hd]# ffmpeg -v trace -i 3296.mp4 2>&1 | grep -e 'mdat' -e 'moov'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x57466c0] type:'moov' parent:'root' sz: 666455 40 119853175
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x57466c0] type:'mvhd' parent:'moov' sz: 108 8 666447
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x57466c0] type:'trak' parent:'moov' sz: 289658 116 666447
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x57466c0] type:'trak' parent:'moov' sz: 375673 289774 666447
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x57466c0] type:'trak' parent:'moov' sz: 660 665447 666447
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x57466c0] type:'udta' parent:'moov' sz: 348 666107 666447
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x57466c0] type:'mdat' parent:'root' sz: 119186621 666495 119853175

Is there something wrong with it?

**Comment by Applepiee** [comment]
It seems like the video is streamable..

```
[root@ns571525 hd]# mediainfo "--Inform=General;IsStreamable: %IsStreamable%" 3296.mp4
IsStreamable: Yes
```
