### ISSUE TITLE
Hide controlBar on Pause

### ISSUE THREAD

**Issue by Sell24** [videojs/video.js#7412]
I have looked and looked but could not find an option that would hide the controls on pause and then show on a mouseover. I was able to get around this by using the following code (vuejs based):

```javascript
      this.player = videojs(this.$refs.videoPlayer, this.options, function onPlayerReady() {
            var myPlayer = this;
            var isPaused = false
            var isHidden = false
            myPlayer.on("pause", function () {
               isPaused = isHidden = true
               myPlayer.controlBar.show()
            });
            myPlayer.on("play", function () {
               isPaused = isHidden = false
               myPlayer.controlBar.hide()
            });            
            myPlayer.on("mouseenter", function () {
               if (isPaused && isHidden) {
                  myPlayer.controlBar.show()
                  isHidden = false
               }
            });   
            myPlayer.on("mouseleave", function () {
               if (isPaused && !isHidden) {
                  myPlayer.controlBar.hide()
                  isHidden = true
               }
            });                               
      })
```

But I am just wondering, is this an option that I just missed or is this the way it should be done (or something similar)?

**Comment by FredZeng** [comment]
When the player play or pause, a `vjs-playing` class will be attached or detached. You can toggle control-bar by overwriting styles in [_control-bar.scss](https://github.com/videojs/video.js/blob/main/src/css/components/_control-bar.scss)

**Comment by OwenEdwards** [comment]
You need to consider keyboard accessibility/operation of the player as well as mouse-only operation - your proposed use of `mouseenter` and `mouseleave` will block sighted keyboard-only users from being able to operate the player correctly.

**Comment by Sell24** [comment]
Thank you both for you comments. I was looking to see if there was a config option that I missed that already took care of this functionality but apparently it seems it is something I need to implement myself whether using my way or css . @OwenEdwards I am using videojs for myself, so while it is an important point, for my use it is unnecessary. Thanks again for your comments.

**Comment by gkatsev** [comment]
Yeah, we don't have any such options. You could also try using user activity instead, and set user active on mousenter and userinactive on mouseleave `player.userActive(true)` and `player.userActive(false)`. This way, if you tab into things it should show the control bar again since keyboard usage should make the player active again.
However, what you have should work too within your constraints.
