### ISSUE TITLE
Bug [Accessibility]: : NVDA focus move to hidden volume slider present on video dialog using down arrow navigation in browse mode.

### ISSUE THREAD

**Issue by Saiteja341** [videojs/video.js#7415]
**Test Environment:**
OS: Windows 10 Version (OS Build 21390.1)
Browser: Anaheim Version 92.0.902.2 (Official build) dev (64-bit)
URL: [https://www.skype.com/en/](url)
Screen Reader: NVDA (2020.4)

## Steps to reproduce
1.Open the URL in Edge Anaheim dev browser.
2.Login with valid credentials.
3.Navigate to the 'Play Video' button using tab key and activate it.
4.Video dialog will be open.
5.Turn on NVDA using 'Ctrl+Alt+N' key and enable browse mode using 'Insert+Space' key.
6.Navigate to the video controls in browse mode using down arrow key.
7.Observe the issue.

### Expected
NVDA focus should not move to hidden volume slider using down arrow navigation in browse mode. NVDA focus should move to visible content of the page.

### Actual
NVDA focus move to hidden volume slider present on video dialog using down arrow navigation in browse mode.

**Note:**
1. NVDA focus is not moving time duration text in browse mode navigation using down arrow key. (Refer Attachment: Note_1.wmv)
2. Same issue (Both issue Main and Note_1) is repro in video controls present on below URL :  [https://www.skype.com/en/free-conference-call/ ](url)

**User Impact:**
Screen Reader user will face difficulty if screen reader focus is incorrect after any controls it will be very confusing and disorienting for user to perform a task.

**Guideline Reference**
https://www.w3.org/TR/WCAG21/#meaningful-sequence

**Attachment**
[Focus moves to hidden volume slider on the page.zip](https://github.com/videojs/video.js/files/7128909/Focus.moves.to.hidden.volume.slider.on.the.page.zip)

**Comment by mister-ben** [comment]
Thanks for the detailed report, however this page does not use Video.js.
