### ISSUE TITLE
[Accessibility]: An extra tab is encountered on Video frame under 'Get the most out of Skype' heading.

### ISSUE THREAD

**Issue by Saiteja341** [videojs/video.js#7416]
**Test Environment:**
OS: Windows 10 Version (OS Build 21390.1)
Browser: Anaheim Version 92.0.902.2 (Official build) dev (64-bit)
URL: [https://www.skype.com/en/features/](url)

## Steps to reproduce
1.Open the URL in Edge Anaheim dev browser.
2.Login with valid credentials.
3.Navigate to the controls present on video frame under 'Get the most out of Skype' heading using tab key.
4.Observe the issue.

### Expected
Extra tab should not be encountered for any of the UI element. Focus should move to Play/Pause button instead of going to video frame.

### Actual
An extra tab is encountered on Video frame under 'Get the most out of Skype' heading. First keyboard focus is moving to video frame and then again pressing tab focus is moving to Play/Pause button.

**User Impact:**
Focus order is not aligned with either the meaning or operation of the UI, which is confusing for the Keyboard dependent users who navigate the page sequentially and expect the focus order to be consistent with the sequential and meaningful reading order.

**Guideline Reference**
https://www.w3.org/TR/WCAG21/#focus-order

**Attachment**
[Extra tab on video section.zip](https://github.com/videojs/video.js/files/7129036/Extra.tab.on.video.section.zip)

**Comment by mister-ben** [comment]
Thanks for the detailed report, however this page does not use Video.js.
