### ISSUE TITLE
Subtitles are not displaying - TypeError: Cannot read properties of null (reading 'addEventListener')

### ISSUE THREAD

**Issue by kirandcunha** [videojs/video.js#7423]
## Description
stpp subtitles embedded in dash manifest are not displayed. 

## Steps to reproduce
1. Play URL https://livesim.dashif.org/dash/vod/testpic_2s/multi_subs.mpd using videojs.
2. Click on any subtitle

Sample: https://codepen.io/kirandcunha/pen/oNweOQM?editors=1010

### Expected
Subtitles should display

### Actual
Subtitles are not displaying

### Error output
video.debug.js:51412 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at workerCallback (video.debug.js:51412)
    at parseInitSegment (video.debug.js:51580)
    at video.debug.js:51636
    at callbackWrapper (video.debug.js:40836)
    at Object.callback (video.debug.js:40861)
    at cbOnce (video.debug.js:7872)
    at XMLHttpRequest.loadFunc (video.debug.js:7946)
![image](https://user-images.githubusercontent.com/10655667/133257612-af6547da-f1a1-43b9-b8f9-7c24ff9eea50.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
7.14.3

#### browsers
Chrome, Edge, Firefox
#### OSes
Windows 10
### plugins
videojs-contrib-quality-levels
videojs-seek-buttons
videojs-contrib-eme

**Comment by kirandcunha** [comment]
@gkatsev is there an alternative? Any plugin you can suggest which can be helpful?

**Comment by gkatsev** [comment]
Unfortunately, it isn't available. I'll be taking a look at making contrib-dash work with TTML captions as that's likely the most expedient method.

**Comment by gkatsev** [comment]
I got a change there. I expect a release of videojs-contrib-dash soon with support for TTML.
