### ISSUE TITLE
[Feature Request] Enhance videojs sample to accept custom URL and options

### ISSUE THREAD

**Issue by kirandcunha** [videojs/video.js#7424]
## Description
Current [videojs sample](https://videojs.com/advanced/) contains a few pre defined URLs and options. This can be enhanced to accept custom URLs and options as input. This can be a starter testbed to check default player behaviour.

## Steps to reproduce
Open https://videojs.com/advanced/

### Expected
User should be able to play custom URL and set options to videoJS player

### Actual
User can select pre defined videos

### Error output
NA

## Additional Information
NA

**Comment by mister-ben** [comment]
Does https://videojs-http-streaming.netlify.app have what you want?

**Comment by kirandcunha** [comment]
@mister-ben this looks good!
