### ISSUE TITLE
Issue with very short HLS chunks

### ISSUE THREAD

**Issue by gregfr** [videojs/video.js#7439]
Greetings
I'm experimenting with short HLS chunks (2s or less).
I'm currently watching a stream with 1s chunks (chunk list of 20 chunks). After about two hours, the player "falls behind" the end of the playlist, but doesn't restart to the latest chunk, which is weird since 20 seconds of video are available.
What's happening? how does the player chooses which chunk to fetch/play?
Thanks in advance
Regards

**Comment by dioramayuanito** [comment]
1second chunk is LLHLS spec (LowLatency HLS). you should turn-on videojs-http-streaming engine of LLHLS implementation (still experimental?)

you can search word 'llhls'

**Comment by gregfr** [comment]
Thanks for your answer. I didn't activate the LLHLS option. What's the limit? For example, 2s chunks arrive in less than 200ms, so it should ok (and it is for a while).
The question is actually on the strategy of the player regarding which chunk to download/play at a given time...
