### ISSUE TITLE
stream duration/remainingTime is infinity, need time so far for progress bar

### ISSUE THREAD

**Issue by YaBoiBreezy** [videojs/video.js#7443]
I am making controls for a video player using your code
I need a progress bar and xx:xx / xx:xx, but when I take vidPlayer.duration() or vidPlayer.remainingTime() I get infinity
I get that it's a stream, so it could theoretically never end, but I just need "duration so far"
I checked all the commands and didn't see anything that would work
please help
thanks

**Comment by gkatsev** [comment]
You can find out via seekable. `player.seekable().start(0)` beginning of the timeline and `player.seekable().end(0)` for the end. There may be multiple regions (though unlikely) so you may want to use `player.seekable().length` to get the end time.

**Comment by YaBoiBreezy** [comment]
Thanks gkatsev it works
