### ISSUE TITLE
Freeze in Chrome/Edge with MAIN Profile h264 encoding-settings

### ISSUE THREAD

**Issue by SL-Streamlab** [videojs/video.js#7445]
## Description
The video freezes with Chrome and Edge for about 4 seconds until it runs smoothly when using MAIN Profile in h264 encoding. 
Playerlink Video.js: https://lcplayerdev.livecoder.com/Watch/1jqvY3
Playerlink JW: https://lcplayerdev.livecoder.com/Watch/9ynlep

## Steps to reproduce
1. Open the Testplayerlink Video.js (https://lcplayerdev.livecoder.com/Watch/1jqvY3) with Chrome.
2. Press play to start the video (it should automtically play bitrate 1p) The video freezes for about 4 seconds until it runs smoothly. Rewind to the beginning to reproduce the freeze.
3. Change to Bitrate 2p, rewind and play the video. Here is will start without freezing.

## Results
Both playlists are encoded with the same setting except the mp4 PROFILE. The first video 1p uses MAIN as profile while the second one 2p was transcoded with BASELINE as profile.
When using JW Player (https://lcplayerdev.livecoder.com/Watch/9ynlep) it plays smoothly.
Firefox works fine. Problems with Chrome and Edge.

#### videojs
7.5.4
#### browsers
Chrome, Edge
### plugins
Videojs-hls-quality-selector v1.0.5
videojs-contrib-quality-levels v1.0.5
Videojs-watermark v2.0.0

**Comment by dioramayuanito** [comment]
i think your m3u8 has bad numbers in "Resolution"?

#EXTM3U 
#EXT-X-VERSION:3 
#EXT-X-STREAM-INF:BANDWIDTH=Main,RESOLUTION=960x1
en/v1/v1.m3u8 
#EXT-X-STREAM-INF:BANDWIDTH=Baseline,RESOLUTION=960x2
en/v2/v2.m3u8 


you can check good numbers of resolutions in here

https://support.google.com/admanager/answer/7245661?hl=id

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=694272,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=768x432
chunklist_b694272.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=202752,CODECS="avc1.66.31,mp4a.40.2",RESOLUTION=480x270
Chunklist_b202752.m3u8

**Comment by SL-Streamlab** [comment]
> i think your m3u8 has bad numbers in "Resolution"?
> 
> #EXTM3U #EXT-X-VERSION:3 #EXT-X-STREAM-INF:BANDWIDTH=Main,RESOLUTION=960x1 en/v1/v1.m3u8 #EXT-X-STREAM-INF:BANDWIDTH=Baseline,RESOLUTION=960x2 en/v2/v2.m3u8
> 
> you can check good numbers of resolutions in here
> 
> https://support.google.com/admanager/answer/7245661?hl=id
> 
> #EXTM3U #EXT-X-VERSION:3 #EXT-X-STREAM-INF:BANDWIDTH=694272,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=768x432 chunklist_b694272.m3u8 #EXT-X-STREAM-INF:BANDWIDTH=202752,CODECS="avc1.66.31,mp4a.40.2",RESOLUTION=480x270 Chunklist_b202752.m3u8

Hi dioramayuanito,

yeah, don't worry about that. I changed it so that I can easier decribe the problem by just saying change the bitrate to "1p" or "2p". The problem still occurs even if that resolution is correct. As I decribed, the problem is the mp4 Profile BASELINE combinded with Chrome or Edge and using video.js as player. Looks like a bug to me.

Best Regards,
Armin

**Comment by dioramayuanito** [comment]
ok... ic... 
btw fyi JWPlayer uses HLS.js v1.0.7 https://github.com/video-dev/hls.js/releases/tag/v1.0.7
they didn't use VHS (VideoJS-Http-Streaming)
