### ISSUE TITLE
Not able to play youtube video. keeps infinite buffering.

### ISSUE THREAD

**Issue by dexterprabhakar** [videojs/video.js#7452]
## Description
Briefly describe the issue.
https://codepen.io/heff/pen/EarCt . This is a simple sample video-js codepen. Change the video src to any youtube embed video and see the effect. The video does not plays whereas the orignal video plays.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Youtube video should play in videojs as expected

### Actual
infinite buffering without error

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
You'll need the You Tube tech to play You Tube sources: https://github.com/videojs/videojs-youtube
