### ISSUE TITLE
TextTrack.mode hidden not supported

### ISSUE THREAD

**Issue by amtins** [videojs/video.js#7461]
## Description

The TextTrack.mode `hidden` does not seem to be supported anymore.

## Steps to reproduce

1. Open the [test page vjs 7.7.6](https://amtins.github.io/cassettator-forbidden-adventures/?version=7.7.6&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8)
2. Start the playback
3. Open the developer console
4. Paste `player.textTracks()[1].mode = 'hidden'` then `player.textTracks()[2].mode = 'showing'`

The same test can be done with the [test page vjs 7.7.5](https://amtins.github.io/cassettator-forbidden-adventures/?version=7.7.5&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8).

### Expected

Using the textTrack mode `hidden` should work.

### Actual

When using the `hidden` text track mode instead of `disabled`, the selection of text tracks no longer works.

#### videojs

Since videojs version 7.7.6

#### browsers
Tested on Firefox and Chrome

#### OSes
Tested on Ubuntu, Android

**Comment by gkatsev** [comment]
Unfortunately, the way that we currently handle loading text tracks in VHS, we are only able to load a single track at the same time. A mode of hidden should work, but only a single track will work at a time. So, when you set the `[2].mode` to `showing` we turn off `[1].mode`. We do want to support this at some point, but we haven't had a chance to do so. It'll require a pretty big refactor that is currently in progress to work.
