### ISSUE TITLE
Metadata is not getting loaded when disabling qualities in vjs-layout-small

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/video.js#7464]
## Description
When I try to manually enable and disable qualities after the player is initialized, `metadata` is not getting loaded, hence `loadedmetadata` event is not getting called.

This is happening specifically when the player is with the `vjs-layout-small` class (Not accurate though, but mostly when it is)

Here is the [codesandbox](https://codesandbox.io/s/strange-yonath-ho06d?file=/src/Video.js&resolutionWidth=360&resolutionHeight=675) link to reproduce the issue.

## Steps to reproduce
In the code

1. Try checking the output by commenting and uncommenting the lines between 47 and 51 (I have added a note there saying that they are the culprits).
2. Try checking by changing the viewport dimensions to identify the difference.
3. You can check for the `metadata loaded` event in the console (Triggered by videojs-http-source-selector).

### Expected
Metadata should get loaded

### Actual
Metadata is not getting loaded when video is with `vjs-layout-small` class

### Error output
No errors

#### browsers
Chrome 93
#### OSes
Ubuntu
### plugins
videojs-http-source-selector  1.1.6
videojs-contrib-quality-levels 2.1.0

**Comment by gkatsev** [comment]
My initial thought is that you're turning off a level we're trying to load and basically causing a race condition where we fail to actually switch renditions.
It does seem like clicking play does work, and we end up finishing loading at that point.
Unfortunately, I'm not sure we'll be able to take a look at this in the short term. I would recommend waiting for loadedmetadata and then turn on/off the tracks that you want/dont want.

**Comment by KVPasupuleti** [comment]
Yeah, but is it guaranteed that the metadata is loaded only after the levels are added?
