### ISSUE TITLE
Azure AES Dash/DashCMAF encryption playback using videojs

### ISSUE THREAD

**Issue by Sushmahp95** [videojs/video.js#7470]
Hello, We are facing issue while playing azure encrypted DASH/DASH CMOF urls using videojs.  

We are using following code snippet to play `aes encrypted `hls ad dash urls
```
setupTokenForDecrypt (options) {
    if (options.uri.includes('keydeliver')) {
      options.headers = options.headers || {};
      options.headers.Authorization = 'Bearer ' +  this.aesTokenUrl;
    }
  playVideojs (playbackData: any) {

      videojs['Hls'].xhr.beforeRequest  = (options) => this.setupTokenForDecrypt(options);
     
   `---added piece of `code for playing content

    }
```

DASH url: 
https://tataelxsincpa-vod.pc.cdn.bitgravity.com/b1d0b4da-aa6e-47b7-b717-71154bd70fc6/PiratesoftheCaribbeanAtWorld'sEn.ism/manifest(format=mpd-time-csf,encryption=cbc)

DASH CMOF url
https://tataelxsincpa-vod.pc.cdn.bitgravity.com/b1d0b4da-aa6e-47b7-b717-71154bd70fc6/PiratesoftheCaribbeanAtWorld'sEn.ism/manifest(format=mpd-time-cmaf,encryption=cbc)

AES token:
eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJURUxAMTIzNDUiLCJuYmYiOjE2MzQxMTI2MDQsImlzcyI6Ik5DUEFfQ0xJRU5UIiwiZXhwIjoxNjM0MTEzMjA0fQ.pq8wvU9yqoAkY-86CWhRwluKrMtEZx_3-3Bpk5ky7yQ

## Results
 Should able to play Dash and DASH-CMOF urls in videojs
### Expected
Please describe what you expected to see.

### Actual
When try to play dash/Dash cmof url getting tis error : [ERROR] (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

### Error output
Video keep  on loadng
ERROR] (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

## Additional Information
Observation captured while playing AES encrypted DASH/DAH CMOF urls
The player requests the streaming manifest, then it started to request the video/audio fragments without sending a request to the key delivery server, and because of that the player will not be able to decrypt the encoded stream,

-Video JS recognize the AES protection, but not sending the key delivery request(maybe bug or not supported)
#### videojs
 7.8.2
#### browsers
Chrome, Edge
#### OSes
Windows
### plugins
   "videojs-contrib-dash": "^2.11.0",
    "videojs-contrib-eme": "^3.7.0",
    "videojs-contrib-quality-levels": "^2.0.9",
    "videojs-http-source-selector": "^1.1.6",

#6717

**Comment by Sushmahp95** [comment]
@gkatsev Thank you so much for your reply.
Yes, i have tried with latest version of videojs also,
But for dash AES, video keep on loading 
Please help any other solution which will work for both HLS and DASH aes playback.

**Comment by luisamiranda** [comment]
I am using the most recent version of video.js and specifying vhs:overrideNative: true and have the same problem. The manifest is loaded, but the fragments all come back as unauthorized. The function at the top fixed it in older versions (I'm told), but is no longer exposed to override.
