### ISSUE TITLE
I can't make changes to config file

### ISSUE THREAD

**Issue by mattcwebster** [videojs/video.js#7473]
I want to increase the buffer before livestream plays to prevent buffering if slow server times.

I try to change like this, but when I inspect videojs.Vhs it never updates past 30.  

    videojs.Vhs.GOAL_BUFFER_LENGTH = 70;

**Comment by gkatsev** [comment]
There's also a `MAX_GOAL_BUFFER_LENGTH`.
We generally recommend against changing these things. Also, it's definitely possible that we don't actually succeed in filling out the full buffer. Our ABR doesn't take the goal buffer length into account when deciding which rendition to take, so, if we think there's enough bandwidth for a higher rendition, we can still choose it, and it may mean that the buffer doesn't fill up fully. In addition, different devices have limits on how big the buffer can be, so, that's another limit on it.
If you're seeing playback issues, I would recommend turning on `experimentalBufferBasedABR`, while it's flagged behind an experimental flag, it's pretty well tested at this point, we are still tweaking the configuration for it. But it should generally make playback work better but limiting when the player can switch up or down and does bandwidth estimation via an exponential moving average.

**Comment by mattcwebster** [comment]
> There's also a `MAX_GOAL_BUFFER_LENGTH`. We generally recommend against changing these things. Also, it's definitely possible that we don't actually succeed in filling out the full buffer. Our ABR doesn't take the goal buffer length into account when deciding which rendition to take, so, if we think there's enough bandwidth for a higher rendition, we can still choose it, and it may mean that the buffer doesn't fill up fully. In addition, different devices have limits on how big the buffer can be, so, that's another limit on it. If you're seeing playback issues, I would recommend turning on `experimentalBufferBasedABR`, while it's flagged behind an experimental flag, it's pretty well tested at this point, we are still tweaking the configuration for it. But it should generally make playback work better but limiting when the player can switch up or down and does bandwidth estimation via an exponential moving average.

yes I've tried changing both of these values

    videojs.Vhs.GOAL_BUFFER_LENGTH = 140;
    videojs.Vhs.MAX_GOAL_BUFFER_LENGTH = 140;

Doing some testing on a Windows PC, Chrome the average buffered content is about 12sec, my clips are 6 sec segments so basically 2 segments ahead of time.  This is fine if my server is running great but if any network slowdown it can lead to video player spinning.  

How do I turn this on experimentalBufferBasedABR, this is how im setting my player now, im using Angular

      const options1 = {
        'sources': [{
          src: this.src,
          type: 'application/x-mpegURL'
        }],
        fluid: 'true',
        liveui: true,
        liveTracker: { trackingThreshold: 0 },
      };
      this.vjs = videojs('my-player' + this.topic.topicGuid, options1);

**Comment by mattcwebster** [comment]
Thanks for all your help just wanted to say you're awesome for maintaining this crucial repo!
