### ISSUE TITLE
autoplay: "string" fails in scenarios where autoplay: true, muted: true works

### ISSUE THREAD

**Issue by phloxic** [videojs/video.js#7477]
## Description
Test case can be found [here](https://phloxic.productions/test/videojs/autoplay.html)

The docs for the [autoplay option](https://docs.videojs.com/player#autoplay) suggest that you can pass string values to the option. However, configuring autoplay this way is fails in some browsers where using `muted: true, autoplay: true` succeeds.

`loadstart` is probably triggered too late in these scenarios.

Similarly the promise based approach with explicit `play()` call recommended as best practice in the [videojs blog](https://videojs.com/blog/autoplay-best-practices-with-video-js/) also fails this way (may need another issue), most likely because the [manualAutoplay_](https://docs.videojs.com/player#manualAutoplay_) uses promise.

Note: adding `muted: true` does not change the behaviour.

## Steps to reproduce
1. Configure a player with `autoplay: 'muted/any/play'`
2. Test the player

### Expected
Should work the same way as configuring `autoplay` (and `muted`) with boolean values.

### Actual
The player does not autoplay in some scenarios, where at least with `autoplay: 'any'` or `autoplay: 'muted'` it should.

### Error output
If there are any errors at all, please include them here.

#### videojs
Verfied with 7.15.4, 7.16.0
#### browsers
Verified for Firefox, Chrome (Mac OS), Chrome on Android
#### OSes
Various, see browsers
### plugins
No plugins used

**Comment by gkatsev** [comment]
I wonder if it's due to a Chrome change. I _know_ it used to work at some point.

**Comment by phloxic** [comment]
@gkatsev - it works when I call `player.src`, but not when I configure the `sources` option.

**Comment by gkatsev** [comment]
haha nice, I could've sworn it wasn't actually documented.

**Comment by phloxic** [comment]
[Test page](https://phloxic.productions/test/videojs/autoplay.html) is updated to v.7.19.2.
At least temporarily `video-js` tags are used.

Quick test on Mac:
- Firefox 100.0.2: no autoplay
- Safari 15.5: works (with playhead jumps/stutters on start, which is probably not specific to this issue)
- Chrome 102.0.5005.61: autoplay on page reload or after a couple of reloads
