### ISSUE TITLE
Subtitles not working

### ISSUE THREAD

**Issue by veniplex** [videojs/video.js#7490]
I am using the newest version of video.js. I try to make subtitles working, but it doesn't.

My index.html:
```
<!DOCTYPE html>
<html>
<head>
	<link href="script/video-js.css" rel="stylesheet" />
	<meta charset="utf-8">	
	<title>Video test</title>
</head>

<body>
	<video style="display: block; margin: 0 auto 0 auto;" id="my-video" class="video-js" controls controlsList="nodownload" preload="metadata" width="1280" height="720" data-setup="{}">
		<source src="video/video.mp4" type="video/mp4" />
		<p class="vjs-no-js">
		To view this video please enable JavaScript and consider use a web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a> like Google Chrome or Mozilla Firefox.
		</p>
		<track kind="captions" src="caption/subtitles.vtt" srclang="en" label="English" default>
	</video>
	<script src="script/video.min.js"></script>
</body>
</html>
```

Folder structure:
- index.html
- video
-- video.mp4
- caption
-- subtitles.vtt
- script
-- video-js.css
-- video.min.js

No matter what I do, subtitles are not showing. Based on https://quuz.org/webvtt/ the VTT file is valid. FYI: The VTT file was generated by Microsoft Stream.

**Comment by OwenEdwards** [comment]
Which browser are you using? Can you check in the browser's Developer Tools/Console whether video.js is even sending a request for the captions file? If so, are there any errors in the console?

**Comment by veniplex** [comment]
I am using Google Chrome. I fixed the issue.... but I don't understand why. The .vtt has to be in the same folder as the .html.

```
<!DOCTYPE html>
<html>
<head>
	<link href="script/video-js.css" rel="stylesheet" />
	<meta charset="utf-8">	
	<title>OQ Chemicals New Organization</title>

	<style>
		div {
			display: block;
			margin: auto;
			
		}
		a {
			display: block;
			text-align: center;
			margin: auto;
			padding: 25px;
		}
	</style>
</head>

<body>
<div>
	<video id="my-video" class="video-js" controls controlsList="nodownload" preload="metadata" width="1280" height="720" data-setup="{}">
		<source src="video.mp4" type="video/mp4" />
		<p class="vjs-no-js">
		To view this video please enable JavaScript and consider use a web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a> like Google Chrome or Mozilla Firefox.
		</p>
		<track label="English" kind="subtitles" srclang="en" src="subtitles.vtt" default>
	</video>
	<script src="script/video.min.js"></script>
	<script>window.HELP_IMPROVE_VIDEOJS = false;</script>
	<a href="transcript/oqc_new_organization.txt" download>Download Transcript (English)</a>
</div>
</body>
</html>
```

Can anyone explain?

**Comment by OwenEdwards** [comment]
Are you using a web server to provide each of the files (`http:` or `https:` in the URL), or are you accessing them locally (`file:`)?

**Comment by veniplex** [comment]
> Are you using a web server to provide each of the files (`http:` or `https:` in the URL), or are you accessing them locally (`file:`)?

I am using a Windows Server IIS. It's `http`. Files were originally located in a subfolder of the `index.html` folder.

**Comment by albacodina** [comment]
I have the same problem, I add the file:
```
sources: [{
             src: "https://localhost/trackfile/619b7f60a5983a25886d82b2.mp4"
}]
, tracks: [
              {
              src: 'https://localhost/uploads/material/619685b9106f4274e875d812/subtitle.vtt',
              kind: 'captions',
              label: 'English',
}
]
```
If I access the url, the file is downloaded, therefore I don't know what the problem is.

**Comment by gkatsev** [comment]
It sounds like the original issue has been solved. The issue was an incorrect url path to the vtt files.

@albacodina are you seeing any issues in the console? Is the vtt file showing up in the network panel? Are you able to provide a live minimal test page?
