### ISSUE TITLE
how to remove or hide the close modal dialog button

### ISSUE THREAD

**Issue by monsky32** [videojs/video.js#7505]
i created a modal in my video and the viewer must complete a survey listed in a modal to continue watching the video the problem is that the modal has a separated default close dialog box that is very much unwanted in my design.

**Comment by mister-ben** [comment]
Use the `uncloseable` option:

```js
player.createModal('My modal content', {uncloseable: true});
```

**Comment by monsky32** [comment]
> Use the `uncloseable` option:
> 
> ```js
> player.createModal('My modal content', {uncloseable: true});
> ```

yes thank you, it works
