### ISSUE TITLE
video.js in Ionic framework

### ISSUE THREAD

**Issue by kannanvrn** [videojs/video.js#7522]
## Description
I am currently using video.js in Ionic with Angular project. Am trying to develop hybrid app for iOS, Android and Web. Video player is working fine in all platforms.
I need to use capacitor http native call for iOS and Android instead of default xhr request that goes from the player. How can i change each request into capacitor http call instead of default request from player ?

**Comment by gkatsev** [comment]
Unfortunately, we don't have a good way of letting folks override the network calls we make.
It's something that's been requested a lot and something we'd like to do but unfortunately, it isn't something we're able to get to in the near future.

**Comment by kannanvrn** [comment]
Thank You for the reply.

**Comment by mfettah** [comment]
Hi, for me the player note work !
![image](https://user-images.githubusercontent.com/11535868/143135909-a78e2ed9-25d0-470d-8ebc-43d47dd76b3c.png)
