### ISSUE TITLE
The custom menu works normally on the computer side, but there is no response when clicking on the mobile side.

### ISSUE THREAD

**Issue by ljhint** [videojs/video.js#7523]
## Description
The custom menu works normally on the computer side, but there is no response when clicking on the mobile side.
自定义菜单，电脑端正常工作，移动端点击没有反应。
## Steps to reproduce

1.Source code 源码
 
```js
var player = videojs("videoPlayer");
var MenuButton = videojs.getComponent('MenuButton');
var Menu = videojs.getComponent('Menu');
var MenuItem = videojs.getComponent('MenuItem');
const sourceItems = {"高清":"https://vjs.zencdn.net/v/oceans.mp4", "普通":"https://vjs.zencdn.net/v/oceans.mp4"};
const sourceMenu = new Menu(player);
const sourceMenuItemList = [];
let j = 0;
for (let item in sourceItems) {
    sourceMenuItemList.push(new MenuItem(player, {label:item}));
    sourceMenuItemList[j].on('click', $event => {
        let whereYouAt = player.currentTime();
        player.pause();
        player.src({type: 'video/mp4', src: sourceItems[item]});
        player.ready(function() {
            player.play();
            player.currentTime(whereYouAt);
        });
    })
    sourceMenu.addItem(sourceMenuItemList[j]);
    j++;
}
const sourceMenuButton = new MenuButton(player);
sourceMenuButton.addChild(sourceMenu,{},1);
sourceMenuButton.controlText('清晰度');
sourceMenuButton.addClass('source-menu-button');
player.controlBar.addChild(sourceMenuButton, {},15);`
```

### Expected
The menu can be generated normally, but an extra "vjs-menu Div" is generated. When the menu is clicked on the mobile terminal, an empty "vjs-menu Div" is activated.

能正常生成菜单，但是多生成了一个 "vjs-menu   Div"，导至在移动端点击菜单时，激活的是一个空的  "vjs-menu  Div"。

### Error output
```html
<div class="vjs-menu-button vjs-menu-button-popup vjs-control vjs-button source-menu-button">
<button class="vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" aria-haspopup="true" aria-expanded="true" title="清晰度">
<span class="vjs-icon-placeholder" aria-hidden="true"></span>
<span class="vjs-control-text" aria-live="polite">清晰度</span>
</button>
<div class="vjs-menu">
<ul class="vjs-menu-content" role="menu">
<li class="vjs-menu-item" tabindex="-1" role="menuitem" aria-disabled="false"><span class="vjs-menu-item-text">高清</span><span class="vjs-control-text" aria-live="polite"></span></li>
<li class="vjs-menu-item" tabindex="-1" role="menuitem" aria-disabled="false"><span class="vjs-menu-item-text">普通</span><span class="vjs-control-text" aria-live="polite"></span></li>
</ul>
</div>
<div class="vjs-menu vjs-lock-showing">
<ul class="vjs-menu-content" role="menu"></ul>
</div>
</div>
```

### versions
Video.js 7.15.5

#### browsers
Google Chrome 95.0.4638.69
#### OSes
Win11

**Comment by gkatsev** [comment]
`MenuButton` creates a `Menu` itself when created. You probably want to use its menu via `sourceMenuButton.menu` instead of creating a menu yourself.
You can create it early and then do `const sourceMenu = sourceMenuButton.menu` and the rest of the code can mostly stay the same.

**Comment by ljhint** [comment]
> `MenuButton` creates a `Menu` itself when created. You probably want to use its menu via `sourceMenuButton.menu` instead of creating a menu yourself. You can create it early and then do `const sourceMenu = sourceMenuButton.menu` and the rest of the code can mostly stay the same.

Thank you very much, this method can be used

**Comment by ljhint** [comment]
Later I tried to use third-party plugins,
'videojs-language-switch','silvermine-videojs-quality-selector'
They are all very good.

**Comment by gkatsev** [comment]
Yup, those are also good options instead of doing it yourself.
