### ISSUE TITLE
Get Black bars size

### ISSUE THREAD

**Issue by tfmoraes** [videojs/video.js#7524]
When the video doesn't have the same proportion of the media, black bars appears inside the video element. Is it possible to get the size of that black bars?

**Comment by mister-ben** [comment]
Not directly, but you can get `player.currentHeight()` and `player.videoHeight()` and the same for widths, and calculate the respective aspect ratios. You might also want to try fluid mode, so the player matches the video aspect ratio.

**Comment by tfmoraes** [comment]
Thanks @mister-ben! I'm using fluid mode and it's working very well.
