### ISSUE TITLE
Webvtt Subtitles not working for DASH 

### ISSUE THREAD

**Issue by s3bubble** [videojs/video.js#7525]
## Description

I have encoded my media using Shaka packager to add webvtt subtitles using the command here.

https://google.github.io/shaka-packager/html/tutorials/text.html#examples

`packager 'in=input.vtt,stream=text,init_segment=init.mp4,segment_template=text_$Number$.mp4'`

I cannot seem to get the subtitles to play with videojs I have setup an example here.

https://jsbin.com/rinemex/edit?html,output

Here is the live mpd manifest I am testing with.
https://d3370nekj200fx.cloudfront.net/8f6b5ce6_e424_476e_a083_1f24d6e7c899/master.mpd

Subtitles work on these players.
https://videojs.github.io/videojs-contrib-dash/
https://bitmovin.com/demos/drm
https://developer-tools.jwplayer.com/stream-tester

But subtitles dont show up on the videojs player. Its weird as i thought the videojs dash was bundled with the videojs framework.

I have tried setting the native track options to true but no luck.

Any suggestions?

**Comment by phloxic** [comment]
@s3bubble vtt subtitles embedded in mp4 are not yet supported by the vhs tech: see https://github.com/videojs/http-streaming/issues/391

**Comment by s3bubble** [comment]
@phloxic thanks for the info i think we will just update the manifest then if thats all that is needed something like this.
``` js
const xml2js = require('xml2js');
const fs = require('fs')

fs.readFile('./master.mpd', 'utf8', (err, data) => {
    if (err) {
        console.error(err)
        return
    }
    xml2js.parseString(data, function(err, result) {
        result.MPD.Period[0].AdaptationSet.push({
            '$': { mimeType: 'text/vtt', lang: 'en' },
            Representation: {
                '$': { id: 'caption', bandwidth: '123' },
                BaseURL: ['subtitles/sub.vtt']
            }
        });
        const builder = new xml2js.Builder();
        const xml = builder.buildObject(result);
        console.log('Save updated manifest', xml);
    });

});
```

**Comment by s3bubble** [comment]
Ok working now with sidecar subtitles.

https://jsbin.com/rinemex/3/edit?html,output

Its seems the caption menu uses the language attribute instead of the label attribute.

Maybe there should be some kind of conditional as you should be able to have multiple captions for the same language.

(attribute.label) ? attribute.label : attribute.language

Going to take a look at the code.

``` xml
<AdaptationSet mimeType="text/vtt" lang="en" label="English">
      <Representation id="caption">
        <BaseURL>subtitles/en-english.vtt</BaseURL>
      </Representation>
    </AdaptationSet>
    <AdaptationSet mimeType="text/vtt" lang="en" label="English Forced">
      <Representation id="caption">
        <BaseURL>subtitles/en-english_forced.vtt</BaseURL>
      </Representation>
    </AdaptationSet>
    <AdaptationSet mimeType="text/vtt" lang="fr" label="French">
      <Representation id="caption">
        <BaseURL>subtitles/fr-french.vtt</BaseURL>
      </Representation>
    </AdaptationSet>
```
