### ISSUE TITLE
Unable to load audio and caption tracks on iOs

### ISSUE THREAD

**Issue by jaspalm** [videojs/video.js#7526]
## Description
Similar to the following issue: https://github.com/videojs/video.js/issues/7467

I am able to load captions and audio for android, desktop safari, desktop firefox, and desktop chrome. I include this in my player options per suggested in the previous issue, but still can not load audio and captions on iOs devices: 

`          html5: {
            nativeTextTracks: videojs.browser.IS_ANY_SAFARI,
            nativeAudioTracks: videojs.browser.IS_ANY_SAFARI,
            nativeVideoTracks: videojs.browser.IS_ANY_SAFARI,
            vhs: {
              overrideNative: !videojs.browser.IS_ANY_SAFARI,
            },
          },`

A playground illustrating the issue: https://codesandbox.io/s/compassionate-cloud-8bqj1?file=/src/App.tsx

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Watch a .m3u8 file with captions and audio, notice that the audio and caption tracks are empty when using iOs
2.
3.

### Expected
Captions and audio options available on ios

### Actual
Captions and audio are not available on ios

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### what version of videojs does this occur with?
videojs 7.15.4
#### browsers
ios Safari
#### OSes
ios

**Comment by gkatsev** [comment]
I'm unable to reproduce. Loading your sandbox on my iPad I can see and change the captions tracks and the audio tracks.

**Comment by jaspalm** [comment]
> I'm unable to reproduce. Loading your sandbox on my iPad I can see and change the captions tracks and the audio tracks.

Are you using the latest iOs? I'm debugging on my iphone with the latest version of iOs, and this is what I see:

<img width="1002" alt="Screen Shot 2021-11-15 at 1 14 34 PM" src="https://user-images.githubusercontent.com/78827099/141847728-eda9e524-69ad-4a74-9781-d52114dfacbf.png">

I see captions on the player, but I the captions do not change when I select one.

**Comment by gkatsev** [comment]
Yup, on latest. Let me see if the API usage. Could be a timing issue.

**Comment by jaspalm** [comment]
I'll update my sandbox as well. In my actual application, I'm reading audio and captions in the onLoadedMetaData event.

**Comment by gkatsev** [comment]
So, looking at the codesandbox you request the tracks on player ready. This is too early. As you mentioned, you need to wait till at least `loadedmetadata`. Though, we've seen a few occasions that that was too early for Safari, for some reason.
Trying it out locally, I can see that `canplay` will always work. I'm not really sure why `loadedmetadata` is too early now. Must be some change on Safari's side.

**Comment by gkatsev** [comment]
Also, worth noting that you should be using `player.audioTracks()` and ignoring TS's typing checking here. The Video.js types are almost always out of date and can lead you astray.

**Comment by jaspalm** [comment]
I was able to fix the issue in our application by handling captions and audio during the `onCanPlay` event.
