### ISSUE TITLE
Safari: seeking in paused state in native HLS stream with iframe variants makes player hang

### ISSUE THREAD

**Issue by phloxic** [videojs/video.js#7529]
## Description

Test case (using http-streaming demo): https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=false&llhls=false&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&override-native=false&preload=auto&mirror-source=false

## Sources
Is a certain source or a certain segment affected? please provide a public (accessible over the internet) link to it below.
Any HLS source containing I-frame variants, e.g. the default stream on the demo page:  https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

## Steps to reproduce

1. In Safari go to [demo page](https://videojs-http-streaming.netlify.app/)
2. Turn off overrideNative
3. Start playback
4. Pause
5. Seek (try both scrubbing and tapping target position)

### Expected
Player should seek to target position.

### What actually happens
Player is stuck, displaying loading animation. - If lucky one can resume playback by clicking play button.
When seeking (backwards) in playing state, player often jumps back to original position.

AFAIK i-frame variants are not yet supported, and one can avoid the issue by not playing manifests containing i-frame variants. But it would be better not to be forced use edited manifests.

### Error output
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/gear4/iframe_index.m3u8
```
or any other i-frame variant of the stream.

### videojs-http-streaming version
Should not matter because overrideNative is unset

### videojs version
Current. And previous since a long time.

### Browsers
* Safari on mac OS
* possibly also Safari on iOS
* other native HLS scenarios?

### Platforms
* mac OS
* see Browsers above

**Comment by gkatsev** [comment]
This actually happens because this video doesn't actually have the iframe playlist available on the server and on Safari we use fastSeek by default which uses the iframe playlist (This is fixed as part of https://github.com/videojs/video.js/pull/7527, which will then only use fastSeek if scrubbing rather than just click to seek). The "Advanced Bipbop - FMP4 hevc, demuxed" video has iframes and should work. https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=false&llhls=false&url=https%3A%2F%2Fdevstreaming-cdn.apple.com%2Fvideos%2Fstreaming%2Fexamples%2Fbipbop_adv_example_hevc%2Fmaster.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&override-native=false&preload=auto&mirror-source=false

**Comment by phloxic** [comment]
Ah, sorry, I didn't believe those streams were actually missing.
However, I can observe erroneous behaviour with my streams (mediastreamvalidator does not bark) and even in this Apple demo in the native player: https://developer.apple.com/streaming/examples/advanced-stream-ts.html
The playhead jumps back to the original position and then forward to target.
For the moment I think there's some issue with i-frame variants of TS video streams. Although sometimes, more rarely, empty cache helps also with the HEVC stream.

**Comment by phloxic** [comment]
@gkatsev - upon further inspection the [HEVC example](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=false&llhls=false&url=https%3A%2F%2Fdevstreaming-cdn.apple.com%2Fvideos%2Fstreaming%2Fexamples%2Fbipbop_adv_example_hevc%2Fmaster.m3u8) does not really work either for me (mac OS 10.15.7, Safari 15.1).
Play around with jumping or scrubbing, and you'll see the playhead sometime not moving not moving or moving unexpectedly or jumping back or forth.

On the other hand it does not work consistently in the native player either. Jump search often doesn't move the playhead in paused state until you re-start playback, sometimes nothing happens ...

Because of the content it's often less noticeable. Longer streams which are not quickly cached entirely may also help to reproduce. - Or it's just me ;-)

@gkatsev feel free to close because from my perspective this is still wonky in native itself.
