### ISSUE TITLE
Very huge bundle size with Wepback (4Mb)

### ISSUE THREAD

**Issue by issimissimo** [videojs/video.js#7536]
## Description
Hello, I've donwloaded the last version of VideoJS through NPM.

If I import the whole classname in this way:
import videojs from 'video.js'
my bundle size in development mode is 4Mb!

module.exports = {
    mode: 'development',
    ....

So, I've looked around and I've seen that I can import just the core, with HLS support (and not VTT), so I've tried to import it in my app in this way:
import videojs from "video.js/dist/alt/video.novtt"

But, when I make a build (minified), the bundle size is still huge 2MB!!!

## Steps to reproduce
1. npm install --save-dev video.js
2. import videojs from "video.js/dist/alt/video.novtt";
3. npm run build (development mode)
4. the bundle is 2Mb!

### Expected
A bundle size at least less that 1Mb

**Comment by issimissimo** [comment]
solved.
Just recrecreated a new webback prj from scratch.
Actually the full namespace in dev mode is 2Mb, in production 500Kb

**Comment by gkatsev** [comment]
Yeah, unfortunately, Video.js isn't the smallest library. It's definitely worth auditing your webpack bundle every so often to make sure that things aren't being included multiple times. I would also recommend looking into lazy loading Video.js after the page has loaded to increase page load time.
