### ISSUE TITLE
Hide time tooltip (not vjs-time-tooltip)

### ISSUE THREAD

**Issue by adhamfarrag** [videojs/video.js#7541]
## Description

I'm trying to hide this tooltip, tried to know the name, inspect. search for `tooltip` keyword but found nothing so far.

<img width="146" alt="Screen Shot 2021-11-26 at 6 15 58 PM" src="https://user-images.githubusercontent.com/23562275/143565123-9fa80061-f8b2-4bfa-9685-7bdb81a8824a.png">

Thanks.

## Additional Information
Please include any additional information necessary here. Including the following:

**Comment by phloxic** [comment]
There are actually 2 tooltips when you hover over the player. I think you mean the one which displays the time of the mouse position:

```js
videojs('player', {
  // config goes here
  controlBar: {
    progressControl: {
      seekBar: {
        mouseTimeDisplay: false
      }
    }
  }
});
```

**Comment by adhamfarrag** [comment]
Thanks @phloxic
