### ISSUE TITLE
bigPlayButton doesn't work or gives error

### ISSUE THREAD

**Issue by adhamfarrag** [videojs/video.js#7543]
## Description
I'm trying to show the bigPlayButton when player is paused. Using Vue.js I firstly tried using `player.on` using this snippet

```js
    this.player.on('pause', function () {
      this.bigPlayButton.show()
      console.log('show')
    })

    this.player.on('play', function () {
      console.log('hide')
      this.bigPlayButton.hide()
    })
```

log functions work, but icons don't show up. 

then tried using a settimeout function to run the method but added `this.player` to it but it gives me this error.

```js
    setTimeout(() => {
      console.log('hello')
      this.player.bigPlayButton.show()
    }, 5000)
```
<img width="707" alt="Screen Shot 2021-11-26 at 10 38 46 PM" src="https://user-images.githubusercontent.com/23562275/143596880-1f9db9a3-5568-4cb3-8e0b-82a251d3c608.png">

#### videojs : 7.15.4

**Comment by mister-ben** [comment]
Unfortunately `show()` and `hide()` don't work in all case as different rules are hiding the element. For this case in particular, you can add a `vjs-show-big-play-button-on-pause` class to the player.

**Comment by adhamfarrag** [comment]
Thanks @mister-ben
