### ISSUE TITLE
Plugin for all time view count?

### ISSUE THREAD

**Issue by markhv-code** [videojs/video.js#7552]
I have a portal website made via the Gallery module in BrightCove.
I would like some way to display the all time view count for the video. I saw there was one way in the brightcove docs but it seemed complicated with making an authenticated request through a proxy server. I was wondering if there could be a plugin?
Do you have any experience in this or any recommendations? Thank you for your time.

**Comment by gkatsev** [comment]
Unfortunately, video.js doesn't and cannot provide a view count thing. It shouldn't be too hard to make a component that can display a number, but you'll need to be able to make a call to your backend to know what the view count is, as it isn't something that Video.js could possibly have access to.
Your best bet may be to contact Brightcove support to ask for some direction.
Thanks.
