### ISSUE TITLE
Audio Described displayed next the AD icon

### ISSUE THREAD

**Issue by amtins** [videojs/video.js#7556]
## Description
![ad-bug](https://user-images.githubusercontent.com/34163393/144909039-8bd472a4-ab72-40dd-8451-d51fd24338bd.png)

## Steps to reproduce
1. Open [https://videojs-http-streaming.netlify.app](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=true&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=false&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Felephantsdream%2Fhls%2Fed_hd.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&override-native=true&preload=auto&mirror-source=true)
2. Start the playback
3. Click on the audio track icon

### Expected
The `Audio Described` should not be displayed.

### Actual
The `Audio Described` is displayed next the AD icon.

## Additional Information

Maybe something wrong here [v7.14.3...v7.15.0](https://github.com/videojs/video.js/compare/v7.14.3...v7.15.0#diff-9fd94576fe3b609171a426feb961b0954d70c8c14e598024d49ae9c8836a71caR67-R78)

#### videojs
Since version 7.15.0. Version 7.14.3 it works like a charm.

**Comment by gkatsev** [comment]
Thanks for the issue. It's likely related to https://github.com/videojs/video.js/pull/7337. I thought I went through and verified everything, but I guess I missed a use case.

**Comment by gkatsev** [comment]
Have a fix here https://github.com/videojs/video.js/pull/7559
