### ISSUE TITLE
Detect user preference for closed captions

### ISSUE THREAD

**Issue by DusanMilko** [videojs/video.js#7558]
Add ability to detect user preference for whether closed captions should be enabled by default or not

**Comment by gkatsev** [comment]
What type of user preference are you looking for? Personally, I'm not aware of any such user preferences that are accessible to us. Though, it's worth noting that in a single Video.js session, if a user has selected a particular captions track, Video.js will try and match the language of the originally selected captions track.

**Comment by OwenEdwards** [comment]
On iOS, for example, if a user sets the "Reduce Motion" setting in Settings > Accessibility > Motion, then the browser passes that setting to web pages through the [`prefers-reduced-motion` CSS media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion). Similarly, on Windows, macOS, and Android - users can set a preference at a system level, and that preference is conveyed to web pages.

Similarly, the `prefers-color-scheme` media query indicates the user's system-level setting for Dark Mode.

As @gkatsev says, I don't believe there's anything equivalent to that for system-level preferences for closed captions. Those system-level settings _are_ passed to mobile native apps, but not to web pages, as far as I know.

**Comment by DusanMilko** [comment]
Yes, totally understand but videojs seems to be blocking the communication from settings to native video app to apply.
