### ISSUE TITLE
Play button style: is not in the center

### ISSUE THREAD

**Issue by igorhernandez** [videojs/video.js#7562]
## Description
Play button is not in the center, on `_big-play.scss` have a fixed top and left position, what it does the play button stay on the top left corner , on demo site and when are used in html pages.

I have a solution to this to make dynamic, which branch can i open a solution?

![image](https://user-images.githubusercontent.com/46497577/145575685-c468a501-aac1-49de-ba2b-65c422eb5b67.png)

### versions
Actual release version: 7.17.0

**Comment by mister-ben** [comment]
You can add the `vjs-big-play-centered` class to the player for a centred play button.

**Comment by igorhernandez** [comment]
So isn't a bug? it's like this by default? is a litte strange

**Comment by gkatsev** [comment]
The default location of the play button is in the corner. This is to not obscure the poster imagine, which helps entice people to view the video.
In addition, most things about the UI of Video.js is done using HTML and CSS, so, it's very customizable to whatever you want it to be.

**Comment by igorhernandez** [comment]
Oh, okay, thanks for clarification the reason, good week to us my friend.
