### ISSUE TITLE
the duration has '-' , and this is wrong

### ISSUE THREAD

**Issue by qingfengmy** [videojs/video.js#7565]
![图片](https://user-images.githubusercontent.com/4978379/145667600-c26e9a64-390e-4a25-a2c7-20aa6c3c2d99.png)

the video's url is https://sod.bunediy.com/20211112/L57EDNF2/index.m3u8

**Comment by mister-ben** [comment]
It's the remaining time display rather than duration, and this is intentional. There's a separate duration display that is hidden by default which does not count down.

It doesn't seem unreasonable add an option to not show the negative sign on the remaining time display though.
