### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

### ISSUE THREAD

**Issue by woow-wu7** [videojs/video.js#7567]
## Description
It’s no problem to open on the web, but when loading the m3u8 suffix file in the Hybrid environment (iphonex), an error is reported like the title.

## Steps to reproduce
1. [normal work - please click the link](https://1-x--videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2F1256769429.vod2.myqcloud.com%2Fc0ebc744vodtranssh1256769429%2F6d1ed73a5285890813060788698%2Fv.f230.m3u8%3Ft%3D61b9b521%26exper%3D0%26us%3D-1434308%26sign%3D4e6b548c00b6d1438e562d234b96f800&type=application%2Fx-mpegURL)
2. but does not work normally on iphoneX.

### Expected
I would expect to see the video appear in all the tested browsers.

### Actual
Only playing on web desktop

### Error output
- error
  - eruda:27 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
- detail
  - Mt.forEach.n.<computed> | @ | eruda:27
-- | -- | --
  | overrideMethod | @ | react_devtools_backend.js:2540
  | eval | @ | video.es.js:261
  | log.error | @ | video.es.js:449
  | error | @ | video.es.js:25978
  | handleTechError_ | @ | video.es.js:24070
  | eval | @ | video.es.js:23074
  | data.dispatcher | @ | video.es.js:2343
  | error (async) |   |  
  | v.addEventListener | @ | eruda:6
  | t.addEventListener | @ | eruda:27
  | on | @ | video.es.js:2363
  | listen | @ | video.es.js:3153
  | on | @ | video.es.js:3203
  | listen | @ | video.es.js:3155
  | on | @ | video.es.js:3203
  | VhsHandler | @ | video.es.js:53876
  | handleSource | @ | video.es.js:54532
  | _Tech.setSource | @ | video.es.js:9858
  | Html5 | @ | video.es.js:19864
  | loadTech_ | @ | video.es.js:23010
  | src_ | @ | video.es.js:25445
  | eval | @ | video.es.js:25350
  | setSourceHelper | @ | video.es.js:10224
  | setSourceHelper | @ | video.es.js:10226
  | eval | @ | video.es.js:9964
  | eval | @ | video.es.js:5173
  | setTimeout (async) |   |  
  | setTimeout | @ | video.es.js:5168
  | setSource | @ | video.es.js:9963
  | handleSrc_ | @ | video.es.js:25340
  | src | @ | video.es.js:25416
  | MediaLoader | @ | video.es.js:10448
  | addChild | @ | video.es.js:4259
  | handleAdd | @ | video.es.js:4391
  | initChildren | @ | video.es.js:4440
  | Player | @ | video.es.js:22335
  | videojs | @ | video.es.js:27952
  | eval | @ | DetailPlayer.js:85

## v.f230.m3u8 file
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://mama.dxy.com/japi/platform/200920029?edk=CiDmqHXMDibkl2uqApGRc28FE5HQg6p46Nz9WOJPwu9U%2BBCO08TAChiaoOvUBCokMjI1YzEwM2QtNTNjOS00NjFlLTlmOWMtODc1ZTI4MGEyN2M2&fileId=3701925924198082857&keySource=VodBuildInKMS&token=eyJ2aWQiOiIzNzAxOTI1OTI0MTk4MDgyODU3IiwidHMiOjAsImV4cGlyZVRpbWUiOjE2Mzk1NDEyNDA2NzQsInNpZ24iOiJmMWVkNDNlNjZiZjcxNDcxNGRmZTM2NmVkN2NmMzg0OGIyZjUyMmY1In0",IV=0x00000000000000000000000000000000
#EXTINF:10.250000,
v.f230.ts?start=0&end=1411327&type=mpegts&exper=0&sign=dec1ce1a9f5c4ae2c8d1103b2c2c5d4a&t=61b969f8&us=1206118432
#EXTINF:10.500000,
v.f230.ts?start=1411328&end=2782415&type=mpegts&exper=0&sign=dec1ce1a9f5c4ae2c8d1103b2c2c5d4a&t=61b969f8&us=1206118432
#EXT-X-ENDLIST
```

### versions
- "video.js": "^7.14.3"

### what version of videojs does this occur with?
- chrome 96.0.4664.93

### plugins
- PhotoSwipe

**Comment by Kimtho** [comment]
I have the same Issue on iPhone 12 mini running 15.1.1

**Comment by woow-wu7** [comment]
> I have the same Issue on iPhone 12 mini running 15.1.1

Did you solve it? I still need to study this issue again, so I can communicate together.

**Comment by gkatsev** [comment]
I would highly recommend upgrading to latest Video.js/VHS. The 2.x release line of VHS has so many fixes. However, on Safari, we generally play back natively and on iOS, we can only play back natively.
If your stream doesn't play if you put the m3u8 directly into Safari, you need to make sure your stream is fixed.
You'll want to run your stream through apple's mediastreamvalidator and correct any issues it shows.

**Comment by woow-wu7** [comment]
> I would highly recommend upgrading to latest Video.js/VHS. The 2.x release line of VHS has so many fixes. However, on Safari, we generally play back natively and on iOS, we can only play back natively. If your stream doesn't play if you put the m3u8 directly into Safari, you need to make sure your stream is fixed. You'll want to run your stream through apple's mediastreamvalidator and correct any issues it shows.

Have worked hard Oh, Thank you.
