### ISSUE TITLE
videojs not playing encrypted HLS videos, instead hangs

### ISSUE THREAD

**Issue by julesl23** [videojs/video.js#7579]
## Description 
The issue is that videojs does not play encrypted HLS videos.

## Steps to reproduce

1. To reproduce the issue, I include a test Big_Buck_Bunny_1080_10s_1MB.mp4 file.

2. Plus included a test enc.key file containing a 16 byte hex number and its corresponding enc.keyinfo file.

3. With this command, encode the encrypted HLS file:
ffmpeg -i "Big_Buck_Bunny_1080_10s_1MB.mp4" -hls_time 9 -hls_key_info_file enc.keyinfo -hls_playlist_type vod -hls_segment_filename "segmentNo%d.ts" prog_index.m3u8

4. Start up Visual Studio Code Go Live server that's on port 5500.

5. Then open the browser for videojs_issue.html. This contains the videojs player that does not play the encrypted HLS file. Instead there is a spinning cursor and the player hangs.

Here's the html:
```
<head>
  <link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />
</head>

<body>
  <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="1920"
    height="1080"
    data-setup="{}"
  >
    <source src="prog_index.m3u8" type="application/x-mpegURL" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="https://vjs.zencdn.net/7.17.0/video.min.js"></script>
</body>
```

### Expected

I expected to see the encrypted HLS video play in videojs.

### Actual

No error given as videojs just hangs with the spinning cursor.

### Error output
I did try also with a React project, it gives this error message repeatedly in chrome console:
"video.es.js:228 VIDEOJS: WARN: Problem encountered with playlist 0-http://localhost:5500/prog_index.m3u8. Trying again since it is the only playlist."

#### videojs
videojs 7.17.0

#### OSes
Windows 10 Pro 64-bit 20H2

#### browsers
Chrome Version 96.0.4664.110 (Official Build) (64-bit)

### plugins
no videojs plugins other than what's built-in

### others
ffmpeg version 2021-12-20-git-631e31773b-full_build-www.gyan.dev
node v16.13.1
react: ^16.0.0

[videojs_issue.zip](https://github.com/videojs/video.js/files/7769702/videojs_issue.zip)

**Comment by julesl23** [comment]
I ran ffmpeg with:
ffmpeg -i "Big_Buck_Bunny_1080_10s_1MB.mp4" -hls_time 9 -hls_playlist_type vod -hls_segment_filename "segmentNo%d.ts" prog_index.m3u8

Hence with no encryption and the video file plays normally. Confirms something wrong with encryption/decryption

**Comment by julesl23** [comment]
I can confirm looking at chrome console the same error for html (files attached) as for the React version

video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since it is the only playlist.
video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since it is the only playlist.
video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since it is the only playlist.
video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since it is the only playlist.
video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since it is the only playlist.
video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since it is the only playlist.
video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since .
.
.

**Comment by mister-ben** [comment]
The key isn't valid, and Safari native can't play it either. Your enc.key contains the same value you're using IV, but it should be the output of `openssl rand 16` or equivalent.

**Comment by julesl23** [comment]
Hi,
Thanks for pointing out my error. I also made another one with point 3 now corrected; format was mislabelled on a sample download site. I am still unable to play in videojs, but I can confirm that this plays in Chrome with an extension.
Please find test files attached.

1. I have now used openssl rand 16 to produce the enc.key file
2. I have removed the last entry in the enc.key.info as this is optional. The prog.index.m3u8 file now has 0x00 for VI
3. I have replaced the source MP4 file that was previously in HEVC format (not compatible with browsers) with MPEG-4/AVC version

I have confirmed that the hls file(s) produced from ffmpeg plays in Chrome with Play HLS M3u8 extension and...

I am unable to play with videojs, I receive error from Chrome console:
VIDEOJS: WARN: Problem encountered with playlist 0-http://127.0.0.1:5500/prog_index.m3u8. Trying again since it is the only playlist.

[videojs_bug.zip](https://github.com/videojs/video.js/files/7774866/videojs_bug.zip)

**Comment by julesl23** [comment]
This issue is still outstanding. No matter what I try, I can't get videojs to play encrypted HLS content.

**Comment by mister-ben** [comment]
Your last example still has an invalid key. It's 38 bytes, it must be 16 bytes.

**Comment by julesl23** [comment]
> Your last example still has an invalid key. It's 38 bytes, it must be 16 bytes.

Thanks. The `openssl rand 16` command pads a whole bunch of bytes afterwards. A search on internet mentions that it uses PKCS#7 padding.

I wrote a quick utility to output random 16 bytes only and encrypted video plays. Great thanks!

**Comment by cdgriffith** [comment]
Was having this exact same issue, so thank you for figuring it out. All the examples suggest to use `openssl rand 16 > enc.key`. I know you already have a utility and there are 100 ways to do this, but just a quick solution for keygen for anyone else stumbling across it here: 

```
python -c "import os; open('enc.key', 'wb').write(os.urandom(16))"
```
