### ISSUE TITLE
Playback rate menu button not accessible

### ISSUE THREAD

**Issue by AashishAx** [videojs/video.js#7581]
From looking at the docs adding the option `playbackRates` should add the playback rate menu to the control bar but it doesn't seem to work. I even tried adding it by `player.controlBar.addChild('PlaybackRateMenuButton')` but no luck. 

After digging further I found out that the method is working and the above code adds the menu button but has the class `vjs-hidden` so it never shows on the screen. I removed the hidden class through js which works fine on PC but is not clickable on mobile devices.

#### videojs
v7.17.7
### plugins
videojs-youtube v2.0.8

**Comment by AashishAx** [comment]
Update: The button seems to be unresponsive on touch screens. The button is unclickable when you emulate touch screen on browsers

**Comment by amtins** [comment]
If in your configuration you have the combination of properties `responsive` and `playbackRates` and the display size is equal or smaller than `.vjs-layout-small` the menu will not be displayed. This would most likely be the case if the display is in portrait mode. Also, in a non-touch screen, you should have a playback rate menu while in a touch screen, you should only have a button.

For further details, please see the [_adaptative.scss](https://github.com/videojs/video.js/blob/eeda26fbf773b82583d8505799a49caa44aa1942/src/css/components/_adaptive.scss#L30) file and the [DEFAULT_BREAKPOINTS](https://github.com/videojs/video.js/blob/eeda26fbf773b82583d8505799a49caa44aa1942/src/js/player.js#L272) object.
```JavaScript
const options = {
    responsive: true,
    playbackRates: [0.75, 1, 1.25]
};

const player = new videojs('player', options);

//Or if you don't use the options property, after instantiation
//player.playbackRates([0.75, 1, 1.25])
```
I tried the code below and everything seems to work just fine.

Open : https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=true
Then in developer console copy and paste :
```JavaScript 
const youtube = document.createElement('script');    
youtube.async = true;
youtube.defer = 'defer';
youtube.src = 'https://cdnjs.cloudflare.com/ajax/libs/videojs-youtube/2.6.1/Youtube.js';
youtube.type = 'text/javascript';
youtube.onload = ()=> {
player.src({ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"});
player.playbackRates([0.5,1,1.25])
}
document.body.appendChild(youtube);


```

**Comment by AashishAx** [comment]
@amtins defining the playbackrate after the player is ready did work for me [Not sure why defining it through option doesn't work] but the button is still not clickable. The first time I click the playback rate changes to 1.5 and after that it doesn't respond.
I checked my consoles and I'm getting an "Invalid Array Length" error thrown by LoadProgressBar's update method when the video is played. Guessing that's what causing the button to not work as well

**Comment by amtins** [comment]
@AashishAx I managed to get the `Invalid Array Length` error with [videojs-youtube v2.0.8](https://github.com/videojs/videojs-youtube/releases/tag/v2.0.8). However, in my example, I used [videojs-youtube v2.6.1](https://github.com/videojs/videojs-youtube/releases/tag/v2.6.1) which is the latest [version](https://www.npmjs.com/package/videojs-youtube) and seems to work fine. See all the available [tags](https://github.com/videojs/videojs-youtube/tags) for this plugin. If you have the possibility to update the plugin it should solve the problem.

I also noticed that you are using videojs 7.17.7 which I could not find in the available [npm versions](https://www.npmjs.com/package/video.js?activeTab=versions) nor in the [github repo](https://github.com/videojs/video.js/releases).

**Comment by AashishAx** [comment]
@amtins sorry that as a typo on my part that was supposed to be v7.17.0 [latest] 
And for the youtube plugin it looks like if you define the youtube video source in the options of videojs then the `Invalid Array Length` happens and the playback rate menu doesn't work. But if you load the video src after the player is ready like your example then its works fine. Guessing its a bug with the version. I'll try updating to v2.6.1 and see if fixes my issue. Thank you for being so helpful with this.
