### ISSUE TITLE
window npm install error

### ISSUE THREAD

**Issue by zhongshanxian** [videojs/video.js#7590]
## Description
windows developers run npm install in vs code terminal fail with many errors.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. https://github.com/videojs/video.js.git
2. npm install

### Expected
install success.

### Actual
`
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\workspace\video.js\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\workspace\\video.js\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\workspace\video.js\node_modules\node-sass
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

### Error output
If there are any errors at all, please include them here.
`
e:\workspace\video.js\node_modules\nan\nan.h(1064): warning C4996: 'v8::Value::ToString': 被声明为已否决 (编译源文件 ..\src\sass_types\string.cpp) [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
  c:\users\n13522\.node-gyp\12.18.2\include\node\v8.h(2683): note: 参见“v8::Value::ToString”的声明 (编译源文件 ..\src\sass_types\string.cpp)
e:\workspace\video.js\node_modules\nan\nan.h(1855): warning C4996: 'v8::Object::Set': 被声明为已否决 (编译源文件 ..\src\sass_types\string.cpp) [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
  c:\users\n13522\.node-gyp\12.18.2\include\node\v8.h(3498): note: 参见“v8::Object::Set”的声明 (编译源文件 ..\src\sass_types\string.cpp)
e:\workspace\video.js\node_modules\nan\nan.h(1861): warning C4996: 'v8::Object::Set': 被声明为已否决 (编译源文件 ..\src\sass_types\string.cpp) [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
  c:\users\n13522\.node-gyp\12.18.2\include\node\v8.h(3498): note: 参见“v8::Object::Set”的声明 (编译源文件 ..\src\sass_types\string.cpp)
e:\workspace\video.js\node_modules\nan\nan.h(1867): warning C4996: 'v8::Object::Set': 被声明为已否决 (编译源文件 ..\src\sass_types\string.cpp) [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
  c:\users\n13522\.node-gyp\12.18.2\include\node\v8.h(3507): note: 参见“v8::Object::Set”的声明 (编译源文件 ..\src\sass_types\string.cpp)
e:\workspace\video.js\node_modules\nan\nan.h(1873): warning C4996: 'v8::Object::Get': 被声明为已否决 (编译源文件 ..\src\sass_types\string.cpp) [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
  c:\users\n13522\.node-gyp\12.18.2\include\node\v8.h(3553): note: 参见“v8::Object::Get”的声明 (编译源文件 ..\src\sass_types\string.cpp)
e:\workspace\video.js\node_modules\nan\nan.h(1879): warning C4996: 'v8::Object::Get': 被声明为已否决 (编译源文件 ..\src\sass_types\string.cpp) [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
  c:\users\n13522\.node-gyp\12.18.2\include\node\v8.h(3553): note: 参见“v8::Object::Get”的声明 (编译源文件 ..\src\sass_types\string.cpp)
e:\workspace\video.js\node_modules\nan\nan.h(1884): warning C4996: 'v8::Object::Get': 被声明为已否决 (编译源文件 ..\src\sass_types\string.cpp) [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
  c:\users\n13522\.node-gyp\12.18.2\include\node\v8.h(3557): note: 参见“v8::Object::Get”的声明 (编译源文件 ..\src\sass_types\string.cpp)
e:\workspace\video.js\node_modules\nan\nan_object_wrap.h(24): error C2039: “IsNearDeath”: 不是“Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>”的成员 [E:\workspace\video.js\node_modules\node-sass\build\binding.vcxproj]
`

#### videojs
7.4.x
#### browsers
what browser are affected?
#### OSes
win 10
#### npm
6.14.5
#### node
12.18.2

**Comment by mister-ben** [comment]
Have you tried with node 14, the version in [.nvmrc](https://github.com/videojs/video.js/blob/main/.nvmrc)?

**Comment by zhongshanxian** [comment]
> Have you tried with node 14, the version in [.nvmrc](https://github.com/videojs/video.js/blob/main/.nvmrc)?

doesn't work!

`
已用时间 00:00:20.94
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\workspace\video.js\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\workspace\\video.js\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\workspace\video.js\node_modules\node-sass
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by zhongshanxian** [comment]
> Have you tried with node 14, the version in [.nvmrc](https://github.com/videojs/video.js/blob/main/.nvmrc)?

yeap! it works for me by follow steps:

1、delete package-lock.json;
2、npm install with node 14.18.2;

thanks~~
