### ISSUE TITLE
PictureInPicture-Button does not work in Firefox

### ISSUE THREAD

**Issue by soerendohmen** [videojs/video.js#7615]
## Description
PictureInPicture-Button does not work in Firefox 96.0.1 64-Bit on Mac and Windows, even if it is forced to display.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
```
<video
        id="my-player"
        class="video-js"
        controls
        preload="auto"
        poster="//vjs.zencdn.net/v/oceans.png"
        data-setup='{"controlBar": {
        "volumePanel": false,
        "fullscreenToggle": false,
        "remainingTimeDisplay": false,
        "progressControl": false,
        "pictureInPictureToggle": true
      }}'>
  <source src="https://vjs.zencdn.net/v/oceans.mp4" type="video/mp4"></source>
  <source src="https://vjs.zencdn.net/v/oceans.webm" type="video/webm"></source>
  <source src="https://vjs.zencdn.net/v/oceans.ogv" type="video/ogg"></source>
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a
    web browser that
    <a href="https://videojs.com/html5-video-support/" target="_blank">
      supports HTML5 video
    </a>
  </p>
</video>
```

OR

https://videojs.com/city

### Expected
Clickable PiP-Button like in Chrome or at least like in https://videojs.com/advanced?video=disneys-oceans
### Actual
Disabled PiP-Button

### Error output
None

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.10.2
#### browsers
Firefox 96.0.1 64-Bit
#### OSes
Mac, Windows
### plugins
None

**Comment by mister-ben** [comment]
Firefox unfortunately does its own thing with picture in picture. It's not possible to control whether the built in toggle appears, and it hasn't implemented the picture in picture API to be able to have a custom button in Video.js's control bar.

There are notes on when it appears or not at https://firefox-source-docs.mozilla.org/toolkit/components/pictureinpicture/pictureinpicture/index.html#the-picture-in-picture-toggle

**Comment by soerendohmen** [comment]
Thank you for your answer.
As i mentioned above - there is a pip button in the examples even in ff.
https://videojs.com/advanced?video=disneys-oceans
That behaviour would be sufficient.

**Comment by mister-ben** [comment]
That's Firefox's native toggle button. Whether it displays or not is up to Firefox - see the link in the last comment for its criteria.
