### ISSUE TITLE
The dependency xmldom security issue exists in videojs 7.14.3

### ISSUE THREAD

**Issue by ikissz2019** [videojs/video.js#7621]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. npm i video.js@7.14.3
2. Check the xmldom version in package-lock.json

### Expected
The xmldom version is 0.7.0 or later

### Actual
The xmldom version is 0.5.0.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.14.3
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
That was updated in 7.15.3 

https://github.com/videojs/video.js/blob/main/CHANGELOG.md#7153-2021-08-24
