### ISSUE TITLE
Problem when running on Chrome

### ISSUE THREAD

**Issue by ExpertSystemsGroup** [videojs/video.js#7623]
## Description
We used a video.js HLS with AES-128 Encryption by FFMpeg, but it does not work on chrome when it is run under JavaScript modal and it gives errors. this issue not appeared when we used firefox.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. use video.js HLS with AES-128 Encryption by FFMpeg
2. play video by JavaScript modal  on chrome in website or mobile issue appeared "The media could not be loaded, either because the server or network failed or because the format is not supported." and in console "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: 'The media could not be loaded, either because the …rk failed or because the format is not supported.'}"
3.this issue not appeared when we used firefox.

### Error output
1- The media could not be loaded, either because the server or network failed or because the format is not supported.
2-VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: 'The media could not be loaded, either because the …rk failed or because the format is not supported.'}

## Additional Information
this issue not appeared when we used firefox.
### versions
7.18.0
#### videojs
what version of videojs does this occur with?
7.18.0
#### browsers
what browser are affected?
chrome
#### OSes
what platforms (operating systems and devices) are affected?
windows 10  and android
### plugins
 video.js
 HLS 
 AES-128 Encryption 
![WhatsApp Image 2022-01-26 at 11 07 25 AM](https://user-images.githubusercontent.com/89138987/151128612-1ed22bc0-21e9-4e80-859b-0bdf62f5e0a5.jpeg)
![WhatsApp Image 2022-01-26 at 11 07 22 AM](https://user-images.githubusercontent.com/89138987/151128615-012f07c2-19a3-497a-af86-67fb2fdaa11b.jpeg)
![WhatsApp Image 2022-01-26 at 11 23 13 AM](https://user-images.githubusercontent.com/89138987/151128616-2239fbbc-096b-41cb-84eb-46b5954c36d7.jpeg)
![WhatsApp Image 2022-01-26 at 11 23 40 AM](https://user-images.githubusercontent.com/89138987/151128621-7d8f5524-46a7-4690-831a-d6ae5f3ae715.jpeg)
 FFMpeg

**Comment by mister-ben** [comment]
The encoding or hosting of the video will be relevant. Can you add an example?

**Comment by ExpertSystemsGroup** [comment]
hello 
please see this example
https://esg.ayasofyaakademi.com/test/videos

**Comment by ExpertSystemsGroup** [comment]
hello
please see this example
https://esg.ayasofyaakademi.com/test/videos

‫في الأربعاء، 26 يناير 2022 في 11:39 م تمت كتابة ما يلي بواسطة
‪mister-ben‬‏ ***@***.***‬‏>:‬

**Comment by mister-ben** [comment]
The call to `load()`, which calls `load()` on the video element in turn that is causing the problem here. There's almost never a need to call `load()`, Video.js already does that internally if needed.

You should also remove the videojs-contrib-hls.js script, that is an outdated version of the HLS playback engine that is already included in Video.js.

**Comment by ExpertSystemsGroup** [comment]
thank you ... solved
