### ISSUE TITLE
Customize media notifications and playback controls outside the browser

### ISSUE THREAD

**Issue by Hashen110** [videojs/video.js#7626]
[Customize media notifications and playback controls outside the browser](https://www.youtube.com/watch?v=Ft6diPReUAU&ab_channel=GoogleChromeDevelopers)

**Comment by mister-ben** [comment]
There's an implementation of the media session API here: https://github.com/videojs/videojs-media-session

**Comment by Hashen110** [comment]
> There's an implementation of the media session API here: https://github.com/videojs/videojs-media-session

Thanks for the comment
