### ISSUE TITLE
Wrong currentTime at the beginning of the live video

### ISSUE THREAD

**Issue by benesva4** [videojs/video.js#7628]
## Description
Hey, I've run to an issue where live video have strange currentTime() values right from the start. Even at 'loadedmetadata' event. I've made a minimal reproduction in a [Codesandbox](https://codesandbox.io/s/basic-video-js-live-video-wrong-offset-5dwdh?file=/src/VideoJS.js). I've added two streams one which starts at 8, second that starts at around 120. Is it normal? Why is such a thing happening? Thank you very much.

Is it thing of a stream? Or have I configured something badly?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open my example, hit play.

Or: 
1. Create the most basic setup and just pop any of two sources I provided in the example
2. Check currentTime() right after start of the playback.

### Expected
player.currentTime() and even player.liveTracker.liveCurrentTime() both return 0.

### Actual
player.currentTime() and even player.liveTracker.liveCurrentTime() both return non 0 value.
The returned value seems like a multiple of a chunk duration. But it may be coincidence.

### Error output
No visible errors

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs

Latest, but is seems like 6.x is doing the same.

#### browsers
All of them.

#### OSes
Windows/MacOS

### plugins
No additional plugins

**Comment by gkatsev** [comment]
Live streams start from the end of the playlist, 3 target durations from the end. Since your live stream has 5 segments of 4 seconds each and target duration is 4s, the seekable range is only the first two segments, and playback starts at seekable end, which corresponds to 8s.

**Comment by benesva4** [comment]
Well, that seems like a good reason :D Thanks!
