### ISSUE TITLE
Disable mouse seeking on visible control bar

### ISSUE THREAD

**Issue by onetwo12** [videojs/video.js#763]
Is there option for video seeking to be disabled? But the control bar and seek bar to be still visible.

**Comment by Maxooo** [comment]
@rsadwick Your plugin is perfect. Thank you so much !

**Comment by flevizzani** [comment]
@rsadwick is there a way to prevent user seeking / ff / scrubbing until the video has been watched?
I mean: progress is disable while watching the video, but if I am at second 10 I can go back to second 5 and again move ff to second 10... is this possible?
