### ISSUE TITLE
DRM encrypted videos with Azure are not playing only on iPhone & iPad Chrome.

### ISSUE THREAD

**Issue by ravi-kiran-ash** [videojs/video.js#7630]
## Description
DRM encrypted videos with Azure are not playing only on iPhone & iPad Chrome.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. With videojs and videojs-contrib-dash config shown below, videos show error only on iPhone & iPad chrome. Works fine on Android Chrome and Web Chrome browsers.
```
videoPlayer.src({
    src: `${AzureMediaPath}(format=mpd-time-csf,encryption=cenc)`,
    type: 'application/dash+xml',
    keySystemOptions: [
        {
	        name: 'com.widevine.alpha',
	        options: {
		        licenseUrl: `${drmConfig.widevineLicenseUrl}`,
		        httpRequestHeaders: {
			        Authorization: `Bearer=${drmConfig.cencToken}`,
		        },
		        withCredentials: false,
	        }
        }
    ]
});
```

### Expected
Videos play on iPhone & iPad Chrome browser.

### Actual
![image](https://user-images.githubusercontent.com/71669692/152038036-7a6171be-75fb-4ed2-8c8b-3d96e717c8ff.png)

### Error output
Error Code 4. No compatible source was found for this media.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
```
"video.js": "^7.15.4",
"videojs-contrib-dash": "^5.1.0",
```
Note: Also tested with latest `video.js` and `videojs-contrib-dash` versions and still see the issue

#### browsers
what browser are affected?
Only iPhone & iPad Chrome are the issue.

**Comment by mister-ben** [comment]
It's not possible to play DASH on iPhone at all, it does support Media Source Exensions. iPad OS does support MSE so unencypted DASH can be possible, but neither support Widevine. You'd need HLS+Fairplay for DRM on iPhone/iPad.
