### ISSUE TITLE
loading video.js deferred in footer

### ISSUE THREAD

**Issue by bitshiftersgmbh** [videojs/video.js#7631]
## Description
For boosting client performance (PageSpeedInsights metrics) I wanted to load video.js **deferred** in the footer part (right before </body>).
I then renamed `data-setup` in `<video>` tags and wanted to init videojs asynchronously (after all ressources are loaded). 
I use this code inside a `jQuery.each()` recursion:
```
videojs(this, JSON.parse($(this).attr("data-videojs-setup")));
```
I seems to fail whenever I do put the `<script>` **not** in the `<head>`.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Just place the video.js-src at the end of your html page

### Expected
Using video.js with deferred loaded src (because it's big!).

### Actual
When embedding video.js in `<head>` all works nice. As soon as I put it elsewhere neither automatic nor manually coded initialization work.

### Error output
Browser console shows error:
```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

Error appears @ 3rd line in this minified code snippet:
```js
!0 !== window.VIDEOJS_NO_DYNAMIC_STYLE && (this.styleEl_ = xe("vjs-styles-dimensions"),
r = Te(".vjs-styles-defaults"),
(a = Te("head")).insertBefore(this.styleEl_, r ? r.nextSibling : a.firstChild)),
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.17.3
#### browsers
just tested Chrome, expect other browsers to behave equally
#### OSes
Win 10

**Comment by mister-ben** [comment]
When the script is loaded ought not to matter and in this [simple example along the lines you describe](https://codepen.io/mister-ben/pen/JjOKRgL?editors=1001) works, there must be something else to consider. Do you have an example to share?

**Comment by bitshiftersgmbh** [comment]
Hey @mister-ben , thanks for the pen. It works nice even on mobile. And I figured out, that the error only occurs, when `vjs-styles-defaults` class is set initially (beneath `video-js` class). So the error is gone ... I have another issues but its not related to this topic here. So this is solved now. thx again!
