### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media

### ISSUE THREAD

**Issue by raphael10-collab** [videojs/video.js#7636]
With this code (React-Electron-Typescript ) : 

    import VideoJS from './videojs/VideoJS'
    import "videojs-youtube"
    
    function App_C(props) {
      const [url, setUrl] = React.useState("")
    
      const playerRef = React.useRef(null)
    
      React.useEffect(() => {
        setUrl("https://www.youtube.com/watch?v=voFRslp8d60")
      }, [])

      console.log("App_C-url-updated: ", url)
    
      const changeVideoSource = (player) => {
        playerRef.current = player;
        //setUrl('https://www.youtube.com/watch?v=voFRslp8d60')
        player.changeSource(url)
      }
    
      const videoJsOptions = { // lookup the options in the docs for more options
        autoplay: true,
        controls: true,
        responsive: true,
        fluid: true,
        sources: [
          {
          src: 'https://www.youtube.com/watch?v=voFRslp8d60',
          type: 'video/youtube'
          },
          {
            src: '/path/to/video.mp4',
            type: 'video/mp4'
          }
        ]
      }
    
    
      const handlePlayerReady = (player) => {
        playerRef.current = player;
    
        // you can handle player events here
        player.on('waiting', () => {
          console.log('player is waiting');
        });
    
        player.on('dispose', () => {
          console.log('player will dispose');
        });
      };
    
    
        return (
          <div id="outer-container" className='outer-container'>
           <h1>App_C</h1>
    
           <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
    
          </div>
        );
    }
    
    export default App_C;

![image](https://user-images.githubusercontent.com/70313067/152959581-a3f74fe7-7750-4260-a4cb-6a10ba936391.png)

But I get this error message:

![image](https://user-images.githubusercontent.com/70313067/152962059-964b60d0-e698-4937-bb3f-eee9ae716c18.png)

if I want to set the  video`source` to the `url` (a string)  : 

      console.log("App_C-url-updated: ", url)
    
      const changeVideoSource = (player) => {
        playerRef.current = player;
        //setUrl('https://www.youtube.com/watch?v=voFRslp8d60')
        player.changeSource(url)
      }
    
      const videoJsOptions = { // lookup the options in the docs for more options
        autoplay: true,
        controls: true,
        responsive: true,
        fluid: true,
        sources: [
          {
            src: changeVideoSource,
            type: 'video/youtube'
          },
          {
            src: '/path/to/video.mp4',
            type: 'video/mp4'
          }
        ]
      }

Or:

      const videoJsOptions = { // lookup the options in the docs for more options
        autoplay: true,
        controls: true,
        responsive: true,
        fluid: true,
        sources: [
          {
            src: url,
            type: 'video/youtube'
          },
          {
            src: '/path/to/video.mp4',
            type: 'video/mp4'
          }
        ]
      }

Other info:
    
    "react": "^17.0.2"
    "video.js": "^7.17.0"
    "videojs-youtube": "^2.6.1"
    "electron": "^16.0.7"
    node: v16.13.0
    O.S. : Ubuntu 20.04 Desktop

How to make it work?

**Comment by mister-ben** [comment]
It could be the Video.js tech isn't registered properly, or that your `setUrl()` isn't passing the type. It would be easier to tell with a (minmal) live example, e.g. on [codesandbox](https://codesandbox.io/s/adoring-kare-0sfll?file=/src/App.js) or similar.

**Comment by raphael10-collab** [comment]
Hi @mister-ben ! Thanks for helping

    const [url, setUrl] = React.useState("")
    
      React.useEffect(() => {
        setUrl("https://www.youtube.com/watch?v=voFRslp8d60")
      }, [])

The `type` of the `url` passed is `string` 

I'm having some problems in importing modules in `codesandbox` but here I've put all the code: https://codesandbox.io/s/quizzical-yalow-y6g73

**Comment by mister-ben** [comment]
codesandbox seems to be having some problems with dpendencies, looks liek it only works if you explicity add mux.js as a dpe, whcih shouldn't be necessary, and isn't if you build locally. I see they have issues with other packages along those lines.

Irrespective of that there are other issues before it event gets to the player. Probably easier to show an example of it working: https://codesandbox.io/s/video-js-with-youtube-0sfll

Notably - import `videojs-youtube` in the video componwent rather than index.js, and msot importantly when setting the source it **must** be passed to Video.js as an object with a type for the youtube tech to kick in. It will not work with just a URL string.

```
{
        src: "https://www.youtube.com/watch?v=voFRslp8d60",
        type: "video/youtube"
}
```

**Comment by raphael10-collab** [comment]
React.useEffect(() => {
        setUrl("https://www.youtube.com/watch?v=voFRslp8d60")
    
      }, [])

    console.log("App_C-url-updated: ", url)


      const videoJsOptions = {
        autoplay: "muted",
        controls: true,
        responsive: true,
        fluid: true,
        sources: [
          {
            //src: "https://www.youtube.com/watch?v=voFRslp8d60",
            src: url,
            type: "video/youtube"
          }
        ]
      };

![image](https://user-images.githubusercontent.com/70313067/153577415-363d870c-a605-4c0b-aa96-3570f4a40e50.png)



`sources` is an `array` of `objects`, where each `object` , as far as I understand, has this structure:

    {
      src: video_url,   //  What type is `video_url` ? 
      type: "video/youtube"
    }

Setting

          {
            src: url,
            type: "video/youtube"
          }

doesn't work, with `url` is a `string`

What is the `type` of `source.src` ?

**Comment by raphael10-collab** [comment]
@mister-ben 

    import * as React from 'react';
    
    import path from 'path';
    
    import VideoJS from './videojs/VideoJS'
    
    // https://codesandbox.io/s/es96l?file=/src/index.js
    
    function App_C(props) {
    
      const componentIsMounted = React.useRef(true);
    
      const [url, setUrl] = React.useState("")
    
      const playerRef = React.useRef(null)
    
      const videoJsOptions = {
        autoplay: true,
        controls: true,
        responsive: true,
        fluid: true,
        sources: [
          {
            src: "https://www.youtube.com/watch?v=voFRslp8d60",
            type: "video/youtube"
          }
        ]
      };
    
      const handlePlayerReady = (player) => {
        playerRef.current = player;
    
        player.on("waiting", () => {
          console.log("player is waiting");
        });
    
        player.on("dispose", () => {
          console.log("player will dispose");
        });
      };
    
    
      React.useEffect(() => {
        setUrl("https://www.youtube.com/watch?v=nZmO8B9rRik")
      }, [])
    
      console.log("App_C-url-updated-outside: ", url)
    
      console.log('typeof("https://www.youtube.com/watch?v=nZmO8B9rRik"): ', typeof("https://www.youtube.com/watch?v=nZmO8B9rRik"))
      console.log("typeof(url): ", typeof(url))
    
    
      //videoJsOptions.sources[0].src = url
    
      videoJsOptions.sources[0].src = "https://www.youtube.com/watch?v=nZmO8B9rRik"
    
        return (
          <div id="outer-container" className='outer-container'>
           <h1>App_C</h1>
    
          <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
    
          </div>
        );
    }
    
    export default App_C;


Setting `videoJsOptions.sources[0].src = "https://www.youtube.com/watch?v=nZmO8B9rRik"` works :  

![image](https://user-images.githubusercontent.com/70313067/153591731-49384538-dab1-4847-bf9a-ceb8e70787b1.png)

While setting `videoJsOptions.sources[0].src = url` does not work and gives this error:



![image](https://user-images.githubusercontent.com/70313067/153592098-16ad86c9-66c7-4215-afbf-cac7dfd63c7d.png)

`url` and `"https://www.youtube.com/watch?v=nZmO8B9rRik"` are both `string` type : 

    App_C-url-updated-outside:  https://www.youtube.com/watch?v=nZmO8B9rRik
    App_C.tsx:90 typeof("https://www.youtube.com/watch?v=nZmO8B9rRik"):  string
    App_C.tsx:91 typeof(url):  string

So, I do not understand the difference between 

`videoJsOptions.sources[0].src = "https://www.youtube.com/watch?v=nZmO8B9rRik"`

and 

`videoJsOptions.sources[0].src = url`

How to make it work?

**Comment by raphael10-collab** [comment]
Hi @mister-ben !

After few trials, I'm now stuck, and your help is really appreciated.

This is the complete code: 

   import * as React from 'react';
    
    import path from 'path';
    
    import VideoJS from './videojs/VideoJS'
    
    // https://codesandbox.io/s/es96l?file=/src/index.js
    
    
    function App_C(props) {
    
      // @ts-ignore
      window.api.electronIpcOn("window-C-channel", (event, args) => {
        console.log("App_C-args: ", args);
      });
   
      const playerRef = React.useRef(null)
    
      const [url, setUrl] = React.useState("https://www.youtube.com/watch?v=voFRslp8d60") // Seth Meyers video
    
      const videoJsOptions = {
        autoplay: true,
        controls: true,
        responsive: true,
        fluid: true,
        sources: [
          {
            src: url,
            type: "video/youtube"
          }
        ]
      };
    
      const handlePlayerReady = (player) => {
        playerRef.current = player;
    
        player.on("waiting", () => {
          console.log("player is waiting");
        });
    
        player.on("dispose", () => {
          console.log("player will dispose");
        });
      };
    
      React.useEffect(() => {
        // @ts-ignore
        window.api.electronIpcOn("window-C-channel-from-main", (event, args) => {
          console.log("App_C-window-Ch-channel-from-main-args: ", args)
          setUrl(args)
        });
    
        console.log("App_C-url-updated-insideUseEffect: ", url)
        console.log("typeof(url): ", typeof(url))
        console.log('typeof("https://www.youtube.com/watch?v=nZmO8B9rRik"): ', typeof("https://www.youtube.com/watch?v=nZmO8B9rRik")) // Himalayas video
    
        videoJsOptions.sources[0].src = url
    
        //videoJsOptions.sources[0].src = "https://www.youtube.com/watch?v=nZmO8B9rRik"
    
      }, [])
    
        return (
          <div id="outer-container" className='outer-container'>
           <h1>App_C</h1>
    
          <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
    
          </div>
        );
    }
    
    export default App_C;


Setting `videoJsOptions.sources[0].src = url` within the `React.useEffect()` does not change the video display, which is still initially with `const [url, setUrl] = React.useState("https://www.youtube.com/watch?v=voFRslp8d60")`, despite the change showed later : 

    App_C-url-updated-insideUseEffect:  https://www.youtube.com/watch?v=voFRslp8d60

![image](https://user-images.githubusercontent.com/70313067/153614108-b94aeb5e-5dd9-4a0a-8c9b-8b53901e32ab.png)

But both `url` and `"https://www.youtube.com/watch?v=nZmO8B9rRik"` are type `string : 

    typeof(url):  string
    App_C.tsx:61 typeof("https://www.youtube.com/watch?v=nZmO8B9rRik"):  string

**Comment by raphael10-collab** [comment]
SOLVED:

this was the problem.

In VideoJS.jsx : 


      // you can update player here [update player through props]
      const player = playerRef.current;
      player.autoplay(options.autoplay);
      player.src(options.sources);


Thank you for your kind help
