### ISSUE TITLE
Safari 15.x with unmuted autoplay. Video resumes itself.

### ISSUE THREAD

**Issue by tbourigault** [videojs/video.js#7638]
## Description
On Safari 15.x and using unmuted autoplay, pausing the video and scrolling down until the video is out of view will resume the playback.
Example here : https://tbourigault.github.io/video-js-bug-autoplay-safari-15.html

## Steps to reproduce
1. use safari 15.1 or 15.2 on desktop
2. setup Safari to allow autoplay with audio. 
    safari > preferences > auto play > allow all autoplay
3. load the page https://tbourigault.github.io/video-js-bug-autoplay-safari-15.html
4. the video should autoplay, if not refresh a few time
5. pause the video
6. scroll down until the video is not visible

### Expected
The video stays on pause

### Actual
The video unpauses itself

### Error output
No errors in the console

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
bug confirmed on version 7.8.3, 7.17.0 7.18.0
#### browsers
Safari 15.1 & 15.2
#### OSes
Mac Os 11.6.2
### plugins
none

**Comment by gkatsev** [comment]
Seems like a bug in Safari. There's a play request that's coming from the video element itself. Also, if I don't initialize Video.js and add the `autoplay` attribute on the video element, I get the same behavior.

**Comment by tbourigault** [comment]
My bad, sorry.
I confirmed it's from Safari itself.
I have the same bug using html5 video only 
here
https://tbourigault.github.io/HTML-5-video-safari-15.x-autoplay-scrolling-bug.html
Thanks !
