### ISSUE TITLE
Custom decoder tech

### ISSUE THREAD

**Issue by RakshithGB** [videojs/video.js#7648]
Example to add a custom decoder? I understand it needs to be a plugin using Tech, but any documentation regarding how to do this? Tried following available plugins that did something similar but couldn't find it helpful enough. Requesting for a basic documentation on how to do this. I have built the necessary wasm file for the decoder, just wanted some inputs on how to integrate this.

**Comment by freddy-daniel** [comment]
No guide for example tech

**Comment by misteroneill** [comment]
The only real documentation we have for adding a tech is https://videojs.com/guides/tech/ - but a tech may not be what you need. You may need a source handler. You can look at our playback engine for an example: https://github.com/videojs/http-streaming

You may want to read up on Media Source Extensions (MSE): https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API
