### ISSUE TITLE
How to play with `SWF` files with`video.js` ?

### ISSUE THREAD

**Issue by raphael10-collab** [videojs/video.js#7651]
How to play with `SWF` - `Shockwave Flash` files with`video.js` ?

Example: https://cdnapisec.kaltura.com/index.php/kwidget/wid/_1773841/uiconf_id/39954662/entry_id/1_jtybishv?widget_id=1_8apfjfgc

I've found this plugin https://github.com/videojs/video-js-swf
but it's outdated and not anymore maintained

**Comment by gkatsev** [comment]
Adobe Flash has been end-of-lifed and it is **highly** recommended to transcode your videos to something that isn't a SWF. In addition, modern browsers cannot and will refuse to run Flash.

Should you have an environment that should be able to run flash, you should grab https://github.com/videojs/videojs-flash.
