### ISSUE TITLE
Video pop up of Samsung Internet browser not supported with videojs 7.10.1+

### ISSUE THREAD

**Issue by damatri** [videojs/video.js#7656]
## Description
Video pop up of Samsung Internet browser (a sort of PIP) not supported with videojs 7.10.1 and higher. 

## Steps to reproduce

1. Open Samsung Internet browser
2. Make sure video assistant is turned on in settings
3. Go to:
 - https://videojs.com/
 - https://videojs.com/advanced?video=disneys-oceans
4. Play video
5. Click on the right icon that appears in the browser that looks like a pop-up/PIP icon

The video on the main page of videojs does not work and  "This webpage doesn't support support Pop-up player" is shown, the video on the demo page however does work. Because of different videojs versions I am assuming. 

### Expected
To open a pop up/PIP

### Actual
An error message appeared

### Error output
"This webpage doesn't support support Pop-up player"

#### videojs
7.10.1+ 
#### browsers
Samsung Internet browser
#### OSes
Android
### plugins
none

**Comment by damatri** [comment]
Yes this came up after updating, hence the 7.10.1+, on 7.10.0 and before it worked fine. 
And yes it a is a feature of the Samsung Internet browser.

**Comment by damatri** [comment]
Thanks, yes setting `overrideNative` to false makes it work. The default setting for `overrideNative` has always been true? Or is it possible that in some earlier versions of videojs Samsung internet was somehow seen as Safari/iOS? I am just trying to figure out what the possible changes have been from 7.10.0 forward and if it is safe to have the default setting to false (as in if it has been false before it does not matter for our users).

**Comment by misteroneill** [comment]
Also, it should be safe to set `overrideNative: false` in environments where it's needed. As Gary said, the default (`true`) will use MSE-based playback everywhere except Safari/iOS.

I think this one is answered, so I'm going to close it, but please comment/reopen if further information is needed.
