### ISSUE TITLE
Way to force new liveui

### ISSUE THREAD

**Issue by SubJunk** [videojs/video.js#7664]
When I am playing a HLS file that is being built while it is played, sometimes the new liveui disables itself (I guess some threshold isn't met) and it rolls back to the old liveui. It would be great if that didn't happen, even if there was a flag to force it.

**Comment by misteroneill** [comment]
Thanks for the issue! It would be really helpful to have an example of the behavior you're describing because it doesn't sound like something we've seen before.

**Comment by gkatsev** [comment]
Only time I know it's disabled it when a live stream ends and the EXT-X-ENDLIST tag is added to the playlist.

**Comment by SubJunk** [comment]
We ended up writing our server code a different way. It is likely still a bug but it doesn't affect me anymore.
