### ISSUE TITLE
Audio Tracks don't seem to behave according to tutorial, can't set label, language, etc.

### ISSUE THREAD

**Issue by sdasda7777** [videojs/video.js#7667]
## Description
I am trying to use videojs to play file with multiple audio tracks. However, I can't seem to find a way to set track description, or language, or anything, really.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Chrome 98, experimental features enabled
2. Create a page that has video with multiple audio tracks.
3. Try to set label as shown in tutorial (https://docs.videojs.com/tutorial-video-tracks.html)

### Expected
I would expect the label to change, or perhaps some warning, or at least that the object didn't resist modifying.

### Actual
Nothing happens. All tracks still have label that reads "soundhandler".
![image](https://user-images.githubusercontent.com/17746796/156201392-cb448e6d-d7f1-48fd-a024-9bf3c31ac6d8.png)

### Error output
There are no errors, but I'm not sure that is a good sign.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.10.2
#### browsers
Chrome/Edge 98, Firefox doesn't even show the track select icon.
### plugins
No plugins.

**Comment by gkatsev** [comment]
I would recommend using HLS or DASH. It's supported across the board, and they allow you to label the tracks.
Unfortunately, an mp4 or webm with multiple audio tracks isn't recommended. Safari supports mp4s, but other browsers don't really, and there's some funkyness with the experimental audio tracks in Chrome that we haven't gotten around to looking at.

**Comment by sdasda7777** [comment]
I see, I'll look into that, then. Thanks a lot.

**Comment by gkatsev** [comment]
You're welcome.
