### ISSUE TITLE
always cant bind the ready function. is that a problem?

### ISSUE THREAD

**Issue by CorgiTT** [videojs/video.js#7668]
in my project , when i use videojs function to create a new object , and i passed a 'ready' function in params , it is like [office's Doc Demo](https://docs.videojs.com/tutorial-react.html):

```
videojs(videoElement, options, () => {
        console.log("player is ready");
        onReady && onReady(player);
});
```

however , there is nothing errors , but player is cant play.

then , i debug breakpoint from the source code , and found this code , it's always **undefinde** , and skip the flow code where bind the ready function.....

https://github.com/videojs/video.js/blob/774f9e7f459df1df532ddab1b8b20117509c7c1e/src/js/video.js#L135

```
if (player) {
    if (options) {
      log.warn(`Player "${id}" is already initialised. Options will not be applied.`);
    }
    if (ready) {
      player.ready(ready);
    }
    return player;
}
```

so , if it's not a problem , what other methods could bind the ready function ??

**Comment by CorgiTT** [comment]
https://codesandbox.io/s/busy-beaver-obfdo6?file=/src/App.js 

@gkatsev  please check it.

**Comment by CorgiTT** [comment]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/16759949/156992675-6109549a-d9ef-4f9a-a7b6-3114dbc1e639.png">

and i found the video element's id is changed after  the code running...  Is it because this reason? How should I configure it?

**Comment by CorgiTT** [comment]
i think i found the reason. `children: ["bigPlayButton"]` , because of this option , cause the player is not working ,  but why?

**Comment by misteroneill** [comment]
Yeah, it looks like that option could definitely be problematic - it will remove all children _except_ the `bigPlayButton`. Removing that option appears to fix your test case.

I can see how this option could confuse, though. The [default list of child components for the player](https://github.com/videojs/video.js/blob/main/src/js/player.js#L5103-L5114) includes some necessary things like `mediaLoader`.

Why were you specifying this option? Perhaps there's another way to accomplish your goal.
