### ISSUE TITLE
[docs] [typescript] Undocumented 'id' option property

### ISSUE THREAD

**Issue by BrainCrumbz** [videojs/video.js#7670]
## Description
When instantiating a player through a `videojs(...)` call, its `options` input parameter can include an `id` property which will be used as the ID of wrapping div element, as well as a base for the ID of video element. But we could not see this option documented anywhere.

We found out about this feature in issue #5088. Looking at [current source code](https://github.com/videojs/video.js/blob/a80307fe0dda11455451ad17e231f326f467a38c/src/js/player.js#L308), feature still seems to be present. Also running a basic [repro project](https://codesandbox.io/s/videojs-issue-undocumented-id-option-7b0b82), one can see that the passed `id` field is used in DOM.

## Steps to reproduce
1. Open [repro project](https://codesandbox.io/s/videojs-issue-undocumented-id-option-7b0b82)
2. Inspect DOM to see that wrapper div ID attribute is the same as the one passed through options

### Expected
* [Video.js Options Reference page](https://docs.videojs.com/tutorial-options.html) should describe `id` property. Or maybe point to an existing page already describing such property.
* TypeScript `videojs.PlayerOptions` type defined by [@types/video.js](https://www.npmjs.com/package/@types/video.js) NPM package should declare `id` property

### Actual
* Video.js Options Reference page has no mention of such property
* TypeScript compiler complains that `id` property does not exist in `videojs.PlayerOptions`  type

### Error output
None

#### videojs
video.js: 7.17.0  
@types/video.js: 7.3.31

#### browsers
Should not matter. Anyway, tried on Google Chrome

#### OSes
Should not matter. Anyway, tried on Windows 11

### plugins
None

**Comment by mister-ben** [comment]
Yes, it should be documented. The guides are about to be moved so we'll update it once that's complete. We don't manage the typescript defintions; an issue or PR on [their repo](https://github.com/DefinitelyTyped/DefinitelyTyped) would be best.
