### ISSUE TITLE
Tight coupling with controlBar component

### ISSUE THREAD

**Issue by try2beth3b3st** [videojs/video.js#7689]
## Description
We have tight coupling in player.js Class Player method resetControlBarUI_(), when using reset() method. 
ControlBar component may be not exists or exists on another nesting level..
![image](https://user-images.githubusercontent.com/8491566/159703152-937f67e3-37fc-445c-bac1-56568f92ec9c.png)

## Steps to reproduce
Use player.reset() method, when in player object there is no controlBar child/component at property "children"  

### Expected
Reset player instance 

### Actual
We have error

### Error output
![image](https://user-images.githubusercontent.com/8491566/159706521-ded23015-8573-45fd-8e9b-f8aa495efd52.png)

#### videojs
7.17.1
#### browsers
all
#### OSes
all

(Sorry for my bad english)

**Comment by try2beth3b3st** [comment]
> Having a control bar is definitely the default use-case. We probably don't test enough with trying to disable default components. Looks like it's because it's trying to dereference from an undefined object. The solution is likely to add a default value on the line where durationDisplay and remainingTimeDisplay are being destructured.
> 
> ```
> const  { durationDisplay, remainingTimeDisplay } = this.controlBar ?? {};
> ```
> 
> if our build doesn't like `??` we can continue using `||`.
> 
> Are you interesting in submitting a PR?

Yes. But i can't do it now (Have't permissions for push).
![image](https://user-images.githubusercontent.com/8491566/159864100-e72044be-6b65-4892-a3e5-cf5dcce67683.png)

**Comment by mister-ben** [comment]
You'll need to create your own _fork_ of the repo, make your changes in a _branch_, then a pull request to propose the changes from your branch are added to Video.js. There's a quick walkthrough here: https://opensource.com/article/19/7/create-pull-request-github

**Comment by try2beth3b3st** [comment]
Done
