### ISSUE TITLE
Using `window.VIDEOJS_NO_DYNAMIC_STYLE` in React.js

### ISSUE THREAD

**Issue by fcisio** [videojs/video.js#7690]
## Description

Hi, I'm trying to disable the dynamic styles on a react project.

I can't seem to make it work since I use Webpack, not the CDN import.

Can anyone point me in the right direction?

**Comment by misteroneill** [comment]
Unfortunately, as soon as the Video.js script is executed, the `VIDEOJS_NO_DYNAMIC_STYLE` value is referenced.

The easiest workaround today is to include it in your HTML page _before_ your WebPack bundle:

```html
<script>window.VIDEOJS_NO_DYNAMIC_STYLE = true;</script>
<script src="//path/to/bundle.js"></script>
```

The `VIDEOJS_NO_DYNAMIC_STYLE` solution is a bit of a hack and is something we should improve in future versions of Video.js.
