### ISSUE TITLE
Vue-videoJS added actions buttons.

### ISSUE THREAD

**Issue by AlexPG96** [videojs/video.js#7704]
Hello!

I'm currently workingith vue-videoJS library, but i have some problems.

I need to add more buttons in the video bar. I need add live button, vu-meter button, subtitles button and custom info button.

How can i do it? I can't find in the documentation, i'ts very scarce for vue.

Thanks!
Alex.

**Comment by misteroneill** [comment]
We don't know about or support any Vue/Video.js library, but...

- The Live button will appear automatically when the player is playing a livestream.
- Don't know what a vu-meter is...
- Subtitles button will show if there are subtitles tracks available.
- Don't know what a custom info button is...
