### ISSUE TITLE
wrong duration

### ISSUE THREAD

**Issue by zhongshanxian** [videojs/video.js#7709]
## Description
The actual video was only 4 minutes long, but it took more than 13 hours to parse.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. open https://videojs-http-streaming.netlify.app/ tool in chrome
2. https://ksvod.cc.netease.com/record/pushstation/8fa3e88fb5dd39c62d23330514791/hls/8fa3e88fb5dd39c62d23330514791-1649163028-1649163295.m3u8
3. Start playing

### Expected
4 minutes duration

### Actual
13 hours duration

### Error output
nothing

#### videojs
Not sure what client has, we tested with https://videojs-http-streaming.netlify.app/, which is presumably the latest.
#### browsers
Chrome
#### OSes
win 10

**Comment by zhongshanxian** [comment]
see https://github.com/videojs/http-streaming/issues/1266

**Comment by misteroneill** [comment]
Not exactly sure what's going on there, but I'm guessing it's an issue with the stream or content itself.

**Comment by misteroneill** [comment]
Closing this as a duplicate of https://github.com/videojs/http-streaming/issues/1266

**Comment by zhongshanxian** [comment]
But vlc can play this stream normally
