### ISSUE TITLE
"Captions Settings" does not work in safari

### ISSUE THREAD

**Issue by juandav23** [videojs/video.js#7723]
## Description
The "Caption Settings" option menu is not working in Safari Browser in any version 

## Steps to reproduce
For example trying to reproduce this video, the captions settings works in all browser but Safari, and when changing the video.js version does not work neither
https://codepen.io/grbla/pen/xxxZPQm?editors=1010
![Screen Shot 2022-04-13 at 11 36 00 AM](https://user-images.githubusercontent.com/23363951/163229615-18d4f1f0-8e78-4c61-9ba4-bedb468337ae.png)

**Comment by juandav23** [comment]
Thanks,  Indeed  as you said the captions settings in safari work according to the operating system settings

**Comment by dayjobtitus** [comment]
I notice both the native and customized UI is available in Safari for this example player for videojs: https://videojs.com/advanced/?video=bipbop-advanced although the options are much more limited than using this same link on any other browser. Also you can of course hide the customized bar and then right click and show native controls and see that captions/subs also show in the native control bar and also list the very same items that the custom control bar shows. So this was added at some point and is broken maybe?
