### ISSUE TITLE
How to stretch poster image to full width and keep aspect ratio of the image

### ISSUE THREAD

**Issue by pavlexander** [videojs/video.js#7737]
## Description
We have pairs of videos and their respective posters. The poster is always **expected to be of the same aspect ratio as the video** itself. 

Therefore the idea is that poster image is always loaded before the video. The video `preload` option is set to `false`. 

The problem is - `videojs` ignores the aspect ratio of the poster image and is always scaling it down to fit the default aspect 16:9 ratio.

**Is it possible to stretch the poster image to full width, while maintaining the original poster image aspect ratio? (see expected)**

(To elaborate on the problem - I don't like that the `videojs` changes it's size after user clicks on the play button. Video has an aspect ratio of 4:3, but image poster is loaded in AR 16:9, so when users click on play button - the player magically increases in size - fitting the video file aspect ratio, stretching both horizontally and vertically (unlike poster image))

https://user-images.githubusercontent.com/20644772/165305830-583d0596-d291-44bb-8d7c-c0a5f664f2fc.mp4

## Steps to reproduce
Here is the fiddle: https://jsfiddle.net/mu7zohyq/7/
In the fiddle - video is 16:9 AR that is why you don't see the video size changing. I could not find a proper video on the internet of AR 1:1, 4:4, 3:4 or similar. If you have an example of such video please paste a link :)

```html
<!DOCTYPE html>
<html>

  <head>
    <link href="//vjs.zencdn.net/7.10.2/video-js.min.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/7.10.2/video.min.js"></script>
  </head>

  <body>
    <div id="mydiv">
      <video id="vid1" class="video-js vjs-default-skin vjs-big-play-centered vjs-show-big-play-button-on-pause">
      </video>
    </div>
  </body>

</html>
```

```js
var posterImagUrl = "https://dummyimage.com/480x480/bf00bf/ffffff";
var videoUrl = "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4";

var options = {
  "poster": posterImagUrl,
  "sources": [{
    "src": videoUrl,
    "type": "video/mp4"
  }],
  "controlBar": {
    "liveDisplay": true,
    "pictureInPictureToggle": false
  },
  "fluid": true,
  "preload": "none",
  "autoplay": false,
  "controls": true
};

var player = videojs('vid1', options, function onPlayerReady() {
  videojs.log('Your player is ready!');
});

```
### Expected
[![enter image description here][2]][2]

### Actual
[![enter image description here][1]][1]

### Error output
none

## Additional Information

I have tried multiple `CSS` tricks from `stackoverflow` but none of them worked. The closest result is:

```
.vjs-poster {
  background-size: cover !important;
}
```

[![enter image description here][3]][3]

The problem here is that top and bottom areas are cut.

Alternatively, maybe it's possible to set the poster image in `videojs` not as a `background image`, but as a image with `img` tag? I was thinking maybe it would give move css customization options..

#### videojs
`videojs 7.18.1`
#### browsers
Any
#### OSes
Any
### plugins
none

  [1]: https://i.stack.imgur.com/cu1dR.png
  [2]: https://i.stack.imgur.com/tbye7.png
  [3]: https://i.stack.imgur.com/LdLxN.png

**Comment by mister-ben** [comment]
The player will adjust to the video size, with `preload` `none` that won't be known until after the play request.

If you know the aspect ratio, use `"aspectRatio": "1:1"` instead of `"fluid": true`. Alternatively for common aspect ratios there are the classes `vjs-1-1`. See https://videojs.com/guides/layout/#fluid-mode

**Comment by pavlexander** [comment]
okay so the answer is basically there is no known way of achieving this result. I was hoping the video could use the actual poster as a reference for the video size. This could have been a feature of `videojs`. I will close this issue because for now I will try to use the default `video` tag which seems to not suffer from this issue.
