### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by xiaobo1215** [videojs/video.js#7741]
the video src be not supported ，in ios(xs)    mobile phone ; 

https://prod-vedio-1303824005.cos.ap-beijing.myqcloud.com/video/44b928b2-327f-4005-a2c2-1bc60081bd3f.mp4

Please help me ，or tell me why ?    thank you !!!!!!

**Comment by misteroneill** [comment]
Video.js is not involved in MP4 playback - that's entirely on the browser itself.

If you're seeing this error in Safari, it's likely an issue with the content itself (such as an unsupported codec) or [the server hosting the media](https://videojs.com/guides/troubleshooting/#problems-when-hosting-media).

Regardless, this is not something that Video.js can fix.

**Comment by danielehrhardt** [comment]
Same Problem. Without VideoJS it does work.

**Comment by misteroneill** [comment]
This is a really generic error message. If you can provide a reduced test case, that would give us something to look at, but as I said above, Video.js defers to the browser when it comes to MP4 videos.
