### ISSUE TITLE
React 18 StrictMode does not work with typical usage of video.js

### ISSUE THREAD

**Issue by goffioul** [videojs/video.js#7746]
## Description
React 18 StrictMode comes with additional behaviors to prepare for reusable state. In particular, when a component is first mounted, React simulates mount+unmount+mount [1]. A typical integration as described in the guides [2] does not work anymore and lead to the following warning (and no video DOM element present in the page):
```
VIDEOJS: WARN: The element supplied is not included in the DOM
```

The reason is that when React simulates unmount, the video.js `dispose` removes the video element from the DOM, which invalidates the ref that React held.

This is illustrated in the following sandbox: https://codesandbox.io/s/react-videojs-strictmode-kvkk4c

The easy route is for each project to blame the other: react should not simulate mount+unmount+mount, video.js should not remove the DOM element on dispose. But as an application developer, I'm creating this bug in the hope to trigger a discussion between the projects and offer a solution for developers (other than _do not use StrictMode_).

[1] https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode
[2] https://videojs.com/guides/react/

## Steps to reproduce
https://codesandbox.io/s/react-videojs-strictmode-kvkk4c

### Expected
One should still be able to use StrictMode.

### Actual
No video DOM element when using StrictMode.

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
- videojs@7.18.1
- react@18.1.0

**Comment by mister-ben** [comment]
I don't know React well, so don't necessarily understand the implications in React of this approach, but having React render a placeholder element and inserting a `video-js` el into that seems to work. That way Video.js is only manipulating the element inserted into React's remdered element.

https://codesandbox.io/s/react-videojs-strictmode-forked-gkk5eh?file=/src/VideoJS.js

**Comment by gkatsev** [comment]
It's interesting to note that react says this behavior only happens in dev mode and doesn't happen in production mode (which makes sense), though, yeah, it'll be good to figure out what the new best practice is, since ideally, we'd want to support strict-mode long term, even if we say it isn't supported in the short term.

**Comment by thijstriemstra** [comment]
Not being able to use the latest React is a major issue for video.js, I'm surprised this is still open after 3 months.

**Comment by mister-ben** [comment]
Any feedback on the [suggestion above](https://github.com/videojs/video.js/issues/7746#issuecomment-1122801556) could have helped this along. If React's changes are complicating things enough that a package like @jimmycallin's serves better than a quick example, that could become the recommendation.

**Comment by thijstriemstra** [comment]
I'm sorry if I sounded harsh, one of these days.

**Comment by lachieh** [comment]
I came to a similar solution as you, @mister-ben with a slight variation:

In the callback for unmount, I added a check to see if the player is disposed already in case it is destroyed elsewhere. This might be unnecessary to include in the updated react workflow example.

```js
	useEffect(() => {
		const player = playerRef.current
		return () => {
			if (!player || player.isDisposed()) return
			player.dispose()
			playerRef.current = null
		}
	}, [playerRef])
```

**Comment by skreutzberger** [comment]
I can confirm that the solution by @mister-ben is solving the issue. It took me 3h to figure out why Video.js is not working in my Next.js project which uses React 18 Strict Mode.

**Comment by liu-zhi-fei** [comment]
> I don't know React well, so don't necessarily understand the implications in React of this approach, but having React render a placeholder element and inserting a `video-js` el into that seems to work. That way Video.js is only manipulating the element inserted into React's remdered element.
> 
> https://codesandbox.io/s/react-videojs-strictmode-forked-gkk5eh?file=/src/VideoJS.js

I see the use of `document.createElement('video-js')` , video.js suport Web Components?

**Comment by danestves** [comment]
On Remix side this approach is not working 😅 so we have to switch to react@v17

**Comment by JuanIrache** [comment]
> I don't know React well, so don't necessarily understand the implications in React of this approach, but having React render a placeholder element and inserting a `video-js` el into that seems to work. That way Video.js is only manipulating the element inserted into React's remdered element.
> 
> https://codesandbox.io/s/react-videojs-strictmode-forked-gkk5eh?file=/src/VideoJS.js

Thank you. I think this solution should be more prominent somewhere
