### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by purplemur** [videojs/video.js#7770]
### Description

While doing Lighthouse testing I ran across the following message: "Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details."

Just wanted to pass this along in case you were not aware.

### Steps to reproduce

1. Open a site using video.js.
2. Run a Lighthouse Report.
3. Open the Best Practices section of the report.

### What version of Video.js are you using?

7.18.11

### What browser(s) including version(s) does this occur with?

Chrome 101

### What OS(es) and version(s) does this occur with?

Any (found while using Windows 10)

**Comment by mister-ben** [comment]
It's occuring here. We're not actually using it, so nothing would break with its removal. `path` could be added to the exclusions.

https://github.com/videojs/video.js/blob/50ffd57a8e74f978fd942b44d4fbea531eb4f953/src/js/utils/events.js#L116-L128

**Comment by purplemur** [comment]
I dug into this a bit more. It is being used in the minified code, and appears to be part of the URLToolkit script that gets rolled into it. However, looking into that code, it appears this is a false flag as URLToolkit is using their own internal object.path, not the event.path flagged by Google. So, everything is fine.
