### ISSUE TITLE
React examples are broken in guide

### ISSUE THREAD

**Issue by nmalancea** [videojs/video.js#7780]
### Description

There is a variable used before being defined and the example doesn't run.

<img width="985" alt="Screen Shot 2022-05-25 at 1 31 31 PM" src="https://user-images.githubusercontent.com/3107683/170242472-a7785746-32a0-41bc-9c56-ba3d52405562.png">

UPDATE:
The class-based example is also broken, giving the same error, on line 9.
<img width="979" alt="Screen Shot 2022-05-25 at 2 14 18 PM" src="https://user-images.githubusercontent.com/3107683/170249718-8d5a1d1f-abfe-4f5a-8cb8-c0c9a139df29.png">

### Steps to reproduce

1. Load the React example found here https://videojs.com/guides/react. The one with `useEffect`.
2. The page does not load and it errors out with `player is not defined`. It fails on line 26 of the example VideoJS component.

### Errors

player is not defined

### What version of Video.js are you using?

7.19.2

### What browser(s) including version(s) does this occur with?

Brave

### What OS(es) and version(s) does this occur with?

macOS

**Comment by mister-ben** [comment]
See the changes in videojs/videojs.com#149 which should fix that.

The discussion #7746 re newer React strict mode might also be of interest.
