### ISSUE TITLE
Videojs zencdn links don't work as server is not responding

### ISSUE THREAD

**Issue by kowlgi** [videojs/video.js#7793]
[videojs zencdn links](http://vjs.zencdn.net/7.10.2/video.min.js) don't work as zencdn appears to be down. This breaks video playback on webpages that point to videojs on zencdn. 

Zencdn is the official recommended CDN (see videojs README).

For the time being, I've switched to using unpkg for videojs i.e. replaced the zencdn link with this https://unpkg.com/video.js@7.10.2/dist/video.min.js .

**Comment by gkatsev** [comment]
That URL seems to be working for me. Has it started working for you again?
Looks like Fastly has scheduled maintenance through this morning and that could've caused a blip.

**Comment by gkatsev** [comment]
Huh, super weird. I'm not seeing anything else on fastly's status page: https://status.fastly.com/.
Not seeing anything in the dashboard, and it's showing requests succeeding in the UK.

I assume you don't have an unexpected proxy or firewall rule that's blocking this domain/url?

**Comment by TelegimTvProgramacion** [comment]
It's also not getting the current version correctly in the getting started page ( https://videojs.com/getting-started/ ) 
![imagen](https://user-images.githubusercontent.com/61551776/172885226-b38b4551-edfc-4c17-8a86-a2485453e062.png)

**Comment by kowlgi** [comment]
My bad, the server is indeed accessible when I accessed from a different wifi network. I believe parental controls on the home router are responsible for blocking access to zencdn. 

I'll close this issue as it's a problem specific to my wifi network.
