### ISSUE TITLE
Warning in chrome in dev tools : Deprecated Feature Used 

### ISSUE THREAD

**Issue by aviyi** [videojs/video.js#7806]
Open console in Chrome 
Go to issues tab 
The message will appear
"'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details"
Link to repeduce
https://codesandbox.io/s/videojs-examples-es96l

**Comment by mister-ben** [comment]
This was fixed in #7782, released in 7.20.1. We weren't using `Event.path`, but the message was being triggered when event properties were copied.
