### ISSUE TITLE
requestVideoFrameCallback broken for audio players

### ISSUE THREAD

**Issue by joeflateau** [videojs/video.js#7807]
### Description

initializing a videojs object on an <audio> element in a browser that supports requestVideoFrameCallback results in an error because requestVideoFrameCallback is not available on an <audio> element.

### Steps to reproduce

```typescript
const audioPlayer = videojs(document.createElement('audio'));
  audioPlayer.src({
    type: 'application/x-mpegURL',
    src: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
  });
```

### Errors

video.es.js:20691 Uncaught TypeError: this.el_.requestVideoFrameCallback is not a function
    at Html52.requestVideoFrameCallback (video.es.js:20691:23)
    at TextTrack2.startTracking (video.es.js:7972:28)
    at new TextTrack2 (video.es.js:7813:13)
    at new HTMLTrackElement2 (video.es.js:8298:17)
    at Html52.createRemoteTextTrack (video.es.js:9223:12)
    at Html52.createRemoteTextTrack (video.es.js:20826:52)
    at Html52.addRemoteTextTrack (video.es.js:9254:33)
    at Html52.addRemoteTextTrack (video.es.js:20872:63)
    at new MasterPlaylistController2 (video.es.js:51098:40)
    at VhsHandler2.src (video.es.js:54512:38)

### What version of Video.js are you using?

7.19.2

### Video.js plugins used.

none

### What browser(s) including version(s) does this occur with?

Chrome 102

### What OS(es) and version(s) does this occur with?

MacOS 12.4

**Comment by gkatsev** [comment]
Should be fixed in 7.20.1 via https://github.com/videojs/video.js/pull/7778

**Comment by joeflateau** [comment]
my fault, i searched issues but not PRs

**Comment by gkatsev** [comment]
No worries

**Comment by TimmNL** [comment]
With version 7.20.1 I get the exact same error. I've added an example of my code in the following sandbox: https://codesandbox.io/s/zen-rubin-grq8sr

**Comment by joeflateau** [comment]
yeah, i just confirmed it. looks like this.setSource (src/js/tech/html5.js:47) calls requestVideoFrameCallback before src/js/tech/html5.js:117 has a chance to say it's not supported on this element.
