### ISSUE TITLE
play button invalid

### ISSUE THREAD

**Issue by Cashew-wood** [videojs/video.js#7813]
### Description

Clicking the play button in "7.x" version is invalid

It can be used normally in "5.x" version
5.5.3 verion:
https://codepen.io/cashew-wood/pen/ZExzQmQ
7.19.2 verion:
https://codepen.io/cashew-wood/pen/jOzNWeN

### Reduced test case

https://codepen.io/cashew-wood/pen/jOzNWeN

### Steps to reproduce

1.click play button
2.
3.

### Errors

no

### What version of Video.js are you using?

7.19.2/7.20.1

### What browser(s) including version(s) does this occur with?

edge,chrome

### What OS(es) and version(s) does this occur with?

window11

**Comment by gkatsev** [comment]
I'm a bit surprised that Video.js 5 works, I was pretty sure that the src attribute never worked. However, the fix is to use a `<source>` element, which is the documented method for Video.js for setting a source.
```html
  <video id="my-video" class="video-js"  controls preload="auto" width="640" height="264" data-setup="{}">
    <source src="https://www.runoob.com/try/demo_source/movie.ogg" type="video/ogg">
  </video>
```
