### ISSUE TITLE
why play-progress-bar not like mouse-time-display to follow the mousemove ?

### ISSUE THREAD

**Issue by xiongneng** [videojs/video.js#7815]
### Description

when mousemove the ProgressControl ,  mouseTimeDisplay will follow the mousemove, but playProgressBar not. 
We hope that the Dot on the progress bar can also follow the mouse movement in real time

follow are the resource code

    if (mouseTimeDisplay) {
      mouseTimeDisplay.update(seekBarRect, seekBarPoint);
    }

    if (playProgressBar) {
      playProgressBar.update(seekBarRect, seekBar.getProgress());
    }

### Steps to reproduce

1.1
2.
3.
1

### What version of Video.js are you using?

latest

### Video.js plugins used.

no

### What browser(s) including version(s) does this occur with?

chrome100

### What OS(es) and version(s) does this occur with?

mac

**Comment by misteroneill** [comment]
The progress bar indicates the current playhead position, it wouldn't make sense to have it track the mouse position in this way.
