### ISSUE TITLE
How can I force native text tracks on VideoJS

### ISSUE THREAD

**Issue by SimonMinottoSociabble** [videojs/video.js#7817]
### Description

Hello

I have a videojs player (up to date)
I have crossorigin="anonymous" on my video tag

I'm adding remote text tracks using javascript, when the player is ready
const subtitleKind = 'captions';
            const lang2Chars = t.LangCode.substring(0, 2);
            const track = {
                src: t.Url,
                kind: subtitleKind,
                srclang: lang2Chars,
                label: t.LangLabel
            };
            this.vjsPlayer.addRemoteTextTrack(track, true);

My Player is playing HLS, using AES encryption

Some init options : 
options.overrideNative = true;
options.textTrackSettings = false;
options.nativeControlsForTouch = false;

Expected behavior : 
My player should display native text tracks
Instead of that, emulated text tracks are displayed

And... it's not fine, because when I'm using PIP (picture in picture)
Subtitles stays in the player and don't follow the video on the PIP area, because they are emulated

Thanks for your help

### Steps to reproduce

Juste want help / external point of view about text tracks, emulated text tracks and PIP

### What version of Video.js are you using?

7.17.0

### What browser(s) including version(s) does this occur with?

last chrome

### What OS(es) and version(s) does this occur with?

windows 11

**Comment by gkatsev** [comment]
You should set [`html5.nativeTextTracks: true`](https://videojs.com/guides/options/#nativetexttracks) as an option
```js
videojs('vid', {
  html5: {
    nativeTextTracks: true
  }
});
```
