### ISSUE TITLE
ended event not working in WebView(iOS, Android)

### ISSUE THREAD

**Issue by atomsbaza** [videojs/video.js#7831]
### Description

ended event not working in WebView(iOS, Android)

`getStream(): void {`
    `var myPlayer = videojs('myVideo');`
    `myPlayer.ready(function () {`
      `this.on('ended', function () {`
         ` alert("before send data");`
`this.sendData();`
      `})`
    `});`
`}`

When streaming is end Alert popup is not working including it cannot call other functions but it working find on desktop.

### Steps to reproduce

1. Open Application on Andriod or iOS
2. Select streaming content
3. Wait until the streaming end
4. "ended" event should trigger
5.  Alert message on mobile devices 

### What version of Video.js are you using?

7.19.2

### What browser(s) including version(s) does this occur with?

Chrome. Safari

### What OS(es) and version(s) does this occur with?

iOS, Android

**Comment by misteroneill** [comment]
This issue has been open for a while, but we didn't get around to investigating it. If this is still an issue in a current version of Video.js, please open a new ticket.
