### ISSUE TITLE
React - VideoJS DOM element disappear when used with React.useContext hook

### ISSUE THREAD

**Issue by issimissimo** [videojs/video.js#7833]
### Description

When using videojs with React, the functional component (VideoJS) disappear if in the Component that is using VideoJS there's a React "useContext" hook

### Steps to reproduce

1. create a React app, install videojs from npm 
2. follow the official videojs tutorials for React, to create the "VideoJS" functional component, and a 2nd component that will consume it
3. in the 2nd component use "useContext" to inheritate some props or functions from a root Component
4. boom! the videoJs DOM element will disappear

### Errors

VIDEOJS: WARN: The element supplied is not included in the DOM 
    at VideoJS

### What version of Video.js are you using?

latest

### Video.js plugins used.

no plugin

### What browser(s) including version(s) does this occur with?

Chrome

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by Juleseck** [comment]
I'm having the exact same issue

**Comment by issimissimo** [comment]
Yes. I think that the problem is that the useEffetc( ... [playerRef]) is called just after that the component is mounted.
Simply remove
`return () => {
      if (player) {
        player.dispose();
        playerRef.current = null;
      }
    };`
and dispose the player manually

**Comment by JuanIrache** [comment]
> Yes. I think that the problem is that the useEffetc( ... [playerRef]) is called just after that the component is mounted. Simply remove `return () => { if (player) { player.dispose(); playerRef.current = null; } };` and dispose the player manually

Thanks. Removing the cleanup function gets rid of the problem, but do you know where we should dispose of the player instead?

**Comment by misteroneill** [comment]
Our [React and Video.js guide](https://videojs.com/guides/react/) demonstrates a workflow for how to use Video.js with React. There are samples in there on using Video.js with both class components and functional components. Unfortunately, we are generally not React experts and can provide limited advice.

In general, you should only invoke `videojs()` when a component is mounted (i.e. its elements are in the DOM). When a component is unmounted, it should be disposed.
