### ISSUE TITLE
issue with the first start with autoplay in Safari 15.5 (detected on Version 15.5 17613.2.7.1.8)

### ISSUE THREAD

**Issue by Optim** [videojs/video.js#7836]
### Description

the video doesn't auto plays via JS for the first try.
Play options:

```
{
autoplay: false,
  controls: true,
  preload: 'metadata',
  fluid: false,
  liveui: true,
  nativeControlsForTouch: false,
  muted: true,
  fit: true,
}
```
 
the same time, client gets next error in browser Console:

> [Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

### Steps to reproduce

1. const player = VideoJs(element, videoOptions);
2. on hover effect (over element) -> player.play()
3. view error

### Errors

[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

### What version of Video.js are you using?

7.19.2

### Video.js plugins used.

@videojs/http-streaming, @silvermine/videojs-quality-selector

### What browser(s) including version(s) does this occur with?

Safari 15.5

### What OS(es) and version(s) does this occur with?

mac os

**Comment by mister-ben** [comment]
The browser will decide whether the play request is allowed without a user action (a `mouseover` event is not considered a user action). The error is Safari's version of the message that it is blocking playback. It would normally play on Safari if the player is muted as your options suggest, but an individual user's settings can overrde this.

**Comment by misteroneill** [comment]
You might want to check out this blog post: [Autoplay Best Practices with Video.js](https://videojs.com/blog/autoplay-best-practices-with-video-js/)

Regardless, this sounds as if the browser is working as designed.
