### ISSUE TITLE
Unable to play videos uploaded to blogger

### ISSUE THREAD

**Issue by rj686** [videojs/video.js#7844]
This isn't a bug but a feature request. Will it be possible for videojs to fetch links of videos uploaded to blogger blog? Or is there a plugin to do that?

**Comment by KVPasupuleti** [comment]
Hey @rj686,

As you said this is not a bug, you can remove the bug tag on this issue.

And, an issue with better details and explanation is more likely to get an answer from the community.
What do you mean by fetching links of videos?

**Comment by gkatsev** [comment]
Based on the original post, you need to provide a type for Video.js to be able to play properly.
For example `<source src="..." type="video/mp4">`.

Video.js itself does not have any blogger integrations and likely won't be able to create one.

**Comment by mister-ben** [comment]
The video URLs have tokens to prevent this type of usage outisde of their platform. Although the Blogger player is essentially a version of the You Tube player, I don't believe there's a way to embed it eternally so using something like the videojs-youtube tech wouldn't be feasible either.
