### ISSUE TITLE
cant't get the seeking time

### ISSUE THREAD

**Issue by mboussaid** [videojs/video.js#7846]
### Description

hello everyone i'was trying to get the seeking time when click on the progress bar i was trying the getCurrentTime whenever seeking event fired but seems that's getCurrentTime dont match the seeking time that i selected on progress bar.
(if the player was in 1:00 in moved to 2:00 i need to get (2.00) but instead i get (1.00) i'dont like to use the event `seeked` my target is to use the seek start time )
for any idea or solution .

### Steps to reproduce

1.
2.
3.

### What version of Video.js are you using?

latest

### What browser(s) including version(s) does this occur with?

chrome

### What OS(es) and version(s) does this occur with?

any

**Comment by misteroneill** [comment]
This issue has been open for a while, but we didn't get around to investigating it.

The player's `currentTime()` method is the correct one to use here. In cases of seeking, you may need to wait until seeking has stopped (the `seeked` event) to determine the new current time.
