### ISSUE TITLE
fix(lang): Fix spacing for 2 translation keys within lang/fr.json

### ISSUE THREAD

**Issue by tgwittman** [videojs/video.js#7847]
### Description

When implementing video.js's option `language` for `fr`, we noticed that "Picture-in-Picture" wasn't being translated properly. We noticed [#7589](https://github.com/videojs/video.js/pull/7589) introduced this issue within the `fr.json` file.

### Steps to reproduce

1. Follow [language guide](https://videojs.com/guides/languages/#setting-default-player-language) to implement a locale based video.js component with all video controls 
2. Change `language` to be `fr`
3. Build video.js component within html and view "Picture-in-Picture" tooltip

### What version of Video.js are you using?

7.19.2

### What browser(s) including version(s) does this occur with?

103.0.5060.114

### What OS(es) and version(s) does this occur with?

macOS 12.4

**Comment by tgwittman** [comment]
Pull-request is up: https://github.com/videojs/video.js/pull/7848

**Comment by mister-ben** [comment]
Fixed in #7848
