### ISSUE TITLE
Video freezes between second 3 to 6 and forwards playing 

### ISSUE THREAD

**Issue by anschm** [videojs/video.js#7855]
### Description

We are using videojs 7.20.1 in our project. The streaming is done by cloudflare via HLS. If we play some videos with chrome or edge they are freezing between second 3 to 6. After that short freeze the player forwards playing the rest of the video. At the progress bar of the player we see a little gap at second 5. At firefox or safari we don't see this gap, but the video skips some frames between second 3 or 6 and don't freeze.

You can see the behaviour on following link:

https://dillybeeze.de/videos/46b332e2-2309-4a1b-a6e0-ca25494301a2/watch

I markt the gap in this picture (its really small):

![Bildschirmfoto 2022-07-27 um 11 16 47](https://user-images.githubusercontent.com/79454810/181211299-a8cc1e7e-717f-496c-8f76-d60d2767c9ec.png)

### Reduced test case

https://codepen.io/aschm/pen/GRxMydV

### Steps to reproduce

1. Open https://codepen.io/aschm/pen/GRxMydV
2. Watch the video with chrome
3. Video freeze at second 6
4. A gap is at second 5

### Errors

No error displayed

### What version of Video.js are you using?

7.20.1

### Video.js plugins used.

videojs-contrib-quality-levels, videojs-hls-quality-selector, videojs-logo

### What browser(s) including version(s) does this occur with?

Chrome 103.0.5060.134

### What OS(es) and version(s) does this occur with?

Mac and Windows

**Comment by idreaminteractive** [comment]
Hi @anschm - I have a similar issue as well - using Cloudflare Stream with HLS as the source. If you remove the "width" and "height" params from the video tag - the stutter disappears. I also found that using the available Dash or MP4 versions (if you generated a downloadable version) from Stream seemed to work when you change the width + height as well.

Not sure if it helps in your case. While not a solution for the HLS streams - it may be a temporary workaround. I took your codepen and just modified the source tag to be:

`<source src="https://cloudflarestream.com/3fc363339973293d412f5fb14bbde319/manifest/video.mpd" type="application/dash+xml">`

**Comment by suau** [comment]
@anschm I ran across a related issue and believe it is Cloudflare related. Videojs doesn't seem to tolerate errors in playlist files much.
Specifically the `iPad Pro with M1` + `Chrome` will completely freeze and never recover.
Note that it will work file on other iPads, iPhones and if switching to safari.

Did you every find a solution to this other than switching to another library ?

**Comment by poooow** [comment]
Not shure what causes the problem, but I was able to fix it by replacing old cloudflare URL `https://videodelivery.net/{VIDEO_ID}/manifest/video.m3u8` with a new (recommended) one: `https://customer-{CUSTOMER_ID}.cloudflarestream.com/{VIDEO_ID}/manifest/video.m3u8`

**Comment by misteroneill** [comment]
This sort of thing would happen if the player's seekable ranges are incomplete - which it gets from the stream itself. It sounds like this was an issue with the stream and may be resolved by (thanks @poooow) switching to a different CloudFlare stream URL.

If not, please feel free to open a new issue.
