### ISSUE TITLE
Ads issue in videoplayer

### ISSUE THREAD

**Issue by dev-issue** [videojs/video.js#7859]
### Description

Hi Support Team, 

We are from VPlayed OTT solution Platforms. In our OTT Platform using the video.js  We have implemented the unique ADS services and integrated into all the platforms like  Website, Android, iOS, Android tv & Apple tv. The ADS are playing fine in all the platforms.
 We have contacted the LG TV team and enquired about this problem, they are requesting us to check with your support team.

1. Is there any integration guide we are missed to integrated on our React tv?

@. Any additional steps we have to follow for this to acheive these ADS?
Waiting for your positive response..
Thank you

### Steps to reproduce

1. From the Admin Website, we upload any mp4 videos and assign to the respective Subscription plan users, the frontend users will view our uploaded mp4 video clip as ads and then the original content will be played.

2. The same way we tried to implement the React tv platforms like LG & Samsung tv, the respective ADS are not playing on our video player.

### What version of Video.js are you using?

7.2.0

### What browser(s) including version(s) does this occur with?

LG TV model name: 43UK6360PTE   TV software version: 05.40.26

### What OS(es) and version(s) does this occur with?

Linux

**Comment by misteroneill** [comment]
This issue has been open for a while, but we didn't get around to investigating it. If this is still an issue in a current version of Video.js, please open a new ticket with sufficient details including a reduced test case.
