### ISSUE TITLE
Question: Is there a way to set a track name like element in mpd manifests?

### ISSUE THREAD

**Issue by venomone** [videojs/video.js#7870]
Hey folks,

at my MPD file I have a lang="en" element, sadly in VideoJS this is not displayed as "English", instead it's displayed as is and the player simply shows "en" and "de" for example when it comes to language selection. Now I would like to know if there is a track_name like object that I can set in the mpd similar to what I can do in a m3u8 playlist e.g.:

`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="a-4",NAME="English",CHANNELS=2,AUTOSELECT="YES",DEFAULT="NO",LANGUAGE="en",URI="a-aac-en-mp4a.40.2_128000/master.m3u8"`

NAME="English" is what gets displayed in VideoJS and LANGUAGE="en" indicated the actual real language. What's the equivalent in Dash/mpd here?

Thanks in advance

**Comment by venomone** [comment]
Please refer to:

https://stackoverflow.com/questions/73295441/is-there-a-way-to-set-a-track-name-like-element-in-dash-mpd-manifests/73304582#73304582

**Comment by mister-ben** [comment]
A `<Label>` element within the `<AdaptionSet>` is the way to do this, as your linked post. Thanks for closing the loop.

**Comment by venomone** [comment]
@mister-ben 

Basically, there is still an "issue" here... This issue is basically hot fixable, but It's still not right in the end.
Currently, VideoJS does not recognize <Label> elements for Subtitle tracks within a MPD ... You can only really rename the subtitle if you touch the lang="" attribute of a Subtitle track ... To me, this is simply non-sense. Why should it work for Audio but not for a Subtitle track the same way?

**Comment by gkatsev** [comment]
I think we just don't have it implemented in [mpd-parser](https://github.com/videojs/mpd-parser/) because we didn't realize that you could use a Label element at the time.
Not sure if we have much bandwidth to implement this ourselves, but we'd definitely help push through a PR.

**Comment by gkatsev** [comment]
Maybe. There's also the related issue https://github.com/videojs/video.js/issues/6960, which provides some direction on how mpd-parser should get updated (https://github.com/videojs/video.js/issues/6960#issuecomment-733115810)

**Comment by venomone** [comment]
@gkatsev Thx for the reference. I guess this whole fix will only be a few lines of code, as it's already implemented for Audio Tracks.

**Comment by gkatsev** [comment]
yeah, I can't imagine it being too bad to implement, just no one has done it yet for _reasons_.

**Comment by venomone** [comment]
@gkatsev Well I would if I could, but I'm heavily into Python Backend development since years and just started with Angular and Typescript 2 days ago ... :(

Have a fine weekend
