### ISSUE TITLE
Webm doesnt play on iOS

### ISSUE THREAD

**Issue by Tschucki** [videojs/video.js#7872]
### Description

When initializing a Video.js Player inside a Vue Compoenent with a webm/vp8 video the player throws `VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "No compatible source was found for this media."`
This only happens on iOS. On Mac and Windows it works.

I have already tried to provide a video type within the options Object.
I have tried using the sources Array aswell.

### Steps to reproduce

1. Init video.js with a local hosted webm
2.
3.

### Errors

VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "No compatible source was found for this media.

### What version of Video.js are you using?

7.20.1

### Video.js plugins used.

None

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

iOS

**Comment by mister-ben** [comment]
Unfortunately iOS Safari only supports webm for webrtc, not regular playback.
