### ISSUE TITLE
Does Android web browsers support Player's PictureInPicture feature?

### ISSUE THREAD

**Issue by kyojunlee** [videojs/video.js#7878]
### Description

I used the sample page(https://videojs.com/advanced/?video=bipbop-advanced) to test PIP feature on Android web browsers such as Samsung browser and Chrome browser, and PIP button is not visible.

I am wondering if Android web browsers does not support html5 player's PIP feature.

### Reduced test case

https://videojs.com/advanced/?video=bipbop-advanced

### Steps to reproduce

1. Open the page on Android web browsers like Samsung browser or Chrome browser
2. See if PIP is working

### Errors

PIP not working..

### What version of Video.js are you using?

7.12.3

### What browser(s) including version(s) does this occur with?

Android browsers

### What OS(es) and version(s) does this occur with?

Android above Oreo

**Comment by mister-ben** [comment]
Android supports PIP but differently. While playing full screen video, it will go to PIP on the home screen gesture/button.
