### ISSUE TITLE
MultiDRM wiseplay support

### ISSUE THREAD

**Issue by djpav** [videojs/video.js#7881]
### Description

As part of multidrm solution, if we insert widevine/fairplay/playready + wiseplay DRM playlist, we are getting error
`app.e2fde4d78f0b0d78add4.js:50 VIDEOJS: WARN: Problem encountered with playlist 3-https://app.url/stream/playlist/hls/?session=831fe869-df40-440f-bf5b-4c26243327af&stream=hp3500&player=fm3u8cbcs&track=35000256. Invalid HLS key at URL: data:text/plain;base64,AAAAv3Bzc2gAAAAAPV5tNZ... Switching to playlist 2 `

### Steps to reproduce

1. insert in playlist wiseplay playlist url
2. play video

### Errors

`app.e2fde4d78f0b0d78add4.js:50 VIDEOJS: WARN: Problem encountered with playlist 3-https://app.url/stream/playlist/hls/?session=831fe869-df40-440f-bf5b-4c26243327af&stream=hp3500&player=fm3u8cbcs&track=35000256. Invalid HLS key at URL: data:text/plain;base64,AAAAv3Bzc2gAAAAAPV5tNZ... Switching to playlist 2 `

### What version of Video.js are you using?

v7.20.2

### Video.js plugins used.

videojs-contrib-eme

### What browser(s) including version(s) does this occur with?

Chrome Version 104.0.5112.79 (Official Build) (arm64)

### What OS(es) and version(s) does this occur with?

macOS Monterey 12.5.1

### Wiseplay url:
`urn:uuid:3d5e6d35-9b9a-41e8-b843-dd3c6e72c42c`

**Comment by misteroneill** [comment]
Unfortunately, Video.js does not support WisePlay DRM as no major browser supports it.
