### ISSUE TITLE
userActions option not working

### ISSUE THREAD

**Issue by mrassili** [videojs/video.js#7882]
### Description

Hello there!
I'm trying to disable the default click handler using `userActions.click` option but it doesn't seem to work. Here's a reproduction codepen

https://codepen.io/jdejedjed/pen/YzadvzR

### Reduced test case

https://codepen.io/jdejedjed/pen/YzadvzR

### Steps to reproduce

1. click the video
2. the click causes the video to play/pause
3. the click should be disabled

### What version of Video.js are you using?

v7.20.2

### Video.js plugins used.

videojs-youtube

### What browser(s) including version(s) does this occur with?

Chrome 104.0.5112.101

### What OS(es) and version(s) does this occur with?

MacOS 12.3

**Comment by mrassili** [comment]
It works though if using a `mp4` source https://codepen.io/jdejedjed/pen/JjLwBMo?editors=1000

**Comment by gkatsev** [comment]
Your initial example is including a really old version of Video.js in addition to Video.js 7. Also, it doesn't actually set `userActions.click` to false. I updated your example here https://codepen.io/gkatsev/pen/poLqqvm

However, it won't work for youtube because the click event is going through to youtube's iframe, which is handling toggling playback on click in those cases. The youtube-tech doesn't do anything to prevent these clicks as it's trying to be a pretty simple wrapper.

**Comment by mrassili** [comment]
> Your initial example is including a really old version of Video.js in addition to Video.js 7. Also, it doesn't actually set userActions.click to false. I updated your example here https://codepen.io/gkatsev/pen/poLqqvm

Sorry about that, I was playing around with the code.

> However, it won't work for youtube because the click event is going through to youtube's iframe, which is handling toggling playback on click in those cases. The youtube-tech doesn't do anything to prevent these clicks as it's trying to be a pretty simple wrapper

I figured. Then I just used a div to overlap the video.

**Comment by mrassili** [comment]
@gkatsev another issue that I found is when I you unmute the video (on Chrome) the video pauses, and you can't resume it until you mute the video again. This is reproducible on your [codepen](https://codepen.io/gkatsev/pen/poLqqvm)

Any idea why ?

**Comment by mrassili** [comment]
at least in the first time

https://user-images.githubusercontent.com/25288435/185632114-0d1194fe-39dd-427b-b6ea-7c28613d42c0.mov

**Comment by mister-ben** [comment]
Closing as the original question is answered and there's a new issue for the new question.
