### ISSUE TITLE
Does Video.js has any way to set a range ?

### ISSUE THREAD

**Issue by nelson777** [videojs/video.js#7891]
I need a way to set a play range. Say that my video durantion is 01:45:00 minutes long. I want to make the player play only from customizable range, say from 00:07:00 till 01:35:00 (blocking 7 minutes in the start, 10 minutes in the end in this case). I want the user to be able to customize range with a control such as this:

[<img src="https://i.imgur.com/aO2P1S3.png" width="300"/>](https://i.imgur.com/aO2P1S3.png)

Currently I'm using Clappr in my project, but AFAIK it doesn't have a range option, so I'm considering video.js for this module. Does it has this functionality natively or via plug-ins ?

**Comment by mister-ben** [comment]
I've not used it personally, but there's at least one plugin that does that at https://github.com/Ericonaldo/rangeslider-videojs-7.x

**Comment by nelson777** [comment]
Perfect. Thanks.
