### ISSUE TITLE
linkedin videos not supported

### ISSUE THREAD

**Issue by mboussaid** [videojs/video.js#7901]
### Description

seems that it's impossible to play linkedin videos is there is any way for doing this ?!

### Steps to reproduce

1- try to play a linkedin video

### What version of Video.js are you using?

latest

### What browser(s) including version(s) does this occur with?

not related

### What OS(es) and version(s) does this occur with?

not related

**Comment by mister-ben** [comment]
I don't think there's a way to do this, you'd need linkedin to provide a direct link to the video (and a means to reliably get a current URL), or a player embed with a comprehensive API aaround which a tech like videojs-youtube could be built. Most services don't provide either - they want the end user to watch videos on their platform or in a branded player.
