### ISSUE TITLE
In video.js, when the source content type is "audio/mp3", the subtitle of the track is not updated.

### ISSUE THREAD

**Issue by iranika** [videojs/video.js#7910]
### Description

I am trying to add subtitles to audio.
In video.js, when the source content type is "audio/mp3", the subtitle of the track is not updated.

We have prepared a Demo page.

Demo page.
https://iranika.github.io/videojs-debug/

Souce Code.
https://github.com/iranika/videojs-debug

What is interesting is that when you change the caption or operate the fullscrean, the subtitle will be displayed.
However, the subtitle is not updated.
In Chrome. ( Firefox is not occurred.)
It's not detecting the cuechange Event, i think well...

Is this a bug?

### Reduced test case

https://github.com/iranika/videojs-debug

### Steps to reproduce

Demo page.
https://iranika.github.io/videojs-debug/

Souce Code.
https://github.com/iranika/videojs-debug

### What version of Video.js are you using?

latest 7.10.2

### What browser(s) including version(s) does this occur with?

Chrome 105.0.5195.53

### What OS(es) and version(s) does this occur with?

Windows11

**Comment by locpd** [comment]
After updating from 7.9.7 to 7.20.2, I also experience this problem of subtitle not updating on Samsung TV (Tizen OS). When I switched subtitle for a video with multiple subtitles, the current cue would show (if there was an active one) and it just stayed there forever, switching to another subtitle and the same thing happened. I think it has something to do with the 'cuechange' event.

**Comment by mister-ben** [comment]
It's to do with using `requestVideoFrameCallback` and `requestAnaimationFrame` for more precise and reliable cues than can be achieved `timeupdate`. Although we don't use `requestVideoFrameCallback` with audio elements, an audio-only source in a video element as in the example won't trigger any frame updates.

The video on Samsung doesn't really make sense, but TVs do do strange things. I think we'll just have to use `timeupdate` for cues as well to cover all the edge cases.

**Comment by iranika** [comment]
Problem solved :)
Good job, and thanks!

**Comment by locpd** [comment]
I can confirm subtitle now works again on Samsung TV, and Sony TV too.

**Comment by yassinox1234** [comment]
Hello
Does anyone have a good iptv player app for samsung tv that can play subtitles too, all apps i've tried on my samsung don't play subtitles at all
