### ISSUE TITLE
Chrome 105: Uncaught DOMException: Failed to read the ‘handle’ property from ‘MediaSource’: MediaSourceHandle creation is currently supported only in a dedicated worker.

### ISSUE THREAD

**Issue by nick-myers-dt** [videojs/video.js#7911]
### Description

Release of Chrome 105 appears to have "broken" something.
https://bugs.chromium.org/p/chromium/issues/detail?id=1358918&q=MediaSourceHandle&can=2

### Reduced test case

https://videojs.github.io/videojs-contrib-hls/

### Steps to reproduce

1. Go to https://videojs.github.io/videojs-contrib-hls/ in using Chrome 105.0.5195.52
2. Open developer console
3. See error: Uncaught DOMException: Failed to read the ‘handle’ property from ‘MediaSource’: MediaSourceHandle creation is currently supported only in a dedicated worker.

### Errors

Uncaught DOMException: Failed to read the ‘handle’ property from ‘MediaSource’: MediaSourceHandle creation is currently supported only in a dedicated worker.

### What version of Video.js are you using?

7.8.4

### What browser(s) including version(s) does this occur with?

Chrome 105.0.5195.52

### What OS(es) and version(s) does this occur with?

Mac OS, Windows 10

**Comment by nick-myers-dt** [comment]
FYI - we're using:

"video.js": "^7.8.2",
"videojs-contrib-eme": "^3.7.0",
"videojs-hotkeys": "^0.2.27"

and are looking at updating to:

"video.js": "^7.20.2",
"videojs-contrib-eme": "^5.0.1",
"videojs-hotkeys": "^0.2.28"

To see if this resolves the issue.

**Comment by nick-myers-dt** [comment]
Closing as this is already reported here: https://github.com/videojs/video.js/issues/7905

**Comment by jgreen01su** [comment]
I'm seeing this issue in the Chrome Beta _106.0.5249.21_.

**Comment by gkatsev** [comment]
@jgreen01su please update your version of Video.js to latest (or newer than 7.10.x)

**Comment by gkatsev** [comment]
Let have all discussions related to this issue in #7905
