### ISSUE TITLE
Installing Video.js plugin (rangeslider-videojs) that don't have a npm package in Angular

### ISSUE THREAD

**Issue by nelson777** [videojs/video.js#7912]
Hello, I'm trying to install rangeslider plugin on an Angular project. I have searched some sites that show how to integrate with Angular, but they all start by installing the npm package of the plugin. Examples:

https://github.com/videojs/video.js/issues/6747
https://github.com/videojs/video.js/issues/4942

Now AFAIK the plugin I want to install doesn't have an npm package. This is the link to it:

https://github.com/Ericonaldo/rangeslider-videojs-7.x

It's also a fork of a fork that doesn't have issues enabled in the project. That's why I couldn't ask there. 
How would I install this on an Angular project ?

Any help appreciated. Thanks.

**Comment by nelson777** [comment]
I'm having a hard time Rangeslider plugin in Angular 13. The problem is that the rangeslider code expects a global videojs variable to be available and alters it's prototype. 

So at the moment videojs is provided by an import in my component: 

    import videojs from 'video.js';

And I start videojs with this code in AfterViewInit:

	this.player = videojs(this.myVideoComponent.nativeElement, this.config, () => {
		console.log('player ready!');
	});

Now AFAIK Rangeslider plug in (https://github.com/Ericonaldo/rangeslider-videojs-7.x) doesn't have a npm package available, so I download it and imported as a normal file within my project:

    import RangeSlider from 'src/app/shared/rangeslider-videojs';

This created the error `videojs not found`, because videojs isn't global and not even initialized;

So to be able to have videojs initialized it has to be in AfterViewInit after the initialization code mentioned above. So I tried all this: 

    let RangeSlider = require('src/app/shared/rangeslider-videojs');

    let RangeSlider = require('src/app/shared/rangeslider-videojs')(videojs, {});

    this.player.bind(require('src/app/shared/rangeslider-videojs'));

    window['videojs'] = require('src/app/shared/rangeslider-videojs');

With equal results.
I CAN put videojs and rangeslider files directly in root dir and use `<script>` tags to load it the hard way. But that would be so ugly I'm very relutant in doing it.

Anyone knows a way to load rangeslider plugin on an Angular component ?

**Comment by mister-ben** [comment]
Answered at https://stackoverflow.com/questions/73620828/how-do-i-install-video-jss-rangeslider-plugin-on-angular-13
