### ISSUE TITLE
WARN: Problem encountered with playlist 0-http://******** Trying again since it is the only playlist.

### ISSUE THREAD

**Issue by siamyolo55** [videojs/video.js#7914]
### Description

I'm streaming an android device screen from a v4l2 device using ffmpeg on my linux. After creating the endpoint, when I hit the endpoint, download starts and after ending the stream I get a mpeg-2 (video/mp4) file. Now I'm trying to open this on my chrome browser with videojs. 

`<video id="myplayer" class="video-js vjs-fluid" controls preload="auto" data-setup='{}' autoplay> 
    <source src="http://*****" type="application/x-mpegURL"> ``
</video>`

This is the log I'm getting from browser:
WARN: Problem encountered with playlist 0-http://******** Trying again since it is the only playlist.

What am I doing wrong?

### Steps to reproduce

...

### Errors

This is the log I'm getting from browser:
WARN: Problem encountered with playlist 0-http://******** Trying again since it is the only playlist.

### What version of Video.js are you using?

7.20.2

### Video.js plugins used.

None

### What browser(s) including version(s) does this occur with?

104.0.5112.101

### What OS(es) and version(s) does this occur with?

Ubuntu 20.02

**Comment by pocketChao** [comment]
did they fixed this problem ?

**Comment by 18BQ1A05G8** [comment]
any updates?

**Comment by keepgagaga** [comment]
same problem

**Comment by mister-ben** [comment]
Closing this issue as it is not useful. Without a reproducible case there is no information to give other than what is already in the error message. Somebody may be able to give more guidance on why the error occurs with a particular stream if an issue is opened on the [http-streaming repository](https://github.com/videojs/http-streaming/issues/new) with **the stream that triggers the error** and any other steps needed to reproduce.
