### ISSUE TITLE
m3u8 playlist with relative URL doesn't play in a video.js player

### ISSUE THREAD

**Issue by ExperiBass** [videojs/video.js#7916]
### Description

When attempting to play a stream from a m3u8 playlist with relative URLs, Video.JS fails. For example, the Canada One stream (at `http://cdn8.live247stream.com/canadaone/tv/playlist.m3u8`) contains (as of this issue):
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2852684,RESOLUTION=1280x720,CODECS="avc1.42c01f,mp4a.40.2"
canadaone/stream1/chunks.m3u8?nimblesessionid=2327180541
```
It seems like Video.JS doesnt know what to do with the last line and fails. A working stream is the NASA stream (over at `https://uplynkcontent.sinclairstoryline.com/channel/ddd76fdc1c0a456ba537e4f48e827d3e.m3u8`). It contains:
```
#EXTM3U
// metadata removed
#EXT-X-STREAM-INF:RESOLUTION=416x234,BANDWIDTH=435851,CODECS="mp4a.40.5,avc1.42000d",FRAME-RATE=30.000,AUDIO="aac",CLOSED-CAPTIONS="ccs",AVERAGE-BANDWIDTH=416413
https://content-ausw2-up-1.uplynk.com/channel/ddd76fdc1c0a456ba537e4f48e827d3e/d.m3u8?pbs=82c1a28024534923a39d184a8c273fb6
// other streams
```
as you can see, it contains a full URL.

### Reduced test case

https://codepen.io/experibass/pen/qBYdNoE

### Steps to reproduce

1. find a stream with relative urls.
2. attempt to play it.
3. profit(?)

### What version of Video.js are you using?

7.10.2

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

iOS 15.4.1

**Comment by mister-ben** [comment]
It doesn't run on codepen becuase it's http on an https page. That stream plays on an http page.

**Comment by ExperiBass** [comment]
> It doesn't run on codepen becuase it's http on an https page. That stream plays on an http page.

codepen was only to hold the code, i probably shouldve thrown it in a gist. You may still be correct though, i'll test again and see if something is implying https. Thanks!
