### ISSUE TITLE
how to hide pip when fullscreen ?

### ISSUE THREAD

**Issue by febrimaulana** [videojs/video.js#7921]
### Description

how to hide pip when fullscreen ?
![image](https://user-images.githubusercontent.com/30101915/189288986-d5f87459-cb4a-4aff-b6a1-4f7451403759.png)

### Steps to reproduce

1. click pip on video
2. click fullscreen on the video while pip is still active

### What version of Video.js are you using?

v7.20.1

### Video.js plugins used.

https://vjs.zencdn.net/7.20.1/video.min.js

### What browser(s) including version(s) does this occur with?

chrome

**Comment by mister-ben** [comment]
You can exit pip when entering fullscreen like this

```js
player.on('fullscreenchange', function() {
    if (player.isFullscreen() && player.isInPictureInPicture()) {
        player.exitPictureInPicture();
    }
});
```

**Comment by mister-ben** [comment]
This should be a default behaviour, a native video element will exit PIP on entering fullscreen

**Comment by Walexero** [comment]
Is anyone interested in working on the issue, if not, i would be interested on working on it and would also need guidance on how to go about it

**Comment by onigetoc** [comment]
For myself, I also want to remove/hide pip on mobile, it do nothing except on my tablet where the video view disappear and is not showing anywhere.

**Comment by lalitkumawat1m** [comment]
I want to work on this issue could you please assign to me ?
