### ISSUE TITLE
[BUG] VideoJS not show menu audio if have same audio label

### ISSUE THREAD

**Issue by jazz1611** [videojs/video.js#7925]
### Description

```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="English",DEFAULT=YES,AUTOSELECT=YES,URI="1080/audio/0.m3u8?token=2651ce7cd8e76feeca55231e8cf8a6c5"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="English",DEFAULT=NO,AUTOSELECT=YES,URI="1080/audio/1.m3u8?token=2651ce7cd8e76feeca55231e8cf8a6c5"
#EXT-X-STREAM-INF:BANDWIDTH=508075,RESOLUTION=720x480,AUDIO="audio"
480.m3u8?token=2651ce7cd8e76feeca55231e8cf8a6c5
#EXT-X-STREAM-INF:BANDWIDTH=880851,RESOLUTION=1280x720,AUDIO="audio"
720.m3u8?token=2651ce7cd8e76feeca55231e8cf8a6c5
#EXT-X-STREAM-INF:BANDWIDTH=1516499,RESOLUTION=1920x1080,AUDIO="audio"
1080.m3u8?token=2651ce7cd8e76feeca55231e8cf8a6c5
```

### Steps to reproduce

Hello,

the VideoJS not show menu audio if have same audio label (example: English in my case). you can add 2 audio track with same English language and convert to HLS m3u8 by ffmpeg. then try playing in VideoJS

### Errors

![image](https://user-images.githubusercontent.com/1846222/189539422-05acfbed-70de-4fc9-8484-4cc9c8f6ade7.png)

![image](https://user-images.githubusercontent.com/1846222/189539368-6c91ccfe-4d2e-4aa5-9178-b77d24e4128a.png)

### What version of Video.js are you using?

7.20.3

### What browser(s) including version(s) does this occur with?

Firefox 104.0.2 (64-bit), Chrome 105.0.5195.102 (Official Build) (64-bit)

### What OS(es) and version(s) does this occur with?

Windows 11 Pro for Workstations 21H2

**Comment by mister-ben** [comment]
Safari native/Quicktime will behave the same, not show two English tracks to choose from. If you've alternate tracks [the `NAME` must be district](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.6.1.1), such as "English" and "English (commentary)".
