### ISSUE TITLE
Videojs not working well on laptop but works well on android

### ISSUE THREAD

**Issue by alexander01202** [videojs/video.js#7934]
Hello. I am using videojs obviously and I just came across this error.

I am able to successfully load/attach different sources and links to videojs and I can verify that when I open up chrome developer tools however I am not able to change to those sources, i.e, I do see the option to change to the sources but It doesn't work. I click on the label source and it doesn't change. Note that this doesn't occur on my android phone(chrome browser also). Every thing works so well on my android. I am also not able to see the caption/subtitles that was given to the video on laptop/desktop. I get the option to enable/disable the caption and I set it to enabled but it still doesn't work. It's like no setting is applied at all in the controls area. Also my play button stays at the default play button i.e it doesn't change to pause or play when clicked. It just remains at the initial play button, I am not talking about the big centered play button that disappears when video is playing. Also I am not able to see the video length. It just stays at 0:00 even when the video has been loaded. All these issues don't occur on my android phone. 
**What could be the cause of the problem??**

**Comment by gkatsev** [comment]
Can you create a minimal live test page? We're unlikely to be able to help without being able to reproduce the issue.

**Comment by alexander01202** [comment]
Thank you for your response. I however have seen the issue. I was loading empty source in my javascript file like so:
`player.src([
    {
      src: '',
      type: 'video/mp4',
      label: '1080P',
  },
  {
      src: '',
      type: 'video/mp4',
      label: '720P',
  },
  {
      src: '',
      type: 'video/mp4',
      label: '480P',
      selected: true,
  },
]);`

Commenting this out fixed the problem
