### ISSUE TITLE
Content shift when video is loading

### ISSUE THREAD

**Issue by kimvuVarner** [videojs/video.js#7947]
### Description

while loading it appear a black square which has more height than the orignal video. This causes a layout shift which i don't want
![image](https://user-images.githubusercontent.com/89914537/193537781-67ad47dd-3d6c-4e32-900c-6fa6d6456b91.png)
thevideo:
![image](https://user-images.githubusercontent.com/89914537/193537853-90b7fdf9-4360-4bcc-b0e4-4b372d97fa57.png)

I believe this is because of 
the padding-top beeing first 56.25% then changed to 41.66% once the video is loaded

![image](https://user-images.githubusercontent.com/89914537/193538258-8935c2cc-34b4-4a67-b79e-9823748b2bad.png)

Is there a way to have no padding or use the 41.66% straight away?

### Reduced test case

https://videojs.com/advanced/?video=disneys-oceans

### Steps to reproduce

1. just refresh the page and you'll see a big black square which has more height than the original source

### What version of Video.js are you using?

7.3.46 (guessing the newest is used on the website)

### What browser(s) including version(s) does this occur with?

Chrome 106.0.5249.62

### What OS(es) and version(s) does this occur with?

Windows 11

**Comment by kimvuVarner** [comment]
found a solution to this: 

`  useEffect(() => {
    const img = new Image();
    if (source) {
      img.src = source;
    }
    img.onload = () => {
      const height = img.height;
      const width = img.width;
      setPaddingTop((height / width) * 100 + '%');
    };
  }, [source]);`

` '& .vjs_video_3-dimensions.vjs-fluid:not(.vjs-audio-only-mode)': {
      paddingTop: paddingTop,
    },`

used the poster image and used its height/width ratio as paddingTop

**Comment by mister-ben** [comment]
Fluid mode adapts the player size to the video size - but the video size isn't known until metadata is loaded. 16:9 is the default if/until the actual video size is known. If you know the aspect ratio you want you can set it as a setup option, e.g. `"aspectRatio": "24:10"`. Note if you use a `<video>`element you might still get shift as the browser's default size for a video will also be 16:9. Using `<video-js>` avoids that.
