### ISSUE TITLE
Volume bar not working in demo video

### ISSUE THREAD

**Issue by E-fais** [videojs/video.js#7948]
### Description

In the videojs website ,volume controller for  demo video is not working.

### Steps to reproduce

1.fix bug
2.
3.

### What version of Video.js are you using?

Latest 

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

Ios

**Comment by mister-ben** [comment]
The volume bar is not displayed on iOS and iPadOS as Safari doesn't allow the volume to be set.
