### ISSUE TITLE
help me how import to web builder wysiwyg..

### ISSUE THREAD

**Issue by manuelsongokuh** [videojs/video.js#7952]
### Description

wysiwygwebbuilder is a software for builder web page,

i need to import to wysiwygwebbuilder, or extension for wysiwygwebbuilder

there is object in wysiwygwebbuilder: html code(html1), so i insert all code of videojs but something not work, example width and height follow by html1, "use <div> to set position and size of the HTML" , instead code of videojs: 

```
<video id="example_video_1" class="video-js" controls preload="none" width="640" height="264" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
<source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4">
<source src="http://vjs.zencdn.net/v/oceans.webm" type="video/webm">
<source src="http://vjs.zencdn.net/v/oceans.ogv" type="video/ogg">
<track kind="captions" src="../shared/example-captions.vtt" srclang="en" label="English">
<track kind="subtitles" src="../shared/example-captions.vtt" srclang="en" label="English">
<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video>
```

width= size of html1 
height= size of html1

not work..

### Steps to reproduce

this is not bug but problem , not work.. with code videojs to wysiwygwebbuilder

### Errors

not work...

### What version of Video.js are you using?

last versione videojs

### Video.js plugins used.

yes

### What browser(s) including version(s) does this occur with?

last firefox , last chrome

### What OS(es) and version(s) does this occur with?

windows 10

**Comment by mister-ben** [comment]
Sorry, not sure what you're trying to do with width and height, but the crux of your issue is possibly not including the script and link tags in your HTML that you're entering into your editor.

https://videojs.com/getting-started/
