### ISSUE TITLE
iOS Playback Rate > 2 -> playbacks only frames

### ISSUE THREAD

**Issue by cagnulein** [videojs/video.js#7961]
### Description

Using the https://videojs.com/ as a reference, on windows I can see smooth video at playback rate of 3 without any issue.
On iOS (tried safari and chrome) the video on 3x is jumping through frames. Is it possible to have smooth playback at 3x even on iOS?
Thanks

### Reduced test case

https://videojs.com/

### Steps to reproduce

1. go to https://videojs.com/ on iOS
2. set the playback rate to 3

### What version of Video.js are you using?

https://videojs.com/

### Video.js plugins used.

https://videojs.com/

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

iOS 16

**Comment by mister-ben** [comment]
Video.js can't influence this behaviour, it's iOS's native playback Video.js sets the playbackRate on the video el; it's then up to Safari/Webkit how it responds to that.

**Comment by cagnulein** [comment]
hah ok, thanks :(
