### ISSUE TITLE
event for browser-permission check 

### ISSUE THREAD

**Issue by straycoders** [videojs/video.js#7975]
I need to execute some codes right after browser-permission check is done but, before `ready` event is fired. Is that possible to achieve? I'm really expecting a handler like: `player.on('browser-permission', function(state){..})` but couldn't find suitable one from the events list. --thank you in advance.

**Comment by mister-ben** [comment]
What do you mean exactly? What permission?

**Comment by straycoders** [comment]
@mister-ben . I apologize, actually I'm using `videojs-record` where browser-permission (for using camera) is involved. Finally realize that your `video.js` doesn't require that. Closing this right away and thank you for your time and atttention.
