### ISSUE TITLE
H.265 (HEVC) support in Android Chrome 107+ HTML5 MSE

### ISSUE THREAD

**Issue by denji** [videojs/video.js#7978]
### Description

* https://bugs.chromium.org/p/chromium/issues/detail?id=460703
* https://caniuse.com/hevc
* https://www.chromium.org/audio-video/#:~:text=codec%20and%20container%20support
* https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop_25.html

### Steps to reproduce

.

### What version of Video.js are you using?

.

### What browser(s) including version(s) does this occur with?

.

### What OS(es) and version(s) does this occur with?

.

**Comment by gkatsev** [comment]
Video.js will support this without any other work assuming that the browser supports it. There's definitely some issues around DMR+HEVC in chrome, but it generally should work.
Take a look here https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=false&url=https%3A%2F%2Fdemo.unified-streaming.com%2Fk8s%2Ffeatures%2Fstable%2Fvideo%2Ftears-of-steel%2Ftears-of-steel-hevc.ism%2F.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true
