### ISSUE TITLE
CC label is not translated when using Closed Captions file from HLS manifest

### ISSUE THREAD

**Issue by natalia-ku** [videojs/video.js#7993]
### Description

Hello,

We are playing HLS videos with VideoJS 7.10 version. Our videos has embedded English closed captions defined in HLS manifest file, similarly to this:

ID="subs",NAME="English",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,LANGUAGE="en",URI="someUrl.m3u8"

We are setting the language correctly when initializing player instance (according to the language doc: https://docs.videojs.com/docs/guides/languages.html). 

### Steps to reproduce

Whenever customer selects different languages on the website, we reload the page and create a new instance of the player, passing correct language code. After that all VideoJS labels are translated as expected, except for the "English" closed caption label that is available when clicking CC button. That label in not translated and stays as  "English" even if customer selected Spanish language and player is initialized with Spanish language code ("English" is "Inglés" in Spanish).

We thought that it is not translated because the subtitle's config in the manifest says NAME="English" (as shown above) because subtitles are only available in English. However, we think that it should be translated to Spanish as a standards used across other websites.

Could you help us identify how can we configure translation of the CC label for our use case? Note, it is not happening for the non-HLS videos.

### What version of Video.js are you using?

7.10

### What browser(s) including version(s) does this occur with?

Chrome

### What OS(es) and version(s) does this occur with?

Mac

**Comment by mister-ben** [comment]
There are two schools of thought here, either to display the languages in the language of the track (because the user might only recognise the language name in that language) or in the language of the UI (assuming the user understands the UI language).

There are no default transaltions for language names included Video.js's language files, but menu items' labels are passed through `player.localize()`, so you can add them:

```js
videojs.addLanguage('es', {
  "English": "Inglés"
})`
```
