### ISSUE TITLE
Video Js starting twice

### ISSUE THREAD

**Issue by gitbucket-crypto** [videojs/video.js#7999]
### Description

I grab this error the videojs is starting in double, i remove all classes in <video> and it stoped but when  I add the data-setup it came back again.

Its possible start the videojs on javascrit and set the data setup  and  others config;

I nor find any solution in googl

### Steps to reproduce
```
 <video id="myPlayerID" 
           class="video-js vjs-default-skin vjs-big-play-centered vjs-show-big-play-button-on-pause" 
           preload="auto" 
           controls 
           style="height:290px;width:100%;border:2px;overflow-x: hidden !important;"          

           >
    </video> 

data-setup='{ "fluid": true, "asdf": true , "nativeControlsForTouch": true, "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/embed/BhW0rbod9kk"}]  }'
```

### What version of Video.js are you using?

7.20.3

### Video.js plugins used.

Yes 

### What browser(s) including version(s) does this occur with?

chrome, firefox

### What OS(es) and version(s) does this occur with?

OSX, Linux , Android

**Comment by mister-ben** [comment]
Sorry but the problem you are describing and how to reproduce it are not clear enough to answer.
