### ISSUE TITLE
How to track progress of a video when reach exactly at 25%, 50%, 75% and 100%

### ISSUE THREAD

**Issue by Santoshah** [videojs/video.js#8002]
### Description

I want to track only when the video reaches exactly at certain percentage. Such as 25%, 50%, 75% and 100%. This event never triggers because the values are diluted or call multiple times because 25% trigger multiple times.

How can I track exact at the given percentage?

```
  videojs(this.target.nativeElement, {plugins: {seekButtons: {forward: 10, back: 10}}, type:'video/mp4', autoplay: true, height:400, "playbackRates": [0.5, 1, 1.5, 2], sources:{src:this.current_resource_url}}).on('timeupdate', function cb(){
    console.log(this.player().currentTime());
    
    let percent = this.player().controlBar.progressControl.seekBar.percent_
    if (percent == .25) _this.updateUserCourse(percent);
    if (percent == .50) _this.updateUserCourse(percent);
    if (percent == .75) _this.updateUserCourse(percent);        
    if (percent == 1  ) _this.updateUserCourse(percent);

  })
```

### Steps to reproduce

1.
2.
3.

### What version of Video.js are you using?

^7.20.3

### What browser(s) including version(s) does this occur with?

chrome

### What OS(es) and version(s) does this occur with?

Mac

**Comment by gkatsev** [comment]
You can do `player.currentTime() / player.duration()` to get the current progress percentage. you can do this on a timeupdate as you have in your example.

**Comment by Santoshah** [comment]
Hi @gkatsev,

Thank you for your response.

After implementing your logic I see below result. Still not getting exact 0.25, 0.50, 0.75. 

<img width="357" alt="image" src="https://user-images.githubusercontent.com/3863771/202076862-513e7030-17ce-4bcf-babd-0d9c326382f6.png">

```
.on('timeupdate', function cb(){

    //two decimal point
    console.log(Math.floor(this.player().currentTime()/this.player().duration() * 100) / 100);
    
    let percent = Math.floor(this.player().currentTime()/this.player().duration() * 100) / 100;
    if(percent ==  Math.floor(0.25 * 100) / 100) {
      console.log('video tracking', 0.25)
    }
    if(percent ==  Math.floor(0.50 * 100) / 100) {
      console.log('video tracking', 0.50)
    }
    if(percent ==  Math.floor(0.75 * 100) / 100) {
      console.log('video tracking', 0.75)
    }
    if(percent ==  Math.floor(1 * 100) / 100) {
      console.log('video tracking', 1)
    }
    
  })

```

**Comment by gkatsev** [comment]
Time update probably doesn't trigger enough to get exactly those percentages. You can try using setTimeout or requestAnimationFrame to get faster timers but ultimately you may want to round/consider the first update after the corresponding threshold.

Videojs doesn't have such an API natively.

**Comment by Santoshah** [comment]
I have manage to make it work. I have created a temporary variable called as lastPercent and update it at the end of the function.


```
.on('timeupdate', function cb(){
    console.log(Math.floor(this.player().currentTime()/this.player().duration() * 100) / 100);
    let percent = Math.floor(this.player().currentTime()/this.player().duration() * 100) / 100;
    if(percent >= .25 && lastPercent < .25) {
      console.log('video tracking', 0.25)
    }
    if(percent >= .50 && lastPercent < .50) {
      console.log('video tracking', 0.50)
    }
    if(percent >= .75 && lastPercent < .75) {
      console.log('video tracking', 0.75)
    }
    if(percent >= 1 && lastPercent < 1) {
      console.log('video tracking', 1)
    }
    lastPercent = percent;
    
  })
```

Thank you for your prompt response. 

Closing it..
