### ISSUE TITLE
Player with HLS not working on some iphone / IOS

### ISSUE THREAD

**Issue by louiiuol** [videojs/video.js#8028]
### Description

I have implemented a videojs (Version: ^7.11.8) player which supports HLS stream (MPEG-URL).

This player is globally working on any device (windows, macOS, android, iPhone) but some specific cases remain (iPhone/IOS versions below) where the player won’t load/launch the video.

I have also noticed that the problem can be fixed if I turned off autoplay … Must be linked somehow … However, I have check all recommendations from Apple and Videojs documentation:

<video> tag has an attribute inline , preload="auto" & muted as required here:  [Apple Developer Documentation](https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari)

Videojs Player is overriden with following options [GitHub - videojs/http-streaming: HLS, DASH, and future HTTP streaming protocols library for video.js](https://github.com/videojs/http-streaming#overridenative)
`html5 = {
    nativeVideoTracks: false,
    nativeAudioTracks: false,
    nativeTextTracks: false,
    useBandwidthFromLocalStorage: true,
    vhs: {
      limitRenditionByPlayerDimensions: true,
      useDevicePixelRatio: true,
      overrideNative: true,
    },
  };`

NB: I generate my own m3u8 file, so may be something is missing on this side too .. Here is the related file:

https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw.m3u8

Also if you have any idea on how to debug theses cases, considering they happened on iPhone specific versions .. I’ve heard of Sofi, but I’m not sure what I can do with it ? 

 Thanks a lot ! 🙏

Louis

### Reduced test case
You can find an example of a hosted player that can be played anywhere but in some specific iPhone cases.
Web page: https://players-cdn.vidmizer.com/7c0a2e3d-cba3-4183-bbec-fc00dc292356/index.html#da7e2e27-6289-4e04-9dce-eaaa59973d42
M3U8 file: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw.m3u8

### Steps to reproduce

1.Launch the URL above on specific version of iPhone (listed below)
2. When player tries to load/launch video: it breaks

### Errors

Video cannot be played on specific iPhone/ iOS versions

### What version of Video.js are you using?

^7.11.8

### Video.js plugins used.

videojs-playlist

### What browser(s) including version(s) does this occur with?

safari for iOS

### What OS(es) and version(s) does this occur with?

iPhone 8  iPhone 12  iPhone 13  iPhone 14  (IOS Versions :  15.6  16  16.1)

**Comment by gkatsev** [comment]
Video.js isn't in charge of playback on iPhones, even if `overrideNative` is set. If you load in the m3u8 directly on those devices, I would expect it to not work as well.
Running your stream through Apple's `mediastreamvalidator` is showing a bunch of MUST fix errors that should be addressed.

Here's the output:
<details>
<pre><code>
--------------------------------------------------------------------------------
MUST fix issues
--------------------------------------------------------------------------------

Error: Measured peak bitrate compared to multivariant playlist declared value exceeds error tolerance
--> Detail:  Measured: 796.50 kb/s, Multivariant playlist: 931.43 kb/s, Error: 14.49%, Combined rendition name: audio_3
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_2.m3u8

--> Detail:  Measured: 304.24 kb/s, Multivariant playlist: 431.43 kb/s, Error: 29.48%, Combined rendition name: audio_3
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_0.m3u8

--> Detail:  Measured: 583.94 kb/s, Multivariant playlist: 711.43 kb/s, Error: 17.92%, Combined rendition name: audio_3
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_1.m3u8

Error: Different target durations detected
--> Detail:  Target duration: 4 vs Target duration: 10
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_0.m3u8

--> Detail:  Target duration: 4 vs Target duration: 10
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_2.m3u8

--> Detail:  Target duration: 4 vs Target duration: 10
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_1.m3u8

Error: Illegal MIME type
--> Detail:  MIME type: binary/octet-stream
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw.m3u8

--> Detail:  MIME type: binary/octet-stream
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_1.m3u8

--> Detail:  MIME type: binary/octet-stream
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_0.m3u8

--> Detail:  MIME type: binary/octet-stream
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8

--> Detail:  MIME type: binary/octet-stream
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_2.m3u8

Error: Program date-time tags are too far apart
--> Detail:  Playlist: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_1.m3u8, date-time: 2022-10-27T03:44:51.000-04:00 vs Playlist: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8, date-time: 1969-12-31T19:00:00.000-05:00
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_1.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8

--> Detail:  Playlist: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_0.m3u8, date-time: 2022-10-27T03:44:51.000-04:00 vs Playlist: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8, date-time: 1969-12-31T19:00:00.000-05:00
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_0.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8

--> Detail:  Playlist: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_2.m3u8, date-time: 2022-10-27T03:44:51.000-04:00 vs Playlist: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8, date-time: 1969-12-31T19:00:00.000-05:00
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_2.m3u8
--> Compare: https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_3.m3u8

Error: Playlist video resolution doesn't match parsed video resolution
--> Detail:  Playlist: 356 x 360, Video: 357 x 360
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_1.m3u8

--> Detail:  Playlist: 536 x 540, Video: 535 x 540
--> Source:  https://storage.gra.cloud.ovh.net/v1/AUTH_cf288dd96a8a4bc5bbc0ba258e1b93b8/media-storage-prod/d7b95c06-b445-4ea1-9638-a229e7227ae5_phpefwyfw_media_2.m3u8
</code></pre>
</details>

**Comment by louiiuol** [comment]
Thanks a lot for your feedback! (impressive timing, didn't expect answer before tomorow at least 🙏)

" If you load in the m3u8 directly on those devices, I would expect it to not work as well."
It actually plays well on a lot of devices (including iPhones) 😅

Anyway, thanks again for this tool and output, I will look into it !

Have a nice day

**Comment by gkatsev** [comment]
> impressive timing, didn't expect answer before tomorow at least

Sometimes, we reply fast, sometimes we reply slow :)



> It actually plays well on a lot of devices (including iPhones) 😅

Specifically, I meant, on the devices you're having trouble with, I would expect it to continue failing without video.js. Frankly, with some of the flags that medaistreamvalidtor shows, I'm a bit surprised you haven't run into issues in other browsers.
