### ISSUE TITLE
my videoJs player just won't play on iphone

### ISSUE THREAD

**Issue by farzadabroudi** [videojs/video.js#8039]
### Description

Hi every one

I configured videoJs and now its work on windows desktop & android devices & even mac safari but it is not work on iphone browsers (safari ,firefox,chrome) 

my code :
![videojs1](https://user-images.githubusercontent.com/72689711/206857456-3c8d19a3-c23c-4f5c-a1d3-5a626e3b4d41.jpg)

### Steps to reproduce

1.
2.
3.

### Errors

the media could not be loaded either because the server or network failed or because the format is note supported.

![IMG_4747](https://user-images.githubusercontent.com/72689711/206857468-10037829-b1e9-4ddb-906a-f12331bdfedb.PNG)
![IMG_4746](https://user-images.githubusercontent.com/72689711/206857469-420ea701-06af-43d7-915d-cdf5b2f0456f.PNG)

### What version of Video.js are you using?

7.19.2

### What browser(s) including version(s) does this occur with?

iphone browsers

### What OS(es) and version(s) does this occur with?

windows 11

**Comment by gkatsev** [comment]
iPhones will always play m3u8 natively. If it isn't working, I would recommend running your stream through Apple's mediastreamvalidator and making sure that it isn't showing any issues.

**Comment by farzadabroudi** [comment]
Thank you for your guidance
I was doing the authentication in the header, that's why the token was not sent to the iPhone
I asked the backend to authenticate via cookie
