### ISSUE TITLE
Some VideoJS resources randomly fail to play

### ISSUE THREAD

**Issue by fmkoreacom** [videojs/video.js#8045]
### Description

Randomly sometimes videojs based videos don't load, when there are multiple videojs videos.
This happens in Chrome, Samsung Browser, web view browsers and even older Chrome versions.
I have directly seen this in Chrome versions 99.0.4844.88 and 108.0.5359.79
Of note, no users using safari have this problem at all.
I have only seen this in mobile browsers. I am not sure if it occurs in PC or not, but if it does it is rare.

See captured video of the following:
Visited https://m.fmkorea.com/best/5303857732 on Android, Chrome 108.0.5359.79
reload
video 8 seconds: first video won't play
reload
video 27 seconds: first video won't play
reload
video 39 seconds: second video won't play
reload
all videos works
reload
video 1:19 seconds: first video won't play

Note, one video often randomly doesn't play. I have not seen more than one video not work.

Captured video file:
https://user-images.githubusercontent.com/71078324/207414467-2da8c489-170d-46d4-9d92-030ac0aea4dd.mp4

Tested on
Galaxy S21 Ultra 5G
SM-G998N
One UI version 5.0
Android version 13
Updated today to most recent update.

I did an open test with real users(of note we have tens of thousands of users online) in a public forum post:
https://www.fmkorea.com/5306466514
Of note, this issue seems to randomly appear for some users, with refresh fixing it and causing it randomly.
The issue occurs in many chromium browser users, but appears randomly.
With the bulk of users having no problems.

Using a defer script to defer the videojs loading seems to fix the issue itself, but has too much performance impact along with some other problems related to defer.

The not playing video will not be reproducible on our site itself anymore, however the issue still does occur, we have patched our site to work using the following:
If videoJS.src() is empty set videoJS.src to the underlying video tag src.
When the video load fails we change the blank src to fix it.

In a different test, when the video was working and not working we got the 
videojs object output in the Chrome console before playing the video.
We found the error videos have waitToPlay_ function set and not disappear along with videoJS.src()  being empty.
attached file working.txt and working2.txt are two working videos
attached file notworking.txt is the not working video

[working.txt](https://github.com/videojs/video.js/files/10221073/working.txt)
[working2.txt](https://github.com/videojs/video.js/files/10221074/working2.txt)
[notworking.txt](https://github.com/videojs/video.js/files/10221075/notworking.txt)

### Steps to reproduce

See captured video attached in description of this issue of the following:
Visited https://m.fmkorea.com/best/5303857732 on Android, Chrome 108.0.5359.79
reload
video 8 seconds: first video won't play
reload
video 27 seconds: first video won't play
reload
video 39 seconds: second video won't play
reload
all videos works
reload
video 1:19 seconds: first video won't play

However, this issue occurs for only some users, and most users it does not.
I have no idea why it occurs only for some users.

The not playing video will not be reproducible on our site itself anymore, however the issue still does occur, we have patched our site to work using the following:
If videoJS.src() is empty set videoJS.src to the underlying video tag src.
When the video load fails we change the blank src to fix it.

### What version of Video.js are you using?

7.21.1 also reproduced on 7.11.7

### Video.js plugins used.

persistvolume

### What browser(s) including version(s) does this occur with?

Chrome versions 99.0.4844.88 and 108.0.5359.79, other chromium mobile browsers.

### What OS(es) and version(s) does this occur with?

Android 13

**Comment by fmkoreacom** [comment]
Here is our current workaround.
When the one random videoJS is broken and doesn't play, the src is empty in videoJS, but still in the video tag itself.

We load videoJS using the following function after document is ready.
`loadVideoJs($(this).attr('id'));`

Then at the top of loadVideoJs we added
```
    var $ = jQuery;
    var vid = videojs(element_id);
    if(vid.src() === "") {
        console.log('source load error : ' + element_id + ' -> try to fix');
        var new_src = $('#' + element_id).find('source:first').attr('src');
        vid.src({src: new_src});
    } else {
        console.log('source load success : ' + element_id);
    }
```

This makes the videos play without problems.

**Comment by mister-ben** [comment]
It's not clear what issue you were having or how to reproduce, but it sounds like you have resolved it so closing
