### ISSUE TITLE
videojs-ima ads playing but not displaying or showing

### ISSUE THREAD

**Issue by yashraj-02** [videojs/video.js#8051]
### Description

So basically I am trying to play video ads using videojs & videojs-ima & videojs-contrib-ads. On one site my player is able to play ads but on another site it is unable to play ads. I am not able to find the solution in any forum online. Please help me find the root cause.

Url where ads are playing: https://www.javatpoint.com/javascript-tutorial?forceOutstreamBid=true&forceApPlayer=true

Url where ads are not playing: https://www.iaai.com/VehicleDetail/1817919~CA?forceApPlayer=true&forceOutstreamBid=true

PS: you might not get the video ads on every page refresh. Incase you don't receive ads use incognito and/or VPN. Video link of the issue: https://vimeo.com/782497314#t=80

Backup video link of the issue: https://drive.google.com/file/d/1lUuAgSaGt_285Vy0pTHtm_5igL85hCFp/view?usp=sharing

### Steps to reproduce

1.
2.
3.

### Errors

No errors displayed

### What version of Video.js are you using?

7.20.2

### Video.js plugins used.

"videojs-contrib-ads": "^6.9.0" & "videojs-ima": "^2.0.1"

### What browser(s) including version(s) does this occur with?

safari, chrome  & firefox

### What OS(es) and version(s) does this occur with?

macos

**Comment by yashraj-02** [comment]
Anyone?

**Comment by dioramayuanito** [comment]
1. This adTagUrl **https://www.javatpoint.com/javascript-tutorial?forceOutstreamBid=true&forceApPlayer=true** gives me an error

**Access to XMLHttpRequest at 'https://www.javatpoint.com/javascript-tutorial?forceOutstreamBid=true&forceApPlayer=true' from origin 'https://imasdk.googleapis.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**


2. This adTagUrl **https://www.iaai.com/VehicleDetail/1817919~CA?forceApPlayer=true&forceOutstreamBid=true** gives me a warning 

"AdsLoader error: AdError 1010: The ad response was not understood and cannot be parsed.". 
It occurs because of your adTagUrl from iaai.com didn't produce valid VAST/VPAID XML (but iaai.com produced HTML Page)

**Comment by yashraj-02** [comment]
Thanks for replying @dioramayuanito

https://github.com/googleads/videojs-ima/issues/1 Both the URLs which I mentioned aren't the adTagUrl's. They are the URLs of the website where the player is live. I shared it so that you can check the issue there.

https://github.com/googleads/videojs-ima/issues/2 If you want the vastXml then here it is:

<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><VAST version=\"3.0\"><Ad id=\"97517771\"><InLine><AdSystem>adnxs</AdSystem><AdTitle><![CDATA[Prebid Video Skippable -- Avocados From Mexico]]></AdTitle><Error><![CDATA[https://sin3-ib.adnxs.com/vast_track/v2?info=ZwAAAAMArgAFAQlyYaFjAAAAABEz_pJ_dXa9aBlyYaFjAAAAACDLgcAuKAAw7Ug47UhA0-hISLuv1AFQgdKnBljDlQtiAklOaAFwAXgAgAECiAEEkAGsApgBMqABAKgBy4HALrABAQ..&s=178d0e971f19e17f0bf8302a9d0650bcfe6732c3&event_type=4&error_code=[ERRORCODE]]]></Error><Impression id=\"adnxs\"><![CDATA[https://sin3-ib.adnxs.com/it?an_audit=0&referrer=https%3A%2F%2Fwww.iaai.com%2FVehicleDetail%2F1817919%7ECA%3FforceApPlayer%3Dtrue%26apDebug%3Dtrue%26forceOutstreamBid%3Dtrue&e=wqT_3QKTDaCTBgAAAwDWAAUBCPLChZ0GELP8y_zXzt3eaBitmpX6rr2s7VAqNgkAAAECCCRAEQEHEAAAJEAZEQkAIREJACkRCQAxEQmoMIHSpwY47UhA7UhIAlDLgcAuWJzxW2AAaOWljwF489MFgAEBigEDVVNEkgUG9IEBmAEBoAEBqAEBsAEAuAEDwAEDyAEC0AEA2AEA4AEA8AEA-gEIb3V0LXRlc3SKAil1ZignYScsIDI1Mjk4ODUsIDApO3VmKCdyJywgOTc1MTc3NzEsIDApO5ICrQQhN1dGUmVRalktTHdLRU11QndDNFlBQ0NjOFZzd0FEZ0FRQVJJN1VoUWdkS25CbGdBWU9VR2FBQncxaEI0eEtZQ2dBSFdFSWdCeEtZQ2tBRUJtQUVCb0FFQnFBRURzQUVBdVFIenJXcWtBQUFrUU1FQjg2MXFwQUFBSkVESkFVX0NQSzRpQ000XzJRRUFBQUFBQUFEd1AtQUJBUFVCQUFBQUFKZ0NBS0FDQUxVQ0FBQUFBTDBDQUFBQUFNQUNBTWdDQU5BQ0FOZ0NBT0FDQU9nQ0FQZ0NBSUFEQVpnREFib0RDVk5KVGpNNk5UYzFNLUFEaERDSUJBQ1FCQUNZQkFIQkJBQUFBQUFBQUFBQXlRUUFBQUFBQUFBQUFOZ0VBUEVFQUFBQUEFIyBDSUJma3NxUVUFDgBBAagIN0VGDQ0BEAhCQlEBCAkBAHkVKAxBQUFOMigAAFouKAA8NEFYQWhEM3FCU1lJQXhJaQFJ8E82ZkpnM2V6bFN4SW5fcndWYzBmaDRpcW5PZGtQQnc2bzgxeVJHV2tFU2ZBRm5NUGZBdmdGM2JTYUFZSUdBMVZUUklnR0FKQUdBWmdHQUtFRwGDAQEsSkVDb0JnR3lCaVFKARANAQBSDQgBAQBaAQUNAQBoDQhYQUFBQzRCZ28umgKVASFpdzlwcEFqWS1dMShuUEZiSUFRb0FERQEuAQFUa1FEb0pVMGxPTXpvMU56VXpRSVF3UzEhDFBBX1URDAxBQUFXHQwAWR0MAGEdDABjHQwQZUFDSkEdEPCVwgI4aHR0cDovL3ByZWJpZC5vcmcvZGV2LWRvY3Mvc2hvdy1vdXRzdHJlYW0tdmlkZW8tYWRzLmh0bWzYAvfpA-ACrZhI6gJkaHR0cHM6Ly93d3cuaWFhaS5jb20vVmVoaWNsZURldGFpbC8xODE3OTE5fkNBP2ZvcmNlQXBQbGF5ZXI9dHJ1ZSZhcERlYnVnPXRydWUmBSAET3UNeAxCaWQ9ARfQgAMAiAMBkAMAmAMXoAMBqgMAwAPgqAHIAwDYA9e9QuADAOgDAPgDAYAEAJIEDS91dC92My8J1_BhmAQAogQNMTAzLjIzNS4wLjIyOKgEuLAWsgQPCAQQBBisAiAyKAEwADgDuAQAwASA2rgiyAQA0gQOOTMyNSNTSU4zOjU3NTPaBAIIAeAEAPAEy4HALogFAZgFAKAF______8BAxQBwAUAyQWJrRTwP9IFCQkJDHgAANgFAeAFAfAFw5UL-gUECAAQAJAGAZgGALgGAMEGCSUo8D_QBvUv2gYWChAJERkBcBAAGADgBgTyBgIIAIAHAYgHAKAHQMgH89MF0gcNFWQBJgjaBwYBXfQOARgA4AcA6gcCCADwB4yzC4oI8wEK7gEAAAGFLmSlUGi9dnV_kv4z-80simTv7e63ca1uKDe0JBrnC5Pnu8nfxg8XSa5Foq02p0E8ikywlThC7IkMvA9jPnokxrvulgAheYZt2856CPDyR0o2Psq_g-v1mVAdrYzoNfIg5ljq2-vwRvZJTblnXyA2fIFgmkfBktM5sEQHV963Gyj7ZDPpPzHxGK_gCa1Fl_tdNkE8i2O7eUuVRFrmaHcOFFcZBRZH3E33qD0M9IelioAbw8jUlO8PDjXbo02o1e-ZyiIIjZs7yJ1B6DWuHXHEjaZumifwUqINNZPO7bw69ZvGYIMWipL5x2EQEAGVCAAAgD-YCAE.&s=1ac5583456a69a3b15aac3b05f7caad4eef5373f]]></Impression><Creatives><Creative id=\"70944\" adID=\"97517771\"><Linear skipoffset=\"00:00:05\"><Duration>00:00:30.000</Duration><TrackingEvents><Tracking event=\"start\"><![CDATA[https://sin3-ib.adnxs.com/vast_track/v2?info=ZwAAAAMArgAFAQlyYaFjAAAAABEz_pJ_dXa9aBlyYaFjAAAAACDLgcAuKAAw7Ug47UhA0-hISLuv1AFQgdKnBljDlQtiAklOaAFwAXgAgAECiAEEkAGsApgBMqABAKgBy4HALrABAQ..&s=178d0e971f19e17f0bf8302a9d0650bcfe6732c3&event_type=2]]></Tracking><Tracking event=\"skip\"><![CDATA[https://sin3-ib.adnxs.com/vast_track/v2?info=ZwAAAAMArgAFAQlyYaFjAAAAABEz_pJ_dXa9aBlyYaFjAAAAACDLgcAuKAAw7Ug47UhA0-hISLuv1AFQgdKnBljDlQtiAklOaAFwAXgAgAECiAEEkAGsApgBMqABAKgBy4HALrABAQ..&s=178d0e971f19e17f0bf8302a9d0650bcfe6732c3&event_type=3]]></Tracking><Tracking event=\"firstQuartile\"><![CDATA[https://sin3-ib.adnxs.com/vast_track/v2?info=ZwAAAAMArgAFAQlyYaFjAAAAABEz_pJ_dXa9aBlyYaFjAAAAACDLgcAuKAAw7Ug47UhA0-hISLuv1AFQgdKnBljDlQtiAklOaAFwAXgAgAECiAEEkAGsApgBMqABAKgBy4HALrABAQ..&s=178d0e971f19e17f0bf8302a9d0650bcfe6732c3&event_type=5]]></Tracking><Tracking event=\"midpoint\"><![CDATA[https://sin3-ib.adnxs.com/vast_track/v2?info=ZwAAAAMArgAFAQlyYaFjAAAAABEz_pJ_dXa9aBlyYaFjAAAAACDLgcAuKAAw7Ug47UhA0-hISLuv1AFQgdKnBljDlQtiAklOaAFwAXgAgAECiAEEkAGsApgBMqABAKgBy4HALrABAQ..&s=178d0e971f19e17f0bf8302a9d0650bcfe6732c3&event_type=6]]></Tracking><Tracking event=\"thirdQuartile\"><![CDATA[https://sin3-ib.adnxs.com/vast_track/v2?info=ZwAAAAMArgAFAQlyYaFjAAAAABEz_pJ_dXa9aBlyYaFjAAAAACDLgcAuKAAw7Ug47UhA0-hISLuv1AFQgdKnBljDlQtiAklOaAFwAXgAgAECiAEEkAGsApgBMqABAKgBy4HALrABAQ..&s=178d0e971f19e17f0bf8302a9d0650bcfe6732c3&event_type=7]]></Tracking><Tracking event=\"complete\"><![CDATA[https://sin3-ib.adnxs.com/vast_track/v2?info=ZwAAAAMArgAFAQlyYaFjAAAAABEz_pJ_dXa9aBlyYaFjAAAAACDLgcAuKAAw7Ug47UhA0-hISLuv1AFQgdKnBljDlQtiAklOaAFwAXgAgAECiAEEkAGsApgBMqABAKgBy4HALrABAQ..&s=178d0e971f19e17f0bf8302a9d0650bcfe6732c3&event_type=8]]></Tracking></TrackingEvents><VideoClicks><ClickThrough><![CDATA[http://prebid.org/dev-docs/show-outstream-video-ads.html]]></ClickThrough><ClickTracking id=\"adnxs\"><![CDATA[https://sin3-ib.adnxs.com/click?AAAAAAAAJEAAAAAAAAAkQAAAAAAAACRAAAAAAAAAJEAAAAAAAAAkQDP-kn91dr1oLU1F7-qx2lByYaFjAAAAAAHpyQBtJAAAbSQAAAIAAADLANAFnPgWAAAAAABVU0QAVVNEAAEAAQDl0gAAAAABAwMCAAAAAMYAEheevQAAAAA./bcr=AAAAAAAA8D8=/cnd=%21iw9ppAjY-LwKEMuBwC4YnPFbIAQoADEAAAAAAAAkQDoJU0lOMzo1NzUzQIQwSQAAAAAAAPA_UQAAAAAAAAAAWQAAAAAAAAAAYQAAAAAAAAAAaQAAAAAAAAAAcQAAAAAAAAAAeACJAQAAAAAAAAAA/cca=OTMyNSNTSU4zOjU3NTM=/bn=92659/]]></ClickTracking></VideoClicks><MediaFiles><MediaFile id=\"824647\" delivery=\"progressive\" type=\"video/mp4\" width=\"768\" height=\"432\" scalable=\"true\" bitrate=\"1700\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7_768_432_1700k.mp4]]></MediaFile><MediaFile id=\"824648\" delivery=\"progressive\" type=\"video/x-flv\" width=\"768\" height=\"432\" scalable=\"true\" bitrate=\"1100\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7_768_432_1100k.flv]]></MediaFile><MediaFile id=\"824649\" delivery=\"progressive\" type=\"video/mp4\" width=\"768\" height=\"432\" scalable=\"true\" bitrate=\"1100\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7_768_432_1100k.mp4]]></MediaFile><MediaFile id=\"824650\" delivery=\"progressive\" type=\"video/mp4\" width=\"768\" height=\"432\" scalable=\"true\" bitrate=\"500\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7_768_432_500k.mp4]]></MediaFile><MediaFile id=\"824651\" delivery=\"progressive\" type=\"video/x-flv\" width=\"768\" height=\"432\" scalable=\"true\" bitrate=\"500\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7_768_432_500k.flv]]></MediaFile><MediaFile id=\"824652\" delivery=\"progressive\" type=\"video/webm\" width=\"768\" height=\"432\" scalable=\"true\" bitrate=\"500\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7_768_432_500k.webm]]></MediaFile><MediaFile id=\"824653\" delivery=\"progressive\" type=\"video/webm\" width=\"768\" height=\"432\" scalable=\"true\" bitrate=\"1500\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7_768_432_1500k.webm]]></MediaFile><MediaFile id=\"824654\" delivery=\"progressive\" type=\"video/mp4\" width=\"960\" height=\"540\" scalable=\"true\" bitrate=\"1775\" maintainAspectRatio=\"true\"><![CDATA[https://vcdn.adnxs.com/p/creative-video/c7/84/47/f8/c78447f8-84f7-400b-aacf-39a87d9e1fb7/c78447f8-84f7-400b-aacf-39a87d9e1fb7.mp4]]></MediaFile></MediaFiles></Linear></Creative></Creatives><Extensions><Extension type=\"AdVerifications\"><AdVerifications><Verification vendor=\"appnexus.com-omid\"><JavaScriptResource apiFramework=\"omid\" browserOptional=\"true\"><![CDATA[https://cdn.adnxs.com/v/omsdkvideo/231/trk.js]]></JavaScriptResource><VerificationParameters><![CDATA[tv=vh2-136&d=1x1&s=3479483&st=0&vctx=4&ts=1671520626&vc=iab;vid_ccr=1&vjs=https%3A%2F%2Fcdn.adnxs.com%2Fv%2Fvideo%2F231%2Ftrk.js&cb=https%3A%2F%2Fsin3-ib.adnxs.com%2Fvevent%3Fan_audit%3D0%26referrer%3Dhttps%253A%252F%252Fwww.iaai.com%252FVehicleDetail%252F1817919%257ECA%253FforceApPlayer%253Dtrue%2526apDebug%253Dtrue%2526forceOutstreamBid%253Dtrue%26e%3DwqT_3QKTDaCTBgAAAwDWAAUBCPLChZ0GELP8y_zXzt3eaBitmpX6rr2s7VAqNgkAAAECCCRAEQEHEAAAJEAZEQkAIREJACkRCQAxEQmoMIHSpwY47UhA7UhIAlDLgcAuWJzxW2AAaOWljwF489MFgAEBigEDVVNEkgUG9IEBmAEBoAEBqAEBsAEAuAEDwAEDyAEC0AEA2AEA4AEA8AEA-gEIb3V0LXRlc3SKAil1ZignYScsIDI1Mjk4ODUsIDApO3VmKCdyJywgOTc1MTc3NzEsIDApO5ICrQQhN1dGUmVRalktTHdLRU11QndDNFlBQ0NjOFZzd0FEZ0FRQVJJN1VoUWdkS25CbGdBWU9VR2FBQncxaEI0eEtZQ2dBSFdFSWdCeEtZQ2tBRUJtQUVCb0FFQnFBRURzQUVBdVFIenJXcWtBQUFrUU1FQjg2MXFwQUFBSkVESkFVX0NQSzRpQ000XzJRRUFBQUFBQUFEd1AtQUJBUFVCQUFBQUFKZ0NBS0FDQUxVQ0FBQUFBTDBDQUFBQUFNQUNBTWdDQU5BQ0FOZ0NBT0FDQU9nQ0FQZ0NBSUFEQVpnREFib0RDVk5KVGpNNk5UYzFNLUFEaERDSUJBQ1FCQUNZQkFIQkJBQUFBQUFBQUFBQXlRUUFBQUFBQUFBQUFOZ0VBUEVFQUFBQUEFIyBDSUJma3NxUVUFDgBBAagIN0VGDQ0BEAhCQlEBCAkBAHkVKAxBQUFOMigAAFouKAA8NEFYQWhEM3FCU1lJQXhJaQFJ8E82ZkpnM2V6bFN4SW5fcndWYzBmaDRpcW5PZGtQQnc2bzgxeVJHV2tFU2ZBRm5NUGZBdmdGM2JTYUFZSUdBMVZUUklnR0FKQUdBWmdHQUtFRwGDAQEsSkVDb0JnR3lCaVFKARANAQBSDQgBAQBaAQUNAQBoDQhYQUFBQzRCZ28umgKVASFpdzlwcEFqWS1dMShuUEZiSUFRb0FERQEuAQFUa1FEb0pVMGxPTXpvMU56VXpRSVF3UzEhDFBBX1URDAxBQUFXHQwAWR0MAGEdDABjHQwQZUFDSkEdEPCVwgI4aHR0cDovL3ByZWJpZC5vcmcvZGV2LWRvY3Mvc2hvdy1vdXRzdHJlYW0tdmlkZW8tYWRzLmh0bWzYAvfpA-ACrZhI6gJkaHR0cHM6Ly93d3cuaWFhaS5jb20vVmVoaWNsZURldGFpbC8xODE3OTE5fkNBP2ZvcmNlQXBQbGF5ZXI9dHJ1ZSZhcERlYnVnPXRydWUmBSAET3UNeAxCaWQ9ARfQgAMAiAMBkAMAmAMXoAMBqgMAwAPgqAHIAwDYA9e9QuADAOgDAPgDAYAEAJIEDS91dC92My8J1_BhmAQAogQNMTAzLjIzNS4wLjIyOKgEuLAWsgQPCAQQBBisAiAyKAEwADgDuAQAwASA2rgiyAQA0gQOOTMyNSNTSU4zOjU3NTPaBAIIAeAEAPAEy4HALogFAZgFAKAF______8BAxQBwAUAyQWJrRTwP9IFCQkJDHgAANgFAeAFAfAFw5UL-gUECAAQAJAGAZgGALgGAMEGCSUo8D_QBvUv2gYWChAJERkBcBAAGADgBgTyBgIIAIAHAYgHAKAHQMgH89MF0gcNFWQBJgjaBwYBXfQOARgA4AcA6gcCCADwB4yzC4oI8wEK7gEAAAGFLmSlUGi9dnV_kv4z-80simTv7e63ca1uKDe0JBrnC5Pnu8nfxg8XSa5Foq02p0E8ikywlThC7IkMvA9jPnokxrvulgAheYZt2856CPDyR0o2Psq_g-v1mVAdrYzoNfIg5ljq2-vwRvZJTblnXyA2fIFgmkfBktM5sEQHV963Gyj7ZDPpPzHxGK_gCa1Fl_tdNkE8i2O7eUuVRFrmaHcOFFcZBRZH3E33qD0M9IelioAbw8jUlO8PDjXbo02o1e-ZyiIIjZs7yJ1B6DWuHXHEjaZumifwUqINNZPO7bw69ZvGYIMWipL5x2EQEAGVCAAAgD-YCAE.%26s%3D1ac5583456a69a3b15aac3b05f7caad4eef5373f&cet=0&cecb=&rdcb=https%3A%2F%2Fsin3-ib.adnxs.com%2Frd_log%3Fan_audit%3D0%26referrer%3Dhttps%253A%252F%252Fwww.iaai.com%252FVehicleDetail%252F1817919%257ECA%253FforceApPlayer%253Dtrue%2526apDebug%253Dtrue%2526forceOutstreamBid%253Dtrue%26e%3DwqT_3QKcD6CcBwAAAwDWAAUBCPLChZ0GELP8y_zXzt3eaBitmpX6rr2s7VAqNgkAAAECCCRAEQEHEAAAJEAZEQkAIREJACkRCQAxEQmoMIHSpwY47UhA7UhIAlDLgcAuWJzxW2AAaOWljwF489MFgAEBigEDVVNEkgUG9IEBmAEBoAEBqAEBsAEAuAEDwAEDyAEC0AEA2AEA4AEA8AEA-gEIb3V0LXRlc3SKAil1ZignYScsIDI1Mjk4ODUsIDApO3VmKCdyJywgOTc1MTc3NzEsIDApO5ICrQQhN1dGUmVRalktTHdLRU11QndDNFlBQ0NjOFZzd0FEZ0FRQVJJN1VoUWdkS25CbGdBWU9VR2FBQncxaEI0eEtZQ2dBSFdFSWdCeEtZQ2tBRUJtQUVCb0FFQnFBRURzQUVBdVFIenJXcWtBQUFrUU1FQjg2MXFwQUFBSkVESkFVX0NQSzRpQ000XzJRRUFBQUFBQUFEd1AtQUJBUFVCQUFBQUFKZ0NBS0FDQUxVQ0FBQUFBTDBDQUFBQUFNQUNBTWdDQU5BQ0FOZ0NBT0FDQU9nQ0FQZ0NBSUFEQVpnREFib0RDVk5KVGpNNk5UYzFNLUFEaERDSUJBQ1FCQUNZQkFIQkJBQUFBQUFBQUFBQXlRUUFBQUFBQUFBQUFOZ0VBUEVFQUFBQUEFIyBDSUJma3NxUVUFDgBBAagIN0VGDQ0BEAhCQlEBCAkBAHkVKAxBQUFOMigAAFouKAA8NEFYQWhEM3FCU1lJQXhJaQFJ8E82ZkpnM2V6bFN4SW5fcndWYzBmaDRpcW5PZGtQQnc2bzgxeVJHV2tFU2ZBRm5NUGZBdmdGM2JTYUFZSUdBMVZUUklnR0FKQUdBWmdHQUtFRwGDAQEsSkVDb0JnR3lCaVFKARANAQBSDQgBAQBaAQUNAQBoDQhYQUFBQzRCZ28umgKVASFpdzlwcEFqWS1dMShuUEZiSUFRb0FERQEuAQFUa1FEb0pVMGxPTXpvMU56VXpRSVF3UzEhDFBBX1URDAxBQUFXHQwAWR0MAGEdDABjHQwQZUFDSkEdEPCVwgI4aHR0cDovL3ByZWJpZC5vcmcvZGV2LWRvY3Mvc2hvdy1vdXRzdHJlYW0tdmlkZW8tYWRzLmh0bWzYAvfpA-ACrZhI6gJkaHR0cHM6Ly93d3cuaWFhaS5jb20vVmVoaWNsZURldGFpbC8xODE3OTE5fkNBP2ZvcmNlQXBQbGF5ZXI9dHJ1ZSZhcERlYnVnPXRydWUmBSAET3UNeAxCaWQ9ARcw8gIRCgZBRFZfSUQSB22kBRQIQ1BHBRQYNTc1OTM4OAEUCAVDUAETNAgyMTk3MDAwOPICEAoIATxwRlJFURIEMTA2N_ICDQoIUkVNX1VTRVISATDyAgwJIxRDT0RFEgAFDwFaEQ8QCwoHQ1AVDhAJCgVJTwFjBADyARoESU8VGjgTCg9DVVNUT01fTU9ERUwNJAgaChYyFgAcTEVBRl9OQU0FaggeCho2HQAIQVNUAT4QSUZJRUQBYhwNCghTUExJVAFN2AEwgAMAiAMBkAMAmAMXoAMBqgMAwAPgqAHIAwDYA9e9QuADAOgDAPgDAYAEAJIEDS91dC92My8p4PBhmAQAogQNMTAzLjIzNS4wLjIyOKgEuLAWsgQPCAQQBBisAiAyKAEwADgDuAQAwASA2rgiyAQA0gQOOTMyNSNTSU4zOjU3NTPaBAIIAeAEAPAEy4HALogFAZgFAKAF______8BAxQBwAUAyQWpthTwP9IFCQkJDHgAANgFAeAFAfAFw5UL-gUECAAQAJAGAZgGALgGAMEGCSUo8D_QBvUv2gYWChAJERkBcBAAGADgBgTyBgIIAIAHAYgHAKAHQMgH89MF0gcNFWQBJgjaBwYBXfQOARgA4AcA6gcCCADwB4yzC4oI8wEK7gEAAAGFLmSlUGi9dnV_kv4z-80simTv7e63ca1uKDe0JBrnC5Pnu8nfxg8XSa5Foq02p0E8ikywlThC7IkMvA9jPnokxrvulgAheYZt2856CPDyR0o2Psq_g-v1mVAdrYzoNfIg5ljq2-vwRvZJTblnXyA2fIFgmkfBktM5sEQHV963Gyj7ZDPpPzHxGK_gCa1Fl_tdNkE8i2O7eUuVRFrmaHcOFFcZBRZH3E33qD0M9IelioAbw8jUlO8PDjXbo02o1e-ZyiIIjZs7yJ1B6DWuHXHEjaZumifwUqINNZPO7bw69ZvGYIMWipL5x2EQEAGVCAAAgD-YCAE.%26s%3Dbbe5e83e916b82bc3d42b6ef647205d9b6d38212&bridge=1.11.0&rblog=auc=7547318797566410291;bm=9325;sm=9325;cr=97517771;pl=13232385&vid_context=anoutstream;anbannerstream;anoverlayplayer]]></VerificationParameters></Verification></AdVerifications></Extension></Extensions></InLine></Ad></VAST>

**Comment by dioramayuanito** [comment]
sorry i gave you wrong information. we discuss this issue in videojs-ima

**Comment by yashraj-02** [comment]
Cool. This is resolved. This is an issue with the CSS on the webpage. Basically, there's a rule with `div: { position: relative }` on the page and that is causing the issue. It's resolved now.
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/75726876/208624242-1067f5a7-7b6f-4694-aab1-61f31086c7db.png">

**Comment by dioramayuanito** [comment]
> Cool. This is resolved. This is an issue with the CSS on the webpage. Basically, there's a rule with `div: { position: relative }` on the page and that is causing the issue. It's resolved now.
> <img width="1382" alt="image" src="https://user-images.githubusercontent.com/75726876/208624242-1067f5a7-7b6f-4694-aab1-61f31086c7db.png">
> 
> 
> 

Good Job 👍👍👍
