### ISSUE TITLE
Importing CDN to a regular HTML/JS setup results in no style / broken style

### ISSUE THREAD

**Issue by Jurugi** [videojs/video.js#8059]
![image](https://user-images.githubusercontent.com/33045184/209445663-65194102-b31a-44bd-a1d8-06fce8b15b71.png)

Using the remote CDN as described https://videojs.com/getting-started/, and then calling: 
videojs(id, {controls: true,autoplay: false,preload: 'auto' }); to transform the video stream.
It does seem the code is working, it even detects I am using a stream, but the styling is completely not working.
It is using NodeJS but this is all local, no server-side magic happening, just added the lines to the html that is sent, then browser reads html/js and runs it. Just a basic index.html with javascript, but thought I'd that detail.
Also noted it seems the .css is running and has effect, positions work, it just isn't properly displaying the buttons/styling.
And confirmed removing 'all' CSS or placing it at the bottom of <head> so it overrides things does not work.

**Comment by amtins** [comment]
Hi @Jurugi , I followed the instructions provided in the getting started and I got the expected result. Does the video tag contain the `video-js` css class? It is this css class that will apply the style to the player.

Here is what I did to try to reproduce your issue:
```bash
mkdir videojs-getting-started
cd videojs-getting-started
touch index.html
```

Then I opened the `index.html` file and I pasted the following code:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://vjs.zencdn.net/7.20.3/video-js.css" rel="stylesheet" />

    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <!-- <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script> -->
</head>

<body>
    <!-- https://videojs.com/getting-started/ -->
    <video id="my-video" class="video-js" width="640" height="264">
        <source src="https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8"
            type="application/x-mpegURL" />
        <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a
            web browser that
            <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
    </video>

    <script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
    <script>
        const player = videojs('my-video', {
            controls: true,
            autoplay: false,
            preload: 'auto'
        });
    </script>
</body>

</html>
```
The code above is from the getting started page but I modified it to look like what you described. However the video tag contains the `class="video-js"`.

Finally, to make sure everything works as expected from the `videojs-getting-started` folder run the command:
```bash
npx http-server
```

The page should be accessible from `http://127.0.0.1:8080`.

**Comment by Jurugi** [comment]
I still have no idea why that happened but I switched to OpenPlayerJS and it worked much better and just customized it. VideoJS is good I'm sure but such an issue happening for no reason is weird. One thing to note is I didn't have static video, I have streaming vids that dynamically are made (create element) so then called videojs init on them. The styling .css loaded, I could remove the css file and the icons would change positions. I think the classname was still there and adding video-js class to it did not work, it was clearly recieving the css positioning but not the styling for some reason. This was also live on a https/ssl server linux Ubuntu etc.. Anyway whateva.
