### ISSUE TITLE
Captions/Subtitles are not displaying in Fullscreen-mode on Safari IOS

### ISSUE THREAD

**Issue by LuoyeAn** [videojs/video.js#8061]
### Description

Hi, developers! I see what you worked on the problem #7356  , but she is still there, on my devices.

### Reduced test case

https://codesandbox.io/s/keen-montalcini-qmxfet?file=/src/VideoPlayer.js

### Steps to reproduce

Play video on mobile Safari
IOS set fullscreen mode
Captions are not displaying

### Errors

tried to use html5: {nativeTextTracks: false}, it works on iPhone when the video is not fullscreen, but the subtitle will hidden after I calicked the fullscreen button.

if without { nativeTextTracks: false }, it will  always not show the subtitle whether full screen or not.

### What version of Video.js are you using?

7.20.3

### Video.js plugins used.

none

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

iPhone12  & iOS16.0.3

**Comment by mister-ben** [comment]
As explained in the other issue, if you use `nativeTextTracks: false` on iPhone you cannot have subtitles in fullscreen. It's not possible to overlay anything over the video.

**Comment by LuoyeAn** [comment]
I didn't use `nativeTextTracks: false`， please see [my demo](https://codesandbox.io/s/keen-montalcini-qmxfet?file=/src/VideoPlayer.js)

**Comment by mister-ben** [comment]
As the console message says, crossorigin isn't set. That can stop Safari laoding the track. You can add `crossOrigin="anonymous"`
