### ISSUE TITLE
why the subtitles setting can't see the word??

### ISSUE THREAD

**Issue by friendtasy** [videojs/video.js#8074]
### Description

just like following below image
<img width="586" alt="屏幕截图 2023-01-17 165120" src="https://user-images.githubusercontent.com/17196859/213118754-b2a3e571-15ed-40ac-b9f1-9127a7884b26.png">

### Steps to reproduce

1.on the website play includ subtitles video
2.
3.

### What version of Video.js are you using?

 * Video.js 7.20.3 <http://videojs.com/>

### Video.js plugins used.

videojs-contrib-quality-levels.min，videojs-http-source-selector.min

### What browser(s) including version(s) does this occur with?

chrome 109

### What OS(es) and version(s) does this occur with?

windows 11

**Comment by gkatsev** [comment]
Looks like some style interference from global styles and video.js styles. If you can create a minimal live test example page, we could add these styles to our minimal internal css reset. Alternatively, you can add some CSS yourself to change the text of the select of black as a workaround.

**Comment by friendtasy** [comment]
> Looks like some style interference from global styles and video.js styles. If you can create a minimal live test example page, we could add these styles to our minimal internal css reset. Alternatively, you can add some CSS yourself to change the text of the select of black as a workaround.

can't i put the html content in here? test example page not easy to do.

**Comment by friendtasy** [comment]
<img width="626" alt="3" src="https://user-images.githubusercontent.com/17196859/213065083-4647a1d8-1427-45b2-8530-49918035b886.png">

**Comment by friendtasy** [comment]
<img width="389" alt="屏幕截图 2023-01-19 100712" src="https://user-images.githubusercontent.com/17196859/213338954-d8a749cb-d6e6-4855-a10d-a444c7f307d1.png">
i found than css inherit by bootstrap.min.css about button input optagroup select systle,just cancel about color affect,that word would be see.how can i do somethin in html?

**Comment by friendtasy** [comment]
i don't know it is best way to solve this problem,in my <script> add one-line command document.getElementsByClassName("vjs-modal-dialog-content")[0].setAttribute('style','color:#000000')，any way ,it sole.

**Comment by misteroneill** [comment]
Glad you were able to solve your issue. As @gkatsev said, it looks like a CSS conflict and not an issue with Video.js.
