### ISSUE TITLE
about volume location not at centre

### ISSUE THREAD

**Issue by friendtasy** [videojs/video.js#8077]
### Description

the volume location not at centre,anywhere active or noactive.
the html
<link href="https://unpkg.com/video.js/dist/video-js.min.css" rel="stylesheet">
<script src="https://unpkg.com/video.js/dist/video.min.js"></script>

<video class="video-js vjs-default-skin vjs-big-play-centered" height="450px" id="video" width="720px" webkit-playsinline playsinline>您的浏览器不支持 video 标签。</video> <p id="currentplay" style="font-size:18px;"></p>

<script>
    var player = videojs('video',{
        controlBar: {volumePanel: {inline: true}},
        muted: false,
        bigPlayButton: true,
	    controls : true,
	    loop : false,
	    language: 'zh-CN',
	    errorDisplay: false,
	    playbackRates: [0.5, 1, 1.5, 2,2.5,3],
	    TitleBar: {'text':''},
            }
            );
 player.src("https://xx.mp4");
</script>
in chorme edge firefox just like than
<img width="201" alt="1" src="https://user-images.githubusercontent.com/17196859/213069158-47272521-6d1a-4e2c-bd6a-788f718dd1db.png">
<img width="182" alt="2" src="https://user-images.githubusercontent.com/17196859/213069179-5fd29527-a28d-4a40-b256-78293d17ff9c.png">
<img width="165" alt="3" src="https://user-images.githubusercontent.com/17196859/213069185-c7c39c0c-8d6f-482f-a5c9-28f7e3dc1336.png">

even in virtual machine win11 100% zoom just like than.may be in chinaese would like than?
the test html,if test change the src
[新建 文本文档 (3).txt](https://github.com/videojs/video.js/files/10441523/3.txt)
i had not idea but change the style let the dot not show
/* css how to hide little circle in progressbar */

.vjs-icon-circle:before, .vjs-seek-to-live-control .vjs-icon-placeholder:before, .video-js .vjs-volume-level:before, .video-js .vjs-play-progress:before {

content: "";

}

### Steps to reproduce

1.website play video
2.
3.

### What version of Video.js are you using?

7.20

### What browser(s) including version(s) does this occur with?

chrome 109

### What OS(es) and version(s) does this occur with?

windows11

**Comment by mister-ben** [comment]
That can happens when the browser language is Chinese, that changes something about font sizing. It's fixed in version 8, with the changes in #7990

**Comment by friendtasy** [comment]
> That can happens when the browser language is Chinese, that changes something about font sizing. It's fixed in version 8, with the changes in #7990

thank you hard work~,i will waitting~,actyllay this thing i thoght it native html5 better,always be centre

**Comment by wseymour15** [comment]
Closing this ticket, as it looks to be resolved.
