### ISSUE TITLE
VideoJS with AngularJS

### ISSUE THREAD

**Issue by terrykfwong** [videojs/video.js#808]
First of all, thank you for this awesome plugin :)

I am working with AngularJS with VideoJS, I have created a directive

```
.directive('videojs', function () {
    var linker = function (scope, element, attrs){
            attrs.type = attrs.type || "video/mp4";

            var setup = {
                'techOrder' : ['html5', 'flash'],
                'controls' : true,
                'preload' : 'auto',
                'autoplay' : false,
                'height' : 480,
                'width' : 854
            };

            var videoid = 107;
            attrs.id = "videojs" + videoid;
            element.attr('id', attrs.id);
            element.attr('poster', "http://10.1.21.36:8080/Testube/media/" + videoid + ".jpg");
            var player = _V_(attrs.id, setup, function(){
                var source =([
                    {type:"video/mp4", src:"http://testube:8080/Testube/media/" + videoid + ".mp4"}
                ]);
                this.src({type : attrs.type, src: source });
            });
        }
    return {
        restrict : 'A',
        link : linker
    };
});
```

And in the partial HTML I have

```
    <video videojs class="video-js vjs-default-skin vjs-controls-enabled vjs-has-started vjs-paused vjs-user-inactive" ng-model="video">
    </video>
```

The first time I visit the page, videoJS render the control successfully, however, the second time I visit the same page, it doesn't render it at all unless I do a full page reload. For example, if I visit video 107, and visit video 108, they both render successfully, but if I go back to video 107, it would not render. The _V_ method is called, but it's not changing the DOM.

I couldn't create a demo on jsbin because it involves more than one page. This is the first time I am filing a issue report on github, please let me know if I have done anything wrong, thank you very much.

**Comment by LonnyGomes** [comment]
I know this is a pretty stale issue, but if anyone is interested I created an angular directive called [vjs-video](http://lonnygomes.github.io/vjs-video/) that addresses the several "gotchas" that could occur when using video.js with angular. 

It properly disposes of the player when the directive is destroy (as @mmcc pointed out should happen) and adds angular functionality such as bindable media sources.

**Comment by mmcc** [comment]
@LonnyGomes Sweet! Any chance you're going to update this for 5.0?

**Comment by LonnyGomes** [comment]
@mmcc yup, it isn't using browserfy or anything but it does support 5.x as well as 4.x. I should probably make that more clear in the documentation!
