### ISSUE TITLE
Subtitles not working on video.js

### ISSUE THREAD

**Issue by NeoCsatornaja** [videojs/video.js#809]
I tryed make subtiltes for a video,but not working on the player.
You can see what happen in here:
http://neocsatblog.mblx.hu/embeds/biber.php
My .vtt file place:
http://www.neocsatblog.mblx.hu/embeds/srts/eng/alive.vtt
You see?
Only one thing visible, the loading image...

**Comment by elfaxvaxec** [comment]
I'm very sorry, I have not worked default subtitle
