### ISSUE TITLE
Problems with MUIU Browser/Samsung Internet - "Play() can only be initiated by a user gesture"

### ISSUE THREAD

**Issue by MatheusLopesDev99** [videojs/video.js#8095]
### Description

Hey Guys, i am experiencing some issues using the Video.JS

I am trying to play the video when the user clicks on the custom button but returns the error

"Play() can only be initiated by a user gesture".

Happens with the Samsung Browser and MIUI Browser.

Here is the CodeSandBox:

https://codesandbox.io/s/suspicious-hellman-5mjfhf?file=/src/App.js

### Reduced test case

https://codesandbox.io/s/suspicious-hellman-5mjfhf?file=/src/App.js

### Steps to reproduce

1.Access the codesandbox
2. Click on the button
3. Access with the Samsung Browser or MUIU Browser

### What version of Video.js are you using?

7.2.11

### Video.js plugins used.

Vimeo

### What browser(s) including version(s) does this occur with?

MIUIU Browser and Samsung Internet

### What OS(es) and version(s) does this occur with?

MIUIU Browser and Samsung Internet

**Comment by mister-ben** [comment]
For the browser to consider the user gesture when allowing playback of the video element inside the vimeo iframe, all parent iframes must have `autoplay` in its `allow` attribute. Although the vimeo iframe has that, the code sandbox preview iframe does not.

If you go directly to [https://5mjfhf.csb.app/](https://5mjfhf.csb.app/) the browser acknowledges the user gesture, and can play.
