### ISSUE TITLE
Video player issue on IOS 

### ISSUE THREAD

**Issue by Gsk6** [videojs/video.js#8107]
1. Does a vertical player exist?
2. Does the mp4 file itself contain information on whether it was taken in horizontal or vertical mode?
3. Set a parameter to determine whether the video was shot in horizontal or vertical mode, and display the playback player in horizontal or vertical  mode according to that parameter.

**Comment by mister-ben** [comment]
You can create a "vertical" player with the class `vjs-9-16` or setup option `"aspectRatio": "9:16"`.
The video element, and Video.js in turn, can get the video dimensions at `loadedmetadata`, with  `player.videoWidth()` and `player.videoHeight()`. However on iOS `loadedmetadata` may not occur until playback starts as preloading video is blocked by the browser.
You can use fluid mode (`vjs-fluid`) to have the player automatically resize to fit the aspect ratio once those dimensions are detected, which again might not be until playback starts, but resizing elements and causing other content to reflow is considered a bad thing by page optimization tools like Lighthouse. Setting the player to the video's aspect ratio when it's created would be better from that point of view.
