### ISSUE TITLE
Calling Ressources of vjs v8.0.3 get back a 403 Forbidden

### ISSUE THREAD

**Issue by tboiteux** [videojs/video.js#8111]
Hello all

I'm having a bug while trying to use the loader with the CDN ressources. I noticed this bug has already been seen on some tickets, usually whenever a new version of videojs is released.

**Description**
Following the getting started steps here https://videojs.com/getting-started/#videojs-cdn

**Steps to reproduce**
1. Follow the getting started steps
2. Player fails because the cdn remote resource returns http 403 denied

**Results**
_Expected_
CDN listed in getting started guide should be able to load

_Actual_
Returns access denied

_Error output_
GET https://vjs.zencdn.net/8.0.3/video.js net::ERR_ABORTED 403

Can you see to it please ?

**Comment by misteroneill** [comment]
Thanks for the report!

URLs with 8.0.3 should be resolving now.

8.0.2, 8.0.1, and 8.0.0 will be fixed next for historical purposes.

**Comment by tboiteux** [comment]
Thank you, it working again :)
