### ISSUE TITLE
Video fails to play on iPhone if default `track` lacks `src`

### ISSUE THREAD

**Issue by htwyford** [videojs/video.js#8118]
### Description

When playing a video with a `track` that contains the `default` attribute but not the `src` attribute, the video buffers endlessly but does not log an error. A minimal example is available [here](https://jsfiddle.net/ag9wL2ze/2/).

In my project, I only have a URL pointing to a WebVTT file if that video has subtitles. I render the video with React like this
```
<video src="https://..." ...>
  <track default src={myWebVttUrl}>
</video>
```
When `myWebVttUrl` is undefined, the `src` attribute is not rendered and the bug occurs. This issue does not reproduce when using a bare non-VideoJS `video` tag, so it's an issue within VideoJS.

### Reduced test case

https://jsfiddle.net/ag9wL2ze/2/

### Steps to reproduce

1. Create a `video` element containing a `track`
2. Set the `default` attribute on the track but omit the `src` attribute
3. Attempt to play the video on an iPhone, or in the Xcode Simulator

### What version of Video.js are you using?

My project uses 7.10.2. Also reproducible in whatever version JSFiddle uses.

### What browser(s) including version(s) does this occur with?

All versions of Safari on iPhone

### What OS(es) and version(s) does this occur with?

All versions of iOS

**Comment by mister-ben** [comment]
It also fails on iOS with a vanilla element if you create a `<video>` with an invalid `<track>` and set the src later with `video.src = '...'. The answer here is to make sure your code omits the track entirely if you don't have a src. You can set a track after player init, similar to how you set src later.

https://videojs.com/guides/text-tracks/#remote-text-tracks

https://videojs.com/guides/text-tracks/#remote-text-tracks
