### ISSUE TITLE
videojs.options not applies to video

### ISSUE THREAD

**Issue by LadyR123** [videojs/video.js#8120]
### Description

at start adding
`   videojs.options.userActions = { click: false };    
    videojs.options.controls = true;  
    videojs.options.preload = "none";`

then adding this to div-container

`<video class="video-js"  poster=" ...
<video class="video-js"  poster=" ...
<video class="video-js"  poster=" ...`

but global settings doesnt apply, why?

### Steps to reproduce

1. add `videojs.options.userActions = { click: false };    
    videojs.options.controls = true;  
    videojs.options.preload = "none";`  to `<script type="text/javascript">`
2. add `<video class="video-js"  poster=" ...
<video class="video-js"  poster=" ...
<video class="video-js"  poster=" ...` to div element via `$(document).ready`
 

### What version of Video.js are you using?

8.0.4

### What browser(s) including version(s) does this occur with?

Chrome 109.0.5414.120

### What OS(es) and version(s) does this occur with?

Win7

**Comment by mister-ben** [comment]
Here's an example of how to use it. Make sure you're not overriding the options elsewhere - embed/player specific options override global options.

https://codepen.io/mister-ben/pen/zYJxabb?editors=1001

**Comment by wseymour15** [comment]
This appears to have been resolved. If this is not the case, please feel free to re-open this ticket.
