### ISSUE TITLE
playback speed on YouTube video

### ISSUE THREAD

**Issue by mishav78** [videojs/video.js#8132]
is there a way to increase or decrease video playback speed of a YouTube video through code not controls. In other words I embed a YouTube video with this player on my blog and automatically want the video to play at 3x.

**Comment by friendtasy** [comment]
player.playbackRates=3

**Comment by mishav78** [comment]
is this in Javascript?

**Comment by friendtasy** [comment]
> is this in Javascript?

yes

**Comment by friendtasy** [comment]
it will work at common video,but youtube video i have not idea about it

**Comment by mister-ben** [comment]
You Tube allows a maximum playback rate of 2. `player.playbackRate(2)`
