### ISSUE TITLE
Does YouTube count views and watchtime made from this player on YouTube videos? 

### ISSUE THREAD

**Issue by mishav78** [videojs/video.js#8133]
Does YouTube count views and watchtime made from this player on YouTube videos?

**Comment by mister-ben** [comment]
Yes. When using the videojs-youtube tech, a youtube player without controls is being used to play the video. Their player will record analytics as usual.

**Comment by mishav78** [comment]
can you increase the playback rate up to 16x just like the other player?

**Comment by mister-ben** [comment]
Youtube doesn't allow the playback rate to be set above 2. `player.playbackRate(2)`

**Comment by mishav78** [comment]
oh okthanks
