### ISSUE TITLE
[PR Proposal] Detect Shadow DOM to avoid false flags 'The element supplied is not included in the DOM'

### ISSUE THREAD

**Issue by BrainCrumbz** [videojs/video.js#8136]
### Description

Hi. We've been through some issues related to the warning `VIDEOJS: WARN: The element supplied is not included in the DOM` and also related to video.js being applied to an element in Shadow DOM. E.g. [this](https://github.com/videojs/video.js/issues/4697#issuecomment-435487577), [this](https://github.com/videojs/video.js/issues/7158#issuecomment-821328694) and also [this](https://github.com/videojs/video.js/pull/5831).

Would you consider a PR that would also take care of the Shadow DOM case when performing the check at [this line](https://github.com/videojs/video.js/blob/2c7eea889a9e4d0cd535f14cfb8a7322717b30c5/src/js/video.js#L152)?

Basically something along the lines of:

```js
const inShadowDom = el.getRootNode() instanceof ShadowRoot;
const rootNode = inShadowDom ? el.getRootNode() : el.ownerDocument.body;

if (!el.ownerDocument.defaultView || !rootNode.contains(el)) {
  log.warn('The element supplied is not included in the DOM');
}
```

Apart from removing the annoying warning, it actually helps to flag a real issue when one does something wrong within Shadow DOM.

Hopefully there should be no need for test case reproduction or steps, the issue seems to be known. Please tell us if they're needed anyway.
Cheers

### Steps to reproduce

1. skipping unless needed

### What version of Video.js are you using?

7.20.3

### Video.js plugins used.

none

### What browser(s) including version(s) does this occur with?

Chrome 109.0.5414.121 (Build ufficiale) (a 64 bit)

### What OS(es) and version(s) does this occur with?

Windows 11

**Comment by gkatsev** [comment]
A PR that improves that to account for the shadow DOM would be welcome!

*Especially*, if you can provide a test along the change.

**Comment by BrainCrumbz** [comment]
We haven't been through video.js testing suite. Are there already some similar test scenarios that we could have a look at?
I mean, some test case that already instantiates a video.js player in a page? Maybe when the video element is added to DOM and when is not yet added to DOM?
Thanks

**Comment by gkatsev** [comment]
Yup, there's even an existing test for the current behavior. Would just need update it or add a new test that accounts for the shadow dom.
https://github.com/videojs/video.js/blob/main/test/unit/video.test.js#L45-L85

**Comment by BrainCrumbz** [comment]
Thanks for the highlight. By any chance, do you think there would be any problem by adding LitElement into the test suite? As that's the web component library we'd use to test the feature.

**Comment by gkatsev** [comment]
I think it would be best to keep it simple with just a native WebComponent element.

**Comment by BrainCrumbz** [comment]
Is there a way we can by-pass the scss path error, so that we can try with the PR? Thanks
