### ISSUE TITLE
iOS > 14 hls not working

### ISSUE THREAD

**Issue by odmro** [videojs/video.js#8138]
### Description

Live videostream fails to load.

On iOS < 15 works as expected - screenshots bellow

![Screenshot from 2023-02-17 19-07-37](https://user-images.githubusercontent.com/5202634/219720481-065aaf76-4db8-435e-80a5-3e2ec955acb5.png)
![Screenshot from 2023-02-17 19-03-19](https://user-images.githubusercontent.com/5202634/219720486-c1bea9d0-3cb7-4126-9722-5c2ef06464b8.png)
![Screenshot from 2023-02-17 19-01-51](https://user-images.githubusercontent.com/5202634/219720491-39441848-b3e3-4dfa-bca1-b07556023f88.png)
![Screenshot from 2023-02-17 19-01-02](https://user-images.githubusercontent.com/5202634/219720493-779ce5e5-fa28-46e0-af67-f86a0fbf56d2.png)
![Screenshot from 2023-02-17 19-00-29](https://user-images.githubusercontent.com/5202634/219720497-935b8b3d-d581-473c-892c-c6ae0919fd03.png)
![Screenshot from 2023-02-17 18-59-39](https://user-images.githubusercontent.com/5202634/219720500-3bebe089-8d4f-4573-a054-bcb3431782af.png)
![Screenshot from 2023-02-17 18-59-03](https://user-images.githubusercontent.com/5202634/219720504-23dee036-33ac-4dcb-ad79-cfd98818b302.png)
![Screenshot from 2023-02-17 18-58-56](https://user-images.githubusercontent.com/5202634/219720508-d65b75ac-3d76-4842-a606-bb649a9bf32b.png)

### Reduced test case

https://stream.alpinexpert.ro/player.php

### Steps to reproduce

1. Open with any iPhone/iPad and IOS > 14
2. Open with any Apple Map (ventura  / monterey)

### What version of Video.js are you using?

8.0.4

### Video.js plugins used.

none

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

iOS > 14

**Comment by mister-ben** [comment]
Where there is a problem, as here, with native playback on Mac Safari and iOS, it's out of Video.js's control and needs to be fixed in the stream itself. I've seen a few issues of this type, such as [this](https://stackoverflow.com/questions/70592081/why-is-my-hls-stream-infinitely-loading-on-ios-15-safari-but-works-fine-on-ios-1) and [this](https://developer.apple.com/forums/thread/690298), but unfortunately I don't know what's specifically upsetting Webkit.

**Comment by odmro** [comment]
The problem was not from you (videojs). Thank you for your input.
