### ISSUE TITLE
Uncaught ReferenceError: X is not defined

### ISSUE THREAD

**Issue by kissjakub** [videojs/video.js#8170]
### Description

video.js 8> Uncaught ReferenceError at video type: `'application/x-mpegURL'`  **after build** react-app

### Packages:
  "react": "^18.2.0",
  "react-scripts": "5.0.1",
  "video.js": 8>,

### Description:
- npm run start - WORKS WELL
- npm run build - Uncaught ReferenceError
- npm run build - (using `video.js 7.x.x`) - ALSO WORKS WELL

### Code snippet:
`player.src({
  src: "//vjs.zencdn.net/v/oceans.mp4",
  type: "application/x-mpegURL",
})`

### Steps to reproduce

1. create react app
2. use video.js 8>
3. write code that should play video with type: `application/x-mpegURL`
4. `npm run build`
5. serve `build` folder
6. **Uncaught ReferenceError** - when starting the video

### Errors

Uncaught ReferenceError: X is not defined
![image](https://user-images.githubusercontent.com/34818570/222383614-b6c21454-5e3a-4f66-aedb-86f40b395e49.png)

### What version of Video.js are you using?

8>

### What browser(s) including version(s) does this occur with?

110.0.5481.178 

### What OS(es) and version(s) does this occur with?

Windows 11

**Comment by mister-ben** [comment]
Any MP4 wou;dn't work if you loaded it as type application/x-mpegURL. If you're actually using an HLS video, a reduced test case with an unminified Video.js would be useful.

**Comment by kissjakub** [comment]
Surprisingly it works in video.js 7  - `mp4` video higher ^^ & `application/x-mpegURL`

I normaly use videojs for play `application/x-mpegURL` videos .. I found another example video:

`player.src({ src: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8", type: "application/x-mpegURL" })`

^^ does not work in video.js 8.. but only when I build react app and serve it using express.. If I run react app on my local computer then playback works

I also tried: 
1. clone video.js repo
2. change `@videojs/http-streaming` package to 2.16.x version
3. build video.js
4. build my react app

And it works ^^ .. So problem may be in `@videojs/http-streaming` 3>

**Comment by kissjakub** [comment]
> I was able to player that source (`player.src({ src: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8", type: "application/x-mpegURL" })`) on https://videojs-preview.netlify.app/sandbox/index.html, which uses Video.js 8 and VHS 3.0.2.
> 
> Also, `player.src({ src: "//vjs.zencdn.net/v/oceans.mp4", type: "video/mp4", })` works, but `player.src({ src: "//vjs.zencdn.net/v/oceans.mp4", type: "application/x-mpegURL", })` does not.
> 
> Can you provide a minimal live test case? We likely won't be able to help anymore without one.

Please see **Steps to reproduce**.. it occurs only after react app build.. you will need create react app and build it..

**Comment by tzarebczan** [comment]
A quicker workaround may be to replace the x-mpegURL type with video/mp4, that may work per the comment above. 

Running into the same issue here at https://github.com/OdyseeTeam/odysee-frontend in an uncommited branch.

**Comment by khowling** [comment]
> A quicker workaround may be to replace the x-mpegURL type with video/mp4, which may work per the comment above.
> 
> Running into the same issue here at https://github.com/OdyseeTeam/odysee-frontend in an uncommitted branch.

Thanks  for workaround suggestion!  Doesn't work for my reolink feed unfortunately CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED.

**Comment by tzarebczan** [comment]
We tried this too earlier today, same issue. 

Hoping the team can figure this one out soon.

@gkatsev do you think it's in http-streaming or here?

**Comment by mister-ben** [comment]
Please add a link to a [reduced test case](https://stackoverflow.com/help/mcve). Here the error does not occur in a simple react app: https://codesandbox.io/s/react-videojs-strictmode-v8-gkk5eh?file=/src/App.js

**Comment by kissjakub** [comment]
@mister-ben 
https://github.com/kissjakub/videojs-testcase

1. clone ^^
2. `npm i`
3. `npm run build`
4. `node server.js`
5. go to: http://localhost:3000/

**Comment by mister-ben** [comment]
<img width="382" alt="grafik" src="https://user-images.githubusercontent.com/1676039/225753713-7d11843f-b58d-4690-a207-6b6d22208403.png">

This is [in aes-decrypter](https://github.com/videojs/aes-decrypter/blob/6f0cbd92c65b28e1ec7b54a605cb1c2c270dd512/src/aes.js#L197).

**Comment by tzarebczan** [comment]
Any more progress on this? It's holding back our upgrade to v8.

**Comment by mister-ben** [comment]
This is the same as the issue discussed at mapbox/mapbox-gl-js/issues/10173 and mapbox/mapbox-gl-js/issues/10565: the transpiled classes are broken in workers. The undefined function is `_createClass`.

Mapbox's solutions also work here. See https://docs.mapbox.com/mapbox-gl-js/guides/install/#targeting-transpilation-to-es6-with-browserslist for details, but basically use one of these:

Set the production `browserslist` to

```
      ">0.2%",
      "not dead",
      "not op_mini all",
      "not safari < 10",
      "not chrome < 51",
      "not android < 5",
      "not ie < 12"
```


Or when importing videojs use the ! syntax 
```
// eslint-disable-next-line import/no-webpack-loader-syntax
import videojs from "!video.js";
```

**Comment by smithyj** [comment]
good

**Comment by simida0852** [comment]
reduced version to 8.2.0 and it works. hope it helps!

**Comment by Impre-visible** [comment]
> reduced version to 8.2.0 and it works. hope it helps!

I just tried with version 8.2.0, same problem. I can play a video when running the app, but if the app is builded, don't work

**Comment by mister-ben** [comment]
See the comment above, which is also documented at https://videojs.com/guides/webpack/

You will need to ensure the build process does not break the code that is used in service workers. The react boilerplate app's default configuration will not work.

**Comment by thestanislav** [comment]
For vite users, adding this lines to vite.config.ts helped me
```
 build: {
        minify: 'terser',
        mangle : {
                toplevel: false,
        }
}
```
