### ISSUE TITLE
TypeScript: Property 'on' does not exist on type 'Player'

### ISSUE THREAD

**Issue by knpwrs** [videojs/video.js#8178]
### Description

With the following code:

```ts
const player = videojs(document.querySelector('video'));

player.on('timeupdate', () => {
  console.log('timeupdate');
});

player.one('play', () => {
  console.log('play')
});
```

TypeScript says `Property 'on' does not exist on type 'Player'` and `Property 'one' does not exist on type 'Player'`. Despite this, the code works as expected in the browser.

### Steps to reproduce

1. Install video.js: `npm i video.js`
2. Try the code above
3. Check with `tsc`

Alternatively, look at the type definitions. Sure enough, there are no `on` or `one` methods on `Player` or `Component`.

### What version of Video.js are you using?

8.0.4

### What browser(s) including version(s) does this occur with?

N/A

### What OS(es) and version(s) does this occur with?

macOS 13.1

**Comment by mister-ben** [comment]
This was resolved in 8.2.0 with an update to the type definitions

**Comment by Santoshah** [comment]
I am also facing same issue. Also the type Player has been remove from the videojs. Now I need to import Player from `import Player from "video.js/dist/types/player";` Please fix .on in type player. its throwing error. The latest version is still 8.0.4. I cannot find 8.2

**Comment by Florinstruct** [comment]
Yes, the type definitions in `video.js/dist/types/player` are way outdated. Methods like `ended()` or `readyState()` are not even in there.

You could use the unofficial types from [https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/video.js](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/video.js). Those include the missing methods at least, but they're for Video.js 7.3 and I'd rather have official, current type definitions.

**Comment by pratikexwzd** [comment]
Hi , the typescript definition of 8.0.4 is still lacking alot of stuff . When would 8.2.0 be available via npm?

**Comment by leo-paz** [comment]
> Hi , the typescript definition of 8.0.4 is still lacking alot of stuff . When would 8.2.0 be available via npm?

bump

**Comment by gkatsev** [comment]
8.2.0 (and newer) is available on npm. https://www.npmjs.com/package/video.js/v/8.2.0

**Comment by leo-paz** [comment]
@gkatsev should 8.2.0 fix the component issue i was getting above? I updated but still see it
