### ISSUE TITLE
plugin "httpSourceSelector" does not exist

### ISSUE THREAD

**Issue by jeffreycao1998** [videojs/video.js#8188]
### Description

I'm trying to get the `videojs-http-source-selector` package to work
- I imported the two packages, `videojs-contrib-quality-levels` and `videojs-http-source-selector`
- I create the player with `videojs(element, { plugins: { httpsSourceSelector: {} } })`
- load my site and I get the error `plugin "httpSourceSelector" does not exist`
- if I remove it then the video works fine

I also tried registering the example plugin and it seems like it worked but according to the docs [here](https://videojs.com/guides/plugins/#the-player-plugin-name-property) there should be a method called `examplePlugin` but it doesn't exist when I log the player

![Screenshot 2023-03-12 at 11 28 27 PM](https://user-images.githubusercontent.com/25717421/224615606-4e42d828-de01-4984-b60e-7fa3353ef2f1.png)

### Steps to reproduce

1. I imported the two packages, `videojs-contrib-quality-levels` and `videojs-http-source-selector`
2. I create the player with `videojs(element, { plugins: { httpsSourceSelector: {} } })`
3. load my site and I get the error `plugin "httpSourceSelector" does not exist`
4. if I remove it then the video works fine

### Errors

plugin "httpSourceSelector" does not exist

### What version of Video.js are you using?

8.0.4

### Video.js plugins used.

httpSourceSelector

### What browser(s) including version(s) does this occur with?

Chrome

### What OS(es) and version(s) does this occur with?

MacOS

**Comment by gkatsev** [comment]
Looks like videojs-http-source-selector depends on video.js 7. So, if you downgrade to latest v7 of Video.js in your project, it should work.
alternatively, it should be possible to use npm to force video.js 8 for videojs-http-source-selector.

**Comment by jeffreycao1998** [comment]
Okay, upgraded from `7.0.0` to `7.21.3` and it seemed to fix the problem where it wasn't being initialized. I'm still not getting the quality selector to show up though. I get this line printed to the console saying `player.videojs_http_source_selector_initialized == false`. It seems like it's initially true and then gets flipped to false for some reason, it's true when I logged the `player` right after creating it from videojs(...args).

I had this same problem with using `@mux/videojs-kit`

![Screenshot 2023-03-13 at 10 49 15 AM](https://user-images.githubusercontent.com/25717421/224770707-9de5806b-b8dd-40a9-a998-f975b5abe2f1.png)

**Comment by jeffreycao1998** [comment]
I'm also not seeing the `examplePlugin` or `httpsSourceSelector` methods on the player 🤔

**Comment by gkatsev** [comment]
Can you make a test page on something like codesandbox.io?

**Comment by jeffreycao1998** [comment]
@gkatsev https://codesandbox.io/s/videojs-mux-kit-react-forked-mxj4f3?file=/src/App.js

**Comment by jeffreycao1998** [comment]
Just noticed that in the codesandbox the two methods for the plugins ARE showing up. But it still isn't locally. Any ideas on anything I could try?

**Comment by jeffreycao1998** [comment]
Downgrading to 7.x.x fixed the issue. The other issue I was having was because I wasn't using a m3u8 file for the source of the player

**Comment by friendtasy** [comment]
you could vistor this https://github.com/FreeTubeApp/videojs-http-source-selector,it's work ok with at video.js 8
