### ISSUE TITLE
Playing different audio files for a video file

### ISSUE THREAD

**Issue by newyork-anthonyng** [videojs/video.js#8198]
I wanted to check if the below is possible.

I have a video file (video.mp4) with no audio.
I have 2 audio files (lang1.m4a, lang2.m4a). 

Can I use video.js to play the video with one of the audio files? And keep them in sync?

I've seen a [StackOverflow](https://stackoverflow.com/questions/48515994/how-to-add-an-audiotrack-in-video-js/48516544#48516544) where someone posted a solution that does it. But it doesn't work for me.

Also, in the [videojs/audio-tracks guide](https://videojs.com/guides/audio-tracks/#caveats), it says:
> Video.js only stores track representations. Switching audio tracks for playback is not handled by Video.js and must be handled elsewhere - for example, [http-streaminfg](https://github.com/videojs/http-streaming) handles switching audio tracks to support track selection through the UI.

But I'm pretty sure it's referring to HLS and DASH formats. I just wanted to confirm.

**Comment by gkatsev** [comment]
Yup, the audio tracks are basically for HLS/DASH or if an mp4 has multiple audio tracks internally and the browser exposes it.

I definitely would recommend trying to generate HLS/DASH over trying to sync audio and video in separate media elements client-side, if at all possible.
