### ISSUE TITLE
Player not falling back to supported format

### ISSUE THREAD

**Issue by DusanMilko** [videojs/video.js#8204]
### Description

When using transparent videos, videojs is not falling back to the supported format.

Created a videojs example with mp4, followed by webm video.
Safari and Chrome work with mp4 file.
Firefox throws error and fails to use webm which would work:
"The media could not be loaded, either because the server or network failed or because the format is not supported."

https://codepen.io/dusanmilko/pen/xxayjbo

### Reduced test case

https://codepen.io/dusanmilko/pen/xxayjbo

### Steps to reproduce

1. Create video-js element
2. Add mp4 as first source, webm as second source (when I used transparent video mp4, the mp4 will fail and should fallback to webm. Non transparent mp4 does not fail in firefox)
3. Firefox fails at mp4, and does not try loading webm

### Errors

The media could not be loaded, either because the server or network failed or because the format is not supported.

### What version of Video.js are you using?

7.18.0

### What browser(s) including version(s) does this occur with?

Firefox 111.0.1

### What OS(es) and version(s) does this occur with?

Mac OS 13.2.1

**Comment by gkatsev** [comment]
Try setting `retryOnError` as a player option. It's the default in Video.js 8.

**Comment by gkatsev** [comment]
The API docs reflect Video.js 8 right now, but it was an option that was available. but, yes, just tried it on your codepen and it works.
