### ISSUE TITLE
in 8.x version vide.js/dist/video.js includes es6 syntax，webpack error

### ISSUE THREAD

**Issue by smithyj** [videojs/video.js#8205]
### Description

in 8.x version vide.js/dist/video.js includes es6 syntax，webpack error

### Steps to reproduce

1.in 8.x version vide.js/dist/video.js includes es6 syntax，webpack error
2.
3.

### What version of Video.js are you using?

8.0.4

### What browser(s) including version(s) does this occur with?

Chrome 100

### What OS(es) and version(s) does this occur with?

Mac

**Comment by mister-ben** [comment]
Webpack/Babel's transpiling of ES6 classes can break Video.js. See [this comment](https://github.com/videojs/video.js/issues/8170#issuecomment-1480370207) for how to ensure that the classes are left intact.
