### ISSUE TITLE
video.js:23 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video. in chromium v 38

### ISSUE THREAD

**Issue by AbbasAlsbihawi** [videojs/video.js#8208]
### Description

how to fix this and any verion using in  browser chromium version
 38

### Steps to reproduce

1.chromium v 38
2.
3.

### What version of Video.js are you using?

chromium v 38

### Video.js plugins used.

chromium v 38

### What browser(s) including version(s) does this occur with?

chromium v 38

### What OS(es) and version(s) does this occur with?

chromium v 38

**Comment by mister-ben** [comment]
What codecs are you using? Chromium has poorer support than most browsers, including Chrome. Notably it does not support h264.
https://www.chromium.org/audio-video/

**Comment by KaKi87** [comment]
Hello,

I'm experiencing the same issue on Chromium 112.0.5614.0, using an `*.m3u8` URL as `src` and `application/x-mpegURL` as `type`.

Thanks

**Comment by mister-ben** [comment]
Chromium doesn't support h264, so it can't play HLS/m3u8. While there are ways to build Chromium with additional codec support, you can't rely on end users having done that.

**Comment by KaKi87** [comment]
So this project doesn't add support ?

https://github.com/videojs/http-streaming
