### ISSUE TITLE
没见过这么难用的文档的

### ISSUE THREAD

**Issue by Superman-wc** [videojs/video.js#8231]
### Description

没见过这么难用的文档的
没见过这么难用的文档的

没见过这么难用的文档的

没见过这么难用的文档的
没见过这么难用的文档的

### Reduced test case

https://www.baidu.com

### Steps to reproduce

1.没见过这么难用的文档的
2.没见过这么难用的文档的
3.没见过这么难用的文档的

### Errors

没见过这么难用的文档的
没见过这么难用的文档的
没见过这么难用的文档的

### What version of Video.js are you using?

7.21.0

### What browser(s) including version(s) does this occur with?

Chrome 100

### What OS(es) and version(s) does this occur with?

MAC OS

**Comment by Superman-wc** [comment]
<img width="1855" alt="image" src="https://user-images.githubusercontent.com/11311755/230608748-505e31c1-6386-4830-80f3-db0daa50ee84.png">
这些都是什么玩意？

**Comment by Superman-wc** [comment]
这个文档完全没什么用， 这是我见过最难让人接受的文档

**Comment by Superman-wc** [comment]
想看7.X版本的文档，根本无从下手

**Comment by Soo-For** [comment]
文档还不如腾讯的。服气了

**Comment by dev-dingxue** [comment]
Unable to understand the order and content of the document, unable to find direction。

**Comment by philjhale** [comment]
If you want help with a problem you are having please open a new issue that complies with [our code of conduct](https://github.com/videojs/video.js/blob/main/CODE_OF_CONDUCT.md) and we will be happy to help.
