### ISSUE TITLE
The latest tag on npm has not been updated to v8.3.0

### ISSUE THREAD

**Issue by smorimoto** [videojs/video.js#8239]
As the title says...

That makes Renovate and something others unable to create version bump PR correctly, and yarn's update feature displays weird prompt 🤷‍♂️

<img width="809" alt="image" src="https://user-images.githubusercontent.com/38746192/232121737-02ae9490-28dc-4c46-b01c-832a3f074a87.png">

**Comment by smorimoto** [comment]
<img width="765" alt="Screenshot 2023-04-15 at 3 02 10" src="https://user-images.githubusercontent.com/38746192/232122577-eefb9487-2f1c-41ca-89c5-907e37fd8a85.png">

**Comment by philjhale** [comment]
@smorimoto Thanks for reporting this issue. Video.js 8.3.0 now has the _latest_ tag.

**Comment by amtins** [comment]
@philjhale it seems that the release note [8.3.0](https://github.com/videojs/video.js/releases/tag/v8.3.0) is still marked as `pre-release`.

**Comment by philjhale** [comment]
@amtins Updated, thank you.
