### ISSUE TITLE
How can I deactivate it?

### ISSUE THREAD

**Issue by anmvdev** [videojs/video.js#8241]
### Description

Hi, it's a simple problem, but with little knowledge of HTML,CSS,JS is a bit complicated to hide or disable this section, I only get ineffective results and design errors, the issue is that I want to disable the volume drop down bar on mouse over, and just leave the icon to apply mute or sound when I want.

This is what it looks like today:
![ezgif-5-b0f2e7a084](https://user-images.githubusercontent.com/102996815/232291186-b32d03ef-b309-4bff-8b4f-1e14f09fc252.gif)

And I want something like that:
![ezgif-5-c9b6a649f5xx](https://user-images.githubusercontent.com/102996815/232292454-ab89ec49-33cc-412b-9702-b3e1257eb4c0.gif)

### Reduced test case

https://codepen.io/anmvcode/pen/XWxdoGg

### Steps to reproduce

1.
2.
3.

### What version of Video.js are you using?

7.14.3

### Video.js plugins used.

videojs-http-streaming.js, videojs-playlist.min.js

### What browser(s) including version(s) does this occur with?

Edge

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by mister-ben** [comment]
- Remove `data-setup="{}"` from the video element. You don't want to use auto setup as you're using the constructor with options.
- Add `controlBar: { volumePanel: false }`  to your `options` object.
- Add a MuteToggle the same way you add your other buttons: `player.getChild('controlBar').addChild('MuteToggle', {}, 3);`

**Comment by anmvdev** [comment]
@mister-ben Thanks for the information, now it works exactly as I wanted it to.
[https://codepen.io/anmvcode/pen/XWxdoGg](url)

**Comment by anmvdev** [comment]
I just noticed a small detail, when I stop using the cursor, the controls and progress bar are not automatically hidden, could it be due to the recent configuration?

**Comment by anmvdev** [comment]
Ah sorry, I left the property "inactivityTimeout" in "0", I consider it solved, thanks.
