### ISSUE TITLE
Safari, S3, CloudFront: MEDIA_ERR_SRC_NOT_SUPPORTED - works in Chrome and Firefox

### ISSUE THREAD

**Issue by strugman** [videojs/video.js#8246]
Hello
I know this error has been reported multiple times, but none of the issues I've read has helped me.
I host a MP4 file on AWS S3 and make it available via AWS CloudFront.
It works perfectly fine in Chrome and Firefox, but in Safari I get this error (sorry about polish texts):

```
[Error] VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "The media could not be loaded, either because the server or network failed or because the format is not supported." – i {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported.", status: null, …}

{code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported.", status: null, MEDIA_ERR_CUSTOM: 0, MEDIA_ERR_ABORTED: 1, …}i
	(anonimowa funkcja) (video.min.js:12:1663)
	error (video.min.js:21:23702)
	handleTechError_ (video.min.js:21:10432)
	(anonimowa funkcja)
	bound 
	(anonimowa funkcja) (video.min.js:12:12488)`
```

My whole setup is this - I'm currently testing this for an online shop:
```
<div data-vjs-player style="width: 197px; height: 350px;">
	<video-js id="vid1"></video-js>
</div>

<script>
	const player = videojs('vid1', {
		controls: true,
		autoplay: false,
		preload: true,
		loop: true,
		fluid: true,
		liveui: true,
		sources: [{
			src: 'https://bravoplus-cdn.eu/video/Delikatne-paki-W-02-3.mp4',
			type: 'video/mp4'
		}],
	});
</script>
```

I did read that **byte range headers** must be set by the server, which hosts the file and from this screenshot, you can see they are:

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/801297/233554912-3f723b24-f800-4821-8418-b7e9fbb1781c.png">

Can someone assist me please?

**Comment by mister-ben** [comment]
Safari does not support the AV1 codec used by this file.

**Comment by strugman** [comment]
> Safari does not support the AV1 codec used by this file.

That was that! Thank you very much. I don't know much about video and it did not occur to me.
Now I've learnt more about codecs from the following pages (for reference if anyone else has similar problem):
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs
https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari
