### ISSUE TITLE
v.7.20.2 Firefox 112 fetching .m3u8 key as base64 encoded value

### ISSUE THREAD

**Issue by igorNS** [videojs/video.js#8254]
### Description

When fetching the key for a hls playlist, the key requested by Firefox get's returned as a base64 encoded value instead as the value which is available on the server. What could be the reason for that?

### Reduced test case

https://brookerfieldrenewable.cdn.spotlightr.com/watch/MTQxMTI5OQ==

### Steps to reproduce

1. Load in Firefox and Chrome
2. Opent dev tools, network, look for the .key file
3. In Chrome it has the regular value, in Firefox it has that value, just base64 encoded.

### What version of Video.js are you using?

7.20.2

### What browser(s) including version(s) does this occur with?

Firefox 112

### What OS(es) and version(s) does this occur with?

Windows, Mac

**Comment by mister-ben** [comment]
It's just a difference in how the browsers choose to **display** data of a `application/octet-stream` content type within the dev tools. The data actually received isn't any different.

**Comment by igorNS** [comment]
> 

Learned something new. Thanks.
