### ISSUE TITLE
Hls streaming not working on Chromium 53/68

### ISSUE THREAD

**Issue by jonybekov** [videojs/video.js#8266]
### Description

I'm building an application for LG Smart TVs (WebOS 4+) which uses chromium >=53.
I have a video player based on video.js latest version (8.3.0). In development, I'm testing my app on chromium 68. Unfortunately, the player is not playing HLS content displaying "No compatible source was found for this media".
However, when I open the player on latest Chrome (112.x) the HLS content is playing successfully.

In [http-streaming docs](https://github.com/videojs/http-streaming#installation), it's mentioned that hls will work if browser supports Media Source Extension API. It's supported since Chrome 23.
I can't find where's the problem. Apperciate your help.     

You can check the source code of test video player here: https://stackblitz.com/edit/vitejs-vite-hkqafz?file=src/VideoPlayer.svelte

You can try this deployed version on older browsers (Chromium >= 53) https://splendid-boba-51eaac.netlify.app/ 

### Reduced test case

https://splendid-boba-51eaac.netlify.app/

### Steps to reproduce

1. Open [this link](https://splendid-boba-51eaac.netlify.app/) in Chromium 68 or 53. 
You can download them here:
  - [Chrome 68 x64](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/399650/)
- [Chrome 53 x64](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/561388/)
2. Observe video player
3. HLS video doesn't play

### Errors

No compatible source was found for this media.

![image](https://user-images.githubusercontent.com/39439363/236703798-5927f4eb-3242-4c7c-8e7e-b84be21e21ba.png)

### What version of Video.js are you using?

v8.3.0

### What browser(s) including version(s) does this occur with?

Version 68.0.3439.0 (Developer Build) (64-bit)

### What OS(es) and version(s) does this occur with?

Windows 11

**Comment by jonybekov** [comment]
Even [the DEMO page of http-streaming](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false) is not working on Chrome 68

![image](https://user-images.githubusercontent.com/39439363/236704672-f167deae-81ee-4630-83a4-656546c71c44.png)

**Comment by gkatsev** [comment]
Video.js 8 changed a bunch of things in the playback engine and dropped support for a bunch of older browsers, namely IE. It's possible that some of the changes make it no longer work in Chrome 68 and older.
I'd probably advise trying out the latest version of Video.js 7.

I tried loading https://videojs-http-streaming.netlify.app/ in Chrome 68 and 53 via browserstack and I was able to get playback in Chrome 68 but not Chrome 53.

Also, your test example https://splendid-boba-51eaac.netlify.app/, seems to be using Video.js 7.10.0 and I did get playback in Chrome 68 and 53 with it.

**Comment by misteroneill** [comment]
We'll need to look into this as we should be supporting Chromium 53+ for Smart TVs

**Comment by jonybekov** [comment]
> https://splendid-boba-51eaac.netlify.app/,

Hi, thanks for your answer. Version 7.10.0 seems working on Chrome 53 via Browserstack but not on Chromium 53. Currently, I don't have access to my WebOS 4.x LG TV. Eventually, I should check it on real device. 
For now, I guess I will stick to version 7.10.

However, it's really strange that the result on Chrome and Chromium are different. I thought they use the same rendering engine and support the same Javascript APIs.

**Comment by jonybekov** [comment]
> We'll need to look into this as we should be supporting Chromium 53+ for Smart TVs

I would really appreciate your help.

**Comment by jonybekov** [comment]
@gkatsev @misteroneill 
It looks there's something wrong HLS and Chromium browser.
I just installed Chromium 114 (latest?) via [official website](https://www.chromium.org/getting-involved/download-chromium/) and tried to open [hls demo website](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false) and [my test example](https://splendid-boba-51eaac.netlify.app/) (which uses video.js v7.10.0) and none of these websites play the video

![image](https://user-images.githubusercontent.com/39439363/236886604-2a8de128-262a-42ee-ba87-41c7370c2ccf.png)
![image](https://user-images.githubusercontent.com/39439363/236886629-f8cb80f0-f533-4dc7-a894-1408585ae79b.png)
![image](https://user-images.githubusercontent.com/39439363/236886668-e9ecf546-dae6-4e63-afea-076f4f4e241c.png)

**Comment by gkatsev** [comment]
I believe latest Chrome is 113. It's worth noting that Chromium doesn't ship with the codecs required to play back h264 streams, which the default video on the example uses.

https://videojs-http-streaming.netlify.app/ plays for me without any issues on Chrome 113.

**Comment by dani3l3** [comment]
Is this related ?  https://github.com/videojs/video.js/issues/8159  I am also still using an old videojs version in the webOS LG and samsung Tizen apps as I got into those troubles when trying to upgrade.

**Comment by dani3l3** [comment]
Also in my case 7.6 works... probably up to 7.1xsomething... 7.21.x and the whole 8 version blow up with the blob not defined stuff.
