### ISSUE TITLE
play one mp4 file with multi tracks (video tracks)

### ISSUE THREAD

**Issue by annpeter** [videojs/video.js#8275]
### Description

i have one mp4 file with multi tracks (video tracks), how can i play with video.js. get all tracks list, and can change the current play track.

### Reduced test case

none

### Steps to reproduce

none

### What version of Video.js are you using?

8.3.0

### What browser(s) including version(s) does this occur with?

chrome 100

### What OS(es) and version(s) does this occur with?

macos 13

**Comment by amtins** [comment]
@annpeter would this help https://videojs.com/guides/video-tracks/ ?

**Comment by gkatsev** [comment]
Unfortunately, you can't really add the video tracks externally. Also, browsers themselves don't really support multiple video tracks currently. Right now, Video.js will pass mp4s directly to the browsers to play..
