### ISSUE TITLE
Preload parameter wrong type

### ISSUE THREAD

**Issue by alfonsograziano** [videojs/video.js#8282]
### Description

Ehy everyone, I'm using the `preload` option from the `VideoPlayerOptions`. 
In the Typescript type imported from `video.js/dist/types/player` it looks like the preload function accepts a boolean. 

Also in the [code doc](https://github.com/videojs/video.js/blob/f1558c660bbc132b23dbd63b2f3cdf7b6e60d00b/src/js/player.js#LL3691C1-L3692C1) there is a boolean value param. This looks wrong to me, since in the [documentation](https://videojs.com/guides/options/#preload) this option is a string.

Can this be an issue or is intended to be true/false? If so, maybe it is worth to update the documentation

### Reduced test case

https://github.com/videojs/video.js/blob/f1558c660bbc132b23dbd63b2f3cdf7b6e60d00b/src/js/player.js#L3684

### Steps to reproduce

1. import type VideoJsPlayerOptions from 'video.js/dist/types/player'; 
2. Check the `preload` option required type
3. Should be a function which takes a string, but is a function which takes a boolean

### What version of Video.js are you using?

8.0.3

### What browser(s) including version(s) does this occur with?

Typescript issue

### What OS(es) and version(s) does this occur with?

Typescript issue

**Comment by mister-ben** [comment]
Thansk. Addressed in #8277
