### ISSUE TITLE
videojs CDN url should be create to download the latest URL

### ISSUE THREAD

**Issue by artbindu** [videojs/video.js#8306]
### Description

videojs shoule expose a CDN url to give the latest player.

Now we know if we want to get a specific videojs release build we have to use CDN url like:
**videojs player 8.0.0:** `https://vjs.zencdn.net/8.0.0/video-js.css`
**videojs player 8.4.0:** `https://vjs.zencdn.net/8.4.0/video-js.css`

We need to expose a CDN url which is mapping with latest player like 
`https://vjs.zencdn.net/8/video-js.css` (latest player of version 8) 
or
`https://vjs.zencdn.net/latest/video-js.css` (map with latest of latest version of player)

### Reduced test case

https://vjs.zencdn.net/8.4.0/video-js.css

### Steps to reproduce

Not Applicable

### What version of Video.js are you using?

8.4.0

### What browser(s) including version(s) does this occur with?

Chrome, Edge, Firefox

### What OS(es) and version(s) does this occur with?

Windows, Mac

**Comment by gkatsev** [comment]
We have historically specifically avoided creating those urls because we felt like the likelihood of soft breakages were too big.

As an alternative, you can try jsdelivr or unpkg urls: https://cdn.jsdelivr.net/npm/video.js@8/dist/video.min.js

**Comment by artbindu** [comment]
Yes, I understand. @gkatsev

**Comment by artbindu** [comment]
But this url, 
`https://cdn.jsdelivr.net/npm/video.js@8/dist/video.min.js` mapping with **Video.js 8.3.0 version**
 
 It should be **Video.js 8.4.0 version**

**Comment by mister-ben** [comment]
jsdelivr and simlar services cache the files, so there will always be some delay for them update. That URL is serving me 8.4.0 now.

**Comment by artbindu** [comment]
Yes, it can be @mister-ben 
Now I am gating 8.4.1  😊

OK, I am resolving this issue.
Thank to all.
