### ISSUE TITLE
Analog of the beforeRequest function in Video.js

### ISSUE THREAD

**Issue by Raino** [videojs/video.js#8317]
### Description

Hello!
I'm sorry that I'm not writing according to the established format, it's just a more abstract question.
Faced with the problem that the latest version of `Video.js` conflicts with old libraries, for example, such as `videojs-contrib-hls.js` . 
In the description of `videojs-contrib-hls.js` says that it is integrated into `Video.js` **by default**. 
There was a `Hls.xhr.beforeRequest` function in this library, which does not work in the latest version during testing `Video.js`. 
Are there any existing **alternatives** to this feature in the **latest versions** of `Video.js` or are there **new ways** to change the URL of the player in _real time_?
I would like to sort this out so as not to resort to using older versions `Video.js`.

### Reduced test case

https://videojs.github.io/videojs-contrib-hls/

### Steps to reproduce

1. Go to the page
2. Try to launch HLS video
3.

### What version of Video.js are you using?

8.3.0

### What browser(s) including version(s) does this occur with?

Chrome

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by Raino** [comment]
@gkatsev, perhaps you know how things are with this now?

**Comment by mister-ben** [comment]
It's [videojs/http-streaming (VHS)](https://github.com/videojs/http-streaming) that is included in video.js 7+, as stated on that test page. contrib-hls is no longer used or developed. 

http-streaming 3.3.0 / video.js 8.4.0 introduced request hooks which are more flexible/capable:

https://github.com/videojs/http-streaming/blob/main/README.md#vhsxhr

If using an older version, you can use `beforeRequest` still
https://github.com/videojs/http-streaming/blob/v3.2.0/README.md#vhsxhr
