### ISSUE TITLE
 How to disable prefetch m3u8 after the player loaded?

### ISSUE THREAD

**Issue by JonasWater** [videojs/video.js#8348]
### Description

I found the m3u8 will prefetch/preload after the player loaded.

How to disable it?

### Reduced test case

https://videojs.com/city

### Steps to reproduce

1.  Refresh the test website: https://videojs.com/city
2. You can see the m3u8 has prefetched.

How to disable the prefetch?  Thx for your reply.

<img width="1067" alt="image" src="https://github.com/videojs/video.js/assets/118031233/98ce7cab-a413-40b1-abff-0532bad7f770">

### What version of Video.js are you using?

7.21.4

### What browser(s) including version(s) does this occur with?

Chrome 114

### What OS(es) and version(s) does this occur with?

MacOS 12.4

**Comment by mister-ben** [comment]
Preload attribute or option set to `'none'`.

```
<video-js preload="none" ...
```

```
video-js('my_video', { preload: 'none' });
```

**Comment by JonasWater** [comment]
```
<video-js preload="none" ...

video-js('my_video', { preload: 'none' });
```

I have tried, but its't works. (video.js Version: 7.21.4)
What i have missed? Or what something to config?

@mister-ben Thx your reply.

**Comment by JonasWater** [comment]
Okay, thx
