### ISSUE TITLE
M3u8 stream with multiple audio tracks doesn't play on iOS

### ISSUE THREAD

**Issue by jkirkcaldy** [videojs/video.js#8349]
I have a web app that I’ve created that uses videojs to play m3u8 files created with ffmpeg.

Any file that has a single audio track or no audio works fine, but I have some files that have 9 audio tracks embedded in the m3u8 file. 

This works fine on desktop but gives an error saying no compatable source could be found when viewing on iOS.

I have tried the overridenative argument but that doesn’t work.

My current code: 

```

var overrideNative = false;
var player = document.querySelector("#my-video");

  player = videojs('my-video', {
    playbackRates: [-2, -1, -0.5, 0.5, 1, 2],
    fluid: true,
    aspectRatio: "16:9",
    liveui: true,
    controls: true,
    preload: "auto",
    poster: "",
    html5: {
      vhs: {
        overrideNative: overrideNative
      },
      nativeVideoTracks: !overrideNative,
      nativeAudioTracks: !overrideNative,
      nativeTextTracks: !overrideNative
    }
    });

```

**Comment by mister-ben** [comment]
`overrideNative` does nothing on iOS as only native playback is possible. Unlike MacOS and iPad OS Safari, it still doesn't support Media Source Extensions. As it's native playback, it's difficult to troubleshoot. Apple's mediastreamvalidator tool might highlight some issue.

https://developer.apple.com/documentation/http-live-streaming/using-apple-s-http-live-streaming-hls-tools

**Comment by jkirkcaldy** [comment]
I figured this out, it seemed that the transcode was the issue, not sure exactly which setting changed it but it was either setting the profile to 'main' or the pixformat to yuv420p in my ffmpeg script.
