### ISSUE TITLE
Video.js Not Playing HLS Videos in Chrome with First Source as HLS

### ISSUE THREAD

**Issue by Benzeman97** [videojs/video.js#8388]
### Description

I've encountered an issue with Video.js where HLS videos are not playing in Google Chrome when the HLS source is set as the first source in the video element. The video remains in a buffering state without playing

when I configure HLS first place the video is not playing, just buffering 

If I give mp4 or webm in the first place then it will work

### Reduced test case

https://codepen.io/benzeman97/pen/KKrEmKg

### Steps to reproduce

1. Set up a Video.js video element with HLS, MP4, and WebM sources.
2. Place the HLS source as the first source in the list.
3. Load the page in Google Chrome.

### Errors

In Google Chrome, the video does not play and the player remains in a paused state when the HLS source is set as the first source. The issue does not occur when the HLS source is placed after other formats like MP4 and WebM.

### What version of Video.js are you using?

8.3.0

### What browser(s) including version(s) does this occur with?

Version 115.0.5790.111

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by mister-ben** [comment]
Mixing hls.js and video.js that way they'll conflict with each other. Either use video.js's inbuilt HLS support and remove hls.js, or if there's a reason you have to use hls.js, you might want to try https://github.com/streamroot/videojs-hlsjs-plugin
