### ISSUE TITLE
Does videojs play Live H265 with videojs version 7.9.5 or later??? Help me

### ISSUE THREAD

**Issue by LeMuiHV** [videojs/video.js#8394]
### Description

I need play video codec H265 on videojs

### Reduced test case

https://github.com/videojs/video.js/issues/new?assignees=&labels=needs%3A+triage&projects=&template=bug_report.yaml

### Steps to reproduce

1.
2.
3.

### Errors

not support h265

### What version of Video.js are you using?

7.9.5

### Video.js plugins used.

videojs 7.7.6

### What browser(s) including version(s) does this occur with?

Chrome

### What OS(es) and version(s) does this occur with?

Window 10

**Comment by friendtasy** [comment]
you need Chrome 107 or update,and video card can decode h265

**Comment by mister-ben** [comment]
Or Safari. The browser needs to support the codec. See also https://caniuse.com/hevc
