### ISSUE TITLE
Mobile fullscreen orientation

### ISSUE THREAD

**Issue by reaganch** [videojs/video.js#8396]
### Description

When enabling fullscreen mode on mobile, the video does not automatically switch to landscape mode when the muted option is enabled. When the muted option is removed, the video automatically switches to landscape mode on fullscreen as expected.

### Reduced test case

```
<html>

<head>
    <link href='https://unpkg.com/video.js@8.5.0/dist/video-js.css' rel='stylesheet'>
    <title>Video.js Starter Template</title>
</head>

<body>
    <script src='https://unpkg.com/video.js@8.5.0/dist/video.js'></script>
    <script>
        const video = document.createElement('video-js')
        video.id = 'video'
        video.src = 'https://vjs.zencdn.net/v/oceans.mp4'
        document.body.appendChild(video)
        const player = videojs('video', {
            controls: true,
            muted: true
        })
    </script>
</body>

</html>
```

### Steps to reproduce

1. Create video player with muted option enabled
2. View player on Firefox for Android, with phone held in portrait orientation
3. Enable fullscreen mode
4. Video does not automatically switch to landscape orientation
5. Remove the muted option
6. Reload the page on Firefox
7. Enable fullscreen mode again
8. Video automatically switches to landscape orientation

### What version of Video.js are you using?

8.5.0

### Video.js plugins used.

None

### What browser(s) including version(s) does this occur with?

Firefox 116.2.0

### What OS(es) and version(s) does this occur with?

Android: MIUI 14

**Comment by mister-ben** [comment]
Video.js isn't controlling or attempting the rotation here, it's Firefox itself. I note when muted calling `window.screen.orientation.lock('landscape')` also doesn't work, the promise will reject with 'operation not permitted'. I don't know if this is a bug or by design, but it's a Firefox issue rather than anything Video.js can resolve.
