### ISSUE TITLE
Full Screen mode does not change to native controls and video is blacked out with only audio playing

### ISSUE THREAD

**Issue by streamzyuk** [videojs/video.js#8402]
### Description

When on IOS 15.5 Ipad 9th gen, and when you switch to full screen video is blacked out and only audio plays without any error.
In fullscreen Native controls are not displayed. Video js controls are messed. 

It plays without any issue on inline playback.

It looks like an issue with the themes or fullscreen api

### Reduced test case

www.videojs.com

### Steps to reproduce

Go to videojs.com. Sample player behaves same

### Errors

No errors

### What version of Video.js are you using?

8.3.0 , 8.5.2

### Video.js plugins used.

contrib eme

### What browser(s) including version(s) does this occur with?

safari ipad 15.5

### What OS(es) and version(s) does this occur with?

IOS 15.5

**Comment by mister-ben** [comment]
It's expected that it's not native controls on iPad, as it supports the proper fullscreen API. There's an issue with some versions of iOS with `inline-block` in fullscreen, there's a fix already out in 8.5.1 that uses `block` instead.
