### ISSUE TITLE
play video blank

### ISSUE THREAD

**Issue by LingRen** [videojs/video.js#8405]
### Description

<img width="508" alt="image" src="https://github.com/videojs/video.js/assets/15982348/6d8a5ea3-16ca-4cc3-af30-341ea801b3cc">
<img width="541" alt="iShot_2023-08-17_16 55 09" src="https://github.com/videojs/video.js/assets/15982348/6e4f5df2-6a5b-48af-9900-2dc30b89c6e9">

### Reduced test case

no test case

### Steps to reproduce

play m3u8 video

### What version of Video.js are you using?

v8.3.0

### Video.js plugins used.

no

### What browser(s) including version(s) does this occur with?

ios16.4

### What OS(es) and version(s) does this occur with?

ios

**Comment by mister-ben** [comment]
I don't see anything obviously wrong from the screenshot of the video codec, but it's hard to say more without an example stream. 
In any case, since it's iOS's native playback, this is most likely an issue with the video encoding that can't be fixed client-side.

**Comment by mister-ben** [comment]
I played this on a couple of devices and it plays back fine. Noticing the background in your screenshot, are you playing this in XCode's iOS Simulator? Current versions have a bug with video playback https://developer.apple.com/forums/thread/727288

**Comment by LingRen** [comment]
yeah，thanks。
