### ISSUE TITLE
Not able to use title-bar as a link

### ISSUE THREAD

**Issue by rochapablo** [videojs/video.js#8406]
### Description

<img width="1256" alt="image" src="https://github.com/videojs/video.js/assets/5365304/1a0c45ce-ddb3-4278-b06e-5cb277a0104c">

After upgrade to version 8.5.2 every click goes to pause/play the video and I'm not able to use the link from title-bar.

### Reduced test case

no

### Steps to reproduce

```
const Component = videojs.getComponent('Component');

class TitleBar extends Component {
    constructor(player, options = {}) {
        super(player, options);

        if (options.text) {
            this.updateTextContent(options.text);
        }

        if (options.href) {
            this.updateHRefContent(options.href);
        }
    }

    createEl() {
        return videojs.dom.createEl('a', {
            className: 'vjs-title-bar',
            target: '_blank'
        });
    }

    updateTextContent(text) {
        this.el().innerHTML = text;
    }

    updateHRefContent(href) {
        this.el().href = href;
    }
}

videojs.registerComponent('TitleBar', TitleBar);
```

```
this.player.addChild('TitleBar', {
    text: 'Lorem Ipsum is simply dummy text',
    href: 'https://github.com/videojs/video.js
});
```

### What version of Video.js are you using?

8.5.2

### What browser(s) including version(s) does this occur with?

Firefox

### What OS(es) and version(s) does this occur with?

iOS

**Comment by mister-ben** [comment]
[_title-bar.scss](https://github.com/videojs/video.js/blob/main/src/css/components/_title-bar.scss) has had `pointer-events: none;` since it has existed in Video.js, that hasn't changed in 8.5.2. You could override that rule.

**Comment by rochapablo** [comment]
```
.video-js .vjs-title-bar {
    /** Allow click to link */
    pointer-events: all;
}
```

Thanks!
