### ISSUE TITLE
Unexpected seek event 

### ISSUE THREAD

**Issue by unreal998** [videojs/video.js#8419]
### Description

Hello guys,  we have a problem with seeking after 'loadedmetadata' event. The main problem is the disappearance of video posters in content that has metadata. The disappearing happens after seek event described before. I'll attach a video recording.

### Reduced test case

https://abc.com/movies-and-specials/the-new-face-of-hollywood

### Steps to reproduce

1. Run any video with metadata
2. Wait for metadata to be loaded
3. See the seek to zero even if the current playback position is 0

### What version of Video.js are you using?

7.18.1

### Video.js plugins used.

"videojs-contrib-ads": "^6.9.0",
"videojs-contrib-eme": "^3.10.1",
"videojs-hotkeys": "^0.2.25",
"videojs-ima": "^2.1.0"

### What browser(s) including version(s) does this occur with?

Chrome 115

### What OS(es) and version(s) does this occur with?

macOS Ventura 13.5

https://github.com/videojs/video.js/assets/31666287/4e45032f-4d84-40e0-a9f9-fbf8878d9d32

**Comment by mister-ben** [comment]
The seek is triggered [here within dash.js](https://github.com/Dash-Industry-Forum/dash.js/blob/8f75266ac0ab057fa39dfcddf0eb21c455a448c3/src/streaming/controllers/StreamController.js#L526C42-L526C42). I don't know its internals well enough to say why. 

Your page is missing the styles for Video.js's poster element. With these styles applied, the poster image would be displayed while the player is in this state.

https://github.com/videojs/video.js/blob/main/src/css/components/_poster.scss

**Comment by unreal998** [comment]
thank you !
