### ISSUE TITLE
captions issues on system player of ios (iphone)

### ISSUE THREAD

**Issue by nabilintigo** [videojs/video.js#8427]
### Description

Using videojs and vuejs3

the captions are shown in fullscreen mode or default mode (in desktop, mac, android) but in ios fullscreen they are not shown 

I see only a black box without text of captions

### Reduced test case

1. https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

### Steps to reproduce

using this m3u8 test link
1. https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8
that has it's own captions loaded 
2. Open the videojs app in IOS iphone safari
3. Go to full screen mode
4. no captions are shown even when you navigate between subtitles options

### What version of Video.js are you using?

7.4.3

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

IOS

**Comment by bhaveshdaswani93** [comment]
Hi May I know how you solve I am facing the same issue, the caption are not being shown on full screen in safari iOS
