### ISSUE TITLE
why liveui button not visible 

### ISSUE THREAD

**Issue by xalteropsx** [videojs/video.js#8428]
### Description

liveui is completely not working 

### Reduced test case

https://codepen.io/facundofernandez/pen/NMeQRQ

### Steps to reproduce

let player = videojs("my-video",{liveui:true}); i tried this https://codepen.io/facundofernandez/pen/NMeQRQ

### Errors

liveui button is not displaying  

### What version of Video.js are you using?

8.3.0 tested in other version as well

### What browser(s) including version(s) does this occur with?

test in all browser firefox chrome brave non of them showing

### What OS(es) and version(s) does this occur with?

window 11

**Comment by mister-ben** [comment]
Your example does not have `liveui` set, and is not playing a live video. The live UI (progress bar) will only appear if `liveui` is `true` and the source is a live stream that has a seeable DVR buffer.
