### ISSUE TITLE
Feature Request: Interactive Video: Quizzes

### ISSUE THREAD

**Issue by connecteev** [videojs/video.js#8431]
Allow interactive video quiz questions in the middle of a video (at specified timestamps), with the options to:

1. View Quiz Feedback in 2 modes:
   - Mode 1 (Immediate Feedback): Allow User to see whether their answer was correct or incorrect immediately after answering a quiz question
   - Mode 2 (Delayed Feedback): Allow User to see whether their answers were correct or incorrect only after answering all quiz questions
2. Whether or not to Allow User to view their quiz overall score, correct and incorrect answers, and choose whether to retake quiz before proceeding
3. Whether or not to Block user from proceeding until they get ALL the quiz answers correct

All of these options / functionality can be enabled or disabled by the website owner using code / parameters.

For reference, see: https://vimeo.com/blog/post/video-quiz/#what-is-a-video-quiz
And demos like https://liqvidjs.org/

**Comment by karmatys8** [comment]
If this feature is wanted by the owners I would like to try implementing it.

**Comment by mister-ben** [comment]
This type of thing makes sense to implement as a [plugin](https://videojs.com/guides/plugins/) rather than in the Video.js core repo. Showing an overlay on top of the video is easy enough, such as with the [ModalDialog](https://videojs.com/guides/modal-dialog/) component, the bigger question is the back-end you'd use for reporting etc

**Comment by karmatys8** [comment]
Unfortunately I haven't done anything with back-end yet so I will have to pass on it.

**Comment by mister-ben** [comment]
Closing this. As already mentioned, this is something to be implemented as a plugin rather than in the core player, and needs to consider more than the front-end components.
