### ISSUE TITLE
InvalidStateError: getBody(@videojs/xhr/index)

### ISSUE THREAD

**Issue by yantongtong-1** [videojs/video.js#8438]
function getBody() {
        // Chrome with requestType=blob throws errors arround when even testing access to responseText
        var body = undefined

        if (xhr.response) {
            body = xhr.response
        } else {
            body = xhr.responseText || getXml(xhr)
        }

        if (isJson) {
            try {
                body = JSON.parse(body)
            } catch (e) {}
        }

        return body
    }
Report an error in the above code：
InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').

**Comment by mister-ben** [comment]
Please add more information and a reproducible test case
