### ISSUE TITLE
Some m3u8 cannot be played ？

### ISSUE THREAD

**Issue by dysibai** [videojs/video.js#8440]
### Description

https://c3.monidai.com/20230917/iWuST6iA/index.m3u8 
上面的地址，无法正常播放？

### Reduced test case

https://c3.monidai.com/20230917/iWuST6iA/index.m3u8 

### Steps to reproduce

Repeated playback address：https://c3.monidai.com/20230917/iWuST6iA/index.m3u8 

### What version of Video.js are you using?

8.5.3

### What browser(s) including version(s) does this occur with?

最新chrome浏览器和移动设备

### What OS(es) and version(s) does this occur with?

mac 13.0

**Comment by dysibai** [comment]
n @ video.min.js:12
proxy-tf-all-ws.bilivideo.com/url=http://i2.hdslb.com.aoxtv.com/20230916/iHt73LOM/1000kb/hls/MwOu2104000.ts:1     Failed to load resource: the server responded with a status of 403 ()
video.min.js:12 VIDEOJS: WARN: Problem encountered with playlist 0-https://c3.monidai.com/ppvod/56A907AF3C0F4DC42D2A6ACA5A7D8538.m3u8. Trying again since it is the only playlist.

**Comment by gkatsev** [comment]
Seems like your stream is misconfigured. Segments are returning an HTTP 403 error when Video.js tries to download it.

**Comment by dysibai** [comment]
vlc and ckplayer players can play

> Seems like your stream is misconfigured. Segments are returning an HTTP 403 error when Video.js tries to download it.

vlc and ckplayer players can play!

**Comment by gkatsev** [comment]
Desktop players have different considerations. Something on the backend is configuring it so Video.js can't play. Other web players can't play either.
The only thing that can be configured that might help is `withCredentials` https://github.com/videojs/http-streaming#withcredentials, but from a quick trial, I didn't see it help anything.

**Comment by dysibai** [comment]
ckplayer is a mobile player

**Comment by dysibai** [comment]
https://github.com/videojs/http-streaming#withcredentials ，Can't play！

**Comment by mister-ben** [comment]
Apparently the server is checking the referrer header but allowing the absence of a referrer header. If you look at the request that returns 403 in dev tools, copy as curl, and paste into a terminal it will fail. If you remove the referrer header, it gets a successful response.

Apps, desktop or mobile won't send a referrer header, a browser always will. This can't be worked around client side, it's a server configuration issue.

**Comment by gkatsev** [comment]
Nice sleuthing @mister-ben!
