### ISSUE TITLE
Fullscreen Video opened on button click is not fullscreen and tablet devices

### ISSUE THREAD

**Issue by mol-knysh** [videojs/video.js#8449]
### Description

The video component is get from outer library and then wrapped in the video js.
On click on the button I have to open video Fullscreen, play it with sound.
But the video is not shown as Fullscreen.
This issue is observed on Android mobiles and tablets(Chrome) and iOS tablets(Safari).
Have tried to apply to native browsers Fullscreen methods - did not work out.

### Reduced test case

https://codepen.io/Olha-Knysh/pen/wvRjxWx

### Steps to reproduce

1. Open it on any browser on mobile/tablet, or Safari on tablet 
2. Click the button
3. The video is not fullscreen

### What version of Video.js are you using?

8.5.2

### What browser(s) including version(s) does this occur with?

Chrome,, Edge, Safari - only on mobiles

### What OS(es) and version(s) does this occur with?

Android 12,  Android 13, iOS 16

**Comment by mister-ben** [comment]
Your example works for me (goes fullscreen) on Android Chrome and iPhone and iPad Safari. However browsers do require fullscreen to be initiated by a user action, so going fullscreen on the `play` event could be too removed from the click in some cases, such as a slow connection delaying the play. It might be more robust as something like

```js
  $fullscreenButton.on('click', function() {
    player.play();
    player.requestFullscreen();
  });
```

i.e. going fullscreen directing in the click handler. Note Video.js's `Player.fullscreen()` is subject to the same restrictions re user gesture, it's just calling the browser API, but it already handles making sure the right fullscreen API method is used.
