### ISSUE TITLE
Video does not play from beginning (time 0:00); it begins playing from 9 seconds in

### ISSUE THREAD

**Issue by ghost** [videojs/video.js#8454]
### Description

I embed VideoJS on my website like this:
```html
    <video
      class="video-js embed-container"
      controls
      preload="none"
      width="1280"
      height="720"
      poster="//media.example.xyz/dir/cover.png"
      data-setup="{}"
    >
      <source src="//media.example.xyz/dir/desktop.mp4" type="video/mp4" media="min-width:1000px" />
      <source src="//media.example.xyz/dir/mobile.mp4" type="video/mp4" />
      <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a
        web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
      </p>
    </video>
```
Why does the video start from 9 seconds in when I playback? Same problem on both mobile and desktop.
Server supports 206 Partial Content.

### Reduced test case

https://codepen.io/Tobias-Andersen/pen/QWzZvzK?editors=1000

### Steps to reproduce

The same problem appears in the above Codepen.

### What version of Video.js are you using?

8.5.2

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

macOS, iOS

**Comment by amtins** [comment]
@andersentobias1 I had quickly looked at this issue when you posted it. I noticed it was an encoding problem. If I remember correctly, `ffprobe` returns the following message: `Missing key frame while searching for timestamp: 0`. In the meantime, the video had been re-encoded and the problem was no longer visible. Can we close this ticket?

**Comment by shunyaekam** [comment]
Yes, please close it. Thanks.
