### ISSUE TITLE
Some gamble webside linkes is found in your lincense webside

### ISSUE THREAD

**Issue by keijack** [videojs/video.js#8457]
Dear videojs owner, 

Thanks for creating this marvellous component and it works fine. 

But the malware scanning department of my company find that there is a gamble website link (https://svgjs.com/svgjs) in your license website (https://www.brightcove.com) commented in released js file (https://vjs.zencdn.net/8.5.2/video.min.js). 

Please check line 183 and 184 in website https://www.brightcove.com.

We find out that svgjs have change their domain to https://svgjs.dev now, and the old one has been registered by some gamble company. I think that code is useless in your page. 

This issue is slight, but out malware scanning department doesn't think so. 

Could you please update that link? 

Max thanks.

**Comment by mister-ben** [comment]
Thank you for reporting. Those svgjs.com URLs (which were only present in attributes within SVG images) have been removed.
