### ISSUE TITLE
detach from the document flow

### ISSUE THREAD

**Issue by tbrwba** [videojs/video.js#8458]
Hello, in the process of developing with Vue 2 and H5, I found that the video element has a high z-index and is positioned outside the normal document flow. As a result, the video container is stuck to the top of the page. What could be causing this issue?

**Comment by amtins** [comment]
@tbrwba are you sure you don't have a custom css that changes the z-index of the video element?

After a quick look at the video.js css I don't see what could cause the behavior you describe. Please see https://github.com/search?q=repo%3Avideojs%2Fvideo.js%20z-index&type=code

The only case the z-index is modified is when the player is in Document Picture in Picture.
