### ISSUE TITLE
"Product not registered"

### ISSUE THREAD

**Issue by fulldev100** [videojs/video.js#8468]
### Description

![image](https://github.com/videojs/video.js/assets/132243422/69b54a48-9454-4e90-8b60-b3d7044c2d61)

Hi, everyone!
Do you know how to fix this issue?

### Reduced test case

https://github.com/videojs/video.js/assets/132243422/69b54a48-9454-4e90-8b60-b3d7044c2d61

### Steps to reproduce

I am using video.js and nuevo.js in ReactJS. it worked well in my previous server and doesn't work after moving the code on new server.
Please help me.
Thanks in advance

### What version of Video.js are you using?

1.22

### What browser(s) including version(s) does this occur with?

chrome 94

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by amtins** [comment]
Hi @fulldev100 I suggest you to contact Nuevo support since video.js doesn't require any registration.

**Comment by fulldev100** [comment]
Oh I see. Thanks for your feedback.
