### ISSUE TITLE
Passing source without type

### ISSUE THREAD

**Issue by tsi** [videojs/video.js#8475]
### Description

Hi team,

Not sure if this is a bug, a feature request or just some lack of knowledge from my side.

What I'm trying to do is pass a `src` to the player without specifying the `type` since type will be auto resolved at the CDN level, and is unknown at this stage (Cloudinary will auto resolve to the best type available for the browser).

The thing is this - it will work when set via the `src` attribute ([codesandbox](https://codesandbox.io/s/minimal-videojs-f-auto-with-src-attribute-ns3zhp?file=/index.html))
But it fails when I try to set the `src` via the player method, which is what I need ([codesandbox](https://codesandbox.io/s/minimal-videojs-f-auto-with-src-method-call-kzjfq5?file=/index.htm))

Is there anything I can do from my side to make this work without specifying a `type`?

Thanks!

### Reduced test case

https://codesandbox.io/s/minimal-videojs-f-auto-with-src-method-call-kzjfq5?file=/index.html

### Steps to reproduce

1. Set up a basic videojs player
2. Using the `player.src()` method pass a `src` without specifying a `type`
3.

### Errors

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

### What version of Video.js are you using?

8.6.0

### What browser(s) including version(s) does this occur with?

Latest Chrome, latest Safari

### What OS(es) and version(s) does this occur with?

OSx, Win

**Comment by amtins** [comment]
@tsi I think using a video.js [middleware](https://videojs.com/guides/middleware/) will help you get the result you want:

## solution 1
```javascript

videojs.use('cloudinary/src', (player) => {
  return {
    async setSource(srcObj, next) {
      const headers = await fetch(srcObj.src).then((r) => r.headers);

      return next(null, {
        src: srcObj.src,
        type: headers.get('content-type'),
      });
    },
  };
});

const player = videojs('player');

player.src({src:'https://res.cloudinary.com/your/source', type:'cloudinary/src'})
```

## Solution 2

I don't recommend this solution

```javascript
videojs.use('*', (player) => {
  return {
    async setSource(srcObj, next) {
      // only for cloudinary sources...
      if (srcObj.src.includes('cloudinary')) {
        const headers = await fetch(srcObj.src).then((r) => r.headers);

        return next(null, {
          src: srcObj.src,
          type: headers.get('content-type'),
        });
      }

      // other sources
      return next(null, srcObj);
    },
  };
});

const player = videojs('player');

player.src('https://res.cloudinary.com/your/source')
```

Tested with the source provided in the `codesandbox` link and it works fine.

**Comment by tsi** [comment]
Thanks @amtins !!
This is a great solution. 
But can't I just _not_ pass a `type` somehow?
I mean, it [works fine](https://codesandbox.io/s/minimal-videojs-f-auto-with-src-attribute-ns3zhp?file=/index.html) without a type when setting `src` via the html attribute. Is there no way I could pass it without the `type` and save myself the extra `fetch`?

**Comment by gkatsev** [comment]
You can try not passing a type, but Video.js may not know how to properly play your video otherwise. It'll try to detect based on the url (like if an `.m3u8` extension is present), but otherwise, it'll just pass the url to the video element, which may not be able to play the video itself.
We do strongly recommend passing a type.

**Comment by tsi** [comment]
Thanks, if it was just passing the url to the video element [I believe I would be fine](https://codesandbox.io/s/minimal-video-f-auto-src-95jqzk?file=/index.html).
But instead it seems like it will throw the `MEDIA_ERR_SRC_NOT_SUPPORTED` error.


> We do strongly recommend passing a type

Fair enough, I guess @amtins solution is perfect then

**Comment by mister-ben** [comment]
In case fetching the whole file first or CORS is ever a problem, and since Cloudinary apparently only returns a couple of formats, you could also just use both types. It might be you get webm even if the video el supports MP4 but that wouldn't matter.

```
player.src([
  { src: 'https://example.com/abcd', type: 'video/mp4' },
  { src: 'https://example.com/abcd', type: 'video/webm' }
]);
```
Perhaps there is a case for [optionally] trying to load any unknown type source with the Html5 tech.

**Comment by tsi** [comment]
@mister-ben thanks, yeah passing both was something I considered but thought it might lead to issues in cases where the browser and the back-end are not aligned, for example - browser picking webm but server deciding to serve mp4.

I ultimately went with @amtins solution, but I noticed that just `fetch`ing like that will cause the whole file to be downloaded even when it is already cached by the browser, changing it to be `method: 'HEAD'` fixed that.

```
  videojs.use('video/auto', () => {
    return {
      async setSource(srcObj, next) {
        const { headers } = await fetch(srcObj.src, { method: 'HEAD' });

        return next(null, {
          src: srcObj.src,
          type: headers.get('content-type')
        });
      }
    };
  });
```
