### ISSUE TITLE
多个播放地址时,如果首个地址是m3u8格式,地址失效时,不会自动播放下一个有效视频!

### ISSUE THREAD

**Issue by jywyf** [videojs/video.js#8477]
如题:
多个播放地址时,如果首个地址是m3u8格式,地址失效时,不会自动播放下一个有效视频!
所有地址都是MP4格式时,不存在此问题.
请问如何解决首个地址是m3u8格式失效时播放下一个有效视频?

**Comment by mister-ben** [comment]
This example works. There are two HLS sources, the first with an invalid URL.

https://codepen.io/mister-ben/pen/rNPLdLR
