### ISSUE TITLE
disable scale of the progress bar circle on hover?

### ISSUE THREAD

**Issue by ming2024** [videojs/video.js#8492]
### Description

how to disable scale of the progress bar circle on hover?

<img width="840" alt="image" src="https://github.com/videojs/video.js/assets/111698568/95a4d8af-b3a2-403e-9422-5829f2f22852">

seems like it's controlled by js. I tried this

vjs-play-progress:before {
    font-size: 1.6em;
    color: #fd01c6;
    transform: scale(1) !important;
}

it won't stop the circle from scailling on hover. there's no active class added for hovered. Is there any js option to disable the scale effect?

### Steps to reproduce

1. hover on the progress bar

### What version of Video.js are you using?

v7.20.3

### What browser(s) including version(s) does this occur with?

chrome

### What OS(es) and version(s) does this occur with?

macOS

**Comment by mister-ben** [comment]
It inherits from this rule for the progress holder element.

https://github.com/videojs/video.js/blob/d535e163da3f1df5d87f7f7a1a2e8ff628361afb/src/css/components/_progress.scss#L42-L46

**Comment by ming2024** [comment]
> It inherits from this rule for the progress holder element.
> 
> https://github.com/videojs/video.js/blob/d535e163da3f1df5d87f7f7a1a2e8ff628361afb/src/css/components/_progress.scss#L42-L46

won't work. this is the culprit

<img width="374" alt="image" src="https://github.com/videojs/video.js/assets/111698568/1dbaebd4-3f78-44de-955e-9b9265814e2c">

**Comment by ming2024** [comment]
> .video-js .vjs-progress-control:hover .vjs-progress-holder {

ok found the solution
```
.vjs-play-progress:before {
    font-size: 1.6em;
  }
  .video-js .vjs-progress-control:hover .vjs-progress-holder {
    font-size: 1em;
  }
  ```
  
Thanks @mister-ben !!
