### ISSUE TITLE
Scrubber acting weird in new Chrome versions

### ISSUE THREAD

**Issue by webmasterh** [videojs/video.js#8509]
### Description

As you can see in video, the scrubber of videojs acting so weird in chrom.
 

https://github.com/videojs/video.js/assets/142931228/8c6ae1d6-64e6-47c6-9859-9319789718c4

For let you know, I use videojs(7.20.1) in my vuejs (2.6.12) app.
But in other browser like Firefox it works fine.

https://github.com/videojs/video.js/assets/142931228/bc40fef7-565d-47e3-97e9-f4e3c7300cd7

Is there anyone that suggesting useful guide?

### Reduced test case

all

### Steps to reproduce

n/a

### What version of Video.js are you using?

7.20.1

### What browser(s) including version(s) does this occur with?

Chrome 119.0.6045.199 (Official Build) (64-bit)

### What OS(es) and version(s) does this occur with?

Ubuntu 22.04.3 LTS

**Comment by webmasterh** [comment]
@mister-ben Thanks for your response.
So, your opinion is that I should change the headers of my request?

**Comment by mister-ben** [comment]
No, if that is the issue it's the server that has to change, and return what was requested by the request headers.
