### ISSUE TITLE
currentTime() not work correctly

### ISSUE THREAD

**Issue by makarna35** [videojs/video.js#8515]
### Description

`  var myPlayer = videojs('my_video');
    myPlayer.ready(function() {
        myPlayer.on('timeupdate', function () {
            var whereYouAt = myPlayer.currentTime();
            if (!myPlayer.paused()) {
                console.log(whereYouAt);
            } 
            console.log(myPlayer.paused());
        });
      });`
        
currentTime() function not work correct. example: Sometimes it produces these values for 2. seconds:
2.248962
2.529225
2.806487

Some times:
2.265328
2.54331
2.823605
etc...

this is not consistent at all. if you have for 2.248962. second triger this triger some times work sometimes not work because one more times function newer return 2.248962 value. This problem all seconds etc... Real time second newer return.
        

### Reduced test case

not have

### Steps to reproduce

1. use currentTime()
2. Plaey video
3. check currentTime

### What version of Video.js are you using?

8.6.1

### Video.js plugins used.

not

### What browser(s) including version(s) does this occur with?

Firefox 120.0.01 (64 bit)

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by mister-ben** [comment]
This is correct and normal behaviour. The `timeupdate` event is not be fired at a regular and predictable interval, see e.g. [the mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/timeupdate_event). `currentTime()` returns seconds as a float as returned by the HTML element.
You might want to round the time to the nearest integer, or act at the first value greater than or equal to your target. Or use `requestVideoFrame()` or `requestAnimationFrame()` which are more frequent, or use cues in a metadata track and listen to `cuechange` events.
