### ISSUE TITLE
No MenuItem elements in DOM

### ISSUE THREAD

**Issue by rudachenkoev** [videojs/video.js#8517]
### Description

Hey, everybody.
Please help me with the problem that menu items don't appear in the DOM after adding.
I am using Vue.js 2 and plugin version ^8.6.1.
What am I doing wrong?

```
setupPlayer () {
      if (!this.$refs.videoPlayer) return false
      this.player = videojs(this.$refs.videoPlayer, this.options, () => {
        
        let MenuItem = videojs.getComponent('MenuItem')
        let MenuButton = videojs.getComponent('MenuButton')
        
        let settingButton = new MenuButton(this.player)
        settingButton.setIcon('cog')
        
        let settingMenu = settingButton.createMenu()
        for (let quality of this.options.scaledFiles) {
          let qualityItem = new MenuItem(this.player, { label: quality.resolution })
          settingMenu.addItem(qualityItem)
        }
        settingButton.on('click', () => settingMenu.show())
        this.player.getChild('ControlBar').addChild(settingButton)
      })
    }
```

![photo_2023-12-12 18 58 12](https://github.com/videojs/video.js/assets/148888624/651ad5a3-d8a6-41b2-a8e7-f488bf4a14fb)

### Reduced test case

https://no.url.com

### Steps to reproduce

1. Creating MenuButton
2. Create menu inside MenuButton using .createMenu()
3. Add MenuItem using .addItem()

### Errors

No errors

### What version of Video.js are you using?

^8.6.1

### What browser(s) including version(s) does this occur with?

Chrome 120.0.6099.71

### What OS(es) and version(s) does this occur with?

Macos

**Comment by amtins** [comment]
@rudachenkoev what about something like?

```javascript
function setupPlayer() {
  if (!this.$refs.videoPlayer) return false;
  this.player = videojs(this.$refs.videoPlayer, this.options, () => {
    let MenuItem = videojs.getComponent('MenuItem');
    let MenuButton = videojs.getComponent('MenuButton');

    MenuButton.prototype.createItems = function (
      options = this.options.scaledFiles
    ) {
      const items = [];

      for (let quality of options) {
        items.push(new MenuItem(this.player(), { label: quality.resolution }));
      }

      return items;
    };

    let settingButton = new MenuButton(this.player);
    settingButton.setIcon('cog');

    this.player.getChild('ControlBar').addChild(settingButton);
  });
}
```

**Comment by mister-ben** [comment]
The reason it didn't work is `settingButton.createMenu()` will create a new but detached menu DOM. It doesn't return or replace the original one. `let settingMenu = settingButton.menu;` should work in your original code.

**Comment by rudachenkoev** [comment]
@mister-ben yeah, it really works, thanks
perhaps you can give some more advice on the selected option in MenuItem
I want to highlight one of the options as active, but none of the following options helped me:
1. `qualityItem.selected(<boolean>)`
2. `let qualityItem = new MenuItem(this.player, { label: quality.resolution, selected: <boolean> })`

**Comment by rudachenkoev** [comment]
figured it out.
To make MenuItem with selectable option you need to add the option `selectable: true` - `new MenuItem(this.player, { label: quality.resolution, selectable: true })`
although there is nothing about it in the [documentation](https://docs.videojs.com/menuitem)
