### ISSUE TITLE
Safari won't show programmatically created RemoteTextTracks

### ISSUE THREAD

**Issue by tsi** [videojs/video.js#8519]
### Description

Hi team,
I have already commented on https://github.com/videojs/video.js/issues/3857 but that one is very old and uses an old videojs version (v5.x) so I guess a new ticket makes sense.
The issue is with programmatically created textTracks not showing in Safari with video.js 8.7.0, "normal" textTracks from a remote VTT file do work as expected.

### Reduced test case

https://jsfiddle.net/tsish/xabnqyv4/

### Steps to reproduce

1. Create a captions textTrack using `addRemoteTextTrack` & `addCue`
2. Test in Firefox/Chrome - captions display as expected
3. Test in Safari - no captions

### What version of Video.js are you using?

8.7.0

### What browser(s) including version(s) does this occur with?

Safari 16

### What OS(es) and version(s) does this occur with?

MacOS

**Comment by mister-ben** [comment]
It seems this will only work if you delay adding the cue slightly — `setTimeout()` with a 100ms delay seems to consistently work in a quick test. The `addtrack` event on the TextTrackList is apparently also too soon.

**Comment by tsi** [comment]
Thanks @mister-ben this does help Safari display the caption 🙏 
I wonder, is there maybe some `ready` event on the textTrack that I can listen to? couldn't find any, but maybe I'm missing something...

**Comment by mister-ben** [comment]
I don't think so unfortunately. Tracks are missing a few events that would make certain workflows a lot easier.

**Comment by tsi** [comment]
Thanks @mister-ben
What I did eventually, was to similarly postpone adding cues, but with a "sleep" promise, seemed a bit more readable 

```
      player.ready(async () => {

        var track = await player.addRemoteTextTrack({
          kind: "captions",
          label: "English",
          srclang: "en",
          default: true
        });

        // Wait for Safari, otherwise track doesn't show
        await new Promise(resolve => setTimeout(resolve, 100));

        track.track.addCue(new VTTCue(1, 18, "This caption should be visible in Safari."));

      });
```
