### ISSUE TITLE
How to support MP2？

### ISSUE THREAD

**Issue by zhuxuda** [videojs/video.js#8524]
### Description

I have a video, and its audio encoding format is MP2. When playing, only the screen has no sound. May I ask how I can solve this problem. thanks

### Reduced test case

https://play2.spocube.live/transcode/hd-1-c994713c5a27bb/sd/605a3570-9dd2-402e-af92-0b80ef039659-sd.m3u8

### Steps to reproduce

1. open this url  https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fplay2.spocube.live%2Ftranscode%2Fhd-1-c994713c5a27bb%2Fsd%2F605a3570-9dd2-402e-af92-0b80ef039659-sd.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false
2. play
3.

### What version of Video.js are you using?

8.0.4

### What browser(s) including version(s) does this occur with?

chrome118

### What OS(es) and version(s) does this occur with?

mac

**Comment by mister-ben** [comment]
This plays in Chrome 118 and 120 on Mac. The first four seconds are a still image, but that seems intentional.

**Comment by mister-ben** [comment]
Closing as not reproducible, and the example link is now dead.
