### ISSUE TITLE
I used videojs flvjs. min.js and the latest version of video.js with an error message. But I use https://vjs.zencdn.net/7.11.4/video.min.js Can play videos.

### ISSUE THREAD

**Issue by itchangc** [videojs/video.js#8531]
### Description

![image](https://github.com/videojs/video.js/assets/40175292/deb97beb-e74f-4540-99e2-568867ab61ff)

Uncaught TypeError: Class constructor v cannot be invoked without 'new'
    at new r (videojs-flvjs.min.js:1:1946)
    at b.loadTech_ (video.min.js:21:1341)
    at b.src_ (video.min.js:21:21378)
    at video.min.js:21:20509
    at i (video.min.js:12:82209)
    at i (video.min.js:12:82216)
    at b.<anonymous> (video.min.js:12:82238)
    at video.min.js:12:28475

### Reduced test case

http://192.168.0.194:80/rtp/02930F45.live.flv

### Steps to reproduce

1.Video cannot be played directly, must appear
2.
3.

### Errors

Uncaught TypeError: Class constructor v cannot be invoked without 'new'
    at new r (videojs-flvjs.min.js:1:1946)
    at b.loadTech_ (video.min.js:21:1341)
    at b.src_ (video.min.js:21:21378)
    at video.min.js:21:20509
    at i (video.min.js:12:82209)
    at i (video.min.js:12:82216)
    at b.<anonymous> (video.min.js:12:82238)
    at video.min.js:12:28475

### What version of Video.js are you using?

video-js-8.8.0/

### Video.js plugins used.

videojs-flvjs.min.js

### What browser(s) including version(s) does this occur with?

chrome and edge

### What OS(es) and version(s) does this occur with?

win 11

**Comment by itchangc** [comment]
![image](https://github.com/videojs/video.js/assets/40175292/7e40aa4b-d773-4ce0-87f9-8bcf643c6322)
I tested it and it can't be used since video 8.0.0

**Comment by itchangc** [comment]
cnd是从 https://www.bootcdn.cn/video.js/

https://cdn.bootcdn.net/ajax/libs/video.js/8.0.1/alt/video.core.min.js

**Comment by mister-ben** [comment]
This error is where a transpiled rather than native es6 class is used. Basically, plugins' build scripts need to be updated to leave classes intact in their dist version. See https://github.com/mister-ben/videojs-flvjs/issues/29 in this case.
