### ISSUE TITLE
Error playing HEVC that's supported by Chrome

### ISSUE THREAD

**Issue by daveisfera** [videojs/video.js#8549]
### Description

Works with Safari and HLS.js but fails with Video.js on Chrome

([HLS.js will play it with the tag of `hev1` but not with `hvc1`](https://github.com/video-dev/hls.js/issues/6086) which is what `ffmpeg` prefers/recommends)

### Reduced test case

https://raw.githubusercontent.com/daveisfera/hls_hevc_tag/main/index_hvc1.m3u8

### Steps to reproduce

1. Open URL in demo player ( https://videojs-http-streaming.netlify.app )
2. Observe error about no supported playlist

### Errors

```
videojs-http-streaming.js:33832 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists.
```

### What version of Video.js are you using?

8.6.1

### Video.js plugins used.

N/A

### What browser(s) including version(s) does this occur with?

120.0.6099.199 (x86_64)

### What OS(es) and version(s) does this occur with?

macOS 14.2.1

**Comment by mister-ben** [comment]
The playlist is rejected because Chrome reports that it can't play it — `window.MediaSource.isTypeSupported('video/mp4;codecs="hvc1.1.4.L150.B01"')` returns `false`

**Comment by daveisfera** [comment]
Looks like [`ffmpeg` has part of `CODECS` hard coded to `4` and `B01` on the end](https://trac.ffmpeg.org/ticket/10786). From poking around with that, the `B01` is what Chrome doesn't like, so I'll follow up with `ffmpeg`
