### ISSUE TITLE
Audio not working on Android devices

### ISSUE THREAD

**Issue by mbrigham19** [videojs/video.js#8555]
### Description

Playing any sort of media (video or audio) on an Android device in Chrome or Edge doesn't have any sound output. The 'muted' icon isn't present, but no audio is playing. This is occurring on Samsung Galaxy and Pixel devices.

### Reduced test case

https://codepen.io/gkatsev/pen/GwZegv?editors=1000

### Steps to reproduce

1. Open the link in an Android device in Chrome or Edge
2. Play the video 
3. Observe that there is no sound output

### What version of Video.js are you using?

8.9.0

### What browser(s) including version(s) does this occur with?

Chrome 117, Edge 111

### What OS(es) and version(s) does this occur with?

Android 12, 13, 14

**Comment by gkatsev** [comment]
I'm unable to reproduce is in Chrome for Android v120 on a pixel running android 14.

Do you have any other reduced test cases we can take a look? Any errors in the or other relevant logs in the console?

**Comment by mister-ben** [comment]
I also have encountered this or heard of any other report. Are you testing on real devices or some kind of emulator?

**Comment by anthonyrivas** [comment]
I can reporduce on an emulator (Browserstack) but not on an actual device!

**Comment by mister-ben** [comment]
Browserstack [documents](https://www.browserstack.com/question/39397) that audio doesn't work in Chrome on Android, and it apparently doesn't in Edge now either. I asked their support and they confirmed:

> Currently, support for browser audio is not available on Android devices and our team is working towards providing the same in the future. In addition to that, we will modify the documentation to avoid any further confusion.
