### ISSUE TITLE
how to create quality selector in version 8

### ISSUE THREAD

**Issue by xavier-che** [videojs/video.js#8563]
### Description

I have been trying for three days to find any information and answers, but all in vain.
I tried to import 'videojs-contrib-quality-levels' and  import 'videojs-hls-quality-selector',
but always said "Property 'qualityLevels' does not exist on type 'Player'" and "Property 'hlsQualitySelector' does not exist on type 'Player'".
Im using Angular for this, anyone can help me, plz....

### Reduced test case

no

### Steps to reproduce

as detailed

### What version of Video.js are you using?

8.9.0

### What browser(s) including version(s) does this occur with?

chrome

### What OS(es) and version(s) does this occur with?

windows 10

**Comment by iblack10** [comment]
I don't think [videojs-hls-quality-selector](https://github.com/chrisboustead/videojs-hls-quality-selector) supports video.js v8 yet. I've had some success using [jb-videojs-hls-quality-selector](https://www.npmjs.com/package/jb-videojs-hls-quality-selector)  which is a fork that's been updated to work with v8.

**Comment by xavier-che** [comment]
> I don't think [videojs-hls-quality-selector](https://github.com/chrisboustead/videojs-hls-quality-selector) supports video.js v8 yet. I've had some success using [jb-videojs-hls-quality-selector](https://www.npmjs.com/package/jb-videojs-hls-quality-selector) which is a fork that's been updated to work with v8.

OMG! That works! thank you so much!
