### ISSUE TITLE
Serious issues on EdgeHTML

### ISSUE THREAD

**Issue by Pedro1234-code** [videojs/video.js#8571]
### Description

VideoJS does not work correctly on EdgeHTML in Windows 10 Mobile or Windows 10 RT in portrait. Videos don't play and there is a giant black thing in the screen. 

![wp_ss_20240127_0001](https://github.com/videojs/video.js/assets/78425126/6dd031a1-a0b3-4337-9ef9-8dafbcc10b1a)

Putting it on landscape works. It's a very annoying situation.

### Reduced test case

Don't know

### Steps to reproduce

1. Open any site with VideoJS in Windows 10 Mobile or Windows 10 RT or any PC with an EdgeHTML UWP browser.
2. Put it in portrait mode.
3. You will see it happening.

### What version of Video.js are you using?

Not sure but all sites with VideoJS has the same bug.

### What browser(s) including version(s) does this occur with?

Tested by myself: Edge 40.15254.603 and the version that ships with Windows 10 15035. I also heard people saying the same about other EdgeHTML versions.

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by mister-ben** [comment]
Video.js 8 does not support pre-Chromium Edge. It's possible an older version might work on these devices, but I'm not certain how far back you might have to go.
