### ISSUE TITLE
Subtitles Peculiarities

### ISSUE THREAD

**Issue by anthonygreco** [videojs/video.js#8574]
### Description

I've seen several other posts of subtitles not working properly but none of the answers resolve the issue. Are subtitles never going to work in this player? Complete details to the issue found here: https://stackoverflow.com/questions/77910419/videojs-not-showing-subtitles

### Reduced test case

https://master--mellow-muffin-2473a9.netlify.app/

### Steps to reproduce

Simply attempt to use subtitles in the player per the documentation.

### Errors

No errors are displayed.

### What version of Video.js are you using?

8.10.0

### Video.js plugins used.

None

### What browser(s) including version(s) does this occur with?

Chrome and Safari

### What OS(es) and version(s) does this occur with?

OS X

**Comment by gkatsev** [comment]
Your subtitles file is slightly malformed. You need an extra new line after the `WEBVTT` header. Adding it in locally fixes the issues. Hope that helps.

**Comment by mister-ben** [comment]
FWIW there's a WebVTT validator here: https://w3c.github.io/webvtt.js/parser.html

**Comment by anthonygreco** [comment]
> Your subtitles file is slightly malformed. You need an extra new line after the `WEBVTT` header. Adding it in locally fixes the issues. Hope that helps.

I actually discovered that about an hour after I had posted this and totally thought I had closed this. Apologies for the clutter in your inbox and props for being a reactive OSS dev! Great work on this project!
