### ISSUE TITLE
How to seek a long duration

### ISSUE THREAD

**Issue by vanminhquangtri** [videojs/video.js#8575]
Hello everyone,

I am using videojs to play video content. The problem is, if I seek a duration about 10 minutes, it's ok. 
But if I seek longer, for example 30 minutes, 40 minutes, the TS file is loaded, but player keep loading.
I have read the docs but can't find how to set the limit of seeking.

My videojs version: 7.15.0
My stream url: https://tshift.fptplay.net/tv/vtv3HD/index_1706798400_3000.m3u8
My videojs config: 

```
{
language: 'vi',
  languages: {
    vi: LANGUAGE,
  },
  responsive: true,
  autoplay: true,
  muted: true,
  aspectRatio: '16:9',
  controls: true,
  poster: '/images/player/poster-default.jpg',
  textTrackSettings: false,
  bigPlayButton: false,
  controlBar: {
    pictureInPictureToggle: false,
    children: [
      'playToggle',
      'liveDisplay',
      'volumePanel',
      'currentTimeDisplay',
      'durationDisplay',
      'progressControl',
      'seekToLive',
      'customControlSpacer',
      'playbackRateMenuButton',
      'chaptersButton',
      'descriptionsButton',
      'subsCapsButton',
      'audioTrackButton',
      'fullscreenToggle',
    ],
  },
  dnaConfig: {},
  html5: {
    hls: {
      overrideNative: true,
    },
    nativeAudioTracks: false,
    nativeVideoTracks: false,
  },
}
```

I hope to receive any advice. Thank you.

**Comment by mister-ben** [comment]
The link is inaccessible. Do the segment durations in the manifest match the actual segment durations? That can break seeking calculations.
