### ISSUE TITLE
Should video.js be able to play this fmp4 HEVC video on Chrome/Firefox? (hls.js is able to)

### ISSUE THREAD

**Issue by SebastianSchoeps** [videojs/video.js#8577]
### Description

I have videos that can be played by hls.js but not video.js (besides Safari). I tried many different things with e.g. techOrder and the different hls-plugins, but to no success.

[video.js (not working)](https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fweb.taggy.cam%2Flivestreams%2FGfzeAjbtpXuvhqcGpMPYyyWV140fbOOj%2Fvideo.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false)
[hls.js (working)](https://hlsjs.video-dev.org/demo/?src=https%3A%2F%2Fweb.taggy.cam%2Flivestreams%2FGfzeAjbtpXuvhqcGpMPYyyWV140fbOOj%2Fvideo.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==)

Should it be possible generally to play that video in video.js? Does it have some kind of messed-up format?

Thanks for any hint pointing to where I could go next - I am a little lost at this point.

Sebastian

### Reduced test case

https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fweb.taggy.cam%2Flivestreams%2FGfzeAjbtpXuvhqcGpMPYyyWV140fbOOj%2Fvideo.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false

### Steps to reproduce

Use the URL to play the video

### What version of Video.js are you using?

8.9.0

### Video.js plugins used.

http-streaming

### What browser(s) including version(s) does this occur with?

Chrome, Firefox (Safari works)

### What OS(es) and version(s) does this occur with?

macOS

**Comment by mister-ben** [comment]
CORS issues aside, it should play if there were a multivariate playlist declaring the codec, rather than using just a media playlist, e.g.

```
…
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=343200,CODECS="mp4a.40.2,hvc1.1.60000000.L150",RESOLUTION=320x180,CLOSED-CAPTIONS=NONE
https://web.taggy.cam/livestreams/GfzeAjbtpXuvhqcGpMPYyyWV140fbOOj/video.m3u8
```

**Comment by SebastianSchoeps** [comment]
Thank you very much, @mister-ben! Indeed, it works - you are a lifesaver! Astonished by the great support...

**Comment by SebastianSchoeps** [comment]
@mister-ben One last question: it plays on:
Mac: Chrome/Safari/Edge
Windows: Chrome/**not Edge** 

Edge is at the same version on Mac and Windows (121.0.2277.98).

Here's the new link without CORS issues: https://taggy-test.b-cdn.net/test/hlstest4/playlist.m3u8

Any idea why that might be the case?

**Comment by SebastianSchoeps** [comment]
Thanks!
