### ISSUE TITLE
RTMP Secure Token support

### ISSUE THREAD

**Issue by hryuk** [videojs/video.js#858]
It would be fine if videojs supports secure token authentification of rtmp streams like jwplayer does (See 'SECURE TOKEN' section):

http://www.longtailvideo.com/support/jw-player/28854/using-rtmp-streaming

**Comment by mmcc** [comment]
@httpdigest I just realized I never got back on the question about PRs. The work flow you described is pretty much exactly spot on. Any progress on this?

**Comment by erald** [comment]
Am trying to use the secure links feature on a rtmp stream and had the same problem: The link is not working. Looks like the same problem.
My link looks like rtmp://xx.xx.xx.xx:1935/vod/bbb.mp4?st=eFOnE1qDD3UnEIoTgtr8UA&e=1465282095

is there any progress on this? Hate to drop video.js for my projects

**Comment by jackli0855** [comment]
+1

**Comment by TopCoderMyDream** [comment]
+1

**Comment by shscy** [comment]
wtf
