### ISSUE TITLE
Share Link doesn't default to the current URL

### ISSUE THREAD

**Issue by churchillnlm** [videojs/video.js#8589]
### Description

When you select Settings from the control bar then Share the Link has N/A and doesn't default to the current URL. 

To get the Share Link you have to hard code it:
     player.nuevo({
          url: '//github.com'
      });

### Reduced test case

/videojs/examples/index.html

### Steps to reproduce

1.Settings
2.Share
3.

### Errors

No errors

### What version of Video.js are you using?

8.10.0

### What browser(s) including version(s) does this occur with?

Current versions of Edge, Chrome and Chrome

### What OS(es) and version(s) does this occur with?

Windows 10 Enterprise

**Comment by mister-ben** [comment]
The nuevo plugin isn't part of Video.js core or created by this team. Please log with the plugin developer's repo/support, they can help you better.

**Comment by churchillnlm** [comment]
Thanks.
