### ISSUE TITLE
Yo can modify the Google Drive URL to get a direct link - see e.g. http://www.labnol.org/internet/direct-links-for-google-drive/28356/

### ISSUE THREAD

**Issue by dhanil-vd123** [videojs/video.js#8600]
Yo can modify the Google Drive URL to get a direct link - see e.g. http://www.labnol.org/internet/direct-links-for-google-drive/28356/

```
<source src="https://drive.google.com/uc?export=download&id=0B-zKk5F6hm6rOXJicnBSOHIyd28" type='video/mp4'>
```

_Originally posted by @mister-ben in https://github.com/videojs/video.js/issues/2027#issuecomment-92766494_

the above one is not working, and it was working few weeks back when i try. but with the same configuration it is not working

**Comment by mister-ben** [comment]
It looks like they send a `403` response now if there is an `Origin` header, which there always will be when trying to play in a browser. If anything I'm surprised it's worked as long as it has, Google presumably doesn't want Google Drive to be used this way.
