### ISSUE TITLE
support of multi Audio

### ISSUE THREAD

**Issue by iptvsmartws** [videojs/video.js#8605]
Hello Video.js Team,

I'm developing a web-based application targeted at LG's webOS platform and am currently evaluating Video.js for media playback functionalities. My application needs to play MKV video files that contain multiple audio tracks and subtitles, utilizing Media Source Extensions (MSE) for dynamic stream manipulation.

Before proceeding, I have a few questions regarding Video.js's capabilities in this specific context:

Multi-Audio Track Support: Does Video.js support switching between multiple audio tracks in MKV files when played through MSE on webOS? If so, could you provide guidance or examples on how to implement this feature?

Subtitle Support: Similarly, does Video.js offer support for displaying subtitles from MKV files in a webOS web-based application? Are there specific steps or configurations required to enable subtitle selection and display through MSE?

webOS Compatibility: Are there any known limitations or considerations when using Video.js for MKV playback with MSE on the webOS platform? Any tips on ensuring smooth playback and track handling on webOS would be greatly appreciated.

MKV and MSE: Given the complexity of MKV as a container format, are there any best practices for packaging MKV content for MSE streaming that you would recommend to ensure compatibility with Video.js?

Our goal is to provide a seamless viewing experience for our users, allowing them to choose their preferred audio tracks and subtitles during playback. Any insights or advice you could offer would be invaluable as we move forward with our development.

Thank you for your time and assistance.

Best regards,

**Comment by friendtasy** [comment]
Multi-Audio and Subtitle need create  dash or hls

**Comment by mister-ben** [comment]
Video.js has no built in support for playing MKV files with MSE. Conceivably support could be added with a source handler, but realistically converting to a format more suitable for streaming, DASH or HLS as friendtasy says, would usually be a better course of action.
