### ISSUE TITLE
Changing audio tracks triggers textTracks change event on Safari.

### ISSUE THREAD

**Issue by lalit-tudip** [videojs/video.js#8617]
### Description

On Safari, I noticed whenever I change the audio tracks the caption(textTracks) `change` event is triggered. The same behavior is not noticed on the Chrome browser.

**Below is the event I'm using:**
```
this.player.textTracks().on("change", function action(event) {
      console.log("textTracks change", event);
    });
```

**Below is my code for changing audio tracks:**
```
    const audioTracks = this.playerTest.audioTracks().tracks_;
    const selectedAudioTrack = audioTracks.find(
      (track) =>
        track.language?.toLowerCase() ===
        this.state.captionSettings.audio?.toLowerCase()
    );

    // Check if the selected audio track exists
    if (selectedAudioTrack) {
      // Disable all other audio tracks
      audioTracks.forEach((track) => {
        if (track !== selectedAudioTrack) {
          track.enabled = false;
        }
      });

      // Enable the selected audio track
      selectedAudioTrack.enabled = true;
    }
```

@gkatsev @mister-ben Could you please assist me with this?

### Reduced test case

NA

### Steps to reproduce

It is just a question/doubt, will the text tracks change event trigger on changing the audio on Safari?

### Errors

NA

### What version of Video.js are you using?

7.21.4

### Video.js plugins used.

"videojs-contrib-dash": "5.1.0",     "videojs-contrib-eme": "3.9.0", "@videojs/http-streaming": "^2.8.0",

### What browser(s) including version(s) does this occur with?

Mac Safari 17.3.1

### What OS(es) and version(s) does this occur with?

Mac Sonoma 14.3.1

**Comment by mister-ben** [comment]
I tested a couple of sources and do not see this happening. Please add a [reduced test case](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates exactly what you have.

**Comment by gkatsev** [comment]
i could imagine it might do it depending on your locale and various user preferences safari decided are appropriate for you, so, that when the audio track is chnaged, it may think that a different text track is now appropriate.
