### ISSUE TITLE
Video starts on fullscreen on iOS devices

### ISSUE THREAD

**Issue by JESUMH** [videojs/video.js#8619]
### Description

Hi,

Video starts on fullscreen mode when autoplay config is enabled.

We use `playsinline` attribute to prevent this issue (recommended on VideoJS docs) but it not takes effect.

Is it possible to prevent this behavior? 

I attach videojs-http-streaming demo that contains autoplay config, but it occurs in all players.

Thanks!

### Reduced test case

https://videojs-http-streaming.netlify.app/?debug=false&autoplay=true&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fd2zihajmogu5jn.cloudfront.net%2Fbipbop-advanced%2Fbipbop_16x9_variant.m3u8&type=application%2Fx-mpegurl&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false

### Steps to reproduce

1. Enter on video page with autoplay
2. Video starts on fullscreen

### What version of Video.js are you using?

8.10.0

### What browser(s) including version(s) does this occur with?

Safari

### What OS(es) and version(s) does this occur with?

iOS 15+

**Comment by mister-ben** [comment]
The http-streaming page does not use `playsinline` so is not the same as your description.  Please add a [reduced test case](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue. I'd expect a player with `playsinline`, `autoplay` and `muted` would play inline.

**Comment by JESUMH** [comment]
Hi,

@mister-ben finally I fixed this issue using inline property in video method of library canAutoplay. 

Thank you,
Jesús Martínez

**Comment by SarveshMishra001** [comment]
`playsInline` will help you @JESUMH 
`playinline` works with android devices but one need to use `playsInline` for iOS devices.

`<video
              className="w-32 h-40"
              loop
              autoplay="autoplay"
              muted
              playsInline
            >
              <source
                src={`/abc.mp4`}
                type="video/mp4"
              />
            </video>`
