### ISSUE TITLE
Trigger durationchange in the duration() method

### ISSUE THREAD

**Issue by heff** [videojs/video.js#863]
In #861 we hit a callstack size error because of a loop between duration() and onDurationChange().

We're not handling duration changes as cleanly as we should be. What should be happening is the tech should be listening for its own `durationchange` event, and when it occurs, set duration on the player instead of triggering the durationchange event on the player. Then the durationchange event should be triggered inside the duration() method after the cached duration is updated.

Related work: #2057

**Comment by dmlap** [comment]
The [Techs 2.0 plan](https://github.com/videojs/video.js/milestones/Techs%202.0) is to have the player be responsible for listening to the tech to discover any interesting state changes. In the case of `durationchange`, the player would listen for this event on the tech and bubble it out to any external listeners. That means that we *should not* be triggering `durationchange` in duration()-- the responsibility for emitting the event would be on the tech.

It also means that `durationchange` will probably occur asynchronously. That is consistent with HTML5 video `durationchange` events.

**Comment by eXon** [comment]
@dmlap see https://github.com/videojs/video.js/pull/2057 for how the tech 2.0 will be. It's almost done.
