### ISSUE TITLE
On Edge browser, an unexpected mini menu appears on the control bar of the video player when users double-click on it.

### ISSUE THREAD

**Issue by binhphan009** [videojs/video.js#8648]
### Description

When using the Edge browser, an unexpected mini menu appears on the control bar of the video player when users double-click on it.

### Reduced test case

https://videojs.com/city

### Steps to reproduce

1. Go to https://videojs.com/city
2. Click the Play button
3. Double click on the control bar
4. Observe the appearance of the mini menu.

### Errors

the appearance of the mini menu
<img width="56" alt="image" src="https://github.com/videojs/video.js/assets/105278576/114c4587-acf1-4ceb-b597-9d034f85d70b">

<img width="588" alt="image" src="https://github.com/videojs/video.js/assets/105278576/108cac51-f8fe-4f24-9dca-575a2ab81b98">

The video player should not show mini menu when user double click on it.

### What version of Video.js are you using?

8.10.0

### What browser(s) including version(s) does this occur with?

Microsoft Edge

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by amtins** [comment]
Hi @binhphan009 I'm not sure if it's a player bug, I have the impression it's a feature Edge wants. It's reproducible pretty much everywhere. 

A possible workaround could be to stop `mouseup` bubbling either in the player or in the window itself, depending on the experience you want to offer.

However, it would be interesting to make sure that this doesn't cause any side-effects.

**Only the player**
```javascript
player.on('mouseup', (e)=> e.preventDefault());
```

**The entire page**
```javascript
window.onmouseup = event => event.preventDefault();
```

**Comment by binhphan009** [comment]
thanks @amtins for prompt response. Your solution works well.
