### ISSUE TITLE
Video doesn't show in IE 8

### ISSUE THREAD

**Issue by clancioni** [videojs/video.js#865]
Hi.
I've a video in mp4 and webm formats. The problem is that it work well on chrome and firefox but it doesn't work in Internet Explorer 8.
The page give an error on line 56 of video.js: "h" is null or not an object...
I've avada theme, Wordpress 3.6.1 and wpml. My version of Video JS is 4.2
What can I do?

Thanks in advance.
Cristina.

**Comment by thejae** [comment]
Just wanted to chime in on this issue. I ran into the same problem with Internet Explorer 7. Where it would scream:
```
Line 56 of video.js: "h" is null or not an object
```

As correctly pointed out by @sp00n and this thread on StackOverflow: http://stackoverflow.com/q/18506062/541591

Error only occurs when Adobe Flash has not been installed/ enabled.
