### ISSUE TITLE
Can not switch audio Iphone

### ISSUE THREAD

**Issue by kapahin** [videojs/video.js#8657]
Hello, 

My app play m3u8 stream which have multiple audios, codes is mp4a.40.2. The problem is with Iphone (both Safari and Chrome).
Version Videojs I use is 8.10.0.
When I call function player.audioTracks(), it always return empty. So the player alway play the default audio.
I tested with Iphone from 7Plus to 15Pro Max, no devices works.
While It works all windows, MacOS, Android Mobile.

Can you please let me know is this because Apple IOS not support? Or I have to use another way to swith audio?

This is how I switch audio:

```
const tracks = player.audioTracks();
for (let i = 0; i < tracks.length; i++) {
      if (tracks[i].language === selectedLanguage) {
        tracks[i].enabled = true;
      } else {
        tracks[i].enabled = false;
      }
 }
```

Thank you.

**Comment by mister-ben** [comment]
iOS's native playback does support multi audio tracks in HLS, I've seen plenty of streams work with it. There's not enough information here to say why it might not work with your stream or setup.
