### ISSUE TITLE
when enableDocumentPictureInPicture is true and at PictureInPicture play video the Progress bar can't undate..

### ISSUE THREAD

**Issue by R8KwEwN2hvrhY** [videojs/video.js#8663]
### Description

when enableDocumentPictureInPicture is true and at PictureInPicture play video the Progress bar can't update..
<img width="825" alt="11111111" src="https://github.com/videojs/video.js/assets/17196859/de3be926-378b-4f54-aa47-628711925edc">

### Reduced test case

NONE

### Steps to reproduce

1.when enableDocumentPictureInPicture is true and at PictureInPicture play video the Progress bar can't undate..
2.
3.

### What version of Video.js are you using?

8.11.3

### What browser(s) including version(s) does this occur with?

CHROME 123

### What OS(es) and version(s) does this occur with?

WINDOWS 11

**Comment by mister-ben** [comment]
Closing as there is no reproducible example.

**Comment by R8KwEwN2hvrhY** [comment]
on website 
https://videojs.com/
play "sintel" video at PictureInPicture...
<img width="397" alt="11" src="https://github.com/videojs/video.js/assets/17196859/831ff7a1-ddfc-4412-a72c-66ec35c300c0">
<img width="420" alt="22" src="https://github.com/videojs/video.js/assets/17196859/6cb2405d-0cff-4a4e-acff-1a835d473d88">
