### ISSUE TITLE
firefox cannot play videos?

### ISSUE THREAD

**Issue by DesenEnterprises** [videojs/video.js#8665]
### Description

I see old posts about firefox being an issue. Is it still? I can play on all browsers but not firefox. I do see that the videojs.com web site plays video's just fine in the same firefox browser, however.

What do I need to do to make it work for me?

I'm using just a standard embed with a <video tag.

### Reduced test case

http://videos.prophecyandtruth.com/

### Steps to reproduce

1.load the page in firefox

### Errors

no error displayed, it just never loads the videos past the poster...

### What version of Video.js are you using?

latest download

### Video.js plugins used.

none

### What browser(s) including version(s) does this occur with?

firefox latest version

### What OS(es) and version(s) does this occur with?

iOS and windows

**Comment by mister-ben** [comment]
This page isn't using Video.js. Firefox used to have limited codec support, now it uses the OS's support for h264. There might still be codecs missing on some Linux boxes and less common Windows setup, but generally ok now. Looking now the videos do play, so perhaps a local machine issue.
