### ISSUE TITLE
Remove JSON shim to avoid eval() CSP issues

### ISSUE THREAD

**Issue by paz** [videojs/video.js#867]
(updated title and description to describe the enhancement)

IE8 supports JSON in IE8 standards mode (the default), but not other browser modes. In 5.0 we should be able to ask video.js users who need to support JSON in other modes or older browsers to supply their own JSON shim. This way we can avoid Content Security Policy issues that come up, even when the shim isn't used. 

This shouldn't be removed in 4.0 because of the potential to break existing installs, including those that are still making Video.js work with IE6 & 7.

**Original Title + Description**

### eval() in vjs.JSON.parse forces use of 'unsafe-eval' in Content Security Policy in order for VideoJS to work

eval() in vjs.JSON.parse forces use of 'unsafe-eval' in Content Security Policy in order for VideoJS to work. Is there any chance the JSON parser will move to a non-eval()ing parser? 

In vjs.JSON.parse on line 7024 in video.dev.js:
```
j = eval('(' + text + ')');
```

**Comment by dconnolly** [comment]
I'm taking this up. :+1:

**Comment by dconnolly** [comment]
Fixed by c62aa10637c1f967ef4633924b363dd827336f11
