### ISSUE TITLE
Ionic app with video.js on Android will not enable the picture in picture button

### ISSUE THREAD

**Issue by jkyoutsey** [videojs/video.js#8680]
### Description

An Ionic app using video.js deployed to an Android device will not enable the picture in picture button. PiP works fine on iOS and web, but not on an Android device.

I've added `android:supportsPictureInPicture="true"` to the AndroidManifest.xml and if I open settings for the app on the device it shows that the Picture in Picture permission is allowed. But the button for PiP is always disabled on Android. I've tried this on multiple simulators and physical devices and in the below reproduced application and a much more complex application scenario.

### Reduced test case

https://github.com/jkyoutsey/ionic-videojs-playback-rates-flicker-bug

### Steps to reproduce

1. Follow instructions in the README.md in the repo

### What version of Video.js are you using?

^8.9.0

### Video.js plugins used.

vjs-show-big-play-button-on-pause

### What browser(s) including version(s) does this occur with?

n/a

### What OS(es) and version(s) does this occur with?

Android 13

**Comment by mister-ben** [comment]
AFAIK Android webviews don't support picture-in-picture. See e.g. [here](https://chromium.googlesource.com/chromium/src/+/165531a5b2e188857170f1b3d330d752f2cda65d%5E%21), "`document.pictureInPictureEnabled` will always be false"
