### ISSUE TITLE
Tap to click not work not progressbar

### ISSUE THREAD

**Issue by maytinhdibo** [videojs/video.js#8691]
### Description

On macOS, when playing video, can not light click (tap) to change progress bar

### Reduced test case

https://videojs.com/advanced/?video=disneys-oceans

### Steps to reproduce

1. Play a video
2. Light click (tap) on progress bar

### What version of Video.js are you using?

newest

### What browser(s) including version(s) does this occur with?

Chrome, Firefox

### What OS(es) and version(s) does this occur with?

macOS

**Comment by mister-ben** [comment]
Do you mean when using "Tap to click" enable in MacOS's trackpad settings?

**Comment by maytinhdibo** [comment]
> Do you mean when using "Tap to click" enable in MacOS's trackpad settings?

Yes, it's enabled on macOS setting, but must strong click (force touch) to click progress bar.

**Comment by mister-ben** [comment]
A "tap to click" reaches [here](https://github.com/videojs/video.js/blob/21b4a5225bf98cc4a491d62625fd6f0d40fdd3e8/src/js/utils/dom.js#L776-L782) and considered not a single left click because `event.buttons` is `0` on `mousedown`.

**Comment by maytinhdibo** [comment]
> A "tap to click" reaches [here](https://github.com/videojs/video.js/blob/21b4a5225bf98cc4a491d62625fd6f0d40fdd3e8/src/js/utils/dom.js#L776-L782) and considered not a single left click because `event.buttons` is `0` on `mousedown` on Sonoma. On Ventura it'a usually `1` but sometimes also `0`.

I think we have to change it to click event. Default video tag handle this event. This issue is only on video.js. Sync with native behaviour.
