### ISSUE TITLE
Green texttrack color not handled

### ISSUE THREAD

**Issue by kasty** [videojs/video.js#8692]
### Description

The green color that should be applied to some of our textrack according to the VTT file content is not applied. Other colors like magenta or cyan are correctly handled

### Reduced test case

https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fmanifest-arte.akamaized.net%2Fapi%2Fmanifest%2Fv1%2FGenerate%2F231229114532%2Ffr%2FXQ%2BKS%2F110195-005-A.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=false&preload=auto&mirror-source=true&forced-subtitles=true

### Steps to reproduce

1. Play the given manifest
2. Enable "français (sourds et malentendants)" subtitles
3. Go to 1:50 : subtitles are in cyan color, it's correct according to the VTT content 
```
00:01:50.760 --> 00:01:53.480 line:83% align:center
<c.cyan.bg_black>puis a financeÌ ses eÌtudes aux USA</c>
<c.cyan.bg_black>en travaillant.</c>
```
4. Now go to 2:31, the text "pensez-vous que nous sommes" should be green according to the VTT content but they are white
```
(00:02:31.680 --> 00:02:33.800 line:58% align:center
<c.green.bg_black>Pensez-vous que nous sommes</c>)
```

### What version of Video.js are you using?

8.6.1

### What browser(s) including version(s) does this occur with?

Chrome 123

### What OS(es) and version(s) does this occur with?

MacOS 13.4.1

**Comment by mister-ben** [comment]
Hmm, there's [no green defined in vtt.js](https://github.com/videojs/vtt.js/blob/2eb1ea469f06478cd40268fe9d7de5746dee60fb/lib/process/parse-content.js#L30-L39). A CSS rule like `.vjs-text-track-display span.green { color: #0f0; }` would work.

**Comment by mister-ben** [comment]
> If your background is captioning, don’t get confused: The color for the class lime is what has traditionally been used in captioning under the name [green](https://www.w3.org/TR/css-color-4/#valdef-color-green) (e.g. 608/708).

https://www.w3.org/TR/webvtt1/#default-text-color 😕

**Comment by kasty** [comment]
> Hmm, there's [no green defined in vtt.js](https://github.com/videojs/vtt.js/blob/2eb1ea469f06478cd40268fe9d7de5746dee60fb/lib/process/parse-content.js#L30-L39). A CSS rule like `.vjs-text-track-display span.green { color: #0f0; }` would work.

Yes that's exactly what we did in the meantime but I understand that it will finally stay that way :) Thanks for the inquiry

**Comment by gkatsev** [comment]
Switching to `lime` would be most compliant.
