### ISSUE TITLE
currentTime(641) is succeeded，but the video is seeked to 0

### ISSUE THREAD

**Issue by husongge-tal** [videojs/video.js#8699]
### Description

When I used currentTime(641), the seek was successful（Because we detected the player's seek event
）, but the browser reported an error and the video started playing from 0 seconds（We have once again detected the player's seek event，and In fact, the video started playing from 0 seconds）, I have only used currentTime once. Why?
my code:

if(this.player) {
this.player.currentTime(newVal);
}
……
this.player.on('seeked', function () {
        console.log('The video has seeked!', this.player.currentTime());
      });

event listeners ：
![events](https://github.com/videojs/video.js/assets/131868420/4a5caf82-ecf1-4693-adff-de51dc8930c0)

### Reduced test case

http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

### Steps to reproduce

1. this.player = videojs(videoDomId, this.options, async () => {this.player.play()});
2. add events listener
3.this.player.currentTime(641)

### Errors

the error picture:
![error](https://github.com/videojs/video.js/assets/131868420/39a44c0a-83fa-4a1d-b5f9-bb8e5d48b43e)

### What version of Video.js are you using?

8.10.0

### What browser(s) including version(s) does this occur with?

Chrome/78

### What OS(es) and version(s) does this occur with?

MacBook Pro (16-inch, 2019)

**Comment by mister-ben** [comment]
The test stream is not playable as it lacks CORS headers and is http. Running on localhost and modifying headers, no such behaviour is observable.

```
player.on('seeked', function () {
  console.log('The video has seeked!', player.currentTime());
});
player.play();
player.currentTime(641)
```

```
VM54:2 The video has seeked! 641
```

Please read [these guidelines](https://stackoverflow.com/help/minimal-reproducible-example) on creating a reduced test case.

**Comment by mister-ben** [comment]
Closing as no actionable information.
