### ISSUE TITLE
How do I disable pauses in the video tag？

### ISSUE THREAD

**Issue by trookie2000** [videojs/video.js#8702]
### Description

Using webrtc and js to listen to events, I was able to remotely control the shared computer. But there is a problem, when I left click (for example to close a window on the shared device), the sharing screen will pause.

But when I use

@click="mouseHandler($event)"
onMounted(() =&gt;  {
remoteDesktop();  // Call remoteDesktop method on component mount
});

After, all mouse operations are forbidden (including clicking and sliding the mouse), how to solve

### Reduced test case

null

### Steps to reproduce

1.<video class="video" ref="videoElements"
          :srcObject="video.stream" controls  autoplay @mousedown="e => mouseDown(e, $refs.videoElements[index])"
          @mouseup="e => mouseUp(e, $refs.videoElements[index])"
          @mousemove="e => mouseMove(e, $refs.videoElements[index])" @wheel="e => wheel(e, $refs.videoElements[index])"
          @contextmenu.prevent="e => rightClick(e, $refs.videoElements[index])"
          @dblclick="toggleFullScreen($refs.videoElements[index])" @click="mouseHandler($event)">
        </video>
2.const mouseHandler = (event) => {
      // 阻止视频默认点击事件
      event.preventDefault();
    };

### What version of Video.js are you using?

null

### What browser(s) including version(s) does this occur with?

null

### What OS(es) and version(s) does this occur with?

null

**Comment by trookie2000** [comment]
controlslist currently only supports disabling nodownload, nofullscreen, and noremoteplayback.

**Comment by mister-ben** [comment]
You can disable the default click action. See https://videojs.com/guides/options/#useractionsclick

`"userActions": {"click": false}`
