### ISSUE TITLE
Is there any way to play clean h265 videos with the current player?

### ISSUE THREAD

**Issue by pedro-demeu** [videojs/video.js#8710]
### Description

Hi guys, I need to play videos in h265 in my player that uses videoJS, but I can't find a player that works anywhere, there is an example that I managed to find but it doesn't support all types of h265 videos and I would like a final version without bugs, with good integration, is there a tutorial or something that can help me on this journey? So far I haven't found anything concrete, and if there isn't a solution, how difficult would it be for me to implement something functional? I am Mid level frontend working with React and TS.

Link to demo that supposedly has a video running in h265:
https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fdemo.unified-streaming.com%2Fk8s%2Ffeatures%2Fstable%2Fvideo%2Ftears-of-steel%2Ftears-of-steel-hevc.ism%2F.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false

### Reduced test case

https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fdemo.unified-streaming.com%2Fk8s%2Ffeatures%2Fstable%2Fvideo%2Ftears-of-steel%2Ftears-of-steel-hevc.ism%2F.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false

### Steps to reproduce

1.
2.
3.

### What version of Video.js are you using?

7.20.3

### Video.js plugins used.

"videojs-errors": "^4.3.2",     "videojs-hlsjs-plugin": "^1.0.5","@videojs/http-streaming": "^2.4.0","@types/video.js": "^7.3.10",

### What browser(s) including version(s) does this occur with?

Chrome 124.0.6367.78

### What OS(es) and version(s) does this occur with?

Windows 11 / Linux

**Comment by mister-ben** [comment]
h265 can be played where the browser supports it. which isn't universal. See https://caniuse.com/hevc

**Comment by pedro-demeu** [comment]
> h265 pode ser reproduzido onde o navegador for compatível. o que não é universal. Veja https://caniuse.com/hevc

![image](https://github.com/videojs/video.js/assets/60648173/daa14298-bb4a-4e6e-9239-f13c1ec7ec84)

According to the website, Chrome in version 124 was supposed to work, but I still get black screens when trying to play these videos in this format.

**Comment by JinNgVN** [comment]
Hi @pedro-demeu , I can normally play the video in your link, which is weird. The reason is that i already tested hevc with hls format on my computer using videojs and it didnt work (the videos are stored in cloudflare R2). I am using microsoft edge - win 10. Why can i play your videos but not mine? is it because of the mpeg-dash vs hls?

**Comment by JinNgVN** [comment]
Hi @pedro-demeu , may i ask why do you need hevc with hls while you already have it with dash (your video can be played on my machine, maybe just need a bit configuration then you can also play it too).
May i also ask how do you generate that type of video? I try on my own using ffmpeg but it doesnt work. I first convert the h264 video to h265 video, then use the result to convert to dash (all using ffmpeg). It doesnt work but when i take your url and put in my videojs, it can be played normally.
