### ISSUE TITLE
electron Enable hardware acceleration suppression，Play HEVC265 video，Black screen

### ISSUE THREAD

**Issue by dengxueru** [videojs/video.js#8713]
### Description

1、Enable in Electron     // app.disableHardwareAcceleration()
2、Play HEVC265 video，Black screen

### Reduced test case

This requires the Electron environment

### Steps to reproduce

1.Enable and disable hardware acceleration in the Electron environment   // app.disableHardwareAcceleration()
2.play video， black screen

### Errors

nothing

### What version of Video.js are you using?

18.12.1

### Video.js plugins used.

8.10.0

### What browser(s) including version(s) does this occur with?

Chrome/110.0.5481.208 Electron/23.3.13

### What OS(es) and version(s) does this occur with?

window10

**Comment by mister-ben** [comment]
No browser has a software decoder for h265, they can only play it in hardware. Disabling hardware acceleration makes playback impossible.
