### ISSUE TITLE
Use HLS， We got some variable errors

### ISSUE THREAD

**Issue by SolitaryMist** [videojs/video.js#8715]
### Description

Hi~ I got some problems when i used videojs in ReactApp!

**My package.json file**
-
```
"video.js": "^8.6.1",
```

**My video react component code:**
-
```
const Video = forwardRef((props: Props, ref) => {
  const {
    src,
    hlsSrc,
    poster,
    onMouseOver,
    onMouseOut,
    controls = true,
    autoplay = false,
    watermaker,
    onEnded,
    pictureInPictureToggle = false,
    fullscreenToggle = false,
    volumePanel = false,
    videoClassName,
    mediaHeightInWorkCard,
  } = props;
  const videoRef = useRef(null);
  useEffect(() => {
    if (!videoRef?.current) return;
    const player = videojs(videoRef?.current, {
      sources: hlsSrc ? [{
        src: hlsSrc,
        type: 'application/x-mpegURL',
      }] : [{ src }],
      ...(hlsSrc ? {
        html5: {
          vhs: {
            overrideNative: true,
            withCredentials: true,
          },
          nativeAudioTracks: false,
          nativeVideoTracks: false,
        },
      } : {}),
      ...(poster ? { poster } : {}),
      controls,
      autoplay,
      preload: 'metadata',
      responsive: true,
      fluid: true,
      muted: true,
      language: 'zh-CN',
      html5: {},
      controlBar: {
        ...(volumePanel
          ? {
            volumePanel: {
              inline: false,
            },
          }
          : {
            volumePanel: false,
          }),
        pictureInPictureToggle,
        fullscreenToggle,
      },
      userActions: {
        doubleClick: false,
      },
    });
    player.on('ended', handleEnded);
    return () => {
      player.dispose();
      player.off('ended', handleEnded);
    };
  }, []);
...
...
...
  return (
    <div data-vjs-player onMouseOver={onMouseOver} onMouseOut={onMouseOut}>
      <video
        ref={videoRef}
        className={classnames('video-js vjs-default-skin', videoClassName)}
      />
    </div>
  );
```
I saw my console contain some errors，here is screenshot。
<img width="1800" alt="image" src="https://github.com/videojs/video.js/assets/22884560/07361714-0ab9-474b-8e32-b4d17221ae88">
<img width="1473" alt="image" src="https://github.com/videojs/video.js/assets/22884560/b744dd85-2200-4500-9530-9e37bfb309fd">

if i delete my hls config，and use normal video source such as .mp4, The error disappeared.

I have no idea, The cause of the error cannot be found.

### Reduced test case

none

### Steps to reproduce

1.use videojs 8.6.1
2.use hls config and .m3u8 video source
3.error will appear

### What version of Video.js are you using?

8.6.1

### Video.js plugins used.

videojs-dynamic-watermark

### What browser(s) including version(s) does this occur with?

124.0.6367.79

### What OS(es) and version(s) does this occur with?

macos

**Comment by mister-ben** [comment]
This `getVariables()` code where the error occurs is not part of Video.js.

**Comment by SolitaryMist** [comment]
> This `getVariables()` code where the error occurs is not part of Video.js.

When I use the .m3u8 video source and enable the type: 'application/x-mpegURL' configuration of videojs, an error will be reported.

I'm also very troubled. I couldn't find the `getVariables()` code in the packaged code.

I wonder if it might be a problem caused by the videojs-http-streaming plug-in of videojs.

**Comment by mister-ben** [comment]
It's not in http-streaming either. Part of the reasons it is **imperative** to create a [reduced test case](https://stackoverflow.com/help/minimal-reproducible-example) when opening issues is to isolate where an issue occurs and what combination of factors is relevant. As it is, there is nothing actionable here.

**Comment by SolitaryMist** [comment]
> It's not in http-streaming either. Part of the reasons it is **imperative** to create a [reduced test case](https://stackoverflow.com/help/minimal-reproducible-example) when opening issues is to isolate where an issue occurs and what combination of factors is relevant. As it is, there is nothing actionable here.


I seem to have found the problem. It is indeed not a bug in videojs, but a problem with a certain chrome plugin. I disabled all plugins and found that the problem disappeared. Thank you for helping me answer❤️❤️❤️
