### ISSUE TITLE
Qulaity selector integration issue in react js

### ISSUE THREAD

**Issue by Shreyas-sonu** [videojs/video.js#8730]
### Description

Hi guys, i am a beginner frontend  React developer,
 I am trying to integrate video js in my react App for HLS adaptive bitrate streaming,
 But when I trying to add quality sector menu I am facing issue I am getting error  
![image](https://github.com/videojs/video.js/assets/111351684/980da015-d543-4a26-ae8a-f45dc68dac04)
please help me how to resolve this 

this is my code
import { useEffect, useRef, useState } from "react";
import VideoJS from "./VideoJS";
import "videojs-hls-quality-selector";

const Video = () => {
  const playerRef = useRef(null);
  const [player, setPlayer] = useState(null);
  const videoJsOptions = {
    autoplay: true,
    controls: true,
    responsive: true,
    height: "500px",
    disablePictureInPicture: true,
    enableSmoothSeeking: true,
    experimentalSvgIcons: true,
    playbackRates: [0.5, 0.75, 1, 1.5, 2],
    controlBar: {
      components: {
        qualityMenuButton: {},
      },
      skipButtons: {
        backward: 10,
        forward: 10,
      },
    },
    userActions: {
      hotkeys: true,
    },
    sources: [
      {
        src: "http://192.168.1.139:5000/hls/subject27/video-chunk/video-chunk_master.m3u8",
        type: "application/x-mpegURL",
      },
    ],
  };
  const handlePlayerReady = data => {
    playerRef.current = data;
    setPlayer(data);
  };
  useEffect(() => {
    if (player) {
      player.hlsQualitySelector({ displayCurrentQuality: true });
    }
  }, [player]);
  return (
    <div>
      <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
    </div>
  );
};

export default Video;

### Reduced test case

`

### Steps to reproduce

1.Creating a instance in Video JS
2. installing plugin  "videojs-hls-quality-selector": "^2.0.0"
3. try to add plugin to video player

### Errors

react-dom_client.js?v=be7178ec:16691 Uncaught TypeError: Class constructor _Plugin cannot be invoked without 'new'
    at new HlsQualitySelector2 (videojs-hls-quality-selector.js?v=be7178ec:111:21)
    at _Player.hlsQualitySelector (chunk-R2PXRAPO.js?v=be7178ec:28299:22)
    at Video.jsx:42:14
    at commitHookEffectListMount (react-dom_client.js?v=be7178ec:16936:34)
    at commitPassiveMountOnFiber (react-dom_client.js?v=be7178ec:18184:19)
    at commitPassiveMountEffects_complete (react-dom_client.js?v=be7178ec:18157:17)
    at commitPassiveMountEffects_begin (react-dom_client.js?v=be7178ec:18147:15)
    at commitPassiveMountEffects (react-dom_client.js?v=be7178ec:18137:11)
    at flushPassiveEffectsImpl (react-dom_client.js?v=be7178ec:19518:11)
    at flushPassiveEffects (react-dom_client.js?v=be7178ec:19475:22)

### What version of Video.js are you using?

8.12.0

### Video.js plugins used.

videojs-hls-quality-selector v-2.0.0

### What browser(s) including version(s) does this occur with?

chrome

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by mister-ben** [comment]
`TypeError: Class constructor Plugin cannot be invoked without 'new'` means the plugin class has been transpiled and that won't work, it has to be a native ES6 class.
