### ISSUE TITLE
Poor Video Streaming Support - How to Improve???

### ISSUE THREAD

**Issue by nomaam** [videojs/video.js#8738]
### Description

Video.js seems to have very poor video streaming support when compared to other players, such as VLC. 

Is there any way to improve video streaming support?

For example, the following streams play on VLC, but do not play on Video.js

    http://85.238.112.40:8810/hls_sec/239.33.16.32-.m3u8

    https://vgtrkregion-reg.cdnvideo.ru/vgtrk/ufa/russia1-hd/index.m3u8

    https://news.cgtn.com/resource/live/arabic/cgtn-a.m3u8

    https://news.cgtn.com/resource/live/french/cgtn-f.m3u8

    https://news.cgtn.com/resource/live/russian/cgtn-r.m3u8

    https://sktv-forwarders.7m.pl/get.php?x=CNN_Portugal

    https://live.duhnet.tv/S2/HLS_LIVE/cnnturknp/playlist.m3u8

    http://81.94.196.204/tsstreamer/CurrentTime_SD.ts

    https://edge-ar.rcs-rds.ro/digi24ar/index.m3u8

    https://lnc-estrella.tubi.video/playlist.m3u8

    https://rakuten-euronews-2-fr.samsung.wurl.tv/manifest/playlist.m3u8

    https://raw.githubusercontent.com/ChiSheng9/iptv/master/TV02.m3u8

    https://oan-plus-tcl.amagi.tv/playlist.m3u8

    https://video1.makrodigital.com/rtu/rtu/chunks.m3u8?nimblesessionid=

    http://stream.spilebanon.com:1935/spi/myStream/playlist.m3u8

    https://obs.friendshipchurch.eu/tvn/mystream.m3u8

    http://78.129.193.20/tsstreamer/TVP_SD.ts

    https://6180c994cb835402.mediapackage.eu-west-1.amazonaws.com/out/v1/06e44cd7f7e0445fbd669f279c997fd4/index.mpd

-- Update: so I tested all of these links in hls.js player, as i know desktop players have more power than a browser player, some of the examples i provided do play in hls.js player, but not in videojs player

plays in hls.js but not in videojs

    http://stream.spilebanon.com:1935/spi/myStream/playlist.m3u8

    https://news.cgtn.com/resource/live/arabic/cgtn-a.m3u8

    https://news.cgtn.com/resource/live/french/cgtn-f.m3u8

    https://news.cgtn.com/resource/live/russian/cgtn-r.m3u8

    https://rakuten-euronews-2-fr.samsung.wurl.tv/manifest/playlist.m3u8

### Reduced test case

https://seeURLsAbove

### Steps to reproduce

detailed in description

### Errors

doesn't play streams that have been confirmed to play in another player

### What version of Video.js are you using?

newest

### What browser(s) including version(s) does this occur with?

latest versions of firefox and chrome

### What OS(es) and version(s) does this occur with?

windows

**Comment by nomaam** [comment]
@mister-ben thank you so much for the feedback. This info is super helpful. So I can remove any .ts links or http links. Are there any other formats that you know are common and won't play? 

Also, is there any way to programmicaly check if the stream has a cors policy? The only way I can think of is through a simulated browser, which I would like to avoid as its slow. 

Take care.

**Comment by mister-ben** [comment]
See e.g. https://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl?noredirect=1&lq=1
