### ISSUE TITLE
Why player.volume(val) fires volumechange event?

### ISSUE THREAD

**Issue by morskoyzmey** [videojs/video.js#8744]
Example. Once user changes volume in one player I want to set that volume for all the rest players on the page.
I'm doing this in `volumechange` event, where for each player (except current) I call `p.volume(new_val)`. But each such call fires another `volumechange`  event. So we get the recursion here, which breaks only because there is no event for unchanged value.

That behaviour I barely met in any API I've used before.

Video.js 8.6.1

**Comment by mister-ben** [comment]
> That behaviour I barely met in any API I've used before.

This is the same behaviour of a plain video element. `volumechange` is triggered when you set `<video>.volume` to a new value.
