### ISSUE TITLE
The player does not support m3u8 videos in H265 format

### ISSUE THREAD

**Issue by wjm1996** [videojs/video.js#8749]
### Description

Videos in H264 format can be played, but videos in H265 format are not supported.

### Reduced test case

nothing

### Steps to reproduce

```<template>
  <div>
    <video id="my-player" ref="videoRef" class="my-video" autoplay controls muted></video>
  </div>
</template>
<script setup lang="ts">
import "video.js/dist/video-js.css";
import Videojs, { VideoJsPlayer, VideoJsPlayerOptions } from "video.js";

const props = defineProps<{
  url: string;
  options: VideoJsPlayerOptions;
}>();

let myPlayer: VideoJsPlayer;
const videoRef = ref();
const setUrl = (url?: string) => {
  if (url) {
    myPlayer?.src([
      {
        src: url
      }
    ]);
  }
};

onMounted(() => {
  myPlayer = Videojs("my-player", { autoplay: true });
  setUrl(props.url);
});

onBeforeUnmount(() => {
  myPlayer?.dispose();
});

watch(
  () => props.url,
  v => {
    setUrl(v);
  }
);
</script>
<style lang="scss" scoped>
.my-video {
  width: 100%;
  height: 100%;
}
</style>
```

### Errors

video__js.js?v=55800458:10505 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists.

### What version of Video.js are you using?

8.12.0

### What browser(s) including version(s) does this occur with?

125.0.6422.112

### What OS(es) and version(s) does this occur with?

windows 11

**Comment by gkatsev** [comment]
h265 is only fully supported in Safari. In other browsers, specifically chromium based ones, it depends on hardware support (and on Windows potentially also requires the h265 add-on). This isn't something that we can handle if the browser is missing support.
