### ISSUE TITLE
It works for adding other custom headers but not working for overwriting the 'User-Agent' request header. Can you please refer to some information about it.

### ISSUE THREAD

**Issue by rishbitsnbytes** [videojs/video.js#8756]
I'm not really sure where you got `videojs.Hls.xhr.headers`, but the `videojs.Hls.xhr.beforeRequest` should work according to the [docs](https://github.com/videojs/http-streaming#hlsxhr). I've tested it locally, and it seems to be working.

```
videojs.Hls.xhr.beforeRequest = function(options) {
  options.headers = {
    foo: 5
  };
  return options;
};

var player = videojs('video-player-id');
player.src(...);
```

It's possible you may need to reload the source or only set it after `videojs.Hls.xhr.beforeRequest` is set.

_Originally posted by @gkatsev in https://github.com/videojs/video.js/issues/5724#issuecomment-459363403_

**Comment by rishbitsnbytes** [comment]
Hey @gkatsev 
`videojs.Hls.xhr.beforeRequest` works for adding other custom headers but not working for overwriting the 'User-Agent' request header. Can you please refer to some information about it.

**Comment by mister-ben** [comment]
It's not possible to change the user-agent header. Browsers don't allow it to be modified by client side javascript, only by extensions.

**Comment by rishbitsnbytes** [comment]
Hey @mister-ben thank you very much for a quick response.
And yes I checked various places, some say it can't be changed at all and then other places even like official MDN docs says it can be changed now.

Pls have a quick look at this below highlighted text "Note" and kindly reply with your thoughts on this.

**Comment by gkatsev** [comment]
Yeah, apparently it should be allowed now, but it seems like Chrome didn't make the change, though Firefox seems to have (not sure about Safari). So, if you care about Chrome, you can't do it this way. Maybe Chrome lets you modify the user agent via a service worker?

**Comment by mister-ben** [comment]
TIL. You can change it on Safari and Firefox, but not Chrome or Edge. (Latest versions on Sonoma).

**Comment by gkatsev** [comment]
So, yeah, I think this can be closed as a browser bug. https://issues.chromium.org/issues/40450316 linked from mdn.
If beforeRequest is working for you to add headers, it should work the same for user agent for the browsers that support it, i.e. not chromium based ones.

**Comment by rishbitsnbytes** [comment]
Thank you for your quick responses guys.
You have already concluded it with browser bug. And I tested it on Chrome, Firefox and Safari.
It was working only in Firefox.

**Comment by gkatsev** [comment]
The usage of `.Hls` has bees deprecated for a while and as of v8, only .Vhs is available.
