### ISSUE TITLE
AudioTrackKind misalignment re description(s)

### ISSUE THREAD

**Issue by david-hm-morgan** [videojs/video.js#8769]
https://github.com/videojs/video.js/blob/6b468dd2a959ebcb1a2540fb08128ae4f52b01b0/src/js/control-bar/audio-track-controls/audio-track-menu-item.js#L54

This should be plural `descriptions` in order to align with 
```js
export const AudioTrackKind = {
  'alternative': 'alternative',
  'descriptions': 'descriptions',
  'main': 'main',
  'main-desc': 'main-desc',
  'translation': 'translation',
  'commentary': 'commentary'
};
```
https://github.com/videojs/video.js/blob/6b468dd2a959ebcb1a2540fb08128ae4f52b01b0/src/js/tracks/track-enums.js#L28C1-L35C3

**Comment by AdityaGupta-cyber** [comment]
Hello, 
If the issue still persists, then I would like to work on this open issue.

**Comment by david-hm-morgan** [comment]
> Hello, If the issue still persists, then I would like to work on this open issue.

Hi @AdityaGupta-cyber I've already proposed a PR #8770

**Comment by AdityaGupta-cyber** [comment]
Hi @david-hm-morgan  I would love to connect and learn more about how do you plan to close this issue and work on the bug, I have already connected with you on twitter(now X). Please let me know.
