### ISSUE TITLE
Still facing issue with progress bar not completing 100%

### ISSUE THREAD

**Issue by SagarBansal21** [videojs/video.js#8782]
### Description

Version : 8.15.0

![error](https://github.com/videojs/video.js/assets/69359079/88b7fdbb-12a9-4218-aded-d9e50741497d)

### Reduced test case

https://devgrapeseedmaterial.blob.core.windows.net/gl-content-audio/GSv4-U12-CM-Hear.mp3?sv=2021-10-04&st=2024-07-01T06%3A43%3A38Z&se=2024-07-31T06%3A43%3A00Z&sr=b&sp=r&sig=b2kQYvpVm4Nx%2B2Yg2G0wuNi1vIAdA%2FJWXUsBqBrnhrQ%3D

### Steps to reproduce

1. Copy the streaming URL into the player
2. Play the audio
3. You will see that sometimes the progress bar does not fill 100%

### What version of Video.js are you using?

8.15.0

### What browser(s) including version(s) does this occur with?

Chrome Version 126.0.6478.127

### What OS(es) and version(s) does this occur with?

Windows 11

**Comment by SagarBansal21** [comment]
Link to codepen -
https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0

**Comment by mister-ben** [comment]
`this.requestNamedAnimationFrame` [here](https://github.com/videojs/video.js/blob/f701102fe9248f4afb1ca697b9efc63a2d3517f5/src/js/slider/slider.js#L259-L265) is acting as a throttle

**Comment by SagarBansal21** [comment]
@mister-ben , I dont understand correctly. What should be done to fix this?

**Comment by akhileshverma92** [comment]
Here are some general troubleshooting actions you might take to resolve a video progress bar issue in the interim.js:

1. Check for Errors .  Check for JavaScript errors in the browser console; they may offer you some idea of what's wrong.
   
2. Update video.js . Verify that the version of video.js you are using is the most recent. Updates occasionally include bug fixes.

3. Initialization: Check to see if your React component is properly initialising the video.js player.

4 . Progress Event: Verify that the progress event is managed appropriately. To make sure that the progress events are triggered as anticipated, you can add event listeners.

5 . Network Problems: Verify that there are no network problems preventing the video file from loading properly. If there are issues loading the video file, the progress metre may occasionally not update.

6 . Custom Styles/Plugins: Verify that any custom styles or plugins you're employing aren't obstructing the progress bar's operation.

To enable me to offer you more tailored guidance, kindly include further information or the pertinent code snippet.

**Comment by SagarBansal21** [comment]
@akhileshverma92 , even I got the same reply from chat gpt. So let's not proceed with general instructions and try to find a solution if possible.
