### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ( and  Uncaught ReferenceError: videojs is not defined in chrome v 53

### ISSUE THREAD

**Issue by shivTravelxp** [videojs/video.js#8783]
### Description

I am working on WebOS LGTV application which using chrome 53 v, I am facing an issue with latest videojs version 8+ but it working fine with videojs version 7+

working fine with below script in chrome version 53
`<script src="https://vjs.zencdn.net/7.21.1/video.min.js"></script>`

getting Uncaught ReferenceError: videojs is not defined error with below given script
![image (6)](https://github.com/videojs/video.js/assets/138012484/704d15b2-4d56-42e5-9637-2cc67b4dc9a6)

`<script src="https://vjs.zencdn.net/8.12.0/video.min.js"></script>`

### Reduced test case

NA

### Steps to reproduce

1.chrome v 53
2.
3.

### Errors

Uncaught SyntaxError: Unexpected token ( 
Uncaught ReferenceError: videojs is not defined in chrome v 53

### What version of Video.js are you using?

8.12.0

### Video.js plugins used.

<script src="https://vjs.zencdn.net/8.12.0/video.min.js"></script>

### What browser(s) including version(s) does this occur with?

chrome 53

### What OS(es) and version(s) does this occur with?

webOS and version-1.2.8

**Comment by mister-ben** [comment]
Chrome 53 has a problem with the minified version, although it's not obvious to me why. The non-minified works.
