### ISSUE TITLE
TransientButton: WARN: removeClass was called with an element that doesn't exist

### ISSUE THREAD

**Issue by phloxic** [videojs/video.js#8795]
### Description

Expected: player does not try to removeClass after disposal of the TransientButton.
What happens: after disposing the TransientButton, the player still tries to removeClass when you toggle controlbar visibility by hovering.

### Reduced test case

https://deploy-preview-8629--videojs-preview.netlify.app/sandbox/transient-button.html

### Steps to reproduce

1. Go to [demo page](https://deploy-preview-8629--videojs-preview.netlify.app/sandbox/transient-button.html), open console
2. Start playback
3. Click transient unmute button
4. Check `removeClass was called with an element that doesn't exist` warning in console, when controlbar visibility (user activity) is toggled.

### Errors

No errors. Just the aforementioned warning.

### What version of Video.js are you using?

v8.17.0

### Video.js plugins used.

none

### What browser(s) including version(s) does this occur with?

presumably in all browsers

### What OS(es) and version(s) does this occur with?

presumably in all OSes

**Comment by mister-ben** [comment]
Thanks for keep us honest. Fix incoming.
