### ISSUE TITLE
enableDocumentPictureInPicture doesn't appear to be working as expected as an inline option

### ISSUE THREAD

**Issue by spurin** [videojs/video.js#8798]
### Description

Hi there,

Firstly, thanks on the amazing efforts of video.js, appreciate all that you do with this amazing project!

I wanted to mimic the video player implementation as seen on the videojs.com website and had challenges getting a working implementation with enableDocumentPictureInPicture.

Please excuse if I'm off target on this, I'm not sure if this is one or more of 

a) a bug, b) user error or c) an opportunity to improve the documentation.

I was expecting to be able to pass enableDocumentPictureInPicture as an inline option, much like you would controls or other options, however, I was only able to get this working as a data-setup parameter.

Please see the following short example. Option 1, works as expected when activating pip, whereas Option 2 does not -

```
<link href="https://vjs.zencdn.net/8.16.1/video-js.css" rel="stylesheet" />
<link href="https://unpkg.com/@videojs/themes@1/dist/fantasy/index.css" rel="stylesheet" />

<video id="1" class="video-js vjs-theme-fantasy" controls preload="auto" data-setup='{ "enableDocumentPictureInPicture": true }'>
  <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4" />
</video>

<video id="2" class="video-js vjs-theme-fantasy" controls preload="auto" data-setup='{}' enableDocumentPictureInPicture="true">
  <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4" />
</video>

<script src="https://vjs.zencdn.net/8.16.1/video.min.js"></script>
```

Many Thanks!

- James Spurin

### Reduced test case

https://codepen.io/James-Spurin/pen/MWMwmbo

### Steps to reproduce

Run the code above or as per the codepen example.

### Errors

No Error

### What version of Video.js are you using?

8.16.1 - I matched the version from the videojs.com website

### Video.js plugins used.

None

### What browser(s) including version(s) does this occur with?

Chrome 126.0.6478.127

### What OS(es) and version(s) does this occur with?

Mac OS X

**Comment by spurin** [comment]
Further update on this, the example may need to be run locally. The new pip functionality doesn't appear to work from codepen.

**Comment by mister-ben** [comment]
It's not intended to work as an attribute. Either use `data-setup`, or if initialising the player with `videojs()`, pass as an option there. e.g. `videojs('myvideo', {enableDocumentPictureInPicture: true})`.

The only Video.js options that can be set as attributes are those that are also standard html video attributes.

**Comment by spurin** [comment]
Thanks @mister-ben 

Appreciate your feedback, will close the issue. Others can potentially find this in the issues search if needed 👍

**Comment by mister-ben** [comment]
If there is documentation that implies it would work that way, or maybe doesn't call out explicitly that it doesn't, please let us know - or a PR with an update would also be welcome.
