### ISSUE TITLE
[Performance] Keep moving progress bar seeker causes player stuck

### ISSUE THREAD

**Issue by ritingliudd01** [videojs/video.js#8804]
### Description

When you keep dragging seeker on progress bar left and right for few seconds at https://videojs.com/advanced/?video=disneys-oceans, the player looks stuck. Checking developer tool you will find tens of requests sent in Safari of iPad Pro. It will revive until the last request returns response.

Some servers will cancel the repeated requests from the same URL with a series of corrupted .m3u8 files returned. If the browser is unable to ignore those responses and still send them to `<video />` to handle, this issue will happen https://github.com/videojs/video.js/issues/8561

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/8b2c5fcc-a1d5-45a6-8dfa-e0585ee40d4b">

### Reduced test case

https://videojs.com/advanced/?video=disneys-oceans

### Steps to reproduce

1. In Safari of iPad, go to https://videojs.com/advanced/?video=disneys-oceans;
2. Play the default video and keep dragging the seeker on progress bar for few seconds;
3. The video keeps loading and the player looks stuck.

### What version of Video.js are you using?

The version used at https://videojs.com/advanced/?video=disneys-oceans

### What browser(s) including version(s) does this occur with?

Safari on iPad Pro (12.9-inch) 6th generation

### What OS(es) and version(s) does this occur with?

iOS 16.2

**Comment by ritingliudd01** [comment]
### Suggestion
- There should be a `debounce` to avoid sending request every pixel moved. Send only once when dragging seeker stops;
- Handle the error raised from `<video>`. If the error is caused by a corrupted return, ignore it.

Thanks 🙏

**Comment by mister-ben** [comment]
There'a a balance to be struck. Some people are very certain that seeking **should** occur as the slider is moved with immediate feedback.

**Comment by ritingliudd01** [comment]
> There'a a balance to be struck. Some people are very certain that seeking **should** occur as the slider is moved with immediate feedback.

Got it. Thanks 🙏
