### ISSUE TITLE
Captions Settings menu buttons don't work on mobile.

### ISSUE THREAD

**Issue by rn4j1m1** [videojs/video.js#8808]
### Description

Hi
Captions Settings menu Buttons (reset and done) don't work on mobile.

### Reduced test case

https://v8-16-1--videojs-preview.netlify.app/

### Steps to reproduce

I test With chrome on android phone

### What version of Video.js are you using?

8.16.1

### What browser(s) including version(s) does this occur with?

Chrome 126

### What OS(es) and version(s) does this occur with?

Android 11

**Comment by rn4j1m1** [comment]
![image](https://github.com/user-attachments/assets/f7e2a602-c138-4f77-91b1-2fffd60191f0)

**Comment by rn4j1m1** [comment]
thanks
This issue has been solved by :
https://github.com/videojs/video.js/pull/8809

**Comment by mister-ben** [comment]
Thanks for reporting!
