### ISSUE TITLE
Switching between sources with diffrenet technologies causes problem

### ISSUE THREAD

**Issue by ahmadazimi** [videojs/video.js#882]
In my case this is the techOrder:

```javascript
techOrder : ['html5', 'flash']
```

everything works fine while I'm using file types which are supported by Html5 tech, however as soon as I pass on a file type which is not supported by html5 and it requires  the tech to be switched to Flash everything start acting weird for example the play progress bar doesn't work anymore or the currrentTime always stays on zero.

My best guess here is that Flash player couldn't trigger events anymore.

**Comment by mmcc** [comment]
Pretty sure this is closed by #2125, but if not ping this thread and we'll reopen.
