### ISSUE TITLE
Most urgent: VideoJS IMA SDK content not pausing on Android Chrome browser i.e. Content and preroll ad both playing same time

### ISSUE THREAD

**Issue by sunilitgd** [videojs/video.js#8823]
Hi Team, 
Can you please help me to solve the issue of VideoJS IMA SDK? I am facing issues of content and pre roll ads both playing at the same time on Android Chrome browser and it is working fine on windows desktop. Please find below player link and screen recording of android chrome browser - chrome://inspect/#devices

https://instore-tosshub-com.s3.amazonaws.com/sites/player/test-dev/VIDEOJS_4-0_TEST/test/v4_raw/index-php-it_raw.html
 db.vidContrib = videojs(String(db.vpmed.id), objParams);
                initAds();

Screen recording of the error - 
https://instore-tosshub-com.s3.amazonaws.com/sites/player/test-dev/VIDEOJS_4-0_TEST/test/videojs_imasdk_android_issue.mp4

IMA SDK loading ads on videojs player ready but giving error highlighted in below screenshot. 
 db.vidContrib.ready(function() {
                     console.log("");console.log("");
                     initAds();
https://instore-tosshub-com.s3.amazonaws.com/sites/player/test-dev/VIDEOJS_4-0_TEST/test/v4_raw_ready/index-php-it_raw.html?debug=1

image.png

Also as advised in the documents  (https://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html) I am not able to init player.ads(); 
<video id="video" src="movie.mp4" controls></video>
<script src="video.js"></script>
<script src="videojs.ads.js"></script>
<script>
videojs('video', {}, function() {
  var player = this;
  player.ads(); // initialize videojs-contrib-ads As given in the documents it is not initializing and giving error
  // your custom ad plugin code
});
</script>
Also there are two files given in the URL-  https://cdnjs.com/libraries/videojs-contrib-ads 
1) https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-ads/7.5.2/videojs.ads.min.js
2) https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-ads/7.5.2/videojs-contrib-ads.min.js
Do I need to include both files or only one file? When I checked on diff checker both files had the same content. 

Please help me with this.

**Comment by mister-ben** [comment]
The maintainers of videojs-ima don't monitor here. Please log issues for videojs-ima on that repo instead: https://github.com/googleads/videojs-ima/issues

As already answered in Slack:
* As you are using videojs-ima, do not try to init `player.ads()`. If you are using videojs-ima, videojs-ima is the integrator of contrib ads, and it will take care of initialising `ads()` with the options it needs, when it needs it.
* The duplicate names exist for backwards compatibility. The script was renamed at one point. Do not include both.
