### ISSUE TITLE
Incorrect Language Labels in Audio and Text Tracks on Safari iOS

### ISSUE THREAD

**Issue by renatosalopes** [videojs/video.js#8824]
When watching a video with multiple languages, the player correctly identifies and classifies the available languages in the audio and subtitle menus. For example, on desktop (Edge), it correctly shows the available languages as “pt” and “en”. However, on Safari iOS, the labels appear differently, showing “stream_0”, “stream_1”, etc., as seen in the attached image. Sometimes the correct language appears in parentheses. Is there a way to “force” the labels to appear simply and clearly as “pt” and “en”?

Version: videojs v8.6.1;
Plugins: videojs-contrib-ads, videojs-contrib-eme, videojs-event-tracking, videojs-mobile-ui, videojs-zoom;
Browser: Safari (multiple);
OS: iOS (multiple);

![IMG_20240801_164042030](https://github.com/user-attachments/assets/de93d968-ac01-4726-aa11-6b0fd7c95b42)
![Screenshot_20240729_163745_WhatsApp_1](https://github.com/user-attachments/assets/449400c8-2dc1-4156-89ca-9f098b902e8d)

**Comment by mister-ben** [comment]
Is this with in-manifest tracks or remote webvtt tracks? Do you have an example? iOS Safari is handling the tracks natively and you won't be able to override the native UI, so you'll probably need to fix this in the manifest.

**Comment by renatosalopes** [comment]
Hi Ben,

Thanks for your response. The application uses local files only. Indeed, those strings were coming from the manifest, where each item was correctly identified with the language, but their names were like stream_x. What puzzled me was that other browsers captured the correct language value, but Safari did not. I will try to fix this.

Thanks!
