### ISSUE TITLE
Fix `latest` tag version

### ISSUE THREAD

**Issue by rtritto** [videojs/video.js#8863]
`next` tag is used as _latest_ and it should be used only for major versions.
`latest` tag isn't updated with latest version that is assigned to `next` tag.

## Current
latest: 8.17.3
next: 8.17.4

## Expected
latest: 8.17.4
next: 8.17.4 (v8 not updated) OR 9.x.y

---

Related: [.github/workflows/release.yml](https://github.com/videojs/video.js/blob/v8.18.0/.github/workflows/release.yml)

**Comment by mister-ben** [comment]
Our versions have `next` when first published to npm. They are usually tagged as `latest` after about two weeks, unless we decide to skip it - for example if an issue is discovered that's fixed in the next release.
