### ISSUE TITLE
No poster image on mobile

### ISSUE THREAD

**Issue by kvendrik** [videojs/video.js#889]
**The issue**
I'm currently browser testing a website on which I use video.js and noticed that the image poster does not show up on android and iOS and instead shows the default os player.

**HTML**
                        &lt;video id="video-player" class="video-js vjs-default-skin vjs-big-play-right-top"
                          controls preload="auto" poster="assets/img/nickbijvoetpitch.png" width="auto" height="auto" data-setup='{}'&gt;
                             &lt;source src="assets/video/nickbijvoetpitch.mp4" type='video/mp4' /&gt;
                             &lt;source src="assets/video/nickbijvoetpitch.webm" type='video/webm' /&gt;
                             &lt;source src="assets/video/nickbijvoetpitch.ogv" type='video/ogg' /&gt;
                        &lt;/video&gt;

**JS**
videojs.options.flash.swf = 'js/libs/video-js/video-js.swf';

Any ideas?

**Comment by msnpr567** [comment]
Im facing serious issue with poster image in all browsers. how can i get 100% width with small image. My poster and video width should same.. can any one help, thanks in advance

**Comment by heff** [comment]
@msnpr567 it's hard to help without a live example of the issue. Could you put together a jsbin or something to help?
http://jsbin.com/axedog/edit?html,js,output

**Comment by msnpr567** [comment]
In your example jsbin. dont fix height , just place a small image as poster , can u observe the effect of loading video. first poster is taking 100% width , after its converted into video width.In mobile view its not good.

i will post complete code pls observe

Please find code in http://plnkr.co/edit/?p=templates&s=z8rv62B6vPcFmtQK

**Comment by mmcc** [comment]
Everything about your example looks normal, so I think this is a misunderstanding as to what the expected behavior is. The poster is resized to be as big as it can while still fitting into the dimensions of the player (`background-size: contain`). So since this image is relatively square, most (normal) video aspect ratios are going to mean that this poster will fill 100% height, then be as wide as it can while maintaining it's own aspect ratio.

**Comment by msnpr567** [comment]
I want to load poster with video aspect ratio.dont want that disturbance . can you please give fix for this..

**Comment by ramezrafla** [comment]
Here is what worked for us on iPhone (using jQuery)
We add videojs through string into the DOM

	// iPhone bug to show controls
	if (!showControls) $('#player').attr('poster',poster);

**Comment by andfinally** [comment]
Unfortunately setting the poster attribute (on both the video element and the div VideoJS uses on desktop) like in @yzapuchlak's solution didn't do the trick for me. It seems there is a general issue with iOS not showing poster images.

**Comment by sobytes** [comment]
i am getting this error and after changing the user agent to iPhone in safari i was able to debug, if i check the css it has this class for native controls.

~~~
.vjs-controls-disabled .vjs-poster, .vjs-using-native-controls .vjs-poster {
     display: none;
}
~~~

So i can use jQuery or even css to apply a fix. But when the video is played the poster still remains and does hide?

~~~
$(".vjs-poster").css("display", "block");
~~~
