### ISSUE TITLE
Android 2.2 and 2.3 support

### ISSUE THREAD

**Issue by kvendrik** [videojs/video.js#890]
**The issue**
Next to the issue of the poster not showing up on android and iOS about which I posted an issue [here](https://github.com/videojs/video.js/issues/889), I detected two other issues on android 2.2 and 2.3.

**Android 2.3**
I am currently browser testing a website on which I use video.js and can't seem get it to play on Android 2.3. Instead I get a "Sorry, this video cannot be played" error. Any ideas on this? What file does android use for playing the video? Maybe something with the codec?

**Android 2.2**
Android 2.2 doesn't seem to support video.js at all and insetad shows a fallback image. I was wondering if it would be possible to detect if video.js is supported in the current browser or not so I can show a different player like vimeo instead when it's not.

Any ideas on this?

**Comment by gkatsev** [comment]
Going to close this as a Wont Fix, if it's even an issue anymore. The global market share for android 2.3 is really low ([less than 4%](http://developer.android.com/about/dashboards/index.html)) and it's a really old platform with a lot of bugs. We're unlikely to make changes to specifically support it in videojs 5.0. Though, we could be convinced to make a patch for the 4.x version.
