### ISSUE TITLE
React 18 StrictMode does not work with typical usage of video.js

### ISSUE THREAD

**Issue by NikhilVideostori** [videojs/video.js#8902]
### Description

video.js is not working in strict mode, when removed from my index.js file it is working fine but i can't push my code without strict mode. has anyone found any solution to it??

### Reduced test case

https://codepen.io/gkatsev/pen/GwZegv?editors=1000

### Steps to reproduce

video.js is working fine if i do not include my <App/> component in strict mode but if do it with strict mode it is not working. video just pops up for a split second and then nothing on the browser.

### What version of Video.js are you using?

8.18.1

### What browser(s) including version(s) does this occur with?

chrome

### What OS(es) and version(s) does this occur with?

windows11

**Comment by mister-ben** [comment]
I believe [this example]](https://videojs.com/guides/react/#react-functional-component-and-useeffect-example) caters for strict mode's unmount and remount.

Alternatively, the [`resoreEl`](https://videojs.com/guides/options/#restoreel) option was added in 7.20.0 for use cases where you need the original element to be restored when the player is disposed.
