### ISSUE TITLE
ios iphone could not play, about .mpd, other Android and ipad（ios，Android）can play

### ISSUE THREAD

**Issue by sitaoi** [videojs/video.js#8931]
![Image](https://github.com/user-attachments/assets/73fc1e09-ae0f-40ff-a7fe-2a1107d64d03)

**Comment by mister-ben** [comment]
DASH can only be played with Media Source Extentions, which are not available on iPhone, or with Managed Media Source Extensions, which iPhone does support and we have *experimental* support for. You can opt into using that, and feedback would be welcome. Make sure you're on the newest version of Video.js (currently 8.21.1).

```
var player = videojs('playerId', {
  html5: {
    vhs: {
      experimentalUseMMS: true,
      overrideNative: true
    }
  }
});
```

https://github.com/videojs/http-streaming?tab=readme-ov-file#experimentalusemms

**Comment by sitaoi** [comment]
but report
code: 3, message: 'Playback cannot continue. No available working or supported playlists.'
