### ISSUE TITLE
videojs.log.history is empty on iphone ios

### ISSUE THREAD

**Issue by RodionPushkin** [videojs/video.js#8935]
videojs.log.history is empty on iphone ios, i have a same bug on other versions of package, 6.x.x, 7.x.x, 8.x.x., work with a hls player, and i need to access to the log history, but only on iphone i have a empty array when use console.log(videojs.log.history()) ![Image](https://github.com/user-attachments/assets/23e6262d-9841-4778-926d-520544d67da4)

waiting for your response about this problem, also in iphone i got bug with player.on("error"....., videojs cant handle errors, i dont know why, thats only problem in iphone, i have tested this in browserstack on iphone 15 safari and chrome browsers, and have tested it on my own iphone, also i have tested this on mac and windows on browserstack and all is good, no issues, and i tested it on my work mac and windows computer, and take the same result, problems only on iphone

**Comment by RodionPushkin** [comment]
my code on react
videojsPlayerRef.current = videojs(videojsRef.current, {
      autoplay: true,
      controls: true,
      preload: "auto",
      sources: [
        {
          src: "...",
          type: "application/x-mpegURL",
          withCredentials: false,
        },
        {
          src: "...",
          type: "application/x-mpegURL",
          withCredentials: false,
        },
        {
          src: "...",
          type: "application/x-mpegURL",
          withCredentials: false,
        },
      ],
      controlBar: {
        playToggle: true,
        volumePanel: true,
        currentTimeDisplay: true,
        timeDivider: true,
        durationDisplay: true,
        progressControl: true, 
        fullscreenToggle: true, 
      },
      playsinline: true,
      html5: {
        nativeTextTracks: false,
        nativeAudioTracks: false,
        nativeVideoTracks: false,
        nativeControlsForTouch: false, 
        overrideNative: true,
        hls: {
          overrideNative: true,
          enableLowInitialPlaylist: true,
          limitRenditionByPlayerDimensions: false,
          smoothQualityChange: true,
          useDevicePixelRatio: false,
          withCredentials: false,
        },
        vhs: {
          overrideNative: true,
          enableLowInitialPlaylist: true,
          limitRenditionByPlayerDimensions: false,
          smoothQualityChange: true,
          useDevicePixelRatio: false,
          withCredentials: false,
        },
      },
    });
videojsPlayerRef.current.on("error", function () {
      console.log("player error");
    });

    const interval = setInterval(() => {
      console.log(JSON.stringify(videojs.log.history()));
    }, 1000);

      <video
        ref={videojsRef}
        className="video-js vjs-default-skin w-screen"
        webkit-playsinline
        playsInline
        x-webkit-airplay="allow"
        x5-video-player-type="h5"
        x5-video-player-fullscreen="true"
        x5-video-orientation="portraint"
      />

**Comment by RodionPushkin** [comment]
videojs on iphone uses native hls player, and i think this is the reason why i cant access to player.on("error"... and reason why history array is empty, but event player.on("waiting"... works pretty good

**Comment by RodionPushkin** [comment]
in my project we use history() to access to warnings and etc for using that to switch sources to lower resolution when cdn gives broken fragment

**Comment by mister-ben** [comment]
iPhone's native playback won't necessarily trigger errors in the same conditions, nor does it log anything. It's a black box.

Latest iOS on iPhone has support for Managed Media Source Extensions, with which we can play HLS with our VHS playback engine. It's still considered **experimental** - we don't know if we've seen every edge case yet - but you could try it out for your use case as detailed in the comment linked below.

https://github.com/videojs/video.js/issues/8931#issuecomment-2523737856
