### ISSUE TITLE
skipForward doesn't work

### ISSUE THREAD

**Issue by cale23** [videojs/video.js#8938]
### Description

Seems like it just stops the video for a moment, and the video continues.

### Reduced test case

https://stackblitz.com/edit/stackblitz-starters-6cxf2fue?file=index.html

### Steps to reproduce

1. Click on the skip forward button
2. Seems like it just stops the video for a moment, and the video continues

### What version of Video.js are you using?

8.21.0

### What browser(s) including version(s) does this occur with?

Chrome 131.0.6778.139

### What OS(es) and version(s) does this occur with?

MacOS 15.1.1 (24B91)

**Comment by mister-ben** [comment]
It won't work without a configured time to skip. When configured, there is no need to `show()` it.

```js
const videoRef = videojs(document.querySelector('.video-js'), {
  controlBar: { skipButtons: { forward: 10 }}
});
//videoRef.controlBar.skipForward.show();
```

**Comment by cale23** [comment]
@mister-ben thx for the response, the test scenario works.

But I have an issue when configuring the `controlBar`:
<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/529e0fb7-772a-4dd7-adc2-44a92da6f022" />

my config:
```
data() {
    return {
      videoOptions: {
        height: '530',
        autoplay: false,
        controls: true,
        sources: [
          {
            src: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            type: 'video/mp4',
          },
        ],
        playbackRates: [0.5, 1, 1.5, 2],
        controlBar: {
          playbackRateControl: true,
          chaptersButton: true,
          pictureInPictureToggle: false,
          skipButtons: {
            backward: 10,
            forward: 10,
          },
        },
      },
    };
  },
```

my init:
```
mounted() {
    this.player = videojs(this.$refs.videoPlayer, this.options, () => {
      this.player.log('onPlayerReady', this);
    });
},
```

**Comment by cale23** [comment]
When adding:
`language: 'en'`

it works now!

I guessed the default was already 'en', but I was wrong.

Thx again @mister-ben!

**Comment by mister-ben** [comment]
That shouldn't be necessary, language does default to 'en' if not set and not retrievable from `window.navigator`.

https://github.com/videojs/video.js/blob/19ca3f2ebe0ec7f0374fa3bc7df1457f9f185823/src/js/player.js#L5545

What was `player.language()` returning there?

**Comment by cale23** [comment]
When player init, it returns the empty string "". @mister-ben
