### ISSUE TITLE
Vertical Slider Not Working

### ISSUE THREAD

**Issue by nmatthew123** [videojs/video.js#942]
I am trying to make my volumeBar vertical by using this code posted here : https://github.com/videojs/video.js/pull/477
This is how I am setting up my  video player 

``` javascript
var myPlayer = videojs("video-player", {
    'children': {
      'controlBar': {
        'children': {
          'volumeControl': {
            'children': {
              'volumeBar' : {
                vertical: true
              }
            }
          }
        }
      }
    }
});
```

For some reason my video menu bar disappers. Do you have any idea what is going on? I've been working on this for a day and Im not sure what I should do. I haven't worked with videojs before so I'm a complete noob.

**Comment by nothernrace82** [comment]
Perfect solution, Thank you for sharing, mmcc !!!

**Comment by maluklo** [comment]
Evaluate new skin video-js-6.2.4

https://github.com/maluklo/Skin-video-js-6.2.4
