### ISSUE TITLE
Volume bar: diamond displaced  

### ISSUE THREAD

**Issue by h3sands** [videojs/video.js#946]
Layout issue
When the page loads, the diamond in the Volume bar is displaced to the right. Any mouse click over the loudspeaker icon, diamond or the bar, adjust the position

OS X 10.6.8: Safari 5.1.10, FF 26.0, Chrome 32.0.1700.77
Win 7: IE 10.0.9200.16750, FF 25.0.1, Chrome 31.0.1650.63 m

http://jsbin.com/eGAtoCUH/1

**Comment by mmcc** [comment]
I'm going to close this since we're probably not going to make skin updates to 4.x anymore and this isn't an issue in 5.0.
