### ISSUE TITLE
New Feature: Default Styling for RTL languages

### ISSUE THREAD

**Issue by alexlapinski** [videojs/video.js#949]
I am looking for default styling when the 'dir' attribute is present on the HTML element of the containing page, and the value of the 'dir' attribute is RTL.

I am not myself an expert in RTL languages, and designs, but I would imagine that it is a pure flip of the UI (progress bar from right to left, instead of left to right).

**Comment by FREEZX** [comment]
+1

**Comment by mister-ben** [comment]
I don't speak Arabic but was recently in the Middle East and discussed this with some site owners and developers. Their consensus was that users are used to player controls being "ltr", and flipping would be confusing. Muscle memory would play havoc with a progress slider going the "wrong" way. So my vote is to not change the control order / orientation by default. Any plugins creating overlays, menus etc are likely to need to adjust to accommodate rtl langauges though.

**Comment by gkatsev** [comment]
I think we still need some confirmation that we would actually want to do this.

**Comment by azawawi** [comment]
Sorry for the late reply. I think this should be closed.

@mister-ben Yes, you are correct in that regard. I tried reversing them and they are confusing to website users.

**Comment by gkatsev** [comment]
@azawawi thanks. Going to close this.
If someone does want it, making a videojs plugin that reverses the UI would be preferred.
