### ISSUE TITLE
Opening subtitle files on-the-fly

### ISSUE THREAD

**Issue by DannyZB** [videojs/video.js#952]
Right now there is no way in the player to load subtitle files after the video starts playing .. only as part of the player load

I saw some examples online of using textTracks , but the player object has no such attribute !

How is that done ?

Plus - files encoded using ANSI ( for example windows-1255 for hebrew ), even when I set their encoding to windows-1255 in the track tag still appear as a bunch of question marks in an UTF-8 page

**Comment by gkatsev** [comment]
Videojs 4.12 received a huge update to how text tracks work. Based on the comments above, I think that the issues raised here have been addressed (see new API methods and also the fact that we use the browser's native functionality when available).
Going to close this as fixed but please let us know if there are issues.
