### ISSUE TITLE
Callback for when a video has ended?

### ISSUE THREAD

**Issue by binarykitchen** [videojs/video.js#954]
Hello again

Is there a callback for when a video has ended (has reached the end)? And how can I change to another video when that has happened? Dynamically I mean.

Thanks!

**Comment by oleynikd** [comment]
Where can I find the full list of available events? Thanks.

**Comment by wakasann** [comment]
It's work fine,Thanks you very much! If Html5 video have loop attribute or options loop is true ,It's will not working.

**Comment by murnieza** [comment]
I am also looking for full list of existing events.

**Comment by mmcc** [comment]
The [HTML5 media events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events) are going to cover just about every event Video.js will fire.

**Comment by cocoli** [comment]
Nice

**Comment by badguy18** [comment]
Not work on my site [Tubeplayer](http://www.tubeplayer.top/)

**Comment by jasan-s** [comment]
exactly what i was looking for

**Comment by shakyasaijal** [comment]
I have solved this problem by using **timeupdate** event

```
player.on('timeupdate', function(){
      if(player.currentTime() == player.duration()){
          console.log('video is ended');
      }
});
```

**Comment by MuslimAKhan** [comment]
All Events are here:
[VideoJS Events](https://docs.videojs.com/docs/api/player.html#Eventsended)
