### ISSUE TITLE
Create a sensible toJSON for a vjs object.

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#957]
Would be nice if we were able to come up with a sensible output for a toJSON function so that when a user does `JSON.stringify` it doesn't throw on them.

---
Please describe the feature/enhancement (be as detailed as possible when describing the use cases behind it).

Any existing documentation/specs?
Any existing examples?

### To finish
- [x] Tests written  
- [x] Feature implemented  
- [ ] Docs/guides updated  
- [ ] Example created (e.g. [jsbin](http://jsbin.com/axedog/9999/edit))  
- [ ] Pull request submitted

**Comment by heff** [comment]
@gkatsev this one isn't clear yet. Can you talk about what you want this to look like so another person could work on it? I think you originally just said to have it return a string with 'player' or something.

**Comment by EZWrighter** [comment]
Would be nice if you could serialize player state out with this.  Sources, Tracks, poster, control states, current player head position.  Not sure how useful it would be, but it makes sense intuitively.

**Comment by gkatsev** [comment]
Not sure exactly what I had in mind originally but last night when I noticed it, I thought of something like what @EZWrighter said.

**Comment by heff** [comment]
That works for me. Could one of you give some specific definition around it and provide and example, so anyone could jump in and work on it?

**Comment by gkatsev** [comment]
Fixed via #2114
