### ISSUE TITLE
timeout for video controls and keyboard-only users

### ISSUE THREAD

**Issue by gdkraus** [videojs/video.js#969]
We are working on making the player controls more accessible for keyboard-only users and screen reader users and making sure we follow the ARIA design specifications. One of the problems we are running into is that when we are using the keyboard to control the video, the player controls sometimes hide themselves before we have finished completing our action. I see a couple of possible solutions.

1. Extend the timeout for the video controls to hide themselves
2. Extend the timeout for the video controls to hide themselves, but only if it is detected that the user is using the keyboard to interact with the controls
3. Turn off the auto-hide feature of the controls if it is detected that the user is interacting with the controls via keyboard, and then hide the controls once the player loses focus.

Do any of these sound like viable solutions? Do you have any other suggestions?

Thanks.

**Comment by marcobarbosa** [comment]
@gdkraus I'd also be interested to see your fixes and findings. Working on a project now where all the videojs videos must be accessible through keyboard. Do let us know how it went :)

**Comment by mmcc** [comment]
Yeah this would be a nice one to go ahead and tackle ahead of 5.0. Any update? Anything we can do to help?

**Comment by gkatsev** [comment]
When talking with @OwenEdwards recently, this came up as part of Screen Reader support. I think our decision was that we shouldn't specifically do anything to not hide the controls when the player becomes inactive but instead we should make sure that the controls continue working when the player becomes inactive and the buttons should stay focused. We wouldn't want to punish sighted users or Screen Reader users one way or the other.
