### ISSUE TITLE
Mobile support issues and some solutions

### ISSUE THREAD

**Issue by sangatpedas** [videojs/video.js#975]
Hi guys,

I've been focussing on mobile support for videojs on the most popular Android browsers and find the following issues and some solutions. Mainly this is about support for the videojs controls.

First, in Chrome on Android all seems to work as expected.

The most problems occur with the default Android browser on Jelly Bean, ICS seems to be ok. Basically in the current version the controls of the standard browser in Jelly Bean don't work at all. The reason for this is that Browser generates multiple clicks. So for instance when the play button is clicked it calls the process twice, resulting in a play request followed immediately by a pause request, resulting in nothing really happening. The same goes for all other buttons in the control bar.

I'm sure my solutions won't meet the required quality of the project but I give them anyway so they can be used as temporary work-around by others. This is done by editing the dev version.

First I've defined more booleans so I better know what browser I deal with:

```javascript
vjs.IS_FIREFOX = (/Firefox/i).test(vjs.USER_AGENT);
vjs.IS_CHROME = (/Chrome/i).test(vjs.USER_AGENT);
vjs.IS_OPERA = ((/Opera/i).test(vjs.USER_AGENT) || (/OPR/i).test(vjs.USER_AGENT));
if (!vjs.IS_FIREFOX && !vjs.IS_CHROME && !vjs.IS_OPERA) //the safari string is also used in other browsers
vjs.IS_SAFARI = (/Safari/i).test(vjs.USER_AGENT);
```

Next, I define an execution time out based on browser/platform:

```javascript
var execTimeout=0;
if (vjs.TOUCH_ENABLED && vjs.IS_ANDROID && (vjs.IS_SAFARI || vjs.IS_FIREFOX))
var execTimeout=500; //this is the time in ms that allows for a next execution
var isExecuted=false;
```

Now basically all onclick function are rewritten like this:

```javascript
// OnClick - Toggle between play and pause
vjs.PlayToggle.prototype.onClick = function(event){
   if(isExecuted==false || isExecuted==null) {
	isExecuted=true;
	if (this.player_.paused())  {
		this.player_.play();
  	} else {
		this.player_.pause();
  	}
  	setTimeout(function() {isExecuted=false; }, execTimeout);
  }
};
```

On the fullscreen toggle button more changes are required. Since Safari uses native controls in fullscreen mode, any request from the toggle button is always a request for fullscreen. And since returning from fullscreen with native controls doesn't change the values of the button or the var isFullScreen, no need to change them in the first place.

```javascript
vjs.FullscreenToggle.prototype.onClick = function(){
  if(isExecuted==false || isExecuted==null) {
	isExecuted=true;
	if (this.player_.isFullScreen==null) this.player_.isFullScreen=false;
	if ((vjs.TOUCH_ENABLED && vjs.IS_ANDROID && vjs.IS_SAFARI) || !this.player_.isFullScreen) {
		this.player_.play();
    	this.player_.requestFullScreen();
	}
	else if (!this.player_.isFullScreen) {
    	this.player_.requestFullScreen();
    	this.el_.children[0].children[0].innerHTML = 'Non-Fullscreen'; // change the button text to "Non-Fullscreen"		
  	} else {
    	this.player_.cancelFullScreen();
    	this.el_.children[0].children[0].innerHTML = 'Fullscreen'; // change the button to "Fullscreen"
  	}
  	setTimeout(function() {isExecuted=false; }, execTimeout);
  }
};

vjs.MuteToggle.prototype.onClick = function(){
	var _this = this;
	if(isExecuted==false || isExecuted==null) {
		isExecuted=true;
		_this.player_.muted( _this.player_.muted() ? false : true ); 
	}
	setTimeout(function() {isExecuted=false; }, execTimeout);
};
```
As for the volume slider, I don't see much use for it unless one is a midget with extremely small fingers.

Then there's a problem (in my opinion) once a player is paused. Most mobile browser show a play button in the middle but since vjs.MediaTechController.prototype.onTap only triggers user activity. Since Chrome and Opera show a big native play button I made the following changes:

```javascript
vjs.MediaTechController.prototype.onTap = function(){
  this.player().userActive(!this.player().userActive());
     if ((this.player().paused()) && (vjs.IS_CHROME || vjs.IS_OPERA))
      this.player().play() ;
};
```

After having done these changes the following issues remain for Android:

Firefox:
fullscreen doesn't work, remote debugging shows the fullscreen request is ignored due to too many iterations. This corresponds with a test I did with an external button that requests a full change, which works. 

Returning from fullscreen changes zoom mode, player is slightly bigger as if double clicked.

Safari (so the official Safari release on Android)
Any fullscreen requests is ignored and stops the video entirely from playing

Opera
First play always switches to fullscreen
returning from fullscreen the native controls show again, even the boolean is set to false.

Thanks for all the work you guys put in and I hope this helps a bit and obviously I hope you guys can help with some of the remaining issues.

Remco

**Comment by anttimo** [comment]
@mmcc The multiple click issue with video player controls is still reproducible at least with default Android Browser on Samsung Galaxy S3 4.3. Also can be reproduced on Video.js landing page. When using native controls everything works correctly. Based on our Google analytics on one of our sites default Android browser is still as popular as Chrome browser so it would be nice to get this fixed.

**Comment by anttimo** [comment]
I assume double click issue could be also prevented by the ghost click busting method explained in this Google's article https://developers.google.com/mobile/articles/fast_buttons#ghost We actually used that method to stop these double clicks in one webview based app we made.

**Comment by cocomitte** [comment]
I'm also having exactly same issue on Galaxy S3.. Video.js landing page video won't play at all on the S3 and my video player on my page is very intermittent. I get it to play by button mashing. Any single click to play just pauses itself again.

**Comment by NekR** [comment]
I also can confirm that video.js is totally broken on Android 4.3 Default Browser (Galaxy Nexus). I also cannot play video on official site homepage, but I made local version of player and it starts to play (somehow through fullscreen), but video.js controls do not correctly -- always ghost/double click per one touch. It's very surprising for me to see such bug.

**Comment by NekR** [comment]
https://github.com/videojs/video.js/blob/master/src/js/component.js#L1087
This does not works everywhere, especially on Android Stock Browser, so you need to mark that gesture as already processed as a click and do now process real click event.

Quick fix might look like this:
```javascript
this.on('touchstart', function() {
  //...
  this.touchClickProcessed = false;
  this.preventNativeClick = false;
  //...
});

this.on('touchend', function() {
  //...
  if (allConditionsMeetAndLetThisClickHappen) {
     //...
     this.touchClickProcessed = true;
     //...
  } else if (doNotWantSimulatedTouchButAlsoDoNotWantRealClick) {
    this.preventNativeClick = true;
  }
});

this.on('click', function(e) {
  var ignoreClick = this.touchClickProcessed || this.preventNativeClick;

  this.touchClickProcessed = false;
  this.preventNativeClick = false;

  if (ignoreClick) {
    e.preventDefault();
    return;
  }

  //...
});
```

**Comment by craigcarnell** [comment]
On my Samsung Galaxy Tab GT-P5200 I get a black background instead of a video. It plays fine without videojs?

**Comment by sangatpedas** [comment]
I upgraded and then immediately rolled back, many many issues with this version. When using poster image you don't see the video play, just hear the sound. And I had some other issues.

**Comment by mmcc** [comment]
@sangatpedas "And I had some other issues" isn't very helpful at all. Mind expanding on that? Even better, check and see if someone else has reported them, and if not, open a new one. We can't fix things we don't know about!

**Comment by sangatpedas** [comment]
@mmcc Sorry mate but I was testing this in a production environment and as soon as I saw video wasn't showing I rolled back and kinda didn't care so much about the other problems. As far as I can remember the multiple click issue wasn't solved yet as well so I applied (a slightly modified) version of the code I posted initially in this thread. But like I said, at that moment I didn't bother to test a player that doesn't (consistently) show video. Anyway, didn't mean to be negative, me and all others appreciate what you guys are doing. If i have some time later I will do some checks and let you know.

**Comment by mmcc** [comment]
Totally understandable! The core contributors just have a (relatively) limited device-set we can test on locally, so it's really helpful when we can get solid issue reports from the rest of the device world.

**Comment by sangatpedas** [comment]
Hi Matthew,

Here are two things I encountered and our dev team will look into the reasons why it occurs. Here's the demo page of the latest videojs version and when you cut the query in the url it will revert to an older version of videojs. http://lv8.tv/the-salvation-official-us-release-trailer-1-2015-mads-mikkelsen-eva-green-movie-hd-12x6ony0l5cy.html?v=4.11.4

The older version works fine, the new version has some (major) issues but I suspect it might also be in our css or in one of the plugins.

1. When played in Chrome on Android KitKat the poster doesn't disappear so you don't see the video play but you hear the sound.

2. The resolution selector doesn't popup on mouse over anymore and basically can't function anymore. It opens on click but will disappear the moment the mouse leaves the button.

I don't see these problems on the videojs site so I guess css and plugins that worked with older versions are not compatible anymore with the latest version.

As said, we're looking into the cause and will update you later.

**Comment by sangatpedas** [comment]
Hi Matthew,

An update from my side after testing V4.11.4:

1. The problem described in this thread, a click generating multiple events, seems to be solved, also on older versions of Android.

2. The problem with the poster might have come from a plugin as it doesn't occur when we test a version without any plugins. We easily solved it with:
.video-js.vjs-android .vjs-poster { display: none; }

3. The problem with the menu might be a bug as we had to override the mouse over event:
$(document).ready(function(){
    $('.vjs-res-button.vjs-menu-button.vjs-control').on('mouseenter', function(){
        $('.vjs-menu').last().show();
    });
    $('.vjs-res-button.vjs-menu-button.vjs-control').on('mouseleave', function(){
        $('.vjs-menu').last().hide();
    });
});

So in my opinion this thread can be closed as the problems originally reported now have been solved.

Thanks!

**Comment by endrjuskr** [comment]
I tried to open http://lv8.tv/the-salvation-official-us-release-trailer-1-2015-mads-mikkelsen-eva-green-movie-hd-12x6ony0l5cy.html?v=4.11.4 provided above in WebView on Android 4.1.2 and video didn't load at all.

Here is how it looks:

![error](https://cloud.githubusercontent.com/assets/2611549/6867051/60c14348-d47e-11e4-8dc4-fe8923ff5384.png)


Do you have any idea, how to solve it?

**Comment by carpasse** [comment]
Hi guys

I have tested our video player on Android 4.3 default browser on a Galaxy nexus and a Galaxy s3 and the onClick function still gets called several times. It is no longer the same event type but now, 'tab' and 'click, events get raised one after the other. We have done our tests against version 4.11.4 and  4.12.5 of videoJs.

The only solution I could find was to debounce the the calls to onclick

I have done a plugin to fix this issue (es5 forEach polyfill required) 
```
// This plugin fix the multiple click issue existing on android default browsers
// For more info please refer to https://github.com/videojs/video.js/issues/975

vjs.plugin('multiple-clicks-fix', function mobile(opts) {
  var player = this;

  player.ready(function () {
    walkChildrenTree(player, function (child) {
      if (isClickable(child)) {
        preventMultipleClicks(child);
      }
    });
  });

  /*** Local functions ***/
  function walkChildrenTree(component, handler) {
    component.children().forEach(function (child) {
      walkChildrenTree(child, handler);
      handler(child);
    });
  }

  function isClickable(component) {
    return typeof component.onClick === 'function';
  }

  function preventMultipleClicks(component) {
    var debouncedClick = debounce(component.onClick, 500, true);
    ['tap', 'click'].forEach(function(evt) {
      component.off(evt, component.onClick);
      component.on(evt, debouncedClick);
    });
  }

  /**
   *  Returns a function, that, as long as it continues to be invoked, will not be triggered.
   *  The function will be called after it stops being called for N milliseconds.
   *  If `immediate` is passed, trigger the function on the leading edge, instead of the trailing.
   */
  function debounce(func, wait, immediate) {
    var timeout;
    return function(evt) {
      var context = this;
      var args = arguments;
      var later = function() {
        timeout = null;
        if (!immediate){
          func.apply(context, args);
        }
      };
      var callNow = immediate && !timeout;
      clearTimeout(timeout);
      timeout = setTimeout(later, wait);
      if (callNow){
        func.apply(context, args);
      }
    };
  }
});
```

I could do a PR to debounce the calls to onClick still seems a bit hacky. 
What do you think??

**Comment by heff** [comment]
@sangatpedas great to hear the issues have been fixed for you!

@carpasse that does feel a bit hacky, and could potentially lead to other bugs. If a touch event and a click event are both firing, it sounds like a preventDefault isn't getting called somewhere we need it to. Either that or Android ignores preventDefault and still fires both. Either way it'd be great to have a full understanding why that's happening before we patch it.

**Comment by carpasse** [comment]
@heff I completely agree we need to investigate this better.

**Comment by gkatsev** [comment]
in v5, we default to native controls in the native android browser (https://github.com/videojs/video.js/pull/2499) which I believe closes this issue.
If there are still problems, we can reopen this issue.
