### ISSUE TITLE
Responsive Sizing

### ISSUE THREAD

**Issue by heff** [videojs/video.js#982]
Responsive sizing is when the player can dynamically change size to fit its container while maintaining the desired aspect ratio. This should be a feature built into video.js and we need to find out the right way to add it. (it's currently possible with additional work or outside libs)

### To finish
- [ ] Tests written  
- [ ] Feature implemented  
- [ ] Docs/guides updated  
- [ ] Example created (e.g. [jsbin](http://jsbin.com/axedog/9999/edit))  
- [ ] Pull request submitted  

Related issues: #771, #359, #384, #925, #983
Also see the [intrinsic ratio example](http://jsfiddle.net/alexbell/Zs5WB/) from @baloneysandwiches

Related Links:
http://alistapart.com/article/creating-intrinsic-ratios-for-video/

The intrinsic ratio method seems like the best approach. In order to make that happen, we need to allow the user to supply the ratio some how. Some potential options:

```
// set a flag and then we calculate the ratio from the width and height
videojs('id', { responsive: true, width: 1600, height: 900 }); // --> ratio = 16:9

// provide a ratio
videojs('id', { aspectRatio: '16:9' });
```
(specific naming TBD)

Video.js would essentially have 2 layout modes, fixed and responsive, and we would probably apply a different class of styles to the player div depending on which was needed.

### Additional considerations
- How this might affect poster sizing
- What happens if width('600') is called on the player when in responsive mode?
- Determining the aspect ratio after the metadata loads from videoWidth/videoHeight. (We don't support this yet with the fixed layout, so should probably be a separate issue.)

### User Stories Draft

Not sure if all of these are valid, but providing possible solutions for each based on the aspectRatio/autoHeight setting.
```
User wants the video to fill width, and specifies an aspect ratio to calculate height
  `videojs({ aspectRatio: '16:9' });`
    -> Add width: 100%, padding-bottom: (9/16)%

User wants the video to fill width, and auto adjust height to match source aspect ratio from metadata
  `videojs({ aspectRatio: 'auto' });`
    Before metadata:
      Use a default aspect ratio, like 2:1 or 16:9
      -> Add width: 100%, padding-bottom: (9/16)%
    After loadedmetadata
      -> update padding to match source aspect ratio

User wants the video to fill height, and specifies an aspect ratio to calculate width?
  I don't think this is a valid user story, or at least I can't think of a real world use case. Video dimensions are rarely taller than wide (though...iPhone videos). Browser windows have restricted widths not heights.

User wants the video to fill both width and height and the video content to fit inside
  This isn't something we need to handle with this story, but we also don't want to get in the way of it
  `vjs-fill` or a similar simple class to add. Don't need an option.
  --> We would just need to add width: 100%, height: 100%.

User wants the video to fill both width and height and the content to cover the space
  See BigVideo.js. Appears to require a good amount of work. Not something we need to get into with this, and probably best handled as a plugin

User wants a fixed width and height
  `videojs({ width: 100, height: 100 });`

User wants a fixed width and specifies an aspect ratio to calculate height
  `videojs({ width: 100, aspectRatio: '16:9' });
  You could just calucalate height here, so this doesn't seem like a priority.
  If we don't allow this, we could assume whenever aspectRatio is used that we set width to 100%. Otherwise we would just manually calculate the other value here.
  When you do set a width, you can't use the intrinsic ratio, because the height percentage is based on the width of the parent element, not the video player width itself.

User wants a fixed width, and auto adjust height to match source aspect ratio from metadata  
  The video element does this, so video.js should if possible.
  `videojs({ width: 100 });`
  We could either have a default aspect ratio that we calculated and set until the metadata is available, or just allow the default height (set on the .video-js class) to be maintained. The former would be cleaner and more inline with the video element, but would take more work.

User wants a fixed height, and auto adjust width to match source aspect ratio from metadata
  The video element does this also, so video.js should if possible
 `videojs({ height: 100 });`

User wants a video tag with no width or height or aspect ratio settings to be viewable
  `videojs({});`
  We could have a default width/height on the main .video-js class. That way it would be overrideable through CSS or through javascript style setting.

User wants to use CSS to manually set width/height
  `videojs({});` CSS set elsewhere
  The main difference between video.js and the video element here is that with the video element, if you set width and height attributes on the tag, they can easily be overridden by CSS. In Video.js we have to take the width/height attributes and apply them through javascript (inline) styles, which makes them only overrideable by using !important. It should atleast be possible to exclude width/height and use CSS manually.
```

**Comment by jbruni** [comment]
I would say that CSS transform is the best implementation choice. Ancient browsers are pre-mobile, and we usually want responsive for mobile environment. I would rather develop a good rock-solid solution using CSS transform, and offer a best-effort solution fallback for stone age browsers.

**Comment by anonym24** [comment]
```
.video-js-responsive-container.vjs-hd {
  padding-top: 56.25%;
}
.video-js-responsive-container.vjs-sd {
  padding-top: 75%;
}
.video-js-responsive-container {
  width: 100%;
  position: relative;
}
.video-js-responsive-container .video-js {
  height: 100% !important; 
  width: 100% !important;
  position: absolute;
  top: 0;
  left: 0;
}
```
hd = 16:9, sd=4:3
```
<div class="video-js-responsive-container vjs-hd">
    <video .... standard videojs code ... >
        ... sources ...
    </video>
</div>
```
http://stackoverflow.com/a/24413783 (Adapted from: http://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php)

That css code works great: http://rmshow.tk/ (example video.js resizing)

**Comment by Someone777** [comment]
I tried the code recommended by anonym24 but it doesn't seem to work with an RTMP source.  The video and the poster image get scaled down to the same size as the height of the player toolbar and, consequently, covered by it.

If I had to guess, the problem is that it can't tell what size the video is and assumes the size is 0.  The stream is actually 720P but I can't find any way to specify this.  Anyone know how to fix that?

**Comment by odev79** [comment]
https://gist.github.com/odev79/6f30981e24123ad7df3c

**Comment by odev79** [comment]
Responsive Sizing

https://github.com/videojs/video.js/issues/982
digitalmoksha commented on 14 Oct 2014

I have tried using the CSS only solution mentioned by @j4k3 on Aug 2. In general, this worked well for me. However, the aspect ratio was somehow thrown off just enough to create extra "space" above/below the video. Could not figure out how to fix that.

The CSS solution is basically the same as outlined in the css-tricks article (as well as other places): Fluid Width Video. In there they put height: 0; in the wrapper, which in this case is the .video-js:afterblock. Adding this closed up the extra space.

.video-js { width:100%!important; height: auto!important; }
.video-js:after { content:'.'; display:block; position:relative; padding:40.1% 0 0; margin:0 0 0 -100%; visibility:hidden; height:0; }

**Comment by mmcc** [comment]
Closed thanks to #1952.

**Comment by SimonEast** [comment]
To save people from reading this enormous thread, can something be added to the README that explains how to implement fluid/responsive sizing?

**Comment by heff** [comment]
@SimonEast wanna help put one together?

**Comment by BioSyntheticDesigns** [comment]
If base video is 1903x965 ...  
adding the same to jQuery(window).resize() makes it even responsiver :D

var windowWidth = $(window).innerWidth();
var sizeRatio = windowWidth/1903;
var videoHeight = 965*sizeRatio;
$(".videocontent").height(videoHeight);

**Comment by jgmio** [comment]
yes @SimonEast : I am missing some real documentation. There isn't even a chapter on how to use data-setup properly and what options are available.

I love the performance of videojs but getting the videos to stay within the my containers is becoming a hassle

**Comment by gkatsev** [comment]
Not really documentation but I wrote a bit about fluid mode here: http://videojs.github.io/blog/Video-js-5-s-fluid-mode-and-playlist-picker/
I also plan on tackling docs soon.

**Comment by jgmio** [comment]
I tried another player but I'm going to give video.js another attempt. Hope I can get it playing nicely

**Comment by jgmio** [comment]
What am I missing? I feel like such a noob atm.

I'm including screenshots of the code and result between videojs with & without fluid. 
But also one of JWplayer

The html
```
<div class="screen" >
     <video>
     </video>
 </div>
```


The css for ".screen"
```
width:24%;
margin:2px;
```
VideoJS { fluid :false }
![videojs_nofluid](https://cloud.githubusercontent.com/assets/11217741/16957740/f17d99ca-4ddd-11e6-802a-220640bd553b.png)
VideoJS { fluid :true}
![videojs_fluid](https://cloud.githubusercontent.com/assets/11217741/16957741/f17ddd72-4ddd-11e6-8696-02f6ae19ce2e.png)
JWplayer
![jwplayer](https://cloud.githubusercontent.com/assets/11217741/16957742/f17defd8-4ddd-11e6-80f7-9fc1db0e7322.png)

**Comment by nebrot** [comment]
Have you included video-jscss, for example http://vjs.zencdn.net/5.10.7/video-js.min.css ?

**Comment by jgmio** [comment]
I'm almost sad that I did include it ;)
Thanks for the suggestion.

**Comment by jgmio** [comment]
A friend came to the rescue. Hopefully I will have time soon to add it to your codebase as a setup option "responsive : true".

Init:

`videojs(....).addClass("video-js");`

css:

```
.video-js {
    height: 0px !important;
    width: 100% !important;
    padding-top: 62.5%; // or find aspect ratio of video, e.g. 16:9 and do calc(B/(A/100) = aspectRatio -> calc(9/(16/100) = 56.25%
}
```
![videojs_morten](https://cloud.githubusercontent.com/assets/11217741/16984937/70f06418-4e7d-11e6-8992-35a509cf2dcf.png)

**Comment by gkatsev** [comment]
you probably also want to call `player.aspectRatio` with `16:9` or something like that or add the `vjs-16-9` class to the player.
