### ISSUE TITLE
Improve default width/height settings

### ISSUE THREAD

**Issue by heff** [videojs/video.js#983]
We have a challenge when trying to mimic the video element with the player div. The video element defaults to 300x150 if no width/height attributes or CSS is applied, but a div defaults to 100% width and zero height, and doesn't respond to width/height attributes. In order to make the div act like the video element and not require width and height, we have to apply a default using CSS.

Currently we're adding the default using the element styles if no width/height is supplied (and no `auto` is used either as in #359). The problem is still that these styles can't be overridden easily, and the `auto` setting isn't valid for width/height.

Talking with @mmcc we may have come up with a better solution: Add the 300x150 default to the video-js class. This would allow it to be overridden more easily, either by custom user styles that follow video-js.css in the dom, or through element styles like it currently does when you do supply a width/height.

So the solution would be to kill the default here:
https://github.com/videojs/video.js/blob/v4.3.0/src/js/core.js#L86

And add it here:
https://github.com/videojs/video.js/blob/v4.3.0/src/css/video-js.less#L672

This would need to be tested in different situations.
- No width/height provided at all
- No width/height provided but set by CSS

**Comment by gkatsev** [comment]
I believe this has been taken care off with the 5.0 update and the defaults and styles classes.
