### ISSUE TITLE
Javascript errors when no Windows Media Player available

### ISSUE THREAD

**Issue by legsak1mbo** [videojs/video.js#984]
When browsing a site that contains videojs on a device with no Windows Media Player - for example an RDP session on an RDS server - a Javascript error is thrown. Unfortunately this stops all javascript on the page. The issue seems to be here:-

```
vjs.Html5.canControlVolume = function(){
  var volume =  vjs.TEST_VID.volume;
  vjs.TEST_VID.volume = (volume / 2) + 0.1;
  return volume !== vjs.TEST_VID.volume;
};
```

...and can be partially resolved with a try/catch block:-

```
vjs.Html5.canControlVolume = function(){
  var volume =  vjs.TEST_VID.volume;
  try {
    vjs.TEST_VID.volume = (volume / 2) + 0.1;
    return volume !== vjs.TEST_VID.volume;
  }
  catch(e) { return false; }
};
```

However, the errors then move to:-

```
var attrs = ['autoplay','preload','loop','muted'];
  for (var i = attrs.length - 1; i >= 0; i--) {
    var attr = attrs[i];
    if (player.options_[attr] !== null) {
      el[attr] = player.options_[attr];
    }
}
```

This throws a "not implemented error" which can be caught with:-

```
try { el[attr] = player.options_[attr]; }
catch(e){}
```

At this point JS on the page begins working again but "Unexpected call to method or property access" is then thrown repeatedly on line 3260. This seems to be caused by the buffered function being called on an interval. We can correct this with:-

```
vjs.Player.prototype.buffered = function(){
 try {
  var buffered = this.techGet('buffered'),
  start = 0,
  buflast = buffered.length - 1,
  end = this.cache_.bufferEnd = this.cache_.bufferEnd || 0;

  if (buffered && buflast >= 0 && buffered.end(buflast) !== end) {
   end = buffered.end(buflast);
   this.cache_.bufferEnd = end;
  }
  return vjs.createTimeRange(start, end);
 }
 catch(e){return false}
};
```

...and

```
vjs.Player.prototype.trackProgress = function(){
 if(this.buffered()){
  this.progressInterval = setInterval(vjs.bind(this, function(){
   if (this.cache_.bufferEnd < this.buffered().end(0)) {
   this.trigger('progress');
   } else if (this.bufferedPercent() == 1) {
   this.stopTrackingProgress();
   this.trigger('progress');
   }
  }), 500);
 }
};
```

At this point we only get one "Error: Unexpected call to method or property access." message in the console and everything works as expected. I'm not sure if it's the best way to address this but it works.

**Comment by DaveVdE** [comment]
I had this issue on Windows 8.1 Enterprise N running IE11 inside a VM on a Mac. I tried the html5test.com site, and it reported none of the video codecs were supported.

**Comment by aariacarterweir** [comment]
This issue is happening again on 4.12.5? Using Saucelabs vm running win7 + IE9? Happening on the video-js website - but copy and pasting the last gist @heff posted fixes the problem.

**Comment by zungaphobia** [comment]
Can confirm the video-js website is not working on an EC2 Windows Server instance with no media player. Console shows the not implemented error on attempting to set volume.
